### ISSUE TITLE
Consecration duration tracking doesn't work

### ISSUE THREAD

**Issue by Shingedo** [Hekili/hekili#1]
The event `UNIT_SPELLCAST_SUCCEEDED` gets fired multiple times during the duration of Consecration, probably on each tick, so the code in [Paladin.lua](../blob/master/Classes/Paladin.lua#L195-L211) does not work as intended.

Also it would be nice if something like `buff.consecration.remains` would not constantly be `3600` like it does right now, but the real expiration.

**Comment by Hekili** [comment]
Investigating!

**Comment by Hekili** [comment]
Will use GetSpellCooldown() to update the internal Consecration calculations.  Fix will be up soon.
