### ISSUE TITLE
Rotation for Holy Paladin

### ISSUE THREAD

**Issue by LoudAC** [Hekili/hekili#100]
Hi. I've recently started playing some Holy Paladin and I would like a priority helper for DPS. I know that this isn't really an issue for people and Ive tried to solve this myself. My experience in this kind of craft is far to limited and I have failed. What I am looking for is similar to how the other specs work. I'm willing to do all the prioritizing myself and then extract that info, but I cant get Hekili to show up at all as Holy.

Either way, this is a great addon and I thank you with all my heart for creating it. My gaming experience would not have been the same without it.

**Comment by Hekili** [comment]
It's something I'm open to working on, but not a huge priority (ha).  Supporting healer specs is not something that I've taken up so far, simply because of the increase to the workload and the tiny, tiny narrow niche it would involve.

Healers that have DPS profiles in SimC are more likely to get supported at some point than the others, but again, this is a low priority project.

**Comment by LoudAC** [comment]
Yea I figured. I know this is a long shot, but if you have any kind of documentation that will help me, Im willing to do some work on this and keep you posted.

**Comment by Hekili** [comment]
Each specialization's abilities have to be modeled (see the Classes folder); even abilities shared between specs have to be reviewed to make sure spell IDs and mechanics match across specs.

A complete HolyPaladin.lua file would be the bare minimum starting point, given there are abilities Holy uses that don't work the way they work for Ret or Prot.

**Comment by LoudAC** [comment]
Yea, that was my starting point as well. I will keep on it. Are you interested in any kind of "advancement" I make or just the complete files? If so, how would you like for me to contact you? If not, no hard feelings at all. I'm not a pro and I get that your creations hold a higher standard.

**Comment by Hekili** [comment]
It wouldn't be the first time that a user contributed a spec module as a starting point.

If you remove all your character's gear and type `/hek skeleton` in game, then use each of your abilities one-by-one (including swapping talents to use each of those), then you'll be able to retrieve a starting module for Holy from `/hekili`.

**Comment by LoudAC** [comment]
Thank you, that's a great tip!

**Comment by Hekili** [comment]
Sure, after that point, all the mechanical stuff comes into play -- does an ability proc a buff, consume a buff, generate a resource, consume a resource, etc.  Does an azerite power change something?  All of that conditional stuff comes into play; look at other spec modules for examples.

**Comment by LoudAC** [comment]
Will do. Considering HolyP only has about 4 abilities that deals damage but a lot of ways to modify them, I think this will be an interesting ride.

**Comment by Hekili** [comment]
How did this turn out?  Is it something you'd like to see rolled into the addon?

**Comment by LoudAC** [comment]
I dont know. It turned out decent. I'm gonna do some more deep diving before releasing it. Thanks for keeping interest.
