### ISSUE TITLE
pool_resource changes impacting Assassination Rogue

### ISSUE THREAD

**Issue by p4nchez** [Hekili/hekili#1000]
Rotation seems stuck on v9.0.5-1.0.2-beta1

looks like in some AOE situations i stucks and want to me to use garrote even if it had CD or recommend me some spells like fan of knives and shows it with red cooldown number

only happend on the latest v9.0.5-1.0.2-beta1 so i guess it come from the "76db465 Fix pool_resource,for_next. - Hekili"

switching back to Hekili-v9.0.5-1.0.1a and it work as it should

snapshot 1
https://pastebin.com/cWyc7s94

snapshot 2
https://pastebin.com/3QwZjnAr

charakter data
https://pastebin.com/jN0xrUWV

ingame
http://wanna.see.my.p4nda.de/ShareX/2021-03-20_00-32-23.gif

**Comment by Hekili** [comment]
You're correct that the pool_resource feature is still not working correctly in the beta release.  I'm working on it again.

**Comment by element221** [comment]
is this pool_resource feature for like pooling enough energy before shiv to spam envenoms so they get buffed from shiv? cause that kind of thing on assasination will be excellent. Also if there is a chance for making something to keep track and tell you to mutilate nearest target while doomblade is equipped so it gets dotted

**Comment by Hekili** [comment]
May be resolved with -beta2.  Reopen if you still have issues.

**Comment by p4nchez** [comment]
seems not fixed :(
and i noticed it looks like happens only if switch to a target that dont have garrote but garrote is on CD because i used it on other target before

testet these versions and all got the same problem
Hekili-v9.0.5-1.0.3-beta1.zip
Hekili-v9.0.5-1.0.2.zip 
Hekili-v9.0.5-1.0.2-beta2.zip

snapshots
https://pastebin.com/KKRmuG5e
https://pastebin.com/rYhpLAnt

latest working version is
Hekili-v9.0.5-1.0.1a.zip

everything after that release have the stuck problem 
let me know if you need anything more from me to nail it down

**Comment by Hekili** [comment]
I looked at your snapshots, which show some new information that I added to snapshots.  It's definitely trying to pool resources when it doesn't need to, but I have more insight into what I need to change to sort that out.  Thanks for the updated snaps.

**Comment by p4nchez** [comment]
testet your latest commit "9bd001c Re-re-refix pool_resource." in v9.0.5-1.0.3
seems fixed 
thx <3

**Comment by Hekili** [comment]
Thanks for confirming!
