### ISSUE TITLE
Keybinding for toggeling class specific

### ISSUE THREAD

**Issue by kolster9** [Hekili/hekili#1002]
Please describe your idea or feature and when it would be useful.
Is it possible to set a keybind to toggle on and off the spec specific toggles.

such as cancel starlord and using starfall in Single Target.

this would be useful for the Council fight, where you want Starfall to be up after frieda dies, and not when phasing niklaus.

**Comment by Hekili** [comment]
You can use macros for this.  See `/hek set`.  I understand the value here, but the challenge with keybinds is that most people are close to their mental limit for # of useful, accessible keybinds already.  If people feel like they need to bind all the things, it can feel stressful.

I'll leave this ticket open in case there are more strong feelings about it, but I am not immediately persuaded to pursue this.
