### ISSUE TITLE
Show a notification when a modified default priority package is updated

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#1003]
I make small modifications to the default priority package to improve it (the improvement is only for "real" gameplay, not for sims, so the SimulationCraft default APL will not include it). My problem is that I loose thise changes every time the default priority package of Hekili is updated.

I do want those updates, so I don't want to create a copy. Manually applying my changes after the default priority package is updated is fine. I just would like to have a notification - e.g. a popup window on login - when a default priority package that was modified is updated (and therefore the modifications are lost).

**Comment by Hekili** [comment]
I find pop-ups at login to be really intrusive, but I also think people get spammed with a lot of text in their chatframe at login so that wouldn't be helpful either.  I'll think about it.

**Comment by cremor** [comment]
What if the user could choose the notification type? E.g. "none", "text message", "popup".

**Comment by Hekili** [comment]
I'm warming up to this idea, but still not sold.  I am so annoyed when half my addons pop-up telling me stuff when I update and log in.

**Comment by cremor** [comment]
How about one of the following possibilities?
- A new setting like I mentioned in my previous comment. The default could be "none"/"disabled". So it would be an explicit opt-in by the user.
- No new setting, but the popup window contains a "never show this again" checkbox/button.

**Comment by cremor** [comment]
I noticed that some of the last few updates (including beta versions) seems to have added text messages on login. Thanks for that!
But I also got that message on a character where I didn't change the default priority. Is this expected?

**Comment by Hekili** [comment]
Yes, it is notifying you that I pushed an update, not that I overwrote your changes.

**Comment by cremor** [comment]
Ok, good enough for me. Thanks!
