### ISSUE TITLE
Feral Druid - Brutal Slash

### ISSUE THREAD

**Issue by Shizukanashi** [Hekili/hekili#1005]
**Describe the Bug/Issue**
Recommends Brutal Slash when having no charges for as long as 7 seconds & being at full energy. I believe the addon is ignoring the fact you have no charges and continues to recommend using it

This issue happens in raid and on training dummies

**To Reproduce**
Attacking a training dummy, follow along with what is recommended you will come across the issue within 15~ seconds after you run out of Brutal Slash charges and it will continue to recommend using it

**Expected behavior**
Brutal slash should not be recomended when you have no charges left for more than a second and sitting at max energy, especially should not be recommending it when you have 7 seconds left till next charge

**Screenshots**
https://i.imgur.com/3nTBn8e.jpg
full energy, full 8 second wait on brutal slash recommended

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/uZW5xVAU

**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/niJCJWKF

**Comment by Hekili** [comment]
Thanks, this report helped and should be resolved in 1.0.3.
