### ISSUE TITLE
Prot Warrior Revenge bug + few suggestions for mitigation

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#1007]
Remodeling mitigation
In default list there are 2 mitigation spells that are recomeding even with no dmg incoming (Shield block when down and ignore pain.
https://i.imgur.com/T3Vs3Sq.png
These two positions will negate position 14 mitigation, and recommending spells like shield block and ignore pain even if no dmg incoming in example "off tanking ", this is waste rage and should be spend on revenge or execute. 

**In my suggestion is just remove it from default list and left only mitigation requirements to use these abilities.** 

3. Revenge remodel 

I suggest adjust rage condition from 70 to 80 , because there are scenarios that you used ignore pain and shield block + revenge and you don't have rage for next ignore pain if big dmg incoming to you. 

4. Ignore pain remodel 

I suggest add extra condition for ignore pain :
" rage > 50 & buff.ignore_pain.down & **incoming_damage_3s > 5000 "**
Sometimes dmg is not to high that need spend rage on ignore pain and only shield block mitigation will be enough, ignore pain should be recommended while big dmg incoming

 
**PUT SNAPSHOT LINK HERE:**

https://pastebin.com/MQE1x3yw

**Comment by mati3464** [comment]
Also i checked Revenge problems. 

Even if rage is 100 and no dmg incoming after disabling shield block and ignore pain from default list, revenge still not recommending because ignore pain down, in WarriorProtection.lua there is a string for this requirements line 736 "if toggle.defensives and buff.ignore_pain.down then return false, "don't spend on revenge if ignore_pain is down" end"

        22.  revenge ( generic - 1 )
        The action (revenge) is unusable at (0.00 + 1.28) because don't spend on revenge if ignore_pain is down.
        Time spent on this action:  0.08ms
        TimeData:Protection Warrior-generic-1:revenge:0.08:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.04

Next problem with revenge is that if you use that ignore pain to meet requirements for revenge ("ignorepain.up" from .lua), while ignore pain is up, hekili still recommending use revenge even if less than 70 rage. 
https://i.imgur.com/Ukz4ZMP.png

This condition is called from generic because there is double Revenge condition. Position 8 and 10, and this need be changed because with this recommendation you wasting rage on revenge and no rage backup for mitigation if dmg start incoming. Also in AOE there is no restriction to spam Revenge 
**Suggestion: remove position 10 from generic and add "rage >= 80" for AOE Revenge ** 

https://i.imgur.com/2E8Ijj0.png

**Comment by mati3464** [comment]
Conclusion:
 
Here is edited profile that i suggest  ( some random website because pastebin detect blocked words )
https://justpaste.it/7pzzn

Also, need edit WarriorProtection.lua and remove line 736
"if toggle.defensives and buff.ignore_pain.down then return false, "don't spend on revenge if ignore_pain is down" end"


After all those fixes, there are no rage capping, good mitigation on m+/raids and everything looking smooth, also solving problem with threat on m+ , because you spend more range on Revenge than spamming ignore pain on small amount incoming dmg.

**Comment by Hekili** [comment]
I may or may not go this route.  It's a pretty standard functionality for the addon to reserve resources for mitigation, since you have to be able to deal with stuff reactively when needed.  Spending down Rage with Revenge puts you at risk of not being able to mitigate.  Maybe I'll make a spec option.  TBD.
