### ISSUE TITLE
[Unholy DK]The problem with the epidemic is when new targets are added.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1008]
**BEFORE SUBMITTING AN ISSUE:**

1.  v9.0.5-1.0.3

**Describe the Bug/Issue**
During the battle with the Generals boss. When the +4 target is added, the addon suggests using the epidemic in rotation without overlapping the Outbreak targets.

**To Reproduce**
I press festering strike-> festering strike-> apocalypse-> combo burst (DT + UB + Covenant ability) and see epidemic. Not outbreak.

**Expected behavior**
When we add new goals to the main one, we must wait until goals without Outbreak are added, and through the main goal, we adjust to adjacent Outbreak, and after only making sure that all goals with Outbreak, press epidemic.

**Screenshots**
https://imgur.com/a/Crw1ei4

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  https://pastebin.com/N7reyFzs

**PUT ISSUE REPORT LINK HERE:**

2. https://pastebin.com/PHppABhZ
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
Please, please. An addon should always check on targets for an outbreak or not. And after this condition, only then do we click epidemic. This must be done for both Outbreak and Unholy blight.

**Comment by Hekili** [comment]
The current Outbreak behavior is consistent with the sim behavior.  I understand that you'd prefer to Outbreak before Epidemic.  Can you do that in a sim and prove it works better than the default?

**Comment by Hekili** [comment]
I did my own quick test in a HecticAddCleave sim and it seems pretty straightforward:

![image](https://user-images.githubusercontent.com/9438134/111926293-a8f5e180-8a82-11eb-9f2a-f03fb79be90d.png)

I'll forward my sim to the SimC devs as well.

**Comment by Hekili** [comment]
My solution is in the new beta.
