### ISSUE TITLE
Ice lance possibly wrongly placed in recommendation 

### ISSUE THREAD

**Issue by LucianDK** [Hekili/hekili#1009]
Using build: v9.0.5-1.0.3

Ive started to notice that Ice lance is pushed seemingly wrongly to recommendations.  I added screenshots of it, where you can see when its properly highlighted, and when its not highlighted with no procs or buffs up in the right corner.  Only seeing a 3 stack Icicles

I added a snapshot right after it

Edit: Hrm, just strikes me its the Winter's chill debuff that is the culprit on the second image, which is not getting highlighted by the addon. Winter's Chill makes your target count as frozen.

[frostsnap.txt](https://github.com/Hekili/hekili/files/6178369/frostsnap.txt)
[Gearsnap.txt](https://github.com/Hekili/hekili/files/6178338/Gearsnap.txt)
![icelancehightlighted](https://user-images.githubusercontent.com/48681832/111920007-e8c1c680-8a8c-11eb-8ff8-d6402233364a.png)
![icelancenothighlighted](https://user-images.githubusercontent.com/48681832/111920319-941f4b00-8a8e-11eb-801d-ad8b2a094c9e.png)

**Comment by Hekili** [comment]
The addon simply respects the built-in highlighting of the ability.  Fingers of Frost highlights Ice Lance on your bar; Winter's Grasp on your target does not.
