### ISSUE TITLE
 rotation does not work correctly dh

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#101]
build: v8.1.5-07
level: 120
class: DEMONHUNTER
spec: havoc

talents: demon_blades
    demonic
    fel_barrage
    felblade
    first_blood
    master_of_the_glaive
    netherwalk

traits: azerite_globules=1
    chaotic_transformation=1
    furious_gaze=2
    gemhide=1
    heed_my_call=1
    overwhelming_power=1
    resounding_protection=2
    revolving_blades=1
    thirsting_blades=2

sets/legendaries/artifacts: none

gear:     ___=1
    ____=1
    _=1
    __=1

Good day for this build, the rotation display does not work correctly. When taking an azerit talent for a pullback, he does not offer to use his eyes, and the dance of blades. He may offer to throw a blade or sometimes a demonic blade is offered.

**Comment by geraint425** [comment]
https://imgur.com/a/J871B4J 
plus simkraftu no fel_rush in rotation.

**Comment by Hekili** [comment]
I don't understand a lot of what you're saying, but please read the priority in the add-on. You'll see an explanation for Fel Rush. You can edit your own copy as you see fit. 

When submitting a ticket, please follow the ticket instructions.
