### ISSUE TITLE
Demonology amount of Wild Imps for Imposion preference getting ignored.

### ISSUE THREAD

**Issue by SCP002** [Hekili/hekili#1010]
**Description:**
Regardless of the value set in Demonology -> Core -> Preferences -> Wild Imps for Implosion, addon suggest to use Implosion only when you have at least 8 (approximately, may be inaccurate) or more wild imps.

**To reproduce:**
1) Open Hekili options.
2) Set Demonology -> Core -> Preferences -> Wild Imps for Implosion to "3".
3) Close Hekili options.
4) Attack grouped training dummies and generate three soul shards.
5) Cast Hand of Gul'dan to summon three Wild Imps.
6) See casting Implosion is not recomended.

**Expected behavior:**
Implosion get recomended respecting the amount of Wild Imps set in preferences.

**Screenshots:**
![preferences](https://user-images.githubusercontent.com/22541678/111922886-8f1dc400-8aad-11eb-8e1c-7d02e951da89.jpg)
![implosion-not-recomended-on-3](https://user-images.githubusercontent.com/22541678/111922887-92b14b00-8aad-11eb-9932-9d4d44b8fdbd.jpg)
![implosion-recomended-on-8](https://user-images.githubusercontent.com/22541678/111922891-9513a500-8aad-11eb-968a-df3e490ec936.jpg)

**The information from the Issue Reporting tab:**
https://pastebin.com/ga4pkZ12

**Snapshot link:**
https://pastebin.com/3geRjtH5

**Comment by Hekili** [comment]
I'm more inclined to remove the feature, as it's not particular relevant any longer.  The newer priority has the optimal imp thresholds in place.
