### ISSUE TITLE
Balance Opener

### ISSUE THREAD

**Issue by HoboJingles** [Hekili/hekili#1011]
Hi,

Currently the best opener for Balance - BOTA - Night Fae with Nature’s Balance would be:

Wrath, Wrath, Surge, Surge, Dots then Celestial, Trinkets, Convoke. 

Currently in the rotation when cooldowns are enabled during single target it is using the cooldowns before the surges and dots. It’s basically using them after the 2x Wrath. 

Is there a possibility that this can be fixed?

I found this data here:

https://www.dreamgrove.gg/balance/2020-12-08-9.0_faq/

Thank you!

**Comment by Hekili** [comment]
Yes, other priorities could be written.  Are you observing a difference between the addon and your sims or a difference between the addon and a guide?  If it's the latter, the solution is for the sim to be built such that it's consistent with the guide (if that is optimal).  When that's done, the addon will be updated to match.

If the addon isn't replicating sim behavior, then a ticket with a snapshot of your opener and a sim of the same character can be put in a ticket and I'll follow-up then.
