### ISSUE TITLE
Balance Druid Performance Issues

### ISSUE THREAD

**Issue by Rogue1337** [Hekili/hekili#1012]
Hey, as stated in Discord i have perfomance issues when playing Balance and using Hekili, other classes run fine. Im posting 2 Snapshots where it happend in a dungeon and the performance dropped drastically. Seems like it happends more frequently when using Starfall.

Character Data:

build: v9.0.5-1.0.3
level: 54 (54)
class: DRUID
spec: balancea

talents: mass_entanglement
    natures_balance
    restoration_affinity
    solstice
    soul_of_the_forest
    stellar_drift
    wild_charge

pvptalents: celestial_guardian
   moonkin_aura
   prickling_thorns

covenant: night_fae

conduits: none

soulbinds: []

sets: none

gear: ashjrakamas_shroud_of_resolve = 1
    brawlers_guild_tabard = 1
    circlet_of_the_enveloping_leviathan = 1
    deathstalkers_treads = 1
    fastened_venombarb_binds = 1
    girdle_of_the_insatiable_maw = 1
    goldtasseled_epaulets = 1
    harlans_loaded_dice = 1
    heart_of_azeroth = 1
    infinitely_divisible_ooze = 1
    seal_of_the_city_watch = 1
    skyterrors_stonehide_leggings = 1
    soul_keepers_spire = 1
    spymasters_wrap = 1
    stylish_green_shirt = 1
    thornwoven_band = 1
    wharf_wardens_gloves = 1

legendaries: none

itemIDs: 155860, 155881, 158075, 159299, 159310, 159328, 162542, 162548, 165473, 167812, 169223, 173054, 173815, 178769, 178819, 178934, 6385

settings: aoe = 3
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

Snapshots:

Snap 1: https://pastebin.com/vXmc8hNe
Snap 2: https://pastebin.com/fmT3Ex8G

**Comment by Hekili** [comment]
1.0.4-beta2 may help address this further.  Let me know if you notice a difference.

**Comment by Rogue1337** [comment]
Will try it out asap! Also reducing the amount of spells recommended from 4 to 3 did help a bit! Thank you again

**Comment by Hekili** [comment]
Let me know if you experience further issues.
