### ISSUE TITLE
Balance Druid - Starfall on single target

### ISSUE THREAD

**Issue by Zardilann** [Hekili/hekili#1013]
Starfall is being suggested for single target when talent "Stellar Drift" is selected and option "Use Starfall in Single-Target with Stellar Drift" is not selected. When selecting another talent, Starfall is not suggested.

I haven't been able to find any recommendations for using Starfall on single target from any other sources.

Issue Report: https://pastebin.com/pZGsRfg4

Snapshot: https://pastebin.com/7ZbLLbZf

**Comment by Hekili** [comment]
Yeah, that's a natural part of the latest priorities whereas Stellar Drift Starfall was previously an addon-specific enhancement.

**Comment by JustinHartline** [comment]
From the Balance APL:

#### Use Starfall with Stellar Drift and no Starlord, when no Starfall is up, you are in Lunar Eclipse or to proc Pulsar when above 90 AsP or adpative swarm has 8+secs remaining or is in flight
actions.st+=/starfall,if=talent.stellar_drift.enabled&!talent.starlord.enabled&buff.starfall.refreshable&(buff.eclipse_lunar.remains>6&eclipse.in_lunar&buff.primordial_arcanic_pulsar.value<250|buff.primordial_arcanic_pulsar.value>=250&astral_power>90|dot.adaptive_swarm_damage.remains>8|action.adaptive_swarm_damage.in_flight)&!cooldown.ca_inc.ready)

From the Add-on:

talent.stellar_drift.enabled[true] & ! talent.starlord.enabled[false] & buff.starfall.refreshable[true] & ( buff.eclipse_lunar.remains[11.09] > 6 & eclipse.in_lunar[true] & buff.primordial_arcanic_pulsar.value[0.00] < 250 | buff.primordial_arcanic_pulsar.value[0.00] >= 250 & astral_power.current[78.00] > 90 | dot.adaptive_swarm_damage.remains[0.00] > 8 | action.adaptive_swarm_damage.in_flight[false] ) & ! cooldown.ca_inc.ready[false]


So, you should stellar drift in that case.

**Comment by Zardilann** [comment]
Thanks for the replies. If it's part of the base rotation, should the option to use it in the rotation then be removed?

**Comment by Hekili** [comment]
Probably, unless I make it an internal condition that overrides that entry, too.
