### ISSUE TITLE
LUA Error.

### ISSUE THREAD

**Issue by Maverick013** [Hekili/hekili#1014]
**Describe the Bug/Issue**
LUA Error When in combat, hekili does not show next combat option. occuring since 1.0.3. rolling back to 1.0.1 works ok

**To Reproduce**
entering combat, will fail mid battle, on differnt keypress

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
build: v9.0.5-1.0.4-beta2
level: 53 (53)
class: ROGUE
spec: assassination

talents: exsanguinate
    iron_wire
    leeching_poison
    master_poisoner
    nightstalker
    poison_bomb
    vigor

pvptalents: none

covenant: kyrian

conduits: none

soulbinds: []

sets: none

gear: ashjrakamas_shroud_of_resolve = 1
    band_of_chronicled_deeds = 1
    boots_of_the_insatiable_maw = 1
    courageous_aspirants_breeches = 1
    deathsnap_hood = 1
    deathsnap_jerkin = 1
    gonk_outrunner_belt = 1
    gonk_outrunner_shoulderguards = 1
    heart_of_azeroth = 1
    misfiring_centurion_controller = 1
    plaguebringers_dirk = 1
    razzashi_tooth_medallion = 1
    seal_of_dathremar = 1
    sparring_trainers_grips = 1
    undercity_tabard = 1
    wristwraps_of_the_insatiable_maw = 1
    zocalo_stabber = 1

legendaries: none

itemIDs: 157915, 157916, 157942, 157945, 158075, 158114, 165610, 165667, 165683, 169223, 173325, 173344, 173349, 173477, 174954, 175626, 45583

settings: aoe = 3
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Assassination
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    envenom_pool_pct = 50
    mfd_points = 3
    mfd_waste = true
    priority_rotation = false
    solo_vanish = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = true

**PUT ERROR MESSAGE(S) HERE:**
Message: Interface\AddOns\Hekili\Hekili.lua:205: bad argument #4 to 'format' (string expected, got nil)
Time: Tue Mar 23 23:12:07 2021
Count: 1
Stack: Interface\AddOns\Hekili\Hekili.lua:205: bad argument #4 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "@Interface\AddOns\Hekili\Hekili.lua"]:205: in function `Debug'
[string "@Interface\AddOns\Hekili\Core.lua"]:1160: in function `GetPredictionFromAPL'
[string "@Interface\AddOns\Hekili\Core.lua"]:840: in function `GetPredictionFromAPL'
[string "@Interface\AddOns\Hekili\Core.lua"]:840: in function `GetPredictionFromAPL'
[string "@Interface\AddOns\Hekili\Core.lua"]:1367: in function `GetNextPrediction'
[string "@Interface\AddOns\Hekili\Core.lua"]:1746: in function `ProcessHooks'
[string "@Interface\AddOns\Hekili\Options.lua"]:10194: in function `MakeSnapshot'
[string "@Interface\AddOns\Hekili\Core.lua"]:1787: in function `ProcessHooks'
[string "@Interface\AddOns\Hekili\UI.lua"]:824: in function <Interface\AddOns\Hekili\UI.lua:689>

Locals: (*temporary) = "%8sAttempted to Pool Resources for Next Entry ( %s ), but the next entry is not usable because %s.  Skipping."
(*temporary) = ""
(*temporary) = "vanish"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Hekili** [comment]
Go ahead and update, should be resolved.
