### ISSUE TITLE
Function Key display

### ISSUE THREAD

**Issue by Nolenkw1** [Hekili/hekili#1015]
key binds does not show function key name (f1, f2, etc..)
build: v9.0.5-1.0.4
level: 49 (49)
class: DEMONHUNTER
spec: vengeance

talents: abyssal_strike
    demonic
    fallout
    fracture
    sigil_of_chains
    spirit_bomb

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: band_of_malornes_chosen = 1
    darksaber_leather_belt = 1
    drogstitch_boots = 1
    drogstitch_bracers = 1
    drogstitch_grips = 1
    eternal_will_of_the_martyr = 1
    explorers_delving_loop = 1
    fashionable_undershirt = 1
    illustrious_guild_tabard = 1
    inherited_cape_of_the_black_baron = 1
    ormguls_bug_sprayer = 1
    stained_shadowcraft_cap = 1
    stained_shadowcraft_pants = 1
    stained_shadowcraft_spaulders = 1
    stained_shadowcraft_tunic = 1
    strong_fishing_pole = 1
    swift_hand_of_justice = 1

legendaries: none

itemIDs: 121684, 121729, 122248, 122254, 122261, 122358, 122361, 122383, 122668, 130292, 130304, 130309, 130312, 131730, 151116, 6365, 69209

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Vengeance
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    infernal_charges = 1

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = true

**Comment by Hekili** [comment]
This is a case where a screenshot would be useful.

**Comment by Nolenkw1** [comment]
Hope this helps, but i have modified my UI with several add-ons.

**Comment by Hekili** [comment]
There is no displayed image in your comment.

**Comment by Nolenkw1** [comment]
Not sure why you don’t see the image, does your mail server strip attachments?  Sending again.

[cid:00E4E90F-EB8D-4F61-8C5E-194D31A1E240]

  Kenneth W. Nolen

Sent from my iPad

On Mar 25, 2021, at 7:53 AM, Hekili ***@***.***> wrote:

﻿

There is no displayed image in your comment.

**Comment by Nolenkw1** [comment]
Just thought, this is a .png file, don’t know if you computer knows it.

  Kenneth W. Nolen

Sent from my iPad

On Mar 25, 2021, at 7:53 AM, Hekili ***@***.***> wrote:

﻿

There is no displayed image in your comment.

**Comment by Hekili** [comment]
It's not my email system, it's GitHub.  If you follow the link back to the ticket, you can paste your screenshot.

**Comment by Nolenkw1** [comment]
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/77912978/112506105-6fabc300-8d5b-11eb-96d3-2ec417aa839a.png">

**Comment by Nolenkw1** [comment]
Ok, sorry, didn’t realize I was locked into using the online mail.  Let me know if I can do more to help.

  Kenneth W. Nolen

Sent from my iPad

On Mar 25, 2021, at 9:21 AM, Hekili ***@***.***> wrote:

﻿

It's not my email system, it's GitHub. If you follow the link back to the ticket, you can paste your screenshot.

**Comment by Hekili** [comment]
This is likely to have more to do with how you've arranged your bars (the order of them) than anything else.  I'm not sure what bar mod you're using, but the easiest solution is to manually set those bindings in /hekili > Abilities.
