### ISSUE TITLE
Unable to find/disable Sinful Aspirants Emblem in 'Gear and Trinkets'

### ISSUE THREAD

**Issue by ravisangha** [Hekili/hekili#1019]
Hello, I do not believe the Sinful Aspirants Emblem (the PvP HP trinket) is in the list of 'Gear and Trinkets'. Was hoping to disable it as it shows up by default in the cooldowns profile. Any help would be appreciated. Thanks : )

**Comment by Hekili** [comment]
All the Emblems are shared under the Gladiator's Emblem.

**Comment by ravisangha** [comment]
Hi, I had looked through what felt like the entirety of the list and couldn't find Gladiator's Emblem or Aspirant's Emblem. The only two Sinful Gladiators badge of Ferocity and Medallion. I have another look through the list however. Thanks regardless for replying

**Comment by ravisangha** [comment]
Update: Found it under Notorious Gladiator Emblem. Thanks for the help, take care and great job on the fantastic addon. Cheers!
