### ISSUE TITLE
Balance Druid Performance Drops

### ISSUE THREAD

**Issue by Rogue1337** [Hekili/hekili#1021]
Hey, me again, after updating to the newest Beta version i did some dungeon and sadly i didnt notice any change to performance drops at all, seems like even im just riding past some mobs and im infight with them the performance starts to drop, i got some Snapshots from an Mists Key i did.

build: v9.0.5-1.0.4
level: 60 (60)
class: DRUID
spec: balance

talents: mass_entanglement
    natures_balance
    restoration_affinity
    solstice
    soul_of_the_forest
    stellar_drift
    wild_charge

pvptalents: none

covenant: night_fae

conduits: conflux_of_elements = 1

soulbinds: [niya]
   grove_invigoration = 1
   run_without_tiring = 1

sets: none

gear: bands_of_the_undergrowth = 1
    brawlers_guild_tabard = 1
    darkmoon_deck_putrescence = 1
    death_gods_signet = 1
    drape_of_inscrutable_purpose = 1
    hood_of_refracted_shadows = 1
    hopebreakers_boots = 1
    lakalis_spire_of_knowledge = 1
    masterful_phaedrum_necklace = 1
    ritual_commanders_ring = 1
    shadebound_gauntlets = 1
    shadebound_vest = 1
    shadebound_waistguard = 1
    stylish_green_shirt = 1
    sunblood_amethyst = 1
    umbrahide_leggings = 1
    undying_chill_shoulderpads = 1

legendaries: balance_of_all_things = 1

itemIDs: 167812, 172250, 172252, 172256, 172318, 173069, 173145, 178702, 178714, 178779, 178781, 178817, 178826, 179355, 183418, 184758, 6385

settings: aoe = 3
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = dual
    potions = false

Snapshot:

https://pastebin.com/2zSAn61W
https://pastebin.com/Kqta4uUh
https://pastebin.com/0HneDwgC
https://pastebin.com/eLAmfaBd

**Comment by Hekili** [comment]
You may want to use toggles to swap between Auto/AOE instead of using Dual mode.  I don't see anything especially egregious in terms of time spent generating recommendations, and I'm not aware of anything that would cause excessive rechecking of recommendations.

In the same way that 4 icons costs more CPU than 2 icons, 2 displays with multiple recommendations costs more CPU time than 1.  I'll continue to explore optimization opportunities in the addon, but at the moment, this looks like the cost of doing business, as we discussed.
