### ISSUE TITLE
Volley missing in Hunter rotation

### ISSUE THREAD

**Issue by xfloggingkylex** [Hekili/hekili#1022]
Volley does not show up in either single target or AoE in the default action lists for 9.0.5-1.0.4.  Not sure if that is intentional but I couldn't get it to trigger and I find it hard to believe there are no scenarios you would want it.

build: v9.0.5-1.0.4
level: 60 (60)
class: HUNTER
spec: marksmanship

talents: double_tap
    explosive_shot
    master_marksman
    natural_mending
    posthaste
    streamline
    volley

pvptalents: none

covenant: kyrian

conduits: enfeebled_mark = 5
   markmans_advantage = 5
   powerful_precision = 5
   resilience_of_the_hunter = 5

soulbinds: [pelagos]
   cleansed_vestments = 1
   combat_meditation = 1
   focusing_mantra = 1
   let_go_of_the_past = 1

sets: none

gear: absonant_constructs_handguards = 1
    antisepticsoaked_dressing = 1
    boneshatter_pauldrons = 1
    dealer_xyexas_cape = 1
    executors_prideful_girdle = 1
    fleshfused_circle = 1
    gormhusk_kilt = 1
    guild_tabard = 1
    instructors_divine_bell = 1
    overcharged_anima_battery = 1
    rattling_deadeye_hood = 1
    ritualists_treasured_ring = 1
    spatial_rift_striders = 1
    tortured_assistants_bindings = 1
    trailspinner_pendant = 1
    triumphant_combatants_chainmail = 1
    xy_cartel_crossbow = 1

legendaries: serpentstalkers_trickery = 1

itemIDs: 172327, 178707, 178738, 178767, 178794, 178843, 178869, 179345, 179348, 179349, 180105, 180116, 181416, 183037, 184842, 44694, 5976

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Marksmanship
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    trueshot_vop_overlap = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Please follow the ticket instructions.  If you have an issue with recommendations, you need to post a snapshot (*see instructions*) when it's happening.

Volley does appear in the priority for Marksmanship.

**Comment by xfloggingkylex** [comment]
My apologise, first time submitting any kind of bug report.  Below is the snapshot just sitting in town where Volley is normally the 4th recommended use, but since 1.0.4 never comes up for my setup.

https://pastebin.com/BDAxYBve

**Comment by Hekili** [comment]
```
35.  volley ( st - 12 )
The action (volley) is usable at (3.55 + 1.33).
 - the action is ready before the current recommendation (at +1.33 vs. +60.00).
List ( st ) called from ( Marksmanship:default:9 ) would PASS at 1.33.
active_enemies[1.00] < 3
 - this entry's criteria FAILS: ( buff.resonating_arrow.up[false] | ! covenant.kyrian[true] | talent.lethal_shots.enabled[false] ) & ( buff.precise_shots.down[false] | ! talent.chimaera_shot.enabled[false] | active_enemies[1.00] < 2 )
12.335668298649 - true
There are 1 recheck events.
Rechecking stopped at step #1.  The recheck ( 13.66 ) isn't ready within a reasonable time frame ( 10s ).
Time spent on this action:  0.40ms
```

The conditions for Volley have changed in single-target (same with your sims).

It requires one of:
- Resonating Arrow is up
- You're not Kyrian
- Lethal Shots is talented

And one of:
- Precise Shots is down
- **Chimaera Shot is not talented**
- **There is only 1 enemy**

You would meet the latter criteria but not the former.
