### ISSUE TITLE
Volley not being recommended

### ISSUE THREAD

**Issue by xfloggingkylex** [Hekili/hekili#1025]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Volley never gets suggested in Single Target or AoE mode.  Prior to 1.0.4 even sitting in town it would be recommended 4th on my Kyrian hunter.

**To Reproduce**
Be on 1.0.4.  I am not sure if it is something I am wearing, or my Covenant I cannot get Hekili to recommend Volley.  On 1.0.3 it was recommended on cooldown.  Easy to replicate by rolling back to 1.0.3 and reload the priority pack from default.

**Expected behavior**
Volley should be and always has been recommended practically on cooldown, and while idling in town has been 4th recommended for as long as I can remember.  It doesn't matter if I am dungeon with 10+ mobs, it just never shows Volley.

**Screenshots**
1.0.4 town idle
![image](https://user-images.githubusercontent.com/81341785/112478959-e4c2cc80-8d4a-11eb-93ba-2489175fab52.png)

1.0.3 town idle
![image](https://user-images.githubusercontent.com/81341785/112479105-16d42e80-8d4b-11eb-9a46-9b70c8902df9.png)

1.0.2 town idle 
![image](https://user-images.githubusercontent.com/81341785/112479259-3ec39200-8d4b-11eb-9073-a1eadeb03a77.png)

Snapshot pastebin in 1.0.4 with Volley missing.

https://pastebin.com/KiwS7gPv

Here is the snapshot from AoE w/ CDs on.  Still no Volley even though in a 5 man 5 min fight it should be ~%8.5 total DPS.
https://pastebin.com/c7YNsMfR

**Comment by xfloggingkylex** [comment]
Sorry for the previous ticket, I hope this gives you the info needed.  If there is anything else you need please let me know, I can grab a snapshot of 1.0.3 if that helps to see what is preventing Volley from actually being shown.

**Comment by xfloggingkylex** [comment]
Crap and I just realized you replied in the other closed ticket.  

Interesting, so for Kyrian hunters, volley is a DPS loss?

> ```
> 35.  volley ( st - 12 )
> The action (volley) is usable at (3.55 + 1.33).
>  - the action is ready before the current recommendation (at +1.33 vs. +60.00).
> List ( st ) called from ( Marksmanship:default:9 ) would PASS at 1.33.
> active_enemies[1.00] < 3
>  - this entry's criteria FAILS: ( buff.resonating_arrow.up[false] | ! covenant.kyrian[true] | talent.lethal_shots.enabled[false] ) & ( buff.precise_shots.down[false] | ! talent.chimaera_shot.enabled[false] | active_enemies[1.00] < 2 )
> 12.335668298649 - true
> There are 1 recheck events.
> Rechecking stopped at step #1.  The recheck ( 13.66 ) isn't ready within a reasonable time frame ( 10s ).
> Time spent on this action:  0.40ms
> ```
> 
> The conditions for Volley have changed in single-target (same with your sims).
> 
> It requires one of:
> 
> * Resonating Arrow is up
> * You're not Kyrian
> * Lethal Shots is talented
> 
> And one of:
> 
> * Precise Shots is down
> * **Chimaera Shot is not talented**
> * **There is only 1 enemy**
> 
> You would meet the latter criteria but not the former.

If it only needs 1 from each group, I am meeting them so I am not sure why.  Idling in town I clearly have Resonating Arrow available, and do not have precise shots on (haven't attacked recently).  It doesn't matter if its single target or AoE, nothing I do, no skills I use brings Volley into the recommendations.

**Comment by xfloggingkylex** [comment]
Sorry man, new to github and accidentally closed this.  I ran a raidbot in both 1 boss and 5 boss mode and it shows volley as being used with every resonating arrow which is how Hekili recommended it prior to 1.0.4.

1 boss 5 min: https://www.raidbots.com/simbot/report/p1xcNwaqsbQxBDgWjM8z7k

5 boss 5 min: https://www.raidbots.com/simbot/report/nJZ6f87xr7CYnARmdknTkR

**Comment by Hekili** [comment]
You're not interpreting what I said correctly.

> Interesting, so for Kyrian hunters, volley is a DPS loss?

No.  If you're not Kyrian you're probably not concerned with aligning with Resonating Arrow, given that you don't have that ability.

> If it only needs 1 from each group, I am meeting them so I am not sure why. Idling in town I clearly have Resonating Arrow available, and do not have precise shots on (haven't attacked recently).

Not "available" -- Resonating Arrow would need to be *applied*.  *Or* Lethal Shots could be talented.  Or you could not just be Kyrian.  *Plus* one of the second three conditions would need to be met (i.e., Chimaera not talented).

In a one target scenario, with Chimaera Shot not talented:
1.  Use Resonating Arrow.
2.  If Volley is not recommended, take a new snapshot and put it on Pastebin and link it here.

Keep in mind, it's a priority list, so if something higher priority than Volley is recommended, that'd be normal.

**Comment by xfloggingkylex** [comment]
Here you go, single target priority set, cooldowns off (for simplicity, doesn't impact the recommendations shown), and resonating arrow used, still no volley.

https://pastebin.com/AiTfUEmp

> It requires one of:
> 
> * Resonating Arrow is up
> * You're not Kyrian
> * Lethal Shots is talented
> 
> And one of:
> 
> * Precise Shots is down
> * **Chimaera Shot is not talented**
> * **There is only 1 enemy**

I just took the talent for Lethal Shots and it started recommending Volley in both single target and AoE priorities.  Is there a chance that instead of looking for 1 of those 3 first items it is making lethal shots mandatory?  Or just not correctly recording resonating arrow?

Also wanted to include a snapshot of AoE where RA has been used but still no recommendation for Volley:
https://pastebin.com/HsYrvBzC

EDIT: just wanted to add I really appreciate the help, this addon is awesome and I love what you do so I am sorry I am wasting so much of your time.

**Comment by Hekili** [comment]
That snapshot helps.  Resonating Arrow is detected as debuff on the target rather than as a buff (which is how SimC manages it).  I'll make an adjustment to account for the issue.

**Comment by Hekili** [comment]
Try the new beta and see if it works better for you.

**Comment by xfloggingkylex** [comment]
Much better.  Volley disappears from the recommendation for the  second that Resonating Arrow is in flight which is slightly confusing if you're strictly following the primary recommendation, but before you use Resonating Arrow Volley is listed immediately after, and when Resonating Arrow lands Volley is the #1 recommendation again.  Since you explained the logic used I understand why, just something different from 1.0.3, still workable though.

Thanks!

EDIT: Snapshot of recommendations with RA in flight.  Ideally you'd want to use Volley but it isn't recommended since the debuff  isn't hitting the target yet.

https://pastebin.com/kxffBUz0

**Comment by Hekili** [comment]
Tracking Resonating Arrow as a projectile would require more processing, so I'd prefer to avoid it.  Try -beta2 and see if that solution works more smoothly for you.

**Comment by xfloggingkylex** [comment]
Will do as soon as it becomes available.  Again, really appreciate it.

I'm not sure what changed between 1.0.3 and now because that issue didn't exist before, Volley was always recommended after RA even while it was in flight.  I assume the change in logic helps cover another scenario I am missing (like RA missing the target perhaps?) so I trust your judgement on what works best, just trying to provide the feedback as a Kyrian Hunter (there are dozens of us).

**Comment by Hekili** [comment]
The conditions changed and it exposed a difference between the addon and SimC.  It's good that you reported.

**Comment by xfloggingkylex** [comment]
beta2 works fantastic.  Right back to how it has been in the past with Volley always recommended after RA.  Thanks!

**Comment by Hekili** [comment]
Thanks!
