### ISSUE TITLE
Start After Global Cooldown behaviour

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#1026]
Latest beta version of Hekili running.

**Describe the Bug/Issue**
Basically without "Start After Global Cooldown" (Which I believe is now set to default unticked. Where as before it was ticked) being ticked the rotation for example on Balance isn't correctly using cooldowns, as shown in the snapshots. It would be suggesting CA for example after ruby or suggesting CA right after the first Starsurge in the opener. Which would actually change back to Starsurge near the end of the GCD/

Expected behaviour is how it should be with the option "Start After Global Cooldown" ticked. Which used to be default. I reinstalled Hekili and this option was unticked by default. I have posted snapshots with the option ticked which shows the correct rotation. 

https://pastebin.com/semSP3iN - Suggests CA after first Starsurge (Start After Global Cooldown unticked)
https://pastebin.com/FMfHcAuD - Suggests double Starsurge as it should (Start After Global Cooldown ticked)

https://pastebin.com/LWhvxrxJ - Suggesting Ruby after CA (Start After Global Cooldown unticked)
https://pastebin.com/edKs96Et - Suggests the correct rotation and waits for Ruby (Start After Global Cooldown ticked)

https://pastebin.com/v4b3cMdX - Issue report

I'm almost certain this feature was ticked by default in the past. Maybe it's good for some classes but not all to have it unticked? But ticking this option makes it run perfect.

**Comment by Hekili** [comment]
Yeah, I'll revert this, though it's confusing because SimC definitely has different behavior in terms of waiting for the GCD between specs.
