### ISSUE TITLE
Wrath/Starfire issue (not sure if bug?)

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#1027]
Latest version of Hekili

**Describe the Bug/Issue**
Wrath and Starfire, both have numbers I guess? So like 2 casts of wrath to go into Eclipse.
I'm having a issue.  Basically I follow Hekili with opening with double Wrath, but lets say I cast one Wrath, the number is 1. And I move for whatever reason, it then suggests Starfire, even though Wrath has 1 cast to go into next Eclipse.

**To Reproduce**
Follow Hekili in opener. After one cast of Wrath, move.

**Expected behavior**
Shouldn't it be using Wrath again, not sure how moving would make it suggest Starfire instead of using the Wrath is would've used if I didn't move. I can record a video/gif of this if it's not making sense what I am trying to say. Not sure how to desscribe it apart from moving makes it not suggest the second wrath but goes to Starfire for some random reason. Maybe it already thinks its already used Solar Eclipse and uses the condition "eclipse.any_next"

https://pastebin.com/8J2DaBXS - Snapshot on Starfire after moving, after using the first Wrath
https://pastebin.com/v4b3cMdX - Issue report

**Comment by Hekili** [comment]
The opener relies on you (1) being at max range (2) casting before combat starts.  After combat starts, the in-combat priority takes over.
