### ISSUE TITLE
Hunter trueshot recommendation is wrong in newest version

### ISSUE THREAD

**Issue by Williamn88** [Hekili/hekili#1028]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Newest version

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Trueshot is being recommended at the wrong time

**To Reproduce**
Just load the addon and its the second recommendation being recommended after double tap and as a pre-pull kind of thing before first aimed shot

**Expected behavior**
Trueshot should be recommend after stready shot buff is up and wild spirits is cast.
Double checked it with the raidbot sample rotation and the simc apl and it should still be true.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/Hv5U9FzE

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/aPSH0NfK

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Williamn88** [comment]
Just an update. I reset my profile and it was looking normal again.
Thought that was strange as I had not changed anything afaik. So after some digging I could see it was the "start after global cooldown" check box that affected it. When it was unticked trueshot jumped up to the second place and if ticked it was looking normal.

Thought I did try to change that before without seeing anything change in teh suggestions, but maybe I remember it wrong.
At least now I can "fix" and recreate the error with that setting.
So it seems like its the same as the other ticket with boomkin CA being suggested wrongly if unticked.

**Comment by Hekili** [comment]
Start after Global Cooldown is going to be checked again by default.
