### ISSUE TITLE
[Surv hunter] Fast Rotation Shrapnel Bomb.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1029]
**BEFORE SUBMITTING AN ISSUE:**

1.  9.0.5-1.0.5-beta2

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
The rotation is very quickly updated, and the abilities quickly change when you need to use the Shrapnel Bomb. And not only with this ability.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
Due to the rotation of SimcAPL, I would have to use Shrapnel Bomb as soon as it is available to me.

**Screenshots**
It is difficult to capture the problem of flickering in a screenshot.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  https://pastebin.com/bGUaswyM

**PUT ISSUE REPORT LINK HERE:**

2.  https://pastebin.com/ZvfLte9K
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

Please correct the quick change in the rotation of abilities. Since the quick change very much interferes with the further understanding of what needs to be pressed. There are moments that while the ability is being restored, he can blink a rotation ten times and each time offer 2 abilities between himself. While they are on recharge. I thought at first that this problem is due to the fact that I have two different legendary items, but it turned out that the problem does not affect the legendary items I wear.

**Comment by Hekili** [comment]
Sorry, I won't be able to do anything for this ticket.

**Comment by geraint425** [comment]
I looked there Thyminde was updating APL SV can you make a correction? and this will solve the given problem?
