### ISSUE TITLE
 The display of the icon on the Lord Stormsong boss disappears.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#103]
Hello. Yesterday being in 18 keys in Shrine of the Storm. I found a bug. When the battle begins with Lord Stormsong everything goes fine. Until the moment he begins to use the Ancient Mindbender spell. At this point, the Hekili icon disappears, and after exiting the spell, the icon does not appear. And only after some time. And this happens only at the moment when he uses the Ancient Mindbender spell on us. Please correct this moment. I use the version of Hekili v8.1.5-08-beta1.

Hekili edit:  Please make separate tickets for separate issues, and complete the template properly.

**Comment by Hekili** [comment]
Someday, you will submit a proper bug report following the ticket instructions, my friend.

If you would obtain a snapshot when this happens sometime, that would help to resolve it faster.

**Comment by Hekili** [comment]
Also, when this happens, snapshotting should help by also forcing the display to update.  Just pause then unpause and recommendations should return.

**Comment by SUU09** [comment]
Same thing happens to me and I need to disable and then enable to make the addon work again.

**Comment by Hekili** [comment]
8.0.1-beta2 has a couple of different measures added to potentially resolve this issue.

**Comment by Hekili** [comment]
This should be resolved.
