### ISSUE TITLE
assasination rogue flagellation/vendetta

### ISSUE THREAD

**Issue by element221** [Hekili/hekili#1033]
the addon seems to work pretty well, what im requesting is that you can set a toggle option so it desyncs flagellation from vendetta so you dont lose casts over the time of a fight, in some situations casting flagellation on cooldown is better than syncing with vendetta,

keep it up!

**Comment by Hekili** [comment]
I can allow it to desync, if Vendetta is on a long CD (or toggled off).  You might regret it, though!
