### ISSUE TITLE
Havoc DH - Darkglare Boon double Eye Beaming Fury

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#1034]
Latest version of Hekili is running

**Describe the Bug/Issue**
It's using double Eye Beam, instead of using two Annihilations in-between the reset of the Eye Beam. As running Blind Fury, it regens Fury as you're channelling Eye Beam. So basically it's just sitting at 120 Fury the entire time instead of spending Fury on for example Annihilation between the casts.

**To Reproduce**
Equip legendary Darkglare Boon and follow the rotation that Hekili suggests and hope for Legendary proc after Eye Beam.

**Expected behavior**
According to Sims it is using double Annihilation after Eye Beam as usual with normal rotation, then going into the Eye Beam that was reset, I assume this is so it's not capping on fury so much. Where as current behaviour I am staying at 120 Fury due to it double Eye Beaming.

**Screenshots**
![Eye Beam](https://user-images.githubusercontent.com/75596862/113183941-887d1280-924c-11eb-944e-09d21055c7b6.png)

Issue Report - https://pastebin.com/y2q3g06B

Snapshot - https://pastebin.com/TAPKmrZE

https://www.raidbots.com/simbot/report/whr3fL1KqPpYgJSmHCVSKP 
Here is a sim (not my character but basically the same Sample Ability Log, I'd rather not have my character on here)

Please let me know if you require more information.

**Comment by Smudgiee** [comment]
I just tried the updated simc version. I know you're not supposed import as it can mess. But I just wanted to test and the newest simc version of Havoc seems to have been fixed.

**Comment by Smudgiee** [comment]
Another update. Doesn't seem to be working in the aoe part of the rotation. But I will wait until Hekili is updated with the latest simc changes before posting that?

**Comment by ijoihlhnn** [comment]
havoc dh is fine, the legendary is just pure rng nothing else.

**Comment by Smudgiee** [comment]
> havoc dh is fine, the legendary is just pure rng nothing else.

You misread my post or I completely didn't explain properly. 
That has nothing to do with what I was trying to explain.

**Comment by Hekili** [comment]
Yes, this will be resolved when the next batch of priority updates are uploaded.  Soon.
