### ISSUE TITLE
Boomkin cooldowns 

### ISSUE THREAD

**Issue by wow1989** [Hekili/hekili#1036]
Hekili not recommending convoke or celestial alignment despite both being toggled on

**Comment by jacii9467** [comment]
Snapshot of issue

https://pastebin.com/geknR5z7

**Comment by Hekili** [comment]
Please test the 1.0.6-beta1 and let me know if it is resolved for you.

**Comment by jacii9467** [comment]
Working as expected with beta1. Thank you for quick response.

**Comment by Hekili** [comment]
Thanks!
