### ISSUE TITLE
Warlocks bug Rotation

### ISSUE THREAD

**Issue by Hairydabs** [Hekili/hekili#1037]
**BEFORE SUBMITTING AN ISSUE:**

1. Yes I am currently on Hekili-v9.0.5-1.0.5.zip

 2.  From what I've seen so far, no one has had this issue. I did ask my guild member if he was having the same issue and he was but his addon doesn't even show the rotation bar

**Describe the Bug/Issue**
I'm not too sure whats going on with this update but Hekili has been recommending me to use corruption instead of using malefic rapture and its making me use it like 4-5 times until the next ability and drain soul isnt even showing up in my rotation nor recommending soul rot

![WoWScrnShot_040321_164131](https://user-images.githubusercontent.com/81880803/113492283-654ca000-94a4-11eb-81ef-85ee0fa57d21.jpg)

https://pastebin.com/sNKThw2N

**Comment by FullSol** [comment]
I have the same issue. It's not just malefic rapture it also does not show drain soul. I've uninstalled the addon and reinstalled. I also reset my profile.

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

**Comment by FullSol** [comment]
https://pastebin.com/qdG9yhdZ

**Comment by Hairydabs** [comment]
https://pastebin.com/XUWXYh0v

sorry kind of new to this. not too sure on how long i need to do the rotation for but hopefully this work

**Comment by Demosus1143** [comment]
Same issue, corruption shows repeatedly even when it's applied and not ready to drop off

https://pastebin.com/vER8XTem

**Comment by F074** [comment]
I have the same problem.

**Comment by Hekili** [comment]
Please try the new beta build and let me know if you still have issues.

**Comment by Hairydabs** [comment]
So I switched it to beta and keeps happening. corruption shows still

https://pastebin.com/nMk0HZkZ

**Comment by FullSol** [comment]
Working for me now.

**Comment by Smudgiee** [comment]
Can confirm, fixed

**Comment by Hairydabs** [comment]
can confirm as well. thanks boss!

**Comment by Hekili** [comment]
Thanks for confirming!

**Comment by Stephiegee** [comment]
Has anyone run into an issue where Hekili conflicts with WOW and will not allow a warlock to res a party member using soulstone?
I can soulstone myself or another PRIOR to combat, but if the member dies during the dungeon, addon must be disabled to carry out res on them. Im new and really like the addon. :))

**Comment by Hekili** [comment]
Hi Stephiegee, this is a ticket from 9 months ago that is closed.  You can open a new ticket if you have an issue, but there's no reason the addon would prevent you from soulstoning in combat.  In fact, I've played Warlock a lot and not had this issue.  If another addon is interacting with this addon, it might not be implemented in a safe way to prevent "taint."

If you submit a ticket, make sure to use the "bug" ticket and follow the instructions to collect error messages.

**Comment by Stephiegee** [comment]
Thank you for the reply.
