### ISSUE TITLE
BUG: Annihilation outside Demonic/Metamorphosis

### ISSUE THREAD

**Issue by LucianDK** [Hekili/hekili#1039]
build: v9.0.5-1.0.5
BUG: Annihilation outside Demonic/Metamorphosis

Playing a Havoc Demon Hunter, Ive frequently noticed that Hekili will show Annihilation on the queue list without actually being in Demon Form. Additionally Annihilation may show brightly as if having enough fury for it, but actually not having it.
I paused the addon right after getting the issue as described.
[Snap1.txt](https://github.com/Hekili/hekili/files/6254366/Snap1.txt)

Expected result is that it should show Chaos Strike instead of Annihilation, and only being bright when having enough fury.

A shot of me at low fury, Eyebeam is dim as expected. But Annihilation is lit up despite lack of fury, and present despite not being in Demon form. 
![nofurynodemon](https://user-images.githubusercontent.com/48681832/113504927-d55a3500-953b-11eb-9b61-3ebdd3cc296c.png)

**Comment by LucianDK** [comment]
The issue appears to be with the Demonic talent.   Annihilation always appearing when Eye Beam is off cd, but not used yet to trigger Demonic while still not in Demon form that would give you access to Annihilation. And always lit up wether or not you actually have enough fury to use Eye Beam/Annihilation.

**Comment by LucianDK** [comment]
> 
> 
> The issue appears to be with the Demonic talent. Annihilation always appearing when Eye Beam is off cd, but not used yet to trigger Demonic while still not in Demon form that would give you access to Annihilation. Wether or not you actually have enough fury to use Eye Beam/Annihilation.

**Comment by LucianDK** [comment]
Bah, accidentally closed it.

**Comment by Hekili** [comment]
I think you are profoundly misinterpreting what the display is showing you.  It's giving you the next three recommendations, and each is contingent on the previous.

Use Demon's Bite (filler, Fury generation), then Eye Beam (which will trigger Metamorphosis with Demonic), at which point Annihilation is ready to go.
