### ISSUE TITLE
Elemental Shaman missing ability - Call Lightning

### ISSUE THREAD

**Issue by brugrabud-wow** [Hekili/hekili#104]
There is an storm elemental ability called "Call Lightning" that isn't available as a spell/action to use.  It is also missing from the abilities section.

**Comment by Hekili** [comment]
Fill out a proper ticket and supply the required information.

**Comment by Hekili** [comment]
(Call Lightning is auto-cast by your Elemental unless you've explicitly disabled it.  Eye of the Storm is included and used contingent on your pet's Call Lightning buff.)

Do you tend to manually control Call Lightning?

**Comment by Hekili** [comment]
I haven't found a context where manually controlling Call Lightning seems to be a thing, so I'm closing this for now.
