### ISSUE TITLE
Unholy Death Knight Soul Reaper

### ISSUE THREAD

**Issue by Rafa28062013** [Hekili/hekili#1041]
Hello:) The Problem is that Hekili often didnt say when i have to use Soul reaper. the Target is shortly at 35% or he is at 35% and Hekili didnt tell me that i have to use Soul Reaper.

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:** build: v9.0.5-1.0.5
level: 48 (48)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    deaths_reach
    soul_reaper
    unholy_blight
    unholy_pact
    wraith_walk

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: beinschtzer_der_fatalen_konsonanz = 1
    beschlagener_halsreif_des_verdammten = 1
    blutrote_kehlenquetscher = 1
    frostumhllter_plattengrtel = 1
    gelenkschnallen_der_rechtschaffenen_abrechnung = 1
    goldstahlbrustschutz = 1
    krakenschulterstcke = 1
    langer_frostblutumhang = 1
    nie_endender_hunger = 1
    ring_der_eisigen_stimmung = 1
    schienbeinschtzer_des_verrters = 1
    schneeblindschlchter = 1
    talisman_der_tundra = 1
    thorasus_das_steinerne_herz_draenors = 1
    trainingshelm_der_vrykul = 1

legendaries: none

itemIDs: 109894, 112361, 113685, 124236, 124325, 124337, 124634, 127979, 127984, 36377, 37556, 42799, 42864, 42878, 44361

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycleDebuff = festering_wound
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = dual
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
![Screenshot (221)](https://user-images.githubusercontent.com/79382964/113513644-030aa280-956b-11eb-8d61-a8f231d88b53.png)

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
The criteria for Soul Reaper is not that the target is sub-35%.  It's that the target will be sub-35% within 5 seconds and not die before 5 seconds is up.  That way, you actually get the explosion from Soul Reaper.
