### ISSUE TITLE
Sinister Strike instead of Serrated Bone Spike in AoE for Rogue Outlaw

### ISSUE THREAD

**Issue by dariogentiletti** [Hekili/hekili#1044]
For outlaw necro rogue in 2+ targets, Hekili does not suggest to use Serrated Bone Spike on the targets which do not have the DoT. Instead, it just suggests to use Sinister Strike. I believe APL suggests to cast SBS as soon as possible to the targets in cleave if it does not overcap CPs.

**PUT SNAPSHOT LINK HERE:**  https://pastebin.com/ciQgrxST

**Comment by Hekili** [comment]
After you submitted your ticket, I set up Serrated Bone Spike to work with target cycling.  You have to have Recommend Target Swaps enabled for your specialization for that to work (otherwise, the addon is following your preference of not telling you to use abilities on other targets).
