### ISSUE TITLE
Beast Mastery hunter - primal rage

### ISSUE THREAD

**Issue by Lozza290177** [Hekili/hekili#1045]
hi, i'm sure it is a user issue but i cannot get primal rage to feature in my rotation. my configuration data is below....what am i doing wrong please?

build: v9.0.5-1.0.4
level: 53 (53)
class: HUNTER
spec: beast_mastery

talents: animal_companion
    aspect_of_the_beast
    natural_mending
    posthaste
    scent_of_blood
    stomp
    thrill_of_the_hunt

pvptalents: none

covenant: night_fae

conduits: none

soulbinds: []

sets: none

gear: arachnid_cipher_ring = 1
    blighted_margraves_cloak = 1
    composite_crossbow = 1
    desolate_scale_gauntlets = 1
    desolate_scale_vest = 1
    dreamthorn_legguards = 1
    dreamthorn_wristguards = 1
    gormhusk_waistwrap = 1
    heartsbane_charm = 1
    mantle_of_ephemeral_visages = 1
    rattling_deadeye_hood = 1
    ritual_commanders_ring = 1
    sin_stained_pendant = 1
    striders_of_restless_malice = 1
    withergrove_shardling = 1

legendaries: none

itemIDs: 158557, 172242, 172244, 172351, 175665, 175677, 178738, 178745, 178755, 178781, 178821, 178827, 178933, 181424, 183851

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Beast Mastery
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    avoid_bw_overlap = false
    barbed_shot_grace_period = 0.5

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = true

**Comment by p4nchez** [comment]
you have to add it yourself under Priorities> Action List

then you will see the primal rage icon
![2021-04-05_14-57-53](https://user-images.githubusercontent.com/29162840/113576626-30fdee80-9620-11eb-8393-c15ceabcf845.png)

**Comment by Hekili** [comment]
I strongly recommend that you don't do this, but you can -- as panchez noted.  It's also detailed in the FAQ, in terms of how to add something to your priority list.

https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#how-do-i-make-the-addon-recommend-________

Primal Rage is situational for every fight...  It's not a use-on-CD kinda deal.  Bloodlust is omitted by default because popping on CD is just going to make your raid leader mad at you.
