### ISSUE TITLE
No global cooldown animation

### ISSUE THREAD

**Issue by PabSaez** [Hekili/hekili#1047]
Hello,

I installed the addon and I cannot display the animation of the GCD (rotation as in the action bars) or even a timer informing me of the GCD (directly on the spells displayed by Hekili) , I saw in some videos that it was possible but I can not find anything about it on internet so I come to seek help here.

Thank you

**Comment by Smudgiee** [comment]
Are you running Masque? That addon has the ability to remove GCD swirl, maybe that could be the issue? If that is what you're talking about I assume, the GCD swirl

**Comment by Hekili** [comment]
Masque would be the most likely culprit.

**Comment by PabSaez** [comment]
Yes my problem was Masque, thank you :D
