### ISSUE TITLE
Recklessness disappearing 1 box before recommendation (Loop) 

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#1048]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**
While recommendation going on, Recklessness cooldown disappear before recommendation. I saw this today but as i remember good in previous version addon this never happened. https://www.youtube.com/watch?v=1frvlj5g_HE , recommendations are in left top corner video. I turned on Cooldowns durning recommendations and while Recklessness should be at first box , it disappears. 

As far i see, this is something with Lego 

**this entry's criteria FAILS: ! runeforge.signet_of_tormented_kings.equipped[true] & gcd.remains[0.00] = 0 & ( ( buff.bloodlust.up[false] | talent.anger_management.enabled[true] | raid_event.adds.in[3600.00] > 10 ) | target.time_to_die[136.00] > 100 | variable.execute_phase[false] | target.time_to_die[136.00] < 15 & raid_event.adds.in[3600.00] > 10 ) & ( spell_targets.whirlwind[1.00] = 1 | buff.meat_cleaver.up[false] )**

When i take lego off, recommendations are fine 

**Screenshots**
Video: https://www.youtube.com/watch?v=1frvlj5g_HE (Recommendations left top corner )

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/JGgSct8a

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/WJaAGDfW

**Comment by Hekili** [comment]
Recklessness with signet is used off-GCD.  If you have Sync with Global Cooldown enabled, that'll pose a problem.  I'll probably revise it.
