### ISSUE TITLE
Keybinding going outside Hekili box regions

### ISSUE THREAD

**Issue by PaulVlahosCS** [Hekili/hekili#105]
**Describe the Bug/Issue**
The keybinding text that on Hekili extending past the box ends.

**To Reproduce**
1. Be Fury Warrior
2. Update to v8.1.5-08
3. Assign keybinds that involve mousewheel? (not sure if relvant)
4. Turn on Keybind text

**Expected behavior**
The text is supposed to stay inside the box. This bug didnt exist in v8.1.5-07 release. I've been staying on that version hoping 08 would eventually have this bug fixed.

**Screenshots**
v8.1.5-08: https://i.imgur.com/IrPwiwq.png

v8.1.5-07: https://i.imgur.com/OLp3Z1p.png

build: v8.1.5-08
level: 120
class: WARRIOR
spec: fury

talents: carnage
    double_time
    dragon_roar
    endless_rage
    siegebreaker
    sudden_death
    warpaint

traits: azerite_empowered=3
    cold_steel_hot_blood=2
    impassive_visage=1
    infinite_fury=2
    overwhelming_power=3
    resounding_protection=2
    simmering_rage=1
    unbridled_ferocity=1

sets/legendaries/artifacts: none

gear:     dawnbreaker=1
    loa_exultants_shroud=1
    gorecrusted_butchers_block=1
    legplates_of_charged_duality=1
    seal_of_the_city_watch=1
    breastplate_of_the_deathbound=1
    seal_of_the_zandalari_empire=1
    ramping_amplitude_gigavolt_engine=1
    crusade_pummelers=1
    splinterbone_vambraces=1
    last_stand_greatbelt=1
    soulspun_casque=1
    ebon_filigreed_doublet=1
    fluorescent_flora_stompers=1
    cthraxxi_binders_pauldrons=1
    heart_of_azeroth=1

**Comment by Hekili** [comment]
The change is intentional to support texture strings being loaded for ConsolePort users.

That said, I will abbreviate MOUSEWHEEL so it should generally fit.

**Comment by Hekili** [comment]
Should be resolved in 8.1.5-11.
