### ISSUE TITLE
Possible Havoc rotation improvement with Eye Beam and Blind Fury

### ISSUE THREAD

**Issue by LucianDK** [Hekili/hekili#1050]
Would it be possible for the addon to be more mindful of when it recommends casting Eye Beam? I use the Blind Fury talent, and Ive seen the addon recommend Eye Beam even at nearly full on Fury and would thusly waste the massive Fury income.

Eye Beam costs 30 Fury to cast, and generates 40 Fury per second with Blind Fury.

**Comment by LucianDK** [comment]
On the other hand it might conflict with the Darkglare Medallion power, which have a 40% chance to make eye beam not go on cd, and refunding the cst.

**Comment by Hekili** [comment]
You need to start simming your suggestions.  You can test these theories.  In a lot of cases, while it seems wasteful to overcap resources, letting an ability sit off cooldown is often the worse solution.
