### ISSUE TITLE
Enable/Disable Toggle bind

### ISSUE THREAD

**Issue by F074** [Hekili/hekili#1055]
Hey. 

I think it would be great if I had a bind to toggle the general tab "enable" checkmark in stead of going into the option everytime. I tend to enable/disable the addon a lot depending on what I'm doing.

Thanks.

**Comment by Hekili** [comment]
Is the ability to macro this sufficient?

`/hekili disable` and `/hekili enable` should work, and you could put those in macros if you wanted.

**Comment by F074** [comment]
Yeah that works.
