### ISSUE TITLE
[Unholy] Outbreak on new adds relies on Recommend Target Swaps

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1056]
**BEFORE SUBMITTING AN ISSUE:**

1.  build: v9.0.5-1.0.6

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
I click FS-FS-Apoc-UH-Trinket-Spawn adds-epidemic
- See error

**Expected behavior**
I click FS-FS-Apoc-UH-Trinket-Spawn adds-virtual plauge-epidemic.

**Screenshots**

**An outbreak error appears again. Adon again does not recommend using the plague first, and then the epidemic.**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**https://pastebin.com/13HZvvSR**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**https://pastebin.com/Pn7yTmAU**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
You didn't have a rune to Outbreak, but you could Epidemic.

**Comment by geraint425** [comment]
Well, here's a screenshot I attach with what is happening, there is a buff on the main target, there is no on others, and the addon suggests using an epidemic, not an outbreak. https://imgur.com/a/ts4Lqp0
and here's another bug with what the addon suggests to use. https://pastebin.com/yS7e2vtu

**Comment by Hekili** [comment]
This snapshot helps, since you have runes but it didn't recommend Outbreak.  The reason is that I adopted the logic that SimC uses, which relies on Recommend Target Swaps enabled, and you have that turned off.

I think I'd rather have this work without suggesting that you swap targets, so I'll put back in a workaround for it.

**Comment by Hekili** [comment]
This will be in the next release.
