### ISSUE TITLE
Fire Mage Trinket Usage.

### ISSUE THREAD

**Issue by F074** [Hekili/hekili#1058]
Hey Hekili.

I know you hate hearing about fire mage problems, but this one I think seems like a much more minor issue. 

Anyway, I use the trinkets Soul Infuser and Gladiator's Badge of Ferocity. Two on use trinkets( I'm sure you're well aware).
After the opener trinket usage seems fine and normal. The rotation will hold the badge for combust and use soul igniter somewhere after the internal CD comes off and it all works fine. My issue is in the opener. Before combat starts the rotation will suggest I pop Soul Infuser before entering combat. So 5 seconds later when it is time to combust my Badge is on CD. This only happens in the opener and is quite annoying. 

Here is the snapshot: https://pastebin.com/rnShiAyj

**Comment by Hekili** [comment]
Can you post snapshots from the times you're concerned about?  Show me the Soul Infuser recommendation from before entering combat.

**Comment by F074** [comment]
Here:  https://pastebin.com/ARUkDL1u

**Comment by Hekili** [comment]
Can you try v9.0.5-1.0.7-beta2 when it's available and let me know if it looks better?

**Comment by F074** [comment]
I tried one pull on a dummy and the trinket usage is fixed, but fire blast is broken rotation isn't using it anymore. I tried to snapshot it after a relog, but now I'm getting a ton of errors and the addon hangs up (primary icon disappears).

**Comment by Hekili** [comment]
Submit the same snapshot information.

**Comment by F074** [comment]
The rotation will try to activate disciplinary command by casting frost bolt and it will bug out and get errors as soon as I try to cast frost bolt. 

This is the snapshot as it's asking me to cast frost bolt (right before errors):
https://pastebin.com/RzJR1ZGF

This is snapshot for prepull:
https://pastebin.com/4fV986pB

**Comment by Hekili** [comment]
Can you provide the errors as well?

**Comment by F074** [comment]
Here you go: 
https://pastebin.com/gAadyvxV

**Comment by F074** [comment]
Let me know if you need anything else.

**Comment by Hekili** [comment]
Nope, the error message covered it.  -beta3 is coming.

**Comment by Hekili** [comment]
This should be resolved.
