### ISSUE TITLE
ConsolePort variable name requires correction

### ISSUE THREAD

**Issue by foxdenry** [Hekili/hekili#106]
**BEFORE SUBMITTING AN ISSUE:**

_1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version._

I am using v8.1.5-08.

_2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports._

I saw no other issue reports referencing this issue.

**Describe the Bug/Issue**
Support for console port button overlays was recently added, but this change appears to reference a variable that was named something different. It seems "confPortZoom" should actually be "cPortZoom". Since the variable being referenced does not exist, the icons aren't shown, and bugs are constantly thrown.

Code that needs to be updated (s/confPortZoom/cPortZoom/):
- https://github.com/Hekili/hekili/blob/8.0/Events.lua#L1215
- https://github.com/Hekili/hekili/blob/8.0/Events.lua#L1264

Change that introduced this functionality, showing cPortZoom is the intended variable name: https://github.com/Hekili/hekili/commit/3d3a054a99feb79c5d1af503ac9fd94abd9bc920

I verified that change locally, and icons are now visible, and errors are no longer thrown.

**To Reproduce**
- Have ConsolePort and Hekili both installed
- Log on a Druid or Rogue
- Enable Hekili (activate a dps or tank spec)
- See errors in bug sack

**Expected behavior**
Expect icons on hekili ability tiles, and no errors.

**Screenshots**
N/A

**WHEN SUBMITTING AN ISSUE:**
N/A

**PUT ISSUE REPORT LINK HERE:**
N/A
 
**PUT SNAPSHOT LINK HERE:**
Bugsack dump: https://pastebin.com/c8jeF6Un

**PUT ERROR MESSAGE(S) HERE:**
10244x Hekili\Events.lua:1215: attempt to perform arithmetic on field 'confPortZoom' (a nil value)

**Comment by Hekili** [comment]
Fix going out in -09.
