### ISSUE TITLE
[Frost DK] A quick rotation change leads to a drop in runic power during an active BOS.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1060]
**BEFORE SUBMITTING AN ISSUE:**

1.  v9.0.5-1.0.7

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
We make an opener, gain 55+ runic power, and press BOS. When the runic power approached 30rp, the addon quickly began to change the icon from Remorseless Winter to Rime proc, and then altogether changed to Obliterate.

**Expected behavior**
we make an opener, gain 55+ runic power, then if we have 30 rp and have 2 runes, we give priority to Obliterate first in order to gain runic power. And only then everything else. An important priority is not to miss the moment when the meaning of runic power is dropped and BOS has not been canceled.

**Screenshots**
https://imgur.com/a/7YrblYH

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**https://pastebin.com/SKb2srTN**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**https://pastebin.com/HjM6Bd2a**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**I would also like to draw your attention to the fact that when opening for some reason, at the beginning, the addon suggests first using the Covenant ability and then only the opener. I am attaching a screenshot https://imgur.com/a/FtL8KnL with a quick simulation and an opener sequence, and there I did not see the Covenant ability at the beginning of the rotation. Please look at this moment too. Thank you.**

**Comment by Hekili** [comment]
If you want to know why the covenant ability was shown during the opener, you'll have to supply a snapshot from when it happens.

The snapshot you provided re: BoS was not taken during BoS and is recommending Obliterate. You'll need to post snapshots from the correct time per the ticket instructions.

**Comment by geraint425** [comment]
It seems to have succeeded in catching the moment with BOS. https://pastebin.com/uR92V1AG
But I attach about the Abomination Limb offered by the add-on right at the beginning of the rotation. https://pastebin.com/7g5zmV2u

**Comment by Hekili** [comment]
> It seems to have succeeded in catching the moment with BOS. pastebin.com/uR92V1AG

This is recommending Remorseless Winter during Breath of Sindragosa, which seems fine.

> But I attach about the Abomination Limb offered by the add-on right at the beginning of the rotation. pastebin.com/7g5zmV2u

This recommended Abomination Limb because its criteria were met:

> active_enemies[1.00] = 1 & cooldown.pillar_of_frost.remains[0.00] < 3 & ( ! raid_event.adds.exists[false] | raid_event.adds.in[3600.00] > 15 )

It wouldn't have been recommended in that case if there were multiple enemies, or Pillar had more than 3 seconds on CD.

You can see that your sim also used Abom Limb right before Pillar:

![image](https://user-images.githubusercontent.com/9438134/115024296-e2f1b200-9e8d-11eb-9dde-340778c4bb82.png)

Is the problem that the Abom Limb recommendation goes away before you actually use it?  That'd happen if another enemy came into range or if you popped Pillar of Frost.  (That Pillar requirement could be loosened up so that Abom Limb would be used if the Pillar buff is up, but it presently is not like that.)

**Comment by geraint425** [comment]
Wouldn't it be better to use Abom Limb after activating BOS? It turned out that my character had runic power starvation. And as soon as the addon reaches the threshold of 30-35rp, here we have a problem. It's just really hard to catch. I just don't know the addon still takes into account the game delay? Because sometimes I tried to beat the manikin, and it turned out that if I destroyed it myself at the time when it was 30rp, then I managed to hold BOS for another 3 seconds. And there were procs, I kept it for 5-7 seconds. This is if I myself pressed erase in this interval. If we have 1 rune and 2 in just 1 second on the way, the addon begins to quickly change the rotation, and at this moment I miss BOS. Exactly at this moment.
Maybe, of course, someone else from the guys will be able to view it. And maybe I'm really crooked)

**Comment by Hekili** [comment]
If you want to see the priority changed, you'd need to make changes in your sims and show that those result in more DPS.  At this point, all the behavior you reported matches the sim you provided.  Is there something else I'm missing?

**Comment by geraint425** [comment]
I'd rather study this problem in more detail. Because the problem may still arise due to the flimsy responsiveness of the game due to the Internet. If this problem recurs more often, I will write better again.

**Comment by Hekili** [comment]
Sounds good.  If you make adjustments to the priority and show a DPS improvement in sims, link them here (via Raidbots) and you will probably want to share them with the SimulationCraft devs as well.  Take care.
