### ISSUE TITLE
(BM)Pet Based Multi Target Detection Not Working 

### ISSUE THREAD

**Issue by Sol622** [Hekili/hekili#1062]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

Automatic Mode is not working for pet based / nameplate target detection. Its happened twice now and each time in the middle of a raid (my zoning into castle Nathria seems to be the only constant each time) 

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

When my pet is near 2 target it should suggest AOE (Multi Shot) but it is not. Last time the only way i could fix it was to reset my settings in the addon folder.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

https://pastebin.com/FeA3aB9M

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Sol622** [comment]
Update:

I did a setting reset again, and this time its still not working for pet based detection, recent damaged enemies seems to be working though Here is an updated snapsnot

https://pastebin.com/KGnyVpaY

**Comment by Hekili** [comment]
Can you post a screenshot of your target settings and a screenshot of your action bars with the pet ability shown?

**Comment by Hekili** [comment]
I'm testing on a BM hunter myself and haven't had this issue yet.  @Sol622, can you provide the screenshots I asked for when you have a moment?

**Comment by Sol622** [comment]
@Hekili im so sorry, i figured out the issue, I didn't have nameplates on during combat, i must've hit the key by accident to turn them off during raid. im sorry to have wasted your time!

**Comment by Hekili** [comment]
Thanks for letting me know! I'll need to make it easier to catch.
