### ISSUE TITLE
[Surv] Shrapnel Bomb icon does not change after use.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1063]
**BEFORE SUBMITTING AN ISSUE:**

1.  v9.0.5-1.0.7

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
The icon does not change when using Shrapnel Bomb. This is not always repeated, but when there are 2 Charges, this bug appears.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**https://pastebin.com/Errvn08P**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**https://pastebin.com/QQPLtZNU**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**P.S. 
Please look at one more point. When I turn on the Recommend Targets Swaps feature, the Addon suggests using the Kill Command for other targets. And when 3+ targets already have a Kill Command debuff, the addon still recommends changing the target to the Kill Command ability, although the target already has a debuff. Please look at this moment. This, of course, may not be a bug, but I will write it here in every case so as not to spawn threads. https://pastebin.com/cTzmdaec**

**Comment by Hekili** [comment]
> The icon does not change when using Shrapnel Bomb. This is not always repeated, but when there are 2 Charges, this bug appears.

Can you explain what you mean by "the icon does not change"?  The recommendation doesn't change after using the ability?  Or the bomb changes but the addon doesn't reflect a change?  I need more explanation.

> P.S.

If you have another issue to report, submit another ticket.  Stop combining unrelated issues.

**Comment by geraint425** [comment]
The rotation shows the Shrapnel Bomb icon, I click on the Shrapnel Bomb ability, and my icon does not change in the rotation. I was shown the blue Shrapnel Bomb icon, but it did not disappear, but suggests using the blue Shrapnel Bomb again. Although I already had a red Shrapnel Bomb because I used a blue Shrapnel Bomb. 
It simply did not remove the icon, and did not change to a new one, if the rotation offered at the moment to use another Shrapnel Bomb again.

**Comment by Hekili** [comment]
Alright, test fix is in 1.0.8-beta2.

**Comment by geraint425** [comment]
No problems were noticed. Everything seems to be good
