### ISSUE TITLE
 Add a heliki trinket

### ISSUE THREAD

**Issue by Dravor-pixelk** [Hekili/hekili#1064]
Hello,

I am a French player, and I am not at all if you are going to be able to help me. Your addon is very practical and I recommend it a lot to my friends. But I am having a problem with. One day I had to remove all my addons and reinstall heliki. As I was waiting, my profile was not registered but suddenly I cannot add my trinket to the dps rotation that heliki offers me at all. Do you have any idea how to add it? Thank you so much.

**Comment by Hekili** [comment]
I'm sorry, I don't really understand the question.  But if you supply the required ticket information, that'd be a starting point for figuring it out.  And tell me specifically what you want.  What trinket are you having a problem with?  Why do you think you need to manually add something?  Etc.
