### ISSUE TITLE
Problems with FireMage Hekili rotation

### ISSUE THREAD

**Issue by AlienLoveChild** [Hekili/hekili#1065]
Hi, 

I installed yesterday on a recommendation from a friend and I think its great although there are things missing from the rotation workflow i.e. Combustion, Mirror Image and my trinkets are not included at all.  Is this something I need to adjust in the /hekili settings or something else?

Thanks!

build: v9.0.5-1.0.7
level: 60 (60)
class: MAGE
spec: fire

talents: flame_on
    frenetic_speed
    kindling
    living_bomb
    rune_of_power
    searing_touch
    shimmer

pvptalents: none

covenant: night_fae

conduits: cryofreeze = 4
   discipline_of_the_grove = 5
   flow_of_time = 1
   infernal_cascade = 3

soulbinds: [korayn]
   face_your_foes = 1
   get_in_formation = 1
   horn_of_the_wild_hunt = 1
   wild_hunt_tactics = 1

sets: none

gear: charm_of_eternal_winter = 1
    darkmoon_deck_indomitable = 1
    doubtweavers_handwraps = 1
    faewoven_amice = 1
    faewoven_cowl = 1
    faewoven_cuffs = 1
    faewoven_drape = 1
    faewoven_leggings = 1
    faewoven_sandals = 1
    faewoven_sash = 1
    faewoven_tunic = 1
    harp_of_the_sanguine_court = 1
    inscrutable_quantum_device = 1
    kaals_gloomblade = 1
    leafed_banewood_band = 1
    red_swashbucklers_shirt = 1
    rendorei_tabard = 1
    shadowghast_ring = 1

legendaries: disciplinary_command = 1

itemIDs: 157758, 173096, 175581, 175588, 175592, 175597, 175600, 175603, 178856, 178926, 179350, 179570, 179623, 179657, 181708, 183040, 184170, 6796

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    pyroblast_pull = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
You have your cooldowns toggle turned off. See /hekili > Toggles.
