### ISSUE TITLE
Balance Druid cooldowns and covenant not recommended in rotation

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#1066]
Hi,

The cooldown and covenants for Balance Druid is not recommended in rotation.
All toggles are enabled and using the latest version v9.0.5-1.0.7

https://pastebin.com/ZPcR3KNi

build: v9.0.5-1.0.7
level: 60 (60)
class: DRUID
spec: balance

talents: mighty_bash
    natures_balance
    restoration_affinity
    solstice
    soul_of_the_forest
    stellar_drift
    wild_charge

pvptalents: none

covenant: night_fae

conduits: born_anew = 2
   conflux_of_elements = 6
   innate_resolve = 6
   wellhoned_instincts = 5

soulbinds: [niya]
   grove_invigoration = 1
   niyas_tools_burrs = 1
   run_without_tiring = 1
   swift_patrol = 1

sets: none

gear: bleakwing_assassins_grips = 1
    corset_of_the_deft_duelist = 1
    cowled_batwing_cloak = 1
    digested_interrogators_gaze = 1
    fleshfused_circle = 1
    glyph_of_assimilation = 1
    oakheart_bracers = 1
    runetender_shoulderguards = 1
    sapgorger_belt = 1
    stitchfleshs_misplaced_signet = 1
    trailspinner_pendant = 1
    umbrahide_treads = 1
    volatile_shadestitch_legguards = 1
    wakeners_frond = 1
    whizblast_walking_stick = 1

legendaries: balance_of_all_things = 1

itemIDs: 172315, 178699, 178707, 178736, 178760, 178869, 179339, 179772, 181418, 181457, 182989, 183007, 183024, 183034, 184021

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = true
    custom1 = true
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = single
    potions = true

**Comment by Hekili** [comment]
Did you explicitly disable your equipped trinket(s)? It looks like perhaps the trinket sync is failing, which prevented use of Celestial Alignment, which in turn prevents Convoke.

**Comment by SUU09** [comment]
Yes, both trinkets disabled

**Comment by Hekili** [comment]
That's why.  Although I understand that you might not want to see them, so I'll look at a workaround (probably treat disabled trinkets as though they're passive and hide the cooldowns, etc.).

**Comment by SUU09** [comment]
Great! 
Thanks

**Comment by Hekili** [comment]
Testfix in 1.0.8-beta1, which will be out in a few minutes.

**Comment by SUU09** [comment]
It's fixed now, but now I have another issue.

If cooldowns toggle is enabled and covenant toggle is disabled, cooldowns will not show up in rotation.
In order for cooldowns to shows up both cooldowns toggle and covenant toggle should be enabled.

https://pastebin.com/iXivHRgz

**Comment by Hekili** [comment]
Yeah, I can potentially work around that, but the priority is truly written to focus on syncing up, especially with BoAT legendary.

**Comment by Hekili** [comment]
Hmm, it's risky.  Because just because you have CDs enabled and Covenants disabled, you may not want to keep them desynched for the whole fight.  Will continue to think about it.

**Comment by Hekili** [comment]
A test change for letting Convoke desync when you have toggled it off will be in next release.
