### ISSUE TITLE
Fire Mage rotation workflow still not working

### ISSUE THREAD

**Issue by AlienLoveChild** [Hekili/hekili#1068]
Further to your last advise I clicked 'show cool downs' in the toggle so now they show up once cooled down in the cool down section but they are still not appearing in the primary/AOE rotation streams.  I am still not seeing mirror image, combustion, interrupts or trinkets.  I have pasted the up to date settings below. Please advise. 

build: v9.0.5-1.0.7
level: 60 (60)
class: MAGE
spec: fire

talents: blazing_soul
    flame_on
    frenetic_speed
    kindling
    living_bomb
    rune_of_power
    searing_touch

pvptalents: none

covenant: night_fae

conduits: cryofreeze = 4
   discipline_of_the_grove = 5
   incantation_of_swiftness = 5
   infernal_cascade = 3

soulbinds: [niya]
   grove_invigoration = 1
   niyas_tools_poison = 1
   run_without_tiring = 1
   swift_patrol = 1

sets: none

gear: charm_of_eternal_winter = 1
    darkmoon_deck_indomitable = 1
    doubtweavers_handwraps = 1
    faewoven_amice = 1
    faewoven_cowl = 1
    faewoven_cuffs = 1
    faewoven_drape = 1
    faewoven_leggings = 1
    faewoven_sandals = 1
    faewoven_sash = 1
    faewoven_tunic = 1
    harp_of_the_sanguine_court = 1
    inscrutable_quantum_device = 1
    kaals_gloomblade = 1
    leafed_banewood_band = 1
    red_swashbucklers_shirt = 1
    rendorei_tabard = 1
    shadowghast_ring = 1

legendaries: disciplinary_command = 1

itemIDs: 157758, 173096, 175581, 175588, 175592, 175597, 175600, 175603, 178856, 178926, 179350, 179570, 179623, 179657, 181708, 183040, 184170, 6796

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    pyroblast_pull = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
You didn't need to open a new ticket, you can still add to the last one.

Please check out the ticket instructions and include a snapshot with cooldowns enabled (not a screenshot). I'll take a look.

**Comment by AlienLoveChild** [comment]
I posted again as the last one said closed so wasn't sure.  The snapshot is the same as the one above. 

build: v9.0.5-1.0.7
level: 60 (60)
class: MAGE
spec: fire

talents: blazing_soul
    flame_on
    frenetic_speed
    kindling
    living_bomb
    rune_of_power
    searing_touch

pvptalents: none

covenant: night_fae

conduits: cryofreeze = 4
   discipline_of_the_grove = 5
   incantation_of_swiftness = 5
   infernal_cascade = 3

soulbinds: [niya]
   grove_invigoration = 1
   niyas_tools_poison = 1
   run_without_tiring = 1
   swift_patrol = 1

sets: none

gear: charm_of_eternal_winter = 1
    darkmoon_deck_indomitable = 1
    doubtweavers_handwraps = 1
    faewoven_amice = 1
    faewoven_cowl = 1
    faewoven_cuffs = 1
    faewoven_drape = 1
    faewoven_leggings = 1
    faewoven_sandals = 1
    faewoven_sash = 1
    faewoven_tunic = 1
    harp_of_the_sanguine_court = 1
    inscrutable_quantum_device = 1
    kaals_gloomblade = 1
    leafed_banewood_band = 1
    red_swashbucklers_shirt = 1
    rendorei_tabard = 1
    shadowghast_ring = 1

legendaries: disciplinary_command = 1

itemIDs: 157758, 173096, 175581, 175588, 175592, 175597, 175600, 175603, 178856, 178926, 179350, 179570, 179623, 179657, 181708, 183040, 184170, 6796

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    pyroblast_pull = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
That's not a snapshot.

**Comment by AlienLoveChild** [comment]
Then what is if its not a screen shot or that???????

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

**Comment by AlienLoveChild** [comment]
Okay, I did the ALT-SHIFT-P to pause it at a point where I disagreed with the recommendation(s), then I did ALT-SHIFT-{ for the snapshot but when I went to the snapshot page on /hekili there was nothing in there to copy and paste?

**Comment by Hekili** [comment]
You don't need to do both ALT-SHIFT-P and ALT-SHIFT-[.  Either creates a snapshot.

The instructions on the Snapshots tab should be pretty clear.  You'll select which display's snapshot you want and select which snapshot # for that display.  Then click the snapshot box, CTRL+A, CTRL+C.  You can paste a screenshot of that Snapshots tab if you're still having trouble.

**Comment by AlienLoveChild** [comment]
https://pastebin.com/7DAgziFU

**Comment by AlienLoveChild** [comment]
I had to select Primary and 1 in the boxes on the screenshot page or it wouldn't give me the option to Control C

**Comment by Hekili** [comment]
That's still not a snapshot -- it doesn't show the recommendations that were made and why.

1.  Hit Pause.
![image](https://user-images.githubusercontent.com/9438134/115161909-41758680-a06e-11eb-90dd-13d5df7a902e.png)

2.  /hekili > Snapshots
![image](https://user-images.githubusercontent.com/9438134/115161920-53572980-a06e-11eb-8619-8b80bdec76a5.png)

3.  Pick the Primary display (assuming that's what you're concerned with -- if you're worried about Cooldowns and have them configured to show separately, pick the Cooldowns display).

4.  Pick the Snapshot # (presumably, you're taking one snapshot, so pick 1).

5.  Click in the Snapshot box, press CTRL+A (to select all) and CTRL+C to copy.  (If you have CTRL+A or CTRL+C bound to something else inside WoW, that might interfere with copying and pasting.  You'd have to change those bindings to copy.)
![image](https://user-images.githubusercontent.com/9438134/115161947-87324f00-a06e-11eb-88cc-17b1cc1c3dc9.png)

6.  Paste that to Pastebin and link it here.

**Comment by AlienLoveChild** [comment]
https://pastebin.com/vPTnrRJK

**Comment by Hekili** [comment]
Do you have Cooldowns set to show separately?

![image](https://user-images.githubusercontent.com/9438134/115162580-6a981600-a072-11eb-8ae3-8ff32ae521ba.png)

**Comment by Hekili** [comment]
Have you changed any settings in /hekili > Abilities for Combustion?

![image](https://user-images.githubusercontent.com/9438134/115162675-d8dcd880-a072-11eb-9866-ce89e7f5a062.png)

**Comment by AlienLoveChild** [comment]
I set them to show separately after you told me to click 'show cool downs' as they were still not appearing in the recommendations when it was time to use them.   No I didnt touch any settings for combustion.

**Comment by Hekili** [comment]
Uncheck Show Separately.

**Comment by AlienLoveChild** [comment]
Okay tried it out. Works better but still only ever requests to use Mirror Image as an opener and never again.

**Comment by Hekili** [comment]
Yes, that's consistent with your sim, too.

**Comment by AlienLoveChild** [comment]
Ok thanks.
