### ISSUE TITLE
Arcane Mage: only suggesting Arcane Missiles other than at the start of the encounter. 

### ISSUE THREAD

**Issue by mightymcbeast** [Hekili/hekili#1069]
**Expected behavior**
Im no expert at arcane mage atm *obviously using your addon lol. but i do know the basics that you should be using arcane blast to fish for clear casting procs but the addon almost never suggests arcane blast other than at the start of an encounter and then its just straight arcane missles after that.

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/bh15rp6x

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/FFk8HhxS

**Comment by Hekili** [comment]
You have the Arcane Missiles spam setting turned on. Check out your spec options. I believe that's still discussed in class guides as well.
