### ISSUE TITLE
Hunter remains_guess bug

### ISSUE THREAD

**Issue by bje259** [Hekili/hekili#107]
**Describe the Bug/Issue**
Action List entries leveraging the cooldown remains_guess functionality were throwing an error related to query_time being null.
Error text: 2320: attempt to perform arithmetic on global 'query_time' (a nil value)

Potential Fix:
Update lines in the mt_default_cooldown table to include state prefix for query_time

File:State.lua
Line:2320
Current: local reduction = ( query_time - lastCast ) / ( t.duration - t.remains )
Updated: local reduction = ( state.query_time - lastCast ) / ( t.duration - t.remains )
Line:2330
Current: local reduction = ( query_time - lastCast ) / ( t.duration - t.remains )
Updated: local reduction = ( state.query_time - lastCast ) / ( t.duration - t.remains )

**To Reproduce**
Update the Action list using the latest BM APL (this introduces the remains_guess function into the cleave action list for Bestial Wrath)
- On a BM hunter start combat with multiple targets (to trigger the cleave action list) and use Aspect of the Wild so there is a value for lastCast
- Bestial Wrath will no longer show as a recommended action
- View the Bestial Wrath action list item in the cleave action list
- See error for cooldown.aspect_of_the_wild.remains_guess

**Expected behavior**
Action list items leveraging the remains_guess function should continue being recommended after the first use.

Issue Report Link: https://pastebin.com/6KZu6Dxu

**Comment by Hekili** [comment]
Thanks, this will get taken care of in the morning.
