### ISSUE TITLE
Fury warrior Recklessness disappears from suggestions

### ISSUE THREAD

**Issue by mythadon** [Hekili/hekili#1070]
**BEFORE SUBMITTING AN ISSUE:**

1.  v9.0.5-1.0.7

**Describe the Bug/Issue**
while doing the rotation, recklessness is suggested after using rampage which is correct, but it disappears after using rampage

**To Reproduce**
- press any spells until you can see rampage suggested
- you should see rampage and recklessness after it
- press rampage
- See recklessness disappear

**Expected behavior**
recklessness not disappearing.

**Screenshots**
can't provide it of this event.

**WHEN SUBMITTING AN ISSUE:**

1.  tallents = 2-1-1-3-3-3-1

**PUT SNAPSHOT LINK HERE:**  https://pastebin.com/UvdL4F48

**Comment by Hekili** [comment]
You have "Sync with Global Cooldown" enabled while Recklessness is used off-GCD with your current gear.

Uncheck Sync with Global Cooldown in /hekili > Fury > Performance (I think) and you'll be fine.

I'll put a workaround in place as well.

**Comment by mythadon** [comment]
thanks that seems to work!
