### ISSUE TITLE
Assasination rogue Garrote "spam" with subterfuge talent enabled

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#1072]
**BEFORE SUBMITTING AN ISSUE:**

1.  Latest version
2.  Did not find simmilar topic

**Describe the Bug/Issue**
Assasination profile suggests using Garrote every global cooldown while Subterfuge talent is enabled. 
MY THOUGHTS are that it is due silence duration. For some reason when Silence duration is almost down the addon thinks that it is time to refresh Garrote.

**To Reproduce**
Go in Orgrimmar and start hitting PvP maneken.

**Expected behavior**
Do not reccommend Garrote if it is still ticking despite its silence duration.

**Screenshots**
https://prnt.sc/11vijkc

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  Issure reporting tab.

**https://pastebin.com/k6dZrC1c**          

2.  Snapshot
 
**https://pastebin.com/wsPX8Rgn**

3.  No errors detected.

**Comment by Hekili** [comment]
What stealth effect is active in your screenshot?  Your snapshot isn't from the same time.

**Comment by IIeTpoc** [comment]
I did screenshot in 2nd reproduction of this situation as i forgot to do it 1st time. I`ve just done it again and the stealth effect is actually [Subterfuge](https://www.wowhead.com/spell=108208/subterfuge). What i did just hit PvP maneken in orgri with Garrote and it immideatly recommended the 2nd Garrote right away and so i paused and made screenshot

**Comment by IIeTpoc** [comment]
Here are screenshot + issue reporting and a snapshot from another reproduction all from the same situation
https://prnt.sc/11vl2qa

Issue - https://pastebin.com/zJ348V5s

Snapshot - https://pastebin.com/D1me2DKY

**Comment by Hekili** [comment]
Those entries are attempting to replace a low snapshot Garrote with a higher snapshot Garrote.

> What i did just hit PvP maneken in orgri with Garrote and it immideatly recommended the 2nd Garrote right away and so i paused and made screenshot

Did you Garrote from Stealth and immediately get a recommendation to Garrote during Subterfuge?

**Comment by IIeTpoc** [comment]
> Those entries are attempting to replace a low snapshot Garrote with a higher snapshot Garrote.
> 
> > What i did just hit PvP maneken in orgri with Garrote and it immideatly recommended the 2nd Garrote right away and so i paused and made screenshot
> 
> Did you Garrote from Stealth and immediately get a recommendation to Garrote during Subterfuge?

Yes it is exactly what happened. Garrote was recommended then for a 1 gcd another abbility was recommended (but i didnt manage to react and press it) then recommendation immidiately swapped to another garrote despite it was applied like 1 gcd ago

**Comment by Hekili** [comment]
What is your latency?

**Comment by IIeTpoc** [comment]
65ms local 53ms global

**Comment by Hekili** [comment]
About the same as me, to be honest.  I'm not sure why snapshotting the power of the Garrote dot is working for me but not for you.  That's what it's doing -- it's saying that during Subterfuge, you should overwrite a weak Garrote with a strong Garrote.  But your Garrote should be strong if it was just applied from stealth.  There's even a built-in 0.2s buffer for stealth falling off before Garrote that treats it as a buffed Garrote.  Not sure what to do here.  The snapshot definitely thinks you have a weak Garrote applied and wants to override it with a stronger one.

**Comment by IIeTpoc** [comment]
For some reason it happens only in PvP segment of the game not in PvE (PvP maneken also acts as PvP segment)

**Comment by Hekili** [comment]
That's useful information.  I'll experiment and see if I can replicate it with the PvP dummy.

**Comment by Hekili** [comment]
This looks like a PvP dummy issue.  It looks like it reapplies all the debuffs repeatedly during combat.

**Comment by Hekili** [comment]
Yeah, the PvP dummy has 1 maximum health which the addon treats as dead for certain logistical reasons.  I'm adding a workaround.

**Comment by IIeTpoc** [comment]
> Yeah, the PvP dummy has 1 maximum health which the addon treats as dead for certain logistical reasons. I'm adding a workaround.

Oh ty for the investigation)

**Comment by Hekili** [comment]
Fix will be in release going out tonight.
