### ISSUE TITLE
Assasination rogue Envenom use only with 5 combo points (like with Between The Eyes in Outlaw spec)

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#1073]
Hi! Basicly it would be nice to have an option to use [Envenom](https://www.wowhead.com/spell=32645/envenom) only with 5 combo points. It could be usefull with "[System Shock](https://www.wowhead.com/spell=198145/system-shock)" talent.
I tried to do a different Priority but it is so complicated so I was not able to reproduce the same method you used for [Between the Eyes](https://www.wowhead.com/spell=199804/between-the-eyes) in Outlaw.

**Comment by Hekili** [comment]
I won't be doing this without sims showing that it's better than following the sim-tested logic.
