### ISSUE TITLE
[UH-DK] Shows AoE Outbreak when active on unholy blight targets.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1076]
**BEFORE SUBMITTING AN ISSUE:**

1.  v9.0.5-1.0.8-beta2

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

Correct the rotation tracking of the debuff when using unholy blight in an outbreak location. Just to prevent Outbreak from being offered when Unholy blight is active. Only when Unholy blight is on CD, only then an outbreak is offered if there is no debuff on the targets. This bug works very well on Sire Denathrius where many targets spawn instantly and die quickly. It is possible to make a check that if the targets die faster then do not suggest using the debuff on them.

**To Reproduce**
The fight begins with Sire Denathrius Mythic.
I press 2 times Festering strike after Apocalypse.
Then I press trinket> abomination limb> Unholy blight> Dark transformation.
After that I press 1 more time Clawing Shadows to give myself more runic power.
Then we have 20+ targets around the boss. And at this moment my error begins to rotate.
it shows Epidemic for me, I press it, and then Outbreak appears, although there is a buff from Unholy blight on nearby targets.

**Expected behavior**

After I have 20+ targets, and if Unholy blight is active, I should not have Outbreak in the rotation, but there should be an epidemic, and only it, if there is runic power. There should be a check that if Unholy blight was activated, and a debuff was placed on the target from this ability, then Outbreak should not be offered in rotation.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**https://pastebin.com/cq87bJCf**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**https://pastebin.com/GEgwVQ6K**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Going to use the fix in `ffbae0a`.
