### ISSUE TITLE
[Survival] addon not reporting correct usage of leggo "Nessingwary's trapping apparatus"

### ISSUE THREAD

**Issue by Serqlo** [Hekili/hekili#1077]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
When using the legendary "nessingwary's trapping apparatus" my sim tells me that I need to use traps after spending focus on mongoose bite, hekili takes into account that I have the legendary and it recommends to use traps like freezing trap and tar trap, but it shows that I need to use them all in quick succesion defeating the purpose of the buff

**To Reproduce**
-equip the legendary "nessingwary's trapping apparatus"
-attack a single target target dummy

**Expected behavior**
I expect the addon to show when I need the focus regeneration for more mongoose uptime like in the sim: https://www.raidbots.com/simbot/report/8GMzAk2UPTQsXBRnERunY

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:** https://pastebin.com/M5WB8h7v

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**  https://pastebin.com/V97NBRu8

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
There's not a great way to address this, since there's no way to be certain that your trap is actually going to trigger at a particular moment.

I've made it so that `cast_regen` for trap abilities will reflect the initial gain from the legendary, but you'll likely see the other traps recommended briefly when the trap hasn't yet popped.
