### ISSUE TITLE
Keybinds not showing up on the covenants button

### ISSUE THREAD

**Issue by Xiaoyang-Huang** [Hekili/hekili#1080]
**Describe the Bug/Issue**
Keybinds not showing up on the covenants button.

**To Reproduce**
1. Put an covenants ability to your extra action bar. (that is right bottom one for me).
2. bind Ctrl + ` as hotkey
3. reload your game
then you can see there is no keybind indicator on the button 
![1](https://user-images.githubusercontent.com/4454469/115898825-92331800-a490-11eb-82ab-b67066bd2917.png)

**Expected behavior**
But! if you move your covenants ability to main action bar, and move it back, it will shows up:
![2](https://user-images.githubusercontent.com/4454469/115899339-35842d00-a491-11eb-8769-92381abaa5f1.png)

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/szsWxA3c

**Comment by Hekili** [comment]
This is not a real priority; I don't scrape the binding from the extra action button.  I'll take a look at it, though.

**Comment by Xiaoyang-Huang** [comment]
I just found this issue may related to another plugin: 'Bartender4', the keybinds is just back after I disabled BT4

**Comment by Hekili** [comment]
Thanks for the update.  I'll make a note to look at BT4 Covenant button for bindings in the future.
