### ISSUE TITLE
SBS target cycle issue

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#1081]
Lastest verison of Hekili is running

**Describe the Bug/Issue**
Basically from what I am seeing is, two targets it won't suggest to target cycle, to get two bone spikes out. Three targets it will target cycle once to do two bone spikes. It seems to be behind by one at detecting enemies or something is wrong with the aura max/duration. MfD target cycling is working perfect on two targets but not SBS.
I did take a look through the snapshot myself and see "There is only 1 valid enemy for target cycling; canceling cycle." However there was two targets. This was tested on dummies but also happens in a dungeon, I can also snapshot a dungeon if needed.

**To Reproduce**
Go to a dummy or two mobs and follow rotation with Essences (SBS) enabled playing Outlaw

**Expected behavior**
According to sims with two targets or more it will cycle through the enemies when conditions are met.

https://pastebin.com/N22bU1rT - Issue Report (Essences is disabled, yes. But I have changed SBS to use "none")
 
https://pastebin.com/YhRzgQXL - As seen in the snapshot if I am reading it correctly it's saying "There is only 1 valid enemy for target cycling; canceling cycle." However there is two targets where I am standing as you can see it's detecting two nameplates in the snapshot.

EDIT: If I target the enemy myself then it will suggest SBS which makes me think it's something with Cycle.

**Comment by Hekili** [comment]
Good news, I found what was causing the target count to be reduced.  Pending fix.
