### ISSUE TITLE
Slice and Dice 

### ISSUE THREAD

**Issue by Triplehxh** [Hekili/hekili#1083]
I recognized espacially as outlaw rogue that slide and dice is popping up much to early.
Is there any possibility to configure this?
Sometimes is calling "refresh slice and dice" but i am able to do 1-2 more finishers with 5-6 combo points before i really need to refresh and still avoid that it was not active.

**Comment by Hekili** [comment]
Please follow the instructions when submitting a ticket.  Thanks.
