### ISSUE TITLE
There are problems with the rotation of the survival hunter.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1086]
I decided to create this topic, as I have a lot of questions about the rotation of the survival hunter. I'll start in order.

1. When we put on the Wildfire Cluster legendary item, and take the talents 3.1, x, 1, x, 1.2. An interesting thing happens in AOE. If 5+ targets are involved in the battle, then the addon holds the shrapnel bomb for some reason. But when taking this legendary power, we get a huge advantage when we have a very large number of targets. Because the shrapnel bomb has no cap, and it is more profitable for us to press the shrapnel bomb as often as possible, and more often use Carve to quickly restore the shrapnel bomb. But the addon doesn't do that. In fact, the addon does this, it uses only Serpent Sting on 1 target, then Kill Command, and shrapnel bomb only 1 time, after that he presses Carve, and waits for 2 shrapnel bombs to appear. And we are not tapping into the potential of the Wildfire Cluster of legendary power. Please review this rotation in AOE. Ideally, the fight in AOE should start like this (Serpent Sting is used for the maximum number of targets, then we use shrapnel bomb 2 times in a row, then we use Carve) and while we do not have this combination, we use the standard rotation. Well, something like that at this point.

2. Was spotted in single-target combat and when taking on the legendary power of Rylakstalker's Confounding Strikes. The addon does not aim to quickly use a shrapnel bomb. It turned out that I had 1 shrapnel bomb, the addon, as usual, was waiting for the second shrapnel bomb, I decided to press this shrapnel bomb with my hands and it turned out that a 15% chance worked, and I got another shrapnel bomb, and then immediately a shrapnel bomb. But before I had 2 seconds before the rollback shrapnel bomb which the addon was waiting for. And it turned out that the addon missed this point and I could use 3 shrapnel bombs with a 15% chance if I hit faster. In fact, I used only 2 shrapnel bombs because the addon was waiting for a rollback for a long time, and did not take into account the factor that there is a legendary power and there is a 15% chance of getting an additional shrapnel bomb. I understand that this legendary power is an RNG, but if the addon did not wait for the shrapnel bomb to roll back with this legendary power, then it would be possible to increase the damage.

So far, this behavior of the add-on has been noticed in these situations. I also want to make the new legendary power of Nesingwary's Trapping Apparatus and test the playability with a set of talents 1,2, x, 2, x, 2,1 I saw that a person has already written about this problem, but I want to see for myself what exactly. Because this is a legendary power, and such a set of talents gives a huge advantage to 1 target.

**Comment by Hekili** [comment]
Have you simmed your character and identified whether this behavior happens in sims or if it appears to be an addon defect?

**Comment by geraint425** [comment]
I now offer my two simcraft, one on [ST](https://www.raidbots.com/simbot/report/6T72FeuhSKBqAeMYXqifPf), the other on [AOE](https://www.raidbots.com/simbot/report/g7io8Cgf25cFhYz3pQ3kBW). I just checked into the raider manikin, and there were again problems with the sharpnel bomb. If you look at the rotation from sim, then there they are used almost 1 for 1. Sometimes even when two at once. And the addon sometimes did not immediately use the red sharpnel bomb, but waited for the timer to have 3-4 seconds until the next sharpnel bomb. The green sharpnel bomb strictly followed the action that if 1-3 seconds were left until the end of the buff, then it was used. The blue sharpnel bomb could also be used right away, or an addon could just hold it down until the next stack.
