### ISSUE TITLE
2 Issues for Afffliction. Siphon Life and Vile Taint.

### ISSUE THREAD

**Issue by F074** [Hekili/hekili#1087]
Hi, 

These are two completely separate  issues. I just felt it easier to consolidate into 1 ticket let me know if you would rather I separate.

First Issue: Siphon Life priority on the opener. Single Target talents. 

The rotation will simply pop all cds and shard dump BEFORE using siphon life. I thought at first it was waiting for a trinket proc or something, but it happens every time. Top 100 parses indicate this is not ideal. I'm not entirely sure what yuo would want me to snapshot here let me know if it's necessary.

Second Issue: Vile Taint and Soul Rot not lining up and using at the same time. (Like Soul Rot and Phantom) Mythic SLG Talants.

The title pretty much explains this issue. Vile Taint and Soul rot should be popped one after the other for optimal shard dumping. Right now the rotation does not do that. Again let me know what snap shots you might need if any.

Thanks.

**Comment by Hekili** [comment]
You'll need to follow ticket instructions for me to investigate the questions.

**Comment by Hekili** [comment]
I actually managed to investigate a bit anyway.  The Affliction profile is missing a Siphon Life entry.  I'll address it in the next day or two.

**Comment by F074** [comment]
I snapshot an instance when vile taint was suggested, but soul rot was still on CD and wouldn't come up before VT fell off.

Here: https://pastebin.com/sNvzam1v

Let me know if this isn't what you wanted.

**Comment by Hekili** [comment]
The current Affliction simc priority doesn't seem to make a specific effort to sync the two.

**Comment by F074** [comment]
I don't know exactly how simc works. Is it possible those talents are so rarely used that simc doesn't have enough data to base their current assertions? Then again I'm not an expert in warlock by any means. I could be wrong. It just seems that if you COULD line those two up it would be better than not. Let me know what you think.

**Comment by fzarr** [comment]
Was the Siphon Life part of this ticket fixed? It still seems to be happening for me where it will not recommend SL, e.g. in the opening burst window.

**Comment by Hekili** [comment]
It is fixed now -- the update hadn't been published.
