### ISSUE TITLE
Corresponding keybind does not display properly

### ISSUE THREAD

**Issue by LEOMODE** [Hekili/hekili#1088]
**Describe the Bug/Issue**
Currently, one of my skills is bound as SHIFT+4. However, on Hekili sometimes it shows 1, and sometimes it shows S4 which is confusing. I do not have this skill bound on any of my windows. 

**To Reproduce**
It just shows 1 most of the time, and rarely/occasionally S4. I would say about 95/5 ratio. 

**Expected behavior**
Needs to be S4

**Screenshots**
Will add if necessary but I think my statement above is adequate.

**Comment by Hekili** [comment]
It's how your binds/bars are setup.  If the detected bind isn't accurate, you can set it via /hekili > Abilities.
