### ISSUE TITLE
Outlaw rogue Serrated Spike Bones

### ISSUE THREAD

**Issue by pewpewxd** [Hekili/hekili#1092]
It would be great to only recommend using Serrated Spike Bones repeatedly for combo point generation and damage on the boss but not on mob packs. It will waste spikes that can otherwise be used on the different unique targets. Is there a way to achieve that?

**Comment by Hekili** [comment]
Yes, but you'd have to write a custom priority for that (which I don't generally offer support for).

If you want to hold Serrated Bone Spike, you can use your Covenants keybind to toggle it on/off.
