### ISSUE TITLE
Arcane Mage ability, MANA GEM, unable to remove it from suggested rotation skills.

### ISSUE THREAD

**Issue by Phelix84** [Hekili/hekili#1093]
Mana Gem, a conjured item, is unable to be disabled via the abilities list.

Conjured Mana Gem, is, but disabling it does not cancel out the item it creates from appearing on your rotation list.

So, Mana Gem, needs to be put onto the abilities list so it's allowed to be disabled, and not appear on your rotation.

Thanks.

**Comment by Hekili** [comment]
It's in the items list, is it not?

**Comment by Phelix84** [comment]
Maybe im dumb. lol.

**Comment by Phelix84** [comment]
Yup I found it, sorry for the report.
