### ISSUE TITLE
Fury Warrior: Recklessness problem. Bladestorm question

### ISSUE THREAD

**Issue by matfg** [Hekili/hekili#1096]
After downloading the new update i started noticing something unusual. Recklessness never shows up while being out of combat. Only pops up after Rampage for few milliseconds. Also, never shows up after its off cooldown.  
Oddly enough everything works as before without any issues on other warrior characters. Except for my  character main.

Bladestorm question. After the latest update i started seeing this icon whenever i use the ability (screenshot below). Same thing as with Recklessness this doesn't show up whenever using other warrior characters.

**Describe the Bug/Issue**

Recklessness doesn't show up in cooldown list while being out of combat or whenever it is off cooldown. 

**Expected behavior**
Recklessness to always show in cooldown tab whenever its up.

**Screenshots**
Only got screenshot for Bladestorm question. 

https://imgur.com/a/o0IhOWy

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/nMiVbZT6

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/YQUWmRML

**Comment by Hekili** [comment]
> Bladestorm question. After the latest update i started seeing this icon whenever i use the ability (screenshot below). Same thing as with Recklessness this doesn't show up whenever using other warrior characters.

X means cancel.

> Recklessness doesn't show up in cooldown list while being out of combat or whenever it is off cooldown.

It shows up when its conditions are met, which include being used immediately after Rampage for your talents and legendary.

If you have Signet and just used Rampage and:
- Bloodlust is up or Anger Management is talented or adds aren't spawning for a while
- OR target won't die in the next 100 seconds
- OR you're in execute phase
- OR target will die within 15 seconds and adds won't spawn for a while
...AND there's 1 target or Meat Cleaver is up.

In your snapshot, if you'd just used Rampage, you'd have had Recklessness recommended next.
