### ISSUE TITLE
 [Surv] Problem with recommend target swaps and Kill Command

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1097]
**BEFORE SUBMITTING AN ISSUE:**

1.  v9.0.5-1.0.8

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
All this time I have been testing from the beginning to the end of the surv. And I noticed one thing. That when I check recommend target swaps, the Kill Command ability shows that you need to change the target, but there is a debuff from the Kill Command ability on the main and second targets. 

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**
https://imgur.com/a/V3XzJ2x

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**https://pastebin.com/y8dhisjt**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**https://pastebin.com/gmsQv0DU**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
I enabled this option because in AOE I have to use Serpent Sting for the maximum number of targets and maintain the Kill Command debuff. If you do not enable this option, the addon does not offer to use Serpent Sting and Kill Command on other targets in AOE.

**Comment by Hekili** [comment]
I believe this has been fixed.  Can you confirm?

**Comment by geraint425** [comment]
Yes, this problem is fixed thanks
