### ISSUE TITLE
Allow frame to be moveable

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1098]
When the frame is open you can't see the icons to move them around and you can't move the frame.

----------------
build: v9.0.5-1.0.8
level: 56 (56)
class: WARRIOR
spec: fury

talents: bounding_stride
    cruelty
    double_time
    dragon_roar
    massacre
    siegebreaker
    sudden_death

pvptalents: none

covenant: venthyr

conduits: none

soulbinds: []

sets: pocketsized_computation_device = 1

gear: argent_conscripts_wristplates = 1
    ashjrakamas_shroud_of_resolve = 1
    breastplate_of_otherworldly_influence = 1
    briarbane_halberd = 1
    cinderwall_great_mace = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    night_guardian_legguards = 1
    pauldrons_of_unleashed_pride = 1
    pocketsized_computation_device = 1
    purple_martial_shirt = 1
    ring_of_carnelian_and_sinew = 1
    shadowsteel_gauntlets = 1
    shadowsteel_sabatons = 1
    shadowsteel_waistguard = 1
    signet_of_the_false_accuser = 1
    wing_commanders_helmet = 1

legendaries: none

itemIDs: 158075, 167194, 167555, 169223, 171443, 171444, 171448, 174044, 177792, 178060, 178812, 178814, 178820, 178824, 181216, 183566, 183631

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_ww_range = false

toggles: cooldowns = false
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true 
    interrupts = true 
    mode = automatic 
    potions = true

**Comment by N6REJ** [comment]
looks like it would be very simple to add
```lua
local frame = CreateFrame("Frame", "DragFrame2", UIParent)
frame:SetMovable(true)
frame:EnableMouse(true)
frame:RegisterForDrag("LeftButton")
frame:SetScript("OnDragStart", frame.StartMoving)
frame:SetScript("OnDragStop", frame.StopMovingOrSizing)

-- The code below makes the frame visible, and is not necessary to enable dragging.
frame:SetPoint("CENTER")
frame:SetSize(64, 64)
local tex = frame:CreateTexture("ARTWORK")
tex:SetAllPoints()
tex:SetColorTexture(1.0, 0.5, 0, 0.5)
```

**Comment by Hekili** [comment]
Click and drag the configuration UI out of the way and you can click and drag to place things.

**Comment by N6REJ** [comment]
@Hekili tried that it won't move.  I'm using elvui if that makes a difference.
