### ISSUE TITLE
Balance Druid - No Celestial Alignment Recommendation

### ISSUE THREAD

**Issue by howdeh** [Hekili/hekili#1099]
Hello! 

Celestial Alignment is not being recommended. Any assistance as to why? I do not have any Balance trinkets just yet.

build: v9.0.5-1.0.8
level: 60 (60)
class: DRUID
spec: balance

talents: guardian_affinity
    heart_of_the_wild
    natures_balance
    solstice
    soul_of_the_forest
    stellar_drift
    wild_charge

pvptalents: none

covenant: night_fae

conduits: conflux_of_elements = 5
   innate_resolve = 5
   tireless_pursuit = 5
   wellhoned_instincts = 5

soulbinds: [korayn]
   first_strike = 1
   get_in_formation = 1
   horn_of_the_wild_hunt = 1
   wild_hunt_tactics = 1

sets: none

gear: bargasts_leash = 1
    cowled_batwing_cloak = 1
    fleshfused_circle = 1
    gloves_of_phantom_shadows = 1
    gorewrought_stave = 1
    hateful_chain = 1
    miasmalacquered_jerkin = 1
    precisely_calibrated_chronometer = 1
    primeval_souls_ankleguards = 1
    sapgorger_belt = 1
    sin_stained_pendant = 1
    sinful_gladiators_ring = 1
    umbrahide_leggings = 1
    vicious_surge_faceguard = 1
    wicked_flankers_gorget = 1

legendaries: balance_of_all_things = 1

itemIDs: 172318, 175916, 178699, 178827, 178869, 179352, 180106, 181688, 183009, 183019, 183026, 183029, 183034, 184017, 184026

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = false
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false

**Comment by Hekili** [comment]
I'm assuming that you found the Cooldowns toggle.  :)
