### ISSUE TITLE
Hunter BM Support multiple abilities added

### ISSUE THREAD

**Issue by Marakuja** [Hekili/hekili#11]
Hi,

I just want to add after some days of testing the new Hunter.lua, that there are some issues with the hunter.lua file. (had some problems with the multishot prediction in BM)

- the "specializationChanged" hook is present 2 times and doesn't differ between the specs (e.g. potion is defined 2 times)
- counter_shot is added 2 times now
- multishot is also added 2 times, but with different values as BM the costs are 40 focus baseline and MM does some focus regen (3 per enemy hit)

Should I open a new pull request here to come at these topics or are you aware of this and want to do it by yourself?

**Comment by Hekili** [comment]
I think I took care of all of these.  You're always welcome to submit a pull request.
