### ISSUE TITLE
Druid (Balance) - APL Update (Not Urgent)

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#110]
The Druid APL had a minor change on the 2nd April, which is unlucky being you pulled in changes on the 1st of April. It's only a very minor change, so no hurry.

You can see the change here, following by a typo (sort of?) they fixed: https://github.com/simulationcraft/simc/commit/bb0b1bacbe594c4c6fc98eab8deebbeba3c96f85#diff-71114c60f8bbe311a4408957a0c86588
https://github.com/simulationcraft/simc/commit/09e739093c30e19e044a369b9b4678a5961ac709#diff-71114c60f8bbe311a4408957a0c86588

```
build: v8.1.5-10
level: 120
class: DRUID
spec: balance

talents: natures_balance
    restoration_affinity
    shooting_stars
    starlord
    twin_moons
    typhoon
    wild_charge

traits: arcanic_pulsar=1
    azerite_empowered=3
    azerite_globules=1
    blightborne_infusion=1
    dawning_sun=1
    on_my_way=1
    reawakening=1
    self_reliance=1
    streaking_stars=3
    switch_hitter=1
    unstable_flames=1

sets/legendaries/artifacts: none

gear:     seal_of_dathremar=1
    seal_of_the_zandalari_empire=1
    phoenixfire_staff=1
    gloves_of_spiritual_grace=1
    fashionable_undershirt=1
    cowl_of_righteous_resolve=1
    sea_dogs_cuffs=1
    stretched_sinew_waistcord=1
    loa_exultants_shroud=1
    lady_waycrests_music_box=1
    crest_of_paku=1
    mercenary_miners_boots=1
    leggings_of_the_aberrant_tidesage=1
    grongpelt_vest=1
    gorak_tuls_mantle=1
    heart_of_azeroth=1
```

For now personally, I just made a copy of APL and made the change myself so as not to mess with the default one.

Unrelated note, your TTD changes are working well so thank you!

**Comment by Hekili** [comment]
Updated in 11-beta2.
