### ISSUE TITLE
Enhancement Shaman - Potion Support

### ISSUE THREAD

**Issue by larskeizer** [Hekili/hekili#1100]
The rotation of Enhancement shamans does currently not include dps pots (even when turned on in options.) - It'd greatly boost the dps if potions were actually included as any other dps spec

**Comment by Hekili** [comment]
You will need to submit a complete ticket following the ticket instructions.  Potions are included in the Enhancement priority, but I can't tell without the required ticket information which would include a snapshot that shows your settings and the addon's recommendations.
