### ISSUE TITLE
Warlock: Affliction: Impending Catastrophe and CDs without Phantom Singularity issue

### ISSUE THREAD

**Issue by tflo** [Hekili/hekili#1103]
Since recently I often see this error in BugSack:

```
1004x [string "-- Affliction:aoe:12..."]:2: attempt to call a boolean value
[string "-- Affliction:aoe:12
return safebool( (covenant.venthyr and (cooldown.impending_catastrophe.ready or dot.impending_catastrophe_dot.ticking) and cooldown.summon_darkglare.ready and (dot.phantom_singularity.remains>2 or not (talent.phantom_singularity.enabled))) and ((covenant.necrolord or covenant.kyrian or covenant.none) and cooldown.summon_darkglare.remains<2 and (dot.phantom_singularity.remains>2 or not (talent.phantom_singularity.enabled)))(covenant.night_fae and (cooldown.soul_rot.ready or dot.soul_rot.ticking) and cooldown.summon_darkglare.remains<2 and (dot.phantom_singularity.remains>2 or not (talent.phantom_singularity.enabled))) )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Hekili\Core.lua"]:799: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:840: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:1369: in function `GetNextPrediction'
[string "@Hekili\Core.lua"]:1745: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:824: in function <Hekili\UI.lua:689>
```

“Often” here means ‘not regularly but not rarely’.

_I think,_ I started seeing this error when I began to play around with Vile Taint and Sow the Seeds instead of Phantom Singularity.

***

Things I’m observing that _might_ be related to that error:

- Without Phantom Singularity selected, Impending Catastrophe never gets recommended in the rotation.
- Without Phantom Singularity selected, the big CDs (Dark Soul: Misery and Summon Dark Glare) very rarely are recommended. For example, with target dummies or small mobs I never see them recommended, but today I saw them once as I fought an elite mob with some adds

Concerning the second point, it almost seems as if the script was waiting for Phantom Singularity to be casted (which will never happen, since the talent is not selected). It’s weird though that the CD recommendation appeared once today.

With Phantom Singularity selected, nothing of the above does happen. That is, the CDs are recommended regularly, also for small mobs or dummies, and also Impending Catastrophe is recommended.

I just spent 10 minutes hammering on target dummies, in order to further narrow down the occurrence of the error, but… it didn’t appear now.

***

<details>
<summary>Click here for the Hekili “Character Data” info.</summary>

```
build: v9.0.5-1.0.8
level: 60 (60)
class: WARLOCK
spec: affliction

talents: dark_caller
    dark_soul_misery
    demon_skin
    drain_soul
    howl_of_terror
    siphon_life
    vile_taint

pvptalents: none

covenant: venthyr

conduits: accrued_vitality = 5
   focused_malignancy = 5
   rolling_agony = 5
   shade_of_terror = 5

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   familiar_predicaments = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: avowed_arcanists_staff = 1
    chalice_nobles_signet = 1
    court_of_harvesters_tabard = 1
    essence_extractor = 1
    faemoss_amice = 1
    faemoss_bindings = 1
    gorewrought_drape = 1
    grimveiled_robe = 1
    masque_of_the_path = 1
    reinforced_high_collar = 1
    sanctified_guardians_signet = 1
    sincollectors_leggings = 1
    slippers_of_the_leafy_undergrowth = 1
    soulsiphoners_handwraps = 1
    spine_crawler_waistcord = 1
    vial_of_caustic_liquid = 1

legendaries: perpetual_agony_of_azjaqir = 1

itemIDs: 173241, 179282, 181177, 181179, 181218, 181224, 181334, 181420, 181426, 181503, 181638, 181702, 184127, 184133, 184729, 184755

settings: aoe = 3
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0.5
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 7
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Affliction
    petbased = true
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    manage_ds_ticks = false

toggles: cooldowns = true
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = true 
    interrupts = true [separate]
    mode = single 
    potions = false 
```
</details>

***

Please let me know if you need a snapshot or any other additional information.

– Tom

**Comment by Hekili** [comment]
Please provide a snapshot when you think you should be getting a CD recommendation but are not.  See the new ticket instructions for details about snapshots.

**Comment by tflo** [comment]
Here you go:

- [Cooldowns](https://pastebin.com/T31xWdg0)
- [Primary](https://pastebin.com/qHVLyV4P)
 
While making the snapshot, the above mentioned error has _not_ been logged, since I’m unable to reproduce it reliably. Though, the described recommendation anomalies (which might have a cause that is related to the cause of the error) were present.

**Comment by Hekili** [comment]
The error looked like it involved a multitarget scenario.  You had two targets there, but maybe try 3+?

**Comment by tflo** [comment]
Ok, tried with the 5-target swarm dummy, and I can reliably produce the error then. Though, when the error is there, I cannot make snapshots.  (Nothing saved and no snapshot confirmation in console; just the “There are too many errors in your UI.” message.)

Some interesting findings though: The error is triggered differently, depending if Phantom Singularity is selected or not:

- _With Phantom Singularity selected:_ I can open combat and cast any other abilities without error, but the moment I cast Phantom Singularity the error starts counting in BugSack.

- _Without Phantom Singularity selected:_ The error starts counting already when I’m just standing in front of the 5 targets. Without initiating combat or casting anything.

With the 3-target cleave dummy the error does not appear.

**Comment by Hekili** [comment]
This is/was a silly typo error that I'm fixing right now.

**Comment by tflo** [comment]
Oh, glad to hear. Typos are the easiest ones :)

**Comment by Hekili** [comment]
This fix should be live.  Reopen this ticket with new information if you still have the issue.

**Comment by tflo** [comment]
With which version has it gone live? I have 9.0.5-1.0.9a and cannot find anything newer.
