### ISSUE TITLE
Issue with Unholy Death Knight - AOE Setup & AOE Burst

### ISSUE THREAD

**Issue by mikemangu** [Hekili/hekili#1105]
**Describe the Bug/Issue**
When multiple mobs are present to switch to AOE rotation, one of the core abilities, Death and Decay is not being recommended. It seems like it is staying on "Generic" action list and not recommending any of the AOE Burst, particularly not enough Epidemics.

**To Reproduce**

- Get into a multi-mob fight, that last longer than 15 seconds
- Addon picks up multiple mobs, but never recommends Death and Decay
- Since it doesn't recommend Death and Decay it doesn't read that it's ticking and never goes into AOE Burst.

**Expected behavior**

- When the addon reads that there are 3 or more mobs, it should begin AOE Setup call list, and then go into AOE burst until there are only 1 or less than selected "multiple enemies" selected.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

**https://pastebin.com/91WTCjEm**

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
