### ISSUE TITLE
Recommending potions while doing world quests

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1106]
I'm very confused as to whats going on.  It keeps recommending a potion outside of instances ( like raids ) to use my potion.
THE ONLY time it should be recommending potions is during raids.
This is on my balance druid.

**Comment by Hekili** [comment]
Follow the instructions when submitting tickets.

**Comment by N6REJ** [comment]
@Hekili so its too much effort on your part to explain how to prevent this from occuring?

**Comment by Hekili** [comment]
I'll take a look if I get a proper ticket, so I have the information I need to investigate.  It's not a personal attack.
