### ISSUE TITLE
Balance druid rotation nerfed

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1107]
Seems the rotation for the balance druid is all wrong.  I've tried with simc priorities and that didn't help.
it recommends 5 or 6 starfire in a row, same thing with sunfire and wrath.
It should be wrath,wrath, starfire for the opener which it seems to do and then it gets "stuck"
it NEVER seems to throw moonfire & stellar flare into the rotation which should be early on.

**Comment by Hekili** [comment]
Follow the instructions when submitting tickets.

**Comment by N6REJ** [comment]
maybe I just need to NOT use hekili since you want to be so persnickety

**Comment by Hekili** [comment]
Submit a proper and complete ticket, with all the required information, if you'd like me to investigate an issue.  That's all.  Thanks.
