### ISSUE TITLE
Issues with druid recommendations

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1109]
I'm very confused as to whats going on. It keeps recommending a potion outside of instances ( like raids ) to use my potion.
THE ONLY time it should be recommending potions is during raids.
This is on my balance druid.

**WHEN SUBMITTING AN ISSUE:**

build: v9.0.5-1.0.9a
level: 60 (60)
class: DRUID
spec: balance

talents: force_of_nature
    mass_entanglement
    renewal
    restoration_affinity
    solstice
    starlord
    stellar_flare

pvptalents: none

covenant: night_fae

conduits: born_anew = 5
   conflux_of_elements = 5
   innate_resolve = 1
   wellhoned_instincts = 5

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   niyas_tools_burrs = 1
   run_without_tiring = 1

sets: none

gear: bloodoath_signet = 1
    fearless_challengers_leggings = 1
    fleshcrafters_knife = 1
    gloves_of_phantom_shadows = 1
    horde_tabard = 1
    macabre_sheet_music = 1
    mantle_of_manifest_sins = 1
    miasmalacquered_jerkin = 1
    oakheart_belt = 1
    oakheart_crest = 1
    oakheart_mantle = 1
    precisely_calibrated_chronometer = 1
    requiem_chime = 1
    ritualists_treasured_ring = 1
    sinful_aspirants_pendant = 1
    sinful_gladiators_insignia_of_alacrity = 1
    umbrahide_treads = 1

legendaries: balance_of_all_things = 1

itemIDs: 172315, 178120, 178335, 178386, 178789, 178801, 178871, 179768, 179770, 179771, 181631, 183009, 183019, 183026, 183033, 183037, 184024

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = false
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true 
    interrupts = true 
    mode = automatic 
    potions = true 

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

Unable to provide snapshot 
![image](https://user-images.githubusercontent.com/1850089/119994333-21e94c00-bf92-11eb-8ff3-b30857d1ea8e.png)

**PUT ERROR MESSAGE(S) HERE:**
None specified.

I tried getting it to do it again using the training dummies but it didn't do it this time.
It did it twice while fighting mobs in ardenweald.

**Comment by Hekili** [comment]
You can and must provide a snapshot.

**Comment by N6REJ** [comment]
how, it doesn't work.
I showed that in the screenshot

**Comment by Hekili** [comment]
> Click [t]here, press CTRL+A, CTRL+C to copy the snapshot.
> Copy and paste this to pastebin.com and provide the link here.

**Comment by Hekili** [comment]
Additionally, you will need to be sure to take the snapshot when the issue you're concerned about (potion being recommended) is actually happening.  If you provide a snapshot from a different moment, it won't be useful.

**Comment by N6REJ** [comment]
It might take me a few days to make it happen again, idk. didn't do it on the training dummies.  I saw it briefly last night but it went away by the time the next skill came up.

**Comment by N6REJ** [comment]
ok, figured out the snapshot, idk if this is relevant but I just had the same skills show up like 6x in a row.
https://pastebin.com/C8zQZLUQ

**Comment by Hekili** [comment]
Your snapshot shows Starfire and Sunfire, so you didn't take the snapshot when it was recommending a potion, which is the topic of your ticket. 

> I just had the same skills show up like 6x in a row.

Are you expecting Balance not to cast the same spell several times in a row? I can't help if you don't clearly explain the issue you're having and provide data from when you're actually having the problem.

**Comment by N6REJ** [comment]
@Hekili i get it.. sorry for being scattered.. so there are 2 issues..
1) potion which hasn't happened again yet, other then for the briefest instant.
2) repeatedly recommending the same spell.  Last night I counted 7 wraths and 5 starfires in a row.

**Comment by Hekili** [comment]
What makes you think multiple Wraths and Starfires in a row is incorrect?  Have you simmed yourself?

**Comment by N6REJ** [comment]
yes... I can see 2 wraths then a starfire, and even 2 starfires but 6? 7? in a row?

**Comment by Hekili** [comment]
Yeah, you'll want to check out a Balance Druid guide.
