### ISSUE TITLE
Endless LUA errors "tried to compare number with string" demonology warlock

### ISSUE THREAD

**Issue by TooUnskilled** [Hekili/hekili#111]
This keeps happening with both versions released on 19/4, had to go back to previous release to stop it.
Not much to say about recreating it, I just start a fight and it immediately starts popping LUA errors until I shut down the game.
In case it helps, I've changed most of my skills into Macros, and they all follow this formula:

#showtooltip
/targetenemy [noexists][dead]
/petattack
/cast 
/use 13
/use 14

OR

#showtooltip
/targetenemy [noexists][dead]
/petattack
/cast [@cursor]
/use 13
/use 14

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/UePzdAEL

That's about it. If you need more details, let me know what I need to do to report them. Happy to help you help me :)

**Comment by SpatenLa** [comment]
the error text itself would be important

**Comment by TooUnskilled** [comment]
> the error text itself would be important

Will redownload one of the versions causing it and get back to you with a screenshot today.
If you'd rather have something other than a screenshot, let me know how you'd like me to do it.

**Comment by Hekili** [comment]
Yeah, the proper error message will give line numbers for me to investigate.

**Comment by Hekili** [comment]
Can confirm that I'm not able to replicate any errors using a Demo Warlock with your talents and I tried adding a macro like you've described with no error messages.

Please submit the ticket information *using the version you're seeing the error on* so that the error message and ticket information match the problem situation.

**Comment by TooUnskilled** [comment]
I also added my full list of addons, just in case you know of any conflicts. Let me know if I missed anything.

![WoWScrnShot_042019_193655](https://user-images.githubusercontent.com/49813844/56459969-2b139200-63a4-11e9-9729-8905c525a86a.jpg)
![WoWScrnShot_042019_193703](https://user-images.githubusercontent.com/49813844/56459970-2bac2880-63a4-11e9-911e-83b088bae330.jpg)
![WoWScrnShot_042019_193706](https://user-images.githubusercontent.com/49813844/56459971-2bac2880-63a4-11e9-8a53-b9f29454e4b3.jpg)
![WoWScrnShot_042019_193754](https://user-images.githubusercontent.com/49813844/56459972-2bac2880-63a4-11e9-9bf8-1e44e4a65ee1.jpg)
![WoWScrnShot_042019_193757](https://user-images.githubusercontent.com/49813844/56459973-2bac2880-63a4-11e9-8ee3-496bdc6f1c00.jpg)
![WoWScrnShot_042019_193759](https://user-images.githubusercontent.com/49813844/56459974-2bac2880-63a4-11e9-8f72-5491f95591c1.jpg)
![WoWScrnShot_042019_193802](https://user-images.githubusercontent.com/49813844/56459975-2c44bf00-63a4-11e9-9155-9ac71e4ef162.jpg)
![WoWScrnShot_042019_194604](https://user-images.githubusercontent.com/49813844/56460046-0e2b8e80-63a5-11e9-89a9-b65239db3274.jpg)
![WoWScrnShot_042019_194615](https://user-images.githubusercontent.com/49813844/56460047-0e2b8e80-63a5-11e9-8774-c8a265ab1296.jpg)
![WoWScrnShot_042019_194551](https://user-images.githubusercontent.com/49813844/56460048-0e2b8e80-63a5-11e9-9551-1d29e6817003.jpg)

**Comment by Hekili** [comment]
Addon version?  Issue Reporting tab?

**Comment by TooUnskilled** [comment]
> Addon version? Issue Reporting tab?

build: v8.1.5-10
level: 120
class: WARLOCK
spec: demonology

talents: bilescourge_bombers
    burning_rush
    darkfury
    doom
    grimoire_felguard
    sacrificed_souls
    soul_strike

traits: azerite_empowered=2
    dagger_in_the_back=1
    elemental_whirl=1
    impassive_visage=1
    incite_the_pack=1
    shadows_bite=1
    vampiric_speed=1

sets/legendaries/artifacts: none

gear:     slippers_of_the_twilight_prophet=1
    phoenixfire_staff=1
    wild_pyromancers_trousers=1
    periwinkle_cloak=1
    loop_of_pulsing_veins=1
    firecallers_handwraps=1
    sirensong_garments=1
    warcasters_arcane_mantle=1
    heart_of_azeroth=1
    secret_spinners_miter=1
    sea_star=1
    spearfishers_band=1
    shadra_silk_sash=1
    emblem_of_zandalar=1
    7th_legionnaires_cuffs=1

Should be the same I pasted last time. Am I missing something?
Edit: Oops yeah, the other one was a different version. My bad!

**Comment by TooUnskilled** [comment]
I just noticed something. I kept killing mobs one at a time without realizing I hadn't rolled back versions yet. Then I pulled a second one and it started spamming LUA errors again.

So it might only happen in multi target situations
Edit: Yep, definitely only if there's more than one target involved.

**Comment by Hekili** [comment]
Fixed in -11-beta2.

**Comment by TooUnskilled** [comment]
You're the best!
