### ISSUE TITLE
New Display Mode: "Automatic Dual Display"

### ISSUE THREAD

**Issue by Artenuvielle** [Hekili/hekili#1110]
I would love to see a dual display mode for single target (in primary display) and aoe (in secondary display) but the aoe would be somewhat automatic. It would assume there are allways at least the number of targets available as specified as minimum aoe targets for that spec or a higher value if the automatic detection algorithm detects a number higher than that.

The reason for that would be that some specs (e.g. elemental shaman) tries to keep up a dot on some targets if you less then 5 enemies but starting from that you want to skip dotting and just continue with aoe spells.

**Comment by Hekili** [comment]
That's exactly how the Dual display mode works.
