### ISSUE TITLE
Error with gladiators_badge_345228

### ISSUE THREAD

**Issue by PicardRaphael** [Hekili/hekili#1113]
Hello, i want to know how can resolver my error lua : Interface\AddOns\Hekili\CLasses\MageFire.lua:613:aattempt to index field 'gladiators_badge_345228' (a null value)

**Comment by PicardRaphael** [comment]
![image](https://user-images.githubusercontent.com/35990535/121329622-aa160c80-c915-11eb-9e01-7cecbc814768.png)

**Comment by PicardRaphael** [comment]
![image](https://user-images.githubusercontent.com/35990535/121329756-c74adb00-c915-11eb-8c7a-a3fd8c677c7e.png)

**Comment by PicardRaphael** [comment]
for you know i'm french player sorry for my english.

**Comment by Hekili** [comment]
Sorry the taking a month to respond.  I believe this has been fixed in 9.1, but if you still see it, please reopen or respond to this ticket.  Thanks!
