### ISSUE TITLE
Intermittent freezing in M+ Fury.

### ISSUE THREAD

**Issue by Zoliii** [Hekili/hekili#1114]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version. - Done

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports. Checked only Fire Mage

**Describe the Bug/Issue**

In large pulls such as HOA start, Dos start my game would lock up for around 1-2 seconds. With hekili off game is fine. Also small pulls are fine

**To Reproduce**
Run HOA 15
Large first pull
Blow cool downs
Mid cool down freeze

**Expected behavior**
Shouldnt freeze

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here. Have removed addon, not adding back for this. But have tested on 2 PCs. Character is Zolì-Barthilas

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

- no lua errors shown
- If wow running in console mode issue does not occur 
- Issue began 9 days ago

**Comment by Hekili** [comment]
> Have removed addon, not adding back for this. But have tested on 2 PCs. Character is Zolì-Barthilas

Thanks for the report.  I'll leave it open for now, in case someone else decides to supply the required info.  Take care.

**Comment by Zoliii** [comment]
FYI. Also run a boomy and MM hunter and don’t experience the issue. Also tested with a new install of wow and hekili, same issue 

had bug sack and bug grabber running, no errors were thrown

**Comment by Hekili** [comment]
Still need the required ticket info.  Thanks.
