### ISSUE TITLE
Blood DK priority needs tuning

### ISSUE THREAD

**Issue by nb41** [Hekili/hekili#1116]
1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Checked for updates, didn't find any.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

Didn't see this when searching on Blood or BDK.

**Describe the Bug/Issue**
The main issue is around Death Strike and stacks of Bone Shield. Due to Ossuary, Death Strike shouldn't be cast at under 5 stacks of Bone Shield. The only exception is a dire circumstance. After spending a fair amount of time on a target dummy, I'm seeing the rotation continually let Bone Shield drop down to 3-4 and then suggesting DS despite 2 runes free and no risk of overcap on RP. I'm not clear on the exact spot in the priority list this needs tweaking but it's happening often enough I'm relatively sure it's a baseline issue and not just due to my wacky coveneant choice (Nightfae).

Note that checking 'Save Blood Shield' definitely reduces how often it happens, by a significant margin.

**To Reproduce**
Swap spec to Blood DK. Enter combat with a target dummy *which damages you*, on the 'Automatic' Hekili setting. Eventually the reccomendation will be to Death Strike even though Bone Shield is <5 stacks, your RP is in no danger of capping, and your health isn't especially low. (Occasionally it will also recommend a DS at 5, but in the window of a stack falling off to 4 when GCD is rolling. This causes a Bad DS as well.)

**Expected behavior**
It should really never recommend DS if you are at < 5 Bone Shield, due to Ossuary. BDKs are at a risk for 'falling behind' and this is a waste of 5RP to DS at <= 4 stacks. Additionally, if your 6th stack fell off >2.5s ago, it's risky--you could lose stack 5 right as you go to DS, costing the 5 RP again.

**Screenshots**
![image](https://user-images.githubusercontent.com/29413086/122624461-2666c900-d055-11eb-9678-e7836e709877.png)

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  

https://pastebin.com/1TJNTfVG

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot. 
 

https://pastebin.com/rXSsLE34

The main issue seems to be a lack of checking for Bone Shield level when choosing to DS. In fact none of the DS recommendations seem to have it.

**Comment by Hekili** [comment]
Please follow the instructions when submitting a ticket, including the snapshot.  Thanks!

**Comment by nb41** [comment]
The feature request doesn't ask for anything ...? Unless you feel this is a bug request in which case, no worries, I can follow those.

**Comment by Hekili** [comment]
Yeah, this isn't a feature request, it's a change to the existing priority.  Use the Bug Report template, please.

**Comment by nb41** [comment]
:+1: Will do.

**Comment by nb41** [comment]
@Hekili Updated.

**Comment by Icenova20** [comment]
Thanks for posting this, I had no idea that was a thing, and this lets me keep an eye out an try to manually adjust my play.

**Comment by nb41** [comment]
@Icenova20 np. There's a really good WA which will tell you if you're MR too early, or DSing under 5, or overcapping RP. It's how I tracked this and knew when to hit my snapshot.

**Comment by Hekili** [comment]
Is this happening in 9.1?

**Comment by nb41** [comment]
Definitely still happening--I just updated to the latest version of Hekili and can do another snapshot if you need one.

**Comment by Hekili** [comment]
Sure.

**Comment by Hekili** [comment]
The next release will have a rather haphazard (and impossible to really test in sims) change that will prioritize Marrowrend if Bone Shield is under 5 stacks and it won't overcap RP.
