### ISSUE TITLE
Hekili crashes/disconnects WoW for only one toon when logging in.  

### ISSUE THREAD

**Issue by LadyRakael** [Hekili/hekili#1117]
Hekili crashes/disconnects World of Warcraft when I log into my main toon. None of my alts who use this add-on have this issue upon logging in. The only way I can avoid crashing is when I disable Hekili first at the character selection screen, load, then reload Hekili add-on after my toon is logged in and in-world. 

This has been going on for months. The only way I could successfully log into my main without crashing was to disable all the add-ons, load my toon, then enable the add-ons afterward. Finally this morning I sat down and disabled the add-ons one by one to find the culprit. I was very surprised that it was Hekili.  I tested it several times enabled and disabled  Hekili upon loading the toon. Every single time I had it enabled upon loading the toon, the game crashed and gave me error code WOW51900319.

I am unable to capture bugs about this using the buggrabber/bugsack addon , sadly. 

I reset and deleted profiles saved by this addon. That did not work. It still crashes upon loading. 

I deleted the add-on, restarted the game, loaded my toon with success, exited the game, reinstalled Hekili, loaded my toon, and CRASH. 

I am baffled by this and now approach you for any ideas what may be happening. (Does Hekili not like paladins? Ha ha.)

**Comment by Hekili** [comment]
So it's a Paladin.  Tell me about your Paladin.  Spec, settings, gear, talents, covenant, renown, soulbinds, conduits, etc.  When did this start?  I have no open requests for any crash issues at all.

**Comment by Hekili** [comment]
> The only way I can avoid crashing is when I disable Hekili first at the character selection screen, load, then reload Hekili add-on after my toon is logged in and in-world.

Do this, then submit the information from the Issue Reporting tab.

**Comment by LadyRakael** [comment]
From the issues reporting tab. Prot first.

build: v9.0.5-1.0.9a
level: 60 (60)
class: PALADIN
spec: protection

talents: blessed_hammer
    crusaders_judgment
    divine_purpose
    fist_of_justice
    judgment_of_light
    sanctified_wrath
    unbreakable_spirit

pvptalents: none

covenant: kyrian

conduits: punish_the_guilty = 5
   pure_concentration = 5
   ringing_clarity = 5
   shielding_words = 5

soulbinds: [forgelite_prime_mikanikos]
   brons_call_to_action = 1
   forgelite_filter = 1
   regenerating_materials = 1
   soulsteel_clamps = 1

sets: none

gear: ascended_gladius_of_glory = 1
    chyruss_crest_of_hope = 1
    dealer_xyexas_cape = 1
    diadem_of_imperious_desire = 1
    dynamo_doomstompers = 1
    epaulettes_of_overwhelming_force = 1
    fashionable_undershirt = 1
    fogweaver_gauntlets = 1
    gluttonous_spike = 1
    gormshell_greaves = 1
    hellhound_cuffs = 1
    inscrutable_quantum_device = 1
    nobles_birthstone_pendant = 1
    rampaging_giants_chestplate = 1
    ring_of_perpetual_conflict = 1
    ritual_bone_band = 1
    shadowghast_waistguard = 1

legendaries: vanguards_momentum = 1

itemIDs: 151116, 171418, 174315, 178701, 178706, 178870, 178872, 179338, 179349, 179350, 182994, 182997, 182999, 183018, 183039, 184023, 184272

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Protection Paladin
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = true 
    interrupts = true [separate]
    mode = automatic 
    potions = false 

******** Ret below *******

build: v9.0.5-1.0.9a
level: 60 (60)
class: PALADIN
spec: retribution

talents: blade_of_wrath
    blinding_light
    divine_purpose
    eye_for_an_eye
    final_reckoning
    healing_hands
    zeal

pvptalents: none

covenant: kyrian

conduits: expurgation = 5
   golden_path = 5
   ringing_clarity = 5
   shielding_words = 5

soulbinds: [pelagos]
   cleansed_vestments = 1
   combat_meditation = 1
   focusing_mantra = 1
   let_go_of_the_past = 1

sets: none

gear: bloodoath_signet = 1
    dealer_xyexas_cape = 1
    diadem_of_imperious_desire = 1
    dynamo_doomstompers = 1
    epaulettes_of_overwhelming_force = 1
    fashionable_undershirt = 1
    fogweaver_gauntlets = 1
    gluttonous_spike = 1
    gormshell_greaves = 1
    guarding_cudgel_of_the_goliath = 1
    hellhound_cuffs = 1
    inscrutable_quantum_device = 1
    nobles_birthstone_pendant = 1
    rampaging_giants_chestplate = 1
    ring_of_perpetual_conflict = 1
    shadowghast_waistguard = 1

legendaries: vanguards_momentum = 1

itemIDs: 151116, 171418, 178701, 178706, 178871, 178872, 179338, 179349, 179350, 180312, 182994, 182997, 182999, 183018, 183039, 184023

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Retribution
    petbased = false
    potion = spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = false
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = true 
    interrupts = true [separate]
    mode = automatic 
    potions = false

**Comment by Hekili** [comment]
Does it matter which spec you are when you sign in?

**Comment by LadyRakael** [comment]
No.

**Comment by Hekili** [comment]
If you sign in as Holy, does it have any impact?

**Comment by LadyRakael** [comment]
It still crashed, sadly, when I logged in as Holy.

**Comment by Hekili** [comment]
I'm sorry that I can't replicate this on my end.  The next thing to try is editing Hekili.toc inside the Hekili folder.

Try placing a # before Classes\PaladinProtection.lua and Classes\PaladinRetribution.lua, like so:

```
# Classes\PaladinProtection.lua
# Classes\PaladinRetribution.lua
```

Restart WoW.  See if you have the same error.  Let me know.

If that let you back into WoW, edit the Hekili.toc again, removing the # from one of the files.  Restart WoW again.  If WoW works, put the # back and then remove the # from the other file.  Restart and try again.

Let me know in which cases you experience the client crash.

**Comment by Hekili** [comment]
Also, what else can you tell me about your PC?  CPU/GPU/memory?  WoW settings in general?

My best guess at it's related to item or spell caching (since item/spell information isn't available immediately on first load) but I have no idea why it'd happen specifically for your Paladin -- with no one else reporting.

**Comment by LadyRakael** [comment]
I've picked up troubleshooting this issue again today. One thing I noticed between my paladin and the other toons when they loaded in. All my other toons would have a notification stating saying "The [spec] and [spec] priorities were updated." When I previously loaded Hekili for my paladin, she never got this text. 

This morning, I've temporarily scrubbed the Cache, Interface, and WTF folders. Now I am able to finally get the Hekili update notification.

![image](https://user-images.githubusercontent.com/86302995/123136203-a8257080-d420-11eb-9e46-1c7e4ed7f6d8.png)

I did try your suggestion with the # marks, but it didn't work.  I plan to keep working on this some more to see what may have gone wrong for future sake. 

Thanks for your time in all this. I appreciate it.

**Comment by Hekili** [comment]
It sounds like your Hekili data in your SavedVariables folder must've been corrupted in some way that couldn't be interpreted successfully.  If you kept a copy of that file, I can look and try to see more.  Otherwise, there's no way to replicate and resolve this.  But I'm glad it's working for you now!

**Comment by LadyRakael** [comment]
What is the best way to get you a copy of this file?

**Comment by Hekili** [comment]
Pastebin probably works, or hekili.tcn@gmail.com as an attachment.  Thanks!
