### ISSUE TITLE
Damage spenders are not recommended when seraphim, final reckoning and execution sentence are available for ret paladin.

### ISSUE THREAD

**Issue by Everyone1234567** [Hekili/hekili#1118]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Build: v9.0.5-1.0.9a

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
When seraphim, final reckoning and execution sentence are available for use Hekili will continue to recommend using builders past the cap of 5 holy power as I have not enabled CDs. I would have expected Hekili to recommend using an appropriate damaging spender (TV or DS depending on target count). It doesn't appear to matter whether avenging wrath is currently up, available or on cooldown. I have tried enabling CDs for one rotation and disabling it again, the rotation worked as expected with CDs showing but reverted back to the above rotation when disabled again. 

**To Reproduce**
Build to 5 holy power but don't use seraphim at any time.

**Expected behavior**
I wouldn't expect Hekili to recommend overcapping holy power. I would expect it to continue recommending appropriate damaging spenders until seraphim is used. 

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:** https://pastebin.com/pF0inRRT

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**  https://pastebin.com/LNP4BMWD

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:** N/A

**Comment by Hekili** [comment]
You've manually added Seraphim to the cooldowns toggle or toggled it off.  That's not default behavior.  I can potentially babyproof that, though.

**Comment by Hekili** [comment]
It looks like you made Seraphim a CD and you took Final Reckoning off the CDs toggle.  Can you post a screenshot of /hekili > Retribution > Toggles with your Cooldowns visible?  That's the only way I can replicate what you've shown.

**Comment by Hekili** [comment]
Closed (discussed in Discord).
