### ISSUE TITLE
Fire Mage

### ISSUE THREAD

**Issue by kentaaa94** [Hekili/hekili#1119]
Hello! Just wondering if the fire mage rotation is still broken, or if I’m just doing something wrong. Outside of combustion, it just tells you to spam hard cast flamestrike. Just wanted to check if that was the bug mentioned in the post. Thanks so much!

**Comment by Hekili** [comment]
There is an issue with Fire Mage that I'll work to resolve for 9.1, but please follow the instructions when submitting a ticket. Thank you!
