### ISSUE TITLE
Marked for Death cycling issue?

### ISSUE THREAD

**Issue by Lipstopica** [Hekili/hekili#1121]
Obviously it's best to mouseover MfD the lowest target which is what I do most of the time. But I noticed this and thought I would report it just in case it is a bug or it's just how Hekili is with sniping lowest TTD. This was taken with just two dummy targets as an easy cycle as there is only one more target. But this happens just the same in a dungeon with multiple targets. I would tab through every target and it would still be there multiple times. 

Please let me know if you need anymore additional information as I believe I've answered everything as much as I possibly can for this issue.

1. Latest version of Hekili is running. Even reinstalled.

**Describe the Bug/Issue**
Basically when Hekili is telling me to snipe the lowest target via target cycle icon. Targeting lowest and the target cycle icon stays there. Moving closer to the target makes the cycle icon disappear after a while.

**To Reproduce**
Go to dummies, or enemy NPCs and follow the rotation until it tells you snipe the lowest TTD with target cycling enabled.

**Expected behavior**
I mean sure you're technically just supposed to mouseover for MfD which is most likely the most logical and easy way. But just reporting it still. 
Supposed to remove the cycle icon once targetting the lowest TTD target.

**Screenshots**
Sent GiF in Discord DM

https://pastebin.com/J2477bsW - Issue Report
 
https://pastebin.com/H7t26y87 - MfD at the distance with the cycle icon MfD while targeting the lowest TTD (second target).

https://pastebin.com/Mtg8r4eJ - This one is when I walk closer to the target. Normally it shows it like a second after I move to the target. But this time it took like a good 3 seconds before the cycle icon disappeared.

I was looking at the Snapshots I made and can never seem to see MfD at the bottom where I take the snapshot (not sure that's how it works) but its somewhere in the list of stuff.

**Comment by Lipstopica** [comment]
Okay... I don't think it disappears when I'm closer to the target. That might've only been because I moved too close and it only showed one nameplate and only one target. But still the issue/bug remains weird due to it not wanting to accept that as lowest ttd to use MfD on when both targets are visible. When main target already has MfD on and MfD is ready to use again.

**Comment by Hekili** [comment]
Okay, I'm trying to follow what you're reporting and asking for, so correct me if I miss something.

First, if you want secondary targets to be detected when they don't have a nameplate on screen, you need to (re-)enable damage-based target detection.

> Supposed to remove the cycle icon once targetting the lowest TTD target.

TTDs are volatile and update multiple times per second.  Dummies aren't great targets for testing time-to-die logic because they aren't going to die.  You're very likely dealing with microseconds of difference in calculated time-to-die since neither of them are really going to die anyway.

**Comment by Lipstopica** [comment]
X = Hekili is telling me to target the lowest target ttd which for example in a dungeon a pack of  3-4 mobs and still shows cycle icon even when I cycle through every single target I have there and all the monsters I am in combat with are not classed as lowest ttd. 
Y = Cycle should dissapear once I targetted the lowest ttd monster

I did test it on dummies but I did also see it happen in dungeons
At first I thought it might've been because my main target happened to be the lowest TTD, with the aura of MfD already being up on that target so it would keep cycling to try and find the lowest TTD without the MfD aura (but happens to be the lowest TTD target has MfD aura already up) as MfD resets with the target dying with the aura up or cooldown reset so you can have multiple MfD being used

**Comment by Hekili** [comment]
Seems resolved.
