### ISSUE TITLE
Can we get some love for demonology warlock?

### ISSUE THREAD

**Issue by MPJulian86** [Hekili/hekili#1122]
Demo WL seems to be pretty good in 9.1 but atm when i try at the dummy i get only low tyrants. I tried the opener thats in the warlock class discord and i got a big tyrant but with hekilli i only  get low tyrants. Would love to use this in 9.1.

**Comment by Hekili** [comment]
Demonology Warlock only got love very recently in SimC.  All specs will be updated for 9.1.
