### ISSUE TITLE
Balance Druid SimulationCraft profile priorities only showing one spell

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#1123]
**Describe the Bug/Issue**
I loaded a custom rotation from a SimulationCraft profile. After activating it, it showed my opening abilities and was quickly replaced with a  long string of one spell. Even after applying the dot, the addon continued to recommend that I cast moonfire over and over again. The same thing happens with sunfire when AoE mode is activated as well. 

**To Reproduce**
I provided the profile and issue report strings below. Here is how I got the profile though:

- Download latest build of SimulationCraft desktop app
- Import balance druid character
- Paste SimC profile into Hekili priorities and activate
- Display mode single/auto

**Expected behavior**
Expect a full rotation, not a single spell.

**Screenshots**
![image](https://user-images.githubusercontent.com/86528223/123519165-e14f2200-d666-11eb-896f-a42629a169b7.png)

**Comment by Lipstopica** [comment]
Why are you pasting a profile into Hekili. It doesn't tell you to do that and you shouldn't do that unless you know what you're doing. 
Default Hekili profile already uses the SimC profiles. Hekili has to manually edit the Simc profiles to translate some functions.

**Comment by Hekili** [comment]
Basically, what Lipstopica just said.

If you're a power-user who is importing (presumably customized) profiles, you're on your own in terms of any additional translation needed to make them work in the addon.
