### ISSUE TITLE
Arcane Mage Rotation

### ISSUE THREAD

**Issue by AnxiousLynx** [Hekili/hekili#1126]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
The Arcane Mage rotation is quite scrambled after the new update. Rune of Power overlaps with Arcane Power, Arcane Missiles during Radiant Spark window. After hitting a training dummy for a bit I've noticed that it's much different from last release even though last release needed only a few tweaks (counting in-flight Harmony stacks, which is a welcome addition in the new update)

**To Reproduce**
Simply followed the Single Target Rotation as shown on the display.

**Expected behavior**
Didn't expect much change from last release after viewing the changelog.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

https://pastebin.com/K2axzFLB

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

https://pastebin.com/bKxGR2Rf

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Are you testing on 9.0.5 or 9.1 PTR?

**Comment by Hekili** [comment]
> The Arcane Mage rotation is quite scrambled after the new update. Rune of Power overlaps with Arcane Power, Arcane Missiles during Radiant Spark window. After hitting a training dummy for a bit I've noticed that it's much different from last release even though last release needed only a few tweaks (counting in-flight Harmony stacks, which is a welcome addition in the new update).

The updates that were made were consistent with the updates to the spec's sim profile.

Have you simmed yourself with the new profiles?  Can you give specific feedback in terms of the behavior that's different from your simmed actions?

**Comment by AnxiousLynx** [comment]
I'm testing on 9.0.5, guess I'll have to wait for tonight's patch to drop. Currently Raidbots is undergoing maintenance, I'll bump this once I get a sim. 

But to give a quick example - On pull (tested on a training dummy, single target display, cooldowns and covenant abilities on) it overspams Arcane Missiles way above 18 Harmony stacks, and subsequently recommends to pop RoP into ToTM into AP, which wasn't expected.

**Comment by Hekili** [comment]
The way to submit this is to take a snapshot when the problem is occurring, then link that with Pastebin.

Then you can say "It is showing A then B then C, but it should show X then Y then Z, because \<your explanation here\>."

If you can provide that, I'm sure it can be easily resolved.

**Comment by AnxiousLynx** [comment]
https://pastebin.com/CGYN4eNW  SNAP 1
https://pastebin.com/4vGYMCVv SNAP 2

In snap 1 I'm capped on Harmony stacks yet the display recommends more AM spam
In snap 2 I already have RoP active, yet the addon wants me to use Arcane Power

These are the examples from the first few seconds of the rotation

**Comment by Hekili** [comment]
Perfect.  Thank you!

**Comment by AnxiousLynx** [comment]
Thank you so much for the swift responses :)

**Comment by Hekili** [comment]
This is the entry that is being used for Arcane Missiles at that point:

```
# When using Empyreal Ordnance, cast a few extra missiles while waiting for the buff at the start of the fight
actions.harmony+=/arcane_missiles,if=equipped.empyreal_ordnance&time<30&cooldown.empyreal_ordnance.remains>168
```

If you remove your Empyreal Ordnance, is it resolved?

**Comment by AnxiousLynx** [comment]
Tried unequipping Empyreal, rotation still persists :(

**Comment by AnxiousLynx** [comment]
Should I remove it from the item list?

**Comment by Hekili** [comment]
No, but you should snapshot again without the Empyreal equipped so I can see the difference.  :)

**Comment by AnxiousLynx** [comment]
NO EMPYREAL

https://pastebin.com/UPqnjWBb SNAP 1
https://pastebin.com/QiKJqLeZ SNAP 2

1st snap is still same issue, overlapping Rune and Arcane Power
2nd snap is releasing Barrage too early with no Radiant stacks

**Comment by Hekili** [comment]
1st snap does not sound like the same issue of:
`In snap 1 I'm capped on Harmony stacks yet the display recommends more AM spam`

Is `In snap 1 I'm capped on Harmony stacks yet the display recommends more AM spam` resolved or not?

**Comment by AnxiousLynx** [comment]
Yes, it doesn't recommend me anymore AM spam, so that one's good.

**Comment by Hekili** [comment]
So, the Arcane Power entry that is recommended second comes after Touch of the Magi, which looks written intentionally into the APL.

`actions.harmony+=/arcane_power,if=prev_gcd.1.touch_of_the_magi`

When you can sim, you'll want to see if the same behavior is occurring and potentially ask the mage TCers if it's intentional.

**Comment by AnxiousLynx** [comment]
Okay, so for now I can just ignore the RoP recommendation in the opener. When Raidbots come down from maintenance and new patch comes out, I'll be sure to investigate. Thank you

**Comment by Hekili** [comment]
For your latest snap 2, Arcane Barrage is cast with 18 stacks of Arcane Harmony.

```
92.  arcane_barrage ( harmony - 22 )
The action (arcane_barrage) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
List ( harmony ) called from ( Arcane:default:21 ) would PASS at 0.00.
covenant.kyrian[true] & runeforge.arcane_infinity.enabled[true]
 - this entry's criteria PASSES: buff.arcane_charge.stack[4.00] = buff.arcane_charge.max_stack[4.00] & variable.empowered_barrage[true]
Action chosen:  arcane_barrage at 0.00!
```

`variable.empowered_barrage` is `true`:  `buff.arcane_harmony.stack[18.00] = buff.arcane_harmony.max_stack[18.00] | ( runeforge.arcane_bombardment.enabled[false] & target.health.pct[99.44] < 35 )`

There are no conditionals related to Radiant Spark at this point, so it may be an oversight in SimC.  I'll watch for priority changes.

**Comment by Hekili** [comment]
Also, Radiant Spark had > 15 seconds on its CD, so I doubt you'd want to sit on 18 stacks of Harmony for 15+ seconds until you can cast Radiant Spark.  That looks like it's working as intended.

**Comment by Hekili** [comment]
Looking over that Empyreal Ordnance logic, it appears intentional as well.

```
target_debuffs:
   345540 - empyreal_ordnance                        -   5 - 5.80
   324260 - *Sinful Revelation                       -   1 - 6.58
```

It's waiting for you to get buffed:
```
# When using Empyreal Ordnance, cast a few extra missiles while waiting for the buff at the start of the fight
actions.harmony+=/arcane_missiles,if=equipped.empyreal_ordnance&time<30&cooldown.empyreal_ordnance.remains>168
```

**Comment by AnxiousLynx** [comment]
So just ran a key and everything else seems fine if not for the Rune of Power recommendation. I see your point with the Empyreal now. Still need to see what the sim says

**Comment by Hekili** [comment]
That Arcane Power while RoP is already down looks deliberate.  Yeah, I'll leave this open while we wait for sims.

**Comment by AnxiousLynx** [comment]
![paveikslas](https://user-images.githubusercontent.com/86646719/123893346-85351800-d95c-11eb-943b-0f2bc3620c6b.png)

There was indeed no Rune of Power overlapping with AP in the sim where the addon recommended it (after the 11:4 Missiles). This happens later in combat too, when AP comes off cooldown, the addon recommend going Spark -> RoP

**Comment by Hekili** [comment]
Go ahead and link the sim so I can compare. Thanks.

**Comment by Hekili** [comment]
I'll need links to sims for further testing, please let me know if you can/will be providing more data.  Thanks!
