### ISSUE TITLE
Shaman Primal Elementalist issue

### ISSUE THREAD

**Issue by LucianDK** [Hekili/hekili#1128]
[primal elementalist snapshot.txt](https://github.com/Hekili/hekili/files/6737032/primal.elementalist.snapshot.txt)
Using build: v9.1.0-1.0.1

I noticed someone had posted a report about Primal Earth Elemental being recommended if a dps Primal Elemental was present.
Mine is the reverse issue.    I use the Primal Elementalist talent, and upon casting Primal Earth Elemental even if its not recommended in the queue bar, Hekili does however still recommend Primal Fire Elemental and Meteor despite the Primal Earth Elemental being active.  Observed both in the world and on a raider dummy.
So, if you have the Primal Earth Elemental up, it would be up for a reason, and not wanting to overwrite it with the Primal Fire Elemental unless needed.

Picking the Primal Elementalist talent. Activate Earth Elemental and it will still recommend Primal Fire Elemental and Meteor, despite the Primal Earth Elemental being present.

Primal Fire Elemental and Meteor should not be recomended if Primal Earth Elemental is active

**Comment by Hekili** [comment]
Yes, that was intentional, but I've gone ahead and made a revision in 1.0.3 that will trust that if you have any pet up, it won't try to replace it with a different elemental.
