### ISSUE TITLE
Brewmaster 2 abilities

### ISSUE THREAD

**Issue by Dov1an** [Hekili/hekili#113]
Brewmaster is only displaying two abilities at a time, and only four abilities in the rotation. Blackout Strike, Keg Smash, Breath of Fire and Chi Wave. 

It refuses to show Tiger Palm. 

It was working perfectly in a previous update

No other classes are affected. 

Bug Error:
Date: 2019-04-20 23:40:25
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Hekili\Classes\MonkBrewmaster.lua line 867:
   attempt to perform arithmetic on a boolean value
Debug:
   Hekili\Classes\MonkBrewmaster.lua:867:
      Hekili\Classes\MonkBrewmaster.lua:867
   (tail call): ?
   Hekili\State.lua:2232:
      Hekili\State.lua:2172
   Hekili\State.lua:2290:
      Hekili\State.lua:2172
   Hekili\State.lua:5182: TimeToReady()
   Hekili\Core.lua:540: GetPredictionFromAPL()
   Hekili\Core.lua:992: GetNextPrediction()
   Hekili\Core.lua:1158: ProcessHooks()
   Hekili\UI.lua:820:
      Hekili\UI.lua:685
Locals:
(*temporary) = false
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on a boolean value"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AAPCore, v8.1052
  Altoholic, vr190
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDeathGraphs, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  GatherMate2, v1.43.6
  GuildRosterManager, v1.55
  GuildTracker, v8.0.1-1
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBrokenShore, vv1.30
  HandyNotesGuild, v1.10
  HealBot, v8.1.5.8
  HealBotTips, v8.1.5.8
  Hekili, vv8.1.5-10
  HHPH, v2
  Informant, v8.1.6246 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LucidNightmareHelper, v
  Oilvl, v8.0.2
  OPie, vWalnut 2
  Postal, vv3.6.0
  Prat30, vr1195      
  Prat30Libraries, v
  Rarity, v1.0 (r688-release-2)
  RarityOptions, v
  SavedInstances, v8.1.1
  SexyMap, vv8.1.1
  SilverDragon, vv4.0.15
  SilverDragonBattleForAzeroth, vv4.0.15
  SilverDragonBurningCrusade, vv4.0.15
  SilverDragonCataclysm, vv4.0.15
  SilverDragonLegion, vv4.0.15
  SilverDragonMists, vv4.0.15
  SilverDragonVanilla, vv4.0.15
  SilverDragonWarlords, vv4.0.15
  SilverDragonWrath, vv4.0.15
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20190420
  TomTom, vv80105-1.0.0
  WorldQuestTracker, v
  WQAchievements, vv8.1.5-3release
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=8bb)

**Comment by Hekili** [comment]
Version?

**Comment by Dov1an** [comment]
v8.1.5-10

**Comment by Hekili** [comment]
Please update to 8.1.5-11-beta4 (in a few minutes) and let me know if you still have trouble.

**Comment by Dov1an** [comment]
that fixed it. thank you!
