### ISSUE TITLE
The world of warcraft sticks with me with this version of hekili

### ISSUE THREAD

**Issue by drkrox** [Hekili/hekili#1133]
Good I do this thread for the following problem, in the WOW it does not start me with the current version of hekili, the screen literally stays stuck I do not know what it can be, I uninstalled the addons I reinstalled them and with the only one I have the problem is with hekili, could you give me some help to solve this problem

Thank you

**Comment by Hekili** [comment]
It's possible something is corrupted in your saved variables.  You can send me a copy of the Hekili.lua inside your WTF folder for testing.

To (probably) resolve quickly:  Close WoW.  Open WoW\\_retail\_\WTF\Account\<Your Account Name>\SavedVariables.  Delete the Hekili.lua.  Restart WoW.  See if it's fixed.

**Comment by drkrox** [comment]
I can't find the file in the place you mentioned
![ADDONS](https://user-images.githubusercontent.com/86793810/124164914-3e841280-da6f-11eb-8ec1-9322bb532915.png)

**Comment by Hekili** [comment]
I don't know what else to recommend.  I don't have any information that would help me replicate this.  Can you explain the issue in more detail?

> the current version of hekili

What is the actual version number?

> the screen literally stays stuck

What does this mean?  What screen?  Are you in-game?  Signing into the game?

**Comment by drkrox** [comment]
1.- is the last version
![image](https://user-images.githubusercontent.com/86793810/124180018-975ca680-da81-11eb-9262-c41ac16e440b.png)
  2.-  when starting WOW the game stays like this.
When deactivating the addon it works fine normally
![noresp](https://user-images.githubusercontent.com/86793810/124181225-3afa8680-da83-11eb-9285-664b83962cbe.png)

**Comment by Hekili** [comment]
Ok, so you do get in-game. Does the game freeze immediately upon logging in? If so, I need to know your character info (talents, covenant, etc.). If not, you can copy/paste from /hekili > Issue Reporting.

**Comment by drkrox** [comment]
_Does the game freeze immediately upon logging in?_
Yes
shadow priest,
covenat Night Fae, niya conduitt
talents
fortrees of the mind
body and soul
searing nigthmare
mind bomb
Auspicius spirits
void torrent
Hungering void

**Comment by Hekili** [comment]
No luck replicating this so far.  What's your gear?  Legendaries?  If you log in without Hekili loaded and change your talents, your gear, your soulbinds, etc., then load Hekili and try again, are you still blocked?

I can't find anything so far.

**Comment by drkrox** [comment]
Hello
today I installed the latest version of hekili and it worked, I don't know what they fixed but now it's fine, thank you very much for everything

**Comment by drkrox** [comment]
_No luck replicating this so far. What's your gear? Legendaries? If you log in without Hekili loaded and change your talents, your gear, your soulbinds, etc., then load Hekili and try again, are you still blocked?_

Before it was fixed, it couldn't do anything, it just stayed there on the loading screen just like the previous images.

**Comment by Hekili** [comment]
I'm glad it's working.  I don't understand `it just stayed there on the loading screen` considering that your screenshot is not a loading screen, but we'll call it good.  :D  Can you provide a list of addons you're using, just in case I learn later that it's a combination of addons or something?  Thanks.
