### ISSUE TITLE
[Feral] - unknown function max:target.time_to_die

### ISSUE THREAD

**Issue by Nmxsz** [Hekili/hekili#1135]
When using the newest 9.1 Feral APL u will not get a suggestion to cast "Ferocious Bite" and "Feral Frenzy".

e.g.
actions+=/ferocious_bite,target_if=max:target.time_to_die,if=buff.apex_predators_craving.up

actions.cooldown+=/feral_frenzy,target_if=max:target.time_to_die,if=combo_points<3&target.time_to_die>7&!cooldown.tigers_fury.up|fight_remains<8&fight_remains>2

actions.finisher+=/ferocious_bite,max_energy=1,target_if=max:time_to_die

actions.finisher+=/ferocious_bite,target_if=max:time_to_die,if=buff.bs_inc.up&talent.soul_of_the_forest.enabled

**Comment by Hekili** [comment]
If you import your own priorities, you have to deal with translating them for the addon.  `target_if` is not supported.  Where is this 9.1 Feral APL found?

**Comment by Nmxsz** [comment]
> If you import your own priorities, you have to deal with translating them for the addon. `target_if` is not supported. Where is this 9.1 Feral APL found?

This APL was generated by Raidbots 

https://www.raidbots.com/simbot/report/9s3zzFS72EugFMtFYAZkzu/simc

**Comment by Hekili** [comment]
It's no different or better than the default -- APLs from SimC generally do not change significantly based on gear (or I incorporate the gear-related differences into my default priority). You do not need to import anything. You really don't.
