### ISSUE TITLE
Arcane Mage Cooldowns Missing from Suggested Rotation

### ISSUE THREAD

**Issue by ESBVader** [Hekili/hekili#1136]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Using version 9.1.0-1.0.3b downloaded 07.02.2021

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Currently running as Venthyr Arcane Mage.  I've run through the rotations several times at 5-10 minutes each verifying the suggested rotation.  The rotation is not suggesting Rune of Power, Arcane Power, or Presence of Mind. Touch of the Magi is suggested however.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
Rotation enabled that includes CD's and correct prioritization.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
build: v9.1.0-1.0.3b
level: 60 (60)
class: MAGE
spec: arcane

talents: amplification
    arcane_orb
    chrono_shift
    overpowered
    resonance
    rune_of_power
    shimmer

pvptalents: none

covenant: venthyr

conduits: arcane_prodigy = 6
   diverted_energy = 5
   flow_of_time = 5
   magis_brand = 5
   siphoned_malice = 6

soulbinds: [theotar_the_mad_duke]
   exquisite_ingredients = 1
   leisurely_gait = 1
   soothing_shade = 1
   token_of_appreciation = 1

sets: none

gear: arachnid_cipher_ring = 1
    azurevenom_choker = 1
    castigators_mantle = 1
    dealer_xyexas_cape = 1
    deathshackle_wristwraps = 1
    depraved_physicians_mask = 1
    empyreal_ordnance = 1
    grimveiled_mittens = 1
    infinitely_divisible_ooze = 1
    kintaras_baleful_cord = 1
    manastorms_magnificent_threads = 1
    signet_of_the_false_accuser = 1
    soulenveloping_leggings = 1
    stradamas_misplaced_slippers = 1
    surgical_pustule_extractor = 1
    vessel_of_shining_radiance = 1

legendaries: siphon_storm = 1

itemIDs: 173244, 178704, 178753, 178756, 178759, 178769, 178824, 178852, 178859, 178933, 179335, 179349, 180109, 180115, 180117, 187373

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Arcane
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
You did not provide all the required information.

**Comment by ESBVader** [comment]
Apologies.  Adding it now.

**Comment by Hekili** [comment]
`toggles: cooldowns = false`

You have Cooldowns toggled off (which is default).

See /hekili > Toggles.  It's intentional that you can hold CDs and not just burn them all the time (i.e., on trash packs or trivial enemies).

**Comment by ESBVader** [comment]
Thank you so much.  Appreciate your patience with my noob question!  

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 2, 2021 at 5:55 PM, ***@***.***> wrote:   


Closed #1136.
