### ISSUE TITLE
[Fury War] Bladestorm not recommended during AOE rotation

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#1137]
Hi,

I noticed that during only AOE rotation, Bladestorm is not being recommended.
I'm using latest build v9.1.0-1.0.3c

Link to snapshot:
https://pastebin.com/z1FSRsLV

build: v9.1.0-1.0.3c
level: 60 (60)
class: WARRIOR
spec: fury

talents: anger_management
    bladestorm
    cruelty
    double_time
    massacre
    sudden_death
    warpaint

pvptalents: none

covenant: venthyr

conduits: ashen_juggernaut = 4
   depths_of_insanity = 4
   inspiring_presence = 5
   stalwart_guardian = 4

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   familiar_predicaments = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: azurevenom_choker = 1
    darkmoon_deck_voracity = 1
    distorted_constructs_gauntlets = 1
    dread_sentinels_ebony_chestplate = 1
    dread_sentinels_ebony_cloak = 1
    dread_sentinels_ebony_legguards = 1
    honortoll_gavel = 1
    lost_wayfarers_band = 1
    oversized_centurion_helm = 1
    ritualists_treasured_ring = 1
    sapsteel_pauldrons = 1
    shadowghast_armguards = 1
    sophisticated_bonecracker = 1
    stone_legion_heraldry = 1
    tabard_of_the_honorbound = 1
    valinors_ground_pounders = 1
    vault_guardians_girdle = 1

legendaries: signet_of_tormented_kings = 1

itemIDs: 160545, 171419, 173087, 178752, 180104, 180115, 180902, 180916, 180938, 181419, 181635, 183037, 184027, 184132, 184139, 185882, 185895

settings: aoe = 2
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = true
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_ww_range = true
    heroic_charge = false

toggles: cooldowns = false
    custom1 = true 
    custom2 = false 
    defensives = true 
    essences = true 
    interrupts = true [separate]
    mode = single 
    potions = false

**Comment by Hekili** [comment]
This should be resolved in 1.0.4 (AOE list was not properly called).
