### ISSUE TITLE
Sub rogue Funnel Damage not working correctly

### ISSUE THREAD

**Issue by Elderin1** [Hekili/hekili#1138]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Sub priority rotation does not seem to be working correctly. It displays black powder instead of eviscerate. 

**To Reproduce**
Just set funnel damage on and go to aoe dummies to see.
After some testing, it seems that priority rotation is working when shadow dance is not active. So if you remove shadow dance from the rotation, it will shuriken storm to build CP and use eviscerate as finisher. However if you have shadow dance active, rotation becomes black powder finisher.

**Expected behavior**
The priority rotation should build combo points with shuriken storm and use single target finishers like eviscerate even in shadow dance in an aoe priority rotation.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/UJLDsbA5

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/rJ4PQw6y

Extra note:  "/hek set allow_shadowmeld" does not switch on/off. Everytime i use the macro it sets it to on.

**Comment by Hekili** [comment]
Thanks, this is a good report.  I've found that moving the `use_priority_rotation` earlier in the Subtlety priority resolves this issue.  It should be before any `call_action_list` or `run_action_list` entries.  I'll prepare the change for later today.

**Comment by Hekili** [comment]
This fix is in 1.0.4.  Thanks again.

Also, /hek set allow_shadowmeld should work as well.
