### ISSUE TITLE
Frost Mage - COOLDOWNS/AOE

### ISSUE THREAD

**Issue by sleeper323** [Hekili/hekili#1139]
**Describe the Bug/Issue**
When COOLDOWNS is toggled, hekili doesn't want me to AoE using blizzard.

**To Reproduce**
- Toggle everything on including cooldowns
- Go to AoE pack

**Expected behavior**
When COOLDOWNS is toggled, and you are in AoE pack, it will tell me to keep pressing my racial button

 SNAPSHOT
**https://pastebin.com/BSQEQMiP:**

**Comment by Hekili** [comment]
I'm not able to replicate this with the information provided.

![image](https://user-images.githubusercontent.com/9438134/124362353-4de79500-dc02-11eb-8b24-f60d08d2a2d3.png)
