### ISSUE TITLE
Monk - Whirling Dragon Punch (Blizzard Bug)

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#114]
Whirling Dragon Punch often comes up in rotation (display) when it is actually not usable, but this is I think due to a Blizzard bug. I can't seem to reproduce it at will, though people suggest the cause of it in the threads I will link below.

As a safety measure, though not tested is it possible to do a IsUsableSpell() check on it. That should return a false I hope even when it is bugged out, because it appears at least on the action bar as not usable.

Can this:
`usable = function () return cooldown.fists_of_fury.remains > 0 and cooldown.rising_sun_kick.remains > 0 end,`

Be replaced with something like:
`usable = function () return cooldown.fists_of_fury.remains > 0 and cooldown.rising_sun_kick.remains > 0 and IsUsableSpell("Whirling Dragon Punch")  end,`

as a work around for the blizzard bug.

Forum Threads:
https://eu.forums.blizzard.com/en/wow/t/whirling-dragon-punch-is-bugged-bug/27581
https://eu.forums.blizzard.com/en/wow/t/whirling-dragon-punch-sometimes-not-usable-even-though-rsk-fof-are-on-cooldown/29747
https://eu.forums.blizzard.com/en/wow/t/bugs-windwalker-monk/34511
https://old.reddit.com/r/wow/comments/a7d65s/whirling_dragon_punch_not_working_properly/

**Comment by behub-au** [comment]
Just IsUsableSpell("Whirling Dragon Punch") actually would return the same result as 'cooldown.fists_of_fury.remains > 0 and cooldown.rising_sun_kick.remains > 0' as well.

**Comment by Hekili** [comment]
That doesn't work for forecasting, however.  IsUsableSpell works for *now* but not anything after now.

**Comment by behub-au** [comment]
I figured. Just trying to do more than just report and offer a solution. The rotation can just get stuck on you using this ability until a action higher on the priority comes up.

**Comment by Hekili** [comment]
Yup, I will test using that for the primary icon and cooldown info for the
secondary recommendations.

**Comment by Hekili** [comment]
Let me know if the later builds/alphas address this for you.  I'm aware of the bug on the Blizz side but I can't duplicate it in my Monk's gear.

**Comment by behub-au** [comment]
Been using this for a few days now. Have had no issues with the new logic. Appreciate the changes!

**Comment by Hekili** [comment]
Great, thanks!
