### ISSUE TITLE
Necrolord Fleshcraft Classified as Covenant Ability, Should be Defensive

### ISSUE THREAD

**Issue by GamingSeat** [Hekili/hekili#1140]
---Necrolord Fleshcraft Defensive---
Fleshcraft is being suggested mid fight by rotation across multiple specs while covenant abilities are enabled, it should be classified as a defensive as it isn't integral to a dps rotation by default and disabling covenants to get it out of the rotation causes useful abilities like bone spear(rogue), death chakrams(hunter), and other abilities to be cut from your rotation causing dps loss.

to reproduce
1. turn on covenant abilities
2. will automatically be suggested as a priority spell
3. disable covenant abilities and it will stop being suggest but this removes dps covenant abilities from rotation

Expected behavior: Fleshcraft should not be getting suggested when covenant abilities are on, only when defensives are on.

Screenshot: Not needed, happens on all classes using necro cov.

**Comment by Hekili** [comment]
This was intentionally added to your sim priorities.  Do you have sims that show you doing more DPS with the in-combat Fleshcraft removed?

**Comment by GamingSeat** [comment]
> This was intentionally added to your sim priorities. Do you have sims that show you doing more DPS with the in-combat Fleshcraft removed?

What would be an easier way to show that as casting fleshcraft is just down time with no damage gains as its purely defensive with no offensive benefits at all

Or how would I specify the non use of fleshcraft in a sim?

**Comment by Hekili** [comment]
Link your sim.

**Comment by GamingSeat** [comment]
# Nysteji - Outlaw - 2021-07-04 17:15 - US/Thrall
# SimC Addon 9.1.0-01
# Requires SimulationCraft 910-01 or newer

rogue="Nysteji"
level=60
race=blood_elf
region=us
server=thrall
role=attack

talents=2132322
spec=outlaw

covenant=necrolord
soulbind=plague_deviser_marileth:4,323074/241:3:0/323091/230:3:0/323081
# conduits_available=238:3/239:4/241:3/242:3/245:3/246:4/248:3/227:1/240:3/247:3/234:2/230:3/232:4
renown=17

head=,id=180915,bonus_id=7198/1494/6616
neck=,id=173146,gem_id=168637,bonus_id=7185,drop_level=60,crafted_stats=40
shoulder=,id=172319,bonus_id=7121/6717/6649/6650/1507
back=,id=178755,bonus_id=6807/6652/1498/6646
chest=,id=180904,bonus_id=7199/1501/6646
tabard=,id=69210
wrist=,id=178847,bonus_id=7376/7359/6652/7193/1498/6646
hands=,id=178757,bonus_id=6807/6652/1498/6646
waist=,id=181587,bonus_id=6652/7194/1472/5878/6616
legs=,id=178801,bonus_id=6806/6652/1485/4785
feet=,id=180908,bonus_id=7198/1494/6616
finger1=,id=178871,bonus_id=7376/7359/6652/6935/1498/6646
finger2=,id=178933,bonus_id=6807/6652/7193/1498/6646
trinket1=,id=178715,bonus_id=7362/7359/6652/6923/1498/6646
trinket2=,id=178811,bonus_id=6807/6652/1498/6646
main_hand=,id=180095,bonus_id=7390/7359/6652/1498/6646
off_hand=,id=181215,bonus_id=6652/1472/5868/6616

### Gear from Bags
#
# Bladesworn Wraith's Visage (164)
# head=,id=182259,bonus_id=7196/1481/6616
#
# Shoulders of the Sanguine Monstrosity (72)
# shoulder=,id=159323,bonus_id=4817/1485/4785/6259
#
# Ebony Death Shroud Spaulders (190)
# shoulder=,id=180920,bonus_id=7200/1507/6646
#
# Bladesworn Battle Standard (1)
# back=,id=181803
#
# Kael's Dark Sinstone Chain (1)
# back=,id=180941
#
# Shroud of Winter's Chill (158)
# back=,id=117375,bonus_id=7191,drop_level=60
#
# Ashjra'kamas, Shroud of Resolve (133)
# back=,id=169223,bonus_id=6276/1472
#
# Bladesworn Wraith's Cloak (177)
# back=,id=182267,bonus_id=7198/1494/6616
#
# Blighted Margrave's Cloak (171)
# back=,id=178755,bonus_id=6806/6652/1485/4785
#
# Freshly Embalmed Jerkin (184)
# chest=,id=178744,bonus_id=7358/7359/6652/1498/6646
#
# Raiment of the Blighted Tribe (72)
# chest=,id=159335,bonus_id=4817/1485/4785/6257
#
# Tabard of Summer Skies (1)
# tabard=,id=35279
#
# Soulstalker Bindings (174)
# wrist=,id=181187,bonus_id=41/7194/1472/5871/6616
#
# Bladesworn Wraith's Armguards (164)
# wrist=,id=182266,bonus_id=7196/1481/6616
#
# Radiant Light Binders (171)
# wrist=,id=178847,bonus_id=6806/6652/7194/1485/4785
#
# Gloves of Obscure Rituals (171)
# hands=,id=178757,bonus_id=6806/6652/1485/4785
#
# Bladesworn Wraith's Stranglers (171)
# hands=,id=182262,bonus_id=7197/1488/6616
#
# Bladesworn Wraith's Belt (155)
# waist=,id=182265,bonus_id=7195/1472/6616
#
# Bladesworn Wraith's Breeches (155)
# legs=,id=182263,bonus_id=7195/1472/6616
#
# Soulfeather Breeches (171)
# legs=,id=179324,bonus_id=6806/6652/1485/4785
#
# Depraved Darkblade's Treads of the Quickblade (129)
# feet=,id=177774,bonus_id=6907/43/1677,drop_level=60
#
# Primeval Soul's Ankleguards (171)
# feet=,id=179352,bonus_id=6806/6652/1485/4785
#
# Fleshfused Circle (184)
# finger1=,id=178869,bonus_id=6807/6652/7194/1498/6646
#
# Signet of the False Accuser (171)
# finger1=,id=178824,bonus_id=6806/6652/6935/1485/4785
#
# Sinful Aspirant's Medallion (158)
# trinket1=,id=184052,bonus_id=6793/1472/6616
#
# Fleshcrafter's Knife (184)
# main_hand=,id=178789,bonus_id=6807/6652/1498/6646
#
# Unburdened Hammer of the Peerless (131)
# main_hand=,id=176801,bonus_id=6908/6652/1685,drop_level=60
#
# Stoneguardian's Morningstar (171)
# main_hand=,id=178834,bonus_id=6806/6652/1485/4785
#
# Duskwarder Warclub (168)
# main_hand=,id=179547,bonus_id=6652/1472/5865/6616
#
# Duskwarder Warclub (168)
# off_hand=,id=179547,bonus_id=6652/1472/5865/6616
#
# Stoneguardian's Morningstar (171)
# off_hand=,id=178834,bonus_id=6806/6652/1485/4785
#
# Unburdened Hammer of the Peerless (131)
# off_hand=,id=176801,bonus_id=6908/6652/1685,drop_level=60
#
# Fleshcrafter's Knife (184)
# off_hand=,id=178789,bonus_id=6807/6652/1498/6646

**Comment by GamingSeat** [comment]
> Link your sim.

hope that was what you were asking for? or was it this https://www.raidbots.com/simbot/report/g9FdEgnifyAS9sT5qmeCD3

**Comment by Hekili** [comment]
Your sim is using Fleshcraft in combat, as well.

![image](https://user-images.githubusercontent.com/9438134/124400080-edce1d00-dced-11eb-8699-10858e5d9338.png)

**Comment by GamingSeat** [comment]
> Your sim is using Fleshcraft in combat, as well.
> 
> ![image](https://user-images.githubusercontent.com/9438134/124400080-edce1d00-dced-11eb-8699-10858e5d9338.png)

Yes i know, im saying it shouldnt at all, its flat down time, when i do it myself and IGNORE this piece of the rotation it leads to higher dps consistently in dungeons/boss fights, but the problem is the rotation is suggesting i use it when it should not be using defensive abilities with no offensive throughput in the middle of a rotation.

I dont make custom sims nor do I know how to remove the fleshcraft from the sim as I do not engineer sims, I'm trying to explain this from constant pulls over the course of a few days that fleshcraft, which has no damge output in anyway shape or form, is randomly thrown in the middle of a damage rotation for no reason. 

It is a defensive ability, not offensive ability, and should not be suggested when defensives are disabled. I'm not sure how else to explain it besides that. It has me randomly using a defensive in the middle of a high dps moment where im taking no damage because it doesnt understand what the abilities use case is and this is causing my rotations damage to drastically drop all of a sudden.

**Comment by Hekili** [comment]
It's used because it's not exclusively defensive with your soulbinds. There are buffs that you are foregoing if you don't use Fleshcraft.

You can disable Fleshcraft or set it up as a defensive ability in /hekili > Abilities > Fleshcraft.

**Comment by Hekili** [comment]
Good news.  Other specializations' priorities are rolling in via SimC that include Fleshcraft-in-combat related logic.  I am rolling that logic into the Rogue APLs and we'll see how this appears to perform.  The notable difference is, if Fleshcraft is recommended due to the Volatile Solvent, the recommendation will interrupt -- the addon's recommendations should show you using your next ability immediately rather than waiting for Fleshcraft to finish channeling.

For the Pustule Eruption soulbind, you'll still channel for the full duration.

![image](https://user-images.githubusercontent.com/9438134/124475368-a2f4e980-dd6f-11eb-9133-87e93fbe0902.png)

I may revisit this further and I'll keep an eye on updated sim profiles that fine tune this behavior.  I did some sim testing on my own last night and found that the full channel of Fleshcraft was basically DPS neutral on average, but it may be beneficial to avoid Fleshcraft toward the end of a fight.
