### ISSUE TITLE
Bloodthirst with Fresh Meat doesnt tell me to target swap

### ISSUE THREAD

**Issue by lonesniper52** [Hekili/hekili#1141]
**Describe the Bug/Issue**
I have Fresh Meat talented, Recommend target swaps checked. Hekili still doesnt tell me to bloodthirst another target

**Expected behavior**
to recommend me to bloodthirst another target to keep enrage up

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**https://pastebin.com/RMLENMij**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**https://pastebin.com/Vp0K2YM1**

**Comment by Hekili** [comment]
Thanks, this helped identify an issue -- Bloodthirst damage to secondary targets via Whirlwind was treating those secondary targets as having been hit by Bloodthirst with Fresh Meat.  I've put together a fix that seems to work.  I've also integrated some APL logic to better support this, though it may require additional tuning.

Basically:
1. Is Enrage up?  Then feel free to keep Bloodthirsting your current target.
2. Is Enrage down?  Then swap to a different target that you haven't hit with Bloodthirst (if any exist) before Bloodthirst.

The data regarding who you've hit with Bloodthirst is reset upon exiting combat, so it should be fine for target dummies for testing.
