### ISSUE TITLE
SV Hunter nessingwary's trapping apparatus not recommending freezing/tar traps

### ISSUE THREAD

**Issue by wolf654** [Hekili/hekili#1142]
Hi, First thank you so much for the add-on. Ive found that while using NTA legendary, the add-on does not recommend Freezing or Tar traps as part of the rotation. According to sims, they should be there on CD. After rooting around a bit, I did see the Action list in the add-on does have an "nta" entry. Im not sure why, or if it is significant, but this entry and a few others are white while "default" and "precombat" are blue. 
Looking at the "nta" list shows all 3 traps (steel, freezing and tar). Freezing and tar both have these conditions 
"! buff.wild_spirits.remains | buff.wild_spirits.remains & cooldown.kill_command.remains"
I removed them and still wasn't able to make all 3 traps appear in the normal rotation.
<img width="909" alt="Screen Shot 2021-07-05 at 10 45 39 AM" src="https://user-images.githubusercontent.com/86976320/124505988-9082ac00-dd7f-11eb-8347-8f39b4eb6bca.png">

**Comment by Hekili** [comment]
Please follow the instructions when submitting an issue ticket.

**Comment by wolf654** [comment]
Okay,

1-v9.1.0-1.0.5 (2021-07-05)
2-I can find no other posts regarding this issue.

**To Reproduce**
Equiping Nessingwary's legendary does not result in freezing and tar traps to be included in the rotation.

**Expected behavior**
Equiping Nessingwary's legendary should result in freezing and tar traps be included in the rotation.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/bipM5MxY

**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/ZHNaJ8hX

**Comment by Hekili** [comment]
I'll take a look, but it's much easier if you put those on Pastebin and supply the links here.

**Comment by wolf654** [comment]
Gah sorry, if it isn't obvious yet, <noob. And thanks again.

**Comment by Hekili** [comment]
The entry that calls the "nta" list uses `runeforge.nesingwarys_trapping_apparatus.equipped` -- the addon doesn't use `equipped` for that field right now.  It'll be fixed later this evening.

**Comment by wolf654** [comment]
Thank you!

**Comment by Hekili** [comment]
This is resolved -- the addon can now handle misspelled nesingwarys vs. nessingwarys.
