### ISSUE TITLE
Cancel bladestrom fury warrior not recomending

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#1143]
Cancel bladestrom not in recomendations after update and i didint change anything

**PUT ISSUE REPORT LINK HERE:**

build: v9.1.0-1.0.5
level: 60 (60)
class: WARRIOR
spec: fury

talents: anger_management
    bladestorm
    cruelty
    fresh_meat
    massacre
    storm_bolt
    warpaint

pvptalents: none

covenant: venthyr

conduits: ashen_juggernaut = 7
   brutal_vitality = 6
   depths_of_insanity = 6
   safeguard = 7

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   familiar_predicaments = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: breastplate_of_brutal_dissonance = 1
    ceremonial_parade_legguards = 1
    charm_of_eternal_winter = 1
    dealer_xyexas_cape = 1
    distorted_constructs_gauntlets = 1
    errant_crusaders_greaves = 1
    girdle_of_the_soulflayer = 1
    hellhound_cuffs = 1
    inscrutable_quantum_device = 1
    quick_oxxein_ring = 1
    rimebinders_runeblade = 1
    shadowghast_ring = 1
    stone_legion_heraldry = 1
    unyielding_combatants_pauldrons = 1
    wing_commanders_helmet = 1
    zinkhas_blade_of_the_fallen_god = 1

legendaries: signet_of_tormented_kings = 1

itemIDs: 173133, 178780, 178802, 178812, 178926, 179326, 179330, 179349, 179350, 180099, 180104, 183002, 183018, 183027, 183040, 184027

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_ww_range = true
    heroic_charge = false

toggles: cooldowns = false
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = false 
    interrupts = false 
    mode = aoe 
    potions = false 

 
**PUT SNAPSHOT LINK HERE:**

3.  https://justpaste.it/8t1qq

**Comment by mati3464** [comment]
Updated pastebin:

https://pastebin.com/wbvKxSYp

Video: Recomendations are in top left corner for this test , i get 100 rage + execute phase 

https://www.youtube.com/watch?v=82KBaPPk-ms

**Comment by Hekili** [comment]
We resolved this in Discord.
