### ISSUE TITLE
Enhancement Shaman Windfury Totem

### ISSUE THREAD

**Issue by SpatenLa** [Hekili/hekili#1146]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
Latest

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**Windfury Totem gets reccomended with Doom winds while its already up and doom winds debuff is there** 

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

Drop totem fight!

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/WXHxJwfw

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/N45a2XBd

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
It's weird -- the addon can't see that you have Windfury Totem applied.  Can you see the spell ID for Windfury Totem when you drop it?

**Comment by SpatenLa** [comment]
327942, but could also be a issue with the worldboss because that thing is a bit weird wit LoS

**Comment by Hekili** [comment]
I think the compromise here is to not allow Windfury to be recast while Doom Winds is up at all.  So I'm trying that.

**Comment by Hekili** [comment]
1.0.7a should prevent this, though the addon will still be spammy about WFT outside of Doom Winds if there are LOS issues.
