### ISSUE TITLE
Balance CDs are not being requested

### ISSUE THREAD

**Issue by panchitojr** [Hekili/hekili#1147]
Convoke (only deep into the rotation) and Incarnation (not at all) are not being suggested.

including the 2 paste bin of a test dummy fight. let me know if you need any more info. 

https://pastebin.com/ukLzVYFD

https://pastebin.com/sx1RNPjd

**Comment by Wraithlord45** [comment]
having similar issue with Venthyr druid. trinket is recommended but not Incarn/Frenzy
https://pastebin.com/iA9K8Nd3
https://pastebin.com/mxEPPxfX
https://pastebin.com/HHmYNFjs
https://pastebin.com/1s81DRNr

**Comment by Hekili** [comment]
Downloaded most recent update and tried the priority on training dummies. Incarn/Frenzy is not being recommended but IQD is now.

pastebin.com/iA9K8Nd3
pastebin.com/mxEPPxfX
pastebin.com/HHmYNFjs
pastebin.com/1s81DRNr

**Comment by Hekili** [comment]
> Convoke (only deep into the rotation) and Incarnation (not at all) are not being suggested.
> 
> including the 2 paste bin of a test dummy fight. let me know if you need any more info.
> 
> [pastebin.com/ukLzVYFD](https://pastebin.com/ukLzVYFD)
> 
> [pastebin.com/sx1RNPjd](https://pastebin.com/sx1RNPjd)

Snapshots before getting into combat and even getting into Moonkin Form aren't really useful.  Remember that snapshots should be taken when the problem you're concerned about are happening.  I.e., your trinket is recommended before your CDs.

**Comment by Hekili** [comment]
If you swap your trinket slots, do you notice any change?  Can you sim yourself and provide a Raidbots link?

**Comment by Wraithlord45** [comment]
Yeah, I swapped IQD with Unbound Changeling and it recommends CA/Frenzy properly.

Raidbots sim https://www.raidbots.com/simbot/report/t5W4ntyPvKaqvQNTYFMfeB

**Comment by Hekili** [comment]
Try 1.0.7b-beta1 when it's finished building.

**Comment by panchitojr** [comment]
I am still having the no incarn issue with late convoke. but also, while looking at the snapshot its stating i have incarn toggled off. i dont know why when i have CDs enabled. could i be missing something?


https://pastebin.com/Ncjc39e1

**Comment by Hekili** [comment]
Can you quote the part where you think it says Incarnation is toggled off?

**Comment by Hekili** [comment]
Oh wait, I see it.  Do you have cooldowns shown separately?

**Comment by panchitojr** [comment]
no. only change ive done from default was add convoke to the cooldowns on the toggles.

**Comment by Hekili** [comment]
You have your cooldowns toggle turned off, and Incarnation is a cooldown by default.

**Comment by panchitojr** [comment]
In the setting menu i have it enabled which is why convoke comes up but late in the rotation. even with the shortcut key i toggle it to show cooldowns: on.

**Comment by Hekili** [comment]
`toggles: cooldowns = false`

If you have a similar problem with Cooldowns toggled on, you'd need to submit a snapshot showing that.

**Comment by panchitojr** [comment]
Here is my snapshot with CDs off.

https://pastebin.com/NK1i9RVJ

now its stating that the cooldowns + true while in fact are off. hence no convoke or incarn. so weird.

**Comment by Hekili** [comment]
I think you're mistaken.  You can show screenshots of your Toggles tab along with your snapshot, though.
