### ISSUE TITLE
Balance Druid not using CDs with the new trinket from raid (see wowhead link)

### ISSUE THREAD

**Issue by munkafan** [Hekili/hekili#1151]
Snapshot:
https://pastebin.com/rwsyak7V

Trinket:
https://ptr.wowhead.com/item=186422/tome-of-monstrous-constructions?bonus=4799:4786:1485&ilvl=239#dropped-by

Sim:
https://www.raidbots.com/simbot/report/o8tMyvTJuZPhA5MdG26yz

**Comment by Hekili** [comment]
This may be fixed in 1.0.8a-beta1, please test and let me know.
