### ISSUE TITLE
Border Option Not Disabling

### ISSUE THREAD

**Issue by derekengel** [Hekili/hekili#1152]
I am using version v9.1.0-1.0.8.  I open the configuration of the addon, go to Displays > Primary  > Border, and uncheck enable.  This does not seem to do anything.  To verify I also tried changing the border color to something like red.  When selecting this color and going back in, it just goes back to the default color.

The goal is that I also use Masque and would like to get rid of the borders.  Notice in the screenshot the borders showing?

![image](https://user-images.githubusercontent.com/8973148/125016177-e042cb00-e03e-11eb-9f28-9c6e76f00331.png)

**Comment by Hekili** [comment]
Load Hekili by itself and see if the border is removed.  It looks to me like you have multiple addons skinning it.

**Comment by derekengel** [comment]
Yes that did the trick.  Thank you for the prompt reply.
