### ISSUE TITLE
[Bug] Cd not show

### ISSUE THREAD

**Issue by Naik93** [Hekili/hekili#1154]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an existing, open ticket for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I use the addon on my rogue and balance, but in the rotation don't show shadow blade or the talent like marks of death, and on the balance don't show Celestial Alignment or the talent too

### How to Reproduce

I use the addon on my rogue and balance, but in the rotation don't show shadow blade or the talent like marks of death, and on the balance don't show Celestial Alignment or the talent too

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hekili** [comment]
Cooldowns are toggled off by default, so that you can control when you want them to show up.  See /hekili > Toggles.
