### ISSUE TITLE
[BUG] Error fired when clicked on the "Issue Reporting" tab

### ISSUE THREAD

**Issue by gi2k15** [Hekili/hekili#1157]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

This error is immediately fired when I click the "Issue Reporting" tab in the options menu.

### How to Reproduce

Open the Options and click in the "Issue Reporting" tab.

### Player Information (Link)

Issue Reporting isn't working

### Error Messages (Link)

https://pastebin.com/mCYREQYh

**Comment by Hekili** [comment]
Thanks, this one is painfully ironic and funny.  Looks to be simple to fix.

**Comment by Hekili** [comment]
I have a testfix going into 1.0.10-beta1 in a few minutes.  Can you give me some character information since Issue Reporting wasn't working for you?  How do I replicate this?  Ret Paladin?  Any spec?  Every spec?

**Comment by gi2k15** [comment]
Weird, I've tested with other toons now and it's working. Went back to my main (ret pally) and started working again too. Maybe an addon conflict?

build: v9.1.0-1.0.9
level: 60 (60)
class: PALADIN
spec: retribution

talents: cavalier
    divine_purpose
    final_reckoning
    fires_of_justice
    repentance
    selfless_healer
    zeal

pvptalents: none

covenant: kyrian

conduits: focused_light = 5
   golden_path = 5
   lights_barding = 5
   resplendent_light = 6
   shielding_words = 5

soulbinds: [kleia]
   cleansing_rites = 1
   hope_springs_eternal = 1
   mentorship = 1
   pointed_courage = 1
   valiant_strikes = 1

sets: none

gear: breastplate_of_cautious_calculation = 1
    charm_of_eternal_winter = 1
    colossal_plate_gauntlets = 1
    cowled_batwing_cloak = 1
    epaulettes_of_overwhelming_force = 1
    errant_crusaders_greaves = 1
    fused_bone_greatbelt = 1
    gorewrought_greatsword = 1
    macabre_sheet_music = 1
    manabound_mirror = 1
    ritualists_treasured_ring = 1
    seal_of_the_panoply = 1
    selfless_collectors_greathelm = 1
    shadowghast_greaves = 1
    tabard_of_the_ascended = 1
    vambraces_of_verification = 1

legendaries: shock_barrier = 1

itemIDs: 171416, 174289, 178734, 178991, 181694, 182984, 182987, 182994, 183027, 183034, 183037, 183040, 184024, 184029, 185815, 185840

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Retribution
    petbased = false
    potion = spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = true

toggles: cooldowns = true
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = single 
    potions = false

**Comment by Hekili** [comment]
Could've been an addon conflict, could've been anything.  It doesn't look like we have a way to explore it further so I'll close this ticket.  Feel free to open another ticket if you see this again.
