### ISSUE TITLE
Destro Warlock Mythic Stormwall disappears

### ISSUE THREAD

**Issue by Gendolin** [Hekili/hekili#116]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**

During Stormwall blockade, (i am ranged, thus starting at sister (Mythic)) once brother swaps to our boat, my hekili either fully disappears or 3 of the 4 boxes dissapear. Once the add comes my spells temporarly appear again before disappearing once again. The same thing happens in phase 2 when the sirens show up, the whole thing disappears whilst bugsack keeps screeching "fatality" 

**Screenshots**
https://gyazo.com/f851ef48b5eafc6ca12cb5d4d84955cb
https://gyazo.com/99c106cff8a07ead69f17405246b3854
https://gyazo.com/bf1e51bf4eef4a23b1f516f6d8c0c0d1

**WHEN SUBMITTING AN ISSUE:**

1.  https://pastebin.com/m6mq3d95

**PUT ISSUE REPORT LINK HERE:**

2.  when i go into hekili-snapshots bugsacker keep screaming fatality, no snapshots generated
 

3. https://pastebin.com/N0pPuJX1

**Comment by Hekili** [comment]
Should be resolved in 8.1.5-13-alpha3 which will be available in a few minutes.

**Comment by Gendolin** [comment]
Cool, cheers for the quick reply
