### ISSUE TITLE
[REC] Gaurdian druid not showing aoe rotation properly

### ISSUE THREAD

**Issue by roreycorey** [Hekili/hekili#1160]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi I realised that on aoe on gaurdian druid it only recommends thrash and swipe and sometimes moonfire, i got this from icy veins. it never shows mangle at all on +2 targets or maul for rage dump

Keep Moonfire Icon Moonfire ticking on up to 2 targets.
Use Thrash
Use Mangle on up to 4 targets.
Use Moonfire with a Galactic Guardian Icon Galactic Guardian on up to 3 targets.
Use Maul to dump Rage on up to 3 targets, if you do not need the Rage for Ironfur or Frenzied Regeneration.
Use Swipe.
This means that on 4+ targets, your rotation will consist exclusively of Thrash, Mangle and Swipe.

### How to Reproduce

try and incorporate up to a limited number of targets if possible or maybe i can do myself? thanks.

### Snapshot (Link)

https://pastebin.com/z7WSzbWR

### Contact Information

Cravenator#7728

**Comment by Hekili** [comment]
Thanks for the details.  The comparison to be made isn't guide vs. addon, it would be sim vs. addon.  Could you sim yourself (in an AOE scenario) and link your sim on Raidbots?  Thanks!

Also, keep in mind, you have a spec option available that will cause you to use Mangle more often.  See /hekili > Guardian.

**Comment by roreycorey** [comment]
https://www.raidbots.com/simbot/report/avAY1MpH67RQanhkSVbrF
[https://www.raidbots.com/simbot/report/avAY1MpH67RQanhkSVbrF/preview.png]<https://www.raidbots.com/simbot/report/avAY1MpH67RQanhkSVbrF>
Quick Sim - Trynkitts - 2,795 DPS - Raidbots<https://www.raidbots.com/simbot/report/avAY1MpH67RQanhkSVbrF>
/
www.raidbots.com


________________________________

**Comment by Hekili** [comment]
Using DungeonSlice is misleading, because you're dealing with a variety of group sizes at different points in the sim.

I ran a sim of your profile with 4 enemies sustained:

https://www.raidbots.com/simbot/report/oy5YB87VB1jRj9Y8cofDnP/simc

Mangle *never* gets used in the sim, under those circumstances.  It's a good argument that the sim should be revised.

**Comment by Hekili** [comment]
Relaxing the target # requirements didn't produce an increase in DPS:

https://www.raidbots.com/simbot/report/uyyh6HtjZn4A35rr5MaNk4/simc

**Comment by roreycorey** [comment]
So you think that the Sim is misleading? Thanks On 12 Jul 2021 19:38, Hekili ***@***.***> wrote:
Using DungeonSlice is misleading, because you're dealing with a variety of group sizes at different points in the sim.
I ran a sim of your profile with 4 enemies sustained:
https://www.raidbots.com/simbot/report/oy5YB87VB1jRj9Y8cofDnP/simc
Mangle never gets used in the sim, under those circumstances.  It's a good argument that the sim should be revised.

**Comment by Hekili** [comment]
The DungeonSlice sim adds in a lot of changing circumstances; different group sizes, timings, etc.  So it's simply not a clean comparison.

What you're concerned about is that the addon doesn't recommend Mangle with 3+ targets.  If you sim, you find out that the sim doesn't either (so Mangle is getting used, in DungeonSlice, when there are fewer targets -- so is the addon).

If you set up an apples-to-apples comparison where we're looking at more than 3 targets the whole fight, the sim doesn't Mangle.  The addon doesn't either.  Some quick edits to the priority for comparison's sake don't result in a performance improvement.

![image](https://user-images.githubusercontent.com/9438134/125339823-b54ac680-e31f-11eb-9425-2a2d27ad7de1.png)

https://www.raidbots.com/simbot/report/doqFPvfnaCGra7vnr5X4y2/simc

The "MangleMore" profile will use Mangle at up to 4 targets, even over Swiping (that's what it takes to get Mangle on the board).  And it's a performance loss.

Guides often get written based on accepted truisms, but ideally, guide writers would have sims that support the advice they're giving.  That could mean that guides are right and they just don't have a supportive sim, or that sims don't support what they're saying but it doesn't matter enough for their purposes.  It's hard to know.

**Comment by Hekili** [comment]
Maul usage, on the other hand, is simply more conservative within the addon, by design.  This is because your Rage is used both for your aggro/DPS and for your mitigation.  The addon is conservative about spending your resources that are used for mitigation, since you'll probably die if you can't mitigate damage and you're actually tanking.

**Comment by roreycorey** [comment]
Yes of course, thanks for your help dude, there is one more thing I don't like convoke where it normally is so I put it into cooldowns, I realize then that it doesn't show up if I have usable trinket On 12 Jul 2021 19:49, Hekili ***@***.***> wrote:
Maul usage, on the other hand, is simply more conservative within the addon, by design.  This is because your Rage is used both for your aggro/DPS and for your mitigation.  The addon is conservative about spending your resources that are used for mitigation, since you'll probably die if you can't mitigate damage and you're actually tanking.

**Comment by Hekili** [comment]
You'd need to submit a snapshot of that trinket scenario if you want that to be investigated.

**Comment by roreycorey** [comment]
No problem thanks for your time and help.On 12 Jul 2021 20:36, Hekili ***@***.***> wrote:
You'd need to submit a snapshot of that trinket scenario if you want that to be investigated.
