### ISSUE TITLE
[SURV] Doesn't often use bombs in AOE scenarios 

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1161]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When 2+ targets start fighting, I want to see the frequent uses of bombs. But the addon ignores the AOE and follows the bomb scenario in ST mode. Ultimately, our legendary Wildfire Cluster power is not 100% realized in AOE scenarios. I want Bombs to be used frequently. Here in my sim here it is clearly shown in the rotation which sequence is going on.  https://www.raidbots.com/simbot/report/r6YG6i11JwTW99kgt2Mwac

### How to Reproduce

1. Специализация Survival Hunter.
2. Talent set 3,1, X, 1, X, 1, 2 equipped with the legendary power of the Wildfire Cluster.
3. Accepted Kyrian Covenant and Medium Mikanikos
4. We go to the mannequins in the citadel of kiriya where there are 5 targets.
5. We go to the citadel of kiriya to 5 dummy.
6. Use trinket
7. Serpent Sting
8. Resonating Arrow
9. Wildfire Bomb
10. Carve
And after that, the addon is waiting for 2 bomb, but we have 1 bomb that we can use.

### Snapshot (Link)

https://pastebin.com/zUHDdQTg

### Additional Information

I attach https://pastebin.com/uf0w4NwH with ST rotation. So that you can compare that there is absolutely no difference except the addition of a new ability and Carve. And I also fit a sim with ST rotation. https://www.raidbots.com/simbot/report/dveNyFqQrp6YTnTdpvRXru.

### Contact Information

narvell3#3571

**Comment by Hekili** [comment]
See if 1.0.11-beta2 resolves this and let me know.

**Comment by geraint425** [comment]
The problem also remained, he still holds 1 bomb until the next one rolls back. He does not use them on CD. Here is attached without recommend target swaps https://pastebin.com/TWZkmL42 

But with the use of recommend target swaps, everything works more or less stably, except for what happens when you need to update the Serpent Sting on targets, we then have a delay in bombs https://pastebin.com/XwdPgNbK

**Comment by Hekili** [comment]
In your new snapshot, Kill Command's criteria passed before the addon would reach the entry where Wildfire Bomb would've been used.  Do a snapshot once Kill Command is on cooldown.

**Comment by geraint425** [comment]
I am adjusting https://pastebin.com/yBHDM0ff.

**Comment by Hekili** [comment]
That snapshot correctly uses Carve because Carve with Shrapnel Bomb ticking is higher priority than the other Wildfire Bomb entry.

```
actions.cleave=serpent_sting,cycle_targets=1,if=talent.hydras_bite.enabled&buff.vipers_venom.remains&buff.vipers_venom.remains<gcd
actions.cleave+=/wild_spirits
actions.cleave+=/resonating_arrow
actions.cleave+=/wildfire_bomb,if=full_recharge_time<gcd
actions.cleave+=/chakrams
actions.cleave+=/butchery,if=dot.shrapnel_bomb.ticking&(dot.internal_bleeding.stack<2|dot.shrapnel_bomb.remains<gcd)
actions.cleave+=/carve,if=dot.shrapnel_bomb.ticking
actions.cleave+=/death_chakram,if=focus+cast_regen<focus.max
actions.cleave+=/coordinated_assault
actions.cleave+=/butchery,if=charges_fractional>2.5&cooldown.wildfire_bomb.full_recharge_time>spell_targets%2
actions.cleave+=/flanking_strike,if=focus+cast_regen<focus.max
actions.cleave+=/carve,if=cooldown.wildfire_bomb.full_recharge_time>spell_targets%2&talent.alpha_predator.enabled
actions.cleave+=/kill_command,cycle_targets=1,if=focus+cast_regen<focus.max&full_recharge_time<gcd&(runeforge.nessingwarys_trapping_apparatus.equipped&cooldown.freezing_trap.remains&cooldown.tar_trap.remains|!runeforge.nessingwarys_trapping_apparatus.equipped)
actions.cleave+=/wildfire_bomb,if=!dot.wildfire_bomb.ticking
...
```

There's a high priority Wildfire Bomb entry that uses WfB when you're close to capping charges.

The next WfB entry is halfway down the list, after several entries for other abilities.  So far you haven't supplied a snapshot where higher priority abilities were not ready/recommended and Wildfire Bomb wasn't used.

**Comment by geraint425** [comment]
Okay, I’ll try to go to Raid and M + again and check there again. Just looking at the Simc rotation I saw Wildfire Bomb being used more often.

**Comment by Hekili** [comment]
Yeah, just remember, snapshots are for when you think it should show something *now* and it's not showing it.  So far, the examples you've provided always had a higher priority action ready to go.

I did remove an old restriction on usage of Wildfire Bomb from the addon code, and it may be more subtle than you realize.  You still have a lot of buttons to press before using your second Wildfire Bomb charge comes into play.

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/125331102-8891b180-e315-11eb-83e7-3540f667bf10.png)

Here's my Survival Hunter having the later Wildfire Bomb recommended.

```
46.  wildfire_bomb ( cleave - 14 )
The action (wildfire_bomb) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +2.33).
List ( cleave ) called from ( Survival:default:7 ) would PASS at 0.00.
active_enemies[4.00] > 2
 - this entry's criteria PASSES: ! dot.wildfire_bomb.ticking[false]
Action chosen:  wildfire_bomb at 0.00!
Returned from list (cleave), current recommendation is wildfire_bomb (+0.00).
- cleave
The recommended action (wildfire_bomb) is ready in less than 0.2s; exiting list (default).
```

**Comment by geraint425** [comment]
Yesterday I went to a raid and M + everything works. Thank you.

**Comment by Hekili** [comment]
Great news.  Thanks for updating.
