### ISSUE TITLE
[Bug] Feral Druid - Starfire suggested during solar eclipse

### ISSUE THREAD

**Issue by theitan** [Hekili/hekili#1163]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Feral Druid in Moonkin form I expect Wrath instead of Starfire during solar eclipse

### How to Reproduce

1. Login as Feral druid. 
2. Turn off Owlweaving.
3. Use Mookin form
4. Enter solar eclipse

### Snapshot (Link)

https://pastebin.com/zKyZ1E09

**Comment by Hekili** [comment]
Have you simmed your character to see if the same thing happens in your sims?  If so, provide a link.

**Comment by Hekili** [comment]
Okay, definitely found an issue there.  One challenging piece is that for Balance, Eclipse states update on cast.  For Feral, they update on impact.

**Comment by Hekili** [comment]
This should be resolved in 1.0.11-beta3.  If you could test and confirm it works more like you expect, I'd appreciate it.

**Comment by theitan** [comment]
Now moonking form works perfect. But owlweaving is broken after update, it stuck with sunfire
https://pastebin.com/pFBNnKwd

**Comment by Hekili** [comment]
1.0.12-beta2 should resolve that.
