### ISSUE TITLE
Keeps wanting me to drop Windfury totem on some encounters.

### ISSUE THREAD

**Issue by Thera83** [Hekili/hekili#1165]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I've  seen this now on two bosses 1. Mor'geth, Tormentor of the Damned (new 9.1 world boss) & 2. Gul'dan in The Nighthold (only attempted on mythic). 

What is happening when the encounter is engaged at some point during combat it keeps wanting me to drop Windfury Totem every other or every third ability. This happens regardless whether Doom Winds (only noticed it when running the DW legendary) is on CD or not.  It seems to happen both when AOE & ST mode are currently active. Not sure if its talent related but I run 2/1/1/1/2/3/3

I have downloaded the newest version of the addon and even disabled all other addons and it still seems to happen. However, I did not notice bug doing Sanctum or Domination heroic or mythic so, it seems to be encounter specific. 

### How to Reproduce

1. Enter gamer as an enhance shaman. 
2. Head to the new world boss Mor'geth and/or mythic Gul'dan in Nighthold.
3. Ensure Doom Winds Legendary is equipped
4. Engage the encounter.

### Player Information (Link)

https://pastebin.com/kCwG3zAV

### Error Messages (Link)

N/A

### Additional Information

Bugsack/Buggrabber did not show any errors

### Contact Information

Thera#1125 (Discord)

**Comment by Hekili** [comment]
This is the wrong kind of ticket; you'll need to supply a snapshot.  You can resubmit as a recommendation issue if you'd like.

**Comment by Thera83** [comment]
I apologise first time doing a ticket. I will resubmit
