### ISSUE TITLE
Kyrian Arcane Mage Rotation

### ISSUE THREAD

**Issue by Nubbz1992** [Hekili/hekili#1166]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am attempting to create a priority list within the Hekili addon. I copy pasted the kyrian 45 second sync rotation provided via [toegrinder](https://docs.google.com/document/d/1LZXWSUsaTo6GlKWo_FPKNjxD0PYcL-IeLUDX1bhNoUo/edit#)  within his guide .... [Kyrian Arcane 45 Second APL](https://pastebin.com/4f83ache). I noticed when going into action list i am not seeing any priorities being added so I made a copy of the original arcane profile updated the apl and it seems to be not properly syncing the cooldowns correctly. 

### How to Reproduce

Creating a new arcane profile and adding the [apl ](https://pastebin.com/4f83ache)

### Snapshot (Link)

https://imgur.com/MZ0ZpCh

### Additional Information

Is there a way I can properly import the Harmony priority list also making it so that radiant spark will try to sync up with ring of power and touch of the magi?

**Comment by Hekili** [comment]
Custom priorities are not supported.  If they have their priority integrated into SimulationCraft, I'll carry out that work.

> I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).
