### ISSUE TITLE
After the first cast, the first box shows a scroll symbol - does this mean it can't display the button properly? [screenshot]

### ISSUE THREAD

**Issue by metalmight** [Hekili/hekili#1168]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After the first cast, the first recommendation box shows a scroll symbol - does this mean it can't display the button properly?
![WoWScrnShot_071421_205841](https://user-images.githubusercontent.com/25989333/125727434-26b9f7dc-0066-4fc9-8451-66bee524cd0f.jpg)

### How to Reproduce

1. Enter game as a Worgen Balance Druid.
2. Start fighting a Larion in Bastion.
3. View the scroll icon in the first recommendation box

### Player Information (Link)

https://pastebin.com/ucQCSrq1

### Error Messages (Link)

n/a

### Contact Information

jshc559@yahoo.com

**Comment by Hekili** [comment]
Nope, that's a trinket.

When you pause (`ALT-SHIFT-P` by default), you can mouseover the icon to see more info.
