### ISSUE TITLE
[FEATURE]  Is it possible to make some abilities so that the addon uses them only within the radius of action?

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1170]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello. I have been playing with your addon for a long time. And I notice more and more on different classes and abilities one thing that is wildly annoying. I will take DK as an example. The FDK has the ability Ruthless Winter Addon recommends it regardless of whether I am close to the target or not. And for the radius of action for which it inflicts damage only in the vicinity of the target. BDK (Blood Boil) Surv (Сarve) also has such abilities. This is why the addon ignores their range by the type of such methods and recommends using them at a distance, when their action is realized only when they are close to the target. Please, if it's not difficult to see if it is possible to bind them to the range.

**Comment by Hekili** [comment]
This has come up in other conversations, and honestly, it confuses me a great deal.

You're melee.  You should be in range of things.  If you're out of range of things, you're probably not going to press optimal buttons.  When you're out of range, it's not optimal to tell you to push suboptimal buttons.  It's optimal to tell you to get in range.

The addon doesn't "ignore their range" -- those spells don't have a range in the sense that you can't use them based on range.

So far, I'm not persuaded that I should change the addon's recommendations to be wrong when people are out of range of a boss.

**Comment by mickeygeecom** [comment]
I would agree with Hekili on this one.

It could be a toggle though.

**Comment by geraint425** [comment]
Well, there are moments figuratively when you need to follow the mechanics of the battle, and not the rotation, and I'm already used to the fact that if the ability is red, then I'm out of range and I need to come closer, or not press it at all. And it turns out the addon simply recommends me to push the ability into the void. For example, I take into account the moments where there are dashes or you need to wait in a certain place and there, of course, you can already see. But in battle, let's say where there are a lot of movements and you need to follow the boss there, you can easily make a mistake and press this ability into the void. It's just that I'm not asking to invent a bicycle there, it's just banal to tie these abilities to the fact that they work in the vicinity when it will be effective. So that when I departed it would just be painted red like all other abilities. This will greatly simplify the task of keeping track of the rotation. And more attention will be paid to the mechanics of the boss fight.

**Comment by Hekili** [comment]
Yes, and when you're focusing on mechanics, you can handle them.  I believe in your ability to not hit Thrash when you're out of range and you know you can't get in range due to mechanics.  You don't have other meaningful filler to hit in that scenario, either.

What recommendation do you want when you're melee and out of melee range?

**Comment by p4nchez** [comment]
change under display -> range check to "melee" and you should get your red icon everytime out of range

![grafik](https://user-images.githubusercontent.com/29162840/126045986-ad2ac381-fddf-4784-a16e-461cd57c13b2.png)

**Comment by Hekili** [comment]
That doesn't work in this case, because Thrash doesn't actually have a range associated with it.  I can add one, but I have to make sure to account for talents/effects that alter the range, which is annoying.

**Comment by p4nchez** [comment]
i dont need added this no worry
but in my case if i set range checking to "melee range" my primal wrath, thrash, brutal slash will be marked as red icon if im not near my target

![grafik](https://user-images.githubusercontent.com/29162840/126046185-f3facfe8-af7b-4cb7-93fa-73d78fbc9a85.png)

**Comment by p4nchez** [comment]
same here if i target the thrid dummy out of meele range it will get my icon red until i move in range
![grafik](https://user-images.githubusercontent.com/29162840/126046209-ffb8fa77-f737-46de-9560-bd56f959dde0.png)
