### ISSUE TITLE
[REC] Night Fae Balance Druid - Non-CA Convoke being recommended at end of trash pack fights

### ISSUE THREAD

**Issue by woefulwabbit** [Hekili/hekili#1171]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

[This recent commit](https://github.com/Hekili/hekili/commit/5ea454414f15fab924dd91733ffaf1dbc2dbc47a) causes Convoke the Spirits to be recommended for Night Fae Balance Druids, regardless of whether the CA buff is up, at the end of all fights instead of only boss fights. This is probably not a good idea for M+ trash packs

### How to Reproduce

1. Enter the game as a Night Fae Balance Druid
2. Removeaura Pulsar buff, burn Celestial Alignment and click it off
3. Find random trash mob in the wild and follow normal rotation on it
4. When trash mob is almost dead, Convoke the Spirits will be recommended

### Snapshot (Link)

https://pastebin.com/WP1jrp0k

**Comment by Hekili** [comment]
I've added back a boss check to the Convoke recommendation.
