### ISSUE TITLE
Should not be recommending whirlwind when sweeping strikes is up

### ISSUE THREAD

**Issue by BigBong69** [Hekili/hekili#1172]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It's suboptimal to use whirlwind when sweeping strikes is up. 

As evidenced by the sim (standard 2 boss 5 minute patchwerk) it uses 0 casts of WW, however, the addon recommends using WW. This is likely due to the fact that hekili is attempting to use the HAC profile, which is incomplete (I've spoken to one of the guys working on it) as the HAC profile assumes many adds and therefore ignores the slam in the rotation. The default single target profile should suffice for AOE situations. (AKA use WW at 5 targets, or 3 targets if sweeping strikes is up) which is already defined in line 20 in hekili.

### How to Reproduce

1.Find a 2 target dummy (I used the one in NF covenant)
2.blow all other CDs.
3. turn on sweeping strikes
4. it should recommend slam, but it recommends WW instead.

### Snapshot (Link)

https://pastebin.com/nBMtdZ7X

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dizP3YWzkpyynBkqaEFJJp/simc

### Additional Information

N/A

### Contact Information

I Love OU#0854 (preferred)

**Comment by Hekili** [comment]
This should be resolved in 1.0.13.
