### ISSUE TITLE
[BUG] My keybinds have been completely removed from the hekili queue

### ISSUE THREAD

**Issue by ChrisOfRivia** [Hekili/hekili#1173]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![Screenshot_1](https://user-images.githubusercontent.com/87647232/126149239-98eb5840-7daa-4b5d-aba4-1576eaf2265a.png)

Since yesterday keybinds on my Hekili havent been showing on the top right of the ability. (I overrided the keybind for "Summon water elemental" to see if it would fix itself) 

![Screenshot_3](https://user-images.githubusercontent.com/87647232/126149516-00f2516b-6d50-491b-8a79-13c333e25cf3.png)
I have checked the Keybinds enabled for the "Primary" section and I still have the problem. 

### How to Reproduce

1. Addon works great
2. Downloaded a couple of different addons (LUI,Aurora, Narcissus, Talent Manager)
3. Keybinds don't show the next day
4. Tried only loading Hekili to see if it's because of other addons
5. Still have the problem 

### Player Information (Link)

https://pastebin.com/gHhAHpSS

### Error Messages (Link)

https://pastebin.com/ix1PBd19

### Contact Information

ChrisOfRivia#1070

**Comment by Hekili** [comment]
You're potentially using an unsupported action bar mod, or have set up your bars in an odd configuration.  Keybind detection in WoW is a weird and painful process, so if your configuration isn't reasonably similar to default action bars and action paging, you'll need to manually set your bindings on your abilities yourself.

You can do that in /hekili > Abilities and /hekili > Gear and Trinkets as appropriate.

**Comment by ChrisOfRivia** [comment]
Like I mentioned before, I used Hekili without any other addons loaded and
I still had the issue.

And keybinding every single ability from your menu is quite simply
impossible, considering all my alts I have to do this to.

Is there another solution?

**Comment by Hekili** [comment]
If you create a fresh Profile in Hekili, does that have any impact?

The issue most likely relates to how action slots are used between pages.  When you load Hekili by itself, your abilities are still moved from page 1 or 2 to 3, 4, 5, 6, etc.  The addon uses the binding from the lowest numbered page/slot combination barring a few exceptions related to stances/forms.  Can you tell if your abilities are using the lower action bar pages or not?

You could also `/dump Hekili.KeybindInfo` and Pastebin it and link it here.  That could offer a few clues.

**Comment by ChrisOfRivia** [comment]
Making new profiles in Hekili does not change anything. Yes, I am using the first 3 bars in WoW, Bar1, Bar2, Bar3. Here are some pictures.  ^^^Also, when inserting the command in the chat it displays: Dump: value=Hekili.KeybindInfo[1]={} Sent from Mail for Windows 10 From: HekiliSent: July 19, 2021 4:19 PMTo: Hekili/hekiliCc: ChrisOfRivia; AuthorSubject: Re: [Hekili/hekili] [BUG] My keybinds have been completely removed from the hekili queue (#1173) If you create a fresh Profile in Hekili, does that have any impact?The issue most likely relates to how action slots are used between pages. When you load Hekili by itself, your abilities are still moved from page 1 or 2 to 3, 4, 5, 6, etc. The addon uses the binding from the lowest numbered page/slot combination barring a few exceptions related to stances/forms. Can you tell if your abilities are using the lower action bar pages or not?You could also /dump Hekili.KeybindInfo and Pastebin it and link it here. That could offer a few clues.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Hekili** [comment]
Please update via GitHub.com, your email is mangled and largely unreadable in the ticket.

**Comment by Hekili** [comment]
Also, make sure when you do the `/dump Hekili.KeybindInfo` that it's with only my addon loaded.

**Comment by ChrisOfRivia** [comment]
Making new profiles does not seem to fix the problem

![Screenshot_1](https://user-images.githubusercontent.com/87647232/126184622-9cc3eb90-06b6-4222-8136-ce8c3e878696.png)
![Screenshot_2](https://user-images.githubusercontent.com/87647232/126184633-3d464968-f581-4499-aa24-6a4d85760db3.png)
![Screenshot_3](https://user-images.githubusercontent.com/87647232/126184640-1b560244-b78e-4799-a748-f641fadbe19a.png)

Here are the pictures showing that I am using the first 3 Blizzard bars on my character.

The text that comes up from the command is:

Dump: value=Hekili.KeybindInfo
[1]={
}

**Comment by Hekili** [comment]
I don't see keybinds on your action bars in your screenshot.

**Comment by ChrisOfRivia** [comment]
Oh! I never thought of this being a problem since my I keybind my abilities using another addon.
The problem is now fixed, whenever I used the blizzard keybind system. 

I really appreciate the time and effort you put into my problem!

I am really sorry for placing a bug report over a dumb easy to fix issue! Thanks again and have a wonderful rest of your day!

**Comment by Hekili** [comment]
No worries, thanks for supplying information so we could work through it.  What is the other addon you use for bindings?  Maybe I should support it.  You can submit a feature enhancement ticket if you want, with the addon information and (ideally) that addon's savedvariables file.

**Comment by ChrisOfRivia** [comment]
I am not sure what a "savedvariables" file is and where to find it, but the UI I use is called LUI, the addon has an imported keybind feature on it.

**Comment by ChrisOfRivia** [comment]
Apologies for the late response, I thought the conversation wouldn't continue onward
