### ISSUE TITLE
[FEATURE] When using dual or reactive displays, don't duplicate recommendations

### ISSUE THREAD

**Issue by dmora** [Hekili/hekili#1174]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I like to use reactive display since it will let me make a final choice depending on my current view of the game, not only the suggestion system. But it gets confusing when the AOE & Primary view recommends the same talents.

The feature will let chose whether or not you want duplicate actions in both displays, this is mainly for the first item only, since queue items are ok to be duplicates (since they follow a sequence.

**Comment by Hekili** [comment]
Explain more.  How is it confusing when both show the same suggestion?  That sounds less confusing to me.

**Comment by dmora** [comment]
i think it is a really specific use case:

- if im using reactive display, i would like to have the option to have the first item for each queue (Primary, Aoe) to be unique so if i put both bars together, one having the queue going left and the other one going right, they dont show a duplicate suggestion.

It works as intended, not a bug, it is actually a nice to have feature.

**Comment by Hekili** [comment]
Yeah, I still don't understand.  What's supposed to show when Primary and AOE have the same recommendation?  What's supposed to show when they're different?  You have to explain.

**Comment by Hekili** [comment]
Closing for lack of information.
