### ISSUE TITLE
[REC] Elemental/Shaman/Necrolord Primoridal Wave current action shows as Flame Shock

### ISSUE THREAD

**Issue by claybarrett** [Hekili/hekili#1176]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Necrolord, Primordial Wave applies Flame Shock. Targets without Flame Shock ticking are having Flame Shock displayed as the current action while casting Primordial Wave, until the dot is applied. I realize this is minor, probably only a display issue, but as someone using Hekili while learning a class I find it incredibly disorienting.

### How to Reproduce

1. Enter the game as an Elemental Shaman 
2. Join the Necrolord covenant
3. Target a enemy
4. Cast Elemental Overload (because it's the first rec action) 
5. Cast Primordial Wave (because it's the second rec action) 
6. See that it now shows you are casting Flame Shock

### Snapshot (Link)

https://pastebin.com/VuD5fShw

### Contact Information

Glorfindel#2165

**Comment by Hekili** [comment]
Your snapshot wasn't taken while casting Primordial Wave, as far as I can see.  I'm *guessing* that you're saying that Flame Shock gets recommended between your cast of Primordial Wave and when it impacts and actually applies Flame Shock.  Is that accurate?

Can you post another snapshot during your Primordial Wave cast?  Thanks.

**Comment by claybarrett** [comment]
Primordial Wave is an instant, so it's going to be difficult to snapshot *during*. I guess maybe the Flame Shock is slipping into the recs after PW is cast but before FS is applied. It does appear to happen more often with a ranged target, so this is probably due to travel time?.

**Comment by Hekili** [comment]
That makes sense.

Flame Shock is applied on impact, which makes sense.

Can you confirm whether you get the PW buff on cast (instant) or when it impacts?

**Comment by claybarrett** [comment]
It is applied to the caster when PW impacts the target.

**Comment by Hekili** [comment]
This should be resolved in the current release.
