### ISSUE TITLE
[REC] Elemental/Shaman Stormkeeper not rec

### ISSUE THREAD

**Issue by claybarrett** [Hekili/hekili#1177]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As an Elemental Shaman, the Stormkeeper talent is the best choice in all PVE situations; we always take it. Most guides suggest this be used pre-pull. Hekili does not. Ok, maybe that's a design choice like not pre-casting elementals. But, I have never seen that icon queued for me, during any raid fight, over the past month of using Hekili. 

### How to Reproduce

1. Play as Elemental Shaman
2. Take Stormkeeper
3. Attack something

### Snapshot (Link)

https://pastebin.com/VuD5fShw

### Additional Information

I'm not sure what conditions to expect Hekili to recommend casting Stormkeeper, so this is the same snapshot as my other issue. It's early pull, like 2 actions in.

### Contact Information

Glorfindel#2165

**Comment by Hekili** [comment]
Stormkeeper is counted as one of your "Cooldown" abilities, and is controlled by that toggle.  It's disabled by default, because there are many situations where you want to hold onto your Cooldown abilities instead of burning them on trash before a boss pull (for example).

`toggles: cooldowns = false`

See /hekili > Toggles.  ALT-SHIFT-R toggles CDs on and off by default.

**Comment by claybarrett** [comment]
Ok I'll try it with CDs on. Can I ask if "cooldowns" are hard coded or if there's a variable for setting the length? Like if I wanted anything =>2m considered a cooldown is there a place I could customize this?

**Comment by Hekili** [comment]
You can see and edit what is attached to which toggle in the addon options. See your spec options or the Abilities section.
