### ISSUE TITLE
[REC] Balance Druid Venthyr Covenant - Hekili is not recomending Ravenous Frenzy/CA/Inc

### ISSUE THREAD

**Issue by AleSSouza** [Hekili/hekili#1180]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I noticed that after the last update Hekili is not recommending Ravenous Frenzy/CA/Incarn and the opener is wrong.

Edit: I don't have the legendary crafted but I think that should not interfere with opener recommendation.

The opener:

![snap_druid](https://user-images.githubusercontent.com/87926384/126909365-36d3a868-d122-403c-b0a3-a56fbfce2471.png)
[** Hekili is recommending a Starfire before DoT's? **](https://pastebin.com/vhWAxSwW) 

- To emulate Balance Venthyr opener I pressed 2x Wrath > DoT's.

[** - Incarnation: Chosen of Elune + Stellar Flare **](https://pastebin.com/GptQuLZj)
![snap_druid](https://user-images.githubusercontent.com/87926384/126909390-e2fa0c89-6a51-46a2-a4f6-eb013e9a06ab.png)

[** - Soul of the Forest + Stellar Flare **](https://pastebin.com/FkKThH1y)

[** - Soul of the Forest + Stellar Drift **](https://pastebin.com/7sd046eq)

Let me know if snapshots are wrong or something that I could do to help.

Thank you.

### How to Reproduce

1. Enter the game as Venthyr Balance Druid
2. Go to dummy and select it.
3. You should see the opener recommendation
4. For CD's(CA/INC/Rav. Frenzy) cast 2x Wrath > Moonfire > Sunfire > Stellar Flare (if talented).

### Snapshot (Link)

https://pastebin.com/vhWAxSwW

**Comment by Hekili** [comment]
I'm not sure how "separate issues belong in separate tickets" got us to having two issues in this ticket, but I'll just address the opener piece first:

Wrath -> Wrath -> Starfire matches the sim opener unless you've simmed yourself and seen otherwise.  Those recommendations do change once you enter combat, which is something that will be addressed soon.  For anything else related to openers, go ahead and keep that in the ticket related to openers.  Feel free to link your sim there, if it shows different behavior.

For Venthyr/CDs:  Do you have snapshots related to Venthyr and CDs?  Take a snapshot when you think it should be recommending your CDs, but it isn't.

I'll be editing the title of this ticket to make it clear this is specifically for the CDs issue.

**Comment by AleSSouza** [comment]
[https://pastebin.com/GptQuLZj](https://pastebin.com/GptQuLZj)
This snapshot and print is the exact moment when I expect Hekili should recommend CA/INC + Ravenous Frenzy(Covenant ability).

Another one: [https://pastebin.com/5uLu5HFd](https://pastebin.com/5uLu5HFd)
I pressed 2x Wrath, Moonfire, Sunfire and I think this should be the moment to Hekili recommend CA/INC + Ravenous Frenzy.

I tried to follow recommendations as it shows but CD's recommendations never came.

**Comment by Hekili** [comment]
And your sim link?

**Comment by AleSSouza** [comment]
> And your sim link?

Here it goes: [https://www.raidbots.com/simbot/report/qgE6dCtiVbGoaEMMfrtBvd](https://www.raidbots.com/simbot/report/qgE6dCtiVbGoaEMMfrtBvd)

Sorry.

**Comment by Hekili** [comment]
Great, thanks.  If you scroll down, you can see that the opener starts with Wrath, Wrath, Starfire.  What's the rationale in terms of why you shouldn't Starfire there?

I'm looking at the cooldowns piece.  There's a lot of complicated logic for trinkets and CDs so there'll probably be a glitch to fix in general.  But the opener is (or will be) consistent with sim at next release.

**Comment by AleSSouza** [comment]
> Great, thanks. If you scroll down, you can see that the opener starts with Wrath, Wrath, Starfire. What's the rationale in terms of why you shouldn't Starfire there?
> 
> I'm looking at the cooldowns piece. There's a lot of complicated logic for trinkets and CDs so there'll probably be a glitch to fix in general. But the opener is (or will be) consistent with sim at next release.

Yes, you're right. The sim recommend a Starfire before dotting. Thank you.

For the CD part If there's something I can do to help you figure it out, let me know.
Thanks.

**Comment by Hekili** [comment]
Snapshots help.  If you go through the list of actions in the sim in the order the sim does them and then snapshot where it should be recommending CDs but isn't, that'll help.  I *think* that's what you've done already, though.

**Comment by AleSSouza** [comment]
> Snapshots help. If you go through the list of actions in the sim in the order the sim does them and then snapshot where it should be recommending CDs but isn't, that'll help. I _think_ that's what you've done already, though.

My CA/INC and Ravenous Frenzy are macroed in one button, I thought that it would be the problem but tested again following the exact recommendations and got the same result, no CD recomendations. =/

**Comment by Hekili** [comment]
Yeah, macros will have nothing to do with it.

**Comment by Hekili** [comment]
What if you remove your trinkets?

**Comment by AleSSouza** [comment]
So, you're right. The problem is trinket, specifically IQD.

- With no trinkets - OK
- With Tome of Monstruous Construction - OK
- With IQD - No CD recommendations

What further investigations can I do?

**Comment by Hekili** [comment]
Do you have your IQD specifically disabled in the Gear and Trinkets section?

**Comment by AleSSouza** [comment]
Yes, it is disabled. Any other way Hekili doesn't show it?

**Comment by Hekili** [comment]
No, but the APL, as written, factors its usage into CD usage, so it makes sense that this is blocking for you.  This is always a risk with toggling/disabling.  Essentially, disabling an ability treats it like it is fully on CD all the time.  So anything trying to sync with that ability is told to wait.

It'd be hard to resolve internal to the addon without risking other priorities also being impacted.  Maybe.  I'll see if I can try something.

**Comment by AleSSouza** [comment]
Enabled it and the problem was solved. 
Thank you very much for your patience and time.

**Comment by Hekili** [comment]
The release that's being put together right now (1.0.15) *might* let you leave IQD disabled if you so desire.  Give it a try and let me know.

**Comment by AleSSouza** [comment]
Perfect. Even with trinket disabled it is recommended. Ty.
