### ISSUE TITLE
Request: Addon activation on rare elites beside bosses

### ISSUE THREAD

**Issue by LucianDK** [Hekili/hekili#1182]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Currently you have an option to have spells/items only go active on dungeon/raid bosses. Which is useful for things you dont want to blow on mundane mobs such as trinkets.

But I find myself greatly missing that it also would work on rare elites, given that I spend so much time in Korthia killing them.  Mainly for trinkets that be.

**Comment by Hekili** [comment]
Honestly, the game is so bad about distinguishing rare/rare elite/boss enemies consistently that this isn't likely worth any effort.

**Comment by LucianDK** [comment]
ah, I suppose that makes sense. you know best here.

**Comment by Hekili** [comment]
If this were implemented, how would you envision rare-elite vs. bosses?  I.e., if you checked a "Rare-Elite" option but not "Boss" option, what would your expectation be when:
* you're fighting a boss?
* you're fighting a rare-elite?
* you're in combat with a rare-elite but you're targeting something that isn't rare-elite (i.e., adds or other enemies that got pulled in with the rare-elite)?

It seems like this could be confusing and risky.  But maybe it can be made to work.

**Comment by LucianDK** [comment]
Rare elite bosses as in those in Korthia. I believe they are level 62, but dont quote me for it.

**Comment by Hekili** [comment]
I understand.  Any thoughts on these points, or no?
