### ISSUE TITLE
[BUG] Apply ElvUi Cooldown Style bugged for Cooldowns Display

### ISSUE THREAD

**Issue by egorlepa** [Hekili/hekili#1183]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![image](https://user-images.githubusercontent.com/76429849/126966414-92e45314-3a57-41a4-9124-4405a8f0b4e3.png)
Apply ElvUi Cooldown Style option seems to work only for first recommendation for Cooldowns Display.

### How to Reproduce

have elvui installed
import my style - https://pastebin.com/sfLtM4kU

### Player Information (Link)

https://pastebin.com/iaUFJekF

### Error Messages (Link)

no error messages

### Contact Information

discord retzer#8320

**Comment by Hekili** [comment]
My addon doesn't support multiple recommendations in the Cooldowns display.

**Comment by egorlepa** [comment]
@Hekili 
what do u mean by that? it clearly does, it has "Icons Shown" slider and queue options just like any other display... And it works (except for elvui cooldowns)

**Comment by egorlepa** [comment]
![image](https://user-images.githubusercontent.com/76429849/127019347-115b68f1-132c-44d9-bffe-9415b15198c6.png)

**Comment by Hekili** [comment]
It's not supposed to, but I suppose that's an oversight on my part.

With that in mind, you can go to the Queue tab and check Apply ElvUI Cooldown Style.  If that's already set, but not working, let me know.

**Comment by egorlepa** [comment]
oh, i was completely oblivious about queue tab having Apply ElvUI Cooldown Style too. Works great, sorry

**Comment by Hekili** [comment]
It's weird that it's separated like that, but if I didn't separate it, someone would ask me to separate it.  Anyway, glad that's resolved.  Take care.
