### ISSUE TITLE
[REC] IQD Trinket not shown for Balance

### ISSUE THREAD

**Issue by saminilison** [Hekili/hekili#1184]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

cube trinket dosent show for balance dudu  rotation  and feral its show only for gurdian 

### How to Reproduce

i can share screen for you 

### Snapshot (Link)

https://pastebin.com/dtftg1GF

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cxVu8CkF8ZiQE8wfb3nNYs

### Contact Information

saman#7578

**Comment by robertbarral** [comment]
Same Happening to me.

**Comment by saminilison** [comment]
you cant see the cube after you update add one right ?

**Comment by robertbarral** [comment]
Yeah. It doesn't show up

**Comment by Hekili** [comment]
I'll need you to take a snapshot during Ravenous Frenzy (especially toward the end of Ravenous Frenzy).

**Comment by saminilison** [comment]
> I'll need you to take a snapshot during Ravenous Frenzy (especially toward the end of Ravenous Frenzy).

can i just go live in discord and you tell me when i stop and take snap shot?

**Comment by Hekili** [comment]
No, just do it in the last 5 seconds or so of Ravenous Frenzy.

**Comment by mickeygeecom** [comment]
Well, the entire cooldown (opener) rotation as Venthyr balance druid is entirely off. It's way different from Night Fae's. Due to the covenant ability (and the legendary extending it).

@Hekili, you might find some hints here: method.gg/guides/balance-druid/playstyle-and-rotation

I can happily assist on Discord or w/e.

**Comment by mickeygeecom** [comment]
Duplicate of ticket #1180 really.

**Comment by Hekili** [comment]
No, just provide your sims and your snapshots when you think the recommendation should happen, but isn't happening.  Thanks.

**Comment by saminilison** [comment]
https://pastebin.com/qiP7GgdF on sims its say on 10 stak i ger 1 more snap shot too when its 5 second to end

**Comment by saminilison** [comment]
https://pastebin.com/TA8WJ5N7 this is 5 second to end

**Comment by saminilison** [comment]
this is my sim https://www.raidbots.com/simbot/report/cxVu8CkF8ZiQE8wfb3nNYs

**Comment by Hekili** [comment]
If you uncheck "Start after Global Cooldown" in /hekili > Balance > Performance, IQD should be recommended.

I'll adjust the priority not to check the GCD before using IQD.

**Comment by saminilison** [comment]
![image](https://user-images.githubusercontent.com/88009155/127093607-65c873fc-4485-4099-9ca4-bc41a746800a.png)
not showing

**Comment by saminilison** [comment]
i uncheek that and try 2 time its not coming up

**Comment by Hekili** [comment]
Then submit new snapshots.

**Comment by saminilison** [comment]
5 last second again ?>

**Comment by saminilison** [comment]
https://pastebin.com/ezvH8TTr  this is for 5 last second

**Comment by Hekili** [comment]
Alright, I'll make adjustments in the morning to remove the GCD condition. Thanks for the data.

**Comment by saminilison** [comment]
ty hope you  fix this soon ty for this great aadone

**Comment by Hekili** [comment]
Please try https://github.com/Hekili/hekili/releases/tag/v9.1.0-1.0.16-beta1 and let me know if the issue is resolved for you.

**Comment by saminilison** [comment]
fixed ty for great work
