### ISSUE TITLE
 Is it possible to move global cooldowns to another window without breaking the rotation.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1185]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello Hekilli. Please tell me if there is a possibility or a way to remove bursts from rotation in another addon window? But without breaking the rotation in general. This functionality works great in Herorotation for your colleagues. Why am I asking you to take out bursts separately. There are moments in the raid in M ​​+ where using bursts on cooldown is not good, for often it is a special combat mechanic, where we want to hold the bursts and then press them at the right time. These are quickly dying opponents when the opponents already have 10-20% health and we don't want to press bursts, etc. I know that you have the addition of rotation icons and it's cool, but keeping 5 rotation icons on the screen, I think this is not quite what you want to see. I deliberately displayed 5 rotation icons for myself and pressed the rotation, but my rotation showed in the 4 icon because the other 3 were busy with bursts, and this is very inconvenient and not practical. It would be very healthy if individual bursts were shown in a separate window, as I indicated above, as in herorotation, where at the right moment a small window with bursts appears, and shows that now at the moment I can press them, but at my will, and in the main window shows further rotation. This is what I want to see with you, it would be very cool. So I would control the bursts myself, but without getting confused by a bunch of icons with rotation that I need to press. I now use crutches in the form of entering bursts in the defance window, which shows bursts to me, but the rotation then breaks and does not work correctly, since I remove them from the main icon and add them to the defance window. But this method works crookedly badly, but in this way I can control the bursts. I hope you will consider this request.

**Comment by Hekili** [comment]
Sounds like you want to use HeroRotation.  That's fine.

I don't have any intention of implementing this feature.  If you can't achieve it via the existing displays and toggles, it's not part of my addon.

**Comment by geraint425** [comment]
A "great" response to a request to add a feature that will really improve your rotation. Probably you need to play like this with your add-on in order to keep the burst for sure so that everything works. Very comfortably. I think I'm not the only one who faces this problem.
![2](https://user-images.githubusercontent.com/32466458/127148994-d6898711-1db1-4a80-a95e-3611ee4b91a9.jpg)

**Comment by Hekili** [comment]
Okay.

**Comment by Hekili** [comment]
I *am* curious, though.  Am I misinterpreting you?  Are you basically "negging" me because I declined a feature enhancement that you want?

> Probably you need to play like this with your add-on in order to keep the burst for sure so that everything works.

Is this just a translation issue?  Feature requests exist so you can ask for things.  Not demand them.

**Comment by geraint425** [comment]
I did not require this functionality from you, I did not say what to do now, right now, that's all. I just referred to your colleagues who just did it and that's it. I would really like this functionality and see you in the future, I do not demand that now you give up everything and do it. For a given moment, your addon cannot provide the flexibility to hold bursts. Either I don’t know how to do this, please tell me how to set up your rotation to keep bursts.

**Comment by Hekili** [comment]
Help me understand, then.

First, as far as I can tell, what you're calling bursts are just big cooldowns.  Is that right or wrong?

You can toggle cooldown abilities off -- which puts them on hold.  You can add/remove which abilities are linked to each cooldown.  You can have cooldowns displayed separately (not a feature I use, but it's there).  That may be what you want?  I can't really tell from your description.  If you look at /hekili > Toggles, you can see "Show Separately" next to Cooldowns.  If you use that, and Cooldowns are turned on, when they're available they pop up in the separate display, wherever you've placed it, assuming the conditions to use it are met.

By default, you press `SHIFT-ALT-R` and those cooldown abilities are toggled on/off until you turn them off/on again.  That applies whether you have cooldowns Shown Separately or not.

If that doesn't cover what you need, you'll have to specifically explain what is different about what you want.  Bullet points would be best.
