### ISSUE TITLE
[FDK] BoS recommends using Fleshcraft while running

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1187]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When we have BoS active we shouldn't use Fleshcraft. Today level 54 appeared and I took the talent on Fleshcraft Emeni. And adon started recommending Fleshcraft regardless of when and what happens even if BoS is active. Please, please make sure that Fleshcraft is not recommended during BoS work, no matter whether the end is BoS or the beginning or the middle of the work. Fleshcraft should not be recommended while running BoS under any circumstances.

### How to Reproduce

1. Fleshcraft on CD
2. Talent taken from Emeni (Pustule Eruption)
3. We activate BoS.
4. When BoS is running, Fleshcraft should already be ready.
5. And as soon as Fleshcraft is no longer on CD, he recommends it.

### Snapshot (Link)

https://pastebin.com/m1NtJPQD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2XK8B3Sug2zPc1RcUwNhr9

**Comment by Hekili** [comment]
Agreed.  Easy to fix, will take care of it in a day or two.

**Comment by Hekili** [comment]
Here's a sim comparison showing the (small) value in not channeling during BoS, which helps justify changes.  I looked at casting Fleshcraft but interrupting it immediately, and that wasn't valuable for the default profile.

https://www.raidbots.com/simbot/report/7z12ZemKZH16pmLkECudFN

**Comment by geraint425** [comment]
There should be no Fleshcraft during BoS. Forgive me, but there are such moments as an additional chance for Rime's ability and we can extend the BoS. Plus, we also do not always fight according to the ideal scenario. There are moments that BoS is used in advance on the barefoot, and maybe in 5-10 seconds heroism, and from above they can still give power infusion and we can hold BoS for a very long time. I still adhere to the fact that during the work of BoS Fleshcraft should not be. Plus, as I wrote above, when taking a talent, we want to use Fleshcraft for 9 stacks without breaking it. But Fleshcraft should be used either before BoS or after BoS ends during BoS, it shouldn't be.

**Comment by Hekili** [comment]
I know.  You should read the words I said.

**Comment by geraint425** [comment]
I saw that you wrote that it does not play a special role if you just take click and cancel. But this is 1 gcd and it can be 30RP + and we have 1 second before getting 2 runes to use obliterate, thereby prolonging BoS by 1-2 seconds. Do you take into account the moments like I wrote Rime? And plus take into account the fact that BoS is very sensitive to ping in the game, that the simulation presses everything perfectly, and I am not a robot, I will not be able to perfectly press the button. And this also needs to be corrected. I kind of see the problem in spending 1gcd on clicking Fleshcraft and canceling.

**Comment by Hekili** [comment]
No, you misunderstood me.  I told you the comparisons I made so you can have an understanding of backing up your claims with data.  I also told you I agreed in my first response.

Just to clarify, I try to actually get data to support changes, even if they look right at a glance and seem obvious, because I should have evidence that a change is beneficial.  That's all.

**Comment by geraint425** [comment]
I beg your pardon, I misunderstood you.

**Comment by Hekili** [comment]
Try 1.0.17-beta1 when it is available.

**Comment by geraint425** [comment]
Yesterday I was in the raid, everything worked fine. Fleshcraft did not interrupt BoS. Thanks for a great job.

**Comment by Hekili** [comment]
Thanks for reporting back.
