### ISSUE TITLE
Havoc - Trinket Not Always Being Recommended with The Hunt

### ISSUE THREAD

**Issue by alcaras** [Hekili/hekili#1188]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Expecting recommendation to use Salvaged Fusion Amplifier (Trinket) after The Hunt.

Sometimes it doesn't happen. Not sure why :-/

### How to Reproduce

1. Play Havoc
2. Use a 1:30m cd trinket after using the Hunt
3. Hekili will not alwayas recommend the trinket until the 3rd Hunt
(Can't reproduce on this on a training dummy, but see the snapshot below)

### Snapshot (Link)

https://pastebin.com/LHL7TbM6

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ojLuQjrqb88GDpxyn1FQDF

### Additional Information

Additional snapshots:
https://gist.github.com/alcaras/b14806642f7e84359f517e2d746f2af2
https://gist.github.com/alcaras/774bcd3b02cd4de5acf9c91a42f04d3e

### Contact Information

alcaras#6052

**Comment by Hekili** [comment]
I'll be posting a beta build that *might* address this, but maybe not.  The Use Items entries in the cooldowns list should be Trinket #1 and Trinket #2 entries instead.

There may be additional work needed to resolve from there.

**Comment by Hekili** [comment]
Try 1.0.17-beta1 when it is available.

**Comment by alcaras** [comment]
e: Sometimes seems to work, sometimes not. Will try to get a snapshot when I think it should be suggesting it but it isn't.

Example snapshot of it not suggesting:
https://gist.github.com/alcaras/796851278d71b643d32b19416558a39e

**Comment by Hekili** [comment]
This appears related to a very high "fight_remains" value during your fight.  Try changing the `>?` in your Trinket 1 and Trinket 2 entries (cooldown list) to `<?` and see if it makes a difference.

**Comment by alcaras** [comment]
i.e. from
`variable.trinket_sync_slot = 1 & ( buff.metamorphosis.up | ( ! talent.demonic.enabled & cooldown.metamorphosis.remains > ( fight_remains >? trinket.t1.cooldown.duration / 2 ) ) | fight_remains <= 20 ) | ( variable.trinket_sync_slot = 2 & ! trinket.t2.cooldown.ready ) | ! variable.trinket_sync_slot`

to
`variable.trinket_sync_slot = 1 & ( buff.metamorphosis.up | ( ! talent.demonic.enabled & cooldown.metamorphosis.remains > ( fight_remains **<?** trinket.t1.cooldown.duration / 2 ) ) | fight_remains <= 20 ) | ( variable.trinket_sync_slot = 2 & ! trinket.t2.cooldown.ready ) | ! variable.trinket_sync_slot`
?

Will try that out and report back.

**Comment by alcaras** [comment]
Looks like that fixed it, though I've only had a chance to try it out on a few bosses.

**Comment by alcaras** [comment]
From playing with it a few days, looks to be fixed! Thank you.

Will reopen if I see issues during next week's raid reset.
