### ISSUE TITLE
Automatic Snapshot generated on Shadowpriest

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1189]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Im getting an automatic snapshot generated from the addon periodically while questing.

### How to Reproduce

Just doing your rotation while questing, killing random mobs out in the world.

### Player Information (Link)

https://pastebin.com/i4HS4Mif

### Error Messages (Link)

https://pastebin.com/7H39MnQx

**Comment by Hekili** [comment]
So, this looks like the logic for not dotting when a target is about to die is effectively blocking you from nuking (because the priority is written to put dots up and then nuke) is counterproductive.  I'll post a test change in a little bit.

**Comment by Hekili** [comment]
Try 1.0.17-beta1 when it is available.

**Comment by Tzuyume** [comment]
I think that fixed it, at least i havn't encountered it while playing. Will make a new ticket if i see it again.

**Comment by Tzuyume** [comment]
https://pastebin.com/M3JRhpBm

Problem returned again.

**Comment by Hekili** [comment]
It's a different issue with the same outcome.  In any case, this may be fixed in 1.0.18-beta1.

**Comment by Tzuyume** [comment]
https://pastebin.com/71A5Nnu5

Still showing up snapshots.

**Comment by Hekili** [comment]
Hm, addon still thinks it's channeling Mind Flay after it would break by using Empyreal Ordnance.  I'll take a look again.

**Comment by Hekili** [comment]
This should be fixed in the latest betas.
