### ISSUE TITLE
Arc. Mage bug fight world mini boss's

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#119]
My talents are: 331-1, I'm level 118
Each and every time I fight a world mini boss, I get the below message.

Message: Interface\AddOns\Hekili\Classes.lua:1285: attempt to index global 'dm' (a nil value)
Time: Thu Apr 25 21:57:29 2019
Count: 222
Stack: Interface\AddOns\Hekili\Classes.lua:1285: attempt to index global 'dm' (a nil value)

Locals:

**Comment by Hekili** [comment]
Should be fixed in 8.1.5-14-alpha2.
