### ISSUE TITLE
[UI] Incarnation : Chosen of Elune is not able to disabled only when boss encounters

### ISSUE THREAD

**Issue by howdeh** [Hekili/hekili#1190]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For the Balance abilities you would expect to see Incarnation: Chosen of Elune in the list of abilities to disable/only have on boss encounter. Outside of boss i'd like to choose when I use this.

Is this just the ability named wrong? 

### How to Reproduce

1. Enter game as Balance Druid
2. Open Hekili
3. Abilities tab
4. Specialization Balance
5. Note that Incarnation: Chosen of Elune is not in the list

### Snapshot (Link)

N/A

**Comment by Hekili** [comment]
The name there will come from whatever spec you are at login.  Incarnation is just Incarnation regardless.
