### ISSUE TITLE
DEMONOLOGY WARLOCK DOOMGUARD BREAKS ROTATION

### ISSUE THREAD

**Issue by hekilibug** [Hekili/hekili#1191]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Have an issue with it breaking because of one of my favorite spell "Ritual of Doom"
When the Doomguard is summoned, the rotation keeps suggesting to summon Felguard and the spell
"Command Demon"

Is there anyway around this?
I did not supply a pastebin link as I do not think its necessary, but if you would like me to please let me know.
Thanks

### How to Reproduce

1. Enter game as Warlock
2. Summon Doomguard
3. Take him under your control with subjugate
4. Try to fight something, it will keep recommending summon felguard.

### Snapshot (Link)

https://pastebin.com/

**Comment by Hekili** [comment]
You did not include a snapshot.

**Comment by hekilibug** [comment]
I'll include one soon, sorry about that.

**Comment by Hekili** [comment]
Closing for lack of required info.
