### ISSUE TITLE
[BUG] Multiple LUA errors when entering combat

### ISSUE THREAD

**Issue by lucifa42** [Hekili/hekili#1193]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Multiple errors when entering combat with my Tauren Deathknight lvl 50. Do not get these errors with any other characters.
Gets thousands of errors over a short period of time.

### How to Reproduce

Simply enter combat, doesn't seem to matter how you do it.

### Player Information (Link)

https://pastebin.com/vSJuLb2e

### Error Messages (Link)

https://pastebin.com/t4cjGgax

**Comment by Hekili** [comment]
Your ticket says multiple errors.  Is this the first error that appears?

**Comment by lucifa42** [comment]
Apologies, I meant the same error comes up multiple times. Just one error.

**Comment by Hekili** [comment]
I'm not able to replicate this with what you've supplied.  I have a 51 Unholy DK, I applied the same talents (even PvP talents).

Are you using the default, built-in priority?  Did you import a priority?

What else do you see on screen when the errors start?  Is anything recommended at all?

**Comment by lucifa42** [comment]
Did you enable war mode? That's the only thing I can think of.
Using the default priority - I've never used a custom one on any character.
I've made a recording of it happening: https://youtu.be/vc9LnhKMLEU

You'll even see after the second fight that the errors continue even when out of combat for a short time.

**Comment by lucifa42** [comment]
Ok I did some tests. I think it's related to Death's Echo pvp talent and war mode.

I just tested it in in Orgrimmar on the target dummys.

War mode off with Deaths Echo selected: no errors
War mode on with Death's Echo selected: errors in combat
War mode on with no Death's Echo selected: no errors.

**Comment by Hekili** [comment]
Good catch, should be resolved in 1.0.17.
