### ISSUE TITLE
[FEATURE] Lua fetch the wait/delay on recommended ability

### ISSUE THREAD

**Issue by Snoogey** [Hekili/hekili#1196]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

This might be less of a feature request, and more of a question.
When an ability is recommended, there's sometimes a recommendation to delay/wait to use the ability with the use of some sort of timer counting down until you should use it.
Is it possible to fetch this timer through a custom function in a WeakAura?
For instance, using `return Hekili_GetRecommendedAbility("Primary",1)` I can fetch the ID of the recommended ability in slot 1.
Using spell.item I can fetch the ID of the recommended item (such as a trinket etc).
Is there way for me to fetch this timer?
I've been able to build some pretty insane WeakAuras using this so far, so thanks a lot for your great work on Hekili, it's amazing.

**Comment by Hekili** [comment]
I can expose this without a lot of effort.  If you have ViragDevTool or anything similar, you can take a look at the `HekiliDisplayPrimary.Recommendations[1]` to see what else is available.  I'd probably just make it so `GetRecommendedAbility` returns the time of the cast if it is in the future, 0 otherwise, for its second argument.  Is there any other data about the recommendation that should be exposed?  Target cycling, etc.?

**Comment by Snoogey** [comment]
Thats great to hear!
Let me take a look at what other variables could be useful and Ill get back to you tomorrow- thanks a lot!

**Comment by Snoogey** [comment]
You actually don't need to "expose" this - it's already all available actually! I prodded around with ViragDevTool (thanks for the tip!) and I can access all the variables in the table HekiliDisplayPrimary.Recommendations[1], and HekiliDisplayPrimary.Recommendations[1].wait was the one I was looking for!
Thanks a lot Hekili, you're awesome.
Now I'm going to see what other cool stuff is in this table. :)
You may close this issue if you want, as I'm satisfied with the result.

**Comment by Hekili** [comment]
I won't guarantee that those tables will be exposed forever, but I have no plans to make changes (hide or restrict that data) right now.  Just keep in mind if something breaks later on, it might be that I've opted to protect more of that information.  Let me know if there are other specific details you want to have accessible via the API.
