### ISSUE TITLE
[FEATURE] Potion as Cooldown

### ISSUE THREAD

**Issue by leakyfaucetNA** [Hekili/hekili#1198]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Was looking for a way to put the Potions into the CD section. I tried doing it manually but the option "[Potion]" did not yield any results.

**Comment by Hekili** [comment]
You should submit this as a priority issue.  If you reassigned the "Potion" ability to Cooldowns and then it wasn't recommended despite Cooldowns being disabled, I'd need to see a snapshot where that is happening.

As an aside, I don't really recommend using the Potions toggle anyway.  For any relevant content, using your combat potion is probably part of the raid strategy and not really *just* a priority issue.

**Comment by leakyfaucetNA** [comment]
Hey, I was moving it to the cooldowns section so it would show there anyways, but when I select potion it it didnt really add anything to that category. I tried putting it in the Custom 1 section same thing. Not sure if that wasnt supported or a bug.

**Comment by Hekili** [comment]
So make whatever change you were intending, get in combat (at a point where you think it should recommend a potion), take a snapshot, put it on Pastebin, and link it here.  Otherwise, I have nothing to review.
