### ISSUE TITLE
Arc Mage problems....

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#120]
Arc Mage fight a mini boss (named quest boss)
Talents 3312133

Message: Interface\AddOns\Hekili\Classes.lua:1285: attempt to index global 'dm' (a nil value)
Time: Fri Apr 26 19:18:51 2019
Count: 1
Stack: Interface\AddOns\Hekili\Classes.lua:1285: attempt to index global 'dm' (a nil value)
Interface\AddOns\Hekili\State.lua:3342: in function <Interface\AddOns\Hekili\State.lua:3300>
Interface\AddOns\Hekili\State.lua:5095: in function `IsUsable'
Interface\AddOns\Hekili\Core.lua:630: in function `GetPredictionFromAPL'
Interface\AddOns\Hekili\Core.lua:996: in function `GetNextPrediction'
Interface\AddOns\Hekili\Core.lua:1163: in function `ProcessHooks'
Interface\AddOns\Hekili\UI.lua:820: in function <Interface\AddOns\Hekili\UI.lua:685>

Locals: t = <table> {
 lastApplied = 0
 v1 = 0
 v2 = 0
 caster = "nobody"
 duration = 15
 timeMod = 1
 expires = 0
 name = "no_name"
 key = "stealable_magic"
 count = 0
 applied = 0
 v3 = 0
 unit = "target"
 lastCount = 0
}
k = "up"
class_aura = <table> {
 funcs = <table> {
 }
 key = "stealable_magic"
 max_stack = 1
 id = -1
 generate = <function> defined @Interface\AddOns\Hekili\Classes.lua:1272
 duration = 30
}
(*temporary) = nil
(*temporary) = <table> {
 funcs = <table> {
 }
 key = "stealable_magic"
 max_stack = 1
 id = -1
 generate = <function> defined @Interface\AddOns\Hekili\Classes.lua:1272
 duration = 30
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
class = <table> {
 totems = <table> {
 }
 talents = <table> {
 }
 abilityList = <table> {
 }
 stateExprs = <table> {
 }
 auras = <table> {
 }
 pets = <table> {
 }
 itemPack = <table> {
 }
 interrupts = <table> {
 }
 gear = <table> {
 }
 trinkets = <table> {
 }
 packs = <table> {
 }
 itemList = <table> {
 }
 abilities = <table> {
 }
 itemSettings = <table> {
 }
 stateTables = <table> {
 }
 stances = <table> {
 }
 primaryResource = "arcane_charges"
 range = 8
 hooks = <table> {
 }
 settings = <table> {
 }
 toggles = <table> {
 }
 resources = <table> {
 }
 potions = <table> {
 }
 num = 4
 stateFuncs = <table> {
 }
 pvptalents = <table> {
 }
 potionList = <table> {
 }
 powers = <table> {
 }
 potion = "battle_potion_of_intellect"
 itemMap = <table> {
 }
 file = "MAGE"
 specs = <table> {
 }
}
requiresLookup = <table> {
 lastApplied = true
 v1 = true
 v2 = true
 caster = true
 id = true
 timeMod = true
 expires = true
 name = true
 unit = true
 v3 = true
 applied = true
 count = true
 lastCount = true
}
default_debuff_values = <table> {
 lastApplied = 0
 v1 = 0
 v2 = 0
 caster = "nobody"
 duration = 15
 timeMod = 1
 expires = 0
 name = "no_name"
 unit = "target"
 v3 = 0
 applied = 0
 count = 0
 lastCount = 0
}
auras = <table> {
 target = <table> {
 }
 player = <table> {
 }
}
state = <table> {
 spend = <function> defined @Interface\AddOns\Hekili\State.lua:1176
 tostring = <function> defined =[C]:-1
 putTrinketsOnCD = <function> defined @Interface\AddOns\Hekili\State.lua:3952
 role = <table> {
 }
 IsKnown = <function> defined @Interface\AddOns\Hekili\State.lua:4929
 forecastResources = <function> defined @Interface\AddOns\Hekili\State.lua:1014
 purge = <table> {
 }
 cast_start = 0
 GetTime = <function> defined =[C]:-1
 incanters_flow = <table> {
 }
 pairs = <function> defined =[C]:-1
 UnitCastingInfo = <function> defined =[C]:-1
 stop_burn_phase = <function> defined @Interface\AddOns\Hekili\Classes\MageArcane.lua:375
 tonumber = <function> defined =[C]:-1
 predictionsOff = <table> {
 }
 player = <table> {
 }
 prev = <table> {
 }
 display = "Primary"
 removeStack = <function> defined @Interface\AddOns\Hekili\State.lua:743
 prev_off_gcd = <table> {
 }
 active_dot = <table> {
 }
 applyDebuff = <function> defined @Interface\AddOns\Hekili\State.lua:760
 mainhand_speed = 1.806000
 IsUsableSpell = <function> defined =[C]:-1
 debuff = <table> {
 }
 PlayerBuffUp = <function> defined @Interface\AddOns\Hekili\State.lua:3931
 channelSpell = <function> defined @Interface\AddOns\Hekili\State.lua:904
 equipped = <table> {
 }
 gain = <function> defined @Interface\Ad

**Comment by Hekili** [comment]
Should be resolved in 8.1.5-14-alpha2.
