### ISSUE TITLE
[FEATURE] Separate Ability Range Checks

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#1200]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

After reading quite a few different suggestions regarding the "Exclude Out-of-Range" feature, I thought this might be a decent idea that could potentially help people customize their priorities more without having to make tickets for each ability they would like range checks on.

Currently you can choose between "Per Ability", "Melee Range", and "Exclude Out-of-Range" in the Range options in settings. I was wondering if it would be possible to apply these settings on a per ability basis so that even if an ability doesn't have a range attached to it, you can still prevent it from being suggested in certain circumstances?

As in, if you never wanted a specific ability suggested if you weren't in melee range, you would set that ability alone to not be suggested. That could allow the rotation to continue (your ranged attacks, etc) during times when you may not have the ability to be close to the target.

If you could customize on a per ability basis in this way, you could probably circumvent the need for range checks on a bunch of different abilities. I know a lot of people (including myself) use the Exclude Out-of-Range feature primarily, and I've read how you don't like dealing with it. Perhaps this could alleviate some of those tickets.

Thank you for all your hard work and I really appreciate all the options you implement to let us try and customize as much as we want to.

**Comment by Hekili** [comment]
That's an approach that might work as a per-ability setting that people would configure.

I'd need to make sure it snapshots well so that when an ability is ruled out based on this range check, it's clear that this occurred because of a user preference.

**Comment by Hekili** [comment]
This has long-since been implemented (for abilities that have proper range check settings via the API).
