### ISSUE TITLE
Hekili macro/command to change priority 

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#1201]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

"/hek set priority X" type of command to be able to macro for when wanting to change the priority without having to go through the UI to change.

### Contact Information

Smudgie#2425

**Comment by Hekili** [comment]
`/hekili priority` should work in 1.0.18.
