### ISSUE TITLE
Just need some help as new user.

### ISSUE THREAD

**Issue by Crystalmari** [Hekili/hekili#1202]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

THis is not a feature request but an information request.   You don't have a choice for that one.  The streamer guys said this was a very easy to use DPS helper.  I have been using but have a major problem that doesn't not fit into an end game issue.   The spell suggestions are in the middle of the screen and I cannot move them.   This was one of the features they mentioned was available and even show doing it on their streaming.   Their instruction were:  right click on mini map to get menu (no problem so far), left click to move.   The problem is the menu is over the spell suggestions.   You can't move the menu to get it out of the way to get to the spell suggestions and of course with the menu over the spell suggestions, you can't move them. WOW is always putting things in the exact same place as the spell suggestions so they have dialog on top of the suggestions during a fight or they put you in a mechanical thing and the tool thing is right on top of the spell bar.   So they can't be seen.  Moving them would solve the problem but can't figure out how to do this.   Looked at everything in the menu to try to find a move, or lock display or something and can find nothing.   Do you have a tutorial to tell those of us that aren't computer genius what all these things do?   It certainly is not as easy as they tried to make it out to be but then they are streamers.   Please help as I like the suggestions that are given and it has improved my DPS when I can see all the symbols.   Also added Spellflash but it is not showing up on my buttons.   But another problem for another day.   Thanks.

**Comment by Snoogey** [comment]
Just drag the menu window, lmao.
Drag it from the top.

**Comment by Hekili** [comment]
Move the menu out of the way (click where the name of the addon is) and click and drag where you want.

Or go to /hekili > Displays > (select each display) and set their X/Y coordinates.
