### ISSUE TITLE
SpellFlash on ActionBarButton1 only?

### ISSUE THREAD

**Issue by rakkarage** [Hekili/hekili#1204]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hi. Recently got hekeli setup. But when using SpellFlash only the first button (1) ever flashes. For example if I have Shield Slam on button 1 and Devastate on button 2; only shield slam ever flashes when it comes up in rotation and devastate never does. But if I swap them then Devastate flashes when it comes up in rotation and shield slam never does? Does anyone recognize this problem and/or have a solution please?
i have removed all other addons and even settings tried on multiple characters for multiple days... idk. Please and thanks.
https://www.youtube.com/watch?v=M20iF5OopaU

### How to Reproduce

1. Install Hekili and SpellFlash
2. Enable spell flash
3. only the spell in ActionBarButton1 is flashed others are not
4. move another spell into ActionBarButton1
5. goto 3

### Player Information (Link)

https://pastebin.com/MvMqp1tt

### Error Messages (Link)

no errors (required?)

**Comment by Hekili** [comment]
It's an issue with the (old) version of SpellFlashCore found on Curse.

If you download this version instead, you should be fine:  https://github.com/Tga123/SpellFlashCore
