### ISSUE TITLE
[REC] Balance - IQD Reccomended before ravenous while ravenous is off CD

### ISSUE THREAD

**Issue by yenbounger** [Hekili/hekili#1206]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On the second usage of Ravenous Frenzy, I am seeing recommendations to use IQD before Ravenous Frenzy

### How to Reproduce

1. Enter the game as a Balance Druid, with IQD (possibly caused by double on use)
2. Follow the rotation on a target dummy until the second use of ravenous frenzy has come back up
3. Observe an early recommendation for IQD

### Snapshot (Link)

https://pastebin.com/JHYFGQVz

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/CbdNaciMuPsVe5hoLsJYY

### Additional Information

Was recommended as the second act in a snapshot - have seen it as the first recommendation previously (will try and snapshot next time I see it)

**Comment by noiseuu** [comment]
Hello!

This problem is still at newest update.

**Comment by Hekili** [comment]
I haven't posted a new update release, but you should submit an updated snapshot if you've done new testing.

**Comment by noiseuu** [comment]
i guess u want combat snapshot?

**Comment by Hekili** [comment]
The same rule as always with snapshots.  Take the snapshot at the time where you're seeing the problem.  Explain it when you post it.

**Comment by noiseuu** [comment]
Okay, im gonna try that balance prio push. And see if something wrong still there

**Comment by noiseuu** [comment]
https://pastebin.com/AtY3pNak
Okay, in that pastebin i have been 3 min to dummy, and when second rf+incarn+trinket comes, it suggest only iqd.
https://gyazo.com/eb0bcfa8a40c88939b33171ff28313e1
I paused it for u, if u want see what line

**Comment by Hekili** [comment]
> Explain it when you post it.

What do you think you should be seeing instead?

**Comment by Hekili** [comment]
Oh, never mind.  I see it.  I need to make Trinket 1 and Trinket 2 actions not morph into trinkets that are explicitly in the priority already.  Will fix.

**Comment by Hekili** [comment]
Okay, if you want to test the latest commit (after the last beta release), it may be more of what you expect.

**Comment by noiseuu** [comment]
Yes, fixed now ty

**Comment by noiseuu** [comment]
Hey,
One thing, after that update second use trinket doesnt want show. In this time it is bell

**Comment by Hekili** [comment]
You know what to do...

**Comment by noiseuu** [comment]
https://pastebin.com/jvPkj88z
So this pastebin everything goes well in opener, but missing second trinket usage.

**Comment by Hekili** [comment]
-beta4 may address this.

**Comment by yenbounger** [comment]
Issue has been resolved for me on -beta4
