### ISSUE TITLE
[REC] Marksmanship and legendary bow

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1207]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I ran into a rotation issue with the openner and further use of the Wailing Arrow ability. The problem is that in Simc we have to use Wailing Arrow before Resonating Arrow, but we are losing dps because we are casting Wailing Arrow and we are wasting time. I tested on another oppener and then used it in rotation in this sequence. I would like to start the rotation like this (prepull Double Tap-> 3sec Steady Focus) Steady Focus-> Resonating Arrow-> Trueshot-> Wailing Arrow and then the standard rotation continues. And then when the abilities are again ready, we use Double Tap-> Resonating Arrow-> Trueshot-> Wailing Arrow. I tried to do this in the game and my dps was higher. I'm not good at how to do it in Simc, so I can't show it in the program. But I described how I used it myself in the game and got a better result than the sim rotation now offers

### How to Reproduce

1.prepull Double Tap 
2.prepull3sec Steady Focus 
3. Steady Focus
4. Resonating Arrow 
5. Trueshot
6. Wailing Arrow

### Snapshot (Link)

https://pastebin.com/xNVZGYUU

**Comment by Hekili** [comment]
If you cannot test on the sim yourself, but you are confident this is a DPS increase, you might reach out to the Hunter theorycrafters for SimC and see if they can implement those suggestions.  I'm not able to investigate this on your behalf.

**Comment by geraint425** [comment]
I got an answer to my question, which I asked you and the Simc APL Hunter developer himself. Here is a screenshot of his answer, and a link to raidbots. https://www.raidbots.com/simbot/report/9yeLBn9FUTNfyAianoJZUh
![1](https://user-images.githubusercontent.com/32466458/129382239-a20d2d35-c82c-44da-a25e-671bbcab756e.jpg)

**Comment by geraint425** [comment]
I think the ticket can be closed.

**Comment by Hekili** [comment]
Thanks for following up.
