### ISSUE TITLE
[Bugfix] Havoc Demon Hunter Darkglare Boon legendary not recognized

### ISSUE THREAD

**Issue by Kaaosa** [Hekili/hekili#1209]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Havoc Demon Hunter, the `use_eye_beam_fury_condition` variable checks to see if the player is using Demon Blades talent or the Darkglare Boon legendary alongside the Blind Fury talent. However the check for Darkglare Boon is incorrect. It checks for `runeforge.darkglare_medallion.enabled` which returns false if the character is wearing the belt version of the legendary (I have not tested for other slots of the legendary effect). Changing the check to `runeforge.darkglare_boon.enabled` results in the check operating properly. This also fixes the issue of Hekili recommending Eyebeam when it would generate excess Fury.

### How to Reproduce

1. Equip a Darkglare Boon Legendary on a Havoc Demon Hunter
2. Select Blind Fury talent
3. In the precombat Action List, select the `use_eye_beam_fury_condition` variable
4. Hover over the value field to see that it returns false for `runeforge.darkglare_medallion.enabled`

### Snapshot (Link)

https://pastebin.com/MQfbTDCp

### Contact Information

Kaaosa#2930

**Comment by Hekili** [comment]
Thanks, this will be resolved in today's release.
