### ISSUE TITLE
Ret Pally Consecration is on Bar 10 Keybind Z but Hekili will occasionally show it as Q on bar 1

### ISSUE THREAD

**Issue by Quttzik** [Hekili/hekili#1210]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Occasionally showing wrong keybind for Consecration which is currently on bar 10 keybind Z
It will occasionally show Consecration with a keybind of Q which is on bar 1. 
I have included the snips of Bar 1 and Bar 10 Elvui settings.  And
![Bar 1 settings](https://user-images.githubusercontent.com/88072566/129396694-2a062523-115d-4108-8218-234e78ff2b06.PNG)
![Bar 10 settings](https://user-images.githubusercontent.com/88072566/129396715-dd5fd480-b711-48a3-a3fc-ccae90da04a8.PNG)

### How to Reproduce

Not sure. 

### Snapshot (Link)

https://pastebin.com/YrcSxpFV

**Comment by Hekili** [comment]
This appears to be resolved in 1.0.18.
