### ISSUE TITLE
[MM] When using Double Tap before the start of the battle, bursts disappear

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1211]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I noticed one interesting thing. If you use Double Tap before the start of the battle, then abilities (Resonating Arrow, Trueshot) disappear in the rotation. But if Double Tap becomes available for use again during the fight, Resonating Arrow, Trueshot will be shown. I would like that if I used Double Tap before the start of the battle, then the bursts would not disappear in the rotation.

### How to Reproduce

We use Double Tap before the start of the fight.

### Snapshot (Link)

https://pastebin.com/rVUj3j0q

**Comment by Hekili** [comment]
Please provide a sim of your character, I'll take a look.  There's probably some CD syncing logic that should be adjusted for situations where your CDs are not aligned.

**Comment by geraint425** [comment]
https://www.raidbots.com/simbot/report/qD4jUS1q6uCqKLLbiwZMuh

**Comment by Hekili** [comment]
I've put some changes in 1.0.19-beta2 that might address this.  If you test and find issues, be sure to submit new snapshots.
