### ISSUE TITLE
 [BUG] Events.lua attempt to perform arithmetic on local 'slot' (a nil value)

### ISSUE THREAD

**Issue by Quttzik** [Hekili/hekili#1212]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

4899x Hekili\Events.lua:2064: attempt to perform arithmetic on local 'slot' (a nil value)
[string "@Hekili\Events.lua"]:2064: in function <Hekili\Events.lua:2060>
[string "@Hekili\Events.lua"]:2180: in function <Hekili\Events.lua:2180>

Full Bug Sack message below in pastebin.

### How to Reproduce

Not sure as error occurs on log in.  I am assuming tho this is in part due to the correction to the keybind issue I was having on the pally and the updated Events.Lua you sent.  Just wanted to drop a note here to let you know what was happening.

### Player Information (Link)

https://pastebin.com/59F6uYng

### Error Messages (Link)

https://pastebin.com/8qUSBmSH

### Contact Information

Rammarcyna#9189

**Comment by Hekili** [comment]
This is resolved in 1.0.18.
