### ISSUE TITLE
[BUG] Fury Warrior, AOE, showing Raging Blow icon when Whirlwind or Rampage is recommended

### ISSUE THREAD

**Issue by wartali** [Hekili/hekili#1214]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

i observed this only in AOE rotation, in the recommendation box, it appears raging blow but the key bind is for whirlwind or rampage . The picture is not correct but the key bind is. I notice this because even though i do not have whirlwind stacks it will not tell me(in aoe) to cast it again but to cast raging blow. This also happens sometimes with him recommending me in picture raging blow even if i have rage for rampage, but the key bind on the top right of the picture is for rampage and is correct but the picture is for raging blow.

### How to Reproduce

1. enter game as fury warrior
2. DO NOT pick talent meat cleaver
3. go to a practice dummy for aoe and you will after a few hits that the picture says to use raging blow insted of whirlwind even though your whirlwind stacks are gone. 
in the picture you will see, it recommends raging blow even though i have aoe mobs near, i have no whirlwind stacks and they keybind for raging blow is 2 no F , F is for whirlwind which is correct.
![hekili](https://user-images.githubusercontent.com/88987716/129492458-e8012ecc-027a-4eab-a71f-b54c3557fa75.png)

### Snapshot (Link)

https://pastebin.com/UZ3851yC

### Contact Information

tali86#7115

**Comment by Hekili** [comment]
Was the snapshot taken at the same time as the screenshot?

**Comment by wartali** [comment]
> Was the snapshot taken at the same time as the screenshot?

nope, different times

**Comment by wartali** [comment]
Hello, if it helps, i also tested solo dps on dummy and same issue happens, it shows the picture of the raging blow but the keybind or rampage , the correct choice should be rampage

My raging blow keybind is 2 and my rampage is 3

https://pastebin.com/nQhMW6YR
![hekilisolodps](https://user-images.githubusercontent.com/88987716/129525235-983b0809-47a6-445e-9ad3-59f66b076d32.png)

**Comment by wartali** [comment]
really like your guys WA, i think it is one of the best in wow that is why i am showing you this. It almost Keep up the great work

**Comment by Hekili** [comment]
In your second screenshot and snapshot combination, are these simultaneous?

**Comment by Hekili** [comment]
I'm going to try removing texture caching from those abilities and see if it makes a difference in 1.0.18.

**Comment by wartali** [comment]
> In your second screenshot and snapshot combination, are these simultaneous?

yes. And i have seen there are issues with even more spells. Wrong picture showing but correct keybind.

**Comment by wartali** [comment]
I downloaded the new version and i can confirm it is all working now!!! for AOE and for single target.

Thank you very much!

**Comment by Hekili** [comment]
Thanks for reporting!
