### ISSUE TITLE
[FEATURE] Give a toggle to supress targetswap recommendations during Single-Target Mode

### ISSUE THREAD

**Issue by SkullCandyTV** [Hekili/hekili#1215]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

As mentioned in the Discord already, there is a problem for especially Necro-Feral druids.
The problem is that during ST-fights and even while having ST-Mode activated the recommendation will flicker recommend to target-swap which can be very distracting or sometimes actually a significant DPS loss as you FF and the adaptive swarm will often be used together and FF relies on the dmg amp of the swarm to be worth it.

It would be cool to have a toggle to disable the targetswap-recommendation during ST-mode.
The same problem also happens with the adaptive swarm.

Would love to have these toggles in place. 

### Contact Information

SkullCandy#1156

**Comment by Hekili** [comment]
I'm going to suppress (most, if not all of) these when there are not additional targets to hit.  One exception is Reverse Harm, which you would cast on another friendly target.  This will be in 1.0.18.
