### ISSUE TITLE
[BUG] Necrolord Fire Mage - Covenant Legendary - Error Messages

### ISSUE THREAD

**Issue by taintedbunny** [Hekili/hekili#1216]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The error message only pops up for Fire spec (Arcane and Frost are fine).
I suspect it's the interaction between Deathborne, Death's Fathom and Combustion, but I don't know how to fix it myself.

### How to Reproduce

1. Be Necrolord Mage in Fire Spec
2. Have Death's Fathom Equipped
3. Use Deathborne and Combustion

### Player Information (Link)

https://pastebin.com/qY03BJPi

### Error Messages (Link)

https://pastebin.com/pWPF4sS3

### Additional Information

Keep up the great work; Can't live without your addon :p

### Contact Information

Discord ID: Bacchanal#0323

**Comment by Hekili** [comment]
This is interesting.  Can you sim yourself on raidbots and provide a link?  Thanks in advance.

**Comment by taintedbunny** [comment]
https://www.raidbots.com/simbot/report/qaMVYzJqcjnMgtx1vRJbDj

this is a quick sim; let me know if you need anything more

**Comment by Hekili** [comment]
As a temporary measure, you can disable the second entry in your standard_rotation action list.  It never gets used in your sim.

**Comment by taintedbunny** [comment]
Hey, that's working! Thanks a million!

**Comment by Hekili** [comment]
This should be resolved in the upcoming release (1.0.18).

**Comment by taintedbunny** [comment]
Awesome. Keep up the great work.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Hekili** [comment]
Hey, this line was updated in simc this weekend -- the last check is actually an enemy check.

The new line is:

> actions.standard_rotation+=/fireball,if=buff.deathborne.up&runeforge.deaths_fathom&variable.time_to_combustion<buff.deathborne.remains&active_enemies>=2

I'll update the addon later today.

**Comment by taintedbunny** [comment]
Awesome!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
