### ISSUE TITLE
[REC] Arcane Mage Evocation at High Mana

### ISSUE THREAD

**Issue by sanyex89** [Hekili/hekili#1217]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sometimes without CD enabled and in AOE situations hekili suggest using evocation, altough i am at 90-100% mana.
Kyrian - no legendary equipped

### How to Reproduce

Go into AOE situations (3-5 mobs) disable CD recommendations and do the priority - evocations will be suggested sometimes at 100% mana

### Snapshot (Link)

https://pastebin.com/08ExFEdq

**Comment by Hekili** [comment]
It recommended Evocation because it found literally nothing else to do.

What do you think should've been recommended, and why?

**Comment by sanyex89** [comment]
4x Arcane Blast / 4 x Arcane Explosion + 1 Arcane Barrage at 4 Arcane Charges? It feels off, if a pack has 90% hp and everyone else is attacking and i stand in the back evocating at 90%+ Mana maybe this is the way, but it feels wrong for me. Especially standing on top of the rune of power with 4 sec left casting evocation.

**Comment by Hekili** [comment]
Sure.  Those are a lot of your buttons to push.  Which one did you think would've been the right one, at that moment, and why?

I'm not arguing with you.  I'm asking you for information to aid in investigating the issue.

**Comment by Hekili** [comment]
Can you sim yourself in an AOE scenario on Raidbots and provide the link here, as well?  Thanks.

**Comment by sanyex89** [comment]
Touch of magi = 4 Charges -> Arcane Power / Rune of Power -> Arcane Barrage to waste the Charges -> (if skilled) Arcane Orb = 4 Charges -> Arcane Barrage to waste the Charges -> 

1-4 x arcane blast = out of range for arcane explosion
1-4 x arcane explosion = 3 or more mobs in range for arcane explosion
4 x Arcane Charges -> 1 Arcane Barrage  -> back to 1-4 x Arcane Blasts for the Charges into Arcane Barrage ... and so on 

https://www.raidbots.com/simbot/report/axaSE6RyRs2jPs8yHfx4NX

its hard for me to explain but i lose alot of damage if i use evocation right after using my DMG CDs Touch of Magi, Radiant Spark and Rune of Power (all still active while channeling evocate at 85% mana)

maybe another more experienced arcane mage could say something to that problem or aoe rotation?

**Comment by Hekili** [comment]
No, at the moment it told you to press Evocation, what is the one button you believe you should've pressed at that moment.  Not the rotation.  One button, at that moment.  Why that button?

Thanks for the sim link.

You don't need to persuade me that it's an issue to Evocate when you don't need to Evocate.  I'm on board with that.  I'd just like you to say what you thought you should've been doing in that one instant instead.

**Comment by Hekili** [comment]
Also, try using one of the latest betas and see if that has an impact.  Looking at your snapshot, this may have been related to a channeling bug that is resolved in the latest beta.  

https://github.com/Hekili/hekili/releases/tag/v9.1.0-1.0.18-beta5

If you still see this issue with 1.0.18-beta5, please grab another snapshot and link it here.  Thanks!

**Comment by sanyex89** [comment]
4 Options i would say at 50%+ Mana:
- less than 4 charges and out of range? arcane blast
- less than 4 charges and in range? arcane explosion
- 4 charges? arcane barrage
- Touch of the Magi on Target and Clearcasting? Arcane missiles

basicly the normal stuff you would do, if evocation wouldnt pop up 

ok ill try the beta

**Comment by sanyex89** [comment]
1.0.18 beta5:
still the same at 100% mana aoe rotation at 5 targets (out of range for arcane explosion)

https://pastebin.com/CU4GuLRy

btw i only have this problem right now if i am out of range for arcane explosion in aoe situations

**Comment by Hekili** [comment]
> 4 Options

**1** option.  What would you have pressed at that actual moment instead?

> btw i only have this problem right now if i am out of range for arcane explosion in aoe situations

There we go.  Arcane Explosion is ruled out due to range checking that was recently asked for and added.  That quickly came back to haunt us.

I will probably remove that Evocation entry from the priority entirely, then let the single-target priority get used if nothing in the AOE priority is selected.

**Comment by sanyex89** [comment]
1 option? arcane barrage

yeah seems to be the best option

thank you for your patience

**Comment by Hekili** [comment]
The fix for this will be in the next release (today).

That said, if you notice performance issues in AOE, please submit a separate ticket for Arcane Mage.  The way this works, it could result in a lot more processing for AOE decisions when you're not in range.

**Comment by sanyex89** [comment]
**RoP**, Radiant Spark, Touch of the Magi
