### ISSUE TITLE
[REC] Assassin rogue/necro - kevin's oozeling uptime is not prioritized.

### ISSUE THREAD

**Issue by radogor** [Hekili/hekili#1218]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a necrolord assassination rogue, using marileth's last trait (kevin's oozeling), I expect it's uptime maximized, while now its not the case - SBS is used only to get a debuff and when charges are nearly to cap, allowing to drop kevin's buff. Best would be to align with cooldowns, if possible.

### How to Reproduce

1. Necro assassination rogue, use marileth til llast trait Kevin's Oozeling.
2. Start rotation on dummy, it goes via stealth, garrote, sbs for debuff and then observe - when kevin's buff is gone, its not refreshed by sbs again, mutilating instead.
(in a snapshot I used 2 targets).

### Snapshot (Link)

https://pastebin.com/HaENtPQ3

### Additional Information

Thanks for the great work!

### Contact Information

Варяг (Муро)#2174

**Comment by Hekili** [comment]
Is Kevin's Oozeling prioritize in your sim?  If not, you may want to take this up with the Rogue theorycrafters (they may have found it's not worth it).  I don't see any conditionals in the sim profile related to Kevin's Oozeling.

In either case, please sim yourself on Raidbots and provide a link.  I can potentially investigate this a bit.

**Comment by radogor** [comment]
>>>Is Kevin's Oozeling prioritize in your sim? If not, you may want to take this up with the Rogue theorycrafters (they may have found it's not worth it).
Not really sure, I'll try to discuss with them.

>>>In either case, please sim yourself on Raidbots and provide a link. I can potentially investigate this a bit.
Here is a link to quicksim: https://www.raidbots.com/simbot/report/fnU7PCT81dDnfPUQCpd5YD
I'd try to perform advanced sim with sbs prioritized, but dont know how, actually, my knowledge in APL not that good.

**Comment by Hekili** [comment]
> I'd try to perform advanced sim with sbs prioritized, but dont know how, actually, my knowledge in APL not that good.

You'd have to edit the sim priority to prioritize SKS differently, which is basically the hardest part of everything.

If you had to explain when to use SKS to improve Kevin's Oozeling's uptime, what would the exact conditions for SKS's usage be?

**Comment by radogor** [comment]
>If you had to explain when to use SKS to improve Kevin's Oozeling's uptime, what would the exact conditions for SKS's usage be?

Id say definitely during Vendetta and Shiv. Apart of that - a bit reverse SBS usage - use as a default builder right from the start, to get max Kevin's time (its logic that SBS adds time to Kevin's Oozeling buff, not refreshes), and then use either to align with Vendetta and/or Shiv or as soon as there is a charge available.

**Comment by radogor** [comment]
And other big cooldowns like bloodlust.

**Comment by radogor** [comment]
I need to add that as im mainly m+ runner, not raiding, kevin's uptime is important on trash packs. So, if prio it at the start of the pull, it'll last potentially entire fight.

**Comment by Hekili** [comment]
I've yet to find an opportunity to do this where it provides a DPS increase.  I'd need a snapshot (or a few) where you think SBS should be recommended to proc Kevin's Oozeling.

You may see increased usage of SBS in general if you turn on target cycling, which would be relevant in M+ packs.

See /hekili > Assassination > Targeting for "Recommend Target Swaps."

**Comment by Hekili** [comment]
Okay, I am testing some changes in 1.0.19-beta2; it'll literally just recommend SBS if you have the soulbind and he isn't there.  It looks DPS positive but doesn't really make an effort to sync up with anything.

**Comment by radogor** [comment]
> 
> 
> I've yet to find an opportunity to do this where it provides a DPS increase. I'd need a snapshot (or a few) where you think SBS should be recommended to proc Kevin's Oozeling.
> 
> You may see increased usage of SBS in general if you turn on target cycling, which would be relevant in M+ packs.
> 
> See /hekili > Assassination > Targeting for "Recommend Target Swaps."

Yes, I'm actually doing so, but I dont personally like target swapping advices. I'd manually change targets to spread dots.

**Comment by radogor** [comment]
> 
> 
> Okay, I am testing some changes in 1.0.19-beta2; it'll literally just recommend SBS if you have the soulbind and he isn't there. It looks DPS positive but doesn't really make an effort to sync up with anything.

Thank you!
