### ISSUE TITLE
[FEATURE] pet.Storm_elemental.active duration needs to be checked to match depending on conduits.

### ISSUE THREAD

**Issue by elsavira** [Hekili/hekili#1219]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Currently, the pet.storm_elemental.active gets set to false after a preset amount of time. This happens even when storm elemental is STILL up.

 Presumably this has to do with the Call of Flame conduit extending the uptime on elementals.

### Additional Information
This has been checked repeatedly on dummies, where recommendations start failing in the latter third of Storm Elemental being up. 

Tested by setting lightning bolt as the only thing to be cast during SE, and flame shock above it with the flag ''if=!pet.storm_elemental.active"

build: v9.1.0-1.0.17
level: 60 (60)
class: SHAMAN
spec: elemental

talents: aftershock
    ancestral_guidance
    earthen_rage
    primal_elementalist
    spirit_wolf
    storm_elemental
    stormkeeper

pvptalents: counterstrike_totem
   lightning_lasso
   spectral_recovery

covenant: night_fae

conduits: call_of_flame = 8
   condensed_anima_sphere = 8
   high_voltage = 7
   spiritual_resonance = 8
   totemic_surge = 7
   vital_accretion = 8

soulbinds: [niya]
   bonded_hearts = 1
   grove_invigoration = 1
   niyas_tools_burrs = 1
   run_without_tiring = 1
   survivors_rally = 1
   swift_patrol = 1

sets: none

gear: arachnid_cipher_ring = 1
    blighted_margraves_cloak = 1
    boneshatter_gauntlets = 1
    boots_of_shuddering_matter = 1
    coiled_stygian_grapnel = 1
    electrified_compression_shirt = 1
    harness_of_twisted_whims = 1
    inscrutable_quantum_device = 1
    lakalis_spire_of_knowledge = 1
    lichbone_legguards = 1
    mistwrap_manacles = 1
    nathrian_usurpers_mask = 1
    ornately_engraved_amplifier = 1
    plagueborne_shoulderguards = 1
    stitchfleshs_misplaced_signet = 1
    unbound_changeling = 1

legendaries: seeds_of_rampant_growth = 1

itemIDs: 151263, 172324, 178708, 178714, 178736, 178755, 178764, 178778, 178796, 178816, 178933, 179350, 179353, 185842, 186301, 186302

settings: aoe = 5
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = SE No LvB
    petbased = false
    potion = potion_of_spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    funnel_damage = false
    funnel_targets = 1
    stack_buffer = 1.1

toggles: cooldowns = true
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

### Contact Information

elsavira#2556

**Comment by Hekili** [comment]
Good call-out.  I'll have a test fix in the next beta build, probably later tonight (1.0.18-beta6).

**Comment by Hekili** [comment]
This will be in the full release this morning.
