### ISSUE TITLE
Balance opener change.

### ISSUE THREAD

**Issue by noiseuu** [Hekili/hekili#1220]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello!

So rotation works fine, but atm rotation waits 90-100 astral power when uses incarn + ravenfrenzy.
https://gyazo.com/9a26303b2703504c3f2534bc6db75f30
So in that gyazo, in apl it uses cd:s but rotation it wants use starfires until u have 90-100 astral power.

### How to Reproduce

1. Enter my druid
2. Doing normal opener.
3. Paused for snapshot.

### Snapshot (Link)

https://pastebin.com/kTF497ET

**Comment by Hekili** [comment]
Separating cooldowns out into a separate display may simply not work for you here.

Testing on target dummies might also not be effective because they don't die, so time to die calculations get silly.

The conditions for Incarnation, in your snapshot, are ultimately as follows.

```
! druid.no_cds[false] & variable.cd_condition[true] & ( ( cooldown.empyreal_ordnance.remains[0.00] < 167 + ( 11 * runeforge.sinful_hysteria.enabled[true] ) & equipped.empyreal_ordnance[false] ) | astral_power.current[90.00] >= 90 & ( ! talent.fury_of_elune.enabled[true] | buff.ca_inc.duration[28.50] > cooldown.fury_of_elune.remains[0.00] + 8 ) & dot.sunfire.remains[10.66] > 12 & dot.moonfire.remains[13.35] > 8 & ( dot.stellar_flare.remains[19.35] > 8 | ! talent.stellar_flare.enabled[true] ) & variable.thrill_seeker_wait[true] & ( buff.kindred_empowerment_energize.up[false] | ! covenant.kyrian[false] ) & target.time_to_die[1004.00] > buff.ca_inc.duration[28.50] * 0.7 | boss[true] & fight_remains[1004.00] < buff.ca_inc.duration[28.50] | covenant.night_fae[false] | buff.bloodlust.up[false] & buff.bloodlust.remains[0.00] < buff.ca_inc.duration[28.50] + ( 9 * runeforge.primordial_arcanic_pulsar.equipped[false] ) ) & ! buff.ca_inc.up[false] & ( ! covenant.night_fae[false] | cooldown.convoke_the_spirits.up[true] | boss[true] & fight_remains[1004.00] < cooldown.convoke_the_spirits.remains[0.00] + 6 | fight_remains[1004.00] % 180 < buff.ca_inc.duration[28.50] )
```

That's not going to be easy to interpret, but it's worth noting that your sim has Bloodlust up and your character doesn't.  That appears to be the relevant difference.

**Comment by noiseuu** [comment]
Okay, but if raid pop lust its gonna still use that rotation.

**Comment by Hekili** [comment]
That'd be the time to snapshot when you submit a ticket, then.

**Comment by noiseuu** [comment]
https://pastebin.com/yz2w9d5V
Here is snapshot, with drums

**Comment by Hekili** [comment]
I don't see a buff from Drums, and you're in Incarnation in that snapshot.

**Comment by Hekili** [comment]
(15% from Drums is not really treated as Bloodlust within the addon anyway, but arguably it should/could be supported that way.)

**Comment by noiseuu** [comment]
Okay, then i need just forget that starfire after dots.
