### ISSUE TITLE
[REC] Arms Warrior priority recommendation re: Execute vs. Mortal Strike.

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#1221]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

After few fights i recomending add this condition for Arms warrior Execute phase:

Action List: Execute
Spel: Execute (row 22 )
 "runeforge.enduring_blow.enabled & cooldown.mortal_strike.remains > gcd"

The reason for this is enduring blow lego and its efect. While this lego active, allways prio is  Mortal strike even at execute phase. Without this condition, hekili recomending use execute even when mortal strike is ready for use and this is loss dps. 

Snapshot: https://pastebin.com/gvGbUnSw
Hekili data: https://pastebin.com/EhKU14wW
Logs: 2 x guardian fight  pure ST (Dastrolwarr nickname) : https://www.warcraftlogs.com/reports/96d8PhWacnmA71YR/

**Comment by Hekili** [comment]
Addon behavior matches the sim, and sim testing doesn't demonstrate a DPS benefit for the change you requested, so I won't move forward with this.
