### ISSUE TITLE
[REC] Venthyr Balance Druid / Ravenous Frenzy/Celestial Alignment

### ISSUE THREAD

**Issue by thomasbrezina** [Hekili/hekili#1222]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

 Neither Celestial Alignment nor Ravenous Frenzy is being recommended (or rarely). I checked if it is checked in the abilities and what it says in the priorities but for some reason it does not seem to recommend it ever.

### How to Reproduce

1. Enter Game as Venthyr Balance Druid
2. try the rotation on anything and you will see that the two biggest CDs are not being recommended

### Snapshot (Link)

https://pastebin.com/4KaQmdNC

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2GybyUamFezP8qZDpPoSCT

### Contact Information

ThomasBrezina#6159

**Comment by Hekili** [comment]
As discussed in Discord, a snapshot from a moment where CA or Ravenous Frenzy should've been recommended, but isn't, is needed to triage this.

If you look at your sim link, you'll find that Ravenous Frenzy isn't recommended until several seconds into the fight, after a long chain of Starfires:

![image](https://user-images.githubusercontent.com/9438134/130102047-051711b6-cf72-418b-83f2-3959a36c6e59.png)

That would be the approximate time you'd want to provide a snapshot.
