### ISSUE TITLE
[FEATURE] Difference between Target Swap and Mouseover Recommendation Indicator

### ISSUE THREAD

**Issue by Snoogey** [Hekili/hekili#1224]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Do you have any plans to make the indicators for "Mouseover cast on a different target" vs "Swap to a different target" different?
I'm having a hard time understanding wether it wants me to Target Swap vs Mouseover Cast as for some abilities it means swap, but other others it means mouseover.

**Comment by Hekili** [comment]
Honestly, this is probably overthinking it entirely.  In the rare cases that it matters (i.e., you swap to a target you cast Havoc on), it would tell you to swap off the target as well.

Give me more information about the situations where you feel this would help you.

**Comment by Snoogey** [comment]
Sure, absolutely - I might be overthinking it. On one hand I mean you get used to it after a while and don't tab target anymore, as you know that's what it's not asking you to do,  such as the case for Havoc.
But in other cases when I haven't played the class that much, I have to "get used" to which abilities this is the case, tab, realize it means Mouseover, then throw my Mouse over a Target and cast what needs to be casted.
I'd say it would be more "user friendly" to have them be different, however this might be quite the rewrite for every single spec that uses this logic. In the case where I can see a little "mouseover" icon instead coming up in the 3rd/2nd suggestion, I can already position my mouse and "get ready" for that part if I'm not used to the spec yet.

Indeed nothing critical or major, just a minor little suggestion. However if this suggestions requires a major rewrite in terms of how the indicator is set, then perhaps not worth it.

Thanks tho :)

**Comment by Hekili** [comment]
I appreciate the additional depth.  Can you tell me more about these other scenarios where it's misleading?  Which classes?  Which specific abilities?

It doesn't require a dramatic rewrite to support a different indicator, but it does change what a lot of users will see and may create a large volume of new questions that ultimately don't help people do better DPS.  But maybe it is important in some cases.

Which cases would those be?

**Comment by Snoogey** [comment]
I've only really played two Specs where I've greatly encountered this, so I'll use those as an example, both with their own quirks which make it fairly confusing.

First being **Destruction Warlock**, wherein there's a tip directly in the Options (/hekili > Destruction > Core) that reminds the user that when the "swap" icon is showing on Havoc or Immolate, that means it wants you to Mouseover Cast these spells without swapping to a new target.
Is this also the case when Recommend Target Swap is enabled? I.e. _always_ when Immolate or Havoc is shown with the "swap" icon, it always means Mouseover Cast, even with Target Swap enabled?

Then we have **Assassination Rogue**.
Marked for Death seems to sometimes give a case of "Mouseover Cast", while in some cases enough Tabbing will change it to no "swap" icon. I mostly always run Recommend Target Swap on my Assassination Rogue, so I've gotten used to just slamming it with Mouseover on the Lowest Health Unit in the pack we're fighting. I guess that's always what it wants, however I got fairly confused the first time using MfD without Recommend Target Swap enabled and I saw the indicator pop up.

Next is probably the most confusing part for Assassination Rogue - the "Funnel AOE -> Target" setting.
Does this change the "Recommend Target Swap" functionality in any way, i.e. all "swap" recommendations become "mouseover" recommendations instead? As in, if youre focusing on a primary target, I would assume any case of "swap" gets removed and should instead be "mouseover", as you have a primary target you want to funnel damage on.
Hekili obviously doesn't know what your Primary target is, so if you swap it just considers this new target to be the "Primary".

I have of course learned to adapt to these things, it's not rocket science for anyone using it.
I just figured I'd raise it in case you felt like it could/_should_ be made more clear, or if it puts another layer of complexity that isn't worth it in the long run.

**Comment by Hekili** [comment]
This ticket is super outdated and will be closed, but I should've responded to the last post after you answered about it.

In each of those cases, there's nothing *wrong* with swapping targets.  The mouseover macros are just *options* for when you're using target swapping and need to multidot but you don't want to change your actual target.  It's not wrong to switch targets.  It's not wrong to not switch targets.

In any of these sim profiles, your character actually *would* switch to the new target and stay there until some other action's criteria required swapping again.  Using the *optional* macros avoids that, because usually in PvE content, you're targeting what you're targeting quite intentionally and don't want to swap permanently, but also don't want to lose the benefit of target swapping.
