### ISSUE TITLE
[REC] Necro Druid / Feral Swarm usage 50%->75% increase by changing of APL

### ISSUE THREAD

**Issue by SkullCandyTV** [Hekili/hekili#1225]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The current APL that Hekili uses reapplies Swarm on targets with 3 or more stacks / uses it on cooldown which results in a significant reduction in uptime while also wasting a stack of swarm each time. 

The current simc doesn't overcap and reaches 75%~ uptime.
[Example sim of my Feral Druid](https://www.raidbots.com/simbot/report/mV82zmeZAgqBkHMhrU9psU)

The current Hekili APL basically uses swarm on CD which results in lost stacks and only 50% uptime.
[Example uptime of me using Hekili for 5m ST ](https://imgur.com/a/xrL6duy)

Implementing this change or at the very least giving an optional toggle for a more efficient use of swarm would improve the uptime by 50% from 50% to 75%+ like the current sim one does, as that is also how the leading Feral players use this spell, as it was intended to be juggled this way. 

### How to Reproduce

Using Adaptive Swarm as a Feral Druid

### Snapshot (Link)

Fundamental APL issue, no snapshot needed.

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mV82zmeZAgqBkHMhrU9psU

### Contact Information

SkullCandy#1156

**Comment by Hekili** [comment]
Latest release fixes a bug where the conditions for Adaptive Swarm were missing.  This may require more attention later.
