### ISSUE TITLE
[BUG] Balance Druid Issue

### ISSUE THREAD

**Issue by mckayrogit** [Hekili/hekili#1226]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon disappears while in combat and isn't usable. It will periodically reappear. The cast order seems to be updating.

### How to Reproduce

1. Use balance druid specialization and attack mobs.

Possibly related to arcane pulsar legendary.

### Player Information (Link)

https://pastebin.com/g1HH5qkq

### Error Messages (Link)

https://pastebin.com/yk1rcYUx

### Contact Information

Face#5427

**Comment by Hekili** [comment]
Looking at this now.

When this was happening, did you have the Primordial Arcanic Pulsar buff up?

Does this happen constantly or only after you build up enough Primordial Arcanic Pulsar that it procs and resets?

When you have the Primordial Arcanic Pulsar buff up, can you type `/run Hekili.State.reset(); print(Hekili.State.buff.primordial_arcanic_pulsar.value)` and tell me what the output is?  Can you do the same when the buff is not up?

If you open /hekili and go to Priorities > Balance > Action Lists, Action List: st, Entry: 25 and mouseover the Conditions, can you take a screenshot and post the screenshot here?

Thanks for reporting!

**Comment by sanyex89** [comment]
/run Hekili.State.reset(); print(Hekili.State.buff.primordial_arcanic_pulsar.value) = 0 without buff and 50 with 1 stack

![grafik](https://user-images.githubusercontent.com/77323774/130811815-11317cf4-0526-4920-9156-76858f61c566.png)

![grafik](https://user-images.githubusercontent.com/77323774/130811934-bd2e5a73-134a-4865-b080-4d543e3f634e.png)

**Comment by mckayrogit** [comment]
Hello,
Thank you for the quick reply. Okay, I will do this later tonight and send
you the output.

Cheers,
Rory Mckay

----------------------------------------
Intelligence, Intensity, Integrity

**Comment by mckayrogit** [comment]
Heya,
The output when I do not have the buff is 0 and then when I have the buff
it is nil.

[image: WoWScrnShot_082621_221109.jpg]
Cheers,
Rory Mckay

----------------------------------------
Intelligence, Intensity, Integrity

**Comment by mckayrogit** [comment]
[
![WoWScrnShot_082621_221109](https://user-images.githubusercontent.com/53409299/131146900-48428621-ad43-4f3d-8237-702e97207316.jpg)
](url)

**Comment by Hekili** [comment]
This one is strange because I couldn't replicate it directly.  I have prevented the nil error in 1.0.20, but I'm worried that the amount of stored energy in your Arcanic Pulsar buff isn't being parsed successfully.  I'm not sure why that would happen.

**Comment by mckayrogit** [comment]
That appears to have corrected the issue. Thank you kindly.


Cheers,
Rory Mckay

----------------------------------------
Intelligence, Intensity, Integrity

**Comment by Hekili** [comment]
Thanks for confirming.  I'd be interested in seeing a couple of additional snapshots or screenshots like you supplied before (with and without the Arcanic Pulsar buff up).  I'm curious to confirm that the actual value is being detected successfully.

**Comment by mckayrogit** [comment]
Hello,
Just an update. The issue is reoccurring. I have isolated it to enabling
and disabling another addon that conflicts with this somehow. It is called
"Ice Hud." I haven't figured out what module it is, but when I disable it
completely, the error appears to stop.

Cheers,
Rory Mckay

----------------------------------------
Intelligence, Intensity, Integrity

**Comment by mckayrogit** [comment]
I seem to have found a workaround without having to disable the "Ice Hud"
app. I have disabled blizzard's Unit Nameplates, in the
interface/names/Unit Nameplates/ area. I disabled the "Personal Resource
Display" and it has corrected the issue.


Cheers,
Rory Mckay

----------------------------------------
Intelligence, Intensity, Integrity
