### ISSUE TITLE
[REC] NecroDruid - Hekili recommends Adaptive Swarm on targets with 3+ stacks

### ISSUE THREAD

**Issue by SkullCandyTV** [Hekili/hekili#1227]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili still recommends the use of Adaptive Swarm on a Target with 3+ stacks after the update

### How to Reproduce

Use adaptive swarm as a druid on an enemy until 3 stacks are reached and the spell comes off CD

### Snapshot (Link)

https://pastebin.com/9SFQxAdV

### Contact Information

SkullCandy#1156

**Comment by Hekili** [comment]
I know it's been a long wait -- it took a pretty significant rewrite of Adaptive Swarm -- but this should be addressed in the next release.
