### ISSUE TITLE
Arcane Mage:Arcane missiles not being suggested when clearcasting buff is active.

### ISSUE THREAD

**Issue by phazeshifta** [Hekili/hekili#1228]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my arcane mage, I expect arcane missiles to be suggested to be cast when the clearcasting buff is active. Snapshot is taken while attacking a target dummy while the chearcasting buff is active and its continuing to suggest casting arcane blast.

### How to Reproduce

Attack target dummy
watch for a clearcasting buff on character
see if arcane missiles is suggested.

### Snapshot (Link)

https://pastebin.com/hhqNxVEU

### Contact Information

BillW#7208

**Comment by Hekili** [comment]
Clearcasting is not active in that snapshot.

```
player_buffs:
   127230 - *Visions of Insanity                     -   1 - 3679.53
     1459 - arcane_intellect                         -   1 - 2778.87
   186406 - *Sign of the Critter                     -   1 - 3600.00
   210126 - arcane_familiar                          -   1 - 3479.54
   311465 - *Two of Putrescence                      -   1 - 3600.00
```

**Comment by Hekili** [comment]
I'll wait for someone to submit snapshot + screenshot at the same time to support this ticket.

**Comment by phazeshifta** [comment]
Sorry you're a shitty dev:

https://pastebin.com/UuPWX1eC
https://imgur.com/a/eENZFLX

Clearcasting clearly up, 3 stacks of it in fact. Screenshot taken 1 second apart from the snapshot. 

Either you're blind, stupid or incompetent...I'm starting to think all three.

Maybe don't tell people that are trying to help you be better that they're lying to you.

**Comment by Hekili** [comment]
I am fascinated.  You're insulting and abusive, but you also provided some information I asked for, together.

What do you think happens at this point?  If the roles were reversed, how would you handle it?  I'm genuinely interested.

**Comment by phazeshifta** [comment]
I wouldn't be put in this situation, because I'm not a shitty dev. I would take the information provided, not make my users jump through hoops and do my damn job. 

You don't want to work with the information I've now provided you, through multiple channels multiple times now, that's your prerogative. It doesn't make you any less of a piece of shit.

**Comment by SpatenLa** [comment]
i just want to say, now the snapshot says the cleacasting is up.
the first snapshot was taken while you didnt have any target and werent infight.

**Comment by Hekili** [comment]
Spaten's correct regarding the buff being detected in the snapshot.

```
player_buffs:
   127230 - *Visions of Insanity                     -   1 - 1946.76
     1459 - arcane_intellect                         -   1 - 1046.11
   210126 - arcane_familiar                          -   1 - 3550.05
   186406 - *Sign of the Critter                     -   1 - 3600.00
   263725 - clearcasting                             -   3 - 7.08
   311464 - *Ace of Putrescence                      -   1 - 3600.00
```

Clearcasting was detected in your buffs.

```
        92.  arcane_missiles ( opener - 18 )
        The action (arcane_missiles) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +7.93).
        List ( opener ) called from ( Arcane:default:25 ) would PASS at 0.00.
        variable.have_opened[0.00] = 0 & ! ( covenant.kyrian[true] & runeforge.arcane_harmony.enabled[false] )
         - this entry's criteria FAILS: debuff.touch_of_the_magi.up[true] & talent.arcane_echo.enabled[false] & ( buff.deathborne.down[true] | active_enemies[1.00] = 1 ) & debuff.touch_of_the_magi.remains[1.45] > action.arcane_missiles.execute_time[1.70]
```

Arcane Missiles is not recommended above because Touch of the Magi would fall off.

```     
        93.  arcane_missiles ( opener - 19 )
        The action (arcane_missiles) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +7.93).
        List ( opener ) called from ( Arcane:default:25 ) would PASS at 0.00.
        variable.have_opened[0.00] = 0 & ! ( covenant.kyrian[true] & runeforge.arcane_harmony.enabled[false] )
         - this entry's criteria FAILS: buff.clearcasting.stack[3.00] = buff.clearcasting.max_stack[1.00] & covenant.venthyr[false]
```

Here's a logic error that needs to be fixed regarding Clearcasting's max stacks, which I'll take care of.  This would still not pass because you're not a Venthyr.

```        
        94.  arcane_missiles ( opener - 20 )
        The action (arcane_missiles) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +7.93).
        List ( opener ) called from ( Arcane:default:25 ) would PASS at 0.00.
        variable.have_opened[0.00] = 0 & ! ( covenant.kyrian[true] & runeforge.arcane_harmony.enabled[false] )
         - this entry's criteria FAILS: buff.clearcasting.react[3.00] & cooldown.arcane_power.remains[120.00] & ( buff.rune_of_power.up[false] | buff.arcane_power.up[false] )
```

This entry wouldn't pass because neither Rune of Power nor Arcane Power are up.

Anyway, the tl;dr is that you're in the opener and the logic for the APL are met during the opener, except for the max_stacks value for Clearcasting which I'll update.

I have the max_stacks issue queued up to be posted.  Other than that, we're done here as I'm not inclined to take more abuse from you.  Best of luck.
