### ISSUE TITLE
[FEATURE] Reserve 1 charge of Shadow Dance (with Enveloping Shadows talent) as CD, for Sub Rogue

### ISSUE THREAD

**Issue by Twissle** [Hekili/hekili#1230]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Enveloping Shadows talent for Sub Rogue gives Shadow Dance 2 charges. Would it be possible to add a toggle to reserve one charge for use with CDs like you have previously done with WW Monk's Storm. Earth and Fire? It's important for the spec to use 1 with other big cooldowns like Flagellation and Shadow Blades, but the other charge can be used as required.

**Comment by Twissle** [comment]
Just to add, I added Shadow Dance to the Cooldowns toggle as it wasn't previously there, but I would like it to only consider 1 of the charges as a cooldown and continue to recommend use of the other one even with the cooldowns toggle off.

**Comment by Hekili** [comment]
The biggest risk here, to be honest, is that I could force this *mechanically* but the priority itself may be written to enforce synchronization anyway.  So it might not actually accomplish anything.

**Comment by Twissle** [comment]
On further testing, I'm not sure this is actually needed, especially if it's not a straightforward fix. Shadow Dance comes back very quickly with the spec's baked-in cooldown reduction that it's not really necessary to hold a charge. I'll move Shadow Dance back out of the cooldowns section, as in default with the addon. Thanks for your time :)
