### ISSUE TITLE
As a rogue the primary display on Hekili does not change when I go into stealth

### ISSUE THREAD

**Issue by Celstar1** [Hekili/hekili#1232]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As a rogue the primary display on Hekili does not change when I go into stealth.

### How to Reproduce

Enter game as an outlaw rogue.
I go into stealth.
Icons on the primary display do not match icons on the primary stealth-action bar. They continue to match the out-of-stealth action bar.

### Player Information (Link)

https://pastebin.com/YfDdp5Dz

### Error Messages (Link)

I get no errors

### Additional Information

i made a snapshot , here is the URL.
https://pastebin.com/rEYrbiF6

### Contact Information

philmohrman@gmail.com

**Comment by Hekili** [comment]
I can't see either of those snapshots on Pastebin.

I'm not sure what you're expecting to be different about the icons that are shown based on being in stealth or not.  This is a case where screenshots and a detailed explanation would also be helpful.

**Comment by Celstar1** [comment]
![hekili issue file reduced](https://user-images.githubusercontent.com/90639029/133138912-d6439026-1ffe-41ac-9428-78693f249f51.png)

**Comment by Hekili** [comment]
So, the right buttons to push are Marked for Death, then Roll the Bones, then Slice and Dice.  That's the correct keybinding, I assume, when you're out of Stealth.

What would you rather the addon show you at this time?  I'd recommend putting MfD, RtB, and SnD somewhere that's accessible to you when you are in Stealth.

**Comment by Celstar1** [comment]
You are awesome, thank you for responding.  AND, thanks for Hekili.  When I
look at the add-on and the add-on is telling me to click a "suggested"
action I understand that.....problem is, when I look at my action bar, it
does not match the add-on visa versa.  I will copy this to someone more
familiar with the jargon.

**Comment by Hekili** [comment]
If you put Marked for Death, Roll the Bones, and Slice and Dice somewhere that's visible to you while in Stealth, you should see the appropriate keybindings.

The abilities it is recommending are the correct recommendations.  You should put those abilities on your action bars so you can use them at the right time, even in Stealth.

**Comment by Celstar1** [comment]
Thank you, time for me to leave the Training Dummie (it had a good laugh at
me).  Gonna try this out on some real monsters.  Thanks again.
