### ISSUE TITLE
[BUG] GCD Swirl on Blood DK non-GCD abilities (GCD Sync Turned off)

### ISSUE THREAD

**Issue by Larsy93** [Hekili/hekili#1233]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

GCD Swirl on Rune Tap, Raise Dead, perhaps more abilities, turned off GCD Sync in settings.

### How to Reproduce

1. Enter game as Death Knight
2. Change to Blood Specialization
3. Play until rune tap or raise dead is suggested and notice that it has a GCD swirl even tho it should not. (Aslong as gcdsync = false

### Player Information (Link)

pastebin.com/raw/SUeYQmqA 

### Error Messages (Link)

No Error Messages

### Additional Information

I know that I am only level 27 but this should not affect this specific issue.

Snapshot 1 Rune Tap https://pastebin.com/raw/SUeYQmqA

Snapshot 2 Rune Tap https://pastebin.com/raw/DKyXip3s

Snapshot 3 Raise Dead https://pastebin.com/raw/v33CMgLm

All snapshots were taken while the ability in question was the #1 Suggestion

### Contact Information

Burzum#3010

**Comment by Hekili** [comment]
Sure, I'll remove Rune Tap and Raise Dead from the GCD.

**Comment by Larsy93** [comment]
Thank you, I changed line 1289 and line 1308 in DeathKnightBlood.lua to "gcd = "off"," as a temporary fix myself, but thanks for including it in the next release, and thanks for great and quick support and an awesome addon.
