### ISSUE TITLE
[BUG] When in PvP Situations and you have Ice Form talented as a FMage, Icy Veins is still reccomended

### ISSUE THREAD

**Issue by djcosmic22** [Hekili/hekili#1235]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Ice Form replaces Icy Veins. When in PvP situations the addon still recommends Icy Veins when you cannot cast Icy Veins

### How to Reproduce

1. Play Frost Mage
2. Take Ice Form
3. Turn on War Mode or PvP

### Player Information (Link)

https://pastebin.com/vM47DfYJ

### Error Messages (Link)

N/A

### Contact Information

djcosmic2#4589

**Comment by Hekili** [comment]
Yeah, this probably should've been a feature request to add Ice Form.  PvP talents aren't generally built-in and priorities don't tend to account for their functional differences (since you can't use them in any encounters you'd actually sim).

**Comment by djcosmic22** [comment]
Should I make a new thread for a feature request then?

**Comment by Hekili** [comment]
Nope, I'll accept this and put it on my to-do list.

**Comment by Hekili** [comment]
This will work in 9.1.5.
