### ISSUE TITLE
[BUG?] Balance druid and Ravenous Frenzy 

### ISSUE THREAD

**Issue by ssonkai** [Hekili/hekili#1236]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [x] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Shows to use Starsurge 3 times before stack to full Revenous Frenzy
Video below where see what i mean 
https://streamable.com/j9oxzn

**Comment by Hekili** [comment]
Please follow ticket instructions and submit snapshots.
