### ISSUE TITLE
Simcraft and rotation code

### ISSUE THREAD

**Issue by ssonkai** [Hekili/hekili#1237]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After pasting the rotation code from simcraft my rotation only want to use moonfire

Video: https://streamable.com/rdd3mv

### How to Reproduce

.

### Player Information (Link)

https://pastebin.com/XRUqsKab

### Error Messages (Link)

no errors in game

**Comment by Hekili** [comment]
Yeah, don't do that. There's no reason to do it. 

On the default priority, the little circle-arrow button is for resetting to default.
