### ISSUE TITLE
[REC] Starsurge recommended before Ravenous Frenzy converts to Sinful Hysteria

### ISSUE THREAD

**Issue by ssonkai** [Hekili/hekili#1238]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Shows to use Starsurge 3 times before stack to full Revenous Frenzy
video: https://streamable.com/wy31gm
To maximize damage it is necessary to use 3x or 4x Starurge If we end up stacking Ravenous Frenzy, This is very important

### Additional Information

https://pastebin.com/D7EUZcA2

**Comment by Hekili** [comment]
Is there something I could do differently for you to select the right kind of ticket? This is a recommendation issue. I see you included the snapshot, but the snapshot was not taken at the time those recommendations were shown.

**Comment by ssonkai** [comment]
Sorry i copy wrong Snapshot
https://pastebin.com/ccD0ZdwT correct

I think I chose the right type of ticket

Feature Request and Priority/Recommendation Issue" I think this thread would suit both, 
"I would like the addon to have a new enhancement,"  this description fits this thread perfectly

if I'm wrong, I'm sorry, don't be angry

**Comment by Hekili** [comment]
That snapshot recommended Wrath, Starsurge, Wrath.  What did you think it should've recommended differently?

**Comment by Hekili** [comment]
Looking again, that snapshot is in the the Sinful Hysteria part of Ravenous Frenzy.  Are you intending to show me Starsurge being used prematurely during the Ravenous Frenzy part?

**Comment by ssonkai** [comment]
Watch what's happening from 34 seconds in the video, look at the stacks and time left of Ravenous Frenzy (https://imgur.com/a/NYqfhZ5) < Screen
When we have 25 stacks and we are in the 1st stage of stacking them, we have 1.5 seconds to stack them, the rotation starts using 3x starsurge in a row. After 1.5 seconds we have an additional 5 seconds of Revenous Frenzy with how many stacks we could get and at this crucial moment we should use 3x starsurge or 4 if we can cast. 

In the video you can see that only 1x starsurge was cast when we have maximum stacks of Ravenous Frenzy

https://youtu.be/V0p_4F9H5Oo?t=581 here is the exact explanation

**Comment by Hekili** [comment]
Will you be providing the required snapshot at the right time?

**Comment by ssonkai** [comment]
https://pastebin.com/3M8aUHti

**Comment by Hekili** [comment]
The criteria that passed, in order for Starsurge to be recommended in your snapshot, was:

```
buff.oneths_clear_vision.up[false] | 
buff.kindred_empowerment_energize.up[false] | 
buff.ca_inc.up[true] & ( 
    buff.ravenous_frenzy.remains[1.49] < gcd.max[0.94] * ceil ( astral_power.current[98.50] / 30 ) + 3 * talent.new_moon.enabled[false] & ! runeforge.sinful_hysteria.enabled[true] & buff.ravenous_frenzy.up[true] | 
    buff.ca_inc.remains[5.24] < gcd.max[0.94] * ceil ( astral_power.current[98.50] / 30 ) | 
    buff.ravenous_frenzy_sinful_hysteria.up[false] | 
    ( buff.ravenous_frenzy.remains[1.49] < action.starfire.execute_time[1.12] & spell_haste[0.62] < 0.4 | buff.ravenous_frenzy.remains[1.49] < action.wrath.execute_time[0.94] | variable.iqd_condition[false] & cooldown.inscrutable_quantum_device.ready[false] & equipped.inscrutable_quantum_device[true] ) & buff.ravenous_frenzy.up[true] | 
    ! buff.ravenous_frenzy.up[true] & ! cooldown.ravenous_frenzy.ready[false] |
    ! covenant.venthyr[true] ) | 
astral_power.current[98.50] > 90 & eclipse.in_any[true]
```

That translates to:

```
Any of 1 through 4, as long as at least 1 of its subcriteria are met:

1.   Oneth's Clear Vision is up -- nope.
2.   Kindred Empowerment Energize is up -- nope.
3.   Celestial Alignment or Incarnation is up, and:
     a.   Ravenous Frenzy is up and will expire in the time you can dump your Astral Power and you don't have Sinful Hysteria -- nope.
     b.   Celestial Alignment / Incarnation will expire in the time it would take to dump your Astral Power -- nope.
     c.   The normal Ravenous Frenzy ended and you're in the Sinful Hysteria part -- nope.
     d.   Ravenous Frenzy is up, and:
          i.   RF will expire before you can finish casting a Starfire and your spell haste is less than 40% -- nope.
          ii.  RF will expire before you can finish casting a Wrath -- nope.
          iii. It's time to use IQD and IQD is ready and equipped -- nope.
     e.   Ravenous Frenzy is down and not ready to be cast -- nope.
     f.   You're not a Venthyr -- nope.
4.   Your Astral Power is over 90 and you're in an Eclipse -- yep.
```

So, based on the APL, just like your sim, you're firmly in the "if you don't cast Starsurge, you're going to overcap and waste AsP" range.  I looked at the sim profile to see if I missed anything, and that entry is preceded by the following comment.

`# Use Starsurge Oneth procs and dump AsP when CA/Inc or the Venthyr buff is about to fall off or you'd cap AsP`

So the priority is intentionally avoiding overcapping, and is behaving as intended in the case of your snapshot.

Looking at your [screenshot](https://imgur.com/a/NYqfhZ5), that is recommending Wrath, Wrath, Starsurge while you have ~3 seconds left on Ravenous Frenzy.  What's wrong about that?  Do you think you shouldn't cast Starsurge after casting two more Wraths? Ravenous Frenzy would have about 1 second remaining (or less, depending on your haste).

I'd need a snapshot from that specific scenario to judge, but it seems like 3.a from the criteria above would pass as well as 3.d.ii.  Or, again, it could be a different Starsurge entry entirely.

**Comment by Hekili** [comment]
FWIW, I did a comparison sim where that AsP overcap scenario is ignored in the last 5 GCDs of Ravenous Frenzy, and it is a DPS loss.

https://www.raidbots.com/simbot/report/hSrfQdk5nXJ8FH5n7n6LiK

![image](https://user-images.githubusercontent.com/9438134/133930665-632e3234-6360-4527-b6d1-8428025cc9e6.png)

**Comment by Hekili** [comment]
Examining the default sim profile, you can see this spelled out more clearly as well:

![image](https://user-images.githubusercontent.com/9438134/133931143-d26b8e40-4197-432e-98bf-50d654c990f0.png)

- 28.708s:  Starsurge is cast at 98 AsP.  Ravenous Frenzy is still up.
- 29.463s:  Starsurge is cast at 73.5 AsP.  Ravenous Frenzy is still up.
- 30.216s:  Starsurge is cast at 52.5 AsP.  Sinful Hysteria is now up.
- 30.970s:  Starsurge is cast at 30.5 AsP.  We're still in Sinful Hysteria, of course.

SimC doesn't have as much granular detail as an addon snapshot, unfortunately, but it's pretty safe to say that the first Starsurge is cast based on avoiding overcapping AsP.  The second is 3.d.i or 3.d.ii (or both, no time for a hardcast as RF falls off), and the third and fourth would be 3c (you're now in Sinful Hysteria).

**Comment by ssonkai** [comment]
You right sir.
