### ISSUE TITLE
[BUG] When some one in Sanctum of domination raid left or join after boss(The Nine)

### ISSUE THREAD

**Issue by vetalgn** [Hekili/hekili#1239]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have long freeze after i play in Sanctum of domination and kill The Nine(him name) boss, around 20 sec i guess. After this freeze i grab this error (link below) it happens after some one left or join the raid, for example it was in The Nine. or if some one dont left after kill The Nine it can happens after kill another boss from raid.

### How to Reproduce

1. Play arms warrior(it does not matter i think).
2. Kill The Nine or another boss.
3. Join or left some one after kill.
4. Got 20 sec freeze(only one time every raid).

### Player Information (Link)

https://pastebin.com/71uFhg4G

### Error Messages (Link)

https://pastebin.com/mdhrjFcf

**Comment by Hekili** [comment]
I would recommend reporting this issue to the SpellFlashCore maintainer on CurseForge.

**Comment by vetalgn** [comment]
ok i will try

**Comment by vetalgn** [comment]
oh SpellFlashCore doesnt support  i think. bcos last update was Jul 31, 2018, can i some thing dissable so as not to see the error?

**Comment by Hekili** [comment]
Do you use SpellFlash?  What are your SpellFlash settings?

**Comment by Hekili** [comment]
From the error itself, it seems like it's an interaction between Shadowed Unit Frames and SpellFlashCore.  Perhaps similar issues have been reported to SUF if SpellFlashCore isn't maintained.

**Comment by vetalgn** [comment]
I dont use SpellFlash addon, but yes i use Shadowed Unit Frames and I will try to send a bug report to them

**Comment by Hekili** [comment]
Thanks.  I'd recommend loading SpellFlashCore separately and disabling Hekili and seeing if you have the same bug pop up.
