### ISSUE TITLE
Problem with Bonestorm at BDK

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#124]
Hello, since the last change you made, so that the survival rate became better everything was fine, but during the whole time since the last change, I noticed that the storm of bones was never used in a large number of targets, it is only used for 1 target. I have this suggestion.

You can try to do this - if Bonestorm is registered for automatic use, we have 3 or more goals and Bonestorm is not on CD now, then we prohibit using Death Strike for sickness, but wait until 80 RPs for Bonestorm are accumulated, after which we use it. If Bonestorm is on a CD or we have less than 3 goals, then we use Death Strike for the sick as before. 
Please write, how do you think this is normal or not? Thank.

**Comment by Hekili** [comment]
I have moved Bonestorm up in the priority and this will appear in the next release.
