### ISSUE TITLE
druid balance Night Fae Celestial Alignment

### ISSUE THREAD

**Issue by Xamof** [Hekili/hekili#1241]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

at no time does hekili launch celestial alignment in its rotation, nor Convoke the Spirits

Soulletting Ruby the same 

sorry my english

### How to Reproduce

follow the rotation it does not start

### Snapshot (Link)

https://worldofwarcraft.com/fr-fr/character/eu/la-croisade-%C3%A9carlate/x%C3%A4mof/

### Raidbots Sim Report (Link)

https://worldofwarcraft.com/fr-fr/character/eu/la-croisade-%C3%A9carlate/x%C3%A4mof/

### Additional Information

https://worldofwarcraft.com/fr-fr/character/eu/la-croisade-%C3%A9carlate/x%C3%A4mof/

### Contact Information

xamof76@gmail.com

**Comment by Hekili** [comment]
You did not follow the ticket instructions properly (which is likely a language issue), but I'm going to assume you probably haven't turned on your Covenant abilities or Cooldowns.  See /hekili > Toggles.

**Comment by Xamof** [comment]
désolé pour mon anglais c'est du google traduction
exact Show cooldowns désactivé

sorry for my english it's google translation
exact Show cooldowns disabled

**Comment by Hekili** [comment]
You want to check Show Cooldowns if you want your major cooldown abilities to show.  You generally want to turn these on and off with the toggle (keybinding) while you're playing, so that the addon doesn't recommend them when you're trying to save them.
