### ISSUE TITLE
[BUG] Starfall usage at remnant orbs dont work

### ISSUE THREAD

**Issue by Yinzeni** [Hekili/hekili#1243]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello!

So this snapshot is from remnant lfr, paused insta when orbs buff is away. And dont think about opener i suddenly pushed wrong keybind :D. If u need more information just say it

### How to Reproduce

1. Enter game
2. Went lfr remnant as balance druid
3. Issue snapshot

### Player Information (Link)

https://pastebin.com/rnQL7rC8

### Error Messages (Link)

-

**Comment by Hekili** [comment]
There's no indication in your snapshot that you've hit the orb.  Did you?

**Comment by Yinzeni** [comment]
No, i didnt hit orb. Usually i see it reconizes 2-3targets but it didnt change number at all

**Comment by Hekili** [comment]
You have to hit a target for it to be counted.

**Comment by Yinzeni** [comment]
Okay, i can go try it again

**Comment by Yinzeni** [comment]
https://pastebin.com/hYac1QSx
Here

Btw this hasnt do this bug report but i guess u can see opener isnt correct. I can make new report if needed. In pull used lust and after dots it still want go to 80-90astralpower to use cd:s

**Comment by Hekili** [comment]
Thanks.  I can see that filtering by aura + damage-based target detection aren't playing nicely with each other.  I have a fix in testing.

**Comment by Yinzeni** [comment]
Okay, thanks works. How about this opener thing, do i make new report?

**Comment by Hekili** [comment]
I have no idea what you're talking about.

**Comment by Yinzeni** [comment]
"Btw this hasnt do this bug report but i guess u can see opener isnt correct. I can make new report if needed. In pull used lust and after dots it still want go to 80-90astralpower to use cd:s" In opener when u get bl/tw opener should goes like wrath-wrath-starfire-dots-incarn/rf. But atm it still wants suggest 90astpower

**Comment by Hekili** [comment]
I'm sorry, you'll need to open a separate ticket with sim and snapshots to compare for that.
