### ISSUE TITLE
[FEATURE] SCALE Option

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#1244]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Scale the icons with a slider. I do not wish to change the width or height of primary/aoe/cooldowns/defensives/interupts.

Just a slider for all of it with a scale feature then ill drag it to where I wish. Thanks

**Comment by Hekili** [comment]
I realize this is a very old ticket.

I do not plan to do this, simply because scaling is implemented poorly in WoW and I'd get endless questions about why 1 pixel borders are now taking up 0 or 2 pixels.
