### ISSUE TITLE
Change of open rotation at DEMONOLOGY WARLOCK

### ISSUE THREAD

**Issue by Myro2** [Hekili/hekili#1245]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Good day. 
would it be possible to please make a change at the opener rotation for DEMONOLOGY WARLOCK? it should look something like this. : 
![image](https://user-images.githubusercontent.com/81858506/134999762-56739ec7-2ace-4e07-ba83-3db88cce2a4c.png)

### Contact Information

tysl@email.cz

**Comment by Hekili** [comment]
This is not a feature request. 

If you build a sim profile that matches the above and it outperforms the existing sim, provide a raidbots link in a recommendations ticket.
