### ISSUE TITLE
[REC] Wrong opener with Bloodlust Balance Druid Venthyr

### ISSUE THREAD

**Issue by Yinzeni** [Hekili/hekili#1246]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello again!

So atm i feel hekili doesnt use correct opener with bloodlust. Cooldowns should use after stellar flare, and not farm 90 ap before using it. Like this
https://gyazo.com/6e6dc69ae2eaa1bdab0d1372de6ff15f

https://gyazo.com/e492a6b4bca02ce32e25699c54ce45c0
This opener what hekili uses without bloodlust is correct

### How to Reproduce

1. Enter game
2. Asked friend pop Bloodlust
3. Blast

### Snapshot (Link)

https://pastebin.com/nQUQR3yk

**Comment by Hekili** [comment]
Link the actual Raidbots sim(s).

Take the snapshot at the moment you disagree with the recommendation.  I.e., just after Stellar Flare if you think it should recommend CDs next but isn't doing so.

**Comment by Yinzeni** [comment]
Actually, i pop after stellar flare cd:s 
https://www.raidbots.com/simbot/report/cJ9GXvzrNietAGJ1Z8bwDL with bloodlust, hekili doesnt do this
https://www.raidbots.com/simbot/report/fLY5bSHwiKw9Bo4jHwG4EM without bloodlust, and hekili does this everytime with bl or not

**Comment by Hekili** [comment]
Hey, you'll need to follow instructions precisely if you want me to investigate.

**Comment by Hekili** [comment]
> Take the snapshot at the moment you disagree with the recommendation. I.e., just after Stellar Flare if you think it should recommend CDs next but isn't doing so.

**Comment by Yinzeni** [comment]
https://pastebin.com/mP5vGVzE
Here, i hope u get the point now. I paused when it suggested after stellar flare starfire
https://gyazo.com/e76e74479efd33f5f2d97367bf1a8e00 this what i see after pause

**Comment by Hekili** [comment]
This looks to be related to fight length, which is confabulated and only going to get worse vs. a target dummy (because they'll never really die).

A snapshot taken in an actual raid environment, immediately after you've cast Stellar Flare, would help confirm.

**Comment by Yinzeni** [comment]
https://pastebin.com/txnY5fL4
This is from heroic tarrague, i hope anima powers dont fuck this up

**Comment by Hekili** [comment]
Thanks, that helps.  Fight length will be a factor, because there's logic that centers on using CA/Incarn if you'd otherwise get 1 fewer cast in your boss fight.  However, this also revealed that the logic for updating the duration of Celestial Alignment vs. Incarnation wasn't swapping correct (in your snapshot, it was showing a 29 second duration on Incarnation, when it should've been 39 seconds).  That would cause the Bloodlust logic in cd_condition_st to be met sooner.

**Comment by Yinzeni** [comment]
Are fixing this or just stay with that? And i mean like, is there both lust/timewarp/drums this 29 duration ?

**Comment by Hekili** [comment]
Yes, it'll be fixed, but your question doesn't actually line up with what I said.  You can trust that if I investigate an issue and find a bug, that yes, I'll be working to resolve it.

**Comment by Yinzeni** [comment]
Okay thanks
