### ISSUE TITLE
Shadowgrasp totem not showing with bottled flayedwing toxin buff

### ISSUE THREAD

**Issue by preeve1** [Hekili/hekili#1247]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shadowgrasp totem not showing with bottled flayedwing toxin buff. when the buff is off it will show, but when the buff is on if will not be recommended at all during a fight.

### How to Reproduce

bottled flayedwing toxin buff is on
shadowgrasp totem will not showw
bottled flayedwing toxin buff off
shadowgrasp totem will be recommended.

### Snapshot (Link)

https://pastebin.com/H7x61mtg

### Contact Information

FiggyPuddin#11883

**Comment by Hekili** [comment]
Did you edit your priority list?  The first entry in your `trinkets` list is not consistent with the default.

**Comment by preeve1** [comment]
I believe everything is stock minus cooldown togggle and single/auto toggle

**Comment by preeve1** [comment]
i've just reloaded default priorities and appears to not work still.

**Comment by Hekili** [comment]
Post a new snapshot, please.

**Comment by preeve1** [comment]
https://pastebin.com/SJ2dsAGd

**Comment by Hekili** [comment]
This *may* be fixed for 9.1.5.
