### ISSUE TITLE
[BUG] Hard freeze (not responding) when logging in with Hekili activated on Warrior only

### ISSUE THREAD

**Issue by xxxj2kxxx** [Hekili/hekili#1248]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Very strange issue that took a few hours to narrow down... When I log into WoW on my Horde Venthyr Warrior with Hekili activated... I see the game for 1-3 frames then it hard freezes (not responding). All other characters work fine with Hekili activated... Turning off Hekili on my warrior stops the issue... unfortunately Fury warrior is one of the specs I enjoy Hekili with.

### How to Reproduce

Activate Hekili
Log into my Horde Venthyr Warrior
Instant hard freeze (not responding)

All other characters work fine with Hekili.

### Player Information (Link)

Can not open hekili on the affected toon

### Error Messages (Link)

No message, just hard freeze

### Contact Information

Doublebrutal#4438

**Comment by Hekili** [comment]
Get BugSack and BugGrabber to see if there are error messages.

**Comment by xxxj2kxxx** [comment]
OK will try this tomorrow cheers

**Comment by Hekili** [comment]
Thanks.  You could try deleting your Hekili profile (`WTF\Account\<Account #>\SavedVariables\Hekili.lua`) before starting WoW.  I'm not aware of anything that could endlessly loop at the moment.  That will mean you have to redo your layout and everything again, though.

If you can share your Warrior's armory/bnet profile and/or /simc output with the SimulationCraft addon, that could help me try to replicate the issue.

**Comment by xxxj2kxxx** [comment]
Sorry for late update... just installing bug grabber and bugsack stopped the hard freeze. No idea how/why but thats literally the only thing I changed.

**Comment by xxxj2kxxx** [comment]
... and turning both those addons off it still works... just one of those weird things I guess

I also deleted both Bug addons and relaunched game and warrior still logs in just fine now... neither bug addon showed me anything they just magically fixed it :S
