### ISSUE TITLE
Key binding shortcuts fine tuning

### ISSUE THREAD

**Issue by TinyTrbl** [Hekili/hekili#125]
Hello.

Can you change some key binding (popup bar action button text) shortcuts to more appropriate style?

key shortcut **BACKSPACE** to BKSP or something like this instead of extremely long BACKSPACE 
directional arrow shortcut **U** to UP instead of U
directional arrow shortcut **D** to DOWN or DN instead of D

I tried to do change them manually but was unable to find correct file...

Thank you!

**Comment by Hekili** [comment]
Fixed in tonight's upcoming release.
