### ISSUE TITLE
Cool down spinner doesn't work for festering strike and scourge strike...unholy

### ISSUE THREAD

**Issue by Bat1000** [Hekili/hekili#1250]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Cool down spinner doesn't work for festering strike and scourge strike...unholy. All other actions display properly and the spinner is working. Only the two actions seem to be affected.

### How to Reproduce

Load as a unholy DK and see if the spinners work for scourge strike and festering strike.

### Player Information (Link)

build: v9.1.0-1.0.22 level: 60 (60) class: DEATHKNIGHT spec: unholy  talents: army_of_the_damned     asphyxiate     clawing_shadows     death_pact     soul_reaper     unholy_blight     unholy_pact  pvptalents: none  covenant: necrolord  conduits: convocation_of_the_dead = 10    embrace_death = 7    eternal_hunger = 8    fleeting_wind = 7    reinforced_shell = 9    spirit_drain = 9  soulbinds: [plague_deviser_marileth]    kevins_oozeling = 1    oozs_frictionless_coating = 1    plagueborn_cleansing_slime = 1    ultimate_form = 1    undulating_maneuvers = 1    volatile_solvent = 1  sets: none  gear: airborne_abductors_vambraces = 1     caged_legplates = 1     cavalier_oathbreakers_grasps = 1     cuirass_of_the_lonely_citadel = 1     dark_tormentors_gaze = 1     death_gods_signet = 1     grimveiled_cape = 1     periapt_of_pristine_preservation = 1     sparkdeflecting_girdle = 1     spires_of_broken_hope = 1     sworn_oath_of_the_nine = 1     titanic_ocular_gland = 1     tormented_rack_fragment = 1     warboots_of_ruthless_conviction = 1     zinkhas_blade_of_the_fallen_god = 1  legendaries: deadliest_coil = 1  itemIDs: 173242, 179330, 179355, 180101, 186290, 186291, 186311, 186312, 186315, 186316, 186349, 186370, 186423, 186430, 186630  settings: aoe = 2     buffPadding = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycleDebuff = festering_wound     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = true     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 8     nameplates = true     package = Unholy     petbased = false     potion = potion_of_spectral_strength     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false     festermight_cycle = false  toggles: cooldowns = false     custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false 

### Error Messages (Link)

no bugs

**Comment by Hekili** [comment]
What do you mean by "doesn't work"?

Feel free to move your player information to a Pastebin link, as well, so that it's readable.  Thanks!

**Comment by Bat1000** [comment]
https://bpa.st/SSCA

The gcd spinning effect does happen on scourge strike or festering strike. All other actions will spin. I have to look at the other icons to see when either of those actions are available.

**Comment by Bat1000** [comment]
n

**Comment by Hekili** [comment]
> bpa.st/SSCA

Well, that's not what I asked for.  You can see that it's not organized nicely.  Can you not just copy/paste from in-game so that it has proper line breaks?

After that, I'll look and see if I can replicate this issue, but no luck so far.  Do you have another addon that's skinning your GCD spirals or something?

**Comment by Bat1000** [comment]
Hopefully this is better. I am not tech savvy so it took a bit to figure this out. I'm not sure what you mean by skinning so I can't answer that question. I recently added a weak aura and method raid tools. I disabled the raid tools and deleted the weak aura but that didn't fix the issue. Those were the most recent add-ons I have downloaded. I have used your rotation helper for as long as I can remember and never had an issue to report so I am unfamiliar with the process, sorry if I am making things frustrating.
https://pastebin.com/k8iqJafg

    On Saturday, October 2, 2021, 06:04:47 AM PDT, Hekili ***@***.***> wrote:  
 
 



bpa.st/SSCA


Well, that's not what I asked for. You can see that it's not organized nicely. Can you not just copy/paste from in-game so that it has proper line breaks?

After that, I'll look and see if I can replicate this issue, but no luck so far. Do you have another addon that's skinning your GCD spirals or something?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hekili** [comment]
Thanks for the Pastebin.  I don't see the same issue when I use Unholy with your settings.

By skinning, I'm asking if you have another addon that changes the look and feel of your icons or cooldown spirals.  Masque is a common one.  If you have all other addons disabled and use Hekili, do you still have the issue?

**Comment by Bat1000** [comment]
I use what ever is the default setting. Nothing that changes the look or my UI. I did have some pop up that said there were errors in my addons several weeks ago but that was before this issue. When I did the error grab thing there were no errors in the add on which went back two weeks. Maybe it will fix itself after awhile?
    On Saturday, October 2, 2021, 02:43:32 PM PDT, Hekili ***@***.***> wrote:  
 
 


Thanks for the Pastebin. I don't see the same issue when I use Unholy with your settings.

By skinning, I'm asking if you have another addon that changes the look and feel of your icons or cooldown spirals. Masque is a common one. If you have all other addons disabled and use Hekili, do you still have the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Skood555** [comment]
I have the same issue on my blood dk.  Marrowrend and Heart Strike do not have the gcd effect.  All other spells are fine.  I disabled all addons and this did not solve the issue.  I think it started about 2 weeks ago, but didn't play for a week or so on this toon.  All other classes work great as usual.  Love the addon.  Thanks!

**Comment by Skood555** [comment]
So I just switched back to version .21 and it works great again.  So it seems whatever changed on the Sep 16th update with the gcd spirals did something.  Might want to start there!!

**Comment by Bat1000** [comment]
Thanks i will try that also.
Sent from Yahoo Mail on Android 
 
  On Mon, Oct 4, 2021 at 10:43 AM, ***@***.***> wrote:   


So I just switched back to version .21 and it works great again. So it seems whatever changed on the Sep 16th update with the gcd spirals did something. Might want to start there!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bat1000** [comment]
Yes, i went back to version .21 and it works for me as well.
    On Monday, October 4, 2021, 11:23:39 AM PDT, Ron Ruf ***@***.***> wrote:  
 
 Thanks i will try that also.
Sent from Yahoo Mail on Android 
 
  On Mon, Oct 4, 2021 at 10:43 AM, ***@***.***> wrote:   


So I just switched back to version .21 and it works great again. So it seems whatever changed on the Sep 16th update with the gcd spirals did something. Might want to start there!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hekili** [comment]
The changes that caused this issue have been reverted for 9.1.5.
