### ISSUE TITLE
Sub Rogue no Cooldowns displayed

### ISSUE THREAD

**Issue by lasseblooten** [Hekili/hekili#1251]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello, I tried Sub Rogue for the first time today and wanted to use Hekili to get started.
I have the Problem that Flagellation and Shadow Blades is not displayed in the recommended spelllist.
Assa and Outlaw is working fine.
I hope you can help me.
Thanks in Advance!

### How to Reproduce

1. Activate Sub Spec
2. Start doing DPS  on Target dummy 
3. no Shadow Blades or Flagellation is recommended

### Snapshot (Link)

https://pastebin.com/K0hBuMnX

**Comment by Hekili** [comment]
You have cooldowns toggled off.  See /hekili > Toggles.

**Comment by lasseblooten** [comment]
Well, I am dumb. Thanks a lot. I did toggle off these, but didn't reload...
Thanks again!
