### ISSUE TITLE
Finding priority! continually scrolls in /s white say chat

### ISSUE THREAD

**Issue by twitch122** [Hekili/hekili#1253]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Finding Priority! continually scrolls in my chat box forever
![WoWScrnShot_100521_162454](https://user-images.githubusercontent.com/91991843/136104944-8c613030-e6f0-42b0-9890-a270d33ba25c.jpg)
.

Seems to be conflicting with Hedd DPS Priority addon, but only on version of Hekili v9.1.0-1.0.18 and beyond.

### How to Reproduce

Just entering game on any character with Hedd addon and Hekili v9.1.0-1.0.18 and beyond

### Player Information (Link)

build: v9.1.0-1.0.22 level: 60 (60) class: DEMONHUNTER spec: havoc  talents: blind_fury     cycle_of_hatred     demonic     glaive_tempest     insatiable_hunger     soul_rending     unleashed_power  pvptalents: none  covenant: venthyr  conduits: condensed_anima_sphere = 7    fel_defender = 9    felfire_haste = 9    growing_inferno = 9    relentless_onslaught = 7    shattered_restoration = 9  soulbinds: [theotar_the_mad_duke]    exquisite_ingredients = 1    leisurely_gait = 1    life_is_but_an_appetizer = 1    party_favors = 1    refined_palate = 1    soothing_shade = 1  sets: none  gear: animasplattered_hide = 1     blighted_margraves_cloak = 1     bottled_flayedwing_toxin = 1     gloves_of_haunting_fixation = 1     grim_codex = 1     poxstorm_longsword_of_pestilence = 1     precisely_calibrated_chronometer = 1     ring_of_perpetual_conflict = 1     ritual_commanders_ring = 1     shadowghast_necklace = 1     shadowhirl_waistwrap = 1     shardhide_leather_breeches = 1     stone_generals_edge = 1     vanquished_usurpers_footpads = 1     visage_of_the_obliterator = 1     wicked_bladewing_pauldrons = 1  legendaries: darkglare_boon = 1     darkglare_medallion = 1  itemIDs: 178742, 178754, 178755, 178781, 178797, 178811, 178832, 178835, 178857, 178858, 178872, 178927, 180111, 183019, 185865, 187378  settings: aoe = 2     buffPadding = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 7     nameplates = true     package = Havoc     petbased = false     potion = phantom_fire     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false     demon_blades_acknowledged = false     recommend_movement = false  toggles: cooldowns = false     custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = true [separate]     mode = automatic      potions = false 

### Error Messages (Link)

4889x Hedd\lib\frame.lua:78: attempt to call field 'UpdateFlash' (a nil value) [string "@Hedd\lib\frame.lua"]:78: in function <Hedd\lib\frame.lua:70

**Comment by Hekili** [comment]
Report that to Hedd, "Finding priority!" does not exist in my addon's code anywhere.
