### ISSUE TITLE
Some abilities of the Death Knight do not have a GCD Animation

### ISSUE THREAD

**Issue by djcosmic22** [Hekili/hekili#1254]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When you DPS with Frost DK, some abilities, mainly Obliterate and Howling Blast will not advance to the next ability and show the GDC animation. When the GCD finishes, the next ability shows

### How to Reproduce

Play as Frost DK

### Player Information (Link)

https://pastebin.com/WmpcmP9U

### Error Messages (Link)

https://pastebin.com/WmpcmP9U

### Additional Information

N/A

### Contact Information

djcosmic2#4589

**Comment by Hekili** [comment]
I've reverted the CD spiral changes for 9.1.5.
