### ISSUE TITLE
Error message that won't close (sub rogue)

### ISSUE THREAD

**Issue by Avadahkadavrah** [Hekili/hekili#1255]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I try to use the Lady Moonberry's Wand quest item (during Night Fae assault) I get an error message that won't close until I reload. This is only happening with my sub rogue.
I've also had some error messages on the same char while I've been in a group

### How to Reproduce

1) Enter game as sub rogue
2) Start NF assault
3) Use Lady Moonberry's Wand (part of Snail Stomping quest)

### Player Information (Link)

https://pastebin.com/hawAATPE

### Error Messages (Link)

https://pastebin.com/1LX8cyf7

### Contact Information

Colette#7364

**Comment by Hekili** [comment]
This is fixed for 9.1.5.  Thanks for reporting.
