### ISSUE TITLE
Rogue/Sub AoE not working properly (not showing blackpowder)

### ISSUE THREAD

**Issue by Ekaj7** [Hekili/hekili#1256]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Worked fine for a couple of days then stopped displaying correct rotation. Yes i have tried and searched everything and re-installed ADDON

Any Help would be great

### How to Reproduce

Enter Game as a Sub Rogue
Go to Training Dummies
Take AoE Talents
Use Shuriken Storm on 5+ targets
It Will Show To Use Eviscerate instead Of Black Powder

### Snapshot https://ibb.co/DzFRWW2
Not Needed

**Comment by Hekili** [comment]
Please follow the ticket instructions and supply the required snapshot(s).

**Comment by Ekaj7** [comment]
Done :)

**Comment by Hekili** [comment]
Nope.  Here are the instructions.

![image](https://user-images.githubusercontent.com/9438134/137028099-a2ae2a35-a4e7-4cac-9d96-2ec0b83cfc1d.png)
