### ISSUE TITLE
Affliction warlock here and the rotation keeps reccomending a mage talent called evocation...

### ISSUE THREAD

**Issue by deschroyer** [Hekili/hekili#1257]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

build: v9.1.0-1.0.22
level: 60 (60)
class: WARLOCK
spec: affliction

talents: dark_soul_misery
    demon_skin
    drain_soul
    haunt
    mortal_coil
    phantom_singularity
    siphon_life

pvptalents: demon_armor
   rampant_afflictions
   rapid_contagion

covenant: night_fae

conduits: diabolic_bloodstone = 10
   fel_celerity = 8
   focused_malignancy = 9
   resolute_barrier = 10
   soul_eater = 9
   withering_bolt = 10

soulbinds: [dreamweaver]
   dream_delver = 1
   field_of_blossoms = 1
   podtender = 1
   somnambulist = 1
   soothing_voice = 1
   waking_dreams = 1

sets: none

gear: dark_stride_footwraps = 1
    death_gods_signet = 1
    desecrators_keening_wristwraps = 1
    grimveiled_cape = 1
    hood_of_vengeful_possession = 1
    maledict_opus = 1
    mantle_of_arthuras_chosen = 1
    precious_ribbon = 1
    sash_of_duplicitous_magics = 1
    shadowed_orb_of_torment = 1
    sin_stained_pendant = 1
    sorcerers_headlong_legwraps = 1
    soulcasters_woven_grips = 1
    soulsewn_vestments = 1
    tarnished_insignia_of_quelthalas = 1
    titanic_ocular_gland = 1

legendaries: relic_of_demonic_synergy = 1

itemIDs: 173242, 178792, 178827, 179355, 180102, 186285, 186286, 186287, 186321, 186322, 186358, 186377, 186406, 186423, 186428, 52019

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Affliction
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    manage_ds_ticks = true

toggles: cooldowns = true
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true 
    interrupts = true 
    mode = reactive 
    potions = true 

### How to Reproduce

enter a bg and target another player shows up an evocation icon that i dont have as an affliction warlock

### Snapshot (Link)

build: v9.1.0-1.0.22 level: 60 (60) class: WARLOCK spec: affliction  talents: dark_soul_misery     demon_skin     drain_soul     haunt     mortal_coil     phantom_singularity     siphon_life  pvptalents: demon_armor    rampant_afflictions    rapid_contagion  covenant: night_fae  conduits: diabolic_bloodstone = 10    fel_celerity = 8    focused_malignancy = 9    resolute_barrier = 10    soul_eater = 9    withering_bolt = 10  soulbinds: [dreamweaver]    dream_delver = 1    field_of_blossoms = 1    podtender = 1    somnambulist = 1    soothing_voice = 1    waking_dreams = 1  sets: none  gear: dark_stride_footwraps = 1     death_gods_signet = 1     desecrators_keening_wristwraps = 1     grimveiled_cape = 1     hood_of_vengeful_possession = 1     maledict_opus = 1     mantle_of_arthuras_chosen = 1     precious_ribbon = 1     sash_of_duplicitous_magics = 1     shadowed_orb_of_torment = 1     sin_stained_pendant = 1     sorcerers_headlong_legwraps = 1     soulcasters_woven_grips = 1     soulsewn_vestments = 1     tarnished_insignia_of_quelthalas = 1     titanic_ocular_gland = 1  legendaries: relic_of_demonic_synergy = 1  itemIDs: 173242, 178792, 178827, 179355, 180102, 186285, 186286, 186287, 186321, 186322, 186358, 186377, 186406, 186423, 186428, 52019  settings: aoe = 3     buffPadding = 0     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 8     nameplates = false     package = Affliction     petbased = false     potion = spectral_intellect     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false     manage_ds_ticks = true  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true      essences = true      interrupts = true      mode = reactive      potions = true 

### Raidbots Sim Report (Link)

# Áshath - Affliction - 2021-10-13 20:06 - US/Dalaran # SimC Addon 9.1.0-01 # Requires SimulationCraft 910-01 or newer  warlock="Áshath" level=60 race=gnome region=us server=dalaran role=spell professions=enchanting=115/jewelcrafting=100 talents=3312223 spec=affliction  covenant=night_fae # soulbind=niya:1,322721/202:7:1/342270/144:8:1/320687/283:7:1/220:7:1/320660/203:8:1/352501/162:7:1/352503 soulbind=dreamweaver:2,319217/160:8:1/203:8:1/319211/202:7:1/222:8:1/319216/319191/220:7:1/352779/144:8:0/352786 # soulbind=korayn:6,325066/325067/325073/325068/352806/352805 # conduits_available=174:8/201:8/202:7/203:8/204:7/205:8/206:7/207:8/208:8/211:7/212:7/214:8/220:7/144:8/168:8/171:8/221:7/160:8/162:7/222:8/283:7 renown=78  head=,id=186287,gem_id=187315,bonus_id=7188/6652/1485/6646 neck=,id=178827,gem_id=173130,bonus_id=7622/7359/6652/7576/1566/6646 shoulder=,id=186286,gem_id=187310,bonus_id=7188/6652/1485/6646 back=,id=173242,enchant_id=6203,bonus_id=7027/6649/6648/7451/1559 chest=,id=178792,enchant_id=6230,bonus_id=7359/6652/7591/1560/6646 shirt=,id=52019 wrist=,id=186321,enchant_id=6220,gem_id=187302,bonus_id=7188/6652/1485/6646 hands=,id=186358,bonus_id=7187/42/1498/6646 waist=,id=186322,gem_id=187318,bonus_id=7188/6652/1485/6646 legs=,id=186285,bonus_id=7188/6652/1485/6646 feet=,id=180102,enchant_id=6207,bonus_id=7608/7359/6652/1566/6646 finger1=,id=186377,enchant_id=6166,gem_id=173130,bonus_id=7188/6652/7576/1485/6646 finger2=,id=179355,enchant_id=6166,gem_id=173130,bonus_id=7359/6652/7576/7620/1560/6646 trinket1=,id=186428,bonus_id=7188/6652/1485/6646 trinket2=,id=186423,bonus_id=7188/6652/1485/6646 main_hand=,id=186406,enchant_id=6229,bonus_id=7188/6652/1485/6646  ### Gear from Bags # # Abominable Visage (242) # head=,id=178732,bonus_id=7359/6652/7575/7590/1556/6646 # # Ingra Maloch's Mantle (239) # shoulder=,id=178696,bonus_id=7359/6652/7604/1553/6646 # # Cloak of Scarred Honor (239) # back=,id=186289,bonus_id=7188/6652/1485/6646 # # Self-Replicating Tissue (239) # back=,id=186374,bonus_id=7188/6652/1485/6646 # # Vault Guardian's Drape (213) # back=,id=185905,bonus_id=7694/6652/1485/6646 # # Cloak of Coordination (29) # back=,id=65360 # # Leggings of the Screaming Flames (239) # legs=,id=186323,bonus_id=7188/6652/1485/6646 # # Grim-Veiled Sandals (262) # feet=,id=173243,bonus_id=7451/1559 # # Empyreal Ordnance (236) # trinket1=,id=180117,bonus_id=7603/7359/6652/1550/6646 # # "The Brokers Angle'r" (40) # main_hand=,id=180136

**Comment by Hekili** [comment]
Please submit the required snapshot and use pastebin links per the instructions.
