### ISSUE TITLE
DH Havoc too many error in UI

### ISSUE THREAD

**Issue by scouterwww** [Hekili/hekili#1258]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The rotatation and primary adn AOR are not responding

### How to Reproduce

IT only happen on my DH all other classes no error and I have 6 different ones.  

### Player Information (Link)

build: v9.1.0-1.0.22 level: 60 (60) class: DEMONHUNTER spec: havoc  talents: blind_fury     cycle_of_hatred     demonic     insatiable_hunger     master_of_the_glaive     netherwalk     unbound_chaos  pvptalents: none  covenant: venthyr  conduits: demonic_parole = 6    felfire_haste = 8    growing_inferno = 8    ravenous_consumption = 8    relentless_onslaught = 8    viscous_ink = 8  soulbinds: [nadjia_the_mistblade]    agent_of_chaos = 1    dauntless_duelist = 1    fatal_flaw = 1    friends_in_low_places = 1    sinful_preservation = 1    thrill_seeker = 1  sets: none  gear: allconsuming_loop = 1     fine_razorwing_quill = 1     gloves_of_advancing_death = 1     irradiated_undercoat = 1     korthian_twinblade = 1     lost_wayfarers_band = 1     mawsworn_lieutenants_treads = 1     nurgashs_belt_of_many_sinstones = 1     pyrophus_wrist_ties = 1     quick_oxxein_necklace = 1     renowned_guild_tabard = 1     shardhide_leather_breeches = 1     shardhide_leather_epaulets = 1     shardhide_leather_jerkin = 1     umbrahide_helm = 1     vault_guardians_drape = 1     vault_guardians_warglaive = 1     vial_of_caustic_liquid = 1  legendaries: agony_gaze = 1  itemIDs: 169878, 172317, 173146, 181503, 184130, 185865, 185895, 185901, 185905, 186219, 186756, 186757, 186769, 186976, 187376, 187402, 187538, 69210  settings: aoe = 2     buffPadding = 0     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 7     nameplates = true     package = Havoc     petbased = false     potion = phantom_fire     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false     demon_blades_acknowledged = false     recommend_movement = true  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = true      mode = automatic      potions = false 

### Error Messages (Link)

Bug Sack Error description 35588x Hekili\Classes\DemonHunterHavoc.lua:797: attempt to index field 'brand' (a nil value) [string "@Hekili\Classes\DemonHunterHavoc.lua"]:797: in function `start' [string "@Hekili\State.lua"]:5473: in function `RunHandler' [string "@Hekili\Core.lua"]:1877: in function `ProcessHooks' [string "@Hekili\UI.lua"]:945: in function <Hekili\UI.lua:810>  Locals: (*temporary) = nil (*temporary) = 945062.608000 (*temporary) = 10.539112 (*temporary) = "attempt to index field 'brand' (a nil value)" last_eye_beam = 945055.128000

**Comment by Hekili** [comment]
Thanks for the report, this is fixed for 9.1.5.
