### ISSUE TITLE
Assasination rogue rotation sometimes does not recommend spells

### ISSUE THREAD

**Issue by imarkvisser** [Hekili/hekili#1259]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Assasination rogue rotation sometimes does not recommend spells and automatically creates a snapshot. Not sure if this is something worth looking into.

### How to Reproduce

Start a fight, mostly multitarget.

### Snapshot (Link)

https://pastebin.com/raw/mZ5fgfXK

**Comment by Hekili** [comment]
There is a priority update for 9.1.5 that might make this report obsolete.  If it comes up again in 9.1.5, please reopen the ticket with a fresh snapshot and share what you believe should've been recommended at that time.
