### ISSUE TITLE
Blacklist certain targets for AOE

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#126]
I was wondering if there's a possibility to add a blacklist for targets for AOE.

For example i'm playing monk.  The aoe priority is usually correct.

But on Heartsbane Triad (Waycrest Manor) i would find the single target rotation better, so i would blacklist the 3 mobs in that fight. (for example, maybe there's other solutions, or no solutions)

or can you in the aoe action list under Conditions, add something like !targets  ...

**Comment by Hekili** [comment]
This is what the mode toggle is for.  If you want single-target recommendations in a multi-target environment, swap to single-target mode during that fight and then swap back to Auto, etc. afterward.

**Comment by ghost** [comment]
alright i will do it like that then, thanks for the quick answer
