### ISSUE TITLE
Need help with my Frost DK Rotation

### ISSUE THREAD

**Issue by Orillien** [Hekili/hekili#1260]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello there, i need help with the rotation im trying to make. Im new with this addon, and learned many commands but im not able to create the rotation i want to make. Can you please help me out ? This is what i want:

If single target:

1. Chains of ice, only with 20 stacks of cold heart
2. Remorless Winter
3. Howling Blast, only with rime up
4. Obliterate, with killing machine
5. Frost Strike if rune power is 75 or more
6. Obliterate
7. Frost Strike
(aoe is very similar, i just would change chains of ice with one howling blast for frost fever. isnt need to make an aoe rotation for this)

If Breath of Sindragosa is ready to use or in < 10 sec:

1. Howling Blast
2. Remorless Winter
3. Howling Blast, only with rime up
3. Obliterate til 100 runic power
4. (if i reach 100 runic power) Empower Rune Weapon, Breath of Sindragosa and Pillar of Frost at once
5. Obliterate spam

Its quiet easy, but it just ignore the cooldown commands and similar ones with BoS, ERW and PoF. I cant do it without them. Anyone knew what to do ?

### How to Reproduce

1. cooldown.breath_of_sindragosa.remains < 10
2. cooldown.empower_rune_weapon.remains < 10
3. cooldown.pillar_of_frost.remains < 10

### Player Information (Link)

https://pastebin.com/qfq8ZLiz

### Error Messages (Link)

https://pastebin.com/2xTuHsiQ

### Contact Information

Orillien#3171

**Comment by Hekili** [comment]
Sorry, I do not help write custom priorities.  I would recommend trying to build your priority in SimulationCraft and reference their wiki for testing purposes.

**Comment by Orillien** [comment]
> 
> 
> Sorry, I do not help write custom priorities. I would recommend trying to build your priority in SimulationCraft and reference their wiki for testing purposes.

It would be enough if you tell me whats wrong with the cooldown command with the ability breath of sindragosa because it just dont do anything and what i shall do instead.

**Comment by Hekili** [comment]
Quick guess would be that (1) it's on the Cooldowns toggle and (2) you have Cooldowns toggled off.  That'll treat BoS like it's fully on cooldown.

**Comment by Orillien** [comment]
> 
> 
> Quick guess would be that (1) it's on the Cooldowns toggle and (2) you have Cooldowns toggled off. That'll treat BoS like it's fully on cooldown.

Sometimes im feeling..........stupid as hell.....i toggled it off.......Well, thank you for that. And if i have you here for the moment anyway, it would be nice too if the ability list is sorted alphabetically to find the wanted ability faster.
