### ISSUE TITLE
Jotungeirr, Destiny's Call isn´t showing in rotation - Feral Druid

### ISSUE THREAD

**Issue by MrHunter79** [Hekili/hekili#1261]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In the rotation Jotungeirr, Destiny's Call isn´t showing.
Cooldowns on.

### How to Reproduce

Test fight on dummy - no Jotungeirr in rotation.

### Snapshot (Link)

https://pastebin.com/041uPXb3

**Comment by Hekili** [comment]
Fixed for 9.1.5's release.
