### ISSUE TITLE
[BUG] Event not found error on login

### ISSUE THREAD

**Issue by DiscordGregory** [Hekili/hekili#1265]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I get this error when loggin in. The character I saw it on was a Night Fae Beast Mastery Hunter

1x Hekili\Events.lua:115: Attempt to register unknown event "SOULBIND_CONDUIT_CHARGES_UPDATED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Hekili\Events.lua"]:115: in function `RegisterEvent'
[string "@Hekili\Shadowlands\SoulbindConduits.lua"]:518: in main chunk

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "SOULBIND_CONDUIT_CHARGES_UPDATED"

### How to Reproduce

All I did was login.

### Player Information (Link)

https://pastebin.com/UMWAtP73

### Error Messages (Link)

https://pastebin.com/bbAHMiWE

**Comment by Hekili** [comment]
1.0.1 will fix.
