### ISSUE TITLE
Lua error when logging in on 9.1.5

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1266]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I log in on 9.1.5 I get a large Lua error

### How to Reproduce

Turn on Lua error reporting.
update to 9.1.5 ( I'm on a Mac )

### Player Information (Link)

n/a

### Error Messages (Link)

n/a

### Additional Information

It is not possible to run /hekili as its apparently not loading properly.  I get command not found error
```lua
Message: Interface\AddOns\Hekili\State.lua:574: attempt to call local 'formatKey' (a nil value)
Time: Tue Nov  2 18:25:02 2021
Count: 1
Stack: Interface\AddOns\Hekili\State.lua:574: attempt to call local 'formatKey' (a nil value)
[string "@Interface\AddOns\Hekili\State.lua"]:574: in main chunk

Locals: addon = "Hekili"
ns = <table> {
 getClassID = <function> defined @Interface\AddOns\Hekili\Constants.lua:40
 getInverseDirection = <function> defined @Interface\AddOns\Hekili\Constants.lua:25
 getLocalClass = <function> defined @Interface\AddOns\Hekili\Constants.lua:9
 Patrons = "Abom, Abra, Abuna, Aern, Aggronaught, akh270, Alasha, alcaras, Amera, ApexPlatypus, aphoenix, Archxlock, Aristocles, aro725, Artoo, Ash, av8ordoc, Battle Hermit VIA, Belatar, Borelia, Brangeddon, Bsirk/Kris, Cele, Chimmi, Coan, Cortland, Daz, DB, Der Baron, Dez, Drako, Enemy, Eryx, fuon, Garumako, Graemec, Grayscale, guhbjs, Hambrick, Hexel, Himea, Hollaputt, Hungrypilot, Ifor, Ingrathis, intheyear, Jacii, jawj, Jenkz, Katurn, Kingreboot, Kittykiller, Lagertha, Leorus, Loraniden, Lord Corn, Lovien, Manni, Mirando, mr. jing0, Mr_Hunter, MrBean73, mrminus, Muffin, Mumrikk, Nelix, neurolawl, Nighteyez, nomiss, nqrse, Orcodamus, Parameshvar, Rage, Ramen, Ramirez (Jon), Rebdull, Ridikulus0510, rockschtar, Roodie, Rusah, Samuraiwillz501, sarrge, Sarthol, Scerick, Sebstar, Seniroth, seriallos, Shakeykev, Shuck, Skeletor, Slem, Spaten, Spy, Srata, Stevi, Strozzy, Tekfire, Tevka, Theda99, Thordros, Tic[Ã ]sentence, Tobi, todd, Torsti, tsukari, Tyazrael, Ulti.DTY, Val (Valdrath), Vaxum, Vsmit, Wargus (Sh PTR = true
 targets = <table> {
 }
 auras = <table> {
 }
 TTD = <table> {
 }
 getSpecializationKey = <function> defined @Interface\AddOns\Hekili\Constants.lua:211
 keys = <table> {
 }
 frameProfile = <table> {
 }
 GetResourceKey = <function> defined @Interface\AddOns\Hekili\Constants.lua:88
 debug = <table> {
 }
 snapshots = <table> {
 }
 FrameStratas = <table> {
 }
 Tooltip = HekiliTooltip {
 }
 hotkeys = <table> {
 }
 queue = <table> {
 }
 getSpecializationID = <function> defined @Interface\AddOns\Hekili\Constants.lua:216
 ResourceRegenerates = <function> defined @Interface\AddOns\Hekili\Constants.lua:99
 GetResourceID = <function> defined @Interface\AddOns\Hekili\Constants.lua:83
 GetResourceInfo = <function> defined @Interface\AddOns\Hekili\Constants.lua:78
 UI = <table> {
 }
 cpuProfile = <table> {
 }
 formatValue = <function> defined @Interface\AddOns\Hekili\Formatting.lua:774
 lib = <table> {
 }
}
Hekili = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 IsClassic = <function> defined @Interface\AddOns\Hekili\Hekili.lua:16
 defaultModuleLibraries = <table> {
 }
 Deserialize = <function> defined @Interface\AddOns\ElvUI\Core\Libraries\Ace3\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 SaveDebugSnapshot = <function> defined @Interface\AddOns\Hekili\Hekili.lua:209
 Snapshots = <table> {
 }
 Printf = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "Hekili"
 ProfileFrame = <function> defined @Interface\AddOns\Hekili\Hekili.lua:35
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\Ac
 ```

**Comment by N6REJ** [comment]
if I disable all addons except hekili I get
```lua
Message: Interface\AddOns\Hekili\Hekili.lua:5: attempt to call global 'LibStub' (a nil value)
Time: Tue Nov  2 18:33:11 2021
Count: 1
Stack: Interface\AddOns\Hekili\Hekili.lua:5: attempt to call global 'LibStub' (a nil value)
[string "@Interface\AddOns\Hekili\Hekili.lua"]:5: in main chunk

Locals: addon = "Hekili"
ns = <table> {
}
(*temporary) = nil
(*temporary) = "AceAddon-3.0"
(*temporary) = "attempt to call global 'LibStub' (a nil value)"
```

**Comment by Hekili** [comment]
Thanks for the report.  What is the first error?

Please use Pastebin to link the full content of errors.

**Comment by Hekili** [comment]
What class/spec are you logging in with?  Does it happen with multiple classes/specs?

**Comment by Hekili** [comment]
What version of the addon are you using?

**Comment by N6REJ** [comment]
hi, let me gather information for you..
I'm on a very slow old Mac so sorry if I'm slow

**Comment by N6REJ** [comment]
lvl 50 vengeance demon hunter, in the maw.
Please notice the error changed after turning off all other addons
Original error: https://pastebin.com/QF0HB34s
Current error: https://pastebin.com/3fEekbc8
version: 9.1.5-1.0.1

Please note that the addons I had running are the normal ones I use with no issues

**Comment by Hekili** [comment]
It's possible that another addon is supplying an old/broken/modified version of LibStub, but that would be odd.  You'd have to narrow down the other addon(s) involved to be able to figure this out.

Clear out your BugSack, reload your UI, and then go back to provide the very first error in the list.  Everything else is likely a result of the first error.  Thanks.

**Comment by N6REJ** [comment]
yeah, cause when I change char I got a totally different error https://pastebin.com/bCqSk16Y
I would suspect addibags let me do some research really quick

**Comment by Hekili** [comment]
I only care about the first error.

**Comment by N6REJ** [comment]
I posted it twice.

**Comment by Hekili** [comment]
> Clear out your BugSack, reload your UI, and then go back to provide the very first error in the list. Everything else is likely a result of the first error. Thanks.

Which of the errors you provided is the first one in the sack after you've done the above?

> I would suspect addibags let me do some research really quick

I use AdiBags and am not seeing this error message.

**Comment by N6REJ** [comment]
This old man is getting confused....
The ORIGINAL error I put in the original post.
I'm installing bug sack now.

**Comment by N6REJ** [comment]
ok, went to a brand new char with brand new install of bug sack and got https://pastebin.com/WALnTxKM

**Comment by Hekili** [comment]
Error messages are show with the latest first. That's why I'm asking you to scroll back to the first one. If it's frustrating, you don't have to do anything you don't want to do. We can wait for someone else to make a report instead. Otherwise, I have to ask clarifying questions and get direct answers to the specific questions I ask. Thanks.

**Comment by N6REJ** [comment]
it's fine, I'm not trying to frustrate you. I"m on a very slow pc right now so thast hindering things

**Comment by N6REJ** [comment]
I see lots of errors when hitting "previous in bugsack. 
https://pastebin.com/QQRckv6d is the error when I keep hitting previous and get as far back as it will go.
Would it be  better if I sent you the report via game?

**Comment by N6REJ** [comment]
@Hekili did I frustrate you?

**Comment by Hekili** [comment]
> I see lots of errors when hitting "previous in bugsack.

That's why you have to clear your BugSack and then reload UI.  That way you just see the errors from when you reload, forward.

> pastebin.com/QQRckv6d is the error when I keep hitting previous and get as far back as it will go.

The only way formatKey would be unavailable at this point in time would be if there were an error earlier in the load process that prevented Utils.lua from being loaded, because Utils.lua (with formatKey in it) loads before State.lua.

Are you installing a complete Hekili package that includes all the libraries?  Do you see LibStub inside Hekili/Libs?

I'll keep looking to replicate this, but no luck so far.

**Comment by N6REJ** [comment]
Libstub is there.. but I noticed its not throwing the error now.  I'm going to see if its still an issue or not.  There has been a ton of updates from all the big players in the last 48hrs
It might be a mac only thing, which would be weird, but I'll try to research it.  My mac will be down for a few days while I await a kvm.

**Comment by Hekili** [comment]
This appears to be resolved.
