### ISSUE TITLE
Start After Global Cooldown removal causing performance issues

### ISSUE THREAD

**Issue by joshhr** [Hekili/hekili#1268]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It seems with the removal of ‘Start After Global Cooldown’ option the addon will wait 1-2 seconds before suggesting which spell to cast next. 

I reverted to an older version and it works flawlessly again. 

### How to Reproduce

1. Download the 9.1.5 release of Hekili.
2. Chose any melee spec
3. Go to a target dummy and begin following the Hekili priority. 

### Snapshot (Link)

It’s happening on all melee specs 

### Contact Information

joshhr#4384

**Comment by joshhr** [comment]
This creates very weird issues when playing a proc based spec as it takes quite a while for the priority to update causing missed/delayed procs

**Comment by Hekili** [comment]
No, that's not what Start after Global Cooldown does (or did).  If you want to submit a ticket with the required information, I'll take a look at that.
