### ISSUE TITLE
Problem showing Vampiric blood migitation BDK

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#127]
Problem showing Vampiric blood migitation BDK
Hello i cant figure to show the Vampiric blood when im low on hp defensive, only icebound shows. is it easy to fix this?

**Comment by Hekili** [comment]
You can customize your priorities in /hekili > Priorities > Blood.

Under Action Lists, look at the `mitigation` list to find the entry for Vampiric Blood.

**Comment by Tobbelainen** [comment]
Found that, so i need to put the numbers when i want Vampiric blood to appear and not to apear when im dead, Vampiric blood only says (Group 50[66), sorry fpr bad explaining but seems that im kinda retard to understand when it should show^^
