### ISSUE TITLE
[BUG] Warrior / Arms / Necrolord - "attempt to call global 'FindUnitBuffByID' "

### ISSUE THREAD

**Issue by necampanini** [Hekili/hekili#1270]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Moving from Kyrian to Necrolord, I am encountering a repeating LUA error at various times, but mainly as I leave combat.

It appears to loop giving a very high error count.

### How to Reproduce

1. Enter game as Warrior, specced into Arms and aligned with Necrolord covenant
2. Enter or leave combat

### Player Information (Link)

https://pastebin.com/KkJxLJba

### Error Messages (Link)

https://pastebin.com/r1XfgQZB

**Comment by Hekili** [comment]
Fix inc.
