### ISSUE TITLE
[SV Hunter] incorrectly recommends updating Serpent Sting

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#1271]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

My Surv Hunter incorrectly recommends updating Serpent Sting. 
The addon now recommended the following: I had a Green Shrapnel bomb and had 4 seconds left on the target until the Serpent Sting ended. The addon recommended using Serpent Sting instead of Green Shrapnel bomb. The addon should not recommend me to use Serpent Sting when there is a Green Shrapnel bomb. How I wish the addon would recommend to me in such a case. He had to offer me a Green Shrapnel bomb, thereby increasing my dps and did not use Serpent Sting. Since this is the right choice in this situation. If there is a Green Shrapnel bomb and there is little time left for the Serpent Sting on the target, we should always only use the Green Shrapnel bomb.

### How to Reproduce

Log into Sv Hunter Ventir with the Legendary Pouch of Razor Fragments
Use Serpent Sting on the target, and make a Green Shrapnel bomb during rotation and wait 1-4 seconds for the Serpent Sting to end on the target.

### Snapshot (Link)

https://pastebin.com/ya2bVZzM

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/aU3jnGgPcMMFbLwFgY77vn

**Comment by Hekili** [comment]
It's following the sim priority; if you're managing to sit at Focus cap, you're doing something else incorrect.  This is entry 10 in the `st` action list.

>  - this entry's criteria FAILS: full_recharge_time[5.26] < gcd.execute[1.10] | focus.current[100.00] + cast_regen[7.50] < focus.max[100.00] & ( next_wi_bomb.volatile[true] & dot.serpent_sting.ticking[true] & dot.serpent_sting.refreshable[true] | next_wi_bomb.pheromone[false] & ! buff.mongoose_fury.up[true] & focus.current[100.00] + cast_regen[7.50] < focus.max[100.00] - action.kill_command.cast_regen[22.00] * 3 ) | time_to_die[685.00] < 10

Specifically this part:

> focus.current[100.00] + cast_regen[7.50] < focus.max[100.00] & ( next_wi_bomb.volatile[true] & dot.serpent_sting.ticking[true] & dot.serpent_sting.refreshable[true]

If you were at 92.5 Focus or fewer, it would've recommended the Volatile Bomb instead.  Otherwise, it wants you to use something that costs Focus so that you're not wasting Focus regen.

You could try removing the `focus.current + cast_regen < focus.max &` part of that entry and you'd end up getting the behavior you want.  I have no promises that it's optimal (again, because you'll waste Focus regen).

**Comment by geraint425** [comment]
Okay, I'll try to find this line myself and fix it for myself. It's just that what you described so does not work correctly in reality. And you can take the time yourself and look at most of the logs that people are not using the Dot update

**Comment by Hekili** [comment]
> I'll try to find this line myself

> This is entry 10 in the `st` action list.
