### ISSUE TITLE
Flayed Shot (Ventyhr) not showing/not being recommended at all

### ISSUE THREAD

**Issue by AhoyThere** [Hekili/hekili#1273]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Today I changed covenants from NF to Venthyr with my Survival Hunter. And while it did show the NF ability (Wild Spirits) just fine it never ever shows Flayed Shot (Venthyr ability). I already checked the options and it's not disabled. 
Just killed The Tarrague on Mythic for example. Flayed Shot wasn't recommended, not even one. The Kill Shot (Kill Shot procs) however show up/get recommended just fine.

### How to Reproduce

No special steps needed to reproduce.

### Snapshot (Link)

n/a

### Raidbots Sim Report (Link)

n/a

### Contact Information

Thevil#5362 (Discord)

**Comment by Hekili** [comment]
Sorry, you'll need to submit a proper ticket including the required snapshot(s).

**Comment by AhoyThere** [comment]
https://pastebin.com/1UeiQwQn

Is this what you need?

**Comment by Hekili** [comment]
Yes.  You have cooldowns and covenant abilities toggled off, so Flayed Shot isn't showing.  See /hekili > Toggles.

**Comment by AhoyThere** [comment]
Oh wow, you are right... although I'm not sure how that happened.
Thank you.
