### ISSUE TITLE
Arcane mage performance issues

### ISSUE THREAD

**Issue by kuttim** [Hekili/hekili#1274]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm getting huge spikes in performance when I switch to arcane specialization on my mage (dropping to about 20-30 fps in combat) - frost specialization seems to be fine, no fps drops what so ever.

### How to Reproduce

To reproduce which I'm seeing one should be just specced into arcane and should see performance degrading like I do.

### Snapshot (Link)

https://pastebin.com/Zz7wvuhY

**Comment by Hekili** [comment]
Arcane is the only spec that's vastly more complex than Fire.  I might be able optimize it a bit, but it's not going to outperform Fire which is already pretty CPU intensive.

**Comment by kuttim** [comment]
Ah I see, thank you for clarifying, couldn't find much information under issues section regarding arcane performance issues so figured I'd open a ticket, personally didn't think arcane would be more complex than fire is, but that makes sense now, thank you!

**Comment by Hekili** [comment]
There is still room to optimize.
