### ISSUE TITLE
Earth Elemental and Healing Surge conditions

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#1276]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Good day everyone, I am playing my Shaman and was wondering if it is possible to set up a custom condition for Earth Elemental and Healing Surge to be recommended under the following conditions:
1. Earth Elemental: If I have more than 3 mobs and my health drops below 35% 
2. Earth Elemental: If I am fighting a mob single mob and my health drops below 30%. 
3. Healing Surge: If my health is below 55% and it is a free cast.
Any help would be very much appreciated.

Having these abilities set up as I have described would help a lot while in open-world questing and grinding. Of course, only if it is possible.

### How to Reproduce

1. Enter game as Enhancement Shaman
2. Go to target dummy or find mobs to fight
3. Fight mobs

### Snapshot (Link)

https://pastebin.com/TN43K3iz

**Comment by Hekili** [comment]
This would all be doable, but I don't help write custom priorities just because that requires more time than I have.

However, there's a similar guide for Feral here:  https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#how-do-i-make-the-addon-recommend-________
