### ISSUE TITLE
[BUG] Global variable 'gcd' error when using Arcane Mage Profile

### ISSUE THREAD

**Issue by LeonardoDeQuirm** [Hekili/hekili#1281]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When trying to use  the Arcane mage profile, I get continuous errors that the application is trying to do arithmetic on the 'gcd' variable. Attempting to play causes the rotation frame to constantly disappear.

### How to Reproduce

1. Enter game as Arcane Mage
2. Watch as BugSack freaks out and the game lags

### Player Information (Link)

https://pastebin.com/rbv3TvFq

### Error Messages (Link)

https://pastebin.com/VQGX0kZC

### Contact Information

LeoDeQuirm#2079

**Comment by LeonardoDeQuirm** [comment]
I believe I have fixed this myself: Line 607 in the affected module calls arithmetic on `gcd` instead of `gcd.max` as per the comment. Adjusting this has made the Lua error far less common

**Comment by Hekili** [comment]
Yup, that's the correct fix.  Will be resolved in -alpha2.
