### ISSUE TITLE
[REC] DRUID Balance recommended ability keys not recognized in moonkin form when its also on the bar in normal form

### ISSUE THREAD

**Issue by basalt51** [Hekili/hekili#1285]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

DRUID Balance recommended ability keys not recognized in moonkin form when its also on the bar in normal form. The recommended ability is recommending a key that the ability is not on when in moonkin form, but it is on that key when in a different form. 

### How to Reproduce

1. Enter game as balance druid. 
2. Put Starfire on keybind 6
3. change into moonkin form. Put Starfire on keybind R
4. Target something while in Moonkin. Hekili will recommend 6 for Starfire even though starfire is on R

### Snapshot (Link)

https://pastebin.com/jFHqinSM

**Comment by Hekili** [comment]
This is dependent on the order you put abilities on your bars.  If you changed which bars are used for which forms, the addon has no way of knowing.

You can manually set the keybinding text for anything the addon can't safely detect in /hekili > Abilities.
