### ISSUE TITLE
[BUG] Queue Direction Bug

### ISSUE THREAD

**Issue by nancikennedy** [Hekili/hekili#1289]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Queue Direction/Anchor: Left/Left OR Right/Right-> Display area is ("Icons Shown" - 1) wide and the Main spell is moved to the center of the box, obscuring what's behind it.

Any other combination and the results are as expected.

### How to Reproduce

Set Anchor and Queue direction to both be either Left or Right when spell count is greater than 1.

### Player Information (Link)

https://pastebin.com/9Cgxh2ie

### Error Messages (Link)

None

### Additional Information

I noticed it a really long time ago and just figured I was screwing something up, but I just figured out today that it is only doing it when the directions chosen match the way that I described. I have Bugsack installed, and it throwing no errors.

**Comment by Hekili** [comment]
I'm not seeing this behavior on mine.

![image](https://user-images.githubusercontent.com/9438134/142795183-b1349971-13c5-4600-bbf8-af6e216fe9a3.png)

![image](https://user-images.githubusercontent.com/9438134/142795205-19c5073a-2b91-48ab-8ab2-3f5c63a7208b.png)

Can you post screenshots of yours where this issue is happening?

**Comment by nancikennedy** [comment]
Well, that's because I am an IDIOT! It's when you set it opposite, so Left/Right OR Right/Left. /sigh

**Comment by Hekili** [comment]
Yeah, that behavior is intentionally allowed, because I assume if you do something weird like that, you have a reason to do it weird.  If you anchor something to the left side and then have it go right, the natural outcome is that there will be overlap.
