### ISSUE TITLE
Arcane Mage error upon login

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#129]
Each time I login on my Arcane Mage, I get the below error (tried it twice and got error both times)
This is using the latest update (5/14/2019)
My talents are: 2312121

Message: Interface\AddOns\Hekili\Classes\MageArcane.lua:1040: attempt to call method '?' (a nil value)
Time: Wed May 15 14:19:46 2019
Count: 1
Stack: Interface\AddOns\Hekili\Classes\MageArcane.lua:1040: attempt to call method '?' (a nil value)

Locals: 

===================
Message: Interface\AddOns\Hekili\Classes\MageArcane.lua:1040: attempt to call method '?' (a nil value)
Time: Wed May 15 15:01:04 2019
Count: 1
Stack: Interface\AddOns\Hekili\Classes\MageArcane.lua:1040: attempt to call method '?' (a nil value)

Locals:

**Comment by Hekili** [comment]
Fix going out in 8.1.5-15.
