### ISSUE TITLE
[BUG] Game Freezes at Loading Screen, Sometimes Crashes, Sometimes program stops responding

### ISSUE THREAD

**Issue by legitirl** [Hekili/hekili#1290]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have been having an issue for a few months now, I thought it was just my computer or addon compatibility. I did a fresh install of world of warcraft, and installed addons one by one until I could narrow the problem. 

When ever I hit a loading screen, it loads fast (m.2 SSD, 32GB Ram, 2080) but when the loading bar hits full, and I had Hekili enabled, the game freezes, gives me a "program not responding" message, and sometimes it will just crash the game out. 

IF the games does load into an arena or battleground. The timer will be out of sync. See video for reference. 

### How to Reproduce

1. Enter Game as any character
2. Enable Hekili (only addon installed/enabled)
3. Load into BG or arena

### Player Information (Link)

https://pastebin.com/nnFabbNs

### Error Messages (Link)

N/A

### Additional Information

Link to issue. https://www.twitch.tv/videos/1212924258

### Contact Information

Discord - Legit#8803

**Comment by Hekili** [comment]
Can you send me your Hekili.lua file from your SavedVariables?

**Comment by legitirl** [comment]
[New Compressed (zipped) Folder.zip](https://github.com/Hekili/hekili/files/7584240/New.Compressed.zipped.Folder.zip)

**Comment by Hekili** [comment]
Thanks, nothing jumped out at me immediately.

Do you know when this started for you?  If you revert the addon to earlier versions, is there a specific point at which this goes away for you?

**Comment by legitirl** [comment]
It's honestly been doing this for 6+ months, i just never knew what it was. I thought it was my PC. I upgraded some stuff, reinstalled windows, reinstalled the game. Same result. I have no clue what is going on or what caused this. 

How can I install a previous version? I will try that.

**Comment by Hekili** [comment]
They're all available -- see the Releases section here, or Files on CurseForge.

**Comment by Hekili** [comment]
You might also try removing SpellFlash from the addon to see if it makes a difference.

See Hekili/embeds.xml, remove these lines:

```
	<Script file="Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"/>
	<Script file="Libs\SpellFlashCore\Localization.lua"/>
	<Script file="Libs\SpellFlashCore\SpellFlashCore.lua"/>
```

You can do this with the game loaded and then type `/reload` to reload your UI.

**Comment by legitirl** [comment]
> You might also try removing SpellFlash from the addon to see if it makes a difference.
> 
> See Hekili/embeds.xml, remove these lines:
> 
> ```
> 	<Script file="Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"/>
> 	<Script file="Libs\SpellFlashCore\Localization.lua"/>
> 	<Script file="Libs\SpellFlashCore\SpellFlashCore.lua"/>
> ```
> 
> You can do this with the game loaded and then type `/reload` to reload your UI.

When I remove those lines the addon does not load on /reload

**Comment by Hekili** [comment]
You can also add this Warmup addon and post a screenshot of the output:

https://github.com/tomchapin/Warmup/releases/tag/v0.4.3

**Comment by Hekili** [comment]
Since you closed the ticket (I reopened), should I assume you won't be trying any of the things I recommended?

**Comment by legitirl** [comment]
I didn't mean to close it. I'm fairly new to this website here lol. 

I'm going to be trying some other things today. So far still having the same problems.

When I deleted the lines you mentioned above (shading) the addon wouldn't load. Do you know why?

**Comment by Hekili** [comment]
Probably messed up the formatting of the file.  If tabs were converted to spaces, it might not parse correctly.  I deleted those lines and loaded the addon without any issue.

**Comment by legitirl** [comment]
Can you send me your embeds file without those lines? I'll give that a go.

**Comment by legitirl** [comment]
This is when I do /reload. 
![image](https://user-images.githubusercontent.com/94859160/143043602-f88633b7-497f-45bf-b586-2c180771ea97.png)

**Comment by legitirl** [comment]
The behavior I experience is ONLY when loading in or out of an instance and it seems that warmup doesn't pick up those load times? 

I just queued for arena skirmish and the game had a big freeze/pause at the loading screen.

**Comment by Hekili** [comment]
Yeah, it's not egregious for just loading into the game.

You might try having /etrace open when you queue into a skirmish or whatever and see if there are a bunch of events firing a ton.  If there's a long gap between events in the /etrace that'd tell me what event is causing all the excess processing.

`/dump Hekili.ECount` might also be useful information (especially after zoning in and desyncing).

**Comment by Hekili** [comment]
Also, trying an old version might help narrow down when code was added that is problematic.

Try the first Shadowlands release.  If no problem, let me know.
Try the first 9.1 release.  If no problem, let me know.
Once you find the first version with a problem, you can backtrack through minor versions to figure out which release introduced the problem.

**Comment by legitirl** [comment]
> Yeah, it's not egregious for just loading into the game.
> 
> You might try having /etrace open when you queue into a skirmish or whatever and see if there are a bunch of events firing a ton. If there's a long gap between events in the /etrace that'd tell me what event is causing all the excess processing.
> 
> `/dump Hekili.ECount` might also be useful information (especially after zoning in and desyncing).

While sitting in cov hall
![image](https://user-images.githubusercontent.com/94859160/143045127-b0d7f189-0f62-4fb3-8019-de66b962c9fd.png)

**Comment by legitirl** [comment]
> 

![image](https://user-images.githubusercontent.com/94859160/143046783-7f11048d-b8d0-4d77-a187-8e3464ba3229.png)
post arena skirmish

**Comment by Hekili** [comment]
I really need that data + /etrace from right after entering the arena (but before the fight).

**Comment by legitirl** [comment]
> I really need that data + /etrace from right after entering the arena (but before the fight).

https://youtu.be/XEpZk1vNqMQ

**Comment by Hekili** [comment]
Thanks, that helps but not quiet enough, unfortunately.

Can you try `/dump Hekili:DumpProfileInfo()` before teleporting into the arena and then again immediately after teleporting in?

It'll put a *lot* of information into your chat.

**Comment by legitirl** [comment]
> 

before loading in arena
![image](https://user-images.githubusercontent.com/94859160/143060214-805d6a37-6d13-4e8c-9af4-2b71c1796487.png)

after loading in arena
![image](https://user-images.githubusercontent.com/94859160/143060283-ec5d8187-0edd-4df4-9cab-20b3ec3290ab.png)

after loading out of arena
![image](https://user-images.githubusercontent.com/94859160/143060371-c0982396-e178-4b42-a3e2-52c59eb7e052.png)

**Comment by legitirl** [comment]
looks like all of them started with "Dump: value=Hekili:DumpProfileInfo()" and ended with "empty result"

**Comment by Hekili** [comment]
Yeah, you have to have CPU profiling enabled for it to work, unfortunately.

`/run SetCVar("scriptProfile", "1")`

Reload UI.

Queue for skirmish.

When the queue pops, `/run Hekili:DumpProfileInfo()` and grab the output.

Accept the queue.

After the loading screen goes away, `/run Hekili:DumpProfileInfo()` again and grab the output.

`/run SetCVar("scriptProfile", "0")` and then `/reload` (to turn CPU profiling back off).

**Comment by legitirl** [comment]
https://youtu.be/RKcA2R1rPPY

**Comment by Hekili** [comment]
I can't tell anything in that 360p video, but screenshots that follow the instructions my last post would be good enough.

**Comment by legitirl** [comment]
> /run Hekili:DumpProfileInfo()

before hitting loading screen 
![image](https://user-images.githubusercontent.com/94859160/143067260-1b229d8f-855b-4b92-8f6e-6f8cb582d4b5.png)

post-loading screen (it does it on zone changes, i.e. hearth stone, accepting summons, etc also)
![image](https://user-images.githubusercontent.com/94859160/143067419-aea9f679-efc4-4913-979f-f6d871d24a25.png)

**Comment by Hekili** [comment]
Thanks.  Can you try grabbing the latest alpha version and posting the same information again?  (You can revert back to 1.0.3 after.)

It does look like something is triggering a lot of resetting during the loading screen, which is pointless.

**Comment by legitirl** [comment]
> Thanks. Can you try grabbing the latest alpha version and posting the same information again? (You can revert back to 1.0.3 after.)
> 
> It does look like something is triggering a lot of resetting during the loading screen, which is pointless.

maybe I'm newb.  

I go here:
https://github.com/Hekili/hekili/tree/v9.1.5-1.0.4-alpha

I click on Code Dropdown, click download ZIP.

I copy contents into Hekili folder. 

/reload

Hekili shows in addon menu but does not load. (I had this same issue when trying to pull in previous versions). 

Am I doing something wrong?

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/releases/download/v9.1.5-1.0.4-alpha5/Hekili-v9.1.5-1.0.4-alpha5.zip

**Comment by legitirl** [comment]
Seems the alpha fixed it! 

https://youtu.be/5iRzQBOl1QU

**Comment by legitirl** [comment]
> https://github.com/Hekili/hekili/releases/download/v9.1.5-1.0.4-alpha5/Hekili-v9.1.5-1.0.4-alpha5.zip

how would i get to this file for future reference? Seems I took the wrong path.

**Comment by Hekili** [comment]
Under Assets, it's the first link.  It is the "packaged" version that includes libraries.  The source code alone does not include libraries.

There are likely other issues with -alpha5 (and -alpha4), so I would suggest trying -alpha3 for now.

**Comment by legitirl** [comment]
I will give those a shot when I get back to my computer. Thank you so much.

**Comment by Hekili** [comment]
Closing this as resolved in the alpha branch.
