### ISSUE TITLE
[REC] Balance suggest before cd:s

### ISSUE THREAD

**Issue by noiseuu** [Hekili/hekili#1291]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

So, correct rotation going but after 2x wraths and starfire it suggest still starfire like 2-3seconds before dots, i cant is this bug or something but u can play away from it. It happend when i updated newest hekili. But without that rotation works fine.

### How to Reproduce

1. Enter game as balance druid
2. blast dummy

### Snapshot (Link)

https://pastebin.com/PSKt1H2R

**Comment by noiseuu** [comment]
https://gyazo.com/a16d7ed6beab960bbeaa19448e840b3c

like doing this

**Comment by kuttim** [comment]
Why did you close this? Did you find a fix?

**Comment by Hekili** [comment]
Because it's an alpha build and it's a known side effect of something else I'm working on.
