### ISSUE TITLE
All Class/Specs - Buff skills/trinkets being high in priority even when they have 50+ mins left

### ISSUE THREAD

**Issue by Dreamin93** [Hekili/hekili#1292]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For version 9.1.5-1.0.4-alpha4

I'm having an issue on multiple specs where the game asks me to recast buff abilities, even when they are still on - for example:
Warrior - Asks me to continously apply battleshout
Mage - Asks me to reapply Arcane Intellect
Enh Shaman - Wants me to keep putting down Windfury totem even when its already down (I can't get this one to happen again, it happened when I was killing the world boss but I feel like it might be linked to the others)

All class - Asks me to reapply Flayedwing Toxin trinket.

Another weird issue I've noticed:
Druid - When I stealth, all of the upcoming abilities it asks me to press is stealth 

### How to Reproduce

1. Log onto class (Mage or Warrior or class with trinket)
2. Use Battleshout/Arcane Intellect
3. Hekili will recommend reapplying

### Snapshot (Link)

https://pastebin.com/jcNUnXQ6

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wjtp2jjtkqCCAUALmVz7PA

**Comment by Hekili** [comment]
Thanks for alpha testing.  I appreciate the report.  Please revert to the previous alpha (or to the previous full release) while I investigate.

**Comment by Hekili** [comment]
1.0.4-alpha5 looks like it fixes this.  Maybe.  Let me know.  Thanks!
