### ISSUE TITLE
[BUG] Keybinds are wrong

### ISSUE THREAD

**Issue by xdLhx** [Hekili/hekili#1293]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

THe Kebinds are all wrong
![image](https://user-images.githubusercontent.com/95081204/143573547-af8b31dc-a40d-4db4-b03a-d12e932c2b57.png)

### How to Reproduce

1. Enter the game as Ret Paladin
2. Open Hekili 
3. Go to Displays - Primary - Keybinds and make sure Enabled is checked
4. Keybinds are wrong

### Player Information (Link)

https://pastebin.com/4KqR6VTH

### Error Messages (Link)

https://pastebin.com/4KqR6VTH

### Contact Information

Alex_RiSA#7038

**Comment by xdLhx** [comment]
Looks like a bartender issues. Sorry, you can close it down

**Comment by Hekili** [comment]
Not precisely a Bartender issue, but maybe how the addon reads from Bartender.  There's a fair amount that is dependent on the order you load abilities into your bars, unfortunately.  You can manually set what keybinding you want to see in /hekili > Abilities (or Gear and Trinkets, if it's an item).
