### ISSUE TITLE
game freezes crashes on raid

### ISSUE THREAD

**Issue by rogal223** [Hekili/hekili#1294]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello, I have a problem like going to a raid while fighting the nine boss, soulrender or possibly more monsters, the game just stutters goes down to the 0 game I have the add-on turned on

### How to Reproduce

Enter Game as any character
Enable Hekili (only addon installed/enabled)
only in raids

### Player Information (Link)

build: v9.1.5-1.0.3 level: 60 (60) class: WARRIOR spec: fury  talents: anger_management     bladestorm     cruelty     fresh_meat     massacre     storm_bolt     warpaint  pvptalents: none  covenant: kyrian  conduits: ashen_juggernaut = 6    depths_of_insanity = 9    fueled_by_violence = 10    indelible_victory = 3    piercing_verdict = 3    safeguard = 10  soulbinds: [forgelite_prime_mikanikos]    brons_call_to_action = 1    effusive_anima_accelerator = 1    forgelite_filter = 1    resilient_plumage = 1    soulglow_spectrometer = 1    soulsteel_clamps = 1  sets: grim_codex = 1  gear: ancient_colossus_chassis = 1     cloak_of_scarred_honor = 1     distorted_constructs_gauntlets = 1     drustlords_greataxe = 1     entwined_gorger_tendril = 1     essence_extractor = 1     fused_bone_greatbelt = 1     grim_codex = 1     muckwallow_stompers = 1     plague_handlers_greathelm = 1     rimebinders_runeblade = 1     shadowghast_greaves = 1     steelcore_shoulders = 1     stitchfleshs_misplaced_signet = 1     stonewrought_armplates = 1     trailspinner_pendant = 1  legendaries: elysian_might = 1  itemIDs: 171416, 178707, 178713, 178734, 178736, 178773, 178774, 178780, 178811, 178848, 180104, 181203, 181334, 181672, 186289, 186347  settings: aoe = 2     buffPadding = 0     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 8     nameplates = true     package = Fury     petbased = false     potion = potion_of_phantom_fire     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false     check_ww_range = false     heroic_charge = false  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true      essences = true      interrupts = true      mode = automatic      potions = false 

### Error Messages (Link)

no error pops up in game

### Additional Information

I have the following specifications
Intel i9-10850k
rtx 2070 super
16 gb ddr4 3600 mhz
m2 ssd

### Contact Information

Rogal#9461

**Comment by Hekili** [comment]
Sorry, you'll need to follow ticket instructions to supply information that allows me to investigate.
