### ISSUE TITLE
[BUG] game freezes crashes on raid

### ISSUE THREAD

**Issue by rogal223** [Hekili/hekili#1295]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello, I have a problem like going to a raid while fighting the nine boss, soulrender or possibly more monsters, the game just stutters goes down to the 0 game I have the add-on turned on

### How to Reproduce

Enter Game as any character
auto spec change hekili
only in raids

### Player Information (Link)

https://pastebin.com/kHBSP2cP

### Error Messages (Link)

n/a

### Additional Information

I have the following specifications
Intel i9-10850k
rtx 2070 super
16 gb ddr4 3600 mhz
m2 ssd

### Contact Information

Rogal#9461

**Comment by Hekili** [comment]
> Hello, I have a problem like going to a raid while fighting the nine boss, soulrender or possibly more monsters, the game just stutters goes down to the 0 game I have the add-on turned on

What does this mean?

> auto spec change hekili

What does this mean?

**Comment by rogal223** [comment]
What character would I not play when I go to a raid and I have the hekili on, which requires a fight with more monsters, the game crashes I do not know why this is happening. The hardware in the computer is not weak. You once wrote to me that the problem is on the processor side when I had amd but now I have i9 and this is the same problem.

**Comment by rogal223** [comment]
auto spec I mean that I just automatically uploaded the rotation settings by the program, I do not change anything there, one that adds just 5 skills forward to show me

**Comment by Hekili** [comment]
I honestly don't understand what you are saying.  It would help if you could describe the actual steps you are taking -- don't summarize.

1.  Start with fresh Hekili install.
2.  Log into X.
3.  Go to raid.
4.  Do Y or Z.
5.  Describe the problem that happens.

If I can't get specific step-by-step instructions for replicating, I won't be able to investigate this for you.

**Comment by Hekili** [comment]
> auto spec I mean that I just automatically uploaded the rotation settings by the program, I do not change anything there, one that adds just 5 skills forward to show me

I do not understand what this means.  You uploaded/imported something?  You didn't upload/import something?  You changed the display to show 5 skills?  I'm sorry that I cannot follow what you're saying.

**Comment by SpatenLa** [comment]
do you have the addons bugsack and buggrabber installed?

**Comment by rogal223** [comment]
i got instaled adibags

**Comment by rogal223** [comment]
![image](https://user-images.githubusercontent.com/66420209/143921149-6a6cf684-a9e6-41e1-83cb-9f109a0915a1.png)

**Comment by SpatenLa** [comment]
but its about the two addons "bugsack" and "buggrabber"

**Comment by rogal223** [comment]
I don't have this or that installed

**Comment by rogal223** [comment]
![image](https://user-images.githubusercontent.com/66420209/143921415-9d4584d7-f6a4-4575-99ba-c2549a6323eb.png)
this is all addons what i have instaled

**Comment by SpatenLa** [comment]
without those two addons you cant really say that you dont have errors, which are very very very important to know about potential issues and how to fix it.

**Comment by rogal223** [comment]
ok im installed it now

**Comment by SpatenLa** [comment]
now you look out for the red sack on your minimap
