### ISSUE TITLE
[REC] WW Monk Recommendation Issue

### ISSUE THREAD

**Issue by thomasbrezina** [Hekili/hekili#1297]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

for some reason the addon recommends odd thigns while in BDB on WW monk. It recommends Chi Burst during the window which is a 1 sec cast instead of spamming SCK!

### How to Reproduce

1. Enter the Game as a WW Monk
2. Walk to Training Dummies
3. Attack and follow instructions
4. Use BDB and see what it recommends

### Snapshot (Link)

https://pastebin.com/yczSMVAj

### Additional Information

https://prnt.sc/214z1o0 Screenshot of BDB on CD and Applied to all four targets.

### Contact Information

ThomasBrezina#6159

**Comment by Hekili** [comment]
Thanks.

Is your user interface setup to show spell IDs in tooltips?  I'm curious about what spell ID is shown for Bonedust Brew on yourself and Bonedust Brew on your target.

**Comment by thomasbrezina** [comment]
yes, let me quickly check.

BDB ID on Target: 325216
BDB ID on Toolbar: 325216

**Comment by thomasbrezina** [comment]
and thank you for your great work. you are the best.

**Comment by Hekili** [comment]
Does your UI show who caused it?  I.e., does it confirm that it's your BDB?  I'm relying on the regular WoW API, with no special tricks, so I don't see any specific reason Bonedust Brew wouldn't work via normal detection.

**Comment by thomasbrezina** [comment]
Yes. It is mine. I am the only person there + the debuffs only show my own!

**Comment by Hekili** [comment]
To be clear, I'm not asking whether you know it is yours.  I'm saying, does your UI show you who cast a buff, and when you look at your target (while this issue is happening), does it show that debuff belongs to you?

**Comment by thomasbrezina** [comment]
oh. no, it prolly does not. it doesn't say whos it is i think but i will check again. can i turn this on somehow? does it have to be on?

**Comment by Hekili** [comment]
It depends on your UI and people normally don't see it.  I'll do some experimenting on my own.

**Comment by thomasbrezina** [comment]
So basically it reads my screen? so if I can manage to make the UI show whos buff it is - it will be fixed?

**Comment by Hekili** [comment]
No, you're misunderstanding me.  Don't worry about it.  You can't see the info I need, so I'll do my own testing.

**Comment by thomasbrezina** [comment]
ok! i hope it can be fixed cuz i am pushing fairly high keys and I rely very heavily on the addon (i know i shouldnt haha) and for some reason i try to burst amidst a massive group and all of a sudden it says cast "Chi Burst" or even worse "Fleshcraft"

**Comment by Hekili** [comment]
The snapshot you provided is not from the same time that you had the issue with Bonedust Brew.

![image](https://user-images.githubusercontent.com/9438134/144129380-b9480666-14ff-45b0-b38d-1ef987ba9dbf.png)

This shows the cooldown of Bonedust Brew has 36.37 seconds remaining, which means you cast BDB 23.63 seconds ago.  The buff/debuff would not be on the target after that much time.

The snapshot has to be taken at the exact time you're having an issue.  It is the log of one set of recommendations, not historical data.

**Comment by thomasbrezina** [comment]
it was taken 1 second before. I am 100% sure I can even have a video made or stream on discord! something is off!

**Comment by Hekili** [comment]
You might've made multiple selections and submitted the wrong one.  But the snapshot you submitted doesn't match your screenshot, either.

**Comment by thomasbrezina** [comment]
sec lemme try and i send both others

**Comment by thomasbrezina** [comment]
https://pastebin.com/2hZXvxmi

https://pastebin.com/9BMxef92

**Comment by Hekili** [comment]
In pastebin.com/2hZXvxmi, you don't have a target.

In pastebin.com/9BMxef92, you have Bonedust Brew applied (and it is detected), but the AOE action list (3+ targets) doesn't check for Bonedust Brew when deciding whether to use Chi Burst.

I'll check to the sim behavior about that last part.

**Comment by thomasbrezina** [comment]
yea then its the second one! i sometimes had it use Fleshcraft during BDB window

**Comment by Hekili** [comment]
> yea then its the second one! i sometimes had it use Fleshcraft during BDB window

You'd need to provide a snapshot of that actually happening.  It could be that you weren't targeting anything, which means your non-existent target doesn't have BDB, which means Fleshcraft is allowed.

**Comment by thomasbrezina** [comment]
yea dont worry about it i just wanted to mention it

**Comment by Hekili** [comment]
So yeah, I can confirm that the simc profile would use Chi Burst during BDB in AOE scenarios.

![image](https://user-images.githubusercontent.com/9438134/144132113-d639ccbb-7a47-4e0c-b4e8-5b502286614b.png)

I ran a sim to compare holding Chi Burst during BDB and it's a minor DPS loss to hold it back.  It's worth noting that the template sim character for Necrolord doesn't take Chi Burst.

![image](https://user-images.githubusercontent.com/9438134/144132621-88450cdd-a41e-4485-a271-9b2d7d2da367.png)

**Comment by thomasbrezina** [comment]
ok so i just follow the advice? and does it differ between 2 or 10 targets?

**Comment by Hekili** [comment]
I can make adjustments to make the addon more resilient to target swapping and such, to *probably* avoid the issue of casting Fleshcraft during BDB like you described.

And no, the AOE action list for Windwalker is used at 3+ targets.

Within that list, the only condition for Chi Burst is that it won't overcap Chi.

Beyond that, you could create a custom priority and add additional conditions there, if you want.  I don't provide active support for that, but something like the following should work:

`chi.max - chi >= 2 & buff.bonedust_brew.down & debuff.bonedust_brew_debuff.down`

That would mean (1) it doesn't overcap Chi and (2) the BDB buff isn't on your character and (3) the BDB debuff isn't on your target.

The relevant place (for Chi Burst, anyway) would be here:

![image](https://user-images.githubusercontent.com/9438134/144134018-261d267d-70a6-4764-a9c1-3d7e9bfa8dcc.png)

The wiki/FAQ covers making your own copy of the priority before making your edits.

**Comment by thomasbrezina** [comment]
![grafik](https://user-images.githubusercontent.com/89210110/144134437-d041e561-676a-4ab8-b2be-73921ee08823.png)

this might also explain why the aoe rotation isnt 100% correct!

**Comment by thomasbrezina** [comment]
oh thanks man! appreciate it!

**Comment by thomasbrezina** [comment]
![grafik](https://user-images.githubusercontent.com/89210110/144134915-1c43de1b-1b10-4db8-9444-a791628d6810.png)

**Comment by Hekili** [comment]
Yeah, that happens occasionally.  This has happened for other specs at times.  I don't rewrite sim priorities entirely unless I have tons of time for testing alternatives.

The WW priority isn't especially complex, IMO, so I'm not sure what's missing from the priority.  But if they update SimC, I'll update the addon to match.
