### ISSUE TITLE
Hunter/Marksmanship trinkets are not recommended in Fixed dual display mode

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1299]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Trinkets are not recommended in Fixed dual display mode for Primary Display. They display fine for AOE. Not once for Primary.

### How to Reproduce

1. Enter the game as a MarksmanShip Hunter
2. Wear trinket(s) which have Use ability
3. Setup on Hekili Fixed Dual Display and Display 3 icons (The number is not important I believe)
4. You will see trinkets in the AOE display only

### Snapshot (Link)

https://pastebin.com/PXziUyAT

### Contact Information

Markô#2877

**Comment by marekCs** [comment]
Okay, now my Primary trinket is showing up. But I think I've figured out where the error is. Trinket wasn't showing up in the phase when I hadn't gotten covenant abilities yet, I didn't have any. (and it was only showing for AOE) so there must be a condition somewhere in Primary that the char has covenant ability. After I got covenant ability (Wild Spirits) the trinket suddenly started showing up correctly.

**Comment by Hekili** [comment]
Yeah, sim priorities are generally built assuming you have all of the current expansions core features.  Not really a bug, but the Marksmanship priority could be adjusted to use Trueshot regardless of Covenant (which would then allow trinket usage, based on how the priority is written).
