### ISSUE TITLE
[REC] Soothe isn't being recommended for enrage effects

### ISSUE THREAD

**Issue by izomiac** [Hekili/hekili#1302]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Soothe should be recommended as an interrupt for enrage type effects on the target, but I can't recall ever seeing it recommended in any druid spec on any target.  I tried adding it to my utility/interrupt list but it still isn't recommended.

### How to Reproduce

The Bloodtusk Alphas slightly East of the Arena in Maldraxxus have an enrage effect they use frequently, which can be dispelled with Soothe.

### Snapshot (Link)

https://pastebin.com/NPe9U2qd

### Additional Information

Dispelling might be out of scope, since there are so many NPC abilities and [six types](https://wowpedia.fandom.com/wiki/Dispel) of dispellable buffs/debuffs.  OTOH, this is an area where a lot of players could improve, since it's an easily forgotten ability.

**Comment by Hekili** [comment]
Correct, Soothe is not in the Guardian priority.

> I tried adding it to my utility/interrupt list but it still isn't recommended.

Where'd you do that?  I don't see Soothe in your snapshot.  Guardian doesn't have a utility/interrupt list.

**Comment by izomiac** [comment]
> Correct, Soothe is not in the Guardian priority.

Am I mistaken in it's absence in Feral and Balance as well, or is it just not recommended to ever use it?  I try it if the mob flashes red... sometimes it works, sometimes it doesn't, and I have no idea when I'm just wasting my time.

> Where'd you do that? I don't see Soothe in your snapshot. Guardian doesn't have a utility/interrupt list.

[Under toggles](https://imgur.com/VfQxaCK), I like to keep everything separated.

**Comment by Hekili** [comment]
That just makes it controlled via that toggle; that does not add it to the spec's priority. See the FAQ here on GitHub for details on editing a priority. 

> Am I mistaken in it's absence in Feral and Balance as well, or is it just not recommended to ever use it?

It's a GCD not spent on DPS so it's not in the default priorities.

**Comment by izomiac** [comment]
Fair enough

**Comment by purplemooni** [comment]
as a balance druid, I have enabled to see Soothe in the Utility/Interrupts category but I never see it displayed. so when I'm attacking a mob that has an enrage the soothe button doesn't show up.

**Comment by Hekili** [comment]
Being controlled by a toggle only means that, when the toggle is activated, a priority that includes the ability can treat that ability as usable.  If the priority doesn't include Soothe, toggling it on will do nothing.

You'd need a custom priority that includes Soothe -or- to persuade me to add it.  Which I'm undecided on at this point.

**Comment by purplemooni** [comment]
sometimes its nice have a Soothe alert in a M+ setting. I'm still struggling with the settings. I made it a custom priority but still not showing for some reason

**Comment by purplemooni** [comment]
on my hunter the Tranq shot shows up perfectly fine which is the same as what a soothe does.

sometimes its nice to have a Soothe alert in a M+ dungeon. I'm still struggling with these settings. I made it a custom priority but still not showing for some reason.

**Comment by purplemooni** [comment]
on my hunter the Tranq shot shows up perfectly fine which is the same as
what a soothe does.

sometimes its nice to have a Soothe alert in a M+ dungeon. I'm still
struggling with these settings. I made it a custom priority but still not
showing for some reason. if you could help me make this a little less
complicated, I'd appreciate it!

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#how-do-i-make-the-addon-recommend-________
