### ISSUE TITLE
Ret/Feral/maybe others Gladiators Badge of Ferocity 

### ISSUE THREAD

**Issue by TelleThomas** [Hekili/hekili#1303]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using Unchained Gladiator's Badge of Ferocity on retribution paladin and Feral druid the addon will continue to reccomend its usage through entire cooldown of the trinket. This happens when using double on use trinkets, i have not tested with single on use trinket
![image](https://user-images.githubusercontent.com/73715967/145266369-85e066d7-364a-4bbc-93f3-9f338c15572c.png)

### How to Reproduce

Ret Paladin
equipped unchained Gladiators Badge of Ferocity
used in primary/aoe rotations
cooldowns/covenants enabled
continue rotation.
addon will continue to reccomend usage of unchained Gladiators Badge of Ferocity

### Snapshot (Link)

https://pastebin.com/YH8huZxi

### Contact Information

TelleThomas#1742

**Comment by Hekili** [comment]
Please update to the latest release and provide an updated snapshot. Thank you!

**Comment by TelleThomas** [comment]
sorry, reverted to try and fix it will do.

**Comment by TelleThomas** [comment]
updated pastebin

https://pastebin.com/YH8huZxi

**Comment by Hekili** [comment]
When you took the snapshot, was your badge on CD or not?

**Comment by TelleThomas** [comment]
it was on CD, it continues in 1st priority through normal usage even if i use the other on use trinket while badge is still on CD

**Comment by TelleThomas** [comment]
![image](https://user-images.githubusercontent.com/73715967/145266835-ad5c47eb-dc67-463e-bb4c-e38bdb16db39.png)

**Comment by TelleThomas** [comment]
and with both on CD for context

![image](https://user-images.githubusercontent.com/73715967/145267084-95d1aa66-5a42-4502-928c-5355b3e8e9dc.png)

**Comment by QuiteGoneJin** [comment]
Came to report this also. Not happy others are going through this but happy its not just me all the same. Was really messing me up in mage tower. Edit, on my MM hunter.

**Comment by TelleThomas** [comment]
i've tested alphas back to reintalling to first alpha 1.0.4 and the issue persists. reinstalling to 1.0.3 does seem to fix the issue on my end.

**Comment by QuiteGoneJin** [comment]
How does one reinstall to a diff ver, i use wowup if that makes a diff.

**Comment by dglynch** [comment]
I encountered the same thing today. Here is my snapshot: https://pastebin.com/HuLjGbM2

**Comment by Hekili** [comment]
Thanks, I'm testing a fix right now.

**Comment by TelleThomas** [comment]
Thank you! you're a champ dude!

**Comment by Hekili** [comment]
I posted a release (1.0.5) just now -- please test and confirm that it's working as expected for you.  I don't have the trinket so I had to fudge something for testing purposes.

**Comment by TelleThomas** [comment]
unfortunately no same

**Comment by Hekili** [comment]
Post new snapshots.

**Comment by TelleThomas** [comment]
no idea if it could be related or not but its also not selectable in gear and trinkets menu either. will recreate and post new snapshot momentarily

![image](https://user-images.githubusercontent.com/73715967/145306583-2d69b5f8-af32-4a7d-8d8c-0b372e195257.png)

**Comment by TelleThomas** [comment]
https://pastebin.com/yea5LEqu

**Comment by Hekili** [comment]
That snapshot says you still have version 1.0.4.

**Comment by TelleThomas** [comment]
pffft hit update and reloaded but it failed. 1.0.5 appears to have solved the issue. huzzah

**Comment by dglynch** [comment]
Confirmed that 1.0.5 is working for me as well.

**Comment by QuiteGoneJin** [comment]
Ditto, ty for the fast work, have a great day.

**Comment by Hekili** [comment]
Thank you!

**Comment by QuiteGoneJin** [comment]
Hey, might not be completely fixed, for some reason the hotkey isnt showing for badges, otherwise working as intended,
