### ISSUE TITLE
Overlay wont load

### ISSUE THREAD

**Issue by ArwenEven** [Hekili/hekili#1304]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![image](https://user-images.githubusercontent.com/95827913/145291470-07773a99-64d4-4045-8c87-1e3c29f6ce86.png)

Overlay for spells wont load, this is the message I keep getting.
Message: Interface\AddOns\BittensSpellFlash_DK\src\Spells.lua:41: table index is nil
Time: Wed Dec  8 21:53:39 2021
Count: 1
Stack: Interface\AddOns\BittensSpellFlash_DK\src\Spells.lua:41: table index is nil
[string "=[C]"]: ?
[string "@Interface\AddOns\BittensSpellFlash_DK\src\Spells.lua"]:41: in function `SetCost'
[string "@Interface\AddOns\BittensSpellFlash_DK\src\Spells.lua"]:45: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\SpellFlash\SpellFlash.lua"]:545: in function <Interface\AddOns\SpellFlash\SpellFlash.lua:525>
[string "@Interface\AddOns\SpellFlash\SpellFlash.lua"]:1152: in function `Function'
[string "@Interface\AddOns\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"]:35: in function `OnUpdate'
[string "@Interface\AddOns\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"]:19: in function <...dOns\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua:19>

### How to Reproduce

Enter game as Unholy Death Knight.
Try to attack anything.

### Player Information (Link)

build: v9.1.5-1.0.4 level: 60 (60) class: DEATHKNIGHT spec: unholy  talents: army_of_the_damned     clawing_shadows     deaths_reach     soul_reaper     unholy_blight     unholy_pact     wraith_walk  pvptalents: none  covenant: necrolord  conduits: adaptive_armor_fragment = 10    condensed_anima_sphere = 10    embrace_death = 9    eternal_hunger = 10    fleeting_wind = 10    reinforced_shell = 9  soulbinds: [plague_deviser_marileth]    kevins_oozeling = 1    oozs_frictionless_coating = 1    plagueborn_cleansing_slime = 1    ultimate_form = 1    undulating_maneuvers = 1    volatile_solvent = 1  sets: inscrutable_quantum_device = 1  gear: airborne_abductors_vambraces = 1     ancient_colossus_chassis = 1     cavalier_oathbreakers_grasps = 1     champions_gruesome_greaves = 1     grimveiled_cape = 1     inscrutable_quantum_device = 1     legplates_of_unholy_frenzy = 1     phial_of_putrefaction = 1     ruinous_warchiefs_shoulderguards = 1     signet_of_the_false_accuser = 1     sin_stained_pendant = 1     sworn_oath_of_the_nine = 1     valorous_visage_of_krexus = 1     waistguard_of_expurged_anguish = 1     zinkhas_blade_of_the_fallen_god = 1  legendaries: deadliest_coil = 1  itemIDs: 173242, 178739, 178771, 178824, 178827, 178842, 179330, 179350, 186290, 186311, 186314, 186316, 186318, 186347, 186350  settings: aoe = 2     buffPadding = 0     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycleDebuff = festering_wound     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = true     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 8     nameplates = true     package = Unholy     petbased = false     potion = potion_of_spectral_strength     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false  toggles: cooldowns = false     custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false 

### Error Messages (Link)

![image](https://user-images.githubusercontent.com/95827913/145291470-07773a99-64d4-4045-8c87-1e3c29f6ce86.png)

**Comment by Hekili** [comment]
That error is from Bittens' SpellFlash DK / SpellFlash / SpellFlashCore.

**Comment by ArwenEven** [comment]
so do i need to go and find a forum for that ? I thought this was part of spellflash?

**Comment by Hekili** [comment]
This is not part of SpellFlash.
