### ISSUE TITLE
Hekili flickers, doesn't show or doesn't react

### ISSUE THREAD

**Issue by PaigePB0** [Hekili/hekili#1305]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

These are what I've seen..

- on game load, hekili doesn't show
- if I toggle between auto and reactive I can get it to show
- if I prowl, the initial 

https://user-images.githubusercontent.com/95829888/145308858-e2cd9479-d3f9-4687-b309-fefc075983bf.mp4

prowl icon stays but flickers
- if I engage combat the options do not change

I added a short video which shows (briefly) prowl flickering and the hekili bar not changing options during a fight.

### How to Reproduce

I'm not really sure how to reproduce... but two things changed so it might be related to one of them

1. I started experimenting with a new weapon - Jotungeirr
2. I updated hekili to the lastest version

### Player Information (Link)

https://paste-bin.xyz/21746

### Error Messages (Link)

https://paste-bin.xyz/21746

### Additional Information

The error message link is required but I'm not seeing any lua (script) errors nor did BugSack catch any

**Comment by Hekili** [comment]
For recommendations issues, I need a snapshot.  Pause (SHIFT-ALT-P) when it's being difficult, then /hekili > Snapshots, select the display and snapshot #, copy and paste to Pastebin, and provide the link here.

**Comment by PaigePB0** [comment]
@Hekili, does this do what you need? this was taken during the fight when the addon was visible but stuck and not making new recommendations though I was in the midst of fighting

https://paste-bin.xyz/21768

**Comment by Hekili** [comment]
Not really -- it shows that it made four recommendations.  So I'm not sure why it would not be working.  Are there actual in-game error messages (the original ticket instructions talk about using BugSack and BugGrabber to retrieve error messages).

**Comment by Hekili** [comment]
Can you switch to the latest version of the addon and update me?

If that doesn't fix it, go back to 1.0.4 and then go to /hekili > Priorities > Feral, and click the circle arrow next to Priority Name.  Click Accept.  Let me know if that fixes it for you.

![image](https://user-images.githubusercontent.com/9438134/145312403-ded1ceb8-1c2a-446d-9581-dc1e93377482.png)

**Comment by PaigePB0** [comment]
Oddly no. I went looking for errors, even using /console scriptErrors 1 and didn't see any.

Following your instructions above now.

**Comment by Hekili** [comment]
This seems to have something to do with reactive mode, specifically.  I'll keep investigating.

**Comment by PaigePB0** [comment]
@Hekili thank you. It fixed, but in an odd way.  This is what I did.

- I upgraded to the latest (didn't fix)
- downgraded to 1.0.4 - though didn't yet click the circle arrow (didn't fix)
- swapped out to my old weapon (Devo's poleaxe) and took some swing, (started working)
- swapped back to the new weapon - Jotungeirr (continued to work)
- reloaded a couple of times switching back and forth weapons (continued to work)
- reinstalled the latest  (still works)

I don't know the code base nor wow's api, so this is a raw guess - but maybe the weapon's signifier (or its equivalent) got corrupted on wow's side?

But the good news is that the temporary weapon swap seemed to fix it.

Thank you for your time this late in the evening!  I'll let you know if it comes back and one of these steps doesn't solve it.

**Comment by Hekili** [comment]
I think I have it fixed in https://github.com/Hekili/hekili/releases/download/v9.1.5-1.0.6-alpha2/Hekili-v9.1.5-1.0.6-alpha2.zip -- I think it's a matter of being in Reactive mode and having the AOE display luck into refreshing itself infinitely and not letting Primary update.

**Comment by PaigePB0** [comment]
Excellent! thank you!

**Comment by PaigePB0** [comment]
I downloaded the alpha in time for raid. It is working very well and quickly. ty
