### ISSUE TITLE
Sub rogue disappearing priority during combat

### ISSUE THREAD

**Issue by jpnow** [Hekili/hekili#1306]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using hekili fuq sub rogue venthy. While doing rotation it randomly starts disappearing priority icons 1 by 1 until nothing is visible anymore, then they randomly come back.

Also when allow vanish when solo is ticked off it still shows it in the rotation

### How to Reproduce

Enter as sub rogue venthyr 
play rotation

### Snapshot (Link)

https://pastebin.com/dxDQkkzR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kNawusBrH5kGop7RJ1pExp

**Comment by Hekili** [comment]
Please try https://github.com/Hekili/hekili/releases/download/v9.1.5-1.0.6-alpha1/Hekili-v9.1.5-1.0.6-alpha1.zip and let me know if that fixes it.

**Comment by Hekili** [comment]
I'm posting 1.0.6 as a release.  So, hopefully it works for you.  If not, let me know.

**Comment by jpnow** [comment]
Will try after work and will keep you posted

**Comment by jpnow** [comment]
Looks back to normal, had one instants and re adjusted immediately thank you

**Comment by Hekili** [comment]
Any time this happens (when no recommendations can be made), the addon should automatically create a snapshot.

If that has happened, please go to /hekili > Snapshots, select Primary (or whichever display) and the snapshot # (there's probably just 1).  Copy and paste to Pastebin and submit the link so I can review.

**Comment by jpnow** [comment]
Below a snapshot while it failed to find recommendations 

https://pastebin.com/9tYz2pWL

**Comment by Hekili** [comment]
Thanks, I'll investigate it.

One thing to note, especially for Sub, 5 recommendations in the future is a lot of wasted CPU time.  It's probably very rare that recommendation 5 is correct by the time we get there (due to procs, crits, etc.).  The addon predicts the predictable stuff but there's so much RNG that you'd probably be better off just reducing to 2 or 3 icons.

I used to default the addon to 4, but with the amount of RNG in-game, I shifted the default to 3 because that's what ends up being mostly stable for most specs.

**Comment by Hekili** [comment]
You may need to enable Enhanced Recheck for Subtlety to address this issue.

Enhanced Recheck basically tries to forecast when action list criteria will change.  So at the time of that failure, you were in some kind of stealth (`stealthed.all` = `true`).  That blocked certain actions from being considered.  Enhanced Recheck would have the addon check these other items when you fall out of stealth.

Maybe.

**Comment by jpnow** [comment]
tried the enhanced recheck error still persists.  You mentioned being in stealth, not sure its related while doing some testing it looks as the shadow dance buff is gonna drop recommendations start disappearing. Below screenshot of shadow dance buff dropping and recommendations showing 1 instead of 3

https://snipboard.io/xaGeI3.jpg

**Comment by Hekili** [comment]
Yeah, that may or may not be solved with Enhanced Recheck in your Subtlety settings.

**Comment by jpnow** [comment]
even with enhanced recheck didnt work

**Comment by Hekili** [comment]
Post a snapshot with Enhanced Recheck then.  Thanks!

**Comment by Hekili** [comment]
(NOT a screenshot.)

**Comment by jpnow** [comment]
https://pastebin.com/EuJPYZjj snapshot with enhanced recheck

**Comment by Hekili** [comment]
Thanks, this helps.  I'm right about the problem formulation, but apparently Enhanced Recheck needs some additions to it.
