### ISSUE TITLE
Gladiator badge issue persists, doesn't show keybind

### ISSUE THREAD

**Issue by QuiteGoneJin** [Hekili/hekili#1307]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

keybind in suggestion list missing. previous issue of badge being suggested while on cd is fixed, updated, reloaded, etc. Same for all characters (checked 3)

### How to Reproduce

after the last few days of the old error where glad badge was being suggested during its cd, this stopped, but back then the hotkey wasnt showing either, the main issue with the suggestion is fixed but the hotkey/keybind isnt showing in the suggestion list still. on many toons, reloaded, made sure im up to date, etc. 

### Player Information (Link)

https://pastebin.com/1TpY0Rmw

### Error Messages (Link)

https://pastebin.com/1TpY0Rmw

### Contact Information

QuiteGoneJin#0321

**Comment by Hekili** [comment]
Fixed in 1.0.7.
