### ISSUE TITLE
[REC] Sub rogue not working properly

### ISSUE THREAD

**Issue by Floapy** [Hekili/hekili#1308]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sometimes doesn't give me recommendations on the spells I have to use

### How to Reproduce

No clue

### Snapshot (Link)

https://pastebin.com/UJPCJGCd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vrD8oUDmZK9zgEsx17Wwoq

### Additional Information

It started ~2-3 ago I think? not sure exactly.

### Contact Information

Floapy#0124

**Comment by Floapy** [comment]
https://pastebin.com/0hA1XAY4 < Snapshot I 100% know for sure that it has the failed recommendations

**Comment by Hekili** [comment]
Please try the new alpha release.

https://github.com/Hekili/hekili/releases/download/v9.1.5-1.0.7-alpha1/Hekili-v9.1.5-1.0.7-alpha1.zip

**Comment by Floapy** [comment]
Seems to be working so far, further testing this.
