### ISSUE TITLE
Variable:  resource regen check fails

### ISSUE THREAD

**Issue by daBlitter** [Hekili/hekili#131]
Heliki 8.1.5-16

Script error after loading char:

Date: 2019-05-16 07:42:30
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Hekili\Scripts.lua line 1130:
   attempt to index field '?' (a number value)
Debug:
   [C]: ?
   Hekili\Scripts.lua:1130: LoadScripts()
   Hekili\Scripts.lua:1185: LoadScripts()
   Hekili\Classes.lua:4188: SpecializationChanged()
   Hekili\Events.lua:223: handler()
   Hekili\Events.lua:52:
      Hekili\Events.lua:46
Locals:

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AAPCore, v8.1055
  AddOnSkins, v4.15
  Altoholic, vr190
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AzeritePowerWeights, v8.1.15
  AzeriteTooltip, v2.0.2
  AzerothAutoPilot, v
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.24-10-g267a7763c
  DBMDefaultSkin, v
  DBMInterrupts, v8.1.0
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.2
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v11.11
  ElvUILocPlus, v2.42
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  FishingBuddy, v1.9.29
  GatherMate2, v1.43.6
  GTFO, v4.47.1
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  Hekili, vv8.1.5-16
  Informant, v8.1.6246 (SwimmingSeadragon)
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.149
  NPCScan, v8.0.1.13
  OmniCC, v8.1.1
  Pawn, v2.2.41
  ReQuest, v0.1
  SexyMap, vv8.1.1
  Simulationcraft, v1.11.1
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TomTom, vv80105-1.0.0
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=77d)

**Comment by Hekili** [comment]
Thanks, please be sure to provide the information from your Issue Reporting tab in the future; it helps with investigating problems for specific specs/builds/azerite, etc.

**Comment by Hekili** [comment]
Posting a fix in v8.1.5-17; please update.  If still having issues, please re-report and include all the information in the ticket instructions.  Thanks!
