### ISSUE TITLE
[BUG] Guardian Druid Interrupts not being recommended

### ISSUE THREAD

**Issue by gonzoinc** [Hekili/hekili#1310]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Guardian druid interrupts are not being shown an all. No interrupts are showing in the primary window or when separate window toggle is checked.

### How to Reproduce

1. Enter Spires of Ascension (tested on Normal mode since solo test)
2. Engage a Forsworn Goliath
3. No interrupt was recommended.

When Rebellious Fists casts, then Skull Bash should be the recommended interrupt for single target, Incapacitating Roar for multi target/spell interrupt.

Snapshot was taken about 50% into the rebellious fists cast

### Player Information (Link)

https://pastebin.com/kqap470q

### Error Messages (Link)

n/a

### Additional Information

Interrupts are working and recommending fine on my main BM Hunter (except when the separate window toggle is enabled). 
They used to be recommended on the Guardian Druid also so not sure exactly when it stopped functioning

**Comment by Hekili** [comment]
1.  Wrong kind of ticket, this is about the addon's recommendations.  But you ended up submitting a snapshot, so okay.  I'll treat it as a recommendations ticket.
2.  Based on the snapshot, I can tell that you're not using the default Guardian priority, which has Skull Bash in it.  What you imported does not.  I don't support imported priorities (which the ticket for recommendations would've warned you about).

You can go to `/hekili` > Priorities > Guardian and click the little circle arrow to the right of Priority Name to reset back to the default that is included with the addon.

You do not need to import your priority from simc.

**Comment by gonzoinc** [comment]
Sorry about that, Honestly didn't even notice that last option....

TBH I don't even know how to import from SimC and have never messed with anything in the priority list. Made the change and tested again. Same mob/dung scenario and now skull bash shows up but only as the second recommendation and only for a split second, shows about 40% into the cast and then just disappears. Going to uninstall and reinstall the addon as I think something is out of whack and Idk where to look as I have not messed with anything outside of the toggles and just UI stuff.

**Comment by Hekili** [comment]
I don't know how you'd have a priority installed that doesn't have Skull Bash as the first entry in the priority list without manually editing the priority or importing something you shouldn't.

I usually set my interrupts to show in a separate display.  The addon tries to interrupt channels immediately, or cast-time spells in the last second of the cast.

**Comment by gonzoinc** [comment]
Deleted and re-installed and everything is working as it should. Now that I'm thinking about it I guess I should have backed up the old one first in case you needed to examine it. Profiles were all still there and loaded back. Everything is good so IDK. Even the separate interrupt window is now working which wasn't on all my characters. Thanks for the help.
