### ISSUE TITLE
[REC] Action bar only possible?

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1311]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Is it possible to turn off all display EXCEPT for the action bar?
I'm asking for a friend who is searching for a conro replacement.

### How to Reproduce

attempt to have actions bars be the only notification of next skill in rotation

### Snapshot (Link)

none

**Comment by Hekili** [comment]
This is not what issue tickets are for.

You can look at SpellFlash settings on each display.
