### ISSUE TITLE
[BUG] Hekili occasionally stops working for unholy dk 

### ISSUE THREAD

**Issue by Savanta177** [Hekili/hekili#1312]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

At certain times hekili bugs out with my death knight and it does not show the spells to click next or it would only show 1 or 2 spells at a time. This happened frequently in a mists dungeon I did.

### How to Reproduce

I don't know how to replicate it, it seems to be at random.

### Player Information (Link)

build: v9.1.5-1.0.7 level: 60 (60) class: DEATHKNIGHT spec: unholy  talents: army_of_the_damned     asphyxiate     clawing_shadows     soul_reaper     spell_eater     unholy_blight     unholy_pact  pvptalents: none  covenant: necrolord  conduits: condensed_anima_sphere = 5    eternal_hunger = 5    insatiable_appetite = 5    lingering_plague = 4  soulbinds: [plague_deviser_marileth]    kevins_keyring = 1    oozs_frictionless_coating = 1    volatile_solvent = 1  sets: none  gear: allconsuming_loop = 1     endlessly_gluttonous_greaves = 1     faesworn_warmaul = 1     girdle_of_the_soulflayer = 1     pranksters_pauldrons = 1     ritual_bone_band = 1     sabatons_of_the_towering_construct = 1     shadowsteel_breastplate = 1     soul_cage_fragment = 1     trailspinner_pendant = 1     vambraces_of_the_inbetween = 1     vault_attendants_cape = 1     vault_guardians_handguards = 1     viscera_of_coalesced_hatred = 1     wrathbark_greathelm = 1  legendaries: none  itemIDs: 171442, 178694, 178697, 178707, 178808, 178870, 179326, 179536, 182992, 186751, 186770, 187392, 187397, 187402, 187447  settings: aoe = 2     buffPadding = 0     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycleDebuff = festering_wound     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = true     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 8     nameplates = true     package = Unholy     petbased = false     potion = potion_of_spectral_strength     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false  toggles: cooldowns = false     custom1 = false      custom2 = false      defensives = false      essences = false      interrupts = false      mode = automatic      potions = false 

### Error Messages (Link)

no error messages

**Comment by Hekili** [comment]
This is the wrong kind of ticket. Submit a recommendations ticket and supply the snapshot(s) it requires. They are automatically generated when the addon can't find something to recommend.
