### ISSUE TITLE
Arcane Mage arcane missiles spam / wants me to use frost bolt and fire blast

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#1313]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With cooldown activated (Arcane Power available as well as Radiant Spark and Touch of the Magi) and full stacks of Resonating Harmony the suggestion were spamming arcane missiles then frost bolt and some glitch suddenly showing Fire Blast. 

In the opener Hekili doesn't tell me to Touch after radiant spark but to spam arcane missiles, if I use Touch without following the advices then it shows Arcane Power & Burst correctly. 

### How to Reproduce

Playing Kyrian Arcane Mage normal raid spec cooldown activated (1-2-3-1-1-2-1 -- Mikanikos and usual conduits) with Arcane Infinity leggo on training dummy in Elysian Hold 

### Snapshot (Link)

https://pastebin.com/qWtxdHWr

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wYta8y3wqqjxq6LqdsZe3E

### Additional Information

Here are other snapshots of what I described : https://pastebin.com/ysL28G1A

Here I'm starting the normal burst (rune 3s before pull, spam missiles until 18 stacks, then radiant spark. Right after Radiant Spark is used I should be advised to do Touch > Arcane Power + trinkets & Racial > 5x Arcane Blast > Barrage. Instead it tells me to cast arcane missiles again.

### Contact Information

Nibana#6011

**Comment by Amortalist** [comment]
It's only when I start casting the right spell (which isn't the spell advised on Hekili) that Hekili decides that the rotation is the correct one. 

Here is another snapshot : https://pastebin.com/9ZKdxaNQ

In this one I purposely made the good opener (rune, 3x missile on pull > radiant spark > touch > arcane power + on use). Right now it should tell me to do 5x Arcane Blast > 1x Barrage > Presence of Mind > 2x Blast > Arcane Missiles until Arcane Power falls off, but instead it tells me to use Arcane Missiles (when I already have 18 stacks of Harmony) which would basically make Radiant Spark useless (falls off after 4 hits) and then cast Barrage.

**Comment by Amortalist** [comment]
Normal pull without modifying the prepull logic by using Rune before engaging : https://pastebin.com/DW5tTcap 

Tells me to Rune of Power instead of TotM > Arcane Power

**Comment by Amortalist** [comment]
Redid the Clearcast > Rune > 3x Arcane Missiles > Radiant Spark opener, should advise TotM Arcane Power next instead of missile spam : https://pastebin.com/bXDZ5ZrX

**Comment by Hekili** [comment]
Fixed in v.9.1.5-1.0.8.  Thanks!
