### ISSUE TITLE
Arcane Mage rotation doesn't use mana gems

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#1315]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Mana Gem is not advised here but should be, it also never shown in 3+ minutes of rotation :  https://pastebin.com/UNunM6Qw

Not playing Enlightened, mana inferior to 80% and 3 gems in inventory. 

### How to Reproduce

Do Kyrian arcane mage normal opener and rotation on dummy with Harmony Leggo
Talents 1-2-3-1-1-2-1

### Snapshot (Link)

https://pastebin.com/UNunM6Qw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/meoGawT9DJ6aQJzgcpZRku

### Contact Information

Nibana#6011

**Comment by Hekili** [comment]
This should be resolved in current release.

**Comment by Amortalist** [comment]
Still not working

**Comment by Hekili** [comment]
Add a new snapshot.

**Comment by Amortalist** [comment]
I'm not sure where in the rotation to select the snapshot. Maybe describe the logic of mana gem in the code so I can reproduce like, being sub XXmana and above XXmana with evocation not active or smth.

**Comment by Hekili** [comment]
With Enlightened talented:
- Mana <= 80%
- Mana >= 65%

Without Enlightened talented:
- Mana <= 85%

**Comment by Amortalist** [comment]
https://pastebin.com/myMHpsfy

**Comment by Hekili** [comment]
You're not using the latest.

**Comment by Amortalist** [comment]
Is it not live on curseforge & all ? I updated when you closed the issue, have the latest version available. I'll download the one on GitHub

**Comment by Hekili** [comment]
You have v9.1.5-1.0.9-alpha1.

Current release is v9.1.5-1.0.9 (which is newer).

There is also a newer alpha (v9.1.5-1.0.10-alpha1).

![image](https://user-images.githubusercontent.com/9438134/149023355-7fd7e874-3eac-4d5d-ae85-e87b68d45216.png)

**Comment by Amortalist** [comment]
Might be a bug from curse then, I updated with the 2022-01-02 version yesterday through curseforge

**Comment by Hekili** [comment]
There is no 2022-01-02 version.

**Comment by Amortalist** [comment]
![image](https://user-images.githubusercontent.com/47482996/149023715-f10a1103-26eb-4f9f-8fe5-13a6845d16cd.png)

**Comment by Amortalist** [comment]
Using the latest release on GitHub, sub 80% mana : https://pastebin.com/dC7AQURd

**Comment by Hekili** [comment]
Re: date, maybe it's a time zone difference.

Do you actually have a mana gem in your bag?

If so, can you see what its item ID is?

**Comment by Amortalist** [comment]
Yes I have one. Item ID is 36799

**Comment by Hekili** [comment]
Thanks, this is helpful.

**Comment by Hekili** [comment]
Today's release should use Mana Gems and even show their keybinding successfully.
