### ISSUE TITLE
[BUG] Instructor's Divine Bell Trinket graphic not showing.

### ISSUE THREAD

**Issue by Daugger** [Hekili/hekili#1316]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The instructor's Divine Bell trinket from world quests does not show a graphic when Hekili suggests using it. It shows an empty see through box.

### How to Reproduce

1. Have Instructor's Divine Bell equipped.
2. Use abilities until Hekili suggests using trinket.

### Player Information (Link)

https://pastebin.com/Tgqfwdrp

### Error Messages (Link)

No in game error messages

### Contact Information

Daugger09#7115

**Comment by Odysseas68** [comment]
Also have the same exact problem

**Comment by Hekili** [comment]
I'll need a snapshot taken when the trinket is recommended but its icon is blank.

**Comment by Odysseas68** [comment]
Just to inform you that the first time i login to the game the trinket icon appears correctly. If i do a reload then the icon is blank.

 https://i.imgur.com/4wh6vUn.png

**Comment by Hekili** [comment]
Thanks.

By snapshot, I mean:

> Snapshots are logs of addon decision-making used to see how it arrived at its present recommendations.

> Unless disabled, the addon will automatically take a snapshot when it is unable to arrive at a recommendation. Additionally, you can create a snapshot by pressing Pause (default: ALT-SHIFT-P) or Snapshot (default: ALT-SHIFT-[) at the time you are seeing the recommendation that you disagree with. You can change these keybinds in /hekili > Toggles.

> When reporting any issue with the addon's recommendations, please include a snapshot taken at the time you are seeing the problem. You will need to copy the snapshot from /hekili > Snapshots and paste it to a site like Pastebin. It can be tricky to create a snapshot at the exact moment, but it is the only way to be absolutely sure why you are seeing the recommendations that you see.

It's helpful to know that it works on first load, but not after reload, too.

**Comment by Odysseas68** [comment]
Here is the snapshot. I did it quickly because of the reset time. The trinket was the first recommendation of the add on. This is the recommendation with the icon blank. This time no need to reload for the icon to be blank.

https://pastebin.com/EVN4fcgs

Hope this helps.

**Comment by Daugger** [comment]
Here is my snapshot if comparing two is helpful.

https://pastebin.com/c2f979PY

**Comment by Hekili** [comment]
Thanks, sorry to ask more of y'all, but the output from the following macros would be useful.

Each of the following, once when Divine Bell shows up (i.e., first login, before reload) and again after a reload and Divine Bell's icon is missing.

- [ ] `/dump Hekili.Class.abilities.instructors_divine_bell`
- [ ] `/dump Hekili_Primary_B1`
   *If your addon is set to show multiple recommendations and your Divine Bell is in the second or third icon, change `B1` to `B2` or `B3` in the second macro.*
- [ ] `/dump HekiliDisplayPrimary.Recommendations[1]`
   *If your addon is set to show multiple recommendations and your Divine Bell is in the second or third position, change `[1]` to `[2]` or `[3]` in the third macro.*

**Comment by Odysseas68** [comment]
Ok... here are the results:

Icon is ok (1rst login in game)

Note1: I have set the addon To show Separately the Cooldowns
Note2: I have install Elvui. Do i have to enable anything in addon config?

https://pastebin.com/sS5AZ86z

Icon blank. After reload

https://pastebin.com/KXC22aK5

---------------------
Check the first 10-15 lines of the /dump Hekili.Class.abilities.instructors_divine_bell.
2nd time after reload (blank  icon) it's different.

**Comment by Hekili** [comment]
With Cooldowns shown separately, then two macros have to change:

- [ ] `/dump Hekili_Cooldowns_B1`
- [ ] `/dump HekiliDisplayCooldowns.Recommendations[1]`

**Comment by Hekili** [comment]
After you've reloaded, if you type `/hekili` is there a "Warnings" on the left section?  If so, what all is in that tab?

**Comment by Odysseas68** [comment]
ok..

First login icon ok (with Cooldowns shown separately):

https://pastebin.com/nAd1yy6C

after reload icon missing

https://pastebin.com/jSHPt3Ba

no warnings from `/hekili` after reload.

https://i.imgur.com/s7lJQOo.png

**Comment by Odysseas68** [comment]
Also just notice that in the first login in `Gear and trinkets` you can see it in the drop down menu:
https://i.imgur.com/fPsPNU5.png

After reload it missing from there also.
https://i.imgur.com/ipUn11H.png

**Comment by Daugger** [comment]
This is my results from the previous mentioned commands after a reload. I also want to mention that when I pause hekili before a reload that the recommendations move position. bell will be in the second slot but when i pause it moves to the third slot, the first recommendation moves to the second slot, and the original opening shows up in the first slot.

https://pastebin.com/nuBvX4Ek

i think it was just because my first recommendation was on such a short cd. 3.4 seconds. but finally got it to where it stayed put. This is the output before a reload and the icon is visable. 

https://pastebin.com/15iPECqV

**Comment by Hekili** [comment]
I genuinely don't know if 1.0.10-alpha1 is going to make a difference or not, but please try it when it finishes building.

You may also notice that you clear the loading screen more quickly.

Or everything may break.  (If so, you can revert back to the 1.0.9 release.)

**Comment by Odysseas68** [comment]
I just try the alpha version `1.0.10-alpha1` and it seems the problem gone. Test it with before and after reload and in combat with a Training dummy (use it and in 1 minute start the countdown of the cooldown sowing the icon).

**Comment by Hekili** [comment]
Thanks for reporting back. Let me know if you find any other issues.

**Comment by Odysseas68** [comment]
Thanks. If i can help in anyway i can just tell me.

Happy new year!!

**Comment by marekCs** [comment]
This bug has disappeared on alpha (it was only when I didn't have the trinket on the bar) but it seems to me that the performance is now worse (Fire mage here, but excuse my rating I'm just a private server)

**Comment by Hekili** [comment]
> This bug has disappeared on alpha (it was only when I didn't have the trinket on the bar) but it seems to me that the performance is now worse (Fire mage here, but excuse my rating I'm just a private server)

None of the changes would impact Fire Mage, but Fire Mage is what it is and isn't part of this ticket.
