### ISSUE TITLE
[BUG] ROUGE - Vanish

### ISSUE THREAD

**Issue by GoceNakov** [Hekili/hekili#1317]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Vanish showing up inside rotation even it is set to OFF when solo.

### How to Reproduce

![Screenshot 2021-12-16 at 20 00 12](https://user-images.githubusercontent.com/96261192/146432365-1da19fce-7caa-4de3-b5af-c82f2653deea.png)

### Player Information (Link)

https://pastebin.com/zkMfjGPV

### Error Messages (Link)

No error

**Comment by Hekili** [comment]
This is about recommendations; submit a recommendations ticket that includes a snapshot of the addon recommending Vanish.
