### ISSUE TITLE
[REC] SUB ROGUE - Vanish

### ISSUE THREAD

**Issue by GoceNakov** [Hekili/hekili#1318]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Vanish showing inside rotation even it is turned off when solo

### How to Reproduce

![Screenshot 2021-12-16 at 20 04 42](https://user-images.githubusercontent.com/96261192/146433036-fc97f403-85ed-434e-a518-5a5a5909ae4f.png)
![Screenshot 2021-12-16 at 20 00 12](https://user-images.githubusercontent.com/96261192/146433049-a42be252-fbeb-4b26-9032-399a1b653b3d.png)

### Snapshot (Link)

https://pastebin.com/tiGQELSQ

**Comment by Hekili** [comment]
That link is not a complete snapshot.  I need a snapshot where Vanish was recommended while solo.

**Comment by GoceNakov** [comment]
Here you go
![Screenshot 2021-12-16 at 21 29 52](https://user-images.githubusercontent.com/96261192/146444706-3f3ab3e8-5a3a-4c85-839c-b8466df0f035.png)

**Comment by Hekili** [comment]
No, please follow ticket instructions.


## Snapshot (Link)

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

* Log into your WoW character.
* Recreate the issue you are reporting (i.e., generate 5 Holy Power).
* When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
* Type /hekili and press Enter.
* Open the Snapshots section on the left side.
* Select the display which is showing the recommendation (usually Primary).
* Select the snapshot number (usually 1, if you took only 1 snapshot).
* Copy all of the text in the lower box.
* Paste the text to Pastebin (pastebin.com).
* Provide the Pastebin link here.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.
If you do not provide this information, I cannot triage your problem.

Snapshot Link:

**Comment by GoceNakov** [comment]
Sorry for that, here you go. I am sure it worked fine like some versions ago, then I played my warrior for some time and when I returned to the rogue, this issue persisted.

https://pastebin.com/9mr7t1Gc

**Comment by Paul2or3** [comment]
Same issue on Assassination Rogue

**Comment by Hekili** [comment]
This should be resolved in the latest release.
