### ISSUE TITLE
Script Error and no display - Assassination Rogue

### ISSUE THREAD

**Issue by daBlitter** [Hekili/hekili#132]
Heliki 8.1.5-16

After loading char:

Date: 2019-05-16 07:50:18
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Hekili\State.lua line 3352:
   attempt to index global 'forbidden' (a nil value)
Debug:
   [C]: ?
   Hekili\State.lua:3352:
      Hekili\State.lua:3314
   [string "-- Assassination:direct:1 recheck..."]:2: Recheck()
   Hekili\State.lua:1254: recheck()
   Hekili\Core.lua:673: GetPredictionFromAPL()
   Hekili\Core.lua:590: GetPredictionFromAPL()
   Hekili\Core.lua:986: GetNextPrediction()
   Hekili\Core.lua:1153: ProcessHooks()
   Hekili\UI.lua:820:
      Hekili\UI.lua:684
Locals:

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AAPCore, v8.1055
  AddOnSkins, v4.15
  Altoholic, vr190
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AzeritePowerWeights, v8.1.15
  AzeriteTooltip, v2.0.2
  AzerothAutoPilot, v
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.24-10-g267a7763c
  DBMDefaultSkin, v
  DBMInterrupts, v8.1.0
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.2
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v11.11
  ElvUILocPlus, v2.42
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  FishingBuddy, v1.9.29
  GatherMate2, v1.43.6
  GTFO, v4.47.1
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  Hekili, vv8.1.5-16
  Informant, v8.1.6246 (SwimmingSeadragon)
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.149
  NPCScan, v8.0.1.13
  OmniCC, v8.1.1
  Pawn, v2.2.41
  ReQuest, v0.1
  SexyMap, vv8.1.1
  Simulationcraft, v1.11.1
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TomTom, vv80105-1.0.0
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=77d)

**Comment by daBlitter** [comment]
Heliki 8.1.5-15 works fine with the rogue

**Comment by Hekili** [comment]
Merged with #131, fix pending.
