### ISSUE TITLE
[REC] Warlock: Demo: Vilefiend never recommended with Wilfred legendary active

### ISSUE THREAD

**Issue by tflo** [Hekili/hekili#1320]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With the Wilfred legendary (the one that reduces the CD of the Tyrant) equipped, I never see the recommendation to cast “Summon Vilefiend” and, in consequence, the whole Tyrant build-up fails (Tyrant never recommended, which ofc is plausible, since we don't have the Vilefiend out).

If I ignore the absence of the Vilefiend recommendation and put it out “on my own”, then also the Tyrant appears as CD recommendation at the appropriate time, i.e. correctly (AFAICT).

The responsible APL code for this seems to be in ‘tyrant_setup’ -> ‘3. Summon Vilefiend’. To make the logic more transparent, here the code in indented form:

```
( 
    cooldown.summon_demonic_tyrant.remains_expected < 15 - (
    action.summon_demonic_tyrant.execute_time 
    ) & 
    (
        cooldown.call_dreadstalkers.remains < 15 - (
            action.summon_demonic_tyrant.execute_time + action.summon_vilefiend.execute_time 
        ) 
    | pet.dreadstalker.remains > cooldown.summon_demonic_tyrant.remains_expected + action.summon_demonic_tyrant.execute_time 
    )
) | 
(
    ! runeforge.wilfreds_sigil_of_superior_summoning.enabled & cooldown.summon_demonic_tyrant.remains_expected > 40 
)
```

If I read it correctly, with Wilfred active, the only accepted condition is the expected CD of Summon Tyrant being less than 15s. Without Wilfred the condition is `>40`, and without Wilfred indeed the APL works as expected (Vilefiend _is_ recommended and then leads to the usual Tyrant build-up).

In a short test I changed the `cooldown.summon_demonic_tyrant.remains_expected` in line 2 above to 1500s, just to force it to return true, and then the whole thing seems to work properly also with Wilfred.

To be honest I don't really see the logic in this APL, seems kind of awkward to me. But I can confirm that during multiple Torghast runs with Wilfred equipped and this APL active, I’ve never seen a Vilefiend recommendation. (Without Wilfred: everything normal.) 

Not a big issue, but in hectic fights it is irritating, since I’m very used to the normally good recommendatons by Hekili.

### How to Reproduce

1. Be specced to Demonolgy Warlock.
2. Equip Wilfred legendary.
2. Make sure that the Demonic Consumption talent is active.
3. Hit any major mob, or target dummy, and observe the recommendations.

### Snapshot (Link)

https://pastebin.com/Nxx084Ty

### Additional Information

Snapshot after having cast one initial ‘Shadow Bolt’ and then ‘Grimoire: Felguard’. At this point (or even before casting Felguard) Vilefiend should be recommended.

**Comment by Hekili** [comment]
Post a screenshot of your /hekili > Abilities > Summon Demonic Tyrant settings, please.

> If I read it correctly, with Wilfred active, the only accepted condition is the expected CD of Summon Tyrant being less than 15s. Without Wilfred the condition is >40, and without Wilfred indeed the APL works as expected (Vilefiend is recommended and then leads to the usual Tyrant build-up).

No, that's not a correct interpretation.

I can see the the addon thinks your remaining CD for Summon Demonic Tyrant is exactly 90 seconds, which is unlikely -- that's what the addon does when an ability is disabled or toggled off.

**Comment by tflo** [comment]
Here a [screenshot](https://d.pr/i/VzB2FT). Nothing deactivated and the toggle is Default.

But you maybe bring up a good point here: I remember that some time ago (~2 months)  I indeed  changed something from primary display to CD display during a TG run, and if I remember correctly, it was the Tyrant (which apparently was not on the CD display at that time).

But since then I have reloaded the original APL several times.

**Comment by Hekili** [comment]
Under Toggles, do you have "Show Separately" checked for Cooldowns?  The snapshot doesn't say so, but that would be cause Tyrant's CD to be faked in the Primary display.

If you uncheck Show Separately for Cooldowns, you'll see Vilefiend recommended.

**Comment by Hekili** [comment]
Alternately, you could set Summon Vilefiend's "Require Toggle" to "Cooldowns" and that will make it appear in the CDs display.

**Comment by tflo** [comment]
> Under Toggles, do you have "Show Separately" checked for Cooldowns? 

Indeed, I had, and without that the Vilefiend shows up correctly. But the CD display is such a huge usability improvement, that I don't wanna miss it. And it works fine, genarally (I use Hekili on all 12 classes, and with most specs.)

> Alternately, you could set Summon Vilefiend's "Require Toggle" to "Cooldowns" and that will make it appear in the CDs display.

Going to check this out…

**Comment by Hekili** [comment]
> And it works fine, genarally (I use Hekili on all 12 classes, and with most specs.)

Sure, but the concept of toggles doesn't even exist in SimC (because how would you turn things on/off mid simulation), so priorities aren't written to accommodate it.  But I have to fake CDs for just this kind of scenario -- if you're holding Tyrant, you probably want to hold the abilities that you would align with Tyrant, too.

The separate display is just a recent accommodation that doesn't always work well.

I may alter some logic so that I can potentially turn off the faked CD when something is toggled into a separate display, but that could just as easily break the logic in other specs' priorities.  Hard to know.

**Comment by tflo** [comment]
OK, Vilefiend on CD seems to work too. But, ofc, Vilefiend is not really a CD (in terms of CD duration; you use it also on intermediate mobs). 

But this is definitly a usable solution. Thank you for this!

> The separate display is just a recent accommodation that doesn't always work well.

I'm aware of that and also that you have introduced it only recently (more or less). But in general it really works fine. And it's the only way to go, IMO: Blocking the main display with CDs you won't use at that moment doesn't make sense.

**Comment by Hekili** [comment]
> IMO: Blocking the main display with CDs you won't use at that moment doesn't make sense.

That's why the CD toggle exists, you tell them to go away and then invite them back when you want to use them.

But anyway, I'll see if I can adjust this without breaking everything else.

**Comment by tflo** [comment]
I see, you are calling me lazy because I want to have all in one without toggling ;)

**Comment by tflo** [comment]
And I _am_ lazy. And I am not doing end game content like Mythic raids or such. And so I can understand that you rather go for full optimization (instead of maybe more usability). That's perfectly OK.

Thank you very much for your help!

– Tom

**Comment by tflo** [comment]
Just to not forget to mention it: The introduction of a separate CD row was a **substantial QoL improvement**. And I fully understand that the separation is likely to produce problems with the rotation, and that this probably generates lots of work.

But, it is really useful.

**Comment by tflo** [comment]
Just done a couple (well, at least 6) Torghhast runs, and it is definitely playable with the Vilefiend as CD. But … _somehow_ it doesn’t feel right. 

It’s not that I don’t know how to set up my Tyrant without Hekili, it’s rather when I am with trash elites, or even non-elite trash, I forget to cast the Vilefiend  just because it isn’t there in Hekili’s main display – as it used to be (w/o Wilfred). And, since it is only a 40s CD, it should be there.

And, as said, without Wilfred, the recommendations seem right to me. (With Vilefiend on default display.) There is definitely room for optimization here.
