### ISSUE TITLE
Retribution Paladin priority not showing final reckoning

### ISSUE THREAD

**Issue by bangarang7** [Hekili/hekili#1321]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am currently talented into Final Reckoning, however the priority list currently does not recommend it for me.

I recently got a new computer and had to reinstall Hekili and used the profile I had saved. This profile was showing Final Reckoning on my previous computer, so I'm not quite sure how this issue started on my new computer.

### How to Reproduce

1. Enter the game as a Retribution Paladin.
2. Be in combat for ~20 seconds.
3. Notice Final Reckoning won't appear.

### Snapshot (Link)

https://pastebin.com/pUxAPbCg

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/orxj38NQ4DmfVzwxbFNzBj

**Comment by Hekili** [comment]
See /hekili > Toggles. Your big CDs are toggled off by default. Use the hotkey to tell the addon when you want them recommended.
