### ISSUE TITLE
Rogue/Assassination not showing Vendetta in rotation

### ISSUE THREAD

**Issue by airsorc** [Hekili/hekili#1326]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It never recommends me to use Vendetta at any point during my rotation.

### How to Reproduce

1. Following rotation via Hekili.
2. Vendetta never appears

### Snapshot (Link)

https://pastebin.com/yrm2aE5A

### Contact Information

Air#5486

**Comment by Hekili** [comment]
Vendetta is a cooldown ability that is controlled by a toggle.  See https://github.com/Hekili/hekili/wiki/Getting-Started#toggles--cooldowns-interrupts-potions-and-defensives
