### ISSUE TITLE
[REC] Kyrian Balance Druid CA/Incarn never recommended in ST

### ISSUE THREAD

**Issue by ryanjoliveira** [Hekili/hekili#1328]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In general, switching to Kyrian Balance druid and using either Primordial Arcanic Pulsar or Kindred Affinity legendaries (possibly others, these are just the legendaries I have) results in a single target rotation that will never recommend me to press CA (or Incarn if it is talented).

The snapshot I took is basically after dotting up a target dummy and having near full astral power.  If I had kept following the ST recommendations, I'm pretty sure it will never have me press Incarn (incarn is talented for the particular snapshot I took, but the same happens for CA).

I normally keep recommendations up for both AoE and ST, and I can see at this point that the AoE recommendation would have me press Incarn after a single Starfall, which I mostly wanted to mention as its a sort of sanity check that I do have cooldown recommendations enabled.  Also when I switch to NF without any other changes, the ST rotation is fine and recommends things correctly.

Interestingly as a result of never pressing Incarn, its also never having me activate the Kindred Spirits buff or activating my Instructor's Divine Bell, which I'm pretty sure is because it wants to do those after you press Incarn.

### How to Reproduce

1. Go Kyrian Balance Druid.
2. Activate Lone Spirit (covenant ability)
3. Trinket choice or soulbind choice doesnt seem to matter, but I'm using Mikanikos
3. Go hit a single target dummy for a while following recs exactly and see if it ever recommends CA/Incarn

### Snapshot (Link)

https://pastebin.com/G5qdnUqk

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fQc8AoDUcwdL2qfkAaQbNZ

### Contact Information

Discord ryanolloz#4617

**Comment by Hekili** [comment]
Hey, I've reviewed this pretty closely and found an issue that'll be addressed in the next release.

This will make the Kyrian opener look more like this:

![image](https://user-images.githubusercontent.com/9438134/147892028-042ebddb-a3ab-46ff-9e5d-6ea236fef815.png)

In a boss fight, without Bloodlust, there'd be a reset of Astral Power when the encounter starts, so you'd likely see another Starfire before Incarnation.  After Incarnation, you'd likely see Empower Bond (I can't show it because my Druid isn't actually Kyrian).

**Comment by Hekili** [comment]
This should be resolved in the latest release.
