### ISSUE TITLE
[BUG] Covenant toggle doesn't work

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#1329]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Covenant toggle doesn't work for Brewmaster Monk.
I toggle off covenant but still recommends Bonedust Brew.

### How to Reproduce

.

### Player Information (Link)

https://pastebin.com/L63D1gK9

### Error Messages (Link)

.

**Comment by Hekili** [comment]
Wrong ticket type; this requires a snapshot.  See "Priority/Recommendations Issue."
