### ISSUE TITLE
Hunter dont work

### ISSUE THREAD

**Issue by ch0b04ng3l** [Hekili/hekili#133]
Date: 2019-05-16 09:32:46
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Hekili\Scripts.lua line 1130:
   attempt to index field '?' (a number value)
Debug:
   Hekili\Scripts.lua:1130: LoadScripts()
   Hekili\Scripts.lua:1185: LoadScripts()
   Hekili\Classes.lua:4188: SpecializationChanged()
   Hekili\Events.lua:223: handler()
   Hekili\Events.lua:52:
      Hekili\Events.lua:46
Locals:
self = <table> {
 IsTimeSensitive = <function> defined @Interface\AddOns\Hekili\Scripts.lua:1054
 PackInfo = <table> {
 }
 DB = <table> {
 }
 CTC = <function> defined @Interface\AddOns\Hekili\Scripts.lua:354
 EmulateSyntax = <function> defined @Interface\AddOns\Hekili\Scripts.lua:477
 SplitExpr = <function> defined @Interface\AddOns\Hekili\Scripts.lua:223
 SimToLua = <function> defined @Interface\AddOns\Hekili\Scripts.lua:145
 BuildRecheck = <function> defined @Interface\AddOns\Hekili\Scripts.lua:415
 GetModifiers = <function> defined @Interface\AddOns\Hekili\Scripts.lua:1061
 StoreReadyValues = <function> defined @Interface\AddOns\Hekili\Scripts.lua:753
 CheckScript = <function> defined @Interface\AddOns\Hekili\Scripts.lua:983
 ConvertScript = <function> defined @Interface\AddOns\Hekili\Scripts.lua:837
 ImplantDebugData = <function> defined @Interface\AddOns\Hekili\Scripts.lua:1310
 CheckVariable = <function> defined @Interface\AddOns\Hekili\Scripts.lua:1032
 LoadItemScripts = <function> defined @Interface\AddOns\Hekili\Scripts.lua:1200
 LoadScripts = <function> defined @Interface\AddOns\Hekili\Scripts.lua:1094
 GetConditionsAndValues = <function> defined @Interface\AddOns\Hekili\Scripts.lua:1346
 Channels = <table> {
 }
 GetScript = <function> defined @Interface\AddOns\Hekili\Scripts.lua:758
 RecheckExpr = <function> defined @Interface\AddOns\Hekili\Scripts.lua:411
 StoreValues = <function> defined @Interface\AddOns\Hekili\Scripts.lua:731
}
profile = <table> {
 toggles = <table> {
 }
 minimapIcon = false
 displays = <table> {
 }
 packs = <table> {
 }
 Clash = 0
 runOnce = <table> {
 }
 notifications = <table> {
 }
 clashes = <table> {
 }
 interrupts = <table> {
 }
 iconStore = <table> {
 }
 trinkets = <table> {
 }
 specs = <table> {
 }
 enabled = true
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Marksmanship = <table> {
 }
 Beast Mastery = <table> {
 }
 Survival = <table> {
 }
}
(for control) = "Marksmanship"
pack = "Marksmanship"
pData = <table> {
 source = "# https://github.com/simulationcraft/simc/"
 builtIn = true
 date = 20190317.204400
 author = "SimC"
 hidden = false
 desc = "# Marksmanship Hunter
# https://github.com/simulationcraft/simc/
# March 17, 2019 - 20:42

# Changes:
# - Add utility priority to APL.
# - Use time_to_die rather than target.time_to_die to anticipate end of combat."
 lists = <table> {
 }
 version = 20190317.204400
 warnings = "Imported 6 action lists.
"
 spec = 254
 profile = "# Marksmanship Hunter
# https://github.com/simulationcraft/simc/
# March 17, 2019 - 20:42

# Changes:
# - Add utility priority to APL.
# - Use time_to_die rather than target.time_to_die to anticipate end of combat.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/augmentation
actions.precombat+=/food
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion
actions.precombat+=/hunters_mark
# Precast this as early as possible to potentially gain another cast during the fight.
actions.precombat+=/double_tap,precast_time=10
actions.precombat+=/trueshot,precast_time=1.5,if=active_enemies>2
actions.precombat+=/aimed_shot,if=active_enemies<3

actions.utility=counter_shot
actions.utility+=/serenity_dust
actions.utility+=/spore_cloud
actions.utility+=/soothing_water
actions.utility+=/sonic_blast
actions.utility+=/nether_shock
actions.utility+=/chijis_tranquility
ac}
specData = <table> {
 totems = <table> {
 }
 RegisterPet = <function> defined @Interface\AddOns\Hekili\Classes.lua:550
 itemAbilities = 0
 RegisterCycle = <function> defined @Interface\AddOns\Hekili\Classes.lua:546
 stateExprs = <table> {
 }
 class = "HUNTER"
 auras = <table> {
 }
 pets = <table> {
 }
 role = "DAMAGER"
 RegisterOptions = <function> defined @Interface\AddOns\Hekili\Classes.lua:533
 interrupts = <table> {
 }
 gear = <table> {
 }
 RegisterAbility = <function> defined @Interface\AddOns\Hekili\Classes.lua:349
 RegisterPowers = <function> defined @Interface\AddOns\Hekili\Classes.lua:250
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AddOnSkins, v4.15
  AdvancedInterfaceOptions, v1.2.9
  AngryKeystones, v
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AzeritePowerWeights, v8.1.15
  AzeriteTooltip, v2.0.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  BigWigs, vv148
  BigWigsCore, v
  BigWigsPlugins, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v11.11
  ElvUISLE, v3.53
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GroupfinderFlags, v0.10
  Hekili, vv8.1.5-16
  Informant, v8.1.6246 (SwimmingSeadragon)
  LittleWigs, vv8.1.14
  OmniCC, v8.1.1
  Pawn, v2.2.41
  RaiderIO, v8.1.0 (v201905160600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  Simulationcraft, v1.11.1
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  BlizRuntimeLib_deDE v8.1.5.80100 <none>
  (ck=63f)

**Comment by macgwery** [comment]
no icons are showing with my hunter, and all other classes, only shows 2 or 3 spells

**Comment by Hekili** [comment]
Merged with #131, fix is pending.
