### ISSUE TITLE
[REC] Covenant toggle doesn't work 

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#1330]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Covenant toggle doesn't work for Brewmaster Monk.
I toggle off covenant but still recommends Bonedust Brew.

### How to Reproduce

.

### Snapshot (Link)

https://pastebin.com/f6rXzRCk

### Additional Information

[https://pastebin.com/L63D1gK9](url)

**Comment by Hekili** [comment]
Can you check the following?

- On `/hekili` > Toggles, is `Cooldowns Override` checked next to Covenants?  If so, that means when Cooldowns are enabled, Covenants are also enabled.  You can uncheck it if you don't want that.  You can paste a screenshot here of that section of your options.
- On `/hekili`> Abilities > Bonedust Brew, what does the `Require Toggle` option show?  You can paste a screenshot.  If you've taken Bonedust Brew off the Covenants toggle here, then toggling off Covenants won't impact it.

Thanks!

**Comment by SUU09** [comment]
Cooldowns Override was checked, I uncheck it and solved my issue.
Thank you!

**Comment by Hekili** [comment]
Thanks for providing the detailed info so I could look into your issue.  Take care!
