### ISSUE TITLE
[BUG] Ventyr Druid - Hekili does not recommend Starsurge with full AP

### ISSUE THREAD

**Issue by Sdw8** [Hekili/hekili#1333]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After upgrading to version 1.0.9, the Druid often began to lose Starsurge recommendation at full AP. Can you fix this somehow? I have returned to version 1.0.8 for now.

### How to Reproduce

Use filler with high haste / burst and full AP.

### Snapshot (Link)

https://pastebin.com/AJtPrfRr

### Contact Information

__Nice#2063

**Comment by noiseuu** [comment]
soon fixing this?

**Comment by Hekili** [comment]
Are you seeing this outside of an initial opener?  The 1.0.9 update tries to model the AP reset on entering an encounter, but I may just remove that to avoid confusion.

**Comment by noiseuu** [comment]
I only see this bug at opener

**Comment by noiseuu** [comment]
okay, i see this bug everytime when i pop cd:s

**Comment by Hekili** [comment]
Yeah, I can see in your snapshot that you're more than a minute into combat but AP is resetting to 50.  I'll revert that.

**Comment by noiseuu** [comment]
Hello!
Just asking, are u gonna bring revert soon or 9.2?

**Comment by Hekili** [comment]
This will be in today's release.
