### ISSUE TITLE
[REC] SUB ROGUE// SLICE N DICE WHILE DANCE IS ACTIVE

### ISSUE THREAD

**Issue by SaschaDaSilva** [Hekili/hekili#1335]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili will recommend Slice and dice, as a combo finisher, while shadow dance is active, which will effectively remove 1 GCD (Shadowstrike/Eviscerate/Black Poweder) from shadow dance window which is a huge dps loss in the long run. This also applies to rupture

While Shadow dance is active, only Shadowstrike/Eviscerate/Black powder should be recommended as combo finisher, nothing else.

Cheers!

### How to Reproduce

Just play as sub rogue, wait until slice and dice or rupture is almost ran out, and enter shadow dance.

### Snapshot (Link)

-

### Raidbots Sim Report (Link)

-

### Additional Information

-

### Contact Information

SaschaDaSilva#6220

**Comment by Hekili** [comment]
Priorities will be updated for 9.2 and hopefully this is listed in there.  This ticket did not include the required snapshot and other information.
