### ISSUE TITLE
[BUG] Every 2 sec graphic stutters

### ISSUE THREAD

**Issue by LEOMODE** [Hekili/hekili#1336]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Every 2 sec, there is a 1-second graphic stutter that kind of stops whether I'm fighting, walking, running or flying. I disabled all add-ons and validated one add-on at a time and this add-on caused the stutter. 

### How to Reproduce

1. Enter the game with any characters. 
2. Try to fight/walk/run/fly. 

### Player Information (Link)

https://pastebin.com/pydmJKZk

### Error Messages (Link)

https://pastebin.com/59zRCTp2

**Comment by Hekili** [comment]
As the addon warns, using while leveling is at-your-own-risk.  It's likely that you're missing abilities/traits that are crucial to the priority, which results in more processing time as the addon tries to figure it out.

Don't use the addon below level 50.  If you continue to have issues above 50, you can submit a ticket and include a snapshot of recommendations.

Also, the error messages you included are not from this addon.  Thanks!

**Comment by LEOMODE** [comment]
Hi, the same bug occurs with the other 60 levels characters as well. It's not only limited to non-60. Please see below. Also, I don't see any of Hekili errors on bugsack. 

https://pastebin.com/V32uiVqA

**Comment by Hekili** [comment]
I'm not sure this will help pin down the answer, but:

1. Does it occur if you reset your Hekili profile to default?
2. If resetting to default addresses it, what settings do you routinely change from the defaults?
3. When did you first notice this issue?  More specifically, what is the last version that doesn't appear to have this issue?
4. If you upgrade to https://github.com/Hekili/hekili/tree/v9.1.5-1.0.10-alpha1, is the issue resolved?

Do you have CPU profiling enabled?  You can check with `/dump GetCVar("scriptProfile")`; if the result is `1` then profiling is enabled.

If profiling is already enabled and you disable it (`/run SetCVar("scriptProfile", "0")`), does that resolve the issue?

Otherwise, enable CPU profiling (`/run SetCVar("scriptProfile","1")` and `/reload`.  Leave your character idle and let the stutter for 1-2 minutes.  Then type `/run Hekili:DumpProfileInfo()` and paste the output on Pastebin and provide a link.  That will help show what addon functions are actually running periodically and may be running overly long.

**Comment by LEOMODE** [comment]
> I'm not sure this will help pin down the answer, but:
> 
> 1. Does it occur if you reset your Hekili profile to default?
> 2. If resetting to default addresses it, what settings do you routinely change from the defaults?
> 3. When did you first notice this issue?  More specifically, what is the last version that doesn't appear to have this issue?
> 4. If you upgrade to https://github.com/Hekili/hekili/tree/v9.1.5-1.0.10-alpha1, is the issue resolved?
> 
> Do you have CPU profiling enabled? You can check with `/dump GetCVar("scriptProfile")`; if the result is `1` then profiling is enabled.
> 
> If profiling is already enabled and you disable it (`/run SetCVar("scriptProfile", "0")`), does that resolve the issue?
> 
> Otherwise, enable CPU profiling (`/run SetCVar("scriptProfile","1")` and `/reload`. Leave your character idle and let the stutter for 1-2 minutes. Then type `/run Hekili:DumpProfileInfo()` and paste the output on Pastebin and provide a link. That will help show what addon functions are actually running periodically and may be running overly long.

Thanks. 

1. Yes still occurred. 
2. The icon location, from 3 icons to 2, change Display Mode (show automatic, AOE), Display Mode keybind to CAPS LOCK, override keybind text as some doesn't show proper keybind
3. I haven't played wow for the past 3-4 months and only played sporadically, but I seemed to notice this from I would say 1-2 months ago. At first I didn't know if it was because of Hekili or not and I only logged in just to chat so I sort of ignored it. Then I started playing again from a few days ago and noticed it. I believe I updated Hekili once since my absence 3-4 months ago (there was just one update recently right?) I do it from Curseforge. 
4. No it's the same. 

Since I wasn't able to copy/paste the text you requested. I uploaded it on imgur. Please see below link and let me know what the issue is. I can definitely see some lagged commands. 

https://imgur.com/a/d9Xb8Qo

**Comment by Hekili** [comment]
For 3, please download a few earlier releases and see if an earlier release makes a difference.  I can't replicate the issue on my end, so I'd need to know:

<table>
<tr>
	<td>#
	<td>Version
	<td>Result
<tr>
	<td>1.
	<td>1.0.10-alpha1
	<td>Stutters
<tr>
	<td>2.
	<td>1.0.9
	<td>Stutters
<tr>
	<td>3.
	<td>1.0.8
	<td>
<tr>
	<td>4.
	<td>1.0.7
	<td>
<tr>
	<td>5.
	<td>1.0.6
	<td>
<tr>
	<td>6.
	<td>1.0.5
	<td>
<tr>
	<td>7.
	<td>1.0.4
	<td>
<tr>
	<td>8.
	<td>1.0.3
	<td>
<tr>
	<td>9.
	<td>1.0.2
	<td>
<tr>
	<td>10.
	<td>1.0.1
	<td>
<tr>
	<td>11.
	<td>1.0.0
	<td>
</table>

If you can fill in the blanks until you find a version that doesn't stutter, that'd be great.

**Comment by Hekili** [comment]
Your numbers are very strange.  Do you have a very old CPU?

The reset process taking that long is very bizarre.

**Comment by LEOMODE** [comment]
> Your numbers are very strange. Do you have a very old CPU?
> 
> The reset process taking that long is very bizarre.

I have an Intel Xeon processor, 12 core. I'm running on a Mac Pro 2019 Boot Camp Windows 11. Ran WoW and Hekili fine ever since I bought it. 
https://ark.intel.com/content/www/us/en/ark/products/193749/intel-xeon-w3235-processor-19-25m-cache-3-30-ghz.html

I'm still checking on previous versions.

**Comment by Hekili** [comment]
We can continue to use the ticket interface.

**Comment by LEOMODE** [comment]
> We can continue to use the ticket interface.

Can I just copy paste the Hekili version and just do /reload in wow interface instead of getting out of the game and restarting the game? A bit of a hassle haha.

**Comment by Hekili** [comment]
You do not have to restart the WoW client to add/remove/update WoW addons.

**Comment by LEOMODE** [comment]
> You do not have to restart the WoW client to add/remove/update WoW addons.

ok so after replacing the Hekili version in the folder, just doing /reload should be sufficient to test that version.

**Comment by LEOMODE** [comment]
> For 3, please download a few earlier releases and see if an earlier release makes a difference. I can't replicate the issue on my end, so I'd need to know:
> 
> #	Version	Result
> 1.	1.0.10-alpha1	Stutters
> 2.	1.0.9	Stutters
> 3.	1.0.8	 Stutters
> 4.	1.0.7	 Stutters
> 5.	1.0.6	 Stutters
> 6.	1.0.5	 Stutters
> 7.	1.0.4	Stutters
> 8.	1.0.3	
> 9.	1.0.2	
> 10.	1.0.1	
> 11.	1.0.0	
> If you can fill in the blanks until you find a version that doesn't stutter, that'd be great.

I can confirm that from 1.0.3 and downwards the stutter disappears. So from 1.0.4 to 1.0.10 is where the stutter happens. Also, I cannot confirm if this is related to Hekili, and I might need further testing, but when I first /reload, the first few movements do have stutter whether I try to move left, right, straight, but it goes away after the first few moves. Just wanted to let you know if this can also be related.

**Comment by Hekili** [comment]
There were a lot of changes from 1.0.3 to 1.0.4.  In order to narrow down changes, can you try the alpha versions between 1.0.3 and 1.0.4?

Does it stutter with https://github.com/Hekili/hekili/releases/tag/v9.1.5-1.0.4-alpha1 ?  If so, I can look at changes that are in that alpha build.  If not, I'd like to pin down if the changes in alpha2, alpha3, etc. specifically trigger this issue for me.

> Also, I cannot confirm if this is related to Hekili, and I might need further testing, but when I first /reload, the first few movements do have stutter whether I try to move left, right, straight, but it goes away after the first few moves. Just wanted to let you know if this can also be related.

I don't know about this piece and you'd have to link it back to a specific version again, if it's addon related, to investigate (basically, same deal as the rest of this thread).

**Comment by LEOMODE** [comment]
It looks like from 1.0.4-Alpha4 and upwards the stutter occurs. So I'm using 1.0.4-Alpha 3 right now as it's the latest without the stutter for me. Please let me know if there is anything else you want me to test.

**Comment by Hekili** [comment]
Thanks for researching.  I might make an alpha version that'll help collect more data.

Are you playing on a private server?  When you've done each phase of testing, has that been with the addon alone or with other addons loaded?

**Comment by LEOMODE** [comment]
> 

Thanks. I just play on the US retail server. I'm not familiar with private servers. The stutter happens with other addons as well, but also, when I tested initially (when I posted this bug) I tested one add-on at a time and Hekili was the one that still caused the stutter, so I suspect that this might have nothing to do with other add-ons as prior to 1.0.4-Alpha3 Hekili worked fine even with other addons.

**Comment by LEOMODE** [comment]
> Thanks for researching. I might make an alpha version that'll help collect more data.
> 
> Are you playing on a private server? When you've done each phase of testing, has that been with the addon alone or with other addons loaded?

Would you be uploading it to the public for me to test it out, or just a separate file? We can talk in Discord if you want real-time feedback. Thanks.

**Comment by Hekili** [comment]
I'm having a hard time finding anything between those two releases that really relates to performance, but I did remove one change that might have an impact.  That'll be in today's release.  If it's still broken, let me know.  I plan to overhaul the whole update cycle soon, so if I can't find an incremental fix it'll have to wait until the overhaul.

**Comment by LEOMODE** [comment]
> I'm having a hard time finding anything between those two releases that really relates to performance, but I did remove one change that might have an impact. That'll be in today's release. If it's still broken, let me know. I plan to overhaul the whole update cycle soon, so if I can't find an incremental fix it'll have to wait until the overhaul.

Thanks just tested, but the lag is still there, so I had to revert it back. My question is, would the latest 9.2 skills that'll be added not be in the version that I have to forcibly use until the overhaul?

**Comment by Hekili** [comment]
Yes, 9.2 content/mechanics are not in earlier version of the addon.

Can you record this stutter?  Show me if it's something that happens when idling vs. combat vs. whatever?  I need more inforamtion to investigate further.

**Comment by Hekili** [comment]
Also, can you reconfirm that 1.0.4-alpha3 continues to work without stuttering, while 1.0.4-alpha4 stutters?  Thanks.

**Comment by LEOMODE** [comment]
Hey, I just tried recording and discovered something interesting. When I actually removed everything on the screen to record it for your request (Toggle User Interface), the lag was gone despite using the latest version (1.0.10). So I started disabling one add-on at a time to see if anything showing on the screen is causing this glitch, and it seemed like by disabling Details! add-on, I no longer had the glitch (1.0.10). 

However, I tried doing that with 1.0.4-alpha4 but when I disabled Details! add-on, the Hekili was also not loading despite it being checked off under the add-on list. I also tried enabling both add-ons and turned off Toggle User Interface and noticed that the lag was gone too. I did only enable Hekili by itself and tested every single version so I don't know why all of a sudden I cannot do this anymore, but I will update once I'm able to again. 

So what I'm seeing is some sort of connection between Hekili and Details! (at least for 1.0.4-alpha4 until you fixed it with 1.0.10). I don't know why Hekili is also disabled when I disable Details! add-on with 1.0.4-alpha4 but the glitch definitely seemed to stem from add-ons that are visible on the screen. I have no idea why I cannot enable Hekili even by itself when I disabled all add-ons. 

Also FYI, by disabling Hekili and enabling Details! do not cause any glitches.

**Comment by Hekili** [comment]
Do you also have WeakAuras loaded?

**Comment by LEOMODE** [comment]
> Do you also have WeakAuras loaded?

Yes I do.

**Comment by Hekili** [comment]
So, here are the scenarios to test (and confirm which version(s) you test for each of these.  Disable all other addons during the testing or the results are not useful.

Copy and paste for each version of Hekili that you test:
```
Hekili version:  
For each of the following, answer:  Does it stutter? (Y/N)
1.  Hekili alone:  
2.  Hekili + Details:  
3.  Hekili + WeakAuras:  
    a.  If it does _not_ stutter, try:  /run WeakAuras.ScanEvents( "HEKILI_RECOMMENDATION_UPDATE" )
        and note if that immediately causes a stutter.  Result:  
4.  Hekili + Details + WeakAuras:  
    a.  If it does _not_ stutter, try:  /run WeakAuras.ScanEvents( "HEKILI_RECOMMENDATION_UPDATE" )
        and note if that immediately causes a stutter.  Result:  
```

**Comment by LEOMODE** [comment]
I don't know what's going on but I can't seem to have Hekili activated. I literally did the same thing as before just by copying/pasting your release folder and dump it under Interface folder and name the folder as Hekili.


Update: for some reason it's not working on my Druid. I can do it on my other character (all level 60).

**Comment by Hekili** [comment]
That would not have been the right approach.  Go to Releases and download the packaged file for each version you're testing -- the packaged file includes other libraries used by the addon -- and unpack it so the Hekili folder is in Interface/AddOns.

https://github.com/Hekili/hekili/releases/

The first zip file under Assets for each release is the correct file.

**Comment by LEOMODE** [comment]
> That would not have been the right approach. Go to Releases and download the packaged file for each version you're testing -- the packaged file includes other libraries used by the addon -- and unpack it so the Hekili folder is in Interface/AddOns.
> 
> https://github.com/Hekili/hekili/releases/
> 
> The first zip file under Assets for each release is the correct file.

I think we're talking the same thing. I did go to Releases -> Click on the version I want to download -> Code -> Download ZIP. Then I extracted the ZIP and put them under Interface/AddOns folder.

**Comment by Hekili** [comment]
"Code" is not the packaged file.  Use the top link under the release.

![image](https://user-images.githubusercontent.com/9438134/154330003-f7f9262e-e083-49f5-abbc-5c286c62e683.png)

[Hekili-v9.1.5-1.0.10.zip](https://github.com/Hekili/hekili/releases/download/v9.1.5-1.0.10/Hekili-v9.1.5-1.0.10.zip) = the whole package; my addon's code plus all the required libraries pulled in from other projects.  Use this.

[Source code (zip)](https://github.com/Hekili/hekili/archive/refs/tags/v9.1.5-1.0.10.zip) = just the addon code, none of the other libraries required from other projects.  Don't use this.

**Comment by SpatenLa** [comment]
![grafik](https://user-images.githubusercontent.com/39881841/154330325-f8e767ea-cdcd-430a-aa96-77aa7fbb23c2.png)

**Comment by LEOMODE** [comment]
Thanks both, let me try and get back to you soon. It is now working with just Hekili by itself.

**Comment by LEOMODE** [comment]
Ok, first off, I think I may have to correct myself because when I disabled Details!, it seems like Hekili was also turned off due to me downloading wrong ZIP files (but I'm sure I downloaded the correct one when I first created this post, sorry as I downloaded them again and tested and gave you the confusion), thus not causing any stutter. As a result, with my testing below using the correct Addon folder I downloaded under Assets, I'm seeing the original comment I made in this thread. 

**1.0.10 - All Yes, so 3.a & 4.a couldn't be applied. 
1.0.4-alpha 4 - All Yes, so 3.a & 4.a couldn't be applied.
1.0.4-alpha 3 - All No including 3.a & 4.a**

1.  Hekili alone:  
2.  Hekili + Details:  
3.  Hekili + WeakAuras: 
    a.  If it does _not_ stutter, try:  /run WeakAuras.ScanEvents( "HEKILI_RECOMMENDATION_UPDATE" )
        and note if that immediately causes a stutter.  Result:  
4.  Hekili + Details + WeakAuras:  
    a.  If it does _not_ stutter, try:  /run WeakAuras.ScanEvents( "HEKILI_RECOMMENDATION_UPDATE" )
        and note if that immediately causes a stutter.  Result:  

Based on this, my original comment stands, with a new finding that when I disable everything on the screen (Toggle User Interface) and the screen is free of all the texts/icons, the stutter is gone regardless which version I'm using. I currently have 2 icons showing for Hekili and I wonder if the screen showing is causing the stutter.

**Comment by Hekili** [comment]
That brings us back to the recording then.  Did you make one?

**Comment by LEOMODE** [comment]
> That brings us back to the recording then. Did you make one?

https://youtu.be/L53mZzPCPfY

Showing both with the Toggle User Interface on and off. when off the stutter is gone.

**Comment by Hekili** [comment]
Probably didn't need to be a youtube video, but ok.

The UI toggle isn't anything that helps resolve anything.  The more interesting comparison is 1.0.4-alpha3 vs. more recent versions.

CTRL+R to show your frame rate the whole time would be helpful.

It'd be helpful to know if you experience the issue with the addon paused (SHIFT-ALT-P by default).

**Comment by LEOMODE** [comment]
> 

Sorry didn't know how else I can make a video to post it (but this is unlisted so noone can see it unless you have the link. I can make it private after this fix also). Video is re-uploaded with your request (CTRL+R and SHIFT+ALT+P). As you can see there is a noticeable 10~fps drop when stutters and when you disable the add-on, the stutter is not there. 

https://youtu.be/JPdKb6hwQMs

**Comment by LEOMODE** [comment]
> Probably didn't need to be a youtube video, but ok.
> 
> The UI toggle isn't anything that helps resolve anything. The more interesting comparison is 1.0.4-alpha3 vs. more recent versions.
> 
> CTRL+R to show your frame rate the whole time would be helpful.
> 
> It'd be helpful to know if you experience the issue with the addon paused (SHIFT-ALT-P by default).

Any update after seeing the video?

**Comment by Hekili** [comment]
Not yet.  I'll post when there's more to look at.  Thanks!

**Comment by Hekili** [comment]
Oh, somehow we got this far without me getting a snapshot of the addon's decision-making.

Can you hit Pause (SHIFT-ALT-P by default), then go to `/hekili` > Snapshots > Primary > 1, copy and paste to Pastebin and link here?  Thanks!

**Comment by Hekili** [comment]
I'm releasing a 9.2 alpha now.  It should be fine to use on 9.1.5, but you could test in either live or PTR.  Can you take a look?

Info:  https://github.com/Hekili/hekili/releases/v9.2.0-1.0.0-alpha1
Download:  https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.0-alpha1/Hekili-v9.2.0-1.0.0-alpha1.zip

**Comment by LEOMODE** [comment]
> Oh, somehow we got this far without me getting a snapshot of the addon's decision-making.
> 
> Can you hit Pause (SHIFT-ALT-P by default), then go to `/hekili` > Snapshots > Primary > 1, copy and paste to Pastebin and link here? Thanks!

https://pastebin.com/bFT38nUS

I will also try with your new alpha add-on and see if this works now.

**Comment by LEOMODE** [comment]
> I'm releasing a 9.2 alpha now. It should be fine to use on 9.1.5, but you could test in either live or PTR. Can you take a look?
> 
> Info: https://github.com/Hekili/hekili/releases/v9.2.0-1.0.0-alpha1 Download: https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.0-alpha1/Hekili-v9.2.0-1.0.0-alpha1.zip

Ok the latest version, the stutter exists but it's not consistent. It's more sporadic in various different intervals vs every 2-3 secs on previous versions for instance (the interval seems much longer based on my testing right now).

**Comment by Hekili** [comment]
Thanks for checking.  I've gone ahead and made the underlying changes to the addon's decision-making process in https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.0-alpha3/Hekili-v9.2.0-1.0.0-alpha3.zip.

Unless there is some other interaction that is causing spiky CPU usage, the process of updating recommendations should no longer spike under the vast majority of circumstances.

**edit**:  Updated to alpha3, resolved a bug in alpha2.

**Comment by Hekili** [comment]
Closing; a new thread will be needed for performance reports post-9.2.
