### ISSUE TITLE
[BUG] Every 2 sec graphic stutters

### ISSUE THREAD

**Issue by LEOMODE** [Hekili/hekili#1337]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Every 2 sec, there is a 1-second graphic stutter that kind of stops whether I'm fighting, walking, running, or flying. I disabled all add-ons and validated one add-on at a time and this add-on caused the stutter.

Note: It doesn't matter which level you are at, whether you are at max level or low level. Before I believe 2-4 months ago this never happened regardless of any levels. 

### How to Reproduce

1. Enter the game with any characters.
2. Try to fight/walk/run/fly.

### Player Information (Link)

https://pastebin.com/pydmJKZk

### Error Messages (Link)

https://pastebin.com/59zRCTp2

### Additional Information

Note I do not see any error messages regarding Hekili.

**Comment by Hekili** [comment]
You don't have to create a new ticket, you already have the other one that I closed.

Honestly, I don't have this experience with a 2 second stutter and what you've provided won't help investigate it.  I'll reopen the previous ticket to invite people to post if they're having similar experiences.
