### ISSUE TITLE
[REC] Spellflash flashes up to four abilities at the same time

### ISSUE THREAD

**Issue by HumanMakro** [Hekili/hekili#1338]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi,

I am using the integrated spellflash functionality.

Abilities flashed by spellflash seem to stay highlighted for about a second or a little bit longer after beeing used.

This leeds up to four flashed abilities (cooldown, trinket, two normal abilities) at the same time, which is very confusing.

My expectation was that only one ability should be highlighted at the same time.

![grafik](https://user-images.githubusercontent.com/27286566/151852759-61e36624-aeea-4c7b-a66d-601fefad4cca.png)

### How to Reproduce

1. use the most recommended ability
2. wait for the coodown to finish
3. watch the recommendation switch back to the prior ability
4. for about a second both abilities should be flashed at the same time

### Snapshot (Link)

https://pastebin.com/gmJHD90Y

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/84qaCm3mae2u72Kf7r15Ch

### Additional Information

the recommendations seem to be fine ... just the flashing is bugged

by the way, I love your addon an recommended it to to a lot of struggeling players.

**Comment by Hekili** [comment]
I've added code that will force a display's previous flash(es) to immediately fade when recommendations changed.  This will be in today's release.

Thanks!
