### ISSUE TITLE
8.1.5-16 Demon Hunter Demon's Bite

### ISSUE THREAD

**Issue by pollixx** [Hekili/hekili#134]
Updated to the latest build 8.1.5-16 and proceeded to do an Atal'Dazar +11 key. The whole dungeon, Hekili would only give me the options for Immolation Aura, Eye Beam, and Demon's Bite. If Immolation Aura and Eye Beam were on cooldown, my only rotation options with Hekili was Demon's Bite. That's it.

**Comment by Hekili** [comment]
Sorry, I always feel especially bad when the addon is giving problems in a timed key.  

In the future, please be sure to include information laid out in the ticket so I know your talents/azerite/etc.  This impacts the testing I'm able to do.

Regardless, this should be fixed with #131 in a moment.

**Comment by pollixx** [comment]
Apologies. This was my first bug report. I'll make sure to follow the directions if I need to write a bug report in the future.
