### ISSUE TITLE
[BUG] Flame shock default tick duration set to 3 seconds, should be 2. 

### ISSUE THREAD

**Issue by elsavira** [Hekili/hekili#1343]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![image](https://user-images.githubusercontent.com/22588626/152653497-406d80b7-03be-4562-a797-8fbe14309204.png)
![image](https://user-images.githubusercontent.com/22588626/152653502-0fe59628-79b3-4e3a-b464-646f09d59ceb.png)

The default Dot-tick-time for Flame shock is incorrectly set to 3 seconds. 

### How to Reproduce

1. Spec Elemental Shaman
2. Apply Flame Shock
3. Check Internal values

### Player Information (Link)

https://pastebin.com/Eaaejhki

### Error Messages (Link)

-

### Additional Information

Line 923 in ShamanElemental.lua shows the following:

    min_ttd = function () return debuff.flame_shock.duration / 3 end

I believe this should be 2.

The same also for line 198:

    tick_time = function () return 3 * haste end,

### Contact Information

Elsavira#2556

**Comment by Hekili** [comment]
That `min_ttd` value is not relevant to the tick time.

The `tick_time` is; I'm correcting it now.  Thanks.
