### ISSUE TITLE
Masque settings not saving for Hekili

### ISSUE THREAD

**Issue by blecaplol** [Hekili/hekili#1345]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The issue from here where u closed it i dont even know if its the correct category and will be my last time reporting it.
https://github.com/Hekili/hekili/issues/1344#issuecomment-1031049031

I said I used the latest version I keep them updated not just your addon. **v9.1.5-1.0.9**

Masque said is your issue and you said its their issue then what i do? Blame it on the president?  Again Im just reporting a bug to both of you if yall wanna push the blame i dont care. Lol. U can close now if u want.

### How to Reproduce

The skin will not stay and I delete both addons saved variables.

I click enable twice on the addon on the minimap not a /reload and it got skinned but it is not persistent on /reload or entering the world, or loading into anotehr instance anything that invoke a loading screen.

### Player Information (Link)

none

### Error Messages (Link)

none

**Comment by Hekili** [comment]
Did you not actually read what I wrote? I explained how to determine which addon is the source of the issue. 

I also asked you to fill the ticket out completely, so the missing Player Information confuses me. 

> Masque said is your issue and you said its their issue then what i do? Blame it on the president? Again Im just reporting a bug to both of you if yall wanna push the blame i dont care. Lol. U can close now if u want.

This is really inappropriate. First, that's not what I said. Second, it's combative. 

If you want to supply the missing information and test earlier versions of this addon, like I described, that'd be useful info. If not, let me know and I'll close the ticket and wait for a complete report. Thanks.

**Comment by Hekili** [comment]
I'm not able to replicate this issue.

**Comment by StormFX** [comment]
A bit late to the party here, but to clarify: I stated if a series of other solutions didn't work, it _may_ be Hekili's implementation. That said, after testing it, I was also unable to reproduce the issue. It seems to one of those rare cases where saved variables don't work properly, whether a file system glitch, exiting the game incorrectly or who knows. It does seem to crop up on occasion (like once/year).

**Comment by Hekili** [comment]
Thanks for letitng me know!
