### ISSUE TITLE
Hekili auto snapshots quite often as BM

### ISSUE THREAD

**Issue by cdc1287** [Hekili/hekili#1346]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Playing BM for WQ, often get the snapshot message. Usually only have 1 icon in the queue when it happens. Tends to resolve itself instantly.

### How to Reproduce

Appears random when in combat.

### Player Information (Link)

https://pastebin.com/W5diER17

### Error Messages (Link)

No BugSack errors

### Additional Information

Snapshot 1: https://pastebin.com/2AtPDk6K

Snapshot 2: https://pastebin.com/9YLr2Rva

**Comment by Hekili** [comment]
Does it resolve if you disable "check pet range"?

**Comment by cdc1287** [comment]
I will give it a go and feedback. Thanks for the reply!

**Comment by cdc1287** [comment]
I have not had that issue appear since disabling 'check pet range'. I will let you know if it happens again.

Thanks!

**Comment by Hekili** [comment]
Great, I also have a solution planned so you can still use Check Pet Range, but that the priority will recover and use other abilities when it currently gives up.

**Comment by cdc1287** [comment]
Amazing. Thank you for creating this wonderful addon!

**Comment by Hekili** [comment]
This is addressed in the latest releases.  Thanks!
