### ISSUE TITLE
[BUG] LuA error on login

### ISSUE THREAD

**Issue by jamcdani** [Hekili/hekili#1349]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Once I log into my toon, and the addon loads, i immediately receive a LuA error that continues to happen then cleared or reloaded. This is happening on all toons and specs. looks like it is running into errors with other addons, but haven't had this issue before the update to Hekili today. Including Error Text below

 Message: Interface\AddOns\Hekili\UI.lua:1259: attempt to index global 'b' (a nil value)
Time: Mon Feb 21 13:20:58 2022
Count: 2933
Stack: Interface\AddOns\Hekili\UI.lua:1259: attempt to index global 'b' (a nil value)
[string "@Interface\AddOns\WagoAnalytics\WagoAnalytics.lua"]:72: in function <Interface\AddOns\WagoAnalytics\WagoAnalytics.lua:70>
[string "=[C]"]: ?
[string "@Interface\AddOns\Hekili\UI.lua"]:1259: in function <Interface\AddOns\Hekili\UI.lua:865>

Locals: err = "Interface\AddOns\Hekili\UI.lua:1259: attempt to index global 'b' (a nil value)"
ok = true
innerError = nil
handleError = <function> defined @Interface\AddOns\WagoAnalytics\WagoAnalytics.lua:43
oldErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

### How to Reproduce

Log in to world of warcarft
select a toon
error received 

### Player Information (Link)

https://pastebin.com/Csj4z3m1

### Error Messages (Link)

https://pastebin.com/ZP47DDnJ

### Contact Information

Virenna#5764

**Comment by Hekili** [comment]
Thanks; I have a fix incoming.
