### ISSUE TITLE
8.1.5-16 Outlaw Rogue

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#135]
As of last update often doesn't suggest anything at all, Or at random displays only 2 or 3 icons. The whole rotation seems to be messed up, Often only suggesting Sinister Strike.

Pretty much all the same issues as:

#134 
#133 
#132 
#131

**Comment by ghost** [comment]
Currently using Hekili-v8.1.5-15 again and no problems whatsoever.

**Comment by Hekili** [comment]
Yes, this is the same issue as #131, fix is pending.
