### ISSUE TITLE
Hekili rotation wont load on any characters

### ISSUE THREAD

**Issue by mertslam** [Hekili/hekili#1350]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

the rotation boxes for Hekili arent showing up
![Uploading image.png…]()

### How to Reproduce

enter game as any character
100% reproduction rate

### Player Information (Link)

build: v9.1.5-1.0.10 level: 60 (60) class: WARLOCK spec: demonology  talents: dark_pact     demonic_calling     demonic_consumption     dreadlash     grimoire_felguard     mortal_coil     summon_vilefiend  pvptalents: none  covenant: night_fae  conduits: borne_of_blood = 11    carnivorous_stalkers = 11    condensed_anima_sphere = 11    demonic_momentum = 11    resolute_barrier = 11    tyrants_soul = 11  soulbinds: [dreamweaver]    dream_delver = 1    field_of_blossoms = 1    podtender = 1    somnambulist = 1    soothing_voice = 1    waking_dreams = 1  sets: soulletting_ruby = 1  gear: bilgewater_cartel_tabard = 1     desecrators_keening_wristwraps = 1     drape_of_twisted_loyalties = 1     embroidered_shirt = 1     forlorn_prisoners_strap = 1     grasps_of_the_clairvoyant_sage = 1     interplanar_keystone = 1     maledict_opus = 1     mantle_of_arthuras_chosen = 1     phantasmaforged_striders = 1     sacrificers_sacramental_cassock = 1     shadowghast_ring = 1     sorcerers_headlong_legwraps = 1     soulletting_ruby = 1     sworn_oath_of_the_nine = 1     titanic_ocular_gland = 1     veil_of_the_banshee_queen = 1  legendaries: wilfreds_sigil_of_superior_summoning = 1  itemIDs: 167192, 178809, 178926, 180123, 186281, 186282, 186285, 186286, 186288, 186290, 186321, 186325, 186356, 186379, 186406, 186423, 64884  settings: aoe = 2     buffPadding = 0     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = false     enhancedRecheck = false     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 8     nameplates = true     package = Demonology     petbased = false     potion = spectral_intellect     potionsReset = 20180919.1     throttleRefresh = false     throttleTime = false  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true      essences = true      interrupts = true      mode = automatic      potions = false   keybinds:      axe_toss              = 9   [01]     blood_fury            = 7   [01]     call_dreadstalkers    = 3   [01]     demonbolt             = 4   [01]     grimoire_felguard     = 6   [01]     hand_of_guldan        = 1   [01]     implosion             = 5   [01]     shadow_bolt           = 2   [01]     soul_rot              = 0   [01]     soulletting_ruby      = -   [01]     summon_demonic_tyrant = 8   [01]     summon_vilefiend      = =   [01]

### Error Messages (Link)

6x Warlockbox\main.lua:58: attempt to call method 'SetBackdrop' (a nil value) [string "@Warlockbox\main.lua"]:58: in main chunk  Locals: alreadyRegistered = false demonCount = 0 empowered_demonCount = 0 lastEnpowermentCast = 0 petActive = 0 petEmpowered = 0 playerGUID = nil CurrentDemon = "Succubus" EmpowermentTimeLeft = 0 EmpowermentcastingTime = 1.500000 DemonicTable = <table> {  417 = "Felhunter"  17252 = "Felguard"  1863 = "Succubus"  416 = "Imp"  99737 = "Wild Imp"  55659 = "Wild Imp"  58960 = "Voidwalker"  1860 = "Voidwalker"  58965 = "Wrathguard"  98035 = "Dreadstalker"  120526 = "Succubus"  120527 = "Succubus"  58964 = "Observer"  58963 = "Shivarra"  58959 = "Imp"  11859 = "Doomguard"  89 = "Infernal" } ShowWindow = <function> defined @Warlockbox\main.lua:41 WarlockboxGUI = WarlockboxGUI {  0 = <userdata> } (*temporary) = nil (*temporary) = WarlockboxGUI {  0 = <userdata> } (*temporary) = <table> {  bgFile = "dialogframe\ui-dialogbox-background-dark"  tileSize = 32  edgeFile = "tooltips\UI-tooltip-Border"  tile = true  edgeSize = 8  insets = <table> {  } } (*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"

### Contact Information

mertslam#4037

**Comment by Hekili** [comment]
Please follow the directions and paste error messages to Pastebin and then provide the link here (it helps for readability).

The error(s) you provided here are from something called "Warlockbox" and not my addon.  Clear your BugSack, reload your UI, and then retrieve the first error message that references my addon.  Paste that on Pastebin and then provide a link here.

You can also look at /hekili > [specialization] and check that "Enabled" is checked.

![image](https://user-images.githubusercontent.com/9438134/155255957-21b92b92-da5b-4a97-a2b6-5c04f020cd8e.png)

**Comment by Hekili** [comment]
(But also upgrade to the new release that is posted now.)

**Comment by Hekili** [comment]
Reopen if this is still occurring with the latest release(s).
