### ISSUE TITLE
[BUG] State.lua:6768: attempt to perform arithmetic on field '?' (a nil value)

### ISSUE THREAD

**Issue by Roo212** [Hekili/hekili#1351]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Getting Lua errors stating arithmetic is nil

### How to Reproduce

I tried the steps and could not repeat the errors on DH or on any other toon.

### Player Information (Link)

build: v9.2.0-1.0.1 level: 60 (60) class: WARLOCK spec: destruction  talents: cataclysm     dark_pact     dark_soul_instability     flashover     mortal_coil     reverse_entropy     roaring_blaze  pvptalents: none  covenant: necrolord  conduits: accrued_vitality = 9    ashen_remains = 9    condensed_anima_sphere = 9    duplicitous_havoc = 9    fatal_decimation = 9    resolute_barrier = 9  soulbinds: [plague_deviser_marileth]    kevins_keyring = 1    kevins_oozeling = 1    oozs_frictionless_coating = 1    ultimate_form = 1    viscous_trail = 1    volatile_solvent = 1  sets: none  gear: antecedent_drape = 1     choral_slippers = 1     death_gods_signet = 1     grimveiled_hood = 1     impossibly_oversized_mitts = 1     korthian_caretakers_cinch = 1     korthian_caretakers_kris = 1     korthian_caretakers_mantle = 1     korthian_caretakers_orb = 1     korthian_caretakers_robes = 1     korthian_scholars_signet = 1     muehzalas_hexthread_sarong = 1     soul_cage_fragment = 1     temporal_oracular_wrists = 1     unbound_changeling = 1     undisputed_champions_shirt = 1     unfathomable_pendant = 1  legendaries: madness_of_the_azjaqir = 1  itemIDs: 173245, 178708, 179351, 179355, 183022, 185855, 185860, 185888, 185890, 185941, 186670, 187447, 188007, 188054, 188106, 190753, 98082  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 33     nameplateRange = 8     nameplates = false     package = Destruction     petbased = false     potion = spectral_intellect     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true      essences = true      interrupts = true      mode = automatic      potions = false   keybinds:      bane_of_havoc                 = -   [01]     casting_circle                = S-  [06]     cataclysm                     = 5   [01]     chaos_bolt                    = 4   [01]     conflagrate                   = 2   [01], 1   [08]     corruption                    = =   [01]     create_soulwell               = A2  [03]     curse_of_exhaustion           = A-  [03]     curse_of_tongues              = S0  [06]     curse_of_weakness             = A0  [03]     dark_soul_instability         = S4  [06]     decimating_bolt               = 0   [01]     demon_armor                   = S6  [06]     demonic_circle                = A1  [03]     demonic_circle_teleport       = A4  [03]     demonic_gateway               = A9  [03]     devour_magic                  = S3  [06]     drain_life                    = S7  [06]     fear                          = 8   [01], 3   [02]     fleshcraft                    = A=  [03]     gladiators_medallion          = C=  [04]     havoc                         = -   [01]     health_funnel                 = S9  [06]     healthstone                   = C7  [04]     immolate                      = 3   [01]     incinerate                    = 1   [01]     mortal_coil                   = 7   [01]     rain_of_fire                  = S2  [06]     ritual_of_summoning           = A3  [03]     shadowfury                    = 9   [01]     summon_infernal               = 6   [01]     unchained_gladiators_shackles = C-  [04]     unending_resolve              = S8  [06]

### Error Messages (Link)

227x Hekili\UI.lua:1057: Hekili\State.lua:6768: attempt to perform arithmetic on field '?' (a nil value) [string "=[C]"]: in function `error' [string "@Hekili\UI.lua"]:1057: in function <Hekili\UI.lua:865>  Locals: (*temporary) = "Hekili\State.lua:6768: attempt to perform arithmetic on field '?' (a nil value)"

### Contact Information

https://discord.gg/MAfT4Ey3

**Comment by Hekili** [comment]
Thanks for the report.  v9.2.0-1.0.2-alpha1 will be available (http://github.com/Hekili/hekili/releases) in a few minutes.  It should resolve this error.  Thanks!

**Comment by Lerzan** [comment]
Having a similar issue, also as destruction 

Character Data
build: v9.2.0-1.0.1
level: 60 (60)
class: WARLOCK
spec: destruction

talents: cataclysm
    dark_soul_instability
    demon_skin
    flashover
    mortal_coil
    roaring_blaze
    shadowburn

pvptalents: none

covenant: necrolord

conduits: accrued_vitality = 5
   ashen_remains = 5
   condensed_anima_sphere = 5
   fatal_decimation = 5
   infernal_brand = 5
   kilroggs_cunning = 5

soulbinds: [plague_deviser_marileth]
   kevins_oozeling = 1
   oozs_frictionless_coating = 1
   plagueborn_cleansing_slime = 1
   ultimate_form = 1
   undulating_maneuvers = 1
   volatile_solvent = 1

sets: none

gear: abandoned_automa_loop = 1
    antecedent_drape = 1
    choral_amice = 1
    choral_handwraps = 1
    choral_leggings = 1
    choral_slippers = 1
    choral_vestments = 1
    choral_wraps = 1
    extract_of_prodigious_sands = 1
    flowing_sandbenders_staff = 1
    impossibly_ancient_band = 1
    oracular_hood = 1
    oracular_sash = 1
    symbol_of_the_raptora = 1
    tabard_of_the_explorer = 1
    unfathomable_pendant = 1

legendaries: none

itemIDs: 188006, 188007, 188008, 188010, 188012, 188037, 188053, 188054, 188055, 188106, 190045, 190344, 190347, 190602, 190726, 43348

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Destruction
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = single 
    potions = false 

keybinds: 
    arcane_torrent          = CN9 [05]
    bane_of_havoc           = N2  [06]
    cataclysm               = N6  [06]
    channel_demonfire       = S2  [01]
    chaos_bolt              = 4   [01]
    conflagrate             = 3   [01]
    corruption              = S1  [01]
    curse_of_exhaustion     = N9  [06]
    curse_of_tongues        = C9  [02]
    curse_of_weakness       = C6  [02]
    dark_soul_instability   = CN3 [05]
    decimating_bolt         = N1  [06]
    demonic_circle_teleport = C3  [02]
    drain_life              = N3  [06]
    fear                    = N4  [06]
    fel_domination          = C7  [02]
    flame_of_battle         = CN2 [05]
    fleshcraft              = C2  [02]
    havoc                   = N2  [06]
    health_funnel           = C4  [02]
    healthstone             = N0  [06]
    immolate                = 1   [01]
    incinerate              = 2   [01]
    mortal_coil             = CN7 [05]
    rain_of_fire            = N5  [06]
    shadowburn              = MwD [01]
    shadowfury              = C5  [02]
    summon_infernal         = CN6 [05]
    unending_resolve        = C1  [02]

Error Message
Update: Interface\AddOns\Hekili\State.lua:6768: attempt to perform arithmetic on field '?' (a nil value)

[string "@Interface\AddOns\Hekili\UI.lua"]:1056: in function <Interface\AddOns\Hekili\UI.lua:865>



Currently using the alpha linked above, recommendations will freeze or not go away when used.

**Comment by Hekili** [comment]
Your report doesn't show you using the alpha version.

The latest (alpha3) should address this completely.
