### ISSUE TITLE
[BUG] Error shown in UI.lua:1057 State.lua:5861

### ISSUE THREAD

**Issue by VitalijSelynin** [Hekili/hekili#1352]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Version: v9.2.0-1.0.2-alpha1

Error occurs after log-in or infight.
Other, not up to date addons are disabled.
After the lua error occurs infight, rotation suggestions are not working anymore.

### How to Reproduce

1. Enter Game
2. Error shown
3. Creation of error during fight: start fight
4. Cast 2-3 spells
5. Error is shown and rotation is not properly updated

### Player Information (Link)

https://pastebin.com/WLTaB0tT

### Error Messages (Link)

https://pastebin.com/fxp2GRap

**Comment by Hekili** [comment]
Thanks; incoming fix in alpha2.

**Comment by VitalijSelynin** [comment]
Thank you for the quick response, tested with alpha2, a "new error" occurred 
https://pastebin.com/4p100Nn1

Result: Hekili is not shown at all after startup and during fights.

**Comment by Hekili** [comment]
Thanks for the fast report back.  Should be resolved in alpha3.

**Comment by VitalijSelynin** [comment]
Tested alpha 3 on 4 mobs, no additional issues occurred. Thank you for the fast response!
