### ISSUE TITLE
[BUG] Primary rotation get "stuck" for Destro. 

### ISSUE THREAD

**Issue by lowendahl** [Hekili/hekili#1353]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Rotation works as intended first 3-4 actions then it get "stuck" and do not update recommendations for a while. Sporadically it "resets" and fixes it self.

### How to Reproduce

1. Start combat as Destro warlock
2. Run combat

### Player Information (Link)

https://pastebin.com/rSHvCW96

### Error Messages (Link)

https://pastebin.com/rsVtrDbu

### Contact Information

Threval#2718

**Comment by Hekili** [comment]
This is resolved in https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.2-alpha3/Hekili-v9.2.0-1.0.2-alpha3.zip.

**Comment by lowendahl** [comment]
Works for demo och ele shaman

**Comment by lowendahl** [comment]
ah - thanks.
