### ISSUE TITLE
[BUG] Doesnt seem snapshot is working for me? 

### ISSUE THREAD

**Issue by Twizzerious** [Hekili/hekili#1354]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am trying to grab some snapshots of a suspected priority bug/recommendation bug but anytime I press my snapshot keybind, It doesnt seem to save a snapshot?

I get the chat message that hekili saved a snap shot but when I go to the snapshot tabs in Hekili, there is nothing to save or copy. Dont know what other information you would want. Let me know

Not getting a buggrabber bug either

![image](https://user-images.githubusercontent.com/12769454/155445266-8a3479f0-35f3-4ba0-9245-177a7175cae2.png)
![image](https://user-images.githubusercontent.com/12769454/155445341-13063421-b9df-4507-ad46-bd2f150522d8.png)
![image](https://user-images.githubusercontent.com/12769454/155445370-71d25edf-51b1-4100-b7f1-d83a74becc89.png)

### How to Reproduce

Enter game
Press your snapshot keybind to produce a snapshot
Snapshot doesnt seem to save in snapshot tab?

### Player Information (Link)

https://pastebin.com/XbqC1iej

### Error Messages (Link)

https://pastebin.com/11h9Pewa

### Additional Information

dont think paste bin for error message is relevant but its required for bug report?

### Contact Information

Twizz#2915

**Comment by Hekili** [comment]
Pick the display first, then the snapshot #.  Does that work?

**Comment by Twizzerious** [comment]
It worked. Forgive me for my plebness.
