### ISSUE TITLE
Suggesting only Multi-Shot and ignoring everything else for MM Hunter aoe rotation

### ISSUE THREAD

**Issue by titorrrr** [Hekili/hekili#1355]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Everytime I pull a 3+ mob pack, the addon automatically suggests Multi-Shot. I can see the next suggested spell, but when I use multi-shot, it never leaves the first position of the list, completely ignoring the Trick Shots effects (and everything else actually). The only thing that seems to have a higher priority is Explosive Shot when off cooldown.

### How to Reproduce

1. Enter the game as an MM Hunter, with the default M+ build
2. I tested it with Night Fae
3. Try to run an M+ or even test it with the Swarm Training Dummies at the Heart of The Forest.
4. You'll see the addon will keep suggesting Multi-Shot forever, only changing when Explosive Shot is up, or suggesting Steady Shot if there's no focus. It never suggests Aimed Shot or Rapid Fire after Multi-Shot.

### Snapshot (Link)

https://pastebin.com/KWF88y7X

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wr8mMoVkuho3Lc7thq2b7X

### Contact Information

Uldog#5957

**Comment by Hekili** [comment]
Update to the latest version and confirm the problem still occurs.

**Comment by titorrrr** [comment]
Unfortunately it does :(

I don't think the addon is tracking the Trick Shots buff correctly.

I've found another issue from 2020 that seems very similar: https://github.com/Hekili/hekili/issues/637

**Comment by Hekili** [comment]
Thanks, I've found the underlying cause and you are on the right track.

When v9.2.0-1.0.3-alpha1 is posted here -- [github.com/Hekili/hekili/releases/v](https://github.com/Hekili/hekili/releases/tag/v9.2.0-1.0.3-alpha1) -- give it a try and let me know if it is resolved.  Thanks!

**Comment by cdc1287** [comment]
Hello I had the same issue and 9.2.0-1.0.3-alpha1 has resolved it. Thanks!

**Comment by titorrrr** [comment]
It worked! Thank you SO much! You're awesome, really :)
