### ISSUE TITLE
[BUG] Feral/Guardian spec not showing any recommendations

### ISSUE THREAD

**Issue by GauntletFTW** [Hekili/hekili#1357]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon is not showing any recommendations for my feral+guardian spec, balance druid working as expected, as well as other class seem to work fine. Clean install of the addon. Tried both latest release version on curseforge, as well as Alpha (v9.2.0-1.0.2).

Bugsack did not show any errors whatsoever. Also whenever I press the Snapshot key it does not seem to save one for Feral/Guardian.

### How to Reproduce

Log in as Druid.
Set spec to Guardian or Feral.
See no recommendations.
Set spec to Balance.
See correct recommendations.

### Player Information (Link)

build: v9.2.0-1.0.2 level: 60 (60) class: DRUID spec: feral  talents: balance_affinity     bloodtalons     heart_of_the_wild     predator     primal_wrath     soul_of_the_forest     tiger_dash  pvptalents: none  covenant: night_fae  conduits: conflux_of_elements = 5    front_of_the_pack = 6    taste_for_blood = 4    wellhoned_instincts = 5  soulbinds: [niya]    grove_invigoration = 1    niyas_tools_poison = 1    run_without_tiring = 1    swift_patrol = 1  sets: dreadfire_vessel = 1     inscrutable_quantum_device = 1  gear: charm_of_eternal_winter = 1     chiropteran_leggings = 1     crest_of_the_legionnaire_general = 1     dreadfire_vessel = 1     gargontamers_spear = 1     gloves_of_phantom_shadows = 1     heedless_pugilists_harness = 1     hood_of_refracted_shadows = 1     hyperlight_band = 1     inscrutable_quantum_device = 1     miasmalacquered_jerkin = 1     precisely_calibrated_chronometer = 1     shadowghast_ring = 1     sinsoaked_waders = 1     wicked_flankers_gorget = 1  legendaries: circle_of_life_and_death = 1  itemIDs: 178817, 178837, 178926, 179350, 179527, 182993, 183005, 183009, 183019, 183026, 183029, 183032, 183038, 183040, 184030  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = false     enhancedRecheck = false     gcdSync = true     maxTime = 33     nameplateRange = 8     nameplates = true     package = Feral     petbased = false     potion = spectral_agility     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     owlweave_cat = false  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true      essences = false      interrupts = false      mode = single      potions = false   keybinds:      barkskin              = CF  [03]     bear_form             = F1  [06]     berserk               = R   [05]     brutal_slash          = 5   [01], 5   [07], 5   [08], 5   [09]     cat_form              = F2  [06]     convoke_the_spirits   = 7   [05]     cyclone               = B   [05]     dreadfire_vessel      = 9   [03]     entangling_roots      = SX  [03], X   [05]     feral_frenzy          = 8   [03]     ferocious_bite        = 2   [01], 2   [07], 2   [08]     frenzied_regeneration = 6   [09]     growl                 = Q   [09]     healthstone           = SZ  [03]     heart_of_the_wild     = C   [05]     hibernate             = 6   [01], F4  [06]     incapacitating_roar   = 3   [09]     ironfur               = F   [09]     maim                  = V   [05]     mangle                = `   [09]     moonfire              = 4   [01], 1   [09], A2  [10]     moonkin_form          = F3  [06]     potion                = C4  [06]     primal_wrath          = 6   [01], 6   [07]     prowl                 = G   [01], G   [07], G   [08], G   [09]     rake                  = `   [01], `   [07], `   [08]     rebirth               = C1  [05]     regrowth              = T   [05]     remove_corruption     = CQ  [03], C3  [06]     revive                = C2  [06]     rip                   = 3   [01], 3   [07], 3   [08]     shred                 = 1   [01], 1   [07], 1   [08]     skull_bash            = Z   [05]     soothe                = CR  [05]     stag_form             = CMwU[04]     stampeding_roar       =     starfire              = A6  [10]     starsurge             = A4  [10]     sunfire               = A1  [10]     survival_instincts    = SG  [05]     swipe                 = 5   [01], 5   [07], 5   [08], 5   [09]     swipe_bear            = 5   [01], 5   [07], 5   [08], 5   [09]     swipe_cat             = 5   [01], 5   [07], 5   [08], 5   [09]     thrash                = 4   [01], 4   [07], 4   [08], 4   [09]     thrash_bear           = 4   [01], 4   [07], 4   [08], 4   [09]     thrash_cat            = 4   [01], 4   [07], 4   [08], 4   [09]     tiger_dash            = SR  [01], SR  [07], SR  [08], SR  [09]     tigers_fury           = F   [01], F   [07], F   [08]     travel_form           = M3  [04]     typhoon               = SC  [03]     wrath                 = A3  [10]

### Error Messages (Link)

No errors were given. it says "You have no bugs, yay!"

### Additional Information

Could not save any snapshots either, I hit the hotkey but it doesn't seem to save a snapshot in Feral or Guardian at all, no message that a snapshot is saved. I tested it with my Balance spec and it saved a snapshot as expected.

### Contact Information

Daimy#9165

**Comment by Hekili** [comment]
Go to /hekili, Feral, click Enabled.

**Comment by GauntletFTW** [comment]
Okay, I feel dumb. that seemed to work. I don't think I ever disabled them myself though, but I could be wrong.
