### ISSUE TITLE
Displays not loading until Profile Reset

### ISSUE THREAD

**Issue by micromalc** [Hekili/hekili#1358]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

BugSack is not collecting any errors. I checked the addon settings according to the steps at the bottom of the CurseForge profile page.

I'm using Hekili out of the box. Prior to 9.2 with my current set of addons it was working fine. After 9.2, the display is not loading until "Profile Reset" is selected. If Profile Reset is used, it will then load and persist through logouts on a single Alt (Alt A).

However, if I log into another alt (Alt B), I will need to perform the same Profile Reset to get the display to appear. Returning to Alt A, the addon display will once again not show. I will then need to Reset Profile once more. Returning to Alt B / C / D etc after Reseting the Profile on any other Alt will then require another Profile Reset.

### How to Reproduce

1. Log into Alt A with new install of Hekili.
2. If display is not visible, reset profile.
3. Log out and back in.
4. Check display is still visible.
5. Log out.
6. Log into Alt B.
7. Display is not visible. Reset profile. Display should be visible.
8. Log back into Alt A. Display is no longer visible.

### Player Information (Link)

https://pastebin.com/X35kCpkk

### Error Messages (Link)

https://pastebin.com/X35kCpkk

**Comment by Hekili** [comment]
You definitely don't need to reset your whole profile. There seems to be an issue where your spec is disabled. You can just /hekili > Your Spec > Enabled (check).

**Comment by Hekili** [comment]
Also, are there error messages in BugSack?

**Comment by micromalc** [comment]
That was it - specs were all disabled. Thanks for clearing that up super fast.

**Comment by Hekili** [comment]
Thanks for confirming. I'll investigate the issue that is auto disabling them.

**Comment by micromalc** [comment]
I don't know if this is related, but I started levelling a Pandaren and started getting bugs.

33x Hekili\Targets.lua:404: attempt to index local 'spec' (a nil value)
[string "@Hekili\Targets.lua"]:404: in function `getNumberTargets'
[string "@Hekili\Events.lua"]:1326: in function `handler'
[string "@Hekili\Events.lua"]:57: in function <Hekili\Events.lua:51>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:
targetChanged = true
now = 227935.181000
showNPs = true
count = 0
spec = nil
db = <table> {
 Creature-0-4239-860-29246-54130-0003187BDB = 227934.547000
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Creature-0-4239-860-29246-54130-0003187BDB = 227934.547000
}
(for control) = "Creature-0-4239-860-29246-54130-0003187BDB"
guid = "Creature-0-4239-860-29246-54130-0003187BDB"
seen = 227934.547000
npcid = "54130"
excluded = nil
(*temporary) = "(%d+)-%x-$"
(*temporary) = "54130"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spec' (a nil value)"
lastCycle = 227935.181000
lastCount = 1
Hekili = <table> {
 GetMacroCastTarget = <function> defined @Hekili\Events.lua:1044
 GetTTD = <function> defined @Hekili\Targets.lua:885
 DeserializeStyle = <function> defined @Hekili\Options.lua:9849
 IC = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili\Options.lua:3898
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili\Targets.lua:870
 GetPetBasedTargetSpells = <function> defined @Hekili\Targets.lua:92
 After = <function> defined @Hekili\Utils.lua:274
 SetDefaultModulePrototype = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 UpdateDisplayVisibility = <function> defined @Hekili\UI.lua:1950
 IsEnabled = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili\State.lua:6249
 SetMode = <function> defined @Hekili\Options.lua:10636
 GetPetBasedTargetSpell = <function> defined @Hekili\Targets.lua:104
 ToggleHold = <function> defined @Hekili\State.lua:6274
 SpecializationChanged = <function> defined @Hekili\Classes.lua:5671
 Update = <function> defined @Hekili\Core.lua:2041
 GetNumTargetsAboveHealthPct = <function> defined @Hekili\Targets.lua:1055
 UpdateUseItems = <function> defined @Hekili\Events.lua:621
 SetSpecOption = <function> defined @Hekili\Options.lua:3685
 GetDefaults = <function> defined @Hekili\Options.lua:557
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Hekili\Core.lua:1453
 Options = <table> {
 }
 ReInitialize = <function> defined @Hekili\Core.lua:158
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Hekili\Classes.lua:5616
 State = <table> {
 }
 OnEnable = <function> defined @Hekili\Core.lua:181
 Version = "v9.2.0-1.0.2"
 CmdLine = <function> defined @Hekili\Options.lua:9284
 IsDisplayActive = <function> defined @Hekili\UI.lua:2049
 GetNumTargetsBelowHealthPct = <function> defined @Hekili\Targets.lua:1074
 SetupPetBasedTargetDetection = <function> defined @Hekili\Targets.lua:118
 ShowDiagnosticTooltip = <function> defined @Hekili\UI.lua:2657
 Notify = <function> defined @Hekili\Options.lua:10597
 OnInitialize = <function> defined @Hekili\Core.lua:61
 NewModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Hekili\Utils.lua:44
 EmbedItemOption = <function> defined @Hekili\Options.lua:4027
 DumpPetBasedTargetInfo = <function> defined @Hekili\Targets.lua:144
 IsClassic = <function> defined @

**Comment by Hekili** [comment]
Were there other error messages before this one?  Usually, the first error in the list is the one that matters.

**Comment by micromalc** [comment]
I think it was maybe only because it was a low level toon without a spec yet? There was only one bug showing (I logged in again just to check, copied it below).

Basically Bugsack was squeaking (?) at me every time I was in combat with one mob and click targetted a 2nd mob (even if not entering combat with that 2nd mob). Also got the same squeak retargetting the first mob (basically every time I switched targets when in combat). But there weren't any additional bugs recorded (or it just recorded the same one each time?). The squeaking completely stopped at lvl 10 once I had a spec.

34x Hekili\Targets.lua:404: attempt to index local 'spec' (a nil value)
[string "@Hekili\Targets.lua"]:404: in function `getNumberTargets'
[string "@Hekili\Events.lua"]:1326: in function `handler'
[string "@Hekili\Events.lua"]:57: in function <Hekili\Events.lua:51>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:
targetChanged = true
now = 227935.181000
showNPs = true
count = 0
spec = nil
db = <table> {
 Creature-0-4239-860-29246-54130-0003187BDB = 227934.547000
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Creature-0-4239-860-29246-54130-0003187BDB = 227934.547000
}
(for control) = "Creature-0-4239-860-29246-54130-0003187BDB"
guid = "Creature-0-4239-860-29246-54130-0003187BDB"
seen = 227934.547000
npcid = "54130"
excluded = nil
(*temporary) = "(%d+)-%x-$"
(*temporary) = "54130"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spec' (a nil value)"
lastCycle = 227935.181000
lastCount = 1
Hekili = <table> {
 GetMacroCastTarget = <function> defined @Hekili\Events.lua:1044
 GetTTD = <function> defined @Hekili\Targets.lua:885
 DeserializeStyle = <function> defined @Hekili\Options.lua:9849
 IC = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili\Options.lua:3898
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili\Targets.lua:870
 GetPetBasedTargetSpells = <function> defined @Hekili\Targets.lua:92
 After = <function> defined @Hekili\Utils.lua:274
 SetDefaultModulePrototype = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 UpdateDisplayVisibility = <function> defined @Hekili\UI.lua:1950
 IsEnabled = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili\State.lua:6249
 SetMode = <function> defined @Hekili\Options.lua:10636
 GetPetBasedTargetSpell = <function> defined @Hekili\Targets.lua:104
 ToggleHold = <function> defined @Hekili\State.lua:6274
 SpecializationChanged = <function> defined @Hekili\Classes.lua:5671
 Update = <function> defined @Hekili\Core.lua:2041
 GetNumTargetsAboveHealthPct = <function> defined @Hekili\Targets.lua:1055
 UpdateUseItems = <function> defined @Hekili\Events.lua:621
 SetSpecOption = <function> defined @Hekili\Options.lua:3685
 GetDefaults = <function> defined @Hekili\Options.lua:557
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Hekili\Core.lua:1453
 Options = <table> {
 }
 ReInitialize = <function> defined @Hekili\Core.lua:158
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Hekili\Classes.lua:5616
 State = <table> {
 }
 OnEnable = <function> defined @Hekili\Core.lua:181
 Version = "v9.2.0-1.0.2"
 CmdLine = <function> defined @Hekili\Options.lua:9284
 IsDisplayActive = <function> defined @Hekili\UI.lua:2049
 GetNumTargetsBelowHealthPct = <function> defined @Hekili\Targets.lua:1074
 SetupPetBasedTargetDetection = <function> defined @Hekili\Targets.lua:118
 ShowDiagnosticTooltip = <function> defined @Hekili\UI.lua:2657
 Notify = <function> defined @Hekili\Options.lua:10597
 OnInitialize = <function> defined @Hekili\Core.lua:61
 NewModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Hekili\Utils.lua:44
 EmbedItemOption = <function> defined @Hekili\Options.lua:4027
 DumpPetBasedTargetInfo = <function> defined @Hekili\Targets.lua:144
 IsClassic = <function> defined @

**Comment by micromalc** [comment]
There was a different error from another toon, but I think that was just because I was trying to apply an essence at the Heart Forge without my Heart of Azeroth equipped. Anyway, here it is just in case: 

1x Hekili\UI.lua:1057: Hekili\State.lua:3678: bad argument #1 to 'IsAzeriteItemEnabled' (Usage: local isEnabled = C_AzeriteItem.IsAzeriteItemEnabled(azeriteItemLocation))
[string "=[C]"]: in function `error'
[string "@Hekili\UI.lua"]:1057: in function <Hekili\UI.lua:865>

Locals:
(*temporary) = "Hekili\State.lua:3678: bad argument #1 to 'IsAzeriteItemEnabled' (Usage: local isEnabled = C_AzeriteItem.IsAzeriteItemEnabled(azeriteItemLocation))"

**Comment by Hekili** [comment]
For the first one, that explanation makes sense.  I'll make the addon use spec defaults when there's no spec information available.

For the second one, that shouldn't be an issue with the latest versions (especially alpha versions).  Can you confirm whether it is resolved in https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.3-alpha2/Hekili-v9.2.0-1.0.3-alpha2.zip ?

Thanks!

**Comment by Hekili** [comment]
I've found the issue that was causing new profiles to disable classes at first log-in, will be posted soon.  I'll be force-enabling all specs to fix anyone affected.
