### ISSUE TITLE
BM Hunter recommending Beastial Wrath as first global for opener

### ISSUE THREAD

**Issue by ReilerA** [Hekili/hekili#1359]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my beast mastery hunter in single target opener  I expect it to be Aspect of the Wild,>Inscrutable Quantum Device,> Wild Spirits,> Double Barbed Shot,> Beastial Wrath,> Barbed then normal Priority  rotation
When I updated hekili to the most recent version it started recommending to do the same rotation but with one change use Beastial Wrath at the beginning for the opener

I'm also getting the same error for the AOE rotation 2+ targets 
I expect for the AOE opener to be Aspect of the wild,> Inscrutable Quantum Device,> Multi-Shot,>Wild Spirit,>Double Barbed Shot,>Multi-Shot,> Beastial Wrath then normal priority rotation
Same error with AOE says to press Beastial Wrath first from what I can tell the normal priority rotation is fine it's just the opener that is wrong recommending beastial wrath as your first button press
![image](https://user-images.githubusercontent.com/100390960/155642944-e3ffb490-5c52-48b5-843f-33642c1744d7.png)

### How to Reproduce

1. Enter game as Beast Mastery Hunter
2. Use the following talents (2122211)
3. Go to a target dummy or mob

### Snapshot (Link)

https://pastebin.com/Jrn5evkt

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ui2hk91ZoVsNBggRDmx3rM

### Additional Information

I linked the radibots up top for single target the one here is AOE https://www.raidbots.com/simbot/report/hW1dy3AyWPg8Z47PTaLaGu

Looking at raidbots it agrees  with what I said earlier they're not using bestial wrath in opener for AOE or Single Target

### Contact Information

Discord: Reiler#0101

**Comment by Hekili** [comment]
Thanks.  Give 1.0.3-alpha2 a try when you have a chance.

**Comment by ReilerA** [comment]
Thanks tested it out the update worked didn't get the recommendation suggestion error anymore :)
