### ISSUE TITLE
Hekili dosnt show

### ISSUE THREAD

**Issue by madsgraversen** [Hekili/hekili#136]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by madsgraversen** [comment]
build: v8.1.5-16
level: 120
class: HUNTER
spec: beast_mastery

talents: a_murder_of_crows
    aspect_of_the_beast
    chimaera_shot
    killer_instinct
    natural_mending
    posthaste
    stomp

traits: azerite_empowered=3
    dance_of_death=1
    dire_consequences=1
    duck_and_cover=1
    feeding_frenzy=1
    haze_of_rage=1
    impassive_visage=1
    overwhelming_power=2
    shellshock=1
    treacherous_covenant=2
    unstable_flames=1

sets/legendaries/artifacts: none

gear:     loa_exultants_shroud=1
    galecallers_boon=1
    guild_tabard=1
    mistfire_raiment=1
    pauldrons_of_ancestral_vengeance=1
    pacifist_mk7=1
    grips_of_harmonious_spirits=1
    coif_of_the_court_spider=1
    city_crusher_sabatons=1
    loop_of_pulsing_veins=1
    heart_of_azeroth=1
    harlans_loaded_dice=1
    tempered_mistscale_greaves=1
    chainlinked_safety_cord=1
    band_of_multisided_strikes=1
    dread_captains_irons=1

**Comment by Hekili** [comment]
Thanks for the report.  This should be fixed in 8.1.5-17; please update and re-report if you still have trouble.
