### ISSUE TITLE
Recklessness does not seem to be recommended at all while in combat as Fury

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1360]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When im playing my fury warrior recklessness only appears when im out of combat. As soon i go in combat the recommendation disappears and i never see it again, this does not seem intentional.

### How to Reproduce

Play a fury warrior and look at your hekili recommendations before you go in combat.
After you go in combat you will notice how recommendations change away from recklessness and its never recommended again.

### Snapshot (Link)

https://pastebin.com/5beBYnkk

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/t77gmPNhzDZDofwU2Uy4L8

**Comment by Hekili** [comment]
Funny enough, that's consistent with your sim's behavior; your linked sim didn't use Recklessness after starting combat.

I did some quick testing:

> recklessness,if=!variable.unique_legendaries&gcd.remains=0&((buff.bloodlust.up|talent.anger_management.enabled|raid_event.adds.in>10)|target.time_to_die>100|variable.execute_phase|target.time_to_die<15&raid_event.adds.in>10)&(spell_targets.whirlwind=1|buff.meat_cleaver.up)&**cooldown.conquerors_banner.remains>20**

This line *seems* to be the one we would want to fire for your character, but the Conqueror's Banner check doesn't work well for a Night Fae.

https://www.raidbots.com/simbot/report/eyqfuvt4K5jUVw7zwybFfB

Changing it to:

> recklessness,if=!variable.unique_legendaries&gcd.remains=0&((buff.bloodlust.up|talent.anger_management.enabled|raid_event.adds.in>10)|target.time_to_die>100|variable.execute_phase|target.time_to_die<15&raid_event.adds.in>10)&(spell_targets.whirlwind=1|buff.meat_cleaver.up)&**(cooldown.conquerors_banner.remains>20|!covenant.necrolord)**

...seems to produce the desired result, though this means it's possible other changes could optimize even more.  I'll share with SimC folks and workaround it in the addon.

**Comment by Tzuyume** [comment]
Okey that makes alot of sense actually, thanks for looking it up.

**Comment by Hekili** [comment]
Submitted ticket to SimC:  https://github.com/simulationcraft/simc/issues/6419

**Comment by Hekili** [comment]
This should be resolved.
