### ISSUE TITLE
Marksman Priorities Scuffed (Multi-Shot)

### ISSUE THREAD

**Issue by goldur** [Hekili/hekili#1361]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing Marksmanship-Hunter in Multi-Target Rotation, Hekili always suggests Multi-Shot as first priority, even with Trick-Shots up.

### How to Reproduce

1. Enter the Game as Marksmanship Hunter
2. Get to Multi-Target (>3 Targets) Training dummies
3. Start Multitarget-Rotation

### Snapshot (Link)

https://pastebin.com/iPn9d3fw

### Contact Information

Goldur#9583

**Comment by Hekili** [comment]
Fixed in https://github.com/Hekili/hekili/tree/v9.2.0-1.0.3-alpha2
