### ISSUE TITLE
[FEATURE] Hekili Abilities Override Keybind Text Key Modifiers

### ISSUE THREAD

**Issue by NathanPrice** [Hekili/hekili#1362]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hi, I ran across this while following the advice mentioned [here ](https://github.com/Hekili/hekili/issues/1293#issue-1064370348)because I'd have abilities show up on this alt character of mine show the wrong keybindings. 

In there it was told to go to /hekili > Abilities and change what you want to be shown there for the abilities that where causing problems. While it's intuitive to do normal keybindings (EX: 1-9) I find it's a bit unintuitive when you have to add binds that include modifier keys (EX: Shift-1 - Shift-9). Adding normal keys is fine as you just have to hit the buttons and apply them but for modifier keys you can't do that as it'll either not work or show something you might not expect. 

For example, in my eyes anyways, if you press Shift-1 on the "Override Keybind Text" box you should ideally see S1 or whatever it is you're normally supposed to see normally on the rotation list when there's modifier keys. However what ends up happening in the example I mentioned it'll just take what would happen when you press that keybind normally which in the example I provided will just show "!" instead of "S1". Same situation when you do Ctrl-1 (C1) or ALT-1 (A1) for example but with different things displaying if it was a valid key combination that would display something. Essentially it's just working as a normal keyboard input box rather than a keybinding box if that makes sense.

Obviously you can get around this issue by manually typing what you'd what to be displayed (manually typing S1, C1, A1, etc) but the way I look at it it's not very conventional and some people might not be aware or think to do that. If it's even possible I think it'd be better to have it as a keybinding box in game in the options panel since it'd be a lot more straight forward in my opinion.

### Additional Information

1. Type /hekili
2. Go to the "Abilities" option
3. Pick an ability you want to change the keybind text of
4. Press a modifier key followed by a keybinding
5. Will either not show anything or display a character in the box if it was a valid combination / thing to show (EX: Shift-1 will display "!" instead of S1)

Also like stated before it appears to be coded / designed like a normal textbox rather than a keybinding box.

**Comment by Hekili** [comment]
You're overthinking it. You can specify the exact text you want to see. If you want `S1` then type `S1`, don't hold shift and press `1`.

You could type `farts` in that box and that's what the keybind text will show.

**Comment by NathanPrice** [comment]
Yes I'm aware, I even stated that. I was just bringing it up because I thought it was a bit strange. Majority of people would only use it for keybinding text.  

Can't really imagine what else you'd use it for so it would just save time overall treating it like a keybind box. It just opens up something that shouldn't be there in the first place. For example there's plenty of badly made forms online where it asks / expects a specific piece of information (Phone Number, Credit Card, etc) which don't validate or check the type of information you put in it. Just because you can doesn't mean you should is all I'm getting at and like I stated some people might not be aware to do that.

It's like binding an ability, it would be pretty bad game design if you had to go around typing out the entire modifiers for each key that had them in there.

**Comment by Hekili** [comment]
The purpose of the feature is to let you decide what should be shown if auto-detection fails to gather what you wanted.  Making it force real keybinds is more restrictive/less flexible, and doesn't accomplish anything significant.

> It's like binding an ability, it would be pretty bad game design if you had to go around typing out the entire modifiers for each key that had them in there.

It's not like binding an ability though.  It's deciding what you want to show.  I could use it to force nothing to be shown.  I could use it because I don't like how a binding is abbreviated (or fails to be abbreviated).  Restricting to actual binding format removes that functionality, and even potentially misleads others into thinking you've actually bound those abilities through the addon.

**Comment by NathanPrice** [comment]
Gotcha, that makes sense. The way you initially worded it just came off as "you do it this way and that's just how it has to be". 

Main reason I was even bringing it up because the wording could be potentially confusing. I was thinking "big picture" because in my eyes anyways when the average person see's "keybind" they would probably initially think to just press their normal keybindings and not having to type the whole thing out. 

Appreciate your time nevertheless. Figured it wouldn't be that big of an issue since it was just a small nuance / complaint. Didn't think there was more going on in the backend with it.
