### ISSUE TITLE
Hunter Marksman AoE rotation - multi-shot favored over everything on over 5 mobs

### ISSUE THREAD

**Issue by framezart** [Hekili/hekili#1363]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When i am doing the AoE rotation - the addon sticks on Multi-shot and doesnt cycle through rapid fire and aimed shot for better damage. If i disable multi-shot it defaults to Steady Shot on packs of 5 or more. 

### How to Reproduce

Log on to MM hunter Kyrian
Find packs of 5 or more 
Start with DoubleTap then Explosive shot
Put down resonating arrow
cast volley 
The next cast should be rapid fire and then 2 aimed shots
I get Multi shot as the next cast on Hekili and it never changes from Multi-shot until it Double Tap comes off of cooldown.

### Snapshot (Link)

Click here and press CTRL+A, CTRL+C to copy the snapshot.  build: v9.2.0-1.0.2 level: 60 (60) class: HUNTER spec: marksmanship  talents: camouflage     double_tap     explosive_shot     master_marksman     posthaste     streamline     volley  pvptalents: none  covenant: kyrian  conduits: deadly_chain = 11    enfeebled_mark = 10    marksmans_advantage = 11    rejuvenating_wind = 10    resilience_of_the_hunter = 11    reversal_of_fortune = 10  soulbinds: [forgelite_prime_mikanikos]    brons_call_to_action = 1    effusive_anima_accelerator = 1    forgelite_filter = 1    hammer_of_genesis = 1    resilient_plumage = 1    soulglow_spectrometer = 1  sets: inscrutable_quantum_device = 1  gear: amphitheater_stalkers_hood = 1     bonded_soulsmelt_greaves = 1     cord_of_coerced_spirits = 1     death_gods_signet = 1     decanter_of_endless_howling = 1     drape_of_twisted_loyalties = 1     inscrutable_quantum_device = 1     iron_spiked_handgrips = 1     plagueborne_shoulderguards = 1     ring_of_perpetual_conflict = 1     shadowghast_necklace = 1     shardskin_sabatons = 1     soaring_decimators_hauberk = 1     tabard_of_the_guardians_of_hyjal = 1     the_philosopher = 1     tortured_assistants_bindings = 1  legendaries: surging_shots = 1  itemIDs: 178764, 178767, 178799, 178815, 178830, 178841, 178872, 178927, 179350, 179355, 180112, 180123, 186364, 186367, 186429, 65906  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 33     nameplateRange = 8     nameplates = false     package = Marksmanship     petbased = false     potion = spectral_agility     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     eagletalon_swap = false     prevent_hardcasts = false     trueshot_vop_overlap = false  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true [separate]     essences = true      interrupts = true [separate]     mode = reactive      potions = false   keybinds:      aimed_shot              = 2   [01]     arcane_shot             = 3   [01], 3   [03]     aspect_of_the_turtle    = S5  [06]     binding_shot            = C   [06]     bursting_shot           = [   [06]     counter_shot            = 7   [01]     disengage               = -   [01]     double_tap              = =   [01], =   [12]     exhilaration            = S3  [06]     explosive_shot          = 9   [01]     flare                   = ]   [06]     freezing_trap           = AC  [06]     kill_shot               = 6   [01]     misdirection            = ;   [06]     multishot               = 5   [01], 5   [05]     phial_of_serenity       =     potion                  = AM  [03]     rapid_fire              = 4   [01]     resonating_arrow        = S6  [06]     steady_shot             = 1   [01]     stoneform               = C5  [06]     survival_of_the_fittest = S4  [06]     tar_trap                = M3  [06]     tranquilizing_shot      = A-  [01]     trueshot                =     volley                  = 8   [01], 8   [08]   targets:     dmg          -  0 - Creature-0-4218-2222-18176-160325-00011A6AA7     dmg          -  0 - Creature-0-4218-2222-18176-160325-00021A6AA7     dmg          -  0 - Creature-0-4218-2222-18176-160325-00009A6AA7     dmg          -  0 - Creature-0-4218-2222-18176-160325-00001A6AA7     dmg          -  0 - Creature-0-4218-2222-18176-160325-00019A6AA7   player_buffs:    307185 - *Spectral Flask of Power                 -   1 - 527.82    164273 - lone_wolf                                -   1 - 3600.00    347901 - *Veiled Augmentation                     -   1 - 355.48     93341 - *Champion of the Guardians of Hyjal      -   1 - 3600.00    186403 - *Sign of Battle                          -   1 - 3600.00    332514 - *Bron's Call to Action                   -  23 - 3600.00    260402 - double_tap                               -   1 - 6.98    260243 - *Volley                                  -   1 - 2.72    257622 - volley                                   -   1 - 2.91  player_debuffs:  target_buffs:  target_debuffs:    353248 - *Effusive Anima Accelerator              -   1 - 3.40    308498 - resonating_arrow                         -   1 - 6.28    269576 - master_marksman                          -   1 - 6.63   New Recommendations for [ AOE ] requested at 14:38:40 ( 196468.92 ); using built-in ( Marksmanship ) priority. *** START OF NEW DISPLAY: AOE ***  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: focus[ 100.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Marksmanship - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   bottled_flayedwing_toxin ( precombat - 1 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.05ms         TimeData:Marksmanship-precombat-1:bottled_flayedwing_toxin:0.05:Ability Known, Enabled(0.05)                  2.   fleshcraft ( precombat - 2 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Marksmanship-precombat-2:fleshcraft:0.02:Ability Known, Enabled(0.02)                  3.   tar_trap ( precombat - 3 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.02ms         TimeData:Marksmanship-precombat-3:tar_trap:0.02:Ability Known, Enabled(0.02)                  4.   double_tap ( precombat - 4 )         The action is not ready ( 51.93 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Marksmanship-precombat-4:double_tap:0.02:Ability Known, Enabled(0.02)                  5.   aimed_shot ( precombat - 5 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.02ms         TimeData:Marksmanship-precombat-5:aimed_shot:0.02:Ability Known, Enabled(0.02)                  6.   steady_shot ( precombat - 6 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.02ms         TimeData:Marksmanship-precombat-6:steady_shot:0.02:Ability Known, Enabled(0.02)          Completed precombat action list [ Marksmanship - precombat ].          Processing default action list [ Marksmanship - default ].                  Current recommendation was NO ACTION at +10.00s.                  7.   counter_shot ( default - 1 ) - ability disabled ( toggle )         Time spent on this action:  0.02ms         TimeData:Marksmanship-default-1:counter_shot:0.02:Ability Known, Enabled(0.02)                  8.   counter_shot ( default - 2 ) - ability disabled ( toggle )         Time spent on this action:  0.02ms         TimeData:Marksmanship-default-2:counter_shot:0.02:Ability Known, Enabled(0.02)                  9.   tranquilizing_shot ( default - 3 ) - ability disabled ( toggle )         Time spent on this action:  0.02ms         TimeData:Marksmanship-default-3:tranquilizing_shot:0.02:Ability Known, Enabled(0.02)                  10.  call_action_list ( default - 4 )         Time-sensitive Criteria for trinkets deferred at +0.00 - covenant.kyrian[true] & cooldown.trueshot.remains[120.00] & cooldown.resonating_arrow.remains[35.49] | ! covenant.kyrian[true] & cooldown.trueshot.remains[120.00]         Action list (trinkets) was found.         + trinkets         Current recommendation was NO ACTION at +10.00s.                  11.  variable ( trinkets - 1 )          - variable.sync_up will check this script entry ( Marksmanship:trinkets:1 )         buff.resonating_arrow.up[true] | buff.trueshot.up[false]         Time spent on this action:  0.03ms         TimeData:Marksmanship-trinkets-1:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  12.  variable ( trinkets - 2 )          - variable.strong_sync_up will check this script entry ( Marksmanship:trinkets:2 )         covenant.kyrian[true] & buff.resonating_arrow.up[true] & buff.trueshot.up[false] | ! covenant.kyrian[true] & buff.trueshot.up[false]         Time spent on this action:  0.02ms         TimeData:Marksmanship-trinkets-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  13.  variable ( trinkets - 3 )          - variable.strong_sync_remains will check this script entry ( Marksmanship:trinkets:3 )         cooldown.resonating_arrow.remains[35.49] <? cooldown.trueshot.remains[120.00]         Time spent on this action:  0.02ms         TimeData:Marksmanship-trinkets-3:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  14.  variable ( trinkets - 4 )          - variable.strong_sync_remains will check this script entry ( Marksmanship:trinkets:4 )         cooldown.resonating_arrow.remains[35.489000000001]         Time spent on this action:  0.02ms         TimeData:Marksmanship-trinkets-4:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  15.  variable ( trinkets - 5 )          - variable.sync_remains will check this script entry ( Marksmanship:trinkets:5 )         cooldown.resonating_arrow.remains[35.49] >? cooldown.trueshot.remains[120.00]         Time spent on this action:  0.02ms         TimeData:Marksmanship-trinkets-5:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  16.  trinket1 ( trinkets - 6 )         Time spent on this action:  0.02ms         TimeData:Marksmanship-trinkets-6:trinket1:0.02:Ability Known, Enabled(0.02)                  Substituting inscrutable_quantum_device for [Trinket #2] action; it is otherwise not included in the priority.         17.  inscrutable_quantum_device ( trinkets - 7 ) - ability disabled ( preference )         Time spent on this action:  0.06ms         TimeData:Marksmanship-trinkets-7:inscrutable_quantum_device:0.06:Ability Known, Enabled(0.06)         Returned from list (trinkets), current recommendation is NO ACTION (+10.00).         - trinkets                  18.  call_action_list ( default - 5 )         There is no criteria for cds.         Action list (cds) was found.         + cds         Current recommendation was NO ACTION at +10.00s.                  19.  berserking ( cds - 1 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Marksmanship-cds-1:berserking:0.02:Ability Known, Enabled(0.02)                  20.  blood_fury ( cds - 2 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Marksmanship-cds-2:blood_fury:0.02:Ability Known, Enabled(0.02)                  21.  ancestral_call ( cds - 3 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Marksmanship-cds-3:ancestral_call:0.02:Ability Known, Enabled(0.02)                  22.  fireblood ( cds - 4 ) - ability unknown         Time spent on this action:  0.03ms         TimeData:Marksmanship-cds-4:fireblood:0.03:Ability Known, Enabled(0.03)                  23.  lights_judgment ( cds - 5 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Marksmanship-cds-5:lights_judgment:0.02:Ability Known, Enabled(0.02)                  24.  potion ( cds - 6 ) - ability disabled ( toggle )         Time spent on this action:  0.02ms         TimeData:Marksmanship-cds-6:potion:0.02:Ability Known, Enabled(0.02)         Returned from list (cds), current recommendation is NO ACTION (+10.00).         - cds                  25.  call_action_list ( default - 6 )         Criteria for st FAIL at +0.00 - active_enemies[5.00] < 3                  26.  call_action_list ( default - 7 )         Criteria for trickshots PASS at +0.00 - active_enemies[5.00] > 2         Action list (trickshots) was found.         + trickshots         Current recommendation was NO ACTION at +10.00s.                  27.  steady_shot ( trickshots - 1 )         The action (steady_shot) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( trickshots ) called from ( Marksmanship:default:7 ) would PASS at 0.00.         active_enemies[5.00] > 2          - this entry's criteria FAILS: talent.steady_focus.enabled[false] & in_flight[false] & buff.steady_focus.remains[0.00] < 5         Excluded -4.99 recheck time as it is outside our constraints ( 0.00 - 10.00 ).         There were no recheck events to check.         Time spent on this action:  0.18ms         TimeData:Marksmanship-trickshots-1:steady_shot:0.18:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.02):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.08):Post-Recheck Times(0.01):Post Recheck(0.00)                  28.  kill_shot ( trickshots - 2 )         The action (kill_shot) is unusable at (0.00 + 0.00) because IsUsable returned false.         Time spent on this action:  0.07ms         TimeData:Marksmanship-trickshots-2:kill_shot:0.07:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.02)                  29.  flayed_shot ( trickshots - 3 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-3:flayed_shot:0.02:Ability Known, Enabled(0.02)                  30.  double_tap ( trickshots - 4 )         The action is not ready ( 51.93 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-4:double_tap:0.02:Ability Known, Enabled(0.02)                  31.  tar_trap ( trickshots - 5 )         The action (tar_trap) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( trickshots ) called from ( Marksmanship:default:7 ) would PASS at 0.00.         active_enemies[5.00] > 2          - this entry's criteria FAILS: runeforge.soulforge_embers.enabled[false] & tar_trap.remains[0.00] < gcd.execute[1.32] & cooldown.flare.remains[0.00] < gcd.execute[1.32]         Excluded -1.31 recheck time as it is outside our constraints ( 0.00 - 10.00 ).         Excluded -1.31 recheck time as it is outside our constraints ( 0.00 - 10.00 ).         There were no recheck events to check.         Time spent on this action:  0.17ms         TimeData:Marksmanship-trickshots-5:tar_trap:0.17:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.06):Post-Recheck Times(0.03):Post Recheck(0.00)                  32.  flare ( trickshots - 6 )         The action (flare) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( trickshots ) called from ( Marksmanship:default:7 ) would PASS at 0.00.         active_enemies[5.00] > 2          - this entry's criteria FAILS: tar_trap.up[false] & runeforge.soulforge_embers.enabled[false]         There were no recheck events to check.         Time spent on this action:  0.10ms         TimeData:Marksmanship-trickshots-6:flare:0.10:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.02):Post-Recheck Times(0.00):Post Recheck(0.00)                  33.  explosive_shot ( trickshots - 7 )         The action is not ready ( 23.26 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-7:explosive_shot:0.02:Ability Known, Enabled(0.02)                  34.  wild_spirits ( trickshots - 8 ) - ability unknown         Time spent on this action:  0.04ms         TimeData:Marksmanship-trickshots-8:wild_spirits:0.04:Ability Known, Enabled(0.04)                  35.  wailing_arrow ( trickshots - 9 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-9:wailing_arrow:0.02:Ability Known, Enabled(0.02)                  36.  resonating_arrow ( trickshots - 10 )         The action is not ready ( 35.49 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-10:resonating_arrow:0.02:Ability Known, Enabled(0.02)                  37.  volley ( trickshots - 11 )         The action is not ready ( 41.73 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-11:volley:0.02:Ability Known, Enabled(0.02)                  38.  barrage ( trickshots - 12 ) - talent [ barrage ] missing         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-12:barrage:0.02:Ability Known, Enabled(0.02)                  39.  trueshot ( trickshots - 13 ) - ability disabled ( preference )         Time spent on this action:  0.02ms         TimeData:Marksmanship-trickshots-13:trueshot:0.02:Ability Known, Enabled(0.02)                  40.  rapid_fire ( trickshots - 14 )         The action (rapid_fire) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( trickshots ) called from ( Marksmanship:default:7 ) would PASS at 0.00.         active_enemies[5.00] > 2          - this entry's criteria FAILS: runeforge.surging_shots.enabled[true] & ( cooldown.resonating_arrow.remains[35.49] > 10 | ! covenant.kyrian[true] | ! talent.double_tap.enabled[true] ) & buff.trick_shots.remains[0.00] >= execute_time[1.77]         There were no recheck events to check.         Time spent on this action:  0.40ms         TimeData:Marksmanship-trickshots-14:rapid_fire:0.40:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.03):Pre-Recheck(0.28):Post-Recheck Times(0.00):Post Recheck(0.00)                  41.  aimed_shot ( trickshots - 15 )         The action (aimed_shot) is usable at (0.00 + 0.00) with cost of 35 focus.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( trickshots ) called from ( Marksmanship:default:7 ) would PASS at 0.00.         active_enemies[5.00] > 2          - this entry's criteria FAILS: buff.trick_shots.remains[0.00] >= execute_time[2.21] & ( buff.precise_shots.down[true] | full_recharge_time[0.00] < cast_time[2.21] + gcd.execute[1.32] | buff.trueshot.up[false] )         Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 10.00 ).         Excluded -0.88 recheck time as it is outside our constraints ( 0.00 - 10.00 ).         There were no recheck events to check.         Time spent on this action:  0.53ms         TimeData:Marksmanship-trickshots-15:aimed_shot:0.53:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.02):Post Ready/Clash(0.03):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.02):Pre-Recheck(0.34):Post-Recheck Times(0.05):Post Recheck(0.00)                  42.  death_chakram ( trickshots - 16 ) - ability unknown         Time spent on this action:  0.15ms         TimeData:Marksmanship-trickshots-16:death_chakram:0.15:Ability Known, Enabled(0.15)                  43.  rapid_fire ( trickshots - 17 )         The action (rapid_fire) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( trickshots ) called from ( Marksmanship:default:7 ) would PASS at 0.00.         active_enemies[5.00] > 2          - this entry's criteria FAILS: ( cooldown.resonating_arrow.remains[35.49] > 10 & runeforge.surging_shots.enabled[true] | ! covenant.kyrian[true] | ! runeforge.surging_shots.enabled[true] | ! talent.double_tap.enabled[true] ) & buff.trick_shots.remains[0.00] >= execute_time[1.77]         There were no recheck events to check.         Time spent on this action:  0.25ms         TimeData:Marksmanship-trickshots-17:rapid_fire:0.25:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.02):Pre-Recheck(0.14):Post-Recheck Times(0.00):Post Recheck(0.00)                  44.  multishot ( trickshots - 18 )         The action (multishot) is usable at (0.00 + 0.00) with cost of 20 focus.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( trickshots ) called from ( Marksmanship:default:7 ) would PASS at 0.00.         active_enemies[5.00] > 2          - this entry's criteria PASSES: buff.trick_shots.down[true] | buff.precise_shots.up[false] & focus.current[100.00] > cost[20.00] + action.aimed_shot.cost[35.00] & ( ! talent.chimaera_shot.enabled[false] | active_enemies[5.00] > 3 )         Action chosen:  multishot at 0.00!         Returned from list (trickshots), current recommendation is multishot (+0.00).         - trickshots          Completed default action list [ Marksmanship - default ].     Recommendation is multishot at 0.00 + 0.00.     Recommendation #1 is multishot at 0.00s (0.00s).     Time spent generating recommendations:  4.83ms

**Comment by Hekili** [comment]
Fixed in https://github.com/Hekili/hekili/releases/tag/v9.2.0-1.0.3-alpha2, use the alpha or wait for me to post a release.

(Also, in the future, use pastebin as directed for snapshot information.  See how unreadable that is?  :D)

**Comment by framezart** [comment]
Thank you! sorry for the wall of text! wont happen again  :)
