### ISSUE TITLE
[REC] Hunter/Marksmanship - AOE always show Multi-shot and never rapid fire or aimed shot

### ISSUE THREAD

**Issue by chris-munn** [Hekili/hekili#1364]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

AOE always show Multi-shot and never rapid fire or aimed shot, I can get this working if I amend the aimed shot and rapid fire Actionlist for marksmanship - I have to remove the following pieces of code which do not appear to be working... 
& buff.trick_shots.remains >= execute_time

Now my rotation works again but obviously it will now still show aimed shot or rapid fire even if the execution time is greater then the time left on trick shot

### How to Reproduce

Enter game as marksmanship 
Talent Streamline
start hitting 3 or more mobs 
notice that multi-shot never changes

### Snapshot (Link)

https://pastebin.com/

**Comment by Hekili** [comment]
See #1361.
