### ISSUE TITLE
[REC] Moonfire spams even target has already debuff

### ISSUE THREAD

**Issue by noiseuu** [Hekili/hekili#1366]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello!

So after new update, addon wants sometimes just spam moonfire even target has already have it.
At snapshot it says twin moons are my talents but not stellar drift i have talented

https://gyazo.com/60c84e87fb8f7c9d78edffedabd40eb4

### How to Reproduce

1. Just doing dailies at new zone

### Snapshot (Link)

https://pastebin.com/RVziDjXR

**Comment by PARADOX070** [comment]
Same issue, only seems to happen on AOE/AUTOMATIC during an eclipse. It will suggest to spam moonfire on everything as you can see here: https://i.imgur.com/Xp2j0fh.png

Snapshot: https://pastebin.com/hgSQUTKc

**Comment by Hekili** [comment]
There was a typo when I translated the new Balance priority.  This should be resolved in https://github.com/Hekili/hekili/releases/v9.2.0-1.0.3e which is being released now.  If not, please post an updated screenshot and snapshot and any error messages (from BugSack and/or /hekili > Warnings).

**Comment by melarki** [comment]
I think this issue has happened again, doing the same thing to me after updating today

**Comment by Hekili** [comment]
Yep, I see it.  Fix incoming.
