### ISSUE TITLE
Getting spammed by snapshots saved as Feral druid

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1367]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Getting spammed with Constant snapshop saved while in a m+ as Feral Druid Kyrian.

### How to Reproduce

Play as Kyrian Feral druid in a dungeon and get constant "snapshot saved"

### Snapshot (Link)

https://pastebin.com/UaRrpWbK

**Comment by Hekili** [comment]
This should be resolved in https://github.com/Hekili/hekili/releases/v9.2.0-1.0.3e which is being released now.  If not, please post an updated screenshot and snapshot and any error messages (from BugSack and/or /hekili > Warnings).
