### ISSUE TITLE
WW Monk rotation not recommending Whirling Dragon Punch

### ISSUE THREAD

**Issue by imarkvisser** [Hekili/hekili#1368]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For some reason I see Whirling Dragon Punch being queued but when it should be casted according to the queue list it disappears and is never recommended again.

### How to Reproduce

Fight as WW monk in a dungeon

### Snapshot (Link)

https://pastebin.com/raw/ddSMSACX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8x1ww86SzH5ct88Acw1ENw

### Additional Information

Should I add an ingame snapshot?

**Comment by Hekili** [comment]
Please add a snapshot (not a screenshot).

**Comment by Hekili** [comment]
Fixed in 1.0.3g.
