### ISSUE TITLE
Addon seems to stall with using Relic of the Frozen Wastes.

### ISSUE THREAD

**Issue by lkj61** [Hekili/hekili#1370]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am using this trinket on my beastmaster hunter, and the addon seems to stall there.  I swapped it out with a different trinket, and it seems to work fine now.

### How to Reproduce

I swapped the trinket back in, and it seems to stall again.

### Player Information (Link)

https://pastebin.com/QYijVJwi

### Error Messages (Link)

https://pastebin.com/QYijVJwi

### Contact Information

lkj61

**Comment by Hekili** [comment]
Are there error messages?

What do you mean by "stall" precisely?

**Comment by Hekili** [comment]
This is a defect in SpellFlash (it doesn't load spells/items using modern API).  I'm sending a fix over to them.

**Comment by lkj61** [comment]
It stops flashing. Just with that trinket equipped.

**Comment by lkj61** [comment]
Awesome!  Thank you.

Lisa

**Comment by Hekili** [comment]
Fixed in https://github.com/Hekili/hekili/releases/v9.2.0-1.0.4a.

**Comment by lkj61** [comment]
Thank you!

**Comment by lkj61** [comment]
I installed the new version, put the trinket back in, and it worked fine
for about 20 seconds. I uninstalled everything, made sure I got all the
saved variables deleted and got back in the game. Will not flash at all
with that darn trinket equipped. Put the other back in and all is good.

Lisa

**Comment by Hekili** [comment]
Show your "Player Information" from /hekili.

**Comment by lkj61** [comment]
I watched and it proc'd the trinket once, and then when the cooldown on the
trinket was available again, that's when it wouldn't flash anymore.



build: v9.2.0-1.0.4a
level: 60 (60)
class: HUNTER
spec: beast_mastery

talents: animal_companion
    aspect_of_the_beast
    binding_shot
    natural_mending
    scent_of_blood
    stomp
    thrill_of_the_hunt

pvptalents: none

covenant: venthyr

conduits: cheetahs_vigor = 5
   condensed_anima_sphere = 5
   empowered_release = 5
   one_with_the_beast = 5
   resilience_of_the_hunter = 5
   reversal_of_fortune = 7

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   dauntless_duelist = 1
   fatal_flaw = 1
   friends_in_low_places = 1
   nimble_steps = 1
   thrill_seeker = 1

sets: relic_of_the_frozen_wastes = 1

gear: anthemic_links = 1
    anthemic_shoulders = 1
    brokers_enigmatic_cowl = 1
    burnished_arbalest = 1
    cloak_of_scarred_honor = 1
    dimensional_enigmatic_footguards = 1
    enigmatic_chainmail = 1
    gormhusk_kilt = 1
    gormhusk_wristguards = 1
    miniature_breaking_wheel = 1
    periapt_of_pristine_preservation = 1
    razorwing_scale_grips = 1
    relic_of_the_frozen_wastes = 1
    renowned_guild_tabard = 1
    rich_purple_silk_shirt = 1
    sprigthistle_loop = 1
    symbol_of_the_lupine = 1

legendaries: none

itemIDs: 175713, 181416, 181428, 185870, 186289, 186291, 186375, 186437,
188024, 188025, 188040, 190357, 190597, 190742, 190993, 4335, 69210

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    package = Beast Mastery
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    avoid_bw_overlap = false
    barbed_shot_grace_period = 0.5
    check_pet_range = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true [overridden]
    interrupts = true
    mode = automatic
    potions = false

keybinds:
    binding_shot       = 0   [01]
    concussive_shot    = 2   [01], 2   [02]
    disengage          = 5   [01]
    feign_death        = 6   [01]
    freezing_trap      = -   [01]
    hunters_mark       = 4   [01]
    tar_trap           = =   [01]
    tranquilizing_shot = 7   [01]

**Comment by Hekili** [comment]
Do you have in-game error messages?

Can you show where your trinket is bound?  (i.e., a clipped screenshot)

**Comment by Hekili** [comment]
Also, did you cut the Player Information part short?  You should have more abilities listed in keybindings.

**Comment by Hekili** [comment]
One more question -- do you have SpellFlashCore installed separately?  I.e., an AddOns/SpellFlashCore folder?  If so, delete it.

**Comment by lkj61** [comment]
This is what I copied from the report issues window.  The accept button
stays greyed out.
The trinket in question is the bottom right.
[image: WoWScrnShot_022822_101320.jpg]

[image: WoWScrnShot_022822_101528.jpg]



build: v9.2.0-1.0.4a
level: 60 (60)
class: HUNTER
spec: beast_mastery

talents: animal_companion
    aspect_of_the_beast
    binding_shot
    natural_mending
    scent_of_blood
    stomp
    thrill_of_the_hunt

pvptalents: none

covenant: venthyr

conduits: cheetahs_vigor = 5
   condensed_anima_sphere = 5
   empowered_release = 5
   one_with_the_beast = 5
   resilience_of_the_hunter = 5
   reversal_of_fortune = 7

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   dauntless_duelist = 1
   fatal_flaw = 1
   friends_in_low_places = 1
   nimble_steps = 1
   thrill_seeker = 1

sets: none

gear: anthemic_links = 1
    anthemic_shoulders = 1
    brokers_enigmatic_cowl = 1
    burnished_arbalest = 1
    cloak_of_scarred_honor = 1
    dimensional_enigmatic_footguards = 1
    enigmatic_chainmail = 1
    gormhusk_kilt = 1
    gormhusk_wristguards = 1
    miniature_breaking_wheel = 1
    periapt_of_pristine_preservation = 1
    razorwing_scale_grips = 1
    renowned_guild_tabard = 1
    rich_purple_silk_shirt = 1
    sprigthistle_loop = 1
    symbol_of_the_lupine = 1
    titanic_ocular_gland = 1

legendaries: none

itemIDs: 175713, 181416, 181428, 185870, 186289, 186291, 186375, 186423,
188024, 188025, 188040, 190357, 190597, 190742, 190993, 4335, 69210

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    package = Beast Mastery
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    avoid_bw_overlap = false
    barbed_shot_grace_period = 0.5
    check_pet_range = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true [overridden]
    interrupts = true
    mode = automatic
    potions = false

keybinds:
    binding_shot       = 0   [01]
    concussive_shot    = 2   [01], 2   [02]
    disengage          = 5   [01]
    feign_death        = 6   [01]
    freezing_trap      = -   [01]
    hunters_mark       = 4   [01]
    tar_trap           = =   [01]
    tranquilizing_shot = 7   [01]

**Comment by lkj61** [comment]
I checked and I don't have it downloaded.

**Comment by Hekili** [comment]
Do you have BugSack/BugGrabber installed?  Error messages?

When you updated, what did you use to update?  I'm not sure you actually got the SpellFlash changes.

**Comment by lkj61** [comment]
[image: WoWScrnShot_022822_102137.jpg]

**Comment by Hekili** [comment]
I'm not able to see that image.

Can you confirm this file is installed:  https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.4a/Hekili-v9.2.0-1.0.4a.zip

You can go into `Hekili/Lib/SpellFlashCore` and attach `SpellFlashCore.lua` here so I can verify.

**Comment by lkj61** [comment]
Also, no bugs in bugsack.

**Comment by lkj61** [comment]
Was everything okay on my end?

**Comment by Hekili** [comment]
I don't know, I never saw your picture nor whether you had the right file installed.

**Comment by lkj61** [comment]
I just sent it as an attachment.

**Comment by Hekili** [comment]
That doesn't work; you'll need to add through the site.

https://github.com/Hekili/hekili/issues/1370

This would be the latest one to test with:  https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.5-beta1/Hekili-v9.2.0-1.0.5-beta1.zip

**Comment by lkj61** [comment]
Did it work? I’ve never done that before.

**Comment by Hekili** [comment]
No, you're still sending emails.  Go to the website.

**Comment by lkj61** [comment]
I installed the version you just linked.  I will give that one a try as soon as the servers come back up.

**Comment by lkj61** [comment]
Is there any way to stream just to you?

**Comment by lkj61** [comment]
Still stops flashing after the first proc of that trinket.  Works fine
otherwise.

Lisa

**Comment by Hekili** [comment]
I'm not able to duplicate this issue after these fixes.  The last test I can recommend is using that latest version of the addon with only Hekili loaded (no other addons).  If flashes still break down, let me know about it.  You may check whether some other addon is supplying an older version of SpellFlashCore that doesn't work.  Otherwise, if there are no error messages and no other information you can supply, I'd refer you to SpellFlashCore's project to report an issue.

**Comment by lkj61** [comment]
Ok, I'll check it out.

**Comment by lkj61** [comment]
Do you have that trinket available?

**Comment by lkj61** [comment]
Just tried it with only Hekili and default ui loaded.  Still doesn't flash
with that darn trinket.  :(

**Comment by lkj61** [comment]
I don't know if it matters, but if I manually click the trinket after the
timer on it resets, everything starts flashing again as it should.  Is
there a way to have the addon not look at trinkets?  Or maybe just this
one?  Relic of the Frozen Wastes.

Thank you so much for your help with this.  It is truly appreciated.

Lisa

**Comment by lkj61** [comment]
Here's a link to the video of what I was referring to.  

https://drive.google.com/file/d/10NvxhaUPDK8U4vpNaVt7CXoU-HXAglxN/view?usp=sharing

**Comment by lkj61** [comment]
Okay, I found where I can disable it.  I will give it a try.

**Comment by Hekili** [comment]
That is a very, very large (half gigabyte) video.  You should probably clip it to the relevant part.  I also never saw your screenshot.

I'm honestly not sure the whole scope of your issue at this point.  If you can put your explanation, picture, and snapshot altogether in one cohesive summary, I can do a better job of investigating.

Relic sits at the front of the queue?  Even if used?
Relic is at front of queue but doesn't flash?
Both of the above?
Something else?

You can disable any item via /hekili > Gear and Trinkets > [item name] > Disable [item name].  The setting is per-spec.

**Comment by lkj61** [comment]
I will try to clip it. When I first start the rotation, flashing works as
it should, but when the time on the trinket rests then everything stops
flashing until I manually click on the trinket, then the rotation starts
flashing again. That’s the only way I can describe  it. I will try clipping
the video.

Lisa.

**Comment by lkj61** [comment]
https://user-images.githubusercontent.com/9512021/156624795-8f273865-2e11-44b6-be1d-a544472446c0.mp4

**Comment by lkj61** [comment]
I hope that shows what I am talking about.

**Comment by lkj61** [comment]
Everything flashes when the rotation first starts, but when the trinket timer resets, then it stops until I manually click it.  Then it starts back up.  When I end the fight and start another, it won't start flashing again until I manually use the trinket.

**Comment by Hekili** [comment]
Are you saying that it will flash the trinket in your character panel initially, and then not afterward?  I'd be surprised to see anything flash in the character panel to begin with.

If the addon's recommendation doesn't exist on action bars, SpellFlash will just quietly fail.  If you put your trinket onto your action bars, does it flash as expected?

**Comment by lkj61** [comment]
No, it doesn't flash in my character pane.  I left that open so that you could see the timer reset on it and then the bars stop flashing until I click the trinket.  I disabled the trinket in the addon and everything flashes as it should now.

**Comment by Hekili** [comment]
Ok, yeah -- the issue there is that a trinket won't flash if it's not on an action bar, the addon has no mechanism to let you know that recommendations are blocked that way when you have the addon display disabled.

I may add some kind of warning message in such cases, in case this comes up again.  Thanks for following up with that info.

**Comment by lkj61** [comment]
It's the first time I've ever had to disable a trinket.  All the others work just fine in the rotation.  If I swap that one out with another trinket, the flashing never stops like it does with that one trinket.

**Comment by Hekili** [comment]
I'm not sure how that would work, unless you've lucked into having passive trinkets that aren't recommended by the addon (because you don't use them directly).  Or if you had them macro'd so they were getting put on CD when you used your cooldowns anyway.

**Comment by lkj61** [comment]
For example, I replace that trinket with Titanic Ocular Gland, and it doesn't affect my rotation flashing.  As soon as I put the other in, it does what it shows in the video, that when the trinket resets, it stops flashing until I click on it again.

**Comment by lkj61** [comment]
I hope that makes sense?

**Comment by Hekili** [comment]
Yeah, that makes sense -- Titanic Ocular Gland doesn't have a "Use:" effect, so it's never recommended, so it would never block.  Any other trinket with a "Use:" would block in the same way.  It can be useful to have a `/use 13` and `/use 14` macro on your bars, so that if you equip a usable trinket, you have a consistent keybind for it.

**Comment by lkj61** [comment]
I will give that a try.  Thank you.  ;)

**Comment by lkj61** [comment]
Okay, I tried out your "Use:" theory.  I swapped in Brimming Ember Shard, it triggered, everything was flashing, and it continued to flash, even when the timer on the trinket reset.  It all worked as it should with that trinket equipped.

**Comment by Hekili** [comment]
So what was flashing when it was time to use Brimming Ember Shard?

**Comment by lkj61** [comment]
Meh, I can't get it to do it again.  :/  I'll send a video if/when it happens again.

**Comment by lkj61** [comment]
Okay, you saw what it did in the video.  Trinket was triggered, everything flashed as it should in the rotation until the timer on the trinket reset.  I put in the Brimming Ember Shard, and it didn't trigger on it's own and when I did trigger it, everything flashed as it should throughout the rest of the rotation.  When the Relic of Frozen Waste is equipped, it is triggered in the rotation, not by me, and that's when the situation occurs.
The Brimming Ember Shard IS NOT triggered by the rotation, but manually.  Does that make sense?

**Comment by Hekili** [comment]
If the priority would never recommend Brimming Ember Shard, then Brimming Ember Shard would never block.

**Comment by lkj61** [comment]
Meaning, I never trigger the Relic trinket, it does it on it's own.
The Brimming Ember Shard I have to trigger.

**Comment by lkj61** [comment]
Ah.  Gotchcha.  Thanks for explaining.  Sorry to be such a bother. And I do thank you for your time.

**Comment by Hekili** [comment]
Not a problem.  Sorry that I wasn't grasping what you were saying at first.  Thanks for providing more info.

**Comment by lkj61** [comment]
I was away from WoW for several years.  I had previously used Spellflash and it's addons for classes.  I was a bit distraught when I discovered that it was no longer updated.  Then I tried a variety of other rotation helpers until I came across yours and I was instantly smiitten.  :)
