### ISSUE TITLE
[BUG] Spellflash not working anymore

### ISSUE THREAD

**Issue by dMopp** [Hekili/hekili#1371]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Since the latest Update v9.2.0-1.0.4, Spellflash is not working anymore

### How to Reproduce

Just play the game with spellflash enabled

### Player Information (Link)

https://pastebin.com/RmNrsG2W

### Error Messages (Link)

https://pastebin.com/RmNrsG2W

### Additional Information

All AddOns are Up2Date

**Comment by Hekili** [comment]
Fixed in https://github.com/Hekili/hekili/releases/v9.2.0-1.0.4a.
