### ISSUE TITLE
[BUG] Bug grabber error on load

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1372]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When loading into the game you get the following error...
```
8x Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:169: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
[string "=[C]"]: in function `error'
[string "@FrameXML\ObjectAPI\Spell.lua"]:55: in function `ContinueOnSpellLoad'
[string "@Hekili\Libs\SpellFlashCore\SpellFlashCore.lua"]:169: in function <Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:134>
[string "@Hekili\Libs\SpellFlashCore\SpellFlashCore.lua"]:663: in function `?'
[string "@Hekili\Libs\SpellFlashCore\SpellFlashCore.lua"]:639: in function <Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:638>

Locals:
(*temporary) = "Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)"
```

### How to Reproduce

Change worlds or load game.

### Player Information (Link)

https://pastebin.com/CJ3HpSAj

### Error Messages (Link)

https://pastebin.com/M2d00JWR

**Comment by Hekili** [comment]
Fixed in https://github.com/Hekili/hekili/releases/v9.2.0-1.0.4a.
