### ISSUE TITLE
[BUG]  Hekili / SpellFlashCore produces lua errors.

### ISSUE THREAD

**Issue by Tga123** [Hekili/hekili#1373]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

From line 182 ``` if IsAddOnLoaded("ButtonForge") then ``` til line 245 in "SpellFlashCore.lua" there is support for another addon ["Button Forge"](https://www.curseforge.com/wow/addons/button-forge). Async loading here is no needed, coz this part of code load data from another already fully loaded addon. And async loading produces lua errors coz it unusual way to use it.

### How to Reproduce

Use Hekili with ButtonForge.

### Player Information (Link)

https://github.com/Hekili/SpellFlashCore

### Error Messages (Link)

https://github.com/Hekili/SpellFlashCore

### Additional Information

Errors from BugSack.
1) for "item" section
```raw
10x Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:223: table index is nil
[string "@Hekili\Libs\SpellFlashCore\SpellFlashCore.lua"]:223: in function <Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:217>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:35: in function <FrameXML\ObjectAPI\AsyncCallbackSystem.lua:31>
```
2) for "spell" section
```raw
6x Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:210: table index is nil
[string "@Hekili\Libs\SpellFlashCore\SpellFlashCore.lua"]:210: in function <Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:204>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:35: in function <FrameXML\ObjectAPI\AsyncCallbackSystem.lua:31>
```

**Comment by Hekili** [comment]
I'll pull the portion impacting ButtonForge.  The other implementation needs to run asynchronously or restart itself after a delay if item names aren't available when it tries the first time.  Otherwise, items simply will not flash.  Do you have plans to implement a different solution?

**Comment by Tga123** [comment]
I think, reverting old code only in button forge section and add "ButtonForge" to  "## OptionalDeps:" in "Hekili.toc" should be enough.

**Comment by Tga123** [comment]
I try last ([3340ed90a8ad66165b088e8d88588a355fdda78d](https://github.com/Hekili/SpellFlashCore/commit/3340ed90a8ad66165b088e8d88588a355fdda78d)) commit from ["async"](https://github.com/Hekili/SpellFlashCore/tree/async) branch - works great.

**Comment by Hekili** [comment]
Thank you!
