### ISSUE TITLE
[Feature] Soulletting Ruby

### ISSUE THREAD

**Issue by Lejes9X** [Hekili/hekili#1374]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Soulletting ruby is not suggested in rotation.
Pre 9.2, suggested based on distance from target.
9.2, does not suggest at all.

### Additional Information

With the trinket equipped, you will notice it does not suggest at all.

### Contact Information

Fayeshara#4867

**Comment by Hekili** [comment]
This is an issue with recommendations; submit the appropriate ticket with all of the required information.

https://github.com/Hekili/hekili/issues/new?assignees=Hekili&labels=recommendation%2Ctriage&template=Recommendation-Report.yml&title=%5BREC%5D+REPLACE+THIS+TEXT+WITH+YOUR+CLASS%2FSPEC+AND+BRIEF+ISSUE+DETAILS
