### ISSUE TITLE
Elemental Shaman - Primordial Wave not showing up in rotation.

### ISSUE THREAD

**Issue by ShiftyMcFly** [Hekili/hekili#1375]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Elemental Shaman - Primordial Wave not showing up in rotation.  I have checked that covenant abilities are on.  I spoke with Hekili on Discord and they stated that there was a spelling error.  Creating the ticket as a formality.

### How to Reproduce

Simply, the spell does not show up in any rotations, Single target/AOE/CD/Defensive etc.

### Snapshot (Link)

https://pastebin.com/DuReh2WZ

### Contact Information

Shiftymcfly#4325

**Comment by Hekili** [comment]
This is resolved.
