### ISSUE TITLE
GCD Swipe doesn't apply color/alpha scheme from ElvUI

### ISSUE THREAD

**Issue by rikdol** [Hekili/hekili#1376]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

**Copied from General Hekili Discord Chat (02-03-2022 15:53):** 
![image](https://user-images.githubusercontent.com/4119401/156397704-4b21ae74-ad1c-40be-8d76-5bb85b6dee66.png)

As requested:

Rik: Just to be clear, it's the GCD swipe im talking about. if i set this to classcolors for example, hekili will still show the 80% black overlay instead. 
There are also 2 options in hekeli to turn this option on, one for 'main' and one for 'queue'.

Hekili: Oh, yeah, it has never even occurred to me to colorize the spiral.  Can you put in a ticket as a feature request and I'll look into it?

Note: that in the screenshot the alpha is set to 0, but usually in ElvUI i have this set at 90%. So besides colorization, consider alpha also.

### Contact Information

Rik#9999

**Comment by Hekili** [comment]
Hey, this has been an older ticket, but the reason for this difference is that the addon uses your ElvUI *Cooldown Text* settings, not your *ActionBars* settings.  It appears fairly complicated to treat it like an action bar instead.
