### ISSUE TITLE
[BUG] Spellglow not highlighting "Final Verdict" in Ret Paladin rotation

### ISSUE THREAD

**Issue by Thackery-Binx** [Hekili/hekili#1377]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When playing as a ret paladin equipped with the "Final Verdict" legendary item (rank 6 cloak), the spellglow effect for Templar's (Final) Verdict is not highlighting the ability on the bar. Templar's Verdict is replaced automatically with Final Verdict when this legendary is equipped, I believe that the addon is still searching for an ability called "Templar's Verdict".

### How to Reproduce

1. Be a retribution paladin (60) in the Kyrian covenant.
2. Start combat
3. Start normal rotation until the next step in the queue is to use Templar's Verdict. The icon will appear in the queue but the spellglow effect will not highlight the Final Verdict ability on your bar.

Picture 1 shows the issue
Picture 2 shows Blade of Justice working as expected

![WoWScrnShot_030222_105313](https://user-images.githubusercontent.com/100786832/156398789-be393b8e-b401-49fa-a7c5-09095c338c48.jpg)
![WoWScrnShot_030222_105559](https://user-images.githubusercontent.com/100786832/156398793-a7da24dc-e7e9-4f7b-8fbb-c7043b473a9c.jpg)

### Player Information (Link)

https://pastebin.com/pzg6dV5U

### Error Messages (Link)

There are no error messages

### Additional Information

I can reproduce the same issue in MaxDPS addon. I constantly receive the error message that the spell "Templar's Verdict" could not be found on any action bar.

I have uninstalled and reinstalled both addons multiple times. I have deleted the entire WTF folder and started fresh but receive the same error. I have installed and reproduced the issue from the CurseForge app and WoWUP app. 

### Contact Information

thackery_binx#7442

**Comment by Hekili** [comment]
This may be an issue with SpellFlashCore.  I thought it was fixed overall, but it may not be detecting those frames.

If you type `/dump SpellFlashCore.IsFlashable("Templar's Verdict")` what output do you see?

You may need to report that issue to the SpellFlashCore maintainer.

**Comment by Hekili** [comment]
If you have SpellFlashCore installed separate of Hekili, you may try removing it.

If you move Templar's Verdict on your bars and then place it again, does the flash work?

**Comment by Thackery-Binx** [comment]
I do not have SpellFlashCore installed so far as I know, I just have the Hekili addon.

The output I received can be seen in the screenshot. Removing and re-adding the ability doesn't work, regardless of which action bar I put it on. In the screenshot below you can also see that the Templar's Verdict ability is renamed to Final Verdict. I'm not sure if that is what's causing the issue since the ability ID may be separate from Templar's Verdict.

![WoWScrnShot_030222_120605](https://user-images.githubusercontent.com/100786832/156411711-47e58d2b-b1ea-49ce-affc-e9a2bc86b499.jpg)

**Comment by Thackery-Binx** [comment]
Sorry, that screenshot shows the wrong output. I put Final Verdict instead of Templar's, but the output is no different if I use Templar's Verdict. The string that comes out is identical except it says: "Templar's Verdict".

**Comment by Hekili** [comment]
What addon is supplying your action buttons?

Is that Templar's Verdict button a macro?

**Comment by Thackery-Binx** [comment]
I have no addons that are supplying the action buttons. I drag and drop them from the in-game abilities book onto the action bars. I do have Bartender4 installed to move around the action bars, but I do not have any macros or addons for the action buttons themselves.

**Comment by Hekili** [comment]
If you're using Bartender4, your keybinds aren't being detected despite BT4 support being built in.  It would seem that SpellFlashCore has the same issue; not finding your BT4 bars.  Are you sure it's the official working version of Bartender?

**Comment by Hekili** [comment]
Will close if no response.

**Comment by Thackery-Binx** [comment]
I have Bartender4 installed via CurseForge so as far as I am aware it is the official working version. It is version 4.11.1 last updated 2022-02-24.

**Comment by Monkeychow66** [comment]
Hi I'm having the same issue.

The screenshot shows that Hekili identifies that I have Templar's Verdict on my bar, key bound to 3 but it should be Final Verdict as shown in the spell book and the tool tip.

The spell flash function works with well without the Legendary chest on.

Also Final Verdict ability is not listed in the Retribution Specialization

I hope this helps and I appreciate the work that goes into the addon.


![Screenshot 2022-04-16 212025](https://user-images.githubusercontent.com/103868396/163699343-0b873e29-2429-4762-9463-1bf8bfd8edf7.png)
[Hekili Char data.txt](https://github.com/Hekili/hekili/files/8500952/Hekili.Char.data.txt)

**Comment by Hekili** [comment]
Final Verdict is just treated as a "variant" of Templar's Verdict.  I have added code to try to help it flash, but I can't test it myself because PTR is down.  This will be in the next release tonight.

**Comment by Monkeychow66** [comment]
Tested it today and it is working. 

Thank you!

**Comment by Thackery-Binx** [comment]
I can confirm that this also works for me again on both Bartender4 and ElvUI. Thanks for looking into this!
