### ISSUE TITLE
Auto Snapshot on Venthyr Feral Druid

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1378]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During a mythic+ run the addon at some point stopped showing its recommendation and gave an automatic snapshot,

### How to Reproduce

I think it might be related to Venthyr druid because i did not have any auto snapshots on the other covenants but not sure.

### Snapshot (Link)

https://pastebin.com/rshPWSN1

**Comment by Hekili** [comment]
Please sim yourself and provide the link.  Thanks.

**Comment by Tzuyume** [comment]
My bad, "https://www.raidbots.com/simbot/report/wjqvavEtsEMSXsdzGJuVGi"

**Comment by Hekili** [comment]
I think this will be resolved in 1.0.6.  Reopen the ticket if you find it again.  It was related to timing Rake's refresh.
