### ISSUE TITLE
[ARMS] Impossible execute Auto/AOE display recommendation

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#1379]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Necro/Kyrian arms warrior.
When fighting 2+ targets above 60% health (every target has high health pull) using Auto or AOE displays a recommendation for an execute appears which is impossible to perform as targets have high health%.

### How to Reproduce

1. Enter a game as an Necro/Kyrian arms warrior
2.  Go to place with 2+ targets for dps (target dummies on top of Orgrimmar)
3.  Turn on hekili Auto or AOE rotation
4.  Follow addon recommendation (5-6 buttons) untill Execute recommendation appears. This recommendation is impossible to perform as target has more than 40% health and execute can not be performed.

### Snapshot (Link)

https://pastebin.com/VLKwi0C9

### Additional Information

In snapshot that recommendation that is impossible is under number 34.

[  34.  execute ( hac - 16 )
        The action (execute) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +0.94).
        List ( hac ) called from ( Arms:default:15 ) would PASS at 0.00.
        raid_event.adds.up[true] | spell_targets.whirlwind[3.00] > 1
         - this entry's criteria PASSES: buff.sweeping_strikes.up[true] | buff.sudden_death.up[false]
        Action chosen:  execute at 0.00!
        Returned from list (hac), current recommendation is execute (+0.00).
        - hac
        The recommended action (execute) is ready in less than 0.2s; exiting list (default).  ]

Charachter data link: https://pastebin.com/82H05X0G

### Contact Information

IIeTpoc#7401

**Comment by Hekili** [comment]
Can you post a screenshot as well?  Thanks.

**Comment by IIeTpoc** [comment]
![WoWScrnShot_030222_234055](https://user-images.githubusercontent.com/64799395/156448210-acbae662-7854-4a1a-8615-1a7c3d6a0067.jpg)
Sure!

**Comment by IIeTpoc** [comment]
Also I can add, that in Dual display mode Single Target display works as intended and doesnt reccommend such executes

**Comment by Hekili** [comment]
Thanks, should be fixed in 1.0.6.
