### ISSUE TITLE
Funnel Damage Bug - Wants me to use Black Powder Instead of Eviscerate

### ISSUE THREAD

**Issue by Fowka2** [Hekili/hekili#1380]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I main a Rogue - I have selected funnel damage but on the rotation it wants me to use "Black Powder" instead. I have been using these settings ever since but after the update, it's messed up. The settings that I run are "Auto" - "Cooldown" - "Covenants" "Use Priority Rotation (Funnel Damage)" "Allow Shadowmeld". Is there something I'm doing wrong which wants to us?

### How to Reproduce

1. Go to multiple training dummies
2.  Use the settings as "AUTO" - "COOLDOWNS", "COVENANTS", USE PRIO ROTATION (FUNNEL DAMAGE), "ALLOW SHADOWMELD"
3. Follow the addon till it says to use the talent "Shuriken Tornado" 

Instead of Eviscerate, it wants me to use Black Powder

### Snapshot (Link)

https://pastebin.com/WVyiNFtZ

### Contact Information

Xiaomajor#3090

**Comment by Hekili** [comment]
Fixed in 1.0.6.
