### ISSUE TITLE
ASSASSINATION ROGUE - SnD Recommended while more powerful version active

### ISSUE THREAD

**Issue by whoaisjustin** [Hekili/hekili#1381]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've been getting suggestions to use Slice n Dice, however I cannot use the spell as there is already a more powerful version active. I noticed this happen after equipping the Duskwalker's Loop legendary. Also, it's largely between combat, so perhaps it's fishing to use energy so it can get Vendetta off of Cooldown.

### How to Reproduce

This occurs during normal open-world gameplay. Typically after ending combat with one mob, before you begin combat with another.

### Snapshot (Link)

https://pastebin.com/Zw3y4Jfa

### Contact Information

SMARF#4578

**Comment by Hekili** [comment]
Thanks, should be fixed in 1.0.6.
