### ISSUE TITLE
[BUG][Root cause found] Constant main chat window spam for demonology warlocks

### ISSUE THREAD

**Issue by markdall** [Hekili/hekili#1383]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Immediately after installing Hekili 9.2.0-1.0.6 I started seeing spam in my main chat window in the form of a large decimal number and then 10. It's constantly spamming to where if someone says something in raid I can't read it, etc. 

The spam goes away if I disable Hekili and comes back if I enable it. 
![image](https://user-images.githubusercontent.com/238194/156507877-552ca919-b85f-4b92-aaca-18b39ad61d0d.png)

### How to Reproduce

1. Install 9.2.0-1.0.6. 
2. Login or reload ui. 

Expected result: Not spam. 
Actual result: spam. 

### Player Information (Link)

https://pastebin.com/b4L7kGd1

### Error Messages (Link)

There's nothing in bugsack.

### Additional Information

Sample of the output in the chat window: 0.010874935542233 10

**Comment by markdall** [comment]
Data point: It doesn't do it while I'm dead. When I release, it comes back.

**Comment by markdall** [comment]
It also stops happening if I switch specs from Demonology to Destruction. When I switch back to Demonology, the spam returns.

**Comment by markdall** [comment]
Commenting out line 133 of Classes\WarlockDemonology.lua fixed the problem. 
![image](https://user-images.githubusercontent.com/238194/156517270-4af3f1e5-2c0d-4a22-a4b0-0bdbbf0428dd.png)

**Comment by DiscordGregory** [comment]
Yep, was coming here to post this same thing lol.

**Comment by markdall** [comment]
I debugged it while raiding, lol.

**Comment by nijaru** [comment]
I assume it's from the update to demonology today. I haven't had issues with other classes

**Comment by markdall** [comment]
> I assume it's from the update to demonology today. I haven't had issues with other classes

Yes: https://github.com/Hekili/hekili/blame/shadowlands/Classes/WarlockDemonology.lua#L133

Someone left in a print debug statement. I've done that many times myself.

**Comment by Bun10** [comment]
Same issue, Demo Warlock, streaming numbers in chat window.  Hekii only addon running.  Disabled the numbers are absent.

**Comment by Bun10** [comment]
I applied Markdall's fix which worked.  Ty Markdall, for those of us oblivious to lua you explained it perfectly.

**Comment by Hekili** [comment]
Yeah, this is fixed in 1.0.6a; sorry for the spam.  I've also made it so that prints within the emulated state environment will be suppressed if you're not in developer mode.
