### ISSUE TITLE
[Surv Hunter] Addon does not correctly recommend Volatile Bomb in AOE and ST

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1384]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello. I noticed incorrect rotation using Volatile Bomb. The bug manifested itself when the buff from Serpent Sting fell off the target in AOE and the addon recommended using Volatile Bomb without Serpent Sting's DotA. And this is a loss of dps. Since Volatile Bomb deals more damage when the Serpent Sting dot is active on the target. 
I suppose I see so that the addon should react a little earlier to the fall of the Serpent Sting of the target. He must refresh it with either Serpent Sting ability, or Volatile Bomb if we have it ready, or 1-2 seconds remain before Volatile Bomb is ready and 2 seconds remain before the debuff from the Serpent Sting dot drops.

### How to Reproduce

Use Serpent Sting on the target.
We are waiting for the fall of the debuff Serpent Sting.
Before the debuff subsides, we must have a Volatile Bomb, or it remains until it is ready for 1-2 seconds

### Snapshot (Link)

https://pastebin.com/4fyTEeYQ

### Additional Information

https://imgur.com/a/dXjmCDN

**Comment by Hekili** [comment]
Sim yourself in AOE (either HecticAddCleave or Patchwerk with 3+ targets) and provide the link.  There may be a priority issue that would be true of your sim as well.

**Comment by Dragonfo** [comment]
https://www.raidbots.com/simbot/report/2mQwXKWFYFLkbdAYEmH81t Patchwerk with 3+ targets
https://www.raidbots.com/simbot/report/3zDLLE416GnK6xPJ1uh2Uf  HecticAddCleave
https://www.raidbots.com/simbot/report/gwaZeTxCxXXbJuJFV2z6Nk DUNGEON SLICE

**Comment by Hekili** [comment]
This behavior is pretty consistent with your sims (you can see multiple Wildfire Bombs before using Serpent Sting, with your specific talents).  It doesn't really match guides, though.  I'll keep an eye out for updates to the sim profile.

**Comment by Dragonfo** [comment]
Well, I'll wait then for future updates. Thanks
