### ISSUE TITLE
[Demonology] Niya opener is broken

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#1385]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Opener is not correct when playing Niya, but appears to be fine with DW.

### How to Reproduce

This can be reproduced by playing niya and precasting demonbolt into soul rot - it breaks as you are casting soul rot. Unsure how it manifests with other trinkets, but this is the meta build right now and its totally not right.

### Snapshot (Link)

https://pastebin.com/ViKdtuKA

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/whhvGoCYNHqZDkNHQjLznC

### Contact Information

dubu#2080

**Comment by dubudevs** [comment]
https://pastebin.com/VWDKrekp precombat
https://pastebin.com/aswebS1i when casting SR after DB

**Comment by Hekili** [comment]
I'm not 100% sure those new snapshots are using the alpha (maybe you pasted the files, maybe you didn't, maybe didn't reload?), but I can't replicate the issue on this end.  I'm going to do a second alpha build that puts in more debugging information in the snapshots and ask you to snapshot again later.

I'd again want a snapshot before casting Soul Rot and during/after casting Soul Rot, if your trinket jumps to the front. 

https://github.com/Hekili/hekili/archive/refs/tags/v9.2.0-1.0.7-alpha2.zip

**Comment by dubudevs** [comment]
I checked that, I first renamed the old files, then deleted when the behaviour was the same, deleted both, restarted game, I will try again after raid.

**Comment by Hekili** [comment]
It's easier to just drop in the zip to avoid missing something IMO.  The new version will snapshot more info that will help figure it out if this is still unresolved.

**Comment by dubudevs** [comment]
It appears to be working, but the demo opener still doesn't quite appear to be doing the correct thing. This isn't a new development, though. It frequently doesn't fill the time completely (ie it can cast another db to get 3 shards for the final hog, or even 2 SBs), but I think this might be an APL problem. It might even be the first tyrant variable, but it happens with DW and Niya.

**Comment by Hekili** [comment]
Yeah, that issue is an APL problem that'll get swept away with APL changes anyway.  You could definitely squeeze in more if logic were built around "how many shadow bolt/demonbolt casts can I complete, followed by HoG and Tyrant" without a major demon expiring.
