### ISSUE TITLE
[REC] BM Hunter - The First Sigil trinket not recommended when equipped

### ISSUE THREAD

**Issue by felidaetsavo** [Hekili/hekili#1386]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I expect the addon to recommend use of The First Sigil trinket once it comes off cooldown, or at some point during the fight (i.e. during bloodlust, etc.).  However, it never appears as a recommended option during an encounter.

### How to Reproduce

1. Enter game as BM hunter.
2. Have "The First Sigil" trinket equipped in the first or second trinket slot.
3. Start encounter with Dapperdew in the amphitheatre in Ardenweald.
4. Engage with the summoned boss, performing the recommended actions from Hekili, and note the recommendations.

Result:  The First Sigil trinket is not listed as a recommendation during the encounter.

### Snapshot (Link)

https://pastebin.com/dtpA4dzS

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/uxy7QLUYnqkkxCjshU8oSa

### Contact Information

Beck#3245  (Discord)

**Comment by Hekili** [comment]
This should be fixed in the 1.0.7-alpha2 (and will be in 1.0.7 release when it's ready).  Thanks.
