### ISSUE TITLE
[BUG] Occasional LUA error on login/reload on ExactTime

### ISSUE THREAD

**Issue by Fringetastic** [Hekili/hekili#1387]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On March 2 and 3, 2022, with version v9.2.0-1.0.6a, I have gotten this LUA error when logging into the game on my feral druid. It also happens on some /reloads but not all of them.

I also found that the opening sequence changed drastically on wipes to Artificer that a reload would correct but I bet that is something separate.

### How to Reproduce

1. Enter game as Feral Druid with talents 2-3-1-1-1-3-2. I have not tried with other talents.
2. Get LUA error.

### Player Information (Link)

https://pastebin.com/xrR02EcB

### Error Messages (Link)

https://pastebin.com/Y4jpHzxj

### Contact Information

Fringe#6272 or twitter @Frngtstc

**Comment by Hekili** [comment]
This will be resolved in the next release.  Thanks!
