### ISSUE TITLE
[FEATURE] Add Warrior Spell Reflection to the Interrupt or Defensive Displays

### ISSUE THREAD

**Issue by acastaner** [Hekili/hekili#1389]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I think Hekili would greatly benefit if it would display a notification (like it does for Interrupts) for Warriors' Spell Reflection ability. It's a huge damage and defensive booster that not a lot of Warriors use because it's not always clear which spell can be reflected. Adding it to Hekili would be immensely appreciated by Warriors all over Azeroth.

There's already a Weak Aura that does this but, in my experience, it can be buggy and I feel it would be better integrated in Hekili (WA doesn't check if the ability is on cooldown, for instance).

The challenge is that not all spells are reflectable, but the WA actually as a very good list to start from. It's located there: https://wago.io/SpellReflectionTracker

### Additional Information

If someone was to start implementing the structure to support this, I'd be happy to go through the daunting task of manually adding all the spell IDs to the code and then make the pull request.

We would also need an efficient way to add new spells as patches and raids are added, maybe through some logging function (not sure what's possible here).

### Contact Information

SleepyPuffin#1171 (Discord)

**Comment by Hekili** [comment]
I'll keep this open as a feature enhancement; I'm not opposed but it needs a lot of UI work to be particularly useful, and it would be secondary to other plans (simplifying adding defensives/utility in general).

**Comment by Hekili** [comment]
This will be default behavior for Spell Reflection across the board, for all Warrior specializations, in an upcoming release.
