### ISSUE TITLE
[FEATURE] DH Havoc - Another option for recommended movements. 

### ISSUE THREAD

**Issue by Palcave** [Hekili/hekili#1393]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I find that the following option would be a real plus for the addon. 

To have another possibility than "Recommended movements" which would use Fel Rush only when buffed by "Unbound Chaos". This would allow to have always some stacks of "Fel Rush" and not to overuse it as when "recommended movements" checked.

**Comment by ijoihlhnn** [comment]
just be mindful about when to use felrush.

**Comment by Hekili** [comment]
I've added a setting for this that is testable in the 1.0.8-alpha2.
