### ISSUE TITLE
[REC] Ret Seraphim is never recommended when cooldowns are disabled or shown separately

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#1394]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Even though Seraphim itself doesn't use the cooldown toggle, it is never recommended when
- the cooldown toggle is disabled or set to show separately
- and the talent Final Reckoning is used
- and the talent Execution Sentence isn't used

### How to Reproduce

1. Play as Ret Paladin with Seraphim and Final Reckoning talents, but without the Execution Sentence talent.
2. Either disable cooldowns in Hekili or configure them to show separately.
3. Verify that Seraphim is not configured to use the cooldowns toggle.
4. Build to 5 Holy Power.
5. Notice that Seraphim is not recommended. (Neither on the primary display, nor on the cooldowns display.)
6. Enable cooldowns in Hekil (not shown separately).
7. Build to 5 HP again.
8. Notice that Seraphim is now recommended.

### Snapshot (Link)

https://pastebin.com/JzBRcE5c

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/e1aGq75UvNmReZ1uJueNWT

### Additional Information

It seems like the problem is the new split priority list. If Final Reckoning is enabled, but Execution Sentence isn't, and cooldowns are disabled/shown separately, the priority list "es_fr_pooling" is never called because "cooldown.final_reckoning.remains" is always at 60.
And the second place where Seraphim would be shown, in the "finishers" priority list, never shows Seraphim if Final Reckoning is enabled.

So the issue is actually not just about Seraphim, but about the whole "es_fr_pooling" priority list.

I've played around a bit with the condition for the "es_fr_pooling" priority list. But I couldn't find one that works correctly if cooldowns are disabled/shown separately. You can't just change it to include something like "| cooldown.final_reckoning.remains = 60" because then it will always trigger and the "es_fr_active" priority list will never be reached (which is required for other things, e.g. Divine Toll is never shown without it).

**Comment by Hekili** [comment]
With CDs disabled, you don't want to follow ES FR Pooling logic anyway, because that's literally meant to be the 9 seconds leading up to using those CDs.  Which you might not do.

I made adjustments to the regular availability of Seraphim in the Finishers list that seems to work okay.  It's testable in 1.0.8-alpha1.
