### ISSUE TITLE
Issue with key-binds lining up with the display

### ISSUE THREAD

**Issue by Acelisss** [Hekili/hekili#1395]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hey! i have my keybinds setup for a druid i recently xfer'd, i switched them around, but said keybinds didnt update, like thrash from being shift 1, to my mouse button 5, in the rotation display

### How to Reproduce

1. Log into the character
2. Display doesnt line up with keybinds.

### Player Information (Link)

build: v9.2.0-1.0.7 level: 60 (60) class: DRUID spec: feral  talents: balance_affinity     bloodtalons     mighty_bash     primal_wrath     sabertooth     soul_of_the_forest     tiger_dash  pvptalents: none  covenant: night_fae  conduits: born_anew = 9    born_of_the_wilds = 8    carnivorous_instinct = 10    conflux_of_elements = 7    taste_for_blood = 9    wellhoned_instincts = 10  soulbinds: [niya]    bonded_hearts = 1    grove_invigoration = 1    natures_splendor = 1    niyas_tools_poison = 1    run_without_tiring = 1    survivors_rally = 1  sets: jotungeirr_destinys_call = 1  gear: arachnid_cipher_ring = 1     azurevenom_choker = 1     bands_of_the_undergrowth = 1     cloak_of_enveloping_manifestations = 1     daschlas_defiant_treads = 1     freshly_embalmed_jerkin = 1     jotungeirr_destinys_call = 1     loyal_kvaldirs_handwraps = 1     phial_of_putrefaction = 1     ring_of_perpetual_conflict = 1     sapgorger_belt = 1     smugglers_plundered_pauldrons = 1     titanic_ocular_gland = 1     umbrahide_leggings = 1     vicious_surge_faceguard = 1  legendaries: celestial_spirits = 1  itemIDs: 172318, 178699, 178702, 178744, 178771, 178851, 178872, 178933, 180106, 180115, 186295, 186298, 186299, 186404, 186423  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     package = Feral     petbased = false     potion = spectral_agility     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     owlweave_cat = false  toggles: cooldowns = false     custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      barkskin                   =     bear_form                  = SD  [04]     berserk                    = SQ  [06]     berserking                 =     brutal_slash               = M4  [06], 2   [08]     cat_form                   = SA  [04]     celestial_alignment        =     convoke_the_spirits        = SMwU[05]     darkmoon_deck_putrescence  =     dash                       =     ferocious_bite             = S2  [01], S2  [07]     frenzied_regeneration      =     fury_of_elune              =     growl                      =     heart_of_the_wild          =     hibernate                  =     incapacitating_roar        =     innervate                  =     inscrutable_quantum_device =     ironfur                    =     mangle                     =     moonfire                   =     moonkin_form               = SW  [04]     overcharged_anima_battery  =     primal_wrath               = 3   [01], 3   [07]     prowl                      = X   [01], X   [07]     rake                       = 2   [01], 2   [07], 3   [08]     rebirth                    =     rip                        = S1  [01], S1  [07], S2  [08]     shred                      = 1   [01], 1   [07], 1   [08]     solar_beam                 =     soothe                     =     stampeding_roar            =     starfall                   =     starfire                   =     starsurge                  =     sunfire                    =     swipe                      = M4  [06], 2   [08]     swipe_bear                 = M4  [06], 2   [08]     swipe_cat                  = M4  [06], 2   [08]     thrash                     = M5  [06], S1  [08]     thrash_bear                = M5  [06], S1  [08]     thrash_cat                 = M5  [06], S1  [08]     tiger_dash                 =     tigers_fury                = SE  [06]     travel_form                = SS  [04]     typhoon                    =     ursols_vortex              =     wrath                      =

### Error Messages (Link)

None from the addon

### Contact Information

Acelis#1111 (discord)

**Comment by Hekili** [comment]
Please put your Player Information on Pastebin and provide the link.

**Comment by Hekili** [comment]
So, the addon can see that Thrash is on M5 on your 6th actionbar and also S1 on your 8th actionbar.  The addon has to make assumptions about which bar to pull the keybind from, which is based on your form.

In cat form, the addon looks at bar 7 first (default cat bar) then bar 8 (default prowl bar), then it looks at 1-6 and 9-10.  If you're prowling, it looks at bar 8 first, then bar 7, then 1-6 and 9-10.

If you don't want Thrash to show with S1, remove it from bar 8.  Or rebind it on bar 8 to M5.

If you don't want to worry about which bar your abilities are on, you can manually set the keybind text for each ability via /hekili > [Ability Name] > Override Keybind Text.
