### ISSUE TITLE
sometimes the addon does not show up the indicazione about the spell to use

### ISSUE THREAD

**Issue by gafralo** [Hekili/hekili#1396]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

any time I log in - with any character I have - hekili foget all settings and I have to reset everything. I checked if the addon was enbled and it is and more: once i defined my setting the addon work very well, nothing to complain about, and it does with all my alts. It's when I loggin - I repeat it to be clear - that the addon does not show up the usual indicatione on the spell to use and I have to reset everything. Can you help me understanding and solving what's going on? (my english is not perfect but i hope you got it)

### How to Reproduce

random with several alts and main character

### Player Information (Link)

build: v9.2.0-1.0.7 level: 60 (60) class: HUNTER spec: beast_mastery  talents: animal_companion     aspect_of_the_beast     born_to_be_wild     natural_mending     scent_of_blood     stomp     thrill_of_the_hunt  pvptalents: none  covenant: night_fae  conduits: ambuscade = 7    cheetahs_vigor = 8    condensed_anima_sphere = 7    ferocious_appetite = 8    rejuvenating_wind = 8    spirit_attunement = 8  soulbinds: [plasmasogni]    dream_delver = 1    faerie_dust = 1    field_of_blossoms = 1    podtender = 1    social_butterfly = 1    waking_dreams = 1  sets: overcharged_anima_battery = 1  gear: anello_fuso_alla_carne = 1     arbalestra_brunita = 1     batteria_di_animum_sovraccaricata = 1     bracciali_dellinno = 1     calzari_foderati_enigmatici_ricreativi = 1     cinta_dellinno = 1     collare_intagliato_col_codice = 1     copricapo_enigmatico_sincrono = 1     cortina_dei_regni_taciuti = 1     cotta_di_maglia_enigmatica = 1     gambiere_rinforzate_spaccaossa = 1     insegna_di_gilda_rinomata = 1     overcharged_anima_battery = 1     presa_paralizzante_di_zatojin = 1     simbolo_di_lupino = 1     spalline_enigmatiche = 1     vera_di_guscio_della_matriarca = 1  legendaries: rylakstalkers_piercing_fangs = 1  itemIDs: 172326, 178869, 180116, 188025, 188026, 188040, 189939, 189985, 190357, 190362, 190597, 190634, 190730, 190743, 190994, 69210  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = false     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     package = Beast Mastery     petbased = false     potion = spectral_agility     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     avoid_bw_overlap = false     barbed_shot_grace_period = 0.5     check_pet_range = true  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true [separate]     essences = false      interrupts = true [separate]     mode = automatic      potions = false   keybinds:      arcane_shot               = SB  [05]     aspect_of_the_cheetah     = F6  [06]     aspect_of_the_turtle      = F5  [06]     aspect_of_the_wild        = D   [05]     barbed_shot               = 2   [01], 2   [02]     bestial_wrath             = F3  [06]     cobra_shot                = 3   [01], 3   [02]     concussive_shot           = 0   [01], 0   [10]     counter_shot              = F1  [06]     disengage                 = T   [06]     exhilaration              = Y   [05]     feign_death               = F4  [06]     flare                     = F8  [06]     freezing_trap             = E   [06]     hunters_mark              = H   [05]     intimidation              = SX  [05]     kill_command              = 1   [01], 1   [02]     kill_shot                 = 4   [01]     mend_pet                  = 5   [01]     multishot                 = 6   [01]     overcharged_anima_battery = F   [05]     primal_rage               = 8   [01]     shadowmeld                = SC  [05], 0   [07]     tar_trap                  = R   [06]     tranquilizing_shot        = F2  [06]     wild_spirits              = G   [05]a sample of the customization of my main

### Error Messages (Link)

no error message

**Comment by Hekili** [comment]
Please put your Player Information on Pastebin and provide the link.

**Comment by Hekili** [comment]
So, which settings are actually forgotten, specifically?

Change those settings, let me know what you changed, log out.  Post your Hekili.lua from your profile's SavedVariables.

Log in.  Are they different?  Which specific settings are turning off?

Does it happen with the latest alpha version?  https://github.com/Hekili/hekili/releases/download/v9.2.0-1.0.8-alpha2/Hekili-v9.2.0-1.0.8-alpha2.zip
