### ISSUE TITLE
Autosnapshot as Arcane Mage

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1397]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Getting autosnapshot while at the last boss in Spires of Ascension in the end as a Necrolord Arcane mage

### How to Reproduce

Playing Necrolord Arcane mage in the end of a boss fight in end of Spires of Ascension i get auto-snapshot.

### Snapshot (Link)

https://pastebin.com/DdCT3NWf

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/73632t2za2PbXH5LJ2pQgL

**Comment by Hekili** [comment]
What did you think should've been recommended?

**Comment by Hekili** [comment]
Actually, I found the `final_burn` variable was calculating incorrectly, which might've prevented this from happening.  I'll post a new alpha soon.

**Comment by Tzuyume** [comment]
Maybe im posting the autosnapshots in the wrong place? It feels unintended when addon stops working for a while and does a snapshot before it returns to normal.

**Comment by Hekili** [comment]
Why would you think that?

**Comment by Tzuyume** [comment]
well i dont know what should be recommended, just feels like it shouldn't stop recommending things.

**Comment by Hekili** [comment]
Yes, I agree.  I wasn't suggesting it should stop making recommendations.

**Comment by Hekili** [comment]
Closing; 1.0.8 should address it.  If I'm wrong, feel free to reopen.
