### ISSUE TITLE
[FEATURE] Divine Resonance legendary should predict future Holy Power gain and Judgment debuffs

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#1398]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

It would be great if the [Divine Resonance](https://www.wowhead.com/spell=355455/divine-resonance) buff from the legendary of the same name would be used to predict future Holy Power and Judgment debuffs. That would reduce sudden changes in the recommendations when a Judgment from that buff lands.

### Additional Information

I'm not sure if this should already work for Holy Power, since there is a mention of "divine_resonance" under `RegisterResource` in both Paladin class modules. But if that's the case, it seems like this is not working correctly. So then this issue would be half bug and half feature request.

For example, take this snapshot: https://pastebin.com/VVfDyDCL
Here the Divine Resonance buff fades between recommendations 2 and 3. But recommendation 3 assumes only one more Holy Power than recommendation 2, which would be the one from Crusader Strike used at recommendation 2. If Divine Resonance would be used, there should be one additional Holy Power here.

**Comment by Hekili** [comment]
Good catch; the calculation for when the last tick happened is incorrect.  I'll fix.

Note that the reapplication of the Judgment debuff isn't presently modeled, but I'm open to including it if we're confident it will impact recommendations.

**Comment by cremor** [comment]
Thanks for fixing the Holy Power prediction.

About the Judgment debuff:
Here is a snapshot that shows how that would change recommendations: https://pastebin.com/r76meEmc

Recommendation 2 is Judgment (generators 6) here. But with a Judgment debuff prediction that would not have been the case, since it has a `!debuff.judgment.up` condition.
At least I hope that I read this correctly and at this point in time a Divine Resonance Judgment would have hit. I think this should be the case because recommendation 2 shows `holy_power.current[2.00]` in it's log but it would only be one Holy Power without an additional Judgment hit (4 HP at time of snapshot minus 3 HP from using Templars Verdict as the first ability).

**Comment by Hekili** [comment]
Alright, I've added the Judgment casts to the model.  Will be in next release.
