### ISSUE TITLE
Icons disappear when only 1 icon is set to display

### ISSUE THREAD

**Issue by cuetip** [Hekili/hekili#140]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
i have icon shown set to 1 and it was working just fine till after i race changed to zandalar, assassination rogue, when it starts the rotation after about 3 attacks the icons disappear and don't continue with the rotation. if i set 2 or more icons shown it works. after awhile i get a pop up stating your addons are experiencing a large number of errors and may be slowing down the game. only happens on rogue no other toons.

**Expected behavior**

i expected the display icon to work with one icon like before where it would just do the rotation and continue on to what to hit next.

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.
build: v8.1.5-18-beta1
level: 120
class: ROGUE
spec: assassination

talents: cheat_death
    elaborate_planning
    iron_wire
    subterfuge
    poison_bomb
    toxic_blade
    vigor

traits: azerite_empowered=3
    double_dose=2
    gemhide=1
    gutripper=1
    meticulous_scheming=1
    nothing_personal=1
    overwhelming_power=2
    resounding_protection=1
    scent_of_blood=1
    shrouded_suffocation=1
    vampiric_speed=1

sets/legendaries/artifacts: none

gear:     razzashi_tooth_medallion=1
    blood_bog_shoulderpads=1
    fairweather_tunic=1
    latticework_scalpel=1
    sandshined_snakeskin_sandals=1
    loop_of_pulsing_veins=1
    wharf_wardens_gloves=1
    galecallers_boon=1
    seal_of_questionable_loyalties=1
    honorbound_outriders_pants=1
    howlis_crystal_shiv=1
    heart_of_azeroth=1
    honorbound_outriders_buckle=1
    parrotfeather_cloak=1
    venerated_raptorhide_bindings=1
    seafarer_headcover=1

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by cuetip** [comment]
also, i am running the hekili version 8.1.5-18-beta, have tried reverting to 8.1.5-14 and still same issue.

**Comment by Hekili** [comment]
Go to -13 for the time being.

**Comment by cuetip** [comment]
nice, fast response, -13 works perfect, also appreciates the add-on and everything you do with it.

**Comment by Hekili** [comment]
Alright, I have a potential solution in v8.1.5-18-beta2 going up. Please let me know if it works for you!

**Comment by cuetip** [comment]
yeah it works in the beta 2, sorry for delayed response, thanks
