### ISSUE TITLE
Kyrian Balance Druid recommending cancelling Primordial Arcanic Pulsar

### ISSUE THREAD

**Issue by Foraga88** [Hekili/hekili#1401]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Kyrian balance druid rotation looks to be frequently recommending a cancelaura of Primordial Arcanic Pulsar bff. When I pause the addon and mouseover, it refers to a line that suggests cancelling to better line up Convokes - something Kyrian druids dont have. 

### How to Reproduce

Unable to give specifics, but often CA and/or Kindred Spirits is on CD and Arcanic stacks are low

### Snapshot (Link)

https://pastebin.com/L5DqTNrW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tReMvZrZ1kZKAJBjvQdACS

**Comment by Hekili** [comment]
Sim yourself and provide the link.

> Raidbots Sim Report (Link):

**Comment by Foraga88** [comment]
https://www.raidbots.com/simbot/report/tReMvZrZ1kZKAJBjvQdACS

**Comment by ElMorz** [comment]
Hi, I'd like to mention I'm playing a Venthyr balance druid and I also get a starssurge with a red 'x' on it as well.

**Comment by Hekili** [comment]
Thanks.  Looking closely at the snapshot, I've found that there is an issue with priorities that use `@` (abs) being interpreted incorrectly.  I'm working on a fix.

You can disable the relevant entries in your priority by going to /hekili > Priorities > Balance > Action Lists > select `st` > select `24` and uncheck Enabled.

**Comment by Hekili** [comment]
Version 1.0.8 will resolve the issue where `@` was breaking the conditions for the `cancel_buff` entry.  Let me know if it still appears for incorrect specs.
