### ISSUE TITLE
[BUG] Demonology Imps not in the recommendation since 1.0.8 update

### ISSUE THREAD

**Issue by Statticc** [Hekili/hekili#1403]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

with version 9.2.0 1.0.7 The Auto and AoE display modes would suggest implosion for Demonology in any aoe/cleave situation, in M+, open world, dummies etc, even at the end of an encounter to use the resource.

Since the 9.2.0 1.0.8 update, this no longer occurs.  There is no Implosion recommendation/suggestion in Auto or AoE display modes.

### How to Reproduce

DPS'ing in any cleave/aoe situation.  There simply are no implosion recommendations in the display anymore since the update.

### Player Information (Link)

https://pastebin.com/DHb5TL4C

### Error Messages (Link)

no errors displayed

**Comment by Hekili** [comment]
Wrong kind of ticket, this is about recommendations so use that ticket and submit the required information.

**Comment by Statticc** [comment]
I'm not sure how this is a recommendation.  The rotation used to suggest implosion in 1.0.7, now with 1.0.8 it doesn't. So is it not a bug or an oversight of some sort?

**Comment by Hekili** [comment]
Closing this one, will use the other ticket.
