### ISSUE TITLE
[FEATURE] The ability to move Potions from Primary to Cooldowns

### ISSUE THREAD

**Issue by j-mes** [Hekili/hekili#1404]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

For example: I've moved Wild Spirits from the Primary/AOE boxes into Cooldowns because it is to me a cooldown that needs to be held back sometimes in the raid fights or in M+.

![image](https://user-images.githubusercontent.com/5721977/157220323-5d216a29-efb4-43cb-9150-d205252847df.png)

However I'd love to see the ability to do the same for potions as currently I double pot or use pot on CD in M+ when needed.

### Additional Information

This addon rocks. It helps so many people when they're learning a new spec or class. Keep up the good work 😄 

### Contact Information

Howl#0005

**Comment by Hekili** [comment]
I didn't realize you couldn't do this, to be honest.

**Comment by j-mes** [comment]
It's a minor QoL thing which would be handy. I hope it's not a huge thing to do though.

**Comment by Hekili** [comment]
The potion ability will be listed in the Gear and Items section in the next release.
