### ISSUE TITLE
[Demonology] Precombat shadowbolt or demonbolt recommended if you already have 5 shards

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#1407]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since this is not something that will ever happen in sims, it is not accounted for at all. If you have 5 shards before you enter combat the APL still recommends to precast shadowbolt or doombolt to generate shards (thinking you must have 3, since you're not in combat).

### How to Reproduce

Get 5 shards, leave combat, check recommendations.

### Snapshot (Link)

-

**Comment by Hekili** [comment]
It does but...it's fine?  What else are you going to push pre-pull?

**Comment by dubudevs** [comment]
Hand of Guldan or dogs most likely. In any situation where you have 5 shards and you're not in combat you're probably not going to be able to effectively "precast", you will be better off waiting for tank to pull and then dropping GFG or instant cast dogs if you don't want to precast. If the tank pulls as you're precasting thats just wasted damage, and its definitely not worth risking pulling for the tank. Even if you are trying to precast, at 5 shards you will want to precast hog or dogs like I mentioned.

I don't see any issue with telling it to just skip the shard gen precast if you don't need shard gen. It should handle it fine.

**Comment by Hekili** [comment]
I don't agree with some of your logic -- it's no more risky to precast at 5 shards, in terms of pulling from the tank, than precasting at any other time.

Not wanting to waste shard generation in the "opener" makes sense, except if you're at 5 shards you're probably not going to do an actual opener on this pull.

I'll tinker with it and see what it ends up looking like, but this is very likely not a thing that matters at all.

**Comment by dubudevs** [comment]
> it's no more risky to precast at 5 shards, in terms of pulling from the tank, than precasting at any other time.

In raid it's not risky to precast at all, in m+ (when you are potentially going to have 5 shards going into combat) it is risky at any time, chances that you will time it correctly even in very coordinated keys are slim so its either a time loss or a pain for the tank. The difference at 3 shards is that by precasting you actually gain 2.66 globals which is arguably worth the risk over the 2500 damage or however much a demonbolt does.

> Not wanting to waste shard generation in the "opener" makes sense, except if you're at 5 shards you're probably not going to do an actual opener on this pull.

Sure you are likely to do an actual opener, you are just as likely as any other time. I know that if I plan on opening with tyrant in the next pack I will make sure that I end this pack with 5 shards so I don't need to waste casts generating shards.

> I'll tinker with it and see what it ends up looking like, but this is very likely not a thing that matters at all.

It doesn't really matter, but its just strange to see SB suggested when I'm sitting at 5 shards about to open and SB is the last thing I want to be casting.

**Comment by Hekili** [comment]
> in m+ (when you are potentially going to have 5 shards going into combat) it is risky, chances that you will time it correctly even in very coordinated keys are slim so its either a time loss or a pain for the tank.

This is an argument for not precasting anything in M+, which is probably not what you're going for.

I don't like "kitchen sink" arguments where you toss in everything that supports getting the outcome you want, because the actual reason is the only one that matters.  And I get that overcapping shards feels bad.

> Sure you are likely to do an actual opener, you are just as likely as any other time. 

When you are starting combat with 5 shards, the current state of your CDs is infinitely more likely to be desynchronized than a fresh pull with all CDs at 0 and 3 shards.

> It doesn't really matter, but its just strange to see SB suggested when I'm sitting at 5 shards about to open and SB is the last thing I want to be casting.

This part is true.  It does feel odd.  I'll tinker with it and see what happens.  There's a good chance this exacerbates the other concern you had about casting Tyrant sooner than you had to (when you could've generated a few more imps).  But I'll look at it.

Is the "new" Demonology priority going into SimC any time soon?

**Comment by dubudevs** [comment]
> This is an argument for not precasting anything in M+, which is probably not what you're going for.

I edited this in after a few mins, I should have added it as a reply: The difference at 3 shards is that by precasting demonbolt you actually gain 2.66 globals which is arguably worth the "risk" where the 800 single target damage of a shadowbolt at 5 shards is (imo) never worth it. 

I'd sooner see no precasting recommended in m+, though.

> with 5 shards, the current state of your CDs is infinitely more likely to be desynchronized

True, but you still want to be precasting something that isn't shardgen if you do indeed want to precast. For demo the shardgen damage is basically zero (shadowbolt does legit like 800 damage and demonbolt is practically impossible to time without a countdown, and SB is what is recommended in m+ because they are non-boss). I am 100% going to take getting into my ramp up to a whole global earlier over a single shadowbolt of damage. 

I wouldn't hold your breath for the new APL going live soon. It still needs to be optimised and then checked and tweaked for all of the other builds.

**Comment by dubudevs** [comment]
FWIW: Dogs is basically always up because its such a short CD, and in 15-20 keys you are tyranting basically every pack anyway because packs will live for about 40 seconds, at which point tyrant is at ~25 seconds cd and you are a few seconds off starting your ramp again, which is taken by moving to the next pack. It's not unusual to tyrant at the start of more than half the packs in a dungeon.

**Comment by Hekili** [comment]
It's pretty trivial to test the "don't cast generators" at 5 shards precombat logic and see where it ends up.  When servers are online.

It'll be interesting to see if that will apply more pressure toward delaying the last HoG before summoning your Tyrant.

**Comment by dubudevs** [comment]
EU servers are still up, I will have a play with it. `! ( boss | action.demonbolt.cast = 0 ) | soul_shards > 3 & soul_shards < 5` should do the trick right?

**Comment by Hekili** [comment]
I think you want, for Demonbolt:
`soul_shards < 4 & ( boss | action.demonbolt.cast = 0 )`

Shadow Bolt:
`soul_shards < 5 & ! ( boss | action.demonbolt.cast = 0 )`

**Comment by dubudevs** [comment]
https://puu.sh/INvSB/94a86815ed.png Hmmmmmmmmmmm something is not right here lol

My screenshotting skills are insane, I have 5 soul shards here.

**Comment by Hekili** [comment]
Yes, the `|` you have in there means "or" so the left side doesn't matter and so the condition considered is `soul_shards > 3 & soul_shards < 5`.

> My screenshotting skills are insane, I have 5 soul shards here.

Not after casting Grimoire Felguard (edit: or Summon Felguard) you don't.

**Comment by dubudevs** [comment]
That's summon felguard, good point. That'll do it. I always forget it consumes a shard.

**Comment by Hekili** [comment]
> I always forget it consumes a shard.

Big same.

**Comment by dubudevs** [comment]
Those worked for me, I'll test how it plays with tyrant.

**Comment by dubudevs** [comment]
Non-standard openers have always been janky, but this change doesn't appear to dramatically break anything. It still recommends to build around 6 imps and then tyrant straight away, because current APL's tyrant logic assumes linear combat. The mid fight ramp assumes that the previous actions were executed correctly. Nothing new there.

**Comment by Hekili** [comment]
I may revisit some of the imp generation logic there or to delay the Tyrant cast a bit more.  Thanks for the testing and feedback.

**Comment by Hekili** [comment]
I added the precombat changes in 1.0.8b.  I haven't come up with other tweaks to squeeze in more imps before Tyrant though.
