### ISSUE TITLE
[BUG] The Automatic Attack Balance Druid will not start

### ISSUE THREAD

**Issue by istvantarn** [Hekili/hekili#1410]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [x] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hi. Unfortunately, the automatic attack will not start! 
I watched videos too, all settings are fine. The attack panel is nicely visible on the screen.

### How to Reproduce

Thanks for the help! :)

### Player Information (Link)

https://pastebin.com/y644cyZg

### Error Messages (Link)

https://pastebin.com/y644cyZg

### Contact Information

Steve Mardel #8840

**Comment by Hekili** [comment]
Uhhhhh... what?

Nothing happens automatically.  Automation/botting is not suported.  Are you asking something else and I'm not understanding you?

**Comment by istvantarn** [comment]
I got the answer to my question! 
i thought it would automatically go under attack! I thought I didn't have to press the keyboard! Thx :)

**Comment by Hekili** [comment]
Take care!
