### ISSUE TITLE
Lua error when logging in and on reload calling out SpellFlashCore

### ISSUE THREAD

**Issue by Meltun** [Hekili/hekili#1411]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Does not seem to be causing an operational problem, just the Lua error.  I just close the window and everything is ok until next reload.

### How to Reproduce

Login on any of my toons.
Reload on any of my toons.
I have SpellFlashCore and SpellFlash as addons.

You will see this in the window:
Message: ...AddOns\Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:344: EnumerateFrames: Couldn't find 'this' in current object
Time: Tue Mar  8 18:23:11 2022
Count: 1
Stack: ...AddOns\Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:344: EnumerateFrames: Couldn't find 'this' in current object
[string "=[C]"]: in function `EnumerateFrames'
[string "@Interface\AddOns\Hekili\Libs\SpellFlashCore\SpellFlashCore.lua"]:344: in function `Function'
[string "@Interface\AddOns\Hekili\Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"]:35: in function `OnUpdate'
[string "@Interface\AddOns\Hekili\Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"]:19: in function <...Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua:19>

Locals: (*temporary) = <table> {
}

### Player Information (Link)

build: v9.2.0-1.0.8a level: 60 (60) class: MAGE spec: arcane  talents: amplification     arcane_orb     chrono_shift     overpowered     resonance     rune_of_power     slipstream  pvptalents: none  covenant: night_fae  conduits: arcane_prodigy = 7    condensed_anima_sphere = 6    diverted_energy = 6    flow_of_time = 6    nether_precision = 7    tempest_barrier = 6  soulbinds: [niya]    bonded_hearts = 1    called_shot = 1    grove_invigoration = 1    natures_splendor = 1    niyas_tools_burrs = 1    run_without_tiring = 1  sets: wakeners_frond = 1  gear: attendants_loop = 1     band_of_the_risen_bonelord = 1     bookborrower_identification = 1     faewoven_drape = 1     fine_cloth_shirt = 1     gorewrought_medallion = 1     grand_inquisitors_stave = 1     korthian_caretakers_bindings = 1     korthian_caretakers_cinch = 1     korthian_caretakers_mitts = 1     korthian_caretakers_pantaloons = 1     korthian_caretakers_shoulderpads = 1     oracular_hood = 1     oracular_slippers = 1     renowned_guild_tabard = 1     verayns_formal_robes = 1     wakeners_frond = 1  legendaries: none  itemIDs: 177803, 179623, 181457, 181625, 182682, 184143, 185860, 185861, 185886, 185894, 186665, 186667, 187369, 190342, 190344, 69210, 859  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     package = Arcane     petbased = false     potion = spectral_intellect     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     am_spam = 1  toggles: cooldowns = true     custom1 = false      custom2 = false      defensives = true [separate]     essences = true [overridden]     interrupts = true [separate]     mode = automatic      potions = false   keybinds:      arcane_barrage       = 7   [01], 7   [02]     arcane_blast         = 0   [01], 0   [02]     arcane_explosion     = 8   [01], 8   [02]     arcane_missiles      = 9   [01], 9   [02]     arcane_orb           = S6  [06]     arcane_power         = 3   [01], 3   [02]     berserking           = S5  [06]     blink                = S2  [06]     conjure_mana_gem     = AS6 [05]     counterspell         = S8  [06]     evocation            = A1  [05]     fire_blast           = 6   [01], 6   [02]     frost_nova           = A2  [05]     frostbolt            = AS2 [05]     greater_invisibility = A6  [05]     ice_block            = AS4 [05]     mana_gem             = AS3 [05]     mirror_image         = A4  [05]     polymorph            = S1  [06]     presence_of_mind     = 4   [01], 4   [02]     prismatic_barrier    = S4  [06]     remove_curse         = AS1 [05]     rune_of_power        = S9  [06]     shifting_power       = S3  [06]     slow                 = 5   [01], 5   [02]     slow_fall            = A5  [05]     spellsteal           = S7  [06]     touch_of_the_magi    = S0  [06]     wakeners_frond       = 2   [01], 2   [02]

### Error Messages (Link)

Message: ...AddOns\Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:344: EnumerateFrames: Couldn't find 'this' in current object Time: Tue Mar  8 18:23:11 2022 Count: 1 Stack: ...AddOns\Hekili\Libs\SpellFlashCore\SpellFlashCore.lua:344: EnumerateFrames: Couldn't find 'this' in current object [string "=[C]"]: in function `EnumerateFrames' [string "@Interface\AddOns\Hekili\Libs\SpellFlashCore\SpellFlashCore.lua"]:344: in function `Function' [string "@Interface\AddOns\Hekili\Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"]:35: in function `OnUpdate' [string "@Interface\AddOns\Hekili\Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua"]:19: in function <...Libs\SpellFlashCore\libs\BigLibTimer\BigLibTimer.lua:19>  Locals: (*temporary) = <table> { }

**Comment by Hekili** [comment]
You can try removing your separate installation of SpellFlash/SpellFlashCore.

**Comment by Meltun** [comment]
OK, thanks, I will.  Game is down for maintenance now.  Will check when it comes back up.

**Comment by Hekili** [comment]
Hey, just a friendly reminder to report back whether you're still having this problem.  Thanks!

**Comment by Meltun** [comment]
I am.
My wife, who has the same build, is not.  I will research further as it seems unique to my installation.  It is having trouble enumerating frames in SpellFlashCore.  I commented that entire section and everything is ok, functionality and all. 
I do not have the SpellFlash options selected within Hekili setup.
BTW:  The add on is a staple to my enjoyment of the game.  Thanks for keeping it going.

— Friarbison (or Meltun)

**Comment by Hekili** [comment]
It's weird.  EnumerateFrames is Blizzard code; it lets you go through literally every frame the UI has created (base UI, addons, etc.) to do whatever you might need to do to them.  I guessed you might have multiple SpellFlash installs, but it's hard to know.

You might try turning off any addons you have that your wife doesn't and see if it's resolved.  If so, turn them back on one by one until you see the error again.  If it's something like WeakAuras, that could mean a specific aura you have installed is doing something wonky.

**Comment by Meltun** [comment]
Yes, great suggestion.  I will do that and get back to you later.

 

Thanks

**Comment by Meltun** [comment]
The problem was in a personal addon of mine (only on my pc).  I had this:

 

   for i, v in pairs(nFrame) do

     nFrame[i] = nil

   end

 

I thought I had eliminated this everywhere, but …

 

Sorry for the rabbit trail!

 

*	Friarbison

 

 

From: Randall Harbison ***@***.***> 
Sent: Friday, March 11, 2022 9:05 AM
To: 'Hekili/hekili' ***@***.***>
Subject: RE: [Hekili/hekili] Lua error when logging in and on reload calling out SpellFlashCore (Issue #1411)

 

Yes, great suggestion.  I will do that and get back to you later.

 

Thanks

**Comment by Hekili** [comment]
I just appreciate you letting me know that you found the issue on your end.  Take care!
