### ISSUE TITLE
The First Sigil trinket not in pulldown menu. Need a way to disable recommendation in rotation.

### ISSUE THREAD

**Issue by Screwgun** [Hekili/hekili#1414]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I love your addon. I can't play WoW without it. 
The trinket "The First Sigil" is not listed on the pulldown menu. I would like to disable recommendation for it since it's a 5 minute cooldown.
BM hunter.

**Comment by Hekili** [comment]
It's a trinket.  It's in Gear and Trinkets.
