### ISSUE TITLE
shaman enhancement  active_dot.flame_shock count doesn't work

### ISSUE THREAD

**Issue by machajr** [Hekili/hekili#1415]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

there is no active flame shock but its shows active_dot.flame_shock 5

### How to Reproduce

edit (moved):  https://pastebin.com/Aj1nY1qH
https://pastebin.com/eNgLTSMG

### Snapshot (Link)

edit:  _No response_

### Contact Information

incubo#7205

**Comment by Hekili** [comment]
Please put your snapshot in a Pastebin link. Thanks.

**Comment by Hekili** [comment]
I updated your ticket and reviewed what you provided.  `active_dot.flame_shock` doesn't appear in anything you submitted.  The snapshot needs to be taken when you're having the issue in question.  Feel free to reopen the ticket with a snapshot from the correct time.

**Comment by Hekili** [comment]
Could you post a screenshot of where you're seeing 5 active Flame Shocks?  The snapshots aren't matching up with what you're describing.  Thanks!

**Comment by Hekili** [comment]
Reopening per our Discord conversation.  Info needed:

1. Snapshot that shows the value being incorrect (i.e., a snapshot when Fire Nova is recommended based on having multiple Flame Shocks, but no Flame Shocks are active).
2. A screenshot accompanying 1 to show no Flame Shocks are out.
3. More detail about when this starts to occur -- after specific enemies or in specific dungeons, raids, encounters.
4. Check BugGrabber/BugSack for errors.
5. Check /hek > Warnings for any messages -- this section only appears if there are errors/warnings to show, so if it's not there, that means there are no warnings.

Remember that snapshots and warnings go away on reload, so try to submit this information before reloading your UI or it will be gone.

Please post here when you have all of these.  Thanks!

**Comment by machajr** [comment]
snapshots: https://pastebin.com/KzqnDrVx
ss out of combat: 
![image](https://user-images.githubusercontent.com/75227922/157914025-8e106c83-231c-4eba-9dd2-4a8ee2b60c09.png)

warning:    Unknown buff: swirling_currents

[string "@Interface\AddOns\Hekili\State.lua"]:3530: in function <Interface\AddOns\Hekili\State.lua:3521>
[string "return buff.swirling_currents.up"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface\AddOns\Hekili\Scripts.lua"]:935: in function `EmulateSyntax'
[string "@Interface\AddOns\Hekili\Scripts.lua"]:1207: in function <Interface\AddOns\Hekili\Scripts.lua:1198>
[string "@Interface\AddOns\Hekili\Scripts.lua"]:1516: in function `LoadScripts'
[string "@Interface\AddOns\Hekili\Scripts.lua"]:1605: in function `LoadScripts'
[string "@Interface\AddOns\Hekili\Core.lua"]:1472: in function <Interface\AddOns\Hekili\Core.lua:1470>

**Comment by Hekili** [comment]
I unchecked `I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported)` given this was a custom priority.

You DMed that you tested without it; was that by removing the actual entry that includes it (i.e., your custom priority is deleted) or just by switching priorities?  The warning is caused when loading your priority with Swirling Currents (which I will fix), but does not appear that it should impact Flame Shock counts.

Are you playing on a private server?

**Comment by machajr** [comment]
3.its happened almost every dungeons and first one raids 
4.buggrabber : https://pastebin.com/iADU6n3M
 thats all

**Comment by Hekili** [comment]
Also, please try:

`/run Hekili.State.reset(); print( Hekili.State.active_dot.flame_shock )`

Let me know what you get.  If it's non-zero when you have no active Flame Shocks, you can try:

`/run Hekili.State.active_dot.flame_shock = nil; Hekili.State.reset(); print( Hekili.State.active_dot.flame_shock )`

And see if it changes.  I'll keep investigating, but also answer if this is a private server or something else.  I don't know why your Fire Nova icon is messed up in that screenshot.  (Also, for screenshot, I didn't mean a screenshot of the options UI.)

**Comment by machajr** [comment]
i m not playing on a private server.
i only removed swirling currents buff from my custom priorty

**Comment by Hekili** [comment]
Did you reload UI afterward?

**Comment by machajr** [comment]
/run Hekili.State.reset(); print( Hekili.State.active_dot.flame_shock )

with this again im out of combat its shown 1

**Comment by machajr** [comment]
i reload the ui . btw main problem is active_dot.flame_shock count not fire nova it efect aoe rotation

**Comment by Hekili** [comment]
I understand that Flame Shocks appear to be counted when they're expired in your case.  I also have to figure out why you're having that problem and I'm not.

I'll probably have to add some more debugging options into an alpha version to test on your end, because I can't replicate this issue.

I will probably need you to test if you can cause this problem to occur with only this addon loaded, too.  I'm not sure how another addon could interfere, but I can't replicate it so far.

**Comment by machajr** [comment]
its keep rising :D again its just before the pull 
![image](https://user-images.githubusercontent.com/75227922/157922850-f80ad5fa-7949-4ea6-8b4d-88d3c9c9b743.png)

**Comment by machajr** [comment]
> I understand that Flame Shocks appear to be counted when they're expired in your case. I also have to figure out why you're having that problem and I'm not.
> 
> I'll probably have to add some more debugging options into an alpha version to test on your end, because I can't replicate this issue.
> 
> I will probably need you to test if you can cause this problem to occur with only this addon loaded, too. I'm not sure how another addon could interfere, but I can't replicate it so far. 
yeah sure i can do that after raid mate

**Comment by machajr** [comment]
can you tell me whats addon are you using ?

**Comment by Hekili** [comment]
> /run Hekili.State.reset(); print( Hekili.State.active_dot.flame_shock )
> with this again im out of combat its shown 1

Please do the follow-up from the same post:
`/run Hekili.State.active_dot.flame_shock = nil; Hekili.State.reset(); print( Hekili.State.active_dot.flame_shock )`

Report if it resets to 0.

If not, please run the following and report back on the output:
`/run print( rawget( Hekili.State.active_dot, "flame_shock" ) )`

**Comment by Hekili** [comment]
I've released updates that include audits that more consistently purge these expired auras.  Feel free to comment/reopen if you are still having a problem.

**Comment by machajr** [comment]
exactly same error again i cant remember how did you fix it but its pop up again. i dont know it s just me or not.
