### ISSUE TITLE
enhancement shaman bug active flame shock always shown 5 

### ISSUE THREAD

**Issue by machajr** [Hekili/hekili#1416]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

even if i m not in combat it still says 5 active flame shock

### How to Reproduce

enhancement shaman flame shock 

### Snapshot (Link)

https://pastebin.com/eNgLTSMG

### Contact Information

incubo#7205

**Comment by Hekili** [comment]
> even if i m not in combat it still says 5 active flame shock

You're not showing anything that indicates that.  Show me.  And do it in the other ticket.

https://github.com/Hekili/hekili/issues/1415
