### ISSUE TITLE
 [Surv Hunter] Doesn't use much bombs when equipped with a tier set.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1420]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello. I got 2 hunter tier sets. And I decided to play Surv. I've noticed that the addon doesn't try to use bombs often when it has a tier set. The rotation works as if we don't have a tier set, and he holds the bombs like in a normal rotation. When a tier set means that we should use bombs in rotation as often and as much as possible in both AOE and ST.

### How to Reproduce

A bomb must be used in the rotation after each Kill Command. If you look at the simulation and the rotation that is indicated.

### Snapshot (Link)

https://pastebin.com/qrD9cbxJ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/316E8HP13d4fWi2rYtHQKr

**Comment by Hekili** [comment]
Could you provide a snapshot that shows the issue, then?  The first recommendation in this snapshot is Wildfire Bomb.

> A bomb must be used in the rotation after each Kill Command. If you look at the simulation and the rotation that is indicated.

This is not what happens in the sim.  

The sim is using Wildfire Bomb consistent with non-tier *plus* when Kill Command procs the 2pc Mad Bombardier buff.  In your snapshot, you procced the buff and it's being recommended.

**Comment by Dragonfo** [comment]
All I saw was my mistake, I did not notice the buff. I'm sorry for the ticket
