### ISSUE TITLE
Fury warrior line 7 inconsistent with the sims

### ISSUE THREAD

**Issue by BigBong69** [Hekili/hekili#1421]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Line 7 in hekili for fury warrior incorrectly suggests raging blow when it should be crushing blow (an ability that replaces raging blow through reckless abandon). 

### How to Reproduce

Open up the fury priority list, single target, line 7. Attached in the raidbots link is the default sim vs the mistake that was in hekili.

### Snapshot (Link)

N/A

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/w58z77AFBvEPtczLjYQ5aV/simc

### Contact Information

105°C#0854

**Comment by Hekili** [comment]
Technically, to the addon, Crushing Blow and Raging Blow are interchangeable (to help address that they swap).  That was fine with older priorities but is more of a problem now.

**Comment by BigBong69** [comment]
Yeah, I thought that was the problem, but it was definitely a noticeable dps down. Just wanted to let you know that its an issue.

**Comment by Hekili** [comment]
Yes, it's good to report it, I was just explaining.  I should probably stop explaining issues as I fix them, because people think I'm arguing against them.

**Comment by Hekili** [comment]
This has since been resolved.
