### ISSUE TITLE
[BUG] Spinning Crane Kick makes the swipe of the next reccommended skill last 0.5 seconds too long

### ISSUE THREAD

**Issue by gnew95** [Hekili/hekili#1423]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Spinning Crane Kicks swipe lasts 50% longer then the GCD for the next reccomended skill. At the moment the swipe follows the 1.5 second cast time of SCK however you are able to cast your next spell at 1 second with the damage of SCK still occuring. This can lead to either:

A) Damage loss by waiting for the whole swipe to finish before casting the next spell (which could have been casted 0.5 seconds sooner)

B: spamming the following spell after pressing SCK knowing I will be able to cast it sooner then hekili recommends. (This also causes a strange visual bug of the swipe repeating quickly over and over.) 

Thank you very much for all your hard work and time on this add on!

### Additional Information

This is a picture showing the slower cooldown swipe for the next reccomended cast. The proper 1 second swipe is shown for all subsequent reccomendations. This can be replicated by playing as brewmaster monk and casting spinning crane kick.

![monk bug picture](https://user-images.githubusercontent.com/101494776/158071806-925c02b7-b5ea-4483-87bb-2347c610a7ee.jpg)

**Comment by Hekili** [comment]
This has been addressed in the latest release.
