### ISSUE TITLE
[Surv Hunter] While buffed, Mad Bombardier does not press Carve when the bombs are on cooldown.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1424]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In an AoE with 5 targets buffed by Mad Bombardier and a bomb on cooldown (there are none), the addon suggests that you only press Kill Command at that moment in the AoE. When we have a lot of focus to press one Carve button to roll back the bombs, and press them under the Mad Bombardier buff. But the addon does not offer to press Carve in AOE to roll back the bombs, it will just offer Kill Command all the time until we have the bombs ready. Although we already have the Mad Bombardier buff and we have enough focus to press one Carve button.

### How to Reproduce

Start a fight with 5 AOE targets.
Make Mad Bombardier buff
we should have bombs on cd before their cooldown remains 3-4sec
And at this moment the addon will recommend in the AoE to press only Kill comand

And it should be simple. If the bombs are on cooldown and we have the Mad Bombardier buff we should just press Carve and use the bomb without a lot of Kill comand while the bombs are on cooldown.

### Snapshot (Link)

https://pastebin.com/0AJ6jvC8

**Comment by Hekili** [comment]
You'll have to investigate the priority a bit more on your own going forward.

In this case, the addon is using Kill Command specifically because the Pheromone Bomb debuff is applied.

**Comment by Dragonfo** [comment]
It seems to me that in this case everything is simple. If we got the mad bombardier buff from Kill Command and we have a 3-4 second bomb cooldown, we use Carve. After we use the bomb and for the rest of the time we implement the pheromone bomb. As far as I can see, this moment can be beaten. Just here you need to take into account one point, if Carve can reduce the time of the bomb in 1 hit so that it is ready, then use Carve. If this condition is not possible, then only spam Kill Command until Carve can reduce the cooldown of bombs.

**Comment by Hekili** [comment]
> If we got the mad bombardier buff from Kill Command and we have a 3-4 second bomb cooldown, we use Carve.

Your sim doesn't do this.  If you make a sim profile that does this, you can contribute to SimulationCraft once you've proven it's a DPS increase to do so.

> After we use the bomb and for the rest of the time we implement the pheromone bomb.

We've talked about the Wildfire bomb/Pheromone Bomb/Kill Command interaction already.

> As far as I can see, this moment can be beaten. Just here you need to take into account one point, if Carve can reduce the time of the bomb in 1 hit so that it is ready, then use Carve.

Your sim doesn't do this.  If you make a sim profile that does this, you can contribute to SimulationCraft once you've proven it's a DPS increase to do so.

> If this condition is not possible, then only spam Kill Command until Carve can reduce the cooldown of bombs.

It's certainly possible, it's just not what is tested and proven with sims.  The hard part is figuring out exactly where this logic fits into a priority list vs. everything else that is already built and tested.  You can refer to the SimulationCraft wiki and the default [Survival Hunter](https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier28/T28_Hunter_Survival.simc) profile and build from there.

I don't have time to continue to go back and forth on this.  If you make a custom priority and run sims that show a DPS increase, I'll look at it.  If you get changes made to SimulationCraft and the default profile is updated, I'll receive those and implement it.  Thanks for understanding.
