### ISSUE TITLE
SpellFlashCore.lua error which freezes wow client for around 1 minute

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#1425]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

During game session in open world (particularly in Zereth Mortis) WoW client just freezes from time to time for about 1 minute straight. After freeze ends a lua error appears and everything is allright but might repeat itselft in several hours or after /reload.

### How to Reproduce

1. Enter the game as Rogue/Warrior.
2. Play in Zereth Mortis

### Player Information (Link)

https://pastebin.com/5KuSmph9

### Error Messages (Link)

https://pastebin.com/QyfYcQk9

**Comment by IIeTpoc** [comment]
![hekilispellflashluaerror](https://user-images.githubusercontent.com/64799395/158069558-0650cf38-065c-4dd0-82a8-5a1dbe0bfaf5.png)
This is the first error i get upon reloading when this situation happens.

**Comment by Hekili** [comment]
You will want to report this to the SpellFlashCore developer or the BigLibTimer developer, based on the error message you see.
