### ISSUE TITLE
[BUG] GUI not loading v9.2.0-1.0.9-alpha3

### ISSUE THREAD

**Issue by p4nchez** [Hekili/hekili#1426]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

rightclicking on minimap button for GUI open only black transperent window with nothing in it

### How to Reproduce

1. Enter game
2. Rightclick on Minimap Icon for GUI
3. only transperent window opens 

### Player Information (Link)

https://pastebin.com/QgVcsEwz

### Error Messages (Link)

https://pastebin.com/QgVcsEwz

### Contact Information

p4nda#156
![unknown](https://user-images.githubusercontent.com/29162840/158222113-9b69b30d-ea2d-4612-8206-8eb603fc7669.png)
7

**Comment by p4nchez** [comment]
looks fixed in Hekili-v9.2.0-1.0.9

**Comment by Hekili** [comment]
Thanks for confirming!
