### ISSUE TITLE
[BUG] balance druid recommending moonfire spam

### ISSUE THREAD

**Issue by melarki** [Hekili/hekili#1429]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

addon is recommending moonfire spam when entering lunar eclipse in multi-target scenario
![hekili](https://user-images.githubusercontent.com/101700927/158575920-9be268e4-97e4-4abe-abf0-231c7bd91e39.png)

### How to Reproduce

enter eclipse in multi-target encounter

### Player Information (Link)

https://pastebin.com/vtZKTNcN

### Error Messages (Link)

n/a

### Contact Information

Melarki#8029

**Comment by kwlockwo** [comment]
+1 for this issue

**Comment by Hekili** [comment]
Thanks, this is fixed in 1.0.9a.
