### ISSUE TITLE
[REC] 2 set wrong opener in raid nf druid

### ISSUE THREAD

**Issue by noiseuu** [Hekili/hekili#1432]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Just do opener

hekili does wrath - wrath - starfire
when dreamgrove says
In raid with 2-Set Wrath, dots, New Moon(when talented), Wrath, CA, continue with the openers above.

### How to Reproduce

1. just do dmg at dummy

### Snapshot (Link)

https://pastebin.com/QGxUecbY

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fozNMXXyraxbnX8bmcgFJz

**Comment by Hekili** [comment]
This snapshot doesn't match the report.  Please add a snapshot taken when the Starfire recommendation is appearing.

**Comment by noiseuu** [comment]
https://pastebin.com/ukRvDKku
sry there new snapshot

**Comment by Hekili** [comment]
This will be fixed in next release.  Thanks!
