### ISSUE TITLE
[Surv Hunter] Quick change of bombs between rotations after activating the mad bombardier buff.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1433]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When we have an active mad bombardier buff and we use bombs, then the addon shows the Raptor Strike ability for 1 second first, after the bomb comes, and again shows Kill Command. In this interval between these two, it shows the readiness of the bomb, when we can have 0 of them. The addon does not seem to take into account the possibility of a cooldown of bombs of bombs. And the addon always starts to flicker when the buff is activated and the bomb is used, showing either the bomb or the ability. This only happens when we use a buff and a bomb and we will have 0 in theory, but the buff returns 1 bomb to us after activating it. And the addon shows this bomb every time that we have it ready. Of course, I tried to fix the moment when it started blinking.

### How to Reproduce

1. Active buff mad bombardier.
2. we have 1 bomb.
3. And just use a bomb, preferably a red one.
4. And at this point, there will be a quick bomb display between the Raptor Strike and Kill Command abilities.

### Snapshot (Link)

https://pastebin.com/7HJQzXrc

**Comment by Hekili** [comment]
Are you able to show that happening?  Screenshots or a short recording?  Thanks.

**Comment by Dragonfo** [comment]
https://imgur.com/a/fhR3Pcl Attached a piece of video as it is displayed when the buff is consumed. It flickers very quickly every time, is it possible to remove it somehow? So that it does not flash, but simply shows as usual without quick changes.

**Comment by Hekili** [comment]
Thanks.  Can you tell me if your Mad Bombardier buff goes away instantly on cast or if it goes away when your bomb hits?

**Comment by Hekili** [comment]
I made some changes that might address this for you, but I can't test the set bonus directly.  It may also cause issues with the texture used for Wildfire Bomb.  Please try it out and let me know if it works for you.

https://github.com/Hekili/hekili/releases/tag/v9.2.0-1.0.10-alpha1

**Comment by Dragonfo** [comment]
As for the mad bombardier, it activates when it hits a target. I just checked today and recorded another short video where he still shows the bombs just as quickly.  I recorded a video a little longer so that you can see how it manifests itself now. https://imgur.com/a/1uXEjBL

**Comment by Hekili** [comment]
The question I am asking is: when you already have a Mad Bombardier buff, does the buff go away immediately on cast, or does it go away when the bomb hits the target?

I can't tell from your video. You can test by getting the buff and then throwing your bomb from a distance.

**Comment by Dragonfo** [comment]
Here I am attaching a video where I did it from a distance. https://imgur.com/a/Ui3nwnQ

**Comment by Hekili** [comment]
Okay, that makes sense -- the buff is consumed on impact rather than on cast.  I'll sort it out.  Thank you.

**Comment by Hekili** [comment]
Could you please try the latest alpha?  1.0.10-alpha2?  

https://github.com/Hekili/hekili/releases/tag/v9.2.0-1.0.10-alpha2

**Comment by Dragonfo** [comment]
Well, you can say 50 to 50. In some moments everything is fine, but in others it is not. He also keeps changing priorities quickly. I noticed that when the turn of the blue bomb comes up, he immediately consumes it without taking into account the mad bombardier buff. It seems to me that the problem is in the blue bomb, since it is simply used by rotation without any conditions. I recorded a longer video because it was difficult to keep track of all these problems. https://imgur.com/a/ea8rSWY

**Comment by Hekili** [comment]
> I noticed that when the turn of the blue bomb comes up, he immediately consumes it without taking into account the mad bombardier buff.

Can you snapshot this?  The priority is always considered.  The priority does basically say to use whatever bomb you have when Mad Bombardier is up, barring a few higher priority buttons.

> I recorded a longer video because it was difficult to keep track of all these problems. [imgur.com/a/ea8rSWY](https://imgur.com/a/ea8rSWY)

The recordings have helped when trying to investigate "I see this then it changes to that" while seeing what your fight situation looks like, but snapshots before/after would help for comparing the other details.

One limitation for the addon is that when you use a Wildfire Infusion bomb, the addon doesn't know what bomb type is coming next.  This can cause the recommendations to change, if your new bomb type would impact what should be chosen next.

Thanks for continuing to supply information.

**Comment by Dragonfo** [comment]
https://pastebin.com/FpJARd1E I took a snapshot, at that moment I had two charges of the Kill command, and for some reason, not using the Kill command, the recommendation decided to suggest just using the blue bomb, without trying to get the mad bombardier buff.

**Comment by Hekili** [comment]
There were two Kill Command entries considered before using Raptor Strike.

```
41.  kill_command ( st - 11 )
The action (kill_command) is usable at (0.00 + 0.04).
 - the action is ready before the current recommendation (at +0.04 vs. +7.94).
List ( st ) called from ( Survival:default:7 ) would PASS at 0.04.
active_enemies[1.00] < 3 & ! talent.birds_of_prey.enabled[false]
 - this entry's criteria FAILS: set_bonus.tier28_2pc[1.00] & dot.pheromone_bomb.ticking[false] & ! buff.mad_bombardier.up[false]
 ```
 
Not recommended because it wants you to have Pheromone Bomb ticking.

```
46.  kill_command ( st - 16 )
The action (kill_command) is usable at (0.00 + 0.04).
 - the action is ready before the current recommendation (at +0.04 vs. +7.94).
List ( st ) called from ( Survival:default:7 ) would PASS at 0.04.
active_enemies[1.00] < 3 & ! talent.birds_of_prey.enabled[false]
 - this entry's criteria FAILS: full_recharge_time[2.24] < gcd.execute[1.07] & focus.current[100.00] + cast_regen[22.50] < focus.max[100.00]
There are 1 recheck events.
List ( st ) called from ( Survival:default:7 ) would PASS at 1.21.
active_enemies[1.00] < 3 & ! talent.birds_of_prey.enabled[false]
Recheck #1 ( +1.21 ) NOT MET: full_recharge_time[1.07] < gcd.execute[1.07] & focus.current[100.00] + cast_regen[22.50] < focus.max[100.00]
```

This didn't get recommended because you were not capped on Kill Command charges for another 2.24 seconds.  Additionally, it wants you to spend down focus such that you won't overcap during the time you use Kill Command -- and you were already at Focus cap.

Back to the bomb issue, I was asking for a before and after snapshot so I can see what might've changed.  If you can rapidly get the following:

1. Blue bomb is recommended in first slot, but you haven't pushed it yet.
2. You just pushed blue bomb and it's in the air.
3. Blue bomb has just hit the target.

**Comment by Dragonfo** [comment]
I could only fix the blue bomb on 3 points when it hit the target. But most likely this was done again with the aim of wasting focus.
https://pastebin.com/bN72zb3P
It's just that if this condition worked again, that you threw it off above, then I don't understand the rotation. If we play with the Mad Bombardier buff, we don't want to make 0 bombs, we want to implement them under the buff to get as many procs and free bombs as possible. And the addon recommends spending bombs at 0 in some situations, where then we can get the Mad Bombardier buff and still wait 5-6 seconds before the cooldown of bombs with the Mad Bombardier buff. I see so even if we have 100 energy and have 1 blue bomb and 2 kill comand why don't we try to use 1-2 kill comand in the hope of getting the Mad Bombardier buff thereby speeding up the process of obtaining bombs. And do not wait from 4-6 seconds when the bomb is on cooldown and the Mad Bombardier buff just hangs.

**Comment by Hekili** [comment]
> I could only fix the blue bomb on 3 points when it hit the target. But most likely this was done again with the aim of wasting focus.
> [pastebin.com/bN72zb3P](https://pastebin.com/bN72zb3P)

I don't understand what you mean here, but you can study the priority in your sims if you want to look at it more closely.

> I don't understand the rotation. If we play with the Mad Bombardier buff, we don't want to make 0 bombs, we want to implement them under the buff to get as many procs and free bombs as possible.

You have to report snapshots that relate to exactly what you're asking about, and provide the context.  That means when you think, "hey, I don't think I should actually use this bomb right now, it'll spend down to 0 charges and I want to be able to use a bomb with Mad Bombardier" then you take a snapshot at that moment.  Then you can review the snapshot or share it here.  Make sure to label it with the appropriate context.

> And the addon recommends spending bombs at 0 in some situations, where then we can get the Mad Bombardier buff and still wait 5-6 seconds before the cooldown of bombs with the Mad Bombardier buff.

The short answer is "this is what the priority is written to recommend, and you can snapshot that scenario to see why you're seeing what you see."

> I see so even if we have 100 energy and have 1 blue bomb and 2 kill comand why don't we try to use 1-2 kill comand in the hope of getting the Mad Bombardier buff thereby speeding up the process of obtaining bombs.  And do not wait from 4-6 seconds when the bomb is on cooldown and the Mad Bombardier buff just hangs.

Assuming you're using Wildfire Infusion, you would use your Wildfire Bombs in the following circumstances (single-target):

You have the 2pc bonus and you'll cap on Wildfire Bomb charges in less than 2 GCDs, or
You have the Mad Bombardier buff, or
You don't have the 2pc, and<ul>
<li>You'll cap charges within a GCD, or
<li>You won't overcap Focus, and<ul>
<li>You have a Volatile Bomb and Serpent Sting is applied to your target and it is refreshable, or
<li>You have a Pheromone Bomb and Mongoose Fury is down and you'll won't end up overcapping from using Kill Command 3 times, or
<li>There's 10 seconds left in the fight.</ul></ul></ul>

You have a Shrapnel Bomb, enough Focus to Mongoose Bite or Raptor Strike twice, and Serpent Sting will last at least 5 GCDs on your target.

You have Rylakstalker's legendary equipped.

You do not have the 2pc set bonus, and<ul>
<li>You have a Volatile Bomb and Serpent Sting is ticking, or
<li>You have a Pheromone Bomb, or
<li>You have a Shrapnel Bomb and at least 50 Focus.</ul>

If you're seeing Wildfire Bomb recommended outside of the above circumstances in single-target, snapshot it and look at the conditions for the recommendation that is shown (and look at why other items were left out).  I'll continue to review for a bit, but at some point, the priority is the priority -- if you have a better one, you can contribute to SimulationCraft and get that project updated, and I'll make the changes here.

One thing I have done, however, is add a spec option that will effectively disable the checks related to overcapping Focus.  When I tested in sims, it performed roughly equal, on average though it had lower lows and slightly higher highs.  That may or may not get you closer to what you're expecting in general.  This is testable in the latest alpha.

**Comment by Dragonfo** [comment]
The last alpha version you posted works great and even fixed that blue bomb issue ) Thank you so much for your work and quick fixes. You are the best.
