### ISSUE TITLE
[REC] BM Hekili not recommending Multishot / not detecting AoE

### ISSUE THREAD

**Issue by Floapy** [Hekili/hekili#1434]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

BM hunter rotation not recommending Multi-shot / also I think it's not detecting multiple targets at all

### How to Reproduce

Dont think it's detecting multiple targets at all

### Snapshot (Link)

https://pastebin.com/0u0rPhNZ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/n2v51awbWNbD6BzuESvXUE

### Contact Information

Floapy#0124

**Comment by Hekili** [comment]
You have nameplate-based target detection turned on, so it's looking for targets around your character.

You should probably look at /hekili > Beast Mastery > Targeting and set up Pet-Based Target Detection and turn off nameplate-based detection.
