### ISSUE TITLE
[REC] MM Hunter Rapid Fire Trick Shots buff 

### ISSUE THREAD

**Issue by Lipstopica** [Hekili/hekili#1437]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During the channel of Rapid Fire, the buff of Trick Shots remains until the channel is over. I believe this is what is causing Hekili to suggest Aimed Shot after Rapid Fire in AoE without refreshing the buff first because it believes the buff will still be active at the end of the channel of Rapid Fire.

### How to Reproduce

Go to AoE dummies
Press Multi-Shot
Press Rapid Fire (The buff of Trick Shots remains until the end of the channel)
Check Hekili, it keeps suggesting Aimed Shot until the end of the channel (which is when the Trick Shots buff ends)

### Snapshot (Link)

https://pastebin.com/NZVx3mSq

### Contact Information

Smudgie#2425

**Comment by Hekili** [comment]
Here is what I will test, but since you're downloading changes (says you have a dev build), you may consider trying this yourself and reporting back.

In Classes/HunterMarksmanship.lua, scroll down to the entry for the `rapid_fire` ability.  It should be ~line 827.  Replace the ability with this:

```Lua
        rapid_fire = {
            id = 257044,
            cast = function () return ( 2 * haste ) end,
            channeled = true,
            cooldown = function () return ( buff.trueshot.up and 8 or 20 ) * haste end,
            gcd = "spell",

            spend = 0,
            spendType = "focus",

            startsCombat = true,
            texture = 461115,

            start = function ()
                applyBuff( "rapid_fire" )
                if talent.streamline.enabled then applyBuff( "streamline" ) end
                removeBuff( "brutal_projectiles" )
            end,

            finish = function ()
                if buff.volley.down then removeBuff( "trick_shots" ) end
                removeBuff( "double_tap" )
            end,

            auras = {
                -- Conduit
                brutal_projectiles = {
                    id = 339929,
                    duration = 3600,
                    max_stack = 1,
                },
            }
        },
```

Save the file and then `/reload` in game.

This shifts the removal of Trick Shots to the end of the channel rather than the start.  Let me know if that seems to solve it for you.

**Comment by Lipstopica** [comment]
That seems to have fixed the issue :) thank you

**Comment by Hekili** [comment]
Thanks, fix will be live soon.
