### ISSUE TITLE
Bladestorm gives almost constant Interface errors

### ISSUE THREAD

**Issue by Icebane1331** [Hekili/hekili#1438]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Bladestorm gives almost constant UI errors in both Fury and Arms spec.

### How to Reproduce

Doesn't happen all the time but when it does gives errors throughout the duration of Bladestorm after activating

### Player Information (Link)

https://pastebin.com/mZ5ZYmNs

### Error Messages (Link)

https://pastebin.com/mfJabAXG

### Contact Information

Icebane#5253

**Comment by Hekili** [comment]
It looks like this occurs when the recommendation to cancel Bladestorm is active.  A fix is incoming.

**Comment by Hekili** [comment]
This should be resolved.

**Comment by Icebane1331** [comment]
Thank you

**Comment by Icebane1331** [comment]
not sure what happened but now spell flash isn't working with Hekili since
you updated it
