### ISSUE TITLE
[Surv Hunter] 3+ target AoE uses Volatile Bomb without Serpent sting.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1439]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I just noticed that the recommendations for using Volatile Bomb in the AOE are not working correctly. This is due to the fact that if we start the fight with 3+ targets at once, the addon does not check Serpent sting on targets. The rotation recommendation in the addon works like we'll have a blue bomb first, but not a green one. And we have no right to use Volatile Bomb without a buff from Serpent sting. You need at least 1 target to always be buffed by Serpent sting.

### How to Reproduce

1. So that at the beginning of the battle there was immediately a Volatile Bomb.
2. Start a fight with 3+ targets.

### Snapshot (Link)

https://pastebin.com/PbJvf6TK

**Comment by Hekili** [comment]
You've submitted this already, and I even brought the issue to Hunter theorycrafters.  It doesn't pay off to delay bombs for Serpent Sting.  You can always press Serpent Sting anyway, if you want to, but overall the tradeoff is not worth it.
