### ISSUE TITLE
[BUG] addon not loading on any of my characters after reset

### ISSUE THREAD

**Issue by melarki** [Hekili/hekili#1440]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

addon won't appear on any character, it's enabled and if i go into config window i can see the position of the primary display but it's blank, screenshot linked, i normally have it covering the first 4-5 weakaura squares but just moved it down to see clearer https://gyazo.com/bdd6b0a5097268c5993c835c645f24f9

### How to Reproduce

log in to any character, have tried reloading UI 

### Player Information (Link)

https://pastebin.com/VTfhXxgK

### Error Messages (Link)

n/a

### Contact Information

Melarki#8029

**Comment by Hekili** [comment]
When was the last time you updated the addon?  I see that you're up to date, but has it been a while since you updated before now?

It looks like the addon -- or your specialization -- is not enabled.  Please check your specialization's section of the addon options.

**Comment by melarki** [comment]
I update it regularly, but yes I see now the spec is disabled, something weird must have happened with my settings on reset. Thanks will make sure to check that first next time! :)

**Comment by Hekili** [comment]
No, it's an issue that it's resetting for some folks, so I appreciate the report.  I'll keep investigating.
