### ISSUE TITLE
[Rogue/Outlaw] Invigorating Shadowdust not accounting for Kyrian CD

### ISSUE THREAD

**Issue by Khaniixx** [Hekili/hekili#1443]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In the opening rotation for outlaw to get the most out of the Invigorating Shadowdust you would vanish after using Echoing Reprimand e.g Echoing Reprimand>Vanish>Dispatch

**Example of correct rotation for my Talents.**
Stealth > Marked for death > Roll the bones > Slice and Dice > Ambush > Adrenaline Rush > (Blade Flurry+Blade Rush if aoe) Blade Rush > Ghostly Strike > Echoing Reprimand > Vanish > Dispatch

**Example of the rotation i am being shown**
Stealth > Marked for death > Roll the bones > Slice and Dice > Ambush > Adrenaline Rush > (Blade Flurry+Blade Rush if aoe) Blade Rush > Ghostly Strike > Vanish > Ambush > Echoing Reprimand

### How to Reproduce

1. Enter game as Outlaw Rogue
2. Take Ghostly Strike, Marked for Death, Blade Rush talents. 
3. Be Kyrian
4. Wear Invigorating Shadowdust and Cinch of unity (belt)
5. Follow the Hekili Rotation (Stealth > Marked for death > Roll the bones > Slice and Dice > Ambush > Adrenaline Rush > (Blade Flurry+Blade Rush if aoe) Blade Rush > Ghostly Strike) 
6. See recommendation.

### Snapshot (Link)

https://pastebin.com/GM67i8TD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qq9wYXQC6oq1beFgKs37pF

### Additional Information

I have also noticed the quick sim displays the correct rotation in the "Sample Ability Log"

**Comment by Hekili** [comment]
You mentioned this is still not working; can you post a new snapshot using the latest alpha?  Thanks.

**Comment by Khaniixx** [comment]
https://pastebin.com/eMnvgBKR

**Comment by Hekili** [comment]
The latest alpha appears to address this successfully.
