### ISSUE TITLE
cycle_enemies doesnt work

### ISSUE THREAD

**Issue by machajr** [Hekili/hekili#1444]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

cycle_enemies doesnt work

### How to Reproduce

cycle_enemies always shown 1 enemy i dont know why i tried in multiple fights. i noticed that with my enchancement shamaman

### Snapshot (Link)

https://pastebin.com/jptnCt2n

**Comment by Hekili** [comment]
`cycle_enemies` is something I created for the addon; it only works with "Recommend Target Swaps" enabled (a.k.a., cycling).  You do not have it enabled.

It is the number of targets that you would actually want to cycle through in a fight, essentially filtering `active_enemies` based on internal ability criteria and your spec's settings (i.e., if you specify that targets need to live for 10 seconds and you're in a pack of adds that will die in 3 seconds, none of them are counted).
