### ISSUE TITLE
[BUG] Arcane Mage + Siphon Storm Legendary results in odd reccomendations

### ISSUE THREAD

**Issue by crflanigan** [Hekili/hekili#1445]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

My charecter is Venthyr and recently changed my legendary from Temporal Warp to Siphon Storm. I noticed that often one of my trinkets are now no longer suggested, when Mirrors of Torment is off cooldown early (due to the Legendary Convenant belt) the addon doesn't reccomend it, and often the addon doesn't reccomend Arcane Power. I thought it could be that it's waiting for a burn phase, but Mirrors should never be on CD, and Arcane Power should be used almost on CD to ensure uptime. 

My charecter is here:
https://worldofwarcraft.com/en-us/character/us/sargeras/raamagus 

### How to Reproduce

1. Be a Arcane Mage with Siphon Storm and Venthyr convenant legendary
2. Log into WoW with the latest Hekili
3. Cast based on Hekili's suggestions

### Player Information (Link)

https://pastebin.com/SWCNS4x2

### Error Messages (Link)

No in game errors

**Comment by Hekili** [comment]
Please submit a "Recommendations" ticket following those instructions.  Thanks.
