### ISSUE TITLE
[REC] Arcane Mage + Siphon Storm Legendary results in odd reccomendations

### ISSUE THREAD

**Issue by crflanigan** [Hekili/hekili#1447]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

My charecter is Venthyr and recently changed my legendary from Temporal Warp to Siphon Storm. I noticed that often one of my trinkets are now no longer suggested, when Mirrors of Torment is off cooldown early (due to the Legendary Convenant belt) the addon doesn't reccomend it, and often the addon doesn't reccomend Arcane Power. I thought it could be that it's waiting for a burn phase, but Mirrors should never be on CD, and Arcane Power should be used almost on CD to ensure uptime.

### How to Reproduce

Be a Arcane Mage with Siphon Storm and Venthyr convenant legendary
Log into WoW with the latest Hekili
Cast based on Hekili's suggestions

### Snapshot (Link)

https://pastebin.com/SWCNS4x2

**Comment by crflanigan** [comment]
After playing a little more I am still seeing the same pattern, but another weird thing is coming up. 

Hekili will tell me to Arcane Barrage when I have plenty of mana, but no way to fill up my Arcane charges because ToM and Orb are on 10+ seconds CD left. I basically just ignore when it does that but I do have to catch myself. 

Mirrors of Torment continue to not get reccomended even when it's been off cooldown for some time; I've been watching out for it myself.

**Comment by Hekili** [comment]
The same ticket instructions apply. Snapshot it, provide a link. Sim link of your character helps, too. Thanks!

**Comment by crflanigan** [comment]
When you say snapshot, do you mean I screen capture when Mirrors is off CD but not recomended, or when Arcane Barrage is suggested but there's no way to rebuild charges besides Arcane Blast?

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/160222238-dee63f3e-5205-4ffe-81b1-16a08d9f750e.png)

(For either/both scenario.)
