### ISSUE TITLE
Interrupt Window Gets Stuck

### ISSUE THREAD

**Issue by whoaisjustin** [Hekili/hekili#1449]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Fairly often, my interrupt window gets stuck displaying despite no enemy targeted/not in combat/no enemy casting. Image attached (I hope). 

![image](https://user-images.githubusercontent.com/15135401/160061022-7eddb447-8901-4303-87d9-f079f648884b.png)

### How to Reproduce

I haven't been able to deduce a common catalyst for this issue. It's fairly often and usually after I've left combat. 

### Player Information (Link)

https://pastebin.com/CVRQ2tiS

### Error Messages (Link)

N/A

**Comment by Hekili** [comment]
Thanks for the report.  It'd be helpful to also have a snapshot to see what exactly is getting stuck.  Do you have BugSack and BugGrabber.  Are you *sure* there's no error message?  Thanks!

**Comment by whoaisjustin** [comment]
I've installed Bugsack/BugGrabber and will try to provide amplifying information when I see it again. Feel free to close the issue and I can just throw in another one when/if it happens.

**Comment by Hekili** [comment]
Another place to check would be /hekili > Warnings -- issues that occur when the addon is generating recommendations might get caught here and not show up as a normal error.

**Comment by Hekili** [comment]
Going to close -- if you see it again and can get a snapshot/error messages, feel free to reopen.
