### ISSUE TITLE
Lua error Balance druid

### ISSUE THREAD

**Issue by Rynxz** [Hekili/hekili#145]

**Comment by Rynxz** [comment]
v8.1.5-18 

Happens dureing combat in dungeons or raids. Never seen it while soloing

87x Hekili\Utils.lua:16: bad argument #2 to 'format' (string expected, got nil)
[C]: ?
Hekili\Utils.lua:16: in function <Hekili\Utils.lua:15>
Hekili\State.lua:673: in function <Hekili\State.lua:669>
Hekili\State.lua:736: in function `removeBuff'
Hekili\Classes.lua:1715: in function `handler'
Hekili\State.lua:4716: in function `RunHandler'
Hekili\Core.lua:1225: in function `ProcessHooks'
Hekili\UI.lua:820: in function <Hekili\UI.lua:684>

Locals:
InCombatSkipped

**Comment by Hekili** [comment]
Go ahead and fill out the required information for the ticket as well.
