### ISSUE TITLE
[BUG] LUA Error - 1704 attempt to call global 'GetItemTexture' (a nil value)

### ISSUE THREAD

**Issue by Trantore** [Hekili/hekili#1450]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili has an LUA error almost immediately after starting the game on my Beast Mastery Hunter - if I clear the bug from BugSack & SpartanUI it will reappear fairly quickly

### How to Reproduce

Enter game as dwarven Beast Mastery Hunter
Start playing - LUA error happens frequently - 53 times in a 30 min session

### Player Information (Link)

https://pastebin.com/e8Mvfjci

### Error Messages (Link)

https://pastebin.com/WrF19h2f

### Additional Information

Unless I am missing something there is no feature to copy the COMPLETE BugSack entry in one action.

I had to copy sections at a time and join them together - hopefully without mistakes!

**Comment by Hekili** [comment]
This is resolved in the latest alphas and will be in the new release.
