### ISSUE TITLE
[REC] Feral: The First Sigil trinket not recommended.

### ISSUE THREAD

**Issue by deodanyt** [Hekili/hekili#1451]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

hekili dont recomends first sigil on opener on my feral idk if its same for other classes

### How to Reproduce

1.log on feral
2.take first sigil trinket and any other
3.start opener 
4. see that first sigil ist recomendet

### Snapshot (Link)

https://pastebin.com

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qHNEsuAsaNuCq7Rd2SbNTH

### Additional Information

normaly you would take first sigil after berserk

### Contact Information

pummeluff#2116

**Comment by deodanyt** [comment]
https://pastebin.com/FJ03zbP0
here new pastbind accidently put wrong

**Comment by Hekili** [comment]
> v9.2.0-1.0.6

![image](https://user-images.githubusercontent.com/9438134/160300854-10cbb134-e081-4782-af41-12a68c8fe306.png)

This should be resolved in the latest alpha (1.0.13-alpha4) and will be in the next full release.
