### ISSUE TITLE
[BUG] Execute being suggested when the boss was significantly above 20%

### ISSUE THREAD

**Issue by BigBong69** [Hekili/hekili#1453]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Execute being recommended when the boss is above 20% (AKA when the spell was not castable). for testing purposes, I talented into sudden death to make sure that the procs aren't messing up the suggestions. Curiously this only happens in lords of dread and nowhere else (though I haven't played much arms warrior anywhere else)

### How to Reproduce

1.Enter the game as arms warrior
2. (optional) take skullsplitter in order to remove execute procs
3. Go to lords of dread (for some reason it functions as expected everywhere else though I don't play arms often on anything but lords)
4. execute is being recommended when the target hp is significantly above 20%.

### Snapshot (Link)

https://pastebin.com/M7N6ZMnN

### Contact Information

105°C#0854

**Comment by Hekili** [comment]
Thanks, I'm investigating this now.

**Comment by Hekili** [comment]
This should be resolved in 1.0.13.
