### ISSUE TITLE
[BUG] 4 set bug with venthyr druid

### ISSUE THREAD

**Issue by noiseuu** [Hekili/hekili#1455]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

So

With 4 set "while in an eclipse, the cost of Starsurge and Starfall is reduced by 15"
In hekili it suggest but icon is grey and, i cant use it..
I paused and line is st #31
https://gyazo.com/299a452018b537420d193e0ce8bd4a44

### How to Reproduce

1. Just playing m+

### Player Information (Link)

https://pastebin.com/UW6utmUv

### Error Messages (Link)

i didnt get get bugsack errors

### Additional Information

https://pastebin.com/UW6utmUv
Snapshot again for u

**Comment by Hekili** [comment]
I'll fix this, but if you submit any more tickets, please make an effort to pick the right kind of ticket and actually describe the problem in a meaningful way.  The easier you make it for me to understand the problem you are having, the more likely I'll be able to fix it in a timely fashion.

The AP cost reduction of the tier set was tuned based on the original design, and wasn't updated to account for the nerf to 15%.  I am also properly making the cost-reduction limited to when you're actually in an Eclipse, which I'd missed.  I'll post an alpha version for testing in a minute.
