### ISSUE TITLE
Shaman/Enhancement - Suggests FlameShock when target already has it active

### ISSUE THREAD

**Issue by Jroy21** [Hekili/hekili#1456]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Recommendation to cast FlameShock when it's already active on the target. Should recommend Lava LAsh or Primordial Wave (Necro). Looking at logs from top performers, FlameShock is never cast to refresh its duration on a target with it already active.

### How to Reproduce

- Enter the game as an Enhancement Shaman
- Talent choices don't seem to matter but I have replicated the issue with Lashing Flames, Hot Hand, Fire Nova, Sundering, Elemental Spirits.
- Single Target rotation on Single target raid dummy
- Start the rotation and about 30sec in, FlameShock will get suggested while an existing application of FlameShock is rolling on the target

### Snapshot (Link)

https://pastebin.com/ZKwpfgj2

### Contact Information

Dalis#3357

**Comment by Hekili** [comment]
Lava Lash was not available for 5.13 seconds.
Primordial Wave was not ready for 34.86 seconds.

Your choices were to push nothing or to push Flame Shock; pushing Flame Shock was the better option.  There is a class setting you can use to turn this off if you want.  /hekili > Enhancement > Filler Shock.

**Comment by Jroy21** [comment]
Great, thanks for the info, didn't know about the Class settings.
