### ISSUE TITLE
Shaman/Enhancement - Crash Lightning is not suggested before Stormstrike in AOE situation

### ISSUE THREAD

**Issue by Jroy21** [Hekili/hekili#1457]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using the AoE profile, I noticed Stormstrike and Lava Lash being suggested ahead of Crash Lightning when the Crash Lightning and Gathering Storm buffs are not active.
<img width="1159" alt="CrashLightning" src="https://user-images.githubusercontent.com/102682629/160913689-4f640231-f429-40f2-ae2c-b3d9666e41b2.png">
 

### How to Reproduce

1. Enter the game as an Enhancement shaman
2. Talent configuration is not really relevant, this buff is baseline
3. Attack multi-target dummies using the AoE profile
4. Roughly 15sec into the rotation Lava Lash and Stormstrike will be suggested ahead of Crash Lightning.

### Snapshot (Link)

https://pastebin.com/HCjPUCjA

### Contact Information

Dalis#3357

**Comment by Hekili** [comment]
1. There's no AOE "profile."  There's just a priority list that can make different recommendations based on targets and other factors.
2. Actually, talents do influence when you'd use Crash Lightning.  With Crashing Storm, you end up using it again before the Crash Lightning buff expires.
3. In your snapshot, you had another 1.79 seconds of Crash Lightning buff up.  This means both the Lava Lash and the Stormstrike would already be buffed and the cast after would reapply Crash Lightning.
4. Refreshing Crash Lightning early, when both Lava Lash and Stormstrike are ready to be used, would represent a waste of 2 GCDs of cooldown recovery (1 GCD for LL, 1 GCD for SS).  Opportunity cost isn't always intuitive, but that's the case here.

If you're interested in identifying new optimizations for Enhancement, take a look at the default profiles in SimulationCraft.

https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier28/T28_Shaman_Enhancement.simc
https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier28/

The SimC wiki can provide clarification about how priority lists work, but essentially you start from the top and execute the first thing in the list that is ready (not on CD, has required resources) and has its conditions met (`if=xxx`).

It takes a lot of careful iteration to figure out which optimizations are actually worthwhile; that's been an issue for Enhancement for years.

**Comment by Jroy21** [comment]
Thanks for the explanation
