### ISSUE TITLE
[BUG] DPS/Guardian rotation being suggested when in Druid Restoration spec

### ISSUE THREAD

**Issue by CaffeineFueled** [Hekili/hekili#1459]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Greetings.

I am running v9.2.0-1.0.13 as a Druid.  When I change spec to Restoration, Hekili seems to be "remembering" my previous spec and showing icons for it.  The icons do not change when I cast spells which suggests it is not actively monitoring my casts, but they are definitely spells from the previous spec.  For instance, if I go Balance, cast a spell at a target dummy, then change spec to Restoration, Hekili will show Balance abilities (some of which I do not have access to as Restoration).  Same for going from Feral or Guardian to Restoration; Hekili will show either Feral or Guardian abilities.  Affinity does not seem to play into the issue.

Here you can see Hekili suggesting Fury of Elune as the 5th ability which is not available as Restoration:
![image](https://user-images.githubusercontent.com/6114721/161164011-31aa7d8c-e429-486f-ade2-beeafa505410.png)

Luckily, reloading or relogging makes this behavior go away until the next time I change spec.

### How to Reproduce

1. Log into a druid.
2. Change spec to Balance.
3. **ATTACK A TARGET DUMMY OR MOB** -- in my testing, the behavior did not express itself until I attacked something.
4. Drop combat and change spec to Restoration.
5. Walk up to a target dummy and target it.

You should see Hekili icons on your screen.

### Player Information (Link)

https://pastebin.com/vC71iAKX

### Error Messages (Link)

https://pastebin.com/vC71iAKX

### Additional Information

To my knowledge, there are no errors.

**Comment by Goldenstar74** [comment]
Hello,

I have the same issue with Resto Shaman when I switch from Enhance to Resto on my shaman.

If I /reload while in Resto spec the issue clears, I have also noticed the issue will happen when in Resto spec and join a group, again /reload resolves the issue.

Let me know if you need any more detail or information

**Comment by Hekili** [comment]
Thanks, this will be resolved in today's release.
