### ISSUE TITLE
Defensives and Interrupts; spells not showing in the bars

### ISSUE THREAD

**Issue by defions** [Hekili/hekili#146]
Hi,

I can't seem to get the defensive and interrupt bars to show spells for my havoc demon hunter. I've tried multiple options on the toggle menu, checked that the abilities are set to defensives and/or interrupts as applicable, and have read all the setup instructions I can find. Still the aforementioned bars remain empty. That being said, the primary bar is working well. Thanks.

build: v8.1.5-18
level: 115
class: DEMONHUNTER
spec: havoc

talents: blind_fury
    demon_blades
    demonic
    first_blood
    master_of_the_glaive
    soul_rending
    trail_of_ruin

traits: azerite_empowered=3
    burning_soul=1
    impassive_visage=1
    revolving_blades=1
    seething_power=1
    self_reliance=1
    thirsting_blades=1

sets/legendaries/artifacts: none

gear:     charm_of_demonic_fire=1
    banisher_jerkin=1
    rusty_steelclaw=1
    shimmering_quicksilver_drape=1
    banisher_grasps=1
    demon_trophy=1
    heart_of_azeroth=1
    banisher_footwraps=1
    banisher_strap=1
    banisher_trousers=1
    bracers_of_dreadful_maladies=1
    band_of_wortcunning=1
    spectral_revenger=1
    risebreachers_band=1
    shoulderguards_of_the_champion=1
    cursed_boarhide_helm=1

**Comment by Hekili** [comment]
Defensives are for tanks, you'd have to write an action list that makes defensive recommendations for Havoc.

Interrupts show when there's something to interrupt, based on your interrupts toggle.

**Comment by defions** [comment]
That makes sense.  Thanks for letting me know.  and a great addon
