### ISSUE TITLE
[REC] Balance - Convoke not recomennded on Pulsar proc when CDs are disabled and Covenants are enabled

### ISSUE THREAD

**Issue by woefulwabbit** [Hekili/hekili#1461]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On several raid encounters, the use of Bloodlust is often delayed until the final phase (e.g. Vigilant Guardian, Artifixer Xy'mox, Prototype Pantheon, Halondrus). In such encounters, CA/Inc will be used once at the start of the fight, and the 2nd (or 3rd, if the fight is long enough) use of CA/Inc should be synced with the use of Bloodlust. Convoke should continue to be used whenever Pulsar procs.

With Hekili, this should be expected to be achieved by disabling Cooldowns after the first CA/Inc is completed so that CA/Inc will not be recommended when it completes the cooldown, until it is enabled again just before Bloodlust is to be used. Covenant will remain enabled to allow Convoke to be recommended when Pulsar procs.

However, the current APL does not recommend Convoke when Cooldowns are disabled, even when Covenants are enabled.

### How to Reproduce

1. Enter the game as a Balance Druid
2. Select Night Fae Covenant
3. Equip Unity and Primordial Arcanic Pulsar
4. Disable Cooldowns on Hekili
5. Enable Covenants on Hekili
6. Use Hekili recommended rotation on a target dummy until Pulsar procs
7. Note that Hekili does not recommend Convoke after Pulsar procs

### Snapshot (Link)

https://pastebin.com/6acZC88s

### Contact Information

wabbit#3202

**Comment by Hekili** [comment]
Yeah, you were right in our other discussion on this topic -- `druid.no_cds` in SimC will block usage of Convoke even though the addon lets you toggle Convoke separately.  I'll remove the `druid.no_cds` check since it's not needed for addon purposes.

**Comment by Hekili** [comment]
1.0.14 should address this issue.
