### ISSUE TITLE
[Surv Hunter] Problem with CT rotation and mad bobardier implementation in one target.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1462]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Faced a problem. That the proposed rotation to one target deprives us of the full bombs and does not give a chance for the implementation of mad bobardier. Rotation suggest us to immediately use 2 bombs in a row, and thus we are waiting for 8 seconds of the bomb. When before that the following recommendations were in rotation. We used 1 bomb, then used kill comand twice to have a chance of getting the mad bobardier buff. And after that, we start using the cyclic receipt of bombs from the mad bobardier buff, so to speak. And now the rotation looks like that from the beginning of the pool I immediately threw out 2 bombs, I sit for 8 seconds without bombs, I get the mad bobardier buff and wait for the bombs to appear, I use the bomb from the mad bobardier buff again and the rotation again suggest that I drop the next bomb without getting samples mad bobardier and the implementation of this buff. We cannot use bombs in one target like this. Because we either use bombs for 2-3 seconds before the end of the cooldown of the next bomb, or we try to get mad bobardier to release as many bombs as possible.

### How to Reproduce

1. Take one target. 
2. Use a bomb, and rotate to suggest the next bomb.

### Snapshot (Link)

https://pastebin.com/TqzSXCuw

**Comment by PoroKingWin** [comment]
I think this is happening because the full_recharge_time is always 0 for Wildfire Bomb (this is probably part of the new changes to make it work for spells that are unknown) so it thinks the player is permanently capped. The APL has it as a priority to not cap so it is recommending bomb as soon as it's available. I think this might be because of the changing spell ID for Wildfire Bomb when using Wildfire Infusion so it always considers the spell unknown as they're not the ID for Wildfire Bomb

**Comment by Hekili** [comment]
This was a bug that should be resolved in -alpha3.  Thanks for the report.

For future reports, if necessary, I'd appreciate it if you can keep it brief and in bulletpoints or numbered:

1. I see X, Y, Z.
2. I should see A, B, C.
3. Because D, E, F.

**Comment by Dragonfo** [comment]
Thanks for the quick fix. For the future, I will take into account I will describe the problem more briefly) And also thanks to PoroKingWin for finding the problem.
