### ISSUE TITLE
[Vengeance Demon Hunter] Infernal Strike Usage

### ISSUE THREAD

**Issue by Dreamin93** [Hekili/hekili#1463]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hey I was wondering if it's possible to get the addon to recommend using Infernal Strike if you are about to cap two charges.
(as is recommended in the wowhead guide: https://www.wowhead.com/vengeance-demon-hunter-rotation-guide)

Currently it just recommends you waste them both on pull.

### How to Reproduce

Enter game as Vengeance Demon Hunter
Go attack a target
Addon will recommend using covenant ability then Infernal strike x2
(using 2233221 talents)

### Snapshot (Link)

https://pastebin.com/R3fXfXFi

### Contact Information

Jordan#4168

**Comment by Hekili** [comment]
Your snapshot doesn't show what you're saying you see.

**Comment by Hekili** [comment]
If I had to guess, this might've shown up for you based on a bug impacting abilities with charges that is fixed in the upcoming alpha build.  If not, let me know and provide a snapshot showing the issue.
