### ISSUE TITLE
[BUG] Warlock (Destruction) - Immolate spam in AOE scenario bug

### ISSUE THREAD

**Issue by yomeistro** [Hekili/hekili#1465]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Whenever i'm in a heavy add AOE scenario in which you would be using Rain of Fire, the rotation helper tells you to spam Immolate if there are 5+ targets until Rain of Fire can be used again. instead of the normal rotation. Upon trying to recreate this, it seems it only happens inside dungeons, outside of dungeons it seems to work normally.

Screenshot here: https://imgur.com/a/y2d7lFx
 

### How to Reproduce

Enter a dungeon as a Destro Lock and go in a heavy AOE scenario where you should be using Rain of Fire, use it, then it should happen.

### Snapshot (Link)

https://pastebin.com/LRJBVXau

### Contact Information

BITCH#7864

**Comment by Hekili** [comment]
Can you sim yourself in a 5 target scenario and provide the link?

**Comment by yomeistro** [comment]
https://www.raidbots.com/simbot/report/cAuFtDFvqHB7zENyZ1WbV5

**Comment by Hekili** [comment]
Ok, so, fun news:  your sim does the same thing!  The default profile will absolutely spam Immolate in multi-target.

![image](https://user-images.githubusercontent.com/9438134/161434003-8a748e18-6260-4d0a-a9ad-c407009012cc.png)

https://www.raidbots.com/simbot/report/ou69AFLgrgdzt2ssYVVbux

I tried a couple of quick edits and it's clearly a mistake.  I'll post a ticket for SimC to do their updates and make matching updates to the addon.

**Comment by yomeistro** [comment]
your a star mate thank you very much!
