### ISSUE TITLE
[FEATURE] Add option to disable addon for specific specs

### ISSUE THREAD

**Issue by Elmegaard** [Hekili/hekili#1466]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I am playing all three specs of my Monk actively and using Hekili for both Brewmaster and Windwalker. The issue is that there is no Mistweaver spec but the addon is still enabled and recommending spells that I don't even have access to, it is also showing keybinds for those spells even though it is not in the hotbar. But that is not really an issue, I'd rather have the entire addon disabled whenever I am in the Mistweaver spec.

**Comment by Hekili** [comment]
Use the latest version of the addon.
