### ISSUE TITLE
Hunter/Surv recommending double bomb when it shouldn't

### ISSUE THREAD

**Issue by TheHambrick** [Hekili/hekili#1468]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When wearing the 2 set for survival hunter, the addon will initially recommend using two bombs in a row, but will remove the 2nd bomb from the future list as soon as the first bomb hits. It isn't too much of an issue if you're following the far left recommendation, but it does create a bit of visual clutter.

### How to Reproduce

1. Enter game as a Survival Hunter
2. Obtain your 2 set tier from season 3 of Shadowlands
3. Choose the Wildfire Infusion and Guerilla Tactics talents
4. Use Wildfire bomb so that you retain 1 charge but not 2
5. Use kill command to proc the 2 set bonus
6. See recommendations.

### Snapshot (Link)

https://pastebin.com/u45reVDW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8F7dWeyR8sJp35Ex9kY94Z

### Additional Information

Looking over the raidbots sample action list, it does sometimes use 2 bombs in a row, but it seems to be basically only happen in the sim when hasted from lust, or in a situation like where resonating arrow will be up in a few seconds and that would interfere with not sitting on a 2 charge. I also took a snapshot where it's recommending to use 2 bombs even though there are over 10 seconds left on the bomb recharge timer and that is linked below this.

https://pastebin.com/niuATXkj

### Contact Information

Jackson

**Comment by Hekili** [comment]
Can you recheck this with 1.0.15?  Thanks.
