### ISSUE TITLE
[BUG] Hekili does not disappear when switching to unsupported specs. (HPal)

### ISSUE THREAD

**Issue by faidtastic** [Hekili/hekili#1469]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have a paladin and I use Hekili for the ret spec only. I have the "Enabled" box unchecked in prot in order to disable it. There is no option for Holy to enable/disable it for that spec, understandably.

If I am in ret spec the Hekili display shows properly. If I switch to Prot (a specific spec I have disabled in the Hekili options) Hekili disappears, and reappears when I switch back to ret. Intended/working great.

However, if I'm in ret and switch to Holy the Hekili display 1) does not disappear, 2) continues to show specific abilities, and 3) does not "update" as I use abilities. If I do a /reload Hekili does not still appear in Holy, but I have to do this every time I switch from Ret to Holy.

### How to Reproduce

1. Be a ret paladin.
2. Have Hekili installed.
3. Switch to Holy spec.

### Player Information (Link)

https://pastebin.com/prh63w7S

### Error Messages (Link)

No in-game bug messages appear.

### Contact Information

Discord Faid#6495

**Comment by Hekili** [comment]
Thanks for your ticket.  Please download and install https://github.com/hekili/Hekili/releases/v9.2.0-1.0.15-alpha2 and see if the issue persists.

**Comment by faidtastic** [comment]
Yes, this version you've posted above is now working well, thank you!!
