### ISSUE TITLE
[BUG] Hekil no showing modifier key for modifier keybinds

### ISSUE THREAD

**Issue by Glorithan** [Hekili/hekili#1470]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am using the addon Dominos for my action bars. I disabled it and ensured there were no abilities bound to the default action bar. I have abilities bound to Shift +1, Shift+2, etc but hekili only shows the number/letter and not the shift/alt/ctrl modifier key like it used too.

![image](https://user-images.githubusercontent.com/78930333/162120239-467eebe1-0ea4-44dc-b241-c6ac2a712c59.png)

### How to Reproduce

1. Log into hunter
2. View hekili doesn't show shift modifier on my cooldowns like it used too

### Player Information (Link)

https://pastebin.com/u3TNj4im

### Error Messages (Link)

N/A

### Contact Information

Hoku#3305

**Comment by Glorithan** [comment]
I just dropped dominos and it fixed it.

**Comment by tmttn** [comment]
I am seeing the same behaviour, besides that I want to add that Spellflash also doesn't work for any dominos action bar, besides action bar 1.

**Comment by Hekili** [comment]
This is a closed ticket.

If the detected keybinds are not correct, you can specify your keybinds in /hekili > Abilities.  Thanks!
