### ISSUE TITLE
Survival Hunter Serpent Sting Spam

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#1474]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While Serpent Sting's dot is active on the target and other abilities are available, Hekili advises me to spam Serpent Sting regularly (before being even close to the refresh window around 3s from the dot falling). It appears that SS isn't advised in the "coming advices" but suddenly appears at the top priority, like if the dot was not up anymore. 

Two different pastebins with the same problems when ignoring spamming advice : 

https://pastebin.com/VB4DjxAW

https://pastebin.com/SCdJ4ZVS

### How to Reproduce

Play Surv
Talents : 3 1 2 1 3 1 2 
No legendaries
Covenant in Night Fae - Dreamweaver
Do normal ST rotation

### Snapshot (Link)

https://pastebin.com/VB4DjxAW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/t7sjMpHweYyD6fQ3LVpPDh

### Additional Information

Here is how the damage profile appears if I respect completely the SS spam (SS should be much lower, considering Raidbots' sim it should be no higher than 20 casts and way lower that Raptor Strike)

![image](https://user-images.githubusercontent.com/47482996/162551028-922e13dd-8200-48d9-b13f-e5c3e4c174fe.png)

**Comment by Hekili** [comment]
Thanks for the report.  Are you the only Survival Hunter in your raid?

**Comment by Lipstopica** [comment]
I've also encountered this. I was with another Hunter but he was a MM Hunter in a dungeon. I didn't get a snapshot only because I've just encountered and didn't see this until after. I will get a snapshot next time I see it happen, if needed.

**Comment by Hekili** [comment]
So far, I'm trying to determine if:

1. It only happens with "Recommend Target Swaps" enabled (this shows as `cycle = true` in snapshots.
2. If this only started with 1.0.15, which attempts to use a more efficient aura detection system.
3. If this only happens with another Hunter also using Serpent Sting.

In Amortalist's post, the addon has clearly detected Serpent Sting on the target pre-recommendations but then shows `dot.serpent_sting.ticking[false]` when it recommends using Serpent Sting.  I'm still trying to figure out what could cause that incongruity.

**Comment by Lipstopica** [comment]
1. I had my target swap disabled when it happened to me
2. If I have time later on I will go pre version and see if I can catch it 
3. The MM I was with did not use the talent Serpent Sting or the legendary that grants Serpent Sting

I couldn't seem to replicate the issue on a target dummy when I tried too.

**Comment by Amortalist** [comment]
I tried without recommended swap and it seemed to have done the same SS spam, actually in the Hekili minimap menu as a survival hunter, whether you click on "recommend target swap" or not doesn't trigger the yellow dot that indicates if it's active or not, rather you have to see the prompt in the middle of your screen. It has been doing that in Single Target bosses (or no continuous ads) like Dausegne.

**Comment by Dragonfo** [comment]
If you look at the APL, then conditions are worked out there such as if there are 3 seconds left on the target before the Serpent sting subsides, the addon should check if we have a bomb.volatile to update the SS, or do a refreshabl. But the addon does not work out these conditions very well. 
`serpent_sting,target_if=min:remains,if=!dot.serpent_sting.ticking&target.time_to_die>7|buff.vipers_venom.up&buff.vipers_venom.remains<gcd`
`serpent_sting,target_if=min:remains,if=refreshable&target.time_to_die>7|buff.vipers_venom.up`

The addon does not work well with this condition with a T4 set. 
Because the addon reacts badly to the update in the AOE voliate bomb.
`wildfire_bomb,if=full_recharge_time<2*gcd&set_bonus.tier28_2pc|buff.mad_bombardier.up|!set_bonus.tier28_2pc&(full_recharge_time<gcd|focus+cast_regen<focus.max&(next_wi_bomb.volatile&dot.serpent_sting.ticking&dot.serpent_sting.refreshable|next_wi_bomb.pheromone&!buff.mongoose_fury.up&focus+cast_regen<focus.max-action.kill_command.cast_regen*3)|time_to_die<10)`
But when with the T4 set, there seem to be problems with the SS update unnoticed. It refreshes it for 3-2 sec.

But I suppose that the whole problem lies precisely in the first two conditions. Because the conditions come from them already on wildfire_bomb.

**Comment by Hekili** [comment]
The minimap dropdown is a separate issue that I have fixed but not released.

So far, I am *thinking* that the newer code that tries to make aura updates more efficient is just...losing track of Serpent Sting somehow, and it may occur for other auras.  I am adding some code to test and catch scenarios where a snapshot detects a buff/debuff up front but that it is missing when decisions are being made.  I'll post an alpha for 1.0.16 in a little bit that will collect this information when a snapshot is generated.  That will require new snapshots to be made.

**Comment by Hekili** [comment]
@Dragonfo I'll take a look and see if I can prove that extensions/applications by Volatile Bomb are a trigger for this issue.  That's a good suggestion.

**Comment by Hekili** [comment]
Okay, 1.0.16-alpha1 is available now.  I made it so Snapshots will now tell me if you have a buff but the addon didn't capture it earlier.  I also reverted a change to buff detection that will force all buffs and debuffs to be updated more often.

I couldn't find any relationship between Serpent Sting disappearing and Volatile Bomb, although I was testing on dummies and dummies have odd behavior that might cause that to break.

**Comment by Hekili** [comment]
Please update and let me know if the Serpent Sting issue persists with the alpha version.  If it's resolved, I'll leave these solutions in place.  If it's not resolved, please post updated snapshots so I can investigate further.  Thanks!

**Comment by Amortalist** [comment]
It seems to be ok now, tried multi target and ST, haven't seen any SS spam advised

**Comment by Hekili** [comment]
I'll be putting these changes into a release this week.  Thanks!
