### ISSUE TITLE
Fae Transfusion always showing

### ISSUE THREAD

**Issue by Shamuray82** [Hekili/hekili#1478]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Fae Transfusion doesnt hide from priority when checked as disabled or show on boss only

### How to Reproduce

Select abilities, fae transfusion, check disable or boss only and it still shows in priority

### Snapshot (Link)

https://pastebin.com/WdDaYnWe

**Comment by Hekili** [comment]
Show me a screenshot of your settings where you have Fae Transfusion disabled or set to show on boss only.

**Comment by Shamuray82** [comment]
![ss](https://user-images.githubusercontent.com/103365654/163228829-5d26ac43-48c8-48f5-b793-9d3dcd74d5f7.jpg)

**Comment by Jimmis79** [comment]
I can confirm that Fae Transfusion is been shown even when is disabled

**Comment by Shamuray82** [comment]
any chance it can be hotfixed?

**Comment by Hekili** [comment]
It will be fixed; I've been busy with my real job so I haven't had time to resolve it, but it will be fixed this weekend.

**Comment by Shamuray82** [comment]
ty vm

**Comment by Jimmis79** [comment]
Thank you very much for your hard work and the awesome addon! I am using it for years! I can't play WoW without it:)

**Comment by Hekili** [comment]
Fix is incoming.  Thanks for reporting.
