### ISSUE TITLE
[RECOMMENDATION] Blood DK using Blood Boil less during DRW with tier set.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1479]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

There is a problem with the rotation in AOE With a T4 set for BDK. When DRW is active we only use Heart strike and death strike, and very little blood boil. The essence of the problem is that due to the small amount of blood boil used during DRW, we lose AoE dps, and as a result, aggro with a number of worthwhile targets. As I understand it, this problem is related to APL, not on the side of the addon's recommendations. I would like to suggest that you make a small workaround. We need to reduce the number of death strikes during active DRW. Only use death strike when there are 5 stacks of hemostasis. Without 5 stacks of hemostasis, don't cast Death Strike. And if instead of Death Strike we add more blood boil we will get more dps in aoa and thus there will be no problems with aggro during active DRW.

### How to Reproduce

1. Take BDK and t4 set + kriya covenant.
2. Start a fight with 5 targets.
3. Activate DRW

### Snapshot (Link)

https://pastebin.com/XyE8JgcT

### Additional Information

Attached a second Snapshots, in order to once again show that we have a large gap between the use of blood boil. https://pastebin.com/Ei3FfUKB

**Comment by Hekili** [comment]
Have you made sims for the changes you're asking for?  What is the result?

**Comment by Dragonfo** [comment]
Here I apologize, but I'm not strong here, I don't know how to make a sim with changes.

**Comment by Hekili** [comment]
You'd have to be able to explain the "why" for your changes.  If you can't sim it, you still need to provide a sim of your character in the situation you describe, and explain why you think this would perform better.

**Comment by Dragonfo** [comment]
Here are my two sims. https://www.raidbots.com/simbot/report/3mBgFBmk1JyZDQtjhsMECA  https://www.raidbots.com/simbot/report/ibcLJSfqXhzxGK1qR1cDtk Why did I emphasize on the ability of Blood boil during active DRW. According to the rotation of the sim, we have the minimum amount of Blood boil. This is due to the fact that now the rotation is built around DRW and its cooldown. Here is a screenshot of how the BDK rotation should look like with a T4 set in M+. https://imgur.com/ZPIBips If you look at the same logs and rotation it will be clear that we should use on average from 250-300 Blood boil. According to the sim, Blood boil is used very rarely in our country. Second screenshot https://imgur.com/sVvnRp2 This is what a rotation with DRW active should look like. Now the sim and addon recommendations look more like a CT rotation. In single target fights we are fine, we don't need to use Blood boil so often in single target fights. In AoE, we have a rotation that is more suitable for one target. Death strike is very common in DRW rotation. We use it without Hemostasis talent stacks. It turns out that we ignore the Hemostasis talent and press Death strike with low healing efficiency. With DRW active, we don't need to use Death Strike as often. Because we block 60% damage due to active DRW. as before, we don’t have % of health falling as quickly as it was before the T4 set. I see a rotation such as in the screenshot that I attached. This is an acceptable rotation when DRW is active. We extend the duration of DRW with Heart Strike and we press Blood boil for more AOE damage with DRW and create more aggro. Death Strike in this case makes sense to press when we have less than 60% health, because all the rest of our damage is absorbed by DRW. we have a parry due to the huge active time of the DRW. Which helps us avoid a lot of damage. We just need to press 2 buttons during DRW to extend and deal damage in AoE, and one button to heal when our health drops to a certain %. It looks like good tanking in AOE.
![2](https://user-images.githubusercontent.com/63850853/163229428-fe90ee32-1cc0-4325-9fb1-4920a2330e22.jpg)
![1](https://user-images.githubusercontent.com/63850853/163229431-1e81732d-9d44-4af0-a1cc-11a7b0e2194a.jpg)

**Comment by Hekili** [comment]
I just want to remind you that the "wall of text" explanations are a real challenge to interpret and work with.  Please think about submitting bullet points with short, specific topics.  This is...too much.  I need to be able to clearly delineate "here is what the addon/sim does" vs. "here is what I want" vs. "here is the evidence that supports what I want."

I'm sorry if there is a communication barrier, but it would *really* help me to help you if you can organize your arguments a bit.  I'll try to sort through this, but it is going to take time for me to break it down, and you submit a lot of tickets.  If you're going to submit tickets, you are going to have to make it easier for me to follow.

**Comment by Hekili** [comment]
I'm getting closer to a sim profile that uses Blood Boil more, but there has been a fairly significant loss of mitigation in the process.

https://www.raidbots.com/simbot/report/sU3DLjJFziUDei4jmqoYPG
https://www.raidbots.com/simbot/report/93B3hbYLUXdVt2M3SNENK5

**Comment by Dragonfo** [comment]
Hello. I apologize for not answering for so long. I saw that you added these changes to the alpha version. I tested with this function in AoE damage increased, and problems with AoE disappeared. 
There is a problem now with DRW. There is a suggestion to use a runic power overcap in favor of extending the DRW time. Right now the addon uses Death strike when we hit the runic power cap, but we still have 3 active runes to use Heart Strike. I suggest using Heart Strike and Blood boil while DRW is active. Death strike can only be used when our health percentage drops to 50%.  This is due to the fact that while DRW is active, we do not need to press Death strike so often. We parry blows. Due to the now frequent use of Blood boil. For 1 use of Death Strike under DRW, we will be able to make ourselves 100% health with 1 hit with 50% health.

**Comment by Dragonfo** [comment]
We just need to reduce more death strikes during DRW. To increase DRW uptime. The current game for BDK looks like our healing is cut off by 3 times. Due to the large uptime of DRW
![1](https://user-images.githubusercontent.com/63850853/163668380-4a724845-adc6-4ca5-bce5-03ecc9755953.jpg)
.

**Comment by Dragonfo** [comment]
I've also attached screenshots. To show that we still have problems with DRW uptime and we still need to reduce the number of death strikes. We should have DRW uptime somewhere around 70-80% 
To make it comfortable to tank. Now while uptime does not exceed 60% percent. We lose 20% on using Death strike.
![1](https://user-images.githubusercontent.com/63850853/163672680-0020ddd2-e4d0-463e-ab6b-42c2a0ac9338.jpg)
![1](https://user-images.githubusercontent.com/63850853/163672696-c3a73e0a-c5e5-4bab-8807-a061c0a75a5d.jpg)

**Comment by Hekili** [comment]
I would encourage you to work with SimulationCraft to prove the changes you are asking for.  You are welcome to add to this closed ticket when you have data that supports further changes.  Thanks.
