### ISSUE TITLE
[REC] No Niuzao on Brewmaster

### ISSUE THREAD

**Issue by SirWillae** [Hekili/hekili#1480]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Niuzao seems to be missing from the rotation for Brewmaster.  I just spent a good 5 minutes at a training dummy and he never showed once.  I double checked to make sure I have Cooldowns enabled in the menu.  I noticed there's some pretty complicated logic regarding Niuzan and Purifying Brew.  I wonder if it's related to that.

### How to Reproduce

1. Start fight as Brewmaster
2. Follow Hekili recommendations
3. Niuzao never shows up
4. Being a 3-minute ability, it should probably be one of the first things you do.

### Snapshot (Link)

https://pastebin.com/DVpCJqsh

**Comment by Hekili** [comment]
You can see the criteria in /hekili > Priorities > Brewmaster.  Invoke Niuzao appears in the default action list.  It requires you have a target that will live 6+ seconds, and that you have fewer than 2 Purifying Brew charges.  If you aren't taking damage and purifying, it won't be recommended.

```
22.  invoke_niuzao ( default - 17 )
The action (invoke_niuzao) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +10.00).
 - this entry's criteria FAILS: target.time_to_die[665.00] > 6 & cooldown.purifying_brew.charges_fractional[2.00] < 2
 
 ```

There are some new criteria for Brewmaster in sims that I have not yet implemented, but if you fight a tank dummy and use Purify, you should find Niuzao to be recommended in the meantime.
