### ISSUE TITLE
On Default, Hekili wants me to moonfire everything before using rotation.

### ISSUE THREAD

**Issue by twonwick** [Hekili/hekili#1481]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Every encounter in dungeons (haven't tested raids yet) the ui tells me to use moonfire on everything i'm in combat with, sometimes (rarely) it will tell me to cast moonfire on a single target encounter several times before it goes away. It won't continue the rotation until i moonfire all targets it wants me to. Sunfire will say the same thing but it goes away after i sunfire one thing.

### How to Reproduce

Play ass boomkin
Go into combat with default settings
Moonfire everything

### Snapshot (Link)

n/a

### Contact Information

Longdickmike#1999   <<<Discord

**Comment by Hekili** [comment]
You'll have to submit a complete ticket with the snapshot showing this occurring. 

Did you import a priority? There's no need.
