### ISSUE TITLE
When Destro lock gains the buff (ritual of ruin) from the two piece set bonus, the addon is not recommending to use the proc right away 

### ISSUE THREAD

**Issue by Doog45** [Hekili/hekili#1483]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As Destro Lock with having the two set tier, the addon is not recommending to use the procs from ritual of rain buff right away.  Sometimes not for a while.  When I get the proc chaos bolt and rain of fire both light up and I get a free cast of one of them, but the addon often times doesn't say to use it.  In the picture below you can see I have the proc, but the addon is recommending different spells for the at least the next 5 spells.
![WoWScrnShot_041722_230847](https://user-images.githubusercontent.com/43385477/163816367-79ce5c10-7f2b-485d-a985-040228effefd.jpg)

### How to Reproduce

Play destro lock while having two piece tier set.  Gain 10 soul shards and get the buff ritual of rain.  

### Player Information (Link)

https://pastebin.com/q5z4GntS

### Error Messages (Link)

none

### Contact Information

Discord Doog#5589

**Comment by Hekili** [comment]
This is not a bug report; this should be a recommendations ticket with a snapshot of recommendations along with a sim of your character to compare.  You can add a snapshot and sim link and reopen if you'd like me to review it.

However, keep in mind, with Ritual of Ruin up, the Destruction sim profile is written to pool shards and not immediately spend.

![image](https://user-images.githubusercontent.com/9438134/164991030-67fea8c5-4c3f-4230-9f4b-adde83b3421e.png)
