### ISSUE TITLE
[BUG] Spellflash Texture Option not working

### ISSUE THREAD

**Issue by Darthkakarot** [Hekili/hekili#1485]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Spellflash seems to work correctly, I am unablke to change the display to be any of the dropdown in the texture part of the spell flash settings. 

I have 
SpellflashCore 8.0.1 (latest version available in Curseforge)
SpellFlash 8.0.5 
ElvUI

I see the blinking queue for the spell in the queue, but no matter what I do it wont change from the default flash animation.

![image](https://user-images.githubusercontent.com/90983907/164489943-63fd5d99-4d26-4e89-98b6-6088610ab0ef.png)

checking Fixed size and/or Brightness does not change the display 

### How to Reproduce

Tested on Enhan Shaman, Frost and Unholy DK

### Player Information (Link)

https://pastebin.com/WBRwL5c0

### Error Messages (Link)

https://pastebin.com/1X32VMM4

### Additional Information

For the bug sack error that is error 1/7, there is an aditional ExRT error. one thaat shows 4x (null), and 4 error related to Raider.IO

**Comment by Hekili** [comment]
I'm not able to replicate this.

> SpellflashCore 8.0.1 (latest version available in Curseforge)
> SpellFlash 8.0.5

You do not need to have these installed separately for the addon to work.

**Comment by Darthkakarot** [comment]
Thanks for checking, today I disabled SFC in game and it works. Thanks for letting me know it doesnt have to be installe separetly. I was deleting and reinstalling SFC and SF, was getting frustrating, TYSM both for the helpo and the awesome addon.
