### ISSUE TITLE
Destruction Warlock, Opening recommendation (Soul Fire, Immolate, Channel Demonfire)

### ISSUE THREAD

**Issue by MistarrBubbles** [Hekili/hekili#1487]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For the opener, I don't expect to see Immolate after a Soul Fire, reason being that Soul Fire applies said Immolate, it then skips the second recommendation and jumps to Channel Demonfire.

### How to Reproduce

Enter as Destruction Warlock.
Talent in to Soul Fire and Channel Demonfire. (For reference, I have talents 3,3,2,2,2,2,2
Target enemy.
It recommends me Soul Fire, Immolate, Channel Demonfire

### Snapshot (Link)

https://pastebin.com/7jUbt8b2

### Contact Information

Santiago#7654

**Comment by Hekili** [comment]
Could you provide a sim of yourself as well?

### Raidbots Sim Report (Link)

**Comment by MistarrBubbles** [comment]
Of course I can.
Here you go: https://www.raidbots.com/simbot/report/kPU7HF21htChQFGBzE3Nmd

**Comment by Hekili** [comment]
So, if you look at your sim, your sim actually does the same thing.  It looks like the addon model and the sim model are not applying Immolate on Soul Fire cast.  I checked SimulationCraft and it applies on impact rather than on cast.  I submitted a ticket for that issue and will make the addon expect Immolate to be applied following a Soul Fire cast as well.

**Comment by MistarrBubbles** [comment]
Ah, I see! That makes it understandable why it does what it does.

I'm glad I could bring this to your attention then, so that you had the chance to review it and bring it forward.
