### ISSUE TITLE
Balance rotation being suggested while I'm in guardian spec

### ISSUE THREAD

**Issue by Majcolorado** [Hekili/hekili#1488]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Issue in title. I saw a previous similar issue described as corrected so I reinstalled the mod to make sure I had the most up to date version without success.

### How to Reproduce

1. Enter game as Guardian Druid.
2. Take Balance Affinity and HotW.
3. Toggle on the Primary Display.
4. This does not occur with Feral or Resto Affinity.

### Snapshot (Link)

https://pastebin.com/VJjdGcNm

### Contact Information

Rage#0949

**Comment by Hekili** [comment]
I'm not able to replicate this.

> Toggle on the Primary Display.

What do you mean by this?

**Comment by Majcolorado** [comment]
I solved this. The addon was suggesting HotW pre pull because that's the max dps move at that moment. Once I press HotW or engage a pack the addon returns to normal suggestions. User error on my part. Sorry for the distraction.
