### ISSUE TITLE
[FEATURE] Keybinds with modifiers

### ISSUE THREAD

**Issue by AckItsMe** [Hekili/hekili#1491]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I use macros heavily with multiple spells/abilities on a single key.  For example, on my DH, I have Demon's bite on my 1 key with Sinful Brand as a modifier.

When it shows up in the UI, both spells show with a 1 for the key.   While this is ok for most toons, for some the spell images are similar so it can be confusing.   

Would it be possible to have it show some modifier option for those abilities?

**Comment by Hekili** [comment]
No, as far as the addon is concerned, it looks at which actions are in which slots and what the bindings are for that slot.  What you're asking for would involve also parsing macros to try to determine all the potential key combinations it could be.

The solution for this sort of issue is already available.  You can go to /hekili > Abilities > Sinful Brand > Override Keybind Text and type what you want to show for Sinful Brand.  If you change your macro or keybind, you'd need to manually change that overridden text as well.
