### ISSUE TITLE
[REC] Unholy DK Snapshots and Warnings

### ISSUE THREAD

**Issue by Prejudice182** [Hekili/hekili#1494]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

This happens during combat with my Unholy DK. Not every fight, but enough that I have decided to report it.

### How to Reproduce

1. Unholy DK
2. Talents: AotD, Asphx, Clawing Shadows, Reaper, Blight, Pact, Wraith
3. Enter combat
4. Wait

### Snapshot (Link)

https://pastebin.com/wAT1JWyL

### Additional Information

Warnings:
https://pastebin.com/EFD5PhYd

### Contact Information

Prejudice#5438

**Comment by Hekili** [comment]
Thanks for reporting; I know this aged quite a bit.  If this continues in the latest release of the addon, feel free to submit an updated snapshot and reopen this issue ticket and I'll take a look.
