### ISSUE TITLE
[BUG] Hekili\Targets.lua error

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#1495]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

?

### How to Reproduce

N/A

### Player Information (Link)

N/A

### Error Messages (Link)

https://pastebin.com/Y93HLY9N

**Comment by Hekili** [comment]
Hi, could you provide the missing information?  I moved the error messages to Pastebin and linked them.  Your Player Information?  How is this error impacting your game?

**Comment by DeathspectreNZ** [comment]
I'm having this issue every zone change.

**Comment by Hekili** [comment]
This should be resolved in 1.0.17b.
