### ISSUE TITLE
[BUG] The spells qeue disapear when i go demonology but works in all other specs 

### ISSUE THREAD

**Issue by JmZz64** [Hekili/hekili#1496]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not laoding normally for my Demonology spec 
![image](https://user-images.githubusercontent.com/104915608/166724281-92912700-3af6-4987-9f4d-9936a1061c0f.png)

### How to Reproduce

Enter game with warlock demonology

### Player Information (Link)

https://pastebin.com/F5u0B6Bf

### Error Messages (Link)

https://pastebin.com/BNuj6zKi

### Contact Information

Inxi#6031 Discord

**Comment by JmZz64** [comment]
Just a precision it was working fine till today's hekili update

**Comment by Hekili** [comment]
The error messages that are linked aren't relevant to the addon.  Do you have multiple errors?  Do any of them contain the word "Hekili"?

Do you see anything about a snapshot being created in your chat box?

Do you see any Warnings shown in /hekili?  If so, what are they?

Can you create a snapshot by pausing the addon (ALT-SHIFT-P by default) and retrieving it from /hekili > Snapshots?  If so, please paste it to Pastebin and provide a link.

**Comment by JmZz64** [comment]
there's that in warning 

Update: Interface\AddOns\Hekili\State.lua:6961: attempt to compare number with table

[string "@Interface\AddOns\Hekili\UI.lua"]:1102: in function <Interface\AddOns\Hekili\UI.lua:903>

**Comment by Hekili** [comment]
And the other questions?

**Comment by JmZz64** [comment]
i don't know how to create a snapshot, i can show you on discord what's exactly happening on my hekili so you will understand better

**Comment by Hekili** [comment]
I explained it right there.  There are instructions in Discord as well (see `!snapshot`).

I have not been able to replicate this issue on my Warlock.

**Comment by JmZz64** [comment]
i'm really bad at these things can i show you directly what's happening via my screen ?

**Comment by Hekili** [comment]
I don't need to see your screen; I need the data that is in the snapshot.

**Comment by JmZz64** [comment]
can't find the discord link to see the section

**Comment by Hekili** [comment]
Actually, I may be okay without the snapshot; I can see that when I match your Imps setting, I get the same warning.  Will fix.

**Comment by JmZz64** [comment]
it's not when i smah imps for me i use 4 spells then hekili stop to queue the spells and nothing else appear

**Comment by JmZz64** [comment]
mb i missreaded, yeah just use the 4 first spells and you normally won't see any more spells after that hekili stop working

**Comment by JmZz64** [comment]
You closed it but idk what to do :/

**Comment by Hekili** [comment]
Get the updated version of the addon.
