### ISSUE TITLE
[BUG] bad argument #1 to 'IsAzeriteItemEnabled'

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#1498]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I'm getting this error after updating to latest beta

bad argument #1 to 'IsAzeriteItemEnabled'

### How to Reproduce

N/A

### Player Information (Link)

https://pastebin.com/zS1zjWaG

### Error Messages (Link)

https://imgur.com/a/f2IPqmZ

**Comment by Hekili** [comment]
What's showing up in Warnings?

Are you *sure* you're not using a custom priority here?

Do you have error messages in BugSack/BugGrabber rather than screenshots?

Have you tried a fresh install (not resetting your profile, but just redownloading the addon itself)?

**Comment by SUU09** [comment]
It got resolved by logging-out then in
