### ISSUE TITLE
[BUG] Hekili wont work on any caracter after update

### ISSUE THREAD

**Issue by MrDickslap** [Hekili/hekili#1499]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Since 6.05.2022 Update theaddon is not working on any of my chars.
Reinstalled it but not working. Looks like hekili cant read, what char i am

### How to Reproduce

Logging into char, not working.

### Player Information (Link)

https://pastebin.com/DjF6aREx

### Error Messages (Link)

not

### Additional Information

All Speccs are activated

**Comment by Hekili** [comment]
You'll have to follow the instructions from the original ticket form so you can submit error messages; otherwise, there's no information here I can use to diagnose a problem.

**Comment by MrDickslap** [comment]
Found the mistake. Some addons blocked Hekili from getting informations. But i sadly cand locate the addon.

**Comment by Hekili** [comment]
Thanks MrDickslap.
