### ISSUE TITLE
LUA error in Beta: attempt to register unknown event "GLYPH-ADDED"

### ISSUE THREAD

**Issue by nzall** [Hekili/hekili#15]
Addon version: 8.0.0-a3

character data from issue-reporting: 

build: @project-version@
level: 110
class: SHAMAN
spec: enhancement

talents: boulderfist
    crashing_storm
    earthen_spike
    feral_lunge
    landslide
    searing_assault
    spirit_wolf

traits: none

sets/legendaries/artifacts: none

gear:     saurscale_girdle=1
    saurscale_wristguards=1
    sea_sapphire_band=1
    beaten_copper_loop=1
    saurscale_boots=1
    scalebeast_claws=1
    drape_of_the_golden_city=1
    spaulders_of_the_champion=1
    heart_of_azeroth=1
    saurscale_chestguard=1
    saurscale_gloves=1
    saurscale_coif=1
    enchanted_devilsaur_claw=1
    saurscale_leggings=1
    lucky_braid=1

Received Lua error:

Message: ...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: Attempt to register unknown event "GLYPH_ADDED"
Time: Wed May 16 18:42:59 2018
Count: 1
Stack: ...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: Attempt to register unknown event "GLYPH_ADDED"
[C]: in function `RegisterEvent'
...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: in function `activate'
...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1389: in main chunk

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "GLYPH_ADDED"

This error happens after unzipping the addon folder and then logging into the game. No other addons installed, no customization of the addon.

**Comment by Hekili** [comment]
Thanks, should be fixed.  :)
