### ISSUE TITLE
[FEATURE] Holy Priest DPS Rotation

### ISSUE THREAD

**Issue by Eltinator92** [Hekili/hekili#1501]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hey, I know the Holy Priest DPS rotation is quite simple compared to anything else however it would be great to be able to rely on a DPS rotation in between healing the party or in cases where you want to output as much DPSas possible (e.g. boss zerg phases) and not sure what the right priority is at that time.

I would envision the DPS rotation would just sit on my screen and i would ignore its recommendations while I heal and when I am no longer required to heal i can rely on the DPS rotation to maximize my DSP for the Dungeon/Content I am doing.

This would also be great for new players that are still learning to 'heal' but dont yet know their dps rotation but still want to be able to contribute to DPS for their groups as much as possible.

**Comment by Hekili** [comment]
I know there's a general desire for healer DPS priorities to exist in the addon, but I don't have a good reason to add that to the maintenance burden of the addon at this time.

The addon is meant to present sim-tested priorities in-game so you can have some level of confidence that it's showing you something that has evidence of being optimal.  That doesn't really exist for healer specs, generally speaking.

It's something that might get done during downtime, but not as long as other work is underway.
