### ISSUE TITLE
Mage Frost Spec no longer works with Disciplinary Command leggo

### ISSUE THREAD

**Issue by tessel8** [Hekili/hekili#1503]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The rotation for Disciplinary Command worked as expected in the v9.2.0-1.0.17-alpha2 build, but appears to have broken in the alpha3 build up to the current v9.2.0-1.0.17b build. The suggestions begin promoting arcane explosion over almost anything else once disciplinary command is activated. It doesn't look like the code is recognizing that the effect has been triggered, or that it is in its cooldown phase after the effect has expired and keeps trying to trigger it with arcane explosion.

### How to Reproduce

1. Enter game as Frost Mage.
2. Talents I used: Bone Chilling, Shimmer, Rune of Power, Frozen Touch, Ice Ward, Freezing Rain, Thermal Void
3. Unity and Disciplinary Command equipped.
4. Begin rotation on training dummy as suggested by hekili.
5. Problems should show up in the rotation almost immediately after Disciplinary Command activates.

### Snapshot (Link)

https://pastebin.com/QMj3PVzK

### Additional Information

The problems begin fairly early in the snapshot but i wasn't sure exactly how to tell. I think the problem probably shows up very earlier, at least by the 2nd arcane explosion.

**Comment by Hekili** [comment]
The snapshot must be taken at the time you see Arcane Explosion recommended.  It is not recommended in the snapshot you provided.

**Comment by badbrain79** [comment]
I have the same problem but not only with Arcane Explosion but also with Fire Blast. Arcane Explosion or Fire Blast is suggested whenever Disciplinary Command is active or on cooldown.

Snapshot with Fire Blast and Disciplinary Command Buff active: https://justpaste.it/40e1n
Snapshot with Arcane Explosion and Disciplinary Command Buff active: https://justpaste.it/83jt7

**Comment by Hekili** [comment]
Thanks, these snapshots will help.  I can see that Disciplinary Command buff is up but that the internal cooldown for it says that it's ready.  I'll investigate.

**Comment by Hekili** [comment]
This should be resolved in 1.0.18.

**Comment by badbrain79** [comment]
I'm not sure if this leads to another problem with Disciplinary Command. Hekili correctly suggests a Frost and Fire spell to activate Disciplinary Command but then doesn't suggest an Arcane spell to complete the activation and activate the buff. In the snapshot you should be able to see that the frost and fire spell has been cast and the fire spell to activate is about to expire but no arcane spell like arcane explosion or counterspell is suggested. https://justpaste.it/9esf7

**Comment by Hekili** [comment]
In your snapshot, it is perceiving that an Arcane spell has been cast in the past 10 seconds.

**Comment by badbrain79** [comment]
Well, that's not true. As you can see in the screenshot on the right side with the weakaura, a frost and fire spell was cast but no arcane spell and in my opinion an arcane spell should now be suggested on the left side because the fire spell for activation is about to expire.
https://i.imgur.com/F15Lfpz.jpeg

**Comment by badbrain79** [comment]
Made another snapshot of the same situation. Admittedly, that doesn't happen often. If you miss this one activation of Disciplinary Command, then he suggests Fire Blast again anyway and with the next Rune of Power you have an Arcane Spell again and the Frost Spell you have always activated as a Frost Mage anyway.
But what is striking is that he only suggests counterspell in the pre-pull and otherwise not at all and also no arcane explosion. I don't know why the snapshot says I cast an arcane spell, maybe he thinks the trinket is an arcane spell.
https://justpaste.it/25a6a

**Comment by Hekili** [comment]
Don't misunderstand me; I'm not arguing about the outcome you want.  I'm telling you what I'm seeing when I look at it.  Yes, it's entirely possible that there's an error in determining whether an Arcane spell has been cast.  I'm investigating.

**Comment by badbrain79** [comment]
No problem, you put a lot of work into the addon and respond very quickly, I think that's great.
As long as you have a weakaura and realize that you're missing an arcane spell, it shouldn't be a problem.

**Comment by Hekili** [comment]
Appreciated.  It'll be fixed soon.  Fortunately, I can track the internal auras that represent whether a fire/frost/arcane spell has been cast, instead of having to manually construct that information.  You were on the right track mentioning a trinket, the addon makes some assumptions about whether an ability will trigger DC if it's not explicitly spelled out.

**Comment by badbrain79** [comment]
I have these two trinkets on the Frost Mage, but they don't count as an Arcane Spell.
Maybe that helps in some way.
https://www.wowhead.com/item=188272/resonant-reservoir?bonus=6805
https://www.wowhead.com/item=188268/architects-ingenuity-core?bonus=6805

**Comment by badbrain79** [comment]
No idea if this is a general problem but in the quick sim you can see at 0:39:161 that you get the DC buff but 10 seconds before that no arcane spell was cast or am I blind?
https://www.raidbots.com/simbot/report/kDjxpp8TGXt6BjHJm4CvwU

**Comment by Hekili** [comment]
That might be a good sim report.  It's possible that the trinket buff is "casting" an Arcane spell in the sim when it expires, or something similar.  If that doesn't match in-game behavior, the SimC developers might wanna fix it.

I've made changes to Disciplinary Command and it's available in the alpha build I just published.  I'd be interested to know if it works closer to what you'd expect.

https://github.com/Hekili/hekili/releases/tag/v9.2.0-1.0.19-alpha1

**Comment by badbrain79** [comment]
Works great now, just as expected.
He now suggests Counterspell to activate the DC buff. And if I turn off Counterspell because I'd rather use it to interrupt in M+, then he suggests Arcane Explosion.
I think that's done and the ticket can be closed.
Great work
