### ISSUE TITLE
Addon Text does not match Keybind

### ISSUE THREAD

**Issue by Heshaman** [Hekili/hekili#1504]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The key bind on Hekili does not match the key bind I am using for spells

### How to Reproduce

1. It happens all my characters :(
2. My friends don't seem to have this problem
3. I can email a screen shot or upload somewhere.

### Player Information (Link)

http://github.com/Hekili/hekili/issues

### Error Messages (Link)

na

### Additional Information

build: v9.2.0-1.0.17b
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ascendance
    hailstorm
    lashing_flames
    natures_guardian
    spirit_wolf
    stormflurry
    sundering

pvptalents: none

covenant: kyrian

conduits: elysian_dirge = 7
   embrace_of_earth = 4
   refreshing_waters = 3
   shake_the_foundations = 6
   totemic_surge = 4
   vital_accretion = 2

soulbinds: [pelagos]
   better_together = 1
   cleansed_vestments = 1
   combat_meditation = 1
   focusing_mantra = 1
   let_go_of_the_past = 1

sets: none

gear: anthemic_bracers = 1
    anthemic_cuirass = 1
    anthemic_gauntlets = 1
    anthemic_legguards = 1
    crystallic_enigmatic_epaulettes = 1
    dark_praetorians_clasp = 1
    deadly_sinvyr_necklace = 1
    dimensional_enigmatic_footguards = 1
    drape_of_twisted_loyalties = 1
    extract_of_prodigious_sands = 1
    haven_guards_cudgel = 1
    helm_of_solemn_vigil = 1
    ritual_commanders_ring = 1
    salvaged_viperid_band = 1
    symbol_of_the_raptora = 1

legendaries: none

itemIDs: 173147, 178781, 180110, 180123, 188019, 188021, 188023, 188026, 188045, 188047, 189775, 190602, 190726, 190742, 190991

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    filler_shock = true
    pad_lava_lash = true
    pad_windstrike = true

toggles:     cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    ascendance           = 4   [03]
    astral_recall        = A   [10]
    astral_shift         = SM3 [03]
    bloodlust            = 7   [01]
    capacitor_totem      = SM4 [01]
    chain_lightning      = R   [02]
    crash_lightning      = Q   [01]
    earth_elemental      = SM5 [01]
    feral_spirit         = A   [02]
    flame_shock          = W   [02]
    flametongue_weapon   = 5   [10]
    frost_shock          = R   [01]
    ghost_wolf           = X   [05]
    healing_stream_totem = M4  [02]
    hex                  = SM5 [02]
    lava_lash            = A   [01]
    lightning_bolt       = W   [01]
    lightning_shield     = Q   [10]
    purge                = 3   [03]
    spirit_walk          = 1   [03]
    stormstrike          = Q   [02]
    sundering            = C   [01]
    vesper_totem         = M4  [01]
    water_walking        = W   [10]
    wind_shear           = 2   [03]
    windfury_totem       = M5  [01]
    windstrike           = Q   [02]

### Contact Information

rfranks1963@gmail.com

**Comment by Hekili** [comment]
You can manually set keybinds for abilities in /hekili > Abilities.  You likely have your action bars set up in a weird order.  If you look at your player information (which should've been on Pastebin), you can see:

```
ascendance = 4 [03]
astral_recall = A [10]
astral_shift = SM3 [03]
bloodlust = 7 [01]
capacitor_totem = SM4 [01]
chain_lightning = R [02]
crash_lightning = Q [01]
earth_elemental = SM5 [01]
feral_spirit = A [02]
flame_shock = W [02]
flametongue_weapon = 5 [10]
frost_shock = R [01]
ghost_wolf = X [05]
healing_stream_totem = M4 [02]
hex = SM5 [02]
lava_lash = A [01]
lightning_bolt = W [01]
lightning_shield = Q [10]
purge = 3 [03]
spirit_walk = 1 [03]
stormstrike = Q [02]
sundering = C [01]
vesper_totem = M4 [01]
water_walking = W [10]
wind_shear = 2 [03]
windfury_totem = M5 [01]
windstrike = Q [02]
```

That's `ability` = `detected_keybind` [`actionbar/page`].

If you're doing other weird things with action bars and their pages that don't correspond to the normal bar layout, the addon won't be able to sort that out.  That's what the Override Keybind Text feature helps you resolve.

**Comment by Heshaman** [comment]
Interesting. I WAS using an add-on called Move and Improve to manage the Bars. It is using a very different method of naming the bars/pages. 

The Overide key bind would have been to complicated. I had to type my whole rotation. Instead I reset WOW and repair to get Hekili to work properly.

I appreciate the help!
