### ISSUE TITLE
[REC] Druid/Balance - change rotation and priority

### ISSUE THREAD

**Issue by itsbarryboys** [Hekili/hekili#1505]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello
Since the new tier sets change the rotation of the balance druid, I then wondered if it was possible to change the recommendation. The reason for this is with the new sets bonus, simc recommends going into Lunar Eclipse as many times as possible due to its small Fury of Elune proc - where Hekili tries to go in Solar since without the sets bonus it used to be balance's best single target rotation. 
We can also stay in CA due to our legendary, so the Lunar or solar doesn't matter too much, but in the long run, we miss a few procs and cost us Astral power generations. 

### How to Reproduce

After coming out of Celestial Alignment with around 0 Astral power or at least a small amount, it is there I have seen the issue.

### Snapshot (Link)

https://pastebin.com/ZFnnStrv

### Contact Information

Barry#3270

**Comment by Hekili** [comment]
> simc recommends going into Lunar Eclipse as many times as possible due to its small Fury of Elune proc - where Hekili tries to go in Solar since without the sets bonus it used to be balance's best single target rotation.

The addon uses SimC's priority and accounts for set bonuses, legendaries, talents, etc. by default.  There are a number of mistaken assumptions, but that doesn't mean there's not an error or issue to resolve.

First, could you sim your character on Raidbots and provide a link, so we can compare apples to apples?  That will let me compare what the sim is doing when you're coming out of Celestial Alignment with low Astral Power to what the addon is requesting.  However, the snapshot you took doesn't have low Astral Power (it's at 75 when it starts), but either way, we can compare and see which entry the addon is recommending and whether that matches SimC.

Looking at the Starfire entry that was recommended, its criteria *are* met and there's no higher priority Wrath cast that would've been recommended in the priority to take us into Lunar instead.

![image](https://user-images.githubusercontent.com/9438134/168406632-c688e2a3-f40d-48d2-89a9-15de4233bb8d.png)

When you supply your sim, I can take a look and inspect further if the sim is doing what you described.

**Comment by itsbarryboys** [comment]
Sorry,
I already thought I posted the simc:

**Comment by itsbarryboys** [comment]
https://www.raidbots.com/simbot/report/irEgQmgqnWA8asGFXQ5HGu

**Comment by Hekili** [comment]
Reviewing your sim, it doesn't look like it goes into Lunar at every opportunity.

![image](https://user-images.githubusercontent.com/9438134/168457714-011f9d7b-bcec-41a0-9218-4ec5ebe91a61.png)

![image](https://user-images.githubusercontent.com/9438134/168457730-18a0dde4-c43a-466c-a5ac-cc4eba956864.png)

![image](https://user-images.githubusercontent.com/9438134/168457735-31d16b91-2c09-41af-b056-8bd44db039a5.png)
