### ISSUE TITLE
[REC] Ossuary passive/Marrowrend too high of a priority during DRW

### ISSUE THREAD

**Issue by ravisangha** [Hekili/hekili#1506]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello, I've noticed that marrowrend is recommended after popping DRW in pulls since you quickly lose a stack of bone shield, dropping to 4 and losing the ossuary buff. My recommendation is that with 4 piece, and with crimson rune weapon leggo, it is better defensively and GCD efficient (since one marrowrend with DRW is 9 stacks of bone shield) for you to simply put those 2 runes meant for marrowrend into more heartstrikes extending your rune  weapon and only marrowrend if DRW if about to fall off and you have less than 7 stacks of boneshield OR anytime while DRW is up and you have only one stack of boneshield.  

I only write this since this is what Naow and Nerftank (two great tank players) state is the optimal usage is marrowrend is during DRW. If there is a way for me to make it so I can personally make the changes on my personal heliki profile, that would be great too if you do not want make this the default usage of marrowrend. Any help would be greatly appreciated. Thanks and have a nice day : )

### How to Reproduce

1. Pop DRW and enter combat
2. Lose one stack of Boneshield
3. The addon will then recommend Marrowrend despite it being inefficient both rune wise and defensively worse than heart striking with 4pc and crimson rune weapon leggo

### Snapshot (Link)

https://pastebin.com/AnHNzyR1

**Comment by Hekili** [comment]
Thanks, this is a good call-out.

In order to maintain uptime, Marrowrend had been shifted up in the priority list, which left one specific entry in place before the priority would fork depending on whether DRW was up or not.  That will be fixed in the next release (later today).

**Comment by ravisangha** [comment]
Great, thanks alot :D

**Comment by Hekili** [comment]
This should be resolved in 1.0.18.
