### ISSUE TITLE
[BUG] Ret Pally Final Verdict / Templar's Verdict Spell Flash Size not changing

### ISSUE THREAD

**Issue by Toresh** [Hekili/hekili#1507]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Ret Pally Final Verdict / Templar's Verdict Spell Flash Size not changing.

Normal size
https://i.gyazo.com/829ba8b84a6dca7259e032b5d68fa5e5.jpg

Wrong size
https://i.gyazo.com/2dd70171d51f632036fbdf3299884b40.jpg

Current Setting Spell Flash setting:
https://i.gyazo.com/bbf3f541b6648e10be2bac35f18e80af.png

### How to Reproduce

N/A

### Player Information (Link)

https://pastebin.com/QmU6yaDt

### Error Messages (Link)

N/A

### Additional Information

SnapShot:
https://pastebin.com/0E2JrRrT

**Comment by Hekili** [comment]
Do you have SpellFlash installed separately, or are you using the addon's built-in version?

**Comment by Toresh** [comment]
Only using the built-in version with Hekili.

Thanks
