### ISSUE TITLE
[BUG] attempt to concatenate local 'aFlash' (a table value)

### ISSUE THREAD

**Issue by Zetaprime82** [Hekili/hekili#1508]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

1x Hekili\UI.lua:1351: attempt to concatenate local 'aFlash' (a table value)
[string "@Hekili\UI.lua"]:1351: in function <Hekili\UI.lua:903>

Locals:
self = HekiliDisplayPrimary {
 0 = <userdata>
 UpdateAlpha = <function> defined @Hekili\UI.lua:1563
 index = 3
 Active = true
 lastFlash = "templars_verdict"
 Deactivate = <function> defined @Hekili\UI.lua:1793
 combatTime = <table> {
 }
 updateCount = 129898
 RefreshCooldowns = <function> defined @Hekili\UI.lua:1589
 flashColor = <table> {
 }
 updateTime = 0.300025
 Recommendations = <table> {
 }
 refreshTimer = 0.114000
 postRange = 0.216700
 auraTimer = 0
 flashTimer = 153678
 postDelay = 0.121400
 UpdatePerformance = <function> defined @Hekili\UI.lua:1848
 firstThreadCompleted = true
 numIcons = 3
 TextureUpdateNeeded = true
 alpha = 1
 refreshRate = 0.500000
 updateMax = 8.891600
 flashWarnings = <table> {
 }
 firstForce = 152141.639000
 UpdateKeybindings = <function> defined @Hekili\UI.lua:873
 eventMax = 0.212600
 combatUpdates = <table> {
 }
 GetPerimeterButtons = <function> defined @Hekili\UI.lua:1805
 criticalUpdate = true
 Initialized = true
 activeThreadTime = 5.222800
 Buttons = <table> {
 }
 postPrimary = 8.750900
 eventCount = 2830
 failEvents = <table> {
 }
 eventMaxType = "SPELL_ACTIVATION_OVERLAY_GLOW_SHOW"
 successEvents = <table> {
 }
 postTargets = 1.037700
 NewRecommendations = false
 Activate = <function> defined @Hekili\UI.lua:1736
 lastUpdate = 153677856.424400
 activeThreadStart = 153677851.183700
 postGlow = 0.037900
 RecommendationsStr = "templars_verdict"
 postRecs = 0.395800
 HasRecommendations = true
 glowTimer = -1.017000
 flashReady = true
 lastFlashFrames = <table> {
 }
 OnUpdate = <function> defined @Hekili\UI.lua:903
 postAlpha = 0.058600
 activeThreadFrames = 1
 eventTime = 0.017445
 targetTimer = 0.052000
 delayTimer = -1
 alphaCheck = 0.500000
 id = "Primary"
 IsThreadLocked = <function> defined @Hekili\UI.lua:895
 threadUpdates = <table> {
 }
 OnEvent = <function> defined @Hekili\UI.lua:1632
 eventsTriggered = <table> {
 }
 recTimer = 0.100000
 SetThreadLocked = <function> defined @Hekili\UI.lua:899
 combatRate = 0.100000
 postFlash = 0.314800
 superUpdate = true
 rangeTimer = 0.200000
 threadLocked = false
}
elapsed = 0.017000
init = 153677965.074700
profile = <table> {
 displays = <table> {
 }
 Clash = 0
 fixedBrightness = false
 autoSnapshot = true
 fixedSize = true
 iconStore = <table> {
 }
 trinkets = <table> {
 }
 enabled = true
 minimapIcon = false
 screenshot = true
 toggles = <table> {
 }
 flashTexture = "Cooldown\star4"
 clashes = <table> {
 }
 runOnce = <table> {
 }
 notifications = <table> {
 }
 specs = <table> {
 }
 packs = <table> {
 }
 interrupts = <table> {
 }
}
conf = <table> {
 glow = <table> {
 }
 indicators = <table> {
 }
 builtIn = true
 order = 1
 primaryWidth = 50
 flash = <table> {
 }
 anchorPoint = "BOTTOM"
 frameLevel = 10
 relativeTo = "SCREEN"
 numIcons = 3
 border = <table> {
 }
 range = <table> {
 }
 enabled = true
 zoom = 30
 keepAspectRatio = true
 elvuiCooldown = false
 captions = <table> {
 }
 targets = <table> {
 }
 frameStrata = "LOW"
 queue = <table> {
 }
 y = -225
 x = 0
 name = "Primary"
 primaryHeight = 50
 keybindings = <table> {
 }
 delays = <table> {
 }
 visibility = <table> {
 }
 displayPoint = "TOP"
}
postAlpha = 153677965.075800
now = 153677.963000
postRecs = 153677965.148700
postPrimary = 153677965.150300
postGlow = 153677965.151800
postRange = 153677965.211600
a = "templars_verdict"
changed = false
ability = <table> {
 gcd = "spell"
 startsCombat = true
 flash = <table> {
 }
 copy = <table> {
 }
 key = "templars_verdict"
 texture = 461860
 charges = 1
 recharge = 0
 id = 85256
 desc = ""
 funcs = <table> {
 }
 name = "Templar's Verdict"
 realUnit = "Creature-0-1469-2481-31243-183033-00008257E3"
 realCast = 153387.239000
 handler = <function> defined @Hekili\Classes\PaladinRetribution.lua:1261
 cooldown = 0
 spendType = "holy_power"
}
aFlash = <table> {
 1 = 85256
 2 = 336872
}
(*temporary) = <function> defined @Ad

### How to Reproduce

Retri pally Final Verdict

### Player Information (Link)

https://pastebin.com/2C2BdQB6

### Error Messages (Link)

https://pastebin.com/2C2BdQB6

**Comment by Hekili** [comment]
Thanks; this may help explain another spellflash ticket.  I'm testing a solution.

**Comment by Zetaprime82** [comment]
Thats realy nice :D

**Comment by Hekili** [comment]
This should be resolved (I just took forever to close it).
