### ISSUE TITLE
Necro Frostmage reccomending to shatter with IL instead of FB

### ISSUE THREAD

**Issue by Tiltmage** [Hekili/hekili#1509]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

From what I can tell frost necro prio w/ slick ice is to just spam fb while skeletal mage is up , flurry w/ proc and contiue to spam fb ignoring fingers of frost unless you have to move. Hek is currently reccomending to il when fingers of frost proc while skeletal mage is active. 

### How to Reproduce

Be necro frost mage w/ Slick Ice legendary
pop deathborne and IV 
cast frostbolt until flurry and fof procs happen
can see it shows IL when should be spamming fb

### Snapshot (Link)

https://pastebin.com/U752vi3X

### Contact Information

Tilt#0666

**Comment by Hekili** [comment]
If this is still an issue, please link a sim to compare behavior and reopen the ticket.
