### ISSUE TITLE
Not displaying 8.2.0-01

### ISSUE THREAD

**Issue by Jomty** [Hekili/hekili#151]
Hi,

Installed lastest version, straight away nothing displaying in our out of combat. Tried all characters that use it. 

All options seem to function but the display itself won't show any suggestions. You can move the anchor points which do show, but after that nothing else displays.

Error messages:

1:
[18:48] Interface\AddOns\Hekili\Events.lua:94: Attempt to register unknown event "AZERITE_ESSENCE_UPDATE"
[18:48] [C]: in function `RegisterEvent'
Interface\AddOns\Hekili\Events.lua:94: in function `RegisterEvent'
Interface\AddOns\Hekili\Events.lua:631: in main chunk
[18:48] (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "AZERITE_ESSENCE_UPDATE"

2:
[18:51] Interface\AddOns\Hekili\Core.lua:200: attempt to call field 'ReadKeybindings' (a nil value)
[18:51] Interface\AddOns\Hekili\Core.lua:200: in function <Interface\AddOns\Hekili\Core.lua:195>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:489: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1194: in function <Interface\FrameXML\UIParent.lua:1090>

3:
[18:52] Interface\AddOns\Hekili\Events.lua:587: attempt to call field 'updateEssences' (a nil value)
[18:52] Interface\AddOns\Hekili\Events.lua:587: in function `updateGear'
Interface\AddOns\Hekili\Core.lua:161: in function <Interface\AddOns\Hekili\Core.lua:58>
[C]: ?
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:498: in function `InitializeAddon'
...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0-12.lua:613: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:605>

Hope thats everything you need...

Cheers,

**Comment by Hekili** [comment]
Are you trying to use an 8.2 version in a place that is still 8.1.5?

**Comment by Jomty** [comment]
Shit... Yeah, updated automatically... 

Whats the best way to revert to previous version?

**Comment by Hekili** [comment]
Download the previous version from the Curse site.

**Comment by Jomty** [comment]
Yeah, just sorted it. Sorry for being a doofus. Great work with the addon, much appreciated! x

**Comment by Hekili** [comment]
You're not the only one to run into this.  I'll make a note of it.
