### ISSUE TITLE
[REC]Nightfae Frost Mage Disciplinary Command recommending CS right before Rune of Power

### ISSUE THREAD

**Issue by im-naomi** [Hekili/hekili#1510]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

There's no reason for it to recommend CS when rune of power counts as arcane, and it also recommends it before icy veins, which places a rune of power and counts as both frost and fire spells for the legendary.

### How to Reproduce

Default priority, equip Diciplinary command 

### Snapshot (Link)

https://pastebin.com/R9hTxbdM

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/R7gosmH4Rtw7TmDfJunN2

### Contact Information

NAOMI#0001

**Comment by Hekili** [comment]
Have you done any comparison sims to see if it's worthwhile to prevent this behavior?
