### ISSUE TITLE
[BUG] Hekili does not appear to be installed on certain characters

### ISSUE THREAD

**Issue by JacobERobison** [Hekili/hekili#1511]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have Hekili installed (and tried uninstalling and reinstalling through Curseforge) 

Recently, Hekili hasn't been displaying for my Demon Hunter but it displays for my Paladin. 

I can open the /hekili panel from my Paladin but not from my Demon Hunter. 

It's almost like, when on my DH, Hekili doesn't realize it's installed. 

Looked through the menus on my Paladin and didn't see anything that might resolve this issue. 

Thank you, in advance!

### How to Reproduce

Log into my Havoc Demon Hunter
Hekili is not recognized

Log into my Prot Paladin
Hekili is available

### Player Information (Link)

/hekili not opening on certain characters

### Error Messages (Link)

Says I have no bugs

### Contact Information

JacobERobison#5775

**Comment by Hekili** [comment]
I am not able to investigate this with the information provided.

Confirm that the addon is loaded and enabled for each of your characters/classes -- you can sometimes have an addon turned on for one class/spec and not another.  Thanks!
