### ISSUE TITLE
Arcane Mage (Almost perfect) - It's recommending 5 Arcane Blasts in Opener instead of 4

### ISSUE THREAD

**Issue by Dreamin93** [Hekili/hekili#1512]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili is recommending I use 5 Arcane Blasts in the Opener + burst phases instead of 4.

With only 1 legendary this would be correct, but if you are using Kyrian + Arcane harmony legendary this changes to 4 Arcane blasts, followed by a Arcane Barrage.

https://www.wowhead.com/arcane-mage-rotation-guide
(Under the Kyrian Arcane Mage opener rotation section)

It seems that the sims are casting 5 instead of 4 (When I did a /simc and simmed myself on raidbots it was also using 5). But if you check any of the logs from top Arcane players - they all do the rotation according to the guide.

Here is an example
https://wowanalyzer.com/report/2KjJ6rvhN9TZBGXd/10-Mythic+Skolex,+the+Insatiable+Ravener+-+Kill+(3:59)/Phosphoros/standard/timeline

### How to Reproduce

1. Enter game as Arcane Mage
2. Use recommended raid talents: 1,3,3,2,1,2,1
3. Target enemy (target dummy)
4. Start rotation
5. At the burst phase it will ask you to press Arcane Blast 5 times instead of 4

### Snapshot (Link)

https://pastebin.com/FTTW0cRK

### Contact Information

Jordan#4168

**Comment by Hekili** [comment]
> It seems that the sims are casting 5 instead of 4 (When I did a /simc and simmed myself on raidbots it was also using 5). But if you check any of the logs from top Arcane players - they all do the rotation according to the guide.

If/when sims are updated to behave differently, the addon will also be updated to match.  Thanks!
