### ISSUE TITLE
[FEATURE] Exclude Gavel of the First Arbiter Soul Fragments from enemy target counts

### ISSUE THREAD

**Issue by Thordros** [Hekili/hekili#1514]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

The [Soul Fragments](https://www.wowhead.com/npc=186150) spawned from [Gavel of the First Arbiter's](https://www.wowhead.com/item=189862) on-use are immune to all AOE and cleave abilities, and should not be included in enemy target counts. Treating them the same way that Explosive affix orbs are handled would probably do the trick.

### Contact Information

Thordros#1784

**Comment by Hekili** [comment]
This will be in the next release.
