### ISSUE TITLE
[REC] Feral Druid Priority Issue with Shred & Swipe(cat)

### ISSUE THREAD

**Issue by Oni-Wan** [Hekili/hekili#1518]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I noticed on my Feral Druid that Hekili prefers to use Swipe(Cat) in a pure Single Target Situation to build CP instead of Shred. (Shred does clearly do more damage in ST). Same Issue: I noticed some times in a MT Situation where it prefers Shred over Swipe, but not quite as often. Important to reproduce is to blow all your CDs.

### How to Reproduce

1. Be a decent geared Feral Druid (277 in my case)
2. Be Nightfae and have 2/3/1/3/1/3/2 (so have Swipe for MT Situation instead of Brutal Slash)
3. Get a victim or a Dummy
4. Blow all your CDs/Trinkets/Convoke, it is important to "Do" your normal Rotation.
5. Done!

### Snapshot (Link)

https://pastebin.com/zF8DGiva

**Comment by Hekili** [comment]
The priority is explicitly written to do this, because Swipe is better damage-per-energy than Shred under most circumstances.  It's a WoW design issue, not a priority issue.

**Comment by Oni-Wan** [comment]
This may be sometimes the case, but I think on the long run (or should i say in short fights) shred is more usefull than swipe.
Unfortunately does this not explain why I'am getting Shreds in some Multi-Targets fight beside my CDs. It is not happen very often and I don't know how to reproduce outside of a raid/m+

**Comment by Hekili** [comment]
> This may be sometimes the case, but I think on the long run (or should i say in short fights) shred is more usefull than swipe.

Sim yourself and look at what your sim does.  You can edit your sim profile to make it Shred instead of Swipe and see if it is more performant.

> Unfortunately does this not explain why I'am getting Shreds in some Multi-Targets fight beside my CDs. It is not happen very often and I don't know how to reproduce outside of a raid/m+

When your Shred is free (Clearcasting), damage-per-energy isn't a factor and so Shred is prioritized.  This can be seen in the priority itself.  These are the impacted lines:

```
actions.filler+=/swipe_cat,if=spell_targets.swipe_cat=1&!buff.clearcasting.up
actions.filler+=/shred,if=buff.sudden_ambush.down
```

**edit:**  Shred is also used for proccing Bloodtalons.
