### ISSUE TITLE
[REC] Elemental Shaman - Flame Shock reapplication is suggested too early when Storm Elemental is talented and active

### ISSUE THREAD

**Issue by Elutriate** [Hekili/hekili#1519]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [x] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When Storm Elemental is talented and active, Flame Shock only lasts 18 seconds (lasts ~40 seconds when Fire Elemental is active). Hekili appears to suggest reapplication of Flame Shock based on the ~12 second pandemic window that would be correct if a Fire Elemental were active, as opposed to the ~6 second pandemic window that should be correct with Storm Ele active. (ie. it suggests reapplying Flame Shock at around 11 seconds left, when the pandemic window with Storm Ele talented starts at 6 seconds.)

In other words, When Storm Ele is active, I would expect the pandemic window of Flame Shock to start at 6 seconds, but the addon appears to be think that the pandemic window starts at 12 seconds, which is what I would expect to be true if a Fire Elemental were active because of the extended duration of Flame Shock

### How to Reproduce

1. Enter the game as an Elemental Shaman
2. Take the Primal Elementalist (Might be optional, I have not tested without this talent) and the Storm Elemental talents.
3. Enter combat with a single enemy
4. Cast Storm Elemental
5. Apply Flame Shock to your target
6. Perform your rotation as is suggested by Hekili
7. When the Flame Shock debuff has around 12 seconds remaining , Hekili suggests that you reapply Flame Shock.

Please let me know if I did not describe this issue clearly enough.

### Snapshot (Link)

https://pastebin.com/wbTunJFA

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jzAH2CvJU8jRvadU8fjNAZ

### Contact Information

Feel free to email me, but for more expeditious response: Discord: Elutriate#2660

**Comment by elsavira** [comment]
Can confirm this one, was in the process of gathering this data too.

**Comment by Hekili** [comment]
Give the alpha version a try and see if it is resolved.  Thanks.

**Comment by Elutriate** [comment]
> 

How do I use the alpha version? Is that an option within the addon or is it a separate addon? Having difficulty finding it.

**Comment by Hekili** [comment]
edit: https://github.com/Hekili/hekili/releases/tag/v9.2.5-1.0.1-alpha1

**Comment by Elutriate** [comment]
Thank you. This issue is fixed in the Alpha version :)
