### ISSUE TITLE
Demon Hunter abilities disappeared after update

### ISSUE THREAD

**Issue by thamjam** [Hekili/hekili#152]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
Updated to 8.2.0 and all the abilities for the demon hunter disappeared. When i go to the abilities tab it shows nothing under Havoc nor Vengeance

**Comment by sofiaringstrom** [comment]
Can confirm something is wrong on demon hunter, getting the following lua-error on current and old version:
`Message: Interface\AddOns\Hekili\Events.lua:94: Attempt to register unknown event "AZERITE_ESSENCE_UPDATE"
Time: Tue Jun 25 23:28:10 2019
Count: 1
Stack: Interface\AddOns\Hekili\Events.lua:94: Attempt to register unknown event "AZERITE_ESSENCE_UPDATE"
[C]: in function `RegisterEvent'
Interface\AddOns\Hekili\Events.lua:94: in function `RegisterEvent'
Interface\AddOns\Hekili\Events.lua:631: in main chunk

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "AZERITE_ESSENCE_UPDATE"
`

**Comment by Hekili** [comment]
Don't update to v8.2.0-01 until 8.2 launches in your region.
