### ISSUE TITLE
[REC] Elemental Shaman - Hekili Does not Account for Elemental 2 Piece Guaranteed Lava Surge Procs

### ISSUE THREAD

**Issue by Elutriate** [Hekili/hekili#1520]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

This issue is only relevant when using the Windspeaker's Lava Resurgence (WLR) Legendary and when 2 piece is equipped. The elemental 2 piece tier set bonus guarantees a Lava Surge proc every 8 seconds while a Fire (or Storm) Elemental is active. With WLR, our Earth Shocks will also guarantee a Lava Surge proc. It is very common to encounter a scenario where, at a single point in time you have:

A) enough Maelstrom to cast Earth Shock, and it seems desirable to do so to avoid overcapping on Maelstrom. 
and
B) A Lava Surge proc from the 2 piece set bonus will be happening shortly.

In this scenario, you are forced to choose between:

A) casting Earth Shock and hoping there is enough time to dump the Lava Surge proc that occurs before the 2 piece Lava Surge Proc happens OR
B) Holding off on casting the Earth Shock and casting alternate spells until your 2 piece Lava Surge proc happens, then cast the 2 piece Lava Surge, cast Earth Shock and cast the resulting Lava Surge.

Both options have drawbacks. Option A will often result in your 2piece Lava Surge occurring while you already have the Lava Surge buff from casting Earth Shock, thus wasting a Lava Surge proc. Option B will typically result in an overcap of Maelstrom. 

As the addon is coded right now, it doesn't account for the guaranteed 2 Piece Lava Surge Proc and will suggest Earth Shock when a 2 piece Lava Surge is imminent. I don't believe that this is optimal. If forced to choose between the 2 options, I believe that overcapping on Maelstrom is the better option and that Hekili should account for the imminent 2 piece procs, taking into consideration your haste to determine whether or not there is enough time to cast the Earth Shock, Lava Burst sequence before the 2 piece procs. 

The problem is easy enough to manage in my head, but there are definitely times where I am forced to make a judgement call on whether or not to try to squeeze an Earth Shock in and end up losing out on a Lava Surge proc because of a bad decision, or end up holding on to an Earth Shock that I had time to cast.

### How to Reproduce

1. Enter the game as an Elemental Shaman
2. Ensure you have at least 2 pieces of the current tier set equipped
3. Ensure you have the Windspeaker's Lava Resurgence legendary equipped.
4. Enter combat with a single target
5. Cast Fire (or Storm) Elemental
6. perform your rotation until you have at least 60 maelstrom
7. Your Fire/Storm Ele being active will cause Lava Surge to proc automatically every 8 seconds. There are Weakauras that can track this proc for you so you know when exactly you will get this proc. (if you need a Weakaura I can link the one that I use)
8. I have found that if I cast Earth shock with less than 1.5 seconds before the 2 piece set bonus Lava Surge Proc occurs, I don't have enough time to spend the Lava Surge proc before the 2 piece procs (depending on haste. During Bloodlust or other significant haste buffs this is not true). If the 2 piece procs while you already have a Lava Surge buff, it doesn't do anything and you miss out on the Lava Surge proc that the 2 piece would have given you.

### Snapshot (Link)

https://pastebin.com/PjPjKNnw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/7jPg4WrB1rjd92HBirhfWy

### Additional Information

I am running the 9.2.5a Version of the addon. But this issue existed on the normal version before I started using the alpha version as well.

### Contact Information

Elutriate#2660

**Comment by Hekili** [comment]
> As the addon is coded right now, it doesn't account for the guaranteed 2 Piece Lava Surge Proc and will suggest Earth Shock when a 2 piece Lava Surge is imminent. I don't believe that this is optimal. If forced to choose between the 2 options, I believe that overcapping on Maelstrom is the better option and that Hekili should account for the imminent 2 piece procs, taking into consideration your haste to determine whether or not there is enough time to cast the Earth Shock, Lava Burst sequence before the 2 piece procs.

You would need to provide sims that demonstrate that Maelstrom waste is better than Lava Surge waste.

The tier procs are modeled by the addon, though.

**Comment by Elutriate** [comment]
> The tier procs are modeled by the addon, though.

Can you explain what you mean by this? Are you referring to the Hekili addon or a Sim addon? And what do you mean that the tier procs are modeled? 

Regardless, I will learn how to run said sims. Thanks!

**Comment by Hekili** [comment]
> Can you explain what you mean by this? Are you referring to the Hekili addon or a Sim addon? And what do you mean that the tier procs are modeled?

When the addon engine generates recommendations, it looks at the present moment forward, and "knows" that predictable Lava Surge procs occur every 8 seconds.

> Regardless, I will learn how to run said sims. Thanks!

What you're looking to determine is if spending a Lava Surge proc before a new one will proc is more valuable than spending Maelstrom via Earth Shock at that key moment.  That's something that may be true, and sounds fairly intuitive, but evidence has to be supplied to support this sort of change.

It may be challenging to test, because I'm not sure if SimulationCraft has expressions available that will help you determine that a tier set Lava Surge is coming.  You might ask Elemental theorycrafters about your idea.

**Comment by Elutriate** [comment]
> It may be challenging to test, because I'm not sure if SimulationCraft has expressions available that will help you determine that a tier set Lava Surge is coming. You might ask Elemental theorycrafters about your idea.

The Ele Discord seems to agree with this theory. Favoring Lava Surge procs over Earth Shock casts with this legendary is not new to this tier, it is just a much more common scenario due to the predictability and frequency of Lava Surge procs that comes with the tier set bonus. With the fact that this is not a new choice we have to make, I am surprised to find that this is not already represented in the default Ele APL.

I believe I've identified a method for simc to account for incoming 2 piece Lava Surge procs and will share my findings here when I have them.

**Comment by Elutriate** [comment]
I believe I have gathered proof that what I'm suggesting is better. [Here](https://pastebin.com/xRtQ5D5J) is the altered APL I used: 

The only change that I made to the [original](https://pastebin.com/3KEBrAnA) is I added the following action on the single target list of actions, beneath a bunch of Lava Burst casts that I saw (There is storm ele stuff in it because I stole it from the storm ele section.)

actions.single_target+=/earth_shock,if=spell_targets.chain_lightning<2&buff.fireheart.tick_time_remains<gcd&maelstrom>=60&(buff.wind_gust.stack<20|maelstrom>90)|(runeforge.echoes_of_great_sundering.equipped&!buff.echoes_of_great_sundering.up)|runeforge.windspeakers_lava_resurgence.equipped

The important part being "&buff.fireheart.tick_time_remains<gcd"
Fireheart is the buff that ele receives when our fire/storm ele is out and we have 2 piece. It is what grants us a lava surge proc every 8 seconds. That piece of code states that the tick (application of lava surge) from fireheart must not be within the next GCD (because you want a GCD's worth of time between when you cast earth shock and when you will get your fireheart lava surge, so that you can spend the lava surge proc that you got from earth shock before the firehaert tick)

Due to the varying nature of sim results, I took 10 sims from the default APL and 10 with my edited APL. Below are the best and worst of each.


[Worst Custom APL.txt](https://github.com/Hekili/hekili/files/8882875/Worst.Custom.APL.txt)
[Best Default APL.txt](https://github.com/Hekili/hekili/files/8882876/Best.Default.APL.txt)
[Worst Default APL.txt](https://github.com/Hekili/hekili/files/8882877/Worst.Default.APL.txt)
[Best Custom APL.txt](https://github.com/Hekili/hekili/files/8882878/Best.Custom.APL.txt)

I really don't know what I am doing when it comes to custom APL's. There's potential I didn't do this right, and there's potential (and likelihood) that, if I did do it right, there are better ways to customize the APL for more optimal performance.

**Comment by Elutriate** [comment]
I believe I have the proof that I need. I can provide .txt files of the sims that I ran with my custom APL , or feel free to run my custom APL against the default Shaman APL. 
Here is my custom APL
https://pastebin.com/DSJe405Y

The only change that I made is I replaced the Earth Shock line with:

actions.single_target+=/earth_shock,if=buff.fireheart.tick_time_remains>gcd&maelstrom>=60&runeforge.windspeakers_lava_resurgence.equipped

The Fireheart buff is what grants Lava Surge procs every 8 seconds when fire/storm ele is active.

**Comment by Hekili** [comment]
> I believe I have the proof that I need. I can provide .txt files of the sims that I ran with my custom APL , or feel free to run my custom APL against the default Shaman APL.

This is what Raidbots is for.  :)

Your version:

https://www.raidbots.com/simbot/report/bVRwwc2ZUfFaTqaMfQenA3

![image](https://user-images.githubusercontent.com/9438134/173198330-f59ea2e8-ecac-4b2a-800a-01e336e56b4e.png)

Looks like a marginal average improvement with possible higher top-end, but 0.1% is very close to "caring about this is less productive than not caring about this" territory.

I edited it further (no reason to skip Earth Shock when Fireheart isn't active, though Fireheart *is* basically always active).

`actions.single_target+=/earth_shock,if=(buff.fireheart.down|buff.fireheart.tick_time_remains>gcd)&maelstrom>=60&runeforge.windspeakers_lava_resurgence.equipped`

https://www.raidbots.com/simbot/report/3xVotXcbo7yPZBSUEwsdke

![image](https://user-images.githubusercontent.com/9438134/173198343-2b12f5ae-eabd-4591-906e-efc3b08e2bfa.png)

Same basic deal, marginal increase but now lower top-end.  Have you explored this with Elemental Shaman theorycrafters?  They likely did their own sim testing on this front.

**Comment by Elutriate** [comment]
I have messaged them and was told they would look into it.

**Comment by Elutriate** [comment]
> This is what Raidbots is for. :)

Also, sorry I could not figure out how to use custom APL within raidbots :(

**Comment by Hekili** [comment]
I'll make changes if/when SimulationCraft updates the priority to handle it.  Thanks.
