### ISSUE TITLE
[REC] Elemental Shaman Hekili Sometimes incorrectly recommends Casting Earthquake

### ISSUE THREAD

**Issue by Elutriate** [Hekili/hekili#1521]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When utilizing the Echoes of the Great Sundering legendary, it is always optimal to alternate between Earth Shock and Earthquake casts for your spenders. Simply put, if you have the buff from the legendary, you cast Earthquake. If you do not have the buff from the legendary, you cast Earth Shock to get the buff from the legendary. 

For this issue, it is important to make the distinction between the spell that Hekili recommends you cast next and the few spells that it recommends in 2 and 3 spells from now. This issue only exists when you are utilizing said legendary, but do not have the buff from it, you are in combat with 2 or more targets, and only when it is recommending a spender in 2-3 spells from your next cast. In the above scenario, the addon will recommend that you cast Earthquake. As you continue to cast spells and the "spender slot" of the spells moves into the next spell you should cast slot, the addon corrects itself and correctly recommends that you cast Earth Shock. Additionally, this does not happen 100% of the time. Sometimes the addon recognizes that you don't have the buff and correctly predicts that in 3 casts, you will need to cast Earth Shock. When the addon incorrectly suggest an Earthquake cast in 2-3 spells, it always corrects itself by the time the spender spell reaches the "next spell" slot

### How to Reproduce

1. Enter the game as an Elemental Shaman
2. Ensure you are using the Echoes of the Great Sundering legendary
3. Enter combat with at least 2 targets
4. Ensure that your spell queue is clear of all of your CDs, such as any on use trinkets, racial on use abilities, Stormkeeper, fire/storm ele etc. so that you can see the addon begin to suggest a spender 2-3 spells in advance.
5. Generate 60+ Maelstrom
6. Cast Earth Shock
7. Generate 60+ Maelstrom
8. Cast Earthquake
9. Repeat steps 4-8 until the described issue occurs. It doesn't appear to happen on the first cycle of maelstrom generation/spending but it doesn't take me many cycles to generate this issue. 

### Snapshot (Link)

https://pastebin.com/NTtNsdG9

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mYGuwD9i5d3VvhkGFh1y72

### Additional Information

I am running the 9.2.5a Version of the addon. But this issue existed on the normal version before I started using the alpha version as well.

### Contact Information

Elutriate#2660

**Comment by Hekili** [comment]
This should be addressed in https://github.com/Hekili/hekili/releases/tag/v9.2.5-1.0.1-alpha2.

**Comment by Elutriate** [comment]
After installing this version, I was unable to recreate the described bug. Thank you!

**Comment by Hekili** [comment]
Thanks for reporting back!
