### ISSUE TITLE
[REC] Windwalker Monk, Spinning Crane Kick can not be recommended while being channeled

### ISSUE THREAD

**Issue by MrZombieCow** [Hekili/hekili#1522]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've been trying to implement a Bonedust Brew rotation for monk into my rotation helper, but Spinning Crane Kick can not be recommended while you're already channeling the spell. All it does is telling me that "The action is not ready ( 1192.96 ) before our maximum delay window ( 10.00 ) for this query." even tho it is the spell it should be recommending next.

### How to Reproduce

1. https://pastebin.com/W7fvSAzm <-- Use this action profile
2. Go on target dummies/anywhere where you can get +5 targets
3. Perform rotation
4. Once you get 5 stacks of Mark of the Crane and still have 5 targets you start spinning, but it will not recommend you to spin more if you are already spinning.

### Snapshot (Link)

https://pastebin.com/HX7aZ1v4

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/7zXVLuZ6fkEzF7SZN6qVgr

### Additional Information

Burst sim with original profile: https://www.raidbots.com/simbot/report/gwnt7c4H8qxgVfZrXqdvkD

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/releases/tag/v9.2.5-1.0.1-alpha3 should prevent Spinning Crane Kick's cast/channel/cooldown timing from getting mangled.
