### ISSUE TITLE
[REC] Outlaw w/ Concealed Blunderbuss recommends sinister strike as a builder at low (0 - 1) CP even with Blunderbuss proc active

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#1524]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I expected a recommendation to use the blunderbuss proc with pistol shot immediately after the finisher instead of using sinister strike, as otherwise the proc might be wasted due to a sinister strike re-proccing the effect.

### How to Reproduce

Difficult to reproduce this one as it doesn't always happen. I followed the rotation on a target dummy until I was able to produce a snapshot of the issue.

### Snapshot (Link)

https://pastebin.com/XqFWDqGs

**Comment by Hekili** [comment]
This is working as expected.  Pistol Shot wasn't used because you were at risk of wasting Energy regen since Pistol Shot's energy cost was reduced by Opportunity.

```
buff.opportunity.up[true] & ( energy.deficit[11.97] > energy.regen[25.75] * 1.5 | ! talent.weaponmaster.enabled[true] & combo_points.deficit[5.00] <= 1 + buff.broadside.up[false] | talent.quick_draw.enabled[false] )
```

Using Sinister Strike would help you spend down Energy to avoid waste.  You can customize a priority and test in Raidbots to see if changing the priority to match your expectations will sim higher than the default.

**Comment by fzarr** [comment]
Ah it seems the latest outlaw profile isn't included in the addon yet, from here: https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier28/T28_Rogue_Outlaw.simc the line:

`actions.build+=/pistol_shot,if=buff.opportunity.up(buff.greenskins_wickers.up|buff.concealed_blunderbuss.up|buff.tornado_trigger.up)`

adds an extra case for this situation.
