### ISSUE TITLE
Shadow priest rotation has the word DELETE across the icons

### ISSUE THREAD

**Issue by Divalicious72** [Hekili/hekili#1526]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

First time posting so hopefully I follow rules correctly.

The word DELETE shows up across the rotation icons while I am in shadowform , and it appears above my vampiric touch.. If I take myself out of shadowform, the word DELETE disappears. It follows the Vampiric Touch icon in my rotation. So if its already been used, the word disappears until Vampiric Touch appears in the rotation again.

No error messages show up in BugSack or anywhere else that I can see.

![WoWScrnShot_061122_090756](https://user-images.githubusercontent.com/107309452/173189417-c7a8edd6-e0df-4119-a3f3-b8cf35335154.jpg)

### How to Reproduce

I have changed specs but it only shows up when I go into shadowform, and only above the Vampiric Embrace icon

### Player Information (Link)

https://pastebin.com/09rcaEdX

### Error Messages (Link)

No error shown

### Additional Information

I tried to give you the error message but nothing ever popped up in the BugSack window.

### Contact Information

Divalicious#3980

**Comment by SpatenLa** [comment]
is the keybind for you vampiric touch the del key?

**Comment by Divalicious72** [comment]
> 

Well I feel like an idiot. Apparently my keybind changed DELETE to the 2nd bind of my vampiric embrace.. I've recently returned to the game, didn't change any binds so not sure how/why that happened as I only use it as the 1 key.  Thank you very much as that was driving me insane. Thought maybe wow was hinting at me to delete my priest ;-)
