### ISSUE TITLE
[REC] Sub Rogue second Shadow Dance charge recommended at tail end of Shuriken Tornado (e.g. in opener) which can be misleading

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#1527]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

This is more of a suggestion rather than an issue as the correct recommendation is made if the full duration of shuriken tornado is let expire before taking the next action, however it can be misleading due to a sudden change of recommendation when this occurs (e.g. shadow dance flips immediately to rupture in the opener once shuriken tornado ends).

The following line in the APL causes the addon to (correctly) recommend shadow dance until the full duration of shuriken tornado has expired - the downside is that if shadow dance falls off during shuriken tornado and there is a second dance charge available (which almost always happens in the opener), it will cause the addon to recommend pressing shadow dance, even though that is not 'in the spirit' of what the line is trying to achieve:

```
# Use Dance off-gcd before the first Shuriken Storm from Tornado comes in.
actions.cds=shadow_dance,use_off_gcd=1,if=!buff.shadow_dance.up&buff.shuriken_tornado.up&buff.shuriken_tornado.remains<=3.5
```

While this seems to work fine for simc itself, the upcoming recommended series of abilities could be better highlighted if the condition was something like the following:

`actions.cds=shadow_dance,use_off_gcd=1,if=!buff.shadow_dance.up&buff.shuriken_tornado.up&buff.shuriken_tornado.remains<=3.5&buff.shuriken_tornado.remains>1` 

I thought I would bring this to your attention even though its technically working as the APL is written.

### How to Reproduce

0. Select Shuriken Tornado talent
1. Follow opener rotation
2. After Shuriken Tornado is pressed, a second dance charge will be queued up as a recommendation instead of rupture/snd (e,g, ss->evis->ss->evis->dance and ideally should be ss->evis->ss->rupture->dance)

### Snapshot (Link)

https://pastebin.com/MnSu8nzL

**Comment by Hekili** [comment]
It looks like there's potentially an opportunity here, but you'll need to provide comparison sims to determine if it's a performance increase (or at the very least, not a performance loss).

**Comment by fzarr** [comment]
I ran a few sims that seems to indicate its not a dps loss:

https://www.raidbots.com/simbot/report/5hKiumMCNXC4oGsVNw8MTZ / https://www.raidbots.com/simbot/report/5hKiumMCNXC4oGsVNw8MTZ/simc (ST) 

https://www.raidbots.com/simbot/report/f729eVNyvUpekQGXo7a966 / https://www.raidbots.com/simbot/report/f729eVNyvUpekQGXo7a966/simc (DungeonSlice) 

However, I'm not confident it won't be worse in some situations. Might be best to leave this one out but perhaps there's an option or a warning that could be added to be careful about aggressively pressing dance during shuriken tornado somehow?

**Comment by Hekili** [comment]
> Might be best to leave this one out but perhaps there's an option or a warning that could be added to be careful about aggressively pressing dance during shuriken tornado somehow?

You'd have to provide a clear explanation of what you're seeking to accomplish and why someone would want to opt-in or opt-out of the feature, and a rationale for which option should be default.  But I'd consider it then.  Otherwise, I'll leave this as closed.
