### ISSUE TITLE
BM Hunter CORE dropdown does not have BM as a choice

### ISSUE THREAD

**Issue by Bri134** [Hekili/hekili#1531]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The BM specialization is not selecteable in the CORE tab dropdown menu.  

It is, however, selectable in the MM specialization CORE tab

### How to Reproduce

1 enter game as BM hunter
2. open addon
3. select Beast Mastery
4. CORE tab enabled
5. Priority dropdown only has 'none' as a selection

![image](https://user-images.githubusercontent.com/107523441/173723630-fd465b8c-bec6-4853-b68f-56654ae5715c.png)

![image](https://user-images.githubusercontent.com/107523441/173723701-9949b4d0-3bfd-40d7-a02f-d3d03d28faff.png)

### Player Information (Link)

https://pastebin.com/nv9E6qQ6

### Error Messages (Link)

None

### Contact Information

Brians#3724 on Discord

**Comment by Hekili** [comment]
Fixed in 9.2.5-1.0.1a.

**Comment by Romancito9** [comment]
> Fixed in 9.2.5-1.0.1a.

I am not seeing this update.
