### ISSUE TITLE
[BUG] I can´t view the BM Rotation.

### ISSUE THREAD

**Issue by Romancito9** [Hekili/hekili#1532]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I can not see the rotation of the BM Hunter. I haven't touched anything since yesterday, which was working normally, and today out of nowhere I can't see the rotation. Help me
![image](https://user-images.githubusercontent.com/107526127/173728346-765b5d45-5618-4644-b352-5ce695af5d2b.png)
![image](https://user-images.githubusercontent.com/107526127/173728379-edb4e68b-c4db-49f9-89f2-b5d9294fcb07.png)

### How to Reproduce

I enter the game normally as usual, but the rotation of my BM is not displayed.

### Player Information (Link)

build: v9.2.5-1.0.1 level: 60 (60) class: HUNTER spec: beast_mastery  talents: animal_companion     aspect_of_the_beast     binding_shot     natural_mending     scent_of_blood     stomp     thrill_of_the_hunt  pvptalents: none  covenant: night_fae  conduits: condensed_anima_sphere = 12    ferocious_appetite = 12    marksmans_advantage = 12    one_with_the_beast = 12    reversal_of_fortune = 12    spirit_attunement = 12  soulbinds: [tejesueos]    dream_delver = 1    field_of_blossoms = 1    podtender = 1    somnambulist = 1    soothing_voice = 1    waking_dreams = 1  sets: the_first_sigil = 1     tier28 = 5  gear: arganeo_extraviado_de_suturas = 1     botines_de_triturahuesos = 1     broche_de_unidad = 1     cabujn_del_vuelo_infinito = 1     camisote_de_acechadioses = 1     celada_de_acechadioses = 1     el_primer_sigilo = 1     escarcelas_de_acechadioses = 1     espaldares_de_acechadioses = 1     glndula_ocular_titnica = 1     grilletes_de_vitalidad_fascinante = 1     guanteletes_de_acechadioses = 1     mantn_de_lealtades_retorcidas = 1     tabardo_de_hermandad_ilustre = 1     tentculo_de_atiborrador_entrelazado = 1     the_first_sigil = 1     tier28 = 5     yasahm_el_rompegrietas = 1  legendaries: fragments_of_the_elder_antlers = 1     rylakstalkers_piercing_fangs = 1  itemIDs: 172323, 178736, 178846, 178848, 180123, 185783, 185820, 186423, 188271, 188856, 188858, 188859, 188860, 188861, 190466, 69209  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 3     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Beast Mastery (2)     petbased = false     potion = spectral_agility     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     avoid_bw_overlap = true     barbed_shot_grace_period = 0.5     check_pet_range = true  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      aspect_of_the_cheetah = 8   [01]     aspect_of_the_wild    = F   [05]     barbed_shot           = 2   [01]     bestial_wrath         = E   [05]     binding_shot          = G   [05]     cobra_shot            = 1   [01]     counter_shot          = M4  [06]     disengage             = 6   [01]     exhilaration          = 0   [01]     freezing_trap         = H   [05]     intimidation          = R   [01]     kill_command          = 4   [01]     kill_shot             = 3   [01]     multishot             = M5  [01]     potion                = CC  [05]     shadowmeld            = 9   [01]     the_first_sigil       = Z   [05]     tranquilizing_shot    = T   [06]     wild_spirits          = Q   [05]

### Error Messages (Link)

No error message

### Contact Information

Roxflop#1623

**Comment by Hekili** [comment]
See #1531.

**Comment by ghost** [comment]
Thank you soooo much for the quick fix! I struggled all night trying to diagnose and revert to a previous build but nothing worked. Then I found the update just when we hit the Jailer boss. All seems to work as expected.
