### ISSUE TITLE
[BUG] In Game Errors with Assassination Rogue

### ISSUE THREAD

**Issue by HolteUnderscore** [Hekili/hekili#1533]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Getting in game errors as assassination rogue and the action frame isn't showing during combat.

### How to Reproduce

1. Enter game as Assassination rogue
2. Kill any hostile mob

### Player Information (Link)

https://pastebin.com/3pi4LVcv

### Error Messages (Link)

https://pastebin.com/VMTdSqAQ

**Comment by Hekili** [comment]
Please try this test version in a few minutes when it's done packaging:

https://github.com/Hekili/hekili/releases/tag/v9.2.5-1.0.2-alpha1

**Comment by HolteUnderscore** [comment]
Yeah, that seems to be working properly now - not getting any errors and the actions are showing on target as I have them set.
Thank you.
