### ISSUE TITLE
[BUG] Demonology not working anymore since the latest update v9.2.5-1.0.2

### ISSUE THREAD

**Issue by stx4** [Hekili/hekili#1534]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Demonology is not loading anymore. Most likely because the default APL disappeared. I'm unable to add it myself as the looking glass icon is greyed out.

![image](https://user-images.githubusercontent.com/103367136/173894670-aec904e7-de7c-44f4-8085-9e213ea95112.png)

### How to Reproduce

1. Enter game as a warlock
2. Change spec to Demonology

### Player Information (Link)

https://pastebin.com/gB04WU2L

### Error Messages (Link)

There is no error

### Additional Information

No error.

### Contact Information

stx#9163

**Comment by shredxt** [comment]
I can repro this, might be related to the RegisterPack change: https://github.com/Hekili/hekili/commit/5026eb2443ec9dc43bb28f8f706dcbdfc0f64e53#diff-fb7619404d3488311210dcb3863acc4315cfe1fad77141a8a0c43cebc70efc41R2007

The string starts with Hekili:Hekili: and is much shorter than the previous value.

**Comment by shredxt** [comment]
Here is a working Priority Export String:
`Hekili:v3ZAtoUTr(BzQurR08qReNh749Kukh7C52T85KkJVZ(tdffjKeRHIuHp0UZvQ0V9RBa(aaeaKusZ6KpyVJibA0DJg9taWNh)8V88tEoPKN)zRrwwJEy89dTgBnA09p)u6RBjp)0wh3xCwb)rOZg4))JKnrHrbrREfF1RbroEiisIYIDHxVonDBYhF)7x5NUoBXq3OnVpXFtwGtQFuOBSZYu83UV)5NwK5hK(PWNxOy8h)G1dam3sCHh)a8NR998iS2ssC5XIdZ)vN4Gi3xo85pNfsomF84RpmhH1HpF4Z)WANWvKKpE4Z3Cy(tBjbbhM)tqJhsFWFlma6FmbWYnKqVdZPGDruq6H5BJj3apFHd83(lH)d)3e4)ctsDcHF0pk(W81oXEUojWpxI)CruscjzW)XH5ErHVdEA0osSRZ2dZtWwMWa1RrzVlgWue03Jq8W801WVJ2scjXmu7Vh9fcaWN83UocEVtqa8apr0knc)DKlhsvsa5qz3FhAMtabFNFykjooBB(7((Dr(aaF6pFZS)RO)kGHBD2Cy(xwtcRWWWiOFolIYYhTKSnBOOZH5)YRXWiYa1)zajznBY9)ncNQdG((uuWo6466e6scSrk3LoD4Xawj(aVIbNFj(v2RCy42xaoRF4QCYYhi0FicrlGyDFjrQpBCEPKhI8f)Oy)u4Dr0j5Vef)cJ7)fcfLGbXnnd4RVY6e8cqKTgP9PnahEh2LOnBbkBHFafQSg)FFfmNdYXEjdF(Pa)K0e6AbyUYon2p8fc9b)mDrgj0zraX75)CXkjyjtqajfPq74SfW6j3xDdi2PoXRWocD7jahH1nkBlqDKyFNNFANd8paOhUiB5s7KxdDTDbM3eCMhH0qpFu6WfiI3tf4aYQpSe5W8lpmFLR3WnoFL(3LaklHyJcr2P(BGreeBh8CkSsuImkrUSWfbrrE2azLU(1K0tc7UId7mIrfSXAJoGQ3QbvjB2(AmXjWok2leh12HQ91ITdOi8yRUJ31rfeZFABwmX2ZzdOYLjdzqcYd6V3sFOd7iGINGk6S2Bum9XGrmjjcg(uB4piXW6U4kOO4Dk4Tm44e7UgyKUPj2aHscZGLj2UWY1kWPVjauVtjuDJs247AVkWXZ3jnkoXMHtWFwbxtncG89NbE3dAxbB7VkefGexRw(uOVFqJS4QGx3U2oAPTtcys0NzIKxEeB4oInOqBJpbeDMccAfdT6odJ2JQPwN4x2effA7rCFXEBwkWHCju5)sYwBtaO(DkHkzruiLA35NWbjXhd9E8iLDpleSh4hs84N6adLUVa2tQaN5Mrx04cQOPcQom9ZQwYuXxHLPi6TWp0B4sFsGhYhbDijjrBsgM3LdZ3Vh8naCPaSSVIme4koVIQFPuwItQ7AsqvJb9a9aRoOgcMTk7uMve2KOK0rCuQQvKvOyj(TcT(alx25VkkMojxnMWaErhqXEufuLQMcjFnnhjluZznIr1ABZSdZVDevhMkYrwXqf5CbDOBltVve)GJH(VWWueTbMO8XpQMSL1CvUGI46VXHAYgnbiXpmyIOhhlia0fzV4vBYxD2SfAT0SPzQHXhqppztVm27jXeUJn9xZtff6zpR8Hxi7aNCTJI()ibWB7aF4TKKLnlCoizHfkOC9IO4qcysdcLamdiUuHVX7YD9ge)PEEll53mVCa3YkdQYuXj0zKZaNOr2WffXUmClgnKDcnyirgGBuuGx0xcfBsmzdyXiHk1ZWKHsiYqYxjUzPeCmjCKDj8yH6ylXcY2AqIJFuFuc9udU8EaRUHqDtjSLP3QxEt24EbxEzzayknIyuYaD2TElqK(5N4drdJyxvlZ2QYbbfyblSv7nep)06wYAJPt3OSyCcmfc(sTJfcRZAEKncB9oq0ETUGlBJQge)nqGME4O46KcX2ghTDDUB)5QCsiPa)0O3lMmGp((QbleIgcwrSnkgwez2BdJG8dfbmMVqsTKS4YPRQA9Ahqus)sU(CRrCHOXTPEFdXyf8cjoryj1PIjSwVdKDb)paPIJcLXf10PFo0SclNzWssnmXiEZ5I1Qy)nry4iljbRYaXkZ(A1GpEJV)i4IDFU6ygLwpx9TCEOC06l5T5x8dwgt8Gqr8x5hGEZMKTLGPDYMbyz3uAHpgLAJKOFvUz2YLVwN2eH(1cCXFxtwqL7Gv4ldaavdbzNuIWSNYzCLFMLt9QXz9oqKdQ7MrDXoExnWbU6vfy0aEN24v7xk1CCeZKormTAgtaJQtj9KFX3eCH6urnvCfoAP5TVTyw9fIIqLzX2JS0jd8OvHXASgfX(BzG4VWapivGEWJjRMoo0m(dddw2aSUco7C8dORI5gDSGf2yXnkTFlSMd4hRZcPjFQA0lmou0sNVcKgeMTuBUJVnEKDG7p2BCw57k1o5LXrBb8IKw13cTp4FfKrZzxN85vNtBnKKGookuTdv9jp8Dfidqo2S0tjQnvv4EDHxOFe)wKyQoZTMC6Cl5qcBMBPXqwNcF(cSWs2SYaXJF850xvOunJDJT6eIuIfcrux3oGjKuoQQMrYrNaoAYqfvrm4YJNneetYqAf4ORPgvqE52qRz80e9vl(TF)iWTXKD2y1WgpCTtiDL3QSapSqH9osIt2SqZex5so5SvysRHwoGrKtxX8Ogwy)WgROjRUM5qPSOMiemgcsJZmgIHUY5aZGGkts94IwiKWq)15fcHlpnTjjsuaj8AS)dQ7KRo(s0QCUQEN0XTgafNw6VAnwrTkpykReRqMca1(4FIq1GR0rRwbSNc5g2iWCWyIc)Rb5pyk0nvO2YMPmMIuShYw)6y1keYSFBRaGHCgXCcGv3hWGHBCuqeeBCNPWA1oc7RSTRUjBBkGSYcUxorPoqib2qmO1bla2whq(M0UOkXmj(4zBXe3kHTrPfcM6YhPzLi8P6cHI(Ch(MgZ93jhsK(u61qYEFqCRumG3XAwNaHss4Q01u)41N0sZtrD2joGiTSAkoDl9PASrbDt5AAgREI3q3MexEstKnMRbl952KkxNZHqMxJIfCPqfuiqOjgEfs7BwumA6T8XKzQkzpw2WITgYykBOivdoqNw67clQXv5jYoSRXFRPuHTI33jYQycJ2ZC7laQcRMb8X3jihmL2dRn4xwqfa5CxXpzHOMxLIHLMTyt)fPpdrBTd7UXctWcw(S0BpvbN26TKZji(QIo4v7i43XY4On2q4(2SKoizQZJqrOAnssPRiBrVdbFBeazW7wb4Hbj6gf6L5NQewDNL)VBcR6Dq64ew)2WL)xkbB9(Dv6)m6EKDAKTNpjVCPvatzPsSK9sPfa1IFVEOiz8w69zrlm5loNU8k(Z3Q35aPemZbnXawPGrVrDPnfctiOscybm3MS13dS1zViloKwTYOys9AgRTL8UgXtZv5CLII6TzdU7gtGMViGR6VErrBO9t3E7uIliMf2pT8W8FK3THdZDO7b7a8HVYsm8oY14EEg(pcsO0D8Sd6ciB3BRJlIlxVTy5H2CmuwXknb9sPn927KhWXvtecv6Ti03wvPUzsBdyJIu6n6ya3uLYiRkFQ1vhNrdz7eyCV1RR6GsmsUMAe6tovOZuldU2o7pvOG(gXY)WmKCPYQniIMNJifVPDtF6ToDbxG04w6y9RXNNWOVv3UcIXSGr4fI060F1pDn94g8uP)j4rjaCq5A2)c)FA)yvnb3dfHRW07LUgtvx55F4ACgHDQnw7Kq3w)R9xTM)ObiXcAWVik9O3ssJHkPD1a3ILczoQw08wGw44J9UkjvumsVDOwGogZDMHw0ku7ozlzcXeZ2myct9pTT6m4uCwpsYpyn5Z85hIMmWXKGIZPrLQoMiHl4obHP8MQAVwWGcCzOjUPu6vYU4Dn6(eehpsMYwABIm)r6(mQc7P5b5AQZPTI8FBOh6wfGspnekDxgT(gKRNvUFuBoGevmvev1hh(ji8BqI2G1zskmmHzjdt9jXwpABT11iFPp1d)62nuB0qSe1ZmzE7MsaiAdqcg3WTXiZzPk3Fe6N)yNgb1tm6DvOZYqokcOv3WsnXP0gtfUGTtNzPoBG7oDjaTrFrFnkl)yObXIcSzkpf1zDVSYUfOJ5KAEVkQ0JQP7A0E37GFf9It(HIlxPc4F4g0Z2V0SlSg14vgxE(A2YjsGXjKXoHk03GhOSvd3FSRggW78MrzEQl23jBX0Hp(c1bH0GlypRE7W3v7F)pOzlUtGk)rfDve1MboLYmVP8erEnDpMewCGvFNh7iusOU)KqLQO82HTDfPQ3XTj)OCE(tqOgTfu2XyHfNCXckS4epbC0dK7chLBTMcaab4B7fbQ0DkyQk3YnflEkoYSliRaSF4H5FVRlzBAcUOi8gGNSzjYDyqpHDOrf4sLZ(L17gvb7eGfWpvAV5KhbXwIeTP5KZLgTHGYSqFq3zZsWe8a)vgdzQGBtnmv3POljkG4SoXoH4gdgQsjURd9)NzeELLAArA(oaQKVZTtZfOn9HxC0E(c6KS0BnwwjEoPsfSaFiIIxG8Q0O4nGMkzjV6niT(wcrLQYeUKMGU3qt2dQTRM1u2XcNTta15bJ5DnF9r8IJCqLs9YrSTlQsqKA)Mk18Z4lDjFsx1cxaVQHQ4ZKMgWVJhQTBiOkxwVTXtvBIFiOmG)Wgs2aTydh7uxls1DkBZ7HdWjqZgAbzTgWoCagol5np11Mkw)2VBmQp3aT3MFdLO94L76aCyaMlJDGvhHom36wsKI)MHa6AS9DuF7ZNo0csfAP7eE0cKWmdVvOOUJCOwTFkImIY)5pK7yPInRenv)H8dp5WGxX2BJ9t20(iXAKnicxf2zkqam1)2e3a)TjK2rVFO8SuZ3vfww48cqYTxWQB2MT1uaAkkBRrTmEJknvkmnj6UZYL4HQNMdm8I6i2zhbD1li6l4TBbwbM89BmZdvmCH)zMpn93EE(iqCcWmqq26GcBykZc9qh6BjQkEHxOWUwbuWRdLLqJrJaoH(BCGihwPE6QUkI8zlnWqLzTshNyGySWuj7zdtX97xIDXWjo)PajaAnLdIPk2NFsdRLYH16egwAIAQTd(u4SQ6dyHMLeZ6GWPIBPcQLQ8TlMXdW2fTE3llfmp)PMV4fINYnfUBZRFqS0GsjfqHh8vL8tSTTRsiLETzkqy(8nj5LMEpQnRtvjoyUIDvj09oTOZh4zqk2goYHXr3tKfccf9d3cnK4xOQweyPctQS7ZLLzXVAAgfVIoOT00mjYHa22MA4hGHFXHYcGx9RF))4N)0p)x)4H5hM)lOIsisfqIkp7RVtq)27kvF6H8ACnLtgeAMdnGt2nCeE3e9t(0BJQpIHOhc6SOV(j)n)a0RxdtXiM)JSi6)Pmi8Cp)D(SnJaSgk2HEUq6)EW5R(J)6GsWzDEb3TNlWD4ZnWcLZE2jXfFxL(JF7DmSK)rfQpENe1kdLYTxzjqQEIoyyDwWezOCmyYTNfmrgkTftS4GXDam(hGlr7qia6H(4VHZGeuJsF2niwXzBIDzNrkUp4KfhV7irgEyC)5czU)mGmpCKW4woy8bjyK7dAjek(ToC4XJeh4HX3DgGX4rhhqqxA)l)TFQ9QA43FXDtnZPUKQrul)md2nS6TqqSRu2PjoligCSaHFnXy5ffTficyISu9XXuSopgNSKv(DKG58mtF7PsunUuOml)DBXqnTiDfXotGPr67iDxugVkIxCmNc)Qix)TA0L88wrJTu0Fl((3ibXcTRJKZXTmvwL)j6eyDliFIsziugpQil6hMtVapH3drpKLUgVHbrhIXcsfT0htO6F4pKx4n5BEw8fkU9zXhxDd0I)Q2TqB(d)x1BI2C07mCB0wajD3iT5V)CDR0MdUZYntBoS68TtRC)EdUHAZhIwFl1sLkHvdNNcKE4Z5)EyP28RM(EXsZET)YPyMNMnQ3fLLmvDhRQBQ63xel)1yoOM2q1qBdi0v1tn0vPSK63ZxzkKQvv3ZzJ7PPENtMA1kuwDQ5v31Y6cIOtvAHsMCFV(OcI97z9sQaIthnqZeuvgHQdXlAeKOWQkWwKolgfwlNLxhTDk4m)10Yznfuy3savE2VLaGAAtSVYjwteenum0E9BU8Nx1qjpVYq5oNnEqT1XT8UfPK2NwD3Iu(mGliETIW)MIRre(NXFTHubzroPyjqe5JD8anIYCxu6WqTJq8(9DeEZA(gUGNApg6shCrsPVjsPHmKpOxhP1jnJtcRRA7QPriLOV6XAzF8LEqeIAkEgDYxBIV7Dr1n9WrmMJTAa8LqNzet1b84ig2rTEu1mO9uAJbS0MQ5(Q43hSu7DRrVZjE26lpdKE0xcfzTHSFslbwUJh5r21ClXsGqxPBG7PDTZG977RVBg3Tf96FHbZh73t7S09DXGb80t5PYJ6idOuQNW1wXeRlbsRfmaMgd2zjz6yQVGs3yf9qtwtQxOYgHTCffegLsvR1Vrk2V3KE3Y3v7MNanViFBtWJLSRfHMMU1ODBs(UOKYnMvJBWHxIxfeAH3TpEcYpdAM7ZNKvrxcyIYfx4bm(rL1S2CW)1ruZ(oKM0UGr1sPc51hUmNbxN0eQIPrvdD1M7mlRMhndYk91XhSgDZ9x2rMQaHR4InOmILCIbPtTte3RvxbBQOy76pB8v9hFzdU6oqTvSPp0R94depd2wDNu8CvEsdXL9hF1Dx2xZPcFM1GbZMQfS7gRxHPetW6CqGCt3kqNkn(6ou273R)az3Ak5KMoVQ)TL9f9bv6ySpOlCJ)TC6(CYa(MjouBFZu6rqA15BFYTJ47J82NrzxSEurxe1OQSFJfu(i6pPywjMk0sTjVyY99AoE9EM3anf2zegr8eLGdf)jjbJA)CCw0Blpy20B71xJF573R35Z2d)8mAjFi071IJ)ZmRcZYDE4KxDzvp4JIbz0W7VQ8uxFfBCA6uERfAtogODv)rZ(t9V9Mk6yWGll6QQZg(r6M4nk4MhHZZxiFAWPsTFdpz2clBJkpgFuCRPJkGGh5IjK1GRwDmxT3AAyosNUn92Yr9pqRFuRoNWD8ysxZj(cfL15b0ZhwpofO3P1qL1ikoFQN553eKBYyRtdU91iEmZA)(MCs6nqaslXO6Wjlrj9FGx5KkDt8hLYz60oEtEhnCmmlAsv9b4F7aDl5MXL3(JAYYrYtwn6y6UQZst6)oDKEBVPZB1Vmf8Oo14r6Ll56gSN3V)9DroAWvnlVmOMhvch2wMflopS0yAKol9n8e22zHvvpN5XX4RYnRFPM1gA8YfRru(lgkSdMNkxfuXVTOQyWLcoikuK(1jsFtm)J3Ft)sp6UuRwSbAqRRQvRt5VSNDatUcWKthdQ9n6upg0Vgkm4QXwnHgviISALPf1PbhYtRurnxEMAJEHsX8X3q6u5Jev54RnnwtSgTFVons3Yxd6gWUlmYEmG7dAg5VqF6g1H6JF0iMlvDcvR2WTTCU40Aq6lD9WTUPn4bBjzk9fdSNHeMYzGeCz5ii17Ayw6TMwL(s2zGw)9I8mLE3kPwuau8Z83(9vVw(tUwVl0XagmWGa7PskgOevLBIZJbvFB(Mu6hO(VlFa1043JpLZ5fJXJDEpbmPjfpv7cibfJ1MJO2Qv(z17A(Tx2u1TJZBELA)e(A1jGi1QB1XQ(V2qCH(XWiK8v9vVdbyBumnDeVrYYZeRSlmAoq(k6zDVmuFY75hwSoUtRo6AIVaay15vR2RkpKA1Et5jttyKOfmDAlT9sNvAWcMmSHrwivDkEFTu(QOnYP4vvtmKWvZhjYMbMzBdLdJ5K2YYQYDkgT6yf)Ku9d)QK4iTNCFbXn11AYJ1)OR3PUR9JSENGIHpP6DcoNeNGovM)HuVtDu5hhDuSHPEPijacBfWMHQ2pq6DckcFC07upn(DqNx(SmoVIvjC7PXmUtvE((M5B9UtzqDmT(uVUB)cQkpg4nFjBCIJrlgI2yyv)GREF8Qp(sU9sGEOkCBzywp5PG88xyg6X4pOesQtQwP5zeCYzIkQ2TSH2u6MNV53UBeJoqtcPwOfCv1xSf1Nf5xcBgS4LgrX2vJT5Ry)9qX78IENd4BXdFRtc(QzN11qshrLz7RNsjsA1i4grw7P1IyQGprc8C5IgCVAiOYVjJW5d30NbNw8PRSSoJ6sKAV(Ti9Sh5yk5Px3qS8AmRQUSA4mMRPQ6udlptOAdiOnnuJVVdCL2YP7cmBfN(TLtIMZ74gkRDznrAIPHDCxTc0DmCrDIInjTicBdkx0TFk0VfeAnrmOkxk1LgkQedomYF(EhWsNurqZf7tYoGKtAns2iNoF0LXXEIp8nzCP(TP6ZjCpnV58JfdO3Ump))p`

**Comment by shredxt** [comment]
Here is a working string for Demo using the updated priority: https://pastebin.com/RWUhCpMz

![image](https://user-images.githubusercontent.com/47064656/173920041-e027583e-fce8-4b85-8e06-8243a913ce64.png)
![image](https://user-images.githubusercontent.com/47064656/173920074-ebdfe78c-df7a-45a3-9c24-2692fe63756b.png)

**Comment by Hekili** [comment]
> The string starts with Hekili:Hekili: and is much shorter than the previous value.

A string so nice, I named it twice...

When the build comes up, please test this alpha (https://github.com/Hekili/hekili/releases/tag/v9.2.5-1.0.2a-alpha1) and then report back if it works.

**Comment by stx4** [comment]
Checked. Works again.
