### ISSUE TITLE
[REC] Subtelty Rogue Recommendation issue (autosnapshot)

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#1537]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon has struggled to make a recommendation during fight which resulted in an auto-snapshot.

### How to Reproduce

1. Just follow addon recommendations for sub rogue untill atuo-snapshot occures

### Snapshot (Link)

https://pastebin.com/6TQfFncr

### Contact Information

IIeTpoc#3818 discord ID

**Comment by IIeTpoc** [comment]
One more Autosnapshot which occured during target dummy 2 minute fight  https://pastebin.com/7YSnGgBP

And a link from Warning tab which represents lua error in State.lua  (echoing_reprimand buff) https://pastebin.com/nx0BR0Lp

Issue Reporting tab link: https://pastebin.com/nJmu57cP

**Comment by Hekili** [comment]
None of these look like the auto-snapshot -- they all successfully generated recommendations.  Are you submitting the right snapshots?

**Comment by Hekili** [comment]
Test fix will be here soon:  https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.3-alpha2/Hekili-v9.2.5-1.0.3-alpha2.zip

**Comment by IIeTpoc** [comment]
> Test fix will be here soon: https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.3-alpha2/Hekili-v9.2.5-1.0.3-alpha2.zip

I have tested the latest addon verison as of today and still got this issue. I am posting auto screenshot and snapshot of today's  recommendation issue. BUT i want to adress that it is for the icon number 3, thus it is not very urgent in my opinion. Still just noticed that it happens which did not occure 2 weeks ago.

![hekilisubbug](https://user-images.githubusercontent.com/64799395/174432677-2b25ea66-4c3f-45f0-9b2b-54805362b3e2.jpg)

Target dummy fight duration: 2 min 34 sec

Snapshot link: https://pastebin.com/58G6TAKL

Issue reporting tab info: https://pastebin.com/5jRtZKEC

Warning tab: nothing related

**Comment by Hekili** [comment]
If you enable Enhanced Recheck (/hekili > Subtlety > Performance > Enhanced Recheck), does this still occur?

**Comment by IIeTpoc** [comment]
I am checking it right now. Will be back in 5 minutes

**Comment by IIeTpoc** [comment]
> If you enable Enhanced Recheck (/hekili > Subtlety > Performance > Enhanced Recheck), does this still occur?

No it stopped occuring, Thanks for the hint!
