### ISSUE TITLE
[BUG] Windwalker Monk only showing 1 icon, sometimes none

### ISSUE THREAD

**Issue by GiurlaniDev** [Hekili/hekili#1538]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not loading for my Windwalker Monk. I don't see any errors whatsoever and apart from that it is working correctly, except sometimes it will show only 1 icon or sometimes none. 

I am unaware of what is causing it, although I'm pretty sure it's related to AOE (or might not be). I used to see a recommendation to spam Spinning Crane Kick, and now that does not show. 

I have played around with the settings and I am unable to revert to the previous functioning iteration

Doesn't load -
![Uploading WoWScrnShot_061722_132632.jpg…]()

Sometimes only loads 1 icon -
![Uploading WoWScrnShot_061722_114306.jpg…]()

How it usually looks - 
ST - ![Uploading WoWScrnShot_061722_133344.jpg…]()
AOE - ![Uploading WoWScrnShot_061422_195940.jpg…]()

### How to Reproduce

1. Play Windwalker Monk
2. Go into a m+ key
3. Start AOE and see it disappear / show no options whatsoever / only show 1 icon as opposed to the usual 3 or 4

### Player Information (Link)

https://pastebin.com/W7xPJJ6p

### Error Messages (Link)

N/A not getting any errors

### Additional Information

My discord name is Swoots. Please let me know if the screenshots have uploaded or not, my internet is very crappy and even though I attached several to the bug report, it's unclear if they've actually gone up

### Contact Information

Swoots#4547

**Comment by Hekili** [comment]
Thanks!  I'm investigating and testing a fix right now.

**Comment by Hekili** [comment]
Test fix is here:  https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.3-alpha1/Hekili-v9.2.5-1.0.3-alpha1.zip

**Comment by blake8705** [comment]
Had the same issue on WW monk, the posted fix seems to have worked for me. Thank you!
