### ISSUE TITLE
Dps Defensives - allow DPS to use defensives display and associated toggle.

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#154]
Hi just got a question, i try to get a list for 1 defensive for unholy, i made the list and added that to default and all set the % hp but the icon will not show in the defensive made it all right wont show as a dps then even if the spell is set to defensive and all, anyway best addon!

**Comment by Hekili** [comment]
Show what you did.

**Comment by Tobbelainen** [comment]
did make a new action list mitigation with icebound fortitude put it to ur default list as call list name mitigation and put health.pct <88
and it wont show in the defensive icon as a Unholy Dk i must be doing something wrong

**Comment by Hekili** [comment]
Can you post screenshots of the changes you made?

**Comment by Tobbelainen** [comment]
sure

**Comment by Tobbelainen** [comment]
![WoWScrnShot_062719_230351](https://user-images.githubusercontent.com/48166902/60300820-1b7a7180-9930-11e9-96f1-e72de9b7758a.jpg)

**Comment by Tobbelainen** [comment]
![WoWScrnShot_062719_230343](https://user-images.githubusercontent.com/48166902/60300848-3220c880-9930-11e9-8894-f4aef5f0f08a.jpg)

**Comment by Hekili** [comment]
Thanks.  Right now, the Defensives display requires that you're in a tank spec for it to show up, but I will relax that in 8.2.0-03.

**Comment by Tobbelainen** [comment]
the funny thing is that the icon icebound fortitude shows in the defensive icon when i have the window opened, and when i close to test just to see so it shows when i have that% it wont come up i have done every thing to activate so icebound shall be a defensive=)

**Comment by Tobbelainen** [comment]
Ur my superstar<3 thanks then i was on the right track^^

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/releases/tag/v8.2.0-03-alpha1

**Comment by Tobbelainen** [comment]
tyty

**Comment by Tobbelainen** [comment]
quick question whats the code to make example Death strike show when a buff called dark succor comes up in the condition sorry for hold up your time this late. Bye =)

**Comment by Hekili** [comment]
I'd generally direct you to the simulationcraft wiki since the syntax is the same (or similar), but assuming Dark Succor is supported, you want to use `buff.dark_succor.up` as the condition.  But this is not really a ticket issue any longer.  :)

**Comment by Tobbelainen** [comment]
<3 the best tyty

**Comment by ColonialAF** [comment]
Necro posting, but was this undone? Because I can't find a toggle anywhere, and as a DPS I definitely have need of using defensives. Especially on Rasz.

**Comment by Hekili** [comment]
/hekili > Toggles > Defensives > Show Separately

The issue will be that the default DPS priority does not include defensive abilities.  You can look at the Wiki/FAQ to determine if you want to manually add some defensive abilities to your priority.  They are not included by default because more often than not, you'd want to choreograph them with raid mechanics that the addon doesn't track for you.

**Comment by ColonialAF** [comment]
I feel like that's where that "show separately" option comes in, same with
interrupts.
