### ISSUE TITLE
Fire mage rotation can't produce a recommendation, typically seems to be due to Sun King's Blessing legendary.

### ISSUE THREAD

**Issue by awcarr** [Hekili/hekili#1540]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Fire mage rotation can't produce a recommendation, typically seems to be due to Sun King's Blessing legendary.

### How to Reproduce

Hit target dummy in single target until SKB proc is available.

### Snapshot (Link)

https://pastebin.com/DPqJV65g

**Comment by Hekili** [comment]
This should be addressed in 1.0.4; if not, reopen this ticket and add a new snapshot, please.
