### ISSUE TITLE
WarlockDestruction.fixed_aoe_3_plus checked and 2targets still recommend Rain of Fire.

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#1542]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

WarlockDestruction.fixed_aoe_3_plus checked and 2targets still recommend Rain of Fire.

**Comment by Hekili** [comment]
You are welcome to submit a ticket re: Recommendations and provide all the required information if you'd like me to look into this issue.
