### ISSUE TITLE
[REC] Subtelty rogue shadow dance during GCD recommendation + possible skip_rupture tweak with simms.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#1546]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon follows simcraft's recommendion flawlessly but I found out that it recommends to use Shadow Dance before a GCD becomes available which results in loosing 1 effective cast during Shadow Dance window. Here are sims:
1. [Default T28 Sub rogue sim]( https://www.raidbots.com/simbot/report/h4oUe53QTwm9HUMoNL9L4Q) **16875 DPS**
2. [Shadow dance on GCD sim](https://www.raidbots.com/simbot/report/kwaxXbuWhafn6Nhb1iMz2u) **16875 DPS**
So DPS is the same and makes actually gameplay using addon smoother. As a note i added `use_off_gcd=0` to all _shadow_dance_ entries in the 2nd sim except for the 1st one in CDs which adresses _shuriken_tornado_ as it is needed to be used off gcd there. 
I wanted to add that in default simc profile in line 88 `actions.cds=shadow_dance,**use_off_gcd=1**,if=!buff.shadow_dance.up&buff.shuriken_tornado.up&buff.shuriken_tornado.remains<=3.5` specifically stated, that Shadow dance should be used off GCD but in all other shadow dance entries GCD is not adressed at all, thus i suspect simc logic is to allign shadow dance use with GCD.

One more thing is about Rupture. Again simc's logic is followed but sometimes addon recommends to refresh Rupture during Shadow dance window where it could fill in 1 more Eviscerate and then reapply rupture outside of Shadow dance with minumum downtime. I provide a snapshot of that situation and also simc reports modeling to not recommend Rupture during `stealthed.all`

1. [Default T28 Sub rogue sim]( https://www.raidbots.com/simbot/report/h4oUe53QTwm9HUMoNL9L4Q) **16875 DPS**
2. [Skip rupture during shadow dance](https://www.raidbots.com/simbot/report/p7vvBJ1TKVHQTQpcrMs8v9) **16885 DPS**

That is also not a DPS loss compared to default simc priority.

And final sim link modules both skip rupture during `stealthed.all` and shadow dance with `use_off_gcd=0` mod. [LINK](https://www.raidbots.com/simbot/report/8Qb8GwChjv7yrcZ9CaocWp) **16881 DPS**

### How to Reproduce

#

### Snapshot (Link)

https://pastebin.com/ZUXH6hQd

### Contact Information

IIeTpoc#3818 discord ID

**Comment by Hekili** [comment]
I would recommend having the default simc priorities updated, if you have not already, and then I would incorporate this once those are published.  Thanks!
