### ISSUE TITLE
[REC] Cache of acquired treasures is meant to be used off gcd

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#1547]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I tested this on subtelty rogue. [Cache of acquired treasures](https://www.wowhead.com/item=188265/cache-of-acquired-treasures?bonus=6805) should be used off gcd but addon still accounts for a GCD before recommending to cast this trinket.

### How to Reproduce

1. Enter game as a sub rogue
2. Go to target dummy in orgrimmar
3. Equip [Trinket](https://www.wowhead.com/item=188265/cache-of-acquired-treasures?bonus=6805) 
4. Start to follow addon's recommendations

### Snapshot (Link)

https://pastebin.com/Um8hj15v

### Additional Information

I checked Trinkets.lua and there is coded `gcd=off` but yet it is still recommended to be used only when GCD is ready.

### Contact Information

IIeTpoc#3818 discord ID

**Comment by Hekili** [comment]
You would need to supply a snapshot where the trinket is being recommended.  This one does not.  It shows that your trinket is on CD for ~170 seconds.

**Comment by IIeTpoc** [comment]
Sorry. this one should have it

https://pastebin.com/wwVLudkG

**Comment by Hekili** [comment]
This snapshot shows it being recommended now, but your GCD isn't active.  Take a snapshot while the GCD is still active and the trinket is being recommended after the GCD expires.

**Comment by IIeTpoc** [comment]
I hope this one shows it
![WoWScrnShot_062222_210801](https://user-images.githubusercontent.com/64799395/175107270-7a4b1edc-e561-4d25-8454-61310055cb21.jpg)
https://pastebin.com/KcmWKw0H
Enhanced recheck is turned on

**Comment by Hekili** [comment]
This should be addressed in the next release.  If not, feel free to reopen this ticket with an updated snapshot where the trinket is looking to sync with the GCD.  Thanks!
