### ISSUE TITLE
[BUG] Lua errors in/after combat after swapping from Feral to Resto

### ISSUE THREAD

**Issue by Kathalian** [Hekili/hekili#1548]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

once combat begins you pretty much get a constant string of errors even when not actually attacking based on my limited knowledge of LUA it seems to be an issue tracking combo points

### How to Reproduce

1. Be a resto druid
2. take feral affinity
3. go and fight anywhere in shadowlands (I tried to replicate this on target dummies it doesn't seem to work almost to the point of fooling me it had stopped happening)

### Player Information (Link)

https://pastebin.com/f0rtgRHh

### Error Messages (Link)

https://pastebin.com/7erP1uUx

### Contact Information

Kathalian#3071

**Comment by Hekili** [comment]
The addon shouldn't even work for Resto, so I'll address that problem.

**Comment by Hekili** [comment]
I'm not able to replicate this issue with the information provided.

Edit:  Looks like it only takes effect if you are Feral and swap to Resto after logging in.

**Comment by Hekili** [comment]
This should resolve the issue when the link becomes active:  https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha2/Hekili-v9.2.5-1.0.5-alpha2.zip

Let me know if you still see errors.

**Comment by Kathalian** [comment]
> I'm not able to replicate this issue with the information provided.
> 
> Edit: Looks like it only takes effect if you are Feral and swap to Resto after logging in.

I've never had it happen under this circumstance (feral is the one spec I don't play) though it may happen when swapping between guardian and resto I do that a lot

**Comment by Kathalian** [comment]
> This should resolve the issue when the link becomes active: https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha2/Hekili-v9.2.5-1.0.5-alpha2.zip
> 
> Let me know if you still see errors.

yep that seems to have solved the problem just did a dungeon no errors at all :)

**Comment by Hekili** [comment]
Thanks!
