### ISSUE TITLE
[BUG] Xy'mox - Addon disappears for survival hunter on latest update

### ISSUE THREAD

**Issue by 3ternalhunter** [Hekili/hekili#1549]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon move suggestions completely disappear in phase 2 or while on the platforms fighting the adds.
Survival Hunter - Setting Automatic

### How to Reproduce

1. Play as a survival hunter
2. Display mode - Automatic
3. Get to phase 2 of Xy'mox
4. Target Adds

### Player Information (Link)

https://pastebin.com/JimyrG9U

### Error Messages (Link)

N/A

**Comment by Hekili** [comment]
> [x] I confirm that I have downloaded the latest version of the addon.

v9.2.5-1.0.2a is not the latest update.  Try https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha2/Hekili-v9.2.5-1.0.5-alpha2.zip.

**Comment by 3ternalhunter** [comment]
> > [x] I confirm that I have downloaded the latest version of the addon.
> 
> v9.2.5-1.0.2a is not the latest update. Try https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha2/Hekili-v9.2.5-1.0.5-alpha2.zip.

My bad, I downloaded an old version to fix the issue and pasted the old.
It exists in the new

**Comment by Hekili** [comment]
You'll have to show it happening with the latest version; do you routinely use alpha versions?  The one I linked has only been available for 9 hours.

If you don't have BugSack and BugGrabber (or there are no error messages there), please check /hekili > Warnings and look if any error messages have been captured there.  If/when you have data from the latest alpha version, you can reopen the ticket.  Thanks!
