### ISSUE TITLE
Priority display disappears as soon as adds spawn in Xymox attempt. 

### ISSUE THREAD

**Issue by nhiebert1776** [Hekili/hekili#1550]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Survival hunter using default settings. Tried reseting profile still experiencing issue.  HUD functions normally until adds spawn on Mythic xymox. Then only shows when i have wildfire procs or serpent sting to apply. 

### How to Reproduce

engage xymox as survival hunter, using Koryn soulbinds. HUD functions as normal until adds spawn then hud disappears only suggesting serpent sting and wildfire procs. 

### Player Information (Link)

https://pastebin.com/BLFya6d2

### Error Messages (Link)

https://pastebin.com/BLFya6d2

### Contact Information

Rubix#9866

**Comment by Hekili** [comment]
Try https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha2/Hekili-v9.2.5-1.0.5-alpha2.zip

**Comment by nhiebert1776** [comment]
> Try https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha2/Hekili-v9.2.5-1.0.5-alpha2.zip

Thanks for the fast response. Same issue though.

**Comment by Hekili** [comment]
I'll need the following information to proceed:

1. When this is occurring, try to generate a Snapshot.  The keybinding for this is `ALT-SHIFT-[` by default but can be changed on the Toggles section of `/hekili`.  After the fight, you can retrieve the snapshot from `/hekili` > Snapshots, paste the text to Pastebin, and link it here.

2. If you have BugSack and BugGrabber (addons), if they have collected any error messages, please report them back.

3. After a fight where this has occurred, open the `/hekili` > Warnings section and click the dropdown.  Take a screenshot of the messages that appear there.  If any of them are not related to flash spells or auditing or removing auras, select one and then report back the content of that Warning here.

Thanks!

**Comment by 3ternalhunter** [comment]
This is the warning I am receiving using 9.2.5-1.0.5-alpha2:

Update: Interface\AddOns\Hekili\Targets.lua:282: attempt to compare nil with number

[string "@Interface\AddOns\Hekili\UI.lua"]:1104: in function <Interface\AddOns\Hekili\UI.lua:903>

**Comment by nhiebert1776** [comment]
We just finished on prog for the week unfortunately. Hopefully 3ternalhunter can provide the requested info, otherwise I'll do it next Wednesday raid. I'll try in LFR maybe same issue.

**Comment by nhiebert1776** [comment]
> This is the warning I am receiving using 9.2.5-1.0.5-alpha2:
> 
> Update: Interface\AddOns\Hekili\Targets.lua:282: attempt to compare nil with number
> 
> [string "@interface\AddOns\Hekili\UI.lua"]:1104: in function <Interface\AddOns\Hekili\UI.lua:903>

I have this same warning.

**Comment by Hekili** [comment]
Thanks, I'm posting a 1.0.5-alpha3 that may resolve this issue.  It'll take a minute before it's online.

https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha3/Hekili-v9.2.5-1.0.5-alpha3.zip

**Comment by Hekili** [comment]
If either of you get an opportunity to test and confirm this is working, let me know and I'll post the fix as a release.  Thanks again for reporting.

**Comment by Plasmaxyz** [comment]
I was having this same issue on mythic on my BM/Survival hunter with the latest version and 1.0.5-alpha3 has fixed the issue.

**Comment by Hekili** [comment]
Thanks.  I'll go ahead and publish a full release to address this ASAP for other folks.
