### ISSUE TITLE
[BUG] Priority list dissapears in the transition phase on Xymox (demo warlock)

### ISSUE THREAD

**Issue by KNP54** [Hekili/hekili#1551]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When fighting Xymox on mythic difficulty and targeting adds in the transition phase, the priority list disappears. Once the transition phase is complete, switching back to Xymox the priority list reappears. I have not tested other class/specs or other difficulty. One thing to note, we have another demo warlock in our group using Hekili and he experienced the same bug. also, there was no LUA errors.

### How to Reproduce

1. Enter the game as a Demo Warlock
2. Start the Xymox mythic fight
3. Wait for the transition phase
4. Target an add

### Player Information (Link)

https://pastebin.com/1GrizL6G

### Error Messages (Link)

no LUA error

### Contact Information

Picoglad#7304 (discord)

**Comment by Hekili** [comment]
Try https://github.com/Hekili/hekili/releases/download/v9.2.5-1.0.5-alpha2/Hekili-v9.2.5-1.0.5-alpha2.zip

**Comment by Hekili** [comment]
Closing as a duplicate ticket.
