### ISSUE TITLE
Rogue Assassination low crimson tempest uptime

### ISSUE THREAD

**Issue by jpnow** [Hekili/hekili#1552]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi,
During some log comparisons and testing on the dummy. I noticed that CT is being dropped more frequently and sometimes its not being recommended during vendetta. Some 5min target dummy fights were showing 10 to 15% less uptime compared to 5min sims.

### How to Reproduce

Following the recommended spells with enhanced recheck on (5min tests)

### Snapshot (Link)

https://pastebin.com/ALcDHqG1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/oouHc7771sVp1Cc8WC4QVp

**Comment by Hekili** [comment]
Hi, I will be posting an updated version of the addon tonight; if you are still having this issue, feel free to reopen this ticket with a snapshot taken at a time you think Crimson Tempest should be recommended, but isn't.  Thank you.
