### ISSUE TITLE
[BUG] FURY BLADESTORM AND RECKLESSNESS NOT SHOWING IN RECOMMENDED LIST

### ISSUE THREAD

**Issue by srice88** [Hekili/hekili#1554]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Warrior Fury - Bladestorm and recklessness abilities not showing in the recommended list.. I've looked through all setting and cannot find where to enable

### How to Reproduce

1. Login in as Fury Warrior
2. Fight mobs
3. Bladestorm and recklessness do not show on the recommended list

### Player Information (Link)

build: v9.2.5-1.0.5 level: 60 (60) class: WARRIOR spec: fury  talents: anger_management     bladestorm     cruelty     fresh_meat     impending_victory     massacre     warpaint  pvptalents: none  covenant: kyrian  conduits: condensed_anima_sphere = 9    indelible_victory = 3    inspiring_presence = 10    piercing_verdict = 8    unnerving_focus = 6    vicious_contempt = 5  soulbinds: [kleia]    cleansing_rites = 1    light_the_path = 1    mentorship = 1    pointed_courage = 1    spear_of_the_archon = 1    valiant_strikes = 1  sets: grim_codex = 1  gear: achillites_unbreakable_grip = 1     anima_field_emitter = 1     drape_of_titanic_dreams = 1     dutys_ascendant_breastplate = 1     enforcers_containment_cinch = 1     entwined_gorger_tendril = 1     fleshfused_circle = 1     grim_codex = 1     legplates_of_unholy_frenzy = 1     pauldrons_of_unleashed_pride = 1     rimebinders_runeblade = 1     selfless_collectors_warboots = 1     sin_stained_pendant = 1     stonewrought_armplates = 1     stonewrought_legion_halberd = 1     wing_commanders_helmet = 1  legendaries: none  itemIDs: 174291, 178739, 178780, 178811, 178812, 178820, 178827, 178848, 178869, 180118, 180398, 181203, 185781, 185792, 189796, 189826  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Fury     petbased = false     potion = potion_of_phantom_fire     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     check_ww_range = true     heroic_charge = false  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      bladestorm        = 5   [01]     bloodbath         = 3   [01]     bloodthirst       = 3   [01]     charge            = 1   [01]     crushing_blow     = 2   [01]     execute           = 7   [01]     grim_codex        = 0   [01]     impending_victory = 8   [01]     raging_blow       = 2   [01]     rampage           = 6   [01]     spear_of_bastion  = 9   [01]     whirlwind         = 4   [01]

### Error Messages (Link)

na

### Contact Information

swrice06@gmail.com

**Comment by Hekili** [comment]
Turn on cooldowns in `/hekili` > Toggles.
