### ISSUE TITLE
[REC] DK/Unholy Apocalypse is recommended without being castable

### ISSUE THREAD

**Issue by Drizzt1990** [Hekili/hekili#1555]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Apocalypse under 16 sec boss TTL is recommended without being castable, since there is a blanket condition without checking for festering wounds

![grafik](https://user-images.githubusercontent.com/59632954/176316699-e3c33997-563a-4693-b678-206b597776b0.png)

checked with current simcraft and simcraft is the same, I don't no if simcraft handles and/or different but it seems to be just wrong even on their end

### How to Reproduce

get in bossfight
have cooldowns active
get boss down to less than 16 sec to live with 0 festering wounds

### Snapshot (Link)

https://pastebin.com/mUdUM2t5

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/aRfz1J45ZMLaqAaA8mGaLE

### Contact Information

Drizzt1990#5474

**Comment by Hekili** [comment]
This will be addressed in the next release.
