### ISSUE TITLE
[REC] Ret Paladin Precombat Boss Recommendation

### ISSUE THREAD

**Issue by Jacii1121** [Hekili/hekili#1556]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I expect to have a precombat recommendation of Blade of Justice > Judgment > Crusader Strike. 
However, I'm getting Trinket > Divine Toll > Blade of Justice.

Only seems to happen on Bosses, and quickly changes once in combat.

### How to Reproduce

Before combat, target boss. Look at recommendations.

I did swap Conduits earlier in the raid, but swapped them back for this boss.

### Snapshot (Link)

https://pastebin.com/mxrjU6Y1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bxbsWG56npN8qowPLqn77u

### Contact Information

Jacii#8227

**Comment by Hekili** [comment]
Any errors in BugSack/BugGrabber or /hekili > Warnings?  (You can ignore any warnings about flashes or auras being removed.)

It looks like the time-to-death calculation is showing 1 second remaining.  I'm going to assume this was after at least one pull.  Does it occur after a /reload?

**Comment by Jacii1121** [comment]
Just checked again this morning. Able to replicate with the "Raider Training Dummy" in Bastion.  (not able to get back into a raid). Nothing in Bugsack or /hekili > Warnings. 

Reloading seems to fix, temporarily. However, after about 10 seconds of just standing in front of the dummy, the recommendations change to Trinket>DT>BoJ.

**Comment by Hekili** [comment]
This should be addressed in the next release; it was related to time-to-die calculations.
