### ISSUE TITLE
Warrior/Arms 2+ Target Cleave addon will not recommend MS

### ISSUE THREAD

**Issue by killer1209** [Hekili/hekili#1557]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When more then one target is in range MS will not be recommended unless sweeping strikes/cds are active.

During start of pull with cds it seems like the rotation works it has you charge >Avatar >Warbreaker >Bladestorm>SS>Rend>MS>overpower and then will do a basic MS/overpower rotation. up to this point everything seems good.

After SS/CDS drop the addon will only recommend WW and overpower intill SS is about to come up. the global before SS comes up it will recommend MS and then back into a normal MS/overpower roation with WW as a filler if getting rage caped

The issue is the 15 seconds once SS falls the addon only recomends WW/overpower. I am new to warrior so i could be wrong but these seems/feels extremly inccorect expecially because arms runs the MS lego.

I have tried on 2 targets and 4 and it gives the same recomendation.

i apologise if i am an idiot and dont know what im talking about :) if that is the case sorry for wasting your time

### How to Reproduce

Arms warrior
Sudden Death-Double Time-Rend-Bounding Stride-Warbreaking-Avatar-Dreadnaught

Start pull- Do rotation till SS/CD fall
Profit?

### Snapshot (Link)

https://pastebin.com/J9Grwdzu

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/d5UzMvajYT3LHrvu9dMupf

### Contact Information

Shakeykev#9472

**Comment by killer1209** [comment]
So i dug into this a little bit more and it appears that the addon is following the sim recommendations
https://i.imgur.com/QNE5JlM.png

It looks like the sim is saying when SS is not up it only MS to refresh deep wounds.

Is it possible that the sim rotation is incorrect? or do i just not know what im talking about. 

IMO the only time you would WW over MS is if enough targets are present to do more damage in 1 WW then 1 MS. Currently my MS does 6426 and WW does 1677 meaning WW needs to hit 4+ target to do more damage then one single MS. That is also ontop of the damage factor of the MS lego(i have no idea how to calculate that)

feel free to call me a idiot if i am wrong :)

**Comment by Hekili** [comment]
> Is it possible that the sim rotation is incorrect?

All things are possible.  You can edit the priority in your sim and see if you get better results.  If you do, you'd want to let SimulationCraft know and let me know, and I can adopt similar changes.

> or do i just not know what im talking about.

The only way to find out is to edit priorities in SimulationCraft and see if you end up with higher DPS output.

https://www.raidbots.com/simbot/report/cvgRZDrgh4k7HtiVFZE3Pv

Without putting a lot of thought into it, I added a conditionless entry for MS in the `hac` action list and it's a fair DPS increase.  You could probably keep tinkering with its position and while thinking about other mechanics and improve on it.

**Comment by Hekili** [comment]
I'm going to go ahead and make some updates that reflect my own testing.  If SimC makes different updates at some point, I'll incorporate those when they're available.
