### ISSUE TITLE
[BUG] Hekili crashes when sorting bag

### ISSUE THREAD

**Issue by Sneezry** [Hekili/hekili#1558]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I sort the bag, Hekili crashes and the recommendation disappears.

I can see there's a warning in Hekili warning tab:

```
Update: Interface\AddOns\Hekili\State.lua:3821: bad argument #1 to 'IsAzeriteItemEnabled' (Usage: local isEnabled = C_AzeriteItem.IsAzeriteItemEnabled(azeriteItemLocation))

[string "@Interface\AddOns\Hekili\UI.lua"]:1104: in function <Interface\AddOns\Hekili\UI.lua:903>
```

I didn't see any related error message in BugSack. But here are the two error in BugSack report:

<details>
<summary>BugSack report</summary>
<h1>SexyMap addon error</h1>
<pre><code>
  5x SexyMap\Borders.lua:934: attempt to index global 'MinimapStyleShowString' (a nil value)
  [string "@SexyMap\Borders.lua"]:934: in function `ApplyPreset'
  [string "@SexyMap\Borders.lua"]:903: in function `OnEnable'
  [string "@SexyMap\SexyMap-v9.2.6.lua"]:424: in function `PLAYER_LOGIN'
  [string "@SexyMap\SexyMap-v9.2.6.lua"]:383: in function `?'
  [string "@SexyMap\SexyMap-v9.2.6.lua"]:33: in function &lt;SexyMap\SexyMap.lua:32&gt;
  [string "=[C]"]: in function `LoadAddOn'
  [string "@BigFoot\BigFoot-zhCN9.2.5.921.lua"]:1: in function `BigFoot_LoadAddOn'
  [string "@BigFoot\Config\MapToolkit.lua"]:197: in function &lt;BigFoot\Config\MapToolkit.lua:194&gt;
  [string "=[C]"]: in function `pcall'
  [string "@BigFoot\BigFoot-zhCN9.2.5.921.lua"]:1: in function &lt;BigFoot\BigFoot.lua:1&gt;
  [string "@BigFoot\BigFoot-zhCN9.2.5.921.lua"]:1: in function &lt;BigFoot\BigFoot.lua:1&gt;
  [string "@BigFoot\BigFoot-zhCN9.2.5.921.lua"]:1: in function &lt;BigFoot\BigFoot.lua:1&gt;
  [string "@BigFoot\BigFoot-zhCN9.2.5.921.lua"]:1: in function &lt;BigFoot\BigFoot.lua:1&gt;
  [string "@BigFoot\BigFoot-zhCN9.2.5.921.lua"]:1: in function `BigFoot_OnEvent'
  [string "*:OnEvent"]:1: in function &lt;[string "*:OnEvent"]:1&gt;
  
  Locals:
  self = &lt;table&gt; {
   UpdateBorder = &lt;function&gt; defined @SexyMap\Borders.lua:1088
   CreateBorderFromParams = &lt;function&gt; defined @SexyMap\Borders.lua:968
   ClearWidgets = &lt;function&gt; defined @SexyMap\Borders.lua:1013
   UpdateBackdrop = &lt;function&gt; defined @SexyMap\Borders.lua:1096
   NewBorder = &lt;function&gt; defined @SexyMap\Borders.lua:944
   db = &lt;table&gt; {
   }
   OnDisable = &lt;function&gt; defined @SexyMap\Borders.lua:911
   presets = &lt;table&gt; {
   }
   StartRotations = &lt;function&gt; defined @SexyMap\Borders.lua:1034
   ApplyPreset = &lt;function&gt; defined @SexyMap\Borders.lua:932
   GetSequenceOfBorderPresets = &lt;function&gt; defined @SexyMap\Borders.lua:1112
   SavePresetAs = &lt;function&gt; defined @SexyMap\Borders.lua:950
   OnEnable = &lt;function&gt; defined @SexyMap\Borders.lua:859
   Clear = &lt;function&gt; defined @SexyMap\Borders.lua:925
   RebuildPresets = &lt;function&gt; defined @SexyMap\Borders.lua:915
   ApplySettings = &lt;function&gt; defined @SexyMap\Borders.lua:1071
  }
  preset = "Blue Rune Circles"
  (*temporary) = nil
  (*temporary) = nil
  (*temporary) = nil
  (*temporary) = nil
  (*temporary) = "attempt to index global 'MinimapStyleShowString' (a nil value)"
  mod = &lt;table&gt; {
   UpdateBorder = &lt;function&gt; defined @SexyMap\Borders.lua:1088
   CreateBorderFromParams = &lt;function&gt; defined @SexyMap\Borders.lua:968
   ClearWidgets = &lt;function&gt; defined @SexyMap\Borders.lua:1013
   UpdateBackdrop = &lt;function&gt; defined @SexyMap\Borders.lua:1096
   NewBorder = &lt;function&gt; defined @SexyMap\Borders.lua:944
   db = &lt;table&gt; {
   }
   OnDisable = &lt;function&gt; defined @SexyMap\Borders.lua:911
   presets = &lt;table&gt; {
   }
   StartRotations = &lt;function&gt; defined @SexyMap\Borders.lua:1034
   ApplyPreset = &lt;function&gt; defined @SexyMap\Borders.lua:932
   GetSequenceOfBorderPresets = &lt;function&gt; defined @SexyMap\Borders.lua:1112
   SavePresetAs = &lt;function&gt; defined @SexyMap\Borders.lua:950
   OnEnable = &lt;function&gt; defined @SexyMap\Borders.lua:859
   Clear = &lt;function&gt; defined @SexyMap\Borders.lua:925
   RebuildPresets = &lt;function&gt; defined @SexyMap\Borders.lua:915
   ApplySettings = &lt;function&gt; defined @SexyMap\Borders.lua:1071
  }
  sm = &lt;table&gt; {
   ping = &lt;table&gt; {
   }
   coordinates = &lt;table&gt; {
   }
   borderPresets = &lt;table&gt; {
   }
   buttons = &lt;table&gt; {
   }
   hudmap = &lt;table&gt; {
   }
   backdrop = &lt;table&gt; {
   }
   shapes = &lt;table&gt; {
   }
   core = &lt;table&gt; {
   }
   zonetext = &lt;table&gt; {
   }
   clock = &lt;table&gt; {
   }
   L = &lt;table&gt; {
   }
   movers = &lt;table&gt; {
   }
   borders = &lt;table&gt; {
   }
  }
  defaults = &lt;table&gt; {
   backdrop = &lt;table&gt; {
   }
  }
</code></pre>

<h1>BigFootBar addon error</h1>
<pre><code>
  1x [ADDON_ACTION_BLOCKED] 插件 'BigFootBar' 尝试调用保护功能 'BigFootBarFrame1ActionButton1:Show()'。
  [string "@!BugGrabber\BugGrabber.lua"]:519: in function &lt;!BugGrabber\BugGrabber.lua:519&gt;
  [string "=[C]"]: in function `Show'
  [string "@FrameXML\ActionButton.lua"]:350: in function `Update'
  [string "@BigFootBar\BigFootBar.lua"]:1: in function `BigFootActionButton_OnEvent'
  [string "@BigFootBar\BigFootBar.lua"]:1: in function &lt;BigFootBar\BigFootBar.lua:1&gt;
</code></pre>
</details>

Also, I made a record of the issue (note Hekili recommendation at bottom right corner disappears after sorting the bug):

https://youtu.be/O3KD5ZYY6vo

### How to Reproduce

1. Enter the game as an Outlaw Rogue
2. Kill some NPCs to pick some items, an equipment item and a Vendor Trash required at least
3. Sell Vendor Trash
4. Sort your bag
5. Hekili should crash now

### Player Information (Link)

https://pastebin.com/wsqmWVXs

### Error Messages (Link)

https://pastebin.com/qUNg1qpn

### Additional Information

Hekili version: v9.2.5-1.0.5

Please ask me to provide any more information for troubleshooting if the above information is insufficient. I'm glad to follow up.

**Comment by Hekili** [comment]
This should be addressed in the next release.
