### ISSUE TITLE
Issues after update

### ISSUE THREAD

**Issue by Clenzo** [Hekili/hekili#156]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Clenzo** [comment]
Just updated to the 8.2 version and now its throwing errors non stop. 
here is the error


Message: Interface\AddOns\Hekili\State.lua:1079: bad argument #1 to 'wipe' (table expected, got nil)
Time: Fri Jun 28 23:47:38 2019
Count: 3198
Stack: Interface\AddOns\Hekili\State.lua:1079: bad argument #1 to 'wipe' (table expected, got nil)
[C]: ?
[C]: ?
Interface\AddOns\Hekili\State.lua:1079: in function <Interface\AddOns\Hekili\State.lua:1061>
Interface\AddOns\Hekili\State.lua:1231: in function `gain'
Interface\AddOns\Hekili\Classes\WarriorFury.lua:416: in function `handler'
Interface\AddOns\Hekili\State.lua:4765: in function `RunHandler'
Interface\AddOns\Hekili\Core.lua:1249: in function `ProcessHooks'
Interface\AddOns\Hekili\UI.lua:838: in function <Interface\AddOns\Hekili\UI.lua:702>

Locals:

**Comment by Hekili** [comment]
Please fill out the ticket properly.

**Comment by Clenzo** [comment]
I cant all it does is pop up I have to disable addon in order for me to do anything I was able to grab this on the last attempt b4 the error pop up happened again and the count shot up to 5k 

build: v8.2.0-03
level: 120 (120)
class: WARRIOR
spec: fury

talents: bladestorm
    fresh_meat
    frothing_berserker
    inner_rage
    siegebreaker
    storm_bolt
    warpaint

azerite: azerite_empowered=3
    blood_siphon=1
    gathering_storm=2
    impassive_visage=1
    overwhelming_power=2
    pulverizing_blows=1
    resounding_protection=2
    simmering_rage=1
    unbridled_ferocity=1

essences: [the_crucible_of_flame]=1, none

sets/legendaries/artifacts: none

gear:     boots_of_the_dark_iron_raider=1
    boralus_sailors_cloak=1
    dooms_fury=1
    girdle_of_burgeoning_apathy=1
    golden_empire_signet=1
    heart_of_azeroth=1
    honorbound_centurions_breastplate=1
    honorbound_decapitator=1
    pocketsized_computation_device=1
    poens_deepsea_handguards=1
    sinister_gladiators_greatsword=1
    sinister_gladiators_ring=1
    zanjir_scaleguard_faceguard=1
    zanjir_scaleguard_legplates=1
    zanjir_scaleguard_shoulderplates=1
    zanjir_scaleguard_vambraces=1

itemIDs: 158075, 158152, 158159, 159450, 161463, 163874, 165030, 165052, 165563, 167555, 167778, 167781, 169815, 170110, 170336, 170537

**Comment by Hekili** [comment]
Thanks, should be addressed in -04.
