### ISSUE TITLE
[REC] WARRIOR/FURY - CONDEMN RECOMMENDED WITHOUT HEALTH CONDITIONS MET

### ISSUE THREAD

**Issue by gblnunes** [Hekili/hekili#1560]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Warrior Fury, when I have an primary target if less than 80% or more than 20%, Condemn still being recommended.

### How to Reproduce

1. Enter the game as a Warrior Fury
2. Select Display Mode on Hekili as Single
3. Hit an opponent until less than 80% or more than 20% health, Condemn will appear as a recommendation.

### Snapshot (Link)

https://pastebin.com/c7bRwy5a

**Comment by gblnunes** [comment]
Any updates? :/.

**Comment by Hekili** [comment]
This will be fixed in the next release.
