### ISSUE TITLE
Only one icon works for Deathknight - no error message

### ISSUE THREAD

**Issue by byllam824** [Hekili/hekili#1563]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Only one icon works for Unholy Deathknight - "Raise Dead". Addon works correctly with 3 other characters.

### How to Reproduce

Enter game as Unholy Deathknight.
Attack target dummy.
Only Raise Dead icon works

### Player Information (Link)

https://pastebin.com/hyxVKjV1

### Error Messages (Link)

Get no error message!

### Contact Information

byllam824@yahoo.com

**Comment by Hekili** [comment]
Please submit a snapshot of your Primary display via Pastebin. (Yes, even as it displays nothing.)

See your Toggles tab for the snapshot keybind.

**Comment by Hekili** [comment]
I am not able to replicate this issue with the same settings that you are using.

**Comment by byllam824** [comment]
"C:\Users\bylla\OneDrive\Pictures\hekili.jpg"

    On Saturday, July 23, 2022 at 04:03:30 PM EDT, Hekili ***@***.***> wrote:  
 
 


Please submit a snapshot of your Primary display via Pastebin. (Yes, even as it displays nothing.)

See your Toggles tab for the snapshot keybind.
