### ISSUE TITLE
[BUG] HasVehicleActionBar seems broken

### ISSUE THREAD

**Issue by gaveer** [Hekili/hekili#1564]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

@Hekili 
i have issue with **Visibility** of the displey when doing Puzzles quest in Zereth Mortis 
- i use **bartender 4 ** addon
![image](https://user-images.githubusercontent.com/45834601/180625527-296cc86e-19e0-4944-98b6-2a1e7eb6fe3d.png)

- My displey in middle of screen
-------------------------------------------------
- **Edit** : 
press ESC ones seems remove the displey 

### How to Reproduce

Starting Zereth Mortis Puzzles 

### Player Information (Link)

https://pastebin.com/eJhundaG

### Error Messages (Link)

no error

**Comment by Hekili** [comment]
Thanks, this will be addressed in the next release; these are technically override action bars and not vehicle action bars.

**Comment by gaveer** [comment]
ty <3
