### ISSUE TITLE
Survival Core has completely disappeared.

### ISSUE THREAD

**Issue by Leondis** [Hekili/hekili#1565]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I updated to version 9.2.5-1.0.6 and when I entered combat as survival my addon broke and completely removed the core of survival. BM and MM still work correctly. When I'm BM, I can look at the core and it shows a drop down option for survival, but when I switch to survival it is enabled and just shows (none) 
![WoWScrnShot_072422_025133](https://user-images.githubusercontent.com/109894504/180637681-1d321274-ef3d-4d14-bd97-7bfb34bc00b8.jpg)
![WoWScrnShot_072422_020141](https://user-images.githubusercontent.com/109894504/180637682-e26c926d-5141-4a34-80b6-aeda25e6c069.jpg)
![image](https://user-images.githubusercontent.com/109894504/180638216-07718403-e9c3-460a-9988-909888dd038a.png)

### How to Reproduce

Enter the game on a hunter as survival spec. The rotation helper does not exist.

### Player Information (Link)

https://pastebin.com/KctSjQ1k

### Error Messages (Link)

There are no bugsack errors.

### Contact Information

Leondis#5143

**Comment by cypiate** [comment]
Have same problem

**Comment by jinyoung-lee7** [comment]
Me too, have same problem. Please fix.

**Comment by parwiz7** [comment]
same

**Comment by esipaland** [comment]
Hekili help us to fix this

**Comment by elsavira** [comment]
You seem to have unfortunately registered the BM Pack for survival in [this commit](https://github.com/Hekili/hekili/commit/db3af85058a45e2418adefddb26d46d91040738c)

Changing line 1426 of Classes/HunterSurvival.lua to `spec:RegisterPack( "Survival", 20220724, [[Hekili:T3t7YnUns(SOkv4inJhns0wZmBolTv2S3TxMlx2RItv79llrlrzX1sKAjPShNsLE2Vga8daWUbaLKNj7v7wBLela0Or3n6VqdWBhE7VE7nlcYdV9N9h47p4d(x1F4OrdU8QBVj)5TH3EZ2G5peCp8FehSb(N3Sl9XOhdwZA451jblyailzx6COXV5WSv55BZ(U39U7JYxT7U(Zt28USOn7whKhLeppnyzo7VN)UBV5UDrRZ)X4BVthbU9MGD5RssHjlAZpC7nRIwSiu0VWS51OWHz)N7IZdtp8PpTlo8Wm)RUa(haqo8PdF6hsIFmmn)WSLjZ3LDywc8xZd2Ey28vHZFa(H8KdZsdZ2goh6uC4tqlRdYGgYcZZJIVh(VE3Hz7YclBLnUPCOnTcyHFElaJmyP1)2BwhLLNXihWVbR77cYH)4N5u4W4G7whU42)0T3KSfOxH5rlV9M5Pra6hfaK6G1HX593KeFFssw407Gg6xoi(YonAlJcE7nFfwypgKovW93C300SPZtYYbM0CbcbTgXqu2)16DHtdxNfw2A)0GT5jPtZYtJEiSVyG8Uv1d11mVh5GSaJQvodz72a9A62WCzkj0RlL71Dj55qltxUo45WfpbR0P5jFokwBmxjpMLRdZwXLk161inUwnRkfK1wMKEFyFqQFn))AA4M7ctZ6h(p2fTDlJJvc)CGYLd0agiFVYskpmCTOjLjgWJ48Gk5gBDxqNqXZohMD3ULl7)u06ftZ2gbnK1pnCtqumibSFVXM9aXIKK1lsEkU)drRxdS8nBcIxu2djkyAy4VXP1flZl)AJrs08C2ENLb7wJUtuE7hWfZ7NSlplAr4h5Zw5UL(WoLPRcs3MKeZBGJKb89xttwonFfW)dUFDyFgUvJgfdPHW8MD)2VX2S0uqMIOvGDrzt3YeTtLwQPbXGm36iohiBvsUMYI)cOliyvyWc4Ffd)JFTAaWU)F()5hGn6XHBIcZanNpb)0IK4xLZ(xWSUkkJPKj9WmX0c)1DHZd4koIYF1c2FY02a9nBBWMnpxmhm4mpGdNuyMJw)CX8Y6x48OLrZfeXS(v7hLw6cfn)9K8DX3hgLMofwqaJ4zqTtW611RD6Eut8y99rG9iwJhMn(WSHCEy3c2iisLUikgm)SykOJKjP0F3wHWyhjjoS(Pk5MKjesZJ2ec6DMUicidxFy2LdomRNOpWKQJqtkrio2aACtG5GXldsttEQcvmIR9Q0xvsAysSajytMMu27jLYMdk(Jdalqp8m83XQB3mU4L7yd8xHeXPNh30uV0yC4PI)ykZERWQBH1jWit8dHGnyyT(bT1Qtay(c(y)ijDsN)XyWc2UWa(DrPlYyAfaRNpxBaNz(BEotdKB4XDjCvP)H2JhDo3OIWC8WboJkGiTF7NM5RddEmKpvkg(ca3rIzBOstHfvdBLfddr5ELLZW0TWiNY0qCpIlxREErAqMIdx1BiFmAlO3Bki0MSrrK3qRaR4(5aHE(ZaYnvO7oJHF2SwNgeTyA4JmKkyXcWBIpZ8NuS3rVTQzBctL2arNAWjg3CGZtaxMpm71CMujns2IRvRrhnA(Xtel11UGz848GPNmbfrvMzNkxUd2BarnSIjUmLzdPuqsYaWMGftVJfxba7W0AJdLMEwgD)Q8PYcIJu5XlJsd5qWMXGcnYkJPVa5YMUmvatwayWCOSdpvShwx5BnS7YvrDCCgy9Cu8LkdWOr6iuAw7v)Db3Z0AUzxCeBvH5v)IWG8vtb6XdPbBmBWOgUXSWPIV)PGuWrfM)PB5sYB3gKgKVREAeSsrSDa5Tm6Q(YHE1wTRSqkkTNunab6R7JGbn9lsY7NTcW8yiweUirE08hGvrPlvSoeXIihKnMcJpe2dCF)S8G5pWxl(c2qt4OP8K5ttDyD7Yb(w6Z12gocKRd3FE43JbkDoS7X)Jt93ohr0DiToASnamRD9hP6iJ62gST2t4Ucd)EH5bEe5(eRzATXiYZsbMToi(bEyb8yV5GsxDzzFLdOsNOUfqKei87WMuvmsAj5gxJfUzXH0kg5GzPi(JPBcsFGdef8Mh2ddk6A0KOepdkIfHhHo)06R6iexvzPoizHRlRupNy7cH80W((8EG4y1vL6Xig4vud8sld89v6inOD2ZaamzPziT6rH5G4WpNp9PibXTCtCf6u4OwfyJIxUJNyQk3169IU)J2l8Z4mwP)Xxx)RT9Oug1m5sHq(7iTnvTQvs9dEeHL5IPrKGhZC3JWPA1agal3Plctz2WNdEjQBFZ3K(DdQtLYahdk6kLR6gv4gPHa5kBfBaYbmsf(rroFuYMaid9rcsGssnfYsAlBDvShRy1)psUrjHS1Ms0iCujsWfonXeRRpSeKkPcNyS6AJkhRsI2rhBUiVchtSYMdgURdXdxypuEtafB5mjOYrjqiXKmsziuDLs3l4hDYt6WJ1PcFYFdl7MzS4SUpmMV84na(68zEJdhuAqYvmWXU6uggU0fzA6OMpgJj0XNAWNaAp(ARtTk7IvC1tznt7I3XOs5flenAxLmsxAerQRQju3ItLIzpdPGwwSCiluOxBq8Sr0LuQ((sJxTYhIgXi6g1npAB5bgb(cgKwgz8yW)Cc0IYndsYvHBfbR3UkGL53fbacP4zrP26kqSCx6Zkut1wKPJfY8VJdfeX(dZERQ2XELKDs19nIj1UYiwmbQjEWM6jRrXzADpbh(VLF0nVUnZshZturey6NG0WpwoysOBk4lhD8tN14aFOBB9iRukuYAkU6tU0IYbz(Jlpm75KDvNq5QGhzNGz9m(Qm(PmYNZdZ((Yj9cWYE0MTSZGKjxEy2)fSSpm7heR7dZIkH7tc4wT(yh27)HahxMMSHnXCiNL0)WmjSXDuPyiGTPDRxygDsROpSZG9UqWJe2bYYoyvo1jb62)DHq0Hz)jGrb)gmOFHR)5WSBQt5dvsroD2)rW4DikGjIn0NIIgBHsCUMIUYPNOo(qv5CdnlJLsTFEXt9ns)TO8vUjTMeZ21qkGYWvOxbPHInlLlfyhxciQM(uet2mlpzlRyJ4aNewZ3XpEVQfBWgr27zs)q0e7UFLOSMY2bMmJIl2lu2l2UbHo51HlZlQzHG4NfTOGTmGac9muE5YAC2ssaBrIbAKRlRXwXtCTCJ91tvqhhkwb729PGQUFaeMPvo7GghfNwmZdK7SYPlQ1r685BErl5un(rTzinpeE)OgINa8QvAK8MSjkH9zPgnO8BZuIKShpFrwFqxJn9uqjReKElqMMOwKAacriwU3xKHL(HgEVc)1gEPlegFFW9HBy)MSOCTVdv8GAmvVUROLbSXSUBDsYcUasvK1hpWcINhcmZG1IIuYyu4obqgFJJHvHtx2YA25aNn9VVBX9BAu0eUCUVks9ezZMhkvfLsCMPSqEFaT6BCATr4(7LsZdiLfMY94Tmw5QDwyLvhDQ7nCO5(JAXg6Tj8)nwOT1twxzr2puuCbUu3tshiAPhhSIo9UiGVSfSfUd2KfMUJBAx1TJQU9ycR0RH(LLS(r9nsInV69GHvkhbRCvYYpFx2uoLxbZRcIJdxdmeVoKywDa2UADvZ)sYcTL3VMo4jDmh1UBUg8ubTlKLLhwPguvbH6zMFKsKULuo56)LmRbCuZfks1kDxlPqA46v1jdbyDHtz)hGMFSeouJu0ucKJQ4KYvGwqkvNVlTcZVg4wdt5gof7Vg4NQdeyHckB3LJglIa3Rb7uIkQ59sgVAwTZcl6zwkSAlPoWqzaH0CPuV2pVyxk)YLW9BtVXirk6hvLDfhbQCqyxnOMs0irRuBQjDyQipoQU8lNLiIJ(7dseot1LHPYfZt7S2RGrf5bZDojtfwpHhYYHOodwTFLJ7(7LLIE5o5aT75ITIq)YrMPAUKq7c61IQpqu7vV26b2qMLwTlnd1HSqRb8O3T3942W7paF7ErzbkuaFkQekiJuL9)WbgIw2Ox4hnL6CsMCGe4BJe4pGihagJpWYYV6geeZ9BFzqOQBE03TOoKdg3y0jqvV80PQeiupl08lhynZih5jmICYRkPeY6zMrhEKDnwEMkYokvz2mh5W5gzW9ffn4LHqXB0SnolP7ZIXbQK2vIvNNQy4T2Z)1R5gI6zxIKxoe3sNXPgbgQ47ps9EqYpTuSQDAznPQCP9OQKIweVu1v9s5mZsFEDWdGX91peY9TpEjyGAr9(mSYpVUwLDpIOtD2BQLTT17ONPAELxd1m5idLXnvnHFKLsIwE7PoNS)j8K2Le2TCvBjMFt(VsSBHQk5O2fBP6ur5COtm15TCkU)BuqKapOt1ObirMlbYQa2LQouOhMmksQW8WxygoIgIY22Rs6DcHOR4s5qymu52(OksB(kC08WmuuHtCFxipaMwuVHeuoATZhJgytluQtTXCvvDEpdmw9WyxjELWhMMjc6iLQzxoImJ3eTJYhotEO1OnIDfJQQr0wlvNlDnNPFDrQhV2RZrbR)yUP5YVdizphpF6UTyjaZogGDlWPXkpho9B5y70bQdlM80e2gU61KUobP3SfSvfgGQfPv30HHoIhoc5xpfxoCOP3VlmltIQA9w4F9F0TJDQaY5npJYxycHGV8YsgWYtLRllI1JMS3l)AauI0AwPUw0S1jS6XOqzIuzkx)lkkl7YkIgEl9Zh2Fvq2u2ZmbJvQLzgPnGAdOeHLooZk)du3ew2mXg7osG23rCP5yQrh2yKAuI(l5Xm5QVcvnItsdVc(1jtIDGlyyqDp6HIf1RblKfVZgg0XfUMj8ORnu5TCF)Klnu5DEcSGOPj2G97KVq4UJLNDI5VROdA8mST3MxnkRx05RxJLSY(SGfpRswrNgbbzc5Q2JSLRTb63vD907ydhjxefZfcBRP9qnKfRdfPd(CjP0wCwhzTYAyP67nM4aMxUNU0CtiiLZChw(tSHIhjRGA1Agqx3O4KSkX8gBWCsdyQlXJBC7fIVO9)50e8kIGab650cGWlIUwna0vZAxjQBvEAszjhyJ8vEEpTv6uNkGqiWxsNp3GoEdb9KinQSUOS(ZdMVkKLCUG5)JDqGVlMMdQEZ2LgwGa6P2(6YSjXdROAupXsxrjZYu6WjgwpSZPu1Pz)gon7BWPzxDuLK9CgDA2vh4BogcPLH2LwSjn(c51bcwuVgSqwSA1ZzmODonJRe2mQyZcUJMxn4CeEeigWYZoX83v0HVmX8r7YbItZgCi5uDA2I59o2WrYfXxeNMpAjL2IZKontXA(Y40SLqES70m9YVTon7kRWQtZOa6eDAgxVKvNMXnU9cXxEjCAgzb4GtZ4gaCYPzm5PJ3PzhLoDWPz75270Cd64neq50S)V7CAw)i5p5x05CX5E9yyk7D)6wPpuapfKgZQ3PBV5V99)Yp)J)8F57om7WSFLD7qJ2SnjT82G(QcYv2RyxesbwZUKmSYoiyxEYgwUZ5vNcGaz9p8PFkIDEEV)7yxxv(7TpRz2NJayuphNZoWZV9a)6K(t7comBr0JrzCovY2W0a(LWU77a(v3rFUhf4krQ(d7))(kbWELKGc7366FLdJ3hz8(fJ)9sJ)dN3LZhoILJb0XPLJGCC4twy3vFbgAh)EOogjQXNA0P4VllZh43dG58F)V(taUn0nulRT40OtNR5iQnFrl3FmCGgbR6oGvrYQ)fjIwxFjXGHxEUwGfW7QZm8(YXaUlzBlzaNBAN2A9v1vQsfhv6NKzPkG5mO48sdWZLnMQYy6a4ixxF8iWdh59INY8wY(9pD6SP13jdV)W5cEh(0pYPwmO8XYst6Wm(NChOz23CNKLrSJR)BGPPXhii4hfFJGK)eb9nv4wvT5uvQ0VuFmDyZRa5Z6xzK6nJFxPtQxWCwACDXYDrY2X8kt4cETbmUOMSA(rZ5I6AoOStPn(27CX8K4f8N16XyFXHWrT6V(o4Tt9D3bV313Ly82lVJRxeTCSl3VvCuUQ2ELO3JlEzayqUiGPYp4lEyFSx8e(4s8HEPcSW0jU75CbkN)GR8V9v5dUImw38JhdJY0PG0u91MrEiLFyresPu(RZaJASdJh61LtnNJw0p733PkMhSEuek1(9SBzGNuuUxF5GE733vDYMmuW5qQMmac0yrpSvAgWvb26FoeOfaZjyoVgafVPmls2DhqZbvmrRlECNeVfuB3b)8Vun9hM99S5NnaXZJtQ4TVP4bDQmqYOScM76e2yyAEwGnT)z20w8iufZl7WebWY4GRydEwXtZdtPIayBGnWZEkceZIlMBwUNYczdjJ925e(uWZxu0uw0g(8YI7tAARSgfXy0p3xqDQjBGoqEbSoLr8x)yituOYdq9glKjq5tsHrJxcutgoy)(M5946HVxHpQ)MlkKClJgKHEAj5WZfjrpROhxKU9a2oQd(OBVtGFKxWu7ppF8WM7gV(sptFJySdE4FBe6DonWl8eYWumXxgiQFIyKnWEh34Puv8EHsnclanxge7InxiEI1013pFX(9sLCFpLjfqk5IMgBwr8tqO1Y67flOVZ0T8A)E(F(M6c1(6QI0(ndh0ZXzXPUjrnqx)mBk6nOupZuuIM3oebfNJunVQFAtH2vvKysqgv5TAwVjCXuWjwfz0w8E4v48IhhHUUkbLs3rcnmq5zhWXfKI7FKs(42c9iBRKNpS)OxJW3v8N8l1K24UNECKc8lf04lB9A04vdRqTI(LVWd5xlx2C2832fro5T1BZ7XOmn0d502TofxUbVUuB86q(0JAaVN0eAVD4RTbVo0ae81tXu)h9OHd3B8)1RgA7F1qphwY62XzLHf2RWuc2JZd)xpyLipyLNdMKZSOApxrFZwN0Tf6NQHvU2Z2v7at3onEyvzHdO9t1ZwZ3x1wnFn0RwdphTgB1puJpmafAfPcFg1GJxZX34g)PBNulAgmRjLxAVgoj1e345tWaIB2WAPzzDKU0dxXyPUEItQ861yq)TYtbRgxn(SB2AjIMHFStoFw9HqbvZPLThpZc)nRV0MYGcWO6h8slEQPpq1h3Ywo4QhYYwooTN5Yglg53KsrG(f6cS88worXdZcGv9WtAbj18q5sDavMQq1Fv8ksYbnldxkvBY1(JCucUGCwLG1lKFRgh70t1idfe6fV(ddKYcJjNYf6Jjb5(9KVfLcFhrF)j7PVSKZlSzRzK5k2t3Kdd1LmUj)crYBQrIf3Vx9xgpuoBKtgP5cEjdbG7ffp0IJ9hrTcYRFDhDB1inZx9AeH2QyWBMbfgI3m3zUBqSHyTUM7x2Ptvl9l(0HCgacfU85O8vtCY43RODMNfl75FI(dbMhDQPmMzkDCqZWn3Qm(BS1(9eVnvtgZs3Q22HXOpUAV2hz(1DS44WHpEkOaL)jTglonkrdFgAxUUkodevleJWwUShjifZEQoM08H456HiGPrIN62Ac2iNjxq89OPNWHpoVOuGVEzTRgjkE1rqAQ8rmQY5FSxmdVUg(O6ET)(9KFmDVwZwudbd65Sd6BSL5vqt5Pj(9h5ri9H41LYZf13IT1PT51TAG2IoM(LdZdJsugmfDEOvN5stW8rP9TSfFzwMiA6aqO1Nyk1AyRMMBCfBO96IWsh233tBZ8vSnTiD8k9oEjrhFpSTNqPIh6aWu3jlk2Td6BWcml2(uY27SkVAtf8rbuBYYUFCkEDpcDFMtfeD2DyS4wpByQVmKR)Q(0IKZupgB(PjNnfd(S10XZjFKs24mXE)Ns(iYbeEu8cKHB88zWCo1CoFQhb47Wy5sls63z6TLPKCnXCf(yp0vfE3H1KhEAk0RpGI5uoQ4xKPREcZYh7YPq6r7GyJgyb6s886(MMpTUxpQxtBviGO0VZRgiJ8Uiw1H8z)cBB9hGLkTNduoW7H)2H1RO)AP7ZCGEajf3)K2To0itOheoVLwffhg3UBBy3(dAYU5bkmEyBfeqQCSH6shohI8PkgJTUmG9(yyVVo232OBB(uyR66ttviDqgsZ96TKwCz7Pfitzp0kdSPyDRIEGpidEBuj0ylAEFwkLqdKGoiF891KhppQEy0x3qpAvdgpaQ97X1BrCWsEhDnk9wb9L6yDE9L9W42dh0tJZyZrkucSHabTgZx9SIO5SkuaTyIgkNCd3Flq1GUCWpNNj4yJdcnOr)(JWYtrbLvNX1cN359)3XvJJNvxYqNbkxeAPeoruF2POg9hUkrguvlLbwTroNPms1wh5uJvRPhp4oBzt3oAwfezdCcI0WR9rvPwKuuH8H5eTjuD0idIoX9TZMBS(ogffTDZ4z5e9F7qtkumeTtBe0TrTAR9vklOA)UMC1Ob9OKsQrWYYzFS6TiQ4M3xCZH4eL2ENiAohVr)UkP(A2umz61(o1KtxYNf3keeWCwW0cbI6Rxv9nJsBsRwrwQ4)R)JUCA5I3Jv5lRvlgvKHspqTQW(krdEbwxUXzFzwotEXzPORTQ7E0f8NBSYBRcx)z3U5v3YE5xQcPi6k2RO2VsuQNxx0xdfMl7n2U1jV6g5BEU06y5KTFF9VlrSlCacFHWQSpIzTEavaRm2YjJrMPYg7PpxL9GAb6DcZuhAYlXK11WS92rxJ(8LSFp6ppXaO(w)EY8dku4Sqh(IUMQjS6BjmGH1Opcy7vJ)6paSEgG5BhnbDf4H(RxBasFRp7WQOqbCKJdufABtv9EMACI)GJKV5i(iJiMiJdh8gCkMjS)OKE0hepvsMwntmsDDM6HH(gg71kL7HrM4BmTLvbmssy6AGppus()d9oAIc)E0iuddtDP0J1TJoAyIFozupQflltJokiiVg6PSV1ODT2zKS1QW61ZtwXO53ik9k05A)Il)U2d8uJk5zyrko07yV24yJVQJn2C2aNmECo2yZjkTo2KN18b)I2i753oL(Cv2dQfOj1U2MjhCSrxpIHz7yDca1yzdh8WqHZcD4l6A6fWtyutuQo2GA76OCSHWqrhsuah5oVo20k(MJ4dMJnyKXxehBiCF0GJnyRghDSXg1ZKJniJ9yCSbBllLJn6AGppuYtWXgFxDSrxpMjhBAYpD0Xglccuo2qgW(XyKS1QWuCSX2JF5xyhBm)U4C7nS7ra7Z13i(dA5T)Fp]] )` should fix this.

**Comment by Hekili** [comment]
I'll post a fix after lunch. Thanks.

**Comment by ghost** [comment]
I tried to uninstall and install the last version and still had the same issue.

**Comment by vyktir** [comment]
Just copy the profile and switch to survival in your copy and make it your active profile. Takes a few seconds.

**Comment by Renai-glitch** [comment]
How?

**Comment by esipaland** [comment]
pls say step by step until fix it

**Comment by TheForbiddenToegang** [comment]
same here ...

**Comment by Hekili** [comment]
1.0.6a will be published soon.  You'll be able to download it [here](https://github.com/Hekili/hekili/releases/tag/v9.2.5-1.0.6a) in a few minutes.  It will land on Wago/CurseForge/WoWInterface shortly after.  Thanks for the reports.

**Comment by vyktir** [comment]
Removed by Hekili.

**Comment by Hekili** [comment]
I removed vyktir's instructions to add your own sim profile because 99 times out of 100, you will only lose functionality by importing from SimulationCraft.  The default profiles are translated from SimC and have a few optimizations to function better in-game, which you lose if you import your own.

By and large, your sim profile's action list *does not* change based on your gear/talents/etc., it is not customized for your character to any meaningful extent.  In a few cases, some trinket lines will be added/removed based on your gear, but I incorporate all of them so that you can rely on the default priorities.
