### ISSUE TITLE
[BUG] When queueing as <tank> but sitting in town as <dps>, addon priority shows <dps> in dungeon

### ISSUE THREAD

**Issue by kyatastrophe** [Hekili/hekili#1566]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Happened most recently on a paladin where I was sitting in town as ret spec, queued as tank and the game changed me to prot, so I didn't manually change specs. The addon showed ret priorities.

### How to Reproduce

Enter game as <dps>
Sit in town as <dps>
Queue as <tank> (or vice versa)
Addon gives dps prios

### Player Information (Link)

nooooooooo link sorry

### Error Messages (Link)

nooooooooo link sorry

### Contact Information

Kyatastrophe#1432

**Comment by Hekili** [comment]
I would need a snapshot for this.  What did you queue for?  I just tested on my Paladin and queued for a dungeon, and it didn't swap me.

**Comment by kyatastrophe** [comment]
Might be a chromie time related issue actually now that I think of it. I will test
