### ISSUE TITLE
Many LUA errors, unable to snapshot or submit issues on addon itself

### ISSUE THREAD

**Issue by Machampion** [Hekili/hekili#157]
Sorry I wrote out everything like you asked before, but it didn't save and it took a long while. The accept button is greyed out and the snapshot isn't working at all. I'll paste error info below, I know I probably won't get looked at but here it is:
build: v8.2.0-03
level: 113 (113)
class: WARRIOR
spec: fury

talents: bounding_stride
    carnage
    double_time
    dragon_roar
    fresh_meat
    reckless_abandon
    sudden_death

azerite: azerite_empowered=1
    champion_of_azeroth=1
    gemhide=1

essences: none*, none

sets/legendaries/artifacts: najentuss_vertebrae=1
    sephuzs_secret=1
    tier20=1

gear:     cradle_of_anguish=1
    dregadas_greatsword=1
    heart_of_azeroth=1
    idol_of_voljamba=1
    najentuss_vertebrae=1
    pauldrons_of_the_champion=1
    polished_jade_chestguard=1
    rastari_battlegloves=1
    rastari_stompers=1
    rastari_vambraces=1
    sephuzs_secret=1
    spirit_twisters_band=1
    tidemistress_greatcloak=1
    tier20=1
    titanic_onslaught_greathelm=1
    wildtusk_ivory_headcracker=1
    wracksoul_legplates=1

itemIDs: 121280, 132452, 137087, 137527, 147010, 147190, 155268, 158075, 158424, 159103, 159122, 159150, 159151, 159763, 160918, 161139

Message: Interface\AddOns\Hekili\State.lua:1079: bad argument #1 to 'wipe' (table expected, got nil)
Time: Sat Jun 29 01:01:02 2019
Count: 37855
Stack: Interface\AddOns\Hekili\State.lua:1079: bad argument #1 to 'wipe' (table expected, got nil)
[C]: ?
[C]: ?
Interface\AddOns\Hekili\State.lua:1079: in function <Interface\AddOns\Hekili\State.lua:1061>
Interface\AddOns\Hekili\State.lua:1231: in function `gain'
Interface\AddOns\Hekili\Classes\WarriorFury.lua:416: in function `handler'
Interface\AddOns\Hekili\State.lua:4765: in function `RunHandler'
Interface\AddOns\Hekili\Core.lua:1249: in function `ProcessHooks'
Interface\AddOns\Hekili\UI.lua:838: in function <Interface\AddOns\Hekili\UI.lua:702>

Locals:

**Comment by Hekili** [comment]
Update.
