### ISSUE TITLE
no bars for bear tank. checked UI. they are enabled. 

### ISSUE THREAD

**Issue by zvifflemeyer** [Hekili/hekili#1571]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I play feral. today, i went guardian for a world boss and my bars disappeared. 

### How to Reproduce

1. i went tank. attacked something, had no bars
2. went back feral. had bars
3. went back tank. attacked something else. still no bars
4. checked ui to make sure it was enabled for that spec
5. was eneabled
6. still no bars

### Player Information (Link)

https://pastebin.com/FV8DT7PU

### Error Messages (Link)

none

### Contact Information

zviff#4705 discord

**Comment by Hekili** [comment]
I'm not able to replicate this.  In Guardian spec, please get a snapshot and put it on Pastebin, then link it here.

Did you get BugSack and BugGrabber, and if so, did you have any error messages?

What do your /hekili > Guardian > Core settings look like?  (Screenshot is fine.)

**Comment by zvifflemeyer** [comment]
no error messages but the problem seems to have sorted itself out. Thank you for responding. 
    On Monday, August 1, 2022 at 11:55:38 AM GMT+8, Hekili ***@***.***> wrote:  
 
 


I'm not able to replicate this. In Guardian spec, please get a snapshot and put it on Pastebin, then link it here.

Did you get BugSack and BugGrabber, and if so, did you have any error messages?

What do your /hekili > Guardian > Core settings look like? (Screenshot is fine.)

**Comment by Hekili** [comment]
Thanks for the update.
