### ISSUE TITLE
Enhancement Shaman- Vulperan Racial

### ISSUE THREAD

**Issue by drjeangrey** [Hekili/hekili#1574]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I cannot get the addon to stop recommending the "Bag of Tricks" racial on my Vulperan toons.

### How to Reproduce

1. Enter game as any Vulperan.
2. Enter Combat.
3. Set priority with cooldowns.
4. Remove the Spell from the Enhancement Display Toggles tab.
5. Continue to see it recommended during combat.

### Snapshot (Link)

https://pastebin.com/xe1Fq45A

### Raidbots Sim Report (Link)

*removed partial snapshot text; it should be on pastebin*

### Contact Information

Discord Werio#8888

**Comment by Hekili** [comment]
> Remove the Spell from the Enhancement Display Toggles tab.

![image](https://user-images.githubusercontent.com/9438134/182622226-7496f6a0-c54e-4166-84d3-1b49a5398f1c.png)

Sounds like removing it from the Toggle is, at best, the opposite of what you wanted.

You can disable the ability entirely -- the addon will _never_ recommend it -- via /hekili > Abilities.  Select your Specialization and Bag of Tricks, then check Disable Bag of Tricks.
