### ISSUE TITLE
[RogueOutlaw] Unable to make recommendation(s) in combat (auto-snapshotting)

### ISSUE THREAD

**Issue by maccabe** [Hekili/hekili#1575]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The Issue came with the last patch Season 4
Addon shows recommendations before the fight, During the fight they vanish and dont update anymore. stop fighting brings back recommendations after a while.
No Bugsack messages only the trigger Message from Hekili.

![Before Fight](https://user-images.githubusercontent.com/34674993/182801663-b0a096d4-2ee1-4c2e-a5a2-20623b503dff.png)
![During Fight no more recommendations 1](https://user-images.githubusercontent.com/34674993/182801717-f24bf4a6-55e1-4924-9b01-a601f075b482.png)
![During Fight no more recommendations](https://user-images.githubusercontent.com/34674993/182801730-992b23c2-fe79-41b6-a34b-b12665f7430a.png)
![Fighting stopped](https://user-images.githubusercontent.com/34674993/182801743-5d7caa22-703e-4bfb-909f-c73bfd49902c.png)

### How to Reproduce

1. Enter game as rogue
2. outlaw
3. go to dummy
4. fight

### Player Information (Link)

https://pastebin.com/NgTudkhj

### Error Messages (Link)

https://pastebin.com/WgY4gEd6

### Contact Information

cosima103@gmail.com

**Comment by maccabe** [comment]
Ps:
![Fighting stopped with triggermessage](https://user-images.githubusercontent.com/34674993/182802818-2066a419-92e9-4951-ab06-d65a2ba556ab.png)

**Comment by maccabe** [comment]
Update: the addon works with my other spec "Subtlety" and the other chars on my acc.

**Comment by Hekili** [comment]
If it's automatically creating snapshots, could you provide the snapshots? They're in /hekili > Snapshots.

Is there anything in /Hekili > Warnings?

**Comment by maccabe** [comment]
There is only
Outlaw; Primary - N/A
Outlaw; AOE - N/A
no warnings

**Comment by Hekili** [comment]
Only the first line is visible on that tab.  Press CTRL+A, CTRL+C and see if there's more when you paste it to Pastebin.

**Comment by maccabe** [comment]
Ok. Sry
https://pastebin.com/XLmSaVRJ
https://pastebin.com/6HhJNrSu

**Comment by Hekili** [comment]
You somehow have an internal logic/flow "ability" assigned to a toggle and disabled.

`/dump Hekili.DB.profile.specs[260].abilities.call_action_list.toggle` will tell you what toggle it has been assigned.

I'm guessing you managed to inadvertently add it via /hekili > Outlaw > Toggles > (some section) > Add Ability, so I'll prevent that from occurring again.

You'll probably be fine if you type:

`/run Hekili.DB.profile.specs[260].abilities.call_action_list.toggle = "default"`

**Comment by maccabe** [comment]
Thank you very much. 
This resolved the problem
