### ISSUE TITLE
Windwalker - Touch of Death being recommended even when it's on cooldown

### ISSUE THREAD

**Issue by Cheadstina** [Hekili/hekili#1576]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sometimes Hekili recommmends Touch of Death - even when Touch of Death is on cooldown

I haven't been able to figure out when. 
The picture is not from the exact same situation as the snapshot.

![Touch of Death recommmended](https://user-images.githubusercontent.com/22419320/183147667-75347048-aac9-494d-b91f-8e3ac9af1269.jpg)
.

### How to Reproduce

Monk Windwalker - I haven't been able to figure out when it happens. Doesn't happen all the time.

### Snapshot (Link)

https://pastebin.com/E6zdB3Cm

**Comment by Hekili** [comment]
That's not Touch of Death. It's pressing Storm, Earth, and Fire again to fixate them on a single target.

**Comment by Cheadstina** [comment]
Thank you very much!
Sorry for this post.
