### ISSUE TITLE
[BUG] attempt to compare number with nil (rogue)

### ISSUE THREAD

**Issue by bignoob8** [Hekili/hekili#1578]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Seems another person had a similar issue on shadow priest. I am playing rogue and getting the "too many errors in your ui" message. Playing all 3 rogue specs. Addon works and is great, just drops to 30-40 fps in combat

### How to Reproduce

happens during combat

### Player Information (Link)

https://pastebin.com/5ASWEWgy

### Error Messages (Link)

https://pastebin.com/ab5U8Az6

### Additional Information

are there any settings or features i can tweak or enable/disable that might help with this also?

### Contact Information

disc - Ash#0488  wasn't able to find the hekili discord. would like to join if there is one!

**Comment by Hekili** [comment]
No, but this is already fixed and will be posted soon.  This error doesn't prevent the addon from functioning as normal.

**Comment by bignoob8** [comment]
Awesome. I saw that you told the spriest you already had a fix for this but
just wanted to submit in case it was somewhat different being that we were
two different specs. glad to hear though, thanks for the response and help!
