### ISSUE TITLE
Hekili primary display will not show rotation or only one skill

### ISSUE THREAD

**Issue by mon1800** [Hekili/hekili#1581]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Randomly and periodically the rotation helper will only show one icon or none while in combat and actively attacking targets. I searched for other threads of this nature and found one that was closed where the problem could not be duplicated.

### How to Reproduce

Unholy DK. Normally playing mythic +
[New Text Document (3).txt](https://github.com/Hekili/hekili/files/9316301/New.Text.Document.3.txt)

### Player Information (Link)

https://pastebin.com/5DFaQ0z7

### Error Messages (Link)

none

### Contact Information

schecterfied@gmail.com

**Comment by Hekili** [comment]
I'd recommend resubmitting your ticket as a recommendations issue, and follow the instructions for that ticket to include the snapshots that are generated when the addon cannot make recommendations.

**Comment by Hekili** [comment]
I realize the New Text Document(3).txt actually uploaded and was readable.  I was able to replicate the issue and I believe I have a fix prepped for the next release.  Thanks!
