### ISSUE TITLE
[BUG] Addon doesn't consistently pick up all damaged enemies

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#1584]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When hitting certain enemies, not all are counted by the addon when damaged. 

Usually its fine, in keys etc there is no issue, but on eg NF training dummies it doesnt see all 3, despite all 3 being damaged.

### How to Reproduce

Hit middle dummy, observe that at any 1 time only 2 are "seen" by the addon.

It happens regardless of which pet ability I have on my bar for range detection.

https://i.imgur.com/qX7hJwW.png
https://i.imgur.com/xtnMdg0.png
https://i.imgur.com/aH42yrs.png

### Player Information (Link)

https://pastebin.com/ARNm1BSu

### Error Messages (Link)

-

### Contact Information

dubu#2080

**Comment by Hekili** [comment]
Pet-based detection supercedes damage-based detection, if you're targeting something in range of your pet ability.

**Comment by dubudevs** [comment]
Any chance we can get the option to choose between the higher of the two values?

**Comment by Hekili** [comment]
There's not really a point to that.  You'd just turn off pet-based detection.
