### ISSUE TITLE
[FEATURE] add Fleshrender's Meathook trinket

### ISSUE THREAD

**Issue by MagicHomie5** [Hekili/hekili#1585]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hey, I noticed that the Fleshrender's Meathook trinket is not available on the addon and it's actually my spec's bis, so I'd like it to be added to the addon if possible, thanks.

### Contact Information

discord: MagicHomie#0628

**Comment by dubudevs** [comment]
Many of the new trinkets are not recommended currently

**Comment by MagicHomie5** [comment]
Guess I just have to wait until then

**Comment by Hekili** [comment]
Yeah, if a trinket is missing, reporting them here is the right thing to do.  Thanks.

**Comment by dubudevs** [comment]
Enforcer's Stun Grenade is missing too
