### ISSUE TITLE
[FEATURE] Add Enforcer's Stun Grenade

### ISSUE THREAD

**Issue by Fyurie** [Hekili/hekili#1586]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I had a look through the item list and noticed this was missing. With the buff this reset, it's BiS for several specs. Would be great to have it included. It was also mentioned in the closed #1585 ticket, but I figured creating this fresh issue gives it proper visibility (as well as being the correct procedure).

### Contact Information

Fyurie#1958

**Comment by Fyurie** [comment]
Looking at the commit history, I see https://github.com/Hekili/hekili/commit/72132095c28a1d11b36fa2efede84f4f8e48ce14 is there. Is the build containing this commit just not propagated to Curseforge yet? I can still only download a 9.2.5 release build from there.

If that's the case, just close this ticket. My apologies for not checking the commit history first.

**Comment by Hekili** [comment]
Yeah, this will be enabled in the next release, which will be today or tomorrow.

What spec are you playing?

**Comment by Fyurie** [comment]
Survival. The numbers have looked promising for using it with that spec.

The current APL info suggests it's just popped with every CA, so that's simple enough to deal with without it included right now, but I imagine others will want it to show on their priority lists.

**Comment by dubudevs** [comment]
Bis or close for demo too

**Comment by mrgrimms** [comment]
This has also been showing up on sims for balance druid and feral

**Comment by Hekili** [comment]
This should be resolved in the latest release.
