### ISSUE TITLE
[BUG] Abilities that are added and then removed from toggles disappear from the toggle window permanently

### ISSUE THREAD

**Issue by elsavira** [Hekili/hekili#1587]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

When adding an ability to a toggle, and then removing it from said toggle again afterwards, that ability will never show up in the list again.

It appears that the SavedVariables/Hekili.lua file uses an incorrect formatting here and sets the toggle field to none when these abilitites are removed from a toggle

 `["abilities"] = {
						["spiritwalkers_grace"] = {
							["toggle"] = "none",
						}
					},`

Expected would be to remove the ability entirely from this list, or allow abilities whose toggles are set to ''none'' to still be addable to a different toggle category again.

### Additional Information

You can reproduce this by:
1. adding Spiritwalker's grace to the utility/interrupts toggle
2. removing Spiritwalker's Grace from the utility/interrupts toggle
3. attempting to add Spiritwalker's grace again will show it no longer in the list of custom abilities to add, and the Hekili.lua file with incorrect formatting.

### Contact Information

Elsavira#2556

**Comment by Hekili** [comment]
> When adding an ability to a toggle, and then removing it from said toggle again afterwards, that ability will never show up in the list again.

For your reproduction steps, can you tell me which approach you're taking to add/remove abilities from the toggle?  There are two places:
* /hekili > *Your Specialization; presumably Elemental* > Toggles
* /hekili > Abilities > Require Toggle

**Comment by elsavira** [comment]
Ah yes.

/hekili > Specialization > Toggles

This happens on at least Elemental/Enhancement specs.

**Comment by Hekili** [comment]
This should be resolved in the latest release.
