### ISSUE TITLE
[BUG] Memory leak issue as of 9.2.7

### ISSUE THREAD

**Issue by RyukiResain** [Hekili/hekili#1590]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During normal use of the addon, despite having reinstalled the newest version, I am seeing a consistent 2-3 MB per tick drain on memory. I have tested with all addons enabled and with Hekili being the sole addon loaded and it is the only addon currently experiencing this leak. Functions normally aside from this, but is causing massive lag spikes towards the end of dungeon runs as the addon drains available memory. 
I don't have an exceptional amount of things running as I am not addon heavy, and use a single visible recommendation node.

![528 cap](https://user-images.githubusercontent.com/111618384/185722265-5ee2c6a5-2fdf-4e56-af40-75bf4770b6ee.JPG)
![529 cap](https://user-images.githubusercontent.com/111618384/185722263-256ab5cc-4af5-4628-bbbc-a9e7b0b85f90.JPG)
![530 cap](https://user-images.githubusercontent.com/111618384/185722267-2baf34d4-f1de-40ab-a90b-a1bc50b83a66.JPG)

### How to Reproduce

1: Load game
2: Sit in any zone
3: Watch addon memory rise infinitely

### Snapshot (Link)

https://pastebin.com/yDYx3kix

**Comment by Hekili** [comment]
What is your assumption that memory usage and lag spikes are related based upon?  Which dungeons?

> a consistent 2-3 MB per tick

What do you mean by tick?

WoW's Lua interpreter will garbage collect as needed.  The alternative is actually using CPU to wipe and reuse tables, which has a larger impact on performance.

Is there another recent version of the addon where you don't see the memory usage (or the lag spikes)?  Which version?
