### ISSUE TITLE
Wrap of Electrostatic Potential not being recommended or shown on any display

### ISSUE THREAD

**Issue by Ohm1989** [Hekili/hekili#1592]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Recently got this item in Mechagon, I have checked the Gear and Items tab for this item and it is not disabled. I have the most recent update and the update from 8-12 says this item was added but it is still not being recommended
![WoWScrnShot_082022_141130](https://user-images.githubusercontent.com/111656270/185760887-ceecde64-087f-4d48-a83c-950efbbb6cf2.jpg)

### How to Reproduce

I don't exactly know what to put in this section I'm not gonna lie haha, but here's another picture of the item in the Hekili interface 
![WoWScrnShot_082022_141542](https://user-images.githubusercontent.com/111656270/185760937-61348ac5-9d73-49ed-8cd7-f28f1292a182.jpg)

### Player Information (Link)

https://pastebin.com/HBXfmUGf

### Error Messages (Link)

https://pastebin.com/CsKTpP6n

**Comment by Hekili** [comment]
This is an issue with recommendations; I need a snapshot of addon recommendations to be able to investigate.
If you have multiple on-use items, put the other one(s) on cooldown and wait for Wraps to be ready to be used, then take a snapshot.  See /hekili > Snapshots for details.

**Comment by Ohm1989** [comment]
Hello, here is the snapshot of recommendations, after making sure the
Skulker's Wing trinket was used and on cooldown. Wraps is still not being
recommended to use.
https://pastebin.com/3uah7Ftv
Also attached is a screen showing the trinket on cooldown and the next 7
spells recommended

**Comment by Hekili** [comment]
You didn't copy the whole snapshot.

**Comment by Ohm1989** [comment]
I'm sorry this process is new to me. Do I use the trinket, press Alt Shift
[ to start the snapshot, then do combat for a few seconds to get a full
snapshot, then Alt Shift P to pause the snapshot, then send that in a
pastebin link?

**Comment by Hekili** [comment]
No, the whole snapshot is instantly created, you just didn't select it all after making it.

![image](https://user-images.githubusercontent.com/9438134/185772498-2a674609-8e60-46ea-9102-45803e1ed92f.png)

Click in the box, press CTRL+A to select all (there are multiple lines, though you can only see one), then hit CTRL+C and paste that to Pastebin.  It'll be *much* longer.  :)

**Comment by Ohm1989** [comment]
https://pastebin.com/k4CxcuGr
there we go, i believe this is correct.

**Comment by Hekili** [comment]
This should be resolved in the latest release.
