### ISSUE TITLE
Hekili does not show key bind on default bar when using Bartender4 

### ISSUE THREAD

**Issue by Mabellah** [Hekili/hekili#1593]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I play a druid. I just switched from elvui to bartender4. When using elvui the keybindings would show in hekili when switching stance bars, but they do not show when using bartender4 and switching stance bars.

The key bindings are set on bar 1/default. When my stance changes bar 1 changes to the bar based on my stance. The keybinding does not show up in Hekili.

![cat 1](https://user-images.githubusercontent.com/111665096/185768675-044a40ea-f226-48d7-9562-2d4f03a2013a.jpg)

When I change the key bind to the stance bar (bar 7) the key bind will show up in Hekili but won't show as bound in the default bar - bar 1
![image](https://user-images.githubusercontent.com/111665096/185768720-f08456b0-9e03-47ce-8ab8-c5f25c51ef09.png)

### Additional Information

I can work around this issue by changing all the key binds to bar 7 (cat), but not an ideal solution since it removes my ability to use the keybindings in any other stance.

**Comment by Hekili** [comment]
Set up your bars however you normally would and then get a snapshot (see /hekili > Snapshots) or grab the information from the Issue Reporting tab and post it here.

Assuming you end up with Rake on bar 7 and your bar 1 changes to bar 7 in Cat Form, I'd also like to know the output of:

`/dump BT4Bar7.disabled`

Thanks!

**Comment by Mabellah** [comment]
Hi Hekili,

Here is the information you requested. Thanks - Mabellah

Snapshot:
Feral; Primary - Prowl(0.00), Rake(0.00), Thrash (Cat)(1.00)

dump result:
dump:value=BT4Bar7.disabled
empty result
 
Issue reporting information
build: v9.2.5-1.0.8
level: 60 (60)
class: DRUID
spec: feral

talents: balance_affinity
    bloodtalons
    mighty_bash
    predator
    primal_wrath
    soul_of_the_forest
    wild_charge

pvptalents: none

covenant: night_fae

conduits: carnivorous_instinct = 10
   condensed_anima_sphere = 11
   conflux_of_elements = 10
   front_of_the_pack = 10
   taste_for_blood = 10
   wellhoned_instincts = 10

soulbinds: [niya]
   bonded_hearts = 1
   called_shot = 1
   grove_invigoration = 1
   niyas_tools_poison = 1
   run_without_tiring = 1
   swift_patrol = 1

sets: none

gear: antecedents_aliform_joggers = 1
    brokers_lucky_coin = 1
    choral_staff = 1
    cinch_of_unity = 1
    cryptic_grips = 1
    cryptic_mask = 1
    cryptic_shoulderpads = 1
    cryptic_trousers = 1
    cypheretched_ring = 1
    cypheretched_torque = 1
    gemstone_of_prismatic_brilliance = 1
    impossibly_ancient_cloak = 1
    lattice_of_the_distant_keeper = 1
    modified_defense_grid = 1
    umbrahide_armguards = 1

legendaries: celestial_spirits = 1
    frenzyband = 1

itemIDs: 172321, 189772, 190351, 190352, 190353, 190354, 190374, 190389, 190465, 190605, 190618, 190619, 190632, 190634, 192450

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Feral
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    delay_berserking = false
    filler_regrowth = false
    owlweave_cat = false

toggles:     cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    barkskin            = AC9 [06]
    berserk             = AC8 [06]
    brutal_slash        =
    convoke_the_spirits = A-  [06]
    cyclone             = AC1 [06]
    dash                = 5   [01], AC4 [06]
    entangling_roots    = 4   [01]
    ferocious_bite      =
    healthstone         = AC= [06]
    maim                =
    mighty_bash         =
    moonfire            = 2   [01], AC2 [06]
    potion              = ACR [02]
    primal_wrath        =
    prowl               = ACP [02]
    rake                =
    regrowth            = 3   [01], AC5 [06]
    remove_corruption   = 6   [01]
    rip                 =
    shred               =
    skull_bash          =
    stampeding_roar     =
    survival_instincts  = AC7 [06]
    swipe               =
    swipe_bear          =
    swipe_cat           =
    teleport_moonglade  = =   [01]
    thrash              =
    thrash_bear         =
    thrash_cat          =
    tigers_fury         =
    typhoon             =
    wrath               = 1   [01]
