### ISSUE TITLE
[FEATURE] Add a general option to activate trinket / offensive CD on boss only. But as an overrride for ALL trinkets/CD.

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [Hekili/hekili#1596]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

For the love of god, please add an option to activate trinkets for boss only that overrides EVERY TRINKET.
This addon is AMAZING, but I hate it every time I loot a new trinket because I have to go spend 10 minutes trying to find it in a freaking long list to have it activated only for boss...

Also please add the same option for offensive CD :)

### Additional Information

Kinda like the bloodlust override in the CD toggle, have an option that overrides every trinket/CD and disables them unless on a boss.

**Comment by Hekili** [comment]
I have been considering this, but am saving it for 10.0 when I do away with the Covenants toggle (probably).  I may allow for a number of overrides to the remaining toggles, including that you're in a boss fight.  TBD.
