### ISSUE TITLE
Does not affect game play, but error pop up for this addon

### ISSUE THREAD

**Issue by kingreboot** [Hekili/hekili#1600]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

not sure?
Error

788x Hekili\Events.lua:1695: bad argument #1 to 'max' (number expected, got nil)
[string "=[C]"]: in function `max'
[string "@Hekili\Events.lua"]:1695: in function <Hekili\Events.lua:1492>
[string "@Hekili\Events.lua"]:1789: in function `handler'
[string "@Hekili\Events.lua"]:51: in function <Hekili\Events.lua:45>

Locals:
(*temporary) = nil
(*temporary) = 0
(*temporary) = "number expected, got nil"

### How to Reproduce

log in?

### Player Information (Link)

https://pastebin.com/CRnMBFVt

### Error Messages (Link)

above, its short 

### Additional Information

Error happens on any character

**Comment by jdm12983** [comment]
Having this same issue suddenly show up on only one of 24 characters so far.

I have used this on at least one of every class and race for the Alliance side; but as soon as I used it on a Vulpera Shaman, this error pops up every time I click any spell.

**Comment by jdm12983** [comment]
To add to my issue:

I went from version 9.2.5-1.0.10-beta1 from Aug 28, 2022 to version 9.2.5-1.0.10 release [that came out a day ago] and my problem went away.

**Comment by Hekili** [comment]
This was corrected in 1.0.10 as noted.  Thanks!
