### ISSUE TITLE
[FEATURE] Enable SpellFlash on DominosActionButton

### ISSUE THREAD

**Issue by jaychang85** [Hekili/hekili#1601]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

FrameNames.Action = {
"VFLButton", -- OpenRDX
**"DominosActionButton", -- Dominos**
}

I just added above line into Hekili\Libs\SpellFlashCore\SpellFlashCore.lua to enable SpellFlash on Dominos Action bar. See if you could update and release.

**Comment by Hekili** [comment]
This would be better solved via modifying SpellFlashCore -- have you put in a ticket for that project?  

https://github.com/Tga123/SpellFlashCore

**Comment by jaychang85** [comment]
Sound good.  Will open ticket to SpellFlashCore.

**Comment by jaychang85** [comment]
look like there is no way to open ticket to SpellFlashCore.

**Comment by Hekili** [comment]
I believe you can submit a pull request without a ticket.  Or you could a while back, when I did so.

**Comment by jaychang85** [comment]
np.  let me try pull request.  no hurry.  Just one line code I need to sync every time you have new update tho.

**Comment by jaychang85** [comment]
https://github.com/Tga123/SpellFlashCore/pull/2
