### ISSUE TITLE
[BUG] Reactive Dual Display - both options stay open  indefinitely after detecting multiple targets

### ISSUE THREAD

**Issue by PaigePB0** [Hekili/hekili#1603]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

It looks like the reactive duel display is showing both displays open even after fight ends?

### How to Reproduce

1. start game
2. go to target dummies, fight a single target, leave  AR & ER: hekili shows one display which goes away after fight
3. got to multiple target dummies. hit them all then stop fight or got to single:

ER: the second display or both should go invisible
AR: both displays stay open

### Player Information (Link)

https://pastebin.com/E2KbycJc

### Error Messages (Link)

https://paste-bin.xyz/21746

### Additional Information

There are no messages in bugsack that I spotted

### Contact Information

Laph#0865

**Comment by Ntropy99** [comment]
Can Confirm. First ability on AOE prompt also seems to get stuck, even when ability on cooldown stays there

**Comment by Hekili** [comment]
Your error messages link does not work.  I'm investigating this issue.

**Comment by PaigePB0** [comment]
Right. I didn't see any lua errors to post but to submit I needed to provide something as a link so I thought I re-posted the previous info, apparently not though.

If there's anything I can do to help diagnose this, please let me know.

**Comment by Hekili** [comment]
A fix will be out today in the next release.

**Comment by PaigePB0** [comment]
Ty!
