### ISSUE TITLE
[REC] Rogue Rotation not recommending Cache (Outlaw)

### ISSUE THREAD

**Issue by Romdiaz123** [Hekili/hekili#1604]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Rogue rotation is not recommending Cache Trinket. Tested on several 5 mins dummies and several m+

### How to Reproduce

Basic rogue rotation with correct trinket Cache of Treasures 

### Snapshot (Link)

https://pastebin.com/0P4QmNTZ

**Comment by assariah** [comment]
Can confirm. noticed the problem today too during the raid

**Comment by 1onar** [comment]
Same here. Cache doesnt show up in hekili. Other Trinkets still work as expexted.

**Comment by Muskatnuzz** [comment]
Same for me with Sub Rogue

**Comment by kkimmikko** [comment]
Same issue. Tried different conditions, even on AoE and Axe active it won't show up. It was fine like week ago or so.

**Comment by CKATEPTb** [comment]
Same

**Comment by Hekili** [comment]
This should be resolved when I post today's release.
