### ISSUE TITLE
MonkBrewmaster stagger.pct doesn't seem to be correct value is 0 1 2

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#1605]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

MonkBrewmaster stagger.pct doesn't seem to be correct value is 0 1 2

### How to Reproduce

MonkBrewmaster stagger.pct doesn't seem to be correct value is 0 1 2

### Snapshot (Link)

no pic

**Comment by Hekili** [comment]
Sorry, this ticket lacks the required information to be explored further.  Closed.
