### ISSUE TITLE
[FEATURE] Please add the swap output variable to the function HEKILI_RECOMMENDATION_UPDATE

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1606]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello, I would like to request the possibility to add another output variable to the HEKILI_RECOMMENDATION_UPDATE function, where so far the output is only spellname and spellID, and this would be information about whether it is necessary to move to another target or not, called swapping. Your addon shows this event with an arrow, but at the moment it's not very readable for some people in quick or hard fights (M+ or raids) and they would like more notification. If the variable was implemented in Weakauras, there are great possibilities to render the event, with sound, giant icon, etc. It would be up to the WA developers how they handle it. I personally need sound in my headphones because I can't keep track of whether an arrow is coming or not, but that's a personal preference. I think releasing this into WA functionality will cost you next to nothing, it's not dangerous in the sense that it will crash your addon and its functionality and on the contrary it will help people.

If this intervention would require rewriting a large part of the code, I am able to sponsor this action with a contribution via paypal.

### Contact Information

Markô#2877

**Comment by Hekili** [comment]
I'll pass this information in the next release.  It will technically pass any "indicator" but it most often references target swapping.  You'll have to take a look at the information that's sent to determine its usefulness.

**Comment by marekCs** [comment]
Thank you very much.
