### ISSUE TITLE
[REC] Blood DK crimson rune weapon legendary does not give 5 stacks of bone shield

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#1607]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon does not account for the 5 stacks of bone shield and bone shield refresh that dancing rune weapon gives when playing the crimson rune weapon legendary causing very wrong recommendations.

### How to Reproduce

play CRW
observe recommendations - stack should be 5 and remaining should be 30s https://i.imgur.com/IccnpYp.png

### Snapshot (Link)

https://pastebin.com/X4Xu21d7

**Comment by Hekili** [comment]
> causing very wrong recommendations.

Tell me more about that.  What is "very wrong" aside from initially anticipating Marrowrend after DRW, but updating when it detects you have Bone Shield stacks?

**Comment by dubudevs** [comment]
One example is using excessive marrowrends before DRW to bring yourself over the desired amount, causing yourself to overcap and waste runes that you want to keep for your DRW window. Casting MR outside DRW should very rarely be done, as it is possible to maintain stacks almost permanently assuming one has a normal amount of haste and remains in combat. On a tanking dummy it is possible to only cast 1 MR in DRW and never drop stacks. 

I am not sure whether the addon can "see" the bone shield extension without having it manually specified in the BDK file, if not that would cause issues too.

I modified the BDK file to correctly apply stacks and extend duration locally to test and see if more changes would be required. Since sims are different from the real game, I suggest making a small tweak to the hekili APL to the effect of preventing MR casts a short time before you cast DRW, which I noticed when testing on a dummy with CRW implemented. I added to the APL a condition that MR should not be cast when DRW has <30s CD unless you have 1 stack or its about to time out, and the behaviour of the addon appears to very closely match correct gameplay. This "30s" would be heavily reduced by CDR generally, but I have not calculated the optimal value for this. I will do some dungeons with my updated version and see how it looks.

Is there a way to calculate the "expected" cooldown of DRW, accounting for close to max bone shield consumption and tombstone if available (similar to demo lock tyrant cd estimation)? This could be used to make the condition more robust.

**Comment by Hekili** [comment]
> One example is using excessive marrowrends before DRW to bring yourself over the desired amount, causing yourself to overcap and waste runes that you want to keep for your DRW window.

Why wouldn't this change apply to the SimC priority?

> I modified the BDK file to correctly apply stacks and extend duration locally to test and see if more changes would be required.

Applying stacks makes sense for Crimson Rune Weapon.  What duration extension are you referencing?

> I added to the APL a condition that MR should not be cast when DRW has <30s CD unless you have 1 stack or its about to time out, and the behaviour of the addon appears to very closely match correct gameplay.

This seems like an appropriate edit to the SimC profile as well, which is also an opportunity to measure it's actual value.

> Is there a way to calculate the "expected" cooldown of DRW, accounting for close to max bone shield consumption and tombstone if available (similar to demo lock tyrant cd estimation)?

`cooldown.dancing_rune_weapon.remains_expected` (or `remains_guess`) will proportionately reduce the remaining cooldown based on how much faster it has recovered than since the actual last cast.  It's a linear function, so it's imperfect (i.e., if all the CDR events proc in short bursts and no more CDR events are going to occur until the CD resets, then it'll be wrong).

**Comment by Hekili** [comment]
DRW will proc the Bone Shield stacks in the next release.  Thanks!

**Comment by dubudevs** [comment]
https://www.raidbots.com/simbot/report/sbUNiW5Fqxx6A9vU9HdD5A

Look between 26 and 46 seconds and compare to this snapshot where I tried to replicate a similar scenario: https://pastebin.com/PfSgfcQf ( specifically line 387, `| buff.bone_shield.stack[1.00] < 5 )` )

As you can see, there is something in the sims that makes it not cast but I am not certain what it is. This is with the CRW effect implemented, using the default profile.

**Comment by Hekili** [comment]
The first several lines of the `standard` list in the addon and SimC need some reconciliation.

Try this:

```
Hekili:vZvFpUTns)pllkohBNn(SSxVBsHLbAtlUl5PxoG6c07VSmTeTTEIER6LDZwyOp73mKusKsKYE3Si3D4k6TwIIC4m)Mz(ndj6gRn)2M1EKC6MpnB6SztFNL1eRzwVDX72So)Xe6M1je3ptoa)reje(3)yqCSh(0hdIjE4xNfxK6cVzTFyraj3po69PK95BwVRWpi)drB2PFfEl8Pjux4XlMUz9rFppkFS0mxX6uU9NOK8JLB))I8pCmV8JRPj50WD00YTwwxxUfNXYpw(X3FKeDGM99LF8nLBxxKKeNMxUDFmmoXe9JX(bLB9JGP8x)9YTz08C)Odt2SoWplpJPfsFWPib(RpXuk0iYUaQ3MFCZA3u)CAQpb3s73pzxCe1j7OpnWBswoOEk3UQC7IYTdk3MwerHFAdIw1V9DDsIFGMoXJU331pN)65tRhpiMhOtGfjmloYbFIZdussC0KkzynXf1RGjjoCxwoS(BYb9MrXCy52osAknK4hLvUDPnFzNK7hsDYJDMxU90PZ9fWuEWf0JVUCRBCCGx8drt2HQwVu)Opd7UukX7XYTJl3MtcOr5QVviMS3Ft52r8LuNCk0OlR0GWyUcxZ7HPaM1iQBACqCQNKqt2fh6hXGEob(H7MuKWwc()y0kGWNgvBijnn(HuAKhQBN3NUf(h3JeWOL1Yut56kR6nOxSqp4Keqouqv1PZKveGVqqGtooT5zIpAhd0wdUelQZ(uUqtc4Rp4qvTtVIlDvAl4)l)4JPSxXuvzpqsbD1bNqa2Z1tnQGMffvb30sfeNaoS08MHFpbuiWBX)kOGYunZwWGiQBMJusAUtwEQ)NPYie2Z3baN2iKzmXcMFhEqh5jWjnXbCvrjCrljSsW8WGgIH317LTj7aXfWB0yOfTG2RQn8enYJK2Vc)dGAWxnnSzRnq25P(1YcbFNh4d(dUGF)nJpsYYzE732hIuvFZ3)KiphpQlbCkX4nnyGQinzUqKBiYJWBb36NzEqW2nT1Z1VhLY7mkLsAvbQD60gzcC7cOzzIOFKG8)uk06nNdAxRuvH3Yk25Qi9kLpkZV1amsYDqAFiYCi7IwB)71hEME7676tJ1eKEwfgTr(KrH4mzn9su()hcsR13efAwY2Q36ghLveMW)rZojh(FRRS8z9NI(kbIITqzoEfCaEDYcPNllL3inKUoiTKF2N3Fk4ALIhjYfrKY51Rx4vvoMD8oaL(7a)J3Oj3GciNfVCopxxJuQmK68zvVTD(svvDNa)sy)4IGD(rEtskYYlcOo00cMXQbpWIIunS7JrcHW4YIdq)vfytLHQ9GCowesII99y6D)iyTXvXXFVKa0(Jugyyi1ZhzCU2QztVhIVC0LZmTzShcI3rcWbQjFIQRyvyK2wRLSqzs6(JqClqYYpsDkIEayIE8rocojL6ce4i56qWiT3uFb0)N)c1Tihvu7q6Hu0jd)q83haKZKYT)GRlqggWqrXrVbigeUVaIZWfc4PXrbpor7UNjkH(5(hyiG(9MGWcb5hNK4MZ2OlMwZxbmFhsJrxlqH0Ay3ERcA8EsyIFkOXyre153OpZTIk5drUiQ9aqQIecfKawb6Fu4dUsG5hy2NHKp(lWgFF52qYxQKjengeFnk66EjwqarStMiVX9flNdF1CMl46j2PUfPPiStdvXlyV8tXrVcK5ak8ViGeq)c4MY2BIQvwZONaB10yvXkJCp1rMcdt93wyxWdTiLFvH1JWO1pDiRjlyXwWuo9guiNe9zMSxnLSiD5KKjy8pTY3CU8j0LmdcSstNi5Uwnj97xQbEYJyoBkBk1V3LGM(U0DXfadgWll3pVW7mCTATG3XjMNqZNC4ieBsrdUqkMabMcmTljWbkOw4eczIjfbpLOb07PPapmKua8Vpszo8yvUi8NCpXpGLmxQQgFCVLsP)P28vco9yOvDS6R4FldLHuFHjoKqqRL3kVBtrAy16o7jvLg4qdYG)EXI6sfUBA)vzvdQWOnMG3GSdIKlYIqIcbbsvY)HdwBpVcFXgrkSxVyAotbnzUXusk2gmqrLTijgFwdHiaHtYyLTfDG6bXGEG(QaiiD2JrUWp8Xaq)0V(7nYoFcQH8vpUiJ6aswywRe1THP894bierGt8EwcO9(PWMNKUd3znZypJPIeFTJiXhwEab41A1BtBwdfmTkqTv1xbyodrnWQFx3swfnzqhB6lcvaLtdoMzA5qB0dwfg8d5G9jbckKhd2xXyRWfSqdamEpIaayskqpXnhwIhruaIiIIZXMfajNkCfzLyFzeWkVC7(I8IuARs(EMQVBR6uGrlK8OVPYyPpc3m(6XjMwxQINpTPG6rnK8FQMLgc)4u0B3UA69stVyQLNByBfM00BtuEBDzWTBp2QwvEXZOiYozzokw)ocsuf6(E2m)mdqjLd1OYv0TtCvm1gLEnoq15rEKupEMSkpOE5sEMsIyTpuk0qpnzeTrxDMgn2PVw7lsFSohy9ROPz0umvtROBMnQ4NcKWOr0qFPoawHB4KN6TTJ3kvTaj1LaAHKcmd55ZjveDmo4rmvmn6aqer2ChGrbYC()l8oek4MQKgb06q55Pqam0YQlxs1iHmcuoxD1bPKyyh5aldcKb(ZTZmzo3WL0kwHobi2i4yNlH36fIPpmfZ1FmRdmgdNFMI57gOfSVT6)feXWTMj8q9THyq)DHqTUP2n4XmM8f)CjEjB2MYHwygF))khArpNyXT1vh)8tqVqjbT(TgNf05pDdjtz6LCqtQ23EjhSSpbuY4RESk92HLZ0HstfH8c2MYxCOF7UDAUWYEPLifp5inmgaCz(z14ooqFbR0xZDGwBh(B3I6EooO2D2xYa)zmpGiFHcR4)b8oEtxe91WlMMjy7MaXnHmOUVH(LCaDO0LdpkBVQm1nDtypZzsPMGjl6pRJXZ9yqnOjLcSBo64hjwozOJjpmRPTn1khgsVT2x)HH8sc(uoKJof2CHL(36CbE(zfvBfaSjTEXoQq2FynzM8br(Yn7AlGPD1hpTtxP2B0qLtDXvshyIzAkxWP3nVxaBpLY0UIQZEyuNHiRoNrUgH7nss8zcwCysCMpUgDVne62bMZWyoDf)uyg3AhjFwu4m)CIDBDMm56xz1aVw9EMQuEGOQCeT5ijFU29qs8UZlNTN5xxxGVzmWlEzaqHa3dvSHVMFBIwa4S1q8Wi8iz3S(3)HF9tF4t)TVVCB52FdBGIFO0vb6v8IEFv9rh4HNoa2kvsbqsLWAXkVBDztk)4V4JAxlyYEFCeSSSx)QgIu)RxXB3J8JQaPWRWtR5N)N)cywS(YO6P7w20b7ixEdD)JcsGF(J46srJX(04qykTTRMC8peZq5hpZ(RQiPN2o8MN7o8sfR6g581jx1h(xTy18ezPAMqQ(atiWp9UQdgRCl76EbVgpnU49(yYUV77Q5N066MHVX0vodFxZ1od)1t8QNXMeaI8YCuFLFu87j1NY4RT)Rnh7xNv7cpkH651w6OeQFiSev54Ug5lyBIK(1Xj2m2gxdHv9yXZTVQlbIRzjWTVB61nKfSxSqE9A3vk(620y)R5NjGT11(7TfhJWPtDpcHvtzkKxG(3llD8Pax6(6aU0hu3BFDpKV3m3SE5VPPp9YpvUEwuQUQhXAWqnwKtNmuS6Q7gDEZIOVGmn93GwKllqT7WdU7FABWBhn4CnjF1ndg2PNtlND6uxIDlHSLxGgRowzhRi2Vz2MaLJL2ZgOsjBfm)d6YezLnub5OtNutFJdwEb0SfphArb7P2OzrOawY2NGRGEfsvonmawviUALKDJztsELB5MrZ7YBeVsdt0UlecOKl7cxTlPrjRMpqIQZk7HVB6Bg2Z15z88rJ0V8TV0o6hvtaFucnEFDoDY4nPzaxj23TY5An31gmEBRBvJYJKLM2ZTb9TM7rdUPyWFf16sS6zj4bh5zx33XAmyhYVRwW8IwX9MAZiDL98Pd6TXzTxtqSBA4fZz1eN6L2QEKcWO2roe8wFDpnWCCpnVC8nGZFxPGT7xotjKF1nRwikAUv1JgnsREA2unkIMQyykIHIytcDnebZcKmtxqAi(gk3M6wfy30hQZA0GRg2U9j8W4TV6ZJ0iZQKz0CNifeugoBXRn3AHX90wHXZ0TUY0MUwClrTfxs0g0RMRQdMvHfCVTnzPDFxTtqjzQxPdm3N0L9i71vHZm292jcB75dme5fS59(PRSVrhsRsqfHhAc3cbg4lLP7xmKaxdEP)wTTCUo1GeCxJb0WTgEGra(mnlHSHSksyZfeEPCoDdqlv9Z3ESIupvKdy3WE3w9UcIcCZvUA5IPqmHRyxwVbsp(2BhXyy(n4kcQtM1OK7EH3wzREZbzc8t7EaEHRDNRi4aDf)mOBifqPAooJ1KfJvaykYaZTsWpvuZfFUQEbR79DeeqT0ChahpDILHPV7T0RdW4ndNnDSU90idZPU6dKMX7wmOlX(fYGwrTn2n3UGlGuiKTMLZ1yU8tNUQNS5J6S8yKN67WGU3kFbdqbehrZ1xaYgZRnyPL2m73ov3C26MguNHQ7TtqRePCpe0nI67FG2TR89oONDSOVHgI5X4S081vvzyay0fka(cJN197TBhJUBbNdmCajdg2T6LbMkE52rAL9xgkVFDzeLeN)BKlSbQW3czwEAThyHO9a6eZ7msuguU9wrXGlPQYLMwy9MHNgfatTW7zZd4LdpPwsHHMDi8JAFq5a0zXBmr3QdVtzMyCYfpLZY2KZqZPzJYVXt5EGYjCV6Ujl6XSQq82aT6b9Fg3AHQwt1Bc6LR9lMLU3cXQkcZ6ROimDnK(YJvl3E6VkXyS1enzr04Zo8jXBFK2oqAWKQbhDMIWMRDE6T8KBulp5zbJXn15oDyTlHuzhAtmw3SUXMeYljYJLX8b9mX6uARSgmunJiVmFdj0VZ86QolVwPf0YsXLszAZAsr(X4u2)1E49Sdb(Vt)SFGp7Sz38V)
```

**Comment by dubudevs** [comment]
Seems to be working correctly 👍
