### ISSUE TITLE
Allow HEALER to use target.time_to_die

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#1608]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

At present, I detect the value of Hekili.State.target.time_to_die in my addon to control whether I enable some cooldown skills. But when HEALER calls this, the value is always equal to 300. TANK and DPS are normal, how can I make them available in HEALER

**Comment by marekCs** [comment]
Hm interesting. So Hekili addon also works with a healer spec? I have to try it.

**Comment by Hekili** [comment]
Healer modules are outside the scope of support.  The most I can say is I don't recall any specific barrier to healers seeing time to die.  It does take a few seconds of damage before TTD will calculate.
