### ISSUE TITLE
Warrior - Fury - Bloodthirst error

### ISSUE THREAD

**Issue by Valkaneer** [Hekili/hekili#161]
**BEFORE SUBMITTING AN ISSUE:**

1. build: v8.2.0-03

2.  
**Describe the Bug/Issue**
Warrior- spec Fury- Issue - Bloodthirst

When I am in Fury spec I receive a Lua Error report in which the count does not stop and keeps going up which breaks the addon.  I was able to stop the error by deleting all Bloodthirst from under Priorities> Fury> Action List Tab> (Action List drop-down - Single Target) (Entry drop-down - Bloodthirst).  When I deleted all forms of Bloodthirst it seemed to operate normally.

**To Reproduce**

Re-introduce Bloodthirst into the priority list or reset profile function.

**Expected behavior**
To be able to use Hekili without the addon crashing in Fury spec.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
build: v8.2.0-03
level: 112 (112)
class: WARRIOR
spec: fury

talents: bounding_stride
    carnage
    double_time
    dragon_roar
    reckless_abandon
    sudden_death
    war_machine

azerite: none

essences: none*, none

sets/legendaries/artifacts: insignia_of_the_grand_army=1
    tier21=1

gear:     band_of_the_sargerite_smith=1
    brawlers_harness=1
    brulstone_idol=1
    doomwalker_warboots=1
    guild_tabard=1
    heart_of_azeroth=1
    inherited_cape_of_the_black_baron=1
    insignia_of_the_grand_army=1
    juggernaut_gauntlets=1
    nathrezim_battle_girdle=1
    polished_breastplate_of_valor=1
    polished_helm_of_valor=1
    polished_legplates_of_valor=1
    polished_spaulders_of_valor=1
    stalwart_crest=1
    tier21=1
    triumvirate_high_guards_bracers=1
    warswords_of_the_valarjar=1

itemIDs: 122245, 122251, 122261, 122355, 122381, 128908, 134146, 134553, 147278, 152009, 152020, 152064, 152180, 152626, 153344, 158075, 5976, 6125

3. Error Report

853x Hekili\State.lua:1079: bad argument #1 to 'wipe' (table expected, got nil)
[C]: ?
Hekili\State.lua:1079: in function <Hekili\State.lua:1061>
Hekili\State.lua:1231: in function `gain'
Hekili\Classes\WarriorFury.lua:416: in function `handler'
Hekili\State.lua:4765: in function `RunHandler'
Hekili\Core.lua:1249: in function `ProcessHooks'
Hekili\UI.lua:838: in function <Hekili\UI.lua:702>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by Hekili** [comment]
Update to v8.2.0-04 and re-report if the issue persists.

**Comment by Valkaneer** [comment]
All good! It's funny that in the time it took me to write the post on the error you downloaded the fix.  When I checked it said updated 14 min ago.  Mind reader :)
