### ISSUE TITLE
[Feature Request} Sort Action List by Name

### ISSUE THREAD

**Issue by totalschaden** [Hekili/hekili#1612]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Sorting Action List in Priorities by Name, currently its unsorted and diffucult to find Spells.

![grafik](https://user-images.githubusercontent.com/1507739/190876305-96982553-7c47-41ac-8403-1fb63eaed69a.png)

**Comment by Hekili** [comment]
FYI, this should work for Dragonflight.  If not, you can reopen after Dragonflight launches and let me know.
