### ISSUE TITLE
Recent Performance Impact - Reporting Thread

### ISSUE THREAD

**Issue by yuuri1249** [Hekili/hekili#1614]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Up to 40 fps drops during combat, more hectic more frames.

### How to Reproduce

1. Enter combat as outlaw

### Player Information (Link)

https://pastebin.com/HuazCM7P

### Error Messages (Link)

No errors in bugsack

### Additional Information

Havent seen the issue appear outside of outlaw and only began to drop large amounts of frames after the most recent updates.

**Comment by Hekili** [comment]
What was the last release that did not have this issue for you?  You can install a previous version to confirm.

**Comment by Hekili** [comment]
Updating this thread for data collection purposes.  Do not submit alternate threads on this topic.  If adding information, the following details are required.  Please copy and paste these questions and supply your own answers.

1. Did you confirm the issue occurs with the latest released version?  (`v9.2.7-1.0.0b` at time of posting.)
2. Please go to `/hekili` > Issue Reporting and copy the Character Data information, paste it on Pastebin, and provide the Pastebin link here:  
3. What is/was the first version where you noticed the issue?
4. What was the last version that does not have the issue?
You can install older versions of the addon here: https://curseforge.com/addons/wow/hekili/files
This information is _critical_ in terms of detecting which release causes your issue.
5. If you play multiple classes/specializations, do you notice this issue on some classes/specializations but not others?
If yes, which classes/specializations are not impacted?  Which are impacted?
6. Do you notice anything else about when this seems to occur?  Raids only?  M+ only?  Many target fights (i.e., mote affix)?  Some other time?
7. **Added 21 Sept**:  After noticing this issue in-game, please type `/hekili` and see if the Warnings section is lit up.  Is it?  
If so, please screenshot the warnings and/or copy/paste the text to Pastebin and link here.
8. Please share any other observations about the issue that come to mind.

Thank you for your help!

**Comment by yuuri1249** [comment]
Did you confirm the issue occurs with the latest released version? (v9.2.7-1.0.0b at time of posting.) - yes
Please go to /hekili > Issue Reporting and copy the Character Data information, paste it on Pastebin, and provide the Pastebin link here: build: v9.2.7-1.0.0b - https://pastebin.com/LYfffY9c
What is/was the first version where you noticed the issue? The most recent version
What was the last version that does not have the issue? Aug 14 release
You can install older versions of the addon here: https://curseforge.com/addons/wow/hekili/files
This information is critical in terms of detecting which release causes your issue.
If you play multiple classes/specializations, do you notice this issue on some classes/specializations but not others?
Ive only noticed these issues with outlaw specifically
If yes, which classes/specializations are not impacted? Which are impacted? Only experience with outlaw
Do you notice anything else about when this seems to occur? Raids only? M+ only? Many target fights (i.e., mote affix)? Some other time? It is dramatically worse in m+ and raid many targets seems to cause greater losses in fps 
Please share any other observations about the issue that come to mind
I notice a spike in fps as well when activating blunderbuss proc i assumed it was due to rapid reccomendations.

**Comment by IIeTpoc** [comment]
I can confirm I have the same issue as yuuri1249 has

**Comment by Hekili** [comment]
Please follow the directions for reporting in this thread.

**Comment by Tzuyume** [comment]
Did you confirm the issue occurs with the latest released version? (v9.2.7-1.0.0b at time of posting.)
Please go to /hekili > Issue Reporting and copy the Character Data information, paste it on Pastebin, and provide the Pastebin link here: https://pastebin.com/935SZqhK
What is/was the first version where you noticed the issue? unsure but its been a month at least
What was the last version that does not have the issue? unable to test atm
You can install older versions of the addon here: https://curseforge.com/addons/wow/hekili/files
This information is critical in terms of detecting which release causes your issue.
If you play multiple classes/specializations, do you notice this issue on some classes/specializations but not others?
If yes, which classes/specializations are not impacted? Which are impacted? Sofar Unholy, Enhancement and outlaw. Not noticed on either healing specs
Do you notice anything else about when this seems to occur? Raids only? M+ only? Many target fights (i.e., mote affix)? Some other time? Specifically happens in junkyard in the area between trixie and last boss, and tazavesh streets in the big court area between zogron and goldfuse.
Please share any other observations about the issue that come to mind.
Will add more as i found out, thought better you get something

**Comment by marekCs** [comment]
9.2.5.1.0.10 is doing well.

**Comment by Hekili** [comment]
I added a question to my list above, which is:

After noticing this issue in-game and **before** reloading your UI or restarting your client, please type `/hekili` and see if the Warnings section is lit up. Is it?
If so, please screenshot the warnings and/or copy/paste the text to Pastebin and link here.  

If you could add this information to your earlier responses (or any new responses), I would appreciate it.  Thank you.  I am investigating.

**Comment by Hekili** [comment]
Closing for lack of info/updates.
