### ISSUE TITLE
ability missing in rotation

### ISSUE THREAD

**Issue by Nemesis977** [Hekili/hekili#1617]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hi, i see that in dragonflight a lot of ability of the WW are missing...is that normal?
Ability like:
RUSHING JADE WIND
BONEDUST BREW
CHI WAVE AND CHI BURST
STRIKE OF THE WINDLORD

maybe the addon is not ready for the beta, np than...only want to know if i miss something

### How to Reproduce

dont understand

### Player Information (Link)

http://github.com/Hekili/hekili/issues

### Error Messages (Link)

no error message

**Comment by Hekili** [comment]
There is no released version of the addon for Dragonflight beta.
