### ISSUE TITLE
Monk - Lua Error - v8.2.0-05-alpha3

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#162]
Downgrading back to the release version makes the error go away.

This only happens when I am in a party.

```
175x Hekili\Classes\MonkWindwalker.lua:912: Usage: UnitIsFriend("unit", "otherUnit")
[C]: in function `UnitIsFriend'
Hekili\Classes\MonkWindwalker.lua:912: in function <Hekili\Classes\MonkWindwalker.lua:907>
(tail call): ?
Hekili\State.lua:5593: in function `IsUsable'
Hekili\Core.lua:650: in function `GetPredictionFromAPL'
Hekili\Core.lua:1008: in function `GetNextPrediction'
Hekili\Core.lua:1177: in function `ProcessHooks'
Hekili\UI.lua:838: in function <Hekili\UI.lua:702>

Locals:
InCombatSkipped
```

build: v8.2.0-05-alpha3
level: 120 (120)
class: MONK
spec: windwalker

talents: ascension
    chi_wave
    hit_combo
    inner_strength
    ring_of_peace
    tigers_lust
    whirling_dragon_punch

azerite: azerite_empowered=3
    blood_siphon=2
    dance_of_chiji=1
    elemental_whirl=1
    glory_of_the_dawn=1
    longstrider=1
    open_palm_strikes=3
    pressure_point=1
    resounding_protection=2

essences: [the_crucible_of_flame]=1, none

sets/legendaries/artifacts: none

gear:     7th_legionnaires_warhammer=1
    bonelash_paw=1
    calibrated_hefty_cog=1
    fathomstalker_cloak=1
    gloves_of_corrupted_waters=1
    heart_of_azeroth=1
    high_altitude_turban=1
    lord_waycrests_signet=1
    lurkers_insidious_gift=1
    lustrous_golden_plumage=1
    pustule_bearers_pants=1
    sea_dogs_cuffs=1
    shoulders_of_the_sanguine_monstrosity=1
    silent_pillagers_footpads=1
    vest_of_reverent_adoration=1
    whirling_dervish_sash=1

itemIDs: 158075, 158305, 158362, 158364, 159303, 159317, 159321, 159323, 159338, 159617, 163883, 165520, 165588, 167866, 169002, 169487

**Comment by Hekili** [comment]
Should be fixed in alpha4
