### ISSUE TITLE
WotLK DK blood rotation

### ISSUE THREAD

**Issue by willz501** [Hekili/hekili#1625]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

when set to only show one icon its only recommending icy touch 

### How to Reproduce

set as blood instead of unholy and reduced the suggested icons to 1

### Snapshot (Link)

https://pastebin.com/NSk172AF

**Comment by willz501** [comment]
i think its not reading the frost fever dot

**Comment by willz501** [comment]
fixed pastebin link

**Comment by Hekili** [comment]
Previous resolved.
