### ISSUE TITLE
Wotlk frost dk only suggesting icy touch, plague strike, blood strike and death coil

### ISSUE THREAD

**Issue by Aldwew** [Hekili/hekili#1627]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Frost DK profile suggests only icy touch, plague strike, blood strike and death coil.

### How to Reproduce

Log in and get into combat as frost dk with frost dk profile selected

### Player Information (Link)

https://pastebin.com/yy2h5Wes

### Error Messages (Link)

-

**Comment by Hekili** [comment]
This would be a recommendations issue and would require a snapshot per that ticket form's instructions.
