### ISSUE TITLE
[BUG] Doesnt show MM Hunter

### ISSUE THREAD

**Issue by HunterFace13** [Hekili/hekili#1629]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon isn't loading in my game for my MM Hunter. I changed the settings but none of them works.

### How to Reproduce

1. Enter my Hunter
2. Hekili isn't shown

### Player Information (Link)

https://pastebin.com/UQnxCTvd

### Error Messages (Link)

https://pastebin.com/4D0xaySb

**Comment by Hekili** [comment]
Yes. That's correct. I haven't built hunters yet.
