### ISSUE TITLE
Unable to disable 'Ripple in Space' Essence Ability

### ISSUE THREAD

**Issue by Exsol-bit** [Hekili/hekili#163]
**Describe the Bug/Issue**
Ripple in Space essence ability is always shown as apart of rotation, despite being toggled off and manually removed.

**To Reproduce**
I was able to reproduce the issue in both Elemental and Enhancement spec. Issue does not occur when using Concentrated Flame (did not test other essences).

Issue occurs with:
- Essences toggled off in UI (and with keyboard shortcuts)
- When cool-downs are toggled on or off
- In both Single-Target and Automatic (no other Display modes were tested)
- With 'Ripple in Space' manually removed from UI Interface (Under Elemental > Toggles > Azerite Essences)

**Expected behavior**
Ripple in Space ability should not show up as apart of the rotation when manually removed from Azerite Essences toggle or when Essences is toggled off.

**Screenshots**
![4f64bf1369d7ec63e2bfacadb9da2871](https://user-images.githubusercontent.com/52397322/60415256-00547e00-9c1e-11e9-9940-57833571e131.png)
![008a84d980d6d3c89f1aa46a238daf55](https://user-images.githubusercontent.com/52397322/60415257-00547e00-9c1e-11e9-890d-be04cf50d205.png)
![f79f0eb55edfdd959d43cba794ec1a61](https://user-images.githubusercontent.com/52397322/60415259-00547e00-9c1e-11e9-89fe-ad552005d253.png)

**PUT ISSUE REPORT LINK HERE:** https://pastebin.com/BPPjMpn1

Apologies if I've missed anything.

**Comment by Hekili** [comment]
If you remove it from the Essences toggle, that means you are leaving it enabled at all times.

If you never want it to be recommended, go to /hekili > Abilities > Ripple in Space and disable it there.

**Comment by Exsol-bit** [comment]
All of that effort to report it, and it wasn't a bug </3 I can only assumed I removed it from the list because if a misunderstanding and then went of a wild goose chase trying to figure it out. Thanks for at least looking into it.
