### ISSUE TITLE
Frost DK suggesting only couple of skills

### ISSUE THREAD

**Issue by Aldwew** [Hekili/hekili#1630]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Does not suggest anything besides icy touch, plague strike, blood strike and death coil. It even suggests Icy touch even tho the target has Frost Fever on it. Attacked a mob, used icy touch, plague strike and blood strike twice. Then it suggested Icy Touch again, the target still had Frost Fever. After using Icy touch again, then it suggests plague strike again, even tho there's blood plague on the target.

### How to Reproduce

Enter the game and attack a mob?

### Snapshot (Link)

https://pastebin.com/J66KJB5S

### Additional Information

It doesn't even suggest changing to Blood Presence, which if I understood correctly, it should. Doesn't suggest Blood Tap even after using blood strike twice, suggests death coil instead of frost strike.

**Comment by Hekili** [comment]
I consciously don't have it tell you to change presences unless it's for something specific (like Unholy DKs swapping late in their opener).  Think how annoying it would be for the addon to tell you to swap presences when you specifically chose your presence for a reason.

What else were you wanting it to recommend, aside from Blood Tap (which is considered a cooldown, which you have toggled off)?  

You don't have Frost Strike talented in the snapshot.  Is that inaccurate?

**Comment by willz501** [comment]
> I consciously don't have it tell you to change presences unless it's for something specific (like Unholy DKs swapping late in their opener). Think how annoying it would be for the addon to tell you to swap presences when you specifically chose your presence for a reason.
> 
> What else were you wanting it to recommend, aside from Blood Tap (which is considered a cooldown, which you have toggled off)?
> 
> You don't have Frost Strike talented in the snapshot. Is that inaccurate?

I agree with not having suggested stances sometimes you can be dpsing and the tank dies you SHOULD know to switch to frost but i do have the issue of death coil being suggested when i am talented into frost strike here is my snapshot https://pastebin.com/u6FckkwA

**Comment by Aldwew** [comment]
> I consciously don't have it tell you to change presences unless it's for something specific (like Unholy DKs swapping late in their opener). Think how annoying it would be for the addon to tell you to swap presences when you specifically chose your presence for a reason.
> 
> What else were you wanting it to recommend, aside from Blood Tap (which is considered a cooldown, which you have toggled off)?
> 
> You don't have Frost Strike talented in the snapshot. Is that inaccurate?

Frost Strike is talented, but don't have the 32 runic power glyph as of yet. Also if I understand correctly, it only suggests Obliterate when Blood Tap has been used, seems kinda dumb tbh

**Comment by meak89** [comment]
I was waiting till someone had a similar issue because I thought I was doing something but I am having the same exact issue where only the mentioned abilities are showing up. I can get obliterate to show up if I had made my blood runes turn into death runes. Although frost strike never shows up and instead it is death coil like said above as well. Also blood tap I think is supposed to be activated for obliterate exclusively. By reading the icyveins guides that I think you use as reference, the priority kind of resembles more of the top chunk of information instead of the actual priority that is stated below the opener section I believe.

**Comment by astothialo** [comment]
found both the rotation severly lacking and pretty bung.
using the following spec: https://wotlk.evowow.com/?talent#jfV0VZG0exArczf0cuzAo:akpVMm and both rotations are broken.
keeps suggesting to use pestilence when i could be doing oblit, bt/erw or whatever.

**Comment by SpatenLa** [comment]
you need to provide a Snapshot and make sure that you have the newest Version which is beta8

**Comment by Hekili** [comment]
Submit a fresh ticket for your issue, which is not the issue this ticket was for.  Follow the instructions when submitting tickets.

The Frost Strike talent/rank issue is resolved.
