### ISSUE TITLE
Raptor Strike is recommended too often Surv

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1633]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The problem is that it doesn't matter if it's a fight with 1 target or with many, the addon often recommends using Raptor Strike. As I know, we should have more Kill Command and bomb damage. But if strictly following the rotation through the addon, then we have Raptor Strike with a huge gap from these two main abilities. There is an assumption that the addon does not aim to do more damage through bombs in 1 target.

### How to Reproduce

Just hit the manikin.

### Snapshot (Link)

https://pastebin.com/Pnhzt79x

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3J18tX5NkshwKmxXpTnxzV

### Additional Information

Maybe I certainly don't understand something. But looking at the logs of people, and looking at my simulation, I see that the addon does not implement the red bomb. In terms of the fact that the addon does not seek to try to get a buff that can give a free bomb. Maybe I'll repeat myself again, I'm wrong.

**Comment by Hekili** [comment]
Your snapshot isn't taken at a useful time to analyze this.  Take the snapshot when the addon is recommending Raptor Strike and you think it shouldn't have.

**Comment by Urmus-dev** [comment]
Same issue here is a snapshot: https://pastebin.com/HTqx1Wn2

**Comment by Hekili** [comment]
Please check the "Allow Focus Overcap" option for your specialization.  With it disabled, the addon will follow the default sim priority and require you to spend down Focus before pushing other buttons (so that focus regen is not wasted).

If you still have the same issue with Allow Focus Overcap enabled, please post a new snapshot taken when Raptor Strike is being recommended but you believe it should not be.  Thanks!
