### ISSUE TITLE
Retri pala Doesnt work

### ISSUE THREAD

**Issue by Zsola79** [Hekili/hekili#1635]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Retri pala doesnt work. I cant see Hekili spells. Cant see Paladins types etc,? retri, hol, prot. Priority is empty. No import string.

### How to Reproduce

Retri pala

### Player Information (Link)

http://github.com/Hekili/hekili/issues

### Error Messages (Link)

xx

**Comment by SpatenLa** [comment]
yes. its not finished. paladin doesnt exist.

**Comment by Zsola79** [comment]
:(  best addon

**Comment by Zsola79** [comment]
When is the development expected? (upgrade)

**Comment by Doog45** [comment]
still not working, any idea when that might change?

**Comment by Hekili** [comment]
I will resume working on additional classes after DF prepatch launches and stabilizes.
