### ISSUE TITLE
Subtlety rogue (WOTLK)

### ISSUE THREAD

**Issue by psenne** [Hekili/hekili#1636]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I didn't see anything about the subtlety rogue (or rogue in general) online, so I wanted to ask if it was a work in progress or if I'm doing something wrong. I have a hunter in retail and Hekili works out of the box. But in Wrath on my rogue, it doesn't show up at all and doesn't seem to have a prioritization builtin. 

### How to Reproduce

Create a level 70 rogue and and start the game. There's no Hekili popping up.

### Snapshot (Link)

http://pastebin.com/justaquestion

**Comment by Hekili** [comment]
no, i haven't implemented rogues yet
