### ISSUE TITLE
Death Runes NYI in Classic

### ISSUE THREAD

**Issue by willz501** [Hekili/hekili#1637]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

sees death runes as blood runes and wastes them as bloood runes

### How to Reproduce

using regular rotation in single icon

### Player Information (Link)

https://pastebin.com/XHfqyf5f

### Error Messages (Link)

none

### Contact Information

Samuraiwillz501#0239

**Comment by Alqua1** [comment]
Hi, I'm frost dk too, I noticed that too and I'm using the following and it's working correctly (this is just temporary solution, we'll need to wait Hekili later on): 
actions+=/blood_strike,if=(!GetRuneCooldown(1)&GetRuneType(1)=1)|(!GetRuneCooldown(2)&GetRuneType(2)=1)

There are two parts in this code: 
A: (!GetRuneCooldown(1)&GetRuneType(1)=1) ==> If your left most rune is off cooldown (which means you can use it) and it's a blood rune, 
B: (!GetRuneCooldown(2)&GetRuneType(2)=1) ==> If your left 2nd most rune is off cooldown (which means you can use it) and it's a blood rune, 

Either A or B true, then you can blood strike to convert it from blood. This script will not suggest you to spam blood strike and waste the death rune. 

Like I said, it's temporary, wait Hekili to implement the death runes.

**Comment by Hekili** [comment]
Or just be patient.

**Comment by Hekili** [comment]
Death Runes as distinct from other runes is NYI.  Will follow-up later.
