### ISSUE TITLE
UH DK | Ghoul Frenzy unusable because it doesn't find the Ghoul eventho it's there

### ISSUE THREAD

**Issue by SkullCandyTV** [Hekili/hekili#1639]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When trying to make Hekili recommend Ghoul Frenzy, it doesn't no matter what you try.
The Snapshot says 

14.  ghoul_frenzy ( default - 10 )
        The action (ghoul_frenzy) is unusable at (0.00 + 1.47) because require a living ghoul.
        Time spent on this action:  0.12ms
        TimeData:Unholy (IV)-default-10:ghoul_frenzy:0.12:Ability Known, Enabled(0.04):Post-TTR and Essential(0.07):Post Cycle(0.00):Post Usable(0.01)

### How to Reproduce

Unholy Deathknight
Spec into Ghoul Frenzy
Summon Ghoul
Attack Target
Follow Hekili Rotation
No Ghoul Frenzy recommended

### Snapshot (Link)

https://pastebin.com/NYtm3jGF

### Contact Information

SkullCandy#1156

**Comment by ArtisanNull** [comment]
Unholy priority Entry 10 pet.ghoul.up shows false

changed to pet.ghoul.active also false

changed to pet.ghoul returned true

looks like the conditions are missing for tracking the buff on the ghoul

something like pet.ghoul.buff.ghoul_frenzy.remains <10 & pet.ghoul.active

**Comment by Tobbelainen** [comment]
Is there any solution on this? =)

**Comment by Hekili** [comment]
Fix will be posted later today.
