### ISSUE TITLE
UH DK | Add either a toggle or second Unholy-Priority for the superior Dualwield/GhoulFrenzy/NoScourgeStrike build

### ISSUE THREAD

**Issue by SkullCandyTV** [Hekili/hekili#1640]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

The current Unholy DK prio is outdated and only better full BiS T10 with Shadowmourne. 

![Screenshot 2022-10-04 204527](https://user-images.githubusercontent.com/89059544/193900794-2bf21915-1faf-4346-b261-973f807ac301.png)

This dualwield build ( or additional blood sub) here is significantly better.

It changes our rotation in a few ways.

No ScourgeStrike (Can still be used but is just less damage because us using 1H weapons, we will use SS again in ToC with the Sigil)

Bloodboil filler on ST

Bloodstrike to procc Desolation & only used to refresh at around 10s

Ghoul Frenzy & it's refresh around 10s remaining duration

Death and Decay on CD both ST and AOE

Death Coil only during rune-downtime 

The website https://wowsims.github.io/wotlk/deathknight/ has already fully implemented that spec and it's rotation almost perfectly and significantly outperforms the old Scourge-Strike one.

The new ST rotation looks like this flowchart
![Screenshot 2022-10-04 205316](https://user-images.githubusercontent.com/89059544/193902709-d8232305-48bf-4c15-839f-c91e501facb5.png)

And the new AOE rotation just replaces Bloodboil with Pestilence after spreading them on Pull.

That means Bloodboil because it doesn't scale with Weapondmg is now a strictly ST filler and Bloodstrike is just there to keep the Desolation-Buff constantly running.

This style of Unholy DK requires a lot more tracking and input but doesn't rely on proccs which makes it perfect for a fantastic software like Hekili 

### Additional Information

There is also an entire explanation/guide video for it by Whitewolf who is a very well known P-Server player that made this playstyle popular

https://youtu.be/BXSbwqG1jE8

If there are any further questions, I am always on DC and would love to help.

### Contact Information

SkullCandy#1156

**Comment by Tobbelainen** [comment]
This would be so awesome if @Hekili could take a look on this!

**Comment by Hekili** [comment]
Please do not pad tickets with unnecessary pings.

**Comment by Hekili** [comment]
If there's a spelled out written version, I'll take a look at it.  Translating a video and priority written in Go is a large effort.

**Comment by DrManowar** [comment]
> If there's a spelled out written version, I'll take a look at it. Translating a video and priority written in Go is a large effort.

The unholy rotation on wowtbc.gg mostly matches what is said in the video. If you wish to refine it further, the video itself has the general priority list with more info in the forms of slides/screenshots. If you don't want to sift through the video I can send you all the screenshots with your permission.

**Comment by Hekili** [comment]
I've reviewed a bunch of these materials and will work on the UH priority after Dragonflight prepatch releases and is stable.

**Comment by Divirts** [comment]
> I've reviewed a bunch of these materials and will work on the UH priority after Dragonflight prepatch releases and is stable.

hi, where can I get the code for this rotation?

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
