### ISSUE TITLE
Surv an error appears when attacking a manikin and bosses

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1641]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When starting a boss fight or a manikin, I get an error.

### How to Reproduce

Just hit the manikin or the boss.

### Player Information (Link)

https://pastebin.com/csasQTeN

### Error Messages (Link)

https://pastebin.com/j2ipJNGd

**Comment by Hekili** [comment]
I'm not sure this is truly an issue with this addon; it is a taint issue.  The addon doesn't touch anything associated with pet action bars.  If you play for a bit without the addon loaded, do you get the same error attributed to another addon?

**Comment by Dragonfo** [comment]
I have dominous for panels, and clicked for clicking abilities. It's just that there were no mistakes before. Now it has begun to pour errors and it is on bosses and mannequins

**Comment by Hekili** [comment]
> If you play for a bit without the addon loaded, do you get the same error attributed to another addon?

**Comment by Dragonfo** [comment]
Just killed 5 bosses already, and there are no mistakes. Disconnected everything only left Bigwigs WA and Hekili. There are no errors. I also included all addons and the error stopped appearing after restarting the interface
