### ISSUE TITLE
PI no longer recommended

### ISSUE THREAD

**Issue by Cormelain** [Hekili/hekili#1643]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Yesterday, PI was being recommended after casting Void Eruption. Today, with no changes to Hekili that I know of, PI is no longer recommended at any time during a fight.

### How to Reproduce

1. Enter as Shadow Priest
2. Make sure Cooldowns are turned on
3. Get into single target fight
4. No recommendation of PI, ever

### Player Information (Link)

https://pastebin.com/FmG5cm3K

### Error Messages (Link)

None

**Comment by Hekili** [comment]
>         43.  power_infusion ( cds - 1 )
>         The action (power_infusion) is usable at (7.62 + 0.00).
>          - the action is ready before the current recommendation (at +0.00 vs. +10.00).
>         List ( main ) called from ( Shadow:default:24 ) would PASS at 0.00.
>         NONE
>         List ( cds ) called from ( Shadow:main:6 ) would PASS at 0.00.
>         NONE
>          - this entry's criteria FAILS: priest.self_power_infusion[true] & ( buff.voidform.up[true] | ! covenant.kyrian[false] & ! covenant.necrolord[true] & cooldown.void_eruption.remains[90.00] >= 10 | fight_remains[22.38] < cooldown.void_eruption.remains[90.00] ) & ( fight_remains[22.38] >= cooldown.void_eruption.remains[90.00] + 15 & cooldown.void_eruption.remains[90.00] <= gcd.execute[0.00] * 4 | fight_remains[22.38] > cooldown.power_infusion.duration[120.00] | boss[false] & fight_remains[22.38] < cooldown.void_eruption.remains[90.00] + 15 | covenant.kyrian[false] | buff.bloodlust.up[false] )
>         Excluded -67.61 recheck time as it is outside our constraints ( 0.00 - 10.00 ).
>         Excluded -82.61 recheck time as it is outside our constraints ( 0.00 - 10.00 ).
>         There were no recheck events to check.
>         Time spent on this action:  0.37ms
>         TimeData:Shadow-cds-1:power_infusion:0.37:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.02):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.25):Post-Recheck Times(0.04):Post Recheck(0.00)

The short version of this is that the Power Infusion entry in the priority would've passed in a boss fight, but not during trash fights.
