### ISSUE TITLE
Cannot revert to original action list, despite re-installing

### ISSUE THREAD

**Issue by Milltips** [Hekili/hekili#1644]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I deleted the action string from priorities --> profile, i was wanting to do the old school method of brining in the list from SIMcraft.

turns out when I did that i didn't save the old string, now for single target dps its telling me to cast moon fire over and over again.

i deleted the addon and its settings using the two options available to me in curse forge.  unfortunately every time i re-install it does not install the balance action string.

please help.

### How to Reproduce

xx

### Player Information (Link)

xx

### Error Messages (Link)

xx

**Comment by Hekili** [comment]
So, not a bug, and, well, don't do that.

You can reset your profile (see Profiles section of options) and reload and you'll be back to defaults.
