### ISSUE TITLE
[FEATURE] Keybinds support for Dominos action bar

### ISSUE THREAD

**Issue by jaychang85** [Hekili/hekili#1645]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

actionBarNumber 2 - DominosActionButton1-12
actionBarNumber 7 - DominosActionButton13-24

Please help to see how to add this support

**Comment by jaychang85** [comment]
<Binding name="CLICK DominosActionButton1:HOTKEY" header="DominosActionBar2" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton2:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton3:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton4:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton5:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton6:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton7:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton8:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton9:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton10:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton11:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton12:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton13:HOTKEY" header="DominosActionBar7" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton14:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton15:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton16:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton17:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton18:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton19:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton20:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton21:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton22:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton23:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton24:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton25:HOTKEY" header="DominosActionBar8" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton26:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton27:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton28:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton29:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton30:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton31:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton32:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton33:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton34:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton35:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton36:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton37:HOTKEY" header="DominosActionBar9" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton38:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton39:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton40:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton41:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton42:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton43:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton44:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton45:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton46:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton47:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton48:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton49:HOTKEY" header="DominosActionBar10" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton50:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton51:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton52:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton53:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton54:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton55:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton56:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton57:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton58:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton59:HOTKEY" category="BINDING_CATEGORY_Dominos"/>
	<Binding name="CLICK DominosActionButton60:HOTKEY" category="BINDING_CATEGORY_Dominos"/>

**Comment by Hekili** [comment]
Closing as resolved.
