### ISSUE TITLE
[REC] Warrior Fury, Sunden Armor

### ISSUE THREAD

**Issue by Rechiyo** [Hekili/hekili#1646]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As Fury Warrior when u want to start your Rotation he shows Sunden Armor, when you reach the 5 Stacks it still appears and dont remove. And if I try to remove the ablity from the prio rotation, it doesnt work at all and freeze.

### How to Reproduce

Enter game as fury warrior
try to follow the rotation as it shows,
it will stuck and not keep going on.

### Snapshot (Link)

Fury (IV); Primary - Intercept(0.00), Sunder Armor(0.00), Bloodthirst(1.44) build: v3.4.0-1.0.0-beta7a level: 80 (80) class: WARRIOR spec: warrior  talents: anger_management     armored_to_the_teeth     bloodsurge     bloodthirst     commanding_presence     cruelty     death_wish     deep_wounds     dual_wield_specialization     flurry     impale     improved_berserker_stance     improved_charge     improved_cleave     improved_heroic_strike     improved_rend     improved_whirlwind     intensify_rage     precision     rampage     tactical_mastery     titans_grip     twohanded_weapon_specialization     unbridled_wrath     unending_fury  pvptalents: none  covenant: none  conduits: none  soulbinds: none  sets: none  gear: boots_of_the_whirling_mist = 1     brutal_gladiators_decapitator = 1     colossal_skullclad_cleaver = 1     deadly_gladiators_bracers_of_triumph = 1     deadly_gladiators_cloak_of_victory = 1     deadly_gladiators_pendant_of_victory = 1     drakemounted_crossbow = 1     dual_wield = 1     gauntlets_of_dragon_wrath = 1     grim_toll = 1     guardians_band_of_triumph = 1     hemorrhaging_circle = 1     mainhand_2h = 1     mirror_of_truth = 1     savage_saronite_waistguard = 1     snake_den_spaulders = 1     titanforged_plate_helm_of_triumph = 1     titans_grip_offhand = 1     valorous_dreadnaught_battleplate = 1     valorous_dreadnaught_legplates = 1  legendaries: none  itemIDs: 34997, 35131, 37191, 37363, 37627, 37642, 37666, 37852, 40256, 40525, 40529, 40684, 40888, 41352, 42028, 42068, 44902  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = false     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcd = 6673     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Fury (IV)     package1 = Arms (IV)     package2 = Fury (IV)     package3 = Protection Warrior (IV)     petbased = false     potion = prolonged_power     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = false      interrupts = false      mode = reactive      potions = false   keybinds:      battle_shout         = A3  [01], C2  [05], A3  [08], A3  [09]     berserker_rage       = C1  [05]     bloodrage            = A2  [01], MwU [05], A2  [08], A2  [09]     bloodthirst          = 1   [01], 1   [07], 1   [09]     charge               = A1  [01], A1  [07], 1   [08], A1  [09]     cleave               = G   [06], 3   [07]     commanding_shout     = ^   [05]     death_wish           = F   [01], A3  [07], F   [09]     demoralizing_shout   = E   [06]     disarm               = T   [06]     enraged_regeneration = SM3 [05]     execute              = 6   [01], 6   [07], 6   [09]     hamstring            = Q   [06]     heroic_strike        = 2   [01], 2   [07], 4   [08], 2   [09]     intercept            = M4  [06]     intervene            = SM4 [05]     intimidating_shout   = SE  [06]     overpower            = X   [07]     pummel               = R   [06]     recklessness         = SM5 [06]     rend                 = 5   [01], 5   [07], 5   [09]     retaliation          = SQ  [06]     revenge              = 3   [08]     shattering_throw     = C3  [05]     shield_bash          = 2   [08]     shield_wall          = M3  [05], 5   [08]     slam                 = 4   [01], 4   [07], 4   [09]     spell_reflection     = SR  [06]     sunder_armor         = C   [01], C   [07], C   [09]     thunder_clap         = S   [06]     victory_rush         = F   [07]     whirlwind            = 3   [01], 3   [09]   targets:     nameplate3   -  2 - Creature-0-4445-1-20658-31146-00003E9C3B - 3591.00 - 10 - Heroic Training Dummy    player_buffs:     29801 - rampage                                  -   1 - 3600.00     47436 - battle_shout                             -   1 - 71.91   player_debuffs:  target_buffs:     61573 - *banner_of_the_alliance                  -   1 - 3600.00  target_debuffs:     58567 - sunder_armor                             -   5 - 3.69     New Recommendations for [ Primary ] requested at 11:06:32 ( 88788.37 ); using built-in ( Fury (IV) ) priority. *** START OF NEW DISPLAY: Primary ***  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: rage[ 100.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Fury (IV) - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   berserker_stance ( precombat - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.05ms         TimeData:Fury (IV)-precombat-1:berserker_stance:0.05:Ability Known, Enabled(0.05)                  2.   battle_shout ( precombat - 2 )         The action (battle_shout) is usable at (0.00 + 0.00) with cost of 10 rage.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: buff.battle_shout.down[false]         There were no recheck events to check.         Time spent on this action:  0.22ms         TimeData:Fury (IV)-precombat-2:battle_shout:0.22:Ability Known, Enabled(0.05):Post-TTR and Essential(0.06):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.04):Pre-Recheck(0.02):Post-Recheck Times(0.01):Post Recheck(0.01)                  3.   commanding_shout ( precombat - 3 )         The action (commanding_shout) is usable at (0.00 + 0.00) with cost of 10 rage.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: buff.my_battle_shout.down[false]         There were no recheck events to check.         Time spent on this action:  0.23ms         TimeData:Fury (IV)-precombat-3:commanding_shout:0.23:Ability Known, Enabled(0.04):Post-TTR and Essential(0.06):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.08):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)          Completed precombat action list [ Fury (IV) - precombat ].          Processing default action list [ Fury (IV) - default ].                  Current recommendation was NO ACTION at +10.00s.                  4.   pummel ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.04ms         TimeData:Fury (IV)-default-1:pummel:0.04:Ability Known, Enabled(0.04)                  5.   spell_reflection ( default - 2 ) - ability disabled ( toggle )         Time spent on this action:  0.11ms         TimeData:Fury (IV)-default-2:spell_reflection:0.11:Ability Known, Enabled(0.11)                  6.   intercept ( default - 3 )         The action (intercept) is usable at (0.00 + 0.00) with cost of 10 rage.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry has no criteria to test.         Action chosen:  intercept at 0.00!          Completed default action list [ Fury (IV) - default ].     Recommendation is intercept at 0.00 + 0.00.     Recommendation #1 is intercept at 0.00s (0.00s).  RECOMMENDATION #2 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: rage[ 90.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Fury (IV) - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   berserker_stance ( precombat - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.04ms         TimeData:Fury (IV)-precombat-1:berserker_stance:0.04:Ability Known, Enabled(0.04)                  2.   battle_shout ( precombat - 2 )         The action (battle_shout) is usable at (0.00 + 0.00) with cost of 10 rage.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: buff.battle_shout.down[false]         There were no recheck events to check.         Time spent on this action:  0.13ms         TimeData:Fury (IV)-precombat-2:battle_shout:0.13:Ability Known, Enabled(0.03):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)                  3.   commanding_shout ( precombat - 3 )         The action (commanding_shout) is usable at (0.00 + 0.00) with cost of 10 rage.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: buff.my_battle_shout.down[false]         There were no recheck events to check.         Time spent on this action:  0.14ms         TimeData:Fury (IV)-precombat-3:commanding_shout:0.14:Ability Known, Enabled(0.04):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)          Completed precombat action list [ Fury (IV) - precombat ].          Processing default action list [ Fury (IV) - default ].                  Current recommendation was NO ACTION at +10.00s.                  4.   pummel ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-1:pummel:0.03:Ability Known, Enabled(0.03)                  5.   spell_reflection ( default - 2 ) - ability disabled ( toggle )         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-2:spell_reflection:0.03:Ability Known, Enabled(0.03)                  6.   intercept ( default - 3 )         The action is not ready ( 30.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-3:intercept:0.03:Ability Known, Enabled(0.03)                  7.   bloodrage ( default - 4 ) - ability disabled ( toggle )         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-4:bloodrage:0.03:Ability Known, Enabled(0.03)                  8.   shattering_throw ( default - 5 ) - ability disabled ( toggle )         Time spent on this action:  0.04ms         TimeData:Fury (IV)-default-5:shattering_throw:0.04:Ability Known, Enabled(0.04)                  9.   death_wish ( default - 6 ) - ability disabled ( toggle )         Time spent on this action:  0.04ms         TimeData:Fury (IV)-default-6:death_wish:0.04:Ability Known, Enabled(0.04)                  10.  heroic_fury ( default - 7 ) - talent [ heroic_fury ] missing         Time spent on this action:  0.02ms         TimeData:Fury (IV)-default-7:heroic_fury:0.02:Ability Known, Enabled(0.02)                  11.  recklessness ( default - 8 ) - ability disabled ( toggle )         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-8:recklessness:0.03:Ability Known, Enabled(0.03)                  12.  use_items ( default - 9 )         There is no criteria for Use Items.         + items         Current recommendation was NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items                  13.  sunder_armor ( default - 10 )         The action (sunder_armor) is usable at (0.00 + 0.00) with cost of 15 rage.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria PASSES: ( debuff.sunder_armor.stack[5.00] < 5 | debuff.sunder_armor.remains[3.69] < 5 ) & target.time_to_die[3591.00] > 15         Action chosen:  sunder_armor at 0.00!          Completed default action list [ Fury (IV) - default ].     Recommendation is sunder_armor at 0.00 + 0.00.     Recommendation #2 is sunder_armor at 0.00s (0.00s).  RECOMMENDATION #3 ( Offset: 0.00, GCD: 1.44, Casting: 0.00 ).      Resources: rage[ 75.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Fury (IV) - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   berserker_stance ( precombat - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Fury (IV)-precombat-1:berserker_stance:0.03:Ability Known, Enabled(0.03)                  2.   battle_shout ( precombat - 2 )         The action (battle_shout) is usable at (0.00 + 1.44) with cost of 10 rage.          - the action is ready before the current recommendation (at +1.44 vs. +10.00).          - this entry's criteria FAILS: buff.battle_shout.down[false]         There were no recheck events to check.         Time spent on this action:  0.13ms         TimeData:Fury (IV)-precombat-2:battle_shout:0.13:Ability Known, Enabled(0.03):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)                  3.   commanding_shout ( precombat - 3 )         The action (commanding_shout) is usable at (0.00 + 1.44) with cost of 10 rage.          - the action is ready before the current recommendation (at +1.44 vs. +10.00).          - this entry's criteria FAILS: buff.my_battle_shout.down[false]         There were no recheck events to check.         Time spent on this action:  0.14ms         TimeData:Fury (IV)-precombat-3:commanding_shout:0.14:Ability Known, Enabled(0.04):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)          Completed precombat action list [ Fury (IV) - precombat ].          Processing default action list [ Fury (IV) - default ].                  Current recommendation was NO ACTION at +10.00s.                  4.   pummel ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-1:pummel:0.03:Ability Known, Enabled(0.03)                  5.   spell_reflection ( default - 2 ) - ability disabled ( toggle )         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-2:spell_reflection:0.03:Ability Known, Enabled(0.03)                  6.   intercept ( default - 3 )         The action is not ready ( 30.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-3:intercept:0.03:Ability Known, Enabled(0.03)                  7.   bloodrage ( default - 4 ) - ability disabled ( toggle )         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-4:bloodrage:0.03:Ability Known, Enabled(0.03)                  8.   shattering_throw ( default - 5 ) - ability disabled ( toggle )         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-5:shattering_throw:0.03:Ability Known, Enabled(0.03)                  9.   death_wish ( default - 6 ) - ability disabled ( toggle )         Time spent on this action:  0.04ms         TimeData:Fury (IV)-default-6:death_wish:0.04:Ability Known, Enabled(0.04)                  10.  heroic_fury ( default - 7 ) - talent [ heroic_fury ] missing         Time spent on this action:  0.02ms         TimeData:Fury (IV)-default-7:heroic_fury:0.02:Ability Known, Enabled(0.02)                  11.  recklessness ( default - 8 ) - ability disabled ( toggle )         Time spent on this action:  0.03ms         TimeData:Fury (IV)-default-8:recklessness:0.03:Ability Known, Enabled(0.03)                  12.  use_items ( default - 9 )         There is no criteria for Use Items.         + items         Current recommendation was NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items                  13.  sunder_armor ( default - 10 )         The action (sunder_armor) is usable at (0.00 + 1.44) with cost of 15 rage.          - the action is ready before the current recommendation (at +1.44 vs. +10.00).          - this entry's criteria FAILS: ( debuff.sunder_armor.stack[5.00] < 5 | debuff.sunder_armor.remains[32.25] < 5 ) & target.time_to_die[3589.56] > 15         Excluded 27.26 recheck time as it is outside our constraints ( 0.00 - 10.00 ).         There were no recheck events to check.         Time spent on this action:  0.18ms         TimeData:Fury (IV)-default-10:sunder_armor:0.18:Ability Known, Enabled(0.03):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.05):Post-Recheck Times(0.01):Post Recheck(0.00)                  14.  call_action_list:unknown ( default - 11 )         Criteria for ??? FAIL at +0.00 - active_enemies[1.00] > 1                  15.  bloodthirst ( default - 12 )         The action (bloodthirst) is usable at (0.00 + 1.44) with cost of 20 rage.          - the action is ready before the current recommendation (at +1.44 vs. +10.00).          - this entry has no criteria to test.         Action chosen:  bloodthirst at 1.44!         Time spent on this action:  0.15ms         TimeData:Fury (IV)-default-12:bloodthirst:0.15:Ability Known, Enabled(0.04):Post-TTR and Essential(0.06):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)         The recommended action (bloodthirst) is ready within the active GCD; exiting list (default).          Completed default action list [ Fury (IV) - default ].     Recommendation is bloodthirst at 0.00 + 1.44.     Recommendation #3 is bloodthirst at 1.44s (1.44s).     Time spent generating recommendations:  4.42ms

**Comment by Hekili** [comment]
This might be fixed with today's update.  If not, please submit a new ticket, correctly, and I'll investigate.

If you say the priority gets "stuck," you will probably want to look for error messages (/hekili > Warnings) and submit any messages you find there.
