### ISSUE TITLE
[BUG][Wrath] Enhancement Shaman when out of mana get snapshot error.

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#1648]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Enhancement Shaman when low/out of mana will give a snapshot report but the snap shots are empty.  Last thing the APL doesnt have a line to use Shamanistic Rage to refill mana.

### How to Reproduce

Enter game as Enhancement Shaman. 
Empty mana bar and attempt to use abilities.
Hekili will say snapshot error but they are empty.

### Player Information (Link)

https://pastebin.com/7AqZVcA3

### Error Messages (Link)

No Error messages

### Contact Information

Theo#2455

**Comment by Hekili** [comment]
Can you provide a screenshot of these empty Snapshots?  They appear as one line in the UI, but if you CTRL+A then CTRL+C, there is (usually) more information that you can paste per ticket instructions.

The addon does have default behavior to attempt to create a snapshot when it can't come up with recommendations, which it can't do if you have no mana.  I'll consider restricting that to only occur if you have resources to spend.

You can also disable the auto-snapshot in /hekili > Snapshots.

**Comment by Bingo176** [comment]
Nevermind on the empty snapshots. Basic way to reproduce is to empty your mana bar and attempt to do the rotation. It reappears when you get mana back. More of a minor inconvenience.

https://pastebin.com/vjA5b5V2 -- Interrupt
https://pastebin.com/xRhQNVAZ -- Defensives
https://pastebin.com/a8p6SPUH -- Cooldowns
https://pastebin.com/2SgsCYpg --  Primary
https://pastebin.com/84MMDyVs -- AoE

**Comment by Hekili** [comment]
This will be resolved in today's update.
