### ISSUE TITLE
[REC] Paladin/Holy active_dot.beacon_of_light = 0 never false

### ISSUE THREAD

**Issue by Jeffreyb723** [Hekili/hekili#1649]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I was expecting for the condition active_dot.beacon_of_light = 0 to return false if there is a Beacon of Light buff on any party or raid member. However it remains as the primary priority after casting it on anyone.

### How to Reproduce

1. Enter game as a Holy Paladin.
2. Cast Beacon of Light on yourself or any part or raid member.

### Snapshot (Link)

https://pastebin.com/Ern457mS

**Comment by Hekili** [comment]
I'll look into this.

**Comment by Hekili** [comment]
This should be resolved with today's update.
