### ISSUE TITLE
Some Issues with Fury.

### ISSUE THREAD

**Issue by Heelrea** [Hekili/hekili#165]
First issue is : when battle shout is missing, doesnt show it in bar. But for arms, it's ok.
Second issue : In multi target, dragon roar either never comes or come in pos 3 max in the queue list. 
I checked many times if it was an error, reinstalled it, tried alphas.

It feels like the APL is weird.

Currently playing with that : 

role="melee"
talents="2123123"
spec="fury"

head=",id=167778,bonus_id=6300/6298/1502/4786/6264/4775,azerite_powers=176/575/30/15/13"
neck=",id=158075,bonus_id=4932/4933/6316/699,azerite_level=51"
shoulder=",id=157932,bonus_id=1592/4786/5418/4775,azerite_powers=451/176/30/15/13,enchant_id=5900"
back=",id=155884,bonus_id=5010/1572/4786"
chest=",id=170537,bonus_id=1577/4786/5413/4775,azerite_powers=119/176/30/15/13"
wrist=",id=167783,bonus_id=6300/6291/1497/4786"
hands=",id=170336,bonus_id=6300/6291/1497/4786,enchant_id=5932"
waist=",id=167782,bonus_id=6300/6292/1502/4786"
legs=",id=165493,bonus_id=5126/1517/4786"
feet=",id=159679,bonus_id=5010/1582/5860/4784"
finger1=",id=165679,bonus_id=4803/1562/4786"
finger2=",id=159463,bonus_id=5009/1567/4786"
trinket1=",id=159625,bonus_id=5010/1572/4786"
trinket2=",id=169321"
main_hand=",id=165030,bonus_id=5252/5142/1487/4786"
off_hand=",id=159638,bonus_id=4779/1542/5850/4783"

**Comment by Hekili** [comment]
I can look into some of this, but please fill out a complete ticket with your info, snapshot, etc.

**Comment by Heelrea** [comment]
I'm sorry i've not done it correctly. Thanks for your incredible work in advance.

So it feels like the single target rotation is ok, but when doing a pack for example in mythic+, dragon roar barely shows up.

And Battle Shout is'nt showed up missing.

Thanks !

Charachter Data

build: v8.2.0-05-alpha4
level: 120 (120)
class: WARRIOR
spec: fury

talents: carnage
    double_time
    dragon_roar
    endless_rage
    siegebreaker
    sudden_death
    warpaint

azerite: azerite_empowered=3
    cold_steel_hot_blood=3
    infinite_fury=1
    overwhelming_power=3
    resounding_protection=3
    unbridled_ferocity=1

essences: [blood_of_the_enemy]=1, none

sets/legendaries/artifacts: none

gear:     deathguards_greaves=1
    electroarm_bludgeoner=1
    heart_of_azeroth=1
    highborne_compendium_of_sundering=1
    honorbound_centurions_breastplate=1
    loop_of_pulsing_veins=1
    ornate_elundris_ring=1
    parrotfeather_cloak=1
    pauldrons_of_rezans_bladeguard=1
    poens_deepsea_handguards=1
    sabatons_of_rampaging_elements=1
    sinister_gladiators_greatsword=1
    vial_of_animated_blood=1
    zanjir_scaleguard_armguards=1
    zanjir_scaleguard_faceguard=1
    zanjir_scaleguard_greatbelt=1

itemIDs: 155884, 157932, 158075, 159463, 159625, 159638, 159679, 165030, 165493, 165679, 167778, 167782, 167783, 169321, 170336, 170537

Snapshot :

build: v8.2.0-05-alpha4
level: 120 (120)
class: WARRIOR
spec: fury

talents: carnage
    double_time
    dragon_roar
    endless_rage
    siegebreaker
    sudden_death
    warpaint

azerite: azerite_empowered=3
    cold_steel_hot_blood=3
    infinite_fury=1
    overwhelming_power=3
    resounding_protection=3
    unbridled_ferocity=1

essences: [blood_of_the_enemy]=1, none

sets/legendaries/artifacts: none

gear:     deathguards_greaves=1
    electroarm_bludgeoner=1
    heart_of_azeroth=1
    highborne_compendium_of_sundering=1
    honorbound_centurions_breastplate=1
    loop_of_pulsing_veins=1
    ornate_elundris_ring=1
    parrotfeather_cloak=1
    pauldrons_of_rezans_bladeguard=1
    poens_deepsea_handguards=1
    sabatons_of_rampaging_elements=1
    sinister_gladiators_greatsword=1
    vial_of_animated_blood=1
    zanjir_scaleguard_armguards=1
    zanjir_scaleguard_faceguard=1
    zanjir_scaleguard_greatbelt=1

itemIDs: 155884, 157932, 158075, 159463, 159625, 159638, 159679, 165030, 165493, 165679, 167778, 167782, 167783, 169321, 170336, 170537

New Recommendations for [ Primary ] requested at 02:23:57 ( 475727.20 ).

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00 ).
 - rage, 73 / 100

Processing precombat action list [ Fury - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.

[001] potion ( precombat - 5 ) - ability disabled.

[002] recklessness ( precombat - 6 )
The action is not ready before our maximum delay window (15.00) for this query.
Completed precombat action list [ Fury - precombat ].

Processing default action list [ Fury - default ].
Current recommendation was NO ACTION at +60.00s.

[003] charge ( default - 1 )
The action (charge) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.

[004] pummel ( default - 2 ) - ability disabled.

[005] potion ( default - 3 ) - ability disabled.

[006] furious_slash ( default - 4 ) - ability unknown

[007] rampage ( default - 5 )
The action (rampage) is usable at (0.00 + 0.09) with cost of 75.
 - the action is ready before the current recommendation (at +0.09 vs. +60.00).
 - this entry's criteria FAILS: cooldown.recklessness.remains[62.47] < 3
There were no recheck events to check.

[008] recklessness ( default - 6 )
The action is not ready before our maximum delay window (15.00) for this query.

[009] whirlwind ( default - 7 )
The action (whirlwind) is usable at (0.00 + 0.00) with cost of 0.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: spell_targets.whirlwind[3.00] > 1 & ! buff.meat_cleaver.up[false]
Action chosen:  whirlwind at 0.00!
Completed default action list [ Fury - default ].
Recommendation is whirlwind at 0.00 + 0.00.
Recommendation #1 is whirlwind at 0.00s (0.00s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.01 ).
 - rage, 79 / 100

Processing precombat action list [ Fury - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.

[001] potion ( precombat - 5 ) - ability disabled.

[002] recklessness ( precombat - 6 )
The action is not ready before our maximum delay window (15.00) for this query.
Completed precombat action list [ Fury - precombat ].

Processing default action list [ Fury - default ].
Current recommendation was NO ACTION at +60.00s.

[003] charge ( default - 1 )
The action (charge) is unusable at (0.00 + 1.01) because ability 'usable' function returned false without explanation.

[004] pummel ( default - 2 ) - ability disabled.

[005] potion ( default - 3 ) - ability disabled.

[006] furious_slash ( default - 4 ) - ability unknown

[007] rampage ( default - 5 )
The action (rampage) is usable at (0.00 + 1.01) with cost of 75.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
 - this entry's criteria FAILS: cooldown.recklessness.remains[61.55] < 3
There were no recheck events to check.

[008] recklessness ( default - 6 )
The action is not ready before our maximum delay window (15.00) for this query.

[009] whirlwind ( default - 7 )
The action (whirlwind) is usable at (0.00 + 1.01) with cost of 0.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
 - this entry's criteria FAILS: spell_targets.whirlwind[3.00] > 1 & ! buff.meat_cleaver.up[true]
There were no recheck events to check.

[010] ramping_amplitude_gigavolt_engine ( default - 8 )
The action (ramping_amplitude_gigavolt_engine) is unusable at (0.00 + 0.00) because item not equipped.

[011] use_items ( default - 9 )
There is no criteria for Use Items.
Current recommendation was NO ACTION at +60.00s.

[012] blood_of_the_enemy ( items - 1 )
The action is not ready before our maximum delay window (15.00) for this query.

[013] vial_of_animated_blood ( items - 2 )
The action is not ready before our maximum delay window (15.00) for this query.
Returned from Use Items; current recommendation is NO ACTION (+60.00).

[014] blood_fury ( default - 10 )
The action is not ready before our maximum delay window (15.00) for this query.

[015] berserking ( default - 11 ) - ability unknown

[016] lights_judgment ( default - 12 ) - ability unknown

[017] fireblood ( default - 13 ) - ability unknown

[018] ancestral_call ( default - 14 ) - ability unknown

[019] run_action_list ( default - 15 )
There is no criteria for this action list..
Action list (single_target) was found.
+ [single_target]
Current recommendation was NO ACTION at +60.00s.

[020] siegebreaker ( single_target - 1 )
The action is not ready before our maximum delay window (15.00) for this query.

[021] rampage ( single_target - 2 )
The action (rampage) is usable at (0.00 + 1.01) with cost of 75.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
List ( single_target ) called from ( Fury:default:15 ) would PASS at 1.01.
 - NONE
 - this entry's criteria FAILS: buff.recklessness.up[false] | ( talent.frothing_berserker.enabled[false] | talent.carnage.enabled[true] & ( buff.enrage.remains[4.19] < gcd.execute[1.01] | rage.current[85.30] > 90 ) | talent.massacre.enabled[false] & ( buff.enrage.remains[4.19] < gcd.execute[1.01] | rage.current[85.30] > 90 ) )
There are 4 recheck events.
List ( single_target ) called from ( Fury:default:15 ) would PASS at 2.53.
 - NONE
Recheck #1 ( +2.53 ) MET: buff.recklessness.up[false] | ( talent.frothing_berserker.enabled[false] | talent.carnage.enabled[true] & ( buff.enrage.remains[2.67] < gcd.execute[1.01] | rage.current[94.75] > 90 ) | talent.massacre.enabled[false] & ( buff.enrage.remains[2.67] < gcd.execute[1.01] | rage.current[94.75] > 90 ) )
Action chosen:  rampage at 2.53!

[022] execute ( single_target - 3 )
The action (execute) is unusable at (0.00 + 1.01) because ability 'usable' function returned false without explanation.

[023] bladestorm ( single_target - 4 ) - ability unknown

[024] bloodthirst ( single_target - 5 )
The action (bloodthirst) is usable at (0.00 + 1.01) with cost of -8.
 - the action is ready before the current recommendation (at +1.01 vs. +2.53).
List ( single_target ) called from ( Fury:default:15 ) would PASS at 1.01.
 - NONE
 - this entry's criteria PASSES: buff.enrage.down[false] | azerite.cold_steel_hot_blood.rank[3.00] > 1
Action chosen:  bloodthirst at 1.01!

[025] raging_blow ( single_target - 6 )
The action is not ready in time ( 1.01 vs. 1.01 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.

[026] dragon_roar ( single_target - 7 )
The action is not ready in time ( 1.01 vs. 1.01 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.

[027] bloodthirst ( single_target - 8 )
The action is not ready in time ( 1.01 vs. 1.01 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.

[028] raging_blow ( single_target - 9 )
The action is not ready in time ( 1.01 vs. 1.01 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.

[029] furious_slash ( single_target - 10 ) - ability unknown
The recommended action (bloodthirst) would be ready before the next GCD (1.01 < 1.01); exiting list (single_target).
Returned from list (single_target), current recommendation is bloodthirst (+1.01).
- [single_target]
Added single_target to blocklist as it was called via RAL.
Completed default action list [ Fury - default ].
Recommendation is bloodthirst at 0.00 + 1.01.
Recommendation #2 is bloodthirst at 1.01s (1.01s).
Advancing clock by 1.01...

RECOMMENDATION #3 ( Offset: 1.02, GCD: 1.01 ).
 - rage, 93 / 100

Processing precombat action list [ Fury - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.

[001] potion ( precombat - 5 ) - ability disabled.

[002] recklessness ( precombat - 6 )
The action is not ready before our maximum delay window (15.00) for this query.
Completed precombat action list [ Fury - precombat ].

Processing default action list [ Fury - default ].
Current recommendation was NO ACTION at +60.00s.

[003] charge ( default - 1 )
The action (charge) is unusable at (1.02 + 1.01) because ability 'usable' function returned false without explanation.

[004] pummel ( default - 2 ) - ability disabled.

[005] potion ( default - 3 ) - ability disabled.

[006] furious_slash ( default - 4 ) - ability unknown

[007] rampage ( default - 5 )
The action (rampage) is usable at (1.02 + 1.01) with cost of 75.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
 - this entry's criteria FAILS: cooldown.recklessness.remains[60.53] < 3
There were no recheck events to check.

[008] recklessness ( default - 6 )
The action is not ready before our maximum delay window (15.00) for this query.

[009] whirlwind ( default - 7 )
The action (whirlwind) is usable at (1.02 + 1.01) with cost of 0.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
 - this entry's criteria FAILS: spell_targets.whirlwind[3.00] > 1 & ! buff.meat_cleaver.up[true]
There were no recheck events to check.

[010] ramping_amplitude_gigavolt_engine ( default - 8 )
The action (ramping_amplitude_gigavolt_engine) is unusable at (1.02 + 0.00) because item not equipped.

[011] use_items ( default - 9 )
There is no criteria for Use Items.
Current recommendation was NO ACTION at +60.00s.

[012] blood_of_the_enemy ( items - 1 )
The action is not ready before our maximum delay window (15.00) for this query.

[013] vial_of_animated_blood ( items - 2 )
The action is not ready before our maximum delay window (15.00) for this query.
Returned from Use Items; current recommendation is NO ACTION (+60.00).

[014] blood_fury ( default - 10 )
The action is not ready before our maximum delay window (15.00) for this query.

[015] berserking ( default - 11 ) - ability unknown

[016] lights_judgment ( default - 12 ) - ability unknown

[017] fireblood ( default - 13 ) - ability unknown

[018] ancestral_call ( default - 14 ) - ability unknown

[019] run_action_list ( default - 15 )
There is no criteria for this action list..
Action list (single_target) was found.
+ [single_target]
Current recommendation was NO ACTION at +60.00s.

[020] siegebreaker ( single_target - 1 )
The action is not ready before our maximum delay window (15.00) for this query.

[021] rampage ( single_target - 2 )
The action (rampage) is usable at (1.02 + 1.01) with cost of 75.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
List ( single_target ) called from ( Fury:default:15 ) would PASS at 1.01.
 - NONE
 - this entry's criteria PASSES: buff.recklessness.up[false] | ( talent.frothing_berserker.enabled[false] | talent.carnage.enabled[true] & ( buff.enrage.remains[3.17] < gcd.execute[1.01] | rage.current[93.30] > 90 ) | talent.massacre.enabled[false] & ( buff.enrage.remains[3.17] < gcd.execute[1.01] | rage.current[93.30] > 90 ) )
Action chosen:  rampage at 1.01!

[022] execute ( single_target - 3 )
The action is not ready in time ( 1.01 vs. 1.01 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.

[023] bladestorm ( single_target - 4 ) - ability unknown
The recommended action (rampage) would be ready before the next GCD (1.01 < 1.01); exiting list (single_target).
Returned from list (single_target), current recommendation is rampage (+1.01).
- [single_target]
Added single_target to blocklist as it was called via RAL.
Completed default action list [ Fury - default ].
Recommendation is rampage at 1.02 + 1.01.
Recommendation #3 is rampage at 1.01s (2.03s).
Advancing clock by 1.01...

RECOMMENDATION #4 ( Offset: 2.04, GCD: 1.01 ).
 - rage, 24 / 100

Processing precombat action list [ Fury - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.

[001] potion ( precombat - 5 ) - ability disabled.

[002] recklessness ( precombat - 6 )
The action is not ready before our maximum delay window (15.00) for this query.
Completed precombat action list [ Fury - precombat ].

Processing default action list [ Fury - default ].
Current recommendation was NO ACTION at +60.00s.

[003] charge ( default - 1 )
The action (charge) is unusable at (2.04 + 1.01) because ability 'usable' function returned false without explanation.

[004] pummel ( default - 2 ) - ability disabled.

[005] potion ( default - 3 ) - ability disabled.

[006] furious_slash ( default - 4 ) - ability unknown

[007] rampage ( default - 5 )
The action is not ready before our maximum delay window (15.00) for this query.

[008] recklessness ( default - 6 )
The action is not ready before our maximum delay window (15.00) for this query.

[009] whirlwind ( default - 7 )
The action (whirlwind) is usable at (2.04 + 1.01) with cost of 0.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
 - this entry's criteria PASSES: spell_targets.whirlwind[3.00] > 1 & ! buff.meat_cleaver.up[false]
Action chosen:  whirlwind at 1.01!

[010] ramping_amplitude_gigavolt_engine ( default - 8 )
The action (ramping_amplitude_gigavolt_engine) is unusable at (2.04 + 0.00) because item not equipped.
The recommended action (whirlwind) would be ready before the next GCD (1.01 < 1.01); exiting list (default).
Completed default action list [ Fury - default ].

**Comment by Hekili** [comment]
Should be resolved in alpha.
