### ISSUE TITLE
[BUG] Rogue not working properly

### ISSUE THREAD

**Issue by 10kmw01** [Hekili/hekili#1652]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not loading anything for rogue Action Pack I believe you call it.  It does not let me select assassination, sub, or combat for a priority list.  At this moment I have re-downloaded the addon, grabbed a bugzapper in case, and made sure all the settings were correct to make anything visible.  I then tried to see if I could grab a priority list elsewhere but I dont think im that saavy :D.  bug zapper

### How to Reproduce

Play a Rogue

### Player Information (Link)

https://pastebin.com/rQKLgAi7

### Error Messages (Link)

https://pastebin.com/rQKLgAi7

**Comment by Hekili** [comment]
Rogue is not yet implemented.
