### ISSUE TITLE
[BUG] trying to open on PTR

### ISSUE THREAD

**Issue by deeg427** [Hekili/hekili#1653]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

not loading on my BM huntere i have a bug sack report comijng in 

### How to Reproduce

1. sign in 
2. attempt to open hekili
3. bug report comes up 

### Player Information (Link)

build: v9.2.7-1.0.0b level: 60 (60) class: HUNTER spec: beast_mastery  talents: none  pvptalents: none  covenant: night_fae  conduits: bloodletting = 13    condensed_anima_sphere = 13    marksmans_advantage = 13    one_with_the_beast = 13    rejuvenating_wind = 13    spirit_attunement = 13  soulbinds: [dreamweaver]    cunning_dreams = 1    dream_delver = 1    field_of_blossoms = 1    podtender = 1    somnambulist = 1    soothing_voice = 1  sets: dreadfire_vessel = 1     ring_of_collapsing_futures = 1     scars_of_fraternal_strife = 1     tier28 = 4  gear: dreadfire_vessel = 1     ring_of_collapsing_futures = 1     scars_of_fraternal_strife = 1     tier28 = 4  legendaries: none  itemIDs: none  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 3     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Beast Mastery     petbased = false     potion = spectral_agility     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     avoid_bw_overlap = false     barbed_shot_grace_period = 0.5     check_pet_range = true  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      aspect_of_the_cheetah = 6   [01]     aspect_of_the_turtle  = 9   [01]     barbed_shot           = 1   [02], S5  [06]     bestial_wrath         = 2   [02], S2  [06]     binding_shot          = S=  [06]     cobra_shot            = 4   [02], S1  [06]     counter_shot          = 4   [01]     disengage             = 7   [01]     freezing_trap         = =   [01]     intimidation          = 1   [01]     kill_command          = 3   [02]     kill_shot             = S3  [06]     tranquilizing_shot    = 2   [01]     wing_clip             = =   [02]

### Error Messages (Link)

2x Interface/AddOns/Hekili/Core.lua:47: attempt to index global 'InterfaceOptionsFrameOkay' (a nil value) [string "@Interface/AddOns/Hekili/Core.lua"]:47: in function <Interface/AddOns/Hekili/Core.lua:46>  Locals: (*temporary) = nil (*temporary) = nil (*temporary) = "attempt to index global 'InterfaceOptionsFrameOkay' (a nil value)" ns = <table> {  specTemplate = <table> {  }  hasRequiredResources = <function> defined @Interface/AddOns/Hekili/State.lua:6883  IsTimer = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22  serializeActionList = <function> defined @Interface/AddOns/Hekili/Options.lua:10645  forecastResources = <function> defined @Interface/AddOns/Hekili/State.lua:1256  frameProfile = <table> {  }  UnregisterUnitEvent = <function> defined @Interface/AddOns/Hekili/Events.lua:208  Localize = <table> {  }  setClass = <function> defined @Interface/AddOns/Hekili/Classes.lua:5649  debug = <table> {  }  GetTexString = <function> defined @Interface/AddOns/Hekili/Utils.lua:603  dumpNameplateInfo = <function> defined @Interface/AddOns/Hekili/Targets.lua:482  queue = <table> {  }  SetTimer = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22  addWhitespace = <function> defined @Interface/AddOns/Hekili/Classes.lua:5597  AddToSuperMark = <function> defined @Interface/AddOns/Hekili/Utils.lua:671  addSetting = <function> defined @Interface/AddOns/Hekili/Classes.lua:5582  storeAbilityElements = <function> defined @Interface/AddOns/Hekili/Classes.lua:5660  spendResources = <function> defined @Interface/AddOns/Hekili/State.lua:6475  safeMax = <function> defined @Interface/AddOns/Hekili/Utils.lua:240  updateMinion = <function> defined @Interface/AddOns/Hekili/Targets.lua:550  safeAbs = <function> defined @Interface/AddOns/Hekili/Utils.lua:252  RegisterUnitEvent = <function> defined @Interface/AddOns/Hekili/Events.lua:165  AbilitySettings = <function> defined @Interface/AddOns/Hekili/Options.lua:3656  attr = <table> {  }  RecycleTable = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22  updateEssences = <function> defined @Interface/AddOns/Hekili/Events.lua:615  AddTexString = <function> defined @Interface/AddOns/Hekili/Utils.lua:591  actorHasDebuff = <function> defined @Interface/AddOns/Hekili/Targets.lua:593  StopEventHandler = <function> defined @Interface/AddOns/Hekili/Events.lua:119  SpaceOut = <function> defined @Interface/AddOns/Hekili/Utils.lua:53  getModifier = <function> defined @Interface/AddOns/Hekili/Targets.lua:633  roundUp = <function> defined @Interface/AddOns/Hekili/Utils.lua:136  deserializeDisplay = <function> defined @Interface/AddOns/Hekili/Options.lua:10545  ResourceRegenerates = <function> defined @Interface/AddOns/Hekili/Constants.lua:94  print = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:94  wipeDebuffs = <function> defined @Interface/AddOns/Hekili/Targets.lua:586  GetResourceInfo = <function> defined @Interface/AddOns/Hekili/Constants.lua:73  round = <function> defined @Interface/AddOns/Hekili/Utils.lua:129  GetResourceKey = <function> defined @Interface/AddOns/Hekili/Constants.lua:83  GetResourceID = <function> defined @Interface/AddOns/Hekili/Constants.lua:78  Audit = <function> defined @Interface/AddOns/Hekili/Targets.lua:785  updateGear = <function> defined @Interface/AddOns/Hekili/Events.lua:709  eliminateUnit = <function> defined @Interface/AddOns/Hekili/Targets.lua:728  castsOff = <table> {  }  commitKey = <function> defined @Interface/AddOns/Hekili/Utils.lua:169  multiUnpack = <function> defined @Interface/AddOns/Hekili/Utils.lua:114  orderedPairs = <function> defined @Interface/AddOns/Hekili/Utils.lua:223  numMyTargets = <function> defined @Interface/AddOns/Hekili/Targets.lua:537  CachedGetItemInfo = <function> defined @Interface/AddOns/Hekili/Utils.lua:573  StartEventHandler = <function> defined @Interface/AddOns/Hekili/Events.lua:89  PetActions = <table> {  }  numTargets = <function> defined @Interface/AddOns/Hekili/Targets.lua:534  StopConfiguration = <function> defined @Interface/AddOns/Hekili/UI.lua:333  FeignEvent = <function> defined @Interface/AddOns/Hekili/Events.lua:221  Tooltip = HekiliTooltip {  }  formatKey

### Contact Information

johnston_427@hotmail.com

**Comment by Hekili** [comment]
I have not created a release for DF beta/PTR at this time.
