### ISSUE TITLE
[BUG] no recommendations show in game for Fury warr Wotlk classic

### ISSUE THREAD

**Issue by pozzer18** [Hekili/hekili#1654]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

when fury is selected i get no options for the rotation there are two warning showing in the warning section

Warning 1

Returned unknown string 'applyBufF' in state metatable [Fury (IV):default:12].

[string "@Interface\AddOns\Hekili\State.lua"]:2214: in function <Interface\AddOns\Hekili\State.lua:1863>
    [string "@Interface\AddOns\Hekili\Wrath\Warrior.lua"]:864: in function `handler'
[string "@Interface\AddOns\Hekili\State.lua"]:6039: in function `RunHandler'
        [string "@Interface\AddOns\Hekili\Core.lua"]:1980: in function <Interface\AddOns\Hekili\Core.lua:1482>

Warning 2

Update: Interface\AddOns\Hekili\Wrath\Warrior.lua:864: attempt to call global 'applyBufF' (a nil value)

[string "@Interface\AddOns\Hekili\Wrath\Warrior.lua"]:864: in function `handler'
[string "@Interface\AddOns\Hekili\State.lua"]:6039: in function `RunHandler'
    [string "@Interface\AddOns\Hekili\Core.lua"]:1980: in function <Interface\AddOns\Hekili\Core.lua:1482>

### How to Reproduce

load game and select Fury as the active priority

### Player Information (Link)

https://pastebin.com/rxZe2z0g

### Error Messages (Link)

https://pastebin.com/KkTcDGWF

### Contact Information

Pozzer#8576

**Comment by Hekili** [comment]
The fix for this issue will be posted later today.
