### ISSUE TITLE
[BUG] Not work for mage ? 

### ISSUE THREAD

**Issue by FluuXuux** [Hekili/hekili#1655]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello, Hekili is fine for all my others char but i just conect on my mage and no one work on him , like fire, frost or arcane ? ty

### How to Reproduce

1. enter game as a mage
2. the mage doesnt exist

### Player Information (Link)

https://pastebin.com/QrUmvxgT

### Error Messages (Link)

https://pastebin.com/QrUmvxgT

### Additional Information

no more informations

### Contact Information

FluuXuux

**Comment by SpatenLa** [comment]
you are correct. mage does not exist

**Comment by Hekili** [comment]
Mage will be released when it's released.  Thanks for your patience.

**Comment by FluuXuux** [comment]
Thx for answer and thx for your beautiful work .
