### ISSUE TITLE
[BUG] [WotLK] Events.lua:1753: GetSpellCooldown(): Invalid spell slot

### ISSUE THREAD

**Issue by AlrikOlson** [Hekili/hekili#1656]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When logged onto a Shadow Priest at level 70, every spell cast causes this Lua error:

```
Message: Interface\AddOns\Hekili\Events.lua:1753: GetSpellCooldown(): Invalid spell slot
Time: Fri Oct 14 09:44:19 2022
Count: 155
Stack: Interface\AddOns\Hekili\Events.lua:1753: GetSpellCooldown(): Invalid spell slot
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSpellCooldown'
[string "@Interface\AddOns\Hekili\Events.lua"]:1753: in function <Interface\AddOns\Hekili\Events.lua:1559>
[string "@Interface\AddOns\Hekili\Events.lua"]:1847: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:57: in function <Interface\AddOns\Hekili\Events.lua:49>

Locals: 
```

Here is what is displayed in the Hekili Settings -> Warnings menu:

`UNK: cooldown.global_cooldown.id`

### How to Reproduce

1. Install latest version of addon via CurseForge (`Hekili-v3.4.0-1.0.0-beta7a`)
2. Log into a 70 Shadow Priest
3. Attack target dummy (or any target for that matter)
4. Notice Lua errors as described

### Player Information (Link)

https://pastebin.com/0t96Npka

### Error Messages (Link)

https://pastebin.com/eAs47YzM

**Comment by Hekili** [comment]
Yeah, that'll happen on a not-yet-supported class.  Will fix.

**Comment by AlrikOlson** [comment]
> Yeah, that'll happen on a not-yet-supported class. Will fix.

Is there a list of supported classes for WotLK somewhere?
