### ISSUE TITLE
[BUG] Addon doesn't load for priest - works for other classes

### ISSUE THREAD

**Issue by dirde** [Hekili/hekili#1657]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not loading anything for my shadow priest, when I check the menu it doesn't have a class listed on the left column. The addons works wonderfully on my other classes like shaman, hunter and druid. I've been trying to do some troubleshooting and I loaded up BugSack but it said everything honky dory.

### How to Reproduce

1. Enter game as a priest (shadow in this case)
2. No priorities are suggested, no icons show up.

### Player Information (Link)

https://pastebin.com/Kin7FrJx

### Error Messages (Link)

None

**Comment by SpatenLa** [comment]
There is no Version that includes Priest yet.
