### ISSUE TITLE
[BUG] Dont work whit my rogue

### ISSUE THREAD

**Issue by Akaarimune** [Hekili/hekili#1658]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I just installed it, I don't see it with my rogue but with my druid I have tried and if it does, I haven't touched any option

### How to Reproduce

does not appear

### Player Information (Link)

https://pastebin.com/K1P7D7xS

### Error Messages (Link)

no error messages

### Additional Information

I've been waiting for months to have it in wotlk thanks for your work

### Contact Information

criss#3444

**Comment by SpatenLa** [comment]
There is no version that include Rogue yet.

**Comment by Akaarimune** [comment]
oh :( , do you know when you will implement it?
