### ISSUE TITLE
Pocket-Sized Computation Device to a viable action within addon APL

### ISSUE THREAD

**Issue by PaulVlahosCS** [Hekili/hekili#166]
**Describe the Bug/Issue**
When trying to add Pocket-Sized Computation Device to the APLs it doesn't come up in the drop down of viable actions.

**To Reproduce**
- Go to Priorities -> Any Spec -> Action Lists Tab
- Try to add a new action and click the drop down under Action
- Pocket-Sized Computation Device is not in there

**Expected behavior**
I should be able to add the Pocket-Sized Computation Device trinket individually. The logic for it is: use_item,name=pocketsized_computation_device,if=!buff.recklessness.up&!debuff.siegebreaker.up

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

https://paste.ee/p/oEfTZ
 
**PUT SNAPSHOT LINK HERE:**

N/A. There is no error caught by bugsack/bugcatcher.

**Comment by Hekili** [comment]
Should work in latest alpha.
