### ISSUE TITLE
[BUG] Unknown issue more logging for refrence

### ISSUE THREAD

**Issue by pozzer18** [Hekili/hekili#1660]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

warning generated by the addon, no visual impact in game

### How to Reproduce

play as unholy DK

Update: Interface\AddOns\Hekili\State.lua:2536: attempt to compare number with nil

[string "@Interface\AddOns\Hekili\State.lua"]:2536: in function <Interface\AddOns\Hekili\State.lua:2494>
[string "@Interface\AddOns\Hekili\Wrath\DeathKnight.lua"]:1829: in function `usable'
[string "@Interface\AddOns\Hekili\State.lua"]:6941: in function `IsUsable'
[string "@Interface\AddOns\Hekili\Core.lua"]:949: in function `GetPredictionFromAPL'
[string "@Interface\AddOns\Hekili\Core.lua"]:1420: in function `GetNextPrediction'
[string "@Interface\AddOns\Hekili\Core.lua"]:1824: in function <Interface\AddOns\Hekili\Core.lua:1482>

### Player Information (Link)

https://pastebin.com/uP0r1nbv

### Error Messages (Link)

https://pastebin.com/TmMkyCGc

### Contact Information

Pozzer#8576

**Comment by Hekili** [comment]
Fix will be posted soon.
