### ISSUE TITLE
[REC] Ghoul Frenzy recommended w/o a Ghoul Pet

### ISSUE THREAD

**Issue by pozzer18** [Hekili/hekili#1661]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

ghoul detection is still not working correctly, i get the recomendation to use ghoul frenzy when i dont have an active ghoul.

usually caused by using death pact or just forgetting to summon a ghoul. 

### How to Reproduce

have the ghoul frenzy talken as unholy and then run a combat  with out a ghoul up. 

### Snapshot (Link)

https://pastebin.com/TqUkehyT

### Contact Information

Pozzer#8576

**Comment by Hekili** [comment]
I'm not able to replicate this issue.  Can you tell me more about when this happens?  Did you have a ghoul up that died?

**Comment by pozzer18** [comment]
When using sacrifical pact to regen health it still detects the pet. Even tho I have killed the pet for health

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
