### ISSUE TITLE
[BUG] FindUnitBuffByID lua Error

### ISSUE THREAD

**Issue by Kwixii** [Hekili/hekili#1662]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Every Fight i get a .lua error for the FindUnitBuffByID and my game is always telling me im not in range.

### How to Reproduce

1. Playing as Affliction Warlock
2. Sometimes as Demo Warlock
3. Generell being in Fight
4. Group in Fight and not in Range

### Player Information (Link)

https://pastebin.com/6jWsSExQ

### Error Messages (Link)

https://pastebin.com/4KKWFPqS

### Contact Information

cJ ♥ Kwixii | Matrinix#0964

**Comment by Hekili** [comment]
Thanks, this will be a pretty quick fix.

**Comment by Hekili** [comment]
This will be fixed later today.
