### ISSUE TITLE
Mage Prio list is missing

### ISSUE THREAD

**Issue by aaronoo7** [Hekili/hekili#1663]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hi, I am playing made in WOTLK and i cannot choose spec priority and there it wont come up in display for rotation. It says none under profiles.

I have other charcters like paladin and DK, it works fine for them but not Mage.

Thanks,

Aaron.

### How to Reproduce

Mage Frost spec

### Player Information (Link)

http://github.com/Hekili/hekili/issues

### Error Messages (Link)

None

**Comment by aaronoo7** [comment]
Playing Mage* apologies.

**Comment by SpatenLa** [comment]
you are correct. Mage is not yet implemented in Hekili for WotLK

**Comment by aaronoo7** [comment]
for the entire expansion or for now? Thank you

**Comment by Hekili** [comment]
I will resume working on additional classes for Wrath after DF prepatch launches and stabilizes.

**Comment by gunhoss710** [comment]
are any of the specs working for mage or none of them? i noticed it wasnt popping up on my mage which is fire but havent tried the other two. it gives me a notice on my mage saying hekili isnt supported under lvl 50 so i was assuming maybe it would pop up for me at lvl 50. thank you for your time. love the addon works great on my other characters!
