### ISSUE TITLE
Unholy DK DW/MORB Spec Priority off Wowhead.

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#1665]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The links for the guides you are using are from Icy-Veins/Wowtbc.gg.  But neither of those use Unholy DK Dual Wield/Morb spec that is currently the top unholy dk spec in the game. Is there a way to make this possible?  Frost looks great though!

### How to Reproduce

Not an issue, moreso wrong guide.

### Snapshot (Link)

Not needed

### Contact Information

Pulse#0223

**Comment by Hekili** [comment]
I'm aware of the alternate build.  Wrath updates will be on hold until after Dragonflight prepatch launches and stabilizes.
