### ISSUE TITLE
[BUG] Wrath Nothing show up on my spriest version 3.4.0-1.0.0 -beta8

### ISSUE THREAD

**Issue by Nikker69** [Hekili/hekili#1668]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I dl the add on and nothig show up on my screen I can still see the option or the blueprint of where I can place my icone but when out of the option pannel nothing show on my screen 
- its enable 
- There is no alpha transpenrency on the visibility tab

### How to Reproduce

...

### Player Information (Link)

build: v3.4.0-1.0.0-beta8 level: 80 (80) class: PRIEST spec: priest  talents: none  pvptalents: none  covenant: none  conduits: none  soulbinds: none  sets: none  gear: amulet_of_the_spell_flinger = 1     chilly_slobberknocker = 1     clerics_linen_shoes = 1     forgotten_shadow_hood = 1     gianthair_woven_gloves = 1     girdle_of_bane = 1     heroes_robe_of_faith = 1     illustration_of_the_dragon_soul = 1     mainhand_2h = 1     resurgent_phantom_bindings = 1     runed_mana_band = 1     shoulders_of_the_northern_lights = 1     subterranean_waterfall_shroud = 1     tabard_of_the_kirin_tor = 1     the_egg_of_mortal_essence = 1     the_horsemans_seal = 1     valorous_pants_of_faith = 1     wand_of_the_sanlayn = 1  legendaries: none  itemIDs: 37177, 37408, 37684, 37730, 37843, 39390, 39515, 40432, 40457, 40685, 41821, 43157, 43181, 43283, 43285, 45808, 49123  settings: none  toggles:     cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = automatic      potions = true   keybinds: 

### Error Messages (Link)

there is no error message

### Contact Information

lnbouchard@gmail.com

**Comment by SpatenLa** [comment]
thats correct, there is no version that includes shadow priest yet.

**Comment by Nikker69** [comment]
Any chance you guys can have a Eta on when will it be avalible?

**Comment by Hekili** [comment]
I will resume working on additional classes for Wrath after DF prepatch launches and stabilizes.
