### ISSUE TITLE
 Can you add Repeat Performance to the rotation?

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#167]
Hello. In the raid, I encountered a Repeat Performance spell that prohibits using 2 times the same spell. Is it possible to do something like this so that the addon tracks the debuff and prevents the spells from repeating? Thank. The debuff itself is https://www.wowhead.com/spell=304410/repeat-performance

**Comment by Hekili** [comment]
Right now, the alpha version of the addon treats any ability you just used as though it is unavailable until Repeat Performance falls off (creating a 'delay').  This will leave the addon to select the next best ability that is available sooner, if there is one.  If not, the addon would select the current ability with a long delay, which would be an indicator to use an off-GCD ability and then use the ability.

I haven't done the fight yet, so I don't know how well this is working.

Ideally, you would use off GCD interrupts, stuns, possibly even defensive CDs, etc. to set yourself up to avoid the effect.  But none of that works directly with any specialization's priority list.

Short answer is it's more complicated to do anything else more elaborate.  The alternative I've considered is:

Blacklist the last ability while RP is up.  Allow the user to specify 2 backup abilities for Repeat Performance.  If the addon can't recommend anything while blacklisted, suggest the 1st backup ability.  If the 1st backup ability is blacklisted, suggest the 2nd.

Got any other suggestions?

**Comment by geraint425** [comment]
I think that I rather simply will even put downing or still some ability in rotation. I so believe that 100% to avoid dumbness not to turn out.

**Comment by geraint425** [comment]
And one moment. I would like to clarify how to deal with the ADK with the definition of goals. Now my goals are not correct. In the earlier versions, I could use the definition of the objectives of the ability, and near the radius. And now I only define by radius. This can be done so that I can, as in earlier versions, determine by the radius and the targets from the dot spell?

**Comment by Hekili** [comment]
I'm not sure what you're asking but I don't think we're still on the same topic any more.
