### ISSUE TITLE
[REC] Protection Warrior - Victory Rush recommended with Impending Victory Talented.

### ISSUE THREAD

**Issue by arcanechocolate** [Hekili/hekili#1671]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Victory Rush is being recommended even when Impending Victory is talented to the point where both can be present in the queue simultaneously.

### How to Reproduce

Kill a mob to trigger "Victorious" buff (killing blow) which will introduce Victory Rush into the recommendation for the generic portion of the priority list.
It might be required to use a few other skills in order to advance the queue and see Victory Rush (often even paired with Impending Victory).

### Snapshot (Link)

https://pastebin.com/jKcNU6z8

**Comment by Hekili** [comment]
Thanks; I will disable Victory Rush when Impending Victory is talented.
