### ISSUE TITLE
DK blood rotation AOE 3 targets seem to freeze on recommended. Overlook rotation aoe.

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#1673]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Blood Tank DK the priority on aoe agains 3 targets doesnt seem to fuction properly almost like the recomendation freezes after i put Death and decay down until next recomendation shows.

### How to Reproduce

1. Enter the game as Blood DK
2. fight against 3 targets 
3. follow the hekili rotation helper
4. The aoe rotation doesnt show next reccomendation as fast as i want it almost freezes. very clunky compare to single target rotation.
5. Single target seems fine.

### Snapshot (Link)

https://pastebin.com/7f6HgwzJ

### Additional Information

1. Wonder if u can overlook the rotation so it feels smoother on the aoe part from Wowhead as it descripes better then icy veins imo.
2.  Add mitigation prio exampel when my char is 50% it recommends icebound fortitude or another defensive that i can add by myself that trigger when its reach number % hp 
3. Can i tweak and how? So deathstrike is recommended when my DK have below 75hp as mitigation on the rotation.
4. Ty for the best addon ever <3

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
