### ISSUE TITLE
Hekilli No longer showing as of 10.0.0 Prepatch

### ISSUE THREAD

**Issue by T0xicsmog** [Hekili/hekili#1677]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

as in title, the addon is not loading correctly with the prepatch release

### How to Reproduce

load addon even when out of date. does not show

### Player Information (Link)

https://pastebin.com/bq7fJCc6

### Error Messages (Link)

idk

### Contact Information

Toxicsmog#9149

**Comment by TheHambrick** [comment]
Hekili has not released a 10.0 version of the addon at the time of this post

**Comment by xathian** [comment]
Hekili relies on Simulationcraft APLs as the base for the rotation it displays for you. You will have to wait until your classes community theorycrafters devise an APL for the current class redesigns. As it stands this will likely take a while, you can track the progress of APLs being submitted to Simulationcraft from this google docs page

https://docs.google.com/spreadsheets/d/e/2PACX-1vSCfqvYso2z8Ir8LZ3NhRYn5vcQXaTAOAi9GbY_hhjnl02L-QKMX1K_c9kyXRLXuGE08dl0wBLRzF-C/pubhtml#

As you can see, very few have an APL even in beta. Some class communities such as Warrior and Priest have had their usual APL creators straight up say they won't be wasting their time devising an APL for pre-patch so you won't be seeing those until launch, and they will be focused around level 70. You'll probably have to do without Hekili for a month or so

Someone could potentially just copy over the old APLs and fixed any issues regarding missing abilities or drastic changes but those would be borderline useless as the priorities likely HEAVILY changed with Dragonflight talent changes and you'd probably get the same DPS just mashing your buttons

**Comment by karpana** [comment]
Thank-you for the awesome tracking spreadsheet.

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/197943622-45eea389-f542-4a58-818a-2e2752bf946c.png)
Known issue from [https://github.com/BigWigsMods/packager](https://github.com/BigWigsMods/packager/commit/439a2f12e22ab111bfa704a577872a1f58731ebd) (As Hekili uploaded a file an hour ago, but its marked as 1.0.0)

**Comment by N6REJ** [comment]
only class I see it showing for is for Guardian druid.  I hope we can at least get it working the way it was while its being updated.

**Comment by TheHambrick** [comment]
> only class I see it showing for is for Guardian druid. I hope we can at least get it working the way it was while its being updated.

The talent overhaul is massive for pretty much every spec and their priority. Any recommendation the addon would give you based on the old priorities would be effectively useless. Asking to have it working while it's being updated is like asking the mechanic if you can take your car on a road trip while he's fixing the engine.

**Comment by T0xicsmog** [comment]
> Hekili relies on Simulationcraft APLs as the base for the rotation it displays for you. You will have to wait until your classes community theorycrafters devise an APL for the current class redesigns. As it stands this will likely take a while, you can track the progress of APLs being submitted to Simulationcraft from this google docs page
> 
> https://docs.google.com/spreadsheets/d/e/2PACX-1vSCfqvYso2z8Ir8LZ3NhRYn5vcQXaTAOAi9GbY_hhjnl02L-QKMX1K_c9kyXRLXuGE08dl0wBLRzF-C/pubhtml#
> 
> As you can see, very few have an APL even in beta. Some class communities such as Warrior and Priest have had their usual APL creators straight up say they won't be wasting their time devising an APL for pre-patch so you won't be seeing those until launch, and they will be focused around level 70. You'll probably have to do without Hekili for a month or so
> 
> Someone could potentially just copy over the old APLs and fixed any issues regarding missing abilities or drastic changes but those would be borderline useless as the priorities likely HEAVILY changed with Dragonflight talent changes and you'd probably get the same DPS just mashing your buttons

Rogue APL's have been updated, that spreadsheet has not been updated

**Comment by Cubano0o** [comment]
has the new 10.0 verison come out yet bc i dont see it. i use wowup and its still on that 9.2 version. and the addon isnt appearing on my screen.

**Comment by Wyste** [comment]
> has the new 10.0 verison come out yet bc i dont see it. i use wowup and its still on that 9.2 version. and the addon isnt appearing on my screen.

You need to change the channel to the BETA channel in WoWUp. After that you'll see version v10.1.0betaX.
![image](https://user-images.githubusercontent.com/5103286/198294803-1d63fa57-8823-4047-acae-fe3a88c2a052.png)

**Comment by T0xicsmog** [comment]
Not officially I don't think. There's some class support for beta versions
which U can get off the github

**Comment by hdn1217** [comment]
Hi, I love your APP but I am having a small problem.  The third action bar placed on my screen with the Pre Patch is covering up the hekili Bars.  Is there a way to move either of them so that will not be overlapping?

Thanks,

**Comment by vond82** [comment]
Either move the bars with the games built in Edit Mode
Or move the Hekili bars with /hekili (it'll show up on your screen then as movable bars)

**Comment by hdn1217** [comment]
Thanks.What are the steps to use the /hekilli command to move it up one level on the screen?ThanksHowardSent from my iPhoneOn Nov 21, 2022, at 11:32 AM, Patrik Högberg ***@***.***> wrote:﻿
Either move the bars with the games built in Edit Mode
Or move the Hekili bars with /hekili (it'll show up on your screen then as movable bars)

**Comment by hdn1217** [comment]
Hi,

 

I can bring up your options page using  /hekili command, but I don’t know what I should do then to bring your bars up a level so as to not hide behind the game bars…..HELP ☺

 

Thanks,

Howard

 

From: Patrik Högberg ***@***.***>
Reply-To: Hekili/hekili ***@***.***>
Date: Monday, November 21, 2022 at 11:31 AM
To: Hekili/hekili ***@***.***>
Cc: hdn1217 ***@***.***>, Comment ***@***.***>
Subject: Re: [Hekili/hekili] Hekilli No longer showing as of 10.0.0 Prepatch (Issue #1677)

 

Either move the bars with the games built in Edit Mode
Or move the Hekili bars with /hekili (it'll show up on your screen then as movable bars)

**Comment by TheHambrick** [comment]
> Hi, I can bring up your options page using  /hekili command, but I don’t know what I should do then to bring your bars up a level so as to not hide behind the game bars…..HELP ☺ Thanks, Howard From: Patrik Högberg ***@***.***> Reply-To: Hekili/hekili ***@***.***> Date: Monday, November 21, 2022 at 11:31 AM To: Hekili/hekili ***@***.***> Cc: hdn1217 ***@***.***>, Comment ***@***.***> Subject: Re: [Hekili/hekili] Hekilli No longer showing as of 10.0.0 Prepatch (Issue #1677) Either move the bars with the games built in Edit Mode Or move the Hekili bars with /hekili (it'll show up on your screen then as movable bars) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Just drag the abilities bar in edit mode or the hekili bar away from each other

**Comment by hdn1217** [comment]
Thanks for your help.  All I had to do was to do was to temporary disable the game bars, which were hiding your bar, move your bar up a little and then turn the game bars back on….

 

Cheers,

Howard

 

From: TheHambrick ***@***.***>
Reply-To: Hekili/hekili ***@***.***>
Date: Wednesday, November 23, 2022 at 2:17 PM
To: Hekili/hekili ***@***.***>
Cc: hdn1217 ***@***.***>, Comment ***@***.***>
Subject: Re: [Hekili/hekili] Hekilli No longer showing as of 10.0.0 Prepatch (Issue #1677)

 

Hi, I can bring up your options page using /hekili command, but I don’t know what I should do then to bring your bars up a level so as to not hide behind the game bars…..HELP ☺ Thanks, Howard From: Patrik Högberg @.> Reply-To: Hekili/hekili @.> Date: Monday, November 21, 2022 at 11:31 AM To: Hekili/hekili @.> Cc: hdn1217 @.>, Comment @.> Subject: Re: [Hekili/hekili] Hekilli No longer showing as of 10.0.0 Prepatch (Issue #1677) Either move the bars with the games built in Edit Mode Or move the Hekili bars with /hekili (it'll show up on your screen then as movable bars) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

Just drag the abilities bar in edit mode or the hekili bar away from each other
