### ISSUE TITLE
When Left-clicked to drag and reposition, interface "sticks" to cursor and cursor is no longer responsive to anything. 

### ISSUE THREAD

**Issue by tracyneproski** [Hekili/hekili#1678]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Initially, the addon wasn't showing at all, so I went into my settings and reset the profile. After I clicked the Primary and AOE tabs, the interface became visible. When I left-clicked to drag the interface to a different part of the screen, it got stuck to my cursor and wouldn't release. I pushed Esc to get out of the Hekili options and the options closed, but the interface was still stuck to the cursor. I wasn't able to click anything with the cursor at that point, not even menus, so I had to force quit the game to get out. Tried on a different character/class and the same thing happened.

### How to Reproduce

1. Enter game.
2. Open Hekili options
3. Reset profile.
4. Left click on interface to reposition
5. Push Esc to close Hekili options dialog box.
6. Force quit game as cursor is no longer responsive.

### Player Information (Link)

https://pastebin.com/Zb0KLrS8

### Error Messages (Link)

https://pastebin.com/9cV9JgK1

**Comment by Hekili** [comment]
No new tickets until I actually post a Dragonflight release.  Reports for the 9.2.7 release will be outdated.

**Comment by auddie2015** [comment]
Here as well, Hekili. Just to confirm his report.
