### ISSUE TITLE
Demo Warlock Demonic Core Freeze

### ISSUE THREAD

**Issue by L3bulba** [Hekili/hekili#1679]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Anytime Demonic Core has Proc'd for demonology warlock Hekili freezes until all demonic core procs have been expended. 

### How to Reproduce

1. Cast standard rotation to get Demonic Core to proc.
2. While Demonic core buff is active Hekili will not refresh its recommended spell.
3. Expend all demonic core stacks to resume Hekili refreshing

### Player Information (Link)

https://pastebin.com/c4nZfJzm

### Error Messages (Link)

no error

### Additional Information

I understand there are a lot of moving parts with the new expac. Just thought I would report this incase it was flying under the radar. 

You are doing amazing work out there. 

Cheers.

### Contact Information

Discord: Lebulba#2311

**Comment by Hekili** [comment]
9.2.7 versions are out of date; Warlock is not yet supported in Dragonflight.
