### ISSUE TITLE
Trinket not showing in 'Gear and Trinkets' Section

### ISSUE THREAD

**Issue by Triggersad** [Hekili/hekili#168]
Please describe your idea or feature and when it would be useful.
Hello, this is most likely coming in the new beta or something...but a couple of trinkets arent showing. 

pocket sized computation device - https://www.wowhead.com/item=167555/pocket-sized-computation-device

and 
Ashvane's Razer Coral - https://ptr.wowhead.com/item=169311/ashvanes-razor-coral&bonus=4798:1487

**Comment by Rogue1337** [comment]
Same for me, the Pocket Sized Compulation Device isnt showing at all in the Rotation, specifically the Cyclotronic Blast trinket, is this intended? Im using the latest Alpha

**Comment by Hekili** [comment]
Try the latest alpha!

**Comment by Rogue1337** [comment]
Sry for askin again but i did download the latest Alpha, the Trinket is in the Trinket List but its not getting recommend for me at all, it doesnt appear in the Rotation, still talking about the Cyclotronic Blast Trinket not the Ashvane one

**Comment by Hekili** [comment]
Can you complete a problem ticket with all the required information then?  I'll want a snapshot when you're not seeing Cyclotronic Blast with the latest alpha.
