### ISSUE TITLE
[REC] RET PALADIN, NOT RECOMMENDING RADIANT DECREE and EXORCISM. 

### ISSUE THREAD

**Issue by Ratayu** [Hekili/hekili#1680]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my retribution paladin, when I talent for Radiant Decree and Exorcism these are not being recommended,

1. Radiant Decree (which replaces Wake of Ashes) - I observe that the addon still recommends Wake of Ashes even though the ability has been replaced nor do I have enough holy power to use Radiant Decree even if it was a icon display issue.
2. Exorcism - The ability is not recommended at all.

### How to Reproduce

1. Enter game as ret paladin with Radiant Decree and Exorcism talents selected.
2. Enter combat on training dummy
3. See that it recommends Wake of Ashes instead of Radiant Decree. 
4. Continue to build and spend holy power, see that it never recommends Exorcism
5. See that neither abilities are listed in rotation addon. 

### Snapshot (Link)

https://pastebin.com/QuK6ABqi

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/npxy2GXvgE9MtJzpcpQxdV

### Contact Information

Ratayu#0795

**Comment by Hekili** [comment]
Noted.  I have not yet updated the Retribution module for DF.  Thanks.

**Comment by Ratayu** [comment]
Just downloaded latest update(Hekili-v10.0.0-02.zip) and radiant decree and exorcism are not being recommended.  You stated in this fix addressing radiant decree not being recommend and it being recommended when it should not be. Just wanted to give you a heads up. @Hekili

**Comment by Ratayu** [comment]
> Just downloaded latest update(Hekili-v10.0.0-02.zip) and radiant decree and exorcism are not being recommended.  You stated in this fix addressing radiant decree not being recommend and it being recommended when it should not be. Just wanted to give you a heads up. @Hekili 

Update: I saw in other tickets folks recommended to reset the default priority and that seemed to resolve the problem. I haven't fully tested the rotation but wanted to update you.

**Comment by Hekili** [comment]
This is resolved in the latest release.
