### ISSUE TITLE
[REC] [Dragonflight] - Enhancement Shaman - Covenant ability, Windfury Weapon, Trinkets

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1681]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Covenant abilities are recommended in areas where I cannot use them, for example in BFA. Tested as NF on Enhancement shaman.
Windfury Weapon issue - I have Windfury weapon as the first recommended spell, but even if I press it as much as I want, it still shows up in the menu in the first place, it's like in a cycle. And it's well casted, I can see that in the cast history. And same situation happened with Windfury Totem but with different talents (without Doom Winds talent).
Trinkets problem - Trinkets with use abilities are recommended even if they are on cooldown.
### How to Reproduce

1. Enter the game as Enhancement shaman with NF.
2. Go to BFA dummies.
3. Try rotation.

### Snapshot (Link)

https://pastebin.com/kbMfV8YX

### Contact Information

Markô#2877

**Comment by Hekili** [comment]
Try -beta2.

**Comment by pingitoreluiz** [comment]
Thats seems to happen if you have windfury totem talent selected. Tried -beta2 and no fix

**Comment by marekCs** [comment]
me to, trying beta 2 now and I have 2 windfury totems in the icon list (ST and AOE as well).
pastebin: [https://pastebin.com/8p4q1894](https://pastebin.com/8p4q1894)

**Comment by Bsirk** [comment]
I also had this same issue. I'll attach the snapshot so you can see

https://pastebin.com/YnmBxV2w

**Comment by Hekili** [comment]
If this issue persists with 05.1 or later, please add a comment with an updated snapshot and your talent string.  Thanks.
