### ISSUE TITLE
DF - Make Windfury totem as an ability I can only cast within x yards of the target.

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1682]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Just a thought. A lot of times when running to a pack in M+, Windfury Totem is the first spell recommended and the second spell is a spell that can be cast from a distance. It would be nice if Windury Totem didn't interfere with this and it could only be cast when standing at melee distance from the target. For example, the condition target.distance < 10?

### Contact Information

Markô#2877

**Comment by Yaooti** [comment]
target.within9
