### ISSUE TITLE
[REC] Vengeance DH; Fel Devastation rec. without req. Fury; Covenant Ability rec. outside of Shadowlands

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#1683]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With 10.0 pre-patch, Veng. DH Fel Devastation requires 50 Fury to cast, however its recommanded already with 30 Fury. Addition of "Fury >= 50" as an ability condition fixes that problem.

I also noticed, when outside of Shadowlands zones, Elysian Decree (Covenant Ability) is being recommanded. I did not spec into the new talent tree ability. (see this Snapshot: https://pastebin.com/6B71YZkM)

### How to Reproduce

When tanking, starve yourself of Fury while Fel Devastation is the queued ability. Most of the time there is enough fury, so this bug will not occur very often. However while testing with dummies, I ran into that a few times. 

For Elysian Decree, just leave Shadowlands and it will recommand it, although its unusable.

### Snapshot (Link)

https://pastebin.com/SmzgCECy

### Contact Information

mrJones2k#2881

**Comment by Hekili** [comment]
Were there any messages in the Warnings section of the addon?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/28655236/198037327-695c6184-b3fb-49ce-a1c2-0cd212b0194f.png)

nothing coinciding with the time of taking the snapshot

**Comment by ghost** [comment]
> Unknown buff: prepared [Havoc:normal:2]
> 
> [string "@Interface/AddOns/Hekili/State.lua"]:3793: in function <Interface/AddOns/Hekili/State.lua:3784>
>     [string "return buff.prepared.down"]:1: in main chunk
>     [string "=[C]"]: in function `pcall'
> [string "@Interface/AddOns/Hekili/Scripts.lua"]:919: in function `EmulateSyntax'
>         [string "@Interface/AddOns/Hekili/Scripts.lua"]:1193: in function <Interface/AddOns/Hekili/Scripts.lua:1184>
>             [string "@Interface/AddOns/Hekili/Scripts.lua"]:1505: in function `LoadScripts'
> [string "@Interface/AddOns/Hekili/Scripts.lua"]:1594: in function `LoadScripts'
>                 [string "@Interface/AddOns/Hekili/Core.lua"]:1480: in function <Interface/AddOns/Hekili/Core.lua:1478>

upon entering the game, this error is thrown (just updated to beta2

**Comment by ghost** [comment]
Similarly, with beta7 I get a recommandation for soul cleave, although there is not enough fury available: https://pastebin.com/BXkGVJey

**Comment by ghost** [comment]
Regarding the covenant abilities: when I simply test IsUsableSpell("Elysian Decree") ingame, it returns the expected behaviour. In Shadowlands its true, in dalaran e.g. its not true. I could not find in your code where or if that ingame function is applied for every spell recommandation.

**Comment by ghost** [comment]
I found a fix for the elysian decree problem: https://github.com/Hekili/hekili/pull/1730 with other small fixes.

The fury problem is not 100% reproducible on my end either.
