### ISSUE TITLE
[FEATURE] [Dragonflight] - Balance Druid - Target Swaps and player's screen

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1685]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

When I have the swap hint checked and I'm casting Starfall, at least on the dummies at NF it makes me swap targets with sunfire,moonfire spell, but at first glance it's not obvious where my targets are everywhere. I found them after a while, somewhere behind me off screen. Would it be possible to just focus on what I see on the screen? If I see 5 targets, do you recommend swapping to just those, even though I probably hit the targets behind me with Starfall?

### Contact Information

Markô#2877

**Comment by Hekili** [comment]
With nameplates enabled, this is viable and makes sense.  I'm testing something along these lines now.

**Comment by Hekili** [comment]
This has been implemented in the retail release.
