### ISSUE TITLE
[BUG] UH DK, Priority does not progress or progresses sporadically

### ISSUE THREAD

**Issue by tcarlsen86** [Hekili/hekili#1687]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Some abilities cause the tracker to progress other abilities it gets stuck on. Unholy blight is one that it seems to get stuck on. May affect other class but have only tested UH dk.

### How to Reproduce

1. Enter as DK
2. Spec unholy
3. try to attack and go through priority
4. priority doesn't always progress

### Player Information (Link)

https://pastebin.com/D9nANCsS

### Error Messages (Link)

no error

### Contact Information

Oni#1975

**Comment by Hekili** [comment]
Thanks.  I haven't posted the DK updates yet.
