### ISSUE TITLE
primal primer build isnt working enchacement

### ISSUE THREAD

**Issue by greganbu** [Hekili/hekili#169]
during bfa i used the primal primer x3 build for enchacement and the addon sense it and changed but now that i change back to the build it keep having me cast stromstrike over the hot hand 10 stacks of primal primer and rockbiter. i even went to the actions tab and switch to freezerburn_core thing and still using stromstrike and building malstrom over using hot buff/10 stack of PP. not for sure what happen in a recent update but its not working. guess ill switch back to stromstrike build till its fixed

**Comment by Hekili** [comment]
Submit a proper ticket with the requested information to from the template.

**Comment by Hekili** [comment]
I'll need your build information, gear information, and a snapshot when you think it should recommend Lava Lash but recommended Stormstrike instead.

Keep in mind, "Frezerburn" really kicks in with 2+ Primal Primer stacks, Hot Hand, and Hailstorm.
