### ISSUE TITLE
[BUG] [Dragonflight] Hek throwing an error when looting

### ISSUE THREAD

**Issue by snoblitz** [Hekili/hekili#1691]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When looting any mob or treasure, Hek is throwing an error. BugGrabber in pastebin below.

### How to Reproduce

1. Kill a thing
2. Loot the thing
3. See the error

### Player Information (Link)

https://pastebin.com/jCJXcvh1

### Error Messages (Link)

https://pastebin.com/7pSHWykA

**Comment by Hekili** [comment]
You can download a beta version for Dragonflight (with only a handful of specs supported), but please do not submit tickets while using a Shadowlands version of the addon.
