### ISSUE TITLE
[ERROR] Core.lua:47: attempt to index global 'InterfaceOptionsFrameOkay'

### ISSUE THREAD

**Issue by daxigua249121589** [Hekili/hekili#1693]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Got error when I want to open the hekili panel.

1x Interface/AddOns/Hekili/Core.lua:47: attempt to index global 'InterfaceOptionsFrameOkay' (a nil value)
[string "@Interface/AddOns/Hekili/Core.lua"]:47: in function <Interface/AddOns/Hekili/Core.lua:46>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'InterfaceOptionsFrameOkay' (a nil value)"
ns = <table> {
 FindPlayerAuraByID = <function> defined @Interface/AddOns/Hekili/Utils.lua:514
 specTemplate = <table> {
 }
 hasRequiredResources = <function> defined @Interface/AddOns/Hekili/State.lua:6950
 IsTimer = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 forecastResources = <function> defined @Interface/AddOns/Hekili/State.lua:1268
 frameProfile = <table> {
 }
 UnregisterUnitEvent = <function> defined @Interface/AddOns/Hekili/Events.lua:216
 Localize = <table> {
 }

More Error information please see the **Error Messages (Link)**

### How to Reproduce

1. Enter game as a frost mage.
2. open the hekili control panel.
3. got error and cannot open the panel.
 

### Player Information (Link)

cannot open it

### Error Messages (Link)

https://pastebin.com/LEPcCZBU

### Contact Information

DaXiGua#2635

**Comment by daxigua249121589** [comment]
This is the only Error(1/1) which the bugsack show

**Comment by Hekili** [comment]
Thanks, this will be fixed in the next build.  You can open the addon's options via `/hekili` in the meantime.
