### ISSUE TITLE
Windfury Totem being repeatedly recommended.

### ISSUE THREAD

**Issue by jankozilla** [Hekili/hekili#1696]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Enhancement Shaman, the prio helper always shows Windfury and Flametongue weapon in the list even if I cast it, it seems to not be aware that the buffs are applied.

### How to Reproduce

1.Log in World of Warcraft
2. Log on enhancement shaman
3. Cast windfury and flametongue on self.
4, Helper should still be recommending you cast those 2 spells.

### Snapshot (Link)

https://pastebin.com/3t7Z5Aas

### Contact Information

Janko#2971

**Comment by Hekili** [comment]
I'm not able to replicate this on my end.  Please provide the following:

1. Check /hekili > Warnings and select/copy each warning listed and paste here.
2. Type `/dump GetWeaponEnchantInfo()` in-game (with your imbues applied) and paste that information here.

**Comment by jankozilla** [comment]
1. Update: Interface/AddOns/Hekili/State.lua:5779: table index is nil

[string "@Interface/AddOns/Hekili/State.lua"]:5779: in function `ResetQueues'
[string "@Interface/AddOns/Hekili/State.lua"]:6080: in function `reset'
    [string "@Interface/AddOns/Hekili/Core.lua"]:1541: in function <Interface/AddOns/Hekili/Core.lua:1478>
        
        
2. [1]=true;
[2]=3501584
[3]=0
[4]=5401
[5]=true
[6]=3503184
[7]=0
[8]=5400

**Comment by snoblitz** [comment]
I also am seeing this. I actually had to disable them to fix it for now.

**Comment by Wulfknightz** [comment]
Here is the warnings that are popping up for this. I get same thing on the dump command
Update: Interface/AddOns/Hekili/Classes.lua:114: attempt to compare number with string

[string "@Interface/AddOns/Hekili/Classes.lua"]:114: in function `generate'
[string "@Interface/AddOns/Hekili/State.lua"]:3611: in function <Interface/AddOns/Hekili/State.lua:3569>
[string "@Interface/AddOns/Hekili/State.lua"]:3665: in function <Interface/AddOns/Hekili/State.lua:3569>
[string "@Interface/AddOns/Hekili/State.lua"]:3662: in function <Interface/AddOns/Hekili/State.lua:3569>
[string "@Interface/AddOns/Hekili/Dragonflight/ShamanEnhancement.lua"]:803: in function `hook'
    [string "@Interface/AddOns/Hekili/Classes.lua"]:5643: in function `callHook'
[string "@Interface/AddOns/Hekili/State.lua"]:6268: in function `reset'
        [string "@Interface/AddOns/Hekili/Core.lua"]:1541: in function <Interface/AddOns/Hekili/Core.lua:1478>

![Untitled](https://user-images.githubusercontent.com/116749530/198088482-57be0fff-ea27-457d-8c31-fd799e348bb6.png)

**Comment by Hekili** [comment]
Which version of the addon are you using?

**Comment by Wulfknightz** [comment]
Hekili-v10.1.0-beta3.zip

**Comment by jankozilla** [comment]
Hekili-v10.1.0-beta3.zip

**Comment by Wulfknightz** [comment]
Enhancement; Primary - Windfury Weapon(0.00), Flametongue Weapon(1.08), Windfury Totem(2.17)
build: v10.1.0-beta4
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ancestral_defense
    ancestral_guidance
    ashen_catalyst
    astral_bulwark
    astral_shift
    capacitor_totem
    chain_lightning
    earth_elemental
    elemental_blast
    elemental_spirits
    elemental_warding
    elemental_weapons
    feral_spirit
    fire_and_ice
    flurry
    frost_shock
    hailstorm
    healing_stream_totem
    hot_hand
    ice_strike
    improved_lightning_bolt
    improved_maelstrom_weapon
    lashing_flames
    lava_burst
    lava_lash
    maelstrom_weapon
    molten_assault
    natures_fury
    raging_maelstrom
    spirit_walk
    storms_wrath
    stormstrike
    sundering
    swirling_currents
    swirling_maelstrom
    thundershock
    thunderstorm
    wind_rush_totem
    wind_shear
    windfury_totem
    windfury_weapon
    winds_of_alakir
    witch_doctors_ancestry

pvptalents: none

covenant: night_fae

conduits: essential_extraction = 13
   magma_fist = 10
   refreshing_waters = 10
   spiritual_resonance = 13
   thunderous_paws = 13
   vital_accretion = 10

soulbinds: [niya]
   bonded_hearts = 1
   grove_invigoration = 1
   niyas_tools_burrs = 1
   run_without_tiring = 1
   survivors_rally = 1
   swift_patrol = 1

sets: scars_of_fraternal_strife = 1

gear: blue_martial_shirt = 1
    boneshatter_waistguard = 1
    dominations_deliverance = 1
    dormazains_tenderizer = 1
    elegy_of_the_eternals = 1
    loquacious_keepers_peridot = 1
    scars_of_fraternal_strife = 1
    shadowghast_ring = 1
    tabard_of_the_lightbringer = 1
    theurgic_starspeakers_adornment = 1
    theurgic_starspeakers_howl = 1
    theurgic_starspeakers_ringmail = 1
    theurgic_starspeakers_runebindings = 1
    theurgic_starspeakers_shawl = 1
    theurgic_starspeakers_tassets = 1
    winters_stampeding_striders = 1
    worldkiller_iris = 1
    wristwraps_of_nights_renewal = 1

legendaries: seeds_of_rampant_growth = 1
    witch_doctors_wolf_bones = 1

itemIDs: 172328, 178926, 186387, 188253, 188270, 188920, 188922, 188923, 188924, 188925, 188927, 189795, 189797, 189802, 189818, 189859, 42374, 52252

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    filler_shock = true
    pad_lava_lash = true
    pad_windstrike = true

toggles:     cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    ancestral_guidance        = S6  [06]
    astral_shift              = Q   [03]
    capacitor_totem           = 4   [02], S7  [06]
    chain_heal                = 8   [02]
    chain_lightning           = 5   [01]
    earth_elemental           = 3   [02], S2  [06]
    earthbind_totem           = 7   [02], S9  [06]
    elemental_blast           = 7   [01], S-  [06]
    fae_transfusion           = 0   [01]
    feral_spirit              = -   [01]
    fireblood                 = 0   [02], SMwU[03]
    flame_shock               = 2   [01]
    flametongue_weapon        = -   [07]
    frost_shock               = 3   [01]
    ghost_wolf                = ,   [04]
    healing_stream_totem      = 6   [02], S0  [06]
    healing_surge             = E   [03]
    healthstone               = R   [03]
    ice_strike                = S8  [06]
    lava_burst                =
    lava_lash                 = 6   [01]
    lightning_bolt            = 4   [01]
    lightning_shield          = 9   [07]
    purge                     = 9   [02]
    scars_of_fraternal_strife = =   [01]
    spirit_walk               = .   [04]
    stormstrike               = 1   [01]
    sundering                 = 8   [01]
    thunderstorm              = S=  [06]
    tremor_totem              = 5   [02]
    water_walking             = 7   [07]
    wind_rush_totem           = S4  [06]
    wind_shear                = MwU [04]
    windfury_totem            = 1   [02], S1  [06]
    windfury_weapon           = 0   [07]
    windstrike                = 1   [01]



player_buffs:
   192106 - lightning_shield                         -   1 - 1217.36
   186401 - *sign_of_the_skirmisher                  -   1 - 3600.00
   368636 - the_second_rune                          -   1 - 3600.00
   369439 - elegy_of_the_eternals                    -   1 - 3600.00
   368635 - the_first_rune                           -   1 - 3600.00

player_debuffs:

target_auras:  target does not exist


New Recommendations for [ Primary ] requested at 11:42:27 ( 1016143.01 ); using built-in ( Enhancement ) priority.
*** START OF NEW DISPLAY: Primary ***

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Enhancement - precombat ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        1.   windfury_weapon ( precombat - 1 )
        The action (windfury_weapon) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry has no criteria to test.
        Action chosen:  windfury_weapon at 0.00!
    
    Completed precombat action list [ Enhancement - precombat ].
    Recommendation is windfury_weapon at 0.00 + 0.00.
    Recommendation #1 is windfury_weapon at 0.00s (0.00s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.08, Casting: 0.00 ).

    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Enhancement - precombat ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        1.   windfury_weapon ( precombat - 1 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Enhancement-precombat-1:windfury_weapon:0.01:Ability Known, Enabled(0.01)
        
        2.   flametongue_weapon ( precombat - 2 )
        The action (flametongue_weapon) is usable at (0.00 + 1.08).
         - the action is ready before the current recommendation (at +1.08 vs. +10.00).
         - this entry has no criteria to test.
        Action chosen:  flametongue_weapon at 1.08!
        Time spent on this action:  0.09ms
        TimeData:Enhancement-precombat-2:flametongue_weapon:0.09:Ability Known, Enabled(0.02):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)
        The recommended action (flametongue_weapon) is ready within the active GCD; exiting list (precombat).
    
    Completed precombat action list [ Enhancement - precombat ].
    
    Processing default action list [ Enhancement - default ].
        
        Current recommendation was flametongue_weapon at +1.08s.
        The recommended action (flametongue_weapon) is ready within the active GCD; exiting list (default).
    
    Completed default action list [ Enhancement - default ].
    Recommendation is flametongue_weapon at 0.00 + 1.08.
    Recommendation #2 is flametongue_weapon at 1.08s (1.08s).

RECOMMENDATION #3 ( Offset: 1.09, GCD: 1.08, Casting: 0.00 ).

    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Enhancement - precombat ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        1.   windfury_weapon ( precombat - 1 )
        The action is not ready ( 3598.91 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Enhancement-precombat-1:windfury_weapon:0.01:Ability Known, Enabled(0.01)
        
        2.   flametongue_weapon ( precombat - 2 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Enhancement-precombat-2:flametongue_weapon:0.01:Ability Known, Enabled(0.01)
        
        3.   lightning_shield ( precombat - 3 )
        The action is not ready ( 1096.27 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Enhancement-precombat-3:lightning_shield:0.02:Ability Known, Enabled(0.02)
        
        4.   windfury_totem ( precombat - 5 )
        The action (windfury_totem) is usable at (1.09 + 1.08) with cost of 150 mana.
         - the action is ready before the current recommendation (at +1.08 vs. +10.00).
         - this entry's criteria PASSES: ! runeforge.doom_winds.equipped[false]
        Action chosen:  windfury_totem at 1.08!
        Time spent on this action:  0.15ms
        TimeData:Enhancement-precombat-5:windfury_totem:0.15:Ability Known, Enabled(0.02):Post-TTR and Essential(0.07):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.03):Post Recheck(0.00):Action Stored(0.01)
        The recommended action (windfury_totem) is ready within the active GCD; exiting list (precombat).
    
    Completed precombat action list [ Enhancement - precombat ].
    
    Processing default action list [ Enhancement - default ].
        
        Current recommendation was windfury_totem at +1.08s.
        The recommended action (windfury_totem) is ready within the active GCD; exiting list (default).
    
    Completed default action list [ Enhancement - default ].
    Recommendation is windfury_totem at 1.09 + 1.08.
    Recommendation #3 is windfury_totem at 1.08s (2.17s).
    Time spent generating recommendations:  1.10ms

**Comment by Hekili** [comment]
Please test -beta5 and confirm if this is resolved for you.

**Comment by adamsalem** [comment]
> Please test -beta5 and confirm if this is resolved for you.

I was having the same issue and Beta 5 resolves it, thanks!

**Comment by Hekili** [comment]
Thanks for confirming!

**Comment by jankozilla** [comment]
works on my side aswell, thx Hekili.
