### ISSUE TITLE
Lua Error Balance Druid

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1697]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Was about to start doing damage to dummy with balance druid and got lua error.

### How to Reproduce

Went to dummies in Orgrimmar as balance , targeted dummy to start doing damage, get lua error.

### Player Information (Link)

https://pastebin.com/UrsJAC05

### Error Messages (Link)

https://pastebin.com/NU4VHQF1

**Comment by Hekili** [comment]
Thanks, this should be fixed in beta5.
