### ISSUE TITLE
[BUG] Whirlwind recommended as if with no cooldown when Storm of Swords is talented

### ISSUE THREAD

**Issue by addicu** [Hekili/hekili#1698]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon is suggesting Whirlwind as if it has no cooldown when using Storm of Swords.

Storm of Swords
Talent
Requires Warrior (Fury)
Whirlwind has a 7.0 sec cooldown, but deals 70% increased damage.

Slam has a 12.0 sec cooldown and generates 10 Rage, but deals 100% increased damage.

### How to Reproduce

1. Active AoE APL

### Snapshot (Link)

https://pastebin.com/aB3EQGVp

**Comment by Wyste** [comment]
Fury as a Class/spec is supported, but the APL hasn't been updated for Dragonflight yet. This snapshot appears to be using the SL APL from before the update (which would have been stored in your SavedVariables) even after updating the addon. 
You will likely have to wait for an APL to be written for Fury that is DF compatible.

**Comment by addicu** [comment]
Understood.

**Comment by addicu** [comment]
Just for clarification, the spellID on Whirlwind shouldn't matter, correct? With the Storm of Swords altered Whirlwind being 190411 and the one without CD 1680.

**Comment by xathian** [comment]
It's not perfect, but if you want a roughly functional APL (better than nothing) you can take the one from Raidbots. Just run a Quick Sim of your character then choose "Full HTML Report" then scroll to the APL section and basically just copy paste each line into Hekili's Priority list.

It ain't pretty but it's updated for DF talents, the biggest caveat, and it's a big one, is that Raidbots APLs are entirely single target only right now.

**Comment by addicu** [comment]
Okay, cool! thank you

**Comment by Hekili** [comment]
This should be resolved in the latest beta versions.
