### ISSUE TITLE
[BUG]  hekili does not appear on the screen after I installed the latest version

### ISSUE THREAD

**Issue by drkrox** [Hekili/hekili#1699]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Today I updated the addon and when I entered the game it no longer appears on the screen, I did everything and nothing, maybe it is an error, please help im shadow priest

### How to Reproduce

sacerdote sombras

### Player Information (Link)

build: v10.1.0-beta3 level: 60 (60) class: PRIEST spec: shadow  talents: none  pvptalents: none  covenant: necrolord  conduits: clear_mind = 13    dissonant_echoes = 13    haunting_apparitions = 13    lights_inspiration = 13    mental_recovery = 13    rabid_shadows = 13  soulbinds: [maestro_de_plagas_marileth]    kevins_oozeling = 1    oozs_frictionless_coating = 1    plagueborn_cleansing_slime = 1    ultimate_form = 1    undulating_maneuvers = 1    volatile_solvent = 1  sets: fleshrenders_meathook = 1  gear: amito_de_los_empreos = 1     amuleto_del_ltimo_guardin = 1     anillo_atesorado_de_ritualista = 1     bculo_del_teniente_juraexnimes = 1     camisa_de_filigrana_de_bano = 1     cantoral_de_cabalista = 1     cinturn_de_velo_lgubre = 1     fleshrenders_meathook = 1     gancho_de_desgarracarne = 1     hbito_de_los_empreos = 1     leotardos_de_los_empreos = 1     mantn_de_los_empreos = 1     mitones_de_velo_lgubre = 1     pulseras_de_los_empreos = 1     sello_de_saltheril = 1     sobrecapa_de_los_empreos = 1     tabardo_de_la_avanzada_de_la_muerte = 1     zapatillas_sucias_del_suplicante = 1  legendaries: pallid_command = 1     shadowflame_prism = 1  itemIDs: 110002, 137532, 142207, 169049, 173244, 173248, 183037, 184028, 184249, 186997, 188875, 188876, 188878, 188879, 188880, 188882, 42369  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     petbased = false     potion = prolonged_power     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     ignore_solvent = true     pad_ascended_blast = true     pad_void_bolt = true     stm_timer = 20     sw_death_protection = 50  toggles:     cooldowns = true      custom1 = false      custom2 = false      defensives = false      essences = true [overridden]     interrupts = true      mode = automatic      potions = false   keybinds:      dark_ascension             = |   [06]     dark_void                  = T   [06]     desperate_prayer           = Z   [05]     devouring_plague           = F3  [06]     dispersion                 = 9   [07]     flash_heal                 = 8   [01]     fleshcraft                 = SW  [01]     fleshrenders_meathook      = SF  [06]     halo                       = F4  [06]     healthstone                = C   [05]     mass_dispel                = 0   [01]     mind_blast                 = 3   [01], 1   [07]     mind_flay                  = 1   [01]     mind_sear                  = 4   [07]     mind_spike                 = 7   [01], 2   [07]     mindgames                  = F   [06]     potion                     = SM3 [05]     power_infusion             = SR  [06]     power_word_fortitude       = SJ  [06]     power_word_shield          = 5   [01]     psyfiend                   = ST  [06]     purify_disease             = SM5 [05]     ring_of_collapsing_futures = X   [05]     shadow_word_death          = G   [06], 7   [07]     shadow_word_pain           = 2   [01]     silence                    = M3  [05], 8   [07]     unholy_nova                = F1  [06]     vampiric_embrace           = SM4 [05]     vampiric_touch             = SQ  [06], 3   [07]     will_to_survive            = 9   [01]

### Error Messages (Link)

No tienes ningún errores! ¡Hurra!

### Additional Information

no tengo mas info

### Contact Information

Darik#2940

**Comment by RussellAnas** [comment]
The same happens with me on Warrior + Hunter. It starts appearing when I go back to the latest Shadowlands version.

**Comment by SpatenLa** [comment]
because they arent yet included in the dragonflight release. hekili is working on it.

**Comment by Cubano0o** [comment]
how did you get a 10.1 update on hekili. im still stuck on the old version and it says updated

**Comment by Hekili** [comment]
There are beta versions posted on CurseForge and everywhere else.

**Comment by drkrox** [comment]
hekili released a version of 10.0 so ask and let them know since the rotation screen does not appear

**Comment by SNhurricane** [comment]
Still doesnt work :( how about you all?

**Comment by marekCs** [comment]
Because Priest is not ready yet? Be patient

**Comment by SpatenLa** [comment]
what i said didnt change in the last 2 hours.

**Comment by drkrox** [comment]
just let me know what happens don't be mad :(

**Comment by K0uds** [comment]
Same here rotation does not appear after updating to version 10.1.0-beta4

Everything OK with 10.1.0-beta3

**Comment by chrislloydonline** [comment]
Same issue for me, ever since todays update Hekili has completely disappeared. All settings are same as they were earlier today, just the interface for Primary/AOE no longer shows up. Have seen on Twitter things are being updated, just wanted to let you know.

**Comment by markdall** [comment]
10.1.0-beta4 on a Destruction Warlock. The displays don't appear and there's no message explaining why. If they're not ready, some kind of indication of that would be great. Then none of us would worry about it.

**Comment by baswebbie** [comment]
> 10.1.0-beta4 on a Destruction Warlock. The displays don't appear and there's no message explaining why. If they're not ready, some kind of indication of that would be great. Then none of us would worry about it.

There is, in your chat window.

**Comment by Hekili** [comment]
The first time you cast literally anything, it will warn you that your spec is not yet supported.  Please be patient.

**Comment by markdall** [comment]
Gotta say here folks, no it doesn't. Maybe it's my chat settings? I'm not trying to be difficult here, it truly doesn't. If it did, I'd have never come here and bothered you with it. 
![image](https://user-images.githubusercontent.com/238194/198138558-bed45f16-94ab-4c49-b829-2155517ae35e.png)

**Comment by TheHambrick** [comment]
> 



> Gotta say here folks, no it doesn't. Maybe it's my chat settings? I'm not trying to be difficult here, it truly doesn't. If it did, I'd have never come here and bothered you with it. ![image](https://user-images.githubusercontent.com/238194/198138558-bed45f16-94ab-4c49-b829-2155517ae35e.png)

![image](https://user-images.githubusercontent.com/103148780/198139341-4664be65-d7b8-4f90-9890-7789a43cd798.png)

not the chat box like bas said, but it's there, and it pops up again every time you reload

**Comment by baswebbie** [comment]
![image](https://user-images.githubusercontent.com/11398483/198139777-c98808cf-9c3d-48ae-a987-19e03d4c4de6.png)

**Comment by markdall** [comment]
I don't know why you don't believe me. I get that you see what you're supposed to see. I don't. 

I showed you my chat window with zero output from Hekili. Here's a snippet of the screen just after a hit a target dummy with a chaos bolt. The notification window is directly there in the middle, if something was going to show up, you'd see it here. 
![image](https://user-images.githubusercontent.com/238194/198140748-e714aea7-f816-488e-a17e-260384f2338a.png)

Having said all that... maybe it's me. Maybe I messed something up. Maybe it's an addon. 

Either way though, believe me when I tell you for a third time that I do not in fact see anything like you do, or I literally wouldn't have come here... like I said.

**Comment by vond82** [comment]
> I don't know why you don't believe me. I get that you see what you're supposed to see. I don't.

I just tried logging in with a class that isn't supported yet and I got the msg immediately upon logging in, in the notification window. There's nothing when you attack a target (that would be extremely intrusive if there was too)
