### ISSUE TITLE
Feral Shred not displaying correctly after recent update

### ISSUE THREAD

**Issue by th3g3rmb0y** [Hekili/hekili#170]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by th3g3rmb0y** [comment]
![image](https://user-images.githubusercontent.com/52911282/61202920-d5b7fa00-a6e0-11e9-8ee0-f612eaaf7591.png)

AS you can see in the image above, energy is basically full, however "Shred" should be showing but its not...

**Comment by Hekili** [comment]
Weird. Can you fill out the template and provide all the info it asks for?

**Comment by th3g3rmb0y** [comment]
Hi,

 

I’ve realised that is showing Shred after some tweaks. For now, please delete the bug submission – I’ll check the settings all again

 

Thanks
