### ISSUE TITLE
[BUG] Assasination Rogue Rotation Priority does not progress 

### ISSUE THREAD

**Issue by Infernas** [Hekili/hekili#1702]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Priority does not progress at all

### How to Reproduce

Enter as rogue
Spec assasination
try to attack and go through priority
priority doesn't progress

### Player Information (Link)

https://pastebin.com/YW9hp17Z

### Error Messages (Link)

no error

### Contact Information

Infernas#2368

**Comment by Hekili** [comment]
Please wait for a Dragonflight release.
