### ISSUE TITLE
[BUG] Taint issue (may be resolved).

### ISSUE THREAD

**Issue by chrislloydonline** [Hekili/hekili#1703]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Upon updating to prepatch and updating Hekili to latest version via CurseForge, the addon no longer appears in game. When using ELVui or Bliazzard UI, the Hekili addon has gone. When entering Blizzards new "Edit Mode" a error message appears on screen. See attached picture for details. 
![Hekili Broken](https://user-images.githubusercontent.com/78756414/198116343-758455bf-c7d1-4e3a-9595-04493b79e1ee.jpg)

### How to Reproduce

Enter game on any character.
Open Edit Mode
Error Message Appears

### Player Information (Link)

https://pastebin.com/LGEADdD6

### Error Messages (Link)

https://pastebin.com/BbU2fA8t

### Contact Information

peridotix#6811

**Comment by chrislloydonline** [comment]
Just before anybody comments I am aware my action bars are empty, this isn't the issue here. Hekili doesn't load on any of my characters, even the ones with full action bars.

**Comment by jmusick** [comment]
Have you tried disabling all addons except Hekili to see if that resolves it by chance?

**Comment by chrislloydonline** [comment]
> Have you tried disabling all addons except Hekili to see if that resolves it by chance?

I havent, but I will try it now.

**Comment by markdall** [comment]
Reproduces for me, 10.1.0-beta4.

**Comment by Hekili** [comment]
It's hard to know what can be triggering these taints with all of Blizz's UI changes.  I will no longer register my addon's options in the game's UI, so options will be accessed via `/hekili` or the minimap icon instead.  That may or may not resolve the issue fully.
