### ISSUE TITLE
[REC] GUARDIAN DRUID DOESNT RECOGNIZE INCARN AS BERSERK

### ISSUE THREAD

**Issue by TheKalazar** [Hekili/hekili#1704]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When doing my rotation, during incarn, the addon keeps recommending to use berserk instead of incarn. 

### How to Reproduce

1 Enter the game as Guardian Druid
2 Enter combat
3 Use incarn
4 Use thrash
5 Realize the addon is still recommending berserk

### Snapshot (Link)

https://pastebin.com/raw/iujkjYYq

**Comment by Hekili** [comment]
Snapshot is incomplete; I can't even tell which version of the addon you're using.

**Comment by Hekili** [comment]
This will be fixed in the next beta.
