### ISSUE TITLE
[BUG] Some minor bugs i've been experienced since pre-patch.

### ISSUE THREAD

**Issue by Tyrakoz** [Hekili/hekili#1705]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Keybinds doesn't show up on the prio or AoE bar. And also i can't "drag and drop" the bars (prio, aoe etc.), it just gets stuck and i can't "drop" it in place. I have the latest version downloaded.

### How to Reproduce

1. Enter the game on any character.
2. Keybinds doesn't show up on the bars.
3. I can't drag and drop.

### Player Information (Link)

build: v9.2.7-1.0.0b level: 46 (46) class: MONK spec: windwalker  talents: none  pvptalents: alpha_tiger    disabling_reach    turbo_fists  covenant: none  conduits: none  soulbinds: []  sets: none  gear: none  legendaries: none  itemIDs: none  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Windwalker     petbased = false     potion = potion_of_spectral_agility     regularRefresh = 0.5     strict = false     throttleRefresh = false     throttleTime = false     allow_fsk = false     check_sck_range = false     check_wdp_range = false     optimize_reverse_harm = false     sef_one_charge = false     tok_damage = 1     use_diffuse = false  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds: 

### Error Messages (Link)

No errors.

### Contact Information

Tyrakoz#5725

**Comment by Hekili** [comment]
No tickets for 9.2.7.  When I've posted a full release for Dragonflight, feel free to report issues then.
