### ISSUE TITLE
[BUG] Keybinds not working with Bartender.

### ISSUE THREAD

**Issue by tance77** [Hekili/hekili#1706]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I'm using bartender and it seems that some of the keybinds are either not right or just don't exist at all.

### How to Reproduce

- Play the game as a Feral Nightfae Druid with  Adaptive Swarm.
- Use bartnder bars 1 5 6 3 4 and 7

Notice when you go through your rotation the moves notice that some moves are right, wrong, or non existant.
![image](https://user-images.githubusercontent.com/3421501/198150148-4b05dd51-b784-41a5-a646-9925b76ffc15.png)
![image](https://user-images.githubusercontent.com/3421501/198150172-24075228-7994-48df-b85a-301f2b775d7d.png)

In the examples above you can see that Stealth is on Shift 2 and the addon doesn't know what to show for the keybind.
Also notice that tigers fury is on 2 and the addon doesn't know what it is.
Another thing, moonfire, which is on Bar 6 on SHIFT+G it is saying it is E.

### Player Information (Link)

https://pastebin.com/eJK4s8Mm

### Error Messages (Link)

N/a

**Comment by tance77** [comment]
Related from 2 months ago https://github.com/Hekili/hekili/issues/1593

**Comment by marclapl** [comment]
Looks like it's from a change in Bartender4

They changed the GetBindingKey from :LeftClick to :Keybind

Here's an exemple:

![image](https://user-images.githubusercontent.com/67342980/198180506-3b3b9fd9-02f8-4020-bed4-8933608e7ac2.png)

seen in the code of Bartender4:
https://github.com/Nevcairiel/Bartender4/commit/4907a6ae639a7ac5ea19960bf9209c7306d059f1

**Comment by tance77** [comment]
I think this PR that I made will fix the bartender issue, I just really quickley skimmed through the Event.lua file and did a replace on the ones that were referencing bartender. This may be completly wrong but I thought I would open a PR just for the heck of it.

https://github.com/Hekili/hekili/pull/1715

**Comment by picklerick84** [comment]
Hello.  I am having the same issue as the op of this thread.  I'm trying to swap off elvui today and use bartender and the keybindings won't show when using bartender.  If I go back to elvui it works fine.

I should add that it does work for abilities on bar 1, but none of the other keybindings show up when using bartender.
