### ISSUE TITLE
Stellar Flare is spamrecommended

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1707]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While in a dungeon on multitarget addon seems to get confused and not recommend anything but stellar flare.

### How to Reproduce

Do multitarget as balance with stellar flare selected and it will periodically only recommend stellar flare even if every target has it up.

### Snapshot (Link)

https://pastebin.com/DDJ7qtVr

**Comment by Hekili** [comment]
Update.
