### ISSUE TITLE
[BUG] Elemental Shaman Missing

### ISSUE THREAD

**Issue by caist4321** [Hekili/hekili#1708]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I updated the addon and logged into my elemental shaman to see the missing rotation. When I load the configuration, the option for elemental is missing. 

### How to Reproduce

Logging into elemental shaman to not see the rotation listed. 

### Player Information (Link)

https://pastebin.com/xgKXKza8

### Error Messages (Link)

n/a

### Contact Information

Caist#0654

**Comment by Hekili** [comment]
I haven't implemented Elemental for Dragonflight yet; it'll be there soon.
