### ISSUE TITLE
Pocket-Sized Computational Device shows in sequence

### ISSUE THREAD

**Issue by Draugrs** [Hekili/hekili#171]
I finally received the Pocket-Sized Computational Device trinket on my Elemental Shaman (Draugrs - US Hyjal if you need further detail from armory). It is lvl 404 with following:

Red - grants 1,152 haste for 12 secs;
Yellow - 165 versatility, 52 haste;
Blue - increase spare parts found;

It should not show in the rotation sequence as it does not have any interactive pieces associated with it. I noticed after equipping it though that the rotation calls for Stormkeeper, Concentrated Flame, Lava Burst, then shows a slightly dulled Pocket-Sized Computational Device icon. It does not move away from this icon except maybe to suggest interrupts. I was able to go into the settings under 'Gear and Trinkets' find the Pocket-Sized Computational Device and choose to disable it. The rotational then works as normal.

One other thing, I noticed the rotation calls for Stormkeeper, Lava Burst, Concentrated Flame (if available), then Flame Shock. I would think Flame Shock should come first since it provides a 100% crit to Lava Burst. I could be missing something though.

Thanks for your time and assistance.

**Comment by Hekili** [comment]
Keep distinct issues separate, but I'll look at the Essence/Flame Shock issue.

Can you post a snapshot when you're getting Pocket-Sized Computational Device recommendations?

**Comment by Draugrs** [comment]
Yes, FYI just logged into Warrior and it did it on him as well. I will take off trinket disable and screenshot for you. Sorry for dropping two issues in one.
![WoWScrnShot_071519_115218](https://user-images.githubusercontent.com/40501145/61233903-4b2ec500-a6f7-11e9-84e3-288e042dc033.jpg)

**Comment by Hekili** [comment]
No, I mean a snapshot (see the issue ticket instructions).  It's the log of why the addon recommended specific actions.

SHIFT+ALT+P to pause.
/hekili > Snapshots
Select Primary, 1.
Copy and paste to pastebin.
Link here.

**Comment by Draugrs** [comment]
Ah ok sorry again will do

**Comment by Draugrs** [comment]
build: v8.2.0-05.02
level: 120 (120)
class: SHAMAN
spec: elemental

talents: echo_of_the_elements
    master_of_the_elements
    natures_guardian
    primal_elementalist
    spirit_wolf
    stormkeeper
    totem_mastery

azerite: apothecarys_concoctions=1
    azerite_empowered=3
    azerite_globules=1
    echo_of_the_elementals=1
    gutripper=1
    heed_my_call=1
    igneous_potential=2
    impassive_visage=2
    lava_shock=1
    self_reliance=1
    thunderous_blast=1

essences: [the_crucible_of_flame]=1, none

sets/legendaries/artifacts: pocketsized_computation_device=1

gear:     bilewing_mantle=1
    blightguards_harness=1
    cloak_of_restless_spirits=1
    dreadmire_helm=1
    g04w4y_crowd_repeller=1
    gaolers_chainmail_gaiters=1
    heart_of_azeroth=1
    honorbound_skullcrusher=1
    honorbound_vanguards_clasp=1
    honorbound_vanguards_sabatons=1
    igneous_winterskorn_loop=1
    incandescent_sliver=1
    paku_windrider_bracers=1
    pocketsized_computation_device=1
    poens_deepsea_handgrips=1
    seal_of_dathremar=1
    sharkskin_tunic=1

itemIDs: 157889, 157925, 157955, 158075, 159392, 159663, 163449, 163451, 163869, 165480, 165571, 165680, 165683, 167555, 168603, 170335, 98083

New Recommendations for [ Primary ] requested at 12:04:46 ( 223707.97 ).

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00 ).
 - maelstrom, 33 / 100
 - mana, 20000 / 20000

Processing precombat action list [ Elemental - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.

[001] totem_mastery ( precombat - 5 )
The action is not ready before our maximum delay window (15.00) for this query.

[002] stormkeeper ( precombat - 6 )
The action is not ready before our maximum delay window (15.00) for this query.

[003] fire_elemental ( precombat - 7 ) - ability disabled.

[004] storm_elemental ( precombat - 8 ) - ability unknown

[005] potion ( precombat - 9 ) - ability disabled.

[006] elemental_blast ( precombat - 10 ) - ability unknown

[007] lava_burst ( precombat - 11 )
We are already in-combat and this pre-combat action is not essential.  Skipping.

[008] chain_lightning ( precombat - 12 )
We are already in-combat and this pre-combat action is not essential.  Skipping.
Completed precombat action list [ Elemental - precombat ].

Processing default action list [ Elemental - default ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( default ) is not set or not enabled.  Skipping.

[009] potion ( default - 2 ) - ability disabled.

[010] wind_shear ( default - 3 )
The action is not ready before our maximum delay window (15.00) for this query.

[011] totem_mastery ( default - 4 )
The action is not ready before our maximum delay window (15.00) for this query.

[012] fire_elemental ( default - 5 ) - ability disabled.

[013] storm_elemental ( default - 6 ) - ability unknown

[014] use_items ( default - 7 )
There is no criteria for Use Items.
Current recommendation was NO ACTION at +60.00s.

[015] pocketsized_computation_device ( items - 1 )
The action (pocketsized_computation_device) is usable at (0.00 + 0.00) with cost of 0.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: ( ! settings.boss[false] | boss[false] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
Action chosen:  pocketsized_computation_device at 0.00!
Returned from Use Items; current recommendation is pocketsized_computation_device (+0.00).
The recommended action (pocketsized_computation_device) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Elemental - default ].
Recommendation is pocketsized_computation_device at 0.00 + 0.00.
Recommendation #1 is pocketsized_computation_device at 0.00s (0.00s).

**Comment by Draugrs** [comment]
build: v8.2.0-05.02
level: 120 (120)
class: SHAMAN
spec: elemental

talents: echo_of_the_elements
    master_of_the_elements
    natures_guardian
    primal_elementalist
    spirit_wolf
    stormkeeper
    totem_mastery

azerite: apothecarys_concoctions=1
    azerite_empowered=3
    azerite_globules=1
    echo_of_the_elementals=1
    gutripper=1
    heed_my_call=1
    igneous_potential=2
    impassive_visage=2
    lava_shock=1
    self_reliance=1
    thunderous_blast=1

essences: [the_crucible_of_flame]=1, none

sets/legendaries/artifacts: pocketsized_computation_device=1

gear:     bilewing_mantle=1
    blightguards_harness=1
    cloak_of_restless_spirits=1
    dreadmire_helm=1
    g04w4y_crowd_repeller=1
    gaolers_chainmail_gaiters=1
    heart_of_azeroth=1
    honorbound_skullcrusher=1
    honorbound_vanguards_clasp=1
    honorbound_vanguards_sabatons=1
    igneous_winterskorn_loop=1
    incandescent_sliver=1
    paku_windrider_bracers=1
    pocketsized_computation_device=1
    poens_deepsea_handgrips=1
    seal_of_dathremar=1
    sharkskin_tunic=1

itemIDs: 157889, 157925, 157955, 158075, 159392, 159663, 163449, 163451, 163869, 165480, 165571, 165680, 165683, 167555, 168603, 170335, 98083

New Recommendations for [ Primary ] requested at 12:04:46 ( 223707.97 ).

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00 ).
 - maelstrom, 33 / 100
 - mana, 20000 / 20000

Processing precombat action list [ Elemental - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.

[001] totem_mastery ( precombat - 5 )
The action is not ready before our maximum delay window (15.00) for this query.

[002] stormkeeper ( precombat - 6 )
The action is not ready before our maximum delay window (15.00) for this query.

[003] fire_elemental ( precombat - 7 ) - ability disabled.

[004] storm_elemental ( precombat - 8 ) - ability unknown

[005] potion ( precombat - 9 ) - ability disabled.

[006] elemental_blast ( precombat - 10 ) - ability unknown

[007] lava_burst ( precombat - 11 )
We are already in-combat and this pre-combat action is not essential.  Skipping.

[008] chain_lightning ( precombat - 12 )
We are already in-combat and this pre-combat action is not essential.  Skipping.
Completed precombat action list [ Elemental - precombat ].

Processing default action list [ Elemental - default ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( default ) is not set or not enabled.  Skipping.

[009] potion ( default - 2 ) - ability disabled.

[010] wind_shear ( default - 3 )
The action is not ready before our maximum delay window (15.00) for this query.

[011] totem_mastery ( default - 4 )
The action is not ready before our maximum delay window (15.00) for this query.

[012] fire_elemental ( default - 5 ) - ability disabled.

[013] storm_elemental ( default - 6 ) - ability unknown

[014] use_items ( default - 7 )
There is no criteria for Use Items.
Current recommendation was NO ACTION at +60.00s.

[015] pocketsized_computation_device ( items - 1 )
The action (pocketsized_computation_device) is usable at (0.00 + 0.00) with cost of 0.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: ( ! settings.boss[false] | boss[false] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
Action chosen:  pocketsized_computation_device at 0.00!
Returned from Use Items; current recommendation is pocketsized_computation_device (+0.00).
The recommended action (pocketsized_computation_device) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Elemental - default ].
Recommendation is pocketsized_computation_device at 0.00 + 0.00.
Recommendation #1 is pocketsized_computation_device at 0.00s (0.00s).

**Comment by Draugrs** [comment]
Hopefully I did that right

**Comment by Hekili** [comment]
Yep, that helps.  I am posting a new alpha version that you can hopefully try and let me know if the problem persists.  Look for v8.2.0-05.03-alpha1 in a moment.

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/releases/tag/v8.2.0-05.03-alpha1

**Comment by Draugrs** [comment]
Awesome thks will give it a go.

**Comment by Hekili** [comment]
Please let me know if it works.

**Comment by Draugrs** [comment]
Alright tested both toons appeared to correct the Pocket-Sized Computational Device issue in rotation. Spot on thanks again.
