### ISSUE TITLE
[BUG] Havoc DH - Fel Rush remaining in rotation after unchecking recommend movement and not recognizing keybind.

### ISSUE THREAD

**Issue by KEH912** [Hekili/hekili#1710]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Before when I unchecked recommend movement on my Havoc DH Fel Rush would be taken out of the rotation. Now I have to completely disable it to get it out of the rotation. Not a big deal just wanted to make you aware.

I have also noticed that it is not recognizing my keybind in the rotation so that specific ability does not have a keybind shown.

### How to Reproduce

Enter Game as Havoc Demon Hunter -> open Hekili menu -> Havoc -> uncheck Recommend Movement -> close -> /reload

### Player Information (Link)

https://pastebin.com/JJiinWh9

### Error Messages (Link)

No Error Message

### Contact Information

KHoffman912@gmail.com

**Comment by Hekili** [comment]
This is a "recommendations" issue.  If it persists with the 05.1 release, submit a new ticket re: recommendations and include the required snapshot.
