### ISSUE TITLE
Covenant Skills not being recommended inside of a mythic+ dungeon

### ISSUE THREAD

**Issue by pingitoreluiz** [Hekili/hekili#1711]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As stated by blizzard covenant skill are still usable inside Season 4 mythic+ dungeons. But as stated in another post, the commit https://github.com/Hekili/hekili/commit/5849ccbd113894372416a2883d0329b29595bb4f removed the covenant skills to be recommended outside of shadowlands. but that do take place in a season 4 dungeon( Iron Docks, Karazhan(Lower and upper),Mechagon,Grimrail Depot)

### How to Reproduce

1. Enter the game with any class and select any covenant
2. start a m+ dungeon outside of shadowlands (Iron Docks, Karazhan(Lower and upper), Mechagon, Grimrail Depot)
3. As you can see the addon will not recommed you cov skill

### Snapshot (Link)

Don't have a key from a dungeon outside of shadowlands

### Contact Information

Lazugo#8823

**Comment by Hekili** [comment]
There's already an open ticket and this added no information.  You can add a snapshot to the other ticket.
