### ISSUE TITLE
[BUG]  Interface/AddOns/Hekili/Events.lua:745: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)

### ISSUE THREAD

**Issue by sfmulla** [Hekili/hekili#1712]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

the addon gives "Lua Error" when game started  with this message: 
Message: Interface/AddOns/Hekili/Events.lua:745: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
and there is some details
when I close the error window it is woring untill I loot a mob or do other activity like enchant or eat
[Lua Error.txt](https://github.com/Hekili/hekili/files/9875072/Lua.Error.txt)

### How to Reproduce

[Lua Error.txt](https://github.com/Hekili/hekili/files/9875101/Lua.Error.txt)

### Player Information (Link)

https://pastebin.com/pA985645

### Error Messages (Link)

https://pastebin.com/kUkDjCY0

### Contact Information

sfmulla@hotmail.com

**Comment by Hekili** [comment]
Wait for a Dragonflight release; do not post tickets for Shadowlands versions of the addon.
