### ISSUE TITLE
UH DK APL Has Hardcoded Opener for Gargoyle. Also, Apoc not suggested with Dark Transformation.

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#1713]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unholy DK opener for Gargoyle was hardcoded by the APL writer. You mentioned in chat that you have to rewrite sequences so opening a ticket to solidify its position on the to-do list for you.

The 2nd part of the ticket applies to the attached snapshot.  While going through the rotation and having the appropriate wounds up.  Apoc is not ever suggested and simply is consistently pushed back in the rotation over and over again.

### How to Reproduce

Gargoyle Opener can be recreated by letting all cooldowns reset.  Target a mob, and compare spell sequencing with what is suggested via the Opener guide on Wowhead. https://www.wowhead.com/guide/classes/death-knight/unholy/rotation-cooldowns-pve-dps

Recreating Apoc Issue:

Target Dummy and follow rotation.  Apocalypse simply goes from being runner up spell to pushed back, and repeated endlessly unless manually pushed.

### Snapshot (Link)

https://pastebin.com/ZPgRr88Y

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wpk3SSNJM3JuBckYWTmTfu

### Additional Information

If any of the information is inaccurate or needs follow-up links, please let me know, and I will provide it asap.

Thanks for all you do!

**Comment by Hekili** [comment]
Can you post snapshots from when the Apocalypse issue is actually occurring?  Specifically, when it is second-in-queue per your description.  Thanks!

**Comment by UltiDeeps** [comment]
https://pastebin.com/2zfz2N7P

Updated snapshot of the moment.

**Comment by Hekili** [comment]
This is an APL issue that I'll need to resolve.  Thanks!

**Comment by UltiDeeps** [comment]
I received clarification on the play style from APL writer. In DF, Apoc and DT will be synced all of the time while in pre patch due to a conduit, Apoc is casted on CD since it’s reduced so heavily.  When release happens and the conduit goes away they are always synced. Not sure if this has any impact on what you plan to do moving forward.

**Comment by UltiDeeps** [comment]
Sorry didn’t mean to close. Reference above comment.

**Comment by UltiDeeps** [comment]
Did not mean to close ticket. Phone is misreading screen inputs because cracked glass I think? Lol 

Reference above comment.

**Comment by UltiDeeps** [comment]
https://pastebin.com/wZr6dKSh

Above is a snap shot that takes place right after I Dark Transformation and should subsequently Apoc but it instead shifted a Death Coil to the front which if hit will then send Apoc down the suggestion chain even deeper again.

**Comment by Hekili** [comment]
May be resolved in the release.  If not, feel free to reopen.
