### ISSUE TITLE
[BUG] Not recommending Spear of Bastion for Prot Warrior

### ISSUE THREAD

**Issue by NokuraWoW** [Hekili/hekili#1714]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Doesnt recommend spear during rotation as kyrian. Int he snapshot it says the talent is missing. But as kyrian we have it by default. 

### How to Reproduce

Be kyrian without spear of bastion talent.
Never recommend spear.

### Player Information (Link)

https://pastebin.com/vm6im5aV

### Error Messages (Link)

https://pastebin.com/vm6im5aV

### Contact Information

Nokura#1874

**Comment by penguinlust** [comment]
This is true of all Covenant abilities for warriors, I suspect -- I'm not seeing Ancient Aftershock (Night Fae) on Arms. Heck, I'm not seeing any equipped item abilities either, like Gavel of the First Arbiter.

**Comment by Wyste** [comment]
It's likely because the name is the same as the talent. SIMC handled this by renaming the Cov ability to "kyrian_spear" within the code, something similar might need to be done here as well, to differentiate between the two (covenant vs class ability).

penguinlust's statement about all cov abilities not being recommended is false, the included APL in the current DF release just doesn't include Ancient Aftershock or Conq Banner in the list. You could add them yourself and they show up just fine; I've tested this today.

**Comment by Sammzy1** [comment]
Without making a new thread. Just will type it here. Odyn's Fury is also not showing up

**Comment by Sammzy1** [comment]
Sweeping Strikes for Arms also doesn't show up in recommended list

**Comment by penguinlust** [comment]
Ok, fair enough. The APL is probably woefully inadequate at this point and if so that's not a Hekili issue. Trying to figure out why no equipped items are showing up either, but it's probably the same issue.

**Comment by pingitoreluiz** [comment]
be sure to see if youare doing a shadowlands content. Because he disabled the cov abilities outside of shadowlands but they aren't working for S4 dungeons that go outside of shadowlands(Iron Docks, Grimrail Depot, Mehcagon and karazhan)

**Comment by Hekili** [comment]
There are no current Warrior priorities from SimulationCraft that have these abilities.  Will update when a priority is written.

**Comment by penguinlust** [comment]
I should add that when I run simulationcraft directly these abilities do show up as does the equipment in the generated action priority list. I can't find it in their code (admittedly haven't looked too hard), but it's doing the right thing. However, I was able to directly add this stuff to the Hekili priority lists and it works just fine.

**Comment by Hekili** [comment]
This is addressed in release 05.
