### ISSUE TITLE
[REC] 3 Issues with Protection Warrior

### ISSUE THREAD

**Issue by thomasbrezina** [Hekili/hekili#1716]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

So I found 3 issues with prot warrior - want me to make 3 tickets or just state them here with both snapshots? Fairly simple and straight forward ones!

I have attached two Snapshots, just in case here are the links:
https://pastebin.com/wdk3FUf6
https://pastebin.com/QQwh1Mfc 

1. It recommends Spell Reflect on CD without any damage coming in
2. It recommends DEVESTATE as a skill yet its a passive after taking the Devastator Talent in the Protection Plan
3. It recommends LAST STAND on CD without any damage coming in

### How to Reproduce

1. Enter Game as Protection Warrior 
2. Assign the Devastator Talent in the Protection Tree
3. Attack any Target
4. Press Buttons and see what is recommended

### Snapshot (Link)

https://pastebin.com/QQwh1Mfc 

### Additional Information

Second Snapshot:
https://pastebin.com/wdk3FUf6

### Contact Information

https://pastebin.com/QQwh1Mfc

**Comment by Hekili** [comment]
Should be addressed in next beta.
