### ISSUE TITLE
[REC] [Dragonflight] - BM - Death Chakram is never recommended for the first position

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1717]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Death Chakram is never recommended for the first position, always max as the second spell in the order. Also, when I equip the Death Chakram talent, I get weird outputs, like Cobra Shot 10 times in a row, etc.

### How to Reproduce

1. Enter the game as a BM Hunter.
2. Set Death Chakram as a spell on 60 lvl char.
3. Try rotation on dummies (NF).

### Snapshot (Link)

https://pastebin.com/YXgfu2Bu

### Contact Information

Markô#2877

**Comment by marekCs** [comment]
Btw on BM and also on MM it still snapshots my chat, even when I turn off automatic snapshots.

**Comment by tomtim90** [comment]
Having the exact same issue with MM. I suspect it's the talent/covenant ability issue that other specs are having. Death Chakram is simply not being suggested.

**Comment by RussellAnas** [comment]
I'm having the same issue on MM. Death Chakram is not being recommended.

**Comment by Hekili** [comment]
Try beta8 and report back.

If snapshots are generated, it's a good idea to put them on Pastebin and link them so I can read them.  :)

**Comment by RussellAnas** [comment]
I didn't see snapshots taken by the addon, but it is still not recommending Death Chakrams on MM. Here is the data for my char profile atleast if it helps:

*clipped*

**Comment by tomtim90** [comment]
Beta 8 still doesn't show Chakram for MM. BM it never makes it to the next action icon. Staying at 2nd or 3rd priority. Seeing the same MS spam behavior reported above for BM.

BM - https://pastebin.com/BfAfTRFw

MM - https://pastebin.com/3keVdbim

**Comment by marekCs** [comment]
I can confirm as well that on beta8 there is no Death Chakram recommendation, 2 minutes fight with MM, and with BM, same situation like before, DCH is max 2nd in the order but never first spell in the row, [pastebin](https://pastebin.com/AtcH501c)

**Comment by Hekili** [comment]
@marekCs:  Type `/dump GetSpellInfo( "Death Chakram" )` and let me know what you see in chat.

@tomtim90:  Your BM snapshot has too much focus to recommend Death Chakram.  There's logic looking to spend down Focus before using Death Chakram, but I'm sure it feels counterintuitive.  Hopefully, new APLs account for this fairly quickly.

For MM, it says you don't know the spell (so obviously a bug).  Will investigate.  Can you also share the output of `/dump GetSpellInfo( "Death Chakram" )` ?  Thanks.

**Comment by marekCs** [comment]
It says:
1 - Death Chakram
3 - 3578207
4 - 0
5 - 0
6 - 40 on BM and on MM it's: 43.17142868042 
7 - 375891
8 - 3578207

**Comment by Hekili** [comment]
I'm posting possible fixes in beta9 now.

**Comment by marekCs** [comment]
Marksman - v10.1.0-beta9 - Death Chakram works, it's the first spell to come to the foreground, however the icon doesn't disappear immediately after the cast, it goes dark like it's offcd and is there in the first place for about 5 - 10 seconds. I'll try on BM now.
BM same

**Comment by marekCs** [comment]
Now it seemed to me that on BM late registered the system that the Death Chakram was pressed, because it stopped as offcd only in the second place, it works as if with a delay. [Pastebin](https://pastebin.com/mtC9W4E6)

**Comment by tomtim90** [comment]
It's showing up on marksman but like @marekCs said...something is locking up. It's like the addon gets stuck for a few GCDs showing Chakram and abilities you've already pressed without updating. Addon will not snapshot while it happens. I did get a screenshot of it. You can see Chakram has been pressed as of 3-4 seconds prior but the addon has frozen.

Snapshot MM post addon freeze - https://pastebin.com/UbszqR21

![WoWScrnShot_102722_151429](https://user-images.githubusercontent.com/17338234/198378741-12bd99d3-7478-471f-92e8-deeae0eeea60.jpg)

**Comment by tomtim90** [comment]
Another MM snapshot directly post freeze https://pastebin.com/GFdyhKBT

**Comment by mackdoherty** [comment]
Can confirm the MM chakram freeze is continuing. Applicable pastebin with warnings here: https://pastebin.com/8ViULeAX

**Comment by Hekili** [comment]
This should be resolved in the upcoming release.
