### ISSUE TITLE
[REC] Vengeance DH - Fracture is being recommended I believe but the icon is wrong. 

### ISSUE THREAD

**Issue by Wiqz** [Hekili/hekili#1718]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon seems to be working as intended except the icon telling me to press what I believe is Fracture, is showing me the icon for Shear.

### How to Reproduce

1. Enter as Vengeance DH.
2. Use this talent build -> BUkAAAAAAAAAAAAAAAAAAAAAAAAgIUCREARCQCgEtEJCJIJtkUSIJhSkEAAAAA
3. Look at the addon and see the Shear icon instead of Fracture.

### Snapshot (Link)

https://pastebin.com/A4VssFXy

### Contact Information

Wiqz#8584

**Comment by RoseFarts** [comment]
Similarly, with beta7 I get a recommandation for shear, although there is not enough fury available: https://pastebin.com/BXkGVJey

The title here might be misleading, but shear should not be recommanded, if there is not enough fury to cast it.

**Comment by ghost** [comment]
you are not on the old SL build. 
Download latest version here https://github.com/Hekili/hekili/releases or on wowup/ curseclient

**Comment by Hekili** [comment]
Yes, please update to a Dragonflight version of the addon.  No tickets for 9.2.7 anything.

**Comment by ravisangha** [comment]
I was hoping to get some clarification about the 9.2.7 version of the addon. Should people be using the 10.0 beta versions of the addon while playing the current live game which is in prepatch, or is that for the beta client? If we are able to use the beta releases for the live game, do I just extract the file into my retail addon files? Ive tried that and the game did not pick up the addon. Any help would be appreciated, thanks!
