### ISSUE TITLE
Bear Druid essences 

### ISSUE THREAD

**Issue by willzbear** [Hekili/hekili#172]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by willzbear** [comment]
since the the new update im having an issue with bear druid where it is showing abilities ive taken out of the defensive rotation i.e anima of death and barkskin when i have them in they toggle off and on i remove them and they are still there even when i have defensive off

**Comment by willzbear** [comment]
since the the new update im having an issue with bear druid where it is showing abilities ive taken out of the defensive rotation i.e anima of death and barkskin when i have them in they toggle off and on i remove them and they are still there even when i have defensive off

**Comment by willzbear** [comment]
build: v8.2.0-05.03
level: 120 (120)
class: DRUID
spec: guardian

talents: brambles
    earthwarden
    galactic_guardian
    rend_and_tear
    restoration_affinity
    typhoon
    ursols_vortex

azerite: azerite_empowered=2
    azerite_veins=1
    fight_or_flight=1
    impassive_visage=1
    incite_the_pack=1
    resounding_protection=1
    twisted_claws=1
    wild_fleshrending=1

essences: [anima_of_life_and_death]=1, none

sets/legendaries/artifacts: none

gear:     belt_of_gleaming_determination=1
    common_white_shirt=1
    corrosive_handlers_gloves=1
    fathomstalker_leggings=1
    footbomb_championship_ring=1
    galecallers_boon=1
    heart_of_azeroth=1
    honorbound_outriders_drape=1
    honorbound_outriders_shoulderguards=1
    hood_of_the_slithering_loa=1
    lingering_sporepods=1
    mercenary_miners_boots=1
    notorious_gladiators_pike=1
    seal_of_questionable_loyalties=1
    spymasters_wrap=1
    thunder_bluff_tabard=1
    wristguards_of_the_sandswimmer=1

itemIDs: 155860, 158075, 158306, 158314, 159305, 159318, 159332, 159336, 159462, 159614, 159626, 16060, 163360, 169714, 169809, 170531, 45584

**Comment by Hekili** [comment]
Essences are treated like trinkets.  If they don't appear in your priority, they are filled in as part of the Use Items action.

If you don't want them to show up, disable the ability, don't delete it.

**Comment by willzbear** [comment]
i disabled them and it still shows up barkskin as well

**Comment by willzbear** [comment]
on the toggle screen i hit the x button that disables it

**Comment by Hekili** [comment]
No.  That list is showing you what is *controlled by* the toggle.  If you remove an ability from the list, it is no longer controlled by the toggle.  Meaning it can be recommended regardless of the toggle.

You want to turn the toggle off via /hekili > Toggles (with the ability in the list) or turn the ability off via /hekili > Abilities.
