### ISSUE TITLE
[REC] BLOOD DK NOT USING EMPOWER RUNE WEAPON IN CDS OR ROTATION.

### ISSUE THREAD

**Issue by ltbutterman** [Hekili/hekili#1720]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The blood dk rotation seems pretty fluffed out apart from the fact it does not utilise empower rune weapon for cooldowns or in main rotation.

### How to Reproduce

log into DK.
Enter blood dk spec and makesure empower rune weapon is selected in talents.
proceed to bash face on dummies.

### Snapshot (Link)

no snapshot

### Contact Information

ThiCCShady#3609

**Comment by Hekili** [comment]
Ticket is lacking required information.
