### ISSUE TITLE
FURY WAR BETA ROTATION STILL NOT FUNCTIONAL/RESPONDING

### ISSUE THREAD

**Issue by ltbutterman** [Hekili/hekili#1721]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

FURY WAR BETA ROTATION STILL NOT FUNCTIONAL/RESPONDING TO INPUTS WHEN SELECTING ABILITIES IN QUEUE

### How to Reproduce

Enter game as war
select fury RB spec
hit dummies

### Player Information (Link)

none

### Error Messages (Link)

none

### Contact Information

ThiCCShady#3609

**Comment by Hekili** [comment]
Ticket is lacking required information.
