### ISSUE TITLE
[BUG] REPLACE THIS TEXT WITH A SHORT DESCRIPTION OF THE BUG YOU ARE REPORTING

### ISSUE THREAD

**Issue by Cubano0o** [Hekili/hekili#1722]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

the addon is not appearing. I use wowup and its still shows i am on the latest update. there is no beta or no new update on wowup and on wow i  can not see the addon at all. last time i ask you guys shut me out and said dont show me bugs on this patch. well this is the only patch i have, go on wow up and see there is no new update.

### How to Reproduce

,

### Player Information (Link)

build: v9.2.7-1.0.0b level: 60 (60) class: DRUID spec: balance  talents: none  pvptalents: none  covenant: kyrian  conduits: adaptive_armor_fragment = 7    deep_allegiance = 7    fury_of_the_skies = 8    innate_resolve = 7    ursine_vigor = 7    wellhoned_instincts = 8  soulbinds: [pelagos]    better_together = 1    bond_of_friendship = 1    combat_meditation = 1    focusing_mantra = 1    let_go_of_the_past = 1    newfound_resolve = 1  sets: cosmic_gladiators_medallion = 1     gladiators_medallion = 1     tier28 = 3  gear: cosmic_gladiators_medallion = 1     gladiators_medallion = 1     tier28 = 3  legendaries: none  itemIDs: none  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = true     gcdSync = true     maxRefresh = 10     maxTime = 10     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Balance     petbased = false     potion = spectral_intellect     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     delay_berserking = false     starlord_cancel = false  toggles:     cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true      interrupts = true      mode = automatic      potions = false   keybinds: 

### Error Messages (Link)

my screen does not show me the app.

### Additional Information

please help me i dont understand why you guys refuse to help me.

### Contact Information

Cubano #6919

**Comment by Prejudice182** [comment]
You have the wrong version. Your version needs to be at least 10.x to view rotations on prepatch. From your player information, you are still on 9.2.7-1.0.0b. WowUp shows version 10.1.0-beta7 as the latest available on it.
