### ISSUE TITLE
[REC] BM Cleave Cobra shot issue.

### ISSUE THREAD

**Issue by Yaooti** [Hekili/hekili#1724]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

BM is suggesting cobra shot far too much in cleave. The add-on is bypassing Kill command due to the check on focus for multishot, and is instead wanting to dump our focus with cobra shot while sitting on two charges of Kill command. Focus cost of Cobra is 35 and Kill command is 30. This causes all sorts of issues.

### How to Reproduce

Hit the training dummies.

### Snapshot (Link)

N/A

**Comment by bchinfoon** [comment]
I made a copy of my Beast Mastery priorities and went to action list and edited the following for cleave:
21. Kill Command:
focus > cost
25. Cobra Shot:
focus.time_to_max < gcd * 2 & cooldown.kill_command.remains

I'm not sure if this is 100% optimized or not, but I am getting pretty much 100% uptime on beast cleave and 3 stacks of frenzy maintained pretty much all the time so I think it's a decent hack until the developer provides a fix.  if you want to do this make sure you point to the new copy of the priority list you have made in the Beast Mastery tab.  With this hack I am getting Cobra Shot recommended pretty much never for cleave.

**Comment by Hekili** [comment]
Ticket is lacking required info.
