### ISSUE TITLE
[REC] Arms Warrior - Rend not being recommended properly, sometimes rotation seems to get stuck

### ISSUE THREAD

**Issue by OhsawaSenpai** [Hekili/hekili#1725]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Playing in my Arms Warrior, Hekili is not recommending me to Rend a lot of times, even if Rend is down on the target.
At the same time, sometimes Rend is up on the target with more than 10 seconds left, and it is still being recommended.
When I use Rend according to the recommendation, it does not change and continues to suggest it.
Sometimes also recommend Charge even though I'm fighting in melee range.

![image](https://user-images.githubusercontent.com/116802120/198300814-0d51cd06-d8f3-4369-bf7d-7d0853165898.png)

### How to Reproduce

1. Playing as an Arms Warrior;
2. Using the following build: https://www.wowhead.com/ptr/talent-calc/warrior/arms/DAPEURUUEkJUQQlBAQBEOVVUVURQBVBIBABBA 
3. Charge a mob and attack it;
4. The issue described in the initial description occurs; 

### Snapshot (Link)

https://pastebin.com/SDybeDPs

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3Z7C48T3USKDtKPkXndZsa

### Contact Information

OhsawaSenpai#3546

**Comment by irdx** [comment]
I've been testing and got a conclusion:

The rotation becames stuck when Warbreaker/Colossus smash is recommended on the rotation list. Once you use colossus/warbreaker, the rotation flows normally.

Temporally fix: on addons settings, remove warbreaker/colossus recomendation :)

**Comment by Hekili** [comment]
Please provide the talent export from the game, instead of Wowhead links.  I can't import the Wowhead links.

If Rend isn't detected, it's likely an issue with a talent changing its spell ID.  Are you able to see the spell ID of the Rend debuff on your target?

**Comment by irdx** [comment]
so far I know, the spell id remains the same
![image](https://user-images.githubusercontent.com/1235043/198390803-960d2292-781a-45c5-9428-390927384f79.png)

The bug of spell queue being stuck when Colossus/Warbreaker are on the queue is still happening.

with colossus:
![image](https://user-images.githubusercontent.com/1235043/198391050-34814f9d-2a64-488a-a4fc-c682d85bf70f.png)

colossus on cd:
![image](https://user-images.githubusercontent.com/1235043/198391080-8e7e7024-0160-4b50-8d95-876d644a5935.png)

**Comment by OhsawaSenpai** [comment]
@Hekili my current build: BcEAAAAAAAAAAAAAAAAAAAAAAAAkkkkkQkoUSSAAAAABRkoQAEJQiAHgmEhASQIAAAAAAAA4AgEJA

I have also tried what @irdx mentioned, and it works fine after disabling Colossus!

**Comment by Hekili** [comment]
When you say Colossus, are you referencing Colossus *Smash* or something else that I should know about?

Please let me know if this is resolved in the release version, or if I need to investigate further.  I have not been able to replicate this issue with/without Colossus Smash and/or Warbreaker.  If you are still having the issue after the release, be sure to provide an updated snapshot when this occurs, as the old one will be out of date.  Thanks!

**Comment by OhsawaSenpai** [comment]
@Hekili, yes, I'm referring to Colossus Smash (https://www.wowhead.com/spell=167105/colossus-smash).

I have updated to the latest version v10.0.0-01.

The issue persists:
![image](https://user-images.githubusercontent.com/116802120/198530607-c967582a-7faa-46b0-a06e-b74b2831b34a.png)

Since I am still determining if I'm accurately collecting the snapshots, I tried to collect them 3 times. 
[new-1.txt](https://github.com/Hekili/hekili/files/9886254/new-1.txt)
[new-2.txt](https://github.com/Hekili/hekili/files/9886255/new-2.txt)
[new-3.txt](https://github.com/Hekili/hekili/files/9886256/new-3.txt)

If I disable Colossus Smash or I use the ability, the issue seems to stop.

**Comment by Hekili** [comment]
Snapshots 1 and 2 don't show Rend at the front of the queue.  Snapshot 3 shows Rend at the front.

If you open /hekili > Warnings after experiencing this issue, are there any messages in the dropdown?  If so, please copy and paste them here.  Thanks!

**Comment by OhsawaSenpai** [comment]
No warnings showing up.

**Comment by OhsawaSenpai** [comment]
Would it help if I recorded a video for example?

**Comment by Hekili** [comment]
Video wouldn't hurt, but probably won't help.

If you took all three of those snapshots when Rend appeared at the front of the queue, it sounds like a display bug.  In which case, there should be either Warnings or error messages that could be caught with BugSack/BugGrabber.

**Comment by irdx** [comment]
The bug isn't related to Rend itself. 

When addon suggests to use Colossus Smash/Warbreaker, the spell queue gets stuck until we use colossus smash/warbreaker.
Like you said, it sounds like a display bug.

When we remove Colossus Smash/Warbreaker from spell suggestions on Hekili, the spell queue doesn't get stuck at all.

I'll try to generate some snapshots and grab error messages laterly. I'm working right now :P

**Comment by OhsawaSenpai** [comment]
Sorry if this is not the correct one: [new-4.txt](https://github.com/Hekili/hekili/files/9888803/new-4.txt)

I confirm what @irdx is saying - if Colossus Smash/Warbreaker is disabled, everything seems to work just fine!

**Comment by Hekili** [comment]
Yes, the challenge is that it works just fine for me 100% of the time.  If the display doesn't update due to an error, I need the error messages (from BugSack/BugGrabber) or warnings (from /hekili > Warnings).  I don't have this issue in my own testing, with or without Colossus Smash, Warbreaker, etc.

**Comment by OhsawaSenpai** [comment]
Unfortunately, there is no **warning** 😢

**Comment by OhsawaSenpai** [comment]
Have you tried with **Colossus Smash** specifically? No **Warbreaker**.

I think the behavior might be different, will test again and share the results.

**Comment by manu310891** [comment]
I have the same issue but only when I skill Test of Might. I get the following error in Hekili:
Update: Interface/AddOns/Hekili/State.lua:5655: attempt to call method 'QueueAuraEvent' (a nil value)

[string "@Interface/AddOns/Hekili/State.lua"]:5655: in function `QueueAuraExpiration'
[string "@Interface/AddOns/Hekili/Dragonflight/WarriorArms.lua"]:850: in function `handler'
[string "@Interface/AddOns/Hekili/State.lua"]:6034: in function `RunHandler'
[string "@Interface/AddOns/Hekili/Core.lua"]:1965: in function <Interface/AddOns/Hekili/Core.lua:1476>

**Comment by OhsawaSenpai** [comment]
I tested it again, it seems the issue only occurs with **Colossus Smash**, not with Warbreaker.

I was also able to get an error. Seems to be the same error as the one above. 
_Update: Interface/AddOns/Hekili/State.lua:5655: attempt to call method 'QueueAuraEvent' (a nil value)

[string "@Interface/AddOns/Hekili/State.lua"]:5655: in function `QueueAuraExpiration'
[string "@Interface/AddOns/Hekili/Dragonflight/WarriorArms.lua"]:850: in function `handler'
    [string "@Interface/AddOns/Hekili/State.lua"]:6034: in function `RunHandler'
[string "@Interface/AddOns/Hekili/Core.lua"]:1965: in function <Interface/AddOns/Hekili/Core.lua:1476>_

**Comment by OhsawaSenpai** [comment]
Also, considering the long CD of Colossus Smash/Warbreaker, shouldn't this be part of the CDs instead of the normal priority list?

**Comment by Hekili** [comment]
Thanks, these error messages will help me get this sorted.  That's exactly what I needed to see.

**Comment by manu310891** [comment]
colossus_smash = {
        id = 167105,
        cast = 0,
        cooldown = 45,
        gcd = "spell",

        talent = "colossus_smash",
        notalent = "warbreaker",
        startsCombat = false,
        texture = 464973,

        handler = function ()
            applyDebuff( "target", "colossus_smash" )
            applyDebuff( "target", "deep_wounds" )
            if talent.in_for_the_kill.enabled and buff.in_for_the_kill.down then
                applyBuff( "in_for_the_kill" )
                stat.haste = stat.haste + ( target.health.pct < 35 and 0.2 or 0.1 )
            end
            if talent.test_of_might.enabled then
                **state.QueueAuraExpiration( "test_of_might", TriggerTestOfMight, debuff.colossus_smash.expires )     "There is a point instead of a colon behind state"**
            end
        end,
    },
