### ISSUE TITLE
[REC] Covenant ability Wild Spirit outside of SL for BM Hunter

### ISSUE THREAD

**Issue by MrBean73** [Hekili/hekili#1726]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The convenant ability "Wild Spirits" ist recommended outside of Shadowlands content

### How to Reproduce

1. Enter game as BM Hunter
2. enter for example Instance outside SL (Mechagon Mythic not M+)
3. attack or target enemy
4. see recommendation

### Snapshot (Link)

https://pastebin.com/xGaQZ5ya

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/gH8V5iwmBf9kdQofcdzL7R

**Comment by Hekili** [comment]
Can you do me two favors?

1. Can you type `/dump Enum.CovenantType` in chat and share the result?
2. Can you mouse over your Wild Spirits ability and post a screenshot of the tooltip?

This may be a locale issue for the German client.  Thanks!

**Comment by MrBean73** [comment]
sure :-) 

![Dump_Enum](https://user-images.githubusercontent.com/116820193/198331862-e7383430-e581-44b0-a233-44ac2f22a133.png)
![WildSpirits-German](https://user-images.githubusercontent.com/116820193/198331919-9fd8535f-358a-4f72-a24f-2cd99b061281.png)

**Comment by Hekili** [comment]
Ok, the next beta build should address this.
