### ISSUE TITLE
[BUG] [Dragonflight] Multiple Lua error messages when entering the game

### ISSUE THREAD

**Issue by luisillo1cr** [Hekili/hekili#1728]
- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Simply, when I enter the game multiple Lua error messages appear, previously this error did not appear, until this version it started to appear and only by deactivating Hekili the error messages disappear.

I tried leaving only the Hekili addon installed and I deleted all the others from the addons installation folder and the issue still occurs. 

![error3](https://user-images.githubusercontent.com/54914200/198344452-9bcf4105-8c4b-48dd-a222-766742879a5f.png)
![error1](https://user-images.githubusercontent.com/54914200/198344458-6e548ba9-f2c2-4c32-8454-1b932a745c7c.png)
![error2](https://user-images.githubusercontent.com/54914200/198344459-e8ca26ca-8d00-4d01-b86c-2aae3a579785.png)

### How to Reproduce

1- Game login.
2- Immediately after logging in, the error messages pop up.
3- If I loot, the error message pops up.
4- When I open the bag, the error message also pops up.
5- If I deactivate all the addons, the error message also appears.

Note: First conflict with these error messages was with my alter level 20, however, with my main character of maximum level also happens.

### Player Information (Link)

https://pastebin.com/T1Nm3UTC

### Error Messages (Link)

https://pastebin.com/T1Nm3UTC

### Contact Information

AsukaLangley#11582

**Comment by Hekili** [comment]
I'm guessing this is a Shadowlands version of the addon.  There are beta versions you can download on CurseForge to test, but I have not posted a full release for Dragonflight yet.
