### ISSUE TITLE
[BUG] LUA Error on Ret Paladin

### ISSUE THREAD

**Issue by Ole6731** [Hekili/hekili#1729]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

All the Time I get this LUA Error

439x Interface/AddOns/Hekili/Events.lua:745: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
[string "@Interface/AddOns/Hekili/Events.lua"]:745: in function `updateGear'
[string "@Interface/AddOns/Hekili/Events.lua"]:360: in function `handler'
[string "@Interface/AddOns/Hekili/Events.lua"]:55: in function <Interface/AddOns/Hekili/Events.lua:47>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 tier28_2pc = 363677
 tier28_4pc = 364370
}
(for control) = "tier28_2pc"
bonus = "tier28_2pc"
aura = 363677
(*temporary) = nil
(*temporary) = 363677
(*temporary) = "attempt to call global 'GetPlayerAuraBySpellID' (a nil value)"
Hekili = <table> {
 GetMacroCastTarget = <function> defined @Interface/AddOns/Hekili/Events.lua:1137
 GetTTD = <function> defined @Interface/AddOns/Hekili/Targets.lua:982
 DeserializeStyle = <function> defined @Interface/AddOns/Hekili/Options.lua:10634
 IC = <table> {
 }
 EmbedAbilityOptions = <function> defined @Interface/AddOns/Hekili/Options.lua:4418
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Interface/AddOns/Hekili/Targets.lua:967
 GetPetBasedTargetSpells = <function> defined @Interface/AddOns/Hekili/Targets.lua:93
 After = <function> defined @Interface/AddOns/Hekili/Utils.lua:281
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 UpdateDisplayVisibility = <function> defined @Interface/AddOns/Hekili/UI.lua:1986
 IsEnabled = <function> defined @Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Interface/AddOns/Hekili/State.lua:6540
 SetMode = <function> defined @Interface/AddOns/Hekili/Options.lua:11447
 currentSpecOpts = <table> {
 }
 GetPetBasedTargetSpell = <function> defined @Interface/AddOns/Hekili/Targets.lua:105
 ToggleHold = <function> defined @Interface/AddOns/Hekili/State.lua:6565
 SpecializationChanged = <function> defined @Interface/AddOns/Hekili/Classes.lua:5837
 Update = <function> defined @Interface/AddOns/Hekili/Core.lua:1477
 AddToStack = <function> defined @Interface/AddOns/Hekili/Core.lua:240
 PLAYER_ENTERING_WORLD = true
 GetNumTargetsAboveHealthPct = <function> defined @Interface/AddOns/Hekili/Targets.lua:1138
 freshFrame = false
 UpdateUseItems = <function> defined @Interface/AddOns/Hekili/Events.lua:685
 SetSpecOption = <function> defined @Interface/AddOns/Hekili/Options.lua:4200
 GetDefaults = <function> defined @Interface/AddOns/Hekili/Options.lua:616
 dumpKeyCache = <table> {
 }
 UpdateDamageDetectionForCLEU = <function> defined @Interface/AddOns/Hekili/Events.lua:1547
 SetEnabledState = <function> defined @Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetDisplayByName = <function> defined @Interface/AddOns/Hekili/Core.lua:1448
 Options = <table> {
 }
 ReInitialize = <function> defined @Interface/AddOns/Hekili/Core.lua:158
 npUnits = <table> {
 }
 baseName = "Hekili"
 GetAbilityInfo = <function> defined @Interface/AddOns/Hekili/Classes.lua:5780
 GetOption = <function> defined @Interface/AddOns/Hekili/Options.lua:9508
 State = <table> {
 }
 OnEnable = <function> defined @Interface/AddOns/Hekili/Core.lua:181
 RestoreDefault = <function> defined @Interface/AddOns/Hekili/Classes.lua:995
 DumpProfileInfo = <function> defined @Interface/AddOns/Hekili/Core.lua:2095
 GetNextPrediction = <function> defined @Interface/AddOns/Hekili/Core.lua:1364
 CmdLine = <function> defined @Interface/AddOns/Hekili/Options.lua:9996
 GetPredictionFromAPL = <function> defined @Interface/AddOns/Hekili/Core.lua:668
 IsDisplayActive = <function> defined @Interface/AddOns/Hekili/UI.lua:2091
 GetNumTargetsBelowHealthPct = <function> defined @Interface/AddOns/Hekili/Targets.lua:1162
 SetupPetBasedTargetDetection = <function> defined @Interface/AddOns/Hekili/Targets.lua:119
 ShowDiagnosticTooltip = <function> defined @Interface/AddOns/Hekili/UI.lua:2819
 Notify = <function> defined @Interface/AddOns/Hekili/Options.lua:11408
 OnInitialize = <function> defined @Interface/AddOns/Hekili/Core.lua:61
 NewModule = <function> defined @Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetErrors = <function> defined @Interface/AddOns/Hekili/Utils.lua:44
 ResetThreadClock = <function> defined @Interface/AddOns/Hekili/Core.lua:654
 EmbedItemOption = <function> defined @Interface/AddOns/Hekili/Options.lua:4636
 DumpPetBasedTargetInfo = <funct

### How to Reproduce

Retribution Paladin. Just Log in and have hekili enabled

### Player Information (Link)

https://pastebin.com/rUY4PTXY

### Error Messages (Link)

https://pastebin.com/KxPC1Smu

### Contact Information

oa673@gmx.de

**Comment by Hekili** [comment]
You are using a 9.2.7 version.  There is not a release for Retribution for Dragonflight yet.
