### ISSUE TITLE
[REC] [Dragonflight] Death Knight / Unholy - Death And Decay Recommended when standing in Death And Decay with Death's Echo Talent

### ISSUE THREAD

**Issue by kkelley1987** [Hekili/hekili#1731]
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When taking the Death's Echo talent (Death's Advance, Death and Decay, and Death Grip have 1 additional charge.) Hekili recommends Death and Decay when standing in Death and Decay.
![image](https://user-images.githubusercontent.com/1396307/198362162-e55a0928-a42d-4634-a0c8-3b0c3c207127.png)

### How to Reproduce

1. Enter Game as an Unholy Death Knight
2. Go to target dummies and stand near two of them.
3. Put down death and decay
4. Hekili suggest putting down another death and decay

### Snapshot (Link)

https://pastebin.com/K8q4yLB8

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8sKSwCTGb1Gew77wY6KoNj

### Contact Information

Martialbob#8722

**Comment by Hekili** [comment]
Please clarify.  Is Death and Decay on cooldown when it's being recommended?

**Comment by kkelley1987** [comment]
No, Death's Echo gives you a second charge of Death and Decay.
![image](https://user-images.githubusercontent.com/1396307/198374440-27b97a49-299c-4023-81ad-48d50d5ecdab.png)

**Comment by Hekili** [comment]
Ah, okay.  This is a simple priority issue, then.  When I get actual DF priorities that account for charges, it'll be resolved.

**Comment by Hekili** [comment]
Let me know if this is still an issue after the release.

**Comment by kkelley1987** [comment]
fixed
