### ISSUE TITLE
[BUG] [Dragonflight] Beast Mastery - autosnapshot creates snapshots after each I'm targeting a target

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1732]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As I wrote in my github thread as a comment that BM autosnapshots too often and you wrote to make a new issue, here it is. Autosnapshot creates snapshots after each target targeting, check pastebin pls.

### How to Reproduce

Be a BM hunter on dummies and try targeting first then second etc.

### Player Information (Link)

https://pastebin.com/SBydRPFt

### Error Messages (Link)

https://pastebin.com/VYH9YjPX

### Contact Information

Markô#2877

**Comment by Hekili** [comment]
The snapshot you posted is from your Interrupts display.  Please update with a snapshot from your Primary display if/when it occurs.
