### ISSUE TITLE
[REC] BM Hunter Cobra Shot Recommended Too Often in AOE

### ISSUE THREAD

**Issue by Plasmaxyz** [Hekili/hekili#1733]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When executing an aoe rotation on my BM hunter with beast cleave and kill cleave, I am getting cobra shot recommended far too often than it should be, so much so that while sitting at 2 charges of kill command with beast cleave up, the addon still recommends using cobra shot in aoe. 

### How to Reproduce

1: Enter game as BM hunter
2: Take Alpha Predator, Beast Cleave, Kill Cleave, Animal Companion talents
3: Begin aoe rotation on three target dummies
4: After roughly 10 seconds see recommendations 

### Snapshot (Link)

https://pastebin.com/djDucUMk

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hfJE9DnVVynYmdxYwL62Vj

### Additional Information

As you can see in the sim with 3 targets, cobra shot is rarely recommended to the point of it being 2-3 times per minute. Whereas in game with the same setup, I get recommended to use cobra shot roughly 13 times per minute when following the displayed priority. 

### Contact Information

Plasma#6030

**Comment by bchinfoon** [comment]
I posted this in another ticket that got closed...but for me this has worked as a stop gap until there is a fix:


I made a copy of my Beast Mastery priorities and went to action list and edited the following for cleave:
21. Kill Command:
focus > cost
25. Cobra Shot:
focus.time_to_max < gcd * 2 & cooldown.kill_command.remains

I'm not sure if this is 100% optimized or not, but I am getting pretty much 100% uptime on beast cleave and 3 stacks of frenzy maintained pretty much all the time so I think it's a decent hack until the developer provides a fix. if you want to do this make sure you point to the new copy of the priority list you have made in the Beast Mastery tab. With this hack I am getting Cobra Shot recommended pretty much never for cleave.

**Comment by Hekili** [comment]
The Kill Command edit shouldn't really matter there.  I've made a couple of similar edits and they'll be in the release version.  If it is still an issue after the release, let me know.  I'll keep an eye out for updated Hunter priorities.

**Comment by MrBean73** [comment]
hi Hekili, i think you forget the conditions for cobra shot under "cleave" , "Cobra Shot" the field is blank in release. and the behavoiur is the same as before. too many cobra shots

**Comment by tomtim90** [comment]
Yeah still getting a lot of Cobra Shots recommended during cleave.

https://pastebin.com/2EdyNEdp

Often telling me to spam CS 3x in a row on 3 targets.

10.0.0-01 release.

**Comment by Williamn88** [comment]
In the default profile atm it seems like the Cobra shot entry at line 31 in cleave have no conditions which makes it dump focus and never get above the threshold for KC as mentioned. With that being said adding "focus.time_to_max<gcd*2" like the  current apl used in raidbots did not fix the issue.

Here is a snap shot that shows it - https://pastebin.com/HUJ708Uf
Seems like it fails it and then selects it on a recheck ?

EDIT: I see suggestions and workarounds to fix it which is great. But the apl is correct and should work as it is. Its the same that is live on raidbots/simc at the moment which does as it should.

**Comment by tpfleck** [comment]
I am also encountering this issue - I've tried to place a couple conditions as well which haven't been resulted in any change. Likely a problem with the APL rather than a technical detail.

**Comment by MrBean73** [comment]
„Cobra Shot:
focus.time_to_max < gcd * 2 & cooldown.kill_command.remains“  
This works for me

**Comment by bchinfoon** [comment]
> I am also encountering this issue - I've tried to place a couple conditions as well which haven't been resulted in any change. Likely a problem with the APL rather than a technical detail.

Where are you editing?  Are you Importing your Profile after editing or manually editing the Action List?

**Comment by TheHambrick** [comment]
https://pastebin.com/4Q9L8Ayz still doing it as of 10.0.0-03. I know a fix wasn't in the changelog but I saw in the changelog that you added more info to snapshots, so hopefully a snapshot from 10.0.0-03 will help

**Comment by MrBean73** [comment]
reload Priority and the conditions for Cobra Shot gone...till not fix in 10.0.0-03

**Comment by TheHambrick** [comment]
Fixed in 10.0.0-04 just went for 2 1/2 minutes on 5 targets and cast 8 cobra shots
