### ISSUE TITLE
[BUG] REPLACE THIS TEXT WITH A SHORT DESCRIPTION OF THE BUG YOU ARE REPORTING

### ISSUE THREAD

**Issue by Cubano0o** [Hekili/hekili#1735]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

you are telling me there is a 10. version of hekili. i am literally on wow up at this moment and the highest level it goes to is 9.2. so if you have a 10. may i have the url to install it from because i do not see it anywhere.

### How to Reproduce

1

### Player Information (Link)

1

### Error Messages (Link)

1

### Additional Information

1

### Contact Information

Cubano #6919

**Comment by marekCs** [comment]
https://www.curseforge.com/wow/addons/hekili/files/all

**Comment by Cubano0o** [comment]
this is for curseforge not wowup?

**Comment by Gyudon47** [comment]
You need to change the download to beta or alpha. You're downloading the stable version. All dragonflight releases are still in beta
