### ISSUE TITLE
Enhance Shaman; Post Primordial Wave (Talent) doesn't recommend using a lightning bolt in aoe when playing venthyr covenant

### ISSUE THREAD

**Issue by Nepv1** [Hekili/hekili#1736]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After using primordial wave the addon should recommend using a lightning bolt as a spender to abuse the lightning bolt on every target with a flame shock, however it continues recommending to use chain lightning (default aoe spender) never using the primordial wave lightning bolt buff

### How to Reproduce

Be venthyr (possibly other covenants except necro)
Use Primordial Wave
Go about rotation 

### Snapshot (Link)

https://pastebin.com/1cXmYimS

**Comment by Hekili** [comment]
Please test after installing the release version of the addon.  Thanks!

**Comment by PhilipH3ro** [comment]
Still not working, maybe covenant check or spellid issue? Tested with edited action lists.
