### ISSUE TITLE
10.1.0-beta9 - Havoc DH: Not recommending Vengeful Retreat to activate Initiative talent, and not recommending Sigil of Flame

### ISSUE THREAD

**Issue by Ohm1989** [Hekili/hekili#1737]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Ideally, both Vengeful Retreat and Sigil of Flame should be recommended on cooldown to take advantage of the new Initiative talent with high uptime, and Sigil of Flame now available to Havoc spec adds both a DPS increase as well as on-demand fury generation 

### How to Reproduce

1. Enter the game as a Havoc DH
2. Take the Sigil of Flame (class talent top row, right side) and the Initiative talent (Havoc tree, 5th row, left side)
3. Execute default recommended rotation
4. Sigil and Vengeful do not get recommended, even with movement toggle turned on as well

### Snapshot (Link)

https://pastebin.com/9tsQUXGj

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8V4kf949GvP4TkMGeGcKcN

### Additional Information

It seems that the Raidbots sim is using Vengeful Retreat to activate Initiative 15 times in the fight for a 25.8% uptime on the Initiative buff, but Hekili does not recommend this in-game. Sigil of Flame was used only 3 times during the sim for a 6.5% uptime which also does not seem correct.

**Comment by Hekili** [comment]
This should be resolved in the release coming out in a few minutes.  If not, feel free to reopen.
