### ISSUE TITLE
Issue with moving addon on the screen

### ISSUE THREAD

**Issue by Glendan78** [Hekili/hekili#1738]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

when you try to move the icons you are unable to "let go" of the icons. They just stay stuck on the curser and you are then unable to click anything until you reload ui.

### How to Reproduce

Happens with each character that I log in with.

### Player Information (Link)

build: v9.2.7-1.0.0b level: 60 (60) class: PALADIN spec: retribution  talents: none  pvptalents: none  covenant: kyrian  conduits: condensed_anima_sphere = 13    golden_path = 13    lights_barding = 13    ringing_clarity = 13    truths_wake = 13    virtuous_command = 13  soulbinds: [forgelite_prime_mikanikos]    brons_call_to_action = 1    effusive_anima_accelerator = 1    forgelite_filter = 1    regenerating_materials = 1    soulglow_spectrometer = 1    soulsteel_clamps = 1  sets: gavel_of_the_first_arbiter = 1     tier28 = 4  gear: gavel_of_the_first_arbiter = 1     tier28 = 4  legendaries: none  itemIDs: none  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Retribution     petbased = false     potion = spectral_strength     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     check_wake_range = false  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      arcane_torrent             = S1  [05]     blade_of_justice           = 3   [01]     blessing_of_freedom        = -   [01]     blessing_of_protection     = 0   [01]     blessing_of_sacrifice      = 9   [01]     consecration               = SM4 [06]     crusade                    = S5  [05]     crusader_strike            = 5   [01]     divine_shield              = ST  [06]     divine_steed               = G   [06]     divine_storm               = M4  [06]     divine_toll                = S6  [05]     final_reckoning            = S8  [05]     gavel_of_the_first_arbiter = R   [06]     hammer_of_justice          = S3  [05]     hammer_of_wrath            = 1   [01]     hand_of_hindrance          = =   [01]     hand_of_reckoning          = M3  [06]     healthstone                = S4  [05]     judgment                   = 4   [01]     lay_on_hands               = S2  [05]     phial_of_serenity          = S7  [05]     rebuke                     = M5  [06]     shield_of_vengeance        = SR  [06]     templars_verdict           = 2   [01]     turn_evil                  = S-  [05]     word_of_glory              = 8   [01]

### Error Messages (Link)

https://pastebin.com/XUmp4sys

### Contact Information

Discord ID:  Glendan#3905

**Comment by Glendan78** [comment]
Also have noticed that when swapping Wake of Ashes with Radiant Decree the addon doesn't seem to recognize Radiant Decree

**Comment by Wyste** [comment]
Your using the wrong version of the addon for the new PrePatch retail is on. Use the beta version of the addon in whatever addon updater you use. You want the latest version (10.1.0-betaX)

Also, Paladin's are not yet fully implemented in the pre-patch version of the addon, so you will need to be patient and keep watching the changelog of the releases to see when it's added.

**Comment by Glendan78** [comment]
Thank you for the fast response and making this addon that I have been
using for years.

**Comment by Wyste** [comment]
Nope, I don't make it, Hekili makes the addon. I'm just trying to be helpful!
