### ISSUE TITLE
[REC] 10.1.0-beta9 - Fury Warrior not recommending Spear of Bastion, Avatar, or Odyn's Fury

### ISSUE THREAD

**Issue by Kranky916** [Hekili/hekili#1739]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am using the Mythic+ suggested talent tree for Fury Warrior found here: https://www.wowhead.com/ptr/talent-calc/warrior/fury/DAPEERUUEEZUURlBAQBEOVURUUAVUBVIFAQBE and I am using the Kyrian covenent.

It is not recommending Spear of Bastion, Avatar, or Odyn's Fury at all.  They should be recommended while Enraged.

### How to Reproduce

1. Enter the game as a Fury Warrior with the Kyrian covenant.  
2. Use this talent build: https://www.wowhead.com/ptr/talent-calc/warrior/fury/DAPEERUUEEZUURlBAQBEOVURUUAVUBVIFAQBE
3. Attack a dummy and you will not see Spear of Bastion, Avatar, or Odyn's Fury recommended at all.

### Snapshot (Link)

https://pastebin.com/R1MWSwiu

### Contact Information

Kranky#0895

**Comment by Wyste** [comment]
Fury's APL (which came from SIMC) does not have them included in the rotation list currently.
You can either add them yourself (and any other missing new talent/ability) to the rotation, or wait for SIMC to update their APL's and then Hekili to update the addon for the Fury spec.

**Comment by addicu** [comment]
I have noticed that if you have Spear of Bastion untalented and you're in SL (with Kyrian Covenant) the APL skips it.

**Comment by Wyste** [comment]
Covenant/new talent overlaps are tricky at the moment. #1714 already covers this (with some discussion) and I imagine a better solution is being worked on as well, but not yet currently fixed as of this time.

**Comment by Hekili** [comment]
Warrior priorities will be updated to include abilities when there's a priority written that includes them.  SimC doesn't have updates for Warrior yet.  @Wyste might help fill in the blanks in the meantime.
