### ISSUE TITLE
Celestial Alignment not being registered as used. So keeps suggesting it, despite being on CD

### ISSUE THREAD

**Issue by RumbleDumble** [Hekili/hekili#1740]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I use Celestial Alignment when prompted, however, Hekili does not register it as used and continues to suggest it despite it being on CD

### How to Reproduce

1. Enter Game as Balance Druid
2. Do Hekili rotation on target dummies until Celestial Alignment is suggested  
3. Observe that that CD does not disappear from suggested 

### Player Information (Link)

build: v10.1.0-beta9 level: 60 (60) class: DRUID spec: balance  talents: astral_communion     astral_influence     balance_of_all_things     celestial_alignment     convoke_the_spirits     eclipse     elunes_guidance     frenzied_regeneration     fury_of_elune     improved_barkskin     improved_sunfire     innervate     ironfur     lunar_shrapnel     lycaras_teachings     matted_fur     moonkin_form     natures_balance     natures_vigil     nurturing_instinct     orbit_breaker     orbital_strike     power_of_goldrinn     rattle_the_stars     shooting_stars     solstice     soothe     soul_of_the_forest     stampeding_roar     starfall     starfire     starlord     starsurge     stellar_flare     sunfire     swipe     thick_hide     thrash     twin_moons     typhoon     umbral_embrace     ursols_vortex     waning_twilight     wild_charge  pvptalents: none  covenant: necrolord  conduits: born_of_the_wilds = 7    carnivorous_instinct = 9    evolved_swarm = 9    taste_for_blood = 10    tough_as_bark = 9    wellhoned_instincts = 9  soulbinds: [plague_deviser_marileth]    kevins_oozeling = 1    oozs_frictionless_coating = 1    plagueborn_cleansing_slime = 1    ultimate_form = 1    undulating_maneuvers = 1    volatile_solvent = 1  sets: cosmic_gladiators_badge_of_ferocity = 1     gladiators_badge = 1     tier28 = 4  gear: antecedents_aliform_joggers = 1     charm_of_eternal_winter = 1     chestguard_of_the_fixed_stars = 1     cinch_of_unity = 1     cosmic_gladiators_badge_of_ferocity = 1     cosmic_gladiators_band = 1     cosmic_gladiators_greatstaff = 1     cosmic_gladiators_leather_shoulderpads = 1     cowled_batwing_cloak = 1     elegy_of_the_eternals = 1     gladiators_badge = 1     handwraps_of_the_fixed_stars = 1     headpiece_of_the_fixed_stars = 1     leggings_of_the_fixed_stars = 1     modified_defense_grid = 1     tier28 = 4     umbrahide_armguards = 1  legendaries: frenzyband = 1     unbridled_swarm = 1  itemIDs: 172321, 183034, 183040, 186785, 186817, 186866, 188270, 188847, 188848, 188849, 188853, 189567, 189772, 190465, 190619  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 6     damageOnScreen = true     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = true     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Balance     petbased = false     potion = spectral_intellect     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     delay_berserking = false     solo_drift = false     starlord_cancel = false  toggles:     cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = dual      potions = false   keybinds:      adaptive_swarm              = A7  [06]     astral_communion            = 7   [01]     barkskin                    = S4  [05]     bear_form                   = A5  [06]     brutal_slash                = 7   [07]     cat_form                    = C5  [04]     convoke_the_spirits         = A8  [06]     cosmic_gladiators_resonator = 0   [08]     cyclone                     = 8   [07], 8   [08]     dash                        = S6  [05]     entangling_roots            = S3  [05]     ferocious_bite              = 3   [07], 3   [08]     fury_of_elune               = =   [01]     gladiators_badge            = S=  [06]     gladiators_medallion        = -   [08]     healthstone                 = A=  [04]     hibernate                   = 9   [07]     innervate                   = 8   [01]     maim                        = 6   [08]     mark_of_the_wild            = A6  [06]     moonfire                    = 2   [01]     moonkin_form                = SB  [05]     natures_vigil               = F   [05]     prowl                       = S-  [06]     rake                        = 2   [07], 2   [08]     regrowth                    = A1  [06]     rip                         = 4   [07], 4   [08]     shred                       = 1   [07], 1   [08]     soothe                      = S2  [05]     stampeding_roar             = S7  [05]     starfall                    = 6   [01]     starfire                    = 4   [01]     starsurge                   = 3   [01]     stellar_flare               = 9   [01]     sunfire                     = 5   [01]     swipe                       = 7   [07]     swipe_bear                  = 7   [07]     swipe_cat                   = 7   [07]     thrash                      = 5   [07]     thrash_bear                 = 5   [07]     thrash_cat                  = 5   [07]     travel_form                 = ASZ [03], C3  [04]     typhoon                     = E   [05]     ursols_vortex               = 0   [01], S5  [05]     wild_charge                 = SZ  [05]     wrath                       = 1   [01]

### Error Messages (Link)

N/A

**Comment by IIeTpoc** [comment]
Install please Bugsack and Buggrabber addons. Then reboot wow, turn off all addons but Hekili Bugsack Buggrabber and start following recommendations. When this error occures again post both snapshot and LUA errors from BugSack on different links via pastebin.com and put links here. It will help fixing the problem

**Comment by RumbleDumble** [comment]
> Install please Bugsack and Buggrabber addons. Then reboot wow, turn off all addons but Hekili Bugsack Buggrabber and start following recommendations. When this error occures again post both snapshot and LUA errors from BugSack on different links via pastebin.com and put links here. It will help fixing the problem

I'm not getting an Error at all

**Comment by Bsirk** [comment]
Then you are going to have to do a !snapshot You can read how to do this in the discord and take a snapshot of when this is happening. Then add it to the ticket.

**Comment by Hekili** [comment]
Yeah, this belongs as a Recommendations ticket with the required information submitted correctly.  Feel free to resubmit if needed.
