### ISSUE TITLE
Celestial Alignment being recommended while on CD and after use

### ISSUE THREAD

**Issue by RumbleDumble** [Hekili/hekili#1742]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When starting rotation, Celestial Alignment is being recommended and not going away after use. 

### How to Reproduce

1.) Log into Balance Druid
2.) Use these Talents: BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQSiIQChkEkIgWCJJhWCiDkDAFplIESDgA

3.) Do default rotation on target dummy

### Snapshot (Link)

https://pastebin.com/AAqRguuz

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/c18MuWcufsk4Rj7dzQWnLE

### Additional Information

If that snapshot is incorrect, please let me know. That is the only text that appeared when snapshotting 

### Contact Information

BigOlTiddyMuncher#8336

**Comment by Hekili** [comment]
Your snapshot is not complete.

**Comment by RumbleDumble** [comment]
> Your snapshot is not complete.

https://pastebin.com/TMgnFySz

Here is Balance snapshot :)

**Comment by Hekili** [comment]
Thanks.  Is there anything in the "Warnings" section of the addon when this occurs?

**Comment by RumbleDumble** [comment]
> Thanks. Is there anything in the "Warnings" section of the addon when this occurs?

Nope, nothing. No error or anything

**Comment by Hekili** [comment]
I think this is resolved; let me know if this is still happening for you after the initial 10.0 release goes live (in a half hour or so).  If it's still having problems, add new snapshots to the ticket.  Thanks.

**Comment by RumbleDumble** [comment]
> I think this is resolved; let me know if this is still happening for you after the initial 10.0 release goes live (in a half hour or so). If it's still having problems, add new snapshots to the ticket. Thanks.

Hi, still having the issue, new Snapshot: https://pastebin.com/xwqF6ue3
