### ISSUE TITLE
Convoke the Spirits being recommended for Feral despite not having the talent and not being in SL's content 

### ISSUE THREAD

**Issue by RumbleDumble** [Hekili/hekili#1743]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Convoke the Spirits being recommended for Feral despite being in Stormwind and not having Convoke talented 

### How to Reproduce

1.) Enter the game as Feral Druid
2.) Use this Talent Setup: BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAQkU0iISSSSRDQEHIJAAAAAAoIAiAAJSSSQiIBAAAAAAAIB

3.) Use default Feral Rotation 

### Snapshot (Link)

https://pastebin.com/PUq6gsHr

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/e18WoszWrVHJdhiFrggYig

### Contact Information

BigOlTiddyMuncher#8336

**Comment by Hekili** [comment]
Your snapshot is not complete.  Make sure to CTRL+A to select all and CTRL+C to copy.

**Comment by RumbleDumble** [comment]
> Your snapshot is not complete. Make sure to CTRL+A to select all and CTRL+C to copy.

https://pastebin.com/PPmUDVX2

Here's Feral one

**Comment by Hekili** [comment]
This will be fixed in the release tonight.
