### ISSUE TITLE
[BUG] Spellflash sometimes fails to flash on some abilities.

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#1745]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I've noticed that sometimes it does not properly flash Moonfire as Feral and New Moon as Balance, the display shows them properly, however.

### How to Reproduce

I've not found a certain way to reproduce this. For now, it seems random to me, will update if that changes.

### Player Information (Link)

BALANCE: https://pastebin.com/RvrgeUGD FERAL: https://pastebin.com/NX4SUHig

### Error Messages (Link)

-

### Additional Information

If this uses spellflashCore it might have some outdated spell IDs, since to my knowledge it hasn't been updated for ages, just a thought. I don't have spellflashCore installed now, but the same thing happens when I do.

### Contact Information

Discord: Niclas#7159

**Comment by ghost** [comment]
Updated with the correct Feral talent build.

Also might be relevant.
I have Moonfire on Shift-2 and New Moon on Shift-3, could it be that those keybinds are sometimes not detected?

**Comment by Hekili** [comment]
Initial release will have a fix in place.  If it isn't resolved, feel free to reopen the ticket.
