### ISSUE TITLE
Feral Druid - Feral Frenzy/Furious Bite Apex procs recommended as opener from prowl

### ISSUE THREAD

**Issue by Shizukanashi** [Hekili/hekili#1746]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

its recommending feral frenzy as opener from prowl. feral frenzy condition is 'combo_points < 2' so it will always recommend this immediately after prowl unless you are 3 or more combo points while out of combat. if you have a apex proc active and leave combat, it will recommend you to bite from prowl as well. I believe Rake should be recommended after prowl all the time.
![image](https://user-images.githubusercontent.com/81050337/198420896-46a76033-c74e-472d-ae36-98c7d833dddf.png)
![image](https://user-images.githubusercontent.com/81050337/198420785-1318f973-84f9-4d1c-a952-49f2ea81a3ef.png)

### How to Reproduce

1. Be a Feral Druid
2. Talent into Feral Frenzy/Apex - BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIRSJNIJJRSLNARyBSCAAAAAApIASCAISCBJIhWCAAAAAAgEA
3. Enter Cat form + be out of combat

### Snapshot (Link)

https://pastebin.com/zfytAtrp

### Additional Information

here is snapshot of apex proc being recommended after prowl as well - https://pastebin.com/dcUpdEqS

**Comment by Hekili** [comment]
I'm going to leave this as-is, since the Feral theorycrafters seem to have set this up intentionally.  I'll watch for priority updates from them and update if this changes.
