### ISSUE TITLE
[BUG] LUA Error with HUD Edit Mode

### ISSUE THREAD

**Issue by aemar32** [Hekili/hekili#1747]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

This addon throws up a LUA error upon opening Edit Mode for my HUD on my Holy Paladin.  If I don't open Edit Mode, I don't get any errors.

### How to Reproduce

Enter game as Holy Paladin.
Open Edit mode.

### Player Information (Link)

https://pastebin.com/uV8Y3c8c

### Error Messages (Link)

https://pastebin.com/V8C2xqzD

### Contact Information

Aemar#0593

**Comment by Hekili** [comment]
This is a "taint" issue -- your error message blames a different addon.
`1x [ADDON_ACTION_FORBIDDEN] AddOn 'Classic Quest Log' tried to call the protected function 'ClearTarget()'.`
