### ISSUE TITLE
Cyclotronic

### ISSUE THREAD

**Issue by Buckwyld** [Hekili/hekili#175]
**BEFORE SUBMITTING AN ISSUE:**

1.  Currently using v8.2.0-06-alpha2 from the Twitch Downloader. 

2.  Could not find a ticket regarding this issue. Searched for both terms used below. 

**Describe the Bug/Issue**
Cycotronic Blast is not being shown when inserted into the trinket Pocket-Sized Computational Device on a Havoc Demonhunter, with all Hekili functionality enabled. Other classes are seeing this ability in the rotation. I have deleted and reinstalled the mod with no success. 

**To Reproduce**
Easily reproducible. Equip trinket, it doesn't show up in any part of the rotation on Hekili. 

**Expected behavior**
Would expect to see the Cyclotronic Blast ability to show up on the rotation for Havoc Demonhunter. 

**Screenshots**
If you need a screenshot showing it's not on there, please let me know. 

**WHEN SUBMITTING AN ISSUE:**

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/b5wfU3Rr

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Thanks for the ticket.  The Use Items action is missing from the Havoc priority and will be added ASAP.

**Comment by Buckwyld** [comment]
Thank you for looking at this, and thank you in advance for putting it into the rotation.

**Comment by Hekili** [comment]
Please update to 06-alpha5 and reopen if you still have problems.
