### ISSUE TITLE
Enhancement only showing windfury, flametongue, and lightning shield

### ISSUE THREAD

**Issue by orcphelia** [Hekili/hekili#1750]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

No matter what I do, the primary icons and spell flash are stuck on windfury, flametongue, and lightning shield even though they are on. nothing else shows up in the addon.

### How to Reproduce

Enter game as enhancement shaman

### Snapshot (Link)

https://pastebin.com/dWhs7NC3

**Comment by Hekili** [comment]
Snapshot is incomplete, but I'm posting a release in a bit, so you can open a new ticket if you're still having issues after installing the release.  Thanks.
