### ISSUE TITLE
[BUG]the icons aren't showing up on my screen

### ISSUE THREAD

**Issue by Mishel71** [Hekili/hekili#1751]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon isn't putting the icons on my screen.

Error 0000250622673d0
Interface/addons/hekili/Events.lus745: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
[string:@Interface/AddOns/Hekili/Events.lua"}:745: in function 'updateGear'
[string:@Interface/AddOns/Hekili/Events.lua"}:360: in function handler'
[string:@Interface/AddOns/Hekili/Events.lua"}:55: in function <Interface/AddOns/Events.lua:47>
NewModule = <funtion> defubed @Interface/AddOns/Hekili/Libs/AceAddon-3.0.lua 235
Get Erros = <function> defined @Interface/AddOns/Hekili/Utils.lua:44
ResetThreadClock = <function> defrined @Interface/AddOns/Hekili/Core:lua654
EmbedItemOption = <function>

I have followed the steps provided on CurseForge under Troubleshooting. I have also deleted the cache on WoW. I am unsure what else to do. 

I don't know what Pastebin is. But here is the information:
build: v9.2.7-1.0.0b
level: 60 (60)
class: MAGE
spec: arcane

talents: none

pvptalents: none

covenant: night_fae

### How to Reproduce

Its at all logins. The icons do not load. 

### Player Information (Link)

i don't know how

### Error Messages (Link)

I don't know how

### Contact Information

Mishel#5625

**Comment by vond82** [comment]
1. You're using a Shadowlands release that doesnt work for the pre-patch. Set up your addon manager to download beta versions to get Hekili to work with pre-patch. :) 
2. Mage is not yet implemented in the beta mentioned above, Hekili is working on adding every spec but with so much changed everyone just has to be patient
