### ISSUE TITLE
Multiple Lua Errors on lvl 54 DK

### ISSUE THREAD

**Issue by Terenfirehawk** [Hekili/hekili#1752]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Bugsack report
227x Interface/AddOns/Hekili/Events.lua:745: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
[string "@Interface/AddOns/Hekili/Events.lua"]:745: in function `updateGear'
[string "@Interface/AddOns/Hekili/Events.lua"]:952: in function `handler'
[string "@Interface/AddOns/Hekili/Events.lua"]:77: in function <Interface/AddOns/Hekili/Events.lua:66>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 tier28_2pc = 364383
 tier28_4pc = 363411
}
(for control) = "tier28_2pc"
bonus = "tier28_2pc"
aura = 364383
(*temporary) = nil
(*temporary) = 364383
(*temporary) = "attempt to call global 'GetPlayerAuraBySpellID' (a nil value)"
Hekili = <table> {
 GetMacroCastTarget = <function> defined @Interface/AddOns/Hekili/Events.lua:1137
 GetTTD = <function> defined @Interface/AddOns/Hekili/Targets.lua:982
 DeserializeStyle = <function> defined @Interface/AddOns/Hekili/Options.lua:10634
 IC = <table> {
 }
 EmbedAbilityOptions = <function> defined @Interface/AddOns/Hekili/Options.lua:4418
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Interface/AddOns/Hekili/Targets.lua:967
 GetPetBasedTargetSpells = <function> defined @Interface/AddOns/Hekili/Targets.lua:93
 After = <function> defined @Interface/AddOns/Hekili/Utils.lua:281
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:409
 UpdateDisplayVisibility = <function> defined @Interface/AddOns/Hekili/UI.lua:1986
 IsEnabled = <function> defined @Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Interface/AddOns/Hekili/State.lua:6540
 SetMode = <function> defined @Interface/AddOns/Hekili/Options.lua:11447
 LoadingScripts = false
 currentSpecOpts = <table> {
 }
 GetPetBasedTargetSpell = <function> defined @Interface/AddOns/Hekili/Targets.lua:105
 ToggleHold = <function> defined @Interface/AddOns/Hekili/State.lua:6565
 SpecializationChanged = <function> defined @Interface/AddOns/Hekili/Classes.lua:5837
 Update = <function> defined @Interface/AddOns/Hekili/Core.lua:1477
 AddToStack = <function> defined @Interface/AddOns/Hekili/Core.lua:240
 PLAYER_ENTERING_WORLD = true
 GetNumTargetsAboveHealthPct = <function> defined @Interface/AddOns/Hekili/Targets.lua:1138
 freshFrame = false
 UpdateUseItems = <function> defined @Interface/AddOns/Hekili/Events.lua:685
 SetSpecOption = <function> defined @Interface/AddOns/Hekili/Options.lua:4200
 GetDefaults = <function> defined @Interface/AddOns/Hekili/Options.lua:616
 dumpKeyCache = <table> {
 }
 UpdateDamageDetectionForCLEU = <function> defined @Interface/AddOns/Hekili/Events.lua:1547
 SetEnabledState = <function> defined @Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Interface/AddOns/Hekili/Core.lua:1448
 Options = <table> {
 }
 ReInitialize = <function> defined @Interface/AddOns/Hekili/Core.lua:158
 npUnits = <table> {
 }
 baseName = "Hekili"
 GetAbilityInfo = <function> defined @Interface/AddOns/Hekili/Classes.lua:5780
 GetOption = <function> defined @Interface/AddOns/Hekili/Options.lua:9508
 State = <table> {
 }
 OnEnable = <function> defined @Interface/AddOns/Hekili/Core.lua:181
 RestoreDefault = <function> defined @Interface/AddOns/Hekili/Classes.lua:995
 DumpProfileInfo = <function> defined @Interface/AddOns/Hekili/Core.lua:2095
 GetNextPrediction = <function> defined @Interface/AddOns/Hekili/Core.lua:1364
 CmdLine = <function> defined @Interface/AddOns/Hekili/Options.lua:9996
 GetPredictionFromAPL = <function> defined @Interface/AddOns/Hekili/Core.lua:668
 IsDisplayActive = <function> defined @Interface/AddOns/Hekili/UI.lua:2091
 GetNumTargetsBelowHealthPct = <function> defined @Interface/AddOns/Hekili/Targets.lua:1162
 SetupPetBasedTargetDetection = <function> defined @Interface/AddOns/Hekili/Targets.lua:119
 ShowDiagnosticTooltip = <function> defined @Interface/AddOns/Hekili/UI.lua:2819
 Notify = <function> defined @Interface/AddOns/Hekili/Options.lua:11408
 OnInitialize = <function> defined @Interface/AddOns/Hekili/Core.lua:61
 NewModule = <function> defined @Interface/AddOns/AngryAssignments/libs/AceAddon-3.0/AceAddon-3.0.lua:235
 GetErrors = <function> defined @Interface/AddOns/Hekili/Utils.lua:44
 ResetThreadClock = <function> defined @Interface/AddOns/Hekili/Core.lua:654
 EmbedItemOption = <function> defined @Interface/AddOns/Hekili/O

### How to Reproduce

Enter game as DK Blood/Unholy.  Enter Combat

### Player Information (Link)

https://pastebin.com/KNy8jABJ

### Error Messages (Link)

https://pastebin.com/fwSu45CA

### Additional Information

The errors only appear when entering combat. Hekili still seems to work, but lots of errors.

### Contact Information

Teren#0092

**Comment by vond82** [comment]
You're using a Shadowlands release that doesnt work for the pre-patch. Set up your addon manager to download beta versions to get Hekili to work with pre-patch. :)

**Comment by Terenfirehawk** [comment]
Patrik, 

 

Thank you so very much!

 

Kate

 

 

Katherine Reab, RN. FNE. LNC

Integrity Legal Nurse Consulting PDX

 ***@***.***> ***@***.***

970-231-7205

 

 ***@***.***> ***@***.***

 <http://legalnursepdx.com/> http://legalnursepdx.com

 <tel:(503)%20775-3221> 503-775-3221

 

HELPING YOU UNDERSTAND MEDICAL RECORDS, 

GIVING YOU MORE TIME TO  PRACTICE LAW. 

 

Please note we offer record retrieval services for both civil and criminal defense attorneys.

 

 

 

 

 

For large PHI files, please use our Hightail account to transmit information:  <https://www.hightail.com/u/wendy223> https://www.hightail.com/u/wendy223

 

Notice of Confidentiality:

This message along with any documents, files or attachments is intended for the sole purpose of the individual, or individuals, to whom it is addressed. It may contain information that is confidential, privileged and exempt from disclosure. This is in accordance with The Health Information Portability and Accountability Act (HIPAA). If you are not the intended recipient, please immediately advise the sender and destroy the original correspondence and its attachments without reading, opening, printing or saving in any manner. Thank you.
