### ISSUE TITLE
[BUG] Enhancement shaman - Doom Winds legendary breaks queue

### ISSUE THREAD

**Issue by Fynnconceivable** [Hekili/hekili#1753]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili loads and displays an appropriate queue of spells before entering combat (as far as I can tell) when using the Doom Winds legendary and windfury totem talent (i.e., it starts with dropping windfury and then stormstrike).

However, once I enter combat and start my rotation, the ability queue freezes and won't update no matter what spells/abilities I use.

### How to Reproduce

1. Equip the Doom Winds legendary.
2. Use this talent buildout (a customization of the "Totem Slam" build from Wowhead to include some AOE-focused talents like Crash Lightning): BcQAfcj78nJtvjmejSqe5Zhm9IJJpAJSSSAQCJJAAAAAAAAAAAAA0iQESiQAIRSBQJRSgC
3. I'm using the default display modes (Automatic and Single-Target came pre-checked) and am displaying 4 spells.
4. Find a target dummy and drop Windfury Totem.
5. Start wailing on it—the Hekili queue icons won't update.

### Player Information (Link)

https://pastebin.com/YhFmJwaf

### Error Messages (Link)

https://pastebin.com/tPNY42WJ

### Additional Information

I didn't see any lua errors actually pop up, so I didn't install BugSack or BugGrabber, but the Hekili add-on itself is logging warnings, which I recorded at the Pastebin link above. Happy to gather more info as needed.

### Contact Information

Fynn#4724

**Comment by Hekili** [comment]
I'm going to post a new release; please let me know if you still have issues with Doom Winds / WFT after updating.

**Comment by Fynnconceivable** [comment]
This particular issue is fixed! But opening a new ticket for another Doom Winds bug.
