### ISSUE TITLE
[REC] RET PALADIN, CONTINUES RECOMMENDING RADIANT DECREE WHILE ON CD 

### ISSUE THREAD

**Issue by TerrySmith22** [Hekili/hekili#1756]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When I talent for Radiant Decree, for my M+ build, it is being recommended, after use and while on cooldown and a with enough holy power is being suggested while on cooldown.

![WoWScrnShot_102822_023107](https://user-images.githubusercontent.com/89761273/198519196-06a80172-66c6-4bb2-b14a-161deaacb2ed.jpg)

### How to Reproduce

Enter game as ret paladin with Radiant Decree talent selected.
Enter combat on training dummy
See that it recommends Radiant Decree, and then suggests it again while on cooldown and with enough holy power thats suppose to activate it. 
Continue to build and spend holy power, still suggests it till it is used again, but continues the cycle

### Snapshot (Link)

https://pastebin.com/YHipiU3u

**Comment by Hekili** [comment]
Thanks, fixing now.

**Comment by TerrySmith22** [comment]
love it thanks!
