### ISSUE TITLE
Warrior/Fury Passiv abalities showned

### ISSUE THREAD

**Issue by TakeyaIkuhara** [Hekili/hekili#1757]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my warrior fury build I was expected only activ abalities to be shown but it seems I've got passiv too.

### How to Reproduce

Enter the game with a warrior fury build.
Look the recommandations.

### Snapshot (Link)

https://pastebin.com/wm6d1GuR

**Comment by Hekili** [comment]
Your snapshot is not complete, use CTRL+A and CTRL+C to copy the whole snapshot (there should be many lines of text).

What specific passive ability are you seeing?

**Comment by Hekili** [comment]
It looks like the displayed abilities are:
1. Recklessness
2. Dreadfire Vessel (trinket)
3. Blood Fury (racial)

None of those are passive abilities.  Am I mistaken?

**Comment by TakeyaIkuhara** [comment]
Sorry for the waste of time... yes, it was the trinket and the racial (I'm really a noob ^^' )
