### ISSUE TITLE
[Bug] Ret Paladin, not recommending Templar's Verdict / Final Verdict with final verdict legendary equipped

### ISSUE THREAD

**Issue by Wouterdude** [Hekili/hekili#1758]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Ret paladin, I expect the addon to recommend Templar's Verdict / Final Verdict when reaching more than 3 holy power on Single target or 2 targets, however it keeps recommending holy power  builder's

### How to Reproduce

Equip Final verdict Legendary or talent into final verdict

### Snapshot (Link)

Retribution; Primary - Judgment(0.00), Crusader Strike(1.24), Crusader Strike(2.49)

**Comment by Wouterdude** [comment]
talent build:

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAgQAIKpFJSOAAplSSSKlAAAAAAAICJJplAJJFkEUOgSA

**Comment by Jacii1121** [comment]
Snapshot that I hope supports this ticket.  - https://pastebin.com/X1kZN9fR
Warnings - https://pastebin.com/aj5wTdHx

**Comment by Hekili** [comment]
Thanks for the ticket and snapshot.  This should be fixed by the same fix as #1761, and the warning re: Aspiration of Divinity will be resolved at the same time.
