### ISSUE TITLE
[BUG] RET PALADIN - NOT RECOMMENDING ANY HOLY POWER ABILITIES OR WAKE OF ASHES or AVENGING WRATH

### ISSUE THREAD

**Issue by Reunion2792** [Hekili/hekili#1759]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my retribution paladin the addon is never recommending Holy Power abilities such as Templar's Verdict or Divine storm, and also not recommending wake or ashes/radiant decree. It also doesn't show Avenging Wrath.

### How to Reproduce

1. Enter the game as a retribution paladin 
2. Perform rotation

### Snapshot (Link)

https://pastebin.com/bWHmhPSW

**Comment by Reunion2792** [comment]
Talents
BYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAIKplIRCAKplkkWJAAAAAAASDJJpIQSShDkEUCB

**Comment by Hekili** [comment]
This should be resolved by the same fix as #1761 -- I'll post an update in a few minutes.
