### ISSUE TITLE
Necrotic Strike not working

### ISSUE THREAD

**Issue by Excitedguy** [Hekili/hekili#176]
Necrotic Strike not displaying when talented and enabled in Hekili. Causes all icons to disappear when it queues up. Looking at DeathKnightUnholy.lua, it appears the spell ID for Necrotic Strike and Necrotic Wound are both invalid compared to what's on Wowhead database. I also see the following line, but not sure what to change it to test since it doesn't appear to be a spell ID, but some other ID like a talent ID.

necrotic_strike = 149

**Comment by Hekili** [comment]
Please fill out a complete ticket and show what edits you made to try to use it.  Include a snapshot.

If I add Necrotic Wound to my default priority, it shows up without an issue:
![image](https://user-images.githubusercontent.com/9438134/61571016-a695e580-aa5e-11e9-9e6b-7e9ff556394f.png)

The PvP talent ID you pointed out is correct (these are different from spell IDs).

The spell ID for Necrotic Strike is 223829, and is properly used.
![image](https://user-images.githubusercontent.com/9438134/61571026-b3b2d480-aa5e-11e9-89d0-c822b5f104e6.png)

The spell ID for Necrotic Wound is 223929, and is accounted for correctly as well.
![image](https://user-images.githubusercontent.com/9438134/61571042-caf1c200-aa5e-11e9-8993-7ce5da8aaa65.png)

**Comment by Excitedguy** [comment]
Thanks for the detailed information. It appears to work correctly when you
spec into the talent, but doesn't work with Conflict and Strife essence...

**Comment by Hekili** [comment]
That makes some sense. 

When you say "doesn't work", what do you mean exactly? It isn't recommended? The whole display blanks out? It deletes you whole WoW?

This is why I ask for complete tickets with snapshot, etc.

**Comment by Excitedguy** [comment]
My apologies, I will be more detailed and will submit a complete ticket for
the next issue I find. For this issue, it ignores the ability entirely. The
rest of the rotation displays without issue. It's as if I never put the
ability in my rotation when I set it. As soon as I change my essence to
something else and spec back into Necrotic Strike, it starts to show
properly.

**Comment by Hekili** [comment]
You can still submit the snapshot, etc. on this ticket.

**Comment by Excitedguy** [comment]
I opened a new ticket with all the necessary information, I will close out
the other ticket since it's technically resolved.

https://github.com/Hekili/hekili/issues/178
