### ISSUE TITLE
[FEATURE] REPLACE THIS TEXT WITH A BRIEF DESCRIPTION OF YOUR NEW FEATURE

### ISSUE THREAD

**Issue by hubikys** [Hekili/hekili#1760]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

почему вы сразу закрываете мои темы, ваш аддон не работает, я хочу всего лиш узнать примерное время ожидания

### Additional Information

почему вы сразу закрываете мои темы, ваш аддон не работает, я хочу всего лиш узнать примерное время ожидания

### Contact Information

100volt#5124

**Comment by TheHambrick** [comment]
To save you a trip to google translate: The guy is asking, "why do you immediately close my topics, your addon does not work, I just want to know the approximate waiting time."

If they were all exceedingly high quality tickets similar to this one, I'm not sure why you would close them /s
