### ISSUE TITLE
RET PALADIN NOT RECOMMENDING TEMPLARS VERDICT OR FINAL RECKONING EVER

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#1761]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Whenever I'm on Single Target when I build to 5 holy power its never recommending Templar's Verdict.  Its only recommending more builders, never a spender.  Now as soon as a Second Target enters, it updates to Divine Storm which is correct.  

It also NEVER recommends Final Reckoning.  Or Radiant Decree if you have that talented.  I had to Untalent Radiant Decree to get Wake of Ashes to even work.

### How to Reproduce

Enter game as Retribution Paladin
Take Radiant Decree and Final Reckoning as talents.

Build to 5 holy power on Single target for Never recommending Templar's Verdict.

For Multiple Targets, build to 5 holy power and follow rotation and see that it never recommends final reckoning or radiant decree.

### Snapshot (Link)

https://pastebin.com/cGhmRif8

### Contact Information

Pulse#0223

**Comment by Hekili** [comment]
Thanks, this will be fixed in a little bit.
