### ISSUE TITLE
[BUG] Suggested abilities not changing properly

### ISSUE THREAD

**Issue by cs96** [Hekili/hekili#1762]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am playing a fury warrior and just downloaded hekili and the suggested abilities are not changing properly. It can be stuck on heroic leap for a while, even after I've used it and it's on cooldown. It also doesn't cycle through Rampage, raging blow and bloodthirst properly.

### How to Reproduce

1. Enter a game as fury warrior.

### Player Information (Link)

https://pastebin.com/UBGwLHmR

### Error Messages (Link)

.

### Contact Information

Vappe#7105

**Comment by cs96** [comment]
https://gfycat.com/frenchcompassionatearcticfox
video shown here

**Comment by Krucible94** [comment]
I think the fix might be here:
WarriorFury.lua
"if talent.deft.experience.enabled then" --> "if talent.deft_experience.enabled then"

**Comment by Hekili** [comment]
This should be resolved in 05.  If not, please open a new ticket with a new snapshot.  Thanks!
