### ISSUE TITLE
Ret paladin Still not recommending Final Reckoning Or Radiant Decree

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#1763]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I understand you just released the new update for Ret paladin and now Templar's Verdict is being recommended for ST.  But Its still not recommending Final Reckoning or Radiant Decree ever.  

### How to Reproduce

Enter game as Retribution Paladin
Have Final Reckoning and Radiant Decree talents selected

Go AOE and it is never recommended.

### Snapshot (Link)

Not sure how to snapshot something that isnt' being recommended

### Contact Information

Pulse#0223

**Comment by felipelariu** [comment]
Not recommending Divine Toll either

**Comment by Jacii1121** [comment]
I was having similar recommendation issues, but I reset priority back to default, it seemed to correct itself.  (I didn't previously mess with the priority).  /hekili > Priorities > Retribution > Summary > And click the big yellow refresh arrow.

**Comment by Pulseonline** [comment]
> I was having similar recommendation issues, but I reset priority back to default, it seemed to correct itself. (I didn't previously mess with the priority). /hekili > Priorities > Retribution > Summary > And click the big yellow refresh arrow.

Trying that

**Comment by Pulseonline** [comment]
That worked!

**Comment by craveica** [comment]
For me is not recommending (even after reset):
Divine Toll
Final Reckoning
Justicar's Vengeance

and it doesn't have any option to keep up Blessing of Dawn/Dusk.

**Comment by Pulseonline** [comment]
> I was having similar recommendation issues, but I reset priority back to default, it seemed to correct itself. (I didn't previously mess with the priority). /hekili > Priorities > Retribution > Summary > And click the big yellow refresh arrow.

This worked perfectly!

**Comment by Pulseonline** [comment]
Yea Hekili everything is recommended and working perfectly.  Just not sure why we had to refresh the priority.  I never messed with it

**Comment by apospathi** [comment]
Just did some testing as I was experiencing the same thing.  I would also add, Final Reckoning is considered a cooldown, so make sure cooldowns are enabled.

Furthermore I noticed that it will only recommend Final Reckoning when you have 4+ holy power.  From my little testing I noticed that it wasn't adjusting to pool holy power when FR is coming off of cooldown.  I'm super new to this, but I'm guessing this is an issue with the APL and not the addon itself.

**Comment by Nemesis977** [comment]
for me even after reset of the last release is not recommending
Final Reckoning
Divine Toll

He told me to use exorcism at pull without consacration (that i think is wrong)


and it doesn't have any option to keep up Blessing of Dawn/Dusk.

**Comment by Purehotty** [comment]
Also noticed it is telling you to Exorcism without having Consecration down to spread the DoT and isn't suggestion final reckoning or Divine Toll

**Comment by Blujelly87** [comment]
I still have this issues as well, have tried some of the above but this didnt work for me

**Comment by LordSkeletor** [comment]
> I still have this issues as well, have tried some of the above but this didnt work for me

Post a snapshot. You very likely have it disabled somewhere.

You can run /hek, go to Abilities, and select Final Reckoning in dropdown. Make sure it is not set to be Disabled, Boss Encounter Only, and also check if there is a required toggle. If you want it to always be available you can change that to None.

**Comment by Hekili** [comment]
After updating to the 05 release, comment and let me know if the issue persists.  If it does, provide a new snapshot as well as your talent string.  Thanks!
