### ISSUE TITLE
RET PALA HAMMER OF WRATH FROM FINAL VERDICT NOT RECOMMENDED AT ALL

### ISSUE THREAD

**Issue by Peligroz** [Hekili/hekili#1767]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello. As the title susgests, the addon doesn't recommend Hammer of Wrath procs from Final Verdict. It only recommends Hammer of Wrath with Crusade / Avenging Wrath and when the target is below 20% health.

### How to Reproduce

1. Enter game as a Retribution Paladin.
2. Use Final Verdict legendary or Final Verdict talent.
3. Keep using Final Verdict until it allows you to use Hammer of Wrath.
4. See recommendations.

### Snapshot (Link)

https://pastebin.com/RncsSdyf

**Comment by Hekili** [comment]
Thanks.  After updating to 05, let me know if this is still an issue.  If it is, please post a new snapshot along with a copy of your talent string.

**Comment by Peligroz** [comment]
Still an issue for the legendary Final Verdict. However, it seems to work for the talent version.
https://pastebin.com/qaRHwBeZ
BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAAAgokWSikAQaKJJpVCAAAAAAgQkkkWSQCFOQSQJKB

**Comment by Hekili** [comment]
I have tested and this will be fixed in the upcoming release.
