### ISSUE TITLE
Lua error [ADDON_ACTION_FORBIDDEN] AddOn 'Hekili' tried to call the protected function 'TargetUnit()

### ISSUE THREAD

**Issue by imarkvisser** [Hekili/hekili#1768]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I got this lua error after I tried using my soulshape again. 

    [ADDON_ACTION_FORBIDDEN] AddOn 'Hekili' tried to call the protected function 'TargetUnit()'.
    [string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
    [string "=[C]"]: in function `TargetUnit'
    [string "@Interface/FrameXML/EditModeManager.lua"]:1518: in function `RefreshTargetAndFocus'
    [string "@Interface/FrameXML/EditModeManager.lua"]:1462: in function `OnEditModeEnter'
    [string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
    [string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
    [string "=[C]"]: in function `Show'
    [string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
    [string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
    [string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
    [string "=[C]"]: in function `SetAttribute'
    [string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
    [string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

### How to Reproduce

Press soulshape. Press it again.

### Player Information (Link)

https://pastebin.com/raw/30rE6hPz

### Error Messages (Link)

https://pastebin.com/raw/GyagLYYj

**Comment by Hekili** [comment]
My addon doesn't ever touch those functions.  Something else is tainting your user interface and blaming the addon.  Blizzard may need to resolve this as part of their UI overhaul.
