### ISSUE TITLE
Addon not showing for monk

### ISSUE THREAD

**Issue by rynotoole** [Hekili/hekili#1769]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Displayed lastnight now when I log in hekili is not showing at all and it is enabled.

### How to Reproduce

1. Enter game as Monk

### Player Information (Link)

n/a

### Error Messages (Link)

n/a

**Comment by imarkvisser** [comment]
Monk is not supported yet. Windwalker is coming soon.

**Comment by lootahn** [comment]
:(
