### ISSUE TITLE
UH DK Gargoyle Opener Slightly Varies From Suggested Opener and then suggests several Scourge Strikes instead of Death Coil

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#1771]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Current UH DK Reccomended opener is as follows:
Gavel
Army
Outbreak/Blight
Festering
Festering
Dark Transformation
Gargoyle
Death Coil
Apocalypse
Death Coil
Death Coil + Racial/Trinket/Pots

Currently Hekili recommends the following https://pastebin.com/C58smDWM which omits a Death Coil after the Dark Transformation and Gargoyle combo in the sequence and goes straight into Apoc and then rapidly recommends Scourge Strike which can be found in the paste bin below.

### How to Reproduce

Load UH DK ST Talents with Gargoyle
Target Dummy
Adjust the Ability slider to 10 to see the Sequence.

### Snapshot (Link)

https://pastebin.com/kuGyRgNz

### Raidbots Sim Report (Link)

Raidbots currently just says Gargoyle Opener instead of listing spells.

**Comment by Hekili** [comment]
One Unholy ticket for all of your Unholy concerns, please.
