### ISSUE TITLE
UH Wounds M+ Build has Slightly Incorrect Opener From Discord and Wowhead Suggestions.

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#1772]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When talented into the following:
Army of the Dead
Unholy Blight
Anholy Assault
Apocalypse
Empower Rune Weapon

The opener for UH DK should be as follows:
AOTD
Unholy Blight
Unholy Assault
Dark Transformation
Apocalypse
Racial Potion Trinket
Covenant Ability
Death Coil
Empower Rune Weapon

The addon currently suggests:
AOTD
Unholy Blight
Unholy Assault
Dark Transformation
Racial
Empower Rune Weapon
Apocalypse
Festering Strike

### How to Reproduce

Load Hekili on Unholy DK with appropriate talents for Mythic Plus.

Change ability slider to 10 to view spell queue.

Compare opener suggestions from addon to opener suggestions from guide.

### Snapshot (Link)

https://pastebin.com/uw9yr0cU

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jtDaNw6YWefAbxJ3KLhmWu            Potentially in beta as listed but also a different variation as well.

**Comment by Hekili** [comment]
If this is an issue in 05, keep updates in a single Unholy related ticket, please.
