### ISSUE TITLE
UH DK AOE Opener is Incorrect from information provided by guide.

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#1773]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Current opener for an AOE pack as suggested by the addon is as follows:
Unholy Blight
Unholy Assault
Racial
Empowered Rune Weapon
Apoc
Festering Strike
Scourge Strike
Scourge Strike

The current opener for an AOE pack as suggested by Wowhead and discord is as follows:
Unholy Blight
Abomb Limb (Currently in Orgrimmar so I'm aware it won't be suggested on these target dummy)
Empower Rune Weapon
Dark Transformation
Festering Strike
Unholy Assault
Vile Contagion
Death and Decay
Scourge Strike Spam

So a combination of no Vile Contagion or Death and Decay.

### How to Reproduce

Enter game as Death Knight.
Adjust spell queue to 10
Reference opener as compared to guide suggestion.

### Snapshot (Link)

https://pastebin.com/Fq3F9h96

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/91dnkTZWkaZJLekZgmwmEr  Completely different from the two openers discussed above.

### Additional Information

I also notice that after the AoE Burst opener, that addon suggests a lot of Death Coils instead of Epidemic. Current understanding is at 4+ targets with diseases it is appropriate to begin spamming epidemic instead of spending on Death Coil with this talent setup.

https://pastebin.com/rEPT34Cn

The above pastbin link is after following the addon suggested opener.  No DnD suggested and 3 festering strikes instead.`

**Comment by Hekili** [comment]
This doesn't look like a defect but will be addressed as priorities get updated in general.

**Comment by Hekili** [comment]
> I also notice that after the AoE Burst opener, that addon suggests a lot of Death Coils instead of Epidemic. Current understanding is at 4+ targets with diseases it is appropriate to begin spamming epidemic instead of spending on Death Coil with this talent setup.

You have 2 targets in your snapshot.

> The above pastbin link is after following the addon suggested opener. No DnD suggested and 3 festering strikes instead.

This should be resolved in the next release; in your case, it would show Death's Due, of course.

If this is unresolved in 05, can you post an updated snapshot along with your talent string?  Thanks.
