### ISSUE TITLE
[BUG] Feral recommends Blood Talon combo generators without having the talent activated

### ISSUE THREAD

**Issue by Testthewest123** [Hekili/hekili#1774]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

- Latest 10-2 version from curseforge
- "Bloodtalons" NOT skilled
- Recommendation includes Swipe on single target
- Recommendation includes Shred on 3+ targets
- Recommendation includes Thrash when Thrash has not yet run out (which in theory could be snapshotting / dynamic adaption for buffs)
- - Beta7 recommends the correct talents for single (shred) and multi targets (swipe on 3+ enemies), without overwriting Thrash immediately.

### How to Reproduce

1) Be a feral cat druid
2) Use BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIEt0gkkESRJgEJJJAAAAAAoIASSAgIJEkgEKJAAAAAAASA as a talent setup
3) Test on dummy

### Player Information (Link)

https://pastebin.com/D9aZrGBD

### Error Messages (Link)

no lua error

**Comment by Hekili** [comment]
Please resubmit a Recommendations ticket with a snapshot if you're confident you're still experiencing this issue in 05 or later.
