### ISSUE TITLE
[BUG] Nothing show in primary box

### ISSUE THREAD

**Issue by Darkman06660** [Hekili/hekili#1775]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hi,

With my priest (all spec) Hekili show nothing in the primary box but with my paladin with the retribution spec it's OK but it's KO withn the others specs.
A message indicate Hekili have no upload the modules.

Thank you.

### How to Reproduce

Nothing, just open the game
There's no error message

### Player Information (Link)

https://pastebin.com/VCyh41Fc

### Error Messages (Link)

https://pastebin.com/Mx8VeFX4

**Comment by vond82** [comment]
The message you got tells you that shadow priest has not yet been implemented for pre-patch.

**Comment by Darkman06660** [comment]
Ok thank you for the response, I thought there was a bug.

And thank you for your work on this add-on.
