### ISSUE TITLE
Ret Paladin Divine Toll still being recommended after use

### ISSUE THREAD

**Issue by Fost47** [Hekili/hekili#1776]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Divine Toll being recommended while on cooldown, believe issue maybe that the old spell is being used as Divine Toll has been updated spell since patch.

### How to Reproduce

1. Enter as Retribution Paladin
2. Take Divine Toll talents
3. Use Divine Toll so as on Cooldown
4. See recommendations still showing Divine Toll when it is on cooldown.

### Snapshot (Link)

https://pastebin.com/YPewmzjJ

**Comment by Hekili** [comment]
Please retest after updating to the 03 release.  If it is still an issue, submit an updated snapshot where Divine Toll is recommended despite being on cooldown.  Thank you!

**Comment by Fost47** [comment]
Hi, have retested but it is still recommending Divine Toll while it is still on cooldown. Have updated the snapshot.

**Comment by Hekili** [comment]
You don't have to replace original ticket info, you can just add links in comments.  So information doesn't get lost.  I'll be posting a new release in a little bit, so please post a new snapshot if you're having this issue (i.e., with Divine Toll on cooldown).  Please include your talent string as well, and confirm whether you're in Shadowlands content or not.  Thank you!

**Comment by Fost47** [comment]
Ok have retested and found that there are two distinct Divine toll spells, one is the Kryian covenant ability and only works in shadowlands and the other is the Talent tree ability and this works everywhere and is what Hekili is tracking. Hekili does not track the Covenant ability but the talented version from the talent tree is working as intended

**Comment by Hekili** [comment]
> If it is still an issue, submit an updated snapshot where Divine Toll is recommended despite being on cooldown.

**Comment by Hekili** [comment]
Next release will have another stab at fixing this issue.  It passes my testin, but I'm not sure if there is another variable here.  If you report again, please include your talent string and a new snapshot.
