### ISSUE TITLE
[BUG] Warlock rotation priorities gone in 10.0.0-02

### ISSUE THREAD

**Issue by Bri134** [Hekili/hekili#1777]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The warlock spec rotations were all present in the Priorities -> specialization dropdown in v10.0.0-01; they are all now missing in v02.

![image](https://user-images.githubusercontent.com/107523441/198724169-9ffab28c-c2c3-4189-b93f-f147925d54ad.png)

### How to Reproduce

1. Enter game as a warlock.
2. See no Hekili displays loaded
3. Type /Hekili; navigate to priorities
4. Click specialization dropdown
5. Observe no spec choices

### Player Information (Link)

https://pastebin.com/DaGsF7xU

### Error Messages (Link)

None

### Contact Information

Brians#3724 on Discord

**Comment by T0xicsmog** [comment]
Hekili relies on Simulationcraft APLs as the base for the rotation it displays for you. You will have to wait until your classes community theorycrafters devise an APL for the current class redesigns and then wait a little longer for hekili to implement them into the addon. Please be patient.

**Comment by Hekili** [comment]
There is a message at login that explains not all specs are supported yet. I'll get to it.
