### ISSUE TITLE
[REC] Ret Paladin priority not showing Final Reckoning, Exorcism, Divine Toll

### ISSUE THREAD

**Issue by JargerWolf** [Hekili/hekili#1778]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When testing the rotation on the training dummy, the addon is not suggesting the use of Final Reckoning or Exorcism at all. 

### How to Reproduce

1. Log into the game as Ret Paladin
2. Use the following talent build: BYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgokWSikAQaKJJpVCAAAAAAgQkkkWSQCFOQSQJKB
3. Spec into Kyrian Covenant
4. Use Bastion - Hero's Rest Target dummy for testing
5. Use and Spend Holy Power for 5 minutes (tracked based on CD of Gavel of the Arbiter) and never see any of the 3 abilities reccomended

### Snapshot (Link)

https://pastebin.com/VAvRkh4B

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tUfjfC5FagSZvVHbua5EZA

### Contact Information

Jarger Wolf#7528

**Comment by Hekili** [comment]
I will be posting a testfix soon.  I'm closing this ticket as an overlap of #1763.
