### ISSUE TITLE
Necrotic Strike not displaying with Conflict and Strife essence.

### ISSUE THREAD

**Issue by Excitedguy** [Hekili/hekili#178]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Necrotic Strike does not display in rotation when added in Action List if Conflict and Strife essence is equipped. Displays fine if Conflict and Strife is not equipped and Necrotic Strike is talented into.

**To Reproduce**
Add Necrotric Strike to Action List while Conflict and Strife essence is equipped.

**Expected behavior**
Necrotic Strike should appear in spell queue while added to Action List with Conflict and Strife essence enabled.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/cBjwtvhd

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/Lz9ecRfd

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Update to 06-alpha5 and submit a new ticket if still having issues.
