### ISSUE TITLE
DH Havoc Fel Bombardment

### ISSUE THREAD

**Issue by Zeuslight56** [Hekili/hekili#1780]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On the Pre patch the new legendary bis of the DH havoc is fel bombardment it consists of using throw glaive when we have 5 stack of fel bombardment with the immolation aura. Hekili does not advise.

### How to Reproduce

1: Enter games as DH Havoc and equip the legendary Fel Bombardment.
2: Activate immolation aura until you reach 5 stack of Fel Bombardment
3: Hekili does not advise throwing glaive when it is the priority.

### Snapshot (Link)

https://pastebin.com/xxCHYQdK

**Comment by Hekili** [comment]
In your snapshot, it does not show that you have Immolation Aura up.  Is that incorrect?

**Comment by Zeuslight56** [comment]
No it had just ended.

**Comment by Hekili** [comment]
After the new release (03) goes up, can you get a snapshot when all the conditions for using Throw Glaive would be met?  You should have Immolation Aura up at the time of snapshot.  Thanks!

**Comment by Zeuslight56** [comment]
No it still does not work, Hekili does not advise throw glaive to 5 stack of fel bombardment.
https://pastebin.com/DNnR2vMJ

**Comment by Zeuslight56** [comment]
With the right talent.
https://pastebin.com/tgYE3T2t

**Comment by Hekili** [comment]
This will be fixed in the next release.
