### ISSUE TITLE
Celestial Alignment still being recommended despite being used 

### ISSUE THREAD

**Issue by RumbleDumble** [Hekili/hekili#1782]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Celestial Alignment is still being recommended after use and when on CD

### How to Reproduce

1.) Login to Balance Druid 
2.) Use these Talents: BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQSiIQChkEkIgWCJJhWCiDkDAFplIESDgA
3.) Use rdefault regular Hekili rotation 

### Snapshot (Link)

https://pastebin.com/xwqF6ue3

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/oiS9wdzjpnpY8ifwWqtQGx

### Additional Information

I also attached a new snapshot to the previous ticket. I wasn't sure if you would see it though since it's a closed ticket

### Contact Information

BigOlTiddyMuncher#8336

**Comment by Hekili** [comment]
I'm not able to import the talents you listed.

**Comment by RumbleDumble** [comment]
> I'm not able to import the talents you listed.

BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQSiIQChkEkIgWCJJhWCiDkDAFplIESDgA

Try this

**Comment by Hekili** [comment]
This may be fixed in -03, which is being released right now.  Let me know either way.  If it's not resolved, please link a new snapshot where Celestial Alignment is being recommended despite being on cooldown.  Thanks!

**Comment by RumbleDumble** [comment]
> This may be fixed in -03, which is being released right now. Let me know either way. If it's not resolved, please link a new snapshot where Celestial Alignment is being recommended despite being on cooldown. Thanks!

Unfortunately, the issue is still happening. Here is new snapshot: https://pastebin.com/FhATMyyY

**Comment by Bsirk** [comment]
I can confirm. After posting the issue on my Shaman I logged into my Balance Druid and was hitting some target dummies. The same issue happened to me.

https://pastebin.com/2tqFRe5T

**Comment by AOkes** [comment]
I believe this has something to do with the Syzygy talent, directly underneath Celestial Alignment. It doesn't appear to be in the Lua code anywhere at all. Try switching to the Primordial Arcanic Pulsar talent, that's what fixed it for me.

**Comment by RumbleDumble** [comment]
> I believe this has something to do with the Syzygy talent, directly underneath Celestial Alignment. It doesn't appear to be in the Lua code anywhere at all. Try switching to the Primordial Arcanic Pulsar talent, that's what fixed it for me.

You are correct, I disabled the Syzygy talent and the rotation works fine!

**Comment by Hekili** [comment]
Great catch.  I'll regather Balance talents to make sure nothing else is missing/left out and post a correction.

**Comment by Hekili** [comment]
Incoming fix!
