### ISSUE TITLE
monk winderwalker no spells showing to use for aoe/single

### ISSUE THREAD

**Issue by kaza125125** [Hekili/hekili#1783]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

no spells are loading up for windwalker monk have reset to default  deleted and installed multiple times

### How to Reproduce

log in nothing shows up

### Player Information (Link)

https://pastebin.com/mGWU06Ce

### Error Messages (Link)

.

### Additional Information

getting no error messagaes 

### Contact Information

kaza#8631

**Comment by Lipstopica** [comment]
Guess you also can't see what it says in your in game chat box? or on the general page when you type /hekili. He is still working on classes/specs.
