### ISSUE TITLE
[BUG] Enhancement shaman - Queue gets stuck on windfury totem using Doom Winds legendary

### ISSUE THREAD

**Issue by Fynnconceivable** [Hekili/hekili#1786]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When using the Doom Winds legendary as enhance shaman, the Hekili priority queue functions as expected upon initially entering combat (first screenshot). However, after going through my rotation for a while, the ability queue gets stuck on Windfury Totem (second screenshot) regardless of what abilities I use. After waiting for the Doom Winds cooldown to fall off, the queue resumes as normal until I drop Windfury Totem again.

(Hi, yes, it's me again. I'm sorry for using Doom Winds.)

![Enhance-initial-queue](https://user-images.githubusercontent.com/47910126/198817410-68bfb66c-da29-4ab1-9ef2-05d3f089d4db.jpg)
![Enhance-queue-after-12-sec](https://user-images.githubusercontent.com/47910126/198817414-80a04e3f-adfc-4459-9fda-d9db6d14f221.jpg)

### How to Reproduce

1. Equip the Doom Winds legendary.
2. Use this talent buildout (a customization of the "Totem Slam" build from Wowhead to include some AOE-focused talents like Crash Lightning): BcQAfcj78nJtvjmejSqe5Zhm9IJJpAJSSSAQCJJAAAAAAAAAAAAA0iQESiQAIRSBQJRSgC
3. I'm using the default display modes (Automatic and Single-Target came pre-checked) and am displaying 4 spells.
4. Find a target dummy, enter combat, and drop Windfury Totem.
5. Start wailing on the dummy—or don't, honestly. Just stay in combat and wait for it.
6. At the 12 second mark, all of your ability icons in the queue will turn into Windfury Totem.

Bonus: Wait for the Doom Winds cooldown timer to tick down. Once the CD debuff drops off, the queue goes back to normal (displaying icons asking for windfury, stormstrike, crash lightning, etc.) Drop Windfury again to repeat issue.

### Player Information (Link)

https://pastebin.com/BjGiYfKh

### Error Messages (Link)

N/A

### Additional Information

I noticed that the issue occurs about 12 seconds after dropping windfury totem for the first time (see the 47 sec windfury CD timer in the screenshot, which I took ~half second late), which is what triggers the legendary Doom Winds effect. The Doom Winds buff lasts 12 seconds. Here's the tooltip:

[Doom Winds](https://www.wowhead.com/spell=335902/doom-winds)
Runecarving Power
Dropping Windfury Totem grants you 100% chance to gain Windfury Weapon and increases Windfury Weapon damage by 25% for **12 sec**. 

This can only occur once every **1 min**.

--
Windfury Totem itself lasts 2 minutes, and if I take the Doom Winds legendary off, the queue issue doesn't happen. So I think the code may just be missing the check against the 1 minute cooldown.

Edit: I waited out the 1 min CD while mindlessly swinging at the target, and sure enough, once the debuff fell off (and thus I could proc the Doom Winds effect again), the priority queue started working again—until 12 seconds after I dropped Windfury Totem.

### Contact Information

Fynn#4724

**Comment by IIeTpoc** [comment]
write !snapshot in discord chat and pls link a snapshot on pastebin.com and include link here

**Comment by Hekili** [comment]
This should be resolved in -04, which is being released now.
