### ISSUE TITLE
[REC] Kyrian Warrior doesnt recommend Spear of Bastion

### ISSUE THREAD

**Issue by chevyn11** [Hekili/hekili#1787]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Using the existing fury apl, which includes an entry for spear of bastion - it is never recommended to cast.

I have the snapshot linked below but the interesting line would be: 

`     17.  spear_of_bastion ( default - 18 ) - talent [ spear_of_bastion ] missing
`

Looks like it is not recommending spear of bastion as long as its not talented.

### How to Reproduce

Enter the game as Fury Warrior (possibly any warrior based on how its coded)
Do rotation 
It will never recommend spear of bastion

### Snapshot (Link)

https://pastebin.com/Ma9XRaQy

**Comment by Hekili** [comment]
Thanks for the ticket and data.  I am fixing this now and will post within the next hour or so.
