### ISSUE TITLE
[BUG] Hekili doesn't show up in game. 

### ISSUE THREAD

**Issue by SteffiLee86** [Hekili/hekili#1788]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The Hekili icons don't show up on my UI in game. I am currently testing on my 60 Balance Druid. 

I'm not sure what pastebin is but here is the character data:

build: v10.0.0-03
level: 60 (60)
class: DRUID
spec: balance

talents: astral_influence
    astral_smolder
    celestial_alignment
    circle_of_life_and_death
    cyclone
    denizen_of_the_dream
    eclipse
    friend_of_the_fae
    improved_barkskin
    improved_sunfire
    innervate
    lycaras_teachings
    mass_entanglement
    moonkin_form
    natural_recovery
    natures_balance
    natures_grace
    natures_vigil
    nurturing_instinct
    orbit_breaker
    primordial_arcanic_pulsar
    rejuvenation
    remove_corruption
    shooting_stars
    solar_beam
    solstice
    soothe
    soul_of_the_forest
    stampeding_roar
    starfall
    starfire
    starsurge
    stellar_flare
    sunfire
    swiftmend
    tiger_dash
    twin_moons
    typhoon
    umbral_embrace
    umbral_intensity
    waning_twilight
    wild_growth

pvptalents: none

covenant: night_fae

conduits: conflux_of_elements = 3
   innate_resolve = 3
   tireless_pursuit = 3

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   run_without_tiring = 1

sets: none

gear: chain_of_the_purposebound = 1
    cryptic_mask = 1
    cypheretched_band = 1
    fireheart_boots = 1
    gordunni_robe = 1
    salvaged_viperid_band = 1
    shimmerbough_leggings = 1
    symbol_of_the_raptora = 1
    withergrove_shardling = 1

legendaries: none

itemIDs: 106576, 175560, 183851, 184757, 188045, 190352, 190602, 190633, 24590

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    delay_berserking = false
    starlord_cancel = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    barkskin         = SA  [06]
    brutal_slash     = SD  [07]
    cyclone          = R   [01], R   [10]
    entangling_roots = SQ  [01], 1   [02], SQ  [10]
    ferocious_bite   = SF  [07]
    fury_of_elune    = 0   [01], SC  [10]
    growl            = SQ  [09]
    ironfur          = 5   [09]
    mangle           = SW  [09]
    moonfire         = 5   [01], SE  [07], 1   [09], 5   [10]
    prowl            = 1   [07]
    rake             = SW  [07]
    regrowth         = 1   [08]
    rip              = SC  [07]
    shred            = 5   [07]
    stampeding_roar  = 0   [07], SS  [09]
    starfall         = SC  [01], 0   [10]
    starfire         = SD  [01], SD  [10]
    starsurge        = SF  [01], SF  [10]
    stellar_flare    = SW  [01], SW  [10]
    sunfire          = SE  [01], SE  [10]
    swipe            = SD  [07]
    swipe_bear       = SD  [07]
    swipe_cat        = SD  [07]
    thrash           = SS  [07], SE  [09]
    thrash_bear      = SS  [07], SE  [09]
    thrash_cat       = SS  [07], SE  [09]
    tiger_dash       = =   [07]
    typhoon          = =   [01], =   [10]
    wild_charge      = 1   [01], SQ  [07], 1   [10]
    wrath            = SS  [01], SQ  [02], SS  [10]

warnings: none

### How to Reproduce

I'm not sure

### Player Information (Link)

See above

### Error Messages (Link)

NONE

**Comment by Duktoc** [comment]
I am also having the same issue. I have been using Hekili for a while but now no icons. I have checked all my settings and still no icons

**Comment by shredxt** [comment]
> I'm not sure what pastebin is

https://pastebin.com 

Are you sure Hekili is enabled?
https://i.imgur.com/zgNm08U.png

Have you tried reloading the priority pack from Defaults?
https://i.imgur.com/dHN9A8j.png

You'll have to excuse my incomplete/broken WAs but the Balance Druid display is working fine for me on v10.0.0-03
https://i.imgur.com/m9e60Ky.png

**Comment by SteffiLee86** [comment]
I have no idea what happened, but I logged back in to my druid and poof! It's here now. *Shrug*

**Comment by Hekili** [comment]
Thanks for confirming.
