### ISSUE TITLE
[Survival] Survival isn't currently included in Hekili 10.0.0-03

### ISSUE THREAD

**Issue by hlokk101** [Hekili/hekili#1789]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Survival doesn't exist in the addon. There's no Core, no Priorities. Only Beast Mastery and Marksmanship. I'm sorry if this is the wrong template for this issue, but the addon is not causing any errors or anything like that. It works perfectly well for BM and MM. You can see in the screen shot. 

My apologies if this is the wrong template for this, but there's no lua errors and I can't make the addon generate a snapshot for no recommendations since it doesn't even load when I am specced into Survival.
![Hekili no SV](https://user-images.githubusercontent.com/75588676/198828218-4d9f8dd9-c072-4cc4-8c29-5afbc4caf603.png)

### Contact Information

hlokk101#9930

**Comment by SpatenLa** [comment]
that is correct, survival is not yet included.

**Comment by hlokk101** [comment]
Survival still isn't in it?

**Comment by SpatenLa** [comment]
correct. the last 7 hours didnt change that

**Comment by hlokk101** [comment]
?
Why is it marked as completed then?

**Comment by Hekili** [comment]
Because it's not an issue, it's planned work.

**Comment by hlokk101** [comment]
Okay. Thanks for letting me know 👍
