### ISSUE TITLE
Add visibility option for "if in combat and has a target"

### ISSUE THREAD

**Issue by Excitedguy** [Hekili/hekili#179]
Please describe your idea or feature and when it would be useful.
Would be really useful to add an additional option to show a display when you are in combat and have a target selected. Right now, you can only choose between always showing it, having a target, or if your in combat. There's no way to show only the display when you are in combat and have a target. As a workaround, I have made edits to UI.lua to make this possible, but I have to keep making edits each time the addon is updated, would be nice to make it an official feature.

**Comment by rvnlord** [comment]
Kindly post your modifications or send it to me by email if you don't mind. I am not really a LUA kind of dev.

**Comment by Hekili** [comment]
This should be available in 8.3.
