### ISSUE TITLE
BM Hunter  on AoE it suggests Cobra Shot over Kill command even with 2 Kill Commands available

### ISSUE THREAD

**Issue by Ruffelgnab** [Hekili/hekili#1790]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my BM Hunter, on AoE, the addon suggests Cobra Shot over Kill command even with 2 Kill Commands available. If i just wait a second or so it changes to  Kill Command. If i keep spamming abilitys it never shows Kill Command. It can show 3 Cobra Shots in a row where it feels like it should be 2 Kill Commands and 1 Cobra Shot. On single target the addon suggests Kill Command as soon as its available.

### How to Reproduce

![WoWScrnShot_102922_133324](https://user-images.githubusercontent.com/116952450/198829445-6bce1ac5-8737-4bb1-914f-e763ae9d9236.jpg)

### Snapshot (Link)

https://pastebin.com/yxnH4eTu

**Comment by marekCs** [comment]
I'll use this thread, since the AOE rotation is going to be fixed, to see if we could consider adding a target swap on the Barbed shot to make it a well spaced on at least 2 targets.

**Comment by Hekili** [comment]
All of the Barbed Shot entries in the Cleave list have a `cycle_targets=1` flag.

**Comment by Hekili** [comment]
Re: Cobra Shot, I've made an adjustment to the priority so that Cobra Shot won't supplant Kill Command when Kill Command is waiting on Focus.  This will be posted soon.
