### ISSUE TITLE
[REC] Boomie SS during INC+RF still thinks it costs less than 40 AP

### ISSUE THREAD

**Issue by badudulance** [Hekili/hekili#1791]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During the RF ramp, it looks good regarding SS cost but near the end it still recommended SS while having like 25-30AP and was stuck like this till I lost the ramp and got stunned. Do mind this sometimes does not happen.

### How to Reproduce

1. Enter game as Balance Druid
2. Take these talents: BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAkkkIikkAQIJAaBJJRaJHgQwBCplAh0AI
3. Start rotation as dictated by Hekili ST with cooldowns on.
4. Get stuck on the SS and lose ramp.

### Snapshot (Link)

https://pastebin.com/FCWus0mn

### Additional Information

I believe I caught the snapshot at the right time, so let me know if I need to re-do the snapshot.

**Comment by Hekili** [comment]
In the snapshot provided, you have 40+ AP when Starsurge is recommended.  Please provide a snapshot where Starsurge is recommended but you do not have sufficient AP for it.
