### ISSUE TITLE
[REC] Boomie recommends Convoke after CA/RF without spending AP first AND FoE recommended right at the start of the ramp.

### ISSUE THREAD

**Issue by badudulance** [Hekili/hekili#1792]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Following Hekili ST with CD's on recommendations, enter eclipse, apply dots, pop CA+RF and it recommends Convoke right after that without spending the usually over 70AP first. Convoke should be used at the start of the ramp but with little AP first because it generates so much of it during Convoke. 

Also, FoE should be used 5 seconds before Sinful Hysteria but it is being recommended at the start, few seconds after Convoke.

### How to Reproduce

1. Enter game as Balance Druid
2. Use talents BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAkkkIikkAQIJAaBJJRaJHgQwBCplAh0AI
3. Start rotation normally with Hekili ST and CD's on
4. Enter CA+RF, get recommended Convoke instantly every time.
5. FoE being recommended 2-3 spells after Convoke.

### Snapshot (Link)

https://pastebin.com/fPp58Ee9

### Additional Information

https://pastebin.com/RZ7Nu88s this one is for FoE, other pastebin for Convoke.

**Comment by Hekili** [comment]
Please provide a Raidbots sim report for comparison purposes.

**Comment by badudulance** [comment]
https://www.raidbots.com/simbot/report/ibd3jbMevCoD3hkZxQLBm6
Does appear that even this report recommends convoke right after CA and RF, however that is afaik incorrect due to casting convoke and losing about 80AP generated from it. But I guess this will be resolved once the APL or whatever it's called by simcraft will be updated.
