### ISSUE TITLE
essence break build

### ISSUE THREAD

**Issue by Zeuslight56** [Hekili/hekili#1795]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With the DH Havoc's Essence Break build when we use Essence Break, Blande Dance and Death Sweep have to be reloaded and then use Chaos Strike/Annihilation until the Essence Break DOT disappears from the targets.

### How to Reproduce

Refer to wowhead link for rotation.

### Snapshot (Link)

https://pastebin.com/TeHdYVwV

### Additional Information

https://www.wowhead.com/guide/classes/demon-hunter/havoc/rotation-cooldowns-pve-dps

**Comment by Hekili** [comment]
You do not need to submit multiple tickets for the same spec when reporting priority concerns.  You can add to one ticket.  I will update Havoc priorities as they are updated in SimulationCraft.  Thanks.
