### ISSUE TITLE
Beta MM+ build  DH havoc

### ISSUE THREAD

**Issue by Zeuslight56** [Hekili/hekili#1796]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When you talent into the trio of [ Furious Throws](https://www.wowhead.com/beta/spell=393029/furious-throws), [ Accelerating Blade](https://www.wowhead.com/beta/spell=391275/accelerating-blade), and [ Soulrend](https://www.wowhead.com/beta/spell=388106/soulrend) you are committing to have Throw Glaive as a superior spender. You want to try to have Throw Glaive on cooldown in advance so it will not risk overcapping during other cooldown windows such as [ Demonic](https://www.wowhead.com/beta/spell=213410/demonic) and [ Essence Break](https://www.wowhead.com/beta/spell=258860/essence-break), plus it has a lot of value trying to utilize it in [ Initiative](https://www.wowhead.com/beta/spell=391215/initiative) windows that are not paired with your Essence Break.
In Mythic+ and AoE you will have to decide for [ Burning Wound](https://www.wowhead.com/beta/spell=391189/burning-wound) whether to apply it via tab target with [ Demon Blades](https://www.wowhead.com/beta/spell=203555/demon-blades) auto attacks or utilize [ Throw Glaive](https://www.wowhead.com/beta/spell=185123/throw-glaive). You should attempt to get your 3 debuffs applied on pull or very early into your immolation aura in a pull, throw glaive without the supporting talents is worse for DPS but much more simpler to maintain.

### How to Reproduce

Cast [ Immolation Aura](https://www.wowhead.com/beta/spell=258920/immolation-aura) on Pull
[ Felblade](https://www.wowhead.com/beta/spell=213241/felblade)
[ Throw Glaive](https://www.wowhead.com/beta/spell=185123/throw-glaive)
[ The Hunt](https://www.wowhead.com/beta/spell=370965/the-hunt)
[ Fel Rush](https://www.wowhead.com/beta/spell=195072/fel-rush)
[ Eye Beam](https://www.wowhead.com/beta/spell=198013/eye-beam)
[ Throw Glaive](https://www.wowhead.com/beta/spell=185123/throw-glaive)
[ Vengeful Retreat](https://www.wowhead.com/beta/spell=198793/vengeful-retreat)
[ Essence Break](https://www.wowhead.com/beta/spell=258860/essence-break)
[ Death Sweep](https://www.wowhead.com/beta/spell=210152/death-sweep)
[ Metamorphosis](https://www.wowhead.com/beta/spell=191427/metamorphosis)
[ Death Sweep](https://www.wowhead.com/beta/spell=210152/death-sweep)
[ Eye Beam](https://www.wowhead.com/beta/spell=198013/eye-beam)
[ Throw Glaive](https://www.wowhead.com/beta/spell=185123/throw-glaive)
Continue regular priority

### Snapshot (Link)

https://pastebin.com/rTPTy18b

### Additional Information

https://www.wowhead.com/guide/classes/demon-hunter/havoc/rotation-cooldowns-pve-dps

**Comment by Hekili** [comment]
Thanks for the information.  I'll continue to watch SimulationCraft for updated APLs and integrate them as I find them.
