### ISSUE TITLE
[REC] Not recommending Fel Devastation for Vengeance DH

### ISSUE THREAD

**Issue by Deathhunt** [Hekili/hekili#1798]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In 10.0.0-01 and later versions(up to v10.0.0-04 tested ), Veng. DH's Fel Devastation is no longer recommended. However, in v10.1.0-beta9 version it is recommended as intended. 

### How to Reproduce

Use 10.0.0-01 and later versions.
Use Vengeance DH to test.

### Snapshot (Link)

https://pastebin.com/9u80M81r

### Additional Information

After installing a newer version, it is required to fallback not only the interface itself to 10.1.0-beta9, but also hekili.lua in SavedVariables folder to the old one to make Fel Devastation recommended again.

**Comment by Hekili** [comment]
Will post a fix soon.

**Comment by Deathhunt** [comment]
Tested in v10.0.0-05, it seems to be fixed, Fel Devastation is back. Thanks a lot for the great work.
