### ISSUE TITLE
[REC] WOTLK - ROGUE - ASSASSINATION - Hunger For Blood Issue

### ISSUE THREAD

**Issue by Zavalla** [Hekili/hekili#1799]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Even if I use Hunger for Blood (so it's up in my buff) the AddOn keeps telling me to use Hunger for Blood, just like if it was'nt recognizing it's usage.

### How to Reproduce

1. Stealth
2. Garrote (playing solo on target dummy)
3. Hunger for blood
4. Follow with Mutilate and Slice and Dice

Notice that Hunger for Blood is still asking for it to be cast even if its up

### Snapshot (Link)

https://pastebin.com/d7RM0LeL

### Additional Information

I must add;

It seems to be fixed as SOON as GAROTTE is OFF the target...... it just stop asking for me to use Hunger for blood, if garrotte is not up... if it's up, it keeps asking me to use it.

### Contact Information

Ekazz#1951

**Comment by WrathPlayer** [comment]
I also ran into this bug, and was able to identify the underlying cause. I submitted a pull request to try and get this fixed.

**Comment by Hekili** [comment]
I would strongly recommend using https://github.com/zmsl/Hekili/releases until I actually post an updated release.  But his version probably needs the change as well.  @zmsl

**Comment by Hekili** [comment]
This should be addressed in the latest releases.
