### ISSUE TITLE
Spell Targets

### ISSUE THREAD

**Issue by thunderchylde** [Hekili/hekili#18]
I saw some comments in the code of being able to reference number of enemies hit by a spell - did that ever get to a point that it could be used in APLs?

(either in 7.3.5 or 8.0)

**Comment by Hekili** [comment]
Right now, it just lets you specify a target cap for an ability.  (And lets the addon use simc action lists that use spell_targets.X without having to revamp them.)

For instance, if you put **max_targets = 5** for an ability, if you have 10 active targets, spell_targets.whatever_ability will report as 5.

**Comment by thunderchylde** [comment]
spell_targets.lunar_strike is returning a table, not a number
