### ISSUE TITLE
Demonology Warlock Doom showing up to be cast before it's finished on Target

### ISSUE THREAD

**Issue by Journei** [Hekili/hekili#180]
Doom shows up as the next spell to cast on the rotation but Doom is still active on the target.  It only does damage at the end of the spell timer (25 seconds).  so if you cast it on the target again, the count down starts over.  So if there is 5 seconds left on the existing doom, it get reset to 25 seconds.  It only does damage when it counts down to zero.  

When Doom shows up as the next spell to cast, i look at the target and ignore if it's still counting.  Doom stays at the front of the "line" as the next best spell to cast until i finally cast it. i'm so used to ignoring it, i'm not getting a good up time on it.

build: v8.2.0-05.03
level: 120 (120)
class: WARLOCK
spec: demonology

talents: bilescourge_bombers
    burning_rush
    demonic_circle
    demonic_consumption
    doom
    soul_conduit
    summon_vilefiend

azerite: azerite_empowered=2
    baleful_invocation=1
    blightborne_infusion=1
    elemental_whirl=1
    explosive_potential=2
    longstrider=3
    overwhelming_power=2
    supreme_commander=1

essences: [memory_of_lucid_dreams]=3, none

sets/legendaries/artifacts: none

gear:     7th_legionnaires_robes=1
    acolytes_shirt=1
    bloodbough_cowl=1
    cord_of_zandalari_resolve=1
    harbingers_inscrutable_will=1
    heart_of_azeroth=1
    igneous_winterskorn_loop=1
    liaras_spire=1
    seal_of_the_zandalari_empire=1
    shirakess_mantle=1
    shirakess_sandals=1
    shirakess_wristwraps=1
    shiver_venom_relic=1
    silverback_cloak=1
    sirensong_trousers=1
    twisted_sisters_handwraps=1

itemIDs: 157970, 158001, 158075, 159272, 163248, 165513, 165567, 165680, 165765, 167756, 167758, 167867, 168905, 169894, 170089, 6097

**Comment by Hekili** [comment]
Doom still ticks and generates resources if you refresh it in "pandemic" range.

![image](https://user-images.githubusercontent.com/9438134/61584328-f08cd300-ab13-11e9-8925-3d93e3cc9fe6.png)
