### ISSUE TITLE
[REC] Blood DK Not updating when standing in Death's Due as Night Fae

### ISSUE THREAD

**Issue by Tao519** [Hekili/hekili#1800]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Blood DK Nightfae, when you stand in Death's Due the addon doesn't update correctly to give priorities

### How to Reproduce

1. Be Blood DK
2. Be Nightfae
3. Cast and stand in Death's Due

### Snapshot (Link)

https://pastebin.com/nU1FLQ60

### Additional Information

I have found that I can manually fix by changing the Blood Covenant priorities, replacing all of the deaths_due with death_and_decay. It seems the update to 10.0 removed 'Death's Due' as a buff. 

### Contact Information

Tao#7221

**Comment by Hekili** [comment]
This will be fixed in the next release.
