### ISSUE TITLE
Celestial Alignment still being recommended after use/on CD with the Syzygy Talent 

### ISSUE THREAD

**Issue by RumbleDumble** [Hekili/hekili#1801]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Celestial Alignment is still being recommended with Syzygy Talent, despite it being on CD/already used

### How to Reproduce

1.) Login to Balance Druid
2.) Use this talent setup: BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQSiIQChkEkIgWCJJRKJhQgUkWIE0AI

3.) Do default primary hekili rotation 

### Snapshot (Link)

https://pastebin.com/AEQx5qnH

### Additional Information

I'm unsure if others are still having this problem, I'm not sure what keeps messing with it 

### Contact Information

BigOlTiddyMuncher#8336

**Comment by Hekili** [comment]
You do not need to resubmit tickets we've already discussed.
