### ISSUE TITLE
[REC] REPLACE THIS TEXT WITH YOUR CLASS/SPEC AND BRIEF ISSUE DETAILS

### ISSUE THREAD

**Issue by soze2k** [Hekili/hekili#1802]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Feral Durid. I exepct the addon will recommond "Rip" on Single Target battle. 
Currently I find that when Feral Durid's talent is AOE, single target combat Addon will not recommend Rip. 
I really love Hekilli btw! hope you can fix it ~

### How to Reproduce

1. Enter game as Feral Durid
2. Import a AOE talent (BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIRSJNIJJRSRDQkkkAAAAAAgiAIJAIikQQCSolAAAAAAAIB)
3. Start ST battle
4. Hekili Never recommond Rip both AOE and ST battle.

### Snapshot (Link)

https://pastebin.com/Vnq7gWdk

### Contact Information

dlii0032@student.monash.edu

**Comment by Hekili** [comment]
These are the correct recommendations for the sim profile with the talents you selected. If the sim profile is changed, I'll update.
