### ISSUE TITLE
Fury Warrior - Whirlwind

### ISSUE THREAD

**Issue by Dorfess** [Hekili/hekili#1803]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Fury Warrior specced into Raging Blow when using a single target build, AKA no whirlwind cleave talents selected and I am in agro with more than 2 enemies hekili only shows whirlwind over and over instead of my single target rotation. My hekili display mode is auto as I dont like having 2 hekili rotations shown at once. Even without the cleave talents my rotation should just switch/stay  to the single target rotation even against more enemies.

### How to Reproduce

1.Join game as fury warrior
2. Problem only seems to manifest whenever you dont have improved whirlwind and Meat Clever active no other talents seem to effect this.
3.auto/aoe mode only show whirlwinds when you dont have those 2 talents selected and enter a fight with multiple enemies.
4.

### Snapshot (Link)

https://pastebin.com/cbfAiLr2

### Additional Information

I would just like to write the single target rotation looks good when attacking more enemies the problem only lies with the hekili "auto" mode where it automatically switches to aoe when attacking more than 1 thing and not having the cleave talents selected so it only shows whirlwind even tho the better rotation would be the single target rotation. So all im saying is it might work exactly how its intended but just me not wanting to have muliple hekili rotions on at once which was why I used auto in the first place.

### Contact Information

Dorfess#7215

**Comment by Wyste** [comment]
looks like Line 19 in the Hekili default action list in the APL needs tweaked.

original:
`spell_targets.whirlwind > 1 & ! buff.meat_cleaver.up | raid_event.adds.in < 2 & ! buff.meat_cleaver.up`
new:
`spell_targets.whirlwind > 1 & (talent.improved_whirlwind.enabled & ! buff.meat_cleaver.up) 
| raid_event.adds.in < 2 & (talent.improved_whirlwind.enabled & !buff.meat_cleaver.up)`

Even if a talent build took Storm of Swords without taking Improved Whirlwind, that still wouldn't make WW more valuable then anything before it. In all cases (that I can see), the recommendation to WW lies solely on the improved whirlwind talent being used to cleave the single_target action list. The above change ensures WW isn't constantly recommended.

new SIMC syntax below:
```
actions.precombat+=/recklessness,if=!runeforge.signet_of_tormented_kings.equipped
actions.precombat+=/fleshcraft

actions=pummel
actions+=/charge,if=time<=0.5|movement.distance>5
actions+=/heroic_leap,if=(raid_event.movement.distance>25&raid_event.movement.in>45)
actions+=/potion
actions+=/pummel,if=target.debuff.casting.react
actions+=/ravager,if=cooldown.avatar.remains<3
actions+=/use_item,name=gavel_of_the_first_arbiter
actions+=/blood_fury
actions+=/berserking,if=buff.recklessness.up
actions+=/lights_judgment,if=buff.recklessness.down
actions+=/fireblood
actions+=/ancestral_call
actions+=/bag_of_tricks,if=buff.recklessness.down&buff.enrage.up
actions+=/avatar,if=talent.titans_torment&buff.enrage.up&(buff.elysian_might.up|!covenant.kyrian)
actions+=/avatar,if=!talent.titans_torment&(buff.recklessness.up|target.time_to_die<20)
actions+=/recklessness,if=talent.annihilator&cooldown.avatar.remains<1|cooldown.avatar.remains>40|!talent.avatar|target.time_to_die<20
actions+=/recklessness,if=!talent.annihilator
actions+=/spear_of_bastion,if=buff.enrage.up&(buff.recklessness.up|buff.avatar.up|target.time_to_die<20)
actions+=/whirlwind,if=spell_targets.whirlwind > 1 & (talent.improved_whirlwind.enabled & ! buff.meat_cleaver.up) 
| raid_event.adds.in < 2 & (talent.improved_whirlwind.enabled & !buff.meat_cleaver.up)
actions+=/call_action_list,name=single_target

actions.single_target=rampage,if=buff.recklessness.up|buff.enrage.remains<gcd|(rage>110&talent.overwhelming_rage)|(rage>80&!talent.overwhelming_rage)|buff.frenzy.remains<1.5
actions.single_target+=/execute
actions.single_target+=/condemn
actions.single_target+=/bloodthirst,if=buff.enrage.down|(talent.annihilator&!buff.recklessness.up)
actions.single_target+=/thunderous_roar,if=buff.enrage.up&(spell_targets.whirlwind>1|raid_event.adds.in>15)
actions.single_target+=/odyns_fury,if=buff.enrage.up&(spell_targets.whirlwind>1|raid_event.adds.in>15)
actions.single_target+=/onslaught,if=!talent.annihilator&buff.enrage.up|talent.tenderize
actions.single_target+=/raging_blow,if=charges>1
actions.single_target+=/crushing_blow,if=charges>1
actions.single_target+=/bloodbath,if=buff.enrage.down|talent.annihilator
actions.single_target+=/bloodthirst,if=talent.annihilator
actions.single_target+=/rampage
actions.single_target+=/slam,if=talent.annihilator
actions.single_target+=/bloodthirst,if=!talent.annihilator
actions.single_target+=/bloodbath
actions.single_target+=/raging_blow
actions.single_target+=/crushing_blow
actions.single_target+=/whirlwind
actions.single_target+=/wrecking_throw
```

Proof change works:
aoe build: BgEAtml4yL3PsSlRlqnvTeVx4HAAAAAAAAAAAhkABQEEiEcANiEigEESgEJJBikkkEgkgDIJBAAAA
![image](https://user-images.githubusercontent.com/5103286/198865990-c8a0def6-7a52-4cf0-96b4-1edcc2ec5d5c.png)
rb build: BgEAtml4yL3PsSlRlqnvTeVx4HAAAAAAAAAAAhkABQEEiEcANiEigEESCRkkEIkkkEpFBQkEAAAA
![image](https://user-images.githubusercontent.com/5103286/198866083-592e6e18-6d11-4f2a-81e3-14df948fd966.png)

**Comment by Hekili** [comment]
Thanks, will be posted in next release.
