### ISSUE TITLE
[REC] Beast Mastery Hunter not recommend  Bestial Wrath

### ISSUE THREAD

**Issue by CooremanM** [Hekili/hekili#1804]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In the previous version it recommended that skill and it worked perfectly with respect to DPS, now it is not recommending it and the DPS drops.

### How to Reproduce

Only proube the class

### Snapshot (Link)

Beast Mastery; Primary - Llamar a mascota 1(0.00), Disparo lacerante(1.35), Matar(2.70)

### Raidbots Sim Report (Link)

.

### Contact Information

ThePrisoner#8624

**Comment by Paua-Hua** [comment]
Cooldowns enabled or disabled? take it off CD usage nd it will fall into rotation.

**Comment by Hekili** [comment]
Please submit a proper and complete snapshot.
