### ISSUE TITLE
"Addon action blocked" taint issue

### ISSUE THREAD

**Issue by fbrown663** [Hekili/hekili#1806]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon action blocked for my Wind Walker Monk

### How to Reproduce

1. Enter game as Wind Walker Monk
2. Enter dungeon
3. Addon action blocked

### Player Information (Link)

https://pastebin.com/MZf6rxkz

### Error Messages (Link)

https://pastebin.com/q7rjuTMh

### Additional Information

N/A

### Contact Information

fbrown663@yahoo.com

**Comment by Hekili** [comment]
If you log in with *only* this addon loaded, do you get the same issues?  I ask because this is a "taint" issue where an addon somewhere has touched secure code, which this addon doesn't actually do.  Once there's taint, the UI will blame just about any code.

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
