### ISSUE TITLE
[REC/BUG] Havoc Demonhunter - Some minor mistakes in configuration(Deathsweep/Bladedance/Throw Glaive)

### ISSUE THREAD

**Issue by goldur** [Hekili/hekili#1807]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In the Code there are some minor issues with recommendations.
Death Sweep and Blade Dance are being recommended without enough Fury with talent First Blood.
Throw Glaive is never recommended.

This is because the spells are not configured correctly in the lua file.
In the Paste-Bin is NO Link to Snapshot but rather the edited code for the DemonHunterHavoc.lua
Hope this helps.

TY

### How to Reproduce

1. Enter Game as Havoc Demon Hunter
2. Select Talents from Standard AOE M+ Build(from wowhead or icy-veins) with Fel Bombardment legendary
3. Try it out on Multiple target dummies

### Snapshot (Link)

https://pastebin.com/mBTH9dKt

**Comment by Hekili** [comment]
Thanks, these will be resolved in the next release.
