### ISSUE TITLE
[REC] Feral: Shred for 3+ targets and Swipe for single target recommended despite no Bloodtalon talent active.

### ISSUE THREAD

**Issue by Testthewest123** [Hekili/hekili#1808]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello
Previous ticket:  #1774

Despite having Bloodtalon talent not activated, both Swipe (single target) and Shred (3+ targets) appear in the recommendation when inappropriate. This happens both in M+ and on dummies. The latest version was installed.

(and thanks for the great work) 

### How to Reproduce

1) Feral with talents: BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIEt0gkkESRJgEJJJAAAAAAoIASSAgIJEkgEKJAAAAAAASA
2) Choose "auto" for the talent recommendation to enable automatic swapping between single target and multi target recommendation. 
3) Go to training dummies: single dummy for single target, swarm trainign dummy (3 dummies) for multi target
4a) Attack a single target: Swipe will appear in the recommendation 
4b) Attack 3+ targets: Shred will appear in the recommendation.

Snapshot: multi target with shred: https://pastebin.com/R3SdQRXt
Snapshot: single target with swipe: https://pastebin.com/zCQy32A0

### Snapshot (Link)

https://pastebin.com/R3SdQRXt

### Raidbots Sim Report (Link)

-

### Additional Information

Snapshot: multi target with shred: https://pastebin.com/R3SdQRXt
Snapshot: single target with swipe: https://pastebin.com/zCQy32A0

**Comment by Hekili** [comment]
Thanks; I will add a check for the Bloodtalons talent before testing the bloodtalons list.

**Comment by Hekili** [comment]
Fix will be posted in a little bit.
