### ISSUE TITLE
[Wrath] Mage not yet supported

### ISSUE THREAD

**Issue by darkkain92** [Hekili/hekili#1809]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I cant make teh addon showing any spell.. idk why i cant figured out
build: v3.4.0-1.0.0-beta9
level: 80 (80)
class: MAGE
spec: mage

talents: none

pvptalents: none

covenant: none

conduits: none

soulbinds: none

sets: none

gear: band_der_bsen_hexe = 1
    das_siegel_des_reiters = 1
    dornige_rosenbrosche = 1
    fleischwerkfesseln = 1
    gugel_von_tirisfal = 1
    heldenhafte_frostfeuergamaschen = 1
    kreis_der_arkanen_strme = 1
    leiahs_fupolster = 1
    luntenanznder_des_kanoniers = 1
    mainhand = 1
    mainhand_2h = 1
    mantelung_von_tirisfal = 1
    plschschrpe_von_guzbah = 1
    schwarztuchhandschuhe = 1
    schwarztuchrobe = 1
    stab_der_missratenen_grundstze = 1
    unterwerfungsumhang_des_tdlichen_gladiators = 1
    wappenrock_der_kirin_tor = 1
    zauberstab_von_ahnkahet = 1

legendaries: none

itemIDs: 30206, 30210, 37384, 37619, 38739, 39493, 40427, 40696, 42063, 42101, 42111, 43157, 43836, 43839, 44013, 49123, 49124

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = false
    enhancedRecheck = false
    gcd = 1459
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    petbased = false
    potion = prolonged_power
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false

toggles:     cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    amplify_magic     = T   [02]
    arcane_blast      = 1   [01]
    arcane_brilliance = F6  [06]
    arcane_explosion  = R   [01]
    arcane_intellect  = F8  [06]
    arcane_missiles   = 2   [01]
    blink             = E   [01]
    blizzard          = M3  [01]
    cone_of_cold      = M5  [01]
    conjure_food      = 2   [07], 2   [10]
    conjure_mana_gem  = T   [07], T   [10]
    conjure_water     = 1   [07], 1   [10]
    counterspell      = 8   [01]
    frost_nova        = M4  [01]
    frostbolt         = 3   [01]
    ice_armor         = ´  [01]
    ice_block         = T   [01]
    ice_lance         = 4   [01]
    slow_fall         = ´  [02]

### How to Reproduce

1

### Player Information (Link)

1

### Error Messages (Link)

no errors

**Comment by Hekili** [comment]
Mage is not yet supported.

**Comment by darkkain92** [comment]
oh ok

**Comment by Damianff7** [comment]
Will be anytime soon? 
and thanks for your great work! :)

**Comment by ryancole** [comment]
Still not supported? Nothing is showing up when I try to load this on my mage in Wrath Classic.

**Comment by Hekili** [comment]
Correct.

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
