### ISSUE TITLE
Blood Deathknight dps Essence on cd

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#181]
Hello i would like that the crucible of flame rank 2 or 3 is showed/used on cd 30 sec cd the major one as blood dk.
now it is only used/shown directly after dancing rune weapon and then it wont show untill dancing rune weapon is back after 2 min^^ Thanks in advance great/the best addon! 

build: v8.2.0-05.03
level: 120 (120)
class: DEATHKNIGHT
spec: blood

talents: bloodworms
    bonestorm
    grip_of_the_dead
    heartbreaker
    hemostasis
    ossuary
    will_of_the_necropolis

azerite: azerite_empowered=2
    cankerous_wounds=1
    festermight=2
    gutripper=2
    harrowing_decay=1
    magus_of_the_dead=2
    resounding_protection=1
    self_reliance=2
    unstable_flames=1

essences: [the_crucible_of_flame]=2, aegis_of_the_deep=2

sets/legendaries/artifacts: cyclotronic_blast=1
    pocketsized_computation_device=1

gear:     akanas_reefstrider_boots=1
    automatic_waist_tightener=1
    breastplate_of_rezans_bladeguard=1
    cyclotronic_blast=1
    heart_of_azeroth=1
    notorious_aspirants_greatcloak=1
    notorious_aspirants_plate_legguards=1
    notorious_gladiators_band=1
    palace_sentinel_vambraces=1
    phial_of_the_arcane_tempest=1
    pocketsized_computation_device=1
    reinforced_digit_diode=1
    skyscorcher_pauldrons=1
    tentacle_crusher=1
    thunder_bluff_tabard=1
    undercove_crushers=1
    warhelm_of_dread_waters=1

itemIDs: 157926, 158075, 159415, 167375, 167485, 167530, 167555, 167672, 168360, 168387, 168885, 168897, 168976, 169009, 169313, 170143, 45584

**Comment by Hekili** [comment]
Yeah, that is pretty restrictive by default.  I'll allow the generic essences/trinkets to be used regardless of Dancing Rune Weapon CD.

**Comment by Tobbelainen** [comment]
ok so that essence cant be used evry 30 sec then it must wait untill dancing is back? =)

**Comment by Hekili** [comment]
Well, that's what you reported, so yes.  It's because Essences are handled like trinkets when they don't have other specified conditions.

The "Use Items" action in the Blood priority checks DRW's CD.  Or it did.  I'm changing it now.

**Comment by Tobbelainen** [comment]
ok thanks for the help as always=)

**Comment by Hekili** [comment]
Changed as of 8.2.0-06-alpha4.
