### ISSUE TITLE
Spellflash throws errors when turning the brightness past 100

### ISSUE THREAD

**Issue by lkj61** [Hekili/hekili#1810]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I set the brightness to anything above 100, it throws errors.  

### How to Reproduce

Open Hekili
Set brightness on Spellflash over 100.
errors start.
Turn it back to 100, and all is good.

### Player Information (Link)

https://pastebin.com/rs9F7Gi3

### Error Messages (Link)

https://pastebin.com/p3jVS1ge

### Contact Information

KayKay#0694

**Comment by Hekili** [comment]
Thank you.  This will be fixed in the next release.

**Comment by lkj61** [comment]
Thank you for such a great addon!  I know you've put a lot of work into this, and it is truly appreciated.
