### ISSUE TITLE
Monk Reverse Harm still an option under WW > Core

### ISSUE THREAD

**Issue by akaRaven** [Hekili/hekili#1814]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Under the Core options for WW it still lists Reverse Harm as being an option. I am new to Monk, but it seems Reverse Harm is no longer an option for DF.

### How to Reproduce

Check under Core options for WW, Optimize Reverse Harm is still an option.

### Snapshot

```Text
No snapshot needed.
```

### Contact Information

Discord AkaDruid#6980

**Comment by Hekili** [comment]
Thanks.  I'll remove it; the setting doesn't harm anything but could cause confusion.

**Comment by Hekili** [comment]
This will be in the next release.
