### ISSUE TITLE
Please add Clicked support

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1816]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

This addon is a very good substitute for panels and addons such as Bartender Dominos, etc. Because it doesn't require moving abilities on the spell panel. Please add it so that the addon can see which Keybinds we bind through it. Thanks. https://www.curseforge.com/wow/addons/clicked

**Comment by Hekili** [comment]
Seems pretty reasonable, but will come after all spec support is restored.

**Comment by Dragonfo** [comment]
Hello. don 't you have time to add addon support yet ?

**Comment by JourneyOver** [comment]
Checking in on this as it would be pretty nice to have!

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.

**Comment by JourneyOver** [comment]
I mean I'd still love to see this added.

**Comment by paperc07** [comment]
Yeah I would also love if I could click the spells its suggesting for my rotation. Is that possible?

**Comment by Hekili** [comment]
> Yeah I would also love if I could click the spells its suggesting for my rotation. Is that possible?

No
