### ISSUE TITLE
[REC] [Dragonflight] Windwalker Monk - On-Use Trinkets not being recommended.

### ISSUE THREAD

**Issue by mackdoherty** [Hekili/hekili#1817]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

On use trinkets not being recommended at all for WW Monk.

### How to Reproduce

Equip on-use trinkets, notice that they're never recommended.

### Talent Loadout

B0QAdeydY63Y4XKaboK13uRRQAAAAAAAAESkkElISSAAAAAJJkAASSgDkSkISIRkkEaJAAAA

### Snapshot

```Text
https://pastebin.com/e1nhkFbp

Got an error about the comment size being too large, so the snapshot is at the pastebin URL above.
```

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rV7vPxavR4C1J2CuQPRzeW

**Comment by Hekili** [comment]
Update to the latest release and report back (with a new snapshot) if you still have this issue.

**Comment by mackdoherty** [comment]
Updated to 10.0.0-05.3 issue is still persisting.

Snapshot
https://pastebin.com/wWSnDYF3

Raidbots Profile:
https://www.raidbots.com/simbot/report/daGBZ22dSgSaxdPCv82mpg
