### ISSUE TITLE
10.0.0-05 - Havoc DH not recommending Throw Glaive in AoE build

### ISSUE THREAD

**Issue by Ohm1989** [Hekili/hekili#1819]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Using a AoE/M+ oriented build with many talents increasing the potency of Throw Glaive and turning it into a major ability in the rotation, Hekili does not recommend Throw Glaive at all.

### How to Reproduce

1. Enter game as a Havoc DH
2. Take the talents Master of the Glaive, Bouncing Glaives, Soulrend, Accelerating Blade, Burning Wound, and Furious Throws (these all augment Throw Glaive into a major ability instead of filler)
3. OPTIONALLY (since these will be gone in DF), also take the Serrated Glaive conduit and Fel Bombardment legendary
4. Execute recommended rotation as normal
5. Throw Glaive will not be recommended

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPThkkkkICSLJJRCQAAAAAAA0SSApQSIIJpFBSAA

### Snapshot

```Text
https://pastebin.com/qEyS9v2x
```

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jRCkk6F4hL79wPh3EY44TQ

### Additional Information

NOTE: Error trying to submit this ticket with the string of the snapshot, says that the body is too long (maximum is 65536 characters), I usually post a Pastebin link with this string, so I will do that again or I will be unable to post. 

For Sim: I chose Hectic Add Cleave because this is an AoE/M+ focused build. Throw Glaive is used 48 times and becomes the 2nd most damaging ability, even outperforming Sinful Brand

**Comment by Hekili** [comment]
This should be resolved in 05.1.
