### ISSUE TITLE
Ele Shaman. Frost Shock Keybind the Same As Icefury. 

### ISSUE THREAD

**Issue by DannyA3434** [Hekili/hekili#1823]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello friend, love the addon. Your my hero. 

Just giving some general feedback to help in case this issue apples to opther classes/specs.

 As an Ele Shaman, I have Icefury keybound to 9. Front Shock keybound to5. 

When Icefury is used pressing 9, all good. But then in my Queue of spells, Frost Shock also dsiplays as keyyind 9, instead of 5. 

Screenshot to better show the example: https://gyazo.com/6b80ca9555cd478c043e126f1e050134

### How to Reproduce

 As an Ele Shaman, I have Icefury keybound to 9. Front Shock keybound to5. 

When Icefury is used pressing 9, all good. But then in my Queue of spells, Frost Shock also dsiplays as keyyind 9, instead of 5. 

Screenshot to better show the example: https://gyazo.com/6b80ca9555cd478c043e126f1e050134

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAAoUSSLJBSLRDBFkIBAAAAAAlAkSSUSRShIik0AQAE

### Snapshot

```Text
https://gyazo.com/6b80ca9555cd478c043e126f1e050134
```

### Additional Information

Thank you sir for all that you do. I do software testing by occupation. If you ever need any troubleshooting help I'd be happy to lend a hand.

**Comment by DannyA3434** [comment]
Whoops. Looks like after a few minutes of testing roations, the issue corrected itself. Apologies for the incvonenience.

**Comment by Hekili** [comment]
Thanks for updating.
