### ISSUE TITLE
Feral Fails To Reccommend Anything After Using Cooldowns

### ISSUE THREAD

**Issue by tance77** [Hekili/hekili#1824]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The addon breaks and does not reccomend anything after opener or random times during combat. It feels like it happens when Bloodlust is cast during combat.

### How to Reproduce

1. Fly To Ardenweald
2. Go To The Training Dummies, fight the Dungeoneer's Training Dummy
3. Open Prowl, Rake, Spectral Agility Potion, Kihra's Adrenaline Injector, Beserk, Shred
4. Addon breaks and doesn't reccomened anything else until a combo spender  is spent. Bite, Primal Wrath, Rip or other.
![image](https://user-images.githubusercontent.com/3421501/198904381-97f46d30-82db-43b0-a764-369bd7410cc4.png)
![image](https://user-images.githubusercontent.com/3421501/198904385-39f17f7f-6c57-4ffd-b651-c796d540f61b.png)

### Player Information (Link)

[Information Link](https://pastebin.com/L7AieMWb)

### Error Messages (Link)

No LUA error, but inline chat error.
```Text
Unable to make reccomendation for Primary #2; triggering auto-snapshot...
Snapshots saved: Cooldowns, Primary.
```

### Snapshots

[Feral Cooldowns Snapshot](https://pastebin.com/rUAjkGWb)
[Feral Primary Snapshot](https://pastebin.com/NEW1n6WJ)

**Comment by tance77** [comment]
It seems to happen after a 5 combo point rip very often.

**Comment by Hekili** [comment]
You're on the right track.  It was when Rip was up and your combo points are maxed out; the Ferocious Bite conditions were wrong.  Fixing now.
