### ISSUE TITLE
Bars are not showing

### ISSUE THREAD

**Issue by Melinamun** [Hekili/hekili#1825]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I bar for Hekili is not showing up under a couple of my toons. There are a warlock and a mage. It is working fine for my hunter. I am not sure what is causing the glitch

### How to Reproduce

1. Just entered the game under my Warlock

### Player Information (Link)

```Text
build: v10.0.0-05
level: 60 (60)
class: WARLOCK
spec: demonology

talents: none

pvptalents: none

covenant: night_fae

conduits: shade_of_terror = 1
   soul_eater = 1

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   run_without_tiring = 1

sets: heart_essence = 1

gear: ascendent_valor_signet = 1
    avowed_arcanists_staff = 1
    black_swashbucklers_shirt = 1
    bloodsilk_cord = 1
    bootacharge_flyers = 1
    choral_vestments = 1
    cowl_of_emberfury = 1
    heart_essence = 1
    heart_of_azeroth = 1
    ilkas_hunting_cloak = 1
    mitts_of_pained_absolution = 1
    newcomers_gladiatorial_badge = 1
    recruits_distinction = 1
    shadowlace_cuffs = 1
    shadowlace_trousers = 1
    shrouded_cloth_spaulders = 1
    sprigthistle_loop = 1

legendaries: none

itemIDs: 134690, 158075, 173199, 173219, 173222, 175713, 175725, 175766, 177656, 178067, 181178, 181224, 181676, 181721, 188006, 4336

settings: none

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 

warnings: none
```

### Error Messages (Link)

```Text
No error messages
```

### Contact Information

Melinamun#6433

**Comment by Hekili** [comment]
Your specialization is not supported in Dragonflight (yet).  This information is presented to you when you log into the game, and is also shown if you open the addon menu.  All classes/specializations will be supported, but it takes time to implement all the new talents and nuances.  Thank you for being patient.
