### ISSUE TITLE
Exorcism only with Consecration Active?

### ISSUE THREAD

**Issue by Purehotty** [Hekili/hekili#1826]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Possible to make it so Exorcism is only suggested when Consecration is already active?

**Comment by Hekili** [comment]
This is not a feature request, nor does it include any context as to why I would want to do that.
