### ISSUE TITLE
[BUG] Actionbuttons continue flashing (with SpellFlash) alfter combat ends and "displays" hide.

### ISSUE THREAD

**Issue by Tga123** [Hekili/hekili#1829]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Actionbuttons continue flashing (with SpellFlash) alfter combat ends and "displays" hide.

### How to Reproduce

1. Turn on SpellFlash glowing.
2. Start combat (or just target enemy).
3. End combat (or clear target).

### Player Information (Link)

```Text
It in ALL characters.
```

### Error Messages (Link)

```Text
No error messages, it just happening.
```

### Additional Information

Also SpellFlashCore has new API, it can made using it slightly easy (instead hooking SFC's funcs and frame scripts).

**Comment by bason1c** [comment]
This is simply telling you the first spell in rotation.  ime it wont go away unless you turn off spell flash.  could be wrong though.

**Comment by Hekili** [comment]
This is not a bug.

**Comment by Tga123** [comment]
Nah nah, it about another case.
I know Hekili flashed first spell in rotation, when combat started or just targeting harm unit.
It is good feature.
But now Hekili continued flashing after combat ends and/or clearing target.
E.G. 
I target dummy, first spell in rotation start flashing, 
	i cast few spells (combat start), it flashing another spells by rotation (all going right), 
	i stop casting, clearing target, move away from dummy (combat ends), 
	Hekili displays canceling recommends spells and hide (Hekili continue flashing last recommended spells),
	i teleport to another location and just stay still (not in combat, without target, without enemy around),
	and Hekili still flashing last recommended spells (no matter how much time elapsed).
Flashes continues until i start targeted another harm unit or start combat again, 
	in that case Hekili start new recommendation sequence.
Previously Hekili stopped flashing when recommendation ends, but few month ago strange behavior began,
	it continued flashing last recommended spells.
