### ISSUE TITLE
Ret Paladin - incorrect order recommended 

### ISSUE THREAD

**Issue by PettyPeterPettigrew** [Hekili/hekili#1832]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello

Ret is super close to perfect there are just two issues

1) We have a talent called Exorcism now (which will be the go to talent in dungeons). The talent spreads exorcism to all enemies in our consecration meaning correct order to cast would be Consecration > Exorcism, but the addon is recommending the opposite therefore exorcism is not spreading to additional enemies.

### How to Reproduce

1. Play Ret
2. Chose Exorcism
3. Gather enemies and click Exorcism then Consecration (addon recommended)
4. See that additional enemies don't have the Exorcism DOT

### Talent Loadout

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAAEAiSaJJSOAAppkwBalAAAAAAAIEJJplEkQBAloEA

### Snapshot

```Text
fg
```

**Comment by Hekili** [comment]
Snapshots are required for recommendations tickets.

**Comment by PettyPeterPettigrew** [comment]
Retribution; Primary - Exorcism(0.00), Consecration(1.38), Crusader Strike(2.76)

**Comment by royalplisk1** [comment]
I just did a +15 as Ret and final reckoning and divine toll were not recommended at all.

build: v10.0.0-05
level: 60 (60)
class: PALADIN
spec: retribution

talents: art_of_war
    ashes_to_ashes = 2/2
    ashes_to_dust = 1/1
    aspiration_of_divinity = 2/2
    auras_of_swift_vengeance = 1/1
    avenging_wrath = 1/1
    blade_of_justice = 1/1
    blade_of_wrath = 1/1
    blessing_of_freedom = 1/1
    blessing_of_sacrifice = 1/1
    blinding_light = 1/1
    cavalier = 1/1
    cleanse_toxins = 1/1
    consecrated_blade = 1/1
    crusade = 1/1
    divine_purpose = 1/1
    divine_steed = 1/1
    divine_storm = 1/1
    empyrean_power = 1/1
    exorcism = 1/1
    final_reckoning = 1/1
    fist_of_justice = 2/2
    greater_judgment = 1/1
    hallowed_ground = 1/1
    hammer_of_wrath = 1/1
    healing_hands = 1/1
    highlords_judgment = 1/2
    holy_aegis = 2/2
    holy_blade = 1/1
    holy_crusader = 1/1
    improved_crusader_strike = 1/1
    incandescence = 1/1
    lay_on_hands = 1/1
    of_dusk_and_dawn = 1/1
    rebuke = 1/1
    recompense = 1/1
    sanctification = 1/1
    sanctify = 1/1
    seal_of_order = 1/1
    seal_of_reprisal = 2/2
    seasoned_warhorse = 1/1
    shield_of_vengeance = 1/1
    tempest_of_the_lightbringer = 1/1
    unbreakable_spirit = 1/1
    virtuous_command = 2/2
    wake_of_ashes = 1/1
    zeal = 1/1

pvptalents: none

covenant: kyrian

conduits: condensed_anima_sphere = 13
   divine_call = 13
   lights_barding = 13
   ringing_clarity = 13
   shielding_words = 13
   truths_wake = 13

soulbinds: [forgelite_prime_mikanikos]
   brons_call_to_action = 1
   effusive_anima_accelerator = 1
   forgelite_filter = 1
   hammer_of_genesis = 1
   resilient_plumage = 1
   soulglow_spectrometer = 1

sets: enforcers_stun_grenade = 1
    ring_of_collapsing_futures = 1
    soleahs_secret_technique = 1

gear: enforcers_stun_grenade = 1
    luminous_chevaliers_casque = 1
    luminous_chevaliers_epaulettes = 1
    luminous_chevaliers_gauntlets = 1
    luminous_chevaliers_plackart = 1
    mountebanks_colorful_cloak = 1
    ornately_engraved_amplifier = 1
    overseers_final_word = 1
    pyroclastic_greatboots = 1
    ring_of_collapsing_futures = 1
    shadowghast_greaves = 1
    shadowghast_waistguard = 1
    signet_of_collapsing_stars = 1
    soleahs_secret_technique = 1
    vambraces_of_verification = 1

legendaries: divine_resonance = 1
    tempest_of_the_lightbringer = 1

itemIDs: 110017, 110051, 142173, 168972, 169064, 171416, 171418, 185813, 185815, 185842, 188928, 188929, 188932, 188933, 190958

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Retribution
    petbased = false
    potion = spectral_strength
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    arcane_torrent         = CS2 [06]
    blade_of_justice       = 3   [01]
    blessing_of_freedom    = SX  [06], 4   [10]
    blessing_of_protection = Z   [05], C1  [09], 5   [10]
    blessing_of_sacrifice  = C1  [02], R   [10]
    blinding_light         = C3  [05]
    cleanse_toxins         = 3   [02], C   [05]
    consecration           = 5   [01]
    crusade                = R   [02], S3  [06], 2   [09]
    crusader_strike        = 1   [01]
    divine_shield          = Q   [01], 1   [10]
    divine_steed           = X   [01], F   [10]
    divine_storm           = S2  [06]
    divine_toll            = S4  [06], X   [09]
    exorcism               = SF  [06]
    final_reckoning        = SE  [06], 4   [09]
    flash_of_light         = S1  [06]
    gladiators_medallion   = SR  [06]
    hammer_of_justice      = C1  [01], 3   [09]
    hammer_of_wrath        = E   [01]
    hand_of_hindrance      = 4   [02], M3  [05]
    hand_of_reckoning      = SM3 [05], Q   [10]
    healthstone            = C5  [05]
    intercession           = S5  [06]
    judgment               = 2   [01]
    lay_on_hands           = SZ  [05], R   [09], 3   [10]
    potion                 = F   [02]
    rebuke                 = C2  [01], Q   [09]
    shield_of_vengeance    = SQ  [06], 2   [10]
    templars_verdict       = 4   [01]
    wake_of_ashes          = R   [01], C2  [09]
    word_of_glory          = F   [01]

warnings: none

**Comment by royalplisk1** [comment]
Actually, I think when I casted Final (without recommendation) it did recommend Divine Toll right after.

**Comment by crashedorange** [comment]
Hi, I don't have anything to contribute in coding, buuuuuuut I have discovered something that *should* work until the expansion is fully released...... do not have divine toll in the talent tree as that seems to be clashing with as that seems to be what is causing the duplicate suggetion in the addon.

**Comment by Hekili** [comment]
@royalplisk1 That still is not a snapshot, but you don't have your cooldowns toggle enabled.
> toggles: cooldowns = false

@crashedorange I do not understand what you're saying, but if you are seeing incorrect recommendations, provide a snapshot and clear, specific details.

**Comment by royalplisk1** [comment]
Per the previous poster - thanks cooldowns somehow turned off. Fixed that. Figured out what a snapshot is below - I believe that Final Reckoning should be within the first 8 spells for sure (and it just isn't coming up for me and neither is Divine Toll until I click Final Reckoning). I wonder if it has something to do with it being a target ground ability that I have macro'd to a cast on self - that being said it has come up in the past. Appreciate the support and this addon.

Retribution; Primary - Blade of Justice(0.00), Judgment(1.15), Crusader Strike(2.30), Crusade(2.30), Templar's Verdict(3.45), Hammer of Wrath(4.60), Templar's Verdict(5.75), Wake of Ashes(6.90)

**Comment by Purehotty** [comment]
I believe what the OP is trying to say is that it currently puts Exorcism before Consecration, which should be reversed as with the new talent when Consecration is down and you Exorcism a target inside of it the DOT effect is spread to other enemies also inside the Consecration which is a huge DPS increase on AOE packs. I was wondering the same how it could be possible to make sure Consecration is down before suggesting to Exorcism.

**Comment by Jacii1121** [comment]
[Snapshot ](https://pastebin.com/CPnY3ADw) that hopefully supports the ticket.  Don't think the simc apl supports this however.

**Comment by petewoolley** [comment]
Agreed on the Exorcism point, shouldn't be prioritised ahead of consecrate unless single target.

**Comment by PettyPeterPettigrew** [comment]
> [Snapshot ](https://pastebin.com/CPnY3ADw) that hopefully supports the ticket. Don't think the simc apl supports this however.
Thanks for posting. I've followed the instructions to create my own but its just giving me the thing I posted. Maybe because I'm not on  level 60 dunno

**Comment by PettyPeterPettigrew** [comment]
> I believe what the OP is trying to say is that it currently puts Exorcism before Consecration, which should be reversed as with the new talent when Consecration is down and you Exorcism a target inside of it the DOT effect is spread to other enemies also inside the Consecration which is a huge DPS increase on AOE packs. I was wondering the same how it could be possible to make sure Consecration is down before suggesting to Exorcism.

Yes thanks for repeating exactly what I said lol

**Comment by Hekili** [comment]
> > [Snapshot ](https://pastebin.com/CPnY3ADw) that hopefully supports the ticket. Don't think the simc apl supports this however.
> Thanks for posting. I've followed the instructions to create my own but its just giving me the thing I posted. Maybe because I'm not on  level 60 dunno

You have to CTRL+A in the textbox to select all the text, including the hidden text. Otherwise, you're just copying the first line.

**Comment by Hekili** [comment]
This morning's release will shift Exorcism vs. Consecration based on target counts, sort of.  Sims will eventually shake out how long you'd hold Exorcism for Consecrate without losing DPS.

**Comment by PettyPeterPettigrew** [comment]
> This morning's release will shift Exorcism vs. Consecration based on target counts, sort of. Sims will eventually shake out how long you'd hold Exorcism for Consecrate without losing DPS.

Thanks!

**Comment by petewoolley** [comment]
Noice.
