### ISSUE TITLE
Add option to hide actionbar proc glow when using SpellFlash

### ISSUE THREAD

**Issue by jordancrain** [Hekili/hekili#1833]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

When using SpellFlash to highlight recommended actions, Blizzard's default glow around action buttons related to a proc activating can obscure the SpellFlash indicator for certain indicator colors/sizes.

### Additional Information

The following code sample can be used to disable all action bar glow overlays:

```lua
hooksecurefunc("ActionButton_ShowOverlayGlow",function(self)
   self.overlay:ClearAllPoints()
   self.overlay:SetPoint("TOP", UIParent, "TOP", 0, 9000)
end)
```

However, that's simply a hack that I managed to stumble upon while trying to mitigate this issue, and there's probably a better way to approach it.

**Comment by Hekili** [comment]
The more I think about this one, the more I think this belongs with SpellFlash rather than my addon.
