### ISSUE TITLE
Enhancement - Earth shield missing

### ISSUE THREAD

**Issue by Ashgaion** [Hekili/hekili#1835]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

I'd like it if Hekili shows me to update my earth shield if it's not up on myself as enhancement.
I took the talent so i can use 2 elemental shields. I use a WA for it now, but rather have it in Hekili 
Maybe as a defensive? Or Cooldown?

### Contact Information
Discord : Ashgaion#8352

**Comment by Hekili** [comment]
This will be handled in today's release.
