### ISSUE TITLE
Windwalker its not recomending any trinkets

### ISSUE THREAD

**Issue by onelz232** [Hekili/hekili#1836]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

when i have been in a fight then i havent seen the addon give the recomendation on any of my trinkets once in the intire fight. So i looked in the list but i dont think i can find it in the list

### How to Reproduce

if possible could you add the trinkets on the list. I belive it was in the list before in shadowlands

### Snapshot

https://pastebin.com/Q2c1Sfjc

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rQVUyb8rRLeQggaucsHpuM

### Contact Information

onelz#0610 (discord)

**Comment by mackdoherty** [comment]
Adding on, since my ticket was closed yesterday, issue is still persisting with the latest release.

Updated to 10.0.0-05.3 issue is still persisting.

Snapshot
https://pastebin.com/wWSnDYF3

Raidbots Profile:
https://www.raidbots.com/simbot/report/daGBZ22dSgSaxdPCv82mpg

**Comment by Hekili** [comment]
Thanks.  This was due to a typo in the priority.  It'll be fixed in today's release.
