### ISSUE TITLE
Unholy DK: Deadliest Coil legendary no longer functions

### ISSUE THREAD

**Issue by jordancrain** [Hekili/hekili#1837]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Death Coil is being recommended when not appropriate because the Deadliest Coil legendary is still being used to calculate runic power costs even though Shadowlands legendary effects are no longer active.

### How to Reproduce

1. Be an Unholy Death Knight  
2. Equip a Shadowlands legendary with the Deadliest Coil effect  
3. Notice that Death Coil can recommended in the rotation when at under 30 runic power

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAASCHItIBSiEhEkkEJAAAAAAAAAAkASkkCAApIFRSSikA

### Snapshot

https://pastebin.com/EnwhtV1W

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iNBeJPJngZDJio4bNVuaog/simc

**Comment by Hekili** [comment]
Where were you when you experienced this issue?  In Shadowlands content or elsewhere?

**Comment by jordancrain** [comment]
I was in Stormwind, and the legendary effect was grayed out on the item.  It didn't occur to me to go back to a Shadowlands zone to test.

**Comment by jordancrain** [comment]
I double checked, and the legendary effect becomes active again in Shadowlands zones.  But there's no obvious buff to indicate that.  Not sure if there something behind the scenes that can be queried to determine if the effect is actually active or not.

**Comment by vond82** [comment]
Since pre-patch Shadowlands stuff like that only works inside Shadowlands zones, so just gotta keep track of where you are :)

**Comment by Hekili** [comment]
Next release will disable Shadowlands legendaries outside of Shadowlands content.  Hopefully.  Maybe.
