### ISSUE TITLE
Ironfur not showing for Guardian Druid

### ISSUE THREAD

**Issue by KayZey** [Hekili/hekili#184]
I used to include this into the rotation, but now is showing Barkskin before anything and Ironfur never shows up. (Frenzied does tho)

build: v8.2.0-05.03
level: 120 (120)
class: DRUID
spec: guardian

talents: blood_frenzy
    earthwarden
    feral_affinity
    galactic_guardian
    mighty_bash
    rend_and_tear
    wild_charge

azerite: azerite_empowered=3
    bulwark_of_the_masses=1
    elemental_whirl=1
    jungle_fury=1
    layered_mane=1
    longstrider=2
    on_my_way=1
    unstable_flames=1
    untamed_ferocity=1
    wild_fleshrending=1

essences: [anima_of_life_and_death]=1, none

sets/legendaries/artifacts: pocketsized_computation_device=1

gear:     7th_legionnaires_buckle=1
    band_of_the_ancient_dredger=1
    blightreaper=1
    bracers_of_dreadful_maladies=1
    darkwood_sentinels_grips=1
    fathomstalker_boots=1
    fathomstalker_headcover=1
    fathomstalker_shoulderpads=1
    fathomstalker_wraps=1
    heart_of_azeroth=1
    pocketsized_computation_device=1
    seal_of_questionable_loyalties=1
    silvertrimmed_breeches=1
    snowpelt_mangler=1
    sporecallers_shroud=1

itemIDs: 158075, 158314, 159292, 159297, 159340, 159461, 159662, 160263, 163384, 165442,

**Comment by Hekili** [comment]
Please submit a complete ticket with a snapshot per the instructions.  Thanks!

**Comment by Hekili** [comment]
Please try 8.2.0-06-alpha5 and submit a new ticket if you are having the same issue.
