### ISSUE TITLE
[REC] Unholy DK unable to show recommendation on single target 

### ISSUE THREAD

**Issue by Deathhunt** [Hekili/hekili#1840]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When using Unholy DK, hekili is unable to show recommendation on single target. After showing a few cooldown abilities, it would not give any further recommendation. Meanwhile, it does seem to be working on multi-target while using the same talent build.

### How to Reproduce

1. Enter the game using an Unholy DK.
2. Import the talent build below.
3. Try it on a single target.

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAiQIiUiEhkIRIIJSAAAAAAAAAAAJgkkkCAIRaSDJJ5ASA

### Snapshot

https://pastebin.com/hkmTDm97

**Comment by Hekili** [comment]
This looks like some Festermight logic was blocking, when you don't have the talent.  Next release should have a fix.

**Comment by Deathhunt** [comment]
Test v10.0.0-06.1 and it's fixed, thanks for the great work.
