### ISSUE TITLE
WW Priority Displayed for Brewmaster Monk

### ISSUE THREAD

**Issue by jmtenet211** [Hekili/hekili#1842]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Windwalker Priority is displaying just fine, however there does not appear to be a priority for Brewmaster included in the latest release. Checking under options, it is clearly not there.

While in BM spec, WW abilities and talents are suggested.

### How to Reproduce

1. Enter game as Monk. Select WW specialization.
2. Look at options in Hekili and see the missing specialization.
3. Switch specs to BM. Notice that WW talents are being recommended.

### Talent Loadout

BwQAdeydY63Y4XKaboK13uRRQAAAAAAAQAAAAAFKlkkQIJp1IAAAApFaJRiEJBHIJBCICkWaSA

### Snapshot

Windwalker; Primary - Expel Harm(0.00), Strike of the Windlord(1.00), Rushing Jade Wind(2.00)

### Additional Information

All of the WW priorities seem to work, except the recommendation to use Spinning Crane Kick over Rushing Jade Wind. But that is an entirely different issue.
![WoWScrnShot_110122_190448](https://user-images.githubusercontent.com/113951822/199220767-0e05e9f2-d7bd-494b-9fde-397f99c4440b.jpg)

### Contact Information

DocSkillz#5401

**Comment by Hekili** [comment]
Correct, Brewmaster is not yet implemented so it is not listed yet.

![image](https://user-images.githubusercontent.com/9438134/199231772-543a4f47-b552-4c18-84bd-c798f248f937.png)
