### ISSUE TITLE
Balance druid - Sunfire is still swap recommended even it is already dotted

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1844]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Sunfire is still swap recommended even it is already dotted. OnSreen enemies only is enabled, but probably this setting is not reflected. I see 8 nameplates on enemies but the addon shows 16 (after spelling Starfall). More mobs are behind me but I don't see them on screen. Tested on Venthyr dummies.

### How to Reproduce

1. Balance Venhyr - try rotation with swap enabled on more enemies

### Talent Loadout

BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAkkkIikkAQIJAaBREpIHICJISKJiESBgA

### Snapshot

https://pastebin.com/J23ceSxG

**Comment by marekCs** [comment]
But it works pretty ok in dungeons, so please just review when you have time, it's not a priority.

**Comment by marekCs** [comment]
Happened again in raid on 2 targets [https://pastebin.com/CMDprd10](https://pastebin.com/CMDprd10)

**Comment by Hekili** [comment]
This should be resolved in the next release.
