### ISSUE TITLE
Shadow Priest: Devouring Plague / Mindgames

### ISSUE THREAD

**Issue by MichaelKaiser** [Hekili/hekili#1846]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Two problems with suggested spells:
1. Devouring Plague is suggested although insanity is below 50
2. Mindgames are never suggested, although SW: Pain, Vampiric Touch and Devouring Plague are on target and have a remaining time above 6.3 seconds

### How to Reproduce

1. Enter the game as shadow priest
2. go to dummy and start fight
3. somewhen Devouring Plague is suggested without enough insanity

### Talent Loadout

BIQAu+2Vv7op3uGggQnVDr07wIItAAAAAAAAAAAAAAikoEhU0iEJlESAakEJSkABJSRahkAA

### Snapshot

https://pastebin.com/DeD9Skhx

**Comment by Hekili** [comment]
The first part is due to a bug that'll be fixed when I post a release in a few minutes.

> Mindgames are never suggested, although SW: Pain, Vampiric Touch and Devouring Plague are on target and have a remaining time above 6.3 seconds

You can add a snapshot for this scenario -- the one you provided matches the Devouring Plague part, but your dots aren't applied for Mindgames.

**Comment by MichaelKaiser** [comment]
Sure: https://pastebin.com/euNaER3b

on this stage I would have expected Mindgames as suggestion

**Comment by Hekili** [comment]
This should be fixed in the next release.
