### ISSUE TITLE
Shadowpriest gets stuck and doesnt recommend anything new

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1847]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Rotation gets stuck and doesn't recommend anything new, it freezes

### How to Reproduce

Seems its just anytime i do the rotation at all it gets stuck and freezes.

### Talent Loadout

BIQAu+2Vv7op3uGggQnVDr07wAJ4ABAAAAAAAAAAAAAJSKRINtkkkUgEgGJRSSIBBBFpFSCA

### Snapshot

https://pastebin.com/mSjXFDHv

**Comment by Hekili** [comment]
No new Shadow Priest tickets until after the next release.
