### ISSUE TITLE
BREWMASTER MONK NOT WORKS

### ISSUE THREAD

**Issue by Brew0monk** [Hekili/hekili#1848]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

It does not work for me on the brewmaster monk, it does not appear to me just hekili in the interface and I only select the ww spec in the options

### How to Reproduce

Not works on brewmaster monk spec

### Player Information (Link)

```Text
build: v10.0.0-06
level: 60 (60)
class: MONK
spec: brewmaster

talents: none

pvptalents: none

covenant: kyrian

conduits: condensed_anima_sphere = 13
   dizzying_tumble = 13
   fortifying_ingredients = 13
   scalding_brew = 13
   strike_with_clarity = 13
   walk_with_the_ox = 13

soulbinds: [forgialita_supremo_mikanikos]
   brons_call_to_action = 1
   effusive_anima_accelerator = 1
   forgelite_filter = 1
   regenerating_materials = 1
   soulglow_spectrometer = 1
   soulsteel_clamps = 1

sets: enforcers_stun_grenade = 1

gear: anello_con_sigillo_di_stellasole_ardente = 1
    anello_di_spettrombra = 1
    bracciali_dei_piumarossa = 1
    calzari_del_piede_ballerino_incantati = 1
    chiave_di_pietra_interplanare = 1
    cintura_foderata_di_pelle_ombrosa = 1
    corazza_del_grande_flusso = 1
    corona_del_grande_flusso = 1
    doppiopetto_filigranato_debano = 1
    drappo_della_vergogna = 1
    enforcers_stun_grenade = 1
    gambali_foderati_del_grande_flusso = 1
    granata_a_stordimento_dello_scagnozzo = 1
    matrice_di_difesa_reattiva = 1
    paramani_di_cuoio_galvanizzati = 1
    ricalibratore_cranico = 1
    spalline_frangiate_del_grande_flusso = 1
    xiphos_dellanima_perduta = 1

legendaries: call_to_arms = 1
    stormstouts_last_keg = 1

itemIDs: 109869, 110017, 142170, 169052, 169054, 172320, 175279, 178926, 183030, 183035, 186379, 186433, 188910, 188911, 188912, 188914, 42360

settings: none

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 

warnings: none
```

### Error Messages (Link)

```Text
No error messages
```

### Additional Information

Not works

**Comment by Hekili** [comment]
Your specialization is not supported in Dragonflight (yet).  This information is presented to you when you log into the game, and is also shown if you open the addon menu.  All classes/specializations will be supported, but it takes time to implement all the new talents and nuances.  Thank you for being patient.
