### ISSUE TITLE
Taint error warning

### ISSUE THREAD

**Issue by bmira420** [Hekili/hekili#1849]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

With many different toons on my razer naga, i use the 12 side keys and on a lot of them when i use it tells me hekili cant be used and forces me to close the addon and reload my ui. 

### How to Reproduce

I log on to various toons and it randomly tells me hekili cannot function when useing miouse side buttons and i have to reload ui and disable hekili

### Player Information (Link)

```Text
build: v10.0.0-06
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ancestral_defense
    ancestral_guidance = 1/1
    ashen_catalyst = 1/1
    astral_bulwark = 1/1
    astral_shift = 1/1
    capacitor_totem = 1/1
    chain_lightning = 1/1
    earth_elemental = 1/1
    elemental_blast = 1/1
    elemental_spirits = 1/1
    elemental_warding = 2/2
    elemental_weapons = 2/2
    feral_spirit = 1/1
    fire_and_ice = 1/1
    flurry = 1/1
    frost_shock = 1/1
    hailstorm = 1/1
    healing_stream_totem = 1/1
    hot_hand = 2/2
    ice_strike = 1/1
    improved_lightning_bolt = 2/2
    improved_maelstrom_weapon = 2/2
    lashing_flames = 1/1
    lava_burst = 1/1
    lava_lash = 1/1
    maelstrom_weapon = 1/1
    molten_assault = 2/2
    natures_fury = 2/2
    raging_maelstrom = 1/1
    spirit_walk = 1/1
    storms_wrath = 1/1
    stormstrike = 1/1
    sundering = 1/1
    swirling_currents = 2/2
    swirling_maelstrom = 1/1
    thundershock = 1/1
    thunderstorm = 1/1
    wind_rush_totem = 1/1
    wind_shear = 1/1
    windfury_totem = 1/1
    windfury_weapon = 1/1
    winds_of_alakir = 2/2
    witch_doctors_ancestry = 2/2

pvptalents: none

covenant: venthyr

conduits: astral_protection = 10
   lavish_harvest = 10
   spiritual_resonance = 12
   thunderous_paws = 12
   totemic_surge = 10
   unruly_winds = 12

soulbinds: [theotar_the_mad_duke]
   exquisite_ingredients = 1
   its_always_tea_time = 1
   leisurely_gait = 1
   party_favors = 1
   soothing_shade = 1
   wasteland_propriety = 1

sets: chains_of_domination = 1

gear: boneshatter_pauldrons = 1
    chains_of_domination = 1
    destructioncore_handlers = 1
    dominations_deliverance = 1
    enigmatic_chain = 1
    mantle_of_manifest_sins = 1
    miniature_breaking_wheel = 1
    periapt_of_pristine_preservation = 1
    ragebound_leg_irons = 1
    shadowghast_ring = 1
    talons_of_the_legion_generals = 1
    theurgic_starspeakers_howl = 1
    theurgic_starspeakers_ringmail = 1
    theurgic_starspeakers_runebindings = 1
    theurgic_starspeakers_tassets = 1
    titanic_ocular_gland = 1

legendaries: elemental_conduit = 1
    witch_doctors_wolf_bones = 1

itemIDs: 172327, 178926, 182390, 183033, 186291, 186343, 186375, 186423, 188252, 188922, 188923, 188924, 188925, 189818, 190363, 190617

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    filler_shock = true
    pad_lava_lash = true
    pad_windstrike = true

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    chain_harvest   = 7   [01]
    chain_lightning = 6   [01]
    crash_lightning =
    feral_spirit    = -   [01]
    flame_shock     = 3   [01]
    frost_shock     = 0   [01]
    ghost_wolf      = =   [01]
    lava_lash       = 2   [01]
    lightning_bolt  = 5   [01], 1   [07]
    stormstrike     = 1   [01]
    sundering       = 4   [01]
    thunderstorm    = 9   [01]
    windfury_totem  = 8   [01]
    windstrike      = 1   [01]

warnings: none
```

### Error Messages (Link)

```Text
NO ERRORS I CAN SEE
```

### Additional Information

this happens at random intervals on many classes

### Contact Information

bmira420#6392

**Comment by Hekili** [comment]
> With many different toons on my razer naga, i use the 12 side keys and on a lot of them when i use it tells me hekili cant be used and forces me to close the addon and reload my ui.

I have no idea what this means.  What says this, and where?

> NO ERRORS I CAN SEE

???

**Comment by bmira420** [comment]
There’s no error code that it gives. When I press the #12 button on my
razor naga. Which is ghost wolf form. It tells me to disable hekili and
reload ui. It doesn’t do it all the time but is very random.

**Comment by Hekili** [comment]
Ok, does this occur if you disable all your other addons and have only Hekili loaded?

**Comment by bmira420** [comment]
I am occasionally having issues with details and silver dragon. But I don’t
have a ton on addons maybe 10 at most. Dbm handynotes sliver dragon,
decursive, details, tomtom, and Hekili. If u have a suggestion on which to
disable to minimize the occurrence I’m happy to oblige

**Comment by Hekili** [comment]
I don't. You didn't answer the question I asked, though. 

This is a "taint" issue, and taint issues are notoriously misattributed in WoW. Once some addon touches something secure by mistake, other addons can get blamed. 

If you play with Hekili and no other addons enabled, do you get the same error?

**Comment by bmira420** [comment]
I’ll give it a try

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
