### ISSUE TITLE
Error with alpha 5

### ISSUE THREAD

**Issue by kittykiller** [Hekili/hekili#185]
getting this error only when fighting bosses

Message: Interface\AddOns\Hekili\State.lua:1514: attempt to compare number with string
Time: Mon Jul 22 15:44:38 2019
Count: 8823
Stack: Interface\AddOns\Hekili\State.lua:1514: attempt to compare number with string
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:583: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:543>
[C]: ?
Interface\AddOns\Hekili\State.lua:1514: in function <Interface\AddOns\Hekili\State.lua:1474>
Interface\AddOns\Hekili\State.lua:1543: in function <Interface\AddOns\Hekili\State.lua:1474>
[string "-- Havoc:cooldown:1 recheck..."]:2: in function `Recheck'
Interface\AddOns\Hekili\State.lua:1305: in function `recheck'
Interface\AddOns\Hekili\Core.lua:693: in function `GetPredictionFromAPL'
Interface\AddOns\Hekili\Core.lua:610: in function `GetPredictionFromAPL'
Interface\AddOns\Hekili\Core.lua:1006: in function `GetNextPrediction'
Interface\AddOns\Hekili\Core.lua:1175: in function `ProcessHooks'
Interface\AddOns\Hekili\UI.lua:840: in function <Interface\AddOns\Hekili\UI.lua:704>

Locals: errMsg = "Interface\AddOns\Hekili\State.lua:1514: attempt to compare number with string"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:335
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:116
 hitInternalError = false
 errorFrame = <unnamed> {
 }
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:350
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:343
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:310
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:278
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by Hekili** [comment]
Very strange.  TSM seems to have hijacked the error report, though, so I can't get more information.

Can you type `/dump Hekili.State.encounterID` after seeing this error (while still in combat) and show me the output?

**Comment by Hekili** [comment]
Never mind, I've put out a fix for this in alpha6.
