### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ckeurk** [Hekili/hekili#1850]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Hi,
is it possible to activate the translation because for the moment it doesn't work?
thanks

### Contact Information

ckeurk

**Comment by Hekili** [comment]
Yeah, at some point, I'd like to re-localize the addon but I haven't had the time/opportunity to do so while focusing on getting specializations released.  But I do plan to do so, eventually.

**Comment by ckeurk** [comment]
Thank you for your answer. 
the French version is practically translated

**Comment by Hekili** [comment]
How so?  Just because the abilities themselves are translated?  Or is somebody publishing a French version that I don't know about?  :)

**Comment by ckeurk** [comment]
No worries Hekili I participated in the translation under another pseudo (Prissti) 
[CurseForge](https://www.curseforge.com/wow/addons/hekili/localization)

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
