### ISSUE TITLE
Shadowpriest: Devouring Plague suggestion without enough resource to cast.

### ISSUE THREAD

**Issue by KennyBurch** [Hekili/hekili#1854]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After about 1-2min of single target testing Dev.Plague will be suggested even though insanity may not be anywhere near close enough to cast.  

### How to Reproduce

Using shadowpriest, progressing though the single target dps rotation will encounter this issue.

### Talent Loadout

BIQAu+2Vv7op3uGggQnVDr07wIItAAAAAAAAAAAAAAikoEhU0iEJlESAakEJSkABJSRahkAA

### Snapshot

https://pastebin.com/BTGQp6D0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/x6J4z8F8MjE1pWsMGD9Gum

### Additional Information

My best guess is that its getting allowed due to 'refreshable'  Since Dev.Plage is unique in its 'refreshing' I don't think this is needed.

### Contact Information

Lavious#8940

**Comment by Hekili** [comment]
The check for Devouring Plague's cost (and every other ability's) is built in and not part of the priority list logic itself.  The addon seems to know that you have only 17 insanity, but it looks like resource forecasting could've broken down.

Do you have BugSack/BugGrabber installed?  I'm not able to replicate the issue on my end, but this would typically occur if there was an error in the course of forecasting resources.

**Comment by slybax** [comment]
I have this issue as well. Ill install BugSack/BugGrabber and post when I get a chance if OP hasn't by then.

The issue does not happen with Wowheads M+ build. It only happens with their single target build:
(BIQAu+2Vv7op3uGggQnVDr07wIk0CAAAAAAAAAAAAAISiSESRLSkUSIBAJ5AJSIhEkIaRQCA)

**Comment by FallsC0ming** [comment]
I have this issue on my S.Priest also. Interesting observation by slybax about this happening on ST build only.

**Comment by KennyBurch** [comment]
Okay, so I did a bit more digging.
1) Removed all addons except buggrabber+bugsack and Hekili.   Ran ST build for a few minutes on the targeting dummies in necrolord area to catch a good example of the event here: https://pastebin.com/GjqtfWjC

No bugs seen in bug grabber.

Screenshot even shows that even with all debuffs dropped off target, the unpaused Hekili was still suggesting a Devouring Plague without enough insanity.  https://imgur.com/qIU2wCg

**Comment by Hekili** [comment]
This was 3 different bugs in a trenchcoat, honestly.  I am testing a solution.

**Comment by Hekili** [comment]
This should be fixed in 10.0.0-06.4.
