### ISSUE TITLE
Balance Druid - Convoke and Celestial Alignment Not in rotation

### ISSUE THREAD

**Issue by sleepness22** [Hekili/hekili#1855]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Balance druid rotation does not include convoke the spirits or celestial alignment. 

### How to Reproduce

N/A

### Talent Loadout

BYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAQiICSChkESiAaBJRkmEQCSJpEhEUAI

### Snapshot

https://pastebin.com

**Comment by Hekili** [comment]
Check /hekili > Toggles and confirm that you have Cooldowns enabled.  If so, follow ticket instructions and submit the required information.  I'm closing this ticket since it's incomplete, but if you comment with the required information, I can reopen it.
