### ISSUE TITLE
Hekili causing item compare tooltip to flicker on WW Monk

### ISSUE THREAD

**Issue by gkchesterton** [Hekili/hekili#1856]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hekili is causing the gear item compare tooltip to flicker in the retail client on my Monk character, but only when in Windwalker spec. The tooltip for the item your character is currently wearing flickers, not tooltip for the item in your bag. I've tested and confirmed this is happening with only Hekili running on the Retail client.

### How to Reproduce

1. Log onto Monk character
2. Switch to WW spec
3. Open bags
4. Hover over gear item in bag
5. See the item compare tooltip flickering 

### Player Information (Link)

```Text
build: v10.0.0-06.1
level: 29 (29)
class: MONK
spec: windwalker

talents: ascension
    calming_presence = 1/1
    fast_feet = 2/2
    ferocity_of_xuen = 2/2
    fists_of_fury = 1/1
    flashing_fists = 2/2
    flying_serpent_kick = 1/1
    glory_of_the_dawn = 1/1
    improved_roll = 1/1
    meridian_strikes = 1/1
    paralysis = 1/1
    power_strikes = 1/1
    rising_sun_kick = 1/1
    soothing_mist = 1/1
    strike_of_the_windlord = 1/1
    tigers_lust = 1/1
    touch_of_karma = 1/1
    vigorous_expulsion = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: bear_hide_boots = 1
    belt_of_beginnings = 1
    bracers_of_the_million_gold_man = 1
    cue_cue_gloves = 1
    eternal_emberfury_talisman = 1
    inherited_cape_of_the_black_baron = 1
    inherited_mark_of_tyranny = 1
    signet_of_the_third_fleet = 1
    stained_shadowcraft_cap = 1
    stained_shadowcraft_pants = 1
    stained_shadowcraft_spaulders = 1
    stained_shadowcraft_tunic = 1
    swift_hand_of_justice = 1
    tabard_of_the_zandalari = 1
    venerable_dalrends_sacred_charge = 1
    venerable_mass_of_mcgowan = 1
    windrunner_band = 1

legendaries: none

itemIDs: 122248, 122254, 122261, 122351, 122358, 122361, 122383, 122385, 122530, 122667, 128169, 165001, 62884, 62887, 62892, 62896, 65671

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Windwalker
    petbased = false
    potion = potion_of_spectral_agility
    regularRefresh = 0.5
    strict = false
    throttleRefresh = false
    throttleTime = false
    allow_fsk = false
    check_sck_range = false
    check_wdp_range = false
    optimize_reverse_harm = false
    sef_one_charge = false
    tok_damage = 1
    use_diffuse = false

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    blackout_kick            = 6   [01]
    crackling_jade_lightning = A5  [06]
    expel_harm               = 3   [01]
    fists_of_fury            = 7   [01]
    flying_serpent_kick      = 1   [01]
    leg_sweep                = =   [01]
    paralysis                = A7  [06]
    rising_sun_kick          = 5   [01]
    roll                     = 2   [01]
    soothing_mist            = 1   [07], 1   [09]
    spinning_crane_kick      = 9   [01]
    strike_of_the_windlord   = 8   [01]
    tiger_palm               = 4   [01]
    tigers_lust              = A1  [06]
    touch_of_death           = CS4 [04]
    touch_of_karma           = CS1 [04]

warnings: none
```

### Error Messages (Link)

```Text
No error message in-game
```

### Contact Information

Chesterton#6100 (Discord ID)

**Comment by Hekili** [comment]
I'm not able to replicate this issue.  Do you have BugSack/BugGrabber installed?  Are there error messages?

**Comment by gkchesterton** [comment]
Just installed them. No error messages come up unfortunately when the flickering happens.

**Comment by gkchesterton** [comment]
I just created a new monk Kul Tiran character, with only Hekili, Bugsack, and Buggrabber enabled, set my spec to WW, searched for some gear in the AH and got the flickering issue when hovering over listings in the AH. It went away when I switched my spec to MW. Still no error reports unfortunately though.

**Comment by maxiixam** [comment]
This may not be limited to WW spec. I have been experiencing the same thing but on other classes sporadically. Wish I could give me details, but I have def seen this tooltip flickering recently and figured it was something on blizzards end. Will try and get mroe details next time I see it happening.

**Comment by gkchesterton** [comment]
Yeah, this is happening as well on my new paladin alt that I'm leveling.

**Comment by mortallon** [comment]
this happening to me on my druid monk also, i didnt check all. just leveling my characters and i observed this issue with hekili enabled. "also i have elvui"

**Comment by Hekili** [comment]
This may be resolved when 10.0.2 launches today, as the tooltip API will change.  Let me know; I still haven't seen this myself.

**Comment by Hekili** [comment]
Can anyone confirm whether they're experiencing this since 10.0.2 launched?

**Comment by maxiixam** [comment]
I have not had it in quite a few versions myself. Seems to be gone.

**Comment by Hekili** [comment]
Thank you!
