### ISSUE TITLE
Balance Druid AoE Starfall not available

### ISSUE THREAD

**Issue by vleermuisman** [Hekili/hekili#1857]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When using AOE Talent build in raid, not so much in keys/dungeons, it will call for me to use Starfall yet I do not have enough astral power to do so, it will then stall for 5 seconds or so. I will have star surge and starfire procs avail to use, I end up using starfire until it allows me to starfall and the addon then aligns back up.

### How to Reproduce

Balance Druid
AoE/Dungeon Talent set from wowhead
Go to dummies and follow addon
Will take a while but will line up in time
(I have CDs off as I use them as needed)

### Snapshot

I will get this later, at work

### Contact Information

Lefonque#4443

**Comment by yenbounger** [comment]
Pastebins of the issue:

Just before I had enough astral power for one starfall:
https://pastebin.com/eWidDKfQ

Just After I cast that starfall:
https://pastebin.com/aAp7rCNa

Let me know if you need any other cases :)

**Comment by Hekili** [comment]
This should be fixed in 10.0.0-06.4.
