### ISSUE TITLE
Death Knight Blood (Tank) Death and Decay issu

### ISSUE THREAD

**Issue by Behnam45** [Hekili/hekili#1858]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hey, when i Entering the combat with my charecter DK blood(tank), the Addon Hekili suggestion Spells after i use 1time Death and Decay and it get 15sec cd, The Rotation again suggest me to use That spell again (Death and decay) Even if it is not ready yet, it just suggest me to use it again and again, while others spells is ready and i can use, it just suggest me to use that :(

### How to Reproduce

![World Of Warcraft Screenshot 2022 11 03 - 00 04 54 39](https://user-images.githubusercontent.com/70517979/199597367-a5894255-f49d-4398-9500-9fefad5f9950.png)
![World Of Warcraft Screenshot 2022 11 03 - 00 05 05 90](https://user-images.githubusercontent.com/70517979/199597408-5fedf67a-aa68-4d89-8e54-68eb8667070c.png)
![World Of Warcraft Screenshot 2022 11 03 - 00 04 48 80](https://user-images.githubusercontent.com/70517979/199597441-8e77908e-f2d0-45ed-a0e7-d5e803820c69.png)
![World Of Warcraft Screenshot 2022 11 03 - 00 04 51 17](https://user-images.githubusercontent.com/70517979/199597513-a0a0e3f6-6a64-4b7d-a2a6-a7ebe33b164f.png)
![World Of Warcraft Screenshot 2022 11 03 - 00 04 58 96](https://user-images.githubusercontent.com/70517979/199597557-cf0417cc-cd43-4e98-bfe1-1ec5052f0d03.png)

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDgQIBCCRSSiIJCSSSAAAAAAgQSkkk0CSAAAkIJRAAAAA

### Snapshot

https://pastebin.com/9MJerNXH

### Contact Information

Behnam#4628

**Comment by Hekili** [comment]
This will be addressed in the next release.
