### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by Madjewow** [Hekili/hekili#186]
I've switched from Arcane to Frost and would love to use Hekili (I have used it on my main, an Elemental Shaman for at least a year.)  My current Frost Mage talents are 1,2,1,1,1,2,1.  My issue is that I can't for the life of me figure out what the 3rd icon is on your priority boxes. It shows Frostbolt, Icy Veins, something I don't know or have as a spell that looks like that, and then Ice Lance.  Help!  What is that icon telling me?  :)  LOVE HEKILI!

**Comment by Hekili** [comment]
Take a look at your pause keybind (ALT-SHIFT-P, if you haven't changed it).  Pause when the icon is showing and then put your mouseover it to see what it is.

**Comment by Madjewow** [comment]
Thank you, it was driving me crazy!!  On a different note, I tried to donate but is there only a monthly donation through Patreon? I want to make a one-time donation (more than the $5 that shows up on Patreon).

**Comment by Hekili** [comment]
There is a donate button on the right side of the CurseForge page for PayPal.  I appreciate any support, whether Patreon or PayPal.  :)

https://www.curseforge.com/wow/addons/hekili

Thank you!
