### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by JumpyCraft** [Hekili/hekili#1860]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

the Addon does not load. I tried all the troubleshooting steps and it still doesn work

### How to Reproduce

enter game and it just doesn't show up.

### Player Information (Link)

```Text
build: v10.0.0-06.3
level: 60 (60)
class: WARLOCK
spec: destruction

talents: BsQAbtPS25JQs0VfQSDmhm+p3AIJRiEINtIINJJkClAIhAJKIBAAAAAAAAAAAQIJlkE

pvptalents: none

covenant: necrolord

conduits: none

soulbinds: []

sets: none

gear: abominable_visage = 1
    avowed_tormenters_vestment = 1
    blighted_margraves_cloak = 1
    faemoss_amice = 1
    gnomeregan_tabard = 1
    gory_surgeons_gloves = 1
    leggings_of_the_erudite_scholar = 1
    memoria_spellblade = 1
    nathrian_tabernacle = 1
    necropolis_lords_shackles = 1
    ritual_commanders_ring = 1
    shadewalker_footwraps = 1
    sin_stained_pendant = 1
    spiritmenders_cord = 1
    stitchfleshs_misplaced_signet = 1
    unbound_changeling = 1
    vial_of_caustic_liquid = 1

legendaries: none

itemIDs: 137508, 177767, 178708, 178732, 178736, 178748, 178755, 178761, 178781, 178782, 178827, 178828, 181420, 181503, 181575, 181636, 45578

settings: none

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 

warnings: none
```

### Error Messages (Link)

```Text
dont get an error just cant see it
```

### Contact Information

JumpyCraft11#2998 - discord

**Comment by pozzer18** [comment]
locks are not currently supported, they are still being worked on try typing /hekili in game to see which current specs / classes are supported

**Comment by pozzer18** [comment]
Current list of non implemented classes and specs

DruidRestoration
EvokerDevastation
EvokerPreservation
MageArcane
MageFire
MageFrost
MonkBrewmaster
MonkMistweaver
PriestDiscipline
PriestHoly
RogueAssassination
RogueOutlaw
RogueSubtlety
ShamanRestoration
WarlockAffliction
WarlockDemonology
WarlockDestruction

**Comment by JumpyCraft** [comment]
ty sm

**Comment by Hekili** [comment]
Your specialization is not supported in Dragonflight (yet).  This information is presented to you when you log into the game, and is also shown if you open the addon menu.  All classes/specializations will be supported, but it takes time to implement all the new talents and nuances.  Thank you for being patient.
