### ISSUE TITLE
Shadowpriest doesn't seem to recommend mind sear under any parameter 

### ISSUE THREAD

**Issue by Zagora69** [Hekili/hekili#1862]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

i have enemy nameplates on tried with plater or deflaut. i currently have the addon on auto but have tried on aoe and reactive. have tried setting mind sear ticks from 0-4 to no avail. i have tried detect dmg enemies/dotted enemies. have tried nameplate detection. Added note have tested in SL open world, a 13 Streets, and on dummies in org/zuldazar.

### How to Reproduce

enter the game as a shadow priest. 
enter an aoe scenario (3 or more)
addon not seeming to want to use mind sear as spender.

### Talent Loadout

BIQAu+2Vv7op3uGggQnVDr07wgIIBAAAAAAAAAAAAAJiSESTLJJJFIBoRSkIRCEkIFpFSCA

### Snapshot

https://pastebin.com/9UUurTJx

### Contact Information

Izuna#9645

**Comment by Hekili** [comment]
Thanks, I've updated the priority from SimC (and shoehorned covenant stuff back in) and will load it later today.

**Comment by Hekili** [comment]
This should be fixed in 10.0.0-06.4.
