### ISSUE TITLE
Death and Decay spam as soon as Dancing Rune Weapon is usable.

### ISSUE THREAD

**Issue by sanyex89** [Hekili/hekili#1867]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I only get Death and Decay recommendations when Dancing Rune Weapon is usable. It keeps telling me to wait for the Death and Decay Cooldown for 10 sec till its usable again. This repeats. If I use Dancing Rune Weapon I get the normal rotation reccomendations from hekili. Till Dancing Rune Weapon is usable. Then it spams Death and Decay again.

### How to Reproduce

Use my Build.
Got to Ebon Hold and attack a Dummy.

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDCJJgk4AiIREJiECkkEJAAAAAAiDkARSTiIBAAISSEAAAA

### Snapshot

https://pastebin.com/gUkZkFaE

**Comment by Hekili** [comment]
Could you do me a favor?  In your description, you say the addon is telling you to *wait* and use DRW again.  In the snapshot, it's actually saying to use Death and Decay *immediately*.  Can you provide a snapshot taken when it is telling you to wait?

**Comment by sanyex89** [comment]
oh what i meant was: hekili shows me the Death and Decay symbol with the swirl on top (like it still needs a few seconds till its off cd) 

so if i would only do what hekili tells me i would only spam Death and Decay with the occasional Deaths Caress in between 

the snapshot was from the moment when i had no more Death and Decay charges and told me to wait (a few seconds till its off cd) till i get another one

edit: here is another snapshot
https://pastebin.com/euviFjT9

![Screenshot 2022-11-03 175055](https://user-images.githubusercontent.com/77323774/199783990-0ae048c9-d5f4-4483-958e-bd8414b2beee.jpg)

**Comment by Hekili** [comment]
This should be fixed in 10.0.0-06.4.
