### ISSUE TITLE
Elemental - Earth shock not recommended in priority queue when using EOGS legendary in multi-target situations

### ISSUE THREAD

**Issue by Fynnconceivable** [Hekili/hekili#1870]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For elemental shaman: If you're wearing the Echoes of the Great Sundering legendary (not using the talent), the queue will not recommend Earth Shock once you've entered combat with multiple targets. You need to use Earth Shock even in aoe/cleave situations in order to trigger the EOGS buff to earthquake.

This issue with the queue does not occur when using the EOGS talent instead.

### How to Reproduce

1. Equip the Echoes of the Great Sundering legendary.
2. Use talent buildout below, ensuring you are not also using the EOGS talent.
3. Find a set of swarm target dummies or hang out in the Venthyr hall where it's nigh impossible to avoid hitting additional target dummies.
4. Start your opening rotation, which will probably involve stormkeeper and chain lightning, assuming you want to hit all the things.
5. Once you generate the required 50 maelstrom (usually after a flame shock > stormkeeper > chain lightning), the queue will recommend earthquake rather than an initial earth shock cast required to buff earthquake.

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAAoVSSLJRJSLRBBFgEAAAAAAUCQKJJlUkUIiIJAIBA

### Snapshot

https://pastebin.com/m8uKsEVv

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/4bk6KgaYDo4uvm9ZTE9ukM

### Additional Information

Character data: https://pastebin.com/EfaMzSXr

INTERESTING OBSERVATION: The hecticaddcleave/1 boss sim I posted above shows me casting earth shock. A multi-boss patchwork sim does not, nor does hecticaddcleave/2 bosses. Here's an example sim of the latter (with legendary gloves):
https://www.raidbots.com/simbot/report/kW4Jea8Qp2GQGHW7uPZcUA

This seems wrong? To compare, here is a sim using rank 1 of the EOGS talent (no EOGS legendary, just Unity) against hecticaddcleave/2 bosses, which does indeed include earth shock casts:
https://www.raidbots.com/simbot/report/pPnHnQ6e5gzvDVF8F3mKiM

(Please ignore the fact that I haven't swapped from venthyr to night fae; I'm being lazy, but I don't think it affects the issue.)

### Contact Information

Fynn#4724

**Comment by Hekili** [comment]
The legendary version of EOGS will be accounted for in the next release.
