### ISSUE TITLE
Can´t change texture for spallflash

### ISSUE THREAD

**Issue by branioparusic** [Hekili/hekili#1871]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hi.
All of the sudden my circle i have been using for Spellflash texture is back to its original Star.

I dont seem to be able to change the texture under Spellflash to show as anything else but default "Star".
Before i had SpellFlashCore and SpellFlash installed and same thing occured then, i have uninstalled them both and no change.

No settings, reloads etc seem to work - it only shows me the Start (Default) blink.

This is my first ticket/report so not sure im doing it right, but would be great if i got some tips on how to sort this.

Thanks

### How to Reproduce

1. I have tried all my other tanks

### Player Information (Link)

```Text
build: v10.0.0-07.1
level: 60 (60)
class: WARRIOR
spec: protection

talents: BkEAtml4yL3PsSlRlqnvTeVx4LgAAAAASSSkkQSLpkgWBRIQRIRJJBIAQLkkAyBQIAAAAAAAABAAlG
    anger_management = 1/1
    armored_to_the_teeth = 2/2
    avatar = 1/1
    barbaric_training = 1/1
    battle_stance = 1/1
    best_served_cold = 1/1
    blood_and_thunder = 1/1
    bloodsurge = 1/1
    booming_voice = 1/1
    brace_for_impact = 1/1
    brutal_vitality = 1/1
    challenging_shout = 1/1
    crushing_force = 2/2
    defensive_stance = 1/1
    demoralizing_shout = 1/1
    devastator = 1/1
    double_time = 1/1
    endurance_training = 1/1
    enduring_defenses = 1/1
    fast_footwork = 1/1
    frothing_berserker = 1/1
    furious_blows = 1/1
    heroic_leap = 1/1
    ignore_pain = 1/1
    impending_victory = 1/1
    impenetrable_wall = 1/1
    indomitable = 1/1
    intervene = 1/1
    into_the_fray = 1/1
    last_stand = 1/1
    leeching_strikes = 1/1
    onehanded_weapon_specialization = 1/1
    overwhelming_rage = 1/2
    pain_and_gain = 1/1
    reinforced_plates = 1/1
    rend = 1/1
    revenge = 1/1
    seismic_reverberation = 1/1
    shield_specialization = 2/2
    shield_wall = 1/1
    show_of_force = 1/1
    sidearm = 1/1
    spell_reflection = 1/1
    strategist = 1/1
    thunder_clap = 1/1
    thunderlord = 1/1
    tough_as_nails = 1/1
    unstoppable_force = 1/1
    violent_outburst = 1/1
    war_machine = 1/1

pvptalents: none

covenant: necrolord

conduits: adaptive_armor_fragment = 1
   brutal_vitality = 1
   fueled_by_violence = 1
   show_of_force = 1
   stalwart_guardian = 1
   veterans_repute = 1

soulbinds: [plague_deviser_marileth]
   kevins_oozeling = 1
   oozs_frictionless_coating = 1
   plagueborn_cleansing_slime = 1
   ultimate_form = 1
   viscous_trail = 1
   volatile_solvent = 1

sets: enforcers_stun_grenade = 1

gear: anodized_deflectors = 1
    arrowbreaker_greatshield = 1
    blade_of_grievous_harm = 1
    cabochon_of_the_infinite_flight = 1
    codex_of_the_first_technique = 1
    duplicating_drape = 1
    enforcers_stun_grenade = 1
    gaze_of_the_infinite_infantry = 1
    grasps_of_the_infinite_infantry = 1
    incarnadine_breastplate = 1
    legplates_of_the_infinite_infantry = 1
    pauldrons_of_the_infinite_infantry = 1
    protecting_bit_band = 1
    shadowghast_sabatons = 1
    shadowghast_waistguard = 1
    shield = 1
    signet_of_collapsing_stars = 1

legendaries: glory = 1
    reprisal = 1

itemIDs: 109892, 110017, 110053, 168978, 169161, 171413, 171418, 185813, 185820, 185824, 185836, 185843, 188937, 188940, 188941, 188942

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Protection Warrior
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    free_revenge = true
    heroic_charge = false
    last_stand_offensively = false
    overlap_ignore_pain = false
    shockwave_interrupt = true
    stack_shield_block = false

toggles: cooldowns = true [separate]
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    avatar             = =   [01]
    challenging_shout  = E   [07]
    charge             = 1   [01]
    demoralizing_shout = -   [01]
    execute            = /   [01]
    fireblood          = Q   [07]
    heroic_leap        = 7   [01]
    ignore_pain        = M5  [06]
    pummel             = 5   [01]
    revenge            = 3   [01]
    shield_block       = M4  [06]
    shield_slam        = 2   [01]
    spell_reflection   = 9   [01]
    thunder_clap       = 4   [01]

warnings: none
```

### Error Messages (Link)

```Text
Dont seems to be any error messages at all.
```

### Additional Information

Same goes for all my other chars in there, have all 6 tanks and none of them can get any other texture than Star (Defalut)

### Contact Information

brani@oparusic.se

**Comment by Bjoerntr** [comment]
same for me with druid (tank and balance)

`build: v10.0.0-07.1
level: 60 (60)
class: DRUID
spec: guardian

talents: BgGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAASEJJplAkEJQEJNIAIIIBSSSSSCAAAAAAAARA
    astral_influence = 2/2
    berserk_ravage = 1/1
    berserk_unchecked_aggression = 1/1
    brambles = 1/1
    circle_of_life_and_death = 1/1
    convoke_the_spirits = 1/1
    elunes_favored = 1/1
    flashing_claws = 2/2
    frenzied_regeneration = 1/1
    fury_of_nature = 2/2
    galactic_guardian = 1/1
    gore = 1/1
    gory_fur = 1/1
    heart_of_the_wild = 1/1
    improved_barkskin = 1/1
    improved_stampeding_roar = 1/1
    innate_resolve = 1/1
    ironfur = 1/1
    killer_instinct = 3/3
    lycaras_teachings = 3/3
    mangle = 1/1
    maul = 1/1
    moonkin_form = 1/1
    nurturing_instinct = 3/3
    renewal = 1/1
    scintillating_moonlight = 2/2
    skull_bash = 1/1
    soothe = 1/1
    stampeding_roar = 1/1
    starfire = 1/1
    starsurge = 1/1
    survival_instincts = 1/1
    swipe = 1/1
    thick_hide = 2/2
    thrash = 1/1
    tooth_and_claw = 1/1
    twin_moonfire = 1/1
    ursine_adept = 1/1
    ursocs_guidance = 1/1
    verdant_heart = 1/1
    vulnerable_flesh = 2/2

pvptalents: none

covenant: night_fae

conduits: conflux_of_elements = 1
   front_of_the_pack = 1
   fury_of_the_skies = 1
   innate_resolve = 1
   precise_alignment = 1
   wellhoned_instincts = 1

soulbinds: [niya]
   bonded_hearts = 1
   called_shot = 1
   grove_invigoration = 1
   natures_splendor = 1
   niyas_tools_poison = 1
   run_without_tiring = 1

sets: architects_ingenuity_core = 1
    cache_of_acquired_treasures = 1

gear: architects_ingenuity_core = 1
    armschienen_der_fixsterne = 1
    cache_of_acquired_treasures = 1
    chiffrengravierter_anhnger = 1
    choralstab = 1
    einfallsreichtumskern_des_architekten = 1
    fulappen_der_fixsterne = 1
    handlappen_der_fixsterne = 1
    hftgurt_der_einigkeit = 1
    illusionssignet_des_tuschers = 1
    rtselhafte_beinkleider = 1
    rtselhafte_maske = 1
    rtselhafte_weste = 1
    schulterpolster_der_fixsterne = 1
    truhe_mit_erhaltenen_schtzen = 1
    unglaublich_uralter_umhang = 1
    weggeworfenes_signet_des_kartells_al = 1

legendaries: celestial_spirits = 1

itemIDs: 188044, 188265, 188268, 188850, 188851, 188853, 188854, 190349, 190352, 190353, 190465, 190605, 190635, 190731, 192450

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Guardian
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    catweave_bear = false
    ironfur_damage_threshold = 5
    mangle_more = false
    maul_rage = 20
    owlweave_bear = false
    shift_for_convoke = false

toggles: cooldowns = true [separate]
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = true [overridden]
    interrupts = true [separate]
    mode = automatic 
    potions = false 

keybinds: 
    barkskin              = 3   [07]
    bear_form             = 1   [01], 1   [07]
    brutal_slash          = 6   [07], 5   [09]
    convoke_the_spirits   = 0   [09]
    entangling_roots      = 7   [10]
    frenzied_regeneration = 9   [09]
    growl                 = 1   [09]
    ironfur               = 8   [09]
    mangle                = 4   [09]
    maul                  = 6   [09]
    moonfire              = 5   [07], 2   [09], 1   [10]
    shred                 = 2   [07]
    skull_bash            = 7   [07], 7   [09]
    survival_instincts    = ß  [09]
    swipe                 = 6   [07], 5   [09]
    swipe_bear            = 6   [07], 5   [09]
    swipe_cat             = 6   [07], 5   [09]
    thrash                = 4   [07], 3   [09]
    thrash_bear           = 4   [07], 3   [09]
    thrash_cat            = 4   [07], 3   [09]

warnings: none

`

**Comment by thematrixincendies** [comment]
We already had an issue for that: https://github.com/Hekili/hekili/issues/1859
Which was just rejected without investigation... 
Yes, it's broken for me too.

**Comment by Hekili** [comment]
Will be fixed in next release.

**Comment by branioparusic** [comment]
Fixed for me, thank you so much for the quick and excellent help! 
Any link on where i can contribute to your work?

Sorry if i missed it somewhere, but please link it and ill donate.

Appreciate the work alot.
Best regards
