### ISSUE TITLE
Outlaw rotation recommend

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#1872]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

2> During DreadBlades window, it recommends to RTB when the buff is expired. We don't want to waste a GCD to refresh RTB

4> It doesn't detect Empower Combo Point from Echoing Reprimand. When we land in those Combo Points, it doesn't suggest to do a finisher. And there is also an error of the old version Hekili with this. Those Empower Combo Points only works with damage finishing moves, it doesn't work with Slice and Dice so it shouldn't get suggested when we land in those CP.

### How to Reproduce

1. Enter game as Outlaw
2. Start hitting dummies to produce those errors in rotation.

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAQEkkAkkEJtkkABSkIBgIAAAAAAAJhkmUSCIJpEAAAA

### Snapshot

https://pastebin.com/AhCQRMH5

### Contact Information

Seveth#0433

**Comment by vond82** [comment]
1. This seems correct? Finisher rules includes finishing at -1 when opportunity is up 
3. While true i dont think the APL has been updated with this yet

**Comment by Sedveth** [comment]
> 1. This seems correct? Finisher rules includes finishing at -1 when opportunity is up
> 2. While true i dont think the APL has been updated with this yet

You only want to finish at 6 CP if broadside is up or at 6 stack of FTH
Edit: yeah my bad, I just checked the finisher rule again. It seems to be corrected

**Comment by vond82** [comment]
> > 1. This seems correct? Finisher rules includes finishing at -1 when opportunity is up
> > 2. While true i dont think the APL has been updated with this yet
> 
> You only want to finish at 6 CP if broadside is up or at 6 stack of FTH

Thats neither what APL (nor outlaw FAQ on rogue discord) says though, and Hekili follows the latest APL

**Comment by Sedveth** [comment]
> > > 1. This seems correct? Finisher rules includes finishing at -1 when opportunity is up
> > > 2. While true i dont think the APL has been updated with this yet
> > 
> > 
> > You only want to finish at 6 CP if broadside is up or at 6 stack of FTH
> 
> Thats neither what APL (nor outlaw FAQ on rogue discord) says though, and Hekili follows the latest APL

Yeah I edited my comment, thanks for your reply

**Comment by Sedveth** [comment]
> > > 1. This seems correct? Finisher rules includes finishing at -1 when opportunity is up
> > > 2. While true i dont think the APL has been updated with this yet
> > 
> > 
> > You only want to finish at 6 CP if broadside is up or at 6 stack of FTH
> 
> Thats neither what APL (nor outlaw FAQ on rogue discord) says though, and Hekili follows the latest APL

Yeah I edited my comment, thank you for reply

**Comment by Hekili** [comment]
Echoing Reprimand will be accounted for in `effective_combo_points` in the next release.
