### ISSUE TITLE
Priority-rotation not automatically updating

### ISSUE THREAD

**Issue by praiseshiva** [Hekili/hekili#1873]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The priority-rotation icons seem to get stuck and stop updating at a certain point. Eventually it will start updating again. The ability it gets stuck on seems to be random. It also seems to happen shortly after engaging a mob. Once the rotation updating starts again and the fight exceeds 10 or so seconds the rotation seems to be fine. I've only noticed this while playing as a Vengeance Demon Hunter. The spec/talent choices don't seem to matter. The issue has existed back through at least the last few updates before v10. 
There is no bugsack error.
I've made very minimal changes as far as Hekili options go (mostly just appearance) and it worked fine prior to maybe v9.2.7 I think but I can't be certain on when I first noticed the issue.

### How to Reproduce

1. Play Vengeance Demon Hunter.
2. Be sure all abilities are off cooldown.
3. Engage with a mob that will live at least 15 seconds or a target dummy. 

### Player Information (Link)

```Text
build: v10.0.0-07.1
level: 60 (60)
class: DEMONHUNTER
spec: vengeance

talents: BUkACnvaHJn8GSPD6tpaeczPTBAgIUCREARCQCgEtEJCJIJtkUSIJhSkEAAAAA
    agonizing_flames = 2/2
    aldrachi_design = 1/1
    aura_of_pain = 1/1
    blazing_path = 1/1
    burning_alive = 1/1
    burning_blood = 2/2
    calcified_spikes = 1/1
    chaos_fragments = 1/1
    chaos_nova = 1/1
    charred_warblades = 1/1
    consume_magic = 1/1
    darkglare_boon = 2/2
    deflecting_spikes = 1/1
    demonic = 1/1
    extended_sigils = 2/2
    fallout = 1/1
    fel_devastation = 1/1
    fiery_brand = 1/1
    fiery_demise = 2/2
    focused_cleave = 1/1
    fracture = 1/1
    frailty = 1/1
    imprison = 1/1
    improved_disrupt = 1/1
    infernal_armor = 2/2
    master_of_the_glaive = 1/1
    perfectly_balanced_glaive = 1/1
    pursuit = 1/1
    quickened_sigils = 1/1
    rush_of_chaos = 1/1
    shattered_restoration = 2/2
    sigil_of_flame = 1/1
    sigil_of_silence = 1/1
    soul_furnace = 1/1
    soul_rending = 2/2
    soul_sigils = 1/1
    soulcrush = 1/1
    the_hunt = 1/1
    void_reaver = 1/1
    volatile_flameblood = 1/1
    vulnerability = 2/2
    will_of_the_illidari = 2/2

pvptalents: none

covenant: venthyr

conduits: condensed_anima_sphere = 1
   fel_defender = 1
   felfire_haste = 1
   growing_inferno = 1
   relentless_onslaught = 1
   soul_furnace = 1

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   familiar_predicaments = 1
   fatal_flaw = 1
   friends_in_low_places = 1
   nimble_steps = 1
   thrill_seeker = 1

sets: none

gear: brokers_lucky_coin = 1
    captain_sanders_shirt = 1
    cryptic_grips = 1
    cryptic_mask = 1
    cryptic_shoulderpads = 1
    cypheretched_band = 1
    cypheretched_lavaliere = 1
    cypheretched_ring = 1
    gnomeregan_tabard = 1
    meno_sword = 1
    mercurial_punishers_boots = 1
    mercurial_punishers_breeches = 1
    mercurial_punishers_jerkin = 1
    shadowlace_cloak = 1
    symbol_of_the_lupine = 1
    umbrahide_armguards = 1
    umbrahide_waistguard = 1

legendaries: agony_gaze = 1
    collective_anguish = 1

itemIDs: 172320, 172321, 173215, 188893, 188894, 188899, 190351, 190352, 190354, 190389, 190597, 190632, 190633, 190635, 192430, 3342, 45578

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Vengeance
    petbased = false
    potion = phantom_fire
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    infernal_charges = 1

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true [overridden]
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    consume_magic   = AE  [06]
    demon_spikes    = 3   [01]
    disrupt         = A2  [06]
    fel_devastation = 4   [01]
    felblade        = AQ  [06]
    fiery_brand     = A1  [06]
    fracture        = 2   [01]
    immolation_aura = A3  [06]
    infernal_strike = `   [03]
    metamorphosis   = AR  [06]
    sigil_of_flame  = A4  [06]
    sinful_brand    = 5   [01]
    soul_cleave     = 1   [01]
    spirit_bomb     = E   [01]
    the_hunt        = AW  [06]
    throw_glaive    = Q   [01]

warnings: none
```

### Error Messages (Link)

```Text
no BugSack/BugGrabber errors.
```

### Additional Information

I made a video with several examples of the issue.
https://streamable.com/xzlaum

**Comment by Hekili** [comment]
This should've been a recommendations ticket and requires a snapshot to diagnose.

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

# Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by praiseshiva** [comment]
Just to be clear, I'm not suggesting a different rotation/priority. I'm saying it seems the addon is not updating the primary suggestion shortly after initiating combat.
Here is a snapshot? I hope you can get what you need out of this.
In this example, Hekili was suggesting Sinful Brand but the ability had already been used several seconds prior. Sinful Brand is also not the only ability that seems to "stick." My video link in the additional information above highlights more.

Snapshot: https://pastebin.com/3Fq7Kwf8
Screenshot: https://i.imgur.com/gXYuwln.jpeg

A couple Hekili related BugSack/BugGrabber errors popped up when trying to take/time my snapshot/screenshot. These do not show up in the normal course of play.
https://pastebin.com/3iRtW4ND

**Comment by Hekili** [comment]
Thanks.  The error message and snapshot (which included warnings) helped diagnose this issues.  Will post a fix in a little bit.
