### ISSUE TITLE
Bestial Wrath is not included in the rotation for Beast Master

### ISSUE THREAD

**Issue by mkh67465** [Hekili/hekili#1875]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After det new updates Beastial Wrath is not showing up in the rotation, which is a bug cause its a must to use

### How to Reproduce

After det new updates Beastial Wrath is not showing up in the rotation, which is a bug cause its a must to use

### Talent Loadout

B0PAIlFMjeNhnEouGfV8Ij2uShgWCACBAAAAAAAAAAgGEyBgIBJkkgmQa5ASChQoRSE

### Snapshot

https://pastebin.com/TdfhJBSU

**Comment by MrBean73** [comment]
you deactivate cooldowns in the  settings ( toogle)

**Comment by mkh67465** [comment]
> 

Thanks! dont know why it got placed under there :)
