### ISSUE TITLE
FDK priority issue

### ISSUE THREAD

**Issue by Cheetah714** [Hekili/hekili#1876]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

while the BoS is active the addon recommends spamming Howling Blast which is not right

### How to Reproduce

1-Enter the game as FDK
2-follow the rotation until you have enough runic power to active BoS
3-active BoS the rotation recommends spamming HB

### Talent Loadout

BsPAdLUHklrTr3hBIcYWdbnCGnkAICSCHIiEBikECIJJJBBCiISkkkkEAAAAAAAAAAAAA

### Snapshot

https://pastebin.com/ZTaSVFn7

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mV2FHP4NVABZbZ6G2Z1riK

**Comment by Hekili** [comment]
This is a subtle issue but should be resolved in the next release.
