### ISSUE TITLE
Feral: Adaptive Swarm talent not working/recommended

### ISSUE THREAD

**Issue by vond82** [Hekili/hekili#1879]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When talented into Adaptive Swarm as feral (with or without Unbridled Swarm capstone), Hekili never recommends to cast it. According to the snapshot there are several warnings like this:

warnings: [#1] IsKnown() - 391888 / adaptive_swarm not found in abilities table.

Full snapshot included below.

### How to Reproduce

1. Enter game as Feral Druid.
2. Take the Adaptive Swarm with or without Unbridled Swarm.
3. Start fighting dummy.
4. Adaptive Swarm is never recommended.

### Talent Loadout

BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAQkUgIJJRSRjQSkIJAAAAAAoIASCAiIJEkgEaJAAAAAAASA

### Snapshot

https://pastebin.com/Kh6nvVcD

### Additional Information

I did not check with the covenant ability, only talent.

**Comment by vond82** [comment]
Update: Tested with covenant version and that works fine

**Comment by Hekili** [comment]
This will be addressed in the next release.
