### ISSUE TITLE
Bane of Havoc (PvP Talent) recommended on long CD

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [Hekili/hekili#188]
On a destruction warlock, with the Bane of Havoc PvP talent selected (which changes single target Havoc ability into a AoE ground ability) it will show Havoc as recommended to be cast even if it's on a 15+ sec cooldown. This only happens when the PvP talent is active (i.e. in PvP zones like warmode). This does not happen with the regular Havoc ability. 

https://pastebin.com/Hd4CwhSD

Let me know if you need different or additional information

**Comment by BuurmanDeBuurman** [comment]
Snapshot:
https://pastebin.com/2E4uXfgd

**Comment by Hekili** [comment]
So, this is interesting because Bane of Havoc *partially* replaces Havoc as far as the spellbook is concerned.

To support this properly, I have to decide whether an entry in the priority list for Havoc should automatically recommend Bane instead.  The conditions where you'd use one vs. the other could be very different.  What are your thoughts?

**Comment by BuurmanDeBuurman** [comment]
So the PvP talent really only has PvE value, at least for me. Ground effects usually don't come that much into play in PvP unless there is heavy CC involved. So, in general, the purpose of Havoc and Bane of Havoc are similar. Havoc (30s CD) allows your single target spells to hit two targets, Bane of Havoc (45s CD) will allow you to hit everyone in the ground effect. The difference being that with the increased CD and static ground effect you'd want to use it on packs of enemies that are grouped and remain in relatively the same place. 

Bane of Havoc has very limited functionality as it's only really valuable for PvE in War Mode, so the most important aspect here is the different CDs. Other than that I'd say that the uses are relatively similar in solo, war mode, pve content as the adds are gathered around you or your voidwalker.

**Comment by BuurmanDeBuurman** [comment]
I don't know if you made any specific changes relating to this, but now the same problem happens except when it comes to my trinket. Showing it as first suggestion while on a 50s+ CD.

**Comment by Hekili** [comment]
Submit a proper ticket for that issue, with the requested troubleshooting information (i.e., a snapshot).

**Comment by Hekili** [comment]
FWIW, seeing any recommendation on a long cooldown *typically* has less to do with the ability being recommended and more to do with a different ability not being found sooner.

The exception would be, as you'd found previously, when an ability's cooldown isn't properly detected.

**Comment by BuurmanDeBuurman** [comment]
The behavior of the trinket recommendation seemed to function very similar to the bug with Bane of Havoc which is why I added to it here after I downloaded the new version, but I'll put in a new ticket with snapshot next time it comes up.

**Comment by Hekili** [comment]
Thanks!
