### ISSUE TITLE
Unholy DK again stopping recommendations, buttons disappearing

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#1881]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

On Unholy DK rotation is disappearing again.  

### How to Reproduce

Enter game as Unholy dk and just do the rotation

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAIRSCHItIBhIRIkkkEJAAAAAAAAAAkkESkkCAApIlDQSSikcA

### Snapshot

https://pastebin.com/2AgC1B3K
### Raidbots Sim Report (Link)

DON'T HAVE ONE

### Additional Information

I have another snapshot if needed as well

### Contact Information

Pulse#0223

**Comment by Hekili** [comment]
Your snapshot needs to go on Pastebin and get linked, as it's unreadable.

**Comment by Pulseonline** [comment]
https://pastebin.com/2AgC1B3K

**Comment by marekCs** [comment]
It's showing up normally. Try type /reload after installing a new version of the addon or check if the addon is not automatically disabled after a new release, type /hekili and see if it is enabled.

**Comment by Pulseonline** [comment]
> It's showing up normally. Try type /reload after installing a new version of the addon or check if the addon is not automatically disabled after a new release, type /hekili and see if it is enabled.

I can tell you its not showing up normally lol.  It disappears shortly after starting any fight.  I have zero buttons on my screen to press.

**Comment by marekCs** [comment]
ok once again, everything works as it should, rotation 1 minute. Just update your addon to 7.2 you have still 7.1.

**Comment by Hekili** [comment]
There's a priority adjustment I need to make -- the `pop_wounds` variable is built around you having Apocalypse and you don't.  Thanks for the snapshot; will fix.

**Comment by Hekili** [comment]
Will post a fix soon.

**Comment by basalt51** [comment]
Since this is closed does that mean its fixed? I am having this issue.

**Comment by Hekili** [comment]
Feel free to provide updated information for me to review.
