### ISSUE TITLE
Fury Warrior rotation reccomends Whirlwind when its not needed.

### ISSUE THREAD

**Issue by Dorfess** [Hekili/hekili#1882]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Reccomends Whirlwind when fighting a single target and I have all abilities up still.

### How to Reproduce

Honestly I tried to recreate it for 1 hour last night and couldnt but I was able to snap shot it today.

### Talent Loadout

BgEAtml4yL3PsSlRlqnvTeVx4HAAAAAAAAAAAQCKJEEBhIwB0ISICSQIJkkIRCgkkEKpFAJJBAAAA

### Snapshot

https://pastebin.com/3Zucam16

### Contact Information

Dorfess#7215

**Comment by Hekili** [comment]
> Reccomends Whirlwind when fighting a single target and I have all abilities up still.

I've reviewed the snapshot; you had nothing else to use but Whirlwind at that time.  Bloodthirst was on cooldown for another 1.64 seconds which left room for only Whirlwind as filler.
