### ISSUE TITLE
Beastmastery Hunter - Bestial Wrath?

### ISSUE THREAD

**Issue by Matze0001** [Hekili/hekili#1883]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I am using Hekili out of the box. Simple questin: Bestial Wrath does not show up - why is that? Bug or my fault having overseen something?

### How to Reproduce

Normal fight, nothing special, Bestial Wrath does not show up (at least for me)

### Talent Loadout

B0PAIlFMjeNhnEouGfV8Ij2uS5AgSCAQAAAAAAAAAAAoRkiAJRQCRChQkQCHQSEI5ARA

### Snapshot

https://pastebin.com/fxNZbqhT

**Comment by marekCs** [comment]
You have off your cooldowns in Hekili settings.

**Comment by Matze0001** [comment]
OMG, thanks, thats it...

Am Sa., 5. Nov. 2022 um 10:46 Uhr schrieb marekCs ***@***.***

**Comment by Hekili** [comment]
Yeah, for the record, the addon starts with cooldowns disabled because using them on CD will end up being suboptimal in actual gameplay outside of a Patchwerk fight.  Think of fights like Sludgefist -- if you use CDs on pull and don't have them after his charges, your CDs may be on cooldown when he is vulnerable and taking more damage.

**Comment by Matze0001** [comment]
Got it - thanks for the immediate reply! Cheers, Mat

Am Sa., 5. Nov. 2022 um 14:28 Uhr schrieb Hekili ***@***.***>:
