### ISSUE TITLE
Error when trying to use Edit Mode for UI

### ISSUE THREAD

**Issue by archxlock** [Hekili/hekili#1884]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When hitting Esc and entering Edit Mode for the WoW UI, I get the following error...

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Hekili' tried to call the protected function 'TargetUnit()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/EditModeManager.lua"]:1513: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1457: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

### How to Reproduce

1. Hit Esc
2. Click Edit Mode
3. Error Appears

### Player Information (Link)

```Text
build: v10.0.0-07.3
level: 60 (60)
class: WARLOCK
spec: affliction

talents: none

pvptalents: none

covenant: night_fae

conduits: borne_of_blood = 1
   condensed_anima_sphere = 1
   fel_celerity = 1
   fel_commando = 1
   resolute_barrier = 1
   soul_eater = 1

soulbinds: [dreamweaver]
   dream_delver = 1
   field_of_blossoms = 1
   podtender = 1
   somnambulist = 1
   soothing_voice = 1
   waking_dreams = 1

sets: enforcers_stun_grenade = 1

gear: acolytes_shirt = 1
    cabalists_hymnal = 1
    enforcers_stun_grenade = 1
    grasps_of_the_clairvoyant_sage = 1
    grimveiled_bracers = 1
    horns_of_the_demon_star = 1
    leggings_of_the_demon_star = 1
    logic_loop_of_recursion = 1
    maledict_opus = 1
    mantle_of_manifest_sins = 1
    mantle_of_the_demon_star = 1
    overclocking_bit_band = 1
    purple_trophy_tabard_of_the_illidari = 1
    robes_of_the_demon_star = 1
    shadowghast_necklace = 1
    stolen_nathrian_slippers = 1
    waistwrap_of_the_demon_star = 1

legendaries: decaying_soul_satchel = 1
    wilfreds_sigil_of_superior_summoning = 1

itemIDs: 110017, 169158, 169159, 173249, 178927, 183033, 184028, 186288, 186406, 188884, 188886, 188887, 188888, 188889, 189823, 31405, 6097

settings: none

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 

warnings: none
```

### Error Messages (Link)

```Text
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Hekili' tried to call the protected function 'TargetUnit()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/EditModeManager.lua"]:1513: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1457: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>
```

### Contact Information

Archxlock#4915

**Comment by Hekili** [comment]
The addon never calls TargetUnit; this is a taint issue caused by another addon.
