### ISSUE TITLE
More powerful spell active

### ISSUE THREAD

**Issue by JimA1966** [Hekili/hekili#1885]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When ever between the eyes and pistol shot I constantly get a more powerful spell active warning
[issue.txt](https://github.com/Hekili/hekili/files/9944407/issue.txt)

### How to Reproduce

enter game as outlaw rogue
go through rotation
between eyes and pistol shot 
get warnings

### Player Information (Link)

```Text
build: v10.0.0-07.3
level: 60 (60)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    adrenaline_rush = 1/1
    alacrity = 2/2
    blade_flurry = 1/1
    blind = 1/1
    cheat_death = 1/1
    cloak_of_shadows = 1/1
    combat_potency = 1/1
    combat_stamina = 1/1
    count_the_odds = 2/2
    deadly_precision = 2/2
    deeper_stratagem = 1/1
    devious_stratagem = 1/1
    dreadblades = 1/1
    evasion = 1/1
    fan_the_hammer = 2/2
    fatal_flourish = 1/1
    feint = 1/1
    fleet_footed = 1/1
    gouge = 1/1
    grappling_hook = 1/1
    greenskins_wickers = 1/1
    heavy_hitter = 1/1
    hit_and_run = 1/1
    improved_adrenaline_rush = 1/1
    improved_main_gauche = 2/2
    improved_sprint = 1/1
    leeching_poison = 1/1
    loaded_dice = 1/1
    numbing_poison = 1/1
    opportunity = 1/1
    quick_draw = 1/1
    restless_blades = 1/1
    roll_the_bones = 1/1
    ruthlessness = 1/1
    sap = 1/1
    seal_fate = 2/2
    shadowstep = 1/1
    shiv = 1/1
    thiefs_versatility = 2/2
    tight_spender = 1/1
    tricks_of_the_trade = 1/1
    vigor = 1/1
    virulent_poisons = 1/1
    weaponmaster = 1/1

pvptalents: none

covenant: venthyr

conduits: condensed_anima_sphere = 1
   count_the_odds = 1
   lashing_scars = 1
   nimble_fingers = 1
   quick_decisions = 1
   triple_threat = 1

soulbinds: [theotar_the_mad_duke]
   exquisite_ingredients = 1
   leisurely_gait = 1
   life_is_but_an_appetizer = 1
   party_favors = 1
   soothing_shade = 1
   token_of_appreciation = 1

sets: dreadfire_vessel = 1
    salvaged_fusion_amplifier = 1
    wraps_of_electrostatic_potential = 1

gear: amulet_of_the_last_guardian = 1
    cruciform_veinripper = 1
    daschlas_defiant_treads = 1
    decadent_nathrian_shawl = 1
    dreadfire_vessel = 1
    edge_of_night = 1
    logic_loop_of_division = 1
    salvaged_fusion_amplifier = 1
    signet_of_collapsing_stars = 1
    soulblade_guise = 1
    soulblade_leathers = 1
    soulblade_leggings = 1
    soulblade_nightwings = 1
    umbrahide_gauntlets = 1
    umbrahide_waistguard = 1
    wraps_of_electrostatic_potential = 1

legendaries: concealed_blunderbuss = 1
    obedience = 1

itemIDs: 142207, 169069, 169157, 172316, 172320, 184030, 184778, 185813, 186299, 186388, 186398, 186432, 188901, 188902, 188903, 188905

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Outlaw
    petbased = false
    potion = potion_of_spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    dirty_gouge = false
    mfd_points = 4
    solo_vanish = true

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    adrenaline_rush                  = 5   [01], 5   [07]
    ambush                           = 7   [01], N2  [06], 7   [07]
    between_the_eyes                 = 3   [01]
    blade_flurry                     = 9   [01]
    dispatch                         = 6   [01], 6   [07]
    dreadblades                      = 0   [01]
    dreadfire_vessel                 = N5  [06]
    flagellation                     = =   [01]
    gouge                            = N4  [06]
    kick                             =
    kidney_shot                      = N6  [06]
    pistol_shot                      = 4   [01]
    roll_the_bones                   = 2   [01], 2   [07]
    salvaged_fusion_amplifier        =
    sinister_strike                  = F   [01]
    slice_and_dice                   = 8   [01], 8   [07]
    wraps_of_electrostatic_potential = -   [01]

warnings: none
```

### Error Messages (Link)

```Text
no issue
```

### Contact Information

Asgar#6151

**Comment by Hekili** [comment]
> When ever between the eyes and pistol shot I constantly get a more powerful spell active warning

Can you elaborate on this?

Are you saying that when the addon is recommending Between the Eyes, you try to press the button and the game says "A more powerful spell is active"?  Is that right?

**Comment by JimA1966** [comment]
yes

**Comment by JimA1966** [comment]
![World of Warcraft 11_5_2022 5_09_26 PM](https://user-images.githubusercontent.com/116915094/200141440-e098d09f-6363-469f-a776-bf339359de4f.png)
here is screen shot

**Comment by JimA1966** [comment]
I think it has something to do with roll the bones because when I try and cast the suggestions flicker a lot and give me the A more powerful spell warning

**Comment by Hekili** [comment]
Do you have anything macroed to those abilities?

**Comment by JimA1966** [comment]
No I do not, no other abilities macroed to the spell keys.  I only macro Items on top keys like kick F thru = are key press only
***@***.***
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Hekili** [comment]
I genuinely have no idea.  The addon itself doesn't trigger that message.  Your screenshot indicates Sinister Strike is recommended and you only have two combo points.  I wonder if this is happening when you cap out on Flagellation stacks.  Regardless, I don't know that I can do anything about this issue.

**Comment by Sedveth** [comment]
That text only happens if you try to cast SnD while the remaining duration last longer than the new one. So probably something's wrong with your keybinds. Fix your keybinds I guess

**Comment by JimA1966** [comment]
Unfortunately I have nothing macroed to my spell cast keys just remapped to my orbweaver.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by JimA1966** [comment]
Fixed this one, keybinds overlaping thank you

**Comment by Hekili** [comment]
Thanks for updating!
