### ISSUE TITLE
Recommending Slice & Dice on opening with no CP but also no shadowmeld recommendation

### ISSUE THREAD

**Issue by OfficialExiled** [Hekili/hekili#1887]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Every opening the Outlaw rogue recommends me start with Roll the dice then Slice and Dice, but we have no other way to start Slice and Dice except being Blood Elf with racial power, and im Night elf atm. But in addition, Shadowmeld is not recommended anymore in the rotations at all. This is even when Allow Shadowmeld is checked. Or could shadowmeld be not recommended due to no dps gain because we dont use Nightstalker talent anymore? hmm not sure about this one actually. 

### How to Reproduce

Probably Slice & Dice can be placed around after using Flagellation, so Ambush - Sinister Strike - Flagellation - Slice & Dice - Dreadblades - Between the Eyes , etc. 

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAABJBQSCJtkkIJBSISAkIAAAAAAAJBpRJJIJJpFAAAA

### Snapshot

https://pastebin.com/rC5r52PM

### Contact Information

Chani#0402

**Comment by Hekili** [comment]
Please test version 08.1 and let me know if you are still experiencing this issue.  Thanks.

**Comment by OfficialExiled** [comment]
Looks like Slice & Dice is now fixed thank you very much. Shadowmeld is still not showing but I guess its also there is no value of dps increase yet due to no Nightstalker talent. Anyways thanks for your hard work <3
