### ISSUE TITLE
Vengeance DH Metamorphosis

### ISSUE THREAD

**Issue by sociallyineptclownpc** [Hekili/hekili#1888]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When tanking the hekili mod does not properly track metamorphosis when it is on CD or when used. For example, combat starts, hekili suggests meta, player clicks meta, meta does not disappear from the priority suggestion. Player must cycle mod on and off using pause for it to go away and correctly cycle priority. When combat is initiated with Meta on CD hekili continues to suggest using meta and will not properly cycle the priority list. 

### How to Reproduce

1. Enter LFG dungeon as Vengeance.
2. Enter combat
3. use Metamorphosis
4. Meta is now on cooldown
5. enter new combat state
6. see meta suggested while on CD

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPTRCIhIItkEJJCEAAAAAAAtIBkCJJFIkWESSkEE

### Snapshot

cannot print screen with keyboard

### Contact Information

drachenacht1989@gmail.com

**Comment by jmusick** [comment]
Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

    Log into your WoW character.
    Recreate the issue you are reporting (i.e., generate 5 Holy Power).
    When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
        You can change these keybindings in /hekili > Toggles if needed.
        If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
    Type /hekili and press Enter.
    Open the Snapshots section on the left side.
    Select the snapshot that shows the recommendation that you disagree with.
        Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
    Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
    Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
    Provide the Pastebin link below.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.
If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
Closing; required snapshot was not included.
