### ISSUE TITLE
MM Hunter Dungeon Spamming Steady Shot

### ISSUE THREAD

**Issue by GitHubberino247** [Hekili/hekili#1889]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Seems that running through a dungeon, the rotation sticks to spamming steady shot. Bosses can be ok after popping CDs. I am running a PvP talent build I yoinked off the armory but I don't think that should make it prioritize Steady Shot over everything else while at full focus. 

My guess is something to do with AoE but not having AoE abilities to use 

/shrug

### How to Reproduce

Pick Marksman Hunter
Do dungeon
Pull trash 
Get past Steel Trap, Volley and Death Chakram
Recommends nothing but Steady Shot

### Talent Loadout

B4PAIlFMjeNhnEouGfV8Ij2uSJgWAIBCAAAAAIJEJSigQk0iQhkoAaCJRIhDEKAAAAAC

### Snapshot

https://pastebin.com/ExVMJV7B

**Comment by Hekili** [comment]
Thanks for the ticket.  This will be resolved in 08.1.
