### ISSUE TITLE
Demonology - Cannot cast Demonic Strength because Felguard is missing

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1891]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The addon recommends Demonic Strength but I can't cast it and the in-game AI gives an error that felguard is missing.

### How to Reproduce

Go as Demo and try rotation on dummies.

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3gESSkIBSLtUCSjkQaBAAAAAtIJJBgkIRSSRLJJIAAAAAAA

### Snapshot

https://pastebin.com/aFt37jJ6

**Comment by Hekili** [comment]
Thanks, I'll add the Felguard check back to Demonic Strength.

**Comment by marekCs** [comment]
Everything works quite well now, thank you (only pity that the resulting Demo is not as OP as I expected, a number of melees will turn it over :))).

**Comment by marekCs** [comment]
Hmm, something is wrong, no Soul Strike or Implosion during 2 minutes fight. My talents BoQAbtPS25JQs0VfQSDmhm+p3AhkEJSgItIItkkQaBAAAAAlIIhQikISi0SLJSIAAAAAAA

**Comment by Hekili** [comment]
> Hmm, something is wrong, no Soul Strike or Implosion during 2 minutes fight. My talents BoQAbtPS25JQs0VfQSDmhm+p3AhkEJSgItIItkkQaBAAAAAlIIhQikISi0SLJSIAAAAAAA

You will need to supply an updated snapshot; talents alone don't help.  Take a snapshot (or multiple!) when you think Soul Strike should be recommended or Implosion should be recommended, but isn't.  Label each snapshot and link them in a new comment.

Also, to help me understand:  How is your comment about Soul Strike and Implosion related to the original Demonic Strength issue?

**Comment by marekCs** [comment]
The problem is that I don't know when exactly what should be better recommended. I'm not a pro warlock. And simulationcraft still doesn't run. So sorry for the bad ticket in your eyes. I just felt like Demo should be spinning more. Maybe a ticket with Hands of Guldan as someone posted will solve that.
