### ISSUE TITLE
Vegenance demon hunter Infernal strife stuck on.

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#1893]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When attacking the Doomwalker when the leap comes up even though I've used it twice and tis in cooldown hekili still says to use it as the next skill.
![WoWScrnShot_110622_125324](https://user-images.githubusercontent.com/1850089/200189894-406c2314-48f5-4045-a01f-533d791d04d0.jpg)

### How to Reproduce

Log in as vengenance demon hunter, go to doomwalker anniversary boss event and attempt to kill it.

### Talent Loadout

doesn't copy anything

### Snapshot

https://pastebin.com/VwQhNRtt

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iP1Ck87C53w9vvQWqueipR

**Comment by Hekili** [comment]
Where in your screenshot is it saying to use Infernal Strike?  The snapshot you provided is recommending Fiery Brand and The Hunt.

You will have to provide your Talent Loadout and a Snapshot that is taken when you're experiencing the issue you're reporting, or else I cannot do anything to investigate the issue.

**Comment by N6REJ** [comment]
I'm so sorry, I got my icons mixed up.  That explains everything.

> You will have to provide your Talent Loadout and a Snapshot that is taken when you're experiencing the issue you're reporting, or else I cannot do anything to investigate the issue.
Right this minute you can't share talent loadouts.. it says its is copied but nothing is in the clipboard.  At least not for me.
