### ISSUE TITLE
Enhancement - Lightning (and earth) shield recommendation is missing when they expire mid combat.

### ISSUE THREAD

**Issue by Ashgaion** [Hekili/hekili#1894]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Thank you for adding the support to cast earth shield if it's missing in the pre-combat checks.
However i have noticed that both Lightning shield and earth shield can run out in combat, and hekili will not tell you to recast them in combat.

Earth shield cooldown i can imagine (would be nice though, to be able to configure that), but if the Lightning shield buff is missing, i will miss dps. Can you make sure it will suggest recasting lightning shield if it expires mid combat?

All your hard work is much appreciated!
Thank you!

### How to Reproduce

Go as enhancement, start combat with lightning shield (or earth shield, or both) on (on a dummy for instance).
Dismiss the buff(s) (right click)
See that hekili does not recommend recasting lightning shield (or earth shield, or both)

### Snapshot

https://pastebin.com/g8rHw9WE

### Contact Information

Discord : Ashgaion#8352

**Comment by Hekili** [comment]
These should be available to refresh in combat in 08.5.

**Comment by Ashgaion** [comment]
Thank you for the hard work!

Op wo 9 nov. 2022 00:03 schreef Hekili ***@***.***>:
