### ISSUE TITLE
[REC] Demonology - Soul Rot is not recommended

### ISSUE THREAD

**Issue by Deathhunt** [Hekili/hekili#1896]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In 10.0 pre-patch server, Soul Rot is not recommendaed for Demonology warlock.

### How to Reproduce

1. Enter game as as a Demonology warlock.
2. Switch to night fae.
3. Test it.

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3AIJRiEINSJINJJkGAAAAA0CIRCQIkkItkIhAAAAAAA

### Snapshot

https://pastebin.com/4R7GG04V

**Comment by Hekili** [comment]
This should be available in 08.5.
