### ISSUE TITLE
Spinning Crane Kick not being recommended at all unless Dance of Chi-Ji is up

### ISSUE THREAD

**Issue by Alpha0o** [Hekili/hekili#1897]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Spinning Crane Kick not being recommended at all unless Dance of Chi-Ji is up no matter how many targets are present.

### How to Reproduce

1. Enter Game as a Windwalker Monk.
2. Take Widening Whirl, Mark of the Crane, Dance of Chi-Ji, Crane Vortex, and Fast Feet talents.
3. Get 5 Mark of the Crane stacks.
4. Cast Summon White Tiger Statue, Invoke Xuen, the White Tiger, Storm, Earth, and Fire, and Bonedust Brew.

### Talent Loadout

B0QAdeydY63Y4XKaboK13uRRQAAAAAAAAEJRSSUiIRAAAAAiAkAkkkkGpECJJSkkkEAAAA

### Snapshot

https://pastebin.com/sGBPqbHv

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/eEckzkYW8GD2TG9zbRkVvF

### Contact Information

Feladdon#0631

**Comment by Hekili** [comment]
If the issue you are experiencing is that SCK isn't being recommended without Dance of Chi-Ji, you should supply a snapshot taken when you think SCK should be recommended but Dance of Chi-Ji is not up.

In your snapshot, Dance of Chi-Ji is up and SCK is the first recommendation.  I need a snapshot where the issue you're reporting is happening instead.  Thanks!

**Comment by Alpha0o** [comment]
https://pastebin.com/ZLJAH2n3
sry... fixed :) To explain more, SCK doesn't get recommended as a spender not matter how many targets are present inside or outside cooldowns in general unless a Dance of Chi-Ji proc is up. In this snapshot, SotWL is on CD, I have 6 stacks of Hit Combo, I have 5 stacks of Mark of the Crane (The SCK modifier should be at maximum). However, RSK is my first recommendation with 8 targets and BDB up while not playing WDP, so there is no point of using RSK.

**Comment by Hekili** [comment]
Thanks, the snapshot helps.  There's a new expression related to Spinning Crane Kick in SimC that I have not yet modeled in the addon.  I'll be working on this today.

**Comment by Hekili** [comment]
I've added the missing expression and brought in an updated priority list; will post in 08.5.

**Comment by Alpha0o** [comment]
Thanks for your assistance :)

**Comment by fzarr** [comment]
I was interested in what this expression was so took a look at the commit and noticed this line of code:

`mod = mod * 1 + ( t.count * ( conduit.calculated_strikes.enabled and 0.28 or 0.18 ) )`

Just thought I'd highlight a possible bug here since the `* 1` doesn't seem like its doing anything. I did not test to see if this is causing an issue in-game.

Sorry if this isn't the right place for this or it feels like an unwanted criticism!
