### ISSUE TITLE
Balance druid stopped showing swap target

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1899]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After last update Balance druid stopped showing swap target (of all dots like he did before). I'm not sure if this is completely from the last update or the one before last.

### How to Reproduce

Enter the game like Balance druid and make AOE rotation on dummies.

### Snapshot

https://pastebin.com/StMV2xTb

**Comment by Hekili** [comment]
For **Describe the Issue** / **How to Reproduce**, I need you to provide more specific detail.  Which specific dot, at the time you took the snapshot, do you think should've been recommended on a different target?

You will also need to provide your Talent Loadout; it's not really optional.  Thanks.

**Comment by Hekili** [comment]
I was able to diagnose this as being related to recent script changes.  I'm going to post a new 08.4 release that seems to resolve it.

**Comment by marekCs** [comment]
it works thx
