### ISSUE TITLE
Cooldown Usage Suggestion

### ISSUE THREAD

**Issue by Shaggypaws** [Hekili/hekili#190]
Please describe your idea or feature and when it would be useful.
I would like to have the ability to scale my usage of Cooldowns on mobs based on how much HP they have. I play monk and when im world questing I do not need suggestions on non elite mobs for example. Having the options to have cooldowns be dynamic based on mob HP or even simply if it is elite or not would be a huge help.

**Comment by Zarggg** [comment]
I generally just toggle Cooldown Display on/off depending on whether I'm fighting an elite/boss mob or not. You can even keybind it.

**Comment by Hekili** [comment]
If you wanted to write a custom priority for something like this, you could.  I don't see where it needs to be build-in, given that you have the ability to turn CDs on/off via a toggle like @Zarggg mentioned.
