### ISSUE TITLE
Hand of Guldan at 1 Shard.

### ISSUE THREAD

**Issue by Lejes9X** [Hekili/hekili#1902]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In the Demonology Priority, after summoning Tyrant and if cooldowns are off and not spec'd into Nether Portal, Hand of Guldan is suggested to cast at less than 3 shards.

### How to Reproduce

1. Enter game as Demonology Warlock.
2. Have talent into Demonic Tyrant
3. Rotation as normal to summon Tyrant.
4. Rotation uses all shards then only suggests using Hand of Guldan at 1 shard from then onwards.

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3AIJRiEi0IISTSCpBAAAAAlASIgkISSItkkgAAAAAAA

### Snapshot

https://pastebin.com/BkE4JLN7

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/g8mrAErfDNmPKZbWU3V1zr

### Contact Information

Fayeshara#4867

**Comment by Lejes9X** [comment]
Hand of Guldan will also be suggested after a Demonic Core Demonbolt cast as well but never at 2 or 3 after that.

**Comment by Hekili** [comment]
Thanks, this is an issue with `variable` entries that I'm working to resolve.

**Comment by Lejes9X** [comment]
Narrowed it down to this
Hand of Gul'dan - soul_shard >= 1 & variable.next_tyrant_cd < gcd.max & time > variable.first_tyrant_time - gcd.max
Once its disabled the priorities go back to suggesting 3 shard Hand of Gul'dan.

**Comment by Hekili** [comment]
I know; that's not the underlying issue but I'm fixing it now.

**Comment by Hekili** [comment]
Actually, it's both issues.  I've adjusted the APL per your recommendation, and have revised scripting again.  I'm completing other testing and will post a release tonight.

**Comment by Hekili** [comment]
This should be resolved in 08.3 (the new release, just posted).  There is still some potential for weirdness, so I'll leave this open for now.  I needed to keep that entry in the APL with additional conditions so that it can be used as the "last HoG before summoning a Tyrant" regardless of shards.  Let me know if you see weirdness.
