### ISSUE TITLE
[Wotlk] Feral - Maul

### ISSUE THREAD

**Issue by Solmyrus** [Hekili/hekili#1903]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Classic (Wrath of the Lich King)

### Feature Request

Hello,
I can't find Maul in selection of spells in priorities. Is possible use maul in rotation in actual version (and I make some fail)?

**Comment by Hekili** [comment]
Yes, Druid for WotLK is not complete.  I will not be working on it again until after all specializations are in Dragonflight.  You are correct that Maul is missing from the ability list at this time.

**Comment by Supernuss** [comment]
should be fixed since #1865 ; issue could be closed
