### ISSUE TITLE
Reccomending Whirlwind when Raging blow is up.

### ISSUE THREAD

**Issue by Dorfess** [Hekili/hekili#1905]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In a single target fight hekili is reccommending whirlwind uses when I still have 3 Raging Blow charges up. Atleast on wowhead and from personal use I cant imagine using whirlwind before raging blow in a single target fight.

### How to Reproduce

1.Enter game as fury warrior 
2.Hit a solo target dummy
3. Should see it reproduce quite quickly.

### Talent Loadout

BgEAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAQCKJEEBhIwB0ISICSQIJkkIRCgkkEKpFAJJBAAAA

### Snapshot

https://pastebin.com/buk2NGy7

### Additional Information

Last time I posted about this you said everything was on cooldown but I can confirm 100% I still had raging blows available and it still reccommends whirlwind heres a 2nd example of this happening. https://pastebin.com/6Hda4Y9p

### Contact Information

Dorfess#7215

**Comment by Hekili** [comment]
Thanks, this will be resolved in 08.6 today.  I appreciate the snapshots and explanation.
