### ISSUE TITLE
WW Monk Fealine stomp doesnt get recommended

### ISSUE THREAD

**Issue by Aliemaxi1** [Hekili/hekili#1907]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Fealine Stomp doesnt get recommended at all from Hekili

### How to Reproduce

1. Enter Game as Windwalker Monk
2. Have Nightfae as Covenant
3. Have Fealine Stomp as covenant with unity legendary
4.  Fealine stomp doesnt get recommended in ST or AOE

### Talent Loadout

B0QAdeydY63Y4XKaboK13uRRQAAAAAAAAESkkElkIRAAAAAJJRAASSCkSkQSiEJJJhCAAAA

### Snapshot

https://pastebin.com/FEruJ7W5

### Additional Information

Nothing to ad

### Contact Information

๖ۣۜℜaͥgeͣgͫⱥ͢͢͢ming#3214

**Comment by Hekili** [comment]
This should be resolved in 08.7.
