### ISSUE TITLE
[Retail] Mage priorities not showing

### ISSUE THREAD

**Issue by JH2535** [Hekili/hekili#1908]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Log in, the primary display is not there. right click the hekilli icon (to get the options) and there are no priorities listed. (Note I posted the character data from the issue reporting, but it doesn't show any tellents selected. I do have talents selected) Here is my exported talents: `B8DAHVkVsxxZrVqBmAzlSR2f7nAAEIJFRk0EiICBAAAAAAAAAIJJCoASQSSSAAAAA`

![image](https://user-images.githubusercontent.com/9281336/200974964-07b0abc5-87ae-4138-9871-38b173deadb2.png)

### How to Reproduce

1. Enter the game as a mage (possibly a lower level one (I'm 49)
2. Hekili's display is not sowing, right click the hekili icon and see that there are no priorities as seen in the image above.

### Player Information (Link)

```Text
build: v10.0.0-08.7
level: 49 (49)
class: MAGE
spec: fire

talents: none

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: ancient_bloodmoon_cloak = 1
    dastardly_bracers = 1
    dignified_headmasters_charge = 1
    discerning_eye_of_the_beast = 1
    dread_pirate_ring = 1
    elders_boots = 1
    eternal_horizon_choker = 1
    red_linen_shirt = 1
    skycaller_sash = 1
    solstone_ring = 1
    stormwind_tabard = 1
    tattered_dreadmist_leggings = 1
    tattered_dreadmist_mantle = 1
    tattered_dreadmist_mask = 1
    tattered_dreadmist_robe = 1
    unsanitary_gloves = 1

legendaries: none

itemIDs: 122250, 122256, 122262, 122353, 122360, 122362, 122384, 122529, 122664, 153690, 160179, 2575, 45574, 58981, 59008, 7354

settings: none

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 

warnings: none
```

### Error Messages (Link)

```Text
No error message showing.
```

**Comment by Hekili** [comment]
Your specialization is not supported in Dragonflight (yet).  This information is presented to you when you log into the game, and is also shown if you open the addon menu.  All classes/specializations will be supported, but it takes time to implement all the new talents and nuances.  Thank you for being patient.
