### ISSUE TITLE
[Ret] Inquisition not shown during Avenging Wrath

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#191]
**Describe the Bug/Issue**
Because of how the priority list is set up, Inquisition is never shown when Avenging Wrath is active. Instead, the APL entry depends on refreshing Inquisition just before using Avenging Wrath. This might work for simulations, but is not good for real fights where you might need to delay Avenging Wrath.

This is the full Inquisition condition. The very first line is the problem:

```
buff.avenging_wrath.down &
( buff.inquisition.down |
buff.inquisition.remains < 8 & holy_power >= 3 |
talent.execution_sentence.enabled & cooldown.execution_sentence.remains < 10 & buff.inquisition.remains < 15 |
cooldown.avenging_wrath.remains < 15 & buff.inquisition.remains < 20 & holy_power >= 3 )
```

I suggest to make a special case for this where you don't follow the SimC APL.

**To Reproduce**
- Get in combat as Ret with the Inquisition talent.
- Note that Inquisition is suggested.
- Cast Avenging Wrath.
- Note that the Inquisition suggestion vanishes.

**Expected behavior**
Inquisition should always be suggested if it is down or expiring soon.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:** https://pastebin.com/YjzYDFqs

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:** https://pastebin.com/ZbSCYh4B

**Comment by Hekili** [comment]
You make a reasonable case here and it comes up in other specs occasionally.  Still, not wise to AW without having Inquisition up for the duration.  But, if you make this mistake, maybe the addon should help you recover.

**Comment by cremor** [comment]
Another comment about the problematic condition:
The last line (as formatted by me) is also suboptimal when you need to delay Avenging Wrath because refreshing Inquisition when the buff still has more than 13 seconds left wastes a bit of the buff time. Maybe it would be a good idea to add a contition that checks if the cooldown toggle is enabled to both the first and last line of that condition?

**Comment by Hekili** [comment]
Your follow-up comment shouldn't be an issue.

`cooldown.avenging_wrath.remains` should be its max cooldown when CDs are disabled, unless you've removed Avenging Wrath from the toggle.

Got a snapshot of a problematic early refresh of Inquisition while CDs are toggled off?

**Comment by cremor** [comment]
I didn't actually test this, I just assumed it would be a problem. Sorry!
Good to know that `cooldown.remains` are at their max value if disabled.

**Comment by Hekili** [comment]
This should be resolved.
