### ISSUE TITLE
Elemental Shaman, recommending wrong spells and spells disabled.

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#1911]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After updating to the latest version, I noticed that Hekili has several spells disabled, (Meteor, Stormkeeper, Storm Elemental, etc..) It is also recommending the use of spells that are not ready for use, ie, not charged.

### How to Reproduce

1. Log into the game as Elemental Shaman
2. Go to target dummy.
3. Engage target dummy
4. Will recommend spells that are not charged after a few opening spells. 

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAA0atk0SSSRSLRDBFABAAAAAAlAkSSiUEFCSSSBgkAA

### Snapshot

https://pastebin.com/KanUjhfz

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3YAajS3odtrkVxM5qj2avA

### Contact Information

MrWizard516

**Comment by Hekili** [comment]
This is resolved in 09 and is also a duplicate ticket.
