### ISSUE TITLE
Priest NYI for Wrath Classic

### ISSUE THREAD

**Issue by tommaricle** [Hekili/hekili#1912]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

When I log in nothing from Hekili shows on my screen.  If I'm in the addon setup screen I see the objects showing behind the setup screen (like a shadow of what they'd look like if they were on the screen).  I've tried the 3 or 4 fix posts that are out there and nothing has fixed this issue for me.  

### How to Reproduce

load game and view that there's nothing from Hekili on screen

### Player Information (Link)

```Text
build: v3.4.0-1.0.0-beta9
level: 80 (80)
class: PRIEST
spec: priest

talents: none

pvptalents: none

covenant: none

conduits: none

soulbinds: none

sets: none

gear: band_of_channeled_magic = 1
    cowl_of_winged_fear = 1
    disguise_of_the_kumiho = 1
    encircling_burnished_gold_chains = 1
    fading_glow = 1
    gloves_of_glistening_runes = 1
    heigans_putrid_vestments = 1
    leggings_of_mortal_arrogance = 1
    mainhand = 1
    mainhand_2h = 1
    mark_of_the_war_prisoner = 1
    plush_sash_of_guzbah = 1
    preceptors_bindings = 1
    ring_of_holy_cleansing = 1
    staff_of_restraint = 1
    sundial_of_the_exiled = 1
    valorous_shoulderpads_of_faith = 1
    xintors_expeditionary_boots = 1

legendaries: none

itemIDs: 37172, 37873, 39250, 39252, 39409, 40234, 40245, 40398, 40450, 40455, 40680, 40682, 40696, 40719, 40723, 40750

settings: none

toggles:     cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = true 

keybinds:
```

### Error Messages (Link)

```Text
no visible error messages
```

### Contact Information

masmaricle@hotmail.com

**Comment by Hekili** [comment]
Yep, nothing loaded for Priest yet in Wrath.

**Comment by tommaricle** [comment]
I used Hekili in Retail and loved it.  Please let me know when there's something in WOTLK.
________________________________

**Comment by AnitaSinha** [comment]
> Yep, nothing loaded for Priest yet in Wrath.

And Why???

**Comment by SpatenLa** [comment]
because hekili is Not Yet Implemented in wrath.

**Comment by AnitaSinha** [comment]
but there is the beta, there are rotations available for most classes that work well, why hasn't one been created for the shadowpriest yet?

**Comment by vond82** [comment]
Because he put Wrath development on hold to make sure to get everything working properly for Dragonflight

**Comment by AnitaSinha** [comment]
is it possible to adjust the settings yourself without much effort?

**Comment by Hekili** [comment]
Classic will be done when it's ready; there's no need to keep an open ticket for this topic.  Thanks.
