### ISSUE TITLE
Request for support with Affliction Warlock (Retail)

### ISSUE THREAD

**Issue by Oxxinator** [Hekili/hekili#1913]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Affliction.

What is needed?  I can try to provide information.  I am not a programmer but I can dig up info from simulationcraft and wowhead/icy-veins.

### Contact Information

nowaydude85@gmail.com

**Comment by Hekili** [comment]
> What is needed?

Patience.
