### ISSUE TITLE
I am new player, Would you tell me that hekili v3.4 download link?

### ISSUE THREAD

**Issue by zhaoweizw2000** [Hekili/hekili#1915]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

I am new player. I don't find the hekili v3.4 update description html, please support link ? thank you!

### How to Reproduce

I am new player. I don't find the hekili v3.4 update description html, please support link ? thank you!

### Snapshot

no

### Contact Information

thank you

**Comment by Hekili** [comment]
All releases can be found on CurseForge/Wago/WoWInterface.
