### ISSUE TITLE
Add keybind sound

### ISSUE THREAD

**Issue by elvitusplay** [Hekili/hekili#1916]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

It would be interesting if the addon produces a sound when telling us which skill is next, for example if I have to cast moonfire and I have the spell assigned with the letter "C" the addon produces a sound saying the letter "Ci", with some google voice or something like that, sorry for my english

**Comment by Hekili** [comment]
This is not planned.  You can make similar audio cues with WeakAuras.  Thanks.
