### ISSUE TITLE
[Ret] Wrong suggestion for Focused Azerite Beam because of error in condition

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#192]
**Describe the Bug/Issue**
The default APL for Ret has a condition error in the line for Focused Azerite Beam. It checks if Avenging Wrath or Crusade is down, which is always true. The condition should be changed to "and".
I've already reported this to SimC (see simulationcraft/simc#4872) but they don't seem to fix it. Maybe you could make a special case for fixing it in the default APL of Hekili?

**To Reproduce**
- Equip the Focused Azerite Beam essence
- Use Avenging Wrath as Ret
- Note that Focused Azerite Beam is suggested

**Expected behavior**
Focused Azerite Beam shouldn't be suggested during Avenging Wrath.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:** https://pastebin.com/Bpi3J6vw

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:** https://pastebin.com/i4bkYzxK

**Comment by Hekili** [comment]
Makes sense.

**Comment by Hekili** [comment]
Sorry for the long wait.  Next build will include this.

**Comment by cremor** [comment]
FYI: SimC now fixed this in the latest batch of APL updates (with a slightly different solution). So the special handling for the default APL in Hekili can be removed again.
