### ISSUE TITLE
Fire mage - recommendation suddenly disappeared after Combustion

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1922]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Its current Beta btw. I wanted to test the full tree.
When I hit Combustion, spells disappeared from the prio list.

### How to Reproduce

Enter a game on Beta with these talents (I can borrow you the beta account) like Fire Mage and try rotation.

### Talent Loadout

B8DAHVkVsxxZrVqBmAzlSR2f7HJIRgkESxBQOQTiISSTCAAAAAAAAAQgEJKJJJHIRSSSSDAAAA

### Snapshot

https://pastebin.com/gaK92Dff

**Comment by Yakrel** [comment]
I can confirm bug, sometimes it's only showing 1 recommendation sometimes there is none.

**Comment by Hekili** [comment]
> I can confirm bug, sometimes it's only showing 1 recommendation sometimes there is none.

That may not be the same bug; I'd need a snapshot from when you have that happen to know for sure.

Fix for this bug will be in the next release.
