### ISSUE TITLE
Hekili suggestions not showing

### ISSUE THREAD

**Issue by Aalsaana** [Hekili/hekili#1925]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After switching from Shadow specialization to Discipline, the suggestion box no longer shows.

### How to Reproduce

1. enter game as Shadow Priest
2. change to discipline
3. suggestion box doesn't show

### Player Information (Link)

```Text
build: v10.0.0-09.1
level: 60 (60)
class: PRIEST
spec: discipline

talents: none

pvptalents: none

covenant: kyrian

conduits: charitable_soul = 1
   courageous_ascension = 1
   lights_inspiration = 1
   move_with_grace = 1
   shining_radiance = 1
   swift_penitence = 1

soulbinds: [pelagos]
   cleansed_vestments = 1
   combat_meditation = 1
   focusing_mantra = 1
   let_go_of_the_past = 1
   newfound_resolve = 1
   path_of_the_devoted = 1

sets: overflowing_ember_mirror = 1

gear: choker_of_the_pure_heart = 1
    choral_amice = 1
    choral_sash = 1
    clerics_linen_shoes = 1
    dimensional_oracular_wrists = 1
    egg_sac_robes = 1
    gloves_of_enraged_slaughter = 1
    gorewrought_drape = 1
    ineffable_spire = 1
    newcomers_gladiatorial_badge = 1
    overflowing_ember_mirror = 1
    salvaged_viperid_band = 1
    selfless_watchers_helm = 1
    shadowlace_trousers = 1
    sprigthistle_loop = 1

legendaries: none

itemIDs: 127605, 143908, 144107, 173219, 175713, 175725, 177657, 178153, 181638, 188011, 188037, 188045, 188050, 188417, 190751

settings: none

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = aoe 
    potions = false 

keybinds: 

warnings: none
```

### Error Messages (Link)

```Text
N/A
```

### Contact Information

darcilyn82@gmail.com

**Comment by pozzer18** [comment]
Healers are not supported currently so there it won't show.
