### ISSUE TITLE
Assassination Priorities and Small Inconsistencies 

### ISSUE THREAD

**Issue by GarvielTwo** [Hekili/hekili#1927]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Thoughts and observations in 4 target dummy combat assassination rogue.

1. At the start of the fight, Garrote is recommended 4 times!, the 4th time actually casts it as a non-empowered garrote, does not seem to keep in mind Improved Garrote 50% buff. This is true even if you have casted Indiscriminate Carnage and spread out garrote on all targets. Even in this case you can argue to cast garrote twice on a prio target to get more garrote duration but that should be the limit.
2. Something weird is happening with Vanish, it gets recommended quite early in the fight and instead of somehow following up with Improved Garrote it switches to some odd combo builder such as FoK. The only reason you would cast vanish if you don't have Master Assassin specced (which I did not) is to either do 3 single empowered garrotes or cast indiscriminate carnage and spread out empowered garrote that way) in my tests I saw Vanish then Garrote in the prio list but the moment I cast vanish the garrote goes away (mobs were fully garroted already)
3. Echoing reprimand gets recommended very late in an AoE fight, I would understand that would be the case if I did not have the Resounding Clarity talent, but I did, and I expect to sneak in an Echoing Reprimand in the first 10-15 seconds and try to fish for some empowered 7 combo point crimson tempests. However when I land on an empowered combo point I seem to get recommended Envenom in 4 targets instead of CT. I believe this is wrong. I can see envenom having a higher prio here if you are specced into poison bomb, dashing scoundrel and dragon t blades but I had none of those.
4. If I put atrophic poison, the first spell the addon recommends shows the icon for crippling poison, this is likely a bug.  
5. Indiscriminate Carnage is cast, it recommends a couple of things, then it gets to rupture, I cast the rupture, then it recommends garrote (all good so far) but as the second choice option after garrote, it shows me the Indiscriminate Carnage icon, like I would cast that after, even though it's already loaded. This is confusing, and it should not be shown. It also happens in reverse, if somehow it recommends garrote first, then it shows the icon for empowered rupture, and Indiscriminate Carnage after. I have attached a screenshot. 

I hope this helps, apologies for the abrupt writing, thank you for the amazing work so far!

### How to Reproduce

1. Is easy to reproduce just be starting a fight.. it always does that.
2. This is also easy to notice just by following the recommended rotation and see how vanish jumps around.
3. This is a personal opinion, it's possible that it's not optimum to cast it that often, but it feels strange to me.
4. Just cast atrophic poison and it will show the recommendation for crippling poison right away
5. this happens with the 2nd or 3rd cast of IC during a fight, never with the first one, just continue a regular rotation and wait until IC is recommended again, cast it and it will show up. I also did a snapshot and screenshot can be found here https://snipboard.io/KGjRNn.jpg

### Talent Loadout

BMQAOB/7AZ//CwQOf4fPMswHVDJSSEJRJBAAAAAAQSAQCAAAAAAAhkGkgkkkWgAJJJRCA

### Snapshot

https://pastebin.com/SV57UW9K

**Comment by Hekili** [comment]
You will need to provide snapshots for each item in your list.  Snapshots need to be taken when you are experiencing the specific issue(s) you are reporting.  Which issue were you seeing when you took the snapshot you provided?

A snapshot is required to diagnose this issue.

# Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by GarvielTwo** [comment]
Hello,

The snapshot is for the 5th point.

I believed the others can be easy to replicate but I will look to provide snapshots for all of them.

Thank you,

**Comment by GarvielTwo** [comment]
https://pastebin.com/ijzQsgEs - snapshot for point 4 - I have Atrophic Poison on, yet the addon recommends crippling, does not detect the Atrophic.
https://pastebin.com/cA33Zzja - snapshot for point 3 - when I have seen Echoing Reprimand first recommended in the list, again this might be personal preference but I feel it's recommended very late in the rotation.
https://pastebin.com/iXXxNesD - snapshot for point 2 - not sure how to best capture this, it recommended vanish, then it was immediately swapped with FoK, snapshot taken after FoK was recommended and after Vanish... vanished.
https://pastebin.com/J7SzBGws - snapshot for point 1 - this was in single target and I took the snapshot when it recommended the 4th garrote in a row on the same target.

Thank you,

**Comment by Hekili** [comment]
Thanks.

For your 5th item, I think the issue you're describing is that Indiscriminate Carnage will go on cooldown after you spend the second "buff" (even though there is only one buff).  Is that accurate?

**Comment by Hekili** [comment]
Can you please provide a Raidbots sim of your character for your 1st item, with the same talents selected and in a Patchwerk fight?

**Comment by GarvielTwo** [comment]
For the 5th item - Indiscriminate Carnage only goes on cooldown after you spend the second "buff" correct. After you cast it you now have 1 IC Garrote and 1 IC Rupture that you are allowed to cast and it gets spread to 8 targets.

However, in a 2-3 minute fight, the addon recommends to cast IC a second time (around the 1 minute mark), I then get recommended an IC garrote (all good so far), I cast the IC garrote and I still have an IC Rupture. At this point I still have the IC buff. The IC spell has not gone on cooldown.  So the addon next recommends the remaining IC Rupture. (again, all good, this is expected) - however, the next spell recommendation after this IC Rupture, is the Indiscriminate Carnage spell itself. I captured a screen shot showing this. https://snipboard.io/KGjRNn.jpg 

So IC gets recommended in the second slot, but you will never be able to cast it, since the moment you cast the IC Rupture, IC goes on cooldown. My callout is that this might be confusing, to recommend a spell in the second slot, that you will not be able to cast.

I hope all of that makes sense.

For the first point, here is the request raibots link : https://www.raidbots.com/simbot/report/fqmcF39HJ7NoWBSXESdacR

**Comment by Hekili** [comment]
1st, 4th, and 5th points will be resolved in next release.


## 2

> [pastebin.com/iXXxNesD](https://pastebin.com/iXXxNesD) - snapshot for point 2 - not sure how to best capture this, it recommended vanish, then it was immediately swapped with FoK, snapshot taken after FoK was recommended and after Vanish... vanished.

Your original question was about Vanish being recommended followed by FoK instead of making use of Improved Garrote.  In your snapshot, you didn't use Vanish and it's recommending FoK, but you described that it was recommending Vanish but changed to FoK before it got to it.  Am I misunderstanding?

With the snapshot provided, I would guess that Vanish was recommended but you got a free Combo Point which made Vanish's criteria no longer met.

<details>
<summary>Why Vanish isn't recommended.</summary>
48.  vanish ( vanish - 2 )

        The action (vanish) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( cds ) called from ( Assassination:default:7 ) would PASS at 0.00.
        NONE
        List ( vanish ) called from ( Assassination:cds:29 ) would PASS at 0.00.
        ! stealthed.all[false] & master_assassin_remains[0.00] = 0
         - this entry's criteria FAILS: talent.improved_garrote.enabled[true] & cooldown.garrote.up[true] & ! debuff.garrote.exsanguinated[false] & dot.garrote.pmultiplier[1.00] <= 1 & ( debuff.deathmark.up[false] | cooldown.deathmark.remains[0.00] < 4 ) & combo_points.deficit[3.00] >= ( spell_targets.fan_of_knives[4.00] >? 4 )

The relevant part is `combo_points.deficit[3.00] >= ( spell_targets.fan_of_knives[4.00] >? 4 )` -- the latter part means your Combo Point deficit should be greater than or equal to the higher value of 4 vs. FoK's targets (which is also 4).

If you just procced a free Combo Point, that would've shifted your deficit from 4 to 3 and made Vanish's criteria no longer met.
</details>

If the issue is the other thing you said -- that you Vanish and it's recommending FoK from Vanish/Stealth despite Improved Garrote, I'd need a snapshot that shows that instead.


## 3a
So point 3 was really two different things.  Echoing Reprimand is recommended after Deathmark is on cooldown (by design), so that's what you're likely waiting for.  If you take Echoing Reprimand off the Cooldowns toggle and leave Deathmark on it, and toggle CDs off, then ER gets recommended pretty quickly.

If you aren't seeing Echoing Reprimand when Deathmark is on CD for 10+ seconds (or toggled off, but ER isn't toggled off), and any of the following are met, take a snapshot.
* You're at least 2 Combo Points shy of cap.
* Your energy is near cap (deficit is 25 + your energy regen from all sources).
* You have at least 2 targets.

Your sim popped Deathmark at ~11 seconds and Echoing Reprimand at 12.  
![image](https://user-images.githubusercontent.com/9438134/201541003-e0146772-cfbd-41b6-9968-13ef61a98c97.png)

## 3b

The other part of your 3rd point was whether the addon should've recommended CT vs. Envenom with 4 targets.  That'd require a snapshot of Envenom being recommended when you think CT should've been recommended instead.  You can open and read the snapshot yourself to see what criteria were met for Envenom vs. CT.  It's possibly something that will be impacted by sim profile updates if it's a real issue.  The priority is also visible in-game (/hekili > Priorities).

There are high priority uses of Envenom before considering any other DOT spenders:
1. buff.slice_and_dice.up & buff.slice_and_dice.remains < 5 & combo_points >= 4
2. buff.flagellation_buff.up & buff.flagellation_buff.remains < 1 & buff.flagellation_buff.stack < 30 & combo_points >= 2

Otherwise, generally speaking, the addon and sim would recommend Rupture or CT before Envenom.

**Comment by GarvielTwo** [comment]
First of all thank you for the very detailed response and for resolving the mentioned points. 

It's clear for me on points 2 and 3b and they can be considered resolved.

I would just like to bring up point 3a for a second. Most of my tests were done on 4 targets, I understand that for single target, Echoing Reprimand is cast exactly as you mentioned. Not contesting any of it.

However on 4 targets and possibly in AoE in general, I still believe it's being recommended very late in the rotation. 

This is a snapshot of when I saw Echoing Reprimand first show up in the recommendation while engaging with 4 targets https://pastebin.com/wkwMCJsi 

I did a raidbots sim with 4 target patchwork in case this helps, I might be wrong, but I don't see the sim cast echoing reprimand at all, perhaps I am reading it wrong.

A final mention on this, on my tests, I am stickling on a single target while testing, essentially funneling damage, while not directly attacking the others. 

Actually, I just tried it now and attacked all 4 targets like I would do in a normal dungeon fight, Echoing Reprimand was not recommended once in over 3 minutes of fighting. 

edit : the 4 target raidbots link https://www.raidbots.com/simbot/report/3FGba1ysnrftsRbrmBH5EF

**Comment by Hekili** [comment]
> However on 4 targets and possibly in AoE in general, I still believe it's being recommended very late in the rotation.
> This is a snapshot of when I saw Echoing Reprimand first show up in the recommendation while engaging with 4 targets [pastebin.com/wkwMCJsi](https://pastebin.com/wkwMCJsi)

I think we are probably more interested in the opposite; a snapshot when you think Echoing Reprimand should be recommended but it isn't.

The reason Echoing Reprimand is shown here is that Deathmark is on cooldown and `use_filler` is true.  There's nothing higher priority to use.  Use Filler means:

`combo_points.deficit[5.00] > 1 | energy.deficit[169.00] <= 25 + energy.regen_combined[22.72] | ! variable.single_target[false]`

Those requirements are pretty easy to meet, so it really has to be a matter of needing to have nothing higher in priority available as well.

**Comment by Hekili** [comment]
I'm going to go ahead and shift Echoing Reprimand and Ambush up in priority so that they get used sooner (while leaving other related conditions intact).

**Comment by GarvielTwo** [comment]
After the latest update, I can see Echoing Reprimand be recommended as I would expect, thank you for the excellent work on this, I believe all of the raised points were address so I will go ahead and close the ticket.
