### ISSUE TITLE
Shadow - Mind Flay recommended briefly

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1929]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hi, I'm having a bit of a problem with Mind Flay in rotation. Or I don't know how to use it properly. It happens very often that the Mind Flay icon only appears for about 1 second or less, because it is immediately replaced by another spell. But it's there long enough for the person to react and press, but the spell itself doesn't get channeled. So I think it's pointless. Wouldn't it be better not to show it at all in this case, if necessary? Less often it shows up as standard, i.e. a few seconds and channels beautifully and I see that as fine.

### How to Reproduce

Enter the game as Shadow Priest and try rotation at least 1 minute.

### Talent Loadout

BIQAu+2Vv7op3uGggQnVDr07wACAAAAAAAAAAAAAAJiSESTLJJJFAAkEJSkABJSRahkAA

### Snapshot

https://pastebin.com/N8c7gVub

**Comment by Hekili** [comment]
> But it's there long enough for the person to react and press, but the spell itself doesn't get channeled.

I'm not sure what to do for this. The addon cannot model your reaction time.  Sometimes, there is a very small window of time before a recommendation will change.  Can you explain more about what you want the addon to do?

Also, your snapshot is not taken at a time where Mind Flay is being recommended.  Snapshots need to be taken when the issue you describe is occurring.  Please provide an updated snapshot if you'd like to explore further.

# Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
