### ISSUE TITLE
Bm hunter Bestial Wrath issue

### ISSUE THREAD

**Issue by Dravus814** [Hekili/hekili#1930]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Currently it is not recommending Bestial Wrath in the rotation with it enabled. 

### How to Reproduce

1. Enter game as BM hunter.
2. Do rotation and see that Bestial Wrath is not going into the rotation

### Snapshot

Beast Mastery; Primary - Kill Command(0.00), Kill Command(1.16), Cobra Shot(2.32)

### Additional Information

build: v10.0.0-09.1
level: 60 (60)
class: HUNTER
spec: beast_mastery

talents: alpha_predator
    animal_companion = 1/1
    aspect_of_the_beast = 1/1
    barbed_shot = 1/1
    barbed_wrath = 1/1
    beast_cleave = 2/2
    beast_master = 2/2
    bestial_wrath = 1/1
    binding_shackles = 1/1
    binding_shot = 1/1
    born_to_be_wild = 2/2
    brutal_companion = 1/1
    camouflage = 1/1
    cobra_shot = 1/1
    counter_shot = 1/1
    hunters_avoidance = 1/1
    improved_kill_command = 2/2
    improved_kill_shot = 1/1
    kill_cleave = 1/1
    kill_command = 1/1
    kill_shot = 1/1
    master_marksman = 1/2
    misdirection = 1/1
    multishot = 1/1
    natural_mending = 2/2
    natures_endurance = 1/1
    pack_tactics = 1/1
    pathfinding = 2/2
    piercing_fangs = 1/1
    posthaste = 2/2
    rejuvenating_wind = 2/2
    scent_of_blood = 2/2
    stomp = 2/2
    survival_of_the_fittest = 1/1
    thrill_of_the_hunt = 3/3
    training_expert = 2/2
    war_orders = 2/2
    wild_call = 1/1

pvptalents: none

covenant: night_fae

conduits: condensed_anima_sphere = 1
   ferocious_appetite = 1
   harmony_of_the_tortollan = 1
   one_with_the_beast = 1
   reversal_of_fortune = 1
   spirit_attunement = 1

soulbinds: [dreamweaver]
   dream_delver = 1
   field_of_blossoms = 1
   podtender = 1
   somnambulist = 1
   soothing_voice = 1
   waking_dreams = 1

sets: enforcers_stun_grenade = 1

gear: boneshatter_armguards = 1
    boneshatter_vest = 1
    choker_of_barbed_reins = 1
    dark_rangers_quiver = 1
    decanter_of_endless_howling = 1
    discount_mailorder_belt = 1
    enforcers_stun_grenade = 1
    godstalkers_gauntlets = 1
    godstalkers_pauldrons = 1
    godstalkers_sallet = 1
    godstalkers_tassets = 1
    logic_loop_of_division = 1
    overclocking_bit_band = 1
    raeshalare_deaths_whisper = 1
    ragebound_leg_irons = 1

legendaries: dire_command = 1
    fragments_of_the_elder_antlers = 1

itemIDs: 110017, 142174, 169157, 169159, 172322, 172329, 185808, 186343, 186414, 186429, 186439, 188856, 188859, 188860, 188861

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Beast Mastery
    petbased = false
    potion = spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    avoid_bw_overlap = false
    barbed_shot_grace_period = 0.5
    check_pet_range = true

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    aspect_of_the_cheetah   = F1  [06]
    aspect_of_the_turtle    = F   [06]
    barbed_shot             = 3   [01]
    bestial_wrath           = 0   [01]
    binding_shot            = F4  [06]
    cobra_shot              = 4   [01]
    counter_shot            = -   [01]
    disengage               = 8   [01]
    exhilaration            = M5  [06]
    feign_death             = 9   [01]
    flare                   = SN  [05]
    freezing_trap           = F3  [06]
    healthstone             = S5  [05]
    hunters_mark            = S1  [05]
    kill_command            = 1   [01]
    kill_shot               = 6   [01]
    misdirection            = M4  [06]
    multishot               = 7   [01]
    sentinel_owl            = S6  [05]
    survival_of_the_fittest = S3  [05]
    tranquilizing_shot      = G   [06]
    wailing_arrow           = 2   [01]
    wild_spirits            = T   [06]

warnings: none

### Contact Information

Dravus#6312

**Comment by Hekili** [comment]
You are asking about an ability that is treated as a major cooldown by the addon.  It will not show unless you toggle Cooldowns on.

See `/hekili` > Toggles > Show Cooldowns

It is recommended that you use a keybind to turn this toggle on/off depending on whether you want your major DPS cooldowns to be recommended.  This helps you save them for key parts of a fight.
