### ISSUE TITLE
Outlaw Between the Eyes renewal vs. Dispatch usage in the rotation

### ISSUE THREAD

**Issue by HurtkBV** [Hekili/hekili#1932]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Playing with another Rogue, we noticed that my Dispatch dmg output is below the auto attack overall dmg. I was completely playing by the Hekili provided rotation. I noticed, it is the result of the recomemndation of the use of Between the Eyes. It is recommendet to apply it when the provided 20% crit but is about at 50% of time left. You still can do 2x Dispatch and 1x Between the eyes until the Between the Eyes buff disappears --> This makes the overall dmg output much higher (22k overall vs 28k overall in the same dungeon on the same m+24 key). To improve the output, I would adapt the recommendation to renew Between the Eyes on target when ~4 sec of the buff is left. 

### How to Reproduce

1. Enter WoW with Outlaw Rogue
2. Play the Greenskin's Wickers talent build
3. Apply Between the Eyes to target
4. Compare DMG output of Hekili vs. the renewal of the skill at the last seconds

### Snapshot

https://pastebin.com/QTCNsBev

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/7Qk1gx9SS7YD1Hmzn6Px7R

### Additional Information

Result of Hekili would be resulting in lesser dmg + dispatch dmg beeng less then auto attack.

**Comment by Sedveth** [comment]
You want to BTE on cooldown (but not when GSW is up) to get GSW buff. This is in APL.

**Comment by Sedveth** [comment]
For dispatch dmg below auto attack, maybe your gear is not optimized or you might have overcapped your CP, probably need log to see.

**Comment by Hekili** [comment]
In your Raidbots sim, which was for Hectic Add Cleave, your sim has 27.55 casts of Between the Eyes vs. 94.42 casts of Dispatch.  When you play Outlaw in a similar environment (meaning several add waves over a similar period of time), how many casts of Dispatch are you seeing vs. casts of Between the Eyes?

The Between the Eyes recommendation you're getting in the snapshot is intentional, as Sedveth noted, for Greenskin's Wickers.
