### ISSUE TITLE
Feral Druid - icon has a bad keybind info

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1933]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello, Prowl icon has SC keybind info - it means "Shift + C" right? But the spell is bindend on "0" (zero) key.

### How to Reproduce

Go Feral and bind Prowl spell to 0 key. I dont use Bartender etc just Blizz UI.

### Talent Loadout

BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAQkUQikkEJFNQSkIJAAAAAAoIASCAiIJEkgEaJAAAAAAASA

### Snapshot

https://pastebin.com/s6gcTBWC

**Comment by marekCs** [comment]
And ofc under Shift+C is nothing. And even then, when I try to press the SC keys - nothing happens.

**Comment by Hekili** [comment]
You have Prowl on multiple bars:

`prowl                  = 0   [06], SC  [08]`

On bar 6, it's bound to 0.  On bar 8, it's bound to Shift-C.  The addon uses a priority system for selecting which binding to show:  The order is 7, 8, 2, 3, 4, 5, 6, 9, 10, 1, based on default assumptions about bars and forms.

If you remove Prowl from bar 8, you should only see 0 for it.  Otherwise, you can set the keybinding for Prowl in /hekili > Abilities > Prowl.

**Comment by marekCs** [comment]
First of all, I thought I couldn't have a bind of combination of spells twice, on two bars. But okay, I guess I can. Second, the addon is wrong - I now have SC on bar 1 (but no spell here). And I only have bars 1 - 7 enabled, with only 1 - 5 binded. So as of bar 6 I have no binds on them.

**Comment by marekCs** [comment]
You can check my binds here: [https://uloz.to/tamhle/G3nuXRoGFJeQ#!ZGuyBQR2ZzVmAmSuAwx2MGp2AwR4AISyFxMMETckIJHlFQOuZN==](https://uloz.to/tamhle/G3nuXRoGFJeQ#!ZGuyBQR2ZzVmAmSuAwx2MGp2AwR4AISyFxMMETckIJHlFQOuZN==)

**Comment by Hekili** [comment]
Not according to the WoW API, apparently.

When I reference the "bar" here, I'm really talking about action bar pages (which mostly align, but shift for forms and stealth and whatnot).  The bar can be enabled, and when you go into Cat Form or Prowl, you notice how the buttons change?  That's your action bar page changing for the form in question.

Regardless, just set the keybind text.

**Comment by marekCs** [comment]
ok if I leave the cat everything is fine. When I'm in the cat it shows bad. And my keybinds are still the same, cat or human.

**Comment by Hekili** [comment]
I'm sorry that I'm not able to explain it any better.  You can look at Wowpedia regarding action bars, pages, forms, and stealth.
