### ISSUE TITLE
Feral- Convoke Season 4 Dungeons (German Client)

### ISSUE THREAD

**Issue by MrBean73** [Hekili/hekili#1934]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The spell Convoke the Spirits don't recommended om german client outside shadowlands (m+). Reload fix the error

### How to Reproduce

1. enter Dungeon outside shadowlands
2. start the m+ key
3.  Convoke don't recommended
4. reload
5. Convole recommended

### Talent Loadout

BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIRSLtDgkkEJl0AEJSCAAAAAAKCgkAgISCBJIhWCAAAAAAgEA

### Snapshot

https://pastebin.com/apt5eWn0

**Comment by MrBean73** [comment]
![image](https://user-images.githubusercontent.com/116820193/201539674-7ee48bd2-db37-4526-839c-ba743ef2ff37.png)

**Comment by Hekili** [comment]
I'll post a test fix in 10.1 in a little bit.

**Comment by MrBean73** [comment]
works

**Comment by Hekili** [comment]
Thanks for confirming!

**Comment by MrBean73** [comment]
update: Works yesterday in Kara but not in Gogrond
