### ISSUE TITLE
Elemental Shaman - Night fae - Fae Transfusion ability not being recommended at all

### ISSUE THREAD

**Issue by TerrySmith22** [Hekili/hekili#1935]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hekili is not recommending Fae Transfer for nIght fae in any situation be it single target or multiple targets/cleave/AOE

### How to Reproduce

1. Enter game as Elemental, check that Covenant Ability is checked in toggles
2.  Load up to any training dummy or mob
3. start rotation,
4. note abilities being recommended
5.  Fae Transfer not recommended in rotation even after reloading priority list

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAAoVSSLJBSLRDBFkIBAAAAAAlAkSSUSRShIik0AQAE

### Snapshot

https://pastebin.com/fbgedBXQ

**Comment by Hekili** [comment]
I'm posting 10.2 which will fix this issue.  Thanks.
