### ISSUE TITLE
Outlaw - Sometimes Flagellation and Dreadblades doesnt show in rotation

### ISSUE THREAD

**Issue by OfficialExiled** [Hekili/hekili#1936]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

So I tried multiple talents and it seemed like suddenly Flagellation might not show in recommendation at all or after I use Flagellation, Dreadblades wont show in recommendation as well. Which changed after the newest update I think. 

### How to Reproduce

So usually rogue gets first 7 combo points on opening then we use Flagellation - Between the Eyes - Dreadblades - Vanish to Dispatch. 
Flagellation and Dreadblades also have to be in combo so usually wait for cooldown until both of them are usually ready to go. 

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAABEkEQSSCJtEBSgEJSAkIAAAAAAAJBpRJJIJJRAAAA

### Snapshot

https://pastebin.com/3TuPNQ2y

**Comment by vond82** [comment]
This might not be the case here, but is your main target (since I notice you're on swarm dummies) at very low hp from extended fighting? Stuff like flagellation and BtE won't be recommended then due to "time to kill" checks in the APL

**Comment by OfficialExiled** [comment]
Time to kill didnt matter for me. I was doing M+ as well and that was the same case over there.

**Comment by OfficialExiled** [comment]
> This might not be the case here, but is your main target (since I notice you're on swarm dummies) at very low hp from extended fighting? Stuff like flagellation and BtE won't be recommended then due to "time to kill" checks in the APL

Time to kill didnt matter for me. I was doing M+ as well and that was the same case over there.

**Comment by Chugdogg** [comment]
I've noticed the same thing as well in Retail/Beta M+ keys... All of sudden it's stopped recommending Dreadblades and Shadow Dance... However, if as soon as I manually use Dreadblades, it will then recommend using Shadow Dance.
However, if I don't manually cast Dreadblades, it will not ever recommend using either.

Snapshot - https://pastebin.com/HAxneKM2 

This is after opening rotation, I would be expecting it to recommend Dreadblades

**Comment by Hekili** [comment]
If you add to the ticket, please include a snapshot where you're experiencing the issue.

**Comment by Hekili** [comment]
@OfficialExiled Your snapshot is taken before you're even in combat, which I will assume is not when you're expecting Flagellation to be recommended.  Please provide a snapshot taken at a time you'd expect Flagellation to be recommended.

**Comment by OfficialExiled** [comment]
@Hekili Oh my bad, https://pastebin.com/rhLnqjgh hopefully this is working.

**Comment by Hekili** [comment]
That one is taken from your AOE display, and it still says you're not in combat.  At least finish your opener so that your initial buffs aren't in the way (Roll the Bones, Slice and Dice, etc.).

**Comment by OfficialExiled** [comment]
@Hekili https://pastebin.com/wA4r0siB Hey sorry for taking your time, but am i in combat now? It seems snapshot doesnt automatically record it, tried to do it manually but that doesnt record either which is weird.

**Comment by Hekili** [comment]
Snapshotting is a manual process.  You have to push the button when you're seeing what you want to show me (or should be seeing it).  

A snapshot is required to diagnose this issue.

# Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by OfficialExiled** [comment]
https://pastebin.com/3TMvSrS4 So looking at the snapshot, After Flagellation, it goes to vanish before using Dreadblades at all.

**Comment by OfficialExiled** [comment]
This is different talent tree with (BQQAOB/7AZ//CwQOf4fPMswHVDAAABJBQSCJtkkIJBSISAkIAAAAAAAJBpRJJIJJpFAAAA) . But on opening it shows Adrenaline but straight to Sinister Strike and not Ambush. https://pastebin.com/GDYauExN

**Comment by icehawk97** [comment]
Flagellation/Dreadblades/ambush doesnt show up/recommended for me neither. Also Adrenaline Rush used to be recommended while dreadblades is active, not anymore.

**Comment by Hekili** [comment]
@icehawk97 If adding to the ticket, please include a snapshot and your talent string.

**Comment by icehawk97** [comment]
Talents - BQQAOB/7AZ//CwQOf4fPMswHVDAAABJBQSCJtkkIJBSIiAkIAAAAAAAJBpRJJIJJpEAAAA

https://pastebin.com/LFg75syD - out of combat (in stealth) Ambush not recommended after Adrenaline rush. (http://piclair.com/o4ckq) Screenshot #1 AR not used.
http://piclair.com/adbnf Screenshot #2 AR used still not recommending Ambush while in stealth.

https://pastebin.com/Gjbs4c6M - In combat with (Chitali the Eldest in zereth mortis) Slice, bladeflurry, adrenaline rush, Roll the bones used. (flag sometimes pops up as recommended and dreadblade doesnt. Worth noticing is that i did Lower karazan +16 where flag didnt pop up at all if that makes a difference. 

First time doing this so i hope i made it correctly.

**Comment by zzzmj** [comment]
I've noticed the same thing as well in Retail/Beta M+ keys

**Comment by IIeTpoc** [comment]
@Hekili It looks like that dreadblades (line 77) was completely removed from the APL according to https://github.com/Hekili/hekili/commit/78addc982fbe49f4d9ea2622e7d3b263021f81f0
That should be the reason why it is not suggested at all.

Also despite the translator fix ingame finish_condition still shows "*" with the latest v10.0.0-11
![image](https://user-images.githubusercontent.com/64799395/201601481-95b5b78b-941c-40cc-9e40-d37c93e03ba6.png)

**Comment by aleksisyrjamaki** [comment]
Adding this in case it is still needed
Dreadblades is not recommended
Talents: BQQAOB/7AZ//CwQOf4fPMswHVDAAABJBkkkQSLRgEIRiEAJCAAAAAAQSQaUSCSSSaBAAAA
Snapshot: https://pastebin.com/isJjZM4j

**Comment by icehawk97** [comment]
Would also like to add in that vanish doesnt get recommended and netiher ambush after using vanish.

**Comment by IIeTpoc** [comment]
In 99% of the time you want to use Dispatch after ambush. For me it is working as it was coded by the simc recommendations, so basicly apart from missing dreadblades APL is pretty ready for the DF launch.
As for Vanish recommendation, a little APL tweak is needed to increase Vanish efficency with Shadowdust legendary, We still need to wait until Hekili checks it, though i suggest it is better to prepare for the DF launch, than polirising stuff that will be not relevant in 2 weeks.

**Comment by coldvyb** [comment]
I'd just like to add in some behaviour I have found regarding Flagellation not being recommended sometimes, I've found similar errors on other specs and I have a feeling that when you're in non-shadowlands content, for example any of the dungeons in the current rotation except for Tazavesh, covenant abilities are not being recommended, and then when you go into Shadowlands content, everything is working fine. I think this might be due to the update that disabled legendaries, soulbinds, covenants etc. outside of Shadowlands and I have found issues with covenant abilities not being listed in the spellbook during a mythic+ instance when they should be enabled. 

I don't have any snapshots of these but if they are needed, I can go grab some from both scenarios I described.

**Comment by Hekili** [comment]
If adding to the ticket, include a snapshot of your own specific case.

**Comment by Hekili** [comment]
> @Hekili It looks like that dreadblades (line 77) was completely removed from the APL according to [78addc9](https://github.com/Hekili/hekili/commit/78addc982fbe49f4d9ea2622e7d3b263021f81f0) That should be the reason why it is not suggested at all.
> 
> Also despite the translator fix ingame finish_condition still shows "*" with the latest v10.0.0-11 ![image](https://user-images.githubusercontent.com/64799395/201601481-95b5b78b-941c-40cc-9e40-d37c93e03ba6.png)

The point of the translator isn't to remove the `*`, it's to ensure it's interpreted correctly.  But there is still an issue with that that I couldn't resolve last night.

Odd that Dreadblades got clipped when updating to use the DF priority.  Will resolve.

**Comment by Hekili** [comment]
I added Dreadblades back into the priority and edited the * again, since the interpreter is taking too long to fix.  Try 11.1 and let me know if the same issues persist.

> I'd just like to add in some behaviour I have found regarding Flagellation not being recommended sometimes, I've found similar errors on other specs and I have a feeling that when you're in non-shadowlands content, for example any of the dungeons in the current rotation except for Tazavesh, covenant abilities are not being recommended, and then when you go into Shadowlands content, everything is working fine. I think this might be due to the update that disabled legendaries, soulbinds, covenants etc. outside of Shadowlands and I have found issues with covenant abilities not being listed in the spellbook during a mythic+ instance when they should be enabled.

There was already an update to address this (rechecking that spells are available when M+ starts); if you are experiencing that presently then please provide a snapshot.

**Comment by icehawk97** [comment]
Tried the new update in workshop +2. This is some problems i found.

While stealthed - Addon suggests bladeflurry before ambush while you are around multiple mobs.
Dreadblades now gets suggested and recommended but flag doesnt.
If i can remember correctly Hekili didnt recommend using DB/Flag if both werent off CD. 
Now it recommends DB even if flag is not off CD for another 10sec or so. 

Vanish is never Recommended.

Screenshot - http://piclair.com/rucht

Addon suggest Flag after DB while personally i think it should be the other way around.
Also like written up top, Flag doesnt show while in M+ but it does in oribos where this screenshot is taken.

**Comment by Hekili** [comment]
### 1
> While stealthed - Addon suggests bladeflurry before ambush while you are around multiple mobs.

Seems reasonable; will make Blade Flurry unusable while in Stealth.

### 2
> Dreadblades now gets suggested and recommended but flag doesnt.

Need to provide a snapshot, not a screenshot.  See `/hekili > Snapshots` and/or `/hekili > Toggles`.

### 3
> If i can remember correctly Hekili didnt recommend using DB/Flag if both werent off CD.

This is probably an artifact of updating to DF priority, where Flagellation goes away.  I'll consider reverting more of this.

### 4
> Now it recommends DB even if flag is not off CD for another 10sec or so.

Same as 4.

### 5
> Vanish is never Recommended.

Need to provide a snapshot when you think Vanish should be recommended but it isn't.  Likely an artifact of new DF priority and will probably be fixed soon enough.

### 6
> Addon suggest Flag after DB while personally i think it should be the other way around.

Same as 4.

### 7
> Also like written up top, Flag doesnt show while in M+ but it does in oribos where this screenshot is taken.

Need a snapshot from M+ with latest version.  Rechecking to allow Covenant abilities in M+ should already be fixed.

**Comment by OfficialExiled** [comment]
So I tried hitting a Sinfall dummy, so I dont know if there is any difference in raid or m+, but looking at the opening everything is fine except in the later in the fight. Looking at the snapshot, https://pastebin.com/kiXtSsj9 it now recommends Dreadblades before Flagellation but fixes when Flagellation is back sometimes but not always. 

For AOE opening,  https://pastebin.com/Rb709Z5N, I am not in combat but as it shows, it starts Stealth - Roll the Bones - Blade Flurry - Adrenaline - Ambush. Which is not possible.

**Comment by IIeTpoc** [comment]
Dread

> So I tried hitting a Sinfall dummy, so I dont know if there is any difference in raid or m+, but looking at the opening everything is fine except in the later in the fight. Looking at the snapshot, https://pastebin.com/kiXtSsj9 it now recommends Dreadblades before Flagellation but fixes when Flagellation is back sometimes but not always.
> 
> For AOE opening, https://pastebin.com/Rb709Z5N, I am not in combat but as it shows, it starts Stealth - Roll the Bones - Blade Flurry - Adrenaline - Ambush. Which is not possible.

Dreadblades should be used on CD as it is a DPS gain in a long fight despite flagelation might still be on CD. Only 1st Dreadblades should be synced with Flagellation which sort of already happens for me.

As for vanish fix i made a pull request which fixed vanish recommendation with shadowdust legendary at least for me
#1947 (at least on target dummies)

**Comment by icehawk97** [comment]
Tested again with an atempt to make a snapshot in Workshop +2 

Problem#(Flag not Recommended when off CD before DB)

Snapshot from that dungeon - https://pastebin.com/SnjFpduU
Screenshot from that exact same time the snapshot was taken where flag was off CD - http://piclair.com/c3462

As for when Vanish is to be used or not i cannot speak for, the knowledge ends there... therefore no snapshot of it. 
Maybe someone more knowledgeable could help with that 👯

**Comment by IIeTpoc** [comment]
Line 488 from your snapshot

        27.  flagellation ( cds - 8 ) - covenant spells are disabled
        Time spent on this action:  0.02ms
        TimeData:Outlaw-cds-8:flagellation:0.02:Ability Known, Enabled(0.02)

Enable it in options

**Comment by icehawk97** [comment]
http://piclair.com/ubofv - it is enabled, or am i missing something?

http://piclair.com/gknik

**Comment by IIeTpoc** [comment]
ur toggle covenant is turnt off

**Comment by icehawk97** [comment]
I havent touched any of that, but if you say so and saw it from the snapshot, how do i turn it on?

**Comment by IIeTpoc** [comment]
You literaly made a screenshot from the tab where you toggle on/off covenants.

**Comment by icehawk97** [comment]
figured it out, but how it was disabled is beyond me, never even looked that far in to the addon itself before.

**Comment by Hekili** [comment]
When 11.3 is released, please test and comment if needed.  I have fixes to Covenant detection and APL updates coming out in a little bit.

**Comment by OfficialExiled** [comment]
So looking at the new updates, with the Ambush option checked, it seems opening is fine except now it recommends Dreadblades first then Flagellation looking at this snapshot. https://pastebin.com/dNg3xVAw. Same goes here after few rotation. https://pastebin.com/7qeSx05T After using Flagellation suddenly it recommends Vanish and Dispatch then Dreadblades. Which should usually be Flagellation - Dispatch/Between the Eyes - Dreadblades - Vanish - Dispatch. But to be honest, I dont think its a big deal to fix this, because DF is releasing soon, so there is probably more work for you with so many classes and more talent options, so dont stress about it.
