### ISSUE TITLE
WW Monk not recommending Storm, Earth, and Fire

### ISSUE THREAD

**Issue by KaiserAnguirus** [Hekili/hekili#1938]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Windwalker rotation is not ever recommending to use Storm, Earth, and Fire when talented. Cooldowns are enabled in Hekili and Storm Wind Fire is in the Cooldowns list.
![image](https://user-images.githubusercontent.com/118151758/201575006-671bd88e-dabd-4873-9d9c-8c010316c3bb.png)
![image](https://user-images.githubusercontent.com/118151758/201575321-4782cba5-6cdf-4186-a39b-f5e87f7f83de.png)

### How to Reproduce

Play as WW monk, have Storm Wind Fire talented.

### Talent Loadout

B0QAdeydY63Y4XKaboK13uRRQAAAAAAAAESkkElISSAAAAAJJkAASSgDkSkISIRkkEaJAAAA

### Snapshot

https://pastebin.com/nZmMeYe3

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vDssvUjmSAEEYZrLWHBE2F

### Contact Information

KaiserAnguirus#5918

**Comment by vond82** [comment]
You're specced into Serenity, not SEF

**Comment by KaiserAnguirus** [comment]
https://pastebin.com/q7exs1kF
![image](https://user-images.githubusercontent.com/118151758/201587251-900d3d96-07a2-458a-816b-f45e0bebc813.png)

Corrected snapshot and screenshot showing I have SEF spec'd

**Comment by Hekili** [comment]
Yes, choice nodes were bugged.  This should be resolved in the latest releases (11.1 and later).
