### ISSUE TITLE
ARMS Warrior: Warbreaker recommended even while the talent isn't enabled.

### ISSUE THREAD

**Issue by MajorKryme** [Hekili/hekili#1939]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Priority recommends "Warbreaker" ability be used when I do not have that ability talent enabled.

### How to Reproduce

Play arms; hit target...the addon will recommend Warbreaker ability whether you have it talented or not.  If you do have it talented, the profile appears to work fine, or at least it continues the priorites.  If you do not have Warbreaker talented, 1) Colossus Smash will not be recommended and 2) Warbreaker will continue to be recommended.

### Talent Loadout

BcEAtml4yL3PsSlRlqnvTeVx4DAkkkkkQko0SSAAAAABRkoQAEJQiAHgmEhASQIAAAAAAAA4AgEJA

### Snapshot

https://pastebin.com/r5CQM6Ht

**Comment by Wyste** [comment]
The snapshot is showing both blunt_instruments + warbreaker (same choice node) talented at the same time. This might help Hekili with dialing in whatever the issue is. The problem likely caused #1941 too.

**Comment by Hekili** [comment]
Yeah, talent detection needed to change but choice nodes were not working.  I'm posting a fixed release now (10.0.0-11.1).
