### ISSUE TITLE
Unholy dk suggestion

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#194]
Essence Blood of the enemy make it prio before using apocalypse and not the other way around for the dmg increase with crit =) Enjoy the summer

**Comment by Hekili** [comment]
For recommendations for changing priorities, generally you need to do one of two things:

1.  Identify a bug with a proper report that demonstrates the addon isn't showing recommendations properly.

OR

2.  Show some sims that demonstrate better performance with the changes you are recommending.

**Comment by Tobbelainen** [comment]
ok ty then=)

**Comment by Hekili** [comment]
It's likely that, if this bears out as a DPS increase, it will be caught and updated by the SimulationCraft folks.  Once their profiles reflect the change, I'll receive notification and will incorporate similar fixes. 

Otherwise, yeah -- test stuff and show your work.  Thanks!
