### ISSUE TITLE
[Ret Pally] Recommending Radiant Decree when not specced

### ISSUE THREAD

**Issue by Teufelaffe** [Hekili/hekili#1941]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Combat rotation is recommending Radiant Decree when I do not have that trait enabled.

### How to Reproduce

1. Enter game as Ret Pally
2. Start combat
3. At some point during rotation, Radiant Decree will be recommended

### Talent Loadout

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAAAgokWSikAQaKJkSJAAAAAAAiEJJplEkQBAloEA

### Snapshot

https://pastebin.com/SAG6tYyb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2E4bsRqHsKgaMPASqt42sZ

**Comment by Hekili** [comment]
Yes, choice nodes were bugged.  This should be resolved in the latest releases (11.1 and later).
