### ISSUE TITLE
Demon-Warlock: Soul Rot does not picked up by Hekili

### ISSUE THREAD

**Issue by timonohe** [Hekili/hekili#1942]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my Demonology Warlock I would expect to cast the Ardenweald Covenant Ability "Soul Rot" on Cooldown but Hekili does not call out to me to use that Ability even once. Either in Single Target or in AoE Situations.

### How to Reproduce

1. Enter the Game as a Demo-Warlock
2. Pick Ardenweald as current Covenant
3. Engage in a fight (ST or AoE)
4. Soul Rot do not appear even once on Hekili

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3ggERiEINCi0kkQaAAAAAAAhgIJikk0SJJJIAAAAAAA

### Snapshot

https://pastebin.com/kSK7MgPt

### Raidbots Sim Report (Link)

fasd

### Contact Information

Ade#2603

**Comment by Hekili** [comment]
Thanks.  I'll post an 11.2 version that removes the talent requirement from Soul Rot.

**Comment by timonohe** [comment]
Hey, just installed the Version 11.2 but Soul Rot is still missing :(
