### ISSUE TITLE
[Feral] Brutal Slash recommended when not talented

### ISSUE THREAD

**Issue by RussellAnas** [Hekili/hekili#1944]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I do not have 'Brutal Slash' selected in my talents, but the addon is recommending 'Brutal Slash' regardless of the talent selection

### How to Reproduce

1. Enter game as Feral Druid
2. Talents setup not to have 'brutal slash'
3. Do rotation and 'brutal slash' eventually starts getting recommended

### Talent Loadout

BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIRSLtDgkkEJl0AEJSCAAAAAAKCgkAgISCBJIhWCAAAAAAgEA

### Snapshot

https://controlc.com/753ac4fe

**Comment by RussellAnas** [comment]
As you can see, I have 'swipe' enabled in my spells, which means I have not taken 'Brutal Slash' (since it replaces Swipe). 

![WoWScrnShot_111422_192635](https://user-images.githubusercontent.com/77004545/201685245-40b32fb9-4a25-4c78-8c2a-efa434c57c65.jpg)

**Comment by P0wn3DD** [comment]
Same for me as Unholy DK… Hekili recommends „Clawing Shadows“ instead of „Festering Strike“, so I didnt even select „Clawing Shadows“ in my talent-tree… and ignoring the abilitie leads to that point that the hekili rotationhelper cant recommend any abilities because he is missing one…

Edit: I switched back to Hekili-v10.0.0-10.2 and its working again. The cause could be one of the updates from today...

**Comment by Hekili** [comment]
Yeah, talent detection needed to change but choice nodes were not working.  I'm posting a fixed release now (10.0.0-11.1).
