### ISSUE TITLE
Auto Snap Blood DK

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1945]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Getting randomly auto snapshots when addon stops recommending abilities. Not sure if its related but Death's Due was never recommended once in the entire dungeon.

### How to Reproduce

Just play blood dk normally following hekili in a dungeon.

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDCJREhISLSIRiIhgkIBAAAAAAikAk0ESSAAARSSEAAAA

### Snapshot

https://pastebin.com/xEbbJKGE

**Comment by Hekili** [comment]
> Just play blood dk normally following hekili in a dungeon.

I would appreciate if you'd provide more careful detail when submitting tickets, especially with regard to describing the issue and reproducing the issue.  

Feel free to submit an update if this is not resolved in the 12.2 or later.
