### ISSUE TITLE
When rotating at Hunter, the position of the midi is completely indicative of rotation

### ISSUE THREAD

**Issue by Myro2** [Hekili/hekili#1949]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

when I go M+ or try training dummies, sometimes the entire rotation disappears in all specs, even on single target or AOE. + sometimes shows spells that have cd and not priorities

### How to Reproduce

Split a couple of seconds after a rotation workout. just make it disappear

![WoWScrnShot_111422_184034](https://user-images.githubusercontent.com/81858506/201729055-2558e391-a335-4ba0-a7f2-8a46d6c33eb3.jpg)

![WoWScrnShot_111422_184040](https://user-images.githubusercontent.com/81858506/201729035-582c9e40-90ed-4e71-9a48-3d2315cf1685.jpg)

### Player Information (Link)

```Text
build: v10.0.0-11.2
level: 60 (60)
class: HUNTER
spec: beast_mastery

talents: alpha_predator
    animal_companion = 1/1
    aspect_of_the_beast = 1/1
    barbed_shot = 1/1
    barbed_wrath = 1/1
    beast_cleave = 2/2
    beast_master = 2/2
    bestial_wrath = 1/1
    binding_shackles = 1/1
    binding_shot = 1/1
    born_to_be_wild = 2/2
    brutal_companion = 1/1
    camouflage = 1/1
    cobra_shot = 1/1
    counter_shot = 1/1
    hunters_avoidance = 1/1
    improved_kill_command = 2/2
    intimidation = 1/1
    keen_eyesight = 1/2
    kill_cleave = 1/1
    kill_command = 1/1
    kill_shot = 1/1
    killer_command = 2/2
    misdirection = 1/1
    multishot = 1/1
    natural_mending = 2/2
    natures_endurance = 1/1
    pack_tactics = 1/1
    pathfinding = 2/2
    piercing_fangs = 1/1
    posthaste = 2/2
    scent_of_blood = 2/2
    stomp = 2/2
    survival_of_the_fittest = 1/1
    tar_trap = 1/1
    thrill_of_the_hunt = 1/3
    training_expert = 2/2
    tranquilizing_shot = 1/1
    war_orders = 2/2
    wild_call = 1/1

pvptalents: chimaeral_sting
   dire_beast_basilisk
   dire_beast_hawk

covenant: none

conduits: none

soulbinds: [forgelite_prime_mikanikos]

sets: ring_of_collapsing_futures = 1
    scars_of_fraternal_strife = 1

gear: astral_verdict = 1
    boneshatter_armguards = 1
    dark_rangers_quiver = 1
    decanter_of_endless_howling = 1
    discount_mailorder_belt = 1
    frozenlink_chestguard = 1
    godstalkers_sabatons = 1
    godstalkers_sallet = 1
    godstalkers_tassets = 1
    illustrious_guild_tabard = 1
    mantle_of_hideous_trophies = 1
    oathsworn_soldiers_gauntlets = 1
    ornately_engraved_amplifier = 1
    ring_of_collapsing_futures = 1
    scars_of_fraternal_strife = 1
    shadowghast_ring = 1

legendaries: none

itemIDs: 142131, 142136, 142173, 172329, 178926, 182991, 185808, 185842, 186429, 186439, 188253, 188859, 188860, 188862, 189853, 69209

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Beast Mastery
    petbased = false
    potion = spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    avoid_bw_overlap = false
    barbed_shot_grace_period = 0.5
    check_pet_range = true

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    aspect_of_the_cheetah     = SMwD[06]
    aspect_of_the_turtle      = SR  [01]
    barbed_shot               = F   [01]
    bestial_wrath             = 4   [01]
    binding_shot              = 7   [01]
    bloodshed                 = A2  [06]
    camouflage                = SM3 [06]
    cobra_shot                = 3   [01]
    counter_shot              = 6   [01]
    disengage                 = SSPACE[01]
    exhilaration              = SMwU[06]
    feign_death               = A3  [06]
    freezing_trap             = A1  [06]
    intimidation              = 2   [01]
    kill_command              = 1   [01]
    kill_shot                 = R   [01]
    mend_pet                  =
    misdirection              = S6  [06]
    multishot                 = 5   [01]
    primal_rage               =
    resonating_arrow          = S3  [06]
    scars_of_fraternal_strife = SF  [01]
    sentinel_owl              = AM3 [05]
    summon_pet                = S2  [06]
    survival_of_the_fittest   = S4  [06]
    tar_trap                  = AMwD[05]
    tranquilizing_shot        = A6  [05]
    wing_clip                 = AMwU[05]

warnings: none
```

### Error Messages (Link)

```Text
no system error reported
```

### Contact Information

tysl@email.cz

**Comment by Hekili** [comment]
Please resubmit as a recommendations ticket and include the snapshot(s) that it's telling you it's creating.  The recommendations ticket has instructions for the snapshots.

![image](https://user-images.githubusercontent.com/9438134/201729869-c42d59e8-be5e-4159-9833-9c9e8216c7b1.png)

**Comment by Myro2** [comment]
I didn't quite understand the answer, sorry

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

# Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
