### ISSUE TITLE
Elemental:  Optimize MOTE -> EQ and/or single-target funneling.

### ISSUE THREAD

**Issue by Arronk** [Hekili/hekili#195]
The AOE rotation does not tell you to buff EQ's with lava surge proc and I think it should to optimize the AOE dps rotation.

**Comment by Hekili** [comment]
You are mostly right about this.  Your sim doesn't really do it at the moment either, but I've done some testing to confirm DPS gains:

![image](https://user-images.githubusercontent.com/9438134/61879613-5e911b80-aec1-11e9-8215-461cd5bd1d3a.png)

I have to do some additional testing to make sure non-MOTE builds aren't affected, but I'll be working on this over the next few days.

**Comment by Arronk** [comment]
I generally go by the special caveat on the stormearthlava website for aoe situations when specced into MoTE. 

Special mention There are many caveats with Master of the Elements when in AoE situations. IF you have two or more Igneous Potential equipped, it is generally worth using Lava Surge procs to empower Earthquakes, even on 4+ targets. On more than 4 targets, only apply flame shock to one of the targets, ideally a target with higher health than the rest. Use Lava Surge procs on the afflicted target in order to empower Earthquake. With this in mind, be careful not to overdo it; it will very likely result in a loss of DPS if enemies die before your Earthquake finishes ticking when you could have used the spell earlier. Obviously this can change with changes in the game so always go by your sims. I did notice when practicing yesterday though the AOE rotation was not asking me to apply a FS on 4+ targets either which I guess is linked up to just having it up to get the lava surge procs for buffing EQ with MoTE

https://stormearthandlava.com/guide/general/priority_list.html

**Comment by Hekili** [comment]
I know.  The issue is translating that into something that can both be tested in sims and displayed via the addon.

**Comment by Arronk** [comment]
Thanks for looking into this and the work you have put into the addon, it is really fantastic.

**Comment by Hekili** [comment]
This was fixed and I am testing an additional change that will open up the grace period for spending Icefury and Stormkeeper stacks (to avoid wastage).
