### ISSUE TITLE
Retribution paladin rotation wih Crusade

### ISSUE THREAD

**Issue by LucasNavim** [Hekili/hekili#1951]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When you pick the talent Crusade on the retribution talent tree it replaces avenging wrath, but the addon still advices to use hammer of wrath when crusade its ON, but crusade doenst allow it to use at anytime as avenging wrath does, but i guess as crusade replaces the avenging wrath the addons still this it does allow...

Thanks!!

### How to Reproduce

Enter the game as Retribution paladin
Get the avenging Wrath talent
Get the Crusade talent
Use Crusade

### Talent Loadout

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAAAgokWSikAQaKJJpVCAAAAAAgQkkkWSQCFOQSQJKB

### Snapshot

https://pastebin.com/7S755ASC

### Contact Information

Navim#2732

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/201798477-5348eee0-5631-497b-83a9-8ea90a3cd916.png)

???

![image](https://user-images.githubusercontent.com/9438134/201798555-0cb6c3c0-0da5-42ca-a166-aa40c0a0b492.png)

![image](https://user-images.githubusercontent.com/9438134/201798580-26188d3a-59db-4077-bdbe-9c4dbef40075.png)

???

**Comment by LucasNavim** [comment]
Sorry, gostaria check Whats going on, because i cant use Hammer of
wrath...otherwise wouldnt make this post.

Thanks for The reply

Em seg., 14 de nov. de 2022 23:17, Hekili ***@***.***>
escreveu:

**Comment by LucasNavim** [comment]
Hey Hekili,

So apparently the HoW cast on AW only works from lvl 58 onwards..

**Comment by Hekili** [comment]
That may have been the case prior to it being a talent.  Can you post an updated snapshot so I can verify which talents you actually have?  Make sure to update to the latest version first.
