### ISSUE TITLE
Outlaw - Vanish not recommended

### ISSUE THREAD

**Issue by Doofbert** [Hekili/hekili#1952]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

During either ST or AOE situations on Dummies or in M+ Dungeons the Addon is not Recommending the usage of Vanish at all in the core rotation.

### How to Reproduce

By simply following the rotation vanish is not being recommended.

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAABJJAJJRSLJJQgEJSAkIAAAAAAAJBpRJJIJJpEAAAA

### Snapshot

https://pastebin.com/2fZmaBUk

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bDhtzVsAwG466s1bArdAPG

### Contact Information

Doofbert#0009

**Comment by Hekili** [comment]
In the linked snapshot, your Vanish is on cooldown for another 18 seconds.  Can you provide a new snapshot where Vanish should've been recommended but isn't, and is not on cooldown?  Thanks.

**Comment by zzzmj** [comment]
I had the same bug

**Comment by zzzmj** [comment]
Snapshot：https://pastebin.com/HUxPssxj
![image](https://user-images.githubusercontent.com/38660039/202116528-36b48d89-a48a-405c-8765-95693118709c.png)

**Comment by Hekili** [comment]
> Snapshot：[pastebin.com/HUxPssxj](https://pastebin.com/HUxPssxj)

That's not a snapshot, unfortunately.  I'll post snapshot instructions below.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
If you use the Use Ambush Regardless of Talents setting, the addon will recommend Vanish without considering other talent requirements.  This change will work with 10.0.2-1.2.  Thanks!
