### ISSUE TITLE
Affliction rotation wont use cds with Malefic Wrath

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1954]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Whenever i use the legendary Malefic Wrath on Affliction it will not use any cooldowns at all, not even vile taint. If i switch to wilfred it shows it as intended.

### How to Reproduce

Do rotation on a dummy with Wilfreds legendary and see that it all works. Now instead equip Malefic Wrath and see that it gets stuck in a loop of maintaining dots and drain soul without using cds.

### Talent Loadout

BkQAbtPS25JQs0VfQSDmhm+p3AIJRiEINig0OQSCpAAAAAAAAAAAAgkkGJJSkkEFJCAA

### Snapshot

https://pastebin.com/pjZsEhZm

**Comment by Hekili** [comment]
Does this still occur in 12.3?  If so, please provide an updated snapshot.

**Comment by Tzuyume** [comment]
The rotation seems to work now with that setup, there is a weird thing with siphon life showing up 4 times in recommendation before you press it though. When you press siphon life it returns to the recommendations as it should though. https://pastebin.com/GXKmj4Ab is the snapshot if that helps.

**Comment by Hekili** [comment]
K, posting a fix.
