### ISSUE TITLE
Destruction not using Immolate on Singletarget

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#1955]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hekili seems to never recommend Immolate on its own in a singletarget rotation.

### How to Reproduce

Do your singletarget rotation anywhere and immolate will never show up.

### Talent Loadout

BsQAbtPS25JQs0VfQSDmhm+p3AIJRiEINtIINJJkCkEQicgSCtSTSAAAAAAAAAAAAAQSA

### Snapshot

https://pastebin.com/Fdk7e5Ze

**Comment by Hekili** [comment]
Did you disable Cataclysm?  It sees you've talented for it and it's not on cooldown, but it shows up as ability unknown in your snapshot.

**Comment by Tzuyume** [comment]
I think its the talent string being a bit wonky then, im talented into inferno.

**Comment by Hekili** [comment]
Ok, this was an issue with choice nodes, from earlier.  You should be fine with the latest releases.
