### ISSUE TITLE
Balance Druid recommending Celestial Alignment when Incarnation: Chosen of Elune is talented

### ISSUE THREAD

**Issue by Memorialized** [Hekili/hekili#1956]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I have talented into Incarnation: Chosen of Elune and the addon is recommending I use Celestial Alignment instead.

### How to Reproduce

1. Play as Balance Druid
2. Select Incarnation: Chosen of Elune as a talent
3. Follow rotation recommendations until it recommends Celestial Alignment

### Talent Loadout

BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQSiIEChkEkIgWCJRkikAJIlkWISQDA

### Snapshot

https://pastebin.com/L2Mkem4h

**Comment by Hekili** [comment]
This has been resolved; make sure to update to the latest release (12.1 at time of posting).
