### ISSUE TITLE
BM Hunter not using multishot in aoe

### ISSUE THREAD

**Issue by Nepv1** [Hekili/hekili#1960]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hitting 5 target dummies in Kyrian covenant area, not recommending multishot to activate multishot

### How to Reproduce

1. Enter combat with more than 1 target
2. Begin rotation (multishot should be recommended as soon as pets reach target)

### Talent Loadout

B0PAIlFMjeNhnEouGfV8Ij2uShgWCACBAAAAAAAAAAgGxBKCkI5ASiERoJEhkQkEhGHIRA

### Snapshot

https://pastebin.com/UJXXE8gV

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pcZCeLvtsLxPo9wBcTqhSp

### Contact Information

nep#0001

**Comment by Hekili** [comment]
You do not have pet-based target detection enabled.  See /hekili > Beast Mastery > Targeting to enable it.
