### ISSUE TITLE
Shattering Star being recommended after Eternity Surge, should be before.

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#1961]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Shattering Star which provides  a 20% damage increase debuff to the mob is being recommended After Eternity Surge, it should be Fire Breath then Shattering Star, THEN Eternity Surge to have the debuff applied before you Eternity Surge to get the extra damage on ES.

### How to Reproduce

Enter Game as Devastation Evoker
Load up the addon and just do the normal rotation.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAgWIJikQgEJlkkIAISIJBSSSQikkA

### Snapshot

https://pastebin.com/yUMGqWTn

### Contact Information

Pulse#0223

**Comment by Hekili** [comment]
I'll go ahead and make a revision for this, but there are subtle issues potentially.  This won't save Shattering Star if Eternity Surge is coming off CD soon since I haven't run sims to test.  I'll publish as 12.1 just to save time.

**Comment by Pulseonline** [comment]
> I'll go ahead and make a revision for this, but there are subtle issues potentially. This won't save Shattering Star if Eternity Surge is coming off CD soon since I haven't run sims to test. I'll publish as 12.1 just to save time.

Yea to be honest I figured that.  Its mainly for the opener.  Its pretty big on opener.  As far as rest of rotation goes.  I'm not sure yet.
