### ISSUE TITLE
Convoke not recommended in M+

### ISSUE THREAD

**Issue by tance77** [Hekili/hekili#1962]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I'm not sure what caused it, but convoke was not being reccomened when running this tallent build during a dungeon.

**Talent String**
BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIkUSDkkEJNtASkcgkAAAAAAgiAIJAQikEBJ0SoAAAAAAAgEA

### How to Reproduce

1. Spec into these tallents : BcGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAIkUSDkkEJNtASkcgkAAAAAAgiAIJAQikEBJ0SoAAAAAAAgEA
2. Run Junkyard
3. Notice convoke isn't reccomeneded after a short while in the dungeon

### Player Information (Link)

[Player Information](https://pastebin.com/y76EDFHm)

### Error Messages (Link)

```Text
No Error Message
```

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

# Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by tance77** [comment]
[Snapshot 1](https://pastebin.com/pfXP6pgL)

**Comment by tance77** [comment]
[Snapshot 2](https://pastebin.com/X2923RBP)

**Comment by tance77** [comment]
It also does not seem to be reccomending Ferocious Bite outside of the Predator proc

**Comment by vond82** [comment]
> It also does not seem to be reccomending Ferocious Bite outside of the Predator proc

This is due to ferals APL for prepatch not being updated properly (afaik it likely won't until DF release) so if you have both Tear Open Wounds and Rip and Tear talents, the APL will say you should PW even on single target

As for the other issue, in the snapshot it says you have Covenant spells disabled

**Comment by Hekili** [comment]
Update to the latest release and confirm you're somewhere that you should be able to Convoke.  Your snapshot does not show Convoke talented and you seem to be somewhere that Shadowlands items are not allowed.

> This is due to ferals APL for prepatch not being updated properly (afaik it likely won't until DF release) so if you have both Tear Open Wounds and Rip and Tear talents, the APL will say you should PW even on single target

@vond82 If you wanna share the upcoming changes, I can update the addon accordingly to match.

**Comment by Hekili** [comment]
Note:  It does look like you're in M+ based on Challenger's Burden being applied.  Please test with the latest release and confirm that Convoke is not being recommended inside M+.  Thanks.

**Comment by tance77** [comment]
> Note: It does look like you're in M+ based on Challenger's Burden being applied. Please test with the latest release and confirm that Convoke is not being recommended inside M+. Thanks.

I updated to 10.0.0-12.1 and it seems to reccommend convoke near the start of the M+, but as time goes on it does not even reccomened it at all even on boss fights. Nore does it reccommend foroceous bite outside of Apex Predator Procs.

It always reccomeneds primal wrath in Single Target as the Combo Spender

**Comment by Hekili** [comment]
> Nore does it reccommend foroceous bite outside of Apex Predator Procs.  It always reccomeneds primal wrath in Single Target as the Combo Spender

This was explained above.

> it seems to reccommend convoke near the start of the M+, but as time goes on it does not even reccomened it at all even on boss fights.

What does this mean, precisely?  When was Convoke recommended in M+?  When was it not?  Two snapshots would be helpful; one in M+ when Convoke was shown, and one in M+ when it *should* be recommended but isn't.

**Comment by Hekili** [comment]
This may be addressed in 12.3 or later.  If Convoke is not recommended in M+, please provide an updated snapshot.

**Comment by tance77** [comment]
> This may be addressed in 12.3 or later. If Convoke is not recommended in M+, please provide an updated snapshot.

Sorry I haven't had time to get you an updated snapshot, but will test in a few hours with 12.3

**Comment by tance77** [comment]
> This may be addressed in 12.3 or later. If Convoke is not recommended in M+, please provide an updated snapshot.

Working on Training Dummy, will check in M+ shortly.


Edit: Unfortunately I didn't get time to test this yesterday will test tonight.

**Comment by tance77** [comment]
It is working in M+ now thanks
