### ISSUE TITLE
Devastation Evoker - Tip the Scales is being recommended for Fire Breath - Should be Eternity Surge

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#1963]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

During Cooldown phase its recommending we use Tip the Scales for Fire Breath - It should be for Eternity Surge.  You use R1 Fire Breath, then Dragonrage, then Shattering Star into Tip The Scales/Eternity Surge.  

### How to Reproduce

Enter Game as Evoker - Devastation Talents
Make sure CD's are enabled, procede with rotation.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAgWIJikQQSkUSSiAgIhkEIJJ5AkIJJ

### Snapshot

https://pastebin.com/ZFzG1AP7

### Contact Information

Pulse#0223

**Comment by Pulseonline** [comment]
![opener](https://user-images.githubusercontent.com/116061761/201825235-bbb7c5ce-57f4-4fef-bf04-0a64413a47ab.PNG)

If this Helps at all.

**Comment by Hekili** [comment]
The pivotal piece is really that sims get updated to reflect this behavior (which makes sense, spending your instant on FB-1 and then charging ES is silly).  I really don't want to be chasing guides.  You might consider submitting pull requests to SimulationCraft with these changes, which will then arrive downstream here later on.

**Comment by Hekili** [comment]
This should be addressed in the latest releases.
