### ISSUE TITLE
Shadow Dance

### ISSUE THREAD

**Issue by BitterPasta** [Hekili/hekili#1965]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Shadow Dance is not appearing for Sub Rogue.

### How to Reproduce

Enter the game on Sub Rogue
Start combat

### Talent Loadout

BUQAOB/7AZ//CwQOf4fPMswHVDAAAAAAAAAARCJJJJICIREASSCJpdgSSiESaUCgkEAAAA

### Snapshot

https://pastebin.pl/view/aed70d22

### Contact Information

BitterPasta#6911 Discord

**Comment by Hekili** [comment]
You didn't provide your Talent Loadout, but your snapshot shows that you do not have Shadow Dance talented.  Is that incorrect?

**Comment by vond82** [comment]
> 

Subtlety rogues have Shadow Dance as baseline and get a 2nd charge from the talent (while Outlaw and Assassin gets 1 charge from talenting into it)

**Comment by BitterPasta** [comment]
My apologies. Had to refresh the page before I could post. Shadow Dance is a base ability with the option to get one more charge as a talent.

**Comment by Hekili** [comment]
Thanks.  I'll post a fix in a bit.

**Comment by Hekili** [comment]
This should be resolved in 12.3.
