### ISSUE TITLE
Demonology - Soul Rot not recommended in M+

### ISSUE THREAD

**Issue by timonohe** [Hekili/hekili#1966]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my Demonology Warlock I would expect to cast the Ardenweald Covenant Ability "Soul Rot" on Cooldown but Hekili does not call out to me to use that Ability even once. Either in Single Target or in AoE Situations.

Regression from https://github.com/Hekili/hekili/issues/1942

### How to Reproduce

1. Enter the Game as a Demo-Warlock
2. Pick Ardenweald as current Covenant
3. Engage in a fight (ST or AoE)
4. Soul Rot do not appear even once on Hekili

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3ggkEJSg0IISTSCpBAAAAAAECJSiIJJtUSSCCAAAAAAA

### Snapshot

https://pastebin.com/7JMKhRzN

### Contact Information

Ade#2603

**Comment by Hekili** [comment]
Your snapshot needs to be taken when you think Soul Rot should've been recommended.

**Comment by timonohe** [comment]
Sorry here it is: https://pastebin.com/Hcv71ZKs

Soul Rot has to be cast on Cooldown with Tyrant.

**Comment by Hekili** [comment]
Where are you doing your testing?  Your snapshot still didn't reach any criteria associated with Soul Rot.  It looks like maybe you were in Mechagon.  Is that right?

**Comment by timonohe** [comment]
Yes that was in a Mythic+ Dungeon. The criteria for Soul Rot is if it is off Cooldown and used with Tyrant...

**Comment by Hekili** [comment]
Ok, so this is because your soulbinds were still viewed as disabled.  That's easy enough to solve.  Thanks for confirming.

**Comment by Hekili** [comment]
I'm posting 10.0.0-12.3 now with a testfix for this.

**Comment by timonohe** [comment]
Tested it with 12.3 but Soul Rot still does not show up. Soulbinds are enabled now and tested on dummies with multiple targets.

https://pastebin.com/DuLs6jdJ

**Comment by Hekili** [comment]
It looks like Soul Rot criteria aren't met with Korayn.  Do you have the legendary equipped?

**Comment by timonohe** [comment]
I dont have any legendary on this character. What criteria with Korayn do you mean? I dont know any legendary that is needed for Casting Soul Rot?

**Comment by Hekili** [comment]
Soul Rot is pretty pointless in-and-of-itself.  With Dreamweaver, you use it because it triggers [Field of Blossoms](https://www.wowhead.com/spell=319191/field-of-blossoms?spellModifier=137042) for haste.  With Niya, you use it for [Grove Invigoration](https://www.wowhead.com/spell=342937/grove-invigoration?spellModifier=137042) because it grants Redirected Anima for Mastery.

With the Decaying Soul Satchel legendary, you'd use it with Tyrant since it grants haste and crit.

With Korayn and no legendary, there's no reason to use it during Tyrant.  So Soul Rot should get recommended after your Tyrant expires and while Tyrant is on cooldown.  That's what this condition refers to:

```
! ( soulbind.field_of_blossoms | soulbind.grove_invigoration ) & ! runeforge.decaying_soul_satchel &  ! pet.demonic_tyrant.active & variable.next_tyrant_cd > 18
```

In your snapshot, that condition would've been met after your Tyrant expired:

```
! ( soulbind.field_of_blossoms.enabled[false] | soulbind.grove_invigoration.enabled[false] ) & ! runeforge.decaying_soul_satchel.enabled[false] & ! pet.demonic_tyrant.active[true] & variable.next_tyrant_cd[75.00] > 18
```

**Comment by timonohe** [comment]
Well Tyrant was in cooldown but no Soul Rot was recommended....

**Comment by Hekili** [comment]
It was on cooldown but it was active.  You have better buttons to push during Tyrant if Soul Rot isn't granting you buffs to make it worth pushing.
