### ISSUE TITLE
[Fury] Bloodbath being recommended while ability still on CD (new Reckless Abandon changes)

### ISSUE THREAD

**Issue by Wyste** [Hekili/hekili#1967]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Fury warrior, while using Rampage to gain 2 stacks of Reckless Abandon, the recommendation is to use Bloodbath back to back, but the 2nd Bloodbath is still on cooldown when the spiral on hekili's primary recommendation 1 is finished, therefore it feels misleading, because I'm pressing the button, yet the ability isn't being used.

### How to Reproduce

Talent Build:
`BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAABBKJEEhEIBHAChAEOQIJQkkkIJCRSoF4AQSSAAAAC`

Perform rotation normally, then when you Rampage, you'll gain 2 stacks of Reckless Abandon buff.
The addon (through normal rotation) will sometimes recommend back to back Bloodbaths, and the 2nd one will not be ready by the time the spiral finishes on the addon; it will still be on cooldown for approximately .5 seconds.

Snapshot was taken when the SECOND bloodbath was 'held up' by this odd feeling scenario.

### Talent Loadout

BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAABBKJEEhEIBHAChAEOQIJQkkkIJCRSoF4AQSSAAAAC

### Snapshot

https://pastebin.com/B97W8gZe

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/51m1QU3Mfx7SUzGxxyhFT6

### Additional Information

Feel free to hit me up on discord for any quick troubleshooting etc.

### Contact Information

Wyste#8631

**Comment by Hekili** [comment]
So your snapshot is actually recommending Bloodthirst while it's transformed into Bloodbath.  The trick here (most likely) is to set the textures on both spells, and make sure when you use Bloodbath it spends a charge of Bloodthirst and vice versa.

**Comment by Hekili** [comment]
Should be fixed with latest commit.
