### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by Rav99** [Hekili/hekili#197]
Version: v8.2.0-06

On login with fury warrior i get this:
"1x ...\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:40: table index is nil
...\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:40: in function <...\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:38>
...\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:163: in function `IsSpellInRange'
Hekili\UI.lua:921: in function <Hekili\UI.lua:704>

Locals:
t = <table> {
}
i = nil
o = false
(*temporary) = nil
(*temporary) = "table index is nil"
tonumber = <function> defined =[C]:-1"

Pastebin: https://pastebin.com/V1HE4Yd0

**Comment by Hekili** [comment]
I'm not able to replicate this with the information you've provided.  Please submit a complete ticket with all the requested info.

**Comment by Rav99** [comment]
I have added the pastebin link.

**Comment by Hekili** [comment]
Have you fully exited and restarted WoW since updating?

**Comment by Rav99** [comment]
Yes

**Comment by Hekili** [comment]
Do you get the error with no other addons loaded?

**Comment by Rav99** [comment]
Its only on first login, after a /rl its gone.

**Comment by Hekili** [comment]
This should be resolved.
