### ISSUE TITLE
Assassination: Shiv not recommended during Kingsbane

### ISSUE THREAD

**Issue by vond82** [Hekili/hekili#1970]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

As an assassination rogue when you play with the Kingsbane talent, Shiv is not recommended. This is a very important buff to keep up during Kingsbane (esp during the latter parts of Kingsbane) as it buffs the damage significantly.

Just before Kingsbane gets used, Shiv shows as the next spell to use. But once it's used, Shiv does not get recommended.

### How to Reproduce

1. Enter game as assassination rogue
2. Take the Kingsbane talent
3. Use Kingsbane
4. Notice Shiv is removed from recommendation while it was previously shown as next ability after Kingsbane

### Talent Loadout

BMQAOB/7AZ//CwQOf4fPMswHVDJSCSSAAAAAAAAJAkkAAAAAAAQQa0SCSSSaBSSCQkkA

### Snapshot

https://pastebin.com/MUDp1ccp

### Additional Information

Fixed by changing **dot.kingsbane.ticking** to **dot.kingsbane_dot.ticking** on line 64 in RogueAssassination.simc

**Comment by Hekili** [comment]
Thanks for the clear report.  I'm fixing the Kingsbane dot detection to resolve this issue.
