### ISSUE TITLE
Enhancement: Wind Fury Totem recommended for Doom Winds Buff while Doom Winds Debuff is still present

### ISSUE THREAD

**Issue by rivengh** [Hekili/hekili#1971]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my Enhancement Shaman, sometimes the addon recommends Windfury Totem (for Doom Winds buff), while actually the Doom Winds Debuff (ID 335904) is still present.

I have attached a snapshot for a case, where you can see that `buff.doom_winds_debuff.down` is considered as _true_, while `doom_winds_cd` debuff is up.

### How to Reproduce

Unfortunately this happens only occasionally and I was not able to reproduce this behaviour on a target dummy, while it tends to happen more often in dungeons (M+) or in group.

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJpAJSiECQCRCAAAAAAAAAAAAAiQES0CBgkkUAUSkEoA

### Snapshot

https://pastebin.com/YgH6utQZ

**Comment by Hekili** [comment]
There will be a testfix in the next release.

**Comment by Hekili** [comment]
This should be resolved in 10.0.2-1.2 and later.

**Comment by rivengh** [comment]
Thank you very much, Hekili! Looks good to me after a short test. I will give you further feedback, after more extensive testing.
