### ISSUE TITLE
Please add Arcane Mage

### ISSUE THREAD

**Issue by Pyxl00** [Hekili/hekili#1972]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Fire and Frost have been added to the addon but I play Arcane mage and cant get the dps that I would like. 

### How to Reproduce

Need Arcane spec added to addon

### Snapshot

N/A

**Comment by Hekili** [comment]
There is no DF priority for Arcane Mage available yet.  It will be added when there's something to add.
