### ISSUE TITLE
Guardian Druid Tooth and Claw changes

### ISSUE THREAD

**Issue by pefcs** [Hekili/hekili#1974]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Addon doesn't consider the new tooth and claw changes (0 rage cost with buff) and waits for enough rage for maul when the buff is up.

"spend = function() return buff.berserk_bear.up and talent.berserk_unchecked_aggression.enabled and 20 or 40 end,"

I tried to modify the maul process locally, but I'm not convinced if it will work properly together with unchecked aggression. Here is my version, it might help to do the changes properly:

    maul = {
        id = 6807,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        school = "physical",

        --spend = function() return buff.berserk_bear.up and talent.berserk_unchecked_aggression.enabled and 20 or 40 end,
	spend = function() return buff.tooth_and_claw.up and talent.tooth_and_claw.enabled and 0 or ( buff.berserk_bear.up and talent.berserk_unchecked_aggression.enabled and 20 or 40 ) end,
        spendType = "rage",

        talent = "maul",
        startsCombat = true,

        form = "bear_form",

        usable = function ()
            if ( settings.maul_rage or 0 ) > 0 and rage.current - cost < ( settings.maul_rage or 0 ) then return false, "not enough additional rage" end
            return true
        end,

        handler = function ()
            removeBuff( "vicious_cycle_maul" )
            addStack( "vicious_cycle_mangle" )
            if talent.infected_wounds.enabled then applyDebuff( "target", "infected_wounds" ) end
            if pvptalent.sharpened_claws.enabled or essence.conflict_and_strife.major then applyBuff( "sharpened_claws" ) end
            if talent.ursocs_fury.enabled then applyBuff( "ursocs_fury" ) end
            if talent.tooth_and_claw.enabled and buff.tooth_and_claw.stack <= 1 then removeBuff ( "tooth_and_claw" ) end
            removeBuff( "savage_combatant" )			
        end,
    },

### How to Reproduce

1. Use talent tooth and claw
2. Create a test, high priority ability with Maul and "buff.tooth_and_claw.up" condition
3. Wait for tooth and claw to proc
4. Spend your rage to bring it below the initial threshold (40)
5. Maul is not shown in the priority list

### Talent Loadout

BgGAYhlYdy9RJ6ROrphOEi69vCAAAAAAAAAAAAASEJBiSkkEJASShCgAIJRgkkEJJCAAAAAAAAAB

### Snapshot

Snapshot is not valuable as the recommendation is not shown, therefore not visible

### Additional Information

I tried the suggested changes and without talenting to Unchecked aggression it works well for me, however I'm not sure, that this is the proper way to modify it.

**Comment by Hekili** [comment]
This will be addressed in the next release.
