### ISSUE TITLE
Blood Death Knight - Death and Decay suggested while on cooldown

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#1975]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

While performing the rotation on target dummies or in dungeons/raids DnD is suggested while it is on cooldown and there's other things available to use.

### How to Reproduce

1. Follow Hekili suggestions on 3+ target

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDCJJQIiISERiIhgkkEBAAAAAg4AJQk0kISAAAikEBAAAA

### Snapshot

https://pastebin.com/6B1UftMb

**Comment by Hekili** [comment]
How long was Death and Decay on cooldown for when you took this snapshot?  It is recommending DnD in 0.25 seconds -- which is when the GCD would expire.  Was Death and Decay actually on a longer cooldown at this time?

**Comment by Hekili** [comment]
I think I have the root cause; the upcoming release should prevent this from occurring.
