### ISSUE TITLE
Gift of the Naaru never comes up.

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#1977]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I put "Gift of the Naaru"  in my default list for my Elemental Shaman, however, it is never recommended.  I am using the following conditions. "health.pct <= 75". I have even tried without conditions and it still is never recommended.

### How to Reproduce

1. Enter the game as Draenei Elemental Shaman
2. Add, Gift of the Naaru to rotation.
3. Take damage until the conditions threshold is met.
4. Does not come up.

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAA0atk0SSSRSLRDBFABAAAAAAlAkSSiUEFCSSSBgkAA

### Snapshot

https://pastebin.com/Erd54fwZ

### Contact Information

MrWizard516

**Comment by Hekili** [comment]
The addon couldn't tell that you know Gift of the Naaru, but custom priorities aren't supported.  In-game, if you type `/dump GetSpellInfo("Gift of the Naaru")`, what is printed on screen?

**Comment by Hekili** [comment]
This should be resolved in the next release.  Thanks!
