### ISSUE TITLE
Shaman Elemental - Nature's Swiftness still recommended even on CD

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1978]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

This spell should have been recommended only once and then another spell should probably follow. Instead, after NS is cast, this spell shows up in the queue again, but cannot be cast because it is on the CD (waiting for another spell to be cast)

### How to Reproduce

Go with these talents as Elemental (on Beta) and try rotation.

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAASrVSSJJJlkgUQQBJCAAAAAAUCQKJh0kUISJJJtAIJAA

### Snapshot

https://pastebin.com/3EjbW55K

**Comment by Hekili** [comment]
Thanks, this will be addressed in next release.
