### ISSUE TITLE
[FDK]  New rotation with Icecap and no big changes in the rotation of the BoS

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#198]
Hello. I would like to ask you added a new rotation under the icecap talent? in rotation fdk? Now this build plays better than BoS.

And I would also like to ask. Is it possible to make the BoS take separately from the rotation? Just in the same Mythyc + is not very convenient when the rotation offers him to live where it fell. Thanks for the help.

**Comment by Hekili** [comment]
I've seen no new priority/profile for Icecap and I've been watching closely.

Breath of Sindragosa is linked to the cooldowns toggle by default.  You can disable cooldowns to disable it.

You can also just disable Breath of Sindragosa itself, altogether.  The addon won't prepare for BoS, but will still react if/when you use it manually.

**Comment by geraint425** [comment]
I now would like to continue the topic with Bos. Because look, there in the rotation there are small shoals. Although it may not. But let's say. Why do we have Cold heart immediately as soon as 20 stacks appear? I noticed that rotation uses them very rarely from here we lose huge DPS in idle. While we have accumulated 20 stacks, we can immediately merge them and start accumulating new ones. 

Plus, I did what you said to remove Bos from the cooldowns. But rotation still suggests using an ice strike and reducing the number of runic power. I would like to offer in such a sulchae condition. Suppose, if we have ready-made 3 abilities, this is a breath of sindragosa, Pillar of Frost, Empower Rune Weapon, then the runic power can only spend up to 70+ runic power, no less. So that during the use of the macro for the simultaneous use of 3 abilities we were always ready. And I also noticed that Pillar of Frost is not used correctly when it remains for 15-20 seconds. before the rollback breath of sindragosa. In this regard, it is better to delay it, since we’ll wait with Pillar of Frost for 15-20 seconds rather than wait 35 seconds for it to roll back.

**Comment by Hekili** [comment]
I guess I would suggest that you build your priority in SimulationCraft, test it, and then send me results and I'll see about implementing any changes.

**Comment by geraint425** [comment]
So I have no experience in drawing up a rotation on Simulationcraft. I just know how these abilities should work and see how they work for you. Just even in the guides it is written that with the accumulation of 20 Cold heart, we must immediately use them. Look at warcraftlogs.

**Comment by geraint425** [comment]
Moreover, we must Cold Heart still synergize with Pillar of Frost. To inflict maximum damage from Cold Heart. As everywhere they write when it’s 5 seconds before the end of Pillar of Frost, we must take the Cold Heart. It turns out 5 seconds before the end of Pillar of Frost go Cold heart.

**Comment by geraint425** [comment]
Please read the footnotes in this guide as described by the person. https://www.wowhead.com/frost-death-knight-advanced-rotation-guide#absolute-zero-cold-heart

**Comment by geraint425** [comment]
That's also in the rotation on Icy how to use Cold Heart. https://www.icy-veins.com/wow/frost-death-knight-pve-dps-rotation-cooldowns-abilities
