### ISSUE TITLE
Assassination Rogue rotation doesn't prompt covenant version of Serrated Bone Spike.  Talented version works fine.

### ISSUE THREAD

**Issue by Schizkey** [Hekili/hekili#1983]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The rotation doesn't ever recommend serrated bone spike, I've used the addon for a while and looked through the profile quite a bit, I reset several times and all, can't figure out why it won't show.  However, if you are not covenant, and just take serrated bone spike talent instead, it works just fine.  I also have tried manually adding in serrated bone spike to the rotation in any spot and none recommend it no matter what, even if placed in cooldown category.

### How to Reproduce

1. Enter game as Assassination Rogue.
2. Choose Necrolord as Covenant.
3. Addon never recommends Serrated Bone Spike.

### Talent Loadout

BMQAOB/7AZ//CwQOf4fPMswHVjkEBSCAAAAAAAQCASCAAAAAAgESaIJSSSSEIJBCJJJA

### Snapshot

https://pastebin.com/cQuTaqv4

### Additional Information

I understand it's pre-patch just noticed this issue and it's just a bit annoying.

### Contact Information

Briskey#6387

**Comment by Hekili** [comment]
This will be fixed in next release.
