### ISSUE TITLE
Expel Harm (monk/windwalker) is given highest priority when it should be lowest

### ISSUE THREAD

**Issue by chiraino** [Hekili/hekili#1984]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Expel Harm is always given highest priority, when it should be the last thing on the list.  At full health, with every ability and full chi available, it still thinks Expel Harm is the most important attack.

Expel Harm shouldn't even be in the list without Defensives selected.

### How to Reproduce

1. Turn on Hekili with Windwalker Monk.

### Talent Loadout

B0QAdeydY63Y4XKaboK13uRRQAAAAAAAAESkkElISSAAAAAJJkAASSgDkSkISIRkkEaJAAAA

### Snapshot

https://pastebin.com/MUGa06Gs

**Comment by Hekili** [comment]
Sim yourself and provide the link.  Thanks!

**Comment by Hekili** [comment]
For reference:  https://www.peakofserenity.com/sl/windwalker/pve-guide/

![image](https://user-images.githubusercontent.com/9438134/202863619-09a9cd17-f2de-40dd-9093-2c8827bf20c2.png)

![image](https://user-images.githubusercontent.com/9438134/202863633-013e58e8-76c1-452b-8974-de5b1c41f515.png)

![image](https://user-images.githubusercontent.com/9438134/202863646-1e5ba6f7-5e5d-4e34-87d3-01be38afc881.png)

Using Expel Harm to generate Chi is recommended in guides and matches sim behavior.

> At full health, with every ability and full chi available, it still thinks Expel Harm is the most important attack.

Your snapshot does not show a recommendation for Expel Harm at full chi.  Every Expel Harm entry in the priority checks to see that you're not already capped on Chi.  If you see that happen, please take a snapshot at that time and link it here.
