### ISSUE TITLE
Frost Mage - frequent stuttering of recommended spells

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#1985]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I don't know how to describe it properly, maybe someone else who tried Frost mage can help me. The recommended spells often get stuck in the middle of the cast in the sense that they freeze then blink and reappear again, it's terribly annoying, kind of jerky, you need to try it yourself on Beta.

I also noticed that Counterspell is not recommended even if the condition is met. To take a snapshot, I was in the queue yesterday for about 6 hours on Beta, but no one got caught and there was no dungeon, so I don't have a snapshot on Counterspell.

### How to Reproduce

Enter the game as Frost mage and try any rotation.

### Talent Loadout

BAEAHVkVsxxZrVqBmAzlSR2f7LQkolIhkUEEtkIikQAAAQSSSESkkkIpkkkIAAAAAAAAAAC

### Snapshot

https://pastebin.com/7AkC3YDL

**Comment by Hekili** [comment]
Thanks for the report with loadout and snapshot.  I appreciate it.

> The recommended spells often get stuck in the middle of the cast in the sense that they freeze then blink and reappear again, it's terribly annoying, kind of jerky, you need to try it yourself on Beta.

If I understand correctly, you are saying that momentarily there will be no recommendations but they will reappear?  On the /hekili > Snapshots tab, do you have Auto-Snapshot enabled?   If it's enabled, that situation should result in a snapshot generated that doesn't have recommendations.

Alternatively, there may be a bug in the BugSack that would help to diagnose the issue.  Do you have BugSack and BugGrabber installed?  If so, after this flicker occurs, are there any errors generated by the addon?

> I also noticed that Counterspell is not recommended even if the condition is met. To take a snapshot, I was in the queue yesterday for about 6 hours on Beta, but no one got caught and there was no dungeon, so I don't have a snapshot on Counterspell.

Your snapshot is from your primary display, while Counterspell is on the Interrupts toggle and you have Interrupts set to Show Separately.  If you can provide a snapshot for your Interrupts display when you have a hostile target that is casting something interruptible, I could investigate that as well.  Thanks!

**Comment by marekCs** [comment]
No, it won't disappear completely. It's kind of like if I'm /stopcasting myself so that the same spell in the middle of the GCD ring that's showing starts all over again. It looks to me like the algorithm gets stuck in the middle of the GCD wait and restarts again, we're talking maybe a few milliseconds but it's crazy :) Ok when it's M+ I'll do a snapshot on some boss when it's cast. Or is there a dummy where I can practice counterpsell?

**Comment by Hekili** [comment]
Let's keep the two distinct issues you're reporting in separate paragraphs from here forward.

The state of the GCD is pulled directly from the game and updated independently of recommendations.  That could mean an ability is modeled incorrectly as to whether it is on GCD or not, so that initial recommendation expects to wait for GCD and then the actual GCD isn't applied.  Is it the same spell each time?  A different spell?  Something that happens *while* casting a particular spell, but impacting other spells?

For Counterspell, there are all sorts of enemies that will cast spells.  You could go to a Primal Storm event and there's usually something that will hard cast a spell.

**Comment by Hekili** [comment]
@marekCs Any new information?

**Comment by marekCs** [comment]
Yes, I was checking the Warning section and there is this info:
Update: Interface/AddOns/Hekili/State.lua:1103: attempt to index global 'debuff' (a nil value)

[string "@Interface/AddOns/Hekili/State.lua"]:1103: in function <Interface/AddOns/Hekili/State.lua:1101>
    [string "=(tail call)"]: ?
    [string "=(tail call)"]: ?
    [string "@Interface/AddOns/Hekili/State.lua"]:7085: in function `TimeToReady'
[string "@Interface/AddOns/Hekili/Core.lua"]:829: in function `GetPredictionFromAPL'
        [string "@Interface/AddOns/Hekili/Core.lua"]:1436: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1816: in function <Interface/AddOns/Hekili/Core.lua:1483>

**Comment by marekCs** [comment]
I also found a small mob in the woods that casted me so I took a snapshot that the counterspell didn't appear:
[https://pastebin.com/N9B72WEY](https://pastebin.com/N9B72WEY)

**Comment by Hekili** [comment]
For that target, it's unclear whether the spell was actually interruptible.  But I'm posting 1.6 now which addresses the warning you reported and may impact recommendations stutter or periods where recommendations were not updating.

**Comment by marekCs** [comment]
Interrupt works on the last patch, thx and good job.. But stuttering still present.

**Comment by Hekili** [comment]
By stuttering, you mean the CD spiral updating in progress, or something different?

The more actual context for it occurring you can provide, the more likely it can be diagnosed.

**Comment by vairey** [comment]
Hi Hekili, I've noticed this issue too on my frost mage. 

The recommendations are stable for Primary. I have 3 recommendations showing, and the string only changes if something procs, as expected. 

For AOE, the recommendations, current and future, change rapidly. Often, it recommends a string of frostbolts then quickly changes its mind. I took a snapshot during an AOE rotation, hopefully it sheds some light (I'm new to snapshots, hopefully I've done it right)  https://pastebin.com/5kNwK4t3

**Comment by Hekili** [comment]
If the situation is that recommendations change, it's always a matter of fight circumstances changing requiring a change in recommendations.  There are all sorts of things that the addon must simply react to.

It also makes it so a single snapshot doesn't help a whole lot, because it's hard for you to know when to snapshot for the "before" picture and when to snapshot immediately after the change.  So, recommendations changing isn't that weird, and I'm not sure why that would be described as "stuttering."

In your case, is there anything else it recommending a string of Frostbolts and then changing that might help me track it down?  Is it when you've just cast Flurry, or just after casting Flurry?

**Comment by marekCs** [comment]
"_It also makes it so a single snapshot doesn't help a whole lot, because it's hard for you to know when to snapshot for the "before" picture and when to snapshot immediately after the change. So, recommendations changing isn't that weird, and I'm not sure why that would be described as "stuttering._"

It's probably best if you try it yourself on the beta, please. I don't think we can describe it any better. We're just saying that with other classes/specs, changing recommendations behaves differently, it's pretty smooth, here it's choppy. And no one else knows the addon better than you, so you might know in a sec what we've been talking about for the past two days.

I've observed this most around the need to cast spells Flurry, Ice Lance and Frostbolt. But like I said, best if you try it yourself. If you don't have the time, we can't describe it any better.

**Comment by Hekili** [comment]
I'm surprised that it needs to be said, but *of course I'm trying it myself.*  What I see and how I interpret it may be different from what you're seeing and how you're interpreting it.  That's why I ask for more detail.

**Comment by marekCs** [comment]
> I'm surprised that it needs to be said, but _of course I'm trying it myself._ What I see and how I interpret it may be different from what you're seeing and how you're interpreting it. That's why I ask for more detail.

Thanks for the information. Ok, I did the mage on 60 at retail yesterday, bought the primal gear today and everything seems to be fine now. I think it was due to the small Haste and large GCD and the overclocking associated with it. I actually had 2% Haste on the beta only and now have slightly over 20% and it works fine. Thanks
