### ISSUE TITLE
Vengeance DH doesn't ever seem to want to cast Sigil of Flame

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#1989]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

According to rotation guides Sigil of Flame should be used when below 70 Fury (and to keep up Frailty). Hekili almost never suggests Sigil of Flame regardless of Fury.

### How to Reproduce

Play Vengeance DH with Hekili

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAgIUCREARCQCgEtEJCJIJtkUSIJhSkEAAAAA

### Snapshot

https://pastebin.com/AbJ7JKEx

**Comment by Hekili** [comment]
This should be addressed in the latest release (10.0.2-1.5).
