### ISSUE TITLE
[Request] Interrupt Slider

### ISSUE THREAD

**Issue by j3llevdb** [Hekili/hekili#199]
Hey,
Adding a %-Slider to only show interrupts at a certain % of the current cast would be golden!
Greetz

**Comment by Hekili** [comment]
This isn't a bad idea, at all.  I'm curious as to what prompted it.  By default, the addon tries to interrupt in the last GCD of a cast or the first GCD of a channel.  Is that not sufficient?

**Comment by j3llevdb** [comment]
well, im usually quite focussed on my hekili square, and the interrupt often shows up too late for me to react to it. With other words, it shows up, and by the time i have reacted to it, the cast is over, but i still pressed my interrupt and so it goes on cd without having anything interrupted. If i could back down the slider a bit, at lets say 80% of the cast, i would have more time to react.

**Comment by j3llevdb** [comment]
Also, when ur playing fury warrior with some gear, sometimes ur hastelevels go out of the roof, wich reduce GCD by a ton. At this point it gets even trickier

**Comment by Hekili** [comment]
Have you tried having the addon show interrupts separately?  See Toggles.

**Comment by j3llevdb** [comment]
i havent no, ill look into it. its so annoying tho to get this properly tested! blizzard should have a 24/7 casting dummy somewhere.

**Comment by j3llevdb** [comment]
still a slider wouldnt be a bad idea

**Comment by MarkusWo** [comment]
It could be latency issues or my own human reaction time but ever since interrupts are being shown at the last gcd of a cast I miss every single one of them. I like the idea of not showing interrupts from the start of any cast, as Hekili used to do, but now I miss most interrupts.
