### ISSUE TITLE
BM Hunter not recommending Kill Command

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#1990]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Kill Command sitting at 2 charges but Hekili not recommending it.

### How to Reproduce

Play BM Hunter using Hekili, never get recommended Kill Command.

### Talent Loadout

B0PAIlFMjeNhnEouGfV8Ij2uShgWCACBAAAAAAAAAAgGRKCEROgkIOQOQoJEhkQkEhGHIRA

### Snapshot

https://pastebin.com/rpgsRfsA

### Additional Information

Screen shot showing Kill Command with no cooldown at 2 charges but still being recommended Cobra Shot.

https://imgur.com/saVrrhw

**Comment by Hekili** [comment]
This happened because "Check Pet Range" is enabled but Pet-Based Target Detection is not enabled/set up.  I'm going to make the addon handle this more gracefully, but I would strongly recommend setting up pet-based target detection anyway. See /hekili > Beast Mastery > Targeting.

**Comment by jmusick** [comment]
ty

**Comment by Hekili** [comment]
This should be addressed in the latest release (10.0.2-1.5).
