### ISSUE TITLE
Howling Blast / Obliterate issue

### ISSUE THREAD

**Issue by aleksisyrjamaki** [Hekili/hekili#1991]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I am using a non-standard talent setup on a Frost DK. Specifically the leveling build from Wowhead. Fresh level 60 without covenants/legendaries, though they wouldn't work in Stormwind anyway. It recommends me to use Howling Blast without Rime when Frost Fever is applied. Obliterate is only recommended when Killing Machine procs. Raidbots is simulating the rotation for the character correctly.

### How to Reproduce

1. Enter game as Frost DK
2. Import the Wowhead leveling build
3. Fight something
4. See the recommendations

### Talent Loadout

BsPAdLUHklrTr3hBIcYWdbnCGfgIAQIJcgISEIJJhEIJRSISAkkQkkkkkSAAAAAAAAAAAAA

### Snapshot

https://pastebin.com/Vfb4UL8n

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cbEZvo28Sdq8owuVyrdv3K

**Comment by angrydanger** [comment]
I'm using a variation of that build (BsPAdLUHklrTr3hBIcYWdbnCGLAISIJcg0iEgIJhASSkkISIQSCRSSSSKBAAAAAAAAAAAAA) and can confirm Howling Blast is recommended by Hekili as the primary rune spender. Seems to only occur when using the 2H build. Tried RofFC and RI runeforge and made no difference.

**Comment by angrydanger** [comment]
This only occurs in single target. AOE recommends appropriate spells.

**Comment by Hekili** [comment]
This should be addressed in the latest release (10.0.2-1.5).  Please let me know if you see otherwise.
