### ISSUE TITLE
Unknown symbol in suggestion window

### ISSUE THREAD

**Issue by Aillip** [Hekili/hekili#1992]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Icon in the left most "square" is not available to me.  I have looked through the Shaman, and elemental talents and skills graph and was unable to locate the icon in question.  I have also tried each talent and spell to see if it would activate or clear that icon, but nothing I have tried has any effect on the icon.  Is it maybe a place holder for an ability, spell, or talent that I have not reached the proper level for?

Looking forward to your reply.

![WoWScrnShot_111822_175229](https://user-images.githubusercontent.com/118574324/202817218-2970c011-9204-49e8-bec8-a0ad2f986097.jpg)

### How to Reproduce

1Select character, then enter game
2Hekili comes on screen with the icon on the left, and to this point nothing will satisfy its use, and it remains as it is even when using spell flash as a back up priority assit.

### Player Information (Link)

```Text
build: v10.0.2-1.4
level: 60 (60)
class: SHAMAN
spec: elemental

talents: aftershock
    ancestral_defense = 1/1
    astral_shift = 1/1
    brimming_with_life = 1/1
    call_of_fire = 1/1
    call_of_thunder = 1/1
    capacitor_totem = 1/1
    chain_lightning = 1/1
    deeply_rooted_elements = 1/1
    earth_shock = 1/1
    earthquake = 1/1
    echo_chamber = 1/2
    echo_of_the_elements = 1/1
    elemental_fury = 1/1
    elemental_warding = 2/2
    eye_of_the_storm = 2/2
    fire_and_ice = 1/1
    fire_elemental = 1/1
    flames_of_the_cauldron = 1/1
    flow_of_power = 1/1
    frost_shock = 1/1
    hex = 1/1
    improved_lightning_bolt = 2/2
    lava_burst = 1/1
    lava_surge = 1/1
    magma_chamber = 2/2
    master_of_the_elements = 2/2
    natures_fury = 2/2
    natures_guardian = 2/2
    planes_traveler = 1/1
    primordial_fury = 1/1
    purge = 1/1
    refreshing_waters = 1/1
    spirit_wolf = 1/1
    static_charge = 1/1
    stormkeeper = 1/1
    thunderstorm = 1/1
    totemic_focus = 2/2
    tumultuous_fissures = 1/1
    unrelenting_calamity = 1/1
    wind_rush_totem = 1/1
    wind_shear = 1/1
    winds_of_alakir = 2/2
    windspeakers_lava_resurgence = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: [korayn]

sets: enforcers_stun_grenade = 1

gear: arans_relaxing_ruby = 1
    barons_oaken_scepter = 1
    boneshatter_gauntlets = 1
    clasp_of_unity = 1
    cypheretched_ring = 1
    enforcers_stun_grenade = 1
    enigmatic_cowl = 1
    nobles_birthstone_pendant = 1
    renowned_guild_tabard = 1
    ruined_crest_of_lordaeron = 1
    shield = 1
    signet_of_the_false_accuser = 1
    theurgic_starspeakers_adornment = 1
    theurgic_starspeakers_bracers = 1
    theurgic_starspeakers_ringmail = 1
    theurgic_starspeakers_sabatons = 1
    theurgic_starspeakers_shawl = 1
    theurgic_starspeakers_tassets = 1

legendaries: none

itemIDs: 110017, 142157, 172324, 178824, 179557, 183039, 188919, 188920, 188922, 188924, 188926, 188927, 189845, 190360, 190473, 190632, 69210

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Elemental
    petbased = false
    potion = potion_of_spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    stack_buffer = 1.1

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = false [overridden]
    interrupts = true 
    mode = automatic 
    potions = true 

keybinds: 
    astral_shift        = -   [01]
    chain_lightning     = 7   [01]
    earth_shock         = W   [06]
    earthquake          = E   [06]
    flame_shock         = S   [01]
    flametongue_weapon  = =   [01]
    frost_shock         = .   [06]
    ghost_wolf          = 2   [01]
    healing_surge       = R   [06]
    hex                 = 9   [01]
    lava_beam           = 7   [01]
    lava_burst          = A   [01]
    lightning_bolt      = D   [01]
    spiritwalkers_grace = 8   [01]
    stormkeeper         = Q   [06]
    wind_shear          = L   [06]

warnings: none
```

### Error Messages (Link)

```Text
No error message in game is generated.
```

### Contact Information

Grey#3178

**Comment by jmusick** [comment]
Probably a trinket or some other on use item you have.

Edit: Yep, looks like it's this thing based on your snap shot: https://www.wowhead.com/item=110017/enforcers-stun-grenade?bonus=9013

Mystery icons are almost always a on use item I'm not familiar with the icon of, or a racial.

**Comment by Aillip** [comment]
Thank you, for such a prompt reply. I'll keep a look out for this item.

**Comment by vond82** [comment]
It's the versatility grenade from ID btw

**Comment by Hekili** [comment]
If you see an icon you don't recognize in the list of recommendations, you can use the Pause feature to freeze the display and take a look.  Obviously, this isn't something you want to do in the middle of a raid encounter, but you can check it out with target dummies or in other scenarios.

The default keybind for Pause is `ALT-SHIFT-P`.  When paused, you can place the mouse over the icon in question.  The tooltip will show for that icon, and the ability itself will be listed at the top of the tooltip.

Most often, if you see an icon you don't recognize, it's going to be a trinket or other piece of usable gear (sometimes weapons or bracers).  Check your character sheet and see if the icon matches gear that you are wearing.

**Comment by Aillip** [comment]
Thank you once again!
I completely overlooked a trinket I have, and that is the unknown icon
(Enforcer's Stun Grenade)
I'm very sorry to have taken time that someone else might have needed.  I
will be aware of Hekili prompting for trinkets from here on out.
Thank you for not making me feel, as dumb as I do already.
Heds demise was the greatest thing to happen to me in game, because I found
your mod and it has been rock solid from the beginning.

Respectfully,

Aillip
