### ISSUE TITLE
outlaw rogue showing wraps of electrostatic potential while in stelth

### ISSUE THREAD

**Issue by JimA1966** [Hekili/hekili#1993]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

showing wraps of electrostatic potential while stealth

### How to Reproduce

1. enter game as outlaw rogue
2. stealth to target
3. start rotation
4. RtB WofESP is next before ambush

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAABJJAJJRSLJJQgEJSAkIAAAAAAAJBpRJJIJJpEAAAA

### Snapshot

https://pastebin.com/thqGJKVC

### Contact Information

Asgar#6151

**Comment by Hekili** [comment]
This should be addressed in the latest release (10.0.2-1.5).
