### ISSUE TITLE
Frost mage - Frozen Orb not getting recommended

### ISSUE THREAD

**Issue by vairey** [Hekili/hekili#1999]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my Frost Mage, I expected the rotation to include Frozen Orb for both ST and AOE, however it is never recommended. 

I expected it to appear as part of my opener when I initiate combat, and then again when it comes off cooldown while I'm in combat. It's not appearing in either case.

Love your work on the addon <3 

### How to Reproduce

1. Enter game as Frost Mage
2. Enter combat, either single or multi target
3. Follow recommendations
4. Note that all other cooldowns will be refreshing (e.g. rune and icy veins will be coming back up after initial use), addon will be recommending a string of Frostbolts (between procs), and Frozen Orb still hasn't been recommended and is available/off cooldown. 

### Talent Loadout

BAEAHVkVsxxZrVqBmAzlSR2f7LIBKJJIJNg0kIiISEAAABQkQSSSiWSSiAAAAAAAAAAkA

### Snapshot

https://pastebin.com/MTgMY6dA

### Additional Information

In the snapshot, I've blown my cd's. It's recommending frostbolt over frozen orb.

**Comment by vairey** [comment]
In the paste above, it shows Frozen Orb as disabled - but that's not what my ui shows, as below. I haven't altered these settings, these are out of the box. 

![image](https://user-images.githubusercontent.com/118662417/202899038-ff22b50d-f7ff-4f42-a1b4-d308b683551f.png)

**Comment by Hekili** [comment]
> toggles: cooldowns = false 

It's on the Cooldowns toggle and the Cooldowns toggle is not active, so it will not appear.  See /hekili >Toggles.
