### ISSUE TITLE
Config UI tooltip misleads re: current state

### ISSUE THREAD

**Issue by KevinMeinon** [Hekili/hekili#2000]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Current Rage is wrong for prot. It's either 10 too low or settles at 50, if rage has been capped for a while. Also shows 40 rage, when I have no rage at all.

![image](https://user-images.githubusercontent.com/3797846/202902595-eebe0fa4-b960-44ee-bee7-1029a7d7b356.png)

![image](https://user-images.githubusercontent.com/3797846/202902707-a291b578-e1d8-4351-9acd-74b14ea06954.png)

### How to Reproduce

Hit dummy with prot warrior and look at rage.current in hekili prio list.

### Talent Loadout

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkg0SKCpUQEIUkAlkEACcA0CJJAHARCAAAAAAAQAAoUaA

### Snapshot

https://pastebin.com/GTjuPZwv

**Comment by Hekili** [comment]
Is this something you're seeing in a way that impacts actual recommendations, or just something you see in the options interface?

For example, do you see recommendations to generate rage when you're full or capped, or recommendations to spend rage when you don't have any?

**Comment by Hekili** [comment]
Your snapshot shows a lot of issues in custom priorities.  Do you experience these issues without your custom priorities loaded?  (I understand that it's not the selected priority in your snapshot.)

**Comment by KevinMeinon** [comment]
> Is this something you're seeing in a way that impacts actual recommendations, or just something you see in the options interface?
> 
> For example, do you see recommendations to generate rage when you're full or capped, or recommendations to spend rage when you don't have any?

Just checked this and it should have been something I checked before opening the issue. Even though the options menu will return "false" if the condition is: ignore pain if rage > 110; for example, since rage will be shown as 50 instead of 115, hekili will still recommend ignore pain and if I pause hekili it will show rage.current as 115 if I mouseover the recommended ability. 

So no, it does not seem to actually impact recommendations but it is still confusing. 



> Your snapshot shows a lot of issues in custom priorities. Do you experience these issues without your custom priorities loaded? (I understand that it's not the selected priority in your snapshot.)

I do, yes. I am working on a few custom priorities currently though and that might explain the issues, like missing variables and stuff, unless there are some bigger issues you might have encountered.

**Comment by Hekili** [comment]
> So no, it does not seem to actually impact recommendations but it is still confusing.

Yeah, it *is* misleading.  I've investigated and it's simply a matter of the options UI not fully resetting the current state when giving you a preview of options.  It's pretty trivial to fix, but doesn't actually impact recommendations that are generated.  When recommendations are generated, the addon *does* fully reset.

**Comment by Hekili** [comment]
This should be resolved in 1.6.1 which is being built now.
