### ISSUE TITLE
Add Twisted Judgement to the Abilities List

### ISSUE THREAD

**Issue by Zepher01** [Hekili/hekili#2001]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Please add Twisted Judgement (The spell cast when using Gavel of the First Arbiter) to the list of abilities that can be disabled for recommendation. Currently whenever the weapon is equipped the ability must always be used in order for other recommendations to be provided which is for me undesirable.

### Contact Information

bob.ilmonen@gmail.com

**Comment by Hekili** [comment]
This already exists.

/hekili > Gear and Trinkets > Gavel of the First Arbiter

**Comment by Zepher01** [comment]
Fantastic! Thanks.  Sorry I missed that.
-------- Original message --------From: Hekili ***@***.***> Date: 2022-11-20  10:03 a.m.  (GMT-05:00) To: Hekili/hekili ***@***.***> Cc: Zepher01 ***@***.***>, Author ***@***.***> Subject: Re: [Hekili/hekili] Add Twisted Judgement to the Abilities List (Issue #2001) 
This already exists.
/hekili > Gear and Trinkets > Gavel of the First Arbiter
