### ISSUE TITLE
Blood DK Priority Issue: Not Recommending Death and Decay Casts for multiple globals when there are charges available and Death and Decay is not currently active

### ISSUE THREAD

**Issue by gnew95** [Hekili/hekili#2004]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

As Blood DK Death and decay is often not recommended for multiple globals even when there are charges available and Death and Decay is not currently active. This applies even when taking talents such as Sanguine Ground, Unholy Ground and Cleaving Strikes that incentivize high Death and Decay uptime.

### How to Reproduce

1. Enter the game as Blood DK
2. See that the priority helper is often not recommending Death and Decay casts even in AOE with Sanguine Ground, Unholy Ground and Cleaving Strikes talented.
3. Thank you for all your hard work as always!
![image](https://user-images.githubusercontent.com/101494776/202929304-b3b36621-adf7-436b-9192-9b9475937015.png)

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDCJBhk4ASLASSiEJQSSkAAAAAAISCEJNhIBAAESSEAAAA

### Snapshot

https://pastebin.com/gn6WqZJP

**Comment by Hekili** [comment]
You didn't have to open a separate ticket, but anyway.

Death's Due was active in your snapshot, so Death's Due or Death and Decay would not be recommended.

Your screenshot is a different set of circumstances.  I can't tell you why without a snapshot that matches.  If you want to send a snapshot and screenshot together, hitting Pause will create both at the same time as long as "Take Screenshot" is still checked in /hekili > Snapshots.

**Comment by gnew95** [comment]
I tried to update my snapshot and screenshot to be more in sync. Upon further testing I think what is going on is that Death's Due has two components. 1: The ground effect that scales with most of our talents and 2: The damage reduction Strength draining effect. The rotation helper is not updating you to cast Death's Due again until the strength draining effect is gone from the mob which usually means around 10-12 seconds of downtime of the ground effect. That being said this is most likely only a problem with the night fae's version of Death and decay so this may become a non issue come dragonflight!

**Comment by Hekili** [comment]
That looks like you're correct; I've updated Death and Decay to only rely on its actual buff rather than swapping for Death's Due.  I'll post that release in a little bit.
