### ISSUE TITLE
Retribution recommending HoW during Crusade

### ISSUE THREAD

**Issue by D3troiit** [Hekili/hekili#2007]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

hammer of wrath still being shown in priority list despite having crusade talented which does not make hammer of wrath usable on any target despite health % but is still being shown first in the priority list whenever it is off cd (except when templar verdict or divine storm have enough holy power to be used)

### How to Reproduce

-be retribution paladin
-take crusade talent in spec tree
-pop crusade on any target above regular health % for hammer of wrath to proc normally
-be unable to use hammer of wrath as it does not have the same effect as avenging wrath

### Talent Loadout

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAAEAiWaJJkDAQKpkwBalAAAAAAAIEJJplEkQBHAUiSA

### Snapshot

https://pastebin.com/0Lf2nGFk

### Additional Information

not a currently max level character (lvl 53 as of reporting the issue)

### Contact Information

D3troit#2862

**Comment by cremor** [comment]
This is not correct. I just tested it ingame and I can use Hammer of Wrath just fine on targets with any health percentage when Crusade is active.

**Comment by Hekili** [comment]
Crusade still combines with other Avenging Wrath talents.  You have Avenging Wrath talented in the Paladin tree, which allows HoW to be cast on any target.

![image](https://user-images.githubusercontent.com/9438134/203124278-52dab1df-b177-46dc-99e7-86c3b9d2b5f7.png)

![image](https://user-images.githubusercontent.com/9438134/203124340-943b4954-4b7d-4d9a-9408-1b120b0d0aab.png)

It's possible that these combination mechanics are tied to a leveling upgrade you don't have since your character is 53, though.  Let me investigate.

**Comment by D3troiit** [comment]
further investigation seems to indicate that this is a level  58 thing as that is when hammer of wrath becomes rank 2. which is seemingly no longer listed in the spellbook but is listed on hammer of wrath's rank 2 page on wowhead. link to page: https://www.wowhead.com/spell=326730/hammer-of-wrath 

so yeah i did misreport this. but is still sort of an issue if you have avenging wrath talented during leveling

but i should have done a little more research beforehand.

**Comment by Hekili** [comment]
Thanks.  I've reported the issue to Blizzard and am updating the addon not to trust that HoW is usable during AW until level 58.
