### ISSUE TITLE
Odyn's Fury not recommended unless using annihilator + maybe doesnt know it enrages

### ISSUE THREAD

**Issue by chevyn11** [Hekili/hekili#2009]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

On a Fury warrior Odyns fury is not recommended unless annihilator is talented. This is due to the new priority only having this line for Odyn's fury:

```odyns_fury,if=talent.annihilator&buff.enrage.up&(spell_targets.whirlwind>1|raid_event.adds.in>15)```

but from simc it is missing the line (on a higher priority, before rampage): 

```odyns_fury,if=!talent.annihilator&buff.enrage.up&(spell_targets.whirlwind>1|raid_event.adds.in>15)```

also attached a simc link for where I found this APL.

----

on a separate note, when trolling through the snapshot of odyn's fury it shows the buff.enrage.up value is false
```... & buff.enrage.up[false] & ...```

I'm wondering if this is correct as with the new titanic_rage talent then odyn's fury will enrage you so this should always be true. Perhaps it should be:
 ```... (talent.titanic_rage.enabled | buff.enrage.up) ...```
or if there's some underlying code changes that need to be made to predict that odyn's fury enrages you before it does its damage (similar to rampage). 

### How to Reproduce

Enter the game as Fury Warrior
Use talent loadout shown below
Do rotation against multi-targets (or single target)
Odyn's Fury is never recommended

### Talent Loadout

BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAAQCKJEEBhIwB0ISICEESCJRSEAJJJhWaBQSSAAAAB

### Snapshot

https://pastebin.com/xtjrsYCZ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bvKkAK2X6whFtMTFiprzqd/simc

### Contact Information

chevyn#4512

**Comment by Hekili** [comment]
Thanks.  I have added the missing lines to the Fury priority in 1.7.1.

I also tested and confirmed that Titanic Rage's Enrage effect is granted prior to the Odyn's Fury damage going out, so there's no need to wait for Enrage before using Odyn's Fury with the talent.
