### ISSUE TITLE
[FDK] New rotation with Icecap and no big changes in the rotation of the BoS

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#201]
I now would like to continue the topic with Bos. Because look, there in the rotation there are small shoals. Although it may not. But let's say. Why do we have Cold heart immediately as soon as 20 stacks appear? I noticed that rotation uses them very rarely from here we lose huge DPS in idle. While we have accumulated 20 stacks, we can immediately merge them and start accumulating new ones.

Plus, I did what you said to remove Bos from the cooldowns. But rotation still suggests using an ice strike and reducing the number of runic power. I would like to offer in such a sulchae condition. Suppose, if we have ready-made 3 abilities, this is a breath of sindragosa, Pillar of Frost, Empower Rune Weapon, then the runic power can only spend up to 70+ runic power, no less. So that during the use of the macro for the simultaneous use of 3 abilities we were always ready. And I also noticed that Pillar of Frost is not used correctly when it remains for 15-20 seconds. before the rollback breath of sindragosa. In this regard, it is better to delay it, since we’ll wait with Pillar of Frost for 15-20 seconds rather than wait 35 seconds for it to roll back.

**Comment by Hekili** [comment]
I guess I would suggest that you build your priority in SimulationCraft, test it, and then send me results and I'll see about implementing any changes.
