### ISSUE TITLE
Flame shock as Enhancer not shows up in the Priority buttons

### ISSUE THREAD

**Issue by Chabonition** [Hekili/hekili#2012]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

The Flameshock is normally the first Prio after the Lightning bolt but on Enhancement Priority the Button for Flameshock dont show up. so if you play with the addon you dont even use Flameshock what is a Lot of DPS loose.

### How to Reproduce

1. enter the game wotlk classic as a enhancer shaman
2. select the enhancer priority 
3. go to a trainingsdoll and click the spells from the addon
4. you will see you dont use the flame shock in the Priority

### Snapshot

https://pastebin.com/xQFbbwL3

### Contact Information

schulz.thiemo@web.de

**Comment by Hekili** [comment]
In your snapshot, Flame Shock wasn't recommended because your target was expected to die in fewer than 3 seconds.

<details>
<summary>Details</summary>

        15.  flame_shock ( default - 10 )
        The action (flame_shock) is usable at (1.37 + 1.36) with cost of 747 mana.
         - the action is ready before the current recommendation (at +1.36 vs. +8.00).
         - this entry's criteria FAILS: ! ticking[false] & target.time_to_die[2.27] >= 9

</details>

**Comment by Chabonition** [comment]
it was a trainingsdummy so i dont think so but i will test it in raid^^ Thank you

**Comment by Hekili** [comment]
It was likely a target dummy sitting at almost no health, then.  Death timers don't care that about something being a dummy; it only cares about how quickly the health would trend down to zero.
