### ISSUE TITLE
Avenger's Shield does not generate Holy Power any more

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#2013]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The addon still thinks that Avenger's Shield generates Holy Power, but that is not the case any more. This can lead to wrong queue suggestions, e.g. a Holy Power spender on queue position 1 after Avenger's Shield if the player only has 2 Holy Power.

### How to Reproduce

1. Play Protection Paladin.
2. Build to 2 Holy Power.
3. See that Avenger's Shield is suggested as next ability.
4. See that Shield of the Righteous is shown as the first queued ability.

### Talent Loadout

BIEAwtJ2KpR8WbGzhz/jy2AP80iWChocgIJhSDJSQCBAAAAAAAAAAAAAANRSSIQSUSJAloEA

### Snapshot

https://pastebin.com/EG5FufPZ

### Additional Information

Unrelated to the issue, but I just noticed it: The link to Pastebin in your issue template is wrong.

**Comment by Hekili** [comment]
Thanks; this will be resolved in 1.7.2.
