### ISSUE TITLE
Please add empower info into Weakauras ScanEvents

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2017]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Please add Queue[1].empower_to as the fourth parameter to the WeakAuras.ScanEvents("HEKILI_RECOMMENDATION_UPDATE") event. Just like you put Queue[ 1 ].indicator, this is very useful info for WA creators.

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
