### ISSUE TITLE
Revenge and Demo Shout not being suggested for Prot Warrior

### ISSUE THREAD

**Issue by Rikluz** [Hekili/hekili#2018]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After beginning combat the profile suggests revenge 2 or 3 times, but then stops entirely and sits at capped rage. I do not have any rage reserved for mitigation configured.

Also demoralizing shout is never suggested in the prot rotation by default.

### How to Reproduce

1. enter the game as a prot warrior
2. begin combat with an enemy
3. see that revenge or demo shout are not suggested after a few seconds

### Talent Loadout

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQSLpkgWBRgQRiElkEgAAtQSCIQIAAAAAAAABAAlGA

### Snapshot

https://pastebin.com/JvZcn3bq

### Additional Information

This seems to have just started in the last 2 or 3 builds. I have not adjusted anything on my end during this time frame!

Thank you, I love this addon!

### Contact Information

Akuda#7860

**Comment by Hekili** [comment]
One issue of note:  Demoralizing Shout is used when you're tanking, so a dummy that doesn't target you will not result in Demoralizing Shout recommendations.

For Revenge, it looks like there are some conditions related to Rage that need to be removed from the priority.  I'm investigating now and have asked @Wyste for feedback.

**Comment by Rikluz** [comment]
> One issue of note: Demoralizing Shout is used when you're tanking, so a dummy that doesn't target you will not result in Demoralizing Shout recommendations.
> 
> For Revenge, it looks like there are some conditions related to Rage that need to be removed from the priority. I'm investigating now and have asked @Wyste for feedback.

Noted about Demo Shout - I should have known that.

Appreciate you looking into this!

**Comment by Hekili** [comment]
I made adjustments for Prot in 1.8.1 that should've gone ahead and used Demo Shout more (it generates rage, after all) and Revenge should be used more frequently (depending on your choices in /hekili > Protection).
