### ISSUE TITLE
[Arms Warrior] Thunderclap not recommended in AoE with "Blood and Thunder" Talent

### ISSUE THREAD

**Issue by RussellAnas** [Hekili/hekili#2019]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In AoE scenarios, with the 'Blood and Thunder' talent, Thunderclap is not recommended ever, only Rend. But Rend only applies on primary add, not on all the surrounding adds. This is even when the adds are target dummies with ample health to justify putting rend on all of them.

### How to Reproduce

1. Login as Arms Warrior
2. Talent into Blood and Thunder
3. Do dps on swarm style dummies
4. Rend gets recommended (not thunderclap)

### Snapshot

https://controlc.com/ee58e9e1e

**Comment by Hekili** [comment]
This was addressed in 1.8.1.
