### ISSUE TITLE
Soul Carver missing from Veneance Demon Hunter rotation/Cooldown or Defensives

### ISSUE THREAD

**Issue by Aryax-19** [Hekili/hekili#2025]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Soul Carver is missing from Veneance Demon Hunter rotation/Cooldown or Defensives it is never recommended or I'm not able to toggle it.

### How to Reproduce

Use Hekili as Vengeance Demon Hunter and have the Soul Carver talent.

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAgIUCREARCwBAIRLRiEJhk0SSJhkEKRSAAAAA

### Snapshot

https://pastebin.com/WzmbSNQK

### Contact Information

Aryax#2713 (discord)

**Comment by Hekili** [comment]
This is partially addressed with 1.8.3; I am using Wowhead/Icy-Veins guides to recommend it with sufficient stacks of Frailty.
