### ISSUE TITLE
[Fury Warrior] - Onslaught not been showing properly in the suggestions

### ISSUE THREAD

**Issue by Rockytcp** [Hekili/hekili#2026]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For fury warrior, when i have Onslaught talented the suggestions display are not showing the ability and causes a strange issue when onslaught is off cooldown (when the ability is ready to be pressed). The suggestion display freezes until i cast onslaught, then it returns to the normal recommendations. it happens everytime onslaught is off cooldown. It used to be normal, but after i updated the addon via curseforge a few days ago it started causing the issue.

In the image below it shows more or less the problem.

![Onslaught bug](https://user-images.githubusercontent.com/56940852/203666570-f0bb7294-58c0-4f4e-9209-cb5dd1344b10.jpg)

### How to Reproduce

1 - Enter the game and as fury warrior choose the onslaught talent (botton right in the spec tree).
2 - Go fight some mobs using the hekili addon.

### Talent Loadout

BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAABgWCBRUEiEQjIhkQcAEkQSkkkAIRSQEIRSSAAAAB

### Snapshot

when i press the keys (alt-shift-p or alt-shift-[) it throws an error, ill put in the additional information. sorry

### Additional Information

Message: Interface/AddOns/Hekili/Dragonflight/WarriorFury.lua:1314: attempt to call global 'addStacks' (a nil value)
Time: Wed Nov 23 21:10:15 2022
Count: 1
Stack: Interface/AddOns/Hekili/Dragonflight/WarriorFury.lua:1314: attempt to call global 'addStacks' (a nil value)
[string "@Interface/AddOns/Hekili/Dragonflight/WarriorFury.lua"]:1314: in function `handler'
[string "@Interface/AddOns/Hekili/State.lua"]:6073: in function `RunHandler'
[string "@Interface/AddOns/Hekili/Core.lua"]:1973: in function `Update'
[string "@Interface/AddOns/Hekili/Options.lua"]:10704: in function `MakeSnapshot'
[string "@Interface/AddOns/Hekili/Options.lua"]:10661: in function `TogglePause'
[string "@Interface/AddOns/Hekili/Options.lua"]:10801: in function `FireToggle'
[string "@Interface/AddOns/Hekili/UI.lua"]:2689: in function <Interface/AddOns/Hekili/UI.lua:2688>

Locals: (*temporary) = nil
(*temporary) = "slaughtering_strikes"
(*temporary) = 3
(*temporary) = "attempt to call global 'addStacks' (a nil value)

Message: Interface/AddOns/Hekili/Hekili.lua:338: bad argument #4 to 'format' (string expected, got nil)
Time: Wed Nov 23 21:07:55 2022
Count: 1
Stack: Interface/AddOns/Hekili/Hekili.lua:338: bad argument #4 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "@Interface/AddOns/Hekili/Hekili.lua"]:338: in function `SaveDebugSnapshot'
[string "@Interface/AddOns/Hekili/UI.lua"]:2188: in function <Interface/AddOns/Hekili/UI.lua:2133>

Locals: (*temporary) = "%s%s; %s"
(*temporary) = "Fury"
(*temporary) = ""
(*temporary) = nil
(*temporary) = "string expected, got nil"

Sorry, maybe its something on my end, some cache problem, i dont know.

Thank you very much for your work and sorry for my bad english.

### Contact Information

Rockytcp

**Comment by Wyste** [comment]
Opened PR #2027 to fix.

**Comment by Hekili** [comment]
This fix will be posted shortly.
