### ISSUE TITLE
Havoc DH, Sigil of Flame not being recommended

### ISSUE THREAD

**Issue by renori** [Hekili/hekili#2029]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Can't get addon to recommend Sigil of Flame outside of queue under any circumstance, even tried changing the condition to:

fury.deficit >= 80

### How to Reproduce

1. Enter game as a havoc DH
2. Talents: BEkACnvaHJn8GSPD6tpaeczPThkkEJig0SSEJCEAAAAAAAtkEQKkECJJpFBSAA
3.  Go thru rotation, getting under 30 fury w/o anything available to cast
4.

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPThkkEJig0SSEJCEAAAAAAAtkEQKkECJJpFBSAA

### Snapshot

https://pastebin.com/UcAFV6LQ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ftC7QjK8dyuZzYyZi5Ci8B

### Contact Information

Renori#9054

**Comment by Hekili** [comment]
> fury.deficit >= 80

That is narrowing the conditions for its use, not expanding them.  It's saying to only use when you're at least 80 Fury *below* maximum.

In the snapshot provided, there are two scenarios where Sigil of Flame would be recommended.

1. You have more than one target.
2. You have a Fury *deficit* of 30 or more.

Both of these conditions are contingent on not having a higher priority button to push, and most of your abilities are higher in priority.  In multi-target, it falls in the middle of your priority.  In single-target, it's pretty low, with only Demon's Bite, Fel Rush filler, Felblade, Vengeful Retreat filler, and Throw Glaive filler lower in priority.

You shouldn't need to try to keep Fury extremely low for Sigil of Flame to be recommended, but you do have to reach a point where you don't have a better button to push.  In your sim, this is 16 seconds into a single-target fight.  The next is 46 seconds.

In your snapshot, Sigil of Flames is initially on cooldown for a couple of seconds already, so you've pushed it.  Once its CD expires and you don't have a better button to push, it shows it would be recommended.

If you've seen it in the queue, but it doesn't make it to the first position, what leaps ahead of it?  Are you seeing anything consistent in that regard?

**Comment by renori** [comment]
Re: the fury deficit - I tried this to get it to use sigil as a generator,
when all fillers and generators were on CD.

To clarify I provided the snapshot with the default APL and that modified
condition removed.  I've taken a new snapshot - I think what is happening
may be that the addon is anticipating fury generation from the Demon Blades
talent, then changes the recommendation to the next spender/filler, instead
of Sigil of Flame.

https://pastebin.com/FB5ckEuy

**Comment by Hekili** [comment]
This snapshot you provided again shows Sigil of Flame on cooldown for a few seconds, otherwise it could've been recommended.  Is that not accurate?

**Comment by renori** [comment]
That's not accurate - sigil of flame was not used at all for the entire
snapshot.

**Comment by Hekili** [comment]
> That's not accurate - sigil of flame was not used at all for the entire snapshot.

A snapshot captures recommendations given at a particular moment.  Are you saying you never used Sigil of Flame prior to taking the snapshot?

**Comment by renori** [comment]
Yes, that is exactly what I am saying.  At no point did I use sigil of
flame while I tried to get it to come up as the primary recommendation.

**Comment by Hekili** [comment]
Thanks, this should be addressed in 10.0.2-1.8.7.
