### ISSUE TITLE
Assassination Rogue, Not Recommending Vendetta, Garrote, Vanish

### ISSUE THREAD

**Issue by c2lknt** [Hekili/hekili#203]
I spent about 30 minutes doing 5 minute sessions on a target dummy.  Vendetta was suggested in the opener, but never came back up after it was off CD.  Garrote also dropped off and wasn't recommended again.  (It seemed like Garrote was no longer recommended once Vendetta was off CD.)  Vanish was never recommended, though I have that toggled off in Outlaw, so maybe that applies to Assassination as well?

Here's the pastebin snapshot:

https://pastebin.com/xNbZLxZ4

~~edit: it also stopped recommending rupture, once that fell off.~~
edit2: I was wrong about this, rupture is still recommended.

**Comment by Hekili** [comment]
This should be resolved as of the latest releases.
