### ISSUE TITLE
Balance Druid:  Wild Mushrooms should spaced out 9 seconds in rotation when Fungal Growth talent is chosen

### ISSUE THREAD

**Issue by Guycicle** [Hekili/hekili#2030]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

This was working until today, it now suggests to blast all 3 Wild Mushrooms back to back even though with the Fungal Growth talent it is more DPS to use subsequent Wild Mushrooms once the Fungal Growth debuff has fully dropped from the target.

### How to Reproduce

Enter game as Balance Druid
Tick Wild Mushrooms talent and Fungal Growth
See how rotation is suggested

### Talent Loadout

BYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAQSiIQChkEkIgWCJJRaSgDEIlkSEEUAIA

### Snapshot

 https://pastebin.com/2DbQ17Je

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/52X6NqinxV9FZd9n8n6C9e

### Contact Information

Battlenet: Guycicle#2681

**Comment by Hekili** [comment]
Thanks, I will investigate.

**Comment by Guycicle** [comment]
It looks like it will separate the spells in AoE rotation but not Single
target. I was accidentally in multitarget mode on my raidbots link. Single
target actually does suggest dumping 3 at once. I really have no idea why
since it decreases damage by ~400dps. But I'll share with you the revised
raidbots link. https://www.raidbots.com/simbot/report/7AkhmYGgpacTh5G1Y8owmD
which Hekili does emulate.

**Comment by Hekili** [comment]
In 1.8.5, this will be spaced out based on the Fungal Growth dot.
