### ISSUE TITLE
Ability cooldown not returned properly if toggle has "Show Seperately" enabled

### ISSUE THREAD

**Issue by gfuto** [Hekili/hekili#2033]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When an ability has the "Required Toggle" set to a toggle that has "Show Separately" enabled the cooldown value is not returned correctly.

Take the havoc demon hunter ability "Blur" as an example. Blur's required toggle is "Defensives". Under hekili Toggles tab I have "Show Defensives" enabled but I get inconsistent cooldown values depending on whether the defensives toggle's "Show Separately" option is enabled or disabled when I reference "cooldown.blur.remains" in the APL. The following values are returned:
- "Show Separately" enabled: cooldown.blur.remains returns the max cooldown at all times
- "Show Separately" disabled: cooldown.blur.remains returns the actual remaining cooldown of blur

I believe the actual cooldown should be returned for an ability if it's "required toggle" is Enabled regardless if the "required toggle" is shown separately or not.
Is this behaviour expected? Is it possible to access an ability's attributes if that ability is on a toggle that has "Show Separately" enabled in another way? 

### How to Reproduce

Starting state:
- Class/Spec: Demon Hunter/Havoc
- Ability: Blur
- Ability's Required Toggle: Defensives
- Toggles/Defensives/Show Defensives: Enabled
- Toggles/Defensives/Show Separately: Enabled

Add the following constraint to an action list entry and accept:
cooldown.blur.remains

The cooldown.blur.remains value returns 60 with the starting state detailed above at all times regardless of the actual cooldown

Change Toggles/Defensives/Show Separately setting to **Disabled**

The cooldown.blur.remains value returns the actual cooldown of Blur (a number between 0-60 counting down) as expected.

### Player Information (Link)

```Text
build: v10.0.2-1.8.2
level: 60 (60)
class: DEMONHUNTER
spec: havoc

talents: accelerating_blade
    any_means_necessary = 1/1
    blazing_path = 1/1
    bouncing_glaives = 1/1
    burning_hatred = 1/1
    burning_wound = 1/1
    chaos_nova = 1/1
    chaotic_transformation = 1/1
    charred_warblades = 1/1
    collective_anguish = 1/1
    consume_magic = 1/1
    critical_chaos = 2/2
    dancing_with_fate = 2/2
    darkness = 1/1
    demon_blades = 1/1
    demonic = 1/1
    erratic_felheart = 2/2
    eye_beam = 1/1
    felblade = 1/1
    felfire_heart = 1/1
    first_blood = 1/1
    furious_throws = 1/1
    growing_inferno = 2/2
    illidari_knowledge = 2/2
    imprison = 1/1
    improved_disrupt = 1/1
    initiative = 1/1
    internal_struggle = 1/1
    looks_can_kill = 1/1
    master_of_the_glaive = 1/1
    pursuit = 1/1
    ragefire = 1/1
    rush_of_chaos = 1/1
    sigil_of_flame = 1/1
    soul_rending = 2/2
    soulrend = 2/2
    tactical_retreat = 1/1
    the_hunt = 1/1
    trail_of_ruin = 1/1
    unbound_chaos = 2/2
    unleashed_power = 1/1
    unrestrained_fury = 2/2
    vengeful_retreat = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: annoras_punctured_leggings = 1
    bromachs_disentombed_locket = 1
    catastrophe_signet = 1
    cyclonic_drape = 1
    dust_devil_epaulets = 1
    dust_devil_gloves = 1
    dust_devil_raiment = 1
    dust_devil_treads = 1
    dust_devil_wristbands = 1
    fist_of_the_treasure_seeker = 1
    galerider_crescent = 1
    seal_of_elemental_disasters = 1
    storm_hunters_insignia = 1
    troggskin_waistband = 1
    versatile_storm_lure = 1
    vision_of_foreshadowed_ends = 1

legendaries: none

itemIDs: 193668, 193800, 193809, 193811, 199356, 199357, 199358, 199361, 199363, 199380, 199381, 199382, 199416, 199555, 199645, 201305

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.05
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxTime = 100
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Havoc
    petbased = false
    potion = phantom_fire
    regularRefresh = 0.05
    throttleRefresh = true
    throttleTime = true
    demon_blades_acknowledged = true
    recommend_movement = true
    unbound_movement = true

toggles: cooldowns = true [separate]
    custom1 = true 
    custom2 = false 
    defensives = true [separate]
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = true 

keybinds: 
    annihilation     = D   [01]
    arcane_torrent   = í  [03]
    blade_dance      = 3   [01]
    blur             = 7   [01]
    chaos_nova       = 6   [01]
    chaos_strike     = D   [01]
    consume_magic    = 9   [01]
    darkness         = 8   [01]
    death_sweep      = 3   [01]
    disrupt          = 5   [01]
    eye_beam         = E   [03]
    fel_rush         = 4   [01]
    felblade         = U   [01]
    immolation_aura  = G   [03]
    imprison         = Y   [03]
    metamorphosis    = R   [03]
    sigil_of_flame   = F   [03]
    the_hunt         = Q   [03]
    throw_glaive     = T   [03]
    torment          = C   [03]
    vengeful_retreat = S   [03]

warnings: none
```

### Error Messages (Link)

```Text
No error messages to input here.
```

**Comment by Hekili** [comment]
Yes, this is intentional.  If an ability can't be recommended in a display, it is treated as though it's fully on cooldown so recommendations don't constantly ramp in preparation for a button it can't suggest that you push.

How does this functionality impact you?  What's the problem with it?

**Comment by gfuto** [comment]
For example on my fury warrior I want to get Odyn's Fury recommended only when Recklessness is either active (which I can do) or Recklessness has less than 25s cooldown which I cannot currently. Recklessness has Cooldowns toggle and is shown separately, Odyn's fury's toggle is None. 
In the apl I'm trying to use the following line:

actions+=/odyns_fury,if=debuff.odyns_fury.down&(cooldown.recklessness.remains>25|buff.recklessness.up)& ...

**Comment by Hekili** [comment]
If an ability's usage is going to be impacted by the cooldown of an ability shown in a separate display, my recommendation is that both abilities should be on that toggle and shown in the same display.

You can bypass the feigned cooldown with the checkbox on your spec's Toggles tab, or use `cooldown.recklessness.true_remains` and that's as far as I'll go on this topic.  This isn't a bug, and this is about a custom priority, for which I don't offer active support.
