### ISSUE TITLE
Havoc DH priority is suggesting demon bite when specced into demon blades.

### ISSUE THREAD

**Issue by kuttim** [Hekili/hekili#2036]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my demon hunter using havoc specialization and specced into demon blades, Hekili suggests to use Demon's bite even though the talent demon blades replaces demon's bite therefore it is not usable (unless i'm missing something) is this intended?

### How to Reproduce

1. Enter game as a havoc DH.
2. Take demon blades talent.
3. Follow the rotation
4. See how Hekili is suggesting demon's bite after using Metamorphosis.

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPTRSCSiASLJRkAAAAAAAAQLJBhSkkUEikGIBJBB

### Snapshot

https://pastebin.com/1SFUFA9N

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vQc9Gxj8s8qaPEXm9c9gXJ

### Additional Information

The raidbots sim link is for single target, but the snapshot provided was in AoE scenario, however Hekili suggests Demon bite in single target as well, if that's an issue and single target sim/snapshot is needed, please let me know.

### Contact Information

Mikk#4847

**Comment by Hekili** [comment]
Interesting.  Your talents were not detected for some reason.  You don't appear to be using a released build of the addon.  If you download a properly packaged release, do you have this issue?

**Comment by kuttim** [comment]
Thank you, downloading a properly packaged release under releases tab on this repository did seem to fix it.
