### ISSUE TITLE
Enhancement: Earth Shield should not be suggested

### ISSUE THREAD

**Issue by codengine** [Hekili/hekili#2039]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I have selected Earth Shield as a talent and Hekili suggests it in the normal rotation, similar to Lightning Shield.
In contrary to Lightning Shield, which is important for DPS, Earth Shield is purely optional IMHO. Moreover, it is annoying when it wears of so frequently in solo play and interrupts your rotation. The problem is that Earth Shield has charges, whereas Lightning Shield doesnt.

I would mark Earth Shield as a purely optional cooldown, outside of the normal rotation.

### How to Reproduce

1. Download latest version of Hekili
2. Select Earth Shock as a talent
3. Begin the rotation

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IRSaASiESISiDkEAAAAAAAAAAAAAIJEhEUAgEJFEQEkE

### Snapshot

https://pastebin.com/uKjUGJcb

**Comment by Hekili** [comment]
You can disable Earth Shield in /hekili > Abilities.
