### ISSUE TITLE
[FDK] Have an idea how to avoid the Repeat Performance spell

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#204]
I previously asked you a question about the [Repeat Performance](https://www.wowhead.com/spell=304409/repeat-performance) spell. You answered that you do not know how to get around. I found a solution to how you can ignore Repeat Performance with a 100% probability. When we fall under the spell’s target, it’s enough for us to add [Mind Freeze](https://www.wowhead.com/spell=47528/mind-freeze), [Death Grip](https://www.wowhead.com/spell=49576/death-grip), [Asphyxiate](https://www.wowhead.com/spell=108194/asphyxiate) or [Blinding Sleet](https://www.wowhead.com/spell=207167/blinding-sleet) to the rotation. Can you make such a condition for this spell? So that these 4 spells are indicated in rotation. You can even just make it in rotation [Mind Freeze](https://www.wowhead.com/spell=47528/mind-freeze), [Death Grip](https://www.wowhead.com/spell=49576/death-grip), and I checked in the raid that is enough to just reap rotation and completely ignore the mechanics. And thus do not lose DPS. Please review this question.

**Comment by Hekili** [comment]
No, I can't/won't do that for every spec.  Many of those abilities have their own conditions built-in (i.e., there's something to interrupt).  Others are really not wise during the fight (taunting with Death Grip).

I'll keep exploring the best ways to warn/avoid this problem, but I won't suggest filler.
