### ISSUE TITLE
Outlaw Rogue Fan The Hammer optimization

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#2040]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After recheck with other people in Ravenholdt Rogue Discord. I'm sure that you only want to finish at 6 CP if you have BROADSIDE or 6 stack of FAN THE HAMMER. The old rule: "Finisher rules are to finish max CP normally but -1 from max if Broadside or Opportunity is active." is no longer a play here. 
It's only like 1.5-2% dps optimization but it would be great to Hekili to perfect this.
[https://imgur.com/a/g6RlAbR](url)

### How to Reproduce

1. Enter a game as Outlaw
2. Start rotation till you get to 6 CP with 3 stack of Fan The Hammer without Broadside
3. The priority should be sending a sinister strike to 7 CP then finisher instead of finish at 6CP

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAQEkkAkkEJtkkABSkIBgIAAAAAAAJhkmUSCIJpEAAAA

### Snapshot

https://pastebin.com/A1SsEew0

**Comment by Hekili** [comment]
This will be addressed in a routine priority update; no ticket is necessary.
