### ISSUE TITLE
Survival Hunter - cannot use Kill Shot - required ranged weapon

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2042]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello, I have equipped 2H Polearm which can be a standard for Survival, but when Kill Shot spell appears, I cannot use it (error message required ranged weapon).

### How to Reproduce

Enter the game as Survival Hunter and try rotation.

### Talent Loadout

B8PAIlFMjeNhnEouGfV8Ij2uSRgW4AJgEEkIkWyBgQSSEhAAAAAAEKooJkIhESoAAAAAA

### Snapshot

https://pastebin.com/tmJ1pEKn

**Comment by Hekili** [comment]
This should be resolved in 1.8.8.
