### ISSUE TITLE
Druid - Disable Shadowmeld When Solo

### ISSUE THREAD

**Issue by Grayfox2325** [Hekili/hekili#2044]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

I noticed Rogues/Demon Hunters have a toggle to disable Vanish/Shadowmeld when not in a group. Could this toggle get added to Druids for Shadowmeld?

**Comment by VincentCassiau** [comment]
It need to be for all specs or just feral ? @Grayfox2325 

Edit : #2102 

If someone have a feral Night Elf to try it, would be perfect !

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
