### ISSUE TITLE
(Mage, probably others:) Queues get stuck

### ISSUE THREAD

**Issue by mystyree** [Hekili/hekili#2045]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Mage (fire/arcane, I assume frost also) queues (or the icons, at least) get stuck (on 1.8.8), although after not casting immediately after a proceeding spell (i.e. a small gap between casts) it does update. This seems to be due to something in 6f4e10cce7f7a56a33df3f1a7aa151658a9ffea0. ~~I did a few spell casts on shad priest and that seemed fine so perhaps this is limited to mage.~~

I didn't notice any problem a few days ago so dropped back to 1.8.5 which was fine. Took a look at the commits since then to see if any changes and only 6f4e10cce7f7a56a33df3f1a7aa151658a9ffea0 seemed to change much. Reverting that restored the previous behaviour. 

In both those specs the queue quickly gets stuck. In fire its after a couple of casts, in arcane it's on casting arcane missiles. In arcane the queue just gets stuck on 4x arcane missile casts.  I took snapshots of both[1] but arcane is simpler cos it's not affected by Hot Streak procs. (Edit:) forgot to clarify a significant point which is that in the snapshots the queue looks correct but it's not reflected in the icons. E.g. in arcane snapshot of the queue shows ``Arcane; Primary - Nether Tempest(0.06), Arcane Barrage(1.21), Arcane Orb(2.37), Arcane Orb(3.53), Arcane Blast(4.69), Arcane Blast(5.88), Arcane Blast(7.06), Arcane Blast(8.24)`` but the icons were just stuck on 4x arcane missiles (which is queue items 3 - 7).

In fire I also noticed that the recommendations are really slow to update before getting stuck - more than 1s rather than instantly. I didn't notice that in arcane. 

Thanks for all your work on this addon. I just discovered it a few days ago and it's fantastic.

[1]: https://gist.github.com/mystyree/ec91dfefddc332636cdc0aabd937ba61 (ignore the gist title, both specs are there)

### How to Reproduce

1. 1.8.8 as mage: cast some spells as arcane or fire, queue quickly gets stuck. 

### Player Information (Link)

```Text
https://gist.github.com/mystyree/ec91dfefddc332636cdc0aabd937ba61#file-hekili-1-8-8-playerinfo
```

### Error Messages (Link)

```Text
N/A
```

**Comment by mystyree** [comment]
Some further info: Also observed this on affli lock and spriest but the behaviour is not so consistent. On affli lock[1] it occured fighting one of the prepatch event bosses, but not on a training dummy. Afterwards I tried to replicate it on spriest[2], also hitting an event boss; in this case the queue didn't get stuck but sometimes it was very slow to update, i.e. still giving recommendations for spells that had gone onto cooldown. 
[1]: https://gist.github.com/mystyree/ec91dfefddc332636cdc0aabd937ba61#file-hekili-1-8-8-lock-playerinfo
[2]: https://gist.github.com/mystyree/ec91dfefddc332636cdc0aabd937ba61#file-hekili-1-8-8-shadpriest-playerinfo

**Comment by mystyree** [comment]
Replicated tests with 6f4e10cce7f7a56a33df3f1a7aa151658a9ffea0 reverted[1] and couldn't replicate issue on spriest or affli lock, pretty sure the issue is in there. 

[1]: https://github.com/mystyree/hekili/commit/74243d1fa91fd996fcf2078889e36c87a99945ba

**Comment by Hekili** [comment]
Thanks.  Please see if 1.8.9 makes a difference (release is publishing now).

**Comment by mystyree** [comment]
1.8.9 seems to resolve this. at least with a quick test on arcane mage (presumably other specs as well). Will reopen this if not.

**Comment by Hekili** [comment]
Thanks, I appreciate the ticket and detail you provided.  You also saved everybody a bunch of CPU cycles from the addon failing to cache information so it was rescanning tooltips a bunch...  Oops.
