### ISSUE TITLE
Reccomends Execute when not available.

### ISSUE THREAD

**Issue by Dorfess** [Hekili/hekili#2048]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Seems to only happen when I am attacking multiple targets but execute will pop up with a arrow pointing right when none of the targets are executable and it did not proc. Now Im not sure if the arrow means switch targets or continue using the rotation from the icon next to it but that wouldnt make sense. And if its telling me to switch targets to execute when its not proced and no ones executable.

### How to Reproduce

Enter as Fury warrior 
attack pack of mobs around your level
it should pop up after a few pulls

### Talent Loadout

BgEAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAIAJokQQESgARjQICEJhEpJRSSIJEJJBaJJISSAAAAB

### Snapshot

https://pastebin.com/H8yRqSMD

### Additional Information

Like I said not sure if its a bug or not but no matter how I look at it it doesnt make sense to me. 

### Contact Information

Dorfess#7215

**Comment by Hekili** [comment]
You have Recommend Target Swaps turned on, and it's recommending Execute on another target.
