### ISSUE TITLE
Targeting Nameplate Detection resets on Logout

### ISSUE THREAD

**Issue by PinkLionArt** [Hekili/hekili#2049]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

On my Devastation Evoker I use Nameplate Detection set to 25 yards. Whenever I log out and then log back onto my character, the Targeting tab has nameplate detection unticked. The Detection Range stays as what I configured when I tick it back on, but the feature itself gets turned off every time.
I remember having this issue on my warlock as well (where I worked around it by switching to Demo with pet based detection), but I haven't tested whether it occurs on any ranged spec.

### How to Reproduce

1. Enter the game as Devastation Evoker
2. Open the Hekili Options Frame and under Devastation > Targeting turn on "Use Nameplate Detection"
3. Log out of your character
4. Log back onto your character
5. Open the Hekili Options Frame and under Devastation > Targeting see that "Use Nameplate Detection" is not ticked

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhTjIAAAAAAgGSiIJBJJRSJJJtAgIhkEIJJSESSC

### Snapshot

https://pastebin.com/u0UvbMsW

**Comment by Myrhial** [comment]
I have a similar issue, except "use nameplate detection" only resets when I log in to another character (different class) and then log back to the first character. 

The steps I'm using to reproduce this is I start on my elemental shaman and turn "use nameplate detection on" (the range is set to 40y). Then I log out and log in my frost mage. On the frost mage, "use nameplate detection" is off. I do not touch any settings or even open the configuration screen. Then I log out from the frost mage and back on with the elemental shaman. Now "use nameplate detection" appears to be off for this character. Upon enabling it I can see that the range is still on 40y.

**Comment by Hekili** [comment]
This should be addressed in next release (10.0.5-1.0.1) and later.

**Comment by Hekili** [comment]
This may recur in 1.0.2a.  I'll reopen while I am testing.

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
