### ISSUE TITLE
Outlaw - Few bad rotations that might need a fix

### ISSUE THREAD

**Issue by OfficialExiled** [Hekili/hekili#2050]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

So playing Outlaw while leveling and max level I have noticed there are few things that can be tweaked. 

First of all, on the opening before going into combat, in Hekili it is recommended to go Roll the bones - Ambush - Adrenalin - Sinister Strike, etc. But in Dragonflight, the opening now should be Adrenaline - Roll the bones - Ambush - (build up to Between the Eyes then Slice & Dice. I was not in combat but you can see the prio in this snapshot. https://pastebin.com/dPnrMhXy

Secondly, while doing the opening on AOE after Adrenaline - Roll the bones then Ambush it doesnt recommend Blade Flurry but rather keep doing ST rotation such as Ambush - Ambush then Blade Flurry. You can look at the snapshot AOE from here. https://pastebin.com/98zaVL4T.  If you need primary here is the same snapshot just primary. https://pastebin.com/FmxN6fU8

Lastly, Vanish is recommended very slow into the fight. Hitting the training dummy, the Vanish didnt recommend until 30 seconds in, here is the snapshot. https://pastebin.com/dKsJmwQ7. Feel like Vanish can come more often when the cooldown is back to use the Ambush and Take'em by Surprise talent. 

### How to Reproduce

Opening - instead of Roll the bones - Ambush - Adrenaline. It is best to be Adrenaline - Roll the bones - Ambush. 

AOE - Blade Flurry must be right after opening with Ambush or just right away when you are in combat. 

Vanish - use more often to get value out of Ambush and Take'em by Surprise talent. Also in addition to it, I remember when using Vanish, pistol shot was also getting recommended instead of Ambush or Dispatch. If you need snapshot, I can also provide this but dont have it right now. 

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRiIJJJhAAAAAAAEJJaSJJgEKBAAAA

### Snapshot

https://pastebin.com/dPnrMhXy & more in description

**Comment by Haakneus** [comment]
I would like to add two more things.. 1. Shadow dance should only be used when theres no Opportunity nor Audacity buff and when BtE (beetwen the eyes) is on your target. 2. While shadow dance is active you want to use ambush to generate CP and dispatch as spender, inside shadow dance buff we should not be using Opportunity stacks.

**Comment by OfficialExiled** [comment]
> I would like to add two more things.. 1. Shadow dance should only be used when theres no Opportunity nor Audacity buff and when BtE (beetwen the eyes) is on your target. 2. While shadow dance is active you want to use ambush to generate CP and dispatch as spender, inside shadow dance buff we should not be using Opportunity stacks.

Yeah this by the way +

**Comment by IIeTpoc** [comment]
Basicly all of the needed changes are already made in the latest simulationcraft APL. We need to wait till Hekili implements them into the addon.

As for 

> But in Dragonflight, the opening now should be Adrenaline - Roll the bones - Ambush - (build up to Between the Eyes then Slice & Dice.

It is not correct. You should use Adrenaline precombat only if you are specced into Improved Adrenaline.

> 2. While shadow dance is active you want to use ambush to generate CP and dispatch as spender, inside shadow dance buff we should not be using Opportunity stacks.

This is also not correct.  For HO builds, If Shadow Dance or Subterfuge is active, Ambush is the only builder you use even if your energy dips below the point where you can't cast it. **The only other generator you would use during Dance is Pistol Shot at max Opportunity stacks for HO builds.**

**Comment by Hekili** [comment]
The basis of comparison is addon behavior vs. sim behavior (i.e., with a Raidbots link).  Anything that is accounted for in sims will be translated to the addon.  I genuinely don't need reports about sim profiles being updated, as I routinely check them and translate them and integrate them into the addon when they're ready.

**Comment by OfficialExiled** [comment]
> Basicly all of the needed changes are already made in the latest simulationcraft APL. We need to wait till Hekili implements them into the addon.
> 
> As for
> 
> > But in Dragonflight, the opening now should be Adrenaline - Roll the bones - Ambush - (build up to Between the Eyes then Slice & Dice.
> 
> It is not correct. You should use Adrenaline precombat only if you are specced into Improved Adrenaline.
> 
> > 2. While shadow dance is active you want to use ambush to generate CP and dispatch as spender, inside shadow dance buff we should not be using Opportunity stacks.
> 
> This is also not correct. For HO builds, If Shadow Dance or Subterfuge is active, Ambush is the only builder you use even if your energy dips below the point where you can't cast it. **The only other generator you would use during Dance is Pistol Shot at max Opportunity stacks for HO builds.**

Not fully sure about the Shadow Dance + Pistol shot / Ambush. But Adrenaline wise, the reason we use Adrenaline first then Roll the Bones are due to Loaded dice talent, and not only Improved Adrenaline Rush. When we use Dreadblades then I can see why we use Roll the bones before Adrenaline but not in this case. 

Anyways i'll wait and see with the new simulationcraft APL, and thanks to you both.

**Comment by IIeTpoc** [comment]
This is a good point. I guess we really need simc to be updated but to this date considering the best theoretically possible build in BiS gear for pure single target DPS. Adrenaline still is not used in precombat. You can check section Sample Ability log.
https://mimiron.raidbots.com/simbot/report/2vMNHsXoinY8ysricQJcec

**Comment by Hekili** [comment]
I'm going to close this due to recent priority updates. If there are specific issues that carry over, feel free to open a new ticket and with specific details for those issues (what you're actually seeing, what you should be seeing, why you think you should be seeing something different, etc.).
