### ISSUE TITLE
Shattering Star should be lead out skill for Devastation evoker

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#2052]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Shattering star weakens 2 enemys by 20% and only has a 15 sec cooldown.  This should be an "opener" since all other skills will hit harder.

### How to Reproduce

Learn Shattering star.
read tooltip

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDCAAAAAAgWcgkIHQOQOQQSkUSSig0CIhkEQSiEhkkA

### Snapshot

https://pastebin.com/s5asue6q

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3twLGmpLFBzDzrhvUZo8T5

**Comment by Hekili** [comment]
Tickets for routine priority changes are not needed; when the sim profiles are updated, the addon will also get updated.
