### ISSUE TITLE
[Rogue rotation] Hekili not suggesting to use Ambush even though I have audacity buff

### ISSUE THREAD

**Issue by Haroldyolo** [Hekili/hekili#2053]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hekili is not suggesting to use Ambush even though I have audacity buff, audacity buff allows the use of ambush even without being in stealth. This feels like big dps decrease but it might be totally simC fault

### How to Reproduce

Just use the latest Hekili on Outlaw rogue with the Audacity talent learned

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAUSCRSASSSk0SSCEHQSkIJIJJJAAAAAAASIpRJJgkEAAAA

### Snapshot

https://pastebin.com/P1d4gmm3

**Comment by Hekili** [comment]
Please provide a snapshot that's in combat where you'd have expected it to recommend Ambush.  I see that you have Audacity up, but Roll the Bones is much higher in priority.  A snapshot taken when a lower priority ability (i.e., Sinister Strike) is recommended despite having Audacity would be more useful in assessing.

**Comment by Haroldyolo** [comment]
Ambush started working again
