### ISSUE TITLE
Fire breath and Disintergrate not working for single target, eternity surge takes screen shot when used and completely makes hekilli disappear

### ISSUE THREAD

**Issue by gargoylegreg** [Hekili/hekili#2056]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Fire breath and Disintergrate not working for single target, eternity surge takes screen shot when used and completely makes hekilli disappear

### How to Reproduce

i mean just go smack a dummy on an envoker, that should do it

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDkAAAAAAgiWKSiIJkQSkUSS0gUQiESCBJJJRikkA

### Snapshot

https://nothanks.com

### Additional Information

i mean every i downloaded every version since 11/26 and they all do the same thing, ive changed nothing, other then my gpu in the past 24 hours

### Contact Information

Parse#7215

**Comment by Xanion83** [comment]
I have a very similar issue lately. Like above, Fire Breath isn't working for single target but neither is Eternity Surge. No issues with Disintegrate.

**Comment by Hekili** [comment]
Snapshots are required.

**Comment by Xanion83** [comment]
Training dummy targeted, and no Flame Breath and Eternity Surge in first three abilities anymore.

![image](https://user-images.githubusercontent.com/119549829/204946855-1d328633-074b-4f79-8e67-ecb0938ff563.png)

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
I've posted changes in 10.0.2-1.9.2 which will be available soon and may address this.  If not, a new ticket that includes a snapshot (as described above) is needed to investigate further.  Thanks!

**Comment by Wicked0neX** [comment]
Having the same type of issue. Fire breath / Eternity Surge are not recommended in the rotation. Even elite mobs.

[Snapshot](https://pastebin.com/ApXUbWFM)

Hopefully that's right.

**Comment by Hekili** [comment]
Thanks for the snapshot.  This issue should be addressed in 1.9.2 (the updated priority included a `next_dragonrage` variable that set it up that you're always waiting for Dragonrage.

**Comment by Xanion83** [comment]
Latest update appears to have corrected this. You folks are terrific! Thanks!
