### ISSUE TITLE
Request: Option to ignore/deprioritize keybinds assigned to macros that contain a recommended action.

### ISSUE THREAD

**Issue by covingtown** [Hekili/hekili#2058]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

I want Hekili to give me the option for the recommendations to ignore any keybindings that are assigned to macros that contain the pending recommended action.

Scenario: I am playing an Evoker. My "1" key is Living Flame. Because pressing "Alt" is uncomfortable for me to reach during combat, and target swapping to myself for a heal is not ideal, I created a macro on my "7" key of the action bar that casts Living Flame with player targeting. This allows me to heal myself seamlessly without swapping targets or holding down an additional key. However, since making this, whenever Hekili recommends Living Flame as my next action, it presents the keybinding as "7" and not "1".

### Contact Information

Vikmourne#8645

**Comment by Hekili** [comment]
I would recommend that you simply set the keybind text in /Hekili > Abilities > Living Flame > Override Keybind Text.
