### ISSUE TITLE
Warrior - Use Free Revenge Only, reverting to true

### ISSUE THREAD

**Issue by jschick04** [Hekili/hekili#206]
**Describe the Bug/Issue**
Whenever you load into the game, or transition to a new zone or run /reloadui then the "Use Free Revenge Only" checkbox reverts back to being checked.

Workaround is to go into the Classes\WarriorProtection.lua and set the "spec:RegisterSetting" to false.

**To Reproduce**
Go to the Warrior Protection Settings
Uncheck "Use Free Revenge Only"
Logout, change zones or run /reloadui
Go back to the Warrior Protection Settings and it will be checked again

**Expected behavior**
I expect this to remain unchecked and to recommend Revenge even when it is not free

**Issue Reporting Info**
https://pastebin.com/cVc46tSZ

**Comment by Hekili** [comment]
Thanks, I thought I'd squashed this before but I missed a spot.

Should be fixed in the 07-alpha1 that I just posted.
