### ISSUE TITLE
Fury Warrior Avatar occasionally desyncs in dungeons.

### ISSUE THREAD

**Issue by IronMongrel** [Hekili/hekili#2061]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Avatar will sit off cooldown for a long period of time.

### How to Reproduce

I'm not sure.

### Talent Loadout

BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAIEkgSCBRQICENChIQkESkmkIJhkQkkEolkgIJBAAAEA

### Snapshot

a

### Additional Information

Change

actions+=/avatar,if=!talent.titans_torment&(buff.recklessness.up|boss&fight_remains<20)

to

actions+=/avatar,if=!talent.titans_torment&(cooldown.recklessness.remains>40|boss&fight_remains<20)

You can change the "40" to whatever number you like. I just picked 40 at whim.

This will be better for syncing, anyway, since it will not recommend Avatar off of procced Recklessness, in the occasion that they become initially desynced, which will not happen in a sim environment.

**Comment by Hekili** [comment]
Have you made the same change in SimulationCraft and tested for comparison?

**Comment by Hekili** [comment]
Also, snapshots are required.
