### ISSUE TITLE
Addon Situation in game on WoW

### ISSUE THREAD

**Issue by susieQ30** [Hekili/hekili#2063]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

You guys are not making this easy to report not sure where to write this but to let you know since Blizzard log the new expansion the Hekili addon window is covering the icons so we can keep it open to change the icon size it is like that for all my characters I am hoping something can be done to move the huge window that is what I call it not sure what it is called sorry just know cannot fix our icons anymore. 
![image](https://user-images.githubusercontent.com/119659208/205251319-6cb61d54-3070-4d8a-9f2f-cf53ddc1b95f.png)
Thank for your attention to this matter. My email is khondow18@gmail.com my name is Karen Hondow I hope I wrote in the right place for this matter I could not find anywhere else to send you this message. By the way I love this addon thank you.

**Comment by Hekili** [comment]
Nothing has changed in Dragonflight in this regard. You can click and drag the options window out of the way to move things. You can set their X/Y positions in each Display's settings as well.

**Comment by Hekili** [comment]
If for some reason clicking and dragging the window's title is not working for you, you can click and drag the lower right corner to make it smaller.

**Comment by Hekili** [comment]
I'm going to close this ticket; if either of the above options don't work for you, you can still add a comment and let me know.  The box at the top should allow you to click and drag the window, though.  Thanks!

**Comment by susieQ30** [comment]
Thank you yes it worked all good

**Comment by Hekili** [comment]
Glad to hear it!  Take care!
