### ISSUE TITLE
Elemental Shaman Storm elemental's Tempest is no longer recommended when Call lightning is used

### ISSUE THREAD

**Issue by GulioElTorch** [Hekili/hekili#2064]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Since DragonFlight launched the addon no longer recommends using Tempest (previously named Eye of the Storm) after the elemental casts call lightning. This was the case in previous expansions and I would expect it to be a dps gain as it is recommended to wait for that cast before pressing Tempest in the class/spec discord.
This goes for both Single target as well as AoE. 
Do note I have tested this with following macro's (bound on keyboard button C) for pressing Tempest with the same result:
#showtooltip
/use [pet:primal storm elemental]Tempest;[pet:primal fire elemental]Meteor;[nopet,@cursor]Liquid Magma Totem

#showtooltip
/use [known:liquid magma totem,@cursor]liquid magma totem;[noknown:liquid magma totem,known:storm elemental]tempest;[noknown:liquid magma totem,known:fire elemental]meteor

### How to Reproduce

1. Enter game as Elemental Shaman
2. Take the Storm Elemental and Primal elementalist talents
3. activate Storm Elemental
4. wait until Storm Elemental casts Call Lightning

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAAoVSSLJUi0S0QUSBJSAAAAAAQJApkEUkUISJJJNAEJBB

### Snapshot

https://pastebin.com/18x2VzSL

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qQuKogqAqbWFV8NznKb7Qx

### Additional Information

Posted single target sim as primary link
AoE: https://www.raidbots.com/simbot/report/pEnSn3YehMFJeHv1HKRHF9

### Contact Information

GulioElTorch#2521

**Comment by Jacii1121** [comment]
From Snapshot
 this entry's criteria FAILS: buff.call_lightning.stack[0.00] >= 10

As far as I know "Call Lightning" doesn't stack anymore likely causing this issue.

**Comment by Hekili** [comment]
Thanks, this will be updated to simply check for the buff in the next release.
