### ISSUE TITLE
UH DK Prio uses Empower Rune Weapon early

### ISSUE THREAD

**Issue by jankozilla** [Hekili/hekili#2066]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The addon recommends ERW very early in the rotation where the free rune would be a waste and only the 15% haste would be a net buff. Also in multiple target situations it prioritizes rune skills instead of dumping runic power with DC or Epidemic.

### How to Reproduce

1.Enter WoW
2.Log on UH DK.
3.Use talents. BwPAdLUHklrTr3hBIcYWdbnCGDAIRSCJtIBhIRIkkkEBAAAAAAAAAAJJJCSaAARKSJkkkDIJHA
4.Hit dummy.

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAIRSCJtIBhIRIkkkEBAAAAAAAAAAJJJCSaAARKSJkkkDIJHA

### Snapshot

https://pastebin.com/WBtKaJWb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jxv31XHmxukBKBukRtDNev

### Contact Information

Janko#2971

**Comment by jankozilla** [comment]
https://pastebin.com/uK09Gbxx   another snapshot of when I was hitting the cleave dummies.

**Comment by Hekili** [comment]
Your sim used ERW at about 15 seconds into the fight.  When is ERW being recommended?

Neither of your snapshots include ERW.

**Comment by jankozilla** [comment]
On my side it shows it like 2nd or 3rd spell. Maybe it was on cd.
![test](https://user-images.githubusercontent.com/116746920/205370894-b8effb32-5fd4-411c-bb1e-0995fff9f4d2.jpg)

**Comment by Hekili** [comment]
Can you provide a snapshot from that time, then?  That's the data I need.

**Comment by jankozilla** [comment]
https://pastebin.com/5ExEx09j   Here! 

Sorry.

**Comment by Hekili** [comment]
I'll be posting Unholy priority updates that look like they should address this issue.  When I researched your case, it seemed that ERW can be recommended after Dark Transformation.  That doesn't match your screenshot precisely, but in either case -- snapshots won't match the new priority that'll be available soon.  Feel free to open a ticket with updated information if this persists.
