### ISSUE TITLE
BM Hunter (Aspect of the Wild)

### ISSUE THREAD

**Issue by Paul2or3** [Hekili/hekili#207]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Paul2or3** [comment]
Since upgrading my Essesnce to Rank 3, where are there 2 stacks of it, Aspect of the Wild no longer flashes when ready.


build: v8.2.0-06.05
level: 120 (120)
class: HUNTER
spec: beast_mastery

talents: a_murder_of_crows
    aspect_of_the_beast
    chimaera_shot
    killer_instinct
    posthaste
    stomp
    trailblazer

azerite: azerite_empowered=3
    blightborne_infusion=1
    bulwark_of_the_masses=1
    dance_of_death=1
    elemental_whirl=1
    feeding_frenzy=1
    haze_of_rage=1
    longstrider=1
    overwhelming_power=1
    primal_instincts=1
    undulating_tides=1
    unstable_flames=1
    vampiric_speed=1

essences: [the_crucible_of_flame]=3, worldvein_resonance=2

sets/legendaries/artifacts: cyclotronic_blast=1
    pocketsized_computation_device=1

gear:     amalgamated_abomination_spaulders=1
    artisan_officers_shirt=1
    ashenwood_bracers=1
    ashenwood_helm=1
    azshari_stormsurger_boots=1
    azshari_stormsurger_legs=1
    chestguard_of_the_submerged=1
    crossbow_of_forgotten_majesty=1
    cyclotronic_blast=1
    heart_of_azeroth=1
    inowaris_waterdancer_handguards=1
    laseretched_band=1
    pocketsized_computation_device=1
    razzashi_tooth_medallion=1
    thornwoven_band=1
    vims_scalecrusher_chain=1
    zanjir_scaleguard_greatcloak=1

itemIDs: 158017, 158021, 158075, 159385, 159643, 162548, 165667, 167555, 167672, 168358, 169007, 169488, 169810, 169892, 170369, 170377, 89195

**Comment by Hekili** [comment]
Please complete the ticket instructions.  Post a snapshot when you are actually seeing this occur.

**Comment by Paul2or3** [comment]
Well, it DOES NOT occur.  That is my problem.  Aspect of the Wild never flashes like it used to.

**Comment by Hekili** [comment]
Make sure your cooldowns are enabled and get a snapshot (not a screenshot) when you think AotW should be recommended but isn't.

**Comment by Paul2or3** [comment]
Sorry.  Snapshot area is blank.  Actually, when I put a check mark in Cooldowns, everything stops flashing.  I only seem to have this problem on Hunter.  All other characters are fine.

**Comment by Paul2or3** [comment]
When I roll back to v8.2.0-04, everything works great.

**Comment by Hekili** [comment]
You have to *take* a snapshot.  Please read the original ticket instructions (part 2 in particular).

**Comment by Hekili** [comment]
Hi, if you are planning to take a snapshot so I can investigate this, I will leave the ticket open.  Otherwise, I will close this.  Let me know.

**Comment by Paul2or3** [comment]
Sorry.  I don’t know how to do a snapshot.  I rolled back to your v8.2.1-04, and it works perfectly.  Like I said, the newer versions work well on most of my toons, but not hunter.  I’ll just wait for someone more computer savvy to complain, and let them do the snapshot.

**Comment by Hekili** [comment]
The instructions are literally in the first post.
