### ISSUE TITLE
Havoc DH - Essence Break

### ISSUE THREAD

**Issue by PARADOX070** [Hekili/hekili#2072]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

If you're specced into essence break as havoc it is 99% of the time not suggested, it rarely does show up. But it breaks the rotation quite often generating snapshots and screenshots. It doesnt matter whether it is single target or aoe.

### How to Reproduce

Just perform the rotation.

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPThkkEJSJItkERiQSAAAAAAA0SSQkCJRJkkkWSgEIB

### Snapshot

https://pastebin.com/YFskTa1R

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/h7a9unAnFB9hzqvCEp6Dkx

### Additional Information

Patchwerk 8 bosses - https://www.raidbots.com/simbot/report/6gSmUeuCgDskbxVK88X54T
Hectic 1 boss - https://www.raidbots.com/simbot/report/tLHM6YqxdbefWECLUBciXp

**Comment by Hekili** [comment]
Essence Break is on cooldown in your snapshot.

**Comment by PARADOX070** [comment]
That is because i used it myself, because it is never suggested.

**Comment by Hekili** [comment]
It's certainly not going to recommend it while it's on cooldown.  The point of the snapshot is to see why it's recommending something or not recommending it.

My best guess is that since you're using Momentum, you probably want to enable "Recommend Movement" in /hekili > Havoc > Core so that Vengeful Retreat and Fel Rush can be recommended to proc Momentum, which is required for Essence Break.

**Comment by Hekili** [comment]
I'm making a change that the addon will not wait for Momentum if Recommend Movement is disabled, though it's very suboptimal and it's basically trusting you to manage Momentum on your own.

**Comment by PARADOX070** [comment]
Ok did some more testing and yes, without having recommend movement enabled essence break is not recommended with the above build.

However the glaive tempest build without momentum, also does not suggest essence break if movement is disabled. Recommend movement for Unbound Chaos should be enough.
Glaive Tempest Build: BEkACnvaHJn8GSPD6tpaeczPThkkEJSJItkERiQSAAAAAAA0SSQkCJhQSSaRKIBSC

**Comment by Hekili** [comment]
I'd need you to provide a new snapshot in your new build, where you'd expect Essence Break to be recommended *now* (and it's not on cooldown) but it isn't being recommended.

**Comment by PARADOX070** [comment]
https://pastebin.com/kaa4Nu7J

https://i.imgur.com/5K08nGs.png
https://i.imgur.com/hBiN18s.png
https://i.imgur.com/qC6bA5w.png

**Comment by Hekili** [comment]
Oh, yeah, that will already be accounted for in the fix I will be posting this afternoon.
