### ISSUE TITLE
[REC] Not recommending Elysian Decree for Vengeance DH

### ISSUE THREAD

**Issue by Deathhunt** [Hekili/hekili#2073]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In hekili v10.0.2-1.9.3, Vengeance DH's Elysian Decree(specced) is never recommended. However, it is recommended when using Havoc DH.

### How to Reproduce

1. Use Vengeance DH.
2. Spec Elysian Decree.
3. Perform the rotation to test.

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAQLJUSyBkEARCANQS0SSSSkI5ASLJlwBSSoEJBAAAAA

### Snapshot

https://pastebin.com/07eb93zH

**Comment by Hekili** [comment]
I'll relax the Frailty requirements here, but the reason it was not shown is because you're expected to stack up Frailty before using it.  But if you end up never using it, it will definitely feel counterproductive.

**Comment by Deathhunt** [comment]
Thanks a lot~Will try again later.
