### ISSUE TITLE
UH DK priority changes when mounted vs. not mounted

### ISSUE THREAD

**Issue by jankozilla** [Hekili/hekili#2077]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Downloaded fresh version. Noticed the recommendations were different when riding my dragon mount or when just walking normaly in the world. And priorities looked more realistic when riding dragon then without, maybe the buff changes something.

### How to Reproduce

1.Enter WoW
2.Log on UH DK.
3. check Hekili while standing on ground.
4. check Hekili, while flying on DF dragon mount.
5.Prio is changed but seems more reliable.

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAiEJJk0iECiEhQSiEBAAAAAAAAAAJJhEJpAAQKS5AkkkIJHA

### Snapshot

https://pastebin.com/iHXa2ddv

### Additional Information

 https://pastebin.com/m8zJ9b5s  this is another snapshot of when standing on ground not flying. The upper one is while flying.

### Contact Information

Janko#2971

**Comment by Hekili** [comment]
The difference is based on not having a pet while mounted (but also having Raise Dead disabled while mounted).

If you want to provide a sim for comparison, I'll take a look at the "standing on the ground" vs. what your sim will do.

**Comment by jankozilla** [comment]
https://www.raidbots.com/simbot/report/rvdcX3Fyr6fUG7h9xCZCSJ

Here is the sim! By looking at it, Im just surprised ERW is used so early, thought it would waste runic power with no Death coils.

Thank though!

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
