### ISSUE TITLE
Outlaw finisher rule

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#2081]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hekili try to send a finisher at -1 from max when it's not at max Opportunity stacks.

### How to Reproduce

1. Enter game as Outlaw.
2. Start a rotation till you get to a condition: without Broadside and 3 stacks of Opportunity and 6 Combo Point, Hekili will send a finisher instead of building CP to max. (or with Broadside and 3 stacks of Oppportinity and at 5 Combo Point, Hekili will send a finisher instead of building CP to -1 from max).

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQkkoJlkASQAAAA

### Snapshot

https://pastebin.com/3XwruDae

**Comment by Hekili** [comment]
Please provide a sim of your character for comparison.

**Comment by Sedveth** [comment]
> Please provide a sim of your character for comparison.

I will provide later when I'm home, thank you.
Here is the faqs in Ravenholdt Discord.

Outlaw has a fast paced rotation that is constantly reacting to buffs and procs. The spec doesn't burst but makes up for it in consistent output. Should be thought as a chaining priority list:

1) Cooldowns, according to the priorities below.
2) Finishers, if you meet the finisher rule, which is:
      - Finish at max combo points normally.
      - Finish at -1 from max if Broadside is active.
      - Finish at -1 from max if you are at max Opportunity stacks.
      - Finish at -1 from max if you are playing Seal Fate and Ruthless Precision is active.

**Comment by Hekili** [comment]
Here is the relevant portion of the sim profile they've built:

```
# Finish at max possible CP without overflowing bonus combo points, unless for BtE which always should be 5+ CP
actions+=/variable,name=finish_condition,value=combo_points>=cp_max_spend-buff.broadside.up-(buff.opportunity.up&(talent.quick_draw|talent.fan_the_hammer))|effective_combo_points>=cp_max_spend
# Always attempt to use BtE at 5+ CP, regardless of CP gen waste
actions+=/variable,name=finish_condition,op=reset,if=cooldown.between_the_eyes.ready&effective_combo_points<5
```

**Comment by Sedveth** [comment]
> Here is the relevant portion of the sim profile they've built:
> 
> ```
> # Finish at max possible CP without overflowing bonus combo points, unless for BtE which always should be 5+ CP
> actions+=/variable,name=finish_condition,value=combo_points>=cp_max_spend-buff.broadside.up-(buff.opportunity.up&(talent.quick_draw|talent.fan_the_hammer))|effective_combo_points>=cp_max_spend
> # Always attempt to use BtE at 5+ CP, regardless of CP gen waste
> actions+=/variable,name=finish_condition,op=reset,if=cooldown.between_the_eyes.ready&effective_combo_points<5
> ```

Thank you again, I just asked the guy who wrote faqs, he said it's pretty the same dps so it doesn't matter. You can close it :)

**Comment by Hekili** [comment]
Ok, thanks.  If there are changes made to the sims, I'll update the addon accordingly.
