### ISSUE TITLE
Prot warrior not showing mitigation

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#2084]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Protection warrior hekili doesn't seem to recommend any mitigation spells.

### How to Reproduce

Go into dungeon and watch the defensives and nothing shows up except spell reflect

### Talent Loadout

BkEAR5QSZgdnGefDo4ho9ZGXKLAAAAAgkkEJJkIpkQaFEBCkIRJJBISQAkkAAhAAAAAAAACAAKlGA

### Snapshot

https://pastebin.com/3NcyWbvG

**Comment by Hekili** [comment]
Your defensives toggle is turned off.

**Comment by Tzuyume** [comment]
yeah.. sorry for bad report just me being dumb
