### ISSUE TITLE
WW Monk Touch of Death should be hard Priority, when available

### ISSUE THREAD

**Issue by aliemaxi2** [Hekili/hekili#2087]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Sometimes when a mob is at the 15 % Mark and touch of death can be used it uses other spells instead when more targets are there. 

Since the new talents for Monk that you can use Touch of death twice and on that it hits 5 targets it should get first priority when it can be used. Deals most of youre Damage in +5 target or more  if used correctly.

Should be triggered instantly when available.

### How to Reproduce

1. Enter the Game with Windwalker Monk.
2. Take all the Touch of Death Talents from the Tree
3. Touch of Death should have 1.5 Minute cooldown now
4. Fight against a group of enemyies of 3 or more targets.
5. Target falls below 15 % or a target can get executed since the healt (100%) is lower then touch of death Damage.
6. Doesnt use Touch of Death or not fast enought or  instantly since it will try to spread for SCK.

### Talent Loadout

B0QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQSkkElISEAAAAQikkQCQSSkGpkkISIRSikkWCOAAAA

### Snapshot

https://pastebin.com/yrgFW82G

### Contact Information

https://pastebin.com/yrgFW82G

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
