### ISSUE TITLE
SpellFlash stops flashing

### ISSUE THREAD

**Issue by Zeuslight56** [Hekili/hekili#2088]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

During my fight the SpellFlash no longer showed me the recommendations.

### How to Reproduce

Activate Spellflash, enter battle, follow the rotation after a while the SpellFlash no longer advises me.

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPThkkEJSJItkERi0EBAAAAAAQLJBRKkElQSSaJBSgEA

### Snapshot

https://pastebin.com/QwThCQmW

**Comment by Hekili** [comment]
Thanks for the report.  Does it stop showing for all abilities, or specific abilities?  (As an aside, a *frappe du chaos* sounds delicious.)

This doesn't sound like an issue with recommendations -- the addon keeps generating recommendations, but the flashes stop.  Do you have BugSack/BugGrabber installed?  Are there any error messages picked up via those addons?

**Comment by Zeuslight56** [comment]
Yes it stops with certain spells and then reappears.

**Comment by Hekili** [comment]
Which spells, specifically?

**Comment by Zeuslight56** [comment]
I believe it's when I'm in meta the spells are no longer recommended.

**Comment by Hekili** [comment]
This should be addressed in the latest releases.
