### ISSUE TITLE
Arcane needs tracking of TOTM/Spark/RoP phases between sets of recommendations

### ISSUE THREAD

**Issue by Lovefulx** [Hekili/hekili#2089]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Getting a recommandation for Evocation at the start of every fight when its ready, even though i am full mana.
Since today at the morning (yesterday everything was fine) i also won't get Touch of Magi or Arcane Surge (spell id 365350 - talent tree) suggested anymore.

I don't think this is correct, cause i am dealing less damage then yesterday.

### How to Reproduce

1. Enter game as a Arcane Mage
2. Load Talent Tree posted in Issue
3. Look at the Rotation to see Evocation at the Start even with full mana
4. Play the rotation to see Touch of Magi and/or Arcane Surge not being recommended in Open World and Dungeons regardless of fighting against 1 or many mobs

### Talent Loadout

B4DAHVkVsxxZrVqBmAzlSR2f7LJColIHgk0ARLJiIikIhEaJItkAAAAAAAAAAAAIJJJhIJJC

### Snapshot

https://pastebin.com/fzjwRV2d

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8tBYgpU7CBqadtUiDxTw6F

### Additional Information

Hectic Add Cleave: https://www.raidbots.com/simbot/report/qUHtCUKRiiLk7gMaEyupbf

**Comment by Mykoymia** [comment]
Just FYI, evocation being used at full mana is correct. The siphon storm talent gives you intellect for every second you channel Evocation, so it's a DPS gain to use it before your burst window. The raidbots sims you linked also has it casting Evocation pre-pull.

**Comment by Lovefulx** [comment]
> Just FYI, evocation being used at full mana is correct. The siphon storm talent gives you intellect for every second you channel Evocation, so it's a DPS gain to use it before your burst window. The raidbots sims you linked also has it casting Evocation pre-pull.

Thanks for that Info, yesterday it was probably missing then, cause i just skilled it today. Still i am confused why the 2 other Spells wont show up after i skilled this evocation thingy. Also normal that they are not prioritized anymore cause of the Talent?

**Comment by Hekili** [comment]
The Arcane Mage priority relies on timing certain phases and needs additional work to support them.  I'm investigating and looking to resolve it soon.

**Comment by Nuke6471** [comment]
@Hekili Any updates on this thread?

**Comment by Hekili** [comment]
There are two tickets open right now.  Have you used Arcane recently?
