### ISSUE TITLE
Outlaw AOE reroll Logic

### ISSUE THREAD

**Issue by Gyudon47** [Hekili/hekili#209]
There is a new updated APL for rerolls for outlaw during blade flurry. I dont think you have looked into this yet as the last update was 6 days ago for outlaw and the addon still suggest to keep every single buff. Basically we keep single Ruthless precision, Broadside, Grand Melee or 2+rolls of anything not counting skull and crossbones.

# With Blade Flurry up, ignore rules above and take everything that is 2+ (not counting SaC) or single BS, GM, RP
actions+=/variable,name=rtb_reroll,op=set,if=buff.blade_flurry.up,value=rtb_buffs-buff.skull_and_crossbones.up<2&(buff.loaded_dice.up|!buff.grand_melee.up&!buff.ruthless_precision.up&!buff.broadside.up)
actions+=/variable,name=ambush_condition,value=combo_points.deficit>=2+2*(talent.ghostly_strike.enabled&cooldown.ghostly_strike.remains<1)+buff.broadside.up&energy>60&!buff.skull_and_crossbones.up&!buff.keep_your_wits_about_you.up
actions+=/variable,name=bte_condition,value=buff.ruthless_precision.up|(azerite.deadshot.enabled|azerite.ace_up_your_sleeve.enabled)&buff.roll_the_bones.up

**Comment by Hekili** [comment]
Complete a proper ticket following the instructions you deleted.

Post a snapshot when you think it should be telling you to reroll but it isn't.

**Comment by Gyudon47** [comment]
Terribly sorry about that here is the snapshot where i think it would be rerolling 

build: v8.2.0-07
level: 120 (120)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    cheat_death
    dancing_steel
    prey_on_the_weak
    quick_draw
    vigor

azerite: ace_up_your_sleeve=1
    azerite_empowered=1
    brigands_blitz=1
    deadshot=3
    gutripper=2
    impassive_visage=1
    keep_your_wits_about_you=1
    overwhelming_power=1
    resounding_protection=1
    vampiric_speed=1

essences: [essence_of_the_focusing_iris]=3, memory_of_lucid_dreams=3

sets/legendaries/artifacts: none

gear:     ardent_worshippers_boots=1
    ascended_leviathans_eye_loop=1
    ashvanes_razor_coral=1
    band_of_the_ancient_dredger=1
    bilestained_crawg_tusks=1
    brineweaver_guardians_gloves=1
    cephalohide_jacket=1
    drape_of_valiant_defense=1
    dribbling_inkpod=1
    heart_of_azeroth=1
    helm_of_the_inexorable_tide=1
    leggings_of_the_stormborn=1
    shoulderpads_of_frothing_rage=1
    skulkers_blackwater_bands=1
    warbeast_hide_cinch=1

itemIDs: 158075, 159314, 159461, 159653, 165518, 165925, 168345, 168348, 168378, 168703, 168879, 169311, 169319, 169931, 169932

New Recommendations for [ Primary ] requested at 17:57:02 ( 1003948.40 ).

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00 ).
 - combo_points, 5 / 5
 - energy, 150 / 150

Processing precombat action list [ Outlaw - precombat ].
Current recommendation was NO ACTION at +60.00s.


[001] potion ( precombat - 1 ) - ability disabled.


[002] marked_for_death ( precombat - 2 ) - ability unknown


[003] stealth ( precombat - 3 )
We are already in-combat and this pre-combat action is not essential.  Skipping.


[004] roll_the_bones ( precombat - 4 )
We are already in-combat and this pre-combat action is not essential.  Skipping.


[005] slice_and_dice ( precombat - 5 ) - ability unknown


[006] adrenaline_rush ( precombat - 6 ) - ability disabled.


[007] azsharas_font_of_power ( precombat - 7 ) - ability disabled.


[008] cyclotronic_blast ( precombat - 8 ) - ability unknown
Completed precombat action list [ Outlaw - precombat ].

Processing default action list [ Outlaw - default ].
Current recommendation was NO ACTION at +60.00s.


[009] kick ( default - 1 ) - ability disabled.


[010] stealth ( default - 2 )
The action (stealth) is unusable at (0.00 + 0.00) because cannot stealth in combat.


[011] variable ( default - 3 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:3).


[012] variable ( default - 4 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:4).


[013] variable ( default - 5 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:5).


[014] variable ( default - 6 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:6).


[015] variable ( default - 7 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:7).


[016] variable ( default - 8 )
 - variable.ambush_condition will check this script entry (Outlaw:default:8).


[017] variable ( default - 9 )
 - variable.bte_condition will check this script entry (Outlaw:default:9).


[018] variable ( default - 10 )
 - variable.blade_flurry_sync will check this script entry (Outlaw:default:10).


[019] call_action_list ( default - 11 )
Criteria FAIL at +0.00 - stealthed.all[false]


[020] call_action_list ( default - 12 )
There is no criteria for this action list..
Action list (cds) was found.
+ cds
Current recommendation was NO ACTION at +60.00s.


[021] call_action_list ( cds - 1 )
Criteria PASS at +0.00 - ! stealthed.all[false]
Action list (essences) was found.
+ cds, essences
Current recommendation was NO ACTION at +60.00s.


[022] concentrated_flame ( essences - 1 ) - ability unknown


[023] blood_of_the_enemy ( essences - 2 ) - ability unknown


[024] guardian_of_azeroth ( essences - 3 ) - ability unknown


[025] focused_azerite_beam ( essences - 4 ) - ability disabled.


[026] purifying_blast ( essences - 5 ) - ability unknown


[027] the_unbound_force ( essences - 6 ) - ability unknown


[028] ripple_in_space ( essences - 7 ) - ability unknown


[029] worldvein_resonance ( essences - 8 ) - ability unknown


[030] memory_of_lucid_dreams ( essences - 9 ) - ability unknown
Returned from list (essences), current recommendation is NO ACTION (+60.00).
- essences


[031] adrenaline_rush ( cds - 2 ) - ability disabled.


[032] marked_for_death ( cds - 3 ) - ability unknown


[033] marked_for_death ( cds - 4 ) - ability unknown


[034] blade_flurry ( cds - 5 )
The action (blade_flurry) is usable at (0.00 + 10.91) with cost of 15.
 - the action is ready before the current recommendation (at +10.91 vs. +60.00).
List ( cds ) called from ( Outlaw:default:12 ) would PASS at 10.91.
 - NONE
 - this entry's criteria FAILS: spell_targets.any[4.00] >= 2 & ! buff.blade_flurry.up[true] & ( ! raid_event.adds.exists[true] | raid_event.adds.remains[111.09] > 8 | raid_event.adds.in > ( 2 - cooldown.blade_flurry.charges_fractional[1.30] ) * 25 )
There are 1 recheck events.
Rechecking stopped at step #1.  The recheck ( 11.04 ) isn't ready within a reasonable time frame ( 10s ).


[035] ghostly_strike ( cds - 6 ) - ability unknown


[036] killing_spree ( cds - 7 ) - ability unknown


[037] blade_rush ( cds - 8 ) - ability unknown


[038] vanish ( cds - 9 ) - ability disabled.


[039] shadowmeld ( cds - 10 ) - ability unknown


[040] potion ( cds - 11 ) - ability disabled.


[041] variable_intensity_gigavolt_oscillating_reactor ( cds - 12 ) - ability disabled.


[042] use_items ( cds - 13 )
Criteria PASS at +0.00 - buff.bloodlust.react[0.00] | time_to_die[3600.00] <= 20 | combo_points.deficit[0.00] <= 2
Current recommendation was NO ACTION at +60.00s.

Substituting focused_azerite_beam for Heart of Azeroth action; it is otherwise not included in the priority.
[043] focused_azerite_beam ( items - 1 ) - ability disabled.
Returned from Use Items; current recommendation is NO ACTION (+60.00).


[044] blood_fury ( cds - 14 ) - ability unknown


[045] berserking ( cds - 15 ) - ability unknown


[046] fireblood ( cds - 16 ) - ability unknown


[047] ancestral_call ( cds - 17 ) - ability unknown


[048] cyclotronic_blast ( cds - 18 ) - ability unknown


[049] azsharas_font_of_power ( cds - 19 ) - ability disabled.


[050] ashvanes_razor_coral ( cds - 20 ) - ability disabled.


[051] use_items ( cds - 21 )
Criteria PASS at +0.00 - buff.bloodlust.react[0.00] | time_to_die[3600.00] <= 20 | combo_points.deficit[0.00] <= 2
Current recommendation was NO ACTION at +60.00s.

Substituting focused_azerite_beam for Heart of Azeroth action; it is otherwise not included in the priority.
[052] focused_azerite_beam ( items - 1 ) - ability disabled.
Returned from Use Items; current recommendation is NO ACTION (+60.00).
Returned from list (cds), current recommendation is NO ACTION (+60.00).
- cds


[053] run_action_list ( default - 13 )
Time-sensitive Criteria deferred at +0.00 - combo_points.current[5.00] >= cp_max_spend - ( buff.broadside.up[false] + buff.opportunity.up[false] ) * ( talent.quick_draw.enabled[true] & ( ! talent.marked_for_death.enabled[false] | cooldown.marked_for_death.remains[60.00] > 1 ) )
Action list (finish) was found.
+ [finish]
Current recommendation was NO ACTION at +60.00s.


[054] between_the_eyes ( finish - 1 )
The action (between_the_eyes) is usable at (0.00 + 11.01) with cost of 25.
 - the action is ready before the current recommendation (at +11.01 vs. +60.00).
List ( finish ) called from ( Outlaw:default:13 ) would PASS at 11.01.
 - combo_points.current[5.00] >= cp_max_spend - ( buff.broadside.up[false] + buff.opportunity.up[false] ) * ( talent.quick_draw.enabled[true] & ( ! talent.marked_for_death.enabled[false] | cooldown.marked_for_death.remains[60.00] > 1 ) )
var[bte_condition] [01/Outlaw:default:9] :: op: set, conditions: NONE -- [true]; value: true
var[bte_condition] [01/Outlaw:default:9] :: op: set, conditions: NONE -- [true]; value: true
 - this entry's criteria PASSES: variable.bte_condition[true]
Action chosen:  between_the_eyes at 11.01!


[055] slice_and_dice ( finish - 2 ) - ability unknown


[056] roll_the_bones ( finish - 3 )
The action (roll_the_bones) is usable at (0.00 + 0.00) with cost of 25.
 - the action is ready before the current recommendation (at +0.00 vs. +11.01).
List ( finish ) called from ( Outlaw:default:13 ) would PASS at 0.00.
 - combo_points.current[5.00] >= cp_max_spend - ( buff.broadside.up[false] + buff.opportunity.up[false] ) * ( talent.quick_draw.enabled[true] & ( ! talent.marked_for_death.enabled[false] | cooldown.marked_for_death.remains[60.00] > 1 ) )
 - this entry's criteria FAILS: buff.roll_the_bones.remains[19.65] <= 3
There were no recheck events to check.


[057] roll_the_bones ( finish - 4 )
The action (roll_the_bones) is usable at (0.00 + 0.00) with cost of 25.
 - the action is ready before the current recommendation (at +0.00 vs. +11.01).
List ( finish ) called from ( Outlaw:default:13 ) would PASS at 0.00.
 - combo_points.current[5.00] >= cp_max_spend - ( buff.broadside.up[false] + buff.opportunity.up[false] ) * ( talent.quick_draw.enabled[true] & ( ! talent.marked_for_death.enabled[false] | cooldown.marked_for_death.remains[60.00] > 1 ) )
var[rtb_reroll] [01/Outlaw:default:3] :: op: set, conditions: NONE -- [true]; value: true
var[rtb_reroll] [02/Outlaw:default:4] :: op: set, conditions: azerite.deadshot.enabled[true] | azerite.ace_up_your_sleeve.enabled[true] -- [true]; value: true
var[rtb_reroll] [03/Outlaw:default:5] :: op: set, conditions: azerite.snake_eyes.rank[0.00] >= 2 -- [false]; value: true
var[rtb_reroll] [04/Outlaw:default:6] :: op: reset, conditions: azerite.snake_eyes.rank[0.00] >= 2 & buff.snake_eyes.stack[0.00] >= 2 - buff.broadside.up[false] -- [false]; value: true
var[rtb_reroll] [05/Outlaw:default:7] :: op: set, conditions: buff.blade_flurry.up[true] -- [true]; value: true
 - this entry's criteria FAILS: ( active_enemies[4.00] = 1 | buff.blade_flurry.down[false] ) & variable.rtb_reroll[true]
There are 1 recheck events.
Rechecking stopped at step #1.  The recheck ( 11.05 ) isn't ready within a reasonable time frame ( 10s ).


[058] between_the_eyes ( finish - 5 )
The action is not ready in time ( 11.01 vs. 11.01 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.


[059] dispatch ( finish - 6 )
The action (dispatch) is usable at (0.00 + 0.00) with cost of 35.
 - the action is ready before the current recommendation (at +0.00 vs. +11.01).
List ( finish ) called from ( Outlaw:default:13 ) would PASS at 0.00.
 - combo_points.current[5.00] >= cp_max_spend - ( buff.broadside.up[false] + buff.opportunity.up[false] ) * ( talent.quick_draw.enabled[true] & ( ! talent.marked_for_death.enabled[false] | cooldown.marked_for_death.remains[60.00] > 1 ) )
 - this entry has no criteria to test.
Action chosen:  dispatch at 0.00!
Returned from list (finish), current recommendation is dispatch (+0.00).
- [finish]
Added finish to blocklist as it was called via RAL.
The recommended action (dispatch) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Outlaw - default ].
Recommendation is dispatch at 0.00 + 0.00.

**Comment by Hekili** [comment]
Thanks, I have a big batch of APL updates that will go out this weekend.

**Comment by Hekili** [comment]
Should be resolved in the latest release.
