### ISSUE TITLE
Demonology - Felguard abilities stop being recommended after some time

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#2090]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Doing the full rotation of demonology doesn't show up smaller cds like guilluitine, demonic strength or even soul strike at any point. I made a snapshot when there was downtime after tyrant and none of above got recommended.

### How to Reproduce

Play demo in a dungeon and follow hekili.

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3ggERSSg0AItkkEaAAAAAgDASIkIJSkIt0SSCCAAAAAAA

### Snapshot

https://pastebin.com/nieHKd7H

**Comment by Hekili** [comment]
It seems that after some time, it fails to detect your Felguard.  I have another report for this issue as well.  I'll be investigating.  Thanks!

**Comment by Hekili** [comment]
For testing purposes, I'm curious if this only happens after playing for some time (i.e., an hour).  If you resummon your Felguard, do your abilities start to work again?  Does it work before/after using Grimoire Felguard?

**Comment by CharlTruter** [comment]
For me, this happens no matter what - if it's resummoned it's the same, will never recommend it.

**Comment by Tzuyume** [comment]
For me its not working from start, even when i resummon, doesn't seem to matter if i use grimoire or not

**Comment by Tzuyume** [comment]
actually had a time when it worked from start after i died now.

**Comment by Tzuyume** [comment]
however now it shows demonic strength and guiluittine next to each others when its not possible to do

**Comment by xinni** [comment]
For the demonic strength and guillotine conflict, I left my comment in [this issue](https://github.com/Hekili/hekili/issues/2047). I thinks this may be the root cause.

**Comment by blippblipp** [comment]
While Guillotine is active Demonic Str and Soul Strike shows up in the recommendations. But once Guillotine finishes they stop showing. Also when specced into Nether Portal and not Guillotine, Demonic Str and Soul Strike never show up. https://pastebin.com/DTdHZzkv

**Comment by Hekili** [comment]
@blippblipp You're describing two or three things.  Which scenario is your snapshot meant to capture?

1. Guillotine is active and Demonic Strength and Soul Strike are recommended?
2. After Guillotine finishes, Demonic Strength and Soul Strike are not recommended?
3. Specced into Nether Portal and neither Demonic Strength nor Soul Strike show up?

I can see it's not the third one, but the point of snapshots are that they're taken at the time you're describing.  Which of the first two is your snapshot supposed to be?  Will you supply snapshots for the other two situations?

**Comment by noxiouslol** [comment]
Neither Soul Strike nor Demonic Strength is recommended with Nether Portal and Demonic Tyrant talented. Even when toggling between Cooldowns ON and OFF and resummoning Felguard.
https://pastebin.com/Rv1cpV9K

**Comment by noxiouslol** [comment]
Demonic Strength is also only rarely recommended when cooldowns are OFF when Tyrant and Guillotine are talented. DS actually gets pushed out of priority before it ever gets to be used. So I am never able to press it. 
Soul Strike is still never recommended.
https://pastebin.com/U2RtLeBU

**Comment by Kintoun** [comment]
Confirmed 2.0.2 had issue 2.0.3 fixed. Soul strike and Demonic Strength were never recommended. Now they are.
