### ISSUE TITLE
Request rogue combat rotation wotlk

### ISSUE THREAD

**Issue by yachitacs** [Hekili/hekili#2091]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Classic (Wrath of the Lich King)

### Feature Request

Good, I would like to know if it would be possible to rotate rogue combat for wotlk, thank you very much

### Contact Information

yachita(Rowt)#9392

**Comment by Hekili** [comment]
Eventually, after Dragonflight is fully stabilized, yes.  But a ticket is not needed.  I won't be providing an ETA.  Thanks!
