### ISSUE TITLE
Demonology not showing Keybind to Axe Toss (Felguard ability) & recommending Demonic Strength when Guillotine is up and vice versa

### ISSUE THREAD

**Issue by Hyrulien** [Hekili/hekili#2095]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [ ] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

explained in "How to Reproduce"

### How to Reproduce

1. go to mob who needs interrupt
2. hekili will suggest axe toss, but without the keybind
3. hekili will sooner or later into the fight suggest either first guillotine or demonic strength to be cast
4. whenever one of those skills has been cast the other one can't be cast for a few seconds until the animation finishes of the attacks e.g guillotine the axe being stuck in the ground and demonic strength the fel blade
5. hekili will still want to suggest that even though you can't press it at that moment.

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3gESSkIBSJig0SSCpBAAAAAtIIhQikIJJi0SiECAAAAAAA

### Snapshot

https://pastebin.com/qYwtUqvL

### Contact Information

Hyrulien#0134

**Comment by Hekili** [comment]
You can manually set the keybind for Axe Toss via /hekili > Abilities.

The other issues noted are in other open tickets and are being addressed.  Thank you!

**Comment by Raven7576** [comment]
Issue has been kinda back in keys while using this build: BoQAAAAAAAAAAAAAAAAAAAAAAggkEJSg0SLCSLJJkWAAAAAQLCSIkIJSSiItkIhAAAAAAA

Ill be mid fight, Guillotine and then next recommendation will be to use Demonic Strength. It will always go Guillo > DS. Additionally, it will move onto a new recommendation a moment or two later but not without making a hiccup in my output. I dont believe its detecting the pets Blade Storm quickly enough. Im completely guessing here though and I dont have much evidence outside of "Something's not quite right" 

I am using the most recent build, and this only really started a patch or two ago.
