### ISSUE TITLE
Not an issue, but I was wondering if it is possible to still recommend dps activities as healer spec to help do damage in mythics?  on my evoker id love to still get dps recommendations while im healing.  Is there a way to do that?  

### ISSUE THREAD

**Issue by bason1c** [Hekili/hekili#2096]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Not an issue, but I was wondering if it is possible to still recommend dps activities as healer spec to help do damage in mythics?  on my evoker id love to still get dps recommendations while im healing.  Also would be good for pvp as well.  Is there a way to do that?  

### Contact Information

basonic.eth@gmail.com

**Comment by Hekili** [comment]
That is a lot of words for the title of an issue ticket.

Presenting DPS recommendations for healers is under consideration and may be implemented once other Dragonflight changes level off.  Nothing is promised and no ETA, but I'm pretty comfortable providing healer DPS recommendations as long as people realize healing itself won't be addressed.
