### ISSUE TITLE
Unholy spending runes while RP capped

### ISSUE THREAD

**Issue by jankozilla** [Hekili/hekili#2097]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

During my rotation I was at full runic power, and Hekili would still recommend Scourge strike instead of Death coil to maybe lower runic power so there is no runic power loss.

### How to Reproduce

1.Log into WoW
2.Play Unholy
3.Fight mobs.

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAiEJJk0iECiEhQSiEBAAAAAAAAAAJJhEJpAAQKS5AkkkIJHA

### Snapshot

https://pastebin.com/KJ7XEJ5c

### Contact Information

Janko#2971

**Comment by Hekili** [comment]
Please provide a sim of your character in a similar scenario (you have two targets in your snapshot).

**Comment by jankozilla** [comment]
https://www.raidbots.com/simbot/report/5PWLDQLWUbsohfRDr32xiF

**Comment by Hekili** [comment]
I've made a few changes that should reduce how frequently you see this, based on some sim testing of my own.
