### ISSUE TITLE
BfA Beta error: Deferred XML Node object named L_UIDropDownMenuTemplate already exists

### ISSUE THREAD

**Issue by Muerr** [Hekili/hekili#21]
I'm using AethysRotation and Hekili addons on the BfA beta to test them out for my characters. I am getting the following errors and a Lua Warning dialog when I log into the game if I have both addons enabled (disabling one or the other causes the error to go away).

```
6/30 10:02:54.684 Loading add-on Hekili
6/30 10:02:54.684 ** Loading table of contents Interface\AddOns\Hekili\Hekili.toc
6/30 10:02:54.684 ++ Loading file Interface\AddOns\Hekili\embeds.xml
6/30 10:02:54.684 ++ Loading file Interface\AddOns\Hekili\Libs\LibUIDropDownMenu\LibUIDropDownMenu.xml
6/30 10:02:54.684 ++ Loading file Interface\AddOns\Hekili\Libs\LibUIDropDownMenu\LibUIDropDownMenuTemplates.xml
6/30 10:02:54.684 Deferred XML Node object named L_UIDropDownMenuButtonTemplate already exists
6/30 10:02:54.684 Deferred XML Node object named L_UIDropDownListTemplate already exists
6/30 10:02:54.684 Deferred XML Node object named L_UIDropDownMenuTemplate already exists
```

I presume Hekili has the error because addons are loaded alphabetically.

I don't get this error when using both addons in the live version of the game, only the beta. I haven't tried these on PTR.

**Comment by Hekili** [comment]
Let me know if this is still an issue.  I believe it may be resolved as I've updated LibUIDropDownMenu.

**Comment by Hekili** [comment]
Looks resolved.

**Comment by Muerr** [comment]
Yup, thank you! 😁
