### ISSUE TITLE
Shadow Priest lucid Dreams not working correctly

### ISSUE THREAD

**Issue by Soulshox** [Hekili/hekili#210]
Lucid dreams is not working correctly in rotation. Addon is saying to use on cooldown instead of over 20 stacks or insanity/bloodlust 26 stacks. cant figure out how to fix.

**Comment by Hekili** [comment]
Submit a complete ticket with the instructions or I cannot investigate this (I don't have Lucid Dreams on a shadow priest for testing purposes).
