### ISSUE TITLE
Unable to make recommendation for Primary #1

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2103]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I was in a dungeon of heroic difficulty. Using its rotation, the addon gave me a notification. The rotation continued to work fine. I don't know what happened, but I decided to attach it here.
![1](https://user-images.githubusercontent.com/63850853/205978606-03571c24-e7b0-4aad-a173-8521933c8125.jpg)

### How to Reproduce

Enter the dungeon. Follow the rotation.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhTDCAAAAAAKaIJikEJkEJlkk0CSLkIhkEIJJSESSC

### Snapshot

https://pastebin.com/cxfGBBzq

**Comment by Hekili** [comment]
Do you have any idea what you were doing when it happened?  Were you empowering a spell?  Was it after empowering a spell?

In the **How to Reproduce** section, ideally you would explain more specifically what was happening when it occurred.  It can be hard to track when the snapshot occurs automatically, though.

**Comment by Dragonfo** [comment]
I was in The Azure Vault, we touched the dragons at the beginning, and I just started rotating as usual everything that the addon recommended. After the fight, I saw what was written to me in the chat and that's it. I honestly can't say at what point it appeared.

**Comment by Hekili** [comment]
Thanks; I am putting some "babyproofing" in the next build that should prevent the error.

**Comment by Dragonfo** [comment]
I have the same problem again. I now noticed where and at what moment. There were too many goals and for some reason the addon recommended me to use for 2 charges when I should have recommended for 4.  https://pastebin.com/XzHnN7eU
![1](https://user-images.githubusercontent.com/63850853/206267676-2bb9a6e4-76ee-4afe-ad58-e08204f19742.jpg)

**Comment by Hekili** [comment]
See if this comes up again in 2.0.4-beta2 or later.  Thanks!
