### ISSUE TITLE
Feral AOE priority

### ISSUE THREAD

**Issue by matyah** [Hekili/hekili#2104]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

This is my first issue ever i'll try to be as precise as i can.
There is a weird interaction in feral's AOE where "Trash" has a higher priority than "Shred" when there is no "Brutal Slash" left.

### How to Reproduce

This problem occurs in AoE alone.

1. Enter the game as a Feral
2. Use every Brutal Slash
3. Use trash 
4. You would see trash have more prio than shred

### Talent Loadout

BcGAYhlYdy9RJ6ROrphOEi69vCAAAAAAIkUSTikkEJl0OAaJRikAAAAAAgiAIJAIikQIJUSolkAAAAAAASA

### Snapshot

https://pastebin.com/UkSmKcDN

**Comment by Hekili** [comment]
Thanks for reporting.  The issue here seems to be that Thrash is being treated as though it's off the GCD.  I'll post a fix later tonight.

**Comment by matyah** [comment]
Thank you for your hard work !
