### ISSUE TITLE
UH DK not suggesting Unholy Assault in Multi target during Cooldowns.

### ISSUE THREAD

**Issue by jankozilla** [Hekili/hekili#2109]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Went into Dragon City, started hitting cleave dummies, toggled cooldowns on, noticed Unholy assault was never suggested , Hekili would rather use 2 times Festering strike instead of UA to apply festering wounds. Also DND was only suggested at cd window and rarely on its own causing its charges to be full.

### How to Reproduce

1.Enter WoW as UH Dk,
2.Hit cleave dummies in dragon city.
3.Notice no UA suggested, and also DnD only at start.

### Talent Loadout

BwPAAAAAAAAAAAAAAAAAAAAAAAACkkQiIRCSSEikkIRAAAAAAAAAAQSSIRSKAAkiUOQkkkIJA

### Snapshot

https://pastebin.com/Cg1WKNSQ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tGvWUfGMUk5oEFiLovTErE

### Additional Information

I love you.

### Contact Information

Janko#2971

**Comment by Hekili** [comment]
Thanks for including the snapshot and the sim.  It looks like this is how the sim profile is written; Unholy Assault is only used when `variable.st_planning` is true:

> active_enemies<=3&(!raid_event.adds.exists|raid_event.adds.in>15)

Current sims will only use with 3 or fewer targets and when there are no add waves / adds won't arrive within 15 seconds.

I'll revise to allow its use based on `variable.adds_remain`:

> active_enemies>=4&(!raid_event.adds.exists|raid_event.adds.exists&raid_event.adds.remains>6)

**Comment by Hekili** [comment]
Testable in 2.0.4-beta2.

**Comment by jankozilla** [comment]
Nice!
