### ISSUE TITLE
What is the first skill in the Assassination Rogue rotation?

### ISSUE THREAD

**Issue by Nekrothaft** [Hekili/hekili#211]
I can't for the life of me find which skill is first in the assassination rotation.

Please tell me which one it is.

[https://i.imgur.com/yZlA1Ck.jpg](url)

Thank you

**Comment by Hekili** [comment]
Crippling Poison.

**Comment by Nekrothaft** [comment]
I see. Thanks. I disabled it from the list of abilities but it still shows up. Any ideas?

**Comment by Hekili** [comment]
The ability you want to disable is actually "Poisons" (rather than "Deadly Poison" or "Crippling Poison").  "Poisons" recommends your Deadly Poison if you don't have a Lethal Poison, then recommends Crippling Poison.

**Comment by Nekrothaft** [comment]
Thank you. That worked! Love your addon btw! Excellent work!
