### ISSUE TITLE
Globe of Jagged Ice not showing in rotation

### ISSUE THREAD

**Issue by Neekodesu** [Hekili/hekili#2112]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my Outlaw Rogue, Globe of Jagged Ice is not showing in rotation, trincket is not added to Hekili yet i guess :')

### How to Reproduce

Just equip Globe of Jagged Ice and no matter what you do it won't show in rotation (atleast with my Outlaw Rogue)

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQSSimDUSCIBBAAAA

### Snapshot

https://pastebin.com/6BMEKgfC

### Contact Information

Neko#7422

**Comment by Hekili** [comment]
Unless you've made some very odd choices, Globe of Jagged Ice is not going to be recommended in your Interrupts display.  Please provide a snapshot from your Primary display, taken at a time you'd expect Globe to be recommended but it isn't.

**Comment by Hekili** [comment]
You may also want to check if you've changed any settings for Globe of Jagged Ice in /hekili > Gear and Items, especially regarding whether it is enabled and/or which toggle is required.

**Comment by Neekodesu** [comment]
Yeah I didn't change anything, rest of the trinkets work good, the only one
not working is Globe of Jagged Ice. And yeah I don't expect it to show in
my interrupts display obviously, maybe i did wrong the snapshot. Anyways it
just doesn't show. I checked in /hekili gear and items and it's not
disabled, so it should show but it just doesn't.
[image: image.png]
[image: image.png]

**Comment by Hekili** [comment]
> Please provide a snapshot from your Primary display, taken at a time you'd expect Globe to be recommended but it isn't.

**Comment by Neekodesu** [comment]
https://pastebin.com/XvtyADbH

**Comment by Hekili** [comment]
The addon doesn't see `skewering_ice` applied to any targets.  Are you finding yourself with a Skewering Ice buff or a Skewering Ice debuff on your enemies, but the trinket isn't recommended?

Can the trinket be used when there are no stacks of Skewering Ice?

**Comment by Neekodesu** [comment]
I can use the trincket when is not recommended yeah, i press it and goes on CD

**Comment by Neekodesu** [comment]
But I can't use the trincket without stacks of Skewering Ice. I need to hit them first, and then I can press the trinket. I don't know why it doesn't detect skewering ice applied to any targets

**Comment by Hekili** [comment]
In your snapshot, you don't have a target.  Provide a snapshot where you have a target and your target has the Skewering Ice debuff.

**Comment by Neekodesu** [comment]
In the last snapshot I sent I was attacking targets D: seriously

**Comment by Neekodesu** [comment]
Globe of Jagged Ice not showing in rotation - Pastebin.com
<https://pastebin.com/hq8fy6dU> Check now (and yes, i see skewering ice
debuff on their plates)

**Comment by Neekodesu** [comment]
https://pastebin.com/RqASQsnJ Here is a new snapshot, in this case I'm using the trincket but i'm not getting the suggestion of Hekili, I'm using it anyways. So I guess this is a bug that needs to get fixed?
