### ISSUE TITLE
Serpent Sting not in MM Rotation

### ISSUE THREAD

**Issue by TheTylerOlson** [Hekili/hekili#2114]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The Hunter talent Serpent Sting is not appearing in the Marksmanship Hunter rotation.

### How to Reproduce

1. Play as Hunter
2. Switch to MM spec
3. Talent into Serpent Sting on the Hunter Tree
4. Try normal rotation, serpent sting will not show

### Talent Loadout

B4PAIlFMjeNhnEouGfV8Ij2uS5ARoFASCCCAAAAQkERSSi4ACRSLkGRQRKaCJJhESoBAAAAA

### Snapshot

https://pastebin.com/d3ZeMz1s

### Additional Information

Character Data from add-on as well:

build: v10.0.2-2.0.3
level: 70 (70)
class: HUNTER
spec: marksmanship

talents: aimed_shot
    arctic_bola = 2/2
    binding_shot = 1/1
    born_to_be_wild = 2/2
    bulletstorm = 1/1
    camouflage = 1/1
    careful_aim = 2/2
    counter_shot = 1/1
    crack_shot = 1/1
    death_chakram = 1/1
    deathblow = 1/1
    double_tap = 1/1
    eagletalons_true_focus = 2/2
    explosive_shot = 1/1
    focused_aim = 2/2
    hunters_avoidance = 1/1
    hunters_knowledge = 1/2
    improved_kill_shot = 1/1
    improved_steady_shot = 1/1
    improved_traps = 2/2
    keen_eyesight = 2/2
    kill_shot = 1/1
    lock_and_load = 1/1
    lone_wolf = 1/1
    master_marksman = 2/2
    misdirection = 1/1
    multishot = 1/1
    natural_mending = 2/2
    natures_endurance = 1/1
    pathfinding = 2/2
    poison_injection = 1/1
    posthaste = 2/2
    precise_shots = 2/2
    rapid_fire = 1/1
    razor_fragments = 1/1
    salvo = 1/1
    serpent_sting = 1/1
    serpentstalkers_trickery = 1/1
    serrated_shots = 1/2
    streamline = 2/2
    surging_shots = 1/1
    survival_of_the_fittest = 1/1
    tar_trap = 1/1
    target_practice = 1/1
    tranquilizing_shot = 1/1
    trick_shots = 1/1
    trueshot = 1/1
    unerring_vision = 1/1
    volley = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: [niya]

sets: erupting_spear_fragment = 1
    irideus_fragment = 1

gear: custodians_medallion_of_delusion = 1
    erupting_spear_fragment = 1
    fatebound_chainmail = 1
    flametouched_legguards = 1
    galerattle_gauntlets = 1
    gnollish_chewtoy_launcher = 1
    irideus_fragment = 1
    ohnahran_falconers_belt = 1
    ohnahran_falconers_bracers = 1
    ohnahran_falconers_coif = 1
    ohnahran_falconers_shoulderguards = 1
    ohnahran_falconers_striders = 1
    platinum_star_band = 1
    potionstained_cloak = 1
    ranged = 1
    ring_of_embers = 1
    tabard_of_the_wild_hunt = 1

legendaries: none

itemIDs: 178336, 191998, 192000, 192002, 192004, 192037, 193426, 193647, 193708, 193712, 193743, 193752, 193769, 193801, 200163, 200266

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Marksmanship
    petbased = false
    potion = spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    eagletalon_swap = false
    prevent_hardcasts = false

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = true [overridden]
    interrupts = true [separate]
    mode = automatic 
    potions = false 

keybinds: 
    aimed_shot              = 4   [01]
    arcane_shot             = 1   [01], =   [11]
    aspect_of_the_cheetah   = C7  [06]
    aspect_of_the_turtle    = C9  [06]
    bag_of_tricks           = C-  [06]
    binding_shot            = A-  [05]
    camouflage              = A1  [05]
    counter_shot            = C8  [06]
    death_chakram           = C1  [06]
    disengage               = 9   [01]
    double_tap              = C4  [06]
    erupting_spear_fragment = A0  [05]
    exhilaration            = =   [01]
    explosive_shot          = 6   [01]
    feign_death             = C=  [06]
    freezing_trap           = A3  [05]
    healthstone             = A4  [05]
    irideus_fragment        = C0  [06]
    kill_shot               = 0   [01]
    multishot               = 5   [01]
    rapid_fire              = -   [01]
    serpent_sting           = 8   [01]
    steady_shot             = 2   [01]
    survival_of_the_fittest = C3  [06]
    tranquilizing_shot      = C5  [06]
    trueshot                = C6  [06]
    volley                  = 7   [01]

warnings: none

### Contact Information

Twitter @TheTylerOlson

**Comment by Hekili** [comment]
> serpentstalkers_trickery = 1/1

It is present in the priority, but isn't used directly most of the time because your Aimed Shot will apply it instead.  

Use if it's refreshable, you didn't talent Serpentstalker's Trickery, and Trueshot Aura is down:
> actions.st+=/serpent_sting,cycle_targets=1,if=refreshable&!talent.serpentstalkers_trickery&buff.trueshot.down

Use if it's refreshable and you talented for Poison Injection but not Serpentstalker's Trickery:
> \# Only use baseline Serpent Sting as a filler in cleave if it's the only source of applying Latent Poison.
> actions.trickshots+=/serpent_sting,cycle_targets=1,if=refreshable&talent.poison_injection&!talent.serpentstalkers_trickery

The exception is if you don't take Serpentstalker's Trickery or if you do take Hydra's Bite:
> actions.trickshots+=/serpent_sting,cycle_targets=1,if=refreshable&talent.hydras_bite
