### ISSUE TITLE
Incomplete Outlaw ticket

### ISSUE THREAD

**Issue by Fowka2** [Hekili/hekili#2117]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Shadowmeld is not in the rotation and nor is vanish. In Shadowlands it used to prioritise Vanish and Shadowmeld. Now in Dragonflight Shadowmeld and Vanish never gets used. Also my trinket never shows up when to use. Feels like the Rogue rotation needs to be reworked and fully touched up

### How to Reproduce

Be a "Night Elf - Rogue". 
Left click the Hekili icon next to maps
Allow Shadowmeld

Kill something with high HP so you could do your rotation and you will never see Vanish and Shadowmeld

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRiIJJJhAAAAAAAkEkmDUSCIJpEAAAA

### Snapshot

Can't  snapshot as I don't know when you'd use Shadowmeld or Vanish.

### Additional Information

I feel like the Rogue (OUTLAW) spec feels off. It doesn't show trinkets and I know many people complained on Discord. Shadowmeld or Vanish is never used or prioritised. I have deleted the addon re-installed and still the same issue.

Please can you look into the OUTLAW spec

### Contact Information

Majór#3090

**Comment by vond82** [comment]
Trinkets have been in for a while now, and it definitely shows vanish for me (not NE so no idea about shadowmeld, just know that meld works properly for feral). Did you make sure that cooldowns etc are enabled?

**Comment by Fowka2** [comment]
![image_2022-12-09_195535865](https://user-images.githubusercontent.com/100809564/206786019-4592e0c7-88e8-4cac-a3a0-59d2cdd72e72.png)

**Comment by Fowka2** [comment]
I always have it on, Been using Hekili since god knows never had an issue till now

**Comment by IIeTpoc** [comment]
What i can tell is that Hekili follows simulation APL very smooth and accurate at least for me. So you should provide some more explanation on why Vanish or Shadowmeld should be prioritized, how much of DPS advantage it will give according to simcraft, etc

**Comment by Fowka2** [comment]
There would be moments when your spamming Sinister Strike. Instead of doing that we could Shadowmeld and then proc Subterfuge and be able to spam Ambush - so there is a DPS gain there. In shadowlands Hekili made us use Shadowmeld and then Dispatch or Vanish - Dispatch

**Comment by Hekili** [comment]
> Can't snapshot as I don't know when you'd use Shadowmeld or Vanish.

Of course you can.  You described it yourself; Sinister Strike is recommended but you think you should Shadowmeld/Vanish instead.  That's the time to snapshot.

I'm going to close this ticket because I'm not able to validate any of the issues you've described.  For the record:

1. Both Shadowmeld and Vanish are in the Outlaw priority and have conditions associated with their usage.
2. Trinkets (both specific items like Manic Grieftouch and trinket usage more generically via `Trinket #1` and `Trinket #2` actions are in the priority.

Glove of Jagged Ice specifically has a fix queued related to finding the required DOT on a target before the trinket is usable.
