### ISSUE TITLE
Default APL for Enhancement Single Target is missing a priority 

### ISSUE THREAD

**Issue by lollerlaban** [Hekili/hekili#2118]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When talented into Hot Hand and Ashen Catalyst, the line 
lava_lash,if=buff.hot_hand.up|buff.ashen_catalyst.stack=8 

Is supposed to be 2nd priority for ST but is absent

Taken from Hekili
![image](https://user-images.githubusercontent.com/3268887/206823334-beec6dae-15c0-4c5b-984e-7e783bcaffae.png)

Taken from the SimC
![image](https://user-images.githubusercontent.com/3268887/206823361-007b0c42-2fcf-44d6-a540-b2c3ac593f0c.png)

### How to Reproduce

1. Spec into Enhancement
2. Talent into Hot Hand & Ashen Catalyst 
3. Priority doesn't change according to these two talent choices in single target

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJpEJgkEikkQJhAAAAAAAAAAAAAQLCRIBFBkUSSSJASkEA

### Snapshot

https://pastebin.com/7XLYK0ab

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/k2gSoFSvxxmFExhwD7XyCR/simc

**Comment by Hekili** [comment]
This was resolved a while ago; thanks for the report!
