### ISSUE TITLE
ashvanes_razor_coral does not show in rotation. 

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#212]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
(v8.2.0-08.04)

**Describe the Bug/Issue**
use_item_ashvanes_razor_coral does not show in rotation.

**Comment by Hekili** [comment]
I'll wait to see if you complete the full ticket; I won't be able to help you without the information it asks for.

**Comment by Hekili** [comment]
Trinkets are linked to your "cooldowns" toggle by default.  If that is not the issue, please submit a complete ticket.

**Comment by geraint425** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
(v8.2.0-08.04)

**Screenshots**
https://imgur.com/a/Zk9gVY5

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v8.2.0-08.04
level: 120 (120)
class: DEATHKNIGHT
spec: frost

talents: asphyxiate
    breath_of_sindragosa
    cold_heart
    frozen_pulse
    gathering_storm
    runic_attenuation
    wraith_walk

azerite: azerite_empowered=1
    blightborne_infusion=1
    frozen_tempest=2
    gemhide=1
    gutripper=1
    heed_my_call=1
    icy_citadel=1
    latent_chill=1
    resounding_protection=1
    unstable_catalyst=1
    unstable_flames=1
    vampiric_speed=1

essences: [condensed_lifeforce]=3, memory_of_lucid_dreams=3

sets/legendaries/artifacts: none

gear:     _=1
    __=1
    __7_=1
    ___=1
    ____=1

itemIDs: 155884, 158075, 159415, 159448, 159658, 163403, 167276, 167346, 168360, 168869, 169157, 169159, 169311, 169319, 170143, 69210, 89195

The problem is that you generally have no coral in rotation. There is a ready-made apl which in which there are conditions for coral and not only. https://pastebin.com/CZCnR52v 

please follow the link and see. thank.
