### ISSUE TITLE
[Retail] Sub Rogue priority list not suggesting Shuriken Tornado properly

### ISSUE THREAD

**Issue by DumbRogue** [Hekili/hekili#2121]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I've noticed while trying out Sub Rogue on the cleave target dummies that Shuriken Tornado is not suggested during the opener (should be used before Secret Technique), and the priority list seems to remove Shuriken Tornado from the list once certain cooldowns are pressed. For example, in the snapshots I've included below, it suggests Shadowstrike --> Symbols --> Shuriken Tornado, but as soon as Symbols is pressed Shuriken Tornado is removed from the priority list. 

### How to Reproduce

1. Talent into Shuriken Tornado.
2. Run through the opener on multiple targets, Shuriken Tornado won't be suggested at all.
3. Continue following priority until Shuriken Tornado is suggested after any cooldown
4. Press the cooldown preceding Shuriken Tornado
5. Shuriken Tornado will be removed from the priority list.

### Talent Loadout

BUQAOB/7AZ//CwQOf4fPMswHVDAAAAAAAAAARCkkICBIRSSikkEBJRIJJJJaJlIkkEAAAAA

### Snapshot

https://pastebin.com/CaBcEavy (before pressing Symbols) https://pastebin.com/UYKkwTaA (after pressing Shadowstrike/Symbols)

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nKxLzTHjQh2BmNGiRcMpAi

**Comment by Xa3lis** [comment]
Can confirm

**Comment by Hekili** [comment]
Is this still occurring in the latest releases?
