### ISSUE TITLE
Survival Hunter - Kill Command and Flanking Strike are recommended even if casting them will cap focus or you are already at the focus cap.

### ISSUE THREAD

**Issue by ManticoreFalco** [Hekili/hekili#2123]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For Survival Hunter, you are not recommended to cast Kill Command or Flanking Strike if doing so will put you over focus cap. However, the addon is recommending them as part of my opening sequence before casting any focus spenders if I have cooldowns off.

![Hekili](https://user-images.githubusercontent.com/120286114/206880458-86d0149d-c6f3-46f0-90ce-957bd5da0751.jpg)

This happens in both my single-target and AOE specs:
Single-target (also included below): B8PAIlFMjeNhnEouGfV8Ij2uSJgWgkDgEEkIRaJkIkkESkAAAAAABRRoJkIhkIhGAAAAA
AOE: B8PAIlFMjeNhnEouGfV8Ij2uSJgSISESQQiEplIIkkkSECAAAAAExBUEaCJSIJSoBAAAAA

### How to Reproduce

1. Enter the game as a Survival Hunter.
2. Talent into Flanking Strike and Wildfire Infusion, but do not talent into Alpha Predator.
3. Observe your opening sequence in Hekili.
4. ---> Kill Command and Flanking Strike are recommended before spending an focus.
5. Engage a target dummy, casting both focus spenders and builders as recommended.
6. ---> Hekili will recommend Kill Command and Flanking Strike, regardless of focus status.
7. When Pheromone Bomb is active, cast it.
8. ---> Hekili will recommend Kill Command spam, regardless of focus amount.

### Talent Loadout

B8PAIlFMjeNhnEouGfV8Ij2uSJgWgkDgEEkIRaJkIkkESkAAAAAABRRoJkIhkIhGAAAAA

### Snapshot

https://pastebin.com/FPPfkJDb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/u7hrTtqpvm1pGhM6erUEEf

**Comment by ManticoreFalco** [comment]
I'm including a snapshot for my AOE rotation, where Flanking Shot is Recommendation #3 despite the fact that it would cap my focus there: https://pastebin.com/Zz2bn9Xd

![WoWScrnShot_121022_183300](https://user-images.githubusercontent.com/120286114/206880943-b0c86bc1-cc57-4924-a505-1fc2fd5f5c93.jpg)

**Comment by Hekili** [comment]
Yep, it does that. You can adjust it in a custom priority if you'd like, because the alternative has been that you can get stuck leaving abilities off cooldown because you're stuck trying to spend down Focus endlessly. 

When I have more time, I'll do some comparison sims.

**Comment by ManticoreFalco** [comment]
Thanks; I'll see if I can figure it out. 😅

**Comment by Hekili** [comment]
Thanks.  I'm going to reapply the Focus checks and see how that plays out for a bit.  This will be in the next release.
