### ISSUE TITLE
When using Eternity Surge, a Snapshot is taken in AOE

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2124]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When a fight occurs with a large number of targets, if I use Eternity Surge, the addon stops displaying the Eternity Surge icon and writes in the chat that an automatic Snapshot has been taken.

### How to Reproduce

1. Start the fight with 5+ targets.
2. Use Fire Breath first
3. And now Eternity Surge.
The icon may disappear, or it may not correctly indicate how many targets are being counted and not show readiness to click.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhTDCAAAAAAKahkISSkgEJlkk0CSLkIhkEIJJSESSC

### Snapshot

https://pastebin.com/g1XNyRbx

**Comment by Hekili** [comment]
This snapshot doesn't seem to match what you describe.  Is this an additional snapshot you manually took, or the snapshot it generated when it says it generated one?

**Comment by Dragonfo** [comment]
I have attached a visual picture where goal counting does not work. https://imgur.com/a/vFjmPdd 
Targets started counting only when I used Azure Strike.

**Comment by Dragonfo** [comment]
I didn't take this Snapshot. This was done automatically. There is a screenshot at which point it was done. Adonne took a screenshot automatically. https://imgur.com/a/mUJr51S

**Comment by Delerp** [comment]
Also getting this sometimes in m+ aoe situations, https://pastebin.com/cHPYU7tt

Automatic snapshot

Usually happens pretty rarely though, think it happened once in that dungeon. Eternity surge is diplayed then disappears

edit: another snapshot from brackenhide m+ https://pastebin.com/LWN5qaGG

**Comment by Hekili** [comment]
Thanks; this will be addressed in the next release.
