### ISSUE TITLE
Add a goal count for Deep Breath Evoker

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2125]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Please add a goal count for Deep Breath Evoker. When using Deep Breath, the addon does not count how many targets were hit by Deep Breath. You have it perfectly implemented with Frostwyrm's Fury. When Frostwyrm's Fury flies over targets and deals damage to them, the addon counts how many targets. Please add the same function for Deep Breath as Frostwyrm's Fury. Thanks.

**Comment by Hekili** [comment]
I think there's some fundamental misunderstanding here.

What makes you think the addon doesn't count targets hit by Deep Breath?

**Comment by Dragonfo** [comment]
I have attached a visual picture where goal counting does not work. https://imgur.com/a/vFjmPdd
Targets started counting only when I used Azure Strike.
