### ISSUE TITLE
new potions

### ISSUE THREAD

**Issue by T0xicsmog** [Hekili/hekili#2128]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

i think new elemental potion of power and ultimate version need to be added to hekilli

### Additional Information

not getting recommendation of using these potions (unable how to snapshot such an error)

**Comment by Hekili** [comment]
Yep, they'll get added.
