### ISSUE TITLE
ashvanes_razor_coral does not show in rotation.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#213]
BEFORE SUBMITTING AN ISSUE:

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
(v8.2.0-08.04)

Screenshots
https://imgur.com/a/kAKkdL0

WHEN SUBMITTING AN ISSUE:

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v8.2.0-08.04
level: 120 (120)
class: DEATHKNIGHT
spec: frost

talents: asphyxiate
breath_of_sindragosa
cold_heart
frozen_pulse
gathering_storm
runic_attenuation
wraith_walk

azerite: azerite_empowered=1
blightborne_infusion=1
frozen_tempest=2
gemhide=1
gutripper=1
heed_my_call=1
icy_citadel=1
latent_chill=1
resounding_protection=1
unstable_catalyst=1
unstable_flames=1
vampiric_speed=1

essences: [condensed_lifeforce]=3, memory_of_lucid_dreams=3

sets/legendaries/artifacts: none

gear: _=1
__=1
_7=1
___=1
____=1

itemIDs: 155884, 158075, 159415, 159448, 159658, 163403, 167276, 167346, 168360, 168869, 169157, 169159, 169311, 169319, 170143, 69210, 89195

The problem is that you generally have no coral in rotation. There is a ready-made apl which in which there are conditions for coral and not only. https://pastebin.com/CZCnR52v

please follow the link and see. thank.

**Comment by geraint425** [comment]
PLS update apl https://github.com/simulationcraft/simc/commit/d2427e9afd7f1beab2dc3c1446848f7713c3a4aa

**Comment by Hekili** [comment]
I will update APLs.

In the meantime, you can edit your own priority.  Thanks.

**Comment by geraint425** [comment]
As soon as I add two variables to the Default rotation, 
 cooldowns -> add_action( "use_item,name=ashvanes_razor_coral,if=debuff.razor_coral.down" );
  cooldowns -> add_action( "use_item,name=ashvanes_razor_coral,if=cooldown.empower_rune_weapon.remains>90&debuff.razor_coral_debuff.up&variable.other_on_use_equipped|buff.breath_of_sindragosa.up&debuff.razor_coral_debuff.up&!variable.other_on_use_equipped|buff.empower_rune_weapon.up&debuff.razor_coral_debuff.up&!talent.breath_of_sindragosa.enabled|target.1.time_to_die<21" )

Coral appears and the rotation goes on. But as soon as it goes to rotation, when Sindragosa is active, it simply does not appear. Believe me, if it would be so simple to add. I would not write here.  And you did not update APL. Since the latest changes did not get up.
