### ISSUE TITLE
Prot Paladin: Hammer of Wrath temporary adjustment due to bug

### ISSUE THREAD

**Issue by caseyjfer** [Hekili/hekili#2130]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For prot paladin (mine is level 51), Hammer of Wrath is shown as priority during Avenging Wrath, but there is a current bug that does not allow it to be used in this use case. It is only usable on the current target when the current target is under 20% health. I tried making this modification, but I'm not sure of the correct syntax for target health percentage, but it should probably be addressed in the default priorities until it's fixed.

### How to Reproduce

1. Use Avenging Wrath on Prot Paladin
2. View the presented priority recommendation for Hammer of Wrath when it shows up

### Talent Loadout

BIEAwtJ2KpR8WbGzhz/jy2AP80QSCiiIJBFkQCCBAAAAAAAAAAAAAAFJJRIBJRBAlQA

### Snapshot

https://pastebin.com/GKC3AAQb

**Comment by alexspew** [comment]
I believe the syntax you are looking for is :: target.health.pct <= 20

**Comment by caseyjfer** [comment]
> I believe the syntax you are looking for is :: target.health.pct <= 20

I have tried this, and target.health.percent <= 20, and target.health.pct < 20 and target.health.percent < 20.

![image](https://user-images.githubusercontent.com/30360586/206938193-c863d4ba-13f1-4722-bc5a-3186249cf41b.png)

![image](https://user-images.githubusercontent.com/30360586/206938218-aca20852-b798-4d50-994b-94ffb7cba2f7.png)

I still end up with the priority appearing when I have Avenging Wrath up

**Comment by Hekili** [comment]
This should be resolved as of the 2.0.4 release.

**Comment by caseyjfer** [comment]
> This should be resolved as of the 2.0.4 release.

Can confirm, thanks @Hekili
