### ISSUE TITLE
[WotLK] Prot paladin priority recommends Divine Plea and Sacred Shield while buffs are still active.

### ISSUE THREAD

**Issue by beanlord7** [Hekili/hekili#2131]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

When using the default prot paladin priority list for WotLK, the addon incorrectly recommends these buffs in these situations:

* Sacred shield (snapshot 1) - After engaging in combat, hekili recommends applying SS. After applying SS, it recommends refreshing SS immediately afterwards, while SS is almost at full duration. After refreshing, it does not recommend it again for 30s.
* Sacred shield 2 (snapshot 2) - after the above issue, SS is always recommended to be refreshed after 30s, even when the Divine Guardian talent is taken, which increases SS duration to 60s. SS is recommended when the buff is still present and has 30s duration left.
* Divine Plea (snapshot 3) - DP is recommended to be refreshed every time it's off CD. Guarded by the Light talent refreshes DP duration every time you hit an enemy, so DP buff can have full duration, but hekili will recommend DP every time it's available, effectively wasting the cooldown.

### How to Reproduce

1. Have Divine Guardian and Guarded by the Light talents.
2. follow the steps described above.

### Snapshot

https://pastebin.com/LJ1yVaZ7   https://pastebin.com/4e01LiCc   https://pastebin.com/txf8bSJU

**Comment by Hekili** [comment]
These should be resolved in the upcoming release.
