### ISSUE TITLE
Darkmoon trinket active cards buff tracking option

### ISSUE THREAD

**Issue by pefcs** [Hekili/hekili#2137]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I recommend to add the tracking option for the darkmoon trinkets' active buffs. So the addon can recommend the deck if the buff is on a certain level.
Eg. I modified the items.lua - darkmoon_deck_watcher the following way:

    darkmoon_deck_watcher = {
        cast = 0,
        cooldown = 90,
        gcd = "off",

        item = 198089,
        toggle = "defensives",

        handler = function()
            applyBuff( "watchers_blessing" )
        end,

        proc = "versatility",
		
	auras = {
            ace_of_earth = {
                id = 382852,
                duration = 0,
                max_stack = 1
            },	
            two_of_earth = {
                id = 382853,
                duration = 0,
                max_stack = 1
            },
            three_of_earth = {
                id = 382854,
                duration = 0,
                max_stack = 1
            },
            four_of_earth = {
                id = 382855,
                duration = 0,
                max_stack = 1
            },
            five_of_earth = {
                id = 382856,
                duration = 0,
                max_stack = 1
            },
			six_of_earth = {
                id = 382857,
                duration = 0,
                max_stack = 1
            },			
            seven_of_earth = {
                id = 382858,
                duration = 0,
                max_stack = 1
            },
            eight_of_earth = {
                id = 382859,
                duration = 0,
                max_stack = 1
            }			
		}
    },

So then I can add the following condition for the trinket usage:

tanking & incoming_damage_5s > 0.15 * health.max & ( buff.ace_of_earth.up | buff.eight_of_earth.up )

This might be valuable for other darkmoon trinkets also.

### How to Reproduce

Use darkmoon trinket

### Snapshot

no snapshot is needed

**Comment by schattenaffe** [comment]
I actually came here looking for something similar for Darkmoon Deck Box Inferno so that it only recommends me to cast it when I have the Ace buff. The damage of any other buff seems useless comparatively so it's better to wait an extra 30secs-1min to get a single 140k cast rather than a 35k cast most of the time on cooldown. I'm just not smart enough to know how to add that in myself manually.

**Comment by Hekili** [comment]
I'll add the auras, but I don't plan to customize priorities to account for the buffs directly.
