### ISSUE TITLE
[WOTLK] Mage plugin isn't working at all.

### ISSUE THREAD

**Issue by Cursedpayne** [Hekili/hekili#2139]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

I've just recently started using the addon and saw an issue from a few months ago with mages that was supposedly resolved. But having gone through and setting up my new UI on all of my characters the addon automatically pops up with the rotation on login. This hasn't been the case on my mage and was wondering if there was any troubleshooting I could do on my end to help fix this.

### How to Reproduce

None

### Snapshot

None

### Contact Information

Cursedpain#1301

**Comment by eyeeric** [comment]
Having the same issue. On classic server, my pally loads just fine. On mage, under priority class, it just says none. No option to choose frost, fire, etc. So I think that's the issue, just not sure how to fix it!

**Comment by sell-westfall** [comment]
I can't get this to on my arcane mage....help

**Comment by JDensen** [comment]
Same issue as well on my mage. Any update on a patch?

**Comment by JDensen** [comment]
Same issue as well on my mage. Any update on a patch?

**Comment by JDensen** [comment]
@Hekili Any update with this? Addon still doesnt work with any mage spec in WotLK Classic. Would love to use, great addon.

**Comment by Hekili** [comment]
If there's an update, it'll be here -- no need to ask.  Wrath dev work takes a backseat to Retail dev work, unfortunately.

**Comment by Rentastic** [comment]
I cannot get Hekili to work on my Frost mage still. In WOTLK  Absolutely love this addon but its sad that what I need isn't available.  Thanks in advance!

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
