### ISSUE TITLE
Is it possible to combine the number of targets by radius and the number of targets by dots?

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#214]
Good day. I want to ask you about how your addon recognizes the number of goals, and automatic switching to AOE. Why did I decide to raise this issue. Everything is very simple. I play as a death knight class. And I like to play in the specialization of ADK and FDK. 
The bottom line is that these two specializations have spells that hang dots. Let's say that FDK is not very critical if we forget to update the howling wind. But with ADK, if we do not update the plague, we cannot push the epidemic. What am I getting at? I suppose maybe other classes of specializations are experiencing. I’m sure the problem is that the addon does not know how to work with analysis in the vicinity and at the distance due to dots. 
You have these two functions, but they work separately from each other. We either count on a radius close to the character. Or we consider the goals for hanging Dots. But if you activate both of them, the result will be 0. I would like to ask you why their work in the place is not possible? After all, let’s say the ADC has a plague that hangs dots and then we don’t care what distant the enemy character will be. We just hit the epidemic and just hit. This is very convenient. When we can not be distracted from rotation by standing next to other enemy creatures, beat them and thereby after their death we will continue to see those who are in the distance under our spell of the plague. I would really like you to implement the simultaneous operation of these two functions. Since it is just very easy to count in goals. Just for the moment I play for the ADC, I use the definition of goals only by Dots because then I can’t understand if I still have a plague on them or not. And also I noticed that the count of goals is not immediately reset when the enemy creature dies. 
I found the response time of this function when the creature dies and the target updates but it does not help much. And also you have a separate checkmark on the ADC for the ulcer talent on Azerite that helps in AOE it doesn’t work correctly, he can offer me to switch to a target that is generally beyond my radius in the distance, when I’m allowed, I’m pouring a puddle in the vicinity and I’m beating next to them I spread ulcers, and he can offer me to run 5 meters to another and hang ulcers on him. This again does not work correctly.

**Comment by Hekili** [comment]
I need you to narrow your focus to the thing you want.  Between the translating and the speculating, I can't tell what you're requesting here.

What is the problem you are trying to solve?

You can already use nameplate and damage/dot-based target detection together.

`But if you activate both of them, the result will be 0.`

The result is never 0.  The addon always pretends there is at least one target.  If you use both nameplate-based target detection and damage/dot-based target detection, the range filtering still applies to any targets that have a nameplate.

`I found the response time of this function when the creature dies and the target updates but it does not help much.`

If a target dies (and WoW actually provides a death event in the combat log), it is no longer counted.  If WoW doesn't provide a death event, the target stops being counted when the timer runs out.  There are no real alternatives to those two approaches.

`And also you have a separate checkmark on the ADC for the ulcer talent on Azerite that helps in AOE it doesn’t work correctly, he can offer me to switch to a target that is generally beyond my radius in the distance, when I’m allowed, I’m pouring a puddle in the vicinity and I’m beating next to them I spread ulcers, and he can offer me to run 5 meters to another and hang ulcers on him.`

It absolutely works, it's doing what it's supposed to do based on the conditions you've provided.  When you say you want dotted targets to be counted as valid targets regardless of distance, you're going to get recommendations to (re)dot those targets regardless of distance.  If that's not helpful to you, don't check the box.
