### ISSUE TITLE
Ambush not being suggested as opener during stealth - Outlaw Rogue

### ISSUE THREAD

**Issue by R34P3R89** [Hekili/hekili#2141]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Since the last update, the addon does not recommend Ambush any longer as opener while stealthed.
It worked flawlessly before but now the opener is simply:
Stealth -> Roll the Bones -> Sinister Strike
Even when I check the option in the Outlaw tab to use Ambush regardless of talents, it doesn't suggest Ambush. Also, even when I manually engage combat using Ambush, the addon does not suggest it entering the next fight.
I also tried adding this line in the profile tab manually, but failed to do so successfully.

![Hekili Screenshot](https://user-images.githubusercontent.com/120551242/207532855-bca64c82-738d-455b-bd17-1275532b4457.jpg)

### How to Reproduce

1. Enter game as Rogue using the Outlaw spec.
2. Choose any talents 
3. Tick the option for Hekili to suggest Ambush regardless of talents in the Outlaw Tab within Hekili
4. Go to a training dummy or any mob
5. Look at Hekili's suggested rotation - either unstealthed or stealthed.

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgEkECkkkkUEhQQSISgkkIAAAAAAARSimDIOAOQSoFAAAA

### Snapshot

https://pastebin.com/zeLQNUUF

**Comment by Hekili** [comment]
This behavior matches the priority as written -- you haven't talented for Opportunity or Find Weakness.  I may revise to support the specialization option to Ambush regardless of talents, though.

**Comment by R34P3R89** [comment]
Thank you! Meanwhile I did spec those two talents and it works. If you could revise it though, it would give me more freedom with the talents. Thanks a lot!

**Comment by Hekili** [comment]
See /hekili > Outlaw; there is a specialization setting that will allow Ambush to be recommended regardless of your talents.
