### ISSUE TITLE
DK - icon for Bone Shield will not display

### ISSUE THREAD

**Issue by shawn571** [Hekili/hekili#2145]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

The Bone Shield icon will not display, even when the condition says Shown

### How to Reproduce

1. Enter game as a Death Knight with Unholy specialization and Bone Shield talent
2. Create an action for Bone Shield (conditions don't matter, it won't display even if no conditions are set)
3. Icon isn't listed in the recommendations, even though in the conditions box it says it's Shown and if the action is first priority

### Player Information (Link)

```Text
build: v3.4.0-1.0.0-beta9
level: 74 (74)
class: DEATHKNIGHT
spec: deathknight

talents: black_ice
    bloodcaked_blade
    bone_shield
    crypt_fever
    desolation
    dirge
    ebon_plaguebringer
    ghoul_frenzy
    icy_talons
    improved_icy_touch
    impurity
    master_of_ghouls
    morbidity
    necrosis
    nerves_of_cold_steel
    night_of_the_dead
    rage_of_rivendare
    ravenous_dead
    runic_power_mastery
    summon_gargoyle
    unholy_blight
    vicious_strikes
    virulence
    wandering_plague

pvptalents: none

covenant: none

conduits: none

soulbinds: none

sets: none

gear: antique_reinforced_legguards = 1
    coldstone_cutlass = 1
    dual_wield = 1
    executioners_band = 1
    first_mates_pocketwatch = 1
    fury_of_the_encroaching_storm = 1
    mainhand = 1
    offhand = 1
    onyx_grips = 1
    overseers_signet = 1
    razorblade_pendant = 1
    runeplate_helm = 1
    seething_waistguard = 1
    shaleground_bracers = 1
    shroud_of_frenzy = 1
    sigil_of_the_dark_rider = 1
    spiked_cobalt_boots = 1
    spiked_cobalt_chestpiece = 1
    spiked_cobalt_shoulders = 1
    stoneblade_slicer = 1

legendaries: none

itemIDs: 30365, 31143, 35808, 35824, 35835, 35891, 35903, 35910, 36871, 37509, 38218, 38259, 39208, 40949, 40950, 40951, 44375

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcd = 47541
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Unholy Morb
    package1 = Blood (IV)
    package2 = Frost DK (IV)
    package3 = Blood (IV)
    petbased = false
    potion = prolonged_power
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false

toggles:     cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = false 
    interrupts = true 
    mode = dual 
    potions = false 

keybinds: 
    blood_boil      = SQ  [03]
    blood_strike    = Q   [03]
    blood_tap       = MwU [04]
    bone_shield     = AQ  [01]
    chains_of_ice   = AR  [04]
    dark_command    = SE  [03]
    death_and_decay = A3  [01]
    death_coil      = 3   [01]
    death_grip      = A1  [01]
    death_strike    = E   [03]
    ghoul_frenzy    = AE  [01]
    horn_of_winter  = A2  [01]
    icy_touch       = 1   [01]
    mind_freeze     = S1  [03]
    pestilence      = R   [03]
    plague_strike   = 2   [01]
    rune_strike     = MwD [04]
    strangulate     = S2  [03]
    summon_gargoyle = S3  [03]
    will_to_survive = =   [01]
```

### Error Messages (Link)

```Text
No errors
```

### Contact Information

WittyWalnut137#4427

**Comment by Hekili** [comment]
This should've been a Recommendations ticket and included a snapshot.  See instructions below.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by shawn571** [comment]
https://pastebin.com/NRnLJCif

**Comment by shawn571** [comment]
I saw that Bone Shield is considered a defensive ability which is why it wasn't showing up. So this issue can be closed or Bone Shield considered to be part of the unholy recommendations because of the 2% damage buff while it's up

**Comment by Hekili** [comment]
Those kinds of updates would be handled with routine priority updates when the time comes, so a ticket isn't needed.  Thanks for updating.
