### ISSUE TITLE
Death and Decay recommenced too early or back to back

### ISSUE THREAD

**Issue by WOWLIT** [Hekili/hekili#2147]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Death and decay is being recommended either too early or back to back during dungeons. I'm not too sure if the snapshot is correct but please let me know and i'll try again if necessary. 

### How to Reproduce

Blood death knight
I took the snapshot in dungeon academy but happens in all dungeons
Following the recommendations 

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDikECJJi0iERkISIIJJRCAAAAAASSSQSLhIBAAEJJJBAAAA

### Snapshot

https://pastebin.com/8gtpxc4y

**Comment by Hekili** [comment]
The sim priority is explicitly written to use both charges with 4+ enemies or if Crimson Scourge is up.  If you provide a comparison sim of your character in Hectic Add Cleave or Patchwerk with 4+ bosses, I can sim to determine if saving the second charge of Death and Decay is worthwhile.
