### ISSUE TITLE
Ret paladin: Addon not suggesting AOE rotation when in aoe situations.

### ISSUE THREAD

**Issue by Troniin** [Hekili/hekili#2149]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The addon is not suggesting AOE abilities in AOE situations. It still suggests the use of TV instead of DS.

### How to Reproduce

Enter a group of mobs.
Notice addon suggest TV instead of DS

### Player Information (Link)

```Text
\build: v10.0.2-2.0.5c
level: 70 (70)
class: PALADIN
spec: retribution

talents: art_of_war
    ashes_to_ashes = 2/2
    ashes_to_dust = 1/1
    aspiration_of_divinity = 2/2
    auras_of_swift_vengeance = 1/1
    avenging_wrath = 1/1
    blade_of_justice = 1/1
    blade_of_wrath = 1/1
    blessing_of_freedom = 1/1
    blessing_of_sacrifice = 1/1
    blinding_light = 1/1
    cavalier = 1/1
    cleanse_toxins = 1/1
    consecrated_blade = 1/1
    crusade = 1/1
    divine_purpose = 1/1
    divine_resonance = 1/1
    divine_steed = 1/1
    divine_storm = 1/1
    divine_toll = 1/1
    empyrean_legacy = 1/1
    empyrean_power = 1/1
    exorcism = 1/1
    final_reckoning = 1/1
    fist_of_justice = 2/2
    greater_judgment = 1/1
    hallowed_ground = 1/1
    hammer_of_wrath = 1/1
    hand_of_hindrance = 1/1
    holy_aegis = 2/2
    holy_blade = 1/1
    holy_crusader = 1/1
    improved_crusader_strike = 1/1
    incandescence = 1/1
    lay_on_hands = 1/1
    of_dusk_and_dawn = 1/1
    rebuke = 1/1
    recompense = 1/1
    relentless_inquisitor = 2/2
    sanctification = 1/1
    sanctified_wrath = 1/1
    sanctify = 1/1
    seal_of_alacrity = 2/2
    seal_of_might = 2/2
    seal_of_order = 1/1
    seal_of_reprisal = 2/2
    seasoned_warhorse = 1/1
    shield_of_vengeance = 1/1
    tempest_of_the_lightbringer = 1/1
    truths_wake = 1/1
    unbreakable_spirit = 1/1
    virtuous_command = 2/2
    wake_of_ashes = 1/1
    zeal = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: [forgelite_prime_mikanikos]

sets: lifeflame_ampoule = 1
    tier29 = 1

gear: assembly_scholars_loop = 1
    bushwhackers_compass = 1
    cloak_of_lost_devotion = 1
    dragonbane_lance = 1
    gaze_of_the_living_quarry = 1
    lifeflame_ampoule = 1
    petrified_fungal_spores = 1
    platinum_star_band = 1
    reinforced_garden_tenders = 1
    tier29 = 1
    trapmasters_utility_belt = 1
    undercity_doublet = 1
    virtuous_silver_breastplate = 1
    wyrmforged_armplates = 1
    wyrmforged_legguards = 1
    wyrmforged_mantle = 1
    wyrmforged_sabatons = 1

legendaries: none

itemIDs: 192007, 192009, 192010, 192012, 193629, 193669, 193708, 195498, 198451, 198490, 200207, 200267, 200286, 200414, 202119, 45674

settings: aoe = 3
    buffPadding = 0.25
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Retribution
    petbased = false
    potion = spectral_strength
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    blade_of_justice       = 2   [01]
    blessing_of_freedom    = N8  [06]
    cleanse_toxins         = S5  [06]
    consecration           = D   [06]
    crusade                = N5  [01]
    crusader_strike        = 1   [01]
    divine_shield          = N1  [01]
    divine_steed           = N7  [06]
    divine_storm           = N9  [06]
    divine_toll            = N+  [06]
    dragon_games_equipment =
    exorcism               = F   [06]
    final_reckoning        = N0  [06]
    flash_of_light         = N4  [01]
    hammer_of_justice      = N3  [01]
    hammer_of_wrath        = 5   [01]
    judgment               = 4   [01]
    lay_on_hands           = END [06]
    radiant_decree         = M3  [01]
    rebuke                 = N2  [01]
    shield_of_vengeance    = N6  [01]
    templars_verdict       = 3   [01]
    wake_of_ashes          =
    word_of_glory          = `   [06]

warnings: [#1] Unknown buff in [Protection Paladin:mitigation:3]: potion
[string "@Interface/AddOns/Hekili/State.lua"]:3819: in function <Interface/AddOns/Hekili/State.lua:3810>
[string "return buff.potion.up"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:921: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:879: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1196: in function <Interface/AddOns/Hekili/Scripts.lua:1187>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1508: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1597: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Core.lua"]:1480: in function <Interface/AddOns/Hekili/Core.lua:1478>
```

### Error Messages (Link)

```Text
No error messages
```

**Comment by Hekili** [comment]
Hey, this should've been a recommendations ticket, which would've included pasting your talent string and a snapshot where you saw TV recommended but were in AOE.  I can't replicate or test with this ticket.  It's probably easier to submit a new one, but otherwise, you can provide your talent export string plus a snapshot (see description below).

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Troniin** [comment]
I am so sorry about doing this wrong. I have never submitted anything like this. Here is the information requested
 
Snapshot: https://pastebin.com/PkRRk3jv

build: v10.0.2-2.0.5c
level: 70 (70)
class: PALADIN
spec: retribution

talents: art_of_war
    ashes_to_ashes = 2/2
    ashes_to_dust = 1/1
    aspiration_of_divinity = 2/2
    auras_of_swift_vengeance = 1/1
    avenging_wrath = 1/1
    blade_of_justice = 1/1
    blade_of_wrath = 1/1
    blessing_of_freedom = 1/1
    blessing_of_sacrifice = 1/1
    blinding_light = 1/1
    cavalier = 1/1
    cleanse_toxins = 1/1
    consecrated_blade = 1/1
    crusade = 1/1
    divine_purpose = 1/1
    divine_resonance = 1/1
    divine_steed = 1/1
    divine_storm = 1/1
    divine_toll = 1/1
    empyrean_legacy = 1/1
    empyrean_power = 1/1
    exorcism = 1/1
    final_reckoning = 1/1
    fist_of_justice = 2/2
    greater_judgment = 1/1
    hallowed_ground = 1/1
    hammer_of_wrath = 1/1
    hand_of_hindrance = 1/1
    holy_aegis = 2/2
    holy_blade = 1/1
    holy_crusader = 1/1
    improved_crusader_strike = 1/1
    incandescence = 1/1
    lay_on_hands = 1/1
    of_dusk_and_dawn = 1/1
    rebuke = 1/1
    recompense = 1/1
    relentless_inquisitor = 2/2
    sanctification = 1/1
    sanctified_wrath = 1/1
    sanctify = 1/1
    seal_of_alacrity = 2/2
    seal_of_might = 2/2
    seal_of_order = 1/1
    seal_of_reprisal = 2/2
    seasoned_warhorse = 1/1
    shield_of_vengeance = 1/1
    tempest_of_the_lightbringer = 1/1
    truths_wake = 1/1
    unbreakable_spirit = 1/1
    virtuous_command = 2/2
    wake_of_ashes = 1/1
    zeal = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: [forgelite_prime_mikanikos]

sets: lifeflame_ampoule = 1
    tier29 = 1

gear: assembly_scholars_loop = 1
    bushwhackers_compass = 1
    cloak_of_lost_devotion = 1
    dragonbane_lance = 1
    gaze_of_the_living_quarry = 1
    illusion_breakers_waistguard = 1
    lifeflame_ampoule = 1
    petrified_fungal_spores = 1
    platinum_star_band = 1
    reinforced_garden_tenders = 1
    tier29 = 1
    undercity_doublet = 1
    virtuous_silver_breastplate = 1
    wyrmforged_armplates = 1
    wyrmforged_legguards = 1
    wyrmforged_mantle = 1
    wyrmforged_sabatons = 1

legendaries: none

itemIDs: 192007, 192009, 192010, 192012, 193629, 193650, 193708, 195498, 198451, 198490, 200207, 200267, 200286, 200414, 202119, 45674

settings: aoe = 3
    buffPadding = 0.25
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Retribution
    petbased = false
    potion = spectral_strength
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    blade_of_justice    = 2   [01]
    blessing_of_freedom = N8  [06]
    cleanse_toxins      = S5  [06]
    consecration        = D   [06]
    crusade             = N5  [01]
    crusader_strike     = 1   [01]
    divine_shield       = N1  [01]
    divine_steed        = N7  [06]
    divine_storm        = N9  [06]
    divine_toll         = N+  [06]
    exorcism            = F   [06]
    final_reckoning     = N0  [06]
    flash_of_light      = N4  [01]
    hammer_of_justice   = N3  [01]
    hammer_of_wrath     = 5   [01]
    judgment            = 4   [01]
    lay_on_hands        = END [06]
    rebuke              = N2  [01]
    shield_of_vengeance = N6  [01]
    templars_verdict    = 3   [01]
    wake_of_ashes       = M3  [01]
    word_of_glory       = `   [06]

warnings: [#1] Unknown buff in [Protection Paladin:mitigation:3]: potion
[string "@Interface/AddOns/Hekili/State.lua"]:3819: in function <Interface/AddOns/Hekili/State.lua:3810>
[string "return buff.potion.up"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:921: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:879: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1196: in function <Interface/AddOns/Hekili/Scripts.lua:1187>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1508: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1597: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Core.lua"]:1480: in function <Interface/AddOns/Hekili/Core.lua:1478>

**Comment by Hekili** [comment]
No worries.

You have Empyrean Legacy proceed, which will cast Divine Storm automatically when you use Templar's Verdict.
