### ISSUE TITLE
Feral sudden ambush + rake = dot.rake.pmultiplier issue

### ISSUE THREAD

**Issue by W8ink** [Hekili/hekili#2150]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When i have sudden ambush buff persistent_multiplier shows correct calculations, but when i consume sudden ambush with rake dot.rake.pmultiplier shows wrong numbers.
![image](https://user-images.githubusercontent.com/105168976/207857457-c881b1fd-bdfa-40e6-96d5-5f97fd50cc6e.png)
![image](https://user-images.githubusercontent.com/105168976/207857466-7f827526-7c78-4ed8-9f64-db6d22635da7.png)

### How to Reproduce

1. Enter game as Feral
2. take sudden ambush talent
3. Look at Rake persistent_multiplier with sudden ambush proc
4. comsume sudden ambush proc with rake
5. Look at dot.rake.pmultiplier

### Talent Loadout

BcGAYhlYdy9RJ6ROrphOEi69vCAAAAAAQkUikISSSSJtIQEHIJAAAAAAoJASCAiIJkQClEaJJAAAAAAgEA

### Snapshot

https://pastebin.com/R08MN8yv

### Contact Information

W8ink#7189

**Comment by Hekili** [comment]
Thanks for the ticket; I had to change how Sudden Ambush is factored into "real" snapshotting but this will be resolved in the next release.

**Comment by W8ink** [comment]
Good job!
