### ISSUE TITLE
Storm-eaters Boon (Trinket) stops giving recommendations if you don't use it. 

### ISSUE THREAD

**Issue by Khaniixx** [Hekili/hekili#2151]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

If i want to hold my trinket for a better fight, i can no longer see the rest of my recommended abilities.

### How to Reproduce

1. Enter game as Outlaw Rogue
2. Have Storm-eaters Boon (Trinket) equiped
3. Follow recommendations until Storm-eaters Boon appears
4. See recommendations

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAUSEkEkkkkkkIJJCBSISAkIAAAAAAAJBpJlkgkkkSAAAA

### Snapshot

https://pastebin.com/gNkr4ZTV

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8JKY2zU5ZNka5Q6F5vJiez

### Contact Information

Scott#8231

**Comment by Hekili** [comment]
Thanks, this will be resolved in next release.
