### ISSUE TITLE
Brewmaster Monk not showing celestial brew in priority

### ISSUE THREAD

**Issue by bigman2tothe4** [Hekili/hekili#2152]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Celestial brew is never suggested within the priority list. I have tried multiple talent builds with no avail.

### How to Reproduce

1. Enter games as brewmaster monk
2. Pull a tank dummy or pack of mobs
3. See priority queue
4. Never get suggested celestial brews (even with maximize celestial brew enabled)

### Talent Loadout

BwQAdeydY63Y4XKaboK13uRRQAAAAAAAQAAAAAloUSSCIJp0iAAAAkSQSkIhEkkkkSCkISkWKlA

### Snapshot

https://pastebin.com/HJwL1kJz

**Comment by Hekili** [comment]
This will be addressed in the next release.

**Comment by bigman2tothe4** [comment]
> This will be addressed in the next release.

Thanks mate, amazing work
