### ISSUE TITLE
Veng DH rec 3x Throw Glaive after CDs

### ISSUE THREAD

**Issue by towicode** [Hekili/hekili#2154]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In the middle of M+ Hekili will suddenly recommend 3x Throw Glaive.

In the VENG rotation you do use Throw Glaive occasionally as filler, but never 3 in a row. I believe something is wrong.

This happens at 100% energy. I think its trying to pool energy to build fragile stacks for the next combo. But often I am 30+ seconds away from the nearest  CD.

### How to Reproduce

1. Goto the cleave dumbs
2. Follow rotation past FD, SC & The Hunt
3. You should see only Glaive, while both immolation aura and sigil of flame are ready for use.

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAQJJIJRSAEJAUAJR7ARSSSSSS0SiIRSoEJBAAAAA

### Snapshot

https://pastebin.com/zdKkWJKK

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/owvFtVwJQP7g1tBY33jeGL

### Contact Information

todd#8935

**Comment by towicode** [comment]
https://user-images.githubusercontent.com/8232247/207949010-75a87d5a-6afb-473d-a243-39c9d872070b.mp4

**Comment by towicode** [comment]
Not the best video, but I caught the end of it. Slow Throw Glaive recs

**Comment by Hekili** [comment]
I'm adjusting the priority to *probably* fix this; there's some odd use of `target` in the Vengeance APL which translates poorly to the addon.  Will post soon.
