### ISSUE TITLE
Windfury Totem is not recommended when you are out of range of the totem.

### ISSUE THREAD

**Issue by Crelam** [Hekili/hekili#2158]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When Windfury Totem is active and you outrange it. It will not show up in the recommendations, even though it's conditions return as true.

### How to Reproduce

As Enh Shaman, spec into Windfury Totem.
Drop totem across the room.
Walk far enough away.
Smack Training Dummy for extra testing.

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJpEJgkEikkQJhAAAAAAAAAAAAAQLCRIBFBkUSSSLASkEA

### Snapshot

https://pastebin.com/MEQ6Zfsz

### Raidbots Sim Report (Link)

N/A

### Contact Information

Crelam#4360

**Comment by rivengh** [comment]
I can confirm this behavior from my side. Thanks for reporting.

**Comment by Crelam** [comment]
Fixed on build v10.0.2-2.0.7c.  Thank you taco dog man, happy holidays.
