### ISSUE TITLE
Razor coral trinket question for Unholy Dk

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#216]
Hello best addon<3, got a question regarding the trinket Razor coral is it possible when i put it up on example the boss its a debuffon the boss but when there coming up adds on the boss fight the addon recommend that i should use the Razor coral again even if i dont have many stacks on the main target is this intended or cant it read that i have coral up on another target, if theres any thing u can paste so i can put that in would be so much appreciated <3 i just wanna hold the razor untill i got my essence up or the apocalypse again and not waste on switching adds=)

**Comment by Hekili** [comment]
I've made changes to the Razor Coral debuff that it will track the debuff on any target rather than your current target.
