### ISSUE TITLE
Add the ability to deal damage on the move evoker

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2160]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Please add Azure Strike as a filer on the run. Because there is not always the Hover ability so that you can do damage in motion. Azure Strike on the run will help in AOE to mark targets and generate charges for Pyre. It can be done optionally as in MM hunter you did with Steady Shot.

**Comment by Hekili** [comment]
No, you can write a custom priority for this.  The addon is intended to advise optimal abilities to use, and in the case of movement, the best thing to do DPS-wise is to calm your movement.

There is nothing preventing you from pressing Azure Strike while moving regardless of the addon's recommendations.
