### ISSUE TITLE
WOTLK - Several issues with Balance recommendations

### ISSUE THREAD

**Issue by shawn571** [Hekili/hekili#2161]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

1. Recommends Moonkin Form when already in Moonkin form
2. Doesn't recommend Mark of the Wild when buff not active
3. Doesn't recommend Starfire or Wrath when starting combat and there is no Eclipse buff to check for

### How to Reproduce

1. Enter Moonkin Form
2. Do not buff Mark of the Wild
3. Start combat through Insect Swarm, no other recommendations appear

### Snapshot

https://pastebin.com/wsaA1S3k

### Contact Information

WittyWalnut137#4427

**Comment by shawn571** [comment]
Messed up original snapshot, didn't Ctrl-A - here is the new pastebin link
https://pastebin.com/KdermLje

**Comment by codeduph** [comment]
what is this rotation for balance druide (wrath)

![2023-01-28_201601](https://user-images.githubusercontent.com/16449014/215266048-8310cfa9-fc3e-4c16-86a5-fbcaf92050a1.png)
![2023-01-28_201827](https://user-images.githubusercontent.com/16449014/215266052-8c06fcf5-bbbe-4b94-989d-63fda0c28805.png)

using
Hekili [v3.4.1-1.2.1](https://github.com/zmsl/hekili/tree/v3.4.1-1.2.1) (2023-01-24)

**Comment by Hekili** [comment]
@codeduph You'll need to add a snapshot, which is not a screenshot, to diagnose the issue.  Please make sure you're using the latest version of the addon if/when you update.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
