### ISSUE TITLE
[veng] add ability to save one charge of Fiery Brand

### ISSUE THREAD

**Issue by towicode** [Hekili/hekili#2162]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

It would be nice if like the (Infernal Strike) we could select to save one use of Fiery Brand. Not sure how much this would break the addon, especially with the current APL being very Fiery Brand dependent. But it would be nice.

**Comment by Hekili** [comment]
Can you tell me more about why this is beneficial?  When do you hold a charge of Fiery Brand but otherwise want to spend down?

**Comment by towicode** [comment]
DPS wise you would never hold a charge. However, in game-play, especially raiding you may want to hold a charge because it's the veng DH only way of surviving massive tank busters.

Allowing Hekili to use one stack would be a compromise to allow for DPS & Still have a backup defensive.
