### ISSUE TITLE
Vengeance priority in SimC is a work-in-progress

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#2164]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Vengeance DH still gets stuck recommending spamming Shear while at full Fury and other abilities available. Originally reported in https://github.com/Hekili/hekili/issues/2148

Tried resetting Hekili profile to default in case something was cached in the APL. Still happening.

### How to Reproduce

Play Vengeance DH with Hekili

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAgIIJJRAQCAFQSUOQkkkkkkEtkUSSSSoEJBAAAAA

### Snapshot

https://pastebin.com/S3h6NvDC

**Comment by Hekili** [comment]
I saw your comment on the other one; you don't have to open extra tickets.  I'm looking into this now.

**Comment by Hekili** [comment]
Would you like to provide a Raidbots sim of your character?  I think you'll find that the sim does the same thing.  I'm working to correct it, though.

**Comment by jmusick** [comment]
Sorry I commented on the first ticket but when it didn't re-open it I wasn't sure you'd get it.

**Comment by jmusick** [comment]
This is the raidbots sim: https://www.raidbots.com/simbot/report/2isuzmLXZbxSnutPMrmaGQ

**Comment by xClow** [comment]
Hey Hekili, I've been experiencing the same thing but am not good enough at veng to know what's wrong.

https://pastebin.com/3xrAT4Py
https://pastebin.com/V9xCzyTN - different enemies + more enemies
https://pastebin.com/L1syaPVT - different different + even more enemies

This is 3 different times where it's suggesting 2 glaive tosses instead of cooldowns like Fel Devistation, Soul Carver etc and im not sure why.

Hope this helps!

-Edited with better snapshots and better explanation.

**Comment by Hekili** [comment]
@xClow Thanks for more information. Go ahead and sim your character on Raidbots and link that as well. That helps us to see if it's what the sim would do or if it's an issue with the addon's translation of the sim profile. Thanks!

**Comment by biehlieh** [comment]
Hey, sorry i can't provide any data at the moment, but i can confirm that there are no suggestions for the following abilities:

- Fel Devastation
- Immolation Armor
- Infernal Strike
- Soul Carver (this shows up very very rarely though!)

Plus there is no suggestion for Soul Cleave on AOE, while suggesting double glaive toss.

It might be connected to the number of Frailty debuffs, but this is just a shot in the dark.
I might edit this comment once i can provide data.
And btw, once i updated to the version with the faulty suggestions, i could not restore the APL to a working state by using an older version of your addon.

edit:  https://pastebin.com/ZNnd8B4P   sim will take a while

edit2: https://pastebin.com/bXRS1Rmj  this is the sim

**Comment by Hekili** [comment]
> [pastebin.com/ZNnd8B4P](https://pastebin.com/ZNnd8B4P)

This isn't a snapshot.

**Comment by biehlieh** [comment]
Oh, very sorry!

This should be the AOE Snapshot: https://pastebin.com/2diDkw5P
This the Singletarget Snapshot: https://pastebin.com/7tJb9HDy

Both of them use an opener, i probably would not agree with. I'd be using Immolation aura or maybe Sigil of Flame to generate resource and then very soon i would be using fel devastation, then fiery brand and/or Fracture depending on resource and souls and then spend resource with Soul Cleave. 

Now Snapshots at full resource or close to it:

https://pastebin.com/d1ZfFgtc (ST, no suggestion for Immolation aura or Fel Deva)
https://pastebin.com/GbF0B1BC (AOE, same)

If i can provide further information, let me know!

**Comment by Hekili** [comment]
> edit2: [pastebin.com/bXRS1Rmj](https://pastebin.com/bXRS1Rmj) this is the sim

This should be a Raidbots link.

Are you using the default priorities that come with the addon?  Can you provide your talent strings?  Thanks.

**Comment by biehlieh** [comment]
> > edit2: [pastebin.com/bXRS1Rmj](https://pastebin.com/bXRS1Rmj) this is the sim
> 
> This should be a Raidbots link.

https://www.raidbots.com/simbot/report/akcZZWGBJbvoT7TmxM8GDq  -my error, sorry again.

> 
> Are you using the default priorities that come with the addon? Can you provide your talent strings? Thanks.


Yes, i am using the default priorities - last time i played was on wednesday evening, where everything was fine. Then i had to leave from thursday until now. I updated my addons including hekili, which has lead to the current state.
My talent strings are the following, whis is pretty much the standard m+ build: 

BUkACnvaHJn8GSPD6tpaeczPTBAgIIJJRAQCQSJBJR7ARiEJhEtkUSSSSoEJBAAAAA

**Comment by Hekili** [comment]
When you look at the Sample Ability Log in the Raidbots link, does its usage of Throw Glaive seem significantly different from what you're explaining?

**Comment by biehlieh** [comment]
This is a good question you brought up, since it made me look at the sample ability log. 
My first sim was pure single target - which seems to be quite fine on simulationcraft. There are Casts of infernal armor, fel deva etc., so this should be correct.
The second sim though was with 4 bosses: https://www.raidbots.com/simbot/report/gcFuwAD2faBXTiMWLCV33e and i could see that the ability log must definitely be wrong on the side of simulationcraft.org! In the Ability log, there is a very long time window, where throw glaive is suggested (from 00:35 to 1:14), which definitely absolutely can not be correct. The rotation starts to look correct again after 2:25, where it starts suggesting fel deva, infernal armor etc.
I hope this helps!

**Comment by biehlieh** [comment]
Hey, just a very quick update: i have asked in the DH Discord and they confirmed, that the APL on simcraft is wrong and is being worked on atm.

**Comment by biehlieh** [comment]
Hey, another udpate: according to the DH discord, the aoe sim should be working again.

**Comment by Hekili** [comment]
> Hey, another udpate: according to the DH discord, the aoe sim should be working again.

Have you resimmed yourself since then?  Want to provide a link?

**Comment by biehlieh** [comment]
Yes i have just now, here is the link: https://www.raidbots.com/simbot/report/pnffLnyWnGsXnjij6tahjs

I still felt like it is somewhat off, but i cant really put my finger on what it is. It feels like it is still suggesting throw glaive a bit too often.

The suggestion for The Hunt is coming too late compared to the sample ability log and i still have instances where i get a suggestion for double throw glaive in a row. Will send a snapshot soon, once i have replicated it. 
Edit: The Suggestion for The Hunt seemed to work just fine on some other tries @ target dummies.

**Comment by biehlieh** [comment]
This is one example of double throw glaive: https://pastebin.com/TMQZV80z

Also, and i dont know how to post a snapshot concerning this topic: i do not get any suggestion for soul cleave on aoe, which should definitely happen.
Same goes for Fiery Brand after the initial usage.

**Comment by Electrocudead** [comment]
Does anyone have a link to where I could download previous profiles? I'd really like to just go back to about a week ago for right now for veng.
