### ISSUE TITLE
Prot warrior Defensive CoolDowns

### ISSUE THREAD

**Issue by ivanbalvan** [Hekili/hekili#2165]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When I first got the addon, I use to get recomendation for defensive cooldowns like Shield Wall, Last Stand, Rallying Cry. Those no longer get recommended for some reason. However I still get Ignore Pain and Shield block. I have tried resetting the addon, resetting the profile. Nothing seems to help.

Thank you in advance! 

### How to Reproduce

Play as Prot warrior, and start losing health to a point where you need a defensive cooldown

### Talent Loadout

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQSLpkkkSBRgAJSUSSACkkQLkkgAEJAAAAAAAQEAAKlGA

### Snapshot

https://pastebin.com/0NKxLqJV

### Contact Information

Schwifty#0816   <Discord ID

**Comment by Hekili** [comment]
Please make use of the settings in /hekili > Protection related to your damage mitigation tools.

**Comment by ivanbalvan** [comment]
I did change those settings, numerous times. I've tried scaling it all the way up, as well as all the way down. I can show u a screen shot of my settings. Health percentage requirements are around 65%. Also Last stand doesnt work even if I check to use it offensively
