### ISSUE TITLE
(Survival hunter) When specced into an active use serpent sting it never appears in the priority queue

### ISSUE THREAD

**Issue by daverv3** [Hekili/hekili#2168]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Serpent sting never appears in the priority queue for survival when you are a spec that is designed to cast it actively, as attached below. 
After testing I also attempted to add it in manually through the action list which also did not work
Any help would be greatly appreciated!
Cheers,
D

### How to Reproduce

1. Enter game as survival hunter
2. Spec into serpent sting and not into Viper's Venom (e.g. B8PAIlFMjeNhnEouGfV8Ij2uS5ABahEABBJkkWSISkkkSSAAAAAAkEKNpoJkEIhEKAAAAAC)
3. Do any single or cleave target combat - serpent sting never comes up as a suggestion in the priority queue regardless of whether it is on a target or not

### Talent Loadout

B8PAIlFMjeNhnEouGfV8Ij2uS5ABahEABBJkkWSISkkkSSAAAAAAkEKNpoJkEIhEKAAAAAC

### Snapshot

https://pastebin.com/ZDQyDjdd

**Comment by Hekili** [comment]
This should be resolved shortly.
