### ISSUE TITLE
Prot warrior Defensive CoolDowns #2165

### ISSUE THREAD

**Issue by ivanbalvan** [Hekili/hekili#2169]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Repost of the issue, since it was wrongfully closed as complete. You recommended i adjust the settings related to the damage mitigation. I have done that numerous times trying all kinds of combos. Upon further research I was able to rectify the issue with Shield Wall not being recommended. It was due to the rotation looking for a certain talent to be enabled, which I do not have. Same thing with Last Stand. However Rallying Cry is not even included in the spell rotation. Can you please have a closer look at this issue and not dismiss it right away. 

"BEGINING OF THE OLD REPORT"
When I first got the addon, I use to get recomendation for defensive cooldowns like Shield Wall, Last Stand, Rallying Cry. Those no longer get recommended for some reason. However I still get Ignore Pain and Shield block. I have tried resetting the addon, resetting the profile. Nothing seems to help.

Thank you in advance!

### How to Reproduce

Play as Prot warrior, and start losing health to a point where you need a defensive cooldown

### Talent Loadout

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQSLpkkkSBRgAJSUSSACkkQLkkgAEJAAAAAAAQEAAKlGA

### Snapshot

https://pastebin.com/0NKxLqJV

### Contact Information

Schwifty#0816 <Discord ID

**Comment by Hekili** [comment]
There's nothing preventing you from commenting on the closed ticket; opening a new one is not necessary.

> Upon further research I was able to rectify the issue with Shield Wall not being recommended. It was due to the rotation looking for a certain talent to be enabled, which I do not have. Same thing with Last Stand. However Rallying Cry is not even included in the spell rotation. Can you please have a closer look at this issue and not dismiss it right away.

Do you want to be more specific about the talents?  Thanks!

**Comment by ivanbalvan** [comment]
talent.immovable_object.enabled 
but upon further consideration I think that is for offensive usage. 
That is why Rallying Cry is not in there because it doesnt have an offensive purpose. 
I just deleted my WTF folder, deleted the addon folder, Then I install only the latest version of hekili. Loged on my warrior, changed the settings to Shield wall Damage requirement to 10 and health percentage to 95, Made sure the defensive toggle is enabled, And the addon did not recommend any off the defensive cooldowns, However it is still recommending Shield block and Ignore pain. I can toggle the Shield block and Ignore pain recommendation with the defensive toggle in the settings.  I have a feeling the issues lies in the Defensive Action list, and it might of been broken in one of the updates. I do not know how to access the Defensive action list. I can see the Default Action list, Aoe, generic  and precombat.

**Comment by ivanbalvan** [comment]
I was just testing the issue some more and noticed that the addon also never recommends Impeding victory. Now i have a Feeling that the addon is not detecting my health properly perhaps? Im avail on discord if u want to use me for testing purposes incase u dont have a warrior.

**Comment by ivanbalvan** [comment]
Ok I was able to get it to work by downgrading the addon to version [v10.0.2-1.9.1](https://github.com/Hekili/hekili/tree/v10.0.2-1.9.1) (2022-11-30) and deleting my WTF folder. Now the addon recommends all the defensive cooldowns as well as Impeding Victory.  I then decided to upgrade back to the newest version, and the it broke again. I will stay on the older version while u resolve the issue. If i can help in any way let me know! cheers!

**Comment by Hekili** [comment]
All of that testing you were doing was also the time to take snapshots to see why you were/weren't seeing what you expected.

I've made some Protection changes that may help further investigate, but this has become quite the laundry list of topics without snapshots for each specific item of concern.  Help me by organizing your thoughts a bit more, with "here is a snapshot taken when I expected to see X (because Y) but I saw A instead."

> I was just testing the issue some more and noticed that the addon also never recommends Impeding victory.

No, Impending Victory isn't in the priority.  You can examine the priority in /hekili >Priorities or see this information in the snapshots you generate.  It looks like it's not worth adding from a damage standpoint, but this starts to get you into "make a custom priority territory" (you can look at the FAQ section of the wiki if you're interested in that).

> I will stay on the older version while u resolve the issue.

Without snapshots associated with your specific issues of concern, there's not much else I'll be doing about this ticket.  It may be resolved to your satisfaction with the updates I'll post later today.  Thanks!

**Comment by ivanbalvan** [comment]
So if I understand correctly. You telling me that Between the old version of the addon and the new version of the addon there was Intentional changes to remove Impeding Victory, Shield Wall, Rallying Cry and Last stand. Because that is what my testing is suggesting. Since I am never being recommended those abilities on the new version.  I agree that it is not worth adding Impeding Victory from a damage stand point but it is definitely worth adding it from the defensive stand point. I still think you have a bug in the new version that does not integrate Defensive abilities properly into the rotation. However I am very satisfied with this old version, so as far as I am concerned its all good!

**Comment by Hekili** [comment]
> You telling me that Between the old version of the addon and the new version of the addon there was Intentional changes to remove Impeding Victory, Shield Wall, Rallying Cry and Last stand. Because that is what my testing is suggesting.

No, that's not what I said.  Glad the new version is all good, though.  Thanks!

**Comment by ivanbalvan** [comment]
what ever u did for the new update, fixed the issue. thank you very much
