### ISSUE TITLE
Auto Show/Hide the Displays in Combat or on Hostile/Neutral Target Selected 

### ISSUE THREAD

**Issue by rvnlord** [Hekili/hekili#217]
I know that github is not the best place to say this but it would be really helpful if you added a feature to toggle auto show/hide displays during combat or better yet - on selecting attackable target (hostile or neutral). Your addon is brilliant, thanks for the effort.

**Comment by Hekili** [comment]
Have you checked out /hekili > Displays > (pick a display ) > Visibility ?

Either those options or the ones that appear when you check Advanced should cover that.

**Comment by rvnlord** [comment]
https://i.imgur.com/kbxKEnd.png
