### ISSUE TITLE
Bad ranged recommendations for survival

### ISSUE THREAD

**Issue by ReilerA** [Hekili/hekili#2172]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my survival spec for ranged dps when I don't have aspect of the eagle ready to press it makes wrong recommendations. It tells me to press mongoose or  flanking strike when those abilities are out of range. Instead it should be recommending bombs, explosive shot, death chakrams, kill command, killshot, and the last ability it should recommend is serpent sting if I have nothing else to press for ranged dmg as surv.

### How to Reproduce

1.Enter game as survival
2.Go to pvp target dummy in dragonflight
3.Use these talents B8PAIlFMjeNhnEouGfV8Ij2uS5ABahkAEEkQSkEhERSaRIAAAAAQSoUkimQSgESoAAAAAI
4.Follow the rotation it recommends from ranged press aspect of the eagle, when you press coordinated assault it will charge you
5.Go back to range and when you don't have aspect of the eagle it will recommend buttons you can't press

### Talent Loadout

B8PAIlFMjeNhnEouGfV8Ij2uS5ABahkAEEkQSkEhERSaRIAAAAAQSoUkimQSgESoAAAAAI

### Snapshot

https://pastebin.com/nD62S8fT

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vKEVihCG7quy7NjfqUDzdP

### Contact Information

Reiler#0101 discord

**Comment by ReilerA** [comment]
Forgot to mention this when your rannged and even have aspect of the eagle you still can't press flanking strike if farther away than 18 yds it shouldn't recommend it unless in range

**Comment by Hekili** [comment]
No, the addon isn't intended to handle that sort of fight choreography.  Otherwise, you could stand out of melee forever and it could give you suboptimal recommendations the whole time.  You're a melee; you should get in melee range whenever possible.  If you can't get in melee, it's okay to push other buttons than what the addon is recommending.  That's always the case.
