### ISSUE TITLE
Empowered Spells and SpellFlash

### ISSUE THREAD

**Issue by Yukio83** [Hekili/hekili#2173]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Hi, I'm using Hekili SpellFlash feature with the "Hide Display" option. 
I've noticed that the empowered spells "power" is not shown on the action bar or anywhere else. The only way to see it seems to be by using the normal Hekili display.
Really sorry if this has been discussed before.

**Comment by Hekili** [comment]
That's a SpellFlash limitation; there's nothing for the addon to do with this.
