### ISSUE TITLE
Arcane mage - Snapshotting

### ISSUE THREAD

**Issue by iNupidstoob** [Hekili/hekili#2175]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I am using single target only on a target dummy and during combat I guess the addon fails to make a recommendation and creates a snapshot.

### How to Reproduce

Get into combat, follow the rotation, snapshot will happen. I am not well-known with the spec so I'm not entirely sure where the problem is.

### Talent Loadout

B4DAHVkVsxxZrVqBmAzlSR2f7TCIplIikUASLhISikIhEaJItkAAAAAAAAAAAAkkkkESSSCA

### Snapshot

https://pastebin.com/raw/wxr7YFFw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dR9QjeJKLNyRU9iCzMQaaV

### Contact Information

Nupidstoob#8835

**Comment by iNupidstoob** [comment]
Another issue I've noticed in the opener is that the recommendation after Touch of the Magi originally is Arcane Blast, but after casting Touch of the Magi it instantly changes to Arcane Missiles, you can see it here at this timestamp: https://youtu.be/TqQbPHj077M?t=71

Not sure if that is intended, it just makes me a bit confused with what is actually meant to be cast next.

**Comment by Hekili** [comment]
This is a very strange snapshot; it attempts to process an action list but then just doesn't.  I'll investigate.  I assume you're really using the default priorities without edits?

**Comment by iNupidstoob** [comment]
Hi Hekili,  yeah it's the default rotation. Let me know if I can do anything to help troubleshoot this more.

I just had another snapshot at the start of a fight; https://pastebin.com/raw/DLtw8TXD

**Comment by Hekili** [comment]
Your snapshots seem to have abilities disabled in them, so it's impossible for me to interpret them.  If this is a current issue (in 2.0.13 or later), please go ahead and respond or open a new ticket with new snapshot(s).
