### ISSUE TITLE
Rogue - Hidden Oppurtinity recent optimization

### ISSUE THREAD

**Issue by Soybeanpaste** [Hekili/hekili#2176]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For Hidden Oppurtunity builds:
Opportunity should be consumed at any CP instead of the current "3cp or below" rule, as long as the finisher rule is not already met.

This means in the cases where you are at 4cp or higher with Opportunity active and not Audacity, Opportunity should be consumed right then and there, instead of waiting until at 3cp or below. This is more common for the Ghostly Strike version of the build. Yes the condition will overcap a lot of combo points -- the FTH Audacity loop is so strong it's throwing CP efficiency out the window.

The finisher rule also changes because of this rule -- HO builds finish at -1 if any Opportunity stacks are active.

Expected gain: 0.2 - 0.8%

### How to Reproduce

Changes in rotation, not sure what to write here

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRiIJJJhAAAAAAAEJJaSJJgEKBAAAA

### Snapshot

Outlaw; Primary - Dispatch(0.00), Ambush(1.00), Blade Rush(2.00)

### Contact Information

Mywiddlepony#3592

**Comment by Hekili** [comment]
> Snapshot
> 
> Outlaw; Primary - Dispatch(0.00), Ambush(1.00), Blade Rush(2.00)

This is not a snapshot.

> Raidbots Sim Report (Link)
> 
> No response

Your sim comparison of the changes you're proposing should go here.

> Expected gain: 0.2 - 0.8%

Based on what?

> This means in the cases where you are at 4cp or higher with Opportunity active and not Audacity, Opportunity should be consumed right then and there, instead of waiting until at 3cp or below. This is more common for the Ghostly Strike version of the build. Yes the condition will overcap a lot of combo points -- the FTH Audacity loop is so strong it's throwing CP efficiency out the window.

Are you expecting that SimulationCraft won't be updated to reflect this?  Why or why not?
