### ISSUE TITLE
Automatic snapshot when user-defined condition is met

### ISSUE THREAD

**Issue by shawn571** [Hekili/hekili#2177]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

All

### Feature Request

I think it would be useful to let users define conditions which would automatically generate a snapshot for troubleshooting. For example, auto-snapshot when something procs or when a specific recommendation fails

### Additional Information

As an example, when I get a lunar eclipse proc (WOTLK) it incorrectly calculates how many Starfires I can get in before the buff expires. So it will stop recommending Starfires when I have enough time left on the buff to get 2 or even 3 more in. Looking at the snapshots myself, for some reason it's thinking the buff remaining time is less than the cast time, and the buff remaining time looks to be off. For example, I'll have 5 or 6 seconds left of the buff when Starfires stop being recommended, but in the snapshot I generated it says I have just over 2 seconds left which is less than the Starfire cast time. Snapshot looks like the recommendations are correct, they just don't match the actual in-game conditions.

If I could auto-snapshot when I get a lunar eclipse proc, it would allow me to confirm that it's correctly saying I have 15 seconds remaining on the buff before it expires for example. Also in other cases, being able to auto-snapshot on specific conditions would remove a user's reaction time to take a manual snapshot if something needs to be caught quickly.

**Comment by Hekili** [comment]
This isn't something I plan to implement.  You can tap your Pause/Snapshot keybind at that time to generate a snapshot.
