### ISSUE TITLE
Rogue - Assassination - Opening rotation seems to be off from what simc is doing.

### ISSUE THREAD

**Issue by firefang03** [Hekili/hekili#2179]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Simc shows the opener as garrote, slice n dice, garrote, serrated bone spike, rupture, echoing reprimand, rupture, exsanguinate, death mark (then use trinkets)

Hekili is never doing that, and typically doesnt even apply bone spike before exsanguinate. It does garrote, snd, garrote, thistle tea

### How to Reproduce

1. Try single target rotation with all cds

### Talent Loadout

BMQAOB/7AZ//CwQOf4fPMswHVLNJSCiElEAAAAAAAJAkkAAAAAAAQQaOQJJkkkkWIikQiEJJB

### Snapshot

https://pastebin.com/Fcn7N4fP

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8u7KgDWfQy1RB4zXRFu6vL

**Comment by firefang03** [comment]
Simming 50k, and doing 40k

**Comment by baruchvlz** [comment]
> Simc shows the opener as garrote, slice n dice, garrote, serrated bone spike, rupture, echoing reprimand, rupture, exsanguinate, death mark (then use trinkets)

Not sure where you're running simc, but you can't garrote -> snd -> garrote unless you wait for the CD.

My sim opener is

1. garrote
2. serrated
3. snd
4. mut
5. mut
6. rupture
7. cds

**Comment by vond82** [comment]
Yes you can, depending on talents.

**Comment by baruchvlz** [comment]
> Yes you can, depending on talents.

Can you elaborate? Which talent? Cause I don't see anything like that in the talent build OP posted. Genuinely curious.

**Comment by firefang03** [comment]
It's improved garrote in the assass tree that allows you to cast multiple garrotes after stealth.

The optimal opener is https://imgur.com/RCxiS6c

Which hekili currently has it as Garrote > Channel Trinket > Garrote > Snd > Serrated > Mut > Rupture> ER > Ruputure >

Without a  channel trinket Hekili recommends Garrote >  Snd > Garrote > Garrote > Thistle Tea > Exsanguinate > Deathmark

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/209557595-78a7a8d7-5a12-43ff-82a4-98c485fd024c.png)

In the provided snapshot, the "opener" doesn't go as expected because you're not starting from an "opener" state.  Your Exsanguinate is on cooldown for another 99.14 seconds, so this is treated as though you're going pack-to-pack.  Under the circumstances, Echoing Reprimand's conditions are met specifically because setting up for an Exsanguinate that's not going to occur for 2 full Echoing Reprimand cooldowns would be very, very wasteful.

```
28.  echoing_reprimand ( cds - 12 )
The action (echoing_reprimand) is usable at (1.00 + 0.00) with cost of 10 energy (have 137).
 - the action is ready before the current recommendation (at +0.00 vs. +0.71).
List ( cds ) called from ( Assassination:default:6 ) would PASS at 0.00.
 - this entry's criteria PASSES: talent.exsanguinate.enabled[true] & talent.resounding_clarity.enabled[true] & ( variable.exsanguinate_condition[false] & combo_points.current[3.00] <= 2 & cooldown.exsanguinate.remains[99.14] <= 2 & ! dot.garrote.refreshable[false] & dot.rupture.remains[0.00] > 9.6 | cooldown.exsanguinate.remains[99.14] > 40 )
Action chosen:  echoing_reprimand at 0.00!
```
