### ISSUE TITLE
Not showing up with Hunter

### ISSUE THREAD

**Issue by Britten42** [Hekili/hekili#218]
Good afternoon. I am using this addon and have used it fine with all other classes that I have tried it on. I have tried to use it on a Hunter but it just isnt showing up. I have checked the visibilty settings etc and all are ok. I thought it might be because my Hunter is a level 5 but this didnt affect any other class that I have played on.

**Comment by Hekili** [comment]
The addon does not support low levels.  Abilities change dramatically as you level, some changing spell ID, buffs/debuffs they apply or consume, etc.
