### ISSUE TITLE
Queue skills not showing

### ISSUE THREAD

**Issue by VOLCA03** [Hekili/hekili#2180]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

My "queue" skills are not showing.

### How to Reproduce

N/A

### Player Information (Link)

```Text
build: v10.0.2-2.0.8c
level: 70 (70)
class: DEMONHUNTER
spec: havoc

talents: accelerating_blade
    any_means_necessary = 1/1
    blazing_path = 1/1
    bouncing_glaives = 1/1
    burning_wound = 1/1
    chaos_nova = 1/1
    chaotic_transformation = 1/1
    charred_warblades = 1/1
    collective_anguish = 1/1
    consume_magic = 1/1
    critical_chaos = 2/2
    dancing_with_fate = 2/2
    darkness = 1/1
    demon_blades = 1/1
    demonic = 1/1
    demonic_appetite = 1/1
    erratic_felheart = 2/2
    essence_break = 1/1
    eye_beam = 1/1
    felblade = 1/1
    felfire_heart = 1/1
    first_blood = 1/1
    fodder_to_the_flame = 1/1
    growing_inferno = 2/2
    illidari_knowledge = 2/2
    imprison = 1/1
    improved_chaos_strike = 1/1
    improved_disrupt = 1/1
    initiative = 1/1
    internal_struggle = 1/1
    know_your_enemy = 2/2
    looks_can_kill = 1/1
    master_of_the_glaive = 1/1
    misery_in_defeat = 1/1
    momentum = 1/1
    precise_sigils = 1/1
    pursuit = 1/1
    ragefire = 1/1
    rush_of_chaos = 1/1
    sigil_of_flame = 1/1
    sigil_of_misery = 1/1
    soul_rending = 2/2
    soulrend = 2/2
    tactical_retreat = 1/1
    the_hunt = 1/1
    trail_of_ruin = 1/1
    unbound_chaos = 2/2
    unleashed_power = 1/1
    unnatural_malice = 1/1
    unrestrained_fury = 2/2
    vengeful_retreat = 1/1
    will_of_the_illidari = 1/2

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: algethar_puzzle_box = 1
    irideus_fragment = 1

gear: algethar_puzzle_box = 1
    blightweavers_clutches = 1
    dragonflayers_seething_shortsword = 1
    eternal_sentrys_ring = 1
    fireproof_drape = 1
    invaders_firestorm_chestguard = 1
    irideus_fragment = 1
    ottuk_hide_bindings = 1
    ottuk_hide_breeches = 1
    ottuk_hide_epaulets = 1
    ottuk_hide_sash = 1
    refractions_edge = 1
    scalebane_signet = 1
    treads_of_restored_order = 1
    tuskarr_bone_necklace = 1
    vision_of_foreshadowed_ends = 1

legendaries: none

itemIDs: 191994, 191995, 191996, 192014, 192024, 193646, 193661, 193666, 193701, 193739, 193743, 193763, 193764, 193768, 193800, 193804

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 7
    nameplates = true
    noFeignedCooldown = false
    package = Havoc
    petbased = false
    potion = phantom_fire
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    demon_blades_acknowledged = false
    recommend_movement = true
    unbound_movement = false

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    algethar_puzzle_box = S1  [05]
    annihilation        = E   [01]
    arcane_torrent      = SD  [05]
    blade_dance         = R   [01]
    blur                = 2   [06]
    chaos_nova          = SE  [01]
    chaos_strike        = E   [01]
    darkness            = 3   [06]
    death_sweep         = R   [01]
    disrupt             = SM4 [05], 1   [06]
    essence_break       = C   [01]
    eye_beam            = F   [01]
    fel_rush            = M4  [06]
    felblade            = Q   [01]
    immolation_aura     = X   [01]
    imprison            = SM5 [05]
    irideus_fragment    = S2  [05]
    metamorphosis       = SF  [01]
    potion              = S3  [05]
    sigil_of_flame      = SX  [01]
    spectral_sight      =
    the_hunt            = SQ  [01]
    throw_glaive        = SC  [01]
    torment             =
    vengeful_retreat    = M5  [06]

warnings: none
```

### Error Messages (Link)

```Text
N/A
```

**Comment by VOLCA03** [comment]
![image](https://user-images.githubusercontent.com/121106951/208678689-e2800ee3-d484-4024-ab62-c4acd5e4548e.png)

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
I will also need your talent export string.

**Comment by VOLCA03** [comment]
Thank you for the quick response.
Here you go:

https://pastebin.com/GaZsaQUr

and for the talent export string: BEkACnvaHJn8GSPD6tpaeczPTRSSSSIlg0SSEJSrFBAAAAAAQLJBHQKkElgIplEIRIB

**Comment by VOLCA03** [comment]
Note that it was working 1h ago .. I just went to lunch and cameback and this happend.

**Comment by Hekili** [comment]
Your snapshot shows multiple recommendations calculated. Can you confirm that when the snapshot was taken, you could not see the queued recommendations?

If so, please go to /Hekili > Displays > Primary and look at the settings on the first two tabs. Are the icon size or anchoring settings changed? You can screenshot them for me to look at here.

**Comment by VOLCA03** [comment]
Yes I couldn't see the queued recommendations. 
Yes I changes the Icon sizes of the Main and Queue icons.
The screenshots below:

![image](https://user-images.githubusercontent.com/121106951/208684941-b8538419-bb24-4942-a954-b4c6d05a2d90.png)
![image](https://user-images.githubusercontent.com/121106951/208685116-150405da-6a58-485e-8e1c-017f9fcacb8a.png)

but I changed it directly into 'Multiple', not Primary tab.

![image](https://user-images.githubusercontent.com/121106951/208685257-c26f860d-17e1-45c7-8cbc-5c27683aee3d.png)
![image](https://user-images.githubusercontent.com/121106951/208685317-edb4efc5-cf0b-45c6-af98-1d9a2d11e92f.png)

**Comment by Hekili** [comment]
The "Multiple" tab is for editing multiple displays at once (the ones checked at the top).  If the recommendations are being generated but not displayed, I have a hard time believing there aren't error messages available via BugSack and BugGrabber.  Is there another addon that might be trying to skin the addon and cause a problem?  If you disable all other addons, can you see all the recommendations?
