### ISSUE TITLE
Trinket: Bonemaw's Big Toe (110012) not shown

### ISSUE THREAD

**Issue by GigaToons** [Hekili/hekili#2183]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Hello! The trinket 'Bonemaw's Big Toe (ID 110012)' is not currently included in hekili. Any chance of getting this added would be greatly appreciated!

### Additional Information

You are absolutely awesome!!!!  And greatly appreciated for the work you do on this amazing add-on.

**Comment by Hekili** [comment]
Thanks, this will be in the next release.
