### ISSUE TITLE
Enhancement: Stormstrike used at high MSW despite set bonus

### ISSUE THREAD

**Issue by unmoved1** [Hekili/hekili#2184]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

so after getting 2 pieces of my raid set which gives stormstrike extra maelstorm weapon it is over generating maelstorm while i have the proc to cast

### How to Reproduce

my explanation is enough

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJpEJgkEikkQJhAAAAAAAAAAAAAQJCRIBFBkUSSSJwBQkEA

### Snapshot

https://pastebin.com/3vnSbQcQ

### Contact Information

Unmoved#9238

**Comment by Hekili** [comment]
This is the same deal as the other ticket (see also your post in the patron forum).  I'll need a sim for comparison, but it's very likely that the opportunity cost of leaving Stormstrike off cooldown to avoid wasting a few MSW stacks was tested and found to not be worthwhile on average.

I'm willing to run a few comparison sims if you provide Raidbots sims of your character (one in Patchwerk with 1 boss, one in Hectic Add Cleave).  Thanks!

**Comment by Hekili** [comment]
Replaced by #2191
