### ISSUE TITLE
Enhancement: Primordial Wave used despite having Maelstrom Weapon stacks

### ISSUE THREAD

**Issue by unmoved1** [Hekili/hekili#2185]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

while maelstorm weapon proc is up it is still asking me to use primodial wave, why not use chain lightning, bolt, lava burst, then prio primodial wave after that.

### How to Reproduce

explained

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJpEJgkEikkQJhAAAAAAAAAAAAAQJCRIBFBkUSSSJwBQkEA

### Snapshot

https://pastebin.com/aMjF4aXJ

### Contact Information

Unmoved#9238

**Comment by Hekili** [comment]
Could you please add a sim of your character to compare addon behavior to sim behavior?  It will also help for testing changes to the priority that align with your character build.

**Comment by Zaxx-is** [comment]
I can confirm that it recommends using Primordial Wave (with Primal Maelstrom talented) even if you have 5+ MS stacks. Maybe it's conflicting with the Overflowing Maelstrom talent which would recommend spenders only at 10 stacks of maelstrom ? Not sure about this, but just an idea :-)

**Comment by Hekili** [comment]
This will require comparison sims to determine it's worthwhile.  Opportunity costs are not always transparent.  To avoid using Primordial Wave when you will waste some Maelstrom generation means delaying its usage or trying to consume Maelstrom in the last GCD or two before it comes off cooldown.  Without comparison sims, we don't know that doing so is worthwhile or if it's just something that sounds correct when feelycrafting.
