### ISSUE TITLE
Allow Potions to be shown with the Cooldowns toggle when shown separately

### ISSUE THREAD

**Issue by dcstaley** [Hekili/hekili#2186]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

With cooldowns shown separately and potions toggled on, I'd like the ability to include potions in cooldowns (instead of the main rotation).  You can see my current setup in the attached screenshot, I'd be looking for the potion to be in the right grouping instead of the left.

![image](https://user-images.githubusercontent.com/5664428/209014304-827368ef-d099-4ee5-8627-4c88af3df5df.png)

**Comment by Hekili** [comment]
This is a good idea.

**Comment by Nakah90** [comment]
May potions have its own module ? I'd like to have, if possible of course,  cooldowns / Potions separated because sometimes I have to keep my potions for later use while using CDs.

Thanks

**Comment by Hekili** [comment]
> May potions have its own module ? 

Potions already has its own toggle.  Separate displays are moderately expensive, so I'm not inclined to add yet another one.  I'm trying to think about the best way to handle these overlapping toggles (i.e., how the Essences/Covenants toggle could be overridden by Cooldowns).

If you're wanting to know your potion cooldown but you don't want the addon to be telling you when to prioritize your potion, that's more of a WeakAuras type issue IMO.

**Comment by Nakah90** [comment]
Ok don't worry. Thanks for answering, I'm just gonna use a WA for potions CD then.

Keep up the good work, Hekili.

**Comment by Mxktoom** [comment]
Hey im facing the same issue has this been resolved?
