### ISSUE TITLE
Druid still not usable

### ISSUE THREAD

**Issue by Amenophyckxs** [Hekili/hekili#2188]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

First of all, I looked for an open ticket, but could not find one. 
I still do not get the correct keybinds to show for Druid (all my other classes work perfectly)
I saw a while back in another thread that I could manually adjust the keybinds that are shown under the 'ability' section in the addon settings so I know this is a known issue. However, this only works for spells or keys that use no modifier key. 
As I use a lot of modifiers for my spells (alt, ctrl, shift, or combos of those) this makes this addon unusable for druid specifically (for me)
Unless there is a fix for this I am unaware of, I would appreciate it if this would be looked at.

Thanks in advance and appreciate the work so far, this addon is great!

### How to Reproduce

playing a druid

### Player Information (Link)

```Text
build: v10.0.2-2.0.8c
level: 46 (46)
class: DRUID
spec: balance

talents: astral_influence
    celestial_alignment = 1/1
    eclipse = 1/1
    improved_barkskin = 1/1
    improved_sunfire = 1/1
    moonkin_form = 1/1
    natural_recovery = 2/2
    natures_balance = 1/1
    natures_grace = 1/1
    nurturing_instinct = 3/3
    orbit_breaker = 1/1
    primordial_arcanic_pulsar = 1/1
    rejuvenation = 1/1
    remove_corruption = 1/1
    shooting_stars = 1/1
    solar_beam = 1/1
    solstice = 2/2
    soothe = 1/1
    soul_of_the_forest = 1/1
    stampeding_roar = 1/1
    starfall = 1/1
    starfire = 1/1
    starsurge = 1/1
    stellar_flare = 1/1
    sunfire = 1/1
    swiftmend = 1/1
    tiger_dash = 1/1
    twin_moons = 1/1
    typhoon = 1/1
    umbral_embrace = 2/2
    umbral_intensity = 2/2
    wild_growth = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: ancient_bloodmoon_cloak = 1
    apocryhphic_bindings = 1
    boots_of_infinite_possibility = 1
    discerning_eye_of_the_beast = 1
    eternal_will_of_the_martyr = 1
    gloves_of_nurtured_truth = 1
    grand_staff_of_jordan = 1
    iridium_inlaid_band = 1
    lasting_feralheart_spaulders = 1
    reinforced_elastic_band = 1
    ring_of_the_quenched_inferno = 1
    stained_shadowcraft_cap = 1
    stained_shadowcraft_pants = 1
    stained_shadowcraft_tunic = 1

legendaries: none

itemIDs: 117572, 122248, 122254, 122262, 122362, 122368, 122377, 122383, 122668, 37388, 57266, 57279, 57331, 57382

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    delay_berserking = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true [overridden]
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    barkskin              = AC= [05]
    bear_form             = C6  [02]
    cat_form              = S8  [03], CS2 [07], ACS2[08], 2   [09], 2   [10]
    celestial_alignment   = S=  [03], CS= [07], 7   [09], 7   [10]
    entangling_roots      = AC9 [05]
    frenzied_regeneration =
    growl                 = C8  [02]
    hibernate             = S5  [03]
    innervate             = C5  [02]
    mangle                = C7  [02]
    mark_of_the_wild      = ACS3[08]
    moonfire              = 6   [01], A1  [04], AS2 [06], CS3 [07], 3   [09], 3   [10]
    moonkin_form          = AS4 [06], CS4 [07], ACS4[08]
    prowl                 = S3  [03]
    regrowth              = A4  [04], =   [09], =   [10]
    rejuvenation          = A6  [04]
    remove_corruption     = C4  [02]
    sea_giants_tidestone  = S-  [03]
    shred                 = S9  [03]
    solar_beam            = S0  [03], AC- [05]
    soothe                = S7  [03]
    stampeding_roar       = CS5 [07], 2   [09]
    starfall              = 9   [01], AS3 [06], 9   [09], 9   [10]
    starfire              = 2   [01], 5   [09], 5   [10]
    starsurge             = A3  [04], 4   [09], 4   [10]
    sunfire               = 3   [01], A2  [04], AS1 [06], CS6 [07], 6   [09], 6   [10]
    swiftmend             = A5  [04]
    tiger_dash            = 0   [01], CS0 [07], ACS0[08], 9   [09], 0   [10]
    travel_form           = =   [01], AS- [06], CS1 [07], ACS1[08], 1   [09], 1   [10]
    typhoon               = 8   [01]
    wild_charge           = -   [01], CS- [07], -   [09], -   [10]
    wild_growth           = A7  [04]
    wrath                 = 1   [01], 8   [09], 8   [10]

warnings: none
```

### Error Messages (Link)

```Text
no error
```

**Comment by Hekili** [comment]
> However, this only works for spells or keys that use no modifier key.
> As I use a lot of modifiers for my spells (alt, ctrl, shift, or combos of those) this makes this addon unusable for druid > specifically (for me)

No, you just type the text you want to see exactly as you want to see it.  If your binding is SHIFT-1, type `S1` or `s1` or `shift and one` if you're feeling saucy.

There's a huge gulf between "Druid still not usable" and "how do I set the keybind text for abilities with modifiers" though, as far as your title is concerned.

**Comment by xClow** [comment]
Noticed this happening too when I started trying out feral, it doesn't do it on Guardian. By default it just shows incorrect keybinds on the primary/aoe/queue icons. I ended up doing what you told him to do and it's been fine.

Is there anything I can provide you to help the issue of it automatically showing incorrect keybinds though?

**Comment by Amenophyckxs** [comment]
Ah my bad, i just pressed shift and 1 (as an example) like how to set keybinds for stuff in wow settings. Did not know i had to write 'shift'.
Sorry for wasting your time!

**Comment by Hekili** [comment]
No problem.  It might make sense to auto-translate a pushed keybinding instead of allowing free text, but free text also affords some flexibility that people may be using.

**Comment by Hekili** [comment]
> Is there anything I can provide you to help the issue of it automatically showing incorrect keybinds though?

Nope.
