### ISSUE TITLE
healthstoneAutoMacro is polluting _G.Item

### ISSUE THREAD

**Issue by Dimmnn** [Hekili/hekili#2189]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When logging into the game I'm getting the chat box message to disable this addon because of too many errors. Below is the error I am getting.

### How to Reproduce

Deathknight playing unholy logging into the game

I have not done anything since lastnight when it was working perfectly fine then.

### Player Information (Link)

```Text
Will not open up when I type /hekili
```

### Error Messages (Link)

```Text
2418x Hekili/Events.lua:1529: attempt to call field 'callHook' (a nil value)
[string "@Hekili/Events.lua"]:1529: in function <Hekili/Events.lua:1527>
[string "@Hekili/Events.lua"]:1824: in function `handler'
[string "@Hekili/Events.lua"]:60: in function <Hekili/Events.lua:52>

Locals:
event = "COMBAT_LOG_EVENT_UNFILTERED"
timestamp = 1671733858.371000
subtype = "SPELL_AURA_APPLIED"
hideCaster = false
sourceGUID = "Player-3684-0DCB147E"
sourceName = "Unknown"
sourceFlags = 1297
sourceRaidFlags = 0
destGUID = "Player-3684-0DCB147E"
destName = "Unknown"
destFlags = 1297
destRaidFlags = 0
spellID = 2383
spellName = "Find Herbs"
school = 1
amount = "BUFF"
interrupt = nil
a = nil
b = nil
c = nil
d = nil
offhand = nil
multistrike = nil
(*temporary) = nil
(*temporary) = "COMBAT_LOG_EVENT_UNFILTERED"
(*temporary) = 1671733858.371000
(*temporary) = "SPELL_AURA_APPLIED"
(*temporary) = false
(*temporary) = "Player-3684-0DCB147E"
(*temporary) = "Unknown"
(*temporary) = 1297
(*temporary) = 0
(*temporary) = "Player-3684-0DCB147E"
(*temporary) = "Unknown"
(*temporary) = 1297
(*temporary) = 0
(*temporary) = 2383
(*temporary) = "Find Herbs"
(*temporary) = 1
(*temporary) = "BUFF"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call field 'callHook' (a nil value)"
ns = <table> {
 FindPlayerAuraByID = <function> defined @Hekili/Utils.lua:516
 specTemplate = <table> {
 }
 WipeCovenantCache = <function> defined @Hekili/Utils.lua:812
 IsTimer = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 forecastResources = <function> defined @Hekili/State.lua:1290
 frameProfile = <table> {
 }
 UnregisterUnitEvent = <function> defined @Hekili/Events.lua:220
 Localize = <table> {
 }
 debug = <table> {
 }
 GetTexString = <function> defined @Hekili/Utils.lua:852
 GetTimer = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 queue = <table> {
 }
 SetTimer = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 BigLibTimer6 = <table> {
 }
 castsAll = <table> {
 }
 cpuProfile = <table> {
 }
 GroupMembers = <function> defined @Hekili/Utils.lua:263
 spendResources = <function> defined @Hekili/State.lua:6585
 safeMax = <function> defined @Hekili/Utils.lua:243
 updateMinion = <function> defined @Hekili/Targets.lua:602
 safeAbs = <function> defined @Hekili/Utils.lua:255
 RegisterUnitEvent = <function> defined @Hekili/Events.lua:176
 CreateTable = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 RecycleTable = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 updateEssences = <function> defined @Hekili/Events.lua:571
 AddTexString = <function> defined @Hekili/Utils.lua:840
 actorHasDebuff = <function> defined @Hekili/Targets.lua:645
 StopEventHandler = <function> defined @Hekili/Events.lua:129
 SpaceOut = <function> defined @Hekili/Utils.lua:54
 getModifier = <function> defined @Hekili/Targets.lua:685
 roundUp = <function> defined @Hekili/Utils.lua:139
 ResourceRegenerates = <function> defined @Hekili/Constants.lua:95
 print = <function> defined @Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:8
 wipeDebuffs = <function> defined @Hekili/Targets.lua:638
 GetResourceInfo = <function> defined @Hekili/Constants.lua:73
 round = <function> defined @Hekili/Utils.lua:132
 GetResourceKey = <function> defined @Hekili/Constants.lua:83
 GetResourceID = <function> defined @Hekili/Constants.lua:78
 Audit = <function> defined @Hekili/Targets.lua:837
 updateGear = <function> defined @Hekili/Events.lua:672
 eliminateUnit = <function> defined @Hekili/Targets.lua:780
 castsOff = <table> {
 }
 FindStringInTooltip = <function> defined @
```

**Comment by orlith** [comment]
Got the same issue this evening

**Comment by TeaDoll-dev** [comment]
I am having the same issue on my rogue

**Comment by Hekili** [comment]
What is the first error in the BugSack/BugGrabber output?

**Comment by Dimmnn** [comment]
24x Hekili/Classes.lua:669: attempt to call method 'CreateFromItemID' (a nil value)
[string "@Hekili/Classes.lua"]:669: in function `RegisterAbility'
[string "@Hekili/Classes.lua"]:875: in function `RegisterAbilities'
[string "@Hekili/Classes.lua"]:2264: in main chunk

Locals:
self = <table> {
 totems = <table> {
 }
 talents = <table> {
 }
 itemAbilities = 2
 stateExprs = <table> {
 }
 auras = <table> {
 }
 gear = <table> {
 }
 RegisterAbility = <function> defined @Hekili/Classes.lua:570
 melee = false
 packs = <table> {
 }
 RegisterStateTable = <function> defined @Hekili/Classes.lua:406
 setBonuses = <table> {
 }
 RegisterTalents = <function> defined @Hekili/Classes.lua:218
 RegisterResource = <function> defined @Hekili/Classes.lua:141
 RegisterUnitEvent = <function> defined @Hekili/Classes.lua:899
 RegisterAbilities = <function> defined @Hekili/Classes.lua:873
 texture = "Interface\Addons\Hekili\Textures\LOGO-WHITE.blp"
 potions = <table> {
 }
 powers = <table> {
 }
 RegisterAuras = <function> defined @Hekili/Classes.lua:360
 pvptalents = <table> {
 }
 dual_cast = <table> {
 }
 pseudoAuras = 27
 RegisterCycle = <function> defined @Hekili/Classes.lua:909
 RegisterPower = <function> defined @Hekili/Classes.lua:367
 phases = <table> {
 }
 pendingItemSpells = <table> {
 }
 RegisterOptions = <function> defined @Hekili/Classes.lua:889
 interrupts = <table> {
 }
 variables = <table> {
 }
 RegisterPowers = <function> defined @Hekili/Classes.lua:376
 options = <table> {
 }
 RegisterGear = <function> defined @Hekili/Classes.lua:486
 abilities = <table> {
 }
 RegisterSetting = <function> defined @Hekili/Classes.lua:952
 stateTables = <table> {
 }
 hooks = <table> {
 }
 RegisterPet = <function> defined @Hekili/Classes.lua:913
 RegisterSetBonuses = <function> defined @Hekili/Classes.lua:509
 SetSetting = <function> defined @Hekili/Classes.lua:946
 RegisterPotion = <function> defined @Hekili/Classes.lua:517
 RegisterSetBonus = <function> defined @Hekili/Classes.lua:504
 RegisterPotions = <function> defined @Hekili/Classes.lua:552
 GetSetting = <function> defined @Hekili/Classes.lua:941
 settings = <table> {
 }
 pets = <table> {
 }
 funcHooks = <table> {
 }
 resources = <table> {
 }
 RegisterPhase = <function> defined @Hekili/Classes.lua:428
 RegisterHook = <function> defined @Hekili/Classes.lua:562
 RegisterPriority = <function> defined @Hekili/Classes.lua:886
 RegisterRecheck = <function> defined @Hekili/Classes.lua:558
 stateFuncs = <table> {
 }
 RegisterPvpTalents = <function> defined @Hekili/Classes.lua:225
 id = 0
 RegisterPack = <function> defined @Hekili/Classes.lua:879
 resourceAuras = <table> {
 }
 RegisterStateExpr = <function> defined @Hekili/Classes.lua:392
 RegisterAura = <function> defined @Hekili/Classes.lua:232
 RegisterStateFunction = <function> defined @Hekili/Classes.lua:399
 RegisterTotem = <function> defined @Hekili/Classes.lua:933
 key = "none"
 pseudoAbilities = 3
 RegisterCombatLogEvent = <function> defined @Hekili/Classes.lua:905
 RegisterEvent = <function> defined @Hekili/Classes.lua:893
 RegisterVariable = <function> defined @Hekili/Classes.lua:978
}
ability = "healthstone"
data = <table> {
 gcd = "off"
 charges = 1
 bagItem = true
 id = -102
 startsCombat = false
 item = 5512
 texture = 538745
}
a = <table> {
 gcd = "off"
 charges = 1
 bagItem = true
 id = -102
 startsCombat = false
 handler = <function> defined @Hekili/Classes.lua:2488
 funcs = <table> {
 }
 key = "healthstone"
 from = 0
 realCast = 0
 item = 5512
 texture = 538745
}
item = 5512
(*temporary) = nil
(*temporary) = <table> {
 new = <function> defined @HealthstoneAutoMacro/Core/Item.lua:3
}
(*temporary) = 5512
(*temporary) = "attempt to call method 'CreateFromItemID' (a nil value)"
CommitKey = <function> defined @AddOns

**Comment by oRRs** [comment]
This is caused by the Healthstone Auto Macro update to v2.4 - reverting it to v2.3 fixes it.

**Comment by Hekili** [comment]
Is that addon polluting the Item table?

**Comment by Dimmnn** [comment]
So I downloaded 2.3 of Healthstone Auto Macro and the errors stopped. So im guessing its that addon something is conflicting with the addon, I was also getting some weakaura errors for certain bars but after reverting back to 2.3 those stopped as well.

**Comment by Hekili** [comment]
Yeah, I put in a ticket on that addon's GitHub.  They are overwriting the `Item` table in WoW which is used by lots of addons, so hopefully they resolve that fairly quickly.
