### ISSUE TITLE
Hekili recommending Memory of Lucid Dreams outside of Voidform [Shadow Priest]

### ISSUE THREAD

**Issue by Nori-MD** [Hekili/hekili#219]
Class/spec: Priest, shadow

(I hope I've submitted this correctly)

**Describe the Bug/Issue**
Hekili is recommending Memory of Lucid Dreams outside of Voidform.  When I enter combat, Lucid Dreams is recommended right away and won't go away until I use it.

This issue was reported a month ago by somebody else, but without required information to help you debug, and therefore closed and not addressed.

**Expected behavior**
Lucid Dreams should be recommended only when buff.voidform.up

**To reproduce**
Enter combat, when not in Voidform.  Memory of Lucid Dreams will be shown as the next recommended skill.

Lucid dreams is in the cooldown section of the APL:
[comment]  Use Memory of Lucid Dreams right before you are about to fall out of Voidform
actions.cds=memory_of_lucid_dreams,if=(buff.voidform.stack>20&insanity<=50)|(buff.voidform.stack>(26+7*buff.bloodlust.up))|(current_insanity_drain*gcd.max*3)>insanity

A look at the snapshot reveals that the logic used to recommend Lucid Dreams is based on criteria set in the ability section (boss only, # of targets, etc.), and did not include the APL logic above.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/J1Ga4BRC

 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/NKZeENnS

**Comment by Hekili** [comment]
Just wanted to note that I saw this; I'll be making a pass on APLs this coming weekend -- in the mean time, you could certainly add an entry for Memory of Lucid Dreams to your priority using the same logic.

**Comment by Hekili** [comment]
Can you submit an updated snapshot?  Memory of Lucid Dreams should be accounted for via the APL rather than via Use Items in the default APL.
