### ISSUE TITLE
Guardian Druid: Recommending abilities that are still on cooldown.

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#2190]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Whenever I am in a dungeon it keeps recommending abilities that are on cooldown.

### How to Reproduce

1. Enter the game as a guardian druid.
2. Use the spec provided.
3. Enter a dungeon.
4. Get into combat. 
5. Once all abilities with a CD of 60 seconds or more are used it will recommend them again.

### Talent Loadout

BgGAYhlYdy9RJ6ROrphOEi69vCAAAAAAAAAAAAASEJJpkokkkEJARShCgAQSSgkkEJJShkWiDAAAAAAAAA

### Snapshot

https://pastebin.com/DNpGLsb2

### Additional Information
Abilities that it is recommending that are still on CD

Rage of the Sleeper 60-second CD
Incarnation: Guardian of Ursoc 180-second CD
Nature's Vigil 90-second CD

Personally, I would recommend any damaging abilities to fill the gap.

### Contact Information

MrWizard #8972 (Discord)

**Comment by Hekili** [comment]
Be specific.  Which abilities, specifically?  Does the snapshot show an ability that's on a long cooldown?  What should be suggested instead?

**Comment by MrWizard516** [comment]
Rage of the Sleeper 60-second CD
Incarnation: Guardian of Ursoc 180-second CD
Nature's Vigil 90-second CD

Personally, I would recommend any damaging abilities to fill the gap.

**Comment by Hekili** [comment]
So, you're snapshotting your Cooldowns display here, which is only going to show your cooldowns.  Do you have your displays stacked in a way that is misleading yourself?

**Comment by MrWizard516** [comment]
I have them all stacked together. I do that so that I can't get confused.
Is there a command that I can add to only show when on CD?

**Comment by Hekili** [comment]
That doesn't make sense.  You're having cooldown abilities shown separately.  The cooldowns display isn't going to have non-cooldown abilities mixed in.  I think you want to uncheck "Show Separately" for Cooldowns in /hekili > Toggles.
