### ISSUE TITLE
Havoc /hek set option for movement toggle

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#2192]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Currently Hekili only has a /hek set unbound_movement option which toggles the "Movement for Unbound Chaos" feature. I would like to suggest that there's another /hek set option for just general movement suggestions so that it can be keybound with a macro.

There's sometimes in tight spaces in dungeons or raids where a quick keybind toggle for turning movement suggestions on/off would be great.

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/209352085-96719d7b-662d-4ca9-94af-eb20a89d1eeb.png)

?

**Comment by jmusick** [comment]
Sorry when I typed /hek set in game I didn't see an option for regular movement toggle.

![image](https://user-images.githubusercontent.com/2590271/209417203-2bd4fbb7-fb5c-446e-94f4-56051d462342.png)
