### ISSUE TITLE
Missing Recommendations

### ISSUE THREAD

**Issue by Ormal1708** [Hekili/hekili#2193]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Rogue Outlaw rotation doesn't appear to recommend Trinkets or Adrenaline Rush, similarly in Assassination spec doesn't recommend Thistle Tea, Trinkets, Deathmark or Echoing Reprimand. Is this an issue or a configuration issue within the tool?

**Comment by Hekili** [comment]
This is not an enhancement; you're asking about recommendations.  You likely don't have your Cooldowns toggle enabled.  If that's incorrect, submit a Recommendations ticket with all the required information instead.

**Comment by Ormal1708** [comment]
How do I enable Cooldowns and if enables does the recommendation show in the primary display?

**Comment by Hekili** [comment]
See /hekili > Toggles

https://github.com/Hekili/hekili/wiki/Getting-Started#toggles--cooldowns-interrupts-potions-and-defensives

**Comment by Ormal1708** [comment]
Perfect thank you and Merry Christmas :)
