### ISSUE TITLE
Windwalker Serenity Single Target Priority issues

### ISSUE THREAD

**Issue by Moistbuddha2** [Hekili/hekili#2195]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Monk Single Target Priority in the APL and peak of serenity recommends cancelling fists of fury in the Serenity window, in order to buff your Rising Sun Kicks  with Xuen's Battlegear talent. The addon is not recommending fists of fury be cast until there is less than 1 second left in the serenity window to buff a full Fists of fury channel. 

### How to Reproduce

1. Enter Game
2. Find single target dummy
3. Follow recommended opener - chi building, xuen, faeline, serenity, strike of the windlords, and here there should be a fists of fury cast that is cancelled but the 4 button list just has RSK,BOK, and tiger palm until the last second. 

### Talent Loadout

B0QAdeydY63Y4XKaboK13uRRQAAAAAAAAgEJJRLiEBAAAAkIJJASSSSSaJpIJiECkkEplACAA

### Snapshot

https://pastebin.com/cKfe26AK

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/sqF1GELdPNtbszgXnEzkvW/simc

### Additional Information

<html>
<body>

actions.serenity
--

Y | 2.92 | strike_of_the_windlord,if=active_enemies<3Serenity Priority
Z | 0.62 | fists_of_fury,if=buff.serenity.remains<1
  | 0.00 | blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike&buff.teachings_of_the_monastery.stack=3&buff.teachings_of_the_monastery.remains<1
a | 8.34 | fists_of_fury_cancel
  | 0.00 | blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike&active_enemies=3&buff.teachings_of_the_monastery.stack=2
  | 0.00 | spinning_crane_kick,if=combo_strike&(active_enemies>3\|active_enemies>2&spinning_crane_kick.modifier>=2.3)
  | 0.00 | strike_of_the_windlord,if=active_enemies>=3
  | 0.00 | spinning_crane_kick,if=combo_strike&active_enemies>1
  | 0.00 | whirling_dragon_punch,if=active_enemies>1
  | 0.00 | blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=active_enemies>=3&cooldown.fists_of_fury.remains&talent.shadowboxing_treads
  | 0.00 | rushing_jade_wind,if=!buff.rushing_jade_wind.up&active_enemies>=3
b | 15.00 | rising_sun_kick,target_if=min:debuff.mark_of_the_crane.remains
c | 2.84 | spinning_crane_kick,if=combo_strike&buff.dance_of_chiji.up
d | 16.20 | blackout_kick,target_if=min:debuff.mark_of_the_crane.remains,if=combo_strike
  | 0.00 | whirling_dragon_punch
e | 4.57 | tiger_palm,target_if=min:debuff.mark_of_the_crane.remains,if=talent.teachings_of_the_monastery&buff.teachings_of_the_monastery.stack<3

</body>
</html>

### Contact Information

Moistbuddha#7828

**Comment by Hekili** [comment]
> [pastebin.com/cKfe26AK](https://pastebin.com/cKfe26AK)

This isn't a snapshot.  You have to copy and paste the whole thing.

**Comment by Moistbuddha2** [comment]
Well i will try again,

**Comment by Moistbuddha2** [comment]
Hopefully this was done correctly 
https://pastebin.com/Mtb1J76n

**Comment by Hekili** [comment]
The snapshot doesn't appear to be taken at the time you described.  I'll try to replicate it myself, but you were reporting that you weren't seeing the Fists of Fury cancellation, so the time to take the snapshot would be when you've started to use Fists of Fury.  Thanks!

**Comment by Moistbuddha2** [comment]
Im showing you that as that is where Fists of Fury should be. Fists is not showing up at all until the end of the serenity window. That snapshot is the beginning of the serenity window

**Comment by Hekili** [comment]
Thanks for the clarification.  It seems that SimC has implemented a version of Fists of Fury that you cancel as a separate ability from a Fists of Fury that you fully channel, instead of just interrupting the channel of Fists of Fury when appropriate.  I'll investigate.

**Comment by Hekili** [comment]
This should be addressed in 2.0.9a.

**Comment by Moistbuddha2** [comment]
Thanks so much!
