### ISSUE TITLE
Why does Hekili not recommend regrowth in queue upon predatory swiftness, and below 50% hp

### ISSUE THREAD

**Issue by jadethread1** [Hekili/hekili#2196]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

i would like hekili to recommend regrowth when predatory swiftness pops on feral druid and below 50% hp

**Comment by Hekili** [comment]
Because it has no DPS value.
