### ISSUE TITLE
Outlaw rogue ambush remains.

### ISSUE THREAD

**Issue by chalchal2** [Hekili/hekili#2198]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Ambush is not enabled, but the Ambush skill continues to be on the screen. Even after using up the dark dance and extinction, the ambush is recognized as available and the dealcycle is not properly represented.

### How to Reproduce

1. Fixing an evil attack if the ambush is unavailable

### Snapshot

https://github.com/Hekili/hekili/issues/Pastebin

**Comment by Hekili** [comment]
Sorry, you must fill out tickets properly if you want support.
