### ISSUE TITLE
Arcane mage ST opener/Burn

### ISSUE THREAD

**Issue by Byggden** [Hekili/hekili#2203]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Arcane mage opener/burn always open up with evocation into arcane surge. 

Should be: Evo->Rune->Spark->3xAB->Trinket-> Arcane Surge
https://www.icy-veins.com/wow/arcane-mage-pve-dps-easy-mode

### How to Reproduce

Enter game as arcane mage and choose single target on Hekili with Cooldowns.
![image](https://user-images.githubusercontent.com/121470529/209603605-64a106bb-483c-4d0e-8710-10db9d8f497b.png)

### Talent Loadout

B4DAAAAAAAAAAAAAAAAAAAAAAIJAHolIRSSDEtEiIikIhEaJItkAAAAAAAAAAAAkkkkESSSCA

### Snapshot

https://pastebin.com/9DySN1gR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tNsPyLjc1C9PEpqoAf5Sh9

### Additional Information

raidbots/simc uses a completly different opener that advised by both Hekili and Icy-Veins

### Contact Information

Byggden#6179

**Comment by Hekili** [comment]
You did not copy the entire snapshot(s).

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, **press CTRL+A to select all text including hidden text and press CTRL+C to copy**.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
