### ISSUE TITLE
Unholy DK no gargoyle or blood fury in newest update

### ISSUE THREAD

**Issue by Heggehasch** [Hekili/hekili#2204]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

On pull the addon does not recommend Gargoyle or Blood fury which has been the standard recommendation until today after the latest patch on Hekili.

Damage is extremely low due to this and can't seem to understand why. 
[Unholy DK.txt](https://github.com/Hekili/hekili/files/10310018/Unholy.DK.txt)

### How to Reproduce

1. Just use unholy DK and try the rotation, it wont recommend Gargoyle nor Blood fury

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAkISSSgEESSEiIJSkAAAAAAAAAAKJJhIAAgEpkIRSSikA

### Snapshot

https://pastebin.com/LyWz7Vbx

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6VhgNf7rRv3tHurvj2gxPX

### Additional Information

It does show to use gargoyle on the raidbots profile

**Comment by Heggehasch** [comment]
[Unholy DK (1).txt](https://github.com/Hekili/hekili/files/10310101/Unholy.DK.1.txt)

https://pastebin.com/b3xzVSgv 

Second pastebin after turning on CD's which was recommended, still no change. Havnt touched options except X on the abilities I do have

3rd pastebin after full reinstall without touching anything

https://pastebin.com/6Z1DJn1z

**Comment by Hekili** [comment]
Thanks; I missed an edit in the update.  Will post an update in a little bit.

**Comment by Hekili** [comment]
This has been resolved.
