### ISSUE TITLE
Add KkthnxUI support please and thank you

### ISSUE THREAD

**Issue by Kkthnx** [Hekili/hekili#2205]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

If you have time could you please add KkthnxUI support

my LAB lib is `kkthnxui = LibStub:GetLibrary("LibActionButton-1.0-KkthnxUI", true),`

also you can see my bar code here 
https://github.com/Kkthnx-Wow/KkthnxUI/blob/master/KkthnxUI/Modules/ActionBars/Elements/Bars.lua

If you have any questions please don't hesitate to let me know so we can get support going! Thank you and happy new years!

### Contact Information

Kkthnx#3217

**Comment by Hekili** [comment]
I'll take a look and/or accept PRs for this.
