### ISSUE TITLE
Unholy not recommending Death and Decay or Epidemic during AOE

### ISSUE THREAD

**Issue by IsitScript** [Hekili/hekili#2206]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Unholy DK rotation not recommending when to use Death and Decay, Unholy Blight , Epidemic, Outbreak during AOE.
Abomination Limb will appear in the rotation but by the time Im suppouse to hit it it will suggest something completely different never actually suggesting it for real.

### How to Reproduce

AOEing or attacking Single target dummies will just never suggest using certain CD's or abilities even when all of these are turned on. Worked fine up until latest update.

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAiQSCJtIhQiEhQSiEBAAAAAAAAAAJJJCJpBAQKSJkkkDIJHA

### Snapshot

https://pastebin.com/GKMW4Nwz

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/4TCS81hnWTjxkEG3FwgcYS

**Comment by jmusick** [comment]
Same issue. Made a snapshot on 5 target dummies for it as well. https://pastebin.com/kdzd4GGP

**Comment by IsitScript** [comment]
Updated pastebin with correct snapshot. Sorry about that.

**Comment by Hekili** [comment]
Thanks; this should be addressed in 2.0.9d.
