### ISSUE TITLE
Enhancement : show while targeting ennemy

### ISSUE THREAD

**Issue by Araldwenn** [Hekili/hekili#2207]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Hi,
As I suggest in the title, would it be possible to show Hekili out of combat only if targeting a hostile target ? It would allow for knowing which opening to use without flashing the bars/showing icons all the time out of combat.

**Comment by Hekili** [comment]
/hekili > Displays > (whichever) > Visibility > Advanced

**Comment by Araldwenn** [comment]
So in fact, I only use spellflash, and /hekili > Displays > (whichever) > Visibility > Advanced doesn't change spellflash behaviour.
Should I mention it as a bug then ?

**Comment by Hekili** [comment]
No, it's not a bug, it's a feature request at best.
