### ISSUE TITLE
Trinket "Gift of Radiance" is not recommended.

### ISSUE THREAD

**Issue by PopsGG** [Hekili/hekili#2209]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The trinket "Gift of Radiance" (https://www.wowhead.com/item=133647) is not recommended in any rotation. It is off the GCD and should be used on CD.

It is not listed under Gear and Items in the settings on a paladin.

### How to Reproduce

1) Log on to character with the trinket
2) Attack target dummy.
3) The rotation will never recommend the trinket.

### Talent Loadout

BIEAwtJ2KpR8WbGzhz/jy2AP80iWCpIKHItkkUKNJJSgIBAAAAAAAAAAAAAANRSSkgIRJFRSIKB

### Snapshot

n/a

### Contact Information

Gurk#4116

**Comment by Hekili** [comment]
This should be resolved.
