### ISSUE TITLE
Brewmaster Purifying Brew never shows

### ISSUE THREAD

**Issue by Kinnetikx** [Hekili/hekili#2211]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Regardless of setting, Purifying Brew is never shown.   Defensive Toggles can be turned on, and the thresholds can be set to their lowest settings (0.1) in the Stagger Tick %, but Purifying Brew is never recommended.

Even adding a custom priority with either no condition or something as simple as 'debuff.light_stagger.remains > 2' never reports it despite all factors being true and being at the very top of the default list.  It even shows as 'True', yet the icon is not in the list.  See screenshot.
![WoWScrnShot_122922_090818](https://user-images.githubusercontent.com/121625500/209972617-27c1a6c5-351d-422d-a51c-dd0e08b749b2.jpg)
![WoWScrnShot_122922_090819](https://user-images.githubusercontent.com/121625500/209972622-afaab137-1365-41a9-a200-6abcf37c1cc6.jpg)

### How to Reproduce

1. Enter game as Monk Class. Set specialization to Brewmaster.
2. Toggle Defensives on.  Set Purifying Brew to any setting of lowest threshold.
3. Walk up to any tanking dummy and take damage to add to stagger pool.
4. Notice Purifying Brew is never recommended.

### Talent Loadout

BwQAdeydY63Y4XKaboK13uRRQAAAAAAAQAAAAIUiSLJJESSaNCAAAQaRkEJSIBJJJpkAiIRapUC

### Snapshot
https://pastebin.com/JjNuWp3h

The key seems to be it's not finding staggered damage.

I created a 2nd snapshot after trying a couple other things and now it's coming up with an error about staggered_damage in the state metatable

https://pastebin.com/eWkUPDP3

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jYMexsbdupGGiFCRNQSNiT

**Comment by Hekili** [comment]
You did not supply a complete snapshot. It should be very long and you have to paste it to Pastebin and provide the link.

**Comment by Kinnetikx** [comment]
Updated with complete snapshot.  Looking at it, it appears to indicate no damage is staggered, even though I clearly have staggered damage?

   5.   purifying_brew ( default - 4 )
        The action (purifying_brew) is unusable at (0.00 + 0.00) because no damage is staggered.
        
I also pulled another snapshot and it seems it now has a warning about staggered_damage in the state metatable

**Comment by Kinnetikx** [comment]
I finally got it to show out in the field, but it appears random and very inconsistent.  Here is a snapshot of it actually displaying in the field. 

https://pastebin.com/hidK6ztR

In looking through the snapshot it seems it fails all of the basic criteria, but is passing when both niuzao and woo is up.

**Comment by Kinnetikx** [comment]
Some further investigation, it seems some things also don't like being a rest zone, such as at training dummies in capitol cities.

**Comment by Hekili** [comment]
There are oddities associated with dummies lying about dying and resetting some data.

**Comment by Kinnetikx** [comment]
Still though, the third log is from the field, not on a dummy or in a capitol city/rested area.  It still shows the oddities that none of the base purifying brew conditions ever trigger, yet the one listed under the Niuzao/Woo list does, albeit very inconsistently and with odd results

**Comment by Hekili** [comment]
Yeah, the conditions checking for solo/group are both returning false due to an error, which is an easy fix.

> the one listed under the Niuzao/Woo list does, albeit very inconsistently and with odd results

What do you mean by this?

**Comment by Hekili** [comment]
> I created a 2nd snapshot after trying a couple other things and now it's coming up with an error about staggered_damage in the state metatable

What are the things you tried?

**Comment by Kinnetikx** [comment]
> Yeah, the conditions checking for solo/group are both returning false due to an error, which is an easy fix.

I noticed this as well, however I did try attempting to remove the &solo flags and it still will not display.  I feel like the heart is somehow it's still not able to pull the damage that is staggered based on what I previously posted.

The action (purifying_brew) is unusable at (0.00 + 0.00) because no damage is staggered.

If it was related to the solo or group flag, wouldn't the snapshot report that it failed on the recommendation due to not being solo or in a group?  The above error seems to indicate something different.

> > the one listed under the Niuzao/Woo list does, albeit very inconsistently and with odd results
> 
> What do you mean by this?

What I mean is the third log posted you can see that it finally did return Purifying Brew as a command, but the one that was was the one listed under the cooldowns_niuzao_woo action list as shown below.  I attached the screenshot that generated it.

The reason I say inconsistent is that it seems to not always recommend it under the same circumstances or conditions.  When I looked at it, it seemed to be related to this condition:

stagger.amounttototalpct

I don't know where that field is derived from, but I tried watching it in the field (Keeping Hekili open and hovering over the condition).

The field would go from Nil to 5 without any consistency based on stagger condition or any other factor.  I could have a healthy stagger pool and it wouldn't report anything.  I could have very little and it would report 5 such as below.

 37.  purifying_brew ( cooldowns_niuzao_woo - 4 )
        The action (purifying_brew) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( cooldowns_niuzao_woo ) called from ( Brewmaster:default:32 ) would PASS at 0.00.
        ( talent.invoke_niuzao_the_black_ox.enabled[true] + talent.improved_invoke_niuzao_the_black_ox.enabled[false] ) <= 1
         - this entry's criteria PASSES: talent.purifying_brew.enabled[true] & stagger.amounttototalpct[5.00] >= 0.7 & ! buff.blackout_combo.up[false]
        Action chosen:  purifying_brew at 0.00!
        Exiting cooldowns_niuzao_woo with recommendation of NO ACTION at +10.00s.
        Returned from list (cooldowns_niuzao_woo), current recommendation is purifying_brew (+0.00).
        - cooldowns_niuzao_woo

![WoWScrnShot_122922_154336](https://user-images.githubusercontent.com/121625500/210079821-03576e2b-3262-4404-84a9-22a1c657b8dd.jpg)

**Comment by Hekili** [comment]
Yeah, that may or may not be resolved with 2.0.9f.  I can't tell which version you were using in your latest post.  It's better to link the whole snapshot and then discuss it.

**Comment by Hekili** [comment]
Are you having this issue in 2.0.9f or 2.0.10?  If so, please supply updated snapshot(s) for review.  Thanks!
