### ISSUE TITLE
Hekili not toggle off (Hpala)

### ISSUE THREAD

**Issue by Nessota** [Hekili/hekili#2212]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

As it says, if you change your specification from ret to holy, you need to reload ui to hide hekili. This is not an issue with my dh, it has vengeance disabled in hekili.

**Comment by BloodyFess** [comment]
The same, when I change spec on my monk and shaman from DD to healers. Hekili not disappears. Need to disable it and enable again for correct displaying. It will be great to fix this.

**Comment by Hekili** [comment]
This should be resolved today (in 2.0.14).
