### ISSUE TITLE
Rogue shiv enrage 

### ISSUE THREAD

**Issue by Paintrain187** [Hekili/hekili#2215]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Hello, I was wondering if it is possible to add an action to rogue interrupt toggle that would show shiv when target is enraged?

**Comment by Hekili** [comment]
You can set an ability to require a toggle via /hekili > Abilities (or /hekili > Gear and Trinkets, if item-related).

You can create a custom priority to use Shiv; you would want the condition to be `debuff.dispellable_enrage.up`.

See the Wiki/FAQ regarding custom priorities.
