### ISSUE TITLE
Change size of Spellflash glow for Circles

### ISSUE THREAD

**Issue by Peregran** [Hekili/hekili#2217]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

I would love to be able to adjust the size (diameter) of the circle when using the Spellflash feature.   I tried all kinds of settings, but none appear to affect it.   The current size is way too big and starts to obscure the other buttons.

Thanks in advance!

### Contact Information

richard@skurnick.net

**Comment by Hekili** [comment]
As far as I can tell, the Flash Size setting on the display's SpellFlash tab does this just fine.

![image](https://user-images.githubusercontent.com/9438134/210087949-4baf2343-3350-45c3-82af-2454caaf1eec.png)

![image](https://user-images.githubusercontent.com/9438134/210087960-6d23c578-fb7a-4cd3-95fc-cd679128a475.png)

![image](https://user-images.githubusercontent.com/9438134/210088026-0388bd75-e213-4b17-8fb4-0a645780790c.png)

![image](https://user-images.githubusercontent.com/9438134/210088002-597e7085-f326-4839-b9e1-692641caa6d8.png)

**Comment by Hekili** [comment]
See /hekili > Displays > Primary > SpellFlash.

**Comment by Peregran** [comment]
Just in case it matters, I only care about the Spellflash ability of the module, I disable the displays.

I tried making it bigger, I tried making it smaller and with it set to 0 it was a no go.   Just as an additional note, I want it to be one size all the time and not pulse or grow/shrink and it didn't work.      I set it to fixed and set it to not fixed size, no luck.

 I do appreciate the fast response!   Being a developer and in IT for a long time, I did a code mode that fixed the issue for me. 

I also ran into an issue where for the different items, I want different colors, for offensive spells yellow, interrupts purple an that also doesn't work.   Maybe I just have the settings wrong.

Any help would be appreciated.   Thanks in advance!

**Comment by Hekili** [comment]
> I tried making it bigger, I tried making it smaller and with it set to 0 it was a no go. Just as an additional note, I want it to be one size all the time and not pulse or grow/shrink and it didn't work. I set it to fixed and set it to not fixed size, no luck.

Show your work.  Those settings all work for me.  Have you installed a separate SpellFlash addon that's overriding controls or something?

> I want different colors, for offensive spells yellow, interrupts purple an that also doesn't work. Maybe I just have the settings wrong.

None of those are settings supported in the addon directly.

**Comment by Peregran** [comment]
To be fair, I completed deleted the save files and the addon and re-installed fresh.   On the Multiple Tab I turned all the options on the top on and made the adjustments you see on the screenshot.   I made sure all the options (Primary, AOE, Cooldowns, Defensives, Interrupts) where identical to Multiple).   I then took on some mobs and the size of the Circle did not change no matter what the setting was.   Remember I want the circle to be just big enough to be over the button I should be presssing, not the size you see (I'm attaching a few files).   In response to you mentioning that the colors are not supported, please explain the purpose of the color option on the SpellFlash tab for each different type of spell.   Maybe I'm misunderstanding it.   The thing is when I went fresh I was seeing 2 colors green and red (I didnt change the default colors).  Also I didnt see the addon suggesting the use of Pummel for interrupts.   Could be a misconfigure on my part.  

Thank you for taking the time to work with me on this.
![WoWScrnShot_123022_183232](https://user-images.githubusercontent.com/73302712/210118255-380e4d0b-f412-4914-8866-fc7bbd67e206.jpg)
![WoWScrnShot_123022_182556](https://user-images.githubusercontent.com/73302712/210118280-7a3c482e-2d1a-42a5-8724-181c628c30d0.jpg)

Let me know if you need more info/screen shots.

**Comment by Hekili** [comment]
The color option is not for the type of spell; it's for the abilities that would be recommended in the display in question.  For example, both Primary and AOE could recommend the same ability under similar or different circumstances.  Because you hide displays, the design metaphor for coloring the flash associated with each display may be confusing.

Editing SpellFlash via the "Multiple" option might be an issue.  You might try editing those settings in your Primary display alone and see if you get better results.
