### ISSUE TITLE
Shield of the Righteous - Divine Purpose

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#2218]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Shield of the Righteous is not immediately being recommended when Divine Purpose is up. It is only being recommended once you have 3 holy power. I believe the "spend" function for shield_of_the_righteous needs to be updated to include Divine Purpose, similar to what is being done with bastion_of_light (line 1444) of PaladinProtection.lua

current: if buff.bastion_of_light.up then return 0 end
suggested: if buff.bastion_of_light.up or buff.divine_purpose.up then return 0 end

### How to Reproduce

1. Enter game as Protection Paladin
2. Talent into Divine Purpose
3. Wait for it to proc with < 3 Holy Power
4. Build up to 3 Holy Power before Shield of the Righteous is suggested.

### Snapshot

https://pastebin.com/CKby2hEM

**Comment by Hekili** [comment]
This should be resolved.  Thanks for reporting.
