### ISSUE TITLE
[Rogue Outlaw] Restless Blades CDR miscalculation

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#2219]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I am refering to Line 713 in https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/RogueOutlaw.lua

1. [True Bearing](https://www.wowhead.com/spell=193359/true-bearing) was changed to reduce CD only by 0.5 second instead of 1

2. [Float like a butterfly ](https://www.wowhead.com/spell=354897/float-like-a-butterfly) reduce CD by 0.5 seconds only for  [Evasion](https://www.wowhead.com/spell=5277/evasion) and [Feint](https://www.wowhead.com/spell=1966/feint) and not for other spells in restless_blades_list.

3. [Evasion](https://www.wowhead.com/spell=5277/evasion) and [Feint](https://www.wowhead.com/spell=1966/feint) with [Float like a butterfly ](https://www.wowhead.com/spell=354897/float-like-a-butterfly) active talent CDR are not implemented in the profile as neither [Evasion](https://www.wowhead.com/spell=5277/evasion) nor [Feint](https://www.wowhead.com/spell=1966/feint) are in the restless_blades_list.

### How to Reproduce

-

### Talent Loadout

-

### Snapshot

-

### Contact Information

IIeTpoc#3818 discord ID

**Comment by Hekili** [comment]
These should be resolved in 2.0.10.
