### ISSUE TITLE
Concentrated flame cooldown

### ISSUE THREAD

**Issue by oayorkshireman** [Hekili/hekili#222]
Im trying to add an entry cooldown. Ive gone into entry in action list. Concentrated flame. Entry cooldown to 7. But it still requests me to use both charges of concentrated flame. I don't want to over write the concentrated flame dot.

Its likely a mistake by me, but ive tried everything I can think of.

Thanks Adam
http://imgur.com/a/0PbJGnW
![Hekilli - Imgur](https://user-images.githubusercontent.com/55314645/64906441-a1f85100-d6de-11e9-95bb-66fa3f778928.png)

**Comment by Hekili** [comment]
Still need a snapshot of Concentrated Flame being recommended -- it's possible you have other entries for Concentrated Flame, etc.  The "Entry Cooldown" applies only to that specific entry.  The default priority for BM has an entry in the Cleave list and an entry in the Single-Target list.

Additionally, if you're wanting to avoid using it when the DOT is up, you should just use Conditions.

`debuff.concentrated_flame_burn.down`

**Comment by oayorkshireman** [comment]
Thanks for the quick response.
So ill just add that condition to each entry and test it. Thanks matey

Greatly appreciated, love the addon as a new dps player its really helpful.

Adam

**Comment by oayorkshireman** [comment]
Hi, tried to add the debuff.concentrated_flame_burn.down
to 
Cleave > Concentrated Flame (see picture)
Still got the same output on the display.
However in ST
ST > Concentrated flame there was already some conditions.
![both visible](https://user-images.githubusercontent.com/55314645/64910238-f6fe8c00-d70b-11e9-9970-665efc8fcb66.jpg)
![one on cd](https://user-images.githubusercontent.com/55314645/64910239-f6fe8c00-d70b-11e9-9975-0014c8c57345.jpg)
![st flame](https://user-images.githubusercontent.com/55314645/64910240-f7972280-d70b-11e9-915c-8a715e070fbe.jpg)

I guess its not really a big issue, i can just ignore it. Its just more a quality of life :D

**Comment by Hekili** [comment]
Still need a snapshot to see when/why things were recommended.

**Comment by oayorkshireman** [comment]
Again going to sound stupid, but how do I do the snapshot? Nothing displays.
![snapshot](https://user-images.githubusercontent.com/55314645/64910944-c884af00-d713-11e9-9fba-475e2eda5042.jpg)

**Comment by oayorkshireman** [comment]
Info from error reporting

build: v8.2.0-08.08
level: 120 (120)
class: HUNTER
spec: beast_mastery

talents: a_murder_of_crows
    aspect_of_the_beast
    chimaera_shot
    killer_instinct
    natural_mending
    posthaste
    stomp

azerite: azerite_empowered=3
    bulwark_of_the_masses=1
    dance_of_death=2
    duck_and_cover=1
    elemental_whirl=2
    feeding_frenzy=1
    overwhelming_power=1
    primal_instincts=3
    resounding_protection=1

essences: [the_crucible_of_flame]=3, essence_of_the_focusing_iris=2

sets/legendaries/artifacts: pocketsized_computation_device=1

gear:     akanas_reefstrider_treads=1
    azshari_stormsurger_shoulderguards=1
    azshari_stormsurger_vest=1
    grips_of_the_scaled_arcanist=1
    heart_of_azeroth=1
    honorbound_vanguards_leggings=1
    logic_loop_of_synergy=1
    notorious_aspirants_longbow=1
    oris_tidal_bracers=1
    pocketsized_computation_device=1
    silivazs_skullguard=1
    smugglers_cove_ring=1
    vims_scalecrusher_chain=1
    vision_of_demise=1
    voiddrenched_cape=1

itemIDs: 158075, 158160, 159289, 163445, 167555, 167767, 167772, 168357, 168381, 169156, 169307, 169747, 170142, 170304, 170369

**Comment by oayorkshireman** [comment]
ok found it, sorry. Took me a while 🗡 
build: v8.2.0-08.08
level: 120 (120)
class: HUNTER
spec: beast_mastery

talents: a_murder_of_crows
    aspect_of_the_beast
    chimaera_shot
    killer_instinct
    natural_mending
    posthaste
    stomp

azerite: azerite_empowered=3
    bulwark_of_the_masses=1
    dance_of_death=2
    duck_and_cover=1
    elemental_whirl=2
    feeding_frenzy=1
    overwhelming_power=1
    primal_instincts=3
    resounding_protection=1

essences: [the_crucible_of_flame]=3, essence_of_the_focusing_iris=2

sets/legendaries/artifacts: pocketsized_computation_device=1

gear:     akanas_reefstrider_treads=1
    azshari_stormsurger_shoulderguards=1
    azshari_stormsurger_vest=1
    grips_of_the_scaled_arcanist=1
    heart_of_azeroth=1
    honorbound_vanguards_leggings=1
    logic_loop_of_synergy=1
    notorious_aspirants_longbow=1
    oris_tidal_bracers=1
    pocketsized_computation_device=1
    silivazs_skullguard=1
    smugglers_cove_ring=1
    vims_scalecrusher_chain=1
    vision_of_demise=1
    voiddrenched_cape=1

itemIDs: 158075, 158160, 159289, 163445, 167555, 167767, 167772, 168357, 168381, 169156, 169307, 169747, 170142, 170304, 170369

New Recommendations for [ Primary ] requested at 17:21:00 ( 431477.61 ).

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00 ).
 - focus, 120 / 120

Processing precombat action list [ Beast Mastery - precombat ].
Current recommendation was NO ACTION at +60.00s.


[001] summon_pet ( precombat - 1 )
The action (summon_pet) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.


[002] potion ( precombat - 2 ) - ability disabled.


[003] azsharas_font_of_power ( precombat - 3 )
The action (azsharas_font_of_power) is unusable at (0.00 + 0.00) because item not equipped.


[004] worldvein_resonance ( precombat - 4 ) - ability unknown


[005] guardian_of_azeroth ( precombat - 5 ) - ability unknown


[006] memory_of_lucid_dreams ( precombat - 6 ) - ability unknown


[007] cyclotronic_blast ( precombat - 7 ) - ability unknown


[008] focused_azerite_beam ( precombat - 8 ) - ability unknown


[009] aspect_of_the_wild ( precombat - 9 ) - ability disabled.


[010] bestial_wrath ( precombat - 10 )
The action (bestial_wrath) is usable at (0.00 + 0.00) with cost of 0.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: azerite.primal_instincts.enabled[true] & ! essence.essence_of_the_focusing_iris.major[false] & ( equipped.azsharas_font_of_power[false] | ! equipped.cyclotronic_blast[false] )
Action chosen:  bestial_wrath at 0.00!
Completed precombat action list [ Beast Mastery - precombat ].
Recommendation is bestial_wrath at 0.00 + 0.00.
Recommendation #1 is bestial_wrath at 0.00s (0.00s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.33 ).
 - focus, 120 / 120

Processing precombat action list [ Beast Mastery - precombat ].
Current recommendation was NO ACTION at +60.00s.


[001] summon_pet ( precombat - 1 )
The action (summon_pet) is unusable at (0.00 + 1.33) because ability 'usable' function returned false without explanation.


[002] potion ( precombat - 2 ) - ability disabled.


[003] azsharas_font_of_power ( precombat - 3 )
We are already in-combat and this pre-combat action is not essential.  Skipping.


[004] worldvein_resonance ( precombat - 4 ) - ability unknown


[005] guardian_of_azeroth ( precombat - 5 ) - ability unknown


[006] memory_of_lucid_dreams ( precombat - 6 ) - ability unknown


[007] cyclotronic_blast ( precombat - 7 ) - ability unknown


[008] focused_azerite_beam ( precombat - 8 ) - ability unknown


[009] aspect_of_the_wild ( precombat - 9 ) - ability disabled.


[010] bestial_wrath ( precombat - 10 )
The action is not ready before our maximum delay window (15.00) for this query.
Completed precombat action list [ Beast Mastery - precombat ].

Processing default action list [ Beast Mastery - default ].
Current recommendation was NO ACTION at +60.00s.


[011] call_action_list ( default - 1 )
Time-sensitive Criteria deferred at +0.00 - debuff.casting.up[false] | debuff.dispellable_magic.up[false] | debuff.dispellable_enrage.up[false]
Action list (utility) was found.
+ utility
Current recommendation was NO ACTION at +60.00s.


[012] counter_shot ( utility - 1 ) - ability disabled.


[013] serenity_dust ( utility - 2 ) - ability unknown


[014] spore_cloud ( utility - 3 ) - ability unknown


[015] soothing_water ( utility - 4 ) - ability unknown


[016] sonic_blast ( utility - 5 ) - ability unknown


[017] nether_shock ( utility - 6 ) - ability unknown


[018] chijis_tranquility ( utility - 7 ) - ability unknown


[019] spirit_shock ( utility - 8 ) - ability unknown


[020] natures_grace ( utility - 9 ) - ability unknown
Returned from list (utility), current recommendation is NO ACTION (+60.00).
- utility


[021] use_items ( default - 2 )
There is no criteria for Use Items.
Current recommendation was NO ACTION at +60.00s.

Substituting concentrated_flame for Heart of Azeroth action; it is otherwise not included in the priority.
[022] concentrated_flame ( items - 1 )
The action (concentrated_flame) is usable at (0.00 + 1.33) with cost of 0.
 - the action is ready before the current recommendation (at +1.33 vs. +60.00).
 - this entry's criteria PASSES: ( ! settings.boss[false] | boss[false] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
Action chosen:  concentrated_flame at 1.33!


[023] vision_of_demise ( items - 2 )
The action is not ready before our maximum delay window (15.00) for this query.
Returned from Use Items; current recommendation is concentrated_flame (+1.33).


[024] ashvanes_razor_coral ( default - 3 )
The action (ashvanes_razor_coral) is unusable at (0.00 + 0.00) because item not equipped.
The recommended action (concentrated_flame) would be ready before the next GCD (1.33 < 1.33); exiting list (default).
Completed default action list [ Beast Mastery - default ].
Recommendation is concentrated_flame at 0.00 + 1.33.
Recommendation #2 is concentrated_flame at 1.33s (1.33s).
Advancing clock by 1.33...

RECOMMENDATION #3 ( Offset: 1.33, GCD: 0.00 ).
 - focus, 120 / 120

Processing precombat action list [ Beast Mastery - precombat ].
Current recommendation was NO ACTION at +60.00s.


[001] summon_pet ( precombat - 1 )
The action (summon_pet) is unusable at (1.33 + 0.00) because ability 'usable' function returned false without explanation.


[002] potion ( precombat - 2 ) - ability disabled.


[003] azsharas_font_of_power ( precombat - 3 )
We are already in-combat and this pre-combat action is not essential.  Skipping.


[004] worldvein_resonance ( precombat - 4 ) - ability unknown


[005] guardian_of_azeroth ( precombat - 5 ) - ability unknown


[006] memory_of_lucid_dreams ( precombat - 6 ) - ability unknown


[007] cyclotronic_blast ( precombat - 7 ) - ability unknown


[008] focused_azerite_beam ( precombat - 8 ) - ability unknown


[009] aspect_of_the_wild ( precombat - 9 ) - ability disabled.


[010] bestial_wrath ( precombat - 10 )
The action is not ready before our maximum delay window (15.00) for this query.
Completed precombat action list [ Beast Mastery - precombat ].

Processing default action list [ Beast Mastery - default ].
Current recommendation was NO ACTION at +60.00s.


[011] call_action_list ( default - 1 )
Time-sensitive Criteria deferred at +1.33 - debuff.casting.up[false] | debuff.dispellable_magic.up[false] | debuff.dispellable_enrage.up[false]
Action list (utility) was found.
+ utility
Current recommendation was NO ACTION at +60.00s.


[012] counter_shot ( utility - 1 ) - ability disabled.


[013] serenity_dust ( utility - 2 ) - ability unknown


[014] spore_cloud ( utility - 3 ) - ability unknown


[015] soothing_water ( utility - 4 ) - ability unknown


[016] sonic_blast ( utility - 5 ) - ability unknown


[017] nether_shock ( utility - 6 ) - ability unknown


[018] chijis_tranquility ( utility - 7 ) - ability unknown


[019] spirit_shock ( utility - 8 ) - ability unknown


[020] natures_grace ( utility - 9 ) - ability unknown
Returned from list (utility), current recommendation is NO ACTION (+60.00).
- utility


[021] use_items ( default - 2 )
There is no criteria for Use Items.
Current recommendation was NO ACTION at +60.00s.

Substituting concentrated_flame for Heart of Azeroth action; it is otherwise not included in the priority.
[022] concentrated_flame ( items - 1 )
The action (concentrated_flame) is usable at (1.33 + 0.00) with cost of 0.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: ( ! settings.boss[false] | boss[false] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
Action chosen:  concentrated_flame at 0.00!
Returned from Use Items; current recommendation is concentrated_flame (+0.00).
The recommended action (concentrated_flame) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Beast Mastery - default ].
Recommendation is concentrated_flame at 1.33 + 0.00.
Recommendation #3 is concentrated_flame at 0.00s (1.33s).

RECOMMENDATION #4 ( Offset: 1.33, GCD: 1.33 ).
 - focus, 120 / 120

Processing precombat action list [ Beast Mastery - precombat ].
Current recommendation was NO ACTION at +60.00s.


[001] summon_pet ( precombat - 1 )
The action (summon_pet) is unusable at (1.33 + 1.33) because ability 'usable' function returned false without explanation.


[002] potion ( precombat - 2 ) - ability disabled.


[003] azsharas_font_of_power ( precombat - 3 )
We are already in-combat and this pre-combat action is not essential.  Skipping.


[004] worldvein_resonance ( precombat - 4 ) - ability unknown


[005] guardian_of_azeroth ( precombat - 5 ) - ability unknown


[006] memory_of_lucid_dreams ( precombat - 6 ) - ability unknown


[007] cyclotronic_blast ( precombat - 7 ) - ability unknown


[008] focused_azerite_beam ( precombat - 8 ) - ability unknown


[009] aspect_of_the_wild ( precombat - 9 ) - ability disabled.


[010] bestial_wrath ( precombat - 10 )
The action is not ready before our maximum delay window (15.00) for this query.
Completed precombat action list [ Beast Mastery - precombat ].

Processing default action list [ Beast Mastery - default ].
Current recommendation was NO ACTION at +60.00s.


[011] call_action_list ( default - 1 )
Time-sensitive Criteria deferred at +1.33 - debuff.casting.up[false] | debuff.dispellable_magic.up[false] | debuff.dispellable_enrage.up[false]
Action list (utility) was found.
+ utility
Current recommendation was NO ACTION at +60.00s.


[012] counter_shot ( utility - 1 ) - ability disabled.


[013] serenity_dust ( utility - 2 ) - ability unknown


[014] spore_cloud ( utility - 3 ) - ability unknown


[015] soothing_water ( utility - 4 ) - ability unknown


[016] sonic_blast ( utility - 5 ) - ability unknown


[017] nether_shock ( utility - 6 ) - ability unknown


[018] chijis_tranquility ( utility - 7 ) - ability unknown


[019] spirit_shock ( utility - 8 ) - ability unknown


[020] natures_grace ( utility - 9 ) - ability unknown
Returned from list (utility), current recommendation is NO ACTION (+60.00).
- utility


[021] use_items ( default - 2 )
There is no criteria for Use Items.
Current recommendation was NO ACTION at +60.00s.

Substituting concentrated_flame for Heart of Azeroth action; it is otherwise not included in the priority.
[022] concentrated_flame ( items - 1 )
The action is not ready before our maximum delay window (15.00) for this query.


[023] vision_of_demise ( items - 2 )
The action is not ready before our maximum delay window (15.00) for this query.
Returned from Use Items; current recommendation is NO ACTION (+60.00).


[024] ashvanes_razor_coral ( default - 3 )
The action (ashvanes_razor_coral) is unusable at (1.33 + 0.00) because item not equipped.


[025] cyclotronic_blast ( default - 4 ) - ability unknown


[026] call_action_list ( default - 5 )
There is no criteria for this action list..
Action list (cds) was found.
+ cds
Current recommendation was NO ACTION at +60.00s.


[027] ancestral_call ( cds - 1 ) - ability unknown


[028] fireblood ( cds - 2 ) - ability unknown


[029] berserking ( cds - 3 )
The action (berserking) is usable at (1.33 + 0.00) with cost of 0.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
List ( cds ) called from ( Beast Mastery:default:5 ) would PASS at 0.00.
 - NONE
 - this entry's criteria FAILS: buff.aspect_of_the_wild.up[false] & ( time_to_die[3600.00] > cooldown.berserking.duration[180.00] + duration[10.00] | ( target.health.pct[100.00] < 35 | ! talent.killer_instinct.enabled[true] ) ) | time_to_die[3600.00] < 13
There were no recheck events to check.


[030] blood_fury ( cds - 4 ) - ability unknown


[031] lights_judgment ( cds - 5 ) - ability unknown


[032] potion ( cds - 6 ) - ability disabled.


[033] worldvein_resonance ( cds - 7 ) - ability unknown


[034] guardian_of_azeroth ( cds - 8 ) - ability unknown


[035] ripple_in_space ( cds - 9 ) - ability unknown


[036] memory_of_lucid_dreams ( cds - 10 ) - ability unknown
Returned from list (cds), current recommendation is NO ACTION (+60.00).
- cds


[037] call_action_list ( default - 6 )
Criteria PASS at +1.33 - active_enemies[1.00] < 2
Action list (st) was found.
+ st
Current recommendation was NO ACTION at +60.00s.


[038] barbed_shot ( st - 1 )
The action (barbed_shot) is usable at (1.33 + 1.33) with cost of 0.
 - the action is ready before the current recommendation (at +1.33 vs. +60.00).
List ( st ) called from ( Beast Mastery:default:6 ) would PASS at 1.33.
 - active_enemies[1.00] < 2
 - this entry's criteria PASSES: buff.frenzy.up[false] & buff.frenzy.remains[0.00] < gcd.execute[1.33] + barbed_shot_grace_period[0.67] | cooldown.bestial_wrath.remains[87.34] & ( full_recharge_time[0.00] < gcd.execute[1.33] | azerite.primal_instincts.enabled[true] & cooldown.aspect_of_the_wild.remains[120.00] < gcd.execute[1.33] )
Action chosen:  barbed_shot at 1.33!


[039] concentrated_flame ( st - 2 )
The action is not ready before our maximum delay window (15.00) for this query.


[040] aspect_of_the_wild ( st - 3 ) - ability disabled.
The recommended action (barbed_shot) would be ready before the next GCD (1.33 < 1.33); exiting list (st).
Returned from list (st), current recommendation is barbed_shot (+1.33).
- st
The recommended action (barbed_shot) would be ready before the next GCD (1.33 < 1.33); exiting list (default).
Completed default action list [ Beast Mastery - default ].
Recommendation is barbed_shot at 1.33 + 1.33.
Recommendation #4 is barbed_shot at 1.33s (2.66s).

**Comment by Hekili** [comment]
Thanks for the snapshot.  There is apparently an issue where essences are being automatically included via both Use Items and the generic "Heart Essence" ability -- the cast of Concentrated Flame that you're seeing is the generic Heart Essence action.  I'll sort that out.

**Comment by oayorkshireman** [comment]
<3

**Comment by oayorkshireman** [comment]
Hi, I installed the recent update, this still happens tho. in the st it already has a condition
"focus + focus.regen * gcd < focus.max & buff.bestial_wrath.down & ( ! dot.concentrated_flame_burn.remains & ! action.concentrated_flame.in_flight ) | full_recharge_time < gcd | time_to_die < 5"

Should I remove this and add the above condition?

Thanks

Adam
