### ISSUE TITLE
Evoker buff doesn't recognise other evokers buffs.

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#2220]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

If another evoker has blessing of the bronze up hekili will recommend you put yours up.

### How to Reproduce

Have another evoker put buff up and watch your recommendation change.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhTBCAAAAAAKaIJikEJkEJlkk0CSDJSIJEkkkEhkkA

### Snapshot

https://pastebin.com/hY67vwjE

**Comment by yurikenus** [comment]
Looks like this is referencing the correct spell ID for the Evoker version of the buff, but the buff is missing the standard mechanism used by other group buffs:
`shared = "player"`
probably needs to be added into the Aura section of EvokerDevastation.lua.

While there, it may be correct to also remove the reference to `blessing_of_the_bronze_evoker` which is down in the Abilities section for Blessing of the Bronze, as this buff is no longer referenced
`applyBuff( "blessing_of_the_bronze_evoker")`

**Comment by Hekili** [comment]
This should be resolved in the latest release.
