### ISSUE TITLE
Assassination Garrote overwrites empowered garrote

### ISSUE THREAD

**Issue by GarvielTwo** [Hekili/hekili#2221]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello,

Given my current selected talents - due to exsanguinate I suspect  - the addon recommends the following opener : 

Garrote -> Slice and Dice -> Garrote -> Garrote.

The problem is that the 3rd Garrote is not empowered, and essentially overwrites your empowered garrote, killing your damage. I initially thought I was just being slow, however I simply cannot pull off that 3rd garrote in time for it to be empowered. And always have to ignore this recommendation to not overwrite the empowered garrote.

The addon should not recommend the 3rd garrote if it's not feasible to cast it empowered, or if the window is somehow very small due to very small gains vs huge risks. I imagine that it's doing that to set up a larger exsanguinate. Raidbots also only does 2 garrotes in the sim.

Provided snapshots and raidbots links.

Thank you for the awesome addon, hoping to get this small thing fixed!

### How to Reproduce

Use provided talents, enter stealth, go to single target dummy and follow the opener recommendation. Casts poisons before hand etc.

### Talent Loadout

BMQAOB/7AZ//CwQOf4fPMswHVLNJSgIUSAAAAAAAkEAJCAAAAAAgEkmDUSCJJJplkISCJSk4AB

### Snapshot

https://pastebin.com/3LJibA79

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3E2S38whzXMYZvtabTfs2A

**Comment by Hekili** [comment]
I've reduced the Improved Garrote window by 0.05s to try to mitigate this issue.  Let me know if you're still having an issue in 2.0.13; if you do, be sure to supply a new snapshot.  Thanks!
