### ISSUE TITLE
Missing trinkets

### ISSUE THREAD

**Issue by Avarrus** [Hekili/hekili#2222]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

The trinket Voidmender's Shadowgem from Shadow Moon Burial Ground is not all the trinket list.   It is labeled as a healer trinket but happens to be very strong for casters, and bis for shadow priest.

### Contact Information

Aavrus#4798

**Comment by Tzuyume** [comment]
Gift of radiance seems to also be missing.

**Comment by Hekili** [comment]
Voidmender's Shadowgem should be available in 2.0.10.  I'll add Gift of Radiance later.

**Comment by Hekili** [comment]
Gift of Radiance will be in 2.0.11.
