### ISSUE TITLE
Hunter: Fortitude of the bear missing

### ISSUE THREAD

**Issue by Williamn88** [Hekili/hekili#2223]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Sorry was unsure which kind of ticket it should be, but the new defensive Fortitude of the bear for hunter is not in the addon currently.

Here is the BM version grapped with skeleton
    -- Increase the maximum health of you and your pet by 20% for 10 sec.
    fortitude_of_the_bear = {
        id = 272679,
        cast = 0,
        cooldown = 120,
        gcd = "off",
        
        startsCombat = true,
        texture = 571585,
        
        toggle = "cooldowns",

        handler = function ()
        end,
    },
    
    and the MM (lone wolf) version
    -- Increase the maximum health of you and your pet by 20% for 10 sec.
    fortitude_of_the_bear = {
        id = 392956,
        cast = 0,
        cooldown = 120,
        gcd = "off",
        
        startsCombat = true,
        texture = 571585,
        
        toggle = "cooldowns",

        handler = function ()
        end,
    },
    
    I have added them myself and it works fine, but thought maybe it would be better to get it in the official release.
    

### How to Reproduce

Ability not on the ability list

### Snapshot

NA

**Comment by Williamn88** [comment]
Is it possible to get this added ? :)

**Comment by Williamn88** [comment]
Any chance you can get this added in when you are doing the 10.2 stuff also ?

**Comment by marekCs** [comment]
Hey man you can add it yourself to the rotation list and no need to hardcode the Hekili class lua files. If you want I can share you all my class action lists with interrupts and defensive spells in the Hekili rotation. Just tell me which class/spec you need.
