### ISSUE TITLE
At the beginning of the battle, the recommendation with Windfury Totem disappears

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2224]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Before the start of the battle, the recommendations show to put Windfury Totem, but if you start the fight, the recommendation disappears and the addon will ignore Windfury Totem. The totem recommendation will not be shown even if we put it ourselves. The addon will take into account Windfury Totem when it is delivered immediately at the beginning of the battle, then the recommendation will work. 

### How to Reproduce

Start the fight, without Windfury Totem

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJpEJISSISCUSkAAAAAAAAAAAAAQJCRIhQUIRJJJFgSJRSA

### Snapshot

https://pastebin.com/PFzXiBix

**Comment by Hekili** [comment]
This should be resolved in the latest release.
