### ISSUE TITLE
Fury precombat Priority Suggests 'Battle Stance' instead of 'Battle Shout'

### ISSUE THREAD

**Issue by SisrenWarrior** [Hekili/hekili#2225]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The default precombat priority list for Fury lists Battle Stance rather than Battle Shout. At least I assume this is the case, as Fury does not have Battle Stance and the default priority does not suggest Battle Shout.

### How to Reproduce

1. Enter game as fury warrior
2. Use default priorities
3. Battle Shout will fail to be suggested
4. Navigate to Hekili's Fury precombat priority editor
5. Change Battle Stance (second priority) to Battle Shout
6. Battle Shout is suggested when appropriate

### Talent Loadout

BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAIEkgSQQEEiEENChIQkESSaJRSkgQSIRapFgkkEAAAQA

### Snapshot

https://pastebin.com/cJ80BX65

**Comment by Hekili** [comment]
Thanks; I'll make adjustments to account for Battle Shout.
