### ISSUE TITLE
ww monk: only displays 2 icons

### ISSUE THREAD

**Issue by ripmanlosa** [Hekili/hekili#223]
I updated with the latest version, and noticed that only 2 icons were being displayed, when my settings was set to display 4 icons. Also when I try to attack a target the icons disappears and then only one icon is being displayed. 
here is a my character data:
build: v8.2.0-08.10-alpha1
level: 120 (120)
class: MONK
spec: windwalker

talents: ascension
    diffuse_magic
    eye_of_the_tiger
    good_karma
    hit_combo
    tigers_lust
    whirling_dragon_punch

azerite: azerite_empowered=3
    dance_of_chiji=1
    exit_strategy=2
    fury_of_xuen=1
    glory_of_the_dawn=1
    heed_my_call=1
    loyal_to_the_end=1
    on_my_way=2
    open_palm_strikes=1
    pressure_point=1
    resounding_protection=1

essences: [condensed_lifeforce]=3, essence_of_the_focusing_iris=3, the_crucible_of_flame=3

sets/legendaries/artifacts: none

gear:     ashvanes_razor_coral=1
    besiegers_deckstalkers=1
    bilestained_crawg_tusks=1
    blackwater_shimmerscale_vest=1
    claw_of_the_myrmidon=1
    dribbling_inkpod=1
    gloves_of_incomparable_beauty=1
    heart_of_azeroth=1
    hood_of_the_slithering_loa=1
    leggings_of_the_stormborn=1
    overseers_lost_seal=1
    seal_of_questionable_loyalties=1
    servoarm_bindings=1
    ship_swallowers_belt=1
    shoulderpads_of_frothing_rage=1
    sporecallers_shroud=1

itemIDs: 158075, 158314, 158353, 159292, 159318, 159320, 159460, 159653, 168276, 168343, 168348, 168378, 168379, 168887, 169311, 169319

**Comment by Hekili** [comment]
Please submit a complete ticket with the snapshot per instructions. Thanks.

**Comment by Hekili** [comment]
This should be sorted in 10-alpha2, which will be up in a few minutes.
