### ISSUE TITLE
Error every time i login - still exist

### ISSUE THREAD

**Issue by Cionax** [Hekili/hekili#2230]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Message: ...AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:162: Usage: NonEmptyItem:ContinueOnItemLoad(callbackFunction) invalid itemID: <199830>
Time: Mon Jan  2 13:51:27 2023
Count: 1
Stack: ...AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:162: Usage: NonEmptyItem:ContinueOnItemLoad(callbackFunction) invalid itemID: <199830>
[string "=[C]"]: ?
[string "=[C]"]: in function `error'
[string "@Interface/FrameXML/ObjectAPI/Item.lua"]:320: in function `ValidateForContinueOnItemLoad'
[string "@Interface/FrameXML/ObjectAPI/Item.lua"]:329: in function `ContinueOnItemLoad'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua"]:162: in function `Function'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua"]:35: in function `OnUpdate'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua"]:19: in function <...Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:19>

Locals: 

### How to Reproduce

Login into my game with my settings ;)

### Player Information (Link)

```Text
10.0.2. (47213)
```

### Error Messages (Link)

```Text
Message: ...AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:162: Usage: NonEmptyItem:ContinueOnItemLoad(callbackFunction) invalid itemID: <199830>
Time: Mon Jan  2 13:51:27 2023
Count: 1
Stack: ...AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:162: Usage: NonEmptyItem:ContinueOnItemLoad(callbackFunction) invalid itemID: <199830>
[string "=[C]"]: ?
[string "=[C]"]: in function `error'
[string "@Interface/FrameXML/ObjectAPI/Item.lua"]:320: in function `ValidateForContinueOnItemLoad'
[string "@Interface/FrameXML/ObjectAPI/Item.lua"]:329: in function `ContinueOnItemLoad'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua"]:162: in function `Function'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua"]:35: in function `OnUpdate'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua"]:19: in function <...Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:19>

Locals:
```

**Comment by Hekili** [comment]
This is an issue with SpellFlashCore; you would need to report the issue to the developer of that library.

**Comment by Cionax** [comment]
But i dont even use a Addon like this. Doesnt have anyone..

**Comment by Cionax** [comment]
@Hekili it still exist...

**Comment by Hekili** [comment]
> This is an issue with SpellFlashCore; you would need to report the issue to the developer of that library.
