### ISSUE TITLE
Performance settings for all specs

### ISSUE THREAD

**Issue by brett1337** [Hekili/hekili#2235]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

I have had massive multiple second long freezing issues every few minutes for all specs for all my alts in all scenarios (raids, dungeons, solo leveling, standing in valdraken) on hekili for multiple weeks now. I am hoping that throttling the updates in the performance specs will help fix the lagging/freezing I am experiencing. I would like to request a feature that updates all specs (under the same profile or just globally) to share the same performance settings changes.

### Additional Information

I have fully tested that hekili is the only addon causing the issue by disabling all other addons and playing for an hour consistent game freezes, with all other applications on my computer closed. I then disabled hekili, enabled all other addons, played for an hour and never got a single freeze. (I have also reinstalled and deleted addon saved variables). 

I have had some initial luck with throttling updates, but in order to fully confirm it is working it would be a large investment of time to edit every spec for every class. 

### Contact Information

brett1337#9368

**Comment by Hekili** [comment]
I do not plan to approach performance optimization in this way.  Different specs have different levels of load and are intentionally configured individually.
