### ISSUE TITLE
BrM recommends purifying brew off cd even with maximize celestial brew shield toggled OFF

### ISSUE THREAD

**Issue by Posuceius** [Hekili/hekili#2236]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

BrM monk. "maximize celestial brew" setting is toggled off and the addon is still recommending purifying brew off CD even when the settings outlined in my stagger tick % have not been met. i have tried a bunch of different talent builds to see if that would change anything but it's still just recommending i spam purifying brew off cd which is severely hurting my survivability and not allowing me to take full advantage of "Training of the Niuzao" mastery buff.

i have provided 2 pastebin links with the first one being the initial purifying brew charges with celestial brew being used when you take any damage, and the second pastebin link being the addon recommending purifying brew again as soon as it is off cooldown despite having almost no stagger. 
![image](https://user-images.githubusercontent.com/121850404/210310883-256c9f16-e82f-4c7d-a0f5-6d5685a70632.png)
![image](https://user-images.githubusercontent.com/121850404/210310936-f89622b1-2586-4650-ad56-95635030924b.png)
![image](https://user-images.githubusercontent.com/121850404/210311095-12cae354-b882-4457-b085-6d085cf105d1.png)
![image](https://user-images.githubusercontent.com/121850404/210311299-3807cb77-f9cd-4ab4-a299-e64789ca164d.png)

### How to Reproduce

1. log in as a brm monk
2. start attacking something
3. take any form of damage
4. see recommendations
5. waste all of your purifying brews for no reason
6. let purifying brews recharge
7. see recommendations (again)

### Talent Loadout

BwQAdeydY63Y4XKaboK13uRRQAAAAAAAQAAAAAloVSSCIJp0iAAAAkSQSkcgICSSSSKJgISkWKlA

### Snapshot

https://pastebin.com/WksvCsse https://pastebin.com/M3LM4AHm

### Contact Information

Posuceius#5267

**Comment by Hekili** [comment]
That entry carried over from Shadowlands and can be removed/disabled.  It's not related to Celestial Brew, but increasing damage throughput during Niuzao.  Since that is handled elsewhere in the priority now, I'll remove the entry.

(And yes, the entry to be removed is also bad because it doesn't check for the relevant talents before using Purifying Brew for damage throughput.  The new entries do the relevant checking.)

**Comment by Posuceius** [comment]
just so you know for your update, after disabling the 2 entries seen in the screenshots, default entry #30 gets called instead and causes you to spam purifying brew off cd. disabling that entry makes it work correctly based off of how much stagger you have set in the settings.
(top is bad, bottom is good)
![image](https://user-images.githubusercontent.com/121850404/210474506-09989efb-0751-40cf-9eff-5b9ba21db994.png)
![image](https://user-images.githubusercontent.com/121850404/210474438-2f67600a-8a78-4cf0-a71b-55e4a0286b1d.png)

**Comment by Hekili** [comment]
Please just use the actual snapshot feature to show the addon's decision-making process, not the screenshots.  See /hekili > Snapshots.  I'll take a look.

**Comment by Posuceius** [comment]
https://pastebin.com/gG3PXb6s

**Comment by Hekili** [comment]
Thank you!

**Comment by Hekili** [comment]
This should be resolved in the latest release.
