### ISSUE TITLE
The number of charges of Eternity Surge is not displayed correctly Evoker

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2238]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I was testing a new build on evoker and at the moment on 5 dummies, I started to show the wrong charging capacity value. It showed not the number 3 but the number 1.

### How to Reproduce

Approach the dummies and start rotating in AOE.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAooFSiIJkQSkUSSSLItQiESCBJJSkDIJJ

### Snapshot

https://pastebin.com/WrZYeH41

**Comment by Hekili** [comment]
There is an experimental change in place for Evoker that *might* address this, but it's a subtle issue.  If you see this happening in 2.0.13 and later, please try to supply pre/post snapshots for investigation purposes.  Thanks.
