### ISSUE TITLE
Demon hunter glaive tempest issue

### ISSUE THREAD

**Issue by salutre** [Hekili/hekili#2239]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my havoc DH, I expect the addon to recommend Glaive Tempest when I'm the closest to my ennemies. However, the addon sometimes recommend to use Fel Rush then Glaive Tempest right after, which is the worst scenario. 

As a solution i recommend to not suggest fel rush / vengeful retreat right before glaive tempest 

(I've made a snapshot but my game is in french) 

### How to Reproduce

1. Enter game as Havoc Demon Hunter
2. Use the talent loadout
3. Follow recommendation and notice Heikili suggesting fel rush then glaive tempest

### Talent Loadout

BEkACnvaHJn8GSPD6tpaeczPThASiUC0SSSSCKJBAAAAAAQLSgWKSSCISaJpIJRSSC

### Snapshot

https://pastebin.com/VX1xpwnE

### Contact Information

Discord : Ezrheal#8344

**Comment by Hekili** [comment]
Could you provide a Raidbots sim of your character?

**Comment by salutre** [comment]
unfortunately i'm very unfamiliar with simulations
