### ISSUE TITLE
Infinite error regarding null index of condensed lifeforce

### ISSUE THREAD

**Issue by Falaenx** [Hekili/hekili#224]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

Endless errors
3620x [string "-- Unholy:default:8 recheck..."]:2: attempt to index field 'condensed_lifeforce' (a nil value)
[string "-- Unholy:default:8 recheck..."]:2: in function `Recheck'
Hekili\State.lua:1308: in function `recheck'
Hekili\Core.lua:704: in function `GetPredictionFromAPL'
Hekili\Core.lua:1017: in function `GetNextPrediction'
Hekili\Core.lua:1186: in function `ProcessHooks'
Hekili\UI.lua:804: in function <Hekili\UI.lua:668>

Locals:
(*temporary) = 0
(*temporary) = 3620
(*temporary) = 0
(*temporary) = 3600
(*temporary) = nil
(*temporary) = "attempt to index field 'condensed_lifeforce' (a nil value)"

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

Always on current patch

**Expected behavior**
Nothing at all

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Submit the rest of the info

**Comment by Hekili** [comment]
I'm not able to replicate this on my end.  I need the rest of the requested information from the bug report template, especially the information from your Issue Reporting tab.

**Comment by Falaenx** [comment]
Sorry for not providing enough info.  I did resolve the issue myself but I had to completely remove the add on and any settings files from my folders.  A fresh reinstall remedied the issue.  My guess was it was either a bad simcraft profile on my part or a mixed bit of code from swapping alpha and release versions.  

You may close this ticket and thank you for this addon!
