### ISSUE TITLE
Skill order reset and broken in devestation evoker.

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#2241]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After the update to fix the non-display issue, it reset my icon count to 3 from 2 and reversed the skill order putting 1st on left again.  I'm unable to fix it with the left/right growth as expected.

### How to Reproduce

update hekili to the latest release as of 2100 3Jan23 CST

### Player Information (Link)

```Text
build: v10.0.2-2.0.11
level: 70 (70)
class: EVOKER
spec: devastation

talents: animosity
    arcane_intensity = 2/2
    attuned_to_the_dream = 2/2
    azure_essence_burst = 1/1
    blast_furnace = 2/2
    causality = 1/1
    cauterizing_flame = 1/1
    charged_blast = 1/1
    dense_energy = 1/1
    draconic_legacy = 2/2
    dragonrage = 1/1
    enkindled = 2/2
    essence_attunement = 1/1
    eternity_surge = 1/1
    eternitys_span = 1/1
    extended_flight = 2/2
    fire_within = 1/1
    focusing_iris = 1/1
    font_of_magic = 1/1
    forger_of_mountains = 1/1
    heat_wave = 2/2
    hoarded_power = 1/1
    honed_aggression = 1/2
    imminent_destruction = 1/2
    innate_magic = 2/2
    inner_radiance = 1/1
    landslide = 1/1
    leaping_flames = 1/1
    lush_growth = 2/2
    natural_convergence = 1/1
    obsidian_bulwark = 1/1
    obsidian_scales = 1/1
    panacea = 1/1
    permeating_chill = 1/1
    power_swell = 1/2
    protracted_talons = 1/1
    pyre = 1/1
    quell = 1/1
    renewing_blaze = 1/1
    ruby_embers = 1/1
    ruby_essence_burst = 1/1
    scintillation = 2/2
    shattering_star = 1/1
    sleep_walk = 1/1
    spellweavers_dominance = 1/1
    tailwind = 1/1
    terror_of_the_skies = 1/1
    tip_the_scales = 1/1
    tyranny = 1/1
    unravel = 1/1
    volatility = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: [dreamweaver]

sets: none

gear: azure_arcanic_amplifier = 1
    calamitous_shockguards = 1
    circle_of_ascended_frost = 1
    flametouched_treads = 1
    gilded_dracthyrs_tabard = 1
    heart_of_azmerloth = 1
    icewraths_channeling_conduit = 1
    koroleths_crackling_dagger = 1
    ohnahran_falconers_chainmail = 1
    ohnahran_falconers_cinch = 1
    ohnahran_falconers_coif = 1
    ohnahran_falconers_greaves = 1
    ohnahran_falconers_shoulderguards = 1
    petrified_bracelets = 1
    platinum_star_band = 1
    shroud_of_raging_tempests = 1
    windsealed_mana_capsule = 1

legendaries: none

itemIDs: 191997, 192000, 192001, 192002, 192003, 193421, 193687, 193708, 193731, 194675, 195210, 195484, 195531, 198407, 199452, 200740, 200880

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxTime = 10
    nameplateRange = 35
    nameplates = false
    noFeignedCooldown = false
    package = Devastation
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    use_clipping = false
    use_deep_breath = true
    use_early_chain = false
    use_unravel = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    azure_strike      = 4   [01]
    cauterizing_flame = E   [05]
    deep_breath       = 2   [01]
    disintegrate      = 3   [01]
    dragonrage        = F3  [06]
    emerald_blossom   = Q   [05]
    eternity_surge    = F4  [06]
    fire_breath       = 6   [01]
    hover             = `   [10]
    landslide         = F6  [06]
    living_flame      = 1   [01]
    obsidian_scales   = F2  [06]
    oppressing_roar   = -   [01]
    pyre              = 5   [01]
    quell             = F1  [06]
    shattering_star   = G   [06]
    tail_swipe        = BkSp[06]
    time_stop         = 7   [01]
    tip_the_scales    = F5  [06]
    unravel           = 8   [01]
    wing_buffet       = =   [01]

warnings: none
```

### Error Messages (Link)

```Text
no error message
```

### Additional Information

![image](https://user-images.githubusercontent.com/1850089/210480752-a2d965e3-cd5f-442e-acbc-f398837e6bcf.png)

**Comment by N6REJ** [comment]
looks like uninstalling and reinstalling hekili fix it.. closing for now

**Comment by N6REJ** [comment]
nope, its still bugged... even thought its set to right-right, its going right left

**Comment by Hekili** [comment]
That screenshot is showing your Primary display while you're adjusting settings for your AOE display.

**Comment by N6REJ** [comment]
they are both the same now and the same thing happens.
![WoWScrnShot_010423_205822](https://user-images.githubusercontent.com/1850089/210691421-01be43d7-923c-4343-ba76-caacd7b94c61.jpg)

**Comment by Hekili** [comment]
It's fundamentally a mistake to stack the displays on top of each other and is likely causing you some confusion.  Take a snapshot and put it on Pastebin, then link it here so we can see the order of the addon's recommendations.

**Comment by N6REJ** [comment]
primary: https://pastebin.com/2vDVeUsD
AOE ( which I never use ) https://pastebin.com/TEuK5HyP
I moved the aoe
![image](https://user-images.githubusercontent.com/1850089/211128397-7427c5a7-b052-4266-a0c6-397fdd59aa89.png)
on primary

**Comment by N6REJ** [comment]
Another issue with this ( didn't happen till last update ) is "Dragonrage" was NEVER suggested the entire raid.

**Comment by Hekili** [comment]
> Another issue with this ( didn't happen till last update ) is "Dragonrage" was NEVER suggested the entire raid.

In your snapshot, cooldowns are toggled off.  Dragonrage is not going to be recommended when cooldowns are toggled off.

In your Primary snapshot there, the first spell is Blessing of the Bronze, the second spell is Living Flame.
> Devastation; Primary - Blessing of the Bronze(0.00), Living Flame(1.28)

Your queue is anchored to the right side of the primary icon, growing right:
![image](https://user-images.githubusercontent.com/9438134/211227507-b6fe3cf0-2a3a-4989-a590-582523278857.png)

So the picture shows exactly what I'd expect to see here.

**Comment by N6REJ** [comment]
you missed the most important point and that is the 1st skill is on the left not the right.
