### ISSUE TITLE
Puzzle box not used after precombat for Fury

### ISSUE THREAD

**Issue by SpencerMalone** [Hekili/hekili#2242]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Puzzle box is not being recommended after the initial precombat use for me. It should be recommended to align w/ CDs per https://github.com/simulationcraft/simc/blob/ceb8dbc07e3bd505fd7c0008bd13e08d8ec15c05/engine/class_modules/sc_warrior.cpp#L8556-L8557

### How to Reproduce

1. Have a puzzle box
2. Be playing fury warrior
3. Precombat use puzzle box
4. Do combat for 3 minutes
5. Notice no puzzle box use is recommended

### Snapshot

https://pastebin.com/ZDhketkJ

**Comment by Hekili** [comment]
Good catch; this will be resolved in the next release.
