### ISSUE TITLE
Outlaw - Blade Flurry recommended with 1 or 0 enemies

### ISSUE THREAD

**Issue by glowpipe** [Hekili/hekili#2243]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

As an outlaw rogue, when fighting one mob or not even near a mob, like in a town with no attackable mobs, blade flurry is recommended as a priority. This happens in both Auto, single and AOE mode.

### How to Reproduce

1: Enter game as Outlaw.
2: Look at hekili addon
3: ??
4: Profit

I haven't done anything special here. It always recommend Stealth, adren rush, roll the bones then blade flurry. Nothing specific i am doing to get it this way

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAUSEEBJJJJkIJJSSgEJSAkIAAAAAAAJJkmUSCSSkWAAAA

### Snapshot

https://pastebin.com/Kd8GNTEt

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jEcJpgLTXH7pJV3ogsbczg

### Additional Information

Since it is recommending blade flurry in single target or no target, the raidbot sim is from patchwerk.

This one here is for Hectid add cleave VVVV
https://www.raidbots.com/simbot/report/dyUJsNr9DacUxJnkTi3QXW

**Comment by Hekili** [comment]
Your priority appears to have been modified (as discussed briefly in Discord).  The first entry in the `default` action list should be Stealth, not Blade Flurry.  You can reset the priority by clicking the reset button to the right of the Priority Name:

See:
![image](https://user-images.githubusercontent.com/9438134/210629232-66b0e790-931d-4663-be97-23827cb703d5.png)

Click:
![image](https://user-images.githubusercontent.com/9438134/210629268-f1bc091f-6354-48a2-921f-af4fd257ae30.png)
