### ISSUE TITLE
Marksmanship Priority Issue when using Hydra's Bite

### ISSUE THREAD

**Issue by Keepoo** [Hekili/hekili#2244]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When using the talent Hydra's Bite in combination with Serpentstalker's Trickery ( i havent tested it without SS trickery) Hekili is recommending to use serpent sting to spread the dot, however this is wrong as you would try to aimed shot to apply the serpent sting and then multidot using aimed shots.

### How to Reproduce

1) Select talent Hydras Bite
2) Select Talent Serpentstalkers Trickery
3) Go to Target Dummy, play the rotation as it is recommended
4) Serpent Sting will be recommended
Note : Disabling Serpent Sting in abilities works  however im not sure about conflicting issues in priority etc.
Also if possible would it be possible to make a functioning recommended target swapping option for MM/BM hunters as unfortunately right now when playing with Serpentstalkers Trickery, it is not recommending to swap targets to Multi-Dot Serpent Sting through Aimed Shots.

### Talent Loadout

B4PAIlFMjeNhnEouGfV8Ij2uS5ARoFASCCCAAAAQkERSSi4ACRSLkGRQTKaCJJhESoBAAAAA

### Snapshot

https://pastebin.com/tsfQAQXY

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/56Q2KcfouSTXha5dGgPvbf

### Additional Information

On that Note would it be possible to make a functioning recommended target swapping option for MM/BM hunters as unfortunately right now when playing with Serpentstalkers Trickery, it is not recommending to swap targets to Multi-Dot Serpent Sting through Aimed Shots, however this is optimal and therefore should be recommended. Same Thing with Barbed Shot for BM Hunters, multidotting the barbed shot is optimal however not supported through the addon. Thank you.

### Contact Information

Trancendence#8723 (discord)

**Comment by Hekili** [comment]
Thanks, the check in the priority list for Serpentstalker's Trickery will be in the next release (which will stop the Serpent Sting recommendation consistent with SimC).

The Serpentstalker's Trickery talent should also enable target cycling recommendations in the next release.
