### ISSUE TITLE
Mana Gem not listed as an item or ability (arcane mage)

### ISSUE THREAD

**Issue by vleermuisman** [Hekili/hekili#2245]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

I would like to be able to make changes to mana gem (I looked over abilities and the item list over 10 times now, hope I am not blind). Conjure mana gem is there, but the changes i want to make are similar to other abilities/items ex disable

**Comment by Hekili** [comment]
It is already at the very end of the Gear and Items list.
