### ISSUE TITLE
Outlaw rogue priority bugs when switching from Assasination

### ISSUE THREAD

**Issue by GreamDesu** [Hekili/hekili#2246]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello,
The priority for outlaw rouge bugs and shows that  I should apply other two poisons as well (but it is not possible) and I suspect it happens after I switch from assassination rouge spec, which has a talent that allows applying 4 poisons. It starts working again after interface reload only and is kinda annoying.

### How to Reproduce

1. Enter a game as Assassination rouge with Dragon-Tempered Blades talent
2. Switch spec to Outlaw rouge
3. Enjoy (not)

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRiIJJJhAAAAAAAEJJaSJJgEaBAAAA

### Snapshot

https://pastebin.com/u4VVK5SH

**Comment by Hekili** [comment]
Thanks, this will be fixed in the next release.
