### ISSUE TITLE
Flame Shock is being advised when it's already on the target in AoE situations (not using filler FS mode)

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#2248]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Flame shock is being recommended in AoE on a target that already has flame shock for at least 10 more seconds, other abilities are available and filler FS is deactivated

### How to Reproduce

Playing enhancement shaman, leveling lvl 69, AoE pull following AoE rotation

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IRSaBIJJhIJkUSkAAAAAAAAAAAAAgIEhECB4AlEJtQARSIB

### Snapshot

https://pastebin.com/GCmr6uek

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6vEGkC7jfkXVsFXB65nw3d

### Additional Information

Happened to me multiple times when flame shock was already on the target(s) and target swap / FS filler weren't activated. 

### Contact Information

Nibana#6011

**Comment by Amortalist** [comment]
Here is another snapshot using phys m+ build at level 70 during a timewalking dungeon where the same thing happen : https://pastebin.com/Q68QJfJB

Build is : BcQAfcj78nJtvjmejSqe5Zhm9IRSaQSiIJCIJtEJAAAAAAAAAAAAAUiQES0CRBSJJJFAlEJBK 
Raidbots for 5 target 40s : https://www.raidbots.com/simbot/report/agoDJhyJWSt5SB8TP6AsoK

**Comment by Hekili** [comment]
The target cycling entry for Flame Shock will check that your current target doesn't have Flame Shock in the next release.
