### ISSUE TITLE
Battle shout suggested when aura is present from another warrior

### ISSUE THREAD

**Issue by coanarcanius** [Hekili/hekili#2249]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When partied with a warrior, when they have battle shouted, I get the suggestion to battle shout. This suggestion will go away if I cast battle shout instead. This is with default arms warrior priority, I have not tested with other specs. 

### How to Reproduce

1) be in a party with another warrior
2) have the other warrior cast battle shout

### Talent Loadout

BcEAR5QSZgdnGefDo4ho9ZGXKDARikkkQSSKlkEAAAAQQEJtCJAROAkkEEaSECAECAAAAAAAACIHAAA

### Snapshot

https://pastebin.com/BGdZWmjV

### Additional Information

This character is over 60, but not 70, unsure if that would affect the suggestions, this was happening both in town and in timewalking. Unsure if that would affect things, but the buff is the same regardless. 

### Contact Information

coan#0001

**Comment by dubudevs** [comment]
Same behaviour with other raid buffs.

**Comment by Hekili** [comment]
@coanarcanius If this wasn't already fixed in 2.0.12, it will be fixed in the next release.

> Same behaviour with other raid buffs.

@dubudevs You can let me know about specific raid buffs that get re-recommended.  Battle Shout was being overwritten by an anima power; the same doesn't apply to any other buffs.  If you share specifics, I can take a look.
