### ISSUE TITLE
Dev evoker Essence Burst proc from Leaping Flames empowered Living Flame is not predicted

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#2251]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

https://pastebin.com/G3xw3CiY
https://pastebin.com/eLWjEhCV

When Dragonrage is active Living Flame and Azure Strike have a 100% chance to give a proc of Essence Burst.
When you have Leaping Flame talented your Living Flame will dupicate to multiple targets. Every one of these can give a proc of Essence Burst. With the Burnout talent Living Flame is the preferred button to press to gain Essence Burst because it does the most damage, and can grant 2 stacks.

NB: Multiple hits of Azure Strike give only 1 Essence Burst (there was a comment asking this in the .toc)

My first snapshot is recommending I cast Living Flame twice, to generate 2 stacks of Essence Burst to spend on Disintegrate. I only need to cast 1 time to get 2 stacks, because I have Leaping Flame active. 

The second snapshot is after I press Living Flame showing I have 2 stacks.

Sims don't show this behaviour, because a Living Flame needs to actually deal damage or heal (it can jump to allies) to grant a stack. This is almost always going to happen in game, but in a ST sim it wont happen because you are full HP and there is only 1 boss.

### How to Reproduce

Enter game with Leaping Flame, Dragonrage, Burnout, Feed the Flames talents (very standard for all content).
Dragonrage>Fire Breath>Press buttons until you have 2 charges of Burnout and 0 Essence Burst

Recommendations will be Living Flame>Living Flame>Disintegrate

Press Living Flame (near either an ally who is not 100% hp or an enemy, the range is very big) and note you get 2 stacks of Essence Burst and recommendations will drop the 2nd LF.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhTDCAAAAAAKaIJikDkkQSkUSSig0CJJhkEIJJSkDQSC

### Snapshot

https://pastebin.com/G3xw3CiY

### Contact Information

dubu#2080

**Comment by Hekili** [comment]
I'll adjust Living Flame to generate 2 stacks of Essence Burst when Dragonrage is active and Leaping Flames is up, if any of the following:
* There are 2 or more enemies
* You're in a group (will assume someone can get healed)
* Your health is less than 100%

If this doesn't seem to model consistently (i.e., assuming you'll have 2 stacks at times when you won't actually generate them), let me know.

Also, FWIW, you can damage yourself and your raid in SimulationCraft with a `raid_events+=/damage,amount=20000,cooldown=10` line to possibly help model this in SimulationCraft.  But we'll see how this edit goes.

**Comment by dubudevs** [comment]
Even without leaping flames, going LF>Dis>LF>Dis is not worse than going LF>LF>Dis>Dis, so even in the case that it does only give 1 charge when 2 are expected the rotation wont change and dps will be effectively identical. Before that would be a potentially  wasted EB, though. Thanks for the update.

**Comment by dubudevs** [comment]
Coming back to this, when you are in single-target mode it is again recommending double Living Flame even when there are multiple enemies. This is expected (but incorrect), because you're in single target mode so it only sees 1 enemy, but the behaviour should be the same since you're still getting the procs. Unsure whether its viable to change this.
