### ISSUE TITLE
Arcane: Phase changes occurring w/o TotM being cast

### ISSUE THREAD

**Issue by F074** [Hekili/hekili#2252]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The priority fails to use touch of the magi in some scenarios completely missing burn phases. Not entirely sure what I'm doing wrong if anything. 

### How to Reproduce

1. Fight 5 stack target dummies.
2. Cooldown mode enabled
3. Complete initial main burn phase
4. priority will suggest spark/surge for next big burn phase
5. totm will not be recommended afterward

### Talent Loadout

B4DAHVkVsxxZrVqBmAzlSR2f7LJChWiESSDEtkIiISiESolg0SCAAAAAAAAAAAgkkkESSSiA

### Snapshot

https://pastebin.com/uhVvx7ZF

### Additional Information

Priority seems to fail criteria even more often in "real-world" dungeon scenarios, but can still happen on target dummies. Not sure why that is.

**Comment by F074** [comment]
This is a snapshot of a single target rotation failing to get into touch phase. (Original is multi-target)

https://pastebin.com/uUNxQtch

The snapshot reads ToTM up = false which I assume mean the priority thinks ToTM is still on CD but its not. Correct me if I'm wrong.

**Comment by F074** [comment]
I went back to nameplate detection targeting and the burns are consistent. Could that be the issue?

**Comment by Hekili** [comment]
> I went back to nameplate detection targeting and the burns are consistent. Could that be the issue?

Unlikely, but if there's additional data you should snapshot it and link it.

> The snapshot reads ToTM up = false which I assume mean the priority thinks ToTM is still on CD but its not. Correct me if I'm wrong.

No, it doesn't mean that.

**Comment by Hekili** [comment]
It looks like you've disabled abilities in the priority.  If you supply more snapshots, be sure to reset to the default priority first.

**Comment by F074** [comment]
Reset all toggles to default. I got this failed touch phase.

https://pastebin.com/B7ueBXMy

**Comment by Hekili** [comment]
I've added some flexibility to the phase changes for Arcane; the priority as written should be using TotM before exiting the phase, but it isn't built into the priority logic.  I've added it.  Let me know if this is resolved for you in 2.0.13.  If not, please provide new snapshots, specifically when:

1. It's not entering a spark phase but it should be.
2. It has exited a spark phase without recommending TotM first.

Thanks!

**Comment by Hekili** [comment]
Please advise whether you've noticed any improvement in 2.0.14 or later.  If you have new examples of finishing your spark phase without TotM getting cast, please provide an updated snapshot.  Thanks!

**Comment by F074** [comment]
I tried it out. There are improvments going into spark&touch phase, but I still got some hang ups with touch phase and the addon not recommending totm. I got weird behavior where it would just spam Arcane Blast constantly after entering spark phase and nothing else. 

https://pastebin.com/Yd7rpGPP
https://pastebin.com/PHEEJU1N
https://pastebin.com/71Qf2R2U
https://pastebin.com/QC5z5ZUa

I know it will say I disabled some abilities in the toggles. All I did is set some abilites in cooldown mode only and all these snapshots were taken in cooldown mode. So essentially no abilities were toggled off or disabled during this gameplay.

**Comment by F074** [comment]
I'm finding it hard to duplicate what I saw in those snapshots of a real dungeon on target dummies. On the dummies everything works fine. Is it possible this is a TimeToDie issue affecting the priority when I targeted a mob that the priority thought would die soon? Is that something it takes into consideration? If so I would prefer it ignore that entirely and I be able to toggle CDs myself.

Also, I have another question regarding whether or not I will mess up the priority if I'm ranged and hitting multi targets. The priority requires you to use Arcane Explosion at some points during the conserve phase and sometimes during touch phase when you don't have missile procs. The problem with that is the priority will never recommend arcane explosion if you're not in melee range. Regardless of how many targets the addon detects. -- So, is the priority designed specifically to ALWAY be in melee range or is that a bug? I'd think I would prefer the priority to tell me to use arcane explosion even I'm not within range and the addon detects multi targets. Then I'd just have to move back in melee range when it said this.

Thanks and let me know what you think.

**Comment by Hekili** [comment]
You don't have to duplicate it on target dummies, just take the snapshot in a dungeon. You can copy the snapshot to post any time up until you reload your UI.

Arcane Explosion only being recommended when in range was added as a user request a while back. I agree with how you feel about it, so I may turn it into a spec preference if I haven't done so already.

**Comment by Hekili** [comment]
From the first snapshot, it looks like the issue is that Arcane Barrage didn't happen before Radiant Spark Vulnerability fell off; TotM requires Arcane Barrage used as the previous ability here. 

I'm traveling now so I won't be able to work on it until Saturday at the earliest, but my guess is that if you cast Arcane Barrage here, TotM will be recommended and the addon will exit the spark phase successfully.

**Comment by F074** [comment]
> From the first snapshot, it looks like the issue is that Arcane Barrage didn't happen before Radiant Spark Vulnerability fell off; TotM requires Arcane Barrage used as the previous ability here.
> 
> I'm traveling now so I won't be able to work on it until Saturday at the earliest, but my guess is that if you cast Arcane Barrage here, TotM will be recommended and the addon will exit the spark phase successfully.

Those 4 new snapshots are all from a dungeon. There’s a good chance they all might be user error which is good to hear. Let me know if the rest are like that and what I did wrong in them.

**Comment by F074** [comment]
> From the first snapshot, it looks like the issue is that Arcane Barrage didn't happen before Radiant Spark Vulnerability fell off; TotM requires Arcane Barrage used as the previous ability here.
> 
> I'm traveling now so I won't be able to work on it until Saturday at the earliest, but my guess is that if you cast Arcane Barrage here, TotM will be recommended and the addon will exit the spark phase successfully.

That’s good to hear. The 4 new snapshots are all from a dungeon so they might all be user error. Let me know what you find in the rest of them and what I did wrong. 

And the arcane explosion in ranged thing. Can I turn that on on my end or is something you have to change? Thanks.

**Comment by Hekili** [comment]
> That’s good to hear. The 4 new snapshots are all from a dungeon so they might all be user error. Let me know what you find in the rest of them and what I did wrong.

My comment wasn't saying it was user error at all.  Did you try casting Arcane Barrage and seeing if that kickstarted the recommendation for TotM?

> And the arcane explosion in ranged thing. Can I turn that on on my end or is something you have to change? Thanks.

Just to confirm, you want the addon to tell you to use Arcane Explosion when you won't actually hit anything with Arcane Explosion.  Is that accurate?

**Comment by F074** [comment]
Yes and Yes. Casting Arcane Barrage did kickstart the prio to use ToTM and I would like the prio to tell me to use Arcane Explosion even if I won't hit anything.

**Comment by Hekili** [comment]
If this issue persists with the latest version, new snapshots will be needed.  Feel free to comment and I'll reopen if needed.
