### ISSUE TITLE
Ignores the Primordial Wave in AOE again.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2253]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Being in a battle with 5 targets, I first pressed Feral Spirit, then pressed Primordial Wave and adon suggested that I press Lava lash in order for Flame Shock to hang itself on other targets. But after Lava lash, there was no recommendation to use Lightning Bolt to activate the Splintered Elements talent. And the recommendation was used by Chain Lightning. Is it still possible to make a point binding by priority in AOE so that rotation always strictly follows such a condition as in the screenshot ? If we do not fulfill this condition in aoe as in the screenshot, we will not receive 50% of the speed from the Splintered Elements talent. We are obliged at the beginning of the battle to first get a % speed buff, and after that everything else.![image](https://user-images.githubusercontent.com/63850853/211158865-402ffb8d-d628-41a3-b1a6-083fe9c5c511.png)

### How to Reproduce

1. Start the AOE 8 targets battle.
2. Use Feral Spirit
3. Use Primordial Wave on the selected first target.
4. Use Lava lash spread Flame Shock.
5. And there will be no Lightning Bolt recommendation here.
6. It will be suggested to use Ice Strike, after Frost Shock, and Chain Lightning will be used for the place of Lightning Bolt.

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IRSKRCCJhIJJUSkAAAAAAAAAAAAAQJCRIJCRBSJJJFAlEJBA

### Snapshot

https://pastebin.com/7aHsiw2V

### Additional Information

I really ask you to please correct the priority in AOE. You can add a condition for an additional goal to use Flame Shock so that we can get a maximum speed gain of 60% of the buff for a place of 50% of the speed buff, since 6 targets will be affected by lightning. It doesn't make sense to use more Lava lash for many purposes, since we need to get %buff as quickly as possible so that we have a huge increase in speed to quickly use further rotation priority. I hope for your help. Thanks.

**Comment by Hekili** [comment]
You do not have the Primordial Wave buff in your snapshot.  Is that not correct?  Did you take the snapshot at the wrong time?

> 5. And there will be no Lightning Bolt recommendation here.

Lightning Bolt would've been recommended in your snapshot if Primordial Wave were up on you.

<details>
<summary>27.  lightning_bolt ( aoe - 2 )</summary>
( active_dot.flame_shock[5.00] >= active_enemies[5.00] | active_dot.flame_shock[5.00] > 6 ) & **buff.primordial_wave.up[false]** & buff.maelstrom_weapon.stack[10.00] >= ( 5 + 5 * talent.overflowing_maelstrom.enabled[true] ) & ( ! buff.splintered_elements.up[false] | fight_remains[534.44] <= 12 | raid_event.adds.remains[534.44] <= gcd.max[1.22] )
</details>

> I really ask you to please correct the priority in AOE. You can add a condition for an additional goal to use Flame Shock so that we can get a maximum speed gain of 60% of the buff for a place of 50% of the speed buff, since 6 targets will be affected by lightning. It doesn't make sense to use more Lava lash for many purposes, since we need to get %buff as quickly as possible so that we have a huge increase in speed to quickly use further rotation priority. I hope for your help. Thanks.

I don't need this additional information; please don't try to sell me on changes (unless you're supplying sim comparisons you've made).  The only issue here is that you don't seem to have the Primordial Wave buff on yourself in your snapshot.  Let me know if that's accurate; feel free to provide another snapshot when you know you have the Primordial Wave buff.
