### ISSUE TITLE
Windfury Totem Being Prioritized over all other Abilities

### ISSUE THREAD

**Issue by Trnxx** [Hekili/hekili#2254]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

On my Enhancement Shaman, Windfury Totem is being prioritized over all other actions once remaining duration < 30 seconds. Will be recommended at 30 seconds remaining even with entry 36 "Windfury Totem buff remains <30" disabled.

![image](https://user-images.githubusercontent.com/122181534/211171169-22a8c1e4-3f7b-4969-99a3-014efd1094f4.png)

### How to Reproduce

1. Enter Game as Enhancement Shaman
2. Choose Windfury Totem as a talent
3. Place Windfury Totem and enter combat with enemy or training dummy
4. Wait until remaining duration on Windfury totem is <30 seconds
5. Windfury totem will be recommended before any other action, including wolves, trinkets etc., instead of correctly when no other priority is available.

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJHAkcARSSSQSiECAAAAAAAAAAAAAlIEhE0EQSJJJlDABRSgC

### Snapshot

https://pastebin.com/VY0ScivF

### Raidbots Sim Report (Link)

(https://www.raidbots.com/simbot/report/vFFvXfHHqQT9qMDmENydxd)

### Contact Information

DAN#5661

**Comment by iNupidstoob** [comment]
That's according to the APL: https://github.com/simulationcraft/simc/blob/dragonflight/profiles/Tier29/T29_Shaman_Enhancement.simc#L136

**Comment by Hekili** [comment]
In this case, it's the `precombat` entry firing when that should fall to the filler entry or only be used out of combat.  I'll update it in the next release.
