### ISSUE TITLE
Misunderstanding re: cooldowns of abilities that are toggled off

### ISSUE THREAD

**Issue by pefcs** [Hekili/hekili#2256]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The cooldown.ability.remains only shows the total cooldown, not the remaining cooldown, thus you cannot create a condition which only triggers when the cooldown remains is higher/lower than a threshold.

Only checked with Guardian druid, might affect other classes, specs.

### How to Reproduce

1. Enter the game as Guardian druid
2. Check a priority where you set an ability with cooldown.remains - issue happens at least with Incarnation, Renewal and Rage of the Sleeper. Should show 0, but shows the total cooldown of the ability - NOK

With Mangle and Thrash_bear it's even weirder. When off CD, it shows it's cooldown as -51164, when it's on Cooldown it shows 0 - haste calculation mistake maybe?
3. Use the ability
4.  cooldown.ability.remains still shows the max cooldown (or 0 with Mangle and Thrash)

### Talent Loadout

BgGAYhlYdy9RJ6ROrphOEi69vCAAAAAAAAAAAAASEJJpkokkkEJQQShiAICCSgkkEJJSBa4AAAAAAAEBE

### Snapshot

https://freeimage.host/i/H5G0eRf

### Additional Information

On the linked image you can see the shown value of the cooldown.ability.remains and in the bottom the real cooldown. I checked if it's only a UI issue, but unfortunately the calculation considers it to be shown even when the cooldown isn't in the threshold.

**Comment by Hekili** [comment]
Abilities that are toggled off have their cooldowns artificially set to the maximum duration.  That explains Incarnation, Renewal, Rage of the Sleeper, etc.

> Snapshot
> [freeimage.host/i/H5G0eRf](https://freeimage.host/i/H5G0eRf)

A snapshot is not a screenshot.

> With Mangle and Thrash_bear it's even weirder. When off CD, it shows it's cooldown as -51164, when it's on Cooldown it shows 0 - haste calculation mistake maybe?

What?  Can you post a snapshot of specifically what you're describing?  Mangle and Thrash (Bear) aren't on any particular toggle; where are you seeing this?

I'll add the Snapshot instructions below (they were in the original ticket instructions).

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by pefcs** [comment]
Ah, I missed that checkbox. Checking - Cooldown: Show Separately - Use Actual Cooldowns solved every issues mentioned above.
Thanks for your help!
