### ISSUE TITLE
Visibility Recommendation - Load Only in Specific Circumstances

### ISSUE THREAD

**Issue by RogerRabbit10** [Hekili/hekili#2258]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

I would like to ask that the overlay feature be designed with visibility toggles, for example if I am in a rested area (city/inn etc) I don't want it to display because I might be mogging my character or doing other non combat related activities.

if possible behave similarly to weak auras with their load commands (not in a pet battle, vehicle etc)

### Additional Information

this matter was recently discussed in the general tab of discord

### Contact Information

Discord lilith#6234

**Comment by mariogusman** [comment]
I believe this is already a feature? Unless you mean a different thing.
Here on my end I configure it to only become visible if **in combat and with a target**.

![image](https://user-images.githubusercontent.com/32820265/235367216-12bfb426-b293-4fb9-bf6d-e194d77404ed.png)
