### ISSUE TITLE
Cancelaura Starlord being recommended

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [Hekili/hekili#226]
As far as I'm aware however this is no longer a useful thing to do, there is a clear consensus in the Balance discord community but it's still being shown in the rotation. I don't however know how I can disable this element, so if that's impossible perhaps consider removing it.

**Comment by Hekili** [comment]
It does appear marginal in current sims in current gear, but folks not in current raid gear probably benefit from the canceling.

I'll consider adding it as a spec option so that you don't have to edit your priority yourself.
