### ISSUE TITLE
Roll the Bones suggested on cooldown

### ISSUE THREAD

**Issue by chevyn11** [Hekili/hekili#2260]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Roll the bones is being suggested on cooldown. It should not suggest roll the bones while skull and crossbones is up. Attached snapshot of roll the bones being suggested while skull and crossbones is still up for another 19 seconds. 

According to reroll logic from outlaw discord:
- Roll away any single buff that is not SnC.
- Roll away any 2 buff combination that contains GM except for SnC + GM.

This is supported by the attached simc report (SNC stays up/ isnt rerolled for ~38 seconds)

### How to Reproduce

Enter game as Rogue
hit dummies according to suggestions
Roll the bones will be suggested everytime it comes off cooldown

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQkkoJlkASQAAAA

### Snapshot

https://pastebin.com/jxPv746N

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pLqNhCeRsBFbMRB9MLauUi

### Contact Information

chevyn#4512

**Comment by Hekili** [comment]
Thanks.  I'm posting 2.0.13a right now which (partially) mitigates this and adds more information to snapshots for troubleshooting.  If you see a reroll that seems wrong with 2.0.13a installed, please grab a fresh snapshot and link it here.

**Comment by Hekili** [comment]
I've released 2.0.13b which should do a better job of identifying which buffs can/will be rolled away.
