### ISSUE TITLE
Arcane Mage AOE not recommending small burn.

### ISSUE THREAD

**Issue by MeowthMeows** [Hekili/hekili#2261]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello the aoe before never really gave me issues until recently where totm+barage after radiant spark isn't being displayed for the mini burn phase.

### How to Reproduce

Go to dummies and just follow aoe rotation for arcane mage. After burn phase where u enter ur mini burn with next radiant spark .

### Talent Loadout

B4DAHVkVsxxZrVqBmAzlSR2f7LJQolIJSSBk0kIiISiESolg0SCAAAAAAAAAAAgkkkESSSiA

### Snapshot

https://pastebin.com/F2sfuZZF

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/1CbpVrKbuMv6cRPNRToTYy

### Contact Information

Foxsays?#2995

**Comment by Hekili** [comment]
> Go to dummies and just follow aoe rotation for arcane mage. After burn phase where u enter ur mini burn with next radiant spark .

Feel free to elaborate.
