### ISSUE TITLE
Never recommending Decoration of Flame

### ISSUE THREAD

**Issue by Shankmaster4k** [Hekili/hekili#2262]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

While using the decoration of flame on my Protection paladin the addon, as of the most recent update, is never recommending the decoration of flame trinket to be used. Double checked that is isn't disabled and is appropriately configured for my spec. The trinket isn't showing up in the cooldown or separate or main automatic display no matter the state of toggles

### How to Reproduce

1. Enter game as Protection paladin
2. Equip decoration of flame trinket
3. Enter combat with any number of mobs 
4. Try toggling cooldowns and defensives, trinket will never be recommended

### Talent Loadout

BIEAAAAAAAAAAAAAAAAAAAAAA0SaJkiodg0ikUKNJJEhIBAAAAAAAAAAAAAANRSSKJBJRJlkEUQA

### Snapshot

https://pastebin.com/3HhzjEWR

### Contact Information

Aliwicious#9177

**Comment by Hekili** [comment]
Decoration of Flame is on the Cooldowns toggle by default, and you have Cooldowns shown separately, so the snapshot needs to be from the Cooldowns display.

**Comment by Shankmaster4k** [comment]
@Hekili apologies, I selected a snapshot from the wrong point in time during my troubleshooting. Here's the updated one: https://pastebin.com/LbuGHgYM

**Comment by Hekili** [comment]
I've adjusted Protection's ability to use trinkets when Moment of Glory is not talented in 2.0.13b.
