### ISSUE TITLE
new warlock expression igb_ratio

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#2264]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Hello please add the new warlock expression igb_ratio  

Calculates number of Imp Gang Bosses divided by total Wild Imps (incl. IGBs)

https://github.com/simulationcraft/simc/wiki/Warlocks
https://github.com/simulationcraft/simc/blob/61c17fb721828ea6ca05a195099d4415a5a68ce4/engine/class_modules/warlock/sc_warlock.cpp#L2034

### Contact Information

Lemonlust#4440

**Comment by Hekili** [comment]
This expression is available in 2.0.13b.
