### ISSUE TITLE
Assassination Rogue with Thistle Tea seems to be overzealous in recommending TT be used

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2266]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When using Thistle Tea talent with assassination rogue, there is a behaviour where thistle tea will constantly get recommended even when there will be enough energy to perform the next action by the time it is usable. Typically it will suggest using TT as the first priority during a GCD, but once the GCD is over, hekili sees it can perform the ability and swaps it with TT. This causes TT to dance around from being recommended first to second and vice versa. I'm wondering if maybe there is an issue with the energy regen/prediction logic or if something can be added to make this more stable.

I've attached a pastebin of it happening in combat. In this example, right after the GCD ends, it swaps to recommending envenom rather than TT. 

Here is another one where it's recommending TT during the opener earlier than simc does: https://pastebin.com/3sUn4dY0 (in this snapshot, TT is the 8th GCD but in simc its the 11th.

### How to Reproduce

1. Perform rotation as normal
2. When lower on energy, after an ability is pressed TT will be recommended during the GCD
3. Once GCD is over, recommended ability is pushed forward and TT pushed back

### Talent Loadout

BMQAOB/7AZ//CwQOf4fPMswHVLNJSCcgQJBAAAAAAQSAkIAAAAAAASQaOQJJkkkkWSiIBJSk4AB

### Snapshot

https://pastebin.com/FRy0auya

**Comment by Hekili** [comment]
In the snapshot, you have 62 energy.  The condition for Thistle Tea that passed is:

`! buff.thistle_tea.up[false] & ( energy.deficit[108.00] >= 100 | charges[2.00] = 3 & ( dot.kingsbane.ticking[false] | debuff.deathmark.up[false] ) | boss[false] & fight_remains[215.98] < charges[2.00] * 6 )`

Essentially, your energy deficit is 100 or greater.  Why shouldn't Thistle Tea have been recommended?  It was the 30th entry considered.  The second recommendation is Envenom, which is the 61st entry considered.  Are you thinking Envenom should've been recommended first, despite Thistle Tea being used when you have an energy deficit of 100 or greater?

**Comment by fzarr** [comment]
Apologies, this probably should have been in feature requests rather than the recommendation category.

The snapshot provided is during the GCD and at that moment, you are correct: TT is the correct recommendation. However as soon as the GCD is over, enough energy regeneration has occurred to where the envenom is possible. I was thinking that there may be a way the addon is modelling energy regeneration so it would know that once the gcd is over, enough energy will have been regenerated so that envenom can be the next action. 

Not sure if this energy regeneration is modelled? The recommendations itself at any point in time seem to be correct, its more that there is no 'look-ahead' so the recommendation swap around from TT to a non-TT very frequently when you are at a certain energy level.

**Comment by Hekili** [comment]
The energy regeneration is modeled, but Thistle Tea is not on the GCD so it is available and correct.  The addon absolutely looks ahead *if there isn't something to do* but if you want Thistle Tea to be lower in priority than other abilities, you'd have to move it down the priority list.  Then you get into territory where you use Thistle Tea fewer times than you could have, and you lose overall Energy due to opportunity cost.

You can test moving Thistle Tea down in priority in SimulationCraft and see if you find a placement that tends to offer more DPS.

**Comment by fzarr** [comment]
Cool, thanks for the explanation.  Will close.
