### ISSUE TITLE
Hekili not recognizing Stormkeeper Buff

### ISSUE THREAD

**Issue by Maddox-TN** [Hekili/hekili#2267]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Title. I can't for the life of me get Hekili to recognize when Stormkeeper buff is up on my Ele Shaman. This makes it so that it does not recommend casting Lightning Bolt. I've tried messing witth the Priorites and I have it just the way I want it, only thing missing is getting it to recommend Lightning Bolt after casting Stormkeeper. In Priorites under Lightning Bolt I've tried with "buff.stormkeeper.up" but it still says gives False values even when Stormkeeper is up.

### How to Reproduce

1. Go on Ele sham
2. attack  Target Dummy
3. Use Stormkeeper
4. Recommends Lava Burst...

### Talent Loadout

BYQAfcj78nJtvjmejSqe5Zhm9AAAAAAgUSr0SSLJgQSjS0SJJEAAAAAAQJAplkQR0ISjk0CBtEgE

### Snapshot

https://pastebin.com/LYAmR5LB

**Comment by Hekili** [comment]
Weird.  Will fix in today's release.

**Comment by Maddox-TN** [comment]
Thanks! Keep up the good work :)
