### ISSUE TITLE
Manic Grieftorch Trinket not being recommended

### ISSUE THREAD

**Issue by nickmo36** [Hekili/hekili#2269]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hello. First off, thank you for the great addon. I really appreciate the effort and work you have put into this.

I recently received a Manic Grieftorch trinket from vault but I can't figure out how to enable it in my Hekili rotation. I'm assuming I'm missing a configuration change.

### How to Reproduce

1. Enter game as Marksman Hunter
2. Attack target dummies
3. Trinket is not recommended during rotation (single target or AOE)

I visited Hekili -> Gear and Items -> Manic Grieftorch and have verified that the trinket is not disabled. I tried increasing minimum and maximum target values but this doesn't seem to have any effect.

### Talent Loadout

B4PAIlFMjeNhnEouGfV8Ij2uS5ARoFASCCCAAAAQkERSSSCCRSLkGRQRKaCJJhESoBAAAAA

### Snapshot

https://pastebin.com/jkM0AKV6

### Additional Information

I hope this is enough information, and I apologize in advanced for anything that I have missed.

**Comment by Hekili** [comment]
It is on the Cooldowns toggle, and your Cooldowns toggle is not enabled.

```
toggles: cooldowns = false
```

See /hekili > Toggles, Show Cooldowns.
