### ISSUE TITLE
Hammer of reckoning missing on ret pally

### ISSUE THREAD

**Issue by retpally1** [Hekili/hekili#227]
Please describe your idea or feature and when it would be useful.
I tried to add a new ability on the hekili UI, but hammer of reckoning is not showing

**Comment by retpally1** [comment]
Also, when i add all the other abilities like divine storm, hammer of justice and other enterrupts and cleaning spells, they dont appear when im in pvp, if i get low hp, it doesnt tell me to use divine shield, doesnt tell me when to enterrupt etc... PVP

**Comment by Hekili** [comment]
I can add Hammer of Reckoning as an ability; PvP talents have generally been added as they are requested since they aren't part of normal (simmed) priorities in general.

With regard to other abilities, there's no way of knowing why you are not seeing those abilities without knowing where you've added them to your priority and what conditions you've supplied for them.

**Comment by retpally1** [comment]
Thanks for wanting to add the ability mate!

I added them as defensives, the divine storm and protection of blessing, it still doesnt show up

**Comment by retpally1** [comment]
and blessing of freedom

**Comment by retpally1** [comment]
and racial human spell "every man for himself"

**Comment by Hekili** [comment]
I don't know what you mean by "added them as defensives" -- that could mean you added them to a toggle or that you put them in your priority list somewhere.  Order matters, conditions matter.

**Comment by retpally1** [comment]
Yeah thats what i meant, they still dont pop up :(

**Comment by Hekili** [comment]
Um, which part did you mean?

**Comment by retpally1** [comment]
When i go to the retriubition interface > toggles > defensives > add new ability, and when i get low hp in a fight it doesnt tell me to use divine storm, when i get cc'd it doesnt tell me to use the others

**Comment by Hekili** [comment]
Yeah, that's not what that is for.

Toggles are for deciding whether the addon can recommend a certain ability or group of abilities.  If you added it to Defensives, that means when Defensives is enabled the addon *could hypothetically recommend the ability if your priority includes it*.

You need to edit the Retribution priority itself if you want to add an ability and have it be recommended under specific circumstances.

**Comment by retpally1** [comment]
I just want my hekili to be aimed towards pvp, as ret pally, how do i do that?

**Comment by Hekili** [comment]
You need to edit the Retribution priority itself if you want to add an ability and have it be recommended under specific circumstances.

**Comment by retpally1** [comment]
It seems to be a complicated mate, well, is there a way to get 2 bars instead of 1? where the second bar displays all the ultility and defensive abilities like hammer of justice and divine storm?

**Comment by retpally1** [comment]
No worries man, but i would love to see hammer of reckoning, thank you and good job man ur addon is lit
