### ISSUE TITLE
Unstable Affliction being incorrectly recommended

### ISSUE THREAD

**Issue by Reiteration38** [Hekili/hekili#2270]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Unstable Affliction is being improperly recommended (every cast, or every other cast) after first application would have expired and re-application was done with Summon Darkglare active.

### How to Reproduce

1. Enter game as Affliction Warlock
2. Start combat against level 70 Training Dummy
3. Follow recommended priority list until all DOTs are active
4. Use Summon Darkglare (talent)
5. Continue following recommendations until original Unstable Affliction (would have) timed out
6. Unstable Affliction starts being recommended every cast, or every other cast, even with 25+ seconds left on duration on the Training Dummy

### Talent Loadout

BkQAbtPS25JQs0VfQSDmhm+p3gQSSikEi00IINJJRaBAAAAakAAAAAAAikCiIJJRSTiAAA

### Snapshot

https://pastebin.com/ChRVRest

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/p2RhikHCKMW5LF9UnjGR7L

### Contact Information

Tareb#4070

**Comment by Hekili** [comment]
Thanks, will adjust this again.

**Comment by Hekili** [comment]
This will be in 2.0.14.
