### ISSUE TITLE
Arcane Mage

### ISSUE THREAD

**Issue by Crucibletwitch** [Hekili/hekili#2271]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

was just wondering why i dont see arcane surge in my rotation at all

### Additional Information

if im missing something that would be great im on the default, maybe theres a way to import another retation?

### Contact Information

Crucible#6929

**Comment by Hekili** [comment]
This is not a feature request.  More likely than not, your Cooldowns toggle is not enabled.  See /hekili > Toggles.
