### ISSUE TITLE
Option to consider rares as bosses

### ISSUE THREAD

**Issue by Wraiven** [Hekili/hekili#2272]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

So as the title states, I would love to see an option under settings that you can consider rares as bossess.

### Contact Information

grootaholic@gmail.com

**Comment by Hekili** [comment]
What is the benefit of this option?  How does it help you and/or the addon to perform better?  Thanks!

**Comment by Wraiven** [comment]
> What is the benefit of this option? How does it help you and/or the addon to perform better? Thanks!

So I know I do, and a lot of others save big cooldowns for the bossess and rares. it would enable the use of those big cooldowns into the rotation helper for those rares instead of only using the non big cooldowns on rares. I suggest it as an option under settings for those that prefer to keep it just bossess, but still adds it for those that would like it for rares as well.

**Comment by Andy88488** [comment]
Agreed. I just started with Hekili on my Demonology Warlock. I engaged a rare elite, very curious to see how it would handle the Demonic Tyrant, and it just did nothing. I mean, if you're in a raid, I can see where you would want to save your Tyrant for the Bosses, but if you're just playing PVE, why not use it against a Rare?

**Comment by Andy88488** [comment]
The other advantage about allowing Rares to be treated as Bosses is that it allows you to practice your rotations with the special ramp-ups that you need to most efficiently use the special cooldown attack. That would be big for me.

**Comment by Hekili** [comment]
I'm still not persuaded that this is better than just making use of the Cooldowns toggle.  Realistically, even in boss fights you *probably* should be using the toggle to save cooldown abilities for the right moments (without leaving them toggled off for too long).

Having the "Boss Only" option on an ability in the first place is questionable at best, IMO.  I'm just not sure that's the right level to implement this sort of thing.

**Comment by Andy88488** [comment]
Okay, I have to confess that I'm still learning about this program, and there's a lot going on in there. If I can manually toggle Cooldowns, that's really perfect.
