### ISSUE TITLE
Death and Decay during Dancing Rune Weapon

### ISSUE THREAD

**Issue by Lilmothmouth** [Hekili/hekili#2274]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Is it possible to make Death and Decay not show during Dancing Rune Weapon?

### Contact Information

Discord: Lilmothmouth#8860

**Comment by Hekili** [comment]
It is possible, yes -- it would be a custom priority which isn't supported, until/unless SimulationCraft testing demonstrates this is a consistent performance gain.  Then I can build it in.

Or you can make a strong case for this to be added as an option -- usually, that's the sort of thing that you'd want to test in SimulationCraft to confirm it's better than the alternatives.  For example, what you *really* want might be to pop Death and Decay before DRW so it's not fully wasting CD recovery time, which is not the same thing as just not using Death and Decay during DRW.
