### ISSUE TITLE
Healer Rotations

### ISSUE THREAD

**Issue by awoodyyc** [Hekili/hekili#2275]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Healing rotations were added in 1.0.17 for Shadowlands, but disabled in the TOC with a # preceding the ClassSpec. I understand that they were never officially added nor were they supported, but are there any plans to allow minimally functional rotations for healer to be enabled in the same way?

**Comment by Hekili** [comment]
If/when there are viable *DPS* rotations for healers, and if/when there is limited active work on DPS specializations for Retail, I'll do some additional work toward enabling healer DPS.  In the meantime, it is officially unsupported.

**Comment by awoodyyc** [comment]
There certainly are viable DPS rotations for healers - Holy Paladin, Disc Priest and Mistweaver Monk are the big standouts that require a DPS rotation in order to heal. The DPS rotation informs the healing more than the healing informs the DPS rotation with the above.

I appreciate you looking at this, whenever you do. Much thanks for everything else.
