### ISSUE TITLE
Dragonrage never called

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#2279]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I reported this before and after making the fixes as stated before It's still not showing up.
I just fought "Morchok" and it never once went off.  It hasn't been going off all day.

![image](https://user-images.githubusercontent.com/1850089/212081439-a41fed99-88cc-461f-84e8-0002cf7166f4.png)
![image](https://user-images.githubusercontent.com/1850089/212081482-a23a40f0-bf64-4f26-b078-1f2a820caf19.png)
![image](https://user-images.githubusercontent.com/1850089/212081511-4d538bfc-800a-4af9-8f80-e19fcf0c2bd3.png)

### How to Reproduce

Enter any lengthy fight.  Dragorage should go off at each cooldown as its a major skill

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhLEAAAAAAAahkkcAROQOgkEJlkkUCHINgEyBCJJJJEJJB

### Snapshot

https://pastebin.com/0sXDRqZF

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kJyHz7yzomzAN4t6D14AYm

### Additional Information

build: v10.0.2-2.0.14
level: 70 (70)
class: EVOKER
spec: devastation

talents: ancient_flame
    animosity = 1/1
    arcane_intensity = 2/2
    attuned_to_the_dream = 2/2
    azure_essence_burst = 1/1
    blast_furnace = 2/2
    bountiful_bloom = 1/1
    burnout = 1/2
    catalyze = 1/1
    causality = 1/1
    cauterizing_flame = 1/1
    dense_energy = 1/1
    draconic_legacy = 2/2
    dragonrage = 1/1
    enkindled = 2/2
    essence_attunement = 1/1
    eternity_surge = 1/1
    eternitys_span = 1/1
    fire_within = 1/1
    firestorm = 1/1
    font_of_magic = 1/1
    forger_of_mountains = 1/1
    heat_wave = 2/2
    honed_aggression = 1/2
    imminent_destruction = 1/2
    imposing_presence = 1/1
    inherent_resistance = 2/2
    innate_magic = 2/2
    instinctive_arcana = 1/2
    landslide = 1/1
    lay_waste = 2/2
    leaping_flames = 1/1
    lush_growth = 1/2
    natural_convergence = 1/1
    obsidian_bulwark = 1/1
    obsidian_scales = 1/1
    onyx_legacy = 1/1
    panacea = 1/1
    permeating_chill = 1/1
    protracted_talons = 1/1
    pyre = 1/1
    quell = 1/1
    recall = 1/1
    renewing_blaze = 1/1
    ruby_embers = 1/1
    ruby_essence_burst = 1/1
    shattering_star = 1/1
    spellweavers_dominance = 1/1
    terror_of_the_skies = 1/1
    tip_the_scales = 1/1
    tyranny = 1/1
    volatility = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: [dreamweaver]

sets: none

gear: blaze_ring = 1
    calamitous_shockguards = 1
    circle_of_ascended_frost = 1
    dreamscape_prism = 1
    flametouched_treads = 1
    gilded_dracthyrs_tabard = 1
    icewraths_channeling_conduit = 1
    koroleths_crackling_dagger = 1
    ohnahran_falconers_chainmail = 1
    ohnahran_falconers_cinch = 1
    ohnahran_falconers_coif = 1
    ohnahran_falconers_greaves = 1
    ohnahran_falconers_shoulderguards = 1
    petrified_bracelets = 1
    petrified_fungal_spores = 1
    plume_of_the_forgotten = 1
    windsoaked_drape = 1

legendaries: none

itemIDs: 144111, 191997, 192000, 192001, 192002, 192003, 193421, 193687, 193731, 194675, 195484, 195531, 198489, 200159, 200207, 200740, 200858

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxTime = 10
    nameplateRange = 35
    nameplates = false
    noFeignedCooldown = false
    package = Devastation
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    use_clipping = false
    use_deep_breath = true
    use_early_chain = false
    use_unravel = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    azure_strike      = 4   [01]
    cauterizing_flame = E   [05]
    deep_breath       = 2   [01]
    disintegrate      = 3   [01]
    dragonrage        = F3  [06]
    emerald_blossom   = Q   [05]
    eternity_surge    = F4  [06]
    fire_breath       = 6   [01]
    firestorm         = F5  [06]
    hover             = `   [10]
    landslide         = F6  [06]
    living_flame      = 1   [01]
    obsidian_scales   = F2  [06]
    oppressing_roar   = -   [01]
    pyre              = 5   [01]
    quell             = F1  [06]
    shattering_star   = G   [06]
    tail_swipe        = BkSp[06]
    tip_the_scales    = T   [06]
    wing_buffet       = =   [01]

warnings: none

**Comment by N6REJ** [comment]
just killed Basrikron and still no dragonrage https://pastebin.com/vcfZ3qH5

**Comment by Hekili** [comment]
Your Cooldowns toggle is off, so your major cooldown ability is not going to be recommended. See the wiki at the top of this website re: toggles.

/hekili > Toggles > Show Cooldowns
