### ISSUE TITLE
Question about azerite essence

### ISSUE THREAD

**Issue by FayeSelene** [Hekili/hekili#228]
I want to disable the azerite beam from the focusing iris essence because I only want to use it when im in mellee range. I looked a bit around under trinkets and spells but cant find anything besided disable heart of azeroth what didnt do the trick. Is there someone who can point me in the right direction. It probably really simple and im just overlooking something.

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/66402453-dc3dd100-e9b2-11e9-83cd-79d66a9a55d0.png)

**Comment by FayeSelene** [comment]
Thank you, like I said I just overlooked it, but found it now, thanks again!

**Comment by Hekili** [comment]
No worries.  Keep in mind, if you add an entry to your priority (I don't even know which spec you're playing) for Focused Azerite Beam, you could also add a condition for your target's range.

`target.within8` means your target is within 8 yards, for example.
