### ISSUE TITLE
(WOTLK) Allow switching of specs for Hunter class to remain constant after logging out/back on

### ISSUE THREAD

**Issue by shawn571** [Hekili/hekili#2280]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Classic (Wrath of the Lich King)

### Feature Request

I've so far only noticed this on a Hunter - but when making the active priority Marksmanship or Survival, it will not persist through logons/logoffs or even a /reload of the console, it will always revert back to Beast Mastery. I haven't tried all other classes but the ones I did seemed to persist once it was set. Feature request is to allow the priority choice to save for Hunter and any other class where it may not yet.

### Contact Information

WittyWalnut137#4427

**Comment by Hekili** [comment]
I am not seeing this occur with the newest releases.  Please update to the latest Wrath release.  If you are still having issues, submit a new ticket.
