### ISSUE TITLE
Dev Evoker Unravel never recommended

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#2281]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

This spell is your best button vs shields but is never recommended. In terms of priority it is below dragonrage/empower spells, and above everything else. I am not certain exactly how many enemies pyre becomes better damage, but its a few and if you play unravel it is probably because you want to press it so having it above pyre in prio is likely not an issue.

### How to Reproduce

Talent Unravel
Hit a shielded unit

### Snapshot

- I cant find an enemy with a shield to test it easily, but its not in the APL anyway

**Comment by yurikenus** [comment]
A few things to help you out @dubudevs :
1. It is actually the second entry on the `default` APL, behind only Quell.  I think that's the default, unless I modified mine and the reset priorities isn't working.
2. However, it requires a toggle to be turned on. You can enable Unravel (at that high priority) by left-clicking the Hekili minimap icon, or in the Hekili interface in the "Devastation" menu, in the "Core" tab.  If this toggle is off, Unravel will never be recommended.
3. There are many creatures with shields for testing this one to get a snapshot.  I'll direct you to this lonely quest mob out on an island in the Azure Span: https://www.wowhead.com/npc=196809/wild-kelp-elemental as well as many of the NPCs that use this ability across the whole of the Dragon Isles: https://www.wowhead.com/spell=390979/tectonic-shield?dd=1&ddsize=5#used-by-npc

If you you set the toggle, find an NPC in the world (or in a dungeon/raid) and it doesn't recommend Unravel (while it is talented and not on cooldown), then take that Snapshot.  I don't imagine you'll get help here without it.

**Comment by Hekili** [comment]
@dubudevs yurikenus's answers are correct (and the snapshot is required anyway; it wastes so much time to not just supply it when you first supply the ticket).  It would've shown whether you had Use Unravel checked or not.  I'm going to close the ticket, but if you are still not finding Unravel recommended, you can comment and I'll reopen with your snapshot.
