### ISSUE TITLE
Sub Rogue Cold Blood is not directly before Secret Technique

### ISSUE THREAD

**Issue by n00del** [Hekili/hekili#2282]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hi,
the sub rota is recommending Cold Blood also right before normal Finisher.
As you can see in the raidbot report and also in the ravenhold discord it should only be used right before secret technique.
But for me its recommending it like you can see in this screenshot:
https://imgur.com/a/Cx9mFO4

### How to Reproduce

1. Enter Game aus Rogue
2. Run the Rotation as recommended
3. Cold Blood is also used right before normal Finisher

### Talent Loadout

BUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhAJJiQACSCSSSkIJRKJJRSiWSJCJJhWAAAA

### Snapshot

https://pastebin.com/6N1NjXBh

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/1KLpswZaFX99DnAcn9nvSr

**Comment by steveozz** [comment]
having same issue here！ responser said there are no problem with cold blood at all， no idea when they are going to notice this issue when aoeing

**Comment by Hekili** [comment]
@steveozz Please don't comment unless you are adding data to the ticket (i.e., snapshots) or anything that helps to identify the problem.

@n00del You need to provide a snapshot taken when you think the recommendation is incorrect or your alternative recommendation should happen.  In your case, that'd be:

1. Cold Blood is being recommended but Secret Technique is not next.
2. Secret Technique is being recommended but Cold Blood has not been recommended.

Taking a snapshot outside of combat is not helpful.  See the instructions below:

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by n00del** [comment]
Thank you for the answer.

Here the snapshots in the right moment. 
But before I want to mention that in the first case it is recommended as it should but everytime i cast cold blood and then its changing from Secret Technique to Eviscerate.

1.Cold Blood is being recommended but Secret Technique is not next.
https://pastebin.com/ED3bAe8L

2.Secret Technique is being recommended but Cold Blood has not been recommended.
https://pastebin.com/34P2xxHz

**Comment by Hekili** [comment]
I've found some adjustments to help make the in-game behavior with Cold Blood more closely match how it behaves in SimulationCraft with regard to its cooldown.  This seems to sync up with Secret Technique more effectively.  I'll post it in today's release.

**Comment by Hekili** [comment]
This will be in today's release.
