### ISSUE TITLE
Vengeance DH spamming Throw Glaive

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#2283]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Hey, Whenever i tank as vengeance dh usually it recommends throw glaive when fracture or other spells are up or sometimes it seems to get stuck recommending several throw glaives when other things are up as in the snapshot. This seems wrong to me ?

### How to Reproduce

Just follow the rotation in a dungeon and it does these odd recommendations periodically but not always.

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAQJgkERAEJSC0AJRTkcgkkkkQLJSSSSkSkEAAAAA

### Snapshot

https://pastebin.com/ZTGHigLQ

**Comment by Hekili** [comment]
Can you test with the latest release and see if this is still occurring?  If so, I need an updated snapshot when Throw Glaive is incorrectly/excessively recommended.  Thanks!
