### ISSUE TITLE
 Make a key to toggle for Show Separately.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2285]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Please do it Separately so that you can bind the key for on/off of this option. It is convenient when in battle you can move your priorities without going to the menu. I think it won't take you long. Because you already have this functionality for your other functions in the Toggles section. Thanks

**Comment by Hekili** [comment]
I don't plan to approach this issue this way.
