### ISSUE TITLE
Evoker Devastation: Eternity Surge Empowerment will sometimes not glow up when the level is reached

### ISSUE THREAD

**Issue by sanyex89** [Hekili/hekili#2286]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Sometimes the image in the hekili window will not glow up when the empowerment stage is reached (hekili suggests eternity surge 2 but the hekili image for eternity surge will still be faded out when stage 2 is reached) 

I have no problem with Fire Breath. only with eternity surge. 

Its also only happening sometimes and not all the time

### How to Reproduce

1. Be a Evoker with Devastation spec
2. go to training dummies with my build
3. attack till eternity surge is recommended
4. check if the spell "glows up" when the recommended empowerment stage is reached

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhTDCAAAAAAKaIJikEJkEJlkk0CSDJSIJBSSSSESSC

### Snapshot

https://pastebin.com/7FsapQfK

**Comment by sanyex89** [comment]
normal behaviour:
![grafik](https://user-images.githubusercontent.com/77323774/212486246-1ba536fe-43ec-435a-9de9-e3c6b9e391d0.png)

not glowing up:
![grafik](https://user-images.githubusercontent.com/77323774/212486550-9256ee84-5563-4b8d-be95-5ecfd2257317.png)

the eternity surge icon is still greyed out even tho we passed the stage 1 that was recommended. it didnt glow up when stage 1 was reached

**Comment by Hekili** [comment]
I'd need a snapshot from your last example to accompany a screenshot.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by sanyex89** [comment]
https://pastebin.com/Y4ARJWFd

it switched from eternity surge empowered 3 to eternity surge empowered 1 while attacking the 5 training dummies in valdrakken and stayed greyed out

**Comment by Hekili** [comment]
Test against the latest version.

**Comment by Hekili** [comment]
Going to address mostly in the next release.  The addon will not reduce target counts while an Empowered spell is being charged, and it will not stop processing recommendations sooner while figuring out which Empowered entry to cast.
