### ISSUE TITLE
Demon hunter: movement spells recommended when rooted

### ISSUE THREAD

**Issue by Hemario** [Hekili/hekili#2287]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

For vengeance and havoc, spells that are movement abilities (vengeful retreat, fel rush, felblade, the hunt, infernal strike) cannot be used when the character is rooted in place. When that happens, no other ability is being recommended.

I checked the code a little bit. Seems like we could use a `usable` statement as it is specified for Gladiator's medallion.
https://github.com/Hekili/hekili/blob/dragonflight/Classes.lua#L4480

Even though `debuff.loss_of_control.up` takes all loss of control into account (stunned, feared, ...) and not only rooted, it doesn't really matter as you can't really use any movement abilities any when you don't have control.

Additionally, a new debuff called `debuff.rooted.up` could be created, that only checks whether the `locType == "ROOT"`.

### Contact Information

Hemario#4869

**Comment by Hekili** [comment]
I'll add some attempts to control for this in the next release.  However, it could easily break down the entire priority -- sim priorities are not generally written to re-prioritize for when you can't use abilities due to a loss of control effect.
