### ISSUE TITLE
Blizzard issue: Manic Grieftorch cooldown readiness misreported by game UI

### ISSUE THREAD

**Issue by dro123123** [Hekili/hekili#2289]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The addon is telling me to use Manic Grieftorch but doesn't account that the trinket is not ready to use. I am using Windscar Whetstone with it. Windscar is used then you have to wait until the Grieftorch is able to be used (Normal). The Grieftorch says it's able to be used but in reality it's not because the blizzard UI doesn't account for Windscar whetstone cooldown starting until after the 6 seconds it's been used. So Hekili is telling me to use Grieftorch and I try to but it's not ready and won't let me go to the next spell until it's used. The Whetstone has a 6 second cast but the blizzard UI starts the cooldown right when the trinket is popped. Grieftorch then is used at the improper time as the blizzard UI doesn't account for this cooldown.

### How to Reproduce

1. Enter game with a character that has Windscar Whetstone and Manic Grieftorch
2. Go to dummy
3. use Windscar and wait for grieftorch to be able to be used next
4. Grieftorch unable to be used as cooldowns are bugged for this.
5. Grieftorch saying "item not ready to be used yet"

### Snapshot

https://pastebin.com/wN9vyKFK

### Contact Information

Rooski#9901

**Comment by Hekili** [comment]
The snapshot is required.

**Comment by dro123123** [comment]
> The snapshot is required.

https://pastebin.com/jL5ZG0xA

I took two snapshots in case 

https://pastebin.com/YPUKdwT1

**Comment by Hekili** [comment]
In neither of your snapshots is Manic Grieftorch being recommended.  You said it is being recommended when it is not ready.  Can you snapshot at the time that is occurring and link it?  Thank you.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by dro123123** [comment]
New snapshot + Video of it happening.
https://pastebin.com/f2SfqTsw
https://streamable.com/rn85zi - error "Item not ready yet"

**Comment by Hekili** [comment]
The video really confirms that this is a Blizzard issue.  I will try to think of ways to mitigate the issue, but if the UI lies about the trinket being ready, there may not be a lot I can do.

**Comment by shredxt** [comment]
The cooldown issue for double on-use trinkets with Whetstone has been hotfixed by Blizzard now.

https://i.imgur.com/eN68rBU.png

**Comment by Hekili** [comment]
Right.  Are you noticing issues related to the guardrails I put in since 10.0.5 came out, or just advising that the ticket can be closed.  Let me know if there are any lingering issues that you've seen.  Thanks!
