### ISSUE TITLE
Outlaw: Puzzle Box not specifically prioritized

### ISSUE THREAD

**Issue by Neekodesu** [Hekili/hekili#2290]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Puzzle box should be recommended as prepull, and before my whetstone, but it's not getting priorized, its just popping randomly in middle of the fight instead prepull or before whetstone.

### How to Reproduce

1. Enter a game as Outlaw Rogue.

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQkkoJlkASQAAAA

### Snapshot

https://pastebin.com/gZFDtHkr

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/aauL9LfeiBNJ3YNvi7Wtkq

### Additional Information

I have already tried to add Puzzle Box in Outlaw > Action list, CDS as number 1 priority, and precombat, without any result.

### Contact Information

Neko#7422

**Comment by chevyn11** [comment]
rogue sims havent made special cases to optimise puzzle box yet, hekili will inherit any simc updates for it.
A recent update to simc also stopped making puzzle box oversim for outlaw rogues (though maybe it gets back some value if properly optimised): https://github.com/simulationcraft/simc/commit/e3a7ee0b009a6f007df077117fd0ad8c7599f7d8

You should put a raidbots quick sim to show where the sim uses puzzle box.

**Comment by Neekodesu** [comment]
https://www.raidbots.com/simbot/report/4YyrLuisRHifgGJUUJwVkt there you go!

**Comment by Hekili** [comment]
If you look at the behavior of the sim, it is not used pre-pull and doesn't look to be modeled entirely accurately.  I'll wait for the Rogue sims to get updated.
