### ISSUE TITLE
Outlaw use of Dispatch

### ISSUE THREAD

**Issue by steveozz** [Hekili/hekili#2291]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

outlaw dispatch can use at 5 combo points instead of 7 at some point， or there might be too much Sinister Strike used  to waste energy 

*originally posted in title:*  outlaw dispatch can use at 5 combo points instead of 7， or there might be too much Sinister Strike used Edit： sometimes i need to use 4 times Sinister Strike to get fully combo point to use finisher， but instead 2 or 3 sinister to get 5 combo to dispatch or finisher，and also vanish and shadow dance should not be using via cd， it should be used when you have no pistol or ambush on hand， it gives you addtional resources. thanks for your hardwork again

### How to Reproduce

outlaw rogue Priority，Recommendation

### Talent Loadout

BQQAOB/7AZ//CwQOf4fPMswHVDAAgERSAkkEJSSCkEJRikkkkECAAAAAAQkkoJlkASQAAAA

### Snapshot

https://pastebin.com/4CCnJgsL

**Comment by IIeTpoc** [comment]
Reupload snapshot to pastebin please. Your link is invalid. Also snapshot the moment there is falsely recommended 1. Finisher. 2. Shadow dance. 3. Vanish.
Ideally it should be 3 different snapshots

**Comment by Hekili** [comment]
The addon quite frequently recommends Dispatch with fewer than max combo points.  You'll need to provide an actual snapshot taken when the addon seemingly should recommend Dispatch but has not done so.  See instructions below.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
