### ISSUE TITLE
Demonlogy Warlock Power Siphon Displays improperly

### ISSUE THREAD

**Issue by thatdan23** [Hekili/hekili#2292]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I got this Addon yesterday and generally works great.  However I did notice on my Warlock that Power Siphon shows up incorrectly:

I'm on a level 65 warlock using the starter build (no power siphon talented) yet with cooldowns toggled on it displays.  Additionally if I do talent into power siphon and put it on cooldown it still displays.

Perhaps this is showing as something default?  But I did look at the SimC code and it doesn't seem to care about power siphon being talented or not.  Additionally the conditionals seem to disregard the talent's existence as well so maybe that's the problem.

### How to Reproduce

1.  Have a Demonology warlock with Power Siphon untalented
2. Set Cooldowns to display as separate
3. Note that the Power Siphon icon displays.

### Player Information (Link)

```Text
build: v10.0.2-2.0.15
level: 65 (65)
class: WARLOCK
spec: demonology

talents: abyss_walker
    accrued_vitality = 2/2
    annihilan_training = 1/1
    antoran_armaments = 1/1
    call_dreadstalkers = 1/1
    carnivorous_stalkers = 1/1
    curses_of_enfeeblement = 1/1
    dark_accord = 1/1
    demon_skin = 2/2
    demonbolt = 1/1
    demonic_calling = 2/2
    demonic_circle = 1/1
    demonic_embrace = 1/1
    demonic_fortitude = 1/1
    demonic_gateway = 1/1
    demonic_inspiration = 1/1
    demonic_knowledge = 1/1
    demonic_meteor = 1/1
    desperate_pact = 2/2
    dread_calling = 1/1
    dreadlash = 1/1
    fel_and_steel = 1/1
    fel_armor = 2/2
    fel_domination = 1/1
    fel_might = 1/1
    fel_sunder = 1/1
    fel_synergy = 1/1
    from_the_shadows = 1/1
    grand_warlocks_design = 1/1
    grimoire_of_synergy = 2/2
    imp_gang_boss = 2/2
    implosion = 1/1
    infernal_command = 1/2
    inner_demons = 2/2
    lifeblood = 2/2
    mortal_coil = 1/1
    ripped_through_the_portal = 2/2
    shadowfury = 1/1
    soul_conduit = 2/2
    soul_link = 1/1
    soulbound_tyrant = 2/2
    summon_demonic_tyrant = 1/1
    summon_vilefiend = 1/1
    teachings_of_the_black_harvest = 1/1
    wrathful_minion = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: [dreamweaver]

sets: integrated_primal_fire = 1

gear: ancient_bloodmoon_cloak = 1
    avowed_arcanists_staff = 1
    bejeweled_stonewatchers_pendant = 1
    causality_band = 1
    choral_sash = 1
    choral_vestments = 1
    cobalt_watchers_cuffs = 1
    cypheretched_ring = 1
    integrated_primal_fire = 1
    junior_timewarder_leggings = 1
    oracular_hood = 1
    oracular_mantle = 1
    stonefiend_shapers_mitts = 1
    surveyors_cloth_treads = 1
    windsealed_mana_capsule = 1

legendaries: none

itemIDs: 122262, 178833, 181224, 188006, 188011, 190344, 190346, 190632, 191990, 193498, 195206, 195212, 199018, 200868, 200880

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Demonology
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    dcon_imps = 6

toggles: cooldowns = true [separate]
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    axe_toss              = 6   [01]
    burning_rush          = C3  [05]
    call_dreadstalkers    = 2   [01]
    curse_of_exhaustion   = S=  [06]
    curse_of_tongues      = S6  [06]
    curse_of_weakness     = M4  [01]
    dark_pact             = C7  [05]
    demonbolt             = 1   [01]
    demonic_gateway       = -   [01]
    drain_life            = C0  [05]
    fear                  = S-  [06]
    fel_domination        = S3  [06]
    hand_of_guldan        = 3   [01]
    health_funnel         = C8  [05]
    healthstone           = =   [01]
    implosion             = S2  [06]
    mortal_coil           = 0   [01]
    shadow_bolt           = 4   [01]
    shadowfury            = C4  [05]
    soul_strike           = S4  [06]
    soulstone             = S7  [06]
    stoneform             = S0  [06]
    subjugate_demon       = C6  [05]
    summon_demonic_tyrant = S1  [06]
    summon_felguard       = C9  [05]
    summon_pet            = C9  [05]
    summon_vilefiend      = 5   [01]
    unending_breath       = C=  [05]
    unending_resolve      = 7   [01]

warnings: none
```

### Error Messages (Link)

```Text
n/a
```

### Contact Information

Snedhepl#1790

**Comment by Hekili** [comment]
This is an issue related to recommendations; it should've been submitted as such.  A snapshot is required.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by thatdan23** [comment]
Pastebin link: https://pastebin.com/VhtLk4L6

**Comment by Hekili** [comment]
That is your trinket.

https://www.wowhead.com/item=200868/integrated-primal-fire
