### ISSUE TITLE
Marksmanship hunter not using aimed shot properly

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#2293]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Multiple times aimed shot is available and not used, sometimes 2 aimed shots. Even during trueshot its not used with 2 stacks.

### How to Reproduce

Go into a a fight as marksman and see how aimed shot is not recommended when it should be, even in trueshot.

### Talent Loadout

B4PAIlFMjeNhnEouGfV8Ij2uS5ARoFASCCCAAAAQkERSSi4ACRSLkGRkWRKaCJSIhgGAAAAA

### Snapshot

https://pastebin.com/0CDtESxJ

**Comment by Hekili** [comment]
This should be addressed in 2.0.15a.  If it isn't, please comment with a new snapshot and elaborate on what you're seeing vs. what you should be seeing.  Thanks.
