### ISSUE TITLE
Marksman Hunter - Arcane Shot prioritised over aimed shot Procs and trueshot.

### ISSUE THREAD

**Issue by Banditpanda2702** [Hekili/hekili#2294]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Latest hekili update has changed hunter prio. sometimes suggesting up to 5 arcance shots in a row.

### How to Reproduce

1. Enter as MM hunter
2. begin prio rotation
3. Aimed shot and true shot procs being ignored.

### Talent Loadout

B4PAIlFMjeNhnEouGfV8Ij2uS5ARoFASCCCAAAAQkERSSi4ACRSLkGRQRKaCJJhESoBAAAAA

### Snapshot

https://pastebin.com/vpzj5AVP

**Comment by Hekili** [comment]
This should be addressed in 2.0.15a.  If it's not, please comment with a new snapshot and explain more clearly the difference between what you're expecting to see vs. what you're actually seeing.  Thanks.
