### ISSUE TITLE
Warlock Priority Bug - Randomly works on trash mobs - no functionality on boss/target dummy.

### ISSUE THREAD

**Issue by Bona580** [Hekili/hekili#2299]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Classic (Wrath of the Lich King)

### Describe the Issue

Title basicly sums it up.  The priority display is certainly visible and it does recognize spell press but does not update or change as spells are utilized.  

I attemtped this with all other addons disable with the same results as above.  

I included a video of the above issue to Hekili. 

### How to Reproduce

1. Login 
2. Be an affliction warlock (may be demo as well - unsure)
3. Begin attacking.  

https://user-images.githubusercontent.com/123010332/213261522-55364893-2ac5-4b00-9151-08af50b0aa87.mov

### Player Information (Link)

```Text
build: v3.4.0-1.0.0-beta9
level: 80 (80)
class: WARLOCK
spec: warlock

talents: amplify_curse
    bane
    contagion
    deaths_embrace
    empowered_corruption
    eradication
    everlasting_affliction
    fel_concentration
    haunt
    improved_corruption
    improved_curse_of_agony
    improved_felhunter
    improved_shadow_bolt
    malediction
    nightfall
    pandemic
    ruin
    shadow_embrace
    shadow_mastery
    siphon_life
    soul_siphon
    suppression
    unstable_affliction

pvptalents: none

covenant: none

conduits: none

soulbinds: none

sets: none

gear: band_of_channeled_magic = 1
    boots_of_impetuous_ideals = 1
    cape_of_the_unworthy_wizard = 1
    dying_curse = 1
    guild_tabard = 1
    illustration_of_the_dragon_soul = 1
    leash_of_heedless_magic = 1
    leggings_of_mortal_arrogance = 1
    mainhand = 1
    matriarchs_spawn = 1
    signet_of_manifested_pain = 1
    the_turning_tide = 1
    unsullied_cuffs = 1
    valorous_plagueheart_circlet = 1
    valorous_plagueheart_gloves = 1
    valorous_plagueheart_robe = 1
    valorous_plagueheart_shoulderpads = 1
    wand_of_the_archlich = 1
    wyrmrest_necklace_of_power = 1

legendaries: none

itemIDs: 39426, 39766, 40246, 40255, 40396, 40398, 40399, 40405, 40420, 40421, 40423, 40424, 40432, 40561, 40719, 44008, 44661, 5976

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcd = 687
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Affliction (wowtbc.gg)
    package1 = Affliction (wowtbc.gg)
    package2 = Demonology (wowtbc.gg)
    package3 = Destruction (wowtbc.gg)
    petbased = false
    potion = speed
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    group_curse = curse_of_agony
    group_type = party
    shadow_mastery = true
    solo_curse = curse_of_agony

toggles:     cooldowns = false [separate]
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = false 
    interrupts = true [separate]
    mode = single 
    potions = false 

keybinds: 
    corruption              = N3  [01]
    curse_of_agony          = N4  [01]
    demon_armor             = -   [01]
    demonic_circle_summon   = G   [02]
    demonic_circle_teleport = F   [02]
    drain_soul              = N5  [01]
    haunt                   = N1  [01]
    life_tap                = RIGHT[01]
    potion                  = LEFT[05]
    seed_of_corruption      = N6  [01]
    shadow_bolt             = N0  [01]
    shadowflame             = N7  [05]
    soulshatter             = N*  [05]
    summon_voidwalker       = =   [01]
    unstable_affliction     = N2  [01]
    will_to_survive         = PgDn[05]
```

### Error Messages (Link)

```Text
No error message in game. Just no functionality.
```

### Contact Information

Discord ID - Bona580#3714

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Bona580** [comment]
I found the issue - by enabling "interupt" for my alt on the same account - it is locking my warlocks prio from functionally working. When I disable interupt - magically we are functional again.

**Comment by Hekili** [comment]
I still need the snapshot information.

**Comment by Hekili** [comment]
@Bona580 Please take a look at this Wrath fork of the addon as well, if you're not already using it.  It may already resolve this for you.  (Thanks @zmsl!)

https://github.com/zmsl/hekili/releases/tag/v3.4.1-1.0.0

**Comment by Bona580** [comment]
Okay, so on digging deeper.. I was utilizing the "Potions" under the "Gear and Items" tab to assign my potions to "interrupt" as I wasn't using that box for anything else.  Now, after trying to assign potion to any other possible combination of boxes - It completely destroys the addon to the point it won't even load now.  I tried putting it back on interrupts - I tried putting it in cooldowns - tried putting it back on main display... None of these options will work.

**Comment by Bona580** [comment]
Yea, so I have tried just about everything.. I cannot generate a potions window.  If yuo enable "show potions" it still wigs.  Previously I had this setting off since I had it under the interrupts pane since it was empty - basicly allowing me a totally seperate window just for my potions - may at this point just disable and put it back in through a weakaura.  I think the nice thing I liked about having it in this format was the ease of it basicly vanishing and arriving so as to reduce clutter etc.

**Comment by zacksamselsonos** [comment]
@Bona580 are you using the Hekili install from the main repo, Curseforge, or from the release page mentioned above?

**Comment by Bona580** [comment]
Curseforge.. I assumed it would be the same in terms of release.

**Comment by Bona580** [comment]
Did a manual install of the above - same issues persist.

**Comment by Bona580** [comment]
Show Interrupts w/ Show Seperately.
Gear and Items - Potion.  Assign to toggle "interrupts"
Viola - the entire addon vanishes.

**Comment by Hekili** [comment]
I'm not going to prioritize this; I'd recommend not putting your Potions on the interrupts toggle if it breaks everything.
