### ISSUE TITLE
Ret Consecration Range Check

### ISSUE THREAD

**Issue by ehmehzing** [Hekili/hekili#2301]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

There should be a range check on consecration enabled for ret, dropping consecration off targets is a major damage decrease now due to the increased value of damage done to mobs affected by the AOE. 

### How to Reproduce

Run hekili in ret spec and it will recommend consecration be cast even out of range. 

### Talent Loadout

BYEAwtJ2KpR8WbGzhz/jy2AP8AAAAAAgIBgkWaJJEKkEKpkkkWJAAAAAAASTkkkmAJRJtkEUiSA

### Snapshot

test

### Raidbots Sim Report (Link)

test

### Additional Information

test

### Contact Information

test

**Comment by Hekili** [comment]
Sounds like it's worth submitting the complete ticket for, instead of just typing the word test into the boxes.
