### ISSUE TITLE
Survival Hunter Butchery/Carve

### ISSUE THREAD

**Issue by wlfdx** [Hekili/hekili#2302]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When playing as SV, hitting a single target dummy or cleave dummies it will never recommend carve or butchery (whichever specced) - same in open world.

### How to Reproduce

Simply take a survival hunter to the cleave or single target dummies.

### Talent Loadout

B8PAIlFMjeNhnEouGfV8Ij2uSxBgW4ASgEEkIRKJECRSEhAAAAAAgChGkIhkIhCAAAAgA

### Snapshot

https://pastebin.com/Qui3ME2R

**Comment by chevyn11** [comment]
```
49.  call_action_list:cleave ( default - 5 )
        Criteria for cleave FAIL at +1.07 - active_enemies[2.00] > 2
```

looks like it will only recommend the whole cleave action list at 3 or more enemies.. your snapshot only has 2

**Comment by Hekili** [comment]
Chevyn's response is correct; Carve/Butchery is used with more than 2 targets.
