### ISSUE TITLE
Vengeance demonhunter: phase stays true after talent change

### ISSUE THREAD

**Issue by Hemario** [Hekili/hekili#2304]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After changing specialization from havoc to vengeance and then changing talents, the phases do not get reset and keep getting stuck.

### How to Reproduce

1. Switch to vengeance demon hunter, select Elysian Decree talent
2. Switch specialization to havoc DH and relog
3. After relogging, switch specialization to vengeance
4. Swap Elyssian Decree talent to Fodder to the Flame
5. Check out `variable.elysian_decree_ramp_in_progress` is still set to true wasn't reset

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAgIIJJRAQCAFIJR7AJkkkkkEtkUSSSSoEJBAAAAA

### Snapshot

https://pastebin.com/87fz37XN

### Additional Information

As you can see in the snapshot
```
[ Vengeance ] Phase 'elysian_decree_ramp_in_progress' set to 'true' (reset_precast).
```
even though talent elyssian_decree is not selected and `fodder_to_the_flame = 1/1` is

### Contact Information

Hemario#4869

**Comment by Hekili** [comment]
Good catch, thanks for the ticket.  It's *probably* safe for me to just reset all phase variables when talents change, but I'll think about it a bit.

**Comment by Hekili** [comment]
I have a test fix in the latest release.
