### ISSUE TITLE
Prot Warrior - Shield Wall and Last Stand Usage

### ISSUE THREAD

**Issue by LynxAU** [Hekili/hekili#2306]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

So, prot warrior for myself is basically just recommending Shield Wall and Last Stand on cooldown and ignoring the options i have set

The settings are

Shield Wall Damage Required - 0
Shield Wall Health Percentage - 50
Last Stand Damage Required - 0
Last Stand Health Percentage - 20

These are just kind of values where i like them to be set as personal preference, obviously i use my CDs as i feel i need them, but it's always good having the reminder if my health drops and i'm not completely paying attention.

It's my understanding that with the settings set like this it should only recommend those spells when my health is below 50% and 20%

Thanks in Advance,
The addon is amazing keep up the good work!

![Wow_JZSj6gw5Oz](https://user-images.githubusercontent.com/8641094/213846534-0e18f014-6b5c-4c98-a53d-ef51ec70f838.png)

### How to Reproduce

1. Enter Game
2. Be a prot warrior any talent build as long as you have shield wall and last stand
3. attack anything it'll recommend them on cooldown (or does at least for myself)

### Talent Loadout

BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQSLpkkkSBRgQRiElkEgAJBtQSCiAhAAAAAAAARAAoUaA

### Snapshot

https://pastebin.com/rMnfWpVF    https://pastebin.com/kE1pTAsp

### Additional Information

I don't check github ever really so feel free to contact me on discord my username is listed below and i'm in the hekili discord!

### Contact Information

Harath#0001

**Comment by Wyste** [comment]
With the setting at your value `Damage Required - 0` , you are effectively telling the addon that you want shield wall when you take 0% of your HP in damage, which is basically always.

The way the shield wall damage and health settings works are they are exclusive of eachother UNLESS you have the checkbox clicked for Requiring both.

In your case with your settings, the addon asks 
`damage taken greater then 0% of hp?` (true) 
OR
`is current HP under 50%` (false)

Since one is true - it recommends the action. Hope this helps! You should try setting the Damage required to something like 50% (which means you've taken 50% of your HP in damage in the last 5 seconds). I think 50% is the default as well.

**Comment by LynxAU** [comment]
I’m not using the “damage and health percentage option, both of those boxes are unchecked so it only uses health %

so unfortunately your advice is not relevant as I’m not using the setting which requires damage taken and should just be completely based off health % and as per the fly out text when you mouse over the damage taken option it specifically says “if you have this above 0” this is what it does and goes into the explanation about how it works.

At 0 it should not be enabled as the description says “if you have this above 0”

appreciate the reply.

**Comment by Hekili** [comment]
> At 0 it should not be enabled as the description says “if you have this above 0”

No, you're interpreting it backwards.  If set to 0, there is no requirement -- it can be recommended regardless of how much damage has come in.  What you want to do is check that both options are required.

**Comment by LynxAU** [comment]
tried to send this on discord but unfortunately i don't think you saw it.

Hi, Thanks for the reply on github in relation to issue #2306

I should have added this in the original post, but enabling those settings and having it set to 0 and a health percentage then it doesn't recommend those 2 spells at all
https://i.imgur.com/hUdydmP.jpeg

Unless there is another reason it's not recommending them i'm not sure.

Done a bunch of keys and still same result... at no point under 80% HP did it recommend shield wall with these settings.

Unless i'm still missing something about this, this is where my confusion lies.

**Comment by PKoka5** [comment]
Do you have an update on this for the patch v11.0.02-1.0.14a.
