### ISSUE TITLE
Evoker Preservation Spec Missing

### ISSUE THREAD

**Issue by Brudersma** [Hekili/hekili#2307]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Only the Devastation Spec is available in Hekili. I cannot get my Preservation spec to show at all. I have reloaded my ui, tried changing my spec to Devastation and back to Preservation, reset my profile and even deleted the addon and re-added it. I only have a few other addons loaded and there does not seem to be any sort of conflict. No matter what I do, Hekili just will not work with the Preservation spec on my Evoker.

### How to Reproduce

It is a constant issue. No matter what I try, the preservation spec is just not found. I had a friend try on his account and he also cannot use Hekili with his Evoker Preservation spec. It only works with Devastation.

### Player Information (Link)

```Text
build: v10.0.2-2.0.15a
level: 70 (70)
class: EVOKER
spec: preservation

talents: none

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: amberquill_shroud = 1
    bramble_chain_hauberk = 1
    brimming_arcanocrystal = 1
    carved_basalt_ring = 1
    emboldened_dracthyrs_tabard = 1
    pioneers_leather_boots = 1
    riveted_drape = 1
    sandencrusted_greaves = 1
    sharpened_silver_sword = 1
    shikaar_scout_pauldrons = 1
    solemn_seashell_string = 1
    tamed_eagle = 1
    thrumming_celestial_arrangement = 1
    trailblazers_scale_bracers = 1
    trailblazers_toughened_chainbelt = 1
    trailblazers_toughened_grips = 1
    water_ordained_signet = 1

legendaries: none

itemIDs: 192017, 193386, 193393, 194366, 197656, 197989, 197990, 198006, 198021, 198037, 200182, 200186, 200212, 200536, 201948, 201950, 202197

settings: none

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 

warnings: none
```

### Error Messages (Link)

```Text
There are no error messages in BugSack
```

### Contact Information

brudersma#5254

**Comment by chevyn11** [comment]
It's almost amazing that you seem to have tried everything except read the main /hekili page that says healers aren't supported.

**Comment by Nistmaru** [comment]
To be honest, the main Hekili page in CurseForge does not mention that healers are not supported. I'm sorry that someone felt the need to be a rude troll. This should be a place where people can come for help rather than snark.

**Comment by Hekili** [comment]
Please don't be overly critical of questions here, but it is correct that healers are not actively supported at this time.  Thanks.
