### ISSUE TITLE
Microstuttering after leaving Combat and Looting

### ISSUE THREAD

**Issue by SuperKnuxx** [Hekili/hekili#2308]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Microstutters after Combat / Looting, this seems to happen on ALL characters.

### How to Reproduce

Kill a mob or loot a mob causes micro stutter

### Player Information (Link)

```Text
build: v10.0.2-2.0.15a
level: 62 (62)
class: HUNTER
spec: beast_mastery

talents: a_murder_of_crows
    animal_companion = 1/1
    aspect_of_the_beast = 1/1
    barbed_shot = 1/1
    barbed_wrath = 1/1
    beast_cleave = 2/2
    beast_master = 2/2
    bestial_wrath = 1/1
    binding_shackles = 1/1
    binding_shot = 1/1
    born_to_be_wild = 1/2
    camouflage = 1/1
    cobra_shot = 1/1
    counter_shot = 1/1
    death_chakram = 1/1
    improved_kill_command = 2/2
    improved_kill_shot = 1/1
    keen_eyesight = 2/2
    kill_command = 1/1
    kill_shot = 1/1
    killer_command = 2/2
    misdirection = 1/1
    multishot = 1/1
    natural_mending = 2/2
    natures_endurance = 1/1
    one_with_the_pack = 1/2
    pack_tactics = 1/1
    pathfinding = 2/2
    piercing_fangs = 1/1
    posthaste = 2/2
    scent_of_blood = 2/2
    sharp_barbs = 2/2
    stomp = 2/2
    survival_of_the_fittest = 1/1
    trailblazer = 2/2
    training_expert = 2/2
    war_orders = 2/2
    wild_call = 1/1
    wilderness_medicine = 2/2

pvptalents: dire_beast_basilisk
   dire_beast_hawk
   hunting_pack

covenant: none

conduits: none

soulbinds: []

sets: none

gear: ascended_defenders_crest = 1
    band_of_chronicled_deeds = 1
    cinch_of_uncertain_devotion = 1
    expedition_mercenarys_boots = 1
    expedition_mercenarys_grips = 1
    expedition_mercenarys_hauberk = 1
    expedition_mercenarys_leggings = 1
    expedition_mercenarys_wristwraps = 1
    humble_aspirants_helm = 1
    molten_flak_cannon = 1
    primalist_pendant = 1
    ranged = 1
    reverberating_silver_band = 1
    skyloom_cloak = 1
    stonewatchers_eye = 1
    waylight_shoulderguards = 1

legendaries: none

itemIDs: 173316, 173330, 173339, 173342, 173344, 175704, 175718, 194346, 194352, 194369, 194382, 194402, 194413, 199031, 200252

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Beast Mastery
    petbased = false
    potion = spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    avoid_bw_overlap = false
    barbed_shot_grace_period = 0.5
    check_pet_range = true

toggles: cooldowns = true [separate]
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = true [overridden]
    interrupts = false [separate]
    mode = single 
    potions = false 

keybinds: 
    a_murder_of_crows     = F   [06]
    aspect_of_the_cheetah = SX  [03]
    aspect_of_the_turtle  = 0   [01]
    barbed_shot           = 2   [01]
    bestial_wrath         = Q   [06]
    binding_shot          = G   [06]
    camouflage            = 9   [01]
    cobra_shot            = 3   [01]
    counter_shot          = SZ  [03]
    death_chakram         = E   [06]
    dire_beast_basilisk   = =   [01]
    dire_beast_hawk       = 7   [01]
    disengage             = SV  [03]
    exhilaration          = CC  [03]
    feign_death           = 6   [01]
    kill_command          = 1   [01]
    kill_shot             = SC  [03]
    misdirection          = SB  [03]
    multishot             = 4   [01]
    tranquilizing_shot    = CF  [03]
    wing_clip             = -   [01]

warnings: none
```

### Error Messages (Link)

```Text
No error messages
```

### Additional Information

I think it might be a conflict with Zygor guides but not thoroughly tested this

**Comment by Hekili** [comment]
I do not have a way to test vs. Zygor guides.  What makes you think it is this addon having an issue?

**Comment by SuperKnuxx** [comment]
It could be Hekili or zygor to be honest, if I have them both running this problem happens. If I turn zygor off it goes away vice versa.

**Comment by SuperKnuxx** [comment]
> I do not have a way to test vs. Zygor guides. What makes you think it is this addon having an issue?

Just done some more testing. It is not zygor now, tested more with just Hekili and I get the microstutters.

**Comment by TheLegendTotam** [comment]
Signed up specifically to comment on this thread as I am having a very similar issue. I've tried extensive testing of disabling just about every add on and weakaura I have installed and the problem seems to keep pointing to Hekili. With Hekili loaded I'm getting micro freezes of <1 second entering and leaving combat. This also seems to occur when jumping between mobs in combat after the first initial freeze ie, combat starts, microfreeze, kill mob, shadowstep to new mob, microfreeze, kill mob, microfreeze right before combat ends. Outside of combat performance is flawless(i9-9900k, 2080, 32GBDDR4). A fresh reload of the UI seems to prevent the issue for 15 or so minutes before it randomly rears its' head. I noticed this occur for the first time last Tuesday during raid night when combat began on Eranog. The only time I have been able to prevent the issue is by uninstalling or disabling Hekili. Repairing game files/reinstalling all addons yesterday proved no change. I'll continue messing around this week.

**Comment by Hekili** [comment]
So far, I've removed some globals that could've contributed to taint and taint logging that impact performance, but I'll continue to look for other possible issues.  I'll definitely need Issue Reporting information for each example where people are experiencing issues, so I can see if there are consistent issues with particular specs or settings.

**Comment by Oswalend** [comment]
I just downloaded this addon for the first time and upon loading the game up there is a few seconds that the game stutters. Then on occasion when I enter combat the whole game lags to the point of not being able to do anything.  I can’t pinpoint exactly what it is but I did turn off CD, potions, and interrupts and it has seemed to help a little bit but didn’t fix the problem.

**Comment by Hekili** [comment]
If adding to this thread, you must include:
* your installed and enabled addons when the issue occurs
* whether you detect the issue when the addon is paused (ALT-SHIFT-P) or not
* whether you detect the issue with the addon loaded but disabled (/hekili disable)
* the information from /hekili > Issue Reporting

Please include all of these details along with any other narrative description you provide.

If you were previously using the addon without this issue, please try older releases of the addon (working backward from the latest) and let me know if you find a particular version that does not have the issue.

**Comment by slizersteam** [comment]
you might want to reset your wtf folder in your wow directory

**Comment by Hekili** [comment]
I've been looking into this again.  I've found that, under some circumstances, splitting the addon's calculation work across multiple frames has a significantly higher performance impact than getting it over and done in a single frame.  I'm trying to figure out the exact breaking point so I can set up default options.

I expect that I'm going to change default behavior to calculate all recommendations in a single frame, then turn on throttling for the most complicated specs with harder priorities to calculate.

**Comment by RussellAnas** [comment]
Hey - I wanted to add to the thread as I am experiencing the same and I just don't want to disable the addon just because of stutters:

your installed and enabled addons when the issue occurs (YES)
whether you detect the issue when the addon is paused (ALT-SHIFT-P) or not (NO ISSUE DOES NOT OCCUR)
whether you detect the issue with the addon loaded but disabled (/hekili disable) (ISSUE DOES NOT OCCUR)

The issue is reproduced easily on retribution paladin with defensive, interrupts etc. enabled and attacking aoe dummies in valdrakken. I'm not sure what else to add here to make it helpful since a snapshot isn't going to capture this data.

**Comment by lucas-lima-s** [comment]
I can confirm that still happening. Is there any expectation of resolving this issue?

**Comment by Amerigowarlock** [comment]
Hello, I confirm this is still happening because of (my guess is) a weird interaction with AutoPotion.
It only happen with both addons on. If only one of them is on there is not stutter.
