### ISSUE TITLE
Arcane Mage full mana Evocation

### ISSUE THREAD

**Issue by dvandervlag** [Hekili/hekili#2309]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When not in combat, or when engaging into combat, Hekili tells me to use Evocation instantly. This seems like a bug to me, as Evocation should be used when under 10%-20% mana (Or directly after an Arcane Surge).

There's little to no use in using it on 100% mana.

### How to Reproduce

1. Enter the game (I am playing on a level 54 arcane mage currently when making ticket)
2. Load talent loadout specified below
3. Notice evocation get's recommended.

### Talent Loadout

B4DAHVkVsxxZrVqBmAzlSR2f7jAAiIJFQSTIikIJCgWg0SCAAAAAAAAAAAQkkkECSyBA

### Snapshot

https://pastebin.com/CUEcM0PD

**Comment by elsavira** [comment]
This is correct behaviour due to the talents you selected: https://www.wowhead.com/spell=384187/siphon-storm

**Comment by Hekili** [comment]
elsavira is correct.
