### ISSUE TITLE
Azerite essences/cooldowns being recommended at wrong times for shadow priest

### ISSUE THREAD

**Issue by pbelsley97** [Hekili/hekili#231]
**Describe the Bug/Issue**
As a shadow priest, the addon is telling me to use Lucid Dreams/shadowfiend at different times than the default APL says to use

**To Reproduce**
log into a shadow priest with memory of lucid dreams major power equipped
enter combat
the 1st spell it recommends to cast will be memory of lucid dreams

**Expected behavior**
the addon will not recommend you to cast lucid dreams before you have higher stacks of voidform 

Issue Reporting tab:
https://pastebin.com/m0x8NuFz

Snapshot of issue occuring:
https://pastebin.com/6DuzeRyR

**Comment by Hekili** [comment]
I'm looking into this.  Can you look at your Shadow priority and confirm that your "cds" action list has Memory of Lucid Dreams included?

**Comment by pbelsley97** [comment]
Can confirm that Memory of Lucid Dreams is 1st in the cds Action list, and has the following conditions: 
( buff.voidform.stack > 20 & insanity <= 50 ) | buff.voidform.stack > ( 26 + 7 * buff.bloodlust.up ) | ( current_insanity_drain * gcd.max * 3 ) > insanity

**Comment by vhamran** [comment]
Happened to me too after i swaped from Focusing Iris to Memory of Lucid Dream. Dunno how to fix would like help too.

**Comment by Hekili** [comment]
A temporary workaround is to turn off the entry for "Heart Essence" (the generic one) as that is the one that is morphing into MoLD at the wrong time.

The addon isn't supposed to morph HE into an essence that already exists in your priority, so I have to keep investigating that bit.  I'm not seeing this on my end.

**Comment by Hekili** [comment]
Should be fixed in v8.2.5-02.
