### ISSUE TITLE
After using Algeth'ar Puzzle Box on Unholy DK, Manic Grieftorch is shown for 20 seconds instead of the next ability

### ISSUE THREAD

**Issue by goonreboot** [Hekili/hekili#2310]
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After using Algeth'ar Puzzle Box on Unholy DK, Manic Grieftorch is shown for 20 seconds instead of the next ability. This only appears to be a problem during Unholy DK opener, however I don't have both of these trinkets on another class to test.

### How to Reproduce

1. Use Unholy DK opener
2. Use Algeth'ar Puzzle Box trinket with Manic Grieftorch equipped
3. Bug has been reproduced, and the only suggestion shown is Manic Grieftorch for 20s until you use it

### Talent Loadout

BwPAdLUHklrTr3hBIcYWdbnCGDAkISSSgEESSEiIJSkAAAAAAAAAAKJJhIAAgEpItEJJJSC

### Snapshot

https://pastebin.com/gLMZZKwT

### Raidbots Sim Report (Link)

N/A

**Comment by Hekili** [comment]
This should be resolved in the first release for 10.0.5 tomorrow.
