### ISSUE TITLE
Burn Maelstrom before Primordial Wave bug

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2311]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

I decided to test this function and found a problem. When the readiness cooldown of the Primordial Wave remains somewhere 3-4sec and we have 7-8 stacks of Maelstrom. Then the addon does not always recommend using Chain lightning in AOE to use the remaining Maelstrom stacks. This bug happens if we have Lava lash and Frost shock used before using Primordial Wave. They can generate a lot of Maelstrom stacks in aoe. I think it makes sense to take this point into account. I still see that this function works well when we have 10 stacks of Maelstrom. We need a condition that if we have 6+ stacks of Maelstrom and the Primordial Wave ability is ready for 1-2 seconds, then use one of the following abilities to spend Maelstrom

### How to Reproduce

1. Start a battle with 5 targets in the city.
2. Make 7-8 stacks of Maelstrom
3. The next ability will be Primordial Wave.

### Talent Loadout

BcQAfcj78nJtvjmejSqe5Zhm9IJJpEJISSISCUSkAAAAAAAAAAAAAQJCBSUSRIk0SSSBgEJBA

### Snapshot

https://pastebin.com/7z6ZNvbd

**Comment by Hekili** [comment]
In your snapshot, the recommendation is for Lightning Bolt.

edit:

> Then the addon does not always recommend using Chain lightning in AOE to use the remaining Maelstrom stacks.

There's still a priority to actions and Chain Lightning is not going to jump into top priority ahead of other big cooldowns.  If you can show me Chain Lightning not getting recommended when Primordial Wave is ready in 1-2 GCDs despite no higher priority abilities being available, I'll look at it again.  Otherwise, you will need to start thinking about doing your own sim testing and custom priorities.  I'm not going to take this much further than I have.

**Comment by Dragonfo** [comment]
https://pastebin.com/jRvJcQ72 I've attached where I have 6 stacks and the recommendation was Primordial Wave. In this case, any other ability should have been used to spend 6 stacks. But not as an overcap.

**Comment by Hekili** [comment]
Thanks, this is based on a typo.  It'll be fixed in the first 10.0.5 release.
