### ISSUE TITLE
[Outlaw Rogue] GCD during Adrenaline Rush. Sinister strike GCD.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#2312]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Almost all Outlaw abilities have 1 second GCD baseline (thus in Outlaw  gcd = "totem" is being used) but it is lowered to 0.8 seconds during Adrenaline Rush window which is not being accounted by the addon. 
[Effect 3 from Adrenaline Rush](https://www.wowhead.com/spell=13750/adrenaline-rush)

EDIT: It might be already implemented considering Line 3146, 3159 here https://github.com/Hekili/hekili/blob/dragonflight/State.lua
But during gameplay it feels like I am pressing next ability recommendation and it goes of while according to add-on GCD should not be ready from the previous ability pressed. It could be ping issue though.

As a side note [Sinister Strike also has 1 second GCD baseline](https://www.wowhead.com/spell=193315/sinister-strike), but it is coded as  [**gcd = "spell"** at Line 1261](https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/RogueOutlaw.lua)

Also does [Dreadblades ](https://www.wowhead.com/spell=343142/dreadblades)     [Line 1042](https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/RogueOutlaw.lua)

The GCD of the following spells is also 1 second, but it is not affected by Adrenaline Rush [Effect 3 from Adrenaline Rush](https://www.wowhead.com/spell=13750/adrenaline-rush). Thought I do not think it is important to exclude these from Adrenaline Rush GCD multiplier)
[Dismantle](https://www.wowhead.com/spell=207777/dismantle)         [Line 992](https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/RogueOutlaw.lua)

[Smoke Bomb](https://www.wowhead.com/spell=212182/smoke-bomb)        [Line 1288](https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/RogueOutlaw.lua)

### How to Reproduce

-

### Talent Loadout

-

### Snapshot

-

### Contact Information

IIeTpoc#3818 discord ID

**Comment by IIeTpoc** [comment]
EDIT: It might be already implemented considering Line 3146, 3159 here https://github.com/Hekili/hekili/blob/dragonflight/State.lua
But during gameplay it feels like I am pressing next ability recommendation and it goes of while according to add-on GCD should not be ready from the previous ability pressed. It could be ping issue though.

**Comment by Hekili** [comment]
The current GCD will be shown based on the game API itself, not the addon.  Modeled behavior is for future predictions, not the current state of things.

If you have snapshots, reproduction criteria, talent information, and confirm there is a problem, you can fill out the rest of the ticket and I'll look at it.

**Comment by IIeTpoc** [comment]
Yep, most likely it is ping. Ty for the answer, the GCD animation in the addon and my ability bars is the same.

**Comment by Hekili** [comment]
Thanks for updating/closing.  Enjoy 10.0.5 (soon!).
