### ISSUE TITLE
[Outlaw Rogue] 10.0.5 Fan The Hammer post nerf Combo Point gain adjustment.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#2313]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

In 10.0.5 [Fan the Hammer Combo Points gain will be nerfed.](https://www.wowhead.com/guide/classes/patch-10-0-5-changes)

[Pistol shot](https://www.wowhead.com/spell=185763/pistol-shot) gives 1 combo point baseline. Due to [Quickdraw talent](https://www.wowhead.com/spell=196938/quick-draw) giving "original" [Oppotunity buff](https://www.wowhead.com/spell=195627/opportunity) it gives 1 more CP when Pistol Shot is Half-Cost.

[Pre nerf Fan the Hammer](https://www.wowhead.com/spell=381846/fan-the-hammer):  Half-cost uses of Pistol Shot consume 1 additional stack of Opportunity to fire 1 additional shot (Max 2 additional stacks). 
Each of them gives 2 combo points without any other modifiers (6 combo points in total with no other modifiers)

[Post nerf Fan the Hammer](https://www.wowhead.com/ptr/spell=381846/fan-the-hammer): Half-cost uses of Pistol Shot consume 1 additional stack of Opportunity to fire 1 additional shot. **Additional shots generate 1 fewer combo point**.
Now only first, "original" stack gives 2 combo points (without any modifiers). Other 2 stacks upon consumption will give (2-1=1) combo points each, resulting in 4 combo points overall without any modifiers from Roll The Bones.

### How to Reproduce

-

### Snapshot

-

### Contact Information

IIeTpoc#3818 discord ID

**Comment by Hekili** [comment]
Ticket not needed.
