### ISSUE TITLE
[Destruction Warlock] Sacrafice Demon Showing in Roation after Sac 

### ISSUE THREAD

**Issue by Enzlow** [Hekili/hekili#2315]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Sacrafice Demon Showing in Roation after Sac 

### How to Reproduce

Enter as Destruction Warlock 
Pick Talent Sacrafice
Sacriface Demon 
After about 2 seconds It says to summons another demon 

### Talent Loadout

BsQAbtPS25JQs0VfQSDmhm+p3ggkEJSg0SLCSLJJkWgDkokkkEQr0kEAAAAAAAAAAAAJHAlkA

### Snapshot

https://pastebin.com/vuS6DZdQ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/azPqumsnCyVUxSS3G94zP1

### Additional Information

Just trying to help! 

### Contact Information

Enzlow #6472

**Comment by Hekili** [comment]
Will be addressed soon; thanks.
