### ISSUE TITLE
sin rogue recommending puzzle box as first action in opener

### ISSUE THREAD

**Issue by fridge2065** [Hekili/hekili#2316]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

addon is recommending puzzle box as first action as opener when it should be right before deathmark or after

### How to Reproduce

equip puzzle box as sin rogue  use kingsbane ST build or DTB build...target test dummy

### Snapshot (Link)

https://pastebin.com/RrHMY5rT

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dKwzkBE99kEvDjF5gVTBZQ

**Comment by vond82** [comment]
Yeah seems to have snuck in for sin aswell when it was added for outlaw and sub (as they do want it prepull)

**Comment by fridge2065** [comment]
its been like that for awhile now ..just decided to post it after the most recent update

**Comment by Hekili** [comment]
@fridge2065 Your snapshot isn't readable; please post it to Pastebin and provide a link instead.

**Comment by fridge2065** [comment]
dropped a link to the pastebin hope thats correct

**Comment by Hekili** [comment]
This will go away in the 10.0.5 release, but you can disable the entry in the Assassination priority list (/hekili > Priorities > Assassination > Action Lists > precombat).  I think it's the 3rd entry.  Just uncheck Enabled.
