### ISSUE TITLE
[FEATURE] UH DK - PVP Talent : Raise Abomination (PvP talent) can be added to the CD spell list

### ISSUE THREAD

**Issue by Ohemx** [Hekili/hekili#2317]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Raise Abomination (PvP talent)  is  a major CD for UH Dks, it will be very useful to be added to the CD list for out door PvP, BGs ..etc
good for players that play both PvP and PvE.

**Comment by Hekili** [comment]
Raise Abomination currently shares its settings with Army of the Dead, and is already on the cooldowns toggle.  What makes you think it cannot be controlled with the cooldowns toggle?

**Comment by Ohemx** [comment]
thanks for clearing that out I didn't know was shared setting with army of the dead.
