### ISSUE TITLE
[BUG] Prot Warrior - Avatar not being called as a cooldown

### ISSUE THREAD

**Issue by Kedakaiqt** [Hekili/hekili#2319]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Prot warrior avatar is not being called as a cooldown or normal rotation.

### How to Reproduce

1. Enter game as prot warrior with avatar talented.
2. Enter combat
3. ??? No avatar

### Player Information (Link)

https://pastebin.com/YnNQie20

### Error Messages (Link)

N/A

### Contact Information

Kedakai#7309

**Comment by Dirty-git** [comment]
Buff ID changed from 107574 to 401150 .

**Comment by Hekili** [comment]
This will be resolved in the next release.
