### ISSUE TITLE
[BUG] no rotation is displayed

### ISSUE THREAD

**Issue by miezomat** [Hekili/hekili#2321]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

WOTLK - Classic - All options are set as recommended. Addon is enabled, profile is resettet, Alpha is 1. BugSack/BugGrabber don't report any issues. I can place the frames. In combar nothing is shown. After i close the hekili options window the frames still remain visible and can be moved around, but when i start combat the are missing. 

### How to Reproduce

1. start a fight

### Player Information (Link)

https://pastebin.com/g3VpJxq1

### Error Messages (Link)

no bugs 

### Additional Information

![Screenshot 2023-01-25 114303](https://user-images.githubusercontent.com/123550675/214543387-9e8fd952-d0e4-4605-918c-9f3827589d2a.png)
![Screenshot 2023-01-25 114436](https://user-images.githubusercontent.com/123550675/214543396-c70120e1-f7ba-4681-a405-9aca3172958c.png)

### Contact Information

discord: Miezomat#6612

**Comment by miezomat** [comment]
Sorry, i just found [WOTLK] Mage plugin isn't working at all. #2139 i think it's the same issue. i didn't see this when i first was looking through the list

**Comment by miezomat** [comment]
for my druid it works fine

**Comment by Hekili** [comment]
Some specs are not yet supported for Wrath.  There's no need to open a ticket; what you see is what you get, for the time being.
