### ISSUE TITLE
[MM Hunter] Salvo does not get recommended after 10.0.5 update

### ISSUE THREAD

**Issue by RussellAnas** [Hekili/hekili#2322]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

[MM Hunter] Salvo does not get recommended

### How to Reproduce

1. Enter game as marksman hunter
2. Attack multiple adds or dummies
3. Salvo spell does not get recommended

### Snapshot (Link)

https://pastelink.net/9uctasce

**Comment by Hekili** [comment]
This is resolved in 1.0.2, but I'm sure the Marksmanship priority will have more adjustments to account for Salvo over time.  Thanks!
