### ISSUE TITLE
Feral druid game crash 

### ISSUE THREAD

**Issue by Neferpitou43** [Hekili/hekili#2324]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

i use avatar of ashamane and addon telle me to stealth i use avatar of ashamane  rake restealth like it tells me, rerake and it crash's the game with and error code 
 ERROR #132 (0x85100084) fatal exception 

programc;\Program files(x86)\world of
warcraft\_retail\Wow.exe
ProcessID:           20808
ThreadID:            20156
Exception:           ACCESS_VIOLATION

The instruction at '0x00000176336751d8' referenced memory 
at '0x00000176336751d8'
The memory could not be 'executed'

this only happens when hekili is enabled all other addons have been disabled to check that hekili was the cause with that rotation on feral druid on any target this will happen 

### How to Reproduce

Enter game as feral stealth use  avatar of ashamane, feral frenzy rake restealth and rake again once u do game should crash again only happens when hekili is loaded 

### Player Information (Link)

build: v10.0.5-1.0.2b level: 70 (70) class: DRUID spec: feral  talents: apex_predators_craving     astral_influence = 2/2     berserk = 1/1     berserk_frenzy = 1/1     berserk_heart_of_the_lion = 1/1     bloodtalons = 1/1     brutal_slash = 1/1     carnivorous_instinct = 1/2     circle_of_life_and_death = 1/1     doubleclawed_rake = 1/1     dreadful_bleeding = 1/1     feline_swiftness = 2/2     feral_frenzy = 1/1     frantic_momentum = 2/2     frenzied_regeneration = 1/1     improved_swipe = 1/1     incarnation = 1/1     incarnation_avatar_of_ashamane = 1/1     incessant_tempest = 1/1     infected_wounds = 1/1     innervate = 1/1     killer_instinct = 2/2     lycaras_teachings = 3/3     matted_fur = 1/1     merciless_claws = 1/1     mighty_bash = 1/1     moment_of_clarity = 1/1     moonkin_form = 1/1     natures_vigil = 1/1     omen_of_clarity = 1/1     pouncing_strikes = 1/1     predator = 1/1     predatory_swiftness = 1/1     primal_fury = 1/1     primal_wrath = 1/1     raging_fury = 1/1     rake = 1/1     rampant_ferocity = 1/1     renewal = 1/1     rip = 1/1     rip_and_tear = 1/1     sabertooth = 1/1     skull_bash = 1/1     soothe = 1/1     soul_of_the_forest = 1/1     stampeding_roar = 1/1     starfire = 1/1     sunfire = 1/1     survival_instincts = 1/1     tear_open_wounds = 1/1     thrash = 1/1     tigers_fury = 1/1     typhoon = 1/1     ursols_vortex = 1/1     wellhoned_instincts = 2/2     wild_charge = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: [niya]  sets: algethar_puzzle_box = 1     tier29 = 4  gear: algethar_puzzle_box = 1     awakened_planar_pillar = 1     belt_of_burning_focus = 1     boots_of_burning_focus = 1     bottle_of_spiraling_winds = 1     cape_of_entanglement = 1     elemental_lariat = 1     jeweled_signet_of_melandrus = 1     lost_landcallers_claws = 1     lost_landcallers_leggings = 1     lost_landcallers_mantle = 1     lost_landcallers_robes = 1     loyal_flametenders_bracers = 1     platinum_star_band = 1     stoneroot_headdress = 1     tier29 = 4  legendaries: none  itemIDs: 109787, 109829, 134542, 144094, 193001, 193692, 193697, 193701, 193708, 195504, 195525, 200351, 200353, 200355, 200356  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 3     damageOnScreen = true     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Feral     petbased = false     potion = spectral_agility     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     rip_duration = 9  toggles: cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      algethar_puzzle_box   = S4  [06]     barkskin              = X   [06]     bear_form             = A1  [05]     brutal_slash          = 2   [07]     cat_form              = A4  [05]     dash                  = S7  [06]     entangling_roots      = A3  [05]     feral_frenzy          = 7   [07]     ferocious_bite        = SMwD[06]     frenzied_regeneration = 2   [09]     growl                 = 1   [09]     haymaker              = A5  [05], 3   [10]     healthstone           = A9  [05]     incapacitating_roar   = 4   [09]     incarnation           = S6  [06]     innervate             = AN- [05]     ironfur               = 7   [09]     mangle                = MwD [09]     mark_of_the_wild      = SN- [06]     mighty_bash           = S1  [05]     moonfire              = 2   [01], 1   [10]     natures_vigil         = N+  [01], 6   [07]     primal_wrath          = 4   [07]     prowl                 = S9  [06]     rake                  = MwU [07]     regrowth              = S8  [06], 5   [10]     rejuvenation          = 6   [01]     renewal               = 9   [07]     rip                   = SMwU[06]     shred                 = MwD [07]     skull_bash            = S2  [05]     soothe                = A8  [05]     stampeding_roar       = A6  [05]     starfire              = 4   [01]     starsurge             = MwU [01]     sunfire               = 2   [10]     survival_instincts    = M3  [06], MwU [10]     thrash                = 5   [07], 5   [09]     thrash_bear           = 5   [07], 5   [09]     thrash_cat            = 5   [07], 5   [09]     tigers_fury           = S5  [06]     travel_form           = A2  [05]     typhoon               = 5   [01], 8   [07]     ursols_vortex         = 3   [07]     wild_charge           = 1   [01], 1   [07]     wrath                 = MwD [01]  warnings: none

### Error Messages (Link)

n/a

**Comment by Hekili** [comment]
This is not an issue specific to the addon; Blizzard is looking into it.
