### ISSUE TITLE
Hunter MM - Salvo is now an Active and its never suggested

### ISSUE THREAD

**Issue by Stringer123** [Hekili/hekili#2325]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sience yesterday's update Salvo is now an Active skill, replaced the old Double Tap that got removed, the addon never suggests to use it which I could understand in a single target scenario but its impossible in an AoE scenario since it throws 2 explosive shots.

### How to Reproduce

1. Enter as Hunter MM
2. Try to do the suggested AoE rotation anywhere/on dummies, Salvo never gets suggested

### Snapshot (Link)

https://pastebin.com/NYjpDVRi

### Contact Information

Stringer#8814 on Disc

**Comment by Hekili** [comment]
You'll want to update to the latest version.
