### ISSUE TITLE
The ability Salvo is not showing up on rotation or even a option (hunter)

### ISSUE THREAD

**Issue by kodiak24** [Hekili/hekili#2327]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

there is a ability called (Salvo) that got added to hunters MM and it is not even on the hekilli abilities sheet as far as drop menus go nor on the rotation I know the latest patch said it was up to date but it is not with this ability anyways, Just wanted to bring it to your attention thank you.

### How to Reproduce

It's just not on the abelites sheet at all when the drop down menu is selected 

### Player Information (Link)

https://pastebin.com/SR8L0Lbj

### Error Messages (Link)

none

**Comment by Hekili** [comment]
You'll want to update to the latest version of the addon.
