### ISSUE TITLE
Warlock inquisitor's eye now passive

### ISSUE THREAD

**Issue by dkmike718** [Hekili/hekili#2328]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

The inquisitor's eye is now a passive talent and no longer needs to show up for rotations.  
Thank you for all your hard work and time.

**Comment by Hekili** [comment]
Yes, I know.  Why are you submitting a ticket about it?  Did you not update your addons?

**Comment by dkmike718** [comment]
I updated on curseforge.
