### ISSUE TITLE
[REC] Totemic Recall showing in actions but never suggested to cast while off CD

### ISSUE THREAD

**Issue by JPearson4110** [Hekili/hekili#2329]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am specced into Toemic recall for my Elemental Shaman and see it shows on the actios if the cooldown of Liquid Magma Totem is over 45 but when i cast the Magma Totem it stays on CD and no suggestion to cast Totemic Recall 

### How to Reproduce

Just run through rotation, never suggested

### Snapshot (Link)

http://NO SNAPSHOT AS NEVER SHOWS

### Contact Information

Ishkat#2751 - Discord

**Comment by Hekili** [comment]
The snapshot is required.  Take one when you think Totemic Recall should be recommended, but isn't.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Oriny** [comment]
HI , i have same problem and look for what is the problem and i have found the require toggle for this spell is default lisen as defensive , switch the toggle to none fix the problem and spell is suggestes on the bar.
