### ISSUE TITLE
is wotlk support dead ?

### ISSUE THREAD

**Issue by codeduph** [Hekili/hekili#2330]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

last update was **Oct 22, 2022** and ToC isn't even updated for 3.4.1...

**Comment by Hekili** [comment]
@zmsl Has been handling Wrath support in his fork which hasn't been rolled back into this release yet.  See https://github.com/zmsl/hekili/releases.
