### ISSUE TITLE
Balance Druid Defaulting to all Stellar Flare

### ISSUE THREAD

**Issue by Pulseonline** [Hekili/hekili#2331]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For some reason and I cant tell what it is, all 5 icons that I have enabled are defaulting to just all Stellar Flare, when just sitting there out of combat and i've occasionally got it in combat as well.  

### How to Reproduce

Enter game as Balance druid and turn on Hekili CDs enabled.

### Snapshot (Link)

https://pastebin.com/cWR0DTX3

### Contact Information

Pulse#0223

**Comment by Pulseonline** [comment]
I will say, this was working perfectly until this very latest update

**Comment by eriksen080499** [comment]
I am having same issue.
Balance druid is not working properly.
Worked fine before update.

**Comment by Hekili** [comment]
If adding to the ticket, please submit snapshots via Pastebin rather than long text.  I am investigating this issue and it should be resolved shortly.

**Comment by Hekili** [comment]
@Pulseonline If you can provide an example of it occurring in combat, that would help.  I can't replicate it there.

**Comment by Hekili** [comment]
Posting my fix in a few minutes (1.0.3a).

**Comment by PhilipH3ro** [comment]
still issue https://pastebin.com/80tdbJYf

**Comment by shindead72** [comment]
I am having the same issue no ss - it doesnt happen when in incarn though.

**Comment by Hekili** [comment]
@shindead72 Post a snapshot when you see it, and make sure you've updated to the latest version.

**Comment by shindead72** [comment]
https://gyazo.com/c5a203b64d6191a4bae5caedd8634fc8

https://gyazo.com/f00a1d5f98af6bbc80608b7cb52b7041

**Comment by Hekili** [comment]
@shindead72 Snapshots, not screenshots.  

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by shindead72** [comment]
https://pastebin.com/zknQJxru

**Comment by shindead72** [comment]
just to note - I have updated twice today and have just now noticed another update which i have just applied. I will try and recreate the issue again.

**Comment by shindead72** [comment]
This has now fixed the issue - again sorry for wasting your time. I honestly didnt see you had just posted another update.

Thank you for your help and time!!!!

**Comment by Hekili** [comment]
No problem, thanks for testing and confirming.
