### ISSUE TITLE
Decoration of flamme not recommended as pal prot Since Hekili-v10.0.2-2.0.14

### ISSUE THREAD

**Issue by Lulua59** [Hekili/hekili#2333]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since the Hekili-v10.0.2-2.0.14 the trinket decoration of flamme is no longer recommended.

### How to Reproduce

Everytime the trinket is up.

### Snapshot (Link)

https://pastebin.com/eb7wGA2P

**Comment by Hekili** [comment]
```
28.  decoration_of_flame ( trinkets - 6 )
The action (decoration_of_flame) is usable at (0.00 + 0.00).
 - this entry's criteria FAILS: ( buff.moment_of_glory.up[false] | ! talent.moment_of_glory_enabled.enabled[false] & buff.avenging_wrath.up[false] ) & ( ! trinket.t2.has_cooldown[false] | trinket.t2.cooldown.remains[0.00] | variable.trinket_priority[1.00] = 1 ) | boss[false] & trinket.t1.buff_duration[0.01] >= fight_remains[427.38]
```

The trinket would've been used if Avenging Wrath were up, or if you were talented for Moment of Glory and Moment of Glory were up.

**Comment by Lulua59** [comment]
It's work with avenging Wrath, but if u pick Sentinel, doesn't work anymore

**Comment by Hekili** [comment]
This should be resolved in the latest releases; if not, please comment with an updated snapshot.  Thanks!
