### ISSUE TITLE
Stuttering: Same as Issue  #2194

### ISSUE THREAD

**Issue by Bios777** [Hekili/hekili#2334]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

During performance optimization I went through all of my addons and found out that hekili was causing me stuttering every 1-2 seconds. The description perfectly fits the issue  #2194. By disabling Hekili everything is fine again.

### How to Reproduce

Simply enter the game. Nothing special is causing it.

### Player Information (Link)

https://pastebin.com/MuYWs8YN

### Error Messages (Link)

There is no error message

**Comment by Hekili** [comment]
Then don't open a second ticket.
