### ISSUE TITLE
Hekili not flashing over consoleport button bars

### ISSUE THREAD

**Issue by n47h4ni3l** [Hekili/hekili#2335]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hi, I would like the button flashing to work over consoleport bars. The consoleport dev team has generously supplied me with the code needed to give to you.

local CPActionButtonEvent = LibStub("CPActionButton"):GetScript("OnEvent")
local function ShowGlow(spellId)
    CPActionButtonEvent(_, "SPELL_ACTIVATION_OVERLAY_GLOW_SHOW", spellId)
end
local function HideGlow(spellId)
    CPActionButtonEvent(_, "SPELL_ACTIVATION_OVERLAY_GLOW_HIDE", spellId)
end

Thank you kindly.

**Comment by Hekili** [comment]
The button flashing is supplied by SpellFlashCore, which appears to no longer be maintained.  I do not plan to reimplement SpellFlash without a pre-existing library.
