### ISSUE TITLE
Balance Druid - Primordial Arcanic Pulsar value 0

### ISSUE THREAD

**Issue by PhilipH3ro** [Hekili/hekili#2336]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

https://i.imgur.com/c78LKey.jpeg
It is not gathering the pulsar value from the tooltip correctly anymore

### How to Reproduce

Play balance druid
Have Primordial Arcanic Pulsar talent
See value

### Snapshot (Link)

https://pastebin.com/mdsqvcYN

**Comment by Hekili** [comment]
Thanks for this report.  I've updated the spell ID for arcanic pulsar and can see it tracking accurately now.  This will be in 1.0.3c.
