### ISSUE TITLE
Frost Mage AOE isn't recommending Blizzard

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#2337]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili is detecting 5 targets but it isn't recommending Blizzard and it's not on cooldown.

### How to Reproduce

Hitting 5 target dummies in city while playing Frost spec.

### Snapshot (Link)

https://pastebin.com/0nLF5nyJ

**Comment by Odeon91** [comment]
I confirm that blizzard is gone from the rotation of the wizard and the problem is not solved either by updating the addon or reainstalling it

**Comment by Hekili** [comment]
The Frost Mage priority is written to use its AOE action list at 7+ targets (or 3+ with Ice Caller talented).

`active_enemies[5.00] >= 7 | active_enemies[5.00] >= 3 & talent.ice_caller.enabled[false]`

Blizzard also appears in the single-target action list, if you have 2+ targets and both Ice Caller and Freezing Rain talented.

`active_enemies[5.00] >= 2 & talent.ice_caller.enabled[false] & talent.freezing_rain.enabled[false]`

For confirmation, you can sim your character on Raidbots with a Patchwerk fight style and 5 boss targets.  Check how many casts of Blizzard you see.

**Comment by Odeon91** [comment]
I'm noticing a few oddities: the first that if I keep the 'addon in aoe there are no errors with two and more blizzard targets is shown.
But if I keep the addon in automatic blizzard despite having multiple targets it is not recommended.
Another oddity I have no problem if I log another mage and use the addon, yet they have the same options turned on

**Comment by Odeon91** [comment]
ok it would seem that the problem only arises on the dummies, I tried on the mobs and it advises right

**Comment by Hekili** [comment]
All dummies, or specific dummies?

**Comment by Odeon91** [comment]
On dummy groups ( I am currently in Valdrakken and it does not detect blizzard despite being 5 targets)

**Comment by Hekili** [comment]
> On dummy groups ( I am currently in Valdrakken and it does not detect blizzard despite being 5 targets)

Just a reminder; Blizzard requires 7 targets by default, 3 targets with Ice Caller, or 2 targets with Ice Caller and Freezing Rain.

If you didn't take Ice Caller at the very least, 5 dummies will not get you a Blizzard recommendation with the current priority.
