### ISSUE TITLE
MM Hunter Salvo Duplicate

### ISSUE THREAD

**Issue by tharpy35** [Hekili/hekili#2338]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Salvo is applied, you then use Multi-Shot or Volley which then apples Explosive Shot. However, the addon is recommending Explosive Shot while the DoT is still on target and has not exploded. If used while DoT is active, it overwrites the original so you only  get two explosions rather than three. Recommend the addon not recommending Explosive shot until the DoTs from Salvo have exploded.

### How to Reproduce

1. Enter the game as Marskmanship Hunter
2. Take Salvo as talent
3. Target enemy
4. Use Salvo
5. Fire Multi-Shot or Volley
6. Review the recommendations as Explosive Shot will be recommended during the DoT of the original Explosive Shots

### Snapshot (Link)

https://pastebin.com/H8GHTadk

**Comment by Hekili** [comment]
Please put your snapshot on pastebin and link it.  It is not readable like this.

**Comment by tharpy35** [comment]
Done, sorry about that.
    On Thursday, January 26, 2023 at 08:03:25 PM EST, Hekili ***@***.***> wrote:  
 
 


Please put your snapshot on pastebin and link it. It is not readable like this.

**Comment by Hekili** [comment]
lol

I need an original from in-game.  Your Pastebin doesn't have line breaks either.  Please copy a snapshot from in-game, put it on Pastebin, and provide the link here.  Thanks.

**Comment by tharpy35** [comment]
Third times the try!

**Comment by Hekili** [comment]
> target_debuffs:
>   212431 - explosive_shot                           -   1 - 0.52  

In your snapshot, you have Explosive Shot on the target, but it expires in 0.52 seconds.

> Marksmanship; Primary - Manic Grieftorch(0.00), Explosive Shot(1.66), Death Chakram(2.90), Wailing Arrow(4.14)

The Explosive Shot recommendation is in 1.66 seconds.  They aren't overlapped in your snapshot.

**Comment by tharpy35** [comment]
Hello,
Must be an in game bug then. Casting Salvo and then using Volley or Multi-Shot puts Explosive shot on the target, then in my set up Volley is next with Explosive Shot after. When I cast Explosive shot, the debuff on target increases to 5 seconds, but the original one still explodes. Then the second one 2 seconds later for a second explosion.
Thanks,
    On Thursday, January 26, 2023 at 08:47:14 PM EST, Hekili ***@***.***> wrote:  
 
 



target_debuffs:
212431 - explosive_shot - 1 - 0.52


In your snapshot, you have Explosive Shot on the target, but it expires in 0.52 seconds.


Marksmanship; Primary - Manic Grieftorch(0.00), Explosive Shot(1.66), Death Chakram(2.90), Wailing Arrow(4.14)


The Explosive Shot recommendation is in 1.66 seconds. They aren't overlapped in your snapshot.

**Comment by Hekili** [comment]
> Must be an in game bug then. Casting Salvo and then using Volley or Multi-Shot puts Explosive shot on the target, then in my set up Volley is next with Explosive Shot after. When I cast Explosive shot, the debuff on target increases to 5 seconds, but the original one still explodes. Then the second one 2 seconds later for a second explosion.

Take the snapshot when Explosive Shot is being recommended despite Explosive Shot already being on the target, if that's the issue you're reporting.  The snapshot is from in-game, so I don't think I understand the confusion.

**Comment by tharpy35** [comment]
My bad on this one. I was using different abilities because of the quick change the addon was doing to recommend something else. My old brain just can't keep up with the kids these days. Sorry to have wasted your time.    On Thursday, January 26, 2023 at 10:44:08 PM EST, Hekili ***@***.***> wrote:  
 
 



Must be an in game bug then. Casting Salvo and then using Volley or Multi-Shot puts Explosive shot on the target, then in my set up Volley is next with Explosive Shot after. When I cast Explosive shot, the debuff on target increases to 5 seconds, but the original one still explodes. Then the second one 2 seconds later for a second explosion.


Take the snapshot when Explosive Shot is being recommended despite Explosive Shot already being on the target, if that's the issue you're reporting. The snapshot is from in-game, so I don't think I understand the confusion.
