### ISSUE TITLE
[Priest/Shadow]active_dot.vampiric_touch not working as expected

### ISSUE THREAD

**Issue by aohajin** [Hekili/hekili#2341]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shadow priest's APLs seems to have some problems in AOE cases. It will always be stuck and only recommend mind spike very soon after the AOE begins.

I tried this on the AOE training targets in Valdrakken, After first wave of PI/shadow fiend boost, hekili would only recommend mind spike and mind sear rotation while there were obviously better choice in APLs like void torrent, highlighted mind blast.

I took a snapshot and found the variable active_dot.vampiric_touch always returned 1, no matter I used shadow crash to get them vt debuff or manually casted vt on them one by one.

This totally mess the AOE rotation.

### How to Reproduce

1. Enter the game as shadow priest
2. Use talent with shadow crash, psychic link, misery,mind spike, for example mine: BIQA16pR6xQxvK1VWhXk+w0/GkQSLEAAAAAAAAAAAAAikoEplUgkkUSikEoFJ5AJShUIBJCpFkAA
3. Use default hekili setting, display mode as "Automatic"
4. Target one of the AOE training dummy targets, and do whatever hekili tell you.
5. After the shadow fiend expires(the second shadow crash cycle), the recommandation will go wrong.

### Snapshot (Link)

https://pastebin.com/z8F5jkku

### Contact Information

Discord ID: aohajin#2566

**Comment by Hekili** [comment]
Dummies "die" repeatedly, which purges off-target dot tracking.  There's not really anything to be done about it.
