### ISSUE TITLE
GetRecommendedAbility

### ISSUE THREAD

**Issue by Six6pounder** [Hekili/hekili#2344]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

GetRecommendedAbility is broken for many classes since 01/23/2023-Hekili-v10.0.2-2.0.16.zip, everytime you call that function you receive lua errors and it doesn't return nothing, for warrior fury and arms is broken, for rogue sub it works, I don't know what's causing the issue. Thanks for the support.

I don't know if it can help but last working version was 1/18/2023-Hekili-v10.0.2-2.0.16-beta2.zip

### How to Reproduce

1. Enter the game as Fury warrior (other classes have the same issue)
2. Call the function 'Hekili_GetRecommendedAbility("Primary", 1);' 
3. Lua errors 

### Player Information (Link)

https://pastebin.com/KtVC3K1h

### Error Messages (Link)

https://pastebin.com/fFiiSuVw

**Comment by Hekili** [comment]
Is it possible that you have WeakAuras enabled on some characters and not others?  I'm making an adjustment that the recommendation payload will be prepared regardless of having WeakAuras installed/running.

**Comment by Six6pounder** [comment]
> Is it possible that you have WeakAuras enabled on some characters and not others? I'm making an adjustment that the recommendation payload will be prepared regardless of having WeakAuras installed/running.

Tried to disable WeakAuras completely but still the same issue

**Comment by Hekili** [comment]
Disabling WeakAuras complete would've worsened the issue, not improved it.  Can you post updated errors from the latest release(s) and confirm which version of the addon you're using now?

**Comment by Six6pounder** [comment]
I'm using latest version [v10.0.5-1.0.4a] (2023-01-29) and now it's working again, no errors so far, I didn't test all classes but looks like it's fixed. Thank you for the support and for the awesome addon 👍
