### ISSUE TITLE
[BUG] Unholy keeps recommending Anti-Magic Shell wrongly

### ISSUE THREAD

**Issue by chiraino** [Hekili/hekili#2347]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Anti-Magic Shell provides no offensive benefit.  I also do not have Defensives checked.

### How to Reproduce

1. Just be in combat as Unholy. It'll come up after a few abilities.

### Player Information (Link)

https://pastebin.com/WyH2vMkV

### Error Messages (Link)

https://pastebin.com/WyH2vMkV

**Comment by Hekili** [comment]
Anti-Magic Shell is intentionally included in your DPS priority, consistent with simulations, but I understand that you likely would rather use it defensively instead.  You can disable it for yourself:  /hekili > Abilities > Anti-Magic Shell > Disable Anti-Magic Shell.
