### ISSUE TITLE
[FEATURE] Wotlk classic Surv hunter r4/r3 explosive shot rotation

### ISSUE THREAD

**Issue by Rorobor** [Hekili/hekili#2349]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'd like Hekili to add r4 and r3 explosive shot rotation for lock and load procs. when it happens sometimes it gets flooded with other casts and makes it hard to keep track of

### Contact Information

Discord ID- Dew#9428

**Comment by Hekili** [comment]
You'll have to provide a lot more specific information if you would like to see a change made.  Where is this r4/r3 explosive shot rotation?

**Comment by Rorobor** [comment]
It's supposed to occur during lock and load procs. You cast one r4
explosive shot followed by r3 explosive shot then another r4 explosive
shot. Three explosive shots total r4/r3/r4 uses all lock and load charges

**Comment by Hekili** [comment]
Sure, but I'll need sources that show that this is a beneficial change.

**Comment by Rorobor** [comment]
from Survival Hunter DPS Rotation, Cooldowns, and Abilities - Wrath of the
Lich King Classic - Guides - Wowhead
<https://www.wowhead.com/wotlk/guide/classes/hunter/survival/dps-rotation-cooldowns-abilities-pve>

Due to recent discoveries that Rank 3  Explosive Shot
<https://www.wowhead.com/wotlk/spell=60052/explosive-shot> and Rank 4
Explosive
Shot <https://www.wowhead.com/wotlk/spell=60053/explosive-shot> do not
override each other, the best thing to do during  Lock and Load
<https://www.wowhead.com/wotlk/spell=56344/lock-and-load> is the following
rotation below. Doing this will result in a fairly significant dps increase
over filling the gap between Rank 4 explosive shots with another ability
such as  Steady Shot <https://www.wowhead.com/wotlk/spell=49052/steady-shot>,
or  Black Arrow <https://www.wowhead.com/wotlk/spell=63672/black-arrow>.

   1.  Lock and Load
   <https://www.wowhead.com/wotlk/spell=56344/lock-and-load> - Lock and
   Load procs.
   2.  Explosive Shot
   <https://www.wowhead.com/wotlk/spell=60053/explosive-shot> - Cast your
   first Rank 4 Explosive Shot immediately.
   3.  Explosive Shot
   <https://www.wowhead.com/wotlk/spell=60052/explosive-shot> - Cast Rank 3
   Explosive Shot
   4.  Explosive Shot
   <https://www.wowhead.com/wotlk/spell=60053/explosive-shot> - Cast your
   second Rank 4 Explosive Shot

**Comment by Hekili** [comment]
I've added a commit that *might* help with this but maybe not.

**Comment by Flax78** [comment]
Hey @Hekili , 
just found this.
Actualy i have made a castsequence Macro (reset=5) with Rank 4 followed by Rank 3 explosive shot.
But how can is get my Hekilli to show me this rotation?

atm i use this modified Version of Survival (call of Wild etc. are withing macros, thats why i disabled them).
I just have no clue how to add Rank 4 -> Rang 3 -> Rank 4 during  Lock&Load proccs

As of Sim that would be an at least 120DPS increase.

```
Hekili:vAvWsUjoq0pMuvQSv2Gny7zYSvMCypKAhFWxyQAVjqacJklKOKeM1x03EAjIbblE8Klgq6Px361QFYOq0RO4cSMGoeToAZ6hJ2eegUD3UTOy9LgckUbNFcFeEHJRHFJBLNPNXmt6N6eD6S8GJh)dlQlmbUWYMs0kZbKvADJ6VwTAag8MMDAvodRuF5ylTGOwP(fDFPQLRjYvO4Swkt)chLnjVIcdbMBi5OdBaQPffKEievok(1kQYK2iPcjvFXKA)kdRifMub3KQRiM0H0WK(VsSUYK6sHaumJQ0kNoqkXTmn86HWR)OrXeooJrkq)nkoh4NiPyumoxtf8aSnN0jIYeiijNPnezGMwtsuuEoe1VzsFWK(riDAllxeDBJB(CHGvi64bK)RHju0ZafvcDGKuJPCy)8Dt66RHfKcnbxCXbbsXdrlNUxrpnUfs8rbVc3DYFdzdUltQXCCaKz5eU2f2OD2qSXQqlkf2vogR(cPkPglpzx3w76UoPe3qlskPsYixzwu78rLJzSRjBhLvmd7d(yprbS5IAiRNJ7rFCnI(NJ7aaXx9r0QijWwQwnd0t3EJtCv1zvSPYX0jT8fU(MeQXYJeDGOvRGJMHE17mg0gMGLsrNJJW7Xrhvxr5(umMjAOm4yj6MSyxeGKWj1us)PVOrQQHUe6W(52NmEBwolymYfhfB)FLuh7tleHtoKGHUSIfH9W9kyknLFunRqPiYg4eFIBshpp6Zt27sJlLcLEuF)6VtBPZoWpkkIUprTDKhjj2h9OwOp9BpBsHmXg1N8LjFJIj6e8zJKaDoz4bhV3HHXeP(2NFEBpHn3TZC77CpadCgy2cZ7IIoSKBvou8l1ncP2ErqKjTNptQZWpWS3QaIskdmJ(WhmPJxT9pU81S3oAyOj9hKmzlwc3SyJHzVzFpvQGbj8ZpV6wI2YO91K)Kw(SZ)DrK9c0YZ5jnEP19OhMF0j2F05oV(Z5702lnJZv2c392QsQeDm)1ml1HrgCz9hCQjPlDVP1Q)68CfTlAU95YHW2D6H(AtSp4b)nlUPMyFpYhyVf29qnyO5p4O)L)OtCH8ecpllF4J(n3zhnPfc3QReGvZWFjY1iH(5d
```
