### ISSUE TITLE
Error while in combat

### ISSUE THREAD

**Issue by Jagear** [Hekili/hekili#235]
I am running the addon in combat and I got this error.  It has happened mutliple times since the last update 

Message: Interface\AddOns\Hekili\Core.lua:1241: attempt to compare number with nil
Time: Sun Nov  3 23:02:27 2019
Count: 768
Stack: Interface\AddOns\Hekili\Core.lua:1241: attempt to compare number with nil
[C]: ?
Interface\AddOns\Hekili\Core.lua:1241: in function `ProcessHooks'
Interface\AddOns\Hekili\UI.lua:804: in function <Interface\AddOns\Hekili\UI.lua:668>

Locals: 

any ideas?

**Comment by JerkyGunner** [comment]
Chiming in with the same problem, but turning off Essences seems to have fixed it.

**Comment by Calen81** [comment]
Just got the Major Essence unlocked on a newly dinged DK, and now I get this error too, every time i target something.
I switched to my main, (hunter with full essence unlocked), and no errors there.

**Comment by Hekili** [comment]
Thanks, should be fixed in 8.2.5-04.01 -- report back otherwise.
