### ISSUE TITLE
[FEATURE] Ability to override Shield of Vengeance 20% hp loss over 3 seconds so that it gets recommended precombat

### ISSUE THREAD

**Issue by phatzz** [Hekili/hekili#2350]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hi
snapshot:
https://pastebin.com/DW7XzCUW
I added multiple instances of calling for "Shield of Vengeance" to be recommended precombat or at the start of combat, with no luck.
Looking at the snapshot it seems to have some hidden conditions based on hp % lost built into the ability:
"The action (shield_of_vengeance) is unusable at (0.00 + 0.00) because incoming damage over 3s is less than 20% of max health."

I would like to be able to override this so that it is suggested based on the conditions in the action list, instead of abiding to this.

**Comment by Hekili** [comment]
This should probably be a specialization setting at some point, but is not at the top of my to-do list.

**Comment by Hekili** [comment]
This will be available as a setting in /hekili > Retribution in the next release.  You can set the slider to 0 and the addon won't require any detected damage before using SoV.
