### ISSUE TITLE
WotLK DK : nothing on screen ! 

### ISSUE THREAD

**Issue by ivoriginz** [Hekili/hekili#2351]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is working on my warlock, my paladin, but when I log my DK, nothing is present on screen. 
I tryied to uninstall, re-DL, reinititialize profile ... nothing works ! If someone can help, it would be nice. 

### How to Reproduce

1. Enter game with DK (WotLK)
2. Try /hekili and put unholy spec.
3. See that nothing is working

### Player Information (Link)

https://pastebin.com/zzEUNjX0

### Error Messages (Link)

https://pastebin.com/RrhSeGTt

### Contact Information

Antho#4884     (Discord)

**Comment by Hekili** [comment]
Please update to the latest Wrath release.  If you are still having issues, submit a new ticket.
