### ISSUE TITLE
Guardian Druid not recommending raze on ST at all and not enough on AOE. Not using Tooth and Claw Procs on ST.

### ISSUE THREAD

**Issue by rasenkunai** [Hekili/hekili#2352]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon is not recommending Raze on ST under any condition even with Tooth and Claw procs and with 3 stacks of Vicious Cycle. I also feel like it's not recommending Raze enough on AOE as well. It's prioritizing swipe over raze even with excess rage and Tooth and Claw Procs.

### How to Reproduce

1.) Enter the game as Guardian Druid.
2.) Take Raze, Tooth and Claw and Vicious Cycle talents.
3.) Follow rotation provided by Hekili on ST tank and/or non-tank dummies and AOE dummies.

### Snapshot (Link)

https://pastebin.com/DNGdxpnE

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cUEuhwC2fTPJL9Sv7RNseZ

### Additional Information

https://www.raidbots.com/simbot/report/jGviAF3mWUQKjp7JHWFFDr

### Contact Information

Epluchage#3985

**Comment by Hekili** [comment]
It seems that Druid theorycrafters agree, as they've updated the Guardian profile to use Raze more.  This will be posted tonight.

Keep in mind, Raze is also impacted by the `Excess Rage for Maul (or Raze)` setting in your /hekili > Guardian options.
