### ISSUE TITLE
[BUG] Chat Spam + FPS Drop

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#2353]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I noticed today fps drops while I was doing keys on my demo lock, after updating Hekili.  There were also these messages appearing in chat a lot:

```
07:53 Hekili: Phase change for next_tyrant [ Primary ] (from 77.186000000002 to 91.392).
07:53 Hekili: Phase change for next_tyrant [ AOE ] (from 77.186000000002 to 91.421999999999).
```

### How to Reproduce

1. DPS as demo lock with Hekili on

I don't know if build matters, but I'm using the nether portal build from mplus.subcreation.net this week: BoQA041aTpyHyczNbmCyk1bsJgESSkIBSTJCS7AJJkWAAAAAQLSSSIBSIRyBi0SicACAAAAAAA

### Player Information (Link)

https://pastebin.com/v8GWvR4W

### Error Messages (Link)

no error

**Comment by Hekili** [comment]
I'll remove the debug print.
