### ISSUE TITLE
[BUG] Text in caht  during Warlock rotation

### ISSUE THREAD

**Issue by javenjefven** [Hekili/hekili#2354]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

during demo loch rotation - text in chat appears constantly stating " Hekili: Phase change for next_turant ( Primary ) (from 43.471000000002 to 57.495000000112)

### How to Reproduce

1. Play loch in demo spec
2. go in combat
3. check chat

### Player Information (Link)

https://pastebin.com/Q1Vfif9i

### Error Messages (Link)

none

### Additional Information

none

**Comment by Hekili** [comment]
This is already resolved. Update your addon.
