### ISSUE TITLE
Guardian druid won't recommend Mangle without specing into mangle upgrade

### ISSUE THREAD

**Issue by dapal-003** [Hekili/hekili#2355]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using guardian druid, mangle is one of the primary ways of generating rage and thus staying alive. The ability is not recommended in the current queue when the guardian talent "Mangle" on the 3rd row is not selected. This talent does not unlock the ability, rather it just improves it by giving 20% extra damange on bleeding targets. Without having the talent Hekili does not recommend using Mangle while it is available to cast.

### How to Reproduce

1. Enter game as Guardian druid
2. Select talents that does not include Mangle on the guardian tree third row. 
3. Use major cooldowns to get to the rotation recommendations
4. Going through the primary recommendations Mangle will not appear while available to cast.

### Snapshot (Link)

https://pastebin.com/n2mwtaG6

### Raidbots Sim Report (Link)

N/A as far as I know

### Additional Information

The snapshot states the following:
57.  mangle ( bear - 23 ) - talent [ mangle ] missing
Whilst yes, the talent is missing, the ability it self is not and can still be cast.

### Contact Information

Dapal#0695

**Comment by Hekili** [comment]
Good catch, I'll remove the talent requirement.
