### ISSUE TITLE
Hilight existing icons

### ISSUE THREAD

**Issue by Tawg23** [Hekili/hekili#2356]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hilight existing icons like MaxDPS instead of flashing your own set of icons.  During battle it would help a lot to just click the hightlighted icon instead of having to search my existing icons.

**Comment by Hekili** [comment]
You can use a similar feature via the SpellFlash tab of each display.  If you don't want the addon's icons to show, be sure to check "Hide Display."

![image](https://user-images.githubusercontent.com/9438134/216129618-ac18e380-3f4d-440a-b32e-0f71adb93d0e.png)

**Comment by Tawg23** [comment]
Thank you for the quick reply and resolution.

You guys are doing a nice job on this addon.


Bill Dudek
