### ISSUE TITLE
Elemental not loading for Shaman

### ISSUE THREAD

**Issue by Logieuk** [Hekili/hekili#2357]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have installed Hekili and used it for Brew, DH and Enh shaman. When i try Elemental Shaman there is no information filled in on Elemental on Share Styles. 

Under Priorities there is on Enhancement showing

Been unable to make my own and import

### How to Reproduce

1. Log into came
2. Change shaman to elemental in game
3. Hekili no longer showing suggested rotation abilities
![Hekiliprob](https://user-images.githubusercontent.com/124194736/216126961-5fa24fc2-900c-42bb-8c01-81fdc4b3acef.jpg)

### Player Information (Link)

https://pastebin.com/39a6xFT0

### Error Messages (Link)

not applicable

### Additional Information

I have tried bugsack and buggrabber and no errors are shown

### Contact Information

Logie#1686

**Comment by Hekili** [comment]
Thanks, this will be fixed in 1.0.6a.
