### ISSUE TITLE
Balance Druid recommending Celestial Alignment when on cooldown

### ISSUE THREAD

**Issue by Xenon45** [Hekili/hekili#2358]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Currently, when I am going through the rotation it keeps recommending Celestial Alignment when it is still on cooldown 

### How to Reproduce

Just follow the rotation in a target dummy 

### Snapshot (Link)

https://pastebin.com/JDCrT0pR

**Comment by Hekili** [comment]
Can you post your talent export string from your game client?

Can you confirm that Celestial Alignment was on cooldown at the time of your ticket?

**Comment by Xenon45** [comment]
You can close this now I figured out why it was being recommended so when you have not taken Incarnation: Chosen of Elune it will stay up in recommend soon as I took that talent it started working fine I dont believe this is an issue anymore

**Comment by Hekili** [comment]
This did illustrate a *potential* issue that I couldn't replicate directly; when Incarnation is talented, Celestial Alignment will be disabled (since Incarnation replaces Celestial Alignment).  I never did see Celestial Alignment recommended under these circumstances, but the logic has been added for completeness.
