### ISSUE TITLE
Rogue Subtlety - Suggesting Shuriken Storm during Shuriken Tornado

### ISSUE THREAD

**Issue by outlawrogueforever** [Hekili/hekili#2359]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shuriken Storm is being suggested while Shuriken Tornado has just been used in the previous GCD and while it is still active. Will be quite confusing to newer sub rogue players learning the spec and may bait them into pressing Shuriken Storm while Shuriken Tornado is active.

### How to Reproduce

1. Play Subtlety Rogue
2. Take Shuriken Tornado Talent
3. Fight AOE Dummies and perform your rotation as suggested
4. While Shuriken Tornado buff (277925 - shuriken_tornado) is up, you'll see Shuriken Storm suggestions, more frequently when it is used outside of Shadow Dance window

### Snapshot (Link)

https://pastebin.com/6LnBTx2x

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mdxLA4Zac2USViPXA58ABJ

### Additional Information

The issue only applies to AOE scenarios

### Contact Information

Ame#9781

**Comment by Hekili** [comment]
I'm going to more assertively model the auto-casts of Shuriken Storm during Shuriken Tornado, but the timing is a bit more challenging than I anticipated.

**Comment by outlawrogueforever** [comment]
Sounds good, thanks for the update!
