### ISSUE TITLE
[WOTLK] Warlock, Hekili is not displayed.

### ISSUE THREAD

**Issue by WerlingWI** [Hekili/hekili#2361]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Most of the time the rotation bar is not visible. If it is visible, it will not be processed. I have already deactivated all addons and reinstalled Hekili. As soon as you go into the settings of Hekili, an error message is thrown.

### How to Reproduce

1. Enter the Game as Affli Warlock
2. No rotation seen
3. /hekili or other way into the settings, generates the error message

### Player Information (Link)

https://pastebin.com/DWUAfda4

### Error Messages (Link)

https://pastebin.com/b6t0pv5D

**Comment by Hekili** [comment]
Please update to the latest Wrath release.  If you are still having issues, submit a new ticket.
