### ISSUE TITLE
ElvUi raid/party frames range check (fader) conflict with Hekili on preservation evoker

### ISSUE THREAD

**Issue by romonlol** [Hekili/hekili#2362]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Preservation evoker have 30 yds range, but Hekili overrides it to 40 yds, even if addon is disabled/paused. 

And yes i understand that hekili doesn't working with healer specs, but every time when you are respeccing from dps to heal, you forced to disable addon completly or you cann't understand who out of range and who is not, which is frustrating.

### How to Reproduce

1. Enable Hekili and Elvui
2. Join random party or group
3. You will be able to see, frames fade out on 40 yds

### Player Information (Link)

https://pastebin.com/5xdKD1qE

### Error Messages (Link)

skip

**Comment by Hekili** [comment]
If ElvUI's range-checking on friendly nameplates is impacted by my addon, it's an issue with ElvUI.
