### ISSUE TITLE
Balance druid defensive on cd

### ISSUE THREAD

**Issue by Fluke667** [Hekili/hekili#2368]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

i am a Balance druid, how to set Barkskin on CD?
i want use it always in mythic dungeons on CD

But howto do this?

Hekili got so many Options and i cannot find anything

### How to Reproduce

i am a Balance druid, how to set Barkskin on CD?
i want use it always in mythic dungeons on CD

But howto do this?

Hekili got so many Options and i cannot find anything

### Snapshot (Link)

no snapshot

**Comment by Hekili** [comment]
Barkskin isn't part of the DPS priority for Balance by default.  You could make a custom priority that includes it, but custom priorities are not something I would provide active support for.  See https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions for information about that.
