### ISSUE TITLE
[REC] Sin rogue failed to make recommendation (possibly from poisons falling off)

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2369]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Was on dummy and got a message about no recommendation. From the looks of the snapshot it looks like its because poisons fell off but there was no recommendation to re-apply poisons.

### How to Reproduce

Happened at some point doing regular rotation on dummy.

### Snapshot (Link)

https://pastebin.com/hkjyMncd

**Comment by Hekili** [comment]
I'm making an update that will ensure more poisons can be refreshed in combat, though I'm not certain that is the make-or-break factor here.

**Comment by Hekili** [comment]
Because I'm making changes to Subtlety (that impact Assassination, too) in the next build, please open a new ticket with a new snapshot if you observe this again.  Thanks!
