### ISSUE TITLE
Hunter pet ability whitelist request

### ISSUE THREAD

**Issue by Thordros** [Hekili/hekili#237]
I noticed a handful of Hunter pet skills can't be added to the priority—is it possible they aren't whitelisted? [Spirit Shock](https://www.wowhead.com/spell=264265/spirit-shock), [Nether Shock](https://www.wowhead.com/spell=264264/nether-shock), and [Survival of the Fittest](https://www.wowhead.com/spell=272679/survival-of-the-fittest) (and its [Marksmanship Lone Wolf version](https://www.wowhead.com/spell=281195/survival-of-the-fittest)) all don't work. If those aren't whitelisted, I suspect these aren't either, but I don't have the pets on hand to test them:

- [Serenity Dust](https://www.wowhead.com/spell=264055/serenity-dust)
- [Spore Cloud](https://www.wowhead.com/spell=264056/spore-cloud)
- [Soothing Water](https://www.wowhead.com/spell=264262/soothing-water)
- [Chi-Ji's Tranquility](https://www.wowhead.com/spell=264028/chi-jis-tranquility)
- [Nature's Grace](https://www.wowhead.com/spell=264266/natures-grace)
- [Primal Rage](https://www.wowhead.com/spell=264667/primal-rage)
- [Master's Call](https://www.wowhead.com/spell=53271/masters-call)

Not a high priority issue since this is all utility stuff. Just QoL stuff.

**Comment by Thordros** [comment]
also healthstones

**Comment by Hekili** [comment]
Healthstones should be available in 8.3.  The Hunter abilities should already be in when appropriate.  Submit a new ticket if anything is not working in 8.3.
