### ISSUE TITLE
[REC] Sin rogue recommending garotte instead of vanish->garrote when deathmark is up and vanish is available

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2370]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Seems like a non-vanished garrote is sometimes recommended (feels like if you spend one global incorrectly) even though deathmark is still rolling and vanish is available. In this case I'd expect vanish->garrote to be recommended rather than a garotte and keeping vanish on cd.

Probably something else I'm missing here, like trying to sync vanish with next deathmark instead, but just thought I'd raise it as it seems off.

Here's a second snapshot where a similar thing is happening on recommendation #3: https://pastebin.com/Tefp9jFW

### How to Reproduce

1. Spec improved garotte
2. Perform opener rotation until you get to the point where you can vanish garotte once original garotte is in pandemic
3. Addon sometimes recommends garrote without using vanish first.

### Snapshot (Link)

https://pastebin.com/2HSiYawS

**Comment by Hekili** [comment]
This appears to match sim behavior as intentionally written; it didn't want to burn your Vanish when you would be wasting some of the extra combo points.  If you provide a sim of your character, I can test to see whether it's valuable to go ahead and Vanish despite wasting combo points.

**Comment by fzarr** [comment]
My main reasoning for thinking this is that the garrote outside of stealth will not have the 50% damage from improved garrote, which is also duplicated during deathmark. I think imperfect play is sometimes causing situations the APL hasn't catered towards.

What sort of sim do you want, just a raidbots link to a standard sim?

**Comment by Hekili** [comment]
> What sort of sim do you want, just a raidbots link to a standard sim?

A sim of your character in the circumstances you're concerned about.

**Comment by fzarr** [comment]
https://www.raidbots.com/simbot/report/fbGyPo9hHQecBwJLWkwiK2

At 0:17:446, there is a mutilate followed by ambush, which would generate at least 4 combo points, yet it still uses vanish->ambush as the next action.

**Comment by Hekili** [comment]
> At 0:17:446, there is a mutilate followed by ambush, which would generate at least 4 combo points, yet it still uses vanish->ambush as the next action.

Can you elaborate?  Are you telling me that you think this is correct or that you think this is incorrect?  That the addon should match this, or that the sim should be different?

<html><body>


0:16.440 | direct | O | envenom | Fluffy_Pillow | 170.0/170: 100% energy 4.0/6: 67% combo_points | bloodlust, slice_and_dice, envenom, alacrity(4),  thistle_tea, echoing_reprimand_4, elaborate_planning, septic_wounds(5),  way_of_controlled_currents_stack(9), algethar_puzzle,  elemental_potion_of_ultimate_power
-- | -- | -- | -- | -- | -- | --
0:17.446 | direct | T | mutilate | Fluffy_Pillow | 170.0/170: 100% energy 0.0/6: 0% combo_points | bloodlust, slice_and_dice, envenom, alacrity(5),  thistle_tea, elaborate_planning, septic_wounds(5),  way_of_controlled_currents_stack(10), way_of_controlled_currents_surge,  algethar_puzzle, elemental_potion_of_ultimate_power
0:18.451 | direct | S | ambush | Fluffy_Pillow | 161.4/170: 95% energy 2.0/6: 33% combo_points | bloodlust, slice_and_dice, envenom, alacrity(5),  thistle_tea, blindside, elaborate_planning, septic_wounds(5),  way_of_controlled_currents_stack(10), way_of_controlled_currents_surge,  algethar_puzzle, elemental_potion_of_ultimate_power
0:19.457 | vanish | a | vanish | Rogue | 170.0/170: 100% energy 4.0/6: 67% combo_points | bloodlust, slice_and_dice, envenom, alacrity(5),  elaborate_planning, septic_wounds(5),  way_of_controlled_currents_stack(10), way_of_controlled_currents_surge,  algethar_puzzle, elemental_potion_of_ultimate_power
0:19.457 | stealthed | Y | garrote | Fluffy_Pillow | 170.0/170: 100% energy 4.0/6: 67% combo_points | bloodlust, slice_and_dice, vanish, envenom,  alacrity(5), improved_garrote_aura, elaborate_planning,  septic_wounds(5), way_of_controlled_currents_stack(10),  way_of_controlled_currents_surge, algethar_puzzle,  elemental_potion_of_ultimate_power


</body>
</html>

In the sim, you can see Mutilate was used at 0 combo points and generated 2, then Ambush was used to generate 2 more, and Vanish was used at 4 combo points.  The Vanish entry that was used is here:

<html><body>


a | 2.81 | vanish,if=talent.improved_garrote&cooldown.garrote.up&!exsanguinated.garrote&(dot.garrote.pmultiplier<=1\|dot.garrote.refreshable)&(debuff.deathmark.up\|cooldown.deathmark.remains<4)&combo_points.deficit>=(spell_targets.fan_of_knives>?4)
-- | -- |:--


</body>
</html>

For that Vanish to have been selected, `combo_points.deficit>=(spell_targets.fan_of_knives>?4)` had to have been true, which indicates the addon inverted min/max expressions.  I'm making that correction now and will post a new build.  This means that the combo_points deficit required will be the lesser of FOK targets or 4.

**Comment by fzarr** [comment]
Sorry - the sim behaviour seems correct to me in this case and is what hekili should also recommend, at least from what makes sense to me as being optimal - I would have to try and edit the APL to get the sim to garotte instead of vanish->garrote in this case to compare.

However, it seems that it always uses vanish->garrote, regardless of combo point state at that time which is confusing me due to that combo_point deficit line in the APL.

Here is a sim where it envenoms and vanish->garrotes on 0 cp (without me making any changes to APL etc): https://www.raidbots.com/simbot/report/mFVj4eQFe2a3bD6c9XFhgA

So I'm not sure where the vanish logic is coming from, almost like its hardcoded for this particular case.

**Comment by Hekili** [comment]
For clarity, sims are for making comparisons vs. in-game.  So, generally, you'd want to provide a snapshot of what you're describing and a sim of what you want to compare.

> For that Vanish to have been selected, combo_points.deficit>=(spell_targets.fan_of_knives>?4) had to have been true, which indicates the addon inverted min/max expressions. I'm making that correction now and will post a new build. This means that the combo_points deficit required will be the lesser of FOK targets or 4.

This means that your Mutilate -> Ambush -> Vanish -> Garrote example should now be addressed in the addon (at least in single-target or when your combo point deficit is greater/equal than how many targets FoK would hit (but no more than 4).

**Comment by fzarr** [comment]
Sorry for the delay in getting back, Seems to be working as expected now, thanks :D Will keep an eye on it.

**Comment by Hekili** [comment]
Thanks for giving lots of detail and talking through it!
