### ISSUE TITLE
For Spellflash, I selected a circle and I'm still getting a star flashing at me.

### ISSUE THREAD

**Issue by llchristopherson** [Hekili/hekili#2372]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

No matter which of the other textures I select under the Multiple --> SpellFlash tab, I only ever get the star. 

### How to Reproduce

1. Playing on my druid. Set everything up.
2. The icon flashes a star. No circle.

### Player Information (Link)

https://pastebin.com/qKTrPgRD

### Error Messages (Link)

None

### Additional Information

I use a Mac...

**Comment by llchristopherson** [comment]
Also, I can't find a thing on how to edit settings in Spellflash or I would've tried that.

**Comment by Hekili** [comment]
If you set the flash texture for each display individually, do you get a different result?  I.e., edit under the "Primary" display rather than "Multiple"?

**Comment by tangaiyun** [comment]
please disable the addon named as "masque"

**Comment by Hekili** [comment]
> please disable the addon named as "masque"

@llchristopherson Do you have Masque installed?  Did you try disabling it to see if you get a different result?  My addon is pretty aggressive about forcing the SpellFlash texture to change, so I'm really not sure what else might be causing.  It'd be helpful to try disabling other addons and turning them on one-by-one until you see what is interfering.

**Comment by llchristopherson** [comment]
I'm so sorry I didn't see this until today. I do not have any addon called Masque. 

I tried setting the texture for each and I got the same thing. It's still a star and not a circle. (So either multiple or primary--doesn't matter, still a star.)

I will try turning other addons off and seeing what happens and I'll let you know.

**Comment by Hekili** [comment]
Thanks.  I've reopened the ticket while you try to gather more information.

Do you have SpellFlash installed separately, by any chance?  The addon includes a version of SpellFlash already, so I wonder if perhaps it's being overwritten by another version?

**Comment by llchristopherson** [comment]
I didn't know that, so that is possible. I will uninstall both and reinstall ONLY Hekili. I'll get back to you soon (and thanks for your help!)

**Comment by llchristopherson** [comment]
Yep, that was it. I thought I was supposed to install SF. So SF was overriding your circle. THANKS!

**Comment by llchristopherson** [comment]
So now that I can see this... can I reduce the size of the circle?

**Comment by Hekili** [comment]
The size of the circle is controlled on the same tab where you set the texture.
