### ISSUE TITLE
Enhancement - Primordial Wave is a projectile

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2373]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

At the beginning of the battle, after pressing the Primordial Wave, Flame shock is shown in recommendation a, Light bolt should be shown. When we use Primordial Wave in rotation, there should not be a Flame shock recommendation next.

### How to Reproduce

1. Algetar box prepool.
2. Feral Spirit
3. Primordial Wave
4. Flame shock it should not be in the recommendation.

### Snapshot (Link)

https://pastebin.com/0Hf73aD5

**Comment by Hekili** [comment]
The addon relies on the game API to offer recommendations.  At the time recommendations were generated, you didn't have the Primordial Wave buff nor had Flame Shock applied to your target.

**Comment by Dragonfo** [comment]
I have tracked how the Flame shock recommendation is happening. It turns out that at the time of activation of the Primordial Wave, the ability has not yet worked on the main target (flying) will always recommend using Flame shock. Well, as I understand it, it's unrealistic to track it with an addon only to control it yourself.

**Comment by Hekili** [comment]
Mostly correct, yeah.  Primordial Wave has a travel time before it impacts and Flame Shock is applied.  I'll see if I can adjust it a bit.

**Comment by Hekili** [comment]
This will be modeled in the next build; it'll help or it won't.
