### ISSUE TITLE
{Retail}Druid Feral SMBG M+ Bonemaw Recommending Thrash repeatedly

### ISSUE THREAD

**Issue by Baxtercane21** [Hekili/hekili#2374]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Using the default auto rotation the addon recommends thrash nearly every other spell. Forcing single target mode intermittently will work (i have had it work flawless one time), but the game seems to think once the 2 extra adds are dead that they are directly under the boss and it will just request Thrash over and over regardless of combo points or priority of spells.

### How to Reproduce

1. Shadowmoon Burial Grounds M+
2. Work your way to Bonemaw (3rd boss)
3. Can try Auto or Single Target mode
4. If and when one or both of the extra tentacles die the addon I think places them not hittable under the boss which triggers multi target mode, I don't know if this is correct.

### Snapshot (Link)

https://pastebin.com/JHFQtVVU

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pGTt4qksh1vkqu4ensUew8

### Additional Information

I don't think it is a range issue, but possibly the thrash isn't registering a hit so it is prompting to recast it over and over, but I am close enough for all other spells/attacks. And seems to occur more once the two other adds are dead regardless of me helping to kill them or not.

### Contact Information

Baxtercane#7478

**Comment by Hekili** [comment]
You didn't copy/paste the whole snapshot; only the first line is in the Pastebin.

**Comment by vond82** [comment]
Its an issue with that boss and aoe abilities, its the same for any class/spec. You have to stand very very close for it to actually hit

**Comment by Hekili** [comment]
> Its an issue with that boss and aoe abilities, its the same for any class/spec. You have to stand very very close for it to actually hit

This is what I was anticipating; the condition for Thrash includes having the bleed applied to the target, so if you're out of range and the bleed doesn't apply, it will get recommended again.

**Comment by Baxtercane21** [comment]
I ran it again, and the snap shot shows the same just 3 spells, but if i am basically inside the boss it recommends correctly, eventhough it has i think an 11y range and all my other skills land just fine.

**Comment by Hekili** [comment]
You haven't provided me the complete snapshot.

The solution here is to get close enough to Bonemaw that Thrash actually applies its bleed.  It's a game problem, not an addon problem.

**Comment by Hekili** [comment]
I'm going to close since this is really a Blizzard issue.  I've sent them information about this range issue, but the real answer is to get real close to Bonemaw so your Thrash will apply.
