### ISSUE TITLE
Vengeance APL rewrite is merged

### ISSUE THREAD

**Issue by xClow** [Hekili/hekili#2376]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

https://github.com/simulationcraft/simc/pull/7331

Just a heads-up that this was merged earlier today. They say it’s a full rewrite basically?

### How to Reproduce

Sorry if this was the wrong category.

### Snapshot (Link)

NA

**Comment by Hekili** [comment]
Thanks; I routinely check for priority updates so there's no need to open tickets for this.  I'm reviewing the Vengeance changes now.  Looks a lot simpler.
