### ISSUE TITLE
[REC] Monk Windwalker: debuff.skyreach_exhaustion.down / up does not work

### ISSUE THREAD

**Issue by replikatoren** [Hekili/hekili#2378]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

see title

### How to Reproduce

priority tigerpalm if debuff.skyreach_exhaustion.down

### Snapshot (Link)

https://pastebin.com/cUkyheSV

**Comment by Hekili** [comment]
Thanks for the ticket.  I can see in your snapshot that you tried a lot of things to make it work, which must've been frustrating.  I am correcting the typo that caused Pressure Point to overwrite Skyreach Exhaustion.  It'll go in the next release.  Thanks!
