### ISSUE TITLE
Totemic Recall showing in actions but never suggested to cast while off CD 

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2379]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I have created a new theme regarding Windfury Totem and the Totemic Projection ability. I will try to prove to you the usefulness of Totemic Projection. I put a totem near 1 target at the beginning of the battle, and specifically left the range of the Windfury Totem so that I could see the Windfury Totem in the recommendations. At that moment, I had the Totemic Projection ability ready and if I activated it, the totem could move next to my character without using the GCD abilities of Windfury Totem. The benefit of Totemic Projection is that the ability itself does not have a GCD and can be used in 1 pressing of the ability without using the inner GCD of the shaman's spell abilities. And if we use Windfury Totem, then this ability leads our total cooldown of all abilities to recharge and thus does not allow us to immediately immediately use the next spell after Windfury Totem. There is a suggestion that you add the same condition as Windfury Totem only for Totemic Projection. When a character leaves the Windfury Totem range, the next ability to use Totemic Projection. And in this sequence, we will use Totemic Projection to move the totem faster without using GCD.

### How to Reproduce

1. Use Windfury Totem.
2. Step away from the totem until you see a recommendation to use the new Windfury Totem
3. Use Totemic Projection and the totem will move next to the character.

### Snapshot (Link)

https://pastebin.com/PePMkGLF

### Additional Information

You can test it in Waldraken on mannequins. Place the totem near a single dummy, and move to the opposite side and click Totemic Projection. In this sequence, I tested the work.

**Comment by Hekili** [comment]
I have thought about this myself, and the only thing that has kept me from implementing it, is half the time when I use Totemic Projection in a raid environment, I still don't end up with the benefit of my own Windfury Totem.

**Comment by Dragonfo** [comment]
At the moment I use this option, which is used by most shamans
#showtooltip Stormstrike
/cast [@player] Totemic Projection
/cast Stormstrike
This advantage can be felt in the raid when you use Gamba build where you need to always beat the boss to activate Ascendance. And in this build, we don't want to press the Windfury Totem button often. Because we need to use Stormstrike more often to activate 6% Ascendance. In such situations, Totemic Projection looks like an excellent choice because we use it immediately without delay in rotation.

**Comment by Dragonfo** [comment]
Using Totemic Projection gives us the opportunity to move our totem without GCD just by quickly pressing one button without a delay in rotation. In the meantime, the addon recommends us a full-fledged ability with GCD, which makes us a delay in rotation. The extra 1-3 seconds really play a role for us.

**Comment by Hekili** [comment]
The macro is a clever idea, though if you're dropping other totems it could be counterproductive.  If you're already macroing that, the addon shouldn't be needing to recommend Windfury Totem anyway, right?  As soon as you're in range and you Stormstrike, your WF totem is back with you.

**Comment by Dragonfo** [comment]
You all correctly said that if I use a macro, then there is a slight delay in the fact that the recommendation checks whether there is a totem nearby or not. I just thought that if we have the opportunity to use Totemic Recall, then the addon would suggest using Totemic Recall. And if Totemic Recall is on recharge, and we left the totem radius again, then the recommendation was offered by Windfury Totem. The main goal itself is to use less Windfury Totem and more Totemic Recall.

**Comment by Hekili** [comment]
I'll test having the addon assume you're in range of WFT if you have a totem up and have used Totemic Projection in the past second and see if that gives the client enough time to catch that you're now in range.  I may or may not add TP to the priority for such things; it'd have to be a spec option because sometimes you don't want to drop your totems under your butt.

**Comment by Dragonfo** [comment]
As a player, I just see it that way. But there is really a lot of truth and accuracy in your words. Well, I will believe that there will be time for you to find time to search for the best application of WTF. Now so far at the moment it is not very critical that we often use WTF, but I would like not to see it so often, of course, when we have Totemic Recall. The macro doesn't always work well because we use it too often at the expense of the main ability.

**Comment by Hekili** [comment]
Just remember, you can customize your priority if you want it to do things that aren't done in the sim and that I don't want to implement.  There's nothing preventing you from reading the FAQ regarding adding an ability to a custom priority.
