### ISSUE TITLE
SpellFlash:  Use LibCustom Glow, Allow Other Shapes, etc.

### ISSUE THREAD

**Issue by brentrichardjr** [Hekili/hekili#238]
Action Bar highlighting is my favorite feature of Hekili. Other addons (e.g. WeakAuras, MaxDPS) take advantage of [LibCustomGlow](https://www.curseforge.com/wow/addons/libcustomglow) to expand the functionality and customization of button glows, including texture overlays. Any chance this could get integrated into Hekili?

**Comment by Hekili** [comment]
To be clear, what you want is for the SpellFlash feature to have more customization options?  I can take a look.

**Comment by brentrichardjr** [comment]
Exactly, thank you, I really appreciate it. I've tried MaxDPS addon in the past but I much prefer Hekili. The only thing I really liked from MaxDPS was the action bar customization. By default its a circle (Interface\Cooldowns\ping4), but could be changed to the glows like SpellFlash or Blizzard. I stumbled across the library after digging around in my addons folder, particularly weakauras2 (who's author contributes to LibCustomGlow). Seeing as SpellFlash isn't maintained anymore, I figured LibCustomGlow may be something you'd be interested in exploring.

**Comment by Hekili** [comment]
I've used LibCustomGlow (and it is packaged with the addon).  However, the SpellFlash library is what locates abilities on your action bars and starts/stops the flash effect.  I'll see if it's relatively trivial to use it to use LibCustomGlow flashes instead of its default.

**Comment by dMopp** [comment]
Please please :). Custom Texture would be perfect

**Comment by Hekili** [comment]
It's still an okay idea, just not at the top of my priority list.

**Comment by N6REJ** [comment]
anyway to make the flash more noticeable?  Spell flash hasn't been updated in 2yrs.  It's VERY subtle

**Comment by Hekili** [comment]
Not a priority at this time.

**Comment by N6REJ** [comment]
@Hekili ok.. I know at least 2 people who will stop using hekili because of it.
for me, I like hekili just need to figure out the druid issue.

**Comment by Bigity** [comment]
This would be a feature I would use as well, FWIW.

**Comment by Tga123** [comment]
SpellFlashCore is in Public Domain, you can use any of currently working fork of it (eg from [here](https://github.com/Tga123/SpellFlashCore)).

**Comment by Hekili** [comment]
Closing, as the addon has allowed customizing the SpellFlash glow for a long time.  I have no plans to make use of LibCustomGlow.
