### ISSUE TITLE
[REC] Not Recommending Berserking as Arms Warrior

### ISSUE THREAD

**Issue by Ovaldo** [Hekili/hekili#2380]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In Arms spec, addon doesn't display Troll Racial spell Berserking. In Fury and Protection, they are displayed when other cooldowns are recommended. It has been like this since I started on Warrior in pre-patch Dragonflight and I assumed it was a quirk of pre-patch and it would be caught by someone, but its been a while since then and not resolved, that's on me.

### How to Reproduce

Make a troll warrior, spec as arms, check if berserking is recommended

### Snapshot (Link)

https://pastebin.com/Fjccwggh

**Comment by Hekili** [comment]
Good catch; I'll add the missing racial CDs to the priority.
