### ISSUE TITLE
Mistweaver monk - only propose Tiger Palm

### ISSUE THREAD

**Issue by Hemario** [Hekili/hekili#2381]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

If you don't take Teachings of the Monastery talent, blackout kick is never suggested.

### How to Reproduce

1. Enter the game as mistweaver monk
2. Change talents to not take Teachings of the Monestery
3. Go to a ST target dummy
4. only Tiger Palm is suggested

### Snapshot (Link)

https://pastebin.com/jMmAjkkZ

### Contact Information

Hemario#4869

**Comment by Hemario** [comment]
You would regret adding the healer APLs, you said it yourself :)

**Comment by Hekili** [comment]
If/when there are updates to Mistweaver priorities, they'll be added to the addon.  You can disable Mistweaver in the meantime.  :)
