### ISSUE TITLE
Guardian Druid - No SpellFlash on Raze

### ISSUE THREAD

**Issue by codengine** [Hekili/hekili#2382]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Although I was at 100 rage, there was no recommendation although Raze for example would be castable. This is counterintuitive in my opinion.

Moreover, in the /hekili settings I also configured that with > 20 excess rage it should recommend Maul/Raze.

The issue is similar to https://github.com/Hekili/hekili/issues/2352 but I think Raze would be the correct recommendation instead of doing nothing.

### How to Reproduce

1. Enter Game as Guardian Druid
2. Cast the recommended spells
3. At some point it stops recommending anything

### Snapshot (Link)

https://pastebin.com/KPRskCXD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cUeBBmZ8HqUopxmZyDR9uB

**Comment by Hekili** [comment]
The snapshot you provided shows Raze being recommended.  Do you have a snapshot that matches what you're describing?

**Comment by codengine** [comment]
Hm this is exactly the snapshot that I took when it happened but the spell was not highlighted at my action bar.
This is not a general problem, as it usually works. I'm using Dominos + LiteButtonAuras if that makes a difference? So, probably the spell is recommended but not highlighted? I'll try to take a screenshot

**Comment by Hekili** [comment]
Dominos shouldn't be an issue; LiteButtonAuras might be an issue but I don't know.  Try using the addon without LiteButtonAuras to see if there's some kind of conflict there.

**Comment by Hekili** [comment]
If the snapshot was taken at the correct time like you've described, you may want to get and install BugSack and BugGrabber.  If there is interference between addons, there's likely to be an error message that would help troubleshoot.

**Comment by codengine** [comment]
![WoWScrnShot_020923_220643](https://user-images.githubusercontent.com/498798/217939802-aba68141-e5e4-47a5-8653-eae7f427568e.jpg)

https://pastebin.com/as3A3AqK

Same behaviour, even with Standard UI. BugSack is empty. I enabled Spellflash and it only does not work with Raze for some reason.

It does work with Maul for example:

![WoWScrnShot_020923_221150](https://user-images.githubusercontent.com/498798/217940275-3c668a2c-92c9-494a-a8da-9b531fcdd0e2.jpg)

**Comment by Hekili** [comment]
Ok, I can resolve that.  Thanks for the additional data.

**Comment by codengine** [comment]
I can confirm, the bug is fixed in v10.05-1.0.10. Great work 👍
