### ISSUE TITLE
[WOTLK] ShadowPriest Prio not loading :(

### ISSUE THREAD

**Issue by s4br3x1980** [Hekili/hekili#2387]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I installed the Addon at Curseforge App. I can start the addon ingame and costumize it but the rotation prio don't start. The ingame addon has no "Action Pack" button or anything similar.

### How to Reproduce

1

### Player Information (Link)

build: v3.4.0-1.0.0-beta9 level: 80 (80) class: PRIEST spec: priest  talents: none  pvptalents: none  covenant: none  conduits: none  soulbinds: none  sets: none  gear: akolythenhemd = 1     band_der_arglist = 1     ergriffene_schnheit = 1     flammenherzzauberskalpell = 1     flieende_schrpe_des_befehls = 1     gamaschen_des_tdlichen_hochmuts = 1     gothiks_gugel = 1     handschuhe_der_dunklen_gesten = 1     letzter_fluch = 1     luntenanznder_des_kanoniers = 1     mainhand = 1     manschetten_des_schattenaszendenten = 1     mantelung_des_tapferen_glaubens = 1     schwarztuchrobe = 1     seuchenznder = 1     stiefel_der_leidenschaftlichen_ideale = 1     talisman_des_geielbefehls = 1     umhang_aus_keafedern = 1     umschlieende_poliergoldkette = 1     wappenrock_der_kirin_tor = 1  legendaries: none  itemIDs: 35609, 37694, 37850, 39192, 40108, 40246, 40255, 40284, 40339, 40398, 40459, 40680, 40724, 40741, 42101, 43157, 44013, 44173, 6097  settings: none  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds: 

### Error Messages (Link)

no error

**Comment by Hekili** [comment]
Please update to the latest Wrath release.  If you are still having issues, submit a new ticket.

**Comment by s4br3x1980** [comment]
Yes it works really good
