### ISSUE TITLE
I just downloaded for the first time and my game stutters.

### ISSUE THREAD

**Issue by Oswalend** [Hekili/hekili#2388]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I just downloaded this addon for the first time and I experience my game stuttering upon login and during my first few minutes of playing and fighting.  

### How to Reproduce

1. Load up game.
2. Start moving or attacking anything. 

### Player Information (Link)

https://pastebin.com/d644uisj

### Error Messages (Link)

N/A

### Contact Information

Oswalend#1896

**Comment by Hekili** [comment]
There's an open ticket to which you can add information.  Otherwise, you can only wait for me to release other performance optimizations down the line.
