### ISSUE TITLE
Hekili recommends RTB during Shadow Dance for CTO build

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#2389]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

There is a a build for outlaw involving the count the odds talent (CTO).  One of its rules is that during shadow dance (or subterfuge), roll the bones should never be used.   However, Hekili recommends roll the bones during shadow dance.  

Link from rogue discord: https://discord.com/channels/124169701881282560/856897810536071208/1047397756160983070

### How to Reproduce

1. Be outlaw and use the CTO build: https://discord.com/channels/124169701881282560/856897810536071208/1047397077770059796

loadout string: BQQAAWulQAmRd/c4Iy2r7VOUFAAAgERSAOQSSkQSCkEJRikkkkECAAAAAAQ0CkUSCIRKBAAAA

2. Cast shadow dance with roll the bones not up or about to fall off

3. Hekili recommends roll the bones during shadow dance

### Snapshot (Link)

https://pastebin.com/HZd46GTf

**Comment by Hekili** [comment]
I'm not sure why they've not added this to the sim profile.  Can you provide a raidbots sim of your character for comparison?

**Comment by wheatbread** [comment]
Hi, sorry for the late reply!

If you still need it:

Dungeon Slice: https://www.raidbots.com/simbot/report/deRMVxmdykE2aZzyF4JhY2
Patchwerk: https://www.raidbots.com/simbot/report/6fPffZkzUFJGzKr17z97S1

**Comment by Hekili** [comment]
Are you seeing this happen with the latest version of the addon?

**Comment by Zecho997** [comment]
Tested the new version of the app yesterday while raiding but it still showed me to RTB before AD. Am I doing something wrong?

**Comment by Hekili** [comment]
I don't know, as you didn't provide a snapshot.  But if I had to guess, you probably didn't enable the setting.

**Comment by Zecho997** [comment]
Will test it today. After im back with the results :)

**Comment by Hekili** [comment]
Reviewing your original sim, I found a Roll the Bones entry that fired during Shadow Dance:

01:29.4 | cds | M | roll_the_bones | Silk | 47.2/150: 31% energy | slice_and_dice,   blade_flurry, take_em_by_surprise_aura, shadow_dance, alacrity(5),   elemental_lariat__empowered_flame, sophic_devotion
-- | -- | -- | -- | -- | -- | --

I modified the sim to never use Roll the Bones during Subterfuge or Shadow Dance and ran a 3 target sim.  The results are functionally identical:

![image](https://user-images.githubusercontent.com/9438134/219513904-cc368ff0-0d01-40a4-8ba0-27d7bd203ffa.png)

![image](https://user-images.githubusercontent.com/9438134/219513929-46eb4c83-02d8-4c38-99d5-ec63ca3af199.png)

https://www.raidbots.com/simbot/report/7mwGQvQKe6MtpXreyuVPR6/simc
