### ISSUE TITLE
Hope to add range detection to the frost talent 'Arcane Explosion'

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#2390]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Spell: Arcane Explosion Hope to add range detection to the Frost. Just be the same as the Arcane

**Comment by Hekili** [comment]
This doesn't seem unreasonable, though IIRC sometimes you're just looking to cast an Arcane spell for Disciplinary Command.  That might be out of date, though.

**Comment by Hekili** [comment]
I'm adding the option to all Mage specs in the next release.
