### ISSUE TITLE
Constantly Looped  Hunter Ability "Serpent Sting"

### ISSUE THREAD

**Issue by ghLuTS** [Hekili/hekili#2392]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After the 11.02.23 update, any display shows a looped Serpent Sting after two abilities

### How to Reproduce

Unfortunately, I can't tell you what to do to make this happen again, other than try it on another hunter.

### Snapshot (Link)

https://pastebin.com/PuyJ3Bu3

### Contact Information

GH luTS#1826

**Comment by Hekili** [comment]
This will be fixed later today.

**Comment by ghLuTS** [comment]
Thanks a lot!

> This will be fixed later today.

Thanks a lot!
