### ISSUE TITLE
Holy Paladin APL Won't Load - Add-on Warning for State/Core LUA files for 'k'

### ISSUE THREAD

**Issue by yurikenus** [Hekili/hekili#2395]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The add-on is not showing recommendations for Holy Paladin.  Or, it may sometimes display when switching back from Retribution.

- There are no BugGrabber/BugSack errors, but there are Hekili warnings (shared below).
- The add-on does load recommendations for Retribution.
- The add-on behaves this way with the new stock Holy APL, as well as a custom one.
- I have tried both the latest from Github as well as the latest from Curseforge, and this occurs with both.

### How to Reproduce

1. Log in as Holy Paladin.
2. Notice no recommendations are made.
3. Switch to Retribution spec, notice Recommendations are there.
4. Switch back to Holy.
5. Notice recommendations are broken or still show Retribution recommendations.
6. Reload, no improvement.

### Player Information (Link)

https://pastebin.com/HnyxTC0t

### Error Messages (Link)

https://pastebin.com/PXHKbiFL

**Comment by Hekili** [comment]
This will be fixed in a bit.
