### ISSUE TITLE
Does not correctly count the goals on the mythic rashaget

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2397]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When we are near the Surging Ruiner, the addon shows that there are 4-5 targets next to it. When it is still there 1. Please fix the display of this goal count.

### How to Reproduce

Come to the rashaget.
Transfer to another platform.
Place yourself near the Surging Ruiner 
And the addon will show not 1 goal that it sees.

### Snapshot (Link)

nothing

**Comment by Hekili** [comment]
You'll have to provide a snapshot.

**Comment by Dragonfo** [comment]
https://pastebin.com/7sVRvXT9 Here I attached a snapshot. In phase 1.5, rashaget always shows me 4 goals, regardless of how many goals. I can stand next to the Surging Ruiner and still 4 goals will show.

**Comment by Dragonfo** [comment]
Here's a screenshot I even attached, I was dead and Adon still counts 3 goals.

**Comment by Hekili** [comment]
Yeah, the API is giving bad range information for those guys:

```
targets:
    nameplate10  -  0 - Creature-0-4240-2522-4155-193760-0002EA7AF4 - 43.00 - 6 - Заряженный губитель 
    boss2        -  0 - Creature-0-4240-2522-4155-193760-00016A7AF4 - 300.00 - 0 - Заряженный губитель 
    boss3        -  0 - Creature-0-4240-2522-4155-193760-0000EA7AF4 - 30.00 - 7 - Заряженный губитель 
    boss4        -  0 - Creature-0-4240-2522-4155-193760-00006A7AF4 - 300.00 - 0 - Заряженный губитель 
```

The quickest solution is to make them not count as targets if they're not your current target.  According to the game, all of those enemies are 0 yards from you and the addon is forced to trust it.  Try out v10.0.5-1.0.13-alpha1 and let me know if that resolves this for you.

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/releases/download/v10.0.5-1.0.13-alpha1/Hekili-v10.0.5-1.0.13-alpha1.zip

**Comment by Dragonfo** [comment]
Everything works fine. Thanks. I just tested it.
