### ISSUE TITLE
Enhancement Shaman - Chain lightning recommended on single target

### ISSUE THREAD

**Issue by eriksen080499** [Hekili/hekili#2398]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I dont understand why Hekili suddently are beginning to use chain lightning on single target.

I am using all my procs and following rotation provided, but suddently it has begun to recommend chain lightning on single target, even when lava burst and lightning bolt is ready to be cast?
Could you enlighten me?

### How to Reproduce

1. Start attacking 1 dummy
2. follow rotation provided
3. Chain lightning?

My sim doesnt include chain lightning at all on ST, so must be something with enemy detection.

### Snapshot (Link)

https://pastebin.com/w0EjbVU1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ce45ML7jhGpQumeqGWCcB4

**Comment by chevyn11** [comment]
You are in aoe mode. Set it to single target mode or auto.

**Comment by eriksen080499** [comment]
> You are in aoe mode. Set it to single target mode or auto.

lol. Thanks man, didnt notice...

**Comment by LionHokies** [comment]
I have this issue and i'm in auto mode.  I suspect there might be a bug.
