### ISSUE TITLE
[UH DK] Dark Transformation used before Commander of the Dead

### ISSUE THREAD

**Issue by jherad217** [Hekili/hekili#2399]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I found an Issue with the Unholy Death Knight Rotation when you are specced into "Commander of the Dead". "Dark Transformation" should be used after "Apocalypse", "Summon Gargoyle" and "Army of the Dead" to buff the respective Pets.

Additionally Minor Changes:
- "Sudden Doom" Procs should maybe have a higher Priority in the Rotation. 
- "Empower Rune Weapon" should be timed with "Summon Gargoyle" and in the "Summon Gargoyle" Window "Death Coil" should have a higher Priority
- "Summon Gargoyle" and "Army of the Dead" should be recommended to use if "Dark Transformation" is ready to go.

### How to Reproduce

Just play the Rotation with the actual Profile (13.02.2023)

### Snapshot (Link)

https://pastebin.com/mQkQG5F7

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vfML85QxSXDgqiYX7Qy772

### Additional Information

It seams that Raidbots also has that issue that it casts "Dark Transformation" before summoning the other Pets when specced into "Commander of the Dead"

**Comment by Hekili** [comment]
Unless something has changed that I don't know about, you have 4 seconds after Dark Transformation to summon pets and have them benefit from Commander of the Dead.  Is that no longer accurate?
