### ISSUE TITLE
Warrior Arms Hurrican buff overlap with Bladestorm and Avatar

### ISSUE THREAD

**Issue by Gromzie** [Hekili/hekili#2400]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Is it only me or isn't the arms rotation optimal? It want me to use  Bladstorm 
right after avatar when the hurricane buff is up for several seconds. There you should probably get some attacks in before you use Bladstorm to renew the Hurricane buff.Hurrican gives you +30% Strength and Merciless Bonegrinder gives +50% dmg on Cleave and Whirlwind. You dont want to overlap that buffs.

### How to Reproduce

1. Enter game as Arms.
2. Go to AOE dummies in Valdrakken.
3. Follow opening rotation for Avatar and Bladstorm.
4. The Hurrican buff will be overlapped.

### Snapshot (Link)

https://hastebin.com/share/uqugasotem.scss

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fVNUD8TJwgsVVjryttrcuV

### Contact Information

Baba#8725

**Comment by Hekili** [comment]
Your snapshot is incomplete.  You need to press CTRL+A and then CTRL+C so you copy all lines of information.

It looks like the sim profile also carries out this behavior:

<html><body>


Time | List | # | Name | Target | Resources | Buffs
-- | -- | -- | -- | -- | -- | --
0:01.211 | hac | F | avatar | Fluffy_Pillow | 10.5/130: 8% rage | wild_strikes, gladiators_emblem
0:01.211 | Waiting |   |   | 4.006 sec | 40.5/130: 31% rage | avatar, wild_strikes, bladestorm, hurricane, gladiators_emblem
0:05.217 | hac | G | warbreaker | Fluffy_Pillow | 98.7/130: 76% rage | avatar, wild_strikes, merciless_bonegrinder, hurricane(5), sophic_devotion, gladiators_emblem
0:06.427 | default | 9 | berserking | Fluffy_Pillow | 98.7/130: 76% rage | avatar, wild_strikes, merciless_bonegrinder, hurricane(6), in_for_the_kill, sophic_devotion, gladiators_emblem
0:06.427 | hac | H | thunderous_roar | Fluffy_Pillow | 98.7/130: 76% rage | berserking, avatar, wild_strikes, merciless_bonegrinder, hurricane(6), in_for_the_kill, sophic_devotion, gladiators_emblem
0:07.431 | hac | I | bladestorm | Fluffy_Pillow | 130.0/130: 100% rage | berserking, avatar, wild_strikes, merciless_bonegrinder, hurricane(6), in_for_the_kill, sophic_devotion, gladiators_emblem


</body>
</html>

Could you also re-run your sim?  If I sim using your profile, I get a significantly different DPS result.  I'll test keeping Bladestorm from being used during Merciless Bonegrinder, but I can't see why I'm getting 20% more DPS when I sim you than you did.

**Comment by Gromzie** [comment]
edit: https://pastebin.com/Y6XSgbgS

And you want to use warbreaker direcly after the first bladstorm/avatar to get bonus damage and then get whirlwind and cleave in before pressing Bladestorm to refresh Hurricane. Hurricane is 6 sec and Merciless bonegrind is 9 so you want to press bladstorm just before Hurricane expire to reapply it. To keep the +30% Strength buff for as long as possible. 

I simmed without buffs that might be why.

**Comment by Gromzie** [comment]
I checked the sims and the rotation that is showed in Hekili seems to be the same as the sim. But it's impossible that it's worth to overlap a +30% Strength buff + half the bonegrind buff. When I look at the top players they play like what I explained here above. Seems like the sim are wrong. Maybe need to wait for them to update the sim then.

**Comment by Hekili** [comment]
> Seems like the sim are wrong. Maybe need to wait for them to update the sim then.

You can submit a ticket to SimulationCraft re: the priority, if they don't have an open ticket about it.  It's still a matter of proving that the way folks are playing is outperforming the way the sim is doing things.  I'm not saying it isn't possible, I'm just saying proof is needed.

**Comment by Hekili** [comment]
More testing:

[This sim](https://www.raidbots.com/simbot/report/57HcWAHyND8G7a6VKBkyUu) tries to daisy chain Hurricane, only using Bladestorm if there is less than 1 GCD left on Hurricane.

![image](https://user-images.githubusercontent.com/9438134/218752953-39c8391f-0b0f-47f4-bc96-5041b2ded828.png)

It's DPS neutral.

| Default Sim | Hurricane
|-|-
| ![image](https://user-images.githubusercontent.com/9438134/218753638-ba4fab21-b391-4915-bce0-58a57f6a3e6e.png) | ![image](https://user-images.githubusercontent.com/9438134/218753784-269a2ce5-8a24-4d97-835c-e180af0302ea.png)

It fills the time between after Thunderous Roar with Cleave, Whirlwind, and Overpower:

Time | List | # | Name
-- | -- | -- | -- 
0:01.211 | hac | F | avatar
0:05.251 | hac | G | warbreaker
0:06.461 | default | 9 | berserking
0:06.461 | hac | H | thunderous_roar
0:07.464 | hac | J | cleave
0:08.465 | hac | K | whirlwind
0:09.467 | hac | J | cleave
0:10.467 | hac | O | overpower
0:11.468 | hac | J | cleave
0:12.470 | hac | I | bladestorm

*Maybe* it creates a slightly higher burst spike in the opener?  

[This sim](https://www.raidbots.com/simbot/report/jpriyjEGNUDUSHTbUbT3ma) waits until Merciless Bonegrinder is expiring before using Bladestorm.

![image](https://user-images.githubusercontent.com/9438134/218753360-3180e6a5-de3a-4747-bf3f-08e2a3bf310d.png)

It's an 0.2% DPS loss.

It's possible there are other tweaks that would eke out damage, but I've not found them yet.  This may be one of those things that sounds good overall, and isn't necessarily bad, but it just doesn't pay off as much on average.

**Comment by Hekili** [comment]
> When I look at the top players they play like what I explained here above. Seems like the sim are wrong. Maybe need to wait for them to update the sim then.

You can report the issue in simc if you'd like (potentially even linking the test sims that I ran).

https://github.com/simulationcraft/simc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
