### ISSUE TITLE
Ret Paladin - Double on use trinkets only one will ever get recommended.

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2401]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With the priority trying to use trinkets during Crusade or with 10 stacks of crusade it only ever seems to recommend one trinket. It will prompt the second trinket for the brief window where the 1st trinket is still on cool down but will instantly turn to the second once it is back off cool down. Then will not prompt a trinket until the next crusade window. 

### How to Reproduce

    Enter game as Ret Paladin.
    Go to AOE dummies in Valdrakken.
    Follow AOE rotation during crusade and get trinket recommendation.
    Never get second trinket recommendation.

### Snapshot (Link)

https://pastebin.com/16VQ2Uuj

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/oCUN1QXS59YkSmUqsExVsh/simc

**Comment by Hekili** [comment]
In your case, it seems to be that the Crusade talent has you wait until 10 stacks of Crusade to use your first trinket, which puts the other on CD, and if you take more than 5 seconds to get to 10 stacks, Crusade has fallen off by that point.

There is a secondary aspect that, as far as the addon is concerned, Windscar Whetstone counts as a "buff" when in the sim, it's just a damage proc.  I'm doing some work on this so that the trinket can get used whenever based on just being a damage effect.

**Comment by Hekili** [comment]
Please try out the latest release (10.0.5-1.0.13) and let me know if this is resolved for you or not.  If not, please provide two snapshots:
* One taken as you reach 10 stacks of Crusade and your first trinket is recommended.
* One taken in the last couple seconds of Crusade if/when your second trinket is not recommended.

Thanks!

**Comment by Bingo176** [comment]
This seems to have resolved the problem! I will update if I notice anything odd after I run some keys with it. Appreciate everything.

Thanks

**Comment by Bingo176** [comment]
I figure this is along the same idea. This only happens in pre combat so I'm unsure how to get a snapshot of that, so i took a SS of the pause. It also disappears and reappears after I take a few steps. It has me puzzled. 

![image](https://user-images.githubusercontent.com/25187247/219904677-77879009-4ecc-4604-9cea-1705d519e6f2.png)

**Comment by Hekili** [comment]
> It also disappears and reappears after I take a few steps. It has me puzzled.

Sorry, what exactly does this mean?

**Comment by Bingo176** [comment]
https://pastebin.com/bMiMRGkb of the cooldown when I hit pause.

After a little bit of testing it only seems to happen in the Valdrakken area. 

This is the recommendation outside of combat which seems contrary to how that trinket should show up.  (Center Valdrakken area with the water fountain)
![image](https://user-images.githubusercontent.com/25187247/220156871-2ccd16e3-57ea-4e4c-9f41-4d4e32268b41.png)

How almost all the other areas in the game show pre combat. 
![image](https://user-images.githubusercontent.com/25187247/220157258-2fa5a315-09d8-4e9c-999e-0cfa5f8a301b.png)

It really doesn't bother me but just was a weird interaction running around seeing your trinket appear and disappear.

**Comment by Hekili** [comment]
It is likely based on the initial fight duration calculation.  With a target, the number can change based on type of enemy.  With no target, there's a made up number.

**Comment by Hekili** [comment]
I've made another adjustment to trinket entries related to this ticket.
