### ISSUE TITLE
BM rotation problems(dont show Bestial Wrath and opener is bad)

### ISSUE THREAD

**Issue by vladavlada92** [Hekili/hekili#2403]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Heki don show Bestial Wrath  AND have bad opener

### How to Reproduce

just start to dps

### Snapshot (Link)

Beast Mastery; Primary - Kill Command(0.00)

### Additional Information

no

### Contact Information

vladaakitan@gmail.com

**Comment by Hekili** [comment]
Please don't bother submitting tickets if you're not going to give specifics.  The questions are intended to help investigate your issue.

You also did not copy the complete snapshot, but if you had, my best guess is that you have your Cooldowns toggle disabled.  Bestial Wrath is on the Cooldowns toggle by default, so you won't see it until/unless you turn that on.  See /hekili > Toggles to switch it or to set up your keybinding to toggle it on/off.

**Comment by vladavlada92** [comment]
I am so sry,didnt know better,i will try next time.
