### ISSUE TITLE
[REC] BREWMASTER MONK / TIGER PALM-SPINNING CRANE KICK TIER SET BUFF

### ISSUE THREAD

**Issue by LucasNavim** [Hekili/hekili#2404]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For brewmasters monks tiger palm and spinning crane kick are not showing to keep up the tier set buff

### How to Reproduce

1. Enter the game As a brewmaster monk
2. have 2 or 4 tiers set
3. engage any enemy

### Snapshot (Link)

https://pastebin.com/XDkMxsNb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rmsCMFLg83DStvXzHWroSK

### Contact Information

Navim#7628

**Comment by Hekili** [comment]
Your snapshot is not complete. Make sure to take the snapshot when you think it should be recommending Tiger Palm/SCK but isn't. It looks like you took a snapshot just logged in and neither of those are probably the very first ability you're expecting to see. (Maybe not.)

But the snapshot is required. Make sure to CTRL+A then CTRL+C to get all the additional info.

**Comment by Hekili** [comment]
https://www.wowhead.com/guide/classes/monk/brewmaster/tier-set-bonuses

![image](https://user-images.githubusercontent.com/9438134/219512740-5a3984df-833d-4de0-a927-67790d945cb4.png)
