### ISSUE TITLE
[BUG] Incomplete SW Priest APL

### ISSUE THREAD

**Issue by AdenJustice** [Hekili/hekili#2405]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

https://github.com/Hekili/hekili/blob/781fea44fa3278aaaad1958c523548b2a799095e/Dragonflight/APLs/PriestShadow.simc#L117

The line is incomplete. I found it while comparing the default APL with what I generated using SimulationCraft.
I'm not sure it's just a mistake on APL only or it actually causes a problem on Hekili.

### How to Reproduce

No process required

### Player Information (Link)

not relevant

### Error Messages (Link)

not relevant

**Comment by Hekili** [comment]
Thanks!

**Comment by Hekili** [comment]
This will be fixed in next release.
