### ISSUE TITLE
[REC] Feral Druid - tells user to use finishers on 4 combo points instead of 5 with Blood Talons

### ISSUE THREAD

**Issue by colsonj** [Hekili/hekili#2406]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For the Feral Druid, I expect that a finisher should only ever be used with 5 combo points (potentially situationally but not for optimal DPS). Consistently the addon is telling me to use finishers on 4 combo points. As far as I am aware, this started occurring in the most recent build

![image](https://user-images.githubusercontent.com/111336522/219382557-12266dda-67aa-4856-87b0-f6b224b03361.png)
![image](https://user-images.githubusercontent.com/111336522/219382625-257495ad-afff-4023-88e8-f9cff8628ce8.png)
![image](https://user-images.githubusercontent.com/111336522/219382900-45fed152-39d3-4054-86a5-f32f465ae9aa.png)

### How to Reproduce

1. Enter game as feral druid
2. Use any combination of talent builds
3. Attack the AoE/single target test dummies or real enemies

### Snapshot (Link)

https://pastebin.com/FCGN7KAh

### Contact Information

yohan1121#7599

**Comment by vond82** [comment]
Intended and was in the changelog:

"Note:  New priority will use finishers at 4+ CP when Lion's Strength is talented.  It's not a bug."

Its from latest set of APL changes

**Comment by colsonj** [comment]
It still happens when using Blood Talons

![image](https://user-images.githubusercontent.com/111336522/219389900-be160dde-5f61-4666-84db-25dc804653a0.png)
![image](https://user-images.githubusercontent.com/111336522/219389956-9de97368-6246-4439-82ed-3b9d4d88a2a9.png)

**Comment by shredxt** [comment]
![image](https://user-images.githubusercontent.com/47064656/219391347-a6f8b948-338c-4fad-9d58-abda0ce03e76.png)

Your combo points are > 3, therefore Primal Wrath is recommended.

Full APL: https://raw.githubusercontent.com/simulationcraft/simc/dragonflight/engine/class_modules/apl/feral_apl.inc

**Comment by Hekili** [comment]
Yeah, these are deliberate updates to the sim priority and are not bugs.
