### ISSUE TITLE
[REC] Brewmaster Keg smash charges issue 

### ISSUE THREAD

**Issue by W8ink** [Hekili/hekili#2407]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addons\Hekili\Dragonflight\MonkBrewmaster.lua
Replace:

keg_smash = {
        id = 121253,
        cast = 0,
        cooldown = 8,
        charges = function () return legendary.stormstouts_last_keg.enabled and 2 or nil end,
        recharge = function () return legendary.stormstouts_last_keg.enabled and 8 or nil end,
        gcd = "totem",
        school = "physical",

with something like:

keg_smash = {
        id = 121253,
        cast = 0,
        cooldown = function () return 8 * haste end,
        charges = function () return talent.stormstouts_last_keg.enabled and 2 or nil end,
        recharge = function () return 8 * haste end,
        gcd = "totem",
        school = "physical",

### How to Reproduce

dont know what to write

### Snapshot (Link)

1

### Contact Information

W8ink#7189

**Comment by Hekili** [comment]
You'll have to actually explain your reasoning.

edit:  I'm interpreting this as "Stormstout's Last Keg" talent doesn't appear implemented and needs to result in a second charge.

**Comment by Hekili** [comment]
Will be fixed in next release.

**Comment by W8ink** [comment]
sry for absent discription of issue and ty for response!
