### ISSUE TITLE
[REC] Resto Shaman - Does not take into account Acid Rain talent or multi-doting Flame Shock

### ISSUE THREAD

**Issue by Michael-Ziluck** [Hekili/hekili#2408]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Lava Surge talent affects the rotation for Elemental Shaman, but it is not incorporated to the Resto Shaman rotation for multi-doting Flame Shock.
Healing Rain (when Acid Rain talent is taken) is also not included.
Stormkeeper is not included as a damage CD.

### How to Reproduce

Take the talents mentioned above. They are not included.

### Snapshot (Link)

N/A

### Contact Information

DoctorZee#4445

**Comment by Hekili** [comment]
Sorry, required information is missing from this ticket.

**Comment by Michael-Ziluck** [comment]
@Hekili Raidbots does not support resto shaman so I can not provide that. Additionally what help is a Snapshot for things that are completely missing? I can include it if you'd like but all it would be is the exact default Snapshot...

**Comment by SpatenLa** [comment]
there is no default snapshot.
The snapshot includes current information, the APL and why it does step over something or so something. there is no "default" there.
