### ISSUE TITLE
[REC] DH Glaive Tempest movement

### ISSUE THREAD

**Issue by linygany1** [Hekili/hekili#2409]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Glaive Tempest build uses Initiative talent but no Momentum, but i dont understand how to let hekili put vengeful retreat in rotation, BUT NO fel rush, if Recomended movement enabled, u get both, if anything else checked or unchecked, u got no Vengeful Retreat for Initiative buff  

### How to Reproduce

1. Havoc Glaive Tempest DH
2. Take Initiave talent, dont take Momentum
3. Hekili doesnt recommend ONLY Vengeful Retreat in any possible "recommended movement", check or uchecked

### Snapshot (Link)

https://pastebin.com/TMyf5BCt

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nTw43XnvGQtEaWoGirHaNV

**Comment by Zeuslight56** [comment]
Hekili advises because there is also the isolated prey talent which generates fury with the dashes too.

**Comment by Hekili** [comment]
These settings have been changed since this ticket was opened.  Let me know if you have any current questions.  Thanks!
