### ISSUE TITLE
Balance Druid does not recommend Cancel Starlord Aura if checked

### ISSUE THREAD

**Issue by MPJulian86** [Hekili/hekili#2410]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Balance druid dont recommend to cancel Starlord Aura if its checked in the menu.

### How to Reproduce

Enter Game as Balance Druid
Make sure Cancel Starlord is checked in the Settings.
Play.
It will never show that you have to cancel Starlord.

### Snapshot (Link)

https://pastebin.com/DAviBB4D

**Comment by Hekili** [comment]
That is correct; the latest sim profiles do not cancel Starlord.  I will retire that setting to avoid confusion.
