### ISSUE TITLE
Warlock ALL SPECS Hekilli dont show any trinket what i use

### ISSUE THREAD

**Issue by SebastianPlominski** [Hekili/hekili#2411]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I remember in the past that the addon used to show me normally when to use a trinket, now I don't have that, I have already set everything in the settings.

### How to Reproduce

To show a trinket 

### Snapshot (Link)

N/A

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/975
