### ISSUE TITLE
[FEATURE] Sub Rogue Funnel Damage Toggle for Boss encounter Only

### ISSUE THREAD

**Issue by Rikkyspanish** [Hekili/hekili#2412]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Sorry if this is not where you prefer to me messaged but was just going to suggest as a change that would be amazing, is that if there was an option in Core Sub to toggle "Use Priority Rotation (Funnel Damage)" only during a boss encounter. 

 

This would be great for large pulls onto boss in M+. 

### Contact Information

Rikyspanish#5815

**Comment by Hekili** [comment]
I've been thinking about this, but I'm not sure I want to go this route.  You can already toggle with `/hekili set` or using the minimap dropdown menu, and having this choice automated would run the risk that folks would not realize why the priority suddenly looks/feels different without having changed any settings.
