### ISSUE TITLE
Protection Warrior - buff.avatar.up always false

### ISSUE THREAD

**Issue by Ed51** [Hekili/hekili#2413]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In my testing buff.avatar.up always seems to show as false after activating Avatar.

In the default action pack it should recommend Thunder Clap in AOE after using Avatar.

### How to Reproduce

First Way:
1. Enter game as Prot Warrior 
2. Open Hekili add action to the top of list Thunder Clap with condition buff.avatar.up
3. Activate Avatar and this action won't be recommended

Second Way (default list)
1. Enter game as Prot Warrior
2. AOE > 3 targets
3. Activate Avatar
4. Thunder Clap won't be priority recommendation

### Snapshot (Link)

https://pastebin.com/t7pJVFqJ

**Comment by Hekili** [comment]
Thanks; I'll update the Avatar spell ID.

If you review the snapshot on your own, you'll find there are a lot of errors in your custom priority (i.e., `shield_wall.up` alone does not work -- you likely want `buff.shield_wall.up`; and you have some conditions that are missing spaces around `|` operators and so forth, so they don't actually work).

**Comment by Ed51** [comment]
That's great, thanks.

Oh, those bugs were from another test I was doing :).

**Comment by Hekili** [comment]
This is resolved.
