### ISSUE TITLE
Frost DK: no initial recommendations w/ Obliteration talented

### ISSUE THREAD

**Issue by ozzie1250** [Hekili/hekili#2414]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

If i don't have breath pick, single target priority only shows me raise dead. I tested it while having and not having breath selected. It was working prior to level 60, I leveled with it and it work fine.

### How to Reproduce

![Wow_gD8dtlXOiK](https://user-images.githubusercontent.com/125758371/219879717-0225ce3a-d405-44aa-9974-a758e338bc81.png)
move it down but that's what it shows me if breath is not selected. everything is default 

### Snapshot (Link)

https://pastebin.com/Evh8xE5y

**Comment by Hekili** [comment]
I'm investigating this, but you did not provide a complete snapshot (it will have many lines, not just 1).

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by ozzie1250** [comment]
https://pastebin.com/3LQ2gZ1e, this is a new one sorry for the privies one. I keep fiddling with it and sometime i get some extra spells to show but its not continues like with unholy. Once i click the recommended spell the list goes blank and i have to wait for one to show up. I tried in aoe and it seem to work better but it still was not recommending me to use CD like Pillar of Frost or Empowered Rune Weapon, i have looked and they are not disabled but in this example i had Empowered Rune Weapon not selected.

**Comment by mrblister** [comment]
Still seeing the same issue with the new update.

**Comment by Hekili** [comment]
@ozzie1250:
> I keep fiddling with it and sometime i get some extra spells

What are you fiddling with?  Supply snapshots of when you're having the issue, not when you're seeing recommendations.

@mrblister:
> Still seeing the same issue with the new update.

Post updated snapshots for investigation.  Remember to put them on Pastebin and link them, as they are far too long to include in a GitHub post (and they won't be readable here).

**Comment by ozzie1250** [comment]
I keep trying to see if different action give better result, like i said sometime i get a full bar of runic power and frost strike show but nothing else once I expend my runic power. I cant snap shot it other wise. I will provide you with four samples one with obliterate + no breath, one with breath only which is when everything is recommended and properly working and one before i even start combat. 
In combat -Obliterate only - https://pastebin.com/JgucKt6V
In combat -Breath ( working perfectly recommends everything ) - https://pastebin.com/dcGxnKW7
Out of - Obliterate only - https://pastebin.com/W5ike10J
Out of - Breath only - https://pastebin.com/sVyMuNZK

**Comment by Hekili** [comment]
edit: ~~@ozzie1250 Your updated snapshots don't have my priority changes included.  Are you importing a priority yourself, or did I fail to actually include the priority update?~~

Never mind, I see that the rune check *is* included.

**Comment by mrblister** [comment]
https://pastebin.com/3Xf53ykR

**Comment by Hekili** [comment]
I've reported this issue to SimulationCraft because it is at least partially related to misuse of `gcd` in the APL variables:  https://github.com/simulationcraft/simc/issues/7363

**Comment by ozzie1250** [comment]
That's awesome let me know if you need anything else from me. Good job with the add-on.

**Comment by Hekili** [comment]
> [pastebin.com/3Xf53ykR](https://pastebin.com/3Xf53ykR)

Your issue seems to be related to talenting for Obliteration but not having Empower Rune Weapon.  I'm adjusting the priority for that scenario.

**Comment by ozzie1250** [comment]
Was not going to be an issue at max then level but I'm glad to help you work out the little things

**Comment by Hekili** [comment]
My additional changes are here:  https://github.com/Hekili/hekili/releases/download/v10.0.5-1.0.16/Hekili-v10.0.5-1.0.16.zip

Let me know if you continue to have issues.

**Comment by Hekili** [comment]
I've made additional changes in 1.0.17 and SimulationCraft has also been updated.
