### ISSUE TITLE
[Icon Glow / Cool Glow] Is it possible to get an icon Glow like in this dead addon: Cool Glow

### ISSUE THREAD

**Issue by xapollyon** [Hekili/hekili#2417]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Is it possible got Hekili to have an Action button icon glow like Cool Glow (which is used in MaxDPS Addon) - unfortunately Cool Glow hasnt been updated.

But if this can be brought into Hekili this would be great.

Cool Glow - https://www.curseforge.com/wow/addons/cool-glow

MaxDps - https://www.curseforge.com/wow/addons/maxdps-rotation-helper

Thanks in advance.

**Comment by Hekili** [comment]
Hmmm.  Maybe.

**Comment by xapollyon** [comment]
Thanks for the reply, to push the idea further, what I can say is that one of the benefits would be a cleaner action bar. The thick Outline circles which I see many people using can become overpowering when everything starts flashing.  The 'cool glow' will just be around the buttons making it less like a fireworks and also be beneficial for clicker players.  Anyway I have said my peace.

Thanks for making a great addon

**Comment by Hekili** [comment]
The issue is that I *try* to leave all of the SpellFlash preferences to sit with SpellFlash itself, which I don't maintain.  The addon does a small amount of funny stuff (i.e., changing flash textures, forcing a flash to end prematurely on change), but replacing SpellFlash's glow mechanism is not something I'm sure I want to be doing.
