### ISSUE TITLE
[REC] Balance - Celestial Alignment CD not tracked with Orbital Strike

### ISSUE THREAD

**Issue by Yarvillian** [Hekili/hekili#2418]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Balance Druid, I expect for Celestial Alignment to be cast on Cooldown, however, the addon is requesting that I cast it when it still has 60-70 seconds remaining. The only reason this could be appearing is due to the fact that I am level 65.

### How to Reproduce

1. Enter the Game as Balance Druid. 
2. Start rotation as normal and follow the recommended buttons to press.
3. Within 20-30 seconds of Celestial Alignment being off cooldown, the spell will come up recommended again
![CA on CD](https://user-images.githubusercontent.com/66763620/220166672-fa1f717b-f77a-4eb3-bebf-8709fcffa4b3.JPG)

### Snapshot (Link)

https://pastebin.com/ButgejwQ

### Additional Information

I understand that the addon is not built for people at level 65 and this problem may solve itself as I reach level 70. This is a very small edge case, but I want to do my part to help out where I can! I am using a leveling build that does include the CD reduction of Celestial Alignment by 60 seconds but it is still asking for me to cast it 1:30 too early 

### Contact Information

Yarv#1980

**Comment by Hekili** [comment]
Are you able to tell what the spell ID for Celestial Alignment is on your character?

**Comment by Yarvillian** [comment]
I don't run an addon that tells me that! I'm sorry :(

**Comment by Hekili** [comment]
No problem, I believe I've sorted it.  Orbital Strike changes the spell ID and was not accounted for.  Will be fixed in next release.

**Comment by Yarvillian** [comment]
Hell yeah! Glad I was able to help! :D
