### ISSUE TITLE
Holy Paladin not recommending Hammer of Wrath

### ISSUE THREAD

**Issue by cryxii** [Hekili/hekili#2419]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Holy Paladin profile has Hammer of Wrath in default action list but it is never recommended by the addon

"The action (hammer_of_wrath) is unusable at (0.00 + 0.00) because IsUsable returned false." but avenging_wrath is in player_buffs according to snapshot

### How to Reproduce

1. Activate Avenging Wrath as Holy Paladin
2. Use Consecration so the addon will recommend Hammer of Wrath
3. Check recommendation, it will show Judgment instead of Hammer of Wrath, or Holy Shock if you used Judgment

### Snapshot (Link)

https://pastebin.com/8R1nr6XX

### Additional Information

Hammer of Wrath recommendation works for Retribution and Protection but not Holy

**Comment by Hekili** [comment]
This is resolved in 1.0.16.
