### ISSUE TITLE
Outlaw Pistol Shot/ Sinister Strike Problem

### ISSUE THREAD

**Issue by Raqz69** [Hekili/hekili#242]
and here is the second issue, it occurs only in ae situations, hekili tells me to use sinister strike to build combo points even if i got a pistol shot procc up.

build: v8.2.5-04.04
level: 120 (120)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    cheat_death
    dancing_steel
    prey_on_the_weak
    quick_draw
    vigor

azerite: ace_up_your_sleeve=3
    azerite_empowered=3
    brigands_blitz=1
    deadshot=1
    heed_my_call=1
    impassive_visage=1
    keep_your_wits_about_you=1
    lying_in_wait=2
    overwhelming_power=2

essences: [essence_of_the_focusing_iris]=3, memory_of_lucid_dreams=3, vision_of_perfection=2

sets/legendaries/artifacts: none

gear:     band_des_uralten_baggerschiffs=1
    gezeitenblutarmschienen=1
    glnzend_goldenes_gefieder=1
    grtung_des_azeritarsenals=1
    handschuhe_der_unvergleichlichen_schnheit=1
    herz_von_azeroth=1
    logikleitring_der_synergie=1
    pantalons_des_seelufers=1
    phiole_des_arkanen_sturms=1
    raals_latz=1
    reif_des_einhllenden_leviathans=1
    rotes_leinenhemd=1
    schlagstock_des_enterpiraten=1
    schleichsohlen_des_belagerers=1
    schulterpolster_der_schumenden_wut=1
    schwarzwasserschimmerschuppenweste=1
    sivaras_schlngelklinge=1

itemIDs: 158075, 159294, 159310, 159320, 159322, 159333, 159461, 159617, 159973, 168343, 168348, 168377, 168818, 168887, 169156, 169313, 2575
build: v8.2.5-04.04
level: 120 (120)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    cheat_death
    dancing_steel
    prey_on_the_weak
    quick_draw
    vigor

azerite: ace_up_your_sleeve=3
    azerite_empowered=3
    brigands_blitz=1
    deadshot=1
    heed_my_call=1
    impassive_visage=1
    keep_your_wits_about_you=1
    lying_in_wait=2
    overwhelming_power=2

essences: [essence_of_the_focusing_iris]=3, memory_of_lucid_dreams=3, vision_of_perfection=2

sets/legendaries/artifacts: none

gear:     band_des_uralten_baggerschiffs=1
    gezeitenblutarmschienen=1
    glnzend_goldenes_gefieder=1
    grtung_des_azeritarsenals=1
    handschuhe_der_unvergleichlichen_schnheit=1
    herz_von_azeroth=1
    logikleitring_der_synergie=1
    pantalons_des_seelufers=1
    phiole_des_arkanen_sturms=1
    raals_latz=1
    reif_des_einhllenden_leviathans=1
    rotes_leinenhemd=1
    schlagstock_des_enterpiraten=1
    schleichsohlen_des_belagerers=1
    schulterpolster_der_schumenden_wut=1
    schwarzwasserschimmerschuppenweste=1
    sivaras_schlngelklinge=1

itemIDs: 158075, 159294, 159310, 159320, 159322, 159333, 159461, 159617, 159973, 168343, 168348, 168377, 168818, 168887, 169156, 169313, 2575
build: v8.2.5-04.04
level: 120 (120)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    cheat_death
    dancing_steel
    prey_on_the_weak
    quick_draw
    vigor

azerite: ace_up_your_sleeve=3
    azerite_empowered=3
    brigands_blitz=1
    deadshot=1
    heed_my_call=1
    impassive_visage=1
    keep_your_wits_about_you=1
    lying_in_wait=2
    overwhelming_power=2

essences: [essence_of_the_focusing_iris]=3, memory_of_lucid_dreams=3, vision_of_perfection=2

sets/legendaries/artifacts: none

gear:     band_des_uralten_baggerschiffs=1
    gezeitenblutarmschienen=1
    glnzend_goldenes_gefieder=1
    grtung_des_azeritarsenals=1
    handschuhe_der_unvergleichlichen_schnheit=1
    herz_von_azeroth=1
    logikleitring_der_synergie=1
    pantalons_des_seelufers=1
    phiole_des_arkanen_sturms=1
    raals_latz=1
    reif_des_einhllenden_leviathans=1
    rotes_leinenhemd=1
    schlagstock_des_enterpiraten=1
    schleichsohlen_des_belagerers=1
    schulterpolster_der_schumenden_wut=1
    schwarzwasserschimmerschuppenweste=1
    sivaras_schlngelklinge=1

itemIDs: 158075, 159294, 159310, 159320, 159322, 159333, 159461, 159617, 159973, 168343, 168348, 168377, 168818, 168887, 169156, 169313, 2575

New Recommendations for [ AOE ] requested at 23:11:23 ( 197577.07 ).

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00 ).
 - combo_points, 0 / 5
 - energy, 150 / 150

Processing precombat action list [ Outlaw - precombat ].
Current recommendation was NO ACTION at +60.00s.

[001] potion ( precombat - 1 ) - ability disabled.

[002] marked_for_death ( precombat - 2 ) - ability unknown

[003] stealth ( precombat - 3 )
The action (stealth) is usable at (0.00 + 0.00) with cost of 0.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: ( ! equipped.pocketsized_computation_device[false] | ! cooldown.cyclotronic_blast.duration[0.00] | raid_event.invulnerable.exists[false] )
Action chosen:  stealth at 0.00!
Completed precombat action list [ Outlaw - precombat ].
Recommendation is stealth at 0.00 + 0.00.
Recommendation #1 is stealth at 0.00s (0.00s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 0.00 ).
 - combo_points, 0 / 5
 - energy, 150 / 150

Processing precombat action list [ Outlaw - precombat ].
Current recommendation was NO ACTION at +60.00s.

[001] potion ( precombat - 1 ) - ability disabled.

[002] marked_for_death ( precombat - 2 ) - ability unknown

[003] stealth ( precombat - 3 )
The action (stealth) is unusable at (0.00 + 2.00) because already in stealth.

[004] roll_the_bones ( precombat - 4 )
The action (roll_the_bones) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.

[005] slice_and_dice ( precombat - 5 ) - ability unknown

[006] adrenaline_rush ( precombat - 6 ) - ability disabled.

[007] azsharas_font_of_power ( precombat - 7 ) - ability disabled.

[008] cyclotronic_blast ( precombat - 8 ) - ability unknown
Completed precombat action list [ Outlaw - precombat ].

Processing default action list [ Outlaw - default ].
Current recommendation was NO ACTION at +60.00s.

[009] kick ( default - 1 ) - ability disabled.

[010] stealth ( default - 2 )
The action (stealth) is unusable at (0.00 + 2.00) because already in stealth.

[011] variable ( default - 3 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:3).

[012] variable ( default - 4 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:4).

[013] variable ( default - 5 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:5).

[014] variable ( default - 6 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:6).

[015] variable ( default - 7 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:7).

[016] variable ( default - 8 )
 - variable.ambush_condition will check this script entry (Outlaw:default:8).

[017] variable ( default - 9 )
 - variable.bte_condition will check this script entry (Outlaw:default:9).

[018] variable ( default - 10 )
 - variable.blade_flurry_sync will check this script entry (Outlaw:default:10).

[019] call_action_list ( default - 11 )
Criteria PASS at +0.00 - stealthed.all[true]
Action list (stealth) was found.
+ stealth
Current recommendation was NO ACTION at +60.00s.

[020] ambush ( stealth - 1 )
The action (ambush) is usable at (0.00 + 0.00) with cost of 50.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
List ( stealth ) called from ( Outlaw:default:11 ) would PASS at 0.00.
 - stealthed.all[true]
 - this entry has no criteria to test.
Action chosen:  ambush at 0.00!
Returned from list (stealth), current recommendation is ambush (+0.00).
- stealth
The recommended action (ambush) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Outlaw - default ].
Recommendation is ambush at 0.00 + 0.00.
Recommendation #2 is ambush at 0.00s (0.00s).

RECOMMENDATION #3 ( Offset: 0.00, GCD: 1.00 ).
 - combo_points, 2 / 5
 - energy, 100 / 150

Processing precombat action list [ Outlaw - precombat ].
Current recommendation was NO ACTION at +60.00s.

[001] potion ( precombat - 1 ) - ability disabled.

[002] marked_for_death ( precombat - 2 ) - ability unknown

[003] stealth ( precombat - 3 )
We are already in-combat and this pre-combat action is not essential.  Skipping.

[004] roll_the_bones ( precombat - 4 )
We are already in-combat and this pre-combat action is not essential.  Skipping.

[005] slice_and_dice ( precombat - 5 ) - ability unknown

[006] adrenaline_rush ( precombat - 6 ) - ability disabled.

[007] azsharas_font_of_power ( precombat - 7 ) - ability disabled.

[008] cyclotronic_blast ( precombat - 8 ) - ability unknown
Completed precombat action list [ Outlaw - precombat ].

Processing default action list [ Outlaw - default ].
Current recommendation was NO ACTION at +60.00s.

[009] kick ( default - 1 ) - ability disabled.

[010] stealth ( default - 2 )
The action (stealth) is unusable at (0.00 + 2.00) because cannot stealth in combat.

[011] variable ( default - 3 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:3).

[012] variable ( default - 4 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:4).

[013] variable ( default - 5 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:5).

[014] variable ( default - 6 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:6).

[015] variable ( default - 7 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:7).

[016] variable ( default - 8 )
 - variable.ambush_condition will check this script entry (Outlaw:default:8).

[017] variable ( default - 9 )
 - variable.bte_condition will check this script entry (Outlaw:default:9).

[018] variable ( default - 10 )
 - variable.blade_flurry_sync will check this script entry (Outlaw:default:10).

[019] call_action_list ( default - 11 )
Criteria FAIL at +0.00 - stealthed.all[false]

[020] call_action_list ( default - 12 )
There is no criteria for this action list..
Action list (cds) was found.
+ cds
Current recommendation was NO ACTION at +60.00s.

[021] call_action_list ( cds - 1 )
Criteria PASS at +0.00 - ! stealthed.all[false]
Action list (essences) was found.
+ cds, essences
Current recommendation was NO ACTION at +60.00s.

[022] concentrated_flame ( essences - 1 ) - ability unknown

[023] blood_of_the_enemy ( essences - 2 ) - ability unknown

[024] guardian_of_azeroth ( essences - 3 ) - ability unknown

[025] focused_azerite_beam ( essences - 4 )
The action (focused_azerite_beam) is usable at (0.00 + 1.00) with cost of 0.
 - the action is ready before the current recommendation (at +1.00 vs. +60.00).
List ( cds ) called from ( Outlaw:default:12 ) would PASS at 1.00.
 - NONE
List ( essences ) called from ( Outlaw:cds:1 ) would PASS at 1.00.
 - ! stealthed.all[false]
 - this entry's criteria PASSES: spell_targets.blade_flurry[3.00] >= 2 | raid_event.adds.in[3600.00] > 60 & ! buff.adrenaline_rush.up[false]
Action chosen:  focused_azerite_beam at 1.00!

[026] purifying_blast ( essences - 5 ) - ability unknown
The recommended action (focused_azerite_beam) would be ready before the next GCD (1.00 < 1.00); exiting list (essences).
Returned from list (essences), current recommendation is focused_azerite_beam (+1.00).
- essences
The recommended action (focused_azerite_beam) would be ready before the next GCD (1.00 < 1.00); exiting list (cds).
Returned from list (cds), current recommendation is focused_azerite_beam (+1.00).
- cds
The recommended action (focused_azerite_beam) would be ready before the next GCD (1.00 < 1.00); exiting list (default).
Completed default action list [ Outlaw - default ].
Recommendation is focused_azerite_beam at 0.00 + 1.00.
Recommendation #3 is focused_azerite_beam at 1.00s (1.00s).
Advancing clock by 1.00...
Advancing clock by 1.10...
Advancing clock by 1.10...

RECOMMENDATION #4 ( Offset: 3.20, GCD: 1.01 ).
 - combo_points, 2 / 5
 - energy, 150 / 150

Processing precombat action list [ Outlaw - precombat ].
Current recommendation was NO ACTION at +60.00s.

[001] potion ( precombat - 1 ) - ability disabled.

[002] marked_for_death ( precombat - 2 ) - ability unknown

[003] stealth ( precombat - 3 )
We are already in-combat and this pre-combat action is not essential.  Skipping.

[004] roll_the_bones ( precombat - 4 )
We are already in-combat and this pre-combat action is not essential.  Skipping.

[005] slice_and_dice ( precombat - 5 ) - ability unknown

[006] adrenaline_rush ( precombat - 6 ) - ability disabled.

[007] azsharas_font_of_power ( precombat - 7 ) - ability disabled.

[008] cyclotronic_blast ( precombat - 8 ) - ability unknown
Completed precombat action list [ Outlaw - precombat ].

Processing default action list [ Outlaw - default ].
Current recommendation was NO ACTION at +60.00s.

[009] kick ( default - 1 ) - ability disabled.

[010] stealth ( default - 2 )
The action (stealth) is unusable at (3.20 + 0.00) because cannot stealth in combat.

[011] variable ( default - 3 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:3).

[012] variable ( default - 4 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:4).

[013] variable ( default - 5 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:5).

[014] variable ( default - 6 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:6).

[015] variable ( default - 7 )
 - variable.rtb_reroll will check this script entry (Outlaw:default:7).

[016] variable ( default - 8 )
 - variable.ambush_condition will check this script entry (Outlaw:default:8).

[017] variable ( default - 9 )
 - variable.bte_condition will check this script entry (Outlaw:default:9).

[018] variable ( default - 10 )
 - variable.blade_flurry_sync will check this script entry (Outlaw:default:10).

[019] call_action_list ( default - 11 )
Criteria FAIL at +3.20 - stealthed.all[false]

[020] call_action_list ( default - 12 )
There is no criteria for this action list..
Action list (cds) was found.
+ cds
Current recommendation was NO ACTION at +60.00s.

[021] call_action_list ( cds - 1 )
Criteria PASS at +3.20 - ! stealthed.all[false]
Action list (essences) was found.
+ cds, essences
Current recommendation was NO ACTION at +60.00s.

[022] concentrated_flame ( essences - 1 ) - ability unknown

[023] blood_of_the_enemy ( essences - 2 ) - ability unknown

[024] guardian_of_azeroth ( essences - 3 ) - ability unknown

[025] focused_azerite_beam ( essences - 4 )
The action is not ready before our maximum delay window (15.00) for this query.

[026] purifying_blast ( essences - 5 ) - ability unknown

[027] the_unbound_force ( essences - 6 ) - ability unknown

[028] ripple_in_space ( essences - 7 ) - ability unknown

[029] worldvein_resonance ( essences - 8 ) - ability unknown

[030] memory_of_lucid_dreams ( essences - 9 ) - ability unknown
Returned from list (essences), current recommendation is NO ACTION (+60.00).
- essences

[031] adrenaline_rush ( cds - 2 ) - ability disabled.

[032] marked_for_death ( cds - 3 ) - ability unknown

[033] marked_for_death ( cds - 4 ) - ability unknown

[034] blade_flurry ( cds - 5 )
The action (blade_flurry) is usable at (3.20 + 1.01) with cost of 15.
 - the action is ready before the current recommendation (at +1.01 vs. +60.00).
List ( cds ) called from ( Outlaw:default:12 ) would PASS at 1.01.
 - NONE
 - this entry's criteria PASSES: spell_targets.any[3.00] >= 2 & ! buff.blade_flurry.up[false] & ( ! raid_event.adds.exists[true] | raid_event.adds.remains[3600.00] > 8 | raid_event.adds.in[3600.00] > ( 2 - cooldown.blade_flurry.charges_fractional[2.00] ) * 25 )
Action chosen:  blade_flurry at 1.01!

[035] ghostly_strike ( cds - 6 ) - ability unknown
The recommended action (blade_flurry) would be ready before the next GCD (1.01 < 1.01); exiting list (cds).
Returned from list (cds), current recommendation is blade_flurry (+1.01).
- cds
The recommended action (blade_flurry) would be ready before the next GCD (1.01 < 1.01); exiting list (default).
Completed default action list [ Outlaw - default ].

**Comment by Hekili** [comment]
The snapshot provided doesn't match your report. 

Most APLs don't consider ranged vs. melee when making recommendations, as the right answer is generally to get in melee. You can exercise judgment and Pistol Shot when you can't get into melee.
