### ISSUE TITLE
[REC] feral druid getting stuck providing recommendations / frozen

### ISSUE THREAD

**Issue by knifebunny** [Hekili/hekili#2421]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since the most recent APL update that has feral finishing at 4+ combo points, I have been having issues whereby while following the rotation, Hekili's recommendations will not update, or rather the recommendations appear to be 'frozen in time'

By 'frozen in time' I mean the priorities do not update, the list of priorities is then static, and still shows perhaps abilities that cannot be used or are otherwise on cooldown.

What I have noticed is that the recommendations seem to become unstuck / un-frozen within a few seconds of 'beserk' coming off cooldown.  There doesn't seem to be any specific way to prompt or coerce this to occur (e.g. leaving combat)

When I specifically binded a key for snapshotting, it seems like it is getting stuck on tiger's fury?

### How to Reproduce

I cannot reliably reproduce this on target dummies, but seems to happen at least once or twice in a dungeon or in world content

### Snapshot (Link)

https://pastebin.com/TTkLja3A

### Contact Information

knifebunny@gmail.com

**Comment by Hekili** [comment]
This should be addressed in 1.0.17.
