### ISSUE TITLE
[REC] "Sentinel" doesnt show SpellFlash and cannot be added to a toggle

### ISSUE THREAD

**Issue by PopsGG** [Hekili/hekili#2422]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Prot paladin ability "Sentinel" doesnt show SpellFlash. It is also not listed under Abilities in the settings, so it cannot be added to a toggle or disabled.

Based on the Snapshot, I am guessing its a conflict with "Avenging Wrath" because they are alternate abilities in talents that replace each other.

### How to Reproduce

1. Go to tanking dummy and engage
2. Quickly "Sentinel" will be recommended, but there is no SpellFlash on action button.

1. Under Settings > Abilities 
2. Sentinel is not listed

### Snapshot (Link)

https://pastebin.com/x7sWZzmD

### Additional Information

NA

### Contact Information

Gurk#4116

**Comment by PopsGG** [comment]
Talents: BIEAwtJ2KpR8WbGzhz/jy2AP80SaJkiodgISiSTSiERiEAAAAAAAAAAAAAA0EJJRSISUSJJBFKB

**Comment by Hekili** [comment]
Sentinel is treated as a replacement of Avenging Wrath, so it doesn't have it's own entry.  I've now made Sentinel's spell ID flashable which will show up in the next release (which will be 1.0.18 in the next day or two).
