### ISSUE TITLE
FPS Stuttering only on Feral/Guardian Druid

### ISSUE THREAD

**Issue by picklerick84** [Hekili/hekili#2423]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I play as druid, only tested Feral and Guardian atm since I raid as feral and tank m+.  As soon as I login to the game I start getting fps stutters about every 2 seconds, even just in a city and not in combat or near it.  It actually makes it super irritating to raid with it.  It doesn't seem to get worse during combat, it just persists through my entire play period.

As far as can tell, it only happens on druid.  I play all 6 tanks specs and some dps as those classes as well and no other class/spec that I can find has the issue so far.

I'm certain it is Hekili though.  I've disabled every addon and used default ui with just Hekili enabled to try and get a better raid experience and it persists until I disable Hekili and then the fps is perfect again.

### How to Reproduce

Login to the game playing a druid.

### Player Information (Link)

https://pastebin.com/2x1K9Mc7

### Error Messages (Link)

NA

### Additional Information

There are no issues that pop up in bugsack/bug grabber

### Contact Information

Discord: Juicefactory#9818

**Comment by Hekili** [comment]
Can you provide snapshots from both Feral and Guardian as well as your talent export strings for each?  Thanks!

**Comment by picklerick84** [comment]
This is for Feral

Talent String:  BcGAPjJFohhWlFcNj9E1Av/dNBAAAAAAIJplmEikIpoEUSSSkEAAAAAAKAIJAAJJJhkItEaJOAAAAAAAkAaAA
![image_2023-02-22_114647490](https://user-images.githubusercontent.com/66019145/220728630-421f67f4-3822-4f60-b2d1-29ce81777bbe.png)

https://pastebin.com/GGJEwsjg

**Comment by picklerick84** [comment]
This is for Guardian

Talents String:  BgGAPjJFohhWlFcNj9E1Av/dNBAAAAAAAAAAAAAJJJRSJUSSSyBCkEShCASCCSgkkESiUgWiDAAAAAAICIaAA

![image_2023-02-22_115229238](https://user-images.githubusercontent.com/66019145/220730062-9877da41-9401-4a36-ba48-dd54bd695926.png)

https://pastebin.com/XwTkibJw

**Comment by picklerick84** [comment]
I also deleted the addon and settings and reinstalled it in case something was messed up.  Still have the same result though

**Comment by Hekili** [comment]
I've found a few optimizations that are not Druid-specific as I investigate this issue.  If you notice that it seems related to any particular class talents or other shared mechanics, please let me know.  I'm still digging.

**Comment by picklerick84** [comment]
Sounds good.  I haven't really noticed the issue in other classes/specs I play, but druid is my main so maybe its just not as bad on other ones so I haven't noticed.  I will see if I notice anything on the other classes.

**Comment by Hekili** [comment]
Let me know if you notice any difference with the current alpha release here:  https://github.com/Hekili/hekili/releases/download/v10.0.5-1.0.18-alpha2/Hekili-v10.0.5-1.0.18-alpha2.zip

I don't think it's fully resolved but that alpha includes some new optimization and fixes some bugs that could eat CPU time.

**Comment by Jovetic** [comment]
Hey Hekili, I just installed the Alpha having also had issues with fps while using the addon. The new build is perfect.  Target dummies in Vald earlier were 150-160k dps.  Now I'm doing 200k dps.  So much smoother.  Thank you :)

**Comment by knifebunny** [comment]
I also note performance improvements in the new alpha, well over 200k dps on training dummies now and in general feels smoother, thank you

**Comment by picklerick84** [comment]
I haven't been able to test it yet.  I have raid in less than 2 hrs tho, so I can test it during that and let you know how it is after.

**Comment by picklerick84** [comment]
I'm still raiding atm testing on Mythic Broodkeeper and it started smooth at the start of the raid and at about 45 minutes in, it started doing the same again as feral. I can't test as guardian right now.  I'll upload another snapshot to pastebin.

My talent string right now is:   BcGAPjJFohhWlFcNj9E1Av/dNBAAAAAAISapJhkkIpoEUSSSkEAAAAAAKAkIAAJJJJSi0Sol4AAAAAAAQCAA

![image_2023-02-23_192616972](https://user-images.githubusercontent.com/66019145/221076919-cd9427d5-206c-466a-ab65-d3f0b756d798.png)


Pastebin of snapshot:  https://pastebin.com/mZYZSmR9

**Comment by Hekili** [comment]
> it started smooth at the start of the raid and at about 45 minutes in, it started doing the same again as feral

Interesting; there's nothing special about a 45 minute mark.  Does this persist through a `/reload`?  Thanks for checking back.

**Comment by picklerick84** [comment]
Yea. I reloaded multiple times once it started, usually disabling addons to see if anything could make it stop doing it.  I should've saved a short clip, so it's easier to see what I'm talking about.  Basically about every 2 seconds, everything moving stops for about a half sec and then it starts again with everything catching back up.

Could it have to do with changing talents or equipment or anything?  Sometimes I swap trinkets and/or talents.

**Comment by Hekili** [comment]
Of course. If you find more specific details for when it happens (talents, gear, etc.), then it's easier to diagnose. That's what snapshotting aims to help gather.

**Comment by Hekili** [comment]
Did you find any information about particular trinkets/gear/etc. seeming to cause this issue for you?
