### ISSUE TITLE
Hekili no longer recommends fel rush alone to activate Momentum.

### ISSUE THREAD

**Issue by Zeuslight56** [Hekili/hekili#2425]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili no longer recommends fel rush alone to activate Momentum compared to the update before while the Momentum buff increases the dps. This time Hekili recommends it but only when untied chaos is active. before the last update I was at 75% and more in buff Momentum, here I am at 50% so it's a big loss of dps.

### How to Reproduce

1 Get into the game
2 Select the classic AOE build BEkACnvaHJn8GSPD6tpaeczPThkkkkIlg0SSEJSTEAAAAAAAtkEEpQSUCSSaJBSgEA 
3 hekili no longer recommends fel rush in phases where Momentum is not active.

### Snapshot (Link)

https://pastebin.com/F5b6j9Az

**Comment by Hekili** [comment]
?

**Comment by Zeuslight56** [comment]
Strangely, by making a dungeon I realized that the DPS remains unchanged or even better even with this update.
