### ISSUE TITLE
Grieftorch/Puzzlebox seem to scale with haste now

### ISSUE THREAD

**Issue by legacy3** [Hekili/hekili#2426]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The cast time of Grieftorch/Puzzlebox seems to scale with haste now. Not sure about other trinkets.

### How to Reproduce

1. Cast the trinket and see that its hasted.

### Snapshot (Link)

-

**Comment by Hekili** [comment]
Thanks, this will be in the next release.
