### ISSUE TITLE
Blizzard not recommended on aoe

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#2427]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During raid trash i just realised that blizzard is never recommended at any point with 2+ mobs

### How to Reproduce

Enter fight with more then 2 mobs and see that it doesn't get recommended

### Snapshot (Link)

https://pastebin.com/h8QiHHEn

**Comment by Hekili** [comment]
```
18.  call_action_list:aoe ( default - 4 )
Criteria for aoe FAIL at +0.00 - active_enemies[5.00] >= 7 | active_enemies[5.00] >= 3 & talent.ice_caller.enabled[false]
```
The `aoe` action list is invoked with 7+ targets or 3+ targets with Ice Caller.

```
27.  blizzard ( st - 8 )
The action (blizzard) is usable at (0.00 + 0.00) with cost of 5000 mana (have 250000).
 - this entry's criteria FAILS: active_enemies[5.00] >= 2 & talent.ice_caller.enabled[false] & talent.freezing_rain.enabled[false]
```
In the `st` action list, Blizzard is used with 2+ enemies if you have both Ice Caller and Freezing Rain talented.

The conditions for using Blizzard are not met in your snapshot.

**Comment by Tzuyume** [comment]
okey so its all working like intended then, thanks

**Comment by Hekili** [comment]
Yeah, at least it's consistent with the sims (which is what I aim to present).  You could explore customizing a priority if you wanted to use Blizzard with fewer targets/different talents.

**Comment by Tzuyume** [comment]
honestly i think i might've gotten so used to it from m+ build and didn't notice it was a talent that made it worth doing.
