### ISSUE TITLE
[REC] Hekili recommends Roll The Bones when I have multiple buffs up

### ISSUE THREAD

**Issue by dejdara111** [Hekili/hekili#2428]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Outlaw Rogue I often am recommended to reroll my buffs with Roll the Bones even though I have 4-6 buffs thanks to Count the Odds.

### How to Reproduce

1. Enter the game as Outlaw Rogue.
2. Take Shadow Dance and Count the Odds talents. I'm only taking one point of Count the Odds.
3. Use Roll the Bones until you get a bad roll that would usually be recommended to reroll.
4. Reset your Roll the Bones cooldown.
5. Use haste buffs like Adrenaline Rush.
6. Use Vanish and Shadow Dance to get as many casts of Ambush and Dispatch as possible in a short period of time to get Count the Odds buffs. (It's very random since Count the Odds only has 10% chance per Ambush / Dispatch cast)

### Snapshot (Link)

https://pastebin.com/QXzPxEY6

### Additional Information

It's actually hard to snapshot it accurately for me because I get the most buffs from Count the Odds in Raids and dungeons thanks to Bloodlust as my gear is very low haste. Also hard to snapshot in the middle of the raid pull. In my snapshot there are only 3 buffs but in a raid I often get up to 5-6 and still being told to reroll.

### Contact Information

Waleera#8986

**Comment by Hekili** [comment]
Please update to the new alpha version and let me know if this appears resolved.  It is version v10.0.5-1.0.18-alpha2.  Thanks!

https://github.com/Hekili/hekili/releases/tag/v10.0.5-1.0.18-alpha2

**Comment by dejdara111** [comment]
Hi, tested with the version mentioned above. The issue is still there - addon told me to reroll with 4 buffs.
Made another snapshot:

https://pastebin.com/V8k8v64v

**Comment by Hekili** [comment]
Thanks; I think I've captured the "short buffs are only safe if there are no normal buffs" logic now.  Try -alpha3 when it posts in a little bit.

**Comment by dejdara111** [comment]
I've got another snapshot from an actual raid environment today. Again 4 buffs up and telling me to reroll, was 5 buffs but I was a little slow snapshotting it so one actually ended. But it's on the v10.0.5-1.0.17 so I don't know if it's of any use to you.
v10.0.5-1.0.18-alpha2 stopped working for me for some reason so I reinstalled v10.0.5-1.0.17 right before the raid.

https://pastebin.com/y4fx5d15

**Comment by Hekili** [comment]
Nope, the snapshot has to be from the current -alpha3 that we're testing for it to be relevant.  I've made specific changes there in terms of how it decides which buffs will get wiped by using Roll the Bones.

**Comment by Hekili** [comment]
@dejdara111 Any further testing?

**Comment by dejdara111** [comment]
I have not tested it on alpha3 yet. I've got a raid on Wednesday.

**Comment by dejdara111** [comment]
Hey, sorry for the long wait (I skipped Sunday's raid night). I tested v10.0.5-1.0.20 on yesterday's raid night and it seems to be totally fine now. I didn't get any suspicious roll suggestions, I used to get them often on openers before.
Anyways all's good now, thank you for the fix.
