### ISSUE TITLE
Gift of the Naaru

### ISSUE THREAD

**Issue by brucek2** [Hekili/hekili#243]
Please describe your idea or feature and when it would be useful.
I would like to be able to use the ability "Gift of the Naaru" (draenei racial, 20% heal over 5 seconds) in my action lists.

(Apologies if this is already possible, I looked through all the ability drop downs in every context I could find them and never saw it listed.)

**Comment by Hekili** [comment]
This is an easy addition; I'll make it available for custom action lists.
