### ISSUE TITLE
Assassination not recommending anything

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#2432]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sometimes assassination seems to lag my game alot then stops recommending anything at all until i press something.

### How to Reproduce

Happens seemingly random i dont know what causes it.

### Snapshot (Link)

https://pastebin.com/yWzC264S

**Comment by Hekili** [comment]
Do you have any abilities disabled?

Do you have any thoughts about what should've been recommended?  Your target has Garrote falling off but no Rupture:
```
target_debuffs:
      703 - garrote                                  -   1 - 0.88  
     2818 - deadly_poison_dot                        -   1 - 13.82 
     3409 - crippling_poison_dot                     -   1 - 9.48  
   392388 - atrophic_poison_dot                      -   1 - 9.32  
   383414 - amplifying_poison_dot                    -  16 - 11.32
```

You had 6 combo points and 53 energy, and the following buffs:
```
player_buffs:
     3408 - crippling_poison                         -   1 - 1158.83
   381637 - atrophic_poison                          -   1 - 1157.02
     2823 - deadly_poison                            -   1 - 1155.04
   381664 - amplifying_poison                        -   1 - 1153.21
   315496 - slice_and_dice                           -   1 - 48.60 
    32645 - envenom                                  -   1 - 3.10  
   108211 - leeching_poison                          -   1 - 3600.00
   186401 - *sign_of_the_skirmisher                  -   1 - 3600.00
   394845 - septic_wounds                            -   5 - 7.35  
   193538 - alacrity                                 -   4 - 4.03  
   381754 - blessing_of_the_bronze_rogue             -   1 - 3306.57
      465 - *devotion_aura                           -   1 - 3600.00
   207386 - *spring_blossoms                         -   1 - 5.77  
```

My first assumption is that the logic that avoids using Rupture on a target that's going to die in < 4 seconds is blocking you from spending CP, Envenom's criteria aren't met, and the logic that doesn't want to overcap CP won't recommend a generator afterward.

**Comment by Tzuyume** [comment]
I have nothing at all disabled that i know of, im not sure at all what should be shown it just seems weird it stops appearing at all for a while

**Comment by Tzuyume** [comment]
Maybe it should recommend to rapture another target around?

**Comment by Hekili** [comment]
You didn't have any other targets to Rupture.

There's a subtle issue related to the addon trying to time when it should retest an action, related to conditions like `energy.deficit<=25+energy.regen_combined`.  If `energy.regen_combined` changes due to a buff falling off, then the timing is off and the condition still ends up failing.

In this case, though, I think I'm going to just solve by allowing the Envenom recommendation to pass when you've maxed out combo points and Rupture's being withheld since your target is about to die.

**Comment by Hekili** [comment]
My solution for this will be in the next release.
