### ISSUE TITLE
Lvl 66 Protection Paladin, Addon suggests Auto-Attack that never goes away

### ISSUE THREAD

**Issue by chaoszone** [Hekili/hekili#2434]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am currently Level 66 and the addon always suggest to use the auto-attack.
This suggestion does not go away even after a few seconds.

### How to Reproduce

1. Enter combat
2. Follow the suggestions of the addon

### Snapshot (Link)

https://pastebin.com/MrJkQshG

**Comment by chaoszone** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/19907220/221360718-37d7d0fc-e0bf-441f-8816-cce29c3ec6f2.png">

**Comment by Hekili** [comment]
No, you have the horseman's sword which you can use to summon pumpkins. 

The addon never suggests auto attack.

**Comment by chaoszone** [comment]
sorry, I am stupid
