### ISSUE TITLE
FERAL / Ferocious Bite Build Finisher

### ISSUE THREAD

**Issue by belfastbiker** [Hekili/hekili#2435]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In a Ferocious Bite Feral build, but when hitting against AOE, with no points in Tear Open Wounds and instead taking Taste for Blood and Relentless Predator. I'd only expect to refresh Primal Wrath every 10 seconds, and in between finish with Ferocious Bite instead.   Hekili is telling me to Primal Wrath every finisher.  I've looked through settings, and am not smart enough to sort this. 

My build.
BcGAPjJFohhWlFcNj9E1Av/dNBAAAAAAIRapJRSSikiyBQJJJRSAAAAAAAAJCAQSSSikItEaJCAAAAAAkAAA

### How to Reproduce

Dummies in Valdrakken, us the Ferocious Bite build above, and you'll see it still wants to PW every finisher.

### Snapshot (Link)

https://pastebin.com/eTTYw4Dd

**Comment by Hekili** [comment]
Have you simmed yourself for comparison?  I don't think the Feral simc priority actually does funnel, but it is something I plan to shoehorn in anyway.  Go ahead and link your Raidbots sim for comparison.

**Comment by Hekili** [comment]
I went ahead and threw in an experimental option for funneling in 1.0.18.  After you've updated, see /hekili > Feral > Ferocious Bite Funnel and see if it works well.  It requires TfB and RP and turns off if TOW is taken.  I'll think more about it when I'm not sick.

**Comment by belfastbiker** [comment]
TY so much, gonna test it now and compare.....  Do you have a donation account?

**Comment by belfastbiker** [comment]
OK, seems to do broadly similar damage on group of dummies, while having the advantage of also being better on single target.  I think I'll keep the ferocious build, thank you for the addon, and get well soon!
