### ISSUE TITLE
"Better Hekili Targeting" WeakAura breaks in v10.0.5-1.0.18+ (attempt to perform arithmetic on field 'lastAudit')

### ISSUE THREAD

**Issue by Micijah** [Hekili/hekili#2436]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Logged in and received a constant local error - 384

8300x [string "return function() "]:447: attempt to perform arithmetic on field 'lastAudit' (a nil value)
[string "return function() "]:447: in function `getNumberTargets'
[string "@Hekili/UI.lua"]:1351: in function <Hekili/UI.lua:926>

Locals:
frameTime = 2902.294000
(*temporary) = nil
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0
(*temporary) = 1
(*temporary) = "nameplate40"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "nameplate40"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 LWA = <table> {
 }
}
(*temporary) = "UnitGUID"
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to perform arithmetic on field 'lastAudit' (a nil value)"
lastCycle = nil
lastCount = 0
validTarget = <function> defined return function() :335
enemyExclusions = <table> {
 23775 = true
 161895 = true
 163122 = true
 160966 = true
 352052 = true
 157452 = true
 163126 = true
 165913 = true
 164698 = true
 165108 = true
 170483 = true
 166970 = true
 168962 = true
 174786 = true
 169159 = true
 173447 = true
 164501 = true
 170147 = true
 168365 = true
 168988 = true
 170217 = true
 168445 = true
 156227 = true
 164578 = true
 166079 = true
 166971 = true
 165251 = true
 166885 = true
 120651 = true
 166969 = true
}
auraExclusions = <table> {
 1 = 310126
 2 = 321764
 3 = 323149
 4 = 323190
 5 = 333293
 6 = 329808
 7 = 329636
 8 = 333737
 9 = 327812
 10 = 355790
 11 = 33786
 12 = 217832
 13 = 710
 14 = 118
 15 = 51514
}
ns = <table> {
 FindPlayerAuraByID = <function> defined @Hekili/Utils.lua:516
 specTemplate = <table> {
 }
 hasRequiredResources = <function> defined @Hekili/State.lua:7081
 IsTimer = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 forecastResources = <function> defined @Hekili/State.lua:1325
 frameProfile = <table> {
 }
 UnregisterUnitEvent = <function> defined @Hekili/Events.lua:221
 Localize = <table> {
 }
 setClass = <function> defined @Hekili/Classes.lua:5715
 debug = <table> {
 }
 GetTexString = <function> defined @Hekili/Utils.lua:852
 GetTimer = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 queue = <table> {
 }
 SetTimer = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 addWhitespace = <function> defined @Hekili/Classes.lua:5663
 castsAll = <table> {
 }
 addSetting = <function> defined @Hekili/Classes.lua:5648
 GroupMembers = <function> defined @Hekili/Utils.lua:263
 spendResources = <function> defined @Hekili/State.lua:6659
 safeMax = <function> defined @Hekili/Utils.lua:243
 updateMinion = <function> defined @Hekili/Targets.lua:602
 safeAbs = <function> defined @Hekili/Utils.lua:255
 RegisterUnitEvent = <function> defined @Hekili/Events.lua:177
 attr = <table> {
 }
 RecycleTable = <function> defined @Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 updateEssences = <function> defined @Hekili/Events.lua:591
 AddTexString = <function> defined @Hekili/Utils.lua:840
 actorHasDebuff = <function> defined @Hekili/Targets.lua:645
 StopEventHandler = <function> defined @Hekili/Events.lua:130
 SpaceOut = <function> defined @Hekili/Utils.lua:54
 getModifier = <function> defined @Hekili/Targets.lua:685
 roundUp = <function> defined @Hekili/Utils.lua:139
 ResourceRegenerates = <function> defined @Hekili/Constants.lua:95
 FindStringInSpellTooltip = <function> defined @Hekili/Utils.lua:643
 wipeDebuffs = <function> defined @Hekili/Targets.lua:638
 GetResourceInfo = <function> defined @Hekili/Constants.lua:73
 round = <function> defined @Hekili/Utils.lua:132
 GetResourceKey = <function> defined @Hekili/Constants.lua:83
 GetResourceID = <function> defined @Hekili/Constants.lua:78
 Audit = <function> de

### How to Reproduce

The issue doesn't require behaviors to start. It just starts as soon as I log in or enable Hekili.

### Player Information (Link)

https://pastebin.com/m3JC378L

### Error Messages (Link)

https://pastebin.com/jdH2RHhq

### Contact Information

Micijah#9895

**Comment by Hekili** [comment]
Your Player Information indicates you're using 1.0.18-alpha2, which is not the latest version.  Update and let me know if you get this error.

**Comment by Micijah** [comment]
@Hekili apologies, here is the updated info with the same error.

Hekili Player Profile Updated - https://pastebin.com/xMX03G43

Bugsack Error Sub 2 - https://pastebin.com/2j1AJDLD

**Comment by Hekili** [comment]
I gotta say, I genuinely have no idea.  There's literally no `lastAudit` in my addon any longer at all.  I assume you've cleared your BugSack since using alpha2.

**Comment by Hekili** [comment]
Did you try making edits to the Assassination priority?  Most of those errors appear in the course of trying to compile the Assassination priority.  Try resetting that priority and reloading UI.

**Comment by parandsn** [comment]
Hello,
I am also experiencing a similar bug.

Character Data: [https://pastebin.com/u66VwHbh](https://pastebin.com/u66VwHbh)

Bugsack : [https://pastebin.com/eNqgLhfQ](https://pastebin.com/eNqgLhfQ)

**Comment by Hekili** [comment]
If you disable addons and run only Hekili (for testing purposes), do you get the same error?

**Comment by parandsn** [comment]
I do not, how curious. It appears to be weakauras that's causing the issue.

**Comment by UFTimmy** [comment]
I think a WeakAura called "Better Hekili Targeting" is causing the issue.
The WeakAura isn't on wago any more, but it was during Shadowlands. I tried it out and forgot about it.

I can confirm that it has lastAudit in its custom code, and disabling it removed the error mentioned in this issue.

**Comment by Hekili** [comment]
Thanks.  I'm going to lock and pin this thread; the author of that WeakAura will need to update it.  I recommend disabling it in the meantime.
