### ISSUE TITLE
[REC] Priest / Shadow - Dark Ascension recommended while on cooldown

### ISSUE THREAD

**Issue by DesertDwarf** [Hekili/hekili#2437]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During default rotation, Dark Ascension was recommended before it was off cooldown.

![WoW - Dark Ascension - Cooldown ignored by Hekili](https://user-images.githubusercontent.com/39987/221396374-2c218663-798f-4b0e-9af7-ba4e8eda0093.png)

### How to Reproduce

1. Enter the game as a Shadow Priest. (Mine is level 60.)
2. Load Icy Veins' recommended talents for leveling a Shadow Priest: BIQA16pR6xQxvK1VWhXk+w0/GAJtQAAAAAAAAAAAAAAcgSkmUIJJJlkIAakkDkINCSQIFpFSCA
3. Hit all the buttons Hekili recommended. Partway through Dark Ascension's 60-second cooldown, it is recommended again.

### Snapshot (Link)

https://pastebin.com/ZwwYqWZB

**Comment by Hekili** [comment]
Your snapshot needs to be taken when the recommendation is occurring.

**Comment by Hekili** [comment]
Please comment and I'll reopen if/when you have a snapshot that shows the recommendation in question.  Thanks!
