### ISSUE TITLE
[BUG] Preist Config Menu Error

### ISSUE THREAD

**Issue by evilgodly** [Hekili/hekili#2438]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

WotLK Classic: Sitting in Dal and wanted to turn off the MiniMap button on my 63 Shadow Priest. Going through the menus to find the option to turn off the MiniMap button and got this error when doing literately nothing and not changing anything. 

### How to Reproduce

1. Log into Priest already in Shadow Spec
2. Be in Dal
3. Bring up Addon Config Menus
4. Move around in the menus

### Player Information (Link)

https://pastebin.com/t6aPb16w

### Error Messages (Link)

https://pastebin.com/yHgzMjbA

### Contact Information

evil_godly#9187

**Comment by evilgodly** [comment]
i have tried this on my different toons and get the same error when moving through the Config menus, dal or SW or anywhere else.

**Comment by Hekili** [comment]
This'll be fixed soon.  It's just an issue with the generic PvP trinkets config page.
