### ISSUE TITLE
[REC] BM Hunter Spell Flash does not show all Recommendations, Cobra Shot in this example

### ISSUE THREAD

**Issue by Seikusa** [Hekili/hekili#2439]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When trying to set up spell flashes and trying out the spell flash recommendations I noticed that it didnt Spell Flash for Cobra shot
Then I checked the Recommendation Bar (the one with the standart 3 spell queue) and it showed Cobra Shot

### How to Reproduce

1. BM Hunter
2. Wowhead ST Spec
3. Follow the recommendations
4. See the discrepency between Spell Flash and Queue Bar

### Snapshot (Link)

https://pastebin.com/wRxasDWs

### Contact Information

Seikusa#8719

**Comment by Seikusa** [comment]
![image](https://user-images.githubusercontent.com/25350387/221428205-c6f1af00-b66b-42f7-8b82-deb2fcf11f9a.png)
Here is a Screenshot of it

**Comment by Seikusa** [comment]
I solved the Bestial Wrath Problem, I had to add the cooldowns toggle otherwise Bestial wrath didnt show (Strangly Bloodshedding and Death Chakram are not in the Cooldown tab.
Still cobra shot has no Spell flash.

**Comment by Hekili** [comment]
It may be that your Cobra Shot macro is set up in such a way that SpellFlash can't locate the ability.  I can see Cobra Shot lit up on my hunter with SpellFlash.

Can you try:
1. Placing the spell itself (not macroed) on your bar and see if it will flash?
2. Making sure Cobra Shot is the first usable spell in your macro?
3. (if your UI shows spell IDs) Responding back with the spell ID of Cobra Shot for your character?

Thanks!

**Comment by Hekili** [comment]
Please comment if there's a need to reopen this ticket.  Thanks.
