### ISSUE TITLE
cooldown.avenging_wrath.remains appears to be showing incorrect values

### ISSUE THREAD

**Issue by Turne087** [Hekili/hekili#244]
I'm currently getting guardian of azeroth as my number 1 priority as long as it's off cooldown for retribution paladin.  I went into the action lists to look at it and noticed that it's always evaluating to true. cooldown.avenging_wrath.remains is always evaluating to 104.4 and seems to be part of the cause of the problem(the other is cooldown.crusade.remains is evaluating to 120 even though the talent isn't active and fulfilling cooldown.crusade.remains >= 45).

 I'm assuming .remains is supposed to show the remaining cooldown(apologies if I'm wrong).  When avenging wrath is off cooldown it should evaluate to 96 seconds. Avenging Wrath is a 2 minute cd that is modified by the azerite essence Vision of Perfection that reduces it to 1.6 minutes.(96 seconds).  

Issue 1 - cooldown.avenging_wrath.remains value never changes and always remains at 104.4
Issue 2 - cooldown.avenging_wrath.remains should evaluate to 96 seconds when off cooldown
Issue 3 - cooldown.crusader.remains is evaluating to 120 when the talent isn't active(dont know if this is intended or not)

![awCD](https://user-images.githubusercontent.com/20669236/70861927-7ca3fa80-1efa-11ea-9ddb-d01535f9a3ac.PNG)
aw cd is 1.6 mins or 96 secs

![remains1](https://user-images.githubusercontent.com/20669236/70861928-7ca3fa80-1efa-11ea-9ba9-b61d8070b88d.PNG)
cooldown.avenging_wrath.remains is showing 104.4. On the bottom left of my action bars is the avenging wrath button. It's showing its off cooldown, avenging_wrath.remains should be showing 96

![remains2](https://user-images.githubusercontent.com/20669236/70861929-7ca3fa80-1efa-11ea-8894-a0da109c4e92.PNG)
avenging wrath is on cooldown.  It should be showing 51 seconds in cooldown.avenging_wrath.remains

build: v8.2.5-04.04
level: 120 (120)
class: PALADIN
spec: retribution

talents: cavalier
    execution_sentence
    fist_of_justice
    hammer_of_wrath
    inquisition
    selfless_healer
    wake_of_ashes

azerite: avengers_might=3
    azerite_empowered=3
    earthlink=1
    elemental_whirl=1
    expurgation=2
    gallant_steed=1
    heed_my_call=1
    impassive_visage=1
    lights_decree=1
    stalwart_protector=1

essences: [condensed_lifeforce]=3, conflict_and_strife=3, vision_of_perfection=3

sets/legendaries/artifacts: none

gear:     akanas_reefstrider_boots=1
    ashvanes_razor_coral=1
    band_of_the_ancient_dredger=1
    blood_knight_tabard=1
    breastplate_of_arterial_protection=1
    cloak_of_the_restless_tribes=1
    dribbling_inkpod=1
    eternity_keepers_greatbelt=1
    heart_of_azeroth=1
    helm_of_the_raptor_king=1
    legplates_of_charged_duality=1
    lockjaw_shoulderplate=1
    notorious_aspirants_ring=1
    poens_deepsea_handguards=1
    precious_ribbon=1
    tentacle_crusher=1
    waveblade_farseers_armguards=1

itemIDs: 158075, 159288, 159407, 159422, 159432, 159435, 159461, 167523, 168869, 168897, 169311, 169319, 170143, 170303, 170336, 25549, 52019

**Comment by Hekili** [comment]
Abilities linked to a toggle (i.e., Cooldowns) will have their remaining cooldown show as the maximum when the cooldown is disabled. This prevents the addon from trying to prepare to use the cooldown when you've told the addon not to use the cooldown.

**Comment by Turne087** [comment]
Ok, thanks for pointing this out.
