### ISSUE TITLE
[REQUEST] Add Chi-Ji and Sheilun's Gift mists available in priority logic

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#2440]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Mistweavers cannot currently track these two features:

Chi-ji stacks for Enveloping Mist

Sheilun's Gift mists, which comes into play when you are talented Shaohao's Lessons.

Would be nice to track both auras, as they are the base of the spec in mythic+

**Comment by Hekili** [comment]
Sorry, which specific auras are you asking for, with name and spell ID?  You can post Wowhead links.

For Sheilun's Gift mists, you're referring to the count of mists that is on the action button (but is not a visible aura), correct?

**Comment by oversoe** [comment]
You can currently track Chi-ji uptime, because of the different rotation, but Chi-ji adds a stacking buff: Spell ID: 343820.
It would be nice to be able to track this one to be able to tell when to cast enveloping mist in the chi-ji rotation.

Yes, I was referring to the cloud of sheilun's gift which would be some aura, I have yet to find.

**Comment by oversoe** [comment]
Edit; you can't track whether Chi-ji is up at all :-(

**Comment by Hekili** [comment]
What makes you think that?

**Comment by oversoe** [comment]
Sorry for the disturbance, but you've added the Chi-Ji stacking buff and it works PERFECTLY!

However I can't track whether chi-ji is active or not?

Is this the same spell and is it a buff/totem/pet?

buff.invoke_chiji.up?
totem.invoke_chiji.active?

**Comment by oversoe** [comment]
I went with cooldown.invoke_chiji.remains>48

**Comment by yurikenus** [comment]
I struggled with this some and previously found a solution, which I had documented here: https://github.com/Hekili/hekili/discussions/1280, but that was during Shadowlands.

However, it looks like the Discussions area of the project is no longer here, so that link is now dead (even though it is in my Github discussion history).

I believe it had something to do with treating Chiji as either a pet, guardian, or totem, since I also couldn't track it by an aura or buff.

**Comment by oversoe** [comment]
cooldown.invoke_chiji.remains>48 doesn't work after fix.
I can't get either totem or pet to work at all :-(

**Comment by Hekili** [comment]
Discussions got spammed hard by bots recently, so I shut it down.

In the next release, `chiji` and `yulon` can be referenced like any pet/totem:  `pet.chiji.up` will be true when Chi-Ji is active; `pet.yulon.remains` will give the remaining time on Yu'lon.

I've also added `gust_of_mist.count` as an expression that will show the # of mists (as shown on the Sheilun's Gift action button) and the addon will forecast mist gains from abilities (but not from time in combat).
