### ISSUE TITLE
[REC] Brewmaster Monk - Touch of Death not in priority

### ISSUE THREAD

**Issue by lolHakks** [Hekili/hekili#2441]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Monk ability Touch of Death is never recommended by the add-on. I believe this is because it is not included in any of the priority lists by default.

### How to Reproduce

1. Enter the game as a Brewmaster Monk
2. Engage in combat with any enemy.
3. If the enemy has less hit points than you, and the ability Touch of Death is not on cooldown the add-on should recommend Touch of Death in the cooldowns window.

### Snapshot (Link)

https://pastebin.com/vNF7ZecA

### Contact Information

Discord: Hakks#6041

**Comment by Hekili** [comment]
Let's not do titles in all caps.

I'll add it back to the Brewmaster priority.  Doesn't look like it's showing up in sim profiles right now.

**Comment by lolHakks** [comment]
Thanks for the work, sorry about the caps; honestly thought that was the format. Noted for the future.Sent from my iPhoneOn Feb 26, 2023, at 11:20 PM, Hekili ***@***.***> wrote:﻿
Closed #2441 as completed.
