### ISSUE TITLE
[FEATURE] DH Havoc option to reserve 1-2 charges of Fel Rush and Throw Glaive

### ISSUE THREAD

**Issue by pdrayton** [Hekili/hekili#2442]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

For DH Vengeance, there is the option to reserve some number of Infernal Strike (IS) charges. Hekili generates IS recommendations only when using IS would still leave N charges available. This is very useful to keep a charge available for ad-hoc use.

For DH Havoc there are talents that provide for 2 charges of Fel Rush (FR) and 2 charges of Throw Glaive (TG). By default the APL spends all charges of FR and TG but it would be helpful to have the same option as vengeance - to reserve N charges of FR or TG to keep them available for ad-hoc use.

Examples of ad-hoc use for TG would be holding a charge until Thundering starts, or holding a charge until the next Fodder to the Flame proc so you can immediately bounce a glaive off the demon for the damage buff. Examples of ad-hoc use of FR is retaining a charge to allow for movement utility. Also, for FR most of the DPS guides suggest keeping a charge on reserve for using in DPS burst windows. 

Letting Hekili be configurable so it provides good all-purpose recommendations but lets us maintain charges in reserve would help optimize those DPS burst windows - for both TG and FR. Basically please give Havoc the same feature Vengeance does :)

**Comment by Hekili** [comment]
I'll consider it; there is a big difference between Vengeance's use of Infernal Strike and Havoc's use of Fel Rush and Vengeful Retreat.  I changed the way the settings work for Havoc with regard to those abilities because if you take the relevant talents but aren't pushing those buttons, you're going to do extremely poorly.

**Comment by pdrayton** [comment]
Understood, and thanks for considering. Unlike FR and VR, the reason why I think keeping a charge in reserve for FR and TG is very "safe" wrt how much damage you would do versus how much you would do with "full send" is that if one talents into 2 charges, and always keeps one on cooldown/recharging, the "net loss" of sitting on a TG or a FR is one use of the ability across an encounter. That weighed against having it up to respond to specific scenarios which could include critical DPS windows is pretty good tradeoff IMO.

**Comment by Hekili** [comment]
That's a pretty fair argument.

**Comment by Hekili** [comment]
I'm just going to modify the entry for Essence Break such that the Momentum requirement is ignored if both FR and VR are disabled and the Tactical Retreat requirement is ignored if VR is disabled.  That will function for scenarios where the abilities are moved to a toggle (cooldowns, interrupts, custom) or if they're just flat-out disabled.

**Comment by pdrayton** [comment]
That is a fantastic solution to not having "don't recommend movement" but does still leave the issue with wanting to save 1 charge of Fel Rush and/or 1 charge of Throw Glaive. TBH the reason I created this suggestion for reserving charges, and replied on the other issue about "Essence Break is not ever suggested" was because I was hoping to get both (separate) capabilities :)

If it would help I can PR the fix to add the 'reserve N charges", for you to review? I'm familiar w. Lua and the Hekili code.

**Comment by pdrayton** [comment]
Submitting a PR that adds the ability to reserve N charges of Throw Glaive and Fel Rush - the feature requested in this [REC]. LMKWYT
