### ISSUE TITLE
[BUG] Target counting issue for Fury Warrior

### ISSUE THREAD

**Issue by kingreboot** [Hekili/hekili#2443]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon will sometime get stuck (mostly seen when changing talents/specs) on my warrior where the addon will not count more then one target and will not think I am in melee range until I am basically directly under the mob I am targeting. I can Fix this with a quick reload. I will also mention that I don't change talents with normal loadouts but instead using BtWLoadouts Addon (https://www.curseforge.com/wow/addons/btwloadouts). 

### How to Reproduce

unsure. Change specs while as a warrior?

### Player Information (Link)

https://pastebin.com/7c1zxnf9

### Error Messages (Link)

No bugs were reported 

### Additional Information

Snapshot: https://pastebin.com/qCg5Sh5R

### Contact Information

Kingreboot#5331

**Comment by Hekili** [comment]
Was the snapshot taken when you were having this issue?

**Comment by kingreboot** [comment]
Yes

**Comment by kingreboot** [comment]
and I under stand why you changed the name to target counting, but I was also have a rang issue. It was recommending charge and telling me I was out of range even though I was in melee range hitting melee range spells.

**Comment by Hekili** [comment]
Do you have multiple nameplates showing? Or only your target's nameplate?

**Comment by kingreboot** [comment]
all nameplates showing and damaged enemies are selected. Even with forcing the addon to count other targets with an Aoe ability does not seems to work. Will note that I use Leatrix to only show Nameplates while in combat, but this has not been an issue in the past and I can confirmed when this issue has happen, that the nameplates were showing.

**Comment by Hekili** [comment]
Can you update to v10.0.19a, then post a new snapshot at the cleave dummies and add a screenshot as well? Thanks.

**Comment by kingreboot** [comment]
ok

**Comment by kingreboot** [comment]
only issue I have is trying to force the bug has been not easy. Its happen a good amount, but recreating it seems very random.

**Comment by kingreboot** [comment]
Could be related to joining a group. Most of my examples happen in M+ groups, but the one above I notice while in a World boss group and I have seen this happen in my raid groups. I don't think I have experienced this while solo

**Comment by kingreboot** [comment]
I have now tried few combination to try to trigger the issue, but nothing has seemed to work. I will try to get a screenshot when I next notice it.

**Comment by kingreboot** [comment]
![WoWScrnShot_022723_145733](https://user-images.githubusercontent.com/24847320/221708330-689b5897-ac24-4b95-b442-3e527a58437e.jpg)

**Comment by kingreboot** [comment]
![WoWScrnShot_022723_145730](https://user-images.githubusercontent.com/24847320/221708395-394b8963-c4e7-4af1-8d6e-49c73870d08d.jpg)

**Comment by kingreboot** [comment]
First example shows not counting targets and second example is showing charge in melee range

**Comment by Wyste** [comment]
The first picture recommends Rampage while you have 2 stacks of Whirlwind still up (and 80+ rage), which would cleave it to everything; I imagine that's the correct recommendation based on target count.

The second picture showing Charge... well that probably is because charge is recommended at distance > 5, but charge needs a minimum distance of 8.
Charge's Conditions: `time <= 0.5 | movement.distance > 5`

@Hekili that probably needs changed to be `>7` I imagine.
![image](https://user-images.githubusercontent.com/5103286/221710316-d3fc95ed-9583-466c-a874-7b49dfe5441c.png)

**Comment by Wyste** [comment]
Also, if you want to be 100% sure what Hekili is counting as it's targets, you can turn on an option which places a number in the bottom right hand corner of the recommendations:
![image](https://user-images.githubusercontent.com/5103286/221710945-6436ffe8-e875-46ca-baf7-9d05bffa0f8e.png)


Example: 5 target dummies:
![image](https://user-images.githubusercontent.com/5103286/221711038-a37d926e-6cce-47f4-af59-6adcf580cb18.png)

**Comment by kingreboot** [comment]
All I know is if I reload my UI, the recommendation start displaying the right spells again and target count starts working again

**Comment by Hekili** [comment]
I need the snapshot *and* the screenshot, as noted above.

**Comment by kingreboot** [comment]
I will try to get snapshot, but the first snapshot I sent had the same issue as screenshot.

**Comment by kingreboot** [comment]
https://pastebin.com/E7t1aJdc 

in Arms spec in raid

**Comment by chevyn11** [comment]
that snapshot seems to be from when you are out of combat with no targets. What is the expected suggestion?

**Comment by kingreboot** [comment]
I thought I got the pause to go off before the pull was over. I was having the same issue where it was not counting more then one mob and recommending charge randomly and while in melee range

**Comment by chevyn11** [comment]
I see, I usually disable charge on my warrior so its never suggested... maybe that will help. 
It's not an out of the box solution for everyone though.

**Comment by kingreboot** [comment]
I leave charge on as it usually not in the way when in range and I like using it when I have to leave range of mob/boss for a mechanic and to know at what point I am in range to use charge to get back in

**Comment by Hekili** [comment]
I wonder if this is related to the new implied targeting stuff (in WoW, not the addon).  Have you changed those settings at all?

**Comment by kingreboot** [comment]
no, unless another addon messes with it, but I can't think of other addons that would mess with it. If it part of the new implied targeting stuff, then it would have to be something that changes based on something because a reload fixes the issue.

**Comment by kingreboot** [comment]
new snapshot while in raid, near alot of trash

https://pastebin.com/Dr6XgrgT

**Comment by Hekili** [comment]
This is likely related to other target auditing issues that cropped up recently.  If it is not resolved in 1.0.23, please add a new snapshot with the latest version.  Thanks!

**Comment by kingreboot** [comment]
Thanks, will test with newest build and will report if it crops up. Hopefully it does not

**Comment by kingreboot** [comment]
I was not able to stop and pause to to grab a snapshot/screenshot as it was during a high key and I just needed the addon to work so I reloaded, but it happened again on the current build. Well current of last night, I think v10.0.5-1.0.23b

**Comment by kingreboot** [comment]
Will point out  that it's always happens after I swapped specs/gear/talents/loading in and never randomly during combat or while going in and out of combat.

**Comment by Hekili** [comment]
I can't investigate without the snapshot.

**Comment by kingreboot** [comment]
I know, just letting you know that the problem is still there, will try to get a snapshot when I can

**Comment by Hekili** [comment]
For target counting to break down, I'd expect there to be an error.  If it happens during an update thread, the snapshot would include the message.  If it's happening at another time, BugSack/BugGrabber would capture error messages that you can forward as well.

**Comment by kingreboot** [comment]
That would make sense, but all I have to go on is what I been experiencing. I have checked for errors and I get none. I wish it was easy to recreate or not happen in moments where I just need the addon to work. I tried my hardest to try to trigger it, but no luck

**Comment by kingreboot** [comment]
https://pastebin.com/sZvLvVLZ

**Comment by kingreboot** [comment]
during the big pack at the start of vault (current M+ vault)

**Comment by Hekili** [comment]
By default, snapshotting also creates a screenshot.  Do you have the screenshot from when you took that snapshot?

**Comment by kingreboot** [comment]
oh let me check, did not know it did that

**Comment by kingreboot** [comment]
it was a pause, then I got the snapshot. Not sure how that works (for screenshotting that is) but let me check

**Comment by kingreboot** [comment]
![WoWScrnShot_031523_162051](https://user-images.githubusercontent.com/24847320/225776653-2e39debc-2ca4-40fc-8b25-a773b80e072e.jpg)

**Comment by Hekili** [comment]
Please don't use the alpha for 10.0.7 on live.  It probably doesn't impact Warrior since there aren't any real changes, but it might.

In your screenshot, with the exception of your targets, the other enemies look like they might not be within 8 yards.  Your `nameplateRange` setting is set to 8.  I'm going to post a new 10.0.5 version that records more targeting data, so I might need to see if you can get another snapshot afterward.

**Comment by kingreboot** [comment]
ok, I will swap back to the 10.0.5 version, also this just happens to be where the snapshot was taken, I was moving in and out of the pack to see if anything was changing, so yes I might have been out of range in that pack, but not always. Also I have detect with damage selected and it was not working. Unless I misunderstand that option and nameplates over rides that option.

**Comment by Hekili** [comment]
Understood.  Trust me, I don't enjoy sending you after multiple snapshots, it's just most helpful to come away with an example that is explicitly clear that the targets should've been detected.  8 yards isn't that far and your snapshot makes it questionable.  If you snapshot again, getting the snapshot and screenshot when you're literally inside the enemy hitboxes would be really helpful.

Does this issue tend to happen with these specific enemies?

If you change your Nameplate Range to 10 yards, do you run into this issue?

**Comment by kingreboot** [comment]
I just changed the range (14 I think? not at computer) to test to see if that is the issues. Had it happen to me a day ago during a 20 NO, sadly did not grab the snapshot. I don't think it has todo with enemies types as I have seen it happen in most of the M+ this season. I will do a few keys tomorrow to fill my vault and will look out to get a snapshot

**Comment by kingreboot** [comment]
![WoWScrnShot_032223_185053](https://user-images.githubusercontent.com/24847320/227078692-dd3a3c5c-aa2e-4551-b78e-9b6c5dbdf121.jpg)
https://pastebin.com/NnNNaeRy

**Comment by Hekili** [comment]
Thanks; I'm making a couple of changes that may help.

1. Enemies filtered due to being out of nameplateRange will be filtered based on their minimum range, not their maximum range.  This means if an enemy is actually 12.5 yards away and `GetRange` says they are 10 - 15 yards away, they'll be excluded only if the lower number is greater than your range.

2. I'm adding another quick fix so that when enemies are filtered by range, it will show their detected range vs. your nameplateRange in the snapshot for diagnostic purposes.

The first might solve your issue entirely; the second will make it easier to diagnose the range vs. your filter settings.  I think we're close to resolution of this issue.

**Comment by kingreboot** [comment]
great

**Comment by Hekili** [comment]
Please give 1.0.1 a try, even if just on target dummies.  Same deal -- if you can send snapshot/screenshots in pairs if you still have trouble, I'll review further.

**Comment by kingreboot** [comment]
Will look out for it, but hoping to not see issues to report anymore

**Comment by kingreboot** [comment]
So I did not get a chance to get this snapshot, but the count issue is no longer there, but my other issue of the addon randomly showing charge when I am in range is still there. Just like the counting issue, a reload fixes it

**Comment by Hekili** [comment]
Ok, open a separate issue for charge if/when you get a snapshot for it.  Thanks!

**Comment by kingreboot** [comment]
ok
