### ISSUE TITLE
[BUG] Error when loading after v10.0.5-1.0.19 /LibRangeCheck-2.0.lua

### ISSUE THREAD

**Issue by PopsGG** [Hekili/hekili#2444]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After upgrading to v10.0.5-1.0.19 BugSack is reporting errors on UI load.

8x Hekili/embeds.xml:18 Error loading Hekili/Libs/LibRangeCheck-2.0-100217/LibRangeCheck-2.0.lua
8x Interface\FrameXML\Bindings.xml:1 Hekili/embeds.xml:18 Error loading Hekili/Libs/LibRangeCheck-2.0/LibRangeCheck-2.0.lua

### How to Reproduce

Update to v10.0.5-1.0.19 
Load the game

### Player Information (Link)

https://pastebin.com/y6MkwbxH

### Error Messages (Link)

https://pastebin.com/Emua2p8e

### Additional Information

Error paste bin, is the same strings shown in the description.

### Contact Information

Gurk#4116

**Comment by Maibenrai** [comment]
I fixed by moving file 
\Hekili\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua
to
\Hekili\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua

**Comment by Beatusvir** [comment]
> I fixed by moving file \Hekili\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua to \Hekili\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua

Thanks @Maibenrai, this worked for me as well.

**Comment by Hekili** [comment]
Fixed in 1.0.19a -- update and respond back if you find otherwise.
