### ISSUE TITLE
[BUG] .lua-Errors after Update - v10.0.5-1.0.19

### ISSUE THREAD

**Issue by JEt22281** [Hekili/hekili#2445]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Many .lua-Errors after installing new Version today.

**1.**
Message: Interface/AddOns/Hekili/State.lua:27: Cannot find a library instance of "LibRangeCheck-2.0".
Time: Mon Feb 27 08:08:24 2023
Count: 1
Stack: Interface/AddOns/Hekili/State.lua:27: Cannot find a library instance of "LibRangeCheck-2.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/ArkInventory/Libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Hekili/State.lua"]:27: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibRangeCheck-2.0"."

**2.**
Message: Interface/AddOns/Hekili/Classes.lua:24: attempt to index field 'metatables' (a nil value)
Time: Mon Feb 27 08:08:24 2023
Count: 1
Stack: Interface/AddOns/Hekili/Classes.lua:24: attempt to index field 'metatables' (a nil value)
[string "@Interface/AddOns/Hekili/Classes.lua"]:24: in main chunk

Locals: addon = "Hekili"
ns = <table> {
 FindPlayerAuraByID = <function> defined @Interface/AddOns/Hekili/Utils.lua:516
 getLocalClass = <function> defined @Interface/AddOns/Hekili/Constants.lua:9
 WipeCovenantCache = <function> defined @Interface/AddOns/Hekili/Utils.lua:812
 auras = <table> {
 }
 IsTimer = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 getSpecializationKey = <function> defined @Interface/AddOns/Hekili/Constants.lua:209
 frameProfile = <table> {
 }
 Localize = <table> {
 }
 IsCovenantSpell = <function> defined @Interface/AddOns/Hekili/Utils.lua:787
 FindUnitDebuffByID = <function> defined @Interface/AddOns/Hekili/Utils.lua:549
 GetTexString = <function> defined @Interface/AddOns/Hekili/Utils.lua:852
 ClearTimer = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 queue = <table> {
 }
 AddonName = "Hekili"
 SetTimer = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 BigLibTimer6 = <table> {
 }
 Mark = <function> defined @Interface/AddOns/Hekili/Utils.lua:909
 cpuProfile = <table> {
 }
 GroupMembers = <function> defined @Interface/AddOns/Hekili/Utils.lua:263
 safeMax = <function> defined @Interface/AddOns/Hekili/Utils.lua:243
 IsItemDisabled = <function> defined @Interface/AddOns/Hekili/Utils.lua:678
 targets = <table> {
 }
 IsActiveSpell = <function> defined @Interface/AddOns/Hekili/Utils.lua:573
 safeAbs = <function> defined @Interface/AddOns/Hekili/Utils.lua:255
 ClearMarks = <function> defined @Interface/AddOns/Hekili/Utils.lua:927
 CreateTable = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 RecycleTable = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 escapeMagic = <function> defined @Interface/AddOns/Hekili/Utils.lua:110
 FindRaidBuffByID = <function> defined @Interface/AddOns/Hekili/Utils.lua:293
 SpaceOut = <function> defined @Interface/AddOns/Hekili/Utils.lua:54
 roundUp = <function> defined @Interface/AddOns/Hekili/Utils.lua:139
 getClassID = <function> defined @Interface/AddOns/Hekili/Constants.lua:36
 getInverseDirection = <function> defined @Interface/AddOns/Hekili/Constants.lua:22
 fsub = <function> defined @Interface/AddOns/Hekili/Utils.lua:105
 Patrons = "Current Status

All specializations are currently supported, though healer priorities are experimental and focused on rotational DPS only.

If you find odd recommendations or other issues, please follow the Issue Reporting link below and submit all the necessary information to have your issue investigated.

Please do not submit tickets for routine priority updates (i.e., from SimulationCraft).  I will routinely update those when they are published.  Thanks!"
 IsInventoryItemDisabled = <function> defined @Interface/AddOns/Hekili/Utils.lua:690
 FindStringInSpellTooltip = <function> defined @Interface/AddOns/Hekili/Utils.lua:643
 ReplaceTimer = <function> defined @Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:22
 round = <function> defined @Interface/AddOns/Hekili/Utils.lua:132
 FrameStratas = <table> {
 }
 formatValue = <function> defined @Interface/AddOns/Hekili/Formatting.lua:774
 GetResourceKey = <function> defined @Interface/AddOns/Hekili/Constants.lua:83
 FindStringInItemTooltip = <function> defined @Interface/AddOns/Hekili/Utils.lua:648
 ResourceRegenerates = <function> defined @Interface/AddOns/Hekili/Constants.lua:95
 GetResourceID = <function> defined @Interface/AddOns/Hekili/Constants.lua:78
 GetResourceInfo = <function> defined @Interface/AddOns/Hek

### How to Reproduce

1. Logging in to Character
2. /hekili will not work, cause of .lua-Errors

### Player Information (Link)

https://doesntworkcauseofluaerrors.de

### Error Messages (Link)

https://seedescribeerrorformessage

**Comment by Hekili** [comment]
The silly ways people fill in boxes sometimes.

This should be resolved in 1.0.19a.
