### ISSUE TITLE
[Help] I don't have any possibility to open options

### ISSUE THREAD

**Issue by th4lioN** [Hekili/hekili#2446]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I downloaded and installed the latest version of Hekili Priority Helper with CurseForge.
The minmap button is there, but I can't open the options by rightclicking it or typing "/hekili" in chat. In the game options Hekili doesn't show up neither like the screenshot proofs.

![Hekili-problem](https://user-images.githubusercontent.com/126482266/221575385-515fe6ee-df6d-482c-8b21-4c3698c793d4.jpg)

### How to Reproduce

It's the same problem with every character.

### Player Information (Link)

I can't.

### Error Messages (Link)

There isn't any error message

**Comment by ElMorz** [comment]
Same issue

**Comment by Hekili** [comment]
Update to 1.0.19a and re-report if you're still having an issue.

If it still will not open and you can't see error messages, install BugSack and BugGrabber to reconfirm that those addons don't capture any errors.  Thanks!
