### ISSUE TITLE
[REC] Paladin Addons does not guide me to keep the dusk and dawn buff

### ISSUE THREAD

**Issue by RedfieldXXX** [Hekili/hekili#2448]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

addons used to guide me to gain 5 holy power thus to keep my dawn buff, but after upgraded to new version in Feb 28th it suddenly keep letting me use my ability when I got 3 holy power, I can't maintain my dawn buff

### How to Reproduce

1

### Snapshot (Link)

1

### Contact Information

harry.canzhang@outlook.com

**Comment by RedfieldXXX** [comment]
need help lol

**Comment by Hekili** [comment]
Sorry, you'll need to fill out the ticket properly.
