### ISSUE TITLE
Not loading priority image for Havoc Dh

### ISSUE THREAD

**Issue by joshuadf21** [Hekili/hekili#2449]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

there are 2 initial talents that will not show image for on opening or after they have cooled down.  depending on talent spec i am running. 

### How to Reproduce

load as havoc DH using raid single target build or AOE mythic throw glaive talent

![Screenshot_20230228_033759](https://user-images.githubusercontent.com/126618196/221975966-1ca02627-9973-45a6-b499-16c3e2aed9cc.png)

### Snapshot (Link)

https://pastebin.com/H51NDMn9

**Comment by Hekili** [comment]
> there are 2 initial talents that will not show image for on opening or after they have cooled down. depending on talent spec i am running.

I don't know what this means.  Can you explain it differently?  What initial talents aren't showing?  (If I have to guess, I would be your Cooldowns are toggled off.  See `/hekili` > Toggles > Show Cooldowns.)

When you respond, please provide a complete snapshot.  You have to CTRL+A then CTRL+C in the box, so it captures all the lines and not just the first one.  Thanks!
