### ISSUE TITLE
Arcane Mage - clearcasting with pvp talent

### ISSUE THREAD

**Issue by wow1989** [Hekili/hekili#245]
currently not recognizing clearcasting procs with pvp talent arcane empowerment

additionally, is there a recognize when i'm moving toggle? always recommending casted spells while i'm moving, would love to fix this.

**Comment by Hekili** [comment]
You could certainly write a priority that only shows instant casts while moving but it wouldn't be optimal for DPS.  The solution is, most often, to stop moving so you can cast.

I'll look at the PvP talent.

**Comment by wow1989** [comment]
Not really true though.

Moving with 0 arcane charges - Should recommend arcane barrage 

Crucible of flame
Barrier
Charged up (situational)

There are a lot of things it could recommend that would certainly lead to a net DPS gain.

**Comment by Hekili** [comment]
If using those instants werr more performant than the default priority, they would be the default priority. The real optimal behavior is to minimize movement, but you can still make a custom priority if you want recommendations to be different when moving.
