### ISSUE TITLE
Feral / combo points spenders

### ISSUE THREAD

**Issue by Nikurd** [Hekili/hekili#2450]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi, I am not sure if this is only for me but for my Feral druid, I expect the addon to recommend a combo finisher when I have 5 combo points. However the addon recommended me to use it at 4 combo points. Everything was fine but last 1/2 week I can this change. Not sure if this is because of my gear or stats but I believe this is something odd.
![Feral](https://user-images.githubusercontent.com/126654019/222074072-00ce7665-369d-4016-8fcb-517824a28252.PNG)

### How to Reproduce

1. Enter game as Feral Druid
2. Use Rake
3. Use Thrash
4. Tiger's Fury
5. It recommends to use finisher at 4 combo points. 

### Snapshot (Link)

https://pastebin.com/2iMbfBfY

**Comment by chevyn11** [comment]
This is normal based on the new feral APL, its optimal to use at >3 combo points instead of always on 5: https://github.com/Hekili/hekili/issues/2406

**Comment by Nikurd** [comment]
Thanks for the replay, I missed that threat. I was just confused that with wowIanalyze and raidbots I have different rotation. I am not sure for what APL stands, can you extend this?

**Comment by Hekili** [comment]
The feral sim uses finishers at 4+ CP for a couple of weeks now. The addon also has some logic related to funneling that is not in SimC yet. But overall, sim behavior and addon behavior are in agreement to my knowledge. 

You can see this by simming your character and looking at the sample output.
