### ISSUE TITLE
[BUG] black corner on some spell icons

### ISSUE THREAD

**Issue by orblazer** [Hekili/hekili#2452]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Some spells have black corner when is unzoomed (first and last in picture bellow).
**NOTE** : This look append on all spell when black cooldown is on top of spell.

![Screenshot_20230302_004037](https://user-images.githubusercontent.com/1344792/222292301-0b223b6b-5fc3-4494-9aaf-27abd93b1be9.png)

### How to Reproduce

1. Enter game
2. Open Hekili config
3. Set `Icon Zoom` to 0 in "Displays" section
4. Look icons

### Player Information (Link)

https://pastebin.com/VJhTzckq

### Error Messages (Link)

none

**Comment by Hekili** [comment]
I'm not able to replicate this issue directly.  I suspect something else is at least partially skinning my addon's icons for you.  Does this occur with no other addons loaded?

**Comment by orblazer** [comment]
Hello,
Yes this append with only that active, but the initial case is look like appear only on few icons, BUT i already have the same issue for "overlay" when delay is active for spell.

**Comment by Hekili** [comment]
For clarity:
1. Can you produce the same screenshot with no other addons turned on?
2. What exact settings are you referencing when you say "'overlay' when delay is active for spell"?  Are you talking about `Display > Delays > Indicator > Show Icon (Color)` or something else?

**Comment by orblazer** [comment]
Yes, the screen bellow is with only hekili addon enable and with all "module" disabled.

I think this is due because its designed for square so the corner is not cropped.
And for render the spells like hotbar, i think the icons need to be rounded crops and have border over the icon

### Render
**Case 1 (Corner bug for "overlay")** :
![Screenshot_20230315_231837](https://user-images.githubusercontent.com/1344792/225456539-85175fb6-12a3-4674-bb2f-3cf334c59e9f.png)
**Case 2 (corner on some spell)** :
![Screenshot_20230315_232039](https://user-images.githubusercontent.com/1344792/225456542-9c21f2fa-d063-4f19-8a97-cf3fd4d4252b.png)

### Exported style (primary)
```
Hekili:LA12Yjooq0VOHYyGSjpoHIzd1MbyI8wZS7dQISTaRkYsEKLbCEiF7B3sYG5Yoj1Ufugz529LZ50TGoKMqj5mlNUiokEu0OHtgepk(2H3qj22koLuBBLWpvSwPMLJMVYikzMwCPLz2WT14Yw6IikzTwzjIxb3nmMs4kwQKNttPeMkRqBOK7xMKS8Rpn)3FaENmTe2lbm29n2DDK76y8Qn4qFkS8ptEC(Iz(9OKVyeV(2ZFRHLByw2BpNaoCpMeWZ4Lv6DCtjhmm5yEC)jjiuImPyJIsMoBrYSNojyjpmF6FCiITy28lI7Pvxipi)SH34J6LfA0GBhE3nr)2DUco6qbdbixuxjzTR0cmCjlxrjPncPDUcDL2KZnU0XWLhtDdtTH3Vwt7iqwQqkSToWuYQloZOmDzkZ6xDrsEwYrQBQQm86A08uPq9cUyTypp3HPWn1vCWVq5ngSWi2uyvO9lggffS8(J7I274I4XoAZdJHcVdlt9vmQ2kezVeCh6m7bOvO2aRAQT6YpKQQx9VtKBlcBd08NIhpbu7Ej(39pBcK6VQbxJKQQPCEMwb5Wehp)PBHnFHZR(mu6z2NywHgZREAoGOGD3Yt0ucz6tZMTaYEdRK)iFlWHa2qjfIC(YsLy6uhvWQa3OQpJRoT76Fx82x3g9Fw3EvjX5qj44ns9UlevDKsoFnRrAp1vrdUBsOlaxGASbJIpspL6Cu42y1zSAB)eQa0osu)a3ydOiXIfeL84YVhm1nutya6aarkjmTjW0JaEtVEDn3(dhhYLBBet1AzUENYnQcXv3OJdyBDfldlh0(cUl(98ZF5qToSmeTWCt)DwuI0Mku5GxCS6Pu57JZxLE7cjmJOlQ8kgGg8VHWG3COIK4WqakD34bZhVCRPVFsG69XD2)fNS6Zgbt(2ZlygdidCTqJ)vsUSvAJ9V9DtdUPVVU65g9E8zfFVPROlxULBmqteSHdTa2h0oR4gHgMhneilfOvoE6vxp(db6eBYr(jJz1MZB82Fng(yc0go2jhA0BDVRF0BYSF8)4uowUJC89W7FNo5tuXUjR89wU6AJncvrqBd(BROweoKaNjKVfmXx3UgruwbYwjcTK8gM0ptJLHZ0W1mT)hOFTeg0L5PGQTUxnC(coXgNX9vDJY6rnMChIwGmysNzjU)pHZyMSQG5wzpSPZRvFmVo8d7t7LZaSUp0)j
```

**Comment by Hekili** [comment]
Hm, as far as I can tell, it's an issue with those textures themselves.  Ice Strike has black corners if I pick it up from an action bar, too.  I could work around it by masking the corners, but I don't know if that'll have downstream impacts for Masque or other addons.
