### ISSUE TITLE
Paladin / Protection - Blessing of Dawn and Dusk priority

### ISSUE THREAD

**Issue by GHSTSHP** [Hekili/hekili#2455]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm curious if it's possible to add blessing of dawn and dusk to the simc priority. Admittedly, I am not smart enough to edit that data in any meaningful or accurate way.

Thank you!

### How to Reproduce

I don't see the spell in the priority list and the default priority never seems to want me to bank five holy power.

### Snapshot (Link)

Protection Paladin; Interrupts - N/A build: v10.0.5-1.0.20 level: 70 (70) class: PALADIN spec: protection  talents: ardent_defender = 1/1     aspiration_of_divinity = 2/2     auras_of_the_resolute = 1/1     avengers_shield = 1/1     avenging_wrath = 1/1     avenging_wrath_might = 1/1     bastion_of_light = 1/1     blessed_hammer = 1/1     blessing_of_freedom = 1/1     blessing_of_protection = 1/1     blessing_of_sacrifice = 1/1     bulwark_of_order = 2/2     bulwark_of_righteous_fury = 1/1     cavalier = 1/1     consecration_in_flame = 1/1     crusaders_judgment = 1/1     crusaders_resolve = 1/1     divine_resonance = 1/1     divine_steed = 1/1     divine_toll = 1/1     eye_of_tyr = 1/1     ferren_marcuss_fervor = 2/2     fist_of_justice = 2/2     golden_path = 1/1     grand_crusader = 1/1     greater_judgment = 1/1     guardian_of_ancient_kings = 1/1     hallowed_ground = 1/1     hammer_of_wrath = 1/1     holy_aegis = 2/2     holy_shield = 1/1     incandescence = 1/1     judgment_of_light = 1/1     lay_on_hands = 1/1     moment_of_glory = 1/1     of_dusk_and_dawn = 1/1     rebuke = 1/1     redoubt = 1/1     relentless_inquisitor = 1/1     righteous_protector = 2/2     sacrifice_of_the_just = 1/1     sanctified_wrath = 1/1     seal_of_might = 2/2     seal_of_order = 1/1     seal_of_reprisal = 1/2     seal_of_the_crusader = 2/2     seasoned_warhorse = 1/1     shining_light = 1/1     soaring_shield = 1/1     strength_of_conviction = 2/2     tyrs_enforcer = 2/2     unbreakable_spirit = 1/1     zealots_paragon = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: decoration_of_flame = 1     tier29 = 4  gear: alacritous_alchemist_stone = 1     broodsworn_legionnaires_pavise = 1     decoration_of_flame = 1     elemental_lariat = 1     frostfire_legguards_of_preparation = 1     goldsteel_bindings = 1     illusion_breakers_waistguard = 1     seal_of_filial_duty = 1     shield = 1     signet_of_titanic_insight = 1     strike_twice = 1     tabard_of_the_lightbringer = 1     tier29 = 4     undisputed_champions_shirt = 1     valkyra_protector_greatboots = 1     vibrant_wildercloth_shawl = 1     virtuous_silver_breastplate = 1     virtuous_silver_gauntlets = 1     virtuous_silver_heaume = 1     virtuous_silver_pauldrons = 1  legendaries: none  itemIDs: 109878, 136772, 190523, 191492, 192999, 193001, 193511, 193650, 193700, 194299, 195520, 195526, 200414, 200416, 200417, 200419, 52252, 98082  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Protection Paladin     petbased = false     potion = phantom_fire     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     ds_damage = 100     goak_damage = 50     wog_health = 0  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = false      essences = true [overridden]     interrupts = true [separate]     mode = automatic      potions = false   keybinds:      ardent_defender           = N3  [01]     avengers_shield           = R   [05]     avenging_wrath            = N1  [05]     bastion_of_light          = N4  [05]     blessed_hammer            = T   [05]     blessing_of_freedom       = N5  [06]     blessing_of_protection    = N+  [01]     blessing_of_sacrifice     = N8  [06]     cleanse_toxins            = 6   [06]     consecration              = Q   [05]     decoration_of_flame       = S   [03]     divine_shield             = N0  [05]     divine_steed              = N2  [06]     divine_toll               = 9   [06]     eye_of_tyr                = 8   [06]     flash_of_light            = 1   [01]     guardian_of_ancient_kings = N6  [01]     hammer_of_justice         = 7   [06]     hammer_of_wrath           = E   [05]     hand_of_reckoning         = A   [03]     healthstone               = 2   [01]     intercession              = N-  [06]     judgment                  = W   [05]     lay_on_hands              = N7  [05]     moment_of_glory           = N9  [01]     rebuke                    = 0   [06]     shield_of_the_righteous   = F   [03]     will_to_survive           = 5   [01]     word_of_glory             = D   [03]  warnings: [#1] Auditor removed an aura 383843 from Creature-0-4232-2444-2632-193385-000002BA2E after exiting combat. [#2] Auditor removed an aura 31935 from Creature-0-4232-2444-2632-193385-000002BA2E after exiting combat. [#3] Auditor removed an aura 385723 from Creature-0-4232-2444-2632-193385-000002BA2E after exiting combat. [#4] Auditor removed an aura 196941 from Creature-0-4232-2444-2632-193385-000002BA2E after exiting combat. [#5] Auditor removed an aura 197277 from Creature-0-4232-2444-2632-193385-000002BA2E after exiting combat. [#6] Auditor removed an aura 383843 from Creature-0-4232-2444-2632-193145-000002BD30 after exiting combat. [#7] Auditor removed an aura 31935 from Creature-0-4232-2444-2632-193145-000002BD30 after exiting combat. [#8] Auditor removed an aura 196941 from Creature-0-4232-2444-2632-193145-000002BD30 after exiting combat. [#9] Auditor removed an aura 197277 from Creature-0-4232-2444-2632-193145-000002BD30 after exiting combat. [#10] Auditor removed an aura 383843 from Creature-0-4232-2444-2632-193394-000002BAED after exiting combat. [#11] Auditor removed an aura 31935 from Creature-0-4232-2444-2632-193394-000002BAED after exiting combat. [#12] Auditor removed an aura 383843 from Creature-0-4232-2444-2632-194570-000082BDEC after exiting combat. [#13] Auditor removed an aura 383843 from Creature-0-4232-2444-2632-194570-000002BDEC after exiting combat. [#14] Auditor removed an aura 385723 from Creature-0-4232-2444-2632-194570-000002BDEC after exiting combat. [#15] Auditor removed an aura 204301 from Creature-0-4232-2444-2632-194570-000082BDEC after exiting combat. [#16] Auditor removed an aura 204301 from Creature-0-4232-2444-2632-194570-000002BDEC after exiting combat. [#17] Auditor removed an aura 196941 from Creature-0-4232-2444-2632-194570-000002BDEC after exiting combat. [#18] Auditor removed an aura 197277 from Creature-0-4232-2444-2632-194570-000002BDEC after exiting combat. [#19] Auditor removed an aura 204242 from Creature-0-4232-2444-2632-191553-000282BBE6 after exiting combat. [#20] Auditor removed an aura 204242 from Creature-0-4232-2444-2632-194570-000082BDEC after exiting combat. [#21] Auditor removed an aura 204242 from Creature-0-4232-2444-2632-194570-000002BDEC after exiting combat. [#22] Auditor removed an aura 383843 from Creature-0-4232-2444-2632-191553-000102BBE6 after exiting combat. [#23] Auditor removed an aura 196941 from Creature-0-4232-2444-2632-191553-000102BBE6 after exiting combat. [#24] Auditor removed an aura 197277 from Creature-0-4232-2444-2632-191553-000102BBE6 after exiting combat. [#25] Auditor removed an aura 383843 from Creature-0-4232-2444-2632-194624-000002BDFC after exiting combat. [#26] Auditor removed an aura 196941 from Creature-0-4232-2444-2632-194624-000002BDFC after exiting combat. [#27] Auditor removed an aura 197277 from Creature-0-4232-2444-2632-194624-000002BDFC after exiting combat. [#28] Auditor removed an aura 204242 from Creature-0-4232-2444-2632-195712-000002413A after exiting combat. [#29] Auditor removed an aura 204242 from Creature-0-4232-2444-2632-195712-00000240E7 after exiting combat. [#30] Auditor removed an aura 196941 from Creature-0-4232-2444-2632-195712-00000240E7 after exiting combat. [#31] Auditor removed an aura 196941 from Creature-0-4232-2444-2632-195712-000002413A after exiting combat. [#32] Auditor removed an aura 197277 from Creature-0-4232-2444-2632-195712-00000240E7 after exiting combat. [#33] Auditor removed an aura 197277 from Creature-0-4232-2444-2632-195712-000002413A after exiting combat. [#34] Auditor removed an aura 204301 from Creature-0-4232-2444-2632-195712-000002413A after exiting combat.   targets:     nameplate2   -  0 - Creature-0-4232-2444-2632-195762-000002C418 - 300.00 - 0 - Mossy Gulper    player_buffs:       465 - devotion_aura                            -   1 - 3600.00    368901 - *cliffside_wylderdrake                   -   1 - 3600.00    383169 - *lucky_horseshoe                         -   1 - 3600.00    186406 - *sign_of_the_critter                     -   1 - 3600.00    384235 - *vantus_rune_broodkeeper_diurna          -   1 - 297685.53    225788 - *sign_of_the_emissary                    -   1 - 3600.00    386984 - *wind_friend                             -   1 - 1640.66    297871 - *anglers_water_striders                  -   1 - 3600.00  player_debuffs:  target_auras:  target does not exist   New Recommendations for [ Interrupts ] requested at 22:18:33 ( 685575.99 ); using built-in ( Protection Paladin ) priority. *** START OF NEW DISPLAY: Interrupts ***  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: holy_power[ 0.00 / 5.00 ], mana[ 50000.00 / 50000.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Protection Paladin - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   devotion_aura ( precombat - 1 ) - ability disabled ( display )         Time spent on this action:  0.05ms         TimeData:Protection Paladin-precombat-1:devotion_aura:0.05:Ability Known, Enabled(0.05)                  2.   lights_judgment ( precombat - 2 ) - ability unknown         Time spent on this action:  0.30ms         TimeData:Protection Paladin-precombat-2:lights_judgment:0.30:Ability Known, Enabled(0.30)                  3.   arcane_torrent ( precombat - 3 ) - ability unknown         Time spent on this action:  0.07ms         TimeData:Protection Paladin-precombat-3:arcane_torrent:0.07:Ability Known, Enabled(0.07)                  4.   consecration ( precombat - 4 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-precombat-4:consecration:0.03:Ability Known, Enabled(0.03)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Protection Paladin - precombat ].          Processing default action list [ Protection Paladin - default ].                  Current recommendation was NO ACTION at +10.00s.                  5.   rebuke ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Protection Paladin-default-1:rebuke:0.03:Ability Known, Enabled(0.03)                  6.   cleanse_toxins ( default - 2 ) - talent [ cleanse_toxins ] missing         Time spent on this action:  0.03ms         TimeData:Protection Paladin-default-2:cleanse_toxins:0.03:Ability Known, Enabled(0.03)                  7.   call_action_list:cooldowns ( default - 3 )         There is no criteria for cooldowns.         Action list (cooldowns) was found.         + cooldowns         Current recommendation was NO ACTION at +10.00s.                  8.   seraphim ( cooldowns - 1 ) - talent [ seraphim ] missing         Time spent on this action:  0.03ms         TimeData:Protection Paladin-cooldowns-1:seraphim:0.03:Ability Known, Enabled(0.03)                  9.   avenging_wrath ( cooldowns - 2 ) - ability disabled ( display )         Time spent on this action:  0.07ms         TimeData:Protection Paladin-cooldowns-2:avenging_wrath:0.07:Ability Known, Enabled(0.07)                  10.  avenging_wrath ( cooldowns - 3 ) - ability disabled ( display )         Time spent on this action:  0.07ms         TimeData:Protection Paladin-cooldowns-3:avenging_wrath:0.07:Ability Known, Enabled(0.07)                  11.  potion ( cooldowns - 4 ) - ability disabled ( toggle a )         Time spent on this action:  0.66ms         TimeData:Protection Paladin-cooldowns-4:potion:0.66:Ability Known, Enabled(0.66)                  12.  moment_of_glory ( cooldowns - 5 ) - ability disabled ( display )         Time spent on this action:  0.07ms         TimeData:Protection Paladin-cooldowns-5:moment_of_glory:0.07:Ability Known, Enabled(0.07)                  13.  holy_avenger ( cooldowns - 6 ) - talent [ holy_avenger ] missing         Time spent on this action:  0.06ms         TimeData:Protection Paladin-cooldowns-6:holy_avenger:0.06:Ability Known, Enabled(0.06)                  14.  bastion_of_light ( cooldowns - 7 ) - ability disabled ( display )         Time spent on this action:  0.07ms         TimeData:Protection Paladin-cooldowns-7:bastion_of_light:0.07:Ability Known, Enabled(0.07)         Exiting cooldowns with recommendation of NO ACTION at +10.00s.         Returned from list (cooldowns), current recommendation is NO ACTION (+10.00).         - cooldowns                  15.  call_action_list:mitigation ( default - 4 )         There is no criteria for mitigation.         Action list (mitigation) was found.         + mitigation         Current recommendation was NO ACTION at +10.00s.                  16.  shield_of_the_righteous ( mitigation - 1 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-mitigation-1:shield_of_the_righteous:0.03:Ability Known, Enabled(0.03)                  17.  word_of_glory ( mitigation - 2 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-mitigation-2:word_of_glory:0.03:Ability Known, Enabled(0.03)                  18.  guardian_of_ancient_kings ( mitigation - 3 ) - ability disabled ( toggle a )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-mitigation-3:guardian_of_ancient_kings:0.03:Ability Known, Enabled(0.03)                  19.  divine_shield ( mitigation - 4 ) - ability disabled ( toggle a )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-mitigation-4:divine_shield:0.03:Ability Known, Enabled(0.03)                  20.  ardent_defender ( mitigation - 5 ) - ability disabled ( toggle a )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-mitigation-5:ardent_defender:0.03:Ability Known, Enabled(0.03)                  21.  lay_on_hands ( mitigation - 6 ) - ability disabled ( toggle a )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-mitigation-6:lay_on_hands:0.03:Ability Known, Enabled(0.03)         Exiting mitigation with recommendation of NO ACTION at +10.00s.         Returned from list (mitigation), current recommendation is NO ACTION (+10.00).         - mitigation                  22.  call_action_list:trinkets ( default - 5 )         There is no criteria for trinkets.         Action list (trinkets) was found.         + trinkets         Current recommendation was NO ACTION at +10.00s.                  23.  variable ( trinkets - 1 )          - variable.trinket_1_sync will check this script entry ( Protection Paladin:trinkets:1 )         1         Time spent on this action:  0.04ms         TimeData:Protection Paladin-trinkets-1:variable:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02)                  24.  variable ( trinkets - 2 )          - variable.trinket_2_sync will check this script entry ( Protection Paladin:trinkets:2 )         1         Time spent on this action:  0.03ms         TimeData:Protection Paladin-trinkets-2:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  25.  variable ( trinkets - 3 )          - variable.trinket_priority will check this script entry ( Protection Paladin:trinkets:3 )         2         Time spent on this action:  0.03ms         TimeData:Protection Paladin-trinkets-3:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  26.  variable ( trinkets - 4 )          - variable.trinket_1_buffs will check this script entry ( Protection Paladin:trinkets:4 )         trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false]         Time spent on this action:  0.03ms         TimeData:Protection Paladin-trinkets-4:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  27.  variable ( trinkets - 5 )          - variable.trinket_2_buffs will check this script entry ( Protection Paladin:trinkets:5 )         trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false]         Time spent on this action:  0.03ms         TimeData:Protection Paladin-trinkets-5:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  28.  trinket1 ( trinkets - 6 )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-trinkets-6:trinket1:0.03:Ability Known, Enabled(0.03)                  Substituting decoration_of_flame for Trinket #2 action; it is otherwise not included in the priority.         29.  decoration_of_flame ( trinkets - 7 ) - ability disabled ( display )         Time spent on this action:  0.31ms         TimeData:Protection Paladin-trinkets-7:decoration_of_flame:0.31:Ability Known, Enabled(0.31)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  30.  trinket1 ( trinkets - 8 )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-trinkets-8:trinket1:0.03:Ability Known, Enabled(0.03)                  Substituting decoration_of_flame for Trinket #2 action; it is otherwise not included in the priority.         31.  decoration_of_flame ( trinkets - 9 ) - ability disabled ( display )         Time spent on this action:  0.28ms         TimeData:Protection Paladin-trinkets-9:decoration_of_flame:0.28:Ability Known, Enabled(0.28)                  32.  use_items ( trinkets - 10 )         There is no criteria for Use Items.         + trinkets, items         Current recommendation was NO ACTION at +10.00s.         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items         Exiting trinkets with recommendation of NO ACTION at +10.00s.         Returned from list (trinkets), current recommendation is NO ACTION (+10.00).         - trinkets                  33.  call_action_list:standard ( default - 6 )         There is no criteria for standard.         Action list (standard) was found.         + standard         Current recommendation was NO ACTION at +10.00s.                  34.  shield_of_the_righteous ( standard - 1 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-1:shield_of_the_righteous:0.03:Ability Known, Enabled(0.03)                  35.  shield_of_the_righteous ( standard - 2 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-2:shield_of_the_righteous:0.03:Ability Known, Enabled(0.03)                  36.  avengers_shield ( standard - 3 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-3:avengers_shield:0.03:Ability Known, Enabled(0.03)                  37.  hammer_of_wrath ( standard - 4 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-4:hammer_of_wrath:0.03:Ability Known, Enabled(0.03)                  38.  judgment ( standard - 5 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-5:judgment:0.03:Ability Known, Enabled(0.03)                  39.  divine_toll ( standard - 6 ) - ability disabled ( display )         Time spent on this action:  0.07ms         TimeData:Protection Paladin-standard-6:divine_toll:0.07:Ability Known, Enabled(0.07)                  40.  avengers_shield ( standard - 7 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-7:avengers_shield:0.03:Ability Known, Enabled(0.03)                  41.  hammer_of_wrath ( standard - 8 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-8:hammer_of_wrath:0.03:Ability Known, Enabled(0.03)                  42.  judgment ( standard - 9 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-9:judgment:0.03:Ability Known, Enabled(0.03)                  43.  consecration ( standard - 10 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-10:consecration:0.03:Ability Known, Enabled(0.03)                  44.  eye_of_tyr ( standard - 11 ) - ability disabled ( toggle a )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-11:eye_of_tyr:0.03:Ability Known, Enabled(0.03)                  45.  blessed_hammer ( standard - 12 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-12:blessed_hammer:0.03:Ability Known, Enabled(0.03)                  46.  hammer_of_the_righteous ( standard - 13 ) - talent [ hammer_of_the_righteous ] missing         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-13:hammer_of_the_righteous:0.03:Ability Known, Enabled(0.03)                  47.  crusader_strike ( standard - 14 ) - talent [ blessed_hammer ] disallowed         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-14:crusader_strike:0.03:Ability Known, Enabled(0.03)                  48.  word_of_glory ( standard - 15 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-15:word_of_glory:0.03:Ability Known, Enabled(0.03)                  49.  consecration ( standard - 16 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Protection Paladin-standard-16:consecration:0.03:Ability Known, Enabled(0.03)         Exiting standard with recommendation of NO ACTION at +10.00s.         Returned from list (standard), current recommendation is NO ACTION (+10.00).         - standard         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Protection Paladin - default ].     Recommendation is NO ACTION at 0.00 + 10.00.     Recommendation #1 is NO ACTION at 10.00s (10.00s).     Resources: Resources: holy_power[ 0.00 / 5.00 | 0.00 @ [1 - actual] 0.00 ], mana[ 50000.00 / 50000.00 | 50000.00 @ [1 - actual] 0.00 ]     Time spent generating recommendations:  4.50ms

**Comment by benkimball** [comment]
In the last few days I have also noticed that following Hekili recommendations no longer triggers Blessing of Dawn. It maintains Blessing of Dusk, but it won't build to 5 holy power.

**Comment by Hekili** [comment]
Thanks for adding to the thread.  Could you post a snapshot to Pastebin where a HoPo spender is recommended without reaching 5 HoPo when playing as Protection.  I'm assuming this is the recent priority update that uses SotR more, but I'd like confirmation before I turn that logic off if ODTD is not talented.

**Comment by Hekili** [comment]
For the sake of time, I'll go ahead and make adjustments based on my own assumptions and we'll see how it goes.

**Comment by benkimball** [comment]
Here's a snapshot where Hekili is recommending SotR when I have 3 HoPo, blessing of the dusk is active, and blessing of the dawn is not active. https://pastebin.com/FJSyXQPj

And here's a quick sim of my character: https://www.raidbots.com/simbot/report/tcqCAS4hwy9C1L4ffKopXj

Hope they help!
