### ISSUE TITLE
[BUG] Forecast Period Setting not working as expected for Cooldowns

### ISSUE THREAD

**Issue by mathiasjg** [Hekili/hekili#2456]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am on my Assassination rogue and am having an issue with the new forecast period setting not working as expected for cooldowns. I'd like to change my cooldown section to only show abilities when they are available or very close to available (less than 2-3 seconds). I changed the forecast period for cooldowns to 1.5 but it is still showing abilities that have ~10 seconds left in the display.

### How to Reproduce

1. Enter game as Assassination Rogue
2. Use Echoing Reprimand
3. Wait until it is coming off cooldown and the ability will show at around 10 seconds instead of the 1.5 seconds as expected with the forecast period setting.

### Snapshot (Link)

https://pastebin.com/2d8vdjq7

### Contact Information

Miharkula@5924

**Comment by Hekili** [comment]
Thanks, this will be fixed in today's release.
