### ISSUE TITLE
[BUG] Spell: Invoke Chi-ji doesn't appear on rotation. Instead when it should appear, the rotation freezes

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#2458]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Whenever Invoke Chi-Ji is off cooldown and is supposed to be cast, it bugs and Hekili freezes for a couple of seconds.
Invoke Chi-ji doesn't ever appear as an option either.
Bug started to appear after recent release.

### How to Reproduce

1: Add chi-ji to action list
2: Attack dummies
3: When Chi-ji is the next priority, it doesn't appear and hekili freezes.

### Player Information (Link)

https://pastebin.com/Te2JHiJ9

### Error Messages (Link)

https://pastebin.com/244utuQJ

**Comment by oversoe** [comment]
Here's a 30 sec video demonstrating the issue:
https://gfycat.com/devotedwickedequine

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
This was resolved in a recent update.
