### ISSUE TITLE
Paladin/Ret Doesn't Recommend Final Reckoning or Divine Toll

### ISSUE THREAD

**Issue by Bsirk** [Hekili/hekili#2459]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Doesn't recommend Final Reckoning or Divine Toll in AOE

### How to Reproduce

1. Enter as Ret
2. Take Seraphim and Final Reckoning talents
3. Use Seraphim and build  Holy power back up to 4 or 5
4. Look for Final Reckoning to be suggested but it never is.

### Snapshot (Link)

https://pastebin.com/PiE5jBsN

### Additional Information

Now I can press Final Reckoning manually and then it will recommend Divine Toll soon after. However, I can not get to recommend automatically.

**Comment by Bsirk** [comment]
I was going through the rotation again and saw that it recommends Templar's Verdict where it should recommend Final Reckoning.

**Comment by Hekili** [comment]
In your snapshot, Cooldowns are toggled off.

**Comment by Bsirk** [comment]
Delete this ticket. I have no idea how they got turned off because I never would have done that. I enabled them and everything is working as intended. Sorry for making you check something that was my fault. :-/
