### ISSUE TITLE
[REC] Warlock not recommending Curse of Elements when set as preffered curse. 

### ISSUE THREAD

**Issue by Vibblez** [Hekili/hekili#2460]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing affliction, and setting my preferred curse to elements, it is still recommending agony in all situations.

### How to Reproduce

1. Enter game as an Affliction Warlock.
2. Have curse of elements as your preferred curse.
3. Begin your rotation.
4. See recommendations.

### Snapshot (Link)

https://pastebin.com/LawmadzU

### Additional Information

I understand CoA would output the DPS, but I'm using this in a 10 man raid, where I am the only lock, we have no boomy or unholy, so I'm the lacky here who needs to apply the magic debuff. /sigh

### Contact Information

Discord: Vibblez#4290

**Comment by Hekili** [comment]
Thanks, I'm investigating this.  I will need to add a new expression to make it easier to avoid using other curses.

**Comment by Vibblez** [comment]
Much love, greatly appreciated. :)

**Comment by Vibblez** [comment]
While we're looking at the curses on the target, can you also put a check in to see if curse of doom is on the target, if so, not to recommend anything else? Sort of an edge case, on like on council right now predotting the next add with doom.
