### ISSUE TITLE
[BUG] active_dot.x not updating when dots have expired (was: Missing Flame Shock spread after Primordial Wave in AOE)

### ISSUE THREAD

**Issue by Beltroth** [Hekili/hekili#2461]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After the last update the addon its no longer racommending Flame Shock spread through Lava Lash after casting Primordial Wave when doing AOE

### How to Reproduce

- Use primordial wave on a group of mobs before casting anything else
- The addon will suggest to instant use Lighting Bolt without using Lava Lash first

### Snapshot (Link)

https://pastebin.com/rrak2PxR

### Contact Information

Hèrz#2795

**Comment by Beltroth** [comment]
UPDATE: okay so now the addon is working, the problem started after i've installed OmniCD but after disabling and renabling OmniCD it appears to have fixed it

**Comment by Beltroth** [comment]
Okay so

**Comment by Beltroth** [comment]
It happens still with or without omnicd, hekili sometimes skip the lavalash spread

**Comment by Hekili** [comment]
You appear to have 7 active Flame Shocks with 5 current targets in your snapshot.

**Comment by Beltroth** [comment]
Okay so i've serched the forum and found that i have the same issue as kingreboot, sometimes the addon won't recognize that i'm on top of a group of adds and suggest me to do single target instead of the AOE rotation, i thought maybe was OmniCD interfering but it was just a quick reload fixing the issue but still happens from time to time

**Comment by Hekili** [comment]
The addon recognized that you're in a group of adds, though.  It shows in your snapshot.  Was the snapshot taken when you were having the issue you're reporting?

**Comment by Beltroth** [comment]
Yeah the snapshot was taken during that issue, i sincerly do not know what it's causing the issue, sometimes all is working fine, sometimes i have to reload the game

**Comment by Hekili** [comment]
Are you using the "Better Hekili Targeting" WeakAura that is broken?

**Comment by Beltroth** [comment]
Update: i've just reinstalled hekili and now it is working fine, maybe it was because i've changed fonts of the addons or maybe just a fresh install was needed, anyway now it's been 2 days without the issue.

**Comment by Beltroth** [comment]
> Update: i've just reinstalled hekili and now it is working fine, maybe it was because i've changed fonts of the addons or maybe just a fresh install was needed, anyway now it's been 2 days without the issue.

Okay I just had to wait before replying D:, the problem still happen after a fresh install and deleting all the settings i had before, i don't have any WA like "Better Hekili Targeting".


![WoWScrnShot_031023_201110](https://user-images.githubusercontent.com/127231877/224405709-fb62e49e-4d3c-4be4-9518-4c64aa61a611.jpg)

**Comment by Bingo176** [comment]
https://pastebin.com/cbNgGyRf

this entry's criteria FAILS: talent.lashing_flames.enabled[true] & dot.flame_shock.ticking[true] & ( active_dot.flame_shock[7.00] < active_enemies[2.00] ) & active_dot.flame_shock[7.00] < 6

This looks like the issue. Had 4 targets in combat and no Lava Lash recommended to spread Flame Shock for spread then you would Lightning Bolt to get the haste from Splintering Elements.

**Comment by JamesHarden-13** [comment]
Any progress? I am also facing this issue

**Comment by Hekili** [comment]
Please don't post non-contributory status update questions.  You'll know when it's been addressed.

**Comment by Hekili** [comment]
Fix should be live in 1.0.23.
