### ISSUE TITLE
[BUG] REPLACE THIS TEXT WITH A SHORT DESCRIPTION OF THE BUG YOU ARE REPORTING

### ISSUE THREAD

**Issue by JamesHarden-13** [Hekili/hekili#2465]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The value of active_dot.flame_shock is wrong,there is no dot of flame shock but the value is 4，please see the attachment
![image](https://user-images.githubusercontent.com/61502135/224282795-d5c98dd4-31e9-4144-8ea4-e325208e74fb.png)

### How to Reproduce

1、enter game as a shaman
2、Change specialization to Enhancement
3、The value of active_dot.flame_shock sometimes is correct sometimers is wrong

### Player Information (Link)

build: v10.0.5-1.0.22 level: 70 (70) class: SHAMAN spec: enhancement  talents: ancestral_defense = 1/1     ancestral_guidance = 1/1     ashen_catalyst = 1/1     astral_shift = 1/1     brimming_with_life = 1/1     capacitor_totem = 1/1     chain_lightning = 1/1     cleanse_spirit = 1/1     crash_lightning = 1/1     crashing_storms = 1/1     earth_elemental = 1/1     elemental_spirits = 1/1     elemental_warding = 2/2     elemental_weapons = 2/2     feral_spirit = 1/1     fire_and_ice = 1/1     flurry = 1/1     frost_shock = 1/1     hailstorm = 1/1     healing_stream_totem = 1/1     hot_hand = 2/2     ice_strike = 1/1     improved_lightning_bolt = 2/2     improved_maelstrom_weapon = 2/2     lashing_flames = 1/1     lava_burst = 1/1     lava_lash = 1/1     maelstrom_weapon = 1/1     molten_assault = 2/2     natures_fury = 2/2     natures_guardian = 2/2     overflowing_maelstrom = 1/1     planes_traveler = 1/1     primal_maelstrom = 2/2     primordial_wave = 1/1     raging_maelstrom = 1/1     spirit_walk = 1/1     spirit_wolf = 1/1     splintered_elements = 1/1     stormstrike = 1/1     sundering = 1/1     swirling_currents = 2/2     swirling_maelstrom = 1/1     thundershock = 1/1     thunderstorm = 1/1     wind_rush_totem = 1/1     wind_shear = 1/1     windfury_totem = 1/1     windfury_weapon = 1/1     winds_of_alakir = 2/2     witch_doctors_ancestry = 2/2  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: algethar_puzzle_box = 1     tier29 = 4  gear:  = 1     algethar_puzzle_box = 1     tier29 = 4  legendaries: none  itemIDs: 134296, 190513, 192999, 193000, 193001, 193425, 193426, 193511, 193685, 193701, 194301, 195512, 198730, 200396, 200398, 200399, 200401  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Enhancement     petbased = false     potion = potion_of_spectral_agility     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     burn_before_wave = true     filler_shock = true     hostile_dispel = false     pad_lava_lash = true     pad_windstrike = true     project_windfury = 0     purge_icd = 12  toggles: cooldowns = true [separate]     custom1 = false      custom2 = false      defensives = true [separate]     essences = true [overridden]     interrupts = false      mode = automatic      potions = false   keybinds:      algethar_puzzle_box = Q   [01], Q   [02], Q   [11]     ancestral_guidance  = F4  [06]     astral_shift        = F2  [06]     bloodlust           = F5  [06]     capacitor_totem     = 7   [01], 1   [02]     chain_lightning     = 6   [01], 6   [02]     crash_lightning     = F1  [05]     earth_elemental     = F3  [06]     elemental_blast     = 4   [01], 4   [02]     feral_spirit        = 1   [01]     flame_shock         = F11 [06]     flametongue_weapon  = N1  [06]     frost_shock         = F10 [05]     ghost_wolf          = F   [05]     healing_surge       = 3   [01], R   [11]     ice_strike          = F9  [05]     lava_burst          = 4   [01], 4   [02]     lava_lash           = F7  [05]     lightning_bolt      = F8  [05], 1   [07]     lightning_shield    = N2  [06]     primordial_wave     = 2   [01], F6  [05]     spirit_walk         = V   [01]     stormstrike         = 5   [01], 5   [02]     sundering           = R   [01], R   [02]     thunderstorm        = 2   [02]     wind_rush_totem     = 3   [02]     wind_shear          = MwD [01]     windfury_totem      = N3  [06]     windfury_weapon     = N0  [06]     windstrike          = 5   [01], 5   [02]  warnings: none

### Error Messages (Link)

No error message

**Comment by Hekili** [comment]
I'm working on a resolution to this issue, which is already discussed in another ticket, so I'm closing this one.  If you make future reports, please make sure to put the Player Information, Error Messages, or Snapshots in Pastebin and link to them so that they are readable.  Thanks.
