### ISSUE TITLE
BM Hunter - multidotting with Barbed shot

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2466]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hey. It would be nice to implement a Barbed shot swap to at least 2-3 more targets. It's quite a dps benefit especially on higher keys and big pools. I observe it myself when I try to apply Barbed shot in pulls or on AOE dummies that the damage is a bit more. Then though the algorithm is a bit confused and stutters in conjunction with Multi-Shot - there is a noticeable pause at times. But I'm sure it could be sorted out. It's a recommendation from wowhead, after all. https://www.wowhead.com/guide/classes/hunter/beast-mastery/rotation-cooldowns-pve-dps#multi-dotting Thank you!

**Comment by Hekili** [comment]
This is the wrong kind of ticket and lacks required information.

**Comment by marekCs** [comment]
I'm not getting it. I'm writing an idea, if it would be possible to add the required functionality in the future. Also, I don't see any other required fields left unfilled.

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/224999433-32a03ca1-e13e-4b21-aee8-f9210d210a2d.png)

Snapshots are required.

**Comment by marekCs** [comment]
Wait, it's doing swapping now for Barbed Shot, you added it in the last patch right? No mention in changelog :)

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/commit/a37f2b534955d7d111a9a5141ba1ca68d4be6048

From last week; first release would be 1.0.23.
