### ISSUE TITLE
Death knight Unholy / festering wound AOE

### ISSUE THREAD

**Issue by j3llevdb** [Hekili/hekili#2467]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When disabling Recommend Target Swaps, the rotation still suggests applying festering wounds with festering strike in AOE,
eventho the target already has 6 stacks.

Also, when relogging, recommend target swaps is checked on again.

nowadays, when playing disease build in m+, its not required anymore to spread festering wounds anymore.

### How to Reproduce

1 enter game as unholy dk
2 take talendbuild as followed: https://www.wowhead.com/talent-calc/death-knight/unholy/DAPUVREBSEVBAFEhqUANVVhUVBkEEBSlFCEA
3 start attacking AOE dummies
4 follow recommendations
5 after some time you will see it keeps suggesting to apply festering wounds to ur target wich already has 6 of them

### Snapshot (Link)

https://pastebin.com/NtiXJYVc

**Comment by Hekili** [comment]
The usage of Scourge Strike in your snapshot is to apply Plaguebringer, regardless of wounds.

**Comment by Hekili** [comment]
If you provide a sim of your character in multi-target (i.e., Patchwerk, 3+ targets), I can adjust to see if suppressing that Scourge Strike at max wounds is a DPS improvement.

**Comment by j3llevdb** [comment]
maybe i missed my snapshot, the issua is not applying plaguebringer with scourge strike.
its applying festering strike while having 6 wounds already

**Comment by j3llevdb** [comment]
while recommend target swaps are disabled

**Comment by Hekili** [comment]
No, the entry in the AOE action list for Scourge Strike that was used is meant to apply Plagueringer when Superstrain, Ebon Fever, and Plaguebringer are talented.  It doesn't care about the number of wounds you have.

```
63.  scourge_strike ( aoe - 2 )
The action (scourge_strike) is usable at (1.76 + 1.07) with cost of 1 runes (have 1).
 - the action is ready before the current recommendation (at +1.07 vs. +5.48).
List ( aoe ) called from ( Unholy:default:23 ) would PASS at 1.07.
active_enemies[5.00] >= 4
 - this entry's criteria PASSES: talent.superstrain.enabled[true] & talent.ebon_fever.enabled[true] & talent.plaguebringer.enabled[true] & buff.plaguebringer.remains[0.00] < gcd.max[1.07]
```

If you provide a sim of your character, I can see whether it would be better to make this entry avoid overcapping wounds as well.  As it is written, it specifically doesn't care about overcapping wounds on the target.

**Comment by Hekili** [comment]
The 10.0.7 release includes changes to avoid wasteful Scourge Strikes (and models Plaguebringer correctly).
