### ISSUE TITLE
[bug] Color Picker issue for Mage in Wrath

### ISSUE THREAD

**Issue by Popparenn** [Hekili/hekili#2468]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I cant use the hekili priority helper for any mage spec, 
i get this error code 

![WoWScrnShot_031423_133959](https://user-images.githubusercontent.com/127210713/225003707-ae81f249-34e9-46f1-a624-02c37db57f93.jpg)

### How to Reproduce

1. try out a mage and see if u get up the priotiy helper 
2.

### Error Messages

```
[string "=[C]"]: in function `SetVertexColor'
[string "@Hekili/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-ColorPicker.lua"]:105: in function `SetColor'
[string "@Hekili/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1377: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@Hekili/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1137: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@Hekili/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@Hekili/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1564: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1548>
[string "=[C]"]: ?
[string "@Hekili/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Hekili/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Hekili/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Hekili/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:522: in function `Select'
[string "@Hekili/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:530: in function `SelectByValue'
[string "@Hekili/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1735: in function `FeedGroup'
[string "@Hekili/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1919: in function `Open'
[string "@Hekili/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:868: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Hekili/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Hekili/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Hekili/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Hekili/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...kili/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>
```

### Snapshot (Link)

sad

### Raidbots Sim Report (Link)

asd

**Comment by Hekili** [comment]
Not the right kind of ticket, but okay.  For future reference:
![image](https://user-images.githubusercontent.com/9438134/225004540-333aed2f-1f67-4466-b169-8fd2e72e7fdb.png)

What version of the addon are you using?

**Comment by Popparenn** [comment]
v3.4.1-1.8.2

**Comment by Popparenn** [comment]
> Not the right kind of ticket, but okay. For future reference: ![image](https://user-images.githubusercontent.com/9438134/225004540-333aed2f-1f67-4466-b169-8fd2e72e7fdb.png)
> 
> What version of the addon are you using?

v3.4.1-1.8.2

**Comment by Popparenn** [comment]
So do you know the problem?

**Comment by Hekili** [comment]
I will update the ticket when I have information to update.

**Comment by Popparenn** [comment]
> I will update the ticket when I have information to update.

Okay =)

**Comment by Popparenn** [comment]
> I will update the ticket when I have information to update.

Still no information?

**Comment by Hekili** [comment]
Yes.  I'm also locking since I already advised you I will update when there's information to update.
