### ISSUE TITLE
Addon doesn't recommend AOE rotation for Ret Paladin after update.

### ISSUE THREAD

**Issue by Fr0stykiller** [Hekili/hekili#2469]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After update, addon doesn't seem to suggest AOE rotation AT ALL. No Divine Storm, no Wake of Ashes, nothing. Just TV as spender, nothing else. 

### How to Reproduce

1. Enter as Ret
2. Take Seraphim and Final Reckoning talents
3. Attack 5+ group of mobs.
4. Build to 4+ HP and start spending
5. No DS except (EL procs)

### Snapshot (Link)

https://pastebin.com/95w4VW5t

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mtKddktRaSXqGfwTwNjFTj

### Additional Information

Checked multiple display types: automatic, primary + AOE. I also had Single Target display + AOE display on at the same time and recomendations are pretty much the same with minimal differences like Cons earlier than other spenders.

**Comment by Hekili** [comment]
You should not install an alpha version for 10.0.7 on live.

**Comment by Fr0stykiller** [comment]
Thank you, that did it. Was blindly installing through addon manager.
