### ISSUE TITLE
Unholy DK Not recommending Epidemic

### ISSUE THREAD

**Issue by Disec** [Hekili/hekili#2470]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

My priority list is not showing epidemic even at 4+ targets. Valdraken dumbies

I reinstalled the addon, along with deleting save data and doing an addon reset. 
My friend logged into my dk after doing the above aswell but he can see epidemic but epidemic does not show on mine.

### How to Reproduce

Unholy dk
Go to 5 pack of dumbies
Use BwPAAAAAAAAAAAAAAAAAAAAAAAAiQSCJiERkIRIkkIRAAAAAAAAAAKkkDECJpBAQKSRkkkIJB Talents
Doesnt show epidemic for me, but does my friend?

### Snapshot (Link)

(https://pastebin.com/rSwRcF2t) Only ever wants death coil. I could run the rotation for 5 hours on the 5 pack and it would never recommend epidemic. Tried with even straight AOE on and it does not want to show epidemic. Tried with ebon fever and bursting sores. It was working perfectly fine a few days ago.

### Raidbots Sim Report (Link)

(https://www.raidbots.com/simbot/report/fiSxJmWVLGaWYcYn5Ecs5k)

**Comment by Disec** [comment]
I've put in snap shot along with a sim. Not sure why it just refuses to recommend epidemic to me. But if my friend logs into my DK on his PC it does?

**Comment by Hekili** [comment]
Those are not complete snapshots that you pasted to Pastebin. Make sure to press `CTRL+A` to highlight all the text in the box, including the lines that you can't see. Then paste it to Pastebin and provide a new link.

A single snapshot will be hundreds of not thousands of lines.  Thanks.

**Comment by Hekili** [comment]
In the meantime, please check the following settings:
- [ ] Check that you haven't installed a 10.0.7 alpha version on live retail. Revert to the latest 10.0.5 version if you did so by mistake. 
- [ ] Display Mode is set to Auto (or specifically not Single).
- [ ] Abilities > Epidemic, Require Toggle is Default and/or not set to a toggle that is turned off. 
- [ ] Abilities > Epidemic, Minimum and Maximum Targets are not set too high/low. (Zero is safe.)
- [ ] Unholy default priority hasn't been edited; click the little circle arrow to reset it to default and test again.

Please check these details and collect a full snapshot and I'll look into this again. Thanks!

**Comment by Disec** [comment]
> In the meantime, please check the following settings:
> 
> * [x]  Check that you haven't installed a 10.0.7 alpha version on live retail. Revert to the latest 10.0.5 version if you did so by mistake.
> * [ x]  Display Mode is set to Auto (or specifically not Single).
> * [x ]  Abilities > Epidemic, Require Toggle is Default and/or not set to a toggle that is turned off.
> * [x ]  Abilities > Epidemic, Minimum and Maximum Targets are not set too high/low. (Zero is safe.)
> * [ x]  Unholy default priority hasn't been edited; click the little circle arrow to reset it to default and test again.
> 
> Please check these details and collect a full snapshot and I'll look into this again. Thanks!

Tried all these last night, my friend who was having no issues and was trying to help me solve the issue suggested these. we even re-installed so many different versions. I will grab a better snapshot when I get home from work later today. I didnt no it showed more then just the 1 little line of text.

**Comment by Hekili** [comment]
Do you have nameplates enabled such that target detection can work?  Not just your target's nameplate, but enemy nameplates in general?

**Comment by Disec** [comment]
> Do you have nameplates enabled such that target detection can work? Not just your target's nameplate, but enemy nameplates in general?

Yeah, me and my friend both use Plater, I use exact same UI and addons etc as him. He helped me do the setup for it all. Just weird that he can login to my dk and it works fine, even deleted all saved variables. reinstalled addon but still only death coils no epidemics.

**Comment by Hekili** [comment]
Do you have a WeakAura called "Better Hekili Targeting" installed?

**Comment by Disec** [comment]
> Do you have a WeakAura called "Better Hekili Targeting" installed?

No, neither of us have that. What does that do?

**Comment by Hekili** [comment]
It breaks things.

**Comment by Disec** [comment]
> It breaks things.

Only one we have is the one where it makes the keybinds into the toggleable window. the clickable window weakaura. Once im home from work around 5pm pst I can post a correct snapshot.

**Comment by Disec** [comment]
Good news, he made a mistake and in his plater it was only showing the 1 nameplate of what he was targetting and not all the enemies around. Thank you for your help anyway!
