### ISSUE TITLE
[BUG] Warlock Destruction "havoc_active" "havoc_remains" variable not functioning correctly with Talent Mayhem

### ISSUE THREAD

**Issue by nuttin0011** [Hekili/hekili#2472]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

i write action list and use variable "havoc_active" "havoc_remains" when use talen Mayhem
both "havoc_active" "havoc_remains" not detected havoc debuff at nearly enemy

and when i use "active_dot.havoc" it work correctly and return 1
but i cannot tract remains debuff timer

please help.

![image](https://user-images.githubusercontent.com/74884682/225712346-b6436250-afa7-47d9-ba94-0c7d6839236a.png)

### How to Reproduce

Destruction Warlock
Use Talent Mayhem
Use Single Spell and Proc Havoc Debuff to nearly Enemy

### Player Information (Link)

https://pastebin.com/RgsyHuL0

### Error Messages (Link)

-

**Comment by Hekili** [comment]
Will be fixed in next release.
