### ISSUE TITLE
[REC] Kyrian Retribution Paladin Divine Toll reccommendation while in Shadowlands Zones at lvl 70

### ISSUE THREAD

**Issue by Ketrel** [Hekili/hekili#2474]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When in shadowlands zones such as the maw, Divine Toll is being detected as available and off cooldown.
It's seemingly detecting the Kyrian version of this ability vs the Ret Paladin version. 

### How to Reproduce

1. Login to game as ret paladin
2. Go to a Shadowlands zone
3. Enter combat and use Divine Toll
4. Continue Rotation
5. Divine Toll is reccomended while still on cooldown

### Snapshot (Link)

https://pastebin.com/XAB8w24P

### Additional Information

![Wow_2023-03-17_16-31-29](https://user-images.githubusercontent.com/1002607/226038209-6ab2a45a-0fe3-4fc8-b662-a564da2e19de.png)

**Comment by Hekili** [comment]
This is more likely a problem that you're using the 10.0.7 version on live; half your talents aren't detected properly, including Divine Toll.  I'm not able to replicate the issue in the last 10.0.5 release.

**Comment by Ketrel** [comment]
That does seem to be the case.  I have no idea how I ended up with the 10.0.7 version.

I get the releases from Github and it definitely said 10.0.5, but the TOC file in my addons folder agrees with what you're saying.
