### ISSUE TITLE
[BUG] Affliction rotation continually recommends Corruption be cast multiple times in a row

### ISSUE THREAD

**Issue by nat3s** [Hekili/hekili#2476]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As above, the addon starts well, but after 4-5 spells, it starts recommending Corruption straight after you've just cast it sometimes for as many as 6 Corruption casts in a row.

Works fine for Destruction, seems Affliction rotation is just broken.

Conro in contrast is fine. I get around 50k dps with Conro and 20k dps with Hekili as a result (ST).

### How to Reproduce

1. Enter game as warlock (affliction)
2. Start hitting dummy with Auto rotation.

### Player Information (Link)

https://pastebin.com/49pjtwBP

### Error Messages (Link)

No error appears, rotation is just broken

### Additional Information

Screenshot showing the error here:

https://imgur.com/a/hoWCKdi

### Contact Information

nat3s#9960

**Comment by Hekili** [comment]
This is a report re: the recommendations made by the addon. Please provide a snapshot.

**Comment by nat3s** [comment]
Sorry what do you meant by snapshot? I included a screenshot in my original post, not sure if you saw it? Here it is again:

https://imgur.com/a/hoWCKdi

100% broken for locks, tried on 2 accounts.

ConRO works fine and parses way higher in dps (50k vs 20k for Hekili).

**Comment by Hekili** [comment]
> 100% broken for locks, tried on 2 accounts.

You don't have to persuade me there's an issue; you just need to provide the data.  When you came to provide a ticket, you were presented with these options:

![image](https://user-images.githubusercontent.com/9438134/226199459-dc3daf0e-5438-4296-873b-bba920017571.png)

You picked the first one, but notably didn't have error messages to submit.  The third was what you were looking for, and provides instructions re: snapshots.  I'll provide that information below.

> ConRO works fine and parses way higher in dps (50k vs 20k for Hekili).

You're totally free to use ConRO, of course.  I'll look into the issue, but submitting the required information from the start definitely expedites the process.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
I did some testing and research in the meantime; your screenshot helped.  I'll be posting an update where the addon will treat PvP dummies like players, so that effects like Absolute Corruption won't cause `refreshable` to be true, suggesting premature Corruption resets.

Essentially, `refreshable` means "remaining time is less than 30% of the duration of a new application."  Corruption's default duration is 14 seconds, but if you talent for Absolute Corruption it is 24 seconds against players (or infinite -- the addon uses 1 hour -- for NPCs).  The problem in this case appears to be that `UnitIsPlayer()` returns false for PvP Target Dummies, so with Absolute Corruption talented and fighting the dummy, the addon was saying "Yep, 20 seconds is less than 30% of an hour, so it's `refreshable`."

I'm certain that's pretty annoying, but it will be addressed in the next release.

Did you see this occur anywhere else, or just in testing on dummies?
