### ISSUE TITLE
FireMage checked Scorch instead of Fireball/Pyroblast in moving, Pyroblast is not recommended when Hot Streak! Buff is on. Unless target's HP below 30%

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#2478]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When getting the Hot Streak! Buff, maybe Pyroblast should be used instead of Scorch regardless of movement

### How to Reproduce

Login to the game with FireMage, checked Scorch instead of Fireball/Pyroblast in moving, and then get Hot Streak! Buff in moving to reproduce.

### Snapshot (Link)

https://pastebin.com/pzC2jRep

### Additional Information

![WoWScrnShot_032023_232855](https://user-images.githubusercontent.com/59405956/226389459-4a0e9680-afd8-475e-a0b6-faff6263c99f.jpg)

### Contact Information

nothing...

**Comment by Hekili** [comment]
> Login to the game with FireMage, open Scorch instead of Fireball/Pyroblast in moving, get Hot Streak! Buff to reproduce。

Then get a snapshot and include that in the ticket, as it's required information.  I'm closing since this is your second ticket on the subject, but you're still not supplying the required information for the ticket.  If you provide the snapshot, I'll reopen it.  Thanks.

**Comment by Livvvvvvven** [comment]
Sry, I'm not very skilled.

https://pastebin.com/pzC2jRep

![WoWScrnShot_032023_232855](https://user-images.githubusercontent.com/59405956/226389459-4a0e9680-afd8-475e-a0b6-faff6263c99f.jpg)

**Comment by Livvvvvvven** [comment]
> > Login to the game with FireMage, open Scorch instead of Fireball/Pyroblast in moving, get Hot Streak! Buff to reproduce。
> 
> Then get a snapshot and include that in the ticket, as it's required information. I'm closing since this is your second ticket on the subject, but you're still not supplying the required information for the ticket. If you provide the snapshot, I'll reopen it. Thanks.

thx.

**Comment by Hekili** [comment]
I saw that you commented with a snapshot and then you removed it.  I still have the snapshot and have found the Pyroblast entry that was prevented due to moving; it normally wants to use Pyroblast with Hot Streak if your last cast was Fireball, which won't be the case if you are using the movement setting.  I'll make that adjustment.

**Comment by Livvvvvvven** [comment]
> I saw that you commented with a snapshot and then you removed it. I still have the snapshot and have found the Pyroblast entry that was prevented due to moving; it normally wants to use Pyroblast with Hot Streak if your last cast was Fireball, which won't be the case if you are using the movement setting. I'll make that adjustment.

Yes, I deleted the new comment and updated in original main. Thank you for your help.

**Comment by Hekili** [comment]
This has been addressed; let me know if you find any issues.

**Comment by Livvvvvvven** [comment]
> This has been addressed; let me know if you find any issues.

Thank you. I will try it tomorrow and give you feedback. And I also hope that this options will be invalid when the player has ice_floes buff, because it still will use Scorch and waste the buff.

https://pastebin.com/gneNxD4y

Of course if you've taken this and updated to 10.0.7. Im sorry to bother you because I can't update yet.
