### ISSUE TITLE
[REC] Ret Pally AoE abilities not showing 

### ISSUE THREAD

**Issue by Blujelly87** [Hekili/hekili#2479]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili-v10.0.7-1.0.0. i noticed that AoE abilities such as Divine Storm & Final reckoning aren't showing on the primary bar, I have the display mode as 'auto'

I have downgraded to Hekili-v10.0.5-1.0.25 just in case I'd changed something, and confirmed the above abilities showed in the bar.

<img width="317" alt="Hekili-v10 0 7-1 0 0  " src="https://user-images.githubusercontent.com/116963975/226691860-40bcb211-436b-4063-8f74-8a0ad905b3e7.png">
<img width="238" alt="Hekili-v10 0 5-1 0 25" src="https://user-images.githubusercontent.com/116963975/226691867-e6f90916-a070-4b5e-abb5-279a2ea2151f.png">

### How to Reproduce

Any AoE ability will not show.

### Snapshot (Link)

https://pastebin.com/t6cvie2Z

**Comment by Hekili** [comment]
Are you playing on 10.0.7 servers or 10.0.5?

**Comment by apospathi** [comment]
I was experiencing it as well.  When I looked into it I noticed under abilities Divine Storm and Blade of Justice were disabled and Cooldowns were set to not shown.

Not sure why those got toggled for me, but something you might want to check.

**Comment by Hekili** [comment]
> Not sure why those got toggled for me, but something you might want to check.

IDK, you didn't provide a snapshot.  If you try to use the 10.0.7 version of the addon before your servers are up with 10.0.5, it's not going to work regardless.

Are you playing on 10.0.7 servers or 10.0.5?

I've posted updates to incorporate more of the 10.0.7 changes that were missed in the initial release.  If you want to support further investigation and are playing on 10.0.7 servers, install v10.0.7-1.0.0b and get a snapshot if you're still having issues.

**Comment by apospathi** [comment]
> > Not sure why those got toggled for me, but something you might want to check.
> 
> IDK, you didn't provide a snapshot. If you try to use the 10.0.7 version of the addon before your servers are up with 10.0.5, it's not going to work regardless.

Its working for me now after making those changes, I did try to log in earlier, probably messed something up.  After manually making those changes it worked for me.  Figured the OP might have encountered the same thing.

**Comment by Hekili** [comment]
It's a good point that the red asterisk can be misleading; it will show when an ability is `disabled` for any reason, even a reason that has nothing to do with the ability's settings.  I'll probably change how those abilities are turned off depending on your talents.
