### ISSUE TITLE
[REC] Ret 10.0.7 Recommendations not updating

### ISSUE THREAD

**Issue by Jacii1121** [Hekili/hekili#2481]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Just updated to v10.0.7-1.0.0a.  Playing around with Target Dummies in Valdraken, noticing that abilities with cooldowns are being recommended after use.  I tried to get a snapshot noticed warnings.

### How to Reproduce

Talent Set - BYEAS+uMNo6HaxL/ztTZBhrdcCAAAQAAiWp0KJtS7AiWkkWSAAAAAAAEBJJEIBRKRIJkSaCkICJiSjWA
Follow rotation on multitarget dummies. Noticed Divine Toll being recommended, hit ability, continues to show in recommendation but is greyed out.  

### Snapshot (Link)

https://pastebin.com/Lv5DJP3R

### Additional Information

Screenshot at time of Snapshot https://i.imgur.com/9t09O5g.jpeg

### Contact Information

Jacii#8227

**Comment by Hekili** [comment]
All should be resolved in latest updates.
