### ISSUE TITLE
[REC] Prot Paladin not recommending Blessed Hammer.

### ISSUE THREAD

**Issue by kittykiller** [Hekili/hekili#2482]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Was attacking a group of target dummies for about 2 mins and Blessed Hammer was never recommended. It also seems to recommend consecration way too much when I'm low on holy power.

### How to Reproduce

1. enter as protection paladin.
2. talent blessed hammer
3. do rotation

### Snapshot (Link)

https://pastebin.com/hdZysXsf

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wPdn7mwwQJmHC1w6tMyxeR

**Comment by Hekili** [comment]
Thanks for the report.  I've re-enabled Blessed Hammer in v10.0.7-1.0.0c.
