### ISSUE TITLE
[BUG] Lua error for sub rogue

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#2483]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am getting this error as a sub rogue while in combat.  (Fighting mobs in the new Forbidden Reach zone)

`3x Hekili/Dragonflight/RogueSubtlety.lua:422: bad argument #1 to 'wipe' (table expected, got nil)
[string "=[C]"]: ?
[string "@Hekili/Dragonflight/RogueSubtlety.lua"]:422: in function `hook'
[string "@Hekili/Classes.lua"]:5728: in function `callHook'
[string "@Hekili/Events.lua"]:1557: in function <Hekili/Events.lua:1555>
[string "@Hekili/Events.lua"]:1852: in function `handler'
[string "@Hekili/Events.lua"]:60: in function <Hekili/Events.lua:52>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"`

### How to Reproduce

1. Enter the game as a sub rogue
2. Enter combat.  

### Player Information (Link)

https://pastebin.com/n5hrX1r1

### Error Messages (Link)

https://pastebin.com/0GXJAJHq

**Comment by Hekili** [comment]
Thanks; this should be resolved in 1.0.7d.

**Comment by wheatbread** [comment]
Sorry, I don't know if the current version is the fixed one yet?  Just wanted to report that I'm still getting spammed with the error ingame. 

`27x Hekili/Dragonflight/RogueSubtlety.lua:422: bad argument #1 to 'wipe' (table expected, got nil)
[string "=[C]"]: ?
[string "@Hekili/Dragonflight/RogueSubtlety.lua"]:422: in function `hook'
[string "@Hekili/Classes.lua"]:5728: in function `callHook'
[string "@Hekili/Events.lua"]:1557: in function <Hekili/Events.lua:1555>
[string "@Hekili/Events.lua"]:1852: in function `handler'
[string "@Hekili/Events.lua"]:60: in function <Hekili/Events.lua:52>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"`
