### ISSUE TITLE
[BUG] error on shaman login "attempt to index local 'mhStats' (a nil value)" wotlk classic

### ISSUE THREAD

**Issue by totano** [Hekili/hekili#2484]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

logging shaman (80 enha or 69 ele) i get an error message, i can dismiss it and the addon works (apparently) fine

### How to Reproduce

1. Enter the game (Wotlk Classic) as a shaman (possibly above 69 level)

### Player Information (Link)

https://pastebin.com/SZCbkw64

### Error Messages (Link)

https://pastebin.com/UHkBt2Hi

### Additional Information

error message is from elvui window, cba to install other addons to report

### Contact Information

alessandro.lendaro@gmail.com

**Comment by Bluedabadii** [comment]
Im having the exact same problem on my Enhanc Shaman lvl 80.
