### ISSUE TITLE
[REC] RET PALADIN RECCOMENDS PASSIVES AND SINGLE TARGET INSTEAD OF AOE, ALSO GREYED OUT ABILITIES

### ISSUE THREAD

**Issue by Mempavrai** [Hekili/hekili#2485]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

didnt do anything, just booted up after update, tried reinstalling too but it doesnt help

### How to Reproduce

1: boot game as ret with build BYEAS+uMNo6HaxL/ztTZBhrdcCAAAQAgIalSrk0KNJKJJpQAAAAAAAkGkkQgEEpEBJEploRCSEiSjWA
2: passives show in the reccomendation as well as single target instead of AoE

### Snapshot (Link)

https://pastebin.com/PjFa0ftM

**Comment by Hekili** [comment]
From your snapshot:
> build: v10.0.5-1.0.17

Are you playing on 10.0.7 servers?  You will need to update the addon.

**Comment by Mempavrai** [comment]
hello,

i am playing on the  10.0.7  servers.
addon is up to date on curseforge aswell :/



![image_2023-03-22_162848960](https://user-images.githubusercontent.com/128611800/226954854-a17fb184-7e8d-4c4a-b44c-128b09d1d3b0.png)

**Comment by Mempavrai** [comment]
![image_2023-03-22_163402357](https://user-images.githubusercontent.com/128611800/226956436-1a71d939-b95c-4c15-9fab-9569d68c5dcd.png)

here is what happens more clearly;

**Comment by Hekili** [comment]
Take a new snapshot, then, because the one you posted shows you are using an old version.

**Comment by Mempavrai** [comment]
i see now. it indeed says 10.0.5 allthough i just reinstalled it 5 times. i will download from other source and let you know

**Comment by Mempavrai** [comment]
hmm. after downloading from Github. it still says 10.0.5

**Comment by Mempavrai** [comment]
found the issue, game is located to my SSD and curseforge thought it was still on my HDD and somhow kept merging the old version still on my HDD with the new version folder. Ew. smells like bad coding from the Curseforge guys
