### ISSUE TITLE
Addon not recognizing multiple targets in combat and suggesting Templars Verdict vs Divine Storm when Emp Legacy not proc'd

### ISSUE THREAD

**Issue by Suzaku1344** [Hekili/hekili#2486]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I went to the 5 target dummies in the PVP room, and started rotation like normal. Noticed it was suggest TV for everything. I manually casted Divine Storm to make sure all targets were in combat and detected, and even switched targets. Addon kept suggesting TV. Checked to make sure Emp Power was not present and it still suggested. Opened dual to see AoE and ST and the suggestions were different as expected. Swapped to Reactive and same issue.

Reset profile and tried again same deal.

Even went up to the dummies and avoided Judgement and Divine Toll so nothing was boosted for Emp Legacy

![ST vs AOE](https://user-images.githubusercontent.com/128621734/226968275-e015f6c2-45d6-4b64-a22d-5c1da86d44e1.png)

### How to Reproduce

![ST vs AOE](https://user-images.githubusercontent.com/128621734/226966862-fcc7a5d3-6078-41aa-8961-1f8bf6542240.png)

### Snapshot (Link)

https://pastebin.com/547hqWrh

### Contact Information

Suzaku#3835

**Comment by Hekili** [comment]
You are in Dual Display mode; your primary display is only going to show single-target recommendations.

See /hekili > Toggles > Display Mode and switch back to Automatic.

**Comment by Hekili** [comment]
Your other targets were omitted because your target detection is set to filter out any enemies that do not have an on-screen nameplate.  I'm guessing you are presently showing only your target's nameplate and not any other targets.  You've blocked out most of your screen, so I can't confirm.

**Comment by Suzaku1344** [comment]
I was swapping between Auto (primarily use) and it wasn't making the suggestion so I started comparing to Single, AOE, Dual, and Reactive. All making the same suggestions.

The name plate deal makes sense and yes it's been only showing one and it's annoying.. knowing that I will dig outside the app to find it.

**Comment by Hekili** [comment]
The CVar for showing other nameplates, not just your target's is `nameplateShowAll`.  You can test with `/run SetCVar("nameplateShowAll", 1)` to enable or `/run SetCVar("nameplateShowAll", 0)` to disable.  You may need to find this setting in your nameplate addon in case it changes it for you.

**Comment by Suzaku1344** [comment]
I did not have the blizz default always show nameplates enabled cause I thought it was including friendlies.. my bad as soon as I enabled it it suggested the correct stuff.
