### ISSUE TITLE
Avenging Wrath - Boss Encounter Only not working

### ISSUE THREAD

**Issue by Blujelly87** [Hekili/hekili#2488]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Currently running on WoW 10.0.7 / Hekili v10.0.7-1.0.0e

I've tried looking over the options and hoping I haven't missed of something glaring & obvious or that has already been flagged. I've noticed if you select Avenging Wrath for boss encounters only, it still shows on the bar.

I know that in settings for abilities or items there is normally a red dot next to it that would suggest a setting has been changed. This doesn't appear to the case on Avenging Wrath.

<img width="670" alt="Screenshot 2023-03-22 at 18 00 31" src="https://user-images.githubusercontent.com/116963975/226997830-e7e6e592-da3c-402c-9c7d-1846fdfb91e6.png">

### How to Reproduce

Unable to reproduce as I believe this could be a. bug with a ability not showing during boss encounters only

### Snapshot (Link)

https://pastebin.com/tBapdKXF

**Comment by Hekili** [comment]
I've narrowed this down to Avenging Crusader overriding Avenging Wrath.  I think you'll find Avenging Wrath listed twice in that Abilities dropdown; the first is actually for `avenging_crusader` and the second is `avenging_wrath`.  I'm looking for a resolution now.

**Comment by Hekili** [comment]
This will be fixed in the next release; in the meantime, if you modify the second "Avenging Wrath" in the Abililties dropdown, you should be able to update those settings.
