### ISSUE TITLE
Ret Pally - Rebuke not showing on timeline

### ISSUE THREAD

**Issue by Blujelly87** [Hekili/hekili#2489]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've noticed that Rebuke isn't showing on the bar for when interrupts are applicable, again not sure if this is an over sight on my end.

Currently running up to date on both WoW & Heklil

<img width="320" alt="Untitled" src="https://user-images.githubusercontent.com/116963975/227032008-287f0b4c-88af-4988-93de-3825e0f3e7ee.png">

### How to Reproduce

I've noticed that Rebuke isn't showing on the bar for when interrupts are applicable, again not sure if this is an over sight on my end.

### Snapshot (Link)

https://pastebin.com/6KVCpGi4

**Comment by Hekili** [comment]
That cast is not interruptible.

**Comment by Blujelly87** [comment]
Sorry uploaded the wrong screenshot, please see below:

<img width="447" alt="123" src="https://user-images.githubusercontent.com/116963975/227125131-908241f2-256d-4253-a3ff-109364532835.png">

**Comment by Hekili** [comment]
I'll need the screenshot and snapshot to match up at the same time.  If I had to guess, you're using Action Targeting and that highlighted enemy is your `softenemy` but not your actual `target`.

**Comment by Blujelly87** [comment]
Does this help? Action targeting is also off

<img width="283" alt="Untitled" src="https://user-images.githubusercontent.com/116963975/227711280-08936122-f2ac-4889-821c-72727013c33c.png">

https://pastebin.com/QLGkUjHT

**Comment by Blujelly87** [comment]
Done some more changes and what not, changed the setting to show separately & Rebuke appears how & when it should.

If you have this setting off & keep it in the main time line, I'm not sure if it's being pushed into the mix. first screen shot/paste is 'show separately' 2nd is without. To be honest I've never used show separately & I much prefer it now then before, not sure if this still a problem and can be a later on fix?

<img width="468" alt="Screenshot 2023-03-25 at 11 02 08" src="https://user-images.githubusercontent.com/116963975/227713376-ff852561-6bc9-4150-90d9-7a0dcfe5a460.png">

https://pastebin.com/aFSmckDN
https://pastebin.com/JAHPN95v


<img width="315" alt="Untitled" src="https://user-images.githubusercontent.com/116963975/227713867-13a2cc7b-c76b-4256-9a15-efea364d533b.png">

https://pastebin.com/D4mzGspT

**Comment by DXtremz** [comment]
I am experiencing the same issue. Rebuke is not showing up on the timeline, action targeting is not enabled.

**Comment by Hekili** [comment]
Thanks, this will be fixed in today's release.
