### ISSUE TITLE
Fel Eruption havoc DH

### ISSUE THREAD

**Issue by PettyPeterPettigrew** [Hekili/hekili#249]
Please describe your idea or feature and when it would be useful.
Hi
Does anyone know why the Havoc DH rotation never tells you to use Fel Eruption? The talent is used by all the top DH, but I cant find anywhere in the settings to make it show

**Comment by Hekili** [comment]
Fel Eruption is really a utility ability; if you sim yourself, you'd notice your sim doesn't use it either.

The addon is aware that the ability exists, so you could add it to a custom priority if you desire, but you'd have to figure out when (under which circumstances) you would want it recommended.

More often, aside from interrupts, it's best to just use your judgment for utility abilities such as stuns.  You wouldn't want the addon to recommend it as it comes off cooldown on a dying enemy when there's a stunnable caster in the next pack.
