### ISSUE TITLE
Assassin Rogue with Arterial Precision isn't recommending shiv at all right now

### ISSUE THREAD

**Issue by Johnnytako** [Hekili/hekili#2491]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Assassin rogues that are using the arterial bleed talent, hekili is no longer recommending shiv at all.  From my experience this is a dps loss for this particular setup

### How to Reproduce

1. Enter the game as a sin rogue.  Use the build that has arterial precision.   BMQAAWulQAmRd/c4Iy2r7VOUFgkIJJJClEAAAAAAAJBQiAAAAAAAINk4AlkQSSSKBiQSERSSA
2. Use Indiscriminate carnage on the 5 target dummies, get all bleeds up.  Normally it would recommend shiv (which is a 20% damage increase on bleeds for 4 targets, there is no recommendation whatsoever for shiv in the current build.  I ran an entire key and it never had me shiv once.

### Snapshot (Link)

https://pastebin.com/NUaTx9wj

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wSBKSMqsXS3Kut7oX4az4Z

### Contact Information

sp4m_4_me@hotmail.com

**Comment by Hekili** [comment]
Thanks; I see that there is a missing entry for Shiv for Arterial Flow.  I'll correct it.

**Comment by Hekili** [comment]
This will be addressed in today's release.
