### ISSUE TITLE
WW Monk - "Touch of Death" is no longer recommended

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2492]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

According to the simulations on raidbots: https://www.raidbots.com/simbot/report/2MC3arbEikwWjk8885b79c I should have at least 9% Touch of Death damage, but for the whole rotation this spell was not recommended even once. I did it on 5-target dummies in Valdrakken.

### How to Reproduce

1. Enter the game as ww monk
2. Use talents I put bellow
3. Try aoe rotation on 5 dummies 

### Snapshot (Link)

https://pastebin.com/Ya3me2TY

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2MC3arbEikwWjk8885b79c

### Additional Information

I made two snapshots, there is the second in about 1 minute of fight: [https://pastebin.com/aRJrSVX2](https://pastebin.com/aRJrSVX2)

**Comment by Hekili** [comment]
Thanks; this will be adjusted in the next release.
