### ISSUE TITLE
[BUG] Resto druid starsurge talent not working.

### ISSUE THREAD

**Issue by f1ns** [Hekili/hekili#2493]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I disabled all addons to test this and tried all previous 10.0.7 hekili versions (deleting hekili.lua in the downgrade process to reset config) none worked.
![WoWScrnShot_032623_023031](https://user-images.githubusercontent.com/11728967/227757295-15b4a09a-8f41-41f4-83c4-a5c33aa0c6b1.jpg)

![WoWScrnShot_032623_023045](https://user-images.githubusercontent.com/11728967/227757306-1f4f5822-1e2f-4498-b5e2-4617e0610c53.jpg)

![WoWScrnShot_032623_023058](https://user-images.githubusercontent.com/11728967/227757327-2813735f-8b69-4415-93a7-84e8fa668096.jpg)
![WoWScrnShot_032623_023102](https://user-images.githubusercontent.com/11728967/227757330-f6659c21-bc06-482d-a287-c606bc7a8955.jpg)
![WoWScrnShot_032623_023117](https://user-images.githubusercontent.com/11728967/227757333-0614889b-3df7-417c-9c63-e35f0c5f4db6.jpg)

### How to Reproduce

just create a Starsurge action as resto druid.

### Player Information (Link)

https://pastebin.com/XpxEqHjd

### Error Messages (Link)

no error

### Contact Information

marcossteele@gmail.com

**Comment by Hekili** [comment]
Wrong ticket. Please read the ticket descriptions before submitting. I'll need a snapshot, which is explained in the Recommendations ticket instructions.

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
I went ahead and dug into this on a Druid alt and found the non-Balance form of Starsurge for Restoration was still requiring AP.  It'll be addressed in my next release.
