### ISSUE TITLE
Request: If Ice Floes is active, allow hardcasts of Fireball and Pyroblast while moving

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#2495]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

10.0 lot of  combat inmoving, more FireMage choose ice_floes talent because there is a Pyroblast that must be cast long. checked Scorch instead Fireball/Pyroblast in moving, It doesn't care if you had the buff, Scorch is still recommended. 

So it is recommended that this option is invalid when the player has the buff.

Thx

**Comment by Hekili** [comment]
This will be in the next release.
