### ISSUE TITLE
[REC] Assassination using Garrote 4x in Opener

### ISSUE THREAD

**Issue by xClow** [Hekili/hekili#2496]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Recommending I garrote 4 times in a row on the opener, i tried to capture it on the 4th garrote but am not sure if I got it. I can submit another snapshot if i didn't.

![image](https://user-images.githubusercontent.com/8822671/227839705-468cb390-5bc2-4740-b66c-bdccfbf125ae.png)

This is what the rogue discord faq says I should be doing. Any advice?

### How to Reproduce

Enter game as rogue
Change to assassination
Stealth and start using hekili

### Snapshot (Link)

https://pastebin.com/NBWAmshX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/59xCH8jZUr1epf6B3LFyKG

### Contact Information

rhet#0069

**Comment by xClow** [comment]
Couple more instances of pressing garrote 2 times in a row on opener and it suggesting a 3rd then 4th. What happens is i'll hit garrote, the icon for garrote stays, i hit it again, repeat

https://pastebin.com/hLuCQjr5
https://pastebin.com/zjKkkvRY
https://pastebin.com/hXpTgz5Y

During testing it generated an auto-snapshot which ill place here but could open a new ticket if needed. https://pastebin.com/7CtsWTti

**Comment by Hekili** [comment]
Just a quick note, you aren't using the latest version of the addon in these snapshots but I don't think there are any changes in the latest that would resolve this for you.

> This is what the rogue discord faq says I should be doing. Any advice?

It looks like the FAQ and sim agree with each other, so I'll look at the sim.  FAQs and guides are too often out of sync with what's proven or tested with sims to rely on them alone.  Thanks for linking a sim.  It looks like the Garrote entry the addon is using, but the sim is ruling out, is:

```
garrote,target_if=min:remains,if=stealthed.improved_garrote&!will_lose_exsanguinate&(remains<12%exsanguinated_rate|pmultiplier<=1)&target.time_to_die-remains>2
```

In the addon, these values are:

```
15.  garrote ( stealthed - 2 )
...
 - this entry's criteria PASSES: stealthed.improved_garrote[true] & ! will_lose_exsanguinate[false] & ( remains[22.34] < 12 / exsanguinated_rate[1.00] | pmultiplier[1.00] <= 1 ) & target.time_to_die[300.00] - remains[22.34] > 2
```

It looks like the multiplier on Garrote is snapshotted wrongly, so it's trying to apply a stronger Garrote even though the one that was just applied should've been buffed.  I'll take a closer look.

**Comment by Hekili** [comment]
Oh, the above may be occurring vs. Training Dummies only, because they are constantly dying and the addon purges aura data on a death event.  Does this happen in real combat?

**Comment by Hekili** [comment]
Oh, the above may be occurring vs. Training Dummies only, because they are constantly dying and the addon purges aura data on a death event.  Does this happen in real combat?

**Comment by xClow** [comment]
> Oh, the above may be occurring vs. Training Dummies only, because they are constantly dying and the addon purges aura data on a death event. Does this happen in real combat?

Confirmed it did this on Terros and that's what made me check it on the dummy. I didn't grab a snapshot unfortunately but this is the timeline of casts on the log you can see right at the start where I did the garrote 4 times
https://www.warcraftlogs.com/reports/mB9fM7dnCQ1H68pA#type=casts&fight=19&source=11&view=timeline

**Comment by Hekili** [comment]
I'll probably post an alpha build for you to test further.  I made adjustments to the auditor that purges auras that seems to handle the dummies well.

**Comment by Hekili** [comment]
Is this still an issue with the latest release?

**Comment by xClow** [comment]
Issue resolved! Thank you
