### ISSUE TITLE
[Holy Paladin] Avenging Crusader not recommended

### ISSUE THREAD

**Issue by spawnpt** [Hekili/hekili#2498]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Avenging Crusader expected to be recommended when 5 holy power available / divine purpose proc and not on cooldown.

I believe it has to do with the change in 10.0.7 and the split of Avenging Wrath and Avenging Crusader, check snapshot
 line 216         1.   avenging_crusader ( default - 1 ) - talent [ avenging_wrath ] disallowed

I tested with and without cooldowns on, with and without exception for avenging wrath and avenging crusader.

### How to Reproduce

1. Enter game as Holy Paladin
2. Play Avenging Crusader with Avenging Wrath and Zealot's Paragon
3. Avenging Crusader will never get recommended, this was also tested using a custom APL containing actions+=/avenging_crusader,if=!buff.avenging_crusader.up as the fist input 

### Snapshot (Link)

https://pastebin.com/DTXP5UyT

**Comment by Hekili** [comment]
This has been resolved in the latest release.
