### ISSUE TITLE
Fire Mage: Pyroblast recommended after Scorch with Searing Touch without Heating Up active

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#2501]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

FireMage When the searing_touch talent is used, when the target's hp below 30%, and no heating_up and pyroclasm id 269651[buff], Pyroblast will be recommended after Scorch.

In the actual game process, this is not the only situation that will lead to the recommendation of Pyroblast.
Pyroblast is recommended too much without any buff. resulting in multiple cast long time in combat.

### How to Reproduce

1. FireMage.
2. searing_touch talent is used.
3. target's hp below 30%.
4. cast Scorch

### Snapshot (Link)

https://pastebin.com/kdBDXPX2

### Additional Information

![WoWScrnShot_032823_011050](https://user-images.githubusercontent.com/59405956/228021404-d10fc8d4-ee3e-4276-87bb-5dc37a86de2f.jpg)

**Comment by Hekili** [comment]
I tried to fix your title into a summary.  Can you clarify if that's correct and revisit the "Describe the Issue" section?

I really need a ticket to cover (1) what you're seeing, (2) what's incorrect about it, and (3) what you should be seeing instead.  I think I have it sorted, but I don't think the snapshot you provided matches the screenshot you've provided, though I don't read your language.  

You're reporting that you're using Scorch and the addon recommends Pyroblast, but you don't have Heating Up (so the Scorch won't proc Hot Streak).

In the snapshot:
1. You are currently hardcasting Pyroblast (3.94 seconds remaining).
2. Heating Up is applied and has 8.93 seconds remaining.
3. Scorch is recommended with the Pyroblast cast finishes.

I think the snapshot is just taken too late.  You'd want to get the snapshot when Pyroblast is being recommended, you're casting Scorch, and Heating Up is not active.  

You could also make your Primary display show multiple icons so both steps of the Scorch > Pyroblast recommendation is captured at once.

**Comment by Hekili** [comment]
I did some investigating on my own; it looks like entry 11 in the `standard_rotation` action list is really written for sim behavior and doesn't align with how the addon can present information.

![image](https://user-images.githubusercontent.com/9438134/228056872-bea103b6-efaf-40a2-bf15-a0b9a8f980c4.png)

If you open that entry and uncheck Enabled, you should be fine.  Actual usage of Pyroblast with Hot Streak active is handled in a different entry.

**Comment by Hekili** [comment]
This is built in to the latest release.
