### ISSUE TITLE
[REC] Enhancement weird recommendation

### ISSUE THREAD

**Issue by fietsDEV** [Hekili/hekili#2502]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi!

If i check my logs and check logs of other enhancement shamans, the priorities in damage done are nearly completely different. Parses are not that nice. Also with like really perfect positioning.

### How to Reproduce

My Log: https://prnt.sc/9oLSOx35Im7L
Better Log: https://prnt.sc/wuQXyQ6Qpv1H

### Snapshot (Link)

-

### Raidbots Sim Report (Link)

-

### Contact Information

fiets#8205

**Comment by Hekili** [comment]
Sorry, there's nothing I can do for you with regard to this feedback.  There's not even information that allows me to confirm we're comparing apples to apples.
