### ISSUE TITLE
[Priest][Shadow] AoE - vampiric touch doesnt actually recommend any target cycle

### ISSUE THREAD

**Issue by phatzz** [Hekili/hekili#2503]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Step #2 of AOE action list for shadowpriest should be recommending target cycling vampiric touch but never actually generates a cycling indicator with standard settings.

### How to Reproduce

1.Enter game as shadowpriest
2.Go into combat with 2 + enemies with target swaps recommending and shadow crash disabled from the addon

### Snapshot (Link)

https://pastebin.com/2DbuzbRj

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jWXjdTHa1uupLsmSvokRoL

### Additional Information

Behavior similar to sim with "skip_actions=shadow_crash" input should be expected, allowing user to follow recommendations and throwing shadow crash when it is a good time to do so.

**Comment by Hekili** [comment]
You didn't provide an actual snapshot.  A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by phatzz** [comment]
> You didn't provide an actual snapshot. A snapshot is required to diagnose this issue.
> 
> ## Snapshot
> Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.
> 
> * Log into your WoW character.
> * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
> * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
>   
>   * You can change these keybindings in /hekili > Toggles if needed.
>   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
> * Type /hekili and press Enter.
> * Open the Snapshots section on the left side.
> * Select the snapshot that shows the recommendation that you disagree with.
>   
>   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
> * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
> * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
> * Provide the Pastebin _**link**_ in a new comment.
> 
> This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems. If you do not provide this information, I cannot triage your problem.

My apologies for not providing a proper snapshot. Here it is, at a time where we have vampiric touched the first target after entering combat, and would expect target cycling to apply VT to the remaining 4 targets to appear shortly after.
https://pastebin.com/pvTHPEKx < taken after first VT, the sim spends a few more globals then starts cycling
https://pastebin.com/kWinFV1w < taken later on in combat, around when the sim starts cycling

**Comment by Hekili** [comment]
Thanks for the snapshots; they definitely helped.

I have made adjustments to how target cycling fakes buffs based on number of active applications.  I'm posting an alpha build (v10.0.7-1.0.6-alpha1) because this can have significant impacts to other specs that need to be explored.  I also needed to tweak the default Shadow priority itself to cope with Shadow Crash being unknown or disabled, so that the remaining logic worked as expected.

Give 1.0.6-alpha1 a try and let me know if it is closer to your expectations.  If not, or if you get errors, please capture new snapshots and/or error messages and report back.  Thanks!

**Comment by phatzz** [comment]
Initial dummy tests are performing just as expected - will do some dungeons and test.

**Comment by Hekili** [comment]
In my testing, the target cycling for Mind Sear seems pretty nonsensical.  In the sim, it would swap targets to pick the one where you'd hit the most targets with Mind Sear, but the addon cannot actually tell that.  I'll probably remove it.

**Comment by phatzz** [comment]
> In my testing, the target cycling for Mind Sear seems pretty nonsensical. In the sim, it would swap targets to pick the one where you'd hit the most targets with Mind Sear, but the addon cannot actually tell that. I'll probably remove it.

Ah, i figured this was to make sure we were refreshing dots with low duration with mental decay - but it does seem to just be a seemingly random cycle.

**Comment by Hekili** [comment]
This appears resolved; the change to Mind Sear has also been published.  Thanks!
