### ISSUE TITLE
[REC] Feral rotation suggesting Mark of The Wild

### ISSUE THREAD

**Issue by PARADOX070** [Hekili/hekili#2504]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Feral rotation suggesting Mark of The Wild, not much more to add here.

### How to Reproduce

Follow the rotation, and eventually it will be suggested.

### Snapshot (Link)

https://pastebin.com/Nn9q39yA

**Comment by Hekili** [comment]
Yep, that'll happen in the current alpha.  It doesn't happen in the current release, and will be resolved in the next alpha.

**Comment by Hekili** [comment]
This is resolved in the current release.
