### ISSUE TITLE
[REC] Ret Pally Consecrated Blade

### ISSUE THREAD

**Issue by NokuraWoW** [Hekili/hekili#2507]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon recommending Consecrated blade but its not an ability we can press. 

### How to Reproduce

Talent into consecrated blade. 

### Snapshot (Link)

https://pastebin.com/yU7XVkBi

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6U38XWjUYLmSUk9Mss2SeU

### Contact Information

Nokura#1874

**Comment by Hekili** [comment]
Closed per Discord chat.
