### ISSUE TITLE
Fire Mage:  sometimes continuous recommend Fireball, even the hot_streak buff on

### ISSUE THREAD

**Issue by Livvvvvvven** [Hekili/hekili#2508]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I don't know how to reproduce this doesn't happen all the time, but not infrequently.
What happens is roughly that when current target is above 30% hp and another unit is below 30%.
I will cast scorch to the unit hp below 30%. After that, it will always be recommend Fireball.

From the two screenshots,  that I cast scorch 14 times, whether hot_streak buff on, will always be recommend Fireball

![WoWScrnShot_040223_112300](https://user-images.githubusercontent.com/59405956/229329865-0e25420e-8ccb-46fb-aed6-c9422056e4fb.jpg)

![WoWScrnShot_040223_112306](https://user-images.githubusercontent.com/59405956/229329868-da3264ee-1b0a-4053-918c-21b6d8070fad.jpg)

### How to Reproduce

1. Fire Mage.
2. More than 2 targets, the current target's HP is higher than 30%, and another is lower than 30%.
3. When recommending Fireball, cast scorch to unit which hp less than 30%.

### Snapshot (Link)

https://pastebin.com/XS5G8WCk
https://pastebin.com/yKsNcVEN

**Comment by Hekili** [comment]
This issue is downstream of the change made from your previous ticket.  I've re-enabled the line in question but made it check for Hot Streak instead of Heating Up.  This will be addressed in today's release.
