### ISSUE TITLE
[REC] Ret Paladin AoE Opener

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2509]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The opener deviates from the sim opener. I'm not sure if its neutral or not(not great with changing the APL).
Hekili will recommend Judgment=> BoJ=> Avenging Wrath => Divine Storm => Wake of Ashes => DS 

It can vary slightly from pull to pull based on procs but the big difference is it spends down after Avenging Wrath where as the sim uses Templar Strike then goes into Final Reckoning 2-3 GCDs faster than Hekili. 

The sim will go as follows:
![image](https://user-images.githubusercontent.com/25187247/229332236-70cd06f6-8322-47f3-8116-6c60e634ef86.png)

### How to Reproduce

Ret Paladin
Go to Valdrakken dummies.
Follow opener Judgment=> BoJ=> Avenging Wrath=> 

### Snapshot (Link)

https://pastebin.com/9LbfFcFW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/7AtXHTR1YcS6Qp9RAXyFDg

### Contact Information

Theo#2455

**Comment by Hekili** [comment]
Since you're reporting an issue involving multiple steps, I'll need your snapshot to show multiple steps.  Set your display's number of recommendations to 10 just for the purposes of snapshotting, then link that here.  Thanks!

**Comment by Hekili** [comment]
Also, make sure to revert to the default priority when snapshotting, and confirm you're using the latest release.

**Comment by Bingo176** [comment]
Yep. Late night moment of overthinking something. No issue :) Apologies

**Comment by Hekili** [comment]
Just for reference, with similar talents to you, here is my opener:

![image](https://user-images.githubusercontent.com/9438134/229334060-27995c70-4352-46b4-a0d6-8ba6fe7e37a7.png)

However, if I put Final Reckoning on a disabled toggle, I see:

![image](https://user-images.githubusercontent.com/9438134/229334082-fa5b8081-99e4-49c4-aa4b-0cb72c65ec66.png)

:)

**Comment by Bingo176** [comment]
Yea. I just need to use the custom toggle to disable when I want to hold it. Something's you can get away with just moving them but others break it( I understand why). Just being greedy I guess.

**Comment by Hekili** [comment]
I'm not sure what makes it seem "broken" -- you told it to hold Final Reckoning, so it did.  The Divine Storm cast is held when Final Reckoning is ready in a couple of GCDs; when it's toggled off, it's not ready in a couple of GCDs.

> actions.finishers+=/divine_storm,if=variable.ds_castable&!buff.empyrean_legacy.up&!(buff.divine_arbiter.up&buff.divine_arbiter.stack>24)&((!talent.crusade|cooldown.crusade.remains>gcd*3)&(!talent.execution_sentence|talent.divine_auxiliary|target.time_to_die<8|cooldown.execution_sentence.remains>gcd*2)&(!talent.final_reckoning|talent.divine_auxiliary|**cooldown.final_reckoning.remains>gcd*2**)|buff.crusade.up&buff.crusade.stack<10)
