### ISSUE TITLE
Bloodtalons for Feral used correctly?

### ISSUE THREAD

**Issue by Tramquor** [Hekili/hekili#251]
First of all i want to thank you for you hard and amazing work. I tried to check for existing issues, however i came up blank.

For me it appears as if the addon doesnt suggest the correct use of Bloodtalons. For instance, it almost never recommends me to use a BT before a Rip-Cast and tells me to refresh Rip even at full duration sometimes. Is my Addon broken or is this really a problem with Hekili/simc?

Thank you very much !!

**Comment by Hekili** [comment]
You'd need to follow the ticket instructions to submit a snapshot showing when this is actually happening.

I play Feral and the addon uses BT properly.  Have you made any modifications?
