### ISSUE TITLE
Guardian druid not recommending defensives in the mage tower

### ISSUE THREAD

**Issue by Aldwew** [Hekili/hekili#2511]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon does not recommend using frenzied regeneration, ironfur, survival instincts or renewal in the mage tower.

### How to Reproduce

1. Go to the mage tower as a guardian druid

### Player Information (Link)

https://pastebin.com/m6Q1Lak9

### Error Messages (Link)

-

**Comment by Hekili** [comment]
Wrong ticket.  See: 
![image](https://user-images.githubusercontent.com/9438134/229818151-ec3cc23a-8d00-4d53-bb54-779afd7c9e3c.png)

You can add the missing information here or open a new ticket and I'll close this one.
