### ISSUE TITLE
[REC] Ret Paladin - Showing the Consecrated Blade icon after dying in a key

### ISSUE THREAD

**Issue by xClow** [Hekili/hekili#2513]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I tried to grab a snapshot but took a screenshot instead T_T doing another key will grab a screenshot if I die. 

Would just showthe consecrated blade icon and if i tried to ignore it it just never recommended cooldowns again until I did a /rl

https://i.imgur.com/Tm5Pkig.png

### How to Reproduce

Enter game as Ret Paladin
Enter key
Die in key
Try rotation
Reload UI to fix

### Snapshot (Link)

https://i.imgur.com/Tm5Pkig.png

**Comment by Hekili** [comment]
That's not a snapshot.  A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
Additional information that would be useful after you replicate this:

1. `/dump Hekili.State.talent.consecrated_blade`
2. `/dump Hekili.State.talent.blessed_hammer`

The snapshot will include that information, as well.  But I can confirm that Consecration checks for both of those talents, so the issue is probably that rezzing or brezzing is causing talent detection to run again (and pull incorrect data).  The snapshot is still critical here.

**Comment by xClow** [comment]
Sorry will keep trying today. 

I've done 5-6 tests in a +2 key and couldn't get it to happen again so it may have been a one-off fluke

**Comment by Hekili** [comment]
Thanks for testing.  I'll leave this open in case it pops up.  I would almost guarantee that there's an error/warning that occurs when it tries to get talents and fails, which would be included in the snapshot, too.

The easiest way to get the snapshot without slowing yourself down further is `SHIFT-ALT-[` by default; it won't even pause the display.  You can change that in /hek > Toggles.
