### ISSUE TITLE
[BUG] Fury Warrior Priority List doesnt show Ravager or Spear of Bastion also it doesnt count my enemies in range correctly.

### ISSUE THREAD

**Issue by Orillien** [Hekili/hekili#2517]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

No matter what i do in my priority list. It never shows me Ravager or Spear of Bastion. Like it doesnt even exist. Also Hekili always thinks im fighting against exactly one enemy. Not even if i fight 5 dummies with whirlwind. Commands like "active_enemies > 1" doesnt work. Its always false because it count always only one enemy. No matter what setting i change for that. I only managed to make the opposite bug so Hekili always thought i fight 5 enemies even i fight only one dummy. 

When im login into my enhancer shaman, Hekili works absoluty perfect with the counting of enemies in my range or what number i fighting right now. But just not with Fury Warrior. 
![active_enemies_bug](https://user-images.githubusercontent.com/92847025/230596786-063ccb4c-d8bc-40b3-b057-96cb1af35daa.jpg)
![spear of bastion and ravager bug](https://user-images.githubusercontent.com/92847025/230596799-9469f28b-b3da-4b07-84ed-11246d437950.jpg)

### How to Reproduce

1. Login Fury Warrior
2. Do any thing in your priority list
3. Add the condition "active_enemies > 1(or whatever number you want)"
4. Enjoy Lord of the rings while you fight against 5 dummies and the wanted ability never shows up.
5. Hover over the conditions box while fighting 5 dummies and Hekili says its false because it count only one enemy.
6. crying
7. Do the same with Ravager or Spear of Bastion even with no conditions and they also never shows up.

### Snapshot (Link)

https://pastebin.com/GZh5JWE0

**Comment by Hekili** [comment]
You only have one visible nameplate, so the addon has no way to track the additional targets using nameplate detection.  You could either:

1. Show all (hostile) nameplates; I think that's `/run SetCVar( "nameplateShowAll", 1 )`.
2. In /hek > Fury > Targeting, turn off Nameplate Detection and turn on Damage Detection.  That'd count enemies after you hit them.

In your snapshot, I see neither Spear of Bastion nor Ravager talented.  Is that incorrect?

**Comment by Orillien** [comment]
"In your snapshot, I see neither Spear of Bastion nor Ravager talented. Is that incorrect?" that is correct but my friend who got it has the same problem. im just the guy who try to help him and asked here to get help. And im sure i tested that setting with the nameplates but i cant try it again.

**Comment by Hekili** [comment]
Your snapshot won't help diagnose his problem, but your screenshot definitely shows that you're not showing all those enemy nameplates.

![image](https://user-images.githubusercontent.com/9438134/230623879-eca28e79-33fa-4769-b82f-26b1a8a1f87c.png)

There's one nameplate.

**Comment by Orillien** [comment]
"In /hek > Fury > Targeting, turn off Nameplate Detection and turn on Damage Detection. That'd count enemies after you hit them."

I let my friend try it but it doesnt change anything.

**Comment by Hekili** [comment]
He'll need to provide his own snapshots.

**Comment by Orillien** [comment]
You want come discord and he show you in stream ? But it worked with the nameplates after he activated all. But the second option you told me to do with the Damage Detection still doesnt work. Fix this please or delete the option which doesnt do anything. But i think this ticket can be closed for now.

**Comment by Hekili** [comment]
No, it works, it just doesn't apply if Nameplate Detection is enabled.
