### ISSUE TITLE
[BUG] Error on Level Up

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#2519]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Getting error on Level Up

### How to Reproduce

Level Up

### Player Information (Link)

https://paste.gg/p/anonymous/3c3c633a0d2b492f8fdfb7360761b01a

### Error Messages (Link)

https://paste.gg/p/anonymous/56f72189df8f4979bc16b1d202a81dbf

**Comment by Hekili** [comment]
Thanks.  I'll sort this out, but it's just a very low level issue (because you don't have talents yet).
