### ISSUE TITLE
boss fights

### ISSUE THREAD

**Issue by mspykerez** [Hekili/hekili#252]
First off I see you closed my ticked #63 regarding 'account for movement', you should look at my comment there and see why I have a different opinion on that.
I also commented on closed ticked #61 and #230 if you want to take a look.

This leads me to another suggestion which is to utilize Bossmods timers (DBM/Bigwigs) to recommend us when to hold or use important CDs or abilities. This would optimize DPS by answering questions like: Should I hold CDs for phase transitions ? for adds ? for when Heroism/Bloodlust (insert phase of the fight when this will be up) is up ? Sure you don't want to use/waste your CDs/abilities before the boss gets immune for some reason or for when you need to do a mechanic that does not allow you to dps properly. If it is to much to just integrate it with boss mods, then I think you could just break a boss fight by phases and allow us an option to make the addon to suggest a pre-determined ability/cd/defense on an interval after X seconds on said phase or when boss reaches X% health or uses a specific ability, something along this lines.

Finally I would like to mention if it is possible to add a build-in sort of 'mini-guide' with the best talents and gear to use based on boss fight? Like having a preset of the best talents and BIS gear we should aim for as a basic reference guide which can also be custom made and shareable.

**Comment by Hekili** [comment]
No, this is outside the scope of the addon. You can manually toggle cooldowns on/off at your discretion. I don't want to automate around boss mechanics and make recommendations that may or may not match players' raids' strategies.
