### ISSUE TITLE
[REC] Outlaw Rogue - Cold Blood being recommended before Slice and Dice

### ISSUE THREAD

**Issue by HavocR88** [Hekili/hekili#2520]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Cold Blood (100% Crit on next ability) is being recommended before Slice and Dice (Increase ATKSPD 50%), which makes you consume the Cold Blood on your next combo generating ability, instead of on a damage finisher like Dispatch.

### How to Reproduce

1. Enter game as a Outlaw Rogue.
2. Take the Cold Blood talent.
3. Start combat and build combo points.
4. Cold Blood will come up in recommendations.
5. Slice and Dice will be next, instead of a damage finisher.

### Snapshot (Link)

https://pastebin.com/XGJWY2mD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tSLtGeQwoBiLd3dxV9WyqS

### Contact Information

Discord: HavocR24#2761

**Comment by Hekili** [comment]
The issue here is that there's 0.25s until the GCD expires and Slice and Dice would be used, but Cold Blood is off GCD so it's available sooner.  I'll take a look at preventing this.
