### ISSUE TITLE
[BUG] Shadowbolt being recommended with 5 Shards

### ISSUE THREAD

**Issue by caim0414** [Hekili/hekili#2521]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When preparing for Tryant, it will have you sit at 5 SS and spam SB. 

### How to Reproduce

1. start combat with something and when you go into your 2nd Tyrant, you will likely see the issue start. so maybe 90 sec into combat.

### Player Information (Link)

https://pastebin.com/tMsdsYCm

### Error Messages (Link)

https://pastebin.com/YSQv5DiD

### Contact Information

Hᴵᴿᴼ#5438

**Comment by Hekili** [comment]
This should be resolved in the latest release.
