### ISSUE TITLE
Druid Feral CAT , Omen Proc dont give prio to Shred and RIP has no prio over FFF untill reaching 90 energy

### ISSUE THREAD

**Issue by Psihotank** [Hekili/hekili#2522]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

1. When OMEN Procs, if RIP is ready to be casted with 5cp and enough Energy, Icons dont switch, meaning RIP Still stays as 1st recommendation comparing to SHRED.  
*****to fix this : As soon as OMEN Procs, Shred Icon should appear, no matter what. ****
2. When RIP is ready to be casted (with 5cp and more than 30 energy), if FFF is also ready to be casted, RIP will NOT be shown as prio over FFF. This way whole RIP Tick is 'lost', comparing to 7 energy loss if RIP is casted before FFF+Shred. Correct behaviour appears only when energy gets to 90. (then RIP icon comes as 1st recommendation, before FFF Icon).
***** to fix this: RIP should be PRIO over FFF after 30 energy****
Thank you for great Addon!! Please fix this to further improve it! 
Psihobeast from Gehennas

### How to Reproduce

1. Just use standard rotation on targe dummy as feral, youll see that when FFF and 5Cp RIP are both off CD (ready to be casted), FFF icon will be 1st in line, and RIP 2nd in line, untill energy reaches 90. Thats wrong. after 30 energy, RIP Icon should appear 1st. 

### Snapshot (Link)

https://pastebin.com/vftRgUK7

### Contact Information

Psihobeast#2524

**Comment by zmsl** [comment]
@Psihotank please try refreshing your profile as mentioned in the Druid Classic Discord.

**Comment by Psihotank** [comment]
How is it exactly done?
I have to enter app and then click where?
Thanks

Sent from my BlackBerry - the most secure mobile device
From: ***@***.***
Sent: April 9, 2023 14:29
To: ***@***.***
Reply-to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [Hekili/hekili] Druid Feral CAT , Omen Proc dont give prio to Shred and RIP has no prio over FFF untill reaching 90 energy (Issue #2522)


@Psihotank<https://github.com/Psihotank> please try refreshing your profile as mentioned in the Druid Classic Discord.

**Comment by zmsl** [comment]
Enter the Hekili settings by entering /hek or /hekili into the chat, then click into the 'Feral DPS (IV)' profile.

**Comment by Hekili** [comment]
This has been resolved in a recent release.

**Comment by Psihotank** [comment]
Yes, I am glad I helped!
Cheers!

Sent from my BlackBerry - the most secure mobile device
From: ***@***.***
Sent: April 10, 2023 18:24
To: ***@***.***
Reply-to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [Hekili/hekili] Druid Feral CAT , Omen Proc dont give prio to Shred and RIP has no prio over FFF untill reaching 90 energy (Issue #2522)


This has been resolved in a recent release.
