### ISSUE TITLE
[REC] Shadow Bolt used at 5 shards when HoG conditions not met in Tyrant window

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#2523]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shadow bolt is being recommended while shards are maxed and demonic cores are available
![WoWScrnShot_040923_110231](https://user-images.githubusercontent.com/7343912/230791675-0cff2c01-8ae9-4c87-89b5-bccdd3b844e7.jpg)

### How to Reproduce

1. Enter Game as Demonology Warlock
2. Use talents BoQA+63P9mnDJYMkogOeTUhr8CIJRSCkmCRaJJhUCAAAAAaRQCJaRSkI5ARaJROABAAAAAAJ
3. Go to training dummy with 1 target
4. Follow rotation until error

### Snapshot (Link)

https://pastebin.com/kVSYsw7j

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qsrwmybHYidrGNC7PmpWVp

### Contact Information

Lemonlust#4440

**Comment by Hekili** [comment]
Thanks.  The issue here is that the current priority refuses to use HoG to spend down shards there.  I'm actually testing a priority rewrite that seems to already account for this.  I'm going to test your specific build before posting an update.

**Comment by Hekili** [comment]
As noted in Discord, my version of the priority that avoids this issue is published in v10.0.7-1.0.9.  Please post a new snapshot if the same issue occurs again.  You can add to this (closed) ticket and I'll reopen if needed.

**Comment by JL907** [comment]
https://pastebin.com/shtbRGES

![WoWScrnShot_041323_002915](https://user-images.githubusercontent.com/7343912/231701929-1e1ced8d-4c4b-47f3-abd1-e925e587ee74.jpg)

Seems to be happening in the latest update. Here its recommending shadow bolt with 5 shards and 2 demonic cores available

**Comment by JL907** [comment]
![WoWScrnShot_041223_194705](https://user-images.githubusercontent.com/7343912/231703204-3a72fda4-251e-44ed-b6e9-668f88cdc6a9.jpg)

I wasn't able to get the snapshot for this one but it was recommending demonbolt at 5 shards here

**Comment by Hekili** [comment]
I'll need a snapshot to see specifics. Off the top of my head, I think the opener Demonbolt doesn't care about overlapping but I could make it do so.

**Comment by JL907** [comment]
> https://pastebin.com/shtbRGES

could you check this one this is for shadow bolt
