### ISSUE TITLE
[BUG] [WOTLK] Priority selector doesn't work correctly

### ISSUE THREAD

**Issue by rbleuse** [Hekili/hekili#2524]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I'm using latest version (3.4.1-1.8.4) but same bug with previous version

I use the auto Priority selector feature for my druid which is Feral tank MS and Feral dps OS
Every time I change spec the 'Feral tank' profile is always selected, even though MS has the Thich Hide talent but not OS so it should work as expected for OS to select the dps profile

### How to Reproduce

1. Enter game
2. Select Feral tank profile
3. Change talents from feral tank to feral dps
4. Feral tank profile is still selected

Tank pastebin : https://pastebin.com/HHxMR2pF
DPS pastebin : https://pastebin.com/0QZy9qzr

### Player Information (Link)

https://pastebin.com/0QZy9qzr

### Error Messages (Link)

No error

**Comment by Hekili** [comment]
Thanks for the report.  Defzach is working to resolve this and we'll post an update in a little bit.  In the meantime, /reload after a talent swap should suffice.

**Comment by Hekili** [comment]
Fixed in 1.8.5; publishing to CurseForge et al now.
