### ISSUE TITLE
[REC] Sub Recommendation Issue

### ISSUE THREAD

**Issue by xMaga** [Hekili/hekili#2527]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since the latest update, skills are no longer suggested after some time and the primary display disappears and comes back after a few seconds.
This only happens when im playing Subltety for Outlaw and Assa the reccomendations is fine

### How to Reproduce

Enter game as Sub Rogue.
Hit a Dummy Target or play some M+

### Snapshot (Link)

https://pastebin.com/KvTDRn49

### Additional Information

The Snapshot above is from a M+ run and below are from Target Dummies in Valdrakken
https://pastebin.com/PSBq2m33
https://pastebin.com/pSv3MkhU

**Comment by khelge** [comment]
Got this problem too. After the latest update yesterday (v10.0.7-1.0.9) the whole window recommending abilities act weird. I have it set to 3 abilities and it shows 3, but it suddenly sometimes only recommends 1 or 2 abilities. It even sometimes completely disappear (not recommending any ability and all the 3 icons disappear. Disappears every 10-20 seconds or something, you should be able to see the bug after 10-15 seconds of combat max. Something in the newest update broke sub rogue, it works fine on my boomkin

**Comment by Hekili** [comment]
Resolved in v10.0.7-1.0.10.
