### ISSUE TITLE
[REC] WOTLK - Blood DK not recommending heart strike when talented

### ISSUE THREAD

**Issue by dookmaster5000** [Hekili/hekili#2529]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I was following a leveling build for Blood DK in wrath of the lich king which recommended taking heart strike as a talent.  Functionally it replaced blood strike as your go-to blood rune spender for 1 - 2 targets.  When talented, Heart Strike is a significant dps increase over it's blood strike counterpart on 1-2 target scenarios, having some sort of recommendation to use it if active enemies = 1 - 2 (dunno the actual syntax) would help out.

Guide being used: https://www.warcrafttavern.com/wotlk/guides/death-knight-leveling-guide/
Build being used: https://www.warcrafttavern.com/wotlk/tools/talent-calculator/deathknight/?t=A001116644489999944cciiiggmmlllpooogsstttxyyyuEEEEEIB000226666688888ffAfff

### How to Reproduce

1. Enter game as Blood DK
2. Talent into Heart Strike
3. Open recommendation panel
4. Go to "Blood (IV)" tab
5. Got go Action List

### Snapshot (Link)

https://pastebin.com/KbZP7hB0

### Contact Information

slyther#5022 (discord)

**Comment by Hekili** [comment]
Yeah, Icy Veins doesn't recommend taking Heart Strike so their priority doesn't include it.  I'll go ahead and add it, though.
