### ISSUE TITLE
Keybindings not displayed

### ISSUE THREAD

**Issue by Vortilion** [Hekili/hekili#253]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
**- check**

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.
**- check**

**Describe the Bug/Issue**
the keybindings are not displayed, or rather not on all characters and for some characters only e.g. the keybindings of bar 2 are displayed. I am using bartender 4 for the action bars. keybindings on bar are there, visible and working. Not on Hekili though.

**Expected behavior**
All keybindings are visible

**WHEN SUBMITTING AN ISSUE:**
https://pastebin.com/peB7FYJw

**Comment by Hekili** [comment]
I'm honestly not even sure how to start troubleshooting this.  Lots of folks use BT4 without issue, as far as I know.

Are your bars laid out in some weird order?  Do bindings show up if you put abilities on bar 1?
