### ISSUE TITLE
[SPriest] Void Eruption / Void Bolt / PI / etc not triggering on Cooldowns

### ISSUE THREAD

**Issue by Kolanjian** [Hekili/hekili#2532]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Installed addon with fresh copy. Can't get Void Eruption / PI and other CDs to show up. Works fine for other characters or builds with DA instead of VE.

### How to Reproduce

1. Install fresh copy of addon
2. Log into game as max level shadow priest
3. Set talents to the following: BIQA16pR6xQxvK1VWhXk+w0/GkQSLRAAAAAAAAAAAAAISiSapJNIRSJJSEkGJJJSjgEESRahkAA
4. Hekili Toggles -> Show Cooldowns and Show Separately checked on.
5. Hekili Toggles -> Set Display Mode to Fixed Dual Display. Only have it checked off and set as Current Display Mode

![image](https://user-images.githubusercontent.com/9438134/231312987-ce5c501d-309c-4caf-9dfc-1ac8ab602443.png)

### Player Information (Link)

https://pastebin.com/Qh5wu6gi

### Error Messages (Link)

N/A

**Comment by Hekili** [comment]
This is not the correct kind of ticket; this should be a Recommendations ticket with snapshots taken when you wanted Void Eruption to be recommended but it wasn't.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
