### ISSUE TITLE
is it possible other WoW addon can interact with Hekili?

### ISSUE THREAD

**Issue by tangaiyun** [Hekili/hekili#2533]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

is it possbile Hekili emit some events then another addon can listen these event? for example, if Hekili finish updating the the first recommendation on the primary queue, it can emit a event which includes spellid, spellname, iconid,etc., then other addon can receive this event, it can play a specific sound depends on the spellname.

**Comment by phatzz** [comment]
Hekili already exposes most if not all of the parameters you are asking for, you can look at them using something like ViragDevTool.

**Comment by Hekili** [comment]
I currently send data to WeakAuras with the `HEKILI_RECOMMENDATION_UPDATE` pseudo-event.  There's no reason I can't or shouldn't register a proper callback system that other addons could use, but it's not something I've implemented.

phatzz is correct that all the current recommenation information is accessible within each display, i.e., `HekiliDisplayPrimary.Recommendations` has all its recommendation information, though it can be a bit volatile.
