### ISSUE TITLE
[BUG] Use "Pet-Based Detection" enemy count cannot work if place in Action Bar 6,7,8

### ISSUE THREAD

**Issue by nuttin0011** [Hekili/hekili#2534]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Use Pet-Based Detection enemy count cannot work if place in Action Bar 6,7,8

![image](https://user-images.githubusercontent.com/74884682/231706527-b2e69e3d-d1ae-4f9a-861b-2f6236a5cb6f.png)

it's work well if place in Action Bar 1-5

### How to Reproduce

i play Hunter and place pet skill "Smack" in player Action Bar 6-8
and use "Pet-Based Detection"

### Player Information (Link)

https://pastebin.com/ZDXi5wfR

### Error Messages (Link)

-

**Comment by Hekili** [comment]
Thanks for the report. I will need to revise how I deal with keybinds and button detection for those bars. I wasn't aware that it is impacting pet-based target detection as well.

**Comment by Hekili** [comment]
Which bar addon are you using, if any?  I can't replicate this with ElvUI action bars.

**Comment by nuttin0011** [comment]
> Which bar addon are you using, if any? I can't replicate this with ElvUI action bars.

Normal WoW UI.

**Comment by Hekili** [comment]
This will be fixed with today's release.  Thanks!
