### ISSUE TITLE
[BUG] fury warrior rotation (maybe i just don't understand how to use it)

### ISSUE THREAD

**Issue by Alausa124** [Hekili/hekili#2536]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

So i played before arms warrior and everything was fine, but now i switched to fury warrior and all i can see is rend, only 1 ability in rotation and when i use it it disapears and it shows nothing and after like 3 seconds it shows me it again, even if i have rage still i only can see 1 ability in rotation.

### How to Reproduce

![image_2023-04-13_211547562](https://user-images.githubusercontent.com/130696394/231848053-ffbb9be5-05dc-48c6-8ca2-16aaa9ceff80.png)

![image](https://user-images.githubusercontent.com/130696394/231848900-e68409d2-b904-44b0-88fd-a17c2c3153c7.png)
![image](https://user-images.githubusercontent.com/130696394/231848930-14652f68-c00e-439b-b026-5cee5b1c97f4.png)
![image](https://user-images.githubusercontent.com/130696394/231848949-c30bc35e-f285-4465-af9b-899b589e474d.png)
![image](https://user-images.githubusercontent.com/130696394/231848972-f2028b89-ce14-454a-990f-c5c4097e64e5.png)

video: https://medal.tv/games/wow-classic/clips/14tM3NFBFb_67M/d1337obU9jTp?invite=cr-MSxsTzgsMTY2MzgxNzg4LA

### Player Information (Link)

https://pastebin.com/kSrf2WWk

### Error Messages (Link)

no error message

### Contact Information

Ženka#2342

**Comment by Hekili** [comment]
Wrong ticket.  Use this link and provide snapshots.
https://github.com/Hekili/hekili/issues/new?assignees=Hekili&labels=recommendation%2Ctriage&template=Recommendation-Report.yml&title=%5BREC%5D+REPLACE+THIS+TEXT+WITH+YOUR+CLASS%2FSPEC+AND+BRIEF+ISSUE+DETAILS
