### ISSUE TITLE
[BUG] fury warrior rotation (maybe i just don't understand how to use it) 

### ISSUE THREAD

**Issue by Alausa124** [Hekili/hekili#2537]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

So i played before arms warrior and everything was fine, but now i switched to fury warrior and all i can see is rend, only 1 ability in rotation and when i use it it disapears and it shows nothing and after like 3 seconds it shows me it again, even if i have rage still i only can see 1 ability in rotation.

### How to Reproduce

![image](https://user-images.githubusercontent.com/130696394/231850681-5ec7d15e-df45-4b8a-9397-0b4bffec08c7.png)
https://medal.tv/games/wow-classic/clips/14tM3NFBFb_67M/d1337QRL8E72?invite=cr-MSxqMlcsMTY2MzgxNzg4LA

### Snapshot (Link)

https://pastebin.com/WneP0VbH

### Contact Information

Ženka#2342

**Comment by Hekili** [comment]
I can't open the snapshot you pasted to Pastebin; it's marked as private.  You'll want to capture the snapshot when you have Rage and are in combat and it will explain why it isn't recommending anything else.  I'll take a look.

**Comment by Alausa124** [comment]
How do i make it public?

**Comment by Alausa124** [comment]
Profile:
actions.precombat+=/berserker_stance,if=buff.stance.down
actions.precombat+=/commanding_shout,if=assigned_shout.commanding_shout&buff.my_battle_shout.down&buff.my_commanding_shout.down
actions.precombat+=/battle_shout,if=assigned_shout.battle_shout&buff.my_battle_shout.down&buff.my_commanding_shout.down

actions+=/call_action_list,name=init
actions+=/sunder_armor,if=variable.should_sunder&variable.emergency_sunder
actions+=/pummel
actions+=/run_action_list,name=berserker_stance,if=buff.berserker_stance.up
actions+=/run_action_list,name=battle_stance,if=buff.battle_stance.up
actions+=/run_action_list,name=defensive_stance,if=buff.defensive_stance.up

actions.init+=/variable,name=time_to_die,value=(debuff.training_dummy.up&300)|target.time_to_die
actions.init+=/variable,name=execute_phase,value=target.health.pct<20
actions.init+=/variable,name=should_slam_over_execute,value=!variable.execute_phase|settings.execute_slam_prio
actions.init+=/variable,name=should_bloodthirst,value=!variable.execute_phase|settings.execute_bloodthirst_enabled
actions.init+=/variable,name=should_whirlwind,value=!variable.execute_phase|settings.execute_whirlwind_enabled
actions.init+=/variable,name=should_sunder,value=settings.debuff_sunder_enabled&variable.time_to_die>((5-debuff.sunder_armor.stack)*(1.5+latency))+3
actions.init+=/variable,name=build_sunder,value=!debuff.major_armor_reduction.up|(debuff.sunder_armor.up&debuff.sunder_armor.stack<5)
actions.init+=/variable,name=maintain_sunder,value=!variable.build_sunder&debuff.sunder_armor.stack=5&debuff.sunder_armor.remains<7&cooldown.bloodthirst.remains&cooldown.whirlwind.remains&!buff.bloodsurge.up
actions.init+=/variable,name=emergency_sunder,value=debuff.sunder_armor.up&debuff.sunder_armor.remains<1.5
actions.init+=/variable,name=should_weave,value=cooldown.bloodthirst.remains>=settings.weave_cooldown_threshold&cooldown.whirlwind.remains>=settings.weave_cooldown_threshold&cooldown.recklessness.remains>1.5&cooldown.death_wish.remains>1.5&!buff.bloodsurge.up&!buff.recklessness.up&!buff.death_wish.up&rage.current<=weave_rage_threshold&target.health.pct>=settings.weave_health_threshold
actions.init+=/variable,name=should_rend,value=variable.should_weave&rage.current>=10&debuff.rend.remains<=settings.rend_refresh_time
actions.init+=/variable,name=should_overpower,value=variable.should_weave&rage.current>=20&(buff.overpower_ready.up|buff.taste_for_blood.up)
actions.init+=/variable,name=weave_now,value=settings.weaving_enabled&(variable.should_rend|variable.should_overpower)

actions.berserker_stance+=/bloodrage,use_off_gcd=1,if=rage.deficit>20
actions.berserker_stance+=/heroic_strike,use_off_gcd=1,if=rage.current>=settings.queueing_threshold&active_enemies=1&!buff.recklessness.up&(!variable.execute_phase|settings.execute_queueing_enabled)
actions.berserker_stance+=/cleave,use_off_gcd=1,if=rage.current>=settings.queueing_threshold&active_enemies>1&!buff.recklessness.up&(!variable.execute_phase|settings.execute_queueing_enabled)
actions.berserker_stance+=/sunder_armor,if=variable.should_sunder&(variable.build_sunder|variable.maintain_sunder)
actions.berserker_stance+=/death_wish,if=debuff.major_armor_reduction.up&!debuff.sunder_armor.up|debuff.sunder_armor.stack=5
actions.berserker_stance+=/use_items,use_off_gcd=1
actions.berserker_stance+=/hyperspeed_acceleration,use_off_gcd=1
actions.berserker_stance+=/slam,if=buff.bloodsurge.up&main_gcd_spell_slam&variable.should_slam_over_execute
actions.berserker_stance+=/bloodthirst,if=variable.should_bloodthirst&main_gcd_spell_bt
actions.berserker_stance+=/whirlwind,if=variable.should_whirlwind&main_gcd_spell_ww
actions.berserker_stance+=/slam,if=buff.bloodsurge.up&variable.should_slam_over_execute
actions.berserker_stance+=/bloodthirst,if=variable.should_bloodthirst
actions.berserker_stance+=/whirlwind,if=variable.should_whirlwind
actions.berserker_stance+=/recklessness,if=(buff.death_wish.up|debuff.shattering_throw.up)
actions.berserker_stance+=/execute
actions.berserker_stance+=/slam,if=buff.bloodsurge.up
actions.berserker_stance+=/demoralizing_shout,if=settings.debuff_demoshout_enabled&!debuff.demoralizing_shout.up
actions.berserker_stance+=/battle_stance,use_off_gcd=1,if=variable.weave_now

actions.battle_stance+=/shattering_throw,if=buff.bloodlust.up&debuff.shattering_throw.down
actions.battle_stance+=/berserker_stance,use_off_gcd=1,if=(cooldown.bloodthirst.up|cooldown.whirlwind.up|rage.current<10)&(debuff.shattering_throw.up|!buff.bloodlust.up)
actions.battle_stance+=/rend,if=!up|debuff.rend.remains<=settings.rend_refresh_time
actions.battle_stance+=/overpower,if=talent.improved_overpower.rank>0

actions.defensive_stance+=/berserker_stance,use_off_gcd=1

author: Defox

last updated: 20230413.2108

description: Fury Warrior priority for Hekili

export string: Hekili:fR1sVnUnq4Fl(IG8MSU(X6MDbI9HIIIU9WEXfO3KmTeDSA0dxkQ4Mcb)BVdjLOOOiLKtd2cKNAeN3CMVH0El8(DVDHik27BlNVC18pTy1SLlw(LvFXBh91ZyVDNrbpJEc(Juuc8ZFPG8k7HVgNHczlopRGeae82DOikM(1uVdg448pVAj8UNXbEFBH3UtrHHyXBIZdeC96()arirzKR7pZ(vefE0r2)(R4NJIJ82fhLtZ5km(iQiMc)534gaofDigh69tE7qb0OSuVDbO4yFX)4ZwNy1(cJiknI6rbfuBXbGqXKiK3UxqWVGhpl)uwrCOFErAigufNR7LKWjyYt40GxRO2iCX)7JijzeMCwXKtnXZfjj4yv5cVXNSQjhkoEC2bmjhtEg4zofLgGNvCUHHKIuRwQ(czYA9aYcrPX4BwqQRIjLFSFPaHqCAE0l3SG0xOhlsU7mbhKLakHPCcnrxjWWSlPnI0KJYE6bkpp6PumKxaPh0zGOtqPHrPpjEappHlRKx9R9m83Kj0wu1xQMAPtwMnng1svYVFQK6Ifo)oHK6yqro2p74r)Ncc5B7T6SBTzGQNnnCi9qCwwyCrofsJ42siweQpbmcEpWuONizx0mfDY9h0DVUpillMXcHaPNIivISSuH4f45XxIsdLKiqf0zbfecofIepED)I5x3pLRPU2v26vpPk202kN2N)uZZ3BwdW(AjvPjGAgc)ibfLMdQ7MR7ZXukOy5Cs(e8rco)KpnITJuURfi1FTmkkgCaZIsotYEbstHFqoNDbtMrqPpFD)2R7N3Wpj1QCcDJS30cUhhsmJcIOCgVuHZChjH3vRRJYEcq7O4wv3YFvGlWvroWZajc8GltGW2cCkojcdUsyjl4eQdPqzRNJX55PW315UUCYnTz(BCqbf7F(ekhlctsXwttk(k9Uv2Xjmjlka8AKONVXuJ)7w82)pS4Gym6fJMQ9CZE647QOBmqonezQMKeB7cf(wsDQDeb27bxTfmb9NzvVpSDlSGZNA)1KMAgk8DM2U4w0G9mbpZtax3OvHye9K)LO8tYo22kzZEoOIj5AaxEOVfDcqqsaqFWwDuqaogtqccTyXNhrT98caQvT5ZC0mz5dSgq5LhJsAJmRoece41y8RYAuIhajMS)YOZhuQ4Bsjoq1kViEvMmwmF0cr25WKiUCPreYxKlGX0DSLh8n4PwmEWYQ2VvNI9IowDk2mF7BQDRk60KO3ztIPMUtvBQ1uUIlS1Qy5LERwj0lga7BR4Hbp9dwxUSmOq79dXjzCGynLbBvEGrNGIJ(NgWCQsSlzU8TVHugAUWkW6NMDPlUqBiqOvZDzOTD2zUP1WRA5W(R4cmpqwzsucSRGPVHWCuVwNqVAUaqflYsrGNLoJboXNM5hgXzdPA(b1hBOB)WQsf7pHrX0tZohia0XGx0iKwDWm1IDyXCRne5BHzdoRQhw3EBOv47VkPSLVo)0GYPvyqVZ47VAjlE0Js1QaJ(25Hvj99PvTIv3KkvzLesoCjx(xRVU)J92jhs2)a)nxmdE37UUpgrzhgbNYu(twzkvqCuf1DUVjRQPUID0jmpURD4jo9AtpYT7PQQTkEltGfgLwBb9w)kZgUYy5DAgo66(h4VLXrdLVMJXXdvj3AiVMMdnEcn4LMqVmSZ4gJlQMjKN1QeN(PFzcPZWku)UTwtCi65uVaT5o6Z7(g4sRPuAyu1Un13ubAHP3ZyyDWbIMyg3ItNtsaSmHbXEUMXyOrLbpHGCZsnvmKpnLjGMdhF7aMJXldwctZyhkIZB8qi6O01NgrhCRVV68Y51JiYvA5zwaYhf(QSKOa6ckhA)CeQzYZgQHA2r1vp4JUaLhw)BfHBnJS2WSkUkTzz11enfTb(x1racVxotzeN5)YLFcEheHHtdgy8RjNZiuM8)rXbeKLcTRyhM)SR)g7SBZogXuFbP8zYdZ9Un)G(P(CF0XnI6unNI71FZ0k1pgt2kh4CBDen3mCaPskgpCuZkGktmiCvYVDblfnZI1UZJ7zbRnmq3QVLAbEMAPhZf0DAGuPvOxLxI7Yq9jAhDVqfSgenCVgdZm15mA4K2TwmiB0p0AjNmCZekU5zm3jWZA3JGzky4UNVjCJRTXvCGrvMww2DiLberlKTvcPtf(hHYr9ZgBteuXXjMrsxwAFEJXjqL273SOmmhX4eQelWnlYoZimobk2HujT(hcWX0aaBDDx)rRysN(bxawXDva9No9UvdOvQWDRDbdGGVS01mgrhRQ1JRNoGEObDTt0qvpTlNnRnsRcIWJp40hwsh7aeDMyaH2aBg1Qjwzr3GNRwRz4ehvQfVLBLC6Zq3UzqOU94lUPvBcK8wWGC6bCmNUbhE1Z0adx90wWGDubH94gtWFD6uySJDPd7DCbbgsPQyGrqIT0TTBwm3Xay2h3yhi74udjSSBqxwo3X1ce1YslWthAFTegOEfpnGNoUMGCwwAfU5u1oU6GeyqRQVaV7voMXnly9WvV4VTQTdnWMw3mMfwjDG52V5lhMmAU1RnlSKn7o(gq63V10EneXfE9(zbB)UBbJevQRXEgkzsATA6xOn1vyICGoJotmxEVSSNow9kE5DQ1oW1FkR5Ru7g4ad4wdS5w1GnCXAoDce6ihhEJAfSpdrvfY6c)aTxg3aTZaBLe1z6LlVvxZ3l3W7Gr3llu3qZ4IB3gSnj0DVBS(3pngxHDF8aBv1VQkgt0Hy35(WKBAnEty9hZAnNzNsRs3VSjyREwQlMz1AUY2EGQptpo287TpJbDE3z66o6QRLp3sLLg)mlvw2cI1I5tDCTNsuwoPJLm1U2YHqb60eLeTBhDKoxBqebSU)pMrBNRgO0N2Fq)P3oub9ugXB3pJpM938J)Y7Fp

**Comment by Hekili** [comment]
No, that's not a snapshot.

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Alausa124** [comment]
ohhh ok wait

**Comment by Alausa124** [comment]
https://pastebin.com/adTwySJV
like this?

**Comment by Alausa124** [comment]
HI, so?

**Comment by Hekili** [comment]
Have you purchased and learned all your skills?  Do you have Berserker Stance?

**Comment by Alausa124** [comment]
Yes

2023-04-14, pn 15:40, Hekili ***@***.***> rašė:

**Comment by Hekili** [comment]
Are you sure?

![image](https://user-images.githubusercontent.com/9438134/232237412-81e47f9e-0999-4208-a41e-bc0d393e0f90.png)

**Comment by Alausa124** [comment]
yeah that was an older photo i got that berserker stance and now its a bit better but still rotation is confusing ;D because it says me to use Sunder armor for 4 or more times in a row at start

**Comment by zmsl** [comment]
> it says me to use Sunder armor for 4 or more times in a row at start

Turn off the "Maintain Sunder Armor" setting in Hekili > Warrior settings if you don't want it to recommend Sunder Armor
