### ISSUE TITLE
monk should not use tiger palm during serenity

### ISSUE THREAD

**Issue by 78jeffrey** [Hekili/hekili#2539]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

monk using tiger palm during serenity and only use fof in the last sec.  
I recheck on raidbots sample ability log which use fof 4 times during serenity.

### How to Reproduce

using fof more and not using tiger palm

### Snapshot (Link)

https://pastebin.com/Pw8wGKFv

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jUEjFViAkUdnsfgvfENNd2

**Comment by 78jeffrey** [comment]
under action list serenity  seems miss a line below 9

fists_of_fury_cancel    compare to the raidbots report.

**Comment by Hekili** [comment]
> under action list serenity seems miss a line below 9
> fists_of_fury_cancel compare to the raidbots report.

Yeah, it's implemented differently in the addon but isn't totally consistent with the sim.

> monk should not use tiger palm during serenity

This is incorrect.  You can see that Tiger Palm is used 7+ times on average during Serenity in your sim.

![image](https://user-images.githubusercontent.com/9438134/232488258-45c38043-6da5-4d10-a62d-eb427503d5d3.png)

I'll take a look at making FoF happen more (with the cancel during Serenity).  It's likely that increasing use of FoF will push down the number of Tiger Palm uses that you're currently seeing.

**Comment by 78jeffrey** [comment]
Thank you for your reply. In my testing FoF was only used at the last second during serneity.

**Comment by Hekili** [comment]
This will be resolved in today's release.

**Comment by 78jeffrey** [comment]
The new release just full casting FoF  during buff invokers_delight.up. 

This is not what I saw on raidbot Sample Ability Log.

under profile you added 

actions.serenity+=/fists_of_fury,interrupt_if=buff.serenity.up&!(buff.serenity.remains<1|buff.invokers_delight.up&(active_enemies>4|talent.jade_ignition&active_enemies<3)|buff.bloodlust.up|active_enemies=2)

I I modified to 

actions.serenity+=/fists_of_fury,interrupt_if=buff.serenity.up&!(buff.serenity.remains<1)

Looks like it fixed the issue.

I have no idea how the code work.  just tried my best to understand it and hope it can help.
