### ISSUE TITLE
[Suggestion] Minimum Number of Enemies OR Boss Fight

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#254]
Is it possible to have skills suggested in this way?

In some cases it's not worth using certain skills unless there is more than one enemy, but would always be worth using during a boss fight.

**Comment by Hekili** [comment]
Yes.

`boss` is true/false if it is a boss fight.
`active_enemies` is the number of enemies.
`|` is the "or" operator.

`boss | active_enemies > 1` would be an example of that.

If there are already other criteria, you can do:

`( boss | active_enemies > 1 ) & other_criteria_here`
