### ISSUE TITLE
[REC] Balance Druid - Trinket not suggested

### ISSUE THREAD

**Issue by PARADOX070** [Hekili/hekili#2540]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On use trinket is never suggested when playing balance. The trinket being Voidmender's Shadowgem.

### How to Reproduce

Just perform the rotation. It will never be suggested.

### Snapshot (Link)

https://pastebin.com/ecVHWBAQ

**Comment by Hekili** [comment]
Thanks; the next release will have adjustments to the `on_use_trinket` variable used to decide which trinket to use.
