### ISSUE TITLE
[BUG] Micro-stuttering on all specs

### ISSUE THREAD

**Issue by Noodleboy0** [Hekili/hekili#2542]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Micro-stutters out of combat. Seems to be accompanied by frame drops as well. Starts off as noticeable but playable, then ramps into more serious and less micro. Strange that it only stutters outside of combat. 

### How to Reproduce

1. Enter the game on any spec.
2. Boom micro stutters

### Player Information (Link)

https://pastebin.com/mPG41YA8

### Error Messages (Link)

n/a

### Additional Information

Computer specs are
i9-12900k
3090
64 GB of ram
So I do not believe it is a hardware issue.
Seems like it happens on every character / spec
Does not micro stutter when Hekili is turned off

### Contact Information

Spaghetti#11735

**Comment by Noodleboy0** [comment]
After some more testing it seems like the stuttering is exclusive to all specs of Warlock, and only out of combat.

**Comment by Hekili** [comment]
> exclusive to all specs of Warlock

No, it's not.  The default settings now allow all displays to be updated in a single frame.  You can go into your spec's performance options to change that.  It's still something I'm iterating on.

**Comment by Noodleboy0** [comment]
Ok, do you have a recommended value I should change it too? I run a 160hz 2k ultrawide

**Comment by Hekili** [comment]
This will be reverted with the next release.
