### ISSUE TITLE
[BUG] Hekili/Dragonflight/PriestHoly.lua:623: attempt to perform arithmetic on field 'up' (a boolean value)

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#2544]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili/Dragonflight/PriestHoly.lua:623: attempt to perform arithmetic on field 'up' (a boolean value)

### How to Reproduce

1. Play Holy Priest

### Player Information (Link)

https://pastebin.com/Xk8eXbPg

### Error Messages (Link)

https://pastebin.com/UK7gCZxJ
https://pastebin.com/nxBQc9bK

### Contact Information

Lemonlust#4440

**Comment by PARADOX070** [comment]
Experiencing the exact same, causing lots of frame drops and stutter.
