### ISSUE TITLE
[BUG] FPS stuttering in combat while using "Fixed Dual Display" mode

### ISSUE THREAD

**Issue by funappear** [Hekili/hekili#2545]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After updating from Hekili-v10.0.7-1.0.10 to Hekili-v10.0.7-1.0.12, I experienced FPS stuttering in AoE combat.

The issue was particularly bad with "fixed dual display" mode and seemed to be less with "automatic" mode.

tested by replacing each file with the previous version to identify the problem and found that the update to the "ui.lua" file caused the issue.

I don't know if I can fix this through option tweaks or if a technical update is required, so I'm reporting it.

I appreciate the author's efforts to keep it updated for the best performance.

### How to Reproduce

1.Enter game as a Shadow Priest.
2.Problems in AoE battles.

### Player Information (Link)

https://pastebin.com/A19FNm3W

### Error Messages (Link)

N/A

### Additional Information

CPU : AMD Ryzen 7 5800X3D 8-Core Processor
RAM : 32 GB
GPU : NVIDIA Geforce RTX 3080
OS : WINDOWS 10
Game version : 10.0.7.48999
Language : Korea

### Contact Information

Discord ID : 즐거운나날#6539

**Comment by Hekili** [comment]
You can re-enable the previous behavior in your spec's performance settings.

**Comment by RussellAnas** [comment]
Experiencing stuttering in AoE combat as Retribution Paladin too.

**Comment by dnobrn** [comment]
Also experiencing this on my characters as of v10.0.7-1.0.12, including ele shaman and frost dk. Only using 1 display module (auto mode), with cooldowns & interrupts toggled on. Ruled out other addons by enabling/disabling them one by one.

**Comment by SultanSem** [comment]
Yes, I have experienced this issue as well. At first I saw the Hekili addon taking snapshots consistently and maybe turning it off will solve the FPS stutters. However, it did not. I tried switching to Single mode and that faired better compared to the Dual mode but it still had some stutters, albeit not as worse as Dual mode. Please fix this, thank you.

**Comment by garodin** [comment]
I have to confirm this.  A  lot of stuttering is occurring  when I play  any  class. Pala ret/Fire Mage/DK blood, any  class goes. This should come  in a future patch. Thanks!

**Comment by Hekili** [comment]
The change I made last week will be reverted in next release.
