### ISSUE TITLE
Frost deathknight recommending Anti-Magic Shell at pull

### ISSUE THREAD

**Issue by iNupidstoob** [Hekili/hekili#2546]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For some reason on Frost DK the priority is prioritizing Anti-Magic Shell before the fight starts.

### How to Reproduce

Enter the world as a Frost DK.

### Snapshot (Link)

https://pastebin.com/raw/TTnpdLim

**Comment by Hekili** [comment]
The sim profile uses AMS offensively/proactively for RP generation without really checking for incoming magic damage to absorb.  I have an option for Unholy DK to decide whether to use AMS offensively which removes it from the Defensives toggle.  Frost DK doesn't have that setting, but you also have Defensives toggled on so using AMS is allowed.  I'll look at adjusting this to make this work more intuitively.  In the meantime, the easy solution is to disable Defensives when not playing a tank.

Thanks!

**Comment by iNupidstoob** [comment]
Apologies I wasn't aware about that. I'll close this issue then. Thanks for your work on this addon. <3
