### ISSUE TITLE
[BUG] Rouge 

### ISSUE THREAD

**Issue by Kenyiro34** [Hekili/hekili#2548]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I got error when try to use  simulationcraft to import  priorities my assasin rouge 

### How to Reproduce

Rouge assasin

### Player Information (Link)

https://pastebin.com/ngyaKhCC

### Error Messages (Link)

http://github.com/Hekili/hekili/issues

**Comment by chevyn11** [comment]
Dont import priorities. Use the defaults.

**Comment by Kenyiro34** [comment]
Default priorites so weak ( low dps 50k ) on Simulationcraft can do it more dps almost 60k ( 2 updates before i always replace priorites from simulationcraft and working good )

**Comment by Hekili** [comment]
> Dont import priorities. Use the defaults.

> Default priorites so weak ( low dps 50k ) on Simulationcraft can do it more dps almost 60k

Almost certainly placebo effect.
