### ISSUE TITLE
Recomendations dont show, no warnings in the addon but i do have a bugsack warning

### ISSUE THREAD

**Issue by pozzer18** [Hekili/hekili#2549]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

2x Hekili/UI.lua:2264: script ran too long
[string "@Hekili/UI.lua"]:2264: in function <Hekili/UI.lua:2191>

Locals:
self = HekiliEngine {
 0 = <userdata>
 combatRate = 0.250000
 activeThreadStart = 23696606.997800
 superUpdate = false
 refreshTimer = 1.010000
 UpdatePerformance = <function> defined @Hekili/UI.lua:2132
 activeThreadFrames = 1
 activeThreadTime = 0
 activeThread = <no value>
 eventsTriggered = <table> {
 }
 IsThreadActive = <function> defined @Hekili/UI.lua:2306
 refreshRate = 5
 criticalUpdate = false
}
elapsed = 0.010000
thread = <no value>
firstDisplay = nil
superUpdate = nil
ok = false
err = "Hekili/Scripts.lua:801: script ran too long"
(*temporary) = false
(*temporary) = "Hekili/Scripts.lua:801: script ran too long"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
Hekili = <table> {
 GetMacroCastTarget = <function> defined @Hekili/Events.lua:1085
 GetTTD = <function> defined @Hekili/Targets.lua:1103
 IC = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili/Options.lua:4026
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili/Targets.lua:1088
 GetPetBasedTargetSpells = <function> defined @Hekili/Targets.lua:121
 LoadingScripts = true
 After = <function> defined @Hekili/Utils.lua:284
 activeFrameStart = 23696607.008500
 GetGreatestTTD = <function> defined @Hekili/Targets.lua:1182
 currentSpecOpts = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SaveCoordinates = <function> defined @Hekili/UI.lua:3030
 PLAYER_ENTERING_WORLD = true
 PendingSpecializationChange = false
 UpdateDisplayVisibility = <function> defined @Hekili/UI.lua:1996
 ResetSpellCaches = <function> defined @Hekili/Core.lua:561
 IsEnabled = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Version = "v10.0.7-1.0.12"
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili/State.lua:6782
 SetMode = <function> defined @Hekili/Options.lua:10742
 baseName = "Hekili"
 BuildUI = <function> defined @Hekili/UI.lua:2739
 GetPetBasedTargetSpell = <function> defined @Hekili/Targets.lua:133
 ToggleHold = <function> defined @Hekili/State.lua:6807
 SpecializationChanged = <function> defined @Hekili/Classes.lua:5929
 Update = <function> defined @Hekili/Core.lua:1426
 DumpProfileInfo = <function> defined @Hekili/Core.lua:2078
 IsRetail = <function> defined @Hekili/Hekili.lua:22
 GetNumTargetsAboveHealthPct = <function> defined @Hekili/Targets.lua:1259
 GetNextPrediction = <function> defined @Hekili/Core.lua:1313
 UpdateUseItems = <function> defined @Hekili/Events.lua:658
 SetSpecOption = <function> defined @Hekili/Options.lua:3809
 GetDefaults = <function> defined @Hekili/Options.lua:442
 dumpKeyCache = <table> {
 }
 GetPredictionFromAPL = <function> defined @Hekili/Core.lua:638
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetDisplayByName = <function> defined @Hekili/Core.lua:1395
 Options = <table> {
 }
 ReInitialize = <function> defined @Hekili/Core.lua:148
 GetSpellLinkWithTexture = <function> defined @Hekili/Utils.lua:582
 IsSpellEnabled = <function> defined @Hekili/Core.lua:555
 GetAbilityInfo = <function> defined @Hekili/Classes.lua:5874
 IsSpellKnown = <function> defined @Hekili/Core.lua:542
 State = <table> {
 }
 OnEnable = <function> defined @Hekili/Core.lua:167
 RestoreDefault = <function> defined @Hekili/Classes.lua:1115
 FindSt

### How to Reproduce

enter game as a DK
choose unholy spec
start combat and see nothing appears, rolling back an update fixes this issue

### Player Information (Link)

https://pastebin.com/945r4uAM

### Error Messages (Link)

pasted above

### Contact Information

Pozzer#8576

**Comment by Hekili** [comment]
Thanks.  I'm reverting the commit that caused higher CPU usage within a frame, so this will be resolved with next release.
