### ISSUE TITLE
Starfall for Balance DRUID

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#255]
Starfall ( 191034 ) not working on Hekilli. I tryed many combinations of mobs, boss encounters etc and still it not recommending use starfall even for 20 targets, no meters you check "Minimum Targets from 1-10 )Hekilli recommends use starsurge all the time

**Comment by Hekili** [comment]
Where are you setting minimum targets? On the display? That's not what that is for r. 

There are two issues at play:

1.  Ranged specs count targets you've hit, so if you haven't hit the targets with anything, they don't count.

2.  Starfall isn't recommended until quite a few targets. 

```# Starfall v Starsurge target cutoff
actions.precombat+=/variable,name=sf_targets,value=4
actions.precombat+=/variable,name=sf_targets,op=add,value=1,if=azerite.arcanic_pulsar.enabled
actions.precombat+=/variable,name=sf_targets,op=add,value=1,if=talent.starlord.enabled
actions.precombat+=/variable,name=sf_targets,op=add,value=1,if=azerite.streaking_stars.rank>2&azerite.arcanic_pulsar.enabled
actions.precombat+=/variable,name=sf_targets,op=sub,value=1,if=!talent.twin_moons.enabled

actions+=/starfall,if=(buff.starlord.stack<3|buff.starlord.remains>=8)&spell_targets>=variable.sf_targets&(target.time_to_die+1)*spell_targets>cost%2.5
```


Basically, you will probably need to hit the targets once (Sunfire, Starfall) and the addon will recommend SF when conditions are met.

**Comment by mati3464** [comment]
I using Hekilii from 8.0 and Before patch it was recommending starfall at 7+ targets as i setin options:

https://i.imgur.com/41LKWuk.png

Even if i hit 8 targets ( https://i.imgur.com/Gbx2srl.png ) changed talets from starlord and remove all azerite gear it still not recommending starfall.

As i write before, before patch everything was fine and i didin't change anything in setup from 8.0

**Comment by Hekili** [comment]
Ok, go ahead and take a snapshot and post the log here.

**Comment by mati3464** [comment]
build: v8.3.0-02
level: 120 (120)
class: DRUID
spec: balance

talents: force_of_nature
    incarnation
    restoration_affinity
    shooting_stars
    twin_moons
    typhoon
    wild_charge

azerite: none

essences: [essence_of_the_focusing_iris]=3, purification_protocol=3, the_crucible_of_flame=3

sets/legendaries/artifacts: none

gear:     ancient_tempest_striders=1
    anglerfish_feelers=1
    ashjrakamas_shroud_of_resolve=1
    boralus_nobles_seal=1
    breeches_of_the_insatiable_maw=1
    heart_of_azeroth=1
    irradiated_undercoat=1
    leviathans_lure=1
    loop_of_pulsing_veins=1
    port_pillagers_belt=1
    scepter_of_the_azshari=1
    shiver_venom_relic=1
    tabard_of_summer_skies=1
    tidebinders_driftglobe=1
    wristwraps_of_the_insatiable_maw=1

itemIDs: 158075, 159309, 159463, 168376, 168380, 168477, 168889, 168903, 168905, 169223, 169304, 169878, 173484, 174954, 35279


VIDEO: https://www.youtube.com/watch?v=ECS3thrj54A&feature=youtu.be 
I take all azerite off

**Comment by Hekili** [comment]
Your addon is in single-target mode.  This does appear to be linked to a bug with the "mode" toggle.  I'll post a fix in a few minutes.

**Comment by Hekili** [comment]
Fixed in v.8.3.0-03.  If you are still experiencing issues, reset your profile before posting an updated snapshot (see the instructions re: snapshots when you make a ticket).
