### ISSUE TITLE
[FEATURE] Option for Tooltip

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#2553]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Might it be possible to have an option to enable a tooltip for Hekili's recommended spells?  

I use Hekili to learn new specs on the target dummy, and I end up spending a lot of time hunting through my spellbook for icons that look like the one that's recommended.  Sometimes I can't find it, like this weird purple thing it wants me to cast on Disc priest--possibly a proc that changes the spell icon appearance?  

It would be amazing to be able to mouse over the relevant spells to find out what they are.

**Comment by Hekili** [comment]
You can pause (ALT-SHIFT-P) and mouse over the icon for information about what is shown. I'm not sure making the button interactive when unpaused is a wise decision. I'd get mad if I couldn't click something because the addon was overlapping it.
