### ISSUE TITLE
[BUG] Holy Priest default priority list fires multiple copies of one error when casting Flash Heal

### ISSUE THREAD

**Issue by jch4983** [Hekili/hekili#2556]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I received the following from BugSack after casting one or two flash heals.
It seems to be specific to the Holy Priest priority, as I've not experienced this on any other healers.
It also seems to only affect a cast of Flash Heal as no other healing spell in my normal kit fired any errors...
Each cast seems to fire roughly 20 copies of this error.

When I cast it three times in a row, I had 22, 39, and 60 errors total (22, 17, and 21 errors per cast).

### How to Reproduce

1. Log in as Holy Priest with Hekili enabled.
2. Cast Flash Heal on any target.

### Player Information (Link)

https://pastebin.com/3HgNVLJu

### Error Messages (Link)

https://pastebin.com/8xkm88Kt

**Comment by Hekili** [comment]
These are fixed in 1.0.13.
