### ISSUE TITLE
Rogue how to switch off poison/poisons in the rotation to only display the one/ones you need to refresh.

### ISSUE THREAD

**Issue by Qtjas** [Hekili/hekili#2557]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

As you can see, I have applied the poisons I require but its still telling me to apply crippling poison in the rotation icons.

![image](https://user-images.githubusercontent.com/131931431/234744424-b023ac7a-7ada-43ec-8139-fcb5d33e3fc4.png)

**Comment by Hekili** [comment]
This is not a feature request.  You can submit a ticket re: recommendations and take a snapshot.  Did you take the talent that lets you apply more talents?

In any case, try a ticket re: recommendations and follow the instructions about supplying a snapshot.  Thanks.
