### ISSUE TITLE
Soothe (Druid) vs Spirit Shock (Hunter)

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#256]
It's possible to add Soothe (2908) like Spirit Shock (264265) to recommendation interrupts when target has enrage? 
Spirit Shock already is recommending as interrupt when target is enraged but Soothe still not. 

Adding | debuff.dispellable_enrage.up should be fine?

**Comment by Hekili** [comment]
Yes, it could be added to a custom priority.

**Comment by Hekili** [comment]
Also, you don't need any conditions for it; Soothe has a built-in usability check that requires a dispellable enrage buff.

The condition is there for Hunter APLs because they have a list of utility abilities to check.
