### ISSUE TITLE
[REC] Discipline (and Holy) Priest - Surge of Light aura missing

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#2560]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

You can't have Flash Heal in rotation on Surge of Light procs, as the aura isn't in Hekili

### How to Reproduce

buff.surge_of_light.up doesn't exist.

### Snapshot (Link)

https://pastebin.com/dr7gsqaG

**Comment by Hekili** [comment]
Thanks, I will add the buff detection along with its mechanics in the next release.
