### ISSUE TITLE
[REC] Hekili thinks that Execution Sentence costs Holy Power

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#2561]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The first queue icon after [Execution Sentence](https://www.wowhead.com/spell=343527) is calculated with the assumption that Execution Sentence costs holy power. This is wrong, Execution Sentence is free. With [Divine Auxiliary](https://www.wowhead.com/spell=406158) it even generates Holy Power.

### How to Reproduce

1. Play as Retribution Paladin.
2. Follow the priority until it suggests Execution Sentence.
3. Notice that the queue icon might show Wake of Ashes, which would waste Holy Power.

### Snapshot (Link)

https://pastebin.com/74UhzPjd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iCAyYZnu3oxHhVjw2ceTM4

### Additional Information

Please also implement the part of Divine Auxiliary that affects Final Reckoning.
Another thing I just noticed in the Execution Sentence code: The Fires of Justice talent was also removed in 10.0.7, but is still used in the code.

**Comment by Hekili** [comment]
Will be fixed in next build.
