### ISSUE TITLE
[REC] Holy Power generators shown when already at 5 Holy Power

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#2562]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While trying a few things at the AoE target dummies suddenly Hekili didn't show any finishers any more. I was at 5 Holy Power and it still suggested a generator.
I could reproduce the problem again when I started combat again. But after reloading the UI I couldn't reproduce it any more.

### How to Reproduce

1. Play as Retribution Paladin.
2. ??? (unknown)
3. Attack the AoE target dummies.
4. Follow the priority.
5. Notice that a generator is shown with 5 Holy Power.

### Snapshot (Link)

https://pastebin.com/57A7q0aj

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cUgN85WyXeLXYDQhYDr4L3

**Comment by Hekili** [comment]
You have Execution Sentence talented but it shows as not known to the addon.  Either you've disabled it, or its spell ID is changed by Divine Auxiliary and the addon doesn't know about it.

> this entry's criteria FAILS: variable.ds_castable[true] & ! buff.empyrean_legacy.up[false] & ! ( buff.divine_arbiter.up[false] & buff.divine_arbiter.stack[0.00] > 24 ) & ( ( ! talent.crusade.enabled[false] | cooldown.crusade.remains[0.00] > gcd.max[1.16] * 3 ) & ( ! talent.execution_sentence.enabled[true] | talent.divine_auxiliary.enabled[false] | target.time_to_die[143.00] < 8 | `cooldown.execution_sentence.remains[0.00] > gcd.max[1.16] * 2` ) & ( ! talent.final_reckoning.enabled[false] | talent.divine_auxiliary.enabled[false] | cooldown.final_reckoning.remains[0.00] > gcd.max[1.16] * 2 ) | buff.crusade.up[false] & buff.crusade.stack[0.00] < 10 )

The criteria for using Divine Storm here requires Execution Sentence being on cooldown or toggled off (so it pretends it is on CD).  Execution Sentence appears higher up in the priority, but you don't seem to know it:

> 24.  execution_sentence ( cooldowns - 12 ) - ability unknown

I'm not sure why that is.  I don't see an obvious combination of talents that would change its ID or otherwise render it unknown.  Have you made edits that might impact this?

**Comment by cremor** [comment]
> You have Execution Sentence talented but it shows as not known to the addon. Either you've disabled it, or its spell ID is changed by Divine Auxiliary and the addon doesn't know about it.

Execution Sentence was not talented when I took the snapshot. You can see it with the talent export string in the snapshot, that contains Final Reckoning. So it seems like Hekili didn't detect my talent switch that happend right before this issue occured.

That would also explain why I couldn't reproduce the issue any more when I reloaded the UI. (I just reloaded the UI. I didn't change the talents again.)

> Have you made edits that might impact this?

No, I'm using the default Hekili priority and settings. No ability (that is relevant in this case) is disabled.

**Comment by Hekili** [comment]
I haven't been able to replicate a talent detection failure for some time.  I'll close this out, but if it occurs again, please let me know (and look for a warning or BugSack message to see how/why talent detection failed).  Thanks!
