### ISSUE TITLE
[FEATURE] have a priority list for HC classic

### ISSUE THREAD

**Issue by bason1c** [Hekili/hekili#2563]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

So i have recently been leveling HC with a lot of people that have no understanding of the game even 20 years later.  I have been trying to find a rotation addon and cant seem to find any that work.  Hekili is my go to suggested addon when i see someone struggle, and its annoying not to have this in the most basic version of the game.  Is there a way that i could use this in classic or import classic rotations into the current build? 

what would be the best way for me to see my rotation as a rogue in classic HC and for other guild members to be easily able to do the same thing. 

### Contact Information

basonic.eth@gmail.com

**Comment by tqphan** [comment]
Would love to have Classic support.
