### ISSUE TITLE
[REC] Retribution Paladin, Hammer of Wrath recommended at 5 holy power

### ISSUE THREAD

**Issue by chevyn11** [Hekili/hekili#2565]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While already having 5 holy power the recommendations show as:  Hammer of Wrath(0.80), Blade of Justice(2.06), Final Reckoning(3.32)

Hammer of Wrath generates 1 holy power.
Blade of Justice generates 1 holy power.

This leads to wasting some holy power.
Not sure if this is a gain, even with the Adjudication talent.

### How to Reproduce

1. Enter game as Retribution Paladin
2. Play the Crusading Strikes build: BYEAS+uMNo6HaxL/ztTZBhrdcCAAAQAAClWrk0KtDkoIJpIJAAAAAAAphkkQgkQkSEIEpkoFJIBiSBA
3. Hit 5 target dummies
4. Sometimes it will recommend hp generators at 5 hp.

### Snapshot (Link)

https://pastebin.com/0yS1MKKA

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/b9qGcVUKL9LDmKk6HSRLb7

### Additional Information

Might be hard to see in quicksim, I dont see the hopo in the UI.

It is using an edited priority but I believe the only change is setting Entry Cooldown on Final Reckoning to 60s so it lines up with wings.

### Contact Information

chevyn#4512

**Comment by Hekili** [comment]
It's because of your edit.  The priority avoids spending Holy Power when Final Reckoning is coming off cooldown.  Line CDs do not impact the perceived cooldown of Final Reckoning.  You'd probably get closer results to what you want if you edited the actual conditions for Final Reckoning -- take a look at the `cooldown.avenging_wrath.remains` and `cooldown.crusade.remains` parts of the priority.

**Comment by chevyn11** [comment]
thats perfect, thanks. I've set the priority to `cooldown.avenging_wrath.remains > 10` and now works like the sims do.
