### ISSUE TITLE
[REC] Enhancement Shaman not suggesting Primordial wave in ST.

### ISSUE THREAD

**Issue by dhaos21** [Hekili/hekili#2566]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my spec i expect Primordial wave to be suggested, it doesn't, as soon as another target is introduced it will suggest it.

### How to Reproduce

1. Enter the game as a Enhancement Shaman. 
2. Take the Primordial Wave Talent.
3. Fight a Single Target/Dummy.

### Snapshot (Link)

https://pastebin.com/4u5UgVA2

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pBpGdkrbhjFE3bocSqweMc

**Comment by Hekili** [comment]
This will auto-resolve in 10.1.  You can temporarily resolve by going to /hekili > Abilities > Primordial Wave and set Require Toggle to None.

**Comment by dhaos21** [comment]
Ok Cheers, want me to close the report?

**Comment by Hekili** [comment]
It can sit here in case anybody else sees this today; I'll close it after 10.1 actually launches.

**Comment by Hekili** [comment]
Resolved with 10.1 launch.
