### ISSUE TITLE
[BUG] Frost mage can't switch to AOE action list even if the condition was met

### ISSUE THREAD

**Issue by tangaiyun** [Hekili/hekili#2567]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

for my frost mage, I setup the targeting as following:
![image](https://user-images.githubusercontent.com/7961235/235721426-f094ef6b-020a-4446-bb3e-c0795a85e427.png)

so you can look I checked "Use Nameplate Detection" and Detect Damaged Enemies"

and I setup the display mode always as automatic as following:
![image](https://user-images.githubusercontent.com/7961235/235722652-38ec4ffc-253a-415d-bd0c-0d438449a241.png)

So when I fight with Cleave training dummies, which inlucdes five targets, but it never recommends skill Blizzard, and "AOE" queue shows the AOE conndition is not match even if I cast an AOE spell to do damage on all five dummies. 
![image](https://user-images.githubusercontent.com/7961235/235724011-b4dcb198-bbed-4061-925a-39f0daadeccc.png)

I watched the profile, there is a sentence as:
actions+=/call_action_list,name=aoe,strict=1,if=active_enemies>=7|active_enemies>=3&talent.ice_caller
 
Hekili should switch to aoe action list when the condition "active_enemies>=7|active_enemies>=3&talent.ice_caller" meets, as you know, there are five dummies, and my frost mage has the talent ice_caller, my talent looks like:
![image](https://user-images.githubusercontent.com/7961235/235724977-1e20d069-6377-420a-a7fb-501824e0f5af.png)

so the condition "active_enemies>=3&talent.ice_caller" should be matched, but the Hekili didn't not switch to the AOE action list 

 

### How to Reproduce

1. set up talent as：
![image](https://user-images.githubusercontent.com/7961235/235725781-b70c947a-05fb-4d3c-9d7c-2821a75fa89c.png)

2. setup Hekili toggle as ：
![image](https://user-images.githubusercontent.com/7961235/235725975-0e058dfb-2335-484e-9b9f-670429a2a740.png)

3. setup targeting as:
![image](https://user-images.githubusercontent.com/7961235/235726203-244a131d-f87c-4150-a05f-7ee00cf17635.png)

4. then fight with  the five Cleave training dummies, you will see Hekili would not switch to the AOE action list 

### Snapshot (Link)

https://pastebin.com/W2dviCWM

**Comment by Hekili** [comment]
Nameplate target detection supersedes and rules out targets.  You're only counting targets within 12 yards of yourself.

Your snapshot would provide more information if it were taken at a point where you clearly have multiple targets and after your initial cooldowns have been used -- it's not even reaching the point where deciding between ST and AOE takes place.

**Comment by tangaiyun** [comment]
Thanks for response.  I uploaded two snatshots ： https://pastebin.com/0SLLpLsb and https://pastebin.com/X4bRC9S2
, before took these two snatshots, I cast serveral AOE spells (such as Arcane Explosion） on the five Cleave training dummies. At the same time, I disable the “Use Nameplate Detection", now my targeting config looks like:
![image](https://user-images.githubusercontent.com/7961235/235815963-2bb6faf4-75c3-426a-bb61-69e437db53a7.png)

but it seems still wound not switch to the aoe action list.

**Comment by Hekili** [comment]
Are you using a WeakAura called "Better Hekili Targeting" or anything like that?  (You should not.)

**Comment by Hekili** [comment]
Uncheck "On Screen Enemies Only" -- that is a nameplate-based filter as well and only counts enemies with nameplates on screen.  Also, nameplates must be visible to count with nameplate detection, too.  It looks like your nameplates are set to only appear for your target.

**Comment by tangaiyun** [comment]
thanks for your response. I solved this problem by checking "Display All Nameplates", but I still have a question：
I unchecked the "Use Namepalte Detection" and checked "Detect Damaged Enemies", why Nameplate display mode would still affect enemies detection?  In my opinion, "Use Namepalte Detection" and "Detect Damaged Enemies" should be "OR" relationship, that means anynone meets, the enemies should be counted. I am confused about the current enemies targeting algorithm.

**Comment by Hekili** [comment]
I have plans to refine target detection in a number of different ways.  In the current state, nameplate (and nameplate range) is only meant for melee or players with a melee pet who use pet-based target detection.  That's why nameplate detection is disabled by default.

I do plan to clear up the messaging as well, but we're in the midst of new patch chaos so it won't be in the immediate future.
