### ISSUE TITLE
[REC] Holy priest recommending Halo when halo talent isn't selected

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#2569]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Halo being recommended even though i dont have talent

### How to Reproduce

1. play holy priest and select divine star instead of halo.

### Snapshot (Link)

https://pastebin.com/DG2dXfC8

### Additional Information

![WoWScrnShot_050223_200422](https://user-images.githubusercontent.com/7343912/235831043-611ae961-65b1-4546-b99b-4207b3a12dd0.jpg)

### Contact Information

Lemonlust#4440

**Comment by Hekili** [comment]
Thanks; fix will be out in a little bit.
