### ISSUE TITLE
Frost DK - No Chains of Ice

### ISSUE THREAD

**Issue by cookiemonsterski** [Hekili/hekili#257]
Chains of Ice does not show in rotation even with cooldowns enabled.

Please advise for fix on user end or if coding needs to be adjusted.

Using v8.3.0-03

**Comment by Hekili** [comment]
Submit a proper ticket following the instructions please.

**Comment by cookiemonsterski** [comment]
---
name: BUG REPORT
about: IF THE REQUIRED INFORMATION ISN'T PROVIDED, YOUR TICKET IS LIKELY TO BE DISCARDED
title: ''Frost DK - No Chains of Ice
labels: ''Issue; Possible Bug"
assignees: Hekili

---

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
When attacking a target (single target or mob, does not matter) as a Frost Death Knight, the talent 'Chains of Ice' does not come into the Hekili rotation. This issue is still present even with the Cooldowns toggled 'On' and Essences toggled 'On' as well. 

**To Reproduce**
Steps to reproduce the behavior:
- As Frost DK with Chains of Ice talent selected
- Attack target with large health pool
- Notice Chains of Ice never shows, even with optimal 20 stacks

**Expected behavior**
Chains of Ice to show in rotation in accordance with simulation computer action algorithms Hekili is based on

**Screenshots**
N/A

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/ATKyZWGv

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
Multiple snapshots needed depending on theorycrafter's guidance, please see below the following paragraph for links. 

NOTE: Usually, Chains of Ice is directed to be used when the first Pillar of Frost is about to end (up to 5 seconds remaining, but dependant on how many runes left..instructed to use Chains of Ice after using final rune within the cooldown for Pillar of Frost). Either way, Chains of Ice never shows in fight against dummies, no matter how long a duration the fight goes on for...this is simply inaccurate, as the script is basically negating the use for the talent 'Cold Heart', when it is universally accepted as head and shoulders above any other talent within it's tier when combo'd with Breath of Sindragosa.

Link 1 - https://pastebin.com/m32G2uCy
Link 2 - https://pastebin.com/weYvBcsE
Link 3  - https://pastebin.com/s11tngvU  (was executed with no armor on whatsoever, noting that script continued to show Frost Scythe to be utilized as Pillar of Frost counted down in the final 5 seconds for the next 3 rotations)



3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

No error message shows

**Comment by Hekili** [comment]
Please get a snapshot -- push the button when you think Chains of Ice should've been recommended but it was not.  Thanks!

**Comment by cookiemonsterski** [comment]
> Please get a snapshot -- push the button when you think Chains of Ice should've been recommended but it was not. Thanks!

Edited with snapshots, thanks for your guidance and patience!

**Comment by Hekili** [comment]
Is it possible that you don't have Razorice enchanted on one of your weapons?  Chains of Ice is used after stacking 5 debuffs; the addon sees 0.

**Comment by cookiemonsterski** [comment]
Well, shit. Don't I feel stupid.

**Comment by Hekili** [comment]
Haha, no big deal.

**Comment by cookiemonsterski** [comment]
Thanks for all your work and assistance!
