### ISSUE TITLE
[REC] Hunter MM - Trueshot is not being recommended when it should

### ISSUE THREAD

**Issue by Williamn88** [Hekili/hekili#2572]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Trueshot stops being recommended. Works at first or with a fresh reload but seems to get out of sync. Would guess its something with the variable.trueshot_ready and the windrunners talents maybe getting it out of sync/wonky. But not sure.
In the snapshot I send the trueshot CD was ready.

### How to Reproduce

Play MM
Do some fighting
At some point it will not recommend trueshot anymore even if the CD is up and there is not a trueshot proc running already

### Snapshot (Link)

https://pastebin.com/fLDCadGF

**Comment by Williamn88** [comment]
Here is me just standing around in the open world after a fight with all CDs ready snapshot where trueshot is still reported as not ready
https://pastebin.com/ukGfKK7v

In the ST condition for trueshot (entry 13) it says variable.trueshot_ready = false.
This is how the variable.trueshot_ready conditions look
![image](https://user-images.githubusercontent.com/42271641/236008819-3b7a89aa-5c49-45e3-8006-a737907cb9f3.png)

**Comment by Williamn88** [comment]
Sorry about the updates. But was looking into it a bit as well. It seems like its bullseye that is causing it.
Its not really a bug from what I can see. It just calculates the time to live and and saves the trueshot for the end when its at max bullseye stacks which  might be a bit clunky in open world/fighting rares with other people where the time to live can be hard to calculate I guess.

**Comment by Hekili** [comment]
In general, any "use at end of fight" logic for cooldowns is applied to bossfights (`boss` = `true`) only.  You could remove the `boss&` from the priority if you wanted and `trueshot_ready` would be true any time a fight is expected to end in 25 seconds.

If you edit the default priority, though, there's no guarantee that I won't overwrite it the next day.
