### ISSUE TITLE
[REC] Holy priest recommend Divine star when talent not selected

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#2573]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Recommending divine star when talent isn't selected.

### How to Reproduce

1. enter game as holy priest with halo talented 

### Snapshot (Link)

https://pastebin.com/j2FWndVF

### Additional Information
![WoWScrnShot_050323_101639](https://user-images.githubusercontent.com/7343912/236009131-ea0365d1-fc95-4198-a598-35fbea296ea1.jpg)

### Contact Information

Lemonlust#4440

**Comment by Hekili** [comment]
This should be resolved.
