### ISSUE TITLE
[BUG] Cooldowns (stormkeeper and nature's swiftness) keep disappearing and re-appearing

### ISSUE THREAD

**Issue by anon9121** [Hekili/hekili#2574]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Cooldowns (stormkeeper and nature's swiftness) keep disappearing and re-appearing while I'm casting my main rotation. Stormkeeper doesn't even show on the Cooldowns bar unless I start casting Elemental blast. Nature's swiftness disappears when I cast lightning bolt.

### How to Reproduce

1. Include stormkeeper and nature's swiftness in seperate cooldown window
2. Start main rotation on dummy
3. See that stormkeeper and nature's swiftness keep disappearing and reappearing without even using them

### Player Information (Link)

https://pastebin.com/RkkpByCP

### Error Messages (Link)

no error message

### Contact Information

Isinar#7863

Snapshot:  https://pastebin.com/w4sjwgUD

**Comment by Hekili** [comment]
The snapshot you posted in Discord should've been included here. It says that Storekeeper was the 4th recommendation in your Cooldowns display, but you're saying it doesn't show up?

Can you post a screenshot of your Cooldowns displays options? Thanks.

**Comment by anon9121** [comment]
Apologies. Attached the snapshot and screenshot of my Cooldowns display options below.

[message.txt](https://github.com/Hekili/hekili/files/11391769/message.txt)
![image](https://user-images.githubusercontent.com/132520268/236068876-28a35c21-c7cd-4222-b625-42a533c1760c.png)

**Comment by Hekili** [comment]
There are three entries in the priority for Stormkeeper.

```
29.  stormkeeper ( single_target - 8 )
The action (stormkeeper) is usable at (0.00 + 1.24).
    - the action is ready before the current recommendation (at +1.24 vs. +10.00).
List ( single_target ) called from ( Elemental:default:17 ) would PASS at 1.24.
NONE
    - this entry's criteria FAILS: ! buff.ascendance.up[false] & ! buff.stormkeeper.up[false] & maelstrom.current[0.00] >= 116 & talent.elemental_blast.enabled[true] & talent.surge_of_power.enabled[true] & talent.swelling_maelstrom.enabled[true] & ! talent.lava_surge.enabled[false] & ! talent.echo_of_the_elements.enabled[false] & ! talent.primordial_surge.enabled[false]
```

This first one would pass if you had 116+ Maelstrom.  You have 0 Maelstrom so it doesn't pass.

```
30.  stormkeeper ( single_target - 9 )
The action (stormkeeper) is usable at (0.00 + 1.24).
    - the action is ready before the current recommendation (at +1.24 vs. +10.00).
List ( single_target ) called from ( Elemental:default:17 ) would PASS at 1.24.
NONE
    - this entry's criteria FAILS: ! buff.ascendance.up[false] & ! buff.stormkeeper.up[false] & buff.surge_of_power.up[false] & ! talent.lava_surge.enabled[false] & ! talent.echo_of_the_elements.enabled[false] & ! talent.primordial_surge.enabled[false]
```

This entry would've appeared if you had a Surge of Power buff, but you don't.

```
31.  stormkeeper ( single_target - 10 )
The action (stormkeeper) is usable at (0.00 + 1.24).
    - the action is ready before the current recommendation (at +1.24 vs. +10.00).
List ( single_target ) called from ( Elemental:default:17 ) would PASS at 1.24.
NONE
    - this entry's criteria FAILS: ! buff.ascendance.up[false] & ! buff.stormkeeper.up[false] & ( ! talent.surge_of_power.enabled[true] | ! talent.elemental_blast.enabled[true] | talent.lava_surge.enabled[false] | talent.echo_of_the_elements.enabled[false] | talent.primordial_surge.enabled[false] )
```

This one would've appeared if any one (or more) of the following were true:  Surge of Power not talented, Elemental Blast not talented, Lava Surge talented, Echo of the Elements talented, or Primordial Surge talented.  None of those criteria were met.

If it helps, keep in mind that the addon is not a cooldown tracker.  Abilities are recommended only if its conditions in the priority are met.  If you generated some Maelstrom, procced Surge of Power, or changed some talents, Stormkeeper would've been recommended.

**Comment by Hekili** [comment]
Just to elaborate:  What this means is that, Stormkeeper appearing and disappearing *makes sense* because when you're above 116 Maelstrom it would show or Surge of Power is active and its other conditions are met, it will display.  Otherwise, it won't.

**Comment by anon9121** [comment]
Interesting, and thank you for explaining all that to me. I appreciate it!!
