### ISSUE TITLE
[REC] Shadow priest stops recommending void eruption when not using Shadow crash

### ISSUE THREAD

**Issue by MichaelNilssonNutid** [Hekili/hekili#2575]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shadow priest rotation breaks when using a ST build not using Shadowcrash. Adding shadowcrash talent makes the rotation work as expected.

![image](https://user-images.githubusercontent.com/44154364/236161458-b56f0824-a709-4986-9689-f5a75bfa6244.png)

### How to Reproduce

1. Start as shadow priest
2. Use the talents BIQAgLWW0w0PLW4I8h9jUYB9zikQSAAAAAAAAAAAAACp4ARSSLNSSSQig0IJJRaEkgQKSLkEAJB
3. Follow the starting recomendations when after initial start it breaks and goes to doing filler rotation. 

### Snapshot (Link)

https://pastebin.com/kJ3kSgzj

### Contact Information

Fiidoo#4197

**Comment by Hekili** [comment]
This one would be a good time to have a sim for comparison so I could see if Void Eruption stops being recommended there, too.  I'm investigating this now.

**Comment by Hekili** [comment]
This should be resolved in v10.1.0-1.0.0d.

**Comment by Hekili** [comment]
Note:  The fix for this could have other implications, so if you notice other odd behavior with this update, please let me know.  You can add to this ticket and I can reopen if needed.  Thanks.
