### ISSUE TITLE
[BUG] Outlaw Rogue not working at all

### ISSUE THREAD

**Issue by DH099** [Hekili/hekili#2579]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I swap to outlaw rogue nothing is shown. 

### How to Reproduce

Whenever I'm spec'd into Outlaw it doesn't work. Sub works fine. 

### Player Information (Link)

https://pastebin.com/befCmkWN

### Error Messages (Link)

N/A

### Contact Information

DEE#8124-Discord

**Comment by Hekili** [comment]
I'm not able to replicate this.  Do you have BugSack and BugGrabber?  You put N/A in the Error Messages box; it seems likely there would be error messages if the spec doesn't work.  Also, a snapshot might help to explain this as well.  Can you try to generate one?  

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by DH099** [comment]
Bugsack doesn't record any errors when I switch to the spec and I seem unable to generate a snapshot.

**Comment by Hekili** [comment]
Ok, I'll need to ask you for some screenshots of your settings then.

Please open the option (/hekili) and then screenshot the following pages:

1. Outlaw (Core tab)
2. Priorities > Outlaw (Summary tab, Profile tab, Action Lists tab)
3. Warnings (if not greyed out)

**Comment by Hekili** [comment]
I'm unable to reproduce this; please be sure to provide the requested information if this persists with version v10.1.0-1.0.0g.  If it's resolved, please let me know as well.
