### ISSUE TITLE
Unlock?

### ISSUE THREAD

**Issue by JediMaDMZ** [Hekili/hekili#258]
I'm trying in all the possible ways to unlock it and move it, in the past the option was in general tab now i can't find it anymore. I'm using Hekili with Elvui.
Any help please?

ty

**Comment by Hekili** [comment]
You can move the displays any time the options window is open.

**Comment by JediMaDMZ** [comment]
thank you. The option window when is open covers the displays so I can't grab and move it

**Comment by Hekili** [comment]
You can move the options window out of the way, or set the display position in the Displays section.

**Comment by JediMaDMZ** [comment]
Solved tyvm :)
