### ISSUE TITLE
[BUG] Stutter every second after updating application. 

### ISSUE THREAD

**Issue by flapjak10** [Hekili/hekili#2581]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

While I have the Hekili addon enabled in the addon list in wow at all, meaning it can be paused or even if I uncheck the 'enable' part of the addon, I am constantly getting a frame or 2 fps stutter every ~1 second. Not only that, but I notice the addon memory increasing with each stutter seeming to indicate a memory leak or something of the sort, it increases it's memory along with Elvui and Details every second.

If I disable elvui and details the stutters continue and only remain so long as I have the hekili addon enabled. If I enable all my addons except for hekili the stutter no longer exists and no addons continually accrue memory. 

The screenshot below shows the addon's memory usage after logging on and running a single dungeon. It has climbed to over 50-60 mbs more than it usually uses and it continues to climb. 
![Screenshot 2023-05-07 013432](https://user-images.githubusercontent.com/89975902/236659690-2034b865-5a69-4433-abd7-a945fac6b151.png)

There are NO errors accumulating in my bugsack at all. 

### How to Reproduce

I logged in and enabled the addon. 

### Player Information (Link)

https://pastebin.com/uFUX3QRH

### Error Messages (Link)

There are none. 

### Contact Information

Flap#2987

**Comment by flapjak10** [comment]
Just want to say that I saw a thread about it happening in combat only and with past versions, this is a new issue for me as it only happened within the past week, I had been using it fine before that, and it happens ALL the time not just during combat. I log in, enable the addon, and constant stutters unless I go into the addon list and turn it off.

**Comment by Hekili** [comment]
> The screenshot below shows the addon's memory usage after logging on and running a single dungeon. It has climbed to over 50-60 mbs more than it usually uses and it continues to climb.

Memory usage, generally speaking, doesn't really matter at all.  All it indicates is that there is unused data that the garbage collector hasn't taken care of yet.  You can watch it go away by typing `/run collectgarbage()` -- the garbage collector will fire automatically if/when it needs to do so.  If I want to prevent that memory usage from increasing until the garbage collector has a reason to clean up, the tradeoff is to use CPU time to clean and recycle tables that's generally not worth doing.

> Just want to say that I saw a thread about it happening in combat only and with past versions, this is a new issue for me as it only happened within the past week,

This is the part that does matter.  With which exact version did you start noticing an issue with stuttering on your Enhancement Shaman?

**Comment by flapjak10** [comment]
> This is the part that does matter. With which exact version did you start noticing an issue with stuttering on your Enhancement Shaman?

It was not this latest update that happened yesterday (Saturday the 6th) but the update right before that. I am not sure what number that was.

**Comment by flapjak10** [comment]
Okay after some testing today it looks like it is just happening when I load the addon on just my shaman, it happens whether I'm in enhance, ele, or resto spec. 

I thought maybe the settings could be weird/different for my different characters but they are all the same. I have not adjusted the spell list or priority list, it is just the default hekili.

**Comment by Hekili** [comment]
> It was not this latest update that happened yesterday (Saturday the 6th) but the update right before that. I am not sure what number that was.

Could you test to confirm?  You can upgrade/downgrade using the Releases section here or via CurseForge.  I can't guarantee that I'll see the same issues that you see.

**Comment by Hekili** [comment]
Just a head's up; I will close the ticket and investigate on my own if you're not able to identify the last version that *didn't* have this issue for you.  (Dates aren't good enough.)  Thanks!

**Comment by Debugga-nb** [comment]
I am seeing the same issue. I'm on a Vengeance DH. I have my hekili set to "hide outside combat" by setting default and target to 0, leaving combat and w/target active. So maybe it's something there?
If I kill WA in the addon list no stutter. I do use weakauras and details, and such. I'm noticing i'm not seeing the frame drops in combat. BUT I am seeing them in "world" when a weakaura is active, and hekili is hidden.


I can try to pull some additional information if you need it, but in my experience, this is a pretty regular occurrence after a major patch. If it wasn't my raid night, I probably would just be waiting it out. You usually get it updated in the first couple weeks of the major patches, so I just go the "patience" route.

**Comment by Hekili** [comment]
It matters when you've tested and what version you're using. I made changes yesterday that are meant to reduce this issue. If you have additional information, make sure to post the addon version and a snapshot or detailed information about class/spec and situation.

**Comment by Debugga-nb** [comment]
Will do. I update my addons before I launch the client to play, but just now, Hekili flagged for an update. So I'll grab that, and get back to you.
