### ISSUE TITLE
[FEATURE] Allow Felstorm Demo spell be in the spell priority list

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2584]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Since the Demo pet very often triggers [Felstorm](https://www.wowhead.com/spell=89751/felstorm) out of the blue, wouldn't it be a good idea to place the Felstorm spell as part of the priority list (and on the pet's tab switched off by default) and only use it as a recommendation when the demonic pet is within the melee range of the mob/adds?

**Comment by Hekili** [comment]
I haven't seen any recent material about folks manually controlling Felstorm, but it's something I could do. One advantage would be that you'd also get more control over Guillotine. I'll think about it a bit.

**Comment by marekCs** [comment]
Thank you very much.

**Comment by marekCs** [comment]
Hello, I fully respect that you do not have much free time to add this action. I would just ask for a quick review pls, is it ok like this?
```
felstorm = {
        id = 89751,
        cast = 0,
        cooldown = 20,
        gcd = "spell",
        school = "physical",
        spend = 60,
        spendType = "energy",
        startsCombat = false,
        toggle = "cooldowns",
        handler = function ()
           applyBuff( "felstorm" )
        end,
    }
```

**Comment by marekCs** [comment]
I'm just not sure if school is nature or physical and also if it's 60 energy, can I write spend = 60

**Comment by Hekili** [comment]
The energy piece won't actually check the pet's resources.  The school doesn't matter (but it's almost certainly not nature).
