### ISSUE TITLE
[REC] Druid Restoration, Not Using Wrath

### ISSUE THREAD

**Issue by danmarzola** [Hekili/hekili#2585]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Druid Restoration DPS Rotation, don't recommend using wrath unless you use convoke, what is kind weird as it keep recommending using skill on CD or refreshing dots without need

### How to Reproduce

1. Follow Druid Resto Priority
2. Don't use Convoke

### Snapshot (Link)

https://pastebin.com/tXBiPUvQ

### Additional Information

build: v10.1.0-1.0.0g
level: 70 (70)
class: DRUID
spec: restoration

talents: BkGAjgO5l4zUDkYE8W5/Dtff2hkEtSSSSKSLJwBSjmWkEAAAAAAAAAAAAQRAJJBBJASCJRKk0SAAAAAAICAAA
    adaptive_swarm = 1/1
    astral_influence = 2/2
    budding_leaves = 1/2
    cenarion_ward = 1/1
    cenarius_guidance = 1/1
    convoke_the_spirits = 1/1
    cultivation = 1/1
    deep_focus = 1/1
    efflorescence = 1/1
    flash_of_clarity = 1/1
    flourish = 1/1
    grove_tending = 1/1
    harmonious_blooming = 2/2
    improved_barkskin = 1/1
    improved_regrowth = 1/1
    improved_rejuvenation = 1/1
    improved_sunfire = 1/1
    incapacitating_roar = 1/1
    inner_peace = 1/1
    innervate = 1/1
    ironbark = 1/1
    ironfur = 1/1
    lifebloom = 1/1
    lycaras_teachings = 3/3
    matted_fur = 1/1
    moonkin_form = 1/1
    natural_recovery = 2/2
    natures_swiftness = 1/1
    natures_vigil = 1/1
    nurturing_instinct = 2/2
    omen_of_clarity = 1/1
    photosynthesis = 1/1
    rampant_growth = 1/1
    rejuvenation = 1/1
    renewal = 1/1
    soothe = 1/1
    soul_of_the_forest = 1/1
    spring_blossoms = 1/1
    stampeding_roar = 1/1
    starfire = 1/1
    starsurge = 1/1
    sunfire = 1/1
    swiftmend = 1/1
    thick_hide = 2/2
    tranquility = 1/1
    typhoon = 1/1
    unbridled_swarm = 1/1
    undergrowth = 1/1
    unstoppable_growth = 2/2
    ursols_vortex = 1/1
    verdancy = 1/1
    verdant_heart = 1/1
    wild_charge = 1/1
    wild_growth = 1/1
    yseras_gift = 1/1

pvptalents: focused_growth
   keeper_of_the_grove
   reactive_resin

covenant: none

conduits: none

soulbinds: []

sets: satchel_of_healing_spores = 1
    tier29 = 1

gear: deeprock_cloak = 1
    epaulets_of_raging_tempests = 1
    glacial_bindings = 1
    heat_of_primal_winter = 1
    icewraths_channeling_conduit = 1
    leggings_of_flowing_flame = 1
    lost_landcallers_claws = 1
    onyx_annulet = 1
    primal_molten_spellblade = 1
    satchel_of_healing_spores = 1
    scalewardens_leather_belt = 1
    signet_of_titanic_insight = 1
    sunless_tunic = 1
    tier29 = 1
    volatile_crystal_shard = 1
    waders_of_raging_tempests = 1
    windborne_hatsuburi = 1

legendaries: none

itemIDs: 190506, 192999, 195484, 195492, 199425, 199432, 200353, 200744, 201962, 203460, 204714, 204914, 204928, 205192, 205303, 206218

settings: aoe = 3
    combatRefresh = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxTime = 20
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Restoration Druid
    petbased = false
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true [separate]
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = false 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    adaptive_swarm        = SE  [05]
    barkskin              = Q   [05]
    bear_form             = AQ  [05]
    cenarion_ward         = F3  [06]
    convoke_the_spirits   = X   [05]
    dash                  = SR  [05]
    efflorescence         = M3  [03]
    entangling_roots      = F1  [06]
    flourish              = G   [03]
    frenzied_regeneration = 1   [09]
    incapacitating_roar   = Z   [05], 3   [09]
    innervate             = R   [05]
    mark_of_the_wild      = F6  [06], A5  [10]
    moonfire              = 3   [01], 3   [10]
    prowl                 = M4  [03]
    renewal               = AE  [05]
    soothe                = F2  [06]
    stampeding_roar       = AT  [03]
    starfire              = F   [03]
    starsurge             = 4   [01], 4   [10]
    sunfire               = 1   [01], 1   [10]
    thrash                = 2   [09]
    thrash_bear           = 2   [09]
    thrash_cat            = 2   [09]
    tranquility           = SG  [03]
    typhoon               = E   [05]
    ursols_vortex         = SF  [03]
    wild_charge           = T   [03]
    wrath                 = 2   [01], SQ  [05], 2   [10]

warnings: none

**Comment by Hekili** [comment]
That's not the complete snapshot. You have to press CTRL-A to select all text before copying.

**Comment by danmarzola** [comment]
> That's not the complete snapshot. You have to press CTRL-A to select all text before copying.

Updated

**Comment by Hekili** [comment]
Thanks. I can see that Wrath is being treated as unusable in your current form, so I guess my implementation isn't accounting for Moonkin talent being available as Resto. I'll take a look tomorrow or Thursday. 

In the meantime, you can probably open up DruidRestoration.lua, look for `wrath = {` under RegisterAbilities, then see if there's a line that says `noform` or `nobuff` and delete it.

**Comment by Hekili** [comment]
I just checked there and didn't find it. It may be a spell ID difference that isn't captured. I'll look when I'm home.

**Comment by Hekili** [comment]
I have not been able to replicate this issue.

**Comment by djsegal** [comment]
I believe this is happening again, along with `Starfire`

I cant seem to get either to show up in the prio queue
