### ISSUE TITLE
Basic Rotation is not showing for Brewmaster Monk

### ISSUE THREAD

**Issue by Vdubbala** [Hekili/hekili#2586]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Was working fine yesterday to some degree (purifying brew was not showing up in the rotation) but when i logged into the game this morning the basic dps rotation was not showing.  The add-on was just showing Summon White Tiger Statue and Weapons of Order.

### How to Reproduce

1. Log into game as a brewmaster

### Snapshot (Link)

https://pastebin.com/7ShpCfEi

### Contact Information

Vdubbala#7903

**Comment by Vdubbala** [comment]
actions.precombat+=/potion
actions.precombat+=/chi_burst,if=talent.chi_burst.enabled
actions.precombat+=/chi_wave,if=talent.chi_wave.enabled
## Blackout Combo
## actions.precombat+=/variable,name=boc_count,op=set,value=0

actions+=/spear_hand_strike
actions+=/diffuse_magic
actions+=/purifying_brew,if=settings.purify_for_celestial&(time_to_max_charges<gcd.max|buff.purified_chi.up&buff.purified_chi.remains<1.5*gcd.max)|cooldown.celestial_brew.remains<2*gcd.max&charges_fractional>1.5
actions+=/celestial_brew,if=tanking&(!talent.improved_celestial_brew|buff.purified_chi.up)&buff.blackout_combo.down
actions+=/purifying_brew,line_cd=5,if=talent.improved_invoke_niuzao_the_black_ox&settings.purify_for_niuzao&pet.niuzao_the_black_ox.active
# Use configured purify_stagger_currhp from Brewmaster options.
actions+=/purifying_brew,if=group&buff.blackout_combo.down&settings.purify_stagger_currhp>0&stagger.pct>=settings.purify_stagger_currhp
# Use configured purify_stagger_currhp from Brewmaster options.
actions+=/purifying_brew,if=solo&buff.blackout_combo.down&settings.purify_stagger_currhp>0&stagger.pct>=settings.purify_stagger_currhp*0.5
# Use configured purify_stagger_maxhp from Brewmaster options.
actions+=/purifying_brew,if=group&buff.blackout_combo.down&settings.purify_stagger_maxhp>0&stagger.pct>=settings.purify_stagger_maxhp
# Use configured purify_stagger_maxhp from Brewmaster options.
actions+=/purifying_brew,if=solo&buff.blackout_combo.down&settings.purify_stagger_maxhp>0&stagger.pct>=settings.purify_stagger_maxhp*0.5
# Stagger % of 20 will kill you in 2.5 seconds without healing or purifying.  Used when purify_stagger_currhp and maxhp are disabled.
actions+=/purifying_brew,if=group&buff.blackout_combo.down&settings.purify_stagger_currhp=0&settings.purify_stagger_maxhp=0&stagger.pct>20
# Stagger % of 10 will kill you in 5 seconds without healing or purifying.  Used when purify_stagger_currhp and maxhp are disabled.
actions+=/purifying_brew,if=solo&buff.blackout_combo.down&settings.purify_stagger_currhp=0&settings.purify_stagger_maxhp=0&stagger.pct>10
actions+=/dampen_harm,if=health.pct<75&incoming_damage_3s>health.max*(0.2+(0.2*group))&buff.fortifying_brew.down
actions+=/fortifying_brew,if=health.pct<50&incoming_damage_3s>health.max*(0.2+(0.2*group))&(buff.dampen_harm.down)
actions+=/potion
actions+=/summon_white_tiger_statue,if=talent.summon_white_tiger_statue.enabled
actions+=/touch_of_death
actions+=/use_items,if=debuff.weapons_of_order_debuff.stack>3|talent.weapons_of_order|boss&fight_remains<25
actions+=/blood_fury
actions+=/berserking
actions+=/lights_judgment
actions+=/fireblood
actions+=/ancestral_call
actions+=/bag_of_tricks
actions+=/call_action_list,name=cooldowns_improved_niuzao_woo,strict=1,if=(talent.invoke_niuzao_the_black_ox.rank+talent.improved_invoke_niuzao_the_black_ox.rank)=2&(talent.weapons_of_order.rank+talent.call_to_arms.rank)<=1
actions+=/call_action_list,name=cooldowns_improved_niuzao_cta,strict=1,if=(talent.invoke_niuzao_the_black_ox.rank+talent.improved_invoke_niuzao_the_black_ox.rank)=2&(talent.weapons_of_order.rank+talent.call_to_arms.rank)=2
actions+=/call_action_list,name=cooldowns_niuzao_woo,strict=1,if=(talent.invoke_niuzao_the_black_ox.rank+talent.improved_invoke_niuzao_the_black_ox.rank)<=1
actions+=/call_action_list,name=rotation_boc_dfb,strict=1,if=talent.blackout_combo.enabled&talent.dragonfire_brew.enabled&talent.salsalabims_strength.enabled
actions+=/call_action_list,name=rotation_dfb,strict=1,if=talent.dragonfire_brew.enabled&talent.salsalabims_strength.enabled
actions+=/call_action_list,name=rotation_chp,strict=1,if=talent.charred_passions.enabled&talent.salsalabims_strength.enabled

## Use <a href='https://www.wowhead.com/spell=10060/power-infusion'>Power Infusion</a> when <a href='https://www.wowhead.com/spell=387184/weapons-of-order'>Weapons of Order</a> reaches 4 stacks.
## actions.cooldowns_niuzao_woo+=/invoke_external_buff,name=power_infusion,if=buff.weapons_of_order.remains<=20
actions.cooldowns_niuzao_woo+=/weapons_of_order,if=(talent.weapons_of_order.enabled)&((equipped.beacon_to_the_beyond&trinket.beacon_to_the_beyond.cooldown.remains<30)|(!equipped.beacon_to_the_beyond))
actions.cooldowns_niuzao_woo+=/bonedust_brew,if=!buff.bonedust_brew.up&debuff.weapons_of_order_debuff.stack>3
actions.cooldowns_niuzao_woo+=/bonedust_brew,if=!buff.bonedust_brew.up&!buff.weapons_of_order.up&cooldown.weapons_of_order.remains>10
actions.cooldowns_niuzao_woo+=/exploding_keg,if=buff.bonedust_brew.up
actions.cooldowns_niuzao_woo+=/invoke_niuzao_the_black_ox,if=buff.weapons_of_order.remains<=16&talent.weapons_of_order.enabled
actions.cooldowns_niuzao_woo+=/invoke_niuzao_the_black_ox,if=!talent.weapons_of_order.enabled
## actions.cooldowns_niuzao_woo+=/purifying_brew,if=stagger.amounttototalpct>=0.7&!buff.blackout_combo.up
## actions.cooldowns_niuzao_woo+=/purifying_brew,if=cooldown.purifying_brew.remains_expected<5&!buff.blackout_combo.up

## Use <a href='https://www.wowhead.com/spell=10060/power-infusion'>Power Infusion</a> when <a href='https://www.wowhead.com/spell=387184/weapons-of-order'>Weapons of Order</a> reaches 4 stacks.
## actions.cooldowns_improved_niuzao_woo+=/invoke_external_buff,name=power_infusion,if=buff.weapons_of_order.remains<=20
## actions.cooldowns_improved_niuzao_woo+=/variable,name=pb_in_window,op=set,value=floor(cooldown.purifying_brew.charges_fractional+(20+4*0.05)%cooldown.purifying_brew.duration%0.65),if=prev.invoke_niuzao_the_black_ox
## actions.cooldowns_improved_niuzao_woo+=/variable,name=pb_in_window,op=sub,value=1,if=prev.purifying_brew&time-action.invoke_niuzao_the_black_ox.last_used<=20+4*0.05
## actions.cooldowns_improved_niuzao_woo+=/purifying_brew,if=(time-action.purifying_brew.last_used>=20+4*0.05-time+action.invoke_niuzao_the_black_ox.last_used%variable.pb_in_window&time-action.invoke_niuzao_the_black_ox.last_used<=20+4*0.05)
## actions.cooldowns_improved_niuzao_woo+=/purifying_brew,use_off_gcd=1,if=(variable.pb_in_window=0&20+4*0.05-time+action.invoke_niuzao_the_black_ox.last_used<1&20+4*0.05-time+action.invoke_niuzao_the_black_ox.last_used>0)
actions.cooldowns_improved_niuzao_woo+=/weapons_of_order,if=(talent.weapons_of_order.enabled)&((equipped.beacon_to_the_beyond&trinket.beacon_to_the_beyond.cooldown.remains<30)|(!equipped.beacon_to_the_beyond))
actions.cooldowns_improved_niuzao_woo+=/bonedust_brew,if=!buff.bonedust_brew.up&debuff.weapons_of_order_debuff.stack>3
actions.cooldowns_improved_niuzao_woo+=/bonedust_brew,if=!buff.bonedust_brew.up&!buff.weapons_of_order.up&cooldown.weapons_of_order.remains>10
actions.cooldowns_improved_niuzao_woo+=/exploding_keg,if=buff.bonedust_brew.up
## actions.cooldowns_improved_niuzao_woo+=/purifying_brew,if=cooldown.invoke_niuzao_the_black_ox.remains<=3.5&time-action.purifying_brew.last_used>=3.5+cooldown.invoke_niuzao_the_black_ox.remains
actions.cooldowns_improved_niuzao_woo+=/invoke_niuzao_the_black_ox,if=time-action.purifying_brew.last_used<=5
## actions.cooldowns_improved_niuzao_woo+=/purifying_brew,if=cooldown.purifying_brew.full_recharge_time*2<=cooldown.invoke_niuzao_the_black_ox.remains-3.5

## Use <a href='https://www.wowhead.com/spell=10060/power-infusion'>Power Infusion</a> when <a href='https://www.wowhead.com/spell=387184/weapons-of-order'>Weapons of Order</a> reaches 4 stacks.
## actions.cooldowns_improved_niuzao_cta+=/invoke_external_buff,name=power_infusion,if=buff.weapons_of_order.remains<=20
## actions.cooldowns_improved_niuzao_cta+=/variable,name=pb_in_window,op=set,value=floor(cooldown.purifying_brew.charges_fractional+(10+2*0.05)%cooldown.purifying_brew.duration%0.65),if=prev.weapons_of_order
## actions.cooldowns_improved_niuzao_cta+=/variable,name=pb_in_window,op=set,value=floor(cooldown.purifying_brew.charges_fractional+(20+4*0.05)%cooldown.purifying_brew.duration%0.65),if=prev.invoke_niuzao_the_black_ox
## actions.cooldowns_improved_niuzao_cta+=/variable,name=pb_in_window,op=sub,value=1,if=prev.purifying_brew&(time-action.weapons_of_order.last_used<=10+2*0.05|time-action.invoke_niuzao_the_black_ox.last_used<=20+4*0.05)
## actions.cooldowns_improved_niuzao_cta+=/purifying_brew,if=(time-action.purifying_brew.last_used>=10+2*0.05-time+action.weapons_of_order.last_used%variable.pb_in_window&time-action.weapons_of_order.last_used<=10+2*0.05)
## actions.cooldowns_improved_niuzao_cta+=/purifying_brew,if=(time-action.purifying_brew.last_used>=20+4*0.05-time+action.invoke_niuzao_the_black_ox.last_used%variable.pb_in_window&time-action.invoke_niuzao_the_black_ox.last_used<=20+4*0.05)
## actions.cooldowns_improved_niuzao_cta+=/purifying_brew,use_off_gcd=1,if=(variable.pb_in_window=0&20+4*0.05-time+action.invoke_niuzao_the_black_ox.last_used<1&20+4*0.05-time+action.invoke_niuzao_the_black_ox.last_used>0)
## actions.cooldowns_improved_niuzao_cta+=/purifying_brew,if=cooldown.weapons_of_order.remains<=3.5&time-action.purifying_brew.last_used>=3.5+cooldown.weapons_of_order.remains
actions.cooldowns_improved_niuzao_cta+=/weapons_of_order,if=(time-action.purifying_brew.last_used<=5)&((equipped.beacon_to_the_beyond&trinket.beacon_to_the_beyond.cooldown.remains<30)|(!equipped.beacon_to_the_beyond))
actions.cooldowns_improved_niuzao_cta+=/bonedust_brew,if=!buff.bonedust_brew.up&debuff.weapons_of_order_debuff.stack>3
actions.cooldowns_improved_niuzao_cta+=/bonedust_brew,if=!buff.bonedust_brew.up&!buff.weapons_of_order.up&cooldown.weapons_of_order.remains>10
actions.cooldowns_improved_niuzao_cta+=/exploding_keg,if=buff.bonedust_brew.up
## actions.cooldowns_improved_niuzao_cta+=/purifying_brew,if=cooldown.invoke_niuzao_the_black_ox.remains<=3.5&time-action.purifying_brew.last_used>=3.5+cooldown.invoke_niuzao_the_black_ox.remains&buff.weapons_of_order.remains<=30-17
actions.cooldowns_improved_niuzao_cta+=/invoke_niuzao_the_black_ox,if=buff.weapons_of_order.remains<=30-17&action.purifying_brew.last_used>action.weapons_of_order.last_used+10+2*0.05
## actions.cooldowns_improved_niuzao_cta+=/purifying_brew,if=cooldown.purifying_brew.full_recharge_time*2<=cooldown.weapons_of_order.remains-3.5&cooldown.purifying_brew.full_recharge_time*2<=cooldown.invoke_niuzao_the_black_ox.remains-3.5

actions.rotation_boc_dfb+=/blackout_kick
actions.rotation_boc_dfb+=/rising_sun_kick,if=talent.rising_sun_kick.enabled
actions.rotation_boc_dfb+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled&buff.rushing_jade_wind.remains<1
actions.rotation_boc_dfb+=/breath_of_fire,if=buff.blackout_combo.up
actions.rotation_boc_dfb+=/keg_smash
actions.rotation_boc_dfb+=/black_ox_brew,if=energy+energy.regen*(cooldown.keg_smash.full_recharge_time*(1-cooldown.keg_smash.charges_fractional))>=65&talent.black_ox_brew.enabled
actions.rotation_boc_dfb+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled
actions.rotation_boc_dfb+=/spinning_crane_kick,if=active_enemies>1&energy+energy.regen*(cooldown.keg_smash.full_recharge_time*(1-cooldown.keg_smash.charges_fractional))>=65
actions.rotation_boc_dfb+=/spinning_crane_kick,if=active_enemies>1|(talent.walk_with_the_ox.enabled&talent.charred_passions.enabled)
actions.rotation_boc_dfb+=/expel_harm,if=energy+energy.regen*(cooldown.keg_smash.full_recharge_time*(1-cooldown.keg_smash.charges_fractional))>=65
actions.rotation_boc_dfb+=/tiger_palm,if=active_enemies=1
actions.rotation_boc_dfb+=/celestial_brew,if=talent.celestial_brew.enabled&!buff.blackout_combo.up
actions.rotation_boc_dfb+=/chi_wave,if=talent.chi_wave.enabled
actions.rotation_boc_dfb+=/chi_burst,if=talent.chi_burst.enabled
actions.rotation_boc_dfb+=/call_action_list,name=rotation_fallback

actions.rotation_dfb+=/blackout_kick
actions.rotation_dfb+=/rising_sun_kick,if=talent.rising_sun_kick.enabled
actions.rotation_dfb+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled&buff.rushing_jade_wind.remains<1
actions.rotation_dfb+=/breath_of_fire
actions.rotation_dfb+=/keg_smash
actions.rotation_dfb+=/black_ox_brew,if=energy+energy.regen*(cooldown.keg_smash.full_recharge_time*(1-cooldown.keg_smash.charges_fractional))>=65&talent.black_ox_brew.enabled
actions.rotation_dfb+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled
actions.rotation_dfb+=/spinning_crane_kick,if=active_enemies>1|(talent.walk_with_the_ox.enabled&talent.charred_passions.enabled)
actions.rotation_dfb+=/expel_harm,if=energy+energy.regen*(cooldown.keg_smash.full_recharge_time*(1-cooldown.keg_smash.charges_fractional))>=65
actions.rotation_dfb+=/tiger_palm,if=active_enemies=1
actions.rotation_dfb+=/celestial_brew,if=talent.celestial_brew.enabled
actions.rotation_dfb+=/chi_wave,if=talent.chi_wave.enabled
actions.rotation_dfb+=/chi_burst,if=talent.chi_burst.enabled
actions.rotation_dfb+=/call_action_list,name=rotation_fallback

actions.rotation_chp+=/breath_of_fire,if=!buff.charred_passions.up
actions.rotation_chp+=/blackout_kick
actions.rotation_chp+=/rising_sun_kick,if=talent.rising_sun_kick.enabled
actions.rotation_chp+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled&buff.rushing_jade_wind.remains<1
actions.rotation_chp+=/keg_smash
actions.rotation_chp+=/black_ox_brew,if=energy+energy.regen*(cooldown.keg_smash.full_recharge_time*(1-cooldown.keg_smash.charges_fractional))>=65&talent.black_ox_brew.enabled
actions.rotation_chp+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled
actions.rotation_chp+=/spinning_crane_kick,if=active_enemies>1|(talent.walk_with_the_ox.enabled&talent.charred_passions.enabled)
actions.rotation_chp+=/expel_harm,if=energy+energy.regen*(cooldown.keg_smash.full_recharge_time*(1-cooldown.keg_smash.charges_fractional))>=65
actions.rotation_chp+=/tiger_palm,if=active_enemies=1
actions.rotation_chp+=/celestial_brew,if=talent.celestial_brew.enabled&!buff.blackout_combo.up
actions.rotation_chp+=/chi_wave,if=talent.chi_wave.enabled
actions.rotation_chp+=/chi_burst,if=talent.chi_burst.enabled
actions.rotation_chp+=/call_action_list,name=rotation_fallback

actions.rotation_fallback+=/rising_sun_kick,if=talent.rising_sun_kick.enabled
actions.rotation_fallback+=/keg_smash
actions.rotation_fallback+=/breath_of_fire,if=talent.breath_of_fire.enabled
actions.rotation_fallback+=/blackout_kick
actions.rotation_fallback+=/black_ox_brew,if=energy+energy.regen*(cooldown.keg_smash.remains+execute_time)>=65&talent.black_ox_brew.enabled
actions.rotation_fallback+=/rushing_jade_wind,if=talent.rushing_jade_wind.enabled
actions.rotation_fallback+=/spinning_crane_kick,if=active_enemies>1|(talent.walk_with_the_ox.enabled&talent.charred_passions.enabled)
actions.rotation_fallback+=/expel_harm
actions.rotation_fallback+=/tiger_palm,if=active_enemies=1
actions.rotation_fallback+=/celestial_brew,if=!buff.blackout_combo.up&talent.celestial_brew.enabled
actions.rotation_fallback+=/chi_wave,if=talent.chi_wave.enabled
actions.rotation_fallback+=/chi_burst,if=talent.chi_burst.enabled

**Comment by Wyste** [comment]
Your snapshot is incomplete, you need to click in the box, press CTRL-A , then CTRL-C to copy everything that's in the box. There is a bunch of text that should be within that very small box.

**Comment by Vdubbala** [comment]
That was the full string in the snapshot.  The only two abilities in the rotation that are showing is that and that's all the snapshot grabbed

**Comment by Hekili** [comment]
No, you have to press CTRL+A to select all text (including hidden text) before copying.

**Comment by Vdubbala** [comment]
https://pastebin.com/mPdv0ngx

*Moved to Pastebin per instructions.*

**Comment by Vdubbala** [comment]
I did try reset the add on to default setting and resetting the priorities as I saw mentioned in previous posts that seemed to have the same type of issue that i am having and that didn't appear to fix the issue

**Comment by Vdubbala** [comment]
Another update, i reset my talents and reapplied them and that appeared to fix the issue.
