### ISSUE TITLE
[REC] Enhancement Shaman AoE Rotation Flame Shock issue

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2587]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When Primordial Wave is on cooldown Flame Shock will not get recommended for spread with Lava Lash for quite a bit. I haven't been playing my shaman until the patch so I didn't notice any changes through the different updates. My assumption is you should have Flame Shock on to spread as a top priority not matter what. 

### How to Reproduce

1. Enter game as Enhancement Shaman.
2. Target Dummies total of 5.
3. Use Primordial Wave to put it on CD to simulate starting a pack with it on CD.
4. Rotation starts out with Crash > IS >Lash/EB .. etc etc No Flame Shock to spread and it usually gets pushed back.

### Snapshot (Link)

https://pastebin.com/0Ne2V11n

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nYbxd285dqScLg9hKzgXGk

**Comment by Hekili** [comment]
> Rotation starts out with Crash > IS >Lash/EB .. etc etc No Flame Shock to spread and it usually gets pushed back.

The snapshot you provided shows the following:

> Sundering(0.00), Flame Shock(1.19), Stormstrike(2.39), Crash Lightning(3.59), Lava Lash(4.79), Ice Strike(5.99), Elemental Blast(7.19), Frost Shock(8.39), Stormstrike(9.59), Flame Shock(13.81)

In the `aoe` action list, Sundering is the last entry that's a higher priority than applying Flame Shock when it isn't already ticking and you have Molten Assault talented.  So you get Sundering, followed by Flame Shock.  Lava Lash was recommended at 4.79 because that's the first time that the GCD wasn't active and LL wasn't on cooldown.

Is there another snapshot that shows what you were describing?

**Comment by Bingo176** [comment]
So that is with me burning my primordial wave CD before combat to simulate starting another pull with it on CD. Looks like about 9 seconds before it recommends Flame Shock. Sometimes it is about 2-3 lava lashes before a flame shock without a spread. 

https://pastebin.com/tDHu4DnR
![image](https://github.com/Hekili/hekili/assets/25187247/499e2721-290f-44dc-b49b-d4cecb1c8408)

**Comment by Hekili** [comment]
Yeah, that's pretty consistent with what the sim would do, if PWave were unavailable at the start:

<html><body>


Time | List  | # | Name | Target | Resources | Buffs
-- | -- | -- | -- | -- | -- | --
0:00.000 | default | A | bloodlust | Fluffy_Pillow | 50000.0/50000: 100% mana | flurry(3)
0:00.000 | default | B | potion | Fluffy_Pillow | 49000.0/50000: 98% mana | bloodlust, flurry(3)
0:00.000 | default | C | auto_attack | Fluffy_Pillow | 49000.0/50000: 98% mana | bloodlust, flurry(3), elemental_potion_of_ultimate_power
0:00.000 | default | D | feral_spirit | Fluffy_Pillow | 49000.0/50000: 98% mana | bloodlust, flurry(2), elemental_potion_of_ultimate_power
0:00.921 | aoe | J | crash_lightning | Fluffy_Pillow | 50000.0/50000: 100% mana | bloodlust, flurry, feral_spirit, icy_edge, crackling_surge, maelstrom_weapon(2), elemental_potion_of_ultimate_power
0:01.843 | aoe | K | ice_strike | Fluffy_Pillow | 50000.0/50000: 100% mana | bloodlust, flurry(2), feral_spirit, icy_edge,  crackling_surge, crash_lightning, stormbringer, maelstrom_weapon(2),  elemental_potion_of_ultimate_power
0:02.764 | aoe | L | lava_lash | Fluffy_Pillow | 49823.6/50000: 100% mana | bloodlust, flurry(2), feral_spirit, icy_edge,  crackling_surge, crash_lightning, stormbringer, maelstrom_weapon(5),  ice_strike, elemental_potion_of_ultimate_power
0:03.684 | aoe | N | sundering | Fluffy_Pillow | 50000.0/50000: 100% mana | bloodlust, flurry(2), feral_spirit, icy_edge,  crackling_surge, crash_lightning, stormbringer, maelstrom_weapon(7),  ice_strike, elemental_potion_of_ultimate_power
0:04.604 | aoe | O | flame_shock | Fluffy_Pillow | 48472.0/50000: 97% mana | bloodlust, flurry(3), feral_spirit, icy_edge,  crackling_surge, crash_lightning, stormbringer, maelstrom_weapon(8),  ice_strike, elemental_potion_of_ultimate_power


</body>
</html>

Having Primordial Wave talented, but not having it at the start of a pull, isn't really what the sim priority is written for.  It does look like using Flame Shock if none are applied can be a DPS gain in sustained AOE (5 minutes), if I make Primordial Wave unavailable for the first 10 seconds of a pull:

![image](https://github.com/Hekili/hekili/assets/9438134/a071db9b-e77c-4166-909b-fd9df5b51172)

It's only 0.5% overall, with a minor drop to priority target DPS.  In a one minute fight, it's more valuable, which might be a better representation of going pack-to-pack:

![image](https://github.com/Hekili/hekili/assets/9438134/a74c734c-12fa-42d9-8314-260ccf2a88e1)

These circumstances are pretty weird, though.  If you were going pack-to-pack, having all of your short rotational abilities off cooldown and in the way of reaching the lower priority Flame Shock shouldn't be incredibly common.  That said, I'll probably go ahead and shoehorn this in to the default priority.

**Comment by Bingo176** [comment]
It feels weird to me. Was this a change in 10.1 in the APL? I always remember moving pack to pack and it recommending Flame Shock to force the Lava Lash spread. Just curious is all.

**Comment by basalt51** [comment]
I agree, something seems weird. And I'm not sure if it is related, but my ability preview shows Primordial Wave -> Lava Lash ->Chain Lightning. It doesn't recommend Lighting bolt until after the lava lash is cast. I don't remember it doing this.

**Comment by Bingo176** [comment]
So i rolled back to an older version to see where I saw the old functionality of Flame Shock that I was describing.

Hekili-v10.0.7-1.0.6 is where I see the functionality as seen below. Primordial Wave on CD etc.

![image](https://github.com/Hekili/hekili/assets/25187247/210d9beb-28e5-4df9-b407-7254592d0e65)

https://pastebin.com/A9CArkfV

**Comment by Hekili** [comment]
The snapshot and screenshot in your last post don't agree with one another.

**Comment by Bingo176** [comment]
https://pastebin.com/9eg9gAmR  -- Precombat with Primoridal Wave on CD.
https://pastebin.com/ANK5BU4S  -- Flame Shock Recommended after Crash with Primordial Wave on CD

**Comment by Hekili** [comment]
This is fixed in 1.0.1.
