### ISSUE TITLE
SV Hunter: Preventing pets from proccing Coordinated Assault empowerment prevents Kill Shot recs

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#2588]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

If you use a macro for guides that is recommended for Coordinated Assault, then there will be no Kill Shot in the recommendation. For better efficiency during an active Coordinated Assault, we are required to use this macro. Without this macro, we lose in damage. Because not all Kill Shots will be enhanced.
![image](https://github.com/Hekili/hekili/assets/63850853/9afcae23-a53b-4bcb-a8df-92f042c5bcab)

### How to Reproduce

1. Make a macro on Coordinated Assault and Kill shot as indicated in the screenshot
2. Start a fight with dummies either in a real fight in 1 target or in AOE, you will not be recommended to Kill Shot during an active Coordinated Assault

### Snapshot (Link)

https://pastebin.com/P9zE0bTn

**Comment by MrBean73** [comment]
For me it works as intended. Remember that you use Killshot when the Coordinated Assault 's **empower** buff is active ( - this entry's criteria FAILS: buff.coordinated_assault_empower.up[false])

**Comment by Dragonfo** [comment]
It can't work as intended. Because in automatic mode, no one uses a pet kick during an active Coordinated Assault. The addon's recommendation should respond to this condition regardless of whether the pet's automatic kick is active or not. And it turns out that if the pet's kick is active, the rotation will not often show the Kill shot for the reason that it will wait for the pet's kickback. And if you put it in manual mode, the rotation will not show the Kill shot recommendation at all. This is not the right job. I do not know what you have working there. But there is a problem and this is a fact.

**Comment by MrBean73** [comment]
What do you mean with „pet kick“ ? If I use the recommended macros Hekili shows kill shot for me, when the empowered buff ist up and kill shot is ready.

**Comment by Hekili** [comment]
The addon reacts to the buff; if you're manually controlling the proccing of Coordinated Assault's empower buff *and* instantly consuming it via a macro, it makes sense that Kill Shot isn't recommended.  You're painting yourself into a corner.

I can probably accommodate this with a class setting, but if you manually create a feedback loop where the buff won't happen if you push the button that you only push if the buff is up, it makes sense that the ability won't be recommended.

You could also try customizing your priority; the entries for Kill Shot that check `buff.coordinated_assault_empower.up` could be changed to `buff.coordinated_assault.up` and probably get you what you're hoping for.

**Comment by Dragonfo** [comment]
buff.coordinated_assault.up solved all the problems. Now the addon also recommends the priority of Kill Shot regardless of whether the pet hit or not. Thank you, I manually changed what you wrote and now this is what I wanted to see in rotation. Of course, I would like you to be able to pay more attention to this macro in order to make it optional, maybe by clicking the button. Those who want to will just use buff.coordinated_assault.up with a macro in manual mode.

**Comment by Hekili** [comment]
I've added an option for this (which will also force a priority update).
