### ISSUE TITLE
Shadow Priest poor ST performance, too little Mind Spike Insanity casts

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#2589]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

it feels like mind spike insanity is way lower priority than it should be according to raidbot's rotation and guides. It's kinda hard to snapshot but basically hekili doesn't make me cast a single MSI for almost the entire duration of the burst up until like 25+s in, sometimes it's about to be recommended but it just swaps to something else, might be because the variables are a bit too strict on maximizing void bolt / mind blast procs and even making mindgames priority higher than supposedly. Generally it is wasting a lot of MSI procs in profit of casting mind blast off cooldown when it should effectively mind blast before MSI only to avoid capping and with shadowy insight procs. 

It also makes me halo early during burst window. On another note, the uptime of devouring plague seems a bit poor and that could be due to not generating enough insanity or trying to refresh it earlier than supposed to instead of using fillers without Mind Devourer procs, but that could also be due to my amount of haste, though raidbots says I should be around 87% uptime and in reality it's rather below 80%.

### How to Reproduce

Shadow priest opener using standard ST build with VOTI 4p

### Snapshot (Link)

https://pastebin.com/FrNNe3x6

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9mgUWYRdttkusoXFemHyfJ

### Contact Information

Nibana#6011

**Comment by Amortalist** [comment]
Added video of the rotation (you can see it takes 30s to start using MSI) : https://youtu.be/mBaIuIAS_C4

**Comment by Lipstopica** [comment]
This is something I have also noticed. It's spamming Mind Blast too much. Current SIMC is holding 1 charge of mind blast and using the Mind Spike Insanity and then using Mind Blast to stop it from capping

EDIT: Actually don't think that what I said above is the case. But it does seem to have less casts of Mind Spike Isanity. Maybe all rng with procs of other things like Mind Blast, DP etc

**Comment by Hekili** [comment]
Let me know if anything improves in the latest release (v10.1.0-1.0.0h).

**Comment by Amortalist** [comment]
Not much difference, it's still casting halo and mindgames before ever using MSI for me, sometimes halo before even void torrent in burst windows and otherwise tries to deplete mind blast as much as possible

**Comment by Hekili** [comment]
Okay, go ahead and provide an updated snapshot when it should be recommending MSI but isn't.

**Comment by Amortalist** [comment]
Ok so it's a bit hard to snapshot because of procs and such but basically here : https://pastebin.com/eFV2Ghhz

New raidbots sim cuz I changed a bit of gear : https://www.raidbots.com/simbot/report/vEFtHU8kBGgdtZqwEsQZJ5

It had me deplete mind blast charges while using DP as much as possible and then advised mindgames while overstacking MSI charges while never using them. Sometimes it seems to prefer to refresh DP a bit early (even using it two times in a row with bloodlust) thus losing some uptime on it but it's happening to fast to be sure

**Comment by Amortalist** [comment]
At the opener it's doing well until after void torrent, the rotation it's advising is : MB MB > CDS > VB > MB > DP > MB > VB > Torrent > VB > DP but then instead of going MB > MSI > VB > MB > MSI > Mindgames, it goes DP > MB > MB to deplete charges > VB > DP > Mindgames > DP > Halo > VB and only starts casting one MSI after 28 seconds, then back to depleting mind blast as much as possible.

Here is a little video again : https://youtu.be/7qZ6yz1THSs

**Comment by Hekili** [comment]
So, the moment we're concerned with is really once you've burned major CDs so they're out of the way, and you've used Devouring Plague to give yourself a charge of MSI.  I do see that I typoed the spell (it's looking for mind_flay_insanity instead of mind_spike_insanity), so it might work as expected once that's fixed.  I'll post an alpha build with the correction.

You can also change PriestShadow.lua line 1484 (under `mind_spike_insanity = {`) from...
    `buff = "mind_flay_insanity",`
...to...
    `buff = "mind_spike_insanity",`
...if you want to test more quickly.

**Comment by Amortalist** [comment]
Trying it out

**Comment by Amortalist** [comment]
It seems to work ! Casting way more MSI, testing a bit more extensively. 

I didn't have a way to find the line number so I just changed the two parts where "buff = "mind_flay_insanity" existed into spike version

**Comment by Amortalist** [comment]
Ok so it's much much better, I'm averaging my sim on 5 min dummy without lust, the only problem I see is that it's often recommending 3 MSI in a row but the reality is that it changes once you use the first one, and because you're thinking you have to recast it you're casting a second one, but once the first one hit it changes to something completely different (like mindgames), here is an example snapshot : https://pastebin.com/HpWGvpsi

**Comment by Hekili** [comment]
Ok, fix should be in place for v10.1.0-1.0.0i which is being built right now.  The issue you noted (Mind Spike Insanity not realizing it consumed the buff) should also be fixed.
