### ISSUE TITLE
Fire Mage - Hekili UI disappearing

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [Hekili/hekili#259]
I am just leveling my fire mage so it might be an issue that only pertains to sub 110 characters, but whenever I cast scorch or my mount, the UI disappears. It only returns after the cast is over. Perhaps this is useful to test on a 120 fire mage.

**Comment by Hekili** [comment]
You can generate a snapshot when that happens and I can take a brief look, but leveling (esp. sub-110) is not supported.

Fire Mage is going to get (another) rewrite soon as well.

**Comment by BuurmanDeBuurman** [comment]
https://pastebin.com/qPRh9QnY

Just pressing scorch

**Comment by Hekili** [comment]
Yeah, 31 is way too low to support.  Abilities change too much over the course of leveling.

You could probably write a simplified APL for Fire Mage for lower levels but there's no way to really optimize or test it.
