### ISSUE TITLE
[REC] Not Recommending Trueshot on single target

### ISSUE THREAD

**Issue by NokuraWoW** [Hekili/hekili#2591]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Trueshot is not being recommended under single target

### How to Reproduce

Start rotation, trueshot will show up as third spell then disappear even without getting a trueshot proc. 

### Player Information (Link)

https://pastebin.com/z274BNA4

### Error Messages (Link)

https://pastebin.com/7Asj3j5N

### Additional Information

https://pastebin.com/7Asj3j5N

### Contact Information

Nokura#1874

**Comment by Hekili** [comment]
I'll need a snapshot taken further into your opener (i.e., after Steady Focus is up, Serpent Sting is applied, and Stampede/Death Chakram/Wailing Arrow/Rapid Fire have been placed on cooldown (if talented/available).

**Comment by Hekili** [comment]
I've made priority adjustments that may address this.  If not, please provide the snapshot requested using the latest release.
