### ISSUE TITLE
[REC] Enhancement Shaman Primordial Wave Lava Lash Issue

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2592]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When you use primordial wave it does not suggest Lava Lash to spread Flame Shock before using lighting bolt on AoE.

![image](https://github.com/Hekili/hekili/assets/25187247/6363f1d0-f22b-4c5f-b060-dff881cd8847)

Using 10.1.0-1.0.0i

### How to Reproduce

1: Enter game as Enhancement Shaman.
2. Use Primordial Burst on Target Dummies with 5 present.

### Snapshot (Link)

https://pastebin.com/bypNT29r

**Comment by Hekili** [comment]
This will be fixed in 1.0.1.
