### ISSUE TITLE
[BUG] Feral Druid AOE not showing up

### ISSUE THREAD

**Issue by GitCadde** [Hekili/hekili#2593]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The AOE is not showing up for Feral Druid. Always Single Target.

### How to Reproduce

Enter Game as Feral Druid
Go to dummys and try to get AOE Rota

### Snapshot (Link)

https://pastebin.com/c0cCS6v1

### Contact Information

Captain Stardust#6492

**Comment by fgud** [comment]
I'm getting this same issue but Automatic detection of enemies just stops working when in group. It works when solo.

**Comment by GitCadde** [comment]
Yeah true, just in group with Automatic detection

**Comment by Hekili** [comment]
This has since been resolved (there was a temporary issue with target detection).
