### ISSUE TITLE
[BUG] Automatic detection of enemies stops working when joining groups

### ISSUE THREAD

**Issue by fgud** [Hekili/hekili#2594]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

This seems to only happen for Feral Druid rotation. I tested for other classes/specs.
Issue happens only when in groups.

### How to Reproduce

This seems to only happen for Feral Druid rotation. I tested for other classes/specs.
Issue happens only when in groups. Other people reporting same issues.

### Player Information (Link)

https://pastebin.com/zesHhaHK

### Error Messages (Link)

https://pastebin.com/zesHhaHK

### Additional Information

Other people reporting same issue in #general. Other specs.

### Contact Information

Tompickles#1234

**Comment by apaxgelfling** [comment]
This is happening on Enh rotation as well, for me

**Comment by galbanese91** [comment]
This is happening to me on my Sub Rogue! Ahh help!

**Comment by AA16064** [comment]
Same for me as sub

**Comment by phatzz** [comment]
Reverting to an old targets.lua fixes this issue.
Probably universal for all specs.

**Comment by Rynched** [comment]
How do you rever the targets.lua?

**Comment by galbanese91** [comment]
> Download the old version of the addon, grab the targets.lua from there and drop it in the new release folder

**Comment by Datreve** [comment]
I have the same issue on sub rogue :( started suddenly. I will try the trick with targets.lua 

@galbanese91  How old the version should be ?

**Comment by bigd123456** [comment]
This started with vertion v10.1.0-1.0.0i. I reverted back to v10.1.0-1.0.0h and it works fine. You can get the v10.1.0-1.0.0h from this link if you need https://www.curseforge.com/wow/addons/hekili/files/4533796

**Comment by apaxgelfling** [comment]
An update has been pushed that fixed this issue for me.
