### ISSUE TITLE
[FEATURE] Add shiv for Outlaw and Subtlety

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#2595]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Could you please add Shiv for Outlaw and Subtlety to dispel enrage?

**Comment by bigd123456** [comment]
I would like to see this added if possible also. I found a post about hunters having it and thought would be great for rogues also.

**Comment by Hekili** [comment]
You can definitely add it yourself, but I'll take a quick look.

https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions
