### ISSUE TITLE
Arcane Mage - Priority Freezing when in dungeons / raids / target dummies

### ISSUE THREAD

**Issue by Repulsing23** [Hekili/hekili#2597]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

after touch of the magi it seems to just freeze and stop working

### How to Reproduce

1.) Seems like just the entire priority system of arcane mage stops. frost seems fine.

### Snapshot (Link)

https://pastebin.com/YPqzRHe0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3D2xwCT1vyLqjENNvrhuXL

**Comment by Repulsing23** [comment]
so base opener into touch of the magi and freezing. comes back about 8 seconds later just frozen on arcane blasts.

**Comment by Repulsing23** [comment]
Update: Interface/AddOns/Hekili/Scripts.lua:1665: attempt to call upvalue 'oldfunc' (a string value)

[string "@Interface/AddOns/Hekili/Scripts.lua"]:1665: in function <Interface/AddOns/Hekili/Scripts.lua:1665>
    [string "@Interface/AddOns/Hekili/Scripts.lua"]:1665: in function <Interface/AddOns/Hekili/Scripts.lua:1665>
        [string "@Interface/AddOns/Hekili/Scripts.lua"]:1665: in function <Interface/AddOns/Hekili/Scripts.lua:1665>
            [string "@Interface/AddOns/Hekili/Scripts.lua"]:1665: in function `interrupt_if'
[string "@Interface/AddOns/Hekili/Core.lua"]:532: in function `CheckChannel'
                [string "@Interface/AddOns/Hekili/Core.lua"]:1610: in function <Interface/AddOns/Hekili/Core.lua:1445>
                    


this is in the warnings not sure if this helps

**Comment by Hekili** [comment]
Thanks for the ticket.  I have a fix pending for this issue.  Will post later today.

**Comment by Repulsing23** [comment]
you're incredible

**Comment by Repulsing23** [comment]
looks like its still freezing after barrage randomly ill try to post another log

**Comment by Hekili** [comment]
I haven't released anything yet.

**Comment by spidii88** [comment]
Oh awesome, I thought I was doing something wrong with the options but it appears as though it's an issue you are aware of - thanks so much!! Glad I checked here :)

**Comment by Repulsing23** [comment]
so it looks like its not recommending arcing surge and priority still seems a little wonky. looks like hekili is still working on some aura buffs and that should fix it i would assume

**Comment by Repulsing23** [comment]
arcane* surge*

**Comment by Hekili** [comment]
The aura fixes should help, but whenever you're adding information about an issue, you should go ahead and include a new snapshot.  Thanks!

**Comment by Repulsing23** [comment]
https://pastebin.com/hK2bcgiw

Updated snapshot for the priority system. looks like its missing the main burn phase priority just seems wonky.

**Comment by Hekili** [comment]
Let me know if this is still an issue with `v10.1.0-1.0.0l`.

> Updated snapshot for the priority system. looks like its missing the main burn phase priority just seems wonky.

Can you explain this a different way?  Wonky doesn't mean anything to me in this context.  Give me objective details rather than subjective.  Thanks!

**Comment by Repulsing23** [comment]
just seems like its chaining way to many arcane blasts together outside of touch of the magi windows.

also doesn't seem to recommend arcane surge even when its available with radiant spark and rune of power. 

just seems like maybe the chain of apl events maybe off? i'm not sure also recommending a ton of barrages in single target.

**Comment by Hekili** [comment]
So, tell me what you're literally seeing.

"I see A then B then C.  I think this is wrong because X, Y, Z.  I think I should see D, E, F."

Make sure to add a snapshot whenever adding detail and especially when there's a new release.

**Comment by Repulsing23** [comment]
https://pastebin.com/TLX5JNgs

snapshot i just took at a target dummy. opener started fine orb / arcane blast / nether tempest / 3 arcane blasts / then went straght into the barrage touch of the magi. it skippped over the whole arcane surge big burn phase. ill try to take a video of it or something its hard to text im kinda dumb i think

**Comment by Hekili** [comment]
You're not dumb, you're just trying to explain a whole sequence when I need to look at a single moment.  A video really isn't helpful in the way you might think.

Is the snapshot taken at a moment where it should be in the "arcane surge big burn phase" or not?  What are you saying should've been recommended at that moment?  Arcane Surge?  Something else?

**Comment by Repulsing23** [comment]
https://pastebin.com/sJdP3dwy

got it. Here it should have been recommending the arcane aruge sequence. instead it went straight back to the "mini burn" of radiant spark and touch of the magi. instead of the "big burn" of surge - gem - 3xAB

**Comment by spidii88** [comment]
I'm having the same issue. It's also recommending arcane barrage during the big burn where it shouldn't be. It should be recommending 2x arcane blast, 1x arcane missiles, rinse repeat (post barrage +touch of the magi) but it's telling me to press arcane barrage every time i have 4 arcane charges but we don't do that unless it's AOE.

It also has long periods where it just randomly tells me to spam arcane blast and never tells me to press anything else (skipping clearcasted arcane missiles).

**Comment by Hekili** [comment]
@Repulsing23 Ok, I'll take this to mean that you were expecting it to recommend Arcane Surge > Mana Gem > Arcane Blast x3 (it's still ambiguous to me, so correct me if I'm wrong).

Your snapshot is showing Arcane Blast(0.18), Arcane Blast(1.16), Arcane Barrage(2.14), Touch of the Magi(2.14).

```
42.  arcane_surge ( spark_phase - 9 )
The action (arcane_surge) is usable at (0.18 + 0.00) with cost of 159036 mana (have 159036).
 - the action is ready before the current recommendation (at +0.00 vs. +5.04).
List ( spark_phase ) called from ( Arcane:default:25 ) would PASS at 0.00.
talent.radiant_spark.enabled[true] & variable.spark_phase[true]
 - this entry's criteria FAILS: ( ! talent.nether_tempest.enabled[true] & prev_gcd[4].radiant_spark[false] ) | prev_gcd[1].nether_tempest[false]

There are 1 recheck events.
List ( spark_phase ) called from ( Arcane:default:25 ) would PASS at 1.00.
talent.radiant_spark.enabled[true] & variable.spark_phase[true]
Recheck #1 ( +1.00 ) NOT MET: ( ! talent.nether_tempest.enabled[true] & prev_gcd[4].radiant_spark[false] ) | prev_gcd[1].nether_tempest[false]
```

Arcane Surge was ruled out here because you have Nether Tempest talented and your previous on-GCD cast was not Nether Tempest.  If you do your opener to the point just before Nether Tempest is used, do you see Nether Tempest followed by Arcane Surge?  If not, can you snapshot Nether Tempest being recommended so I can see what comes up next instead?

Was the snapshot taken at a time where you thought it should be recommending Arcane Surge, Mana Gem, then Arcane Blast x3?  The timing matters.  If it was not taken when you're thinking Arcane Surge should be recommended, please take the snapshot at the moment; not before and not after.

**Comment by spidii88** [comment]
Whatever you just did seems to have fixed it for me. Testing more in dungeon.

Edit: Nevermind, still borked. Not recommending Arcane Surge, flickering strange options. The whole rotation is just off.

**Comment by FitzbanWoW** [comment]
Not sure if it helps but I downgraded to Hekili-v10.1.0-1.0.0g and I'm not certain the recommendations are correct but it at least isn't freezing or doing anything totally weird. Please let me know if there's anything else I can do to assist w/ troubleshooting. Thank you for all of your hard work

**Comment by Repulsing23** [comment]
noticed in the double lust opener after the AB spam down. it recommends mini burn barrage and touch instead of arcange power big burn phase

**Comment by Repulsing23** [comment]
gonna try to pull a snap

**Comment by Repulsing23** [comment]
https://pastebin.com/d82GrE1v

tried to time it right buts its tough. this is on a target dummy. bet this is double lust into supposed to be arcane surge burn portion but just goes straight to mini burn of barrage / touch of the magi.

**Comment by Hekili** [comment]
> It's doing the same thing for outlaw rogue, but I'm not sure if it's a single ability that is causing it. I've noticed it in a couple of places

It's not the same issue and it doesn't belong in an Arcane Mage ticket.  You can submit a ticket for Outlaw if you've updated to the latest version and have found an issue.
