### ISSUE TITLE
Rogue / Subtlety - Sometimes it doesnt recommend me important spell as Shadow Dance or Symbols of Death

### ISSUE THREAD

**Issue by OfficialExiled** [Hekili/hekili#2598]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When I play in raid or dungeon, sometimes when im on mostly low energy, my rotation gets confused and doesnt recommend me neither symbols or shadow dance and have to manually click it for it to refresh the rotation. It's mostly when we spam Gloomblade. However, if we stop spamming Gloomblade and either not pressing any buttons, then they suddenly recommend me other cooldowns such as Shadow Dance and Symbols of Death. Im pretty sure when symbols of death is back then we can press that anyways due to gaining 40 energy, and that means when spamming gloomblade it shouldnt interfere the rotation when cooldown is coming back. 

### How to Reproduce
1. Get into a subtlety rogue
2. go to a practice dummy
3. follow recommendation and keep spamming for few minutes and when you are a bit short on energy, it will tell you keep spamming gloomblade and when cooldown comes back it will still tell you to keep spamming gloomblade until you stop clicking it. 

### Snapshot (Link)

https://pastebin.com/39ddWfGi

### Contact Information

Chani#6061

**Comment by vond82** [comment]
Since you have 2p+2p the rules for SoD is Shadow Dance being on cd and SoD either not being up or having 3s or lower duration. It should never be recommended outside of dance

**Comment by Hekili** [comment]
@OfficialExiled This kind of scenario is a good time to provide a sim of your character for comparison.  Then we can look at a snapshot from when you think Symbols or Shadow Dance should've been recommended and see if the sim would've used them.

**Comment by Hekili** [comment]
I did find that a condition of reaching the `stealth_cds` action list would prevent its entries from being considered while your energy is too low.  This will be in the next release (ending with `m` later today).
