### ISSUE TITLE
Predictively queue Mortal strike after the 2nd execute for arms warrior.

### ISSUE THREAD

**Issue by BigBong69** [Hekili/hekili#2599]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Currently the addon is not predicting mortal strike post 2nd stack of executioner's precision, leading to an erratic change in the recommendations once the 2nd execute goes through. I suspect it's due to the fact that EP is a enemy debuff and the addon is searching for the debuff on the enemy before updating recommendations. As the Debuff application is deterministic (outside of random parries) I feel like it could easily predict the mortal strike that comes after the 2nd execute.

### Contact Information

105°C#0854

**Comment by Hekili** [comment]
This is not a feature request, it's an issue with recommendations.  I need a snapshot taken when the 2nd Execute is recommended but the follow-up is not Mortal Strike.

**Comment by Hekili** [comment]
Actually, nevermind, I see an obvious fix with the stacking buff.  Fix will be in 1.0.1.
