### ISSUE TITLE
[Paladin] Stun as Interrupt

### ISSUE THREAD

**Issue by DJScias** [Hekili/hekili#260]
Hello there,

I had a question as a Retribution Paladin.. I generally tend to use Hammer of Justice as an extra interrupt (when Rebuke is on cd and a raid calls for it) but it seems that Hekili doesn't offer me an option to use a stun as interrupt.

I'm not that well-versed on APL's and such, but is there an easy way to make HoJ behave like Rebuke and get called as an interrupt as well?

Thanks in advance.

**Comment by Hekili** [comment]
Not at the moment, but I understand the appeal.  Part of the challenge is that there's no API-based way of knowing what is stunnable and what isn't; recommending HoJ on a target that isn't stunnable isn't a great plan.

If I expand the options to let you whitelist/blacklist which spells that you want to interrupt, then this might make more sense -- it would be your own fault if you whitelisted a spell that is cast by an enemy that isn't stunnable.

**Comment by DJScias** [comment]
That's fair thinking.

I'm mostly asking it since I noticed it existed on a few other rotation addons but Hekili was the one that felt most consistent.

The whitelist/blacklist option seems most feasible then, if you put it like that. To me I'd just add Hammer of Justice to the whitelist and then have it trigger for interrupts as well and that'd be my 100% use-case.

I have no clue how the other rotation addons made the Stun as Interrupt implementation, so unfortunately I can't shed more light unless I go to look into the code myself.
