### ISSUE TITLE
Aura Detection/Updates Broke in 1.0.0k

### ISSUE THREAD

**Issue by ivanbalvan** [Hekili/hekili#2600]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Prot Paladin update 1.0.0k recommends HolyPower cosumers with insuficient holypower

### How to Reproduce

Prot Paladin update 1.0.0k recommend HolyPower cosumer with insuficient holypower

### Snapshot (Link)

https://pastebin.com/0NKxLqJV

### Contact Information

Schwifty#0816   <Discord ID

**Comment by Hekili** [comment]
This is largely resolved with `1.0.0l` and has an additional fix coming in `1.0.1`.

**Comment by n-r-w** [comment]
Not fixed in 1.0.0l. Still ignore existed sunfire on target for moonkin. Snapshot: https://pastebin.com/q1sA6SiK

**Comment by Hekili** [comment]
Thanks, will investigate.

**Comment by Hekili** [comment]
@n-r-w Is that happening consistently for you?  Does it happen on a single-target consistently, or come up when you've swapped between targets?  I haven't been able to make it happen on my Druid.

**Comment by n-r-w** [comment]
This happens regularly on 1 target (Valdrakken training dummy). Perhaps this is influenced by the low fps in Valdrakken (about 40)?

**Comment by Hekili** [comment]
Ok, I'm going to re-test before posting 1.0.1.  If I can't make it happen, then my other bugfixes since 1.0.0l have also resolved this.
