### ISSUE TITLE
[REC] Feral 0CP Ferocious Bite

### ISSUE THREAD

**Issue by Grayfox2325** [Hekili/hekili#2606]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Feral priority seems to be out of wack. Suggesting ferocious bite while at 0CP. Also noticed rake spamming in Feral and moonfire spamming in Guardian but did not get a snapshot of this, will try to get them if I see it again.

### How to Reproduce

Not sure, was just doing world content and noticed it stuck on Ferocious Bite while at 0CP. Possibly Bloodtalons related?

### Snapshot (Link)

https://pastebin.com/U2HXgN5R

**Comment by cameronstubber** [comment]
I just posted about issues with Feral also on #2601 @Grayfox2325 - Downgrading the version fixes it.

**Comment by Hekili** [comment]
You should upgrade to the latest (ends in `l`) instead and see if it's resolved for you.  There's another update coming in a little bit as well.

**Comment by Hekili** [comment]
I'm going to close this since 1.0.1 is about to be posted; if there are still issues, they'll need to go into a new ticket for that release.  Thanks!
