### ISSUE TITLE
[BUG] 'aura' (a nil value) error

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#2607]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I just flew around in Valdrakken when this error popped up.

### How to Reproduce

1. Reload the UI in Valdrakken.
2. Mount up on a Dragonriding mount.
3. Fly up.
4. Land.
6. Repeat steps 3 and 4 until the error pops up.

### Player Information (Link)

https://pastebin.com/zY1d2jCM

### Error Messages (Link)

https://pastebin.com/AY7H8R4f

**Comment by cremor** [comment]
Now I also got the same error without Dragonriding. I happend after I dropped combat with the target dummies.

**Comment by Hekili** [comment]
Yeah, I am adding code to treat a target swap like a full aura update for targets.  That's when I am able to replicate this issue (gain/lose/swap targets).

**Comment by Mormra** [comment]
I have this happening to me every time I storm strike... not sure if its the exact same error.

https://pastebin.com/kkn8r94n

**Comment by Hekili** [comment]
Seems like the same error, and I can't replicate on my shaman after my testfix.  Let me know if you still see this after downloading `v10.1.0-1.0.1` (in about 10 minutes).

**Comment by jmusick** [comment]
Still getting this on 10.1.0-1.0.0I

1x Hekili/Events.lua:1442: attempt to index local 'aura' (a nil value)
[string "@Hekili/Events.lua"]:1442: in function `handler'
[string "@Hekili/Events.lua"]:82: in function <Hekili/Events.lua:71>

Locals:
event = "UNIT_AURA"
unit = "player"
data = <table> {
 updatedAuraInstanceIDs = <table> {
 }
 removedAuraInstanceIDs = <table> {
 }
 isFullUpdate = false
}
isPlayer = true
forceUpdateNeeded = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 189738
}
(for control) = 1
_ = 1
instance = 189738
aura = nil
id = nil
model = nil
(*temporary) = 189738
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'aura' (a nil value)"
instanceDB = <table> {
 187963 = true
 189738 = true
 187949 = true
}
playerInstances = <table> {
 187963 = true
 189738 = true
 187949 = true
}
targetInstances = <table> {
}
wipe = <function> defined =[C]:-1
state = <table> {
 swing = <table> {
 }
 FindPlayerAuraByID = <function> defined @Hekili/Utils.lua:516
 summonPet = <function> defined @Hekili/State.lua:1147
 resetType = "none"
 IsKnown = <function> defined @Hekili/State.lua:6854
 UnitGUID = <function> defined =[C]:-1
 purge = <table> {
 }
 stat = <table> {
 }
 ptr = 1
 off_hand = <table> {
 }
 floor = <function> defined =[C]:-1
 tonumber = <function> defined =[C]:-1
 SetWhitelist = <function> defined @Hekili/State.lua:6569
 holds = <table> {
 }
 display = "Interrupts"
 prev_off_gcd = <table> {
 }
 SetDefaultVariable = <function> defined @Hekili/State.lua:4378
 mainhand_speed = 2.725000
 channelSpell = <function> defined @Hekili/State.lua:1210
 equipped = <table> {
 }
 gain = <function> defined @Hekili/State.lua:1515
 TimeToReady = <function> defined @Hekili/State.lua:7213
 setStance = <function> defined @Hekili/State.lua:1121
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 UnitAura = <function> defined =[C]:-1
 AddToHistory = <function> defined @Hekili/Events.lua:1021
 SetupCycle = <function> defined @Hekili/State.lua:756
 print = <function> defined @Hekili/State.lua:530
 GetSpellCount = <function> defined =[C]:-1
 ClashOffset = <function> defined @Hekili/State.lua:7427
 azerite = <table> {
 }
 offset = 1.140000
 QueuedCastRemains = <function> defined @Hekili/State.lua:6127
 ApplyCastingAuraFromQueue = <function> defined @Hekili/State.lua:6151
 TargetBuffUp = <function> defined @Hekili/State.lua:5666
 pvptalent = <table> {
 }
 UnitDebuff = <function> defined =[C]:-1
 GetItemGem = <function> defined =[C]:-1
 UnitIsFriend = <function> defined =[C]:-1
 action = <table> {
 }
 addStack = <function> defined @Hekili/State.lua:995
 HasRequiredResources = <function> defined @Hekili/State.lua:7176
 TargetDebuffUp = <function> defined @Hekili/State.lua:5671
 UnitCanAttack = <function> defined =[C]:-1
 rawSpend = <function> defined @Hekili/State.lua:1535
 script = <table> {
 }
 IsUsable = <function> defined @Hekili/State.lua:7034
 GetItemInfo = <function> defined =[C]:-1
 GetPlayerAuraBySpellID = <function> defined =[C]:-1
 health = <table> {
 }
 active_enemies = 1
 IsFiltered = <function> defined @Hekili/State.lua:6999
 cooldown = <table> {
 }
 stance = <table> {
 }
 gcd = <table> {
 }
 empowerment = <table> {
 }
 varDB = <table> {
 }
 ResetQueues = <function> defined @Hekili/State.lua:5919
 auras = <table> {
 }
 GetCycleInfo = <function> defined @Hekili/State.lua:842
 format = <function> defined =[C]:-1
 using_apl = <table> {
 }
 RemoveAuraEvent = <function> defined @Hekili/State.lua:5792
 system = <table> {
 }
 max_targets = 0
 recheckTimes = <table> {
 }
 runHandler = <function> defined @Hekili/State.lua:6234
 recheck = <function> defined @Hekili/State.lua:1578
 GetShapeshiftFormInfo = <function> defined =[C]:-1
 nextOH = 0
 main_hand = <table> {
 }
 IsActiveSpell = <function> defined @Hekili/Utils.lua:573
 GetEvent

**Comment by Mormra** [comment]
Just hopped on, seems to be good to go at the test dummies. ty @Hekili
