### ISSUE TITLE
warrior t30 still doesnt work

### ISSUE THREAD

**Issue by machajr** [Hekili/hekili#2608]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

action.bloodthirst.crit_pct_current >= 95 this doesnt look working i think its only check your crit rate not your buffs for bloodthirst there is a weakaura for that that may help you https://wago.io/PKtmE426S

### How to Reproduce

looks like still checkin for only your crit stat not for spells

### Snapshot (Link)

https://pastebin.com/KpxeppuD

**Comment by Hekili** [comment]
I'll add your snapshot to the other ticket.
