### ISSUE TITLE
Outlaw Rogue not recommending some abilities and/or tinkets

### ISSUE THREAD

**Issue by Baddeye** [Hekili/hekili#2609]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Never recommends usage of Adrenaline Rush, Shadow Dance, or Windscar Whetstone trinket.

### How to Reproduce

Find a group of bad guys and start swinging.  Energy level doesn't matter.

### Snapshot (Link)

https://pastebin.com/pUwNgAGn

### Additional Information

LUA Error below:

Message: Interface/AddOns/Hekili/Events.lua:1442: attempt to index local 'aura' (a nil value)
Time: Sun May 14 11:08:47 2023
Count: 8
Stack: Interface/AddOns/Hekili/Events.lua:1442: attempt to index local 'aura' (a nil value)
[string "@Interface/AddOns/Hekili/Events.lua"]:1442: in function `handler'
[string "@Interface/AddOns/Hekili/Events.lua"]:82: in function <Interface/AddOns/Hekili/Events.lua:71>

Locals: event = "UNIT_AURA"
unit = "player"
data = <table> {
 addedAuras = <table> {
 }
 updatedAuraInstanceIDs = <table> {
 }
 removedAuraInstanceIDs = <table> {
 }
 isFullUpdate = false
}
isPlayer = true
forceUpdateNeeded = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 125122
 2 = 125264
}
(for control) = 1
_ = 1
instance = 125122
aura = nil
id = nil
model = nil
(*temporary) = 125122
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'aura' (a nil value)"
instanceDB = <table> {
 123162 = true
 125128 = true
 125264 = true
 123165 = true
 57152 = true
 57153 = true
 124911 = true
 118237 = true
 57157 = true
 125122 = true
 57154 = true
}
playerInstances = <table> {
 123162 = true
 125128 = true
 125264 = true
 123165 = true
 57152 = true
 57153 = true
 124911 = true
 118237 = true
 57157 = true
 125122 = true
 57154 = true
}
targetInstances = <table> {
 44687 = true
 118476 = true
 44695 = true
 88433 = true
 103632 = true
 45022 = true
 104274 = true
 103648 = true
 103652 = true
 45851 = true
 45355 = true
 45359 = true
 45806 = true
 117745 = true
 44678 = true
 103649 = true
 45314 = true
 45001 = true
 44688 = true
 85399 = true
 45332 = true
 45019 = true
 44521 = true
 85376 = true
 103650 = true
 45346 = true
 125125 = true
 118325 = true
 85405 = true
 123834 = true
 45358 = true
 117542 = true
 45831 = true
 44671 = true
 123166 = true
 125055 = true
 44672 = true
 44674 = true
 88527 = true
 44998 = true
 117539 = true
 88444 = true
}
wipe = <function> defined =[C]:-1
state = <table> {
 swing = <table> {
 }
 spend = <function> defined @Interface/AddOns/Hekili/State.lua:1528
 putTrinketsOnCD = <function> defined @Interface/AddOns/Hekili/State.lua:5677
 role = <table> {
 }
 IsKnown = <function> defined @Interface/AddOns/Hekili/State.lua:6854
 forecastResources = <function> defined @Interface/AddOns/Hekili/State.lua:1327
 purge = <table> {
 }
 stat = <table> {
 }
 safenum = <function> defined @Interface/AddOns/Hekili/State.lua:607
 off_hand = <table> {
 }
 floor = <function> defined =[C]:-1
 queue = <table> {
 }
 predictionsOff = <table> {
 }
 holds = <table> {
 }
 display = "Primary"
 prev_off_gcd = <table> {
 }
 active_dot = <table> {
 }
 mainhand_speed = 1.455000
 danse_macabre_tracker = <table> {
 }
 equipped = <table> {
 }
 gain = <function> defined @Interface/AddOns/Hekili/State.lua:1515
 TimeToReady = <function> defined @Interface/AddOns/Hekili/State.lua:7213
 setStance = <function> defined @Interface/AddOns/Hekili/State.lua:1121
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 UnitAura = <function> defined =[C]:-1
 AddToHistory = <function> defined @Interface/AddOns/Hekili/Events.lua:1021
 SetupCycle = <function> defined @Interface/AddOns/Hekili/State.lua:756
 QueueEvent = <function> defined @Interface/AddOns/Hekili/State.lua:5727
 remove = <function> defined =[C]:-1
 ClashOffset = <function> defined @Interface/AddOns/Hekili/State.lua:7427
 azerite = <table> {
 }
 offset = 1.780000
 QueuedCastRemains = <function> defined @Interface/AddOns/Hekili/State.lua:6127
 ApplyCastingAuraFromQueue = <function> defined @Interface/AddOns/Hekili/State.lua:6151
 TargetBuffUp = <function> defined @Interface/AddOns/Hekili/State.lua:5666
 pvptalent = <table> {
 }
 delayMin = 0
 GetItemGem = <function> defined =[C]:-1
 UnitIsFriend = <function> defined =[C]:-1
 stealthed = <table> {
 }
 combat = 40661.055000
 addStack = <function> defined @Interface/AddOns/Hekili/State.lua:995
 HasRequiredResources = <function> defined @Interface/AddOns/Hekili/State.l

### Contact Information

jweltch@gmail.com

**Comment by Hekili** [comment]
Your Cooldowns are toggled off, if you're concerned specifically about Adrenaline Rush and the like.  Tap `ALT-SHIFT-R` by default to turn them on.  It's generally a good idea to control them during fights so that you can line them up with the right parts of a fight.
