### ISSUE TITLE
MM Hunter - A couple of Issues

### ISSUE THREAD

**Issue by Johaylon** [Hekili/hekili#261]
Hello! I would like to start by giving my info.

build: v8.3.0-03
level: 120 (120)
class: HUNTER
spec: marksmanship

talents: camouflage
    careful_aim
    double_tap
    lock_and_load
    posthaste
    serpent_sting
    streamline

azerite: azerite_empowered=3
    azerite_globules=1
    focused_fire=3
    gemhide=1
    gutripper=2
    longstrider=1
    self_reliance=1
    surging_shots=3

essences: [breath_of_the_dying]=1, memory_of_lucid_dreams=2, the_crucible_of_flame=4

sets/legendaries/artifacts: none

gear:     7th_legionnaires_sabatons=1
    ashjrakamas_shroud_of_resolve=1
    corrupted_aspirants_badge=1
    corrupted_aspirants_band=1
    corrupted_aspirants_chain_leggings=1
    corrupted_gladiators_rifle=1
    deadwash_hauberk=1
    enthrallers_bindstone=1
    heart_of_azeroth=1
    kaldorei_archers_shoulderguards=1
    loop_of_abhorrent_celerity=1
    nefarious_tormentors_girdle=1
    nefarious_tormentors_handguards=1
    nefarious_tormentors_vambraces=1
    notorious_gladiators_chain_headgear=1
    stormwind_tabard=1
    stylish_green_shirt=1

itemIDs: 158046, 158075, 163400, 165453, 167399, 169223, 169317, 172830, 172845, 172849, 173306, 173448, 173818, 174268, 174955, 45574, 6385

The problems are, the game doesnt show "sniper shot" and "Corrupted Aspirant's Badge" in the required sections, so it doesnt take into account neither of these two while giving me the rotation.

It also shows serpent sting sooner than its required. While applying the first serpent sting its fine, it applies a 12 second DOT. So it should come into the rotation when its about to end. However, it tells me to re-apply the serpent sting DOT even though it has 3-5 seconds remaining and I have an aimed shot ready. 

Thanks for the addon!

**Comment by Hekili** [comment]
Please fill out a proper ticket and read the part about snapshots.
