### ISSUE TITLE
[BUG] Periodic bug splats with Balance Druid (nil Aura)

### ISSUE THREAD

**Issue by prom3theu5** [Hekili/hekili#2610]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Receiving sporadic fatality bug captures while playing as balance, sems related to an aura check

### How to Reproduce

Simply run around and play as Balance.

### Player Information (Link)

https://pastebin.com/Swp2WD0p

### Error Messages (Link)

https://pastebin.com/0tepxf8v

**Comment by prom3theu5** [comment]
Reverting to 1.0.0k seems to resolve, so its something that has been introduced with `l`

**Comment by Hekili** [comment]
Yep, a release is pending to fix this.
