### ISSUE TITLE
[BUG] Lua error ending combat 'attempt to index local 'aura' (a nil value)

### ISSUE THREAD

**Issue by Bigity** [Hekili/hekili#2611]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Lua error when entering combat (with enhacement shaman - have not tried other classes/specs), then stops suggesting abilities.  Only seems to throw the error once per login/reload

Message: Interface/AddOns/Hekili/Events.lua:1442: attempt to index local 'aura' (a nil value)
Time: Sun May 14 14:01:44 2023
Count: 6
Stack: Interface/AddOns/Hekili/Events.lua:1442: attempt to index local 'aura' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Hekili/Events.lua"]:1442: in function `handler'
[string "@Interface/AddOns/Hekili/Events.lua"]:82: in function <Interface/AddOns/Hekili/Events.lua:71>

Locals: (*temporary) = <function> defined =[C]:-1

### How to Reproduce

1. Log in
2. Enter combat

### Player Information (Link)

https://pastebin.com/nEQFgtqm

### Error Messages (Link)

n/a

**Comment by Hekili** [comment]
Fixed in 10.1.0-1.0.1.
