### ISSUE TITLE
Aura Nil Value Errors

### ISSUE THREAD

**Issue by Eldraxis** [Hekili/hekili#2612]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Getting an error on all toons when casting spells.

### How to Reproduce

So far it's random spells on my Lock/Warrior/Shaman including mounts
Mostly been able to recreate it on my Shaman, just doing my enhance rotation on a dummy.

### Player Information (Link)

https://pastebin.com/eqhSi8uh

### Error Messages (Link)

https://pastebin.com/7S0GcdEf

**Comment by Hekili** [comment]
You haven't downloaded the latest version.

**Comment by Eldraxis** [comment]
Odd, I did. Guess it didn't copy over correctly. Sorry.

**Comment by Hekili** [comment]
No worries, it happens. Addon updaters can lag a bit behind the release, and there have been several in the past day.
