### ISSUE TITLE
[BUG] Back Drop Error

### ISSUE THREAD

**Issue by Racerx323** [Hekili/hekili#2615]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

UI error when opening options

### How to Reproduce

1. right or left click minimap button

### Player Information (Link)

https://pastebin.com/qKyRFS2W

### Error Messages (Link)

https://pastebin.com/AJEt9zbj

**Comment by Hekili** [comment]
This will be resolved in https://github.com/Hekili/hekili/releases/v10.1.0-1.0.1c.
