### ISSUE TITLE
[REC] Survival hunter missing serpent sting tracking

### ISSUE THREAD

**Issue by PlushyCthulhu** [Hekili/hekili#2617]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Don't seem to have serpent sting coming up in my rotation recommendation when the DOT falls off.

### How to Reproduce

Take serpent sting as a talent
Attack a training dummy
Ability does not come up in tracking

### Snapshot (Link)

https://pastebin.com/q027H6Nt

### Contact Information

PlushyCthulhu#8464

**Comment by Hekili** [comment]
You have [Viper's Venom](https://www.wowhead.com/spell=268501/vipers-venom) talented and you don't have [Hydra's Bite](https://www.wowhead.com/spell=260241/hydras-bite) talented.  Your sim priority will not use Serpent Sting under these circumstances, relying instead on Raptor Strike/Mongoose Bite to apply Serpent Sting based on its % chance.
