### ISSUE TITLE
[BUG] Marksmanship Hunter sometime variable "buff.precise_shots.up" check worng

### ISSUE THREAD

**Issue by nuttin0011** [Hekili/hekili#2619]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

i use Maskmanship Hunter and create simple Rotation
![Arcane Shot Bug 1](https://github.com/Hekili/hekili/assets/74884682/eead226b-617f-4c99-a675-753faa485316)

when i casting "Aimed Shot" it's recommend Arcane Shot for buff "precise shots"
![Arcane Shot Bug 2](https://github.com/Hekili/hekili/assets/74884682/15fa0c8a-de0e-48dd-b951-a1d5672be7ec)

when buff "precise shots" up it's recommend 2 arcane shot as buff stack
![Arcane Shot Bug 3](https://github.com/Hekili/hekili/assets/74884682/5f462469-187e-4b46-a423-1638b94aeb74)

but some time i shot "Aracne Shot" and Buff "precise shots" is vanish but it's still recommend "Aracne Shot"
i cannot found condition it's happen i try to use Aimed Shot twice , Arcane Shot after Aimed Shot immediately, Aimed Shot and Wait etc... but it's happen some time
when i see variable in rotation i found "buff.precise_shots.up" still true and goes false after i use 4-5 arcane shot
![Arcane Shot Bug 4](https://github.com/Hekili/hekili/assets/74884682/35926697-5561-4474-b575-517d2f3cf828)

please help.
ty

### How to Reproduce

as above :)

### Player Information (Link)

https://pastebin.com/n7HKVZyR

### Error Messages (Link)

-

**Comment by Hekili** [comment]
![image](https://github.com/Hekili/hekili/assets/9438134/c1dadfd6-4ea6-421a-8119-af657a2c1aff)

This is not the latest version of the addon.

**Comment by nuttin0011** [comment]
amazing it's work well in latest version of the addon.
TY
