### ISSUE TITLE
Ret Pally - AoE Targeting incorrect forecasted timeline

### ISSUE THREAD

**Issue by Blujelly87** [Hekili/hekili#2620]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've noticed the primary bar is only showing templar strike during any AoE targets, it will occasionally show interrupts & divine toll. When you engage a boss, it goes back to how it should, showing what should be done next.

I'm not sure if it Ret Pally's only our any DPS class

<img width="499" alt="Untitled" src="https://github.com/Hekili/hekili/assets/116963975/2b894144-261b-4bd7-84c6-7581acf0c62f">

### How to Reproduce

any AoEtarget

### Snapshot (Link)

https://pastebin.com/3hd2djNu

**Comment by Hekili** [comment]
You've configured Avenging Wrath to only be available in boss fights.  The Retribution priority is written to avoid spending HoPo just before Avenging Wrath comes off cooldown.  I may adjust the boss-only flag to act like Avenging Wrath is on cooldown, but in the meantime, I'd recommend not restricting Avenging Wrath to boss-fights only.  You can control the Cooldowns toggle with a keybind.

**Comment by Blujelly87** [comment]
ah right ok recommendation has worked, can I ask if that was changed to act like this? I've normally had it to show only during boss fights, as I like to control Avenging Wrath during non-boss fights.

**Comment by Hekili** [comment]
I've adjusted the Ret priority again in `v10.1.0-1.0.1d` to be more lenient with syncing cooldowns if you've made AW unavailable.

**Comment by Blujelly87** [comment]
amazing work as always, thank you! tried & tested
