### ISSUE TITLE
Arcane - Issue with recommendations during lust

### ISSUE THREAD

**Issue by iNupidstoob** [Hekili/hekili#2622]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During lust the recommendations for arcane mage seem to switch up completely, only suggesting Arcane Blast.
This is a bit hard for me to snapshot as it seems inconsistent to reproduce but it's just suggesting Arcane Blast till lust runs out.

Any thoughts on how to properly troubleshoot this?

### How to Reproduce

Enter raid (probably not just raid related tbh), during lust see the recommendations switch up to arcane blast only.

### Snapshot (Link)

I can try create one, but it's hard to catch.

**Comment by Hekili** [comment]
> This is a bit hard for me to snapshot as it seems inconsistent to reproduce but it's just suggesting Arcane Blast till lust runs out.
> Any thoughts on how to properly troubleshoot this?

Take a snapshot when it's endlessly suggesting Arcane Blast during lust.

**Comment by Repulsing23** [comment]
https://pastebin.com/3YHfhwBN

i got it for you its during lust and after big burn seems to spam reccomend only Arcane blast. until next radiant spark window.

**Comment by Hekili** [comment]
Got a sim for comparison?

From what I can see in the snapshot:

```
39.  arcane_blast ( t30_mini - 9 )
List ( t30_mini ) called from ( Arcane:default:22 ) would PASS at 0.00.
cooldown.arcane_surge.remains[42.12] > 30 & ( cooldown.radiant_spark.ready[false] | dot.radiant_spark.remains[8.56] | debuff.radiant_spark_vulnerability.up[true] ) & ( cooldown.touch_of_the_magi.remains[0.00] <= ( gcd.max[1.18] * 3 ) | debuff.touch_of_the_magi.up[false] ) & set_bonus.tier30_4pc[1.00] & active_enemies[1.00] < variable.aoe_target_count[3.00]
 - this entry has no criteria to test.
Action chosen:  arcane_blast at 0.00!
```

This is basically the end of the T30 mini burn phase, when nothing higher priority is selected.  So let's see what was skipped.

```
31.  radiant_spark ( t30_mini - 1 )
The action is not ready ( 26.60 ) before our maximum delay window ( 10.00 ) for this query.
```

Radiant Spark is on cooldown.

```
32.  nether_tempest ( t30_mini - 2 )
 - this entry's criteria FAILS: active_dot.nether_tempest[1.00] = 0 & ( prev_gcd[1].radiant_spark[false] | prev_gcd[1].shifting_power[false] )
```

Nether Tempest only gets recommended here when there's no Nether Tempest already active and you've just cast Radiant Spark or Shifting Power.
 
```
33.  meteor ( t30_mini - 3 ) - talent [ meteor ] missing
```

Meteor isn't talented.

```
34.  arcane_barrage ( t30_mini - 4 )
 - this entry's criteria FAILS: prev_gcd[1].meteor[false] | ( prev_gcd[1].nether_tempest[false] & ( prev_gcd[2].radiant_spark[false] | prev_gcd[3].radiant_spark[false] ) )
```

Arcane Barrage is used after casting Meteor or after Nether Tempest (which is after Radiant Spark). 

```
35.  touch_of_the_magi ( t30_mini - 5 )
 - this entry's criteria FAILS: prev_gcd[1].arcane_barrage[false] & ( action.arcane_barrage.in_flight_remains[0.00] <= 0.2 | gcd.remains[0.00] <= 0.2 )
```

Touch of the Magi gets recommended after Arcane Barrage, when Arcane Barrage is landing or the GCD is almost up.

```
36.  arcane_blast ( t30_mini - 6 )
 - this entry's criteria FAILS: ( debuff.radiant_spark_vulnerability.stack[4.00] > 0 & debuff.radiant_spark_vulnerability.stack[4.00] < 4 ) | buff.nether_precision.up[false]
```

This Arcane Blast entry gets recommended when Radiant Spark's debuff is being stacked or Nether Precision is up.

```
37.  presence_of_mind ( t30_mini - 7 )
The action is not ready ( 11.96 ) before our maximum delay window ( 10.00 ) for this query.
```

POM is on cooldown.

```
38.  arcane_missiles ( t30_mini - 8 )
 - this entry's criteria FAILS: buff.clearcasting.react[1.00] & ( debuff.touch_of_the_magi.remains[0.00] > execute_time[1.57] | ! talent.presence_of_mind.enabled[true] )
```

Arcane Missiles is used with Clearcasting up and either (a) Touch of the Magi's debuff will last longer than the channel or (b) POM isn't talented.

The `t30_mini` action list has the following requirements:
```
30.  call_action_list:t30_mini ( default - 22 )
Criteria for t30_mini PASS at +0.25 - cooldown.arcane_surge.remains[42.12] > 30 & ( cooldown.radiant_spark.ready[false] | dot.radiant_spark.remains[8.56] | debuff.radiant_spark_vulnerability.up[true] ) & ( cooldown.touch_of_the_magi.remains[0.00] <= ( gcd.max[1.18] * 3 ) | debuff.touch_of_the_magi.up[false] ) & set_bonus.tier30_4pc[1.00] & active_enemies[1.00] < variable.aoe_target_count[3.00]
```

Arcane Surge is on CD for more than 30 more seconds, Radiant Spark is applied for 8.5 more seconds (and Radiant Spark's vulnerability debuff is still up), Touch of the Magi is off cooldown, you have Tier30 4-piece, and you have fewer than 3 enemies, so those conditions are met.

If we look at a sim for comparison, we can see what happens during the `t30_mini` phase there, and whether these are consistent.  If I had to guess, the way this priority list strictly looks at what was just cast makes it really easy to fail.  If you pushed any other GCD during those windows or CD alignment is especially odd, then those conditions are no longer met.

You do have a Nether Tempest applied, so presumably that's fairly recent, so we probably want that Arcane Barrage entry to pass.  Assuming no other weird casts go off, Arcane Barrage would make it so Touch of the Magi can be used next, which would be followed by Arcane Missiles for a bit.

Changing that Arcane Barrage condition to something like:
```
action.meteor.last_used > 0 & action.meteor.time_since < gcd.max * 2 | action.nether_tempest.last_used > 0 & action.nether_tempest.time_since < gcd.max * 2 & action.radiant_spark.last_used > 0 & action.radiant_spark.time_since > gcd.max & action.radiant_spark.time_since < gcd.max * 4
```

...might result in Arcane Barrage's usage being a little more flexible.  It's not that graceful, though.

**Comment by Repulsing23** [comment]
i do know that we work in barrage now randomly at those times. what kind of sim can i give you for some help?

**Comment by Hekili** [comment]
Just go to Raidbots and do a Quick Sim of your character in a Patchwerk (1 boss) environment, then provide the link here.

**Comment by Repulsing23** [comment]
https://pastebin.com/5g3pgwN6

Patchwerk 5 min. Quick sim

"Also in Single target talens that i raid in"

**Comment by Hekili** [comment]
If this is still an issue, open a fresh ticket with a snapshot from 1.0.1k (or later).
