### ISSUE TITLE
[REC] Bomb dispenser trinket is being recommended first before Beacon to the Beyond

### ISSUE THREAD

**Issue by Gyudon47** [Hekili/hekili#2623]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I believe Beacon to the Beyond should be used on cooldown first since its long cooldown over bomb dispenser trinket

### How to Reproduce

Follow hekili recommendation

### Snapshot (Link)

https://pastebin.com/7JUg5iRb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/5FRCf5fxptX6ptCAD3joyH

### Contact Information

gyu#0800

**Comment by Hekili** [comment]
Could you retake your snapshot when Bomb Dispenser is recommended but Beacon to the Beyond is available?

**Comment by Gyudon47** [comment]
https://pastebin.com/kSZQu8mB
Here you go! Thank you

**Comment by Hekili** [comment]
Thanks!  Your snapshot showed an error with the `trinket.bed_bath_and_beyond.has_cooldown` expression (or whatever), so I've fixed that in `v10.1.0-1.0.1d` and it should be resolved in a few minutes.  If not, let me know here and I'll reopen the ticket.

**Comment by Gyudon47** [comment]
Hi hekili, the addon  is still recommending bomb first over beacon :( . looks like be being skipped even though it should definitely be the first trinket use. Under my raidbot sims it also shows beacon first.
https://pastebin.com/LGNwena7

**Comment by Hekili** [comment]
It wasn't skipped, its conditions weren't met. There's a bit that will probably be a timing issue where it wants you to use it just after triggering a GCD, but even if that were removed, you were in stealth and it won't recommend that trinket in stealth.

**Comment by Gyudon47** [comment]
Its probably because of shadow dance, the trinket should be used i believed after first between the eyes and before shadow dance
