### ISSUE TITLE
[REC] Add havoc in single target with cry havoc talented.

### ISSUE THREAD

**Issue by rauvagol** [Hekili/hekili#2627]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It might sound insane, but as it is instant, using havoc on a single target (with cry havoc talented) is a decent dps increase even in pure single target situations if more than one chaos bolt hits in the duration. Each explosion deals 100% of spell power damage, at the cost of 1 gcd, and incinerate deals only 154% spell power.

### How to Reproduce

1. Enter game as a Destruction Warlock.
2. Take the Havoc and Cry Havoc talents.
3. Engage an enemy in single target.
4. Get to a situation where 2 chaos bolts or more will be recommended in the next ~12 seconds
5. See recommendations.

### Snapshot (Link)

https://pastebin.com/KCvCTgBs

### Additional Information

It sounds insane and is very minor, but it also gives destruction a tiny TINY bit more movement.

**Comment by Hekili** [comment]
I've removed the logic preventing Havoc from being recommended in ST.  If you're still not seeing it, please add an updated snapshot and I'll reopen the ticket.
