### ISSUE TITLE
[REC] Demo lock Felguard counts as cooldown

### ISSUE THREAD

**Issue by Trickatreat** [Hekili/hekili#2628]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Felguard is up and it keeps suggesting it. When I take off "Cooldowns" it disappears. It should not be listed as a cooldown since it is the main pet of a demo lock :)

### How to Reproduce

1. Load as demonology warlock
2. Summon Felguard
3. Felguard will get suggested

### Snapshot (Link)

https://pastebin.com/SHNYDYhT

### Contact Information

Trickatreat

**Comment by Hekili** [comment]
It is not recommending that you summon your primary Felguard pet.  You have the [Grimoire Felguard](https://www.wowhead.com/spell=111898/grimoire-felguard) talent which summons an additional Felguard (which is a DPS cooldown).
