### ISSUE TITLE
[REC] Sub rogue is not recommending rupture in the opener when using flagellation

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2629]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

According to the simc rotation (linked in raidbots), rupture should be used within the first 10 gcds of the opener, however shadow dance appears to be recommended by the addon in its place. I've linked two snapshots and a raidbots quick sim to note the differences. Behaviour seems correct when not using Flagellation talent.

Snapshot 1: https://pastebin.com/9LKQi1j1 - taken at the position where shadow dance is recommended instead of rupture.
Snapshot 2: https://pastebin.com/LzrDDXwX - taken before combat starts with 10 recommendations set, this shows rupture isn't recommended at all within the first 10 actions.

### How to Reproduce

Enter game as sub rogue, use new ST build with Flag, BUQAAWulQAmRd/c4Iy2r7VOUFAAABAAAAAAAEBkkICBIIJEJJRikEpkkEtAJlkQSSkWAAAA

Begin rotation, rupture wont be recommended until much later on.

### Snapshot (Link)

https://pastebin.com/9LKQi1j1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/v1VkvMcBio5to2NyBgXRcy

**Comment by Hekili** [comment]
This is addressed in the other Subtlety ticket that I just closed.
