### ISSUE TITLE
Is it possible to have a hekili priority for Feral affinity resto druids?

### ISSUE THREAD

**Issue by vladimars** [Hekili/hekili#263]
Was wondering if it was possible to have hekili set up so when you swapped into kitty when in feral affinity as resto the priority would show up, but not show up when not a kitty.

**Comment by Hekili** [comment]
Not at the moment, but I'll keep this ticket as a feature request.  I'm buried in another part of the project right now, but this would be a nice option.

**Comment by mrminus** [comment]
Searching for this exact capability today, any idea if this is something that will make up the priority list? thank you.

**Comment by KestrelWild** [comment]
same for balance affinity!

**Comment by Hekili** [comment]
Closing this ticket, since the answer isn't special to this ticket.  If/when there's time/capacity to add support for healer specs (to DPS), I'll do it.  It won't be considered a main function of the addon.
