### ISSUE TITLE
[REC] During Avenging Wrath, no spenders being recommended

### ISSUE THREAD

**Issue by xClow** [Hekili/hekili#2630]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During avenging wrath no spenders are being recommended.

### How to Reproduce

Enter Game as as retribution paladin
pop Avenging wrath
only getting templar strikes and hammer of wrath as recommendations

### Snapshot (Link)
ST:
https://pastebin.com/QFt2DErc
https://pastebin.com/W3iBxE2e

AoE:
https://pastebin.com/wSrMNax7

### Contact Information

rhet#0069

**Comment by Suitz** [comment]
Don't know if it's related but during avenging wrath hammer of wrath if often completly ignored. 
Especcialy with 4p T30 hammer of wrath is much better than judgment during avenging wrath.

**Comment by Hekili** [comment]
> Don't know if it's related but during avenging wrath hammer of wrath if often completly ignored.
> Especcialy with 4p T30 hammer of wrath is much better than judgment during avenging wrath.

May or may not be related.  But please include a snapshot if you want me to investigate.

**Comment by Hekili** [comment]
@xClow Is there something that changes the spell ID of Final Reckoning?  I see that you have the talent, but the addon can't see that you know Final Reckoning.  It's withholding spenders until you pop FR but then you don't know FR (despite having the talent) so it doesn't get popped.

**Comment by xClow** [comment]
Tried swapping between all my talent builds but it stays the same 343721 :(

**Comment by Hekili** [comment]
Anything funky with /hekili > Abilities > Final Reckoning?

**Comment by xClow** [comment]
![image](https://github.com/Hekili/hekili/assets/8822671/a5cf4e6c-e51f-4843-8b3c-e4afee2bf762)

I dont believe so

**Comment by Hekili** [comment]
`/dump Hekili.Class.abilities.final_reckoning`

`/dump Hekili.State.action.final_reckoning`

**Comment by xClow** [comment]
Dump: value=Hekili.Class.abilities.final_reckoning 
[1]={ 
  gcd="spell", 
  startsCombat=true, 
  handler=<function>, 
  key="final_reckoning", 
  toggle="cooldowns", 
  realUnit="", 
  charges=1, 
  recharge=60, 
  talent="final_reckoning", 
  id=343721, 
  desc="", 
  funcs={ 
    spend=<function>, 
    cast=<function> 
  }, 
  spendType="holy_power", 
  from=70, 
  school="holy", 
  realCast=85782.702, 
  cooldown=60, 
  name="Final Reckoning" 
} 

and

Dump: value=Hekili.State.action.final_reckoning 
[1]={ 
  base_cast=0, 
  gcdType="spell", 
  action="final_reckoning", 
  name="Final Reckoning" 
}

**Comment by Hekili** [comment]
You don't have filter by range enabled and are standing far away or anything weird?

**Comment by xClow** [comment]
Nope :(

These are my targeting settings

https://i.imgur.com/uSm2dEm.png

**Comment by Hekili** [comment]
`/dump IsPlayerSpell(343721)`

`/dump IsSpellKnownOrOverridesKnown(343721)`

`/dump IsSpellKnown(343721, true)`

**Comment by xClow** [comment]
Dump: value=IsPlayerSpell(343721) 
[1]=true 
Dump: value=IsSpellKnownOrOverridesKnown(343721) 
[1]=true 
Dump: value=IsSpellKnown(343721, true) 
[1]=false

**Comment by Hekili** [comment]
Can you install the new alpha (`v10.1.0-1.0.1f-alpha1`) and post a new snapshot?  Thanks.

**Comment by xClow** [comment]
I don’t know what kind of cursed pc I have but after a pc reboot it hasn’t happened again. 

I tried reopening bnet, reinstalling Hekili, reopening WoW etc. but the full pc reboot fixed it, didn’t install the alpha

**Comment by Hekili** [comment]
Weird.  Your PC hadn't been up that long at the time you snapshotted originally.

> 3490.51

That's less than an hour.  Sometimes, we do see API issues related to times if you've gone a LONG time without rebooting.
