### ISSUE TITLE
[REC] Feral Recommending MOTW Mid Combat and Invalid Abilities w/ 4 piece 

### ISSUE THREAD

**Issue by tance77** [Hekili/hekili#2631]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The rotation seems to bug out and recommend wrong abilities sometimes it turns off completely then quickly corrects it. Also it's recommending Mark of the wild randomly during the rotation. Also its missing my Shift + F Keybind on Incarn

### How to Reproduce

Single Target rotation on a target dumby with 4 piece tier set. 

### Snapshot (Link)

https://pastebin.com/BxqiQeQs    https://pastebin.com/WSwGgJsa

**Comment by Hekili** [comment]
~~Neither of the snapshots you've provided show Mark of the Wild being recommended.~~  My bad, I see it.

> The rotation seems to bug out and recommend wrong abilities sometimes it turns off completely then quickly corrects it.

Be specific.  What is recommended wrongly and what should be recommended instead?

> Also its missing my Shift + F Keybind on Incarn

It definitely doesn't see Incarnation on your bars.  I see:

```
    natures_vigil              = SC  [06], **SF  [07], SF  [08]**
    remove_corruption          = **SF  [01]**
```

Which action bar page has Incarnation there?  Bar 7 is usually Cat Form, and Bar 8 is usually Prowling.

**Comment by Hekili** [comment]
LOL, this is a pretty hilarious issue with the priority.  There is a "wait" entry that I configured to wait until your Combo Points hit max from Predator Revealed.  It doesn't really work in this context, though.  It time-traveled an hour into the future, at which point, Mark of the Wild is down.

Will fix.  Thanks for the report.

**Comment by tance77** [comment]
> ~Neither of the snapshots you've provided show Mark of the Wild being recommended.~ My bad, I see it.
> 
> > The rotation seems to bug out and recommend wrong abilities sometimes it turns off completely then quickly corrects it.
> 
> Be specific. What is recommended wrongly and what should be recommended instead?
> 
> > Also its missing my Shift + F Keybind on Incarn
> 
> It definitely doesn't see Incarnation on your bars. I see:
> 
> ```
>     natures_vigil              = SC  [06], **SF  [07], SF  [08]**
>     remove_corruption          = **SF  [01]**
> ```
> 
> Which action bar page has Incarnation there? Bar 7 is usually Cat Form, and Bar 8 is usually Prowling.

Lets tackle this in a later issue. Probably related to a recent transfer, but glad you found the MoTW bug

**Comment by tance77** [comment]
Can confirm the keybind thing was do to the recent transfer that issue is not present anymore.

**Comment by Hekili** [comment]
This will be resolved in the next release.
