### ISSUE TITLE
[REC] Assassination Rogue recommending to use Ambush when unable to cast it.

### ISSUE THREAD

**Issue by Tronasaurus** [Hekili/hekili#2633]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Assassination Rogue I expect the addon to not recommend to use Ambush when I don't have the ability to. 
Vanishing during combat, and using garrote out of it, the addon should not suggest ambush for the next 2 spells which it is currently doing for a few moments before changing to mutilate. 

### How to Reproduce

Enter the game on an Assassination Rogue 
Using either talent loadout below:

- BMQAAWulQAmRd/c4Iy2r7VOUFISikERClEAAAAAAAJBQiAAAAAAAINkIlkgkkkWKJCkERkA **(Aoe)**

or

- BMQAAWulQAmRd/c4Iy2r7VOUFINJSCcgElEAAAAAAAJAkkAAAAAAAQDJOQJJkkkkWKJiEkIRiFE **(Single Target)**

Enter combat, follow priority as normal, watch for vanish, see hekili suggest to ambush once (or twice) after exiting stealth. 

### Snapshot (Link)

https://pastebin.com/jun7SZ0h (AoE) https://pastebin.com/ht6dYMB9 (Single Target)

### Additional Information

I have provided both single target and aoe situations in the same ticket, I apologize if that's not helpful.
Not sure why it's suggesting to use ambush outside of stealth, was working fine before the most recent update. 

### Contact Information

Tron#8234

**Comment by Tronasaurus** [comment]
Issue seems to be present after exiting stealth at the start of combat also.

**Comment by Hekili** [comment]
Add a snapshot from the latest release.

**Comment by Tronasaurus** [comment]
https://pastebin.com/PTzAjREG
Looks to be sorted, thanks so much.
