### ISSUE TITLE
Outlaw Rogue - Ghostly Strike showing keybind "1" on recommendation regardless of keybind

### ISSUE THREAD

**Issue by Baddeye** [Hekili/hekili#2634]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As noted in description:  

Shows keybind "1" for Ghostly Strike regardless of where it's actually bound to. Have tried setting Ghostly Strike to other keybinds with same result.  Also shows correct keybind ("1") for any other ability bound to "1". IE: If I have sinister strike bound to "1", and Ghostly Strike bound to "X", it will recommend "1" for both abilities. All other recommendations and keybinds appear to be displaying correctly.  No LUA errors that I can see.  
![hekili1](https://github.com/Hekili/hekili/assets/133597359/23f9f34e-d676-462d-812a-ffc62472ed08)

### How to Reproduce

Perform normal rotation

### Snapshot (Link)

https://pastebin.com/GVBZkNwm

### Contact Information

jweltch@gmail.com

**Comment by Hekili** [comment]
`ghostly_strike   = 1   [02], X   [03]`

It's X on action bar 3, but it's 1 on action bar 2, so the addon makes its best guess.  You can set the keybind in /hekili > Abilities > Ghostly Strike > Override Keybind Text.
