### ISSUE TITLE
[REC] Arcane Recommendation Does Not Match Sim Ability Log (Missing Evocate)

### ISSUE THREAD

**Issue by FitzbanWoW** [Hekili/hekili#2635]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Five minute sim says we should be casting evocate around 1:13 (this is consistent with top logs) but Hekili does not seem to be recommending this correctly. From what I can tell it recommends it during precombat and then not again for at least 2:00 minutes which is wrong. Trying to figure out if this is an issue with the APL or the addon.

https://www.raidbots.com/simbot/report/dEw5Av8S8P1Zm8PqVaJdQN

### How to Reproduce

1. Hit dummy as Arcane mage
2. Follow Hekili recommendations exactly as displayed
3. Addon will not recommend Evocation at the correct time, which is different from our sims.

### Snapshot (Link)

https://pastebin.com/ANc5xD05

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dEw5Av8S8P1Zm8PqVaJdQN

### Additional Information

Happy to provide additional snapshots if needed, my rotation wasn't perfect but I don't think that would make a difference either way - evocation is a critical spell for our burn phase which we wouldn't want to hold. Thank you!

### Contact Information

Fitzban#0001

**Comment by Repulsing23** [comment]
we figure anything out on this?

**Comment by cameronstubber** [comment]
Arcane is pretty broken - im testing it now, Hekili has no idea how to behave during timewarp/lust/hero.

**Comment by Hekili** [comment]
The use of Evocation here was limited to boss fights and I shouldn't have done that.  I'm updating to address it now.

**Comment by FitzbanWoW** [comment]
That makes sense! I noticed it was working in raid last night. Thank you!
