### ISSUE TITLE
[REC] Shadow Priest In-cooldown prio error

### ISSUE THREAD

**Issue by Apo94** [Hekili/hekili#2636]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Testing the addon on dummy to practice realized that its casting mind blast over empowered mind spikes missing out on damage.

### How to Reproduce

1. Enter game as Shadow Priest
2. Take default m+ recommended build (https://www.wowhead.com/talent-calc/priest/shadow/DAREEAFUEERUVEKFSKEQCFQNVRFURVEKQUGkFBQ)
3. dot up (crash or vamp touch) double mind blast > shadowfiend > Voidform > voidbolt > PI 
4. Follow rotation until voidbolt and void torrent is on cooldown and u have 2 stacks off mind spike insanity

### Snapshot (Link)

https://pastebin.com/41H40y8n

### Raidbots Sim Report (Link)

[_Raidbots_](https://www.raidbots.com/simbot/report/imhLdxiZehKV97bHSYXaw3)

### Additional Information

From my reading and understanding empowered mind spike deals more damage than mind blast and should be prioratized during cooldown when overcapping on stacks but addon tells me to mind blast and overcap on mind spike insanity procs (as mind spike insanity hit for 33.4k on average and mind blast 20.2k within 1% in crits dealt)

### Contact Information

Apo#3534

**Comment by Hekili** [comment]
```
45.  mind_spike_insanity ( aoe - 10 )
List ( aoe ) called from ( Shadow:default:4 ) would PASS at 0.00.
active_enemies[5.00] > 2 | spell_targets.vampiric_touch[5.00] > 3
 - this entry's criteria FAILS: variable.dots_up[0.00] & cooldown.mind_blast.full_recharge_time[0.15] >= gcd.max[1.05] * 3 & talent.idol_of_cthun.enabled[true] & ( ! cooldown.void_torrent.up[false] | ! talent.void_torrent.enabled[true] )
 ```
 
So, I am finding that `variable.dots_up` doesn't get set for the AOE action list, so that's a defect I'm fixing.  However, it's also worth noting that there are times when you'll still Mind Blast despite having 2 stacks of Mind Spike Insanity.  This entry for Mind Spike is also prevented if Mind Blast is going to finish recharging or sit at max charges.  Otherwise, you lose the DPS value of "Mind Blast charge recovery time" while casting your Mind Spikes.

The first issue will be fixed in next release.  Thanks!
