### ISSUE TITLE
[FEATURE] Bloodlust override for potions

### ISSUE THREAD

**Issue by Xeltor** [Hekili/hekili#2638]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Would it be possible to have a Bloodlust override toggle for potions just like we have for cooldowns?

I personally always forget to use them and even though it can be manually toggled i really only ever want to use them during burst phases anyway.

### Contact Information

Xeltor#0001

**Comment by Hekili** [comment]
That's not a bad idea; I'll consider it.  The Potions toggle has other issues, IMO, especially with regard to having Cooldowns shown separately.  I personally don't have the addon recommend potions at all, since they're more situational than rotational.

**Comment by Hekili** [comment]
I've added this for the next release.
