### ISSUE TITLE
[BUG] Missing keybind on random icons

### ISSUE THREAD

**Issue by antarek** [Hekili/hekili#2639]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

From time to time Hekili doesn't display the keybind associated to the skill. I haven't found any consistent way to reproduce this issue but it seems to happen a lot more when grouped in a dungeon/raid. Here is a screenshot of the issue:
![image](https://github.com/Hekili/hekili/assets/42368527/688feb82-7b82-4f08-ae0c-6b8aaac1d7cc)

### How to Reproduce

No consistent way to reproduce the issue for as far as it happens at random when starting a fight. That being said it seems to happen a lot more when in a group/raid.

### Player Information (Link)

https://pastebin.com/hWm9Yh1p

### Error Messages (Link)

nothing

**Comment by Hekili** [comment]
All of your keybinds seem to be detected per the Player Information you've provided.  Did you change or turn off your keybindings on your displays?  See /hekili > Displays > Primary > Keybindings.

**Comment by antarek** [comment]
> All of your keybinds seem to be detected per the Player Information you've provided. Did you change or turn off your keybindings on your displays? See /hekili > Displays > Primary > Keybindings.

No, i never turn them off. It just seems to happen at random on the skill prediction queue from Hekili.

On my screenshot the keybind for "Marrowrend" and "Blood Boil" are missing as you can see. And when it happens it wont display those keybinds on those skills on the skill prediction queue even after a reload.

I m forced to quit the game to have it solved until that this issue happens again or not if i join a group or a raid.
