### ISSUE TITLE
[BUG] Priority not displaying

### ISSUE THREAD

**Issue by Adaptabull** [Hekili/hekili#2640]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not showing up for any of my specializations.
![image](https://github.com/Hekili/hekili/assets/134109328/5bd493e5-0567-497b-abad-ffbdc85fc7d0)
![image](https://github.com/Hekili/hekili/assets/134109328/c461ac74-6e17-4ece-b3c3-d217fe19f15e)
![image](https://github.com/Hekili/hekili/assets/134109328/17951e0f-d221-4eec-9614-c1e3318d0ff2)

### How to Reproduce

Not sure how to reproduce

### Player Information (Link)

https://pastebin.com/7SsCYcbK

### Error Messages (Link)

None

### Contact Information

JT1527#6461 (Discord)

**Comment by Hekili** [comment]
I don't have the information here to be able to offer any real guidance.

* What are the Visibility settings for each display?
* Are you using SpellFlash?  If so, what are your SpellFlash settings for each display?
* What else is shown in the Warnings section that is lit up in the options screen?
* Do you have BugSack/BugGrabber installed?  If so, what is the first error message you see that is associated with this addon, if any?  If not, you probably will want to install these addons to collect error information.
* Do you have WeakAuras installed?  If so, did you install an addon called "Better Hekili Targeting"?  If so, remove it and reload UI.
* A snapshot might be more informative.  You can create one by pausing with ALT-SHIFT-P, then copy it from /hekili > Snapshots by pressing CTRL+A and CTRL+C, then paste it to Pastebin and link it here.

**Comment by acastaner** [comment]
I have the same issue. Hekili stopped showing after the last update. Visibility is set to 1 for all displays in all conditions. If I create a brand new profile it'll show, but after relogging it'll stop showing until I create a brand new profile from scratch.

This is what the snapshot tells me:

https://pastebin.com/bVcUc9pF

**Comment by acastaner** [comment]
And this is the LUA error I get:

Message: ...nterface/AddOns/Hekili/Dragonflight/DruidBalance.lua:2219: attempt to compare nil with number
Time: Tue May 23 12:22:03 2023
Count: 2
Stack: ...nterface/AddOns/Hekili/Dragonflight/DruidBalance.lua:2219: attempt to compare nil with number
[string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:151: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:149>
[string "=[C]"]: ?
[string "@Interface/AddOns/Hekili/Dragonflight/DruidBalance.lua"]:2219: in function `usable'
[string "@Interface/AddOns/Hekili/State.lua"]:7058: in function `IsUsable'
[string "@Interface/AddOns/Hekili/Core.lua"]:932: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function `Update'
[string "@Interface/AddOns/Hekili/Options.lua"]:10723: in function `MakeSnapshot'
[string "@Interface/AddOns/Hekili/Options.lua"]:10680: in function `TogglePause'
[string "@Interface/AddOns/Hekili/Options.lua"]:10820: in function `FireToggle'
[string "@Interface/AddOns/Hekili/UI.lua"]:2795: in function <Interface/AddOns/Hekili/UI.lua:2794>

Locals: private = <table> {
 ThrowError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:50
 DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:92
 ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:112
 SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:88
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:121
 IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:82
 NewError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:54
 IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:99
}
orig_errorhandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360

**Comment by acastaner** [comment]
I disabled RCLoot Council and now the message is more clear, sorry for the spam.

Message: ...nterface/AddOns/Hekili/Dragonflight/DruidBalance.lua:2219: attempt to compare nil with number
Time: Tue May 23 16:28:04 2023
Count: 1
Stack: ...nterface/AddOns/Hekili/Dragonflight/DruidBalance.lua:2219: attempt to compare nil with number
[string "=[C]"]: ?
[string "@Interface/AddOns/Hekili/Dragonflight/DruidBalance.lua"]:2219: in function `usable'
[string "@Interface/AddOns/Hekili/State.lua"]:7058: in function `IsUsable'
[string "@Interface/AddOns/Hekili/Core.lua"]:932: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function `Update'
[string "@Interface/AddOns/Hekili/Options.lua"]:10723: in function `MakeSnapshot'
[string "@Interface/AddOns/Hekili/Options.lua"]:10680: in function `TogglePause'
[string "@Interface/AddOns/Hekili/Options.lua"]:10820: in function `FireToggle'
[string "@Interface/AddOns/Hekili/UI.lua"]:2795: in function <Interface/AddOns/Hekili/UI.lua:2794>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Hekili** [comment]
I have not been able to figure out why either your health or settings for vigil aren't available there, but I'm putting in some babyproofing in the next release.

**Comment by acastaner** [comment]
It seems to be caused by an error in the Balance spec. If I switch the Balance spec to use the Feral profile then the problem doesn't occur anymore.


________________________________

**Comment by Hekili** [comment]
I'll post my fix soon, but I'm curious:

If you log in as Feral and type `/dump Hekili.State.settings.vigil_damage` what do you see?

If you swap to Balance and do the same, what do you see?

If you swap back to Feral and do it again, what do you see?

**Comment by acastaner** [comment]
The output  when in Feral is

[1]=50

It's the same when I change to Balance spec (and set Hekili's Balance spec to use the Balance profile, which I had changed to Feral before as a workaround)
