### ISSUE TITLE
brewmaster monk cooldown priority

### ISSUE THREAD

**Issue by bcotton94** [Hekili/hekili#2641]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When I turned on recommend cooldowns as a brewmaster monk it is recommending a spell to me that does not exist. im not sure what it is, it's a red colored picture. Please fix.

### How to Reproduce

Enter game as brewmaster monk turn on cooldown priorities, number one spell recommendation shows.

### Snapshot (Link)

.

### Contact Information

bcotton94

**Comment by Hekili** [comment]
Sorry, you'll have to submit the ticket correctly including the snapshot.  More likely than not, however, it's a trinket.  You can pause (ALT-SHIFT-P) and mouse over the icon to see more information, if you want to check it out yourself.
