### ISSUE TITLE
[BUG] Lua error preventing recommendations

### ISSUE THREAD

**Issue by Clushini** [Hekili/hekili#2645]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Rotation just constantly freezes and takes a while to proceed

### How to Reproduce

go to target dummy and do your rotation

### Player Information (Link)

https://pastebin.com/bNtFHcAG

### Error Messages (Link)

https://pastebin.com/JU07N7sy

**Comment by Hekili** [comment]
Fix is going out in 1.0.1i.
