### ISSUE TITLE
[BUG] Feral Failing To Recommend. Infinite Snapshot Loop, and Freezing Recommendations 

### ISSUE THREAD

**Issue by tance77** [Hekili/hekili#2647]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

**Feral Failing To Recommend:**
When using the Feral module in Hekili, I noticed that it frequently fails to recommend abilities. Even when my resources are available and conditions for optimal ability usage are met, Hekili does not provide any recommendations for Feral abilities. This occurs randomly during gameplay, making it difficult to optimize my rotation and maximize my performance.

**Infinite Snapshot Loop:**
In some instances, when the Feral module does recommend an ability, there is an issue with the snapshotting mechanism. After executing the recommended ability, Hekili gets stuck in an infinite loop where it keeps recommending the same ability repeatedly, without progressing to the next optimal action. This loop persists until I manually intervene and select a different ability to break the cycle.

**Freezing Recommendations:**
At times, while using the Feral module, Hekili completely freezes and stops providing any recommendations altogether. This issue occurs unexpectedly and prevents me from relying on Hekili for real-time ability suggestions. I have to restart the addon or reload the UI to regain its functionality temporarily, but the freezing issue tends to reoccur after some time.

It seems to happen a lot in single target. 

![image](https://github.com/Hekili/hekili/assets/3421501/5646b6c2-ae22-4d5e-b688-368a21f632c4)
![image](https://github.com/Hekili/hekili/assets/3421501/8476da97-bd95-4810-b80d-ecd25df579cd)

### How to Reproduce

Install and enable the Hekili addon.
Choose the Feral module within Hekili.
Engage in combat scenarios where Feral abilities are required.
Observe the occurrences of Feral failing to recommend abilities, infinite snapshot loops, and freezing recommendations.

### Snapshot (Link)

https://pastebin.com/VCyCtXzi

**Comment by Grayfox2325** [comment]
Same issue. Also noticing recommendations are out of wack, but can't upload a snapshot due to this infinite loop bug. Recommending Tiger's Fury/Incarnation/Prowl while already active, finishers at 0CP, etc.

**Comment by Hekili** [comment]
The snapshot is not from the current version of the addon.  Add an updated snapshot if this is happening with `v10.1.0-1.0.1i`.

**Comment by tance77** [comment]
@Hekili I will when I get home. I updated before playing last night, I'm not sure if the changes though in that release will fix it though. I understand though the latest version may fix it. I shall let you know ASAP

**Comment by MaddyLif3** [comment]
> The snapshot is not from the current version of the addon. Add an updated snapshot if this is happening with `v10.1.0-1.0.1i`.

I am getting an issue where feral suggestions fail to show up at all. It's just blank. Eventually during a dungeon or something it will kick in. I am on latest version that you listed.

**Comment by MaddyLif3** [comment]
https://pastebin.com/kUEh8AGm finally got it to load the addon after accidentally casting regrowth outside of proc and was able to grab this, I don't know if it helps.

**Comment by Hekili** [comment]
It's the same issue as others -- you can toggle off defensives for the moment until I post my fix.

**Comment by MaddyLif3** [comment]
> It's the same issue as others -- you can toggle off defensives for the moment until I post my fix.

cool, thanks Hekili!

**Comment by tance77** [comment]
For the most part this update fixed it. There is a tiny hiccup that im trying to capture with a snapshot but iuts so fast!

**Comment by tance77** [comment]
could not take a snap shot quick enough but there was a hiccup but it wasn't as bad as described in this post. Just going to close it for now till I can get a snapshot. Also seems like a different issue.
