### ISSUE TITLE
[REC] Destruction Warlock : Immolate is recommanded too early with Raging Demonfire talent

### ISSUE THREAD

**Issue by Frossty69** [Hekili/hekili#2648]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Rotation suggest to refresh immolate way too early with Raging Demonfire talent witch extend the duration by 7.5 sec from each use of Channel Demonfire and 0.5 sec form each 2-set proc.
Right now rotation suggest to refresh immolate on timer as if there is no extention duration.

### How to Reproduce

Just doing normal rotation and it suggest refresh immolate with 15 sec remaining on target and next channel demonfire about to be up wich extend it for at least 7.5 sec more

### Snapshot (Link)

https://pastebin.com/ujss5W3Z

**Comment by Hekili** [comment]
Thanks for the report.  It looks like I should be using the duration of the new dot (pre-pandemic) instead of the duration of the existing DOT when calculating.

**Comment by Hekili** [comment]
This will be addressed in the next release.  `v10.1.0-1.0.1k`
