### ISSUE TITLE
[BUG] Can't find Hekili classic addon anymore.

### ISSUE THREAD

**Issue by Draiven123** [Hekili/hekili#2650]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Can't find Hekili classic addon anymore.

### How to Reproduce

Can't find Hekili classic addon anymore.

### Player Information (Link)

www.CantfindHekiliclassicaddonanymore.com

### Error Messages (Link)

www.CantfindHekiliclassicaddonanymore.com

### Additional Information

Can't find Hekili classic addon anymore.

**Comment by Hekili** [comment]
https://www.curseforge.com/wow/addons/hekili/files?gameVersionTypeId=73713

**Comment by Draiven123** [comment]
I was talking about classic era

**Comment by Hekili** [comment]
Doesn't exist.

**Comment by Draiven123** [comment]
> Doesn't exist.

Oh, I thought it would since it's a thing for every other version. Why isn't it? Sorry I would have posted this on the website page on curse but you have comments turned off.
