### ISSUE TITLE
[FEATURE] Ignore Incorporeal adds in Mythic+

### ISSUE THREAD

**Issue by gianlucahorrocks** [Hekili/hekili#2651]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hi. So I've noticed that the adds from the Incorporeal affix this week are being included in Hekili when near them on the Automatic setting. These adds can't be killed and must only be CC'd. So would you be able to make Hekili ignore them? Right now, I keep having to manually switch between single target and automatic when they spawn to get around this.

### Contact Information

Bouncy#8614

**Comment by Hekili** [comment]
This is already in the next release.
