### ISSUE TITLE
not recommending Outbreak at all

### ISSUE THREAD

**Issue by pozzer18** [Hekili/hekili#2655]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

overapping on runes and not spending on outbreak (not talented in to superstrain but sim still shows to use) noticable mostly in raid as works in AOE build ( epidemic)

### How to Reproduce

1. enter raid as Uh DK, use Festering strike and clawing shadows till max runes, 

### Snapshot (Link)

https://pastebin.com/H2Z2FCtt

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jF4H8GZRE8ihzcvV4s5s3H

### Contact Information

Pozzer#8576

**Comment by pozzer18** [comment]
im pretty sure this is due to the conditions needing unholy blight / plaguebringer and superstrain. so i guess this is more of a suggestion than a bug, but the dot it applies does 2,465,990 just over 4.7% of my damage according to the AOE sim. so would be nice to be recomended when full runes or close to full runes when not having the above talents talented and in an AOE enviroment, last boss in the current raid is a good example of this as he spawns 5 mobs often during the fight

**Comment by Hekili** [comment]
No, it's a bug with auras that are not applied not showing as "refreshable" right now.  It'll be fixed in the next release.
