### ISSUE TITLE
[DK] Anti-Magic Shell used offensively

### ISSUE THREAD

**Issue by MrSmurfy** [Hekili/hekili#2656]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unticking "Use Anti-Magic Shell Offensively" still recommends Anti-Magic Shell, not sure if this is borked:
![image](https://github.com/Hekili/hekili/assets/11522121/0ea33ce2-e7ff-4f68-b657-b922436bdf26)

### How to Reproduce

Use addon as DK and untick "Use Anti-Magic Shell Offensively" in the settings.
Observe Anti-Magic Shell still being recommended.

### Snapshot (Link)

https://pastebin.com/raw/rKuyJWfS

**Comment by Hekili** [comment]
> If checked, Anti-Magic Shell will not be on the Defensives toggle by default.

This means, when that is unchecked, it will only be shown if Defensives are toggled on.  In your snapshot, they are toggled on.

If checked, AMS can be recommended regardless of whether the Defensives toggle is on.
