### ISSUE TITLE
[BUG] Lua error after the first use of a portal

### ISSUE THREAD

**Issue by rickenharp** [Hekili/hekili#2657]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The first use of a portal after the game has been started causes an error window to pop-up. It happens on all characters, regardless of class and spec.

### How to Reproduce

1. Enter the game in Valdrakken
2. Take the portal to Stormwind
3. The error window pops up

### Player Information (Link)

https://pastebin.com/fHZ25LjC

### Error Messages (Link)

https://pastebin.com/08rMM1n2

**Comment by Hekili** [comment]
Thanks for reporting.  This is an issue with SpellFlashCore, which is only incidentally included in the addon.  As far as I can tell, SpellFlashCore is not being maintained, so I don't know whether this will be resolved.
