### ISSUE TITLE
Warrior Arms, "hac" action list don't work correctly

### ISSUE THREAD

**Issue by flash45f** [Hekili/hekili#266]
Many spell never show with two adds. Like Mortal Strike
Many difference between simc and hekili
Problem with "hac" actions list and Cleave talents?

https://pastebin.com/CndqYaX5
https://www.raidbots.com/simbot/report/nhEyRatqfPPVvE5J4XgkYX

**Comment by Hekili** [comment]
You're comparing a Patchwerk sim to a snapshot where there are 2 targets. 

Please fill out tickets properly so I have some detail to help investigate.

**Comment by flash45f** [comment]
Boss Targets 2 is not good? 

And target dummy 2?
https://www.raidbots.com/simbot/report/d86scyUfGfxSzPqUUqgwi4

**Comment by Hekili** [comment]
No, not really -- you're asking about hectic add cleave. Patchwerk and target dummy don't have raid events for adds, which is what that list uses. But I will probably change the APL to not use hac.

**Comment by flash45f** [comment]
Ok thanks.
When I simc with patchewerk with 2/3/4 he use "use" hac yes. And it's work. But he don't work with dungeon slice.

For me with hekili I use custom apl like this:

actions+=/run_action_list,name=hac,if=(spell_targets.whirlwind>1&spell_targets.whirlwind<5)

actions.hac+=/skullsplitter,if=rage<60
actions.hac+=/colossus_smash
actions.hac+=/warbreaker
actions.hac+=/bladestorm,if=buff.sweeping_strikes.down&buff.test_of_might.up
actions.hac+=/cleave,if=spell_targets.whirlwind>2
actions.hac+=/execute
actions.hac+=/mortal_strike
actions.hac+=/overpower,if=(rage<70&buff.memory_of_lucid_dreams.down)
actions.hac+=/whirlwind,if=talent.fervor_of_battle.enabled

**Comment by Hekili** [comment]
Based on my own sim testing, I've removed the HAC list and submitted a simc ticket as well.
