### ISSUE TITLE
[FEATURE] Ability to disable recommending rupture during shadow dance

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#2661]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Would like the ability to toggle on or off the ability to recommend rupturing during shadow dance

**Comment by aaronlilla** [comment]
forgot to put, for sub rogue

**Comment by Hekili** [comment]
Why?  Rupture is already skipped in Shadow Dance if you have a single target or Rupture is already ticking and you have 2+ targets, unless Thistle Tea is up with 1 target.

If you feel the addon's recommendations are incorrect, you'd need to snapshot and supply an explanation.  If you want the priority to be changed, it's also helpful to demonstrate your change in a sim you've modified (i.e., on Raidbots, then link here).

**Comment by aaronlilla** [comment]
the reason is because in M+ the standard thing to do is to rupture stuff until the pack is gathered, when it's gathered then go into your dance sectec. often i'll find myself targeting something that isn't ruptured (to blind or kidney or kick or something) and go into my dance with my current target not ruptured so it recommends it, when it would be more preferable to not rupture during dance to get as much aoe damage out as possible

**Comment by aaronlilla** [comment]
also the fact that you'd have to position correctly often to get the value from the rupture with replicating shadows, where i would personally rather have an option to not have to try and do all that during dance and just get as much burst out as possible while i can. 

i'm not suggesting that the rotation or suggestions or wrong, i'm just suggesting an option to turn it off if you prefer

**Comment by aaronlilla** [comment]
after our conversation, you brought up a really good point explaining:

"the issue isn't that Rupture is recommended, really.  The issue is that Secret Technique is not recommended without Rupture up. So if Rupture can't be recommended and it's down, then Secret Technique won't get recommended."

i definitely think if either by default or an option to recommend sectec over rupture during dance that would solve it

**Comment by Hekili** [comment]
A version of this will be in the next release.  If you have a Rupture up on *something* or your current target will die within 15 seconds, Rupture can be skipped.  Let me know if you find that this causes any weirdness.
