### ISSUE TITLE
[FEATURE] Require certain amount of danse macabre stacks before recommending Secret Technique

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#2662]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Would like the ability to manually set the required amount of danse macabre stacks (when talented into it) before recommending secret technique

**Comment by Hekili** [comment]
I don't plan to add an option for this.  Is there a reason why you'd want it to be different than default (which is 3+ stacks)?

**Comment by aaronlilla** [comment]
it's more of just a damage profile thing that would be nice to be able to toggle. this is pretty easy to just override manually thoug.

random example 1:  during a pack with several kicks or kidney targets, i would prefer to have gotten off the biggest amount of burst in the shortest time (a bigger sectec) to be able to kick, kidney, blind etc while technically "losing" less damage

random example 2: on the boss with the chains in neltharus, i would prefer to get off the biggest sectec possible during dance because if the spread-with-chains mechanic happens mid-dance i have to move away and would have preferred to get as much burst out as possible

random example 3: the first boss of neltharus. i know the mammoth is going to charge soon, so i want to get a bigger sectec out first before he charges away and i lose the rest of my value from the dance

**Comment by Hekili** [comment]
Thanks for the additional information; I don't plan to implement this feature.  For example, your third example is really fight choreography and you're totally allowed to push Secret Technique early when you know fight movement necessitates it.  The addon isn't built to anticipate fight choreography.
