### ISSUE TITLE
[REC] Addon rarely predicts the correct ability after shadow dance, in the que

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#2663]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon will rarely provide the actual correct ability after shadow dance in the que. After hitting shadow dance it's correct, but the ability the addon recommends after shadow dance while not in shadow dance seems to be completely random and will often instantly change the recommendation once you hit shadow dance. Would be nice to know the exact ability to use right after entering shadow dance as it's a short high-damage window so knowing exactly what to hit right after, without delay, would be very useful

### How to Reproduce

1. Enter game as sub rogue
2. Go to dummies or dungeon or whatever
3. Do rotation a few times while paying attention to the abilities in the que, specifically what it recommends right after shadow dance
4. hit shadow dance and watch the next recommendation not match up with what was previously in the que

### Snapshot (Link)

http://pastebin.com

**Comment by Hekili** [comment]
You'll have to provide more specific information and a snapshot (or multiple snapshots).  I guarantee that it's not "random."

> hit shadow dance and watch the next recommendation not match up with what was previously in the que

Snapshot when Shadow Dance is recommended; unpause and hit Shadow Dance; Snapshot again.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
