### ISSUE TITLE
[BUG] Unable to Generate Recommendation - Dev Evoker

### ISSUE THREAD

**Issue by dnobrn** [Hekili/hekili#2664]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Error message "unable to make recommendation for primary #1" occurs after first entering combat on devastation evoker. Issue does not occur with other characters/classes. I am using a saved profile for display settings but otherwise using default addon settings. Issue has been present through last few releases. Snapshot is generated each time error occurs.

### How to Reproduce

Enter combat / cast spells as devastation evoker using addon settings from pastebin

### Player Information (Link)

https://pastebin.com/gupyVsEW

### Error Messages (Link)

https://pastebin.com/7KigVbN5

**Comment by Hekili** [comment]
Thanks; I'll take a look.

**Comment by Hekili** [comment]
This may be resolved in the next release.
