### ISSUE TITLE
Discipline Priest - Spell Flash > Talent: Shadow Covenant

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Hekili/hekili#2665]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello, is it normal that the Discipline Priest's spellflash display doesn't work anymore when skilling the Talent: Shadow Covenant? Only when I then use the spell do I have the spellflash on the action bars. When the spell ends, I'll have no more. Once I remove the talent everything works as usual.

### How to Reproduce

I changed or removed the talent.

### Player Information (Link)

https://pastebin.com/D68AGByr

### Error Messages (Link)

None existed.

**Comment by Hekili** [comment]
This will be fixed in the next release.
