### ISSUE TITLE
[REC] Unholy Should Recommend Berserking 14-12 seconds of gargoyle left

### ISSUE THREAD

**Issue by kkelley1987** [Hekili/hekili#2667]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unholy Single Target is no longer recommending Troll Berserking at 14-12 seconds left on gargoyle, instead it is waiting till the very end of gargoyle or even later.

### How to Reproduce

1. Enter game as a Unholy Death Knight
2. Take the full ST CS Gargoyle Build
3. Proceed through standard opener Army -> Outbreak -> FS -> Gargoyle + DT -> Pot -> DC X 4 -> UA -> Apoc -> Trinket -> ERW -> SS -> DC -> etc... 
4. Tuesday/Wednesday raid it correctly recommended Troll beserking with  15-10 seconds left on gargoyle summon... Thursday raid it did not recommend this.

### Snapshot (Link)

https://pastebin.com/SSGCmFyD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2VKZ4G4R6y2mr1ddQDwZpN

### Additional Information

As you can see in the raidbots, it's recommending Berserking 15 seconds into combat

### Contact Information

Martialbob#8722

**Comment by Hekili** [comment]
Thanks, this should be resolved in the next release.
