### ISSUE TITLE
[REC] Templar Strike/Templar Slash range check sometimes not working

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#2668]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Retribution Paladin, sometimes the range check for Templar Strike/Templar Slash doesn't work. It is shown as in-range altough I'm out of range.

### How to Reproduce

1. Play as Retribution Paladin.
2. Make sure you have the Templar Strikes talent selected.
3. Enable all queue icons in Hekili (this is just to make the issue more visible).
4. Use Templar Strike.
5. Go out of range.
6. Notice that the Templar Slash icons are not shown in red although the ability icon on the bar is.

### Snapshot (Link)

https://pastebin.com/BgSTDvXT

### Additional Information

Most of the time the range indicator works fine. But sometimes it doesn't.
I've only seen this problem with Templar Strike/Templar Slash, not with other abilities. Although that might not say much, since all other ret abilities now have a way higher range.

Screenshot of the snapshot link above:
![Main](https://github.com/Hekili/hekili/assets/116314/86c9fdec-cd8a-47e7-a10e-caefe764b2ca)

Here is another snapshot where it is a queue icon: https://pastebin.com/KWS4t5B3
And here is the screenshot for it:
![Queue](https://github.com/Hekili/hekili/assets/116314/15d0c6c0-ea54-4b2c-84d1-408599b128a1)

**Comment by Hekili** [comment]
Does the range checking stay out of sync, or does it update slowly?  I haven't managed to replicate this on my end.

**Comment by cremor** [comment]
After some more testing it seems like this only happens to Templar Slash. And the range indicator stays wrong as long as Templar Slash stays available. Once it falls back to Templar Strike (after 4 seconds), the range is updated.

**Comment by cremor** [comment]
I've updated the steps to reproduce in the initial post.

**Comment by cremor** [comment]
Fixed in v10.1.0-1.0.1o, thanks!
