### ISSUE TITLE
[REC] WOTLK Can't set suitable condition for the spell "ghoul_frenzy" of unholy Death Knight

### ISSUE THREAD

**Issue by tangaiyun** [Hekili/hekili#2674]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In the lastest Hekili for WLK, For my unholy DK, I would like Hekili recommendate skill ghoul_frenzy when the pet ghoul doesn't have the buff  "ghoul_frenzy", not when the player's  ghoul_frenzy  cooldown is ready.

so I give the action with the following condition, but they don't work:

1. actions.st+=/ghoul_frenzy,if=pet.ghoul.up&pet.buff.ghoul_frenzy.down

or

2. actions.st+=/ghoul_frenzy,if=pet.ghoul.up&buff.ghoul_frenzy.down

or
3. actions.init+=/variable,name=ghoul_frenzy_can_proc,value=buff.ghoul_frenzy.last_applied=0|query_time-buff.ghoul_frenzy.last_applied>=30
actions.st+=/ghoul_frenzy,if=pet.ghoul.up & variable.ghoul_frenzy_can_proc

### How to Reproduce

1. enter game as a unholy dk
2. change the ghoul_frenzy condition as I said above
3. cast spells following the hekili recommendations
4. the ghoul_frenzy would be recommendated when the cooldown is ready

### Snapshot (Link)

https://pastebin.com/MsJkFMEy

**Comment by tangaiyun** [comment]
@Hekili 
Is there any suggestion for this issue?

**Comment by Hekili** [comment]
This will be fixed in the next release.
