### ISSUE TITLE
Demonology, Soul Fire + Decimation

### ISSUE THREAD

**Issue by nono1313234** [Hekili/hekili#2676]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello! this question is for  demonology, wlk version

I basically ask whenever buff.decimation.up it will cast Sour Fire,
 but however, it seems cannot continously suggest sour fire, it always disappeared for a short amount of time before it pops back, or while i cast soul fire, it wont continously suggest soul fire anymore, this is more out of curiousity, do you know if there's any setting/condition that I can add to prevent this ?
seems after a gcd casting other spell, the soul fire will back to the recommend priority. (or you wait for a bit i guess) 

in the ideal world, I wish it could be display like this
![image](https://github.com/Hekili/hekili/assets/136677944/bd1a8aac-e230-4dd5-beca-a505104df549)
but it keep suggesting like this
![image](https://github.com/Hekili/hekili/assets/136677944/b08aace0-b0b8-4dfe-b91e-983cf4eaf316)

Thank you so much!

### How to Reproduce

this is my hekili code in case you need.

but basically 
1. Enter the game as Demonlogy Warlock
2. Go to a practice dummy or raid Single Target (below 35% current health)
3. if soulr fire has cast condition "buff.decimation.up" it will recommend in the first place, but it cannot be continously suggest soul fire for some reason, if I have the condition set to "buff.decimation.down" it will continously suggest keep casting soul fire which makes me wondering, does hekili recommend skill with condition like this only check the buff once?", it will recommend other skill, and after about 250ms (or depands on your network latency), or 1 gcd, it will recommend soul fire again.

Hekili:TI12QrUny4NLLfgAjz9Cmh2ssUOukSHs6fUqVZ2YYA8igzlJKCMoWIH(o0xJEBFKk03I(lzpYN9mjTeiyl9F(W3)VhVLE)INBesr8Ez1IvRxC7YBCwU(M7xFVNR6ygXZndH3JIHhsrjW))7F)V(N)8p0hFKXrrA2L8CbgUANsLj)U5ZpWpOcXoXXWtk2(5ygsk)uConIiNhrs4PCgp(4NoGemoE)Cp3WCkt9LuVWw2YQv355IYv74cpxRqb9qJIiLetKyWWoaMJGVLYaJ4JFSi4hS6Oi4xlvsXZ6lwDxrWpscHha5x8CXZiSIYtLozccMNeIux948TeMpsKWfxt3(yy(2ToM3CI4hshMdzEcOqFGX4CKisZ3hYikhnTVsMKNx50Odi2EI4TWfnj7IiNr3s8vidXXSJz7CoDIdjffYirZmoO90X9XmU(SrSkEoZFlvq06rHyKuLdyIc(RKiF5oeiv)qotDsPnI8a3Mkck2NKKXpqeja3nVUJIHtOqmGbLjMqGII3ttJNPqIyiAOOjGNW9JOKNI4AZOKwNOCbQRGIf88mFCUqAKveXemsowEKjymZ8OVHsTHxZSekWMM3MuJ5crEM(TlXQRPEq7oHOqqfz2oUKk1YBlnENYxqsq0u5tRwU4RFnKlLZAD(dBw0ui5GBrvKezVCHpEN2SSL)TuNtE2jRoIkvOum5P7hi7aV5JaB34U5zTIfig0HzE1NbY4AnYYJio5APsqXQhxQzQSU2NKssOe5tlBf7RRPUWsUzvjOQRsqsfrC05uObdV7RZcxTQPE(V1)0nt1U6PFltebttmroR0RI07iiMANtgw9W6BgQOXA)TYePyAkru1PuMkHqcbsWCbXPDsPrmRjWiKvgQGRtYzDxgotrqfvL6Clds)xIqLei3Y363Ux6CC1GA8rmtNN0HpzzvMTtSTyEyZiEe5njep3xjcjiLMt0GXEPaXsp3VaiEcfaReSUiOuDfb6ocPtXZEUMNmZNjBr5mf84lM51LKQpVhYPNBvPJ337PaT2K8sK0ouSwtr9jUybakiOOs2QDMIGNkcwcd7nTOAdXk3U9ZLwUF5(cq0tRMnJQMpueuf(kcMbp3R42O5bXYRnHtxPv1nJQQrK9TlA4lg4EOilIZt0s72)hm8bGZBOr7LA1DxZeMfIUto7(tvcTs3w2oHg10ytqPin(rrWdqACbyXg8GqgNhXYLkdYLw2FUJ)oLqhgs0engawuFCXZJO2LlgWNcBN8gbKSz0VgO04OR3mvQXcAw7LwyzJnTC64SipTDz)49opcb964sdFipRv3c8G(sF0Ee53YngXQ3Tr0ly485ZPS1VBLDXESjJ3Xms5AcmwWMPTGgJP80)5A3d1IooyZAN94RfODB)tWLtPCD1bJMUVNKD138tWn2c6ZejhQDQFpZzroR)aGgwz7VgzAiXPLr9xNCwOWjKcSxMfABq2Ft4idedRGeBIB0VHUpuYu7lwwCPhE1TSk8mZixxR8wRnzhhpOGGiOgkOZ8mA1(tdnOUDhHzjQZAzduozftVLRUePDZuouZPJDfaGhTzWzGUT2Vsh77w59(vJDlHHuIQjsuvsFGg4oTRDwOECapRnyxkFcaNokPZ8I(12tUh3fuTBS7j)cjtOS(RmcUQiy1yOYV8wXW7miAaG8jBNVuK7QqLrLHijj6NHBA(Bf9n2FKPVfyjJG1RdPj37F)d

### Snapshot (Link)

N/A

### Contact Information

asahey#3449

**Comment by nono1313234** [comment]
again thank you so much":) please let me know if any part that confused you as English is really like my...third language:)

**Comment by nono1313234** [comment]
Also this is a very side question - is there a way that we can customise Trinkets or items that we can use? or it has to pre-defined by you in hekili? I am kinda noob in the world of programming so please forgive me if this sounds silly;)

**Comment by Hekili** [comment]
Right now, the addon models Soul Fire as consuming the Decimation buff, so it doesn't forecast it as the next cast as well.  I'll adjust for that.

Additionally, the cast of Soul Fire in the default Demonology priority wasn't checking specifically for the Decimation buff; just that you have the talent.  I'll take a look at that as well.

If you have more information to share, please make sure to include a proper snapshot:

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
