### ISSUE TITLE
[REC] problem with prio in arcane mage

### ISSUE THREAD

**Issue by SebastianPlominski** [Hekili/hekili#2677]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

while raiding and on traning dummy gets snapshots all the time, the rotation that hekilli shows me completely is different than it should be.

### How to Reproduce

1. Enter the game as Arcane Mage
2. Go to a practice dummy or raid Single Target
3. Follow single target recommendations as it tells you

### Snapshot (Link)

https://pastebin.com/hsVaUcvS

**Comment by Hekili** [comment]
> the rotation that hekilli shows me completely is different than it should be.

Explain.

**Comment by Hekili** [comment]
Have you modified the priority in any way?  The `rotation` action list wasn't actually tested in your snapshot.  If you check the priority under Priorities > Arcane > Action Lists, do you see `rotation` in the list?

**Comment by SebastianPlominski** [comment]
> > the rotation that hekilli shows me completely is different than it should be.
> 
> Explain.

when use BL hekili want me to only use Arcane Blast 15x in a row, but i see on top players using 2x arcane blast 1x arcane missles

> Have you modified the priority in any way? The `rotation` action list wasn't actually tested in your snapshot. If you check the priority under Priorities > Arcane > Action Lists, do you see `rotation` in the list?

yes i see, and all on list its enabled
![image](https://github.com/Hekili/hekili/assets/86687550/3b10b8da-d9f8-4991-ab6b-4f91b5c85fdf)

**Comment by Hekili** [comment]
> when use BL hekili want me to only use Arcane Blast 15x in a row, but i see on top players using 2x arcane blast 1x arcane missles

Take a snapshot when that's happening and share that.

For the auto-snapshot issue:

> yes i see, and all on list its enabled

Can you check the `default` action list and confirm the last entry `[Call Action List]` is enabled and references the `rotation` action list?

**Comment by SebastianPlominski** [comment]
> > when use BL hekili want me to only use Arcane Blast 15x in a row, but i see on top players using 2x arcane blast 1x arcane missles
> 
> Take a snapshot when that's happening and share that.
> 
> For the auto-snapshot issue:
https://pastebin.com/SESRxBA5
> 
> > yes i see, and all on list its enabled
> 
> Can you check the `default` action list and confirm the last entry `[Call Action List]` is enabled and references the `rotation` action list?

its last and enabled

**Comment by SebastianPlominski** [comment]
could it be because I don't have a 4 set?

**Comment by Hekili** [comment]
It should work regardless of 4-set.

**Comment by SebastianPlominski** [comment]
Hi,

ok, I have noted some strange things regarding arcane mage, the rotation of the skils is a little different than the top players use or from the tutorials, very often it does not show the use of Nether Tempest if it is coldown, the same applies to Touch of the Magi can even 2min be available to use and hekili does not show to use, arcane surge the same problem, on the raid it was available for 2.5 minutes. I don't know if it's a patch issue or if it's really hard to program it through the complicated arcane mage rotation.

This is the last snapshot that made on training dummy

greetings,

https://pastebin.com/Lq6RPPq6

**Comment by Hekili** [comment]
Sorry; can you elaborate?

For the snapshot you posted, Arcane Missiles was recommended.  What should have been recommended at that time?  Why?

**Comment by SebastianPlominski** [comment]
I sent a snapshot just like that, the bigger problem I see is the lack of use of Arcane surge and other CDs - Touch of the Magi, I reported the problem because I think something is wrong, I also play Shadow Priest and tested hekili there and never had problems or snapshots, everything worked fine. nevermind i just go learn rotation without hekili :P

**Comment by Hekili** [comment]
> I sent a snapshot just like that, the bigger problem I see is the lack of use of Arcane surge and other CDs - Touch of the Magi, I reported the problem because I think something is wrong, I also play Shadow Priest and tested hekili there and never had problems or snapshots, everything worked fine. 

You are listing multiple spells.  When it recommended Arcane Missiles, what was the exact spell you thought should've been recommended at that time?

Arcane Surge and Touch of the Magi were both on cooldown at the time you took the snapshot, so it wouldn't make sense to recommend them at that moment.

**Comment by Hekili** [comment]
Sorry, I haven't been able to get the information needed to investigate this further.
