### ISSUE TITLE
[REC] Charred Passion buff not being tracked on Brewmaster Monk

### ISSUE THREAD

**Issue by MrZombieCow** [Hekili/hekili#2681]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon does not properly track Brewmasters buff for Charred Passions

### How to Reproduce

1. Pick Brewmaster
2. Pick talent Charred Passions
3. Use Breath of Fire
4. "buff.charred_passions.up=false"

### Snapshot (Link)

https://pastebin.com/1PUiJvdt

### Additional Information

Buff ID is 386963, while Talent ID is 386965

### Contact Information

sweettears - discord

**Comment by Hekili** [comment]
I have a fix prepared for this.  In the future, please be sure to snapshot when you have the issue, so that it contains the necessary information.  Thanks!
