### ISSUE TITLE
Devastation Evoker Unravel Not being recommended on Unbound Abomination (The Underrot)

### ISSUE THREAD

**Issue by maxj30** [Hekili/hekili#2683]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Unbound Abomination is considered shielded and Unravel can be used. However it is never recommended in the rotation during that fight.

### How to Reproduce

1. Enter the game as a Devastation Evoker.
2. Ensure Interrupts and and [unravel ](https://www.wowhead.com/spell=368432/unravel)are toggled on.
3. Ensure you have the [unravel spell](https://www.wowhead.com/spell=368432/unravel) talented.
4. Go to "The Underrot" final boss "[Unbound Abomination](https://www.wowhead.com/npc=133007/unbound-abomination)"
5. The boss is shielded by [blood barrier](https://www.wowhead.com/spell=269185/blood-barrier). However Unravel is never recommended. 

### Snapshot (Link)

Devastation; Primary - Living Flame(0.00), Fire Breath(1.81), Shattering Star(2.72)

### Contact Information

tweety.bird

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
For clarity:  The snapshot you provided was incomplete and did not look like it was taken at the time in question.  Snapshots are hundreds/thousands of lines. You have to press CTRL+A in the snapshot box to select all the hidden text and then paste it to Pastebin to link here.  Thanks!
