### ISSUE TITLE
【REC】 by any chance we could add Mjolnir Runestone into buff? 

### ISSUE THREAD

**Issue by nono1313234** [Hekili/hekili#2684]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

this is more for druid dps （cat)， i wonder if you could add trinket Mjolnir Runestone buff id 65019 into buff list? so I it would be great if we would able to to have something like buff.65019.up and prioritise Shred (as far as the end of p3 i think that trinket is still the bis trinket)

*thanks for adding soul fire btw!
,

### How to Reproduce

n/a

### Snapshot (Link)

n/a

### Additional Information

n/a

### Contact Information

asahey#3449

**Comment by Hekili** [comment]
@zmsl Is this worth doing for Cat Druid?

**Comment by zmsl** [comment]
That's already implemented in the 'Optimize Rake' setting.

![image](https://github.com/Hekili/hekili/assets/13343767/a3ce8b4b-b261-4b2a-a184-f7accd09b3ad)
