### ISSUE TITLE
[REC] Fury Warrior - Execute in target swap is frozen in the cycle

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2685]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hey, only sometimes, and I can't say when, maybe a snapshot will help, it happens that when I choose target swap, Execute spell gets stuck and still requires swap to another target, when I do it, it swaps again to another target, etc over and over again, it's stuck and there's no other way out of it than to leave the fight.

### How to Reproduce

1. Enter the game as a Fury Warrior
2. Check all Toggles and recommended target swap
3. Go on dummies at least with 5 targets
4. Play rotation and wait for execute swap

### Snapshot (Link)

https://pastebin.com/cuMxAKpy

**Comment by Hekili** [comment]
You must be using the default priority to report this kind of issue. Feel free to add a snapshot using the default priority. 

I don't see anything in the snapshot immediately; that may mean that you'll want to grab BugSack/BugGrabber in case there are other error messages.

**Comment by marekCs** [comment]
You added the f8 key as a shortcut for snapshots, I guess that wasn't the case before? That's why it froze because I always have the f8 key for the macro /targetenemy, like for swap and freezing was snapshotting the screen, funny, pls don't make it the default key for your interface but some just random alt+something.

**Comment by Hekili** [comment]
No, that's not a default but it is pretty funny. Might you have accidentally rebound the button on the Toggles tab? Or your F8 is mapped to Ctrl-Shift-P?

**Comment by marekCs** [comment]
Oh sorry, my mistake, looks like I accidentally gave it f8 and furiously clicked f8 when the swap and the whole pc was dead :D
