### ISSUE TITLE
Key Binding not matching Prot spec, Ret spec is all ok

### ISSUE THREAD

**Issue by Blujelly87** [Hekili/hekili#2686]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've noticed that Sentinel is showing on my key binds via Hekili action bar as 'S' when it is actually 'Shift R. I then swapped it with Avengers shield the key bind is 'E' and both work fine both 'E' & 'SR' showed on the action bar, when I swapped them back to their original positions, Sentinel started showing as 'S' again.

Currently use Bartender4 & the bar it sits on is bar 3.

### How to Reproduce

As noted above

<img width="483" alt="Screenshot 2023-06-27 at 08 36 31" src="https://github.com/Hekili/hekili/assets/116963975/8033c860-50d5-45b3-914f-d031118e8408">

### Snapshot (Link)

https://pastebin.com/DXzym3Kk

**Comment by Hekili** [comment]
`avenging_wrath            = S   [02], SR  [05]`

(Sentinel replaces Avenging Wrath and shares its bindings.)  You have it on bar 2 bound to S and bar 5 bound to SR.  Bar 2 takes precedence over Bar 5 for bindings.
