### ISSUE TITLE
Survival APL is a little behind.

### ISSUE THREAD

**Issue by Crelam** [Hekili/hekili#2687]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I hesitated to make this ticket because I'm sure its on your list, but just in case this one slipped by you... the Survival APL in the Addon is not matching the APL in simulationcraft.  Notably the inclusion of the on use effect of Djaruun, Pillar of the Elder Flame.

I know Survival Hunter is likely a low priority due to the spec not being the most popular so I'm sure there is no rush.

### How to Reproduce

Compare APL between Addon and [SimulationCraft](https://github.com/simulationcraft/simc/blob/dragonflight/profiles/Tier30/T30_Hunter_Survival.simc).

### Snapshot (Link)

N/A

### Raidbots Sim Report (Link)

N/A

### Contact Information

Crelam

**Comment by Hekili** [comment]
Can you be more specific?  

> Notably the inclusion of the on use effect of Djaruun, Pillar of the Elder Flame.

By this, do you mean that the buff isn't detected or something else?  What's different about the APLs?

**Comment by Crelam** [comment]
No, there is nothing in the addon APL that specifically calls to use the item while in the [SimulationCraft APL](https://raw.githubusercontent.com/simulationcraft/simc/dragonflight/profiles/Tier30/T30_Hunter_Survival.simc) there is at lines 64, 86, 98, & 110.  There may be other changes as well, I did not do a deep dive into comparing the file changes over the past few updates.

**Comment by Hekili** [comment]
Weird.  It's definitely in the APL file, but looks like it simply hasn't been imported.

https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/APLs/HunterSurvival.simc#L38
https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/APLs/HunterSurvival.simc#L60
https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/APLs/HunterSurvival.simc#L72
https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/APLs/HunterSurvival.simc#L84

I'll import and include it in the next release.
