### ISSUE TITLE
[BUG] no mage spec coming up after trouble shootiong

### ISSUE THREAD

**Issue by darthspell** [Hekili/hekili#2688]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

loaded this addon through curse forge and can have it working on all my other toons but load into my mage and there is nothing even after trouble shooting there is nothing at all 

### How to Reproduce

enter as fire mage and try it 

### Player Information (Link)

https://pastebin.com/ggp7B1qp

### Error Messages (Link)

no error message

### Contact Information

damianmaguire@hotmail.com

**Comment by Hekili** [comment]
Not supported in Wrath yet.
