### ISSUE TITLE
Sub Rogue - Missing flagellation in the ST rotation list

### ISSUE THREAD

**Issue by TeckZ11** [Hekili/hekili#2692]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello!

the following build is using flagellation and i haven't seen it anywhere in the suggested rotation. I do not know what else you'd need.

https://www.wowhead.com/guide/classes/rogue/subtlety/talent-builds-pve-dps#mythicplus-build-single-dance

### How to Reproduce

https://www.wowhead.com/guide/classes/rogue/subtlety/talent-builds-pve-dps#mythicplus-build-single-dance

I do not know what else to put here since 

### Snapshot (Link)

is the snapshot needed ?

### Contact Information

Gatz1

**Comment by Hekili** [comment]
Yes, the snapshot is required.  More likely than not, the toggle for Flagellation is turned off, but I can't see any of your settings without the snapshot.
