### ISSUE TITLE
[REC] Time Warp never being recommended with Temporal Warp talent

### ISSUE THREAD

**Issue by dglynch** [Hekili/hekili#2693]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my frost mage, which has the talent Temporal Warp, I expect Time Warp to be recommended at some point when it is off cooldown and when my character has Temporal Displacement or similar effect. Instead, the addon never recommends this spell.

I believe the problem is that the variable buff.exhaustion.up is false even when I have the debuff temporal_displacement on my character. This inconsistency is shown in the snapshot linked below.

If you look at the RaidBots sim linked below, you will see it casts Time Warp after the initial Bloodlust wears off at 40 seconds, unlike the Hekili recommendation.

### How to Reproduce

1. Enter the game as a frost mage.
2. Take the Temporal Warp talent.
3. Use Time Warp.
4. Execute the recommended spells.
5. Wait 40 seconds until Time Warp wears off.
6. See recommendations.

### Snapshot (Link)

https://pastebin.com/05uNqjXL

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hfY5Ny55SjnhDqfXF6M5Cq

**Comment by Hekili** [comment]
For addon purposes, checking for any/all Bloodlust exhaustion type auras should be `debuff.sated.up`.  It's definitely not a `buff`.

I'll update these, but probably not until 10.1.5 lands.

**Comment by Hekili** [comment]
Actually, I went ahead and updated it for tonight's release.

**Comment by dglynch** [comment]
I confirm this is fixed for me in the latest release.
