### ISSUE TITLE
[REC] Potion not being recommended for frost mage

### ISSUE THREAD

**Issue by dglynch** [Hekili/hekili#2694]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my frost mage, the potion is never recommended. I believe this is because the priority list includes a Shadowlands potion ("potion = phantom_fire" in the snapshot) which I don't have in my bags. It should recommend a Dragonflight potion instead.

### How to Reproduce

1. Enter the game as a frost mage.
2. Enable potions.
3. See recommendations.

### Snapshot (Link)

https://pastebin.com/rTK20SDg

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hfY5Ny55SjnhDqfXF6M5Cq

**Comment by Hekili** [comment]
The `phantom_fire` bit there doesn't actually do anything; it's from when the addon still had a dropdown where you could pick which potion you wanted.

Which Dragonflight potion(s) do you have in your bag?

**Comment by Hekili** [comment]
Also, if you go to /hekili > Gear and Items, and select "Potion" at the upper right, what do you see?

![image](https://github.com/Hekili/hekili/assets/9438134/902df466-bb1d-4594-996d-962d70ba0ab4)

**Comment by dglynch** [comment]
> Which Dragonflight potion(s) do you have in your bag?

Elemental Potion of Ultimate Power, Rank 2. I am using this same potion on my retribution paladin and it works fine.

> Also, if you go to /hekili > Gear and Items, and select "Potion" at the upper right, what do you see?

![image](https://github.com/Hekili/hekili/assets/442152/609a6a69-e0b1-427e-ab4f-cf22d100ffb6)

**Comment by Hekili** [comment]
What about `/dump Hekili.Class.abilities.potion`?  It is strange that the Potion ability shows that it's unknown in your snapshot.

Does it work after reloading your UI?

**Comment by dglynch** [comment]
Reloading my UI does not seem to change anything.

Here's the output from that dump command:

> [08:12:18] Dump: value=Hekili.Class.abilities.potion 
> [08:12:18] [1]={ 
> [08:12:18]   gcd="off", 
> [08:12:18]   bagItem=true, 
> [08:12:18]   itemSpellName="Elemental Potion of Ultimate Power", 
> [08:12:18]   realCast=0, 
> [08:12:18]   handler=<function>, 
> [08:12:18]   key="potion", 
> [08:12:18]   listName="|T136243:0|t |cff00ccff[Potion]|r", 
> [08:12:18]   texture=967534, 
> [08:12:18]   itemLoaded=253442.829, 
> [08:12:18]   charges=1, 
> [08:12:18]   recharge=300, 
> [08:12:18]   link="|cffffffff|Hitem:191382::::::::70:64:::::::::|h[Elemental Potion of Ultimate Power |A:Professions-ChatIcon-Quality-Tier2:17:23::1|a]|h|r", 
> [08:12:18]   id=-101, 
> [08:12:18]   itemSpellID=371028, 
> [08:12:18]   itemPended=253442.829, 
> [08:12:18]   funcs={ 
> [08:12:18]     cast=<function>, 
> [08:12:18]     usable=<function>, 
> [08:12:18]     item=<function>, 
> [08:12:18]     timeToReady=<function> 
> [08:12:18]   }, 
> [08:12:18]   name="Potion", 
> [08:12:18]   from=0, 
> [08:12:18]   itemSpellKey="elemental_potion_of_ultimate_power_371028", 
> [08:12:18]   startsCombat=false, 
> [08:12:18]   cooldown=300, 
> [08:12:18]   toggle="potions" 
> [08:12:18] }

**Comment by Hekili** [comment]
Thanks; this is sorted for next release.

**Comment by dglynch** [comment]
I confirm this is fixed for me when I apply the mentioned commit as a patch locally.
