### ISSUE TITLE
[REC] [WOTLK] Refusal to add Rend to the priority if in Berserker Stance

### ISSUE THREAD

**Issue by KevinTyrrell** [Hekili/hekili#2695]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Issue: Priority is completely ignored if the user's stance does not match the priority ability. 

 For example, I've modified the default Fury priority to put Hamstring as the first priority assuming `1 < 2` (always)
![image](https://github.com/Hekili/hekili/assets/12791400/06fdc5fe-bc8b-4d0d-9d09-82222e7261a9)
 
I am in berserker stance and this works perfects, as one would expect.
![image](https://github.com/Hekili/hekili/assets/12791400/d67d7ea8-707b-49a3-a093-8dc543459200)

However if I change my ability to Rend instead of Hamstring...
![image](https://github.com/Hekili/hekili/assets/12791400/f9ce408f-f6cb-4d67-8b43-0abdcd6273e8)

Now, you can see the priority has completely skipped Rend, despite it being the number one priority ability.
![image](https://github.com/Hekili/hekili/assets/12791400/784f623d-1428-4129-ad35-efbfbc52d816)

What one would expect is, when rend's time in the priority queue is ready, the rend icon is shown regardless of what stance they are currently in.

### How to Reproduce

1. Enter game as a Warrior
2. Set highest priority as 'Rend' while in Berserker stance
3. Observe that rend does not appear on the priority queue

### Snapshot (Link)

N/A

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
