### ISSUE TITLE
[BUG] Hekili No longer recommending abilities on Outlaw

### ISSUE THREAD

**Issue by Elfykins** [Hekili/hekili#2697]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I don't know what changed in the past 24 hours, but it was working for me fine 2 days ago, but now it is not. All of a sudden Hekili is no longer recommending Beacon from Beyond or my Grieftorch, it is also no longer telling me when to use vanish or Shadow Dance. I don't know if it's a me issue or what, but I didn't do anything except 1 thing on my Evoker where I disabled the screaming black dragonscale from showing up (as it actually doesn't do anything in combat unless you're flying from above).

### How to Reproduce

1. Enter game as Outlaw Rogue
2. Attempt to do a mythic+/raid/dummy
3. Vanish (even while in team), trinkets and shadow dance do not get recommended at all.

### Player Information (Link)

https://pastebin.com/yyH6GV1T

### Error Messages (Link)

https://pastebin.com/7kHKDKW4

### Additional Information

I noticed the errors in the log for today, so no idea what happened.

**Comment by Hekili** [comment]
The error message is from loading the options screen in combat, not actually relevant. 

You have Cooldowns toggled off, so your Cooldowns abilities arent going to show. See /hekili > Toggles.
