### ISSUE TITLE
Hekili Script error bugsack report

### ISSUE THREAD

**Issue by RogerRabbit10** [Hekili/hekili#2698]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

1x Hekili/UI.lua:2328: script ran too long
[string "@Hekili/UI.lua"]:2328: in function <Hekili/UI.lua:2261>

Locals:
self = HekiliEngine {
 0 = <userdata>
 combatRate = 0.200000
 activeThreadStart = 183855706.609700
 activeThreadFrames = 1
 refreshTimer = 0
 UpdatePerformance = <function> defined @Hekili/UI.lua:2199
 activeThreadTime = 0
 superUpdate = false
 activeThread = <no value>
 eventsTriggered = <table> {
 }
 IsThreadActive = <function> defined @Hekili/UI.lua:2369
 refreshRate = 0.500000
 criticalUpdate = false
}
elapsed = 0.014000
thread = <no value>
firstDisplay = nil
superUpdate = nil
ok = false
err = "Hekili/Scripts.lua:906: script ran too long"
(*temporary) = false
(*temporary) = "Hekili/Scripts.lua:906: script ran too long"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
insert = <function> defined =[C]:-1
frameSpans = <table> {
 1 = 0.014000
}
Hekili = <table> {
 GetMacroCastTarget = <function> defined @Hekili/Events.lua:1086
 GetTTD = <function> defined @Hekili/Targets.lua:1181
 IC = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili/Options.lua:4040
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili/Targets.lua:1166
 EmbedDisciplinaryCommand = <function> defined @Hekili/Dragonflight/MageArcane.lua:615
 GetPetBasedTargetSpells = <function> defined @Hekili/Targets.lua:121
 After = <function> defined @Hekili/Utils.lua:284
 LoadingScripts = true
 activeFrameStart = 183855706.613200
 IsRetail = <function> defined @Hekili/Hekili.lua:22
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 currentSpecOpts = <table> {
 }
 SaveCoordinates = <function> defined @Hekili/UI.lua:3091
 PLAYER_ENTERING_WORLD = true
 UpdateDisplayVisibility = <function> defined @Hekili/UI.lua:2063
 PendingSpecializationChange = false
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 ResetSpellCaches = <function> defined @Hekili/Core.lua:580
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili/State.lua:6800
 SetMode = <function> defined @Hekili/Options.lua:10774
 Version = "v10.1.0-1.0.2c"
 baseName = "Hekili"
 GetPetBasedTargetSpell = <function> defined @Hekili/Targets.lua:133
 ToggleHold = <function> defined @Hekili/State.lua:6825
 SpecializationChanged = <function> defined @Hekili/Classes.lua:5937
 Update = <function> defined @Hekili/Core.lua:1446
 BuildUI = <function> defined @Hekili/UI.lua:2804
 GetGreatestTTD = <function> defined @Hekili/Targets.lua:1260
 GetNumTargetsAboveHealthPct = <function> defined @Hekili/Targets.lua:1337
 GetNextPrediction = <function> defined @Hekili/Core.lua:1333
 UpdateUseItems = <function> defined @Hekili/Events.lua:657
 SetSpecOption = <function> defined @Hekili/Options.lua:3822
 GetDefaults = <function> defined @Hekili/Options.lua:446
 dumpKeyCache = <table> {
 }
 GetPredictionFromAPL = <function> defined @Hekili/Core.lua:657
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetDisplayByName = <function> defined @Hekili/Core.lua:1415
 Options = <table> {
 }
 ReInitialize = <function> defined @Hekili/Core.lua:167
 GetSpellLinkWithTexture = <function> defined @Hekili/Utils.lua:582
 IsSpellEnabled = <function> defined @Hekili/Core.lua:574
 GetAbilityInfo = <function> defined @Hekili/Classes.lua:5882
 IsSpellKnown = <function> defined @Hekili/Core.lua:561
 State = <table> {
 }
 OnEnable = <function> defined @

### How to Reproduce

I just logged in and it happened

### Player Information (Link)

build: v10.1.0-1.0.2c level: 70 (70) class: MAGE spec: fire  talents: B8DAHVkVsxxZrVqBmAzlSR2f7nkAhWikESxBgD0SiIiIJAAAAAAAAA4AEIRokkIJRSSSSDAAAA

### Error Messages (Link)

1x Hekili/UI.lua:2328: script ran too long [string "@Hekili/UI.lua"]:2328: in function <Hekili/UI.lua:2261>  Locals: self = HekiliEngine {  0 = <userdata>  combatRate = 0.200000  activeThreadStart = 183855706.609700  activeThreadFrames = 1  refreshTimer = 0  UpdatePerformance = <function> defined @Hekili/UI.lua:2199  activeThreadTime = 0  superUpdate = false  activeThread = <no value>  eventsTriggered = <table> {  }  IsThreadActive = <function> defined @Hekili/UI.lua:2369  refreshRate = 0.500000  criticalUpdate = false } elapsed = 0.014000 thread = <no value> firstDisplay = nil superUpdate = nil ok = false err = "Hekili/Scripts.lua:906: script ran too long" (*temporary) = false (*temporary) = "Hekili/Scripts.lua:906: script ran too long" (*temporary) = false (*temporary) = nil (*temporary) = nil (*temporary) = nil (*temporary) = nil (*temporary) = nil (*temporary) = "script ran too long" insert = <function> defined =[C]:-1 frameSpans = <table> {  1 = 0.014000 } Hekili = <table> {  GetMacroCastTarget = <function> defined @Hekili/Events.lua:1086  GetTTD = <function> defined @Hekili/Targets.lua:1181  IC = <table> {  }  EmbedAbilityOptions = <function> defined @Hekili/Options.lua:4040  Scripts = <table> {  }  GetDeathClockByGUID = <function> defined @Hekili/Targets.lua:1166  EmbedDisciplinaryCommand = <function> defined @Hekili/Dragonflight/MageArcane.lua:615  GetPetBasedTargetSpells = <function> defined @Hekili/Targets.lua:121  After = <function> defined @Hekili/Utils.lua:284  LoadingScripts = true  activeFrameStart = 183855706.613200  IsRetail = <function> defined @Hekili/Hekili.lua:22  SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405  currentSpecOpts = <table> {  }  SaveCoordinates = <function> defined @Hekili/UI.lua:3091  PLAYER_ENTERING_WORLD = true  UpdateDisplayVisibility = <function> defined @Hekili/UI.lua:2063  PendingSpecializationChange = false  IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447  ResetSpellCaches = <function> defined @Hekili/Core.lua:580  KeybindInfo = <table> {  }  RemoveHold = <function> defined @Hekili/State.lua:6800  SetMode = <function> defined @Hekili/Options.lua:10774  Version = "v10.1.0-1.0.2c"  baseName = "Hekili"  GetPetBasedTargetSpell = <function> defined @Hekili/Targets.lua:133  ToggleHold = <function> defined @Hekili/State.lua:6825  SpecializationChanged = <function> defined @Hekili/Classes.lua:5937  Update = <function> defined @Hekili/Core.lua:1446  BuildUI = <function> defined @Hekili/UI.lua:2804  GetGreatestTTD = <function> defined @Hekili/Targets.lua:1260  GetNumTargetsAboveHealthPct = <function> defined @Hekili/Targets.lua:1337  GetNextPrediction = <function> defined @Hekili/Core.lua:1333  UpdateUseItems = <function> defined @Hekili/Events.lua:657  SetSpecOption = <function> defined @Hekili/Options.lua:3822  GetDefaults = <function> defined @Hekili/Options.lua:446  dumpKeyCache = <table> {  }  GetPredictionFromAPL = <function> defined @Hekili/Core.lua:657  SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420  GetDisplayByName = <function> defined @Hekili/Core.lua:1415  Options = <table> {  }  ReInitialize = <function> defined @Hekili/Core.lua:167  GetSpellLinkWithTexture = <function> defined @Hekili/Utils.lua:582  IsSpellEnabled = <function> defined @Hekili/Core.lua:574  GetAbilityInfo = <function> defined @Hekili/Classes.lua:5882  IsSpellKnown = <function> defined @Hekili/Core.lua:561  State = <table> {  }  OnEnable = <function> defined @

**Comment by Hekili** [comment]
It's been a long time since you posted this; I would've also needed the full data from your Player Information sheet to see what your settings are.  I believe this has been impacted/resolved since you posted, but if you experience this again, feel free to open a new ticket.
