### ISSUE TITLE
[REC] Rogue Sub Priority Shadow_Dance cooldown variable bug?

### ISSUE THREAD

**Issue by danmarzola** [Hekili/hekili#2699]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

cooldown.shadow_dance.remains variable is fixed at 60, this value never change and cause severe problems in multiples recomendations like using finality buff to refresh rupture before shadow dance in single target situations

- this entry's criteria FAILS: !buff.shadow_dance.up[false] & buff.finality_rupture.up[true] & cooldown.shadow_dance.remains[60.00] < 12 & spell_targets.shuriken_storm[1.00] = 1 & ( talent.dark_brew.enabled[true] | talent.danse_macabre.enabled[true] )

### How to Reproduce

Enter as Sub Rogue
Play default or any customized rotation using cooldown.shadow_dance.remains variable and check snapshot

### Snapshot (Link)

https://pastebin.com/zxCGw7XP

**Comment by Hekili** [comment]
If you look at /hekili > Abilities > Shadow Dance, I assume it is on the Cooldowns toggle which you have shown in a separate display.  When that happens, the cooldown will be feigned in the other displays so you're not trapped in an endless cycle of preparing for the ability which you've intentionally shifted out of the queue.

You could try going to /hekili > Subtlety > Toggles and check `Cooldown: Show Separately - Use Actual Cooldowns` and decide if that is closer to what you're expecting to see.

**Comment by danmarzola** [comment]
Yeah, that what i was looking for, thx for this amazing addon, is much easier learning / teaching new class/specs
