### ISSUE TITLE
Demonology Demonic Strength unusuable at certain times

### ISSUE THREAD

**Issue by tacoinspace** [Hekili/hekili#27]
Demonic Strength causes the Felguard to spin. But if the felguard is currently spinning from felstorm, it's unable to use demonic strength, but the addon is currently not monitoring that.

**Comment by Hekili** [comment]
Thanks, will make a note of this.

**Comment by tacoinspace** [comment]
still have problems after the updates. perhaps it's because I use glyph of the wrathguard so my pet is listed as that instead of felguard?

**Comment by Hekili** [comment]
It shouldn't care which pet it is, but I can check into it.  Is the problem still that it's recommending Demonic Strength when you can't use it, or that it's not recommending Demonic Strength when you can?

**Comment by tacoinspace** [comment]
Recommending when I cant use it.

**Comment by Hekili** [comment]
Should be resolved in latest beta -- I had only fixed up Axe Toss and overlooked Demonic Strength.  Thanks!
