### ISSUE TITLE
True Shot Not Recommended

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [Hekili/hekili#270]
Trueshot (Marksman's major CD) is not being recommended. I made sure to check that I didn't have cooldowns turned off or Trueshot disabled in the settings. At first I thought it might have something to do with using vision of perfection minor which changes the CD of Trueshot, but even with a different minor it did not recommend it in the rotation.

1.  https://pastebin.com/kFCmh1q6 (Issue Report)

2.  https://pastebin.com/LJQP0Hd1 (Snapshot)

**Comment by Hekili** [comment]
Your gear wasn't detected for some reason. Can you /reloadui and do it again?

Also, was this a boss snapshot or a dummy? Time to die was not calculated here.

**Comment by BuurmanDeBuurman** [comment]
I redid both of them, I was fighting a target dummy (AOE) for the snapshot. 

1. https://pastebin.com/Mue0q54Q (Issue Report)
2. https://pastebin.com/5vnN1njS (Snapshot)

**Comment by Hekili** [comment]
There's a missing bracket in the conditions for Trueshot.  I'll be posting a fix soon.

**Comment by Hekili** [comment]
Fix is going out in -04-04.
