### ISSUE TITLE
[REC] Provide a short, descriptive title of you Recommendation issue

### ISSUE THREAD

**Issue by Wet777** [Hekili/hekili#2700]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Wow wotlk classic

when I am on my Druid in my feral dps build, I get the correct abilities showing on the addon but when I am my feral tank build, I only show bear abilities when I go into cat form.

Is this a bug or is there a setting I am missing to show abilities based on my form?

### How to Reproduce

Feral tank build

### Snapshot (Link)

N/A

### Contact Information

Discord:  .whets

**Comment by Hekili** [comment]
Please fix the title and add the required snapshot.
