### ISSUE TITLE
[rec] Feral Dps aoe recommend not working sometimes (wlk - toc)

### ISSUE THREAD

**Issue by nono1313234** [Hekili/hekili#2702]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello! I couldnt help but noticed hekili is unable to switch recommendation between single target and aoe when in auto mode at raid Trial Of The Grand Crusader, at boss Lord Jaraxxus (and the summoned minions) or Anub'arak, however I think it will recommand to switch for bosses like Faction Champions.

everything is in default, it used to work normally last week, not sure what happened. but I make sure the threshold switch between aoe is 3 (as default), could you possibly look into that by any chance?

### How to Reproduce

n/a

### Snapshot (Link)

n/a

### Raidbots Sim Report (Link)

n/a

### Additional Information

n/a

### Contact Information

asahey#3449

**Comment by nono1313234** [comment]
*everytihng is in default btw, for actionlist stuff, etc/

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by nono1313234** [comment]
okay， im out for cd this week ill try recreate it again next cd thanks!
