### ISSUE TITLE
Hunter Beast Mastery - buff.dire_pack

### ISSUE THREAD

**Issue by PhilipH3ro** [Hekili/hekili#2704]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Is it possible to add buff.dire_pack so it can be checked? Since right now the prio list is not finished without it.

### How to Reproduce

Play BM

### Snapshot (Link)

-

### Raidbots Sim Report (Link)

-

### Additional Information

-

### Contact Information

-

**Comment by Hekili** [comment]
Yeah.
