### ISSUE TITLE
[REC] Throw glaive should be in the opener and is blocked by blade_dance.remains condition

### ISSUE THREAD

**Issue by bobifle** [Hekili/hekili#2705]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my DH havoc, I expect to cast throw glaive (to apply serated debuff)  before fel rushing then eye beam. 

I may be related to the following rule:

25 throw glaive: talent.serrated_glaive.enabled & cooldown.eye_beam.remains < 6 & ! debuff.serrated_glaive.up & ! debuff.essence_break.up & cooldown.blade_dance.remains

cooldown.blade_dance.remains block the action, because it's not in cooldown on pull. I don't know if removing this would be a good fix, I don't know the impact for the non opener cycle. Howver Serated is a debuff that is critical for the opener.

![image](https://github.com/Hekili/hekili/assets/26679634/5fe02291-bb09-41f2-938f-b4cac9774564)

### How to Reproduce

Target a boss / dummy, throw glaive should be third in the recommendation, immolation aura -> sigilf of flame -> throw glaive

### Snapshot (Link)

Havoc; Primary - Immolation Aura(0.00), Fel Rush(1.27), Eye Beam(1.52), Vengeful Retreat(4.06), Essence Break(5.33)

**Comment by Hekili** [comment]
Sim yourself and look at what your sim does.  If the guide you're reading and the sim are out of alignment, you'll see different results in the addon as well.

**Comment by Hekili** [comment]
Also, I suspect you haven't updated in a while, because I'm pretty sure I already build in an option not to check Blade Dance's CD for Throw Glaive.  Check if that appears in your Havoc options and give it a try.

**Comment by bobifle** [comment]
I have the latest version, v10.1.0-1.0.2c and the blade dance cooldown is still here (defaut havoc package, I have no custom).
Let me try the sim on raidbot, bu tbh I'm not super familiar with raidbot

**Comment by bobifle** [comment]
like this ? 
https://www.raidbots.com/simbot/report/aUfMHMFh3jF2o4NekSVuDA/simc

but there's the issue with simulation craft prio list as well

throw_glaive,if=talent.serrated_glaive&cooldown.eye_beam.remains<6&!debuff.serrated_glaive.up&!debuff.essence_break.up&cooldown.blade_dance.remains

I don't know if it matters, but the guide is from the DH discord "The Fel Hammer" which is supposed to be the most accurate, same ppl who write on wowhead

**Comment by Hekili** [comment]
> there's the issue with simulation craft prio list as well

The sim priority generally has a reason to be designed as it is.  I do recommend going to /hekili > Havoc, and look at the "Throw Glaive before Blade Dance" option.

> I don't know if it matters, but the guide is from the DH discord "The Fel Hammer" which is supposed to be the most accurate, same ppl who write on wowhead

They also build the sim priority, so it's something they might want to revise the priority to make that happen.

Just for clarity, in that sim, here's your opener up to the first Throw Glaive:

<html><body>


Time | List | # | Name | Target | Resources | Buffs
-- | -- | -- | -- | -- | -- | --
Pre | precombat | 0 | flask | Bobe | 0.0/120: 0% fury |  
Pre | precombat | 1 | augmentation | Bobe | 0.0/120: 0% fury | corrupting_rage
Pre | precombat | 2 | food | Bobe | 0.0/120: 0% fury | corrupting_rage
Pre | precombat | 4 | 3min_trinket | Bobe | 0.0/120: 0% fury | corrupting_rage
Pre | precombat | 5 | trinket_sync_slot | Bobe | 0.0/120: 0% fury | corrupting_rage
Pre | precombat | 7 | arcane_torrent | Fluffy_Pillow | 0.0/120: 0% fury | corrupting_rage
Pre | precombat | 8 | use_item_algethar_puzzle_box | Fluffy_Pillow | 15.0/120: 12% fury | corrupting_rage
Pre | precombat | A | immolation_aura | Fluffy_Pillow | 15.0/120: 12% fury | algethar_puzzle, corrupting_rage
0:00.000 | default | B | auto_attack | Fluffy_Pillow | 35.0/120: 29% fury | immolation_aura, unbound_chaos, algethar_puzzle, corrupting_rage
0:00.000 | default | I | fel_rush | Fluffy_Pillow | 35.0/120: 29% fury | bloodlust, immolation_aura, unbound_chaos, algethar_puzzle, corrupting_rage
0:00.387 | cooldown | a | potion | Fluffy_Pillow | 62.0/120: 52% fury | bloodlust, immolation_aura, out_of_range, initiative, momentum, algethar_puzzle, corrupting_rage
0:00.462 | default | P | eye_beam | Fluffy_Pillow | 62.0/120: 52% fury | bloodlust, immolation_aura, initiative, momentum, algethar_puzzle, corrupting_rage, elemental_potion_of_ultimate_power
0:01.744 | default | G | annihilation | Fluffy_Pillow | 76.0/120: 63% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, inner_demon, algethar_puzzle,  corrupting_rage, elemental_potion_of_ultimate_power
0:01.744 | default | H | vengeful_retreat | Fluffy_Pillow | 36.0/120: 30% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, algethar_puzzle, corrupting_rage,  elemental_potion_of_ultimate_power
0:02.498 | default | J | essence_break | Fluffy_Pillow | 73.0/120: 61% fury | bloodlust, immolation_aura, metamorphosis,  vengeful_retreat_movement, furious_gaze, initiative, momentum,  tactical_retreat, algethar_puzzle, mutated_magmammoth_scale,  corrupting_rage, elemental_potion_of_ultimate_power
0:03.253 | default | B | auto_attack | Fluffy_Pillow | 81.0/120: 68% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, tactical_retreat, algethar_puzzle,  mutated_magmammoth_scale, corrupting_rage,  elemental_potion_of_ultimate_power
0:03.253 | default | K | death_sweep | Fluffy_Pillow | 81.0/120: 68% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, tactical_retreat, algethar_puzzle,  mutated_magmammoth_scale, corrupting_rage,  elemental_potion_of_ultimate_power
0:04.008 | cooldown | Z | metamorphosis | Fluffy_Pillow | 66.0/120: 55% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, tactical_retreat, algethar_puzzle,  mutated_magmammoth_scale, corrupting_rage,  elemental_potion_of_ultimate_power
0:05.173 | default | K | death_sweep | Fluffy_Pillow | 81.0/120: 68% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, inner_demon, tactical_retreat,  algethar_puzzle, mutated_magmammoth_scale, corrupting_rage,  elemental_potion_of_ultimate_power
0:05.926 | default | L | annihilation | Fluffy_Pillow | 54.0/120: 45% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, inner_demon, tactical_retreat,  algethar_puzzle, mutated_magmammoth_scale, corrupting_rage,  elemental_potion_of_ultimate_power
0:06.682 | default | S | annihilation | Fluffy_Pillow | 69.0/120: 57% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, initiative, momentum, tactical_retreat, seething_fury,  seething_potential, algethar_puzzle, mutated_magmammoth_scale,  corrupting_rage, elemental_potion_of_ultimate_power
0:07.436 | default | O | throw_glaive | Fluffy_Pillow | 37.0/120: 31% fury | bloodlust, immolation_aura, metamorphosis,  furious_gaze, momentum, tactical_retreat, seething_fury,  seething_potential, algethar_puzzle, mutated_magmammoth_scale,  corrupting_rage, elemental_potion_of_ultimate_power


</body>
</html>

**Comment by bobifle** [comment]
I asked the discord, there's a APL pending fix. So I'll guess it will be reflecting soon in Hekili.

![image](https://github.com/Hekili/hekili/assets/26679634/d4e89675-f3ce-4641-bc26-4fda20303b56)
