### ISSUE TITLE
[REC] Shadow Dance not being recommended for outlaw after initial 10.1.5  update

### ISSUE THREAD

**Issue by Gyudon47** [Hekili/hekili#2706]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shadow dance is not being recommended at any point for outlaw.

### How to Reproduce

Follow recommendation

### Snapshot (Link)

https://pastebin.com/cuRz2saF

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/xnaxYo4JcZeu24MsQ7KLKD

**Comment by Hekili** [comment]
Is this snapshot taken at a time when you'd expect Shadow Dance to be used?  I don't see any obvious reasons it *should* be used there.

**Comment by Gyudon47** [comment]
Yes it should be used here along with with dreadblades to fish as much count the odds procs before pressing Keep It Rolling.
Its just one example where it should be used. Either way it didn't recommend shadow dance at all.
You can see with the quick sim that it shows shadow dance being pressed after Dreadblades 3,8 seconds into the sim

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
