### ISSUE TITLE
enhance storm single target build not recommending elemental blast

### ISSUE THREAD

**Issue by freepain** [Hekili/hekili#2707]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

for my enhancement shaman, with the storm single target build in single target situations, it doesn't recommend elemental blast and will recommend only lightning bolt. i thought it should recommend elemental blast.

### How to Reproduce

1. Enter game as enhancement shaman
2. Import build: BcQAu3fz4tp2ZikXIAdNeR+oLIJJHAkcARSSSQSiECAAAAAAAAAAAAoEhIkgiAJtkkSgAJJogA
3. Attack single target
4. See recommendation

### Snapshot (Link)

https://pastebin.com/yRzV8jXW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nZuSciszBfNGBLNv24bfDa

### Additional Information

a

### Contact Information

pain.alv in discord

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
