### ISSUE TITLE
Guardian not recommending Incarnation

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#2708]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since the new update today, Guardian is not recommending incarnation at all

### How to Reproduce

1. Enter game as guardian druid
2. Have incarn
3. Hit dummies

### Snapshot (Link)

https://pastebin.com/kz1T3UaX

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
