### ISSUE TITLE
PaladinHoly.lua:433: bad argument #2 to 'setfenv' (table expected, got no value)

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#2709]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Getting LUA error with 10.1.5-1.0.0:

2x Hekili/Dragonflight/PaladinHoly.lua:433: bad argument #2 to 'setfenv' (table expected, got no value)
[string "=[C]"]: in function `setfenv'
[string "@Hekili/Dragonflight/PaladinHoly.lua"]:433: in main chunk

Locals:
(*temporary) = <function> defined @Hekili/Dragonflight/PaladinHoly.lua:433
(*temporary) = "table expected, got no value"

### How to Reproduce

Log into paladin using Hekili

### Player Information (Link)

https://pastebin.com/N1MFxtgg

### Error Messages (Link)

https://pastebin.com/Ws09WJNx

**Comment by Hekili** [comment]
There has to be more errors ahead of that.  What's the first error in the BugSack?  Can you grab a snapshot?

**Comment by Hekili** [comment]
Never mind, I have it sorted.

This will be resolved in v10.1.5-1.0.1.
