### ISSUE TITLE
cant change abilities 

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#271]
build: v8.3.0-04
level: 120 (120)
class: HUNTER
spec: beast_mastery

talents: animal_companion
    killer_cobra
    natural_mending
    one_with_the_pack
    posthaste
    stomp
    thrill_of_the_hunt

azerite: azerite_empowered = 3
    dance_of_death = 3
    haze_of_rage = 1
    impassive_visage = 1
    longstrider = 1
    overwhelming_power = 3
    primal_instincts = 1
    swirling_sands = 1
    vampiric_speed = 1

essences: [worldvein_resonance] = 4, conflict_and_strife = 2, essence_of_the_focusing_iris = 3

sets/legendaries/artifacts: none

gear: amalgamated_abomination_spaulders = 1
    arcglass_bindings = 1
    ashjrakamas_shroud_of_resolve = 1
    ashvanes_razor_coral = 1
    bilewing_helmet = 1
    chain_of_consummate_power = 1
    eldritch_cragscale_boots = 1
    gauntlets_of_eternal_service = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    last_vestige_of_neltharion = 1
    lurking_schemers_band = 1
    murky_cerulean_signet = 1
    nefarious_tormentors_leggings = 1
    whispering_eldritch_bow = 1

corruptions: echoing_void = 2
    whispered_truths = 1

itemIDs: 157953, 158075, 158317, 158318, 159377, 159380, 159385, 169223, 169311, 170440, 172193, 173485, 174044, 174147, 175008

settings: aoe = 3
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 20
    nameplateRange = 8
    nameplates = false
    package = Beast Mastery
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = true
    barbed_shot_grace_period = 0.5

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

Only one ability i see after update:
https://i.imgur.com/il2547L.png

**Comment by Hekili** [comment]
For a temporary workaround, /reloadui and it should be fine.

**Comment by Hekili** [comment]
This should be fixed in -04-04.
