### ISSUE TITLE
Protection Paladin not recommending Hammer of Wrath

### ISSUE THREAD

**Issue by tharpy35** [Hekili/hekili#2710]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Protection Paladin, the addon is not recommending Hammer of Wrath during Sentinel. Hammer of Wrath extends Sentinel by .5 seconds, does 10% increased damage, and generates 1 Holy Power when choosing the talent Zealot's Paragon.

### How to Reproduce

1. Enter the game as  Protection Paladin.
2. Choose Zealot's Paragon
3. Use Sentinel
4. Rotation as normal, it will not recommend Hammer of Wrath

### Snapshot (Link)

https://pastebin.com/fKTR3eMu

### Contact Information

Discord: Metzu#9013

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
