### ISSUE TITLE
[REC] Holy Paladin: Missing Abilities & Incorrect Recs

### ISSUE THREAD

**Issue by alphablueofficial** [Hekili/hekili#2711]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The following abilities for Holy Paladin are missing from the addon:

Action List: default
Avenging Crusader
Lights Hammer
Holy Prism
Holy Shock

Action List: spenders
Light of Dawn

_____

As a result of the above missing abilities, the rotation recommendations are not working correctly.

Example: The only ability recommended is Avenging Wrath (showing Avenging Crusader), despite having no Holy Power (Avenging Crusader requires 5 Holy Power) - even when Holy Power is generated and Avenging Crusader is used, the addon still only recommends Avenging Crusader.

### How to Reproduce

1. Enter game as a Holy Paladin
2. Take the Light's Hammer, Avenging Crusader talents
3. Target an attackable entity
4. See recommendations

### Snapshot (Link)

https://pastebin.com/49UdHzJQ

### Contact Information

alphablue

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
