### ISSUE TITLE
Enhancement: Ele blast being recommended while on Cooldown PWAVE TALENT SPEC

### ISSUE THREAD

**Issue by Twizzerious** [Hekili/hekili#2712]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While in PWAVE spec, eleblast is being recommended when BOTH charges are on cooldown and have 5+ maelstrom

### How to Reproduce

Use both charges of Ele  blast
Get 5+ maelstrom while both charges are on cooldown
Hekili recommends ele blast but cant cast

### Snapshot (Link)

https://pastebin.com/KkMTbsuG

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fWittvS2y2MQb2WMBMf1wd

### Contact Information

.twizz

**Comment by Hekili** [comment]
It's because the talent ID for Elemental Blast is wrong in the module.  It's actually recommending Lava Burst, but yours is replaced by Elemental Blast so that's what it shows.  Will fix.

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
