### ISSUE TITLE
Wings and Hammer of Wrath not populating correctly [RET]

### ISSUE THREAD

**Issue by PopsPaladin** [Hekili/hekili#2713]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In retribution spec the Cooldown of Wings is not show at all and the spell queueing is not prioritizing Hammer of Wrath correctly all the time. It sits with two charges for an entire set of wings.

### How to Reproduce

Literally log in a turn on the rotation helper. Select show cooldowns and the issue is present at start.

### Snapshot (Link)

https://pastebin.com/K1ZNBmFM

**Comment by PopsPaladin** [comment]
Reverting to 10.1.0 Does not solve the issue either.

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
