### ISSUE TITLE
Ret Paladin Avenging Wrath and Execution not showing in rotation and recommendations seem off

### ISSUE THREAD

**Issue by Xilone016** [Hekili/hekili#2714]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The add-on is not recommending avenging wrath or execution sentence. Once I manually click avenging wrath then execution sentence is recommended. If I do not click avenging wrath or execution sentence neither will show up in the recommended rotation at any point. Other ability recommendations also appear to be wrong. Like 5 templar strikers in a row when I have other generators available. I have cooldowns checked both minor and major cds. 

### How to Reproduce

1. enter game as ret paladin 
2. ensure cooldowns are selected
3. enter combat with out manually clicking wrath or execution
4. None will show in recommendations.

### Snapshot (Link)

https://pastebin.com/YzYGEuD9

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
