### ISSUE TITLE
[Rec] WW Monk not recommending Invoke Xuen. Only recommending other cooldowns when Xuen is disabled

### ISSUE THREAD

**Issue by BeemMN** [Hekili/hekili#2715]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not recommending Invoke Xuen and will only recommend other cooldowns when Invoke Xuen is disabled. I've tried a bunch of other ways to maybe get it to show up like removing it from cooldown toggles and setting other required toggles for it but nothing seems to work

### How to Reproduce

Set spec as windwalker monk
Make sure you have Invoke Xuen talented
Have cooldowns enabled
Go to a dummy
Check and see if Invoke Xuen is recommended
If not, go to abilities and go to Invoke Xuen and disable it
Check and see if other cooldowns are recommended now that its disabled

### Player Information (Link)

https://pastebin.com/w8uVGau1

### Error Messages (Link)

No error messages

### Contact Information

Beam_mn on discord

**Comment by Hekili** [comment]
This will be resolved in v10.1.5-1.0.1.
