### ISSUE TITLE
Add a distance check for Sundering and Crash Lightning.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#2717]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Please add a distance check for these two abilities, sometimes there are moments in battle when you don't notice that you are far away from the target, and you press intuitively the recommendation that shows you Hekili and it turns out that Sundering and Crash Lightning we press without targets. It's like not quite critical, but I would like to addon such a small thing could provide, would be a very nice bonus for the recommendation that if you see red you do not click as soon as the ability can hit then click it. Thank you.

### How to Reproduce

Play on Enchantment shaman.

### Snapshot (Link)

*

### Raidbots Sim Report (Link)

*

**Comment by Hekili** [comment]
There's a pull request for this already.  I'm still debating including it.

> sometimes there are moments in battle when you don't notice that you are far away from the target, and you press intuitively the recommendation that shows you Hekili and it turns out that Sundering and Crash Lightning we press without targets.

You're responsible for knowing where you are, are facing, etc.  Telling you that it's time to Sunder or use Crash Lightning is also telling you to get in range so you can do it.
