### ISSUE TITLE
[BUG] Augmentation evoker keeps suggesting to use Upheaval even when the skill is on CD

### ISSUE THREAD

**Issue by Greedozx** [Hekili/hekili#2718]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

trying the new script for augmentation, it seems to work find except that it keeps recommending me to use Upheavel even when the skill is on cooldown.

### How to Reproduce

just use the addon with Augmentation spec and you will see how the skill keeps appearing even when on CD

### Snapshot (Link)

https://pastebin.com/2YYDisxZ

**Comment by creed-us** [comment]
Adding my snapshots... Time Skip never appears (unsure if intended) and Upheaval stays in my spell queue.
Primary: https://pastebin.com/qmqe0wxt
AOE: https://pastebin.com/bAupBj51

**Comment by ctroller** [comment]
upheaval can be fixed by changing the spell id in EvokerAugmentation.lua (Line~796) to 408092.

Time Skip is not in the priority list at all, you'd have to add that yourself for the moment.

**Comment by Hekili** [comment]
> upheaval can be fixed by changing the spell id in EvokerAugmentation.lua (Line~796) to 408092.

Without Font of Magic, the current ID is correct and with Font of Magic, it changes to 408092.  I'm testing a fix for this already.

> Time Skip is not in the priority list at all, you'd have to add that yourself for the moment.

It's actually not referenced in the Icy-Veins guide, so I've added it.  There will also be an option to allow Time Skip without Breath of Eons on CD.

**Comment by Hekili** [comment]
This will be addressed in 1.0.2.
