### ISSUE TITLE
Demonbolt not showing up at lower levels.

### ISSUE THREAD

**Issue by Eribun** [Hekili/hekili#2720]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Demonbolt isn't showing up in the rotation as a warlock between 30-50.  Not sure if this is an issue, here's the snapshot as requested.
[snapbolt1.txt](https://github.com/Hekili/hekili/files/12028886/snapbolt1.txt)
[snapbolt1.txt](https://github.com/Hekili/hekili/files/12028887/snapbolt1.txt)

### How to Reproduce

Gain charges of demonic core, demon bolt is not displayed in rotation.

### Snapshot (Link)

https://pastebin.com/yubC6sXQ

**Comment by Hekili** [comment]
Thanks again for submitting.  I'll adjust the priority so those Demonbolts get used when Tyrant isn't talented.  :)
