### ISSUE TITLE
Freeze Not being recommended when available to AoE shatter Glacial Spike; Also when glacial spike is being casted (after a flurry) 2 IL's are recommended to follow.

### ISSUE THREAD

**Issue by vladimars** [Hekili/hekili#2722]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Freeze should be recommended to aoe shatter Glacial spike when mobs are freezable, as its off gcd and comes from the pet. The addon instead recommends Ice Nova (or Frost Nova), and if you use freeze still thinks you should Ice Nova to aoe shatter.

Glacial spike, casted after a flurry, is not being considered by the addon as something that will eat winters chill stacks, so it recommends two ice lances, or 1 ice lance and 1 ray of frost after the spike, even though the final one will not have winter's chill (fairly big deal with RoF, less so with IL) 

### How to Reproduce

Have cone of cold on cd, during icy veins use a Glacial spike, on aoe dummies, with freeze and Ice Nova/Frost Nova available.

take ray of frost.
Single target cast flurry, glacial spike. the addon will recommend 2 Ice lances, or 1 ice lance and 1 ray of frost, during the cast time of the glacial spike.

### Snapshot (Link)

https://pastebin.com/psbtPee9 (freeze)  https://pastebin.com/cnxzP9L8 (Glacial spike)

**Comment by Hekili** [comment]
I'm testing a fix now.

**Comment by MrBackward** [comment]
Hi, I would also like to add that it's hard (without double lust and IV) to fit in a comet storm followed by glacial spike then RoF and ice lance without loosing a winters chill stack, should it be recommending GS into flurry rather then FB into flurry?
might be automatically fixed by changing the logic that glacial spike takes a stack of Winters chill though

**Comment by Hekili** [comment]
I would recommend simming your character and looking at the sim result.  If it does things in a different order than the addon, you can highlight that for me to investigate by including a snapshot and a link to the sim result.

You can see the "Sample Ability Log" if you use Raidbots to do a Quick Sim.  Or you can view the Full HTML Report and open the Action Priority List section, then the Sample Sequence Table.

**Comment by Hekili** [comment]
> Glacial spike, casted after a flurry, is not being considered by the addon as something that will eat winters chill stacks

This is resolved.

> if you use freeze still thinks you should Ice Nova to aoe shatter.

This is resolved.

**Comment by vladimars** [comment]
> Hi, I would also like to add that it's hard (without double lust and IV) to fit in a comet storm followed by glacial spike then RoF and ice lance without loosing a winters chill stack, should it be recommending GS into flurry rather then FB into flurry? might be automatically fixed by changing the logic that glacial spike takes a stack of Winters chill though

You should not be double lusting. And it's normal that you would comet storm glacial spike ray of frost. You will lose the winters chill stack but Ray gives 2 for stacks.
