### ISSUE TITLE
[REC] Flamestrike not being suggested by the addon

### ISSUE THREAD

**Issue by karlinkonig** [Hekili/hekili#2723]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Flamestrike is not being suggested.

### How to Reproduce

1. Spec as a Fire Mage
2. Enter an AOE situation with 3+ targets.

### Snapshot (Link)

https://pastebin.com/gebS11xN

### Additional Information

Further investigating the snapshot showed this:

```
flamestrike ( standard_rotation - 1 ) - talent [ flamestrike ] missing
   Time spent on this action:  0.03msTimeData:Fire-standard_rotation-1:flamestrike:0.03:Ability Known, Enabled(0.03)
```

It seems it's looking for flamestrike as a talent while it's now baseline.

**Comment by Hekili** [comment]
Talent requirement will be removed in 1.0.3.
