### ISSUE TITLE
Breath Of Eon priority might be too low

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#2724]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Spamming Eruption is being recommended before BoE at pull with Cooldowns ON

### How to Reproduce

Playing augmentation, doing the basic 15s prepull in or out of group playing Time Skip talent
BEcBAAAAAAAAAAAAAAAAAAAAAQikWkkoFSSkkIJJNAAAAAQAAQSAIiECJJAAAAIRSLSSikAhE

### Snapshot (Link)

https://pastebin.com/Pbs1g0Gy

### Contact Information

Nibana#6011

**Comment by Hekili** [comment]
I'm working from the Icy Veins guide, since there are no sims. It's waiting for Ebon Might to have fewer that 4 secs remaining for its extension.

**Comment by Amortalist** [comment]
You can check the Evoker discord maybe, it's the most up to date in real time I believe : 
![image](https://github.com/Hekili/hekili/assets/47482996/c3cf3e4c-f306-4764-add5-c81337b0f5b2)

**Comment by Hekili** [comment]
Thanks.  I misinterpreted part of the Icy-Veins guide (basing its use on Ebon Might having less than 4 seconds left on *buff* instead of *cooldown*).

Once that's resolved, my opener looks like:
![image](https://github.com/Hekili/hekili/assets/9438134/14546e2e-a5c6-44ad-ab45-39ab23a3b390)

Will post in 1.0.3 a bit later.
