### ISSUE TITLE
Please add Mirror of fractured tomorrows trinket to rotations.

### ISSUE THREAD

**Issue by Oswalend** [Hekili/hekili#2726]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'd like for the new trinket to be added to rotation so that I can understand when they best time to use it is to get the most out of it.

**Comment by Hekili** [comment]
This item has been added; any priority that includes "Use Items" or "Trinket 1" / "Trinket 2" will be able to use it, consistent with other trinkets.
