### ISSUE TITLE
Frozen orb not being used in AoE frost rotation

### ISSUE THREAD

**Issue by linkandzelda91** [Hekili/hekili#2727]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

frost guides all recommend using frozen orb and blizzard together because of the synergy with the talents that make blizzard instant cast after frozen orb and the ticks of blizzard reducing the orb cd.

hekili never seems to recommend that I use frozen orb, I am not sure why. I am using a fresh install (downloaded the addon fresh when 10.1.5 dropped to try out frost mage).
I have the fixed dual display option selected, if it helps  (I think it's the only change I've made to the stock config), and am testing on v10.1.5-1.0.3

for fun i turned the display icons up to max on the slider to confirm: no frozen orb shown in the 10 spell rotation.

### How to Reproduce

1. frost mage at lvl 70
2. set mode to fixed dual display
3. use these talents:
BAEArSxcnei16P8xFL3rzzOyRKRIFNkkkkmAiERERSCAAQCJSkQSSikkkEJBAAAAAAAAAJCA
4. observe the recommended spells in the aoe roration.

### Snapshot (Link)

https://pastebin.com/X77HbaCU

**Comment by linkandzelda91** [comment]
oh, forgot the sim:
https://www.raidbots.com/simbot/report/tYdR2c5jRPeArP4v8hassc

patchwerk w/ 3 bosses to match the default aoe config in hekili

**Comment by Hekili** [comment]
Frozen Orb is assigned to a toggle that is turned off. 

See /hek > Toggles and/or /hek > Abilities > Frozen Orb.
