### ISSUE TITLE
Malefic Rapture requires specific dots

### ISSUE THREAD

**Issue by raflowers** [Hekili/hekili#2729]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It's recommending affliction warlock opens with 
Haunt
Malefic Rapture
Malefic Rapture
Malefic Rapture

Haunt does not count as a damage over time effect and does not allow Malefic Rapture to be cast.

### How to Reproduce

1. Install addon as affliction warlock
2. Attempt to follow the rotation reommended

### Snapshot (Link)

https://pastebin.com/2e6fW3WN

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pXwK3s72HaD4nFEop5CW4q

**Comment by Hekili** [comment]
Your sim doesn't have the same talents as you; I've made a couple of priority adjustments and fixed Vile Taint and Malefic Rapture.  This should suffice until there's an official simc update.
