### ISSUE TITLE
[BUG] Holy Paladin rotation freezing and throwing error messages

### ISSUE THREAD

**Issue by RenSai93** [Hekili/hekili#2730]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When following the holy paladin rotation hekili will eventually just freeze up and throw errors. During this time it becomes unresponsive preventing any snapshot or pause or toggle to be done. 

### How to Reproduce

1. Follow the recommendations hitting a target dummy.
2. Wait for the addon to start to recommend things on cd and just be frozen in time. 
3. Look at BugSack to see errors thrown.  

### Player Information (Link)

https://pastebin.com/baQWkacG

### Error Messages (Link)

https://pastebin.com/pikeMjDt

### Additional Information

The snapshot included is either during or right after the freeze happened. I am not 100% sure when it was taken since notifications didnt happen correctly during the addon freezing up.

**Comment by knifebunny** [comment]
I can confirm this is happening to me also.  Originally I thought it was tied to avenging crusader cooldown causing the spell suggestions to hang but now I am not sure

I cant narrow it down to a specific talent either

**Comment by Hekili** [comment]
Thanks, I have a fix ready for 1.0.5 today.
