### ISSUE TITLE
[REC] Frost mage no glacial spike on 2nd winter's chill and 2nd BL usage

### ISSUE THREAD

**Issue by uNBEx** [Hekili/hekili#2731]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi, it looks like recommendations get lost for a bit on 2nd winter's chill stack (second spell after flurry). If i have 5 icicles and use the first winter's chill with something else (or gain 5 icicles right on the 2nd winter's chill stack) it won't recommend to use the glacial spike. It sometimes snaps back to recommending glacial spike, but only if you pause for a bit.

Second suggestion: It's more beneficial to use the 2nd BL (temporal warp) on the second icy veins use instead of chaining them. Right now it suggests to press second bloodlust right after the first one ends.

### How to Reproduce

1. Frostbolt
2. Flurry
3. Ice lance
4. Right here, if you have 5 icicles, glacial spike should be recommended. Instead it recommends to ice lance and the glacial spike gets delayed to the next flurry combo.

### Snapshot (Link)

https://pastebin.com/h6caiULF

**Comment by uNBEx** [comment]
Here's a sim link: https://www.raidbots.com/simbot/report/mzZqGGRUgQGwWGaTo2VnRJ
At 0:27:191 there's a situation like this. It also shows 2nd BL used on 2nd Icy Veins

**Comment by Hekili** [comment]
It's interesting, your stacks of Icicles were detected at first but then show as zero in Glacial Spike's conditions.  I'm investigating it.

**Comment by Hekili** [comment]
I haven't really done anything to fix this, but I'd like to see another snapshot after updating to 1.0.6.  Thank you!

**Comment by uNBEx** [comment]
Here's the situation i talked about first - https://pastebin.com/AeT5hPTN

And here's another situation, where before pressing ice lance on the first winter's chill stack there are four icicles, meaning that this ice lance will generate 5th icicle. There should already be a suggestion to press glacial spike next. So the correct suggestion should be ice lance -> glacial spike, not two ice lances. Link: https://pastebin.com/BMktaPrC

**Comment by Hekili** [comment]
Alright, I have some fixes in the next release that should cover these bases.  If there's any change at all in Icicles stacks, recommendations are going to force an immediate reset instead of continuing to generate recommendations.

There are a few logic fixes in the models for Ice Lance and such to ensure buffs are consumed/gained correctly and forecasted accurately.  Let me know if you notice an improvement.

**Comment by uNBEx** [comment]
It looks like it's much better - i still get a feeling it spasms to frostbolt for a short time, but i can't really react fast enough to catch a snapshot.
