### ISSUE TITLE
[REC] Augmentation - Not recommending Fire Breath or Upheaval before Breath of Eons

### ISSUE THREAD

**Issue by Jacii1121** [Hekili/hekili#2732]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Based on the guides on wow-head and icy-veins, I'm expecting empower spells to be used before Breath of Eons. 

### How to Reproduce

Using talent build - BEcBsJu/D+01p9npZvkV+nWIkTikWkkoESSKJikk0AAAAAABAAJBCISISSCAAAASk0ikISCESA

Begin prepull rotation, Prescience, Ebon Might, Blistering Scales etc.  
Cast Living Flame to get into combat
Breath of Eons is recommended.

### Snapshot (Link)

https://pastebin.com/AgGRT9yU

### Additional Information

Thank you for your work.

### Contact Information

jacii_

**Comment by Hekili** [comment]
That's not what I'm seeing in those guides.  Icy-Veins:
![image](https://github.com/Hekili/hekili/assets/9438134/08199a1e-ffe7-42e7-8503-61cc0dd4b9bd)

**Comment by Jacii1121** [comment]
My apologies if that is indeed the case. But this is what I see.

![Uploading Screenshot_20230714-091214.png…]()

**Comment by Jacii1121** [comment]
Updated to alpha. Still seeing similar behavior.

https://pastebin.com/wZ9m3D2y

**Comment by Jacii1121** [comment]
Nix that. All good now.

**Comment by labudjipjev** [comment]
My icy veins prio lookins different to yours.

![image](https://i.imgur.com/K3WhKEt.png)

**Comment by Hekili** [comment]
The priority changes based on Time Skip vs. Interwoven Threads.  This is addressed in 1.0.6.

**Comment by chokopop** [comment]
For me not show on spellflash. But on window is normal. 
![WoWScrnShot_080423_111411](https://github.com/Hekili/hekili/assets/141422654/43a38182-fd3a-4457-9742-cc1b3d668016)
