### ISSUE TITLE
fire mage suggesting Timewarp after already being used

### ISSUE THREAD

**Issue by Switchuser1** [Hekili/hekili#2733]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

when using timewarp the addon then recommends reusing it whilst the timewarp buff is still active 
![Screenshot 2023-07-14 182222](https://github.com/Hekili/hekili/assets/73027507/1b12c080-f89a-42ff-875c-b23a204ced6e)

### How to Reproduce

start the rotation as the addon recommends and use timewarp after combustion - the addon will then still suggest to use timewarp 

### Snapshot (Link)

https://pastebin.com/R4kVgS9s

### Contact Information

camm2195

**Comment by Hekili** [comment]
In 1.0.6, your second use of Time Warp (with Temporal Anomaly?) will wait for your first Time Warp/Bloodlust to expire first.
