### ISSUE TITLE
[REC] Brewmaster Monk - Purifying Brew recommended on cooldown despite stagger tick % HP settings.

### ISSUE THREAD

**Issue by PatrickOkonek** [Hekili/hekili#2734]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since 10.1.5, the addon recommends Purifying Brew on cooldown, so long as there is any damage staggered at all. From my limited understanding of the APL and the addon's implementation for it, as well as from my brief experience playing BrM with Hekili in the prior patch; I believe that the defensive recommendation for PB is not being adjudicated by the 3 settings correctly (Maximize Improved Invoke Niuzao; Stagger Tick % Current Health; Stagger Tick % Maximum Health), and is instead simply being recommended the moment it comes off cooldown.

### How to Reproduce

1. Enter combat with target.
2. Receive damage and stagger.
3. Purifying Brew is recommended regardless of stagger level.
4. Cast Purifying Brew even if you don't need to remove stagger.
5. 2nd charge of PB is immediately recommended again.
6. Cast PB regardless of stagger level.
7. PB will again be recommended the moment it comes up off of cooldown.

### Snapshot (Link)

https://pastebin.com/niUxEDWd

**Comment by Hekili** [comment]
Purifying Brew is not recommended in the snapshot.

**Comment by PatrickOkonek** [comment]
I am attempting to post another snapshot.
https://pastebin.com/0BQBzH9c

**Comment by Hekili** [comment]
Thanks.  The next release will address this.  (1.0.6)
