### ISSUE TITLE
Blistering scales and source of magic always being recommended.

### ISSUE THREAD

**Issue by kittykiller** [Hekili/hekili#2735]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

when in a dungeon blistering scales is being recommended off cooldown when put on other members in the group. Also, source of magic is being recommended even when it's on the healer.

### How to Reproduce

1. be augmentation evoker
2. join m+ dungeon
3. apply buffs to other players

### Snapshot (Link)

https://pastebin.com/rjeTygyD

### Additional Information

I have tried 1.0.6 alpha and it does the same thing.

**Comment by Scaver** [comment]
Same here.
It would be good if there were a query whether the healer already has source of magic or whether you are in a dungeon with a healer at all.

**Comment by Hekili** [comment]
I've made adjustments so that friendly auras will not be purged/forgotten so aggressively in 1.0.6.
