### ISSUE TITLE
[REC] Marksmanship Trueshot behaving unexpectedly during Experiments

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#2737]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Marksmanship hunter does not recommend trueshot on experiments on pull, I think it is linked to the calculated time-to-kill because the boss is broken into 3 parts with smaller HP, especially on heroic/normal. 

Even if you do not get a trueshot proc on pull, it will show up in the queue, but then disappear and force a wait-til-execute condition even if the boss is at near full HP. Evidence for this is that trueshot does finally get recommended later when the first boss gets low. I can also provide a VOD for the pull.

Not sure if this is indicative of a bigger problem or just a quirk of the specific fight.

### How to Reproduce

Pull Experiments on Marksmanship hunter with cooldowns enabled. 

### Snapshot (Link)

https://pastebin.com/a2QiWXQB

### Contact Information

syrif

**Comment by Hekili** [comment]
I'll make the Trueshot conditions visible in 1.0.6 to better diagnose this issue.  I'll need a new snapshot after the update.

**Comment by Hekili** [comment]
Nudging again -- a new snapshot using the latest alpha will provide more information about why Trueshot was not recommended.  It may or may not be based on fight length; the condition is fairly elaborate.

**Comment by syrifgit** [comment]
https://pastebin.com/a6pdnDAp

This is 8 seconds into the experiments pull
![image](https://github.com/Hekili/hekili/assets/139663837/38db3ef5-c6ca-4d41-affd-45ec0ca4412f)

**Comment by marekCs** [comment]
Thank you for taking the time to take care of MM Hunter 🙏. It seems to deserve better results.

**Comment by syrifgit** [comment]
Seems to be behaving much more appropriately on experiments now.

https://pastebin.com/F3F69xsg
