### ISSUE TITLE
[BUG] Primary and AOE prio now showing Vengeance

### ISSUE THREAD

**Issue by enzytesham** [Hekili/hekili#2738]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

My shaman and pally are showing up fine but my vengeance following the the latest update is not showing up.

### How to Reproduce

1. Enter game as Vengeance
2. Enter combat or dungeon

### Player Information (Link)

https://pastebin.com/WvWiY6er

### Error Messages (Link)

no bugs

### Contact Information

discord: enzyte

**Comment by enzytesham** [comment]
For reference, Havoc does show up. It's only Vengeance.

**Comment by picklerick84** [comment]
I was just coming to make this bug report.  After this last update, there is no active priority package for vengeance, but if you activate it and set to vengeance, its the havoc priority package for both vengeance and havoc now.  There is no vengeance prio package, even if you go to action list for vengeance prio, it has blade dance, etc.  
![image_2023-07-16_022451019](https://github.com/Hekili/hekili/assets/66019145/76584289-0360-4666-8d59-926a41d28dfd)
![image_2023-07-16_022530843](https://github.com/Hekili/hekili/assets/66019145/bbee5cda-38fa-4a27-8894-b9299c092ea8)

**Comment by enzytesham** [comment]
I’m happy I wasn’t crazy. Thanks for the amplifying info.

Best,
Enzyte

**Comment by Zhythron** [comment]
Here i thought i was going crazy lol Thanks for saving me time on making a ticket ;P

**Comment by enzytesham** [comment]
I did the work so y’all didn’t have to ;)

Btw hekili, thank you for all the work you do! I know the latest update was
a huge overhaul to vengeance and I was looking forward to seeing it in
action, and that’s how I noticed it.

Your work doesn’t go unappreciated!! Thanks!

Best,
Enzyte

**Comment by picklerick84** [comment]
I totally agree.  Its an amazing addon and I recommend it to alot of people.  Especially as someone who plays pretty much every class and some at a CE and high M+ level.  It allows me to make a rat spriest that I have no idea how to play and at least enjoy it, not doing healer dmg.  

Your work on this is very appreciated.  Let me know if theres any other info I can get you to help.

**Comment by Hekili** [comment]
> Primary and AOE prio now showing Vengeance

Well, that sounds good.

> I was just coming to make this bug report. After this last update, there is no active priority package for vengeance, but if you activate it and set to vengeance, its the havoc priority package for both vengeance and havoc now.

Well, that sounds bad.

**Comment by Hekili** [comment]
Fixed in next release.
