### ISSUE TITLE
Addon still wants pool, if energy % for envenom is 0. Detection disabled still doing same

### ISSUE THREAD

**Issue by noiseuu** [Hekili/hekili#274]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**https://pastebin.com/DxNgRhMA

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**https://pastebin.com/L064cKLD

**Comment by noiseuu** [comment]
I hope this is ok for u to understand

**Comment by noiseuu** [comment]
I saw at apl there is echoing void cheese, and after that i switched echoing void gear to different one and same problem continue?

**Comment by Hekili** [comment]
One issue per ticket.

**Comment by noiseuu** [comment]
I just said before apl echoing void, it worked great but not after that.

**Comment by Hekili** [comment]
I don't understand.

**Comment by noiseuu** [comment]
Okay, but i hope u understand what im saying.. It still pools even i have set 0 
![assa](https://user-images.githubusercontent.com/43645444/73994714-29c94b00-495f-11ea-9796-867df3f58b69.PNG)

**Comment by Hekili** [comment]
Sorry, will put this back in.

**Comment by Hekili** [comment]
Should be resolved.
