### ISSUE TITLE
Trinket not in rotation, Time-Thief's Gambit 

### ISSUE THREAD

**Issue by leewparn** [Hekili/hekili#2741]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I just got Time-Thief's Gambit from the new mega dungeon yesterday and can't get it to show up in rotation.

### How to Reproduce

It should be used like any other trinket on pull when all other CDs are getting used.

### Snapshot (Link)

https://pastebin.com/K2jcd73J

### Contact Information

Danonino#6346

**Comment by Hekili** [comment]
Resolved.
