### ISSUE TITLE
Adding an indication for Prescience to better track the buff.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#2742]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Perhaps you can immediately tell me that my idea is nonsense and I don't need it. But as practice shows, and the guides that describe for Prescience we want to use this buff on the best players or top classes that are with us in the raid. (I'm not talking about M+ because it doesn't make sense there) If we use Prescience on the best players and then buff them with Ebon Might we will get a significant boost for ourselves and two allies in the raid. I wanted to propose to make an indication that would show simply by numbers 1 or 2 buff Prescience. So that the player on Augmentation could immediately quickly react to who ends the effect of the buff Prescience. This will greatly simplify the tracking of the Prescience buff in combat. Because it would just be enough to look at the number 1 or 2 that now on 2 baf Prescience player ends Prescience and we should have updated it, and then in the rotation would appear Prescience with the number 1 because I would see that ends on 1 baf person. It would be very convenient just because of such a simple thing as indication to understand what is the current buff ends on the players. For you I think it is not difficult to just add numbers to the Prescience icon and for Augmentation players a huge boost in the duration of the buff on the right players. Thanks in advance.

### How to Reproduce

Play Augmentation

### Snapshot (Link)

*

**Comment by Hekili** [comment]
This should've been a feature request; it's not a problem with current recommendations.  In any case, I don't plan on telling you who to hit with Prescience or even Blistering Scales.  What happens in a raid and your preferred target is dead or just out of range?

The addon will tell you that it's time to use the ability again; you'll need to decide who gets the buff based on your group and fight choreography.

**Comment by geraint425** [comment]
It's sad, of course. I just wanted to get my point across to you to just add an indication like with the dragon charges. It would be enough for me to just see 1 or 2 buffs I'm about to press. So to speak just to visually watch. Maybe you know how you can do it yourself in your addon ?

**Comment by trabbit11** [comment]
my addon just randomly stopped recommending prescience alltogether. Not sure how? a few hours ago it was telling me to press it on cd pretty much notp it just never tells me its up. I mainly use the addon for cd tracking not necessarily the rotation, so this is ruining my intended use
