### ISSUE TITLE
[REC] Brewmaster monk is missing Spinning Crane Kick when the talent Press The Advantage is active

### ISSUE THREAD

**Issue by olidennis** [Hekili/hekili#2743]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili is not suggesting Spinning Crane Kick at all when the Press The Advantage talent is active. Apparently, the line about sck has been entirely removed from the rotation.

In the rotation_boc case these two lines are present
```
actions.rotation_boc+=/tiger_palm,if=active_enemies=1&!talent.blackout_combo.enabled
actions.rotation_boc+=/spinning_crane_kick,if=active_enemies>1
```

In the rotation_pta case, both have been removed. PtA makes tiger palm passive, so it makes sense that it is removed, but the line about spinning crane kick should be put back in the rotation.

### How to Reproduce

Enable the Press the Advantage talent on Brewmaster monk, then try to do some AoE.

### Snapshot (Link)

http://nopaste.net/eyoUQhjour

**Comment by Hekili** [comment]
This appears to be consistent with the sim priority, so you may want to submit a ticket to SimulationCraft as well.

I'll put SCK into the PtA priority, since it is a significant DPS increase in a modified HecticAddCleave sim:

![image](https://github.com/Hekili/hekili/assets/9438134/32ab7e33-910c-4b2d-9bd2-becca3854d1d)

**Comment by olidennis** [comment]
I opened an issue on simulationcraft (see here https://github.com/simulationcraft/simc/issues/7950).
Note their answer:
```
This is a known issue, but adding SCK to the PtA rotation is not as simple as one might think. Changes will come eventually on this front, though.
```

Anyways, as a temporary fix, having SCK somewhere in the rotation seems to be better than nothing, DPS wise.

**Comment by Hekili** [comment]
Yeah, I didn't add it because it seemed simple, it was just immediately more performant.  If there's further optimization revealed with their sims later, I'll adopt their changes.
