### ISSUE TITLE
Defense/Potion Options

### ISSUE THREAD

**Issue by Technoman84** [Hekili/hekili#2745]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I'm sure I'm doing something wrong and I feel like a dummy having to ask. I have enabled the defense options both on toggle and in the menu of Hekil itself, for some reason it's still not flashing or showing defense options. Please tell me what I'm doing wrong?

### How to Reproduce

1. Enter game as any character
2. Enable defense options in both areas. 
3. Does not work via spellflash nor does it show the picture of the defense, it just tells me defense is not enabled.

### Player Information (Link)

build: v10.1.5-1.0.9 level: 61 (61) class: SHAMAN spec: enhancement  talents: BcQAu3fz4tp2ZikXIAdNeR+oLIJJpEJISSIAUSkAAAAAAAAAAAAAEhIkolioQSTSKAKBJAC     ancestral_defense = 1/1     ancestral_guidance = 1/1     ashen_catalyst = 1/1     astral_shift = 1/1     brimming_with_life = 1/1     capacitor_totem = 1/1     chain_lightning = 1/1     crash_lightning = 1/1     crashing_storms = 1/1     earth_elemental = 1/1     elemental_spirits = 1/1     elemental_weapons = 2/2     feral_spirit = 1/1     fire_and_ice = 1/1     flurry = 1/1     frost_shock = 1/1     guardians_cudgel = 1/1     hailstorm = 1/1     hot_hand = 2/2     ice_strike = 1/1     improved_maelstrom_weapon = 2/2     lashing_flames = 1/1     lava_burst = 1/1     lava_lash = 1/1     maelstrom_weapon = 1/1     mana_spring = 1/1     molten_assault = 2/2     natures_fury = 2/2     natures_guardian = 2/2     overflowing_maelstrom = 1/1     purge = 1/1     raging_maelstrom = 1/1     spirit_walk = 1/1     spirit_wolf = 1/1     stormstrike = 1/1     sundering = 1/1     swirling_maelstrom = 1/1     thundershock = 1/1     thunderstorm = 1/1     totemic_projection = 1/1     wind_rush_totem = 1/1     wind_shear = 1/1     windfury_totem = 1/1     windfury_weapon = 1/1     winds_of_alakir = 2/2     witch_doctors_ancestry = 2/2  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: none  gear: bindings_of_sabotage = 1     cleated_ice_boots = 1     coldwrap_cloak = 1     dingy_golden_band = 1     expedition_mercenarys_hauberk = 1     expedition_mercenarys_leggings = 1     harlans_loaded_dice = 1     icefall_mail_girdle = 1     icefall_mail_helm = 1     interwoven_scale_bracers = 1     lacquered_carving = 1     nerubian_princes_pendant = 1     ring_of_the_shadow_deeps = 1     spaulders_of_lost_secrets = 1     talons_of_totemic_might = 1  legendaries: none  itemIDs: 112350, 112364, 113683, 113686, 155881, 173559, 173666, 173668, 194352, 194402, 27761, 35600, 37170, 42763, 44372  settings: aoe = 2     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 20     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Enhancement     petbased = false     potion = potion_of_spectral_agility     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     check_crash_lightning_range = true     check_sundering_range = true     filler_shock = true     hostile_dispel = false     pad_lava_lash = true     pad_windstrike = true     project_windfury = 0     purge_icd = 12     pwave_targets = 0  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = automatic      potions = true   keybinds:      ancestral_guidance =     astral_shift       = 7   [01]     flame_shock        = 4   [01]     ghost_wolf         = 1   [01]     ice_strike         = 5   [01]     lightning_shield   = 8   [01]     thunderstorm       = 6   [01]     wind_shear         = 2   [01]     windfury_totem     = 3   [01]  warnings: none

### Error Messages (Link)

build: v10.1.5-1.0.9 level: 61 (61) class: SHAMAN spec: enhancement  talents: BcQAu3fz4tp2ZikXIAdNeR+oLIJJpEJISSIAUSkAAAAAAAAAAAAAEhIkolioQSTSKAKBJAC     ancestral_defense = 1/1     ancestral_guidance = 1/1     ashen_catalyst = 1/1     astral_shift = 1/1     brimming_with_life = 1/1     capacitor_totem = 1/1     chain_lightning = 1/1     crash_lightning = 1/1     crashing_storms = 1/1     earth_elemental = 1/1     elemental_spirits = 1/1     elemental_weapons = 2/2     feral_spirit = 1/1     fire_and_ice = 1/1     flurry = 1/1     frost_shock = 1/1     guardians_cudgel = 1/1     hailstorm = 1/1     hot_hand = 2/2     ice_strike = 1/1     improved_maelstrom_weapon = 2/2     lashing_flames = 1/1     lava_burst = 1/1     lava_lash = 1/1     maelstrom_weapon = 1/1     mana_spring = 1/1     molten_assault = 2/2     natures_fury = 2/2     natures_guardian = 2/2     overflowing_maelstrom = 1/1     purge = 1/1     raging_maelstrom = 1/1     spirit_walk = 1/1     spirit_wolf = 1/1     stormstrike = 1/1     sundering = 1/1     swirling_maelstrom = 1/1     thundershock = 1/1     thunderstorm = 1/1     totemic_projection = 1/1     wind_rush_totem = 1/1     wind_shear = 1/1     windfury_totem = 1/1     windfury_weapon = 1/1     winds_of_alakir = 2/2     witch_doctors_ancestry = 2/2  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: none  gear: bindings_of_sabotage = 1     cleated_ice_boots = 1     coldwrap_cloak = 1     dingy_golden_band = 1     expedition_mercenarys_hauberk = 1     expedition_mercenarys_leggings = 1     harlans_loaded_dice = 1     icefall_mail_girdle = 1     icefall_mail_helm = 1     interwoven_scale_bracers = 1     lacquered_carving = 1     nerubian_princes_pendant = 1     ring_of_the_shadow_deeps = 1     spaulders_of_lost_secrets = 1     talons_of_totemic_might = 1  legendaries: none  itemIDs: 112350, 112364, 113683, 113686, 155881, 173559, 173666, 173668, 194352, 194402, 27761, 35600, 37170, 42763, 44372  settings: aoe = 2     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 20     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Enhancement     petbased = false     potion = potion_of_spectral_agility     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     check_crash_lightning_range = true     check_sundering_range = true     filler_shock = true     hostile_dispel = false     pad_lava_lash = true     pad_windstrike = true     project_windfury = 0     purge_icd = 12     pwave_targets = 0  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = automatic      potions = true   keybinds:      ancestral_guidance =     astral_shift       = 7   [01]     flame_shock        = 4   [01]     ghost_wolf         = 1   [01]     ice_strike         = 5   [01]     lightning_shield   = 8   [01]     thunderstorm       = 6   [01]     wind_shear         = 2   [01]     windfury_totem     = 3   [01]  warnings: none

### Additional Information

Information included above

### Contact Information

github.ydx8d@auraprivatemail.com

**Comment by Hekili** [comment]
Enhancement Shaman isn't a tank with defensive abilities loaded by default.  You can consult the FAQ in the Wiki about adding defensive abilities to a custom priority if you want to see them.
