### ISSUE TITLE
[REC] Fists of Fury during Serenity (?)

### ISSUE THREAD

**Issue by 78jeffrey** [Hekili/hekili#2747]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

not recomend Fist of Fury during serinty  

### How to Reproduce

changing profile

# Serenity Priority
actions.serenity+=/fists_of_fury,if=buff.serenity.remains<1
actions.serenity+=/blackout_kick,cycle_targets=1,if=combo_strike&!spinning_crane_kick.max&active_enemies>4&talent.shdaowboxing_treads
actions.serenity+=/blackout_kick,cycle_targets=1,if=combo_strike&buff.teachings_of_the_monastery.stack=3&buff.teachings_of_the_monastery.remains<1
actions.serenity+=/rising_sun_kick,cycle_targets=1,if=active_enemies=4&buff.pressure_point.up&!talent.bonedust_brew
actions.serenity+=/rising_sun_kick,cycle_targets=1,if=active_enemies=1
actions.serenity+=/rising_sun_kick,cycle_targets=1,if=active_enemies<=3&buff.pressure_point.up
actions.serenity+=/rising_sun_kick,cycle_targets=1,if=buff.pressure_point.up&set_bonus.tier30_2pc
actions.serenity+=/rising_sun_kick,cycle_targets=1,if=set_bonus.tier30_2pc
actions.serenity+=/fists_of_fury,if=buff.invokers_delight.up&active_enemies<3&talent.jade_ignition
actions.serenity+=/fists_of_fury,if=buff.bloodlust.up
actions.serenity+=/fists_of_fury,if=buff.invokers_delight.up&active_enemies>4
**actions.serenity+=/fists_of_fury,if=active_enemies=2,interrupt_if=buff.serenity.up&(buff.invokers_delight.up&(active_enemies<3&talent.jade_ignition|active_enemies>4)|buff.bloodlust.up|active_enemies=2)**
/

change bold test to below  since fix the issue

actions.serenity+=/fists_of_fury,if=active_enemies=2
actions.serenity+=/fists_of_fury,interrupt_if=buff.serenity.up&(buff.invokers_delight.up&(active_enemies<3&talent.jade_ignition|active_enemies>4)|buff.bloodlust.up|active_enemies=2)

### Snapshot (Link)

https://pastebin.com/tJY3avxU

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/7fks3eVidtiXRv2AR1DpbZ

**Comment by simplejoecrypto** [comment]
Hekili recommends Fists of Fury during serenity only when there is > 1 enemy detected for me.

**Comment by Hekili** [comment]
The Windwalker priority has been massively overhauled in today's release; I'll need a new ticket/snapshot if this sort of issue persists.  Thanks!
