### ISSUE TITLE
[REC] Holy Paladin Blessing of Summer, Update Icon to Show Current Season

### ISSUE THREAD

**Issue by lolHakks** [Hekili/hekili#2748]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Holy Paladin, I would like to see the addon pull the correct icon for Blessing of Summer/Autumn/Winter/Spring into the Primary rotation queue. 

Currently whenever the ability is available to be cast, it correctly takes precedence over other abilities until cast, but always uses the icon for Blessing of Summer; making it difficult to choose the correct target for the spell (which is best used on different targets depending on which season will actually be cast). 

### How to Reproduce

1. Enter the game as a Holy Paladin
2. Take the Blessing of Summer talent
3. Cast Blessing of Summer as recommended by the add-on (the icon will be the icon for Blessing of Summer)
4. Wait for the buff to expire and Blessing of Summer to come off cooldown
5. The add-on now recommends casting Blessing of Summer (which is now Blessing of Autumn, it rotates with each cast); the icon will still be the icon for Blessing of Summer.

### Snapshot (Link)

https://pastebin.com/Z6yKSVrP

### Raidbots Sim Report (Link)

-

### Contact Information

hakks (Discord)

**Comment by Hekili** [comment]
Hey, could you provide the whole snapshot?  You have to press CTRL+A to select the whole text box and then CTRL+C to copy.  There should be hundreds (or thousands) of lines of text.

Thank you!

**Comment by syrifgit** [comment]
Here's one .. this had been annoying me too lol. 

In this snapshot, I currently have blessing of autumn up.

https://pastebin.com/qaHSF8KL

**Comment by lolHakks** [comment]
https://pastebin.com/QuuE6Qxv

**Comment by Hekili** [comment]
This will be resolved in today's release.
