### ISSUE TITLE
[REC] Frost Deathknight, recommending AMS while "Damage" is selected

### ISSUE THREAD

**Issue by Flowed123** [Hekili/hekili#2749]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On my Frost Deathknight the addon always recommends AMS even if i select "Damage" in the Core Options. Therefore the Requirments should be: incoming magic dmg. I am testing on training dummie and i got no incoming magic dmg, still the addon suggest me to cast AMS.
Under Abilities i got AMS in "Require Toggle" as Default(none).
I often use major cooldowns on and off toggle but AMS is recommended in both scenarios.
I added a Screenshot of the Core Option + Snapshot Pause screenshot while hovering over AMS. In addition to that i added the Snapshot as .txt. 
I do this the first time and i hope its correct i couldnt figure out how to stop the snapshot only how to start it.
Thank you for your awesome work!

![AMS problem](https://github.com/Hekili/hekili/assets/140424182/49d0d7a3-2cfe-4d79-b120-ba049c559775)
![AMS problem3](https://github.com/Hekili/hekili/assets/140424182/789350f6-f1c1-4196-91f0-33054ba3b10b)
[AMS problem4.txt](https://github.com/Hekili/hekili/files/12147458/AMS.problem4.txt)

### How to Reproduce

1. Frost Deathknight Raid Breath Build
2. set AMS core Option to "Damage"
3. see recommendations 

### Snapshot (Link)

https://pastebin.com/ywjPAzFd

**Comment by Hekili** [comment]
Is it possible that any of your effects/procs/trinkets are doing some (small) amount of magic damage to yourself?

Please go to `/hekili` > `Priorities` > `Frost DK` > `Action Lists` > `Action List: default` > `Entry: 3` and add this to the end of the existing conditions:  `& incoming_magic_3s > 0`.

The result should look like this:
![image](https://github.com/Hekili/hekili/assets/9438134/a7f4010c-78a8-4621-9e02-c69ffb82b88c)

Then get a new snapshot when AMS is recommended despite no apparent external magic damage and link it here.  If the problem is that Roused Shadowflame's damage to yourself is counting, then I can make sure not to count self-damage going forward.

**Comment by Flowed123** [comment]
Hey thank you for your fast help. I tested it now:

1. added the "& incoming_magic_3s > 0" line. No change here. 
2. switched out Roused Shadowflame embellishment, and its **solved**!
3. adding or deleting the "& incoming_magic_3s > 0" line makes no change for me now.

It's definitely the self dmg from the embellishment. I cant find a case where Hekili still recommends Ams when i switch out the shadowflame embellishment, so i got no new snapshot. Do u need anything else?

**Comment by Hekili** [comment]
Yeah, getting a snapshot of incoming magic damage from your own embellishment was what I was looking for, but I went ahead and removed self-damage from incoming damage measures.  It'll be in the next release.

**Comment by Flowed123** [comment]
Brilliant, I appreciate your work, thank you very much!
