### ISSUE TITLE
Little "Treasuremap-Icon" / Outlaw-Rogue

### ISSUE THREAD

**Issue by lasseblooten** [Hekili/hekili#275]
Hey, I play Outlaw-Rogue and with the new update I get little "Treasuremap"-Icons in my prioritylist.
They change random from one position to another (from 4th to first for example) after I press an ability and most of the times it has to be a Sinisterstrike.
Does anybody else have these issues?

![Treasuremap-icon](https://user-images.githubusercontent.com/60800368/74074105-0eb51480-4a0d-11ea-8ab7-eeee08eb4602.jpg)

**Comment by Hekili** [comment]
You have Echoing Void. If you have nothing else to do at that moment, hitting Detection gives you a chance to proc EV.

**Comment by lasseblooten** [comment]
Ok, I feel dumb now. 
Didn't use that spell in the last 3 years, totally forgot it.
Thank you. Can't believe how bad this patch (WoW) is that an almost useless spell brings me more dps.

Thank you for your addon, your work and your fast response!!!
You are great!
