### ISSUE TITLE
Keybind text wrong on most characters except action bar 1

### ISSUE THREAD

**Issue by Denixerianer** [Hekili/hekili#2750]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As the title suggests i tried 3 characters and only on one of those three characters the keybinds are showing what they are supposed to. Only action bar 2 and 3 are affected action bar 1 keybinds get shown correctly. I know there is a way to manually set keybinds but that is incredibly tedious especially when you want to move an ability somewhere else. I use the default action bars.

### How to Reproduce

log onto your character and it no workey

### Player Information (Link)

https://pastebin.com/fr9rGygE

### Error Messages (Link)

there are no error messages

**Comment by Hekili** [comment]
```
    avenging_wrath         = V   [01]
    blade_of_justice       = 1   [01]
    blessing_of_freedom    = F   [01]
    blessing_of_protection = CC  [05]
    consecration           = CQ  [05]
    crusader_strike        = 2   [01]
    divine_protection      = C   [01], C   [02]
    divine_shield          = T   [01]
    divine_steed           = X   [01]
    divine_storm           = Q   [02], SQ  [06]
    flash_of_light         = E   [01]
    hammer_of_justice      = 4   [01]
    hammer_of_wrath        = 1   [02], S3  [06]
    intercession           = V   [02], ST  [06]
    judgment               = 3   [01]
    lay_on_hands           = CE  [05]
    rebuke                 = 4   [02], S4  [06]
    redemption             = T   [02], CT  [05]
    shield_of_vengeance    = SC  [06]
    templars_verdict       = 2   [02], S2  [06]
    turn_evil              = CX  [05]
    wake_of_ashes          = Q   [01]
    will_to_survive        = CV  [05]
    word_of_glory          = E   [02], SE  [06]
```

These are the keybinds detected based on your action bars.  For example, WoG is E on action bar 2 or shift-E on action bar 6.  The addon will prefer the lowest numbered action bar.  Divine Storm is Q on action bar 2 or shift-Q on action bar 6.

You may want to remove spells from the unused action bar if it's in two places.

If none of these line up (i.e., you're using a non-Elv, non-Bartender, non-Dominos, non-ConsolePort action bar mod), you can always set your keybindings on each ability manually in /hekili > Abilities.
