### ISSUE TITLE
[REC] MM using steady shot too much for steady focus.

### ISSUE THREAD

**Issue by Williamn88** [Hekili/hekili#2751]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi Hekili
It seems like its not counting steady shot properly for steady focus or the buff itself. Sometimes it throws out 3 in row.
I remember you did some changes to it a while a ago, and I think it started there. Just never got around to report it.

I managed to capture it here where you can see steady focus is up (buff tracker under the 100 focus), focus is at 100 and it recommends SS.

Its not every time. Just once in a while in the rotation it seems to slip up.

![image](https://github.com/Hekili/hekili/assets/42271641/601c4e9d-977e-4755-982a-7c0019e9ae28)

I hovered over the icon and its 
![image](https://github.com/Hekili/hekili/assets/42271641/b9654733-fbc3-4399-b0d8-a8207e52933f)

### How to Reproduce

Play MM
At some point in the rotation it wants to refresh steady focus but fails to count one of them for some reason so instead it does 3 in a row.
See snapshot and screenshot

### Snapshot (Link)

https://pastebin.com/keNAKWDC

**Comment by Hekili** [comment]
I'd need you to provide a snapshot using the default priority, not something you've imported.

In the screenshot and snapshot, you do not have Steady Focus applied.  Are you saying that this snapshot is taken when you've just made the second shot but Steady Focus has not been applied yet?

**Comment by Williamn88** [comment]
Oh sorry, had tmy custom on when I checked some things with trueshot. It happens also on the default, will get a snapshot asap when I'm home.

Yeah that is correct. I paused the rotation just as the extra SS came up. Steady focus was applied but it says it's not and it needs another steady shot.

Let me get the snapshot with default settings so everything is neat

**Comment by Williamn88** [comment]
You can see the steady shot buff in the screenshot right under the focus (number). That's where I paused it and did not cast any more steady shots

**Comment by Williamn88** [comment]
Hi again here is a new snapshot with default APL https://pastebin.com/eG6kJBpQ
![image](https://github.com/Hekili/hekili/assets/42271641/3f61985c-f1f7-4a24-b44a-cb2bc74b5b5a)

I paused as the second steady shot was in the middle of being cast. As you can see in the details history I would have completed two casts here and the next one I paused it at was not needed
Does the logic for steady focus have some look-ahead that knows that the current cast is going to trigger steady focus and no more casts is needed or does it only know when the buff is applied ?

Another thing I have noticed is the count can get out of sync. https://pastebin.com/gTWsAW2P
In this snapshot I had just cast a steady shot, but according to the count I was at 0. I could confirm by casting another steady shot and the buff triggereed.

In the details to the right you can see I cast a arcane shot to reset the count. Then a steady shot but somehow the recommendations went back to a 0 count of steady shot instead of 1.

![image](https://github.com/Hekili/hekili/assets/42271641/c4bbd497-f8a9-4154-b0a6-9183ab5e019e)

**Comment by Williamn88** [comment]
Here is the reverse.
It thinks its at 1 count but its actually at zero count (can confirm by it takes two steady shots to put up the steady focus buff after)

https://pastebin.com/LsFCkvUU
![image](https://github.com/Hekili/hekili/assets/42271641/507448f6-e07f-4db1-8dd6-9d9f4202f508)

Another screenshot with the cast history showing I put up two steady shot, waited for the condition to refresh steady focus. It thinks its at one count, but its actually zero.
![image](https://github.com/Hekili/hekili/assets/42271641/f25f81a3-547e-42f1-89e8-e24ef217d406)

Let me know if there is something you want me to do that explains it better.

**Comment by Williamn88** [comment]
Bonus info.
Been testing a bit and I cant say 100% certainly but I have not been able to trigger triple steady shot at high focus when reverting the change you made some months ago in my testing so far.
![image](https://github.com/Hekili/hekili/assets/42271641/d2f3323a-b1b4-4fef-9a2b-19e57c3c01b1)


Have switched between having it in and not having it in and so far I have only been able to trigger the triple with the change in.
Again not saying its 100% the cause. But could there be something that triggers a count reset that should not happen ?

**Comment by syrifgit** [comment]
I just took a snapshot too, it was 100% on the THIRD cast of steadyshot being recommended.

https://pastebin.com/pvHV8K1c

**Comment by Hekili** [comment]
This may be resolved in the next release.
