### ISSUE TITLE
[BUG] "Decaying Mind" causing Hekili to cease function

### ISSUE THREAD

**Issue by Nyloaf** [Hekili/hekili#2752]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When running Underrot I've encountered a strange issue several times now where getting stunned by a "Diseased Lasher" with the "Decaying Mind" ability causes Hekili to cease most function. It will stop showing dps rotation suggestions and tends to only show dps cd's that are ready and recommended to use. Whenever this happens it requires a ui reload to fix, and has happened several times through the handful I've ran where I was affected by the ability. I unfortunately do not have any recordings of this or error strings, since M+ is a bit time sensitive.

### How to Reproduce

1. Enter Underrot (unclear if it's the S2 M+ version only or not)
2. Aggro a Diseased Lasher
3. Let it cast Decaying Mind on you
4. If the bug occurred, the dps recommendation frames should go empty and only the damage CD recommendation icon will remain

### Player Information (Link)

https://pastebin.com/fpYWuBfE

### Error Messages (Link)

N/A

### Additional Information

I never receive error messages when the bug occurs, it just happens silently and requires a ui reload. Hopefully it can be easily recreated.

### Contact Information

Discord UID <@353326637846233088>

**Comment by Hekili** [comment]
You'll need to attempt to snapshot after this happens; I've been hit with Decaying Mind and the addon functions as usual when it breaks.

> I never receive error messages when the bug occurs, it just happens silently and requires a ui reload. Hopefully it can be easily recreated.

You could easily have error messages hidden.  Look into BugSack/BugGrabber, or check /hekili "Warnings" after this happens.

**Comment by Hekili** [comment]
I'll need snapshot/warning data from a run where this occurred, since I can't replicate it myself.  I'll leave this open for another several days.
