### ISSUE TITLE
Wotlk Classic Unholy DK Rotation Update

### ISSUE THREAD

**Issue by Wrathspawn** [Hekili/hekili#2754]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Unholy DK rotation is WOTLK classic is rather different from WOLTK original. Sites such as https://wowtbc.gg/wotlk/class-guides/unholy-death-knight/ have scrapped the correct discords and compiled the modern rotation ( including the t9 update bringing back Scourge Strike), we rely heavily on DnD now even in single target and weave the remainder to ensure buff uptime with Ghoul Frenzy being maxed as far as not letting the other buffs drop. 

### How to Reproduce

Enter the game as an unholy dk using the spec here (https://wowtbc.gg/wotlk/class-guides/unholy-death-knight/). 
Scourge Strike
When you get Sigil of Virulence (phase 3), this build will outperform the one above, this is the 0/18/53 spec and will be the main unholy spec in t9 and t10 ICC.

The spec APL as is, is very outdated and note reflective of the one used by all unholy DK's today.

### Snapshot (Link)

current APL in hekili addon is incorrect for WOTLK classic DK, Unholy spec

### Additional Information

# APL for Unholy Death Knight - WotLK Classic

# Opener
actions.precombat=use_item,name=potion_of_speed,if=cooldown.summon_gargoyle.remains>120
actions.precombat+=unholy_presence
actions.precombat+=unholy_presence
actions.precombat+=death_and_decay
actions.precombat+=horn_of_winter
actions.precombat+=use_item,name=trinket_name,use_off_gcd=1
actions.precombat+=bone_shield
actions.precombat+=ghoul_frenzy,if=precombat_seconds<=10
actions.precombat+=icy_touch
actions.precombat+=plague_strike
actions.precombat+=blood_strike
actions.precombat+=/scourge_strike,if=talent.scourge_strike.enabled
actions.precombat+=death_and_decay
actions.precombat+=blood_tap
actions.precombat+=ghoul_frenzy
actions.precombat+=summon_gargoyle
actions.precombat+=empower_rune_weapon
actions.precombat+=use_items
actions.precombat+=/scourge_strike,if=talent.scourge_strike.enabled
actions.precombat+=army_of_the_dead
actions.precombat+=icy_touch
actions.precombat+=plague_strike
actions.precombat+=blood_boil
actions.precombat+=blood_presence,if=cooldown.summon_gargoyle.remains<=0

# Default Priority (Single Target)
actions=auto_attack
actions+=blood_presence
actions+=horn_of_winter,if=talent.horn_of_winter.enabled
actions+=bone_shield
actions+=summon_gargoyle
actions+=empower_rune_weapon
actions+=blood_tap,if=buff.ghoul_frenzy.remains<=10
actions+=death_coil,if=runic_power>=40|buff.free_death_coil.react
actions+=icy_touch
actions+=plague_strike
actions+=blood_strike
actions+=death_and_decay,if=buff.ghoul_frenzy.remains<=10
actions+=/ghoul_frenzy,if=buff.ghoul_frenzy.remains<=10
actions+=icy_touch
actions+=blood_boil

# AoE Rotation
actions.aoe=auto_attack
actions.aoe+=blood_presence
actions.aoe+=horn_of_winter,if=talent.horn_of_winter.enabled
actions.aoe+=bone_shield
actions.aoe+=summon_gargoyle
actions.aoe+=empower_rune_weapon
actions.aoe+=icy_touch
actions.aoe+=plague_strike
actions.aoe+=/blood_strike,if=talent.desolation.enabled
actions.aoe+=pestilence
actions.aoe+=blood_tap
actions.aoe+=death_and_decay
actions.aoe+=/ghoul_frenzy,if=buff.ghoul_frenzy.remains<=10
actions.aoe+=icy_touch
actions.aoe+=pestilence

# Defensive Abilities
actions.defensive=death_strike,if=incoming_damage_5s>=health.max*0.20
actions.defensive+=icebound_fortitude,if=incoming_damage_5s>=health.max*0.30
actions.defensive+=antimagic_shell,if=incoming_magic_damage_5s>=health.max*0.20
actions.defensive+=dancing_rune_weapon

# Interrupts
actions.interrupt=mind_freeze
actions.interrupt+=strangulate

# Automatic single-target attack
actions+=auto_attack

# Default Priority (Single Target)
actions=auto_attack
actions+=blood_presence
actions+=horn_of_winter,if=talent.horn_of_winter.enabled
actions+=bone_shield,if=!buff.bone_shield.up
actions+=summon_gargoyle
actions+=empower_rune_weapon
actions+=blood_tap,if=buff.ghoul_frenzy.remains<=10
actions+=death_coil,if=runic_power>=40|buff.free_death_coil.react
actions+=icy_touch
actions+=plague_strike
actions+=blood_strike
actions+=death_and_decay,if=buff.ghoul_frenzy.remains<=10
actions+=/ghoul_frenzy,if=buff.ghoul_frenzy.remains<=10
actions+=icy_touch
actions+=blood_boil

# Proceed to steps 1 - 5 if Ghoul Frenzy has 10 seconds or less remaining
actions.if_gf_10_or_less=icy_touch
actions.if_gf_10_or_less+=blood_boil
actions.if_gf_10_or_less+=/ghoul_frenzy,if=buff.ghoul_frenzy.remains<=10
actions.if_gf_10_or_less+=icy_touch
actions.if_gf_10_or_less+=blood_boil

# Proceed to steps 1 - 5 if Ghoul Frenzy has more than 10 seconds remaining
actions.if_gf_more_than_10=icy_touch
actions.if_gf_more_than_10+=/scourge_strike,if=talent.scourge_strike.enabled
actions.if_gf_more_than_10+=icy_touch
actions.if_gf_more_than_10+=plague_strike
actions.if_gf_more_than_10+=blood_boil

# Use the appropriate step based on Ghoul Frenzy remaining time
actions+=/if=buff.ghoul_frenzy.remains<=10
actions+=if_gf_10_or_less
actions+=/if=buff.ghoul_frenzy.remains>10
actions+=if_gf_more_than_10

### Contact Information

wrath2054

**Comment by Thebigzdog** [comment]
So how do i implement the proper rotation for hekili im little bit confused please help and explain so i can understand ty
