### ISSUE TITLE
[BUG] BM Hunter is not working for the addon as of today.

### ISSUE THREAD

**Issue by Jagged21** [Hekili/hekili#2756]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Was working fine yesterday and previous days. Today, the add one does not work for BM hunter spec. Spells are not moving after being used and even after a pet is called, it is still stuck displaying to call a pet out. It seems to work for a moment after doing a reload but goes right back to being "stuck" and not displaying which spells to use or going forward after pressing displayed spell.

### How to Reproduce

Enter the game with the specialization set as Beast Mastery Hunter. It works fine on Marksmanship Hunter and my other classes.

### Player Information (Link)

https://pastebin.com/tZzt6qJM

### Error Messages (Link)

None

**Comment by GetStiitches** [comment]
seems like its pet classes.

**Comment by Hekili** [comment]
Fixed in 1.0.12.
