### ISSUE TITLE
[BUG] Hekili doesn't update with pet classes.

### ISSUE THREAD

**Issue by GetStiitches** [Hekili/hekili#2757]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After summoning a pet or loading into a dungeon with a pet class hekili will not update abilities.

### How to Reproduce

1. Enter game as BM hunter
2. go to target dummys
3. summon or dismiss pet
4. attack dummies.

1x Hekili/State.lua:2523: attempt to index field '?' (a nil value)
[string "@Hekili/State.lua"]:2523: in function <Hekili/State.lua:2497>
[string "@Hekili/State.lua"]:2625: in function <Hekili/State.lua:2595>
[string "@Hekili/Dragonflight/HunterBeastMastery.lua"]:2189: in function `usable'
[string "@Hekili/State.lua"]:7096: in function `IsUsable'
[string "@Hekili/Core.lua"]:932: in function `GetPredictionFromAPL'
[string "@Hekili/Core.lua"]:1382: in function `GetNextPrediction'
[string "@Hekili/Core.lua"]:1777: in function `Update'
[string "@Hekili/Options.lua"]:11004: in function `MakeSnapshot'
[string "@Hekili/Options.lua"]:11105: in function `FireToggle'
[string "@Hekili/UI.lua"]:2818: in function <Hekili/UI.lua:2817>

Locals:
t = <table> {
 spell = 300091
 name = "guardian_of_azeroth"
 model = <table> {
 }
 duration = 31
 key = "guardian_of_azeroth"
}
k = "expires"
totemIcon = nil
petSpell = 300091
(*temporary) = nil
(*temporary) = 300091
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
class = <table> {
 totems = <table> {
 }
 talents = <table> {
 }
 abilityList = <table> {
 }
 stateExprs = <table> {
 }
 auras = <table> {
 }
 pets = <table> {
 }
 itemPack = <table> {
 }
 abilityByName = <table> {
 }
 interrupts = <table> {
 }
 gear = <table> {
 }
 trinkets = <table> {
 }
 packs = <table> {
 }
 setBonuses = <table> {
 }
 itemList = <table> {
 }
 knownAuraAttributes = <table> {
 }
 primaryResource = "focus"
 file = "HUNTER"
 stateTables = <table> {
 }
 stances = <table> {
 }
 auraList = <table> {
 }
 powers = <table> {
 }
 range = 8
 itemSettings = <table> {
 }
 hooks = <table> {
 }
 essence_unscripted = false
 settings = <table> {
 }
 num = 4
 resources = <table> {
 }
 initialized = true
 specs = <table> {
 }
 stateFuncs = <table> {
 }
 pvptalents = <table> {
 }
 potionList = <table> {
 }
 resourceAuras = <table> {
 }
 variables = <table> {
 }
 toggles = <table> {
 }
 potions = <table> {
 }
 itemMap = <table> {
 }
 abilities = <table> {
 }
}
state = <table> {
 swing = <table> {
 }
 FindPlayerAuraByID = <function> defined @Hekili/Utils.lua:516
 summonPet = <function> defined @Hekili/State.lua:1155
 role = <table> {
 }
 IsKnown = <function> defined @Hekili/State.lua:6906
 UnitGUID = <function> defined =[C]:-1
 purge = <table> {
 }
 stat = <table> {
 }
 ptr = 0
 off_hand = <table> {
 }
 floor = <function> defined =[C]:-1
 tonumber = <function> defined =[C]:-1
 SetWhitelist = <function> defined @Hekili/State.lua:6621
 holds = <table> {
 }
 display = "Primary"
 prev_off_gcd = <table> {
 }
 SetDefaultVariable = <function> defined @Hekili/State.lua:4426
 mainhand_speed = 2.306000
 channelSpell = <function> defined @Hekili/State.lua:1218
 equipped = <table> {
 }
 gain = <function> defined @Hekili/State.lua:1523
 TimeToReady = <function> defined @Hekili/State.lua:7263
 setStance = <function> defined @Hekili/State.lua:1129
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 UnitAura = <function> defined =[C]:-1
 AddToHistory = <function> defined @Hekili/Events.lua:1021
 bloodseeker = <table> {
 }
 SetupCycle = <function> defined @Hekili/State.lua:764
 print = <function> defined @Hekili/State.lua:538
 GetSpellCount = <function> defined =[C]:-1
 ClashOffset = <function> defined @Hekili/State.lua:7480
 azerite = <table> {
 }
 offset = 0
 QueuedCastRemains = <function> defined @Hekili/State.lua:6179
 ApplyCastingAuraFromQueue = <function> defined @Hekili/State.lua:6203
 TargetBuffUp = <function> defined @Hekili/State.lua:5718
 pvptalent = <table> {
 }
 rawGain = <function> defined @Hekili/State.lua:1530
 GetItemGem = <function> defined =[C]:-1
 UnitIsFriend = <function> defined =[C]:-1
 action = <table> {
 }
 addStack = <function> defined @Hekili/State.lua:1003
 HasRequiredResources = <function> defined @Hekili/State.lua:7226
 TargetDebuffUp = <function> defined @Hekili/State.lua:5723
 UnitCanAttack = <function> defined =[C]:-1
 rawSpend = <function> defined @Hekili/State.lua:1543
 script = <table> {
 }
 IsUsable = <function> defined @Hekili/State.lua:7084
 GetItemInfo = <function> defined =[C]:-1
 GetPlayerAuraBySpellID = <function> defined =[C]:-1
 health = <table> {
 }
 IsFiltered = <function> defined @Hekili/State.lua:7049
 cooldown = <table> {
 }
 stanc

### Player Information (Link)

https://pastebin.com/F3nApYzi

### Error Messages (Link)

https://pastebin.com/5fNch9u0

### Contact Information

getstiitches

**Comment by Hekili** [comment]
Fixed in 1.0.12.
