### ISSUE TITLE
plz delet

### ISSUE THREAD

**Issue by Briickwall** [Hekili/hekili#2759]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

the priority is still recommending RSK and FoF when they are on CD and is suggesting TP when it would break mastery

### How to Reproduce

log in to windwalker monk
go to target dummy
start dpsing
observe broken prio

### Player Information (Link)

https://pastebin.com/PEartYFU

### Error Messages (Link)

https://pastebin.com/PEartYFU

**Comment by Firidan** [comment]
FYI 
Similar thing on feral -> showing BS without charges/ Thrash even when just applied

**Comment by Hekili** [comment]
This is resolved in 1.0.12a.
