### ISSUE TITLE
BDK Boneshield stacks running out, Ossuary falling off.

### ISSUE THREAD

**Issue by PARADOX070** [Hekili/hekili#276]
Version: Latest

**Issue**
Boneshield stacks often run out or drop below 5 before marrowrend is suggested. Changing "buff.bone_shield.stack < 3" for both Marrowrend entries to 7  in Action List >> Standard >> Entry and everything seems to work somewhat correctly. However they still most of time just run out of time.

**To Reproduce**
Hit a dummy, Boss, Mob, Anything.

**Expected behavior**
Boneshield should not drop below 5 stacks or run out before it is suggested, Or the talent Ossuary is totally wasted.

Issue Link: https://pastebin.com/ivs4jD0V

Snapshot Link 1: https://pastebin.com/D41TSEZB
Snapshot Link 2: https://pastebin.com/B5QCmQqL

**Comment by Hekili** [comment]
Should be resolved.
