### ISSUE TITLE
[REC] Windwalker ST recommending builders (Tiger Palm) over free spenders (RSK/SOTWL/FOF) in serenity window

### ISSUE THREAD

**Issue by Moistbuddha2** [Hekili/hekili#2761]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Windwalker Serenity opener after casting Tiger Palm once should strictly consist of rising sun kick, fists of fury(sometimes clipping for rising sun kick), faeline stomp when debuff is no longer applied to target, and BoK as needed which can be seen in the priority list here from the Peak of Serenity website that is also basedon the APL:
[Expel Harm] 15s before pull
[Chi Wave] on pull
[Expel Harm]
[Summon White Tiger Statue])
[Faeline Stomp] for [Faeline Harmony] if talented
[Invoke Xuen, the White Tiger]
[Tiger Palm] for Skyreach buff
[Serenity]
[Rising Sun Kick]
[Strike of the Windlord]
[Fists of Fury]
[Rising Sun Kick] (clip [Fists of Fury]

       

### How to Reproduce

1. Enter Game as Windwalker
2. Expel Harm, Tiger statue, Xuen, Tiger Palm, Serenity and begin to see multiple recommendations of Tiger Palm over the higher priority Rising Sun Kicks, Strike of the windlord, fists of fury, and even blackout kick. 

### Snapshot (Link)

https://pastebin.com/CxQibG9X

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wbAtGTfUFScLdGJyU1aFhA

**Comment by Hekili** [comment]
There were recent priority updates that were attempting to apply Skyreach/Skytouch without checking that it is talented.  There was also a code bug that I've fixed.  This should be resolved in the next release.
