### ISSUE TITLE
Proposed Changes to Augumentation Priority [Sources Needed]

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#2762]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'll start in order.
1. Tip the Scales ability is used on cd, which in turn if you look at the rotation recommendations and logs. Tip the Scales we use only with Fire Breath. But not with Upheaval. Spending Tip the Scales on Upheaval is a mistake because there we get only range, which is useless.
2. Regarding Fire Breath, if we take another set of talents under M+ we always recommend Fire Breath for 1 charge, when by rotation and recommendations we use it always for the maximum number of charges. Here is a set of my talents in M+ (BEcBsJu/D+01p9npZvkV+nWIkTSJpFJJahkEJIJJJNAAAAAAAAAAAAAAkEkgISIkkAAAAAAAgEJtIJikAJNB) So you can see for yourself that Fire Breath recommendation will always be for 1 charge.

### How to Reproduce

Playing on the evoker.

### Snapshot (Link)

https://pastebin.com/YsPYCVqR

**Comment by Hekili** [comment]
> Tip the Scales ability is used on cd, which in turn if you look at the rotation recommendations and logs. Tip the Scales we use only with Fire Breath. But not with Upheaval. Spending Tip the Scales on Upheaval is a mistake because there we get only range, which is useless.

You'll have to provide a source and there aren't sims to cite.  Icy Veins' guide states:
![image](https://github.com/Hekili/hekili/assets/9438134/36ef7b83-fb92-4f1f-a7cd-a8d5e6b7586a)

Based on that, I should make Tip the Scales get recommended before Upheaval only in multi-target, which makes sense.  I understand it only impacts the Upheaval radius, though.  You may want to recommend an update to the guides, or provide a guide reference that matches your proposal.

> Regarding Fire Breath, if we take another set of talents under M+ we always recommend Fire Breath for 1 charge, when by rotation and recommendations we use it always for the maximum number of charges. Here is a set of my talents in M+ (BEcBsJu/D+01p9npZvkV+nWIkTSJpFJJahkEJIJJJNAAAAAAAAAAAAAAkEkgISIkkAAAAAAAgEJtIJikAJNB) So you can see for yourself that Fire Breath recommendation will always be for 1 charge.

No, it won't always be for one charge, but you have Time Skip toggled off or moved to a different display, so the cooldown is always at maximum:

> - this entry's criteria FAILS: talent.leaping_flames.enabled[true] & talent.time_skip.enabled[true] & ! talent.interwoven_threads.enabled[true] & cooldown.time_skip.remains[180.00] <= cast_time[2.26] & buff.ebon_might.remains[3.26] > cast_time[2.26]

**Comment by Hekili** [comment]
I'm making the Tip the Scales adjustment in the next release.

**Comment by geraint425** [comment]
Hello again. The latest update fixed the problem with Tip the Scales. Thank you for this. But the problem with talents under M+ is still there. Fire breath is always recommended for 1 charge, when it should be recommended for the maximum amount. I took other talents in M+ (BEcBsJu/D+01p9npZvkV+nWIkTSJpFJJahkkkSCSSSSSSSSDAAAAAAAAAAAAAAJBCiIhQSCAAAASSSLSiIJQ0E) and there is no difference. Here's a Snapshot (https://pastebin.com/GsXcFNE0) I did with the recommendation of 1 charge of Fire breath. It's just that the Plot the Future talent to which Fire breath is tied is not taken in M+ because it's not effective. Please make a correction for M+. Thank you.
