### ISSUE TITLE
Demonology ST rotation

### ISSUE THREAD

**Issue by Jurandes** [Hekili/hekili#2765]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Demonology warlock on 10.1.5 version is getting crazy rotation. As an opener seems legit,but after summoning felguard addon starts showing summon demonic tyrant as a next spell.
Sometimes also skips summon vilefiend on cd and demonic strenght without tyrant active.

Also, there should be trinkets/potions/racials to be used  just **BEFORE** summon tyrant - addon shows just after.

### How to Reproduce

1.Enter the game as demo lock
2.take a pure ST build with nether portal and regin of tyranny
3.start rotation with Power siphon on 2 imps>shadowblot x2 > Nether portal>summon felguard

After that sequence you will notice total mix up. 

### Snapshot (Link)

https://pastebin.com/PaV1jKG3

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6KPXEuZm3bqcNVfpfBzs5F

### Contact Information

Jurandes

**Comment by Hekili** [comment]
Your snapshot is not complete.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
