### ISSUE TITLE
Empowerment error lua message showing after update

### ISSUE THREAD

**Issue by mrgrimms** [Hekili/hekili#2767]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

while the addon is suggestion empowerments it's throwing a lua error 

### How to Reproduce

Enter game as Augment Evoker
Start to go through rotation in Hekili
Once any empowered spell (firebreath, upheaval) is suggested lua error is given

### Player Information (Link)

https://pastebin.com/B63F1FSL

### Error Messages (Link)

https://pastebin.com/EW8VRyEP

### Contact Information

Grimms - Discord

**Comment by Hekili** [comment]
It would be useful to take a snapshot since this is dependent on what is recommended at the time.  I'm not able to replicate the error on my end.

Can you post screenshots of your Primary display's Empowerment settings?

**Comment by mrgrimms** [comment]
Here is my screenshot of the Primary Display's empowerment settings. Testing this on dummies to get the snapshot and it's not doing it this morning. So not sure what changed, I reloaded last night in raid to see if that would fix it and it did not. I'll keep a eye out again. 
![image](https://github.com/Hekili/hekili/assets/61772590/8697ce6e-ffef-4339-95a0-472a84a9401b)

**Comment by Hekili** [comment]
Do you have any WeakAuras that can interact/interfere with the addon?  There was a "Better Hekili Targeting" WeakAura floating around that definitely ought not be used.

If it occurs again, to diagnose the issue, I'll need to see the output of the following macros:

`/dump Hekili.DB.profile.displays.Primary.empowerment`
`/dump Hekili.State.empowerment`

You can just paste each line into chat and screenshot the output.

**Comment by mrgrimms** [comment]
No I don't use that weakaura. I try to keep Hekili free of anything outside of the addon to not mess with it. I even did a fresh restart of it deleting the lua files (both) and re setting up my setting to see if it was something I messed up. I have my Vod from last night but doubt that helps much.

**Comment by Hekili** [comment]
Did you swap specializations back and forth at any point?  Or swap between different addon profiles?

I still can't replicate the problem, but I'm just guessing at what would make either the display's Empowerment options unavailable or the `empowerment` data in the state table become unavailable.

**Comment by mrgrimms** [comment]
I did right before raid, I swapped from Preservation to Augmentation. But there were a couple reloads done after that.

**Comment by Hekili** [comment]
If you experience this again and can paste those `/dump` lines, please go ahead and reopen the ticket.  I'm not able to replicate this.
