### ISSUE TITLE
Survival Hunter AoE Priority not using Butchery, Fury of the Eagle

### ISSUE THREAD

**Issue by Kahb00m** [Hekili/hekili#2768]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

SV M+ Talent Build Used: B8PAAAAAAAAAAAAAAAAAAAAAA4ABahkQoEEIJJplIIESKRIAAAAAQEp0kiGkIhESoBAAAAA
After thoroughly examining the AoE Priority for the Survival build listed above, ensuring that at least 5 targets were within range and engaged in combat, dotted w/ Serpent Sting just to be sure Hekili would detect them, the addon does not ever recommend using Butchery or Fury of the Eagle. I thought it might be possible it's holding FotE until targets reach sub-65% or something, but _AT MINIMUM_ Butchery should be used as 8th highest priority for AoE in this talent build when Shrapnel Bomb is active, or when capped at 3 charges, and it does not get recommended under these conditions, much less any others. 

It's possible that certain conditions aren't being detected properly, or that the abilities aren't being detected. I ran through the rotation for 5+ minutes on three separate logins to verify that the abilites were never recommended.

### How to Reproduce

1. Enter game as a Survival Hunter
2. Use Talent Build Import Code: B8PAAAAAAAAAAAAAAAAAAAAAA4ABahkQoEEIJJplIIESKRIAAAAAQEp0kiGkIhESoBAAAAA
3. Engage Cleave Target Dummies, ensuring you're in combat with at least 3
4. Begin Rotation, Butchery and Fury of the Eagle are never recommended.

### Snapshot (Link)

https://pastebin.com/E6brDHJ1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mqN4i5nb5UVv3LdFP298Uv

**Comment by Hekili** [comment]
You'll have to provide the complete snapshot -- it will be hundreds of lines.  Use CTRL+A to select all and CTRL+C to copy, then update your Pastebin or create a new one.  Thanks!

**Comment by Kahb00m** [comment]
Will do, I'll get another 5min session in and try to capture again. Unless this is a configuration issue on my end though, this is very easy to replicate, and my sim shows 40+ uses of Butchery on 5-targets.

**Comment by Kahb00m** [comment]
Updated the Pastebin, Ran through using the AoE priority for 5+ min. Hopefully that has everything you need!
https://pastebin.com/E6brDHJ1

**Comment by Kahb00m** [comment]
I can always put this in another issue, but I noticed it never recommended Serpent Sting with the Hydra's Bite talent in AoE (I know it never does in Single Target, that's why I didn't initially notice for AoE). In the snapshot provided, I manually casted it a few times outside of Hekili's recommendations to ensure I was in combat with enough dummies.

**Comment by Hekili** [comment]
> https://pastebin.com/E6brDHJ1

```
targets:  Nameplates are enabled.
 - Checking nameplate1 [ Creature-0-3776-2444-137-198594-0000525BCB ] Cleave Training Dummy.
    nameplate1   - -1 - Creature-0-3776-2444-137-198594-0000525BCB - 378.00 - 10 - Cleave Training Dummy 
 
    - Excluded by on-screen nameplate requirement.
    - Excluded by on-screen nameplate requirement.
    - Excluded by on-screen nameplate requirement.
    - Excluded by on-screen nameplate requirement.
```

You have nameplate-based target-detection, with the setting that excludes off-screen enemies, but only your active target's nameplate is being displayed.  You'll need to enable nameplates for the other enemies.

> I noticed it never recommended Serpent Sting with the Hydra's Bite talent in AoE (I know it never does in Single Target, that's why I didn't initially notice for AoE). In the snapshot provided, I manually casted it a few times outside of Hekili's recommendations to ensure I was in combat with enough dummies.

This can be impacted by the same as above -- based on your nameplates, you only have one target.  Recommend Target Swaps is disabled.  There is a fairly low-priority usage of Serpent Sting in multi-target when Viper's Venom is *not* talented or Hydra's Bite *is* talented, but only if your current target's dot is refreshable or there's another target detected that's missing the dot.

**Comment by Kahb00m** [comment]
Confirmed both issues solved with different target detection settings. Thank you for the help!
