### ISSUE TITLE
[REC] Hekili keeps recommending spells that are cooldown

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#2770]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While playing my guardian druid Hekili keeps recommending spells that are still on cooldown while in combat.

### How to Reproduce

1. Enter the game as a Guardian Druid
2. Using the following talents: BgGAlOfJaEu03UKI2/Mrbr1a+BAAAAAAAAAAAAQiIJSJUSSgkiESShCAJJIIBSSSSSiUAIAAAAAAiASIEA
3. Follow Hekili's recommendations.
4. After a short time that addon will start to recommend spells on cooldown
5. If spells are currently on CD Hekili should recommend another spell rather than waiting for cooldowns.

### Snapshot (Link)

https://pastebin.com/6AgaQSVa

### Contact Information

mrwizard8972

**Comment by Hekili** [comment]
That's your Cooldowns display, displaying the next Cooldown that has its requirements met.  It's not going to fill in with other abilities.  This is the intended behavior for Cooldowns Shown Separately.

You'll want to either:
1. Turn off Cooldowns Shown Separately (/hekili > Toggles).  Then the CDs are kept in the Primary/AOE displays as usual and regular rotational abilities will show before them.
2. Move your Cooldowns display?  I suspect you might have your displays overlapping or some other issue leading to confusion.

**Comment by Eutherix** [comment]
I am currenly having this issue. 06/08/2025

Incarnation: Guardian of Ursoc remains being recommended even when on cooldown. I do not have nayhting overlapping and I have turned off the "Cooldowns shown seperately" option. This is only a recent issue (about a week). i'm not really sure what to do at this point. I've considered removing the recommendation altogether.

**Comment by syrifgit** [comment]
> I am currenly having this issue. 06/08/2025
> 
> Incarnation: Guardian of Ursoc remains being recommended even when on cooldown. I do not have nayhting overlapping and I have turned off the "Cooldowns shown seperately" option. This is only a recent issue (about a week). i'm not really sure what to do at this point. I've considered removing the recommendation altogether.

Then open a new ticket and follow the instructions.
