### ISSUE TITLE
Shaman AOE rotation just stops and no new actions show up

### ISSUE THREAD

**Issue by Minchen0** [Hekili/hekili#2772]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When in an AoE enviroment the hekili helper just stops feeding abilities and after a few seconds it comes back.

Talents BcQAAAAAAAAAAAAAAAAAAAAAAIJBQSSkkkASSLJJAAAAAAAAAAAAgSEkQiSKiCJtkkyBAKBJkCC

### How to Reproduce

To reproduce just go into a aoe pack and starting hitting the buttons hekili tells me and it will freeze the functions every so often for about 5 seconds and then the rotation starts again.

### Snapshot (Link)

https://pastebin.com/yvzJ2v0V

**Comment by Minchen0** [comment]
Issue report:


build: v10.1.5-1.0.10
level: 70 (70)
class: SHAMAN
spec: enhancement

talents: BcQAu3fz4tp2ZikXIAdNeR+oLIJBQSSkkkASSLJJAAAAAAAAAAAAgSEIkokmASLJpEEKREhCC
    alpha_wolf = 1/1
    ancestral_defense = 1/1
    ancestral_guidance = 1/1
    astral_shift = 1/1
    brimming_with_life = 1/1
    capacitor_totem = 1/1
    chain_lightning = 1/1
    converging_storms = 1/1
    crash_lightning = 1/1
    crashing_storms = 1/1
    deeply_rooted_elements = 1/1
    doom_winds = 1/1
    earth_elemental = 1/1
    elemental_warding = 2/2
    elemental_weapons = 2/2
    feral_spirit = 1/1
    fire_and_ice = 1/1
    flurry = 1/1
    forceful_winds = 1/1
    frost_shock = 1/1
    go_with_the_flow = 2/2
    healing_stream_totem = 1/1
    ice_strike = 1/1
    improved_maelstrom_weapon = 2/2
    legacy_of_the_frost_witch = 2/2
    maelstrom_weapon = 1/1
    natures_fury = 2/2
    natures_guardian = 2/2
    overflowing_maelstrom = 1/1
    planes_traveler = 1/1
    poison_cleansing_totem = 1/1
    raging_maelstrom = 1/1
    spirit_walk = 1/1
    static_accumulation = 2/2
    static_charge = 1/1
    stormblast = 1/1
    stormflurry = 1/1
    storms_wrath = 1/1
    stormstrike = 1/1
    sundering = 1/1
    thorims_invocation = 1/1
    thunderous_paws = 1/1
    thundershock = 1/1
    thunderstorm = 1/1
    totemic_surge = 2/2
    unruly_winds = 1/1
    wind_rush_totem = 1/1
    wind_shear = 1/1
    windfury_totem = 1/1
    windfury_weapon = 1/1
    winds_of_alakir = 2/2
    witch_doctors_ancestry = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: ominous_chromatic_essence = 1
    tier30 = 4

gear:  = 1
    ominous_chromatic_essence = 1
    tier30 = 4

legendaries: none

itemIDs: 155881, 159463, 190513, 193463, 193465, 193809, 198332, 202468, 202469, 202470, 202473, 202572, 203729, 204424, 204465

settings: aoe = 2
    combatRefresh = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 20
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    check_crash_lightning_range = true
    check_sundering_range = true
    filler_shock = true
    funnel_priority = true
    hostile_dispel = false
    pad_lava_lash = true
    pad_windstrike = true
    project_windfury = 0
    purge_icd = 12
    pwave_targets = 0

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    ancestral_guidance     = M4  [06]
    astral_shift           = CQ  [06]
    berserking             = MwU [06]
    bloodlust              = F1  [03]
    capacitor_totem        = `   [01]
    chain_lightning        = 4   [01]
    crash_lightning        = F   [01]
    doom_winds             = R   [01]
    earth_elemental        = F3  [03]
    earth_shield           = F6  [03]
    earthbind_totem        = F5  [03]
    elemental_blast        = V   [06]
    feral_spirit           = T   [01]
    flame_shock            = 2   [01]
    frost_shock            = 1   [01]
    ghost_wolf             = X   [06]
    healing_stream_totem   = 5   [01]
    healing_surge          = F2  [03]
    ice_strike             = Q   [01]
    lava_burst             = V   [06]
    lightning_bolt         = 3   [01]
    lightning_shield       = CR  [06]
    poison_cleansing_totem = Z   [06]
    primordial_wave        = G   [01]
    spirit_walk            = CF  [06]
    stormstrike            = E   [01]
    sundering              = C   [06]
    thunderstorm           = CE  [06]
    wind_rush_totem        = F4  [03]
    wind_shear             = M5  [06]
    windfury_totem         = MwD [06]
    windstrike             = E   [01]

warnings: [#1] Returned unknown string 'funnel' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return funnel"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:935: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1273: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Core.lua"]:1448: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#2] Returned unknown string 'funnel' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return funnel"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1126: in function <Interface/AddOns/Hekili/Scripts.lua:1115>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1296: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Core.lua"]:1448: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#3] Returned unknown string 'funnel' in state metatable [Enhancement:default:22].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return funnel"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:935: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1273: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Core.lua"]:1448: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#4] Returned unknown string 'funnel' in state metatable [Enhancement:default:22].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return funnel"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1126: in function <Interface/AddOns/Hekili/Scripts.lua:1115>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1296: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Core.lua"]:1448: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#5] Returned unknown string 'funnel' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "-- Enhancement:default:21
return safebool( active_enemies>1 and not (safebool(funnel))  )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:845: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#6] Returned unknown string 'funnel' in state metatable [Enhancement:aoe:1].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "-- Enhancement:default:21
return safebool( active_enemies>1 and not (safebool(funnel))  )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:418: in function `CheckStack'
[string "@Interface/AddOns/Hekili/Core.lua"]:965: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:886: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#7] Returned unknown string 'funnel' in state metatable [Enhancement:default:22].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "-- Enhancement:default:22
return safebool( active_enemies>1 and safebool(funnel) )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:845: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#8] Returned unknown string 'funnel' in state metatable [Enhancement:aoe:2].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "-- Enhancement:default:21
return safebool( active_enemies>1 and not (safebool(funnel))  )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:418: in function `CheckStack'
[string "@Interface/AddOns/Hekili/Core.lua"]:965: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:886: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#9] Unable to compile 'trinket.t1.buff.any.duration' - [string "return trinket.t1.buff.any.duration"]:1: attempt to index field 'any' (a nil value) (pcall-n)
From: ! variable.trinket1_is_weird & trinket.t1.has_use_buff & ( buff.ascendance.up | buff.feral_spirit.up | buff.doom_winds.up | ( fight_remains %% trinket.t1.cooldown.duration <= trinket.t1.buff.any.duration ) | ( variable.min_talented_cd_remains >= trinket.t1.cooldown.duration ) | ( ! talent.ascendance.enabled & ! talent.feral_spirit.enabled & ! talent.doom_winds.enabled ) )
[#10] Unable to compile '(fight_remains%%%%trinket.t1.cooldown.duration<=trinket.t1.buff.any.duration)' - [string "return (fight_remains%trinket.t1.cooldown.d..."]:1: attempt to index field 'any' (a nil value) (pcall-b)
From: ! variable.trinket1_is_weird & trinket.t1.has_use_buff & ( buff.ascendance.up | buff.feral_spirit.up | buff.doom_winds.up | ( fight_remains %% trinket.t1.cooldown.duration <= trinket.t1.buff.any.duration ) | ( variable.min_talented_cd_remains >= trinket.t1.cooldown.duration ) | ( ! talent.ascendance.enabled & ! talent.feral_spirit.enabled & ! talent.doom_winds.enabled ) )
[#11] Unable to compile 'trinket.t1.buff.any.duration' - [string "return trinket.t1.buff.any.duration"]:1: attempt to index field 'any' (a nil value) (pcall-n)
From: !variable.trinket1_is_weird&trinket.t1.has_use_buff&(buff.ascendance.up|buff.feral_spirit.up|buff.doom_winds.up|(fight_remains%%trinket.t1.cooldown.duration<=trinket.t1.buff.any.duration)|(variable.min_talented_cd_remains>=trinket.t1.cooldown.duration)|(!talent.ascendance.enabled&!talent.feral_spirit.enabled&!talent.doom_winds.enabled))
[#12] Unable to compile 'trinket.t2.buff.any.duration' - [string "return trinket.t2.buff.any.duration"]:1: attempt to index field 'any' (a nil value) (pcall-n)
From: ! variable.trinket2_is_weird & trinket.t2.has_use_buff & ( buff.ascendance.up | buff.feral_spirit.up | buff.doom_winds.up | ( fight_remains %% trinket.t2.cooldown.duration <= trinket.t2.buff.any.duration ) | ( variable.min_talented_cd_remains >= trinket.t2.cooldown.duration ) | ( ! talent.ascendance.enabled & ! talent.feral_spirit.enabled & ! talent.doom_winds.enabled ) )
[#13] Unable to compile '(fight_remains%%%%trinket.t2.cooldown.duration<=trinket.t2.buff.any.duration)' - [string "return (fight_remains%trinket.t2.cooldown.d..."]:1: attempt to index field 'any' (a nil value) (pcall-b)
From: ! variable.trinket2_is_weird & trinket.t2.has_use_buff & ( buff.ascendance.up | buff.feral_spirit.up | buff.doom_winds.up | ( fight_remains %% trinket.t2.cooldown.duration <= trinket.t2.buff.any.duration ) | ( variable.min_talented_cd_remains >= trinket.t2.cooldown.duration ) | ( ! talent.ascendance.enabled & ! talent.feral_spirit.enabled & ! talent.doom_winds.enabled ) )
[#14] Unable to compile 'trinket.t2.buff.any.duration' - [string "return trinket.t2.buff.any.duration"]:1: attempt to index field 'any' (a nil value) (pcall-n)
From: !variable.trinket2_is_weird&trinket.t2.has_use_buff&(buff.ascendance.up|buff.feral_spirit.up|buff.doom_winds.up|(fight_remains%%trinket.t2.cooldown.duration<=trinket.t2.buff.any.duration)|(variable.min_talented_cd_remains>=trinket.t2.cooldown.duration)|(!talent.ascendance.enabled&!talent.feral_spirit.enabled&!talent.doom_winds.enabled))
[#15] Returned unknown string 'rotation' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return rotation.standard"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:935: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:893: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1273: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Options.lua"]:6354: in function <Interface/AddOns/Hekili/Options.lua:6334>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...sque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

[#16] Unable to compile 'rotation.standard' - [string "return rotation.standard"]:1: attempt to index global 'rotation' (a nil value) (pcall-b)
From: active_enemies > 1 & ( rotation.standard | rotation.simple )
[#17] Returned unknown string 'rotation' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return rotation.simple"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:935: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:893: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1273: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Options.lua"]:6354: in function <Interface/AddOns/Hekili/Options.lua:6334>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...sque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

[#18] Unable to compile 'rotation.simple' - [string "return rotation.simple"]:1: attempt to index global 'rotation' (a nil value) (pcall-b)
From: active_enemies > 1 & ( rotation.standard | rotation.simple )
[#19] Returned unknown string 'rotation' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return (rotation.standard or rotation.simple)"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:935: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1273: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Options.lua"]:6354: in function <Interface/AddOns/Hekili/Options.lua:6334>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...sque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

[#20] Unable to compile '(rotation.standard|rotation.simple)' - [string "return (rotation.standard or rotation.simpl..."]:1: attempt to index global 'rotation' (a nil value) (pcall-b)
From: active_enemies > 1 & ( rotation.standard | rotation.simple )
[#21] Returned unknown string 'rotation' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return rotation.standard"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1126: in function <Interface/AddOns/Hekili/Scripts.lua:1115>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1296: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Options.lua"]:6354: in function <Interface/AddOns/Hekili/Options.lua:6334>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...sque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

[#22] Returned unknown string 'rotation' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return rotation.simple"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1126: in function <Interface/AddOns/Hekili/Scripts.lua:1115>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1296: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Options.lua"]:6354: in function <Interface/AddOns/Hekili/Options.lua:6334>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...sque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

[#23] Returned unknown string 'rotation' in state metatable [Enhancement:default:22].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return rotation.funnel"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:935: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1273: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Options.lua"]:6354: in function <Interface/AddOns/Hekili/Options.lua:6334>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...sque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

[#24] Unable to compile 'rotation.funnel' - [string "return rotation.funnel"]:1: attempt to index global 'rotation' (a nil value) (pcall-b)
From: active_enemies > 1 & rotation.funnel
[#25] Returned unknown string 'rotation' in state metatable [Enhancement:default:22].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "return rotation.funnel"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1126: in function <Interface/AddOns/Hekili/Scripts.lua:1115>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1296: in function <Interface/AddOns/Hekili/Scripts.lua:1264>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1612: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1723: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Options.lua"]:6354: in function <Interface/AddOns/Hekili/Options.lua:6334>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Masque/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Masque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...sque/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

[#26] Priority 'Enhancement' uses action 'unknown' ( precombat - 1 ) that is not found in the abilities table.
[#27] Priority 'Enhancement' uses action 'unknown' ( precombat - 2 ) that is not found in the abilities table.
[#28] Priority 'Enhancement' uses action 'unknown' ( precombat - 3 ) that is not found in the abilities table.
[#29] Priority 'Enhancement' uses action 'auto_attack' ( default - 3 ) that is not found in the abilities table.
[#30] Priority 'Enhancement' uses action 'invoke_external_buff' ( default - 16 ) that is not found in the abilities table.
[#31] Returned unknown string 'rotation' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "-- Enhancement:default:21
return safebool( active_enemies>1 and (rotation.standard or rotation.simple) )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:845: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#32] Update: [string "-- Enhancement:default:21..."]:2: attempt to index global 'rotation' (a nil value)
[string "-- Enhancement:default:21
return safebool( active_enemies>1 and (rotation.standard or rotation.simple) )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:845: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#33] Returned unknown string 'rotation' in state metatable [Enhancement:default:21].
[string "@Interface/AddOns/Hekili/State.lua"]:2322: in function <Interface/AddOns/Hekili/State.lua:1952>
[string "-- Enhancement:default:21
return safebool( active_enemies>1 and (rotation.standard or rotation.simple) )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:845: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1683: in function <Interface/AddOns/Hekili/Core.lua:1446>

[#34] Update: [string "-- Enhancement:default:21..."]:2: attempt to index global 'rotation' (a nil value)
[string "-- Enhancement:default:21
return safebool( active_enemies>1 and (rotation.standard or rotation.simple) )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:845: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1683: in function <Interface/AddOns/Hekili/Core.lua:1446>

**Comment by Hekili** [comment]
Looks like you updated and then downgraded your version of the addon.  Use the latest.
