### ISSUE TITLE
Mage talent Shifting Power range issue in frost/arcane

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#2774]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am getting Shifting Power recommended when pulling targets from a full 40y range. Shifting Power only hits targets within 18y of the player and the targets are not within that range.

### How to Reproduce

1. Enter game as a Frost or Arcane mage.
2. Level to at least 12 for the Shifting Power mage tree talent.
3. Start fighting a target at range.
4. See recommendations.

### Snapshot (Link)

https://pastebin.com/FvzQd4zG

### Additional Information

I observed this in Dragonflight leveling content with a frost mage. The above Pastebin was from a level 12 test character to pare down all the way to the Shifting Power talent. I did not observe it in Fire spec on the test character. I used a target dummy toy in the void elf starting area to make sure there were no nearby "enemies" being detected and that I could be certain of the target's range.

**Comment by Hekili** [comment]
The solution is to move into range, really.  If the addon doesn't recommend it, then you could stand at range and never end up using Shifting Power (and I'd get a ticket about that).

I'll consider adding a range checking option, but it's worth noting that the sim you compare yourself to does not make similar edits and you can easily end up hurting your DPS.

**Comment by ghost** [comment]
Fair enough. I'm using Hekili in open-world content, so staying at range is kind of how I survive things. Maybe I'll spec out of that particular talent.

Most skills show red when out of range, can Shifting Power not do that? Maybe with a similar toggle to Wake of Ashes on Retribution Paladin?

**Comment by Hekili** [comment]
Those skills have an inherent range reported by the API.  Shifting Power doesn't.

**Comment by ghost** [comment]
Dang it, Blizz.

Thank you for taking the time to respond. I'll look over my tree and see if there's a better choice for me, or maybe learn to dance in and out of range or something. Really enjoying the addon so far!

**Comment by Hekili** [comment]
I'm reopening because I'm still considering making this optional.
