### ISSUE TITLE
Make the Aug. opener optional.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#2775]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello. Add optional opener aug. More specifically the part that comes from 2-3 Living Flame. Not always there are bosses where it is needed. You can just start right away with Fire Breath, etc. These 2-3 Living Flame breaks the rotation a lot. And it is not possible to bypass it even manually. If I use Fire Breath, it will still recommend Living Flame to me and even after Upheaval and Breath of Eons it will still recommend Living Flame. Please make it possible to opt out of these unnecessary Living Flame at the start of the rotation. Thank you.

### How to Reproduce

Play Aug

### Snapshot (Link)

*

**Comment by Hekili** [comment]
> Please make it possible to opt out of these unnecessary Living Flame at the start of the rotation. Thank you.

Those buttons still work even while the addon isn't recommending them.

We've had a few struggles understanding each other in past tickets, so I need you to understand that if you submit tickets, you need to provide the required information.  Saying "Play Aug" and not including a snapshot is not helpful.

> More specifically the part that comes from 2-3 Living Flame. Not always there are bosses where it is needed. You can just start right away with Fire Breath, etc.

You can customize the priority in the addon to remove those Living Flame entries, and then just push them in situations when you know you need to.

> These 2-3 Living Flame breaks the rotation a lot.

When?  The most likely candidate would be going from pack to pack in M+, but you haven't provided any detail.  A snapshot where those Living Flames are recommended and you wouldn't want them to be provides details for discussion:
* Why would you want Living Flame in one situation and not in another?
* In your snapshot (that I trust you'll provide), why is it a problem this time?
* If we're talking about one boss vs. another boss, how is the addon supposed to know which bosses you want to do differently?

**Comment by geraint425** [comment]
![image](https://github.com/Hekili/hekili/assets/32466458/d1485b01-e300-44ba-a461-8040d391ef81)
![image](https://github.com/Hekili/hekili/assets/32466458/135989d4-62c3-4b4c-8d46-a5dbe8978623)
No offence, but you're thinking too much about (And why is it ? And why not ? And for what, etc.) I have long ago fixed myself this problem, it was enough just as in the screenshot to turn off this condition and that's it. And the problem is solved what I asked. And as for why it is necessary ? Yes because, there are fights where classes immediately press the burst button, and there is no time on bosses to stand and press 3 Living Flame. Because while I make them on the recommendation of the addon, the boss can already move to another zone, or start casting a big aoe spell from which you need to get out (Echo and sarkaret bosses). I have already fixed the second problem, when we move, and at the moment of movement we have in the recommendation shows Fire Breath and uphvale and block further rotation, I made it so that now these spells are used only when I am static standing, and if I am in motion, they are replaced by other spells that are more profitable to press use the same spell as Eruption because it extends EM and we have from this increases the time of action of EM and DPS on the logs. These are the little things you have taken into account in Devastation but you don't use them in AUG although I see you have taken Devastation completely as a base with minimal values. Thanks for this, I have already fixed two critical problems myself. Because I've attached a screenshot, 86 log is your rotation does. And 99 is with my edits with these little things. And as you can see it's a huge difference. Because 1 to use at the beginning of 3 Living Flame is not necessary, no one does it on the logs. 2 Fire Breath and uphvale on the move should not stop rotation, but should be replaced by Eruption or Living Flame because it increases our efficiency. I think I explained enough without Snapshot, which is not needed in this situation, because I was able to do such small things myself without code in rotation with your help.
