### ISSUE TITLE
gcd spiral removal

### ISSUE THREAD

**Issue by DruidSmurf** [Hekili/hekili#2777]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

First off, apologies if I'm blind or stupid, but after an hour of looking, I haven't found a way.

I want to not see GCD timer (clock hand showing when the ability is ready) on Hekili Display.
![show gcd request](https://github.com/Hekili/hekili/assets/138749972/d5796986-ec1b-4380-8ce4-161e836eae0b)

Hopefully it's an easy solution and I just haven't found it.
Thank you for the addon btw, it really makes learning new specs a lot smoother! <3

**Comment by Hekili** [comment]
I don't intend to pursue this, unless it just incidentally occurs in the course of updating options/UI.  This addon is intended to show what you should do next and when you should do it.

**Comment by DruidSmurf** [comment]
Aright. Ty again for the really helpful addon!
