### ISSUE TITLE
Add option Priority to recast Faeline Stomp if Ancient_teachings is not active 

### ISSUE THREAD

**Issue by krispykos** [Hekili/hekili#2779]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Mistweaver option 2023-02-16:  Added option to avoid recasting Faeline Stomp when standing in an existing faeline (for mana efficiency).

Can you add or is there any way to add an option to add priority for Faeline stomp if Ancient_teachings isn't buffed 

### Additional Information

Cast Faeline stomp, after buff of ancient_teachings is finished, it won't show as the next priority, awakened Faeline and ancient concordance are active.

**Comment by Hekili** [comment]
Can you provide a snapshot of when you'd want Faeline Stomp to be recommended but it isn't?

> Can you add or is there any way to add an option to add priority for Faeline stomp if Ancient_teachings isn't buffed

Why?  Is there a guide or sim that does this?  What's the rationale for it?  Can you provide a reference that explains why you would want to do this?

If it's just a personal preference thing, you could make a custom priority.

**Comment by krispykos** [comment]
where would i put this conditions "Faeline Stomp" based on the presence of the "Ancient Teachings" buff. You want to prioritize using "Faeline Stomp" when the "Ancient Teachings" buff is about to run out.
tried already with from the default action list of Faeline stomp currently ! settings.save_faeline | ! ( buff.ancient_concordance.up | buff.awakened_faeline.up )
added ancient teachings to no avail

my rationale is that ancient_teachings will always be an enhancement because ur adding value by healing players/yourself
the other logic by removing the entry just suggest faeline stomp when it procs but personally don't want that

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by krispykos** [comment]
https://pastebin.com/qpbvXfZ2
See how it prioritizes the faeline stomp reset and not when Ancient_teachings is expired.

**Comment by Hekili** [comment]
> Can you provide a snapshot of when you'd want Faeline Stomp to be recommended but it isn't?
