### ISSUE TITLE
Frostscythe suggested when out of range w/ Exclude Out-of-Range Enabled

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#278]
**Describe the Bug/Issue**
Frostscythe is suggested even when you're out of range of the target and have exclude out-of-range enabled

**To Reproduce**
Take frostscythe talent
Be out of range with exclude out-of-range enabled

**Expected behavior**
Frostscythe to not be suggested when out of range

(side note) - is there some kind of documentation where i can learn the basics of how to write my own priorities in hekili? thank you again for your time

**Comment by Hekili** [comment]
Frostscythe technically doesn't have a range, but I can sort out a workaround.

**Comment by ghost** [comment]
Remorseless Winter is the same way.

Thank you for your continued help!

**Comment by Hekili** [comment]
I'll go ahead and make Remorseless Winter have a range of 7 (i.e., "within 8") so that the range filter will catch if when you use that.
