### ISSUE TITLE
Precombat and target counting

### ISSUE THREAD

**Issue by marekCs** [Hekili/hekili#2780]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello, I'm having quite a problem with the fact that when I want to start a fight, e.g. balance druid, BM hunter, apparently it only applies to ranged and I can clearly see a group of targets in front of me, it still won't recommend the AOE spell, even if I manually put it in the priorities in the precombat, e.g. now Starfall as seen with Balance, or when I tried it with BM hunter. And even when I turn on the "Use Nameplate Detection" option I can see the count on the Hekili icons correctly, but inside the Precombat it pretends it's not (this should be a technical issue I guess).

Proposed solution, allow for precombat spells counting targets what the player actually sees, regardless of options (nameplates, pet, dot detections, etc). Its like enable Nameplates detection for 40 yeards for ranged for precombat only automatically.

### How to Reproduce

1. Enter the game as any ranged dps.
2. Put some aoe spell to precombat at the first position.
3. Try to get it to be recommended by the nameplates you see

### Snapshot (Link)

https://pastebin.com/vQijTT6y

**Comment by marekCs** [comment]
I also made a screenshot where you can see that precombat specifies that starfall should show up (its green true), but the AI doesn't want to promote it. [https://pasteboard.co/Bt2rkx1rJMnl.png](https://pasteboard.co/Bt2rkx1rJMnl.png)

**Comment by marekCs** [comment]
Just checked Balance druid rotation Opener and they don't really have Starfall right at the beginning but e.g. BM multishot makes sense to me.

**Comment by Hekili** [comment]
`1.   starfall ( precombat - 1 ) - ability unknown`

You don't seem to have Starfall talented.

```
talents: BYGAlOfJaEu03UKI2/Mrbr1a+BAAAAAAAAAAAAAAAAAAgCAJJiQSCQSikkAaJkIJKJaSOQI0SKJhIaAUoAQA
    astral_influence = 2/2
    astral_smolder = 2/2
    balance_of_all_things = 1/2
    celestial_alignment = 1/1
    cosmic_rapidity = 2/2
    denizen_of_the_dream = 1/1
    eclipse = 1/1
    frenzied_regeneration = 1/1
    friend_of_the_fae = 1/1
    fury_of_elune = 1/1
    gale_winds = 1/1
    improved_barkskin = 1/1
    improved_stampeding_roar = 1/1
    improved_sunfire = 1/1
    incarnation = 1/1
    incarnation_chosen_of_elune = 1/1
    innervate = 1/1
    ironfur = 1/1
    lycaras_teachings = 3/3
    matted_fur = 1/1
    moonkin_form = 1/1
    natures_balance = 1/1
    natures_grace = 1/1
    natures_vigil = 1/1
    nurturing_instinct = 2/2
    orbit_breaker = 1/1
    power_of_goldrinn = 2/2
    primordial_arcanic_pulsar = 1/1
    radiant_moonlight = 1/1
    rattle_the_stars = 1/1
    rejuvenation = 1/1
    renewal = 1/1
    rising_light_falling_night = 1/1
    shooting_stars = 1/1
    solar_beam = 1/1
    solstice = 1/1
    soothe = 1/1
    soul_of_the_forest = 1/1
    stampeding_roar = 1/1
    starfire = 1/1
    starlord = 2/2
    starsurge = 1/1
    sunfire = 1/1
    thick_hide = 2/2
    twin_moons = 1/1
    typhoon = 1/1
    ursine_vigor = 2/2
    ursols_vortex = 1/1
    verdant_heart = 1/1
    waning_twilight = 2/2
    warrior_of_elune = 1/1
    wild_charge = 1/1
    wild_surges = 1/1
```
