### ISSUE TITLE
[BUG] Light's Hammer @cursor Makes error

### ISSUE THREAD

**Issue by Hanan8564** [Hekili/hekili#2781]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I Get error only @cursor I did try to delete WTF and reinstall of Hekili over and got nothing.

2x Hekili/State.lua:5806: attempt to compare number with function
[string "@Hekili/State.lua"]:5806: in function `QueueEvent'
[string "@Hekili/Dragonflight/PaladinHoly.lua"]:467: in function `hook'
[string "@Hekili/Classes.lua"]:5836: in function `callHook'
[string "@Hekili/Events.lua"]:1577: in function <Hekili/Events.lua:1575>
[string "@Hekili/Events.lua"]:1874: in function `handler'
[string "@Hekili/Events.lua"]:60: in function <Hekili/Events.lua:52>

Locals:
self = <table> {
 swing = <table> {&&&
 }
 FindPlayerAuraByID = <function> defined @Hekili/Utils.lua:516
 summonPet = <function> defined @Hekili/State.lua:1155
 role = <table> {
 }
 IsKnown = <function> defined @Hekili/State.lua:6910
 UnitGUID = <function> defined =[C]:-1
 purge = <table> {
 }
 stat = <table> {
 }
 ptr = 0
 off_hand = <table> {
 }
 floor = <function> defined =[C]:-1
 tonumber = <function> defined =[C]:-1
 SetWhitelist = <function> defined @Hekili/State.lua:6625
 holds = <table> {
 }
 display = "Interrupts"
 prev_off_gcd = <table> {
 }
 SetDefaultVariable = <function> defined @Hekili/State.lua:4430
 mainhand_speed = 1.994000
 channelSpell = <function> defined @Hekili/State.lua:1218
 equipped = <table> {
 }
 gain = <function> defined @Hekili/State.lua:1523
 TimeToReady = <function> defined @Hekili/State.lua:7267
 setStance = <function> defined @Hekili/State.lua:1129
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 UnitAura = <function> defined =[C]:-1
 AddToHistory = <function> defined @Hekili/Events.lua:1021
 SetupCycle = <function> defined @Hekili/State.lua:764
 print = <function> defined @Hekili/State.lua:538
 GetSpellCount = <function> defined =[C]:-1
 ClashOffset = <function> defined @Hekili/State.lua:7484
 azerite = <table> {
 }
 apply_aura = <function> defined @Hekili/Dragonflight/PaladinRetribution.lua:955
 offset = 1.160000
 QueuedCastRemains = <function> defined @Hekili/State.lua:6183
 ApplyCastingAuraFromQueue = <function> defined @Hekili/State.lua:6207
 TargetBuffUp = <function> defined @Hekili/State.lua:5722
 pvptalent = <table> {
 }
 rawGain = <function> defined @Hekili/State.lua:1530
 GetItemGem = <function> defined =[C]:-1
 UnitIsFriend = <function> defined =[C]:-1
 action = <table> {
 }
 addStack = <function> defined @Hekili/State.lua:1003
 HasRequiredResources = <function> defined @Hekili/State.lua:7230
 TargetDebuffUp = <function> defined @Hekili/State.lua:5727
 UnitCanAttack = <function> defined =[C]:-1
 rawSpend = <function> defined @Hekili/State.lua:1543
 script = <table> {
 }
 IsUsable = <function> defined @Hekili/State.lua:7088
 GetItemInfo = <function> defined =[C]:-1
 foj_cost = <function> defined @Hekili/Dragonflight/PaladinRetribution.lua:964
 GetPlayerAuraBySpellID = <function> defined =[C]:-1
 health = <table> {
 }
 IsFiltered = <function> defined @Hekili/State.lua:7053
 cooldown = <table> {
 }
 stance = <table> {
 }
 gcd = <table> {
 }
 empowerment = <table> {
 }
 varDB = <table> {
 }
 ResetQueues = <function> defined @Hekili/State.lua:5975
 auras = <table> {
 }
 GetCycleInfo = <function> defined @Hekili/State.lua:850
 format = <function> defined =[C]:-1
 using_apl = <table> {
 }
 RemoveAuraEvent = <function> defined @Hekili/State.lua:5848
 system = <table> {
 }
 recheckTimes = <table> {
 }
 runHandler = <function> defined @Hekili/State.lua:6290
 recheck = <function> defined @Hekili/State.lua:1586
 GetShapeshiftFormInfo = <function> defined =[C]:-1
 nextOH = 0
 main_hand = <table> {
 }
 IsActiveSpell = <function> defined @Hekili/Utils.lua:573
 GetEventInfo = <function> defined @Hekili/State.lua:5893
 artifact = <table> {
 }
 ceil = <function> defined =[C]:-1
 talent = <table> {
 }
 GetSpellInfo = <function> defined =[C]:-1
 covenant = <table> {
 }
 FindRaidBuffByID = <function> defined @Hekili/Utils.lua:293
 InFlightRemains = <function> defined @Hekili/State.lua:6153
 IsDisabled = <function> defined @Hekili/State.lua:7006
 IsSpellKnownOrOverridesKnown = <function> defined 

### How to Reproduce

1. Holy Paladin Using Macro :

#showtooltip 
/cast [@cursor] Light's Hammer

### Player Information (Link)

build: v10.1.5-1.0.12 level: 70 (70) class: PALADIN spec: holy  talents: BEEAomTTpSA9oX6huYLb5nP3rDAAAQAARAAACQJJFoUik0aIlk4AlIBtiAIJlkESCRKoJJCAIAQBIEJhA     aura_mastery = 1/1     auras_of_the_resolute = 1/1     avenging_wrath = 1/1     avenging_wrath_might = 1/1     awakening = 1/1     awestruck = 1/1     beacon_of_faith = 1/1     beacon_of_the_lightbringer = 1/1     blessing_of_freedom = 1/1     blessing_of_protection = 1/1     blessing_of_sacrifice = 1/1     boundless_salvation = 1/1     breaking_dawn = 1/2     cavalier = 1/1     commanding_light = 1/1     crusaders_reprieve = 1/1     daybreak = 1/1     divine_glimpse = 1/1     divine_purpose = 1/1     divine_resonance = 1/1     divine_revelations = 1/1     divine_steed = 1/1     divine_toll = 1/1     glimmer_of_light = 1/1     glistening_radiance = 1/1     glorious_dawn = 1/1     golden_path = 1/1     greater_judgment = 1/1     hammer_of_wrath = 1/1     hand_of_divinity = 1/1     holy_aegis = 2/2     holy_shock = 1/1     illumination = 1/1     imbued_infusions = 1/1     improved_cleanse = 1/1     judgment_of_light = 1/1     lay_on_hands = 1/1     light_of_dawn = 1/1     lights_conviction = 1/1     lights_hammer = 1/1     lights_protection = 1/1     merciful_auras = 1/1     obduracy = 1/1     of_dusk_and_dawn = 1/1     overflowing_light = 1/1     rebuke = 1/1     reclamation = 1/1     resplendent_light = 1/1     righteous_judgment = 1/1     rising_sunlight = 1/1     sacrifice_of_the_just = 1/1     sanctified_plates = 2/2     seal_of_alacrity = 2/2     seal_of_mercy = 1/1     seal_of_might = 2/2     seal_of_order = 1/1     seasoned_warhorse = 1/1     touch_of_light = 1/1     tyrs_deliverance = 1/1     unbreakable_spirit = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: [emeni]  sets: ominous_chromatic_essence = 1     rashoks_molten_heart = 1     tier30 = 4  gear: allied_wristguard_of_companionship = 1     breastplate_of_arterial_protection = 1     guild_tabard = 1     heartfire_sentinels_faulds = 1     heartfire_sentinels_forgehelm = 1     heartfire_sentinels_protectors = 1     heartfire_sentinels_steelwings = 1     obsidian_seared_hexsword = 1     ominous_chromatic_essence = 1     pristine_magma_stompers = 1     qalashi_defender = 1     rashoks_molten_heart = 1     ringbound_hourglass = 1     seal_of_the_defiant_hordes = 1     shield = 1     signet_of_titanic_insight = 1     tier30 = 4     understone_gorget = 1     undulating_sporecloak = 1  legendaries: none  itemIDs: 134491, 190511, 190526, 192999, 193000, 193771, 193778, 202450, 202451, 202452, 202453, 202577, 202614, 203729, 205025, 206197, 5976  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     enhancedRecheck = false     gcdSync = true     maxTime = 20     nameplateRange = 25     nameplates = false     noFeignedCooldown = false     package = Holy Paladin     petbased = false     potion = potion_of_spectral_intellect     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false  toggles: cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      absolution      = 6   [08]     consecration    = 2   [01]     crusader_strike = 6   [01]     flash_of_light  = 5   [01]     hammer_of_wrath = =   [01]     holy_light      = 9   [01]     holy_shock      = 8   [01]     judgment        = -   [01]     light_of_dawn   = 1   [01]     lights_hammer   = 3   [01]     redemption      = 5   [08]     word_of_glory   = 0   [01]  warnings: none

### Error Messages (Link)

https://pastebin.com/HqdZnLWT

**Comment by Hekili** [comment]
Thanks, this will be resolved in a release this weekend.

**Comment by Hanan8564** [comment]
Thanks a lot !!!
