### ISSUE TITLE
[REC] Provide a short, descriptive title of you Recommendation issue

### ISSUE THREAD

**Issue by comproh** [Hekili/hekili#2783]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

BM rotation; 
USE All charges of barbed shot before using Bestial wrath
The addon isn't doing that. 

### How to Reproduce

Follow bM rotation.

### Snapshot (Link)

https://pastebin.com/ejvXSKcx

### Contact Information

pie.are.squared

**Comment by syrifgit** [comment]
That is not correct for the rotation. You do not always dump every barb before bestial wrath. For single target, you only do this if you don't have 3 stacks.

https://www.icy-veins.com/wow/beast-mastery-hunter-pve-dps-rotation-cooldowns-abilities
