### ISSUE TITLE
Hekili not working/recommending for rogue

### ISSUE THREAD

**Issue by pete543** [Hekili/hekili#2784]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I main sub rogue, and hekili doesn't work for it. It seems to do nothing. My dad plays feral druid and it works for him, yet when he plays his rogue, the same thing happens. I tried resetting multiple times along with uninstalling and reinstalling.

### How to Reproduce

Be a sub/assassination rogue. Possibly outlaw.

### Player Information (Link)

https://pastebin.com/rpHfbtdc

### Error Messages (Link)

there is none

### Additional Information

I use CurseForge for the addon

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by pete543** [comment]
Well there is nothing to snapshot, unless you want me to snapshot the settings. It just doesn't work. There is no recommendation at all, which is the problem

**Comment by Hekili** [comment]
Yes, please follow the process listed above.  Thanks.

**Comment by pete543** [comment]
> * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).

Im sorry, I dont really understand. The instructions say "When you see the recommendation you disagree with..." and then it goes on to say "Select the snapshot that shows the recommendation that you disagree with". The problem is that there is no recommendation. It acts as if it doesn't exist. Also, I don't know what to take a snapshot of. Please help.

**Comment by syrifgit** [comment]
Is it turned off? Right click the minimap icon for the addon and select "enable", or enable it from the main addon settings.

**Comment by pete543** [comment]
It was on

**Comment by Hekili** [comment]
~~When you see the recommendation you disagree with,~~ press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).

Then continue from there.

**Comment by pete543** [comment]
https://pastebin.com/gbGrZ4VW
Here you go

**Comment by pete543** [comment]
sorry I thought snapshot meant screenshot lol

**Comment by Hekili** [comment]
The snapshot shows that it has recommended Instant Poison.  So my initial guesses would be:

1. You've placed your Primary display somewhere that it's covered/hidden/offscreen.
2. You've set the Primary display's Visibility such that it's transparent or not shown.
3. You enabled SpellFlash and its option to hide the display, and then don't see a flash because Instant Poison is tucked behind a flyout button.

Screenshots of your Primary display settings would be helpful here.  In `/hek` > Displays > Primary, screenshot the following tabs:
* Main
* Visibility
* SpellFlash

**Comment by pete543** [comment]
ok I'll do that. thanks!

**Comment by Gamemaster322** [comment]
![WoWScrnShot_082923_123221](https://github.com/Hekili/hekili/assets/62951871/88582c25-e257-49a2-8d15-8a3efd1271c5)
![WoWScrnShot_082923_123236](https://github.com/Hekili/hekili/assets/62951871/2186e01d-00cb-404d-8fae-eaf9f66a275d)
![WoWScrnShot_082923_123245](https://github.com/Hekili/hekili/assets/62951871/342093b9-2935-41c7-aeed-b77d6c90de75)

**Comment by Hekili** [comment]
On your SpellFlash tab, you have "Hide Display" checked.  This means you're relying ONLY on SpellFlash; if Instant Poison isn't on your bars somewhere, there's nowhere for it to flash.

**Comment by pete543** [comment]
ok ill check it, thanks!

**Comment by pete543** [comment]
I put instant poison on my bars, but it still wont flash, heres a screenshot:
![WoWScrnShot_082923_125151](https://github.com/Hekili/hekili/assets/62951871/7eab0674-03a8-475d-82d9-b5093c540a17)

**Comment by syrifgit** [comment]
You had it set to combat only, as well. It should work if you go smack a target dummy (might even work if you just target it?)

**Comment by pete543** [comment]
I actually did damage the target, still didnt work

**Comment by pete543** [comment]
Thank you guys for the help! I actually got it to work, just had to put some poisons on my bars.
