### ISSUE TITLE
[REC] Ignore Pain not being suggested

### ISSUE THREAD

**Issue by Lejes9X** [Hekili/hekili#2787]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Ignore pain is not suggested in rotation for Protection Warrior.

### How to Reproduce

1. Protection Warrior.
2. Build up enough energy without Ignore pain active.
3. Does not suggest Ignore pain.

### Snapshot (Link)

N/A

### Contact Information

Lejes9X

**Comment by Hekili** [comment]
Sorry, the ticket was not filled out completed.  It's likely your Defensive abilities are toggled off, but I can only guess without the required information.
