### ISSUE TITLE
The automatic snapshot was during the BDK rotati

### ISSUE THREAD

**Issue by nechyu** [Hekili/hekili#2789]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Was in M+, during rotation on boss I got a message about automatic Snapshot on BDK. The rotation stopped showing, only reloading the interface helped.

### How to Reproduce

BDK specialisation.
Go to Underrot M+.
On the boss Unbound Abomination and did in time auto snapshot rotation.

### Snapshot (Link)

https://pastebin.com/qrtYZXkg

**Comment by Hekili** [comment]
This occurred because [Afflicted Cry](https://www.wowhead.com/spell=409492/afflicted-cry) went off, reducing your Haste by 100%, making your Rune regeneration rate so low that there wasn't a button that the addon could recommend.
