### ISSUE TITLE
Outlaw bug with Detection abil

### ISSUE THREAD

**Issue by antrikos** [Hekili/hekili#279]
Hello 
After the last updates on outlaw spec there is a bug on the rotation and everytime u press an abillity the addon adds the rogues "Detection" abillity 
Here is a print screen 
https://imgur.com/7nUdcep

**Comment by Hekili** [comment]
It's not a bug.  Using Detection as filler procs some Corruption effects.  It's dumb, but it's DPS.

**Comment by antrikos** [comment]
hmm ok but is not doing the same on Assassination spec )

**Comment by Hekili** [comment]
Then you're probably not using the latest release of the addon.  But I can't tell because you didn't include the info in your ticket.  :)

**Comment by antrikos** [comment]
v8.3.0-04-08

**Comment by Hekili** [comment]
I'm assuming you're using different weapons in Assassination spec than in Outlaw.  The condition for Detection checks for Echoing Void.  Do you have EV as Assassination?

**Comment by antrikos** [comment]
As outlaw I am using double Follys and as  Assassination double daggers, 
Yes i am using echoing as assassination too

**Comment by Hekili** [comment]
Go ahead and post a snapshot (see original ticket instructions) for your Assassination spec then.
