### ISSUE TITLE
Missing Ability - Shadow Priest: Mindbender

### ISSUE THREAD

**Issue by sandmaansam** [Hekili/hekili#2791]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Under abilities MIndbender is missing from the drop down list

### How to Reproduce

Ability is just missing

### Snapshot (Link)

https://pastebin.com/UEUTBS81

### Contact Information

dark8768

**Comment by Hekili** [comment]
Hi; it's not really missing.  Shadowfiend and Mindbender are used interchangeably in SimC and the addon.

If you need to differentiate their usage, you'd check for `talent.mindbender.enabled` in the conditions.
