### ISSUE TITLE
Ability Keybind text profiles

### ISSUE THREAD

**Issue by sandmaansam** [Hekili/hekili#2792]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Appreciate the current feature that allows you to change the key bindings displayed on the Hekili rotation bar. However, I wish I didn't have to manually adjust it for each character and specialization. Instead, I would prefer the ability to set what appears in specific positions on my action bar.

For instance, it would be great to designate Action Bar 2 for slots 10 through 19 for every character, so I wouldn't have to customize each ability individually.

I'm requesting this because I use a one-handed keyboard with numbers 1-20, and I'd like the Hekili visual rotation to match my keyboard layout. I am aware that you can manually change this, but having a profile that applies to all accounts would be much more convenient. It would save me from changing these keys on each specific ability repeatedly, and if I decided to move a new ability into the action bar, it would automatically recognize the new key assignment. Thus, I wouldn't need to manually adjust other abilities to remove that key assignment.

### Contact Information

dark8768

**Comment by sandmaansam** [comment]
also being able to re-color the Keybind text would be pretty cool to match it to rgb on keyboard

**Comment by Hekili** [comment]
Hi,

I don't plan to implement this.  If the detected keybindings don't match your actual bindings, that's generally an issue of setting up buttons/bars inconsistent with the layout of the base UI.  When that occurs, the solution is to manually set the text as you know.

I don't want to create a second workaround for the same problem.  If I put more work into bindings, it will be to improve upon keybinding detection as-is.
