### ISSUE TITLE
Can't make hekili suggest Refreshing Healing Potion.

### ISSUE THREAD

**Issue by Pugtank** [Hekili/hekili#2793]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

So I'm trying to make Hekili suggest Refreshing Healing Potion when I'm below 90% hp.
I've tried to add a condition for it, but it keeps suggesting another potion upon reaching the hp threshold (90% in this case for testing purposes).
![image](https://github.com/Hekili/hekili/assets/61908478/9e457fc3-b8f5-433b-b22c-910be92830fe)
<img width="241" alt="image" src="https://github.com/Hekili/hekili/assets/61908478/43c84036-b7b3-4c11-a628-62591814e35a">
![image](https://github.com/Hekili/hekili/assets/61908478/9e408cac-fd2f-4351-b2cf-b289e01d743b)

I can't seem to change which potion it suggest.

For reference: I'm playing guardian druid.

### How to Reproduce

Enter the game as Guardian Druid.

Open Hekili 

Go to Priorities -> Guardian

Click "Action Lists" 

Choose "mitigation" from the dropdown menu

Add Entry (and make sure it's 'enabled')

Click "Action" dropdown menu and select [Potion]

In "Conditions" text field input: cooldown.refreshing_healing_potion.remains = 0 & health.pct < 90

Close Hekili

Take 10% damage and see Hekili suggest a different potion

### Snapshot (Link)

https://pastebin.com/ffvGrCxN

### Contact Information

puggiewuggie

**Comment by Hekili** [comment]
That's correct; the Potion ability is for DPS potions.
