### ISSUE TITLE
[REC] [WOTLK] Unholy DK needs new priorities to reflect its emerging DW SS Gargoyle spec

### ISSUE THREAD

**Issue by dookmaster5000** [Hekili/hekili#2794]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hey folks, peaked at the tickets before submitting.  Sorry if this sounds eerily similar to https://github.com/Hekili/hekili/issues/1640 but with the advent of synergies between: 

Desolation ( https://www.wowhead.com/wotlk/spell=66803 )
The proc from Sigil of Virulence ( https://www.wowhead.com/wotlk/spell=67384 )
The 2p proc from T9 ( https://www.wowhead.com/wotlk/spell=67115 )
And fallen crusader procs ( https://www.wowhead.com/wotlk/spell=53365 )

This has led to an entirely revamped rotation that aims to have as much Attack Power as possible before using Summon Gargoyle.  After nerfs, Summon Gargoyle ( https://www.wowhead.com/wotlk/spell=49206 ) No longer snapshots our haste rating, but still snapshots our AP.  This has led to us wanting to use racials, items, and trinkets that give AP before Summon Gargyole, while reserving haste boosting racials, items, ect until after our Gargoyle has been summoned.

This changed rotation now has a static opener of
precombat check to see if pet is summoned, Bone Shield buff is up and currently active presence is set to unholy
If pull timer is being used
-8s cast Ghoul Frenzy
-1.5s cast Horn of Winter
-1.0s use Potion of Speed
Combat Starts
Icy Touch > Plague Strike > Blood Strike > Scourge Strike > Blood Strike > Blood Tap > Ghoul Frenzy > activate all AP boosters > Summon Gargoyle > Empower Rune Weapon > Death and Decay > activate all haste boosters > Army of the Dead > Icy Touch > Plague Strike > Blood Boil > Blood Presence after gargoyle leaves 

After the opener, the rotation falls back to a typical APL priority list with some minor caveats.
Blood Tap is typically reserved to be exclusively used with Ghoul Frenzy
Death and Decay is worth using even in single target
Pestilence is worth using when set to Single Target if active enemies are greater than 1 due to wandering plague ( https://www.wowhead.com/wotlk/spell=49655 ) even if pestilence no longer refreshes main target
Typical Glyph builds forgo Glyph of pestilence ( https://www.wowhead.com/wotlk/spell=64267/ )
Blood Boil is worth recommending in ST if Death and Decay's CD is 6 seconds or longer, or Empower Rune Weapon is able to be cast. 

Rotation Breakdown: https://wowtbc.gg/wotlk/class-guides/unholy-death-knight/
APL conditionals: https://wowsims.github.io/wotlk/deathknight/ (Rotation tab > Unholy DW SS APL from Saved Rotations)
Direct Sims: https://github.com/wowsims/wotlk/releases

I hope this is a useful contribution.

 

### How to Reproduce

N/A - request for renewed priorities

### Snapshot (Link)

https://pastebin.com/Ad2VuaRN

### Contact Information

sparkledooks (discord)

**Comment by Hekili** [comment]
Thanks for the resources.  I'll look into it.

**Comment by marknl** [comment]
I've tried to create this in the addon. It's quite tricky and I don't have any reference documentation to make a proper implementation.

Thank you for taking the time to implement this! Love to see this included in Hekili.
