### ISSUE TITLE
Feral Druid - Want to see Barkskin and Demoralizing Roar

### ISSUE THREAD

**Issue by marnixxx** [Hekili/hekili#2795]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello friends,

I want to see Barkskin and Demoralizing Roar within the normal Automatic Display. I toggled the Defensives on and under "Druid - Toggles - Defensives" both Skills are added.
Under Abilities both abilities are not disabled and not set up to boss only. Both set to req. toggle: Defensives

I dont get these both skills to show up in the rotation helper... Am i doing something wrong?

### How to Reproduce

Enter game as Feral Druid and try to set up Barkskin and Demoralizing Roar

### Snapshot (Link)

https://pastebin.com/hp9A89Db

**Comment by Hekili** [comment]
Toggles control whether abilities that are in the priority list can be shown.  Barkskin and Demoralizing Roar are not in the priority by default.

The [wiki](https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#how-do-i-make-the-addon-recommend-x-when-y) may help you to customize your priority to include Barkskin or Demoralizing Roar.
