### ISSUE TITLE
Hekili not showing anything on my Mage(WOTLK)

### ISSUE THREAD

**Issue by Warmonger66** [Hekili/hekili#2796]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Isnt working on Mage, but on Dk working very well.

### How to Reproduce

I tried with another Mage class and have the same problem.

### Player Information (Link)

build: v3.4.2-1.0.0 level: 70 (70) class: MAGE spec: mage  talents: none  pvptalents: none  covenant: none  conduits: none  soulbinds: none  sets: none  gear: belt_of_blasting = 1     boots_of_foretelling = 1     brutal_gladiators_battle_staff = 1     brutal_gladiators_silk_amice = 1     brutal_gladiators_silk_cowl = 1     brutal_gladiators_silk_handguards = 1     brutal_gladiators_silk_raiment = 1     brutal_gladiators_silk_trousers = 1     brutal_gladiators_touch_of_defeat = 1     collective_stone_of_wisdom = 1     guardians_band_of_dominance = 1     guardians_pendant_of_reprieve = 1     guardians_silk_cuffs = 1     mainhand = 1     mainhand_2h = 1     signet_of_swift_judgment = 1     timbals_focusing_crystal = 1     volanthius_shroud = 1  legendaries: none  itemIDs: 199529, 28517, 30038, 34470, 34987, 35096, 35097, 35098, 35099, 35100, 35107, 35129, 35179, 37929, 38220, 44429  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = false     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcd = 1459     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     petbased = false     potion = prolonged_power     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     usePackSelector = true  toggles:     cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = aoe      potions = false   keybinds:      arcane_brilliance     = SF  [06]     arcane_explosion      = E   [02], SR  [06]     arcane_intellect      = S2  [06]     berserking            = 9   [02]     blink                 = 0   [01], 0   [02]     blizzard              = F5  [06]     combustion            = S3  [06]     counterspell          = SE  [06]     evocation             = S4  [06]     fire_blast            = 2   [01], 3   [02]     fire_ward             = SPADDUp[05]     fireball              = 4   [01], -   [02]     flamestrike           = SPADDRIGHT[05]     frost_nova            = R   [01], R   [02]     ice_block             = M3  [06]     invisibility          = SM3 [06]     mana_shield           = SQ  [06]     molten_armor          = S1  [06]     polymorph             = T   [05]     remove_curse          = CSPADDRIGHT[05]     ritual_of_refreshment = CPADDLEFT[05]     scorch                = 1   [01], 2   [02], CSPADDUp[05]     slow_fall             = CAPS[06]     spellsteal            = =   [02], SPADDLEFT[05]

### Error Messages (Link)

no massage

**Comment by Hekili** [comment]
Yup, not yet implemented.  There's an open ticket already.
