### ISSUE TITLE
[REC] sin rogue recommending vanish in opener with Sepsis

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2797]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon is recommending using vanish in opener when its not recommended in either guides or simulation craft itself.

### How to Reproduce

1. Use default ST raid build - BMQAAAAAAAAAAAAAAAAAAAAAAIFJSCiElEAAAAAAAJAkkAAAAAAAQDJOQJJkkkkWKJikQCRiFE
2. Follow rotation until after Sepsis empowered garrotte is recommended
3. Addon will recommend a vanish garrote but simc does not recommend it

### Snapshot (Link)

https://pastebin.com/rhVq9yXQ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/g5FLMri7CWLDK7notsQshM

**Comment by Hekili** [comment]
Pretty sure this is just because Training Dummies break snapshotting because they're weird.  Does this happen in actual fights?  If so, can you provide a snapshot there?

**Comment by fzarr** [comment]
Does also happen in normal fights, see here: https://pastebin.com/WCrKU6tR

Interestingly it doesn't seem to appear in the upcoming recommendations until the sepsis empowered garotte recommendation is used. You can see the sepsis empowered garotte recommendation in this pastebin without any vanish shown in the next recommendations

https://pastebin.com/gmQXgiJz

Once i press garotte, then the vanish garotte appears as in the previous pastebins.

**Comment by fzarr** [comment]
Something to note: if I ignore the vanish action, vanish will eventually be not recommended after a few globals, however the addon is still recommending a garotte even though it should be waiting until the initial empowered garotte is in pandemic range and/or the sepsis buff is about to wear off. https://pastebin.com/py22C8J5

I'm sure you're already aware but the sepsis buff has two components, one 10 second buff while sepsis is applied, and then another 10 second buff when the sepsis dot expires. The simc recommendation is to apply the first sepsis-empowered garotte at around 6 seconds after pressing sepsis, and the second sepsis-empowered garotte at 19 seconds, pandemic-ing the current empowered garottee while still in the sepsis stealth window.

Might be worth noting too that even if I have vanish ability explicitly turned off in the addon options, it still recommends vanish.

**Comment by Hekili** [comment]
Thanks for the snapshots and additional detail.  Empowering Garrote via Sepsis isn't really clear from the spell data so I had overlooked it.  It'll be in today's release.
