### ISSUE TITLE
Crash Lightning

### ISSUE THREAD

**Issue by Sweetcorp** [Hekili/hekili#280]
Hello! I wanted to post this here since it didn’t seem like a bug, just a question I wanted to clear up. Is crash lightning supposed to be part of single target rotation without the crashing storm talent? It has been suggesting since most recent update. Just wanted to clarify before I made a bug report. I also looked around to see if someone else had posted it. Please forgive me if I am not doing this right. First time poster.

Thanks for the help!!

**Comment by Hekili** [comment]
Not a bug.  You'll see it at low Maelstrom when you can't push something more useful.  Not an actual priority change.

**Comment by Sweetcorp** [comment]
Thank you very much!
