### ISSUE TITLE
Rotation issue with Balance druid "incarn COE" wont go away

### ISSUE THREAD

**Issue by kratospwn** [Hekili/hekili#2800]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

balance druid: doing the rotation however once using the spell incarn will come back and stay as 1st of the spell till cd again and then come back up. idk how i got the snapshot when i got the one i put in snapshot link but the one i screenshot was the issue i was having 

### How to Reproduce

play any druid tree under balance as long incarn is selected and it will show once started ur rotation. 
![incarn](https://github.com/Hekili/hekili/assets/145059930/b7eed764-816f-46ce-ac04-354bb6255544)

### Snapshot (Link)

Balance; Primary - Sunfire(0.00), Moonfire(1.13), Incarnation: Chosen of Elune(2.26)

**Comment by Hekili** [comment]
Hey, sorry for the slow response.  I need a proper and complete snapshot.  I can't replicate this on my druid.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by chicnstu15** [comment]
having the same issue as guy above.

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Foraga88** [comment]
I am also having this issue. Pastebin link to the snapshot below

https://pastebin.com/7guXhdwL

**Comment by Hekili** [comment]
@Foraga88 Thanks for the snapshot.  I'm still struggling to replicate the issue.  I think the additional details I need at this point:

1. Screenshot of the Incarnation recommendation occurring while Incarnation is on CD.
2. Output from macro:<br/>`/run local s = Hekili.State; s.reset(); print( s.action.incarnation.id, s.action.incarnation.ready, s.action.incarnation.ready_time, s.cooldown.incarnation.remains )`
3. Output from macro:<br/>`/run print( GetSpellInfo( "Incarnation: Chosen of Elune" )`
4. Output from macro (while Incarnation is on CD):<br/>`/run print( GetSpellCooldown( "Incarnation: Chosen of Elune" )`

Does this happen for you 100% of the time?  Or only in combat or after something else occurs?  Thanks!

**Comment by Nopsu** [comment]
Happens to me as feral (In raids, every boss) and guardian(m+) too, installed the version from 21.9. as only way to stop it so far. Can get snapshots later when it's not hampering my raiding. Have tried with different talent builds and I'm a night elf.

**Comment by Nopsu** [comment]
> A snapshot is required to diagnose this issue.
> ## Snapshot
> 
> Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.
> 
>     * Log into your WoW character.
> 
>     * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
> 
>     * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
>       
>       * You can change these keybindings in /hekili > Toggles if needed.
>       * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
> 
>     * Type /hekili and press Enter.
> 
>     * Open the Snapshots section on the left side.
> 
>     * Select the snapshot that shows the recommendation that you disagree with.
>       
>       * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
> 
>     * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
> 
>     * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
> 
>     * Provide the Pastebin _**link**_ in a new comment.
> 
> 
> This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems. If you do not provide this information, I cannot triage your problem.

https://pastebin.com/zG1fcxtj Here is a snapshot _(I logged in, re-specced Balance from resto and hit training dummies until my incarnation ended and was on cooldown)_



> @Foraga88 Thanks for the snapshot. I'm still struggling to replicate the issue. I think the additional details I need at this point:
> 
>     1. Screenshot of the Incarnation recommendation occurring while Incarnation is on CD.
> 
>     2. Output from macro:`/run local s = Hekili.State; s.reset(); print( s.action.incarnation.id, s.action.incarnation.ready, s.action.incarnation.ready_time, s.cooldown.incarnation.remains )`
> 
>     3. Output from macro:`/run print( GetSpellInfo( "Incarnation: Chosen of Elune" )`
> 
>     4. Output from macro (while Incarnation is on CD):`/run print( GetSpellCooldown( "Incarnation: Chosen of Elune" )`
> 
> 
> Does this happen for you 100% of the time? Or only in combat or after something else occurs? Thanks!

1. https://imgur.com/a/U6N2XMf screenshot, happens as incarnation is about to end.
2. output is: `102560 true 0 0`
(doesnt change if spell is on cooldown or not)

_Your macro is missing ')' in the end for 3 and 4 btw_

3.  `Incarnation: Chosen of Elune nil 571786 0 0 0 102560 571586`
4.  `368519.684 180 1 1`


It does NOT happen all the time, It happens on cat and bear too. Reloading did not help but re-logging in current specialization worked when I tested it. 

After testing changing specs, relogging few times and changing talents aroung; **I could reproduce this issue** by logging out in resto spec (also tried as convoke cat but it did not make issues after respeccing to inca boomie), logging back in and then speccing into a non-resto spec with Incarnation selected.

**Comment by Hekili** [comment]
> I could reproduce this issue by logging out in resto spec (also tried as convoke cat but it did not make issues after respeccing to inca boomie), logging back in and then speccing into a non-resto spec with Incarnation selected.

Thanks, I can replicate this scenario as well.  I am testing a solution now.

**Comment by zonearc** [comment]
![image](https://github.com/Hekili/hekili/assets/47988564/b4943d31-0fa9-4aa9-9963-374f07d55886)
Constantly happens. See screenshot to see how it locks the incarnation in the first spot even though it's still on CD. 
Will not happen on quest mobs or target dummies, but for some reason it happens in EVERY MYTHIC I do, period. 
I went back a dozen versions and it doesn' thappen, Seems to happen on GA/Beta and current alpha.

**Comment by Hekili** [comment]
@zonearc Does it happen before you've swapped between specializations after reloading your UI?
