### ISSUE TITLE
Guardian Druid rotation issue

### ISSUE THREAD

**Issue by Sylvanas714** [Hekili/hekili#2801]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

for my Guardian Druid , during the Incarn the  addon recommend moonfire and raze as spender while keeping one stack of ironfur , which is not right we should do instead during the Incarn spam Mangle -> Thrash -> Ironfur -> Mangle -> Thrash -> Ironfur untill we have 5 stacks of Thrash then we use Raze while keeping our Ironfur rolling from 5 to 6 stacks and its not worth casting moonfire during the Incarn its a waste of gcd and outside Incarn its not worth casting moonfire on more than 3 targets  its also dps gain to cast so many Ironfur during Incarn because we get benfit from Throns of Iron talent see this video for more details : https://www.youtube.com/watch?v=MfaLG3LD33o&t=571s

### How to Reproduce

1. Enter game as a Guardian Druid 
2. Take the Incarn , Throns of Iron talents 
3. use Incarn
4. see recommendations

### Snapshot (Link)

https://pastebin.com/xk30unUZ

### Contact Information

cheetah3182

**Comment by aaronlilla** [comment]
i also have found it to be not correct at all when taking thorns of iron

**Comment by Hekili** [comment]
> we should do instead during the Incarn spam Mangle -> Thrash -> Ironfur -> Mangle -> Thrash -> Ironfur untill we have 5 stacks of Thrash then we use Raze while keeping our Ironfur rolling from 5 to 6 stacks

The SimC profile isn't presently written this way, which is what the addon follows.  I may add some options to specify how many IF stacks to aim for during Berserk/Incarn vs. outside of CDs.  The priority itself just cares that Ironfur is up, not that it has been stacked.

> its not worth casting moonfire during the Incarn its a waste of gcd and outside Incarn its not worth casting moonfire on more than 3 targets its also dps gain to cast so many Ironfur during Incarn because we get benfit from Throns of Iron

If you go to /hekili > Priorities > Guardian > Action Lists > `bear` > #2 and `Show Modifiers`, you can put a `3` in the `Max Cycle Targets` box and the high priority Moonfire will be limited to 3 targets.  I'd have to do some sims to verify that the DPS output is as you expect before making it a change within the addon itself.

**Comment by Sylvanas714** [comment]
> > we should do instead during the Incarn spam Mangle -> Thrash -> Ironfur -> Mangle -> Thrash -> Ironfur untill we have 5 stacks of Thrash then we use Raze while keeping our Ironfur rolling from 5 to 6 stacks
> 
> The SimC profile isn't presently written this way, which is what the addon follows. I may add some options to specify how many IF stacks to aim for during Berserk/Incarn vs. outside of CDs. The priority itself just cares that Ironfur is up, not that it has been stacked.
> 
yea please that could be helpful to have an optition to specify how many IF stack inside Incarn and also outside Incarn cause  doing +20 not like doing +5 keys the trash hits hard at higher keys
> > its not worth casting moonfire during the Incarn its a waste of gcd and outside Incarn its not worth casting moonfire on more than 3 targets its also dps gain to cast so many Ironfur during Incarn because we get benfit from Throns of Iron
> 
> If you go to /hekili > Priorities > Guardian > Action Lists > `bear` > #2 and `Show Modifiers`, you can put a `3` in the `Max Cycle Targets` box and the high priority Moonfire will be limited to 3 targets. I'd have to do some sims to verify that the DPS output is as you expect before making it a change within the addon itself.

thanks for that tip

**Comment by SUU09** [comment]
It would be great to add an option for IF stacks
