### ISSUE TITLE
Feral Shadowmeld Issues

### ISSUE THREAD

**Issue by Grayfox2325** [Hekili/hekili#2804]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Having some inconsistent issues with the recommendation immediately following Shadowmeld. I've seen Ferocious Bite, Brutal Slash, Regrowth, Trinkets (Dragonfire Bomb Dispenser) all be recommended immediately following Shadowmeld. Rake is the only thing that should ever be recommended following Shadowmeld.

I have one snapshot of a Brutal Slash recommendation after Shadowmeld, will keep trying to get snapshots of the others but doesn't seem easy to reproduce outside raid.

### How to Reproduce

Likely need Brutal Slash & Bloodtalons talented. The Brutal Slash after Shadowmeld was seen on a single target dummy.

### Snapshot (Link)

https://pastebin.com/cdhuUEAL

**Comment by Grayfox2325** [comment]
Looks like Prowl runs into the same issue, inconsistently recommending actions other than Rake immediately following it. Whenever I pause to get a snapshot, prowl disappears from the windows. Legit hardest thing to get a snapshot of.

**Comment by Hekili** [comment]
I have a test adjustment to the priority so that Shadowmeld/Prowl won't be recommended unless you're going to use Rake on your current target *or* you have target-cycling enabled and there's another target missing Rake.
