### ISSUE TITLE
Hekili does not show for boosted character

### ISSUE THREAD

**Issue by thelitsune** [Hekili/hekili#2807]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [ ] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have a mage i boosted to level 70 with a wow token. All my other characters have no issue with hekili. It works flawlessly. For my level 70 mage though nothing shows up. I have uninstalled, reinstalled, reset profile, checked if everything is enabled and so far nothing has worked! When i used bugsack and buggrabber there were no error messages as to why it was not loading so I removed them. This is happening on boosted to level 70 characters. Maybe its because hekili was installed before i boosted that character and maybe it just assumes the character is still level 1 or something? idk. It has been very weird. Any help on this issue would be greatly appreciated. Thanks!

### How to Reproduce

Enter game as any class with hekili already installed
Use a boost token to automatically make the character level 70
Hekili will never work because it acts like you have no talents or anything

### Player Information (Link)

https://pastebin.com/R4xLcnnC

### Error Messages (Link)

n/a - bagnon is only bug showing

### Contact Information

lewdkitsune

**Comment by Hekili** [comment]
Mage is not yet supported in Wrath.

**Comment by thelitsune** [comment]
Wait mage isn’t supported!?!?! Wow that’s wild but thanks for letting me know! Alexandria sent this message. iPhone sent the typos.On Sep 22, 2023, at 2:04 PM, Hekili ***@***.***> wrote:﻿
Mage is not yet supported in Wrath.
