### ISSUE TITLE
[FEATURE] Allow Trinket Macros to show Spellflash

### ISSUE THREAD

**Issue by Xarano-GIT** [Hekili/hekili#2808]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I use trinket macros like the below:
```
#showtooltip
/use 13
```
This allows me to have these two macros on my bar so I don't have to manually drag new trinkets when I get a new one.
The problem is that Hekili does not highlight them when using these.

### Contact Information

Xarano (Discord)

**Comment by syrifgit** [comment]
As a short term solution, have you tried forcing a keybind for your trinkets in Hekili? That might make it work.

Under the gear Section, go to the trinkets you use and add the keybind manually for where you have that trinket. Does it make spellflash work?

**Comment by Xarano-GIT** [comment]
Hi there,

I tried overriding the keybind on the trinket as suggested, however it did not make a difference unfortunately.

I would assume the issue is that the macro is pointing to a gear slot and not a specific item name, so the addon does not know specifically that the macro is referencing a trinket?

**Comment by Hekili** [comment]
This is purely SpellFlash functionality, and SpellFlash doesn't have an active maintainer that I know of.
