### ISSUE TITLE
[BUG] ADDON_ACTION_FORBIDDEN

### ISSUE THREAD

**Issue by PARADOX070** [Hekili/hekili#2809]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Pretty much standing still doing nothing in Valdrakken occasionally this pops up:

 "1x [ADDON_ACTION_FORBIDDEN] AddOn 'Hekili' tried to call the protected function '(for generator)()'.
Debugstack was nil."

### How to Reproduce

See above.

### Player Information (Link)

See above very small error.

### Error Messages (Link)

See above very small error.

**Comment by Hekili** [comment]
This is an issue in WoW itself; have to wait for their fix.
