### ISSUE TITLE
Firemage still have issue in priority!

### ISSUE THREAD

**Issue by slipkorn20** [Hekili/hekili#2810]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I have been using Hekili for many years, currently, fire mage have a priority issue, it often gets stuck on the first spell like Phoenixflames and stays too long, and dont changing priority, I tested other classes as well and it happens on Firemage!

### How to Reproduce

Firemage

### Snapshot (Link)

https://pastebin.com/hvc3LhzA

**Comment by Hekili** [comment]
Another fix will be in 1.0.4 which may address this.
