### ISSUE TITLE
Frost DK and Mirror of Fractured Tomorrows never recommended.

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2811]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Mirror of Fractured Tomorrows will never get recommended for my Frost DK. Swapped slots and no luck. 

### How to Reproduce

1. Frost DK
2. 5 Target dummies 
3. Go through opener rotation
4. Trinket not recommended

### Snapshot (Link)

https://pastebin.com/X6iqR7Qy

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mHdH5jufZYsYZDa3JmHLe9

### Additional Information

![image](https://github.com/Hekili/hekili/assets/25187247/286e5480-ef39-41f9-871d-82cb56d48fd8)

**Comment by Hekili** [comment]
According to your configuration, you have Cooldowns shown separately.  You would need to provide a snapshot of the Cooldowns display to get an explanation of why it was ruled out.  Thanks!

**Comment by Bingo176** [comment]
https://pastebin.com/xL3FfPNZ 1 ability used
https://pastebin.com/hAYbATrh Few seconds in combat

**Comment by Hekili** [comment]
Thanks, these are helpful.  There's a trinket `cast_time` expression that's not being translated.  I'll address it.

**Comment by Hekili** [comment]
This will be resolved in today's release (1.0.4).
