### ISSUE TITLE
Purple book

### ISSUE THREAD

**Issue by BarterClub** [Hekili/hekili#2812]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When getting to level 40 i started to get a purple book in my rotation with no key binding. 

### How to Reproduce

Level 40 mage frost. Unsure how to reproduce as it's consistent. 

### Player Information (Link)

Pastebin.com/EVDt4f4Y

### Error Messages (Link)

None

### Additional Information

I can get more info. Just unsure if it's a bug or something else. 

### Contact Information

Barterclub0001

**Comment by Hekili** [comment]
Probably your trinket.

**Comment by BarterClub** [comment]
> Probably your trinket.

You are correct. Wish it would tell me what is in my rotation so I can find some things that are hidden like that.

**Comment by Hekili** [comment]
What sort of visual distinguisher do you think would work best to communicate that it is a trinket?  I've been trying to decide.

* A little armor icon?
* A little armor icon only if it doesn't have a keybind detected?
* A colored border or frame of some sort?
* Some kind of jewel?
* The word TRINKET scrolling across the whole screen like a 1998 Geocities marquee tag?

In all seriousness, what would you recommend?
