### ISSUE TITLE
[REC] active_dot.glimmer_of_light is not accurately calculated

### ISSUE THREAD

**Issue by elliottabirch** [Hekili/hekili#2816]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

when using glimmer of light or divine toll, the active_dot.glimmer_of_light value is never increased. it remains at 0 permanently. 

### How to Reproduce

enter game as a holy paladin. 
check the values in the profile editor, and type `active_dot.glimmer_of_light` in the box
attack something with holy_shock or divine_toll
see that the value has not been updated

### Snapshot (Link)

https://pastebin.com/hizdtg6s

### Contact Information

baldnbeautiful

**Comment by Hekili** [comment]
active_dot.glimmer_of_light should count Glimmer on enemies and allies in 10.1.7-1.0.5.

If it doesn't, you may want to adjust your custom priority there to use the correct syntax (`&` rather than `and`), as the errors generated may have an impact as well.
