### ISSUE TITLE
Recommend othere skills based on heath 

### ISSUE THREAD

**Issue by Russman99** [Hekili/hekili#2817]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

So I play protection paladin and I know that there is a slider for some skills to be recommended at a specific health but I want to be able to add other skills to be recommended at a specific health as well not just the base skill the class comes with

### Additional Information

For example I have a trinket the gives me shield but it tends to recommend it when I'm at full health 

### Contact Information

russman3324

**Comment by Hekili** [comment]
If you add the trinket to your priority, then its default usage (via the "Use Items" entry) will turn off and it will follow whatever criteria you provide.  If the trinket exists in the priority itself -- you'll need to look -- then you can add/modify its conditions to account for your health percent or health deficit.

The [FAQ](https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions) provides guidance about recommending an ability based on health.

**Comment by Russman99** [comment]
So I added the trinket with the code health.pct >60 and it still suggests
it above 60 percent health what am I doing wrong?

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Russman99** [comment]
Hey sorry to bother you again but the sentinel ability for prot pally
doesn't exist and was wondering if you could add it thx
