### ISSUE TITLE
Missing PVP Talents in the action list.

### ISSUE THREAD

**Issue by PvpSpells** [Hekili/hekili#2818]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As the title suggest, I've noticed some of the PVP talents that are missing from the action list. I realize that Hekili doesn't support PVP by default. I've recently started using it in Arenas, of course with some defensive tweaks, and it works very well.

Missing Spells: 

1) Shaman (added in 10.1.0) (any spec) : https://www.wowhead.com/spell=411370/burrow   

2) Priest (Shadow) : https://www.wowhead.com/spell=211522/psyfiend

--
I will add more spells here if I encounter them on different specs, in case this topic won't be closed.

Thank you.

### How to Reproduce

1. Enter the game as shaman(any spec)/shadow priest
2. Go to action list
3. You will see that those spells are missing

### Snapshot (Link)

https://pastebin.com

### Contact Information

!ZigZag#3424

**Comment by Hekili** [comment]
Burrow and Psyfiend will be available in the next release.
