### ISSUE TITLE
Earth Elemental is possibly bugged for Enhancement Shaman

### ISSUE THREAD

**Issue by PvpSpells** [Hekili/hekili#2819]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I added Earth Elemental (for Enhance shaman) to be suggested at `Health.pct < 70%`, but it's never being suggested no matter what.
The snapshot says:" The action (earth_elemental) is unusable at (0.00 + 0.00) because DPS elementals must be on CD first." but as enhancement shaman you do not have any DPS elemental.

### How to Reproduce

1. Enter the game as Enhancement Shaman
2. Add a condition for Earth Elemental to be suggested at `Health.pct < HP%`  (by default it's in the "Single" action list, u might wanna move it up)
3. Take some damage from Dummy so ur HP falls below threshold
4. Take a snapshot
5. You will see that it says: "The action (earth_elemental) is unusable at (0.00 + 0.00) because DPS elementals must be on CD first."

### Snapshot (Link)

https://pastebin.com/jJML9SP8

### Contact Information

!ZigZag#3424

**Comment by Hekili** [comment]
It's not; it's intentionally only allowed to be recommended when you're not going to wipe out a DPS elemental or need to wipe it out with a DPS elemental.

**Comment by syrifgit** [comment]
But enchancement literally does not have a DPS elemental to cancel it with? It's not possible to do this, so the logic shouldn't be blocking it. It's like having a condition saying hunters can't use cds if their innervate is available.
