### ISSUE TITLE
BM hunter - vision of perfection 

### ISSUE THREAD

**Issue by wow1989** [Hekili/hekili#282]
Hekili is Currently recommending aspect of the wild when that buff is already up due to vision of perfection. 

Delay recommended use until buff is about to drop?

**Comment by Hekili** [comment]
Seems reasonable.

**Comment by Hekili** [comment]
Actually, this probably needs to be optional, since VoP procs could potentially desync Aspect of the Wild if you don't allow the overlap.  But still doable.

**Comment by wow1989** [comment]
I suppose it leaves the opportunity to be casting PI mid wrath. Still probably a bet dps gain though. Most people running VoP are 3x stacking primal instinct.

**Comment by wow1989** [comment]
Aside from wrath, which is a variable Cooldown , and possibly a trinket, there isn’t really much you’re trying to sync aspect with while running VoP anyway

**Comment by PISQOSZ** [comment]
just add this 

> cooldown.barbed_shot.charges < 1 | ! azerite.primal_instincts.enabled &!buff.aspect_of_the_wild.up

**Comment by Hekili** [comment]
The addon already has a spec option to delay AOTW recommendations until after AOTW falls off.
