### ISSUE TITLE
Outlaw - Using RTB after vanish, possibly because of dropping combat vs dummies/raid bosses

### ISSUE THREAD

**Issue by summerfruits** [Hekili/hekili#2820]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As above, Outlaw Rogue (With KIR talents) is recommending RTB after Vanish, but only sometimes. 

### How to Reproduce

1. Spec into KIR talents (BQQAAWulQAmRd/c4Iy2r7VOUFAAAgEkEkkkkkk0SECBSISikkkIAAAAAAARLAlIkkEpFAAAA)
2. Follow Hekili recommendations until Vanish
3. Cast vanish
4. Observe a RTB recommendation (but only sometimes) 

### Snapshot (Link)

https://pastebin.com/qVBaDSr7

### Contact Information

summerfruits

**Comment by summerfruits** [comment]
Now (After implementing the precombat change in the action priority) I'm receiving this LUA error after Vanishing - I assume that it's happening when I drop combat. Hekili suggests I vanish, but after I vanish, it remains the primary suggestion, but shows the '2minute' CD in the Primary #1 slot as well. This is the Lua Error I encountered when snapshotting: 

Message: [string "-- Outlaw:precombat:7..."]:2: attempt to index global 'rtb_buffs' (a number value)
Time: Tue Oct 10 23:31:54 2023
Count: 1
Stack: [string "-- Outlaw:precombat:7..."]:2: attempt to index global 'rtb_buffs' (a number value)
[string "-- Outlaw:precombat:7
return safebool( remains<3 or rtb_buffs.will_lose==0 )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:986: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1382: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function `Update'
[string "@Interface/AddOns/Hekili/Options.lua"]:11004: in function `MakeSnapshot'
[string "@Interface/AddOns/Hekili/Options.lua"]:11105: in function `FireToggle'
[string "@Interface/AddOns/Hekili/UI.lua"]:2818: in function <Interface/AddOns/Hekili/UI.lua:2817>

Locals: (*temporary) = <function> defined @Interface/AddOns/Hekili/State.lua:623
(*temporary) = 2
(*temporary) = "attempt to index global 'rtb_buffs' (a number value)"

**Comment by summerfruits** [comment]
I made a change @Hekili recommended - to change the precombat RTB action priority to: 'remains < 3 | rtb_buffs_will_lose = 0' and it has returned to suggesting RTB after Vanish, likely due to dropping combat.

**Comment by Hekili** [comment]
Make sure to include a new snapshot with your updates.  Thanks!

**Comment by Hekili** [comment]
> I made a change @Hekili recommended - to change the precombat RTB action priority to: 'remains < 3 | rtb_buffs_will_lose = 0' and it has returned to suggesting RTB after Vanish, likely due to dropping combat.

@summerfruits Try just removing the ` | rtb_buffs_will_lose = 0` entirely (so it's just `remains < 3` and see if that suffices.  It'd still reroll if you Vanish as KiR buffs are truly falling off, but that should be extremely rare.
