### ISSUE TITLE
[BUG] Hekili WOTLK not loading with 3.4.3.51666

### ISSUE THREAD

**Issue by jvermast** [Hekili/hekili#2821]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili not loading with new wotlk patch. 
Date: 2023-10-10 14:09:50
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Hekili/State.lua line 3491:
   attempt to perform arithmetic on field 'max' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Hekili/State.lua"]:3491:
      Interface/AddOns/Hekili/State.lua:3441
   [string "@Interface/AddOns/Hekili/Classes.lua"]:3217:
      Interface/AddOns/Hekili/Classes.lua:3214
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Hekili/Options.lua"]:4792: EmbedItemOptions()
   [string "@Interface/AddOns/Hekili/Options.lua"]:9739: RefreshOptions()
   [string "@Interface/AddOns/Hekili/UI.lua"]:304: StartConfiguration()
   [string "@Interface/AddOns/Hekili/Options.lua"]:10245: ?()
   [string "@Interface/AddOns/AskMrRobotClassic/Libs/AceConsole-3.0/AceConsole-3.0.lua"]:94: ?()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4965: ChatEdit_ParseText()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4628: ChatEdit_SendText()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4664:
      Interface/FrameXML/ChatFrame.lua:4660
   [string "=[C]"]: ChatEdit_OnEnterPressed()
   [string "*ChatFrame.xml:121_OnEnterPressed"]:1:
      [string "*ChatFrame.xml:121_OnEnterPressed"]:1
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  AskMrRobotClassic, v15
  Attune, v312
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  AutoCombatLogger, v10.1.1
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  DBMCore, v2060b18
  DBMStatusBarTimers, v2060b18
  DBMVPVEM, v31008bd
  Details, v#Details.20230913.11914.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v13.43
  ElvUIBenikUI, v2.15
  ElvUILibraries, v13.43
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  ExtendedCharacterStats, v3.1.6
  FojjiCore, v
  Gargul, v6.2.6
  GTFO, v5.5.2
  Hekili, vv3.4.3-1.0.0
  Informant, v3.4.6980 (SwimmingSeadragon)
  MinimapAlert, v21
  MuteSoundFile, vv10.1.4
  Plater, vPlater-v564.2-Wrath
  QoLClassicThreatTBC, v22
  QoLCoreTBC, v15
  Questie, v8.10.4
  SexyMap, vv10.1.5
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.2.13
  Stubby, v3.4.6920 (SwimmingSeadragon)
  SwitcherTracking, v3.4.1
  TacoTip, v0.4.3
  TradeSkillMaster, vv4.13.14
  TradeSkillMasterAppHelper, vv4.12.2
  WeakAuras, v5.8.1
  WeakAurasCompanion, v1.0.0
  WowSimsExporter, v2.5
  BlizRuntimeLib v3.4.3.51666(US) <enUS>
  (ck=62f)

### How to Reproduce

Enter game
Load Hekili

### Player Information (Link)

Cannot do asUI won't open

### Error Messages (Link)

Cannot do asUI won't open

### Contact Information

marshallx @ Discord

**Comment by jvermast** [comment]
Date: 2023-10-10 14:04:52
ID: 8
Error occured in: Global
Count: 1
Message: Interface/AddOns/Hekili/State.lua line 2908:
   attempt to index local 'ability' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Hekili/State.lua"]:2908:
      Interface/AddOns/Hekili/State.lua:2903
   [string "@Interface/AddOns/Hekili/Options.lua"]:4963:
      Interface/AddOns/Hekili/Options.lua:4930
   [string "@Interface/AddOns/Hekili/Options.lua"]:5787: EmbedSpecOptions()
   [string "@Interface/AddOns/Hekili/Options.lua"]:9737: RefreshOptions()
   [string "@Interface/AddOns/Hekili/UI.lua"]:304: StartConfiguration()
   [string "@Interface/AddOns/Hekili/Options.lua"]:10245: ?()
   [string "@Interface/AddOns/AskMrRobotClassic/Libs/AceConsole-3.0/AceConsole-3.0.lua"]:94: ?()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4965: ChatEdit_ParseText()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4628: ChatEdit_SendText()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4664:
      Interface/FrameXML/ChatFrame.lua:4660
   [string "=[C]"]: ChatEdit_OnEnterPressed()
   [string "*ChatFrame.xml:121_OnEnterPressed"]:1:
      [string "*ChatFrame.xml:121_OnEnterPressed"]:1
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  AskMrRobotClassic, v15
  Attune, v312
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucScanData, v3.4.6908 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  AutoCombatLogger, v10.1.1
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  DBMCore, v2060b18
  DBMStatusBarTimers, v2060b18
  DBMVPVEM, v31008bd
  Details, v#Details.20230913.11914.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v13.43
  ElvUIBenikUI, v2.15
  ElvUILibraries, v13.43
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  ExtendedCharacterStats, v3.1.6
  FojjiCore, v
  Gargul, v6.2.6
  GTFO, v5.5.2
  Hekili, vv3.4.2-1.0.0
  Informant, v3.4.6980 (SwimmingSeadragon)
  MinimapAlert, v21
  MuteSoundFile, vv10.1.4
  Plater, vPlater-v564.2-Wrath
  QoLClassicThreatTBC, v22
  QoLCoreTBC, v15
  Questie, v8.10.4
  SexyMap, vv10.1.5
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.2.13
  Stubby, v3.4.6920 (SwimmingSeadragon)
  SwitcherTracking, v3.4.1
  TacoTip, v0.4.3
  TradeSkillMaster, vv4.13.14
  TradeSkillMasterAppHelper, vv4.12.2
  WeakAuras, v5.8.1
  WeakAurasCompanion, v1.0.0
  WowSimsExporter, v2.5
  BlizRuntimeLib v3.4.3.51666(US) <enUS>
  (ck=65c)

 
 Another when loading the UI using /hekili

**Comment by Hekili** [comment]
The error message you provided only appears after you are trying to launch into the Hekili UI.  Are there messages before this in your BugSack?

I am not able to replicate this particular error.  There would've had to have been some kind of failed reset before this point, because your maximum mana value isn't set here.
