### ISSUE TITLE
[rec] Best Mana Potion: Endless Loop 

### ISSUE THREAD

**Issue by nono1313234** [Hekili/hekili#2822]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili version [v3.4.3-1.0.0]
other class works, but when mage open hekili recommend the interface is not showing correctly

### How to Reproduce

1. enter game
2. open hekili
3. you get this (see link)
![screenshot](https://github.com/Hekili/hekili/assets/136677944/67a30eda-2f0c-4fb2-a8c3-8bfb8f2de97f)

### Snapshot (Link)

N/A

**Comment by Hekili** [comment]
You didn't link any error information.

**Comment by nono1313234** [comment]
i mean screenshot, usually it has the hekili ui interface, but in mage class is when open hekili is just seeing the screenshot suggested, no ui, nor prio skill suggestion either when first load

**Comment by Hekili** [comment]
This will be fixed in 1.0.1.
