### ISSUE TITLE
[BUG] UI clicking sound repeating after some time

### ISSUE THREAD

**Issue by indandgo** [Hekili/hekili#2823]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

at some point without fail, only with hekili loaded, ill repeatedly hear the UI clicking sound over and over, as if im clicking on an unusable spell, not sure whats causing it, not seeing any patterns.

### How to Reproduce

playing on a survival hunter, with hekili loaded, after using spells for some time

### Player Information (Link)

https://pastebin.com/wT47kB3g

### Error Messages (Link)

no error messages

### Additional Information

Once hekili was turned off, even with other addons, the sound would not come on, the sound starts again once hekili is loaded, persists through /reload ui

### Contact Information

@indandgo discord

**Comment by Hekili** [comment]
This would have to be an interaction with another addon.  This addon doesn't click anything.
