### ISSUE TITLE
Is it possible to create a rotation for Arenas only?

### ISSUE THREAD

**Issue by Graumenth** [Hekili/hekili#2824]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello. I am playing Retribution Paladin and I removed consecration proc talent. I don't want Hekili to recommend me consecration. But as you can understand I will also play PvE and in PvE I believe Hekili is going to recommend pretty much better than what I can do. Is it possible to create another rotation just for arenas, if not could you please tell me how can I remove Consecration.

Thanks.

### Contact Information

Discord ID: Helcaraxë

**Comment by Hekili** [comment]
You could write a custom priority for arenas.

You can disable any ability, including Consecration, by going to /hekili > Abilities and selecting the ability and disabling it.

You could also customize your priority to only disable Consecration in arenas by opening each Consecration entry in the action list and wrapping its conditions in:

 `! arena & (` *existing conditions go here* `)`
