### ISSUE TITLE
[BUG] WOTLK MAGE fails to load and error

### ISSUE THREAD

**Issue by Tocsin614** [Hekili/hekili#2825]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Cant get mage to show anything in the primary window. I right click the icon for options and nothing happens. I have spec selected with left click..  its like it has a conflict in the class atm preventing ya from opening the options panel.
Even tried options>addons>Hekili>open Hekili options panel and nothing...it sticks on the gui to move primary, aoe and notifications but no options panel

### How to Reproduce

log on mage
Right click icon
boom error and options panel doesnt open

### Player Information (Link)

cant open with this error

### Error Messages (Link)

https://pastebin.com/uaGnukxK

### Contact Information

Tocsin in discord channel

**Comment by Hekili** [comment]
This is resolved in the newly published version.
