### ISSUE TITLE
 Add please adjust slider Death Strike for classes DK

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#283]
Hello. Is it possible to make an additional option for the dk class, an adjustable slider on Death Strike. I would like the rotation to offer on a certain% Death Strike. It is very convenient now, when they led the Corruption system.

**Comment by Hekili** [comment]
Can you elaborate?  You want to Death Strike when your shield will be a certain % of health?  When there's a certain % of duration remaining?

**Comment by geraint425** [comment]
No, I just want to use death strike on low hp. And use death strike to consume dark succor. Here are two of these settings would completely satisfy me. This is pure for ADK and FDK. Not for BDK.

**Comment by Hekili** [comment]
It sounds more like you want to write a custom priority.  Adding a custom option means *additional* criteria.

**Comment by geraint425** [comment]
No well, why custom. This in fact we add to our DK. Mini safe. It’s just that it will be inserted into rotation only when our character has figuratively become 56% HP and at this moment this function works, that you need to press Death strike 1 time. And all further rotation. Just this slider will be the threshold for death strike. When it will work. This will simply give a huge advantage in that you can not be distracted from rotation and just see when there is little health and press at the right time death strike. 
I beg you to think about this decision. I will be very grateful for this.

**Comment by Hekili** [comment]
I'm closing this ticket and leaving it out for now.

Wanting to add a recommendation for defensive/self-heal purposes for a DPS spec is something you should do on your own.  I may make it easier to do so in the future, but it's not something I'll add to the defaults.
