### ISSUE TITLE
Settings will not load in WOTLK

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2830]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

/hekili causes errors and settings will not load. Rotation still works. Looks similar to other issues I see but different error messages.

### How to Reproduce

Enter game as Hunter.
Type /hekili error happens.

### Player Information (Link)

Can not load into settings.

### Error Messages (Link)

https://pastebin.com/Th7FtCUL

**Comment by sausje** [comment]
Go to the minimap icon and enable Hekili it from there, should load it.
