### ISSUE TITLE
[BUG] Not working on 10.2 PTR

### ISSUE THREAD

**Issue by Narrttu** [Hekili/hekili#2834]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon don't suggest any action.
![Captura de tela 2023-10-20 084257](https://github.com/Hekili/hekili/assets/54677405/4490f8ab-6751-4333-b201-b70b943187b5)

### How to Reproduce

1. Enter in PTR
2. Nothing happens

### Player Information (Link)

Don't show me a text box

### Error Messages (Link)

https://pastebin.com/3BUUtTwx

**Comment by Hekili** [comment]
There's no published alpha/beta version for PTR at this time.
