### ISSUE TITLE
Balance druid rotation order error?

### ISSUE THREAD

**Issue by ExelArts** [Hekili/hekili#2835]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Tells me to use wrath on the ability bar i have that set to 1 hekili tells me its in 2
It doesnt do this on my warrior mage Demon hunter and hunter
![druid](https://github.com/Hekili/hekili/assets/145317891/952c9da5-13a1-433c-bdfe-6c3a01eb1019)

### How to Reproduce

i dont know
![druid 2](https://github.com/Hekili/hekili/assets/145317891/fb748411-c7ee-40e5-b57d-ed3cb725251b)

### Player Information (Link)

build: v10.1.7-1.0.6 level: 60 (60) class: DRUID spec: balance  talents: BYGACG4EgN+c3/TAgq/XoBdcwAAAAAAAAAAAAAAAAAAAgCQkkIikkAkEsgIgWQSSCJh4AB0SEhgGAFAIA     aetherial_kindling = 1/1     astral_influence = 2/2     astral_smolder = 2/2     balance_of_all_things = 1/2     celestial_alignment = 1/1     cosmic_rapidity = 2/2     eclipse = 1/1     frenzied_regeneration = 1/1     improved_barkskin = 1/1     improved_sunfire = 1/1     innervate = 1/1     ironfur = 1/1     lycaras_teachings = 2/3     matted_fur = 1/1     moonkin_form = 1/1     natures_grace = 1/1     nurturing_instinct = 2/2     orbit_breaker = 1/1     power_of_goldrinn = 2/2     primordial_arcanic_pulsar = 1/1     rattle_the_stars = 1/1     rejuvenation = 1/1     remove_corruption = 1/1     rising_light_falling_night = 1/1     shooting_stars = 1/1     solar_beam = 1/1     solstice = 1/1     soothe = 1/1     soul_of_the_forest = 1/1     stampeding_roar = 1/1     starfall = 1/1     starfire = 1/1     starlord = 2/2     starsurge = 1/1     sunfire = 1/1     swiftmend = 1/1     thick_hide = 2/2     twin_moons = 1/1     typhoon = 1/1     ursols_vortex = 1/1     verdant_heart = 1/1     waning_twilight = 2/2     wild_charge = 1/1     wild_surges = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: none  gear: springrain_band_of_destruction = 1     springrain_belt = 1     springrain_bracers = 1     springrain_cloak_of_destruction = 1     springrain_grips = 1     springrain_headpiece = 1     springrain_idol_of_destruction = 1     springrain_leggings = 1     springrain_medallion = 1     springrain_ring_of_destruction = 1     springrain_spaulders = 1     springrain_stave = 1     springrain_stone_of_destruction = 1     springrain_treads = 1     springrain_tunic = 1  legendaries: none  itemIDs: 153754, 153755, 153756, 153757, 153758, 153759, 153760, 153761, 153762, 153763, 153764, 153765, 153766, 153767, 153783  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 6     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     enhancedRecheck = true     gcdSync = true     maxTime = 20     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Balance     petbased = false     potion = spectral_intellect     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     starlord_cancel = false     vigil_damage = 50  toggles: cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      barkskin              = 3   [09], 9   [10]     celestial_alignment   = E   [02]     dash                  = 3   [07]     entangling_roots      = X   [02]     ferocious_bite        = 2   [07]     frenzied_regeneration = 4   [09]     growl                 = 2   [09]     innervate             = Dn  [02]     ironfur               = 5   [09]     mangle                = 1   [09]     mark_of_the_wild      = Up  [02]     moonfire              = 4   [01], 4   [10]     moonkin_form          = TAB [02]     prowl                 = 4   [07]     regrowth              = RIGHT[02], 8   [10]     rejuvenation          = LEFT[02]     remove_corruption     = 7   [01]     shred                 = 1   [07]     solar_beam            = 7   [10]     soothe                = C   [02]     starfall              = 6   [10]     starfire              = 3   [01], 1   [10]     starsurge             = 5   [01], 5   [10]     sunfire               = 2   [01], 3   [10]     wild_charge           = -   [01]     wild_growth           = R   [02]     wrath                 = 1   [01], 2   [10]  warnings: none

### Error Messages (Link)

i have no bugs

**Comment by ExelArts** [comment]
it does this for other ability's too but moonkin form it gets right

**Comment by ExelArts** [comment]
now on my warrior i noticed hekili moved so i moved it back, Now it want fade away out of combat trying to find if maybe the option got changed but i cant find it now

**Comment by ExelArts** [comment]
just checked my other toons and hekili is stuck on and wont fade away after battle now

**Comment by ExelArts** [comment]
again says i still have no bugs

**Comment by Hekili** [comment]
According to your Player Information you provided, you have Wrath on page 1, bound to `1`, and on page 10, bound to `2`.  Under normal circumstances, your Action Bar 1 is set to page 1 in your normal (caster) form and set to page 10 while in Moonkin form.

If you have configured your action bars differently, you can manually set the binding for any ability in /hekili >Abilities instead.

**Comment by ExelArts** [comment]
but my load order doesnt change when i switch to moonkin? sorry i have a learning disability and i dont under stand why its different on the information but when switching between night elf and moonkin nothing on my Action bar 1 change's 
how do i find this page 10???
