### ISSUE TITLE
Arcane surge not showing up for arcane mage (RETAIL)

### ISSUE THREAD

**Issue by Piemelaapje** [Hekili/hekili#2836]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon doesnt show up arcane surge in the rotation even with cooldowns enabled

### How to Reproduce

Just being logged in for arcane did it for me

### Snapshot (Link)

https://pastebin.com/kqgS2R5Y

### Contact Information

Gastly

**Comment by wiatrM** [comment]
Yep I have the same, no matter what I do Arcane Surde did never appears

**Comment by marekCs** [comment]
> Yep I have the same, no matter what I do Arcane Surde did never appears

I guess you are not at max level 70 yet as well, right?

**Comment by Hekili** [comment]
If you are not high enough level to have the capstone talents that you plan Arcane Surge around in endgame, the priority isn't going to recommend AS.

This isn't a bug, per se, and the addon warns about it, so I'll close this ticket. I may adjust the Arcane Priority to pick a cooldowns/burn action list when underleveled but no guarantees.

**Comment by wiatrM** [comment]
> > Yep I have the same, no matter what I do Arcane Surde did never appears
> 
> I guess you are not at max level 70 yet as well, right?

Nope, Im on max 70
