### ISSUE TITLE
[BUG] wotlk Enabled but not displaying anything - multiple lua errors

### ISSUE THREAD

**Issue by bakua21** [Hekili/hekili#2838]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

addon is enabled, all settings are set up per usual preferences. logged on today and entire addon stopped working. same issue for all characters, no matter the spec. 

all functionality lost, no rotations are displaying within primary or aoe panels and no notifications.

### How to Reproduce

Enter game as any class / spec - broken for all 

### Player Information (Link)

https://pastebin.com/ZV3FzVdw

### Error Messages (Link)

https://pastebin.com/ZV3FzVdw

### Contact Information

discord - nyago

**Comment by zmsl** [comment]
Refer to bug https://github.com/Hekili/hekili/issues/2842 for status updates on this issue.
