### ISSUE TITLE
Addon stopped working - not showing up ingame

### ISSUE THREAD

**Issue by 9HaVoC6** [Hekili/hekili#2839]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Wrath of the Lich King - logged on and it had randomly stopped working, realised that the active priority and priority selectors had disappeared. Checked other chars and they had disappeared also  - below are the bug reports.

### How to Reproduce

I logged in on death knight 
stopped working

### Player Information (Link)

https://pastebin.com/YT7LtfFT

### Error Messages (Link)

https://pastebin.com/YT7LtfFT

### Contact Information

havoc5041

**Comment by magnog0** [comment]
I thought it was the only one... glad it's not my side then and it's actually the addon!

**Comment by zmsl** [comment]
Refer to bug https://github.com/Hekili/hekili/issues/2842 for status updates on this issue.
