### ISSUE TITLE
pvp trinket not being suggested

### ISSUE THREAD

**Issue by master5006** [Hekili/hekili#284]
build: v8.3.0-04-09
level: 120 (120)
class: MAGE
spec: fire

talents: conflagration
    flame_on
    frenetic_speed
    meteor
    rune_of_power
    searing_touch
    shimmer

azerite: azerite_empowered = 2
    blightborne_infusion = 1
    meticulous_scheming = 1
    quick_thinking = 1
    resounding_protection = 1

essences: [the_crucible_of_flame] = 3, breath_of_the_dying = 1, memory_of_lucid_dreams = 1

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    corrupted_aspirants_badge = 1
    corrupted_aspirants_ring = 1
    greasy_bacongrabbers = 1
    heart_of_azeroth = 1
    vile_manipulators_footwraps = 1

corruptions: twisted_appendage = 2

itemIDs: 155891, 157941, 157969, 158003, 158036, 158075, 159129, 165679, 168988, 169223, 170641, 172710, 172844, 172849, 173431, 5976

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    nameplateRange = 8
    nameplates = false
    package = Fire
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    prevent_hardcasts = true
    pyroblast_pull = true
    reserve_runes = 1

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
All relevant PvP trinkets should be incorporated; post a new ticket if you find otherwise.
