### ISSUE TITLE
[BUG] Addon will not show up since the server reset/update.

### ISSUE THREAD

**Issue by magnog0** [Hekili/hekili#2840]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Since the WoW server reset, I dunno if there was an update or not, but Hekili will not load, it doesn't show anymore, but the addon is installed i can access the addon options etc.

### How to Reproduce

 Issue Reporting section is empty 

### Player Information (Link)

 Issue Reporting section is empty.

### Error Messages (Link)

 Issue Reporting section

**Comment by zmsl** [comment]
Refer to https://github.com/Hekili/hekili/issues/2842 for status updates on this issue.
