### ISSUE TITLE
[BUG] Addon won't load

### ISSUE THREAD

**Issue by Bacrdimike** [Hekili/hekili#2841]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon will not show windows for next spell. It will show the very first spell and then hang. I have checked on multiple toons, and they are different classes.

### How to Reproduce

Log into any character and the error happens.

### Player Information (Link)

There is nothing in the reporting section

### Error Messages (Link)

https://pastebin.com/MHQHi2se

### Contact Information

bacrdimike

**Comment by sicksicko** [comment]
you're not the only one. i literally just downloaded it yesterday, dps went up and now this. I couldn't even figure out how to disable/reenable to see if that would work but thankfully im not the only one either.

**Comment by piiccolo** [comment]
getting the same issues as well

**Comment by b14554124** [comment]
xD,  Blizzard's  BUG~
https://us.forums.blizzard.com/en/wow/t/bug-the-event-executechatline-appears-to-have-been-removed-breaking-many-macros-and-addons/1694085

**Comment by zmsl** [comment]
Refer to bug https://github.com/Hekili/hekili/issues/2842 for status updates on this issue
