### ISSUE TITLE
[REC] Shamanistic Rage Threshold not being respected

### ISSUE THREAD

**Issue by Behodar** [Hekili/hekili#2844]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon is no longer recommending Shamanistic Rage until all my mana is completely exhausted. It was working correctly through version 3.4.3-1.0.1 but has failed as of 3.4.3-1.0.2 (or, more accurately, the temporary build posted in #2842, but was not fixed by moving to the official version).

### How to Reproduce

1. Enter the game as an Enhancement Shaman.
2. Type /heliki and observe the value of Shamanistic Rage Threshold (under the Shaman category, Core tab). I believe this is set to 50 by default.
3. Get into combat and follow the addon's recommendations (or just use anything) until your mana drops below the percentage from step 2 (e.g. 50%).
4. I would expect the addon to recommend Shamanistic Rage at this point, but it doesn't.

### Snapshot (Link)

https://pastebin.com/KtB9fxtv

**Comment by Behodar** [comment]
Correction: this issue is intermittent. I've just done a whole raid and it worked some of the time, but not other times. I've yet to figure out any pattern behind it.

**Comment by blagyyy-tools** [comment]
Move Sham Rage up in the priority and it works as intended i guess :D

**Comment by zmsl** [comment]
The thought behind SR being low on the priority is that it is on GCD and is treated as a filler. I need to do some research to see what the optimal SR priority is, especially with the new T10 impact on its use. For now feel free to adjust the priority and know that there is work in that area on the way 👍

**Comment by Behodar** [comment]
I'm a bit baffled as to how this seemed to break in 3.4.3-1.0.2 given that it didn't change the priorities at all! Or maybe it's completely unrelated: you mention T10 so was it just due to getting new gear?

Anyway, thanks and I'll mess with the priorities for now :)

**Comment by Blueing** [comment]
> I'm a bit baffled as to how this seemed to break in 3.4.3-1.0.2 given that it didn't change the priorities at all! Or maybe it's completely unrelated: you mention T10 so was it just due to getting new gear?
> 
> Anyway, thanks and I'll mess with the priorities for now :)

T10 p2 is that you gain 12% dmg while SR is used. So with T10p2 SR should be way higher in priority (I guess use on cooldown). Don't think Hekili does T10p2 take into account yet

**Comment by Hekili** [comment]
It respects the setting; it was using it as filler when resources were low.  You're correct that using SR as a higher priority will need to be accounted for later on.
