### ISSUE TITLE
[REC] Incorrect last_bloodtalons_proc value

### ISSUE THREAD

**Issue by ChrisKader** [Hekili/hekili#2845]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The `SPELL_AURA_APPLIED` subevent is triggered when swapping forms while the "Bloodtalons" buff is active. As a result, `last_bloodtalons_proc` is updated with the current time, even though that is not the correct value.

### How to Reproduce

1. Ensure the "Bloodtalons" talent is enabled.
2. Proc the buff.
3. Swap out of cat form into another form, such as Travel Form.

### Snapshot (Link)

n/a

### Additional Information

Recommend checking for the "SPELL_AURA_APPLIED" subevent and then checking to see if the Bloodtalons buff is up. If the buff is up, do not update `last_bloodtalons_proc`.

**Comment by Hekili** [comment]
The buff will be up, though, if SPELL_AURA_APPLIED is fired. I could check whether the number of stacks has increased, though.
