### ISSUE TITLE
[REC] Doesn't suggest "Death and decay" frequently enough.

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#2847]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a dk tank death and decay should always be up.  This happens on the alliance side but doesn't happen on low level horde dk's.
I'm currently lvl 30.

### How to Reproduce

create low level horde dk tank.

### Snapshot (Link)

Blood; Primary - Death Strike(0.00), Marrowrend(1.17)

### Contact Information

N6REJ

**Comment by Hekili** [comment]
Note that low levels are not actively supported, but if you provide a complete snapshot, I'll take a look.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by N6REJ** [comment]
I did that and all it gave me was what I posted.  Could I have done something wrong?

**Comment by Hekili** [comment]
You have to use CTRL+A to select all text in the box; it only displays one line but there are actually hundreds if not thousands of lines. You'll be able to tell when you paste to Pastebin.
