### ISSUE TITLE
Blood DK update

### ISSUE THREAD

**Issue by willz501** [Hekili/hekili#2848]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

giving a suggestion rotation for blood dk wrath 

### How to Reproduce

NA

### Snapshot (Link)

https://pastebin.com/2YZBAvD7

### Additional Information

https://pastebin.com/2YZBAvD7

paste bin of my blood profile its decent till you make a fix for death runes

### Contact Information

Samuraiwillz501#0239

**Comment by willz501** [comment]
## Samurai Willz
## 11-4-2023

actions.precombat+=/frost_presence,if=buff.presence.down

actions+=/horn_of_winter,if=buff.horn_of_winter.down|runic_power.current<20
actions+=/death_grip,if=time<2
actions+=/rune_strike,if=aggro & runic_power.current >60
actions+=/death_strike,if=health.pct<=50
actions+=/vampiric_blood,if=health.pct<=40
actions+=/rune_tap,if=health.pct<=40
actions+=/death_coil,if=! aggro & runic_power.current >80 | runic_power.current >99
actions+=/use_items
actions+=/unholy_frenzy
actions+=/run_action_list,name=aoe,strict=1,if=active_enemies>1
actions+=/pestilence,if=dot.frost_fever.ticking&dot.blood_plague.ticking&(active_dot.frost_fever<active_enemies|active_dot.blood_plague<active_enemies|glyph.disease.enabled&(dot.frost_fever.remains<7|dot.blood_plague.remains<7))
actions+=/pestilence,if=dot.blood_plague.ticking&dot.blood_plague.refreshable|dot.frost_fever.ticking&dot.frost_fever.refreshable
actions+=/icy_touch,if=!dot.frost_fever.ticking|frost_runes.time_to_max<gcd
actions+=/plague_strike,if=!dot.blood_plague.ticking
actions+=/blood_strike,if=blood_runes.time_to_max<gcd
actions+=/death_strike,if=health.current+action.death_strike.healing<health.max&dot.frost_fever.ticking&dot.blood_plague.ticking
actions+=/blood_tap,if=(glyph.blood_tap.enabled|health.pct>60)&blood_runes.current=0
actions+=/heart_strike
actions+=/blood_strike
## TODO: Determine Death Rune situation.
actions+=/icy_touch,if=(frost_runes.time_to_max<gcd) & (health.pct<=75) 
actions+=/plague_strike,if=(unholy_runes.time_to_max<gcd) & (health.pct<=75) 
actions+=/empower_rune_weapon,if=(blood_runes.current+frost_runes.current+unholy_runes.current)<2


actions.aoe+=/pestilence,if=dot.frost_fever.ticking & dot.blood_plague.ticking & ((active_enemies <= 3 & (active_dot.frost_fever < active_enemies | active_dot.blood_plague < active_enemies)) | (active_enemies >= 4 & active_enemies <= 7 & (active_dot.frost_fever < active_enemies - 1 | active_dot.blood_plague < active_enemies - 1)) | (active_enemies >= 8 & (active_dot.frost_fever < active_enemies - 2 | active_dot.blood_plague < active_enemies - 2)) | glyph.disease.enabled & (dot.frost_fever.remains < 7 | dot.blood_plague.remains < 7))
actions.aoe+=/rune_strike,if=aggro & runic_power.current >60
actions.aoe+=/death_coil,if=! aggro & runic_power.current >80 | runic_power.current >99
actions.aoe+=/death_and_decay,if=active_enemies>2
actions.aoe+=/pestilence,if=dot.frost_fever.ticking&dot.blood_plague.ticking&(active_dot.frost_fever+active_dot.blood_plague<true_active_enemies*2)
actions.aoe+=/icy_touch,cycle_targets=1,if=!dot.frost_fever.ticking
actions.aoe+=/plague_strike,cycle_targets=1,if=!dot.blood_plague.ticking
actions.aoe+=/blood_boil,if=health.pct>60&(active_enemies>2|!talent.heart_strike)
actions.aoe+=/blood_tap,if=blood_runes.current=0
actions.aoe+=/heart_strike,if=active_enemies<3
actions.aoe+=/icy_touch,if=(frost_runes.time_to_max<gcd) & (cooldown.death_and_decay.remains > 7 | active_enemies < 3) & (health.pct<=75)
actions.aoe+=/plague_strike,if=(unholy_runes.time_to_max<gcd) & (cooldown.death_and_decay.remains > 7 | active_enemies < 3) & (health.pct<=75)

**Comment by willz501** [comment]
fixed icy touch and plague strike over rune logic 

## Samurai Willz
## 11-4-2023

actions.precombat+=/frost_presence,if=buff.presence.down

actions+=/horn_of_winter,if=buff.horn_of_winter.down|runic_power.current<20
actions+=/death_grip,if=time<2
actions+=/rune_strike,if=aggro & runic_power.current >60
actions+=/death_strike,if=health.pct<=50
actions+=/vampiric_blood,if=health.pct<=40
actions+=/rune_tap,if=health.pct<=40
actions+=/death_coil,if=! aggro & runic_power.current >80 | runic_power.current >99
actions+=/use_items
actions+=/unholy_frenzy
actions+=/run_action_list,name=aoe,strict=1,if=active_enemies>1
actions+=/pestilence,if=dot.frost_fever.ticking&dot.blood_plague.ticking&(active_dot.frost_fever<active_enemies|active_dot.blood_plague<active_enemies|glyph.disease.enabled&(dot.frost_fever.remains<7|dot.blood_plague.remains<7))
actions+=/pestilence,if=dot.blood_plague.ticking&dot.blood_plague.refreshable|dot.frost_fever.ticking&dot.frost_fever.refreshable
actions+=/icy_touch,if=!dot.frost_fever.ticking|frost_runes.time_to_max<gcd
actions+=/plague_strike,if=!dot.blood_plague.ticking
actions+=/blood_strike,if=blood_runes.time_to_max<gcd
actions+=/death_strike,if=health.current+action.death_strike.healing<health.max&dot.frost_fever.ticking&dot.blood_plague.ticking
actions+=/blood_tap,if=(glyph.blood_tap.enabled|health.pct>60)&blood_runes.current=0
actions+=/heart_strike
actions+=/blood_strike
## TODO: Determine Death Rune situation.
actions+=/icy_touch,if=aggro & (frost_runes.time_to_max<gcd) & (health.pct>=75) 
actions+=/plague_strike,if=! aggro & (unholy_runes.time_to_max<gcd) & (health.pct>=75) 
actions+=/empower_rune_weapon,if=(blood_runes.current+frost_runes.current+unholy_runes.current)<2


actions.aoe+=/pestilence,if=dot.frost_fever.ticking & dot.blood_plague.ticking & ((active_enemies <= 3 & (active_dot.frost_fever < active_enemies | active_dot.blood_plague < active_enemies)) | (active_enemies >= 4 & active_enemies <= 7 & (active_dot.frost_fever < active_enemies - 1 | active_dot.blood_plague < active_enemies - 1)) | (active_enemies >= 8 & (active_dot.frost_fever < active_enemies - 2 | active_dot.blood_plague < active_enemies - 2)) | glyph.disease.enabled & (dot.frost_fever.remains < 7 | dot.blood_plague.remains < 7))
actions.aoe+=/rune_strike,if=aggro & runic_power.current >60
actions.aoe+=/death_coil,if=! aggro & runic_power.current >80 | runic_power.current >99
actions.aoe+=/death_and_decay,if=active_enemies>2
actions.aoe+=/pestilence,if=dot.frost_fever.ticking&dot.blood_plague.ticking&(active_dot.frost_fever+active_dot.blood_plague<true_active_enemies*2)
actions.aoe+=/icy_touch,cycle_targets=1,if=!dot.frost_fever.ticking
actions.aoe+=/plague_strike,cycle_targets=1,if=!dot.blood_plague.ticking
actions.aoe+=/blood_boil,if=health.pct>60&(active_enemies>2|!talent.heart_strike)
actions.aoe+=/blood_tap,if=blood_runes.current=0
actions.aoe+=/heart_strike,if=active_enemies<3
actions.aoe+=/icy_touch,if=aggro & (frost_runes.time_to_max<gcd) & (cooldown.death_and_decay.remains > 7 | active_enemies < 3) & (health.pct>=75)
actions.aoe+=/plague_strike,if=! aggro & (unholy_runes.time_to_max<gcd) & (cooldown.death_and_decay.remains > 7 | active_enemies < 3) & (health.pct>=75)


##dot.frost_fever.ticking & dot.blood_plague.ticking & ((active_enemies <= 3 & (active_dot.frost_fever < active_enemies | active_dot.blood_plague < active_enemies)) | (active_enemies >= 4 & active_enemies <= 7 & (active_dot.frost_fever < active_enemies - 1 | active_dot.blood_plague < active_enemies - 1)) | (active_enemies >= 8 & (active_dot.frost_fever < active_enemies - 2 | active_dot.blood_plague < active_enemies - 2)) | glyph.disease.enabled & (dot.frost_fever.remains < 7 | dot.blood_plague.remains < 7))

##dot.frost_fever.ticking & dot.blood_plague.ticking & ( ( active_enemies <= 3 & ( active_dot.frost_fever < active_enemies | active_dot.blood_plague < active_enemies ) ) | ( active_enemies > 3 & ( active_dot.frost_fever < active_enemies - 1 | active_dot.blood_plague < active_enemies - 1 ) ) | glyph.disease.enabled & ( dot.frost_fever.remains < 7 | dot.blood_plague.remains < 7 ) )

**Comment by Hekili** [comment]
I'm not sure this will actually successfully import with spaces.  Can you remove the spaces?

**Comment by jeffbee75** [comment]
actions+=/icy_touch,if=aggro&(frost_runes.time_to_max<gcd)&(health.pct>=75)
actions+=/plague_strike,if=!aggro&(unholy_runes.time_to_max<gcd)&(health.pct>=75)
actions+=/empower_rune_weapon,if=(blood_runes.current+frost_runes.current+unholy_runes.current)<2

actions.aoe+=/pestilence,if=dot.frost_fever.ticking&dot.blood_plague.ticking&((active_enemies<=3&(active_dot.frost_fever<active_enemies|active_dot.blood_plague<active_enemies))|(active_enemies>=4&active_enemies<=7&(active_dot.frost_fever<active_enemies-1|active_dot.blood_plague<active_enemies-1))|(active_enemies>=8&(active_dot.frost_fever<active_enemies-2|active_dot.blood_plague<active_enemies-2))|glyph.disease.enabled&(dot.frost_fever.remains<7|dot.blood_plague.remains<7))
actions.aoe+=/rune_strike,if=aggro&runic_power.current>60
actions.aoe+=/death_coil,if=!aggro&runic_power.current>80|runic_power.current>99
actions.aoe+=/death_and_decay,if=active_enemies>2
actions.aoe+=/pestilence,if=dot.frost_fever.ticking&dot.blood_plague.ticking&(active_dot.frost_fever+active_dot.blood_plague<true_active_enemies*2)
actions.aoe+=/icy_touch,cycle_targets=1,if=!dot.frost_fever.ticking
actions.aoe+=/plague_strike,cycle_targets=1,if=!dot.blood_plague.ticking
actions.aoe+=/blood_boil,if=health.pct>60&(active_enemies>2|!talent.heart_strike)
actions.aoe+=/blood_tap,if=blood_runes.current=0
actions.aoe+=/heart_strike,if=active_enemies<3
actions.aoe+=/icy_touch,if=aggro&(frost_runes.time_to_max<gcd)&(cooldown.death_and_decay.remains>7|active_enemies<3)&(health.pct>=75)
actions.aoe+=/plague_strike,if=!aggro&(unholy_runes.time_to_max<gcd)&(cooldown.death_and_decay.remains>7|active_enemies<3)&(health.pct>=75)

##dot.frost_fever.ticking&dot.blood_plague.ticking&((active_enemies<=3&(active_dot.frost_fever<active_enemies|active_dot.blood_plague<active_enemies))|(active_enemies>=4&active_enemies<=7&(active_dot.frost_fever<active_enemies-1|active_dot.blood_plague<active_enemies-1))|(active_enemies>=8&(active_dot.frost_fever<active_enemies-2|active_dot.blood_plague<active_enemies-2))|glyph.disease.enabled&(dot.frost_fever.remains<7|dot.blood_plague.remains<7))

##dot.frost_fever.ticking&dot.blood_plague.ticking&((active_enemies<=3&(active_dot.frost_fever<active_enemies|active_dot.blood_plague<active_enemies))|(active_enemies>3&(active_dot.frost_fever<active_enemies-1|active_dot.blood_plague<active_enemies-1))|glyph.disease.enabled&(dot.frost_fever.remains<7|dot.blood_plague.remains<7))

**Comment by jeffbee75** [comment]
http://www.unit-conversion.info/texttools/replace-text/ used that if ya need others w/spaces removed.
