### ISSUE TITLE
[BUG] Display disappears when changing targets

### ISSUE THREAD

**Issue by Haryytasker** [Hekili/hekili#2849]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello, when Hekili broke a couple of weeks ago, I downloaded the version from here with the correction. When I downloaded that version, I noticed my display would disappear if I changed targets and required me to be on a single target for about a rotation cycle before it would reappear. I hoped it would correct when I downloaded the newest version from Oct. 26, but that is not the case. The issue persists.

I made a clip so you can see what I'm talking about. I'm sure I'm doing something wrong and truly appreciate any time you can give me toward correcting this.

https://clipchamp.com/watch/F56vCd1fQxb

### How to Reproduce

Entered game and want to test dummies. Display was fine as long as I only targeted only one dummy. If I switched, display disappeared. This is replicated on other toons.

### Player Information (Link)

https://pastebin.com/geEGsKfE

### Error Messages (Link)

https://pastebin.com/18xvj0zw

**Comment by SpatenLa** [comment]
i am more surprised it worked before the target swap. your error message says its missing the libs. try reinstalling it from your favorite addon distributor. you seem to have downloaded the wrong thing.

**Comment by Haryytasker** [comment]
Hello, I deleted addons and all saved variables and did a clean install. The problem persists with the same lib messages.

**Comment by SpatenLa** [comment]
what is inside your libs folder? where do you download the addon from?

**Comment by Haryytasker** [comment]
I have no idea what's in the folder. I typically use CurseForge. I just deleted everything and am doing a fresh install of WotLK. It was time to clean it up anyway.

I'll update after everything is set up again.

Thank you for your feedback thus far.

**Comment by Haryytasker** [comment]
I just uninstalled WoW and reinstalled it. Hekili is the only addon currently in the game. The same issue is occurring.

**Comment by Haryytasker** [comment]
Okay, I tested as both Destro and Demo, and it appears to only be happening when using the Destro profile.

**Comment by SpatenLa** [comment]
https://github.com/Hekili/hekili/releases/download/v3.4.3-1.0.2/Hekili-v3.4.3-1.0.2-wrath.zip
try installing this version.

**Comment by SpatenLa** [comment]
are there any other errors?

**Comment by Haryytasker** [comment]
None that I'm aware of. Hekili is the only addon installed right now.

**Comment by Haryytasker** [comment]
Issue persists with 1.0.2. Again, it appears to only be happening with Destro. Is there an issue with that particular script?

**Comment by Haryytasker** [comment]
Logged on to hunter. Problem did not replicate.

**Comment by Haryytasker** [comment]
https://pastebin.com/fb3CjpLU

**Comment by Supernuss** [comment]
Destro Aoe-Rota has a problem with less than 4 enemies. Using the following worked for Harrytasker:
```
actions.precombat+=/fel_armor,if=buff.armor.down|buff.armor.remains<180
actions.precombat+=/summon_imp,if=!pet.active
actions.precombat+=/life_tap,if=glyph.life_tap.enabled&buff.life_tap.down
actions.precombat+=/potion
    
actions+=/call_action_list,name=st,if=active_enemies<2
actions+=/call_action_list,name=aoe,if=active_enemies>1
actions+=/call_action_list,name=life,if=health.pct<25    

actions.st+=/group_curse,if=debuff.my_curse.down&curse_grouped
actions.st+=/immolate,if=!ticking|dot.immolate.remains<1
actions.st+=/conflagrate
actions.st+=/solo_curse,if=debuff.my_curse.down
actions.st+=/life_tap,if=glyph.life_tap.enabled&buff.life_tap.down
actions.st+=/chaos_bolt
actions.st+=/corruption,if=!ticking|dot.corruption.remains<2
actions.st+=/potion
actions.st+=/use_items
actions.st+=/inferno,if=target.time_to_die<=60&mana.pct>20&inferno_enabled|target.health.pct<40&inferno_enabled
actions.st+=/corruption,line_cd=6,if=moving
actions.st+=/life_tap,if=moving&mana.pct<80|mana.pct<10    
actions.st+=/incinerate
actions.st+=/curse_of_doom,if=target.time_to_die>60&debuff.my_curse.down
actions.st+=/curse_of_agony,if=target.time_to_die<60&target.time_to_die>30

actions.aoe+=/shadowfury,if=active_enemies>3
actions.aoe+=/seed_of_corruption,cycle_targets=1,if=active_enemies>3&!ticking
actions.aoe+=/shadowflame,cycle_targets=1,if=active_enemies>3&target.distance<10
actions.aoe+=/immolate,cycle_targets=1,if=!ticking
actions.aoe+=/corruption,line_cd=6,cycle_targets=1,if=moving
actions.aoe+=/call_action_list,name=st,if=active_enemies<4

actions.life+=/death_coil
actions.life+=/drain_life
```
