### ISSUE TITLE
Deathknight attack 2 or more not using Apocalypse in rotation frame bugging

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#285]
**Describe the Bug/Issue**
A clear and concise description of what the bug is. When i attack 2 or more mobs the rotation is not recomend me using apocalypse and bugging out not showing abilities in the bar just showing trinkets cd, works just fine when i attack 1 mob only

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.build: v8.3.0-04-09
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: asphyxiate
    bursting_sores
    infected_claws
    pestilence
    soul_reaper
    spell_eater
    unholy_frenzy

azerite: azerite_empowered = 3
    blood_siphon = 1
    earthlink = 1
    festermight = 3
    gemhide = 1
    magus_of_the_dead = 3
    march_of_the_damned = 1
    resounding_protection = 1
    unstable_flames = 1

essences: [vision_of_perfection] = 2, breath_of_the_dying = 1, memory_of_lucid_dreams = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    ashvanes_razor_coral = 1
    azsharas_font_of_power = 1
    corrupted_gladiators_plate_gauntlets = 1
    corrupted_gladiators_plate_greaves = 1
    corrupted_gladiators_plate_vambraces = 1
    desert_guardians_breastplate = 1
    fleetwreckers_greaves = 1
    heart_of_azeroth = 1
    kraken_shell_pauldrons = 1
    loop_of_abhorrent_celerity = 1
    seabrawlers_greathelm = 1
    seal_of_questionable_loyalties = 1
    stormtempered_girdle = 1
    tentacle_crusher = 1
    thunder_bluff_tabard = 1

corruptions: twilight_devastation = 3

itemIDs: 155885, 158075, 158314, 159424, 159431, 168388, 168389, 168897, 169223, 169311, 169314, 172550, 172613, 172618, 174268, 45584

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 5
    damage = false
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 4
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:****PUT ISSUE REPORT LINK HERE:**

2
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v8.3.0-04-09
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: asphyxiate
    bursting_sores
    infected_claws
    pestilence
    soul_reaper
    spell_eater
    unholy_frenzy

azerite: azerite_empowered = 3
    blood_siphon = 1
    earthlink = 1
    festermight = 3
    gemhide = 1
    magus_of_the_dead = 3
    march_of_the_damned = 1
    resounding_protection = 1
    unstable_flames = 1

essences: [vision_of_perfection] = 2, breath_of_the_dying = 1, memory_of_lucid_dreams = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    ashvanes_razor_coral = 1
    azsharas_font_of_power = 1
    corrupted_gladiators_plate_gauntlets = 1
    corrupted_gladiators_plate_greaves = 1
    corrupted_gladiators_plate_vambraces = 1
    desert_guardians_breastplate = 1
    fleetwreckers_greaves = 1
    heart_of_azeroth = 1
    kraken_shell_pauldrons = 1
    loop_of_abhorrent_celerity = 1
    seabrawlers_greathelm = 1
    seal_of_questionable_loyalties = 1
    stormtempered_girdle = 1
    tentacle_crusher = 1
    thunder_bluff_tabard = 1

corruptions: twilight_devastation = 3

itemIDs: 155885, 158075, 158314, 159424, 159431, 168388, 168389, 168897, 169223, 169311, 169314, 172550, 172613, 172618, 174268, 45584

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 5
    damage = false
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 4
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

New Recommendations for [ Primary ] requested at 17:29:17 ( 89726.41 ); using built-in ( Unholy ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: runes[ 6 / 6 ], runic_power[ 0 / 100 ]
    
    Processing precombat action list [ Unholy - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        1.   potion ( precombat - 1 ) - ability disabled.
        2.   raise_dead ( precombat - 2 )
        The action (raise_dead) is usable at (0.00 + 0.00) with cost of 0.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  raise_dead at 0.00!
    
    Completed precombat action list [ Unholy - precombat ].
    Recommendation is raise_dead at 0.00 + 0.00.
    Recommendation #1 is raise_dead at 0.00s (0.00s).
    
    RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.20, Casting: 0.00 ).
    
    Resources: runes[ 6 / 6 ], runic_power[ 0 / 100 ]
    
    Processing precombat action list [ Unholy - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        1.   potion ( precombat - 1 ) - ability disabled.
        2.   raise_dead ( precombat - 2 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        3.   azsharas_font_of_power ( precombat - 3 )
        The action (azsharas_font_of_power) is usable at (0.00 + 1.20) with cost of 0.
         - the action is ready before the current recommendation (at +1.20 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  azsharas_font_of_power at 1.20!
        4.   army_of_the_dead ( precombat - 4 )
        The action is not ready in time ( 1.20 vs. 1.20 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        
    
    Completed precombat action list [ Unholy - precombat ].
    
    Processing default action list [ Unholy - default ].
        
        Current recommendation was azsharas_font_of_power at +1.20s.
        5.   mind_freeze ( default - 1 ) - ability disabled.
        The recommended action (azsharas_font_of_power) would be ready before the next GCD (1.20 < 1.20); exiting list (default).
    
    Completed default action list [ Unholy - default ].
    Recommendation is azsharas_font_of_power at 0.00 + 1.20.
    Recommendation #2 is azsharas_font_of_power at 1.20s (1.20s).
    Advancing clock by 1.20...
    Queueing azsharas_font_of_power cast finish at 89730.82.
    Queued azsharas_font_of_power from 89727.61 to 89730.82 (CAST_FINISH).
    Queueing azsharas_font_of_power channel finish at 89730.82.
    Queued azsharas_font_of_power from 89727.61 to 89730.82 (CHANNEL_FINISH).
    
    RECOMMENDATION #3 ( Offset: 1.20, GCD: 1.20, Casting: 0.00 ).
    
    Resources: runes[ 6 / 6 ], runic_power[ 0 / 100 ]
    
    Finishing queued event #1 ( CAST_FINISH of azsharas_font_of_power ) due at 3.21 as player is casting and cannot cast.
    
    Advancing clock by 3.21...
    While advancing by 3.21 to 4.42, azsharas_font_of_power CAST_FINISH occurred at 4.42.
    
    Handling azsharas_font_of_power at 89730.82 (CAST_FINISH).
    Trying to remove azsharas_font_of_power CAST_FINISH from queue.
    Removing 1 from queue.
    While advancing by 3.21 to 4.42, azsharas_font_of_power CHANNEL_FINISH occurred at 4.42.
    
    Handling azsharas_font_of_power at 89730.82 (CHANNEL_FINISH).
    Trying to remove azsharas_font_of_power CHANNEL_FINISH from queue.
    Removing 1 from queue.
    Resources: runes[ 6 / 6 ], runic_power[ 0 / 100 ]
    
    Processing precombat action list [ Unholy - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        1.   potion ( precombat - 1 ) - ability disabled.
        2.   raise_dead ( precombat - 2 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        3.   azsharas_font_of_power ( precombat - 3 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        4.   army_of_the_dead ( precombat - 4 )
        The action (army_of_the_dead) is usable at (4.42 + 0.00) with cost of 3.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  army_of_the_dead at 0.00!
    
    Completed precombat action list [ Unholy - precombat ].
    Recommendation is army_of_the_dead at 4.42 + 0.00.
    Recommendation #3 is army_of_the_dead at 0.00s (4.42s).
    
    RECOMMENDATION #4 ( Offset: 4.42, GCD: 1.20, Casting: 0.00 ).
    
    Resources: runes[ 3 / 6 ], runic_power[ 30 / 100 ]
    
    Processing precombat action list [ Unholy - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        1.   potion ( precombat - 1 ) - ability disabled.
        2.   raise_dead ( precombat - 2 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        3.   azsharas_font_of_power ( precombat - 3 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        4.   army_of_the_dead ( precombat - 4 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
    
    Completed precombat action list [ Unholy - precombat ].
    
    Processing default action list [ Unholy - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        5.   mind_freeze ( default - 1 ) - ability disabled.
        6.   variable ( default - 2 )
         - variable.pooling_for_gargoyle will check this script entry (Unholy:default:2).
        7.   arcane_torrent ( default - 3 )
        The action (arcane_torrent) is usable at (4.42 + 1.20) with cost of 0.
         - the action is ready before the current recommendation (at +1.20 vs. +60.00).
         - this entry's criteria FAILS: runic_power.deficit[70.00] > 65 & ( pet.gargoyle.active[false] | ! talent.summon_gargoyle.enabled[false] ) & rune.deficit[nil] >= 5
        There were no recheck events to check.
        8.   blood_fury ( default - 4 ) - ability unknown
        9.   berserking ( default - 5 ) - ability unknown
        10.  lights_judgment ( default - 6 ) - ability unknown
        11.  ancestral_call ( default - 7 ) - ability unknown
        12.  arcane_pulse ( default - 8 ) - ability unknown
        13.  fireblood ( default - 9 ) - ability unknown
        14.  bag_of_tricks ( default - 10 ) - ability unknown
        15.  use_items ( default - 11 )
        Criteria PASS at +4.42 - time[0.00] > 20 | ! equipped.ramping_amplitude_gigavolt_engine[false] | ! equipped.vision_of_demise[false]
        Current recommendation was NO ACTION at +60.00s.
        16.  heart_essence ( items - 1 )
        The action (heart_essence) is unusable at (4.42 + 1.20) because your equipped major essence is supported elsewhere in the priority or is not an active ability.
        Returned from Use Items; current recommendation is NO ACTION (+60.00).
        17.  azsharas_font_of_power ( default - 12 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        18.  azsharas_font_of_power ( default - 13 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        19.  azsharas_font_of_power ( default - 14 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        20.  ashvanes_razor_coral ( default - 15 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        21.  ashvanes_razor_coral ( default - 16 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        22.  ashvanes_razor_coral ( default - 17 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        23.  ashvanes_razor_coral ( default - 18 )
        The action is not ready before our maximum delay window (15.00) for this query.
        
        24.  vision_of_demise ( default - 19 )
        The action (vision_of_demise) is unusable at (4.42 + 1.20) because item not equipped.
        25.  ramping_amplitude_gigavolt_engine ( default - 20 )
        The action (ramping_amplitude_gigavolt_engine) is unusable at (4.42 + 1.20) because item not equipped.
        26.  bygone_bee_almanac ( default - 21 )
        The action (bygone_bee_almanac) is unusable at (4.42 + 1.20) because item not equipped.
        27.  jes_howler ( default - 22 )
        The action (jes_howler) is unusable at (4.42 + 1.20) because item not equipped.
        28.  galecallers_beak ( default - 23 )
        The action (galecallers_beak) is unusable at (4.42 + 1.20) because item not equipped.
        29.  grongs_primal_rage ( default - 24 )
        The action (grongs_primal_rage) is unusable at (4.42 + 1.20) because item not equipped.
        30.  potion ( default - 25 ) - ability disabled.
        31.  outbreak ( default - 26 )
        The action (outbreak) is usable at (4.42 + 1.20) with cost of 1.
         - the action is ready before the current recommendation (at +1.20 vs. +60.00).
         - this entry's criteria PASSES: dot.virulent_plague.remains[0.00] <= gcd.execute[1.20]
        Action chosen:  outbreak at 1.20!
        32.  call_action_list ( default - 27 )
        There is no criteria for this action list..
        Action list (essences) was found.
        + essences
        Current recommendation was outbreak at +1.20s.
        The recommended action (outbreak) would be ready before the next GCD (1.20 < 1.20); exiting list (essences).
        Returned from list (essences), current recommendation is outbreak (+1.20).
        - essences
        The recommended action (outbreak) would be ready before the next GCD (1.20 < 1.20); exiting list (default).
    
    Completed default action list [ Unholy - default ].
    Recommendation is outbreak at 4.42 + 1.20.
    Recommendation #4 is outbreak at 1.20s (5.62s).

**Comment by Hekili** [comment]
I'll take a look, but in the future, please use pastebin per the instructions so that tickets remain reasonably readable.

**Comment by Hekili** [comment]
Please review:

>  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot. This is not a screenshot. A snapshot can be generated by binding the Pause feature on the Toggles tab. When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab. Copy and paste this to pastebin.com and provide the link here.

You didn't provide a snapshot when you thought Apocalypse should've been recommended, so I can't do anything with the snapshot provided.

**Comment by Tobbelainen** [comment]
ok so what should i do? provide the snapshot in the exact moment? when in aoe the frame dont even want to use apoc its skipping it totally until its just single target =/

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/75096030-22ae5980-5569-11ea-9e9c-04e0a59d5e84.png)

I can't replicate the problem, here is Apocalypse being recommended in multi-target without issue.  Using the same talents as you.

You can still get a snapshot even if there does not appear to be a recommendation.

**Comment by Tobbelainen** [comment]
thats weird i using the atomatic display mode and dont show is the essence giving the bugg maybe?

**Comment by Hekili** [comment]
There is no way for me to know without a snapshot.  You can go to a few target dummies and build up 4+ festering wounds and then take a snapshot and post it here.

**Comment by Tobbelainen** [comment]
https://pastebin.com/t5qR1kRm

**Comment by Tobbelainen** [comment]
sure i go and do that did try again btw and the link is up, not sure if that helped tho

**Comment by Hekili** [comment]
So, I'm guessing by this snapshot that you didn't actually attack a dummy.  It has 6 runes and 0 runic power, and you haven't raised a ghoul yet.

**Comment by Tobbelainen** [comment]
if fix a new here^^

**Comment by Tobbelainen** [comment]
[repeat paste deleted]

**Comment by Hekili** [comment]
You're not selecting the newest snapshot.  You've pasted the same snapshot 3 times, and for some reason are still not using pastebin as I've asked.

**Comment by Tobbelainen** [comment]
ooh fuck im noob on this ^^ i fix

**Comment by Tobbelainen** [comment]
noob question how to i use the pastebin?

**Comment by Hekili** [comment]
Go to pastebin.com and paste the text there, click "Create New Paste."  Then provide the link here.

**Comment by Tobbelainen** [comment]
[w382JjMP.txt](https://github.com/Hekili/hekili/files/4239632/w382JjMP.txt)

**Comment by Tobbelainen** [comment]
https://pastebin.com/w382JjMP

**Comment by Tobbelainen** [comment]
https://pastebin.com/W8mXiNgt there's my second attempt when all my cd was up and didnt wanted the apoc to use =/ but maybe there's something i have turned off or on no clue ty in advance best addon anyway =)

**Comment by Hekili** [comment]
> - this entry's criteria FAILS: debuff.festering_wound.stack[6.00] >= 4 & ( ! essence.vision_of_perfection.enabled[true] | essence.vision_of_perfection.enabled[true] & ( talent.unholy_frenzy.enabled[true] & cooldown.unholy_frenzy.remains[70.80] <= 3 | ! talent.unholy_frenzy.enabled[true] ) )

So, with VoP slotted and Unholy Frenzy talented, the priority wants you to hit Apocalypse before you pop Unholy Frenzy.  It looks like you're popping Unholy Frenzy first (maybe you've macroed UF to Army or something?).

**Comment by Tobbelainen** [comment]
ok weird havent macroed uf to army and the apoc picture doesnt show before unholy frency for me only on single target =/

**Comment by Tobbelainen** [comment]
https://pastebin.com/G7aEKU6L this is just before poping Unholy frenzy

**Comment by Hekili** [comment]
Your last snapshot is helpful.  I ran a sim of the default Unholy profile and there is some odd behavior around Apocalypse and Unholy Frenzy.

I'll have to investigate a bit, because as far as I can tell, the sim profile should be failing to cast Apocalypse in multi-target but isn't, so there is some internal logic I will probably have to emulate.

**Comment by Tobbelainen** [comment]
ooh thanks, thought there was something weird but i am not an expert on this matter but i´m glad that i learned how to send a proper snapshot after so many attempts haha xD

**Comment by Hekili** [comment]
Yeah, thanks for sticking with me and getting me data I could use.

It looks like the entry for Apocalypse is missing a condition that is in SimulationCraft.

If you go to /hekili > Priorities > Unholy > Action Lists > Action List: cooldowns > Entry: 2, you can delete the Conditions and paste the following:

`debuff.festering_wound.stack >= 4 & ( active_enemies >= 2 | ! essence.vision_of_perfection.enabled | essence.vision_of_perfection.enabled & ( talent.unholy_frenzy.enabled & cooldown.unholy_frenzy.remains <= 3 | ! talent.unholy_frenzy.enabled ) )`

The `active_enemies >= 2 |` part is missing from the addon at the moment.

**Comment by Tobbelainen** [comment]
1000% much thanks it worked perfect =)
