### ISSUE TITLE
[REC] Frost Mage water elemental not detected

### ISSUE THREAD

**Issue by chevyn11** [Hekili/hekili#2853]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Frost Mage I expect freeze (pet spell) to be recommended when I have a water elemental out due to Icy Veins.

### How to Reproduce

1. Enter game as Frost Mage
2. Use Icy Veins
3. Notice Water elemental is out
4. Freeze (pet ability) never recommended

### Snapshot (Link)

https://pastebin.com/yxBC6v3t

### Additional Information

Relevant parts of the snapshot (imo)

Icy veins is up:
```player_buffs:
     1459 - arcane_intellect                         -   1 - 2671.41
    12472 - icy_veins                                -   1 - 24.10 
```

Freeze recommendation:
```
        22.  freeze ( aoe - 5 )
        The action (freeze) is unusable at (0.79 + 0.94) because requires water elemental.
        Time spent on this action:  0.04ms
        TimeData:Frost Mage-aoe-5:freeze:0.04:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)
```

**Comment by Hekili** [comment]
Are you using a cosmetic glyph on your Water Elemental?  If so, which?

Does this occur if you've summoned your Water Elemental but have not reloaded your UI?

**Comment by chevyn11** [comment]
No glyph, this is a fairly new fotm reroll mage :D

I cant summon a water elemental any other way (afaik?), its just summoned as part of icy veins now.
