### ISSUE TITLE
[REC] [PTR] Outlaw rogue opener issues

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2855]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Apologies if you are not accepting tickets for beta/PTR versions but thought it might be helpful.

1) Opener is recommending Stealth as the first precombat action, this is incorrect - it should be recommending at least Blade Flurry before stealth, and potentially Roll the Bones, Adrenaline Rush, and Slice and Dice too. (snapshot 1)
2) Once Blade Flurry is pressed in the opener, the preview actions change drastically, e.g. it goes from ADR -> RTB, no slice and dice, and sinister strikes to RTB -> ADR with slice and dice and ambushes, the latter is more correct but should be that way precombat too (snapshot 1 vs snapshot 2)
3) Recommending Slide and Dice twice in a row (snapshot 3) which isnt even possible due to it trying to re-apply a lower cp SND 

Note snapshot 2 is weird, because when I take the snapshot, the addon changes what it logs vs what it shows on screen (i can see this swapping around visibly on screen). In the snapshot v2 it says its recommending Adrenaline Rush as action #2, but on screen before i take the snapshot, its actually roll the bones as action #2 (the latter of which is correct as you want to RTB before ADR in opener with 4pc). I can repeat this multiple times so its not a matter of me _just_ pressing the snapshot button during a state change. If you want to try and debug this, all you have to do is press blade flurry and attempt to take a snaoshot.

Snapshot 1: https://pastebin.com/6byzbTRB
Snapshot 2: https://pastebin.com/9fecF5mw
Snapshot 3: https://pastebin.com/FEDuHuAQ

### How to Reproduce

As Above

### Snapshot (Link)

Linked in main comment

**Comment by Hekili** [comment]
I will remove the early Stealth entry in precombat, and I'm modifying Blade Flurry to not start combat unless you're in range of your target so that the recommendations don't flip to in-combat recommendations (and back) prematurely.
