### ISSUE TITLE
Assa Rogue Icons not visible

### ISSUE THREAD

**Issue by bettercallme7** [Hekili/hekili#2856]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

the icons are not visible
i made a personal quick sim run and copy paste the html profile from my character. also the normal profil is not showing any icons.

### How to Reproduce

![Unbenannt](https://github.com/Hekili/hekili/assets/150064604/26e283d4-cf70-41a3-ad15-d60b70846a3c)

### Player Information (Link)

https://pastebin.com/d2a472pc

### Error Messages (Link)

no mistakes says bugsack

**Comment by SpatenLa** [comment]
do not import anything. reset your profile. you broke it.

**Comment by bettercallme7** [comment]
It worked also with the imported html. On the other two specs it works also with the imported code.
Just on assasination specc it will not show the icons - sometimes just one, then no one.

**Comment by SpatenLa** [comment]
importing stuff isnt good. thats not how simcraft works. the apl isnt generated for your char. the apl is a general purpose take everything into account list. importing a apl makes it worse than the apl already in hekili because he has to massage some things in that arent 100% translateable from how its written.
DO NOT IMPORT if you didnt change anything yourself and have no idea how this works.
you broke the addon by importing.

**Comment by bettercallme7** [comment]
It works on all my chas - each single specc - just one is not working. So I didn´t broke it. It is just the visibility from the incoming icons. If u dont know the mistake its fine. I will figure it out myself.

**Comment by SpatenLa** [comment]
its not. the snapshot clearly shows massive errors. Reset it. its not about visibility. there are no reccomendations because it cant read anything.

**Comment by bettercallme7** [comment]
![Unbenannt](https://github.com/Hekili/hekili/assets/150064604/9dcd6f59-f400-4fb4-b5b9-91415aca0760)

**Comment by bettercallme7** [comment]
Then please tell me how can i reset it.

**Comment by SpatenLa** [comment]
![grafik](https://github.com/Hekili/hekili/assets/39881841/fbafa8ab-9c3e-4e10-a7bf-4bfda3c4c785)

**Comment by bettercallme7** [comment]
I reset the assa specc. I dont know why its just here not working
Have a nice one mate

**Comment by Hekili** [comment]
You installed the beta for 10.2 and are using it on live.  You'll want to downgrade and then reset that priority, then /reload your UI.
