### ISSUE TITLE
Hekili Discord Ran by Wittle Butthurt Snowflakes

### ISSUE THREAD

**Issue by reale411** [Hekili/hekili#2858]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Asked a question on Discord about Augmentation and was told to sim it, yet there are no sims for Augmentation. Because the wittle snowflakes got all poopoo'd about it, they used their mighty internet powa to boot me from the channel. Another safe space hitler, loser.

**Comment by Hekili** [comment]
betterhelp.com
