### ISSUE TITLE
BM Hunter 10.2 APL fix + remove shadowlands trinket?

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#2859]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

1) Flip the logic comparison on line 25 as per [this simc change](https://github.com/simulationcraft/simc/commit/3001c49c690a69c6595ece4ba05c15b82cc93de8)

actions.cleave+=/multishot,if=pet.main.buff.beast_cleave.remains**_>_**0.25+gcd&(!talent.bloody_frenzy|cooldown.call_of_the_wild.remains)
actions.cleave+=/multishot,if=pet.main.buff.beast_cleave.remains**_<_**0.25+gcd&(!talent.bloody_frenzy|cooldown.call_of_the_wild.remains)

2) Remove line 2 "actions.precombat+=/bottled_flayedwing_toxin" as this is an old shadowlands trinket?

### How to Reproduce

change is already on simc git

### Snapshot (Link)

https://github.com/simulationcraft/simc/commit/3001c49c690a69c6595ece4ba05c15b82cc93de8

**Comment by Hekili** [comment]
I'll leave the trinket for leveling from Shadowlands, but the other APL update will be included.
