### ISSUE TITLE
[FEATURE] Add Item: Libram of Three Truths (WOTLK Classic)

### ISSUE THREAD

**Issue by chasekd** [Hekili/hekili#2860]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Please add support for the item Libram of Three Truths (proc name = formidable, spell id = 71187). Tracking the buff from this item is critical for retribution paladins in ICC, as dropping 5 stacks of the buff while using DS (t10 2 set) procs will result in a large dps loss. 

### Contact Information

discord ID: chasekd

**Comment by Supernuss** [comment]
@chasekd @Hekili implemented in https://github.com/Hekili/hekili/pull/2896
