### ISSUE TITLE
Secret Technique Not Showing Up In Rotation

### ISSUE THREAD

**Issue by Fowka2** [Hekili/hekili#2861]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'll be in dungeons or training dummy, following everything that Hekili is telling me to press. However, I've realised it's not telling me to use "Secret Technique" at all. I've got Cooldowns, Minor CDs active and still doesn't show me to use "Secret Technique"

### How to Reproduce

1. Enter game as Subtlety Rogue
2. Take the "Secret Technique" talent.
3. Go to training dummy 
4. Start in "Stealth" 
5. Follow the rotation Hekili has prioritised 

### Snapshot (Link)

https://pastebin.com/aDrr9RHA

### Contact Information

Majór#3090 (DISCORD)

**Comment by syrifgit** [comment]
It says 10.1.7 in the snapshot, but throwing errors related to 10.2 trinkets

**Comment by Hekili** [comment]
If you upgraded to 10.2 and then downgraded to 10.1.7, you'll need to reset the priority back to 10.1.7 as well.  See the little circle arrow on /hek > Priorities > Subtlety screen.
