### ISSUE TITLE
[REC] Outlaw rogue still recommending double slice and dice in opener

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2862]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon recommending two consecutive slice and dices.

### How to Reproduce

1. Spec into HO raid spec BQQAt5bPuh6pO3KIPROgVVbp4CAEkkEJCSSIJCSkkmkEtkIlkAAAAAAAaJJkERhcgSaBAAAQSCA
2. Addon recommends double slice and dice, which isn't even possible to use

### Snapshot (Link)

https://pastebin.com/4Ci5yeEM

**Comment by obolwako** [comment]
I've noticed the same issue

**Comment by Hekili** [comment]
This has been resolved.
