### ISSUE TITLE
Items, Macros may not show keybinds due to Blizzard API

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#2863]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Some skills don't show the keybind anymore for some skills

### How to Reproduce

go to emerald dreams and try to quest.

### Snapshot (Link)

Destruction; Primary - Incinerate(0.00), Conflagrate(1.55)

### Additional Information

<img width="734" alt="image" src="https://github.com/Hekili/hekili/assets/1850089/e04c1243-5000-4537-a366-ca7b67ca4aac">
I didn't have an option to export anything for snapshot, this is all thats shown.

### Contact Information

N6REJ

**Comment by lightmgl** [comment]
Presumably the same issue but this is happening to me for any ability that is on a Macro.

**Comment by JourneyOver** [comment]
Yea I'm sadly having the same issue that @lightmgl seems to be having where any abilities that are macros are currently not showing any keybinds.

**Comment by KusalJ** [comment]
Same issue, it doesn't show keybinds if the spell is part of a macro (regardless of class):
With Macro: ![image](https://github.com/Hekili/hekili/assets/8160685/0017cb4b-9cc9-457e-87e7-452d2d74d75e)
Without Macro: 
![image](https://github.com/Hekili/hekili/assets/8160685/446bc84c-8377-492b-a035-79997b00a2af)

**Comment by gnew95** [comment]
This one you can fix yourself! If you go to hekili options through /hekili and then the abilities tab you can type in the keybind text you want to appear. Here is an image to help! (You can choose the ability keybind you want to change in the top right. Currently I have adrenaline rush selected)
![image](https://github.com/Hekili/hekili/assets/101494776/603d1bd6-6586-474a-8c86-80c27a9b8148)

**Comment by N6REJ** [comment]
> This one you can fix yourself! If you go to hekili options through /hekili and then the abilities tab you can type in the keybind text you want to appear. Here is an image to help! (You can choose the ability keybind you want to change in the top right. Currently I have adrenaline rush selected) ![image](https://user-images.githubusercontent.com/101494776/281265228-603d1bd6-6586-474a-8c86-80c27a9b8148.png)

thats great to know for some things that don't show.  I always added it to a weakaura lol
in my case its not a macro'd skill thats causing the issue but UNMACRO'd ones..
<img width="607" alt="image" src="https://github.com/Hekili/hekili/assets/1850089/0227935f-9d3e-4ca0-a6dc-4fac34d873e8">

**Comment by N6REJ** [comment]
Happens on my horde DK also.  Again, no error and snapshot doesn't work.  This time its a macro that doesn't show
<img width="261" alt="image" src="https://github.com/Hekili/hekili/assets/1850089/071aa803-b317-405c-8105-552d13938812">

**Comment by RussellAnas** [comment]
Same issue happening on my side. Bunch of keys not showing keybinds. It used to work perfect before.

**Comment by IronicConny** [comment]
> This one you can fix yourself! If you go to hekili options through /hekili and then the abilities tab you can type in the keybind text you want to appear. Here is an image to help! (You can choose the ability keybind you want to change in the top right. Currently I have adrenaline rush selected) ![image](https://user-images.githubusercontent.com/101494776/281265228-603d1bd6-6586-474a-8c86-80c27a9b8148.png)

This did miracles! THX

**Comment by marclapl** [comment]
Related to this issue in the updated 10.2 UI of dragonflight:

https://github.com/Stanzilla/WoWUIBugs/issues/495

It's an easy fix, in Events.lua:

![image](https://github.com/Hekili/hekili/assets/67342980/ff8b7f90-1853-4b3b-b209-8f5ba868c2f4)

**Comment by howlenoates** [comment]
> Presumably the same issue but this is happening to me for any ability that is on a Macro.

same for me

**Comment by N6REJ** [comment]
discovered using abilities doesn't work for death & decay
<img width="681" alt="image" src="https://github.com/Hekili/hekili/assets/1850089/32ee67ab-5a70-4182-84b1-055fb0f251d6">

**Comment by JourneyOver** [comment]
> Related to this issue in the updated 10.2 UI of dragonflight:
> 
> [Stanzilla/WoWUIBugs#495](https://github.com/Stanzilla/WoWUIBugs/issues/495)
> 
> It's an easy fix, in Events.lua:
> 
> ![image](https://user-images.githubusercontent.com/67342980/281444549-ff8b7f90-1853-4b3b-b209-8f5ba868c2f4.png)

This line no longer exists in the latest version (10.2.0-1.0.0c), but the issue sadly still remains for macro's not having their keybinds shown.

**Comment by JourneyOver** [comment]
So it looks like macros that are for skills are working correctly and shows the keybinds now.. but any macros that are for items (example being trinkets you have equipped) like:

```
#showtooltip
/cast 13
```

or
```
#showtooltip
/use 13
```

still sadly seem to not show the keybinds as of yet.

**Comment by howlenoates** [comment]
> So it looks like macros that are for skills are working correctly and shows the keybinds now.. but any macros that are for items (example being trinkets you have equipped) like:
> 
> ```
> #showtooltip
> /cast 13
> ```
> 
> or
> 
> ```
> #showtooltip
> /use 13
> ```
> 
> still sadly seem to not show the keybinds as of yet.

same here, items in macros no longer showing keybinds

**Comment by howlenoates** [comment]
the kebinds of macro'ed items are currently still not showing up

**Comment by JourneyOver** [comment]
Any word on when keybinds for macro'ed items are ever going to be fixed? This is still an ongoing issue.

**Comment by Hekili** [comment]
...when Blizzard fixes their API.

**Comment by Benwarz** [comment]
Hi, I am trying to use a macro (ability, not item) but Hekili won't show the keybind. Am I missing a setting somewhere, maybe, or... thank you for an absolute mind-boggling controller app for WoW, btw.. I have painful arthritis hands and controller helps me play pain-free. tysm

**Comment by Benwarz** [comment]
So, I was having a problem with Hekili not (always) showing my Xbox controller keybinding icons on macroes for macroed abilities (not items). Specifically, I have this Druid macro:

#showtooltip 
/cast [nostealth, nocombat] Prowl; Rake

I also have one exactly like this but for Shred. I haven't nailed down the exact cause, but UI reloads seem to almost always, if not always, remove the controller bind icons from the primary Hekili rotation bar. The macroes are still there with the correct abilities/tooltips, but the little 'X' and 'B' button icons disappear. I found if you go into ConsolePort -> Bindings, there's a little yellow arrow on the far left. Click that to expand a gui for adding binds. Now, the thing is, my Druid has to be stealthed for this to work. The icon then changes from Prowl to Rake, and when I add the above macro back to the 'X' button where it normally is, Hekili picks up the change and adds the correct 'X' (and 'B' for Shred) button controller icons back to the Rake and Shred macroes in the primary Hekili bar. It will work like this for quite awhile, but again, I'm pretty sure any reloading or otherwise refreshing of the UI will cause these to disappear again. But if you repeat the above process you can add them back in just a few moments. You only need to add one of them back and the binds show for both. This is probably confusing as hell but I tried to explain well.. anyway, thx for an awesome mod.. truly amazing work!

**Comment by Benwarz** [comment]
> So, I was having a problem with Hekili not (always) showing my Xbox controller keybinding icons on macroes for macroed abilities (not items). Specifically, I have this Druid macro:
> 
> #showtooltip /cast [nostealth, nocombat] Prowl; Rake
> 
> I also have one exactly like this but for Shred. I haven't nailed down the exact cause, but UI reloads seem to almost always, if not always, remove the controller bind icons from the primary Hekili rotation bar. If you go into ConsolePort -> Bindings, there's a little yellow arrow on the far left. Click that to expand a gui for adding binds. Now, the thing is, my Druid has to be stealthed for this to work. The icon then changes from Prowl to Rake, and when I add the above macro back to the 'X' button where it normally is, Hekili picks up the change and adds the correct 'X' (and 'B' for Shred) button controller icons back to the Rake and Shred macroes in the primary Hekili bar. It will work like this for quite awhile, but again, I'm pretty sure any reloading or otherwise refreshing of the UI will cause these to disappear again. But if you repeat the above process you can add them back in just a few moments. You only need to add one of them back and the binds show for both. This is probably confusing as hell but I tried to explain well.. anyway, thx for an awesome mod.. truly amazing work.

**Comment by Bronski** [comment]
I've been having trouble with some keybinds not showing on my Rogue. Specifically, Ambush, which isn't always showing (BT4 bar switches for stealth). I used the above workaround to force it to show the right key always.

As a programming workaround, perhaps the mod can remember the last keybind it showed for each ability and start by showing that instantly. If it then detects it has changed, it will update the bind shown and remember it for next time.
