### ISSUE TITLE
[REC] MM Hunter Recommendations going blank after Multi-Shot/Volley in AOE situations

### ISSUE THREAD

**Issue by mackdoherty** [Hekili/hekili#2864]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Was testing out the new builds and was somewhat surprised when, after multi-shot or volley hit multiple mobs, the recommendations from the add-on disappeared, and stayed gone. 

### How to Reproduce

1. Make sure you're in a M+ MM spec.
2. Go to the target dummies.
3. Hit multi-shot or volley when targeting a dummy in the pack.

### Snapshot (Link)

https://pastebin.com/wJAcvXxP

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pDqAykecLCa1MGoAkXdzp9

### Contact Information

Discord - Herniation

**Comment by mackdoherty** [comment]
Added data: it looks like where I'm facing impacts it? If I look away, the recommendations return, if I face the targets it disappears again.

**Comment by Hekili** [comment]
The addon doesn't -- cannot -- know anything about facing.  A good chunk of the Marksman priority was missing.  This should already be resolved in 10.2.0-1.0.0c.  Thanks!
