### ISSUE TITLE
UH DK Still Recommending Dark Arbiter Even After Use

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#2865]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While following addon.  Dark Arbiter still showing as not used on priority even after it has been pressed.  Continues to be a top suggestion even while on cooldown.

### How to Reproduce

1. Enter game as Unholy Death Knight.
2. Target enemy with cooldowns toggled on and follow recommendation.
3. Press Gargoyle / Dark Arbiter.
4. Spell still recommended.

### Snapshot (Link)

https://pastebin.com/6nsZYbSS

**Comment by Hekili** [comment]
I'll need to make the ability understand when it is glyphed.  Thanks.

**Comment by Hekili** [comment]
This should be fixed in today's release.

**Comment by UltiDeeps** [comment]
Seems to still be persisting.  Even when swapping off of DA into gargoyle

**Comment by Hekili** [comment]
Can you post an updated snapshot along with the output from `/dump GetSpellInfo("Summon Gargoyle")` and `/dump GetSpellInfo("Dark Arbiter")` please?

**Comment by UltiDeeps** [comment]
Not a problem on the snapshot. I'm home from work today and will grab it
when servers hop back on. I am absolutely clueless on how to obtain the
/dump information, any place I can find a tutorial on that part?

**Comment by Hekili** [comment]
Just paste that into chat and press enter, it'll post a few values into your chat that you can screengrab.

**Comment by UltiDeeps** [comment]
DA still being suggested after cast: https://pastebin.com/DCA9P6PZ
Attempted to replicate with gargoyle like last night but can't and seems to
work now: https://pastebin.com/jyUaC67n

Dump: value=GetSpellInfo("Summon Gargoyle")
[1]="Dark Arbiter",
[3]=298674,
[4]=0,
[5]=0,
[6]=30,
[7]=207349,
[8]=298674

Dump: value=GetSpellInfo("Dark Arbiter")
[1]="Dark Arbiter",
[3]=298674,
[4]=0,
[5]=0,
[6]=30,
[7]=207349,
[8]=298674

**Comment by Echo9G** [comment]
UPDATE :  Its not a glyph but the cosmetic choice from trainer in Archerus that isn't working if you select Valk appearance instead of default Gargoyle, but when I removed it, it works again ....  if I use Valk, it's not recognizing active Gargoyle.

My values from the chat statements match Ultideeps.

I just noticed this exact issue, having the same exact problem, but I guess I'll remove the glyph for now since that is the problem?

**Comment by Hekili** [comment]
Yeah, it's weird that it works for me with the glyphed appearance from the trainer.

**Comment by Echo9G** [comment]
> Yeah, it's weird that it works for me with the glyphed appearance from the trainer.

Was working for me as well for many months now, just recently stopped, I guess with the latest patch.

**Comment by UltiDeeps** [comment]
I have noticed after swapping from frost I will get issues.

**Comment by Echo9G** [comment]
Any updates by chance?

**Comment by Dolch0812** [comment]
by now the best solution for this is going to acherus and changing the arbiter for gargoyle

**Comment by Hyphie24** [comment]
Was looking to see if this was a known issue and saw this post, I went to acherus and changed my gargoyle to arbiter and the ability is still getting stuck. It even breaks hekili and sometimes doesn't know what ability to use thinking that it hasn't been used at all. It will eventually go away, but only if it thinks it's a bad time to use, usually after a min & a half in combat

From what I've noticed there isn't a lua error, but I also haven't been looking for it

![image](https://github.com/Hekili/hekili/assets/31455641/867155bf-04c4-46e4-b10e-ac26b5f50dc3)

no lua error, while on target dummy

**Comment by Hekili** [comment]
I'll post a beta fix as 1.0.5-beta1

**Comment by Hyphie24** [comment]
That seems to have fixed for it not seeing Arbiter being used :D

Don't know about someone who hasn't changed Gargoyle to Arbiter
