### ISSUE TITLE
[BUG] Hekili doesn't show for druid

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#2866]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

My son reports that hekili isn't showing for any spec on his druid.  We tried ALT+SHIFT+[ and no snapshot was taken.
The addon is loaded and when he types /hekili it does show where its supposed to be but when he closes hekili nothing is there.
![image](https://github.com/Hekili/hekili/assets/1850089/7dc0b1d3-0951-4260-9064-77521a604151)
****

### How to Reproduce

load a druid in season 3

### Player Information (Link)

Doesn't display anything as shown in screenshot

### Error Messages (Link)

none possible to show

### Contact Information

N6REJ

**Comment by Hekili** [comment]
Looks like you're in 10.2 content with a 10.1.7 version of the addon.  Make sure he upgrades to the latest version.

**Comment by N6REJ** [comment]
ty that was the problem.  he said "I feel mighty stupid right now"
