### ISSUE TITLE
[BUG] Wrong Icon For Class Ability

### ISSUE THREAD

**Issue by Iwantweiner** [Hekili/hekili#2867]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![hel](https://github.com/Hekili/hekili/assets/150220977/eaccbe96-33f6-4840-a9fb-0cb014ec0897)

### How to Reproduce

1. Enter game as Vengeance Demon Hunter
2. Switch to Havoc Hunter
3. Have Fel Blade talent
4. Fel Blade icon shows as Sigil of Flame icon

### Player Information (Link)

https://pastebin.com/an0Lp287

### Error Messages (Link)

n/a

### Additional Information

d=

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Iwantweiner** [comment]
I'm sorry for wasting your time! I just swapped specs once more and the issue resolved itself. Thank you
