### ISSUE TITLE
Sub Rogue not recommending Secret Technique

### ISSUE THREAD

**Issue by BeemMN** [Hekili/hekili#2868]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [x] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon fails to recommend Shadow Technique at all and keeps telling you to press Eviscerate during Shadow Dance

### How to Reproduce

1. Use talents BUQAt5bPuh6pO3KIPROgVVbp4CAEEAAAAAASJJJlERSKlEhIESSSISLlIJaJJSSCgSaBAAAgEEA
2. Follow default rotation to Shadow Dance

### Snapshot (Link)

https://pastebin.com/dXavA5uG

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/miKXoAiL56Ptgzk572hJN4

### Contact Information

beam_mn on discord

**Comment by syrifgit** [comment]
I did some testing and it appears that the secret_condition is not tracking danse macabre correctly. I had a bunch of stacks, having used every ability, and every value in the secret_condition was still 0

![image](https://github.com/Hekili/hekili/assets/139663837/2943f1cf-1aa7-4bd4-acb1-a5878bfbc447)

![image](https://github.com/Hekili/hekili/assets/139663837/1dfd80dd-bc77-4f6e-aaf2-01f69e65b781)

I also noticed that cold blooded and Symbols of Death are completely failing as well, showing as red entries in the action list despite being talented and enabled. They are also not being recommended alongside secret technique.

![image](https://github.com/Hekili/hekili/assets/139663837/9d7855da-9cac-47a9-9136-5df53f7702d2)

**Comment by Hekili** [comment]
> I did some testing and it appears that the secret_condition is not tracking danse macabre correctly. I had a bunch of stacks, having used every ability, and every value in the secret_condition was still 0

Being able to track danse for other abilities via `action.X.used_for_danse` (vs. just the action being tested, via `used_for_danse`) was not implemented.  It'll be in the next release.

> I also noticed that cold blooded and Symbols of Death are completely failing as well, showing as red entries in the action list despite being talented and enabled. They are also not being recommended alongside secret technique.

I couldn't replicate this part.

**Comment by syrifgit** [comment]
The danse tracker variable is now working correctly, but secret technique still wont recommend because of the cold blood issue.

If you untalent cold blood, secret technique starts working again. :)

**Comment by Hekili** [comment]
Is Cold Blood disabled there because of the buff already being applied?  Is the issue that Cold Blood doesn't truly go on cooldown until the buff is consumed?

**Comment by syrifgit** [comment]
The issue was user error. :) Cold blood is not broken lol

https://discord.com/channels/307520968895627264/307520968895627264/1171833817867231242

**Comment by Hekili** [comment]
Ok, so this is fully resolved?

**Comment by syrifgit** [comment]
Yep!
