### ISSUE TITLE
Outlaw Rogue problems, with SND and BTE

### ISSUE THREAD

**Issue by Sebas0908123** [Hekili/hekili#2869]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

There is problems with addon keep wanting to use SND and BTE, even though they are allready up, other than that it doesnt seem to want to use Keep it Rolling and reroll dices.

### How to Reproduce

just go target dummy or any enemy.

### Player Information (Link)

https://pastebin.com/3e7xb7QC

### Error Messages (Link)

isnt any

### Contact Information

Discord : Tjubiged

**Comment by fzarr** [comment]
The snd thing is an issue I've seen myself,. With crackshot you want to spam bte as much as possible in stealth so what you're describing there may not be an issue.

**Comment by Hekili** [comment]
This will be fixed next release.
