### ISSUE TITLE
Unholy DK - Outbreak getting stuck

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#287]
Outbreak gets stuck, telling me to use it right after I have used it. Pushing another button or the next suggested ability progresses the display forward and then all is working again.

I've had the same thing occurring on my Balance Druid with Sunfire.

I should say this is not 100% all the time. Seems to happen randomly and I have not found a way to reproduce it.

```
build: Development-20200225
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    asphyxiate
    ebon_fever
    epidemic
    soul_reaper
    unholy_frenzy
    wraith_walk

azerite: azerite_empowered = 3
    blood_rite = 1
    festermight = 2
    heed_my_call = 2
    magus_of_the_dead = 3
    march_of_the_damned = 1
    resounding_protection = 2
    unstable_flames = 1

essences: [vision_of_perfection] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 4

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    ballast_sinkers = 1
    bracers_of_phantom_pains = 1
    breastplate_of_arterial_protection = 1
    dark_crystalline_girdle = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    living_obsidian_legguards = 1
    logg = 1
    pauldrons_of_infinite_darkness = 1
    ropescored_gauntlets = 1
    seal_of_questionable_loyalties = 1
    seal_of_the_regal_loa = 1
    second_sight_helm = 1
    vitacharged_titanshard = 1

corruptions: echoing_void = 1
    racing_pulse = 2
    twisted_appendage = 2

itemIDs: 158075, 158314, 159428, 159429, 159432, 159458, 169050, 169223, 174044, 174163, 174166, 174171, 174172, 174177, 174500

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    festermight_cycle = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = dual
    potions = false

```

**Comment by Hekili** [comment]
Fill out a complete ticket with a snapshot when this issue occurs.

Do you have BugSack or BugGrabber?  Are there errors?

**Comment by behub-au** [comment]
No errors and I always run BugSack/BugGrabber. I see the snapshots in settings, but it's all blank. Do I need to do something to enable it capturing?

**Comment by Hekili** [comment]
You deleted the ticket instructions which explained the process.  :)

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by behub-au** [comment]
Sorry, I 've reported many issues in the paste and never had to provide a snapshot so it just became habit for each ticket to just copy and paste and format that into a block of code.

I'll get back to you when it occurrs again.

**Comment by Hekili** [comment]
Thanks.  I generally *try* to reproduce errors when I can, but I literally can't even tell which addon version you are using from the Issue Reporting info (it shows "Development" when you've downloaded the source directly rather than a packaged copy).  Make sure you're up to date.

**Comment by behub-au** [comment]
Run a git pull every time before I start WoW. Living on the edge ;)

**Comment by Hekili** [comment]
That's generally fine, but keep in mind that won't catch library updates that the packager takes care of.

**Comment by behub-au** [comment]
Will close this off for now until I get back to testing it and getting you a snapshot. Could be over a week and will make a proper post as per the requirements I copied over ;)
