### ISSUE TITLE
[REC] Blade Flurry not being recommended as highest priority builder when Deft Maneuvers Talent is enabled and there are 5 targets or more

### ISSUE THREAD

**Issue by outlawrogueforever** [Hekili/hekili#2870]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Blade Flurry is not being used as a builder when talent.deft_maneuvers.enabled & spell_targets >= 5 & ! variable.finish_condition and blade flurry is not on cd.

Hekili ignores these conditions unless blade flurry is about to fall off or is not up.

### How to Reproduce

Attack the 5 cleave dummies in valdrakken following Hekili recommendations.

Based on the current Outlaw profile for 10.2 it should be suggesting Blade Flurry as a builder with Deft Maneuvers Talent enabled as the highest priority builder since it would be at 5 targets, on cd.

Blade flurry is never suggested as a builder, and only when it is about to fall off to refresh its duration.

### Snapshot (Link)

https://pastebin.com/RF60aABx

### Additional Information

![image](https://github.com/Hekili/hekili/assets/124382793/85793102-a14c-42ab-9e69-8d7f32c5aec6)
![image](https://github.com/Hekili/hekili/assets/124382793/474923b8-c4d2-42ee-bf5c-7baffb4aa7f1)

To debug the issue further, I made a copy of the main profile and added a blade flurry recommendation in default to debug to make sure it's being used as a builder at 5 targets or more, with Deft Maneuvers Talent enabled. Still not using Blade Flurry until its about to drop off, so its ignoring the blade flurry recommendation in default.

snapshot for the custom profile debugging blade flurry: https://pastebin.com/gZQqJ4Jc

Could it possible its something to do with this line of code in RogueOutlaw.lua at line 947:

readyTime = function() return buff.blade_flurry.remains - gcd.execute end,

### Contact Information

Ame#9781

**Comment by chevyn11** [comment]
Deleting that readyTime line on my local hekili seems to have worked for me (I assume without this it will get the "real" cd of blade_flurry instead of trying to count it that way). Thanks for the hint :D

**Comment by outlawrogueforever** [comment]
> Deleting that readyTime line on my local hekili seems to have worked for me (I assume without this it will get the "real" cd of blade_flurry instead of trying to count it that way). Thanks for the hint :D

Your welcome, I did the same thing to fix it temporarily when debugging it earlier.

**Comment by outlawrogueforever** [comment]
There is another issue with Sinister strike being used in stealth with HO enabled, suggested while in Subterfuge/ShadowDance instead of ambush. Making a ticket for that now.

**Comment by chevyn11** [comment]
yeah I've seen an issue happen during a key where it recommended roll the dice soon after I hit KIR, afaik nothing will get rerolled because the kir ones have a longer duration. I cant seem to get it to replicate on the dummies though...

**Comment by Hekili** [comment]
I'll remove the readyTime line for Blade Flurry; it was protection against overlapping which we apparently don't care about any longer.

**Comment by outlawrogueforever** [comment]
Thanks Hekili, I'll keep testing thoroughly for anything else.
