### ISSUE TITLE
[REC] Elemental Blast being recommended when Elemental Blast is on cooldown

### ISSUE THREAD

**Issue by Twizzerious** [Hekili/hekili#2871]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Elemental Blast is being recommended while both charges of Elemental Blast is on cooldown.

### How to Reproduce

1) be enhance shaman
2) use all charges of Elemental blast
3) build 5 maelstrom
4) hekili will recommened elemental blast even though its not off cooldown

### Snapshot (Link)

https://pastebin.com/biJKmvbn

### Additional Information

I recall this being an issue at the beginning of last patch as well; if that helps at all. You fixed it pretty quickly from what I recall.

### Contact Information

.Twizz

**Comment by Hekili** [comment]
Thanks.  It's actually recommending Lava Burst, which you still can't do because you have Elemental Blast talented.  I'll prevent that.
