### ISSUE TITLE
[REC] Sinister Strike being recommend while in stealth (Subterfuge or Shadow dance) while playing with HO Talent enabled

### ISSUE THREAD

**Issue by outlawrogueforever** [Hekili/hekili#2873]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sometimes (it doesn't happen every subterfuge or shadow dance window) during subterfuge or shadow dance windows, sinister strike is recommended when it should be ambush.

Playing with Hidden Opportunity talent enabled.

**I think the issue is with stealthed.all, sometimes it returns false when inside subterfuge/shadowdance. Possibly to do with the new UUH interactions?**

Is it also possible because subterfuge is listed as a duration of 3 seconds inside the OutlawRogue.lua? Perhaps need a check for when UUH talent is enabled (talent.underhanded_upper_hand.enabled) to change the duration to 6 seconds instead of 3?

e.g. at line 402:

    subterfuge = {
        id = 115192,
        duration = 3,
        max_stack = 1,
    },
    
And it could be affecting this hook here at line 718 when it applies the subterfuge duration after we use vanish (we exit combat when using vanish at dummies):

```
-- We need to break stealth when we start combat from an ability.
spec:RegisterHook( "runHandler", function( ability )
    local a = class.abilities[ ability ]

    if stealthed.all and ( not a or a.startsCombat ) then
        if buff.stealth.up then
            setCooldown( "stealth", 2 )
            if buff.take_em_by_surprise.up then
                buff.take_em_by_surprise.expires = query_time + 10 * talent.take_em_by_surprise.rank
            end
            if talent.underhanded_upper_hand.enabled then
                applyBuff( "subterfuge" )
            end
        end

        if legendary.mark_of_the_master_assassin.enabled and stealthed.mantle then
            applyBuff( "master_assassins_mark" )
        end

        removeBuff( "stealth" )
        removeBuff( "shadowmeld" )
        removeBuff( "vanish" )
    end

    if buff.cold_blood.up and ( not a or a.startsCombat ) then
        removeBuff( "cold_blood" )
    end

    class.abilities.apply_poison = class.abilities[ action.apply_poison_actual.next_poison ]
end )
```  
    
Snippet of snapshot where it is going wrong, I've included the subterfuge buff being up too. Full snapshot is attached to the ticket.

My buffs:

player_buffs:
   315341 - between_the_eyes                         -   1 - 16.55 
    13750 - adrenaline_rush                          -   1 - 265.81
   315496 - slice_and_dice                           -   1 - 4212.35
     5761 - numbing_poison                           -   1 - 2292.61
   315584 - instant_poison                           -   1 - 2290.89
    13877 - blade_flurry                             -   1 - 835.72
   **115192 - subterfuge                               -   1 - 3.21**  
   
   Recommendation 1:
   
   57.  sinister_strike ( build - 8 )
        The action (sinister_strike) is usable at (0.00 + 0.16) with cost of 45 energy (have 46).
         - the action is ready before the current recommendation (at +0.16 vs. +0.35).
        List ( build ) called from ( Outlaw:default:14 ) would PASS at 0.16.
        NONE
         - this entry has no criteria to test.
        Action chosen:  sinister_strike at 0.16!
        Time spent on this action:  0.10ms
        TimeData:Outlaw-build-8:sinister_strike:0.10:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)
        Exiting build with recommendation of ambush at +0.35s.
        Returned from list (build), current recommendation is sinister_strike (+0.16).
        - build
        The recommended action (sinister_strike) is ready in less than 0.2s; exiting list (default).
        Exiting default with recommendation of NO ACTION at +10.00s.
 
    Completed default action list [ Outlaw - default ].
    Recommendation is sinister_strike at 0.00 + 0.16.
    Recommendation #1 is sinister_strike at 0.16s (0.16s).
    
    
    

    
    
    
    

### How to Reproduce

1. Make sure Hidden Opportunity talent is enabled.
2. Do rotation as usual based on Hekili recommendation
3. Inside Subterfuge or Shadow Dance buff, Sinister Strike is occasionally recommended instead of ambush

### Snapshot (Link)

https://pastebin.com/0ns9UEDd

### Contact Information

Ame#9781

**Comment by Hekili** [comment]
I've made a slider for the "clash" value of Sinister Strike more accessible (/hek > Outlaw or from the minimap dropdown).  If you set it to -0.5, this particular scenario would not have occurred.  Thanks!
