### ISSUE TITLE
[REC] Assassination Rogue showing (now) Passive abilities like Sanguine Blades and Indiscriminate Carnage as useable

### ISSUE THREAD

**Issue by Disastrus** [Hekili/hekili#2874]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Assassination Rogue showing (now) Passive abilities like Sanguine Blades and Indiscriminate Carnage as useable

### How to Reproduce

1.Enter game as Assassination Rogue
2.Attack either single or a group of targets.
3.Passive abilites are suggested by Hekili.

Both Pastebins
Sanguine Blades: https://pastebin.com/2db35tBu
Indiscriminate Carnage: https://pastebin.com/H54n57Qw

---------------------

build: v10.1.7-1.0.7
level: 70 (70)
class: ROGUE
spec: assassination

talents: BMQAt5bPuh6pO3KIPROgVVbp4GJJJhEEAAAAAASJJSLJAAAAAAgWSCSgkkWKJRQSSSQSSRJSAA
    alacrity = 2/2
    amplifying_poison = 1/1
    blind = 1/1
    bloody_mess = 1/1
    cheat_death = 1/1
    cloak_of_shadows = 1/1
    crimson_tempest = 1/1
    dashing_scoundrel = 1/1
    deadened_nerves = 1/1
    deadly_poison = 1/1
    deathmark = 1/1
    deeper_stratagem = 1/1
    doomblade = 1/1
    evasion = 1/1
    exsanguinate = 1/1
    fatal_concoction = 1/1
    fleet_footed = 1/1
    improved_garrote = 1/1
    improved_shiv = 1/1
    improved_sprint = 1/1
    indiscriminate_carnage = 1/1
    iron_stomach = 1/1
    leeching_poison = 1/1
    lethal_dose = 2/2
    master_assassin = 1/1
    master_poisoner = 1/1
    nightstalker = 2/2
    nimble_fingers = 1/1
    numbing_poison = 1/1
    poison_bomb = 2/2
    recuperator = 1/1
    scent_of_blood = 2/2
    seal_fate = 1/1
    shadow_dance = 1/1
    shadowrunner = 1/1
    shadowstep = 1/1
    shiv = 1/1
    shrouded_suffocation = 1/1
    soothing_darkness = 1/1
    subterfuge = 1/1
    thistle_tea = 1/1
    thrown_precision = 1/1
    tricks_of_the_trade = 1/1
    venomous_wounds = 1/1
    vigor = 2/2

pvptalents: hemotoxin
   system_shock
   veil_of_midnight

covenant: none

conduits: none

soulbinds: [plague_deviser_marileth]

sets: mirror_of_fractured_tomorrows = 1
    ominous_chromatic_essence = 1
    tier30 = 1

gear: blightweavers_clutches = 1
    dragonkiln_chestguard = 1
    eternal_sentrys_ring = 1
    galakronds_voracious_hide = 1
    gilnean_adventurers_shirt = 1
    lurking_specters_edgeband = 1
    lurking_specters_shoulderblades = 1
    master_trainers_tabard = 1
    mirror_of_fractured_tomorrows = 1
    neltharic_shiv = 1
    obsidian_combatants_jeweled_amulet = 1
    obsidian_combatants_resilient_wristwraps = 1
    ominous_chromatic_essence = 1
    potionstained_cloak = 1
    tier30 = 1
    treads_of_the_swift = 1
    unearthed_trogglodicer = 1
    unstable_arcane_loop = 1
    vision_of_foreshadowed_ends = 1

legendaries: none

itemIDs: 156666, 193633, 193661, 193712, 193776, 193800, 193804, 193814, 193817, 202494, 202495, 203729, 204095, 204103, 204953, 207581, 207820, 49567

settings: aoe = 3
    combatRefresh = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 20
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Assassination
    petbased = false
    potion = phantom_fire
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    envenom_pool_pct = 50
    mfd_points = 3
    priority_rotation = false
    solo_vanish = true

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    ambush                = 1   [01], 1   [07]
    amplifying_poison     = -   [01]
    blind                 = C   [06]
    cheap_shot            = 2   [07]
    cloak_of_shadows      = 5   [01], 5   [07]
    crimson_tempest       = N4  [05]
    crimson_vial          = 4   [01], 4   [07]
    deadly_poison         = 0   [01]
    distract              = 6   [07]
    echoing_reprimand     = 6   [01], SR  [06]
    envenom               = Q   [06]
    evasion               = 9   [07]
    fan_of_knives         = RIGHT[05]
    feint                 = ARIGHT[05]
    garrote               = Dn  [05]
    kick                  = F   [06]
    kidney_shot           = 2   [01]
    kingsbane             = N2  [05]
    mutilate              = E   [06]
    numbing_poison        = =   [01]
    poisoned_knife        = Up  [05]
    rupture               = 3   [01], 3   [07]
    sap                   = ALEFT[05]
    shadow_dance          = M4  [05]
    shadowstep            = N8  [05]
    shiv                  = Z   [06]
    shroud_of_concealment = 7   [07]
    slice_and_dice        = R   [06]
    sprint                = LEFT[05]
    stealth               = M3  [06]
    thistle_tea           = N6  [05]
    tricks_of_the_trade   = =   [07]
    vanish                = V   [06]

warnings: [#1] Talent 'scent_of_blood' model expects 3 ranks but actual max ranks was 2.
[#2] Talent 'seal_fate' model expects 2 ranks but actual max ranks was 1.
[#3] Talent 'dashing_scoundrel' model expects 2 ranks but actual max ranks was 1.
[#4] Talent 'zoldyck_recipe' model expects 3 ranks but actual max ranks was 2.
[#5] Talent 'improved_poisons' model expects 2 ranks but actual max ranks was 1.
[#6] Talent 'deadly_precision' model expects 2 ranks but actual max ranks was 1.
[#7] Talent 'vigor' model expects 1 ranks but actual max ranks was 2.
[#8] Talent 'bloody_mess' model expects 2 ranks but actual max ranks was 1.

### Snapshot (Link)

https://pastebin.com/2db35tBu

**Comment by Hekili** [comment]
You're not using the latest version of the addon.
