### ISSUE TITLE
Assasination. Crimson tempest is not being recommended in AOE situations

### ISSUE THREAD

**Issue by Ktuky** [Hekili/hekili#2876]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Crimson tempest is not being recommended in AOE situations. I went to the riadbots and did a sim on 5 targets and it uses crimson tempest there.

### How to Reproduce

1. Follow addon recommendations
2. Notice that crimson tempest in not being recommended

### Snapshot (Link)

https://pastebin.com/MXqr0za2

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pakCCUV3yMPSkBB5GbGVhf

**Comment by Hekili** [comment]
Please take your snapshot when you actually have combo points for Crimson Tempest.

**Comment by Ktuky** [comment]
> Please take your snapshot when you actually have combo points for Crimson Tempest.

I'm very sorry, i thought when i press snapshot it snapshots the whole rotation before it.
This should be okay now? https://pastebin.com/bzndRKH5
Edit:
Also not sure if I should open a new issue but when I'm doing ST it autosnapshots and doesn't recommend anything
https://pastebin.com/qU3q7ZQ5

**Comment by Delerp** [comment]
For what its worth, also noticed this and it seems the apl has energy.regen_combined>25 as requirement to recommend crimson tempest causing this issue i believe. I'm not an expert on assa so i don't know which abilities or buffs one needs to achieve energy regen that high.

**Comment by Hekili** [comment]
If you want to sim your character with the `energy.regen_combined>25` and with it removed, that'd help me determine if I can remove it from the priority.

**Comment by Hekili** [comment]
I'd also suggest trying:

`spell_targets >= 2 & refreshable & effective_combo_points >= 4 & ( ! ticking | energy.regen_combined > 25 ) & ! cooldown.deathmark.ready & target.time_to_die - remains > 6`

This makes it so Crimson Tempest will get recommended to apply the dot if it is down, regardless of the Energy regen.

Another idea:

`spell_targets >= 2 & refreshable & effective_combo_points >= 4 & ( ! active_enemies > 2 | energy.regen_combined > 25 ) & ! cooldown.deathmark.ready & target.time_to_die - remains > 6`

This would only restrict Crimson Tempest based on Energy regen with 2 targets.

**Comment by Ktuky** [comment]
> I'd also suggest trying:
> 
> `spell_targets >= 2 & refreshable & effective_combo_points >= 4 & ( ! ticking | energy.regen_combined > 25 ) & ! cooldown.deathmark.ready & target.time_to_die - remains > 6`
> 
> This makes it so Crimson Tempest will get recommended to apply the dot if it is down, regardless of the Energy regen.
> 
> Another idea:
> 
> `spell_targets >= 2 & refreshable & effective_combo_points >= 4 & ( ! active_enemies > 2 | energy.regen_combined > 25 ) & ! cooldown.deathmark.ready & target.time_to_die - remains > 6`
> 
> This would only restrict Crimson Tempest based on Energy regen with 2 targets.

I'm not sure how would i do that.

**Comment by Hekili** [comment]
I'm posting my changes soon.
