### ISSUE TITLE
[BUG] Prot Warrior not recommending Thunder Clap in 10.2.0-1.0.0b

### ISSUE THREAD

**Issue by Arrhae** [Hekili/hekili#2877]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I have "Blood and Thunder", "Rend" and "Thunderclap" talented, but Hekili no longer seems to be recommending the usage of Thunderclap in either AoE or Single Target situations.

### How to Reproduce

1. Enter the game as a Protection Warrior
2. Select the Thunder Clap, Rend, and Blood and Thunder talents (these are selected by default in the Starter Build preset)
3. Engage in combat with any number of targets, following the Hekili recommendations
4. Thunderclap should be recommended fairly early on but never is

### Snapshot (Link)

https://pastebin.com/T33WrEQ6

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/7vWUfrQvsXLbdEvNuj4LEu

**Comment by Hekili** [comment]
I don't see Thunder Clap talented.  Is that correct?

**Comment by Arrhae** [comment]
I have Thunder Clap talented.

**Comment by syrifgit** [comment]
When you paste the talent string from the snapshot into a wowhead talent calculator, it does show thunderclap. Is the add-on not reading the talents correctly?

**Comment by Arrhae** [comment]
I double checked that I had all 3 talents that I mentioned talented before opening the ticket, and I also confirmed that I can hit Thunder Clap and it's properly going off and applying Rend to nearby targets.

**Comment by Arrhae** [comment]
I'm guessing that when Blizzard removed Inspiring Presence in 10.2 that must have shuffled some of the Warrior talent IDs around.

**Comment by Hekili** [comment]
I'm rescraping the talent data now, but the part that matters looks okay.  The spell ID for the Thunder Clap talent is correct.

**Nope, there are definitely some DBC changes since I last scraped.  Fun.  Will post an update soon.**

**Comment by Arrhae** [comment]
I'm seeing recommendations for Thunder Clap in 10.2.0-1.0.0c
