### ISSUE TITLE
[BUG] Hekili spamming numbers in chat - "count 1", "count 2"

### ISSUE THREAD

**Issue by Gerchan** [Hekili/hekili#2878]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon is spaming "count 1", "count 2" in chat when using abilities like Rip (feral)

Happens also when only Hekili is enabled.

### How to Reproduce

Use Rip as Feral Druid.

### Player Information (Link)

https://pastebin.com/aug8K2a1

### Error Messages (Link)

no error

### Additional Information

screenshot: 

https://imgur.com/a/PY9jJWY

**Comment by JeromeDuban** [comment]
fixed here I guess: https://github.com/Hekili/hekili/commit/26531b59181871cc5ed31ef1f535af26c289d02c

**Comment by Gerchan** [comment]
Updated to recent update and it seems to be fixed, thanks! :)

**Comment by Gerchan** [comment]
Updated to recent update and it seems to be fixed, thanks! :)
