### ISSUE TITLE
Adrenaline rush Overlap

### ISSUE THREAD

**Issue by Venezuelan** [Hekili/hekili#2879]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Adrenaline rush being recommended when I still have 8 seconds left on the my last AR.

### How to Reproduce

Opener on a target dummy then use vanish and shadowdance to extend the duration of AR, to the point where you AR again before the first one runs out.

### Snapshot (Link)

https://pastebin.com/pf1VFVsB

**Comment by chevyn11** [comment]
I think this is fine because of improved adrenaline rush talent?

Looking at your snapshot it's using it to generate combo points during crackshot so you can bte more, so i think this is intended.

**Comment by Venezuelan** [comment]
It might be intended , not sure about it tho so I'm putting it out there. Wasting almost 50% of the last AR seems a bit off.

**Comment by chevyn11** [comment]
It happens in sims so its intended, see ~35s into this sim: https://www.raidbots.com/simbot/report/rvBmx5Zs4fXjQBCU5JpzMN 
Whether its a gain to sacrifice some AR uptime for on demand combo points during crackshot or not is something to argue with the rogue theory crafters, but you'll have to bring evidence :smile: 
Its possible that its only a minor gain and you can play either way - in which case hekili can implement an "overlap adrenaline rush" setting or something so people can choose between playstyles.

**Comment by Hekili** [comment]
This is working as intended.
