### ISSUE TITLE
Outlaw keep recommending blade flurry

### ISSUE THREAD

**Issue by OfficialExiled** [Hekili/hekili#2880]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

So because of one talent called Underhanded Upper Hand. When we have Adrenaline Rush up then Blade Flurry will not lose duration. However, the addon keeps recommending me to use blade flurry even it hasnt lost any duration which is waste of gcd. However, this wasnt a problem but rather with Slice and Dice before however, after new update it keeps reminding us to use blade flurry when we dont have to. 

### How to Reproduce

I think when the addon knows we have blade flurry buff up then it should not recommend us to refresh blade flurry. 

### Snapshot (Link)

https://pastebin.com/mjFfeZAk

**Comment by Sedveth** [comment]
Do you have Deft Maneuvers talent? If you did, Blade Flurry will be used as a generator with 5+ targets

**Comment by Hekili** [comment]
```
    deft_maneuvers = 1/1
```
