### ISSUE TITLE
Outlaw Between the Eyes outside of stealth windows

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#2881]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Outlaw rotation, according to finishers rule in Ravenholdt: "BtE on cooldown, but only use BtE out of stealth if Vanish cooldown is over 45s and Dance cooldown is over 12s", Hekili didn't do it correctly and suggested BtE when Vanish or Shadow Dance will be very on soon

### How to Reproduce

1. Enter the game as Outlaw.
2. Doing the rotation as Hekili suggested until BtE is ready, Vanish and Shadow Dance will be up soon.
3. Instead of holding BtE to be use when Vanish/Shadow Dance ready, it suggested to use it.

### Snapshot (Link)

https://pastebin.com/CU6DRJAL

**Comment by chevyn11** [comment]
(what I think is happening) 
You have vanish and shadowdance on the cooldown toggle.
You have cooldowns toggled false.

The way hekili handles cooldown toggles is to set the cooldown of vanish and shadowdance to their max value, so it thinks vanish and shadowdance are 120s and 60s away all the time.
```
         - this entry's criteria PASSES: talent.crackshot.enabled[true] & ( cooldown.vanish.remains[120.00] > 45 & cooldown.shadow_dance.remains[60.00] > 12 )
```

@Hekili might have to use `true_remains` or handle the cooldown toggle differently?

In the meantime, try just playing with cooldowns toggled on all the time :smile:

**Comment by Sedveth** [comment]
Thank you for your explain, I'm appreciated that

**Comment by OfficialExiled** [comment]
> (what I think is happening) You have vanish and shadowdance on the cooldown toggle. You have cooldowns toggled false.
> 
> The way hekili handles cooldown toggles is to set the cooldown of vanish and shadowdance to their max value, so it thinks vanish and shadowdance are 120s and 60s away all the time.
> 
> ```
>          - this entry's criteria PASSES: talent.crackshot.enabled[true] & ( cooldown.vanish.remains[120.00] > 45 & cooldown.shadow_dance.remains[60.00] > 12 )
> ```
> 
> @Hekili might have to use `true_remains` or handle the cooldown toggle differently?
> 
> In the meantime, try just playing with cooldowns toggled on all the time 😄

Even if its cooldown toggled or not it was still the same. This was just an example, but I noticed a lot in a dungeon where even if was toggled on or not.

**Comment by chevyn11** [comment]
> Even if its cooldown toggled or not it was still the same. This was just an example, but I noticed a lot in a dungeon where even if was toggled on or not.

you'll need to provide a snapshot for when that happens, I think a similar thing can happen if you have "Show cooldowns separately" then your main window will act as if cooldowns are toggled off.
