### ISSUE TITLE
[FEATURE] Spellflash should work with my mouseover macros.

### ISSUE THREAD

**Issue by Westside24ch** [Hekili/hekili#2882]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

It would be nice for Spellflash to work with mouseover macros to replace generic spell frames. I play Balance Druid and use mouseovers for my DoT's among other things. I don't prefer using icon rotation so I hide display and use Spellflash instead, but if you replace the generic spell from the spellbook with the exact same spell as a macro, Spellflash no longer highlights it when it's time to cast.

**Comment by Hekili** [comment]
I don't think SpellFlash normally has a problem with mouseover macros, it's just an issue with Blizzard API changes breaking stuff right now.
