### ISSUE TITLE
[REC] Arms Warrior missing Thunder Clap recommendations in 10.2.0-1.0.0d

### ISSUE THREAD

**Issue by Arrhae** [Hekili/hekili#2883]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In multi-target situations, Arms should use Thunder Clap to apply Rend but it's not being recommended.

### How to Reproduce

1. Enter the game as an Arms Warrior
2. Talent into Rend, Thunder Clap, and Blood and Thunder. The Starter Build for Arms does this.
3. Engage in combat with ~3 targets and follow Hekili recommendations.
4. Observe as Hekili does not suggest Thunder Clap to apply Rend.

### Snapshot (Link)

https://pastebin.com/j6P9q65u

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/sqi888n3hBtjRRSQtJSE78

### Additional Information

Based on this line in the snapshot:
30.  thunder_clap ( hac - 2 ) - talent [ thunder_clap ] missing

I suspect this is the same thing that was going on with Protection Warrior in #2877

**Comment by Wyste** [comment]
Your talent setup has TC, but snapshot shows it's not talented... so I'm guessing the ability ID changed and this should be a super easy fix.

**Comment by Wyste** [comment]
Right before where TC Should be : I could open a PR for this, but it's probably faster for Hekili to commit it directly.
https://github.com/Hekili/hekili/blob/b0b161531c5e8f246efa6e26fc747ea24fcc7589/Dragonflight/WarriorArms.lua#L152-L153

TC Talent needs added in talent definition. From Skeleton tool:

`thunder_clap                    = { 92224, 396719, 1 }, -- Blasts all enemies within 8 yards for 11,794 Physical damage. and reduces their movement speed by 20% for 10 sec. Deals reduced damage beyond 5 targets.`

**Comment by Hekili** [comment]
I already beat you to it.  :D

It looks like Warrior talents have some kind of alternate approach for Thunder Clap specifically that my parser doesn't catch.  But I rescraped talents from in-game and this will be fixed in next release.
