### ISSUE TITLE
[REC] Guardian Maul/Raze not recommended

### ISSUE THREAD

**Issue by ryanjoliveira** [Hekili/hekili#2885]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After 10.2 update, I am almost never seeing Maul or Raze recommended, even when rage capped.  I think the only times I have seen Maul recommended, it was because of a Tooth and Claw proc.  But under conditions where you have full rage, I believe it should recommend maul or raze over swipe (which it did just fine before 10.2 update)

Snapshot is specifically taken at a time when Swipe is recommended in both ST and AoE.  Usually swipe is only a last resort button to press, but in this case I have 100 rage so no reason to not press Maul or Raze.  ST snapshot is copied in the main snapshot field below, but I include another AoE snapshot under the additional information

### How to Reproduce

1. Enter game is guardian druid.
2. Execute rotation on target dummy and stay rage capped until swipe is recommended, rage is full, and take snapshot.

### Snapshot (Link)

https://pastebin.com/VJqn2y3u

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/gywvt6AjEWzgDdZL7fAVqM

### Additional Information

"Use Maul and Raze in Ironfur Build" is checked under core guardian settings
Maul or Raze Rage Threshold is set to 20 in core guardian settings
Tried playing around with some different settings, but never seems to make any difference
Here is another snapshot for the AoE portion recommending swipe over raze:  https://pastebin.com/MzzKVdqV

**Comment by Hekili** [comment]
This will be improved upon in today's release.
