### ISSUE TITLE
Ele Shaman seems to be applying Enhance logic to Elemental blast / Lava Burst

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#2887]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Opening on behalf of another user

Lava Burst and Elemental Blast are both part of the single target rotation, as per [the class guide.](https://www.icy-veins.com/wow/elemental-shaman-pve-dps-rotation-cooldowns-abilities) 

In this user's snapshot (discord: alex99 --- @alex in the server) it is disallowing lava burst because of ele blast. That sounds like enhance logic (ele blast replaces lava burst for enhance, but not for elemental -- ele replaces Earth Shock instead).

Sample lines (full pastebin attached)

lava_burst ( single_target - 26 ) - talent [ elemental_blast ] disallowed
   Time spent on this action:  0.02msTimeData:Elemental-single_target-26:lava_burst:0.02:Ability Known, Enabled(0.02)
lava_burst ( single_target - 27 ) - talent [ elemental_blast ] disallowed
Time spent on this action:  0.02ms
TimeData:Elemental-single_target-27:lava_burst:0.02:Ability Known, Enabled(0.02)

lava_burst ( single_target - 28 ) - talent [ elemental_blast ] disallowed
Time spent on this action:  0.02ms
TimeData:Elemental-single_target-28:lava_burst:0.02:Ability Known, Enabled(0.02)

lava_burst ( single_target - 29 ) - talent [ elemental_blast ] disallowed
Time spent on this action:  0.02ms

### How to Reproduce

Do single target rotation as elemental on any build containing elemental blast talent, such as: BYQAzii1bx6MdXWQl8y/78bs6CAAAAAgUSpUSCgDk0SShSgkkEBAAAAAoEgUSCpJKItkkmSAJkEgA

### Snapshot (Link)

https://pastebin.com/56Y3gCH1

### Contact Information

alex99

**Comment by Hekili** [comment]
Thanks, will be resolved next update.
