### ISSUE TITLE
[REC] Outlaw Rogue, Vanish/Shadowdance recommended while bte is on cooldown

### ISSUE THREAD

**Issue by chevyn11** [Hekili/hekili#2888]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The new outlaw talent Crackshot makes Between the Eyes (BTE) have no cooldown if used from stealth. This means that you ideally want between the eyes to be ready before using a stealth(+subterfuge) ability like vanish or shadowdance.

In the sims, because it plays perfectly it deals with this by not using BTE if vanish/shadowdance are coming up soon. However for an imperfect player it is possible to hit BTE at the wrong time and not have it ready for an upcoming crackshot window. In these cases it is recommended not to use vanish or shadowdance until BTE is ready.

From the rogue discord:
![image](https://github.com/Hekili/hekili/assets/111624332/b020d7c9-63de-407a-8bcb-c13cb48b42ab)

Specifies "with BTE ready" in the cooldown priority list:
![image](https://github.com/Hekili/hekili/assets/111624332/4f27eba0-4eaf-4c36-968e-97bd5c5c5adf)

### How to Reproduce

1. Enter the game as an Outlaw Rogue
2. Build combo points
3. Use BTE
4. Follow hekili recommendations until it suggests vanish or shadowdance

### Snapshot (Link)

https://pastebin.com/GsNYhGLE

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/osHuP95BQa4T7qYydCQqGX

### Additional Information

I have included a raidbots report where I ammended the following condition to prove it will have no effect on sim dps because it already does this but in a roundabout way (not using bte if vanish/dance are coming up).

before:
```
actions.cds+=/call_action_list,name=stealth_cds,if=!stealthed.all
```
after:
```
actions.cds+=/call_action_list,name=stealth_cds,if=!stealthed.all&cooldown.between_the_eyes.ready
```

### Contact Information

chevyn

**Comment by chevyn11** [comment]
oh just had a thought, maybe the fix should check for the crackshot talent too...

**Comment by Hekili** [comment]
Looks pretty solid.  Have you submitted your changes to SimulationCraft as well?

**Comment by Hekili** [comment]
I've adjusted this to look to see if you even have Crackshot before waiting for BtE, but otherwise, implemented the same safety mechanism.

**Comment by chevyn11** [comment]
@Hekili haven't checked it in game yet, but reviewing the change i think you added it to the `stealth` list instead of the `stealth_cds` so I'm not sure this will have the same effect. stealth_cds is called from the cds list.

I haven't submitted this to simc as it was a neutral change and only really affects add-ons like this one downstream..

**Comment by chevyn11** [comment]
Can confirm this still happens with 1.0.0f

https://pastebin.com/2MXYe2ss
