### ISSUE TITLE
[FEATURE] To add an option for Ironfur stacks

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#2889]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Can we have an option to control Ironfur stacks?

**Comment by Hekili** [comment]
Just confirming that I plan to handle auras that have "applications" that don't function as normal stacks.  Will update soon.

**Comment by SUU09** [comment]
Thanks
