### ISSUE TITLE
Unholy DK, reccomendations stop

### ISSUE THREAD

**Issue by djcosmic22** [Hekili/hekili#289]
Happens in single target, and multiple mobs.
after using all the suggestions shown, no more suggestions left given

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
When DPSing as an Unholy Death Knight, sometimes the add-on stops giving recomendations when you follow the recomendations goven

**To Reproduce**
Play as Unholy DK and DPS using ability recomendations given by addon

**Expected behavior**
Expected more recomendations for abilities

**Screenshots**
Currently at work, but when I am online later and I see it happen I can add a screen

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v8.3.0-04-14
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: asphyxiate
    bursting_sores
    epidemic
    infected_claws
    soul_reaper
    unholy_frenzy
    wraith_walk

azerite: azerite_empowered = 3
    cold_hearted = 1
    endless_hunger = 1
    festermight = 2
    heed_my_call = 1
    magus_of_the_dead = 3
    march_of_the_damned = 1
    unstable_flames = 2
    vampiric_speed = 1

essences: [vision_of_perfection] = 3, breath_of_the_dying = 2, essence_of_the_focusing_iris = 2, memory_of_lucid_dreams = 2

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    automatic_waist_tightener = 1
    bracers_of_phantom_pains = 1
    deathguards_breastplate = 1
    dismembered_submersible_claw = 1
    grips_of_the_everlasting_guardian = 1
    heart_of_azeroth = 1
    heavy_alloy_legplates = 1
    ichorspine_loop = 1
    malignant_leviathans_stompers = 1
    pauldrons_of_infinite_darkness = 1
    seal_of_questionable_loyalties = 1
    second_sight_helm = 1
    torment_in_a_jar = 1
    vitacharged_titanshard = 1

corruptions: gushing_wound = 1
    racing_pulse = 2
    twisted_appendage = 2

itemIDs: 158075, 158314, 159445, 159650, 166574, 168966, 168976, 169223, 173455, 173943, 174163, 174166, 174177, 174500, 174532

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = single
    potions = false

http://github.com/Hekili/hekili/issues/289

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/Hjm7qS4p
https://pastebin.com/zGz1mzZS
https://pastebin.com/201xRzcM

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Note:  I've played a fair amount of Unholy recently, and haven't seen this in my build.  I'll keep testing.

**Comment by wow1989** [comment]
Also had this problem

**Comment by Hekili** [comment]
That's nice, but unless you've had this problem today with the latest release, it doesn't help.  If you are presently experience this issue, submit a new, complete ticket based on current circumstances.
