### ISSUE TITLE
Havoc DH-Not recommending correct info unless talented into cycle of hatred for ST

### ISSUE THREAD

**Issue by Yelafox1** [Hekili/hekili#2890]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In summary, without the talent cycle of hatred. Hekili will not recommend you to use eye beam, blade dance, essence break, or meta at all in single target. It will just have you throw Glavie, Chaos Strike, and Sigil of flame/fel rush on repeat. This is odd because the sim will show all of those being used. I noticed these while doing M+ as the ignition build does not reuse the cycle of hatred. Spent an hour swapping out one talent point at a time until I found the one bugging the rotation recommendation.

### How to Reproduce

1. Log in as Havoc
2. Make sure you have cycle of hatred talent to see proper recommendations on ST dummy
3. Remove talent to see eye beam, blade dance, essence break, and meta be removed from recommended on ST dummy

### Snapshot (Link)

https://pastebin.com/CyKNaDwc

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/5GurXGf9YvW7KBmPpfxc2G

### Additional Information

It works in AOE.

### Contact Information

yelafox#7259

**Comment by Hekili** [comment]
This should be resolved in 10.2.0-1.0.0g.  Thanks!
