### ISSUE TITLE
[REC] Disc Priest does not recommend Penance enough, and almost never recommends Shadow Word: Death

### ISSUE THREAD

**Issue by Sragoodwin** [Hekili/hekili#2891]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon sometimes does not suggest casting Penance within the Shadow Covenant window, and never suggest casting it outside of this window. I assumed during Shadow covenant you'd want to cast Penance, Mind Blast, Halo (esp in AOE), and Shadow Word: Death on cooldown due to them either being increased by 20% and/or causing additional AOE damage. 

Few other points:
- It suggests casting Penance before Mind blast. Shouldn't this be reversed so you get an extra 10% dmg increase on your Penance?
- Shadow Word: Death doesn't seem to be in the rotation at all even though it would extend mindbender and cause it to do AOE
- Halo also isn't in the rotation even for AOE situations.
- It's almost as if smite spam to reduce the cooldown of mindbender has a higher priority over the things I mention above.

### How to Reproduce

1. Enter the game as a Disc Priest
2. Talent in [Shadow Covenant] down to [Mindbender] (shown below)
3.  Cast PI, Purge the Wicked, and Mind bender to get into Shadow Covenant - I believe the rotation is off after this.

![Disc Talents](https://github.com/Hekili/hekili/assets/150489923/ea49ee7b-7e68-4907-9849-a2804ad490a6)

### Snapshot (Link)

https://pastebin.com/vHKANCvR   or   https://pastebin.com/2xE8zQcm

### Additional Information

I know healers aren't supported by raidbots, but this addon was almost spot on before 10.2. I understand if there is nothing that can be done. Thanks for hearing me out!

**Comment by Thatawow** [comment]
"shadow_word_death" not exist in .lua 

"talent.embrace_shadow" in .simc => talent deleted (line10)

Sorry my bad english

**Comment by Hekili** [comment]
> "shadow_word_death" not exist in .lua

It doesn't need to, it's borrowed from Shadow.

Should be resolved in 1.0.1.
