### ISSUE TITLE
[BUG] Unholy opener breaks after Apoc and Unholy Assault

### ISSUE THREAD

**Issue by Aelirin** [Hekili/hekili#2892]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Opener is fine from army to Dark Transformation / Gargoyle. After UA gets pressed however it doesn't track that it was used, same with Apocalypse. After that it has an empty square in the queue and just keeps recommending death coils.

![image](https://github.com/Hekili/hekili/assets/150493875/d77b81e4-bb88-4505-82bd-3738a2298f30)

https://pastebin.com/93750YzG

The pastebin is the snapshot created after pausing.

### How to Reproduce

1. The regular opener that the helper recommends up until UA/Apoc. It happens every single time I attempt a fight and I can replicate the break every time.

### Player Information (Link)

https://pastebin.com/g4iq7ATm

### Error Messages (Link)

No message is provided when it breaks

### Contact Information

Cairnus on Discord. Aelirin#1411 on bnet

**Comment by Hekili** [comment]
Please add a new snapshot if this still occurs in 10.2.0-1.0.0g.  Thanks!

**Comment by ctroller** [comment]
Still happens. 

https://pastebin.com/ZxSScCrJ
```
    Recommendation thread terminated due to error: Interface/AddOns/Hekili/Core.lua:1873: attempt to compare number with nil
```

"fixing" that line fixes the recommendation system, although i don't know if that's just a dirty fix or a good one:

```lua
                        if ability.cast and ability.cast > 0 then
```

edit: doesn't really fix it properly, adds more issues.
https://pastebin.com/hKdS3r4d

**Comment by Aelirin** [comment]
https://pastebin.com/u2dc7bMF

@Hekili

**Comment by Hekili** [comment]
This may be resolved in today's release (h).

**Comment by Hekili** [comment]
Let me know if this is still happening in 1.0.1.

**Comment by Dolch0812** [comment]
i have a issue when I use Arbiter, it doesnt count as cd and even in cd the addon keep it in priority

**Comment by Hekili** [comment]
> i have a issue when I use Arbiter, it doesnt count as cd and even in cd the addon keep it in priority

What is Arbiter in retail?

**Comment by Dolch0812** [comment]
Dark arbiter is Gargoyle skin.
This one: https://www.wowhead.com/spell=207349/dark-arbiter
