### ISSUE TITLE
[REC] Addon is recommending to use Immolation aura again in the opening rotation, until Fel Rush is used.

### ISSUE THREAD

**Issue by Squidlybeard** [Hekili/hekili#2893]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In havoc's opening rotation with [A Fire Inside] talented, it is optimal to continuously use Immolation Aura(IA) followed by Fel Rush(FR) if you get a proc, however, Hekili is recommending to use a second IA right after the first IA and FR are used, until the second FR is actually used. At that point the whole recommendation list changes to reflect the correct abilities.

### How to Reproduce

1. Have my talents: BEkAzqt9tQbK6xteCyjwasgfTKJRkkgkkISISCAAAAAAItQkERIJplWKRSIBKlIJRA
2. Start opener on single target training dummy, and use abilities as suggested.
3. Once Fel Rush is used, you will see the whole list of abilities change.

### Snapshot (Link)

https://pastebin.com/5MzFDcd2

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/r2zF1NVmPoyY9YwK17JgGJ

### Contact Information

squidly9235

**Comment by Hekili** [comment]
I think this was secondary to another issue with Havoc.  Please update/reopen the ticket if not resolved in 10.2.0-1.0.0g.  Thanks!
