### ISSUE TITLE
[BUG] Lua error when attempting to add a CD

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#2894]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Whenever I go to :

/hekili > Outlaw > Toggles > Cooldowns and then click the green + button to add a cooldown (I wanted to add Roll the Bones and make it have its own window), clicking the + button gives an 'attempt to index field' error.  This happens with all addons disabled except Hekili.

The error: https://pastebin.com/ZpDJy6fa

### How to Reproduce

1. Go to /hekili > [Spec] > Toggles > Cooldowns and then click the + button to add a cooldown (I wanted to add Roll the Bones and make it have its own window), clicking the + button gives the error.
2. Any class seems to do.  I tested it also on my priest and got the same error. 

### Player Information (Link)

https://pastebin.com/utJJy0J3

### Error Messages (Link)

https://pastebin.com/ZpDJy6fa

**Comment by gjritter** [comment]
I'm also seeing this on my priest.

**Comment by Hekili** [comment]
This panel has caused too much confusion and has been removed.  Abilities can be added to and removed from toggles via /hekili > Abilities > X > Require Toggle.  Thanks!
