### ISSUE TITLE
[BUG] Elemental Shaman LUA error

### ISSUE THREAD

**Issue by darkpsy3934** [Hekili/hekili#2895]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When using Elemental Shaman, error states attempt to index global 'talent' (a nil value)

### How to Reproduce

1. Enter game as Elemental Shaman
2. Error appears after a moment or two

### Player Information (Link)

https://pastebin.com/fqRqgURn

### Error Messages (Link)

https://pastebin.com/UF3bLPi3

**Comment by Mike160770** [comment]
me2

**Comment by Hekili** [comment]
Fixed in next release.
