### ISSUE TITLE
Destruction ST and AoE Rotation 

### ISSUE THREAD

**Issue by Catabolik** [Hekili/hekili#2897]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In single target, Shadowburn is not being recommended during the execute phase.

In AoE, Immolate spam is being recommended even when all targets are already affected by Immolate. Chaos Bolt is also being recommended over Rain of Fire, even when Funnel Damage in AoE is not selected.

### How to Reproduce

AoE
1. Enter game as a Destruction Warlock.
2. Take the Rain of Fire talents.
3. Use Immolate on 3+ targets.
4. Build to 3+ Soul Shards.
5. See recommendations.

Single Target
1. Enter game as a Destruction Warlock.
2. Take the Shadowburn talents.
3. Attack enemy until >20% HP.
4. See recommendations.

### Snapshot (Link)

https://pastebin.com/yZEbWiGn (Immolate spam)
https://pastebin.com/6FT2afam (Chaos Bolt > Rain of Fire recommendation)
https://pastebin.com/yCEyrLeF (No Shadowburn during execute phase)

**Comment by Hekili** [comment]
/
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Catabolik** [comment]
Edited pastebin.com link. I believe it should be correct now. Provided additional pastes for Chaos Bolt > Rain of Fire recommendation and absence of Shadowburn during execute phase.

**Comment by Hekili** [comment]
Thanks; I'll be adjusting for this today.

edit:  Your Chaos Bolt > Rain of Fire scenario is with Havoc active, so appears intentional.
