### ISSUE TITLE
There is no DnD recommendation in AOE from Frost DK

### ISSUE THREAD

**Issue by nechyu** [Hekili/hekili#2898]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During a fight with 2+ targets there is no DnD recommendation no matter if it's 5 targets or more, DnD will not show up in the addon recommendations. If you take the Sim rotation there is a DnD recommendation there in the form of "any_dnd,if=!death_and_decay.ticking&variable.adds_remain&(buff.pillar_of_frost.up&buff.pillar_of_frost.remains>5&buff. pillar_of_frost.remains<11|!buff.pillar_of_frost.up&cooldown.pillar_of_frost.remains>10|fight_remains<11)&(active_enemies>5|talent.cleaving_strikes&active_enemies>=2)" but this condition is shown in Hekili in red. That's why it doesn't work for some reason.
![image](https://github.com/Hekili/hekili/assets/143894282/d0b73fe3-4b9d-4e4c-ab96-d898b316dc9f)

### How to Reproduce

Get into combat with any 2+ targets, and just follow the rotation that Hekili suggests, DnD will not show up no matter how many targets are around.

### Snapshot (Link)

https://pastebin.com/3RaEcc0J

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/668xBYUzzLcMQhqasKxUAX

**Comment by ctroller** [comment]
You have Death and Decay disabled in your Abilities according to the snapshot.

**Comment by nechyu** [comment]
> You have Death and Decay disabled in your Abilities according to the snapshot.

Thank you very much yes indeed I found the disabled ability although I didn't switch it off. Thank you.
