### ISSUE TITLE
Balance druid: Keep getting recommended to go into lunar eclipse in single target even though solar eclipse is so much better in single

### ISSUE THREAD

**Issue by Drazatraza** [Hekili/hekili#2899]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my balance druid, I expect to go into a solar eclipse for single target but I am always recommended to go into lunar no matter what.

### How to Reproduce

1. Enter game as balance druid
2. Look at recommendations for single target (starts two wraths always)
3. Finish an eclipse cycle and see recommendations

### Snapshot (Link)

https://pastebin.com/KXSE0EtW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/szuF1wuRysFPYUzTUhvEfw

### Contact Information

Discord: Drazatraza

**Comment by syrifgit** [comment]
I tried twice for 3 minutes each, and was unable to reproduce the issue using these talents.

**Comment by Hekili** [comment]
My best guess is that this has to do with the opener defaulting to using two Wraths in the sim profile.  I will need to revise so that if you drop combat and resume combat, it picks up more consistent with where you left off.
