### ISSUE TITLE
AOE Rogue: Outlaw 

### ISSUE THREAD

**Issue by Nuklearny** [Hekili/hekili#29]
AOE mode is not working after last update, i checked all modes and this is 100% sure its broken

**Comment by Hekili** [comment]
What is broken about it?

What version is last update to you?  Seems fine to me.

**Comment by Hekili** [comment]
Ah, I see that Curse hasn't uploaded version 8.0.1-22 yet.  You can download it here from GitHub instead, otherwise it should be in Twitch client in a few hours.
