### ISSUE TITLE
[BUG] Spell Interrupts Off GCD Still Showing GCD (Indicating I Can't Press It Yet When I Can)

### ISSUE THREAD

**Issue by StreetLight777** [Hekili/hekili#2902]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On any class with an interrupt off the GCD, Hekili shows the ability with a GCD 'sweep' - indicating that I can't use the ability, when in fact I can. I was leveling up a new Rogue alt and saw the icon for Kick with the 'sweep' GCD animation and I can press it immediately. Confirmed this is the same behavior for all classes with abilities/interrupts off the GCD.

### How to Reproduce

1. Enter the game as a rogue
2. Fight an enemy with an interruptible cast, make sure to spam abilities to invoke the GCD...
3. Observe how it shows Kick with GCD 'sweep' animation even though this ability is off the global cooldown.

### Player Information (Link)

build: v10.2.0-1.0.0h level: 16 (16) class: ROGUE spec: assassination  talents: BMQAcWb37Z8KXj8LlE1rTPXfsBACAAAAAAAAkAAAAAAAaIAAAAABBAAA     cheat_death = 1/1     cloak_of_shadows = 1/1     deadly_poison = 1/1     improved_sprint = 1/1     path_of_blood = 1/1     shadowstep = 1/1     shiv = 1/1     venomous_wounds = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: none  gear: balanced_heartseeker = 1     band_of_chronicled_deeds = 1     belt_of_uncertain_devotion = 1     boots_of_inner_calm = 1     dark_silk_shirt = 1     eternal_will_of_the_martyr = 1     inherited_cape_of_the_black_baron = 1     sparring_trainers_grips = 1     stained_shadowcraft_cap = 1     stained_shadowcraft_pants = 1     stained_shadowcraft_spaulders = 1     stained_shadowcraft_tunic = 1     swift_hand_of_justice = 1     unstable_elemental_confluence = 1  legendaries: none  itemIDs: 122248, 122254, 122261, 122350, 122358, 122361, 122383, 122668, 173324, 173325, 173343, 173344, 199686, 4333  settings: aoe = 3     canFunnel = true     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     funnel = false     gcdSync = true     maxTime = 20     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Assassination     petbased = false     potion = phantom_fire     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     envenom_pool_pct = 50     mfd_points = 3     priority_rotation = false     solo_vanish = true  toggles: cooldowns = true [separate]     custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = automatic      potions = false   keybinds:      ambush            = 3   [07]     cheap_shot        = 2   [07]     cloak_of_shadows  = C3  [05]     crimson_vial      = N5  [06]     echoing_reprimand = N1  [06]     eviscerate        = 3   [01]     feint             = C5  [05]     garrote           = 4   [01], 5   [07]     kick              = 6   [01]     kidney_shot       = R   [01]     mutilate          = 2   [01]     sap               = 4   [07]     shadowmeld        = X   [07]     shadowstep        = 1   [01], 1   [07]     shiv              = C4  [05]     slice_and_dice    = F   [01], F   [07]     sprint            = N/  [06]  warnings: none

### Error Messages (Link)

No error message in game, it's weird you require this...

### Contact Information

keifer.street@gmail.com

**Comment by syrifgit** [comment]
That's not what it means in this context.

The addon is getting you to interrupt as late as possible, which is better. The sweep is telling you to wait until the end of the cast and do it at the last moment. This is expected behavior.

And just for additional understanding .. if it does this on your normal abilities it means the same thing. Don't cast till the sweep is done, even if you technically can click the button. Usually this is for the purposes of resource pooling.
