### ISSUE TITLE
Survival Hunter Coordinated Assault Kill Shot Macro issue

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2903]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The CA Kill Shot Macro Option works in AoE but not in ST.

### How to Reproduce

1: Valk Dummies
2: Test 5 Target Aoe with option check will trigger Kill Shot when the macro is used(pet is manually controlled via macro)
3: ST Dummy use will not trigger the Kill Shot recommendation

### Snapshot (Link)

https://pastebin.com/KeDdHSrq

### Additional Information

Here is the option working in AoE on 5 Targets.

https://pastebin.com/fTuyTeqd

**Comment by Bingo176** [comment]
Editing ST Entry 1. Kill Shot like the last APL fixed the issue. 

buff.coordinated_assault_empower.up|coordinated_assault_kill_shot

**Comment by Hekili** [comment]
Fixed for 1.0.1.
