### ISSUE TITLE
[REC] Disc Priest not recommending Penance during Shadow Covenant after update v10.2.0-1.0.0h

### ISSUE THREAD

**Issue by Sragoodwin** [Hekili/hekili#2905]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

1. The addon will not recommend Dark Reprimand during Shadow Covenant, unless you have stacks of Harsh Discipline. It also doesn't recommend using Shadow Word: Death during Shadow Covenant even though it would extend mindbender, and should be a dps increase in AOE situations. I can't confirm the latter.

### How to Reproduce

1. Enter the game as a discipline priest
2.  Cast Mindbender to gain Shadow Covenant buff
3.  The addon won't recommend penance until the buff expires. unless you cast Power Word: Radiance and gain Harsh Discipline stacks

### Snapshot (Link)

https://pastebin.com/gD0izCpm or https://pastebin.com/8ah5ZZCc

### Raidbots Sim Report (Link)

n/a

### Additional Information

Thank you for all the hard work on this!

**Comment by Hekili** [comment]
Until there's an official sim update, what would you prefer?  To force you to use Power Word Radiance, or to allow Penance without Harsh Discipline?

**Comment by Sragoodwin** [comment]
Thanks for your reply. I believe it would be better to allow Penance
without Harsh Discipline. I think suggesting healing spells to increase dps
isn’t a good idea for people new to the spec. You wouldn’t have radiance
charges when they’re actually needed. And there will be a wave of newbies
once they realize how strong Disc is.

Do we need to wait for the updated sim to have Shadow Word: Death suggested
during Shadow Covenant even if the target doesn’t meet the hp %?

Seems the most optimal rotation would be Mindbender, Mind Blast, Penance,
Shadow Word Death, and maybe even halo for AOE. But if you feel like this
would cause more issues, I say we can wait for the updated sim. Just fixing
the Penance problem would make things a lot better.

Thanks again!

Kellen

**Comment by Hekili** [comment]
That's the approach I'm taking.

**Comment by Hekili** [comment]
Also, I fixed SWD.

**Comment by Sragoodwin** [comment]
Thanks!!
