### ISSUE TITLE
[REC] Recommending Trinket and Roll the Bones during Subterfuge/ Shadow Dance on Outlaw HO build

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#2906]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Problem: 

Hekili is currently recommending Roll the Bones and usage of trinket (my trinket is Paracausal Fragment of Shalamayne) during Subterfuge and Shadow Dance windows.  

* * *

From [the outlaw FAQs on rogue server:](https://discord.com/channels/124169701881282560/1171456286991339560/1171456289122025603)

> Crackshot turns Vanish and Shadow Dance into dps cooldowns with the intent to use as many 5+ combo point BtE's as possible inside them  (BTE is between the eyes). 

From [the Wowhead outlaw guide](https://www.wowhead.com/guide/classes/rogue/outlaw/rotation-cooldowns-pve-dps):

> Shadow Dance &  Vanish: These two spells have very similar functionality in enabling the strongest talent in the Outlaw Rogue tree in Season 3 which is  Crackshot. You want to make sure to use  Vanish before [ Shadow Dance](https://www.wowhead.com/ptr-2/spell=185313/shadow-dance) as [ Restless Blades](https://www.wowhead.com/ptr-2/spell=79096/restless-blades) is extremely powerful. During these damage windows you want to make sure you are only casting [ Between the Eyes](https://www.wowhead.com/ptr-2/spell=315341/between-the-eyes) to finish, and [ Ambush](https://www.wowhead.com/ptr-2/spell=8676/ambush) to generate.

Basically, the new Crackshot talent makes it so that you want to spam as many builders and BTEs as you can within that short window of time that Subterfuge (from Vanish/ Stealth) and Shadow Dance offer.  Def should not be using anything else like roll the bones or trinkets during that short window.  

### How to Reproduce

1. Go to training dummies as Outlaw with Crackshot talent.  
2. DPS the dummies and enter Subterfuge/ Shadow Dance window without Roll the Bones being up, and/ or with on-use trinket being off CD.  
3. Hekili will then recommend using RTB/ trinket during the Subterfuge/ Shadow Dance window. 

### Snapshot (Link)

https://pastebin.com/ecYM6uL6

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9cpTytymeh4AvAY5sNAkP2

### Additional Information

The above link was for dungeon slice, with an aoe build.

Here is the link for a patchwerk sim, with an st build. https://www.raidbots.com/simbot/report/wrY43nLftYGAruP858pQz2

Both builds are using HO (hidden opportunity), although this shouldn't affect the usage of BTE for Crackshot one way or another.

**Comment by chevyn11** [comment]
At 2:20 in your st sim it uses rtb while in subterfuge. Seems intended unless the apl isn't updated? Once it is it should get fixed here too.

**Comment by Hekili** [comment]
RtB is probably intentional as it'd make for some awkward logic to either early refresh or wait and let RtB fall off. I'll tinker a bit, though. 

For trinkets, I'll dig a bit. Does that trinket have a cast time? Most trinkets are off GCD so they wouldn't matter.

**Comment by Hekili** [comment]
So far, it sims with tiny losses to prevent using a cast time trinket in Stealth and to avoid rerolling in Stealth.

**Comment by IIeTpoc** [comment]
About Roll the Bones.
Ideally refresh before crackshot but better to refresh during than let it time out if you have T31 4pc. You should never let RtB expire if you have T31 4pc

**Comment by Hekili** [comment]
This should be fixed in today's release.

**Comment by wheatbread** [comment]
> RtB is probably intentional as it'd make for some awkward logic to either early refresh or wait and let RtB fall off. I'll tinker a bit, though.

Hi, sorry, late reply!

Here is the rotation info for RTB from the rogue discord:

![image](https://github.com/Hekili/hekili/assets/548824/f6f06481-dcda-4477-a8f0-8ede70bd6b22)
 
With 4pc:
- Early refresh if buffs are under 7 secs, before hitting vanish or shadow dance
Without 4pc:
- Not mentioned
