### ISSUE TITLE
Update priority for Demonology lock with World Vein

### ISSUE THREAD

**Issue by mrgrimms** [Hekili/hekili#291]
Please describe your idea or feature and when it would be useful.
With World Vein major for Demo, the priority changes to pop racials, trinkets, essence THEN tyrant. 
https://www.youtube.com/watch?v=zdO-UlId8rg for reference 

Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v8.3.0-04-12
level: 120 (120)
class: WARLOCK
spec: demonology

talents: burning_rush
    demonic_calling
    demonic_circle
    demonic_consumption
    demonic_strength
    soul_conduit
    soul_strike

azerite: azerite_empowered = 3
    baleful_invocation = 3
    demonic_meteor = 1
    elemental_whirl = 1
    explosive_potential = 2
    impassive_visage = 1
    longstrider = 1
    overwhelming_power = 2
    vampiric_speed = 1

essences: [worldvein_resonance] = 4, memory_of_lucid_dreams = 3, vision_of_perfection = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    eldritch_seaweave_breeches = 1
    eldritch_seaweave_gloves = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    hyperthread_boots = 1
    logic_loop_of_division = 1
    peerless_leviathans_eye_loop = 1
    psyche_shredder = 1
    shglayos_astral_malignity = 1
    silken_safety_harness = 1
    spaulders_of_miasmic_mycelia = 1
    stormlurkers_cowl = 1
    uhnish_vwah = 1
    voiddrenched_wristwraps = 1
    volatile_arming_doublet = 1

corruptions: infinite_stars = 2
    racing_pulse = 3

itemIDs: 158075, 159244, 168964, 169067, 169072, 169157, 169223, 170458, 170461, 171075, 172190, 174044, 174060, 174108, 174117, 174122

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Demonology
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = false
    mode = automatic
    potions = false

New Recommendations for [ Primary ] requested at 21:39:01 ( 276912.43 ); using built-in ( Demonology ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: mana[ 100000 / 100000 ], soul_shards[ 3 / 5 ]
    
    Processing precombat action list [ Demonology - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   summon_felguard ( precombat - 1 )
        The action (summon_felguard) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.
        
        2.   power_siphon ( precombat - 2 ) - talent [ power_siphon ] missing
        
        3.   potion ( precombat - 3 ) - ability disabled.
        
        4.   demonbolt ( precombat - 4 )
        The action (demonbolt) is usable at (0.00 + 0.00) with cost of 2000.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria FAILS: boss[false] | action.demonbolt.cast[2.35] = 0
        There were no recheck events to check.
        
        5.   shadow_bolt ( precombat - 5 )
        The action (shadow_bolt) is usable at (0.00 + 0.00) with cost of 2000.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  shadow_bolt at 0.00!
    
    Completed precombat action list [ Demonology - precombat ].
    Recommendation is shadow_bolt at 0.00 + 0.00.
    Recommendation #1 is shadow_bolt at 0.00s (0.00s).
    Time spent generating recommendations:  0.546ms

**Comment by Hekili** [comment]
Let me know when sims are updated or after you've done testing, thanks.
