### ISSUE TITLE
[REC] Sin rogue opener is incorrect out of combat

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2912]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sin rogue opener appears differently before combat and once you enter combat.

### How to Reproduce

1. Enter game as sin rogue
2. Go to target dummy, enter stealth
3. Recommendations don't include rupture or deathmark
4.  Enter combat by Garroting
5. Recommendations appear as expected

### Snapshot (Link)

https://pastebin.com/fWX78h8m

**Comment by Hekili** [comment]
You'd need to provide two snapshots to make the comparison.

**Comment by fzarr** [comment]
https://pastebin.com/ZuR4YLGD - you can see deathmark being recommended further in the sequence once i enter combat by pressing garrotte.

**Comment by Hekili** [comment]
A lot can change based on Combo Point generation, some of which is unpredictable.  I've changed Assassin a fair amount so please update and reopen if you're seeing this with 1.0.1d.
