### ISSUE TITLE
Aug Evoker Ebon Might is not recommended after opener

### ISSUE THREAD

**Issue by n00del** [Hekili/hekili#2914]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon should recommend ebon might but its only working on opener or in  breath of eons time range.

### How to Reproduce

1. Enter game as Aug Evoker
2. Play M+ key
3. Play Rotation after opener

### Snapshot (Link)

https://pastebin.com/RvU9b0nB

### Contact Information

n00del

**Comment by n00del** [comment]
seems like this part of the ebon might condition prevents to recommend it
"( active_dot.prescience >= group_members & time <= 10 | active_dot.prescience >= 3 | buff.ebon_might.remains >= action.ebon_might.cast_time | group_members <= 2 )"

**Comment by Hekili** [comment]
Why?  The snapshot shows that you're casting Fire Breath so it's not going to recommend Ebon Might at that time.  Take a snapshot when you're not empowering FB.

**Comment by Hekili** [comment]
I'll go ahead, I guess it makes sense I shouldn't count Prescience stacks if the addon isn't pushing you to use them more often.
