### ISSUE TITLE
[BUG] Deep Breath appearing randomly and no Living Flame.

### ISSUE THREAD

**Issue by TheeCableguy** [Hekili/hekili#2915]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

While playing Aug the basic deep breath icon will appear in rotation even if Breath of Eons is on CD. It seems to be replacing random abilities and as a secondary effect is not recommending living flame.

### How to Reproduce

1. Play the game as an Aug evoker and have Breath of Eons as a talent.

### Player Information (Link)

build: v10.2.0-1.0.1a level: 70 (70) class: EVOKER spec: augmentation  talents: BEcBsJu/D+01p9npZvkV+nWIkTikWkkoFSSKJikk0AAAAAABAAJBAiEikkAAAAgEJtIJJSCESA     accretion = 1/1     aerial_mastery = 1/1     anachronism = 1/1     ancient_flame = 1/1     aspects_favor = 2/2     blast_furnace = 1/1     blistering_scales = 1/1     breath_of_eons = 1/1     chrono_ward = 1/1     defy_fate = 1/1     draconic_attunements = 1/1     draconic_legacy = 1/1     ebon_might = 1/1     eruption = 1/1     essence_attunement = 1/1     essence_burst = 1/1     expunge = 1/1     extended_flight = 2/2     fate_mirror = 1/1     fire_within = 1/1     font_of_magic = 1/1     hoarded_power = 1/1     ignition_rush = 1/1     infernos_blessing = 1/1     inherent_resistance = 2/2     innate_magic = 2/2     instinctive_arcana = 2/2     landslide = 1/1     leaping_flames = 1/1     molten_blood = 1/1     momentum_shift = 1/1     natural_convergence = 1/1     obsidian_bulwark = 1/1     obsidian_scales = 1/1     panacea = 1/1     permeating_chill = 1/1     plot_the_future = 1/1     potent_mana = 1/1     power_nexus = 1/1     prescience = 1/1     pupil_of_alexstrasza = 1/1     quell = 1/1     renewing_blaze = 1/1     rescue = 1/1     ricocheting_pyroclast = 1/1     scarlet_adaptation = 1/1     source_of_magic = 1/1     stretch_time = 1/1     tectonic_locus = 1/1     time_skip = 1/1     time_spiral = 1/1     tip_the_scales = 1/1     twin_guardian = 1/1     unravel = 1/1     upheaval = 1/1     verdant_embrace = 1/1     volcanism = 1/1     zephyr = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: screaming_black_dragonscale = 1     tier30 = 2     vessel_of_searing_shadow = 1  gear: adaptive_dracothyst_armguards = 1     allied_legguards_of_sansok_khan = 1     auburn_scavenger_gauntlets = 1     dreambound_staff = 1     exacting_augmenters_sabatons = 1     frigid_conservators_wrap = 1     hauberk_of_obsidian_secrets = 1     rime_ridden_ring = 1     screaming_black_dragonscale = 1     signet_of_titanic_insight = 1     spirited_stags_waistguard = 1     string_of_delicacies = 1     tier30 = 2     vessel_of_searing_shadow = 1     wingspan_of_obsidian_secrets = 1     winter_foragers_helm = 1  legendaries: none  itemIDs: 192999, 193464, 202486, 202491, 202588, 202612, 202615, 204704, 208355, 209360, 209905, 210358, 210378, 210382, 210700  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = false     maxTime = 20     nameplateRange = 35     nameplates = false     noFeignedCooldown = false     package = Augmentation     petbased = false     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     manage_attunement = false     manage_source_of_magic = false     skip_boe = true     upheaval_rank_1 = true     use_clipping = true     use_deep_breath = true     use_early_chain = true     use_unravel = true     use_verdant_embrace = true  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = automatic      potions = false   keybinds:      azure_strike        = X   [01]     blistering_scales   = E   [01]     breath_of_eons      = R   [06]     cauterizing_flame   =     deep_breath         =     disintegrate        =     dream_breath        =     ebon_might          = 4   [01]     echo                =     emerald_blossom     = T   [06]     eruption            = 3   [01]     eternity_surge      =     expunge             = SX  [03]     fire_breath         = 2   [01]     fury_of_the_aspects = SSPACE[06]     healthstone         = S1  [06]     hover               = M4  [01]     landslide           =     living_flame        = 1   [01]     naturalize          =     obsidian_scales     = Q   [01]     prescience          = V   [01]     pyre                =     quell               = F   [06]     renewing_blaze      = M5  [01]     rescue              = M3  [01]     reversion           =     shattering_star     =     spiritbloom         =     tail_swipe          = SC  [03]     time_skip           = Z   [06]     time_spiral         = F3  [06]     tip_the_scales      = F1  [06]     unravel             = `   [06]     upheaval            = 5   [01]     verdant_embrace     = C   [06]     wing_buffet         = SR  [03]     zephyr              = F4  [06]  warnings: [#1] Returned unknown string 'ABSORB' in state metatable [Augmentation:default:2]. [string "@Interface/AddOns/Hekili/State.lua"]:2326: in function <Interface/AddOns/Hekili/State.lua:1956> [string "@Interface/AddOns/Hekili/Classes.lua"]:2171: in function `generate' [string "@Interface/AddOns/Hekili/State.lua"]:4831: in function <Interface/AddOns/Hekili/State.lua:4810> [string "@Interface/AddOns/Hekili/State.lua"]:4878: in function <Interface/AddOns/Hekili/State.lua:4810> [string "@Interface/AddOns/Hekili/State.lua"]:4866: in function <Interface/AddOns/Hekili/State.lua:4810> [string "@Interface/AddOns/Hekili/State.lua"]:7193: in function `IsUsable' [string "@Interface/AddOns/Hekili/Core.lua"]:932: in function `GetPredictionFromAPL' [string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction' [string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

### Error Messages (Link)

n/a

### Additional Information

n/a

### Contact Information

theecableguy

**Comment by Hekili** [comment]
Update to the latest version.
