### ISSUE TITLE
[REC] Outlaw pre-combat Roll the Bones is never recomended. Might also help solve #2820

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#2916]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Outlaw I expect all `variable.rtb_reroll` entries to be also active during "Precombat" action list which is not true right now.

During opener according to curret APL Roll the Bones should be recomended before Adrenaline Rush.
(It is not accurate by the way according to rogue discord but i will adress it in another PR)

The problem is, that in precombat action list variable.rtb_reroll returns 0 instead of true or false.
If it could be fixed it might also help to solve #2820 on my opinion.

If I replace line 17 `variable.rtb_rerol`l with `rtb_buffs.normal=0` than it works all right.

Also there is an entry to reset rtb reroll conditions which is active only in the precombat list, but should be active in the general profile.

### How to Reproduce

1. Enter as Outlaw
2. The second recomendation should be Roll the Bones in precombat.

### Snapshot (Link)

https://pastebin.com/ZMx3MGuX

### Additional Information

Also, Hekili, I forgot to implement APL changes from this PR https://github.com/Hekili/hekili/commit/3491294097023330fe46ec9ff12c032a2ed092bf
into the profile itself.....

### Contact Information

IIeTpoc#3818 discord ID

**Comment by IIeTpoc** [comment]
Basicly this. It seems like variable.rtb_reroll does not work as intended out of combat.

        5.   roll_the_bones ( precombat - 5 )
        The action (roll_the_bones) is usable at (0.00 + 0.00) with cost of 25 energy (have 200).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry's criteria FAILS: refreshable[true] & variable.rtb_reroll[0.00]
        There were no recheck events to check.
        Time spent on this action:  0.68ms
        TimeData:Outlaw-precombat-5:roll_the_bones:0.68:Ability Known, Enabled(0.03):Post-TTR and Essential(0.09):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.03):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.28):Pre-Recheck(0.11):Post-Recheck Times(0.11):Post Recheck(0.01)

**Comment by Hekili** [comment]
That's not my priority; you can see why I put the rtb_reroll variable at the top of the default priority.

**Comment by IIeTpoc** [comment]
Afaik i was using your default version. 
Now I completely reinstalled the addon. Then ingame reset the in-built priority to default and yet get these recomendations. 
[Snapshot1](https://pastebin.com/4C0NPVg3)
![image](https://github.com/Hekili/hekili/assets/64799395/754d003b-9d55-47b0-b37b-e43ec03bd36d)

If i select all RAW text from https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/APLs/RogueOutlaw.simc and implement it in the addon in-game i get the same result as mentioned above.
[Snapshot2](https://pastebin.com/wGvDjsQE)

Here is screenshot from the Entry dropdown menu. There is no precombat action list there.
![image](https://github.com/Hekili/hekili/assets/64799395/1a36f633-463b-4f8c-85d0-9424c1bbdb92)

And here is screenshot from the Action List dropdown menu. There is precombat list.
![image](https://github.com/Hekili/hekili/assets/64799395/bb2a342b-9872-44ef-a90f-ff8bc665482b)

I can not understand what am i doing wrong to be honest.

In the snapshot in precombat variable.rtb_reroll returns 0
![image](https://github.com/Hekili/hekili/assets/64799395/cce6d6c8-a7f0-49f3-b28e-e5079ff9b881)
![image](https://github.com/Hekili/hekili/assets/64799395/4f5ac6c5-f625-4a55-a920-a3c3bc6ddf9d)


But in-combat returns either true or false
![image](https://github.com/Hekili/hekili/assets/64799395/6aaf1927-c8cb-4e58-a9a1-14367fdedc5a)

**Comment by Hekili** [comment]
This should be fixed in today's release.
