### ISSUE TITLE
[REC] Assassination not able to give recco after prolonged use 1-3 target happens fairly often

### ISSUE THREAD

**Issue by GamingSeat** [Hekili/hekili#2918]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I was just simply fighting open world content in emerald dream and it couldnt reco a generator or spender and would vanish then reappear if i pressed a random generator

### How to Reproduce

1. Enter game as assa rogue
2. flow through rotation as hekili suggests
3. get no reco after going through rotation for a bit

### Snapshot (Link)

https://pastebin.com/waT6zWge

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/gmZY68tw2pyopLGfYndcsU

### Additional Information

For multi-target: https://www.raidbots.com/simbot/report/2uy1U6CFyFhHVrbWFVShRt

### Contact Information

Discord: Null.key

**Comment by Delerp** [comment]
I had this issue in older version also, your snapshot shows your hekili version as v10.2.0-1.0.0g which is several versions old, right now current one is v10.2.0-1.0.1c

try updating the addon and see if this still occurs

**Comment by Hekili** [comment]
This will be fixed in today's release.
