### ISSUE TITLE
[REC] Crimson tempest not recommended when target swapping is active

### ISSUE THREAD

**Issue by Delerp** [Hekili/hekili#2919]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Crimson tempest is not being recommended in aoe against 5 combat dummies, according to guides tempest is to be maintained with high priority in aoe situations

### How to Reproduce

1. Test rotation against dummies with crimson tempest talented
2. do not get any recommendations for applying crimson tempest

### Snapshot (Link)

https://pastebin.com/NT4fg9si

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6VTKPxG7ja3fXeFK8dtbAa

### Additional Information

Ability is used in the sim and is tempest is the largest damage contributor there, is this caused by my target being dummies which have infinite target time to die?

**Comment by Delerp** [comment]
Did a new test without using recommend target swaps, this time crimson tempest was recommended as usual!
something to do with target swap recommending?
Snapshot:https://pastebin.com/wcgyRUqT

**Comment by Hekili** [comment]
The real difference between those snapshots is that in the one that uses Crimson Tempest, Deathmark is on cooldown.  In the one that does not use CT, Deathmark is not on cooldown.

I can adjust for that.

**Comment by Hekili** [comment]
This will be resolved in today's release.
