### ISSUE TITLE
Vision change for rogue apl dont work

### ISSUE THREAD

**Issue by noiseuu** [Hekili/hekili#292]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/ReinftwN
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here. 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/D3VqjHec
3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by noiseuu** [comment]
And im talking about this "Adjusted Vanish to be used "on cooldown" (ignoring Vendetta) for Nightstalker and Master Assassin builds when using Vision of Perfection (minor increase for VoP minor with NS/MA)". I tested fast raidbots quick sim and it uses vanish when it comes from cooldown

**Comment by Hekili** [comment]
Vanish isn't recommended solo because it would drop combat.

**Comment by noiseuu** [comment]
I know, but in raid same happend, but in pulls i dont have time pause and snapshot problem

**Comment by Hekili** [comment]
Well, open a ticket when you can. There's always LFR, world quest groups, etc. 

Submitting a snapshot that's not relevant is kind of odd.

**Comment by noiseuu** [comment]
https://pastebin.com/yXXB68md there u have from normal skitra, it does correctly vendetta in "cooldown" but after vanish doesnt come..

**Comment by Hekili** [comment]
So, the relevant recent APL changes:

```
# Vanish with Nightstalker + No Exsg: Maximum CP and Vendetta up (unless using VoP)
actions.cds+=/vanish,if=talent.nightstalker.enabled&!talent.exsanguinate.enabled&combo_points>=cp_max_spend&(debuff.vendetta.up|essence.vision_of_perfection.enabled)
```

That corresponds to this:
```
32.  vanish ( cds - 10 )
The action (vanish) is usable at (0.00 + 0.00) with cost of 0.
    - the action is ready before the current recommendation (at +0.00 vs. +60.00).
List ( cds ) called from ( Assassination:default:6 ) would PASS at 0.00.
( ! talent.master_assassin.enabled[true] | dot.garrote.ticking[true] )
    - this entry's criteria FAILS: talent.nightstalker.enabled[false] & ! talent.exsanguinate.enabled[false] & combo_points.current[5.00] >= cp_max_spend[5.00] & ( debuff.vendetta.up[false] | essence.vision_of_perfection.enabled[false] )
There were no recheck events to check.
```

The criteria still require the Nightstalker talent, so it failed.

The next APL change...

```
# Vanish with Master Assasin: No stealth and no active MA buff, Rupture not in refresh range, during Vendetta+TB+BotE (unless using VoP)
actions.cds+=/vanish,if=talent.master_assassin.enabled&!stealthed.all&master_assassin_remains<=0&!dot.rupture.refreshable&dot.garrote.remains>3&(debuff.vendetta.up&(!talent.toxic_blade.enabled|debuff.toxic_blade.up)&(!essence.blood_of_the_enemy.major|debuff.blood_of_the_enemy.up)|essence.vision_of_perfection.enabled)
```

That corresponds to:

```
36.  vanish ( cds - 14 )
The action (vanish) is usable at (0.00 + 0.00) with cost of 0.
    - the action is ready before the current recommendation (at +0.00 vs. +60.00).
List ( cds ) called from ( Assassination:default:6 ) would PASS at 0.00.
( ! talent.master_assassin.enabled[true] | dot.garrote.ticking[true] )
    - this entry's criteria FAILS: talent.master_assassin.enabled[true] & ! stealthed.all[false] & master_assassin_remains[0.00] <= 0 & ! dot.rupture.refreshable[false] & dot.garrote.remains[4.66] > 3 & ( debuff.vendetta.up[false] & ( ! talent.toxic_blade.enabled[true] | debuff.toxic_blade.up[false] ) & ( ! essence.blood_of_the_enemy.major[true] | debuff.blood_of_the_enemy.up[false] ) | essence.vision_of_perfection.enabled[false] )
There were no recheck events to check.
```

In this case, you're not using Vision of Perfection, so the new exception added to the APL doesn't apply in your case.

**Comment by noiseuu** [comment]
Weird!? Still u can see what my essences are? Or do i need replace it and replace back?

https://gyazo.com/cad6ee7f09530daa939d79bdd6726889 i took screenshot for u, and i replaced to different and put back on

**Comment by Hekili** [comment]
```
Click here and press CTRL+A, CTRL+C to copy the snapshot.
 
build: v8.3.0-04-12
level: 120 (120)
class: ROGUE
spec: assassination
 
talents: cheat_death
    elaborate_planning
    master_assassin
    poison_bomb
    prey_on_the_weak
    toxic_blade
    vigor
 
azerite: azerite_empowered = 3
    double_dose = 3
    elemental_whirl = 1
    gemhide = 1
    nothing_personal = 1
    overwhelming_power = 2
    personal_absorbotron = 1
    relational_normalization_gizmo = 1
    resounding_protection = 1
 
essences: [blood_of_the_enemy] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 4
```

When you snapshotted, you had BOTE r3 primary, Breath of the Dying r3 and Lucid Dreams r4 secondaries.  Do you not have a third secondary essence?

**Comment by noiseuu** [comment]
Yes, i have? Here is same screenshot for u again
https://gyazo.com/cad6ee7f09530daa939d79bdd6726889

**Comment by Hekili** [comment]
Cool; the addon wasn't checking the last Essence slot.  I'll address that and post an update.

**Comment by noiseuu** [comment]
Thanks, and sry disturbing your time :D
