### ISSUE TITLE
Agumentation - Eruption recommanded outside Ebon Might buff and other minor issue

### ISSUE THREAD

**Issue by N30Exca** [Hekili/hekili#2920]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Erruption gets suggested if Essence burst is active but EM is not ready and it shouldnen't

I also noticed that after fire breath suggested at rank 4 it will nevere again gat suggested at rank 4 and some times during rotation when casting it or upheaval all suggestion totaly disapeared

### How to Reproduce

running normal rotation if essence burst is up and ebon might is not ready erruption still get suggested

### Snapshot (Link)

https://pastebin.com/4BFK6wuV

### Contact Information

discord id: n30exca

**Comment by Hekili** [comment]
Have you simmed yourself and looked whether this would happen in your sim?

**Comment by N30Exca** [comment]
Not the point here man, you never ever cast and extender (Eruption/BoF/UH) outside EM buff and if you talk about BoF rank you cast It rank 4 in nearly all of the scenario.

**Comment by Hekili** [comment]
> nearly all of the scenario

This means sometimes.  So knowing if it would happen in the sim (which now can be done) is important.

**Comment by N30Exca** [comment]
Yes ok but..... Sim for Agu is not fully implemented and is still basicly for developers...

**Comment by N30Exca** [comment]
![image0](https://github.com/Hekili/hekili/assets/19918258/785a972e-939e-491c-b365-f6ab982ec859)
also this

**Comment by howlenoates** [comment]
You are allowed to use eruption if you are capped on essence burst procs and ebon might is on cooldown, or if you are at max essence charges and ebon might is on cooldown and the time it would take to recharge to full is less than how much longer ebon might is on cooldown for

**Comment by N30Exca** [comment]
> You are allowed to use eruption if you are capped on essence burst procs and ebon might is on cooldown, or if you are at max essence charges and ebon might is on cooldown and the time it would take to recharge to full is less than how much longer ebon might is on cooldown for

You never ever cast It outside EM.... Or any extender at all Just check evoker discord....

**Comment by howlenoates** [comment]
> > You are allowed to use eruption if you are capped on essence burst procs and ebon might is on cooldown, or if you are at max essence charges and ebon might is on cooldown and the time it would take to recharge to full is less than how much longer ebon might is on cooldown for
> 
> You never ever cast It outside EM.... Or any extender at all Just check evoker discord....

You go ask yourself. You are correct that you should not use fire breath or upheavel outside of EM ever. But you are allowed to cast eruption in very specific scenarios, which I outlined above. The reason you can use eruption in those cases is because your essence or essence burst procs would be otherwise wasted if you held onto them to wait for EM to come back off cooldown. Thus it is a dps increase to use eruption in those specific cases because you aren't using resources you need.

**Comment by N30Exca** [comment]
> > > You are allowed to use eruption if you are capped on essence burst procs and ebon might is on cooldown, or if you are at max essence charges and ebon might is on cooldown and the time it would take to recharge to full is less than how much longer ebon might is on cooldown for
> > 
> > 
> > You never ever cast It outside EM.... Or any extender at all Just check evoker discord....
> 
> You go ask yourself. You are correct that you should not use fire breath or upheavel outside of EM ever. But you are allowed to cast eruption in very specific scenarios, which I outlined above. The reason you can use eruption in those cases is because your essence or essence burst procs would be otherwise wasted if you held onto them to wait for EM to come back off cooldown. Thus it is a dps increase to use eruption in those specific cases because you aren't using resources you need.

If what you Say Is correct the WA should not trigger but It trigger meaning that in that Moment you should not cast Eruption...

**Comment by howlenoates** [comment]
> > > > You are allowed to use eruption if you are capped on essence burst procs and ebon might is on cooldown, or if you are at max essence charges and ebon might is on cooldown and the time it would take to recharge to full is less than how much longer ebon might is on cooldown for
> > > 
> > > 
> > > You never ever cast It outside EM.... Or any extender at all Just check evoker discord....
> > 
> > 
> > You go ask yourself. You are correct that you should not use fire breath or upheavel outside of EM ever. But you are allowed to cast eruption in very specific scenarios, which I outlined above. The reason you can use eruption in those cases is because your essence or essence burst procs would be otherwise wasted if you held onto them to wait for EM to come back off cooldown. Thus it is a dps increase to use eruption in those specific cases because you aren't using resources you need.
> 
> If what you Say Is correct the WA should not trigger but It trigger meaning that in that Moment you should not cast Eruption...

Here is the conditions for when you should cast eruption according to the Hekili addon, which is based on the SimC input:

buff.ebon_might.remains > execute_time | essence.deficit = 0 & buff.essence_burst.down | buff.essence_burst.stack = buff.essence_burst.max_stack & cooldown.ebon_might.remains > 4

What this means is use Eruption if at least one of the following is true:

1) You have enough time to cast Eruption before the Ebon Might buff ends
2) Ebon Might is on cooldown and will be off cooldown in greater than 4 seconds AND you are full on Essence and you have no Essence Burst up
3) Ebon Might is on cooldown and will be off cooldown in greater than 4 seconds AND you are full on Essence Burst stacks (usually this is 2 as we always run the talent which lets Essence Burst stack twice)

I see no issue with these commands, they provide you the right logic for when to use Eruption in any fight.

**Comment by N30Exca** [comment]
> > > > > You are allowed to use eruption if you are capped on essence burst procs and ebon might is on cooldown, or if you are at max essence charges and ebon might is on cooldown and the time it would take to recharge to full is less than how much longer ebon might is on cooldown for
> > > > 
> > > > 
> > > > You never ever cast It outside EM.... Or any extender at all Just check evoker discord....
> > > 
> > > 
> > > You go ask yourself. You are correct that you should not use fire breath or upheavel outside of EM ever. But you are allowed to cast eruption in very specific scenarios, which I outlined above. The reason you can use eruption in those cases is because your essence or essence burst procs would be otherwise wasted if you held onto them to wait for EM to come back off cooldown. Thus it is a dps increase to use eruption in those specific cases because you aren't using resources you need.
> > 
> > 
> > If what you Say Is correct the WA should not trigger but It trigger meaning that in that Moment you should not cast Eruption...
> 
> Here is the conditions for when you should cast eruption according to the Hekili addon, which is based on the SimC input:
> 
> buff.ebon_might.remains > execute_time | essence.deficit = 0 & buff.essence_burst.down | buff.essence_burst.stack = buff.essence_burst.max_stack & cooldown.ebon_might.remains > 4
> 
> What this means is use Eruption if at least one of the following is true:
> 
> 1. You have enough time to cast Eruption before the Ebon Might buff ends
> 2. Ebon Might is on cooldown and will be off cooldown in greater than 4 seconds AND you are full on Essence and you have no Essence Burst up
> 3. Ebon Might is on cooldown and will be off cooldown in greater than 4 seconds AND you are full on Essence Burst stacks (usually this is 2 as we always run the talent which lets Essence Burst stack twice)
> 
> I see no issue with these commands, they provide you the right logic for when to use Eruption in any fight.

If the code is correct

why the WAra trigger then,,, if it trigger then....

Maybe because it isn't?

**Comment by howlenoates** [comment]
> > > > > > You are allowed to use eruption if you are capped on essence burst procs and ebon might is on cooldown, or if you are at max essence charges and ebon might is on cooldown and the time it would take to recharge to full is less than how much longer ebon might is on cooldown for
> > > > > 
> > > > > 
> > > > > You never ever cast It outside EM.... Or any extender at all Just check evoker discord....
> > > > 
> > > > 
> > > > You go ask yourself. You are correct that you should not use fire breath or upheavel outside of EM ever. But you are allowed to cast eruption in very specific scenarios, which I outlined above. The reason you can use eruption in those cases is because your essence or essence burst procs would be otherwise wasted if you held onto them to wait for EM to come back off cooldown. Thus it is a dps increase to use eruption in those specific cases because you aren't using resources you need.
> > > 
> > > 
> > > If what you Say Is correct the WA should not trigger but It trigger meaning that in that Moment you should not cast Eruption...
> > 
> > 
> > Here is the conditions for when you should cast eruption according to the Hekili addon, which is based on the SimC input:
> > buff.ebon_might.remains > execute_time | essence.deficit = 0 & buff.essence_burst.down | buff.essence_burst.stack = buff.essence_burst.max_stack & cooldown.ebon_might.remains > 4
> > What this means is use Eruption if at least one of the following is true:
> > 
> > 1. You have enough time to cast Eruption before the Ebon Might buff ends
> > 2. Ebon Might is on cooldown and will be off cooldown in greater than 4 seconds AND you are full on Essence and you have no Essence Burst up
> > 3. Ebon Might is on cooldown and will be off cooldown in greater than 4 seconds AND you are full on Essence Burst stacks (usually this is 2 as we always run the talent which lets Essence Burst stack twice)
> > 
> > I see no issue with these commands, they provide you the right logic for when to use Eruption in any fight.
> 
> If the code is correct
> 
> why the WAra trigger then,,, if it trigger then....
> 
> Maybe because it isn't?

I don't understand what you mean. The addon is only triggering Eruption how i detailed out above. Which is not an issue.

**Comment by N30Exca** [comment]
Im talking about this WA

https://wago.io/XfOM-zvXl

That helps you to don't cast extenders outside EM... I use it as a fail safe thats why i noticed this issue

**Comment by howlenoates** [comment]
> Im talking about this WA
> 
> https://wago.io/XfOM-zvXl
> 
> That helps you to don't cast extenders outside EM... I use it as a fail safe thats why i noticed this issue

Thank you for explaining. This weakaura has nothing to do with the Hekili addon, and it does exactly as you stated. It plays a sound when you cast eruption if Ebon Might is not up. They did not program that weakaura to take into account the small cases where it is okay to cast eruption outside of Ebon Might (as detailed above, and as the Hekili addon tells you).

You don't have to listen to the Hekili addon if you don't want. It is only a tiny tiny DPS increase to play the above described anyway. But just because that weakaura plays a sound outside of Ebon Might buff times, doesn't mean Hekili is wrong.

Once again, still you shouldn't cast Fire Breath or Upheaval outside of Ebon Might buff time, but Hekili does not recommend that anyway.

**Comment by N30Exca** [comment]
Ok if you say so.... 
still there are coupple other issue that i reported like all addon disapear while some time casting FB/UH and that is realt realy wierd

**Comment by Hekili** [comment]
Good vibes only in the tickets, please.

You can customize your priority if you want to sit at cap with 2 stacks + full Essence for several seconds, but I don't think it would actually be optimal (which is why it's specifically accounted for).  The addon is notorious for revealing the exceptions and/or intersections between rules.
