### ISSUE TITLE
[BUG] The game is freeze when I use the Fracture spell as Vengeance Demon Hunter 

### ISSUE THREAD

**Issue by gerhatmark** [Hekili/hekili#2922]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The game is freeze when I use the Fracture spell (Vengeance Demon Hunter ) and dont respond anymore.

This happens after I updated to Hekili-v10.2.0-1.0.1d.zip.

### How to Reproduce

1) Enter the game as Vengeance Demon Hunter.
2) Use the spell "Fracture" on any enemy while the addon is ON.

### Player Information (Link)

https://pastebin.com/Y7zu6E33

### Error Messages (Link)

https://pastebin.com/Y7zu6E33

### Contact Information

gerhatmark

**Comment by Hekili** [comment]
Reverting
