### ISSUE TITLE
[REC] Assassination opener

### ISSUE THREAD

**Issue by Delerp** [Hekili/hekili#2923]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The opener(Here's a snapshot of the hekili opener: https://pastebin.com/7kYPg9Ep) seems to differ quite a bit from APL(get slice and dice and rupture up as soon as possible, addon does not seem to cast slice and dice or rupture until later, seemingly focusing on getting envenom up asap)

Assa wants to buff last 3 seconds of kingsbane with master assassin buff which is gained by being in stealth(or vanishing), the apl has very strict requirements to do it:

vanish,if=talent.master_assassin&talent.kingsbane&dot.kingsbane.remains<=3&dot.kingsbane.ticking&debuff.deathmark.remains<=3&dot.deathmark.ticking

Sometimes the opener for Hekili differs a bit in timings, making it so that both of these debuffs being under 3 seconds remaining does not occur so vanish does not get suggested for the burst dps

### How to Reproduce

1.Have master assassin talent, kingsbane and deathmark
2.in singletarget, do the rotation and sometimes deathmark and kingsbane are cast with a sizeable delay between them
3.this ends up desyncing so that vanish never gets recommended

### Snapshot (Link)

https://pastebin.com/qcmEdTFb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/xh5NjLufq5u4fZL9t9iYxU/simc

### Additional Information

In this snapshot with 4 recommendations visible, hekili suggests Deathmark, but after it its suggesting mutilate and slice and dice, in apl and guides the burst is the following combo: Deathmark, Shiv, shadow dance, kingsbane.

Looks like the apl goes envenom-dethmark-shiv-shadowdance-kingsbane, even outside of the opener, to sync the duration of kingsbane dot and deathmark debuff.

Currently what is happening is hekili is casting envenom very early(third cast) sometimes resulting in buff.envenom.up being false for shadowdance's requirements?

**Comment by Delerp** [comment]
Here's two more snapshots, sometimes it seems to be working correcntly:

https://pastebin.com/AUuNMUGz

recommending deathmark,shadow dance,kingsbane

https://pastebin.com/yT0DFjNa

recommending deathmark, mutilate, slicendice

**Comment by Delerp** [comment]
Part may be caused by this line:
rupture,if=effective_combo_points>=4&(pmultiplier<=1)&refreshable&target.time_to_die-remains>(4+(talent.dashing_scoundrel * 5)+(variable.regen_saturated * 6))

part 6 of actions.dot which is used very early on by apl(garrote-ambush-rupture) but hekili suggests envenom instead(garrote-ambush-envenom)

after this, slice and dice is not suggested in the opener due to rupture not ticking:
slice_and_dice,if=!buff.slice_and_dice.up&dot.rupture.ticking&combo_points>=2|!talent.cut_to_the_chase&refreshable&combo_points>=4

Apologies for all the edits, i found an issue and tried to debug it all the way to see what was causing it

**Comment by fzarr** [comment]
It appears that this has been introduced with the latest APL - rolling back to previous version alone doesn't work, but also rolling back the APL does,

**Comment by Hekili** [comment]
Reverting.
