### ISSUE TITLE
Unholy DK - Gargoyle showing Dark Arbiter Icon in Rotation after Update, can't / won't clear

### ISSUE THREAD

**Issue by notoriousmonster** [Hekili/hekili#2924]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Started appearing for me today after update:

On Unholy DK, if you spec into Gargoyle (Standard for Raid Builds) the rotation will no longer show Gargoyle in the queue but instead show the Icon for Dark Arbiter which is currently not in the game for 10.2 

If you press Gargoyle, it doesn't clear Dark Arbiter from the queue

While Dark Arbiter is in the queue, the following actions aren't prioritizing Rune Spending / Runic Power Building 

![Screenshot 2023-11-15 104210](https://github.com/Hekili/hekili/assets/150947577/627f84d6-543c-4713-96fe-80163c6f180b)

### How to Reproduce

1. Select Gargoyle as a Talent on Unholy DK

### Snapshot (Link)

https://pastebin.com/BbX1UteA

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fxrBevBm7C4PfTXpBDbpvR

### Additional Information

I provided a sim however the issue seems to be specifically with talenting in gargoyle and it showing dark arbiter instead 

### Contact Information

notoriousmonster

**Comment by Hekili** [comment]
Dark Arbiter exists; you can change your Gargoyle to a Val'kyr at a trainer.  This is a different issue, but I'm not sure exactly the cause.

When you log in, what does `/dump GetSpellInfo("Summon Gargoyle")` show?

**Comment by lethalg101** [comment]
![image](https://github.com/Hekili/hekili/assets/150962103/e64c354a-925a-4d75-9861-f4ff4a66347e)

**Comment by thesnowfury** [comment]
Can confirm, happening to me too, single target build with Gargoyle (never changed it at trainer). Symptoms exactly as described above.

**Comment by Hekili** [comment]
Can you confirm whether you have the spell "glyphed" via your trainer?

**Comment by lethalg101** [comment]
I do not.

**Comment by Hekili** [comment]
Will revert today's change and post a fix in a bit.
