### ISSUE TITLE
DH Vangeance game freeze

### ISSUE THREAD

**Issue by n00del** [Hekili/hekili#2925]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Game is freezing for almost 1 min and then lua error appears

### How to Reproduce

1. Enter game as Demon Hunter Vengeance
2. Play Rotation and wait until Freeze

### Player Information (Link)

https://pastebin.com/Dv8E2JJD

### Error Messages (Link)

https://pastebin.com/L8RricrE

### Contact Information

n00del

**Comment by n00del** [comment]
seems like the freezes are only in open world but happens very often but on m+ i dont even had one

**Comment by Debugga-nb** [comment]
I can add a +1 to this one. It's happened a few times, and it's a hard hard freeze. You can still alt+tab to escape, but the game will also eventually "catch-up" and resume with a bug being thrown/caught by grabber.

**Comment by Hekili** [comment]
Are there more error messages or warnings?  That one isn't very useful, unfortunately.  I'll revert an edit to Vengeance until I solve it.

**Comment by Debugga-nb** [comment]
Sorry, I totally spaced including the bugstack output. 

`
3x Hekili/UI.lua:2328: script ran too long
[string "@Hekili/UI.lua"]:2328: in function <Hekili/UI.lua:2261>

Locals:
self = HekiliEngine {
 0 = <userdata>
 lastUpdate = 174806805.896600
 activeThreadStart = 174807203.168200
 UpdatePerformance = <function> defined @Hekili/UI.lua:2199
 firstThreadCompleted = true
 criticalUpdate = false
 activeThreadTime = 2.821600
 lastYieldReason = "Reset Pre-Cast Hook"
 threadUpdates = <table> {
 }
 activeThreadFrames = 2
 eventsTriggered = <table> {
 }
 combatRate = 0.200000
 activeThread = <no value>
 refreshTimer = 0
 IsThreadActive = <function> defined @Hekili/UI.lua:2369
 refreshRate = 0.500000
 superUpdate = false
}
elapsed = 0.036000
thread = <no value>
firstDisplay = nil
superUpdate = false
ok = false
err = "Hekili/Dragonflight/DemonHunterVengeance.lua:667: script ran too long"
(*temporary) = false
(*temporary) = "Hekili/Dragonflight/DemonHunterVengeance.lua:667: script ran too long"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
insert = <function> defined =[C]:-1
frameSpans = <table> {
}
Hekili = <table> {
 GetMacroCastTarget = <function> defined @Hekili/Events.lua:1112
 GetTTD = <function> defined @Hekili/Targets.lua:1190
 IC = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili/Options.lua:4050
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili/Targets.lua:1175
 GetPetBasedTargetSpells = <function> defined @Hekili/Targets.lua:121
 ContinueOnSpellLoad = <function> defined @Hekili/Events.lua:271
 After = <function> defined @Hekili/Utils.lua:284
 LoadingScripts = false
 activeFrameStart = 174807225.773900
 GetGreatestTTD = <function> defined @Hekili/Targets.lua:1269
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 currentSpecOpts = <table> {
 }
 SaveCoordinates = <function> defined @Hekili/UI.lua:3090
 PLAYER_ENTERING_WORLD = true
 UpdateDisplayVisibility = <function> defined @Hekili/UI.lua:2063
 PendingSpecializationChange = false
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 ResetSpellCaches = <function> defined @Hekili/Core.lua:580
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili/State.lua:6864
 SetMode = <function> defined @Hekili/Options.lua:11071
 Version = "v10.2.0-1.0.1d"
 baseName = "Hekili"
 GetPetBasedTargetSpell = <function> defined @Hekili/Targets.lua:133
 ToggleHold = <function> defined @Hekili/State.lua:6889
 SpecializationChanged = <function> defined @Hekili/Classes.lua:6080
 Update = <function> defined @Hekili/Core.lua:1446
 BuildUI = <function> defined @Hekili/UI.lua:2803
 IsRetail = <function> defined @Hekili/Hekili.lua:23
 GetNumTargetsAboveHealthPct = <function> defined @Hekili/Targets.lua:1346
 GetNextPrediction = <function> defined @Hekili/Core.lua:1333
 UpdateUseItems = <function> defined @Hekili/Events.lua:657
 SetSpecOption = <function> defined @Hekili/Options.lua:3832
 GetDefaults = <function> defined @Hekili/Options.lua:448
 dumpKeyCache = <table> {
 }
 GetPredictionFromAPL = <function> defined @Hekili/Core.lua:657
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 GetDisplayByName = <function> defined @Hekili/Core.lua:1415
 Options = <table> {
 }
 ReInitialize = <function> defined @Hekili/Core.lua:167
 GetSpellLinkWithTexture = <function> defined @Hekili/Utils.lua:582
 IsSpellEnabled = <function> defined @Hekili/Core.lua:574
 GetAbilityInfo = <function> defined @Hekili/Classes.lua:6025
 IsSpellKnown = <funct
`
