### ISSUE TITLE
[REC] Hunter's Mark Not Recommended For Hunter Specs

### ISSUE THREAD

**Issue by sudoalias** [Hekili/hekili#2926]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

None of the current Hunter class priorities support Hunter's Mark.  I have checked the Simulationcraft and it is not there yet either, but I thought it would be a good idea to get it into Hekili.  Hunter's Mark should be used when another Hunter has not already used it on a target with higher than 80% health (and likely a bit above that as it only affects 100%-80%).  It does not have a duration, but it does have a cooldown when used in combat.

### How to Reproduce

1. Enter the game as a Hunter (survival, marksmanship or beast mastery)
2. Target a mob (including valdrakken target dummies)
3. Hunter's Mark is never recommended.

### Snapshot (Link)

n/a - Spell is not in current priorities

**Comment by sudoalias** [comment]
Forgot to mention, Hunter's Mark spell id and debuff id are 257284 if that helps.

**Comment by sudoalias** [comment]
Something like refreshable & target.health.percent >= 85 doesn't work because it doesn't take other player's hunter's mark debuffs on the same target into account and only one hunter's mark can provide the benefit.

**Comment by Hekili** [comment]
> n/a - Spell is not in current priorities

Snapshot is still required.  Take a snapshot when it should be used but isn't.

> Something like refreshable & target.health.percent >= 85 doesn't work because it doesn't take other player's hunter's mark debuffs on the same target into account and only one hunter's mark can provide the benefit.

Is that something you tried?

**Comment by sudoalias** [comment]
> > n/a - Spell is not in current priorities
> 
> Snapshot is still required. Take a snapshot when it should be used but isn't.
> 
> > Something like refreshable & target.health.percent >= 85 doesn't work because it doesn't take other player's hunter's mark debuffs on the same target into account and only one hunter's mark can provide the benefit.
> 
> Is that something you tried?

Yes, I tested it on a line in the priorites.  Also tried target.debuff.hunters_mark.exists and debuff.hunters_mark.exists.  The latter two don't work at all because it isn't a registered spell in the addon for the addon to track.

**Comment by Hekili** [comment]
Yeah, that's not proper syntax.  Were you going to provide a snapshot and link to a sim?

**Comment by Hekili** [comment]
May be included in latest release.
