### ISSUE TITLE
[REC] Unholy - Mirror being prompted to use after army

### ISSUE THREAD

**Issue by Breadwinka** [Hekili/hekili#2927]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Mirror is being asked to use right after army which is incorrect it should be during UA+ERW

### How to Reproduce

1. look at a mob
2. You can see mirror being recommended 2nd
3. cast army
4. MIrror is recommended.

### Snapshot (Link)

https://pastebin.com/aqEC8dXD

**Comment by Hekili** [comment]
Is it your trinket?

**Comment by Breadwinka** [comment]
Yes its my trinket [Mirror of Fractured Tomorrows]

**Comment by Hekili** [comment]
Thanks; I see the issue and it'll be fixed in next release.
