### ISSUE TITLE
Enhancement trinket doesn't work

### ISSUE THREAD

**Issue by nechyu** [Hekili/hekili#2929]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

My'das Talisman trinket not shown in rotation

### How to Reproduce

Start combat, and for 1 min of combat do not show up in My'das Talisman's recommendations

### Snapshot (Link)

https://pastebin.com/ca8BB3pH

**Comment by Hekili** [comment]
>         Substituting mydas_talisman for Талисман Ми'даса action; it is otherwise not included in the priority.
>        16.  mydas_talisman ( default - 7 ) - ability disabled ( preference )
>        Time spent on this action:  0.05ms
>        TimeData:Enhancement-default-7:mydas_talisman:0.05:Ability Known, Enabled(0.05)

Did you disable the trinket in /hekili > Gear and Items?

**Comment by nechyu** [comment]
Yes I did have the trinkets turned off. Thanks for the tip,
