### ISSUE TITLE
Brewmaster Preferences setting does not work

### ISSUE THREAD

**Issue by JamesHarden-13** [Hekili/hekili#293]
The Primary Display does not show  them when the condition is true

<img width="436" alt="20200306140554" src="https://user-images.githubusercontent.com/61502135/76057428-7468d200-5fb4-11ea-9a24-0e56b5173a2a.png">

**Comment by Hekili** [comment]
1.  Fill out tickets completely, as this is missing information that would be helpful in explaining the situation.

2.  All of these preferences are *in addition to* the conditions in your priority list.  Take a look in /hekili > Priorities > Brewmaster or get a snapshot when you think something should've been shown but wasn't.
