### ISSUE TITLE
[BUG] No longer showing action bar reccomnedations on Hunter

### ISSUE THREAD

**Issue by jdm12983** [Hekili/hekili#2931]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Just updated from v10.2.0-1.0.1f from version v10.2.0-1.0.1c.  And for whatever reason I get no action bar button highlights anymore for my level 70 Beast Master Hunter.

Although I just logged onto my level 70 Ret. Paladin and it seems to be highlighting fine. [not sure if having this error with other classes yet or not.]

### How to Reproduce

1. Log into Beast Master Hunter.
2. Fight an enemy.
3. Get no button highlighting on my action bars.

### Player Information (Link)

https://pastebin.com/VMErRdj1

### Error Messages (Link)

none

**Comment by jdm12983** [comment]
Been a while sense I played my hunter; looks like it wasn't working for v10.2.0-1.0.1c either.

**Comment by Hekili** [comment]
I don't know what action bar highlights are.

**Comment by jdm12983** [comment]
Sorry, the "starburst"/flashing that shows around abilities on the main action bars (the default bars that are keybind for 1-9; etc.) - as the addon recommends what to use next.

**Comment by syrifgit** [comment]
Entire primary display fails as soon as I enter AoE scenario. Looks to me like the cleave list isn't even being called/tested despite the fact the addon knows there are 5 enemies (if you look at the condition testing on the ST list)

https://pastebin.com/52ESE1NE

**Comment by JPee01** [comment]
> Entire primary display fails as soon as I enter AoE scenario. Looks to me like the cleave list isn't even being called/tested despite the fact the addon knows there are 5 enemies (if you look at the condition testing on the ST list)
> 
> https://pastebin.com/52ESE1NE

Agree, AOE seems to be really broken however this should probably be a separate thread maybe to hopefully receive a fix soon?

**Comment by jdm12983** [comment]
Played my Hunter some more; currently using v10.2.0-1.0.3; it suggested using Hunter's Mark, then wouldn't suggest anything else.

**Comment by Hekili** [comment]
> Sorry, the "starburst"/flashing that shows around abilities on the main action bars (the default bars that are keybind for 1-9; etc.) - as the addon recommends what to use next.

That's SpellFlash, which is another addon/library that gets packaged with mine.  I'm not in control of it, though I've contributed to it before.  You can try dropping this file in `Hekili/Libs/SpellFlashCore` after each update until there's a formal fix.  You need to rename it from .txt to .lua for it to work.

[SpellFlashCore.txt](https://github.com/Hekili/hekili/files/13400697/SpellFlashCore.txt)

**Comment by Hekili** [comment]
> Entire primary display fails as soon as I enter AoE scenario. Looks to me like the cleave list isn't even being called/tested despite the fact the addon knows there are 5 enemies (if you look at the condition testing on the ST list)
> 
> https://pastebin.com/52ESE1NE

Is this still happening?  Did you import something?  Because the last entry in your default action list isn't calling the cleave prioirty.  Did it get unset in your priority somehow?

It should look like: 
![image](https://github.com/Hekili/hekili/assets/9438134/3faa73e1-e270-46c4-8b04-a1cb3f9a5821)

**Comment by syrifgit** [comment]
It actually has been working fine, I forgot to update my comment. Been
playing BM in keys and raid the last couple days with 0 issues related to
anything.

**Comment by jdm12983** [comment]
> > Sorry, the "starburst"/flashing that shows around abilities on the main action bars (the default bars that are keybind for 1-9; etc.) - as the addon recommends what to use next.
> 
> That's SpellFlash, which is another addon/library that gets packaged with mine. I'm not in control of it, though I've contributed to it before. You can try dropping this file in `Hekili/Libs/SpellFlashCore` after each update until there's a formal fix. You need to rename it from .txt to .lua for it to work.
> 
> [SpellFlashCore.txt](https://github.com/Hekili/hekili/files/13400697/SpellFlashCore.txt)

OK, I will try, but, it's you addon that suggests what to highlight/flash next right?  If so, it's the addon not suggesting what's next - however, it's working fine on other classes.

Or, is this needed because of changes to the way the hunter class works in recent patches?

**Comment by JPee01** [comment]
> > > Sorry, the "starburst"/flashing that shows around abilities on the main action bars (the default bars that are keybind for 1-9; etc.) - as the addon recommends what to use next.
> > 
> > 
> > That's SpellFlash, which is another addon/library that gets packaged with mine. I'm not in control of it, though I've contributed to it before. You can try dropping this file in `Hekili/Libs/SpellFlashCore` after each update until there's a formal fix. You need to rename it from .txt to .lua for it to work.
> > [SpellFlashCore.txt](https://github.com/Hekili/hekili/files/13400697/SpellFlashCore.txt)
> 
> OK, I will try, but, it's you addon that suggests what to highlight/flash next right? If so, it's the addon not suggesting what's next - however, it's working fine on other classes.
> 
> Or, is this needed because of changes to the way the hunter class works in recent patches?

Hi
I'm having the same issue, works on all other classes just not hunter. I also never installed spellflash for this function to work in Hekili so not sure why it would work on other classes if related to spellflash addon/library

**Comment by jdm12983** [comment]
OK, I seem to have found out what my issue might be - and no clue why it's suddenly a problem when it wasn't before [maybe something to do with WoW patch 10.2?]

For 2 or 3 of my main hunter attacks I use macros that would also make sure my pet is using it's main attacks; however, if I replace the macros with JUST the hunter ability/spell - it would start suggesting them again.

As I said, this is weird, because before (at some point withing the last month or so) it worked fine while using the macros on the main action bar.

**Comment by jdm12983** [comment]
OK, I now know for 100% sure: for whatever reason I cannot use a macro and have it flash as recommended anymore. Not sure why/when it changed. But, putting JUST the spell ability on the bar and the addon will recommend the ability again.

**_However_**! If I use the modified SpellFlashCore.txt you posted - I can use macro-based spells again.

**Comment by jdm12983** [comment]
Just wanted to add: I see that the SpellFlashCore lib got updated in your addon, and it is working fine for my toons.

Thanks for updating it - saves me the trouble of having to re-add the code every time.

**Comment by jdm12983** [comment]
Been a while sense I have played; but seems the permanent fix you uploaded to SpellFlashCore in your addon back around December 2023 has been removed again at some point between then and now.

Any chance you would be willing to add the fix back into your addon itself? OR just post an updated SpellFlashCore file here like before?

Thanks either way.
