### ISSUE TITLE
Doesn't Appear to be swapping recommended ST/AOE Aituations on AUTO.

### ISSUE THREAD

**Issue by AndrewKarlton** [Hekili/hekili#2932]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am trialling rotation on Feral Druid, and despite there being 5+ targets, it's not suggesting Primal Wrath ever, it's only suggesting Rip. Which is purely single target. Doesn't appear to change based on number of targets despite being on Auto.

Was working fine yesterday, appears to be after an update potentially on 16/11 or 15/11

### How to Reproduce

Not sure, just loaded in as feral druid with the below talents : 

BcGAORarfDaLt4uMx8TYOtl8GAAAAAAASk0STCSSSSJtDgSSkIJAAAAAAKAkIBAkkkkIJUSol4AAAAAAAIBAA

### Snapshot (Link)

https://pastebin.com/byYyKgKU

### Contact Information

andrew2396 (discord)

**Comment by holytobi** [comment]
Same as issue as Ret paladin. Some more deeper information for my case:

the variable "spell_targets.divine_storm" is precombat everytime on "5" but infight with 5 dummy targets its always "1".

Maybe a bug on your way to geht the information from the blizz api or maybe blizz changed there api

**Comment by Hekili** [comment]
I'm going to put together a cleaner ticket for tracking this issue.  Blizzard broke range checking via items (intentionally).  Update to v10.2.0-1.0.2wtf and if you have issues afterward, you can add to the new thread.  Thanks.
