### ISSUE TITLE
enh aoe prio not working 

### ISSUE THREAD

**Issue by Socksr4urfeet928** [Hekili/hekili#2933]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

as of todays reset addon isnt factoring in crash light, sunder, or chl in aoe. unchecking the range checker for rash and sunder seems to have fixed those but still no chl. it sometimes still has it in st. 

### How to Reproduce

enter as enh. take ele key build. goto dummies and follow prio list. 

### Player Information (Link)

https://pastebin.com/bn2CUNXD

### Error Messages (Link)

https://pastebin.com/fdgFQBeh

### Additional Information

talked to few others in disc about it an hes having the same problem. but others are not. 

### Contact Information

socksr4urfeet13

**Comment by Hekili** [comment]
I'm going to put together a cleaner ticket for tracking this issue.  Blizzard broke range checking via items (intentionally).  Update to v10.2.0-1.0.2wtf and if you have issues afterward, you can add to the new thread.  Thanks.
