### ISSUE TITLE
AOE not working: ret pal prio doesn't recommend aoe spells when multiple mobs near

### ISSUE THREAD

**Issue by Zachairi** [Hekili/hekili#2934]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

in AOE scenario either hekili doesn't detect the other nearby mobs or the ret prio is still recommending final verdict (single target spender) instead of divine storm (aoe target spender) when it is time to use a spender ability in the rotation. 
divine storm is never ever recommended no matter what.
providing a snapshot below

![WoWScrnShot_111623_150218](https://github.com/Hekili/hekili/assets/151081690/5627def4-578b-4919-9eb4-eb5fa35d9d8e)

### How to Reproduce

1. ret pal
2. start combat with multiple mobs near
3. generate holy power until hekili recommends you use divine storm or final verdict
4. hekili will incorrectly recommend you to final verdict (it should be divine storm in aoe scenario)

### Snapshot (Link)

https://pastebin.com/G9VGmuRS

**Comment by Zachairi** [comment]
Disregard warning in top right, I promise I'm a good boy. 👼

**Comment by karpana** [comment]
following, as this is the same issue I noticed when I went into Everbloom.

**Comment by Hekili** [comment]
I'm going to put together a cleaner ticket for tracking this issue.  Blizzard broke range checking via items (intentionally).  Update to v10.2.0-1.0.2wtf and if you have issues afterward, you can add to the new thread.  Thanks.
