### ISSUE TITLE
[FEATURE] Not Enough Resources Icon Adjustment 

### ISSUE THREAD

**Issue by GodsfavoritePerson** [Hekili/hekili#2936]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'd like to have the icon not fade out when the main icon is displaying the next recommended ability, and there is no reason to wait on pressing the button other than lack of resources. It makes sense and it feels right to have the main icon fade out when you should wait, like for pooling or to pair abilities together, but the icon seems like it should remain lit up when you only have low resources, so you know to keep spamming the button to add it to the spell queue window. I love Hekili for practicing new specs, but when the icon fades out I sometimes stop pushing buttons for a second. This is a small thing, and it just might be a me thing. Anyways, Cheers!

**Comment by Hekili** [comment]
That's not the only reason you wait.  Some specs specifically pool resources to a certain point before pushing their buttons (i.e., Feral and Ferocious Bite).
