### ISSUE TITLE
Shaman enhancment AOE Rotation BUG

### ISSUE THREAD

**Issue by Chicotx** [Hekili/hekili#2937]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm a Enhancment Shaman and the priority rotation of AOE situations is bugged, it is sugesting SGT abilities in AOE cenarius.

### How to Reproduce

1. Enter in the game as a Enhancment Shaman
2. Start my rotation to generate 10 stacks of malestrom in dummies to use AOE abilities and the addon suggest SGT abilities like Elemental Blast
<img width="1244" alt="asdasdasd" src="https://github.com/Hekili/hekili/assets/138011494/d45a2ba6-27bf-4dbb-979a-032376f194ed">

### Snapshot (Link)

asd

**Comment by Hekili** [comment]
I'm going to put together a cleaner ticket for tracking this issue.  Blizzard broke range checking via items (intentionally).  Update to v10.2.0-1.0.2wtf and if you have issues afterward, you can add to the new thread.  Thanks.
