### ISSUE TITLE
Arms AOE rotation not being recommended

### ISSUE THREAD

**Issue by jsuarezik** [Hekili/hekili#2938]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Arms warrior no matter the build ww/cleave is not being recommended nor sweeping strikes, weird because sometimes it does it sometimes it does not, I think is something about the active targets maybe blizzard changed nameplate detection or something along the lines

### How to Reproduce

1-Enter the game as Arms Warrior
2- Pick Merciless Bonegrinder or Hurricane with Bladestorm
3- Go to target dummies then use BS and no cleave/ww being recommended
4-Pick Fervor of Battle and Storm of Swords
5- Go to target  dummies use Sweeping Strikes> CDS > Warbreaker and no WW being recommended

### Snapshot (Link)

none couldnt get a good snapshot

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/aPzExKrurLD1qJS8VrJRgX

### Contact Information

__ _cheesus_ __

**Comment by jsuarezik** [comment]
I Can confirm this is happening with Sub rogue too, not getting recommended Black Powder

**Comment by karpana** [comment]
seems to also be the case with Ret Paladin....
I can see the "mob count" for a few seconds ... then it just stops.
and I think because of the missing "mob count" not being shown (likely not being derived/calculated) Hekili isn't recommending AoE abilities.

**Comment by Hekili** [comment]
I'm going to put together a cleaner ticket for tracking this issue.  Blizzard broke range checking via items (intentionally).  Update to v10.2.0-1.0.2wtf and if you have issues afterward, you can add to the new thread.  Thanks.

**Comment by YomamaNow** [comment]
I confirm same for Arms. I tried tweaking more sensitivity of targets but it is an-unideal temporary "solution" not really on par.

In a 5-dummy AOE, it should never be recommending slam, but was doing so every time in place of whirlwind and also not recommending sweeping strikes when it should or out of order (such as upon charge, instead of the appropriate post-charge Thunder Clap).

**Comment by YomamaNow** [comment]
ONE POSSIBLE FIX: Reset profile, don't activate AOE spellflash, leave only auto and single-target displays checked, and it actually started recommending the  right stuff for AOE again.

**Comment by YomamaNow** [comment]
Nevermind yea it's not a client-fixable thing. Like it worked for a bit on the dummy again, but then I went into dungeon and Bladestorm wasn't getting recommended whole  bunch of aoe stuff, so it's something deeper i think.

Would it possibly have to do with this change from Blizzard just yesterday:

(from) ### Hotfixes November 16, 2023 ### 

User Interface

**Restricted addon functions that allowed for in-combat distance checking between players.** (THIS ONE; Why Blizzard would even do this boggles my mind,.)

Developers’ notes: This change was intended to be implemented with the launch of the Guardians of the Dream patch, to avoid requiring that addon authors update their addons separately after the content is already being played. We apologize for the confusion and inconvenience.
