### ISSUE TITLE
Ret Paladin - Recommendations stop

### ISSUE THREAD

**Issue by dcodom** [Hekili/hekili#294]
The issue is only occuring on my paladin. As I am using the rotation, the number of buttons shown are 4, and then they slowly start to show less buttons, and then show no buttons. Even when no buttons are shown, nothing is on cooldown. If I sit for about a minute, doing nothing at all, they slowly start to reappear one by one. Then if I start killing another mob the same thing repeats. I check my other characters, but they do not have the same problem. 

This was not happening a few updates ago. My character has been sitting for a few days, so I do not know when it broke, and I know the addon has been updated a couple of times since I last logged onto this toon.

build: v8.3.0-04-14
level: 52 (52)
class: PALADIN
spec: retribution

talents: fist_of_justice
    hammer_of_wrath
    righteous_verdict

azerite: none

essences: none*, none

sets/legendaries/artifacts: none

gear: burnished_helm_of_might = 1
    burnished_legplates_of_might = 1
    renowned_guild_tabard = 1
    swift_hand_of_justice = 1
    worn_stoneskin_gargoyle_cape = 1

corruptions: none

itemIDs: 11994, 122260, 122263, 122264, 122361, 122365, 122370, 122372, 122662, 127010, 134683, 62174, 65705, 65727, 69210, 9289

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Retribution
    potion = potion_of_focused_resolve
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by dcodom** [comment]
Appears to be the same issue the DK user reported about a week ago. I have not tested on my dk.

**Comment by dcodom** [comment]
My unholy DK is not experiencing the same issue either.

So I have no clue what is going on. I will test my other characters if we need to, but dont know what could be causing the issue.

**Comment by Hekili** [comment]
All kinds of weird stuff can happen at low levels, that's why they're not supported. 

You'd need to snapshot when you're not getting recommendations as expected. But generally, priorities are written assuming you have all your talents available.
