### ISSUE TITLE
Survival Hunter - Recently, 2 new bugs appeared - One related to Harpoon and Butchery

### ISSUE THREAD

**Issue by Sapphire3279** [Hekili/hekili#2940]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

2 new bugs appeared after last updated:

1.  Harpoon keeps on being recommended even when in melee range of the enemy - This was not happening before.

2.  The rotation icons used to display the number of enemies nearby to enable AOE - this was also disabled and AOE rotation is no longer being recommended. In other words, the spell Butchery is no longer in the recommended spells.

Also, even when selected the profile of AOE only, the butchery spell is not recommended. Tried uninstalling the addon and reinstalling to no avail.

### How to Reproduce

![Screenshot 2023-11-16 221827](https://github.com/Hekili/hekili/assets/151087774/9c3788aa-4d8f-4662-b03e-cf214409902d)

### Snapshot (Link)

https://pastebin.com/kE06EGrZ

**Comment by Hekili** [comment]
I'm going to put together a cleaner ticket for tracking this issue.  Blizzard broke range checking via items (intentionally).  Update to v10.2.0-1.0.2wtf and if you have issues afterward, you can add to the new thread.  Thanks.

**Comment by Sapphire3279** [comment]
Still persisted even after update. Not detecting multiple enemies which results in no AOE recommendation. Which thread should I comment on to keep track of this update?
