### ISSUE TITLE
ALL TARGET DETECTION / RANGE CHECK RELATED ISSUES GO IN THIS THREAD

### ISSUE THREAD

**Issue by Hekili** [Hekili/hekili#2941]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On 16 November, Blizzard issued a hotfix that prevents addons from using `IsItemInRange` and `CheckInteractDistance`.  This addon used these API functions to aid in target detection and to determine (roughly) how far you are from targets.  Doing so, I could reasonably reliably provide target counting filtered by range to simplify target detection for melee specializations.

As of v10.2.0-1.0.2wtf (intentional, WTF?), I have stopped using IsItemInRange and LibRangeCheck-2.0, which relied upon the above API.  I'm grateful to be borrowing a newer, modified LibRangeCheck from the ElvUI team.  This does **not** restore the full previous functionality, but your UI should no longer taint and lock as you play with the addon.

As an additional workaround for melee, you can turn off `Use Nameplate Detection` in your specialization's options.  This will rely on counting targets you've recently damaged instead of nameplates.

![image](https://github.com/Hekili/hekili/assets/9438134/8601b4a8-af95-43c2-a80d-828b91c734e5)

**This means that nearby targets don't count as enemies until you've hit them with something.**  You'll want to "prime the pump" using an AOE ability that tells the addon you care about those nearby enemies.

If you're still having issues, you can add to this thread, including your snapshot and/or error messages in your first post.  If you don't include that information, I'll delete the post to save room.  Try to share everything relevant in one post to keep things manageable here.  Thank you.

### Additional Information

Read the above.  Keep me sane-ish.  Thanks.

### Contact Information

Hekili

**Comment by Sapphire3279** [comment]
This has solved the issue with regards to AOE for me, however Harpoon is still being recommended even when in close range and taking up a slot. Should I just disable the toggle harpoon for now?

**Comment by prideofkarma** [comment]
hello I have the same issue as the comment above, on my warrior it is spamming me telling me to press charge even though I am too close to charge. The issue is that it appears and goes away really fast while in combat and is moving every ability in my rotation back and forth really fast. is there a way to blacklist the ability in the settings? I do not see a toggle for charge anywhere but maybe I am just missing it

**Comment by Todi251** [comment]
Hey worked great before Blizzard issued the Hotfix.
Now for feral druid its not detecting when to go into AoE.
Have tried multiple options, but it doesnt detect nearby enemy, not from namepaltes (using Plater Nameplates) and not "Damaged/Dotted Enemys".
I am not using ElvUI.

**Comment by Fendrith** [comment]
Hello, For enhancement shaman, Sundering and Crash lightning will still not be recommended EVEN IF YOU UNCHECK "use nameplate detection". You have to go into enh core and uncheck "crash lightning range check" and "sundering range check" due to the above issues. It's possible similar things may exist on other classes

**Comment by wojciechkubiak** [comment]
Hi. 
On my side, it doesn't even load, no matter which character I use. And the right mouse button does pretty much nothing, on both the icon and the UI setup. Ofc, the addon is turned on.
ElvUI is not installed.

**Comment by cyberian1221** [comment]
> Hello, For enhancement shaman, Sundering and Crash lightning will still not be recommended EVEN IF YOU UNCHECK "use nameplate detection". You have to go into enh core and uncheck "crash lightning range check" and "sundering range check" due to the above issues. It's possible similar things may exist on other classes

Can confirm this is the case. Will also over-recommend lava blast on aoe, even 5+ targets. Essentially staying on the ST rotation unless you uncheck the ranged checks for sundering/CL

**Comment by shayne56** [comment]
Hello, I posted to closed issue #2950 re: Warrior Charge

Hello, I've followed the steps indicated for disabling target detection. I have installed wtf-b
https://pastebin.com/FcU1JwbG
Short video of charge popping up when the character moves:
https://www.veed.io/view/9abddd22-8a99-4a08-ab54-bf5f5e054b97?sharingWidget=true&panel=

**Comment by CharlTruter** [comment]
> Hello, I posted to closed issue #2950 re: Warrior Charge
> 
> Hello, I've followed the steps indicated for disabling target detection. I have installed wtf-b https://pastebin.com/FcU1JwbG Short video of charge popping up when the character moves: https://www.veed.io/view/9abddd22-8a99-4a08-ab54-bf5f5e054b97?sharingWidget=true&panel=

Having the exact same issue - also disabled nameplates detection and I have the latest wtf-b version.

**Comment by Demiralos** [comment]
Warrior's whirlwind is also broken after range check hotfix. At least in wtf-b version. Havent rolled back yet to check older version.
With everything correctly talented, and with hekili logic passing all the checks still wont recommend it. 

Digging through the snapshot it returns with this line:

40.  whirlwind ( multi_target - 3 )
The action (whirlwind) is unusable at (0.00 + 0.00) because target is outside of whirlwind range.
Time spent on this action:  0.12ms
TimeData:Fury-multi_target-3:whirlwind:0.12:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.05)

Was literally standing on top of the AoE dummies in valdrakken.
Even tested with Nameplate detection on/off, and with damaged + dotted enemies. No change.

**Comment by sudoalias** [comment]
> Warrior's whirlwind is also broken after range check hotfix. At least in wtf-b version. Havent rolled back yet to check older version. With everything correctly talented, and with hekili logic passing all the checks still wont recommend it.
> 
> Digging through the snapshot it returns with this line:
> 
> 40. whirlwind ( multi_target - 3 )
>     The action (whirlwind) is unusable at (0.00 + 0.00) because target is outside of whirlwind range.
>     Time spent on this action:  0.12ms
>     TimeData:Fury-multi_target-3:whirlwind:0.12:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.05)
> 
> Was literally standing on top of the AoE dummies in valdrakken. Even tested with Nameplate detection on/off, and with damaged + dotted enemies. No change.

this seeming worked better in wtf-a

**Comment by Peet207** [comment]
> > Warrior's whirlwind is also broken after range check hotfix. At least in wtf-b version. Havent rolled back yet to check older version. With everything correctly talented, and with hekili logic passing all the checks still wont recommend it.
> > Digging through the snapshot it returns with this line:
> > 
> > 40. whirlwind ( multi_target - 3 )
> >     The action (whirlwind) is unusable at (0.00 + 0.00) because target is outside of whirlwind range.
> >     Time spent on this action:  0.12ms
> >     TimeData:Fury-multi_target-3:whirlwind:0.12:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.05)
> > 
> > Was literally standing on top of the AoE dummies in valdrakken. Even tested with Nameplate detection on/off, and with damaged + dotted enemies. No change.
> 
> this seeming worked better in wtf-a

no this does not work better in wtf-a version. it doesnt at all. if i am out of range it shows the Whirlwind, but as soon as i get in melee it doesnt show Whirlwind anymore. actually i went back all versions 3 days ago and none worked. can it be that the newest update changed something in my WTF settings? guess i have to delete all settings now. thanks :)

**Comment by Demiralos** [comment]
> > > Warrior's whirlwind is also broken after range check hotfix. At least in wtf-b version. Havent rolled back yet to check older version. With everything correctly talented, and with hekili logic passing all the checks still wont recommend it.
> > > Digging through the snapshot it returns with this line:
> > > 
> > > 40. whirlwind ( multi_target - 3 )
> > >     The action (whirlwind) is unusable at (0.00 + 0.00) because target is outside of whirlwind range.
> > >     Time spent on this action:  0.12ms
> > >     TimeData:Fury-multi_target-3:whirlwind:0.12:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.05)
> > > 
> > > Was literally standing on top of the AoE dummies in valdrakken. Even tested with Nameplate detection on/off, and with damaged + dotted enemies. No change.
> > 
> > 
> > this seeming worked better in wtf-a
> 
> no this does not work better in wtf-a version. it doesnt at all. if i am out of range it shows the Whirlwind, but as soon as i get in melee it doesnt show Whirlwind anymore. actually i went back all versions 3 days ago and none worked. can it be that the newest update changed something in my WTF settings? guess i have to delete all settings now. thanks :)

Not this is not related to WTF settings. 100%. This is consequence of the range check fix again. I'll do some more testing and see what I can find out.

**Comment by PerfectionVR** [comment]
While in arms spec:

- If you are in combat
- In either multi- or single target situation
- You are moving within melee range, and not standing still

It will recommend charge for some strange reason.

https://pastebin.com/KgSnvc2a

**Comment by Warz78** [comment]
Is it no longer possible for current Hekili to recommend rotation for single target or multi target based on enemy detection in auto mode for a warrior?

**Comment by Mattucho** [comment]
As a Fury Warrior when im in combat, hekili recommend charge for some reason, but only when I move

**Comment by Warz78** [comment]
> As a Fury Warrior when im in combat, hekili recommend charge for some reason, being in melee range with the mob, but only when I move

Simple fix that I did for this was to disable charge in hekili.

**Comment by seann86** [comment]
I am aware of the changes with the range thing, and I'm not sure if my snapshot is correct, but thought I would post for Frost mage
As cone of cold is not being recommended for AOE
cheers https://pastebin.com/Kx8XjCkd

**Comment by AdamChattaway** [comment]
Turned OFF nameplate detection on feral druid and it's still using primal wrath AOE on a Angle mob in the middle of nowhere with no other enemies around it... You closed my post saying druid is completely broken 100%, It is, it's 100% fked.

**Comment by Peet207** [comment]
with new update it sometimes works now and sometimes not. 3 targets Whirlwind is recommended but 2 targets never. then sometimes 4 targets it is aoe rotation and then its single target rotation again...

**Comment by AdamChattaway** [comment]
> with new update it sometimes works now and sometimes not. 3 targets Whirlwind is recommended but 2 targets never. then sometimes 4 targets it is aoe rotation and then its single target rotation again...

If blizzard did this on purpose then it's broken the addon and I wont be able to play druid with any sanity anymore and will go back to FFXIV...

**Comment by guifaro** [comment]
> I am aware of the changes with the range thing, and I'm not sure if my snapshot is correct, but thought I would post for Frost mage As cone of cold is not being recommended for AOE cheers https://pastebin.com/Kx8XjCkd

Cone of cold and frost nova are with range detection issue

**Comment by Hekili** [comment]
@AdamChattaway You're in a great position to report the specific details, but "100% buggered" doesn't actually clarify or help resolve issues.  There are (or were, last I looked) builds that will use Primal Wrath in single-target, so I'd need to look at a snapshot.  But right now, I'm finalizing range check related fixes.  Cat will be updated to use melee range with a recommendation to include other damaged/dotted targets for a short time.  It'll be fine.

**Comment by AdamChattaway** [comment]
> @AdamChattaway You're in a great position to report the specific details, but "100% buggered" doesn't actually clarify or help resolve issues. There are (or were, last I looked) builds that will use Primal Wrath in single-target, so I'd need to look at a snapshot. But right now, I'm finalizing range check related fixes. Cat will be updated to use melee range with a recommendation to include other damaged/dotted targets for a short time. It'll be fine.

I linked you a video showing it, and before x update I never once used primal wrath on ST and dont have the talent.

https://www.youtube.com/watch?v=E2LUzsrOvZI&ab_channel=Gisborne

My next ability is on the right, so right to left.

**Comment by Hekili** [comment]
I hate videos, tbh.  But that one is clearly set to 1 target.  Did you provide a snapshot (linked on pastebin so it remains readable).  That's the key to clearing that up for you.

**Comment by AdamChattaway** [comment]
> I hate videos, tbh. But that one is clearly set to 1 target. Did you provide a snapshot (linked on pastebin so it remains readable). That's the key to clearing that up for you.

https://pastebin.com/jxtcXa7T

**Comment by Hekili** [comment]
> > I hate videos, tbh. But that one is clearly set to 1 target. Did you provide a snapshot (linked on pastebin so it remains readable). That's the key to clearing that up for you.
> 
> https://pastebin.com/jxtcXa7T

I think you have accidentally edited the priority; your first entry in the Feral - default action list is set to Primal Wrath.  It should be Skull Bash.

![image](https://github.com/Hekili/hekili/assets/9438134/b7343d35-ee23-44ef-862f-298536a881cd)

**Comment by AdamChattaway** [comment]
> > > I hate videos, tbh. But that one is clearly set to 1 target. Did you provide a snapshot (linked on pastebin so it remains readable). That's the key to clearing that up for you.
> > 
> > 
> > https://pastebin.com/jxtcXa7T
> 
> I think you have accidentally edited the priority; your first entry in the Feral - default action list is set to Primal Wrath. It should be Skull Bash.
> 
> ![image](https://user-images.githubusercontent.com/9438134/284011494-b7343d35-ee23-44ef-862f-298536a881cd.png)

![image](https://github.com/Hekili/hekili/assets/151282896/2971cc6d-93da-4c82-8a99-0ba4cdc3b384)

I deleted sav variables and reinstalled 3 times and changed nothing? I've never edited anything other than to stop a CD showing on non boss fights.

**Comment by Hekili** [comment]
It usually happens when someone is checking out settings and accidentally use the scroll wheel over a dropdown or something.  IDK.

**Comment by AdamChattaway** [comment]
> It usually happens when someone is checking out settings and accidentally use the scroll wheel over a dropdown or something. IDK.

And it persisted though 3 reinstalls and saved variables wipes lol.

**Comment by PavelBezpalov** [comment]
I fixed check_explosion_range setting on Arcane Mage by updating [LibRangeCheck-2.0](https://www.wowace.com/projects/librangecheck-2-0) to latest version v5.0.4.
Also i change less to less or equal.
`        usable = function () return not settings.check_explosion_range or target.distance <= 10, "target out of range" end,`

**Comment by Peet207** [comment]
ok as Fury, when i enter combat with 3 targets the addon still thinks there are 3 targets after i killed 2 and still recommand using Whirlwind. but if i enter combat with only 1 target and i pull 2 more the addon still thinks i only have 1 target and does not recommand Whirlwind. can someone check this pls? at least it is what i found out so far why Whirlwind is so fucked up right now with Fury rotation

**Comment by Peet207** [comment]
> ok as Fury, when i enter combat with 3 targets the addon still thinks there are 3 targets after i killed 2 and still recommand using Whirlwind. but if i enter combat with only 1 target and i pull 2 more the addon still thinks i only have 1 target and does not recommand Whirlwind. can someone check this pls? at least it is what i found out so far why Whirlwind is so fucked up right now with Fury rotation

so i think i found the problem/solution for me:
- make sure the "Check Whirlwind Range" is active when under the Core settings in Fury
- then go to Targeting and make sure the "Use Nameplate Detection" is OFF
- and make sure the "Detect Damaged Enemies" is ON

idk why but as soon as i turn the Nameplate Detection on, the addon will recommand me using Whirlwind no matter how far the enemy is. even if its way out of range and i cant hit them both. seems like there might be the problem.
you can test if you go to the dummies in Valdrakken. go the right side to the dungeon and raid dummy. stand in melee with the dungeon dummy while looking to the raid dummy. as soon as you hit the dungeon dummy it will recommand you using the aoe rotaion even though the raid dummy is way way out of range just because it "sees" the nameplate of a possible enemy

**Comment by PavloBezpalov** [comment]
Hekili version v10.2.0-1.0.4
Arcane explosion is not suggested in Mage Arcane rotation.

**Comment by LeighMetz** [comment]
Hekili version v10.2.0-1.0.4
Using nameplate detection, divine storm is never recommended, it just suggests templars verdict.

**Comment by karpana** [comment]
> Hekili version v10.2.0-1.0.4 For ret using nameplate detection, divine storm is never recommended, it just suggests templars verdict.

I would suggest double checking your other options (including ensure name plates are showing)
I switched myself to name plate detection, and Divine Storm is being correctly recommended.

**Comment by Sunzor** [comment]
> @AdamChattaway You're in a great position to report the specific details, but "100% buggered" doesn't actually clarify or help resolve issues. There are (or were, last I looked) builds that will use Primal Wrath in single-target, so I'd need to look at a snapshot. But right now, I'm finalizing range check related fixes. Cat will be updated to use melee range with a recommendation to include other damaged/dotted targets for a short time. It'll be fine.

Feral here: Did the changes as in the issue resolution screenshot and no issues whatsoever, good rule of the thumb is to probably refresh the rotation db. Yes it will sometimes recommend Wrath on ST, but if you use Hekili as a helper and not as a go-to-blind-following then you're good to go.

**Comment by Eco40** [comment]
Posted the issue but perhaps this is the right place to do it.
Shiv is not recommended for Rogues to remove enrage effect from the target like it used to: [https://github.com/Hekili/hekili/issues/2991](https://github.com/Hekili/hekili/issues/2991)

**Comment by b14554124** [comment]
I discovered remote employment, which cannot be identified by nameplates. I suspect it might be due to an issue with this section of code on line 368 in Targets.Lua. Perhaps it should be: local checkPlates = not filterPlates and showNPs and spec and spec.nameplates and spec.rangeChecker?

**Comment by b14554124** [comment]
Choose Frost specialization for the Mage class, select the use of nameplate recognition, confirm that all nameplates are enabled, select the skills used for identification, unable to correctly identify nameplates on the screen

**Comment by iamtabo** [comment]
Gnome, Prot Warrior.  Once I am in melee range, the rotation stops advancing.  If I back up beyond melee range, rotation starts cycling again.  Doesn't seem to have any problems with fury or arms.  Doesn't seem to happen with my DH (both specs) or rogue (combat).  Just prot warrior. 

I have bug sack and bug grabber installed. They captured no lua errors. 

https://pastebin.com/VgkAnMxY

edit:  redid the snapshot because I had a 2h equipped.  Doh.

**Comment by Jurandes** [comment]
I think still something is wrong with APL/range check for enh shammy. When there are more than 5 targets, still priority for EB/LB instead of chain lighting, which is not being shown in any situation - got a feeling like Chain Lightning is kind of cut out of the APL

All options like on pinned screen are on.

**Comment by Hekili** [comment]
> I think still something is wrong with APL/range check for enh shammy. When there are more than 5 targets, still priority for EB/LB instead of chain lighting, which is not being shown in any situation - got a feeling like Chain Lightning is kind of cut out of the APL
> 
> All options like on pinned screen are on.

You'd need to supply a snapshot for investigation (it can be a new ticket), but I suspect that you have AOE Funnel Priority enabled which means you're trying to burn a single-target in AOE scenarios.  If  you uncheck AOE Funnel Priority, you'll probably see more Chain Lightning.

![image](https://github.com/Hekili/hekili/assets/9438134/d7a94a6b-8802-495b-a593-776e464d30aa)
