### ISSUE TITLE
[REC] Enhancement Shaman Multi-target priority not registering in combat

### ISSUE THREAD

**Issue by nodillman** [Hekili/hekili#2942]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Enhancement shaman - When on auto - it does not appear to be acknowledging when multiple targets are present and recommends single target priorities (no crash lightning, lightning bolt or elemental blast over chain lightning).  When in dual mode, or AOE mode the indicator in the lower corner that tracks number of targets starts with the correct number, however once in combat the value changes to 2.

![image](https://github.com/Hekili/hekili/assets/80108869/bd2cf682-ef96-47ca-a26e-d0a2bc5062d7)
![image](https://github.com/Hekili/hekili/assets/80108869/e8731e8a-37d8-4d3b-9c3b-f747a4d5fc2e)
![image](https://github.com/Hekili/hekili/assets/80108869/2834778d-bb12-4774-a511-1fcdd8355b0d)

### How to Reproduce

1. Log onto enhancement shaman
2. Enable AUTO, dual, or AOE modes on Hekili
3. Approach pack of AOE mobs
4. Attack mobs

### Snapshot (Link)

https://pastebin.com/pyZhVTq4

**Comment by Deggers007** [comment]
Same for me when playing ench shaman . Hekili not recognizing multi target rotation

**Comment by nicouni87** [comment]
it's bugged for me. also in single target he suggest flame shock instead of other abilities

**Comment by rafacbart** [comment]
Same for me!! I've spend 1 hour to find a way to correct this inside hekili's options, but it was useless :(

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/2941
