### ISSUE TITLE
[REC] Assarogue recommendations for AOE/Multitarget on Automode / targetcount missing

### ISSUE THREAD

**Issue by alonewicked** [Hekili/hekili#2943]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili will not give me recommendations for AOE/Multitarget ( Fan of Knives , Crimson tempest). it will only show recommendations for Singletarget.

### How to Reproduce

Enter Game as Assasinationn Rogue
go in an addgroup 3+
targetcount wont show up

### Snapshot (Link)

https://pastebin.com/ZhrBWiwE

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/2941
