### ISSUE TITLE
Assassination Rogue AoE Priority Issues

### ISSUE THREAD

**Issue by Coachb21** [Hekili/hekili#2944]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Assassination Rogue, the addon is not making fan of knives a priority in AoE which in return allows the poisons to fall off targets. I believe that in AoE - more priority into Crimson Tempest and Fan of Knives is needed.

The addon rarely - if ever - recommends Crimson Tempest and/or Fan of Knives. It rather prio's Caustic Spatter - which is most likely prio if all dots are active. But after dots fall off - it does not prio keeping them up.

### How to Reproduce

1. Enter game as Assassination Rogue
2. Go attack 5 target's grouped and begin rotation. Rotation will prio single target rotation over AoE / Crimson Tempest / Fan of Knives

### Snapshot (Link)

Assassination; Primary - Mutilate(0.00), Thistle Tea(1.00), Rupture(1.00), Mutilate(2.00)

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rvzNCM2kLskXx8xricmPE1

### Contact Information

brad2122

**Comment by Coachb21** [comment]
Edit : Seeing the 2941 post now

**Comment by foutsnr** [comment]
I'm seeing the same type of thing for Retribution Paladin. It is prioritizing single target when it should be finding more then 3 targets and doing AOE as primary. This is only happening when you get into combat. Out of combat it looks to be correct.

**Comment by Coachb21** [comment]
> I'm seeing the same type of thing for Retribution Paladin. It is prioritizing single target when it should be finding more then 3 targets and doing AOE as primary

https://github.com/Hekili/hekili/issues/2941

Read this - big help

**Comment by leonardoochaves** [comment]
My Fury Warrior is the same. Actually even the menu settings i cant open. The addon seems like dont recognize adds nearby and sugest charge when im already in front from the add.

**Comment by foutsnr** [comment]
> > I'm seeing the same type of thing for Retribution Paladin. It is prioritizing single target when it should be finding more then 3 targets and doing AOE as primary
> 
> #2941
> 
> Read this - big help

Thanks this fixed my issue.
