### ISSUE TITLE
Addon not loading properly.

### ISSUE THREAD

**Issue by chrisp088** [Hekili/hekili#2945]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I'm a fury warrior and the Addon is not loading properly since newest update version 1.0.2wtf. Can left click the icon on map but cannot right click to open options. There is a total of 12 bugs that popped up. I noticed one of the errors would happen constantly. After stopping the addon wiping the bugs and restarting the addon i had only had 3 bugs. One for starting the addon, the second was the same one that went off 200 times before. and the third being stopping the addon. I will post the main bug in the pastebin. But if you do need the start and stop ones i can add those as well.

### How to Reproduce

joined game as my fury warrior after updating addon.

### Player Information (Link)

cannot gather info due to error

### Error Messages (Link)

https://pastebin.com/NzTauCv7

**Comment by senkuden** [comment]
Same Problem Here

**Comment by leonardoochaves** [comment]
Same here!!

**Comment by smashermanboy** [comment]
Same as well. Worked earlier today on my fury warrior now getting errors and wpnt show

**Comment by Hekili** [comment]
Did you download from GitHub?  If so, make sure to download the packaged addon, not the source code:

![image](https://github.com/Hekili/hekili/assets/9438134/1e4babfb-4cb7-4c21-86f2-01cd7696a846)

**Comment by leonardoochaves** [comment]
i download from CurseForge

**Comment by smashermanboy** [comment]
Already had it installed through curseforge. Been using it for awhile. Worked earlier today and then after update im getting the same error as the one listed above

**Comment by Hekili** [comment]
Redownload, reinstall, or download from CurseForge.  Or post more error messages, starting with the first.

**Comment by smashermanboy** [comment]
Already tried that and thanks for the response. The error above is the one were getting. Im not to familar with posting bugs so if anyone can post that would be awesome. I know the guy who created the post had posted one on pastebin that I was getting

**Comment by chrisp088** [comment]
first bug that happens when in a new session.
https://pastebin.com/m4LjzCJf

**Comment by leonardoochaves** [comment]
![image](https://github.com/Hekili/hekili/assets/88862660/9bc44eef-e2a3-4f94-bd08-df4be929fcf1)

I printed the messages of the addon BugSack. Sorry, idk how do I inform this and dont know what mean that messages.

**Comment by inmWill** [comment]
Something's gone sideways with the version on CurseForge.   The librangecheck version is incorrect (still 2.0) in files 
State.lua:,27
Events.lua:24 
Targets.loa:254.  
Change them to LibRangeCheck-3.0-ElvUI and the errors go away.

**Comment by senkuden** [comment]
The 3 others error are : Legendaries.lua , Core.lua  and UI.lua:2339  for the last errors doesn't stop count

**Comment by Hekili** [comment]
Download v10.2.0-1.0.2-wtf-a when available here:  https://github.com/Hekili/hekili/releases/latest

**Comment by senkuden** [comment]
It works thank's !

**Comment by lTof97** [comment]
it started to work normally now, thx
