### ISSUE TITLE
Survival hunter Harpoon and aoe priorities incorrect/not displaying

### ISSUE THREAD

**Issue by KindYettio** [Hekili/hekili#2946]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon recommends Harpoon during a fight in a 5 target cleave, im assuming it has something to do with Terms of engagement talent.  It also does not recommend Butchery at all in AOE nor wildfire bomb spam.  Survival Hunter..... Snapshot was taken with full charges of wildfire bomb and max charges of butchery.

### How to Reproduce

Enter as Survival hunter,
Take terms of engagement talent,
Take butchery talent,
Hit 3+ targets

### Snapshot (Link)

https://pastebin.com/kMuENjNq

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hXiKhmCSnbBRACyLP7WNnz

### Additional Information

https://www.raidbots.com/simbot/report/kAsGFBzwvNH3xWbxXBXtyR
https://www.raidbots.com/simbot/report/nGK2VHHHSZLi8CLAnd4fBJ

### Contact Information

Yettio#1369

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/2941
