### ISSUE TITLE
[BUG] Provide a short, clear title for your Bug Report

### ISSUE THREAD

**Issue by ThomasFinley96** [Hekili/hekili#2947]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On my fury warrior after installing the newest version of hekili ive had a couple of new issues. 
Firstly charge keeps trying to put itself in the rotation list no matter the range set. For example after i charge into a fight, randomly the charge icon throws itself into the rotation no matter the range and then removes itself.  
The second problem I'm having is whirlwind is no longer tracking whirlwind stacks(after using whirlwind the next 4 abilities cleave onto nearby enemies) , and wont show itself in the prio bar. I've change from auto, to aoe only, to reactive, no matter what whirlwind wont show. 

### How to Reproduce

Enter game
Go to training dummy area in valdrakan where the aoe dummies are
start rotation
whirlwind only shows up for first instance of the rotation and doesnt come back.
charge keeps popping up despite being too close to the target to use.

### Player Information (Link)

https://pastebin.com/ZvULYYgj

### Error Messages (Link)

No error messages

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/2941
