### ISSUE TITLE
Enhancement AOE Prio displayin CL over LB

### ISSUE THREAD

**Issue by ittsKC** [Hekili/hekili#2948]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Enhancement AOE prio is recommending chain lightning instead of lightning bolt

### How to Reproduce

5 dummies
PW
LL
Chain lightning showing instead of lightning bolt

### Snapshot (Link)

https://pastebin.com/ueY4n8PX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pF5vGdZeK5hXQ1WYpEGknX

### Contact Information

its_kc#0584

**Comment by Hekili** [comment]
It's buying you time to get a second Lava Lash spread before spending your next set of Maelstrom Weapon stacks on Lightning Bolt.  There are 8 targets and it's only seeing 3 Flame Shocked.

edit: Here's a screenshot of an 8 target sim that behaves similarly:

![image](https://github.com/Hekili/hekili/assets/9438134/c7bdf232-e44f-4339-b416-e434d48aba77)

**Comment by Hekili** [comment]
This should be less frequent with the next release; it's also an artifact of range check limitations that I've addressed better in the new release.
