### ISSUE TITLE
Enhancement Shaman Primordial Wave Issue

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#2949]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using Primordial Wave after spreading flameshock it should recommend Lightning Bolt instead it is recommending CL. 

### How to Reproduce

Enhancement Shaman
Val Dummies
Cast Wolves, PW, and then LL

### Snapshot (Link)

https://pastebin.com/LWpm3WQx

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ei7jrbycxhRq36WxUfCkRi

**Comment by dnlunso** [comment]
I can confirm this, if this helps in any way, here is my snapshot: https://pastebin.com/5ayjgn2S

**Comment by Hekili** [comment]
This should be less frequent with the next release; it's also an artifact of range check limitations that I've addressed better in the new release.
