### ISSUE TITLE
Trinkets aren't showing up

### ISSUE THREAD

**Issue by Craney101** [Hekili/hekili#295]
Hey so something happened and I lost all of my add on profiles (unrelated) but since then trinkets aren't appearing for Hekili add on was wondering how to fix it.
Thanks.

**Comment by Hekili** [comment]
Please fill out the ticket completely; thanks!

**Comment by Craney101** [comment]
By adding a screenshot?

**Comment by Hekili** [comment]
No, the instructions are there when you click "New Issue."
