### ISSUE TITLE
Warrior =>charge in front of target + dont recognize aoe situations

### ISSUE THREAD

**Issue by leonardoochaves** [Hekili/hekili#2950]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When I move a little bit Hekili recommend use charge, even im in front of target. Furthermore, addon dont recognize aoe situations.

### How to Reproduce

1. hitting aoe dummies and dont suggest whirlwind of other thing used aoe situations
2. move a little bit and you see addon recommend charge

### Snapshot (Link)

https://pastebin.com/KGwfbspV

### Raidbots Sim Report (Link)

.

### Additional Information

.

### Contact Information

leonardoochaves@gmail.com

**Comment by weslees22** [comment]
Was just about to post the exact same thing

**Comment by Hekili** [comment]
You have not downloaded the latest version of the addon.

**Comment by leonardoochaves** [comment]
I downloaded it from a link I got about an hour ago from you. Where should I get the most current version?

**Comment by Hekili** [comment]
Maybe you didn't paste the whole snapshot, then?

![image](https://github.com/Hekili/hekili/assets/9438134/88edb669-47ac-4d0c-9c7a-107e5bd72ec7)

**Comment by shayne56** [comment]
Hello, I've followed the steps indicated for disabling target detection. I have installed wtf-b
https://pastebin.com/FcU1JwbG
Short video of charge popping up when the character moves:
https://www.veed.io/view/9abddd22-8a99-4a08-ab54-bf5f5e054b97?sharingWidget=true&panel=
