### ISSUE TITLE
Fel Barrage recommendations

### ISSUE THREAD

**Issue by ROWZZ823** [Hekili/hekili#2952]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The new fel barrage is basically breath of sin, like frost dk.
So we need to only cast Fel Barrage when full Fury or like 60+ and spells following and setuping up Fel Barrage should be all resource builders and not spenders.
Perhaps we can make a custom option for Havoc where we choose what we want our fury to be before suggesting Fel Barrage along with certain perameters leading up to the cast. Like do I have Felblade, Immo Aura, Sigil of Flame off cd.

### How to Reproduce

Perhaps we can make a custom option for Havoc where we choose what we want our fury to be before suggesting Fel Barrage along with certain perameters leading up to the cast. Like do I have Felblade, Immo Aura, Sigil of Flame off cd.

### Snapshot (Link)

N/A

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3HXoUWqo5PkscXAfWv1Cex

### Contact Information

discord id: rowzz

**Comment by ROWZZ823** [comment]
thoughts?

**Comment by Hekili** [comment]
The sim is currently written to use spenders during Fel Barrage.  You'd need to provide an updated comparison sim that shows it is worth not using spenders to keep Fel Barrage rolling.  (It might be true.)  You can see that your sim used spenders immediately after Fel Barrage was triggered:

![image](https://github.com/Hekili/hekili/assets/9438134/a9be46ce-72fb-46f2-997d-3b26d21a7341)
