### ISSUE TITLE
[FEATURE] Option to make abilities not triggering a GCD invisible

### ISSUE THREAD

**Issue by KiloViktor** [Hekili/hekili#2953]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hey,
I wasn't able to figure out if this is somehow already possible in Hekilii (if it is let me know). According to my understanding disabling an ability also disables the calculations in the APL in the background.

A toggle option to hide (but still calculate) the display of an ability that doesn't trigger a GCD. 
Example: Symbols of Death as a Sub Rogue. The APL recommends usage on CD and it's not on GCD so I can macro it into abilities. I don't want it to show up in the actions recommended but rather show the next real GCD action after Symbols. So making it invisible in the display to me.

This would enable CD macros including trinkets and other stuff but only show me one icon instead of many.

Thanks a lot.

**Comment by Hekili** [comment]
You can disable abilities you don't want to see recommended in /hekili > Abilities.

**Comment by KiloViktor** [comment]
thanks for clarifying. Read your ingame tooltip on disabling abilities and it stated that the APL would maybe recommend different stuff because conditions weren't met otherwise.
