### ISSUE TITLE
Spores of Alacrity trinket not listed in Arms warrior gear list.

### ISSUE THREAD

**Issue by YomamaNow** [Hekili/hekili#2954]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Merely needs that Sporres of Alacrity trinket be added to list and incorporated in Hekili's calculations.

### How to Reproduce

1. Enter game as Arms Warrior.
2. Use recommended order of abilities.
3. Notice that my equipped trinket of Spores of Alacrity is not being recommended.

### Player Information (Link)

https://pastebin.com/gDF0hxZ5

### Error Messages (Link)

None

### Additional Information

Just need the trinket Spores of Alacrity added into the Arms list so as to be included in Hekili's calculations.

### Contact Information

Armsparty#2721

**Comment by Hekili** [comment]
This should be resolved in the latest release.
