### ISSUE TITLE
 If you enter the simc profile of an enhanced shaman, AOE will not be visible.

### ISSUE THREAD

**Issue by lwr200** [Hekili/hekili#2955]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

If you enter the simc profile of an enhanced shaman, AOE will not be visible.
Single skill also does not advance to the next skill.

### How to Reproduce

1. Import the simc profile
2. game reload
3. Confirm that add on does not work properly.

### Player Information (Link)

https://pastebin.com/9p1kw1x5

### Error Messages (Link)

11

### Additional Information

11

### Contact Information

lwr200

**Comment by Hekili** [comment]
Don't do that.
