### ISSUE TITLE
[REC] buff.indiscriminate_carnage.up does not work

### ISSUE THREAD

**Issue by Delerp** [Hekili/hekili#2956]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Noticed while testing some stuff at a dummy that buff.indiscriminate_carnage.up is always false even though i have the buff starting the combat and 10 seconds after.

### How to Reproduce

1.Stealth up with indiscriminate carnage talent
2.start combat and pause soon after, check the snapshot and all lines with buff.indiscriminate_carnage.up return as false even though i have the buff.

### Snapshot (Link)

https://pastebin.com/G2Jhc0rY

### Additional Information

In the snapshot it shows up in buffs:
 385747 - *indiscriminate_carnage                  -   1 - 7.35  

but in line:
- this entry's criteria PASSES: stealthed.improved_garrote[true] & ( remains[0.00] < ( 12 - buff.sepsis_buff.remains[0.00] ) | pmultiplier[0.00] <= 1 | ( buff.indiscriminate_carnage.up[false] & active_dot.garrote[3.00] < spell_targets.fan_of_knives[5.00] ) ) & ( ! variable.single_target[false] | combo_points.deficit[3.00] >= 3 ) & target.time_to_die[300.00] - remains[0.00] > 2

buff.indiscriminate_carnage.up is reported as false, not sure what kind of issues this causes along the line.

Probably due to the rework of this talent in 10.2?

**Comment by Delerp** [comment]
Looks like this is caused by the spellid of indiscriminate carnage buff being changed in 10.2:
indiscriminate_carnage buff is now spellid 385754

this line has the old spellid in rogueassassination.lua:
    indiscriminate_carnage = {
        id = 381802,
        duration = 3600,
        max_stack = 1

But there is another buff applied when you break stealth, buffid 385747 activates for 10 seconds after breaking stealth

Edit:
possible fix?
    indiscriminate_carnage = {
        id = 385754,
        duration = 3600,
        max_stack = 1,
	copy = 385747

**Comment by Hekili** [comment]
That's part of the fix; I actually thought I'd already committed a fix.  Will review again.  Thanks.
