### ISSUE TITLE
[BUG] Hekili tried to call the protected function coroutine.resume() UI.lua:2319

### ISSUE THREAD

**Issue by Draugor** [Hekili/hekili#2957]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

everything with the rotation works normally (or at least as far as i can tell) but in fight BugSack picks up multiple instances of a lua-error
it gets worse the more enemies are around me (and the fps tanks at that point) also if i have my other addons active weakaura gets the blame, but i get that error even with only BugGrabber, BugSack and Hekili active

that started happening after i updated to [v10.2.0-1.0.1f](https://github.com/Hekili/hekili/releases/tag/v10.2.0-1.0.1f) (yes i am currently on 1.0.2wtf-b) though i'm not exactly sure what i had before that 

edit: still happening with 1.0.3

### How to Reproduce

1. play as shaman or DH (? at least those two i tested) 
2. fly anywhere
3. pull some mobs
4. fight
5. ...
6. errors

i know not exactly helpful to reproduce but it happens for me all the time so not sure if there is something i'm especially doing wrong maybe because i have CD's display disabled ? 

### Player Information (Link)

https://pastebin.com/Ky5EKMUV

### Error Messages (Link)

https://pastebin.com/SMMwfjPe

**Comment by b14554124** [comment]
I'm not sure if it's because of LibRange 2.0, but when I tried using 3.0, the issue disappeared.

**Comment by Draugor** [comment]
installing LibRange 3.0 extra didn't fix it for me sadly

**Comment by RogerRabbit10** [comment]
I just got this bug

5x [ADDON_ACTION_BLOCKED] AddOn 'Hekili' tried to call the protected function 'resume()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `resume'
[string "@Hekili/UI.lua"]:2319: in function <Hekili/UI.lua:2254>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Hekili** [comment]
Should be resolved with next release.
