### ISSUE TITLE
Trinkets aren't appearing

### ISSUE THREAD

**Issue by Craney101** [Hekili/hekili#296]
Hey so something happened and I lost all of my add on profiles (unrelated) but since then trinkets aren't appearing for Hekili add on was wondering how to fix it.
Thanks.

build: v8.3.0-04-14
level: 120 (120)
class: MAGE
spec: fire

talents: flame_on
    flame_patch
    frenetic_speed
    meteor
    rune_of_power
    searing_touch
    shimmer

azerite: azerite_empowered = 3
    blaster_master = 3
    cauterizing_blink = 1
    firemind = 1
    gutripper = 2
    overwhelming_power = 1
    resounding_protection = 2
    wildfire = 1

essences: [memory_of_lucid_dreams] = 3, breath_of_the_dying = 1, conflict_and_strife = 2, purification_protocol = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    balefire_branch = 1
    corporeal_supplicants_trousers = 1
    cowl_of_unspeakable_horrors = 1
    forbidden_obsidian_claw = 1
    gnomeregan_tabard = 1
    heart_of_azeroth = 1
    hyperthread_wristwraps = 1
    ichorspine_loop = 1
    manainfused_sash = 1
    pauldrons_of_vile_corruption = 1
    robes_of_unreality = 1
    seal_of_questionable_loyalties = 1
    shandai_watcher_of_cosmos = 1
    supplicants_soiled_slippers = 1
    unsettling_seaweave_gloves = 1

corruptions: twilight_devastation = 3

itemIDs: 158075, 158314, 159267, 159630, 168989, 169049, 169223, 170456, 172228, 173944, 174116, 174119, 174124, 174127, 174532, 45578

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    pyroblast_pull = false
    reserve_runes = 1

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false
![WoWScrnShot_030820_121758](https://user-images.githubusercontent.com/61924564/76155470-051beb00-6138-11ea-900b-4389cf090c52.jpg)

**Comment by Hekili** [comment]
Trinkets are generally assigned to your cooldowns toggle, which is turned off.

See /hekili > Toggles > Cooldowns.  Generally a good idea to set/use a keybind to turn them on/off.

**Comment by Craney101** [comment]
I didn't realise it was turned off thanks heaps all fixed. Great work and sorry about before :)

**Comment by Hekili** [comment]
No worries; I just can't see what's going on without the requested info.  Enjoy!
