### ISSUE TITLE
[BUG] Windwalker Monk has no default priorities and never updates any after reinstall or deletion of other priorities

### ISSUE THREAD

**Issue by DevChaseGee** [Hekili/hekili#2960]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

No priorities for windwalker monk. Addon is not useable for the class right now.

![image](https://github.com/Hekili/hekili/assets/78337096/fb1da109-043a-414a-9cbe-6957b1347adc)
![image](https://github.com/Hekili/hekili/assets/78337096/2377af52-4f26-4dae-950e-cf4282931eae)

### How to Reproduce

1. Enter game as Monk
2. Type /hekili
3. Look at priorities notice there is none for ww monk

### Player Information (Link)

https://pastebin.com/L9eD3ssU

### Error Messages (Link)

https://pastebin.com/L9eD3ssU

**Comment by Hekili** [comment]
This should be resolved in v10.2.0-1.0.3.
