### ISSUE TITLE
Recommendation does not change to AOE in AOE situations

### ISSUE THREAD

**Issue by Advoden** [Hekili/hekili#2962]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When I am doing dungeons the addon always recommends the single target priority rather than the AOE when I am fighting packs

### How to Reproduce

Enter game as feral druid
pull 4-6 mobs
recommendation does not change to AOE

### Snapshot (Link)

https://pastebin.com/QuejsdsJ

### Contact Information

Discord: advoden

**Comment by AdamChattaway** [comment]
It doesn't work at all for me, I just did boss dummy test and it kept recommending nothing but primal wrath on ST non stop. On AOE it recommends ST skills etc, It's 100 borked...

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/2941
