### ISSUE TITLE
Recommendation returns N/A while charging Augmentation evoker empowered spells

### ISSUE THREAD

**Issue by ghawksen** [Hekili/hekili#2963]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When casting an empowered spell as an augmentation evoker, the display becomes blank (returns N/A) until the cast is complete or canceled.

### How to Reproduce

1. Enter game as Augmentation Evoker
2. Cast Firebreath or Upheval
3. Recommendation returns N/A and is blank

### Snapshot (Link)

https://pastebin.com/af0LH43G

**Comment by Hekili** [comment]
This should be addressed in next release.
