### ISSUE TITLE
[REC] Enhancement not showing the AoE rotation at all.

### ISSUE THREAD

**Issue by aza-kali** [Hekili/hekili#2965]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It is showing me the AoE recommendation, and then upon entering combat it changes back into the single target rotation. I was also noticing the same issue on my feral druid.

### How to Reproduce

1. Enter game as Enhancement Shaman
2. Walk up to dummies and watch the priority change to the AoE rotation.
3. Start combat, priorities change to single target rotation.

### Snapshot (Link)

Not a "wrong" recommendation, just simply the entire rotation.

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dfXZkohemPoJt6NpBeKE3Z

### Contact Information

Discord: aza.kali

**Comment by Hekili** [comment]
Snapshot is still required; every concern related to target detection and priorities belong in https://github.com/Hekili/hekili/issues/2941.
