### ISSUE TITLE
[REC] Druid is 100% Broken and Unplayable with Hekili. 

### ISSUE THREAD

**Issue by AdamChattaway** [Hekili/hekili#2966]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

ST and AOE are not recommended properly, for example on boss dummy it was recommending me primal wrath non stop over and over at 1-2 combo points. On AOE it will either spam FB or ST rip. I don't know how else to describe it, but its completely utterly broken and made the class unplayable for me. I'll add video for example. 

PS: I've deleted saved var and even reinstalled but it's still the same.

https://www.youtube.com/watch?v=E2LUzsrOvZI

### How to Reproduce

Just use Hekili as Feral Druid etc

### Snapshot (Link)

Feral; Primary - Primal Wrath(0.00), Primal Wrath(1.00), Primal Wrath(2.00) build: v10.2.0-1.0.3 level: 70 (70) class: DRUID spec: feral  talents: BcGAORarfDaLt4uMx8TYOtl8GAAAAAAACJt0kgkkkUS5AokkkIJAAAAAAaAkIBAkkkkIJSLBkAAAAAAgEAAA     apex_predators_craving = 1/1     astral_influence = 2/2     berserk = 1/1     berserk_frenzy = 1/1     berserk_heart_of_the_lion = 1/1     brutal_slash = 1/1     carnivorous_instinct = 1/2     circle_of_life_and_death = 1/1     dire_fixation = 1/1     dreadful_bleeding = 1/1     feline_swiftness = 2/2     feral_frenzy = 1/1     frantic_momentum = 2/2     hibernate = 1/1     improved_stampeding_roar = 1/1     improved_swipe = 1/1     incarnation = 1/1     incarnation_avatar_of_ashamane = 1/1     infected_wounds = 1/1     ironfur = 1/1     killer_instinct = 2/2     lions_strength = 1/1     lycaras_teachings = 3/3     matted_fur = 1/1     mighty_bash = 1/1     moment_of_clarity = 1/1     moonkin_form = 1/1     omen_of_clarity = 1/1     pouncing_strikes = 1/1     predator = 1/1     predatory_swiftness = 1/1     primal_fury = 1/1     primal_wrath = 1/1     protector_of_the_pack = 1/1     raging_fury = 1/1     rake = 1/1     renewal = 1/1     rip = 1/1     rip_and_tear = 1/1     rising_light_falling_night = 1/1     sabertooth = 1/1     skull_bash = 1/1     soothe = 1/1     soul_of_the_forest = 1/1     stampeding_roar = 1/1     starfire = 1/1     sudden_ambush = 1/1     sunfire = 1/1     survival_instincts = 1/1     taste_for_blood = 1/1     tear_open_wounds = 1/1     thick_hide = 2/2     thrash = 1/1     tiger_dash = 1/1     tigers_fury = 1/1     wellhoned_instincts = 2/2  pvptalents: none  covenant: none  conduits: none  soulbinds: [dreamweaver]  sets: irideus_fragment = 1     tier30 = 4  gear: band_of_callous_dominance = 1     chestroots_of_the_autumn_blaze = 1     common_gray_shirt = 1     frigid_conservators_wrap = 1     handguards_of_the_autumn_blaze = 1     harlans_loaded_dice = 1     hooves_of_the_autumn_blaze = 1     irideus_fragment = 1     mantle_of_the_autumn_blaze = 1     pants_of_the_autumn_blaze = 1     red_sky_pendant = 1     salty_shellstudded_girdle = 1     scalebane_signet = 1     soulstarve_hood = 1     tier30 = 4     valdrakken_accord_tabard = 1     winter_foragers_branch = 1     wristbands_of_rousing_violence = 1  legendaries: none  itemIDs: 133368, 134440, 134458, 134528, 155881, 193743, 193768, 198732, 202513, 202514, 202516, 202517, 202518, 206182, 210382, 210385, 3428  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 3     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxTime = 20     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Feral     petbased = false     potion = spectral_agility     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     lazy_swipe = false     regrowth = false     rip_duration = 9     solo_prowl = false     use_funnel = false     vigil_damage = 50     zerk_biteweave = false  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = false      essences = false [overridden]     interrupts = true      mode = automatic      potions = true   keybinds:      barkskin              = MwU [05]     brutal_slash          = 3   [07], 3   [09]     entangling_roots      = CE  [06]     feral_frenzy          = 5   [07]     ferocious_bite        = C3  [06]     frenzied_regeneration = 5   [09]     growl                 = 0   [08], 7   [09]     healthstone           = F2  [05]     hibernate             = 2   [01], 7   [07]     ironfur               = 4   [09]     lunar_inspiration     = 2   [02]     mangle                = 1   [08], 1   [09]     mark_of_the_wild      = F3  [05]     mighty_bash           = C4  [06]     moonfire              = 2   [02]     moonfire_cat          = 2   [02]     primal_wrath          = C2  [06]     prowl                 = 0   [01], 0   [07], 0   [10], 0   [11]     rake                  = 2   [07]     regrowth              = 6   [02], CQ  [06]     renewal               = M3  [05]     rip                   = C1  [06]     shadowmeld            = -   [01], -   [07], -   [10]     shred                 = 1   [07]     skull_bash            = R   [06], 3   [08]     soothe                = CM4 [04]     stampeding_roar       = AE  [06]     survival_instincts    = MwD [05]     swiftmend             = 7   [02]     thrash                = 4   [07], 4   [08], 2   [09]     thrash_bear           = 4   [07], 4   [08], 2   [09]     thrash_cat            = 4   [07], 4   [08], 2   [09]     tiger_dash            = AQ  [06]     tigers_fury           = M4  [04]     typhoon               = 6   [07]     ursols_vortex         = 3   [02]     wrath                 = 1   [02]  warnings: none   targets:  Nameplates are enabled.  - Checking nameplate1 [ Creature-0-1463-2444-10472-194643-000055E1F5 ] Dungeoneer's Training Dummy.     nameplate1   -  2 - Creature-0-1463-2444-10472-194643-000055E1F5 - 300.00 - 0 - Dungeoneer's Training Dummy    - Checking nameplate2 [ Creature-0-1463-2444-10472-189632-000055E1F5 ] Animated Duelist.     nameplate2   - -1 - Creature-0-1463-2444-10472-189632-000055E1F5 - 1014.00 - 10 - Animated Duelist    - Checking nameplate4 [ Creature-0-1463-2444-10472-198594-000155E1F5 ] Cleave Training Dummy.     nameplate4   -  2 - Creature-0-1463-2444-10472-198594-000155E1F5 - 300.00 - 0 - Cleave Training Dummy    - Checking nameplate3 [ Creature-0-1463-2444-10472-194648-000055E1F5 ] Training Dummy.     nameplate3   -  2 - Creature-0-1463-2444-10472-194648-000055E1F5 - 336.00 - 8 - Training Dummy    player_buffs:       768 - cat_form                                 -   1 - 3600.00      1126 - mark_of_the_wild                         -   1 - 3548.12      5217 - tigers_fury                              -   1 - 11.36     102543 - incarnation_avatar_of_ashamane           -   1 - 27.22     395336 - *protector_of_the_pack                   -   1 - 3600.00    186403 - *sign_of_battle                          -   1 - 3600.00    418563 - *wows_19th_anniversary                   -   1 - 3600.00    397734 - *word_of_a_worthy_ally                   -   1 - 3600.00    391876 - frantic_momentum                         -   1 - 1.47      383941 - crumbling_power                          -  18 - 17.22     252071 - jungle_stalker                           -   1 - 3600.00    135700 - clearcasting                             -   1 - 13.00   player_debuffs:  target_buffs:  target_debuffs:      1079 - rip                                      -   1 - 0.30      391356 - tear                                     -   1 - 1.97      391140 - frenzied_assault                         -   1 - 5.91     New Recommendations for [ Primary ] requested at 08:56:07 ( 9495.48 ); using built-in ( Feral ) priority. *** START OF NEW DISPLAY: Primary *** Swarm Info:    Damage - 0.00 remains, 0 stacks.    Dmg In Flight - 0.00 remains, 0 stacks.    Heal - 0.00 remains, 0 stacks.    Heal In Flight - 0.00 remains, 0 stacks.    Count Dmg: 0, Count Heal: 0.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: astral_power[ 0.00 / 100.00 ], combo_points[ 3.00 / 5.00 ], energy[ 100.00 / 100.00 ], mana[ 250000.00 / 250000.00 ], rage[ 0.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Feral - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   mark_of_the_wild ( precombat - 1 )         The action is not ready ( 3548.12 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Feral-precombat-1:mark_of_the_wild:0.02:Ability Known, Enabled(0.02)                  2.   algethar_puzzle_box ( precombat - 2 ) - IsUsableItem item 193701 and nil         Time spent on this action:  0.03ms         TimeData:Feral-precombat-2:algethar_puzzle_box:0.03:Ability Known, Enabled(0.03)                  3.   heart_of_the_wild ( precombat - 3 ) - talent [ heart_of_the_wild ] missing         Time spent on this action:  0.01ms         TimeData:Feral-precombat-3:heart_of_the_wild:0.01:Ability Known, Enabled(0.01)                  4.   prowl ( precombat - 4 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.03ms         TimeData:Feral-precombat-4:prowl:0.03:Ability Known, Enabled(0.03)                  5.   cat_form ( precombat - 5 )         The action (cat_form) is unusable at (0.00 + 0.00) because not usable in current form (cat_form).         Time spent on this action:  0.04ms         TimeData:Feral-precombat-5:cat_form:0.04:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Feral - precombat ].          Processing default action list [ Feral - default ].                  Current recommendation was NO ACTION at +10.00s.                  6.   primal_wrath ( default - 1 )         The action (primal_wrath) is usable at (0.00 + 0.00) with cost of 16 energy (have 100).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry has no criteria to test.         Action chosen:  primal_wrath at 0.00!         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Feral - default ].     Recommendation is primal_wrath at 0.00 + 0.00.     Recommendation #1 is primal_wrath at 0.00s (0.00s).  RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.00, Casting: 0.00 ).      Resources: astral_power[ 0.00 / 100.00 ], combo_points[ 0.00 / 5.00 ], energy[ 93.00 / 100.00 ], mana[ 250000.00 / 250000.00 ], rage[ 0.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Feral - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   mark_of_the_wild ( precombat - 1 )         The action is not ready ( 3548.12 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Feral-precombat-1:mark_of_the_wild:0.01:Ability Known, Enabled(0.01)                  2.   algethar_puzzle_box ( precombat - 2 ) - IsUsableItem item 193701 and nil         Time spent on this action:  0.02ms         TimeData:Feral-precombat-2:algethar_puzzle_box:0.02:Ability Known, Enabled(0.02)                  3.   heart_of_the_wild ( precombat - 3 ) - talent [ heart_of_the_wild ] missing         Time spent on this action:  0.01ms         TimeData:Feral-precombat-3:heart_of_the_wild:0.01:Ability Known, Enabled(0.01)                  4.   prowl ( precombat - 4 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.03ms         TimeData:Feral-precombat-4:prowl:0.03:Ability Known, Enabled(0.03)                  5.   cat_form ( precombat - 5 )         The action (cat_form) is unusable at (0.00 + 1.00) because not usable in current form (cat_form).         Time spent on this action:  0.03ms         TimeData:Feral-precombat-5:cat_form:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01):Post Cycle(0.00):Post Usable(0.00)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Feral - precombat ].          Processing default action list [ Feral - default ].                  Current recommendation was NO ACTION at +10.00s.                  6.   primal_wrath ( default - 1 )         The action (primal_wrath) is usable at (0.00 + 1.00) with cost of 16 energy (have 100).          - the action is ready before the current recommendation (at +1.00 vs. +10.00).          - this entry has no criteria to test.         Action chosen:  primal_wrath at 1.00!         Time spent on this action:  0.06ms         TimeData:Feral-default-1:primal_wrath:0.06:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)         The recommended action (primal_wrath) is ready within the active GCD; exiting list (default).         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Feral - default ].     Recommendation is primal_wrath at 0.00 + 1.00.     Recommendation #2 is primal_wrath at 1.00s (1.00s).  RECOMMENDATION #3 ( Offset: 1.00, GCD: 1.00, Casting: 0.00 ).      Resources: astral_power[ 0.00 / 100.00 ], combo_points[ 0.00 / 5.00 ], energy[ 87.00 / 100.00 ], mana[ 250000.00 / 250000.00 ], rage[ 0.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Feral - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   mark_of_the_wild ( precombat - 1 )         The action is not ready ( 3547.12 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Feral-precombat-1:mark_of_the_wild:0.01:Ability Known, Enabled(0.01)                  2.   algethar_puzzle_box ( precombat - 2 ) - IsUsableItem item 193701 and nil         Time spent on this action:  0.02ms         TimeData:Feral-precombat-2:algethar_puzzle_box:0.02:Ability Known, Enabled(0.02)                  3.   heart_of_the_wild ( precombat - 3 ) - talent [ heart_of_the_wild ] missing         Time spent on this action:  0.01ms         TimeData:Feral-precombat-3:heart_of_the_wild:0.01:Ability Known, Enabled(0.01)                  4.   prowl ( precombat - 4 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.03ms         TimeData:Feral-precombat-4:prowl:0.03:Ability Known, Enabled(0.03)                  5.   cat_form ( precombat - 5 )         The action (cat_form) is unusable at (1.00 + 1.00) because not usable in current form (cat_form).         Time spent on this action:  0.03ms         TimeData:Feral-precombat-5:cat_form:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01):Post Cycle(0.00):Post Usable(0.00)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Feral - precombat ].          Processing default action list [ Feral - default ].                  Current recommendation was NO ACTION at +10.00s.                  6.   primal_wrath ( default - 1 )         The action (primal_wrath) is usable at (1.00 + 1.00) with cost of 16 energy (have 100).          - the action is ready before the current recommendation (at +1.00 vs. +10.00).          - this entry has no criteria to test.         Action chosen:  primal_wrath at 1.00!         Time spent on this action:  0.06ms         TimeData:Feral-default-1:primal_wrath:0.06:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)         The recommended action (primal_wrath) is ready within the active GCD; exiting list (default).         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Feral - default ].     Recommendation is primal_wrath at 1.00 + 1.00.     Recommendation #3 is primal_wrath at 1.00s (2.00s).     Time spent generating recommendations:  1.79ms

### Contact Information

Discord User: gisborne

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/2941

**Comment by AdamChattaway** [comment]
> #2941

the range shows 1 in range though? not multiple so why would it do AOE when it detects only 1?

**Comment by AdamChattaway** [comment]
> #2941

Turned OFF nameplate detection on feral druid and it's still using primal wrath AOE on a Angle mob in the middle of nowhere with no other enemies around it... You closed my post saying druid is completely broken 100%, It is, it's 100% fked.
