### ISSUE TITLE
AOE for Arms and likely other Melee builds are facing fatal issues while in groups

### ISSUE THREAD

**Issue by YomamaNow** [Hekili/hekili#2967]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

This issue is not resolved with Hekili's last update. Perhaps this is due to a misunderstanding of the cause. There is no problem in single-player running straight off of reset profile. Hekili gives the best AOE recommendations immediately in this scenario. However, and yes due to whatever Blizzard did with their most recent and tragic hofix, once the player is in a group situation (dngeons, etc.), the entire Hekili system goes haywire, falling back to single target recommendations and only occasionally giving multi-target ones.

### How to Reproduce

1. Enter a game as Arms warrior.
2. Take on 5 dummies with Hekili (Blizzard's hotfix has no power here).
3. Play any dungeon (Hekili's interaction with Blizzard's hotfix begins once in a group).

### Player Information (Link)

Armsparty#2721

### Error Messages (Link)

None

### Additional Information

Blizzard may or may not get a lawsuit out of their last hotfix (developers have lots of flexibility when it comes to their games) and hopefully enough will complain to them to reverse it (other than those that are leaving and left, which so far was only 94), and I will too when I get the time for it (I brought back freehold, etc.), but Hekili and other developers should let Blizzard know this change is not prudent to the way their and others' addons work. Thanks.

### Contact Information

Armsparty#2721

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/issues/2941
