### ISSUE TITLE
[BUG] Retri Pala AOE not detecting enemies

### ISSUE THREAD

**Issue by Tensewicz** [Hekili/hekili#2968]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi,
2 days ago my AOE rotation stopped working, whenever I am changing to AOE manually it shows the enemies number in red as it is not detecting them at all. On Auto mode it always suggest single target

### How to Reproduce

1. Play as Retri Paladin
2. Attack multiple targets
3. Only Single target rotation is occuring even though attacking multiple targets
4. AOE mode is not detecting targets

### Snapshot (Link)

https://pastebin.com/D3Dk7XTc

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/oqqLZmbE27ScqikjBSseqt

**Comment by Amoqq** [comment]
Unholy DK  has the same problem. When I attack multiple targets, auto display mode suggest only single target rotation.
