### ISSUE TITLE
[REC] Outlaw no longer recommending Stealth precombat

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#2969]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Stealth not recommended as a precombat action.

### How to Reproduce

See above.

### Snapshot (Link)

https://pastebin.com/EgpbCmVk

**Comment by Hekili** [comment]
Fixed in next release.
