### ISSUE TITLE
Bestial Wrath on low lvl alt

### ISSUE THREAD

**Issue by quetzalsly** [Hekili/hekili#297]
For some reason the rotation refuses to ever use Bestial Wrath on my lvl 21 BM hunter. I have Show Cooldowns toggled in Toggles.

Is the addon even meant to be correct for low levels or is it tuned only for maximum dps on max level? I am trying to look for the code but having a hard time understanding what could be preventing Bestial Wrath from being used.

**Comment by Hekili** [comment]
The addon should provide a warning at low-levels that it's not designed to support the lowest levels.  Most priorities are written assuming that you have a talent selected in every row.
