### ISSUE TITLE
[BUG] Plz reopen #2528, changes on SpellFlash were made last week

### ISSUE THREAD

**Issue by Simul4kruM** [Hekili/hekili#2970]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Sorry for this new Issue, but I guess you would not have a look on postings in a closed issue...

Could you please reopen #2528 because your pull request was accepted last week but hekili still says SpellFlashCore isn't installed/enabled...

Thank you!

### How to Reproduce

1. Launch WOTLK with the latest wotlk hekili version
2. Click on a display and navigate to the spellflash tab
3. The setting is unavailable

### Player Information (Link)

https://pastebin.com/HbJwKxMP

### Error Messages (Link)

https://pastebin.com/HbJwKxMP

**Comment by Hekili** [comment]
Do not post tickets like this.  You can still comment on the closed ticket if there's anything to add.
