### ISSUE TITLE
I played Assassination rogue and now all the rotation remains single target when I am on Auto. All other classes are affected by this as well.

### ISSUE THREAD

**Issue by mandmanman** [Hekili/hekili#2972]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I tried assassination rogue today and after a short while of playing, I noticed that aoe spells are not popping up in my rotation when I am fighting a pack. I tested this out on my other classes as well and for some reason while I am on Auto, the rotation remains single target when I am supposed to do AOE damage. I tested this out on my other characters and I am experiencing the same issue with them.

### How to Reproduce

1. Problem persists even after reinstallation of the addon.
2. Scanned and repaired the game still have the same issue
3. Removed cached hekili as well and reinstalled the addon but problem persists

### Player Information (Link)

https://pastebin.com/ZLc0W2jw

### Error Messages (Link)

https://pastebin.com/KR5WWqck

### Contact Information

manu334#5613

**Comment by Pirlouitt** [comment]
Same problem on my end, I updated Hekili a few days ago and since then, auto is broken on every characters (even on lastest version). No AOE priority showing, only the single target priority regardless of numbers of targets. 
Tried everything, reseting settings, reinstalling, even tried reverting back to previous version: no luck.

**Comment by fzarr** [comment]
Blizz rolled out a last minute change that affects how target detection works, Check #2941 for potential temporary workarounds
