### ISSUE TITLE
[REC] DH - Immolation Aura not recommended

### ISSUE THREAD

**Issue by Naaw** [Hekili/hekili#2974]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Even tho there are 2 Stacks of Immolation Aura ready it doesn't recommend it. 
On top it's the "A Fire Inside" build.

I tried it several times and it seems to never recommend the first use of Immolation Aura.
When I still used it without being recommended it then shows up.

### How to Reproduce

1. Enter the Game as a Havoc
2. Use the right specc
3. Attack a Dummy
4. Make a Snapshot when there are 2 stacks of Immolation Aura

### Snapshot (Link)

https://pastebin.com/2geZqkK5

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/29uuzo1ACGf9tUAsDtWE9K

### Additional Information

https://www.raidbots.com/simbot/report/29uuzo1ACGf9tUAsDtWE9K

**Comment by Naaw** [comment]
It also doesn't recommend it when a fire inside procct and there's a new stack

**Comment by Naaw** [comment]
https://pastebin.com/vr5WLRW2  after a procc

**Comment by Hekili** [comment]
Please test with 1.0.4d or later and let me know if anything has improved.

**Comment by Naaw** [comment]
It improved a bit but it's not 100% fixed

here are 2 more Snapshots with inertia raid build:
https://pastebin.com/4sTQMiRL
https://pastebin.com/aQx2ZZV9

With a different build it seems to work way better (Ignition m+) 
https://pastebin.com/E3uJQFJ4

**Comment by Naaw** [comment]
Still a Problem.
It also recommends Fel Rush before Immolation Aura sometimes which makes no Sense.
