### ISSUE TITLE
Interface action failed becuase of an Addon

### ISSUE THREAD

**Issue by devlonc** [Hekili/hekili#2975]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Error in General Tab : Interface action failed becuase of an Addon.  When i check the addons it says 

### How to Reproduce

Anytime i relaod the UI it resets.  when i start a battle i get the error "Interface action failed becuase of an Addon" everytime

### Player Information (Link)

build: v10.2.0-1.0.3 level: 70 (70) class: WARRIOR spec: arms  talents: BcEAfuKaizEAgP2qANDB2hmf7DQRikEJkkoVKJBAAAAEEhoQCRREQCSSoIRIAhDECAAAAAAAAJaJiACRBB     anger_management = 1/1     armored_to_the_teeth = 2/2     avatar = 1/1     barbaric_training = 1/1     battle_stance = 1/1     battlelord = 1/1     blademasters_torment = 1/1     bladestorm = 1/1     blood_and_thunder = 1/1     bloodborne = 2/2     bloodletting = 1/1     colossus_smash = 1/1     cruel_strikes = 1/2     defensive_stance = 1/1     deft_experience = 2/2     die_by_the_sword = 1/1     double_time = 1/1     dreadnaught = 1/1     executioners_precision = 1/1     fast_footwork = 1/1     frothing_berserker = 1/1     fueled_by_violence = 1/1     furious_blows = 1/1     heroic_leap = 1/1     hurricane = 1/1     impale = 1/1     impending_victory = 1/1     improved_execute = 1/1     improved_overpower = 1/1     improved_sweeping_strikes = 1/1     in_for_the_kill = 1/1     leeching_strikes = 1/1     martial_prowess = 1/1     massacre = 1/1     mortal_strike = 1/1     overpower = 1/1     overwhelming_rage = 2/2     pain_and_gain = 1/1     rallying_cry = 1/1     reinforced_plates = 1/1     rend = 1/1     seismic_reverberation = 1/1     sharpened_blades = 1/1     sidearm = 1/1     spell_reflection = 1/1     storm_bolt = 1/1     storm_of_swords = 1/1     sudden_death = 1/1     tactician = 1/1     thunder_clap = 1/1     thunderous_roar = 1/1     thunderous_words = 1/1     twohanded_weapon_specialization = 1/1     uproar = 1/1     valor_in_victory = 1/1     war_machine = 1/1     warbreaker = 1/1     wild_strikes = 2/2  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: ruby_whelp_shell = 1  gear: anomuran_helm = 1     arctic_wardens_gauntlets = 1     arctic_wardens_greatsword = 1     chartreuse_champions_chestplate = 1     chartreuse_champions_girdle = 1     chartreuse_champions_legplates = 1     chartreuse_champions_sabatons = 1     crystalline_tenders_shroud = 1     dream_wardens_tabard = 1     harvest_guardian_pauldrons = 1     idol_of_trampling_hooves = 1     perennial_pompon_pendant = 1     rime_ridden_ring = 1     ruby_whelp_shell = 1     thornwoven_band = 1     thrashing_wind_vambraces = 1  legendaries: none  itemIDs: 133191, 162548, 193679, 193698, 193757, 209883, 209885, 209895, 209903, 209915, 210099, 210354, 210378, 210381, 210401, 210501  settings: aoe = 2     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxTime = 20     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Arms     petbased = false     potion = spectral_strength     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     heroic_charge = false     shockwave_interrupt = true  toggles: cooldowns = false      custom1 = false      custom2 = false      defensives = false      essences = true      interrupts = false      mode = automatic      potions = false   keybinds:      avatar            = 4   [01]     bladestorm        = 9   [05]     charge            = MwU [01]     cleave            = 6   [02]     execute           = 3   [01]     hamstring         = =   [01]     heroic_leap       = M3  [01]     heroic_throw      = =   [02]     impending_victory = -   [02]     mortal_strike     = 2   [01]     overpower         = 1   [01]     rend              = 6   [01]     slam              = 5   [01]     storm_bolt        = -   [01], SMwU[02]     sweeping_strikes  = M4  [02]     thunder_clap      = M5  [02]     thunderous_roar   = SM4 [02]     warbreaker        = SM5 [02]     whirlwind         = 8   [05]  warnings: none

### Error Messages (Link)

1x [ADDON_ACTION_BLOCKED] AddOn 'Hekili' tried to call the protected function 'resume()'. [string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481> [string "=[C]"]: in function `resume' [string "@Hekili/UI.lua"]:2319: in function <Hekili/UI.lua:2254>  Locals: _ = Frame {  RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487  0 = <userdata>  UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487  SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487 } event = "ADDON_ACTION_BLOCKED" events = <table> {  ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553  ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553  PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547  LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562  ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507 }

**Comment by devlonc** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'Hekili' tried to call the protected function 'resume()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:481: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/Hekili/UI.lua"]:2319: in function <Interface/AddOns/Hekili/UI.lua:2254>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:507

**Comment by Hekili** [comment]
This should be resolved in the next release.
