### ISSUE TITLE
Keybind not changing on Hekili after changing on actionbar

### ISSUE THREAD

**Issue by losccoy** [Hekili/hekili#2977]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Changed an ability action bar slot, however that change is not reflected in Hekili.

i have reset the profile
Reinstalled the add-on
nothing seems to work

### How to Reproduce

Use hekili, change keybind

![image](https://github.com/Hekili/hekili/assets/35572031/b24b9ba3-c91d-477f-b8ea-4755a5f9b2dd)

### Snapshot (Link)

Balance; Primary - Wrath(0.00), Wrath(1.41), Starfire(2.82)

**Comment by Hekili** [comment]
Keybinds are heavily dependent on how your bars and pages are set up.  If a keybind is detected incorrectly, you can update it manually in /hekili > Abilities.
