### ISSUE TITLE
[REC] Augmentation - Fire Breath Issues with latest APL from SimC

### ISSUE THREAD

**Issue by calvinwithac** [Hekili/hekili#2978]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Issue 1: With Augmentation, assuming the Leaping Flames and Scarlet Adaptation talents are taken, you cast FB at max empower to generate the additional leaping flames, which even in ST situations provides additional damage due to stored Scarlet Adaptation.

Related to this conversation in Discord: https://discord.com/channels/307520968895627264/307520968895627264/1175808872200540291

This was how the rotation behaved prior to the SimC import and is what the current SimC APL shows (though it doesn't check for talents).

The new APL checks your ebon might duration against an arbitrary "duration", which is set to 8/12/16/20 for rank 1/2/3/4 respectively. Since EM duration is 12~ seconds, and you FB immediately after EM in most cases, you are only ever recommended rank 1 or 2 FB. To cast a rank 4 FB, you would need a remaining EM duration of > 20.

I believe the intent is to check your EM duration against the _cast time_, to ensure EM will not drop before you finish casting. Changing duration to cast_time fixes this issue.

Issue 2: With Augmentation _only_, starting to cast fire breath will change the recommendation to empower rank 1 (or whatever is the last enabled recommendation in the action list that passes, e.g. disabling rank 1 will recommend rank 2 and so on). As seen in snapshot 2, the addon continues iterating through the selected action list even after finding a recommendation, instead of stopping at the first recommendation.

Functionality was different prior to the simc import, where it would continue recommending the appropriate rank depending on the current state, which is how devastation empower recommendations still work. 

I've attached four snapshots in the pastebin:

Snapshot 1 - Default unmodified APL (other than Breath of Eons being disabled), immediately after casting Ebon Might, when rank 4 FB should be recommended, but Rank 2 is instead 
Snapshot 2 - Default unmodified APL, immediately after starting to cast FB, showing the recommendation change from FB rank 2 to FB rank 1
Snapshot 3 - Modified APL changing "duration" to "cast_time", immediately after casting Ebon Might, rank 4 FB is recommended as intended
Snapshot 4 - Modified APL changing "duration" to "cast_time", immediately after starting to cast FB, showing the recommendation change from FB rank 4 to FB rank 1

Justification for upranking vs casting rank 1, because it's not obvious when you think about just FB, since FB itself does the same damage either way:
Aug discord FAQ: https://discord.com/channels/965456344360583188/1171479586601709588/1171479599809564732
Wowhead Guide: https://www.wowhead.com/guide/classes/evoker/augmentation/rotation-cooldowns-pve-dps#rotation-and-priority
IV Guide: https://www.icy-veins.com/wow/augmentation-evoker-pve-dps-rotation-cooldowns-abilities

### How to Reproduce

As Augmentation:

1. Follow recommendations until EM is cast
2. Observe recommended FB rank (will be either 1 or 2, depending on your mastery and how fast you press buttons)
3. Cast FB - if R2 was recommended, you'll see the recommendation change to R1

### Snapshot (Link)

https://pastebin.com/FwpyjsVC

### Raidbots Sim Report (Link)

Not supported.

### Contact Information

Discord: Terayen

**Comment by Hekili** [comment]
Thanks for the detail.  This should be resolved in the next release.
