### ISSUE TITLE
Beast Master Hunter target accuracy

### ISSUE THREAD

**Issue by Crelam** [Hekili/hekili#298]
Could we have an option for Beast Master hunters that bases number of targets by range to the pet.  The WA bellow has the code used as well as the conditions that need to happen for it to work.  I realize this might be a bit of work for a single spec, but I figured it wouldn't hurt to ask.

https://wago.io/Byos8GKBZ

Thank you for all that you do.

**Comment by Hekili** [comment]
I'll take a look.  If range from pet is a thing that actually works, then that would be good.  I could also make it only use those numbers for abilities centered on the pet and/or when you are attacking something your pet is hitting (i.e., for cases when your pet is attacking stuff on one side of the room but you're shooting something else that's not nearby).

**Comment by KevinMeinon** [comment]
Any ETA for this?

**Comment by Crelam** [comment]
> Any ETA for this?

If you are impatient for this kind of functionality, I made a Weakaura that kinda does this in a hacked together kind of way.

https://wago.io/FMk7q8_-L

**Comment by Hekili** [comment]
This is still on my list, FYI.  The delays are mostly because it doesn't fit well with my design priorities right now.  I'm looking at changing target handling altogether, and so I'd have to build this out and then probably rebuild it later if I push this out first.

I still might go that route.

**Comment by Hekili** [comment]
Hey, this happened.
