### ISSUE TITLE
Havoc demon hunter Fel Barrage issue

### ISSUE THREAD

**Issue by Sylvanas714** [Hekili/hekili#2980]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As Havoc demon hunter due to new functionaility of fel barrage and how its drains our fury and stops once our fury has been depleted , we need to be aware of what button we pressing while its channeling , we do not want waste our fury on chaose strike or annihilation while we have fel barrage going , we want to be above 60 fury when we start and do things to generate fury as best as we can for 8s like Vengeful Retreat multiple Immolation Aura felblade sigil of flame , however the addon recommaned throw glaive which cost 25 fury

### How to Reproduce

1. enter game as a Havoc demon hunter
2. take this build BEkAzqt9tQbK6xteCyjwasgfTKJJRSCSSiIBSCAAAAAAItQkEJJtkkWaBBEiSLJJRA
3. build +60 fury
4. cast fel barrage
5. see recommendations

### Snapshot (Link)

https://pastebin.com/XiDHeSTG

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/emFEEjguyjhr2eGqrxHUjj

**Comment by Hekili** [comment]
Update to the latest version and let me know if anything has improved.

**Comment by Sylvanas714** [comment]
> Update to the latest version and let me know if anything has improved.

suggested fel barrage when i had 40 fury then eye beam which cost fury

**Comment by fzarr** [comment]
Eye Beam w/ Blind Fury generates fury as well so it's not always wrong to cast EB after FB. Probably shouldn't be recommending it at 40 fury though.

**Comment by Sylvanas714** [comment]
> Eye Beam w/ Blind Fury generates fury as well so it's not always wrong to cast EB after FB. Probably shouldn't be recommending it at 40 fury though.

we're not getting Blind Fury with this build 
![image](https://github.com/Hekili/hekili/assets/62980306/6e4eef68-a177-4529-bce6-c74a6b0b0f99)

**Comment by Hekili** [comment]
Will need a snapshot with a more recent build to be able to investigate.  Take the snapshot when Fel Barrage is recommended plus immediately afterward, please.

**Comment by Sylvanas714** [comment]
> Will need a snapshot with a more recent build to be able to investigate. Take the snapshot when Fel Barrage is recommended plus immediately afterward, please.

when Fel Barrage Recommended
https://pastebin.com/Ti3tuLNP

afterward
https://pastebin.com/w8dK98Fi

**Comment by Hekili** [comment]
In those snapshots, you had 120 Fury, used Fel Barrage, then it recommended Fel Rush, Blade Dance, and Throw Glaive.  That sounds about right.  What should be different?
