### ISSUE TITLE
AtrocityUI WeakAura locks Hekili in place

### ISSUE THREAD

**Issue by CriticalFalcon** [Hekili/hekili#2981]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am trying to move my primary display to be in a specific location, and it is not clickable to drag around, and changing the x/y coordinates instantly snaps back to the same position.

### How to Reproduce

Not sure if it's reproducible, but this is just an issue I'm having.
![image](https://github.com/Hekili/hekili/assets/7663034/81a346d1-2071-4954-8333-ba0ab7ec0863)

### Player Information (Link)

https://pastebin.com/HZvQ2xM8

### Error Messages (Link)

no bugs

**Comment by Hekili** [comment]
Does this occur with your other addons disabled?

**Comment by CriticalFalcon** [comment]
> Does this occur with your other addons disabled?

I actually just tested with some addons disabled, and turns out when WeakAuras is enabled it gets caught up with it. Disabling the WAs addon lets me move it around, but setting it where I want and enabling WeakAuras again goes back to being in the broken position.

**Comment by CriticalFalcon** [comment]
So i actually found the issue. I'm using Atrocity UI and the latest update of the UI pack had a bug where one of the WAs had Hekili locked to a position controller to one of the internal WAs. Just had to remove it and it's all fixed, no issues on Hekili's side!

**Comment by jtiritil** [comment]
Would you mind sharing which WA it was and how you fixed it? Thanks!

**Comment by Breadwinka** [comment]
> Would you mind sharing which WA it was and how you fixed it? Thanks!

It's AUI player controller WA remove entry 5 then reload UI

**Comment by CriticalFalcon** [comment]
Steps for fixing:
1. `/wa` to open WeakAuras addon
2. Navigate/Search for "Position Controller" (should be under Essentials > Position Controller)
3. Under Custom Options tab > ElvUI Frame Positions, click the dropdown that says "Entry 1" and click on "Entry 5"
4. Click the red X to delete Entry 5
5. Then do a `/reload`

![image](https://github.com/Hekili/hekili/assets/7663034/1449195d-4649-441e-98cd-b0bded322e4b)

**Comment by Jubs85** [comment]
@Hekili You're a legend for reopening this. Thanks! My exact issue.

**Comment by CriticalFalcon** [comment]
**Update:** Atrocity UI has been updated to v9.2 where they have removed that entry that was accidentally added.
Downloading/updating the latest version of AUI will also resolve this issue if you don't want to deal with manual changes!
