### ISSUE TITLE
I'm unable to move the Primary bar -- can move all other bars, primary stuck in bad spot.

### ISSUE THREAD

**Issue by rpgreenb10** [Hekili/hekili#2982]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello, I am unable to move the primary bar and it's now being covered up by part of my weakauras. I've tried to unlock it and change the x and y axis under Hekili > primary > main. Please let me know what I can do to assist

### How to Reproduce

![image](https://github.com/Hekili/hekili/assets/105221253/dedd38c4-db4a-416e-910c-8cf803d2c2c8)

### Snapshot (Link)

![image](https://github.com/Hekili/hekili/assets/105221253/dedd38c4-db4a-416e-910c-8cf803d2c2c8)

### Contact Information

discord: orkatist

**Comment by Hekili** [comment]
See: https://github.com/Hekili/hekili/issues/2981
