### ISSUE TITLE
Unable to see primary or secondary bars

### ISSUE THREAD

**Issue by Zaxzoinger** [Hekili/hekili#2983]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have just recently updated my addon and after the update i can no longer see the primary or secondary bars. I have checked through all the settings and everything appears to be enabled. I checked on multiple characters and the issues persists.

### How to Reproduce

1. Enter game as any class or spec and the issue is there.

### Player Information (Link)

https://pastebin.com/qdVWvtX4

### Error Messages (Link)

no error messages

**Comment by Gomrund** [comment]
also seeing this

**Comment by vash-silver** [comment]
+1 also seeing this suddenly. 

I never realized how much I rely on this addon before today. :D

**Comment by Gomrund** [comment]
I mean I am a hunter so its not a big deal but I have also grown very used to it haha.

**Comment by mmkaaay** [comment]
+1 also

**Comment by markdall** [comment]
Confirmed, reverted to "a" (the previous version) fixed it.

**Comment by sburke45** [comment]
Also having this issue

**Comment by Gomrund** [comment]
Is there a way to revert the prior update on CF?

**Comment by mmkaaay** [comment]
> Is there a way to revert the prior update on CF?

view addon in CF click on versions and you should be able to install any version

**Comment by Gomrund** [comment]
Sweet! Thank you!

**Comment by Hekili** [comment]
This should already be resolved in 1.0.4c.  Sorry for the trouble.

**Comment by vash-silver** [comment]
> This should already be resolved in 1.0.4c. Sorry for the trouble.

Thanks for the quick fix!
