### ISSUE TITLE
[REC] Can't figure out how to enable Rend in Arms Warrior rotation

### ISSUE THREAD

**Issue by Kargalargus** [Hekili/hekili#2984]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Cannot see the spell Rend show up in single target rotation

### How to Reproduce

1. Enter game as Arms Warrior
2. Target enemy
3. See that Rend does not show up in single target or multi target rotation

### Snapshot (Link)

https://pastebin.com/T9S7vi6i

### Contact Information

Kargalargus

**Comment by Hekili** [comment]
Can you provide a sim of yourself for comparison?

The only entry for Rend in the single-target action list is at the very end (which is surprising), and only uses if Crushing Force is not talented and Rend is refreshable.

`actions.single_target+=/rend,if=!talent.crushing_force&remains<duration*0.3`

Also, you have Blood and Thunder talented, so Thunder Clap would proc Rend anyway.

https://www.icy-veins.com/wow/arms-warrior-pve-dps-rotation-cooldowns-abilities

**Comment by Kargalargus** [comment]
what do you mean by a sim?

**Comment by Hekili** [comment]
https://raidbots.com/
