### ISSUE TITLE
Cold snap is not being recommended correctly in aoe.

### ISSUE THREAD

**Issue by vladimars** [Hekili/hekili#2985]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Cone of cold should be recommened after using Comet storm, ideally with frozen orb on cd. However it seems to not be being recommened, when looking at the snapshot it seems to think no enemies were nearby, although i was on top of the dummies and have noticed this in mythic plus as well.

### How to Reproduce

Frostbolt into frozen orb, addon recommends blizzard (although cone of cold's condition list requires both frozen orb and comet storm to be the previous gcd's) then use comet storm, then addon recommends shifting power instead of cone of cold, which leads to another blizzard.

### Snapshot (Link)

https://pastebin.com/TLfSeudd

**Comment by Hekili** [comment]
Is this about CoC or Cold Snap?  The title and ticket don't agree.  Please add a sim as well.  Thanks!

**Comment by vladimars** [comment]
My bad, I think of them (coldest snap, and cone of cold) as the same thing. 
It's not recommending cone of cold correctly when talented into coldest snap is what I should of said. Sorry.

**Comment by Hekili** [comment]
I believe this is resolved, can you confirm?
