### ISSUE TITLE
Hekili conflict with WeakAuras addon.

### ISSUE THREAD

**Issue by Jubs85** [Hekili/hekili#2987]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Installed the Atrocity UI, and added Hekili at the end.
Seems the primary window of Hekili is snapped to my player frame, and keeps resetting to that position. It cant be dragged, only moved by the x/y position, and then it instantly snaps back to the player frame.
All other windows can be moved and customized in Hekili. Not the primary.
Disabled all addons, and there its working as intended. Narrowed it down to the second WeakAuras is enabled as the last addon, the primary window snaps back to the player frame position.
Cant find anything on what it could be, and i tried looking through the weakauras to find the condition that might be causing something like this.
![image_2023-11-20_173806164](https://github.com/Hekili/hekili/assets/151557467/79d7f7d5-97a5-4e53-85f9-bf1508a37984)

### How to Reproduce

Think the description above explains it properly. No idea if it can be reproduced elsewhere. Atm the only option is to disable it, and thats not really what im looking for.

### Player Information (Link)

https://pastebin.com/2132tXk8

### Error Messages (Link)

No ingame error

**Comment by Hekili** [comment]
No, AtrocityUI is trying to control Hekili -- there's a pinned ticket that talks about how to turn that off.
