### ISSUE TITLE
[REC] Havoc Fel Rush not recommended correctly

### ISSUE THREAD

**Issue by Naaw** [Hekili/hekili#2988]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

You want to go into your burst with Intertia activated. That means before you use any big CD you want to get Unbound Chaos by using Immolation Aura and there get the possibility to activate Inertia by using Fel Rush right before your CD's like Eybeam, Fel Barrage, Meta, ESSB etc.

### How to Reproduce

1. Enter the game as a Havoc
2. Use any of the viable damage speccs
3. Have everything ready
4. Use Immolation Aura
5. See recommendations

### Snapshot (Link)

https://pastebin.com/MtW8brQb

### Additional Information

Different Situation, same issue: https://pastebin.com/hMFaibzA

https://www.raidbots.com/simbot/report/8cMsvYoZmKRf1T3KAUZEoq
https://www.raidbots.com/simbot/report/piYTviAMY9zEa2Z1ajB9gv

**Comment by Naaw** [comment]
Still a Problem.

**Comment by Klarato** [comment]
Been noticing this as well - i think the SimC may be incorrect being the problem? Watching its use of inertia over a fight  during a sim on raidbots doesn't seem 100% correct?
