### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Esoterism** [Hekili/hekili#2990]

**Comment by SpatenLa** [comment]
The addon is mainly for use on max level.
but in your case, summon your pet. as a warlock you have a permanent pet. you didnt summon this pet. this pet is a permanent fel guard.

**Comment by Esoterism** [comment]
> The addon is mainly for use on max level. but in your case, summon your pet. as a warlock you have a permanent pet. you didnt summon this pet. this pet is a permanent fel guard.

huh bit peculiar that it even happend cause it was summoned before but it seem to have solved itself after i summoneafter i summoed another pet and then resummoned the felguard, ty for letting me know
