### ISSUE TITLE
Rogue - addon used to recommend Shiv to remove enrage. Seems that functionality has been lost.

### ISSUE THREAD

**Issue by Eco40** [Hekili/hekili#2991]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Rogue - addon used to recommend Shiv in the rotation to remove enrage buff when detected on hostile target.

I remember it working during previous season. Didn't change any of the addon's basic settings so I wonder if this could be brought back. As matter of fact it was an amazing feature. Appreciate your work!

### How to Reproduce

Any Rogue spec with Shiv talent.
Target any mob with an enrage effect.

### Snapshot (Link)

https://pastebin.com/LB6JLjrR

### Additional Information

build: v10.2.0-1.0.3
level: 70 (70)
class: ROGUE
spec: outlaw

talents: BQQAcWb37Z8KXj8LlE1rTPXfsBAAJQSESSIhEJJJpJJRJJSJJAAAAAAItWSCSSUIpkWAAAAIJA
    ace_up_your_sleeve = 1/1
    acrobatic_strikes = 1/1
    adrenaline_rush = 1/1
    airborne_irritant = 1/1
    alacrity = 2/2
    atrophic_poison = 1/1
    audacity = 1/1
    blind = 1/1
    cheat_death = 1/1
    cloak_of_shadows = 1/1
    combat_potency = 1/1
    combat_stamina = 1/1
    count_the_odds = 1/1
    crackshot = 1/1
    dancing_steel = 1/1
    deadened_nerves = 1/1
    deadly_precision = 1/1
    deeper_stratagem = 1/1
    deft_maneuvers = 1/1
    devious_stratagem = 1/1
    evasion = 1/1
    fan_the_hammer = 2/2
    fatal_flourish = 1/1
    featherfoot = 1/1
    fleet_footed = 1/1
    float_like_a_butterfly = 1/1
    graceful_guile = 1/1
    hidden_opportunity = 1/1
    hit_and_run = 1/1
    improved_adrenaline_rush = 1/1
    improved_ambush = 1/1
    improved_between_the_eyes = 1/1
    improved_sprint = 1/1
    iron_stomach = 1/1
    leeching_poison = 1/1
    loaded_dice = 1/1
    nightstalker = 2/2
    nimble_fingers = 1/1
    opportunity = 1/1
    precise_cuts = 1/1
    precision_shot = 1/1
    quick_draw = 1/1
    recuperator = 1/1
    retractable_hook = 1/1
    ruthlessness = 1/1
    shadow_dance = 1/1
    shadowrunner = 1/1
    shadowstep = 1/1
    shiv = 1/1
    sleight_of_hand = 1/1
    soothing_darkness = 1/1
    subterfuge = 1/1
    take_em_by_surprise = 2/2
    thiefs_versatility = 1/1
    tricks_of_the_trade = 1/1
    underhanded_upper_hand = 1/1
    vigor = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: [nadjia_the_mistblade]

sets: beacon_to_the_beyond = 1
    neltharions_call_to_suffering = 1
    tier30 = 4

gear: band_of_the_wyrm_matron = 1
    beacon_to_the_beyond = 1
    crystalline_tenders_belt = 1
    galakronds_voracious_hide = 1
    lifebound_bindings = 1
    lurking_specters_brigandine = 1
    lurking_specters_handgrips = 1
    lurking_specters_shoulderblades = 1
    lurking_specters_visage = 1
    neltharions_call_to_suffering = 1
    periwinkle_cloak = 1
    primal_molten_shortblade = 1
    seal_of_the_regal_loa = 1
    slimy_expulsion_boots = 1
    stylish_black_shirt = 1
    tier30 = 4
    understone_gorget = 1
    winter_foragers_chopper = 1

legendaries: none

itemIDs: 133180, 134491, 134524, 159458, 190505, 193419, 193451, 202495, 202497, 202498, 202500, 203963, 204211, 207820, 210371, 210397, 3427

settings: aoe = 3
    combatRefresh = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    enabled = true
    gcdSync = true
    maxTime = 20
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Outlaw
    petbased = false
    potion = phantom_fire
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    allow_shadowmeld = false
    ambush_anyway = false
    check_blade_rush_range = true
    mfd_points = 3
    no_rtb_in_dance_cto = true
    sinister_clash = -0.5
    solo_vanish = false
    use_ld_opener = true

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = false 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    adrenaline_rush      = R   [06]
    ambush               = M5  [06]
    beacon_to_the_beyond = SM4 [06]
    between_the_eyes     = 4   [01], 4   [07]
    blade_flurry         = M4  [06]
    blind                = `   [06]
    cheap_shot           = CS= [01], CS= [07]
    cloak_of_shadows     = A   [05]
    crimson_vial         = CSA [05]
    dispatch             = 3   [01], 3   [07]
    distract             = =   [01], =   [07]
    evasion              = CSD [05]
    feint                = M3  [05]
    grappling_hook       = D   [05]
    kick                 = CTAB[06]
    kidney_shot          = C=  [06]
    pistol_shot          = 2   [01], 2   [07]
    roll_the_bones       = CT  [06]
    shadow_dance         = MwD [05]
    shadowstep           = SM5 [06]
    shiv                 = CSTAB[06]
    sinister_strike      = 1   [01], 1   [07]
    slice_and_dice       = CST [06]
    sprint               = SMwU[06]
    tricks_of_the_trade  = SR  [05]
    vanish               = MwU [05]

warnings: none

**Comment by SUU09** [comment]
I'm having the same issue, Shiv will not be recommended if target is enraged

**Comment by Fighterisr** [comment]
same, i am an outlaw rogue and if the target is enraged it does not show shiv even though shiv is by default not set to a toggle like interrupts

**Comment by Hekili** [comment]
This has been restored.

**Comment by SUU09** [comment]
@Hekili  Same issue happening again as the below line is not included in TWW RogueOutlaw.simc

actions+=/shiv,if=debuff.dispellable_enrage.up
