### ISSUE TITLE
Time to Die (TTD) feature

### ISSUE THREAD

**Issue by Sylvanas714** [Hekili/hekili#2993]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

it is possible to add Time to Die feature into Hekill that could be great , because throw all of our minicd while the target dying is not optimal like Eye beam while target at 10% or something

**Comment by KevinMeinon** [comment]
This already exists. target.time_to_die to get the TTD for the current target and time_to_die to get the TTD for the current fight / encounter.

**Comment by Sylvanas714** [comment]
> This already exists. target.time_to_die to get the TTD for the current target and time_to_die to get the TTD for the current fight / encounter.

are theres any guide for that or if you could show me which section i have to edit for specific ability

**Comment by KevinMeinon** [comment]
Not sure if there are any guides but you need to change the APL in Hekili for that.  Go to the spell you want to change, then where it says "conditions" enter "time_to_die > 5" for example. If you hover with your mouse over the conditions dialog, it will show you if the condition evaluates to true or what the value of the variable is, etc.

**Comment by Hekili** [comment]
`target.time_to_die` is specific to your target.
`time_to_die` and `fight_remains` shows when the last engaged enemy is expected to die.

You can check the wiki for some tips on making edits to the priority.  In general, I try to avoid wasting CDs on trash packs but will leave stuff usable vs. a dying boss.
