### ISSUE TITLE
[FEATURE/PRIORITY] Outlaw. Disable Between the Eyes use in last 0.5 second of Crackshot window or adjust it usage to a ping.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#2996]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

For Outlaw with [Crackshot](https://www.wowhead.com/spell=423703/crackshot).
There are situations when there are 0.5 seconds left in the "Stealthed" window before the next available GCD, and the addon rightly recommends using Between the Eyes (BtE) during those 0.5 seconds.
But when BtE is pressed as recommended due to pinging or lack of response, it turns out that the "Stealthed" window is already over, which puts BtE into a 45-second cooldown, delaying other Crackshot windows.
Using the snapshot function didn't work for me, as everything happens too fast in a 0.5 second window. 
So I would like to ask you to add a feature that would actually limit the use of BtE if the next available GCD for a BtE throw is available in less than 0.7 or 0.5 seconds remaining in the "stealthed" window.
I wanted to change the duration of "stealthed.rogue", but unless I'm mistaken, there is no duration attached to "stealthed.rogue" at all.
I also tried to change the duration of "subterfuge" and made it 5 seconds instead of 6 in the profile, but nothing worked. It looks like the addon can get the actual duration of the buff despite having the "subterfuge" line in Outlaw.lua

May be changing an APL for something like this `variable.finish_condition & talent.crackshot.enabled & ( stealthed.mantle | buff.subterfuge.remains > gcd.remains * 1.5 | buff.shadowdance.remains > gcd.remains * 1.5 )` could workd as a sub-optimal solution. 

### Contact Information

IIeTpoc#3818 discord ID

**Comment by IIeTpoc** [comment]
The following change in stealth condition of BtE works good and consistent for me:

variable.finish_condition & talent.crackshot.enabled & ( stealthed.basic | buff.subterfuge.remains > gcd.remains * 1.5 | buff.shadow_dance.remains > gcd.remains * 1.5 )

**Comment by chevyn11** [comment]
+1 this seems to be dps neutral as well.. wonder if this happens to the sims sometimes too?
https://www.raidbots.com/simbot/report/vgDrwWPyAtEbmUNguJbi8s

**Comment by Hekili** [comment]
> May be changing an APL for something like this variable.finish_condition & talent.crackshot.enabled & ( stealthed.mantle | buff.subterfuge.remains > gcd.remains * 1.5 | buff.shadowdance.remains > gcd.remains * 1.5 ) could workd as a sub-optimal solution.

Change what part of the priority?  The BtE usage itself?

I'm considering a spec option like this that applies to everything in the Stealth window.
![image](https://github.com/Hekili/hekili/assets/9438134/25f89db0-e2e6-4de0-be3d-56065be3eae5)

**Comment by Hekili** [comment]
New setting is in 10.2.0-1.0.5c.

**Comment by IIeTpoc** [comment]
In the [Outlaw APL file](https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/APLs/RogueOutlaw.simc)
Line 103 `actions.stealth+=/between_the_eyes,if=variable.finish_condition&talent.crackshot` change for this `actions.stealth+=/between_the_eyes,if=variable.finish_condition&talent.crackshot&(stealthed.basic|buff.subterfuge.remains>gcd.remains*1.5|buff.shadow_dance.remains>gcd.remains*1.5)`

**Comment by IIeTpoc** [comment]
I would substitute `(stealthed.basic|buff.subterfuge.remains>gcd.remains*1.5|buff.shadow_dance.remains>gcd.remains*1.5)` with `stealthed.rogue.remains>gcd.remains*1.5` but `stealthed.rogue.remains` is not recognised as a function that can be compared with numbers.

**Comment by IIeTpoc** [comment]
Thanks for the setting!

**Comment by Hekili** [comment]
> I would substitute `(stealthed.basic|buff.subterfuge.remains>gcd.remains*1.5|buff.shadow_dance.remains>gcd.remains*1.5)` with `stealthed.rogue.remains>gcd.remains*1.5` but `stealthed.rogue.remains` is not recognised as a function that can be compared with numbers.

`stealthed.rogue_remains` with an underscore is a Hekili invention to use for timing stuff related to `stealthed.rogue`.  Generally, if a key evaluates to a value already (i.e., `stealth.rogue` evaluates to true/false) then it cannot have any sub-properties (`.remains`).  In most cases, I create the property an underscore instead.
