### ISSUE TITLE
[REC] Havoc Opener - Implement Immolation Aura Proc to Opener + add Sigil of Flame pre-cast

### ISSUE THREAD

**Issue by dsimon07** [Hekili/hekili#2997]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've noticed that the opener recommendation is inconsistent with guide writers, most notably you want to cast The Hunt empowered via Unbound Chaos/Inertia as one of your first opener damaging spells. There seems to also be need to add logic to the opener (pre-combat) around obtaining a proc of "A Fire Inside" talent, i.e. a free charge of Immolation Aura. 

### How to Reproduce

1. Enter game as Havoc DH
2. Stand in front of dummy
3. Target dummy to recommend opener

### Snapshot (Link)

https://pastebin.com/cDYNcK0W

### Additional Information

Per the guide writer opener recommendation, DH should precast Sigil of Flame after precasting Immo Aura. Opener logic is as follows:
1. Cast Immo Aura 2 seconds pre-pull
2. Cast Sigil of Flame 1 seconds pre-pull [ missing from recommendation]
3. Cast Felbade if A Fire Inside does not proc [missing from recommendation, this would enter combat]
4. Cast Eyebeam if A Fire Inside does not proc [already in combat at this point, correct order]
5. Cast Fel Rush to spend Unbound Chaos
6. Cast The Hunt
7. Cast Immolation Aura if Fire Inside procs to avoid overcapping

### Contact Information

elmer_p

**Comment by Hekili** [comment]
Please provide a sim for comparison as well.  I'm looking closely at Havoc right now, but it may be that simc still has some odd behavior (there's an open ticket over there as well).

**Comment by dsimon07** [comment]
https://www.raidbots.com/simbot/report/uFa2YpUPjLJB42qhrxDHXS

#Seems my sim doesn't use a precast SoF, or necessarily follow the prescribed opener by the letter (but neither does the recommendation engine)

**Comment by Hekili** [comment]
I've tweaked the opener which will be available soon in 1.0.11.
