### ISSUE TITLE
[REC] Assassination Rogue Snapshots due to Long Idle Time

### ISSUE THREAD

**Issue by Ktuky** [Hekili/hekili#2998]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When I do ST rotation on dummy, hekili sometimes auto snapshots.

### How to Reproduce

Enter a game as assassination rogue
1. Start ST rotation
2. Hekili auto snapshots

### Snapshot (Link)

https://pastebin.com/QXJeDkAy

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mBLEjXCECa2QyZc6hBTAKP

**Comment by Hekili** [comment]
This is because the current Assassination module, as written, has some long idle periods that exceed the addon's prediction window.

Examples:

![image](https://github.com/Hekili/hekili/assets/9438134/944634f6-f9ca-41b3-b229-4730658210ae)

![image](https://github.com/Hekili/hekili/assets/9438134/1253c87e-7190-436b-a96c-6e210ebeb79b)

Essentially, you're waiting to Envenom at this point.  I'm hoping SimC will get updated to address it.

**Comment by Hekili** [comment]
Submitted a ticket to simc reporting this behavior as a bug:
https://github.com/simulationcraft/simc/issues/8467

**Comment by IIeTpoc** [comment]
If i am not mistaken, due to [Sanguine Blades](https://www.wowhead.com/spell=200806/sanguine-blades) you want your energy to be always >50% when not in a burst window. That is why it is not advised to dump your energy just for an Envenom to close a gap. 
It might be a DPS loss forcing those fillers and waiting might actually be the most dps-efficient strategy as long as you do not cap on energy.

**Comment by Hekili** [comment]
> If i am not mistaken, due to [Sanguine Blades](https://www.wowhead.com/spell=200806/sanguine-blades) you want your energy to be always >50% when not in a burst window. That is why it is not advised to dump your energy just for an Envenom to close a gap.

It might be, but it's hard to sell an 8 second wait as intended behavior for any spec.

**Comment by Jetparsing** [comment]
> > If i am not mistaken, due to [Sanguine Blades](https://www.wowhead.com/spell=200806/sanguine-blades) you want your energy to be always >50% when not in a burst window. That is why it is not advised to dump your energy just for an Envenom to close a gap.
> 
> It might be, but it's hard to sell an 8 second wait as intended behavior for any spec.

Also as assassination it's requesting Thistle tea usage at 100% energy?

**Comment by Hekili** [comment]
> > > If i am not mistaken, due to [Sanguine Blades](https://www.wowhead.com/spell=200806/sanguine-blades) you want your energy to be always >50% when not in a burst window. That is why it is not advised to dump your energy just for an Envenom to close a gap.
> > 
> > 
> > It might be, but it's hard to sell an 8 second wait as intended behavior for any spec.
> 
> Also as assassination it's requesting Thistle tea usage at 100% energy?

Post a snapshot of this.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Jetparsing** [comment]
> > > > If i am not mistaken, due to [Sanguine Blades](https://www.wowhead.com/spell=200806/sanguine-blades) you want your energy to be always >50% when not in a burst window. That is why it is not advised to dump your energy just for an Envenom to close a gap.
> > > 
> > > 
> > > It might be, but it's hard to sell an 8 second wait as intended behavior for any spec.
> > 
> > 
> > Also as assassination it's requesting Thistle tea usage at 100% energy?
> 
> Post a snapshot of this.
> 
> A snapshot is required to diagnose this issue.
> 
> ## Snapshot
> Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.
> 
> * Log into your WoW character.
> * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
> * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
>   
>   * You can change these keybindings in /hekili > Toggles if needed.
>   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
> * Type /hekili and press Enter.
> * Open the Snapshots section on the left side.
> * Select the snapshot that shows the recommendation that you disagree with.
>   
>   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
> * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
> * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
> * Provide the Pastebin _**link**_ in a new comment.
> 
> This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems. If you do not provide this information, I cannot triage your problem.

https://pastebin.com/FS8Pcp5t

Hope this is the right one, was tough to get it in combat before priority changed due to mobs

**Comment by Delerp** [comment]
I got 4 piece and have had this happen quite often now in single target, two snapshots:
https://pastebin.com/VfVULbHp
https://pastebin.com/FYBE1fjp

Here's a raidbots sim:https://www.raidbots.com/simbot/report/3KdEw84SydBuxjJG6K5jo9

Is this caused by the same issue in this ticket?

**Comment by Delerp** [comment]
Newest version seems much better, but this sometimes still happens, two snapshots, one from dummies, one in dungeon:
https://pastebin.com/Kf3v6fRm
https://pastebin.com/v01rjNNs

**Comment by kadaggers** [comment]
Have been noticing this on my end as well.Just wanted to add my pastepin for my snapshot as well:
https://pastebin.com/AZeU87pE

Thanks for looking into this!

**Comment by Hekili** [comment]
1.0.10 has a patch in it to continue using Envenom when otherwise nothing would be recommended.
