### ISSUE TITLE
Brewmaster healing_sphere.count throws exception

### ISSUE THREAD

**Issue by nlewis2142** [Hekili/hekili#30]
By default, Expel Harm uses healing_sphere.count to track whether it can be used. The exception below is spammed whenever the addon gets the value of healing_sphere.count, which internally resolves to `GetSpellCount( action.expel_harm.id )`. As a temporary workaround, I have updated MonkBrewmaster.lua:580 to read `usable = function () return IsUsableSpell( 115072 ) end,`

Exception:
```
1711x Hekili\Classes\MonkBrewmaster.lua:255: attempt to call global 'GetSpellCount' (a string value)
Hekili\Classes\MonkBrewmaster.lua:255: in function <Hekili\Classes\MonkBrewmaster.lua:253>
Hekili\Classes\MonkBrewmaster.lua:580: in function <Hekili\Classes\MonkBrewmaster.lua:580>
(tail call): ?
Hekili\State.lua:4099: in function `IsUsable'
Hekili\Core.lua:684: in function `GetPredictionFromAPL'
Hekili\Core.lua:1025: in function `GetNextPrediction'
Hekili\Core.lua:1148: in function `ProcessHooks'
Hekili\UI.lua:1004: in function <Hekili\UI.lua:670>

Locals:
t = <table> {
}
k = "count"
(*temporary) = "GetSpellCount"
(*temporary) = 115072
(*temporary) = "attempt to call global 'GetSpellCount' (a string value)"
```

**Comment by Hekili** [comment]
Thanks, I'll resolve this by making GetSpellCount available inside the game state, but your workaround will work for the moment.

**Comment by Hekili** [comment]
Fixed.
