### ISSUE TITLE
[REC] Implement Dreambinder, Loom of the Great Cycle for Demonology

### ISSUE THREAD

**Issue by Avarazac** [Hekili/hekili#3002]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Demonology Warlock, I have equipped the staff from Nymue in Amirdrassil, called "Dreambinder, Loom of the Great Cycle". However, the addon does not ever recommend that I use this item, despite it being the BiS for my specialization for the tier. Raidbots sims show this item being used as well.

### How to Reproduce

1. Enter the game as a Demonology Warlock
2. Attack a training dummy, or any mob, and see that the addon never recommends use of the item

### Snapshot (Link)

https://pastebin.com/zasSdGbn

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2cAYTograma3RTjqwWjeTZ

### Additional Information

https://www.raidbots.com/simbot/report/uz4b4fCViYm79bMie4pc3P

**Comment by Hekili** [comment]
Let me know if this is not working in 10.2.0-1.0.5c.

**Comment by Avarazac** [comment]
> Let me know if this is not working in 10.2.0-1.0.5c.

I just updated to 10.2.0-1.0.7 and am still not seeing this item come up in the rotation.

**Comment by micolous** [comment]
This is still an issue on 10.2.0-1.0.8. It appears Hekili knows about it, but the item ID in `Dragonflight/Items.lua` is wrong:

https://github.com/Hekili/hekili/blob/216c0e83104d3e9232376e50e50287f2959b1976/Dragonflight/Items.lua#L2115-L2122

If you change `427113` ([the weapon's on-use spell ID](https://www.wowhead.com/spell=427113/)) to `208616` ([the item ID](https://www.wowhead.com/item=208616/)), then it'll appear in your rotations (provided it's in your spec's APL), and it'll now appear in the "Gear and Items" list.
