### ISSUE TITLE
[REC] VDH precombat missing sof+immo aura

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3004]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The precombat action list for vengeance demon hunter currently only includes heart of azeroth, but it should include sigil of flame and immolation aura (from https://github.com/simulationcraft/simc/blob/dragonflight/profiles/Tier31/T31_Demon_Hunter_Vengeance.simc). Not sure if it is even calling the precombat action list, but it should be. Currently recommendations are wrong for engaging, as it should be pre SoF>infernal strike+spikes+immolation aura>fiery brand(>spirit bomb for threat, probably not "optimal" by simc standards), but SoF is not recommended precombat and immo aura is not recommended early in the pull.

### How to Reproduce

Load 10.2.0 1.0.5 and see recommendations

### Snapshot (Link)

https://pastebin.com/2AqWbrRp

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/riHevaRKKaUtpQ3wk1exHq

**Comment by dubudevs** [comment]
I manually added SoF to the precombat but it suggests double casting even without ascending flame talented, because by the time it would be casting the second SoF the first hasn't popped yet I guess so technically they don't have the debuff? Not 100% sure https://pastebin.com/9H1gRr36

**Comment by Hekili** [comment]
One of the newer releases has updated conditions you could copy:

`talent.ascending_flame & ! talent.illuminated_sigils | ! sigil_placed & active_dot.sigil_of_flame = 0`

There's actually a potential flicker when sigil_placed expires but the debuff hasn't applied, but I'll fix that in due time.

**Comment by dubudevs** [comment]
> One of the newer releases has updated conditions you could copy:
> 
> `talent.ascending_flame & ! talent.illuminated_sigils | ! sigil_placed & active_dot.sigil_of_flame = 0`
> 
> There's actually a potential flicker when sigil_placed expires but the debuff hasn't applied, but I'll fix that in due time.

Looks good, it doesn't predict sigil_placed so it shows double recommendation until you actually cast SoF but looks good otherwise :)

**Comment by Hekili** [comment]
Should be okay with the latest release:

![image](https://github.com/Hekili/hekili/assets/9438134/8e6e5124-e022-4425-a518-72abacb0dccc)

**Comment by dubudevs** [comment]
![image](https://github.com/Hekili/hekili/assets/91028108/8b6c261f-3670-4164-aae4-8ae9f94eef18)
this is what I'm getting

**Comment by dubudevs** [comment]
https://i.imgur.com/CEfGqbU.png This is immediately after pressing SoF https://pastebin.com/75xYh98k (my prio is slightly different other than just the precombat changes, thats why immo aura is there but it shouldn't affect it? I changed can_spb, moved immo aura up, and moved fracture above cleave in small_aoe)

**Comment by Hekili** [comment]
Yeah, may be relying on a few changes I haven't pushed yet.

**Comment by dubudevs** [comment]
Seems to be working correctly with 1.0.6a (that APL modified in the same ways and that version of the addon)

**Comment by Hekili** [comment]
With Sigil of Flame and Immolation Aura in the precombat list, Immo gets skipped because Infernal Strike and Metamorphosis were flagged to be used off the GCD -- so they were available during SoF's GCD.  I've modified these to get similar results as SimC in the next release (1.0.8).
