### ISSUE TITLE
[BUG] Prot warrior rotation recommendations are on CD

### ISSUE THREAD

**Issue by ryanjthiele** [Hekili/hekili#3006]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Bug started a few days ago and was working fine previously. Hekili is recommending an ability and when I've used the recommendation it doesn't update even whilst the ability is on CD. Seems to reset on death of the target but get stuck again every time essentially making the rotation helper useless. I have no attempted to reproduce on other classes or specs at this stage.

### How to Reproduce

Unsure, Prot warrior, recently hit max level and respecced my talents to a mythic + build.

### Player Information (Link)

https://pastebin.com/PpFg2pBD

### Error Messages (Link)

Nil error

### Contact Information

b.funk (Discord)

**Comment by Hekili** [comment]
Update to the latest version.
