### ISSUE TITLE
[BUG] Warrior Rotations Not Updating Beyond CDs

### ISSUE THREAD

**Issue by JWattRealEstate** [Hekili/hekili#3007]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I see some reports for other warrior specs, but I noted that on my profile, ALL warrior specs are failing to update priority. Cooldowns aren't properly triggering and it will stick on any ability with a CD. I tried removing profiles, reinstalling, etc. to no avail.

### How to Reproduce

1. Enter game as warrior
2. Try to progress through rotation beyond a cooldown
3. Rotation sticks at the cooldown and won't update

### Player Information (Link)

https://pastebin.com/V4Kjri8N

### Error Messages (Link)

N/A

### Contact Information

Discord: jackdx

**Comment by Hekili** [comment]
Update to the latest version.
