### ISSUE TITLE
[FEATURE] New Toggle/Display for Healing Spells (Enhancement)

### ISSUE THREAD

**Issue by Geistergurke** [Hekili/hekili#3008]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I think it would be very useful to have the option to toggle on the recommendation of healing spells.
To be specific for things like Earth Shield or Healing Stream Totem.

ATM I get the same result by just adding them to the Priority list right after all the important DPS-Spells.
That way I generate a lot more value for the raid.

But after each Priority List Update I have to add them manually again. So a built-in toggle would be nice.

**Comment by Hekili** [comment]
If you customize your priority to include healing spells, I would recommend adding the abilities to the Interrupts toggle and treating that display as a sort of utility/healing display instead.  See /hekili > Abililties > Require Toggle.
