### ISSUE TITLE
Warrior Rotation doesnt work.(Rotation Freezed in Combat )

### ISSUE THREAD

**Issue by Alim2310** [Hekili/hekili#3009]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Arms Warrior, if i Start the fight the Rotation Freezes and dont show me the next spells to use. (Work on other Classes like Feral, Mage and Priests(all Twinks) just Warrior Not).

### How to Reproduce

1.Log in as Warrior Arms
2. Start a Combat

### Snapshot (Link)

https://pastebin.com/9vuCgAwj

**Comment by Hekili** [comment]
Update to the latest version.

**Comment by JWattRealEstate** [comment]
I am on the latest version and am still having the same issue. You closed my ticket for the same issue and it's still not fixed. Please elaborate more.
