### ISSUE TITLE
How to make hunter mend pet?

### ISSUE THREAD

**Issue by quetzalsly** [Hekili/hekili#301]
I need to somehow make hunter mend pet on cooldown (for soloing some bosses). Also maybe the 30% heal spell + turtle. Is there any easy way to add these without having to write a whole script?

**Comment by Hekili** [comment]
No, if you want to add to a priority, you have to have some comfort/familiarity with APL syntax and logic.

That said:

1.  Go to /hekili > Priorities > Beast Mastery (or whichever) > Action Lists.
2.  Select Action Lists tab.
3.  Select the default Action List.
4.  Click the + next to Entry to create a new entry.
5.  Select Mend Pet.
6.  For conditions, probably try `pet.alive & pet.health_pct < 30` and tweak as you see fit.  That literally means, "pet is alive and pet health is below 30%."
7.  Go test on a boss dummy.

Note that when you edit a default priority, it will be overwritten if I release an updated priority later on.  To get around that, you can create a copy.

1.  Click 
![image](https://user-images.githubusercontent.com/9438134/78995076-93a4d300-7b0f-11ea-953f-3b47e1826c7c.png)

on the priority's screen, next to the name:

![image](https://user-images.githubusercontent.com/9438134/78995063-8c7dc500-7b0f-11ea-91fe-e43ad815f875.png)

2.  Click Accept.
3.  Change the name to something clearer than "Beast Mastery (2)" if you want.
4.  Check Active.  (This will tell the addon to use your edited copy.)

**Comment by quetzalsly** [comment]
Thanks!
