### ISSUE TITLE
[BUG] Warrior Rotation STILL Not Updating - On Newest Version

### ISSUE THREAD

**Issue by JWattRealEstate** [Hekili/hekili#3010]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Warrior rotation STILL not updating while in combat. Previous tickets for same issue were closed saying to update to newest version - addon last updated yesterday, 11/23, v10.2.0-1.0.6a. Please elaborate rather than closing with an 'update to newest version' statement.

### How to Reproduce

1. Enter game as warrior
2. Enter combat
3. Watch rotation fail to update

### Player Information (Link)

https://pastebin.com/v3ybU38Z

### Error Messages (Link)

N/A

### Contact Information

Discord: jackdx

**Comment by Hekili** [comment]
1.0.7 is the newest version (it posted late but it's available now).

**Comment by JWattRealEstate** [comment]
The update just came through via forge. Thanks team! I appreciate you guys.
