### ISSUE TITLE
Protection warrior priorities frozen

### ISSUE THREAD

**Issue by PaulBab1** [Hekili/hekili#3011]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

First of all thank you for your work.
I saw multiple tickets that have been closed, saying "update to last version" reporting the same issue. 
I am on last version provided by curseforge and i encounter the issue : 
In protection spec, my recommandations does not update. They are frozen the second i enter in combat. Is there a more recent version of the addon that is not on curseforge ?
Anyway thank you for your time !

### How to Reproduce

1 - As a lvl 70 protection warrior (1pc of set, don't know if its important)
2 - charge into melee and start pressing abilities
Actual result : 
  The recommandation does not update and remain the same in the exact same order.
Expected result : 
  The recommandation update has they do for all other classes

### Snapshot (Link)

https://pastebin.com/jWBJse34

### Additional Information

Recommandation seems to update (1 step ) at death of an enemy

**Comment by Hekili** [comment]
Get 1.0.7

**Comment by PaulBab1** [comment]
wonderfull ! curseforge just proposed me this version and it fix the issue ! thanks a lot !
