### ISSUE TITLE
[BUG] Warrior, Hekili rotation not updating when target within melee range

### ISSUE THREAD

**Issue by paul-stork** [Hekili/hekili#3012]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

While in combat as a warrior, if the target is within melee range the rotation is not updated. However when stepping out of melee range it updates. This seems to affect Protection and Fury specs, not sure about Arms. I tried to replicate this on other melee classes, but it only seems to be on warriors.

### How to Reproduce

Log in using a warrior, get within melee range, and try to use the rotation.

### Player Information (Link)

https://pastebin.com/s2GCsPMn

### Error Messages (Link)

n/a

### Additional Information

No error message generated, that I noticed.

**Comment by Hekili** [comment]
Get 1.0.7
