### ISSUE TITLE
[REC] Shaman DPS stuck on casted ability/buff

### ISSUE THREAD

**Issue by firagano** [Hekili/hekili#3014]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For both elemental and enhancement priority lists, the addon is getting stuck on an already casts buff/cooldown. For elemental, it is getting stuck on Stormkeeper and for enhancement, it is getting stuck on Flametongue weapon. Example picture is below.

Enhancement
![image](https://github.com/Hekili/hekili/assets/151963521/b0d362fb-fe9d-415f-b7af-8761c2d5601c)
Image shows that my offhand is imbued with Flametongue, yet it is constantly recommending it at the top of the queue.

### How to Reproduce

1. Enter game as Enhancment Shaman.
2. Imbue weapon with Flametongue and Windfury weapon
3. Go to training dummy and start rotation order.
4. Flametongue weapon keeps rising to the top of the list, causing the next true ability to not be casted.

### Snapshot (Link)

https://pastebin.com/SWxF3y9p

### Additional Information

In general, priority is correct outside of this bug, so I did not include the raidbots link.

### Contact Information

Discord = firagano

**Comment by Hekili** [comment]
Did you manage to put WF and FT on the wrong hands?  I think the addon look s for WF/FT on MH/OH specifically.

**Comment by firagano** [comment]
Hello friend. No, it is an automatic cast onto the proper hand and they disabled the weapon swap trick due to some PVP shenanigans in S2 of SL.

**Comment by Hekili** [comment]
Is this happening with the latest release?

**Comment by Tomorrow-sudo** [comment]
Ive been having the same issue with the recommends getting stuck and not updating. This only happens when trying to use a custom profile, the default priorities work great. 

- Imported profile from simulation craft version "simc-1020.01.217f34a-win64"
- Using Hekili [v10.2.0-1.0.9]

This is the snapshot I took:

```
Message: [string "-- SIM:default:23..."]:2: attempt to index global 'rotation' (a nil value)
Time: Mon Nov 27 12:46:51 2023
Count: 1
Stack: [string "-- SIM:default:23..."]:2: attempt to index global 'rotation' (a nil value)
[string "-- SIM:default:23
return safebool( active_enemies>1 and (rotation.standard or rotation.simple) )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Hekili/Core.lua"]:853: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1405: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1691: in function `Update'
[string "@Interface/AddOns/Hekili/Options.lua"]:11159: in function `MakeSnapshot'
[string "@Interface/AddOns/Hekili/Options.lua"]:11260: in function `FireToggle'
[string "@Interface/AddOns/Hekili/UI.lua"]:2811: in function <Interface/AddOns/Hekili/UI.lua:2810>

Locals: (*temporary) = <function> defined @Interface/AddOns/Hekili/State.lua:623
(*temporary) = nil
(*temporary) = "attempt to index global 'rotation' (a nil value)"
```

Thanks for sharing your work <3

**Comment by firagano** [comment]
> Is this happening with the latest release?

My currently installed version is v10.2.0-1.0.7. I see there is an update to v10.2.0-1.0.9, which I will give a try and provide feedback on, I have raid tonight so it will be a good test case.

**Comment by firagano** [comment]
Looks like the update to v10.2.0-1.0.9 worked to fix the problem. it is no longer recommending the weapon imbues when they are already applied.

**Comment by Hekili** [comment]
> Ive been having the same issue with the recommends getting stuck and not updating. This only happens when trying to use a custom profile, the default priorities work great.
> 
>     * Imported profile from simulation craft version "simc-1020.01.217f34a-win64"
> 
>     * Using Hekili [v10.2.0-1.0.9]
> 
> 
> This is the snapshot I took:
> 
> ```
> Message: [string "-- SIM:default:23..."]:2: attempt to index global 'rotation' (a nil value)
> Time: Mon Nov 27 12:46:51 2023
> Count: 1
> Stack: [string "-- SIM:default:23..."]:2: attempt to index global 'rotation' (a nil value)
> [string "-- SIM:default:23
> return safebool( active_enemies>1 and (rotation.standard or rotation.simple) )"]:2: in main chunk
> [string "=(tail call)"]: ?
> [string "@Interface/AddOns/Hekili/Core.lua"]:853: in function `GetPredictionFromAPL'
> [string "@Interface/AddOns/Hekili/Core.lua"]:1405: in function `GetNextPrediction'
> [string "@Interface/AddOns/Hekili/Core.lua"]:1691: in function `Update'
> [string "@Interface/AddOns/Hekili/Options.lua"]:11159: in function `MakeSnapshot'
> [string "@Interface/AddOns/Hekili/Options.lua"]:11260: in function `FireToggle'
> [string "@Interface/AddOns/Hekili/UI.lua"]:2811: in function <Interface/AddOns/Hekili/UI.lua:2810>
> 
> Locals: (*temporary) = <function> defined @Interface/AddOns/Hekili/State.lua:623
> (*temporary) = nil
> (*temporary) = "attempt to index global 'rotation' (a nil value)"
> ```
> 
> Thanks for sharing your work <3

Part of using imported priorities is having to make the adjustments that I make to th
