### ISSUE TITLE
Getting LUA error with Elemental Shaman

### ISSUE THREAD

**Issue by Mike160770** [Hekili/hekili#3015]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When logging in with my Elemental Shaman the following error appears in my BugSack

### How to Reproduce

Appears right away when logging in with my Elemental Shaman

### Player Information (Link)

https://pastebin.com/CUpw5srW

### Error Messages (Link)

https://pastebin.com/HJE5cbGH

**Comment by jrobcodes** [comment]
Anyone know where the original text comes from for the descriptions? I can submit a PR to fix, but not sure what the missing string is supposed to be..

**Comment by Mike160770** [comment]
Any idea somebody? This LUA error gets annoying...

**Comment by Hekili** [comment]
It'll be fixed in the next release.  It is just text describing a new option.  It shouldn't be particularly obtrusive.

**Comment by jrobcodes** [comment]
The enhancement rotation doesn't load; @Mike160770, you can temporarily fix this by changing line 2430 in `Dragonflight\ShamanEnhancement.lua` from:
```lua
        spec.abilities.flame_shock.name, spec.abilities.primordial_wave.name),
```
to
```lua
        spec.abilities.flame_shock.name, spec.abilities.primordial_wave.name, "temp" ),
```

**Comment by Hekili** [comment]
Should be resolved in current release.
