### ISSUE TITLE
[REC] Vanish cooldown is not being tracked

### ISSUE THREAD

**Issue by vititex** [Hekili/hekili#3016]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Vanish cooldown is not being tracked correctly, the value of "cooldown.vanish.remains" is always at "120".

![image](https://github.com/Hekili/hekili/assets/151975998/8577bc5a-4fca-4d58-8cf7-cf7f6ede4cf4)

### How to Reproduce

1. Enter game as outlaw rogue.
2. Use vanish.
3. Open Hekili and navigate to outlaw "Action List".
4. Hover mousecursor over the conditions.

### Snapshot (Link)

https://pastebin.com/cg2dPjuN

### Contact Information

Discord ID: vitlor

**Comment by chevyn11** [comment]
you have `solo_vanish = false` so vanish cooldown is set to max as long as youre not in a group to prevent it from being suggested.

**Comment by vititex** [comment]
Unfortunately, that doesn't change anything. I had just turned it off temporarily to see if it makes any difference.

**Comment by chevyn11** [comment]
works for me, toggling solo_vanish on/off goes from 120 to whatever the actual cooldown is
![image](https://github.com/Hekili/hekili/assets/111624332/68efcb7e-6e13-411d-8734-0c9c47bab198)

Is your vanish disabled in Abilities menu?

**Comment by vititex** [comment]
nope 
![image](https://github.com/Hekili/hekili/assets/151975998/88189c7b-2ce3-4104-b018-e392c5989f53)

**Comment by chevyn11** [comment]
From that it looks like vanish is on the `Custom 1` toggle? your snapshot has that toggled off.

**Comment by vititex** [comment]
I see, that must be my old settings from season 1 or 2. I've already forgotten about it, thought I had reset everything.
I have now reset the addon completely as a precaution and manually readjusted my GUI, and now it seems to be working.
Thank you very much for the fast and precise help!
