### ISSUE TITLE
[BUG] Latest updated broke the only version of SpellFlashCore that's able to scan macros.

### ISSUE THREAD

**Issue by LupinePariah** [Hekili/hekili#3018]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

It's an odd one, this.

So, beta2? I can drop in the fix for SpellFlashCore... And it works just fine. Lovely. It can scan macros, everything is hunky-dory. Great. Okay, so, I updated to 10.2.0-1.0.7 (coming directly off of beta2) and... it broke in such a weird way.

There's now a lag with removing the prior instance. In other words, it won't stop flashing the prior icon for a little while before it starts flashing the next. So on a number of classes I play it's regularly flashing two icons. A roll back to beta2 fixes this.

Here's the fixed SFC that I'm dropping in to have it work with macros: 

https://github.com/Hekili/hekili/files/13400697/SpellFlashCore.txt

The reason I'm dropping that in is that 10.2.0-1.0.7 just doesn't read my macros. It's, as I understand it, a change that occurred in the latest API change, along with making CheckInteractDistance() private. It's something about how GetActionInfo() functions, I believe?

I don't like being a bother, so up until the latest version of Hekili I'd just been quietly dropping in the fix myself. I did try to diff the fix and the SFC in Hekili to try to figure out what had changed, and I was fastidious in how I handled that but it still resulted in the lag that had two slots often flashing at the same time. I'm just not familiar enough with how Hekili functions to do more than I am.

I could be, but at this point, getting this much into the guts of the addon every update is not a place I want to be in as I'm currently taking a break from lua-dev efforts myself. Plus, as much as I have social anxiety, it'd be selfish to keep this to myself regardless as this might help others for whom SFC is failing.

I'm not sure what else I can add, really? I mean, there's nothing to be added from BugSack as this isn't a bug per se. No artillery-administering annelids yelling fatality here.

### How to Reproduce

A succinct rundown it is, then.

- SpellFlashCore doesn't read macros.
- Using the fixed SpellFlashCore results in strange lag where it often flashes two abilities at once.
- Rolling back one version to beta2 doesn't have SFC read macros either, but the fix does work with this one.

### Player Information (Link)

Okay, this part really isn't going to be helpful due to the nature of the beast and how the issue affects all characters and classes with any kind of macro. Plus, I'm outside of WoW right now and anxious enough about doing this already. So I'm going to fire this off as-is and hope for the best!

### Error Messages (Link)

This isn't necessary either, for obvious reasons.

### Contact Information

Social anxiety, no thanks, sorry. I just wanted to raise awareness of this.

**Comment by mgmaxgra** [comment]
[SpellFlashCore.txt](https://github.com/Hekili/hekili/files/13493317/SpellFlashCore.txt)

Hi,
Here is my version what i modified by myself.
It will fix the macro issue (Properly a quick & dirty solution, but works...)
I also fixed the issue, that if sometimes if on action bar slot change the spell on the fly (like bloodthirst, bloodbath) will not glow.

**Comment by Hekili** [comment]
I'd need a proper diff to find your changes or for you to submit a pull request to SpellFlashCore to implement your fix.

**Comment by Hekili** [comment]
I lied; I'll use your version until the main addon has its own fix.
