### ISSUE TITLE
[OUWTLAW ] Addon not taking ''Deft Maneuvers'' in consideration on 5+ targets 

### ISSUE THREAD

**Issue by rogueplayeryes** [Hekili/hekili#3019]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Since the rework of the ouwtlaw tree we got the talent ''Deft Maneuvers'' wich should be used on cooldown for the specc to really go far and beyond on aoe-dmg. 

*Blade Flurry's initial damage is increased by 100% and generates 1 combo point per target struck.

Atm the addon is considering singeltarget spells rather than using Blade Flurry when 2 or less combo points in a scenario where there are 5 or more targets up.

### How to Reproduce

1.Have atleast 5+ targets 
2. Start the usual AOE-rotation
3. watch the addon dont reccomend using Blade Flurry when it comes of CD even tho 5+ targets is alive
4. 

### Snapshot (Link)

https://pastebin.com/y7ySW98B

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rCQirLzaqhb7WyQryA5vDN

**Comment by Hekili** [comment]
Didn't get the complete snapshot -- you have to CTRL+A (or Mac equivalent) to select all text before CTRL+C to copy.  You'll end up with thousands of lines of text.

**Comment by rogueplayeryes** [comment]
https://pastebin.com/2dupUmKW

Did it right this time.

**Comment by rogueplayeryes** [comment]
i dont think i was really clear in my response.

Blad Flurry is still Active but the CD is off cooldown and are ready for use - instead of considering BF in the newly linked snapshot the addon wants me to use Sinister Strike. Yes there are only 4 targets since there are not more target dummys but when im trying it out and pressing BF off CD with 2 or less Combo points there is a significant Dps increase.

**Comment by Hekili** [comment]
It considered Blade Flurry:

```
 - this entry's criteria FAILS: ( spell_targets.any[4.00] >= 2 - talent.underhanded_upper_hand.enabled[true] & ! stealthed.rogue[false] ) & buff.blade_flurry.remains[164.18] < gcd.max[0.80] | talent.deft_maneuvers.enabled[true] & spell_targets.any[4.00] >= 5 & ! variable.finish_condition[false]
```

This would've fired if you had 5+ targets.  If you have a dummy toy from Pandaria or elsewhere, you might try dropping it and seeing the recommendation change.

That said, Blade Flurry would *clearly* be a better button-press both damage and Combo Point-wise, so I'll investigate a bit more to see why the priority doesn't include it.  It could be an error on my part, translating from SimC.

**Comment by Hekili** [comment]
Can you provide a Quick Sim of your character instead of Top Gear?  4 targets Patchwerk, please.

**Comment by rogueplayeryes** [comment]
https://www.raidbots.com/simbot/report/6PF5ap5Lwufc4GHGNRM44u

I will try it out with a 5th dummy provided from toy collection. Posting again if it changes (fairly sure it wont since it does not in m+ with more than 10+ targets)

**Comment by rogueplayeryes** [comment]
> It considered Blade Flurry:
> 
> ```
>  - this entry's criteria FAILS: ( spell_targets.any[4.00] >= 2 - talent.underhanded_upper_hand.enabled[true] & ! stealthed.rogue[false] ) & buff.blade_flurry.remains[164.18] < gcd.max[0.80] | talent.deft_maneuvers.enabled[true] & spell_targets.any[4.00] >= 5 & ! variable.finish_condition[false]
> ```
> 
> This would've fired if you had 5+ targets. If you have a dummy toy from Pandaria or elsewhere, you might try dropping it and seeing the recommendation change.
> 
> That said, Blade Flurry would _clearly_ be a better button-press both damage and Combo Point-wise, so I'll investigate a bit more to see why the priority doesn't include it. It could be an error on my part, translating from SimC.

ive tried out now with a 5th dummy - even tho i cant hit it for some buggy reason the addon picking up a 5th target.
Now it recommend BF on CD, and very accurate, that said i dont know why it wont do it for me in dungeons.

**Comment by chevyn11** [comment]
There is a pull request for this now to optimise for 3-4+ target deft blade flurrys https://github.com/simulationcraft/simc/pull/8481
So it should come to hekili eventually.

**Comment by rogueplayeryes** [comment]
> There is a pull request for this now to optimise for 3-4+ target deft blade flurrys [simulationcraft/simc#8481](https://github.com/simulationcraft/simc/pull/8481) So it should come to hekili eventually

This is great! cheers for picking it up!

**Comment by Hekili** [comment]
This has been updated.
