### ISSUE TITLE
Fury - Essences Show up in Cooldowns and Essences Both

### ISSUE THREAD

**Issue by Kechlion** [Hekili/hekili#302]
Both Guardian of Azeroth and Focused Azerite beam show up when either Cooldowns or Essences are checked. 

In the abilities tab they both require the Default (essences) yet unselecting essences does not remove it from the rotation queue. Nothing beyond either turning off Cooldowns and Essences both or completely axing the essence from the rotation seems to fix it.

![cd_only_essence_01](https://user-images.githubusercontent.com/60458868/76652632-003ea900-6535-11ea-8607-6229cce85483.PNG)

build: v8.3.0-04-15
level: 120 (120)
class: WARRIOR
spec: fury

talents: bounding_stride
    carnage
    dragon_roar
    endless_rage
    siegebreaker
    storm_bolt
    sudden_death

azerite: azerite_empowered = 3
    cold_steel_hot_blood = 3
    gutripper = 1
    impassive_visage = 1
    intimidating_presence = 1
    overwhelming_power = 1
    reckless_flurry = 1
    resounding_protection = 1
    simmering_rage = 1
    unbridled_ferocity = 1
    unstable_flames = 1

essences: [condensed_lifeforce] = 3, breath_of_the_dying = 3, conflict_and_strife = 3, worldvein_resonance = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    ashvanes_razor_coral = 1
    breastplate_of_twilight_decimation = 1
    corrupted_gladiators_signet = 1
    dragonbone_vambraces = 1
    gauntlets_of_the_avian_sentinel = 1
    getiikku_cut_of_death = 1
    gilnean_adventurers_shirt = 1
    heart_of_azeroth = 1
    helm_of_abyssal_malevolence = 1
    humming_black_dragonscale = 1
    leadplate_legguards = 1
    logg = 1
    malignant_leviathans_waistguard = 1
    ornate_elundris_ring = 1
    pauldrons_of_infinite_darkness = 1
    stormsurgers_sabatons = 1

corruptions: deadly_momentum = 2
    void_ritual = 2

itemIDs: 158075, 159413, 159420, 159430, 159451, 159644, 165679, 169050, 169223, 169311, 172665, 173822, 174044, 174164, 174166, 174170, 49567

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = false
    mode = reactive
    potions = false

**Comment by Hekili** [comment]
See the Toggles tab. You can have Essences set to be active when Cooldowns are enabled.

**Comment by Kechlion** [comment]
I see the override now, my apologies for not finding it sooner. Thank you for the help.

**Comment by Hekili** [comment]
Glad to help!
