### ISSUE TITLE
Demonology Warlock rotation seems to be off, it seems to hold on to demonic cores, and it recommends tyrant before grimoire felguard after the initial opener.

### ISSUE THREAD

**Issue by Adamvxx** [Hekili/hekili#3020]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For demo warlocks, we are supposed to cast tyrant after grimoire felguard so we have as many pets out as possible, the addon is recommending that you summon tyrant on cd pretty much. 

It also seems to want to hold on to demonic core casts, to the point they expire. 

### How to Reproduce

Use the standard "Naked tyrant" single target build. It does the same for most other "naked tyrant" builds 

### Snapshot (Link)

https://pastebin.com/gr1WgUvk

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hSCnjHp1wGtH78pVtucX75

### Additional Information

Now that I have submitted this - it actually looks like raidbot sim is incorrect, as it is not casting 2nd grimoire felguard and holding it for 3rd tyrant. I think this is due to the Mirror of fractured tomorrows trinket.

**Comment by Adamvxx** [comment]
Snapshot  - https://pastebin.com/1NSBQiqa
Sim - https://www.raidbots.com/simbot/report/8HfDzxBw42E7EXZodRo4iu

Another paste bin for you, as this is a different trinket and the addon recommends tyrant way before felguard is off cooldown

In this Sim you can see it holds tyrant until Grimoire felguard is off cooldown and then will cast tyrant, the addon wants to cast tyrant on cooldown instead of wait.

**Comment by Hekili** [comment]
Please update if this is occurring with 1.0.10 or later.  Thanks.

**Comment by N30Exca** [comment]
tyrant suggested outside GFG is still an issue as for 1/1/2024 after last update, onm early build it was working as intended, also Demonic Strenght activation remove Nymue Spindle trinket suggestion from action list.

https://pastebin.com/24tq6k8g

**Comment by Hekili** [comment]
> onm early build it was working as intended

On which build?

**Comment by N30Exca** [comment]
[V10.2.0-1.0.21](build: v10.2.0-1.0.21)

**Comment by N30Exca** [comment]
I updated early this morning and i notice this with 1.0.20 all was fine

**Comment by N30Exca** [comment]
https://pastebin.com/MbMjK92D

with 1.0.20 just to compare

**Comment by deanbot3k** [comment]
also does not properly display the correct opener cast sequence of Power Siphon > Grimoire > Shadowbolt > call Dreadstalkers > Shadowbolt > hand > demonbolt > hand > demonbolt > hand > demonbolt > tyrant > nymues
