### ISSUE TITLE
[Outlaw] BtE Suggestion happening outside of Subterfuge Window

### ISSUE THREAD

**Issue by Tastix** [Hekili/hekili#3022]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On Outlaw Rogue, after the most recent update it is now suggesting I use Between the Eyes anytime I am at 5+ combo points even with Vanish and Shadow Dance off cooldown, and outside of Subterfuge windows. Previously, it would only suggest BtE outside of Subterfuge windows when Vanish had > 45 second cooldown and Shadow Dance had > 15 seconds on cooldown. 

### How to Reproduce

1. Log into game as outlaw rogue.
2. Engage training dummies outside of subterfuge with Vanish and Shadow Dance off cooldown
3. Build 5+ combo points
4. Excluding buffs, Between the Eyes is the recommended action even when outside of subterfuge and with Vanish and Shadow Dance off cooldown.

### Snapshot (Link)

https://pastebin.com/QEJGpCFU

### Additional Information

No Raidbots Sim Link, issue happens in all combat situations, including target dummies.

**Comment by Tastix** [comment]
https://pastebin.com/nyWpfj2C
Don't believe I added the Snapshot link correctly, here are the logs pulled once the recommended action was paused.

**Comment by chevyn11** [comment]
your snapshot is still incorrect, but from what I can see your cooldowns are toggled off. 

If you have vanish and dance on the cooldown toggle then hekili will set them to their max cooldown (120 and 60?). This means hekili always thinks your vanish and dance are >45 and >15 seconds away and suggest BTE.

**Comment by Tastix** [comment]
Sounds like user error on my part. Sorry new to game and modding. Where can I view/edit the cooldown toggle for Vanish and Shadow Dance?

**Comment by chevyn11** [comment]
no problem, there should be a toggle when you click on the minimap icon for hekili, just make sure 'Cooldowns' it toggled on and it should start suggesting things correctly.

As for snapshots, when copying a snapshot you have to copy all the lines (even though its only 1 line shown). Hit ctrl+a to select all the text and then copy. Otherwise you only get the top line.

**Comment by Tastix** [comment]
Good to know and thanks so much for the help! That resolved it. Not sure how it got unchecked, but it's working as intended now!

**Comment by Tastix** [comment]
Marking as closed
