### ISSUE TITLE
[FEATURE] TARGET additional state to check if target is in meele range

### ISSUE THREAD

**Issue by mgmaxgra** [Hekili/hekili#3023]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello,

Would it be possible to add following state for the target?

```
....

local mt_target
do
    local autoReset = setmetatable( {
        distance = 1,
        in_range = 1,
        in_meele_range = 1,

....

          elseif k == "in_range" then return t.distance <= 8
            elseif k == "in_meele_range" then 
                name_ = GetSpellInfo(1715)
                return IsSpellInRange(name_, "target") or 0

            elseif k == "minR" or k == "maxR" then
                local minR, maxR = RC:GetRange( "target", true, InCombatLockdown() )
                t.minR = minR or 5
                t.maxR = maxR or 10
....
```

In my own version i have done it with the Hamstring spell, so properly it will not work for every class?
I have only tested it with my warrior, and use this state that for example some trinket will not recommended while in range...

BR Markus

### Additional Information

I have done it before with target.distance < XX, but you know, this isn't working anymore because it becomes protected in combat and distance always will be 15...

**Comment by Hekili** [comment]
What do you need it for?

**Comment by mgmaxgra** [comment]
To be honest it's just about convenience.
For example it's not a good decision to use "Branch of Tormented Ancient" in range as meele.
But yes, there are other solutions for that...

A: Using brain
B: Add it manually for myself...

**Comment by Hekili** [comment]
If you're using Hamstring's spell ID to check range on your Warrior, why wouldn't you just use `action.hamstring.in_range` which already exists?

**Comment by mgmaxgra** [comment]
That's a possibility.
I didn't know that this option exists.
Thanks for your support!
