### ISSUE TITLE
[REC] Assassination Rogue. When clearing AOE packs and then some of the mobs die the addon fails and stops suggesting spells. 

### ISSUE THREAD

**Issue by Fuxxic** [Hekili/hekili#3025]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When AOEing multiple mobs the priority list works fine but when mobs start to die and then there are less mobs the addon fails. The spell que goes blank and it stops suggesting spells.

### How to Reproduce

1. Use my talent build on an assassination rogue.
2. Start aoeing a large pack of mobs.... 5 or 6.
3. continue to aoe until the mobs start to die and the mob count goes down.

### Snapshot (Link)

https://pastebin.com/U0zhywAK

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tyYgH82gkP1jKhPvBn5iZz

### Additional Information

This problem seems to occur when going from multiple targets and then reducing targets.

### Contact Information

fartymcturdy#8524

**Comment by Hekili** [comment]
1.0.10 has a patch in it to continue using Envenom when otherwise nothing would be recommended.

**Comment by kadaggers** [comment]
Thank you so much @Hekili! Appreciate the modification on this
