### ISSUE TITLE
[REC] Nymue's Unraveling Spindle is not being recommended on the opener for Warlocks ( Don't know about other classes )

### ISSUE THREAD

**Issue by Niquity** [Hekili/hekili#3027]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As title says, the trinket Nymue's Unraveling Spindle is having issues being recommended on the opener. As seen by simbot, it's being recommended yet the addon omits it on the opener and only waits for the NEXT Summon Demonic Tyrant CD.

### How to Reproduce

1. Target Training Dummy
2. Use rotation as recommended. Nymue's trinket will not show up in opener

### Snapshot (Link)

https://pastebin.com/6dZC9Kjn

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/idjtGd7bPzSUQMcMamSjEA

### Additional Information

There were some times while on the target dummy the Trinket would pop up in the recommendation queue ( I have it set to 6 ) but would disappear when it's #1-3 in the queue. I'm not sure if my snapshot caught that.

**Comment by Niquity** [comment]
Sorry new here. Can't edit the main post so here's another snapshot. I'm using my single target build: https://pastebin.com/EsVXKuGk
Multi target build: https://pastebin.com/bDmFeeLG

Forgot to mention I also have Belor'relos, the Suncaller trinket so both BIS trinkets equipped. After some testing, it seems with both trinkets equipped it is no longer recommending Belor'relos as the first spell to open with and is instead putting it after Summon Demonic Tyrant where Nymue is supposed to be which then puts Nymue in the next Summon Demonic Tyrant.

EDIT: If I try opening with Belor trinket it still doesn't wait for Nymue to become useable in the opener and instead just recommends Summon Demonic Tyrant without it. When opening with Belor and going through the recommended opener, Nymue does appear in the recommended queue but disappears a few steps before it's next in queue: https://pastebin.com/y3XXNHQk  hopefully that snapshot got it.

**Comment by Hekili** [comment]
The profile is not written to wait for Nymue to become usable in the opener.

![image](https://github.com/Hekili/hekili/assets/9438134/ef5c9003-7a3c-447d-959f-b691be96912a)

**Comment by Niquity** [comment]
Is it normal for it to hold nymue and not cast it until 2m into the fight? That doesn't seem right. In the sim it casts Belor as opener and Nymue 21s into the fight.

**Comment by xcsyx** [comment]
It's expected to be used as soon as possible after Tyrant. In the latest hek 10.2.0-1.0.10 - with Belor'relos Suncaller equipped, I am not recommended to use Nymue's Unraveling Spindle, at all. I once saw it blink for a fraction of a second into the suggested prio, but then it's gone. If I hit a dummy for 6 minutes, I will never see a suggestion to use a spindle. 

[no_spindle.txt](https://github.com/Hekili/hekili/files/13506025/no_spindle.txt)

**Comment by Hekili** [comment]
Take a snapshot at the time you think spindle should be recommended but it is not.  So that means around 21 seconds into the fight, several seconds/GCDs after Tyrant is summoned, if we're comparing to the sim.  I'll make it more flexible.

**Comment by xcsyx** [comment]
The snapshot I attached here, and the one in discord are the Hekili opener continuing after with no spindle visibly recommended. I can make another one of like a 5 minute dummy push if needed.

**Comment by Niquity** [comment]
> Take a snapshot at the time you think spindle should be recommended but it is not. So that means around 21 seconds into the fight, several seconds/GCDs after Tyrant is summoned, if we're comparing to the sim. I'll make it more flexible.

https://pastebin.com/VK7Fcdn8 Snapshot I took. Used spindle a few seconds after Tyrant
