### ISSUE TITLE
[REC] [Survival Hunter] Range checking does not work for Butchery & Carve

### ISSUE THREAD

**Issue by PoroKingWin** [Hekili/hekili#3028]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Both Butchery & Carve always return nil when checked with IsSpellInRange(). I think this is due to them not being targeted spells despite having range values. 

Survival has a few 8yd options with Raptor Strike, Mongoose Bite & Muzzle. Even though Aspect of the Eagle is rarely taken currently, it has the potential to increase the range of Raptor Strike & Mongoose Bite to 40yds so probably a Muzzle angle.

Also thanks for getting to the Havoc range stuff so quickly, I always appreciate your work.

### How to Reproduce

1. Enter game as a Survival Hunter using Carve or Butchery for range checking
2. Stand amongst multiple enemies
3. See active_enemies be 1 despite having >1 valid enemies in range

### Snapshot (Link)

https://pastebin.com/29HQ7dpc

### Raidbots Sim Report (Link)

N/A

**Comment by Ktuky** [comment]
I'm having a same problem on survival.

**Comment by tpfleck** [comment]
This is still a problem where Butchery / Carve aren't being recommended in the AOE rotation

**Comment by tpfleck** [comment]
Not sure what change was made between v1.0.17 -> v1.0.19, nothing that I can see when comparing the diff, but butchery is now being recommended. This is resolved on my end.

**Comment by tpfleck** [comment]
Okay now I'm really confused. Same dummies, went back 30 min later and it isn't being recommended now.

**Comment by Hekili** [comment]
Should be fixed in 1.0.19a.
