### ISSUE TITLE
[REC] MW Monk - Ancient Teachings Buff Maintenance

### ISSUE THREAD

**Issue by FistweavingHero** [Hekili/hekili#3029]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The spell priority profile for MW Monks does not attempt to maintain the Ancient Teachings buff (15 Sec duration), when the Ancient Teachings Talent is selected.

The buff can be applied by casting Faeline Stomp or Essence Font. 

The priority listing should identify when the buff is about to expire, or has expired, and prioritise above all else the spell(s) required to re-apply the buff. 
You would first attempt to re-apply the Ancient Teachings buff by using Faeline Stomp. If Faeline Stomp is on CD, you would use Essence Font. 

A "Fistweaver" would never want to proceed any further in its rotation unless it has the Ancient Teachings buff up. 
If both Faeline Stomp & Essence font are on Cooldown as the Ancient Teachings buff expires, then they should immediately become a priority once any one of them is off CD. 

### How to Reproduce

.1 Enter game as MW Monk
.2 Select Ancient Teaching talent
.3. Select Faeline Stomp talent
.4 Select [Faeline Stomp Prevent Overlap] in the MW Core Hekili Settings.
.5 Cast Faeline Stomp or Essence Font on a target to apply Ancient Teachings Buff
.6 After 15 seconds, when the buff expires. Hekili makes no attempt to prioritise its re-application. 

### Snapshot (Link)

https://pastebin.com/DDNbLVa7

**Comment by Hekili** [comment]
Have you tried this with Save Faeline unchecked in the options?  It's actually labeled `Faeline Stomp: Prevent Overlap`.

**Comment by FistweavingHero** [comment]
Yes. If that option is unchecked it will prioritise Faeline Stomp at every opportunity when it is off Cooldown. 

This would prevent the Ancient Teachings from ever dropping.

However, that is a very _blunt_ fix.  It would burn mana rapidly, and causes Faeline Stomp to be prioritised ahead of other far more suitable CDs in any given occasion. For example, If you already have the Ancient Teachings Buff - One wouldn't want to re-apply a Faeline Stomp ahead of Risking Sun Kick just because Faeline Stomp is off CD.

**Comment by oversoe** [comment]
The APL for mitweaver is poop. It recommends you using chi burst all the time too 😂

but then again, healers aren’t prioritized

**Comment by Hekili** [comment]
> The APL for mitweaver is poop. It recommends you using chi burst all the time too 😂
> 
> but then again, healers aren’t prioritized

A strange way to request changes.  Try again, if you have a productive request.

**Comment by oversoe** [comment]
Sorry, not trying to offend, I know if I want a change, you usually change it within one day😊👍 
Was just trying to be witty 😑
The addon is invaluable for me, and I would be a crappy player without it 😂

**Comment by Hekili** [comment]
This should be addressed with 1.0.16-beta3 forward.
