### ISSUE TITLE
Issue on Havoc opener -  wrong opener and the hunt is not suggested

### ISSUE THREAD

**Issue by N30Exca** [Hekili/hekili#3031]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I was play with my H DH when i noticed that the opener for the class was not correct.
After Immolation Aura is popped if A Fire Inside did not proc Felblade should be suggested but it only rarely suggested, after that Eye Beam should be suggested and then The Hunt into a fel rush.

What is suggested instead is Immolaton Aura>Sigil of Flame>Fel Rush>Immolaton Aura>Eye beam

### How to Reproduce

1-Enter the game
2-pop Immolation aura

### Snapshot (Link)

https://pastebin.pl/view/804d0ea3

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6XYs63gJdNjGQrikBXoDd6

### Contact Information

n30exca

**Comment by Hekili** [comment]
There are 5 open tickets about Demon Hunters and one is specifically about the opener.  Please add your information to an existing ticket.
