### ISSUE TITLE
BM Opener is incorrect with AoE talents

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3033]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

ST talent opener recommends barb-barb-call
AoE opener recommends Call

They ought to be the same as per the class guides, this is new behaviour since I played last night.

### How to Reproduce

Take AoE talents and pull a single target encounter (M+ boss, raid boss, dummy, etc).

### Snapshot (Link)

https://pastebin.com/CbuPzYHT

**Comment by Hekili** [comment]
@syrifgit Is this ticket still an issue?

**Comment by syrifgit** [comment]
Yes. Removing the Scent of Blood talent condition from barb shot fixes it. Once you remove that, it recommends double barb shot opener for every talent build as per the class guide, confirmed by Azortharion on the hunter discord below. He basically said the sim is wrong.

Syrif
OP
 — 12/04/2023 10:41 AM
Seems like the sim has somewhat recently changed to not recommend double barb opener on a single target when you're in AoE talents (Such as an m+ boss or a raid boss where you're assigned to be paddy-mcpad). 
https://www.raidbots.com/simbot/report/kS4ECnigSPEQgpybPxUbBf

But the guides still say double barb opener for AoE talents. What is the correct behaviour? 

Azortharion — 12/04/2023 12:43 PM
The correct behaviour is that of the guide.

**Comment by syrifgit** [comment]
Looks like you only did it in the cleave priority, but it should be the same logic in the ST priority as well. You still want to open up with 2 barbs even with AoE talents on ST (like a dungeon boss).

**Comment by melina3** [comment]
Have the same problem with aoe.not flashing at all. it's not fixed yet

**Comment by Hekili** [comment]
> Have the same problem with aoe.not flashing at all. it's not fixed yet

I don't know what flashing has to do with anything.

I've applied the same fix to single-target (commit is mislabeled, but the Scent of Blood check is gone).

**Comment by syrifgit** [comment]
Will confirm today after server reset. :)

**Comment by syrifgit** [comment]
All 4 of the current talent builds now show the correct opener

**Comment by syrifgit** [comment]
This appears to be broken again across all builds.

https://pastebin.com/LWVAENzc

Sims still showing double barb with the same talents. Looks like the scent of blood condition is back?
https://www.raidbots.com/simbot/report/qaRAgFk7WAM6KhrifDSn7W

**Comment by Hekili** [comment]
@syrifgit This is what I fixed by removing checks for Scent of Blood, no?

**Comment by syrifgit** [comment]
Yes but resetting my priority pack fixed it, I must've been playing with something. False alarm.
