### ISSUE TITLE
Vanish / BtE not recommended Vanish not on cd

### ISSUE THREAD

**Issue by AA16064** [Hekili/hekili#3035]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Its since 1-2 days that vanish is really often not longer rcommended in my priority list. This also makes BtE not recommended and you loose the burst window. Really often Vanish is on CD and will not longer recommended playing

### How to Reproduce

Enter the Game
go on Dungeon single Target dummy for Example
Follow recommendations after the first recommendations and the first vanish used to burst it will not longer recommened vanish + bte

### Snapshot (Link)

https://pastebin.com/B9HcCXqK

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vZUmb5WYFRXAYzmW5xjyjC

### Contact Information

Discord triplehxh (530000125247094810)

**Comment by AA16064** [comment]
I think i found the issue but i leave it open because i definitly was not chaning this setting??

Under Ability > Outlaw > Vanish > the select box for Boss Encounter only was set 

Could this setting be changes from a new version? I was 100% not in the settings and then it makes sence that i did not get a good recommendation

**Comment by Hekili** [comment]
I haven't altered that setting in any way.

**Comment by AA16064** [comment]
Just wanted to be sure that no others has the same issue.

Thanks anyway

**Comment by Hekili** [comment]
Thank you!
