### ISSUE TITLE
[Balance] Unable to get Barkskin to show in recommendations

### ISSUE THREAD

**Issue by notwiththem** [Hekili/hekili#3036]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After adding Barkskin to the priority list while playing Balance it is currently never recommended.  

In the snapshot it shows the reasoning:  
```The action (barkskin) is unusable at (0.00 + 0.00) because player is not tanking right now.``` - despite having recently received damage and meeting all other obvious display conditions

### How to Reproduce

1. Add barkskin to priority list while playing Druid Balance
2. Meet display condition for the recommendation
3. Review snapshot

### Snapshot (Link)

https://pastebin.com/hVBSmwGe

### Additional Information

Discussed this in discord recently and was advised to lodge ticket

**Comment by Hekili** [comment]
The restriction on incoming damage and tanking will apply only to tank (Guardian) in 1.0.13.
