### ISSUE TITLE
[BUG] Hekili not Loading when logging into holy priest spec

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#3039]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili will not load when logging in as holy priest spec.

Work around: Switch to shadow priest then back to holy priest

### How to Reproduce

1. Exit game as holy priest.
2. Open the game and log into holy priest

### Player Information (Link)

https://pastebin.com/Q7Vsn8qH

### Error Messages (Link)

https://pastebin.com/fp5aiTek

### Contact Information

Lemonlust

**Comment by Hekili** [comment]
This appears to be resolved.
