### ISSUE TITLE
Unholy dk

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#304]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is. Wonder if u have time to check apl on unholy dk festermight spread doesnt want to spread before all big cds prio order seem little off, if its just possible to check if all is in order! Best addon<3

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen. Festermight spread dont wanna spread before major cd with bote

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.https://pastebin.com/C5m04MGU

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Tobbelainen** [comment]
Bump

**Comment by Hekili** [comment]
The Festermight spread is more or less antiquated at this point.  You'd need to post complete snapshots consistent with the ticket instructions if you want this to go anywhere.

**Comment by Tobbelainen** [comment]
hmm ok just wonder something more quick sometimes outbreak is recommended 2 times haven't had time to reproduce and put a snapshot when i´m  raiding but is this and update miss or global cd bug maybe or shall i just try hit a dummy and send a new issue when i got snapshot? or is it a apl miss?,  great addon <3

**Comment by Tobbelainen** [comment]
Donating link is appreciated to cant find any=)
