### ISSUE TITLE
[REC] Holy Priest recommending holy fire/Empyreal Blaze/Chastise while spells on cooldown

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#3040]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Recommending Holy Fire while on cooldown, Sometimes recommending other things on cooldown such as Empyreal Blaze or Chastise. This issue does not happen in valdrakken training dummies

![WoWScrnShot_120623_004949](https://github.com/Hekili/hekili/assets/7343912/8c66fe52-e36e-4726-9c6a-18054299b125)

### How to Reproduce

1. Queue into a dungeon and follow recommended spells.

### Snapshot (Link)

https://pastebin.com/x31nmknw

### Additional Information

Attempting to use Pause Hotkey results in error
https://pastebin.com/QwUwfVV3

### Contact Information

Lemonlust

**Comment by Hekili** [comment]
Fixed in 1.0.12 via PR.
