### ISSUE TITLE
[REC] Vivify fills up all future casts when vivacious vivification buff is up

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3043]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Whenever Vivacious Vivification buff is up, I want to cast Vivify.
However hekili doesn't know that Vivify consumes the buff

### How to Reproduce

Add Vivify to APL
Add conditions: buff.vivacious_vivification.up
Wait for buff to appear

### Snapshot (Link)

https://pastebin.com/wVjZNR7Q

### Additional Information

Healer spec, can't really link Raidbots

**Comment by oversoe** [comment]
![billede](https://github.com/Hekili/hekili/assets/95752910/69200f2d-b594-443b-8b9c-40c9c7ac1c3b)

**Comment by Hekili** [comment]
Fixed in next release.
