### ISSUE TITLE
[REC] Buff tea_of_plenty is untrackable for Mistweaver

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3044]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The buff Tea of Plenty is untrackable.
There's 5 seperate buffs (Renewing Mist, Rising Sun Kick, Vivify, Enveloping Mist, Essence Font)

### How to Reproduce

Have "tea of plenty" talented.
Use "Thunder focus tea"
Gain 2 buffs.

### Snapshot (Link)

https://pastebin.com/hRYpYvpk

### Additional Information

Healer spec - no raidbots

**Comment by oversoe** [comment]
![billede](https://github.com/Hekili/hekili/assets/95752910/b6a13c5c-1bb4-43d9-a47f-aa3ad8f9f903)

**Comment by oversoe** [comment]
![billede](https://github.com/Hekili/hekili/assets/95752910/d7b159ea-0c63-476f-b912-5cc0e38215ab)

**Comment by Hekili** [comment]
Do you have the buff Ids for each version?

**Comment by Hekili** [comment]
These will be tracked as `tea_of_plenty_ef`, `_rm`, `_rsk` as well as `tea_of_serenity_em`, `_rm`, and `_v` in the next release.
