### ISSUE TITLE
[REC] Outlaw - addon rec using on-use trinkets while in stealth which breaks stealth granting no subterfuge 

### ISSUE THREAD

**Issue by aycheff** [Hekili/hekili#3046]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon is recommending to use trinket if off CD and you are in stealth/vanish as the next ability. However, doing so as a outlaw rogue, using an on-use trinket while stealth (from stealth itself or using vanish, seems to mostly happen with Vanish) will take you out of stealth and not grant subterfuge, and thus not being able to go into a crackshot window.

### How to Reproduce

1. Enter game as outlaw rogue
2. Enter combat with trinkets not on cooldown
3. Start your opener (don't use trinkets)
4. Use vanish, addon will suggest to use trinket instead of ability.

### Snapshot (Link)

https://pastebin.com/Cxfak6kA

**Comment by Hekili** [comment]
Will be resolved in 1.0.13.
