### ISSUE TITLE
[REC] Purge is not beeing recommended (Elemental Shaman)

### ISSUE THREAD

**Issue by Scatrat** [Hekili/hekili#3047]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Elemental Shaman, I expect the addon to recommend Purge when my enemy target has dispellable magic buffs. However, the addon doesnt recommend Purge at all. The snapshot says the following:

        4.   greater_purge ( default - 2 )
        The action (greater_purge) is unusable at (0.00 + 0.00) because required debuff (dispellable_magic) not active.
        Time spent on this action:  0.14ms
        TimeData:Elemental PVP 2111 Jason-default-2:greater_purge:0.14:Ability Known, Enabled(0.03):Post-TTR and Essential(0.06):Post Cycle(0.00):Post Usable(0.05)

...even my enemy target has dispellable magic buffs active as stated above:

target_buffs:
   264420 - *soldat_der_allianz                      -   1 - 3600.00
   269083 - enlisted_c [MISSING]                     -   1 - 3600.00
   201671 - *blutiges_fell                           -   1 - 3600.00
   397734 - *wort_eines_wrdigen_verbndeten           -   1 - 3600.00
      774 - *verjngung                               -   1 - 12.31 
     8936 - *nachwachsen                             -   1 - 10.23 

For example Regrowth and also Mark of the Wild (which is not listed here).

### How to Reproduce

1. Start a duel oder open world pvp fight against an enemy with dispellable magic buffs, for example druid (Regrowth, Mark of the Wild).
2. Let him buff/hot himself
3. Purge will never be recommended, even its on the highest prio in default

### Snapshot (Link)

https://pastebin.com/EuGTMSBt

### Contact Information

JasonX#5321

**Comment by Hekili** [comment]
Fixed in 1.0.13.
