### ISSUE TITLE
[REC] Can't track buff Flow State on Preservation Evoker

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3049]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unable to track the buff "flow state" that is enabled by empowered spells.
Its a talent.
Spell ID 385696 I think

### How to Reproduce

Use an empored spell that enabled flow state.
Buff appears
Cant track it with buff.flow_state.up

### Snapshot (Link)

https://pastebin.com/RnXGArKf

### Additional Information

Healer spec

**Comment by Hekili** [comment]
Will be available in 1.0.13.

**Comment by oversoe** [comment]
You da man! 😊
