### ISSUE TITLE
Demonology warlock movement 

### ISSUE THREAD

**Issue by wow1989** [Hekili/hekili#305]
The toggle fireball off while moving is an AWESOME addition to fire mage

Can you do the same for demo warlock? Having trouble tracking what is instant and not when I’m moving, would love this option!

Thanks

**Comment by Hekili** [comment]
I am thinking about this.  The thing I'm uncertain about is that it means you're not getting optimal recommendations while you're moving (i.e., should I try to stop ASAP and start hardcasting?  probably).

**Comment by wow1989** [comment]
Certainly stop moving is always optimal, the global is so short to get dps out is think it has to be a net gain.

Additionally I’m having trouble making the decision to instant cast demon bolts or not... certainly with 3 or less shards. What about 4? 5? 

And prioritizing spells while moving
Instant dread stalkers
Implosion
Soul strike
Etc..

I’m really at a loss without an aid

**Comment by Hekili** [comment]
The problem is, for some specs, possibly including Demo, using a suboptimal thing could potentially cause a delay.  It's not good to not be casting, but doing something suboptimal due to movement can have an opportunity cost as well.

I'll potentially make this an option, but I'm still debating.

**Comment by Hekili** [comment]
Not going to pursue this at this time.
