### ISSUE TITLE
[REC] OUTLAW - Roll the Bones being recommend while in stealth window (without the chance of them falling off)

### ISSUE THREAD

**Issue by aycheff** [Hekili/hekili#3050]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When doing the outlaw rotation, hekili is recommending to use roll the bones during crackshot (stealth window). Even when there is enough time within your stealth window to fit another GCD in like Between the Eyes or something and the buff will NOT fall off, it will recommend Roll the Bones even though you can reroll after your stealth window without the buffs falling off. 

Here is a screenshot of a scenario. Things happening in this screenshot: I have 2 buffs up from roll the bones with 12 seconds left. The addons is recommending to reroll even though I have 2 seconds left on my subterfuge (stealth window). Unless the buff is going to fall off, you should never reroll inside your stealth windows.

![Image 12-8-23 at 9 01 PM](https://github.com/Hekili/hekili/assets/22590255/48ab4c1a-c1f4-4942-bff8-c171722dab4f)

### How to Reproduce

1. Enter combat as outlaw rogue with buffs from roll the bones
2. Enter your stealth window with RTB off CD.
3. Addon will occasionally recommend to reroll inside the stealth window even though the buffs would not fall off.

### Snapshot (Link)

https://pastebin.com/JTbciUHD

**Comment by chevyn11** [comment]
I see whats happening, its essentially these points in the RTB priority from the rogue discord and they make up the `rtb_reroll` variable in the APL:
![image](https://github.com/Hekili/hekili/assets/111624332/d9d3b053-5fe8-40db-b46e-c1f315b227fd)
in hekili:
![image](https://github.com/Hekili/hekili/assets/111624332/da4db23c-e58c-444f-84bb-8f2b57c7539b)


You have 2 buffs active and you have loaded dice up (from adrenaline rush). Using rtb here guarantees you 3 rtb buffs (2 from loaded dice + 1 from your t31). I think this has been found by the rogue theorycrafters to be either good or neutral to do even within stealth so the recommendation is correct :D

**Comment by aycheff** [comment]
While yes that’s true, most will recommend not rolling in your stealth window. It’s bad practice. I can make the decision on my own fo course but I use hekili to reduce as much of that as I can.

 Is there a way I can edit the hekili APL to instead not recommend rerolling in stealth windows if the buffs won’t drop, and instead reroll before if time left on buffs is <7s and vanish/sd is ready as is general best practice.

**Comment by aycheff** [comment]
> I see whats happening, its essentially these points in the RTB priority from the rogue discord and they make up the `rtb_reroll` variable in the APL: ![image](https://private-user-images.githubusercontent.com/111624332/289234292-d9d3b053-5fe8-40db-b46e-c1f315b227fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTgwNjgsIm5iZiI6MTcwMjA5Nzc2OCwicGF0aCI6Ii8xMTE2MjQzMzIvMjg5MjM0MjkyLWQ5ZDNiMDUzLTVmZTgtNDBkYi1iNDZlLWMxZjMxNWIyMjdmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwNDU2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDY5M2EyNTVjZmNjN2NjZTVhMDFlNWE5ZTkzOTJkODdlNTM1NzQ0MzllNDdjNzdkN2E3NmEwNWRhODZjNzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gLuPXbinC-4NX-6Mt3ax55UR-gH3bfdkCSpcPB5TlLw) in hekili: ![image](https://private-user-images.githubusercontent.com/111624332/289234455-da4db23c-e58c-444f-84bb-8f2b57c7539b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTgwNjgsIm5iZiI6MTcwMjA5Nzc2OCwicGF0aCI6Ii8xMTE2MjQzMzIvMjg5MjM0NDU1LWRhNGRiMjNjLWU1OGMtNDQ0Zi04NGJiLThmMmI1N2M3NTM5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwNDU2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTU1OWVhZDI3ODkyMzk2ZGRkZGYyNGFiMDQwYWQ2NzhhM2Y4ODdhYTBhMGI5ZjcyYTMxZjY2YmM5NGRlZGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R4RnhuJeo3907bk8WMvyFRXDGxWbPcFU8cqKMnQdIZo)
> 
> You have 2 buffs active and you have loaded dice up (from adrenaline rush). Using rtb here guarantees you 3 rtb buffs (2 from loaded dice + 1 from your t31). I think this has been found by the rogue theorycrafters to be either good or neutral to do even within stealth so the recommendation is correct :D


Sure, but you can reroll after and not potentially miss a damage ability in your window. And While yes that’s true, most will recommend not rolling in your stealth window. It’s bad practice. I can make the decision on my own fo course but I use hekili to reduce as much of that as I can.

 Is there a way I can edit the hekili APL to instead not recommend rerolling in stealth windows if the buffs won’t drop, and instead reroll before if time left on buffs is <7s and vanish/sd is ready as is general best practice.

**Comment by chevyn11** [comment]
Sure, you can add `& ! ( buff.subterfuge.up | buff.shadow_dance.up )` to the rtb_reroll variable under the `Action Lists` tab, so it will look like this:

![image](https://github.com/Hekili/hekili/assets/111624332/f9f477f7-99c0-4093-97e1-23ab761bc45d)

Although I take no responsibility for what other interactions this might cause 😄
The rtb_reroll variable is also used for KIR rules.

**Comment by Hekili** [comment]
It's worth making the same adjustments to your sim profile and testing whether it proves to be more performant.  If so, you can ticket SimC to avoid making that refresh and all our tools will be in sync.

edit:  I don't see a positive/productive difference -- I made it never reroll in Subterfuge or Shadow Dance.

https://www.raidbots.com/simbot/report/6BKc4EvdbdcG9jphZaW8An/simc

![image](https://github.com/Hekili/hekili/assets/9438134/36d529a1-4121-408f-9378-bd15ea75cbb0)

**Comment by Hekili** [comment]
I'm going to address this with a user preference option:

![image](https://github.com/Hekili/hekili/assets/9438134/137c83d2-da74-45d1-9cb2-cbaefd56741f)
