### ISSUE TITLE
BM Hunter - Recommend [Spirit Mend]

### ISSUE THREAD

**Issue by GigaToons** [Hekili/hekili#3051]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello! I was curious if Hekili could recommend Spirit Mend if using a Tenacity Pet with the ability. Other defensives such as Fortitude of the Bear are available, would love to add it as a defensive reminder. =) 

### Additional Information

I double checked this ability was not listed on the abilities list or as another name, i.e. 'Command Pet Ability'.

**Comment by Hekili** [comment]
This will be available in next release.

**Comment by GigaToons** [comment]
You are awesome, thank you! Have a great weekend!!
