### ISSUE TITLE
[BUG] Assassination rogue funnel aoe -> target does not stay checked

### ISSUE THREAD

**Issue by RogueBeard** [Hekili/hekili#3052]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When ticking the funnel aoe -> target check box in assassination rogue>core. It unchecks when changing other settings or moving page and coming back. not allowing to prioritize main target. 

### How to Reproduce

1enter game as assassination rogue
2open hekili settings
3select assassination>core
4tick the funnel aoe->target check box
5change tab or settings and the funnel aoe unticks.

### Player Information (Link)

https://pastebin.com/d88sAuhP

### Error Messages (Link)

https://pastebin.com/d88sAuhP

**Comment by Hekili** [comment]
I'm not able to replicate this.  Is there any chance that you've macro'd the toggle somewhere and don't realize you're turning it on and off?

**Comment by RogueBeard** [comment]
I dont have it macrod anywhere. ill reinstall and see if it resolves.

**Comment by RogueBeard** [comment]
resolved with reinstalling addon. Sorry! didnt think to do that first.
