### ISSUE TITLE
[REC] Prev_gcd doesn't work for Preservation Evoker

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3055]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When adding prev_gcd.1.echo or prev_gcd.1.living_flame, the statement never returns true, and spell aren't being prioritized because of this.

### How to Reproduce

Here my an APL:

Cast reversion if:
essence<2 & !cooldown.echo.ready & prev_gcd.1.echo
Or if the following is true:
prev_gcd.2.echo & !prev_gcd.1.living_flame & !prev_gcd.1.verdant_embrace & !prev_gcd.1.dream_breath & !prev_gcd.spiritbloom & !prev_gcd.1.emerald_blossom

Spell never pops up because none of the spells appear as being true (being the previous gcd).

### Snapshot (Link)

https://pastebin.com/WNHr0nxY

### Additional Information

Healer spec

**Comment by Hekili** [comment]
You provided a snapshot of your Cooldowns display and Echo isn't a cooldown.

You also have something wrong with your Cooldowns 7th entry per the snapshot's warnings.

**Comment by Hekili** [comment]
prev_gcd starts in the current combat episode, so if time is 0 (you are out of combat), it will return false.

**Comment by Hekili** [comment]
I'll be removing/relaxing the combat requirement and we'll see how it goes.
