### ISSUE TITLE
[BUG] Hekili freezes when talented "Cycle of Life" and "Emerald Blossom" is next in rotation (PRESERVATION EVOKER)

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3058]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Whenever emerald blossom appears the addon freezes at previous spells.

### How to Reproduce

1. Cast your CDs and prioritized spells
2. Whenever you should cast Emerald Blossom it freezes
3. 

### Player Information (Link)

https://pastebin.com/RB0Y2KNg

### Error Messages (Link)

https://pastebin.com/dvewUsbH

**Comment by Hekili** [comment]
Can you reset your priority to default?  It's hard to tell what bugs are related to your customization vs. problems with the addon itself.

I do see that `cycle_of_life_count` is missing internally and have added it back.

You also have errors for stuff like `talent_auroboros` which is incorrect syntax AND misspelled (I think).

**Comment by oversoe** [comment]
I’ve since fixed auroboros syntax, but I’m gonna try if the cycle of life bug is causing it

Still fiddling around with finding the best apl for mme 😊
