### ISSUE TITLE
[FEATURE] Arcane Explosion for Arcane Mage is never cast because it is always out of range

### ISSUE THREAD

**Issue by nlewis2142** [Hekili/hekili#3060]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Made this issue as a feature request since there isn't currently an Arcane Explosion recommended in the default priority.

Arcane Explosion is never recommended, even when added to a priority list, since its usable condition is never met. Would like to see the usable condition fixed so the spell can at least be used, and then I can determine whether to enable the ability, assign to a toggle, etc.

### Additional Information

Taking a snapshot lists the following reason on every arcane_explosion entry:
```
The action (arcane_explosion) is unusable at (0.38 + 0.00) because target out of range.
```

Some quick debugging points to [Line 1326 in Dragonflight/MageArcane.lua](https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/MageArcane.lua#L1326)
```lua
arcane_explosion = {
    -- ...
    usable = function () return not settings.check_explosion_range or target.maxR < 10, "target out of range" end,
    -- ...
}
```

If I remove that line, Arcane Explosion functions as expected but will recommend even when standing at range.

It looks like there's been some [changes recently (Move to LibRangeCheck-3.0)](https://github.com/Hekili/hekili/commit/94134144fb82781a728b7390e80d4941e7a31cbd) that have left the spell in a state where it [references a setting that isn't registered anymore](https://github.com/Hekili/hekili/blob/dragonflight/Dragonflight/MageArcane.lua#L2248) and compares range on a property of the target that returns `30` even when you're right next to the target.

I figure there are some complications with making an accurate range check on Mage, however it would be preferable to have a usable ability that I can enable or disable recommendations for rather than the ability just being completely unusable -- then I can assign the ability to a toggle and at least use hotkeys to determine whether I am in range.

**Comment by Hekili** [comment]
I will re-enable the Arcane Explosion: Range Check option since detecting distance of hostiles has been re-enabled.  You'll find it in /hekili > Arcane after next update.
