### ISSUE TITLE
Arcane Mage Single Target Priority Rotation is not working

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#3061]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Arcane mage rotation is only recommending arcane blast. It will recommend to cast mana gem even when one is created already.

### How to Reproduce

Login to game as a mage.
Take default raid single target talents that are recommended on WoWHead for Arcane Mage.
(B4DArSxcnei16P8xFL3rzzOyRSEUSDJSkigIJERSIRCkEk0SCAAAAAAAAAAAISSSSkkkEIA) - Talent Build
Pre-cast conjure mana gem
Begin Rotation

### Snapshot (Link)

https://pastebin.com/mp1jGQ9h

### Additional Information

Not once did the rotation recommend using Touch of the Magi or Arcane Surge.

Prior to the most recent priority update the rotation appeared to be working properly.

### Contact Information

Discord: roghar.

**Comment by TobiasGabel** [comment]
I'm experiencing the same since the most recent update. I assume it is related to the condition on some trinkets added in commit 549064bafbe1a6657969f5ad429e51f548cda552 

So when you have the right equipment it might work fine.
Disclaimer: I'm just guessing as my lua knowledge is even more limited than my arcane knowledge ;)

**Comment by Hekili** [comment]
I'll need the complete snapshot.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
This may be an artifact of other trinket-related code; the next beta release may address it.

**Comment by ghost** [comment]
> This may be an artifact of other trinket-related code; the next beta release may address it.

That would be amazing! Do I need to supply another "Snapshot"?

**Comment by ghost** [comment]
https://pastebin.com/WitnB3Xz

Here's the re-do. My apologies, first time using pastebin and appears the first one I linked didn't copy correctly.

**Comment by Hekili** [comment]
@Ashance Test using the latest beta version, please.

https://github.com/Hekili/hekili/releases/download/v10.2.0-1.0.16-beta2/Hekili-v10.2.0-1.0.16-beta2.zip

**Comment by MKosco2** [comment]
I am experiencing same issue. 
I tried the 1.0.16 patch and it did not help. Single target rotation is not entering spark phase.
here is my snapshot. 
https://pastebin.com/7hEGZd1G
and i am attaching snipe from wowhead and marking on the rotation timeline, when i made the snapshot. 
![obrázok](https://github.com/Hekili/hekili/assets/153763041/4611f66f-c8ef-4673-b95d-724cc5131234)

thanks a lot for your work.

**Comment by ghost** [comment]
> @Ashance Test using the latest beta version, please.
> 
> https://github.com/Hekili/hekili/releases/download/v10.2.0-1.0.16-beta2/Hekili-v10.2.0-1.0.16-beta2.zip

Just tested and basically the same thing @MKosco2 mentioned. It never enters Spark rotation. Current Beta build only casts Evocation, Arcane Blast, Arcane Missles and random Arcane Barrage. Arcane Surge, Radiant Spark, Mana Gem (Consumable), Presence of Mind, and Touch of the Magi are never casted.

https://pastebin.com/mxcAnKnr

**Comment by kapteinRick** [comment]
Having the same issue

**Comment by ghost** [comment]
I'm beginning to notice there is an issue with the AoE rotation also. It will not enter spark rotation

**Comment by Alanwakeftw** [comment]
Can also confirm this issue on Arcane spec, right now it just makes you spam Arcane Blast till you run out of mana.

**Comment by Akr0n** [comment]
This issue opened by me should be related https://github.com/Hekili/hekili/issues/3059

**Comment by kayftww** [comment]
Same issue here. Not entering on spark roation and recommends "conjure mana gem" on precombat when already have it.

**Comment by Hekili** [comment]
@kapteinRick @Ashance @Alanwakeftw @Akr0n @kayftww 
Please provide snapshots using the latest beta so I have data to look into it.

**Comment by ghost** [comment]
> > @Ashance Test using the latest beta version, please.
> > https://github.com/Hekili/hekili/releases/download/v10.2.0-1.0.16-beta2/Hekili-v10.2.0-1.0.16-beta2.zip
> 
> Just tested and basically the same thing @MKosco2 mentioned. It never enters Spark rotation. Current Beta build only casts Evocation, Arcane Blast, Arcane Missles and random Arcane Barrage. Arcane Surge, Radiant Spark, Mana Gem (Consumable), Presence of Mind, and Touch of the Magi are never casted.
> 
> https://pastebin.com/mxcAnKnr

@Hekili the pastebin link in my above reply is the data from the beta build

**Comment by Hekili** [comment]
-beta3 will have a new test fix.  I will also need to get new snapshots and Raidbots quick sim links for comparison going forward.

**Comment by MKosco2** [comment]
I tried Beta3 build and the suggested rotation is better. On dummies, single target openner and spark rotation works correctly for me. Thanks a lot

**Comment by Akr0n** [comment]
> I tried Beta3 build and the suggested rotation is better. On dummies, single target openner and spark rotation works correctly for me. Thanks a lot

I can confirm that the latest beta works fine! https://pastebin.com/gitbFxZd

**Comment by kapteinRick** [comment]
Arcane; Primary - Nether Tempest(0.65), Arcane Blast(1.96), Arcane Blast(3.31)

@Hekili here is the snapshot, but it seems to me to be better with the .16 beta that has released. Atleast the ST rotation.

**Comment by ghost** [comment]
@Hekili Rotations are looking a lot better in the Betav3! Thanks for all your hard work!

https://pastebin.com/0HYkFRiL   -   Single Target

B4DArSxcnei16P8xFL3rzzOyRSEUSDJSkigIJERSIRCkEk0SCAAAAAAAAAAAISSSSkkkEIA  - Single Target Build

https://pastebin.com/R6kRx3Yp   -   AOE

B4DArSxcnei16P8xFL3rzzOyRKRIl0QSOQSKOAISERSkEBSSCJtkAAAAAAAAAAAAikkkQSSiQCA  - AOE Build

Only thing I noticed compared to the current live build is that Trinkets/On-Use Weapons are not in the rotation anymore. No big deal just means I can't forget them. This also applies to Frost spec, which works in the Live Build.

**Comment by GRiiM-Aesthetics** [comment]
> @Hekili Rotations are looking a lot better in the Betav3! Thanks for all your hard work!
> 
> https://pastebin.com/0HYkFRiL - Single Target
> 
> B4DArSxcnei16P8xFL3rzzOyRSEUSDJSkigIJERSIRCkEk0SCAAAAAAAAAAAISSSSkkkEIA - Single Target Build
> 
> https://pastebin.com/R6kRx3Yp - AOE
> 
> B4DArSxcnei16P8xFL3rzzOyRKRIl0QSOQSKOAISERSkEBSSCJtkAAAAAAAAAAAAikkkQSSiQCA - AOE Build
> 
> Only thing I noticed compared to the current live build is that Trinkets/On-Use Weapons are not in the rotation anymore. No big deal just means I can't forget them. This also applies to Frost spec, which works in the Live Build.

@Ashance What is Betav3? Did you just update the add on or did you import a different rotation profile into Hekili? 

Thanks in advance!
