### ISSUE TITLE
[REC] trinket.t2.cooldown.remains always returns 0

### ISSUE THREAD

**Issue by syrairc** [Hekili/hekili#3062]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Per my comments in #pack-development channel, trinket.t2.cooldown.remains seems to always return 0. This means certain trinkets are never recommended if they rely on your other trinket to be on cooldown. 

In the example provided, I'm on an augmentation evoker with Belor'relos in trinket slot 1, and Balefire Branch in trinket slot 2. Belor'relos will not be used unless trinket 2 cooldown is > 20 seconds (or one of the other conditions are met (they aren't in my example.)

In my example there are two snapshots, the first one is balefire in trinket slot 1, belor'relos in trinket slot 2. Using balefire and then following the rotation will result in belor'relos being recommended when we're in the GCD.

The second snapshot has belor'relos in trinket slot 1, balefire in trinket slot 2. Following the same process, putting balefire on cooldown and following the rotation, belor'relos is never recommended. You can see in the snapshot and in the tooltip ingame that trinket.t2.cooldown.remains is always 0. trinket.t1.cooldown.remains works as expected.

### How to Reproduce

1. Equip on-use trinket in trinket slot 2
1. Use trinket 2
2. Observe return value of trinket.t2.cooldown.remains

### Snapshot (Link)

https://pastebin.com/cEymCM3Q

**Comment by Hekili** [comment]
Test fix will be in next beta build.
