### ISSUE TITLE
[OUTLAW]  Ambush icon displayed but shows Keybind for sinister strike

### ISSUE THREAD

**Issue by xxsoco** [Hekili/hekili#3063]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In the rotation it shows the correct ability icon but displays the incorrect key bind.  The key bind shown is for sinister strike. This is new to the latest update.

### How to Reproduce

Enter as Outlaw rogue.
Use talent Hidden Opportunity
Have sinister strike and ambush on non steal bar.
Rotation shows incorrect key bind.

![Error Hekili](https://github.com/Hekili/hekili/assets/21100994/a77168e5-21be-4459-902b-3784122b8007)

### Snapshot (Link)

Outlaw; Primary - Between the Eyes(0.00), Ambush(1.00), My'das Talisman(1.82)

**Comment by Hekili** [comment]
You can manually override any keybind that is detected incorrectly in /hekili > Abilities > Override Keybind Text.
