### ISSUE TITLE
WARRIOR > FURY = Execute is prioritized when SD comes up, thats not the right rotation.

### ISSUE THREAD

**Issue by Metricz27** [Hekili/hekili#3064]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When sudden death comes up rotation fails, it prioritizes execution over the normal priority rotation which follows like this: 

1. Odyn’s Fury
2. Bloodbath (even if overcapping rage)
3. Rampage
4. Bloodthirst (if Rampage was NOT your previous ability OR if you can’t afford Rampage yet)
5. Execute
6. Slam
7. Whirlwind

### How to Reproduce

Sudden death shouldnt be on the priority list because in 10.2 its just a filler

### Snapshot (Link)

https://pastebin.com/cz7WmVC5

**Comment by Hekili** [comment]
Please provide a sim of your character (Raidbots link) for comparison.

**Comment by Zanetsuken** [comment]
Looking at existing guide and the current APL profile - SD is not considered "filler" rather spend it when it procs.
the Wowhead guide mentions that SD procs should be spent as a high priority
