### ISSUE TITLE
[FEATURE] Season of Discovery

### ISSUE THREAD

**Issue by Durron86** [Hekili/hekili#3065]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

could we get Hekili for Season of Discovery?

**Comment by Hekili** [comment]
No, this is not planned.  I may make a few WeakAuras but the priorities are not complex enough to require the work it would take to retailor the addon.
