### ISSUE TITLE
Cannot get Spell Lock interrupt to show on Warlock

### ISSUE THREAD

**Issue by Cager1974** [Hekili/hekili#3066]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I have tried with several warlocks and specs, but cannot get Spell Lock to show.  There are at least 2 different Spell ID's for that spell, depending on if you are using a pet, or using the ability from a sacrificed pet.  There doesn't seem to be any difference for the addon.  I can confirm that the interrupt panel is working as intended on other characters.

### How to Reproduce

1-Have a warlock with the Fel Hunter pet, which provides the Spell Lock as a Command Demon Ability, or gain Spell Lock under the Grimoire of Sacrifice.
2-Enter combat with a spellcaster and wait for an interruptible spell.

### Snapshot (Link)

https://pastebin.com/NvzDZPT5

### Contact Information

micahfloyd@gmail.com

**Comment by Hekili** [comment]
This should be addressed in 1.0.16-beta3 forward.
