### ISSUE TITLE
Ashes of the Embersoul Trinket not recommended

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#3069]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The trinket Ashes of the Embersoul is not recommended first as the sim recommends in double trinket setups. Then when it is not used on the opener it is held until the next AW/FR.

Opener with Branch being recommended. https://pastebin.com/vWcYYksA

Ashes being recommended on second AW/FR. https://pastebin.com/FxXuFrpG

Sim: https://www.raidbots.com/simbot/report/pqKiGKnJgNy5hiexWFX6oS

### How to Reproduce

Ret Paladin.
5 Valk Dummies.

### Snapshot (Link)

https://pastebin.com/vWcYYksA

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pqKiGKnJgNy5hiexWFX6oS

**Comment by Hekili** [comment]
Does it happen with the actual default priority?

Does it change depending on which slot you have which trinket in?

**Comment by Bingo176** [comment]
Not sure if you mean in game or in the sims 

Trinket positions swapped.
https://www.raidbots.com/simbot/report/n2psvcsN1zDcm4mEXDT5is 
https://www.raidbots.com/simbot/report/vPqFJQ67MCbFkJu8hmKZnY 

As for default priority this is with everything reset on auto.  In game either trinket in slot 13 or 14 results in Branch first then Ambersoul held until second AW/FR.

https://pastebin.com/w052qxfY (Ambersoul top slot)
https://pastebin.com/dP7tPkhB (Branch top slot)
