### ISSUE TITLE
[BUG] Error with "Dreambinder, Loom of the Great Cycle / Web of Dreams" equipped

### ISSUE THREAD

**Issue by rockschtar** [Hekili/hekili#3070]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Getting following error with Hekili version v10.2.0-1.0.16 when "[Dreambinder, Loom of the Great Cycle](https://www.wowhead.com/item=208616/dreambinder-loom-of-the-great-cycle)" is equipped:

Hekili/Events.lua:857: attempt to index global 'ability' (a nil value)
[string "@Hekili/Events.lua"]:857: in function `updateGear'
[string "@Hekili/Classes.lua"]:6455: in function <Hekili/Classes.lua:6452>

Locals:
T1 = 208615
T2 = 159610
MH = 208616
isUsable = true
name = "Web of Dreams"
spellID = 427113
tSpell = "dreambinder_loom_of_the_great_cycle"

### How to Reproduce

1. Enter Game with a character that has Dreambinder, Loom of the Great Cycle equipped
2. Error occurs

### Player Information (Link)

https://pastebin.com/ye1EU5u6

### Error Messages (Link)

https://pastebin.com/ym5SkKG1

**Comment by bloerwald** [comment]
Equivalent to #3071.
