### ISSUE TITLE
[BUG] Error with "djaruun_pillar_of_the_elder_flame" equipped

### ISSUE THREAD

**Issue by keflatbn** [Hekili/hekili#3071]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Enter game with Djaruun Pillar of the Elder Flame equipped.

### How to Reproduce

Enter game with Djaruun Pillar of the Elder Flame equipped, error happens direct

### Player Information (Link)

https://pastebin.com/gea4Nj3B

### Error Messages (Link)

https://pastebin.com/aYWRurcD

**Comment by bloerwald** [comment]
Fixed by 435399f2d0e7b6004bc971985d60ca1c595ed662.
