### ISSUE TITLE
[BUG] Keybind Recommendation  with changing stance bars and same abilities

### ISSUE THREAD

**Issue by tance77** [Hekili/hekili#3072]
### Describe the Issue

The keybinds over the recommended abilities seem to malfunction at times. For example I have a bar that changes on ELVUI for my Cat form as a Druid. I have Moonfire and Sunfire both on the human form and cat form (non stealth). It seems to sometimes say use Sunfire from the Human form bar when I am in cat form  and vise versa. I'm not sure what causes it but sometimes it recommends the right keybind

### How to Reproduce

Action Bar with Sunfire and Moonfire on it. Put that same ability on the bar that switches when you have cat form and then you should be able to see it happen. It usually happens after changing dungeons. 

Note moonfire and sunfire need to be on the bar that changes to cat form it can't be on some other action bar that does not change.

### Player Information (Link)

https://pastebin.com/WQp2zWTw

### Error Messages (Link)

NA

### Additional Information

Un-releated resto seems Feral DPS recommendations seems to fail sometimes. I don't have a snapshot sadly.

**Comment by Hekili** [comment]
In your settings, both Moonfire and Sunfire have the same keybindings regardless of bar.  What are you seeing that is different?

**Comment by tance77** [comment]
@Hekili They do not though. I can confirm in cat form as Ctrl + F is Sunfire and in Human form it is Q. I can't remember the other I'm going off my memory right now. I could take some screenshots for you later today.

**Comment by Hekili** [comment]
Here is what is detected in your snapshot:

```
keybinds: 
    adaptive_swarm        = SF  [01]
    barkskin              = 2   [05]
    brutal_slash          = R   [01]
    cenarion_ward         = T   [01], T   [10]
    convoke_the_spirits   = 3   [05]
    dash                  = SMwU[05]
    efflorescence         = V   [01]
    entangling_roots      = S1  [02], G   [05]
    ferocious_bite        = E   [01]
    flourish              = S3  [01]
    frenzied_regeneration = E   [09]
    grove_guardians       = SQ  [01], CF  [10]
    growl                 = T   [09]
    healthstone           = SG  [06]
    heart_of_the_wild     = S6  [02]
    incapacitating_roar   = AF  [02], CF  [09]
    ironbark              = ST  [01]
    ironfur               = V   [09]
    mangle                = Q   [09]
    moonfire              = E   [01], E   [10]
    natures_cure          = AF12[05]
    natures_swiftness     = SF  [01], SF  [10]
    prowl                 = 1   [05]
    rake                  = F   [01]
    regrowth              = CE  [06]
    rejuvenation          = AE  [06]
    renewal               = 5   [02]
    rip                   = V   [01]
    shred                 = Q   [01]
    skull_bash            = S4  [02]
    soothe                = S5  [02]
    stampeding_roar       = SMwD[05]
    starfire              = V   [10]
    sunfire               = Q   [01], Q   [10]
    swiftmend             = F   [01], F   [10]
    swipe                 = R   [01]
    swipe_bear            = R   [01]
    swipe_cat             = R   [01]
    thrash                = SR  [06], R   [09]
    thrash_bear           = SR  [06], R   [09]
    thrash_cat            = SR  [06], R   [09]
    typhoon               = SE  [05]
    ursols_vortex         = S2  [02]
    wild_charge           = ST  [01]
    wild_growth           = 4   [06]
    wrath                 = R   [01], R   [10]
 ```

The bracketed number is the bar page that the detected keybind came from.  Is there a bar or set of bars that are missing?  I don't see any bindings from bars 7 or 8.  Did you change how your bar paging works?

**Comment by tance77** [comment]
> Did you change how your bar paging works?

I use ElvUI. I'm not to familiar with how I would change the paging. However sometimes it will see the keybind on Ctrl + Q for sunfire and other times it will not.  Give me a moment and I can step away from work and try and get you some better info.

**Comment by tance77** [comment]
```
keybinds: 
    adaptive_swarm              = S4  [02]
    bandolier_of_twisted_blades =
    barkskin                    = 2   [05]
    brutal_slash                = R   [07]
    cenarion_ward               = T   [01], T   [10]
    convoke_the_spirits         = 3   [05]
    dash                        = SMwU[05]
    efflorescence               = V   [01]
    entangling_roots            = S1  [02], G   [05]
    ferocious_bite              = E   [07]
    flourish                    = S3  [01]
    frenzied_regeneration       = E   [09]
    grove_guardians             = SQ  [01], CF  [10]
    growl                       = T   [09]
    healthstone                 =
    heart_of_the_wild           = S6  [02]
    hibernate                   =
    incapacitating_roar         = AF  [02], CF  [09]
    incarnation                 =
    innervate                   =
    ironbark                    = ST  [01]
    ironfur                     = V   [09]
    maim                        =
    mangle                      = Q   [09]
    mass_entanglement           =
    moonfire                    = E   [01], T   [07], E   [10]
    natures_cure                = AF12[05]
    natures_swiftness           = SF  [01], SF  [10]
    natures_vigil               =
    prowl                       = 1   [05]
    rage_of_the_sleeper         =
    rake                        = F   [07], Q   [08]
    raze                        =
    regrowth                    = CE  [06]
    rejuvenation                = AE  [06]
    remove_corruption           =
    renewal                     = 5   [02]
    rip                         = V   [07]
    shred                       =
    skull_bash                  = SF  [07]
    soothe                      = S5  [02]
    stampeding_roar             = SMwD[05]
    starfire                    = V   [10]
    starsurge                   =
    sunfire                     = Q   [01], CF  [07], Q   [10]
    survival_instincts          =
    swiftmend                   = F   [01], F   [10]
    swipe                       = R   [07]
    swipe_bear                  = R   [07]
    swipe_cat                   = R   [07]
    thrash                      = SR  [06], R   [09]
    thrash_bear                 = SR  [06], R   [09]
    thrash_cat                  = SR  [06], R   [09]
    typhoon                     = SE  [05]
    ursols_vortex               = S2  [02]
    wild_charge                 = ST  [07]
    wild_growth                 = 4   [06]
    wrath                       = R   [01], R   [10]
```

I just logged in and got the updated binds as you can see its there now along with bar 10?

**Comment by tance77** [comment]
Ah bar 10 is boomkin form

**Comment by Hekili** [comment]
I'll try prioritizing bar 10 differently when you're not in form and see if it helps.  Otherwise, I'd have to make keybind detection a lot smarter than it is.

**Comment by tance77** [comment]
I think may be related to this?

[Snapshot](https://pastebin.com/AsgUwUwp)

**Comment by tance77** [comment]
Okay I replicated it.

Ran a dungeon, everbloom i just did it on normal and 1 shot everything, encountered the above error. Finished the dungeon came b ack to valdrakyn hit some target dumies reloaded as cat and then the keybinds were wrong again

![image](https://github.com/Hekili/hekili/assets/3421501/ae4725ed-aff8-4e9e-8c64-e08d39b3f210)


See it saying Q instead of CF

**Comment by tance77** [comment]
New keybinds it detected after reload

```
keybinds: 
    adaptive_swarm        = S4  [02]
    barkskin              = 2   [05]
    brutal_slash          = R   [01]
    cenarion_ward         = T   [01]
    convoke_the_spirits   = 3   [05]
    dash                  = SMwU[05]
    efflorescence         = V   [01]
    entangling_roots      = S1  [02], G   [05]
    ferocious_bite        = E   [01]
    flourish              = S3  [01]
    frenzied_regeneration = E   [09]
    grove_guardians       = SQ  [01]
    growl                 = T   [09]
    heart_of_the_wild     = S6  [02]
    incapacitating_roar   = AF  [02], CF  [09]
    ironbark              = ST  [01]
    ironfur               = V   [09]
    mangle                = Q   [09]
    moonfire              = E   [01], E   [10]
    natures_cure          = AF12[05]
    natures_swiftness     = SF  [01], SF  [10]
    prowl                 = 1   [05]
    rake                  = F   [01]
    regrowth              = CE  [06]
    rejuvenation          = AE  [06]
    renewal               = 5   [02]
    rip                   = V   [01]
    shred                 = Q   [01]
    skull_bash            = SF  [01]
    soothe                = S5  [02]
    stampeding_roar       = SMwD[05]
    starfire              = V   [10]
    sunfire               = Q   [01], Q   [10]
    swiftmend             = F   [01], F   [10]
    swipe                 = R   [01]
    swipe_bear            = R   [01]
    swipe_cat             = R   [01]
    thrash                = SR  [06], R   [09]
    thrash_bear           = SR  [06], R   [09]
    thrash_cat            = SR  [06], R   [09]
    typhoon               = SE  [05]
    ursols_vortex         = S2  [02]
    wild_charge           = ST  [01]
    wild_growth           = 4   [06]
    wrath                 = R   [01], R   [10]
    ```

**Comment by DockieB** [comment]
I'm having more or less the same issue, though it's not with stance change. I have my Ferocious Bite ability on 5 and Brutal Slash on 2. Hekili prompts me with the icon for Ferocious Bite, but shows the #2 keybind. 

![Screenshot 2023-12-21 104026](https://github.com/Hekili/hekili/assets/93949969/445a288c-b733-4653-915e-f729e3b4dc11)

**Comment by DockieB** [comment]
swapped to bear, and the same issue, with a different keybind. Incarnation: Guardian of Ursoc is on S2, Hekili is showing 9 (which is actually Raze).

![image](https://github.com/Hekili/hekili/assets/93949969/10334f11-0e0a-4a6e-9c39-cfc93143ddaf)

**Comment by Hekili** [comment]
The answer really remains the same.  You can see which bars the addon is pulling its keybinds from in your Player Information or a snapshot.  If you have that ability tucked away on a different hidden bar, and it's the bar that would normally be used by the WoW UI for your form, it's going to use that keybinding.

You can manually set the keybinding if you don't want to search your hidden bars.

**Comment by tance77** [comment]
@Hekili So the solution is just not to use stance changing / hidden bars?

**Comment by Hekili** [comment]
What?  No.  I would just manually set the keybinding in /hekili > Abilities and call it good without worrying about action bar pages.

```
    shred                 = Q   [01]
    skull_bash            = SF  [01]
    soothe                = S5  [02]
    stampeding_roar       = SMwD[05]
    starfire              = V   [10]
    sunfire               = Q   [01], Q   [10]
```

This part does imply some oddness, that Sunfire and Shred are somehow perceived as being on bar one in both cases.

> reloaded as cat

When you say this, are you talking about changing specialization or changing forms?

**Comment by tance77** [comment]
I changed specs then reloaded my ui.

```/console reloadui```

**Comment by DockieB** [comment]
For me, changing spec. 
-------- Original message --------From: Hekili ***@***.***> Date: 12/21/23  18:42  (GMT-05:00) To: Hekili/hekili ***@***.***> Cc: DockieB ***@***.***>, Comment ***@***.***> Subject: Re: [Hekili/hekili] [BUG] Keybind Recommendation  with changing
  stance bars and same abilities (Issue #3072) 
What?  No.  I would just manually set the keybinding in /hekili > Abilities and call it good without worrying about action bar pages.
    shred                 = Q   [01]
    skull_bash            = SF  [01]
    soothe                = S5  [02]
    stampeding_roar       = SMwD[05]
    starfire              = V   [10]
    sunfire               = Q   [01], Q   [10]

This part does imply some oddness, that Sunfire and Shred are somehow perceived as being on bar one in both cases.

reloaded as cat

When you say this, are you talking about changing specialization or changing forms?

**Comment by tance77** [comment]
I dont seem to have this issue anymore, but it does fail to recommend some abilities. Ill open a new ticket with that though.
