### ISSUE TITLE
[BUG] Iridal staff causing errors and not showing up in rotation

### ISSUE THREAD

**Issue by mikeekert** [Hekili/hekili#3073]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili/Events.lua:857: attempt to index global 'ability' (a nil value)
[string "@Hekili/Events.lua"]:857: in function `updateGear'
[string "@Hekili/Classes.lua"]:6455: in function <Hekili/Classes.lua:6452>

Locals:
T1 = 159630
T2 = 110004
MH = 208321
isUsable = true
name = "Extinction Blast"
spellID = 419278
tSpell = "iridal_the_earths_master"

### How to Reproduce

Currently a Shadow Priest, using Iridal staff.

In my rotation, the staff no longer appears, and I constantly get an error listed in the ticket.

### Player Information (Link)

https://pastebin.com/X6E6A7uH

### Error Messages (Link)

https://pastebin.com/FfwaJWvc

**Comment by Hekili** [comment]
There are multiple open tickets for this.
