### ISSUE TITLE
Attempts to call protected function

### ISSUE THREAD

**Issue by JCarrington77** [Hekili/hekili#3075]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As soon as I entered combat on my Balance Druid, the error occurred. Hekili vanished from the screen until combat had ended.

### How to Reproduce

This happened as soon as I entered combat on my Balance Druid.

### Player Information (Link)

https://pastebin.com/Lru2hawK

### Error Messages (Link)

https://pastebin.com/4bJMSgaS

**Comment by Hekili** [comment]
This is most likely a CPU usage issue between the addon and possibly other addons you have installed.  It may happen occasionally, unfortunately.
