### ISSUE TITLE
[FEATURE] REPLACE THIS TEXT WITH A BRIEF DESCRIPTION OF YOUR NEW FEATURE

### ISSUE THREAD

**Issue by daza1980** [Hekili/hekili#3076]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Branch of the tormented ancient not sowing in the rotation ret paladin

**Comment by Hekili** [comment]
Please submit a proper ticket with the correct information.
