### ISSUE TITLE
Consistent error since last update Attempt to index nul, Shadowed Razing Annhilator

### ISSUE THREAD

**Issue by Goodbye8** [Hekili/hekili#3077]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Throws error on log in for my ret pally, but not for my evoker

### How to Reproduce

Enter game as Ret Pally

### Player Information (Link)

https://pastebin.pl/view/e797ff1e

### Error Messages (Link)

 https://pastebin.pl/view/cf15d81a

**Comment by Hekili** [comment]
Can you confirm whether this is resolved with v10.2.0-1.0.19?

**Comment by Goodbye8** [comment]
Hi,

Yes it seems fixed  TY
