### ISSUE TITLE
[BUG] Lua Error Interface/AddOns/Hekili/Events.lua:857: attempt to index global 'ability' (a nil value)

### ISSUE THREAD

**Issue by Leon-Gaming009** [Hekili/hekili#3078]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [ ] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Loading into the game getting Lua Error regarding Hekili as stated in pastebin.

### How to Reproduce

Logged into Augment Evoker and error occurs

### Player Information (Link)

https://pastebin.com/ikdC4uHQ

### Error Messages (Link)

https://pastebin.com/YHnACtjZ

**Comment by Hekili** [comment]
There are multiple open tickets for this.
