### ISSUE TITLE
[REC] Arms AOE recommendations in ST

### ISSUE THREAD

**Issue by Kreytonx** [Hekili/hekili#3080]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When fighting a single target, the addon recommends sweeping strikes and whirlwind as if there were two or more targets.

### How to Reproduce

1. Enter game as Arms Warrior
2. Talent fervor of battle (not required)
3. Enter a single target fight
4. See recommendations 

### Snapshot (Link)

https://pastebin.com/52YYQDQv

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3eTXNJ5agcAcjmxjYdmD6y

### Additional Information

n/a

### Contact Information

.kreyton

**Comment by Hekili** [comment]
Resolved in latest release.
