### ISSUE TITLE
[REC] Paladin Ret PVP ability/spell: Blessing of Sanctuary not listed in Hekili abilities/entries

### ISSUE THREAD

**Issue by Scatrat** [Hekili/hekili#3081]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Retribution Paladin, I expect the addon to list a PVP spell called "Blessing of Sanctuary" in the abilities and entries section. However, I can't find the spell, see my attached screenshots snippets.

### How to Reproduce

1. Enter the game as a Retribution Paladin
2. Take the Blessing of Sanctuary PVP Talent
3. Try to find the spell in Hekili abilites or entries
<img width="205" alt="hekili_sdr1" src="https://github.com/Hekili/hekili/assets/153231714/865b5cca-2f42-4095-942f-f397473de699">
<img width="158" alt="hekili_sdr2" src="https://github.com/Hekili/hekili/assets/153231714/485164dd-2c6e-44c9-b16c-2bd95e67911c">

### Snapshot (Link)

https://pastebin.com/K2Xr7KPh

**Comment by Hekili** [comment]
PvP spells generally aren't supported until requested.  I'll take a look.

**Comment by Hekili** [comment]
Should be in next release v10.2.0-1.0.20.
