### ISSUE TITLE
AOE rotation locking up spell priority for Enhance Shaman

### ISSUE THREAD

**Issue by JackBurton1208** [Hekili/hekili#3082]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

AOE rotation not working for Enhance Shaman, WOW version 10.2.0.52607.  Using current Hekili build 10.2.0-1.0.18.  When entering combat with Auto set, the rotation indicators stop and do not go to the next spell.  Disabling AOE and setting the program to Single seems to work, however, there is no AOE advise.

I have tried to uninstall/reinstall the Addon.  Have also tried to import new profiles.

### How to Reproduce

Enter game as Enhance Shaman with either a Raid build or M+ AOE build(preferred)
Attack a mob of more than 3 
Indicators should stop or appear to be frozen on the last spell used.

### Player Information (Link)

https://pastebin.com/iwQP0yzi

### Error Messages (Link)

No error messages indicated

### Additional Information

Appreciate the help

### Contact Information

JackBurton1208

**Comment by Hekili** [comment]
You're not using the default priority.  Reset to the default priority and report back.

**Comment by JackBurton1208** [comment]
Appears to be working for all class setups. Not sure how that profile was changed. Appreciate the help and the quick response.

Thank you
