### ISSUE TITLE
[REC] Trinket Order: Witherbark's Branch vs. Mirror of Fractured Tomorrows

### ISSUE THREAD

**Issue by nechyu** [Hekili/hekili#3083]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Trinkets are not properly recommended on the shaman. I have two active trinkets such as Witherbarks Branch and Mirror Of Fractured Tomorrows. The addon recommends Mirror Of Fractured Tomorrows first and then Witherbarks Branch. Please correct it.

### How to Reproduce

Wear two trinkets and the recommendation is not as per sim.

### Snapshot (Link)

https://pastebin.com/SMeNK12b

**Comment by Hekili** [comment]
What does your sim do?  Provide the sim report link.  Thanks!

**Comment by nechyu** [comment]
https://www.raidbots.com/simbot/report/kmvUs3vS6cE5fwZAxmGadW

**Comment by Hekili** [comment]
This may be resolved in 10.2.0-1.0.20.  Let me know.
