### ISSUE TITLE
[REC] BM Hunter Single Target Opener

### ISSUE THREAD

**Issue by haydnlenz** [Hekili/hekili#3084]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

If I follow Helkili to a tee, then my opener is always scuffed. This is because there are dynamic changes to moves suggested based on the previous move. While this dynamic rotation suggestion is very useful once the fight has started, it is not helpful when I need to get all my pertinent abilities on cooldown at the very start of the fight. Here's what I mean:

This opener rotation is recommended in all guides, and Helkili even shows it as suggested before combat starts:

"Barbed Shot x2 --- Kill Command --- Call of Wild --- Bloodshed --- Beastial Wrath --- Kill Command --- Barbed Shot --- Kill Command --- Death Chakram --- Dire Beast" 

However, Helkili's dynamic suggestion messes this up right after Call of Wild is cast (step 3). Because it auto switchs the suggestion to getting another Barbed Shot off instead of executing the rest of the opener list. This makes the updated suggestions looks like:

"Barbed Shot x2 --- Kill Command --- Call of Wild"  right after this third step (CoW) Helkili will insert a Barbed Shot instead of continuing to the optimal opening rotation. This dynamic change leads to suboptimal performance when you have just started the initial fight opener. This is also true of AoE fight openers.

Here's the incorrect updated sequence given after this Call of Wild:
- Barbed Shot(0.00), Kill Command(1.15), Bloodshed(2.31), Bestial Wrath(3.47), Death Chakram(4.63), Kill Command(5.79), Barbed Shot(6.95), Kill Command(8.11), Barbed Shot(9.27), Dire Beast(10.43)

Here is my suggestion for a quick fix:

Offer a static opener upon start of combat to include the opener rotation suggested precombat up to the Dire Beast, then begin the dynamic recommendations after that static list is is finished. Do the same here for multi-target

### How to Reproduce

Any BM hunter can easily reproduce this by going to a target dummie:

1. Open up to 10 suggestions which will list the correct opener sequence pre-combat
2. Start combat and follow the first three steps (Barbed Shot x 2 --- Kill Command --- Call of Wild)
3. After completing the above step, you will see that Helkili will be recommending a Barbed Shot directly after this Call of the Wild

### Snapshot (Link)

https://pastebin.com/0si5CELk

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bwBsfpNYpQag4mUZ17oJwv

### Additional Information

Here is a twitch link to a recording I made showing the issue https://www.twitch.tv/videos/2010221201?filter=highlights&sort=time

### Contact Information

haydn.lenz@gmail.com

**Comment by Hekili** [comment]
I'll take a look, but the sim report you provided is for a comparison sim.  Just provide a quick sim of your character; let's see if the sim follows the guides.

> Here is my suggestion for a quick fix:

> Offer a static opener upon start of combat to include the opener rotation suggested precombat up to the Dire Beast, then begin the dynamic recommendations after that static list is is finished. Do the same here for multi-target

Developing an entirely new feature is not a quick fix.

**Comment by haydnlenz** [comment]
Yeah weird, the quick sim does show that doing the Barbed Shot is optimal (below). Why would this be so different from what all the YouTubers and Icyveins, etc guides are suggesting? Is this just wrong?
https://www.raidbots.com/simbot/report/iJdaSLQpD3Pq8qYqV5heoB

**Comment by Hekili** [comment]
It means the sim isn't written to do what the guides do (and vice versa).  It doesn't prove one is more optimal than the other.

It'd be helpful to snapshot just before and after the recommendation changes to do the third Barbed Shot.  I can compare the two and find out what is changing that the addon didn't anticipate.

**Comment by syrifgit** [comment]
"Barbed Shot x2 --- Kill Command --- Call of Wild --- Bloodshed --- Beastial Wrath --- Kill Command --- Barbed Shot --- Kill Command --- Death Chakram --- Dire Beast"

This isn't correct. The guides, sims, and hekili all show call of the wild happening **_after_** the other smaller CDs. This is because you are running different talents than the guide, so hekili and your sim are adjusting for your different talents.

On top of that, there is absolutely nothing wrong with sending the 3rd barbed shot if you get a proc. In fact, [my own sim](https://www.raidbots.com/simbot/report/ppMcC3WoR1usr6q2zCxg8x) does it before death chakram and CoTW.

Non-Issue.

**Comment by haydnlenz** [comment]
Wow that is an insanely higher difference in your sim. Please mark as completed, I'm sorry. 

Thank you guys, I will try to do syrifgit's build and see how that changes.
