### ISSUE TITLE
[REC] Arms Warrior - stance changes not recommended

### ISSUE THREAD

**Issue by Scatrat** [Hekili/hekili#3085]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Arms Warrior, I expect the addon to recommend Battle Stance when starting combat. However the addon doesn't recommend it because it thinks that the action is not ready, but it is. The same for Defensive Stance.

        1.   battle_stance ( precombat - 1 )
        The action is not ready ( 3598.63 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.04ms
        TimeData:Arms-precombat-1:battle_stance:0.04:Ability Known, Enabled(0.04)

### How to Reproduce

1. Enter the game as Arms Warrior.
2. Change Stance to Defensive.
3. Check recommendations, it doesn't recommend Battle Stance.

### Snapshot (Link)

https://pastebin.com/wky38th5

### Contact Information

JasonX#5321

**Comment by Hekili** [comment]
This is a deliberate choice.  If you swap to Defensive Stance in combat, you probably don't want to be told to swap back to Battle Stance constantly.  You want to know what DPS buttons to keep hitting while you mitigate whatever mechanic you're dealing with.

**Comment by Scatrat** [comment]
I would put in some conditions on when to switch to defensive or swap back to battle. as i am doing pvp mainly, it depends on several factors which are checked by wa and imported to hekili. it would be great to see this work, thx!

**Comment by Hekili** [comment]
I could potentially add an option that unlocks those so someone could set up a custom priority for swapping stances, but it would confuse 99% of users who stay in one stance 100% of the time.

**Comment by Scatrat** [comment]
maybe something with a checkbox that i need to tick to make it suggest stances? :)

**Comment by Hekili** [comment]
It'd have to be fairly hidden, like an optional modifier on Stance entries that bypasses the existing override.  Will consider.

**Comment by Scatrat** [comment]
Sounds good! Looking forward to it, thank you in advance!
