### ISSUE TITLE
[REC] Feral druid spell priority acting strange since v1.0.19a, mixing keybinds and spells

### ISSUE THREAD

**Issue by Sunzor** [Hekili/hekili#3086]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon is recommending Feral Frenzy but pointing at keybind of another spell (keybind E). If i swap around spells on the bar, same keybind persists (E), irrelevant what spell is there.  Feral Frenzy is bound to Shift+5 and is present on spellbar.
It seems that it's correctly loading Feral Frenzy as next spell, but somehow sees it on a wrong keybind.
Only started occuring after latest update,v1.0.19a,  2023-12-22.

Have tried resetting prio list.

### How to Reproduce

Enter as Feral Druid
Start Combat, eventually it will reocommend FF, see if it points to the wrong keybind.

### Snapshot (Link)

https://pastebin.com/MgwnjCbX

**Comment by syrifgit** [comment]
What spell is on "E"? The addon thinks you have 2 copies of it. 

feral_frenzy          = E   [01], S5  [04]


Also, you can always manually input the keybind on the abilities page if it's not reading it right.

Looking at it, it sees you have 3 things bound to E. Are you using an actionbar add-on?

**Comment by Sunzor** [comment]
> What spell is on "E"? The addon thinks you have 2 copies of it.
> 
> feral_frenzy = E [01], S5 [04]
> 
> Also, you can always manually input the keybind on the abilities page if it's not reading it right.
> 
> Looking at it, it sees you have 3 things bound to E. Are you using an actionbar add-on?

I use Bartender add-on and you're correct, seems to be actionbar add-on related (Bartender) mixing with default action bar bindings, both are being read by Hekili. 

When i disabled Bartender and went back to original, i see the 3 spells bound to E on 2 different bar "levels" (whatever its called), and Bartender has it's own bar so thats another binding. 

On Bartender, I have only Shred bound to E.

I'll remedy by removing the spells from default actionbar and see what happens when i run Bartender, otherwise i'll just manually input as you suggest.

After your tip I see this as a non-issue, and closing ticket if its OK with you.

Thanks!

**Comment by Sunzor** [comment]
Resolved
