### ISSUE TITLE
demon hunter rage fire problem

### ISSUE THREAD

**Issue by kmkoon** [Hekili/hekili#3087]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

demon hunter rage fire issue , for some reason it recomend to felrush while rage fire is about to explode which leading in massive decrease in damge 

### How to Reproduce

demon hunter rage fire issue , for some reason it recomend to felrush while rage fire is about to explode which leading in massive decrease in damge 

### Snapshot (Link)

didnt find

**Comment by Hekili** [comment]
Please fill out a proper and complete ticket if help is needed.
