### ISSUE TITLE
[REC] MW monk - Zen pulse not being recommended at all.

### ISSUE THREAD

**Issue by Webozo** [Hekili/hekili#3089]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

MW monk is not being recommended to use Zen Pulse at all. Checking the default rotation profile, it does not include the spell anywhere. Could it be added without needing to make a edited profile. could sim-craft recommendation be wrong?

### How to Reproduce

play game. as MW with zen pulse talent selected

### Snapshot (Link)

https://pastebin.com/wF39zBWP

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/4b6D4Ke5keTGXvHcFNRVdS

### Additional Information

checking raidbots sim, ofc it shows it doesn't use zen pulse, but is it not beneficial to use zen pulse even if talented?
Here is Single Target sim : https://www.raidbots.com/simbot/report/dGvZ8po1C4NseFZzsVKxL1
note - Even single target doesn't use zen pulse, or rising sun kick?

### Contact Information

Discord - willyb00b

**Comment by Hekili** [comment]
Zen Pulse is omitted because it's a 30 second cooldown that should *probably* be used situationally on an ally rather than rotationally on yourself.

The addon definitely uses Rising Sun Kick in single-target.

**Comment by Hekili** [comment]
I'm adding Zen Pulse to the AOE action list and also adding an option that enables it in single-target.

**Comment by Webozo** [comment]
> I'm adding Zen Pulse to the AOE action list and also adding an option that enables it in single-target.

Hello, Since adding this in, I had a moment of blank recommendation, not showing spinning crane kick, not a major issue, just thought it might be helpful.

Snapshot - https://pastebin.com/BqPKPCVv

since then has been working as intended.

**Comment by Hekili** [comment]
It looks like the final Spinning Crane Kick in the AOE list was disabled or unset somehow; it's possible that the recommendations were generated while the update was taking place.  It shouldn't be a persistent issue.
