### ISSUE TITLE
Night Elf Shadowmeld does not  = Ambush

### ISSUE THREAD

**Issue by Vernick69** [Hekili/hekili#309]
Hekili always tells Night Elf Rogues to "Shadowmeld" and Ambush. This logic is wrong for most encounters, especially raids as you are still in combat and also you cannot directly Ambush out of a Shadowmeld. Shadowmeld does not hold the same characteristics as Vanish. This sequence should be removed in the next release.

**Comment by Hekili** [comment]
You can absolutely Ambush out of Shadowmeld.  Have you tried?

**Comment by Vernick69** [comment]
If you are out of combat. Shadowmeld does not remove a person from combat in order to be able to Ambush.

**Comment by Hekili** [comment]
You can absolutely Ambush out of Shadowmeld in combat.  When you sim yourself, your sim does it.  You should try it.

**Comment by Vernick69** [comment]
If this was the case, every Rogue would be a Night Elf. I have got with SIMC team as well to verify the logic of the SIMS doing this and reaching out to the rogue discord for more guidance.

**Comment by Hekili** [comment]
For Alliance Rogues, possibly. It's a small gain, but it IS a DPS gain. 

You can just CTRL+F shadowmeld that it's absolutely intentionally included in the priority.

**Comment by Hekili** [comment]
Sim example:  https://www.raidbots.com/simbot/report/vNg7h3WanZjGVxdSJsEene/simc

![image](https://user-images.githubusercontent.com/9438134/78248603-f2889d80-74ba-11ea-87f5-c95da7003f3b.png)

**Comment by Vernick69** [comment]
It is confirmed on my end, on Ravenholdt Discord (Main Wow Rogue Discord),
and other sources that the only time Shadowmeld works is if it can reset
you "out of combat" which will work for sims and target dummies, but not
real raid situations. Vanish is the only item that does this during a
dungeon or raid.

**Comment by Hekili** [comment]
Sure, have them update the sim profile and I'll follow suit.

**Comment by shadowfx1970** [comment]
You have never been able to ambush from shadowmeld, this is why I stopped using hekili. Notified Raidbots over a year ago but alas as always there's little love for us rogues :)

**Comment by Hekili** [comment]
Yes you can. Shadowmeld doesn't change your action bar but you can Ambush anyway. Unless something has changed since the previous 5 times I've checked.

**Comment by shadowfx1970** [comment]
No, you can't, I just tried it in the raid. I'll test it on training dummy see if it works on them.

edit: Tested it on dummy and it worked fine, my apologies don't know why it didn't work in raid.

**Comment by Hekili** [comment]
Thanks for rechecking.

![image](https://user-images.githubusercontent.com/9438134/140592067-84848efd-a51f-4d36-9e3f-6866436164aa.png)

Just leaving this here for future reference:  https://www.warcraftlogs.com/reports/HDk9d4YcCjhqvJgQ#fight=4&type=casts&source=9&translate=true&start=1424184&end=1462169&view=events
