### ISSUE TITLE
[BUG] # of Vanish Charges Incorrect

### ISSUE THREAD

**Issue by MangoB1** [Hekili/hekili#3090]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

cooldown.vanish.charges does not display when Vanish has 2 charges. If it has 2 charges, it shows the value as 1. If it has 1 charge it shows a value of 1, and if it has 0 charges it shows 0 charges.

### How to Reproduce

1. Use cooldown.vanish.charges as a condition for any action list
2. Hover over the condition to confirm that cooldown.vanish.charges still shows 1 even though charges are at 2

### Player Information (Link)

https://pastebin.com/dQGJKH6T

### Error Messages (Link)

https://pastebin.com/dQGJKH6T

### Contact Information

mangob1 (discord)

**Comment by Hekili** [comment]
Will be fixed in 1.0.20.
