### ISSUE TITLE
Hekili Freezes up when running dungeons

### ISSUE THREAD

**Issue by mca82** [Hekili/hekili#3093]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is freezing up when running a dungeon. Just started doing this after last update.

### How to Reproduce

Run a dungeon

### Player Information (Link)

https://pastebin.com/5z8gbTQw

### Error Messages (Link)

https://pastebin.com/sDBFBr0Y

**Comment by mca82** [comment]
https://pastebin.com/a65u9bHH

Error after i cleared bug sack

**Comment by Hekili** [comment]
You have something else tainting your UI and then blaming Hekili for it.  Any new WeakAuras or addons?

**Comment by SpatenLa** [comment]
the snapshot is very fishy too. did you import a APL?

**Comment by Hekili** [comment]
Yeah, any priority that references `fight_style` isn't one of mine.
