### ISSUE TITLE
OUTLAW Damage/Ability Priority does not seem to match guides/logs.

### ISSUE THREAD

**Issue by veroinx** [Hekili/hekili#3094]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When comparing my damage profile on both training dummies and in raid, I am seeing an extremely different damage profile. Between the Eyes is not being maintained/recommended as often as it should be. The Audacity buff is also not being prioritized/recommended in the rotation when its available. Currently Ghostly Strike is being recommended on opener and if it is on cooldown, then Sinister Strike is recommended. 

### How to Reproduce

1. Log in as Outlaw Rogue.
2. Use either of these builds:
(ST)
BQQAAAAAAAAAAAAAAAAAAAAAAAAEkkEJCSSIJCSkkmkElkIlkAAAAAAAaJJxBSEFSKpEAAAASCA
(KIR)
BQQAAAAAAAAAAAAAAAAAAAAAAAAQJBRSIJJhESkkEaJJRJJSLJAAAAAAIlWSCHIJRBKpEAAAASCA
3. Under Outlaw Core, make sure all options are selected **EXCEPT** "Between the Eyes: Stealth Only"
4. Follow Normal Priority recommendations. 

### Snapshot (Link)

https://pastebin.com/7zMwPyFW

**Comment by syrifgit** [comment]
Your snapshot is not pasted correctly. Use Ctrl-A to select all of it before copying. It should be a massive text.

That being said, what I can see of the snapshot you posted matches the opener on the class guide.

**Comment by Hekili** [comment]
You'll need to take snapshots that match the different circumstances that you discuss.

> Between the Eyes is not being maintained/recommended as often as it should be. 

Snapshot when BtE should've been recommended but wasn't.

> The Audacity buff is also not being prioritized/recommended in the rotation when its available.

Snapshot when the Audacity buff is present and (somehow) not being prioritized.

> Currently Ghostly Strike is being recommended on opener and if it is on cooldown, then Sinister Strike is recommended.

What about it?

**Comment by mwojtkowski** [comment]
Looking at BtE object
```
usable = function()
    if talent.crackshot.enabled and not stealthed.all then return false, "userpref requires stealth" end
    return combo_points.current > 0, "requires combo points"
end,
```
if talented into crackshot it will only recommend BtE if you're stealthed, it also ignores setting "Between the Eyes: Stealth Only" as settings.crackshot_lock variable is not used anywhere

adding crackshot_lock variable to condition will allow BtE to be suggested outside of stealth if option "Between the Eyes: Stealth Only" is not checked
```
usable = function()
    if talent.crackshot.enabled and not stealthed.all and settings.crackshot_lock then return false, "userpref requires stealth" end
    return combo_points.current > 0, "requires combo points"
end,
```

**Comment by Hekili** [comment]
@mwojtkowski Thanks, this was an oversight on my part that will be fixed in next release.

**Comment by veroinx** [comment]
My apologies, I actually meant to cancel the post because I was having a hard time catching the snapshot for BtE.

 I was also getting ahead of myself with the Ghostly Strike aspect being recommended on pull. I wasn't acknowledging that it was off of the GCD. 
 
 Since this is posted - I will try to catch a snapshot of the priority recommending Sinister Strike over Ambush from stealth. (I was trying to track Audacity in the KIR build. Ignore my concerns with this issue...)

**Comment by veroinx** [comment]
Below is a snapshot of the issue with BTE not being recommended outside of stealth or subterfuge windows. 
(https://pastebin.com/ffUZ9RYJ)

**Comment by Sedveth** [comment]
> My apologies, I actually meant to cancel the post because I was having a hard time catching the snapshot for BtE.
> 
> I was also getting ahead of myself with the Ghostly Strike aspect being recommended on pull. I wasn't acknowledging that it was off of the GCD.
> 
> Since this is posted - I will try to catch a snapshot of the priority recommending Sinister Strike over Ambush from stealth. (I was trying to track Audacity in the KIR build. Ignore my concerns with this issue...)

KIR build never press ambush

**Comment by veroinx** [comment]
> KIR build never press ambush

Yeah I just didnt pay attention to my spec when I started trying to track it. That was my mistake. Hekili tracks accordingly when using HO/Audacity, but still has the same issue of not recommending BtE outside of stealth windows in order to maintain the 20% crit buff.

**Comment by Hekili** [comment]
The BtE recommendation outside Stealth will be fixed in next update; the Crackshot Lock setting was being applied at all times instead of only when you've explicitly chosen the option.
