### ISSUE TITLE
[FEATURE] Action Bar button that executes next recommended ability

### ISSUE THREAD

**Issue by supere989** [Hekili/hekili#3099]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

So i appreciate that this mod provides Recommended action ordering. But since it is a queue, why can't we have a macro button that is tied directly to the next recommended action so we can has a 1 Button for the next action queue, this would free up a bunch of action bar buttons that are commonly use and free up more space for situational items, and clean up the UI.

### Contact Information

supere989@gmail.com

**Comment by Hekili** [comment]
No, this is automation, is not allowed, is not my design intent for the addon, etc. etc.  Nope.
