### ISSUE TITLE
Paladin - Protection Rotation Error

### ISSUE THREAD

**Issue by BlacKcuD** [Hekili/hekili#31]
Often times prot pala rotation tells you to use consecration while other spells are ready.

Example problematic situation: Consecration is coming off cooldown and hammer has accumulated 2 charges.
Current behaviour: recast cons -> hammer -> hammer
Desired behaviour: hammer  -> recast cons  -> (decide what to do, probably hammer or even judgment)

Hammer is the lowest of the priorities and consecration should be recast early enough to not have it run out during critical phases. However, casting consecration on cooldown is not optimal either and the current Hekili iteration seems to do that.

**Comment by Hekili** [comment]
Need to actually snapshot this sort of issue to establish if it's an action pack issue or another bug.

**Comment by Hekili** [comment]
What is your source for Protection Paladin priority?  I've updated to the latest profile from SimulationCraft (and fixed some compatibility issues) and Hammer is below Consecration in that action list.
