### ISSUE TITLE
DemonHunterHavoc vengeful_retreat‘s felblade lead reduced from 1 to 0.4

### ISSUE THREAD

**Issue by hellovvorld1024** [Hekili/hekili#3101]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

DemonHunterHavoc vengeful_retreat‘s felblade lead reduced from 1 to 0.4
felblade has a distance limit of 5 - 15. If vengeful_retreat casted 1 second earlier, it will exceed the range after landing.

### How to Reproduce

DemonHunterHavoc

### Snapshot (Link)

nothing，Just a suggestion

**Comment by hellovvorld1024** [comment]
`

        readyTime = function ()
            if settings.retreat_and_return == "fel_rush" or settings.retreat_and_return == "either" and not talent.felblade.enabled then
                return max( 0, cooldown.fel_rush.remains - 1 )
            end
            if settings.retreat_and_return == "felblade" and talent.felblade.enabled then
                return max( 0, cooldown.felblade.remains - 0.4 )
            end
            if settings.retreat_and_return == "either" then
                return max( 0, min( cooldown.felblade.remains - 0.4, cooldown.fel_rush.remains - 1 ) )
            end
        end,
`

After testing, the experience is much better than cooldown.felblade.remains - 1

**Comment by Hekili** [comment]
I still need you to explain your reasoning.  What about it makes it better?  What is the problem in the first place?

**Comment by hellovvorld1024** [comment]
Felblade has a distance limit of 5 - 15. Vengeful_retro is a backward skill. it will be about 20 yards from the place where casted.

The current code is Vengeful_retreat's cooldown 1 second before use Felblade, after casting Vengeful_retreatreat, it is recommended that Felblade exceeded the range.

modified it to
`
return max( 0, Cooldown.felblade.remains - 0.4 )
`
`
return max( 0, min( cooldown.felblade.remains - 0.4, cooldown.fel_rush.remains - 1 ) )
`
The amount of advance can be shortened to 0.4 seconds, so it can be used in the air without exceeding the distance.

**Comment by Hekili** [comment]
I've made a similar change for the next release.
