### ISSUE TITLE
[REC] OOC Update Period time always resets to 1 second

### ISSUE THREAD

**Issue by GitCadde** [Hekili/hekili#3103]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Under Performance Tab the Set Update Period toggle is always checked and the OOC Update Period always resets to 1 second itself.
This only happens on the currently active spec.

### How to Reproduce

Just go to performance tab on your currently active spec, change OOC Period Value and reload settings window

### Snapshot (Link)

https://pastebin.com/PLRYSnBN

**Comment by GitCadde** [comment]
@Hekili i just tested more and rewrote issue description

**Comment by Hekili** [comment]
I'm not able to replicate this; does it occur with Retribution only or with any specialization?

When does it reset?  Logging out or reloading UI or both?

**Comment by Xalesch** [comment]
Hello, I have a slightly different problem but i think it comes from the same source. For me the targeting settings alway reset after relog or restart the game. With some of my chars it's fine but with the most not.

I always set the toggle by Targeting "Count Targets by Nameplates" and it always resets.

**Comment by syrifgit** [comment]
This is happening to me now too with my targeting settings.

**Comment by syrifgit** [comment]
My targeting settings are now being remembered since the last update. Is your stuff remembering now too? @GitCadde @Xalesch ?
