### ISSUE TITLE
[BUG] Unable to take snapshot of rotation error for Fire Mage

### ISSUE THREAD

**Issue by notwiththem** [Hekili/hekili#3107]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When playing fire mage I've periodically run into issues where suggestions are made for abilities that have no charges available etc.  When attempting to create a hekili snapshot I get a wow error for the addon as follows:

```
2x Hekili/Dragonflight/MageFire.lua:1453: attempt to call field 'impact' (a nil value)
[string "@Hekili/Dragonflight/MageFire.lua"]:1453: in function `impact'
[string "@Hekili/State.lua"]:6172: in function `HandleEvent'
[string "@Hekili/State.lua"]:6754: in function `advance'
[string "@Hekili/Core.lua"]:1664: in function `Update'
[string "@Hekili/Options.lua"]:11176: in function `MakeSnapshot'
[string "@Hekili/Options.lua"]:11133: in function `TogglePause'
[string "@Hekili/Options.lua"]:11273: in function `FireToggle'
[string "@Hekili/UI.lua"]:2840: in function <Hekili/UI.lua:2839>

Locals:
Skipped (In Encounter)
```

### How to Reproduce

1. Enter game as fire mage
2. Go to training dummies and execute an aoe rotation
3. Wait to see if suggestions get stuck on the same thing ie scorch, or suggests something that has no charges left, ie fire blast or something on cooldown still like combustion
4. Attempt to take snapshot

### Player Information (Link)

https://pastebin.com/74Gd3U8a

### Error Messages (Link)

https://pastebin.com/BkVHZAh9

**Comment by Hekili** [comment]
This will be resolved in 10.2.0-1.1.0a
