### ISSUE TITLE
[BUG] UI.lua:2350 Error

### ISSUE THREAD

**Issue by evilgodly** [Hekili/hekili#3108]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I got this error when i logged into my 70 Druid that is in Gnomergon Pet Battle Area. Didn't do a single things other than log in.

### How to Reproduce

I got this error when i logged into my 70 Druid that is in Gnomergon Pet Battle Area. Didn't do a single things other than log in.

### Player Information (Link)

https://pastebin.com/Pz3whDsJ

### Error Messages (Link)

https://pastebin.com/yPPgw14M

### Contact Information

evil_godly

**Comment by Hekili** [comment]
Does this occur every time you log in there?

**Comment by evilgodly** [comment]
it just happened that one time. Haven't seen it since. 

Update:

I just logged into my 70 Druid that is in the Gnomer Battle Pet Area, doing quest Gnomeregan's New Guardians, and i get it immediately when i login. 

https://pastebin.com/haaYVeuz
