### ISSUE TITLE
[Bug] Keeps recommending Fire Blast with 0 charge

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#3109]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It seems that the addon is stuck on recommending Fire Blast with 0 charges.
Also, sometimes it get stuck on recommending Scorch

### How to Reproduce

N/A

### Snapshot (Link)

https://pastebin.com/ZnzkM1wk

**Comment by Hekili** [comment]
Update to the latest version and retest: v10.2.0-1.1.0

Thanks!

**Comment by SUU09** [comment]
Edited: Still same issue

https://pastebin.com/CEnjbTN9

**Comment by Hekili** [comment]
> Fire; Primary - Living Bomb(1.21), Fireball(2.51), Fire Blast(4.46)

It's recommending Living Bomb, then Fireball, then Fire Blast.  In 4.46 seconds, you'll have Fire Blast available.
