### ISSUE TITLE
Primary Display 2nd and .... icons

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#311]
So I have the latest version of Hekili (just updated today, 4/2/2020).
My problem is with the Primary Display.
I have 2 icons selected, the main (I guess Primary) icon is sized with the w/h adjustments and it works fine but the second icon is not sized the same way, its smaller! I don't know how I adjusted the 2nd icon to be smaller (I do remember doing it) but I don't remember how I did it.

So, somehow the second icon and if I add a 3rd or 4th, they are all the small size and not the size of the "Primary" icon.

**Comment by Hekili** [comment]
/hekili > Displays > Primary

You start on the Main tab, where you can see Width and Height for the Primary Icon:

![image](https://user-images.githubusercontent.com/9438134/78311149-04e7f300-751e-11ea-9d02-b23763e43f91.png)

At the upper right, change Main to Queue.  This is where you adjust the height of queued icons.

![image](https://user-images.githubusercontent.com/9438134/78311233-36f95500-751e-11ea-9b0c-ec1dca7d3159.png)
