### ISSUE TITLE
[BUG] Nameplate Detection Range not working

### ISSUE THREAD

**Issue by SUU09** [Hekili/hekili#3110]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I'm using "Nameplate Detection Range" and set it to 10 yard for Fire Mage, but it still shows 2 target even though the other target is faraway.
![Nameplates](https://github.com/Hekili/hekili/assets/31148722/694b4d92-8e4d-4a7c-9e2d-0458251cbe6f)

### How to Reproduce

N/A

### Player Information (Link)

N/A

### Error Messages (Link)

N/A

**Comment by Hekili** [comment]
Nameplate detection is still using the Range Filter by Spell option, not the slider.  I'll re-enable the slider in a future update.
