### ISSUE TITLE
Customizable color action button glow around main hekili icon to be used on script interface its self.

### ISSUE THREAD

**Issue by dazalar** [Hekili/hekili#3111]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

First off this isn't a spell flash request, this is different. I would like (and others to I believe) to be able to select an action glow color (similar in looks to WA action button glow custom options) for each spell on hekilis rotations interface its self (not action bars like spell flash) that stay around the icon till you hit the corresponding recommended abil, for example as Ret I could choose green for judgment and purple for final verdict etc etc, these action button glow colors would stay on the active hekili icon till pressed then move to the next icon/color designated to it.  The main haters you get to this awesome addon is " it creates bad habits cause people just stare at an icon slider and ignore there environment", if you implement the following change this would shut people up as due to the way the brain works colors can be interpreted better then mixed icons, meaning if you see purple off to the side then you know it wants you to hit Final verdict or if you see green judgment etc.. most dps rotations only have 5-7 main stay GCD/s (excluding big burst cds) might only need 8 colors at most or better yet allow people to choose the color (color wheel like WA) As it stands I can create action glows in WA for icons on my action bars But I lack the ability  to port the action glow effects to your icon script or vise versa integrating your script to use with WA, hence my suggestions. Colors are very powerful and I believe can more easily associate hot key presses with colors then looking astray at icons, this would allow me and others to focus more on the environment whilst knowing what your script is asking me to press. Thank you for your addon its great, I'm just trying to suggest some more versatility to it and to maybe shut down some of those haters. cheers!!

**Comment by Hekili** [comment]
I don't plan to implement this.
