### ISSUE TITLE
[FEATURE] Specific cast sequences

### ISSUE THREAD

**Issue by cameronstubber** [Hekili/hekili#3113]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'd like to have specific sequences of spells being able to be defined for a class/spec, which will be recommended when a certain set of conditions are met.

For example:

Feral Druid
- Tigers Fury
- Potion
- Bezerk
- Trinket
- Feral Frenzy
- Ferocious Bite
- Convoke the Spirits

Arcane Mage
- Radiant Spark
- Nether Tempest
- Arcane Surge
- Potion
- Trinket
- Arcane Barrage
- Touch of the Magi
- Arcane Blast
- Arcane Blast
- Arcane Blast

Everything should be held until all of those are available apart from the Potion. Once the sequence is over or the wrong thing has been cast, the addon defaults back to priority lists.

This would also be applicable for classes with specific orders of things for openers.

### Contact Information

syncsubaru

**Comment by Hekili** [comment]
The addon is designed as a priority helper; I'm not convinced sequences would solve more problems than they create.  Imagine that you stop or get CC'd mid-sequence.  I'd much rather have a priority that uses logic to solve for what to push next than a sequence that wants me to Summon Demonic Tyrant even though my major demons are now gone.

Your solution for this, switching back to a priority if the "wrong" button is hit, has loads of problems, too.  If someone macros Berserking to their major cooldown, does that mean Berserking is wrong and it should fall out of the sequence.

If there are specific sequences of casts that need to happen, a priority can be written to do them under the right circumstances.  For example:

1. Tiger's Fury
2. Potion, `prev_off_gcd.1.tigers_fury`
3. Berserk, `prev_off_gcd.1.potion & prev_off_gcd.2.tigers_fury`
4. Trinket, `prev_off_gcd.1.berserk & prev_off_gcd.2.potion`
5. Feral Frenzy, `buff.berserk.up & buff.tigers_fury.up`
6. Ferocious Bite, `combo_points.current = 5 & prev_gcd.1.feral_frenzy`
7. Convoke, `prev_gcd.1.ferocious_bite & prev_gcd.2.feral_frenzy`

There are still nuances to this that are potentially problematic.  What if you don't have an on-use trinket?

Overall, it's still best to write a priority that gets the result you want than to just try to script a specific sequence of actions.
