### ISSUE TITLE
[BUG] Can't track buff "Resonant Words" on holy priest

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3115]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When casting Holy Word: Serenity with Resonant Words talented, the addon will not acknowledge that the buff is present.
buff.resonant_words.up

### How to Reproduce

1. Cast Holy Word: Serenity
2. Buff isn't tracked in Hekili
3. Forget to cast Flash Heal

### Player Information (Link)

https://pastebin.com/SSJgwqXS

### Error Messages (Link)

No error message

### Additional Information

Nothing really, just an untrackable buff.

**Comment by Hekili** [comment]
This will be resolved in the next release.
