### ISSUE TITLE
[REC] Unable to track clearcasting on Restoration Druid

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3119]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Buff is untrackable
buff.clearcasting.up

### How to Reproduce

1. Cast lifebloom
2. Wait for a proc
3. buff.clearcasting.up doesnt' turn true

### Snapshot (Link)

https://pastebin.com/aMRyJmSG

### Raidbots Sim Report (Link)

Can't sim as a healer

**Comment by Hekili** [comment]
Will be added in next release.
