### ISSUE TITLE
WW , cant off Flying Serpent Kick 

### ISSUE THREAD

**Issue by knagls** [Hekili/hekili#312]
![image](https://user-images.githubusercontent.com/10481465/78339610-6a2ef900-759d-11ea-8131-6df06f0c1c57.png)

Cant off this, it still remains on.

**Comment by knagls** [comment]
![image](https://user-images.githubusercontent.com/10481465/78340251-723b6880-759e-11ea-9492-b3077b314113.png)

click here and expect it to turn off

but 
![image](https://user-images.githubusercontent.com/10481465/78340278-7bc4d080-759e-11ea-8344-dde091a37992.png)

**Comment by Hekili** [comment]
Oh, it took me a minute to understand what's going on there.

You're setting it from the minimap dropdown, which I didn't test for.  Will fix.  Thanks.

**Comment by Hekili** [comment]
You can change it via /hekili > Windwalker and using the checkbox there for now.

**Comment by Hekili** [comment]
Fixed in the latest beta.
