### ISSUE TITLE
[REC] Howling Blast

### ISSUE THREAD

**Issue by ToxxicApe** [Hekili/hekili#3121]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

sometimes its recommended to spam howling blast on frost dk for like 3-4 times...that cant be right

### How to Reproduce

i have it in aoe situation and in single target as well. but not every time

### Snapshot (Link)

https://pastebin.com/garuqPQY

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/64RFPJrC7cAJJ7h6DhZZRX

### Additional Information

Frost DK and have newest version of the addon

**Comment by Hekili** [comment]
Try the 1.1.3-beta1 and see if it makes a difference for you.

**Comment by ToxxicApe** [comment]
do you have a link? cant find it on curse

**Comment by JGBG78** [comment]
Same issue here 

You use howling blast only with proc or to apply dot, It work well inside pillar of frost window, but outside it’s not ok.

**Comment by JGBG78** [comment]
> Try the 1.1.3-beta1 and see if it makes a difference for you.

I try and it doesnt change anything

**Comment by Hekili** [comment]
I think I've identified the issue; will test a fix in 10.2.5.

**Comment by JGBG78** [comment]
Seems to be fixed
