### ISSUE TITLE
[REC] Resto Shaman still has Primordial Wave as part of its rotation when it no longer damages

### ISSUE THREAD

**Issue by Michael-Ziluck** [Hekili/hekili#3122]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my resto shaman, Primordial Wave is recommended as part of the DPS rotation. Since the latest patch, when spec'd into resto, Primordial Wave no longer does damage and applies Flame Shock and should be removed from the rotation entirely.

### How to Reproduce

1. Log in as a Restoration Shaman
2. Spec into Primordial Wave
3. Apply necessary shields and use up any trinkets that would prevent spells from displaying in rotation
4. Observe that Primordial Wave is suggested as a damaging spell

### Snapshot (Link)

https://pastebin.com/nz4cVBpd

### Additional Information

I'm very good about checking GitHub (I'm a software engineer) but in case you need a super quick reply, my Discord is below.

### Contact Information

doctorzee

**Comment by Hekili** [comment]
Good call; will remove.

**Comment by Michael-Ziluck** [comment]
Bump on this, I'd open a PR with the fix if you point me towards where it is in the code base. I'm an SE but Lua isn't my strong suit

**Comment by Hekili** [comment]
Sorry, this update is finally coming (soon).
