### ISSUE TITLE
[FEATURE] Allow interrupt display to use Focustarget before actual target

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3123]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Given the new spell filter list (bravo btw), I think this setting might now be relevant for higher end dungeon content.

In high m+, it's common strategy to be assigned a kick target and set that as your focus while you dps down the priority mob. Would like to be able to have the priority bar pick your focus target first (toggle-able setting, default set to NOT use focus, should be opt-in). If no focus exists, default the display to your target (aka, current behaviour).

If all goes well, I'd delete my focus kick WA entirely and use Hekili's kick bar.

If this is already possible let me know and I can add it to the config guide and/or faq.

BONUS RELATED FEATURE:

Toggle the ability to have the Caption of the kick display be the spell name that is being cast on that target (whether focus or current target)

### Contact Information

Syrif

**Comment by Hekili** [comment]
This is a good idea but not planned for the same reasons that additional targets are not really planned.  The addon only knows the player and the player's target with any significant amount of depth.
