### ISSUE TITLE
[REC] Fury Warrior Thunderous Roar without trinket/Avatar in AOE

### ISSUE THREAD

**Issue by HoldMyKeg** [Hekili/hekili#3126]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Furry warrior is recommending Thunderous Roar before proc Avatar from Odyn's fury when Enraged or with the CD Avatar in AOE.
This is also what sim is doing:
(5 target sim)
![image](https://github.com/Hekili/hekili/assets/74076515/3170c731-f88d-428d-be95-beeaab6cb749)

ST sim:
![image](https://github.com/Hekili/hekili/assets/74076515/c1b033b5-9043-4320-96d2-c6857916d2a4)

I asked on warrior discord one mentions:
"The APL hasn't been updated for AoE properly yet
The order of CDs is the same in AoE and ST"
![image](https://github.com/Hekili/hekili/assets/74076515/77e168de-a2bf-4290-96fd-c07f91882cdc)
![image](https://github.com/Hekili/hekili/assets/74076515/0690178a-99e9-40a9-9637-5b67e238aa14)

I have checked top 10 logs from both The Everbloom and Darkheart Thicket looking at the first 2 casts of Thunderous Roar everyone except 1 was using Odyn's fury to proc avatar or the CD avatar before using Thunderous Roar.

Most have an opener that is looking like this:
![image](https://github.com/Hekili/hekili/assets/74076515/a7c64c64-4ffa-457e-b10a-cf1e2448bd63)
or
![image](https://github.com/Hekili/hekili/assets/74076515/1598632f-1139-4576-99ea-fe6f38eff576)

2. cast:
![image](https://github.com/Hekili/hekili/assets/74076515/b1d800d8-03b1-4c0f-a8cd-0461b5cd8fbc)
![image](https://github.com/Hekili/hekili/assets/74076515/10f93a6a-8135-4022-840f-cd51008dc438)

### How to Reproduce

1. Enter game as a furry warrior
2. use talent BgEAfuKaizEAgP2qANDB2hmf7HAAAAAAAAAAQggSCQESgQS0AhISEESgEJJhkkEBRapkkASSAAAQABB ( popular M+ build don't think I do anything special, I think Titan's torment, Thunderous Roar, Odyn's Fury are the important part)
3. I'm testing on the 5 training dummy's in Valdrakken (this is for AOE), follow recommendations (I get Charge > Recklessness >whirlwind > Rampage > Thunderous Roar)
4. It show Thunderous Roar before  Odyn's Fury / stats trinkets

### Snapshot (Link)

https://pastebin.com/fXFNJBR8

### Raidbots Sim Report (Link)

AOE: https://www.raidbots.com/simbot/report/jSDdr2yiMcHdQaM1KgtRNx  (have the same problem), ST: https://www.raidbots.com/simbot/report/j3E87VCaLoWffzhHnQDYTF (Thunderous Roar used as expected)

### Additional Information

Talked about it in Discord: https://discord.com/channels/307520968895627264/1195441158655070399

### Contact Information

holdmykeg.

**Comment by Hekili** [comment]
Thunderous Roar already has the same conditions in single-target and multi-target in the sim priority, checking only for Enrage to be up.  Did the discussion lead to any plans to update the sim priority?

I'm making an adjustment for this, but it's DPS neutral at best (though it does bring up the DPS floor overall).
