### ISSUE TITLE
[REC] Sub: Recommending Flagellation separately from Shadow Blades

### ISSUE THREAD

**Issue by wheatbread** [Hekili/hekili#3127]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For sub rogue:

Hekili is recommending using Flagellation when Shadow Blades is on CD and will be up soon.  It does not wait for Shadow Blades when you're supposed to always sync them.  It does not wait for Shadow Blades to be less than 12s either before wanting you to cast Flagellation.

From Wowhead guide: https://www.wowhead.com/guide/classes/rogue/subtlety/rotation-cooldowns-pve-dps

Flagellation use explained.
[ Flagellation](https://www.wowhead.com/spell=384631/flagellation) is always aligned with [ Shadow Blades](https://www.wowhead.com/spell=121471/shadow-blades). The easy way to do this is to [ Flagellation](https://www.wowhead.com/spell=384631/flagellation) - Finish - [ Shadow Blades](https://www.wowhead.com/spell=121471/shadow-blades).
However the [ Flagellation](https://www.wowhead.com/spell=384631/flagellation) mastery buff is the important part of the spell, this allows you to use the spell earlier as long as [ Shadow Blades](https://www.wowhead.com/spell=121471/shadow-blades) once you get the 12-second mastery buff.

From Icy veins: https://www.icy-veins.com/wow/subtlety-rogue-pve-dps-rotation-cooldowns-abilities

Cast [Shadow Blades](https://www.wowhead.com/spell=121471) Icon Shadow Blades on cooldown, paired with [Flagellation](https://www.wowhead.com/spell=384631) Icon Flagellation as often as possible.
Use [Flagellation](https://www.wowhead.com/spell=384631) Icon Flagellation with enough combo points to finish after and if Shadow Blades Icon Shadow Blades is up or has less than 12 seconds remaining on its cooldown.

### How to Reproduce

1. Be subtlety rogue spec
2. Use shadow blades and flagellation and wait for flagellation to come off CD (they have different timers), or just use shadow blades by itself and wait for any period.  
3. Hekili will always recommend using flagellation no matter the CD on shadow blades. 

Example 1: 
with 1 min left on shadow blades:

https://pastebin.com/t76mnYd8

Example 2:
with 20s left on shadow blades:
https://pastebin.com/Nyk2cnfd

### Snapshot (Link)

https://pastebin.com/Nyk2cnfd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qT3xx1ctLUoNw8wZc2qPk1

### Additional Information

I linked patchwerk above but it happens regardless if aoe or ST.  Here is dungeon slice:

https://www.raidbots.com/simbot/report/oPw5YyouApsirmLyKJma9F

**Comment by syrifgit** [comment]
> Example 1: with 1 min left on shadow blades:
> 
> https://pastebin.com/t76mnYd8
> 

Your sim also does this because of Vanish CDR. At the 2 minute mark of your sim it casts flagellation, then again at 3 minutes along with shadowblade. This can also be seen in most of the top rogue mythic volcoross logs: https://lorrgs.io/spec_ranking/rogue-subtlety/volcoross



> Example 2: with 20s left on shadow blades: https://pastebin.com/Nyk2cnfd
> 
> ### Snapshot (Link)
> https://pastebin.com/Nyk2cnfd

Same as above point. Vanish is going to lower the CD, probably a few recommendations after this snapshot. It looks like you're going 4 spells without casting, but 2 of those recommendations are off the GCD so this 4-recommendation is only flagellation + 1 global. A snapshot of this afterwards showing it not casting vanish or shadowblades would probably be helpful.

Maybe a rogue main can chime in, but I don't see the issue here.

**Comment by Hekili** [comment]
> Example 1:
> with 1 min left on shadow blades:

The entry used here has a section specifically intended to use Flagellation out of sync with Shadow Blades if Invigorating Shadowdust and Shadow Dance are talented:

```
cooldown.shadow_blades.remains[71.09] >= 14 & talent.invigorating_shadowdust.enabled[true] & talent.shadow_dance.enabled[true]
```

The same is true of example 2 for the same reasons:

```
cooldown.shadow_blades.remains[20.60] >= 14 & talent.invigorating_shadowdust.enabled[true] & talent.shadow_dance.enabled[true]
```

Removing this bit of logic loses about 1.5% DPS on average:

![image](https://github.com/Hekili/hekili/assets/9438134/a68add44-182f-482e-948a-fe7dd6dd796f)
