### ISSUE TITLE
[BUG] cleave_apl in Warlock Destruction check wrong?

### ISSUE THREAD

**Issue by nuttin0011** [Hekili/hekili#3128]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

in ur code
```
spec:RegisterSetting( "cleave_apl", false, {
    name = function() return "|T" .. ( GetSpellTexture( 116858 ) ) .. ":0|t Funnel Damage in AOE" end,
    desc = function()
        return "If checked, the addon will use its cleave priority to funnel damage into your primary target (via |T" .. ( GetSpellTexture( 116858 ) ) .. ":0|t Chaos Bolt) instead of spending Soul Shards on |T" .. ( GetSpellTexture( 5740 ) ) .. ":0|t Rain of Fire.\n\n" ..
        "You may wish to change this option for different fights and scenarios, which can be done here, via the minimap button, or with |cFFFFD100/hekili toggle cleave_apl|r."
    end,
    type = "toggle",
    width = "full",
} )
```

that mean when i check Funnel Dmg in AOE mean variable cleave_apl = true right?
and when i want to AOE i ll uncheck and cleave_apl turn false
and in simc profile
`actions.precombat+=/variable,name=cleave_apl,default=0,op=reset`
it's turn variable to 0
and in AoE condition
`( active_enemies >= 3 - ( talent.inferno.enabled & ! talent.chaosbringer.enabled ) ) & ! ( ! talent.inferno.enabled & talent.chaosbringer.enabled & talent.chaos_incarnate.enabled & active_enemies < 4 ) & ! variable.cleave_apl`
never turn true because `! variable.cleave_apl` = `! 0` = `false`

i never see AoE action list show in recommend
i think something wrong in this code or i miss understand?

please help.

### How to Reproduce

it always show "cleave" action list although i uncheck Funnel Dmg in AOE
and  "Issue Reporting section (left panel)" is vanish?
i cannot dump my toon info for you sorry.

### Player Information (Link)

-

### Error Messages (Link)

-

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots and Reporting section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by nuttin0011** [comment]
https://pastebin.com/NQVPdSjS

yes sir.

**Comment by nuttin0011** [comment]
https://pastebin.com/NQVPdSjS

here sir.

some of warning is made from my Weak aura call ur function and it's Error

**Comment by Hekili** [comment]
`variable.cleave_apl` will respect the `cleave_apl` option in the next release.

Trying to change `variable.cleave_apl` inside the priority will not have any impact because it will be overridden by the setting.
