### ISSUE TITLE
Havoc DH, no recommendations 

### ISSUE THREAD

**Issue by cdc1287** [Hekili/hekili#3129]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I only play Havoc in the open world, but it will sometimes not show any recommendations for a few seconds. It will auto generate a snapshot. This happens very often.

### How to Reproduce

I don't know what causes it to happen.

### Snapshot (Link)

https://pastebin.com/dPgbaCJy

**Comment by Hekili** [comment]
This should be addressed in the upcoming release.
