### ISSUE TITLE
Hekili & SpellFlash

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#313]
All addons are of the latest versions available.

Not sure if this is an issue with Hekili or SpellFlash.

I have spellflsh and spellflashcore addons, run Hekili and the icons give a nice gold glow when Hekili icons show up.
Except Envenom, seems to not flash at all at the appropriate time or if it does, its a "weak/faith" line of gold (if you stare at it). Its an instant cast but so is Rupture and its glow is fine.
I don't see a github board for SpellFlash so I cant post there. If there is support for SpellFlash, where can I find it?

Thanks,
Pete

Envenom = Rogue skill

**Comment by petesmisc** [comment]
Please close this ticket as I believe the problem is in Spellflash.

While the Spellflash in Hekili is disabled, Spellflash still flashes the "boarder" of the rotation icon's except Envenom

Although I like the boarder flash much better than the Hikili "from center" out flash (buts that's just me. May add that as a future option?

**Comment by Hekili** [comment]
I honestly don't even know what different flashes you're talking about.

**Comment by petesmisc** [comment]
Well, as an example, just about every Weak Auras UI's that I have used/using, has the "glow" around the boarder of the icon (when enabled in WA by whom ever wrote the UI).

When I enable Spellflash in Hekili, the flash is from center of the icon out (kind of a four point burst).

To me a gold/yell boarder (color should be adjustable as you currently have in Hekili) around the icon is must more pleasing and it does not flash out the icon itself. 
And should something like that be considered, adjustment of the "thickness" of the boarder would be great also.

Splellflash has that itself but the broader is "thin" and the adjustment does not seem to make much difference. (but as I have said it does not want to reliable flash Envenom for some reason, again, this problem is only when Spellflash is NOT enabled in Hekili). All the other rotation icons seem to work even when Spellflash is not enabled in Hekili

So Spellflash has some issues itself (not sure its much supported anymore) also Hekili has an issue when Spellflash is enabled with the "in combat" problem (wrote a ticket for that)

**Comment by Hekili** [comment]
The addon's support of SpellFlash is intentionally pretty limited.  I don't like SpellFlash, personally.  Playing whackamole with your buttons means less braintime for watching mechanics.

Anyway, if you enable SpellFlash in the addon, the addon tells SpellFlash when there are updates.  If SpellFlash doesn't respect its own options on that front, that's a SpellFlash problem.

**Comment by petesmisc** [comment]
I respect your view of WOW but the game is a whackamole and learning the mechanics is a given if you want to stay alive in any raid, even lfr (although its much more forgiving).
The flash of the icon or a "Primary" window from Hekili are one and the same just a different version.
I like the key highlight (boarder highlight), its just another thing to build up muscle memory.

My guild and I had all the ATOCs in BFA8.2, I stopped playing about 2 years (shortly after the new Islands where added) as I was just burnt out/tired of the rep grind etc... Once you get the mechanics, it is whackamole, but you still have to know the mechanics.

Many years ago, when Spellflash was a "thing" that's what I used for my rotation and loved it. Its too bad its so poorly support now, not so much the toon rotations for Spellflash (nobody makes those anymore) but Spellflash itself.

So I guess the fix for the issue with "always being in Combat when spellflash is enabled in Hekili"
 is off the table?

Reason I'm playing again is because of the Coronavirus, not much else to do at home.

Stay safe :)

**Comment by Hekili** [comment]
You can use the Display's Visibility settings to avoid flashing in combat (the addon's recommendations will be hidden as well).

![image](https://user-images.githubusercontent.com/9438134/78460777-b0fe1b00-7691-11ea-8662-0351fc139a23.png)

![image](https://user-images.githubusercontent.com/9438134/78460780-bc514680-7691-11ea-8b64-97fbb1e97afe.png)

**Comment by Hekili** [comment]
The critical piece there is that Primary > Visibility > Advanced is checked, and the visibility for Always is set to 0.

**Comment by petesmisc** [comment]
That seems to have stopped the rotation flashing while NOT in Combat (or
its still going but hidden) but regardless - Thank You very much!

If Spellflash is doing the flashing and not Hekili none of the limited
Splellflash controls have any effect.
Its too bad, honestly Hekili should do their own flash type ability, with a
choice of Primary Window, Flashing or both
with perhaps more options as to the flash, start burst from center out,
boarder flash, etc.... you already have the color selection :)
