### ISSUE TITLE
[REC] Frost mage - Sated debuff logic not working for all versions of lust - impacting Temporal Warp talent

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3132]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing frost mage (and possible other mage specs, haven't checked), the Temporal Warp talent lets you lust again when you are lusted or sated. Noticed it wasn't being recommended, when I paused / snapshotted I had the [Time warp version of sated](https://www.wowhead.com/spell=80354/temporal-displacement) but the APL condition was not triggering.

Probable fix: Make sure sated is checking every version of lust. Drums, Shaman, Mage, Hunter, Evoker, Alliance/Horde if there's still a difference.

In the snapshot, this can be see on CDs list APL line 6 - Time Warp, combined with the player debuffs section.

This is a pretty big dps loss overall in keys if you have the "wrong" sated debuff.

### How to Reproduce

1. Play frost mage using any temporal warp build
2. Cast time warp and wait out the lust buff
3. Once you are sated with NO lust buff, cast icy veins and notice that time warp is not being recommended

### Snapshot (Link)

https://pastebin.com/FW3nLBbZ

### Contact Information

ya boi syrif

![sated](https://github.com/Hekili/hekili/assets/139663837/7ac44dbe-e08d-4567-a2fa-081a047858f9)

**Comment by syrifgit** [comment]
Lust types

[Fury of the Aspects](https://www.wowhead.com/spell=397744/fury-of-the-aspects) ---> [Exhaustion](https://www.wowhead.com/spell=390435/exhaustion)
[Heroism](https://www.wowhead.com/spell=32182/heroism) ---> [Exhaustion (but different id)](https://www.wowhead.com/spell=57723/exhaustion)
[Primal Rage](https://www.wowhead.com/spell=264667/primal-rage) ---> [Fatigued](https://www.wowhead.com/spell=264689/fatigued)
[Time Warp ](https://www.wowhead.com/spell=80353/time-warp)---> [Temporal Displacement](https://www.wowhead.com/spell=80354/temporal-displacement)
[Bloodlust ](https://www.wowhead.com/spell=2825/bloodlust)---> [Sated](https://www.wowhead.com/spell=57724/sated)

**Comment by Hekili** [comment]
All of these lust types appear accounted for, so I'm not finding an obvious solution right away.

**Comment by syrifgit** [comment]
Do you need me to do more testing? Or do you agree it's the sated condition?

**Comment by Hekili** [comment]
The sated condition is wrong in the screenshot and snapshot, so I don't doubt it.  I may have to set those debuffs not to fall out of the cache.  I wonder if it falls off after exiting combat or re-entering combat.

In your snapshot, I can see temporal_displacement detected, though, and sated is an alias for any of the five debuffs you listed.  Will have to ponder a bit.  I can avoid using the alias as a workaround if I absolutely have to do so.

**Comment by syrifgit** [comment]
Not sure if you changed anything, but it's suddenly working after today's update, even out of combat at training dummies. Will update after running a few keys.

Edit: JK it broke again. Will try to do more testing.

Edit 2: So uh .. it works when I target myself but not an enemy. As soon as I target an enemy the condition goes away. tried with dummies, and random allied / enemy players around Valdrakken, Seems unrelated to combat.

back to back snapshots.

1) Targeting myself: https://pastebin.com/nS98A5BF
2) Targeting something else 2 seconds later: https://pastebin.com/TCgJhpNx

For some reason, it also popped up when I targeted this one specific mistweaver who was my faction and PvP flagged, but not anyone else regardless of PvP flag or faction.

Hope this bizarre data helps lmao

**Comment by syrifgit** [comment]
I tried modifying the APL line to

**Comment by syrifgit** [comment]
I tried modifying the APL line to 

talent.temporal_warp.enabled & (debuff.sated.up **_| debuff.temporal_displacement.up_**) & buff.bloodlust.down & ( prev_off_gcd.icy_veins | ( buff.icy_veins.up & fight_remains <= 110 | buff.icy_veins.up & fight_remains >= 280 ) | boss & fight_remains < 40 )

This had no effect. Both the sated and temportal conditions were true at the same time and false at the same time, following the weird test cases from above. True when targeting myself, false when targeting a dummy (or m+ mob)

**Comment by syrifgit** [comment]
So if you reload ui with temporal displacement on you, it fixes it. It will trigger sated condition whether you target an enemy or yourself as it should.

- You can enter combat and it will still work. You can drop combat and it will still work.
- The second you target **_Yourself_**, it breaks until you reload again. Condition will be false when targeting an enemy. 
- In summary, after fixing with a reload, you can enter combat, drop combat, target any other dummy or player in Valdrakken. All good. But **_not_** yourself. Reloading starts it over again.
- Additionally, if I target another played with a sated debuff, the condition works, whether or not it's in its "broken" state.

Is something causing it to check the target instead of the player?

**Comment by Hekili** [comment]
I'm not able to replicate using the approach you described.  Still investigating.

edit:  Now I am able to replicate it.  I *think* it has to do with aliased auras working differently for buffs vs. debuffs.

**Comment by Hekili** [comment]
I have a testfix in for v10.2.5-1.0.1-beta3.

**Comment by syrifgit** [comment]
Confirmed working on this beta btw
