### ISSUE TITLE
[REC] Outlaw recommending roll the bones after combat drop with rtb buffs active

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3133]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Using KiR build (might happen with HO but didnt test) in m+, I can have 4 buffs active with a lot of time remaining after a pack is dead. While out of combat moving to the next pack, addon recommends rtb immediately instead of waiting until buffs are timing out.

### How to Reproduce

Hit dummies until you get 4+ buffs with a good amount of time remaining, then vanish / drop combat. Addon will recommend RTB regardless of buff status which is potentially losing buffs.

### Snapshot (Link)

https://pastebin.com/bhjsMvQ5

**Comment by Hekili** [comment]
It's not "regardless of buff status" though it is questionable.

```
 - this entry's criteria PASSES: variable.rtb_reroll[true] | rtb_buffs[4.00] = 0 | rtb_buffs_max_remains[18.69] <= 2 & set_bonus.tier31_4pc[1.00] | rtb_buffs_max_remains[18.69] <= 7 & ( cooldown.shadow_dance.ready[false] | cooldown.vanish.ready[false] )
```

`variable.rtb_reroll[true]` is the condition passing that allows for the reroll.  Based on the snapshot, it looks like `precombat - 6` is the entry that ticks `variable.rtb_reroll` from `false` to `true`.

**Comment by Hekili** [comment]
Wait, found an issue.  There is an entry out of order.

**Comment by fzarr** [comment]
I'm pretty sure I've also seen cases while still in combat where its rolling off buffs it shouldn't be, but I haven't been able to snapshot it.

I will try the latest version and see how it feels.

**Comment by spinosaurs** [comment]
could it be due to the set bonus of outlaw where roll the bones will refresh a bonus?

**Comment by fzarr** [comment]
The issue with rtb being recommended after going out of combat with buffs rolling seems to have been fixed. I have seen instances of buffs recommending to be re-rolled when it doesn't look like they should (not tier31 related). Ill make a new ticket for this - seems to be a KiR specific problem.
