### ISSUE TITLE
[REC] Outlaw KiR sometimes recommending rerolling buffs when it appears it shouldn't?

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3136]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've noticed that occasionally playing the KiR build that when having 4+ buffs with significant time remaining they are being recommended to be re-rolled when it 'feels' like they shouldn't, outside of the one case where you rtb with loaded dice with kir-generated buffs.

In the attached snapshot I have 4 buffs with 25s left but I'm getting recommended to reroll, even though KiR has 3m remaining on cooldown so its extremely unlikely that the 4 buffs were generated by KiR (unfortunately I can't see if buffs are from from RTB or from KiR in my UI).

I've noticed the snapshot tags the current buffs with keep_it_rolling, and might be incorrectly refreshing this status when RTB is pressed and overwriting the buffs - in fact I tested this and it seems to be the case - but this is just a wild guess and might be incorrectly interpreting the snapshot.

### How to Reproduce

Smack dummies for a while, generate some KiR buffs. It will correctly recommend adrenaline rush + rtb after < 39s but then at some point later (sometimes), it will recommend a roll the bones refresh and lose buffs prematurely.

### Snapshot (Link)

https://pastebin.com/80f9cmaL

**Comment by aycheff** [comment]
I can confirm that this has been the same case for me.

**Comment by Hekili** [comment]
In the snapshot, `rtb_reroll` tilts over to `true` in precombat #4.

```
# Crackshot builds with T31 should reroll if we won't lose over 1 buff (2 with Loaded Dice)
actions.precombat+=/variable,name=rtb_reroll,if=talent.crackshot&set_bonus.tier31_4pc,value=(rtb_buffs.will_lose<=1+buff.loaded_dice.up)
```

That doesn't seem like it should tick over; the addon knows that you have 4 buffs and that they'll be lost if you reroll:
```
Roll the Bones Buffs:
 - buried_treasure      25.63 : 30.00 lose | keep_it_rolling
 - ruthless_precision   24.94 : 30.00 lose | keep_it_rolling
 - skull_and_crossbones 25.63 : 30.00 lose | keep_it_rolling
 - true_bearing         25.63 : 30.00 lose | keep_it_rolling
```

That suggests that there's something internally incorrect with the translation for this APL entry.  I'll do some investigating.  If you have more examples, you can post more snapshots in the interim.

**Comment by Hekili** [comment]
Try 10.2.5-1.0.1-beta2 when it comes available and see if you notice a difference.  I'll need new snapshots from here forward.

**Comment by fzarr** [comment]
I haven't noticed it happening so far, but I'll keep an eye on it over the coming days. Thanks!

**Comment by fzarr** [comment]
I found another instance of this in the wild today. This happened after I pressed KiR and shortly afterwards, roll the bones. Then it recommended another roll the bones even though I had six buffs active with 30s left on them. I felt it was wrong so I pressed RTB for science and it dropped me to only 3 buffs afterwards.

https://gist.github.com/fzarr/303536bb2cf3594944e1df2cb626c110

**Comment by Hekili** [comment]
Yeah, that snapshot is an odd one.  It does believe you'd keep 5 buffs, but I don't know what the logic is around the 6th.

**Comment by fzarr** [comment]
I can't seem to recreate it on the dummies so I'm wondering if its something that only happens if you go in and out of combat with buffs already up. Here is a log of combat, maybe you can look at the buffs in the snapshots and see if the flags are as expected. The recommendations all look OK except in step 6, there is a reroll recommended with 13 seconds left on 5 buffs, although this might be because a long subterfuge window is coming up, but possibly is related to the issue.

1. Initial 2 buffs rolled pre-combat: https://gist.github.com/fzarr/3594e28008110e9958d350fe18b02a2f
2. RTB pressed with 2 buffs active and loaded dice after ADR pressed: https://gist.github.com/fzarr/a0121ed9c9a69c644b57e871d8555e43
3. KiR pressed, two extend the previous 3 RTB buffs, plus one buff generated from CTO. Its flagging the KiR buffs as 'lose', I don't know if this means anything, but KiR buffs are only lost if the time runs out, not if RTB is rolled: https://gist.github.com/fzarr/35f440ac9274868d56bcc3fd6d51a2c8
4. Dispatch procs a CTO: https://gist.github.com/fzarr/513121050c01ca597d41d8ea7386dc6e
5. After RTB pressed - I think what happens here is all 4 KiR generated buffs from step 3 get extended, and the Grand Melee buff is kept from the T31 tier set or rolled by RTB naturally. I don't know why the GM buff is marked as being from keep_it_rolling as it wasn't a buff extended by KiR in step 3. It also might be sus that all of the other buffs are also still marked as keep_it_rolling: https://gist.github.com/fzarr/b194237e174a2a01f4fcef210af60bdb
6. The next RTB recommendation after step 5 - it has 5 buffs at 13s left, **I feel like this is too early to recommend a reroll but this is perhaps correct** - however it might be because the addon thinks they are from kir and wont actually be lost?: https://gist.github.com/fzarr/4662c9fdd4e60e66c6c46b5c0634675d
7. The resulting snapshot after RTB is pressed after step 6, I guess the remaining 9s of TB is there because the TB buff was generated from KiR in step 3 and was never overwritten by RTB so wasn't lost, However this time, the GM buff is flagged as from RTB but RP and SnC buffs are flagged as from keep_it_rolling - not sure why they would be different and also not sure if they should still be marked as keep_it_rolling buffs after two subsequent roll the bones casts since the last KiR and since they were refreshed with a higher duration it seems clear they were generated by roll the bones: https://gist.github.com/fzarr/36a657720068b1513c00569a52012388

My thought is that perhaps there is active combat state that makes this work, but when combat is dropped and re-entered that the state is cleared and incorrect decisions are made based on incorrect flags being associated with the buffs.

**Comment by fzarr** [comment]
And another one that happened in a m+ run today. These are different to the above cos it does seem to flag some buffs as 'keep' but it seems to be doing it incorrectly.

Recommending RTB (3rd action including a kick) when it has buffs that I felt would be (incorrectly) rolled off: https://gist.github.com/fzarr/f7cfc0f47f3adead0621fca489c6c50e
Right after RTB is pressed, buffs rolled off to 3: https://gist.github.com/fzarr/70591ef5935198c7c1632946a267ef8e

**Comment by Hekili** [comment]
Just wanted to emphasize that I'm not ignoring this, it's just hard to investigate.  You've done a good job providing snapshots.  I might need actual logs because I *think* what might be happening is that one cast of RtB is proccing buffs on multiple frames instead of all results at once.  There are instances in your snapshots where some of the buffs are only 0.01s different in duration from the others.  That might be confusing the code that decides what is going to get rerolled.

**Comment by fzarr** [comment]
I should have a log for the run that correlates with the snapshots taken in my last post. The previous post with the test on the dummies I don't but that should be easily re-creatable.

Is it better if I send you the raw combat log text file or would you prefer a WCL upload?

**Comment by Hekili** [comment]
WCL would be way better.

**Comment by fzarr** [comment]
Here's the log of the m+ run where i noticed the falling off of debuffs and posted the associated snapshots of on Friday last week, hopefully you can correlate the snapshot to when it happened: https://www.warcraftlogs.com/reports/a:mzM9BbvKV7k1acQ3 Exact timestamp the run starts at is 17:00:43 (looks like it happens at about 30s into the run with the troublesome second RTB cast occurring around 40s).

Note that there are some buffs rolled via a combination of both roll the bones and keep it rolling before the key (and combat log) starts so that could have something to do with it, but ive also seen this happen further into a key.

**Comment by fzarr** [comment]
I've noticed that sometimes buff timers are not synced up when you kir and rtb after, 1+ buff might get a duration of around one second less than the others so probably your theory is correct. I haven't been playing non-kir recently but i think it only applies to buffs that have been extended by KiR.

**Comment by Hekili** [comment]
I think, generally, I need to change how I'm flagging whether spells are extended by KiR or not.  Right now, it watches for a cast of KIR and then the next aura events are flagged as KIR-driven.  But the logs look like the aura refreshes actually occur before the KiR cast event fires.  It's something I probably won't get to until I'm back from vacation, so we're looking at middle of March at best.

**Comment by fzarr** [comment]
No worries, enjoy your break!

**Comment by IIeTpoc** [comment]
There is a very complex and complicated WA that is able to differentiate between RTB and KIR buffs, and helps to recommend when to use RTB and KiR. 
I tried it out and it seems to track buffs without the above problem.
I am not a programmer by any means, but it might be useful in implementing a new way of detecting KiR buffs from Hekili. 
The problem is, besides KiR and RtB, it tracks a bunch of other stuff, so I have not managed to find the exact triggers and buff tracking method.

https://wago.io/Pd53s_NPU

**Comment by IIeTpoc** [comment]
@Hekili I just noticed that there is a local "bone" in line 561, but the first definition of "local bone" does not come until line 579.
Also, considering that in the logs it looks like the aura refreshes actually happen before the KiR cast event fires:
Can we track the prolongation of the RtB buffs, and if the RtB buff is prolonged by 30 seconds, and it is not caused by Roll the Bones itself, and Keep it Rolling is on the CD during this event, can the prolonged buffs be "flagged" as KiR-RtB buffs as a temporary measure to track if the bug above persists?

![image](https://github.com/Hekili/hekili/assets/64799395/40179f88-df4a-4e9b-bc93-e7195ad5cb83)

**Comment by Hekili** [comment]
The `bone` on line 561 doesn't matter.  But yes, I need to rework how buff extensions are tracked because the events don't occur in the expected order.  It's on my list of thing to do.
