### ISSUE TITLE
[BUG] Lion's Strength NOT Talented, STILL 4CP Finishers With Bloodtalons?

### ISSUE THREAD

**Issue by Necrochrist** [Hekili/hekili#3139]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Bloodtalons taken instead of Lion's Strength and finishers are being cast with 4 combo points.

Feral Priority Update Package:

2023-02-15:  Priority will use finishers at 4+ Combo Points when Lion's Strength is talented, consistent with latest SimulationCraft updates.

From SimC:

`ferocious_bite,target_if=max:target.time_to_die,if=combo_points=5&dot.rip.remains>8&variable.zerk_biteweave&spell_targets.swipe_cat>1`

Snapshot:

[](https://pastebin.com/ZHuTVh2C)
[](https://pastebin.com/695NDfYJ)

### How to Reproduce

1.  Enter game as Feral Druid.
2.  Face training dummy.
3.  Commence rotation.

### Player Information (Link)

https://pastebin.com/mcJaDKdR

### Error Messages (Link)

No Error Messages

### Contact Information

angelsoftheseventhdawn@outlook.com

**Comment by Hekili** [comment]
You have to take the snapshot when a 4 CP finisher is recommended and you think it shouldn't have been.

**Comment by Necrochrist** [comment]
I apologize, I'm a bit new to this.  I updated the link and added a second one.

**Comment by Hekili** [comment]
The latest SimulationCraft priority allows for usage of finishers at 4+ CP, regardless of talents.  This is likely due to folks having enough crit at this point that generating at 4 CP is likely to waste a lot of combo points.

```
actions+=/call_action_list,name=finisher,if=combo_points>=4
```

```
## actions.finisher+=/pool_resource,for_next=1,if=buff.bs_inc.up
actions.finisher+=/primal_wrath,if=(dot.primal_wrath.refreshable|(talent.tear_open_wounds.enabled|(spell_targets.swipe_cat>4&!talent.rampant_ferocity.enabled)))&spell_targets.primal_wrath>1&talent.primal_wrath.enabled
# with t31 you can rip a few seconds early as to use bite inside of feral frenzy instead. During smoldering you can delay refreshing rip.
actions.finisher+=/rip,cycle_targets=1,if=((set_bonus.tier31_2pc>0&cooldown.feral_frenzy.remains<2&dot.rip.remains<10)|(time<8|buff.bloodtalons.up|!talent.bloodtalons.enabled|(buff.bs_inc.up&dot.rip.remains<2))&refreshable)&(!talent.primal_wrath.enabled|spell_targets.swipe_cat=1)&!(buff.smoldering_frenzy.up&dot.rip.remains>2)
## actions.finisher+=/pool_resource,for_next=1,if=!action.tigers_fury.ready&buff.apex_predators_craving.down
actions.finisher+=/ferocious_bite,max_energy=1,cycle_targets=1,if=buff.apex_predators_craving.down&(!buff.bs_inc.up|buff.bs_inc.up&!talent.soul_of_the_forest.enabled)
actions.finisher+=/ferocious_bite,cycle_targets=1,if=(buff.bs_inc.up&talent.soul_of_the_forest.enabled)|buff.apex_predators_craving.up
```
