### ISSUE TITLE
Hekili & Spellflash

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#314]
Latest version of all addons.

So I enable Spellflash in Hekili and it is flashing (from center out) but its also flashing while NOT IN COMBAT!

I have the toggle "In Combat only" checked in Spellflash addon but icons are still flashing like crazy, if I click on the flashing button, it just goes to next action in the rotation (while NOT IN COMBAT)

Can this be resolved?

Thanks

**Comment by Hekili** [comment]
You only need 1 issue thread.
