### ISSUE TITLE
[BUG] Recommendation Changes After Targeting

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#3142]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hello,

My retribution paladin spell **Execution Sentence** disappears when I select an enemy target. The spell won't show up in the queue or anywhere during a rotation. I tried the rotation for two minutes and it won't show up. It will show in the queue when I target myself and it goes away again when I target a friendly and yes, the talent is enabled. I even did a profile reset, uninstalled the addon, cleared the WoW cache but still the same. It seems that it started when I updated the addon to **10.2.5-1.0.0**

Iin the Paste bin there are two types of info, one where I selected myself and one where I selected an enemy target.

### How to Reproduce

The problem starts when I select an enemy target.

### Player Information (Link)

https://pastebin.com/vwBY0My9

### Error Messages (Link)

No error messages

### Additional Information

There are no error messages

### Contact Information

jackthedipper

**Comment by Hekili** [comment]
You might be targeting a dummy that has almost no health remaining; its "time to die" is estimated to be 5 seconds and Execution Sentence is only recommended if the target will live 12 seconds.

**Comment by ghost** [comment]
I just tested it, and you are right. This is the first time I have seen this, and I have been using Hekili for a while. However, can this be changed for dummies only? If I want to test my rotation or want to see how much dps I can do (without using sim) then this is annoying.

But thank you for replying

**Comment by masterkain** [comment]
is "time to die" also applied to pvp players?

**Comment by Hekili** [comment]
Yes.
