### ISSUE TITLE
[BUG] Destruction Warlock Priority recommend Swap Target show all target if "Havoc" and "Immolate" up on difference target

### ISSUE THREAD

**Issue by nuttin0011** [Hekili/hekili#3144]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![image](https://github.com/Hekili/hekili/assets/74884682/d0367796-419a-46e8-ac4c-9c5c13148d68)
i have 2 target and use "recommend target swaps" options
if i have 2 target and rotation want to Dot "Immolate" both 2 target

i Dot Immolate at 1st target
and Havoc at 2nd target (or Mayhem proc it's automatically Havoc at 2nd target)
when i target 1st target Priority show "Swap target" and i press "tab" to swap
then i swap to 2nd target but Priority still show "Swap target"

i think i should Dot "Immolate" at 1st target for best benefit
and i want "do not show Swap target icon" this case

please help

### How to Reproduce

1. Warlock Destruction
2. use Recommend Target Swaps option
3. i have 2 ( or more ) target
4. DOT Immolate at 1st target ( or all target excepts last target)
5. cast Havoc at 2nd target ( or cast Havoc at last target, may be Mayhem Proc) 
6. all target will have Immolate + "Swap target Icon" show

### Player Information (Link)

https://pastebin.com/dhF1LQbp

### Error Messages (Link)

-

**Comment by Hekili** [comment]
Assuming the white outline means that is your current target, the addon does recommend switching off of the target that has Havoc applied.  Am I misunderstanding the image?

**Comment by nuttin0011** [comment]
yes

when i target Havoc debuff target the addon recommend switching off
when i target Immolate debuff target the addon still recommend switching off

**Comment by Hekili** [comment]
The addon recommends not targeting the enemy that has Havoc applied.  That's intentional.  You're wasting Havoc if you're nuking your current target while Havoc is applied.

It's true that applying Immolate to a secondary target resolves that cast, but you still want your Incinerate and Chaos Bolts going into a different target than Immolate.
