### ISSUE TITLE
[REC] Thunder Clap

### ISSUE THREAD

**Issue by Lejes9X** [Hekili/hekili#3146]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Thunder Clap is not being suggested in the rotation when off cooldown as a rage generator

### How to Reproduce

1. Protection Warrior
2. Use Thunder Clap
3. Rotation as normal
4. Thunder Clap off CD and doesnt suggest using.
5. Tier Empowered Shield Slam proc from tier suggested before using Thunder Clap while off CD

### Snapshot (Link)

N?A

**Comment by Lejes9X** [comment]
Reverted back to v10.2.5-1.0.0 Thunder Claps are suggested.

**Comment by Arrhae** [comment]
#3145 should fix this, a number of prot warrior talent/spell IDs got set to their fury variants.

**Comment by Hekili** [comment]
This should be resolved in 1.0.1c.
