### ISSUE TITLE
Protection Warrior completly not working

### ISSUE THREAD

**Issue by ConnerMcLoud** [Hekili/hekili#3148]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Protection Warrior is only using the cooldowns and Shield Slam, Revenge and Ignore Pain all other attacks are not shown. In the Options all attacks are enabled. I Also deleted and istalled Hekili new. Now change

### How to Reproduce

1. Enter Game as Prot Warrior
2. Start Rotation an Dummy 

### Snapshot (Link)

https://pastebin.com/x0ZBPk0F

### Contact Information

tutanchamun_

**Comment by Hekili** [comment]
Upgrade to 1.0.2c.

In your snapshot, cooldowns are toggled off and defensives are toggled on.  I'd be surprised if cooldown abilities are being shown.

**Comment by ConnerMcLoud** [comment]
That was not the solution. But i found it now. I had to remove all Hekili files manually. Now it seems to work.

**Comment by Movah** [comment]
I'll try this when I get home as well.  I was having the exact same problem and I see there are some spell ID fixes, maybe it was trying to build rage with shield slam instead of something else (thunderclap).  Also I see you  had to manually remove Hekili folder and re-install from there so will make sure to do that also :)
