### ISSUE TITLE
[BUG] Resto druid priority not updating

### ISSUE THREAD

**Issue by ryantharper** [Hekili/hekili#3150]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Resto druid doesn't work, it might work for the first queued spell, but then doesn't update. It will stay on the same 3 spells, and it will sometimes update after using Ferocious Bite or Sunfire, but then stay on the same three spells. Works fine when I switch to Feral/Balance and tried on Mistweaver and works fine on that too.

### How to Reproduce

Start resto druid rotation on a dummy (AoE dummies or ST dummy)

### Player Information (Link)

https://pastebin.com/cQiMSwYw

### Error Messages (Link)

https://pastebin.com/YtnBn9JC

### Contact Information

harpR19

**Comment by chrisleaman** [comment]
Similar issue for me, too.

**Comment by apedley** [comment]
Reverting to v10.2.5-1.0.0 fixed this for me so I believe this has to do with the feral rip duration change.

**Comment by Pallyman** [comment]
same issue

**Comment by Hekili** [comment]
This should be resolved in 1.0.3.

**Comment by chrisleaman** [comment]
Fixed for me, thanks for the fast turn around!
