### ISSUE TITLE
[REC] Inconsistent Fyrakk's Tainted Rageheart

### ISSUE THREAD

**Issue by Shankmaster4k** [Hekili/hekili#3152]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Recent updates seems to have greatly reduced the frequency of the recommendation of Fyrakk's Tainted Rageheart. It seems to be recommending the use of this trinket at seemingly random times, and not nearly on the frequency of it's cooldown. This seems to be a recent change in the last 2-3 versions as last week it wasn't doing this.

### How to Reproduce

1. Enter game as paladin with Fyrakk's Tainted Rageheart equipped. 2. Utilize the following talent build: BIEAomTTpSA9oX6huYLb5nP3r3SaJSKi2B0iko0kkIRkIBAAIAAAAAAAgmQSCBSCJpIgAAiABgACQA
3. Enter combat for 1-2 minutes with (Boulderfist or cleave training dummies both) trinket equipped, cooldowns toggled to be included in Hekili recommendations.
4. See that rageheart isn't recommend at all within 2 minutes of combat irrelevant to damage taken or current HP

### Snapshot (Link)

https://pastebin.com/grS0vtGz

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wM5rXW4Tm1gpgHXnURtTnX

### Contact Information

Disc: Aliwicious or Aliwicious#9177

**Comment by syrifgit** [comment]
take a snapshot during avenging wrath. Looks like it is checking the following conditions

1) fight remaining - this usually doesn't work well on dummies
2) Double on-use (doesnt affect you)
3) avenging wrath to be up

**Comment by Shankmaster4k** [comment]
@syrifgit I'm currently running the sentinel talent, but here's a paste bin of the snapshot with Sentinel up 

https://pastebin.com/QfBnCwmT

**Comment by syrifgit** [comment]
Looks like it's still showing avenging wrath as false when you talent into Sentinel even though it's still increasing your damage. Might need some new logic added to the trinket lines that are waiting for wrath when people take Sentinel @Hekili 

@Shankmaster4k does it work if you swap that talent out for the crit version?

**Comment by Shankmaster4k** [comment]
@syrifgit it DOES look to be recommending it if talented into Avenging Wrath proper. 

https://pastebin.com/WkLxDqxt

**Comment by Hekili** [comment]
Please try 1.0.4-beta1.

**Comment by Shankmaster4k** [comment]
@Hekili As of v10.2.5-1.0.4 it looks to be recommending again on CD with both Avenging Wrath and Sentinel talented in! Thank you so much for the super fast fix.
