### ISSUE TITLE
[BUG] Addon Compartment error on mouseover

### ISSUE THREAD

**Issue by nancikennedy** [Hekili/hekili#3153]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On a character that is too low to make use of Hekili, I do not have it loaded. However, it is still showing as an entry in the Addon Compartment. When mousing over it, it's generating (I assume because it's not actually loaded).

### How to Reproduce

1. Log into a character who DOESN'T have Hekili loaded
2. Mouse over the entries in the Addon Compartment, making sure to pass by the Hekili entry
3. Error happens

### Player Information (Link)

Can't open Hekili as it's not loaded as stated in description of issue above.

### Error Messages (Link)

https://pastebin.com/J83WxJnx

**Comment by nancikennedy** [comment]
Adding pic...
![Hekili-AC-Error](https://github.com/Hekili/hekili/assets/8207666/9be530b7-d70c-4c0f-9e61-626e85003342)

**Comment by Hekili** [comment]
This should be resolved in 1.0.3.
