### ISSUE TITLE
[BUG] error attempting to index field 'empowerment' on Devastation

### ISSUE THREAD

**Issue by Gnathach** [Hekili/hekili#3154]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have been randomly getting this message when in Devastation spec using WoWhead's "leveling" build at L70.  This has been going on for a number of months now through multiple WoW and Hekili updates

`2x Hekili/UI.lua:2548: attempt to index field 'empowerment' (a nil value)
[string "@Hekili/UI.lua"]:2548: in function <Hekili/UI.lua:2547>
[string "=[C]"]: ?

Locals:
self = Hekili_Primary_B1_Cooldown {
 0 = <userdata>
 _occ_priority = 1
 _occ_show = false
 _occ_gcd = true
 noCooldownCount = false
 lastDuration = 1.300000
 _occ_kind = "default"
 _occ_duration = 1.300000
 _occ_settings = <table> {
 }
 _occ_start = 95373.877000
 lastStart = 95373.877000
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'empowerment' (a nil value)"
b = Hekili_Primary_B1 {
 Overlay = Texture {
 }
 Empowerment = Hekili_Primary_B1_Empower {
 }
 Highlight = Texture {
 }
 Keybinding = Hekili_Primary_B1_KB {
 }
 PixelSnapDisabled = true
 lastAction = "fire_breath"
 Targets = Hekili_Primary_B1_Targets {
 }
 Text = false
 Image = 4622458
 0 = <userdata>
 Action = "fire_breath"
 targetShown = false
 glowing = false
 Icon = Texture {
 }
 Texture = Texture {
 }
 index = 1
 Caption = Hekili_Primary_B1_Caption {
 }
 unusable = false
 Keybind = "SW"
 DelayText = Hekili_Primary_B1_DelayText {
 }
 KeybindFrom = 1
 Backdrop = Hekili_Primary_B1_Backdrop {
 }
 texCoords = <table> {
 }
 glowStop = <function> defined @Hekili/UI.lua:2479
 Ability = <table> {
 }
 DelayIcon = Hekili_Primary_B1_DelayIcon {
 }
 EmpowerLevel = Hekili_Primary_B1_EmpowerLevel {
 }
 display = "Primary"
 ExactTime = 95375.177000
 Cooldown = Hekili_Primary_B1_Cooldown {
 }
 Recommendation = <table> {
 }
}
conf = <table> {
 primaryWidth = 45
 rel = "CENTER"
 numIcons = 4
 queue = <table> {
 }
 y = -371.086884
 x = -72.657486
 primaryHeight = 45
}
state = <table> {
 swing = <table> {
 }
 FindPlayerAuraByID = <function> defined @Hekili/Utils.lua:516
 summonPet = <function> defined @Hekili/State.lua:1188
 role = <table> {
 }
 IsKnown = <function> defined @Hekili/State.lua:7007
 UnitGUID = <function> defined =[C]:-1
 purge = <table> {
 }
 stat = <table> {
 }
 ptr = 0
 off_hand = <table> {
 }
 floor = <function> defined =[C]:-1
 essence = <table> {
 }
 tonumber = <function> defined =[C]:-1
 SetWhitelist = <function> defined @Hekili/State.lua:6722
 holds = <table> {
 }
 display = "Primary"
 prev_off_gcd = <table> {
 }
 SetDefaultVariable = <function> defined @Hekili/State.lua:4494
 mainhand_speed = 3.121000
 channelSpell = <function> defined @Hekili/State.lua:1251
 equipped = <table> {
 }
 gain = <function> defined @Hekili/State.lua:1559
 TimeToReady = <function> defined @Hekili/State.lua:7364
 setStance = <function> defined @Hekili/State.lua:1162
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 UnitAura = <function> defined @Blizzard_Deprecated/Deprecated_10_2_5.lua:34
 AddToHistory = <function> defined @Hekili/Events.lua:1082
 SetupCycle = <function> defined @Hekili/State.lua:796
 print = <function> defined @Hekili/State.lua:570
 GetSpellCount = <function> defined =[C]:-1
 ClashOffset = <function> defined @Hekili/State.lua:7581
 azerite = <table> {
 }
 offset = 4.870000
 QueuedCastRemains = <function> defined @Hekili/State.lua:6280
 ApplyCastingAuraFromQueue = <function> defined @Hekili/State.lua:6304
 TargetBuffUp = <function> defined @Hekili/State.lua:5819
 pvptalent = <table> {
 }
 rawGain = <function> defined @Hekili/State.lua:1566
 GetItemGem = <function> defined =[C]:-1
 UnitIsFriend = <function> defined =[C]:-1
 action = <table> {
 }
 addStack = <function> defined @Hekili/State.lua:1036
 HasRequiredResources = <function> defined @Hekili/State.lua:7327
 TargetDebuffUp = <function> defined @Hekili/State.lua:5824
 UnitCanAttack = <function> defined =[C]:-1
 rawSpend = <function> defined @Hekili/State.lua:1579
 script = <table> {
 }
 IsUsable = <function> defined @Hekili/State.lua:7185
 GetItemInfo = <function> defined =[C]:-1
 GetPlayerAuraBySpellID = <function> defined =[C]:-1
 health = <table> {
 }
 `

### How to Reproduce

Start attacking as Devastation spec evoker following the recommended Heili rotation.  Randomly but quite frequently the error occurs.

### Player Information (Link)

https://pastebin.com/EYzR19f6

### Error Messages (Link)

https://pastebin.com/V3brDZPP

**Comment by Hekili** [comment]
I think this is already fixed in 1.0.3; I could not replicate it.  Can you confirm after updating to the latest release?

**Comment by Gnathach** [comment]
> I think this is already fixed in 1.0.3; I could not replicate it. Can you confirm after updating to the latest release?

Thanks it does seem to finally be behaving now, but it didn't always do it either.  I'll re-open if it shows back up again, or create a new ticket whichever is better.
