### ISSUE TITLE
WF and FT are applied to weapons but keeps showing them - seems only a problem with AOE helper

### ISSUE THREAD

**Issue by Janavda** [Hekili/hekili#3157]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

WF and FT are applied to weapons but the priority helper/flash icon keeps showing them - seems only a problem with AOE helper.
![Schermafbeelding 2024-01-25 182822](https://github.com/Hekili/hekili/assets/157733999/bcc895dd-cffc-4887-b7e7-603b2f045e63)

### How to Reproduce

Always showing

### Player Information (Link)

x

### Error Messages (Link)

x

**Comment by Hekili** [comment]
This should be a recommendations ticket and the snapshot would be required.

Make sure you're using the latest release and submit a new ticket.
