### ISSUE TITLE
Toggling COOLDOWNs for rotation produces error

### ISSUE THREAD

**Issue by cgnlegend** [Hekili/hekili#316]
**BEFORE SUBMITTING AN ISSUE:**

1.  I have the most current version

2.  I could not find any other reports of this issue

**Describe the Bug/Issue**
I use the "/" to turn my cooldowns on and off before a boss fight.  When I press "/" I get the following error
"Message: Interface\AddOns\Hekili\Options.lua:9386: attempt to call field 'ScanEvents' (a nil value)
Time: Sun Apr  5 11:57:54 2020
Count: 3
Stack: Interface\AddOns\Hekili\Options.lua:9386: attempt to call field 'ScanEvents' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:733: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:693>
[string "=[C]"]: in function `ScanEvents'
[string "@Interface\AddOns\Hekili\Options.lua"]:9386: in function `FireToggle'
[string "@Interface\AddOns\Hekili\UI.lua"]:2002: in function <Interface\AddOns\Hekili\UI.lua:2001>

Locals: errMsg = "Interface\AddOns\Hekili\Options.lua:9386: attempt to call field 'ScanEvents' (a nil value)"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:514
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:132
 hitInternalError = false
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:495
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:480
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:488
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:328
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:380
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:456
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:297
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"   "
I turned my Tradeskill master off completely by disabling in the Addons and reloaded the game.  When I did that I pressed the "/" and still get an error but shorter.  The following message is the new error message

"Message: Interface\AddOns\Hekili\Options.lua:9386: attempt to call field 'ScanEvents' (a nil value)
Time: Sun Apr  5 12:02:52 2020
Count: 1
Stack: Interface\AddOns\Hekili\Options.lua:9386: attempt to call field 'ScanEvents' (a nil value)
[string "=[C]"]: in function `ScanEvents'
[string "@Interface\AddOns\Hekili\Options.lua"]:9386: in function `FireToggle'
[string "@Interface\AddOns\Hekili\UI.lua"]:2002: in function <Interface\AddOns\Hekili\UI.lua:2001>

Locals: "

I tried right-clicking my datatext bar where Hekili is located to open the dialog box, then I select toggles on the left and go to the box associated with "cooldowns" and check the box to turn it on or off.  I get another error message below:

"Message: Interface\AddOns\Hekili\Options.lua:9386: attempt to call field 'ScanEvents' (a nil value)
Time: Sun Apr  5 12:14:51 2020
Count: 2
Stack: Interface\AddOns\Hekili\Options.lua:9386: attempt to call field 'ScanEvents' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Hekili\Options.lua"]:9386: in function `FireToggle'
[string "@Interface\AddOns\Hekili\Options.lua"]:6388: in function <Interface\AddOns\Hekili\Options.lua:6376>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:290: in function `Fire'
[string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: <none> "

When I open the "Issues reporting" tab I immediately get the following in my error window

"Message: Interface\AddOns\Hekili\Utils.lua:183: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sun Apr  5 12:18:16 2020
Count: 2
Stack: Interface\AddOns\Hekili\Utils.lua:183: bad argument #1 to 'pairs' (table expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `pairs'
[string "@Interface\AddOns\Hekili\Utils.lua"]:183: in function <Interface\AddOns\Hekili\Utils.lua:177>
[string "@Interface\AddOns\Hekili\Utils.lua"]:195: in function `(for generator)'
[string "@Interface\AddOns\Hekili\Options.lua"]:7461: in function `?'
[string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:225: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1192: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: in function `FeedGroup'
[string "@Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:290: in function `Fire'
[string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:515: in function `SetSelected'
[string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:191: in function <...ce3\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:187>

Locals: <none> "

**Expected behavior**
What I expect to happen is my cooldowns option during my rotation to appear in the rotations.  They do see to appear as they are supposed to but not without having to clear the error message which often times I find myself doing during a boss fight, which is when I turn my cooldowns on for my rotation.  

NOTE: In all of my copy and paste of the error messages, I add quotation marks at the beginning and end of each message even if there already was a quotation mark present from the message itself there.  I know it may seem obvious, but just clarify to be as thorough and clear as possible.

I use ElvUI as my main UI interface.  It does not seem to matter which character I am on to produce the error.  I tried it on a Ret and Prot pally, and a Holy priest over the last few days.

**Comment by Hekili** [comment]
The only reason this would happen is if you have something pretending to be WeakAuras without WeakAuras installed or up and running.

**Comment by cgnlegend** [comment]
Ok I do have weak aura downloaded, I do not think it is enabled but I will look into that. I have it and never really use it but have it as a back up. If you don’t hear from me again then you were correct and it worked. Thank you for the help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Hekili** [comment]
I'm putting in some babyproofing for this that I shouldn't have to do.  Closing this ticket.

**Comment by cgnlegend** [comment]
Thanks for your help. I know nothing about code and most of those error messages are hard to decipher which addon is the culprit.  Hopefully I didn’t want to much of your time. At least it was easy to figure out. I love you addon and despite the naysayers who claim a player should learn there spec and not rely on mods like this, I find that these types of addons help learn the spec and rotation. Thanks you for your work and god luck.

Sent from my iPhone

On Apr 10, 2020, at 09:35, Hekili <notifications@github.com> wrote:

﻿

I'm putting in some babyproofing for this that I shouldn't have to do. Closing this ticket.
