### ISSUE TITLE
Ironfur not being suggested in rotation despite having 6 Stacks selected for threshold 

### ISSUE THREAD

**Issue by RumbleDumble** [Hekili/hekili#3161]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Ironfur is not being suggested in rotation despite having 6 Stacks selected for threshold, most I got to from pure suggestions was 5 

### How to Reproduce

1.) Enter game as Guardian Druid

2.) Take these talents - BgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQiIJSJUSSgkiESShCAJJASgkkESSSBahAAAAAAEBkQIA

3.) Do rotation 

### Snapshot (Link)

https://pastebin.com/gs4r1rjG

### Contact Information

bigoltiddymuncher

**Comment by Hekili** [comment]
So the way this caps stacks is by not recommending Ironfur within `7 / x` seconds of another Ironfur cast.  So when set to 6, that's a 1.166667 internal cooldown on Ironfur.  If you follow it strictly, you'll only *just* reach your 6th stack in 7 seconds, assuming you're also producing resources fast enough to use Ironfur that frequently.

I'm mostly okay with how it's working at the present time.  You can always allow more, but you're never going to be able to Ironfur more than your resources allow.
