### ISSUE TITLE
Is it possible to add a option similar to 'Check Movement' in Action Lists's 'Show Modifers', for each spell in the Abilities module?

### ISSUE THREAD

**Issue by hellovvorld1024** [Hekili/hekili#3162]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Each spell in Action Lists has multiple conditions for triggering. In order to prevent the same spell from being recommended during movement, several times need to be modified. 

Can similar options be added to the Abilities module to set Check Movements conditions for a certain spell?

**Comment by Hekili** [comment]
This can already be addressed with existing features.  Why does it need to be in multiple places?  What's the rationale for the change?

**Comment by hellovvorld1024** [comment]
Spell in Action Lists has multiple conditions corresponding to it.

If I want to achieve the spell and Check Movements under any circumstances, I need to search for the spell multiple times in multiple categories of Action Lists, such as cooldowns and precombat, and modify it multiple times.

If can modify it in Abilities module, maybe only need to modify it once and the spell will be easier to find out. Because each spell has one and only one in Abilities module.

**Comment by Hekili** [comment]
I'm not going to implement this as asked, but I am thinking about how to make it easier to configure changes at a per ability vs. per priority vs. per action level.
