### ISSUE TITLE
[REC] Warrior Spear of Bastion is now Champions Spear

### ISSUE THREAD

**Issue by caist4321** [Hekili/hekili#3163]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Fury Warrior Spear of Bastion is now Champions Spear.

### How to Reproduce

1. Enter the game as Fury Warrior 
2. Talents as follows: BgEAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAACBCKBQESICENQICEJhEQkkESSSkERapkkAkEAAAEQQA
3. Rotation does not show Champions Spear

### Snapshot (Link)

https://pastebin.com/5m2Qia4j

**Comment by Hekili** [comment]
You should take the snapshot at a time when you think the priority should show Champion's Spear.

![image](https://github.com/Hekili/hekili/assets/9438134/5ea21006-ba4e-46e3-a0b9-0592b1329d22)

In your snapshot, cooldowns are toggled off, so CS wouldn't be shown unless you removed it from the toggle:

```
toggles: cooldowns = false 
```

See /hekili > Toggles.
