### ISSUE TITLE
[REC] Sub rogue: prediction of rupture usage can swap places

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3165]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

This is mainly just to sense check that theres not something modelled incorrectly causing the jump around.

In the opener prediction, it will recommend rupture before shadow dance in 6 globals time, but changes it to after shadow dance (sim-correct behaviour) once some globals (e.g. flagellation) are pressed. However it can seem to shift back and forth over time, seemingly at random.

Attached four snapshots. Pastebin was down at time of posting

1. Opener with rupture predicted pre-shadow dance as 6th action - https://gist.github.com/fzarr/90a15532276b74f05aeb9a02d7b84d6d
2. Rupture switched to be used after dance once the opening shadowstrikes and flagellation used - https://gist.github.com/fzarr/c79135ee22373f3a2e3f9ddf5dcba1d1
3. Rupture switched back to before dance after some time and other globals used - https://gist.github.com/fzarr/c6b27ff23a306f6f64ff34a8074aa433
4. Rupture switched back to after dance after some further time has elapsed - https://gist.github.com/fzarr/4e023a4412ff1a80c41876c226c9ab13

### How to Reproduce

1. Begin opener on single target dummy
2. Rupture will be recommended before shadow dance
3. Follow the opening rotation. At some point rupture will switch to be recommended to after shadow dance (expected sim behaviour)
4. It can jump back and forward quickly a few times if rupture isnt used

### Snapshot (Link)

https://gist.github.com/fzarr/90a15532276b74f05aeb9a02d7b84d6d

**Comment by Hekili** [comment]
It's most likely due to Shadow Techniques.

**Comment by Hekili** [comment]
Can you provide a few comparable quick-sims to see if Rupture's position is consistent in those sims?

**Comment by fzarr** [comment]
I don't know how to do anything fancy but here's three separate quick sim iterations of a standard ST patchwerk fight. All have the same opener order.

https://www.raidbots.com/simbot/report/vpXcTeVtRLzizP2eV9ULHc
https://www.raidbots.com/simbot/report/7MY7ShTpKF18ghXt18xXDt
https://www.raidbots.com/simbot/report/uim8Et2RC8JMMT6KZEsDZy

**Comment by Hekili** [comment]
This may change with the bugfix in the other ticket.  Will keep investigating.

**Comment by Hekili** [comment]
Let me know if this persists -- and provide an updated snapshot -- if it does.  I just need one snapshot and for it to be explained what Rupture is trading places with in the snapshot.  Thanks!

**Comment by fzarr** [comment]
Still seems to be happening sometimes. It works correctly now precombat: https://pastebin.com/35Vsye2X
However after initial shadowstrikes it changes back to ruputre before dance: https://pastebin.com/N5xeifpP
However it seems to correct itself to be after dance eventually even if no buttons are pressed.

One thing to note is if you have any amount of shadow techniques stacks pre-combat, it will recommend rupture before dance, but I'm not sure if this is correct behaviour: https://pastebin.com/yceTxBAW

**Comment by Hekili** [comment]
> One thing to note is if you have any amount of shadow techniques stacks pre-combat, it will recommend rupture before dance, but I'm not sure if this is correct behaviour: [pastebin.com/yceTxBAW](https://pastebin.com/yceTxBAW)

Probably; the comparison to make would probably be between packs in a DungeonSlice sim.
