### ISSUE TITLE
[REC] Crash lightning range check Enhancement shaman

### ISSUE THREAD

**Issue by Cromaxxx** [Hekili/hekili#3166]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Enhance shaman crash lightning doesnt work properly in combat even on target dummies
![Screenshot 2024-01-31 013223](https://github.com/Hekili/hekili/assets/10215299/f9f7eba7-dcbb-4061-b3ab-8971b1b96d39)

### How to Reproduce

Do normal rotation when it switches from aoe to single target when you move out of range and there is only 1 target detected crash lightning is recommended even though it out of range

### Snapshot (Link)

https://pastes.io/pead78bpvc

### Additional Information

pastebin is dead so i used pastes.io

**Comment by Hekili** [comment]
Yes, Crash Lightning is used in single-target and doesn't have a range.  You're in charge of getting into range.

**Comment by Cromaxxx** [comment]
Why it can't use range check when it uses for aoe?
