### ISSUE TITLE
[REC] Sub rogue (aoe) not refreshing slice and dice outside of shadow dance compared to sims

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3168]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon seems to not refresh snd as aggressively as a sim does. 

Attached snapshots begin at about 0:24-0:30 into the quicksim, following the preceding globals as close as possible. Quick sim always seems to refresh slice and dice after the second shadow dance but the addon never suggests it. Might not be a problem but thought I'd raise it as it could be an indicator of something else.

As an aside, it also feels like it doesn't properly calculate how early the next sectech will be ready by and feels like it delays the shadow dance until sectech is fully off cooldown. This is referenced by the comment here: https://github.com/Hekili/hekili/issues/3167#issuecomment-1919989005

Raidbots sim: https://www.raidbots.com/simbot/report/7n6bmwQq3SMVcVSR33z3mS

Snapshot 1: https://gist.github.com/fzarr/7af818fc44e4cedaba5ef21c07d3fdf8
Snapshot 2 (a few globals further past): https://gist.github.com/fzarr/42d1f83866296dc864cf3993ee4d4b61

I have a pic of the exact buttons ive pressed as part of this snapshot if needed i can DM it or something

### How to Reproduce

Hit the 5-pack dummies as sub rogue m+ spec. After the second dance usage and sectech is used, the addon will keep recommending ss/bp spam instead of a slice and dice.

### Snapshot (Link)

https://gist.github.com/fzarr/7af818fc44e4cedaba5ef21c07d3fdf8

**Comment by Hekili** [comment]
> Quick sim always seems to refresh slice and dice after the second shadow dance but the addon never suggests it. Might not be a problem but thought I'd raise it as it could be an indicator of something else.

The entry that the sim used at this point is here:

> `slice_and_dice,if=!stealthed.all&!variable.premed_snd_condition&spell_targets.shuriken_storm<6&!buff.shadow_dance.up&buff.slice_and_dice.remains<fight_remains&refreshable`
> *Refresh Slice and Dice outside of Shadow Dance.*

Shadow Dance was still active in your snapshot.  Additionally, you had 30+ seconds of Slice and Dice

As far as I can see, the addon is following the sim priority but it's possible the sim isn't modeling the Slice and Dice gains from Premeditation or something.  There's no reason you should want to SnD at the point you snapshotted.

**Comment by fzarr** [comment]
Not taking the Premeditation talent here so it can't be that. 

All I can think of is the opening SnD in the sim is only being used with 1-3 cp so it needs to be refreshed earlier. In my practice at the 5-pack dummies, I always get 5-7 cps on the opener so the initial SnD lasts for much longer. I'll see if anyone in the rogue discord has any idea why the sim might be behaving that way.

**Comment by fzarr** [comment]
OK I checked. What's happening is the sim always starts with a 5cp snd. I must have been gaining extra cps via shadow techniques by autoattacking dummies before the opening Shuriken Storm which led me to have a 6 or 7cp snd in the opener. This accounts for some of the delay delta vs the sim.

However! There is also a case for refreshing SnD with as much as 14 seconds left on the buff due to pandemic of SnD - 14s for 7cps and 12.6 for 6 cps. The addon doesn't seem to always take this pandemic duration into account but I haven't had time to test this fully - I will leave another comment with a snapshot later if I find something here.

**Comment by Hekili** [comment]
Slice and Dice's duration for pandemic purposes should be working as expected; the duration is a function of your combo points, and then pandemic checking is based on 30% of the spell's apparent application duration.

`duration = function () return 6 * ( 1 + effective_combo_points ) end,`

**Comment by fzarr** [comment]
I followed the rotation as close as possible to the sim rotation as I could, and starting with a 5cp slice and dice, the sim and addon are very comparable. However, I've included a snapshot around the global where the sim recommends slice and dice. I should have pandemic-able slice and dice duration in this snapshot (< 14s on snd and 7cp) yet it recommends a black powder before snd. I don't think this really matters and the addon probably is correct but I'll include it to see what you think: https://pastebin.com/aQFxgq8E . Maybe i was still stealth-ed at this point.

One thing ive noticed in the snapshot is that e.g. buff.shadow_dance.up will have both [true] and [false] in the one recommendation section - does the true/false status include the calculation of ! or is it always the status of the buff it follows without any APL modifiers applied?

**Comment by fzarr** [comment]
Also one other thing to comment, the behaviour of the predictions around slice and dice can vary a bit where its pushed and pulled forwards and backwards, I am guessing this has got to do with the pandemic refresh calculation. For example, here is an example followed on from a situation similar to the previous snapshot where I press black powder, but then I only generate 5cp from the shuriken storm, so it shifts to recommending rupture instead of snd (probably because a 7cp snd would have been pandemic, but a 5cp one won't be), and pushes slice and dice further down the line: https://pastebin.com/PwAsfXWd This might be technically correct but its kinda confusing as it happens.

**Comment by Hekili** [comment]
The pandemic refresh calculation shifts based on how many combo points you have at any given moment, so that may account for some variability there.  I.e., pandemic range is smaller when you have few combo points vs. when you have many.  I'm not sure it's worth investing a ton of effort into fiddling with when you're not left without SnD and there's no indication it's costing DPS through some other convoluted mechanic.
