### ISSUE TITLE
trying get it like this

### ISSUE THREAD

**Issue by mrlinuxdude** [Hekili/hekili#3169]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I lost my settings and had to re download this addon. I had it like this before in the video. But now recent update is messed up. and unable to put it like this in the video. Can you help me how can i do this again? Thanks for awesome addon. I need this addon how i had it before

https://www.youtube.com/watch?v=crlvW-b531M&t=100s

### How to Reproduce

watch the video is not so much as Reproduce stuff is left out from older version and i can not get it to how it was in the video. I had it before like this too and lost my setting had to re-download wow . and its a shame i really want it the same way i had it. please help thanks

### Snapshot (Link)

https://pastebin.com).

### Contact Information

profile

**Comment by Hekili** [comment]
I'm not going to watch the video.  You can ask specific questions, if you'd like.

**Comment by syrifgit** [comment]
There is a configuration guide in the discord that goes over all of those settings.

**Comment by mrlinuxdude** [comment]
OK Useless addon dev. I gave you my thoughts you want to make your addon better and simplify fine by me
