### ISSUE TITLE
worldvein not showing up for prot pally

### ISSUE THREAD

**Issue by bitmatt2** [Hekili/hekili#317]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Please fill out the template with the required information.  Thanks!

**Comment by bitmatt2** [comment]
on my prot pally it will never tell me to use worldvein whe i have it in my major essence slot. it will tell me to use it when i change my spec to ret. it will tell me to use crucible of flame when im in prot. but never worldvein when im prot. my info is pasted below.

build: v8.3.0-04-19
level: 120 (120)
class: PALADIN
spec: protection

talents: cavalier
    crusaders_judgment
    final_stand
    fist_of_justice
    holy_shield
    judgment_of_light
    last_defender

azerite: azerite_empowered = 3
    azerite_veins = 1
    bulwark_of_light = 2
    elemental_whirl = 1
    gallant_steed = 1
    gemhide = 1
    gutripper = 1
    inspiring_vanguard = 1
    soaring_shield = 3
    stalwart_protector = 1

essences: [worldvein_resonance] = 3, none

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    boots_of_hallucinatory_reality = 1
    breastplate_of_arterial_protection = 1
    fangproof_gauntlets = 1
    golden_empire_signet = 1
    heart_of_azeroth = 1
    illustrious_guild_tabard = 1
    ironcrest_bulwark = 1
    living_obsidian_legguards = 1
    lockjaw_shoulderplate = 1
    loop_of_pulsing_veins = 1
    malignant_leviathans_clasp = 1
    malignant_leviathans_helm = 1
    mchimbas_ritual_bandages = 1
    plunderbeards_flask = 1
    red_linen_shirt = 1
    resonating_crystal_scimitar = 1
    wardenguards_wristguards = 1

corruptions: none

itemIDs: 158075, 158152, 158164, 158373, 159407, 159432, 159437, 159463, 159618, 159804, 165464, 169223, 173821, 173836, 174172, 174173, 2575, 69209

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Protection Paladin
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
I still need this part:

> 2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
>  
> PUT SNAPSHOT LINK HERE:

Additionally, if you are only showing 1 recommendation, if you would go to /hekili > Display > Primary and increase Icons Shown to 3 or more before taking the snapshot, that would help.  Thanks!

**Comment by bitmatt2** [comment]
https://pastebin.com/3m1kebjs

**Comment by bitmatt2** [comment]
hope that worked. let me know if you need any additional info.

**Comment by Hekili** [comment]
Thanks, I had to actually get essences on my Paladin to test for this.  I've updated the APL to include the entry for Worldvein.
