### ISSUE TITLE
[FEATURE] Add option to desync windwalker's cooldowns in M+

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3170]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

In raid the behaviour is to sync but m+ it's not.

Desyncing cooldowns in M+ for windwalker supported by the class guides.

**Comment by Hekili** [comment]
Feel free to elaborate and provide snapshots when you disagree with what the addon is recommending.  It will help me to investigate what you're asking for.

**Comment by syrifgit** [comment]
I don't have any snapshots as I'm out of town, but if he can provide them, essentially Hekili is forcing windwalker to hold serenity and sync it with xuen. In raid, this is the correct behavior. But the class guides say that in m+ you just send them both on CD regardless, don't hold serenity to sync it.

Class guide: https://www.peakofserenity.com/df/windwalker/pve-guide/


Quote regarding CD sync:
In raid or single target situations, hold Serenity for Invoke Xuen, the White Tiger if you’re using an on-use stat buff trinket. If you’re not using such a trinket or you’re doing mythic+ dungeons, use Serenity on cooldown regardless of Invoke Xuen, the White Tiger.


Snapshot: @aaronlilla please try to get one during a key when serenity COULD be cast but it's not suggesting it.

**Comment by Hekili** [comment]
It looks like this could be as simple as modifying the `sync_serenity` entry to:
`raid&(equipped.neltharions_call_to_dominance|equipped.ashes_of_the_embersoul|equipped.mirror_of_fractured_tomorrows|equipped.witherbarks_branch)`

**Comment by Hekili** [comment]
Updated in 1.0.5.
