### ISSUE TITLE
Hekili - Outlaw - Confusion with Ambush

### ISSUE THREAD

**Issue by imarkvisser** [Hekili/hekili#3171]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm a bit confused in terms of what to press.
During the outlaw rotation it will suggest Ambush, but on the keybind of sinister strike which probably is because of the Audacity talent. However at times it will recommend ambush, without having Audacity buff but still using the sinister strike keybind.
Should I then use Ambush on it's own separate keybind instead?
Thanks for helping clear this up.

### How to Reproduce

Follow the outlaw rotation, observe Ambush being recommended with sinister strike keybind, but not having the ambush spell replacement. (So you effectively use sinister strike)

### Snapshot (Link)

https://pastebin.com/raw/TqK4v3p4

**Comment by Hekili** [comment]
It is recommending Ambush in the snapshot.

**Comment by imarkvisser** [comment]
I know it's recommending Ambush, my issue is with not having the Audacity buff but the addon still showing as if I should use keybind `2` which is my sinister strike.
I've found a workaround for it, so I'll close the ticket. cheers.

**Comment by rogal223** [comment]
could you tell me how you solved this problem because I also assign these 2 skills to 1 key
