### ISSUE TITLE
Hekili does a snapshot screenshot then stops making recomendations Assa Rogue

### ISSUE THREAD

**Issue by ZsomborTib** [Hekili/hekili#3172]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili does a snapshot screenshot then stops making recomendations Assa Rogue

### How to Reproduce

Doing the recomended rotation after a few CDs this happens

### Player Information (Link)

https://pastebin.com/xUWYJxP3

### Error Messages (Link)

N/A

### Contact Information

Discord: brixxchezzy

**Comment by Hekili** [comment]
Did you import something?

**Comment by ZsomborTib** [comment]
> Did you import something?

I Imported a profile from a sim, could that be the cause of this? if so, what would be the best way to use the addon. I have always been told to sim yourself and import the character profile.

**Comment by Hekili** [comment]
No, you don't need to import a profile.  Sims require tailoring to work with the addon, which I take care of for you.  You can click the circle-arrow button to reset your profile back to default.

![image](https://github.com/Hekili/hekili/assets/9438134/3e73c8fe-d8a8-415b-895c-a8da2ad6f83c)
