### ISSUE TITLE
[FEATURE] Mistweaver rotation for Invoke Chi-Ji, the Red Crane.

### ISSUE THREAD

**Issue by Shamainy** [Hekili/hekili#3173]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Would like for it to be an option for Mistweavers to have specific rotation when you cast the Cooldown "Invoke Chi-Ji, the Red Crane](https://www.wowhead.com/spell=325197/invoke-chi-ji-the-red-crane)" and only during that window. 

_Begin the Chi-Ji Rotation:_
**Cast [Invoke Chi-Ji, the Red Crane].**
**Cast [Blackout Kick].**
**Cast [Enveloping Mist].**
**Cast [Rising Sun Kick].**
**Fish for [Rising Sun Kick] resets with Blackout Kick / [Tiger Palm] and use off CD.
Continue to use [Enveloping Mist] at two stacks.**
**Reapply [Ancient Teachings] whenever it falls off with [Thunder Focus Tea] + [Essence Font] / [Jadefire Stomp]**

The request is to have this rotation override the main DPS rotation for the moment you activate Invoke Chi-Ji, the Red Crane cooldown, and also include Enveloping Mist into that rotation and only during that specific window of rotation so that you can clearly tell when you cast it at 2 stacks of the Invoke Chi-Ji, the Red Crane buff (https://www.wowhead.com/spell=343820/invoke-chi-ji-the-red-crane).

And then go back to normal rotation as the buff disappears.

### Contact Information

oskar.broske@hotmail.com

**Comment by Hekili** [comment]
I'm happy to make edits if we get clarity on what *priority* rather than sort of a script of this-then-that.  A priority list means the top thing on the list is used if it can be, if not, the next thing on the list with its conditions met is used instead.

> Cast [Invoke Chi-Ji, the Red Crane].

Always?  Whenever it's available?  I'll assume for the next spells that we're saying Chiji is active.

> Cast [Blackout Kick].

Once?  On cooldown?

> Cast [Enveloping Mist].

Once?  How do I decide how many times to cast Enveloping Mist?

> Cast [Rising Sun Kick].

On cooldown, I assume?

> Fish for [Rising Sun Kick] resets with Blackout Kick / [Tiger Palm] and use off CD.

Ok, so RSK on cooldown, but we're using Blackout Kick and Tiger Palm to proc its reset.

> Continue to use [Enveloping Mist] at two stacks.

Two stacks of what?

> Reapply [Ancient Teachings] whenever it falls off with [Thunder Focus Tea] + [Essence Font] / [Jadefire Stomp]

Where does this fit with regard to everything above?  It sounds higher priority but it's the last thing listed.

**Comment by syrifgit** [comment]
Basic overview

chiji pet up -> call action list Chiji Rotation

Chiji Rotation
1. Renewing mist if will reach 2 charges
2. if ancient teachings falling off, use thunder focus tea (for refresh via essence font)
3.  if ancient teachings falling off, refresh with essence font (even if you were unable to focus tea)
4. if you can't use essence font for some reason, use jadefire stomp to refresh instead
5. At 2 stacks of [Invoke Chi-Ji, the Red Crane](https://www.wowhead.com/spell=343820/invoke-chi-ji-the-red-crane), cast Enveloping mist
6. Rising Sun Kick
7. Spinning Crane Kick if (target >=2 & !talent.ancient_concord & !talent awakened_jadefire) | (target >= 4)
8. Blackout Kick 
9. Tiger Palm


On line 7, target count >=4 would be higher dps output, changing it to like target count >= 7 would be higher HPS throughput

**Comment by Shamainy** [comment]
I'm assuming it's along the lines of the below whenever you activate Invoke Chi-Ji, the Red Crane added under CD. Important is that the moment you get two stacks of the buff, enveloping mist is prio.
While the above is mostly correct, Hekili was made for optimizing DPS rotation, not tell you how to heal, so no need for renewing mist check. 
Jadefire Stomp is important, but that's already added to the addon under actions+= since you need it for both ST and AoE.


This is straight up grabbed from the addon, with some adjustment of abilities that wont proc a red crane buff. I'm not sure if I done it correctly, but maybe you can understand where I'm going with it. 

actions.st+=/thunder_focus_tea
actions.st+=/enveloping_mist,if=!talent.invoke_chi-ji,_the_red_crane&buff.invoke _chi-ji,_the_red _crane<2
actions.st+=/rising_sun_kick
actions.st+=/blackout_kick,if=!talent.teachings_of_the_monastery|(!talent.awakened_faeline&buff.teachings_of_the_monastery.up|buff.teachings_of_the_monastery.stack>3)&cooldown.rising_sun_kick.remains>gcd.max
actions.st+=/tiger_palm

actions.aoe+=/thunder_focus_tea,if=active_enemies<=3
actions.aoe+=/enveloping_mist,if=!talent.invoke_chi-ji,_the_red_crane&buff.invoke _chi-ji,_the_red _crane<2
actions.aoe+=/rising_sun_kick,if=active_enemies<=3|settings.aoe_rsk
actions.aoe+=/blackout_kick,if=!talent.teachings_of_the_monastery|buff.teachings_of_the_monastery.up&active_enemies<=3
actions.aoe+=/spinning_crane_kick

**Comment by syrifgit** [comment]
> While the above is mostly correct, Hekili was made for optimizing DPS rotation, not tell you how to heal, so no need for renewing mist check.

Enveloping mist doesn't do damage either. So are we adding healing spells or not? I thought that was the entire point of your request lol. If we aren't adding renewing mist there is no point adding enveloping mist and so you might as well just scrap the change and follow the ST priority that already exists?

The rotation/prio I posted is correct according to all 3 guides and the MW discord.

A lot of the condition logic you wrote there doesn't make sense. That list would tell you to spam enveloping mist forever, and your AoE thunder focus tea is only casted at exactly 3 targets which is kinda weird

As for jadefire stomp, your assumption may or may not be correct depending on where the chiji actionlist is placed, as stomp is line 10 of the default. So if chiji is placed in priority 9 or higher it is required inside the chiji APL.

**Comment by Shamainy** [comment]
> > While the above is mostly correct, Hekili was made for optimizing DPS rotation, not tell you how to heal, so no need for renewing mist check.
> 
> Enveloping mist doesn't do damage either. So are we adding healing spells or not? I thought that was the entire point of your request lol. If we aren't adding renewing mist there is no point adding enveloping mist and so you might as well just scrap the change and follow the ST priority that already exists?
> 
> The rotation/prio I posted is correct according to all 3 guides and the MW discord.
> 
> A lot of the condition logic you wrote there doesn't make sense. That list would tell you to spam enveloping mist forever, and your AoE thunder focus tea is only casted at exactly 3 targets which is kinda weird
> 
> As for jadefire stomp, your assumption may or may not be correct depending on where the chiji actionlist is placed, as stomp is line 10 of the default. So if chiji is placed in priority 9 or higher it is required inside the chiji APL.

Again, straight up taken from what's in Hekili already. I just tried to show so they can get an idea of what I mean.

> Enveloping mist doesn't do damage either. So are we adding healing spells or not? I thought that was the entire point of your request lol. If we aren't adding renewing mist there is no point adding enveloping mist and so you might as well just scrap the change and follow the ST priority that already exists?
>

I was just trying to tweak how we handle things during Chi-Ji’s time, aiming to mix in a bit of healing with our DPS to make the most out of those moments. The idea was to give us a heads-up on whether to keep hitting hard or sneak in an Enveloping Mist for better results, not to turn Hekili into a healer’s buddy.

Not saying you are wrong, just trying to show specifically what I'm asking for, but again I'm not an expert and tweaking probably needed by someone that knows how APL works together with Hekili.

But I'm sure there are people out there are would like Hekili to be able to help with more than just DPS, but that is more than what I'm asking for here.

**Comment by Hekili** [comment]
I'm okay with healing spells in terms of what's equivalent to maintaining some sort of baseline (like how tanks keep up active mitigation).  I don't want to pretend like healing is optimized and take away from healers making smart decisions about their healing.

**Comment by syrifgit** [comment]
@Shamainy I guess I just don't understand why casting 1, maybe 2 renewing mists during chiji so you don't overcap on charges is crossing a line on dps vs healing but Casting envelop to heal every 3rd global is fine which would be like 10 casts during chiji?

**Comment by Shamainy** [comment]
> @Shamainy I guess I just don't understand why casting 1, maybe 2 renewing mists during chiji so you don't overcap on charges is crossing a line on dps vs healing but Casting envelop to heal every 3rd global is fine which would be like 10 casts during chiji?

Oh, I get where you're coming from, and honestly, I'm on the same page. Tossing in a Renewing Mist or two during Chi-Ji to avoid wasting charges? Sounds like a smart move. My point was more about keeping things simple. Hekili's all about that DPS life, and throwing in Enveloping Mist because it directly ties into the whole Chi-Ji vibe felt like a natural fit. It wasn't about drawing a line in the sand between DPS and healing; it's just sticking to the addon's already providing DPS wise.

Adding more healing spells felt like it might steer us a bit off course from what we're here for. But hey, making sure we're using all our resources efficiently, including not letting those Renewing Mist charges go to waste, totally makes sense.

**Comment by Shamainy** [comment]
> I'm okay with healing spells in terms of what's equivalent to maintaining some sort of baseline (like how tanks keep up active mitigation). I don't want to pretend like healing is optimized and take away from healers making smart decisions about their healing.

Yes, throwing in the Enveloping Mist during that portion of the rotation while Chi-Ji is active seemed like an obvious choice since you want to do it anyways and then continue your rotation! 
While anything else might, as you put it, take away from healers smart decision making.

And even if this isn't something you able to add, I would like to know how I could add it myself into the Hekili Profile, if that's possible! Since you are able to copy existing profile and tweak them yourself.
