### ISSUE TITLE
[REC] Frost mage opener - not casting flurry

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3176]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Frost mage single target opener does not suggest an early Flurry before icyveins / at the same time as icy veins.

Sources showing to flurry first
[IcyVeins Class Guide](https://www.icy-veins.com/wow/frost-mage-pve-dps-rotation-cooldowns-abilities)
[Top Ranking Mythic Volcoross Logs](https://www.warcraftlogs.com/reports/FJ49abAWwq6TBrnp#fight=12&type=casts&source=17&translate=true&view=timeline)
[Sims](https://www.raidbots.com/simbot/report/2ubcxUfhus82evt3YH1F9A)

### How to Reproduce

Single target frost build, follow pre-pull sequence, _**do not start with any icicles.**_

If you do start with icicles, [it will suggest flurry correctly due to icicle react variable](https://pastebin.com/HSjxcWZ3). But on a raid pull you would not be starting with any.

It looks to me like it's trying to suggest the instant flurry but failing the time check

```
        12.  flurry ( cds - 7 )
        The action (flurry) is usable at (1.42 + 0.00) with cost of 2500 mana (have 245034).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( cds ) called from ( Frost Mage:default:3 ) would PASS at 0.00.
        NONE
         - this entry's criteria FAILS: time[0.02] = 0 & active_enemies[2.00] <= 2
```

Perhaps the time should be less than 1 instead of == 0? The instant the frostbolt projectile leaves your character, the time variable goes from 0.01 to 0.17. It is never really 0, even while casting out of combat, time is 0.01 so it always fails.

### Snapshot (Link)

https://pastebin.com/Zv8veqEa

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2ubcxUfhus82evt3YH1F9A

### Contact Information

Syrif

**Comment by syrifgit** [comment]
Not sure if it's the optimal solution, but changing that flurry line to

`time < 0.3 & active_enemies <= 2`

gives the desired opener

I tried time < 1 but it was too long and made you double cast flurry.

**Comment by Amortalist** [comment]
This is still an ongoing problem, tried the <0.3 but it didn't change anything

**Comment by Hekili** [comment]
I'll be changing the opener use of Flurry to fire up to the first half-GCD.  This is going to be very sensitive to pull timing (i.e., if someone else triggers the start of combat, the addon will only have a half-GCD window to recommend this Flurry before it moves on to the next recommendations).
