### ISSUE TITLE
Flamestrike does not show up at all as a recommendation

### ISSUE THREAD

**Issue by Nachuy122** [Hekili/hekili#3177]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I just started using hekili with my fire mage and noticed that it was never recommending flamestrike, like not even once. I have looked through the priority list and its in there and seems as expected but just does not show at all. I am unsure if its something I have done wrong seeing as I couldn't seem to find anyone else with this issue. i even tried disbaling every ability other than flame strike and it still never recommends it

### How to Reproduce

i have fire mage on default auto rotation

### Snapshot (Link)

https://pastebin.com/N2BxtqsT

### Contact Information

Discord username: Mvgic

**Comment by syrifgit** [comment]
That is not the entire snapshot.

You need to select Ctrl+a to select all of the text, it should be massive.

Side note, I don't recommend showing that many abilities in your queue, especially for fire mage.

I would guess your targeting settings are not set up right.
