### ISSUE TITLE
[REC] Vengeance DH Sigil of Flame incorrectly showing in primary when on CD (and counter-issue with Illuminated Sigils talent)

### ISSUE THREAD

**Issue by dannym314** [Hekili/hekili#3180]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When tanking as Vengeance Demon Hunter you choose between "Illuminated Sigils" or "Down In Flames" talents. Illuminated Sigils gives 2 charges to all of your sigils which changes the rotation.

With Illuminated Sigils, Hekili seems to act as though I only have 1 charge of Sigil of Flame, and will not recommend it again until the charge refreshes and I am back on 2 charges.

Without Illuminated Sigils, Hekili seems to act as though I have 2 charges of Sigil of Flame even though I have only 1, recommending me to use Sigil of Flame again as soon as I have used it - often as the first recommendation in the queue.

The most obvious way to see that there is a problem is to make sure you don't have Illuminated Sigils, then begin a rotation on a single target and follow Hekili's advice exactly. You will see Sigil of Flame listed again, and if you continue the rotation correctly Sigil of Flame will move into 1st place despite being on cooldown.

### How to Reproduce

1. Enter game as Vengeance DH
2. Untalent "Illuminated Sigils" so you only have 1 charge of Sigil of Flame
3. Enter combat and perform normal rotation
4. After using Sigil of Flame, Sigil of Flame is still recommended in the primary queue, even though it is on CD. It will often be the first suggestion, even though it is on cooldown.

6. [Additional/Alternative] With "Illuminated Sigils" talented, Sigil of Flame is only ever recommended in the primary queue when 2 charges are available. It is almost as though Hekili is recommending the opposite of what you would expect it to do for Illuminated Sigils.

### Snapshot (Link)

https://pastebin.com/Ybdsz1tb

**Comment by Hekili** [comment]
You'll need to take the snapshot at the time(s) of the recommendation(s) that you have issue with.  Your snapshot is just taken out of combat.

So if you're showing me the "Down in Flames" scenario where it's recommending Sigil of Flame but your Sigil of Flame is on cooldown, take the snapshot at that moment and I can investigate further.  I'll also try to replicate with your instructions here, but your snapshot(s) will be critical as well.

**Comment by dannym314** [comment]
It happens in and out of combat, the snapshot shows Hekili recommending Sigil of Flame in the 3rd slot when it is on CD. I have another one here: https://pastebin.com/YCys5p7V

However there is one small correction - Sigil of Flame never reaches 1st place recommended, only 2nd place. But that makes it harder to glance and see what you need to do in future.

**Comment by Hekili** [comment]
I'm not able to replicate it with your talents, but your snapshot does seem to show Sigil of Flames recommended earlier than it's truly available.  I *think* it may be an issue with the ability having an internal cooldown in my code, so I'll be posting a beta build that helps record more diagnostic information related to ICDs.

**Comment by Hekili** [comment]
Does your interface show spell IDs?  If so, what is the spell ID of your Sigil of Flame when this is occurring?

**Comment by dannym314** [comment]
Sigil of Flame ID from hotbar is 204596 when it is on CD and when it is not on CD (including this redundant information just for completeness).

The debuff it puts on the enemy is ID 204598.

Here is an image of my screen before using Sigil of Flame, one charge only:
https://i.imgur.com/FtRK6Cc.jpg

After using Sigil of Flame, one charge only:
https://i.imgur.com/FXYCM7M.jpg


I can also take screenshots of the opposite problem (having 2 charges, but only 1 gets recommended to be used) if that helps.

Edited: screenshots links were in opposite position

**Comment by Hekili** [comment]
It's bizarre that I can use the same build in the same place and not replicate the issue.  The 1.0.6-beta2 build may add some useful information to snapshots if you give it a run.

**Comment by dannym314** [comment]
The new beta version fixes both issues! Mystery solved.

**Comment by dannym314** [comment]
I don't know if you're going to see this now it's closed, but it's happening again! I checked for a beta to see if that fixes it like last time, but don't see one this time.

I will try to get a snapshot ASAP.

**Comment by dannym314** [comment]
https://pastebin.com/6Bh5AitK

With Sigl of Flame on cooldown, 2nd place recommendation is Sigil of flame. On my screen it looks exactly like the screenshots I posted previously.
