### ISSUE TITLE
[REC] (BrM) Purifying brew recommended nearly on cooldown, with very low stagger

### ISSUE THREAD

**Issue by TreeOfLearning** [Hekili/hekili#3182]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Purifying brew is being recommended with stagger almost at zero, often with 2 charges in a row being recommended. Even if it were trying to purify for celestial brew, which I have deactivated, it shouldn't be using the second charge immediately after celestial brew. I would argue for this snapshot it shouldn't be using purifying brew at all as the stagger is so harmless.

### How to Reproduce

1. Enter game as brewmaster
2. Go to tank training dummy
3. Take 1 hit
4. Notice 2 charges of purifying brew being recommended immediately

### Snapshot (Link)

https://pastebin.com/YefbMrLg

**Comment by TreeOfLearning** [comment]
At a glance (I hadn't actually looked at the snapshot myself yet), it looks like the blackout combo priority list is being called because I don't have press the advantage talented. However, I also don't have blackout combo talented, so it's checking for a buff that will never be up and getting stuck ([see here](https://github.com/Hekili/hekili/blob/60e9e75603a6b767beebbd4879f7cc1817c34c30/Dragonflight/APLs/MonkBrewmaster.simc#L72)). 

I guess one solution is to change my talents and take either press the advantage or blackout combo, but I'd note that my current build is a pretty standard mythic+ build (taken from wowhead). Perhaps another solution is to check that blackout combo is talented as part of that action before checking for the presence of the buff.

**Comment by TreeOfLearning** [comment]
Hmm, taking press the advantage (to use the PTA APL) still results in similar behaviour:
https://pastebin.com/hLXeWjpu

It's still checking in this list of blacskout combo is up - but it's not talented, so it never will be.

**Comment by Hekili** [comment]
Thanks for highlighting these.  I'll be removing these entries from the priority and relying on the ones that interact with the addon's settings/sliders.

**Comment by TreeOfLearning** [comment]
> Thanks for highlighting these. I'll be removing these entries from the priority and relying on the ones that interact with the addon's settings/sliders.

You're very welcome - and that sounds great. Thanks for such a prompt response!
