### ISSUE TITLE
Dancing rune weapon has wrong keybind

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#3184]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing my blood dk it shows the OLD keybind value instead of the current one.  The game has been reloaded and restarted several times.
![image](https://github.com/Hekili/hekili/assets/1850089/7bf92be5-8ffc-4450-b4d1-abe358b8f227)
<img width="775" alt="image" src="https://github.com/Hekili/hekili/assets/1850089/87979a86-daaf-4cde-8eed-779d4644704e">
![image](https://github.com/Hekili/hekili/assets/1850089/d7804729-6d02-4939-88b5-2934a69dfaed)

### How to Reproduce

Create macro for Dancing rune weapon.  Assign it to middle mouse button.

### Snapshot (Link)

https://pastebin.com/EDezNAPf

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cR893NBTrhj17LuptYfgrX

### Additional Information

My middle mouse button is assigned to "middle" in the mouse software

**Comment by syrifgit** [comment]
From the FAQ in the discord

**My keybinds are wrong!**
Go to `Issue Reporting` inside the addon settings and scroll down the text box to find your list of keybinds and see where it thinks the ability is (probably some random hidden bar). If you correct the actionbars, it will likely work. Otherwise, you can go to the `Abilities` section of the addon settings and manually enter a keybind for the ability. This is sometimes necessary for macros.

**Comment by N6REJ** [comment]
> Go to `Issue Reporting` inside the addon settings

I'm sorry this makes no sense to me.  I don't see "issue reporting" anywhere
This is the closest I see and that doesn't have anything you mention 
![image](https://github.com/Hekili/hekili/assets/1850089/fb8eade5-b8a1-4adb-b5ef-67c1493e3800)

**Comment by N6REJ** [comment]
going on the second sentence I was finally able to find this issue.  Hopefully this might help others
<img width="701" alt="image" src="https://github.com/Hekili/hekili/assets/1850089/c11ee928-d7ae-46ae-876b-c775e0cace20">
