### ISSUE TITLE
[REC] Outlaw rogue doesn't seem to be priortising slice and dice after entering combat

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3185]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

If you don't put up slice and dice before entering combat (for example, a ninja pull in m+ or a res during combat) and you have cooldowns available, the addon will wait til the available shadow dance/vanish subterfuge window is over before it will recommend snd. This happens even if you are not in a subterfuge window from stealth when combat starts. 

I feel like slice and dice should have a higher priority, at least in combat when outside of a subterfuge window, and probably also while in subterfuge. I think trying to spam bte in subterfuge windows for 6-18 seconds is a dps loss over not getting snd up. You could even pop a one cp snd after a 7 point finisher (with ruthlessness).

Snapshot demonstrates the case where it probably should be recommending snd before going into subterfuge/crackshot window.

I am unsure how to use a sim to demonstrate this as i think the sim/apl is written in such a way that slice and dice will always be available as it is only in very rare circumstances that it won't be.

### How to Reproduce

1. Exit stealth and wait 6 seconds for any subterfuge window to fall off. Slice and dice is recommended after ADR (precombat action).
2. Enter combat with target dummy. 
3. Slice and dice won't be recommended until after shadow dance/vanish windows are used when it would make most sense to ADR->Slice and dice before entering subterfuge.

### Snapshot (Link)

https://pastebin.com/Mc2pKxzW

**Comment by Hekili** [comment]
Do you have a Raidbots sim for comparison?

**Comment by Hekili** [comment]
Have you done any editing/disabling of entries in the priority?  It's not clear to me why several entries are skipped in the `finish` list.  Are they disabled in your priority?

```
        50.  call_action_list:stealth ( default - 8 )
        Criteria for stealth FAIL at +0.00 - stealthed.all[false] & stealthed.all_remains[0.00] > settings.stealth_padding[0.20]
 
        51.  run_action_list:finish ( default - 9 )
        Criteria for finish PASS at +0.00 - variable.finish_condition[true]
        Action list (finish) was found.
        + [finish]
        Current recommendation was roll_the_bones at +1.00s.
 
        52.  cold_blood ( finish - 5 ) - talent [ cold_blood ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-finish-5:cold_blood:0.01:Ability Known, Enabled(0.01)
        Exiting finish with recommendation of roll_the_bones at +1.00s.
        Returned from list (finish), current recommendation is roll_the_bones (+1.00).
        - [finish]
        Added finish to blocklist as it was called via RAL.
         - blocking script did not immediately block; will attempt to tune it.
         - leaving delayMin at 0.
```

Entries 1 - 4 in the Finish list were skipped for some reason.

**Comment by fzarr** [comment]
I have cold blood and crippling poison disabled (both of which wouldn't be recommended anyway), that's all as far as I know. Also using default apl included in the addon. Anything I can double check?

Here are some sims where i removed the slice and dice precombat action from the second one in each set. It's obviously a dps loss (although not as big as I was thinking it would be). Unfortunately I don't really know how to compare holding snd til the end like what is happening in the 2nd sim vs forcing using it as a finisher early instead of a bte/dispatch.

Single Target:
https://www.raidbots.com/simbot/report/q4rwBvUQDj1mc2J3U2dLCm
https://www.raidbots.com/simbot/report/oPZc2d9BEDbA6B396oQeAW

Seems to be a bigger difference on aoe / shorter fights:
https://www.raidbots.com/simbot/report/tymrT6zaGZBaK8XHuwh6GJ
https://www.raidbots.com/simbot/report/gZk3uzKZxcrw6DzAt16S3L

**Comment by Eco40** [comment]
Might be irrelevant but I noticed similar behavior sometimes. SnD is no recommended when it fell off or is not cast pre-combat. 
I assumed it might be because BTE and Crackshot procs are correctly prioritized at this point but was never cleaver enough to sim it. Nevertheless, I can confirm it happens as described by "fzarr".
