### ISSUE TITLE
[REC] Liquid Magma Totem on ST

### ISSUE THREAD

**Issue by Thornic** [Hekili/hekili#3186]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Elemental Shaman, I expect the addon to not recommend Liquid Magma Totem -> Totemic Recall -> Liquid Magma Totem on single target
You mainly use that combo to spread Flame Shocks. Using it on a boss or the last few mobs of a pack is a waste.

### How to Reproduce

Use a standard M+ build like this: BYQA7dFHISiZRvWu4x4NMgmZAAAAAAAg0SrIJlkACSjSUSLJOQOAAAAAAgSAJlkokGg0SSaKBKBREIA

Use the single target training dummy in the back in valkdrakken

### Snapshot (Link)

https://pastebin.com/YgmyNw40

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/68Xe3BPy4fzpssLwGPHTSF

### Additional Information

I see that the sim it also recommends. But if you look at guides on wowhead / icy veins they never recommend it ST. Mainly because you want to save it for AOE situations.

**Comment by wrogg** [comment]
If you go to the abilities tab and find Liquid Magma Totem, you can select the minimum targets setting so that LMT is only recommended when multiple enemies are detected.

**Comment by syrifgit** [comment]
The single target sim you posted disagrees. The sim does do Liquid Magma Totem -> Totemic Recall -> Liquid Magma Totem on single target.

![image](https://github.com/Hekili/hekili/assets/139663837/80eddfed-48c8-4b82-8b8b-c0a9d013a0b9)


wroggs suggestion will stop it from being used on single target, but if the sims do it, you probably want to do it. As for not sending at the end of a pack, add totemic recall to your cooldown toggle and simply hotkey toggle your cooldowns near the end of a pack so you don't waste them. LMT too.
