### ISSUE TITLE
I keep getting a spell that cant use when its on cooldown? 

### ISSUE THREAD

**Issue by Skuxxlord123** [Hekili/hekili#3187]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my demonology warlock i keep getting the spell grimoire felguard that keeps showing in my taskbar when i cant use it because its on a 2min cool down, Even when i try disabling the spell and also getting rid of the spell in my talent tree it still shows there?

### How to Reproduce

Damage a enemy 

### Snapshot (Link)

https://pastebin.com/wqHanVvx

### Contact Information

balboa#7601

**Comment by syrifgit** [comment]
It just wants you to summon your pet.
```
2.   summon_pet ( precombat - 2 )
        The action (summon_pet) is usable at (0.00 + 0.00) with cost of 1 soul_shards (have 3).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry's criteria PASSES: ! pet.alive[false] & ! buff.grimoire_of_sacrifice.up[false]
        Action chosen:  summon_pet at 0.00!
        Exiting precombat with recommendation of NO ACTION at +10.00s.
 ```
 
Are you not able to summon it? (I am not a warlock player, idk if regular pet summon is different from this grimoire thing)

**Comment by Skuxxlord123** [comment]
It wants me to summon grimoire felguard for a summon but its showing me to use it when i can't because its already on a 2min cooldown from already using it

**Comment by Skuxxlord123** [comment]
![idkddd](https://github.com/Hekili/hekili/assets/161115729/a1eec59c-1464-4b97-84e4-76ed8e1d8235)

**Comment by Skuxxlord123** [comment]
it dosent even show me the button to use

**Comment by SpatenLa** [comment]
it wants you to use your pet. NOT the grimoir. you are a demonology warlock. you have a pet. use it.
it doesnt show you the keybind because you didn keybind it. USE YOUR PET

**Comment by syrifgit** [comment]
> it dosent even show me the button to use

You need to pull it out of your spellbook and place it on an actionbar.

**Comment by Skuxxlord123** [comment]
Okay sweet got it working ty guys!!
