### ISSUE TITLE
Ret Paladin: Shield of Vengeance not being recommended precombat 

### ISSUE THREAD

**Issue by nhymnble** [Hekili/hekili#3189]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Shield of Vengeance, while it can be used as a defensive cd, is normally used as an offensive cd. It appears in the precombat  action lists, but is never recommended precombat. It's only being recommended as a defensive, even when I change it's require toggle from default (defensives) to cooldowns.

### How to Reproduce

Enter game as Retribution Paladin, take Shield of Vengeance talent, fight anything and see no recommendation.

### Snapshot (Link)

https://pastebin.com/582YKDKc

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kNwcLBWGZVi8eCt8APo5yp

### Additional Information

Ideally, Shield of Vengeance should be used precombat as well as on cooldown, paired with Avenging Wrath. The Raidbots report confirms the same.

### Contact Information

Discord: Nhymn or  jason@nhymnble.com

**Comment by syrifgit** [comment]
It's failing the damage taken check.

```
        3.   shield_of_vengeance ( precombat - 3 )
        The action (shield_of_vengeance) is unusable at (0.00 + 0.00) because incoming damage over 5s must exceed 20% of max health.
```

It could maybe be a good idea to add this as a spec option "Use Shield o Vengeance Offensively" and have it skip the damage taken check. We'll see what Hekili says when he's back.

**Comment by nhymnble** [comment]
That would be perfect. I’m surprised it’s not already in there. Along the same lines, it would be nice if BoS could be recommended as a dps cd when Recompense is talented.

**Comment by Hekili** [comment]
The next release will restore the slider, which, when set to 0, will allow Shield of Vengeance without any incoming damage.
