### ISSUE TITLE
Fury Warrior Thunderous Roar not being recommended

### ISSUE THREAD

**Issue by Squatty1** [Hekili/hekili#3190]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing with the talent "uproar" I noticed that Hekili is not recommending Thunderous Roar on cooldown.
According to the class guides it should be used on CD as long as enrage buff is up. There seems to be some additional checks in Hekili.

### How to Reproduce

1.enter game as fury
2.Put all major cd's on cooldown
3. Be enraged
4. Thunderous Roar not being recommended.

### Snapshot (Link)

https://pastebin.com/GUZf7biC

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dNf7qQnEiwbC9wjhdbNo8W

**Comment by syrifgit** [comment]
Looks like a mismatch between sim and Hekili. The sim does not include the avatar checks that are present in the addon.

@Hekili sync needed?

**Comment by chevyn11** [comment]
Hekili made the change specifically for https://github.com/Hekili/hekili/issues/3126 
I don't think either of them took uproar into account.

**Comment by Hekili** [comment]
The added logic is trying to sync with Avatar (from the ability itself, or from Odyn's Fury with Titan's Torment).

**Comment by Squatty1** [comment]
Can there be some additional check. Right now it will just hold it until avatar is up. This can take quite a bit of time as abilities in raid fights do get de-synced, talking about Odyns fury and the second Roar in between. This talent choice is also used for both last bosses for example.

**Comment by Hekili** [comment]
Sure.  How long do you think it should wait for Odyn's Fury or Avatar?  For example, if Avatar has 3 seconds left on CD, would you wait for Avatar before using it?  5 seconds?  10 seconds?

**Comment by Squatty1** [comment]
No more than 3 seconds, but this is just a complete guestimate as I don't know how to edit the Sim APL and check what would be best. :)

**Comment by Hekili** [comment]
This adjustment should be in the latest releases.
