### ISSUE TITLE
(Feral) Tiger's Fury's key in the rotation won't change when moving it to another key

### ISSUE THREAD

**Issue by KomodoDragoon** [Hekili/hekili#3191]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Tiger's Fury still shows as being on the number 8 key, even when it's not. I don't have this issue with any of the other classes.

### How to Reproduce

Try to move Tiger's Fury to another key. You'll see that it still shows as 8 in the rotation.

### Snapshot (Link)

https://pastebin.com/um8CrbZZ

### Contact Information

andrewcornell990@gmail.com

**Comment by syrifgit** [comment]
You can go to the Abilities section of the addon settings and manually enter a keybind for the ability. This is sometimes necessary for macros.

Looks like the addon thinks you have it on 2 separate bars as well. But manually telling it the keybind as per above will work.

**Comment by KomodoDragoon** [comment]
That's weird. I checked all my other bars and I didn't see Tiger's Fury on
any of them except the first one.

**Comment by Hekili** [comment]
Your snapshot shows:
> tigers_fury           = 0   [07], 8   [08]

That means it's on 0 on action page/bar 7 (usually Cat Form) and 8 on page 8 (usually Prowling), even if you don't use bar 7 or bar 8 or have the action bar pages change based on form/stealth.

**Comment by KomodoDragoon** [comment]
I don't know what I'm doing wrong, then. It's not showing up while Prowled,
either.

**Comment by syrifgit** [comment]
If you can't find it, you can still fix it by doing this: Where I have "R", put whatever keybind/text you want to pop up for that spell
![image](https://github.com/Hekili/hekili/assets/139663837/26157ec4-89eb-48b9-bd1f-9cde10e1ecd7)

**Comment by KomodoDragoon** [comment]
Yeah, I'll stick with that. Thanks for the help, and sorry for the trouble.
