### ISSUE TITLE
[REC] Pre-combat actions for outlaw sometimes causing wrong recommendations

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3192]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Outlaw rogue has some piano actions baked in it's pre-combat list. This works fine for raid encounters, but in mythic+ the state can vary outside of ideal conditions (e.g. due to stuff being on cooldown after combat drops).

I've attached a snapshot of one such case where I am out of combat and unstealthed in a key but adrenaline rush is on cooldown. The addon is still recommending the baked list of pre-combat actions (without adr), however recommendation #4 of slice and dice is not possible due to having no combo points and actions 1-3 not generating them.

I think the addon may need some additional logic in order to protect against some scenarios that can arise in m+. I have also sometimes seen roll the bones being (incorrectly) recommended sometimes for a short time after combat drops but i haven't managed to take a snapshot of that yet.

### How to Reproduce

1. Be me in a m+ key with adrenaline rush off cooldown and 0 cp
2. SnD can be recommended without it being possible.

### Snapshot (Link)

https://pastebin.com/VNLP8uTd

**Comment by Hekili** [comment]
You have Deft Maneuvers talented; Blade Flurry generates a combo point (assuming you have at least one enemy around, which the addon does).

**Comment by fzarr** [comment]
Do you mean the addon always assumes one enemy is always in range, or in the snapshot it shows there is a target?

**Comment by Hekili** [comment]
The former.
