### ISSUE TITLE
[BUG] Can't track Sigil of Silence, Sigil of Chains and Sigil of Misery for Vengeance Demon Hunter

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#3194]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili won't recommend Sigil of Silence and Sigil of Misery when put on the APL.

Furthermore cooldown.sigil_of_silence.full_recharge_time<10 always returns 120 even though the spell is on cooldown.

cooldown.sigil_of_misery.full_recharge_time<10 always returns 180 even though the spell is on cooldown.

cooldown.sigil_of_chains.full_recharge_time<10 always returns 180 even though the spell is on cooldown.

It would be nice to have hekili show these abilities even when nothing is being cast by your main target.

### How to Reproduce

1. Use any of the aforementioned sigils 
2. Hekili doesn't recommend it in your rotation.

### Player Information (Link)

https://pastebin.com/X2uKYxtS

### Error Messages (Link)

No bugs though

**Comment by Hekili** [comment]
Sigil of Misery and Sigil of Silence are on the interrupts toggle by default, which you have enabled but displayed in a separate display.  They will not show in the Primary display unless you remove them from the Interrupts toggle (via /hek > Abilities).

**Comment by oversoe** [comment]
I've moved them to cooldowns, but they still dont show up.
It's like silence only appears when there's something to interrupt and misery just never appears

Edit: something to interrupt on my main target

**Comment by syrifgit** [comment]
> I've moved them to cooldowns, but they still dont show up. It's like silence only appears when there's something to interrupt and misery just never appears
> 
> Edit: something to interrupt on my main target

Post a new snapshot of the cooldown display (or main bar if that's where your CDs are) showing Silence and Misery

**Comment by oversoe** [comment]
> > I've moved them to cooldowns, but they still dont show up. It's like silence only appears when there's something to interrupt and misery just never appears
> > Edit: something to interrupt on my main target
> 
> Post a new snapshot of the cooldown display (or main bar if that's where your CDs are) showing Silence and Misery

It's in the original snapshot that I've linked with this bug request

**Comment by oversoe** [comment]
I don't know anything about this but it looks like sigil of silence only triggers when there's something to interrupt and sigil of misery is unknown:

        15.  sigil_of_silence ( default - 13 )
        The action (sigil_of_silence) is unusable at (0.00 + 0.00) because IsUsable returned false.
        Time spent on this action:  0.20ms
        TimeData:Vengeance - Mads-default-13:sigil_of_silence:0.20:Ability Known, Enabled(0.02):Post-TTR and Essential(0.15):Post Cycle(0.00):Post Usable(0.02)
 
        16.  sigil_of_misery ( default - 14 ) - ability unknown
        Time spent on this action:  0.03ms
        TimeData:Vengeance - Mads-default-14:sigil_of_misery:0.03:Ability Known, Enabled(0.03)

**Comment by oversoe** [comment]
Also you can't track the stacks or recharges of any of these 3 spells.

**Comment by syrifgit** [comment]
> Also you can't track the stacks or recharges of any of these 3 spells.

I am able to accurate track the charges / CD of Silence and Chains just fine using `cooldown.sigil_of_silence.full_recharge_time` and `cooldown.sigil_of_chains.full_recharge_time`

Misery does appear to be broken / unrecognized @Hekili , confirmed with my own snapshot using the default pack as well, matching his

Silence requiring a cast typically makes sense. Not sure if that's something that should be changed for everyone, but there may be a way to override it in your own APL?

**Comment by syrifgit** [comment]
I fixed the Misery issue. @Hekili 

From the spec definitions lua file
```
    sigil_of_misery = {
        id = function () return talent.concentrated_sigils.enabled and 207684 or 202140 end,
        cast = 0,
        cooldown = function () return ( pvptalent.sigil_mastery.enabled and 0.75 or 1 ) * 120 - ( talent.improved_sigil_of_misery.enabled and 30 or 0 ) end,
        charges = function () if talent.illuminated_sigils.enabled then return 2 end end,
        recharge = function () if talent.illuminated_sigils.enabled then return ( pvptalent.sigil_mastery.enabled and 0.75 or 1 ) * 120 - ( talent.improved_sigil_of_misery.enabled and 30 or 0 ) end end,
        gcd = "spell",
        school = "physical",

        talent = "sigil_of_misery",
        startsCombat = false,

        toggle = "interrupts",

        handler = function ()
            create_sigil( "misery" )
        end,

        copy = { 207684, 202140 }
    },
```

Adding the following line fixed it and Misery now shows correctly in-game
` known = 207684,`



```
    -- Talent: Place a Sigil of Misery at your location that activates after $d.    Causes all enemies affected by the sigil to cower in fear. Targets are disoriented for $207685d.
    sigil_of_misery = {
        id = function () return talent.concentrated_sigils.enabled and 207684 or 202140 end,
        known = 207684,
	cast = 0,
        cooldown = function () return ( pvptalent.sigil_mastery.enabled and 0.75 or 1 ) * 120 - ( talent.improved_sigil_of_misery.enabled and 30 or 0 ) end,
        charges = function () if talent.illuminated_sigils.enabled then return 2 end end,
        recharge = function () if talent.illuminated_sigils.enabled then return ( pvptalent.sigil_mastery.enabled and 0.75 or 1 ) * 120 - ( talent.improved_sigil_of_misery.enabled and 30 or 0 ) end end,
        gcd = "spell",
        school = "physical",

        talent = "sigil_of_misery",
        startsCombat = false,

        toggle = "interrupts",

        handler = function ()
            create_sigil( "misery" )
        end,

        copy = { 207684, 202140}
    },```

**Comment by Hekili** [comment]
It probably needs to be `known = 202140,` to work with both Concentrated Sigils and without.

**Comment by syrifgit** [comment]
> It probably needs to be `known = 202140,` to work with both Concentrated Sigils and without.

Concentrated sigils was removed from the game. If you mean [Precise Sigils](https://www.wowhead.com/spell=389799/precise-sigils), my fix works as-is with it both talented and untalented.

**Comment by Hekili** [comment]
You're correct, in which case the concentrated sigils condition on the ID needs to go away.  Will fix.

**Comment by Hekili** [comment]
This should be fixed in the latest release.
