### ISSUE TITLE
[REC] Windwalker Touch of Death missing

### ISSUE THREAD

**Issue by 182cm82kg22cm** [Hekili/hekili#3196]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Even with the requirements met, Touch of Death is not being suggested. 
Furthermore, I want it to be suggested with the highest priority, regardless of any condition as well.

I've added the following lines, but it doesn't seem to work either.
actions.cd_sef+=/touch_of_death,target_if=max:target.health,if=combo_strike
actions.cd_serenity+=/touch_of_death,target_if=max:target.health,if=combo_strike&!buff.serenity.up

Any suggestions?

### How to Reproduce

Simply fight a target until 15% or lower life.

### Snapshot (Link)

https://pastebin.com/gAVxk0KJ

### Additional Information

As said, All I want is it being suggested appropriately.

**Comment by Hekili** [comment]
You've imported a priority that doesn't work to begin with.  `target_if=` is not supported.  You can try `cycle_targets=1,if=` in place of `target_if=` and may get the result you're looking for.

**Comment by 182cm82kg22cm** [comment]
Thank you... I'm sorry, I'm no coder or anything like that.
So I'd have to rewrite it like this? (Also preferably until 4 targets)
actions.cd_sef+=/touch_of_death,cycle_targets=1,if=max:target.health,if=combo_strike
actions.cd_serenity+=/touch_of_death,cycle_targets=1,if=max:target.health,if=combo_strike&!buff.serenity.up
Done and I have put it around here..

Executed every time the actor is available.
actions=auto_attack
Potion
actions+=/potion,if=buff.serenity.up|buff.storm_earth_and_fire.up&pet.xuen_the_white_tiger.active|fight_remains<=30
Touch of Death asap
actions.cd_sef+=/touch_of_death,cycle_targets=1,if=max:target.health,if=combo_strike
actions.cd_serenity+=/touch_of_death,cycle_targets=1,if=max:target.health,if=combo_strike&!buff.serenity.up
Build Chi at the start of combat
actions+=/call_action_list,name=opener,if=time<4&chi<5&!pet.xuen_the_white_tiger.active&!talent.serenity



But it doesn't seem to be suggested at all, like before. Even with Serenity up or not

**Comment by syrifgit** [comment]
You keep adding these abilities into sublists. Add them to the default list.

If you look at the snapshot you can see the order it goes through roughly.

But if you're not a coder I also recommend just editing it in the GUI of the add-on as it's far more intuitive that way to visualize what's happening.

Start over with the default pack, make a copy, and play with it. Put the spell in position 1 of the list `Default`.
