### ISSUE TITLE
[REC] Paladin Word of Glory added with code, not highest priority.

### ISSUE THREAD

**Issue by 182cm82kg22cm** [Hekili/hekili#3197]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

My goal is Word of Glory to be suggested right when the paladin hits 60% or less, if the requirements are met.
With the HIGHEST PRIORITY. Regardless of any other condition.
I have added the following line to the profile
actions.cooldowns+=/word_of_glory,if=health.pct<50&holy_power>=3
Requirements = Either 3 or more Holy Power, or Divine Purpose is active (didn't include this one, help)

Now, it is somewhat being suggested, but not as highest priority. It seems often still it wants to throw in another abilities before suggesting the Word.

Where would I need to place the line for it's intended priroity? What do I need to change regarding the intended requirements?

### How to Reproduce

Get below 60% life and target an enemy.

### Snapshot (Link)

https://pastebin.com/L4eJYh8T

**Comment by Hekili** [comment]
You've again imported a priority that's not tailored for the addon, so you're not using the default priority.

If you want something to be "top priority" then it has to be at the top of the priority list.  Move your entry to the top of the `default` action list, for example.

**Comment by 182cm82kg22cm** [comment]
Do you mean my line simply doesn't work or..?
What would be the line necessary for the above mentioned coditions?
Possibly 
actions.cooldowns+=/word_of_glory,if=health.pct<50&holy_power>=3|(buff.divine_purpose.up)

put above flask andp otion into the default part
