### ISSUE TITLE
UH-DK never recommende Epidemic in AOE (V10.2.5-1.0.6)

### ISSUE THREAD

**Issue by MrBean73** [Hekili/hekili#3201]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

in AOE scenarios **Epidemic** was never recommended (testing 2 M+-Keys)

### How to Reproduce

Enter game as Unholy-Dk, talented into Epidemic, fighting to more than 4 grouped enemys

### Snapshot (Link)

https://pastebin.com/qRB9rvPy

**Comment by MrBean73** [comment]
I reverted to 1.05 and reinstall 1.06 and now it works correct

**Comment by MrBean73** [comment]
I have sometimes to reload for recommendation of epidemic

**Comment by Hekili** [comment]
I'd need you to take a snapshot when the addon has stopped recommending Epidemic despite having multiple targets and so forth.  I'm not able to replicate this on my end.

**Comment by MrBean73** [comment]
last it was happens in m+ darkheart thiket. it never recommended it. then i reload it was fine. this happens very often. 

 the snapshot was at Cleave Training Dummy (german:  Trainingsattrappe des Spaltens) i think it was (is) a range checking issue? Dots were on all dummies :

 - Checking nameplate2 [ Creature-0-4239-2444-20674-198594-000177FC18 ] Trainingsattrappe des Spaltens.
    - Excluded by range (30 > 10).
 - Checking nameplate3 [ Creature-0-4239-2444-20674-198594-000077FC18 ] Trainingsattrappe des Spaltens.
    - Excluded by range (30 > 10).
 - Checking nameplate5 [ Creature-0-4239-2444-20674-198594-000277FC18 ] Trainingsattrappe des Spaltens.
    - Excluded by range (30 > 10).
 - Checking nameplate1 [ Creature-0-4239-2444-20674-198594-0001F7FC18 ] Trainingsattrappe des Spaltens.
    nameplate1   - -1 - Creature-0-4239-2444-20674-198594-0001F7FC18 - 67.00 - 10 - Trainingsattrappe des Spaltens 

 I will reset all targeting settings settings an check it

**Comment by MrBean73** [comment]
https://pastebin.com/YTsUQQDa   New Snapshot  Screenshot: 
![Screenshot 2024-04-16 231037](https://github.com/Hekili/hekili/assets/116820193/85575961-90cb-4012-9a76-d9177eb1c051)

after reload:

https://pastebin.com/WEM4Q3zK

**Comment by MrBean73** [comment]
Looks like the problem occured, when i enter a Legion Dungeon. Before, i've done Fall all was fine. Then i enter Legion BRH and Epi was never recommended. Reload fix it.

https://pastebin.com/83PKGRwL

![WoWScrnShot_041824_233128](https://github.com/Hekili/hekili/assets/116820193/e5e7d6aa-e2d6-42ca-a1fe-af1b227f29b1)
