### ISSUE TITLE
Ret Paladin action list doesn't match current apl

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#3203]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Was looking through the generator action list and noticed it was a bit different than the current simc profile. It has an extra BoJ entry #2 which puts WoA as #3. Other changes but those 2 are what caught my attention.

Looks like a missed update is all.

I believe it was this one.
https://github.com/simulationcraft/simc/commit/954a0f99b52c83b09acf4df004349532e8ece54a

### How to Reproduce

Ret Paladin and look at action list.

### Snapshot (Link)

N/A

**Comment by Hekili** [comment]
Thanks; this is updated in 10.2.6-1.0.1.
