### ISSUE TITLE
[BUG] Keybinds not showing for Number keypad

### ISSUE THREAD

**Issue by johndolotko** [Hekili/hekili#3204]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Since the latest update, I seem to have lost the keybinds from the number keypad. It's just showing the icon without the keybind.

### How to Reproduce

always evident

### Player Information (Link)

says no snapshots have been generated

### Error Messages (Link)

no error messages

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by johndolotko** [comment]
Retribution; Cooldowns - Branch of the Tormented Ancient(0.00)
build: v10.2.6-1.0.0
level: 70 (70)
class: PALADIN
spec: retribution

talents: BYEAomTTpSA9oX6huYLb5nP3rDAAAQAAiWp0KJtSjoFJpkEAAAAAAQEkkQgEEpEhkQKpkoFJIkIKFaAA
    adjudication = 1/1
    aegis_of_protection = 1/1
    art_of_war = 1/1
    auras_of_swift_vengeance = 1/1
    auras_of_the_resolute = 1/1
    avenging_wrath = 1/1
    avenging_wrath_might = 1/1
    blade_of_justice = 1/1
    blade_of_vengeance = 1/1
    blades_of_light = 1/1
    blessing_of_freedom = 1/1
    blessing_of_sacrifice = 1/1
    boundless_judgment = 1/1
    cavalier = 1/1
    consecrated_blade = 1/1
    crusaders_reprieve = 1/1
    crusading_strikes = 1/1
    divine_arbiter = 1/1
    divine_resonance = 1/1
    divine_steed = 1/1
    divine_storm = 1/1
    divine_toll = 1/1
    execution_sentence = 1/1
    executioners_will = 1/1
    expurgation = 1/1
    final_verdict = 1/1
    greater_judgment = 1/1
    guided_prayer = 1/1
    hammer_of_wrath = 1/1
    healing_hands = 1/1
    holy_aegis = 2/2
    improved_blade_of_justice = 1/1
    jurisdiction = 1/1
    justification = 1/1
    lay_on_hands = 1/1
    lightforged_blessing = 1/1
    obduracy = 1/1
    of_dusk_and_dawn = 1/1
    penitence = 1/1
    rebuke = 1/1
    rush_of_light = 1/1
    sanctified_plates = 2/2
    seal_of_alacrity = 2/2
    seal_of_might = 2/2
    seal_of_order = 1/1
    seal_of_the_crusader = 2/2
    seasoned_warhorse = 1/1
    seething_flames = 1/1
    shield_of_vengeance = 1/1
    swift_justice = 1/1
    tempest_of_the_lightbringer = 1/1
    truths_wake = 1/1
    unbound_freedom = 1/1
    unbreakable_spirit = 1/1
    vanguard_of_justice = 1/1
    vanguards_momentum = 1/1
    vengeful_wrath = 1/1
    wake_of_ashes = 1/1
    zealots_fervor = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: branch_of_the_tormented_ancient = 1
    tier31 = 5

gear: agonizing_manacles = 1
    band_of_burning_thorns = 1
    branch_of_the_tormented_ancient = 1
    cataclysmic_signet_brand = 1
    eye_of_the_rising_flame = 1
    guild_tabard = 1
    incandescent_soulcleaver = 1
    inflammable_drapeleaf = 1
    lavaforged_sollerets = 1
    red_linen_shirt = 1
    signet_of_the_last_elder = 1
    smoldering_chevaliers_greatbelt = 1
    tier31 = 5
    zealous_pyreknights_ailettes = 1
    zealous_pyreknights_barbute = 1
    zealous_pyreknights_cuisses = 1
    zealous_pyreknights_jeweled_gauntlets = 1
    zealous_pyreknights_warplate = 1

legendaries: none

itemIDs: 207148, 207150, 207157, 207159, 207160, 207162, 207163, 207166, 207169, 207189, 207190, 207191, 207192, 207194, 207799, 2575, 5976

settings: aoe = 3
    combatRefresh = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    enabled = true
    gcdSync = true
    maxTime = 20
    nameplateRange = 10
    nameplates = true
    noFeignedCooldown = false
    package = Retribution
    petbased = false
    potion = spectral_strength
    rangeFilter = false
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false
    desync_toll = false
    sov_damage = 20

toggles: cooldowns = true [separate]
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true [overridden]
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    avenging_wrath         = 0   [01]
    blade_of_justice       = 2   [01]
    blessing_of_protection = =   [01]
    blessing_of_sacrifice  = AZ  [02]
    crusader_aura          = S1  [06]
    divine_protection      = A1  [05]
    divine_shield          = CX  [02]
    divine_steed           = SA  [02]
    divine_storm           = 5   [01]
    divine_toll            = 6   [01]
    execution_sentence     = 8   [01]
    flash_of_light         = N7  [05]
    hammer_of_justice      = SX  [02]
    hammer_of_wrath        = 7   [01]
    hand_of_reckoning      = A3  [05]
    judgment               = 4   [01]
    lay_on_hands           = N8  [05]
    rebuke                 = SZ  [02]
    retribution_aura       = 9   [01]
    shield_of_vengeance    = `   [05]
    templars_verdict       = 3   [01]
    wake_of_ashes          = 1   [01]
    word_of_glory          = N9  [05]

warnings: none


targets:  Nameplates are enabled.

player_buffs:
   183435 - retribution_aura                         -   1 - 3600.00
   351195 - *vengeance                               -   1 - 3600.00
   186403 - *sign_of_battle                          -   1 - 3600.00
   292361 - *embrace_of_paku                         -   1 - 3600.00
   397734 - *word_of_a_worthy_ally                   -   1 - 3600.00

player_debuffs:

target_auras:  target does not exist


New Recommendations for [ Cooldowns ] requested at 13:33:15 ( 5714.33 ); using built-in ( Retribution ) priority.
*** START OF NEW DISPLAY: Cooldowns ***
Purged 439 marked values in 0.19ms.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: holy_power[ 0.00 / 5.00 ], mana[ 250000.00 / 250000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Retribution - precombat ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        1.   retribution_aura ( precombat - 1 ) - ability disabled ( display )
        Time spent on this action:  0.05ms
        TimeData:Retribution-precombat-1:retribution_aura:0.05:Ability Known, Enabled(0.05)
        
        2.   arcane_torrent ( precombat - 2 ) - ability unknown
        Time spent on this action:  0.04ms
        TimeData:Retribution-precombat-2:arcane_torrent:0.04:Ability Known, Enabled(0.04)
        
        3.   shield_of_vengeance ( precombat - 3 ) - ability disabled ( display )
        Time spent on this action:  0.04ms
        TimeData:Retribution-precombat-3:shield_of_vengeance:0.04:Ability Known, Enabled(0.04)
        
        4.   variable ( precombat - 4 )
         - variable.trinket_1_buffs[false] will check this script entry ( Retribution:precombat:4 )
        Time spent on this action:  0.06ms
        TimeData:Retribution-precombat-4:variable:0.06:Ability Known, Enabled(0.03):Post-TTR and Essential(0.03)
        
        5.   variable ( precombat - 5 )
         - variable.trinket_2_buffs[false] will check this script entry ( Retribution:precombat:5 )
        Time spent on this action:  0.04ms
        TimeData:Retribution-precombat-5:variable:0.04:Ability Known, Enabled(0.03):Post-TTR and Essential(0.01)
        
        6.   variable ( precombat - 6 )
         - variable.trinket_1_sync[0.5] will check this script entry ( Retribution:precombat:6 )
        Time spent on this action:  0.04ms
        TimeData:Retribution-precombat-6:variable:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)
        
        7.   variable ( precombat - 7 )
         - variable.trinket_2_sync[0.5] will check this script entry ( Retribution:precombat:7 )
        Time spent on this action:  0.04ms
        TimeData:Retribution-precombat-7:variable:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)
        
        8.   variable ( precombat - 8 )
         - variable.trinket_priority[1] will check this script entry ( Retribution:precombat:8 )
        Time spent on this action:  0.04ms
        TimeData:Retribution-precombat-8:variable:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)
        Exiting precombat with recommendation of NO ACTION at +10.00s.
    
    Completed precombat action list [ Retribution - precombat ].
    
    Processing default action list [ Retribution - default ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        9.   rebuke ( default - 1 ) - ability disabled ( display )
        Time spent on this action:  0.03ms
        TimeData:Retribution-default-1:rebuke:0.03:Ability Known, Enabled(0.03)
        
        10.  variable ( default - 2 )
         - variable.time_to_crusade[0] will check this script entry ( Retribution:default:2 )
        Time spent on this action:  0.04ms
        TimeData:Retribution-default-2:variable:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)
        
        11.  call_action_list:cooldowns ( default - 3 )
        There is no criteria for cooldowns.
        Action list (cooldowns) was found.
        + cooldowns
        Current recommendation was NO ACTION at +10.00s.
        
        12.  potion ( cooldowns - 1 ) - ability disabled ( toggle potions )
        Time spent on this action:  0.81ms
        TimeData:Retribution-cooldowns-1:potion:0.81:Ability Known, Enabled(0.81)
        
        13.  lights_judgment ( cooldowns - 2 ) - ability unknown
        Time spent on this action:  0.05ms
        TimeData:Retribution-cooldowns-2:lights_judgment:0.05:Ability Known, Enabled(0.05)
        
        14.  fireblood ( cooldowns - 3 ) - ability unknown
        Time spent on this action:  0.03ms
        TimeData:Retribution-cooldowns-3:fireblood:0.03:Ability Known, Enabled(0.03)
        
        15.  algethar_puzzle_box ( cooldowns - 4 ) - IsUsableItem item 193701 and nil
        Time spent on this action:  0.06ms
        TimeData:Retribution-cooldowns-4:algethar_puzzle_box:0.06:Ability Known, Enabled(0.06)
        
        Substituting branch_of_the_tormented_ancient for Branch of the Tormented Ancient action; it is otherwise not included in the priority.
        16.  branch_of_the_tormented_ancient ( cooldowns - 5 )
        The action (branch_of_the_tormented_ancient) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( cooldowns ) called from ( Retribution:default:3 ) would PASS at 0.00.
        NONE
         - this entry's criteria FAILS: ( buff.avenging_wrath.up[false] & cooldown.avenging_wrath.remains[0.00] > 40 | buff.crusade.up[false] & buff.crusade.stack[0.00] = 10 ) & ( ! trinket.t2.has_cooldown[false] | trinket.t2.cooldown.remains[0.00] | variable.trinket_priority[1.00] = 1 ) | trinket.t1.buff_duration[0.01] >= fight_remains[30.00]
        There were no recheck events to check.
        Time spent on this action:  0.58ms
        TimeData:Retribution-cooldowns-5:branch_of_the_tormented_ancient:0.58:Ability Known, Enabled(0.14):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.04):Post Stack(0.03):Pre-Script(0.00):Post-Script(0.10):Pre-Recheck(0.19):Post-Recheck Times(0.01):Post Recheck(0.01)
        
        Bypassing 'trinket2' action because the equipped trinket #2 is not usable.
        
        17.  trinket2 ( cooldowns - 6 )
        Time spent on this action:  0.04ms
        TimeData:Retribution-cooldowns-6:trinket2:0.04:Ability Known, Enabled(0.04)
        
        Substituting branch_of_the_tormented_ancient for Branch of the Tormented Ancient action; it is otherwise not included in the priority.
        18.  branch_of_the_tormented_ancient ( cooldowns - 7 )
        The action (branch_of_the_tormented_ancient) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( cooldowns ) called from ( Retribution:default:3 ) would PASS at 0.00.
        NONE
         - this entry's criteria PASSES: ! variable.trinket_1_buffs[false] & ( trinket.t2.cooldown.remains[0.00] | ! variable.trinket_2_buffs[false] | ! buff.crusade.up[false] & cooldown.crusade.remains[0.00] > 20 | ! buff.avenging_wrath.up[false] & cooldown.avenging_wrath.remains[0.00] > 20 )
        Action chosen:  branch_of_the_tormented_ancient at 0.00!
        Exiting cooldowns with recommendation of NO ACTION at +10.00s.
        Returned from list (cooldowns), current recommendation is branch_of_the_tormented_ancient (+0.00).
        - cooldowns
        The recommended action (branch_of_the_tormented_ancient) is ready in less than 0.2s; exiting list (default).
        Exiting default with recommendation of NO ACTION at +10.00s.
    
    Completed default action list [ Retribution - default ].
    Recommendation is branch_of_the_tormented_ancient at 0.00 + 0.00.
    Recommendation #1 is branch_of_the_tormented_ancient at 0.00s (0.00s).
    Time spent generating recommendations:  3.22ms

**Comment by johndolotko** [comment]
Here is the screenshot of the actual issue in picture form.
As can be seen, the first 4 icons are from Hekili and the Trinket which is Number keypad / is not showing the keybind in hekili.
The icon to the far right is a weakaura I made showing the keybind.

![hekili issue](https://github.com/Hekili/hekili/assets/49884783/eeb66bae-124a-47a7-a62a-8cac135f79a6)

EDIT: Forgot to  mention that the issue is with the Cooldown Icons only.

**Comment by Hekili** [comment]
The issue isn't that it's on the numpad; the issue is that it's an item and keybind scraping isn't working immediately for items.  I'll look into it.
