### ISSUE TITLE
[REC] Unholy DK - outbreak recommended as "next up" when unholy blight will be used right before

### ISSUE THREAD

**Issue by taherbert** [Hekili/hekili#3205]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Unholy Death Knight, Unholy Blight should apply the dots that one would use outbreak for. My understanding is that outbreak is used when Unholy Blight is not available to apply or refresh the dots. After casting Unholy Blight, Hekili correctly removes outbreak from the recommended actions list.

Is it possible to not have outbreak in the "up next" section when Unholy Blight will be used first? See screenshot attached.

![CleanShot 2024-03-25 at 17 09 09@2x](https://github.com/Hekili/hekili/assets/18316812/c8aefb49-c96a-4880-bcf9-b3543de255af)

### How to Reproduce

* Using default wowhead talent build for M+: BwPA/gf1fDREKLfAcG9Z2HkF/BAIRSCJiERISECJJJRAAAAAAAAAgCJRISSaAAkIFRSSikE
* Stand next to any target dummy (ST or AOE)

### Snapshot (Link)

https://pastebin.com/ZQ00PeFg

**Comment by Hekili** [comment]
Can you provide a quick sim of your character via Raidbots in a similar scenario?  I *think* the sim would do the same behavior based on reviewing the priority, but not 100% sure.  It has to do with Superstrain.

**Comment by taherbert** [comment]
> Can you provide a quick sim of your character via Raidbots in a similar scenario? I _think_ the sim would do the same behavior based on reviewing the priority, but not 100% sure. It has to do with Superstrain.

Sure, here's a quick sim: https://www.raidbots.com/simbot/report/m6SCvbFuYzY3NbA7Na6bHy

![CleanShot 2024-03-26 at 10 30 41@2x](https://github.com/Hekili/hekili/assets/18316812/821707b4-8b17-42ac-a1dc-5b35345748dc)
