### ISSUE TITLE
Sub rogue rotation occasionally doesn't recognize when rupture was used.

### ISSUE THREAD

**Issue by mccarterextracts** [Hekili/hekili#3207]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing subtlety rogue the addon sometimes does not recognize when rupture was used. This causes the addon to keep recommending rupture, essentially breaking the addon as it will not recommend other spells after the bug occurs.

### How to Reproduce

1. Enter Game as Subtlety Rogue.
2. Go into Amirdrissil the dreams hope raid.
3. Fight any boss. 
4. Observe the addon not registering rupture is used after a few pulls.

### Snapshot (Link)

Not related to rotation itself.

### Raidbots Sim Report (Link)

NA

### Contact Information

ellebellejell

**Comment by Hekili** [comment]
I'll need a snapshot taken when Rupture is being recommended despite having just been used.

**Comment by stantsz** [comment]
@mccarterextracts Keep in mind that the [Finality](https://www.wowhead.com/spell=382525/finality) talent might lead to Rupture being recommended twice in short succession.

**Comment by mccarterextracts** [comment]
@Hekili I'll try and make a video for you in addition to the picture. A picture in this case feels highly redundant.

**Comment by chevyn11** [comment]
A snapshot is not a screenshot (picture)

https://github.com/Hekili/hekili/wiki/Report-an-Issue#how-do-i-get-a-snapshot

**Comment by pilathor** [comment]
This still happens quite often, it happened to me a few times in raid and I was able to replicate it on the practice dummy.

Here is the snapshot,
https://pastebin.com/8y3d5msY

And here is a screenshot of the error on pause,
https://i.postimg.cc/2y2pWdxQ/Wo-WScrn-Shot-091224-231430.jpg

Let me know if another ticket needs to be opened or this one can be reactivated.

**Comment by syrifgit** [comment]
@pilathor Nothing about that appears to be an error.

![image](https://github.com/user-attachments/assets/b3b52217-973f-4073-a57f-e681af9198ea)

![image](https://github.com/user-attachments/assets/4ffcb150-6d36-4836-a837-e57e7020794d)

**Comment by Hekili** [comment]
Also:

```
target_buffs:
 
target_debuffs:
```

You may have used Rupture, but you don't have an active target with Rupture applied.

> [i.postimg.cc/2y2pWdxQ/Wo-WScrn-Shot-091224-231430.jpg](https://i.postimg.cc/2y2pWdxQ/Wo-WScrn-Shot-091224-231430.jpg)

I can't see this screenshot; you can paste screenshots directly into GitHub comments, though.

```
 - this entry's criteria PASSES: ! dot.rupture.ticking[false] & target.time_to_die[300.00] - remains[0.00] > 6
```

Conditions pass for using Rupture on a hypothetical enemy; Rupture isn't ticking and its imaginary time to die is 300 seconds, which is greater than 6 seconds.

**Comment by pilathor** [comment]
Yes, I understand, generally the rotation goes well, but something happens and it cycles only recommending Stab (I understand to generate points) and Rupture forever in a loop. Maybe I didn't capture it correctly but it happens.

Rupture is active in the screenshot
![WoWScrnShot_091224_231430](https://github.com/user-attachments/assets/c023a64c-dec1-42ad-93fa-c2890c527a5d)

**Comment by Hekili** [comment]
From what I can tell, you haven't actually targeted that dummy.  I think it's technically your "softtarget" until you actually target it.  At that point, its auras would be detected.

**Comment by Zanetsuken** [comment]
> From what I can tell, you haven't actually targeted that dummy. I think it's technically your "softtarget" until you actually target it. At that point, its auras would be detected.

Would there be any way around this? Curious as it’s an issue for a few specs- thinking selfishly I know affliction has this problem with Agony if the target is not fully selected.

**Comment by pilathor** [comment]
> From what I can tell, you haven't actually targeted that dummy. I think it's technically your "softtarget" until you actually target it. At that point, its auras would be detected.

You are absolutely right, my bad sorry, something changed my target, I don't understand what it could have been, because it started happening shortly after the opener and I don't have any binds that could cause that, ok then there is no bug, I will be attentive to what causes the target change.
