### ISSUE TITLE
Outlaw recommending finishers at 5 combo points

### ISSUE THREAD

**Issue by Amondq3** [Hekili/hekili#3209]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've noticed Outlaw recommending Between the Eyes at 5 points and Ambush after it. Sometimes it happens right after the first Ambush in the opener, similar thing happens to Dispatch from time to time, where it tells you to use it at 5.  If it's not considered an issue, can it be done by me manually? Basically force it to 6-7 points for BtE and Dispatch.

### How to Reproduce

1. Test opener on Training Dummy.
2. Could happen shortly after 1st Ambush
3. If not, it happens eventually while using stealth based abilities

### Snapshot (Link)

https://pastebin.com/5fwZB0CW

**Comment by chevyn11** [comment]
It is optimal to finish at 5 cp when inside stealth windows for crackshot (including subterfuge, and shadow dance) 
![image](https://github.com/Hekili/hekili/assets/111624332/614e85ab-8f0f-4941-96c0-74d39b526746)

**Comment by Amondq3** [comment]
> It is optimal to finish at 5 cp when inside stealth windows for crackshot (including subterfuge, and shadow dance) ![image](https://private-user-images.githubusercontent.com/111624332/321957032-614e85ab-8f0f-4941-96c0-74d39b526746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTk1OTEsIm5iZiI6MTcxMjkxOTI5MSwicGF0aCI6Ii8xMTE2MjQzMzIvMzIxOTU3MDMyLTYxNGU4NWFiLThmMGYtNDk0MS05NmMwLTc0ZDM5YjUyNjc0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxMDU0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjU3ODIyMDJlNzE1NTA1NWIzNWIzZjc1ODM4YzBhODJmMTQ0OTg4MzkyOTNiOTlkNzk5YTNkYTViYmZmNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gcqSSYRaQwWPXdNzN4V0_ABk-lc8Lo_Eg0g4b2nkZq4)

Ah it seems like wowanalyzer isn't updated with it, everyone's getting it read as "bad". What about Dispatch at 5?

**Comment by chevyn11** [comment]
you shouldnt be dispatching inside of stealth unless you did something wrong. But yeah I assume it is relevant there too, the rule is for finishers in general.
