### ISSUE TITLE
Add Whirlwind to Exclude Out-of-Range Abilities Toggle

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#321]
Currently with the "Exclude Out-of-Range" option enabled in the priority settings, "Whirlwind", a Fury Warrior skill is recommended to be cast even when you are out of range of your target.

Can you add a range check to this ability as well? Thank you for your time!

https://www.wowhead.com/spell=190411/whirlwind

**Comment by Hekili** [comment]
I really, really hate Exclude Out-of-Range, but I went ahead and put a 7 yard range (I know WW says 8, but range checking is really spotty between 7 and 8 yards).

I also added a spec option to filter Whirlwind when out of range (/hekili > Fury), without using that godawful setting.
