### ISSUE TITLE
[BUG] Monk Brewmaster stagger tracking issue

### ISSUE THREAD

**Issue by xinni** [Hekili/hekili#3213]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The stagger tracking has some issues. There are two issues I'm aware of:

1. Sometimes it shows `no damage is staggered` even though I have the stagger debuff. Snapshot: [Pastebin link](https://pastebin.com/gCkcJ7EM)
2. The 'stagger.pct' shows incorrect values (e.g., `stagger.pct[1.00]`, `stagger.pct[2.00]`). Snapshot: [Pastebin link](https://pastebin.com/kfgDkpAz)

### How to Reproduce

1. As BrewMaster
2. Unchecked the two options (Maximum shield, Maximum Improved Invoke Niuzao, the Black Ox) in the BrewMaster preferences

### Snapshot (Link)

https://pastebin.com/gCkcJ7EM   ;   https://pastebin.com/kfgDkpAz

**Comment by Hekili** [comment]
?

**Comment by xinni** [comment]
I misunderstood this point; it's not a bug. The `stagger.pct` actually refers to the stagger ticks percentage.
