### ISSUE TITLE
Wrong Havoc DH Opener with A Fire Inside

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#3215]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili recommends every pulls with double immolation aura and sometimes it spams immo aura during a pull, couldn't snapshot that one in time.

### How to Reproduce

Play Havoc DH Inertia ST build on any boss

### Snapshot (Link)

https://pastebin.com/p9Lt5NBC

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2vcnzq4erVe53XY1ykAx2c

### Contact Information

Nibana#6011

**Comment by Hekili** [comment]
This should be addressed in 10.2.6-1.0.2.
