### ISSUE TITLE
Ignore bar(s) that are not visible/active

### ISSUE THREAD

**Issue by station384** [Hekili/hekili#3216]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Prevent Hekili from scanning non visible bars for spells.

### Additional Information

Currently Hekili scans all player bars for spells that it is suggesting which it will display with the associated key-bind.

The problem lies in that hekili scans all bars if they are visible or not (active), this results in it suggesting a key-bind that is incorrect if that spell is on a bar that is only visible when in a certain spec or you have a certain talent selected.

An would be druid's  moonfire.   In no form moonfire is on button 2 and hotkeyed to key 2,  in feral it is on button 3 and hotkeyed to key 3,  this results in in hekili suggesting button 2 (hotkey 2) while in feral form,  this is incorrect as it should be suggesting button 3 (hotkey 3) when in feral form.  This is caused by hekili suggesting the first spell it finds which happens to be be on  a non visible bar. 

The fix for this would be to ignore all bar that are not visible or active.

**Comment by station384** [comment]
I may be able to implement this in a patch,  to avoid pouring through all the code, could someone point me to where in the code that scan/loads/checks the bars (the api call)?  from there I can figure it out.   Its been 10 years since I've written any lua for wow so most of what I learned I've forgotten and right now getting lost in the code without a little guidance. I have basic ideas of the structure and what it doing and where but not enuf to identify the actual load points.

**Comment by Hekili** [comment]
The addon needs to scan additional bars for spells due to the way stances and paging work.  For some classes and specs, which bars are "active" visible will change as you carry out your priority.  Therefore, the addon has to try to anticipate which bars to look at ahead of time.

> This is caused by hekili suggesting the first spell it finds which happens to be be on a non visible bar.

No, the addon looks at bars in different orders based on your form (to try to align with the default way that action pages are used by the default UI).  When Prowling, it looks at page 8, then 7, then 1, 2, 3, 4, 5, 6, 10, 9, 13, 14, 15.  If in Cat Form but not Prowling, it looks at 7, 8, 1, 2, 3, 4, 5, 6, 10, 9, 13, 14, 15.

**Comment by station384** [comment]
Thank you for the info.     I apologize for my ignorance in understanding the logic.  I was going off the limited evidence I was observing as I couldn't identify in the code what was specifically "scanning" the bars.  
The druid example being one of them, where the suggested icon and hotkey was not active on any visible bars but was on a bar that was only visible in a certain stance. 
This can cause confusion (my wife really, as I get to hear the "what? it says push 5 but 5 isn't that spell" coming from the other room heh).

**Comment by Hekili** [comment]
You can override the keybind text for abilities if you want it to always show something specific.  See /hek > Abilities > Override Keybind Text.
