### ISSUE TITLE
Lustrous Golden Plumage

### ISSUE THREAD

**Issue by SjurBur** [Hekili/hekili#322]
Seems like this trinket isn't on the list of on-use anymore.

Regards

**Comment by Hekili** [comment]
No trinkets have been removed literally ever.

If you're not seeing trinkets in a particular priority, I would need you to submit a proper ticket following the ticket instructions so that I can see why it is potentially not showing up.  Thanks!

**Comment by SjurBur** [comment]
For some reason the latest patch fixed the issue for me.

Regards
________________________________
