### ISSUE TITLE
New Outlaw pooling not implemented 

### ISSUE THREAD

**Issue by chevyn11** [Hekili/hekili#3220]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I commented on a commit previously but it wasnt released so I didnt raise a ticket: https://github.com/Hekili/hekili/commit/be48e0402296a327f65b1ddd8ec3c24eca0af98b#r140844096

The new outlaw tweak to pool energy for crackshot BTE wasnt implemented and left commented out:
```
### Ensure Crackshot BtE is not skipped because of low energy
## actions.stealth+=/pool_resource,for_next=1
```

### How to Reproduce

Enter the game as outlaw.
Look at stealth list
see pooling line is not there

### Snapshot (Link)

https://github.com/Hekili/hekili/commit/be48e0402296a327f65b1ddd8ec3c24eca0af98b

### Contact Information

chevyn

**Comment by Hekili** [comment]
It's not needed; the pooling was there to prevent Dispatch from being used when you've spent energy below BtE's cost.  I've accounted for that elsewhere.
