### ISSUE TITLE
Execution Sentence Recommended Above Avenging Wrath

### ISSUE THREAD

**Issue by Westside24ch** [Hekili/hekili#3221]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On Retribution Paladin, Execution Sentence is being recommended before Avenging Wrath. According to all the priority lists I've seen, Avenging Wrath should be pressed first in order to increase the damage done by Execution Sentence.

### How to Reproduce

Login as Ret Paladin, copy a Single Target Build from WoW Head or IcyVeins, and attack a single target dummy. 

### Snapshot (Link)

https://pastebin.com/TpbMEeXH

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kJR87KJ8np3BzU5AK4ADeZ

**Comment by Hekili** [comment]
You have cooldowns toggled off, so Avenging Wrath is not going to be recommended.

**Comment by Westside24ch** [comment]
My bad! Here is an updated snapshot, cooldowns on. Execution Sentence is recommended first, and then Avenging Wrath.

https://pastebin.com/zvrA93UR

**Comment by Hekili** [comment]
Great.  Can you run a quick sim and link that instead of a droptimizer?

**Comment by labudjipjev** [comment]
You should use ES followed by AW, every guide says so.
https://imgur.com/xRNLnF9
https://imgur.com/0HC3vgF
and sims too
https://www.raidbots.com/simbot/report/cs4hnqQdij7kaxCJ84mABD
