### ISSUE TITLE
[FEATURE] Allow user to set to show non-combat priorities in combat

### ISSUE THREAD

**Issue by crabchurch1** [Hekili/hekili#3223]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I have modified my priorities so that Windfury Totem is top priority. However Hekili will not show Windfury totem in the ability display if the user is in combat. I have looked through the options and don't see a way to disable this. I want this ability it to show even if I am in combat. My request is to add a setting to the Abilities page that allows you to set this manually.

**Comment by Hekili** [comment]
Show your work.  The addon will absolutely recommend Windfury Totem in combat when appropriate.  My best guess is that you're editing the `precombat` list when you want to put it in the `default` list.

The addon also has some built-in protection that it won't refresh WFT if it has more than 30 seconds left on its duration.
