### ISSUE TITLE
Prot Warrior - Overlap Ignore Pain (unchecked) Doesn't Work - Always Overlaps No Matter the Setting

### ISSUE THREAD

**Issue by StreetLight777** [Hekili/hekili#3224]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili does not respect the Overlap Ignore Pain setting. I have this unchecked, but it constantly recommends Ignore Pain even though I still have the Ignore Pain buff up (with lots of health). For now, I've disabled the ability and created a TellMeWhen instead to work as intended, but would like this bug fixed.

### How to Reproduce

1. Have Overlap Ignore pain unchecked
2. Engage in combat as a protection warrior
3. Pop Ignore Pain and do normal rotation
4. Wait while Hekili recommends Ignore Pain again (while the buff is still on you)

### Snapshot (Link)

https://pastebin.com/JWR5xBqQ

**Comment by Hekili** [comment]
It looks like the issue is that Ignore Pain overlaps are only prevented if the remaining absorb is greater than 30% of your maximum health.  Have you seen otherwise?

**Comment by StreetLight777** [comment]
The issue is I don’t ever want it to overlap as it’s a waste of rage.

-- Keifer

**Comment by Wyste** [comment]
There could be a formula problem here...

It's something that was forgotten to be updated, and would create StreetLight's scenario often enough to look like a bug. He would have to be absolutely capped to get the setting to take the effect, as that would be the absorb's max cap with current mechanics.

10.2.0 (Tue Nov 07 2023) Build 51426: Fight through the pain, ignoring 50% of damage taken, up to `(Total health * 30 / 100)` total damage prevented.

10.1.0 (Tue May 02 2023) Build 49190: Fight through the pain, ignoring 50% of damage taken, up to` [(0 + Attack power * 4.375) * (1 + Versatility)]` total damage prevented. 

The older build was much more likely to go over 30% HP
