### ISSUE TITLE
[FEATURE] Is it already possible to disable Racials globally?

### ISSUE THREAD

**Issue by AshG231** [Hekili/hekili#3226]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I have recently installed the addon for the first time; from what I have seen so far the only way to disable racial abilities is the same as other abilities: Abilities Page > Choose Ability > Disable. I was wondering if there is a way to disable racial abilities globally as I have looked through the settings and searched online but not found anything.

**Comment by Hekili** [comment]
No, this is not a priority for development.  Use your racials!
