### ISSUE TITLE
[REC] Windwalker: Djaruun weapon recommended with Serenity, but not SEF.

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3228]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Seems like the item use line is missing from the SEF list, but is present in the Serenity list.

Works fine when using serenity, or playing brewmaster. Pastebin is from another user on Discord.

![image](https://github.com/Hekili/hekili/assets/139663837/8cddf7c4-5110-4198-bf2c-9556d3c26053)

### How to Reproduce

Enter game with an SEF talent build and Djaruun equipped. Swap to Serenity to see the recommendation work again.

### Snapshot (Link)

https://pastebin.com/y2yyfTrq

### Contact Information

Syrif / Calcest

**Comment by Benjirank** [comment]
I would also love to see this fixed. I just recently started using your addon and omg it is a game changer! 

Coming here to see if there is a fix for this issue but now I’m gonna go and see if you’ve got a patreon because you deserve support. 

Thank you

**Comment by Hekili** [comment]
This will be in the next release.
