### ISSUE TITLE
[REC] Please create this hunter rotation

### ISSUE THREAD

**Issue by Haryytasker** [Hekili/hekili#3229]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I understand updating the addon is going to take time now that Cata prepatch has launched. I was hoping someone could quickly make the below rotation work as a filler while we wait for you guys to do your amazing work on a larger scale.

1. Hunter's Mark
2. Explosive Shot
3. Kill Shot when health < 20%
4. Black Arrow
5. Serpent Sting
6. Arcane Shot when ES, BA, and SS on CD and KS not available and Focus >60% (or just leave AS out at this point if Focus is an issue)
7. Steady Shot

### How to Reproduce

There is no issue to reproduce. This is a request for a rotation update for prepatch.

### Snapshot (Link)

https://pastebin.com/J3F2DJq4

### Additional Information

Thank you very much for your consideration.

### Contact Information

cobalttastesgreat

**Comment by Haryytasker** [comment]
I tried to use this, but it did not work.

## Survival Hunter
## Prepatch Test

actions.precombat+=/aspect_of_the_dragonhawk
actions.precombat+=/hunters_mark,if=down
actions.precombat+=/potion
actions.precombat+=/steady_shot

actions+=/hunters_mark,if=down
actions+=/rapid_fire
actions+=/call_of_the_wild
actions+=/potion
actions+=/use_items
actions+=/explosive_shot,if=debuff.explosive_shot.down
actions+=/black_arrow
actions+=/explosive_trap,if=active_enemies>2
actions+=/multishot,if=active_enemies>2
actions+=/kill_shot
actions+=/serpent_sting,if=debuff.stings.down
actions+=/steady_shot

**Comment by PettyPeterPettigrew** [comment]
> I tried to use this, but it did not work.
> 
> ## Survival Hunter
> ## Prepatch Test
> actions.precombat+=/aspect_of_the_dragonhawk actions.precombat+=/hunters_mark,if=down actions.precombat+=/potion actions.precombat+=/steady_shot
> 
> actions+=/hunters_mark,if=down actions+=/rapid_fire actions+=/call_of_the_wild actions+=/potion actions+=/use_items actions+=/explosive_shot,if=debuff.explosive_shot.down actions+=/black_arrow actions+=/explosive_trap,if=active_enemies>2 actions+=/multishot,if=active_enemies>2 actions+=/kill_shot actions+=/serpent_sting,if=debuff.stings.down actions+=/steady_shot



Hes not making a Cata version mate. Stopping at Wrath and just focussing on DF

**Comment by himea-saito** [comment]
This has been added to the Cataclysm branch. Cataclysm deployments aren't ready yet so you will need to manually download the development version from the repo and add it to your installation in your addons folder.
