### ISSUE TITLE
Show currently enabled display mode

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [Hekili/hekili#323]
It would be nice to be able to see what mode is currently active. Either as text that can be enabled around the display frame or if it's possible to enable something in conjunction with a weakaura, that would also be great. I often forget to turn cooldowns or ST/AOE on off after using it.

**Comment by Hekili** [comment]
https://wago.io/HekiliToggles

**Comment by Hekili** [comment]
You can also see the current toggle status using the data text or the minimap icon.

I have thought about dumping important toggle status into the chat frame at the start of a boss encounter (as an option under Notification settings).

**Comment by BuurmanDeBuurman** [comment]
Awesome, thank you! :)
