### ISSUE TITLE
Arcane Mage Rotation seems to not use clearcasting enough

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#3230]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing arcane mage Hekili makes me pool a lot of clearcasting charges, sometimes uses it on radiant spark before arcane blast proccing it, sometimes not using it at all during a burn sequence. Sometimes the arcane missiles recommendation just blinks (i.e appears and disappear) in an instant and is not recommended anymore. A bit hard to snapshot and to compare to raidbots

### How to Reproduce

Play Arcane Mage ST build

### Snapshot (Link)

https://pastebin.com/NjxtDvQH

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hKhTSrVL6SBGFmxL4fv2V4

### Contact Information

Nibana#6011

**Comment by Amortalist** [comment]
Added infos about said problems : Basically Hekili often fails to follow the "spend two arcane blast with Nether Precision procced from using a clearcast on Arcane Missiles and then the clearcast if available (clipping the non 2p buffed missiles with an arcane blast asap to build up 2p stacks)".

It also tried to send a clearcasted or 2p buffed arcane missiles right into radiant spark when it's being advised or casted (which should ONLY be procced with arcane blasts in single target, every ramps). I believe this weird behavior is tied to the arcane missile logic. Maybe there could be some "no missile window" when Hekili is about to recommended Radiant Spark or smth. 

Added 04/05 : it also sometimes recommends to empty both arcane orb charges before a pull or in AoE just like it happened with the double immolation aura on DH

**Comment by Hekili** [comment]
I know this ticket has sat for a long while; for each of the additional scenarios you reported, I would need you to provide a snapshot of when that specific scenario is occurring.

**Comment by Amortalist** [comment]
It's fine no worries, it will also probably change a lot very soon with TWW :) 
I can still to send some snapshots if you still want to work on it
