### ISSUE TITLE
Enhancement: Add Retribution Paladin Wake of Ashes Range Check

### ISSUE THREAD

**Issue by Sizznic** [Hekili/hekili#3239]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Paladin, I expect the addon to recommend Wake of Ashes **only when** target is **in** 8 yard range, similar to the Warrior's Whirlwind range check option.

### How to Reproduce

1. Enter game as Retribution Paladin.
2. Head towards a training dummy.
3. Target said training dummy.
4. Stand outside 8 yard range.
5. See recommendations.

### Snapshot (Link)

Retribution; Primary - Wake of Ashes(0.00)

**Comment by Hekili** [comment]
This will be added back in v11.0.0-0.9.1b.
