### ISSUE TITLE
Automatic Display mode and AOE detection

### ISSUE THREAD

**Issue by KventinDorvard** [Hekili/hekili#324]
I'm using Automatic Display mode and it switches my suggested single target rotation to AOE rotation when it detects the second target. Is it possible to make Automatic mode switch to AOE only when it detects 3 or more targets?
My AOE Display: Minimum Targets for my spec is set for 3, but it is not helping.

**Comment by Hekili** [comment]
First, it's important to actually include the requested information when submitting a ticket, as it gives me context re: what you're seeing.

Second, the not-very-secret thing about most priorities is there isn't explicitly an "AOE" mode or "single-target" mode.  Most priorities are written with some conditions based on how many targets are detected, but not explicitly split.

Automatic mode means that you want recommendations based on the actual number of detected targets.

AOE mode means you want the addon to pretend there are at least X targets (for you, X = 3) even if fewer targets were detected.

Similarly, Single Target mode, for the addon means you want the addon to pretend there is only 1 target even if more are detected.

I'd recommend getting familiar with the mode toggle and controlling Single Target vs. Automatic vs. AOE with it, if you are wanting to specifically avoid cleave/AOE recommendations at 2 targets.
