### ISSUE TITLE
Guardian spec not recommending Heart of the Wild while in Bear form

### ISSUE THREAD

**Issue by XtremeTerrorIII** [Hekili/hekili#3241]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Guardian spec not recommending Heart of the Wild while in Bear form

### How to Reproduce

1. Enter game as druid, change to Guardian spec
2. Pick Heart of the Wild
3. Do rotation
4. Notice no Heart of the Wild

### Snapshot (Link)

https://pastebin.com/0PE1SMqD

**Comment by Hekili** [comment]
The relevant "Weave Cat Form and Bear Form" setting is not enabled.

**Comment by XtremeTerrorIII** [comment]
But that would recommend me to change into Cat Form. Is it possible to make it recommended without enabling the Weave Cat Form and Bear form as the buff applies to non bear spells while in bear form?

**Comment by Hekili** [comment]
You could write a custom priority for that.
