### ISSUE TITLE
[REC] Nymue's Dreambinder: Unable to Recommend while channeling

### ISSUE THREAD

**Issue by yokaii4** [Hekili/hekili#3243]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Whenever the effect of Nymue's Dreambinder is active, the addon fails to make recommendations to other spells. This only happens when the weapon is the "first in line" in the recommendation tab. For example, if you use mage and have Arcane Intellect selected, it will show the full list of recommended spells, but as soon the weapon is first everything else disappears until you use it, and then it all returns normal. Attached screenshot of what I see every time Nymue is suggested: https://prnt.sc/oak_8lIT6W5W

The issue happens both in ST and AOE scenarios.

### How to Reproduce

1. Enter the game with any class that can equip Nymue's Dreambinder 
2. Use all abilities suggested before Nymue's Dreambinder (i.e. Arcane Intellect, Mirror Image, etc.)
3. You should now see the issue: all the recommendations besides the weapon's effect are not showing.

### Snapshot (Link)

https://pastebin.com/1EScxQTR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/q2mCmADgNH9nmQiFwqkVQA

### Additional Information

Additional sims:
Patchwerk 1 target 5 min: https://www.raidbots.com/simbot/report/7tNFY9ftUMuNfFF9PJDJq6
Patchwerk 10 target 5 min: https://www.raidbots.com/simbot/report/x8sst9d6L5ks8StRoJrcv1
Dungeon slice: https://www.raidbots.com/simbot/report/pWB5b1wL8YuAk7f18witA3

### Contact Information

yokaii__

**Comment by yokaii4** [comment]
Edit: misspelled the Dreambinder's name with the trinket one. I am referring to the weapon

**Comment by yokaii4** [comment]
Closed by mistake

**Comment by Hekili** [comment]
Same as #3316
