### ISSUE TITLE
Arms warrior || Defensive Stance Not Triggering at Specified Health Threshold

### ISSUE THREAD

**Issue by PvpSpells** [Hekili/hekili#3244]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Defensive Stance is not being suggested when my character's HP falls below a certain percentage, despite being configured with a condition similar to other defensive abilities (e.g., Die by the Sword) that are triggering correctly. 

How it should ideally work: Suggest defensive stance below certain hp% only once, and about certain percentage suggest Battle stance, again only once.

### How to Reproduce

1-Set Defensive Stance to trigger below 30% HP within the defensives toggle as arms warrior(it works by default for Prot, not sure about Fury)
2-Engage in gameplay until HP falls below 30%.
3-Observe that other defensive abilities like Die by the Sword are suggested, but Defensive Stance is not.

### Snapshot (Link)

https://pastebin.com/ByjMhbWT

### Additional Information

Syrif: "For some reason it thinks your defensive stance is on a 60 minute cooldown. Might be worth a ticket on that one."

### Contact Information

!ZigZag#3424

**Comment by syrifgit** [comment]
This is one I looked at in Discord. D-stance is showing a 1 hour cooldown and I don't know why.

**Comment by Hekili** [comment]
Internally, the addon cares more about you being in a stance than which stance you're in -- it's intentional, such that if you swap to defensive stance, the addon doesn't simply tell you to swap back to Battle or Berserker Stance endlessly.

**Comment by PvpSpells** [comment]
So I guess there is now way to get this working the way I had in mind, thank you for your replies, feel free to close/remove this.
