### ISSUE TITLE
[BUG] Addon not working after 10.2.7 update

### ISSUE THREAD

**Issue by nancikennedy** [Hekili/hekili#3248]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On logging in to 10.2.7 just now, I got an error

### How to Reproduce

Log in with Hekili enabled. There was no snapshot to share

### Player Information (Link)

none

### Error Messages (Link)

https://pastebin.com/n7qw3frR

**Comment by syrifgit** [comment]
Here is my bugsack, it is different

https://pastebin.com/hNCPbJwL

**Comment by Zachairi** [comment]
I have this issue too - not working at all post patch !! (it is loaded and "load out of date addons" is enable, can see in my addon buttons on top right of wow client....but 0 addon functionality!!)

**Comment by kolefield** [comment]
Same issue, bugsack for me:

https://pastebin.com/q8zAE3i9

Edit: Update fixed the issue! Thanks for the quick work <3

**Comment by thunderchylde** [comment]
something has changed with `SetJustifyV` as I have errors from it in other addons

**Comment by Eddyofgarona** [comment]
Here's what I'm getting:

Message: Interface/AddOns/Hekili/UI.lua:2513: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
Time: Tue May  7 17:19:36 2024
Count: 1
Stack: Interface/AddOns/Hekili/UI.lua:2513: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetJustifyV'
[string "@Interface/AddOns/Hekili/UI.lua"]:2513: in function `CreateButton'
[string "@Interface/AddOns/Hekili/UI.lua"]:2003: in function `CreateDisplay'
[string "@Interface/AddOns/Hekili/UI.lua"]:2871: in function `BuildUI'
[string "@Interface/AddOns/Hekili/Options.lua"]:9959: in function `TotalRefresh'
[string "@Interface/AddOns/Hekili/Core.lua"]:197: in function <Interface/AddOns/Hekili/Core.lua:195>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
...
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:402: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:607: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by davemgelinas** [comment]
Same here, don't see it loading at all.

**Comment by syrifgit** [comment]
Hekili deployed a new version. Wait for it to be up on curseforge

**Comment by Zachairi** [comment]
woot issue fixed! Thank you Mr Hekili and commentors

**Comment by tdileo** [comment]
Still not working for me, does not show priority queue.
