### ISSUE TITLE
Rotation Bar - Not showing for Discipline Priest

### ISSUE THREAD

**Issue by schwartzmiller** [Hekili/hekili#325]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

The rotation bar is not appearing for Discipline.  When looking under Priority there is no option to select for the priority list.

build: v8.3.0-04-19
level: 90 (90)
class: PRIEST
spec: discipline

talents: body_and_soul
    castigation
    divine_star
    power_word_solace
    psychic_voice
    sins_of_the_many

azerite: none

essences: none*, none

sets/legendaries/artifacts: none

gear: amaranthine_cord = 1
    amaranthine_cowl = 1
    amaranthine_sandals = 1
    amaranthine_wristwraps = 1
    cloak_of_hidden_flasks = 1
    empty_fruit_barrel = 1
    guardian_serpent_handwraps = 1
    hollowheart_pantaloons = 1
    iron_horde_ritual_staff = 1
    legacy_of_the_emperor = 1
    links_of_the_lucid = 1
    price_of_progress = 1
    regal_silk_shoulderpads = 1
    tabard_of_flame = 1
    viscous_ring = 1
    wicked_witchs_signet = 1

corruptions: none

itemIDs: 101801, 101802, 101807, 101810, 112392, 112434, 23705, 81133, 81136, 81232, 81257, 81266, 85363, 86312, 88166, 89067

settings: enabled = true
    potionsReset = 20180919.1

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

Thanks!

**Comment by Hekili** [comment]
Yeah, Discipline is not officially supported.
