### ISSUE TITLE
[REC] Arms warrior APL needs updating

### ISSUE THREAD

**Issue by danimals26** [Hekili/hekili#3250]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Arms warrior APL updates don't seem to be reflected in the addon yet. More specifically the aoe string.

![image](https://github.com/Hekili/hekili/assets/169276645/817f06e7-2e03-4e1b-8da5-3612c3d01f0f)

Here is the raidbots link https://www.raidbots.com/simbot/report/oG14kqBE8rzkuhq6mCbbnq/simc
Rotation guide: https://www.wowhead.com/guide/classes/warrior/arms/rotation-cooldowns-pve-dps

Some notable examples, the highest cleave priority in the addon is buff.martial_prowess.stack = 2 when in the APL it is cleave,if=buff.martial_prowess.stack=2&(buff.sweeping_strikes.up&active_enemies>4|buff.sweeping_strikes.down)|buff.merciless_bonegrinder.up

Mortal strike is also recommended <8 targets when it should be <4

Also, cleave is being recommended over Overpower when it only has 1 stack of martial prowess instead of 2 sometimes, when the APL has overpower always being used before cleave unless cleave,if=buff.martial_prowess.stack=2&(buff.sweeping_strikes.up&active_enemies>4|buff.sweeping_strikes.down)|buff.merciless_bonegrinder.up
I believe this error is separate from the APL not being updated, because even in the current addon's APL cleave should still not be recommended over Overpower unless martial prowess = 2 and it still is (snapshot below)

The addon also lacks the t31 set bonus modifier on the Execute recommendations which leads to a lot of execute recommendations in aoe when no longer using that tier set.

In the execute ST string, we are also back to mortal strike with 2 stacks of executioner's precision being > overpower and execute, even when outside of collossus smash

Thank you!

### How to Reproduce

1. Enter game as Arms warrior
2. Run wowhead aoe build with Cleave talented
3. Observe cleave recommended when only 1 stack of martial prowess, or execute recommended in aoe when t31 set is not equipped, etc.

### Snapshot (Link)

https://pastebin.com/9X7HGh5U

**Comment by Hekili** [comment]
I don't have to be notified of SimC updates; I scan for them regularly.  This will be in the next release.
