### ISSUE TITLE
Windwalker Monk Djaruun not being recommended with Storm Earth and Fire 

### ISSUE THREAD

**Issue by atlkane** [Hekili/hekili#3253]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Windwalker Monk does not recommend using the Djaruun weapon ability unless Serenity is chosen in the talent tree. If Storm Earth and Fire is selected it will never appear ,

### How to Reproduce

1. Be on Windwalker Monk
2. Change talent to Storm Earth and Fire

### Snapshot (Link)

https://pastebin.com/ZrS1N4qL

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hdpgh146cCR8bgzgZvuHB1

**Comment by syrifgit** [comment]
Make sure you check for already existing tickets before opening a new one. You can add your info to the one already open.

https://github.com/Hekili/hekili/issues/3228
