### ISSUE TITLE
Emerald Coachs Whistle shows in rotation even after buffing yourself/party member

### ISSUE THREAD

**Issue by Targonis1259** [Hekili/hekili#3258]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am using an Emerald Coach's Whistle on my Holy Paladin. It shows in my rotation all the time even after I buff a friend, giving us both a 60 minute buff. It should only show up in my rotation if I do not have the buff active on myself, which I get when I buff someone else.

### How to Reproduce

1. Enter game as Holy Paladin
2. Equip Emerald Coach's Whistle trinket
3. Buff a friend in your party
4. See whistle still in rotation after confirming buff on self/other

### Snapshot (Link)

https://pastebin.com/KRyBfRjj

### Contact Information

Discord: Targonis1259

**Comment by Hekili** [comment]
This should be resolved in the next release.
