### ISSUE TITLE
Question about Rogue

### ISSUE THREAD

**Issue by MrWizard516** [Hekili/hekili#326]
I was wondering how I would go about adding in "Crimson Vial" to appear at a set percentage of HP as well as "Riposte"

Thanks in advance.

**Comment by CreepyJoker** [comment]
To create a new apell entry on a specific priority, you can do the following:
Open Hekili addon interface -> Priorities -> select the specific priority you wish to add it to (Outlaw or whatever spec you play) -> change the default dropdown to Defensives -> click the '+' on the next dropdown where the first defensive spell is and select the spell you want from the dropdown and add your condition. Make sure to tick 'Enabled' after you do so. You can also put it on priority 1 by clicking the Up and Down arrows until it gets to "1.Desired Spell" for it to be firstly taken into consideration.

For Crimson Vial you should select Crimson Vial and add the following condition:
"health.pct <= X", where X is the percentage you're aiming for. Don't include the quotes. Make sure you enable Defensives afterwards from the addon dropdown after that. 
You can place the vial into the default rotation as well, but I won't recommend you do so if you are not familiar with the priority order.

Best of luck!
Sorry for the format, writing from phone.

**Comment by Hekili** [comment]
CreepyJoker's description is correct.  If you try it and have trouble, feel free to pop into Discord and show screenshots of your work.
