### ISSUE TITLE
Frost mage double ice lance after a flurry

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#3261]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili will recommends two ice lance after a flurry instead of maximising Glacial Spike. I believe something is up with the icicles generation logic. It also does not cast Flurry at the opener (as said in another issue).

### How to Reproduce

ST dummy without cds playing ST build as frost mage

### Snapshot (Link)

https://pastebin.com/dFASnebM

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qtBA8Tc44i9wXBesFf9gWQ

### Additional Information

Raid logs where this happens regularly : https://www.warcraftlogs.com/reports/1k4rtLawgKGXV8qR#fight=13&type=damage-done&source=81

### Contact Information

Nibana#6011

**Comment by syrifgit** [comment]
According to the [icyveins](https://www.icy-veins.com/wow/frost-mage-pve-dps-rotation-cooldowns-abilities) and[magehub](https://www.mage-hub.com/frost) guides, this is correct behaviour. No issue here.

![image](https://github.com/Hekili/hekili/assets/139663837/0ce38780-1a51-4648-b7a7-7c2521bc81b8)

![image](https://github.com/Hekili/hekili/assets/139663837/37f832e4-48f3-44bf-a24e-60c3a53f8c04)

![image](https://github.com/Hekili/hekili/assets/139663837/e5516361-492d-4f64-a4c3-8fd94ffecc2f)

**Comment by Amortalist** [comment]
From what I've understood the only single time where this can lead to no shattered GS is when there is either no icicles proc from splintering cold (so <2 icicles when the flurry hit). Here what I'm wondering about is the double ice lance into it. From what I'm seeing the simbot always flurry whenever there is > 2 icicles. 

But then why is my crit rate on GS so low even when correctly spellqueuing and all. It makes me do a lot of these too : 
![image](https://github.com/Hekili/hekili/assets/47482996/4538c32c-226e-4252-9393-61e476d48d1b)

It's supposedly very rare, but it happened multiple times in a single fight for me. This probably is due to some latency or leniency between procs and advised actions, but maybe it could be corrected with never flurry < 2 icicles ?

**Comment by Hekili** [comment]
> This probably is due to some latency or leniency between procs and advised actions, but maybe it could be corrected with never flurry < 2 icicles ?

We'd need to sim the difference to show it's more performant.  Have you tested it?

**Comment by syrifgit** [comment]
> > This probably is due to some latency or leniency between procs and advised actions, but maybe it could be corrected with never flurry < 2 icicles ?
> 
> We'd need to sim the difference to show it's more performant. Have you tested it?

We discussed on discord, it was a user spell queueing error, not a sim/hekili error
