### ISSUE TITLE
LUA HEKILI ERRORS

### ISSUE THREAD

**Issue by grftn** [Hekili/hekili#3264]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

unable to get hekili to load on cata classic, ive tried moving LUAs and Previous settings from retail, wotlk, cata etc, got it down to 10 lua error

wondering if anyone can forward me a working folder 

### How to Reproduce

download both versions of hekili, 
replace lua files with wotlk version
log in game
LUA ERROR  

### Player Information (Link)

cant open due to error

### Error Messages (Link)

https://pastebin.com/PG8qkqbX

### Additional Information

discord - DKSY#1423

### Contact Information

DKSY#1423

**Comment by Hekili** [comment]
Until I post a release for Cataclysm, I'm not supporting people hacking together their own installs.

That said, the order you'd want to do things is to install the Wrath version, then extract the Cataclysm files over the top of your Wrath install, not the other way around.

I'll get a release posted in the next day or two, though.  Thanks.

**Comment by grftn** [comment]
Appreciate the response :) 

Thanks

**Comment by grftn** [comment]
managed to sort addon, unable to sort out the spellflash, unsure if this is something you can do on this patch

![image](https://github.com/Hekili/hekili/assets/72569453/dc918667-4c8e-458f-95af-9a44ae710134)

"
build: Dev-4.4.0 (20240515)
level: 71 (71)
class: MAGE
spec: mage

talents: blast_wave
    burning_soul
    cauterize
    combustion
    critical_mass
    dragons_breath
    fire_power
    firestarter
    hot_streak
    ignite
    impact
    improved_flamestrike
    improved_hot_streak
    improved_scorch
    living_bomb
    master_of_elements
    molten_fury

pvptalents: none

covenant: none

conduits: none

soulbinds: none

sets: none

gear: carrot_on_a_stick = 1
    cloak_of_azure_lights = 1
    deadly_borer_leggings = 1
    enumerated_gloves = 1
    formal_white_shirt = 1
    lightwoven_slippers = 1
    lolas_lifegiving_branch = 1
    mainhand = 1
    mainhand_2h = 1
    murghoul_robe = 1
    pauldrons_of_arcane_rage = 1
    reinforced_velvet_helm = 1
    ring_of_decimation = 1
    runecloth_belt = 1
    torc_of_the_sethekk_prophet = 1
    vanadium_loop = 1
    wand_of_shimmering_scales = 1
    wraps_of_the_sanlayn = 1

legendaries: none

itemIDs: 11122, 11989, 13856, 24024, 25711, 27919, 29333, 35572, 35617, 35973, 37803, 38219, 38223, 39676, 4334, 51970

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcd = 1459
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Arcane Wowhead
    petbased = false
    potion = potion_of_speed
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    usePackSelector = false
    arcane = Arcane Wowhead
    fire = Fire Wowhead
    frost = Frost Wowhead
    living_bomb_cap = 3
    spellsteal_cooldown = 0
    use_cold_snap = false

toggles:     cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    blast_wave   = 3   [01]
    blink        = V   [01]
    counterspell = R   [02]
    fireball     = 2   [01]
    flamestrike  = E   [01]
    ice_block    = E   [02]
    molten_armor = V   [02]
    pyroblast    = R   [01]
    remove_curse = 2   [02]

"

Thanks Again
