### ISSUE TITLE
Addon does not have Granyth's Enduring Scale (Trinket, ID #212757) in its Gear and Items list.

### ISSUE THREAD

**Issue by puffdadi** [Hekili/hekili#3265]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I use Hekili to track defensive cooldowns for my Veng DH and I recently swapped out my Tainted Rageheart, which is supported by the addon, with Granyth's Enduring Scale. Now both of these trinkets are rather similar but for some reason Granyth's Enduring Scale does not show up on the Gear and Items list so it does not pop up for defensive cool downs. 
![2122](https://github.com/Hekili/hekili/assets/169854601/8fe8454d-8a05-4e3b-b604-3d5d3d558fb7)
dont know if this screenshot posted or if it'll help at all.

### How to Reproduce

1. Open hekili
2. navigate to gear and items
3. scroll down to items beginning with G or E or S and it is not there

### Snapshot (Link)

Vengeance; Defensives - N/A

### Contact Information

TonyFans#4401

**Comment by Hekili** [comment]
This will be added to the next release; thanks.
