### ISSUE TITLE
MOP Remix

### ISSUE THREAD

**Issue by Shawy82** [Hekili/hekili#3270]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Entering MOP remix I get the message about Hekili not recommended for lowers levels, I can type /hekili to open options and everything seems like the add on loads, but when options are open it shows primary bar with a red border. 

Once I enter combat nothing pops up, no queue of abilities at all. It is only happening on my MOP remix character, all others are working fine. 

### How to Reproduce

Make a MOP remix character and enter the game 

### Player Information (Link)

No link to paste

### Error Messages (Link)

No error link

### Additional Information

No text in the issue reporting section to copy

**Comment by Shawy82** [comment]
I created a mage character and add on works. The one it didn’t work on was frost DK

**Comment by Shawy82** [comment]
Tried making a new frost DK and pro list still won’t show. Changed spec to blood and also will not show

**Comment by Hekili** [comment]
There are no plans to revise the addon for MoP remix.

**Comment by Shawy82** [comment]
Ok, thanks for your reply

**Comment by EliasRMena** [comment]
> ### Before You Begin
> * [x]  I confirm that I have downloaded the latest version of the addon.
> * [x]  I am not playing on a private server.
> * [x]  I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
> * [x]  I edited the title of this bug report (above) so that it describes the issue I am reporting.
> 
> ### Describe the Issue
> Entering MOP remix I get the message about Hekili not recommended for lowers levels, I can type /hekili to open options and everything seems like the add on loads, but when options are open it shows primary bar with a red border.
> 
> Once I enter combat nothing pops up, no queue of abilities at all. It is only happening on my MOP remix character, all others are working fine.
> 
> ### How to Reproduce
> Make a MOP remix character and enter the game
> 
> ### Player Information (Link)
> No link to paste
> 
> ### Error Messages (Link)
> No error link
> 
> ### Additional Information
> No text in the issue reporting section to copy
> 
> ### Contact Information
> _No response_

Same here

**Comment by Hekili** [comment]
There will be no add'l work to support MoP Remix, so if the v11.0.0 versions of the addon are not functioning there, you'll have to go without.  Thanks for understanding.
