### ISSUE TITLE
[BUG] Nameplate Detection is sometimes screenwide instead of 12 yards

### ISSUE THREAD

**Issue by sanyex89** [Hekili/hekili#3272]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Sometimes hekili counts every nameplate on the screen instead of the 12 yard nameplate detection setting

### How to Reproduce

it happens sometimes after playing for a while, a reload fixes the problem for a while
![WoWScrnShot_051724_170653](https://github.com/Hekili/hekili/assets/77323774/9f89577a-99a7-427b-b1f0-bb0b75ef7f74)

### Player Information (Link)

https://pastebin.com/ZLYgdAxj

### Error Messages (Link)

no error message

**Comment by masterkain** [comment]
most likely it's a bug in librangecheck 3.0 lib that I notified the authors about some months ago, but since they were quite hostile in their responses I developed a patch that fixes the issue for me and I'm fine ever since -- hopefully it's something else entirely

**Comment by sanyex89** [comment]
> most likely it's a bug in librangecheck 3.0 lib that I notified the authors about some months ago, but since they were quite hostile in their responses I developed a patch that fixes the issue for me and I'm fine ever since -- hopefully it's something else entirely

so how do i fix this myself? download your librangecheck and paste it over the hekili files ?

**Comment by masterkain** [comment]
make a backup first and keep your expectations very low :p

**Comment by sanyex89** [comment]
> make a backup first and keep your expectations very low :p

yeah its still showing 9 enemies instead of 2 at the beginning of halls of infusion for example

**Comment by Hekili** [comment]
I have an update with range-check revisions that may address this.
