### ISSUE TITLE
[REC]Unholy DK Cataclysm Classic Profile is out of date

### ISSUE THREAD

**Issue by Eisenvater01** [Hekili/hekili#3273]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Profile is from an icy veins guide with date 26.09.2022 and needs to be updated for the new guide.

### How to Reproduce

![unholydk](https://github.com/Hekili/hekili/assets/170117610/6542cf4c-7bfc-4c7f-8f6a-8835bbbeb0cc)

### Snapshot (Link)

not needed

**Comment by Hekili** [comment]
There's no release for Cataclysm yet; priorities will be updated when ready.
