### ISSUE TITLE
Rotations do not show since remix update

### ISSUE THREAD

**Issue by SpikeHM** [Hekili/hekili#3275]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I made a warrior for the Pandarian remix. Yes, it is enabled and everything is on. I thought it was maybe because of the Remix event. I logged on normal retail and it still doesn't show rotations on my hunter either. (Edit) OK, so I just noticed that somehow the spellflash got turned off. ignore ticket

### How to Reproduce

Log in to wow.
See rotations aren't  showing.

### Player Information (Link)

I'm on my phone

### Error Messages (Link)

I'm reporting from my phone because I'm parenting right now.

**Comment by Hekili** [comment]
Feel free to reopen the ticket when you're at your compute rand can provide the required information (i.e., snapshot, error messages, etc.).  Thanks!
