### ISSUE TITLE
Rogue stuns

### ISSUE THREAD

**Issue by Glaciat** [Hekili/hekili#328]
I noticed that Hekili doesn't take into account about the useage of the Rogue stunning abilities I.E. cheap shot, Kidney shot, ETC. i feel it'd be useful especially with the latter if talented into internal bleeding, will you be implimenting this in future or does it cause conflicts?

**Comment by Hekili** [comment]
They're generally not useful on raid bosses so generally not accounted for in sims.  There's also no reliable way to tell, via the API, that an enemy is stunnable.

The latest Outlaw Rogue APL does try to use Cheap Shot if Prey on the Weak is talented, but not on bosses, and I haven't gotten feedback on whether it works well or not.
