### ISSUE TITLE
[BUG]  Enabling/Disabling Skin Settings not working with masque 

### ISSUE THREAD

**Issue by nayoad** [Hekili/hekili#3280]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I go into Masque, I am unable to disable the skin settings, and I am also unable to disable features like spell flashes. If I click "disable," the Masque setting in Hekili gets disabled for one second but then instantly reverts back. Even if I change the global settings, it stays locked at the latest setting (the setting I had active while importing the new Cataclysm Hekili over the Wrath one, as suggested in the "not working" issue threads). Even if I disable Masque completely, Hekili somehow retains the Masque settings.

### How to Reproduce

Install masque and make some changes.
Install Hekili wrath via WOWUP + paste cataclysm tree github into addon folder.
Go into masque settings and disable skin settings for hekili. - Not working.

### Player Information (Link)

has nothing to do with my character.

### Error Messages (Link)

No lua error with BugSack/Grabber.

**Comment by Hekili** [comment]
> If I click "disable," the Masque setting in Hekili gets disabled for one second but then instantly reverts back.

What Masque setting in Hekili?

> Install masque and make some changes.
> Install Hekili wrath via WOWUP + paste cataclysm tree github into addon folder.
> Go into masque settings and disable skin settings for hekili. - Not working.

This would be better reported after I actually release for Cataclysm.
