### ISSUE TITLE
[REC] Assa Rogue rotation dont work

### ISSUE THREAD

**Issue by arckos78** [Hekili/hekili#3282]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

the rotation of the rogue assa does not correspond to the current simc, the open is bad, advice Crimson Tempest has a bad window and then no longer advises it to refresh the dot, advice the tea has a bad window too, I think it is necessary update the mono and multi simc because when I look in the addon it has not been updated since 2023

### How to Reproduce

1. Enter the game on Assa Rogue with crimson tempest talent
2. Start opener and rota multi target and see instantly the problem

### Snapshot (Link)

https://pastebin.com/nFHpkQVD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mKqPUDCyBFsAhWAEMqvh2P

### Additional Information

as said above I checked the multi rotation but there are probably also problems in mono since the simc is not up to date since 2023

**Comment by Hekili** [comment]
> I think it is necessary update the mono and multi simc because when I look in the addon it has not been updated since 2023

There are no missing updates to the Assassination Rogue priority compared to SimC.

> Start opener and rota multi target and see instantly the problem

If this is the case, you'll need to snapshot and describe the specific problem.  For example, "X is recommended but Y should've been used here because Z."  Your snapshot(s) should correspond the problems described.
