### ISSUE TITLE
[REC] Dragonfire Bomb Dispenser and Grieftorch on Outlaw

### ISSUE THREAD

**Issue by Gyudon47** [Hekili/hekili#3283]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Bomb dispenser should not be used out of stealth on pull because of subterfuge bug, everywhere else is ok. Also grieftorch should have priority over bomb dispenser.

My quick sim:https://www.raidbots.com/simbot/report/wHdEdBufwrrVE81AurWDPb

### How to Reproduce

follow recommendation from addon 

### Snapshot (Link)

https://pastebin.com/v0tS0Ghu

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wHdEdBufwrrVE81AurWDPb

### Contact Information

gyu

**Comment by Hekili** [comment]
Is there more information about this Subterfuge bug somewhere?  Your sims have unfortunately expired since posting.
