### ISSUE TITLE
Backstab not showing 

### ISSUE THREAD

**Issue by GoldGamingGER** [Hekili/hekili#3286]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hey. My Assa Rogue got a big problem. if any target is below 30% not a single spell is showing.

### How to Reproduce

Enter Game as Assa Rogue . Put down any mob below 30% and then Hekili is vanishing.

### Snapshot (Link)

https://pastebin.com/7D6S3m8M

### Contact Information

goldgamingtm

**Comment by GoldGamingGER** [comment]
I did an short clip of a fight, where you can see the problem
https://medal.tv/de/games/wow-classic/clips/2eYhUEUtHdbL-z/d13377mSj85x?invite=cr-MSxrNUUsMjIyNzEwNTY5LA

**Comment by Smufrik** [comment]
I have pushade a pullrequest to fix this👍
