### ISSUE TITLE
Not pulling from my class spec

### ISSUE THREAD

**Issue by cleadens** [Hekili/hekili#3289]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon won't recommend my frost DK spec.  it is pulling blood and unholy spells

### How to Reproduce

enter game frost dk, cast spells and the recommendation spells are for blood dk and not frost.  it is not loading correct profile

### Snapshot (Link)

https://pastebin.com/GcJkJ1Xj

### Contact Information

chadleadens@yahoo.com

**Comment by Supernuss** [comment]
Are we talking Cataclysm here? If yes, we implemented a Frost spec some weeks ago. Check https://discord.com/channels/307520968895627264/1236954018035793931/1236954020023635979 for more information.
