### ISSUE TITLE
[Request] Add Dragon Roar/Bladestorm to Exclude Out-of-Range Abilities Toggle

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#329]
Currently with the "Exclude Out-of-Range" option enabled in the priority settings, Dragon Roar & Bladestorm are suggested even when you are very far away from your target.

Can you add a range check to this ability as well like you did with Whirlwind? Thank you again for your time!

https://www.wowhead.com/spell=118000/dragon-roar

https://www.wowhead.com/spell=46924/bladestorm

**Comment by ghost** [comment]
Hi,

Not trying to rush or be rude but it's been about a month since I submitted this and was wondering if you have an ETA as to when it might be implemented?

Thank you again for your hard work!

**Comment by Hekili** [comment]
Yeah, this just hasn't been a high priority on it's own vs. adding that information to all the spells that are applicable.  I'll get to it eventually.

**Comment by Hekili** [comment]
Added for 06-beta2.
