### ISSUE TITLE
[REC] Destruction Warlock recommends immolate spam, seemingly trying to immolate cycle targets

### ISSUE THREAD

**Issue by phatzz** [Hekili/hekili#3291]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon recommends immolate on main target multiple times because it does not find valid cycle targets.
Potential cycle targets have a low expected time to die, but then it shouldnt fill the recommendation with immolation (with no cycle indicator)

### How to Reproduce

1. Enter game as destruction warlock
2. fight multiple enemies with a primary mob with a long time to die, and adds with low time to die
3. see snapshot filled with immolation with no cycle indicator

### Snapshot (Link)

https://pastebin.com/z5vYaptb

### Contact Information

discord id : phatzzz

**Comment by phatzz** [comment]
I haven't seen this issue on any other multidot specs i played, mainly shadowpriest - only on destruction warlock with immolate

**Comment by Zanetsuken** [comment]
Well, You should be spreading immolate to generate soul shards for RoF, unless there are enough mobs in the pack to make RoF self sustaining.
If you are not seeing the cycle target indicator - Have you checked that swap targets is on? It is likely the addon wants you to spread immolate because it wants to use the AOE profile.

**Comment by phatzz** [comment]
> Well, You should be spreading immolate to generate soul shards for RoF, unless there are enough mobs in the pack to make RoF self sustaining. If you are not seeing the cycle target indicator - Have you checked that swap targets is on? It is likely the addon wants you to spread immolate because it wants to use the AOE profile.

? 
I don't think you understand the issue, i know how to spread immolate and if the targets are consistent the addon is displaying it fine.
In the snapshot it is showing 3x immolate in a row with no cycle indicator, although the cyckle indicator in most circumstances works fine and is turned on.

**Comment by Hekili** [comment]
@phatzz is correct that this is an issue; enemies that will die quickly are not counted as eligible for target swaps but the condition for Immolate is written to allow the recast.  I'll post a fix soon.

**Comment by phatzz** [comment]
> @phatzz is correct that this is an issue; enemies that will die quickly are not counted as eligible for target swaps but the condition for Immolate is written to allow the recast. I'll post a fix soon.

Thank you, appreciate all your work!
