### ISSUE TITLE
[CATA] Mage not loading the auto profiles tried import got the following error all other classes load fine

### ISSUE THREAD

**Issue by RdyPlayerOne** [Hekili/hekili#3292]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

no profiles for mage are loading unless i try to make from scratch all other classes initilize fine i get an lua error

### How to Reproduce

i'm a mage with dual specialization in fire but no second spec 

### Player Information (Link)

https://pastebin.com/gYa8GCmw

### Error Messages (Link)

https://pastebin.com/nujEK2zx

### Contact Information

rhinoisdead

**Comment by RdyPlayerOne** [comment]
to get the lua error you have to try to import a action list in share priorities

**Comment by grftn** [comment]
bump

**Comment by Supernuss** [comment]
Are we talking about Cataclysm here? Check the Mage-Thread that is linked here for a working mage Profile: https://discord.com/channels/307520968895627264/1236954018035793931/1236954020023635979

**Comment by Hekili** [comment]
Mage doesn't have any priorities ready to go (the Wrath versions are commented out in Cataclysm/Mage.lua).  This means it is not supported (yet).
