### ISSUE TITLE
[Enhancement] Primordial Wave never recomended

### ISSUE THREAD

**Issue by Daygath** [Hekili/hekili#3294]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Primordial Wave is core to the current season set bonus, but it never comes up in the rotation suggestion. It should be among the highest priority. Because the current season is a copy of last season I suspect it's looking for last season's set instead of this season as well. No snapshot because I can't show a nothing. It just never shows up.

2pc
Primordial Wave summons a Lightning Feral Spirit that increases your Nature damage dealt by 20% for 15 sec.
4pc
Summoning a Feral Spirit reduces the cooldown of Primordial Wave by 7.0 sec.

### How to Reproduce

Use a shaman with season 4 4pc set. No snapshot because I can't show a nothing. It just never shows up.

### Snapshot (Link)

asds

### Contact Information

teknomage13@gmail.com

**Comment by Hekili** [comment]
Closing as ticket is not complete.
