### ISSUE TITLE
[REC] Fyr'alath On Use effect should not be recommended during Paladin's Execution Sentence

### ISSUE THREAD

**Issue by Ketrel** [Hekili/hekili#3295]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The damage caused by Fyr'alath's use effect does not seem to count towards Execution Sentence, so it should not be recommended for use while the enemy has the Execution sentence debuff.

### How to Reproduce

1. Have both abilities available
2. Use Execution Sentence

### Snapshot (Link)

https://pastebin.com/d36vYtMC

**Comment by Hekili** [comment]
Thanks.  This occurs because the `main_hand` entry in the Retribution APL should not fire when there is an actual entry for `fyralath_the_dreamrender` in the priority, but currently does.

Disabling the 9th entry in the `cooldowns` priority list should work as a temporary workaround.
