### ISSUE TITLE
[REC] Arms Priority List Typo Preventing Sweeping Strikes Recommendation

### ISSUE THREAD

**Issue by nat986** [Hekili/hekili#3296]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Arms AOE actionlist not recommending sweeping strikes / cleave due to typo (missed linebreak) in WarriorArms.simc

### How to Reproduce

1. Approach Target dummies as Arms warrior in AOE spec
2. After opener, sweeping strikes should be recommended.

There is a _typo_ in the WarriorArms.simc: line 55 is a **missing line break**, causing the recommendation for sweeping strikes / cleave to never trigger.

Current:
```
actions.aoe+=/whirlwind,if=buff.collateral_damage.up&debuff.colossus_smash.remains&buff.sweeping_strikes.downactions.aoe+=/thunder_clap,if=talent.thunder_clap&talent.blood_and_thunder&talent.rend&dot.rend.remains<=dot.rend.duration*0.3
```

Proposed:
```
actions.aoe+=/whirlwind,if=buff.collateral_damage.up&debuff.colossus_smash.remains&buff.sweeping_strikes.down
actions.aoe+=/thunder_clap,if=talent.thunder_clap&talent.blood_and_thunder&talent.rend&dot.rend.remains<=dot.rend.duration*0.3
``` 

### Snapshot (Link)

-- See above (simple typo!)

### Contact Information

tyrukian on discord

**Comment by nat986** [comment]
After adding this line break to the APL in-game, Sweeping Strikes is recommended properly in AOE situations.

**Comment by Hekili** [comment]
Fix is pending.

**Comment by nat986** [comment]
Fix was applied, closing issue
