### ISSUE TITLE
WarlockDestruction has always recommended immolate in AOE

### ISSUE THREAD

**Issue by hellovvorld1024** [Hekili/hekili#3299]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I will turn off Recommend Target Swaps when I don't want to switch targets.
It still insists on recommending immolate and no cycle icon ">".

This results in constantly recommending immolate to the primary target regardless of whether it has a dot or not, and without judging it as refreshable.

action.aoe 18 lines
`actions.aoe+=/immolate,cycle_targets=1,if=((dot.immolate.refreshable(!talent.cataclysm.enabled|cooldown.cataclysm.remains>dot.immolate.remains))|active_enemies>active_dot.immolate)&target.time_to_die>10&!havoc_active`

The same problem exists with Havoc
Havoc is still recommended when Recommend Target Swaps is closed. and the cycle icon ">" is present.
[https://pastebin.com/uQgnUm00](https://pastebin.com/uQgnUm00)

### How to Reproduce

1. WarlockDestruction
2. in AOE
3. turn off Recommend Target Swaps

### Snapshot (Link)

https://pastebin.com/QcrQaiHQ

**Comment by hellovvorld1024** [comment]
Forgive me for posting it and then realizing that you've already noticed the problem
[#3291](https://github.com/Hekili/hekili/issues/3291)

**Comment by Hekili** [comment]
Closing duplicate.
