### ISSUE TITLE
[BUG] CATA Enabling "Show Separately" on Cooldowns breaks Cooldown.ability.up 

### ISSUE THREAD

**Issue by Shinerva** [Hekili/hekili#3302]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When making use of "cooldown.ability.up" in conditions, it always returns FALSE when you have "Show Separately" ticked against cooldowns.

example - cooldown.unholy_frenzy.up
even if you have unholy frenzy available, it will show as false

the moment I untick "show separately" for cooldowns, it will then return true.

currently, only tested this on CATA

### How to Reproduce

download and install:
https://github.com/Supernuss/hekili/releases/tag/v4.4.0-0.1.12

go to the priorities for unholy DK - you'll see number 13 = Summon Gargoyle and hovering over the conditions you can see cooldown.unholy_frenzy.up = true.
![image](https://github.com/Hekili/hekili/assets/16002386/4d5a419f-5806-4adf-a3d3-c07183c99106)

go to Toggles and tick "show separately" for cooldowns.
![image](https://github.com/Hekili/hekili/assets/16002386/0d28d29c-ba68-46fe-af19-9e04ff030034)

then back to the unholy entry for Summon Gargoyle and you'll see it's now showing as false:
![image](https://github.com/Hekili/hekili/assets/16002386/b2076dfb-3682-4fb0-aa2b-163dbdde990f)

### Player Information (Link)

build: v4.4.0-0.1.12 level: 85 (85) class: DEATHKNIGHT spec: deathknight  talents: anti_magic_zone     bladed_armor     butchery     contagion     dark_transformation     ebon_plaguebringer     epidemic     improved_blood_tap     improved_unholy_presence     magic_suppression     master_of_ghouls     morbidity     rage_of_rivendare     reaping     runic_corruption     scourge_strike     shadow_infusion     sudden_doom     summon_gargoyle     unholy_blight     unholy_command     unholy_frenzy     virulence  pvptalents: none  covenant: none  conduits: none  soulbinds: none  sets: none  gear: band_of_bees = 1     battleplate_of_ancient_kings = 1     bracers_of_cooled_anger = 1     gift_of_nadun = 1     gorsiks_band_of_shattering = 1     greaves_of_wu_the_elder = 1     heart_of_solace = 1     license_to_slay = 1     mainhand = 1     mainhand_2h = 1     plated_fists_of_provocation = 1     razs_pauldrons = 1     reinforced_biooptic_killshades = 1     relic_of_aggramar = 1     shalugdoom_the_axe_of_unmaking = 1     sky_strider_belt = 1     tabard_of_the_wildhammer_clan = 1     terrastras_legguards = 1     wrap_of_the_great_turtle = 1  legendaries: none  itemIDs: 56301, 56318, 56381, 56393, 58180, 58185, 59225, 59330, 59359, 59503, 62350, 62383, 62447, 63490, 64674, 65062, 65908  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcd = 47541     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = true     noFeignedCooldown = false     package = Unholy Shin     petbased = false     potion = prolonged_power     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     usePackSelector = true     blood = Blood (Beta)     frost = Frost DK (IV)     unholy = Unholy (IV)  toggles:     cooldowns = true [separate]     custom1 = false      custom2 = false      defensives = true [separate]     essences = false [overridden]     interrupts = false      mode = automatic      potions = false   keybinds:      antimagic_shell     = S`  [05]     antimagic_zone      = SZ  [05]     army_of_the_dead    = A5  [05]     blood_boil          = E   [06]     blood_tap           = A4  [05]     chains_of_ice       = SF  [06]     dark_command        = -   [01]     dark_transformation = S1  [06]     death_and_decay     = Q   [06]     death_coil          = 3   [01]     death_grip          = SSPACE[06]     death_pact          = SR  [03]     death_strike        = SQ  [06]     empower_rune_weapon = S3  [06]     festering_strike    = 4   [01]     horn_of_winter      = A1  [05]     icebound_fortitude  = S4  [06]     icy_touch           = 1   [01]     mind_freeze         = 7   [01], F   [06]     outbreak            = `   [05]     pestilence          = SE  [06]     plague_strike       = 5   [01]     raise_ally          = AQ  [03]     raise_dead          = A2  [05], -   [07]     rune_strike         = 7   [07]     scourge_strike      = 2   [01]     strangulate         = S=  [05]     summon_gargoyle     = S2  [06]     synapse_springs     = 8   [01]     unholy_frenzy       = 9   [01]     will_to_survive     = A3  [05]

### Error Messages (Link)

No error message

### Additional Information

Not sure if you need anything else, but feel free to ping me on discord - shinerva

### Contact Information

shinerva

**Comment by Shinerva** [comment]
Update -

cooldown.ability.remains 
also doesn't work when this option is ticked.

raise ghoul for example - doesn't show the remaining cooldown and instead just shows 180 (the full duration of the cooldown)

**Comment by Hekili** [comment]
This is how Show Separately works -- it puts the ability on its full cooldown in the other displays so it won't be recommended, and then uses actual cooldown information in the separate (i.e., Cooldowns) display.

If you're writing a custom priority, you can use `cooldown.ability.true_remains` to access the actual remaining time.
