### ISSUE TITLE
TWW Beta operation

### ISSUE THREAD

**Issue by Jundoh** [Hekili/hekili#3304]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Just wondering if it would be possible to update this so it can be used on the TWW Beta? not asking for rotation adjustments, i can tinker with that in game, just asking for basic operation of the addon in the BETA if possible. I'm aware that some classes will have issues due to ability changes, but several classes didn't have any changes and only have 1 new ability. that may not show in the list. 

### Additional Information

Current version will not load in the beta servers. It appears to just be a version conflict. 

### Contact Information

tigerray00@gmail.com

**Comment by masterkain** [comment]
considering there's not even a release for cataclysm I doubt it, I guess you can either patreon or contribute :)
personally I don't think there will be something ready for tww release too, but I don't know any plans

**Comment by Hekili** [comment]
I'll release when it's ready.
