### ISSUE TITLE
LF Cata enha profile

### ISSUE THREAD

**Issue by LaceRH** [Hekili/hekili#3309]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Would like a properly working cata enha profile :) 

### Contact Information

LaceRH

**Comment by Supernuss** [comment]
Check https://discord.com/channels/307520968895627264/1236954018035793931/1236954020023635979 which Specs are supported :)
