### ISSUE TITLE
Queue Icon - Separate Keybinds Settings

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#331]
Would like to request the queue icons get their own keybind settings or at least just the ability to adjust the font size for it.

My queue icons are smaller than main icon so the keybind text looks massive on the queue icon because it inherits the main icon font size.

**Comment by Hekili** [comment]
This isn't unreasonable.  I'll put it on my list.

**Comment by Hekili** [comment]
Adding font, font size, font color, and lowercase toggle in /hekili > Displays > X > Keybinds (check Use Different Settings for Queue).  Available in -alpha42.
