### ISSUE TITLE
[BUG] HEkili not showing up 

### ISSUE THREAD

**Issue by Defreakshow** [Hekili/hekili#3311]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

shows on every charecter but my dk 

### How to Reproduce

enter game as death knight

### Player Information (Link)

Blood; Primary - N/A build: v10.2.7-1.0.3 level: 10 (10) class: DEATHKNIGHT spec: blood  talents: BoPA/gf1fDREKLfAcG9Z2HkF/BAAAAAAAAAAAAAAAAAAAAAAAAAAA     death_strike = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: none  gear: cloak_of_infinite_potential = 1     greenstone_boots = 1     greenstone_breastplate = 1     greenstone_legguards = 1     timerunners_greatsword = 1  legendaries: none  itemIDs: 208470, 208473, 210275, 210333, 224075  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxTime = 20     nameplateRange = 10     nameplates = true     noFeignedCooldown = false     package = Blood     petbased = false     potion = potion_of_phantom_fire     rangeFilter = false     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     death_strike_pool_amount = 65     ibf_damage = 40     rt_damage = 30     save_blood_shield = true     vb_damage = 50  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = automatic      potions = false   keybinds:      chains_of_ice   = SE  [06]     dark_command    = SF  [06]     death_and_decay = M3  [03]     death_coil      = V   [01]     death_grip      = F   [01]     death_strike    = =   [01]     deaths_advance  = S1  [06]     lichborne       = S2  [06]     rune_strike     = 1   [01]  warnings: none   targets:  Nameplates are enabled.  - Checking nameplate1 [ Creature-0-3748-870-1094-66282-00007E9521 ] Garrosh'ar Grunt.     - Excluded by range (45 > 10).  player_buffs:     45444 - *bonfires_blessing                       -   1 - 3600.00    424143 - *wow_remix_mists_of_pandaria             -   1 - 3600.00    439568 - *runeforge                               -   1 - 3600.00    459337 - *timerunners_mastery                     -   1 - 3600.00    440393 - *timerunners_advantage                   -   1 - 3600.00  player_debuffs:  target_auras:  target does not exist   New Recommendations for [ Primary ] requested at 21:03:42 ( 1383676.85 ); using built-in ( Blood ) priority. *** START OF NEW DISPLAY: Primary *** Purged 167 marked values in 0.06ms.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: runes[ 6.00 / 6.00 ], runic_power[ 0.00 / 115.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Blood - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   fleshcraft ( precombat - 1 ) - not usable here         Time spent on this action:  0.02ms         TimeData:Blood-precombat-1:fleshcraft:0.02:Ability Known, Enabled(0.02)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Blood - precombat ].          Processing default action list [ Blood - default ].                  Current recommendation was NO ACTION at +10.00s.                  2.   mind_freeze ( default - 1 ) - talent [ mind_freeze ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-1:mind_freeze:0.01:Ability Known, Enabled(0.01)                  3.   strangulate ( default - 2 ) - PvP talent [ strangulate ] missing         Time spent on this action:  0.02ms         TimeData:Blood-default-2:strangulate:0.02:Ability Known, Enabled(0.02)                  4.   variable ( default - 3 )          - variable.death_strike_dump_amount[65] will check this script entry ( Blood:default:3 )         Time spent on this action:  0.02ms         TimeData:Blood-default-3:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  5.   variable ( default - 4 )          - variable.bone_shield_refresh_value[4] will check this script entry ( Blood:default:4 )         Time spent on this action:  0.02ms         TimeData:Blood-default-4:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  6.   potion ( default - 5 ) - ability disabled ( toggle potions )         Time spent on this action:  0.23ms         TimeData:Blood-default-5:potion:0.23:Ability Known, Enabled(0.23)                  7.   call_action_list:trinkets ( default - 6 )         There is no criteria for trinkets.         Action list (trinkets) was found.         + trinkets         Current recommendation was NO ACTION at +10.00s.                  8.   fyralath_the_dreamrender ( trinkets - 1 ) - IsUsableItem item 206448 and nil         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-1:fyralath_the_dreamrender:0.02:Ability Known, Enabled(0.02)                  9.   variable ( trinkets - 2 )          - variable.trinket_1_buffs[false] will check this script entry ( Blood:trinkets:2 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  10.  variable ( trinkets - 3 )          - variable.trinket_2_buffs[false] will check this script entry ( Blood:trinkets:3 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-3:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  11.  variable ( trinkets - 4 )          - variable.trinket_1_exclude[false] will check this script entry ( Blood:trinkets:4 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-4:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  12.  variable ( trinkets - 5 )          - variable.trinket_2_exclude[false] will check this script entry ( Blood:trinkets:5 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-5:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  13.  variable ( trinkets - 6 )          - variable.damage_trinket_priority[2] will check this script entry ( Blood:trinkets:6 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-6:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  14.  trinket1 ( trinkets - 7 )         Time spent on this action:  0.01ms         TimeData:Blood-trinkets-7:trinket1:0.01:Ability Known, Enabled(0.01)                  Bypassing 'trinket2' action because the equipped trinket #2 is not usable.                  15.  trinket2 ( trinkets - 8 )         Time spent on this action:  0.01ms         TimeData:Blood-trinkets-8:trinket2:0.01:Ability Known, Enabled(0.01)                  16.  use_items ( trinkets - 9 )         Criteria for ??? FAIL at +0.00 - ( variable.trinket_1_buffs[false] | trinket.t1.cooldown.remains[0.00] ) & ( variable.trinket_2_buffs[false] | trinket.t2.cooldown.remains[0.00] )                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  17.  trinket1 ( trinkets - 10 )         Time spent on this action:  0.01ms         TimeData:Blood-trinkets-10:trinket1:0.01:Ability Known, Enabled(0.01)                  Bypassing 'trinket2' action because the equipped trinket #2 is not usable.                  18.  trinket2 ( trinkets - 11 )         Time spent on this action:  0.01ms         TimeData:Blood-trinkets-11:trinket2:0.01:Ability Known, Enabled(0.01)                  19.  main_hand ( trinkets - 12 )         The action (main_hand) is unusable at (0.00 + 0.00) because ability.usable was false.         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-12:main_hand:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01):Post Cycle(0.00):Post Usable(0.00)         Exiting trinkets with recommendation of NO ACTION at +10.00s.         Returned from list (trinkets), current recommendation is NO ACTION (+10.00).         - trinkets                  20.  raise_dead ( default - 7 ) - talent [ raise_dead ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-7:raise_dead:0.01:Ability Known, Enabled(0.01)                  21.  icebound_fortitude ( default - 8 ) - talent [ icebound_fortitude ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-8:icebound_fortitude:0.01:Ability Known, Enabled(0.01)                  22.  vampiric_blood ( default - 9 ) - talent [ vampiric_blood ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-9:vampiric_blood:0.01:Ability Known, Enabled(0.01)                  23.  rune_tap ( default - 10 ) - talent [ rune_tap ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-10:rune_tap:0.01:Ability Known, Enabled(0.01)                  24.  death_strike ( default - 11 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Blood-default-11:death_strike:0.01:Ability Known, Enabled(0.01)                  25.  deaths_caress ( default - 12 ) - talent [ deaths_caress ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-12:deaths_caress:0.01:Ability Known, Enabled(0.01)                  26.  death_and_decay ( default - 13 )         The action (death_and_decay) is usable at (0.00 + 0.00) with cost of 1 runes (have 6).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: ! death_and_decay.ticking[false] & ( talent.unholy_ground.enabled[false] | talent.sanguine_ground.enabled[false] | spell_targets.death_and_decay[1.00] > 3 | buff.crimson_scourge.up[false] )         There were no recheck events to check.         Time spent on this action:  0.11ms         TimeData:Blood-default-13:death_and_decay:0.11:Ability Known, Enabled(0.01):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.02):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.02):Pre-Recheck(0.01):Post-Recheck Times(0.00):Post Recheck(0.00)                  27.  death_strike ( default - 14 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Blood-default-14:death_strike:0.01:Ability Known, Enabled(0.01)                  28.  blooddrinker ( default - 15 ) - talent [ blooddrinker ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-15:blooddrinker:0.01:Ability Known, Enabled(0.01)                  29.  call_action_list:racials ( default - 16 )         There is no criteria for racials.         Action list (racials) was found.         + racials         Current recommendation was NO ACTION at +10.00s.                  30.  blood_fury ( racials - 1 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-1:blood_fury:0.02:Ability Known, Enabled(0.02)                  31.  berserking ( racials - 2 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Blood-racials-2:berserking:0.01:Ability Known, Enabled(0.01)                  32.  arcane_pulse ( racials - 3 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Blood-racials-3:arcane_pulse:0.01:Ability Known, Enabled(0.01)                  33.  lights_judgment ( racials - 4 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Blood-racials-4:lights_judgment:0.01:Ability Known, Enabled(0.01)                  34.  ancestral_call ( racials - 5 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Blood-racials-5:ancestral_call:0.01:Ability Known, Enabled(0.01)                  35.  fireblood ( racials - 6 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Blood-racials-6:fireblood:0.01:Ability Known, Enabled(0.01)                  36.  bag_of_tricks ( racials - 7 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Blood-racials-7:bag_of_tricks:0.01:Ability Known, Enabled(0.01)                  37.  arcane_torrent ( racials - 8 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Blood-racials-8:arcane_torrent:0.01:Ability Known, Enabled(0.01)         Exiting racials with recommendation of NO ACTION at +10.00s.         Returned from list (racials), current recommendation is NO ACTION (+10.00).         - racials                  38.  sacrificial_pact ( default - 17 ) - talent [ sacrificial_pact ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-17:sacrificial_pact:0.01:Ability Known, Enabled(0.01)                  39.  call_action_list:covenants ( default - 18 )         Criteria for covenants FAIL at +0.00 - ! covenant.none[true]                  40.  blood_tap ( default - 19 ) - talent [ blood_tap ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-19:blood_tap:0.01:Ability Known, Enabled(0.01)                  41.  gorefiends_grasp ( default - 20 ) - talent [ gorefiends_grasp ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-20:gorefiends_grasp:0.01:Ability Known, Enabled(0.01)                  42.  empower_rune_weapon ( default - 21 ) - talent [ empower_rune_weapon ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-21:empower_rune_weapon:0.01:Ability Known, Enabled(0.01)                  43.  abomination_limb ( default - 22 ) - not usable here         Time spent on this action:  0.01ms         TimeData:Blood-default-22:abomination_limb:0.01:Ability Known, Enabled(0.01)                  44.  dancing_rune_weapon ( default - 23 ) - talent [ dancing_rune_weapon ] missing         Time spent on this action:  0.01ms         TimeData:Blood-default-23:dancing_rune_weapon:0.01:Ability Known, Enabled(0.01)                  45.  run_action_list:drw_up ( default - 24 )         Criteria for drw_up FAIL at +0.00 - buff.dancing_rune_weapon.up[false]                  46.  call_action_list:standard ( default - 25 )         There is no criteria for standard.         Action list (standard) was found.         + standard         Current recommendation was NO ACTION at +10.00s.                  47.  tombstone ( standard - 1 ) - talent [ tombstone ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-1:tombstone:0.01:Ability Known, Enabled(0.01)                  48.  variable ( standard - 2 )          - variable.heart_strike_rp[10] will check this script entry ( Blood:standard:2 )         Time spent on this action:  0.02ms         TimeData:Blood-standard-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  49.  death_strike ( standard - 3 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Blood-standard-3:death_strike:0.01:Ability Known, Enabled(0.01)                  50.  deaths_caress ( standard - 4 ) - talent [ deaths_caress ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-4:deaths_caress:0.01:Ability Known, Enabled(0.01)                  51.  marrowrend ( standard - 5 ) - talent [ marrowrend ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-5:marrowrend:0.01:Ability Known, Enabled(0.01)                  52.  consumption ( standard - 6 ) - talent [ consumption ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-6:consumption:0.01:Ability Known, Enabled(0.01)                  53.  soul_reaper ( standard - 7 ) - talent [ soul_reaper ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-7:soul_reaper:0.01:Ability Known, Enabled(0.01)                  54.  soul_reaper ( standard - 8 ) - talent [ soul_reaper ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-8:soul_reaper:0.01:Ability Known, Enabled(0.01)                  55.  bonestorm ( standard - 9 ) - talent [ bonestorm ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-9:bonestorm:0.01:Ability Known, Enabled(0.01)                  56.  blood_boil ( standard - 10 ) - talent [ blood_boil ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-10:blood_boil:0.01:Ability Known, Enabled(0.01)                  57.  heart_strike ( standard - 11 ) - talent [ heart_strike ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-11:heart_strike:0.01:Ability Known, Enabled(0.01)                  58.  blood_boil ( standard - 12 ) - talent [ blood_boil ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-12:blood_boil:0.01:Ability Known, Enabled(0.01)                  59.  heart_strike ( standard - 13 ) - talent [ heart_strike ] missing         Time spent on this action:  0.01ms         TimeData:Blood-standard-13:heart_strike:0.01:Ability Known, Enabled(0.01)         Exiting standard with recommendation of NO ACTION at +10.00s.         Returned from list (standard), current recommendation is NO ACTION (+10.00).         - standard         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Blood - default ].     Recommendation is NO ACTION at 0.00 + 10.00.     Recommendation #1 is NO ACTION at 10.00s (10.00s).     Resources: Resources: runes[ 6.00 / 6.00 | 6.00 @ [1 - actual] 0.00 ], runic_power[ 0.00 / 115.00 | 0.00 @ [1 - actual] 0.00 ]     Time spent generating recommendations:  1.92ms

### Error Messages (Link)

1x ...tes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1507: attempt to call global 'IsQuestFlaggedCompleted' (a nil value) [string "@HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua"]:1507: in function `?' [string "@Details/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...ceDetails/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>  Locals: self = <table> {  SetDefaultModuleLibraries = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:363  Enable = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:290  RegisterChatCommand = <function> defined @AstralKeys/Libs/AceConsole-3.0/AceConsole-3.0.lua:85  LoginMessage = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1764  EnableModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:328  modules = <table> {  }  GetModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:206  IterateEmbeds = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:438  defaultModuleLibraries = <table> {  }  TimeLeft = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:172  UnregisterChatCommand = <function> defined @AstralKeys/Libs/AceConsole-3.0/AceConsole-3.0.lua:111  ScheduleRepeatingTimer = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:129  CancelAllTimers = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:160  Printf = <function> defined @AstralKeys/Libs/AceConsole-3.0/AceConsole-3.0.lua:69  SetDefaultModulePrototype = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:405  nodes = <table> {  }  baseName = "HandyNotes_DraenorTreasures"  OnInitialize = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1439  name = "DraenorTreasures"  HasBeenLooted = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1660  IsEnabled = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:447  orderedModules = <table> {  }  ScheduleTimer = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:94  DisableModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:346  Refresh = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1651  RegisterWithHandyNotes = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1574  QuestCheck = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1505  WorldEnter = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1497  RegisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:80  UnregisterBucket = <function> defined @HandyNotes_Draenor/Lib/AceBucket-3.0/AceBucket-3.0.lua:202  Print = <function> defined @AstralKeys/Libs/AceConsole-3.0/AceConsole-3.0.lua:54  LoadCheck = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1679  OnLeave = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:1000  OnClick = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:992  OnEnter = <function> defined @HandyNotes_DraenorTreasures/HandyNotes_DraenorTreasures.lua:895  IsModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:464  db = <table> {  }  SetDefaultModuleState = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:383  CancelTimer = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:147  SendMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:49  SetEnabledState = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:420  UnregisterAllBuckets = <function> defined @HandyNotes_Draenor/Lib/AceBucket-3.0/AceBucket-3.0.lua:225  enabledState = true  UnregisterAllEvents = <function> defined

### Contact Information

defreakshow

**Comment by Wyste** [comment]
Looks like your on MOP Remix and your only level 10. Hekili was primarily designed for max level on retail usage.

**Comment by syrifgit** [comment]
Blood; Primary - N/A build: v10.2.7-1.0.3 **_level: 10 (10)_**

When you log in, the addon should give you a big warning message in the middle of your screen letting you know it was designed for max level use. Results below max level will be mixed at best.

**Comment by Defreakshow** [comment]
thanks

**Comment by Defreakshow** [comment]
showed up straight away for other mop charecters but my dk it didnt show up till about lvl 20
