### ISSUE TITLE
[FEATURE] REPLACE THIS TEXT WITH A BRIEF DESCRIPTION OF YOUR NEW FEATURE

### ISSUE THREAD

**Issue by Rentastic** [Hekili/hekili#3315]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I have tried but cannot download hekili for cataclysm.  I am not extremely computer capable.  Please help

**Comment by Supernuss** [comment]
> * I edited the title of this feature request (above) so that it describes the issue I am reporting.

![8vg5ls](https://github.com/Hekili/hekili/assets/126069971/dc2e3753-5254-485a-a1b9-0b3e5e0d5de0)

Anyway - find the download link here: https://discord.com/channels/307520968895627264/1236954018035793931/1236954020023635979
