### ISSUE TITLE
Mage Arcane: Unable to Recommend while Evocation is Channeling

### ISSUE THREAD

**Issue by Behnam45** [Hekili/hekili#3316]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hey, For my Mage Arcane when i played after 20-30sec in combat, hekili addon get auto snapshots and 1screen shot from my game. and the rotation of mage arcane its not right because i saw some guide videos and there is a different priority in guide and recommendation hekili
and there is 4 different (1.Arcane Primary 2.Arcane interrupts 3.Arcane defensive 4.Arcane Cooldowns) snapshots but i upload just primary if you need tell me to upload all of them
i see 1other ticket open in issue arcane but mine is different

### How to Reproduce

just go and ply mage arcane in 1 hours in AOE rotation or ST you will get this error and snapshots

### Snapshot (Link)

https://pastebin.com/wBFh8kTX

**Comment by Hekili** [comment]
Looking at your snapshot, it looks like the addon fast-forwards to the end of your Evocation channel but then still limits what it can recommend to spells that are castable-while-channeling.  I'll investigate.
