### ISSUE TITLE
[FEATURE] Add completely safe rockets to hunter rotations

### ISSUE THREAD

**Issue by aphnxrising** [Hekili/hekili#3317]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'd like completely safe rockets to be added to hunters so I know when to reapply it

### Contact Information

aphnxrising

**Comment by Hekili** [comment]
This is not planned; I'd recommend using a WeakAura.
