### ISSUE TITLE
Holy priest rotation does not recommend divine word

### ISSUE THREAD

**Issue by LoneLily993** [Hekili/hekili#3318]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello, I just recently made it to 69 on my holy priest and talented into divine word. This immediately caused some issues. At first it would only recommend Holy Fire, Shadow word: Pain, and then smite until Holy Fire comes off cooldown. The only way I could find to get it to show a normal rotation is turning off the divine_favor_filler entry in the action list. This did bring back the normal rotation but it does not include Divine word at any point. I have tried moving the action list around, changing my talents, reloading the ui, reloading the game, disabling all addons and reloading ect. 

Worth mentioning that prior to turning off the filler action I did not touch the action list whatsoever, and I have reset my profile just to make sure I hadn't potentially turned something off by accident. I also have Divine Image talented if it matters, I have tried removing Divine Image to see if that had any effect as well, but no luck.

Snapshot provide is of default profile on hekili with Divine Word talented. Let me know if anything else is needed. Thank you !

### How to Reproduce

1. Play holy priest  

2. Take the Divine Word talent

### Snapshot (Link)

https://pastebin.com/PcZfmb3G

**Comment by Hekili** [comment]
Looking at the priority for Holy Priest:
* You have Divine Word talented, which requires Divine Word to be up before using Holy Word: Chastise.
* You have Empyreal Blaze talented; this makes Divine Word require the Empyreal Blaze buff to be **up** before using Divine Word.
* Empyreal Blaze is procced by Holy Word: Chastise, so the addon can't recommend Holy Word: Chastise.

If you sim your character on Raidbots, you'd probably find that the same issue occurs.

I'll look at adjusting the entry for Holy word: Chastise.
