### ISSUE TITLE
[BUG] [Cata] Cannot get the addon to load

### ISSUE THREAD

**Issue by HauntedOne** [Hekili/hekili#3319]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon always fails to load for me. Here is the bug sack error message I always get:

2x hekili/embeds.xml:11 Couldn't open hekili/Libs/AceEvent-3.0-4/AceEvent-3.0.xml

Typing /hekili does nothing, the options menu does not open.

### How to Reproduce

1. Launch the game.
2. Log into any character.
3. Addon fails to load.

### Player Information (Link)

Typing /hekili does nothing, cannot open the menu.

### Error Messages (Link)

2x hekili/embeds.xml:11 Couldn't open hekili/Libs/AceEvent-3.0-4/AceEvent-3.0.xml

### Contact Information

parker222

**Comment by Hekili** [comment]
There are already open tickets; I have not posted a Cataclysm release at this time.
