### ISSUE TITLE
Lag on showing when skills are ready (gcd finished)

### ISSUE THREAD

**Issue by ekko84** [Hekili/hekili#332]
I'm a BM hunter, I've noticed at times the addon is still showing the gcd as in progress for the next skill but I can see on my action bars that the gcd is finished.

**Comment by Hekili** [comment]
1. Please submit a complete ticket with snapshot when reporting an issue. 

2. The spiral isn't only showing GCD (dependent on your display config, which I can't see). It's showing that you're should still be waiting to use the next ability. That can be resource generation or related to buffs/debuffs.

If you think there's an error with recommendations, submit a snapshot with a new ticket (see the instructions in a new ticket) when it's having you wait and I can show you why it wants you to wait.
