### ISSUE TITLE
Not showing up on any characters setjustifyv

### ISSUE THREAD

**Issue by v2davee** [Hekili/hekili#3320]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon is not working on any specs on any of my max level toons

### How to Reproduce

1. log into any character in current game 10.2.7

### Player Information (Link)

nothing posting in reporting section

### Error Messages (Link)

https://pastebin.com/raw/vAACcL4Q

### Additional Information

dont have anything showing up in the reporting panel and not letting me snapshot anything manually. other than that, its not working on any specs on any of my max level toons

**Comment by SpatenLa** [comment]
you didnt write the hekili version anywhere

**Comment by v2davee** [comment]
also got this at a vendor

Message: bad argument #1 to '?' (Usage: local result = C_Item.IsEquippedItem(itemInfo))
Time: Sat Jul  6 11:06:32 2024
Count: 1
Stack: bad argument #1 to '?' (Usage: local result = C_Item.IsEquippedItem(itemInfo))
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `IsEquippedItem'
[string "@Interface/AddOns/Hekili/Events.lua"]:717: in function `updateGear'
[string "@Interface/AddOns/Hekili/Events.lua"]:683: in function <Interface/AddOns/Hekili/Events.lua:682>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by v2davee** [comment]
> you didnt write the hekili version anywhere

latest version on curseforge, i have reinstalled it a few times and hasnt worked.

**Comment by SpatenLa** [comment]
there is no version with the number "latest"

**Comment by v2davee** [comment]
> there is no version with the number "latest"
v10.2.5-1.0.5

**Comment by SpatenLa** [comment]
the "latest" version of hekili is
v10.2.7-1.0.3 (2024-05-20)

**Comment by v2davee** [comment]
ok so i see that now, when i click that file and go to install it, it only shows the retail beta on the 'select game instance' drop down.
do i have to download it and drag into addon folder?

**Comment by v2davee** [comment]
was able to download the most recent version from the addon site and manually put it in the addon folder and this seems to be working now. not entirely sure why curseforge only has 10.2.5 version and 10.2.7 in only the retail beta version of the game
