### ISSUE TITLE
[FEATURE] The Hekill skill, when attempting to increase Spell_Power, returns a nil value instead of the corresponding value as intended

### ISSUE THREAD

**Issue by Urban1023** [Hekili/hekili#3321]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

The Hekill skill, when attempting to increase Spell_Power, returns a nil value instead of the corresponding value as intended. The same Lua code functions properly in WA. The game is running on the WLK version, and the Hekill code does indeed contain the instructions to assign Spell_Power

**Comment by Hekili** [comment]
Sorry, this ticket does not include the required information to investigate.
