### ISSUE TITLE
[REC] Vengeance DH: never recommends Demon Spikes

### ISSUE THREAD

**Issue by Akr0n** [Hekili/hekili#3323]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Vengeance DH, I expect that the addon recommends Demon Spikes early after starting the rotation/encounter. This never happens

### How to Reproduce

1 - Enter the game as a tank DH
2 - go to the dummy using the default priority list and checking the defensive option from the drop down menu
3 - the addon does not recommends Demon Spikes in any occasion

### Snapshot (Link)

https://pastebin.com/dTGDjUxB

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2wBhy72RfKLMVqHAk9av3T

### Contact Information

Akr0n (Discord)

**Comment by Hekili** [comment]
You're fighting test dummies that don't aggro you.  You need incoming damage / threat for this to be recommended.
