### ISSUE TITLE
Shaman Elemental - Stuck on totemic recall 

### ISSUE THREAD

**Issue by rikdol** [Hekili/hekili#3325]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Tested after reloading priority from defaults.

**Stuck on Totemic Recall**
Elemental (auto) - stuck on Totemic Recall : https://pastebin.com/2msP7BiH
                 (Single) - stuck on Totemic Recall: https://pastebin.com/Jh8b2RaL
It seems to register cooldown.liquid_magma_totem.remains as 54s ( while it's not on cooldown )
![image](https://github.com/user-attachments/assets/8b64a993-7535-48a9-b00d-5eba1c69ffe7)

Seemed Stuck on SingleTarget#3 and changed this to: 
(cooldown.liquid_magma_totem.remains > 45 & cooldown.liquid_magma_totem.remains < 54)&( talent.lava_surge.enabled & talent.splintered_elements.enabled | active_enemies > 1 & ( spell_targets.chain_lightning > 1 | spell_targets.lava_beam > 1 ) )

### How to Reproduce

The screenshot and snapshot should show that totemix recall should not be true in that logic. But for completionists sake :)

Entering game as shaman
Totemic recall is recommended ( if totemic recall is not on cooldown )

### Snapshot (Link)

https://pastebin.com/2msP7BiH

### Contact Information

Rik#9999

**Comment by Hekili** [comment]
You have Cooldowns toggled off, which makes affected abilities (like LMT) appear to be on cooldown. You probably want to put Totemic Recall on the Cooldown toggle so it won't be recommended when LMT isn't actually on cooldown.
