### ISSUE TITLE
Severe lagg and stuttering when used as fire mage

### ISSUE THREAD

**Issue by Mura1108** [Hekili/hekili#333]
Hello,

I seem to be running in an issue on the fire mage, when I use Hekili as frost or arcane there are 0 issues. As soon as I swap to fire and enter combat, Hekili jumps up in memery usage and tanks my fps to sub 40, whereas on other classes and specs like Shaman, warrior, warlock there are no issues at all.

**Comment by Hekili** [comment]
Submit a complete ticket per the instructions.
