### ISSUE TITLE
Recommends spells that are on cooldown

### ISSUE THREAD

**Issue by robdra** [Hekili/hekili#3331]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I play as a demonology Warlock and the recommendation is to use Grimoire: Felguard all the time, even when its on cooldown.
I found a similar ticket but the answer to that one was that is was the cooldown display. That does not seem to be the answer here
![Skärmbild 2024-07-18 155617](https://github.com/user-attachments/assets/a35ac500-35c3-4a46-b97a-a5a6fc183da1)

### How to Reproduce

1. Play as demonology Warlock.
2. Use these talents BoQAAAAAAAAAAAAAAAAAAAAAAgcASSkkAppQSaHIJh0CAAAAAQgIJpFRkkIpkWSkQAAAAAAQkA
3. Play according to the recommendations.
4. If Grimoire: Felguard isnt recommended again while fighting one enemy, kill them and go to the next enemy while spell is still on cooldown

### Snapshot (Link)

https://pastebin.com/zDxvmPgy

**Comment by Hekili** [comment]
That is not Grimoire Felguard. That is your Felguard pet.

They'll have different icons next week.
