### ISSUE TITLE
Hekili fails to show

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#3334]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I just loaded into game and told it to NOT disable old addons and it doesn't show hekili anywhere

### How to Reproduce

log into character

### Player Information (Link)

can't do this, nothing happens

### Error Messages (Link)

none possible to show

**Comment by syrifgit** [comment]
Wait for the addon to be updated, prepatch just dropped.

**Comment by Hekili** [comment]
I will eat your entire family.

**Comment by Willim0921** [comment]
I am having the same issue, I will watch out for an update! Thanks for the great addon!

**Comment by fuddlesworth** [comment]
This happens on my shadow priest. It shows no specs or profiles available from. It's working on my other characters though.

**Comment by syrifgit** [comment]
> This happens on my shadow priest. It shows no specs or profiles available from. It's working on my other characters though.

Shadow priest is not finished yet

**Comment by Kajinos** [comment]
Good to hear!  Hope its finished soon for shadow,  thanks for the update!
