### ISSUE TITLE
[BUG] LibDataBroker is Missing

### ISSUE THREAD

**Issue by nancikennedy** [Hekili/hekili#3335]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On entering game/reloading, a lua error is generated and hekili is not visible in the UI.

### How to Reproduce

Enable Hekili
Log in, or reload

### Player Information (Link)

No Snapshots

### Error Messages (Link)

See Addl Info, for single line lua error

### Additional Information

2x Hekili/embeds.xml:21 Error loading Hekili/Libs/LibDataBroker-1.1-4/LibDataBroker-1.1.lua

**Comment by nancikennedy** [comment]
I dropped a copy of LibDataBroker 1.1 in the libs folder. This fixed the LUA error, but Hekili is still not showing (both in/out OC)

**Comment by Zanetsuken** [comment]
Have you updated the addon to the latest version that came out about an hour ago.

**Comment by whi-tw** [comment]
Same issue. On `v11.0.0-0.9.0`

**Comment by nancikennedy** [comment]
> Have you updated the addon to the latest version that came out about an hour ago.

Yeah, I'm on v11.0.0-0.9.0. Sorry about forgetting to include the version

**Comment by Zanetsuken** [comment]
If you grabbed the files from Github, its likely you grabbed the unpackaged source instead of the actual release.
I would reinstall the addon from Curse directly or ensure you grab the packaged version from github.

**Comment by nancikennedy** [comment]
> If you grabbed the files from Github, its likely you grabbed the unpackaged source instead of the actual release. I would reinstall the addon from Curse directly or ensure you grab the packaged version from github.

I installed from Curse. :)

**Comment by nancikennedy** [comment]
I looked at the diff between the two latest versions, and it lists LDB (both 1.0 and 1.1) as being deleted. https://github.com/Hekili/hekili/compare/v10.2.7-1.0.4...v11.0.0-0.9.0

**Comment by ghost** [comment]
I have the same issue. lua error, and hekili not showing. 

Installed from curse. Got the error, deleted old version, along with saved variables. Reinstalled. Same issue. 

Interface/AddOns/Hekili/embeds.xml:21 Error loading Interface/AddOns/Hekili/Libs/LibDataBroker-1.1-4/LibDataBroker-1.1.lua
Time: Wed Jul 24 11:39:18 2024

**Comment by ChrisKader** [comment]
> I looked at the diff between the two latest versions, and it lists LDB (both 1.0 and 1.1) as being deleted. [v10.2.7-1.0.4...v11.0.0-0.9.0](https://github.com/Hekili/hekili/compare/v10.2.7-1.0.4...v11.0.0-0.9.0)

Yea, looks like the static version of LDB that Hekili used was removed and the .pkgmeta file was not updated to pull from a repo or embeds.xml was not updated to remove LDB.

**Comment by ChrisKader** [comment]
I pulled the `Libs/LibDataBroker-1.1` folder from the `dragonflight` branch and copied it my local copy and the addon loads/works fine now.

**Comment by karpana** [comment]
> I pulled the `Libs/LibDataBroker-1.1` folder from the `dragonflight` branch and copied it my local copy and the addon loads/works fine now.

With the direction indicated in @ChrisKader's last coment, I went looking into the Hekili Libs folder and noticed that the LibDataBroker-1.1 was missing as well.  So I created the folder and fetched the LUA file from [here](https://github.com/Hekili/hekili/blob/dragonflight/Libs/LibDataBroker-1.1/LibDataBroker-1.1.lua).

This is the version I had installed a short while ago when I started to debug addons upon my first launch of the TWW Prepatch:  `v11.0.0-0.9.0`
![image](https://github.com/user-attachments/assets/b47443cd-58e7-4ed3-a29f-a2953e70c6f5)

**Comment by karpana** [comment]
the recently released v11.0.0-0.9.0a, which just made it to my curseforge client, seems to have fixed this up.
Thank you!!
