### ISSUE TITLE
[REC] DK rotation recommends Army of the Dead despite Raise Abomination being talented

### ISSUE THREAD

**Issue by fwosar** [Hekili/hekili#3336]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Unholy rotation recommends Army of the Dead even if Raise Abomination, which replaces Army, is talented. Since it will continue to recommend Army of the Dead even if Raise Abomination is on CD, it results in a situation where the ability simply gets stuck in the number 1 position.

### How to Reproduce

Just log onto a DK, talent Raise Abomination in the Unholy tree, enable CDs.

### Snapshot (Link)

https://pastebin.com/nBL0ny3k

**Comment by Zanetsuken** [comment]
In the interim as a band aid try disabling army of the dead in hekili - the prio will hopefully then move on.

**Comment by fwosar** [comment]
Yeah, it's what I did for now. It's probably just a matter of updating the class state machine to understand that Raise Abomination replaces Army of the Dead.

**Comment by marekCs** [comment]
So guys if I disable Army spell it will recommend me also the Raise Abomination or you put it to spell rotation manually?

**Comment by Hekili** [comment]
Should be fixed in 0.9.0c.
