### ISSUE TITLE
[BUG] Blood DK appears to be recommending frost abilities (and doesn't work)

### ISSUE THREAD

**Issue by whi-tw** [Hekili/hekili#3337]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

BDK should be recommending Blood abilities, but appears to be using a Frost APL, so fails.

### How to Reproduce

1. Enter game as a BDK
2. attack a mob
3. Observe error occurs

### Snapshot (Link)

https://pastebin.com/zD9ZXr7Z

**Comment by Zanetsuken** [comment]
Someone noted that relaunching the game fixed a similar issue on hunter.

**Comment by whi-tw** [comment]
> Someone noted that relaunching the game fixed a similar issue on hunter.

Alas, not in this case!

**Comment by mcart13** [comment]
Mine is similar but seems to just run out of suggestions after 3-5 abilities

**Comment by hyprpixel** [comment]
only recommending like 2-3 abilities for blood.

**Comment by Reunion2792** [comment]
Same issue here, only getting 3 recommended abilities, anti-magic shell, raise dead and abominations limb

**Comment by whi-tw** [comment]
Just checked the APL - it's definitely the Frost one. @Hekili

**Comment by Hekili** [comment]
It is. But that's what's checked into simc right now. I'm watching for a correction/update.

**Comment by whi-tw** [comment]
Ah amazing, thank you for confirming. I'll simc my own APL up for now!

**Comment by mcart13** [comment]
Apologies for my ignorance, is there an article on how to upload your own
APL from simc?

**Comment by whi-tw** [comment]
In theory you could copy the bdk simc file from dragonflight over the tww one. I'm not in front of a computer rn

**Comment by mcart13** [comment]
Just uploaded a patchwerk profile from the "Nightly" build on simc and can confirm it fixed

**Comment by Hekili** [comment]
This will be fixed in 0.9.0c.
