### ISSUE TITLE
[REC] Addon does not track when Agony applied.

### ISSUE THREAD

**Issue by Zanetsuken** [Hekili/hekili#3338]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Appreciate the addon is using DF list as the APL is not yet updated but the addon does not track when Agony is applied to the target leaving it as the priority suggestion. 

### How to Reproduce

Select target
begin opener
once agony is applied it remains at the head of the prio queue

### Snapshot (Link)

https://pastebin.com/thMUGULd

### Additional Information

I feel like this is not going to be related to APL issue.

**Comment by Timb0909** [comment]
Hey :-)
this issue was gone since agony was shown again on my plater.
 I used:
 /run C_CVar.SetCVar('loadDeprecationFallbacks', 0) ReloadUI()
this helps with plater / details issues. But i have to use it every time I logged in again.. 
I got also issues with all shard spenders like malefic rapture, chaosbold,… they don’t show up :-(

**Comment by Zanetsuken** [comment]
> Hey :-) this issue was gone since agony was shown again on my plater. I used: /run C_CVar.SetCVar('loadDeprecationFallbacks', 0) ReloadUI() this helps with plater / details issues. But i have to use it every time I logged in again.. I got also issues with all shard spenders like malefic rapture, chaosbold,… they don’t show up :-(

I wasn't using plater during this test (albeit i do have it installed)

**Comment by Hekili** [comment]
Should be fixed in 0.9.0b.
