### ISSUE TITLE
[BUG] Elemental Shaman not recommending earthquake with new talent selected

### ISSUE THREAD

**Issue by RenSai93** [Hekili/hekili#3339]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

With the new earthquake talent there is no recomendation to use it on AOE. Swapping back to the ground target version it works fine. Appears to be an issue with the earthquake_2 saying earthquake is then missing. 

### How to Reproduce

1. Have the new earthquake talent that targets the mob. 
2. Have the buff from Echos of Great Sundering
3. Will still only want you to use Elemental Blast

### Player Information (Link)

https://pastebin.com/uw0Z11Gb for wrong one and https://pastebin.com/r6k3N5qS for the ground talent

### Error Messages (Link)

none

**Comment by Hekili** [comment]
Will be fixed in 0.9.0c.
