### ISSUE TITLE
[REC] Not detecting buffs on pets (BM, Frenzy, beast cleave)

### ISSUE THREAD

**Issue by Williamn88** [Hekili/hekili#3341]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

EDIT: I see someone else JUST posted the same issue. So sorry about the duplicate, you can close or whatever you want if thats better.

Hi Hekili

It seems to not detect buffs on pets atm. I checked the ID and it should be correct for what it looks for in your code, so its deeper then what I can spot. Maybe something in your FindUnitBuffByID func ?

 if I do a multi shot to trigger beast cleave it just keeps on suggesting multishot. If I look at the recommendations it says buff.beast_cleave.remains 0 all the time. Snap shot below is taken just after firing a multishot and beast cleave is up in game.
 
 after just firing off the multishot
![image](https://github.com/user-attachments/assets/85232037-eb91-45ab-9b0b-8342b3629942)

In the same vein it also does not detect the frenzy buff on the pet.
In this screenshot I just fired off a barbed shot and the buff is running on the pet in game.
![image](https://github.com/user-attachments/assets/85d4bfc0-f730-44eb-b952-df67ccc3551f)

### How to Reproduce

Be BM
Do AoE and fire off a multishot when it recommended.
See it keeps on suggesting multi shot.

Be BM
Fire off barb shot to trigger frenzy
Look and see if there is any value besides 0 in the duration of frenzy its keeping track off and it still says frenzy up is false

### Snapshot (Link)

https://pastebin.com/7TKCcSex

**Comment by Hekili** [comment]
> Maybe something in your FindUnitBuffByID func ?

Correct.  Working on it.

**Comment by Hekili** [comment]
Fix will be in 0.9.0b.
