### ISSUE TITLE
[REC] Fury execute issue

### ISSUE THREAD

**Issue by Shamuraj** [Hekili/hekili#3342]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Fury Execute doesnt disappear form queue eventhough its on a 3 sec cd

### How to Reproduce

I start dummy session and when it gets to execute phase after using execute the execute is still top prio in queue although its currenlty on cd.

### Snapshot (Link)

https://pastebin.com/v5fywMbe

**Comment by ThatRickGuy** [comment]
I was just coming to report the same. Started beating on a training dummy with low health and Execute stays at #1 even while on cooldown.

**Comment by Wyste** [comment]
I'll look at this today after a few IRL work calls I have going on... Unless Hekili gets to it himself.

**Comment by Hekili** [comment]
Should be fixed in 0.9.0b.
