### ISSUE TITLE
[BUG]  Libs issues  fresh install + wipe of WTF

### ISSUE THREAD

**Issue by Fisshy86** [Hekili/hekili#3343]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Starting the game, I get 2 errors about Libs:

```
Message: ...e/AddOns/Hekili/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:12: LibDBIcon-1.0 requires LibDataBroker-1.1.
Time: Wed Jul 24 13:19:51 2024
Count: 1
Stack: ...e/AddOns/Hekili/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:12: LibDBIcon-1.0 requires LibDataBroker-1.1.

Locals
```
and
```
Message: Interface/AddOns/Hekili/embeds.xml:21 Error loading Interface/AddOns/Hekili/Libs/LibDataBroker-1.1/LibDataBroker-1.1.lua
Time: Wed Jul 24 13:19:58 2024
Count: 2
```

Checking my folder, I don't have the LibDataBroker, so I decided to comment out / remove the lines in embeds.xml: 
```
<Script file="Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua"/>
<Script file="Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"/>
```
(LibDBIcon was requiring LibDataBroker)
and then it seemed to work as expected. 

Not sure if this is due to a first install or any other reason

### How to Reproduce

Delete addons and WTF folders,  installed Hekili,   Ran game and got errors

### Player Information (Link)

shouldn't be needed, happened to all classes i tried

### Error Messages (Link)

https://i.imgur.com/3uTrms7.png    

### Additional Information

pastebin to my Libs folder fresh install: https://i.imgur.com/UvxScVV.png

**Comment by Hekili** [comment]
Will be fixed.
