### ISSUE TITLE
[BUG] Bug on demonolog

### ISSUE THREAD

**Issue by dovbobob** [Hekili/hekili#3344]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When I enter the game, the addon does not work at all. Included only 2 addons, bug grabber and hekili. Constantly spams these errors. The addon cannot be opened. Today I installed the latest version. Changing specialization doesn't help

### How to Reproduce

Enter game

### Player Information (Link)

cant open addon

### Error Messages (Link)

https://pastebin.com/B0kfmakA

### Additional Information

https://pastebin.com/vDxTnnrF
another error

### Contact Information

Discord 
cep_bib

_No response_

**Comment by Zanetsuken** [comment]
How did you install the addon? From Curse or Github?

**Comment by dovbobob** [comment]
Curse

**Comment by dovbobob** [comment]
<img width="713" alt="Знімок екрана 2024-07-24 160644" src="https://github.com/user-attachments/assets/b26a6b91-6f73-4f8a-ad50-5bd94f66cf97">

**Comment by dovbobob** [comment]
It helped to completely remove all addons and clean out the wtf folder (sadface)
