### ISSUE TITLE
[REC] Astral Power resource does not line up with the recommendation for using Starsurge

### ISSUE THREAD

**Issue by Yowkii** [Hekili/hekili#3347]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I just installed the latest patch that was released 7/24/2024 (v11).
I checked the changelog also and it said "Druid (except Resto) priorities are loaded".

I started testing on a training dummy, but when i came to Starsurge, it wanted me to use it another 2-3 times even though i was starved for astral power. I thought it might've been the latest set-piece, so i tested without it. No difference.
I've done a lot of testing, but it always ends with the same result in the priority.

### How to Reproduce

1. start the rotation on a training dummy 2. Wait and cast Starsurge 3. problem will appear and you cannot cast Star surge due to the lack of astral power.

### Snapshot (Link)

https://pastebin.com/3FiMWMvQ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iD6MLrLk7pQhxccS59UyrV

### Contact Information

DiscordID: yowki

**Comment by Hekili** [comment]
Fix incoming in 0.9.0b.
