### ISSUE TITLE
[BUG] `mt_alias_debuff` in `State.lua` should not be a global.

### ISSUE THREAD

**Issue by ChrisKader** [Hekili/hekili#3349]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

[Line 4780 in State.lua](https://github.com/Hekili/hekili/blob/thewarwithin/State.lua#L4780) creates creates `mt_alias_debuff` as a global variable instead of a local one.

### How to Reproduce

Load Hekili in-game and run `/dump _G.mt_alias_debuff` to see that it is global.

### Player Information (Link)

n/a

### Error Messages (Link)

N/A

**Comment by Hekili** [comment]
Thanks, will fix.
