### ISSUE TITLE
[BUG] Assa Rogue profile wont load

### ISSUE THREAD

**Issue by steingoblin** [Hekili/hekili#3350]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Assa Rogue profile wont load

### How to Reproduce

Login Wont load

### Player Information (Link)

no te

### Error Messages (Link)

none

**Comment by Zanetsuken** [comment]
The addon tells you rogue is not yet updated and to wait for updates.
The following specs are currently supported in the initial The War Within release of the addon:

Blood, Frost, Unholy DK
Havoc, Vengeance DH
Balance, Feral, Guardian Druid
Augmentation, Devastation Evoker
Beast Mastery, Marksmanship, Survival Hunter
Protection, Retribution Paladin
Elemental, Enhancement Shaman
Arms, Fury, Protection Warrior
Affliction, Demonology, Destruction Warlock (currently using DF priorities)

If you see problems with any of the above specializations, submit a ticket on GitHub (https://github.com/Hekili/hekili/issues).  If they aren't listed above, they aren't done -- don't put in a ticket.

The remaining specs will be added with DPS > Tanks > Healers, likely Monk > Rogue > Priest > Mage.  There will be a lot of updates throughout the week as sims are updated and new priorities come out.  Please be patient. (edited)

**Comment by steingoblin** [comment]
i see thx Any rogue time when rogue will be done ?
