### ISSUE TITLE
 Vengeance DH spamming Throw Glaive

### ISSUE THREAD

**Issue by Akr01337** [Hekili/hekili#3351]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello,
This issue looks similar to #2283

When tanking as a Vengeance DH, the addon seems to suggest way too many Throw Glaives when other spells are up

### How to Reproduce

Just follow the rotation in a dungeon and it does these odd recommendations.

### Snapshot (Link)

https://pastebin.com/ueHGffjz

### Additional Information

This did not happen with the previous version (v10.2.7-1.0.4).

### Contact Information

akro8415

**Comment by Hekili** [comment]
Fix incoming in 0.9.0b.
