### ISSUE TITLE
[REC] Missing priorities for rogue, using any spec

### ISSUE THREAD

**Issue by Akr0n** [Hekili/hekili#3352]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a rogue, no matter what spec I am using, there isn't a priority to use or follow. Checking in the source code, under the folder [TheWarWithin](https://github.com/Hekili/hekili/tree/thewarwithin/TheWarWithin) rogue's priorities are not there.

### How to Reproduce

1 - Enter the game as a rogue
2 - Addon doesn't show the priority

### Snapshot (Link)

Can't do it, even if I press the keybind

### Contact Information

Akr0n (Discord)

**Comment by Zanetsuken** [comment]
The addon tells you that rogue is not yet supported and to watch for updates.

The following specs are currently supported in the initial The War Within release of the addon:

Blood, Frost, Unholy DK
Havoc, Vengeance DH
Balance, Feral, Guardian Druid
Augmentation, Devastation Evoker
Beast Mastery, Marksmanship, Survival Hunter
Protection, Retribution Paladin
Elemental, Enhancement Shaman
Arms, Fury, Protection Warrior
Affliction, Demonology, Destruction Warlock (currently using DF priorities)
