### ISSUE TITLE
[BUG] Elemental Shaman doesn't recommend icefury

### ISSUE THREAD

**Issue by RenSai93** [Hekili/hekili#3353]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Icefury is never recommended. Looking at the snapshots it appears to be looking for a buff. In game it doesn't look like you get a buff it just replaces the Frost Shock button on your bar with Icefury and nothing in the buff bar. 

### How to Reproduce

1. Get an icefury proc 
2. Never will recommend to spend that proc over using chain lightning/lightning bolt etc

### Player Information (Link)

https://pastebin.com/hQK92chB

### Error Messages (Link)

none

**Comment by Hekili** [comment]
Fix incoming.
