### ISSUE TITLE
[REC] Mage not showing Hekili

### ISSUE THREAD

**Issue by PandaTechnologyMT** [Hekili/hekili#3354]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili is not showing up on Mage and getting the message "Mage does not have a module loaded"

### How to Reproduce

Hekili on mage

### Snapshot (Link)

N/A

### Contact Information

nation_of_pandas

**Comment by Zanetsuken** [comment]
Mage is not yet supported.
The following specs are currently supported in the initial The War Within release of the addon:

Blood, Frost, Unholy DK
Havoc, Vengeance DH
Balance, Feral, Guardian Druid
Augmentation, Devastation Evoker
Beast Mastery, Marksmanship, Survival Hunter
Protection, Retribution Paladin
Elemental, Enhancement Shaman
Arms, Fury, Protection Warrior
Affliction, Demonology, Destruction Warlock (currently using DF priorities)

If you see problems with any of the above specializations, submit a ticket on GitHub (https://github.com/Hekili/hekili/issues).  If they aren't listed above, they aren't done -- don't put in a ticket.

The remaining specs will be added with DPS > Tanks > Healers, likely Monk > Rogue > Priest > Mage.  There will be a lot of updates throughout the week as sims are updated and new priorities come out.  Please be patient.

**Comment by Keanuweedz** [comment]
be a lot cooler if you fixed the rogues

**Comment by burntorangejedi** [comment]
Can we load the old spec for Remix? How does that work?
