### ISSUE TITLE
[REC] Ele Shaman: Magma Totem is showed again after Totemic Recall while Magma Totem is still active and targets are dotted with Flame Shock

### ISSUE THREAD

**Issue by SpartanEsp** [Hekili/hekili#3355]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Magma Totem is showed again after Totemic Recall while Magma Totem is still active and targets are dotted with Flame Shock.

This is a big loss of dps because you spend two 1min CDs at the same time and it is totally unnecessary because the enemies already have Flame Shock applied and you will have 0 Magma totems on the next pull.

Magma Totem should be recommended only if there are 3 or more targets without Flame Shock and Totemic Recall only if the Magma Totem CD it's too long for the fight

### How to Reproduce

1. Enter the game with Elemental Shaman
2. Pick Totemic Recall and Magma Totem talents
3. Go to training dummy (AoE)
4. Start the fight
5. Spend the first Magma Totem, the next recommendation will be Totemic Recall and right after that again Magma totem wasting all you CDs in 5 secs.

### Snapshot (Link)

https://pastebin.com/XwfEw6N4

**Comment by syrifgit** [comment]
That is a correct rotation according to sims and the Elemental class discord.

**Comment by RenSai93** [comment]
That just comes from the APL. If you run an AOE sim that is what they recommend as well per that sim/class discords. You just want to keep your CDs going.

**Comment by Hekili** [comment]
I'm tweaking the sim priority for testing purposes a bit.
