### ISSUE TITLE
[REC] Unholy DK: Outbreak is recommended on AoE infinitely

### ISSUE THREAD

**Issue by SpartanEsp** [Hekili/hekili#3356]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Outbreak is recommended on AoE infinitely a few seconds after starting the fight.

### How to Reproduce

1. Enter the game with a DK
2. Select Unholy spec
3. Start the combat on the AoE Training Dummies
4. Follow Hekili until Outbreak appears
5. Keep using Outbreak

### Snapshot (Link)

https://pastebin.com/ZDhwNgLa

**Comment by Hekili** [comment]
Potential fix in 0.9.0c.

**Comment by Hekili** [comment]
That's not the latest version.
