### ISSUE TITLE
[BUG] Does not display anything for either Rogue specc

### ISSUE THREAD

**Issue by Citruz-del** [Hekili/hekili#3357]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon itself loads and you can enter the settings but it does not show any rotation for rogues, tried on my ret, war and more and it works and so far it's only on the rogue it does not show anything

### How to Reproduce

Tried signing on to other chars and it works but not on rogue. I have aslo changed to all drifferent rogue specs and even my different max lvl rogues. 

### Player Information (Link)

can't 

### Error Messages (Link)

Don't get any error

### Additional Information

not able to get any info from reproting section in the addon

### Contact Information

hedm (disc)

**Comment by syrifgit** [comment]
Rogue specs have not been completed yet.

![image](https://github.com/user-attachments/assets/95222a4c-c5c8-432b-ba51-f77084ad0894)
