### ISSUE TITLE
[REC] Retribution Paladin recommends passive abilities (Radiant Glory) and untalented abilities (Crusade)

### ISSUE THREAD

**Issue by Gnarfoz** [Hekili/hekili#3358]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon recommends Radiant Glory (passive ability) and Crusade (not talented).

### How to Reproduce

Log in after TWW prepatch with the default loadout, fight something, after a couple of abilities, 1st recommendation becomes Radiant Glory (passive) and 2nd recommendation becomes Crusade (not talented, Avenging Wrath: Might is picked on that node).

### Snapshot (Link)

https://pastebin.com/07BkggyA

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6zcFw7jWzKS84Wmni4QjT1

### Contact Information

gnarfoz#8452

**Comment by Hekili** [comment]
Fixed in 0.9.0c.
