### ISSUE TITLE
Disappearing priority window

### ISSUE THREAD

**Issue by casualtry** [Hekili/hekili#336]
[Hekili report 4-21.docx](https://github.com/Hekili/hekili/files/4512787/Hekili.report.4-21.docx)
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Hey, I see the document but could you please follow the snapshot instructions? After posting the snapshot, you can safely downgrade until the behavior stops.

**Comment by casualtry** [comment]
Having an issue with that, it saves the snapshot, but then i cannot paste it

**Comment by casualtry** [comment]
Ok found the issue, something with my keyboard my bad here is this and I
posted it in discord as well

**Comment by Hekili** [comment]
I'm going to close this, as I believe it's resolved as of -beta6 and I plan to post a release.  If you're still experiencing this with any particular spec, please reach out and reopen or submit a new ticket.
