### ISSUE TITLE
[BUG] Monk Windwalker haven`t any abilities for recommendation.

### ISSUE THREAD

**Issue by BloodyFess** [Hekili/hekili#3360]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon not loaded any modules for my monk windwalker. Menu "Specialization" in settings is empty at all. Any abilities absent. I got message something like: "Not any modules for windwalker loaded yet..." after first login when update addon. Was trying completely reinstall addon. No luck.

### How to Reproduce

Enter game as Windwalker monk

### Player Information (Link)

No snapshots have been generated

### Error Messages (Link)

Not any error message

**Comment by syrifgit** [comment]
Monk specs have not been completed yet.

![image](https://github.com/user-attachments/assets/95222a4c-c5c8-432b-ba51-f77084ad0894)
