### ISSUE TITLE
[REC] Augmentation Evoker Breath of Eons not replacing Deep Breath

### ISSUE THREAD

**Issue by Korandia** [Hekili/hekili#3361]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On my augmentation evoker, having Breath of Eons talented (middle of row 4 on aug tree) replaces Deep Breath. In the addon, the icon still shows as Deep Breath and is not replaced. When I use Breath of Eons, the Deep Breath icon still remains in the priority list. 

### How to Reproduce

1. Enter game as an Augmentation Evoker
2. Take Breath of Eons talent in row 4 of the Aug tree
3. Start rotation on training dummies

### Snapshot (Link)

https://pastebin.com/XfgvSMk9

### Contact Information

Discord: Suri#0794

**Comment by syrifgit** [comment]
Can you take a snapshot while it's actually showing deep breath?

**Comment by MatteoLombardi** [comment]
Confirm, I had to set deep breath as disabled, but that caused another issue: ebon might and breath of the eons never got suggested for the whole key, had to force it 

Edit, loggin in my aug to take a snapshot, 1 sec

**Comment by syrifgit** [comment]
Your cooldowns were probably turned off. But again, will need the appropriate snapshot.

**Comment by MatteoLombardi** [comment]
https://pastebin.com/9GZeTrxv, cooldown are on, played aug a lot last season and this season, never had issues

**Comment by Hekili** [comment]
Will be fixed in next release (0.9.0c).
