### ISSUE TITLE
[BUG]? - Mage not available? Please wait?

### ISSUE THREAD

**Issue by Diagro** [Hekili/hekili#3362]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili reports that there are no Mage profiles available (yet). 

Is this the case? Or is mine bugged?

### How to Reproduce

1. ENter game as an Arcane mage 
2. ENable Hekili

### Player Information (Link)

z

### Error Messages (Link)

x

**Comment by syrifgit** [comment]
Mage is not finished yet.
