### ISSUE TITLE
[BUG] addon will not load or display

### ISSUE THREAD

**Issue by kayd311** [Hekili/hekili#3363]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

addon will not show anything every toon says "no module loaded yet. watch for update"

### How to Reproduce

just log in

### Player Information (Link)

says no snapshot which makes sense because the addon isnt giving me recommendations at all

### Error Messages (Link)

no messages just saying no modules for any toon i log into

**Comment by syrifgit** [comment]
You are likely playing a class/spec that is not ready. As the addon says, watch for updates.

**Comment by kayd311** [comment]
well i mean i have 70 of every class and they all say the same. so are there no modules at all loaded yet?

**Comment by syrifgit** [comment]
> well i mean i have 70 of every class and they all say the same. so are there no modules at all loaded yet?

Have you updated to the newest version?

**Comment by kayd311** [comment]
yes i have. i even deleted the addon and reinstalled it
