### ISSUE TITLE
[BUG] Priest priorities not loading, nothing available in options menu.

### ISSUE THREAD

**Issue by tragicshot** [Hekili/hekili#3364]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Priest priorities are not available

### How to Reproduce

Be a priest.  No priorities load, nothing in the options to choose from.  I do not see any priest priorities.

### Player Information (Link)

n/a

### Error Messages (Link)

n/a

### Additional Information

Unsure if missing priorities that are still being added or if this was missed or broken.  I do not see anything specific pertaining to absolute missing priorities.  Apologies if this is already being addressed.

**Comment by tragicshot** [comment]
Apparently the title did not stick this is a priest issue for priorities not loading.  Everything was filled out (also first time user here.)

**Comment by syrifgit** [comment]
Priest is not ready yet. Keep an eye out for updates!
