### ISSUE TITLE
[BUG] Hekili no longer working with Spellflash

### ISSUE THREAD

**Issue by Selevan90** [Hekili/hekili#3365]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Although the addon is up to date and apparently supports devastation or augmentation with spell flash enabled in the settings it no longer highlights the spell recommended to use.

### How to Reproduce

1.Login to any supported class for the latest update of hekili
2.Have spellflash addon installed with the core addon both being enabled
3.have the settings for spell flash to be enabled in the main settings for all encounter types (single target or AOE)
4.engage in combat to see no spells highlighted on the action bar

### Player Information (Link)

https://pastebin.com/em5vwVUL

### Error Messages (Link)

N/A

### Contact Information

Sthelens101#8610 (Sthelens101))

**Comment by Hekili** [comment]
![image](https://github.com/user-attachments/assets/ff496e11-72bf-44f0-bddb-3e6109444a8b)
![image](https://github.com/user-attachments/assets/a361c286-cc9d-4195-a0c0-9ddaaf8cd2f0)
![image](https://github.com/user-attachments/assets/bb2a1e75-d467-4337-ac0f-b4519b4ef6cd)

Seems okay to me?  Are you sure it's not those specs specifically?

**Comment by Selevan90** [comment]
i have tried it on aug,dev,arcane mage and unholy dk and it shows for none of them, it was working prior with no settings change but now it wont highlight for some reason

![image](https://github.com/user-attachments/assets/2a6f601a-725d-4b4f-a3af-fda151fd4213)

**Comment by Paul2or3** [comment]
Spellflash works just fine for regular spells, but has stopped working for macros.  Are your spells possibly macro'd?  I had similar problem, but once I replace the macros with just plain spells, all works.

**Comment by Selevan90** [comment]
No macros for me no, it’s just standard spells on the action bar, I’ve enabled the viewing of the spells as normal on hekili and I can see the recommended spells fine listed but the spell flash intergration just isn’t flashing for me and I’m unsure why. As mentioned though nothing had been changed since the pre patch to break it

**Comment by wilsonm2424** [comment]
![Screenshot 2024-07-25 000957](https://github.com/user-attachments/assets/085bccd5-eaff-4631-aebf-b465a94a0fc7)
Having the same issue.

**Comment by jdm12983** [comment]
> Spellflash works just fine for regular spells, but has stopped working for macros. Are your spells possibly macro'd? I had similar problem, but once I replace the macros with just plain spells, all works.

Yeah, I had originally opened an issue with Spell Flash not working on macros in action bars. They author of this mod and posted a fixed file I used for a while -- then updated the addon lib itself to have the fix sometime around December of last year. But, sometime this year the "fix" was removed from the file - so it's back to not flashing on macros again.

I have the original fix file they provided; but, I don't know enough about the coding of these addons to try and add it back in myself.

**Comment by Simul4kruM** [comment]
I had the same issue as I did not understand, you do not have to install spellflash, because hekili got it built-in...
Uninstalling spellflash did solve the problem...

**Comment by Hekili** [comment]
If there's a newer (and incompatible) version of SpellFlash somewhere, please provide a link.  I should be using their version and asking them to fix SpellFlash itself.

**Comment by Simul4kruM** [comment]
All good, there's just an older, not working with pre-patch. I did not realize that I do not have to install spellflash, that you built it in... 
good job ;)

**Comment by wilsonm2424** [comment]
> I had the same issue as I did not understand, you do not have to install spellflash, because hekili got it built-in... Uninstalling spellflash did solve the problem...

Oh!!  I didn't know that you no longer need spellflash to be installed separately.  I will uninstall and check it out, seems like that might be the conflict.

*edit - removing the spellflash add on did resolve this issue.*

**Comment by Paul2or3** [comment]
> If there's a newer (and incompatible) version of SpellFlash somewhere, please provide a link. I should be using their version and asking them to fix SpellFlash itself.

https://www.curseforge.com/wow/addons/spellflash

**Comment by urfavshadowpriest** [comment]
![where it is not](https://github.com/user-attachments/assets/d8c41e9a-3ce2-47f7-bd2f-c3c8eeef00bd)
well have u guys also seen any topics about hekili not displaying at all ?

**Comment by syrifgit** [comment]
> ![where it is not](https://private-user-images.githubusercontent.com/176608076/352243893-d8c41e9a-3ce2-47f7-bd2f-c3c8eeef00bd.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzE3MjQsIm5iZiI6MTcyMTkzMTQyNCwicGF0aCI6Ii8xNzY2MDgwNzYvMzUyMjQzODkzLWQ4YzQxZTlhLTNjZTItNDdmNy1iZDJmLWMzYzhlZWVmMDBiZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxODE3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmNhMzIxZmI0OGUzYmRkODllOTFlNmYwZjg1OWUwZGM2YjFkNTAwNDFlZjkyNmUyNjMwNDk4YzFkZTFmMDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zjC-GWdK_IbnR-pqqn8LuIpnOdTrX-nbGatRUDBkuXU) well have u guys also seen any topics about hekili not displaying at all ?

Yes, it is one of the pinned issues at the top. Shadow priest is one of the specs not ready yet: https://github.com/Hekili/hekili/issues/3380

**Comment by urfavshadowpriest** [comment]
Oh nice okay my bad I hadn’t checked that post thank you for the update !

**Comment by Selevan90** [comment]
can confirm disabling the addon works must have conflicted even though its the same thing :s but yeah disable both the spellflash and spellflash core now shows the flashing icons thanks for all your help guys

**Comment by jdm12983** [comment]
> If there's a newer (and incompatible) version of SpellFlash somewhere, please provide a link. I should be using their version and asking them to fix SpellFlash itself.

This was my original post where you fixed the macro issue -- if that's what you mean:
[https://github.com/Hekili/hekili/issues/2931](url)
