### ISSUE TITLE
[BUG] mana rogue These professions are not available priorities

### ISSUE THREAD

**Issue by waxz150** [Hekili/hekili#3366]
![33663](https://github.com/user-attachments/assets/41db3239-4e66-4d9f-910f-025de51f6717)
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

mana rogue shaman monk 
These professions are not available priorities

### How to Reproduce

mana rogue shaman monk 
These professions are not available priorities

### Player Information (Link)

8x Hekili/embeds.xml:11 Couldn't open Hekili/Libs/AceEvent-3.0-4/AceEvent-3.0.xml

### Error Messages (Link)

8x Hekili/embeds.xml:11 Couldn't open Hekili/Libs/AceEvent-3.0-4/AceEvent-3.0.xml

**Comment by Hekili** [comment]
You've installed incorrectly if you're missing libraries.

**Comment by waxz150** [comment]
Hello, I just randomly found a bug to fill in the report just to post it, but the fact is that these professions are not on the recommended list. Thank you for your reply。MANA Rogue 
![33663](https://github.com/user-attachments/assets/51fe5c22-30f6-4a7d-ba54-d5a01d94d129)

**Comment by waxz150** [comment]
I see that you are also busy updating, but I still haven't solved this problem by using a.b.c. Some professions have always been the same as in the picture, as far as I know, including pastors and mage and rogue。
I even specifically asked friends who haven't installed hekili to download it, but it doesn't display when they enter the game
