### ISSUE TITLE
Frame is not updating unless I click another unit.

### ISSUE THREAD

**Issue by Crelam** [Hekili/hekili#3367]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Running as enhancement, frame looks stuck on recommendations after I cast the recommended spell.  It tends to get unstuck if I change targets.  I think it has something to do with checking if I am in range for Primal Strike/Stormstrike.

I tried to get a snapshot however I got an error message.  I have included that error message in the linked Pastebin.

### How to Reproduce

Log in as enh, smack a mob, notice output.

### Player Information (Link)

Unavailable

### Error Messages (Link)

https://pastebin.com/WjT0yEFW

### Contact Information

crelam

**Comment by Crelam** [comment]
After doing more research, I've found that it only happens when Displays > Primary > Range > Enable & "Exclude Out-of-Range" is selected.  It works fine using "Per Ability" and "Melee Range".

**Comment by Hekili** [comment]
Think I have this fixed for next release.
