### ISSUE TITLE
Saying no priest modules are loaded 

### ISSUE THREAD

**Issue by Jatticx** [Hekili/hekili#3368]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

idk if anybody else is having this problem but everything seems to be up to date but when i enter combat its saying there are no priest modules loaded yet. 

### How to Reproduce

l

### Snapshot (Link)

l

### Raidbots Sim Report (Link)

l

### Additional Information

l

**Comment by atraxiarhae** [comment]
I too am having this issue. But was unable to send in a help thing cause snapshot isn't working either so thank you for this (:

**Comment by Hekili** [comment]
That's correct.  No priest modules loaded yet.
