### ISSUE TITLE
[BUG] Minimal Rotation Provided, Interface Disappears and Reappears with Cooldowns

### ISSUE THREAD

**Issue by girlcalledblu** [Hekili/hekili#3369]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Blood Elf, Blood DK.

Rotation recommendations will appear, but once exhausted through the first 3-4 spells/abilities, the interface disappears. After a short time, the interface reappears, but again, only shows the first 3-4 abilities before disappearing again. The rotation does not seem to fit the recommended Blood DK rotation. The abilities are:

* Abomb Limb
* Raise Dead
* Arcane Torrent (Blood Elf)
* Anti-Magic Shell

There are occasional flashes of Death and Decay, but it disappears immediately. I did also get recommended to cast Soul Reaper, but again, inconsistent.

### How to Reproduce

1. Enter game as Blood DK.
2. Engage a mob.
3. Click through the available abilities.
4. Wait until the cooldowns reset and the abilities reappear.

### Player Information (Link)

https://pastebin.com/t3hXFZcU

### Error Messages (Link)

https://pastebin.com/pLxUDQ1w

### Contact Information

thetrublu

**Comment by Hekili** [comment]
Fix is incoming in next release.

**Comment by girlcalledblu** [comment]
Thanks! :)
