### ISSUE TITLE
[BUG] Many LUA errors when running through Enhancement Shaman Recommendations

### ISSUE THREAD

**Issue by Necrochrist** [Hekili/hekili#3370]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Running through recommendations for Enhancement Shaman eventually produces a LUA error.

### How to Reproduce

1.  Enter game as enhancement shaman.
2. Face target dummy and target.
3. Start Hekili recommendations.

### Player Information (Link)

https://pastebin.com/ifMK22Ts

### Error Messages (Link)

https://pastebin.com/UxPxZAup

**Comment by Hekili** [comment]
That's not the latest version.

**Comment by Necrochrist** [comment]
Not if you're putting out a new version every 20 minutes LOL.  I just updated it before I started testing!  I downloaded the new update...will test again!
