### ISSUE TITLE
DEMO - Tyrant Being Recommended Too Early

### ISSUE THREAD

**Issue by Rynitaca** [Hekili/hekili#3372]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During the Demo opener, the Tyrant is being recommended immediately after Grimoire, dogs, and vilefiend are all active without trying to demonbolt / hand of gul'dan for maximum imps being extended.

### How to Reproduce

1. Enter game as a Demo Warlock
2. Perform the opener rotation as usual, pulling out all available demons
3. Tyrant will be recommended to use even with 1 imp out and lots of time left on the demons activity 

### Snapshot (Link)

https://pastebin.com/H54Bp8w9

### Contact Information

sym1390

**Comment by Hekili** [comment]
This may have also been an issue with Vilefiend/Gloomhound/Charhound that has since been resolved.  If this is occurring in 0.9.1c or later, feel free to reopen with a new snapshot.
