### ISSUE TITLE
DEMO - Grimoire: Felguard stops being recommended after dogs and vilefiend are active 

### ISSUE THREAD

**Issue by Rynitaca** [Hekili/hekili#3373]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The grimoire felguard stops being recommended during the opener rotation of demonology once your dogs and vilefiend are active. It should be recommended as part of the Tyrant set up

### How to Reproduce

1Enter the game as DEMO Warlock
2. Perform the DEMO Opener as usual
3. Cast dogs and vilefiend first, and you will see grimoire stop being recommended

### Snapshot (Link)

https://pastebin.com/kxtWhuCq

### Contact Information

sym1390

**Comment by Hekili** [comment]
I'm not sure that this was the latest version of the addon at the time you posted, but please test with 0.9.0e when it releases (soon) to see if this is still a valid ticket.

**Comment by Hekili** [comment]
Test with 0.9.0f to confirm if this is still an issue.  Thanks.
