### ISSUE TITLE
[REC] AUG Ebon might and breath refresh casting not working

### ISSUE THREAD

**Issue by thegolfpapa** [Hekili/hekili#3374]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When running a M+ you don't get prompted to cast breath or ebon might and it expires without the reminder in the rotation 

### How to Reproduce

Play Aug and run any level key

### Snapshot (Link)

signed off already

**Comment by syrifgit** [comment]
A snapshot will be required to look at this issue

**Comment by thegolfpapa** [comment]
will grab one after raid

**Comment by davemgelinas** [comment]
I can confirm this issue, just did M+ run and it barely suggested Ebon Might (it did but rarely), and never breath of eons. Resulted in me having only 60%  Ebon Might uptime for the run as I had to keep me eye on it for once.

**Comment by Hekili** [comment]
Still requires a snapshot.

**Comment by thegolfpapa** [comment]
> Still requires a snapshot.

Here is a sample of the no call for breath 

https://pastebin.com/sVkdGDqa

**Comment by Hekili** [comment]
The next release won't rely on the "Sense Power" buff being active.

**Comment by thegolfpapa** [comment]
> The next release won't rely on the "Sense Power" buff being active.

wizard - thanks for checking mate

**Comment by bySenom** [comment]
Yes, I agree, Ebon Might is only suggested again when Breath of Eons is ready, at least that's what I've noticed. Another thing I've noticed is that Prescience is suggested twice even though the first charge is just now becoming ready.

**Comment by davemgelinas** [comment]
How do I log a snapshot?

**Comment by thegolfpapa** [comment]
> Yes, I agree, Ebon Might is only suggested again when Breath of Eons is ready, at least that's what I've noticed. Another thing I've noticed is that Prescience is suggested twice even though the first charge is just now becoming ready.

I'm going to capture more for Hekili today. I've seen these as well.

**Comment by thegolfpapa** [comment]
> The next release won't rely on the "Sense Power" buff being active.

Ebon might dump of not suggesting. It seems to be only suggesting when breath of eons is nearing CD or off CD. Otherwise it's not recommending ebon might. The double prescience is also present in this payload. 

https://pastebin.com/KAQzqEdk

**Comment by Hekili** [comment]
There is a new Aug priority coming; let's see if this is addressed after that update.  Thanks.

**Comment by Hekili** [comment]
New priority will be posted in 0.9.1a.

**Comment by Hekili** [comment]
I'm closing this ticket; if this is still an issue, it can be reopened with a snapshot from 0.9.1c or later.
