### ISSUE TITLE
[BUG] Hekili not displaying anything for WW monk (RESOLVED)

### ISSUE THREAD

**Issue by Uthemon** [Hekili/hekili#3375]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili not displaying anything for WW monk. 

### How to Reproduce

no real way to reproduce. its only happening on my monk. 

### Player Information (Link)

"no snapshots have been generated" and the drop down wont let me.

### Error Messages (Link)

no error

**Comment by syrifgit** [comment]
Monk hasn't been completed yet. Keep an eye out for updates.

**Comment by Uthemon** [comment]
ahhh ok, couldnt find any information on it so just assumed it was a bugged. ty for the update!
