### ISSUE TITLE
Holy Paladin recommendations not showing up as option anymore

### ISSUE THREAD

**Issue by Ratayu** [Hekili/hekili#3376]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my holy paladin when I log into the game there is not a recommended option. When I open the addon I don't see Holy paladin as an option. 

### How to Reproduce

Login into game, open addon, only shows retribution and protection, no holy

### Snapshot (Link)

Not able to use snapshot

**Comment by Ratayu** [comment]
Prior to update, I had even modified my open priorties. Honestly if I can find a way just to have the holy option available, I can re-enter my own custom priority.

**Comment by Ratayu** [comment]
Nevermind, I was able to uncomment in toc file and just brought holy paladin LUA file to TWW file. Good now.

**Comment by syrifgit** [comment]
Holy Paladin has not been completed yet.

![image](https://github.com/user-attachments/assets/c67c816d-0e50-4756-8b90-9fead5fb924a)
