### ISSUE TITLE
Guardian Druid not recommending specific spell

### ISSUE THREAD

**Issue by OfficialExiled** [Hekili/hekili#3377]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am not 100% sure, but I think it should be the same as last season where Raze should be recommended in AOE especially when you are in incarn or when we have lots of rage, but instead it keeps recommending Maul which is a ST spell. Also, I kind of forgot or can make a new ticket, but I think when the rage almost gets 100 or before it should recommend at least some pool to use Ironfur or Raze or something not to cap the rage to 100% consistently. 

### How to Reproduce

Just press incarn and do normal rotation until you get capped rage, then you will see it will recommend Maul and not Raze in AOE situation. 

### Snapshot (Link)

https://pastebin.com/sFJhqwnP

**Comment by OfficialExiled** [comment]
Oh something to add when having a buff called Tooth and Claw, its not recommending to use Maul or Raze, which is buffed and free. If you need a snapshot of this, I can also provide it, or you can just check it out yourself by doing normal rotation until you get the buff "Tooth and Claw"

**Comment by syrifgit** [comment]
Bear still has more updates to be done.

![image](https://github.com/user-attachments/assets/cb3e3ba0-1c82-4d0d-9544-d47106794cb6)

**Comment by Hekili** [comment]
I'm making small tweaks to Guardian in 0.9.0e but the real fixes will come when the sim priorities are updated.
