### ISSUE TITLE
DESTRO - Chaos Bolt not getting recommended

### ISSUE THREAD

**Issue by mjayfinley** [Hekili/hekili#3378]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm not getting Chaos Bolt recommended at all - add on only recommends Incinerate/Conflag spam at max shards

### How to Reproduce

1. Enter Game as Destro Lock
2. Start rotation as suggested by Hekili
3. Notice Chaos Bolt is not recommended, even during Infernal

### Snapshot (Link)

https://pastebin.com/rxVMqSRW

**Comment by BungleTBear** [comment]
Confirm this is happening for me as well since TWW pre-patch.

**Comment by syrifgit** [comment]
Chaos bolt spell/talent ID issue? I will look into it later today if Hekili doesn't get to it first.

```
 49.  chaos_bolt ( default - 18 ) - talent [ chaos_bolt ] missing
        Time spent on this action:  0.01ms
        TimeData:Destruction-default-18:chaos_bolt:0.01:Ability Known, Enabled(0.01)
```

**Comment by yenbounger** [comment]
Chaos bolt has changed from a talent to baseline - have tested locally by removing `talent = chaos_bolt` from WarlockDestruction.lua line 1300 and seems to work locally :)

**Comment by BungleTBear** [comment]
> Chaos bolt has changed from a talent to baseline - have tested locally by removing `talent = chaos_bolt` from WarlockDestruction.lua line 1300 and seems to work locally :)

Have tested same here and also works locally.

**Comment by Hekili** [comment]
Yup, the talent requirement will be removed in 0.9.0e.  Thanks!
