### ISSUE TITLE
Addon not showing at all

### ISSUE THREAD

**Issue by trabbit11** [Hekili/hekili#3379]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I just reinstalled wow after a couple month hiatus, and only downloaded the addons i absolutely cant play without. Hekili is one of those, for cooldown tracking some optimization tweaks to my memorized rotation. When im on my druid, it only appears when i swap to feral, and disappears otherwise. Wehn im on my rogue or my mage, the primary priority helper never appears no matter what i enable or try to change to get it to work. Ive already reset the profile, ive uninstalled, reinstalled, disabled all other addons, and set the hekili back to the default settings it has embedded. Please help

### How to Reproduce

1. I enter game
2. hekili no worky

### Player Information (Link)

asdfasdf

### Error Messages (Link)

asdfasdf

### Additional Information

unable to snapshot, and not getting error messages as the addon not appearing is the sole issue here

### Contact Information

Crakd#0771

**Comment by OfficialExiled** [comment]
Just so you know, currently Rogue and Mage are not available. So, that's why it's not showing anything. 

Blood, Frost, Unholy DK
Havoc, Vengeance DH
Balance, Feral, Guardian Druid
Augmentation, Devastation Evoker
Beast Mastery, Marksmanship, Survival Hunter
Protection, Retribution Paladin
Elemental, Enhancement Shaman
Arms, Fury, Protection Warrior
Affliction, Demonology, Destruction Warlock (currently using DF priorities)

These are the classes that are currently working, and his prio with the next classes will DPS > Tanks > Healers, likely Monk > Rogue > Priest > Mage.

**Comment by trabbit11** [comment]
Thank you very much i was unable to locate this information, but likely because im stupid.

**Comment by OfficialExiled** [comment]
Don't worry about it, if you are unsure about something, just click the pinned messages.

**Comment by trabbit11** [comment]
wher can i locate "pinned messages"? not a frequent github user

**Comment by OfficialExiled** [comment]
> wher can i locate "pinned messages"? not a frequent github user

![image](https://github.com/user-attachments/assets/7f300164-1935-4b87-87de-977effd5122f)
If you look at the top right, there is like a pin icon, just click that

**Comment by syrifgit** [comment]
> wher can i locate "pinned messages"? not a frequent github user

I think they meant in Discord. I have added a new [Pinned Issue](https://github.com/Hekili/hekili/issues/3380) here on Github as well to display the same info
