### ISSUE TITLE
Marksmanship aimed shot

### ISSUE THREAD

**Issue by intoache** [Hekili/hekili#338]
There's a problem with marksmanship hunter that in aoe situation, casting an aimed shot would not remove the trickshots buff in priority. That means I get the priority like multishot-aimed shot-rapid fire, but the right thing should be multishot-aimed shot-multishot-rapid fire.
A line "removeBuff( "trick_shots" )" should be added to the lua of marksmanship, so I don't have to add it myself every time hekili is updated, plz take a look, thanks.

**Comment by Hekili** [comment]
Well, why wouldn't you have reported this before instead of modifying your local copy repeatedly?

I'll update Aimed Shot.

**Comment by intoache** [comment]
I'm from China and Github is hard to connect here, I struggled to find out this website, forgive me and my poor English, ha.

**Comment by Hekili** [comment]
Haha, no problem.  I appreciate the report.  Take care!
