### ISSUE TITLE
TWW Pre-Patch: All Specializations are Live as of v11.0.0-1.0.0

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3380]
# Status of specs for TWW updates

## DPS

- [x] All Specializations

## Tanks

- [x] All Specializations

## Healers

- [x] All Specializations

**Comment by crazyshea** [comment]
Hekili not working for monk

**Comment by syrifgit** [comment]
> Hekili not working for monk

That's why it is on this list as "not yet completed".

**Comment by Myntha** [comment]
Hey! Thanks for the great work with Hekili! I just wonder if there are any ETA on when healers Will ”work” again? 
And once again, the Work you put into this is amazing

**Comment by Critix420** [comment]
Have you already planned when you'll start playing Outlaw Rogue? I love your addon so much.

**Comment by jcruzdesigns** [comment]
When will mage be added?

**Comment by NBloodwyn** [comment]
why the affliction reco goes for like 6x consecutive shadow bolt? shards is capping not enough malefic rupture casted

**Comment by xoDragonsbadxo** [comment]
All tanks but Brewmater are checked. I'm going with you saved the best for last lol.

**Comment by Deerylou** [comment]
Is there a realistic expectation as to when Windwalker Monk and Brewmaster monk are anticipated? Players of both seem the most unacclimated following prepatch, myself included. I appreciate Hekili's guidance as always.

**Comment by iahriZ** [comment]
is there any possible way to import old version priority, rather than waiting? as in pre-patch, some of those can still be used, rather than waiting your work.

**Comment by Zanetsuken** [comment]
> is there any possible way to import old version priority, rather than waiting? as in pre-patch, some of those can still be used, rather than waiting your work.

It will still be incorrect, talent trees have changed, in some cases considerably so.

**Comment by leho93** [comment]
rogue ?

**Comment by Hekili** [comment]
Assassination Rogue added in v11.0.0-0.9.1b.

**Comment by leho93** [comment]
Outla

**Comment by Hekili** [comment]
Outlaw Rogue added in v11.0.0-0.9.2.

**Comment by syrifgit** [comment]
It's all ogre.
