### ISSUE TITLE
enhancement shaman- elemental blast not being recommended at all 

### ISSUE THREAD

**Issue by Hursems** [Hekili/hekili#3381]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

elemental blast not being recommended at all in enhancement shaman default rotation

### How to Reproduce

play enhancement shaman and go through rotation

### Snapshot (Link)

https://pastebin.com/i9sfERpq

**Comment by syrifgit** [comment]
That is not a full snapshot, you only grabbed the top line. It should be a _significant_ wall of text. [This guide](https://github.com/Hekili/hekili/wiki/Report-An-Issue) has detailed instructions of how to get one.

**Comment by Hursems** [comment]
https://pastebin.com/eezxut3N
new paste with the full wall sorry

**Comment by Hekili** [comment]
Right now, in my testing, Elemental Blast is not replacing Lava Burst which is causing issues.  

![image](https://github.com/user-attachments/assets/813a83c7-e7c1-41d0-99ab-13248f64578b)

![image](https://github.com/user-attachments/assets/bcd699fe-83a1-45ef-b6e5-c2f9366c0431)

My class talents also keep falling off during testing.

**Comment by Hekili** [comment]
Fix incoming in 0.9.0e.

**Comment by Hursems** [comment]
awesome thank you !
