### ISSUE TITLE
Hekili not working for Shadow priest

### ISSUE THREAD

**Issue by Travlo10** [Hekili/hekili#3382]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

No matter what i have tried, i can not get Hekili to work for shadow priest. There are no errors to report it just doesnt do anything.

### How to Reproduce

Log in

### Player Information (Link)

There is nothing ti paste

### Error Messages (Link)

no errors

### Contact Information

_trav10

**Comment by Thornic** [comment]
In https://github.com/Hekili/hekili/issues/3380 you can see that Shadow Priest is not yet completed.

**Comment by Travlo10** [comment]
my bad, didnt see this. Will remove the issue
