### ISSUE TITLE
[FEATURE] REPLACE THIS TEXT WITH A BRIEF DESCRIPTION OF YOUR NEW FEATURE

### ISSUE THREAD

**Issue by esteve12** [Hekili/hekili#3383]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello, I would like to know when they will add rogue assassinate to Hekili

**Comment by cptgotham** [comment]
Go to TWW Pre-Patch: Class/Spec Status Tracker and hit F5 every 10 seconds :)

**Comment by syrifgit** [comment]
It will be added once it is completed. Have patience and keep an eye out for updates.

https://github.com/Hekili/hekili/issues/3380
