### ISSUE TITLE
[REC] DK Unholy: AoE rotation only recommends Scourge Strike and Outbreak, not recommends Defile, Epidemic or Abo

### ISSUE THREAD

**Issue by SpartanEsp** [Hekili/hekili#3384]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Opener on AoE not recommends Raise Abo
AoE rotation opener only recommends Scourge Strike, not recommends Defile, Epidemic or Vile Contagion on a target with 6 Festering Wounds
Also, on AoE burst phase, not recommends Epidemic on Sudden Doom procs, only spams Scourge Strike

### How to Reproduce

1. Enter with DK
2. Set talents to Unholy
3. Be sure to select talents: Defile, Apocalypse, Vile Contagion, Raise Abomination
4. Start the AoE pull on Training Dummies
5. Check the opener and you will see that hekili not recommends Defile, Epidemic or Vile Contagion
6. Keep following hekili and check massive spam of Scorge Strike
7. Check AoE burst phase, not recommends Epidemic on Sudden Doom procs, only spams Scourge Strike and in some cases Outbreak

### Snapshot (Link)

https://pastebin.com/JMM55Ku2

**Comment by Hekili** [comment]
Please sim your character on Raidbots for comparison.  Thanks!

**Comment by Hekili** [comment]
0.9.0e will have a fix for this.

**Comment by SpartanEsp** [comment]
> 0.9.0e will have a fix for this.

Thx !

**Comment by Fantome4** [comment]
It still has problem for AOE rotation, stuck on scourge strike/outbreak and never use Epidemic to keep rotation. Try on dummies and dungeon tho

**Comment by SpartanEsp** [comment]
https://pastebin.com/dy6HVUDq

The AoE rotation is still broken, never rec Epidemic with or without Sudden Doom procs its stuck on Scourge Strike in or out of Death & Decay, and should be only rec if the player is inside D&D

Right now it only recommends a continuous spam of Scourge Strike and Outbreak
Vile Contagion should be rec only if the target got 6 Festering Wounds

EDIT: Raise Abomination is still not recommended in any moment

**Comment by Hekili** [comment]
It's not detecting Virulent Plague on enemies to use Epidemic for some reason.  Investigating.

**Comment by Hekili** [comment]
> EDIT: Raise Abomination is still not recommended in any moment

![image](https://github.com/user-attachments/assets/7e8966b9-ee3f-4030-ac53-eee4ae59c686)

It is a replacement for Army of the Dead, which you have set to use only on bosses.

> 2.   army_of_the_dead ( precombat - 2 ) - **ability disabled ( boss-only )**

**Comment by SpartanEsp** [comment]
Check Defile, because im 90% sure that is recommending Defile while Defile is on the floor

EDIT: Defile is recommended while Defile is active

**Comment by SpartanEsp** [comment]
> It is a replacement for Army of the Dead, which you have set to use only on bosses.

Checked and fixed

**Comment by fttf7** [comment]
same for me in 0.9.0e !

**Comment by Hekili** [comment]
0.9.0e was missing some of my fixes; 0.9.0f should include these changes.  Please reply/reopen if the issue persists in 0.9.0f.

**Comment by Woodwind800** [comment]
It seems as though now on the cleave training dummies at least, that outbreak isn't being reccomended at all. Epidemic does get suggested after using outbreak without it being suggested though.
