### ISSUE TITLE
SHAM - ELEM   Earthquake not recommended at all

### ISSUE THREAD

**Issue by JeanRaymondPach** [Hekili/hekili#3385]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Elem sham, I expect Earthquake to be recommanded in AOE cycle. It's never recommanded, even with a Proc.

### How to Reproduce

1. I enter the game as a Elemental shaman.
2. I fight 5 dummies with my AOE build (including Earthquake)
3. I follow the rotation, but Earthquake is never recommanded.

### Snapshot (Link)

https://pastebin.com/sbgSH3zz

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/2kU66WrMbb9CDqEk6eTDV1

### Contact Information

DISCORD : istrians

**Comment by syrifgit** [comment]
This has already been fixed [14 hours ago](https://github.com/Hekili/hekili/releases/tag/v11.0.0-0.9.0c), you need to update your addon. During the first week of a major release it's always a good idea to be constantly checking for updates for all of your addons. Many of the big ones may get multiple updates a day.
