### ISSUE TITLE
Aff lock does not recommend Soul Rot or Dark Glare for rotation.

### ISSUE THREAD

**Issue by Psychospaz** [Hekili/hekili#3386]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

My Aff lock does not get recommended the soul rot or the dark glare like it used to. According to my research the new rotation should have both going due to the increase in MR and DOT time increase.

### How to Reproduce

1. Take affliction.
2. Take soul rot and Dark glare. 
3. Fight dummies and notice that neither pop up for damage.

### Snapshot (Link)

https://pastebin.com/66dLkjYU

### Contact Information

Discord: Psychospaz

**Comment by Hekili** [comment]
Fix is incoming.
