### ISSUE TITLE
[REC] Affliction lock not recommending Summon Darkglare and Soul Rot 

### ISSUE THREAD

**Issue by shanehimself9** [Hekili/hekili#3387]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Affliction lock not recommending Summon Darkglare and Soul Rot. THese spells seem to never appear and or are recommend. 

### How to Reproduce

Playing afflictions and doing any opener or ramp to the darkglare. Every other spell but the two listed get reccomended. 

### Snapshot (Link)

https://pastebin.com/HvTuTE66

**Comment by Hekili** [comment]
Looks like Soul Rot fix didn't make it into 0.9.0e.  I'm publishing 0.9.0f to include the fix.

**Comment by KNP54** [comment]
Error reappeared on 1.0.4?
