### ISSUE TITLE
Unholy DK Recommending Outbreak often and not recommending Epidemic in AOE situations.

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#3388]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Currently UH DK does not seem to recommend Epidemic.  It is in the Q, but instead will suggest outbreak while diseases are up and when outbreak is pressed the Q changes to mostly scourge strikes.

### How to Reproduce

1. Enter game as Unholy DK.
2. Load cookie cutter M+ Build:
CwPAtbMOTHlnKIwUyAn+DK70SDgZGjhZYYmZmZmphxMzYGDAAAAAAAAghZGzYmZmZAAbgZxYmZmhZGAAAAAgZAmBA
3. Hit 5 target dummies and follow suggested rotation for AOE display.  Addon will jump around priority.

### Snapshot (Link)

https://pastebin.com/RWAjR6pL

### Raidbots Sim Report (Link)

Tried to QuickSim with /Simc addon in game and said out of date talents?  Not sure on a fix for this.

### Contact Information

ulltidk

**Comment by SpartanEsp** [comment]
https://github.com/Hekili/hekili/issues/3384

Known issue, prob fixed on next version

**Comment by syrifgit** [comment]
As noted above, this is a duplicate ticket.
