### ISSUE TITLE
Ret Paladin downtime / not recomending free divine storms

### ISSUE THREAD

**Issue by ZethenZynx** [Hekili/hekili#3389]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Not recommending free divine storms and instead showing to wait on templar strikes causing a downtime gap in dps

### How to Reproduce

talents in subject are templar strikes and empyrean power, to reproduce maybe just dps aoe target dummies and when a free divine storm happens it will show a cooldown on templar strikes instead

### Snapshot (Link)

https://pastebin.com/VBHhepPb

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3udPvMj9jkw4X9ss4nu1Qn

### Additional Information

this is my talent build i am using

CYEALSUfbn0RkIzCqAITj7R8pAAAAwAAMZZZbmZbZxMWmZmlF2GAAAAAAGqZmZ2MwMYMLjhZGYWmZZbMwMMGLbYAAAAAAAAA

### Contact Information

zethenzynx on discord

**Comment by syrifgit** [comment]
The sim you posted is using completely different talents than your snapshot. Please get a sim with the same talents so it can be compared.

Can you also make the snapshot when the free divine storm is available but not being recommended?

**Comment by Hekili** [comment]
I tested your talent build in-game and it works fine.

https://pastebin.com/vTevaWSt

I have Empyrean Power active and procced:

```
player_buffs:
   430666 - *sign_of_awakened_storms                 -   1 - 3600.00
   430668 - *sign_of_awakened_embers                 -   1 - 3600.00
   430669 - *sign_of_awakened_dreams                 -   1 - 3600.00
   186403 - *sign_of_battle                          -   1 - 3600.00
   426339 - *igiras_cruel_nightmare                  -   1 - 3600.00
   396092 - *well_fed                                -   1 - 300.80
   399502 - *atomically_recalibrated                 -   1 - 304.25
   393438 - *draconic_augmentation                   -   1 - 1080.75
   425153 - *firestarter                             -   8 - 3600.00
   406975 - divine_arbiter                           -  12 - 26.53 
   385127 - blessing_of_dawn                         -   1 - 16.53 
   326733 - empyrean_power                           -   1 - 11.66 
```

The third entry item in queue is the first time we reach Divine Storm in the action list, and it is selected.

```
        28.  divine_storm ( finishers - 3 )
        The action (divine_storm) is usable at (1.05 + 1.05).
         - the action is ready before the current recommendation (at +1.05 vs. +10.00).
        List ( generators ) called from ( Retribution:default:3 ) would PASS at 1.05.
        NONE
        List ( finishers ) called from ( Retribution:generators:1 ) would PASS at 1.05.
        holy_power.current[5.00] = 5 | buff.echoes_of_wrath.up[false] & set_bonus.tier31_4pc[1.00] & talent.crusading_strikes.enabled[false] | ( debuff.judgment.up[false] | holy_power.current[5.00] = 4 ) & buff.divine_resonance.up[false] & ! set_bonus.tier31_2pc[1.00]
         - this entry's criteria PASSES: variable.ds_castable[true] & ( ! talent.crusade.enabled[false] | cooldown.crusade.remains[120.00] > gcd.max[1.05] * 3 | buff.crusade.up[false] & buff.crusade.stack[0.00] < 10 | talent.radiant_glory.enabled[false] )
        Action chosen:  divine_storm at 1.05!
```

Is it possible you're being misled by Divine Storm lighting up when Echoes of Wrath procs?  Divine Storm isn't free with Echoes of Wrath.  Echoes of Wrath *is* active in your snapshot.

```
   423590 - echoes_of_wrath                          -   1 - 10.93 
```
