### ISSUE TITLE
[REC] TWW Brewmaster update

### ISSUE THREAD

**Issue by Sarletor** [Hekili/hekili#3391]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

TWW Brewmaster update

### How to Reproduce

-

### Snapshot (Link)

-

**Comment by syrifgit** [comment]
Monk is not finished yet: https://github.com/Hekili/hekili/issues/3380
