### ISSUE TITLE
[REC] Elemental Blast Not Recommended for Ele Sham

### ISSUE THREAD

**Issue by Rulyen46** [Hekili/hekili#3392]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Elemental Blast is not being recommended in the rotation for Enhancement Shaman as expected. This is causing extra Crit/Haste and Mastery to be lost during combat.

### How to Reproduce

Enter game as Enhancement Shaman
Ensure Elemental Blast is taken as a talent
Begin combat, follow rotation suggested by Hekili
Note Elemental Blast is never recommended

### Snapshot (Link)

https://pastebin.com/SrftjUaq

### Contact Information

brandon2193 - Discord

**Comment by syrifgit** [comment]
Update to the newest version before submitting a snapshot/ticket, you are 1 version behind. This issue was already fixed.

![image](https://github.com/user-attachments/assets/f379e954-e8e5-493d-ab99-3db73f26dd28)
