### ISSUE TITLE
Beast Mastery not showing

### ISSUE THREAD

**Issue by andi1o** [Hekili/hekili#3394]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

i updated last version but hekili is not showing on beast mastery. i tried enable then disable, i reinstalled addon but still not showing

### How to Reproduce

.

### Player Information (Link)

.

### Error Messages (Link)

.

**Comment by syrifgit** [comment]
Check this setting 

Sorry one sec having trouble uploading from mobile 

![Uploading image.png…]()

**Comment by syrifgit** [comment]
![image](https://github.com/user-attachments/assets/98a5f7a8-a606-4a28-8017-920d33af63f1)

**Comment by andi1o** [comment]
after reentering Talents showed up. tnx

do you know in how many days mage will be available?
