### ISSUE TITLE
[BUG] Hekili is no Longer Showing on Screen Outside of Setup Mode

### ISSUE THREAD

**Issue by balatro-hdg** [Hekili/hekili#3395]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

With the latest release, Hekili no longer shows the rotation on my screen. I can enter "setup mode" and move things around just fine but the rotation never appears on the screen. I've included a screenshot from my lvl 28 mage but it's also holding true for all of my lvl 70 toons. I play with default settings. I have uninstalled and reinstalled the addon via Curseforge. It's probably an easy fix and I'm missing something.

![HekiliGithub](https://github.com/user-attachments/assets/7bdddd39-56a5-4489-ae91-8314e40284a3)

### How to Reproduce

The bug is appearing across all toons.

### Player Information (Link)

See additional information

### Error Messages (Link)

N/A

### Additional Information

I've checked the toggle for taking a snapshot and confirmed that it's Alt-Shift-[. It's not taking a snapshot so that's a separate issue.

**Comment by syrifgit** [comment]
Mage is not ready yet: https://github.com/Hekili/hekili/issues/3380
