### ISSUE TITLE
Hekili Does NOT display at all for my lvl 70 Mage.

### ISSUE THREAD

**Issue by ringochen** [Hekili/hekili#3396]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili does not display for my Mage at all. My other characters load and work perfectly. My mage however, does not display even though it's loaded. I have a lvl 70 Mage and I have deleted the addon from the system and added it back and I've also disabled all the addons except for Hekili and still no luck. I'm lost.. what else can I do?

### How to Reproduce

I simply enter the game as my Mage and its as if I don't have it loaded. All the other characters work fine. I do not change the settings except for the "Profiles" to make sure it doesn't confuse other settings for play. 

### Player Information (Link)

There are no Generated errors

### Error Messages (Link)

I did this and it "grabs" nothing

### Additional Information

There are NO Snapshots with errors to show you so I can't link you to an issue other than tell you it does not display even though it's loaded. :( I am able to bring up the console and display all the settings etc but I can't get the damn thing to display on my screen :( HELP!

Notice the attached file shows in setup that the "Primary", "Notifications", AOE and others display perfectly... but once I leave this mode.. it vanishes.
![github 38 PM](https://github.com/user-attachments/assets/22d3b12c-e1d8-475d-a482-5b4009efba04)

### Contact Information

kashmere_kahn on discord or email at ringo.chen.1@gmail.com

**Comment by Daveo7** [comment]
I can also confirm Hekili does not display on any of my mages (2x fire, 1x frost).

**Comment by BruHaan** [comment]
Yes.. because it not done yet. There is a list already being tracked.

https://github.com/Hekili/hekili/issues/3380
