### ISSUE TITLE
BM Hunter - Hunter's Mark does not show as a reccomendation when targeting a new target in the dungeon that is at 100% HP

### ISSUE THREAD

**Issue by luke0230** [Hekili/hekili#3397]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

BM Hunter - Interrupts and Hunter's Mark do not show on the bar

### How to Reproduce

Running any mythic + dungeon - interrupts and hunter's mark does not show on the bar evn though it is turned on

### Player Information (Link)

Beast Mastery; Primary - Bestial Wrath(0.00), Blood Fury(1.10), Barbed Shot(1.10), Barbed Shot(2.21), Kill Command(3.31)

### Error Messages (Link)

No error messages

### Contact Information

lukaszmonka@me.com

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by luke0230** [comment]
Beast Mastery; AOE - Barbed Shot(0.00), Barbed Shot(1.11), Multi-Shot(2.22)

**Comment by luke0230** [comment]
I edited the post and attached snapshotsBest RegardsLukasz Monka, CCMGM/COO at Tiburon Peninsula Club628.244.7640 ***@***.*** Jul 26, 2024, at 1:50 PM, Hekili ***@***.***> wrote:﻿
A snapshot is required to diagnose this issue.
Snapshot
Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

Log into your WoW character.
Recreate the issue you are reporting (i.e., generate 5 Holy Power).
When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).

You can change these keybindings in /hekili > Toggles if needed.
If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.


Type /hekili and press Enter.
Open the Snapshots section on the left side.
Select the snapshot that shows the recommendation that you disagree with.

Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.


Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
Open https://pastebin.com, use CTRL+V to paste the snapshot text, then click Create New Paste.
Provide the Pastebin link in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
Same as your other ticket; snapshots are LONG logs of text that need to go on Pastebin and then get linked here.  But this will be resolved in the next release.

**Comment by luke0230** [comment]
Sorry for the mess I am not very familiar with logistics. I appreciate your help and updates.Best RegardsOn Jul 27, 2024, at 9:37 AM, Hekili ***@***.***> wrote:﻿
Same as your other ticket; snapshots are LONG logs of text that need to go on Pastebin and then get linked here.  But this will be resolved in the next release.

**Comment by luke0230** [comment]
Great work on the add-on - with the recent change the dispell display stopped working.

Sincerely,
Lukasz
