### ISSUE TITLE
monk recommend fof when I only have 2 chi

### ISSUE THREAD

**Issue by 78jeffrey** [Hekili/hekili#3399]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Monk class recommend FoF when I only have 2 chi

### How to Reproduce

FoF need 3 chi to cast.

### Snapshot (Link)

https://pastebin.com/tjPeh1kJ

**Comment by calvinwithac** [comment]
@Hekili , your ordered_elements statements are backwards on all the spend functions.

e.g.

1815        spend = function() return buff.ordered_elements.up and 2 or 1 end,

should be

1815        spend = function() return buff.ordered_elements.up and 1 or 2 end,

**Comment by nzall** [comment]
> @Hekili , your ordered_elements statements are backwards on all the spend functions.
> 
> e.g.
> 
> 1815 spend = function() return buff.ordered_elements.up and 2 or 1 end,
> 
> should be
> 
> 1815 spend = function() return buff.ordered_elements.up and 1 or 2 end,

Note that there are only some that are inverted. In some statements, buff.ordered_elements.up is used to determine how much chi a spell costs, but in other statements, it's used to determine how much chi should be deducted from the cost.

**Comment by Hekili** [comment]
This will be resolved in the next release.
