### ISSUE TITLE
Shrouded Suffocation/Exsanguinate/Subterfuge

### ISSUE THREAD

**Issue by Stytcha** [Hekili/hekili#340]
I'm not sure if there is already a fix for this. 

When using Shrouded Suffocation/Exsanguinate build. 
My issue I'm seeing is the addon is telling me to cast Garrote when I have an empowered Garrote already applied to the target. It seems to always tell me to use Garrote off cooldown. 

Possibly it is just a simple fix with a profile?

**Comment by Stytcha** [comment]
And one more note. There also seems to be an issue with the addon telling me to apply Rupture with 0 combo points.

**Comment by Hekili** [comment]
Please follow the instructions for submitting a ticket.  There's information I'd need to explore this (issue reporting / snapshot).

**Comment by Stytcha** [comment]
build: v8.3.0-04-21
level: 120 (120)
class: ROGUE
spec: assassination

talents: cheat_death
    deeper_stratagem
    elaborate_planning
    exsanguinate
    internal_bleeding
    poison_bomb
    subterfuge

azerite: azerite_empowered = 3
    heart_of_darkness = 1
    lying_in_wait = 1
    nothing_personal = 2
    overwhelming_power = 3
    self_reliance = 1
    shrouded_suffocation = 3
    vampiric_speed = 1

essences: [blood_of_the_enemy] = 3, breath_of_the_dying = 3, conflict_and_strife = 3, memory_of_lucid_dreams = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    ashvanes_razor_coral = 1
    boots_of_the_insatiable_maw = 1
    bracers_of_dark_prophecy = 1
    cord_of_anguished_cries = 1
    darkheart_robe = 1
    destroyers_shadowblade = 1
    gibbering_maw = 1
    gorak_tuls_mantle = 1
    heart_of_azeroth = 1
    legwraps_of_the_insatiable_maw = 1
    logic_loop_of_recursion = 1
    overclocking_bit_band = 1
    shard_of_the_black_empire = 1
    underrot_grotto_tenders = 1
    vitacharged_titanshard = 1

corruptions: gushing_wound = 1
    twisted_appendage = 5

itemIDs: 158075, 159339, 159344, 169158, 169159, 169223, 169311, 172185, 172227, 173442, 173477, 174131, 174134, 174138, 174140, 174500

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Assassination
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    envenom_pool_pct = 50
    mfd_waste = true
    priority_rotation = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Could you update to the latest beta version?  If you have the latest beta and you still have this issue, capture a snapshot (pause the addon) when it is giving a recommendation you disagree with.

**Comment by Stytcha** [comment]
https://www.raidbots.com/simbot/report/e8gxyUnweopnz5XiVhChwN

The above link is the ideal rotation and I will try to get some snapshots of the recommendations I'm getting. The add on is amazing by the way!

**Comment by Hekili** [comment]
I routinely check the latest SimC profiles (which is what Raidbots is using).  Yeah, if there's a bug in the latest build that's missing Shrouded Suffocation or something, I'd want to address that.

**Comment by Hekili** [comment]
It's worth noting, that with your talents, sims are opening with Garrote, Rupturing, then hitting Garrote again.  So there may be a priority issue with SimC/Raidbots to pursue.

![image](https://user-images.githubusercontent.com/9438134/80250955-c50abc00-8642-11ea-9c30-297948d81ce3.png)

![image](https://user-images.githubusercontent.com/9438134/80250922-b58b7300-8642-11ea-8f34-aceb8ee32eae.png)

**Comment by Stytcha** [comment]
![WoWScrnShot_042420_154413](https://user-images.githubusercontent.com/64280430/80250927-b9b79080-8642-11ea-8be2-ed44d32b3a1a.jpg)
![WoWScrnShot_042420_154448](https://user-images.githubusercontent.com/64280430/80250968-cc31ca00-8642-11ea-93e5-60e312feaaf8.jpg)
![WoWScrnShot_042420_154511](https://user-images.githubusercontent.com/64280430/80250996-d81d8c00-8642-11ea-8a5e-3bc31ab57438.jpg)

**Comment by Hekili** [comment]
Please review the original ticket instructions.  I don't need screenshots; I need snapshots of the addon's decision-making logic.  So far, it appears to match what SimC/Raidbots is doing with regard to the Garrote opener.

**Comment by Stytcha** [comment]
First screen shot is pre combat, and seems to be correct. It seems as though the recommendation is to use Garrote every time its off cool down. You'll notice in the 3rd image it is recommending muti x2 and then Garrote but ideally you would want to cast Envenom after 2x muti.

**Comment by Hekili** [comment]
It's pretty wild.  Have you scrolled through the actions taken by the sim?  It's hitting Garrote **a lot**.

![image](https://user-images.githubusercontent.com/9438134/80251185-321e5180-8643-11ea-885b-93a64b8b0eed.png)

**Comment by Stytcha** [comment]
You want to Garrote as many times as possible within the 3 second window of Subterfuge, which is typically twice. After that, you do not want to apply Garrote until the empowered Garrote has ticked close to 0. Working on snap shots now.

**Comment by Stytcha** [comment]
The last Garrote you see there is right before Subterfuge wears off, after that you would not Garrote again until you Vanish or it has expired from the target.

**Comment by Stytcha** [comment]
https://pastebin.com/ycsGCDs8

**Comment by Hekili** [comment]
Can you go into `/hekili > Priorities > Assassination`, and click the `Action Lists` tab?

From there, select `Action List: default` and `Entry: 1`.

It *looks* like you or somebody changed the action from Kick to Garrote.

![image](https://user-images.githubusercontent.com/9438134/80254061-795b1100-8648-11ea-8e11-a8b22fb72a97.png)

**Comment by Hekili** [comment]
Let me know if that resolves it.  Researching this did help me find another bug which I'll address in a new beta.

**Comment by Stytcha** [comment]
Resolved. Not sure what I did to change the priority but that fixed it. 

I'm not sure if this is the place but I'm interested to know how Vanish is handled. It seems to be recommended seldomly and is very important to the Shrouded Suffocation build. I'd love to be able to help in any way.

**Comment by Hekili** [comment]
Vanish doesn't work solo, since it would reset the fight. So dummy testing
is impacted by it. If it's not working for you in group content, let me
know. Thanks.
