### ISSUE TITLE
[REC] PROT "Sentinel" is recommended, but no Spellflash

### ISSUE THREAD

**Issue by PopsGG** [Hekili/hekili#3400]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my PROT paladin the spell "Sentinel" is recommended in the rotation, but the action bar icon does not have the spellflash applied. "Sentinel" shares a talent slot with "Avenging Wrath: Might" and I believe that might be the cause. Both "Sentinel" and  "Avenging Wrath: Might" have the same issue.

### How to Reproduce

1. Play as Prot pally
2. Do rotation until "Sentinel" is recommended and it will not have the spellflash highlight.

### Snapshot (Link)

https://pastebin.com/npeXd31E

**Comment by Hekili** [comment]
Fixed in next release.
