### ISSUE TITLE
[REC] Call of the wild is considered ready by cooldown.call_of_the_wild.ready when not talented

### ISSUE THREAD

**Issue by gjritter** [Hekili/hekili#3401]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For a Beast Mastery hunter talented into Huntmaster's Call and Killer Cobra, but not talented into Call of the Wild, I expect that Dire Beast should only be recommended when not in Bestial Wrath. The relevant priority condition in the default Beast Mastery priority package is this, from the ST action list:

`talent.huntmasters_call.enabled & ( ! buff.bestial_wrath.up & talent.killer_cobra.enabled | cooldown.call_of_the_wild.ready )`

However, this condition is evaluating to true because `cooldown.call_of_the_wild.ready` is returning true despite Call of the Wild not being talented.

### How to Reproduce

1. Enter the game as a Beast Mastery hunter.
2. Take the Dire Beast, Huntmaster's Call and Killer Cobra talents, but do not take Call of the Wild.
3. During Bestial Wrath, observe that Dire Beast is recommended.

### Snapshot (Link)

https://pastebin.com/7vEnGBtV

### Additional Information

I couldn't generate a relevant raidbots sim report, as raidbots is not currently working correctly with beast mastery (not using any abilities other than kill shot).

### Contact Information

gnomic

**Comment by Hekili** [comment]
The `cooldown.X.ready` expression is the equivalent of `cooldown.X.remains = 0` and does not appear to have a talent check built into SimulationCraft.  I will revise the Beast Mastery priority to also check for the talent instead.  This will be in the next release.
