### ISSUE TITLE
 [BUG] Hekili does not have any Monk Modules (yet) ?

### ISSUE THREAD

**Issue by Valhall2660** [Hekili/hekili#3402]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When i´m logging in, there is a massege from hekili, it says that there are no monk modules to load for hekili and hekili does not work...
![Monk Hekili](https://github.com/user-attachments/assets/90ac6816-4c31-4079-8454-b93759f81c68)

### How to Reproduce

Add monk modules for hekili

### Player Information (Link)

...

### Error Messages (Link)

...

**Comment by Zanetsuken** [comment]
Update your addon as you may not be running the latest version which added monk

**Comment by Raidwiper** [comment]
I have the same issue on the class you mentioned and shadow priest. Addon is updated as well. These are the only 2 classes that have this issue for me.

**Comment by Zanetsuken** [comment]
> I have the same issue on the class you mentioned and shadow priest. Addon is updated as well. These are the only 2 classes that have this issue for me.

Monk (WW and brew) was added last patch and their are open support tickets for rotation issues -https://github.com/Hekili/hekili/issues/3399

Just double check that you are running the latest version 11.0.0 0.9.1, and inside the options the addon is enabled.

 Shadow is not yet supported.
Check the pins for supported specs/classes.
https://github.com/Hekili/hekili/issues/3380
