### ISSUE TITLE
[BUG] Priest does not have any Hekili modules

### ISSUE THREAD

**Issue by Raidwiper** [Hekili/hekili#3403]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![World of Warcraft_2024 07 27-08 27_1](https://github.com/user-attachments/assets/ddd27a9a-d42e-4bcc-a588-e56cc31fed27)

Priest does not have any Hekili modules loaded (yet). Watch for updates.

I get this message as soon as I log into the game. Most other classes work just fine. I tried changing specs and then switching back to shadow priest but it gives the same message every time.

### How to Reproduce

Enter game as Shadow Priest or change spec to shadow priestShadow Priest

### Additional Information

Priest does not have any Hekili modules loaded (yet). Watch for updates.

**Comment by Zanetsuken** [comment]
See my other comment on your other comment.
Priest is not supported yet.

**Comment by Raidwiper** [comment]
Thanks. Sorry this was my first time here, and I didn't notice the pinned messages above at the top. I'm used to forums with pinned messages in the same area as the normal posts so I didn't see the list of supported specs. Thanks for your time.
