### ISSUE TITLE
SIMC: eclipse.in_none does not work and breaks balance SIMC since it is used there

### ISSUE THREAD

**Issue by davidmann4** [Hekili/hekili#3404]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

the simC command "eclipse.in_none" does not work  but is used in the default Balance druid priority pack.

### How to Reproduce

1. Enter game as balance druid
2. create a new profile and only use the following actions for testing the eclipse.in_none property

```
actions+=/starfire,if=eclipse.in_none
actions+=/wrath,if=(buff.celestial_alignment.down&buff.eclipse_lunar.down&buff.eclipse_solar.down)
```

3. hit accept
4. hit import

now it should show starfire, since you have no eclipse available. But it shows wrath - since eclipse.in_none is not working

quick and dirty fix:  replace all `eclipse.in_none` with `(buff.celestial_alignment.down&buff.eclipse_lunar.down&buff.eclipse_solar.down)`

### Snapshot (Link)

https://gist.github.com/davidmann4/34267ac4f268ba7e0a6b5a3f2b3d2dc5

### Contact Information
github should work

**Comment by Hekili** [comment]
`eclipse.in_none` will be functional in the next release.
