### ISSUE TITLE
BM Hunter - Interrupt reccomendation is not showing for any mobs

### ISSUE THREAD

**Issue by luke0230** [Hekili/hekili#3406]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In every dungeon or open world quest the reccommendation for interrupts is gone.

### How to Reproduce

Enter any dungeon or attack any caster mob. 

### Snapshot (Link)

Beast Mastery; AOE - Barbed Shot(0.00), Barbed Shot(1.11), Multi-Shot(2.22)

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by luke0230** [comment]
I attached snap shots…Best RegardsLukasz Monka, CCMGM/COO at Tiburon Peninsula Club628.244.7640 ***@***.*** Jul 27, 2024, at 9:15 AM, Hekili ***@***.***> wrote:﻿
A snapshot is required to diagnose this issue.
Snapshot
Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

Log into your WoW character.
Recreate the issue you are reporting (i.e., generate 5 Holy Power).
When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).

You can change these keybindings in /hekili > Toggles if needed.
If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.


Type /hekili and press Enter.
Open the Snapshots section on the left side.
Select the snapshot that shows the recommendation that you disagree with.

Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.


Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
Open https://pastebin.com, use CTRL+V to paste the snapshot text, then click Create New Paste.
Provide the Pastebin link in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Hekili** [comment]
You missed this part of the snapshot instructions.

> Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
> Open [pastebin.com](https://pastebin.com/), use CTRL+V to paste the snapshot text, then click Create New Paste.
> Provide the Pastebin link in a new comment.

Nevertheless, Counter Shot will be recommended in the next release.
