### ISSUE TITLE
[BUG] Spellflash doesn't work for Final Verdict and Wake of Ashes (Paladin Retribution)

### ISSUE THREAD

**Issue by Narzogg** [Hekili/hekili#3407]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hi, the spellflash option doesn't work with two spells on Paladin Retribution, both Final Verdict and Wake of Ashes. Every other spell works fine though. Is it just me or the issue is already known ? First screenshot it doesn't work with the two spells and on the second one it works with execution sentence (just an exemple) as you can see. Third screenshot is just paused and it's also not working.
![first](https://github.com/user-attachments/assets/f7bb4d38-94c4-45f6-9dbd-9a02497ffb44)
![second](https://github.com/user-attachments/assets/f3c3aa9e-e9f9-4044-bb64-fc6a3ccff78c)
![third](https://github.com/user-attachments/assets/53de3dcf-d49f-47ff-aa74-489512d365ff)

### How to Reproduce

1. Enable spellflash on a retribution paladin. 2. Notice that both Final Verdict and Wake of Ashes are not working, they are correctly recommended but are not flashed.

### Player Information (Link)

Retribution; Primary - Templar's Verdict(0.00), Wake of Ashes(1.11), Templar's Verdict(2.21)

### Error Messages (Link)

No error

**Comment by Hekili** [comment]
Are those macros?

**Comment by Narzogg** [comment]
no, these are not macros.

**Comment by Hekili** [comment]
Will be fixed in next release.
