### ISSUE TITLE
[REC] [REC] when will the mage be added again ?

### ISSUE THREAD

**Issue by Leftboy96** [Hekili/hekili#3408]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Unfortunately, since the pre-patch Hekili is no longer available for my mage

### How to Reproduce

Mager Issue
![Screenshot 2024-07-27 211212](https://github.com/user-attachments/assets/4d13c9b9-ff63-45a9-bdf0-6620459150eb)

### Snapshot (Link)

https://pastebin.com/

**Comment by syrifgit** [comment]
It will be added when it gets finished: https://github.com/Hekili/hekili/issues/3380
