### ISSUE TITLE
[BUG] Marksmanship Hunter Bag Icon in rotation upon targeting

### ISSUE THREAD

**Issue by Brdrker** [Hekili/hekili#3409]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Using WowHead pre-release (live) build for a single target marksmanship hunter. Before targeting a Raider's Training dummy, the rotation shows:

Hunter's Mark | Aimed Shot | Rapid Fire

After I target the dummy, the rotation shows:

Hunter's Mark | Red Bag with green tie thread | Aimed Shot

I've searched for such an icon in the spellbook for the hunter and I cannot find it. As I have seen (on my Balance Druid) a false indicator for a current spell on the non-primary bar. This may be a similar issue. Pictures (pre and post select) attached.

![01_Hekili_preselect](https://github.com/user-attachments/assets/b4c634be-2464-4c87-857b-375a27952441)
![02_Hekili_postselect](https://github.com/user-attachments/assets/32a17bd3-4dc9-483c-8756-53ccaf0d5ca6)

### How to Reproduce

1. Enter game as Level 70 Marksmanship Hunter in Org.
2. Go to Raider's Training Dummy
3. Face dummy (look at 3 action indicators.
4. Select dummy (look at 3 action indicators.

### Player Information (Link)

None

### Error Messages (Link)

None

### Additional Information

 Opened Issue Reporting (Snapshots) and there are no entries to select.

![03_Hekili_NoErrors](https://github.com/user-attachments/assets/a8a51a09-3553-499c-955e-63389b60611e)

I have provided my actual Discord name BUT I'm not in your discord. If you need an email addy: bgahl@bawcsa.org

### Contact Information

revtemerity

**Comment by Hekili** [comment]
It's your trinket.

**Comment by Brdrker** [comment]
Doh. Been away from the game way too long. Sorry for the bother.
