### ISSUE TITLE
[REC] Prot Pally "Shield of Righteous" recommended with not enough holy power

### ISSUE THREAD

**Issue by PopsGG** [Hekili/hekili#3411]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When going through the prot pally rotation on a AoE pull, eventually "Shield of Righteous" is recommended with less than 3 holy power. The spell requires 3 holy power.

### How to Reproduce

1. Log on to a prot pally
2. Fight the 5 "Cleave Training Dummy(s)" in Valdraken. This also happens in M+
3. Continue the rotation for about 1 to 2 minutes
4. Eventually "Shield of Righteous" is recommended with less than 3 holy power.
5. It will not switch to another recommendation

### Snapshot (Link)

https://pastebin.com/qVgvJd1Q

**Comment by Hekili** [comment]
This will be resolved in 0.9.1b.
