### ISSUE TITLE
DEMO - Grimoire & Tyrant not being recommended after casting Gloomhound/Vilefiend

### ISSUE THREAD

**Issue by BoooBooo69** [Hekili/hekili#3413]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hi, So following the recommendations is fine for standard rotation however, when Gloomhound is showing as a priority the next 2 casts after are Dreadstalkers and then Felguard, but when Vilefiend/Gloomhound is cast the recommendations instantly swap to Hand of Guldan and CD's disappear. This causes a loop of never casting cooldowns, if i take over and cast them myself then cooldowns begin to show but like another ticket states it doesn't recommend Vilefiend/Gloomhound or Tyrant for the 2nd mini window. 

### How to Reproduce

1. Enter game as Demo lock.
2. Take Felguard, Vilefiend and Gloomhound Talents
3. Follow Hekili priority list

### Snapshot (Link)

https://pastebin.com/pTTs6vST

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vv6rYtQVnqcLWXGPH1mTZM

### Additional Information

Added the sim but it just suggests shadow bolt spam. Think i have done the snapshot correctly, i tried to pause during the cast of Vilefiend/Gloomhound so the snap grabbed the change in prioritys. Hope you can help!

### Contact Information

Discord - BoooBooo69#0819

**Comment by Hekili** [comment]
> I tried to pause during the cast of Vilefiend/Gloomhound so the snap grabbed the change in prioritys. Hope you can help!

The snapshot recommends Call Dreadstalkers(0.39), Grimoire: Felguard(1.56), Hand of Gul'dan(2.72).

I would recommend taking two snapshots and linking each of them.  One when Vilefiend/Gloomhound is recommended, and one immediately after casting Vilefiend/Gloomhound (and recommendations have updated).

**Comment by Hekili** [comment]
I've worked out a solution for this; Charhound and Gloomhound will be detect as Vilefiend (`buff.vilefiend.up`) in 0.9.1b.
