### ISSUE TITLE
[BUG] Not showing on certain toons

### ISSUE THREAD

**Issue by DaveB1977** [Hekili/hekili#3414]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Pretty much per title, the addon IS loaded but will not show up on certaino characters, I thought it might be a favourites thing but this made no difference, neither did deletibng the default profile and starting again. When in settings I can see the placement of the bars but exiting settings the area goes back to blank. 

### How to Reproduce

Enter the game. Nothing else I did. 

### Player Information (Link)

not available

### Error Messages (Link)

not available

**Comment by DaveB1977** [comment]
To add, I had someone else download and install, they're getting the same issue with the helper only showing on certain characters.

**Comment by Zanetsuken** [comment]
You seem to have neglected to provide any useful info in your opening.

what characters, specs, and have you checked the pin to ensure the specs are currently supported

**Comment by DaveB1977** [comment]
> You seem to have neglected to provide any useful info in your opening.
> 
> what characters, specs, and have you checked the pin to ensure the specs are currently supported

It works on a ret pally & BM hunter (not checked other specs) , druid working (all specs) have tested on a mage (all specs) outlaw rogue, As I say, the addon IS loaded but is not displaying. 

I didn't see a pin about classes and specs so will check it now, I assumed an update would have been for all, that's my bad if this isn't the case, sorry. 

Edit: Looks I was lucky in selecting all the classes and specs you;ve not yet sorted, sucks to be me ><

**Comment by DaveB1977** [comment]
Yep, I'm an idiot. Also just seen another post that I'd missed stating the same, please close the ticket and sorry for wasting your time :(
