### ISSUE TITLE
[REC] Bloodthirst issue

### ISSUE THREAD

**Issue by Shamuraj** [Hekili/hekili#3415]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Eventhough Bloodthirst has a 3 sec cd in certaind situations (in my case mostly AoE m+ situations) after casting Bloodthirst it stays top 1 prio when BT is on cd. Similar situation to the Execute issue I reported a few days ago

### How to Reproduce

 Be fury. at some point te priority will remain Bloodthirst as #1 prio after jsut casating it eventhought its on cd.

### Snapshot (Link)

https://pastebin.com/bWYY0ZDM

**Comment by Hekili** [comment]
That does not appear to be the default priority.  `buff.BattleShout.down` is not correct syntax for the addon.  Revert this priority to default by clicking the circle arrow to the right of the Priority Name.

![image](https://github.com/user-attachments/assets/0af112e2-2c9b-4d35-8ec8-6f749de4df4d)

I'm not able to replicate this issue using the same talents that you're using; in the snapshot you provided, Bloodthirst does not appear to be on cooldown.

If it occurs again after reverting the priority, please provide a new snapshot taken while Bloodthirst is recommended and on cooldown at the same time.  By default, the addon would also create a screenshot and you could post both for confirmation.

**Comment by Shamuraj** [comment]
You are right, I forgot i added the BS  buff manually as it used to be that way before prepatch and i missed it. Maybe its somrthing you could add again as default. Unless im wrong and it was never default and i added it long time ago and forgot. Ill revert the changes and try again, the problem is it mosltly happens in m+ situations and since the BT cd is rly short its sometimes hard to see it and also manage to snapshot it with shift+alt+[. Ill try to catch it and repost.

**Comment by Shamuraj** [comment]
It was my fault as i had a failing castsequence macro with BT and slam, The addon is working as intended. Maybe You could at least add the battle shout buff. Thread ready to close.
