### ISSUE TITLE
[REC] Assassination: Deathmark, Echoing Reprimand and Thistle Tea not recommended at correct points

### ISSUE THREAD

**Issue by Skidsgames** [Hekili/hekili#3417]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

According to the APL and Simc ability log, the order of abilities on pull should be:

- Garrote
- Echoing Reprimand
- Rupture
- Slide and Dice
- Garrote
- Envenom
- Deathmark
- Shiv
- Kingsbane
- Thistle Tea

Hekili recommends:

- Garrote
- Mutilate
- Rupture
- Slide and Dice
- Garrote
- Envenom
- Shiv
- Kingsbane
- Mutilate
- Envenom
- Mutilate x3

Echoing Reprimand Snapshot: https://pastebin.com/ZJKBHHm0
Deathmark Snapshot: https://pastebin.com/ynGhhKxB
Thistle Tea Snapshot: https://pastebin.com/cvVCS3iE

### How to Reproduce

1. Enter game as Assa Rogue
2. Import the talents "CMQA27SZpS4XnmFfcXRqkppuwPjZmhZmxyMAAAAAAMbwyMAAAAAA022MzwDMzYMzMLz2YMGMzMzMzYmNbjZAAAAAAAA"
3. Start hitting a single target dummy

### Snapshot (Link)

Linked in description

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vDNgTQZEjR6UQUUBQt93Dt

**Comment by Hekili** [comment]
Per your snapshots:

```
toggles: cooldowns = false
...
62.  echoing_reprimand ( direct - 6 ) - ability disabled ( toggle cooldowns )
...
22.  deathmark ( cds - 5 ) - ability disabled ( toggle cooldowns )
...
29.  thistle_tea ( cds - 8 ) - ability disabled ( toggle cooldowns )
```

Enable your Cooldowns toggle.  Check the FAQ for more information.
