### ISSUE TITLE
Rogue/Assassination - Unable to make recommendation

### ISSUE THREAD

**Issue by 3ternalhunter** [Hekili/hekili#3418]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While doing the rotation on a single target dummy, I am getting the error "Unable to make recommendation for Primary #1; triggering auto-snapshot..."

It appears to happen at 7 combo points when there isn't enough energy to cast Envenom. When the error triggers, the suggestion windows disappears.

### How to Reproduce

1. Copy my talents
2. Follow the rotation
3. Make sure Garrote, Rupture, Trinkets, Tea, Kingsbane, Deathmark, Shiv, and Echoing Reprimand are either on CD or rolling and do not need to be refreshed.
4. You will eventually get the error when low on energy and capped at 7 combo points.

### Snapshot (Link)

https://pastebin.com/fRhbNC4y

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nCjD2j3hrSL3ZpxJ4dKSnw

**Comment by Hekili** [comment]
I think this will be addressed when I revise `cp_max_spend` in the next release.  When this happens, it's holding out for Envenom but the action list logic won't allow it.

```
        46.  envenom ( default - 9 )
        The action (envenom) is usable at (0.00 + 1.06) with cost of 35 energy (have 35).
         - the action is ready before the current recommendation (at +1.06 vs. +10.00).
         - this entry's criteria FAILS: buff.slice_and_dice.up[true] & buff.slice_and_dice.remains[47.61] < 5 & combo_points.current[7.00] >= 5
```

The above is intended to refresh Slice and Dice when its duration is low; did not apply in your case.

```
        57.  envenom ( direct - 1 )
        The action (envenom) is usable at (0.00 + 1.06) with cost of 35 energy (have 35).
         - the action is ready before the current recommendation (at +1.06 vs. +10.00).
        List ( direct ) called from ( Assassination:default:11 ) would PASS at 1.06.
        NONE
         - this entry's criteria FAILS: ! buff.darkest_night.up[false] & effective_combo_points[7.00] >= variable.effective_spend_cp[5.00] & ( variable.not_pooling[false] | debuff.amplifying_poison.stack[0.00] >= 20 | effective_combo_points[7.00] > cp_max_spend[7.00] | ! variable.single_target[true] ) & ! buff.vanish.up[false]
```

The above failed because `cp_max_spend` is 7, so `effective_combo_points` is not greater than 7.

```
        58.  envenom ( direct - 2 )
        The action (envenom) is usable at (0.00 + 1.06) with cost of 35 energy (have 35).
         - the action is ready before the current recommendation (at +1.06 vs. +10.00).
        List ( direct ) called from ( Assassination:default:11 ) would PASS at 1.06.
        NONE
         - this entry's criteria FAILS: buff.darkest_night.up[false] & effective_combo_points[7.00] >= cp_max_spend[7.00]
```

This entry requires a hero talent, which we don't have yet.

**Comment by Hekili** [comment]
Try v11.0.0-0.9.4a when it comes available and see if that works for you.

**Comment by 3ternalhunter** [comment]
This one appears to be fixed. While testing I've ran into two more bugs. I'll submit separate tickets. Thank you!
One appears to be with Slice and Dice with Vanish
The other I haven't pinned down, but it is another scenario where it is "unable to make a suggestion", this time under 7CP.
