### ISSUE TITLE
Rogue/Assassination - Slice and Dice A More Powerful Buff Active

### ISSUE THREAD

**Issue by 3ternalhunter** [Hekili/hekili#3419]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon is suggesting to use Slice and Dice right after vanishing while the buff is already active. Getting the error "A more powerful buff is active".

I have been able to reproduce twice and each time S&D had 50+ seconds remaining. After vanishing, It wanted to refresh S&D with only 2 combo points. The combo point was not effected by echoing reprimand. Both times it was on 2 combo points.

### How to Reproduce

1. Follow the rotation.
2. Have Slice and Dice above 50 seconds
3. with 2 combo points, use trinket Ashes of the Embersoul
4. Vanish
5. Addon suggests Slice and Dice (unable to refresh buff and stuck here)

### Snapshot (Link)

https://pastebin.com/A9mZ9RbX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nCjD2j3hrSL3ZpxJ4dKSnw

**Comment by Hekili** [comment]
Thanks, I will post an updated priority that doesn't recommend SnD outside of combat if it is not refreshable.
