### ISSUE TITLE
Unholy DK - Error When Checking Cooldowns

### ISSUE THREAD

**Issue by pltboom** [Hekili/hekili#342]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
**When I click "On" cooldowns for my unholy DK once the fight starts and I use cooldowns what to cast next goes blank, if unclick cooldowns the regular rotation shows back up again.**

**To Reproduce**
**Turn On cooldowns for unholy dk, start the fight and what to cast goes away and its blank, turn cooldowns off and the rotation is fine and shows what to cast.**

**Expected behavior**
**Show the rotation and deliver the rotation if I have cooldowns turned on the whole fight**

**Screenshots**
I didnt take a screen shot sorry
**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.
build: v8.3.0-04-21
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    bursting_sores
    epidemic
    grip_of_the_dead
    soul_reaper
    spell_eater
    unholy_frenzy

azerite: azerite_empowered = 3
    elemental_whirl = 1
    festermight = 2
    harrowing_decay = 1
    heed_my_call = 2
    helchains = 1
    impassive_visage = 1
    last_surprise = 1
    resounding_protection = 1
    vampiric_speed = 1

essences: [vision_of_perfection] = 3, breath_of_the_dying = 1, memory_of_lucid_dreams = 3, the_unbound_force = 1

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    heart_of_azeroth = 1
    malignant_leviathans_hauberk = 1
    malignant_leviathans_stompers = 1
    vial_of_animated_blood = 1

corruptions: surging_vitality = 2
    twisted_appendage = 1

itemIDs: 127490, 129876, 158075, 158555, 159411, 159423, 159433, 159457, 159625, 159638, 165679, 169223, 173455, 173837, 174258

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
I'm actually in the middle of cleaning some of this up in the latest beta branch.  I'd suggest trying the latest beta and adding to this report if you're still seeing this problem.

For what it's worth, not having a recommendation isn't technically an "error" -- it means that the addon's profile couldn't come up with a recommendation.  In the current release, that's because of how forecasting Festering Wound stacks from Unholy Frenzy is modeled.  The beta branch should work better and probably fixes this in 99% of situations.

**Comment by Hekili** [comment]
Closing this ticket; try the latest release and if you see this arise again, submit a new report (with a snapshot).
