### ISSUE TITLE
[REC] Shadow Priest, Mind Flay not recommended

### ISSUE THREAD

**Issue by MatteoLombardi** [Hekili/hekili#3421]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Doing a simple AoE rotation on dummies, both Mind Flay and Mind Flay:Insanity were never suggested. I had to force cast it cause the addon displayed a wait timer for devouring plague and mind blast (time that you would fill with either mind flay variant to generate insanity)

PS: I may have missed PI recommendation as well, super used to insta casting it with void form, that I don't recall it showing up

### How to Reproduce

1. Enter the game as spriest
2. Follow the rotation
3. Mind Flay doesn't show up

### Snapshot (Link)

https://pastebin.com/6ApXu4AD

**Comment by MatteoLombardi** [comment]
Apparently the game was weirdly bugged, a refresh after changing some ElvUI stuff "fixed" the rotation, mind flay works..

**Comment by Hekili** [comment]
Thanks.  I took a look at your snapshot and your Shadow priority did not match mine:

```
        Entry #20 in list ( main ) is not set or not enabled.  Skipping.
 
        Entry #21 in list ( main ) is not set or not enabled.  Skipping.
 
        Entry #22 in list ( main ) is not set or not enabled.  Skipping.
 
        Entry #23 in list ( main ) is not set or not enabled.  Skipping.
```

![image](https://github.com/user-attachments/assets/a8da1c49-ea7f-483a-aa03-68b2f05c2dcf)

It looks like you managed to trigger a refresh and now the `filler` list (which includes Mind Flay) is being used.

**Comment by MatteoLombardi** [comment]
I have no idea how that could have happened, but so did to my wife testing Unholy DK. In both cases a reload fixed it.
