### ISSUE TITLE
[BUG] ROG - Outlaw : no ambush in speelflash

### ISSUE THREAD

**Issue by Sepulheure** [Hekili/hekili#3422]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The rotation is done very well but despite the suggestion of ambush the spell is not in the spellflash

### How to Reproduce

1. Enter the game as an outlaw rogue
2. Activate spellflash everywhere
3. Follow the suggestions
4. Note that spellflash never turns on ambush even though the addon suggests it

### Snapshot (Link)

https://pastebin.com/45pqyBYz

**Comment by syrifgit** [comment]
Is your ambush a macro? If so you will need to manually set the keybind. Please see the FAQ for more info: https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#ui--display

Specifically the UI / Display section

**Comment by Sepulheure** [comment]
not a macro

In my action bars I tried with the spells in the bar then without (transformation of the pernicious attack) and it did not work. I will translate the link and read carefully and I will come back to explain what it is.

**Comment by syrifgit** [comment]
> not a macro
> 
> In my action bars I tried with the spells in the bar then without (transformation of the pernicious attack) and it did not work. I will translate the link and read carefully and I will come back to explain what it is.

If you go into the settings and manually set a keybind for Ambush, it will 99.9% work

**Comment by Sepulheure** [comment]
0.1% for me lol

![NoAmbush](https://github.com/user-attachments/assets/911e8609-6076-4390-bfb9-74aff3d258b4)

détect perfect but no flash in spell, i change keybind but nop, i have disabled elvui but nop

**Comment by Sepulheure** [comment]
Bug in addon SpellFlash ???

**Comment by Sedveth** [comment]
New stelath bugs on beta:
- if you cancel aura stealth you get subt now, same if you break with a trinket (I assume subt doesnt require the rogue to break it with a spell anymore)
- casting/channeling while in stealth will now break stealth 
- the first subt window that comes from stealth is fucked in a multitude of ways:
 - stance bar dont activate, nor [stealth] macros and you cannot use spells that require stealth
 - the dispatch from bte crackshot dont go off
 - if your first gcd to break stealth is bte it goes on cooldown
- and finally this new bug, if bte is on cd, you are in stealth, use a finisher (not bte), it will "reset" bte cd, but it wont actually be reset, you will be able to press bte, but it wont castr the spell, also this last kidna forever idk, its super long, you are stuck with a broken bte
- entering stealth riught as subterfuge expire will break stealth
- mounting a dragonriding mount while stealted sometimes doesnt activate dragonriding

The positive is that you can now cast trinkets from stealth which will no longer just break stealth, but will also give subterfuge

**Comment by syrifgit** [comment]
> 0.1% for me lol
> 
> ![NoAmbush](https://private-user-images.githubusercontent.com/176934616/353169141-911e8609-6076-4390-bfb9-74aff3d258b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzcyNDEsIm5iZiI6MTcyMjI3Njk0MSwicGF0aCI6Ii8xNzY5MzQ2MTYvMzUzMTY5MTQxLTkxMWU4NjA5LTYwNzYtNDM5MC1iZmI5LTc0YWZmM2QyNThiNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxODE1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzhlNWRlMGRjNGYzZmIyNjE4YzljYmI3ZDgxNmYwNzY5MzAyMDljMGQyZTgxYjRlZjQxZjU5MDEyYmNhOTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ifHpP_HrLgQVIQWNrXuKP5p26NiQA-Ehy5b3X2KmBeo)
> 
> détect perfect but no flash in spell, i change keybind but nop, i have disabled elvui but nop

Donnez-moi un capture de votre UI en incluant les action bars.

**Comment by syrifgit** [comment]
> New stelath bugs on beta:
> 
> * if you cancel aura stealth you get subt now, same if you break with a trinket (I assume subt doesnt require the rogue to break it with a spell anymore)
> * casting/channeling while in stealth will now break stealth
> * the first subt window that comes from stealth is fucked in a multitude of ways:
> * stance bar dont activate, nor [stealth] macros and you cannot use spells that require stealth
> * the dispatch from bte crackshot dont go off
> * if your first gcd to break stealth is bte it goes on cooldown
> * and finally this new bug, if bte is on cd, you are in stealth, use a finisher (not bte), it will "reset" bte cd, but it wont actually be reset, you will be able to press bte, but it wont castr the spell, also this last kidna forever idk, its super long, you are stuck with a broken bte
> * entering stealth riught as subterfuge expire will break stealth
> * mounting a dragonriding mount while stealted sometimes doesnt activate dragonriding
> 
> The positive is that you can now cast trinkets from stealth which will no longer just break stealth, but will also give subterfuge

None if this is relevant to the Spellflash not showing on Ambush on live servers and this is not the Github for World of Warcraft so we wouldn't be able to do anything. You can submit a bug report on the World of Warcraft forums. This is for the Hekili Addon.

**Comment by Sepulheure** [comment]
https://github.com/user-attachments/assets/60fe2b51-f96e-41f3-a580-628737f7d474

**Comment by syrifgit** [comment]
un photo claire de ça svp? 
![image](https://github.com/user-attachments/assets/83f38937-f2f3-4f49-ba84-0fd36e04e750)

**Comment by Sepulheure** [comment]
![NoAmbushh](https://github.com/user-attachments/assets/d633a0b1-b081-4088-a3cd-9493f069115a)

**Comment by syrifgit** [comment]
> > 0.1% for me lol
> > ![NoAmbush](https://private-user-images.githubusercontent.com/176934616/353169141-911e8609-6076-4390-bfb9-74aff3d258b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzcyNDEsIm5iZiI6MTcyMjI3Njk0MSwicGF0aCI6Ii8xNzY5MzQ2MTYvMzUzMTY5MTQxLTkxMWU4NjA5LTYwNzYtNDM5MC1iZmI5LTc0YWZmM2QyNThiNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxODE1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzhlNWRlMGRjNGYzZmIyNjE4YzljYmI3ZDgxNmYwNzY5MzAyMDljMGQyZTgxYjRlZjQxZjU5MDEyYmNhOTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ifHpP_HrLgQVIQWNrXuKP5p26NiQA-Ehy5b3X2KmBeo)
> > détect perfect but no flash in spell, i change keybind but nop, i have disabled elvui but nop
> 
> Donnez-moi un capture de votre UI en incluant les action bars.

ok donc ici il faut metter "7" pour le keybind, pas "è". Il doit être le même que votre action bar

**Comment by Mike160770** [comment]
> Bug in addon SpellFlash ???

10x ...AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:66: attempt to call global 'GetSpellSubtext' (a nil value)
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua"]:66: in function `SpellName'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua"]:190: in function <...AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua:189>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Interface/AddOns/Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:35: in function <.../Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua:31>
[string "=[C]"]: in function `accessor'
[string "@Interface/AddOns/Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:52: in function `AddCallback'
[string "@Interface/AddOns/Blizzard_ObjectAPI/Mainline/Spell.lua"]:63: in function `ContinueOnSpellLoad'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/SpellFlashCore.lua"]:189: in function `Function'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua"]:35: in function `OnUpdate'
[string "@Interface/AddOns/Hekili/Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua"]:19: in function <...Libs/SpellFlashCore/libs/BigLibTimer/BigLibTimer.lua:19>

Locals:
GlobalSpellID = 6603
NoSubName = nil
SpellName = "Automatischer Angriff"
(*temporary) = nil
(*temporary) = 6603
(*temporary) = "attempt to call global 'GetSpellSubtext' (a nil value)"

**Comment by Sepulheure** [comment]
7 in shorthand was my first test, then I tried with è but nothing

**Comment by Sepulheure** [comment]
Disabling ALL addons and applying shortcut 7 as in my action bar does not solve the problem. I think more about the fact that the spell is basically the pernicious attack but even if I put the ambush spell alone in the action bar it does not work either. I do not see why the hekili rotation perfectly offers the spell and that the glow does not appear on that one only.

**Comment by Hekili** [comment]
I'm not sure what all of this means but I think SpellFlash will be fixed in v11.0.0-0.9.6.

**Comment by Sepulheure** [comment]
this version v11.0.0-0.9.7 fixed the problem

**Comment by Mike160770** [comment]
> this version v11.0.0-0.9.7 fixed the problem

Does it work with macros too? Btw thx for your efforts! Keep up the great work!
