### ISSUE TITLE
FIRE MAGE, CATA, NOT WORKING, NO SPELLS SHOWING IN "AUTOBAR/SINGLE/EXT"

### ISSUE THREAD

**Issue by VINNY101ST** [Hekili/hekili#3423]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not working for my Firemage on cata classic, the box were the spells usually pop up are not there, and it wont let me select a "firemage" priority inside the addon in game.

Thank you, Vinny 

build: v4.4.0-0.9.0
level: 85 (85)
class: MAGE
spec: mage

talents: blast_wave
    burning_soul
    cauterize
    combustion
    critical_mass
    dragons_breath
    fire_power
    firestarter
    hot_streak
    ignite
    impact
    improved_flamestrike
    improved_hot_streak
    improved_scorch
    living_bomb
    master_of_elements
    molten_fury
    netherwind_presence
    piercing_ice
    pyromaniac

pvptalents: none

covenant: none

conduits: none

soulbinds: none

sets: none

gear: beautys_favorite_bone = 1
    darkmoon_card_volcano = 1
    dizzes_whirling_robe = 1
    dolomite_adorned_gloves = 1
    dreamless_belt = 1
    emberfire_cowl = 1
    emberfire_pants = 1
    fireetched_dagger = 1
    mainhand = 1
    mantle_of_master_cho = 1
    melodious_slippers = 1
    ring_of_frozen_rain = 1
    rose_quartz_band = 1
    sand_silk_wristband = 1
    stonebinders_cloak = 1
    string_of_beaded_bubbles = 1
    tabard_of_ramkahen = 1
    tendrils_of_burrowing_dark = 1
    wand_of_dark_worship = 1

legendaries: none

itemIDs: 54496, 54498, 54503, 55045, 55823, 55866, 55876, 56306, 56331, 56333, 56339, 56373, 57933, 58485, 61473, 62047, 65904, 67133

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcd = 1459
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    petbased = false
    potion = potion_of_speed
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    arcane = Arcane Wowhead
    fire = Fire Wowhead
    frost = Frost Wowhead
    living_bomb_cap = 3
    spellsteal_cooldown = 1
    use_cold_snap = false

toggles:     cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    arcane_brilliance = SF  [01]
    blast_wave        = S2  [06]
    blink             = M3  [06]
    combustion        = R   [06]
    counterspell      = F   [06]
    dragons_breath    = C   [01]
    evocation         = S4  [06]
    fire_blast        = 4   [01]
    fireball          = M5  [06]
    flamestrike       = X   [01]
    ice_block         = SC  [01]
    living_bomb       = 1   [01]
    mage_ward         = SR  [01]
    mirror_image      = V   [01]
    pyroblast         = M4  [06]
    replenish_mana    = SG  [06]
    scorch            = 3   [01]

### How to Reproduce

The addon is not working for my Firemage on cata classic, the box were the spells usually pop up are not there, and it wont let me select a "firemage" priority inside the addon in game.

Thank you, Vinny 

### Player Information (Link)

http://github.com/Hekili/hekili/issues

### Error Messages (Link)

http://github.com/Hekili/hekili/issues

### Contact Information

sebastianovinny@gmail.com

**Comment by Dawittewel** [comment]
Hey, Same issue, for fire mage its not showing anything.

**Comment by Nepralido** [comment]
J'ai exactement le même probleme , aucune rotation affiché

**Comment by plugGG333** [comment]
Did you fix it?

**Comment by Nepralido** [comment]
its not fixed ....

**Comment by plugGG333** [comment]
so bad

**Comment by Ralamadudt** [comment]
From what i could gather, it seems the spell-ids are messed up, in the mage.lua

**Comment by Nepralido** [comment]
> D'après ce que j'ai pu comprendre, il semble que les identifiants des sorts soient erronés dans le mage.lua

pense tu que ils vont le corriger prochainement ?

**Comment by Ralamadudt** [comment]
> > D'après ce que j'ai pu comprendre, il semble que les identifiants des sorts soient erronés dans le mage.lua
> 
> pense tu que ils vont le corriger prochainement ?

Can't say for sure since they are busy with prepatch of TWW, but i have made it work for myself by manually updating the spell-ids, but there isn't really any guides either since it's not working.

**Comment by Nepralido** [comment]
> > > D'après ce que j'ai pu comprendre, il semble que les identifiants des sorts soient erronés dans le mage.lua
> > 
> > 
> > pense tu que ils vont le corriger prochainement ?
> 
> Je ne peux pas le dire avec certitude car ils sont occupés avec le pré-patch de TWW, mais j'ai réussi à le faire fonctionner moi-même en mettant à jour manuellement les identifiants de sorts, mais il n'y a pas vraiment de guides non plus car cela ne fonctionne pas.

comment as tu fais ?

**Comment by Supernuss** [comment]
Please consult the discord first, next time. Mage has not been added to supported classes yet.

This Pull request adds Fire and Arcane Mage: https://github.com/Hekili/hekili/pull/3508
Changes will go live with the next CF release.

**Comment by Hekili** [comment]
Fire Mage should be available in the latest cataclysm releases.
