### ISSUE TITLE
[REC] OL Rogue: BtE and Manic Grieftorch not recommended

### ISSUE THREAD

**Issue by Akr0n** [Hekili/hekili#3425]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As stated in the title: Between The Eyes is not recommended because, as of latest addon build, is not listed in any section (by default it says "none" (see screenshot). Tried to fix it by selecting "Cooldowns" from the drop down menu but it gets suggested only at the start. For the Torch... never gest recommended, and no, I didn't disable it from the options.
![image](https://github.com/user-attachments/assets/4513bcd0-8f60-4eeb-ba56-99ede6b85ba4)

### How to Reproduce

1 - enter the game as an OL rogue
2 - go to the dummy and start smashing it
3 - BtE not suggested
4 - Torch never recommended

### Snapshot (Link)

https://pastebin.com/wb7vyHif

### Contact Information

Akr0n (Discord)

**Comment by Hekili** [comment]
Snapshot was taken out of combat with no Combo Points.  it needs to be taken when you'd expect Between the Eyes (or Manic Grieftorch) to be used.  Also, your trinket is on cooldown for 90 seconds.
