### ISSUE TITLE
Guardian druid, no Renewal, Survival Instincts on cooldown, no Skull Bash, drops Thrash

### ISSUE THREAD

**Issue by BIOROGUE** [Hekili/hekili#3426]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Guardian druid, before the 11.0 changes, renewal was recommended with a higher priority than frenzied regeneration, now it's never recommended.
Survival instincts on the other hand is recommended on CD (even back to back if i have 2 stacks)
Also it feels like thrash is dropped from time to time (especially in big packs)
Also, kick (skull bash) is never recommended, even though "interrupts" are enabled in options

### How to Reproduce

Enter game as guardien druid
 
1.1 Spec into Survival Instincts / Improved Survival Instincts
1.2 Pull a pack that damages you (I pulled first mob in normal RLP on normal difficulty to test)
1.3 See recommendations

2.1 Spec into Skull Bash
2.2 Engage a kickable mob (I used normal RLP again for a "Flashfrost Spellweaver"
2.3 See recommendations

3.1 Spec into Renewal
3.2 trusty RLP again Mythic 0 this time, i pulled the first corridor
3.3 Get low HP without Frenzied Regeneration charges
3.4 See recommendations

4.1 For the Thrash drops i pulled the first corridor in RLP (21 mobs on tracker)
4.2 See Recommendations

### Snapshot (Link)

https://pastebin.com/WCZRv6vL

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ooTrTWHAGBgbGEGBcY7L9j

### Additional Information

https://www.warcraftlogs.com/reports/3mDaNB7L96rnzdQw
log, if that helps anything

https://pastebin.com/T5h7dy5C
no kick snapshot

https://pastebin.com/vHBzG8c0
no thrash snapshot

CgGAqvgeoHLefPLb/Pa8nkKXDBAAAAAAAAAAAAmZGzMmlhlZmZMmZhhZmFLAMGMzMT0MzMzMzYWgNGAAAAAAwMwAAAAAAAAAmZGA
talents (used for everythjing here)

sry if i forgot to provide stuff and thank you so very much for your work <3 you carry my whole wow experience

### Contact Information

discord: zauberauh

**Comment by Hekili** [comment]
I made a bunch of arbitrary changes to Guardian that will be available in v11.0.0-1.0.0.
