### ISSUE TITLE
BM Hunter - Tranq shot not displaying in que when needed

### ISSUE THREAD

**Issue by luke0230** [Hekili/hekili#3427]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

BM Hunter - Tranq shot not displaying in que when needed

### How to Reproduce

Run any dungeon with bossess that need tranq shot

### Player Information (Link)

don't know how to do this

### Error Messages (Link)

sry dont know this

### Additional Information

BM Hunter - Tranq shot not displaying in que when needed

### Contact Information

lukaszmonka@me.com

**Comment by syrifgit** [comment]
Please check the ticket instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue

**Comment by Hekili** [comment]
This will be fixed in the next release.
