### ISSUE TITLE
[REC] AFFLICTION: Summon Darkglare recommended only at the start of the aoe rotation

### ISSUE THREAD

**Issue by Akr0n** [Hekili/hekili#3431]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Summon Darkglare is suggested only at the start of the aoe rotation. After CD is off it never gets suggested again.

### How to Reproduce

1 - log in as an Affli lock
2 - start your aoe rotation at the cleave dummies
3 - cast Summon Darkglare when suggested
4 - after finished cd Summon Darkglare never gets suggested again

### Snapshot (Link)

https://pastebin.com/XkARsSHd

### Contact Information

Akr0n (Discord)

**Comment by Hekili** [comment]
At the point you snapshotted, it's waiting for Vile Taint to come off cooldown / be applied before using Summon Darkglare.  Can you take another snapshot when you've cast Vile Taint and the dot is ticking, but Summon Darkglare is not recommended?

**Comment by Akr0n** [comment]
U're right, VT must be applied then the addon suggest Darkglare. Thanks and sorry for bothering.
