### ISSUE TITLE
Aff seems to get caught in shadow bolt spam loop

### ISSUE THREAD

**Issue by illum1n471** [Hekili/hekili#3432]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I noticed while running Amirdrassil as Aff, that I would get stuck in shadow bolt spam loops that were 45-90 seconds long. It didn't matter how many shards I had, or what I had off CD, it would just keep suggesting shadow bolt.

### How to Reproduce

1. Play as Aff Lock.
2. Start normal rotation.
3. Cast all usable DoTs.
4. Issue begins.

### Snapshot (Link)

https://pastebin.com/LquQrPLR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8TyMkxaG2smrxtFrom7xmB

### Additional Information

Upon running the sim, I'm not sure that it will be of much help with this issue. Might just be something we have to wait for TWW to fix.

### Contact Information

1llum1n471

**Comment by Zanetsuken** [comment]
Last I checked new Warlock Sim APLs were not out. 
Warlock is currently using the DF S4 priority which causes issues with the changes to talent trees

**Comment by Hekili** [comment]
`453206 - shadow_embrace_1                         -   2 - 15.12`

Looks like there is a new spell ID for the Shadow Embrace aura, so it's trying to stack it up but is not detected as `shadow_embrace` -- will be addressed in the next release.

**Comment by Wedelgreen** [comment]
still the same problem, i do think its because shadowbolt only needs 2 stacks, while with drain soul it stack up till 4.

**Comment by Hekili** [comment]
I'll need a new snapshot.

**Comment by Hekili** [comment]
[pastebin.com/UGMY4qmd](https://pastebin.com/UGMY4qmd)

**Comment by Hekili** [comment]
Note:  The snapshot should be taken when the "shadow bolt spam loop" is happening; what you've posted shows Haunt(0.00), Agony(1.15), Phantom Singularity(2.30).

**Comment by Wedelgreen** [comment]
Ah sorry about that guess i took the wrong one. 

i hope this is the right one https://pastebin.com/dHq44uQt

**Comment by Hekili** [comment]
Nope, you can tell by the first line of text.

**Comment by Wedelgreen** [comment]
think this is done right, else i dont know :/ 
i apply the dots - then just shadowbolt spam even with cds up its not using malefic rapture - it does want to reapply dots.  
https://pastebin.com/YAS55T2Z
https://pastebin.com/S3q1FyeX

**Comment by syrifgit** [comment]
Looks to me like it's still not adding up the Shadow's Embrace talent properly. Even after multiple shadow bolts it still thinks the enemy only has 1 stack

**Comment by Hekili** [comment]
Should be set in v11.0.0-1.0.0e.
