### ISSUE TITLE
[REC] Assassination rotation errors

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#3433]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I was just hitting dummies and after a while, rotation seems to went wrong, didnt recommend garrote or rupture or cooldown anymore. /Reload the game fix this bug.

### How to Reproduce

1. Enter a game as Assassination.
2. Hitting dummies, maybe afk after few rotations to restart the cycle.
3. Rotation seems mess up, no garrote, rupture, cooldown suggested.

### Snapshot (Link)

https://pastebin.com/5ERXLm5M

**Comment by Hekili** [comment]
I'll need the snapshot from the Primary display, but this is most likely because the target dummies have reached low health such that applying dots is no longer cost-effective in the priority.
