### ISSUE TITLE
[REC] Windwalker Abilities stop displaying when fighting multiple enemies

### ISSUE THREAD

**Issue by Atrom1810** [Hekili/hekili#3434]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Whenever I am playing my Windwalker and I am in combat with multiple enemies, the display suddenly stops showing abilities or only a single ability. Sometimes it reverts to showing three abilities again, for instance, if I press Tiger Palm or any other ability. As soon as there is only one target, the abilities display is back to normal.

I have display mode on automatic and the AoE Ability List enabled.

https://gyazo.com/8ba8267d39231721f982f8afc3e9162f <- short video of it happening

### How to Reproduce

1. Enter the game as Windwalker Monk
2. Go to AoE dummies and start attacking
3. See that ability display disappears or only shows 1 button

### Snapshot (Link)

https://pastebin.com/VYgzX9NY

### Contact Information

atrom

**Comment by Hekili** [comment]
This looks like a defect in the sim priority itself -- similar behavior occurs in a multi-target sim with your talent build.  I'll edit the priority to allow TP to be used in AOE without the Ordered Elements buff up.  This will be in next release.
