### ISSUE TITLE
[REC] Sin rogue recommending Mangic Grieftorch too early (in opener)

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3435]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sin Rogue recommending use of Manic Grieftorch (channelled trinket) as second action in snapshot even when Improved Garrote is talented, which uses up 6s of post-stealth and should be delayed til later (also due to ashes trinket being used).

Attached raidbots sim which waits til ~30s to use it.

### How to Reproduce

Be sin rogue with manic grieftorch equipped (maybe second on-use has to be ashes of embersoul?). Opener will have manic grieftorch as second action.

### Snapshot (Link)

https://pastebin.com/Pwqw4Grd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dj1QLJaa6i6dDF1BFHPVSW

**Comment by Hekili** [comment]
Looks like the trinket proc type detection has been broken for some time.  I'm putting in a test fix for 1.0.0d.
