### ISSUE TITLE
Affliction still caught in a shadowbolt loop. 

### ISSUE THREAD

**Issue by Wedelgreen** [Hekili/hekili#3438]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

you descriped it got a new ID. but thats still the case, i do think its because with drain soul it stack up till 4 and with shadowbolt its only 2 stacks. 

### How to Reproduce

you get your main dots up and then its just shadowbolt spam. 

if i play with drainsoul the problem doesn't appear. 

### Snapshot (Link)

https://pastebin.com/UGMY4qmd

**Comment by Hekili** [comment]
I'll add your snapshot to the existing ticket.
