### ISSUE TITLE
[BUG] Incorrect keybinds displaying

### ISSUE THREAD

**Issue by arcues198750** [Hekili/hekili#3439]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![WoWScrnShot_080224_173059](https://github.com/user-attachments/assets/4fdbca2e-088b-4fda-91b5-00de5ac901b8)
Incorrect key binds are displayed above the abilities. I have attempted to reset my profile and even tried a separate one but the key binds are still being displayed incorrectly and only for this character's key binds.

### How to Reproduce

1. Login to game as DK

### Player Information (Link)

https://pastebin.com/DyY7fpMP

### Error Messages (Link)

https://pastebin.com/s8FfdvFX

### Additional Information

This only appears on this one specific toon.

### Contact Information

arcues198750

**Comment by Hekili** [comment]
Here are all the detected keybinds per your snapshot:

```
keybinds: 
    abomination_limb     = SE  [01]
    algethar_puzzle_box  = S2  [06]
    ancestral_call       = SA  [02], S5  [06]
    antimagic_shell      = SX  [05]
    beacon_to_the_beyond = F   [02]
    blinding_sleet       = SA  [01]
    chains_of_ice        = A   [05]
    dark_command         = SE  [07]
    death_and_decay      = 4   [01]
    death_coil           = 4   [02], S4  [06]
    death_gate           = F4  [04]
    death_grip           = 5   [01]
    death_strike         = S3  [05]
    deaths_advance       = S`  [05]
    empower_rune_weapon  = 5   [02], SW  [06]
    frost_strike         = 3   [01]
    frostwyrms_fury      = S1  [06]
    glacial_advance      = 2   [02]
    healthstone          = F5  [04]
    howling_blast        = 1   [01]
    icebound_fortitude   = CX  [05]
    lichborne            = R   [05]
    mind_freeze          = F   [01]
    obliterate           = D   [05]
    pillar_of_frost      = `   [05]
    raise_ally           = CZ  [03]
    raise_dead           = 3   [02], SF  [06]
    remorseless_winter   = 1   [02], SQ  [06]
    soul_reaper          = 2   [01] 
```

Algethar Puzzle Box was detected as S2 on action bar 6.
Remorseless Winter was detected as 1 on action bar 2 and SQ on action bar 6.

If I had to guess, you have a hidden action bar 2 that has Death Coil, Empower Rune Weapon, Raise Dead, and Remorseless Winter on it.  Even though the bar is not displayed, the actions are on there so the keybinding is detected.

You can remove those actions from bar 2 or you can use /hekili > Abililties > *Ability Name* > Override Keybind Text to manually set the keybinding text you want to see.
