### ISSUE TITLE
Warrior - ability (rampage) use after charge returns error

### ISSUE THREAD

**Issue by ghostspeare** [Hekili/hekili#344]
Message: Interface\AddOns\Hekili\Classes\WarriorFury.lua:364: attempt to index local 'ability' (a nil value)
Time: Mon Apr 27 07:22:14 2020
Count: 5
Stack: Interface\AddOns\Hekili\Classes\WarriorFury.lua:364: attempt to index local 'ability' (a nil value)
[string "@Interface\AddOns\Hekili\Classes\WarriorFury.lua"]:364: in function <Interface\AddOns\Hekili\Classes\WarriorFury.lua:354>
[string "@Interface\AddOns\Hekili\Classes.lua"]:659: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:57: in function <Interface\AddOns\Hekili\Events.lua:51>

Locals: event = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1587990133.858000
subtype = "SPELL_CAST_SUCCESS"
_ = false
sourceGUID = "Player-3675-06DB7808"
sourceName = "Revandriel"
_ = 1297
_ = 0
destGUID = "Creature-0-3018-1642-39-125458-000026C821"
destName = "Gurubashi Thug"
destFlags = 68136
_ = 0
spellID = 126664
spellName = "Charge"
ability = nil
(*temporary) = <table> {
 execute = 1
 impending_victory = 1
 rampage = 1
 victory_rush = 1
 bloodthirst = 1
 storm_bolt = 1
 siegebreaker = 1
 furious_slash = 1
 raging_blow = 1
}
(*temporary) = nil
(*temporary) = "attempt to index local 'ability' (a nil value)"
state = <table> {
 SpendResources = <function> defined @Interface\AddOns\Hekili\State.lua:5389
 index = 4
 class = <table> {
 }
 putTrinketsOnCD = <function> defined @Interface\AddOns\Hekili\State.lua:4501
 role = <table> {
 }
 IsKnown = <function> defined @Interface\AddOns\Hekili\State.lua:5526
 forecastResources = <function> defined @Interface\AddOns\Hekili\State.lua:1087
 target = <table> {
 }
 stat = <table> {
 }
 safenum = <function> defined @Interface\AddOns\Hekili\State.lua:493
 floor = <function> defined =[C]:-1
 selectionTime = 1.027786
 essence = <table> {
 }
 selectedAction = "victory_rush"
 queue = <table> {
 }
 SetWhitelist = <function> defined @Interface\AddOns\Hekili\State.lua:5242
 holds = <table> {
 }
 resetting = false
 RemoveSpellEvents = <function> defined @Interface\AddOns\Hekili\State.lua:4616
 display = "Primary"
 UnitPower = <function> defined =[C]:-1
 removeStack = <function> defined @Interface\AddOns\Hekili\State.lua:813
 prev_off_gcd = <table> {
 }
 timeToInterrupt = <function> defined @Interface\AddOns\Hekili\State.lua:907
 applyDebuff = <function> defined @Interface\AddOns\Hekili\State.lua:830
 mainhand_speed = 2.467000
 IsUsableSpell = <function> defined =[C]:-1
 debuff = <table> {
 }
 PlayerBuffUp = <function> defined @Interface\AddOns\Hekili\State.lua:4480
 channelSpell = <function> defined @Interface\AddOns\Hekili\State.lua:973
 this_action = "impending_victory"
 gain = <function> defined @Interface\AddOns\Hekili\State.lua:1257
 removeBuff = <function> defined @Interface\AddOns\Hekili\State.lua:777
 TimeToReady = <function> defined @Interface\AddOns\Hekili\State.lua:5786
 reduceCooldown = <function> defined @Interface\AddOns\Hekili\State.lua:624
 iteration = 0
 setStance = <function> defined @Interface\AddOns\Hekili\State.lua:891
 setCooldown = <function> defined @Interface\AddOns\Hekili\State.lua:514
 varPaths = <table> {
 }
 args = <table> {
 }
 tinsert = <function> defined =[C]:-1
 AddToHistory = <function> defined @Interface\AddOns\Hekili\Events.lua:873
 SetConstraint = <function> defined @Interface\AddOns\Hekili\State.lua:5236
 active_enemies = 1
 buff = <table> {
 }
 SetupCycle = <function> defined @Interface\AddOns\Hekili\State.lua:642
 scriptID = "Fury:single_target:12"
 print = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:116
 encounterName = "None"
 remove = <function> defined =[C]:-1
 ClashOffset = <function> defined @Interface\AddOns\Hekili\State.lua:5973
 table = <table> {
 }
 spell_targets = <table> {
 }
 spend = <function> defined @Interface\AddOns\Hekili\State.lua:1270
 IsInFlight = <function> defined @Interface\AddOns\Hekili\State.lua:4752
 tostring = <function> defined =[C]:-1
 summonPet = <function> defined @Interface\AddOns\Hekili\State.lua:916
 QueuedCastRemains = <function> defined @Interface\AddOn

**Comment by ghostspeare** [comment]
v8.3.0-04-21 does not reproduce this error

**Comment by Hekili** [comment]
And your Issue Reporting tab info?

**Comment by Hekili** [comment]
Posting a new release w/ this fixed.  Thanks for the report.  A friendly reminder:  I really do need all the information included in the issue template.
