### ISSUE TITLE
[REC] Holy Paladin - Shield of the Righteous

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3442]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Because the awakening talent has been changed, SoTR can be cast in single target. All holy power spenders build stacks of awakening which procs wings at 12 stacks by casting judgment. Also means we probably want a higher-up judgment with the 12 stacks condition attached to it?

APL line `actions.spenders+=/shield_of_the_righteous,if=!talent.awakening|active_enemies>1`
should become
`actions.spenders+=/shield_of_the_righteous`

Not sure what to do about the WoG and LoD lines, but I may look at it when I do a quick pass on healers.

Relevant discussion: https://discord.com/channels/307520968895627264/307520968895627264/1269537323079434312

### How to Reproduce

play da game

### Snapshot (Link)

https://pastebin.com/4xmf3gMX

### Contact Information

Syrif

**Comment by Hekili** [comment]
I made adjustments for this in v11.0.0-1.0.1.
