### ISSUE TITLE
[BUG] Spellflash dont blink

### ISSUE THREAD

**Issue by budesaal** [Hekili/hekili#3443]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I activate Spellflash with blink function. But blink function dont work.

### How to Reproduce

It dont work with all Classes.

### Player Information (Link)

no text

### Error Messages (Link)

https://pastebin.com/wHafzKMr

### Additional Information

https://pastebin.com/59PSVUKa

### Contact Information

no

**Comment by syrifgit** [comment]
That's not a snapshot, follow these instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

We will be able to see your settings, addon version, etc.

**Comment by Hekili** [comment]
If you have SpellFlash (or SpellFlashCore) installed as a separate addon, remove it.
