### ISSUE TITLE
[Bug] Rebuke showing in main priority queue instead of interrupt

### ISSUE THREAD

**Issue by RussellAnas** [Hekili/hekili#3444]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Retribution Paladin, Rebuke is appearing in main priority queue instead of the interrupts section.

### How to Reproduce

1. Enter game as Retri Pala
2. Fight an add with cast
3. Rebuke comes in main priority queue

### Snapshot (Link)

https://pastebin.com/34U2CJrn

**Comment by Hekili** [comment]
You can manually flag Rebuke for the Interrupts toggle in /hekili > Abilities > Require Toggle.

It will be addressed in a future update, too.
