### ISSUE TITLE
[BUG] Recommended spell not available anywhere

### ISSUE THREAD

**Issue by xxromaasxx** [Hekili/hekili#3445]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![Screenshot 2024-08-05 034555](https://github.com/user-attachments/assets/5920d5d8-f2ff-48d0-86a1-e8f95a41149b)
This spell is nowhere in my spellbook or on my talent trees. I cant even figure out what spell its supposed to be?

### How to Reproduce

1. Enter game as Demonology Warlock.
2. Start fighting something

### Player Information (Link)

https://pastebin.com/e4HLE98q

### Error Messages (Link)

https://pastebin.com/e4HLE98q

### Contact Information

rossasbill@gmail.com

**Comment by syrifgit** [comment]
That is your trinket, I recommend checking out the FAQ: https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions

**Comment by xxromaasxx** [comment]
Thank you
