### ISSUE TITLE
Arcane Mage - Recommendations not showing (for Arcane Blast) when Presense of Mind is activated

### ISSUE THREAD

**Issue by TMRaven85** [Hekili/hekili#3447]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Every time I click on Presence of Mind, the recommendations go away. It's supposed to show Arcane Blast, as the next two Arcane Blast spells are free, but  it isn't continuing the recommendations until I throw two Arcane Blasts myself, in which the recommendations continue. 

Sorry for the extra desktop part of the pictures, I guess screenshots in a windowed fullscreen takes extra screen info.

Here before rotation
![image](https://github.com/user-attachments/assets/da7fbd3c-8e43-4b74-acdf-30ba2d0b7117)

Here after clicking Presence of Mind
![image](https://github.com/user-attachments/assets/915d64b0-f74c-48f0-a723-9432a444cae9)

Mid rotation showing Arcane Blast
![image](https://github.com/user-attachments/assets/41e6c8b7-215c-486f-94b1-aa13c70c5975)

Presence of Mind showing in recommended
![image](https://github.com/user-attachments/assets/49c66285-5af2-44ae-89c4-472ac99f7c75)

Nothing after Presence of Mind activated
![image](https://github.com/user-attachments/assets/65a08cb6-a71d-4db4-9259-557e5524232c)

Presence of Mind showing with a red x after 1 Arcane Blast is cast
![image](https://github.com/user-attachments/assets/a527c047-3ba0-48ec-b8dd-40c87d635e2c)

The Arcane Blast spell is showing up in normal rotations, and such this is only when Presence of Mind is activated. 
I've tested a few ways to find the problem on a target dummy, and also seen the Presence of Mind with an red x on after throwing 1 Arcane Blast. 

### How to Reproduce

1. Enter game as arcane mage
2. Have talent Presence of Mind
3. Activate Presence of Mind and look at recommended spell dissapear
4. Cast Arcane Blast and wait, see recommended show Presence of Mind with a red x
5. Cast second Arcane Blast or remove Presence of Mind to get normal rotation back. 

### Snapshot (Link)

https://pastebin.com/PZ4jMb3t

**Comment by Hekili** [comment]
> 4. Cast Arcane Blast and wait, see recommended show Presence of Mind with a red x

That means to cancel Presence of Mind.  Which definitely feels weird, but is explicitly written into the sim.  I'll take a look at it, but you may want to go to /hekili > Priorities > Arcane > Action Lists > `cd_opener` and disable entries 3 and 4 in the meantime.
