### ISSUE TITLE
[REC] Beacon of Light recommended when not talented

### ISSUE THREAD

**Issue by Thornic** [Hekili/hekili#3449]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On holy paladin hekili recommends casting Beacon of Light at the start of a fight, when Beacon of Virtue (which replaces Beacon of Light)  is talented

### How to Reproduce

1. Enter the game as a Holy Paladin
2. Talent Beacon of Virtue (bottom left side of spec tree)

### Snapshot (Link)

https://pastebin.com/xcBn4TDb

### Contact Information

Discord: Tornic.

**Comment by akaRaven** [comment]
I get the opposite, getting recommended to use Beacon of Virtue even when I don't have it talented as I use the double Beacon of Light. Seems like it is just asking us to use both, which is not possible.

**Comment by Myntha** [comment]
same as above

**Comment by Hekili** [comment]
This will be resolved next release.
