### ISSUE TITLE
Low Level Warrior (Unsupported)

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#345]
Hekili works great on all characters, expect one Blood Elf Warrior. Hekili randomly disappears, appear, showing random number of skills in rotation. 
Tested on orc warrior lv 1 and everything works, only one this specific one character I have problem. 

Video: youtube.com/watch?v=rF5ZaKs1c2w&feature=youtu.be

build: v8.3.0-04-22.02
level: 1 (1)
class: WARRIOR
spec: arms

talents: none

azerite: none

essences: none*, none

sets/legendaries/artifacts: none

gear: battleworn_claymore = 1
    recruits_boots = 1
    recruits_pants = 1
    recruits_tunic = 1

corruptions: none

itemIDs: 20902, 20903, 20904, 23346

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Arms
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by mati3464** [comment]
Created another warrior Blod Elf and problem showed again, on other races everything working as supposed to be. I think, its problem with Blood Elf Warrior.

**Comment by Hekili** [comment]
Level 1 isn't supported in general. Posting a snapshot (per the instructions in the original ticket) is how you'd show me the addon's decision-making.

**Comment by Hekili** [comment]
I made a level 1 Orc Warrior and a level 1 Blood Elf Warrior and they behave similarly.  I only have Slam as an active ability, and Rage isn't modeled until you have something to do that starts combat.  Kinda funny, really.

**Comment by raggis87** [comment]
I believe it is related to Arcane Torrent.  I have been noticing this the last few days on my 120 Blood Elf DK.  If I have cooldowns enabled it will disappear until I use Arcane Torrent.

**Comment by Hekili** [comment]
Update and see if it's doing it.  I didn't find any issues for the low level Warriors in this report.  DK had another issue that should be resolved as of yesterday.

**Comment by Hekili** [comment]
@mati3464 In your video, the only ability you really have is Slam and Slam relies on having Rage.  There're no forecasted Rage gains for you because you're not in range and hitting a target to generate anything (and incoming damage Rage isn't forecasted).
