### ISSUE TITLE
Windwalker problem. Dont show Chi Burst and Touch of karma

### ISSUE THREAD

**Issue by wolkenfrei** [Hekili/hekili#3452]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [x] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Chi Burst and Touch of Karma dont show in my primary rotation. hooks are set in settings

### How to Reproduce

every time reproduce

### Snapshot (Link)

https://pastebin.com/SuEv5LbN

### Additional Information

[Windwalker; Primary - snapshot.txt](https://github.com/user-attachments/files/16551984/Windwalker.Primary.-.snapshot.txt)

### Contact Information

wolkenfrei#6677

**Comment by wolkenfrei** [comment]
It doesn't matter whether I run M+ or raids. Chi Burst and Touch of Karma are not displayed in the priority list. The settings are set correctly, but unfortunately it is not displayed.

**Comment by Hekili** [comment]
This will be resolved next release.
