### ISSUE TITLE
[BUG] Spellflash does not display on Dominos action bars beyond 1&2

### ISSUE THREAD

**Issue by superwario15** [Hekili/hekili#3454]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When spellflash is enabled, it displays normally on any abilities that are bound to Dominos action bars 1 or 2, however, if an ability is bound to any bar other than those 2, it does not display.

I have attached images to indicate the issue. The first image image shows my current bindings, and the ability I'm using as the example is Deathmark which is currently bound to Dominos action bar 6.

![WoWScrnShot_080824_134906](https://github.com/user-attachments/assets/f62c102b-aecb-4082-8125-4b078062bf40)

The next image shows the correct behavior when I just bind Deathmark to Dominos action bar 1

![WoWScrnShot_080824_134943](https://github.com/user-attachments/assets/9784f1f7-e0c3-44a2-a02e-28d41933f3e5)

I have confirmed this issue seems to be class-independent and occurs on every character I have.

### How to Reproduce

1. Enter game using Dominos and Hekili addons.
2. Enable spellflash for Hekili recommendations.
3. Bind an ability to be recommended on any action bar that is not 1 or 2.
4. Begin combat rotation.

### Player Information (Link)

https://pastebin.com/raZxZUmK

### Error Messages (Link)

No error messages.

**Comment by Hekili** [comment]
Do you have SpellFlashCore installed separately from the addon, or are you using the one that's included in it?

**Comment by superwario15** [comment]
I do not have SpellFlash installed separately; I'm just using SpellFlashCore that is included with Hekili.

**Comment by ozoxchris** [comment]
I can confirm I'm having this issue as well with the most current version of Dominos. I have only Hekili installed with its built in version of Spellflash.

Moreover, I disabled Dominos and Spellflash works with the default blizzard actionbars.

**Comment by NoShotz** [comment]
That explains so much, I was going insane trying to figure out why my so many of my spells refused to flash. Literally all of my non damaging spells are on bar 3 or 4, and they will not flash.

![image](https://github.com/user-attachments/assets/9349885d-ce5c-49f8-b864-45cdfeac58a8)

**Comment by NoShotz** [comment]
I think I may have found some info that may be of use for solving the issue,  bars 3 and onwards have a frame name like so, 
![image](https://github.com/user-attachments/assets/fa3c4bfe-0b5c-48ba-89a6-66b0e35d1303)

But bars 1 and 2 have a frame name like so,

![image](https://github.com/user-attachments/assets/bb18a957-5ff2-48f3-8a4f-02dc96e8eb60)

**Comment by Tuller** [comment]
I've not delved into the code of this addon, but if you want to apply custom behavior to action buttons derived from the stock Blizzard templates, I'd do something like this:

```lua
-- register known action buttons
for _, button in pairs(ActionBarButtonEventsFrame.frames) do
    registerActionButton(button)
end

-- and watch for any additional action buttons
hooksecurefunc(ActionBarButtonEventsFrame, "RegisterFrame", function(_, button)
    registerActionButton(button)
end)
```

**Comment by NoShotz** [comment]
Hopefully this can be fixed sooner rather than later.

**Comment by Hekili** [comment]
Taking a shot in the dark in 1.0.15 to address this.

**Comment by Hekili** [comment]
*1.0.14 -- this should now be resolved.
