### ISSUE TITLE
Survival Hunter ST Recommendation Not Working

### ISSUE THREAD

**Issue by Hesparax** [Hekili/hekili#3455]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On single target as a SV hunter with the SV talents enabled, the addon stops recommending anything after the first 4-5 globals.

### How to Reproduce

Just start hitting any single target dummy as SV hunter with SV talents. Issue should pop up after 4-5 globals.

### Snapshot (Link)

https://pastebin.com/SYw3Yfby

### Contact Information

hesparax

**Comment by Hekili** [comment]
Thanks.  This will be fixed in the next release.
