### ISSUE TITLE
[REC] Destro lock priority never uses Shadowburn

### ISSUE THREAD

**Issue by JRDK92** [Hekili/hekili#3456]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Running with an Icy Veins WoW build that uses shadowburn. Fighting rares from the recent event in open world, I never once got suggested to use Shadowburn in my priority list at all with a fresh install of Hekili. 

### How to Reproduce

1. Enter game as Destro lock
2. Use spec from [Icy Veins](https://www.icy-veins.com/wow/destruction-warlock-pve-dps-spec-builds-talents?area=area_2), I guess?
3. Does not appear in your suggestions, ever. Not even when target near low HP?

### Snapshot (Link)

https://pastebin.com/LgXw0y4A

**Comment by Hekili** [comment]
Here is the current complete Destruction priority from SimulationCraft:

```
actions+=/incinerate
```

So, yeah, the addon is using a tweaked version of the Dragonflight priority for the time being, which doesn't have Shadowburn in it.  I'll add it in the next release.

**Comment by Hekili** [comment]
This should be resolved-ish kinda in the current release.

**Comment by JRDK92** [comment]
@Hekili Just out of curiousity, what could cause something like this?

**Comment by Hekili** [comment]
There's no updated priority from SimC, and the Dragonflight priority didn't include Shadowburn.
