### ISSUE TITLE
Not registering target count on survival hunter.

### ISSUE THREAD

**Issue by Niixxso** [Hekili/hekili#3457]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When i play on my survival hunter with recommended settings it will not change despite number of targets. I have tried making pet target but still not working. Most of the time getting "locked" to single target rotation. 

### How to Reproduce

1. Enter game as survival hunter. 
2. Have display mode to auto
3. Just fight really. (Sometimes it changes but not consistently)

### Snapshot (Link)

https://pastebin.com/CvrWz9c2

**Comment by Hekili** [comment]
```
targets:  Nameplates are enabled.
 - Checking nameplate list for nameplate3 [ Creature-0-4241-2444-12659-198594-00003495D6 ] Cleave Training Dummy.
    - Excluded by range (40 > 10).
 - Checking nameplate list for nameplate5 [ Creature-0-4241-2444-12659-198594-00013495D6 ] Cleave Training Dummy.
    nameplate5   - -1 - Creature-0-4241-2444-12659-198594-00013495D6 - 47.00 - 10 - Cleave Training Dummy 
 
 - Checking nameplate list for nameplate8 [ Creature-0-4241-2444-12659-194643-00003495D6 ] Dungeoneer's Training Dummy.
    - Excluded by range (40 > 10).
 - Checking nameplate list for nameplate10 [ Creature-0-4241-2444-12659-197833-00003495D6 ] PvP Training Dummy.
    - Excluded by range (40 > 10).
 - Checking nameplate list for nameplate7 [ Creature-0-4241-2444-12659-198594-00023495D6 ] Cleave Training Dummy.
    - Excluded by range (40 > 10).
 - Checking nameplate list for nameplate6 [ Creature-0-4241-2444-12659-198594-0001B495D6 ] Cleave Training Dummy.
    - Excluded by range (40 > 10).
 - Checking nameplate list for nameplate4 [ Creature-0-4241-2444-12659-198594-0000B495D6 ] Cleave Training Dummy.
    - Excluded by range (40 > 10).
```

You don't really need pet-based target detection as Survival; you're melee.  Just use nameplate-based target detection.
