### ISSUE TITLE
[REC] Hekili Showing Incorrect Keybinding For Controller Keybind

### ISSUE THREAD

**Issue by Mosborne90** [Hekili/hekili#3458]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am playing a Devastation Evoker. This issue is only observed on two spells. 

1. Living Flame
2. Pyre

Regardless of the keybind chosen, if Pyre appears in the priority list, Hekili will recommend the keybind for Living Flame. The Icon for Pyre is appearing correctly but the keybind is not. The option in Hekili to use Console Port Keybinds is selected.

Example: Living Flame is keybound to "X" on an xbox controller. Pyre is bound to "LT + X". Pyre will display as "X".

### How to Reproduce

Replication will require a devastation evoker and testing with controller keybinds.

### Snapshot (Link)

https://pastebin.com/ccXEjyLb

**Comment by Hekili** [comment]
```
keybinds: 
    living_flame           = PAD3[01]
    pyre                   = PAD3[02], CPAD3[06]
```

You have Pyre on bar 2 and bar 6; the addon prioritizes bar 2 when determining which keybind to display.

**Comment by Mosborne90** [comment]
Thank you! The action bar appeared clear when I checked all of them. It
seemed to be a bug with the Console Port UI not showing the ability on the
bar. I was able to find a macro to clear all action bars and the issue was
resolved. Thank you again!

**Comment by Hekili** [comment]
Thanks for confirming!
