### ISSUE TITLE
BM/MM Rotation (ST/Multi) still not showing Counter Shot interruption

### ISSUE THREAD

**Issue by IronicConny** [Hekili/hekili#3459]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello,
this issue was allready reported like 2 weeks ago but already marked as solved. Nevertheless it did not solve the problem at least for me. Neither with minor important spell, nor with crucial one's to interrupt. Occuring with BM and MM spec (SV was not tested). Made a screenshot as e.g for MM.

### How to Reproduce

Could me reproduced with any mob casting an interruptable spell.

### Snapshot (Link)

https://pastebin.com/L0NQZNh3

**Comment by Hekili** [comment]
MM was mistakenly set to use Muzzle instead of Counter Shot.  This will be fixed in next release.

**Comment by IronicConny** [comment]
also happens in BM, can u check on that as well? Thx in advance
