### ISSUE TITLE
SV Hunter Wrong ST Recommendation

### ISSUE THREAD

**Issue by Hesparax** [Hekili/hekili#3460]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Survival Hunter ST rotation, the addon recommends casting 4-5 Mongoose Bites back to back even when much more important spells (Explosive Shot, Wildfire Bombs, class CDs) are all available/overcapping.
This issue has started occurring following the latest addon update on August 9th.

### How to Reproduce

Simply go to any single target dummy with the single target talents equipped, and observe the recommended spell queue. It does not follow the indicated priority in the guides. Nowhere are you supposed to cast 4-5 Mongoose Bites back to back, definitely not in the opener.

### Snapshot (Link)

https://pastebin.com/QmQ2aK8v

**Comment by Hekili** [comment]
Provide a sim link of your character.

**Comment by Hekili** [comment]
Actually, your priority looks scuffed. It has Mongoose Bite for the first entry in the default action list without any conditions. I'll check to see if mine is doing that, too.

That entry should be Muzzle.

**Comment by Hekili** [comment]
Yeah, you likely want to click the little circle arrow to reset your Survival priority here:

![image](https://github.com/user-attachments/assets/37a60a8b-167c-49da-9011-4183c58258bd)

**Comment by Hesparax** [comment]
Ah yes, reloading the priority seems to have fixed the issue.
MB is still being recommended more than it used to be in the past, but I reckon that's because of the APL updates to reflect the bomb nerf and MB buff.
