### ISSUE TITLE
PROC not see on rotation

### ISSUE THREAD

**Issue by Kraystase** [Hekili/hekili#3462]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello 
in priority helper  ,  no recognize    " hammer of light "  PROC  see on my screen on bar letter R emplacement  , maybe already in work but want help if you not see that

is on beta , so hope , fix  for retail 
thanks for this addon 

![WoWScrnShot_081024_013950](https://github.com/user-attachments/assets/2f38041f-ceb4-49d8-881f-1c4057ed2e88)

### How to Reproduce

just enter fight on a mob tester 
do your rotate , and just see , no  proc can't see  

### Snapshot (Link)

.

### Additional Information

Just see if possible to include proc on rotate 

### Contact Information

 kraystase#3890

**Comment by Hekili** [comment]
Hero talents will be supported later.

**Comment by Kraystase** [comment]
ok , thanks for you work for this addon    :)
