### ISSUE TITLE
[BUG] Not recommending WW abilities if Grieftorch is available

### ISSUE THREAD

**Issue by NokuraWoW** [Hekili/hekili#3465]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Enter combat, if grieftorch is available you will get an error 

### How to Reproduce

Enter as windwalker, have grieftorch available, get into combat. It also happens when grieftorch becomes available during combat

### Player Information (Link)

https://pastebin.com/zM24cYcx

### Error Messages (Link)

https://pastebin.com/4RYxQtjS

### Contact Information

nokura

**Comment by Hekili** [comment]
This should be resolved in v11.0.2-1.0.0.
