### ISSUE TITLE
SV Hunter priority recommending Kill Command even at maximum Tip of the Spear stacks 

### ISSUE THREAD

**Issue by Hesparax** [Hekili/hekili#3466]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After yesterday's changes, described as "Allow Kill Command regardless of Focus", Hekili has started recommending Kill Command to be cast not only at maximum focus, but also at maximum number of Tip of the Spear stacks, despite several TotS spenders (such as Explosive Shot, Wildfire Bombs, Killshot, etc.) are all available and off cooldown.

This appears to happen mostly during the Coordinated Assault cooldown with Relentless Primal Ferocity talented, which makes Kill Command generate 2 stacks of TotS during the cooldown.

This happens in both ST and AoE.

### How to Reproduce

As a Survival Hunter, make sure you have Coordinated Assault and Relentless Primal Ferocity talented, then start following the addon's rotation.
You will notice the excessive Kill Command recommendations even at maximum Tip of the Spear stacks.

### Snapshot (Link)

https://pastebin.com/HECmM3wX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dKbj5mRrpNW1Tbu1JmUvfk

### Contact Information

hesparax

**Comment by BorpoTingis** [comment]
I'm noticing this as well, appears to be due to the addon checking to see if the Relentless Primal Ferocity buff is up, however Relentless Primal Ferocity doesn't give you a buff when Coordinated Assault is used. Modifying entries 1 and 11 in the sentst action list to check if instead Relentless Primal Ferocity is known and Coordinated Assault is up seems to have fixed this for me.

**Comment by Hesparax** [comment]
> I'm noticing this as well, appears to be due to the addon checking to see if the Relentless Primal Ferocity buff is up, however Relentless Primal Ferocity doesn't give you a buff when Coordinated Assault is used. Modifying entries 1 and 11 in the sentst action list to check if instead Relentless Primal Ferocity is known and Coordinated Assault is up seems to have fixed this for me.

Could you please include your modifications to those lines so I can apply them as well until a fix is pushed to the addon?

**Comment by BorpoTingis** [comment]
Sure. Just a disclaimer, I am by no means an expert so there are probably better ways to do this. I changed the actions in here
![image](https://github.com/user-attachments/assets/ffe8843a-d572-4df3-9998-47dbba9b9318)
to the following. Entry 1:
`( talent.relentless_primal_ferocity.enabled &buff.coordinated_assault.up & buff.tip_of_the_spear.stack < 1 )`
Entry 11:
`( !( talent.relentless_primal_ferocity.enabled & buff.coordinated_assault.up) | ( ( talent.relentless_primal_ferocity.enabled & buff.coordinated_assault.up) & buff.tip_of_the_spear.stack < 2 ) )`

**Comment by Hesparax** [comment]
I appreciate the help. Unfortunately, it doesn't seem to have worked for me, I am still getting wrong KC recommendations both in ST and AoE. Hopefully, we can get an "official" fix soon.
Either way, thanks for looking into it!

**Comment by BorpoTingis** [comment]
Yeah, I'm noticing now too that that will fix over capping on tip of the spear stacks but not focus.

**Comment by Hekili** [comment]
This should be resolved in v11.0.2-1.0.0.
