### ISSUE TITLE
[REC] MM single target and sometimes AoE has too many steady shots recommended in latest update

### ISSUE THREAD

**Issue by RussellAnas** [Hekili/hekili#3467]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On my marksman hunter, after latest update there are too many steady shots recommended, and this is besides me not having the 'steady focus' talent which does prioritize having 2 steady shots few seconds.

### How to Reproduce

1. Enter game as Marksman hunter
2. Enter a dungeon or try rotation on dummy
3. Specifically during trueshot is on CD and there are less spells to recommend, keeps recommending steady shots even when aimed shot is available or arcane shots.

### Snapshot (Link)

https://pastebin.com/MUHZhbkX

**Comment by syrifgit** [comment]
Looks like an issue with steady focus haste buff. On the 3rd steady shot it still thinks you won't have the buff.

**Comment by Hekili** [comment]
You won't have it without Steady Focus talented (I think). The APL needs to check for the talent, I think.

**Comment by RussellAnas** [comment]
That’s the thing, even without the talent it keeps recommending steady focuses one after the other. Other more pressing spells are available but it still suggests steady focus. 

Reverting to previous version fixes things btw.

**Comment by Hekili** [comment]
> That’s the thing, even without the talent it keeps recommending steady focuses one after the other.

Yes, that's what I said.  It'll be fixed in next release.

**Comment by Hekili** [comment]
This should be resolved in v11.0.2-1.0.0.
