### ISSUE TITLE
[REC] Immolate being repeatedly suggested

### ISSUE THREAD

**Issue by JRDK92** [Hekili/hekili#3468]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Simple question: When Cataclysm isn't chosen for Destruction warlock, should the player be suggested to spam immolate on every target?

Background: On Destruction Warlock level 70 fighting Echo of the Lich King in Prepatch, seeing Immolate repeatedly suggested in the AOE suggestion, rather than building up soul shards on the main target and then rain of fire. Not sure if this is intended? Unsure if this is issue, or fully intended, just wanted some insight. 

![image](https://github.com/user-attachments/assets/d6cbf6a5-7f41-4b8b-aaef-a459d49ce5dd)

### How to Reproduce

1. Enter game as Destro warlock. 2. Fight Echo of Lich King in prepatch. 3. See immolate repeatedly over and over again.

### Snapshot (Link)

https://pastebin.com/xFW4rTzs

**Comment by Hekili** [comment]
It is intended; the condition there applies Immolates until there's more than 4 active Immolates.  You could disable target swapping if you don't want to target swap.
