### ISSUE TITLE
[BUG] Protection Paladin "Hekili: Unable to make recommendations for Primary #1 triggering auto snapshot..." and Pala Prot rotation not working

### ISSUE THREAD

**Issue by mustardorketchup** [Hekili/hekili#3469]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Get the snapshot issue during rotation test, started testing on dummys because rotation during a dungeon wasn't working.
As a start I get Consecration, Sentianel, Consecration, devine toll, Consecration, judgement, hammer of wrath and shield of the righteous is never been recommended21 in Rotation.
During this rotation I get sometimes the snapshot report, last time when I started Eye of Tyr. Not sure or it happens always 

### How to Reproduce

1. Protection Paladin Tauren
2. Rotation test on Dummy's at Valdrakken Sanctuary.
3.  Follow Rotation.

### Player Information (Link)

https://pastebin.com/3yCk5vNK

### Error Messages (Link)

No message at Bugsack

### Additional Information

https://pastebin.com/fMnAxE0K

### Contact Information

theblue_pala

**Comment by Hekili** [comment]
Try running this macro: `/run Hekili.DB.profile.displays.Primary.forecastPeriod = nil`

**Comment by mustardorketchup** [comment]
Hello Hekili support,

rotation for Protection Paladin Tauran isn't working as a Protection
Paladin Human, I tested with the same talents on both chars, and on Human
protection is it working fine, on Tauran prot is Rotation not working great
at all.

By Tauran is when Devine Toll on Cooldown still Divine Toll recommended the
same with Sentinel. While at Human rotation goes ok.
[image: image.png]

[image: image.png]

I also tested on dummies to see if I got the snapshot message again, so far
I have tested the rotation, snapshot message wasn't poppued again,  also
checked at "issue reporting (Snapshots) an entry wasn't available.
I also run your macro, is it correct that after you have run this macro no
text feedback has been available to verify that macro was running correctly?
Greetings Ruben




Op zo 11 aug 2024 om 21:06 schreef Hekili ***@***.***>:

**Comment by Hekili** [comment]
@mustardorketchup You'll need to provide snapshots, not screenshots (which didn't make it to GitHub).  See instructions below.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.
