### ISSUE TITLE
Unholy DK Auto Mode disappears

### ISSUE THREAD

**Issue by moosenuckle** [Hekili/hekili#347]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
**Yes it is Up to Date**
2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.
**I Did not see a report**
**Describe the Bug/Issue**
When I'm on my unholy DK the rotation auto mode bugs and disappears every pull if a rune is mis spent and rotation is not followed perfect. It works fine if the rotation is done perfect but it cannot update itself if the rotation sequence is missed.
**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
The Rotation guide to update like it has in the past before updates even when not followed perfectly it used to  update the rotation but no longer does
**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
build: v8.3.0-04-22.02
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: asphyxiate
    bursting_sores
    epidemic
    infected_claws
    soul_reaper
    unholy_frenzy
    wraith_walk

azerite: azerite_empowered = 3
    elemental_whirl = 2
    festermight = 3
    longstrider = 2
    magus_of_the_dead = 2
    overwhelming_power = 1
    runic_barrier = 1

essences: [blood_of_the_enemy] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 3, vision_of_perfection = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    blue_martial_shirt = 1
    dismembered_submersible_claw = 1
    gauntlets_of_nightmare_manifest = 1
    greathelm_of_phantasmic_reality = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    legplates_of_beaten_gold = 1
    lurking_schemers_band = 1
    malignant_leviathans_armguards = 1
    malignant_leviathans_greatbelt = 1
    mechanized_plate_chasse = 1
    rebooting_bit_band = 1
    sabatons_of_rampaging_elements = 1
    tabard_of_the_achiever = 1
    tank_buster_pauldrons = 1
    vitacharged_titanshard = 1

corruptions: twisted_appendage = 3

itemIDs: 158075, 158313, 159650, 159679, 168977, 168979, 169075, 169223, 173461, 173462, 174044, 174167, 174500, 175006, 175008, 40643, 42374

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by kaankaraoglu** [comment]
Also having the same issue, since the last update.

**Comment by Hekili** [comment]
That means it couldn't come up with a recommendation; the way to see why is with a snapshot. I'll keep testing, but I still need snapshots for this.

**Comment by PARADOX070** [comment]
769x [string "-- Unholy:default:3 recheck..."]:2: attempt to call field 'timeTo' (a number value)
[string "-- Unholy:default:3 recheck
return runic_power.timeTo(runic_power.max-(65)), pet.gargoyle.remains, rune.timeTo(rune.max-(5))"]:2: in function `Recheck'
[string "@Hekili\State.lua"]:1323: in function `recheck'
[string "@Hekili\Core.lua"]:738: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:1061: in function `GetNextPrediction'
[string "@Hekili\Core.lua"]:1311: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:826: in function <Hekili\UI.lua:690>

Locals:
(*temporary) = 0
(*temporary) = 0
(*temporary) = 3600
(*temporary) = 1
(*temporary) = "attempt to call field 'timeTo' (a number value)"

Could the above be related to it? Cause basically the same happens, The rotation stops no more spells are being shown. And when trying to generate a snapshot/pause hekili nothing happens, That is when the error pops up.

**Comment by Hekili** [comment]
That's a genuine error, and yes, that's helpful.  And it's happening to you a lot.  I can investigate this, so thanks for passing the error report.

**Comment by kaankaraoglu** [comment]
Paradox070 beat me to it. I get the exact same one when my RP is almost full and I turn on cooldowns.

**Comment by PARADOX070** [comment]
My CD's are on by default, It just seems to happen randomly. Some times on a pull sometimes after using an ability. It happens both when exactly following the rotation as well as deviating from it.

**Comment by Hekili** [comment]
Can I get a screenshot of `/dump Hekili.State.runic_power` and `/dump Hekili.State.rune` ?

And your Issue Reporting information again just so I can confirm talents/azerite/etc.?

**Comment by PARADOX070** [comment]
build: v8.3.0-04-22.02
level: 120 (120)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    asphyxiate
    ebon_fever
    epidemic
    soul_reaper
    unholy_frenzy
    wraith_walk

azerite: azerite_empowered = 3
    azerite_globules = 1
    elemental_whirl = 1
    festermight = 2
    gemhide = 1
    magus_of_the_dead = 3
    overwhelming_power = 1
    personal_absorbotron = 1
    relational_normalization_gizmo = 1
    runic_barrier = 1

essences: [vision_of_perfection] = 4, breath_of_the_dying = 4, essence_of_the_focusing_iris = 4, memory_of_lucid_dreams = 4

sets/legendaries/artifacts: none

gear: artisan_officers_shirt = 1
    ashjrakamas_shroud_of_resolve = 1
    dark_crystalline_girdle = 1
    desert_guardians_breastplate = 1
    dragonbone_vambraces = 1
    fangproof_gauntlets = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    malignant_leviathans_warboots = 1
    paramount_orthogonal_optics = 1
    petrified_wickerplate_greaves = 1
    renowned_guild_tabard = 1
    ring_of_collective_consciousness = 1
    ring_of_cosmic_potential = 1
    skshuul_vaz = 1
    tank_buster_pauldrons = 1
    vitacharged_titanshard = 1

corruptions: gushing_wound = 1
    infinite_stars = 2
    obsidian_skin = 1
    void_ritual = 1

itemIDs: 158075, 159424, 159437, 159456, 169075, 169223, 171009, 172200, 173475, 174044, 174170, 174171, 174500, 174530, 174533, 69210, 89195

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 20
    maxTime = 5
    nameplateRange = 8
    nameplates = true
    package = Unholy
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false


[17:02] **Dump: value=Hekili.State.runic_power** 
 [17:02] [1]={ 
 [17:02]   active_regen=0, 
 [17:02]   type=6, 
 [17:02]   values={ 
 [17:02]     [29351.051604717]=52, 
 [17:02]     [29349.854]=52, 
 [17:02]     [29349.851604717]=52 
 [17:02]   }, 
 [17:02]   last_tick=0, 
 [17:02]   max=100, 
 [17:02]   tick_rate=0.1, 
 [17:02]   regen=0, 
 [17:02]   modmax=100, 
 [17:02]   timeTo=<function>, 
 [17:02]   resource="runic_power", 
 [17:02]   fcount=1, 
 [17:02]   times={ 
 [17:02]     [86]=32951.051604717, 
 [17:02]     [80]=32951.051604717 
 [17:02]   }, 
 [17:02]   forecast={ 
 [17:02]     [1]={ 
 [17:02]       e="actual", 
 [17:02]       t=29348.65, 
 [17:02]       v=52 
 [17:02]     } 
 [17:02]   }, 
 [17:02]   inactive_regen=0, 
 [17:02]   actual=52, 
 [17:02]   add=<function> 
 [17:02] }

[17:03] **Dump: value=Hekili.State.rune** 
 [17:03] [1]={ 
 [17:03]   resource="runes", 
 [17:03]   forecast={ 
 [17:03]     [1]={ 
 [17:03]       e="actual", 
 [17:03]       t=29388.83, 
 [17:03]       v=5 
 [17:03]     }, 
 [17:03]     [2]={ 
 [17:03]       e="rune_regen", 
 [17:03]       t=29396.812, 
 [17:03]       v=6 
 [17:03]     }, 
 [17:03]     [3]={ 
 [17:03]       e="rune_regen", 
 [17:03]       t=29354.967, 
 [17:03]       v=6 
 [17:03]     }, 
 [17:03]     [4]={ 
 [17:03]       e="rune_regen", 
 [17:03]       t=29270.426, 
 [17:03]       v=6 
 [17:03]     }, 
 [17:03]     [5]={ 
 [17:03]       e="rune_regen", 
 [17:03]       t=29270.428, 
 [17:03]       v=6 
 [17:03]     }, 
 [17:03]     [6]={ 
 [17:03]       e="rune_regen", 
 [17:03]       t=29270.423, 
 [17:03]       v=6 
 [17:03]     }, 
 [17:03]     [7]={ 
 [17:03]       e="rune_regen", 
 [17:03]       t=29256.721, 
 [17:03]       v=6 
 [17:03]     } 
 [17:03]   }, 
 [17:03]   regenModel={ 
 [17:03]     rune_regen={ 
 [17:03]       last=<function>, 
 [17:03]       stop=<function>, 
 [17:03]       next=29395.812, 
 [17:03]       value=1, 
 [17:03]       name="rune_regen", 
 [17:03]       resource="runes", 
 [17:03]       interval=<function> 
 [17:03]     } 
 [17:03]   }, 
 [17:03]   gain=<function>, 
 [17:03]   last_tick=0, 
 [17:03]   max=6, 
 [17:03]   tick_rate=0.1, 
 [17:03]   regen=0, 
 [17:03]   expiry={ 
 [17:03]     [1]=0, 
 [17:03]     [2]=0, 
 [17:03]     [3]=0, 
 [17:03]     [4]=0, 
 [17:03]     [5]=0, 
 [17:03]     [6]=29396.8160312 
 [17:03]   }, 
 [17:03]   modmax=6, 
 [17:03]   values={ 
 [17:03]     [29388.832]=5, 
 [17:03]     [29390.029604717]=5, 
 [17:03]     [29390.032]=5, 
 [17:03]     [29391.229604717]=5 
 [17:03]   }, 
 [17:03]   fcount=2, 
 [17:03]   times={ 
 [17:03]   }, 
 [17:03]   actual=5, 
 [17:03]   spend=<function>, 
 [17:03]   cooldown=7.9840312004089, 
 [17:03]   reset=<function> 
 [17:03] }

**Comment by Hekili** [comment]
Test fix incoming (v8.3.0-04-22.03-beta1) -- let me know if it seems to resolve for you immediately or if you notice anything new and odd.  The only change is related to forecasting rune regen for recommendation timing purposes.

**Comment by PARADOX070** [comment]
Fix is working, No more errors after 5 min on the dummy with several CD's.

**Comment by Hekili** [comment]
Yeah, I think this is a pretty narrow scope fix, so I'm going to push it to release.  Thanks.
