### ISSUE TITLE
[FEATURE] SpellFlash on WeakAuras instead of ActionBars

### ISSUE THREAD

**Issue by hazardgg** [Hekili/hekili#3470]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Flash the WeakAuras instead of Actionbars.
Or make it an option to choose WA/WA group or actionbars, depending on your preferal

**Comment by Hekili** [comment]
The addon already notifies WeakAuras when its recommendations update.  It fires `HEKILI_RECOMMENDATION_UPDATE`, sending `displayName` (i.e., "Primary"), `actionID` (usually a spellID), `indicator` (if applicable), `empowerTo` (if applicable), and a `payload` table from which any other information about what the addon is recommending could be extracted.

One could make a WeakAura that triggers/removes glows based on this event using a custom trigger and some effort, but I will be not be creating/supporting that functionality myself.

**Comment by hazardgg** [comment]
Can't it just hook the SpellFlash to weakauras instead of actionbars? 

Like I assume there is some function finding actionbars, instead of looking for actionbars it just find any appropriate WeakAura icon.. Maybe assign from what WeakAura group to look for same spell or similar.

So not actually talking about the Glow function in WA, just using same SpellFlash but on wa's instead.

@Hekili
