### ISSUE TITLE
Druid Major Cooldown (Mark of the Wild) not showing in any spec rotation.

### ISSUE THREAD

**Issue by briarrose33** [Hekili/hekili#3472]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Feral Druid (any spec really) it does not show the "Mark of the Wild" as part of the rotation. I have the radio button selected to show major cooldowns and it does work for the mage/evoker/warrior.

### How to Reproduce

1. Enter the game as any druid spec, 2. Remove "Mark of the Wild" if already active, 3. Look at suggested rotation and see that it is not it shown as an option. 4. Do the suggested rotation and see that "Mark of the Wild" is never a suggested item.

### Snapshot (Link)

https://pastebin.com/q7Ucnu7y

**Comment by Hekili** [comment]
Technically, it would show up for Guardian but not the other specializations.

This will be addressed in the next update.
