### ISSUE TITLE
Priest (All Specs) - Does not Recommend Major Cooldown "Power Word: Fortitude"

### ISSUE THREAD

**Issue by briarrose33** [Hekili/hekili#3473]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing the priest (any spec) the rotation does not recommend "Power Word: Fortitude" at any step. The radial button for Cooldowns is selected.

### How to Reproduce

1. Enter game as Priest (any spec), 2. Remove "Power Word: Fortitude" buff if active, 3. See that "Power Word: Fortitude" is not recommended in the rotation, 4. Continue through the rotation to see it is never suggested.

### Snapshot (Link)

https://pastebin.com/ywUvWVtc

**Comment by Hekili** [comment]
Power Word: Fortitude isn't a major cooldown; it's a raid buff.  It was missing from Shadow, but will be shown in the next release.
