### ISSUE TITLE
Frost DK Glacial Advance

### ISSUE THREAD

**Issue by ToxxicApe** [Hekili/hekili#3475]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The talent Galcial Advance replace Frost Strike at 2+ targets in rotation. But it is recommended even on 1 target instead of frost strike but changes last second to frost strike or something else.

### How to Reproduce

go to single target dummy and play ST rotation. Glacial Advance is always recommended.

### Snapshot (Link)

https://pastebin.com/KPS88mPa

**Comment by Hekili** [comment]
Take the snapshot when Glacial Advance is recommended.  Also, please provide a sim link for your character (Patchwerk, 1-target).  Thanks!

**Comment by Hekili** [comment]
Also, please check if (one of) your weapon(s) has a Razorice runeforge?

**Comment by ToxxicApe** [comment]
it always was recommended but only on third or second position. when it comes to first position it always changes to frost strike.

**Comment by ToxxicApe** [comment]
https://www.raidbots.com/simbot/report/w95e17e9bnNeR4KdPiYvz3

**Comment by Hekili** [comment]
> Take the snapshot when Glacial Advance is recommended.

**Comment by ToxxicApe** [comment]
https://pastebin.com/CCv7ZSij
this is on ST in third position
https://pastebin.com/YSyFuHV9
this is on ST in second position

**Comment by Hekili** [comment]
> Also, please check if (one of) your weapon(s) has a Razorice runeforge?

**Comment by ToxxicApe** [comment]
you see on the sim that i have only fyralath and it has the fallen crusader runeforge on it :)
