### ISSUE TITLE
[REC] Holy Paladin not recommending Blessing of Summer

### ISSUE THREAD

**Issue by gjritter** [Hekili/hekili#3479]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Holy Paladin, when Blessing of Summer is available, I expect Hekili to recommend it, but it does not.

### How to Reproduce

1. Enter game as a holy paladin.
2. Ensure that the Blessing of Summer talent is chosen.
3. Observe that Blessing of Summer is not recommended even though it is available.

### Snapshot (Link)

https://pastebin.com/GkkYgbEC

### Additional Information

I did not post a sim report as it's a healer profile.

### Contact Information

gnomic

**Comment by Hekili** [comment]
This should be resolved in v11.0.2-1.0.0.
