### ISSUE TITLE
Unholy DK - Army of the Dead

### ISSUE THREAD

**Issue by Nazeth** [Hekili/hekili#348]
On rotation scripts value of army_of_the_dead does not only trigger spell with that name, but also trigger on minions with the same name, what are summoned by Unholy DK every VoP Major, Apocalypse and Army of the Dead... 

So probably army_of_the_dead is triggered by:
- spell?
- minions
- buff with that name?

To reproduce that make simple rotation with &!cooldown.army_of_the_dead.remains on spells, that use runes instead of Army of the Dead.
Every time, when Army of the Dead minion will be summoned form spells VoP Major, Apocalypse and Army of the Dead will trigger this and remove that spells from rotation instead when spell Army of the Dead isn't on cooldown.

Issue with that is problematic, because that's negate many scripts from rotation every time, when minion is summoned instead of trigger only on spell with that name.

**Comment by Hekili** [comment]
Submit a proper ticket following the provided instructions, please.

**Comment by Nazeth** [comment]
I can't do it more precisely...

**Comment by Hekili** [comment]
Okay, I'll have to close this then and wait for a new ticket later. Sorry.
