### ISSUE TITLE
Enh Shaman Elemental Blast Being recommended when on Extended CD

### ISSUE THREAD

**Issue by Hammerfall2074** [Hekili/hekili#3480]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Elemental Blast is being recommended while on CD

### How to Reproduce

1. Enter game on shaman
2. ensure specialization is Enhancement
3. Ensure that Lava Blast and Elemental Blast are selected as Talents
4. Go to single target dummy and begin following rotation helper
5. Elemental Blast will be recommended while on CD

### Player Information (Link)

https://pastebin.com/9yhsufnT

### Error Messages (Link)

None

**Comment by Hekili** [comment]
This will be resolved in the v11.0.2 release.
