### ISSUE TITLE
[BUG] TWW/MageFrost.lua not using updated GetSpellInfo naming

### ISSUE THREAD

**Issue by nancikennedy** [Hekili/hekili#3481]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On load, etc:

3x Hekili/TheWarWithin/MageFrost.lua:1609: attempt to call global 'GetSpellInfo' (a nil value)
[string "@Hekili/TheWarWithin/MageFrost.lua"]:1609: in main chunk  [truncated the error as it's diagnostically irrelevant]

### How to Reproduce

Enter game as a Mage

### Player Information (Link)

Ignoring this as you've already corrected this elsewhere.

### Error Messages (Link)

Ignoring this as you've already corrected this elsewhere.

**Comment by nancikennedy** [comment]
I tried updating my local copy by adding the "local GetSpellInfo = C_Spell.GetSpellInfo"  declaration to the same general location as you have it in other ClassSpec files, and that is now prompting a new error:

1x Hekili/TheWarWithin/MageFrost.lua:1605: bad argument #6 to 'strformat' (string expected, got table)
[string "=[C]"]: in function `strformat'
[string "@Hekili/TheWarWithin/MageFrost.lua"]:1605: in main chunk

Locals:
(*temporary) = "If checked, non-instant %s, %s, %s casts will not be recommended while you are moving.

An exception is made if %s is talented and active and your cast would be complete before |W%s|w expires."
(*temporary) = "|W|T135857:0::::64:64:4:60:4:60|t |cff71d5ffBlizzard|r|w"
(*temporary) = "|W|T1698699:0::::64:64:4:60:4:60|t |cff71d5ffGlacial Spike|r|w"
(*temporary) = "|W|T135846:0::::64:64:4:60:4:60|t |cff71d5ffFrostbolt|r|w"
(*temporary) = "|W|T610877:0::::64:64:4:60:4:60|t |cff71d5ffIce Floes|r|w"
(*temporary) = <table> {
 castTime = 0
 name = "Ice Floes"
 minRange = 0
 originalIconID = 610877
 iconID = 610877
 maxRange = 0
 spellID = 108839
}
(*temporary) = "string expected, got table"

**Comment by Hekili** [comment]
This will be resolved in the v11.0.2 release.
