### ISSUE TITLE
Assassination Rotation suggested to Envenom at 4 CP

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#3482]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

So since the last hekili update, I noticed that sometimes Hekili will suggest to send envenom to target at 4 combo points which I think it's not a corrected play. In Rogue discord, from faqs, we send finisher at 5+ combo points so I'm not sure if this is a thing in Simc or it's an error from the addons.

### How to Reproduce

1. Enter game as Assassination
2. Start rotations and at some points, it will suggest to envenom at 4 CP. If testing in dummies, maybe it has something to do with low HP dummies but it also happens in dungeons

### Snapshot (Link)

https://pastebin.com/3A2sKk1Q

**Comment by Hekili** [comment]
This is a thing in SimC.

**Comment by Sedveth** [comment]
Thank you for your quick reply, I'm appreciated.

**Comment by Sedveth** [comment]
I just wanna to open this again to confirm if this is correct behavior in SimC
Currently in apl: envenom,if=buff.slice_and_dice.up&buff.slice_and_dice.remains<5&combo_points>=5
My sim: https://www.raidbots.com/simbot/report/xj4kHtCUu3mGTKLjV8YGpV/simc
My snapshot: https://pastebin.com/5fjeDyfw

In my sim, when I check, it never send any Envenom at CP <5 while sometimes Hekili will suggest to do it at 4 CP
