### ISSUE TITLE
[BUG] Deprecated GetSpellInfo command message

### ISSUE THREAD

**Issue by mbinkhorst** [Hekili/hekili#3483]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Upon loading the addon for my frost mage, I get an error about the deprecated GetSpellInfo command. 

<img width="1431" alt="Screenshot 2024-08-14 at 20 10 12" src="https://github.com/user-attachments/assets/74d9a671-fcb0-4b18-9b2e-b4e6974c1c76">

### How to Reproduce

1. enter game as frost mage ( My build: CAEArhxZfsv/vllYUrQS3iw2nPzYzsZBzwMziBzYmGjxYmxwMzMMzMzMzYmZmZGzMYGAAAAAAAAAAAAzCAAAAAAAAA)
2. error

### Player Information (Link)

https://pastebin.com/G1P1p02e

### Error Messages (Link)

https://pastebin.com/hP0aBi7q

**Comment by vaniron** [comment]
Getting same error just after creating new mage and loading it for first time.

**Comment by Hekili** [comment]
This should be resolved in v11.0.2-1.0.0.
