### ISSUE TITLE
[BUG] Doesn't display anything on my mage. (works fine on other char)

### ISSUE THREAD

**Issue by Falken000** [Hekili/hekili#3484]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [x] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I can open hekili settings and everything seems to be working fine but the issue is that nothing displays on the screen. Only happends on my mage. 

1x Hekili/TheWarWithin/MageFrost.lua:1609: attempt to call global 'GetSpellInfo' (a nil value)
[string "@Hekili/TheWarWithin/MageFrost.lua"]:1609: in main chunk

Locals:
addon = "Hekili"
ns = <table> {
 specTemplate = <table> {
 }
 frameProfile = <table> {
 }
 Localize = <table> {
 }
 debug = <table> {
 }
 queue = <table> {
 }
 PvpDummies = <table> {
 }
 attr = <table> {
 }
 UI = <table> {
 }
 PetActions = <table> {
 }
 Tooltip = HekiliTooltip {
 }
 AddonName = "Hekili"
 targets = <table> {
 }
 metatables = <table> {
 }
 keys = <table> {
 }
 auras = <table> {
 }
 BigLibTimer6 = <table> {
 }
 PTR = true
 cpuProfile = <table> {
 }
 TTD = <table> {
 }
 castsAll = <table> {
 }
 Patrons = "|cFFFFD100Current Status|r

All existing specializations are currently supported, though healer priorities are experimental and focused on rotational DPS only.

If you find odd recommendations or other issues, please follow the |cFFFFD100Issue Reporting|r link below and submit all the necessary information to have your issue investigated.

Please do not submit tickets for routine priority updates (i.e., from SimulationCraft).  I will routinely update those when they are published.  Thanks!"
 castsOff = <table> {
 }
 lib = <table> {
 }
 snapshots = <table> {
 }
 hotkeys = <table> {
 }
 castsOn = <table> {
 }
 FrameStratas = <table> {
 }
}
Hekili = <table> {
 Maintenance = <table> {
 }
 modules = <table> {
 }
 Scripts = <table> {
 }
 defaultModuleState = true
 KeybindInfo = <table> {
 }
 Class = <table> {
 }
 AuraDB = <table> {
 }
 SpecChangeHistory = <table> {
 }
 enabledState = true
 BuiltFor = 110000
 OptionsReady = false
 AllowSimCImports = true
 Version = "v11.0.0-1.0.5"
 State = <table> {
 }
 ECount = <table> {
 }
 ErrorKeys = <table> {
 }
 EventSources = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 Snapshots = <table> {
 }
 IC = <table> {
 }
 name = "Hekili"
 orderedModules = <table> {
 }
 mt_default_totem = <table> {
 }
 ErrorDB = <table> {
 }
 EData = <table> {
 }
 CurrentBuild = 110002
 Flavor = "Retail"
 GameBuild = "11.0.2"
}
class = <table> {
 totems = <table> {
 }
 talents = <table> {
 }
 abilityList = <table> {
 }
 stateExprs = <table> {
 }
 auras = <table> {
 }
 pets = <table> {
 }
 itemPack = <table> {
 }
 abilityByName = <table> {
 }
 interrupts = <table> {
 }
 gear = <table> {
 }
 trinkets = <table> {
 }
 packs = <table> {
 }
 setBonuses = <table> {
 }
 itemList = <table> {
 }
 knownAuraAttributes = <table> {
 }
 file = "MAGE"
 stateTables = <table> {
 }
 stances = <table> {
 }
 auraList = <table> {
 }
 range = 8
 hooks = <table> {
 }
 settings = <table> {
 }
 resources = <table> {
 }
 initialized = true
 specs = <table> {
 }
 stateFuncs = <table> {
 }
 pvptalents = <table> {
 }
 potionList = <table> {
 }
 resourceAuras = <table> {
 }
 itemSettings = <table> {
 }
 variables = <table> {
 }
 toggles = <table> {
 }
 potions = <table> {
 }
 itemMap = <table> {
 }
 abilities = <table> {
 }
 powers = <table> {
 }
 num = 4
}
state = <table> {
 swing = <table> {
 }
 soulbind = <table> {
 }
 conduit = <table> {
 }
 covenant = <table> {
 }
 purge = <table> {
 }
 now = 0
 ptr = 1
 off_hand = <table> {
 }
 items = <table> {
 }
 holds = <table> {
 }
 prev = <table> {
 }
 realQueue = <table> {
 }
 aura = <table> {
 }
 empowering = <table> {
 }
 prev_off_gcd = <table> {
 }
 active_dot = <table> {
 }
 mainhand_speed = 0
 debuff = <table> {
 }
 role = <table> {
 }
 equipped = <table> {
 }
 aggro = false
 recheckTimes = <table> {
 }
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 stat = <table> {
 }
 buff = <table> {
 }
 player = <table> {
 }
 encounterName = "None"
 table = <table> {
 }
 bfa_essence = <table> {
 }
 spell_targets = <table> {
 }
 offset = 0
 hero_tree = <table> {
 }
 max_targets = 0
 pet = <table> {
 }
 runeforge = <table> {
 }
 consumable = <table> {
 }
 pvptalent = <table> {
 }
 delayMin = 0
 queue = <table> {
 }
 action = <table> {
 }
 delayMax = 15
 false_start = 0
 race = <table> {
 }
 predictions = <table> {
 }
 script = <table> {
 }
 health = <table> {
 }
 tanking = false
 cooldown = <table> {
 }
 stance = <table> {
 }
 gcd = <table> {
 }
 empowerment = <table> {
 }
 Enum = <table> {
 }
 movement = <table> {
 }
 varDB = <table> {
 }
 auras = <table> {
 }

### How to Reproduce

Enter game as frost mage. 

### Player Information (Link)

There is no text from text box.

### Error Messages (Link)

https://pastebin.com/dMS788GK

**Comment by Hekili** [comment]
This should be resolved in v11.0.2-1.0.0.
