### ISSUE TITLE
Addon 'out of date'

### ISSUE THREAD

**Issue by magsa88** [Hekili/hekili#3485]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Blizz has decided it's now out-of-date. It was fine earlier. But wanted to make sure you knew it's now pushed it out of full functionality.

It is also 'out of date' on beta, but I don't know if it is not intended to be current for beta, so just adding this as a note. 

### How to Reproduce

Open game. On attempting to get bug info for you, addon not opening, even after forcing it to load out of date addons and reloading the game. 

### Player Information (Link)

addon not opening, even after forcing it to load out of date addons and reload

### Error Messages (Link)

bugsack not producing an error.

### Additional Information

I think I covered everything. Happy to add more if necessary. 
<img width="1142" alt="Screenshot 2024-08-14 at 21 32 43" src="https://github.com/user-attachments/assets/8ad574a2-482b-4ed6-aebb-48a944ebe718">
<img width="346" alt="Screenshot 2024-08-14 at 21 32 55" src="https://github.com/user-attachments/assets/4e9a1714-81e8-48b3-aa31-f4ab7c2cbf30">
<img width="497" alt="Screenshot 2024-08-14 at 21 33 25" src="https://github.com/user-attachments/assets/030dd6e2-562d-48a8-993e-0cacec55625c">
<img width="715" alt="Screenshot 2024-08-14 at 21 33 39" src="https://github.com/user-attachments/assets/1449b593-4f0a-4ef6-bbfa-04d4409cfaf1">

**Comment by Hekili** [comment]
This should be resolved in v11.0.2-1.0.0.
