### ISSUE TITLE
Arcane Mage recommendations brake at opener

### ISSUE THREAD

**Issue by Jumimaru** [Hekili/hekili#3487]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

De recommendations for Arcane Mage brake when you do the opener with the Dreambinder staff equipped. 

Without the staff on it seems to work normally.

### How to Reproduce

1. Log into an Arcane Mage.
2. Equipped Dreambinder
3. Cast Mirror Image
4. Cast Evocation
Here the recommendation goes from 4 as configured to only dreambinder.
![WoWScrnShot_081524_084339](https://github.com/user-attachments/assets/f7b36416-b54b-408a-bdc3-e7cb8d233591)
![WoWScrnShot_081524_084357](https://github.com/user-attachments/assets/97d70ea1-1198-4506-8103-f88d0d4ec16c)

### Snapshot (Link)

https://pastebin.com/btneH9ks

**Comment by Jumimaru** [comment]
No idea if this will still be relevent with the new XPAC, because nobody will use the staff anymore. 

But as a huge fan of the product i felt it was my duty to inform <3

**Comment by Hekili** [comment]
I need the snapshot to be taken when the problem is occurring, not before.  Can you take a snapshot when the display looks like your second image?

Thanks!

**Comment by Jumimaru** [comment]
Here is another try if you need something else let me know.

https://pastebin.com/in16WTTp

**Comment by Jumimaru** [comment]
Closed ticket unintentionally. Reopened again.

**Comment by esergiosantos** [comment]
The same thing happened here to me, disabling the Dreambinder Staff, Loom of the Great Cycle, seems to have solved the problem


The snapshot generated with the problem is not complete, it only includes the name of the staff

Snapshot: Arcane; Dreambinder, Loom of the Great Cycle(0.00)

**Comment by Jumimaru** [comment]
The hotfix from today FIXED the problem, it was a channeling problem. 

Great JOB <3!
