### ISSUE TITLE
Feral priority not pooling energy for ferocious bite outside of incarn to utilize Saber Jaws

### ISSUE THREAD

**Issue by whynotdead** [Hekili/hekili#3488]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Action #4 (max energy set by default) and #5 (max energy unchecked by default) in Finisher Action list seems not working well in pair and ignoring resource pooling outside of incarn making Saber Jaws talent not being utilized completely. Works the same on raid bosses/open world dummy. In case you check max energy at action #5 in finisher section, it will ignore bites during berserk/incarn completely and keep using builders

### How to Reproduce

1. Enter the game as feral
2. Proceed the rotation following recommendations when berserk/incarn, tiger's fury is on cooldown
3. Recommendations keep advicing use ferocious bite instantly at 5 combo points regardless of current energy and tiger's fury cd

### Snapshot (Link)

https://pastebin.com/rwJdnJsy

### Contact Information

whynotdead7

**Comment by Hekili** [comment]
Have you simmed your character for comparison?
