### ISSUE TITLE
Elemental Shaman recommending Thunderstrike Ward even though i have the buff up

### ISSUE THREAD

**Issue by Conneroc03** [Hekili/hekili#3490]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

on my ele shaman, hekili recommends thunderstrike ward buff, even when it is active. 

### How to Reproduce

![Screenshot 2024-08-15 140528](https://github.com/user-attachments/assets/cb2f9f9e-5f48-4e03-921b-ea513e971a0e)

### Snapshot (Link)

https://pastebin.com/MfX1zJK7

### Contact Information

bonzai338

**Comment by MatteoLombardi** [comment]
Should be fixed by [this commit](https://github.com/Hekili/hekili/commit/ca9f5eb532c691b4dd1aaa1bcfefc41341b77e5f), and was described in #3489
