### ISSUE TITLE
[REC] cooldown.dancing_rune_weapon.remains > x is true if spell isnt on cooldown

### ISSUE THREAD

**Issue by Aralunox** [Hekili/hekili#3491]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello,
I was testing the blood dk hekili today and I was confused why the spell Tombstone was recommended although I had Dancing Rune Weapon not on cooldown. It seems that the condition cooldown.dancing_rune_weapon.remains >= 25 is true, although Dancing Rune Weapon is not on cooldown, because it is valued with 120 (which would be the value, if the cooldown would start).
Is this in any way intentional or might there be a problem?
There might be a second problem with the brackets in that Tombstone action, but Im not sure about that one.

### How to Reproduce

1. Talent Tombstone and Dancing Rune Weapon
2. Dont use DRW, follow priolist until Tombstone shows up

### Snapshot (Link)

https://pastebin.com/C5ZzJJ6n

**Comment by georgedeam** [comment]
i believe there is an issue with cooldown.x.remains when it is in a separate window.  at least that's what i understand from messing around with the classic cata addon.  try and see if it works as expected with out the cooldown in a separate window.  also there was this issue from before https://github.com/Hekili/hekili/issues/2626

**Comment by Aralunox** [comment]
It seems its a specific problem to dancing rune weapon, its not the case for bonestorm. Specified the title. Seems lke it stays always on 120. cooldown.dancing_rune_weapon.ready is always false as well.

**Comment by Aralunox** [comment]
> i believe there is an issue with cooldown.x.remains when it is in a separate window. at least that's what i understand from messing around with the classic cata addon. try and see if it works as expected with out the cooldown in a separate window. also there was this issue from before #2626

The option shifted to another place I think, not anymore in Blood, But if I did it correctly I tried it now with separate and without separate cooldowns (used the option in Toggles/Damage Cooldowns).
Had to test it twice, the functionality works without separate cooldowns. In case of DRW this is very inconventient, since it is a defensive cooldown as well and shouldnt be in the basic priority list ;(.
Still the tombstone action does not work right, but I think that is because of the wrong brackets in the action. Simc problem I guess.

**Comment by kevinh-jumbo** [comment]
The way toggling cooldowns off or disabling abilities in hekili works is by setting them to their maximum cooldown (so it appears as if they're unavailable forever). You have dancing rune weapon toggled off due to cooldowns being toggled off
```40.  dancing_rune_weapon ( default - 21 ) - ability disabled ( toggle cooldowns )```

This usually works for most APLs but will get into scenarios like this sometimes. You can either put tombstone also on the cooldowns toggle or use `cooldown.x.true_remains` to get their actual cooldown regardless of their toggled status.

**Comment by Aralunox** [comment]
> The way toggling cooldowns off or disabling abilities in hekili works is by setting them to their maximum cooldown (so it appears as if they're unavailable forever). You have dancing rune weapon toggled off due to cooldowns being toggled off `40. dancing_rune_weapon ( default - 21 ) - ability disabled ( toggle cooldowns )`
> 
> This usually works for most APLs but will get into scenarios like this sometimes. You can either put tombstone also on the cooldowns toggle or use `cooldown.x.true_remains` to get their actual cooldown regardless of their toggled status.

I tried cooldown.x.true_remains and it seems a great solution for my case, thank you very much, I did not know that one.

**Comment by Hekili** [comment]
Bear in mind, there's a reason for the feigned CD -- if a priority is written to sync up CDs and you've told the addon you don't plan to use DRW but don't use the fake CD, the priority *might* have you endlessly preparing to pop DRW.  It also might not.  Sounds like you're satisfied with your edit, so I'll mark this as closed.

**Comment by Aralunox** [comment]
I dont think that if I split cooldowns from the single target rotation visually that I say I dont want to use drw. But of course I see the problems to solve it without breaking other cases maybe. It was just not intuitive that it would behave like that, because it doesnt behave like I disable drw (and it shouldnt, because I didnt disable the ability with splitting the lists), it behaves like its always on cooldown which has in my opinion a wrong impact on the rotation. I guess there are more cases like this, which makes the split cooldown option kinda dangerous to use. But in my opinion its just visually more clear to use which is why I prefer it.

But Im very thankful for the answers, rest assured that I really appreciate the work you do, its an amazing customizable addon.
The provided solution helps my case for sure, since I use custom priority lists which i can modify, so I can solve this problem for myself, thanks again.
