### ISSUE TITLE
[REC] Elemental Shaman, No suggestions.

### ISSUE THREAD

**Issue by PARADOX070** [Hekili/hekili#3494]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Rotation stops working spitting out snapshots.

### How to Reproduce

Just perform your rotation, eventually it just stop suggesting and generates a snapshot.

### Snapshot (Link)

https://pastebin.com/12QpT32r

**Comment by Hekili** [comment]
The addon is recommending 4 spells in your snapshot.  Can you provide the auto-generated snapshot if/when no recommendations are displayed?  Thanks.

**Comment by PARADOX070** [comment]
Havent been able to replicate yet, will update or open a new one once it occurs again.
