### ISSUE TITLE
Assasination doesn't recommend Crimson Tempest

### ISSUE THREAD

**Issue by sixsi** [Hekili/hekili#3495]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon doesn't recommend Crimson Tempest at all.

### How to Reproduce

1. Enter the game as Assasination Rogue.
2. Start your rotation on AoE dummies or in any combat with 3+ targets
3. See the addon doesn't recommend Crimson Tempest at any point of the rotation

### Snapshot (Link)

https://pastebin.com/A9Q5yqGf

### Additional Information

Assasination priority looks not optimal in general. E.g. right now it recommends to use Kingsbane and then to apply Slice and Dice which is not optimal for the burst window (should apply bleeds and Slice and Dice BEFORE using Kingsbane). Updates would be appreciated :)

**Comment by OppYchan** [comment]
Having the same issue on this one

**Comment by Hekili** [comment]
Looks like the `energy_regen_combined` requirement is too aggressive (again).  I'll low this threshold and/or make it a setting to configure.

**Comment by sixsi** [comment]
this was a mop remix issue i guess. just got my char on retail and addon recommends crimson tempest :)

**Comment by Fusroedah** [comment]
There's some scenarios where it does recommend CT, it's extremely rare and it usually recommends Envenom over it, however it can potentially appear. Sounds like Hekili has figured out the issue above

**Comment by bobbytwotime** [comment]
I'm here to chime in the same report. CT is extremely rare not sure if its a energy thing when envenom or ct is max energy is always envenom.

**Comment by cutterbup** [comment]
seems like it still doesnt work. anyone still has the same problem?

**Comment by w1tch666** [comment]
Crimson Tempest is never being recommended neither on 5 target dummies or any packsize in a dungeon. 

edit:
for now you can go to Priorities->Assassination->Action List->aoe_dot->Entry 1.Crimson Tempest 

and modify the conditions at the bottom "energy.regen_combined > 25" to a lower number like 5

**Comment by cutterbup** [comment]
> Crimson Tempest is never being recommended neither on 5 target dummies or any packsize in a dungeon.
> 
> edit: for now you can go to Priorities->Assassination->Action List->aoe_dot->Entry 1.Crimson Tempest
> 
> and modify the conditions at the bottom "energy.regen_combined > 25" to a lower number like 5

thank you!

**Comment by zzhao223** [comment]
Assasination doesn't recommend garrote/ rupture when switch targets， anyone else？

**Comment by Fusroedah** [comment]
Zzhao that sounds like a separate issue, please open a separate ticket

Thanks,

Jake

**Comment by Richard-Holness** [comment]
> Crimson Tempest is never being recommended neither on 5 target dummies or any packsize in a dungeon.
> 
> edit: for now you can go to Priorities->Assassination->Action List->aoe_dot->Entry 1.Crimson Tempest
> 
> and modify the conditions at the bottom "energy.regen_combined > 25" to a lower number like 5

I can't seem to find this line anywhere in that section of the add-on. my condition text read 
"spell_targets >= 3 & variable.dot_finisher_condition & refreshable & ! cooldown.deathmark.ready & target.time_to_die - remains > 6"

**Comment by Hekili** [comment]
I already removed the energy requirement from the 11.0.2-1.0.4 release.  If this is still occurring, a snapshot with the latest version of the addon (at full combo points, in a multi-target scenario) is needed.

**Comment by Fusroedah** [comment]
Fixed!

**Comment by zzhao223** [comment]
Hi Fusro，

i Checked the new release but no assisn rouge update

Fusroedah ***@***.***>于2024年8月26日 周一15:50写道：

> Fixed!
>
>

**Comment by Willbennetdavis** [comment]
https://pastebin.com/43xXsaY4

I think this is right hekili
