### ISSUE TITLE
[BUG] Classic WoW Cata Pas de Rotation Mage sur Hekili depuis plusieurs Semaine 

### ISSUE THREAD

**Issue by Nepralido** [Hekili/hekili#3496]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Je n'ai aucune rotation pour le Mage que ce soit en feut en givre ou en arcane depuis quelque semaine et le probleme n'est toujours pas resolue

### How to Reproduce

je me connecte et tout simplement aucune rotation d'afficher dans les menu de l'add on ni en jeu 

### Player Information (Link)

https://pastebin.com/DXu6Hwj8

### Error Messages (Link)

aucun

**Comment by Supernuss** [comment]
fixed with next release (https://github.com/Hekili/hekili/pull/3508)
next time consult the discord first, a resolution exists for several month now

**Comment by Nepralido** [comment]
> fixed with next release (#3508) next time consult the discord first, a resolution exists for several month now

where i can find the discord plz ?

**Comment by syrifgit** [comment]
> > fixed with next release (#3508) next time consult the discord first, a resolution exists for several month now
> 
> where i can find the discord plz ?

il y a un lien dans le wiki: https://discord.gg/3cCTFxM
