### ISSUE TITLE
No Black Powder During AOE

### ISSUE THREAD

**Issue by lmnbonifacio** [Hekili/hekili#3497]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Black Powder should be the main finisher in 3+ packs. Hekili detects multiple targets enough to show Shuriken Tornado, but gives Eviscerate/Rupture (Single Target) over Black Powder (AOE).

### How to Reproduce

1. Build Combo Points using Shadow Strike/Shuriken Storm.
2. Ensure Slice and Dice is up.
3. Ensure target is Ruptured.

### Snapshot (Link)

https://pastebin.com/WVrQVaRG

### Additional Information

Reviewing the snapshot, it looks like Black Powder has dependencies on War Within hero talents:

buff.darkest_night.up & combo_points = cp_max_spend | effective_combo_points >= cp_max_spend & ! buff.darkest_night.up | ( combo_points.deficit <= 1 + talent.deathstalkers_mark.enabled | fight_remains <= 1 & effective_combo_points >= 3 ) & ! buff.darkest_night.up

### Contact Information

itsdesiderata

**Comment by syrifgit** [comment]
It is failing due to being dependent on some hero talents. Finish levelling to 80, and make sure to update to the newest version.

![image](https://github.com/user-attachments/assets/0a6efabd-5e96-43fc-a9e9-4f2f1e906b38)
