### ISSUE TITLE
[FEATURE] User friendly website design

### ISSUE THREAD

**Issue by MatteoLombardi** [Hekili/hekili#3499]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello! Not strictly a request for the addon itself, but maybe something to think about for the future. As a software engineer I find easy digging around in the repo reading code and managing issues and stuff. But what an average user might like and use may be a simple website tracking the addon's state (fully supported specs, supported but not polished specs, specs currently been worked on and so on) and other info (nothing particular in mind atm, consider it just an idea). I can 100% give an helping hand with that if need be, but I am mainly opening this issue to gather feedbacks about it

### Contact Information

nidhogg94 (discord)

**Comment by syrifgit** [comment]
Seems like a lot of effort for something that can be accomplished with a discord pinned message or GitHub pinned ticket?

**Comment by MatteoLombardi** [comment]
Can a quick single page application with something like a collapsible table stating latest APL change and spec/hero talent state (data maybe fed simply by a JSON, no need for a backend or a db) be considered a lot of effort? 11.0 issues and pin showed how people were interested in knowing about their fav spec and possible ETA for it. So even if this suggestion is to be declined (which I can understand and respect), still it could be valuable feedback to improve the tracking on github

**Comment by Hekili** [comment]
Last APL change is already available in-game (version numbers on a priority are time/date stamps).
