### ISSUE TITLE
Unholy DK - low lvl problems

### ISSUE THREAD

**Issue by Nazeth** [Hekili/hekili#35]
Under 82lvl before reach Army of the Dead rotation is broken with active Cooldowns option. Looks like "4x Outbreak, Death Coil, 4x Outbreak..."

To temporary repair that issue i moved Apocalypse and my racial to "None" group from default (cooldowns) and disabled Cooldowns.

After reach 82lvl and unlock AotD skill all is fine

**Comment by Hekili** [comment]
Low levels aren't specifically supported; ability priorities are generally constructed under the assumption that you have access to all your talents.
