### ISSUE TITLE
Keybinding the 'Festermight: Spread Wounds' toggle

### ISSUE THREAD

**Issue by ravisangha** [Hekili/hekili#350]
Hi there, I have never programmed before so I am not sure if what I'm asking is possible but Ill describe what I was thinking. Unholy DK's have a Festermight Spread toggle used to take advantage of the Festermite AZ trait and the DPS increase while bursting multiple wounds in DnD. This feature is incredibly useful and I love it.

 However, when DnD is off CD and the script is telling me to begin spreading wounds on the pack I'm fighting, I know that the pack will not live until the next DnD cast and thus makes the spreading of those wounds useless. I was hoping there was a way to make it so you can keybind that specific toggle so I could decide spreading wounds on so and so pack useful or not depending or not the pack will live long enough to burst those wounds. 

If this isn't possible, it's alright. I wanted to take the time to say thanks for the addon in general, It's helped me alot learn cool tricks and specific insights in a multitude of specs. Thanks : )

**Comment by Hekili** [comment]
I don't have plans to make a keybind for this, but you can toggle it from the minimap icon.

The feature only considers targets without festering wounds that are expected to live at least 4 seconds past DnD's cooldown, or 8 seconds.  Maybe that logic could use refinement.  

You could try editing Classes/DeathKnightUnholy.lua, ~line 1006:
`min_ttd = function () return min( cooldown.death_and_decay.remains + 4, 8 ) end,`

You could increase the `8` to whatever you think seems to be helpful OR remove the 8 entirely:

`min_ttd = function () return cooldown.death_and_decay.remains + 4 end`

Feel free to tinker and see if something works better for you, and report back!  Thanks.
