### ISSUE TITLE
Frost DK - AoE Rotation Not Suggesting Death and Decay

### ISSUE THREAD

**Issue by Cronass** [Hekili/hekili#3500]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Frost DK, in a pack of more than 2 mobs, Death and Decay is not suggested.

### How to Reproduce

1. Enter the game and load onto Death Knight. 
2. Specialize into Frost spec
3. Go to target dummies or any pack of more than 1 mob
4. Note that Death and Decay is never suggested (inside or outside of Cooldowns)

### Snapshot (Link)

https://pastebin.com/5j0ULX8H

### Additional Information

Ran a 10 Nelth and noticed on the first pack that Death and Decay was not suggested. I went the entire key following the addon trying different ability rotations to try and get the addon to suggest DnD but it never popped up.

### Contact Information

Cronus#0545 on Discord

**Comment by Hekili** [comment]
For some reason, `active_enemies` was `1` and most of the target dummies were perceived as being > 10 yards away.  Will take a look at LibRangeCheck and its usage.

**Comment by Hekili** [comment]
LibRangeCheck-3.0 was updated with 1.0.4 and should be resolved.
