### ISSUE TITLE
Unholy DK - AoE Rotation Not Suggesting Epidemic or Vile Contagion

### ISSUE THREAD

**Issue by Cronass** [Hekili/hekili#3501]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my Unholy DK when in a pack of more than 1 mob I was unable to have the addon suggest either Epidemic or Vile Contagion

### How to Reproduce

1. Enter the game on Death Knight
2. Specialize into Unholy
3. Go to target dummy or pack with more than 1 mob
4. Follow addon suggestions (with cooldowns or without) 
5. Note the suggestion recommends Death Coil where it should suggest Epidemic for RP spender

### Snapshot (Link)

https://pastebin.com/K0VMv4py

### Contact Information

Cronus#0545 on Discord

**Comment by Hekili** [comment]
It looks like LibRangeCheck was showing your additional targets at range, `active_enemies` was 1 during your snapshot.  Most of the target dummies were reportedly 30+ yards away, which seems unlikely.  Will investigate.

**Comment by masterkain** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/4836

**Comment by Hekili** [comment]
This should be resolved with 1.0.4 and later (LibRangeCheck-3.0 was updated).
