### ISSUE TITLE
Brewmaster recomending Purifying Brew even when at 0 stagger

### ISSUE THREAD

**Issue by Ayoya212** [Hekili/hekili#3502]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

when playing as Brewmaster and following rotation addon recommends Purifying Brew back to back and even when at 0 stagger

### How to Reproduce

1. Play as Brewmaster
2. Follow rotation

### Snapshot (Link)

https://pastebin.com/Lxqs5A25

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/n8xhEmt7GL4xp89Vkxkt1Y

### Contact Information

boofy0367

**Comment by Hekili** [comment]
I will remove the rotational Purifying Brew entries from the next update; Purifying Brew will respect the damage intake settings at all times.
