### ISSUE TITLE
Practicing rotation

### ISSUE THREAD

**Issue by Jumimaru** [Hekili/hekili#3503]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Practicing my rotation and it broke within 1,5mins of practicing.

### How to Reproduce

I have no clue how to reproduce, but i have the record.

### Snapshot (Link)

https://pastebin.com/AZpN7iep

**Comment by Hekili** [comment]
This looks like a timing issue with events in the engine; basically a spell cast was emulated as finishing but the addon remained in a state where it appeared to be casting.  I have a testfix ready for the next release.
