### ISSUE TITLE
[BUG] Provide a short, clear title for your Bug Report

### ISSUE THREAD

**Issue by DH099** [Hekili/hekili#3505]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Auto snapshot is happening during a fight or on dummies 

### How to Reproduce

1. Play Arcane mage
2. Hit Dummies for a while
3. Hekili hitches, auto snapshots

### Player Information (Link)

https://pastebin.com/xYQ9VYSi

### Error Messages (Link)

https://pastebin.com/MFweb4sR

### Additional Information

Wish I could be more descriptive of the issue, but it just feels like it breaks randomly. 

### Contact Information

dee09 on discord

**Comment by syrifgit** [comment]
Does it still happen on the newest version?

![image](https://github.com/user-attachments/assets/d7cc0d71-026f-41d4-bfea-ada68635de10)
