### ISSUE TITLE
[REC] Cleaving strikes for DK not baked into Death and Decay timings

### ISSUE THREAD

**Issue by Bunta80** [Hekili/hekili#3506]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Death Knight player
I want Hekili to suggest the timings to use Death and Decay which include the Cleaving Strikes buff if talented without having to remember to ignore the suggestion to use it
So that it doesn't not suggest using my next Death and Decay charge until my Cleaving Strikes buff of 4 seconds has run out

### How to Reproduce

1. Log into game as Unholy DK (works on any spec as is class tree, but easier to see on unholy)
2. Go to Gladiators's Refuge in valdrakken to the cleaving training dummies
3. Execute Hekili rotation until second Defile
4. It will suggest Defile, but do not execute it in rotation
5. It will then pick up Cleaving Strikes buff as old Death and Decay fades
6. Will then suggest Defile as Cleaving Strikes buff fades

### Snapshot (Link)

https://pastebin.com/AWJEyyLm

### Contact Information

bunta80

**Comment by syrifgit** [comment]
Can you provide a raidbots quicksim link which shows this behaviour?
