### ISSUE TITLE
Feral not using finishers during opener 

### ISSUE THREAD

**Issue by Rawr-kitteh** [Hekili/hekili#3509]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [x] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During the opener for feral, it is only recommending combo point generators while Berserk is up. It's staying capped at 5cp the entire time until Berserk drops. I am attaching a screenshot to show what I mean. Hekili on top, and below is TrufiGCD, just to show the previous spells used. After berserk, it says to use Feral Frenzy that caps you at 5cp, uses trinket, then goes spam crazy on CP generators until Berserk falls off. 
![hekili](https://github.com/user-attachments/assets/e3547445-9663-494a-964e-1231f7d31f57)

### How to Reproduce

Attached at the bottom is the spec I am using. Just start combat on a target dummy and follow recommendations. 

CcGAqvgeoHLefPLb/Pa8nkKXDBAAAAAAMz2YMLmZMzsMbM2mZmxMzAAAAAAsEwMAGGNzMzwMzwMmtZGAAAAAAADAAAAAAAAAmZGA

### Snapshot (Link)

https://pastebin.com/iRFL7h95

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wYznjzqckJKyjTarTzFvNa

### Contact Information

rawr.kitteh discord

**Comment by syrifgit** [comment]
Please update to the newest version of the addon and let us know if the issue persists, as there were specific feral changes on that version.

![image](https://github.com/user-attachments/assets/a93f383c-748f-4087-a2ec-d5da23f57530)
