### ISSUE TITLE
Hotkey to choose the active profile

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#351]
Hi! The idea to have a hotkey to choose the active profile.
It could be useful to switch profiles depending on situation. For example I am doing my worldquests so I need a PVE rotation but then an opposite factioner comes along and I want to fight him with a different PVP rotation. Thanks!

**Comment by Hekili** [comment]
I'm not likely to pursue this request as described.

I'm more likely to support changing the current priority with macros.

**Comment by IIeTpoc** [comment]
An opportunity to change the current priority with macros would be great! It is even better than the hotkey. Thank you!

**Comment by Hekili** [comment]
With `/hek set` in place for toggles/number values, allowing you to set the *priority* might be something I'm willing to do.

Changing profiles is actually pretty CPU intensive, as all the action lists have to be recompiled and it's a lot.

**Comment by Hekili** [comment]
`/hek profile` will be in the next release.

![image](https://user-images.githubusercontent.com/9438134/101846687-823d1c00-3b1f-11eb-90dc-a9e4998b826d.png)
