### ISSUE TITLE
[BUG] Level 80 Warrior Getting a LUA error and then only Whirlwhind is recommended

### ISSUE THREAD

**Issue by xqzmeBKK** [Hekili/hekili#3510]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

3x Hekili/TheWarWithin/WarriorFury.lua:672: attempt to call global 'applyBuff' (a nil value)
[string "@Hekili/TheWarWithin/WarriorFury.lua"]:672: in function `hook'
[string "@Hekili/Classes.lua"]:6015: in function `callHook'
[string "@Hekili/Events.lua"]:1663: in function <Hekili/Events.lua:1661>
[string "@Hekili/Events.lua"]:1960: in function `handler'
[string "@Hekili/Events.lua"]:74: in function <Hekili/Events.lua:66>

Locals:
_ = 1724366063.151000
subtype = "SPELL_DAMAGE"
_ = false
sourceGUID = "Player-3691-06FC5630"
sourceName = "Xqzmi"
sourceFlags = 132369
_ = 0
destGUID = "Creature-0-4239-2552-2145-214437-0000C7B4E5"
destName = "Seaborne Colossus"
destFlags = 68168
_ = 0
spellID = 445579
spellName = "Slayer's Strike"
school = 1
amount = 60089
interrupt = -1
a = 1
b = nil
c = nil
d = nil
critical = false
(*temporary) = nil
(*temporary) = "sudden_death"
(*temporary) = "attempt to call global 'applyBuff' (a nil value)"
state = <table> {
 swing = <table> {
 }
 role = <table> {
 }
 purge = <table> {
 }
 stat = <table> {
 }
 ptr = 1
 off_hand = <table> {
 }
 holds = <table> {
 }
 display = "AOE"
 prev_off_gcd = <table> {
 }
 active_dot = <table> {
 }
 mainhand_speed = 2.176000
 equipped = <table> {
 }
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 azerite = <table> {
 }
 offset = 0
 hero_tree = <table> {
 }
 pvptalent = <table> {
 }
 action = <table> {
 }
 script = <table> {
 }
 health = <table> {
 }
 active_enemies = 1
 cooldown = <table> {
 }
 stance = <table> {
 }
 gcd = <table> {
 }
 empowerment = <table> {
 }
 varDB = <table> {
 }
 auras = <table> {
 }
 using_apl = <table> {
 }
 max_targets = 0
 recheckTimes = <table> {
 }
 nextOH = 41467.603000
 main_hand = <table> {
 }
 longest_ttd = 3.554638
 selected_action = "bloodbath"
 min_targets = 0
 artifact = <table> {
 }
 talent = <table> {
 }
 covenant = <table> {
 }
 true_stationary_enemies = 1
 predictionsOn = <table> {
 }
 dot = <table> {
 }
 spec = <table> {
 }
 nextMH = 41467.603000
 encounterDifficulty = 0
 filter = "none"
 index = 1
 true_active_enemies = 1
 items = <table> {
 }
 player = <table> {
 }
 prev = <table> {
 }
 empowering = <table> {
 }
 debuff = <table> {
 }
 this_action = "slam"
 channel_breakable = false
 bfa_essence = <table> {
 }
 rangefilter = true
 buff = <table> {
 }
 raid_event = <table> {
 }
 encounterName = "None"
 table = <table> {
 }
 spell_targets = <table> {
 }
 now = 41466.867000
 pet = <table> {
 }
 runeforge = <table> {
 }
 consumable = <table> {
 }
 torghast = false
 delayMax = 0.250000
 race = <table> {
 }
 predictions = <table> {
 }
 resetType = "none"
 cycleInfo = <table> {
 }
 conduit = <table> {
 }
 rage = <table> {
 }
 scriptID = "Fury:single_target:25"
 resetting = false
 totem = <table> {
 }
 trinket = <table> {
 }
 predictionsOff = <table> {
 }
 hyperthread_wristwraps = <table> {
 }
 legendary = <table> {
 }
 arena = false
 _G = 0
 targets = <table> {
 }
 system = <table> {
 }
 soulbind = <table> {
 }
 class = <table> {
 }
 selection_time = 0.250000
 target = <table> {
 }
 swings = <table> {
 }
 offhand_speed = 2.176000
 faction = "Horde"
 queue = <table> {
 }
 delay = 0.250000
 GUID = "Player-3691-06FC5630"
 sim = <table> {
 }
 Enum = <table> {
 }
 encounterID = 0
 max_empower = 3
 prev_gcd = <table> {
 }
 combat = 41464.275000
 movement = <table> {
 }
 bg = false
 cast_target = "Creature-0-4239-2552-2145-214437-0000C7B4E5"
 PTR = true
 settings = <table> {
 }
 delayMin = 0
 realQueue = <table> {
 }
 aura = <table> {
 }
 toggle = <table> {
 }
 set_bonus = <table> {
 }
 variable = <table> {
 }
}
class = <table> {
 totems = <table> {
 }
 talents = <table> {
 }
 abilityList = <table> {
 }
 stateExprs = <table> {
 }
 auras = <table> {
 }
 pets = <table> {
 }
 itemPack = <table> {
 }
 abilityByName = <table> {
 }
 interrupts = <table> {
 }
 gear = <table> {
 }
 trinkets = <table> {
 }
 packs = <table> {
 }
 setBonuses = <table> {
 }
 itemList = <table> {
 }
 knownAuraAttributes = <table> {
 }
 primaryResource = "rage"
 file = "WARRIOR"
 stateTables = <table> {
 }
 stances = <table> {
 }
 auraList = <table> {
 }
 powers = <table> {
 }
 range = 8
 itemSettings = <table> {
 }
 hooks = <table> {
 }
 essence_unscripted = false
 settings = <table> {
 }
 num = 4
 resources = <table> {
 }
 initialized = true
 specs = <table> {
 }
 stateFuncs = <table> {
 }
 pvptalents = <table> {
 }
 potionList = <table> {
 }
 resourceAuras = <table> {
 }
 variables = <table> {
 }
 toggles = <table> {
 }
 potions = <table> {
 }
 itemMap = <table> {
 }

### How to Reproduce

I enter the game as a warrior
As soon as I pull two or more mobs outside of a dungeon Hekili only recommends Whirlwind.
In every dungeon it's working normally

### Player Information (Link)

https://pastebin.com/x1QZGszH

### Error Messages (Link)

https://pastebin.com/Xg0TAwTg

### Contact Information

xqzme on discord

**Comment by syrifgit** [comment]
Snapshot and info from user @Mosborne90 on duplicate ticket https://github.com/Hekili/hekili/issues/3519

https://pastebin.com/5LD2iS0z

```
I'm not certain what is triggering this issue. I've noticed over 5 times now that Hekili is sometimes only recommended Whirlwind for the multi target rotation for Fury Warrior at level 80. Reloading the addon a couple of times seems to fix the issue. Once the issue happens, the multi target rotation will only recommend whirlwind outside of major cooldowns.
```

**Comment by syrifgit** [comment]
This issue has been reported as fixed with the newest update
![image](https://github.com/user-attachments/assets/474019d4-5eba-4ed2-b978-d66ff730ae82)
