### ISSUE TITLE
Enhance Shaman Rotation Issue - Recommending Tempest At Zero Maelstorm 

### ISSUE THREAD

**Issue by OppYchan** [Hekili/hekili#3511]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Tempest is being recommended when you have zero maelstorm and it should be recommended at 10 stacks only. Also when its procs it shows up 3 times in the priority windows for the next 3 globals even though it should just show for one.

### How to Reproduce

get tempest proc with no maelstorm and it will show it.
![Tempest](https://github.com/user-attachments/assets/19fa0c8c-e228-4342-8263-9c706673a5a4)

### Snapshot (Link)

https://pastebin.com/Q4XxxRN4

### Additional Information

Never posted something before. Sorry if I did it wrong.

**Comment by Hekili** [comment]
The snapshot should be many lines of text, not just one.  Make sure to CTRL+A before pressing CTRL+C to copy the text.

Also, update to v11.0.2-1.0.2 before retesting.  Thanks!
