### ISSUE TITLE
Queued abilities for Unholy DK not showing

### ISSUE THREAD

**Issue by hotnac** [Hekili/hekili#3513]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Queued abilities for Unholy DK not showing, sometimes no recommendations are displayed.

### How to Reproduce

Just play Unholy DK

### Snapshot (Link)

https://pastebin.com/RLQdNfSt

**Comment by Stoufs** [comment]
Happening to me as well

**Comment by Stoufs** [comment]
I should add that I find it happens mostly when i switch targets

**Comment by Stoufs** [comment]
I just tested this again in few dungeons and its gotten much worse. The recommendations queue had less then 10% uptime.

**Comment by syrifgit** [comment]
Can either of you provide a full snapshot? @Stoufs @hotnac 

The original snapshot link is not a full snapshot, it should be a giant wall of text not just 1 line. You need to press CTRL-A then copy it from the addon to make sure you get it all.

See: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by Stoufs** [comment]
edited.

**Comment by syrifgit** [comment]
Can you put it into a pastebin and edit your comment lol @Stoufs 

https://pastebin.com/

**Comment by Stoufs** [comment]
https://pastebin.com/y0gxg8sY

**Comment by syrifgit** [comment]
Seems related to https://github.com/Hekili/hekili/issues/3501 maybe? In the same recommendation, it's showing D&D both ticking and not ticking

```
        53.  call_action_list:aoe_setup ( default - 12 )
        Time-sensitive Criteria FAIL at +2.14 with no valid rechecks - active_enemies[5.00] >= 3 & ! death_and_decay.ticking[true] & cooldown.death_and_decay.remains[0.00] < 10
```

```
        55.  epidemic ( aoe_burst - 1 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Unholy-aoe_burst-1:epidemic:0.02:Ability Known, Enabled(0.02)
```


```
 56.  wound_spender ( aoe_burst - 2 )
         - no aura identified for target-cycling and no aura matching scourge_strike found in ability / spec module; target cycling disabled.
        The action (wound_spender) is usable at (2.14 + 1.09) with cost of 1 runes (have 3).
         - the action is ready before the current recommendation (at +1.09 vs. +10.00).
        List ( aoe_burst ) called from ( Unholy:default:13 ) would FAIL at 1.09.
        active_enemies[5.00] >= 3 & ( death_and_decay.ticking[false] | buff.death_and_decay.up[false] & death_knight.fwounded_targets[4.00] >= ( cycle_enemies[5.00] * 0.5 ) )
         - this entry would not be reached at the current time via the current action list path (1.09).
        There were no recheck events to check.
        Time spent on this action:  0.13ms
        TimeData:Unholy-aoe_burst-2:wound_spender:0.13:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.01):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.04):Pre-Recheck(0.00):Post-Recheck Times(0.01):Post Recheck(0.00)
```

**Comment by Stoufs** [comment]
That is a great question lol. Would that cause it to disappear? Thats what seems to be happening. The recommendation window usually will show 3 spells normally but when i am unholy its only showing one and then it starts disappearing and occasionally will show up but for some reason today's worse.

**Comment by hotnac** [comment]
Could it be that D&D is now called Defile?

**Comment by purefreakz** [comment]
https://github.com/Hekili/hekili/issues/3524

My problem looks the same. And I added a snapshot

**Comment by Stoufs** [comment]
Unfortunately, still a thing with the new update

https://pastebin.com/YwDddTNM

**Comment by syrifgit** [comment]
What about the newest version from today?  @Stoufs 

![image](https://github.com/user-attachments/assets/2fa575da-17c0-40a0-aba1-8581dd08c923)

**Comment by Hekili** [comment]
Testfix in 1.0.5

**Comment by syrifgit** [comment]
Reported as still not working in 1.0.5a by discor user Tappy. Quick analysis is that it thinks wound spender (Scourge strike?) cannot be cast for 13 more seconds despite having the resources. It specifically happens after casting dark transformation.

https://pastebin.com/ytKNUYnz

**Comment by syrifgit** [comment]
I believe this was fixed by changing wound spender stuff in an earlier release.
