### ISSUE TITLE
Demon hunter hero talents never being recommended. 

### ISSUE THREAD

**Issue by bsdgaming** [Hekili/hekili#3514]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Reaver's glaive does not seem to be recommended at all. 

### How to Reproduce

Do a rotation on demon hunter. Havoc and Vengeance both effected 

### Snapshot (Link)

https://github.com/Hekili/hekili/blob/thewarwithin/TheWarWithin/DemonHunterVengeance.lua

**Comment by MatteoLombardi** [comment]
I'll add the spell to this open issue: #3450

**Comment by syrifgit** [comment]
Is this still happening? @bsdgaming 

edit: Oops nevermind I See your comment in the other ticket.

![image](https://github.com/user-attachments/assets/c2bf1c1f-6121-4caf-809a-a8bea174f4e9)

**Comment by syrifgit** [comment]
Closing this ticket as it is contained in https://github.com/Hekili/hekili/issues/3451 via https://github.com/Hekili/hekili/issues/3531#issuecomment-2309040708
