### ISSUE TITLE
[BUG] Havoc Demonhunter: Somtimes no recommendations are made anymore

### ISSUE THREAD

**Issue by sK4r4** [Hekili/hekili#3515]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Sometimes while questing/dungeon whatever, hekili just stops makes recommendation for anything. After a few secs recommendations are back usually but even then the recommendations are not kinda right because often chaos strike and throw glaive are not recommeneded

### How to Reproduce

Just play/fight

### Player Information (Link)

https://pastebin.com/basjrjhe

### Error Messages (Link)

no error

### Contact Information

Skara#2856

**Comment by MatteoLombardi** [comment]
Are you playing Arathi Reaver hero talent?

**Comment by sK4r4** [comment]
No, I play the Fel-Scarred Tree

**Comment by Jacky7533** [comment]
it's not returning back to the main action list after it finishes running through 'opener' with no suggestions

https://pastebin.com/5KKfyyxS

https://pastebin.com/6ehBDaXK

**Comment by GoochWookie** [comment]
I am playing havoc DH and I am getting recommendations for skills that are on CD

**Comment by sK4r4** [comment]
> I am playing havoc DH and I am getting recommendations for skills that are on CD

Yeah, that’s usually happening when recommendations are back. Sometimes a 8 sec cd spell is shown next when other possibilities are there

**Comment by Jacky7533** [comment]
Unsure if the new update fixes the reconmendation, if so, it is still happening to me.

I also noticing that I'm not getting Metamorphsis reconmended at all.

https://pastebin.com/ciHn96Q5

https://pastebin.com/0VcUZtgM

**Comment by sK4r4** [comment]
> Unsure if the new update fixes the reconmendation, if so, it is still happening to me.
> 
> I also noticing that I'm not getting Metamorphsis reconmended at all.
> 
> https://pastebin.com/ciHn96Q5
> 
> https://pastebin.com/0VcUZtgM

Yeah, i have the feeling that the addon waits for the perfect opportunity to use meta, even if it means that it waits like 1 minute.

**Comment by Hekili** [comment]
> I also noticing that I'm not getting Metamorphsis reconmended at all.

There are a couple of reasons for this; if you don't allow Vengeful Retreat to be recommended but take Initiative, the priority is written to expect Initiative resets that the addon isn't allowed to recommend.  I am making adjustments to allow this to be ignored, but just a reminder that if you take Initiative, you probably want to enable the addon to recommend Vengeful Retreat, etc.

**Comment by sK4r4** [comment]
> > I also noticing that I'm not getting Metamorphsis reconmended at all.
> 
> There are a couple of reasons for this; if you don't allow Vengeful Retreat to be recommended but take Initiative, the priority is written to expect Initiative resets that the addon isn't allowed to recommend. I am making adjustments to allow this to be ignored, but just a reminder that if you take Initiative, you probably want to enable the addon to recommend Vengeful Retreat, etc.

Does not seem to work. I don't have Vengeful Retreat dissabled but Meta is not recommended after vengeful retreat in the opener.
In this snapshot, Meta should have been recommended right after the first vengeful retreat (#4), but it wasn't: https://pastebin.com/X3QvPkuA
