### ISSUE TITLE
[REC] Enhancement SHaman recommending Tempest <5 Maelstrom Weapon

### ISSUE THREAD

**Issue by TheSaladBlaster** [Hekili/hekili#3517]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon is recommending to hit Tempest below 5 maelstrom which would cause to not even be instant cast,

### How to Reproduce

If you play through the rotation for enough eventually you will hit a point where you prime your next tempest but don't have the Maelstrom to let it rip. This is when it gives the erroneous recommendation. 

### Snapshot (Link)

https://pastebin.com/wqMr03C3

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vKQwXbf9b4XcLQE42NhE7A

### Contact Information

Discord - SaladBlaster

**Comment by syrifgit** [comment]
You are not running the newest version of the addon, please update and let us know if the issue is still happening. Enhance specifically received changes in this update.

**Comment by TheSaladBlaster** [comment]
I updated it 4 hours ago and there are no new updates available.

**Comment by syrifgit** [comment]
> I updated it 4 hours ago and there are no new updates available.

Can you get a new snapshot of the issue on the new version then? Your snapshot is from version `v11.0.2-1.0.1a`, but the addon is now at `v11.0.2-1.0.2` on Curseforge, and there were a lot of changes to Enhance APL in that update.

**Comment by TheSaladBlaster** [comment]
Thank you, I could have sworn it was doing it after I updated, but I guess not. So sorry to bother you with such triviality!
