### ISSUE TITLE
Delay rotation suggestions if target is partly immune or full immune to damage.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#352]
Hi! The idea is to auto-delay rotation suggestions if target is partly immune to damage. For example target could be immune to physical damage and the addon sees it and suggests to cast magic damage spells. 
It might be created in form of library where addon checks the target`s auras and either pause the suggestions if target is full immunte to damage or make different suggestions depending on the type of immunity.

**Comment by Hekili** [comment]
I'm not aware of any API or libraries that I can rely on for this information, and I don't want to create a library that would require additional maintenance on my part.

If a library exists, feel free to point it out.  Otherwise, this isn't going to happen.

**Comment by IIeTpoc** [comment]
I see if there is no API for this of course it is a massive work for very minor profit to create such a library from scratch. Thank you for the answer!
And is it possible in blizzard API to check for target's buffs? And make such a function for addon to be able to check "if target has buff from the list (and every person will do their own preferable list editing notepad version of the code) then don't cast any spell till the buff is down"?

**Comment by IIeTpoc** [comment]
@Hekili I actually found something considering this topic and want to share starting from the most complicated to the easiest on my opinion.
1. A working API which allows to retrieve auras by name [LINK](https://wow.gamepedia.com/API_AuraUtil.FindAuraByName) 
2. An updated to BFA library of target's auras which includes immunity types and it is called LibAuraTypes [LINK to the GitHub](https://github.com/rgd87/LibAuraTypes/blob/master/LibAuraTypes.lua). 
If I am not mistaken this lib was originated for WoW-Classic but there is a full support for the retail aswell in its Core.lua. Also I've written to the autor of that lib (he is also the author of the LibClasssicAura) asking him about the updating retail-only lib but currently I am waiting for his answer.
3. [BigDebuffs](https://github.com/jordonwow/bigdebuffs) addon which also has Retail.lua with all needed immunity auras.
4. Teach/allow us please to manually add condition for spell checking if buff is present or not (as a simple example when I use in-game addon for priority modification allow adding a condition to the spell like ["Heroic strike" if rage > 80 and !target.buff.41450] 41450=BoP in this case)

**Comment by Hekili** [comment]
Ok.

1. This made me laugh.  Yes, I know how to retrieve auras by name.  Thanks.

2. Looks like a good source of player auras; doesn't address immunities in PvE.

3. Looks like it contains roughly the same info as #2.

4. I deliberately don't want people to try to do priority stuff with unsupported auras, which is why I add them as needed.  I'll think about it.  If you need to learn about writing priorities, check out SimulationCraft's wiki.

**Comment by IIeTpoc** [comment]
@Hekili At least I put you in a better mood for a moment. I'd say it was worth posting  then hehe.

To be honest I don't think there are any partial immunities in the end-game PVE content and basicly the reason I need to code those conditions is because I am learning PVP and I want to "teach" the addon to stop suggesting me magic-damage spells during rogue's Cloak of Shadows, DK's Anti-Magic Shell and physical damage spells during paladin's Hand of Protection.

I will check SimCraft's wiki and try to figure out how to condition these "unsupported" auras to the my spells, thanks for the hint!
