### ISSUE TITLE
Ret Paladin: Not recommending "Hammer of Light" after using "Wake of Ashes"

### ISSUE THREAD

**Issue by xilostcause** [Hekili/hekili#3520]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Ret Paladin, Hekili does not recommend using "Hammer of Light" which is a new button that replaces "Wake of Ashes" after using. It is the first node on the Templar Hero tree called "Lights Guidance"

### How to Reproduce

1. Be Ret Paladin with "Wake of Ashes" and the first node of the Templar hero talent tree unlocked called "Light's Guidance"
2: Enter combat and using "Wake of Ashes"
3: Upon having 5 holy power you should be able to use the follow-up action called "Hammer of Light"

### Snapshot (Link)

https://pastebin.com/feUHMian

**Comment by MatteoLombardi** [comment]
This issue has been already notified in #3450, passing your snapshot over

**Comment by ozsum** [comment]
I don't know if it's related but I was looking over the profile for Ret. And I found a line for finishers that goes:
actions.finishers+=/divine_hammer

As far as I know, Divine Hammer isn't a finisher so I changed that "divine_hammer" to "hammer_of_light" and it started being recommended.

**Comment by syrifgit** [comment]
This has been fixed, make sure you are updated to the newest version

![image](https://github.com/user-attachments/assets/ed2df41b-5681-471b-b759-71eb2dc2eda9)
