### ISSUE TITLE
[REC] Blood DK: Heart Strike/Vampiric Strike not being SpellFlashed

### ISSUE THREAD

**Issue by PopsGG** [Hekili/hekili#3521]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With hero talents the **Heart Strike** skill can sometimes turn into **Vampiric Strike**. It is correctly being recommended in the rotation, but it is not be highlighted with SpellFlash

### How to Reproduce

1. Enter game as a Blood DK
2. Engage in combat
3. As soon as Heart Strike is recommended, you will see it is not SpellFlashed.
4. There is a 10% chance the next Heart Strike will be Vampiric Strike, it is also not SpellFlashed

### Snapshot (Link)

https://pastebin.com/5E1XbAeE

**Comment by PopsGG** [comment]
After further testing the issue doesnt present until you proc the 10% chance the to turn next Heart Strike to Vampiric Strike

**Comment by PopsGG** [comment]
This seems to happen with other Hero Talents that transform 1 skill into another. For example Ret Paladin: "Lights Guidance" converts "Wake of Ashes" to "Hammer of Light", then the skill is no longer SpellFlashed.

**Comment by Hekili** [comment]
I would need the updated spell IDs for these spells when they are not flashing.

**Comment by PopsGG** [comment]
I do not want to confuse the issue. After more testing think the pally issue unrelated/different.

I tested again with Blood DK with the latest version and I cannot reproduce. It is working perfectly now.

**This can be closed.** Thank you.

**Comment by PopsGG** [comment]
Nevermind. I am not sure what the conditions to reproduce are. I cannot reproduce at the target dummy, but it happens in instances when grinding.

The spell ID that is not highlighting is: 433895

**Comment by PopsGG** [comment]
Paladin issue is reproducible in the wild too. 

Wake of Ashes will not SpellFlash: ID 255937

**Comment by PopsGG** [comment]
Same thing happens for Prot warriors. 

Hero talent makes Thunder Clap transform into Thunder Blast (ID: 435222), it does not SpellFlash

**Comment by Hekili** [comment]
Should be fixed.
