### ISSUE TITLE
[REC] Farseer Shaman does not recognize the use of Ancestral Swiftness

### ISSUE THREAD

**Issue by djcosmic22** [Hekili/hekili#3522]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon recommends Ancestral Swiftness, once used it keeps recommending it even thought it has been used and is waiting to use a spell (usually Lava Burst) to trigger it. 

Spell is similar to Nature's Swiftness (Shaman) and Tip the Scales (Evoker) Where It gives you a buff, then the next spell you use has a modified effect, and then the ability goes on cooldown.

### How to Reproduce

1. Enter game as Farseer Shaman
2. DPS

### Snapshot (Link)

https://pastebin.com/JijJsujb

**Comment by syrifgit** [comment]
Does this still happen on the newest version? 

![image](https://github.com/user-attachments/assets/dbaed74f-532f-4d06-b565-206c99a7d339)

**Comment by djcosmic22** [comment]
yes

**Comment by Hekili** [comment]
This will be resolved in 1.0.5.
