### ISSUE TITLE
[BUG] Error in Unholy Rotation M+

### ISSUE THREAD

**Issue by purefreakz** [Hekili/hekili#3524]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Error in rotation. Tells in chatbox: "Unable to make recommendation for Primary #3; triggering auto-snapshot...."

Worked fine 1 week ago. Until then only problems with it ...

### How to Reproduce

Just use m+ rotation and start fighting. Always appears and primary bar not fill up.

### Player Information (Link)

https://pastebin.com/sCkwrGpY

### Error Messages (Link)

https://pastebin.com/sCkwrGpY

**Comment by syrifgit** [comment]
Can you confirm if this still happens on the newest version?

![image](https://github.com/user-attachments/assets/e055af87-7f17-447f-96c3-93849d950146)

**Comment by purefreakz** [comment]
Good morning. Single Target don't give snapshots. Multitarget still does but with a new error. Primary #4 is now the problem. 

Here is the paste: https://pastebin.com/vfMaGFkJ

**Comment by purefreakz** [comment]
CwPAtbMOTHlnKIwUyAn+DK70SDgZGjZMDDzMzMzMNMmZGzYAAAAAAAAAMMzYGzMzMDAYDMLGzMzMMzA2MbGGyAzGDNWwAMDA

Here is the Talents export. Maybe helps.

**Comment by Hekili** [comment]
Testfix in 1.0.5.
