### ISSUE TITLE
Sub Rogue Pressing shadowstrike 3 times in a row at max combo points

### ISSUE THREAD

**Issue by Painxd2** [Hekili/hekili#3525]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

as i said the opener is fine but after 10 seconds ish , hekili wants to press shadowstrike 3 times in a row at max combo points, and also after evis give you max combo points, you should press evis again but the addon says shadowstrike or backstab instead.

### How to Reproduce

enter as sub rogue , do a sim at 5 minutes you wont see any time there are multiply combo builder back to back at max points.
and if you get your combo points back you should use a finisher.

### Snapshot (Link)

https://pastebin.com/m293r0z0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/a6QrZExjgrxCzC25KogYtn

### Contact Information

jonnygodx

**Comment by Painxd2** [comment]
and also when nimble flurry is active u should press evis instead of Black powder , i can make a second ticket for it if needed

**Comment by Painxd2** [comment]
https://pastebin.com/VSWjz5ti new Snapshot from the new version

**Comment by Hekili** [comment]
It looks like Deathstalker's Mark is not being detected on your target.  Can you confirm whether or not Deathstalker's Mark is visible on the target?  Can you see the spell ID?

**Comment by 1oc0** [comment]
same issue here. Deathstalker's Mark cant be on target, thats trickster build problem

**Comment by Painxd2** [comment]
im not playing with deathstalker im playing with trickster , so Deathstalkers Mark cant be on the target.

Edit: i tested it with deathstalker and the rotation is fixed and good, so its only trickster problem.

**Comment by Hekili** [comment]
Remaining issue will likely be solved by v11.0.2-1.0.4 (solving the "both hero trees active" bug).
