### ISSUE TITLE
DH Fel-Scarred icon changes when meta, but keybinds dont copy to match the ability name change

### ISSUE THREAD

**Issue by Sheerphenom** [Hekili/hekili#3526]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

On DH, if you are fel-scarred, when you are in meta all your abilities change names and for whatever reason when this happens Hekili does not pull my keybind. 

Spirit Bomb is on shift + 2 displayed as S2 in Hekili, but when I meta and it becomes Spirit Burst (still on Shift + 2), the icon appears in the queue correctly but without the keybind displayed. 

### How to Reproduce

Enter the game as a DH and press meta after choosing the fel scar talent trees and it will be able to be replicated.

### Snapshot (Link)

I don't have a snapsho

**Comment by TreeOfLearning** [comment]
Not my issue but I will provide a snapshot: https://pastebin.com/5NT0WzTv

This has Sigil of Flame recommended twice, but no keybinds, as it is the empowered version

**Comment by Hekili** [comment]
Should be resolved in v11.0.2-1.0.4; if not, please reopen with an updated snapshot.
