### ISSUE TITLE
Fury warrior Mountain Thane Thunder clap/crushing thunder issue

### ISSUE THREAD

**Issue by Shamuraj** [Hekili/hekili#3527]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I expect the addon to recomment Crushing Thunder with 2 stacks of Thundering BLast, but i doesnt ever, not event regular thunder clap, just Whirlwinds.

### How to Reproduce

Engange any Single or Multi target combat, continue with rotation and see that in mountain thane hero talents you wont get thunder calp/crushing thunder recommended. It's not event on the list of abilities anywhere in fury rotation.

Also I have a Havoc rotation im my specs :)
![Zrzut ekranu 2024-08-24 085130](https://github.com/user-attachments/assets/d27f5d85-2664-4fda-9c3f-349186eae01b)

### Snapshot (Link)

https://pastebin.com/r5qPHpVv

**Comment by Shamuraj** [comment]
Its weird cus i Simmed my fury mountain thane and in 5 mins thers no CT/TC used and the sim goes on 5 mins with 2 stacks of Thunder Blast. Its either a bug or I dont understand the point of this build as my understanding is to use CT instead of WW for 4 stacks of cleave or to use CT with 2 stacks for big DMG.

**Comment by SeaStove** [comment]
I had a similar confusion, i thought maybe it was undertuned but im guessing ignoring thunderclap is a bug since anecdotally it just deletes things when you press it (even if not recommended), feels very good in the rotation when used

**Comment by Hekili** [comment]
Should be resolved in next release (v11.0.2-1.0.4).

**Comment by Hekili** [comment]
Yeah, the sim profile currently doesn't use Thunder Clap at all.  I've revised Fury based on the Icy-Veins guide in v11.0.2-1.0.4.
