### ISSUE TITLE
Assassination Rogue not recommending Garrote, Rupture after target swap

### ISSUE THREAD

**Issue by zzhao223** [Hekili/hekili#3528]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Assasination rogue doesn't recommend garrote/ rupture when switch targets， feel really short on energy。

### How to Reproduce

when u switch target it wont recommend garrote/ rupture first 

### Snapshot (Link)

https://pastebin.com/kSUhNUUb

### Contact Information

zihaozhao213@gmail.com

**Comment by Hekili** [comment]
You will need to provide a complete snapshot when this is occurring.  Snapshots are hundreds/thousands of lines of text.  Make sure to CTRL+A to select all text (even hidden text) in the snapshot box, then CTRL+C to copy.  Thanks.
