### ISSUE TITLE
[REC] Provide a short, descriptive title of you Recommendation issue

### ISSUE THREAD

**Issue by esergiosantos** [Hekili/hekili#3529]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I actually have a problem with the death and decay keyboard shortcut, I use 2 macros, one for @mouseover and another for @player, but in the rotation I would like it to show only the @player keybind which is R, but even changing the settings Hekili recommends CT which is the shortcut for my @mouseover

![image](https://github.com/user-attachments/assets/c2dc7078-1a06-4342-bafd-45e44030166e)
![image](https://github.com/user-attachments/assets/c3a81a23-9cc0-4579-a1c8-d45ded3857fa)

### How to Reproduce

Enter game as BDK, change keybind death and decay not work 

### Snapshot (Link)

https://pastebin.com/26zAxprg

### Contact Information

serg

**Comment by syrifgit** [comment]
Does this still happen on the newest version?

![image](https://github.com/user-attachments/assets/5db82a23-5d89-4b0b-a932-9b7638ebe2b1)
