### ISSUE TITLE
Interruption spell list.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#353]
Hi! The idea is to have a spell list so the interruption suggestion will only show up if the casted spell is from the list and of course make a way to modify the spell list.
It could be useful for example in mythic plus or in horrific visions or even in raids where mobs have different interruptable spells but some of them are "harmless" and some are "deadly" thus it would be great if addon suggests to kick only "deadly" spells.

**Comment by Hekili** [comment]
This has been discussed before and I'm not opposed, I just haven't found a good time to work on it vs. other addon-related projects.

It may also be a bit challenging to come up with an options interface for including/excluding particular spells or settings from the interrupts list.  But yeah, I'd want to do this for interrupts as well as offensive dispels or spellsteals.  Eventually.

**Comment by IIeTpoc** [comment]
I see. Thank you!
