### ISSUE TITLE
[FEATURE] Out of combat and druid flight form hide option.

### ISSUE THREAD

**Issue by Fafnir0681** [Hekili/hekili#3530]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I would like the option to hide the HUD of this addon for whenever i am not in combat and for whenever i am in druid flight form. A simple check box in the settings just like you have for whenever you are mounted in PVE and PVP content. It would be really helpful for keeping my visual screen real estate as clean a s possible.

**Comment by syrifgit** [comment]
The out of combat option already exists

**Comment by Fafnir0681** [comment]
Okay, i finally found it. Now that I know how it works forget the druid form suggestion. 

However, could you put a description statement over the "Default" slide bar for both the pvp and pve hide options that state setting the slide bar to "0" makes the HUD hide function activate?

**Comment by syrifgit** [comment]
> Okay, i finally found it. Now that I know how it works forget the druid form suggestion.
> 
> However, could you put a description statement over the "Default" slide bar for both the pvp and pve hide options that state setting the slide bar to "0" makes the HUD hide function activate?

Maybe? That's sort of what alpha/opacity means in UI and graphic design context, and you'll see it on every other addon as well. If the default is 0 and combat is 1, it won't show until you are in combat. I think it's already explained by the current tooltips.
