### ISSUE TITLE
[REC] Windwalker Monk abilities show inappropriate delay, twice, or no recommendation on v11.0.2-1.0.2

### ISSUE THREAD

**Issue by zmsl** [Hekili/hekili#3532]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The latest update to the Windwalker priority is not working as well as the previous version. I have tested on multiple different specs but all experience the same issues.

Issue 1: During the normal course of a rotation, any ability can have a delay recommended when the ability should and can be used immediately.
Issue 2: Occasionally Hekili will fail to recommend an ability, resulting in an automatic snapshot
Issue 3: Abilities are sometimes recommended twice in a row, which loses monk mastery bonus

### How to Reproduce

1. Enter game as Windwalker Monk levels 70-80
2. Use any of the recommended Raid or M+ talents for either Shado-pan or Celestial hero talents
3. Fight enemies and notice the ability delay, repetitive, or broken recommendations

### Snapshot (Link)

https://pastebin.com/SRwCSaTi

### Additional Information

BoK Delayed: [https://pastebin.com/xvgy2LTz](https://pastebin.com/xvgy2LTz)
SotW Delayed: [https://pastebin.com/DWyuiEAA](https://pastebin.com/DWyuiEAA)
TP Delayed / Overcapping Energy: [https://pastebin.com/ncCMgGzt](https://pastebin.com/ncCMgGzt)
TP Recommended Twice: [https://pastebin.com/dx75hZzP](https://pastebin.com/dx75hZzP)
No Recommendation (auto-snap): [https://pastebin.com/SRwCSaTi](https://pastebin.com/SRwCSaTi)

### Contact Information

defzach

**Comment by Targonis1259** [comment]
This is also occurring to me, I was going to submit it as an issue but found this has already been submitted. If needed, I can add appropriate snapshots. I will watch for a response to see if my information is also required for troubleshooting. Thank you.

**Comment by Hekili** [comment]
This is related to timing for the opener; it looks like treating every pull moving pack-to-pack like a clean pull is probably not the way to go.  I wonder if you'd see similar odd behavior simming a dungeonroute on Raidbots.

**Comment by Nusarai** [comment]
Not sure if its any use but, after the update i tested on dummy's, looked good at the start but after a while it disappeared again.
i took a snapshot in case there is any help in that
[Windwalker; Primary - NA.txt](https://github.com/user-attachments/files/16742429/Windwalker.Primary.-.NA.txt)

**Comment by Hekili** [comment]
It looks like the current priority allows for breaking Hit Combo with Tiger Palm, but the addon doesn't.  I'll relax this requirement in 1.0.5, but will need a new snapshot and Raidbots sim if the issue persists.

**Comment by zmsl** [comment]
So far so good on the new version. Will continue testing and open a new issue with new snapshots if other issues arise.
