### ISSUE TITLE
[REC] What is the secondary "2" showing on the bottom of my Hekili icon here for Frostbolt?

### ISSUE THREAD

**Issue by Lithkur** [Hekili/hekili#3533]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello, I am a new Hekili user. And I am trying to achieve an display where just the keybind is shown large in the center of my icon. However, when I did that, I noticed another number sometimes showing at the bottom like in the screenshot. How do I hide this extra number? What is it? I assumed it was spell charges, but frostbolt does not have an extra charge.
![Capture](https://github.com/user-attachments/assets/e8acc5e0-4770-40aa-82e9-ac7838d567ad)

### How to Reproduce

Unsure

### Snapshot (Link)

https://github.com/user-attachments/assets/e8acc5e0-4770-40aa-82e9-ac7838d567ad

**Comment by Hekili** [comment]
The number of targets currently detected.

**Comment by Lithkur** [comment]
Ah understood, so that ends up crowding my screen when I try to enlarge the keybind text.

Can I turn that indicator off? Or make it appear somewhere else?
