### ISSUE TITLE
[REC] Feral Druid Hero Talent Ravage not Recommended at all during Rotation

### ISSUE THREAD

**Issue by Troxlear** [Hekili/hekili#3536]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Feral Druid Hero Talent Ravage not Recommended at all during Rotation. 

### How to Reproduce

Tried it many times Ravage doesnt seem to get Recommended in Rotation

### Snapshot (Link)

will try to get a snapshot

### Contact Information

Troxlar

**Comment by Hekili** [comment]
Feel free to (re)open if/when you have a snapshot.

**Comment by Bigity** [comment]
I think the issue is it shows up in the display, but it will not flash on your bars like other abilities.  So if you have the displays hidden, you don't see any recommendation for Ravage.

**Comment by Troxlear** [comment]
Will try that later playing with Spellflash. Maybe it will show up when i disable Spellflash and use display. Thx for the reply :)
