### ISSUE TITLE
[REC] Hammer of Light being recommended without enough holy power to cast it

### ISSUE THREAD

**Issue by dglynch** [Hekili/hekili#3537]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For my retribution paladin, I expect the addon to only recommend a holy power spender (such as Hammer of Light) when I have enough holy power available to cast it. However, instead the addon is recommending Hammer of Light when I only have four holy power. Five holy power is required to cast the spell.

### How to Reproduce

Approach a target dummy, begin rotation according to the addon's recommendations. After casting Wake of Ashes, the addon will recommend Hammer of Light. Try to cast it, but it is greyed out due to lack of holy power.

### Snapshot (Link)

https://pastebin.com/xWNGV0vd

**Comment by Hekili** [comment]
Resolved by v11.0.2-1.0.4.
