### ISSUE TITLE
[BUG] Demolition not being recommended.

### ISSUE THREAD

**Issue by YomamaNow** [Hekili/hekili#3538]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Demolition not being recommended.

### How to Reproduce

Exist as an Arms Warrior.

### Player Information (Link)

https://pastebin.com/Mikpzqeq

### Error Messages (Link)

none

### Contact Information

Discord Armsparty

**Comment by Hekili** [comment]
Is "Demolition" the same as "Demolish"?  If so, you'll note that your sim (Raidbots) also does not use it (yet).  I'll shoehorn it in based on Icy-Veins' guide until sims are updated.  Fix in v11.0.2-1.0.4.
