### ISSUE TITLE
Soul Strike part of rotation when Felhunter summoned

### ISSUE THREAD

**Issue by xxLasherxx** [Hekili/hekili#354]
Works great until something other than Felguard is summoned. Then calls for Soul Strike in rotation which cant be done when Felhunter is summoned.

build: v8.3.0-04-22.03
level: 120 (120)
class: WARLOCK
spec: demonology

talents: bilescourge_bombers
    demon_skin
    demonic_calling
    demonic_circle
    demonic_consumption
    soul_conduit
    soul_strike

azerite: azerite_empowered = 2
    baleful_invocation = 1
    explosive_potential = 2
    overwhelming_power = 1
    resounding_protection = 1
    umbral_blaze = 1
    vampiric_speed = 1

essences: [the_crucible_of_flame] = 1, none

sets/legendaries/artifacts: none

gear: 7th_legionnaires_censer = 1
    blessing_bearers_waders = 1
    bonesplinter_band = 1
    darkmoon_deck_squalls = 1
    garments_of_the_forest_lord = 1
    heart_of_azeroth = 1
    julas_jovial_drape = 1
    mantle_of_voidtouched_waters = 1
    purified_tideblood_band = 1
    renowned_guild_tabard = 1
    rikals_ritual_beads = 1
    uncanny_combatants_sorcerous_scepter = 1
    vile_manipulators_belt = 1
    vile_manipulators_handguards = 1
    vile_manipulators_hood = 1
    vile_manipulators_trousers = 1
    vile_manipulators_wristwraps = 1

corruptions: none

itemIDs: 154857, 155231, 158075, 158680, 159126, 159238, 159311, 163892, 163953, 166683, 170312, 173437, 173507, 173511, 173811, 173845, 69210

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Demonology
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Hi, this has been resolved.  Thanks!
