### ISSUE TITLE
[REC] Aldrachi reaver detected when it should not be

### ISSUE THREAD

**Issue by TreeOfLearning** [Hekili/hekili#3541]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili appears to be detecting that I am using aldrachi reaver as my hero talent tree... but I am not.

### How to Reproduce

1. Enter game as vengeance demon hunter
2. Use fel scarred hero talents
3. Notice the recommendations are for aldrachi reaver

### Snapshot (Link)

https://pastebin.com/9RMmZ1fa

### Additional Information

<img width="224" alt="image" src="https://github.com/user-attachments/assets/411f3aa5-5bb8-4bb9-8598-5eb62689810d">
This screenshot shows the incorrect detection. Following is a screenshot of my talent tree:

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/ebdf426c-da68-4673-8c52-535e91199dbe">

And the talent string:
CUkAEDLOxe3SEPP2R8Hw6bhoSAAYMzMjhZkZmBDzMbjxYsNjZMjZGmZ2mZmtZmhZYGAAAAglZxMGmFNNwMjhN

**Comment by TreeOfLearning** [comment]
Perhaps related to #3531 ?

**Comment by Hekili** [comment]
This will be resolved in v11.0.2-1.0.4.
