### ISSUE TITLE
[REC] Spirit bomb being repeatedly recommended when it isn't possible to cast

### ISSUE THREAD

**Issue by TreeOfLearning** [Hekili/hekili#3542]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

**Note: I disabled the aldrachi reaver action list in the vengeance priority due to #3541.** 

Spirit bomb is sometimes suggested when I can't cast it. From what I can tell in the snapshot hekili thinks I have enough souls - but I have 0.

### How to Reproduce

1. Enter game as vengeance DH using fel scarred
2. Disable the broken aldrachi reaver action list
3. Get into an AOE situation
4. Notice spirit bomb being suggested with 0 souls

### Snapshot (Link)

https://pastebin.com/b4p1bFvt

**Comment by Hekili** [comment]
Sorry, I will only troubleshoot the default action lists as-is.
