### ISSUE TITLE
[Evoker-Augmentation] Rotation Issues with both Chronowarden and Scalecommander Hero Talents

### ISSUE THREAD

**Issue by ziggykoala** [Hekili/hekili#3544]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When the Chronowarden Hero Talents are active, the addon does not recommend Breath of Eons. Additionally, Chrono Flames is overriding the rotation when it should only replace Living Flame.

When the Scalecommander Hero Talents are active, the addon does recommend Breath of Eons. However, Living Flame is not recommended and instead defaults to Azure Strike.

It seems the addon isn’t recognizing that Chrono Flames can replace Living Flame, and it’s also not recommending Breath of Eons because it’s being replaced by the Maneuverability talent in the Scalecommander tree. As a result, the addon fails to detect that the Augmentation Evoker still has access to the non-Maneuverability version of Breath of Eons when the Chronowarden tree is active, so it doesn’t recommend it. The same issue occurs with Living Flame when the Scalecommander tree is active.

### How to Reproduce

1. Enter game as an Augmentation Evoker.
2. Select all the Chronowarden and Scalecommander Hero Talents, along with the Breath of Eons talent in the Spec Tree.
3. Start combat with either the Chronowarden or Scalecommander Tree active and follow the recommended rotation (I practiced using a Target Dummy).
4. Review the recommendations provided.

### Snapshot (Link)

https://pastebin.com/dL9qC262; https://pastebin.com/fwmDgRp6

### Additional Information

Snapshot with Chronowarden Hero Talents Active:  https://pastebin.com/dL9qC262
Snapshot with Scalecommander Hero Talents Active: https://pastebin.com/fwmDgRp6

### Contact Information

ziggykoala

**Comment by MatteoLombardi** [comment]
Many many duplicates, please check #3450

**Comment by ziggykoala** [comment]
I reviewed issue #3450, but this is a different problem.

Based on your message, I’m assuming that once Chrono Flames and the Maneuverability version of Breath of Eons are implemented, you are indicating that this ticket will be resolved as well.

However, this issue is distinct from #3450 because it’s not just about the new abilities being implemented, but the addon recognizing that there are two types of Breath of Eons, as well as the differences between Living Flame and Chrono Flames.

**Comment by ziggykoala** [comment]
I believe this issue is closer to #3516, where the addon assumes you have both trees active.

**Comment by Hekili** [comment]
This will be fixed in the next release (both hero trees incorrectly active).
