### ISSUE TITLE
[REC] (Warlock Affliction) Corruption is never recommended when using Soul Harvester hero talents

### ISSUE THREAD

**Issue by KNP54** [Hekili/hekili#3545]
### Before You Begin

- [ ] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For warlock affliction, corruption should be recommended soon in the priority list, however it is never recommended.

### How to Reproduce

1. Enter the game as an Affliction Warlock
2. Select Soul Harvester as hero talent tree
3. Begin the fight
4. Corruption is never recommended

### Snapshot (Link)

https://pastebin.com/m3QN6fhr

### Additional Information

I think it's a bug in Hekili and not the SimC APL.
I think it's a logic error in TheWarWithin\WarlockAffliction.lua on line 1148 since if I force the notalent variable to true it actually works and recommends corruption!

what I tried is to replace line 1148 from:
notalent = function() return state.spec.affliction and talent.wither.enabled and "wither" or nil end,
to
notalent = true,

It's *NOT* the proper fix and I did this just to debug.

### Contact Information

Discord: picoglad (Picoglad#7304)

**Comment by Hekili** [comment]
You'll need to update to 1.0.4 and post a new snapshot.

**Comment by KNP54** [comment]
It's fixed in 1.0.4 you can close the ticket (and I guess I was wrong about line 1178!)
