### ISSUE TITLE
Feral druid hero talent Ravage is recommended in display window, but does not flash on action bar using SpellFlash.

### ISSUE THREAD

**Issue by Bigity** [Hekili/hekili#3546]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hekili properly displays Ravage in the ST/AOE displays, but it does not flash on an action bar as do other abilities. 

### How to Reproduce

Be a feral druid with Ravage hero talent.  Enable rotation display windows as well as enable spellflash.  Perform rotation until Ravage is available and recommended in display window.  See that it does not flash as other abilities using SpellFlash.   No snapshot can be generated this is a display issue only with spellflash.

### Snapshot (Link)

N/A

### Raidbots Sim Report (Link)

N/A

**Comment by syrifgit** [comment]
Did you already go through the Spellflash troubleshooting steps?

https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#spellflash

**Comment by Hekili** [comment]
Testfix in 1.0.5.
