### ISSUE TITLE
Minispikes while playing Fire Mage with Hekili

### ISSUE THREAD

**Issue by Ookintv** [Hekili/hekili#355]
**Describe the Bug/Issue**
It doesnt matter what your doin as fire mage. You will always get minispikes like small screenfrozes while u are in the fire specc.

build: v8.3.0-04-22.03
level: 118 (118)
class: MAGE
spec: fire

talents: flame_on
    frenetic_speed
    living_bomb
    meteor
    rune_of_power
    searing_touch
    shimmer

azerite: none

essences: none*, none

sets/legendaries/artifacts: sephuzs_secret = 1

gear: alluring_glowfly_lantern = 1
    ancient_bloodmoon_cloak = 1
    band_of_destiny = 1
    exquisite_sunderseer_mantle = 1
    heart_of_azeroth = 1
    loa_speakers_bands = 1
    loa_speakers_grasps = 1
    loa_speakers_sandals = 1
    sephuzs_secret = 1
    strong_juju_bloodletter = 1
    tattered_dreadmist_leggings = 1
    tattered_dreadmist_mask = 1
    tattered_dreadmist_robe = 1
    terminus_signaling_beacon = 1
    tickers_spare_catalyst = 1
    zannesu_journey = 1

corruptions: none

itemIDs: 122250, 122256, 122262, 122378, 122384, 132452, 133970, 151969, 155351, 158075, 158972, 158973, 159014, 159038, 159051, 159077

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    no_scorch_blast = true
    prevent_hardcasts = true
    pyroblast_pull = true
    reserve_runes = 1
    save_2_runes = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
You can add commentary/feedback to the existing thread.  The short summary is that I'm looking for ways to reduce the performance impact from the Fire priority, but it's a complex priority that requires more (re)calculating than other priorities.

There're suggestions in the other thread for reducing performance impact as much as possible.  If there's still too much of an impact, don't use it.
