### ISSUE TITLE
[BUG][Retail] Typo in DruidBalance.lua line 2842 "talent.starlight.conduit.enabled" to cause freezing when in restoration spec

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3551]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Typo in DruidBalance.lua line 2842 "talent.starlight.conduit.enabled" to cause freezing when in restoration spec. Should be "talent.starlight_conduit.enabled" instead.

### How to Reproduce

Enter game as druid restoration spec.

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by syrifgit** [comment]
Added to https://github.com/Hekili/hekili/pull/3548

**Comment by Hekili** [comment]
Fixed via Syrif's PR, will be in 1.0.5.
