### ISSUE TITLE
Option to Desaturate Icons on Cooldown

### ISSUE THREAD

**Issue by ambonif** [Hekili/hekili#3552]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

ElvUI has an option to desaturate action bar icons on cooldown. Though Hekili allows for copying ElvUI style cooldown text, the icons aren't desaturated/grayscale when on cooldown if that option is enabled in ElvUI.

**Comment by johnnylam88** [comment]
I think this would be a cool feature, possibly as a default? We'd have to check that the cooldown isn't just due to the GCD before desaturation, but this would make the addon much better for usability.

**Comment by johnnylam88** [comment]
This feature can very easily be added if #3888 gets merged as the desaturate and fade conditions are identical.

**Comment by Hekili** [comment]
This is now a display option.
