### ISSUE TITLE
[REC] Shadowfiend being recommended when voidwraith hero talent has been taken and is on CD.

### ISSUE THREAD

**Issue by Nod53** [Hekili/hekili#3555]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As the title states, I am running the Void Weaver hero talents on shadow priest, with the selected Voidwraith choice node. It is recommending that I cast Shadowfiend when Voidwraith is on cooldown. I am running the Void Weaver hero talents on shadow priest, with the selected Voidwraith choice node

Snapshot: 
https://pastebin.com/ygAAcLq0

![image](https://github.com/user-attachments/assets/228f8f16-0651-4609-9910-a8e955bdb48b)

### How to Reproduce

Shadow priest voidweaver hero talents with voidwraith talent selected. 

see specific talent build I am using:

CIQAJSbRac/22NxZbHdYKOQzcMMYMDAAAAAAAAAAAAwwsYGzMzmNmZmZ2GzsMYWYmZmxsxAjxwsY2mamBLYGzMAoAMbz2SwsxG

Shadowpriest void weaver hero talents with void wraith talent selected.

### Snapshot (Link)

https://pastebin.com/ygAAcLq0

### Contact Information

nodondisc

**Comment by Hekili** [comment]
This is a texture display issue only, but should be resolved in 1.0.5.

**Comment by Nod53** [comment]
The texture was incorrect, however its still suggesting to use Shadowfiend (now the voidwraith icon) when its already on cooldown for 2 minutes.

As per bottom left icon (hekili) and top right icon showing voidwraith on CD.

new snapshot: https://pastebin.com/LR289M21

![image](https://github.com/user-attachments/assets/5c2e23a2-1703-4344-86ed-4c5d352e6b89)

**Comment by syrifgit** [comment]
```
 52.  mindbender ( main - 4 )
        The action (mindbender) is usable at (0.93 + 0.00). 
```
` talent.mindbender.enabled[false]`

 I think it's lying to you. It's technically suggesting mindbender, not shadowfiend.

**Comment by syrifgit** [comment]
Fix, I hope: https://github.com/Hekili/hekili/pull/3578
