### ISSUE TITLE
[REC] Reavers Glaive

### ISSUE THREAD

**Issue by bsdgaming** [Hekili/hekili#3558]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Reavers Glaive is now showing up in queue after the latest update, but doesn't stay for more than two seconds without disappearing.(hasnt made it to the first primary icon). Maybe some requirements need to be loosened. 

### How to Reproduce

Do a normal rotation on havoc Aldrachi Reaver. 

### Snapshot (Link)

https://pastebin.com/g3Mth0g4

**Comment by AnthonyGrenier** [comment]
Can confirm that Reaver's Glaive is still not working. Showing on recommended, but the ability i almost never recommended (going on AoE fight lasting some time, even if RG is up and ready, never being recommended.)

**Comment by AnthonyGrenier** [comment]
Any updates regarding this?

**Comment by syrifgit** [comment]
A new snapshot from the newest version of the addon is required, given that the newest version specifically addresses this spell

**Comment by bsdgaming** [comment]
https://pastebin.com/WZz1yeLJ  

as requested. Newest version of addon.. Reaver's glaive not being recommended

"The action (reavers_glaive) is unusable at (0.00 + 0.00) because required buff (reavers_glaive) not active."

**Comment by Hekili** [comment]
Testing a workaround to use a (fake) Reaver's Glaive buff to track the ability in 1.0.5b.

**Comment by AnthonyGrenier** [comment]
Tested with 1.0.5b, I can still see RG pop up for a split second on first recommended ability, but pops up at quite random moment and does not stay (disappears after 1 or 2 secs).

**Comment by Hekili** [comment]
Please take snapshots before/after the RG recommendation disappears.

I suspect that the Initiative window is not very forgiving and RG is no longer recommended due to latency and reaction times.

**Comment by bsdgaming** [comment]
https://pastebin.com/yjLFFscM 
here is a snapshot of Reavers Glaive being available to throw. While also having Vengeful Retreat ready. Still failing to recommend. 

BTW. this seems to work much better on Multiple targets and almost seems to not be an issue.... (snapshot is ST dummy)

**Comment by AnthonyGrenier** [comment]
100% agree with @bsdgaming, seems to be working much better, just some very weird case where it just won't recommend

Thanks for the snapshot @bsdgaming.

**Comment by bsdgaming** [comment]
Currently i have a Reaver's Glaive proc'd.(they stay forever).... And if i run to the single target dummy it dissapears... As soon as i stand next to the 3 target dummies it reappears. 
not sure if this info could be useful to @Hekili

**Comment by AnthonyGrenier** [comment]
I only seem to be having issue with open world "elites", where it will never be recommended, AoE looks good

**Comment by AnthonyGrenier** [comment]
Any updates on this?

**Comment by syrifgit** [comment]
Closing as this issue is many, many addon versions ago. If the issue still exists, please open a new ticket with new snapshots and sims.
