### ISSUE TITLE
[BUG] [Retail] Affliction Warlock Preferred Demon Settings not working.

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3559]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Affliction Warlock Preferred Demon Settings not working. No matter which preferred demon was selected, hekili always recommended felhunter.

### How to Reproduce

Enter game as Affliction Warlock. Change preferred demon in settings.

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by syrifgit** [comment]
Currently, the Sayaad is the highest DPS pet.
