### ISSUE TITLE
Bm hunter high crit 

### ISSUE THREAD

**Issue by wow1989** [Hekili/hekili#356]
As a bm hunter with high base crit (43%) I find I’m getting a significant dps gain by sitting on Barbed shot stacks during wrath in order to weave cobra - kill commands (with killer cobra talent) and using barbed shot only to keep up frenzy or when focus is down.

Otherwise i run the risk of spamming these barbed shot procs with focus cap and losing dps 

Again, this is all during the bestial wrath window with the killer cobra talent 

Thoughts?

**Comment by Hekili** [comment]
Test it in sims.
