### ISSUE TITLE
[BUG] [Retail] Holy Priest does not call cooldown actionlist

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3561]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Holy Priest does not call cooldown actionlist although there is a cooldown action list in APL.

### How to Reproduce

No response

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by syrifgit** [comment]
Can you provide a snapshot?

https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by EricMiukyQin** [comment]
![image](https://github.com/user-attachments/assets/d856f541-3117-48f2-ad65-b7a38e9ec4e8)


cooldowns is in actionlist，but never be called either from default or others

**Comment by EricMiukyQin** [comment]
> Can you provide a snapshot?
> 
> https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

![image](https://github.com/user-attachments/assets/1eda5a3e-3d40-4cb7-91ba-ee32deca5c61)

cooldowns is in actionlist，but never be called either from default or others

**Comment by syrifgit** [comment]
> > Can you provide a snapshot?
> > https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot
> 
> ![image](https://private-user-images.githubusercontent.com/26683272/362359847-1eda5a3e-3d40-4cb7-91ba-ee32deca5c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjA0MjIsIm5iZiI6MTcyNDg2MDEyMiwicGF0aCI6Ii8yNjY4MzI3Mi8zNjIzNTk4NDctMWVkYTVhM2UtM2Q0MC00Y2I3LTkxYmEtZWUzMmRlY2E1YzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE1NDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGYxYjBmNTlkNDRhYmFlNjljMzY0ZWZhZDUxOTRlNzMxMTlmY2VmOGNkZTRlZDE5YjgyZjk0ODg5NThiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feFP5iyi8WAsGs4HOgEJd59E39kcBDWbyE2sZhM5RIA)
> 
> cooldowns is in actionlist，but never be called either from default or others

Please follow the link provided and include a snapshot. This does not mean screenshot.

**Comment by EricMiukyQin** [comment]
> > > Can you provide a snapshot?
> > > https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/26683272/362359847-1eda5a3e-3d40-4cb7-91ba-ee32deca5c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjA0MjIsIm5iZiI6MTcyNDg2MDEyMiwicGF0aCI6Ii8yNjY4MzI3Mi8zNjIzNTk4NDctMWVkYTVhM2UtM2Q0MC00Y2I3LTkxYmEtZWUzMmRlY2E1YzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE1NDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGYxYjBmNTlkNDRhYmFlNjljMzY0ZWZhZDUxOTRlNzMxMTlmY2VmOGNkZTRlZDE5YjgyZjk0ODg5NThiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feFP5iyi8WAsGs4HOgEJd59E39kcBDWbyE2sZhM5RIA)
> > cooldowns is in actionlist，but never be called either from default or others
> 
> Please follow the link provided and include a snapshot. This does not mean screenshot.

https://pastebin.com/peVKA9yM

**Comment by syrifgit** [comment]
List will have to be updated eventually, but as a healer spec it will be lower priority.

**Comment by Hekili** [comment]
Fixed for 1.0.5b.
