### ISSUE TITLE
[BUG] [Retail] Discipline power_infusion does not belong to cooldown toggle

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3562]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Discipline power_infusion does not belong to cooldown toggle. It's None by default.

### How to Reproduce

No response

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by syrifgit** [comment]
List will have to be updated eventually, but as a healer spec it will be lower priority. However, you can simply assign it to CDs yourself from the abilities page.
