### ISSUE TITLE
Crimson Tempest not being recommended correctly in AOE opener

### ISSUE THREAD

**Issue by OppYchan** [Hekili/hekili#3563]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Crimson Tempest should be recommended before going into your Deathmark cd in AOE but its telling you to envenom first. Thank you for taking a look.

### How to Reproduce

Get full combo points in AOE with slice and dice after getting full rupture and garrot up. You need your dps cds up (Deathmark and Kingsbane)

### Snapshot (Link)

https://pastebin.com/s8rUeX1u

**Comment by Hekili** [comment]
Sim your character for comparison.

**Comment by syrifgit** [comment]
The class theorycrafters disagree with you (2 out of the 3 possible openers do deathmark **_before_** crimson tempest)

![image](https://github.com/user-attachments/assets/ef44b1ab-8d5f-4648-8507-8de0df17b397)

Additionally, the same line that is blocking crimson tempest is the same line that is in the raidbots script, deathmark can't be ready (aka, cast deathmark first).

``` 62.  crimson_tempest ( aoe_dot - 2 )
        The action (crimson_tempest) is usable at (0.00 + 0.00) with cost of 30 energy (have 300).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( aoe_dot ) called from ( Assassination:default:13 ) would PASS at 0.00.
        ! variable.single_target[false]
         - this entry's criteria FAILS: spell_targets.any[5.00] >= 3 & variable.dot_finisher_condition[true] & refreshable[true] & ! cooldown.deathmark.ready[true] & target.time_to_die[636.00] - remains[0.00] > 6
```


This line can be found in the current sim for Assassination Rogue: https://github.com/simulationcraft/simc/blob/thewarwithin/ActionPriorityLists/rogue_assassination.simc

**Comment by OppYchan** [comment]
![image](https://github.com/user-attachments/assets/4ff8d200-c679-45f3-a811-a5031cf3c158)
Things might have changed. I am using this from wowhead from whispyrs guide.

Its still recommending Envenom before crimson tempest and KB. The above is fine but rotation recommendation is not doing the above rotation. This snapshot should still show that.

Thank you for looking at it!

**Comment by syrifgit** [comment]
Ok, well the guides and the class discord show about 5 different openers for that build, and the addon is doing the one the sim does.

Do a 5 target quick sim of yourself and post it.
