### ISSUE TITLE
[BUG] [Retail] Shadow Priest void_blast id incorrect

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3564]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Shadow Priest void_blast spell id should be 450983 instead of 450405, which cause keybind sometimes failed during entropic_rift buff.
![image](https://github.com/user-attachments/assets/5346bcbd-0101-4b1f-82b5-f94ea60a9298)

### How to Reproduce

No response

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by Nod53** [comment]
Thanks for reporting this, I wasn't sure what was happening on mine but knew something was wrong

**Comment by Hekili** [comment]
Should be fixed in 1.0.6.
