### ISSUE TITLE
[BUG] [Retail] Discipline Priest when void blast is active, hekili still recommend smite instead of void blast.

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3565]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue
![image](https://github.com/user-attachments/assets/d8e3b0f2-25bd-4644-9ce0-af862f733dda)
Notice:  void blast spell id for Discipline Priest is 450215, which is diffrent from Shadow Priest.

### How to Reproduce

No response

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by syrifgit** [comment]
A snapshot is required to look at this issue. Take it when it is recommending the wrong thing.

https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by EricMiukyQin** [comment]
> A snapshot is required to look at this issue. Take it when it is recommending the wrong thing.
> 
> https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

https://pastebin.com/jxFyAFP2

**Comment by syrifgit** [comment]
Looks like void blast isn't implemented yet. As a healer spec it will be lower priority, but will leave ticket here so it is not forgotten.
