### ISSUE TITLE
[FEATURE] Druid heal rotation in feral form

### ISSUE THREAD

**Issue by Dvarz** [Hekili/hekili#3567]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello, is it possible to add the rotation for the healing druid in his feral form? This would be a big help because it's not always easy to heal players and keep an eye on combo points and dot on enemies at the same time.
Thanks

**Comment by Dvarz** [comment]
the rotation that could be implemented :

### 1-3 Targets

Use Rip Icon Rip whenever you have 5 Combo Points, and the target has a long time to live. Otherwise, use Ferocious Bite Icon Ferocious Bite.
Keep Rake Icon Rake up.
Keep Moonfire Icon Moonfire up.
Keep Sunfire Icon Sunfire up.
Keep Thrash Icon Thrash DoT up, if talented.
Use Shred Icon Shred to generate Combo Points once all DoTs are up.


### 4+ Targets

Use Rip Icon Rip whenever you have 5 Combo Points, and the target has a long time to live. Otherwise, use Ferocious Bite Icon Ferocious Bite.
Keep Sunfire Icon Sunfire up on all enemies.
Cast Moonfire Icon Moonfire on all enemies.
Use Thrash Icon Thrash for the DoT, if talented.
Keep Rake Icon Rake up on as many targets as you can.
Use Starfire Icon Starfire, if you are able to cast it without interruptions.

source : [https://www.icy-veins.com/wow/restoration-druid-pve-dps-guide](https://www.icy-veins.com/wow/restoration-druid-pve-dps-guide)
source : Last updated on Aug 21, 2024 at 20:20 by Torty

**Comment by Hekili** [comment]
You can reopen this is a Recommendations ticket with a snapshot.  The way the Resto priority is written, the Rake talent needs to be taken to trigger Cat Form recommendations.
