### ISSUE TITLE
[REC] Vengeance DH Fel Scarred Abilities 

### ISSUE THREAD

**Issue by Konnartist** [Hekili/hekili#3569]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Vengeance DH fel scarred abilities do not show up on the 'Abilities' list for Hekili which affects the addons recommended rotation abilities/accuracy. A big example is after casting Metamorphosis, you will get recommended to cast the hero talent version of fel devastation called fel desolation -- the addon keeps recommending fel desolation after casting cause its going off of fel devastations cooldown instead of fel desolation. 
![Fel Desolation Hekili](https://github.com/user-attachments/assets/3cb524a0-c6e5-424b-b617-eb206814cd56)

### How to Reproduce

1. Play fel scarred vengeance DH
2. go to training dummy and drop sigil of flame, immolation aura, and fiery brand
3. cast metamorphosis
4. cast improved version of fel devastation -- fel desolation
5. addon keeps recommending fel desolation even though its on CD

### Snapshot (Link)

https://pastebin.com/YnRTFujJ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/o4rLCSdBqmsDkxDwbWHZWD

### Additional Information

Spell IDs for Fel Scarred empowered abilities --
Fel Desolation -- 452486
Consuming Fire - 452487
Spirit Burst -- 452437
Sigil of Doom -- 452490
Soul Sunder -- 452436

**Comment by syrifgit** [comment]
As you can see by your snapshot and screenshot, it is recommending the regular Fel Devastation, not Fel Desolation. I checked and this is written exactly the same way in the sims.

**Comment by Konnartist** [comment]
Yes but you cannot cast fel devastation after casting metamorphosis because fel scarred hero talent changes fel devastation to fel desolation. All of the fel scarred meta empowered abilities are not loaded into Hekili to be recognized

**Comment by syrifgit** [comment]
> Yes but you cannot cast fel devastation after casting metamorphosis because fel scarred hero talent changes fel devastation to fel desolation. All of the fel scarred meta empowered abilities are not loaded into Hekili to be recognized

That is why you need to cancel meta, did you not receive the recommendation to cancel meta with a little X?

See: https://github.com/Hekili/hekili/issues/3574#issuecomment-2313628607

**Comment by Konnartist** [comment]
So you cancel meta before spending the rest of your empowered abilities?

**Comment by syrifgit** [comment]
You'd have to check the class discord on that. I just know people keep submitting tickets about Fel Dev/Fel Desolation, but it's working as intended. You cancel Meta then use Fel Dev.

**Comment by ambonif** [comment]
Didn't want to open a new issue, but the issue to me is that the keybinds are not shown for the Fel-Scarred abilities in the icon.

@syrifgit

**Comment by ambonif** [comment]
> Didn't want to open a new issue, but the issue to me is that the keybinds are not shown for the Fel-Scarred abilities in the icon.
> 
> @syrifgit

The Fel-Scarred abilities have different spell IDs, defining them manually fixes the issue. I tried to make the id dynamic through the function by detecting if metamorphosis/demonsurge is up and talented to use the right spell ID but couldn't get it to work.

**Comment by ambonif** [comment]
Nevermind, here's a fix:

`    soul_cleave = {
		id = function ()
			if talent.demonsurge.enabled and buff.metamorphosis.up then return 452436 end
			return 228477
		end,
        --id = 228477,`

`    spirit_bomb = {
        --id = 247454,
		id = function ()
			if talent.demonsurge.enabled and buff.metamorphosis.up then return 452437 end
			return 247454
		end,`

`    fel_devastation = {
		id = function ()
			if talent.demonic_intensity.enabled and buff.metamorphosis.up then return 452486 end
			return 212084
		end,
        --id = 212084,`

**Comment by ambonif** [comment]
Proposed via pull request

https://github.com/Hekili/hekili/pull/3603
