### ISSUE TITLE
Icon Interrupts blink on GCD(?)

### ISSUE THREAD

**Issue by Darkpoulp** [Hekili/hekili#357]
Hello

I wanted to have azerite essence on a separate icon
I managed to put it to the interrupt icon (tryed with aoe icon, but i didn't make it works only essence)
but i have an issue
the icon somehow blink (maybe on gcd) when i use skills and come back only if i'm not spamming key 
i've made a video to show this (maybe it's only a setting problem but i can't find out)
[https://www.youtube.com/watch?v=Cye5FjM9AuU](url)

How to make it stay until i use it please?
(I've put visibility only when combat and/or target)

Actualy, i wanted my azerite essence alone on a separate icon

Thx

Here is my character data:
build: v8.3.0-04-20
level: 120 (120)
class: DEMONHUNTER
spec: havoc

talents: demon_blades
    demonic
    felblade
    first_blood
    netherwalk
    trail_of_ruin
    unleashed_power

azerite: azerite_empowered = 3
    dagger_in_the_back = 1
    elemental_whirl = 1
    eyes_of_rage = 1
    furious_gaze = 3
    heed_my_call = 1
    impassive_visage = 1
    lifespeed = 1
    longstrider = 1
    thirsting_blades = 1
    thrive_in_chaos = 1

essences: [purification_protocol] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 3, the_crucible_of_flame = 4

sets/legendaries/artifacts: cyclotronic_blast = 1
    pocketsized_computation_device = 1

gear: appareil_de_calcul_de_poche = 1
    ashjrakamas_voile_de_dtermination = 1
    bague_des_ruminations_insidieuses = 1
    brassards_de_lgionnaire_de_la_7e = 1
    ceinture_de_la_gueule_irrassasiable = 1
    chausses_de_beautemps = 1
    chevalire_du_seigneur_malvoie = 1
    croc_du_mordeur_lectrisant = 1
    crocs_daustergarde = 1
    cur_dazeroth = 1
    cyclotronic_blast = 1
    gilet_de_marin = 1
    mantelet_de_la_gueule_irrassasiable = 1
    pocketsized_computation_device = 1
    poignes_tombpine = 1
    semblance_de_la_rdeuse_vorace = 1
    souliers_de_la_gueule_irrassasiable = 1
    tabard_de_guilde_renomme = 1

corruptions: none

itemIDs: 157974, 158008, 158042, 158075, 158089, 158362, 163278, 167555, 167672, 169223, 169318, 173439, 173816, 173841, 174243, 174469, 69210

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 7
    nameplates = true
    package = Havoc
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    recommend_movement = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = single
    potions = false

**Comment by Hekili** [comment]
Did you change your priority at all or did you just assign Purification Protocol to the interrupts toggle?  What are the conditions for Purification Protocol in your priority?

Have you tried snapshotting when Purifying Protocol disappears, so that there's a log to review for how the addon made its decision?

I suspect that I might've caused an issue with the Interrupts display in terms of waiting until the next GCD, but I'm not sure it would impact this in particular.

**Comment by Hekili** [comment]
I'm not seeing this and haven't received further explanation.  Closing.
