### ISSUE TITLE
Rogue - assassination recommending shive twice in a row and thistle tea 3 times in a row

### ISSUE THREAD

**Issue by cuetip** [Hekili/hekili#3570]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

assassination rogue its recommending to use shiv twice in a row and when it wants thistle tea it want to use all three charges at the same time. its also hardly recommending cds in aoe.

### How to Reproduce

just play assassination and use the default profile in the addon.

### Snapshot (Link)

n/a

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/evavXVcPJrEr5jF1GWfVZU

### Additional Information

i tried previous versions and its kind of funky each time. i did only go back 5 versions though, i will try further back for more testing.

**Comment by syrifgit** [comment]
You need to provide a snapshot for anything to be investigated.

https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot
