### ISSUE TITLE
[BUG] Hekilli doesnt shown after reset profile

### ISSUE THREAD

**Issue by Xpada1993** [Hekili/hekili#3571]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

This bar doesnt show up after i close the settings menu
it just disappear
it happened after i reset my profile
![image](https://github.com/user-attachments/assets/248b1869-199c-4b4b-83bc-0df76d7b4f7f)

### How to Reproduce

I dont get what you mean here

### Player Information (Link)

It only show "snapshot"

### Error Messages (Link)

.

**Comment by syrifgit** [comment]
https://github.com/Hekili/hekili/wiki/Getting-Started

Follow that and make sure your displays are enabled.

**Comment by Xpada1993** [comment]
> https://github.com/Hekili/hekili/wiki/Getting-Started
> 
> Follow that and make sure your displays are enabled.

I did, but it still doesnt work for some reason :(

![image](https://github.com/user-attachments/assets/adbb256b-1090-4184-b6f0-41ddce642d0e)

**Comment by syrifgit** [comment]
That is not what's in the link I sent. Go here and make sure your displays are enabled.

![image](https://github.com/user-attachments/assets/f8a653ca-628f-41ac-8475-36e1e8aebb91)

Also, get a snapshot: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by Xpada1993** [comment]
It still doesnt work, both of the bar on the right just disappear when i close the "hekili setting menu"
https://pastebin.com/YeAkn7dm
![image](https://github.com/user-attachments/assets/b603f89d-8eb2-4b5d-aafa-c7e08728f93f)

**Comment by syrifgit** [comment]
Reset your display position to 0,0
![image](https://github.com/user-attachments/assets/933c7024-4e5f-4587-9d19-c1ae362ce078)

**Comment by Xpada1993** [comment]
Thank youuu!!!
