### ISSUE TITLE
[FURY] Whirlwind while Single Target

### ISSUE THREAD

**Issue by Lithkur** [Hekili/hekili#3572]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While playing Fury Warrior I have noticed some instances where Whirlwind will get suggested to me when I am fighting a single enemy.

### How to Reproduce

1. Engage in combat with single enemy (in my case it was with Tidelord Teethwretch)
2. Hekili suggests whirlwind as part of rotation

### Snapshot (Link)

https://pastebin.com/bZiaDCjY

**Comment by syrifgit** [comment]
This snapshot does not show whirlwind. The spell you have an issue with must be showing on the display when you take the snapshot.

That being said, whirlwind is a part of the single target rotation. I suggest reading a class guide: https://www.icy-veins.com/wow/fury-warrior-pve-dps-rotation-cooldowns-abilities

**Comment by Lithkur** [comment]
I'll take a look at that, thanks!
