### ISSUE TITLE
LUA Error playing Augmentation Evoker

### ISSUE THREAD

**Issue by Jelek113** [Hekili/hekili#3573]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Devastation seems ok, Aug Evoker spams the following LUA error:

Message: Interface/AddOns/Hekili/UI.lua:2563: attempt to index field 'empowerment' (a nil value)
Time: Tue Aug 27 17:20:59 2024
Count: 3
Stack: Interface/AddOns/Hekili/UI.lua:2563: attempt to index field 'empowerment' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Hekili/UI.lua"]:2563: in function <Interface/AddOns/Hekili/UI.lua:2562>
[string "=[C]"]: ?

### How to Reproduce

1. Use Augmentation Evoker
2. Start using abilities, not sure what specific ability causes the issue.

### Player Information (Link)

https://pastebin.com/DvNWmFDG

### Error Messages (Link)

https://pastebin.com/bHzizqV6

### Contact Information

Jelek113

**Comment by Hekili** [comment]
I'm not able to replicate this issue on my end.

**Comment by Jelek113** [comment]
@Hekili Thanks very much for checking, this addon is fantastic btw. I removed all traces of the addon, manually deleted the files in D:\World of Warcraft\_retail_\WTF\Account\63337638#2\SavedVariables and  D:\World of Warcraft\_retail_\Interface\AddOns\Hekili then reinstalled and the issue seems to have resolved, thank you for confirming it was an issue on my end.
