### ISSUE TITLE
Vengeance Demon Hunter incorrect recommendation to cancel active Metamorphosis

### ISSUE THREAD

**Issue by Mura1108** [Hekili/hekili#3574]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing Fel-scarred Vengeance Demon Hunter, the addon keeps recommending to cancel the active Metamorphosis. This would be counter productive as Fel-scarred needs Metamorphosis'  full duration to benefit from the ability reset and multiple uses. This happens both with the Fel devastation induced, aswell with the hard casted CD 

### How to Reproduce

1. play Fel-scarred Vengeance Demon hunter
2. use rotation as shown
3. cast either Fel devastation or hard cast Metamorphosis CD

### Snapshot (Link)

https://pastebin.com/0NNL59gw

**Comment by syrifgit** [comment]
This is the correct thing to do. You should check out the Demon Hunter discord for more information.

![image](https://github.com/user-attachments/assets/b32d2659-ad54-4b79-987a-2b8f368c3019)

**Comment by Mura1108** [comment]
“We hope that bug is fixed soon…” yet claiming it’s intended gameplay? Wild….

**Comment by syrifgit** [comment]
> “We hope that bug is fixed soon…” yet claiming it’s intended gameplay? Wild….

Due to the bug in the actual game itself, cancelling meta is the correct thing to do, yes. If Blizzard fixes the bug, it will no longer be the best thing to do, and then the sims (and the addon) will be updated to stop doing it.
