### ISSUE TITLE
[BUG] [Retail] PriestShadow.lua line 1638 typo, should be voidwraith instead of voidwrath, which makes spell id incorrect.

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3576]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

No response

### How to Reproduce

No response

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by syrifgit** [comment]
Oh, that might be the issue with https://github.com/Hekili/hekili/issues/3555

Will submit a PR
