### ISSUE TITLE
[BUG] [Retail] frostfire_bolt for frost mage not been registered, Hekili can not read correct keybind.

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3577]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![cacf54db4794a9d34f848e025ab161f](https://github.com/user-attachments/assets/a21335b1-2cf5-4709-a1e8-8eccb2b3442d)

### How to Reproduce

No response

### Player Information (Link)

No response

### Error Messages (Link)

No response

**Comment by syrifgit** [comment]
https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#ui--display

Can be fixed via instructions here

**Comment by EricMiukyQin** [comment]
> https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#ui--display
> 
> Can be fixed via instructions here

What I mean is should u use spec:RegisterAbilities to register frostfire_bolt spell? I guess the problem keybind does not show correctly is because there is no frostfire_bolt spell been registered in code.
