### ISSUE TITLE
[REC] Voidwraith and Void Blast not in abilities / registering use

### ISSUE THREAD

**Issue by ZyraMain** [Hekili/hekili#3580]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When playing as a Shadow Priest in the Voidweaver Hero Talent Specialization, I do not see either Voidwraith or Void Blast in the abilities section of Hekili. On top of that when I start the rotation It will recommend Voidwraith and show the icon but after using the skill it stays up as if its never been used. Void Blast will show up in the priority as well but still be on Cooldown/Not available.

### How to Reproduce

1. Enter game as a Shadow Priest
2. Choose Voidweaver Hero Specialization
3. Start Single Target on a dummy and see when it recommends Voidwraith
4. Check under abilities in Hekili Settings to see its not listed.

### Snapshot (Link)

Shadow; Primary - Mind Blast(0.00) build: v11.0.2-1.0.5a level: 80 (80) class: PRIEST spec: shadow  talents: CIQAJSbRac/22NxZbHdYKOQzcMgZGAAAAAAAAAAAAAGzs4BGzMzyYMzMmtZmZZwsxMzMjZjBGjhZxsN1MDWgxMDAKAz2ssEMbsB     ancient_madness = 1/1     angelic_bulwark = 1/1     angelic_feather = 1/1     body_and_soul = 1/1     cauterizing_shadows = 1/1     collapsing_void = 1/1     dark_ascension = 1/1     dark_energy = 1/1     dark_evangelism = 2/2     death_and_madness = 1/1     deathspeaker = 1/1     devour_matter = 1/1     devouring_plague = 1/1     dispel_magic = 1/1     dispersion = 1/1     dominate_mind = 1/1     entropic_rift = 1/1     essence_devourer = 1/1     halo = 1/1     holy_nova = 1/1     idol_of_cthun = 1/1     idol_of_nzoth = 1/1     improved_fade = 2/2     improved_flash_heal = 1/1     inner_quietus = 1/1     insidious_ire = 2/2     leap_of_faith = 1/1     lights_inspiration = 2/2     maddening_touch = 2/2     malediction = 1/1     manipulation = 1/1     mass_dispel = 1/1     mastermind = 2/2     mental_decay = 1/1     minds_eye = 1/1     misery = 1/1     phantom_reach = 1/1     power_infusion = 1/1     protective_light = 1/1     psychic_link = 1/1     sanlayn = 1/1     screams_of_the_void = 1/2     shadow_crash = 1/1     shadow_word_death = 1/1     shadowfiend = 1/1     shadowy_apparitions = 1/1     shadowy_insight = 1/1     silence = 1/1     spell_warding = 1/1     surge_of_insanity = 1/1     thought_harvester = 1/1     throes_of_pain = 2/2     tithe_evasion = 1/1     translucent_image = 1/1     twins_of_the_sun_priestess = 1/1     twist_of_fate = 2/2     vampiric_embrace = 1/1     void_blast = 1/1     void_empowerment = 1/1     void_infusion = 1/1     void_leech = 1/1     void_torrent = 1/1     voidheart = 1/1     voidtouched = 1/1     voidweaver = 1/1     voidwraith = 1/1     whispering_shadows = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: [pelagos]  sets: none  gear: alighted_cord = 1     ancient_hardened_legwraps = 1     arakara_sacbrood = 1     emergency_stop_keychain = 1     empowering_crystal_of_anubikkaj = 1     gemstudded_signet = 1     gleamwax_shackles = 1     krixvizks_speech_rod = 1     mineralsparkled_mantle = 1     noncandescent_smithing_hood = 1     pioneers_perfected_cloak = 1     punctured_apiary_gloves = 1     tainted_earthshard_walkers = 1     tunic_of_irradiating_imprisonment = 1     wicks_golden_loop = 1  legendaries: none  itemIDs: 219312, 219314, 221050, 221067, 221077, 221082, 221099, 221104, 221166, 222835, 223289, 223294, 223299, 224661, 224672  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxTime = 20     nameplateRange = 40     nameplates = false     noFeignedCooldown = false     package = Shadow     petbased = false     potion = potion_of_spectral_intellect     rangeFilter = false     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     pad_ascended_blast = true     pad_void_bolt = true     sw_death_protection = 50  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = false      essences = true [overridden]     funnel = false      interrupts = false      mode = automatic      potions = false   keybinds:      angelic_feather      = SX  [01]     ascended_blast       = F   [01]     dark_ascension       = Q   [01]     desperate_prayer     = SR  [09]     devouring_plague     = C   [01]     dispersion           = SV  [02]     fade                 = V   [02]     flash_heal           = S2  [02]     halo                 = SE  [01]     healthstone          = R   [09]     leap_of_faith        = Z   [02]     levitate             = STAB[02]     mass_dispel          = SG  [02]     mind_blast           = E   [01]     mind_flay            = F   [01]     mind_soothe          = ST  [02]     mindbender           = SR  [01], F   [10]     potion               =     power_infusion       = TAB [02], SF  [10]     power_word_fortitude =     power_word_shield    = SM4 [02]     psychic_scream       = SQ  [01]     psyfiend             = CE  [06]     shadow_crash         = X   [01]     shadow_word_death    = SF  [01]     shadowform           =     shadowmeld           = S4  [02]     silence              = G   [02]     vampiric_embrace     = T   [02], C   [10]     vampiric_touch       = R   [01]     void_torrent         = SC  [01]  warnings: none   targets:  Nameplates are enabled.  - Checking nameplate3 [ Creature-0-3024-2552-90-225985-00004F5E19 ] #Kelpfist.     dmg          - Creature-0-3024-2552-90-225985-00004F5E19    player_buffs:    232698 - shadowform                               -   1 - 3600.00     21562 - power_word_fortitude                     -   1 - 1471.25    442981 - *weavers_tutelage                        -   1 - 3600.00    404468 - *flight_style_steady                     -   1 - 3600.00    227723 - *mana_divining_stone                     -   1 - 3600.00    452226 - *spiderling                              -   1 - 3600.00    452146 - *egg_sac                                 -   1 - 46.49     392511 - deathspeaker                             -   1 - 11.66     390978 - twist_of_fate                            -   1 - 7.89    player_debuffs:  target_auras:  target does not exist   New Recommendations for [ Primary ] requested at 16:03:04 ( 135210.75 ); using built-in ( Shadow ) priority. *** START OF NEW DISPLAY: Primary *** Purged 477 marked values in 0.09ms.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: insanity[ 26.00 / 150.00 ], mana[ 2500000.00 / 2500000.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Shadow - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   power_word_fortitude ( precombat - 1 )         The action is not ready ( 1471.25 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Shadow-precombat-1:power_word_fortitude:0.02:Ability Known, Enabled(0.02)                  2.   shadowform ( precombat - 2 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Shadow-precombat-2:shadowform:0.01:Ability Known, Enabled(0.01)                  3.   variable ( precombat - 3 )          - variable.dr_force_prio[0] will check this script entry ( Shadow:precombat:3 )         Time spent on this action:  0.02ms         TimeData:Shadow-precombat-3:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  4.   variable ( precombat - 4 )          - variable.me_force_prio[1] will check this script entry ( Shadow:precombat:4 )         Time spent on this action:  0.02ms         TimeData:Shadow-precombat-4:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  5.   variable ( precombat - 5 )          - variable.max_vts[0] will check this script entry ( Shadow:precombat:5 )         Time spent on this action:  0.01ms         TimeData:Shadow-precombat-5:variable:0.01:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  6.   variable ( precombat - 6 )          - variable.is_vt_possible[0] will check this script entry ( Shadow:precombat:6 )         Time spent on this action:  0.01ms         TimeData:Shadow-precombat-6:variable:0.01:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  7.   variable ( precombat - 7 )          - variable.pooling_mindblasts[0] will check this script entry ( Shadow:precombat:7 )         Time spent on this action:  0.01ms         TimeData:Shadow-precombat-7:variable:0.01:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  8.   arcane_torrent ( precombat - 8 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Shadow-precombat-8:arcane_torrent:0.02:Ability Known, Enabled(0.02)                  9.   shadow_crash ( precombat - 9 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.01ms         TimeData:Shadow-precombat-9:shadow_crash:0.01:Ability Known, Enabled(0.01)                  10.  vampiric_touch ( precombat - 10 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.01ms         TimeData:Shadow-precombat-10:vampiric_touch:0.01:Ability Known, Enabled(0.01)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Shadow - precombat ].          Processing default action list [ Shadow - default ].                  Current recommendation was NO ACTION at +10.00s.                  11.  silence ( default - 1 ) - ability disabled ( toggle interrupts )         Time spent on this action:  0.01ms         TimeData:Shadow-default-1:silence:0.01:Ability Known, Enabled(0.01)                  12.  variable ( default - 2 )          - variable.holding_crash[false] will check this script entry ( Shadow:default:2 )         Time spent on this action:  0.02ms         TimeData:Shadow-default-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  13.  variable ( default - 3 )          - variable.pool_for_cds[false] will check this script entry ( Shadow:default:3 )         Time spent on this action:  0.01ms         TimeData:Shadow-default-3:variable:0.01:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  14.  call_action_list:aoe ( default - 4 )         Criteria for aoe FAIL at +0.00 - active_enemies[1.00] > 2                  15.  run_action_list:main ( default - 5 )         There is no criteria for main.         Action list (main) was found.         + [main]         Current recommendation was NO ACTION at +10.00s.                  16.  variable ( main - 1 )          - variable.dots_up[true] will check this script entry ( Shadow:main:1 )         Time spent on this action:  0.02ms         TimeData:Shadow-main-1:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  17.  variable ( main - 2 )          - variable.pooling_mindblasts[1] will check this script entry ( Shadow:main:2 )         Time spent on this action:  0.02ms         TimeData:Shadow-main-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  18.  call_action_list:cds ( main - 3 )         Time-sensitive Criteria for cds deferred at +0.00 - boss[false] & fight_remains[30.00] < 30 | target.time_to_die[300.00] > 15 & ( ! variable.holding_crash[false] | active_enemies[1.00] > 2 )         Action list (cds) was found.         + [main], cds         Current recommendation was NO ACTION at +10.00s.                  19.  potion ( cds - 1 ) - ability disabled ( toggle potions )         Time spent on this action:  0.19ms         TimeData:Shadow-cds-1:potion:0.19:Ability Known, Enabled(0.19)                  20.  fireblood ( cds - 2 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Shadow-cds-2:fireblood:0.01:Ability Known, Enabled(0.01)                  21.  berserking ( cds - 3 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Shadow-cds-3:berserking:0.01:Ability Known, Enabled(0.01)                  22.  blood_fury ( cds - 4 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Shadow-cds-4:blood_fury:0.01:Ability Known, Enabled(0.01)                  23.  ancestral_call ( cds - 5 ) - ability unknown         Time spent on this action:  0.01ms         TimeData:Shadow-cds-5:ancestral_call:0.01:Ability Known, Enabled(0.01)                  24.  nymues_unraveling_spindle ( cds - 6 ) - IsUsableItem item 208615 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-cds-6:nymues_unraveling_spindle:0.02:Ability Known, Enabled(0.02)                  25.  power_infusion ( cds - 7 ) - ability disabled ( boss-only )         Time spent on this action:  0.01ms         TimeData:Shadow-cds-7:power_infusion:0.01:Ability Known, Enabled(0.01)                  26.  halo ( cds - 8 ) - ability disabled ( boss-only )         Time spent on this action:  0.01ms         TimeData:Shadow-cds-8:halo:0.01:Ability Known, Enabled(0.01)                  27.  void_eruption ( cds - 9 ) - talent [ void_eruption ] missing         Time spent on this action:  0.01ms         TimeData:Shadow-cds-9:void_eruption:0.01:Ability Known, Enabled(0.01)                  28.  dark_ascension ( cds - 10 ) - ability disabled ( boss-only )         Time spent on this action:  0.01ms         TimeData:Shadow-cds-10:dark_ascension:0.01:Ability Known, Enabled(0.01)                  29.  call_action_list:trinkets ( cds - 11 )         There is no criteria for trinkets.         Action list (trinkets) was found.         + [main], cds, trinkets         Current recommendation was NO ACTION at +10.00s.                  30.  darkmoon_deck_box_inferno ( trinkets - 1 ) - IsUsableItem item 194872 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-1:darkmoon_deck_box_inferno:0.02:Ability Known, Enabled(0.02)                  31.  darkmoon_deck_box_rime ( trinkets - 2 ) - IsUsableItem item 198477 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-2:darkmoon_deck_box_rime:0.02:Ability Known, Enabled(0.02)                  32.  darkmoon_deck_box_dance ( trinkets - 3 ) - IsUsableItem item 198478 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-3:darkmoon_deck_box_dance:0.02:Ability Known, Enabled(0.02)                  33.  dreambinder_loom_of_the_great_cycle ( trinkets - 4 ) - IsUsableItem item 208616 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-4:dreambinder_loom_of_the_great_cycle:0.02:Ability Known, Enabled(0.02)                  34.  conjured_chillglobe ( trinkets - 5 ) - IsUsableItem item 194300 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-5:conjured_chillglobe:0.02:Ability Known, Enabled(0.02)                  35.  iceblood_deathsnare ( trinkets - 6 ) - IsUsableItem item 194304 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-6:iceblood_deathsnare:0.02:Ability Known, Enabled(0.02)                  36.  erupting_spear_fragment ( trinkets - 7 ) - IsUsableItem item 193769 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-7:erupting_spear_fragment:0.02:Ability Known, Enabled(0.02)                  37.  belorrelos_the_suncaller ( trinkets - 8 ) - IsUsableItem item 207172 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-8:belorrelos_the_suncaller:0.02:Ability Known, Enabled(0.02)                  38.  beacon_to_the_beyond ( trinkets - 9 ) - IsUsableItem item 203963 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-9:beacon_to_the_beyond:0.02:Ability Known, Enabled(0.02)                  Entry #10 in list ( trinkets ) is not set or not enabled.  Skipping.                  39.  spymasters_web ( trinkets - 11 ) - IsUsableItem item 220202 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-11:spymasters_web:0.02:Ability Known, Enabled(0.02)                  40.  use_items ( trinkets - 12 )         Criteria for ??? PASS at +0.00 - ( buff.voidform.up[false] | buff.power_infusion.up[false] | buff.dark_ascension.up[false] | ( cooldown.void_eruption.remains[120.00] > 10 & trinket.cooldown.duration[nil] <= 60 ) ) | boss[false] & fight_remains[30.00] < 20         + [main], cds, trinkets, items         Current recommendation was NO ACTION at +10.00s.         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items                  41.  desperate_invokers_codex ( trinkets - 13 ) - IsUsableItem item 194310 and nil         Time spent on this action:  0.02ms         TimeData:Shadow-trinkets-13:desperate_invokers_codex:0.02:Ability Known, Enabled(0.02)         Exiting trinkets with recommendation of NO ACTION at +10.00s.         Returned from list (trinkets), current recommendation is NO ACTION (+10.00).         - trinkets                  42.  desperate_prayer ( cds - 12 ) - ability disabled ( toggle defensives )         Time spent on this action:  0.01ms         TimeData:Shadow-cds-12:desperate_prayer:0.01:Ability Known, Enabled(0.01)         Exiting cds with recommendation of NO ACTION at +10.00s.         Returned from list (cds), current recommendation is NO ACTION (+10.00).         - cds                  43.  mindbender ( main - 4 ) - ability disabled ( boss-only )         Time spent on this action:  0.02ms         TimeData:Shadow-main-4:mindbender:0.02:Ability Known, Enabled(0.02)                  44.  shadow_word_death ( main - 5 )         The action (shadow_word_death) is usable at (0.00 + 0.00) with cost of 12500 mana (have 2500000).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( main ) called from ( Shadow:default:5 ) would PASS at 0.00.         NONE          - this entry's criteria FAILS: priest.force_devour_matter[nil] & talent.devour_matter.enabled[true]         There were no recheck events to check.         Time spent on this action:  0.11ms         TimeData:Shadow-main-5:shadow_word_death:0.11:Ability Known, Enabled(0.01):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.01):Post-Recheck Times(0.00):Post Recheck(0.00)                  45.  mind_blast ( main - 6 )         The action (mind_blast) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( main ) called from ( Shadow:default:5 ) would PASS at 0.00.         NONE          - this entry's criteria PASSES: ! talent.mind_devourer.enabled[false] | ! buff.mind_devourer.up[false] | buff.entropic_rift.remains[0.00] <= gcd.max[1.27]         Action chosen:  mind_blast at 0.00!         Exiting main with recommendation of NO ACTION at +10.00s.         Returned from list (main), current recommendation is mind_blast (+0.00).         - [main]         Added main to blocklist as it was called via RAL.         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Shadow - default ].     Recommendation is mind_blast at 0.00 + 0.00.     Recommendation #1 is mind_blast at 0.00s (0.00s).     Time spent generating recommendations:  1.92ms

### Contact Information

vipe_ucf or vipe#7293

**Comment by syrifgit** [comment]
There is already a ticket for this.
