### ISSUE TITLE
Feral druid > finisher action list > primal wrath logic issue

### ISSUE THREAD

**Issue by whynotdead** [Hekili/hekili#3583]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Here is quick note how primal wrath logic should be happening "maintain/upgrade pws, if we have 6.5+s left on pw, we will instead bite if we have rampant ferocity talented. Without rampant, we will bite a vined target with 6 or fewer targets. If we have Ravage, we use specifically Ravage at 7 or fewer targets." 
However with even 4-5 targets and ravage being up or blood vines ticking with rip dot being longer than even 9 seconds it keep spamming PW instead of prioritizing bites ruining the logic and causing potential dps loss. I cannot provide snapshot since it's not a recommendation issue but simply modifieers not doing their job in their particular sequence
Apex meanwhile works well and goes in advance of PW if it has 6+ duration, but hero talents conditions keep being ignored
Also small tip, idk exactly to what talent build that APL refers, but i guess depending on Circle of Life and Death talent dot remaining time condition should differs since talent makes it tick 20% faster

### How to Reproduce

1. Enter game as feral
2. Auto mode suggestions enabled with AoE being enabled at >=3 targets
3. With Ravage buff being up or Blood Vines ticking on main target it still suggest to use PW when 5 targets around only (same on target dummies which are exactly 5)

### Snapshot (Link)

1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/t7fqAeznbQo4nBuJMysAoA

### Additional Information

On quick sim short APL demo you can clearly see all ravage pop-ups getting utilized even if rip gonna fade off in 3 seconds

### Contact Information

whynotdead7

**Comment by whynotdead** [comment]
https://www.raidbots.com/simbot/report/4iieyYpJqxxnfe1XRJimV9 - actually here on 5 targets you can see that issue that conditional logic is not supported or written wrong, you pw at 0:52 with ravage buff up, then feral frenzy into 5 cps and PW again with ravage buff up 3 seconds later when it suppose to be a ferocious bite to utilize ravage, so idk https://imgur.com/a/l80ndUX . All the same with blood vine dot ticking, but being okay with apex(rampant) procs

**Comment by whynotdead** [comment]
I was able to fix it i think and found out that it works with extra entry for bite, not sure if i did it right logical wise:
https://imgur.com/a/AuDHDpZ - cut entry for PW which is for maintaining 
https://imgur.com/a/fjtzOkA - conditional entry for bite to utilize ravage/blood vines explosion, it looks like working, if i did everything correctly, probably should post rotation tune update cuz it clearly doesn't work in a single entry binded to PW even if we rely not just on rampant ferocity talented but apex proc buff up - it still not using bites outside of apex procs

**Comment by Hekili** [comment]
If this is more of a disagreement with the default sim profile, you might want to submit a PR to the simulationcraft project.  If adopted there, the addon will be updated to match.
