### ISSUE TITLE
[REC] [Retail] Arcane mage hero talent Sunfury: gravity_lapse will replace supernova while resulting keybind incorrect.

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3586]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

No keybind for gradivy_lapse. (It should be keyboard 6 for me)
![image](https://github.com/user-attachments/assets/b4051204-b826-427e-86be-0640d223f04a)

### How to Reproduce

No response

### Snapshot (Link)

https://pastebin.com/hSdfMZgD

**Comment by Hekili** [comment]
Should be addressed in 1.0.6
