### ISSUE TITLE
[REC] [Retail] Fire mage frostfire_bolt also replaces fireball and hekili still recommends fireball.

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3587]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Fire mage frostfire_bolt also replaces fireball and hekili still recommends fireball. Fireball keybind is missing.
![image](https://github.com/user-attachments/assets/4b6bae20-d9de-4e76-90c8-8f236a66695c)

Frost mage has similar issue, which has been mentioned in #3587, but was closed.
![image](https://github.com/user-attachments/assets/04b9ca67-71b8-4553-9e6f-d525493b9c1c)

### How to Reproduce

No response

### Snapshot (Link)

https://pastebin.com/SRn4rv7V
https://pastebin.com/n82Gcjy8

**Comment by Hekili** [comment]
Looking to address this in 1.0.6.
