### ISSUE TITLE
[BUG] Assassination rogue unable to generate recommendation

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3589]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Says unable to recommend action #2 Primary action: Mutalate?

### How to Reproduce

Not sure how to reproduce this, this has happened a few times over the last few days, in heroics.

### Player Information (Link)

https://pastebin.com/vski0j2i

### Error Messages (Link)

https://pastebin.com/vski0j2i

### Contact Information

Wren1740

**Comment by Hekili** [comment]
Can you add the next snapshot you get to Pastebin and link it here? The one you posted had it's formatting nuked and is too hard to interpret/review. Thanks.

**Comment by syrifgit** [comment]
I was able to mostly fix the formatting with notepad++

https://pastebin.com/fcVbmFv2

**Comment by Hekili** [comment]
It looks like the current sim logic had you in a place where it didn't want to apply DoTs, use Envenom, or use a filler Mutilate.  I'm adjusting the action list to have a "filler" Envenom when a "filler" Mutilate is not indicated.
