### ISSUE TITLE
[REC] Arcane Mage Sunfury spellfire_spheres & rondurmancy & burden_of_power and Enhancement Shaman tempest_mael_count do not working correctly

### ISSUE THREAD

**Issue by AzuraZJ** [Hekili/hekili#3590]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I found that some of hekili's parameters didn't work correctly, and it all happened with the hero talent. I only have one shaman and one mage, but due to the similarity of these two bugs, I think this type of problem should also appear in other classes.

As shown below, buff.xxx error happends on spellfire_spheres, rondurmancy, burden_of_power and tempest_mael_count.
All these bugs manifest themselves as:
1. Use the same buff id as wowhead (I don’t know if it is correct, but it is consistent)
2. Unable to identify whether the buff exists
3. Unable to obtain buff stacks

<img width="380" alt="屏幕截图(102)" src="https://github.com/user-attachments/assets/77a6e371-5b5f-4ff0-86b9-df6696311172">

### How to Reproduce

For spellfire_spheres and rondurmancy
1. Enter game login a arcane mage
2. Cast Arcane Barrage
3. Check buff.spellfire_spheres.stack and buff.rondurmancy.up info

For tempest_mael_count
1. Enter game login a enhancement shammy
2. Cast Lightning Bolt when u have Maelstrom Weapon
3. Check tempest_mael_count (It will always be 0)

### Snapshot (Link)
https://pastebin.com/dFzHETqY

**Comment by syrifgit** [comment]
There does not need to be an error to get a snapshot: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by AzuraZJ** [comment]
> There does not need to be an error to get a snapshot: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

thx i will post a link here

**Comment by Hekili** [comment]
For Enhancement, `tempest_mael_count` is NYI because there's no built in tracker that I can find that I can trust.  If I manually count MSW stacks that are consumed, it can get totally out of sync and cause erroneous recommendations.  As it stands, the current implementation recommends the "conservative" behavior so it'll be like this until I come up with a solution.

For Arcane, posting snapshots when you have the actual buffs associated with spellfire_spheres, rondurmancy, burden_of_power, etc. may be helpful in terms of correcting any spell ID errors, assuming that the auras are actually visible.  If they are not visible, I will need to find a way to fake them for sim compatibility.

**Comment by AzuraZJ** [comment]
> For Enhancement, `tempest_mael_count` is NYI because there's no built in tracker that I can find that I can trust. If I manually count MSW stacks that are consumed, it can get totally out of sync and cause erroneous recommendations. As it stands, the current implementation recommends the "conservative" behavior so it'll be like this until I come up with a solution.
> 
> For Arcane, posting snapshots when you have the actual buffs associated with spellfire_spheres, rondurmancy, burden_of_power, etc. may be helpful in terms of correcting any spell ID errors, assuming that the auras are actually visible. If they are not visible, I will need to find a way to fake them for sim compatibility.

Thanks for reply Hekili
I posted the snapshot and as you said it helps. I figured out the problem, which was that those auras weren't being added at all. If you don't mind I'll create a pull to fix it, I don't know much about the issue outside of mages since I only have a mage and a shaman.

**Comment by AzuraZJ** [comment]
Hi @Hekili howdy
Could you please check my PR? Btw in mage, I have play this class for 4 years. I'm just testing some meaningful parameters to improve the performance of mages (such as predicting the number of aura stacks and status during spell casting) today, and if you allow me, I would like to become one of the community contributors and continue to publish these improvements in the future.

**Comment by Hekili** [comment]
PR added.  Will keep `tempest_mael_count` on my to-do list.

**Comment by AzuraZJ** [comment]
great thx @Hekili 
about `tempest_mael_count` I have an idea. Its logic is based on a wa string [Tempest Counter Enhancement](https://wago.io/TKVKEpxkf). 
There is a clear logic for the operation of Tempest: 
1. When Tempest is activated, the buff stack is reset to 0 
2. Players cannot obtain buff stacks when Tempest is activated unless they release it. 
3. Stacks will not expire during battle. 
4. Out of combat buff counter will be saved for a long time

A full-time counter might not be accurate enough, but if just make a short-term counter that activates only when the first storm activates after the game starts and reset frequently, it should be pretty accurate. What do you think?
