### ISSUE TITLE
Disc Priest - Voidwraith SpellFlash

### ISSUE THREAD

**Issue by Vanquish-6** [Hekili/hekili#3593]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

SpellFlash of Voidwraith for Disc priest does not occur

### How to Reproduce

Enter combat, have voidwraith ready (it'll show as spell to use in box priorty) but spellflash does not highlight Voidwraith

### Snapshot (Link)

https://pastebin.com/JeKkG60V

### Contact Information

Vanquish420

**Comment by Vanquish-6** [comment]
After update; still doesn't spellflash it

**Comment by Hekili** [comment]
Test fix in 1.0.8
