### ISSUE TITLE
[REC] Gorefiend's Grasp condition incorrect talent

### ISSUE THREAD

**Issue by esergiosantos** [Hekili/hekili#3595]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I found an error in the Gorefiend's Grasp condition, he has the tightening talent and not the Gorefiend's talent , fix
By changing the talent the problem is solved
![image](https://github.com/user-attachments/assets/87a6e622-7623-4f3b-89e6-d871d5fccb7c)

### How to Reproduce

Enter Games as BDK, see condition Gorefiends Grasp

### Snapshot (Link)

Blood; Interrupts - Garra de Sanguinávido(0.00)

**Comment by syrifgit** [comment]
Not sure that this is an "error" given that it matches the simulation: https://github.com/simulationcraft/simc/blob/thewarwithin/ActionPriorityLists/deathknight_blood.simc

It is only suggesting to use it if you have the talent which reduces the CD

**Comment by esergiosantos** [comment]
> Not sure that this is an "error" given that it matches the simulation: https://github.com/simulationcraft/simc/blob/thewarwithin/ActionPriorityLists/deathknight_blood.simc
> 
> It is only suggesting to use it if you have the talent which reduces the CD

There is a scenario where you want to take Gorefiend's, just removing Hemostasis, such as dungeon scenarios where we will do big pulls, like DG HC, M+ carry etc.

Like this suggest in wowhead talents 
https://www.wowhead.com/guide/classes/death-knight/blood/talent-builds-pve-tank#dungeoncouncil-gorefiends

CoPAAAAAAAAAAAAAAAAAAAAAAghZmZGjZmxMDzYmZmmhhZGzYAAAAAwMzMzMzMmNzMjBAAAzMzMAAAAbmtBGwSw2wEYYBgZwG
