### ISSUE TITLE
[BUG] BtE Bug (Outlaw rogue)

### ISSUE THREAD

**Issue by Gjorns** [Hekili/hekili#3597]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Posting some of my snapshots, to see if anyone can figure out what is the cause of the BTE getting stuck

### How to Reproduce

Honestly dont know, it's so random.

i dont know how to look at the logs but there is an interesting row:

Step 51.

### Player Information (Link)

https://pastebin.com/MKmZLvPv

### Error Messages (Link)

https://pastebin.com/MKmZLvPv

### Contact Information

gjornsy

**Comment by PsjPocco** [comment]
99% unrelated to hekili.

quoting a pin from the rogue discord here :

> Why is my Between the Eyes not going off?
If your BtE is playing its animation but nothing happens, that's a newer bug where BtE cooldown appears to reset on your UI but it did not actually reset. It seems to happen when you break Stealth with BtE on cooldown, though for some people it's not 100% of the time.

> There is also an older bug you may encounter while leveling, which is where Crackshot and related stealth effects don't happen if you recast  Stealth while Subterfuge is already active. This can cause you to break stealth with BtE but it still goes on cooldown.

**Comment by nthnprsnlkid** [comment]
Blizz bug, not hekili
