### ISSUE TITLE
[REC] Feral druid: rake is being recommended sometimes up to three times in a row on the same target

### ISSUE THREAD

**Issue by ThondrFlip** [Hekili/hekili#3598]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For feral druid, rake is being recommended sometimes up to three times in a row on the same target. This is not recommended target switch.
![WoWScrnShot_082924_181741](https://github.com/user-attachments/assets/dd7f6427-712a-4b62-bad4-a2cd859b9225)

### How to Reproduce

On feral druid, do rotation on 3,4,5 or more targets. Sometimes happens single target as well.
Pop all cooldowns, do the rotation, after a while, rake will start being recommended in weird ways. But this is not the recommended target switch reocmmendation for rake, it's on the same target.

### Snapshot (Link)

https://pastebin.com/yUcLQ8Ae

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/sC6kd1d4eUVAPMDtpz1cuo

### Contact Information

discord username: thondr

**Comment by ThondrFlip** [comment]
https://pastebin.com/2XXbDi2c

Other example. Rake is up on target.
![WoWScrnShot_090124_095330](https://github.com/user-attachments/assets/b34f89a0-3f82-4cb2-84b3-c6a77b7593a2)

**Comment by ThondrFlip** [comment]
CelestialRepose, the feral rotation simc author, suggests this may have something to do with how Hekili is parsing target_if when importing the APL. They said you guys are probably already aware of the problem if that's the case.

**Comment by ThondrFlip** [comment]
I suspect it might be something to do with having Recommend Target Swap off. The rotation may still suggest rakes assuming you're going to target switch. Harder to recreate the problem when you turn on Recommend Target Swap.

**Comment by Hekili** [comment]
This should be resolved in 1.0.7
