### ISSUE TITLE
[REC] Fire mage does not recommend either Frostfire Bolt or Fireball under frostfire hero talent

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3599]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After fix #3587, fireball never be recommended in frostfire hero talent.
![image](https://github.com/user-attachments/assets/6c0eade3-badb-4830-a9d9-6b0cc0ec7077)

### How to Reproduce

No response

### Snapshot (Link)

https://pastebin.com/qxwCPZV5

**Comment by syrifgit** [comment]
This is a non-issue. Frostfire bolt is not found anywhere in the fire mage Sims or APL, so you shouldn't be casting it.
