### ISSUE TITLE
[Warrior] Arms Simulation APL fix (by Skyhold Discord)

### ISSUE THREAD

**Issue by j-mes** [Hekili/hekili#360]
**Describe the Bug/Issue**
It is well known that the simulation APL is not correct for Arms Warrior, and a kind person decided to fix it and shared it with the Skyhold discord for Warriors to use on Raidbots.

However, I'd love to see this in Hekili as well, and I tried to convert and it wouldn't work. Apologies in advance if I've missed any documentation/guide for doing this and making it work.

See the [pastebin](https://pastebin.com/Mc2bcRdf) for the fixed SimulationCraft APL. The [source](https://discordapp.com/channels/148872210742771712/148898720803586048/709180348717596691) from Skyhold Discord (The link only works if you're in that Discord as well).

**To Reproduce**
1. Copied the raw contents of the Pastebin.
2. Pasted in a new 'Arms' profile called 'ArmsModified'.
3. Loaded it, and it did not display like it would with the normal Arms profile.

**Expected behavior**
1. Copy APL then load in a new profile.
2. 🎉 New ArmsModified profile to test.

**Information asked for (also for TL;DR)**
1. /hekili > Issue Reporting > Output - [PasteBin](https://pastebin.com/nQmFP9tT)
2. Modified APL from Warrior Discord for Arms - [PasteBin](https://pastebin.com/Mc2bcRdf)
3. Source of the modified APL from Warrior Discord - [Skyhold](https://discordapp.com/channels/148872210742771712/148898720803586048/709180348717596691)

I hope this is enough information for you, and that it won't be discarded 🤞 

P.S. I like the pug in a taco outfit. Very cool 😄

**Comment by Hekili** [comment]
You could probably import this if you remove all the quotation marks, but I'll test it myself.

After importing, you'd need to select the APL in your spec's options.

FWIW, the default Arms APL in the addon is edited since the HAC list isn't useful, IIRC.  I'll see what's different between the two.  

Are there linked sims showing the better performance?

**Comment by Hekili** [comment]
Also, your fixed APL references Executioner's Precision, which IIRC is gone.

**Comment by j-mes** [comment]
Woow @Hekili that is such a quick response. I did not expect one tonight but kudos to you.

I've done two sims based on myself for you to look at.

[Raidbots without modified APL](https://www.raidbots.com/simbot/report/oQyn5KadDCLtKAXW18SWDZ) - 84,939 DPS
[Raidbots with modified APL](https://www.raidbots.com/simbot/report/8gP19QzYSY6m5HaGcANAq9) - 87,629 DPS

Would that be based on Executioner's Precision which is not in the game anymore? 🤔

**Comment by Hekili** [comment]
Can you run a Hectic Add Cleave or add more bosses to your Patchwerk sim?

I thought the fixes were aimed at resolving for multi-target.

But yeah, the five_target priority wouldn't use Mortal Strike without Dreadnaught talented, because of the EP check.  I don't know if that's intended or not, since EP isn't available.

![image](https://user-images.githubusercontent.com/9438134/82672708-b2b67a80-9c0e-11ea-94e7-ed994999d6e9.png)

**Comment by j-mes** [comment]
**Added the Hectic Cleave Sims below:**
- [Hectic Add Cleave (Not modified)](https://www.raidbots.com/simbot/report/oANDNMR6pRUj3cYF5nJAdW) - 130,797 DPS
- [Hectic Add Cleave (Modified)](https://www.raidbots.com/simbot/report/oGNRroWcibaWZp75fPYgjL) - 130,347 DPS

Not much difference 🤔 

**Trying with Patchwerk with 3 bosses below using my Single Target gearset:**
- [Patchwerk with 3 Bosses (Not modified)](https://www.raidbots.com/simbot/report/gBBrpPpGMAqQ1oN5hthzM1) - 131,698 DPS
- [Patchwerk with 3 Bosses (Modified)](https://www.raidbots.com/simbot/report/tQWZXZ3WuFeHQtfg7uvUGU) - 140,193 DPS

That's a big change. If you would like me to run more sims but with gear normalised then let me know what to use? 😄 I have most of the trinkets if it helps (ranging from heroic to mythic)

**Comment by Hekili** [comment]
It's less about gear.  Honestly, the best comparison is to run the most common talent/azerite/essence combinations vs. Patchwerk / HAC / Patchwerk x5.

I think that APL still needs work around its multi-target, based on those sim results.

At best, I'd have to try hybridizing my modified version in the addon with your modified version from SimC.

**Comment by j-mes** [comment]
Okay! I've normalised it with the same talent/azerite/essence combinations across all 6 sims now.

**Patchwerk (1 Boss)**
- [SimulationCraft APL](https://www.raidbots.com/simbot/report/8f5uwRcaDUnitrAL5pMw9s) - 91,453 DPS
- [Modified Skyhold APL](https://www.raidbots.com/simbot/report/e2sVcohWMNPmLiNeqnNXeP) - 95,176 DPS

**Patchwerk (5 Bosses)**
- [SimulationCraft APL](https://www.raidbots.com/simbot/report/sypti9LhsExn9tp6Deuji4) - 154,912 DPS
- [Modified Skyhold APL](https://www.raidbots.com/simbot/report/2CrG8iiBafFbwCWemajdbm) - 155,087 DPS

**Hectic Add Cleave**
- [SimulationCraft APL](https://www.raidbots.com/simbot/report/sndAFxCaXPRMfHLpfoKoW2) - 130,416 DPS
- [Modified Skyhold APL](https://www.raidbots.com/simbot/report/qy7CWr5GLkBocti2Zo2obt) - 129,976 DPS

🤔 It feels like the differences are mostly single target. The HAC/Patchwerk with 5 bosses seems quite close. Forgive me if I interpreted your Patchwerk x5 wrong, unless you wanted me to run the sims (for unmodified and modified) 5 times?

**Comment by Hekili** [comment]
I've been iterating over this APL and -05 and -06 both include the changes.  -06 fixes some bugs with the -05 implementation.  I hope.

**Comment by j-mes** [comment]
Nice 😄 I'll test it out and let you know how it goes!

**Comment by Hekili** [comment]
Resolved.
