### ISSUE TITLE
arcane mage won't cast barrage after blast with burden of power

### ISSUE THREAD

**Issue by 78jeffrey** [Hekili/hekili#3600]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

arcane mage won't cast barrage after blast with burden of power.  just keep blasting

### How to Reproduce

blast x5  will get a buff burden of power.  According to simc  I should cast blast follow by barrage but hekili just keep blasting.

### Snapshot (Link)

https://pastebin.com/x0q8AcD7

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cm9q7EvaLzzgn1ndaMKJyM

**Comment by 78jeffrey** [comment]
glorious_incandescence = {
        id = 449394,
        duration = 3600,
        max_stack = 1

the buff id in game is 451073

after I changed it.   It will suggest barrage but still not work correctly.
we want to cast blast and barrage at same time with buff burden of power.
but glorious_incandescence buff happped after blast casting finished.

**Comment by AzuraZJ** [comment]
hi 78jeffrey
I think this bug can be solved after PR [https://github.com/Hekili/hekili/pull/3602](url) merged.
before that I highly recommend you make some minor modifications to the recommendation logic.
it will be look like:
`prev_gcd.1.arcane_blast & buff.burden_of_power.down & buff.spellfire_spheres.down & time - action.arcane_blast.last_used < 0.5 & time - action.arcane_blast.last_used >= 0 & time > 0`
This will make it work properly after merged.

**Comment by Hekili** [comment]
PR merged.  Arcane is going to get a new APL from the theorycrafters soon, too.

Just as an aside, `time - action.arcane_blast.last_used` can be replaced with `action.arcane_blast.time_since`.
