### ISSUE TITLE
[REC] Afflication/Demon/Destruction Warlock precombat never recommends fel_domination

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3605]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Warlock precombat never recommends fel_domination

### How to Reproduce

No response

### Snapshot (Link)

https://pastebin.com/CCqSRTXj

**Comment by syrifgit** [comment]
wouldn't you want to save that to use in combat, instead of before combat when you actually have time to summon your pet?

**Comment by EricMiukyQin** [comment]
I know what u mean. Shouldn't be a problem if only be used in combat. I will close it, ty~~
