### ISSUE TITLE
[REC] Affliction Warlock cleave does not recommend summon_darkglare

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#3606]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In WarlockAffliction.lua, shadow_embrace max_stack is either 2 or 4 depending on talent. However in cleave APL, shadow_embrace.stack must be 3 when shadow_embrace talent is enabled, which causes this issue when talent drain_soul is inactive.
![image](https://github.com/user-attachments/assets/7e1b4812-46a2-47cb-af0c-f3b3dd73aba5)
![image](https://github.com/user-attachments/assets/b62a2423-27f0-48dc-bda5-64f4570365de)

### How to Reproduce

No response

### Snapshot (Link)

https://pastebin.com/cuZAszJ1

**Comment by syrifgit** [comment]
The line is identical in the actual sim. The max stacks is 4 because you have the talent, so it is possible to stack it to 3, isn't it? 3 shadow bolts would do it? max stacks =/= possible stack values.

max stack of 4 could have 0, 1, 2, 3, 4.

In your snapshot you have 0 stacks.

Additionally, please provide a Raidbots quicksim of your character.

**Comment by EricMiukyQin** [comment]
What I mean is that if u have talent shadow_embrace enabled, in the first condition, u would check if debuff.shadow_embrace.stack is exactly equal to 3. However, if u have no talent drain_soul enabled at the same time, the maxium shadow_embrace stack should be 2 instead of 4 and the stack could never equal to 3, which causes this condion never be true.

**Comment by EricMiukyQin** [comment]
debuff.shadow_embrace.stack = 3
3 might be a variable instead of a constant, which should be similar as what u did in the code

**Comment by Hekili** [comment]
I'm following.  I'll adjust the Shadow Embrace stack checks to be appropriate for DS vs. SB.

**Comment by Hekili** [comment]
Should be fixed in 1.0.7
