### ISSUE TITLE
[REC] Rogue Subltely - Coup De Grace not showing icon. Shows Black Powder instead.

### ISSUE THREAD

**Issue by myrex1** [Hekili/hekili#3608]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After 4 successful strikes with Unseen Blade. (Spell id: 441786).
Eviscerate is replaced with the ability Coup de Grace (Spell id: 441423).

Current rotation will not display Coup de Grace and show Black Powder (Spell id: 319175) instead.

Rotation will then be stuck in a loop of building Gloodblade/Shuriken Storm to then spending Black Powder.

### How to Reproduce

1. Rogue Subtlety.
2. Talents - CUQA27SZpS4XnmFfcXRqkppuwDAMYAAAAAAYWmZmlJDLLYmZMGzMzMzMzY2YmZGbzMDPwMDYmlZbAAAAYGMAGzGMwgZ20CtYDD
3. Allow vanish when solo deselected and shadowmeld deselected.
4. Follow rotation as displayed.

### Snapshot (Link)

https://pastebin.com/a0tKG08a

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cDWRU3iyy2af5UDfNunQQn

**Comment by syrifgit** [comment]
Take the snapshot when you're fighting something and the recommendation is wrong, not when you're standing around outside of combat.

**Comment by myrex1** [comment]
that was taken as the mob died but recommendation showed. didnt realise there was a difference.

**Comment by syrifgit** [comment]
Well, none of the abilities you mentioned having an issue with are in the snapshot, so hard to diagnose anything. Press it when the issue is **currently** on your screen, can you recreate it at a dummy?

**Comment by myrex1** [comment]
Yup. im trying now, was difficult in open world with scaling as it was.

**Comment by myrex1** [comment]
https://pastebin.com/uZgMhrxL

PSA - Above snapshot and below screenshot. 

![image](https://github.com/user-attachments/assets/5a94a4d3-0bfe-46e6-b20d-4a64af740595)

**Comment by Sedveth** [comment]
> https://pastebin.com/uZgMhrxL
> 
> PSA - Above snapshot and below screenshot.
> 
> ![image](https://private-user-images.githubusercontent.com/13150080/363445462-5a94a4d3-0bfe-46e6-b20d-4a64af740595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDcxMTgsIm5iZiI6MTcyNTIwNjgxOCwicGF0aCI6Ii8xMzE1MDA4MC8zNjM0NDU0NjItNWE5NGE0ZDMtMGJmZS00NmU2LWIyMGQtNGE2NGFmNzQwNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE2MDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYjlmODRiMTBmOTkzMjhkNDEzYzQxZDM5NjU5ZDRiNWNlNzFlMWNhZjA2MDE0ZWViYWJjZTYzMGZjYjE2YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dk6vrPhhG9U-QnXiuznvW5O6PZRn0fwRo1ZRbKoBirU)

From your screenshot, look like you dont have Shadow Dance up while still have 1 charge, so it wanna send Black Powder to preserve Coup De Grace for your Dance.

**Comment by myrex1** [comment]
Yeah your right. there is a point in the rotation that shadowdance still has 20-25 seconds left on its cooldown and you get abit energy starved. so naturally it will just backstab/gloomblade and black powder until shadow dance is back off cooldown.

@Sedveth credit for point that out. VMT. closed.
