### ISSUE TITLE
[REC] Assassination Rogue Cold Blood different spell id with Fatebound / Inevitability

### ISSUE THREAD

**Issue by mztikk** [Hekili/hekili#3609]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When talented into [Inevitability](https://www.wowhead.com/spell=454434/inevitability) from fatebound the spell and buff id of cold blood changes from 382245 to 456330 and thus getting stuck at recommending at cold blood since it doesnt detect the buff being active and spell being on cd

### How to Reproduce

Take Fatebound and Inevitability

### Snapshot (Link)

https://pastebin.com/jrzgnL6f

**Comment by syrifgit** [comment]
PR Opened: https://github.com/Hekili/hekili/pull/3629

Just need Hekili's review

**Comment by mztikk** [comment]
Its also spell id not only buff id

**Comment by superwario15** [comment]
The constant Cold Blood priority recommendation was fixed, but now it gets recommended as soon as the buff is gone, even if Cold Blood is on cooldown.

I was able to resolve this issue by modifying the Cold Blood talent in RegisterAbilities:

Line 1901:
`id = function() return talent.inevitability.enabled and 456330 or 382245 end,`

Added new line after 1915:
`copy = { 382245, 456330 },`

**Comment by syrifgit** [comment]
> The constant Cold Blood priority recommendation was fixed, but now it gets recommended as soon as the buff is gone, even if Cold Blood is on cooldown.
> 
> I was able to resolve this issue by modifying the Cold Blood talent in RegisterAbilities:
> 
> Line 1901: `id = function() return talent.inevitability.enabled and 456330 or 382245 end,`
> 
> Added new line after 1915: `copy = { 382245, 456330 },`

Yes I forgot to change the ability ID too, I only did the buff by mistake.

**Comment by Hekili** [comment]
This will be resolved in 1.0.8
