### ISSUE TITLE
Arcane Mage - Recommending Arcane Barrage one 2 stacks of Nether Precision instead of 1

### ISSUE THREAD

**Issue by Dreamin93** [Hekili/hekili#3610]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Arcane Mage Spellslinger (I think it does it for Sunfury too).

You want to use Arcane Barrage when you have 1 stack of Nether Precision, spellqueued straight after Arcane Blast.
The current action says to do this, but the addon seems to think you having 2 stacks of nether precision is the same as having 1.
So the rotation should be: Missiles > Blast > Blast > Barrage
Instead the addon is recommending: Missiles  > Blast > Barrage

Syrif made a band-aid fix last night on the discord:
prev_gcd[1].arcane_blast & prev_gcd[2].arcane_blast & prev_gcd[3].arcane_missiles & time - action.arcane_blast.last_used < 0.015 | cooldown.touch_of_the_magi.ready

### How to Reproduce

Enter Game
Play as Spellslinger build (ST or AOE, they are pretty much the same)
Follow Addon:
Evocation > Arcane Surge > Arcane Barrage > Touch of the Magi > Shifting Power > Arcane Missiles > Arcane Blast > Arcane Barrage > Arcane Missiles > Arcane Blast > **Arcane Barrage** (Should be Arcane Blast again and then spellqueue Arcane Barrage).

### Snapshot (Link)

https://pastebin.com/rwNc8t4x 

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/jJ38PUJZ8WNKLPNR4PWh8v

### Contact Information

jodran93

**Comment by Hekili** [comment]
I will be testing a fix in 1.0.7.  Note that the Arcane priority is likely to be rewritten in the near future anyway.
