### ISSUE TITLE
Hekili not prioritizing maelstrom casts Enhancement Shaman

### ISSUE THREAD

**Issue by Gondhy** [Hekili/hekili#3611]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

At max Maelstrom Hekili is prioritizing stormstrike and other spells until they are on GCD before lightning bolt or chain lightning ETC while at max maeltrom.

### How to Reproduce

Talents tree used:
CcQA6DE2ZxOD3n18X41tWLU5RNzMz2MzMGjZYGmFsMjZAAAAAAAAAAsBwYGDDZB2GN0gFAMLTGYWYMzMGzMzCWmZmswyYZMzAAMD

### Snapshot (Link)

https://pastebin.com/Ru60bmEq

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/gMmrkewbSoScfXgEowjzmq

### Additional Information

It does it for multi-target as well. Posted my SimC so it can be tested for different scenarios if needed.

# Blueogre - Enhancement - 2024-08-30 10:10 - US/Thrall
# SimC Addon 11.0.2-01
# WoW 11.0.2.56313, TOC 110002
# Requires SimulationCraft 1000-01 or newer

shaman="Blueogre"
level=80
race=draenei
region=us
server=thrall
role=attack
professions=herbalism=100/mining=98
spec=enhancement

talents=CcQA6DE2ZxOD3n18X41tWLU5RNzMz2MzMGjZYGmFsMjZAAAAAAAAAAsBwYGDDZB2GN0gFAMLTGYWYMzMGzMzCWmZmswyYZMzAAMD

# Saved Loadout: Mythic+ Totems
# talents=CcQA6DE2ZxOD3n18X41tWLU5RNzMzyMDGzMDzMzshlZMDAAAAAAAAAAwCsAzYhx2AYGwGAmlhZwswYmZMmZmFsMzMglxyYmBAYG
# Saved Loadout: Mythic+ Storm
# talents=CcQA6DE2ZxOD3n18X41tWLU5RNzMz2MzMGjZYGmFsMjZAAAAAAAAAAsBwYGDDsAbDDGsAgZZYgZhxMzYMzMLYZmZYhlxyYmBAYG

# Flamestonge's Coif of the Feverflare (571)
head=,id=229115,bonus_id=10297/11311/6652/1701/1643/10254
# Queensfang Choker (538)
neck=,id=225561,bonus_id=11128,drop_level=78
# Amice of Oblivion (554)
shoulder=,id=221048,bonus_id=11338/10386/6652
# Gem-Woven Shawl of the Fireflash (571)
back=,id=224663,bonus_id=10297/6652/1690/1643/10254
# Chitinoid Chainmail of the Peerless (571)
chest=,id=224682,bonus_id=10297/6652/1688/1643/10254
# Artisan Officer's Shirt (1)
shirt=,id=89195
# Tabard of Brute Force (1)
tabard=,id=43349
# Webweave Wristguards (532)
wrist=,id=225529,bonus_id=11128,drop_level=77
# Claws of Tainted Ichor (554)
hands=,id=221162,bonus_id=11338/10386/6652
# Lamplighter's Cinch (515)
waist=,id=220126,bonus_id=11128,drop_level=75
# General's Pungent Legguards (532)
legs=,id=225526,bonus_id=11128,drop_level=77
# Smuggled Nerubian Boots (532)
feet=,id=225523,bonus_id=11128,drop_level=77
# Hissing Blackblood Ring (532)
finger1=,id=225545,bonus_id=11128,drop_level=77
# Radiant Necromancer's Band (541)
finger2=,id=221200,bonus_id=10385/10387/6652/10395/10392,drop_level=78
# Horn of Declaration (554)
trinket1=,id=217041,bonus_id=11128/11054,drop_level=80
# Entropic Skardyn Core (571)
trinket2=,id=219296,bonus_id=10297/10388/6652/1606/10254
# Deep Terror Carver (571)
main_hand=,id=221248,bonus_id=10297/6652/1606/10254
# Ironclaw Knuckles  (558)
off_hand=,id=222467,bonus_id=11297/11298/9627,crafted_stats=36/49,crafting_quality=5

### Gear from Bags
#
# Coif of the Reckoning's Vengeance (525)
# head=,id=220131,bonus_id=11128,drop_level=76
#
# Dredger's Developed Helm  (548)
# head=,id=222475,bonus_id=11297/11298/9624/10876,crafted_stats=40/36,crafting_quality=2
#
# Long-Lost Choker (541)
# neck=,id=211063,bonus_id=11306/6652/10394/10393,drop_level=78
#
# Tower-Keeper's Shoulderguards (518)
# shoulder=,id=220113,bonus_id=11128/11054,drop_level=75
#
# Marsh Hopper's Spaulders (574)
# shoulder=,id=223938,bonus_id=10296/6652/1609/10254
#
# Anvilhide Cape (541)
# back=,id=221088,bonus_id=10385/10387/6652,drop_level=78
#
# Chef Chewie's Towel (554)
# back=,id=221054,bonus_id=11338/10386/6652
#
# Cape of the Favored (532)
# back=,id=225549,bonus_id=11128,drop_level=77
#
# Gem-Woven Cloak of the Fireflash (564)
# back=,id=224664,bonus_id=10287/6652/1695/1636
#
# Chainmail of Sina's Stalwarts (525)
# chest=,id=220109,bonus_id=11128,drop_level=76
#
# Rescued Aeroknight's Gloves (525)
# hands=,id=225524,bonus_id=11128,drop_level=76
#
# Distressed Breeches (362)
# legs=,id=220319,bonus_id=10350,drop_level=80
#
# Lava-Forged Cogwheel (518)
# finger1=,id=224644
#
# Ancient Fungarian's Fingerwrap (528)
# finger1=,id=223377,bonus_id=11061,drop_level=76
#
# Signet of the Priory (541)
# trinket1=,id=219308,bonus_id=10385/10387/6652,drop_level=78
#
# Harvester's Edict (548)
# trinket1=,id=219317,bonus_id=10385/10387/6652,drop_level=79
#
# Nizrek's Holographic Manipulator (532)
# trinket1=,id=225970,bonus_id=11128,drop_level=77
#
# High Speaker's Accretion (541)
# trinket1=,id=219303,bonus_id=10385/10387/6652,drop_level=78
#
# Imperfect Ascendancy Serum (561)
# trinket1=,id=225654,bonus_id=10288/6652/1633
#
# Shadowed Essence (571)
# trinket1=,id=225693,bonus_id=10297/6652/1472/10254
#
# High Speaker's Accretion (548)
# trinket1=,id=219303,bonus_id=10385/10387/6652,drop_level=79
#
# Ironclaw Great Mace  (548)
# main_hand=,id=222468,bonus_id=11297/11298/9624,crafted_stats=40/32,crafting_quality=2
#
# Lamplighter Elite's Hammer of the Fireflash (571)
# main_hand=,id=229134,bonus_id=10297/11311/6652/1692/1643/10254
#
# Ancient Forged Ritual Knife of the Aurora (545)
# main_hand=,id=224699,bonus_id=10382/6652/1707,drop_level=79
#
# Kaheti Confiscated Mallet (532)
# main_hand=,id=225359,bonus_id=11128,drop_level=77
#
# Cursed Pickaxe (518)
# main_hand=,id=224837
#
# Dredger's Developed Defender  (545)
# off_hand=,id=222474,bonus_id=11297/11298/9623,crafted_stats=32/40,crafting_quality=1
#
# Broodsworn Legionnaire's Pavise (493)
# off_hand=,id=195520,bonus_id=10407/1567/8767
#
# Expeditionary Bulwark of the Fireflash (532)
# off_hand=,id=224635,bonus_id=10382/6652/1692/10844/11036,drop_level=77

### Additional Character Info
#
# upgrade_currencies=c:2915:25/c:1792:1917/c:2914:39/c:3008:617
#
# slot_high_watermarks=0:571:571/1:541:541/2:554:554/3:571:571/4:515:548/5:532:541/6:532:532/7:532:532/8:554:554/9:532:574/10:571:571/11:571:571/12:483:532/13:545:545/14:571:571/15:558:558/16:493:509

# Checksum: 60b7ec65

### Contact Information

Discord ID: gaud8957

**Comment by Hekili** [comment]
Lightning Bolt to spend Maelstrom was checked before Lava Lash was selected:

```
        36.  lightning_bolt ( aoe - 4 )
        The action (lightning_bolt) is usable at (0.00 + 0.00) with cost of 25000 mana (have 2285116).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( aoe ) called from ( Enhancement:default:22 ) would PASS at 0.00.
        active_enemies[2.00] > 1 & ( rotation.standard[true] | rotation.simple[true] )
         - this entry's criteria FAILS: ( ! talent.tempest.enabled[true] | ( tempest_mael_count[0.00] <= 10 & buff.awakening_storms.stack[1.00] <= 1 ) ) & ( ( active_dot.flame_shock[1.00] = active_enemies[2.00] | active_dot.flame_shock[1.00] = 6 ) & buff.primordial_wave.up[false] & buff.maelstrom_weapon.stack[10.00] = buff.maelstrom_weapon.max_stack[10.00] & ( ! buff.splintered_elements.up[false] | fight_remains[30.00] <= 12 | raid_event.adds.remains[30.00] <= gcd.max[1.39] ) )
```

The criteria, as written here, would've fired if Primordial Wave were up and Flame Shock had been spread (i.e., why Lava Lash is recommended here).

You can see in your sim that the APL, as written, still has some abilities used at a higher priority despite 10 stacks of Maelstrom Weapon:

![image](https://github.com/user-attachments/assets/61ffd3d0-df50-48a6-b93d-08cb8a990563)

![image](https://github.com/user-attachments/assets/94d68bee-ff1d-4a5e-b675-833986e7468c)

![image](https://github.com/user-attachments/assets/2ea7338a-f017-474c-91f4-f078f00a95ce)

In your snapshot, you do have target swaps turned off (`cycle = false`), so I may need to revise the Flame Shock check to only count `cycle_enemies` instead of `active_enemies`, but I might not because Lava Lash will spread Flame Shock regardless.

The next Maelstrom Weapon spenders are not much further down the AOE action list:

```
actions.aoe+=/tempest,cycle_targets=1,if=buff.maelstrom_weapon.stack=buff.maelstrom_weapon.max_stack|(buff.maelstrom_weapon.stack>=5&(tempest_mael_count>30|buff.awakening_storms.stack=2))
actions.aoe+=/windstrike,cycle_targets=1,if=talent.thorims_invocation.enabled&buff.maelstrom_weapon.stack>1&ti_chain_lightning
actions.aoe+=/crash_lightning,if=talent.crashing_storms.enabled&((talent.unruly_winds.enabled&active_enemies>=10)|active_enemies>=15)
actions.aoe+=/lightning_bolt,if=(!talent.tempest.enabled|(tempest_mael_count<=10&buff.awakening_storms.stack<=1))&((active_dot.flame_shock=active_enemies|active_dot.flame_shock=6)&buff.primordial_wave.up&buff.maelstrom_weapon.stack=buff.maelstrom_weapon.max_stack&(!buff.splintered_elements.up|fight_remains<=12|raid_event.adds.remains<=gcd))
actions.aoe+=/lava_lash,if=talent.molten_assault.enabled&(talent.primordial_wave.enabled|talent.fire_nova.enabled)&dot.flame_shock.ticking&(active_dot.flame_shock<active_enemies)&active_dot.flame_shock<6
actions.aoe+=/primordial_wave,cycle_targets=1,if=!buff.primordial_wave.up
actions.aoe+=/chain_lightning,cycle_targets=1,if=buff.arc_discharge.up&buff.maelstrom_weapon.stack>=5
actions.aoe+=/elemental_blast,cycle_targets=1,if=(!talent.elemental_spirits.enabled|(talent.elemental_spirits.enabled&(charges=max_charges|feral_spirit.active>=2)))&buff.maelstrom_weapon.stack=buff.maelstrom_weapon.max_stack&(!talent.crashing_storms.enabled|active_enemies<=3)
actions.aoe+=/chain_lightning,cycle_targets=1,if=buff.maelstrom_weapon.stack=buff.maelstrom_weapon.max_stack
```

I'm closing this as working as presently designed, but I wouldn't be surprised if there are updates to the sim profile that would change this behavior a little.  Also, please note that the sim comparison is not apples-to-apples because your snapshot is in a 4-target scenario while your sim is Patchwerk (1 boss target).
