### ISSUE TITLE
[REC] Assassination Death Stalker Clear The Witnesses

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#3612]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Assassination Death Stalker Hero Talent, when the buff "Clear The Witnesse" is up, we should use Fan of Knives instead of Mulitate as builder even in single target, but seems like Hekili ignored this rule. I even sim my profile and in raidbots, we can see it use Fan of Knives in rotation.

### How to Reproduce

1. Enter the game as Assassination
2. Start rotation in single target
3. Hekili will ignore Fan of Knives in rotation when "Clear The Witnesses" is up

### Snapshot (Link)

https://pastebin.com/PR0t2rii

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/crHKSvsLVaDLhwJzmiZ9Gd

**Comment by Hekili** [comment]
It looks like Fan of Knives was not recommended because you have funneling toggled on.

```
 - this entry's criteria FAILS: variable.use_filler[true] & ! priority_rotation[true] & ( spell_targets.fan_of_knives[1.00] >= 3 | buff.clear_the_witnesses.up[true] & ! talent.vicious_venoms.enabled[false] )
 ```
