### ISSUE TITLE
[REC] WW Monk - Recommendation Failed - Auto generated Snapshot

### ISSUE THREAD

**Issue by Duderocktv** [Hekili/hekili#3613]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Very intermittently, during rotation in dungeons, I will get an error message about the recommendation and an autosave to the snapshot.

Not sure how to reproduce. Attached Pastebin

### How to Reproduce

1. Be Windwalker Monk in M+ build from Wowhead 
2. Enter a dungeon.
3. Just follow rotation as normal, sometimes it pops up
Very intermittent.

### Snapshot (Link)

https://pastebin.com/jhfs0AtU

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fMv5iMj5pSDeMYytEnaxKZ

**Comment by Hekili** [comment]
I will make a revision for 1.0.7 that would use Tiger Palm in these scenarios.
