### ISSUE TITLE
[REC] Demonology Warlock recommends Tyrant right before Charhound (Vilefiend replacement talent)

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#3614]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When following the rotation for Demo lock. Often times I'll find that Tyrant will be the current recommendation but the next recommendation will be Charound (Vilefiend replacement). The expected result would be that Charhound is cast first so that it's buffed and extended by Tyrant. This does not always happen, only seems to happen when the CDs get desynced at some point. If you start from scratch on a target dummy the Charhound is recommended early enough in the rotation that it gets buffed by Tyrant because it casts Hounds after Charhound.

It seems to be an issue where Hounds are already out and Charhound and Tyrant are coming off cooldown around the same time.

My guess is there needs to be some padding that if Charhound (vilefiend) is coming off CD within a few seconds, delay Tyrant a second to get Charhound into the Tyrant buff window. Not sure.

### How to Reproduce

Follow Hekili rotation with Demo lock with Tyrant and Charhound talented.

### Snapshot (Link)

https://pastebin.com/8y1n7fwr

**Comment by Hekili** [comment]
There are priority updates for Demo Lock for 1.0.7 that may or may not address this.  I'll need a ticket from 1.0.7 after it's posted.

**Comment by Reshuffling** [comment]
The APL for Tyrant is not affected by Charhound/Vilefiend so this can happen with pre pull hound or desync holding CDs for something. Doesn't look like the APL will change either. 

Have to make a custom condition, or maybe use the grimoire felguard interaction. 

Conclusion doesn't look like the apl will change because it syncs 100% in a perfect world. Just giving some input from the demo lock apl guy. 
![Screenshot_20241012-200329](https://github.com/user-attachments/assets/3780ded0-0cce-4081-9b76-f20ddde05086)

**Comment by Jumimaru** [comment]
What is the status on this ticket, will it be implemented?

**Comment by syrifgit** [comment]
Given how long ago this was, can you provide new snapshots of the issue + a new quicksim link?

**Comment by Jumimaru** [comment]
This is not my ticket, but as a Demo lock I haven't experienced this after the new patch.

I have no clue if the owner of the ticket is still experiencing the problem.

For me it is a closed case 🙂
