### ISSUE TITLE
[REC] The Hunt not properly being recommended, differs from sims. 

### ISSUE THREAD

**Issue by bsdgaming** [Hekili/hekili#3615]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The hunt is not being recommended as a top prio when starting a fight. The hunt procs a free charge of reavers glaive.

All sims use The Hunt to start a fight. right after immo auro and sigil of flame in precombat.

### How to Reproduce

Enter the game and start a fight with The Hunt and Aldrachi Reaver Talented...
Raidbots sim included.

### Snapshot (Link)

https://pastebin.com/wVQaCKNL

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fiKzp7Cmr65M29Kyn15UB8

**Comment by syrifgit** [comment]
The sim runs a strict opener sequence which is not replicated with Hekili as it could easily lead to gameplay issues. It could be possible to modify the APL manually and have it included.

**Comment by syrifgit** [comment]
Closing as this issue is many, many addon versions ago. If the issue still exists, please open a new ticket with new snapshots and sims.
