### ISSUE TITLE
Cheap shoot

### ISSUE THREAD

**Issue by antrikos** [Hekili/hekili#362]
Hello I have notice after the last 2 updates in my rotation the addon tells me to use Cheap shoot and also for first time on my chat " Hekili : snapshoot saved.. Hekili : Snapshoot are viewable via /hekili (until u reload ur ui) 
https://imgur.com/n3YsDgR 
https://imgur.com/cdK3laP

**Comment by Hekili** [comment]
Yes, Cheap Shot is added when you're using Prey on the Weak.

If you look at /hekili > Snapshots, you'll see there's a checkbox to automatically create a snapshot when a recommendation couldn't be determined.  It'll only happen once per instance of combat.  That makes it easier for people to submit snapshots when that happens.

**Comment by antrikos** [comment]
ok thanks, is that any way to remove cheap shoot because for pve is useless?

**Comment by Hekili** [comment]
Is it useless in PvE?  Explain.  (I'm fairly sure Cheap Shot is intended to not be recommended in boss fights, but if that's not working, nobody's reported it.)

But yes, you can disable abilities entirely in /hekili > Abilities.  Or you can modify your own priority as you see fit in /hekili > Priorities.

**Comment by Hekili** [comment]
Hm, I see that the logic *is* missing that would avoid Cheap Shot in boss encounters.  Going to add it in.

**Comment by antrikos** [comment]
Thanks again ye I just check it on darkshore boss :)
