### ISSUE TITLE
[REC] Assassination Rogue - Deathstalker - Darkest Night Falling Off

### ISSUE THREAD

**Issue by Grayfox2325** [Hekili/hekili#3621]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With Deathstalker's Mark, when your marked target dies, you get a 30 sec buff Darkest Night. Within that 30 seconds if you use a full combo point Envenom on a new target, they become marked. You want this rolling 100% of the time, never let it drop. Currently seeing this drop occasionally in dungeons which I don't think should ever happen. Could be related to the blizzard bug of Echoing Reprimand combo points not counting towards Mark/Darkest Night.

### How to Reproduce

1. Open up on a target dummy with a stealthed ambush to apply Deathstalker's Mark.
2. Use up all of Deathstalker's Mark until you get the Darkest Night buff.
3. Continue rotation until you see the first use of combo points upon receiving Darkest Night buff is not a full combo Envenom.

### Snapshot (Link)

https://pastebin.com/M8ZZugi7

**Comment by syrifgit** [comment]
I would say it's due to echoing reprimand because it thinks you're spending 7 on the line that chose envenom. Maybe we need a stricter check for that buff to not count animacharged for the purposes of it? @Hekili

**Comment by Sedveth** [comment]
> I would say it's due to echoing reprimand because it thinks you're spending 7 on the line that chose envenom. Maybe we need a stricter check for that buff to not count animacharged for the purposes of it? @Hekili

I reported this issue with Echoing Reprimand long time ago that if you land on charged combo point and need to refresh SnD, Hekili will suggest to SnD at that one but it didn't work with SnD at all and just count as normal combo point, it was with the old apl which you wanna SnD at max combo point but at the moment, probably not the big issue because we can extend it

**Comment by Sedveth** [comment]
Just want to confirm that by doing this, it will fix this problem
![image](https://github.com/user-attachments/assets/5946aaed-7a12-4469-9934-671cd4858dd6)

**Comment by syrifgit** [comment]
PR already submitted, just waiting review/approval

**Comment by Hekili** [comment]
Fixed in 1.0.7
