### ISSUE TITLE
[REC] Outlaw Rogue (Opener) - Adrenaline Rush 'Use before Roll the Bones' is not working

### ISSUE THREAD

**Issue by matcollins** [Hekili/hekili#3624]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Currently specced into 'Loaded Dice' which guarantee's two matches for RtB. Have selected config value: Adrenaline Rush: 'Use before Roll the Bones {Opener) - Roll the Bones still shows priority over Adrenaline Rush in Opener.

Based on Snapshot, looks to be recommended there correctly, but not updating the UI

### How to Reproduce

1. Enter Game as Outlaw Rogue 
2. Spec into 'Loaded Dice' in Outlaw Tree (Row 6, item 3)
3. Select Hekili minimap Icon Outlaw config 'Adrenaline Rush: Use before Roll the Bones {Opener}
4. Verify Primary/AOE Recommended opener does not change and Roll the Bones still takes priority over Adrenaline Rush

### Snapshot (Link)

https://pastebin.com/GazruSrj

### Additional Information

https://imgur.com/a/f6u5rQJ

**Comment by syrifgit** [comment]
Please provide a raidbots quicksim of your character that shows this behaviour

**Comment by Hekili** [comment]
This has a fix incoming.  I mistyped the setting name that controls this opener as `settings.ld_opener` instead of `settings.use_ld_opener`.  Will be fixed in today's release.
