### ISSUE TITLE
Veng DH - recommending Meta and Fel Desolation While on CD

### ISSUE THREAD

**Issue by Grenmar** [Hekili/hekili#3625]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While dps'ing as Veng DH while in meta form it's recommending fel desolation and what looks to be meta again while they're both on CD and I am currently in Meta form.

### How to Reproduce

Use metamorphosis and cast fel desolation eventually it'll load up what looks to be a metamorphosis button and ask to cast fel desolation again even though you're in meta and fel deso is on CD

### Snapshot (Link)

https://pastebin.com/6wLnYgxa

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cUzzaMk6MNBY98GgUD8rps

### Contact Information

bear5312

**Comment by syrifgit** [comment]
It's telling you to cancel meta, this is intended behaviour.

**Comment by Grenmar** [comment]
It's still recommending fel desolation from being empowered by meta when it's on CD. Does the snapshot not show that?

**Comment by syrifgit** [comment]
Try cancelling meta and following the rotation, as well as searching for previous veng tickets about this same thing.
