### ISSUE TITLE
[REC] Destruction warlock priority list does not contain interrupt recommendation

### ISSUE THREAD

**Issue by vladislav-kibakov** [Hekili/hekili#3626]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello Hekili,

Unfortunately, since tww dropped, destruction warlock recommendation does not contain interrupt (Spell lock) even with "Interrupt" setting is on. 

![image](https://github.com/user-attachments/assets/c579a5a2-3184-496d-a267-a2a606b17668)

While other specs have one (e.g affliction): 

![image](https://github.com/user-attachments/assets/aaac3670-629f-4ecb-a41b-abad6ab763e7)

### How to Reproduce

Settings -> Priorities -> Destruction -> Action lists

### Snapshot (Link)

-

**Comment by syrifgit** [comment]
You can add it in yourself for now. Follow this guide and add it to the very top (position 1) of the list called "Default" which is written in blue.

https://github.com/Hekili/hekili/wiki/Custom-Priorities

**Comment by vladislav-kibakov** [comment]
Thank you for your response.

Yes, I did it initially. I opened the issue to help solve the problem for other users who might not be aware.

**Comment by syrifgit** [comment]
Pending PR: https://github.com/Hekili/hekili/pull/3629

**Comment by Hekili** [comment]
Fixed in 1.0.7
