### ISSUE TITLE
[FEATURE] Add Variable for Buff Blessing of An'she

### ISSUE THREAD

**Issue by holytobi** [Hekili/hekili#3627]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

if miss a variable in hekili. If i try to use "buff.blessing_of_anshe.up" the value is in any case false.

https://www.wowhead.com/spell=445200/blessing-of-anshe

So i think it's not implemented, because it's not in the "simcraft" rotation. But this is wrong (u can't ignore a 200% buff on HoW -.-) Simcraft will update this but maybe hekili can be earlier so i can write my own rotation :-)

**Comment by holytobi** [comment]
ok i checked the code it is implemented. I found an Registered Talent and an Aura and the Spell IDs are correct. it seams more like a bug that its false. Have to check the code deeper if i find the error

**Comment by syrifgit** [comment]
It's probably not tracked. Can you get the spellID from in-game of the actual buff, not the talent?

**Comment by holytobi** [comment]
i can find in the retribution.lua at "RegisterAuras" this lines: 
"-- The healing or damage of your next Holy Shock is increased by $s1%.
    blessing_of_anshe = {
        id = 445204,
        duration = 20.0,
        max_stack = 1
    }," 

this spell id is correct. i can create ingame a WeakAura with the id and it works.

iam not familar with your project so i don't know if it needs more for working ingame correctly. otherwise i would fix it and create a pull request. Maybe if u fixed it, u can post here the solution or reason why it dosent worked so i can help the next time

**Comment by Hekili** [comment]
Take a snapshot when Blessing of Anshe is applied to your character.

**Comment by holytobi** [comment]
https://pastebin.com/wrjbUUqX

**Comment by syrifgit** [comment]
It was using the Holy spec version spellID, I fixed this with https://github.com/Hekili/hekili/pull/3683
