### ISSUE TITLE
Assassination Rotation suggested to Envenom at 4 CP

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#3628]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I just wanna to open this again to confirm if this is correct behavior in SimC
Currently in apl: 

envenom,if=buff.slice_and_dice.up&buff.slice_and_dice.remains<5&combo_points>=5

envenom,if=!buff.darkest_night.up&effective_combo_points>=variable.effective_spend_cp&(variable.not_pooling|debuff.amplifying_poison.stack>=20|effective_combo_points>cp_max_spend|!variable.single_target)&!buff.vanish.up

envenom,if=buff.darkest_night.up&effective_combo_points>=cp_max_spend

In my sim, when I check, it never send any Envenom at CP <5 while sometimes Hekili will suggest to do it at 4 CP

### How to Reproduce

1>Enter game as Assassination
2>Start rotations and at some points, it will suggest to envenom at 4 CP. Because of this, sometimes it will mess up the Darkest Night buff to make you lose the chain cycle

### Snapshot (Link)

https://pastebin.com/5fjeDyfw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/xj4kHtCUu3mGTKLjV8YGpV/simc

**Comment by Sedveth** [comment]
Also sometimes, when at 5CP, at first few seconds, it will recommend to send Mutilate. after a while, it will changes to correct action which is sending finisher. (Darkest Night wasn't up for force 7 CP Envenom to get DeathStalker's Mark)
Here is the snapshot: https://pastebin.com/atz20G5v
or this (Fatebound Hero Talent): https://pastebin.com/7r214zfY

**Comment by Sedveth** [comment]
Another problem, it was already in another ticket but I will just add extra comment here.
When Darkest Night is up, you just wanna force 7 CP Envenom to start a new chain of DeathStalker's Mark but Hekili won't suggest to do it, still wanna finish at < 7 CP
Snapshot: https://pastebin.com/yZkia21D

**Comment by syrifgit** [comment]
The line that chose envenom is identical to the same line in the sim. We would not know if the actual simc behaviour is correct, you would need to take that up with the rogue theorycrafters.

Your effective spend is showing up as 4. When I log into my rogue, it shows up as 5. Do you have 7 max combo points?

If you do, can you go here and check the value of this variable? Just mouse over the box.

![image](https://github.com/user-attachments/assets/d980fac7-8177-423c-b1b9-761645b23b8e)

![image](https://github.com/user-attachments/assets/d82f8120-19ff-40b3-9ea2-649b8d149266)

**Comment by Sedveth** [comment]
> The line that chose envenom is identical to the same line in the sim. We would not know if the actual simc behaviour is correct, you would need to take that up with the rogue theorycrafters.
> 
> Your effective spend is showing up as 4. When I log into my rogue, it shows up as 5. Do you have 7 max combo points?
> 
> If you do, can you go here and check the value of this variable? Just mouse over the box.
> 
> ![image](https://private-user-images.githubusercontent.com/139663837/363518287-d980fac7-8177-423c-b1b9-761645b23b8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzY4MDQsIm5iZiI6MTcyNTIzNjUwNCwicGF0aCI6Ii8xMzk2NjM4MzcvMzYzNTE4Mjg3LWQ5ODBmYWM3LTgxNzctNDIzYy1iMWI5LTc2MTY0NWIyM2I4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwMDIxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmQ3MmEwYWExMmU2YWJjOWIzYWEzZDM4ODk4MjY2MWQwNTJlMDJlZjYxMGFiMTM5N2VlYjAxOGJjMjA2NGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SkWdcjCvdJL79mjCYC303Z2X5ockQUJuY5WjvOY_w2A)
> 
> ![image](https://private-user-images.githubusercontent.com/139663837/363518301-d82f8120-19ff-40b3-9ea2-649b8d149266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzY4MDQsIm5iZiI6MTcyNTIzNjUwNCwicGF0aCI6Ii8xMzk2NjM4MzcvMzYzNTE4MzAxLWQ4MmY4MTIwLTE5ZmYtNDBiMy05ZWEyLTY0OWI4ZDE0OTI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwMDIxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjVhYjU3MGM0MTc2NTJiMmU0OTBlZjVkNDJiYzUzNzFlYTEzYmYwNjEwZDlkNzA2YTY4Y2NkZThiZjJmNzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kTgniWxWfhrJKzKOxvKnVbWAvMI20er65fj6earEty0)

![image](https://github.com/user-attachments/assets/969f3fe7-1d4d-4b22-a4b9-0fa4a6d72ca6)
Yeah for some reasons, my value is 4 while I never touch anything here. I do have 7 max combo points

**Comment by syrifgit** [comment]
Hm it says your max is 6, must be a broken talent definition somewhere.

Are you in the discord? I don't have a levelled rogue but can help look at it in a bit.

**Comment by Sedveth** [comment]
> Hm it says your max is 6, must be a broken talent definition somewhere.
> 
> Are you in the discord? I don't have a levelled rogue but can help look at it in a bit.

Yeah I tagged you in discord, thank you for pointing out the issue, it drives me crazy

**Comment by Hekili** [comment]
Should be fixed in 1.0.7
