### ISSUE TITLE
DK Icecap build Apl with Ashvane razor coral

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#363]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Ashvane razor coral doesnt want to be popped after Blood of the enemy essence comes up from second cd or line up with empowered rune weapon, just shows when to put up the debuff but not when to pop it.

**To Reproduce**
Steps to reproduce the behavior: Do normal rotation put up razor coral and do rotation until big cds come back u can see that razor coral don´t want to be popped with big cds, it just continue keeps stacking forever without being recommended to pop
- Go to '...' 
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
Want the Ashvane razor coral to line up and pop when the big cds comeback seems be missing in icecap spec

**Screenshots**
If applicable, add screenshots to help explain your problem.![WoWScrnShot_052620_002442](https://user-images.githubusercontent.com/48166902/82846248-31016e00-9ee8-11ea-833b-dc26de614e78.jpg)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**  https://pastebin.com/mLi2vXjX

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**  https://pastebin.com/UdHH1vXR
https://pastebin.com/yw1KYY2N

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Looking at your snapshots:

```26.  ashvanes_razor_coral ( cooldowns - 6 )
The action (ashvanes_razor_coral) is usable at (0.00 + 0.95) with cost of 0.
    - the action is ready before the current recommendation (at +0.95 vs. +60.00).
List ( cooldowns ) called from ( Frost DK:default:6 ) would PASS at 0.95.
NONE
    - this entry's criteria FAILS: cooldown.empower_rune_weapon.remains[9.16] > 90 & debuff.razor_coral_debuff.up[true] & variable.other_on_use_equipped[true] | buff.breath_of_sindragosa.up[false] & debuff.razor_coral_debuff.up[true] & ! variable.other_on_use_equipped[true] | buff.empower_rune_weapon.up[false] & debuff.razor_coral_debuff.up[true] & ! talent.breath_of_sindragosa.enabled[false] | time_to_die[3599.05] < 21
There were no recheck events to check.
```

Razor Coral wasn't recommended based on its criteria not being met.

`cooldown.empower_rune_weapon.remains[9.16] > 90 & debuff.razor_coral_debuff.up[true] & variable.other_on_use_equipped[true]`
- didn't pass because ERW is on cooldown, but only for 9 more seconds.

`buff.breath_of_sindragosa.up[false] & debuff.razor_coral_debuff.up[true] & ! variable.other_on_use_equipped[true]`
- didn't pass because Breath of Sindragosa isn't active.

`buff.empower_rune_weapon.up[false] & debuff.razor_coral_debuff.up[true] & ! talent.breath_of_sindragosa.enabled[false]`
- didn't pass because ERW wasn't active.

`time_to_die[3599.05] < 21`
- didn't pass because the time to die couldn't be meaningfully calculated; the fight wasn't expected to end in less than 21 seconds.


What does a snapshot look like right after you've used ERW?

**Comment by Tobbelainen** [comment]
Tried again when i was mixing with throttle updates and throttle time it did show for  0.2 second and after awhile it did show, but dissapearing pretty fast but it works, same with Cold heart talent when to use chains of ice on 20 stacks it recommend me use it earlier sometimes, hopefully the throttle numbers fixed it=)

**Comment by Hekili** [comment]
I don't know that throttle settings would have any impact at all, but if you see a problem, snapshot when the problem is happening and we can look at it.  With snapshots of these perceived issues, we don't have to guess why they're appearing or not appearing.
