### ISSUE TITLE
Not seeing trinket recommendations

### ISSUE THREAD

**Issue by Ormal1708** [Hekili/hekili#3630]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I can't get any trinkets to display as recommendations, I know it used to be in toggles but I'm not seeing anything. A little help please.

**Comment by syrifgit** [comment]
You'll need to provide a snapshot as per the ticket instructions.

https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

Without having the snapshot, I'd say either you have cooldowns off or the trinkets haven't been added yet.

**Comment by Ormal1708** [comment]
Thanks! I have cooldowns enabled but then checked through gear and items and it looks like most trinkets aren't listed as yet. Appreciate the assistance.
