### ISSUE TITLE
[REC] Totemic Shaman continues to show Healing Rain (and it's cooldown) instead of Surging Totem

### ISSUE THREAD

**Issue by DrBostorm** [Hekili/hekili#3631]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When using the Shaman Totemic hero power, the priority list continues to show healing rain (and the shorter cooldown healing rain has) instead of its replaced ability "Surging Totem".

### How to Reproduce

1. Enter game as a Shaman
2. Select Restoration Specialization
3. Select Totemic hero power
4. Once you cast your shields, the healing rain ability will show up on the priority bar... which is now replaced with Surging Totem

### Snapshot (Link)

https://pastebin.com/rKEd0y4P

### Contact Information

drbostorm in Discord

**Comment by syrifgit** [comment]
I am working on some resto shaman stuff, stay tuned

**Comment by syrifgit** [comment]
Pending PR: https://github.com/Hekili/hekili/pull/3629

**Comment by Hekili** [comment]
Should be fixed in 1.0.7
