### ISSUE TITLE
[REC] Vengeance Prio in Metamorphosis does not work

### ISSUE THREAD

**Issue by Valhall2660** [Hekili/hekili#3634]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I´ve disabled the Spell Metamorphosis cause as a Tank you have to use it situatial, but when i use it, hekili does not show me any prio, seems like hekili does not know the spells or so ? 
The only showed Icon is Metamorphosis with the littel red star inside the Icon cause of its disable. 
Is there anyone else with this kind of Problem ? 

### How to Reproduce

Use Metamorphosis and Hekili dont know the Prio any more, after Metamorphosis is over, Prio is working fine as before.

### Snapshot (Link)

Vengeance; Primary - [Cancel Buff](0.00)

**Comment by syrifgit** [comment]
That is telling you to cancel the meta buff, this is intended behaviour. Refer to the DH discord for any specific questions about this.

`/cancelaura Metamorphosis`

**Comment by Hekili** [comment]
Just a heads-up, the cancelaura recommendation goes away in the next release.
