### ISSUE TITLE
Assassination Rogue: Potion ("Tempered Potion") and trinket ("Horn of Declaration") not rec'd. Trink not in DB list either.

### ISSUE THREAD

**Issue by Silentzar** [Hekili/hekili#3635]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Though potion is checked, my "Tempered Potion" will never be rec'd like "Elemental Potion of Ultimate Power" used to. Neither is it seemingly recognized in the Hekili database.  Also, my trinket "Horn of Declaration" is not in the database and so cannot be rec'd during my boss fights (or at all apparently).  

### How to Reproduce

1. Go to the Gear and Items database. TWW stuff needs to be updated in there as it will not rec'd it.  The "Tempered Potion" is not in the database or recognized by Hekili.

### Snapshot (Link)

Cannot snapshot the lack of a rec'd (???)

### Additional Information

Is there a way to get an updated database of gear and items?

**Comment by Hekili** [comment]
Trinkets and potions are on the to-do list.
