### ISSUE TITLE
[REC] Prot pala dont recommend Word of Glory

### ISSUE THREAD

**Issue by Necrostrike** [Hekili/hekili#3636]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The addon does not recommend Word of Glory if HP drops below the WoG threshold.
Even if I have 5 Holy Power or shining light buff (1 or 2 stack).

### How to Reproduce

1. Enter game as Prot pala
2. Start fight with mobs (better with rares or tank dummy)
3. Down your HP lower then WoG threshold
4. Addon dont recommend Word of Glory

### Snapshot (Link)

https://pastebin.com/uQ9acWZi

**Comment by syrifgit** [comment]
It keeps choosing other spells before it even gets to the WOG. Perhaps it should be moved up the priority list, or assigned to defensives by default?

**Comment by mon1800** [comment]
It isn't just WOG. The addon will not recommend defensive cooldowns such as AD and GOAK or DS at the percentages it says it will. Tested this multiple times on raider test dummies.

**Comment by syrifgit** [comment]
They are not in the APL. You can add them yourself in the meantime.
