### ISSUE TITLE
[REC] Assassination pooling

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#3638]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I think the pooling function for Assassination is not working as intended.
I'm testing in dummy single target and for a lot of times, when we are at 5 combo point, what we should do is wait for energy and send Envenom in pandemic time for highest uptime of Envenom as possible, but for some reasons during the pooling time for few seconds, Hekili has a filler Mutilate suggested instead and it will change back to Envenom once we have desired energy, and sending Mutilate at 5 combo point if not for Darkest Night proc is a wrong play here.

### How to Reproduce

1. Enter game as Assassination
2. Hitting the dummy, follow the rotation once you meet the condition: at 5 CP, Envenom buff is up, low energy, instead of showing countdown timer for pooling to send Envenom, it has a filler Mutilate during the pooling

### Snapshot (Link)

https://pastebin.com/zcayU92z

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/sMovbyEshkrNoS5iCH7psK

**Comment by Hekili** [comment]
I have a test fix in 1.0.7, but it may not (fully?) solve this issue.  If it persists, please provide new snapshots.

**Comment by Sedveth** [comment]
> I have a test fix in 1.0.7, but it may not (fully?) solve this issue. If it persists, please provide new snapshots.

Yeah the new update did solve but not fully this issue, but it's much better now
Here is the snapshot after an update
https://pastebin.com/N8cz9zs5

**Comment by syrifgit** [comment]
This issue is multiple addon versions out of date. If it's still happening, open a new ticket with a fresh snapshot on the latest addon version.
