### ISSUE TITLE
Stutter/Hitching when the addon is installed

### ISSUE THREAD

**Issue by OGNoizey** [Hekili/hekili#364]
Hello, hope you're well.

I am experiencing some hitching/lag when using the addon that occurs when strafing/moving the camera.

When I uninstall the addon it fixes itself.

It's worth noting that I have used this addon in the past and did not experience these issues, which makes it hard for me to pinpoint where the problem is coming from.

Not sure if this is relevant for my type of issue but see below:

`build: v8.3.0-04-22.04
level: 120 (120)
class: MAGE
spec: fire

talents: flame_on
    frenetic_speed
    kindling
    living_bomb
    rune_of_power
    searing_touch
    shimmer

azerite: azerite_empowered = 3
    blaster_master = 2
    cauterizing_blink = 1
    eldritch_warding = 1
    firemind = 1
    impassive_visage = 1
    overwhelming_power = 1
    unstable_flames = 1
    wildfire = 2

essences: [essence_of_the_focusing_iris] = 2, spark_of_inspiration = 1, the_crucible_of_flame = 4, vision_of_perfection = 1

sets/legendaries/artifacts: none

gear: aqusirrs_swirling_sash = 1
    ashjrakamas_shroud_of_resolve = 1
    corporeal_supplicants_trousers = 1
    corrupted_gladiators_staff = 1
    gloves_of_staunched_wounds = 1
    heart_of_azeroth = 1
    mountainsage_robe = 1
    psyche_shredder = 1
    seal_of_questionable_loyalties = 1
    spaulders_of_miasmic_mycelia = 1
    stonemasons_guild_band = 1
    unbound_alchemist_stone = 1
    vile_manipulators_footwraps = 1
    vile_manipulators_hood = 1
    vile_manipulators_wristwraps = 1

corruptions: twisted_appendage = 2
    void_ritual = 1

itemIDs: 158075, 158314, 159239, 159253, 165678, 169223, 170811, 171088, 172774, 173431, 173845, 174060, 174117, 174127, 174953

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    potion = superior_battle_potion_of_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    pyroblast_pull = false
    save_2_runes = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false`

Is there anything you would need to know in addition to this?

Asides from the above, quality addon and great work.

Thanks in advance 
Noizey

**Comment by Hekili** [comment]
Fire Mage requires more computation than other specs.  I've put a lot of time into optimizing it, but it just requires more calculation.  You'd can play with the performance options in your spec options or you can show fewer icons in your Primary display.  Those are the avenues available for making Fire go more quickly.

Outside of that, a saner priority in Shadowlands will be your best bet.
