### ISSUE TITLE
[REC] Spellslinger AOE - One Arcane Blast not being recommended during AOE after Touch of the Magi

### ISSUE THREAD

**Issue by ambonif** [Hekili/hekili#3641]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During AOE, the rotation is supposed to recommend one Arcane Blast during Touch of the Magi, for some reason this is failing. I checked the code and it looks like it should work based on the handling function, but in the snapshot, it keeps detecting debuff.magis_spark_arcane_blast.up as false, despite Arcane Blast not yet being cast to consume it.

### How to Reproduce

Run the rotation with 3+ target dummies, cast Touch of the Magi on a primary target.

Failure is at:

        35.  arcane_blast ( spellslinger_aoe - 5 )
        The action (arcane_blast) is usable at (0.00 + 0.00) with cost of 24226 mana (have 336157).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( spellslinger_aoe ) called from ( Arcane:default:15 ) would PASS at 0.00.
        active_enemies[5.00] >= ( variable.aoe_target_count[3.00] + talent.impetus.enabled[true] ) & ! talent.spellfire_spheres.enabled[false]
         **- this entry's criteria FAILS: ( debuff.magis_spark_arcane_blast.up[false] & time[148.32] - action.arcane_blast.last_used[10.99] > 0.015 )**
        There were no recheck events to check.
        Time spent on this action:  0.10ms
        TimeData:Arcane-spellslinger_aoe-5:arcane_blast:0.10:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.00):Post Recheck(0.00)

### Snapshot (Link)

https://pastebin.com/BPzUjvqu

### Additional Information

Tried to troubleshoot it myself but can't figure it out. I tried changing the SpellID of Touch of the Magi debuff to what I see in game, but it still doesn't work.

**Comment by ambonif** [comment]
debuff.magis_spark_arcane_blast.up should be [true] since the handler function that's supposed to remove the magis_spark_arcane_blast "debuff" hasn't been triggered yet from here:

    touch_of_the_magi = {
        id = 321507,
        cast = 0,
        cooldown = 45,
        gcd = "off",
        school = "arcane",

        spend = 0.05,
        spendType = "mana",

        talent = "touch_of_the_magi",
        startsCombat = true,

        handler = function ()
            applyDebuff( "target", "touch_of_the_magi" )
            if talent.nether_munitions.enabled then
                state:QueueAuraEvent( "touch_of_the_magi", NetherMunitions, debuff.touch_of_the_magi.expires, "AURA_EXPIRATION" )
            end
            if talent.magis_spark.enabled then
                applyDebuff( "target", "magis_spark" )
                applyDebuff( "target", "magis_spark_arcane_barrage" )
                applyDebuff( "target", "magis_spark_arcane_blast" )
                applyDebuff( "target", "magis_spark_arcane_missiles" )
            end
            gain( 4, "arcane_charges" )
        end,

**Comment by Hekili** [comment]
Can you take a snapshot when magis_spark_arcane_blast is applied?

**Comment by Hekili** [comment]
nvm, I think I have a fix for this in 1.0.7

**Comment by ambonif** [comment]
If it matters, @Hekili, this didn't seem to fix it. It doesn't look like Touch of the Magi is still applying the debuff.
