### ISSUE TITLE
Darkmoon Deck: Ascension Proc 'Ascendance' confuses rotation into thinking DRE/Ascendance was used

### ISSUE THREAD

**Issue by Spuuwn** [Hekili/hekili#3642]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The buff proc for the trinket [Darkmoon Deck: Ascension] is called 'Ascendance'.
When this proc is active, Hekili mistakes this version of 'Ascendance' for the one from the DRE/Ascendance Shaman talent buff and thinks I can use windstrike and seems to modify the rotation suggestions assuming it is the Shaman buff.

### How to Reproduce

Equip trinket [Darkmoon Deck: Ascension] on a shaman (Enhance spec in this case).
Proc the trinket gaining its 'Ascendance' buff.
Hekili starts suggesting Windstrike thinking its a different buff called Ascendance from the shaman talent trees..

### Player Information (Link)

https://pastebin.com/Qn1LBZBr

### Error Messages (Link)

N/A

**Comment by Hekili** [comment]
Your snapshot is not taken at the time the issue occurs.

**Comment by Hekili** [comment]
Should be resolved in 1.0.7.

**Comment by Spuuwn** [comment]
I should point out I made a mistake with the source of the buff. It is the weapon embellishment [Darkmoon Sigil: Ascension] that procs 'Ascendance'. The trinket procs 'Ascendant'. My mistake, sorry.
