### ISSUE TITLE
Shadow Crash not being recommended for Shadow Priest on AoE

### ISSUE THREAD

**Issue by Hesparax** [Hekili/hekili#3644]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The AoE priority for Shadow Priest does not include Shadow Crash, either as a means of dotting mobs up or refreshing the existing DoTs.
In the snapshot provided above, you can see that 3 out of 5 mobs are dotted, and while the addon detects 5 targets, Shadow Crash is not being recommended to DoT up the remaining targets.
Similarly, Shadow Crash is not recommended to refresh the DoTs on the mobs either.
If I'm to hazard a guess, the priority is set to recommend Shadow Crash only on 8 targets, leading to incorrect recommendations on 5 targets and/or below.

### How to Reproduce

Engage combat with a pack of mobs as a Shadow Priest with Shadow Crash talented, and observe the lack of Shadow Crash being recommended.

### Snapshot (Link)

https://pastebin.com/Ls4PA6yg

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/azvFZNEqBpXBAu4wgLMj1D

### Contact Information

hesparax

**Comment by syrifgit** [comment]
Resolved in https://github.com/Hekili/hekili/pull/3683
