### ISSUE TITLE
Guardian rotation still not recommending heals or some defensives

### ISSUE THREAD

**Issue by gwenskey** [Hekili/hekili#3645]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I saw you updated Guardian today to include Defensives and Heals, so after updating I tested it out on the Dungeoneer's Training Dummy and Normal Tank Dummy in Dornagal, which do damage to you, but the only defensive recommended was Barkskin, Rage of the Sleeper,  and Incarn if you count those. 
Frenzied Regeneration, Renewal, and Survival Instincts were not recommended. Regrowth could also be recommended if talented into Dream of Cenarius.

### How to Reproduce

1. Attack Dungeoneer's Training Dummy in Dornagal alongside the Normal Tank Dummy
2. Use Incan, Rage of the Sleeper, and Barskin alongside full rotation as recommended
3. As health gets low, defensive or healing abilities are not recommended other than Barkskin, Incarn, and Rage of the Sleeper. 
4. Die while trying to get your health low enough with the perfect set of conditions to take a snapshot that don't include the above abilities mentioned. :D

### Snapshot (Link)

https://pastebin.com/BqMSc7dq

### Contact Information

Discord ID: asphyxia1705

**Comment by davidmann4** [comment]
check if you disabled them under "abilities" 

regrowth and renewal should be recommended if you have less then 65% life

```
actions.mitigation+=/regrowth,if=health.pct<65
actions.mitigation+=/renewal,if=health.pct<65
```

**Comment by gwenskey** [comment]
They are not disabled. Though Survival Instincts was under the category of cooldowns for some reason, so i moved it to defensives, but it's still not showing up.

**Comment by syrifgit** [comment]
His snapshot isn't even trying to call the mitigation sublist @davidmann4, it goes potion then bear. Missing the call right between them.

Reset your pack? Instructions in FAQ.

**Comment by gwenskey** [comment]
That did it! Thank you! Those all worked before a few updates ago, but I guess something went wonky and it stopped. I don't use custom profiles, so idk what went wrong, but thank you for helping me fix that! <3

**Comment by davidmann4** [comment]
ohh true 

![image](https://github.com/user-attachments/assets/12e0d7c9-b9c4-4a53-a656-c0457687f20b)

updated my hekili and logged into a guardian druid:

![image](https://github.com/user-attachments/assets/394f9f0b-9a9a-45c6-aef7-c8ee050620ca)

seems i did something wrong at my PR ( https://github.com/Hekili/hekili/pull/3620) since the mitigation list is missing

edit: 

after hitting reset everything is here

![image](https://github.com/user-attachments/assets/536c65d8-8d50-4370-8f51-1ce0a36b2643)


maybe because i did not changed the description?

**Comment by syrifgit** [comment]
The pack string wasn't up to date, so it was still building the APL from the last version, not your updated version. I added that fix to https://github.com/Hekili/hekili/pull/3648
