### ISSUE TITLE
[REC] Ravenous Honey Buzzer trinket always shows even after disabling

### ISSUE THREAD

**Issue by jsx228** [Hekili/hekili#3646]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The Trinket Ravenous Honey Buzzer is now showing up permanently in rotations if you have it equipped. Even when you disable it in gear and items. it still shows up. Even if you change it to toggle on interrupts etc anything, it will still show up. It does not show up when on cooldown.
![honey](https://github.com/user-attachments/assets/9b248e65-17a5-48bf-a12d-f82211518bd1)

### How to Reproduce

Equip Ravenous Honey Buzzer trinket.
Go to gear and items and disable (as per norm)
Hit training dummy or enter dungeon.
See the recommendation in game.

### Snapshot (Link)

https://pastebin.com/Gnm7fM56

**Comment by jsx228** [comment]
https://pastebin.com/8LNFtzs2

updated pastebin as per discord

**Comment by jsx228** [comment]
???

**Comment by Blujelly87** [comment]
Hi all, I can confirm I too have the same issue

**Comment by Hekili** [comment]
Please use this macro and provide the displayed results here.  It would be best to test out of combat, in combat, and in a boss fight:

`/run print(Hekili.State:IsDisabled("ravenous_honey_buzzer"))`

**Comment by jsx228** [comment]
Out of Combat: False
In Combat: False
During Boss Fight: False

edit: I see the recommendation and run it as well and it still says false when it is infront of me being recommended.
I have used Hekili for many years and it is the only way I play the game now bar a few classes - This is the FIRST time an item has stayed recommended even after disabling.

**Comment by chevyn11** [comment]
oppressive_orators_larynx in Items.lua also has an ID of 219298 https://github.com/Hekili/hekili/blob/thewarwithin/TheWarWithin/Items.lua#L134
Try disabling that trinket too (as a workaround).

As for a fix I think the larynx item id is 219318
https://www.wowhead.com/item=219318/oppressive-orators-larynx

**Comment by syrifgit** [comment]
```
    oppressive_orators_larynx = {
        cast = 0,
        cooldown = 120,
        gcd = "off",

        item = 219298,
        toggle = "cooldowns",

        proc = "damage",
    },	
```

@hekili duplicated ID
