### ISSUE TITLE
SIN Rogue: Unable to Make Recommendation - Primary #1

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3647]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Just doing questing and it took an automated screen shot.  Wanted to report before It crashed.

### How to Reproduce

Not sure, just was questing

### Player Information (Link)

https://pastebin.com/nQDZHKZN

### Error Messages (Link)

https://pastebin.com/nQDZHKZN

### Contact Information

Wren1740

**Comment by DrWren** [comment]
here is another one:

but this is for recommedndation #3

https://pastebin.com/LR1hvLkL

**Comment by Hekili** [comment]
This should be resolved in 1.0.9 and later.
