### ISSUE TITLE
Unholy DK

### ISSUE THREAD

**Issue by monoliith** [Hekili/hekili#365]
I've noticed when i'm using my Unholy DK, along the path after the elevator in Nyalotha, right before you enter the larger "open" area where you can choose which of the 4th paths to take to each pair (or trio) of bosses. Hekili glitches, and stops working periodically. It will actually disappear, or just 1 or 2 random abilities will sometimes light up. It will work fine when we get to a boss though.

Also; In Mythic plus dungeons the same thing happens from time to time. The Hekili bar will vanish; and random abilities will just start popping up. Just 1 or 2 at a time.

Every now and then it works fine in M+. But the Nyalotha issue happens every single time.

**Comment by Hekili** [comment]
Follow the ticket instructions and provide the required information.
Thanks.
