### ISSUE TITLE
[BUG] "Void blast" icon overwriting "Mind Blast" before void torrent

### ISSUE THREAD

**Issue by L3bulba** [Hekili/hekili#3651]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Most times while about to start Entropic Rift window, Hekili will recommend using our last Mindblast, and this usually shows the Void Blast Icon instead.

![image](https://github.com/user-attachments/assets/0f545b07-c8e8-4337-afce-d0df22b8815b)

### How to Reproduce

1. Run Voidweaver
2. General opener that reproduces issue:

- Shadow crash
- Dark Ascension + PI
- mind blast
- Issue shows second mindblast usage but with the Void blast icon

### Player Information (Link)

https://pastebin.com/Ag34xR3Z

### Error Messages (Link)

no error

### Contact Information

Lebulba#2311

**Comment by Hekili** [comment]
Will be resolved in 1.0.8 (probably)
