### ISSUE TITLE
After using Reaver's Glaive, addon suggests Soul Cleave instead of Fracture

### ISSUE THREAD

**Issue by REPlatinum** [Hekili/hekili#3652]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I tried to make some changes to the priority today.  After which, I hit the reload button under the Summary tab.  Before doing so, my priority showed I should use Fracture before Soul Cleave after using Reaver's Glaive.  This is correct as the Hero Talent "Fury of the Aldrachi" causes more dps this way.  However, after the reload, Soul Cleave is recommended instead of Fracture after Reaver's Glaive.  Can this be fixed?

### How to Reproduce

Enter Game as Vengeance Demon Hunter.  Take Aldrachi Reaver Hero Talent Tree.  Consume 20 Soul Fragments to trigger Reaver's Glaive, which replaces Throw Glaive ability.  use Reaver's Glaive.  Hekili should show Fracture then Soul Cleave.  Instead, Soul Cleave will be shown.

### Snapshot (Link)

https://pastebin.com/8L1ySVLv

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cPQw2bgsPNDaHU3eqpyqgh

### Contact Information

 moose3963

**Comment by Hekili** [comment]
Your sim uses Soul Cleave after Reaver's Glaive:

![image](https://github.com/user-attachments/assets/e6458199-5e66-415d-a877-0ebf9b5de512)

![image](https://github.com/user-attachments/assets/87a185c7-e71a-42a3-84fd-ec8ff8ae79b6)

![image](https://github.com/user-attachments/assets/53545267-2769-42ce-bb0e-2ed6f1865ab3)

![image](https://github.com/user-attachments/assets/0b4e221c-3051-479a-901f-9add4d6f731d)

**Comment by REPlatinum** [comment]
It should go Reaver's Glaive -> Fracture -> Soul Cleave.

**Comment by syrifgit** [comment]
Okay well the sim you provided disagrees with that statement, as seen in the screenshot above.

**Comment by REPlatinum** [comment]
I don't understand.  From what I see in the screenshot, it goes Reaver's Glaive -> Soul Cleave.

**Comment by syrifgit** [comment]
If you want to customize the priority, follow the instructions here: https://github.com/Hekili/hekili/wiki/Custom-Priorities

The "reload" button you're speaking about is the "reset this pack back to the default as written by the devloper".
