### ISSUE TITLE
Single Target Sunfury Arcane Opener

### ISSUE THREAD

**Issue by GitBearded** [Hekili/hekili#3653]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Not recommending Arcane Missiles after Evocate before surge to proc Nether Precision talent.

### How to Reproduce

Its the opener...it should be the third ability recommended and its not.

### Snapshot (Link)

https://pastebin.com/1k6FcCRa

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/nw4D21ixQRH9WYS7KHMXaH

### Contact Information

COLOSSAL

**Comment by syrifgit** [comment]
Opener is fixed with my arcane overhaul branch: https://github.com/syrifgit/hekili/tree/arcane-overhaul
