### ISSUE TITLE
Sunfury Arcane AoE Opener#1

### ISSUE THREAD

**Issue by GitBearded** [Hekili/hekili#3656]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Arcane Surge being recommended before orb into missiles. Should be Orb > Missiles >surge >barrage > touch > Blast > Barrage > Missiles

### How to Reproduce

Do the rotation.

### Snapshot (Link)

https://pastebin.com/8rDKg49h

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3r3kTaoxGv9wbTME2gt1KK

### Contact Information

COLOSSAL

**Comment by Hekili** [comment]
The Sunfury AOE list that's being called will be gone in next release.
