### ISSUE TITLE
Assasination Rogue Wrong Thristle Tea Recommendation 

### ISSUE THREAD

**Issue by alelsor** [Hekili/hekili#3657]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sometimes we get some weird recommendation that suggest thristle tea, mutilate and thristle tea again even on full energy

### How to Reproduce

It just happens randomly during the rotation, can not find a stable way to reproduce. 

### Snapshot (Link)

https://pastebin.com/q2vCq6be

**Comment by balu100** [comment]
Can confirm happens to me as well

**Comment by Hekili** [comment]
It happens at the end of fights; I'll adjust it to check that there's energy to restore before it spends extra TT charges.
