### ISSUE TITLE
Assassination Rogue doesn't use shadowmeld in any condition

### ISSUE THREAD

**Issue by balu100** [Hekili/hekili#3658]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Assassination Rogue doesn't use shadowmeld in any condition

### How to Reproduce

Enable shadowmeld in the options
Join any group content or try it on training dummies (in a group)
No shadowmeld recommendation occurs

### Snapshot (Link)

n/a

**Comment by Hekili** [comment]
Ticket is incomplete and no snapshot was provided.
