### ISSUE TITLE
[REC] Balance Druid - cast regrowth when not in combat

### ISSUE THREAD

**Issue by fraerie** [Hekili/hekili#3659]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As a Balance druid - the spell priority including full queue when out of combat only shows Regrowth.

### How to Reproduce

Enter game on balance druid
Not be in combat

### Snapshot (Link)

https://pastebin.com/Ad3Ac4LS

### Additional Information

using version Hekili-v11.0.2-1.0.7a on retail

### Contact Information

Felinae - discord ID

**Comment by Hekili** [comment]
Yeah, I'll limit that to only show if there is no Regrowth active.  It's a Keeper of the Grove thing, I guess.

**Comment by syrifgit** [comment]
Snapshot from discord user lucas69420: https://pastebin.com/n8FVknjd

Issue still happening

**Comment by derekslenk** [comment]
I can also confirm this is happening to me, withe the 9/4 updates

**Comment by Hekili** [comment]
This should be less impactful since 1.0.9 or 1.0.10.
