### ISSUE TITLE
GS being suggested when i have winters chill on target when i expect icelance to be suggested

### ISSUE THREAD

**Issue by Scarecroe** [Hekili/hekili#3660]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Glacial spike is being recommended when i have winterchill on target during Icy veins and not durning icy veins It should be ice lance

### How to Reproduce

I just followed what was recommended to frost mage

### Snapshot (Link)

https://pastebin.com/Dg3yEX87

### Contact Information

Scarecroe#9002

**Comment by GitBearded** [comment]
GS = Glacial Spike

**Comment by Hekili** [comment]
Can you provide a Raidbots link to a sim of your character?  It needs to be a Patchwerk sim with 3 boss targets to be comparable here.

I suspect that there's an error in the sim priority in the first `cleave` entry for `ice_lance`:
> `actions.cleave+=/ice_lance,target_if=max:debuff.winters_chill.stack,if=talent.glacial_spike&debuff.winters_chill.`**`down`**`&buff.icicles.react=4&buff.fingers_of_frost.react`

The targeting criteria -- seeking the enemy with the most Winter's Chill stacks -- while the `if` conditions requiring Winter's Chill be down, would seem to be contradictory.  I need to see the sim behavior to compare.

**Comment by Scarecroe** [comment]
Quick Sim - Croe - 1,350,213 DPS - Raidbotsraidbots.comHere you go!On Sep 4, 2024, at 10:32 PM, Hekili ***@***.***> wrote:﻿
Can you provide a Raidbots link to a sim of your character?  It needs to be a Patchwerk sim with 3 boss targets to be comparable here.
I suspect that there's an error in the sim priority in the first cleave entry for ice_lance:

actions.cleave+=/ice_lance,target_if=max:debuff.winters_chill.stack,if=talent.glacial_spike&debuff.winters_chill.down&buff.icicles.react=4&buff.fingers_of_frost.react

The targeting criteria -- seeking the enemy with the most Winter's Chill stacks -- while the if conditions requiring Winter's Chill be down, would seem to be contradictory.  I need to see the sim behavior to compare.

**Comment by syrifgit** [comment]
> Quick Sim - Croe - 1,350,213 DPS - Raidbotsraidbots.comHere you go!On Sep 4, 2024, at 10:32 PM, Hekili ***@***.***> wrote:﻿ Can you provide a Raidbots link to a sim of your character? It needs to be a Patchwerk sim with 3 boss targets to be comparable here. I suspect that there's an error in the sim priority in the first cleave entry for ice_lance: actions.cleave+=/ice_lance,target_if=max:debuff.winters_chill.stack,if=talent.glacial_spike&debuff.winters_chill.down&buff.icicles.react=4&buff.fingers_of_frost.react The targeting criteria -- seeking the enemy with the most Winter's Chill stacks -- while the if conditions requiring Winter's Chill be down, would seem to be contradictory. I need to see the sim behavior to compare. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

That is not a link to a sim. Please provide the URL.

**Comment by syrifgit** [comment]
Here is a sim I generated: https://www.raidbots.com/simbot/report/91Ac9KY4LHEUWBPyYXhLvd

**Comment by Scarecroe** [comment]
Quick Sim - Croe - 1,350,213 DPS - Raidbotsraidbots.comhttps://www.raidbots.com/simbot/report/7fiWv5BEBXLNagmSjUXiKH Sent from my iPhoneOn Sep 8, 2024, at 2:10 AM, syrifgit ***@***.***> wrote:﻿
Here is a sim I generated: https://www.raidbots.com/simbot/report/91Ac9KY4LHEUWBPyYXhLvd

**Comment by Hekili** [comment]
This behavior matches your sim:

![image](https://github.com/user-attachments/assets/cbb58ccd-8245-42bf-9d1b-5a2db9b7ee40)

With your build, the Ice Lance (`H`) that is higher in priority than Glacial Spike (`I` and `M`) is ruled out specifically because Winter's Chill is active.

This allows the Glacial Spike entry to pass and be recommended.

**Comment by Scarecroe** [comment]
Thank you for looking at it and explaining I appreciate it and you guys!Sent from my iPhoneOn Sep 8, 2024, at 9:02 PM, Hekili ***@***.***> wrote:﻿
This behavior matches your sim:
image.png (view on web)
With your build, the Ice Lance (H) that is higher in priority than Glacial Spike (I and M) is ruled out specifically because Winter's Chill is active.
This allows the Glacial Spike entry to pass and be recommended.
