### ISSUE TITLE
[FEATURE] Hero talent abilities are not showing up in abilities tab

### ISSUE THREAD

**Issue by umaru-kitsune** [Hekili/hekili#3661]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

On the abilities tab of the addon, I want to turn off recommendation for certain abilities but certain abilities in the new hero talents are not included in the list of abilities. 

Example 1: "Chrono Flames" (which replaces Living Flames for augmentation evokers for Chronowarden hero talent tree) is not included (and thus I cannot disable it). 

Example 2:  "Summon Charhound" - replaces Summon Vilefiend for warlocks in Diabolist hero talent tree

**Comment by Hekili** [comment]
Spell replacements are controlled by their original spell entry.
