### ISSUE TITLE
Assassination Rogue doesn't use shadowmeld in any condition

### ISSUE THREAD

**Issue by balu100** [Hekili/hekili#3662]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Assassination Rogue doesn't use shadowmeld in any condition

### How to Reproduce

Enable shadowmeld in the options
Join any group content or try it on training dummies (in a group)
No shadowmeld recommendation occurs

### Snapshot (Link)

https://pastebin.com/0ZHhDx0N

**Comment by chevyn11** [comment]
can you add a raidbots quick sim of your character where shadowmeld is used?

**Comment by balu100** [comment]
As far as i know shadowmeld isn't in the APL but it should be used when vanish is not available.
![EX](https://github.com/user-attachments/assets/35551ef4-607c-4fd0-8e04-177e8ac19f46)

**Comment by Sedveth** [comment]
if it's not on APL then it won't be on hekili, you just use it whenever you can and it's unreliable anyway, sometimes it works sometimes it's not

**Comment by balu100** [comment]
Modified the end of simc apl so it includes shadowmeld as an alternative for vanish but hekili still doesn't recommends 
```
# Stealth Cooldowns   Vanish Sync for Improved Garrote with Deathmark
actions.vanish+=/pool_resource,for_next=1,extra_amount=45
# Vanish to fish for Fateful Ending if possible
actions.vanish+=/vanish,if=!buff.fatebound_lucky_coin.up&(buff.fatebound_coin_tails.stack>=5|buff.fatebound_coin_heads.stack>=5)
actions.vanish+=/shadowmeld,if=!buff.fatebound_lucky_coin.up&(buff.fatebound_coin_tails.stack>=5|buff.fatebound_coin_heads.stack>=5)
# Vanish to spread Garrote during Deathmark without Indiscriminate Carnage
actions.vanish+=/vanish,if=!talent.master_assassin&!talent.indiscriminate_carnage&talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&(debuff.deathmark.up|cooldown.deathmark.remains<4)&combo_points.deficit>=(spell_targets.fan_of_knives>?4)
actions.vanish+=/shadowmeld,if=!talent.master_assassin&!talent.indiscriminate_carnage&talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&(debuff.deathmark.up|cooldown.deathmark.remains<4)&combo_points.deficit>=(spell_targets.fan_of_knives>?4)
actions.vanish+=/pool_resource,for_next=1,extra_amount=45
# Vanish for cleaving Garrotes with Indiscriminate Carnage
actions.vanish+=/vanish,if=!talent.master_assassin&talent.indiscriminate_carnage&talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&spell_targets.fan_of_knives>2
actions.vanish+=/shadowmeld,if=!talent.master_assassin&talent.indiscriminate_carnage&talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&spell_targets.fan_of_knives>2
# Vanish for Master Assassin during Kingsbane
actions.vanish+=/vanish,if=talent.master_assassin&talent.kingsbane&dot.kingsbane.remains<=3&dot.kingsbane.ticking&debuff.deathmark.remains<=3&dot.deathmark.ticking
actions.vanish+=/shadowmeld,if=talent.master_assassin&talent.kingsbane&dot.kingsbane.remains<=3&dot.kingsbane.ticking&debuff.deathmark.remains<=3&dot.deathmark.ticking
actions.vanish+=/vanish,if=!talent.master_assassin&talent.indiscriminate_carnage&talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&spell_targets.fan_of_knives>2&(target.time_to_die-remains>15|raid_event.adds.in>20)
actions.vanish+=/shadowmeld,if=!talent.master_assassin&talent.indiscriminate_carnage&talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&spell_targets.fan_of_knives>2&(target.time_to_die-remains>15|raid_event.adds.in>20)
# Vanish fallback for Master Assassin
actions.vanish+=/vanish,if=!talent.improved_garrote&talent.master_assassin&!dot.rupture.refreshable&dot.garrote.remains>3&debuff.deathmark.up&(debuff.shiv.up|debuff.deathmark.remains<4)
actions.vanish+=/shadowmeld,if=!talent.improved_garrote&talent.master_assassin&!dot.rupture.refreshable&dot.garrote.remains>3&debuff.deathmark.up&(debuff.shiv.up|debuff.deathmark.remains<4)
# Vanish fallback for Improved Garrote during Deathmark if no add waves are expected
actions.vanish+=/vanish,if=talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&(debuff.deathmark.up|cooldown.deathmark.remains<4)&raid_event.adds.in>30
actions.vanish+=/shadowmeld,if=talent.improved_garrote&cooldown.garrote.up&(dot.garrote.pmultiplier<=1|dot.garrote.refreshable)&(debuff.deathmark.up|cooldown.deathmark.remains<4)&raid_event.adds.in>30
```

**Comment by chevyn11** [comment]
> I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

But in any case, I dont think it should be used. Shadowmeld is not the equivalent of vanish. It doesnt grant subterfuge. It might be a gain if you can use it to get out of combat (so not during boss fights) and hit real stealth and therefore gain subterfuge.. but even that is incredibly finicky.

If you can convince the rogue discord to add it to the apl properly by showing there's a gain to be had then hekili will follow suit.

**Comment by balu100** [comment]
I'm not sure if it's a good way that I have to convince an entire Discord server just to use this feature. I believe that if i toggle Hekili's dedicated button to enable this feature, along with a custom APL (as mentioned above), it should work as expected.
![Untitled](https://github.com/user-attachments/assets/ba7a75e9-4ea3-4a86-838a-9cda9b8b6657)

Just an end note: using stealth after shedomeld immediately is just a little bit slower than vanish by itself and it can help spread Garrote with Indiscriminate Carnage and Improved Garrote

**Comment by syrifgit** [comment]
You would need to provide a snapshot of Meld not working in order to know anything.

**Comment by balu100** [comment]
I've imported the vanish changes from my previous comment, enabled shadowmeld in the options and was in a group of 5.
No shadowmeld was recommended.
https://pastebin.com/DmqmPNqg
![image](https://github.com/user-attachments/assets/5bdcd0e5-d427-4806-87da-f5c1a9ec7b3e)
