### ISSUE TITLE
[REC] Destruction Warlock AoE recommending Immolate spam on same target

### ISSUE THREAD

**Issue by Twissle** [Hekili/hekili#3667]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Destruction Warlock AoE priority often recommends spamming Immolate on the same target that already has the debuff with over 20 seconds of duration remaining. This happens in dungeons and is replicable on the 5-target training dummies in Dornegal.

### How to Reproduce

1. Be a Destruction Warlock 2. Have Dual-display on 3. Perform rotation on target dummies as recommended. 4. Be baffled when your next 4 recommendations are Immolate without a recommended target swap (and yes, the setting for show target swaps is on)

### Snapshot (Link)

https://pastebin.com/FiG5kNiN

**Comment by Hekili** [comment]
Should be resolved in 1.0.8
