### ISSUE TITLE
[REC] Guardian Druid of the Claw core ability Ravage recommendation not working (buff.ravage not working)

### ISSUE THREAD

**Issue by baaron666** [Hekili/hekili#3670]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Guardian Druid of the Claw core ability Ravage (replacing Maul when buff is up) is not being recommended as configured because buff.ravage is not tracking the buff 441602 properly. Currently it is only recommended when/as Maul is recommended without buff.ravage.up condition.

### How to Reproduce

1. Talent into Killing Strikes as Guardian Druid of the Claw hero talent for guaranteed Ravage proc (so easier testing)
2. Find at least 2 targets (e.g. cleave dummies) because Ravage with at least 2 targets is on top of the default bear APL (again for easier testing)
3. Thrash (to aggro all targets) and then Mangle to guarantee proc Ravage buff
4. Observe that Maul/Ravage is not the top recommendation because buff.ravage.up condition appears as False

### Snapshot (Link)

https://pastebin.com/3kg2LFqN

**Comment by johnnylam88** [comment]
To help with fixes, the spells for the Ravage buff are separate for Guardian and Feral specs:

* Guardian: https://www.wowhead.com/spell=441602/ravage)
* Feral: https://www.wowhead.com/spell=441585/ravage]

The spells that are replacements for Maul and Ferocious Bite are:

* Ravage/Maul: https://www.wowhead.com/spell=441605/ravage
* Ravage/FB: https://www.wowhead.com/spell=441591/ravage

**Comment by Hekili** [comment]
Fix in 1.0.9
