### ISSUE TITLE
[BUG] Hunter - only Markmanship specialization shows rotation

### ISSUE THREAD

**Issue by pel7zi** [Hekili/hekili#3671]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I'm not seeing any rotation for Beast Mastery or Survival specialization for Hunter. Tested on level 63 orc hunter and on level 71 earthen hunter. Only by selecting Markmanship specialization I can see hekili rotation icons on my screen.

### How to Reproduce

1. Login to game as a hunter
2. Select Beast Mastery or Survival specialization
3. See that no rotation is shown to you
4. Change specialization to Markmanship and see that the addon does work but only with this specialization

### Player Information (Link)

I can't create a snapshot

### Error Messages (Link)

no errors on bugsack

**Comment by syrifgit** [comment]
Make sure they are enabled. Why can't you create a snapshot? What happens when you press the keybind?

**Comment by pel7zi** [comment]
If I would know why I can't create snapshop I probably would do something differently so that I could make one. Pressing snapshot keybind doesn't do anything. Also tried to change the keybind and nothing happens. Pausing hekili with a keybind seems to work.

**Comment by syrifgit** [comment]
When you pause it, does it give you a snapshot in the menu? What message does it print in chat? Are the packs enabled?

![image](https://github.com/user-attachments/assets/ccb26415-71b2-4ae3-ae66-98307c947cd6)

**Comment by pel7zi** [comment]
Ok the problem was indeed that only the Markmanship core was enabled.
Taking snapshot doesn't still do anything regardless if the hekili is paused or not. And no messages in chat. But thank you @syrifgit for your help!
