### ISSUE TITLE
when using voidraith talent from the voidweaver heroic tree,  void eruption doesnt pop up.

### ISSUE THREAD

**Issue by comproh** [Hekili/hekili#3672]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

when using voidraith talent from the voidweaver heroic tree,  void eruption doesnt pop up.

### How to Reproduce

I used this talent profile
CIQAJSbRac/22NxZbHdYKOQzcAYmHYAAAAAAAAAAAAAGmlxYmZ2mtxMzMzy8AzsMY2YmZmxsxAjxwsY2mamBLwYmBzsYZqZzgZb2WyYmNWA

then just do ST dps on an ST dummy.

### Snapshot (Link)

https://pastebin.com/Pv9h6X3f

### Contact Information

pie.are.squared

**Comment by syrifgit** [comment]
You are already in voidform (from void eruption) in this snapshot?

**Comment by comproh** [comment]
yes i clicked it because it didnt show it.

**Comment by syrifgit** [comment]
Can you submit a new snapshot where you didn't manually press it? That way we can see the logic of why it is/isn't chosen.

Take it when it should tell you to press, but isn't.

**Comment by comproh** [comment]
https://pastebin.com/TKD9iCC1

**Comment by comproh** [comment]
I figured out why its because of the mindbender talent. If  i have it on it does that but if i dont have the mindbender talent in the shadow talent tree it doesnt do that

**Comment by Hekili** [comment]
I think it's not detecting that your Fiend is active.  May be an issue with Voidwraith.

It would help if you can run this macro when Voidwraith is active and provide the output here:

`/run for i = 1,5 do print(GetTotemInfo(i)) end`

**Comment by syrifgit** [comment]
> I think it's not detecting that your Fiend is active. May be an issue with Voidwraith.
> 
> It would help if you can run this macro when Voidwraith is active and provide the output here:
> 
> `/run for i = 1,5 do print(GetTotemInfo(i)) end`

![image](https://github.com/user-attachments/assets/1efbce4c-2cac-4f36-a44c-e9e350176330)


```
spec:RegisterTotem( "mindbender", 136214 )
spec:RegisterTotem( "shadowfiend", 136199 )
```

add a wraith totem?

**Comment by comproh** [comment]
https://i.imgur.com/bKP8TGY.jpeg

**Comment by Hekili** [comment]
This should now be resolved; please reopen/comment if not working.
