### ISSUE TITLE
[REC] Assasination Rogue - Auto snapshot 

### ISSUE THREAD

**Issue by Floapy** [Hekili/hekili#3673]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

No clue it auto-snapshotted so im assuming im just gonna report this issue lol

### How to Reproduce

no clue was in a bossfight

### Snapshot (Link)

https://pastebin.com/Y5WxRg1V

### Contact Information

Floapy

**Comment by Hekili** [comment]
This occurred because, at 6 combo points, the addon didn't want to Envenom with Darkest Night, but also didn't want to Mutilate and overcap combo points.  I am adjusting the priority to account for this scenario.
