### ISSUE TITLE
[REC] AOE rotation not suggesting Whirlwind

### ISSUE THREAD

**Issue by FrostmoonTheMage** [Hekili/hekili#3676]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When i engage with an aoe pack, with the aoe display to show. it never suggests me to use whirlwind and it even lets me just auto attack to get enough rage or to wait for something to come off CD, instead of using whirlwind.

### How to Reproduce

1. Engage with more than 1 mob

### Snapshot (Link)

https://pastebin.com/2KEeQmHR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fzWMj3i6hXZL1hytfPiYEt

### Additional Information

I reset my profile in game before submitting this ticket.

**Comment by johnnylam88** [comment]
I've tested this on a level 80 Fury Warrior and found no problems. Your issue is likely due to being level 64.

**Comment by syrifgit** [comment]
The addon is designed for max level, it won't use whirlwind because it wants to use thunderclap instead, but since you have no hero talents it is not giving you the AoE buff.
