### ISSUE TITLE
No spenders inside fel devastation 

### ISSUE THREAD

**Issue by Supersuperg** [Hekili/hekili#3681]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Inside fel devastation meta, spirit burst/bomb and soul cleave/sunder are not recommended 

### How to Reproduce

Fel dev

### Snapshot (Link)

https://pastebin.com/VG86NvNE

**Comment by syrifgit** [comment]
Closing as this ticket is 4-5 addon versions ago.
