### ISSUE TITLE
[REC] Fury Warrior - Multi Target Rotation Issues

### ISSUE THREAD

**Issue by Mosborne90** [Hekili/hekili#3682]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I discovered two potential issues:

1. In a multi target scenario with Titan's torment talented, the fury warrior rotation is recommending to use rampage after recklessness+avatar burst. I believe this is incorrect since titan's torment grants the enrage buff. The rotation should move straight into bladestorm. The snapshot showing this behavior is linked below.

2. A separate issue is the multi target rotation is choosing to refresh the whirlwind buff, even with stacks of the buff remaining over the use of crushing blow when available. Additional testing showed that whirlwind was sometimes recommended over other spells besides crushing blow, even if the player had whirlwind stacks remaining. that snapshot can be found here: https://pastebin.com/LL4B3Dwi 

### How to Reproduce

Charge into multi target dummies - pop reck/avatar burst, rampage will appear next instead of bladestorm which should then be followed by odyn's fury.

Whirlwind issue - unsure how to reproduce.

### Snapshot (Link)

https://pastebin.com/A3GdspY1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/d8ASqRF7npS69SaqrCgMnL

**Comment by syrifgit** [comment]
> In a multi target scenario with Titan's torment talented, the fury warrior rotation is recommending to use rampage after recklessness+avatar burst. I believe this is incorrect since titan's torment grants the enrage buff. The rotation should move straight into bladestorm. The snapshot showing this behavior is linked below.

Yet the sim you linked does exactly this, so it is correct.

![image](https://github.com/user-attachments/assets/8508fcaf-1b97-448d-9862-4d23d8add0cb)



> A separate issue is the multi target rotation is choosing to refresh the whirlwind buff, even with stacks of the buff remaining over the use of crushing blow when available. Additional testing showed that whirlwind was sometimes recommended over other spells besides crushing blow, even if the player had whirlwind stacks remaining. that snapshot can be found here: https://pastebin.com/LL4B3Dwi

I believe I know what is causing this. In the SIMC github, the buff of whirlwind attacks is called meat_cleaver, but in hekili it's called improved_whirlwind still. So when it checks for meat_cleaver, it thinks you have 0. Will get this fixed (eventually).

**Comment by Mosborne90** [comment]
@syrifgit Thanks for checking that. I'll be sure to look at the sim next time before a priority recommendation. Glad to know the whirlwind issue is a valid problem though.

**Comment by syrifgit** [comment]
> @syrifgit Thanks for checking that. I'll be sure to look at the sim next time before a priority recommendation. Glad to know the whirlwind issue is a valid problem though.

Interestingly, I couldn't replicate the issue with whirlwind. Can you do a fresh install and APL reset and try to reproduce it again?

![image](https://github.com/user-attachments/assets/014bda20-e052-4c18-b225-f0a347f3d6bb)

**Comment by Mosborne90** [comment]
@syrifgit I tested it again after a fresh install and profile reset. I'm able to replicate the bug this way. 

1. have whirlwind stacks before bladestorm
2. the bug will not occur if you have odyn's fury ready to use. Bladestorm will be followed by odyn's fury which skips the recommendation for whirlwind.
3. after bladestorm ends, whirlwind is recommended even if you have whirlwind buff stacks remaining.


https://pastebin.com/vBb2Vy1V 

vid: https://streamable.com/ths3b8




![image](https://github.com/user-attachments/assets/706e6285-f422-45eb-97a2-408fc1589194)
