### ISSUE TITLE
[REC] Outlaw Rogue crackshot windows

### ISSUE THREAD

**Issue by Dicce-wow** [Hekili/hekili#3684]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

This problem occurs often and while it's subtle sometimes you can be unlucky with combo points and miss out on an entire crack shot window and lose adrenaline rush for over a minute+.

Worst case: I'm hitting a single dummy a few minutes in, I have Adrenaline Rush on cd (1minute left) but the buff is active for 10 seconds, I have both vanishes on cd but I have 1 vanish coming up in 3 seconds.. so usually you would dispatch to get vanish back and then vanish and go into your crackshot window and reapply AR right? well the addon recommends I DONT dispatch and that I Between the Eyes and delay my vanish crack shot window, and now I get unlucky with sinister strikes not hitting additional times for extra combo points and before you know it I've lost AR because I'm spending time getting unlucky with SS, I'm energy starved and AR is still on CD and now i'm feeling like an assassination rogue, this happens in different sorts of ways but it occurs often and I'm having to ignore the addon to avoid such situations.

The addon really likes to recommend you between the eyes instead of dispatch when vanish has less then 30 seconds of cd left and your AR will not line up the way you'd like it to.

in screenshot 1 is what I explained above had happened, I hit BTE as it says and I lose AR because I'm unlucky and energy starved using SS to dispatch.

![outlaw1](https://github.com/user-attachments/assets/db078c3f-e328-40d3-be98-ac418a225165)

in screenshot 2 again the same thing, I hit BTE and I'll lose AR buff and have to play catch up for over a minute and energy starve myself in the process since AR has over 2 minutes CD in that screenshot.
![outlaw2](https://github.com/user-attachments/assets/b66b7e10-6647-4fac-9157-e8fec59bcadb)

![outlaw3](https://github.com/user-attachments/assets/156169e2-b9b4-4d44-91d9-cbfb76ccd1aa)
in screenshot 3 is not so bad, but still I would disagree to BTE instead of dispatching to get vanish back, this is where it's okay because I have plenty of time on AR left.

![outlaw4](https://github.com/user-attachments/assets/7b679376-62c4-47a8-8450-7205d9c6bbb3)
in screenshot 4 is how I explained in the description, If i hit BTE like it recommends I'll lose AR and I could get really unlucky on combo points. I should just need to dispatch and then go right into the crackshot window again.

### How to Reproduce

very finnicky to describe how to recreate since outlaw has so much cooldown reduction with finishing moves, best way would be to use both vanishes and AR off the rip and do standard rotation, keep an eye on BTE and vanish timings with AR is best way sorry I can't help explain it any better. 

### Snapshot (Link)

https://pastebin.com/E3SXDGye

### Additional Information

I also feel like pistol shot could be utilized better and roll the bone timings could be improved, i'm using a WA instead, but honestly the addon is great for when I wanna be lazy and pump, thanks for the awesome work on this addon! 

I am happy to discord and screenshare the videos I have recorded, I don't use github.

### Contact Information

Dicce

**Comment by Sedveth** [comment]
Bro, it's new rule with double vanish.
![image](https://github.com/user-attachments/assets/4553203c-d022-4594-99e2-2ddc08c28cc8)
Hekili is doing a correct rotation here.
I'm not sure how you couldn't get BTE back before AR expired for 12s even with unlucky SS, theory crafting people calculated it and you should have enough time even with your bad luck

**Comment by Dicce-wow** [comment]
Well i've logged back on to recreate what I was experiencing every 2-3minutes and 30minutes later I can't get it to happen once.. I'm not sure wtf has happened but seems like I've wasted a lot of my time instead of just relogging
