### ISSUE TITLE
[REC] ENHANCE SHAMAN [AOE] Flame shock filler is on, even if the checkbox is checked off. Even if the target has Flame shock is applied already

### ISSUE THREAD

**Issue by Taeyong-Sung** [Hekili/hekili#3685]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Flame Shock [AOE] as Enhancement Shaman, even if the Flame Shock filler is off, it is still recommending to use in que even though the Flame Shock is already applied to the target. This happens when other mobs in the AOE is not affected by Flame Shock

### How to Reproduce

Apply Flame shock[AOE] to the enemy, and keep doing the rotations, find the Flame Shock is still applied onto the target, and is still recommending Flame Shock in que even if the filler for Flame Shock  is checked off. This happens when other mobs in the AOE is not affected by Flame Shock

### Snapshot (Link)

Enhancement; Primary - Lava Lash(0.00), Flame Shock(1.27), Lava Lash(2.54)

### Contact Information

chamsae__

**Comment by Hekili** [comment]
You'll need to provide the complete snapshot. It should be thousands of lines and linked from Pastebin.

**Comment by Taeyong-Sung** [comment]
https://pastebin.com/zbiETHaA

**Comment by Taeyong-Sung** [comment]
Sorry, first time posting. Does that work?

**Comment by syrifgit** [comment]
Below is why the addon chose Flame Shock, for the exact reason you explained. Other mobs are missing the debuff. You need to multidot your flame shock, and it is likely getting stuck because you have target swapping off.

```
 - this entry's criteria PASSES: ( talent.fire_nova.enabled[true] | talent.primordial_wave.enabled[true] ) & ( active_dot.flame_shock[1.00] < active_enemies[5.00] ) & active_dot.flame_shock[1.00] < 6
 ```

**Comment by Taeyong-Sung** [comment]
How can I remove that feature? if the pulled mob size are 5++ even though I have Flame Shock applied on max 5 targets, it still puts Flame Shock in que. I would like to take that feature off if my target is already applied with Flame Shock. Is there a way to do so?

**Comment by syrifgit** [comment]
> How can I remove that feature? if the pulled mob size are 5++ even though I have Flame Shock applied on max 5 targets, it still puts Flame Shock in que. I would like to take that feature off if my target is already applied with Flame Shock. Is there a way to do so?

The Sims want you to put flame shock on 6 targets. So if there are 6 and you only have it on 5, it will want you to do 1 more.

Ideally you just need to multidot more. Try turning target swap on and see if that helps

![image](https://github.com/user-attachments/assets/383f0541-475e-4487-b60e-284a9ff1b8b0)

**Comment by Hekili** [comment]
I'll make adjustments for this.
