### ISSUE TITLE
[REC] The trinket I have has a 'use' ability. The trinket never shows in the priority

### ISSUE THREAD

**Issue by bpeterson69** [Hekili/hekili#3686]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I have a trinket on my Beast Master hunter named "Quickwick Candlestick" which has the following use stat:

Use: Hunter be nimble, Hunter be quick. Hunter invoke the power of the candlestick to increase movement speed by 20% and Haste by 5212 for 20 sec. (2 Min Cooldown)

 and it never shows in the priority list. I checked in "Gear and Items" and it isn't even in the list. I'm not sure if I'm missing something obvious or if it needs to be added.

I also have the "Signet of the Priory". It shows in the priory during play and it is in the "Gear and Items" list.

### How to Reproduce

Not sure how to answer this. Have the trinket and see that it isn't in the "Gear and Items" list and that in never shows in the priority.

### Snapshot (Link)

https://pastebin.com/UydCG06M

**Comment by syrifgit** [comment]
Trinkets are not fully implemented yet, this is known. Macro it to call of the wild.
