### ISSUE TITLE
Veangeance DH - Unable to make recommendatoin for Primary #2 

### ISSUE THREAD

**Issue by gordling** [Hekili/hekili#3688]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Was in the middle of a dungeon when the addon broke. It's no longer populating the upcoming spell queue in the rotation. Not sure how or what i did. I logged into my night elf DH it was working perfect. The bug is associated with the character. Wiped the saved variables for that toon, Reset the profiles, wiped and reinstalled the addon. Nothing seems to be fixing it.

### How to Reproduce

1. Enter game on specified Demon Hunter
2. Cast Spell on Hekili order
3. No other spells populate in the rotation queue.

### Player Information (Link)

https://pastebin.com/TnNwvmdn

### Error Messages (Link)

Unable to make recommendatoin for Primary #2 

### Contact Information

223700435079266304 Discord ID

**Comment by Lorenos** [comment]
same issue here, latest version installed and it shows a spell from time to time

any updates on this issue?

**Comment by bnjdpn** [comment]
> same issue here, latest version installed and it shows a spell from time to time
> 
> any updates on this issue?

Worked well but since v11.0.2-1.0.10b it’s broken…

**Comment by Uncleswim** [comment]
is there any update for this? @

**Comment by Arahkni** [comment]
I'm having the same issue. It was working 3 hours ago and now its only recommending Immolation Aura and Infernal Strike.  

Snapshot: https://pastebin.com/rWVS0HhC

**Comment by Dracconiac** [comment]
Same problem here. Worked just fine yesterday. I tried to reset the profile but didn´t help. 

Snapshot: https://pastebin.com/prwbxpuC
