### ISSUE TITLE
Survival hunter explosive shot

### ISSUE THREAD

**Issue by Ruler124** [Hekili/hekili#3689]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

"When I deactivate Coordinated Assault, Explosive Shot is not used in AoE, only in single target. As soon as I activate cooldowns, specifically Coordinated Assault, it gets included in the normal rotation."

### How to Reproduce

enter the game with survival hunter deactivate Coordinated Assault and fight without cds aoe dummys

### Snapshot (Link)

fff

**Comment by syrifgit** [comment]
Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by Ruler124** [comment]
https://pastebin.com/sy74wD94

**Comment by syrifgit** [comment]
This is not an AoE scenario. You are 20-25 yards from all your enemies and thus it is not counting them since you are melee.

Take the snapshot when you are in-combat with multiple enemies, and it is not recommending explo.

**Comment by Ruler124** [comment]
i stand in front of 5 dummys but here is a snapshot from dungeon

**Comment by Ruler124** [comment]
https://pastebin.com/cbXdP1YS

**Comment by Ruler124** [comment]
when i go away from the mobs than explosiveshot will come in my rota but directly in front its not coming only when i use cd

**Comment by syrifgit** [comment]
This issue is because you are disabling coordinated assault and playing the 2 minute CA talent. 
In AoE, you need to cast Coordinated Assault before casting explosive shot, and there is a condition that CA cooldown can't be higher than 80 seconds.

I will look into whether this needs to be changed, I hadn't noticed it myself because I always play with the 1 minute talent.

**Comment by Ruler124** [comment]
When you're running M+, you often have to hold onto your cooldowns, and if Explosive Shot isn't in the rotation, it's not great.

**Comment by syrifgit** [comment]
Yes I know, but you are also not running the recommended m+ build either. the aoe sim APL wasn't necessarily crafted for the 2 minute CA talent by the TCs because you aren't supposed to take that talent. But like I said, I will look into whether it should be changed for the addon.
