### ISSUE TITLE
Fire Mage Trinkets

### ISSUE THREAD

**Issue by Sdw8** [Hekili/hekili#369]
After using Azshara's Font of Power trinket, I need to wait for the cooldown Corrupted Aspirant's Badge and only after that use Combustion and burst rotation.

**Comment by Hekili** [comment]
Fill out the ticket properly, thanks.

**Comment by Sdw8** [comment]
Sorry, but I do not know much English, so it’s hard for me to fill out the ticket properly.

**Comment by Hekili** [comment]
Both Azshara's Font of Power and Corrupted Aspirant's Badge should be accounted for in the priority.  If you're not seeing that, you'd need to complete a ticket with the details required by the ticket instructions.
