### ISSUE TITLE
Explosive shot wrong in priorities

### ISSUE THREAD

**Issue by bitmatt2** [Hekili/hekili#3690]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

explosive shot should come before trueshot, salvo, and volley when shown in the cooldowns window

### How to Reproduce

just have everything offf cd

### Snapshot (Link)

https://pastebin.com/CNaGuTv0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bdL8A2RFvKvDRDj9ms4S53

### Contact Information

bitmatt2@gmail.com

**Comment by syrifgit** [comment]
Please provide a "quicksim" instead of a top gear, as the quicksim will show a sample rotation based on simulation crafts script for us to compare with.

Additionally your snapshot is wrong, it should be hundreds of lines. See auto-reply below for instructions.

---

Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by GitBearded** [comment]
Pretty sure this is only true in an AoE scenario.

**Comment by GitBearded** [comment]
https://www.raidbots.com/simbot/report/jxHjaQyokAobfxLFhLVUBk I ran the quick sim for him. Single target.

**Comment by GitBearded** [comment]
https://www.raidbots.com/simbot/report/eJ8EjjV2sxS3FGkxPf4dsW Here is aoe where explosive shot becomes higher in the prio

**Comment by syrifgit** [comment]
Still need a snapshot of the actual issue @bitmatt2

**Comment by bitmatt2** [comment]
Ok. I must have messed up with the snapshot. Ill work on getting you one
tomorrow. Its definately more crucial on aoe because u want the next two
GCDs after volley to be either aimed shot or rapid fire as thing benifit
from the automatic trick shots that volley gives you. On single shot i
would still use it before trueshot just to not have to use it while
trueshot is active. Icy veins aggrees

**Comment by bitmatt2** [comment]
i have updated my issue report with a quicksim and the correct snapshot

**Comment by bitmatt2** [comment]
also, when i put explosive shot in the AOE and primary rotation. the addon
is correct for primary but wrong in AOE. it does not tell me to use
explosive shot while trueshot is active but it will tell me to use it
during volley. here is a snapshot of me hitting the AOE training dummies:
https://pastebin.com/w5btMFaS

**Comment by Hekili** [comment]
This may be resolved in 1.0,10.

**Comment by bitmatt2** [comment]
Ok ty
