### ISSUE TITLE
fury warrior not recommending stormbolt during bladestorm

### ISSUE THREAD

**Issue by deedz1** [Hekili/hekili#3692]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

fury warrior not recommending stormbolt during bladestorm

maybe the bladestorm buff ID's in the lua are incorrect - it doesn't seem to detect the bladestorm buff

### How to Reproduce

bladestorm and it wont recommend stormbolt

### Snapshot (Link)

N/A

### Additional Information

na

### Contact Information

na

**Comment by syrifgit** [comment]
Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot 

Additionally, please provide a proper quicksim.

**Comment by deedz1** [comment]
actions.slayer_mt+=/storm_bolt,if=buff.bladestorm.up
actions.slayer_st+=/storm_bolt,if=buff.bladestorm.up

I even swapped these to the top of the action list incase it was an order issue

The rotation has it coded, im letting you know it doesnt work. in the time it takes to do all that i'll just go into the LUA and edit the bladestorm buff ID myself

**Comment by syrifgit** [comment]
> actions.slayer_mt+=/storm_bolt,if=buff.bladestorm.up actions.slayer_st+=/storm_bolt,if=buff.bladestorm.up
> 
> I even swapped these to the top of the action list incase it was an order issue
> 
> The rotation has it coded, im letting you know it doesnt work. in the time it takes to do all that i'll just go into the LUA and edit the bladestorm buff ID myself

Please provide what I have asked for, it only takes about 30 seconds.

**Comment by deedz1** [comment]
Hello, this is still not fixed as of the current release
