### ISSUE TITLE
[REC] Holy Paladin - recommends Word of Glory when Eternal Flame is talented

### ISSUE THREAD

**Issue by whi-tw** [Hekili/hekili#3693]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I've taken Eternal Flame (Herald of the Sun Hero talent tree). This replaces Word of Glory.

Hekili still recommends Word of Glory (and therefore does not have the keybind listed correctly)

### How to Reproduce

1. be a Hpal
2. Select Eternal Flame hero talent
3. Do some combat
4. notice that Word of Glory is recommended, rather than Eternal Flame

### Snapshot (Link)

https://pastebin.com/gMaAXK6U

**Comment by Luunae** [comment]
This is reoccurring now.

Snapshot: https://pastebin.com/82ts5mF9
