### ISSUE TITLE
Starfall - AP Cost with 'Soul of the Forest' talent

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#37]
Hello,

Maybe it's intended, but it's not in the Simc APL for Balance Druid but currently Starfall is only coming up to be cast when you have 50+ Astral Power when you have this talent that reduces it's cost down to 40 AP.

I think the issue is because of the line in DruidBalance.lua

`spend = function () return buff.oneths_overconfidence.up and 0 or 50 end,`

There is no check for the talent and the buff it checks for is of course for last expansion. I assume with this line it will only ever return 50 in most cases because there is no check for the talent.

Talent Spell Info here: https://www.wowhead.com/spell=114107/soul-of-the-forest

Thanks.

**Comment by Hekili** [comment]
Fix is incoming; thanks for the very detailed report.
