### ISSUE TITLE
Shadow Priest, Mind Sear Channeling cut short

### ISSUE THREAD

**Issue by xxLasherxx** [Hekili/hekili#370]
Rotation for Shadow priest calls for Mind Sear, but does not allow the channel to end before calling for it again, or before calling for another spell. Seems that it should have a CD dial on it as it channels until the channel is finished?  At any rate, if followed its a huge dps and resource loss.

++++  SNIP  ++++
build: v8.3.0-04-22.04
level: 120 (120)
class: PRIEST
spec: shadow

talents: auspicious_spirits
    body_and_soul
    legacy_of_the_void
    lingering_insanity
    misery
    psychic_horror
    shadow_word_void

azerite: azerite_empowered = 3
    chorus_of_insanity = 1
    death_throes = 1
    earthlink = 2
    heed_my_call = 1
    impassive_visage = 1
    longstrider = 2
    searing_dialogue = 2
    spiteful_apparitions = 1
    thought_harvester = 1

essences: [essence_of_the_focusing_iris] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 3, the_crucible_of_flame = 1

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    breeches_of_faithful_execution = 1
    conch_of_dark_whispers = 1
    drustthatched_wristwraps = 1
    heart_of_azeroth = 1
    hyperthread_boots = 1
    logic_loop_of_maintenance = 1
    loop_of_pulsing_veins = 1
    neural_synapse_enhancer = 1
    renowned_guild_tabard = 1
    vessel_of_skittering_shadows = 1
    vile_manipulators_amice = 1
    vile_manipulators_cord = 1
    vile_manipulators_cowl = 1
    vile_manipulators_handguards = 1
    vile_manipulators_vestment = 1
    wound_dressing = 1

corruptions: deadly_momentum = 3

itemIDs: 158075, 159282, 159463, 159610, 159620, 168964, 168973, 169076, 169223, 173433, 173507, 173812, 173844, 173846, 174237, 44693, 69210

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Shadow
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

+++ END SNIP +++++

**Comment by Hekili** [comment]
Please fill out issue tickets accurately and completely.  You'll need to post a snapshot when the addon recommends interrupting Mind Sear and you believe it shouldn't.

Looking briefly at the Shadow priority, it appears that there are low priority entries for Mind Sear that are interruptible and higher priority entries that aren't intended to be interrupted.  I'll probably need to investigate that a bit, but would appreciate the complete information requested in the ticket instructions to help it along.  Thanks.

**Comment by Hekili** [comment]
Channeling has been revised for Shadowlands and should address chain channeling and the like.  If not, a new ticket is needed.
