### ISSUE TITLE
Outlaw Adjustments for Between the Eyes bugs.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#3701]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

As mentioned in the Rogue Discord, Between the Eyes is currently bugged which impacts the outlaw gameplay.
![image](https://github.com/user-attachments/assets/fffcd1f5-d3db-47c3-b7ef-79bfde1eb9f8)

There is a pattern of behaviour which helps to avoid this bug:
![image](https://github.com/user-attachments/assets/7145c1c5-4947-42ca-bcca-c8d28b79197a)

I would like to ask implementing again "Crackshot lock" via setting and also add setting to avoid casting BtE from the basic "Stealth".

### Contact Information

IIeTpoc#3818 discord ID

**Comment by sneakerh3ad** [comment]
+ this bug is so annoying, fix it please

**Comment by syrifgit** [comment]
Changes have been made as per comments on PR
