### ISSUE TITLE
[REC] (Havoc) Issue is still persisting in most recent update. 

### ISSUE THREAD

**Issue by bsdgaming** [Hekili/hekili#3703]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Same thing as Ticket #3696 , but it was closed for some reason... 

Same issues, Fel-Blade never being recommended when low and fury and a charge is available. Also Meta is still funky.( shows up for a split second before disappearing)

### How to Reproduce

Do rotation as Havoc DH

### Snapshot (Link)

https://pastebin.com/TZDHFcYv

**Comment by aohajin** [comment]
same here,  Fel-Blade seems to be the main problem, action.felblade.cooldown_react is always false

https://pastebin.com/JMcgEqea

**Comment by Hekili** [comment]
This will be fixed in 1.0.10c
