### ISSUE TITLE
[REC] Diabolist buffed demonology spells do not clear after their cast (the cast consumes the buff)

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3707]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Buffed hand of guldan and shadow bolt (ruination and infernal bolt) are recommended repeatedly despite the buff being removed when casted.

The pastebin is for infernal bolt but the same behaviour is present with ruination.

I have included a screenshot of all the relevant buffs. TLDR on the mechanic: Spending a soul shard or summoning tyrant grants diabolic ritual. Consuming a soul shard reduces the demonic ritual buff by 1 second. When the diabolic ritual expires it gives one of the 3 demonic arts. Two of the demonic arts then grant ruination and infernal bolt, pit lord and mother of chaos respectively. 

https://i.imgur.com/OtDh0Rs.png
https://i.imgur.com/uhT84ah.png
https://i.imgur.com/BZ2pAJe.png
https://i.imgur.com/vhvU61A.png
https://i.imgur.com/vhyXkeI.png
https://i.imgur.com/gS1tV8S.png
https://i.imgur.com/dp2Z8Xu.png

### How to Reproduce

Play diabolist
Get 2nd and 3rd proc and observe.

### Snapshot (Link)

https://pastebin.com/31EuQwFZ

**Comment by dubudevs** [comment]
Also I'll add some more info in case its useful:

Infernal bolt generates 3 soul shards
Ruination costs no shards and generates no wild imps

**Comment by Hekili** [comment]
Fixing in 1.0.12
