### ISSUE TITLE
rotation icons are invisible sometimes

### ISSUE THREAD

**Issue by mamatag2g** [Hekili/hekili#3709]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

the skill box on the screen, at the beginning of the rotation you can see only one or two skills, after which it disappears, then it appears again quickly with the rotation. icon shown, 3 are selected, but I see only 1 or 2 on the screen, at the beginning of the rotation, they disappear and appear in an unpleasant way.

### How to Reproduce

1. on Vengance demonhunter 

### Player Information (Link)

no time for thet sry

### Error Messages (Link)

no time for that sry

**Comment by Dushkhov** [comment]
same problem here !

**Comment by syrifgit** [comment]
If you don't have time for a snapshot, we don't have time to look into it.?

If you'd like it looked at, please open a ticket with a snapshot as per the instructions.
