### ISSUE TITLE
Assassination rogue/ Vanish not showing up as a cooldown to use during dps rotation

### ISSUE THREAD

**Issue by Garborogue** [Hekili/hekili#371]
I have checked and redownloaded the addon to make sure it wasnt a customization i did prior to submitting ticket. when i first downloaded the addon Vanish would come up as an ability to use in my rotation and i knew this is an ability we use to apply garrote which it will increase its damage drastically, but now its not showing up anymore, so im wondering if there is a way to fix that?

i tried adding it to the list of cooldowns because it wasnt there. then i went to abilities and used the default setting, scrolled down to vanish and it showed default(none). 

Trying to figure out how to make it come back into my rotation, help please?

build: v8.3.0-06
level: 120 (120)
class: ROGUE
spec: assassination

talents: cheat_death
    elaborate_planning
    poison_bomb
    prey_on_the_weak
    subterfuge
    toxic_blade
    vigor

azerite: azerite_empowered = 3
    gutripper = 1
    heart_of_darkness = 3
    lying_in_wait = 2
    overwhelming_power = 2
    shrouded_mantle = 1
    shrouded_suffocation = 3

essences: [breath_of_the_dying] = 3, essence_of_the_focusing_iris = 3, memory_of_lucid_dreams = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    corpuscular_leather_greaves = 1
    deadeye_spyglass = 1
    gibbering_maw = 1
    heart_of_azeroth = 1
    jollys_boot_dagger = 1
    lurking_schemers_band = 1
    mad_kings_sporran = 1
    onyximbued_breeches = 1
    renowned_guild_tabard = 1
    seal_of_the_city_watch = 1
    servoarm_bindings = 1
    shard_of_the_black_empire = 1
    spaulders_of_aberrant_allure = 1
    tortured_fleshbeast_cuirass = 1
    vitacharged_titanshard = 1
    wharf_wardens_gloves = 1

corruptions: twisted_appendage = 3

itemIDs: 158075, 158353, 159132, 159328, 159623, 162542, 168986, 169223, 172227, 174134, 174135, 174136, 174139, 174144, 174500, 175008, 69210

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Assassination
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    envenom_pool_pct = 50
    mfd_waste = true
    priority_rotation = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = single
    potions = false

**Comment by Hekili** [comment]
Follow the ticket instructions.

Vanish is not recommended when you're soloing or fighting dummies.  (It'd reset enemies.)

Adding Vanish to the Cooldowns toggle makes a bit of sense, but doesn't do what you think it does.  By doing that, you're ensuring that Vanish won't be recommended with CDs disabled.  It doesn't mean that the other criteria from the priority is ignored.

Get a snapshot, per the ticket instructions, when you think Vanish should be recommended but it wasn't.

**Comment by Hekili** [comment]
Any plan to submit a snapshot, or should I close this?  Thanks.
