### ISSUE TITLE
TWW Trinkets are not in the Hekili Gear and Items database list. 

### ISSUE THREAD

**Issue by fubash** [Hekili/hekili#3710]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

TWW Trinkets are not in the Hekili Gear and Items database list and therefore not in the rotation.

### How to Reproduce

enter game with addon enabled and equip any on-use trinket specifically from TWW (The War Within).

### Snapshot (Link)

https://pastebin.com/X7QA8wqF

**Comment by syrifgit** [comment]
We know
