### ISSUE TITLE
[VENG DH] Primary bar not functioning well after updates issued today 09/09/2024

### ISSUE THREAD

**Issue by Sapphire3279** [Hekili/hekili#3712]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After the updates released today 09/09/2024 - The primary bar has spells being disappeared occassionally.w

When I revert to the version released on 06/09/2024, it works well. I have my bar set to display 3 upcoming recommended spells, and sometimes, one dissappear or all 3 altogether.

### How to Reproduce

1. Attack
2. Primary recommendations spells disappear at times.

### Snapshot (Link)

https://pastebin.com/U8KicR0A

**Comment by Hekili** [comment]
There is something wrong with your install; many of the entries in your `fs` action list are "not set or not enabled."

Can you go to /hekili > Priorities > Vengeance, and click the little circle arrow ![image](https://github.com/user-attachments/assets/c15c5699-052b-43ba-aeb8-13de9efbe45e) to reload the Vengeance priority?

![image](https://github.com/user-attachments/assets/3534aa45-14c7-4189-a5c6-ab15598fcce0)
