### ISSUE TITLE
[Havoc] [REC] sigil of flame and immolation aura wrongly suggested

### ISSUE THREAD

**Issue by Zifrost** [Hekili/hekili#3713]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Fel Scarred Havoc DH as u left the opener, u should keep Immo Aura and Sigil of Flame for the next mini burst. Until then u should cast only Chaos Strike, Annihilation, Blade Dance, Death Sweep and Felblade.
The Miniburst consist in: 
-Immolation Aura to get Unbound Chaos
-Sigil of Flame to get Student of Suffering buff from Hero talent 
-Vengeful retreat
-Eyebeam
-FelRush 
-Essence Break
-Death Sweep
-Annihilation
and another death sweep when we get tier set if it procs.
In the opener it should be:
-Immolation 2sec before fight start
-Sigil 1sec before fight start
-The Hunt + pots and trinket
-FelBlade
-Eyebeam
-FelRush
-Death Sweep to consume first Demonsurge
-Annihilation to consume second Demonsurge
-Vengeful Retreat
-Meta
-Death Sweep to consume first Demonsurge
-Annihilation to consume second Demonsurge
-Immolation consume third Demonsurge
-Sigil  consume 4th Demonsurge
-Eyebeam  consume 5th Demonsurge
-FelRush
-Essence Break
-Death Sweep
-Annihilation
and another death sweep when we get tier set if it procs.
Beside those burst windows, as mentioned above, u should only use Chaos Strike, Annihilation, Blade Dance, Death Sweep and Felblade.

### How to Reproduce

Just follow the suggested spell

### Snapshot (Link)

https://pastebin.com/TZMiuXdF

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3DAyUorEX8kUsYf2pRiM23

### Additional Information

Sim is using the first part of the opener kinda wrong cause if u watch Jedith/VooDoo video the follow the opener I told u

### Contact Information

Zifrost

**Comment by Zifrost** [comment]
Forgot to mention that inbetween bursts u can use Vengeful Retreat as it has 20sec cd and Essence Break has 40sec

**Comment by Jacky7533** [comment]
yeah it's not reconmending the correct opener. espeically it's specifically stating to use Sigil of Flame and then Immolation. Also Upon going into your first meta, it suggests you to use Fel Rush after Annihilation, but you shouldn't be using that during that time, since it should be Consuming Fire > Sigil of Doom > Abyssal Gaze then to Fel Rush. And then do Essence Break > Death Sweep > Annihilation until Essence Break debuff drops. 

https://pastebin.com/wSiHvNxn

**Comment by Hekili** [comment]
> yeah it's not reconmending the correct opener. espeically it's specifically stating to use Sigil of Flame and then Immolation.

The sim is very clearly written to use Sigil of Flame followed by Immolation Aura before starting combat.  If that is not correct and interferes with an opener, the SimulationCraft priority will need to be updated accordingly.

**Comment by Jacky7533** [comment]
> > yeah it's not reconmending the correct opener. espeically it's specifically stating to use Sigil of Flame and then Immolation.
> 
> The sim is very clearly written to use Sigil of Flame followed by Immolation Aura before starting combat. If that is not correct and interferes with an opener, the SimulationCraft priority will need to be updated accordingly.

because the first Immolation and Sigil is pre-pull. and I don't know if SimC does pre-pull. you'd Immolate 2sec in pull timer, and Sigil at 1sec. and then you do the hunt, and then felblade. that's the standard for all guides thus far from the looks of it.

EDIT: so SimC does do pre-pull but it seems that, it does everything at 0:00:00 second. but for actual player logic, you'd want to yeah, do Immo at 2sec pulltimer and Sigil at 1 pulltimer.

**Comment by YoelWardaGitHub** [comment]
![{853A8703-26CA-4D04-B917-68CDE45BA950}](https://github.com/user-attachments/assets/63024798-33ce-42ea-8a48-34186c4f4b8d)
now I'm seeing this with the latest update. recommendation for pull should be immolation aura -> sigil of flame -> hunt -> fel blade -> eye beam

talents I was using:
CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzYMzMjZmJmZGAAAAAAwsMmhBGLzMz2sNLjZGmZBLbwysYGDzmmGMzMzgN

**Comment by Jacky7533** [comment]
> ![{853A8703-26CA-4D04-B917-68CDE45BA950}](https://private-user-images.githubusercontent.com/11379737/367414952-63024798-33ce-42ea-8a48-34186c4f4b8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTc0NjEsIm5iZiI6MTcyNjI1NzE2MSwicGF0aCI6Ii8xMTM3OTczNy8zNjc0MTQ5NTItNjMwMjQ3OTgtMzNjZS00MmVhLThhNDgtMzQxODZjNGY0YjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE5NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkY2NiNjM3NGM4ZjE5YjIyZDkzZTBiODk4ZWJlNWEwMDkyZTEzZjNkNGI1ZmRlZjM0OTQzNWZlZWQ3OWMwMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DNoZ8mMcwgNKvFKoas8vRxj_mjSYP7IOfvwGgp0PlOA) now I'm seeing this with the latest update. recommendation for pull should be immolation aura -> sigil of flame -> hunt -> fel blade -> eye beam
> 
> talents I was using: CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzYMzMjZmJmZGAAAAAAwsMmhBGLzMz2sNLjZGmZBLbwysYGDzmmGMzMzgN

Yup can confirm. The opener is not how it is written in all the guides.

this is the snapshot
https://pastebin.com/Ly8nkkJe

this is my talents
CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzgZmZMzMhZGAAAAAAwsNMmZMGLzMz2sNLjZGmZBLbwysYGDzmmGMzMGsB

this is my simC
https://pastebin.com/0mXHdqJX

**Comment by syrifgit** [comment]
This ticket is now many versions old, please contribute to newer DH tickets.
