### ISSUE TITLE
Sunfury Arcane Missiles being recommended after surge.

### ISSUE THREAD

**Issue by GitBearded** [Hekili/hekili#3714]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

During the opener, missiles is being recommended RIGHT after surge is cast and then takes priority over other casts as soon as Clearcasting procs. 

### How to Reproduce

Do the rotation.

### Snapshot (Link)

https://pastebin.com/UMcPD4bR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8EpFXGDeKgKnngA1iiD9mu

### Additional Information

This snapshot is taken RIGHT after surge is cast.

### Contact Information

colossal1

**Comment by Zifrost** [comment]
its good like this, raidbot is not built to use targeted spell in precast. U can watch Preheat video from like 2 days ago and he explain how to do opener and why bot is "wrong" at the very start of the fight

**Comment by Zifrost** [comment]
> and then takes priority over other casts as soon as Clearcasting procs.

this is because u always have to play around Nether Precision proc'd by missiles.
Arcane has been looked for last couple of days and fixed kinda perfectly

**Comment by GitBearded** [comment]
> > and then takes priority over other casts as soon as Clearcasting procs.
> 
> this is because u always have to play around Nether Precision proc'd by missiles. Arcane has been looked for last couple of days and fixed kinda perfectly

This actually is not correct, you DO NOT use missiles with every single clear cast proc. The way it is right now it’s wasting nether precision making you only arcane blast once between missiles. You should ALWAYS use up your nether precision stacks (with blast and or barrage) BEFORE casting another missiles. The exception is 3 stacks of Clearcasting so you don’t overcap.

**Comment by GitBearded** [comment]
22:01 in the video you’re referencing LITERALLY says the opener is ALWAYS evo missiles surge touch blast blast missiles.

**Comment by GitBearded** [comment]
The ONLY time you would missiles AFTER surge is if you DID NOT missiles after evo.

**Comment by Hekili** [comment]
Fix incoming.
