### ISSUE TITLE
Aug Evoker isnt recommending any cds or empowered spells.

### ISSUE THREAD

**Issue by GitBearded** [Hekili/hekili#3715]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Title. 

### How to Reproduce

Log in on an evoker, look at recommended abilities on hekili. 

### Snapshot (Link)

https://pastebin.com/zMkJqjV0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/mHxNf67X6cb7LGCkqQTV5q

### Contact Information

colossal1

**Comment by syrifgit** [comment]
Please test the newest update, .10d

**Comment by hsramm** [comment]
I came here to report the same issue but looks like it recommends them now but I just ran a normal Dawnbreaker and it stopped telling me to use Prescience completely. The entire 3rd and 4th boss didn't pop up once. Really strange...

**Comment by GitBearded** [comment]
> Please test the newest update, .10d

Will test after work.

**Comment by Hekili** [comment]
Closing; submit a new ticket with a snapshot once 1.0.12 is live.
