### ISSUE TITLE
[SURVIVAL] Tranquilizing shot Not working for enemy players 

### ISSUE THREAD

**Issue by Verz3** [Hekili/hekili#3716]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For Hunter - I am expecting the addon to use Tranquilizing shot against enemy players when there is magic or enrage debuff to remove. Below is the syntax: 

debuff.dispellable_magic.up or debuff.dispellable_enrage.up

### How to Reproduce

Enter game as hunter
duel or enter a random bg 
when you see a buff of magic that can be removed by Tranquilizing shot, addon should recommend it even if you place priority 1

### Snapshot (Link)

Survival; Primary - Serpent Sting(0.00) build: v4.4.0-0.9.5 level: 85 (85) class: HUNTER spec: hunter  talents: bestial_discipline     black_arrow     entrapment     essence_of_the_viper     explosive_shot     hunter_vs_wild     hunting_party     improved_serpent_sting     into_the_wilderness     lock_and_load     master_of_beasts     noxious_stings     one_with_nature     point_of_no_escape     resourcefulness     spirit_bond     survival_tactics     thrill_of_the_hunt     tnt     toxicology     trap_mastery     wild_quiver     wyvern_sting  pvptalents: none  covenant: none  conduits: none  soulbinds: none  sets: none  gear: brown_linen_shirt = 1     mainhand = 1     mainhand_2h = 1     vicious_gladiators_badge_of_conquest = 1     vicious_gladiators_cape_of_cruelty = 1     vicious_gladiators_chain_armor = 1     vicious_gladiators_chain_gauntlets = 1     vicious_gladiators_chain_helm = 1     vicious_gladiators_chain_leggings = 1     vicious_gladiators_chain_spaulders = 1     vicious_gladiators_insignia_of_conquest = 1     vicious_gladiators_links_of_accuracy = 1     vicious_gladiators_longbow = 1     vicious_gladiators_necklace_of_prowess = 1     vicious_gladiators_pike = 1     vicious_gladiators_ring_of_accuracy = 1     vicious_gladiators_ring_of_cruelty = 1     vicious_gladiators_sabatons_of_cruelty = 1     vicious_gladiators_wristguards_of_alacrity = 1  legendaries: none  itemIDs: 4344, 60423, 60424, 60425, 60426, 60427, 60554, 60559, 60564, 60658, 60659, 60668, 60783, 61033, 61047, 61340, 61353  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcd = 1494     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Survival     petbased = false     potion = speed     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     usePackSelector = true     arcane_threshold = 80     assigned_aspect = aspect_of_the_hawk     beast_mastery = Beast Mastery (Himea Beta))     call_of_the_wild_macro = false     maintain_aspect = true     marksmanship = Marksmanship (Himea Beta)     survival = Survival  toggles:     cooldowns = true      custom1 = false      custom2 = false      defensives = false      essences = true [overridden]     interrupts = false      mode = single      potions = false   keybinds:      arcane_shot        = 8   [01]     black_arrow        = F9  [05]     cobra_shot         = =   [01]     deterrence         = 2   [01]     explosive_shot     = F10 [05]     feign_death        = V   [06]     flare              = PgUp[05]     hunters_mark       = N-  [06]     ice_trap           = 9   [01], N8  [06]     kill_command       = 6   [01]     kill_shot          = 7   [01]     multishot          = 5   [01]     rapid_fire         = END [05]     raptor_strike      = -   [01]     scatter_shot       = N7  [06]     serpent_sting      = 4   [01]     snake_trap         = PgDn[06]     tranquilizing_shot = 1   [01]     widow_venom        = F6  [06]     wing_clip          = 0   [01]     wyvern_sting       = N3  [06]    player_buffs:     24529 - spirit_bond                              -   1 - 3600.00     13165 - aspect_of_the_hawk                       -   1 - 3600.00     85022 - *surge_of_conquest                       -   1 - 15.24       6673 - battle_shout                             -   1 - 138.08     49868 - *mind_quickening                         -   1 - 3600.00     51701 - *honor_among_thieves                     -   1 - 3600.00     19506 - trueshot_aura                            -   1 - 3600.00  player_debuffs:     46857 - trauma                                   -   1 - 7.96    target_auras:  target does not exist   New Recommendations for [ Primary ] requested at 22:11:00 ( 817819.96 ); using built-in ( Survival ) priority. *** START OF NEW DISPLAY: Primary ***  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: focus[ 50.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Survival - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   aspect_of_the_hawk ( precombat - 1 )         The action is not ready ( 3595.24 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Survival-precombat-1:aspect_of_the_hawk:0.03:Ability Known, Enabled(0.03)                  2.   aspect_of_the_fox ( precombat - 2 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.02ms         TimeData:Survival-precombat-2:aspect_of_the_fox:0.02:Ability Known, Enabled(0.02)                  3.   aspect_of_the_cheetah ( precombat - 3 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.01ms         TimeData:Survival-precombat-3:aspect_of_the_cheetah:0.01:Ability Known, Enabled(0.01)                  4.   aspect_of_the_pack ( precombat - 4 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.01ms         TimeData:Survival-precombat-4:aspect_of_the_pack:0.01:Ability Known, Enabled(0.01)                  5.   aspect_of_the_wild ( precombat - 5 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.01ms         TimeData:Survival-precombat-5:aspect_of_the_wild:0.01:Ability Known, Enabled(0.01)                  6.   hunters_mark ( precombat - 6 )         We are already in-combat and this pre-combat action is not essential.  Skipping.         Time spent on this action:  0.01ms         TimeData:Survival-precombat-6:hunters_mark:0.01:Ability Known, Enabled(0.01)                  Entry #7 in list ( precombat ) is not set or not enabled.  Skipping.          Completed precombat action list [ Survival - precombat ].          Processing default action list [ Survival - default ].                  Current recommendation was NO ACTION at +10.00s.                  7.   use_items ( default - 1 )         There is no criteria for Use Items.         + items         Current recommendation was NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items         Resetting delayMin to 0.00 from 0.00.                  8.   potion ( default - 2 ) - ability disabled ( toggle )         Time spent on this action:  0.02ms         TimeData:Survival-default-2:potion:0.02:Ability Known, Enabled(0.02)                  9.   hyperspeed_acceleration ( default - 3 ) - item [ 0 ] missing         Time spent on this action:  0.02ms         TimeData:Survival-default-3:hyperspeed_acceleration:0.02:Ability Known, Enabled(0.02)                  10.  run_action_list:aoe ( default - 4 )         Criteria for aoe FAIL at +0.00 - active_enemies[1.00] > 2                  11.  run_action_list:cleave ( default - 5 )         Criteria for cleave FAIL at +0.00 - active_enemies[1.00] = 2                  12.  run_action_list:single ( default - 6 )         There is no criteria for single.         Action list (single) was found.         + [single]         Current recommendation was NO ACTION at +10.00s.                  13.  tranquilizing_shot ( single - 1 )         The action (tranquilizing_shot) is unusable at (0.00 + 0.00) because required debuff (dispellable_magic) not active.         Time spent on this action:  0.10ms         TimeData:Survival-single-1:tranquilizing_shot:0.10:Ability Known, Enabled(0.02):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.04)                  14.  deterrence ( single - 2 ) - ability disabled ( toggle )         Time spent on this action:  0.02ms         TimeData:Survival-single-2:deterrence:0.02:Ability Known, Enabled(0.02)                  15.  raptor_strike ( single - 3 )         The action (raptor_strike) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( single ) called from ( Survival:default:6 ) would PASS at 0.00.         NONE          - this entry's criteria FAILS: target.within2[false]         There were no recheck events to check.         Time spent on this action:  0.09ms         TimeData:Survival-single-3:raptor_strike:0.09:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.00):Post Recheck(0.00)                  16.  wing_clip ( single - 4 )         The action (wing_clip) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( single ) called from ( Survival:default:6 ) would PASS at 0.00.         NONE          - this entry's criteria FAILS: target.within2[false]         There were no recheck events to check.         Time spent on this action:  0.08ms         TimeData:Survival-single-4:wing_clip:0.08:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.00):Post-Recheck Times(0.00):Post Recheck(0.00)                  17.  aspect_of_the_hawk ( single - 5 )         The action is not ready ( 3595.24 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Survival-single-5:aspect_of_the_hawk:0.01:Ability Known, Enabled(0.01)                  18.  rapid_fire ( single - 6 )         The action is not ready ( 163.22 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Survival-single-6:rapid_fire:0.01:Ability Known, Enabled(0.01)                  19.  serpent_sting ( single - 7 )         The action (serpent_sting) is usable at (0.00 + 0.00) with cost of 25 focus.          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( single ) called from ( Survival:default:6 ) would PASS at 0.00.         NONE          - this entry's criteria PASSES: debuff.serpent_sting.down[true] & ! prev_gcd.1.serpent_sting[false]         Action chosen:  serpent_sting at 0.00!         Returned from list (single), current recommendation is serpent_sting (+0.00).         - [single]         Added single to blocklist as it was called via RAL.          Completed default action list [ Survival - default ].     Recommendation is serpent_sting at 0.00 + 0.00.     Recommendation #1 is serpent_sting at 0.00s (0.00s).     Time spent generating recommendations:  1.29ms

### Additional Information

I have placed Tranquilizing shot as priority 1 to test against enemy players that have magic buff up and addon does not recommend

**Comment by syrifgit** [comment]
please get a properly formatted snapshot and put it in paste bin next time.

**Comment by Verz3** [comment]
I am sorry, this is my first time doing this

**Comment by syrifgit** [comment]
No snapshot provided that was readable
