### ISSUE TITLE
No clue whats going on but sometimes on opener Hekili makes me wait for an oblit before sindragosa breath

### ISSUE THREAD

**Issue by comproh** [Hekili/hekili#3720]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Sometimes the addon makes me wait for another oblit before sindragosa breath

### How to Reproduce

No clue how to reproduce it cuz sometimes it happens sometimes it doesnt.  just do the opener for dks ig?

### Snapshot (Link)

https://pastebin.com/y2LEab5G

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/4AB1GLxao1B1WQhsUZC3GH   Heres with DND, heres without https://www.raidbots.com/simbot/report/vp5GRjnGdkGYURzR7F9UFT

### Additional Information

reading the guides opener should abom> remorseless winter> reaper> oblit> howling if rime is up> dnd> breath of sindragosa

### Contact Information

pie.are.squared

**Comment by comproh** [comment]
Figured out why, opener should be  OBLIT first then HB, so that incase if rime procs OBLI you get a free rune that DND uses if not then just go with HB last and then sindragosa ..  with hekili it goes with HB then OBLIT for some reason.

**Comment by syrifgit** [comment]
Your snapshot is doing exactly what both of your sims do. Try and get a snapshot exactly when the issue is happening.

**Comment by comproh** [comment]
https://pastebin.com/6F5Hfmcs   new snapshot. its making me do this https://i.imgur.com/a8Qy5kq.jpeg

**Comment by comproh** [comment]
https://pastebin.com/t24q0HBf when following through the "waiting" for OBlit

**Comment by comproh** [comment]
Like I said, it does that when HB is done first then Oblit, but IF i oblit  first it follows the quicksim that i linked

**Comment by comproh** [comment]
https://pastebin.com/XsrfHN56  heres the OBLIT then HB  with DND because rime proc'd.

**Comment by comproh** [comment]
Also just noticed its recommending me soul reaper above 35% https://pastebin.com/FfWN1GqN

**Comment by Stoufs** [comment]
Frost DK seems broken now. It makes me wait up to 6 seconds sometimes to cast obliterate right in the opener too.

https://pastebin.com/1BufBdEv

**Comment by Hekili** [comment]
@comproh Your screenshot shows multiple seconds of waiting, but your snapshot only shows a fraction of a second.  I'm guessing those weren't actually taken at the same time.  Can you get a snapshot during the longer wait time you reported?

Also, which Raidbots sim matches your actual build that you're snapshotting.  I want to compare apples to apples.

**Comment by Hekili** [comment]
@Stoufs The snapshot you provided recommends Howling Blast in 0.28 seconds followed by Remorseless Winter at +4.98s.  Do you have one that shows a 6 second wait for Obliterate?

Also, you have abilities filtered by range, so Frost Strike wasn't allowed while you're out of range:
* `The action (frost_strike) is unusable at (0.28 + 1.35) because filtered out of range.`

I definitely don't recommend filtering abilities based on range, because priorities aren't written to come up with filler abilities that you don't really have as a Frost DK (i.e., it's not time to Howling Blast and you're not in melee... what else would you use?).  The **correct** recommendation is to tell you to Frost Strike (or Obliterate) and if you're not in range, *get in range*.

**Comment by comproh** [comment]
> @comproh Your screenshot shows multiple seconds of waiting, but your snapshot only shows a fraction of a second. I'm guessing those weren't actually taken at the same time. Can you get a snapshot during the longer wait time you reported?
> 
> Also, which Raidbots sim matches your actual build that you're snapshotting. I want to compare apples to apples.

Thats the thing I figured hekili tells me to obli right away, but ON The thing i screenshotted, I did that right after I snapshotted.  as you can see on the picture https://i.imgur.com/b8CeMBA.jpeg its already  more than 1/4 in the wait.  That is the longer wait time, the moment I see hekili telling me to wait to oblit I screenshotted it. 

also both the raidbot sims are the same build. The difference is with rime and the other without rime proc.  they are the same profile build. sindragosa talent profile build.

**Comment by Hekili** [comment]
Snapshot, not screenshot. I need the text.

**Comment by comproh** [comment]
https://pastebin.com/t24q0HBf  this is the snapshot of me waiting through the oblit and going forward after like doing what hekili is telling me.

**Comment by Hekili** [comment]
I don't want you to wait; I want you to snapshot when it shows the recommendation that is telling you to wait several seconds.

**Comment by comproh** [comment]
> I don't want you to wait; I want you to snapshot when it shows the recommendation that is telling you to wait several seconds.

thats the snapshot. of  hekili telling me to wait.

**Comment by comproh** [comment]
its hard to capture it, sometimes it happens sometimes it doesnt.  

here https://pastebin.com/jbFqEyZP is it again. and video recorded it. 
Im uploading the video. 

https://github.com/user-attachments/assets/604b4ea8-dffb-44d4-b288-b3acc4f0759a

**Comment by comproh** [comment]
Video quality is horrible i didnt know it would be like that but you can still see that it makes you wait. and you can see that it recommends HB first then OBLI thats why its making you wait

**Comment by Hekili** [comment]
This one shows the wait:

> [pastebin.com/jbFqEyZP](https://pastebin.com/jbFqEyZP)

In this case, it bypassed Breath of Sindragosa because your RP (42) was less than your BOS RP slider (60).

The Obliterate recommendation is offset by 4.57 seconds because you have 2 Runes and are currently `pooling_runes`:

```
        30.  variable ( variables - 10 )
        pooling_runes #1 [Frost DK:variables:10]; conditions = PASS: NONE
         - value = true: rune.current[2.00] < variable.oblit_rune_pooling[4.00] & talent.obliteration.enabled[true] & ( ! talent.breath_of_sindragosa.enabled[true] | variable.true_breath_cooldown[0.00] ) & cooldown.pillar_of_frost.remains_expected[0.00] < variable.oblit_pooling_time[3.00]
```

This variable looks erroneous to me, as `variable.true_breath_cooldown` of `0` should be treated as `false` -- if I make it through the queue and into the game, I'll check to see if there's an issue with the translation into Lua code.

**Comment by Hekili** [comment]
Fix incoming.

**Comment by comproh** [comment]
alright ima test it after raid :D
