### ISSUE TITLE
[REC] Augmentation Cooldown Usage

### ISSUE THREAD

**Issue by shonuff21** [Hekili/hekili#3725]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [ ] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

It seems cooldowns have switched around. Sometimes they come up and I am doing good dmg other times it seems like its mostly filler spells like flames 

### How to Reproduce

Pulling a pack of mobs in a M+ dungeon

### Snapshot (Link)

Augmentation; AOE - Blistering Scales(0.00), Living Flame(1.42), Prescience(3.31)

### Contact Information

fusilli2121

**Comment by Hekili** [comment]
Please resubmit with a complete snapshot (thousands of lines of text, on Pastebin) and a more complete description of the problem.  You'll want to take the snapshot when you disagree with the recommendation given.  For example, if you think Breath of Eons should be recommended (and is ready) but it isn't, that's a good time to take the snapshot.

**Comment by Mecze** [comment]
I dont know if it is the same error, but it is not recomending Prescience..
It did work several patches ago
here is the snapshot 

edited by @syrifgit: Please use Pastebin next time

https://pastebin.com/2A9503sH

**Comment by TerrySmith22** [comment]
I want to add into his when playing Augmentation, Hekili is not recommending interrupts, but interrupts are being recommended on other classes no issue.

**Comment by syrifgit** [comment]
> I want to add into his when playing Augmentation, Hekili is not recommending interrupts, but interrupts are being recommended on other classes no issue.

Open a new ticket and provide a snapshot. Don't add into an unrelated ticket.

**Comment by Hekili** [comment]
I'm putting in a testfix for the Prescience issue (there appear to be 8 Prescience auras active despite having no allies; they should now time out).

I'm closing the ticket because the "Augmentation Cooldown Usage" issue has no snapshot.  Feel free to open a new ticket with a snapshot if that issue persists.
