### ISSUE TITLE
[PROT WARRIOR] Hekili doesnt work - dont change icons in priorities

### ISSUE THREAD

**Issue by Mortygen** [Hekili/hekili#3731]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [ ] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Protection

### Describe the Issue

Hello,

During combat, hekili shows only Primary (I have 3 icons visible) so for Warrior I see only "Demoralizing shout", 2nd "Shield Charge" amd 3rd "Revenge", when I use any of this skills, icons do not change to new ones, sometimes I see CD timer on them, but mostly they are out of CD.

### How to Reproduce

Dont know, I just installed the newest version of hekili and this happened

### Snapshot (Link)

https://pastebin.com/dX7faCtU

**Comment by Mortygen** [comment]
OK. I also used this fix https://github.com/Hekili/hekili/commit/03c5acc934318d5cb930b001167d9324623bcf80
and it work.

**Comment by Mortygen** [comment]
So its not. after dungeon it again doesn't work, I see only CD on 3 icons and they won;t change to new ones from queue

**Comment by Hekili** [comment]
You should be posting the snapshot, then.  :)

**Comment by Hekili** [comment]
Fixed in 1.0.11b
