### ISSUE TITLE
SIN Rogue: Fatebound - 

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3732]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Raid, single target with Cleave, came up with mulitple errors and the addon disappeared mulitple times.

### How to Reproduce

It haappend on the 2nd boss on Normal, played fatebound, during the add phase, and switching to boss.

### Player Information (Link)

https://pastebin.com/DcftzrbB

### Error Messages (Link)

https://pastebin.com/DcftzrbB

### Contact Information

Wren1740

**Comment by Hekili** [comment]
Test fix in 1.0.11a.
