### ISSUE TITLE
Priority for new Enhancement hybrid storm spec request

### ISSUE THREAD

**Issue by e30Birdy** [Hekili/hekili#3735]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

There is a new Enhancement shaman hybrid storm spec and would love to see that priority in hekili if using the spec.

https://www.simulationcraft.org/reports/TWW1_Raid.html

### How to Reproduce

No issue here just a request

### Snapshot (Link)

N/a

### Raidbots Sim Report (Link)

https://www.simulationcraft.org/reports/TWW1_Raid.html

**Comment by syrifgit** [comment]
No changes are necessary, just load the talents. This new "profile" does not use a different simc APL.

![image](https://github.com/user-attachments/assets/5247ff8c-99ad-4951-abdb-add2ae1c3f5f)

**Comment by e30Birdy** [comment]
Ok, thanks just wanted to be sure! Thanks for all the support and wonderful addon.
