### ISSUE TITLE
Prot Warrior not Loading

### ISSUE THREAD

**Issue by mcdudenurse** [Hekili/hekili#3736]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Protection warrior is either not loading a rotation at all, or when it does it is not displaying new icons as you cast. 

### How to Reproduce

1. Enter game as protection warrior or change spec to protection warrior
2. Target enemy
3. Follow rotation

### Player Information (Link)

Protection Warrior; Primary - Skarmorak Shard(0.00), Avatar(0.00) build: v11.0.2-1.0.11a level: 80 (80) class: WARRIOR spec: protection  talents: CkEAmidFBOBFf5oKuZ7r/WeW7YEDAAAAzMzMmZGmZbmlZmZ2wYQjBjZAsMwwGzMjZYmZMDAAAAAAYmBAYZbDwwgttZMLLbjmZGmhtZpxGzG     anger_management = 1/1     armored_to_the_teeth = 2/2     avatar = 1/1     avatar_of_the_storm = 1/1     battle_stance = 1/1     best_served_cold = 1/1     bloodsurge = 1/1     booming_voice = 1/1     bounding_stride = 1/1     brace_for_impact = 1/1     brutal_vitality = 1/1     burst_of_power = 1/1     challenging_shout = 1/1     champions_bulwark = 1/1     champions_spear = 1/1     crackling_thunder = 1/1     crashing_thunder = 1/1     cruel_strikes = 2/2     crushing_force = 2/2     defensive_stance = 1/1     demoralizing_shout = 1/1     devastator = 1/1     double_time = 1/1     enduring_alacrity = 1/1     enduring_defenses = 1/1     flashing_skies = 1/1     focused_vigor = 1/1     frothing_berserker = 1/1     ground_current = 1/1     heroic_leap = 1/1     ignore_pain = 1/1     impending_victory = 1/1     impenetrable_wall = 1/1     indomitable = 1/1     intimidating_shout = 1/1     into_the_fray = 1/1     keep_your_feet_on_the_ground = 1/1     last_stand = 1/1     leeching_strikes = 1/1     lightning_strikes = 1/1     mountain_thane = 1/1     onehanded_weapon_specialization = 1/1     piercing_challenge = 1/1     punish = 1/1     rallying_cry = 1/1     ravager = 1/1     reinforced_plates = 1/1     rend = 1/1     revenge = 1/1     rumbling_earth = 1/1     seismic_reverberation = 1/1     shield_charge = 1/1     shield_specialization = 2/2     shield_wall = 1/1     shockwave = 1/1     sidearm = 1/1     spell_block = 1/1     spell_reflection = 1/1     storm_bolt = 1/1     storm_bolts = 1/1     strategist = 1/1     strength_of_the_mountain = 1/1     thorims_might = 1/1     thunder_blast = 1/1     thunder_clap = 1/1     thunderlord = 1/1     unstoppable_force = 1/1     violent_outburst = 1/1     war_machine = 1/1     wild_strikes = 2/2  pvptalents: none  covenant: none  conduits: none  soulbinds: [pelagos]  sets: skarmorak_shard = 1  gear: amice_of_hidden_stars = 1     chiseled_boulder_pauldrons = 1     dredgers_developed_gauntlets = 1     dredgers_plate_sabatons = 1     duelists_dancing_steel = 1     earthen_nullification_aegis = 1     malleable_band = 1     nether_bountys_greatbelt = 1     ravaged_lamplighters_manacles = 1     red_linen_shirt = 1     secretdredgers_helm = 1     shadowbinding_ritual_knife = 1     shield = 1     skarmorak_shard = 1     strapped_rescuekeg = 1     tabard_of_the_scarlet_crusade = 1     thunderclad_legguards = 1     warsculptors_furred_plastron = 1  legendaries: none  itemIDs: 211029, 211987, 212392, 212437, 215130, 215178, 219183, 219300, 221034, 221060, 221073, 222471, 222479, 223290, 225589, 23192, 2575  settings: aoe = 2     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxRefresh = 10     maxTime = 33     nameplateRange = 10     nameplates = true     noFeignedCooldown = false     package = Protection Warrior     petbased = false     potion = potion_of_spectral_strength     potionsReset = 20180919.1     rangeFilter = true     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     free_revenge = true     heroic_charge = false     last_stand_amount = 50     last_stand_condition = false     last_stand_health = 50     last_stand_offensively = false     overlap_ignore_pain = false     rallying_cry_amount = 50     rallying_cry_condition = false     rallying_cry_health = 50     reserve_rage = 35     shield_wall_amount = 50     shield_wall_condition = false     shield_wall_health = 50     shockwave_interrupt = true     stack_shield_block = false     stance_weaving = false  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = false [overridden]     funnel = false      interrupts = true      mode = automatic      potions = false   keybinds:      avatar             = TAB [01]     battle_shout       = F1  [03]     berserker_rage     = SE  [06]     challenging_shout  = CMwU[06]     champions_spear    = S4  [05]     demoralizing_shout = Q   [01]     execute            = `   [01]     hamstring          = SM2 [06]     healthstone        = SM1 [06]     heroic_leap        = SR  [06]     heroic_throw       = F   [05]     ignore_pain        = 2   [01]     impending_victory  = E   [06]     intimidating_shout = F2  [01]     last_stand         = T   [01]     pummel             = MwD [05]     rallying_cry       = 6   [01]     ravager            = C   [05]     revenge            = Z   [01]     shield_block       = 1   [01]     shield_charge      = CR  [06]     shield_slam        = 3   [01]     shield_wall        = SSPACE[05]     shockwave          = CMwD[05]     spare_meat_hook    = STAB[06]     spell_block        = SX  [01]     spell_reflection   = X   [06]     storm_bolt         = SMwD[06]     taunt              = MwU [05]     thunder_blast      = 4   [01]     thunder_clap       = 4   [01]     thunderous_roar    = V   [06]     will_to_survive    = SF  [05], TAB [07]  warnings: [#1] Returned unknown string 'hp' in state metatable [Protection Warrior:default:15]. [string "@Interface/AddOns/Hekili/State.lua"]:2390: in function <Interface/AddOns/Hekili/State.lua:2017> [string "@Interface/AddOns/Hekili/TheWarWithin/WarriorProtection.lua"]:1282: in function `usable' [string "@Interface/AddOns/Hekili/State.lua"]:7242: in function `IsUsable' [string "@Interface/AddOns/Hekili/Core.lua"]:950: in function `GetPredictionFromAPL' [string "@Interface/AddOns/Hekili/Core.lua"]:1414: in function `GetNextPrediction' [string "@Interface/AddOns/Hekili/Core.lua"]:1793: in function <Interface/AddOns/Hekili/Core.lua:1464>  [#2] Update: ...ace/AddOns/Hekili/TheWarWithin/WarriorProtection.lua:1282: attempt to compare nil with number [string "@Interface/AddOns/Hekili/TheWarWithin/WarriorProtection.lua"]:1282: in function `usable' [string "@Interface/AddOns/Hekili/State.lua"]:7242: in function `IsUsable' [string "@Interface/AddOns/Hekili/Core.lua"]:950: in function `GetPredictionFromAPL' [string "@Interface/AddOns/Hekili/Core.lua"]:1414: in function `GetNextPrediction' [string "@Interface/AddOns/Hekili/Core.lua"]:1793: in function <Interface/AddOns/Hekili/Core.lua:1464>  [#3] Returned unknown string 'hp' in state metatable [Protection Warrior:default:15]. [string "@Interface/AddOns/Hekili/State.lua"]:2390: in function <Interface/AddOns/Hekili/State.lua:2017> [string "@Interface/AddOns/Hekili/TheWarWithin/WarriorProtection.lua"]:1282: in function `usable' [string "@Interface/AddOns/Hekili/State.lua"]:7242: in function `IsUsable' [string "@Interface/AddOns/Hekili/Core.lua"]:950: in function `GetPredictionFromAPL' [string "@Interface/AddOns/Hekili/Core.lua"]:1414: in function `GetNextPrediction' [string "@Interface/AddOns/Hekili/Core.lua"]:1793: in function `Update' [string "@Interface/AddOns/Hekili/Options.lua"]:12107: in function `MakeSnapshot' [string "@Interface/AddOns/Hekili/Options.lua"]:12214: in function `FireToggle' [string "@Interface/AddOns/Hekili/UI.lua"]:2853: in function <Interface/AddOns/Hekili/UI.lua:2852>    targets:  Nameplates are enabled.  - Checking nameplate list for nameplate7 [ Creature-0-3780-2552-5877-219250-0000619E97 ] PvP Training Dummy.     - Excluded by range (45 > 10).  player_buffs:      6673 - battle_shout                             -   1 - 3214.67    386208 - defensive_stance                         -   1 - 3600.00    225788 - *sign_of_the_emissary                    -   1 - 3600.00    457666 - *dawnthread_lining                       -   1 - 3600.00    404464 - *flight_style_skyriding                  -   1 - 3600.00  player_debuffs:  target_auras:  target does not exist   New Recommendations for [ Primary ] requested at 11:17:58 ( 2611.12 ); using built-in ( Protection Warrior ) priority. *** START OF NEW DISPLAY: Primary *** Purged 308 marked values in 0.11ms.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: rage[ 0.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Protection Warrior - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   battle_stance ( precombat - 1 )         The action is not ready ( 3477.18 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Protection Warrior-precombat-1:battle_stance:0.03:Ability Known, Enabled(0.03)                  2.   battle_shout ( precombat - 2 )         The action is not ready ( 3214.67 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-precombat-2:battle_shout:0.02:Ability Known, Enabled(0.02)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Protection Warrior - precombat ].          Processing default action list [ Protection Warrior - default ].                  Current recommendation was NO ACTION at +10.00s.                  3.   pummel ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-1:pummel:0.02:Ability Known, Enabled(0.02)                  4.   charge ( default - 2 )         The action (charge) is unusable at (0.00 + 0.00) because target too close.         Time spent on this action:  0.12ms         TimeData:Protection Warrior-default-2:charge:0.12:Ability Known, Enabled(0.02):Post-TTR and Essential(0.09):Post Cycle(0.00):Post Usable(0.01)                  5.   use_items ( default - 3 )         There is no criteria for Use Items.         + items         Current recommendation was NO ACTION at +10.00s.                  6.   skarmorak_shard ( items - 1 )         The action (skarmorak_shard) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( items ) called from ( Protection Warrior:default:3 ) would PASS at 0.00.         NONE          - this entry's criteria PASSES: ( ! settings.boss[false] | boss[false] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )         Action chosen:  skarmorak_shard at 0.00!         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from Use Items; current recommendation is skarmorak_shard (+0.00).         - items         The recommended action (skarmorak_shard) is ready in less than 0.2s; exiting list (default).         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Protection Warrior - default ].     Recommendation is skarmorak_shard at 0.00 + 0.00.     Recommendation #1 is skarmorak_shard at 0.00s (0.00s).  RECOMMENDATION #2 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: rage[ 0.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Protection Warrior - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   battle_stance ( precombat - 1 )         The action is not ready ( 3477.18 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-precombat-1:battle_stance:0.02:Ability Known, Enabled(0.02)                  2.   battle_shout ( precombat - 2 )         The action is not ready ( 3214.67 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-precombat-2:battle_shout:0.02:Ability Known, Enabled(0.02)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Protection Warrior - precombat ].          Processing default action list [ Protection Warrior - default ].                  Current recommendation was NO ACTION at +10.00s.                  3.   pummel ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-1:pummel:0.02:Ability Known, Enabled(0.02)                  4.   charge ( default - 2 )         The action (charge) is unusable at (0.00 + 0.00) because target too close.         Time spent on this action:  0.04ms         TimeData:Protection Warrior-default-2:charge:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00)                  5.   use_items ( default - 3 )         There is no criteria for Use Items.         + items         Current recommendation was NO ACTION at +10.00s.                  6.   skarmorak_shard ( items - 1 )         The action is not ready ( 90.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.06ms         TimeData:UseItems-items-1:skarmorak_shard:0.06:Ability Known, Enabled(0.06)         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items                  7.   avatar ( default - 4 )         The action (avatar) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria PASSES: buff.thunder_blast.down[true] | buff.thunder_blast.stack[0.00] <= 2         Action chosen:  avatar at 0.00!         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Protection Warrior - default ].     Recommendation is avatar at 0.00 + 0.00.     Recommendation #2 is avatar at 0.00s (0.00s).  RECOMMENDATION #3 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: rage[ 10.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Protection Warrior - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   battle_stance ( precombat - 1 )         The action is not ready ( 3477.18 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-precombat-1:battle_stance:0.02:Ability Known, Enabled(0.02)                  2.   battle_shout ( precombat - 2 )         The action is not ready ( 3214.67 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-precombat-2:battle_shout:0.02:Ability Known, Enabled(0.02)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Protection Warrior - precombat ].          Processing default action list [ Protection Warrior - default ].                  Current recommendation was NO ACTION at +10.00s.                  3.   pummel ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-1:pummel:0.02:Ability Known, Enabled(0.02)                  4.   charge ( default - 2 )         The action (charge) is unusable at (0.00 + 0.00) because target too close.         Time spent on this action:  0.04ms         TimeData:Protection Warrior-default-2:charge:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00)                  5.   use_items ( default - 3 )         There is no criteria for Use Items.         + items         Current recommendation was NO ACTION at +10.00s.                  6.   skarmorak_shard ( items - 1 )         The action is not ready ( 90.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.06ms         TimeData:UseItems-items-1:skarmorak_shard:0.06:Ability Known, Enabled(0.06)         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items                  7.   avatar ( default - 4 )         The action is not ready ( 90.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-4:avatar:0.02:Ability Known, Enabled(0.02)                  8.   shield_wall ( default - 5 )         The action (shield_wall) is unusable at (0.00 + 0.00) because incoming_damage_5s[0.00] < dmg_required[1806780.50] setting.         Time spent on this action:  0.10ms         TimeData:Protection Warrior-default-5:shield_wall:0.10:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.03)                  9.   blood_fury ( default - 6 ) - ability unknown         Time spent on this action:  0.04ms         TimeData:Protection Warrior-default-6:blood_fury:0.04:Ability Known, Enabled(0.04)                  10.  berserking ( default - 7 ) - ability unknown         Time spent on this action:  0.03ms         TimeData:Protection Warrior-default-7:berserking:0.03:Ability Known, Enabled(0.03)                  11.  arcane_torrent ( default - 8 ) - ability unknown         Time spent on this action:  0.03ms         TimeData:Protection Warrior-default-8:arcane_torrent:0.03:Ability Known, Enabled(0.03)                  12.  lights_judgment ( default - 9 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-9:lights_judgment:0.02:Ability Known, Enabled(0.02)                  13.  fireblood ( default - 10 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-10:fireblood:0.02:Ability Known, Enabled(0.02)                  14.  ancestral_call ( default - 11 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-11:ancestral_call:0.02:Ability Known, Enabled(0.02)                  15.  bag_of_tricks ( default - 12 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-12:bag_of_tricks:0.02:Ability Known, Enabled(0.02)                  16.  potion ( default - 13 ) - ability disabled ( toggle potions )         Time spent on this action:  0.95ms         TimeData:Protection Warrior-default-13:potion:0.95:Ability Known, Enabled(0.95)                  17.  ignore_pain ( default - 14 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Protection Warrior-default-14:ignore_pain:0.02:Ability Known, Enabled(0.02)                  18.  last_stand ( default - 15 )         Recommendation thread terminated due to error: ...ace/AddOns/Hekili/TheWarWithin/WarriorProtection.lua:1282: attempt to compare nil with number                  [string "@Interface/AddOns/Hekili/TheWarWithin/WarriorProtection.lua"]:1282: in function `usable'         [string "@Interface/AddOns/Hekili/State.lua"]:7242: in function `IsUsable'         [string "@Interface/AddOns/Hekili/Core.lua"]:950: in function `GetPredictionFromAPL'         [string "@Interface/AddOns/Hekili/Core.lua"]:1414: in function `GetNextPrediction'         [string "@Interface/AddOns/Hekili/Core.lua"]:1793: in function <Interface/AddOns/Hekili/Core.lua:1464>         

### Error Messages (Link)

N/A

**Comment by syrifgit** [comment]
Update to the newest version.
