### ISSUE TITLE
[FEATURE] Cata PTR update

### ISSUE THREAD

**Issue by sneakerh3ad** [Hekili/hekili#3739]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Looks like currently Hekili is not working for Cata PTR, it is already exist in Curse Forge, but not working in the game (Hekili icon is not available at the minimap). Will it be available on PTR?

**Comment by Hekili** [comment]
This should be a bug report with all the requisite ticket information.
