### ISSUE TITLE
[Brew] Add-on stops providing recomendations

### ISSUE THREAD

**Issue by CivilYoshi** [Hekili/hekili#3740]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Brewmaster

### Describe the Issue

As brew, after I've been in combat for 20-30 seconds, my single target recommendations seem to stop generating. You'll see in the screenshot below how it appears to be suggesting Keg Smash despite having no available charges. (The add-on is treating it as if it's off CD and available) This doesn't appear to be exclusive to target dummy's, as I first encountered it fighting the world boss. 

https://gyazo.com/8d3f0a700ea6bb6b21bbd33929615d71

### How to Reproduce

1. Enter game on Brewmaster.
2. Head over to a Target dummy
3. Hit your buttons for 30-60 seconds, eventually you'll stop getting updated recommendations (with periodic and sporadic updates occasionally)

### Snapshot (Link)

https://pastebin.com/mkr3rEWY

### Contact Information

civilyoshi (discord)

**Comment by Hekili** [comment]
Fixed in 1.0.12
