### ISSUE TITLE
[REC] Trinket Missing - Imperfect Ascendancy Serum 

### ISSUE THREAD

**Issue by sudoalias** [Hekili/hekili#3741]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Arcane

### Describe the Issue

Gear/Item selection for Imperfect Ascendancy Serum does not exist and the trinket is also never recommended by Hekili.

### How to Reproduce

Equip Imperfect Ascendancy Serum trinket, monitor rotation.

### Snapshot (Link)

https://pastebin.com/GTE796j6

**Comment by cp172797** [comment]
same for quickwick candle

**Comment by syrifgit** [comment]
Trinkets have not been fully implemented yet, it's on a todo list
