### ISSUE TITLE
[BUG] Provide a short, clear title for your Bug Report

### ISSUE THREAD

**Issue by sikaros** [Hekili/hekili#3743]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [ ] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Assasination Rogue dps rotation becomes frozen or stuck after a few moments moments of following the rotation

### How to Reproduce

1. Enter game as assasination rogue 
2. start the dps rotation on a training dummy or enemy.
3. after a few moments the hekili UI becomes stuck or frozen on a spell 

### Player Information (Link)

https://pastebin.com/rHNXKbbs

### Error Messages (Link)

https://pastebin.com/rHNXKbbs

### Additional Information

the ui for hekili becomes stuck on a spell after following rotation a few clicks

**Comment by Bronski** [comment]
I'm also having trouble on Ass rogue with v11.0.2-1.0.12.

It was telling me to hit things that made no sense, like stealth while I was still in combat. Other keys weren't working either. I'm not sure if that's related or a different issue but FYI. I'm going to revert a version to ensure it was working previously.

**Comment by Hekili** [comment]
Fixed in 11.0.2-1.0.12a.
