### ISSUE TITLE
SIN Rogue:  Warning: UPDATE String recheck

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3744]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Logged in checked addon, had warning

### How to Reproduce

Enter game, opened addon, check warnings, warning was there

### Player Information (Link)

https://pastebin.com/mqdGWuDe

### Error Messages (Link)

https://pastebin.com/mqdGWuDe

### Contact Information

Wren1740

**Comment by Hekili** [comment]
Fixed in 11.0.2-1.0.12a.
