### ISSUE TITLE
[REC] Recommending dispatch in stealth when BTE is off cooldown

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3745]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

Recommending dispatch over BTE in stealth even when BTE is off cooldown

### How to Reproduce

1. enter game
2. go to dummies
3. do rotation until vanish is recommended
4. hit vanish, wait a few seconds until officially out of combat
5. it will switch from recommending BTE to recommending dispatch in stealth even when BTE is off cooldown

### Snapshot (Link)

https://pastebin.com/sSp2yBeR

**Comment by Hekili** [comment]
Yes, this is intentional because of a Blizzard bug where using BtE in actual stealth can result in BtE going on its full cooldown.

**Comment by diversifybonds** [comment]
Hi is there a toggle or fix for this, I use a macro that doesn't cast BTE unless I'm stealthed so it's not an issue and just a dps loss for me.
