### ISSUE TITLE
[FEATURE] Implement Sikran's Endless Arsenal

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3746]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

The trinket Sikran's Endless Arsenal is not implemented. 
https://www.wowhead.com/item=212449/sikrans-endless-arsenal

**Comment by Hekili** [comment]
Trinkets are on my to-do list.
