### ISSUE TITLE
Rogue - Recommending more than 2 poisons at once

### ISSUE THREAD

**Issue by Bronski** [Hekili/hekili#3747]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

I'm often getting more than 2 poison recommendations on my Assassination Rogue. Sometimes Amplifying Poison is involved, but not in this case.

### How to Reproduce

1. Be Ass Rogue
2. Use WowHead Ass Rogue Delve build: CMQAAAAAAAAAAAAAAAAAAAAAAMjZmZGmhZAAAAAAY2gtZAAAAAAottZmhZmxYmZWmlxYwMzMzgZmZbbZMDwmZZgBsEsMMBGWA
3. ???
4. Profit! 😁

### Snapshot (Link)

https://pastebin.com/VfY616zD

**Comment by chevyn11** [comment]
https://www.wowhead.com/spell=381801/dragon-tempered-blades
