### ISSUE TITLE
[REC] Treacherous Transmitter never being recommended in rotation.

### ISSUE THREAD

**Issue by e30Birdy** [Hekili/hekili#3749]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

So I just got this https://www.wowhead.com/item=221023/treacherous-transmitter last night and started using it and noticed that it does not get recommended in my rotation. Have noticed this behaviour with a few other newer trinkets. Usually the behavior I have seen in DF is that it usually recommends on pull, especially with most fights in new raid being Lust on pull.

### How to Reproduce

1. Enter game
2. Start rotation
3. Never get recommended to use trinket
4. Kill boss

### Snapshot (Link)

https://pastebin.com/ca282Mja

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/oXfWJnRrEiKf9Z1peZT5NJ/simc

### Additional Information

https://www.raidbots.com/simbot/report/6aVwaMP8ZSdWpSDi5tfsbi/simc this is a quicksim link and looking at it I should be using trinket on pull for sure at 0.964 seconds if I remember right.

**Comment by purefreakz** [comment]
same for me

**Comment by syrifgit** [comment]
Trinkets have not been finished yet
