### ISSUE TITLE
Mark Of Khardros missing from the priority! 

### ISSUE THREAD

**Issue by Bombo999** [Hekili/hekili#3750]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

Mark Of Khardros missing from the priority list its one of the best trinkets for frost dk and would appreciate it alot if it could be added

### How to Reproduce

I mean just enter the game and check its not on the list of items/trinkets

### Snapshot (Link)

I dont have snapshot

### Raidbots Sim Report (Link)

I mean theres no sim to this the trinket is just missing

### Contact Information

bombo999

**Comment by Hekili** [comment]
Trinkets are on my to-do list.
