### ISSUE TITLE
Totemic recall and liquid magma aren't working properly. 

### ISSUE THREAD

**Issue by JibbityTibbit** [Hekili/hekili#3751]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

Totemic recall never gets recommended when you use liquid magma totem during aoe and single target. also liquid magma totem does get recommended during aoe but not in ST 

### How to Reproduce

1. enter game as ele shaman 

3. use the m+ stormbringer build from wowhead (CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAMbzyyMjxwMbMmZwMzAAAAAAwYGDDsAbjGasBAmlpZAbLmZmGmxMGWmxMWYZsMLmZmZGzYGG) 

4. go to any aoe target dummies and do the aoe rotation normally to confirm that totemic recall is not working

5. also go to any ST target dummy to confirm that liquid magma is not working 

### Snapshot (Link)

Elemental; Primary - Earthquake(0.00), Lava Burst(1.11), Chain Lightning(2.21)

### Contact Information

Discord: jibbitytibbit

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by JibbityTibbit** [comment]
https://pastebin.com/0QvTyxWU

**Comment by Hekili** [comment]
This may be an artifact of using Cooldowns Shown Separately; Totemic Recall is not flagged as a Cooldown (see `/hekili` > `Abilities` > `Elemental` > `Totemic Recall` > `Require Toggle`), so it cannot be shown in the Cooldowns display.

It also looks like you don't have the `fire_elemental` talent, while the priority (currently) requires Fire Elemental to be talented.  It looks like there's an Elemental priority update that changes this and has not yet been integrated due to a scripting issue.  It should be addressed in the next release.

**Comment by Hekili** [comment]
There is a new priority in place for 1.0.14; please reopen or ticket with a new snapshot if this issue persists.
