### ISSUE TITLE
Trinket Status Tracker

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3752]
# TWW Trinket Implementation Status Tracker

It is known that not all trinkets are implemented yet, we do not need tickets for that at this time. See below to view the status of trinket implementation.

- [x] Raid Trinkets
- [ ] M+ Trinkets
- [x] World Trinkets
- [ ] Consumables
- [ ] Other items (weapons, etc)

**Comment by syrifgit** [comment]
@Hekili what's left on this after your big update?

**Comment by Spike2D** [comment]
foul_behemoths_chelicera @ 419
should be ID: 219915
