### ISSUE TITLE
[REC] MM Hunter Trueshot and Aimed Shot + Rapid Fire Queuing

### ISSUE THREAD

**Issue by roreycorey** [Hekili/hekili#3753]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Marksmanship

### Describe the Issue

When going into trueshot rotation the addon acts strangely. It will show to cast salvo, aimed shot, volley , rapid fire then trueshot but once you cast the previous abilities before trueshot the trueshot icon will dissapear and it will tell you to cast arcane shot.

 I've also noticed the rotation is completely broken during trueshot window you should press aimed shot and spam rapid fire button just incase it pops and it keeps trying to put arcane shots in-between when you have charge of aimed shot or rapid fire to use. i hope this makes sense.

### How to Reproduce

be a marksman hunter with the sentinel aoe build listed here https://www.icy-veins.com/wow/marksmanship-hunter-pve-dps-spec-builds-pet-talents?area=area_2 .

do your rotation with cooldowns enabled until rapid fire trueshot will dissapear. 

also trueshot window is broken in my opinion.

### Snapshot (Link)

https://pastebin.com/c0R9bCgd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/5QDzGAs8fL4UykUhde7J37

### Additional Information

Also I remembered that trueshot never seems to appear when your focus is not near 100%

### Contact Information

corey7728 discord

**Comment by syrifgit** [comment]
I'm looking into some general marksmanship stuff tonight anyways, will keep this ticket in mind.

**Comment by Hekili** [comment]
Is the snapshot taken right after casting Rapid Fire, then?

Can you snapshot when it recommends Rapid Fire followed by Trueshot and link that here?  Thanks!

**Comment by roreycorey** [comment]
Yes I can do that I will do it in a hour or soOn 12 Sept 2024 21:56, Hekili ***@***.***> wrote:
Is the snapshot taken right after casting Rapid Fire, then?
Can you snapshot when it recommends Rapid Fire followed by Trueshot and link that here?  Thanks!

**Comment by roreycorey** [comment]
Marksmanship; Primary - Arcane Shot(0.00), Arcane Shot(1.28), Explosive Shot(2.5 - Pastebin.com<https://pastebin.com/cJSAAy1Z>

It actually seemed to work this time which is strange. I just noticed that it doesnt ever really show trueshot too unless focus is high and the rotation doesnt seem to update when rapid fire refreshes after aimedshot.
________________________________

**Comment by syrifgit** [comment]
> I've also noticed the rotation is completely broken during trueshot window you should press aimed shot and spam rapid fire button just incase it pops and it keeps trying to put arcane shots in-between when you have charge of aimed shot or rapid fire to use. i hope this makes sense.


So to start with, I was unable to replicate your issue of trueshot not coming up. Pops up on cooldown for me every single time without fail, and doesn't disappear unless I start deliberately clicking wrong buttons.

Second, your understanding of the rotation isn't necessarily completely correct. You are allowed to hold rapid fire for up to 5 seconds if your lunar storm hero talent is [coming off CD](https://www.icy-veins.com/wow/marksmanship-hunter-pve-dps-rotation-cooldowns-abilities).

The rotation inside trueshot looked mostly fine to me, according to the guides and sims, and I was able to more or less hit my sim DPS on a dummy while following it 100%. That being said, [I submitted a few minor changes](https://github.com/Hekili/hekili/pull/3757) as the cooldown rate of aimed shot was not being calculated properly, so it's a little less "jumpy" now.

@roreycorey

**Comment by roreycorey** [comment]
> So to start with, I was unable to replicate your issue of trueshot not coming up. Pops up on cooldown for me every single time without fail, and doesn't disappear unless I start deliberately clicking wrong buttons.

> Second, your understanding of the rotation isn't necessarily completely correct. You are allowed to hold rapid fire for up to 5 seconds if your lunar storm hero talent is [coming off CD](https://www.icy-veins.com/wow/marksmanship-hunter-pve-dps-rotation-cooldowns-abilities).

That's a shame as it does happen for me quite alot with trueshot dissapearing and not showing in combat unless focus is high.

A small minmax you can do is taking advantage of the fact that Aimed Shot's cast time during Trueshot is slightly shorter than your GCD. Thanks to Surging Shots, Aimed Shot has a ~15% chance to reset the cooldown of Rapid Fire. Thus, you want to spam Rapid Fire during every Aimed Shot to queue up the Rapid Fire in case it gets a reset. (I was just going by this in terms of trueshot rotation) it says on the same icyveins page.

Thanks for looking into the issue so quickly.

**Comment by soockee** [comment]
have the same issue

**Comment by Hekili** [comment]
> Thus, you want to spam Rapid Fire during every Aimed Shot to queue up the Rapid Fire in case it gets a reset. (I was just going by this in terms of trueshot rotation) it says on the same icyveins page.

I'm not sure this is something I can display effectively in the addon.  The design philosophy is that recommendations are conservative, meaning that if a proc is not certain to occur, the addon's future predictions will assume it did not occur until it actually happens, and then recommendations will be updated.

It's *possible* that I can add some kind of indicator to Aimed Shot (using the caption feature) that shows something like `+[Rapid Fire Icon]` but it'll almost certainly require a lot of extensive explanation in Discord for people to understand it.

**Comment by roreycorey** [comment]
I completely understand that. I think the trouble is when it does reset that hekili is still telling you to use arcane shot it's just something I'll have to live with I guess.

What I'm saying is it can show arcane shot but I know that's wrong if rapid fire resets so it can be confusing to look at in intense situations but I understand that's something that can't really be fixed as it's such a short reset window.

**Comment by syrifgit** [comment]
> I completely understand that. I think the trouble is when it does reset that hekili is still telling you to use arcane shot it's just something I'll have to live with I guess.
> 
> What I'm saying is it can show arcane shot but I know that's wrong if rapid fire resets so it can be confusing to look at in intense situations but I understand that's something that can't really be fixed as it's such a short reset window.

Are you 100% sure it's wrong? As I highlighted above, you can hold rapid fire up to 5 seconds to wait for lunar storm. With a 15 second cooldown, you could theoretically have to to a 33% uptime on holding rapid fire.

Grab a snapshot when it's showing arcane shot but you're 100% sure it should be rapid fire. The addon updates 4 times a second by default I believe, plus on any notable combat events. If it was supposed to use rapid fire immediately because it reset, the recommendation would change.

**Comment by Hekili** [comment]
> I completely understand that. I think the trouble is when it does reset that hekili is still telling you to use arcane shot it's just something I'll have to live with I guess.

Can you provide a snapshot where this is happening?  If Rapid Fire *has already* reset, the addon should react and update accordingly.

I am also looking at whether to put some kind of visual indicator on Aimed Shot during Trueshot that suggests trying to queue Rapid Fire if it's on cooldown, but I'm still worried about confusing people.

**Comment by roreycorey** [comment]
Yes I will try later to see if I can capture it with a snapshot. Maybe you could put it on an optional tickbox like some other things ?On 16 Sept 2024 01:23, Hekili ***@***.***> wrote:

I completely understand that. I think the trouble is when it does reset that hekili is still telling you to use arcane shot it's just something I'll have to live with I guess.

Can you provide a snapshot where this is happening?  If Rapid Fire has already reset, the addon should react and update accordingly.
I am also looking at whether to put some kind of visual indicator on Aimed Shot during Trueshot that suggests trying to queue Rapid Fire if it's on cooldown, but I'm still worried about confusing people.
