### ISSUE TITLE
[REC] Not Recommending Potions/Second Trinket

### ISSUE THREAD

**Issue by JargerWolf** [Hekili/hekili#3755]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

I am unable to get it to recommend Potions in the rotation. I am using Tempered Potion specifically if that makes a difference. My apologies if this is already noted somewhere. I didn't see it. Thank you ahead of time for your help and thank you for the amazing work you have put into this addon :3

### How to Reproduce

Start DPS with the standard rotation set. Have both Skyterror's Corrosive Organ and Oppressive Orator's Larynx equipped. Neither the Tempered Potion nor Organ are recommended as part of the rotation.

### Snapshot (Link)

NA

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/oGKEaEE73LE5cXv8hv9brw

### Contact Information

jargerwolf

**Comment by syrifgit** [comment]
See: https://github.com/Hekili/hekili/issues/3752
