### ISSUE TITLE
[FEATURE] Please add the buff Dawnlight (from the Herald of the Sun Hero Talent tree) to Holy Paladin spec

### ISSUE THREAD

**Issue by NickGesirenZhang** [Hekili/hekili#3756]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [x] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I am writing my own Holy Paladin priority and would like to check if the buff Dawnlight (from the Herald of the Sun Hero Talent tree) is present on myself. I talked to Syrif on discord and they agreed to add this feature. Thanks!

### Contact Information

Discord: nicknik7354

**Comment by Hekili** [comment]
The stacks you get from casting Holy Prism and Barrier of Whatever is `dawnlight` in next release.

The HoT is `dawnlight_hot`.

The DoT is `dawnlight_dot`.

**Comment by NickGesirenZhang** [comment]
hooray! Thanks
