### ISSUE TITLE
Aug Evoker false Rotation @ Trash in Dungeons

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#3758]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

the Fire breath and Upheavel abilities are not displayed in trash groups. However, they work in boss fights and on dolls.

### How to Reproduce

the Fire breath and Upheavel abilities are not displayed in trash groups. However, they work in boss fights and on dolls.

### Snapshot (Link)

https://pastebin.com/GXgA6ZRF

**Comment by ghost** [comment]
Should i play in English to resolve this issue? :)

**Comment by Hekili** [comment]
???

**Comment by ghost** [comment]
Now it works , dont now how but it does ..

**Comment by tpfleck** [comment]
This doesn't work for me. Same issue Levion was having, it is very sporadic when it works.
