### ISSUE TITLE
Shadow priest with voidweaver rotation is wrong with void erruption.

### ISSUE THREAD

**Issue by comproh** [Hekili/hekili#3759]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

Rotation is wrong for shadow priest void weaver with void erruption
https://i.imgur.com/8xvefZl.jpeg

rotation should go like this but with  hekili it prioritized  plague before void erruption in the opener.

### How to Reproduce

Um st damage with the void weaver picked st talent profile. 

### Snapshot (Link)

https://pastebin.com/vQckxeim

### Contact Information

pie.are.squared

**Comment by syrifgit** [comment]
> rotation should go like this but with hekili it prioritized plague before void erruption in the opener.

Which is exactly what your screenshot shows that it should do ..? I'm not sure I understand the issue.

![image](https://github.com/user-attachments/assets/19ebe899-f276-43d3-92e5-4781ef7291dc)

**Comment by Hekili** [comment]
Can you provide a sim of yourself for comparison?

Void Blast does not appear to be available in your snapshot because Entropic Rift doesn't appear to be active.  Was Void Blast actually available to you at the time of the snapshot?

**Comment by syrifgit** [comment]
Requested information not received. If you believe this is still an issue on the newest addon version, you may open a new ticket or reply here. Be sure to include the requested information.
