### ISSUE TITLE
[REC] Havoc Opener Issues

### ISSUE THREAD

**Issue by yokaii4** [Hekili/hekili#3761]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Havoc

### Describe the Issue

In the latest update, the addon is performing Havoc rotation worse than before. Starting from the pre pull, sigil of flame is not recommended after immolation aura, and felblade is recommended before the Hunt, while it should follow Eye Beam later. The issue with Vengeful Retreat not being recommended before Metamorphosis persists and after using Metamorphosis the addon does not recommend Consuming Fire at all (it should be casted before Sigil of Doom).

### How to Reproduce

1. Enter game as Havoc with FelScarred ST talents
2. go to the Kelpfist dummy in Dornogal
3. proceed with the opener/rotation

### Snapshot (Link)

Prepull snapshot: https://pastebin.com/ZSeMWb48 Wrong felblade recommendation: https://pastebin.com/62pL8fnT Vengeful Retreat not being recommended before Meta: https://pastebin.com/jnL0Kz5L Consuming Fire not being recommended: https://pastebin.com/vHHGbXFf

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9nZggkgUwVC1oFE3w5Y1Jp

### Contact Information

yokaii__

**Comment by AnthonyGrenier** [comment]
+ on this. Rotation for havoc seems quite incorrect (at least for FS).

**Comment by AnthonyGrenier** [comment]
In any opener, Sigil of Flame does not seems to be recommended at all. Once in Meta, Immolation is not even recommended to proc a Demon Surge.

**Comment by yokaii4** [comment]
> In any opener, Sigil of Flame does not seems to be recommended at all. Once in Meta, Immolation is not even recommended to proc a Demon Surge.

Correct, I missed this one but apparently Sigil is not being recommended at all. On a side note, you can also notice that my on use trinket is not being recommended too

**Comment by syrifgit** [comment]
> On a side note, you can also notice that my on use trinket is not being recommended too

https://github.com/Hekili/hekili/issues/3752

**Comment by syrifgit** [comment]
## Sigil of Flame
```
        4.   sigil_of_flame ( precombat - 4 )
        The action (sigil_of_flame) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry's criteria FAILS: ! talent.demonic_intensity.enabled[true] | cooldown.metamorphosis.remains[0.00]
        There were no recheck events to check.
        Time spent on this action:  0.20ms
        TimeData:Havoc-precombat-4:sigil_of_flame:0.20:Ability Known, Enabled(0.02):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.09):Pre-Recheck(0.02):Post-Recheck Times(0.01):Post Recheck(0.00)
```

SIMC version of this line doesn't seem to have conditions attached to it

```
actions.precombat+=/variable,name=trinket2_steroids,value=trinket.2.has_stat.any_dps
actions.precombat+=/variable,name=rg_ds,default=0,op=reset
actions.precombat+=/sigil_of_flame
actions.precombat+=/immolation_aura
```

## Felblade

This behaviour matches your sim perfectly for 6 casts in a row. Why do you think Felblade should be after?

`Havoc; Primary - Felblade(0.00), The Hunt(1.00), Eye Beam(2.00), Fel Rush(3.73), Death Sweep(3.98), Annihilation(4.98),`

![image](https://github.com/user-attachments/assets/326ac988-8194-42ae-8d99-f38ba03c10ca)

## Vengeful Retreat

Same as Felblade. This matches the sim, why do you think it's wrong?

`Havoc; Primary - Metamorphosis(0.00), Death Sweep(1.00), Sigil of Doom(2.00), Annihilation(3.00), Vengeful Retreat(3.71),`

![image](https://github.com/user-attachments/assets/18172388-03b8-45ef-b0aa-47be55af0ad6)

## Consuming Fire

It didn't show up in the snapshot, unsure what's up there.

**Comment by yokaii4** [comment]
> This behaviour matches your sim perfectly for 6 casts in a row. Why do you think Felblade should be after?
> 
> Havoc; Primary - Felblade(0.00), The Hunt(1.00), Eye Beam(2.00), Fel Rush(3.73), Death Sweep(3.98), Annihilation(4.98),

Although it matches the Sim, it's a slight DPS los because casting felblade after The Hunt let's you retain a bit more Fury as suggested in the guides (https://www.wowhead.com/guide/classes/demon-hunter/havoc/rotation-cooldowns-pve-dps)

> Vengeful Retreat
> Same as Felblade. This matches the sim, why do you think it's wrong?
> 
> Havoc; Primary - Metamorphosis(0.00), Death Sweep(1.00), Sigil of Doom(2.00), Annihilation(3.00), Vengeful Retreat(3.71),

Casting Vengeful Retreat before Meta is essential because you proc Initiative, unsure as to why the sim suggests otherwise. Refer to the class guide above for this point too

> Consuming Fire
> It didn't show up in the snapshot, unsure what's up there.

Unsure, however I believe there's an issue with it since consuming fire is casted right after Meta. Check the guide linked above for this point as well.

Please let me know if you need more information!

**Comment by AnthonyGrenier** [comment]
Reverting to version 1.0.12a seems to be the best option until fix is implemented.

**Comment by Magwir3** [comment]
> Reverting to version 1.0.12a seems to be the best option until fix is implemented.

How does one do this?

**Comment by syrifgit** [comment]
> Although it matches the Sim, it's a slight DPS los because casting felblade after The Hunt let's you retain a bit more Fury as suggested in the guides (https://www.wowhead.com/guide/classes/demon-hunter/havoc/rotation-cooldowns-pve-dps)

Is it possible to ask in the DH discord about this discrepancy? The sims and guides clearly disagree. and Hekili is based on sims unless there is good reason or proof to go against them,

**Comment by yokaii4** [comment]
@syrifgit I tried asking but apparently there's no real reason and technically "the dps difference should be marginal" although I kinda disagree(the user replying to me wasn't a known member so take it with a grain of salt) because if I vengeful retreat on meta I do more DPS on my burst than as Hekili suggests. I'm talking about 1.09M burst vs not even 900k. I suggest just copying the guide would benefit the addon because I guess that all the procs etc. kinda mess with the recommendations and don't let you burst as you should. AOE seems to be the same: in this case you get Immolation Aura suggested every time it procs, but during the opener it may delay your other CDs too much and could result in a dps loss, besides the first immolation aura wouldn't generate much dps since you were busy getting the others so it is an unnecessary Fury pooling that waste the rotation's time

**Comment by AnthonyGrenier** [comment]
Any updates on this? I think just following the guides is best thing to do here. Also cannot use 1.0.13 as it still seems really messed up.

**Comment by Hekili** [comment]
@AnthonyGrenier Please don't post asking for updates.  I update when I have updates.

1.0.14 is about ready for release and fixes some issues with Sigil of Doom and Immolation Aura.  It looks like it is matching SimulationCraft, although I'm testing with an underleveled DH.
