### ISSUE TITLE
Guardian DoTC fails to recommend Rip/Rake if Rage of the Sleeper is unticked in abilities.

### ISSUE THREAD

**Issue by whysoserrus** [Hekili/hekili#3763]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Guardian

### Describe the Issue

On my guardian druid which is talented into Wildpower Surge and reaches 6 stacks of Feline Potential, I expect the addon to recommend to shapeshift to cat form and cast rip then rake then back to bear. It does this if Rage of the Sleeper ability is toggled on in Hekili (Default) regardless if Rage of the Sleeper is currently active or not. Often it will be active for rake and rip  as it will recommend RoTS much earlier, usually on pull. I would like to be able to save this ability as it is also a defensive cooldown as well as an offensive. It would impact the DPS of rake / rip if used in combination but the rotation rarely has this happen as it takes much longer to build 6 stacks of Feline Potential than the 8 seconds of RoTS.

### How to Reproduce

1. Enter game as Guardian Druid
2. Be specced into Druid of the Claw Hero Talents and specifically take Wildpower Surge in left hand side choice node. 
3. Open Hekili and proceed to Abilities Section
4. Disable Rage of the Sleeper
5. Build 6 stacks of Feline Potential by using Mangle
6. Rotation will not recommend rake or rip at any point. It will if you enable Rage of the Sleeper. 

### Snapshot (Link)

https://pastebin.com/ceiY2PTA - Disabled RoTS / https://pastebin.com/cnJBUeGZ - Enabled RoTS

### Contact Information

whysoserrus

**Comment by Hekili** [comment]
Please add a Raidbots sim link in the same talents. It should be a Patchwork 1-target sim for comparison.

**Comment by whysoserrus** [comment]
https://www.raidbots.com/simbot/report/vzjmvfkyUw43htQhvpRFoy

**Comment by whysoserrus** [comment]
Also would like to add that in the ability queue it says to Rake which will swap me into cat form and cast rake with talents selected but then to go bear but if I  push rake and hekili updates it will say rip then bear where as what I do and believe the sim says is to Rake > Rip > Mangle as mangle will shift back to bear thanks to the same talent as the catshift from Rake. 

Here is a snapshot for this behaviour: https://pastebin.com/PnvarwZq

**Comment by Hekili** [comment]
This may be (partially?) addressed in 1.0.14; please comment and reopen if you continue to find issues.
