### ISSUE TITLE
[REC] Assassination pooling queue

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#3768]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Assassination pooling is still not working as intended from the last fix. When energy is low and at 5 combo point, we wait for energy to send envenom but Hekili spell queue showing Mutilate instead, then at desired energy, it instantly changed to Envenom

### How to Reproduce

1. Enter game as Assassination
2. Doing rotation until your energy get low enough to start pooling
3. at 5 combo point and without Darkest Night proc, we should wait for energy to send envenom but hekili showing mutilate

### Snapshot (Link)

https://pastebin.com/j1ptnEDq

**Comment by Hekili** [comment]
Please provide an equivalent sim via Raidbots and link it here -- I don't see the sim actually pooling like you're expecting.

**Comment by Sedveth** [comment]
> Please provide an equivalent sim via Raidbots and link it here -- I don't see the sim actually pooling like you're expecting.

Ok let me explain it more. As you see in the snapshot, I was at 5 CP, and Hekili suggested to do 1 more Mutilate instead of sending finisher. This is wrong behaviour in Simc, We only do it if we have Darkest Night proc and in my snapshot, it didnt have it.
But the problem is that, after few seconds of suggesting Mutilate, it changed back to correct action which is sending Envenom, that's why I assummed there is something wrong with energy pooling, but maybe it's something different, hope you can take a look into this problem

simc link: [https://www.raidbots.com/simbot/report/oyvDEymYqxxaGzc2Qo5xd5/simc](url)

**Comment by Sedveth** [comment]
Just let me know if you need me to provide other snapshot for this issue, thank you

**Comment by Hekili** [comment]
Could you provide an updated snapshot, please?  I *think* I know what's up (a filler Mutilate), but there have been timing changes since your previous snapshot. Thanks!

**Comment by Sedveth** [comment]
> Could you provide an updated snapshot, please? I _think_ I know what's up (a filler Mutilate), but there have been timing changes since your previous snapshot. Thanks!

Sorry for the delay. Here is my new snapshot.
Same behaviour, I was at 5 Combo Point, low energy, no Darkest Night proc and it still suggest Mutilate instead of Finisher like Rupture or Envenom.
[https://pastebin.com/E5bDn8ER](url)

**Comment by Sedveth** [comment]
Upvote this again, hope Hekili can take a look

**Comment by Hekili** [comment]
I will test a new spec setting in the next release that, if checked, will turn `use_filler` on if you are missing 3+ combo points (vs. 2+ combo points as the priority is written).  This may have unintended consequences, so it will require additional testing.

**Comment by Sedveth** [comment]
> I will test a new spec setting in the next release that, if checked, will turn `use_filler` on if you are missing 3+ combo points (vs. 2+ combo points as the priority is written). This may have unintended consequences, so it will require additional testing.

That's amazing, I wanna update that it's not only happened at 5 Combo Point but also at charged Combo Points from using Echo Reprimand as well

**Comment by devil81** [comment]
any news ?  was this fixed with the last update ?

**Comment by devil81** [comment]
i notice huge lag imput with the addon on last boss hc when 25-30m in raid , i have very good pc but for some reason the addon manage to kill my pc - ryzen 9 7950X3D 4090RTX ... i was using assasination spec for hekili

**Comment by syrifgit** [comment]
> i notice huge lag imput with the addon on last boss hc when 25-30m in raid , i have very good pc but for some reason the addon manage to kill my pc - ryzen 9 7950X3D 4090RTX ... i was using assasination spec for hekili

That's unrelated to this ticket.

In general the addon does require a lot of CPU. Right now, everyone is experience lower frames / higher CPU use in the new expansion, even people without this addon.

You can
- Reduce the # of icons shown on Hekili, particularly if you show more than 3 currently
- Make details slower (update interval)
- Check plater scripts which might be costly
- Check for poorly coded weakauras

**Comment by Hekili** [comment]
I've made another adjustment to the priority; it will pool resource for Envenom when Darkest Night is up and you have 5+ Combo Points.

I removed the "filler" Envenom that I'd previously added.  It looks like this pools as expected, but if there are additional conditions that should be met before pooling, please let me know.

**Comment by Hekili** [comment]
Closed; I *probably* won't make further adjustments for this, as it's not really consistent with the sim behavior anyway.

See:

![image](https://github.com/user-attachments/assets/92fb5ef6-2b5b-4aee-8e78-d24fd978dcef)

**Comment by Hekili** [comment]
(Actually, making one more adjustment to pool for Envenom when Darkest Night is *down* rather than *up*.)
