### ISSUE TITLE
Rotation Does Not Recommend Cold Blood at all

### ISSUE THREAD

**Issue by Urbanskiii** [Hekili/hekili#3769]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

Addon does not recommend Cold Blood at all throughout the entire rotation for Subtlety

### How to Reproduce

1. Enter game as Subtlety Rogue
2. Make it past the first rotation of Shadow Dance
3. See that there is no recommendation before Secret Technique/no recommendation at all

### Snapshot (Link)

https://pastebin.com/ZjTFgH5D

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dpS7jV9Y8BiSvJ478JKdfi

**Comment by syrifgit** [comment]
Ability unknown, probably the same issue as assassination with the hero talent spellIDs.

**Comment by loadeddeath** [comment]
Can confirm,  cold blood is not being recommended even after tweaking

**Comment by Hekili** [comment]
I think this is fixed in 1.0.14; if it has issues when Inevitability is talented, please let me know.
