### ISSUE TITLE
extra button bar for toggles not showing

### ISSUE THREAD

**Issue by Mura1108** [Hekili/hekili#377]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
before a pc crash and fresh clean install - I had a small buttonbar for Hekili that had the toggles for aoe, ST, auto/CD/Defensives/interrupts.
This was not a seperate addon - and Even though I have the drop down menu on the minimap I quite liked the extra small button bar.

**To Reproduce**
Always present

**Expected behavior**
a small "actionbar" with the toggle buttons like in the added screenshot from before my clean install

**Screenshots**
![unknown (2)](https://user-images.githubusercontent.com/64037094/84699883-9e864480-af52-11ea-802c-fb8d63ebdd71.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/cP0Vnfhk

**Comment by Hekili** [comment]
It's a WeakAura, available here:  https://wago.io/HekiliToggles
