### ISSUE TITLE
Sin Rogue - Unable to make recommendation for Primary #1

### ISSUE THREAD

**Issue by Ennz729** [Hekili/hekili#3770]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

I'm not sure what it should recommend I'm learning the spec but it happens often when energy is very low.  Unable to recommend an action

### How to Reproduce

1. Get into combat
2. Use energy until it gets very low

### Snapshot (Link)

https://pastebin.com/2BjyaCnP

### Contact Information

enzo2923

**Comment by Hekili** [comment]
Timing fixes in 1.0.14 may address this; if not, please comment and reopen.

**Comment by michaerlrob92** [comment]
Adding this here as got an auto snapshot when it cannot recommend anything

https://pastebin.com/wqEyhaxi

**Comment by Ennz729** [comment]
Updated to 11.0,2-1.0.17, single target I noticed the same behavior happening although very less frequently.  Here is the pastebin -
https://pastebin.com/QBjatD7s

**Comment by syrifgit** [comment]
Reopened

@Hekili

**Comment by Ennz729** [comment]
https://pastebin.com/DC4EKy1H

Added new pastebin from m+ today.

**Comment by aaronlilla** [comment]
https://pastebin.com/Ns2AxrsA
https://pastebin.com/ahfHKeAQ
https://pastebin.com/n8NHS8fT
https://pastebin.com/kg2u0DqD

**Comment by Hekili** [comment]
There have been updates to Assassin in 1.0.18; please provide new snapshots if this happens again.

**Comment by Hekili** [comment]
DrWren snapshot:  [pastebin.com/GGsbUT3u](https://pastebin.com/GGsbUT3u)

**Comment by Hekili** [comment]
This should be resolved in next release.
