### ISSUE TITLE
Assassination Rogue bad Shiv logic

### ISSUE THREAD

**Issue by w1tch666** [Hekili/hekili#3771]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

I expect the addon to recommend Shiv to snap the last 8 seconds of Kingsbane debuff when playing without the talent [Lightweight Shiv] that gives you an additional Shiv charge, instead of using the only Shiv charge we have right after casting Kingsbane.

Right now when playing with just 1 Shiv charge the addon will tell me to use that Shiv right after kingsbane cast as seen in the attached Snapshot and against what the recommendation should be as seen in attached raidbots.

### How to Reproduce

1.Enter game as Assassination Rogue
2.Don't take the [Lightweight Shiv] Talent
3.Opener rotation on any target or dummy
4.Reach the point in which Kingsbane is about to get recommended (usually right after Deathmark)
5.see recommendations

### Snapshot (Link)

https://pastebin.com/47mydfGE

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9vLbecihq1JCF4zinoojND

**Comment by Hekili** [comment]
This is fixed in a SimC priority update included in 1.0.14.
