### ISSUE TITLE
[REC] Dev evoker - dragonrage recommendation disappear from queue after using deep breath

### ISSUE THREAD

**Issue by akshay14021** [Hekili/hekili#3775]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Devastation

### Describe the Issue

During combat, after using living flame and deep breath as opener, dragonrage disappear from queue
Along with it after using fire breath it does not recommend eternity surge unless you press skill and then it will show in queue, sometimes when fighting multiple enemies even if cds are off cd, it is not recommending unless I switch target.

if deep breath is on cd, every other recommendations are in order

### How to Reproduce

1. Enter game in dungeon
2. Make sure cds are toggled
3. Start by using living flame
4. Deep breath
5. after deep breath usage end
6. No dragon rage in queue
7. Only recommending fire breath 
8. No eternity surge recommendation

### Snapshot (Link)

https://pastebin.com/T7ipfT7w

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/n1y2492KCpcKyPbjxDyHgd

**Comment by syrifgit** [comment]
You need to add a snapshot where the issue is actually occuring

**Comment by akshay14021** [comment]
@syrifgit yeah i am gonna queue into dungeon and add a new snapshot

**Comment by akshay14021** [comment]
@syrifgit https://pastebin.com/NWZRBDBb this is a new one
if you want to see recording ive uploaded that as well

https://github.com/user-attachments/assets/22532792-642d-4aab-b776-f51cf2d194ac

Adding a new snapshot and recording with deep breath turned off from settings in hekili
https://pastebin.com/pwnP7KqA


https://github.com/user-attachments/assets/131cfcf3-2e19-4595-8b5f-291a46e08a30

**Comment by akshay14021** [comment]
@syrifgit this one should give a better idea I think https://pastebin.com/AG9VYhTb
and here is a rec where I switch target and then recommendations are changing - so basically fighting same mobs give wrong recommendations and as soon as I change target it gives correct one


https://github.com/user-attachments/assets/ae009c71-1515-41df-9213-2e472b9a3ac3

**Comment by Hekili** [comment]
Dragonrage was ruled out in your last snapshot because your target was expected to die soon and the "use it before the fight ends" condition was set to boss fights only.

I've removed those time-related conditionals from the AOE action list; we'll see if that resolves this completely.
