### ISSUE TITLE
Snapshots Saved Chat Spam Error

### ISSUE THREAD

**Issue by Shockette** [Hekili/hekili#3776]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Playing Assassination Rogue with the below build.  Sometimes when I get out of combat Hekili starts to just spam this error message in chat and my memory usage for Hekili starts to just climb.  I have to reload UI to get it to stop.  

Rogue build    CMQA27SZpS4XnmFfcXRqkppuwPjZmZGmhZAAAAAAY2gtZAAAAAAottZmhZmxYmZWmlxYwMzMzgZmZbbZMDwmZZgBsEsMMBGWA

This happens no matter the build though.

### How to Reproduce

Play assassination rogue with the above build and enter combat until it happens I guess.  I have a bugsack report and maybe that will lead to the cause. 

### Player Information (Link)

Assassination; Primary - Envenom(0.65), Mutilate(1.65), Mutilate(3.21), Mutilate(5.23) build: v11.0.2-1.0.13 level: 80 (80) class: ROGUE spec: assassination  talents: CMQA27SZpS4XnmFfcXRqkppuwPjZmZGmhZAAAAAAY2gtZAAAAAAottZmhZmxYmZWmlxYwMzMzgZmZbbZMDwmZZgBsEsMMBGWA     acrobatic_strikes = 1/1     airborne_irritant = 1/1     alacrity = 2/2     amplifying_poison = 1/1     bait_and_switch = 1/1     blackjack = 1/1     blind = 1/1     bloody_mess = 1/1     caustic_spatter = 1/1     cheat_death = 1/1     clear_the_witnesses = 1/1     cloak_of_shadows = 1/1     corrupt_the_blood = 1/1     crimson_tempest = 1/1     darkest_night = 1/1     deadened_nerves = 1/1     deadly_poison = 1/1     deadly_precision = 1/1     deathmark = 1/1     deathstalker = 1/1     deathstalkers_mark = 1/1     deeper_stratagem = 1/1     doomblade = 1/1     dragontempered_blades = 1/1     echoing_reprimand = 1/1     evasion = 1/1     fatal_concoction = 1/1     fatal_intent = 1/1     featherfoot = 1/1     fleet_footed = 1/1     graceful_guile =

### Error Messages (Link)

Below

### Additional Information

[New Text Document (3).txt](https://github.com/user-attachments/files/17003563/New.Text.Document.3.txt)

### Contact Information

Shock#2655

**Comment by Shockette** [comment]
![Hekili Spam](https://github.com/user-attachments/assets/78e7c6a9-0ebb-4c3b-a699-a06ee3b5ed5a)

**Comment by Shockette** [comment]
There are three Different Bugsacker Errors in my text document I attached.  I hope this helps to pinpoint the error.  It doesnt seem to matter which spec points I have setup for Assassination.  it occurs in both single target raid as well as Multi-target raid as well as Mythic + builds.   If you need more information please dont hesitate to ask and thank you for such a great addon.

**Comment by Hekili** [comment]
These are all "script ran too long" errors generated when the addon detected a snapshot was needed. 

When this is occurring or has occurred, is there any information in the /hekili > Warnings section or is it greyed out?

**Comment by Shockette** [comment]
Ive been trying to get it to do the repeat thing since I just saw this message and I just saw this come up.  
![image](https://github.com/user-attachments/assets/ab3e6074-03a3-473f-a18f-8d1e1d053f79)

Warning section still greyed out after this one but ill keep trying to see if I can brick it to do the constant spam

**Comment by Hekili** [comment]
It would be good to put the snapshot on Pastebin and link it here.

**Comment by syrifgit** [comment]
Snapshot not received by user.

**Comment by Shockette** [comment]
Hold on im trying  got it to do it again today
![image](https://github.com/user-attachments/assets/74d0cbff-076f-420c-a45b-f4e69835db77)

**Comment by Shockette** [comment]
it did it again in raid.  Warnings is still greyed out and I couldnt click the issue reporting because it was spamming.  It was also erroring when I tried to hit pause on it.

![image](https://github.com/user-attachments/assets/60454de0-35e5-464a-9bc6-da8429f67cee)
