### ISSUE TITLE
Brewmaster Monk Blackout Combo, AOE recommending incorrect ability priority

### ISSUE THREAD

**Issue by zetusx** [Hekili/hekili#3778]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Brewmaster

### Describe the Issue

For my Brewmaster Monk with Blackout Combo talented, in any AOE scenario or when there is even just more than 1 mob/boss, the recommended priority of abilities typically will recommend either Keg Smash or Breath of Fire to consume the BOC buff instead of Tiger Strike. For both Offensive and Defensive purposes this is incorrect. 

Furthermore, this problem may also be related to the AOE Priority as a whole, due to the overwhelming number of times the priority recommends using Spinning Crane Kick, going so far as to recommend using 2-3 times back to back.

Both the current Sims as well as  the class discord recommend that BOC should 95% of the time be consumed by Tiger Strike instead, and that Crane Kick is used dramatically less frequently.

For the Keg Smash issue: one of the main reasons why is that on a Defensive level, the extra Brew CD reduction from keg smash, even with Special Delivery talented, is not a boost in DPS, and is inconsequential on a Defensive level, since those extra 2 Seconds rarely will lead to reaching a Celestial or Purifying Brew at a needed point when there are other Defensive CD's to weave in if necessary.

For the Breath of Fire issue: While the Blackout Combo 50% buff to the damage of Breath of Fire is good, the extra damage is only applied to the initial hit of Breath and does not increase the damage of the DoT, furthermore, this causes the 5% increased damage reduction on the DoT debuff from Breath to be wiped from the buffed 10% to the normal 5% debuff if that target is hit by a Breath of Fire that is not not being buffed from Blackout Combo.

In regards to Spinning Crane Kick, it is typically only utilized at most once to assist with gathering adds/threat, and the majority of Brew Monk's AOE damage stems from Keg Smash. You can see in the 3 target boss sim I have linked Spinning Crane is never used, and in the 5 target boss sim I linked in the additional information panel, it is used only 5 times throughout the fight

### How to Reproduce

1. Enter game as Brewmaster Monk
2. Talent into Blackout Combo
3. set addon to Automatic or AOE
4. Begin fight in dungeon against multiple mobs or against multiple Tank Training Dummies
5. Recommendation immediately suggests using Keg smash after Blackout Kick, and shortly thereafter recommends Breath of Fire after Blackout Kick, Double Spinning Crane Kick is then recommended soon as well

### Snapshot (Link)

https://pastebin.com/5M0ZqQjM

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/u7TfUgUC5YTnmie661kuEu

### Additional Information

5 target boss sim: https://www.raidbots.com/simbot/report/o14oRiWstYzDpfq2oTXgpW

Here is a link to a small video that goes over much of what I stated made by a much more knowledgeable than me Monk from the class discord server
https://www.youtube.com/watch?v=JqQf7LF7I0E

While reading through some of the snapshot, I did also notice that there were several mentions of Bonedust Brew in the profile, I am unsure if this is causing any issues since that ability is no longer in the game, but I wanted to mention it as well!

Thank you again for all you do in the support of the addon <3

### Contact Information

xzetusx on Discord

**Comment by Hekili** [comment]
The Brewmaster priority is still heavily based on DF, mainly because I have to make all the settings actually impact the new priority.  But this is on the radar to update.

**Comment by Hekili** [comment]
Added in next release.
