### ISSUE TITLE
Certain Spells - Keybinds not appearing

### ISSUE THREAD

**Issue by schwartzmiller** [Hekili/hekili#378]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
I just recently switched back to the default blizzard action bars and I noticed that when I have certain spells in the top left action bar, say Immolation Aura that the keybind doesn't show up within the Hekili bar.  In this particular example, Shift+2.  If however I move a different spell into that action bar slot, Infernal Strike as an example the S2 will show up within Hekili.

I previously used bartender and didn't seem to have this issue so I can always go back.  But wanted to see if you were aware or had any ideas.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
Keybinds to show within Hekili for all bars and spells

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v8.3.0-07
level: 120 (120)
class: DEMONHUNTER
spec: vengeance

talents: abyssal_strike
    fallout
    flame_crash
    fracture
    gluttony
    sigil_of_chains
    void_reaver

azerite: azerite_empowered = 3
    bulwark_of_the_masses = 1
    cycle_of_binding = 1
    gutripper = 1
    heart_of_darkness = 1
    infernal_armor = 2
    lifespeed = 1
    revel_in_pain = 2
    shimmering_haven = 1
    soulmonger = 1
    thrive_in_chaos = 1

essences: [vision_of_perfection] = 1, nullification_dynamo = 1, the_crucible_of_flame = 1, touch_of_the_everlasting = 1

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    footguards_of_the_insatiable_maw = 1
    galecallers_boon = 1
    gonk_outrunner_breeches = 1
    gonk_outrunner_mask = 1
    grasp_of_the_insatiable_maw = 1
    grips_of_the_insatiable_maw = 1
    harlans_loaded_dice = 1
    heart_of_azeroth = 1
    honorbound_warglaive = 1
    ring_of_cosmic_potential = 1
    shoulderpads_of_the_insatiable_maw = 1
    thornwoven_band = 1
    vest_of_the_insatiable_maw = 1
    whisperfen_chopper = 1
    wristwraps_of_the_insatiable_maw = 1

corruptions: none

itemIDs: 155881, 157913, 157914, 158075, 158108, 159614, 162548, 163877, 169223, 173440, 173443, 173512, 173516, 173843, 174533, 174954

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Vengeance
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
I'll need a list of spells whose keybinds aren't detected when placed in the same slot, and screenshots would help.

**Comment by schwartzmiller** [comment]
Thanks for the response..

I know concentrated flame and immolation are both not working.  Other appear to work fine when moving them into a Shift+2 keybind on the top left bar as shown in the screenshots.

Here you can see immolation is bound to Shift+5 but within Hekili it it showing as 2:

![image](https://user-images.githubusercontent.com/15131473/84771773-930d3a80-af9f-11ea-9755-3106f5a90e2c.png)

Here is an example of Demons Bite which Hekili is noting it is bound to Shift+5:
![image](https://user-images.githubusercontent.com/15131473/84771882-bc2dcb00-af9f-11ea-9ea6-7ff5377e93b9.png)

Thank you

**Comment by Hekili** [comment]
If you go through your action bar pages, are there entries for any of these abilities left orphaned on another action bar?

I.e., use the up and down arrows to look at the other bars and see if those abilities are in other action bar slots.

![image](https://user-images.githubusercontent.com/9438134/84783163-ee96f280-afb6-11ea-9fc5-010d3bddd2f2.png)

If so, can you screenshot them and then remove them and see if that fixes it?  Thanks.

**Comment by schwartzmiller** [comment]
That was it... it was on two bars.... good grief.  

Thank you for the assistance!

**Comment by Hekili** [comment]
Could you let me know which bar(s) the ability was also on?  I'd like to error proof this if possible.  Thanks.

**Comment by schwartzmiller** [comment]
They were on bar 2 and also on the top left bar.  So it seems like bar2 keybindings were overriding the top left bar keybindings.

Thanks again!

**Comment by ZFBedo** [comment]
@Hekili i have Elvui and it is reading only Elvui keybinds even after i turn-off Elvui it still read its keybinds, should i empty all moves from bars or what? cause i think Elvui is overriding WoW defult UI now is DF so it work even in keybinds.
