### ISSUE TITLE
Mark of Khardros (trinket) not showing on prio display

### ISSUE THREAD

**Issue by Helperboy88** [Hekili/hekili#3782]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

As title says new trinket from Grim Batol isn't showing.

### How to Reproduce

No matter what spec I'm in doesn't show on prio

### Snapshot (Link)

https://pastebin.com/emRf5jGh

**Comment by Hekili** [comment]
See #3752
