### ISSUE TITLE
[BUG] Subtelty - Not recommending Cold Blood before Secret Technique

### ISSUE THREAD

**Issue by michaerlrob92** [Hekili/hekili#3783]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

According to sim and the apl it should be casting cold blood right before secret technique, however it doesn't recommend it ever

### How to Reproduce

1. Login to Rogue
2. Change spec to Subtelty
3. Take Cold Blood & Secret Technique talents
4. Hit target dummy and continue with rotation until Secret Technique is recommended
5. No cold blood is recommended before

### Player Information (Link)

https://pastebin.com/9iPTAQYZ

### Error Messages (Link)

https://pastebin.com/9iPTAQYZ

### Contact Information

vastico

**Comment by michaerlrob92** [comment]
![image](https://github.com/user-attachments/assets/2852b532-9e91-43b3-99b9-d819a9afe8a8)
Cold blood talented

![image](https://github.com/user-attachments/assets/d8806232-9bb2-4f4e-aa1e-5ed36bbfb672)
Paused on secret technique

**Comment by Hekili** [comment]
There is an open ticket for Cold Blood; this will be addressed soon.
