### ISSUE TITLE
[REC] Sub rogue rotation keeps changing

### ISSUE THREAD

**Issue by Sedveth** [Hekili/hekili#3785]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

I was doing a dummy testing and for some reasons, when you are not in cooldown window, at the moment at 3 combo point, Hekili rotation kept changing between Backstab and Rupture back and forth, so I guess there is some issue with logics here.

### How to Reproduce

1. Enter a game as Sub Rogue
2. Do a rotation, out of cooldown window, no dance, no symbol
3. At 3 CP, Hekili was confused and rotation keeps changing back and forth, between Backstab and Rupture

### Snapshot (Link)

https://pastebin.com/7ZYAeB6h

**Comment by Hekili** [comment]
You'd need to take snapshots of both recommendations in order to do a comparison.

**Comment by syrifgit** [comment]
Requested snapshots not received.

If this issue is still happening to you on the newest addon version, you may open a new ticket or reply here. Be sure to include a snapshot **_before and after_** the changed recommendation
