### ISSUE TITLE
Augmentation Rotation dont work correctly on Trash Mobs @ Dungeons

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#3787]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

the Fire breath and Upheavel abilities are not displayed in trash groups. However, they work in boss fights and on dolls.

### How to Reproduce

The Rotation stops working correctly @ trash mobs during Dungeons or Mythic 

The Addon then creates an Auto Snapshot which i post here

### Snapshot (Link)

Augmentation; Primary - N/A build: v11.0.2-1.0.14 level: 80 (80) class: EVOKER spec: augmentation  talents: CEcBWYnbRY1EREkP8a0IbB+ZHwMGbzMzMWGMzsMzwMmZDAAAAAMAAYmBAGzUzYmZAAAAwMmZbMzsMmZgx2MwY2swCMwMM0IWwM     accretion = 1/1     aerial_mastery = 1/1     afterimage = 1/1     anachronism = 1/1     ancient_flame = 1/1     arcane_reach = 1/1     blast_furnace = 1/1     blistering_scales = 1/1     breath_of_eons = 1/1     chrono_flame = 1/1     chrono_ward = 1/1     chronowarden = 1/1     defy_fate = 1/1     doubletime = 1/1     draconic_attunements = 1/1     draconic_legacy = 1/1     ebon_might = 1/1     eruption = 1/1     essence_attunement = 1/1     essence_burst = 1/1     expunge = 1/1     extended_flight = 2/2     fate_mirror = 1/1     fire_within = 1/1     golden_opportunity = 1/1     hoarded_power = 1/1     ignition_rush = 1/1     imminent_destruction = 1/1     infernos_blessing = 1/1     inherent_resistance = 2/2     innate_magic = 2/2     instability_matrix = 1/1     instinctive_arcana = 2/2     interwoven_threads = 1/1     landslide = 1/1     leaping_flames = 1/1     molten_embers = 1/1     momentum_shift = 1/1     natural_convergence = 1/1     obsidian_bulwark = 1/1     obsidian_scales = 1/1     panacea = 1/1     permeating_chill = 1/1     potent_mana = 1/1     prescience = 1/1     primacy = 1/1     protracted_talons = 1/1     pupil_of_alexstrasza = 1/1     quell = 1/1     regenerative_chitin = 1/1     renewing_blaze = 1/1     rescue = 1/1     reverberations = 1/1     ricocheting_pyroclast = 1/1     rumbling_earth = 1/1     scarlet_adaptation = 1/1     source_of_magic = 1/1     stretch_time = 1/1     tectonic_locus = 1/1     temporal_burst = 1/1     temporality = 1/1     threads_of_fate = 1/1     time_skip = 1/1     time_spiral = 1/1     tip_the_scales = 1/1     twin_guardian = 1/1     upheaval = 1/1     verdant_embrace = 1/1     volcanism = 1/1     warp = 1/1     zephyr = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: [pelagos]  sets: signet_of_the_priory = 1  gear: ankerkettengrtung = 1     bindung_der_bindung = 1     brillantes_leuchtfeuer = 1     drachenreiterschiftung_des_kuriers = 1     ewiggeschmiedeter_dolch = 1     fetzer_des_zerstrers = 1     gildenwappenrock = 1     halbdunkle_reifschtzer = 1     knochengeschnitzter_reif = 1     koagulumkrass = 1     kokonbrut_von_arakara = 1     notbremsenanhnger = 1     pollenfngertreter = 1     schreiter_des_fackeltrgers = 1     siegel_des_priorats = 1     signet_of_the_priory = 1     umhang_des_geheimnisbaggers = 1     unschmelzbarer_helm_des_eisenarbeiters = 1  legendaries: none  itemIDs: 133374, 159386, 211006, 211022, 211041, 212030, 215133, 219187, 219308, 219314, 221065, 221077, 221174, 221179, 222439, 223293, 5976  settings: aoe = 3     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = false     maxTime = 20     nameplateRange = 30     nameplates = false     noFeignedCooldown = false     package = Augmentation     petbased = false     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     fire_breath_fixed = 0     manage_attunement = false     manage_source_of_magic = false     use_clipping = false     use_early_chain = false     use_unravel = true     use_verdant_embrace = false  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     funnel = false      interrupts = true      mode = automatic      potions = false   keybinds:      action_return          = F4  [04]     azure_strike           = 5   [01]     blessing_of_the_bronze = F2  [04]     blistering_scales      = 6   [01]     breath_of_eons         = M3  [01]     deep_breath            =     disintegrate           =     dragonrage             =     ebon_might             = F   [01]     emerald_blossom        = 3   [05]     eruption               = M5  [01]     eternity_surge         =     fire_breath            = E   [01]     fury_of_the_aspects    = S4  [05]     healthstone            =     hover                  = Q   [01]     landslide              = SF  [05]     living_flame           = M4  [01]     obsidian_scales        = 1   [05]     oppressing_roar        = V   [05]     prescience             = 7   [01]     pyre                   =     quell                  = C   [05]     renewing_blaze         = 4   [05]     sense_power            = F3  [04]     shattering_star        =     sleep_walk             =     source_of_magic        = F1  [04]     spatial_paradox        =     tail_swipe             = SM4 [04]     time_spiral            = S3  [05]     tip_the_scales         = SE  [01]     unravel                = SR  [05]     upheaval               = R   [01]     verdant_embrace        = 2   [05]     wing_buffet            = SM5 [04]     zephyr                 = S2  [05]  warnings: none   targets:  Nameplates are enabled.     dmg          - Creature-0-1465-1822-28661-129371-0001E7C5D7 (moving)   - Checking nameplate7 [ Creature-0-1465-1822-28661-129372-0004E7C5D7 ] #Schwarzteerbomberin.     dmg          - Creature-0-1465-1822-28661-129372-0004E7C5D7    - Checking nameplate6 [ Creature-0-1465-1822-28661-129369-0000E7C5D7 ] #Eisenfluträuber.     dmg          - Creature-0-1465-1822-28661-129369-0000E7C5D7    - Checking nameplate5 [ Creature-0-1465-1822-28661-129371-000167C5D7 ] #Springflutschredderin.     dmg          - Creature-0-1465-1822-28661-129371-000167C5D7 (moving)   player_buffs:    360827 - blistering_scales                        -  20 - 499.41    403264 - black_attunement                         -   1 - 3600.00    361021 - sense_power                              -   1 - 3600.00     72221 - *lotterieglck                            -   3 - 3600.00    225788 - zeichen_des_gesandten                    -   1 - 3600.00    461957 - satt                                     -   1 - 3282.76    381748 - blessing_of_the_bronze_evoker            -   1 - 286.00    415603 - eingeschlossenes_schicksal               -   1 - 3600.00    452146 - *eiersack                                -   3 - 33.26     448730 - *autoritt_der_strahlenden_macht          -   1 - 4.63      370901 - leaping_flames                           -   1 - 25.26     410263 - infernos_blessing                        -   1 - 0.17      458525 - ascendance_mastery                       -   3 - 11.50     408005 - momentum_shift                           -   1 - 3.60      459878 - *goldene_gelegenheit                     -   1 - 16.81       1126 - mark_of_the_wild                         -   1 - 3514.31      6673 - battle_shout                             -   1 - 3450.75    455656 - *dunkle_umarmung                         -   1 - 14.29   player_debuffs:  target_buffs:  target_debuffs:    357209 - fire_breath_dot                          -   1 - 15.05   previous_spells:    1 - eruption    2 - prescience    3 - eruption    4 - eruption    5 - prescience   New Recommendations for [ Primary ] requested at 07:48:34 ( 635.41 ); using built-in ( Augmentation ) priority. *** START OF NEW DISPLAY: Primary *** Purged 142 marked values in 0.06ms. Essence increased to 0.00 from passive regen.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.50, Casting: 0.00 ).      Resources: essence[ 3.00 / 5.00 ], mana[ 2500000.00 / 2500000.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Augmentation - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   variable ( precombat - 1 )         spam_heal #1 [Augmentation:precombat:1]; conditions = PASS: NONE          - value = nil: NONE          - variable.spam_heal[1] will check this script entry ( Augmentation:precombat:1 )         Time spent on this action:  0.03ms         TimeData:Augmentation-precombat-1:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02)                  2.   variable ( precombat - 2 )         minimum_opener_delay #1 [Augmentation:precombat:2]; conditions = PASS: NONE          - value = nil: NONE          - variable.minimum_opener_delay[0] will check this script entry ( Augmentation:precombat:2 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  3.   variable ( precombat - 3 )         opener_delay #1 [Augmentation:precombat:3]; conditions = FAIL: ! talent.interwoven_threads.enabled[true]          - value = 0: variable.minimum_opener_delay[0]          - variable.opener_delay[0] will check this script entry ( Augmentation:precombat:3 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-3:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  4.   variable ( precombat - 4 )         opener_delay #2 [Augmentation:precombat:4]; conditions = PASS: talent.interwoven_threads.enabled[true]          - value = 0: variable.minimum_opener_delay[0.00] + variable.opener_delay[0.00]          - variable.opener_delay[0] will check this script entry ( Augmentation:precombat:4 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-4:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  5.   variable ( precombat - 5 )         opener_cds_detected #1 [Augmentation:precombat:5]; conditions = PASS: NONE          - value = nil: NONE          - variable.opener_cds_detected[0] will check this script entry ( Augmentation:precombat:5 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-5:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  6.   variable ( precombat - 6 )         trinket_1_exclude #1 [Augmentation:precombat:6]; conditions = PASS: NONE          - value = false: trinket.t1.is.ruby_whelp_shell[false] | trinket.t1.is.whispering_incarnate_icon[false]          - variable.trinket_1_exclude[false] will check this script entry ( Augmentation:precombat:6 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-6:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  7.   variable ( precombat - 7 )         trinket_2_exclude #1 [Augmentation:precombat:7]; conditions = PASS: NONE          - value = false: trinket.t2.is.ruby_whelp_shell[false] | trinket.t2.is.whispering_incarnate_icon[false]          - variable.trinket_2_exclude[false] will check this script entry ( Augmentation:precombat:7 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-7:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  8.   variable ( precombat - 8 )         trinket_1_manual #1 [Augmentation:precombat:8]; conditions = PASS: NONE          - value = false: trinket.t1.is.nymues_unraveling_spindle[false] | trinket.t1.is.spymasters_web[false] | trinket.t1.is.treacherous_transmitter[false]          - variable.trinket_1_manual[false] will check this script entry ( Augmentation:precombat:8 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-8:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  9.   variable ( precombat - 9 )         trinket_2_manual #1 [Augmentation:precombat:9]; conditions = PASS: NONE          - value = false: trinket.t2.is.nymues_unraveling_spindle[false] | trinket.t2.is.spymasters_web[false] | trinket.t2.is.treacherous_transmitter[false]          - variable.trinket_2_manual[false] will check this script entry ( Augmentation:precombat:9 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-9:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  10.  variable ( precombat - 10 )         trinket_1_ogcd_cast #1 [Augmentation:precombat:10]; conditions = PASS: NONE          - value = false: trinket.t1.is.beacon_to_the_beyond[false]          - variable.trinket_1_ogcd_cast[false] will check this script entry ( Augmentation:precombat:10 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-10:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  11.  variable ( precombat - 11 )         trinket_2_ogcd_cast #1 [Augmentation:precombat:11]; conditions = PASS: NONE          - value = false: trinket.t2.is.beacon_to_the_beyond[false]          - variable.trinket_2_ogcd_cast[false] will check this script entry ( Augmentation:precombat:11 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-11:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  12.  variable ( precombat - 12 )         trinket_1_buffs #1 [Augmentation:precombat:12]; conditions = PASS: NONE          - value = false: trinket.t1.has_use_buff[false] | ( trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false] | trinket.t1.has_use_buff[false] ) & ! variable.trinket_1_exclude[false]          - variable.trinket_1_buffs[false] will check this script entry ( Augmentation:precombat:12 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-12:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  13.  variable ( precombat - 13 )         trinket_2_buffs #1 [Augmentation:precombat:13]; conditions = PASS: NONE          - value = false: trinket.t2.has_use_buff[false] | ( trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false] | trinket.t2.has_use_buff[false] ) & ! variable.trinket_2_exclude[false]          - variable.trinket_2_buffs[false] will check this script entry ( Augmentation:precombat:13 )         Time spent on this action:  0.03ms         TimeData:Augmentation-precombat-13:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02)                  14.  variable ( precombat - 14 )         trinket_1_sync #1 [Augmentation:precombat:14]; conditions = FAIL: variable.trinket_1_buffs[false] & ( trinket.t1.cooldown.duration[120.00] % 120 = 0 )          - value = 1: 1          - variable.trinket_1_sync[0.5] will check this script entry ( Augmentation:precombat:14 )         Time spent on this action:  0.03ms         TimeData:Augmentation-precombat-14:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  15.  variable ( precombat - 15 )         trinket_2_sync #1 [Augmentation:precombat:15]; conditions = FAIL: variable.trinket_2_buffs[false] & ( trinket.t2.cooldown.duration[0.00] % 120 = 0 )          - value = 1: 1          - variable.trinket_2_sync[0.5] will check this script entry ( Augmentation:precombat:15 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-15:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  16.  variable ( precombat - 16 )         trinket_priority #1 [Augmentation:precombat:16]; conditions = FAIL: ! variable.trinket_1_buffs[false] & variable.trinket_2_buffs[false] & ( trinket.t2.has_cooldown[false] & ! variable.trinket_2_exclude[false] | ! trinket.t1.has_cooldown[false] ) | variable.trinket_2_buffs[false] & ( ( trinket.t2.cooldown.duration[0.00] / trinket.t2.buff_duration[0.01] ) * ( 0.5 + trinket.t2.has_use_buff[false] * 3 + trinket.t2.has_use_buff[false] ) * ( variable.trinket_2_sync[0.50] ) ) > ( ( trinket.t1.cooldown.duration[120.00] / trinket.t1.buff_duration[0.01] ) * ( 0.5 + trinket.t1.has_use_buff[false] * 3 + trinket.t1.has_use_buff[false] ) * ( variable.trinket_1_sync[0.50] ) * ( 1 + ( ( trinket.t1.ilvl[437.00] - trinket.t2.ilvl[437.00] ) / 100 ) ) )          - value = 2: 2          - variable.trinket_priority[1] will check this script entry ( Augmentation:precombat:16 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-16:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  17.  variable ( precombat - 17 )         damage_trinket_priority #1 [Augmentation:precombat:17]; conditions = PASS: ! variable.trinket_1_buffs[false] & ! variable.trinket_2_buffs[false] & trinket.t2.ilvl[437.00] >= trinket.t1.ilvl[437.00]          - value = 2: 2          - variable.damage_trinket_priority[2] will check this script entry ( Augmentation:precombat:17 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-17:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  18.  variable ( precombat - 18 )         trinket_priority #2 [Augmentation:precombat:18]; conditions = FAIL: ( trinket.t1.is.nymues_unraveling_spindle[false] | trinket.t2.is.nymues_unraveling_spindle[false] ) & ( variable.trinket_1_buffs[false] & variable.trinket_2_buffs[false] )          - value = 2: 2          - variable.trinket_priority[1] will check this script entry ( Augmentation:precombat:18 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-18:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  19.  variable ( precombat - 19 )         hold_empower_for #1 [Augmentation:precombat:19]; conditions = PASS: NONE          - value = nil: NONE          - variable.hold_empower_for[6] will check this script entry ( Augmentation:precombat:19 )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-19:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  20.  aberrant_spellforge ( precombat - 20 ) - IsUsableItem item 212451 and nil         Time spent on this action:  0.04ms         TimeData:Augmentation-precombat-20:aberrant_spellforge:0.04:Ability Known, Enabled(0.04)                  21.  blistering_scales ( precombat - 21 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-21:blistering_scales:0.02:Ability Known, Enabled(0.02)                  22.  living_flame ( precombat - 22 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-precombat-22:living_flame:0.02:Ability Known, Enabled(0.02)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Augmentation - precombat ].          Processing default action list [ Augmentation - default ].                  Current recommendation was NO ACTION at +10.00s.                  23.  variable ( default - 1 )         temp_wound #1 [Augmentation:default:1]; conditions = PASS: NONE          - value = 0: debuff.temporal_wound.remains[0]          - variable.temp_wound[0] will check this script entry ( Augmentation:default:1 )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-1:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  24.  variable ( default - 2 )         pool_for_id #1 [Augmentation:default:2]; conditions = PASS: talent.imminent_destruction.enabled[true]          - value = false: cooldown.breath_of_eons.remains[120.00] < 8 & essence.deficit[2.00] >= 1 & ! buff.essence_burst.up[false]          - variable.pool_for_id[false] will check this script entry ( Augmentation:default:2 )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-2:variable:0.02:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  25.  prescience ( default - 3 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-3:prescience:0.02:Ability Known, Enabled(0.02)                  26.  potion ( default - 4 ) - ability disabled ( toggle potions )         Time spent on this action:  0.71ms         TimeData:Augmentation-default-4:potion:0.71:Ability Known, Enabled(0.71)                  27.  call_action_list:ebon_logic ( default - 5 )         Time-sensitive Criteria for ebon_logic deferred at +0.00 - ( buff.ebon_might_self.remains[0.00] - cast_time[0.00] ) <= buff.ebon_might_self.duration[11.20] * 0.4         Action list (ebon_logic) was found.         + ebon_logic         Current recommendation was NO ACTION at +10.00s.                  28.  ebon_might ( ebon_logic - 1 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-ebon_logic-1:ebon_might:0.02:Ability Known, Enabled(0.02)         Exiting ebon_logic with recommendation of NO ACTION at +10.00s.         Returned from list (ebon_logic), current recommendation is NO ACTION (+10.00).         - ebon_logic                  29.  run_action_list:opener_filler ( default - 6 )         Criteria for opener_filler FAIL at +0.00 - variable.opener_delay[0.00] > 0 & boss[true]                  30.  call_action_list:items ( default - 7 )         There is no criteria for items.         Action list (items) was found.         + items         Current recommendation was NO ACTION at +10.00s.                  31.  nymues_unraveling_spindle ( items - 1 ) - IsUsableItem item 208615 and nil         Time spent on this action:  0.03ms         TimeData:Augmentation-items-1:nymues_unraveling_spindle:0.03:Ability Known, Enabled(0.03)                  32.  aberrant_spellforge ( items - 2 ) - IsUsableItem item 212451 and nil         Time spent on this action:  0.04ms         TimeData:Augmentation-items-2:aberrant_spellforge:0.04:Ability Known, Enabled(0.04)                  33.  treacherous_transmitter ( items - 3 ) - IsUsableItem item 221023 and nil         Time spent on this action:  0.03ms         TimeData:Augmentation-items-3:treacherous_transmitter:0.03:Ability Known, Enabled(0.03)                  34.  spymasters_web ( items - 4 ) - IsUsableItem item 220202 and nil         Time spent on this action:  0.03ms         TimeData:Augmentation-items-4:spymasters_web:0.03:Ability Known, Enabled(0.03)                  Substituting signet_of_the_priory for Siegel des Priorats action; it is otherwise not included in the priority.         35.  signet_of_the_priory ( items - 5 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.06ms         TimeData:Augmentation-items-5:signet_of_the_priory:0.06:Ability Known, Enabled(0.06)                  Bypassing 'trinket2' action because the equipped trinket #2 is not usable.                  36.  trinket2 ( items - 6 )         Time spent on this action:  0.02ms         TimeData:Augmentation-items-6:trinket2:0.02:Ability Known, Enabled(0.02)                  Substituting signet_of_the_priory for Siegel des Priorats action; it is otherwise not included in the priority.         37.  signet_of_the_priory ( items - 7 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.05ms         TimeData:Augmentation-items-7:signet_of_the_priory:0.05:Ability Known, Enabled(0.05)                  Bypassing 'trinket2' action because the equipped trinket #2 is not usable.                  38.  trinket2 ( items - 8 )         Time spent on this action:  0.01ms         TimeData:Augmentation-items-8:trinket2:0.01:Ability Known, Enabled(0.01)                  39.  main_hand ( items - 9 )         The action (main_hand) is unusable at (0.00 + 0.00) because ability.usable was false.         Time spent on this action:  0.03ms         TimeData:Augmentation-items-9:main_hand:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00)         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from list (items), current recommendation is NO ACTION (+10.00).         - items                  40.  deep_breath ( default - 8 ) - talent [ breath_of_eons ] disallowed         Time spent on this action:  0.04ms         TimeData:Augmentation-default-8:deep_breath:0.04:Ability Known, Enabled(0.04)                  41.  tip_the_scales ( default - 9 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-9:tip_the_scales:0.02:Ability Known, Enabled(0.02)                  42.  call_action_list:fb ( default - 10 )         Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - cooldown.time_skip.up[false] & talent.time_skip.enabled[true] & ! talent.interwoven_threads.enabled[true] | empowering.fire_breath[false]                  43.  tip_the_scales ( default - 11 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-11:tip_the_scales:0.02:Ability Known, Enabled(0.02)                  44.  upheaval ( default - 12 )         The action (upheaval) is usable at (0.00 + 0.91).          - the action is ready before the current recommendation (at +0.91 vs. +10.00).          - this entry's criteria FAILS: target.time_to_die[8.09] > cast_time[0.91] + 0.2 & buff.ebon_might_self.remains[0.00] > cast_time[0.91] & cooldown.time_skip.up[false] & talent.time_skip.enabled[true] & ! talent.interwoven_threads.enabled[true]         There were no recheck events to check.         Time spent on this action:  0.15ms         TimeData:Augmentation-default-12:upheaval:0.15:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.04):Pre-Recheck(0.02):Post-Recheck Times(0.01):Post Recheck(0.00)                  45.  breath_of_eons ( default - 13 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-13:breath_of_eons:0.02:Ability Known, Enabled(0.02)                  46.  breath_of_eons ( default - 14 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-14:breath_of_eons:0.02:Ability Known, Enabled(0.02)                  47.  living_flame ( default - 15 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-15:living_flame:0.02:Ability Known, Enabled(0.02)                  48.  living_flame ( default - 16 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-16:living_flame:0.02:Ability Known, Enabled(0.02)                  49.  call_action_list:fb ( default - 17 )         Time-sensitive Criteria for fb deferred at +0.00 - ( raid_event.adds.remains[39.43] > 13 | raid_event.adds['in'][3600.00] > 20 | ( solo[false] | evoker.allied_cds_up[0.00] > 0 ) | ! raid_event.adds.exists[true] ) & ( cooldown.breath_of_eons.remains[120.00] >= variable.hold_empower_for[6.00] | ! talent.breath_of_eons.enabled[true] )         Action list (fb) was found.         + fb         Current recommendation was NO ACTION at +10.00s.                  50.  tip_the_scales ( fb - 1 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-fb-1:tip_the_scales:0.01:Ability Known, Enabled(0.01)                  51.  fire_breath ( fb - 2 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-fb-2:fire_breath:0.02:Ability Known, Enabled(0.02)                  52.  fire_breath ( fb - 3 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-fb-3:fire_breath:0.02:Ability Known, Enabled(0.02)                  53.  fire_breath ( fb - 4 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-fb-4:fire_breath:0.01:Ability Known, Enabled(0.01)                  54.  fire_breath ( fb - 5 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-fb-5:fire_breath:0.02:Ability Known, Enabled(0.02)                  55.  fire_breath ( fb - 6 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-fb-6:fire_breath:0.02:Ability Known, Enabled(0.02)                  56.  fire_breath ( fb - 7 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-fb-7:fire_breath:0.01:Ability Known, Enabled(0.01)                  57.  fire_breath ( fb - 8 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-fb-8:fire_breath:0.02:Ability Known, Enabled(0.02)         Exiting fb with recommendation of NO ACTION at +10.00s.         Returned from list (fb), current recommendation is NO ACTION (+10.00).         - fb                  58.  upheaval ( default - 18 )         The action (upheaval) is usable at (0.00 + 0.91).          - the action is ready before the current recommendation (at +0.91 vs. +10.00).         hold_empower_for #1 [Augmentation:precombat:19]; conditions = PASS: NONE          - value = nil: NONE          - this entry's criteria FAILS: target.time_to_die[8.09] > cast_time[0.91] + 0.2 & buff.ebon_might_self.remains[0.00] > cast_time[0.91] & ( raid_event.adds.remains[38.53] > 13 | ! raid_event.adds.exists[true] | raid_event.adds['in'][3600.00] > 20 ) & ( ! talent.molten_embers.enabled[true] | dot.fire_breath_damage.ticking[true] ) & ( cooldown.breath_of_eons.remains[120.00] >= variable.hold_empower_for[6.00] | ! talent.breath_of_eons.enabled[true] )         There were no recheck events to check.         Time spent on this action:  0.13ms         TimeData:Augmentation-default-18:upheaval:0.13:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.05):Post-Recheck Times(0.01):Post Recheck(0.00)                  59.  time_skip ( default - 19 ) - talent [ interwoven_threads ] disallowed         Time spent on this action:  0.01ms         TimeData:Augmentation-default-19:time_skip:0.01:Ability Known, Enabled(0.01)                  60.  emerald_blossom ( default - 20 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-default-20:emerald_blossom:0.02:Ability Known, Enabled(0.02)                  61.  eruption ( default - 21 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-default-21:eruption:0.01:Ability Known, Enabled(0.01)                  62.  blistering_scales ( default - 22 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-default-22:blistering_scales:0.01:Ability Known, Enabled(0.01)                  63.  run_action_list:filler ( default - 23 )         There is no criteria for filler.         Action list (filler) was found.         + [filler]         Current recommendation was NO ACTION at +10.00s.                  64.  living_flame ( filler - 1 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.02ms         TimeData:Augmentation-filler-1:living_flame:0.02:Ability Known, Enabled(0.02)                  65.  emerald_blossom ( filler - 2 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-filler-2:emerald_blossom:0.01:Ability Known, Enabled(0.01)                  66.  verdant_embrace ( filler - 3 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-filler-3:verdant_embrace:0.01:Ability Known, Enabled(0.01)                  67.  azure_strike ( filler - 4 ) - ability disabled ( empowerment: upheaval )         Time spent on this action:  0.01ms         TimeData:Augmentation-filler-4:azure_strike:0.01:Ability Known, Enabled(0.01)         Exiting filler with recommendation of NO ACTION at +10.00s.         Returned from list (filler), current recommendation is NO ACTION (+10.00).         - [filler]         Added filler to blocklist as it was called via RAL.         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Augmentation - default ].     Recommendation is NO ACTION at 0.00 + 10.00.     Recommendation #1 is NO ACTION at 10.00s (10.00s).     Resources: Resources: essence[ 3.00 / 5.00 | 5.00 @ [2 - none] 9.57 ], mana[ 2500000.00 / 2500000.00 | 2500000.00 @ [1 - actual] 0.00 ]     Time spent generating recommendations:  4.66ms

### Additional Information

The Version Hekili-v11.0.2-1.0.10b worked better

**Comment by Hekili** [comment]
~~Please post your snapshot to Pastebin and provide the link so that it is readable.  Thanks!~~

I've updated the priority to ensure Upheaval casts can always be finished.
