### ISSUE TITLE
[REC] Unravel not being recommended

### ISSUE THREAD

**Issue by PinkLionArt** [Hekili/hekili#3790]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Devastation

### Describe the Issue

Yesterday when clearing heroic raid on my devastation evoker I specifically talented into Unravel for the bosses with a shield (eg: Silken Court) and made sure that the "recommend unravel" option was turned on, as were my interrupts. This feature worked fine for me in the past, but did not recommend unravel for me at all. I was able to use the ability as the boss did have a shield - it just wasn't shown in Hekili. I also wasn't able to find unravel in the priority list.

### How to Reproduce

Log into your devastation evoker
Talent into Unravel
Target an enemy with a shield
See that it is not being recommended

### Snapshot (Link)

I'm hoping this is simply missing in the APL as I couldn't make a snapshot during raid. Will provide one if necessary

**Comment by Hekili** [comment]
This will be addressed in the next release.
