### ISSUE TITLE
[BUG] LUA Errors on Fury Warrior

### ISSUE THREAD

**Issue by joshjau** [Hekili/hekili#3794]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

just saw a few warning error codes in the hekili warning section. unsure if these are current or historical.

### How to Reproduce

1. Load up Fury Warrior with talent tree: CgEAmidFBOBFf5oKuZ7r/WeW7MAAAAAAAAAgRDMDYMWmhxAzCMMjxMzDMMzstNGzMzCmZmZmxMsN8AMmZAAAgwMW2GYBMBzwEYshN
2. see the following lua errors in warning tab of hekili addon:
3. `Unknown debuff in [Fury:slayer_st:5]: slaughterhouse

[string "@Interface/AddOns/Hekili/State.lua"]:5114: in function <Interface/AddOns/Hekili/State.lua:5087>
[string "@Interface/AddOns/Hekili/TheWarWithin/WarriorFury.lua"]:1466: in function `handler'
[string "@Interface/AddOns/Hekili/State.lua"]:6409: in function `RunHandler'
[string "@Interface/AddOns/Hekili/Core.lua"]:1934: in function <Interface/AddOns/Hekili/Core.lua:1464>`

`Attempted to apply unknown aura 'slaughterhouse'.`

I just noticed these, they will not go away, unless they are historical? then i guess its nothing. Thought I would report.

### Player Information (Link)

https://pastebin.com/GCgkhzvi

### Error Messages (Link)

https://pastebin.com/tHepFhSr

### Additional Information

I am in the Patreon channel if any further info is required.

### Contact Information

joshj#2332

**Comment by Hekili** [comment]
Thanks; I'll add the debuff from the Slaughterhouse PvP talent in the next release.
