### ISSUE TITLE
[REC] Mark of Khardros Trinket Failing to Show

### ISSUE THREAD

**Issue by joshjau** [Hekili/hekili#3795]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Fury

### Describe the Issue

The trinket which I asked in the patreon discord channel to be added was, but cannot see it in the dropdown gear/item list and fails to be recommended on fury warrior. 

### How to Reproduce

1. enter game
2. load up fury warrior
3. equip trinket and see.
4. go to item/gear and it is not shown either.

### Snapshot (Link)

https://pastebin.com/8sQdwWRv

### Contact Information

joshj#2332

**Comment by Jacii1121** [comment]
Changing line 876 of items.lua to
`item = 133300,`
fixed it for me.

**Comment by Hekili** [comment]
This will be fixed in next release.
