### ISSUE TITLE
Sunfury Arcane Mage recommending Arcane Orb with Burden of Power UP

### ISSUE THREAD

**Issue by Beltroth** [Hekili/hekili#3796]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Arcane

### Describe the Issue

Once Burden of Power buff is up and I'm about to hit my Arcane Barrage, the addon suggests using Arcane Orb afterward, even though I should instantly have four Arcane Charges back up.
![Screenshot 2024-09-17 061333](https://github.com/user-attachments/assets/c5ce6732-468c-4cfb-a94f-a86adc55cecd)

### How to Reproduce

1.Enter the game as Arcane mage Sunfury
2.Take the standard ST talend build from Icyveins or Wowhead
3.Do the normal rotation until Burden of Power come up
4.The addon will suggest using Arcane Barrage followed with Arcane Orb.

### Snapshot (Link)

https://pastebin.com/TgGYjC87

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ot67Z1vV3KEbCSR8qqt9sR

**Comment by syrifgit** [comment]
Solution incoming.

**Comment by syrifgit** [comment]
That's not how Burden of Power works.

You have burden of power up right now. Consuming this buff (by casting arcane barrage) makes your **_next_** barrage give 4 charges, via a buff called glorious incandescence.

The addon is behaving correctly.

**Comment by Beltroth** [comment]
Yeah, I understand that, but the Burden of Power and, respectively, Glorious Incandescence buffs are triggered by the same Arcane Barrage you cast when Burden of Power is triggered. Hence, Arcane Orb shouldn't be recommended because when I do the rotation, Arcane Orb disappears from the recommendations after Arcane Barrage has been cast.

**Comment by syrifgit** [comment]
Can you recreate the situation, cast the arcane barrage, then wait and get a snapshot so I can see what you're describing?

**Comment by Beltroth** [comment]
Sure can, i think maybe thats a typo on the game talent Glorius Incandescence ? is should be somthing like "Consuming Burden of Power causes Arcane Barrage to grant 4 Arcane Charges and call down a storm of 4 meteorites on its target." without the "Next"part. Trying to recreate the snapshot give me a sec.

**Comment by Beltroth** [comment]
https://pastebin.com/azxfHQUh

**Comment by Beltroth** [comment]
It's actually correct the way it is described, but when you have Burden of Power, you want to cast Arcane Barrage anyway because it gives 4 Arcane Charges through Glorious Incandescence and casts the Meteorites. So, Arcane Orb shouldn't be recommended, or am I missing something?

**Comment by PauloCamposFilho** [comment]
> Can you recreate the situation, cast the arcane barrage, then wait and get a snapshot so I can see what you're describing?

If you have Burden of Power (not Glorious Incantation), and you cast ABarr, you are refunded the 4 charges. This is just the way the Burden of Power buff works now. Presumably this oddity was introduced when they hotfixed being able to double-dip Burden of Power with the ABlast+ABarr combo. But as it is now, casting a Barrage when you have Burden of Power causes both the Burden of Power AND Glorious Incantation to fire off the same Barrage cast (you can verify this on the fact the charges are refunded and the meteorites are triggered)

**Comment by Beltroth** [comment]
> > Can you recreate the situation, cast the arcane barrage, then wait and get a snapshot so I can see what you're describing?
> 
> If you have Burden of Power (not Glorious Incantation), and you cast ABarr, you are refunded the 4 charges. This is just the way the Burden of Power buff works now. Presumably this oddity was introduced when they hotfixed being able to double-dip Burden of Power with the ABlast+ABarr combo. But as it is now, casting a Barrage when you have Burden of Power causes both the Burden of Power AND Glorious Incantation to fire off the same Barrage cast (you can verify this on the fact the charges are refunded and the meteorites are triggered)

Yeah, that's exactly what confused me. So, isn't it better to cast Arcane Blast to consume Burden of Power and then Arcane Barrage to trigger the arcane charge back?

**Comment by Beltroth** [comment]
![Senza titolo](https://github.com/user-attachments/assets/020e917b-3fc6-442e-860c-cac12fde5eb3)

**Comment by syrifgit** [comment]
Okay, so basically the behavior doesn't match the text on the talents anymore?

**Comment by PauloCamposFilho** [comment]
> Okay, so basically the behavior doesn't match the text on the talents anymore?

I'm not sure they ever did, or if the behavior was introduced on the hotfix to not allowing Burden to double-dip anymore, but, yes, that is the situation now.

**Comment by syrifgit** [comment]
Alright, I'll try to fix it this week. Probably won't be tomorrow? We'll see.

**Comment by PauloCamposFilho** [comment]
> Alright, I'll try to fix it this week. Probably won't be tomorrow? We'll see.

Can I suggest you to take a look at the new APL for Arcane? It is based on this behavior, might kill 2 birds with 1 update

**Comment by syrifgit** [comment]
So to confirm,

When you have burden, casting barrage will consume burden, give you glorious, and consume glorious to refund charges, all in a single barrage?

**Comment by PauloCamposFilho** [comment]
> So to confirm,
> 
> When you have burden, casting barrage will consume burden, give you glorious, and consume glorious to refund charges, all in a single barrage?

Correct.

**Comment by Hekili** [comment]
So, I'm left seeking clarification: it sounds like the priority itself is showing correctly, but it's possible that the addon isn't handling BoP/GI when it emulates using it in your recommendations, so the number of Arcane Charges and/or buffs after casting Arcane Barrage is not accurate until you've *actually* cast Arcane Barrage and consumed BoP/GI.  

Are you seeing the recommendations change suddenly when you Arcane Barrage with BoP/GI (or both) are up and Arcane Barrage is recommended?  If so, that just means I need to update the Arcane Barrage handler to consume both buffs.

edit: Nevermind, I can see that Arcane Barrage already consumes BOP and generates 4 Arcane Charges thanks to Syrif's edits a couple weeks back.

**Comment by syrifgit** [comment]
> So, I'm left seeking clarification: it sounds like the priority itself is showing correctly, but it's possible that the addon isn't handling BoP/GI when it emulates using it in your recommendations, so the number of Arcane Charges and/or buffs after casting Arcane Barrage is not accurate until you've _actually_ cast Arcane Barrage and consumed BoP/GI.
> 
> Are you seeing the recommendations change suddenly when you Arcane Barrage with BoP/GI (or both) are up and Arcane Barrage is recommended? If so, that just means I need to update the Arcane Barrage handler to consume both buffs.
> 
> edit: Nevermind, I can see that Arcane Barrage already consumes BOP and generates 4 Arcane Charges thanks to Syrif's edits a couple weeks back.

I will still review it later this week to be sure that it is doing the correct behaviour, as I am not so sure now. I definitely wrote it from the perspective of the talents as written.

**Comment by Beltroth** [comment]
Arcane Orb gets recommended when the addon tells you to Barrage during BoP. With GI, it works as intended, but the Barrage during BoP consumes both BoP and GI, so Arcane Orb shouldn't be recommended afterward
![Screenshot 2024-09-17 180756](https://github.com/user-attachments/assets/d2e79c78-6a38-47b3-ae4d-26eae30e3be1)
![Screenshot 2024-09-17 180813](https://github.com/user-attachments/assets/5983d613-0f3b-40a5-ad5a-cc40f55c3789)

**Comment by syrifgit** [comment]
> https://pastebin.com/azxfHQUh

So this snapshot you got for me, you casted barrage, it showed arcane orb, you waited then it swapped to blast?

**Comment by Beltroth** [comment]
> > https://pastebin.com/azxfHQUh
> 
> So this snapshot you got for me, you casted barrage, it showed arcane orb, you waited then it swapped to blast?

Yeah I casted barrage and waited, the orb was still next but as soon as barrage landed and got the charges back it disappeared and then arcane blast show up instead of orb

**Comment by syrifgit** [comment]
> > > https://pastebin.com/azxfHQUh
> > 
> > 
> > So this snapshot you got for me, you casted barrage, it showed arcane orb, you waited then it swapped to blast?
> 
> Yeah I casted barrage and waited, the orb was still next but as soon as barrage landed and got the charges back it disappeared and then arcane blast show up instead of orb

I am curious if this is still happening for you now that the burden of power bug has been fixed on the Blizzard side? If so I will do something for it soon. I have a line of communication open with Porom now to answer my question about more technical stuff inside the spec.

**Comment by Beltroth** [comment]
Hey Syrif, thanks for the reply. I've tested it now and it still happens during the BoP buff

**Comment by syrifgit** [comment]
Confirmed the behaviour with Porom, PR pending.

https://github.com/Hekili/hekili/pull/3813
