### ISSUE TITLE
[REC] Augmentation Empowered Spells, CDs

### ISSUE THREAD

**Issue by tpfleck** [Hekili/hekili#3797]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

While in combat during M0 w/ adds (non-boss), it doesn't recommend my empowerment spells, tip the scales, or breath of eons. The second I start fighting a boss, it recommends everything properly. When I fighting non-boss dummies, it  recommends the appropriate rotation.

My group is done with M0s until starting M+ tomorrow, so I'm not able to upgrade a Snapshot of it actively happening at the moment. Will paste once I run into the issue again. 

### How to Reproduce

1. Enter game as Aug
2. Enter a M0 and start fighting some non-boss mobs
3. Witness it doesn't recommend tip the scales, empowerments, or breath. 

### Snapshot (Link)

[pastebin](https://pastebin.com/QngRZSYg)

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/5Rkt5ma9JJccdSmPGLGHmJ

**Comment by ghost** [comment]
Unfortunately, it still doesn't work for me too :(

**Comment by GitBearded** [comment]
> Unfortunately, it still doesn't work for me too :(

Did you by chance have “boss encounters only” checked in your settings?

**Comment by Hekili** [comment]
Need to take a snapshot when your CDs/rotation is *not* working in M+.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by tpfleck** [comment]
Updated - https://pastebin.com/QngRZSYg

**Comment by tpfleck** [comment]
https://pastebin.com/QngRZSYg

**Comment by ghost** [comment]
> > Unfortunately, it still doesn't work for me too :(
> 
> Did you by chance have “boss encounters only” checked in your settings?

No :(

**Comment by tpfleck** [comment]
> > Unfortunately, it still doesn't work for me too :(
> 
> Did you by chance have “boss encounters only” checked in your settings?

Also no

**Comment by ghost** [comment]
May this helps, Version Hekili-v11.0.2-1.0.10b works @ trash mobs

**Comment by tpfleck** [comment]
Thanks Levion, I'll look at that until this gets updated.

**Comment by syrifgit** [comment]
`toggles: cooldowns = false`

Your cooldowns are disabled which almost certainly includes atleast some of those abilities. 

Your snapshot also doesn't really help because it only shows 1 icon, so we cannot see any logic past the point where it chose to cast prescience, and the abilities you are concerned about are after prescience in the list. Get a snapshot showing 3+ icons.

**Comment by Irenside** [comment]
It happened multiple times on this run. Not sure how snapshots work so got three. v11.0.2-1.0.10b is the only version that works correctly:

https://pastebin.com/AMyS2JfZ
https://pastebin.com/9z4GA5hk
https://pastebin.com/aaPsiiEd

Thanks!

**Comment by syrifgit** [comment]
Looks like there are already multiple changes/fixes in place for the next addon update, hold off until then.

**Comment by syrifgit** [comment]
Next version has been released and should be on places like Curseforge soon. Please test once you can update to the newest version.

https://github.com/Hekili/hekili/releases/tag/v11.0.2-1.0.15a

**Comment by Hekili** [comment]
(1.0.15a)

**Comment by ghost** [comment]
I think i have found the problem, when I use the buff Sense Power, then Breath of Eons, Upheavel and Fire Breath are no longer displayed... with the buff switched off everything works as it should.

Thanks for ur Time, PS i use the newest Version v11.0.2-1.0.16

**Comment by Irenside** [comment]
016 is still not recommending the empowered spells right after ebon might. If I press an empowered spell when it doesn't tell me to but it's the right time, the display will switch to showing it immediately. Also, fire breath is always being recommended at level 3, it was suggesting level 1 previously to take advantage of molten embers. One trash and one boss snapshot below.

https://pastebin.com/nsDhSw7S
https://pastebin.com/1UYFbMCM

It worked correctly 90% of the dungeon and my dps was much better. Thanks again.

**Comment by saltmastergeneral** [comment]
016a also does not seem to be reccing yet I assume he was fixing the lua stuff but I am on dummy ST not getting recced Tip or any empowered spells when breath of eons is off of CD

**Comment by notoriousmonster** [comment]
Experiencing issues after updating, empowered spells not being recommended on Ulgarax at the moment, no breath of eons, etc to keep Ebon Might up

**Comment by Irenside** [comment]
016a was hitching also, but when I disabled Sense Power, it "seemed" to work better (if that's a thing).

Sorry, snapshot's:
1. Sense Power On: https://pastebin.com/6V20KZAZ
2. Sense Power Off: https://pastebin.com/9b7ax0F1
3. Sense Power Off (Boss): https://pastebin.com/CRr6MfQu

**Comment by saltmastergeneral** [comment]
agree turning off Sense Power seems to improve it

**Comment by Hekili** [comment]
Please don't add to the thread without including your own snapshot.  I can't even be certain of what addon version you're on if you don't snapshots.

**Comment by ghost** [comment]
https://pastebin.com/BEKD3qaf

Sometimes it works, sometimes it doesn't like in this snapshot.

**Comment by Irenside** [comment]
**16b**: Tested in follower dungeon, after using Ebon Might, neither empowered spells were suggested. Went back to **10b** and tried the same dungeon with no issues.

16b: https://pastebin.com/yVtJebNr
10b: https://pastebin.com/NNhK0JMA

**Comment by Hekili** [comment]
Thanks for the snapshots.  I have made adjustments; I am not sure I like the Breath of Eons timing but I'm seeing Fire Breath and Upheaval more.  Please try v1.0.16c.

**Comment by Irenside** [comment]
Edited - See below

**Comment by Irenside** [comment]
It was fine for the first dungeon, the 2nd one I did it went back to the old behavior.

https://pastebin.com/rF2GNCGR
https://pastebin.com/1J9htBKY (No empowered spells for length of EM)

**Comment by Hekili** [comment]
With Sense Power active, the addon waits to see allied CDs pop before FB / BoE / Upheaval, but I'll relax those requirements.
