### ISSUE TITLE
[FEATURE] Add "target.time_to_die" to Abilities options.

### ISSUE THREAD

**Issue by sixsi** [Hekili/hekili#3798]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

![image](https://github.com/user-attachments/assets/f43145aa-9a72-460e-88cf-41c3a50c3832)

Would be really useful  and helpful to add an option to make abilities to not trigger / not be shown if target is gonna die in X seconds. You could add the same sliders for that like "minimum / maximum targets" on the screenshot but with like "target time to die". Right now i have to customize every ability entry i want in action lists which takes tens of minutes after every update. I'd appreciate if you add this to Abilities options which saves after updates :) Thanks for your time and work on the addon btw!

**Comment by Hekili** [comment]
Unfortunately, this is too caustic for many priorities, so I tend to manually implement it for abilities where I know the priority is written to safely "fall through" and use something else when these are skipped.

For example, Shadow Priest priority has checks that that all DoTs are up before it uses some nukes.  If you make those abilities require a tme-to-die over several seconds, the addon may be left with nothing to recommend for the last several seconds of each fight.

Which specific abilities, and for which specialization(s), are you generally concerned with?

**Comment by sixsi** [comment]
> Unfortunately, this is too caustic for many priorities, so I tend to manually implement it for abilities where I know the priority is written to safely "fall through" and use something else when these are skipped.
> 
> For example, Shadow Priest priority has checks that that all DoTs are up before it uses some nukes. If you make those abilities require a tme-to-die over several seconds, the addon may be left with nothing to recommend for the last several seconds of each fight.
> 
> Which specific abilities, and for which specialization(s), are you generally concerned with?

I customize DPS cooldowns in general, just so the addon doesn't show them when my target is low HP.

Frost DK:
Pillar of Frost, Reaper's Mark, Empower Rune Weapon, Frostwyrm's Fury, Death and Decay - for these abilities i usually add target.time_to_die >= 12
Remorseless Winter >= 8 since it's kinda press on CD, but not when pack is almost dead.

Survival Hunter:
Coordinated Assault >= 12
Explosive Shot >= 8

Shadow Priest:
Void Eruption, Shadowfiend, Halo >= 15
Void Torrent >= 8

Assasination Rogue:
Deathmark, Kingsbane >= 15
Shiv, Thistle Tea, Vanish >= 10

These are the specs I play the most. You can most likely use my logic to add this option to all the DPS cooldowns to make it easier to use the addon in M+ and open world. My main idea = major DPS cooldowns i put on something like 12-15 sec because i don't want the addon to show them when target is dying soon. Minor DPS cooldowns i put on 8 sec because i still wanna use them on CD, but not when target is almost dead. I hope you got my idea and I'd be happy to test when you have some time to add this :)

**Comment by Hekili** [comment]
So, generally these are abilities impacted by the Cooldowns toggle.  It's possible I could add an option for Major/Minor Cooldowns that disables the toggle below a certain health % of time-to-die.

Note that in AOE scenarios, you *probably* want to use `fight_remains` over `target.time_to_die`.  The former accounts for when *all targets* are expected to die, while `target.time_to_die` only applies to the current target.

**Comment by sixsi** [comment]
> So, generally these are abilities impacted by the Cooldowns toggle. It's possible I could add an option for Major/Minor Cooldowns that disables the toggle below a certain health % of time-to-die.
> 
> Note that in AOE scenarios, you _probably_ want to use `fight_remains` over `target.time_to_die`. The former accounts for when _all targets_ are expected to die, while `target.time_to_die` only applies to the current target.

This sounds like a good option to me :) and thanks for pointing on "fight_remains", didn't know about that. Does it count enemies in range of my abilities or all enemies in current combat? I'm not really good in undestanding sims and stuff, I just take a look at addon code in each ability entry and see what's there :D
So, I'd be happy to test a new option for Major/Minor Cooldowns if you add it and I will happily leave my feedback!

**Comment by davidmann4** [comment]
watch out with fight_remains its often just 30 as it is the inital value, I usually add fight_remains!=30 

you can look at the value by just posting this in the chat ( or create a macro for it ) 

```
/script print( Hekili:GetGreatestTTD() )
```

or just use this weakaura 

```
!WA:2!nA1tVTrru8y5dvDvLiyPgXFAPRcQvjIILDAtkua1ghSJtX5pA9MKwbOTJ3zwVtY6zwnZSjXv9aYIdCoh4cQxYz4IfFaqCGZRI4tqUJqQFc4n764nPATk(q8BEZV3BE)5375uOrPELWLW)0xi4rQakJi2CB7wRTr9trrkFUyZqfLZKgHFcMkddq9TjhPC84IEiLtOJI2J4G7Zq9OUokFbr6ZdW9pXnsQ490yd)oViMR2jMZnVHj8rqurcMPjksGCiSdk3vPW31m5UX6c06USkwuphfs0LOKjxyqy4tL(im)WNTPNNKOUXudrmxiQ3ItzQATQ3Wo0CYXD6PcHtNfTBhIrksNOKVodkbCab1Dxkw5xBz4OaLKlYLSKqSOmQrzuLrhp4lPVXaLG2Tlri34oIrI)vnv)qsN0N4mzuhYbeMQDKNh9OHoRSCBBN22lBzBLOVttckq5pg3wccGZQ9w1B1AyQpC8PyILobWdKHKGG1WsJ4zoQGZ5f6r15K)q9mzC1fQRiPYKlEdfFP5QeLn4Y5M38tnRuEbtLpHL4Gl3v0G)QmW5Ga6BacjK9SULtRWZn7TlxXB27A2KSpnG(qW8w8djsLT9xp3854KU))CYQcc0Lo3nJs4jrza)Lz5gr9StvpNPsermNp1yGrDrkQ(knlZi5Z51)K(j09vrslxFI7(XxZcgaisJArazOJMTreNGbAKNNnaw0SERTASDRJJyJifgdbw5EjTRdilGy9dFxuISD69RZXKFDQWpmxUBQq8h9AGJtemuWoaHdA7)s4nYbV7NnsQgJZidoKlW7kqHd2DKq(gDVZFLkH3mV7RU4Bdq1XaSC5bCXtA(O)5vV6pMAQPA(O)9w36XGqXIdVGPHl(sxeAL7VCLkv(20w13)sHHhTRVYrq6HOm5dnVTBvJrDu9H7zuZJZuHt3GkqMRZzCZ1jyAuV8tR7poOobMWSiD1JYFWmXx)u4yhK7(DH1GmC(g)G3wkVqgGCDqLSxhgQj4KTk)41Yh8Npg8aDg2M(cY7ho7KxM1JJDeW4WZdVZKbfq6IC774fW5c)r7oFA6UZItiPYychJyu92qoBP4PBeF94k)jbjjTvccRRY)kNIHXo91jticjXLZWYbAm6PG4k109WedJx7kXpj(BIBbILEtn5xpYkUNis6BAFwtPjo5f4WUIXgioknfB(4FEv7FaiEI(NR4OBUJwrUtAUJDWW0k1kj84cfkum8JNCnouqCP65XI1c4i8oN5cBnLoig2bwx7oJvVOafDMF)DEEhfka2Xpt8ZmSsaPLQLakraA5AH8RhzZxlerXd3V6E7U3A9X4xS7eAKxG9P4UhKUZ49k8BdNLIp9stztWblLvp8eW(oOXJuOIVo9NCBOvP7jDAVIv96BKFuNT2OdWoGx14yjjWl53RJVQypydl1RF8vZ36Si4en3IM(VMmKYsvdNmMqSNn4xs2zXYvFq5QLo4VF6)b
```

![image](https://github.com/user-attachments/assets/770de3da-32fb-4bc0-b0f5-d8511b18ff5d)


I wonder if fight_remains would work better if we would just calculate `combined_encounter_hp / current_overall_group_dps`

**Comment by sixsi** [comment]
Yeah I did some test dungeon runs with "fight remains" instead of "target.time_to_die" and i can tell it's not really accurate. Probably gonna stick with "target.time_to_die" for now. May be there will be some fix for "fight_remains" in the future :)

**Comment by fzarr** [comment]
I noticed this happening a lot with thistle tea on rogue in m+ - you can be at max energy but itll still start recommending thistle tea towards the end of a pack and mostly wasting it as you could be going straight into another pack. On a raid boss it mostly works fine. 

`this entry's criteria PASSES: ! buff.thistle_tea.up[false] & ( energy.base_deficit[0.00] >= 150 | fight_remains[7.23] < charges[2.00] * 6 )`

Would be great if there was some solution to ignore it for specific abilities.

**Comment by Cheetah714** [comment]
> > Unfortunately, this is too caustic for many priorities, so I tend to manually implement it for abilities where I know the priority is written to safely "fall through" and use something else when these are skipped.
> > For example, Shadow Priest priority has checks that that all DoTs are up before it uses some nukes. If you make those abilities require a tme-to-die over several seconds, the addon may be left with nothing to recommend for the last several seconds of each fight.
> > Which specific abilities, and for which specialization(s), are you generally concerned with?
> 
> I customize DPS cooldowns in general, just so the addon doesn't show them when my target is low HP.
> 
> Frost DK: Pillar of Frost, Reaper's Mark, Empower Rune Weapon, Frostwyrm's Fury, Death and Decay - for these abilities i usually add target.time_to_die >= 12 Remorseless Winter >= 8 since it's kinda press on CD, but not when pack is almost dead.
> 
> Survival Hunter: Coordinated Assault >= 12 Explosive Shot >= 8
> 
> Shadow Priest: Void Eruption, Shadowfiend, Halo >= 15 Void Torrent >= 8
> 
> Assasination Rogue: Deathmark, Kingsbane >= 15 Shiv, Thistle Tea, Vanish >= 10
> 
> These are the specs I play the most. You can most likely use my logic to add this option to all the DPS cooldowns to make it easier to use the addon in M+ and open world. My main idea = major DPS cooldowns i put on something like 12-15 sec because i don't want the addon to show them when target is dying soon. Minor DPS cooldowns i put on 8 sec because i still wanna use them on CD, but not when target is almost dead. I hope you got my idea and I'd be happy to test when you have some time to add this :)

how to add those conditions tho i tired to add them but still recommending it while the trash is dying 
![image](https://github.com/user-attachments/assets/d5aa3760-856f-432c-9eb7-22d284549d8a)

**Comment by syrifgit** [comment]
Why not just use the built in cooldown toggle and have full control over it all the time?

**Comment by Hekili** [comment]
@Cheetah714 You have to add that condition to *every entry* for Pillar of Frost.  Also, that entry is not Enabled (see that the number is grey and the Enabled toggle is empty).

**Comment by Hekili** [comment]
> I wonder if fight_remains would work better if we would just calculate `combined_encounter_hp / current_overall_group_dps`

I could potentially leverage Details API or something for group DPS and all that, but I disagree that `fight_remains` is unreliable.  It takes less than 1.5 seconds of engagement with any enemy before it updates to a real number.

**Comment by Cheetah714** [comment]
> @Cheetah714 You have to add that condition to _every entry_ for Pillar of Frost. Also, that entry is not Enabled (see that the number is grey and the Enabled toggle is empty).

i tried target.time_to_die and fight_remains conditions to my minicd like Pillar of Frost  Reaper's Mark and dnd and remorseless winter but still the rotation show those cd;s when the trash about to die , is there something im doing wrong ?
![image](https://github.com/user-attachments/assets/196fccd2-bfd1-47df-acf1-b3f643503fc3)
![image](https://github.com/user-attachments/assets/321446d9-c2d9-4bb5-bc1a-a50be7fba19d)

**Comment by syrifgit** [comment]
> > @Cheetah714 You have to add that condition to _every entry_ for Pillar of Frost. Also, that entry is not Enabled (see that the number is grey and the Enabled toggle is empty).
> 
> i tried target.time_to_die and fight_remains conditions to my minicd like Pillar of Frost Reaper's Mark and dnd and remorseless winter but still the rotation show those cd;s when the trash about to die , is there something im doing wrong ? ![image](https://private-user-images.githubusercontent.com/117462129/369656214-196fccd2-bfd1-47df-acf1-b3f643503fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjQ5NDQsIm5iZiI6MTcyNjk2NDY0NCwicGF0aCI6Ii8xMTc0NjIxMjkvMzY5NjU2MjE0LTE5NmZjY2QyLWJmZDEtNDdkZi1hY2YxLWIzZjY0MzUwM2ZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwMDI0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTRjNzJhNDY5ZTUzNDJhYzIyMTA2OTkzNjRkMDQwNjk2ZDIxMzQzZTA0YTczNmZkYTk3MDc5OGE0MzFhNTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f5KjbjYp1mrbgne534i0hLggTwsTm72HtDzQfF3anvc) ![image](https://private-user-images.githubusercontent.com/117462129/369656218-321446d9-c2d9-4bb5-bc1a-a50be7fba19d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NjQ5NDQsIm5iZiI6MTcyNjk2NDY0NCwicGF0aCI6Ii8xMTc0NjIxMjkvMzY5NjU2MjE4LTMyMTQ0NmQ5LWMyZDktNGJiNS1iYzFhLWE1MGJlN2ZiYTE5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwMDI0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmQzYTAyOTBjMWZlNzU3NDE5YTM0NzZiZTkzZmZkZTA4ODMyY2Y3M2IxOThjYmQ4NmQ3Mzk5M2IyOWI1NTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aab96MpqiW-33KtdyL-X2p1kMzhmeptXRiQ6ZbDRQX4)

Take a snapshot. Screenshots of your action list don't offer very much. 

https://github.com/Hekili/hekili/wiki/Report-An-Issue

**Comment by Hekili** [comment]
The `|` symbol is *OR*.  That means ending your conditions with `| boss & target.time_to_die >= 12` will be recommended if the conditions to the left of the `|` are met, OR if you're in a boss fight and your current target will die in 12+ seconds.

If you want the `target.time_to_die` to apply to the entire entry, you can wrap the other conditions in parentheses and add `& target.time_to_die >= 12` -- the `&` is *AND* meaning it is required along with the other conditions that you put in parentheses.

**Comment by sixsi** [comment]
so it's not planned to add this feature? :(

**Comment by syrifgit** [comment]
> so it's not planned to add this feature? :(

For you specifically, almost everything you want is already handled by the built-in cooldowns toggle as mentioned several times. You can just simply toggle cooldowns off when a pack gets too low.

**Comment by Cheetah714** [comment]
> > so it's not planned to add this feature? :(
> 
> For you specifically, almost everything you want is already handled by the built-in cooldowns toggle as mentioned several times. You can just simply toggle cooldowns off when a pack gets too low.

that what i'm doing currently and work fine i add my minicd into toogle and bind it to shift+r when the pack or even a boss in mythic + getting low i just press shift+r , and about my big cd i just disable it and do it manually , i believe big cd like Empower Rune Weapon, Frostwyrm's Fury and meta as demon hunter should never be recommended because that depends on the situation you are doing atm
