### ISSUE TITLE
Hide the main icon

### ISSUE THREAD

**Issue by Aldwew** [Hekili/hekili#38]
I have set the main icon to fade when I'm supposed to wait before using the ability. But I find my self very often using the ability too early. Is there a way instead of fading the icon, completely hide it? I wasn't sure if this was the right place to ask this so sorry about that

**Comment by Hekili** [comment]
No, not at this time.  I am working on tweaking it so it visually looks more like when you're lacking resources, but you still have the timer or icon indicator options (in display settings) until then.
