### ISSUE TITLE
Snapshots Saved Chat Spam Error Follow UP #3776

### ISSUE THREAD

**Issue by Shockette** [Hekili/hekili#3800]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Playing Assassination Rogue with the below build. Sometimes when I get out of combat Hekili starts to just spam this error message in chat and my memory usage for Hekili starts to just climb. I have to reload UI to get it to stop.

Rogue build CMQA27SZpS4XnmFfcXRqkppuwPjZmZGmhZAAAAAAY2gtZAAAAAAottZmhZmxYmZWmlxYwMzMzgZmZbbZMDwmZZgBsEsMMBGWA

This happens no matter the build though.

### How to Reproduce

Play assassination rogue with the above build and enter combat until it happens I guess. I have a bugsack report and maybe that will lead to the cause.

### Player Information (Link)

Assassination; Primary - Envenom(0.65), Mutilate(1.65), Mutilate(3.21), Mutilate(5.23) build: v11.0.2-1.0.13 level: 80 (80) class: ROGUE spec: assassination talents: CMQA27SZpS4XnmFfcXRqkppuwPjZmZGmhZAAAAAAY2gtZAAAAAAottZmhZmxYmZWmlxYwMzMzgZmZbbZMDwmZZgBsEsMMBGWA acrobatic_strikes = 1/1 airborne_irritant = 1/1 alacrity = 2/2 amplifying_poison = 1/1 bait_and_switch = 1/1 blackjack = 1/1 blind = 1/1 bloody_mess = 1/1 caustic_spatter = 1/1 cheat_death = 1/1 clear_the_witnesses = 1/1 cloak_of_shadows = 1/1 corrupt_the_blood = 1/1 crimson_tempest = 1/1 darkest_night = 1/1 deadened_nerves = 1/1 deadly_poison = 1/1 deadly_precision = 1/1 deathmark = 1/1 deathstalker = 1/1 deathstalkers_mark = 1/1 deeper_stratagem = 1/1 doomblade = 1/1 dragontempered_blades = 1/1 echoing_reprimand = 1/1 evasion = 1/1 fatal_concoction = 1/1 fatal_intent = 1/1 featherfoot = 1/1 fleet_footed = 1/1 graceful_guile =

### Error Messages (Link)

Below

### Additional Information

new Error.  See closed ticket for older errors as well as replies.  

1x [string "-- Assassination:cds:8..."]:2: script ran too long
[string "-- Assassination:cds:8
return safebool(  not (buff.thistle_tea.up) and (((energy.deficit>=100+energy.regen_combined or charges>=3) and debuff.shiv.remains>=4) or spell_targets.fan_of_knives>=4 and debuff.shiv.remains>=6) or (buff.thistle_tea.down or energy.deficit>100) and fight_remains<charges*6 )"]:2: in main chunk
[string "=(tail call)"]: ?
[string "@Hekili/Core.lua"]:1061: in function `GetPredictionFromAPL'
[string "@Hekili/Core.lua"]:904: in function `GetPredictionFromAPL'
[string "@Hekili/Core.lua"]:1414: in function `GetNextPrediction'
[string "@Hekili/Core.lua"]:1793: in function `Update'
[string "@Hekili/Options.lua"]:11729: in function `MakeSnapshot'
[string "@Hekili/Options.lua"]:11686: in function <Hekili/Options.lua:11681>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXML/Mainline/UIDropDownMenu.lua"]:1034: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:93_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:93_OnClick"]:1>

Locals:
(*temporary) = 74.077089
(*temporary) = 20.383105
(*temporary) = "script ran too long"

### Contact Information

Shock#2655

**Comment by Shockette** [comment]
it did it again in raid. Warnings is still greyed out and I couldnt click the issue reporting because it was spamming. It was also erroring when I tried to hit pause on it.
![image](https://github.com/user-attachments/assets/001bf7dd-154e-44f9-bb5c-f7353207a8c4)
![Spam Snapshots saved](https://github.com/user-attachments/assets/9d3f5219-abb5-42f7-803f-31bed788746f)

**Comment by Hekili** [comment]
Please post the snapshots for your primary display correctly. Copy and paste the text to Pastebin and then link them here.

**Comment by Shockette** [comment]
> Please post the snapshots for your primary display correctly. Copy and paste the text to Pastebin and then link them here.

Sorry not trying to mess this up.  When I take a snap shot I just use windows snipping tool.  Save it and drop it into here.  I am not sure how to use pastebin or how that would work with a snapshot from the sniping tool.

**Comment by Shockette** [comment]
https://pastebin.com/Jw1YWuyV

**Comment by Shockette** [comment]
https://pastebin.com/FbY4HrAF

**Comment by Shockette** [comment]
okay I think I added what you wanted for the Snapshots.  from the Hekili menu.  I think I wasnt understanding what you were asking for with a snapshot cause I thought you were talking about the snipping tool from windows.  I am sorry for the frustration.

**Comment by Shockette** [comment]
Do the images I post show up on here.  If so here is another one of my settings drop down from the mini map if that helps.  
![image](https://github.com/user-attachments/assets/b1be53e5-1202-4b2c-86c9-5d5ff4e48e81)

**Comment by syrifgit** [comment]
> Do the images I post show up on here. If so here is another one of my settings drop down from the mini map if that helps. ![image](https://private-user-images.gith)

Snapshots already tell us all of your settings

**Comment by Hekili** [comment]
So, what I *think* is happening is that the addon finds some a reason to snapshot, then starts regenerating the information it needs to put in the snapshot, and the CPU time of completing both of these efforts in the same frame is too long, which causes the update to fail.  However, the `ActiveDebug` flag says on, which tells the addon to make a snapshot every loop.

I will attempt two fixes:
* Remove the `ActiveDebug` flag if `Hekili.Update` exits with an error.
* Move snapshot generation to the next, fresh frame.

**Comment by Shockette** [comment]
I think I understand what you are saying because its running both single target and aoe at the same time.  I also have maybe an older PC that isnt doing the best of job on it.  its a 9900k though so its not garbage.  I really appreciate you looking into this.  It doesnt do it all the time and its was kinda hard to get it to do it again to be honest.  Typically in raid or in dungeons is when I notice it which makes sense with CPU load.   Thank you again for your help

**Comment by Hekili** [comment]
This appears to be resolved.
