### ISSUE TITLE
Trinket issue

### ISSUE THREAD

**Issue by Aszwaganda14** [Hekili/hekili#3801]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

Mark of Khardros BIS trinket not showing by hekkili in my rotation for Paladin Retribution

### How to Reproduce

enter game as a Retribution Paladin
wear Mark of Khardros trinket

### Snapshot (Link)

Retribution; Primary - Judgment(0.00), Blade of Justice(1.19), Templar's Verdict(2.39)

**Comment by Hekili** [comment]
This will be fixed in the next release.
