### ISSUE TITLE
[REC] Trinket no longer recommended as of last update

### ISSUE THREAD

**Issue by rheuzzy** [Hekili/hekili#3802]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

Trinket is no longer recommended in my rotation after updating.

### How to Reproduce

Usually the trinket is used when Cooldowns is enabled. Enable cooldowns and note that trinket is not recommended. 

### Snapshot (Link)

https://pastebin.com/SArnNn6e

### Contact Information

.rheuz

**Comment by Hekili** [comment]
Thanks; this will be fixed in the next release.
