### ISSUE TITLE
The rotation does not take into account the proc Trollbane's Icy Fury

### ISSUE THREAD

**Issue by mskitmerlin** [Hekili/hekili#3804]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

Sorry for my English. I noticed that the rotation doesn't take into account the Trollbane's Icy Fury buff, which is provided by the heroic talent (https://www.wowhead.com/spell=444834/trollbanes-icy-fury). Scourge Strike should be a priority if you have this proc. It's the main damage and AoE mechanic.

### How to Reproduce

Play in Unholy DK, Rider of the apocalypse. Prioritize Scourge Strike when activating Trollbane's Icy Fury buff.

### Snapshot (Link)

https://pastebin.com/1VdZCh3K

### Contact Information

itmerlin

**Comment by Hekili** [comment]
The sim, as written, uses Scourge Strike (or Clawing Shadows) when the debuff is falling off, rather than during its whole duration (which seems odd to me, too, since it's a damage amp debuff).

> debuff.chains_of_ice_trollbane_slow.up & debuff.chains_of_ice_trollbane_slow.remains < gcd

Can you provide a Raidbots sim of your character?  I'd like to determine if I've missed a sim update or if this needs to be passed along to SimulationCraft to update.

**Comment by mskitmerlin** [comment]
https://www.raidbots.com/simbot/report/xAfwQocFwpWKXHqZqCyjQv

**Comment by mskitmerlin** [comment]
I don't really understand, but as I see it, the raidbot also doesn't sim this skill for some reason.

**Comment by mskitmerlin** [comment]
I also noticed that there is such a problem: during an active battle, when I quickly press the buttons, the rotation starts showing the wrong skills. For example, it often stops showing Unholy Assault, although this is the main burst. It also stops showing Soul Reaper in AoE. Although this is the 2nd most powerful skill. In general, its problem is that it glitches when quickly pressed.

**Comment by syrifgit** [comment]
> I also noticed that there is such a problem: during an active battle, when I quickly press the buttons, the rotation starts showing the wrong skills. For example, it often stops showing Unholy Assault, although this is the main burst. It also stops showing Soul Reaper in AoE. Although this is the 2nd most powerful skill. In general, its problem is that it glitches when quickly pressed.

So get snapshots of that and open a new ticket
