### ISSUE TITLE
Is there a way to disable the summon pet recommendation for Marksman Hunter? 

### ISSUE THREAD

**Issue by Joshth24** [Hekili/hekili#3805]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Marksmanship

### Describe the Issue

I dont use a pet for Marksman, and the addon always recommends summoning the pet, and is taking up a recommendation spot on the screen. I've looked through the entire config page. and dont see anywhere to disable it. 

### How to Reproduce

The summon pet automatically appears in the recommendation rotation. 

### Snapshot (Link)

https://pastebin.com/TwL6HgnL

**Comment by syrifgit** [comment]
It's because you didn't take the talent where you gain DPS for not having a pet. Also, you're level 50, the addon is designed for max level.

But you can go into the abilities page and disable any ability you want.
