### ISSUE TITLE
DruidGuardian.simc,    line 13,  an obvious character input error

### ISSUE THREAD

**Issue by hellovvorld1024** [Hekili/hekili#3806]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Guardian

### Describe the Issue

../TheWarWithin/Priorities/DruidGuardian.simc     line 13

`actions+=/run_action_list,name=bearn`

In a recent update, it was changed to bearn. Maybe he should have stayed with the original 

`actions+=/run_action_list,name=bear`

### How to Reproduce

Just search for bearn keyword only this one

### Snapshot (Link)

nothing，Just a suggestion

**Comment by syrifgit** [comment]
is guardian druid working properly? Or is this causing an issue in-game

**Comment by hellovvorld1024** [comment]
![20240919094731](https://github.com/user-attachments/assets/4245aeb1-f4ad-4bc4-a7e8-5910b50276e5)

This is an obvious character input error. It doesn't require much validation.
It doesn't generate an error because of the lack of strict character validation. But the character error problem still exists.

Here is a screenshot of simulationcraft apl

**Comment by syrifgit** [comment]
That's not what I asked. Is this causing an issue in-game? Or is it working correctly?

**Comment by hellovvorld1024** [comment]
Sorry, I don't have a Druid character to test. Just find it when I proofread each file every time I pull it.

It's been about a week though and I haven't seen any similar tickets so that's why I'm posting this.  So it should work fine.
If it doesn't matter please just ignore it.

**Comment by Hekili** [comment]
There is another report of this typo, will fix in next release.
