### ISSUE TITLE
Feral Thrash spam recommendation when OOR of anything

### ISSUE THREAD

**Issue by Rawr-kitteh** [Hekili/hekili#3808]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Feral

### Describe the Issue

Quite frequently when you are out of range of everything and in combat, Hekili seems to recommend Thrash spamming for some reason even though it will not hit anything. If anything while OOR, it should be recommending Moonfire if talented into Lunar Inspiration.

### How to Reproduce

Very easy to replicate, just enter combat on a training dummy, and move out of range of it. Sometimes it doesn't recommend anything, but sometimes it recommends Thrash spamming even though it will not actually hit anything. It seems to be 50/50 whether it correctly works or not.

### Snapshot (Link)

https://pastebin.com/R7nCqaW5

### Contact Information

rawr.kitteh (discord)

**Comment by syrifgit** [comment]
Your snapshot sees an enemy in range

targets:  Nameplates are enabled.
 - Checking nameplate list for nameplate4 [ Creature-0-3782-2552-11989-225978-00006A0C43 ] Crystalmaw.
    - Excluded by range (25 > 10).
    - 
 ```
- Checking nameplate list for nameplate3 [ Creature-0-3782-2552-11989-225984-00006A0C44 ] Training Dummy.
    nameplate3   - -1 - Creature-0-3782-2552-11989-225984-00006A0C44 - 385.00 - 10 - Training Dummy 
 ```
 - Checking nameplate list for nameplate5 [ Creature-0-3782-2552-11989-225983-00006A0C45 ] Dungeoneer's Training Dummy.
    - Excluded by range (20 > 10).

**Comment by Rawr-kitteh** [comment]
I was 100% not in melee range of anything, so not sure why it would be reporting that I am, or if the range being checked is just too far for melee. Feral use to have an extended melee range, but it was nerfed with TWW.

**Comment by syrifgit** [comment]
Do you have the screenshot that it auto-saved during your snapshot?

**Comment by Shyirasky** [comment]
Same issue happens with rogue tempest, when there are enemies in the fight, (not in range at all) it suggests the priority. I think it might be to do with the previous range that both specs had prior to war within.

**Comment by syrifgit** [comment]
It's not that. The addon thinks there is an enemy 10 yards away.

**Comment by Hekili** [comment]
This is an artifact of filtering spells by range. 

Technically, from an API standpoint, Thrash has no range. Therefore, it is not filtered. 

It’s worth noting that the Feral priority isn’t written to account for using ranged spells when out of range. You’re a melee spec, the optimal DPS decision is to get in melee range. 

I’m curious what is recommended if you disable Thrash and stand out of range. There’s a good chance that there won’t be anything recommended at all.

**Comment by batkuip** [comment]
Something is weird here though.  Thrash has a 8 yard range (for Guardian at least).  If I'm outside the range of moonfire, moonfire will still be recommended but goes red.   But it doesn't do it for Thrash.  

Not the expert here, but could it be because it's explicitly not checking the range on Thrash? 
`spec:RegisterRanges( "shred", "rake", "skull_bash", "wild_charge", "growl", "entangling_roots", "moonfire" )`

Is this because you can always cast Thrash even when you are out of range?  (eg Moonfire won't actually allow you to cast the spell).

**Comment by Hekili** [comment]
> Not the expert here, but could it be because it's explicitly not checking the range on Thrash? `spec:RegisterRanges( "shred", "rake", "skull_bash", "wild_charge", "growl", "entangling_roots", "moonfire" )`

No, that's dead code from when range checking was otherwise broken.

> Is this because you can always cast Thrash even when you are out of range? (eg Moonfire won't actually allow you to cast the spell).

Yes.
