### ISSUE TITLE
Assassination Rogue priority is off.

### ISSUE THREAD

**Issue by Shyirasky** [Hekili/hekili#3809]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

It seems, when not specced into improved garrote, it suggests we still are using Vanish>Ambush in combat, this is actually a dps loss compared to just pressing mutilate. There are talents which increase ambush combo points by one point, but overall, it is more important to save our vanish, to reapply deathstalkers mark during boss intermissions where it falls off. So there players learning, using the addon, will be following a dps loss priority, I have tried editing the scripts myself, but i'm not too verse with them.

### How to Reproduce

Remove Vanish completely from the priority list, unless speced into Improved Garrote (so we can reapply one later in fight)

### Snapshot (Link)

I mean, you won't need a screenshot for this.

### Additional Information

It's likely a straight forward issue, but im not entirely sure why the priority is this in the first place, whether that's how the sims do it im not sure, but after much discussion in the ravenholt discord, this is a loss in dps to vanish>ambush, in main rotation

**Comment by syrifgit** [comment]
Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by Shyirasky** [comment]
https://pastebin.com/rdhhCgFC

Here is it.

**Comment by syrifgit** [comment]
The class guide disagrees with you. If you think this is incorrect, you should bring it up with the rogue theorycrafters or provide a custom sim showing that it is a dps gain to make the modification.

![image](https://github.com/user-attachments/assets/9f637c71-ef5a-4eb3-b1b6-b4de947d62f5)

**Comment by Shyirasky** [comment]
Yeah we've spoken in the class guide and Whisper (person who wrote the guide) has said that since bug fixes this is no longer part of the rotation, he just hasn't updated the guide since.

**Comment by syrifgit** [comment]
Can you provide a quicksim showing the new rotation?

**Comment by Shyirasky** [comment]
You are right, in here, the apl does specifically use vanish+ambush, as priority as it seems to value combo point builder over the initial damage, however over the course of a fight, this ends up being a dps loss, so i suppose the hekili addon is using the apl from raidbots to determine the action list?

https://www.raidbots.com/simbot/report/fgW9xY3a1o3rmmsUEHUEkD

If this is the case, then i suppose the addon is working as intended its actually the sim that is not working correctly since changes, and idea where I could go from here to try fix this? It's super "neich" i understand but I'm super curious about this all. Talking to some of the theory crafters etc in the discord about this atm too.

**Comment by Shyirasky** [comment]
Alright, after some further research, there is a bug in the game that is causing this issue and not the addon or apl, its just not been changed on the apl as of yet as the fix was looking to be implemented sooner rather than later, so the addon is actually following the sims apl correctly at the moment, apologies, can close this thread now.
