### ISSUE TITLE
Update APL Frost Dk icecap with frostwhelp Indignation azerite trait

### ISSUE THREAD

**Issue by Tobbelainen** [Hekili/hekili#381]
Yes. If you have Frostwhelp's Indignation trait on your gear as icecap and you get Pillar of Frost back off CD before your current one expired, it is a DPS gain to clip your Pillar 1 second before it expires on Single Target. Doing that will refresh the whelp buff and add another stack to it, giving you more mastery.

Current SimC APL does not include this gameplay. The post will be edited once it does. In the mean time, feel free to use the custom APL for your own sims. 
https://pastebin.com/kVTvVbgi From Acherus discord Dk

**Comment by Hekili** [comment]
It looks like this is represented in the simc APL now (I checked this morning) and I'll load it into the addon this weekend.  Thanks!
