### ISSUE TITLE
[REC] Frostwyrm's Fury issue

### ISSUE THREAD

**Issue by Cheetah714** [Hekili/hekili#3810]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

Frostwyrm's Fury should be recommended as soon you get Unholy Strength proc at the end of Pillar of Frost but the rotation recommended it at cd 

### How to Reproduce

1. enter game as frost dk
2. take Frostwyrm's Fury and Pillar of Frost talents
3. follow the rotation during Pillar of frost
4. see recommendation 

### Snapshot (Link)

https://pastebin.com/f6pzHWvg

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pusD3tY7fmdRBgr5zhrVcR

### Additional Information

![image](https://github.com/user-attachments/assets/236acc05-6b75-44ab-be1f-13418878cd81)

_No response_

**Comment by Andrez092** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by syrifgit** [comment]
Your sim does not do this either. If you think it's incorrect, bring it up to the frost DK theorycrafters or provide custom sims showing it is a dps gain.
