### ISSUE TITLE
[REC] Provide a short, descriptive title of you Recommendation issue

### ISSUE THREAD

**Issue by chapterk** [Hekili/hekili#3812]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

'Primary Recommendation' will be erased one by one.
In neutral, I see 2 skills and if you specify a target, I see 3 skills.
And if I use a skill, it's erased one by one and the next skill isn't recommended.
And then a snapshot is taken.

### How to Reproduce

1. There are 3 recommended skills
2. If I use a skill, the recommended skill is erased.
3. Other characters work fine.

### Snapshot (Link)

https://pastebin.com/4ZVahAdT

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rxds4MLcdnMw7D1QbLjdy4

**Comment by syrifgit** [comment]
Looks to me like you've tried to import a custom priority.

![image](https://github.com/user-attachments/assets/805140f9-6f0d-414a-b174-6f2ee01859f9)

Reset your pack back to default as per instructions in the FAQ.

https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#rotation--performance
