### ISSUE TITLE
[BUG] Immolation Aura Keybind Disappears

### ISSUE THREAD

**Issue by SilberComic** [Hekili/hekili#3814]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The Hotkey of Immolation Aura on my DH shows for a second but then disappears quickly and then all of the queued auras dont have hotkeys (only that ability)

### How to Reproduce

1. be havoc dh
2. activate hotkey showcase in primary "box"
3. start rotation and wait till Immolation Aura shows up
4. see the hotkey disappear

### Player Information (Link)

https://pastebin.com/k48UyhGe

### Error Messages (Link)

no error

### Additional Information

i have a clip of the aura hotkey disappearing, heres the clip https://www.youtube.com/watch?v=LKP4MDgauFo

### Contact Information

discord: silbercomic

**Comment by syrifgit** [comment]
The discord link does not work. Attach the actual clip here.

That being said, the addon does not seem to know what your immolation keybind is, so manually overriding that might help. See the FAQ. https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions

**Comment by SilberComic** [comment]
well the correct hotkey does show up for one charge but then the second/third charge has no keybind in it

heres the clip on yt (also edited into the report) : https://www.youtube.com/watch?v=LKP4MDgauFo

**Comment by syrifgit** [comment]
Follow the instructions for keybinds on the link I sent you ..

**Comment by SilberComic** [comment]
same result, it is visible on first use and then disappears

**Comment by syrifgit** [comment]
Show a screenshot of where you set the keybind

**Comment by SilberComic** [comment]
![grafik](https://github.com/user-attachments/assets/d881fe4d-5458-4920-bdf9-c517eac49072)
i put it in here just like the faq instructions said

**Comment by Hekili** [comment]
I'm guessing that something is changing the ID of Immolation Aura and I'm not sure what it is.  I can add the spell ID to keybind detection if you're able to supply that spell ID.

**Comment by SilberComic** [comment]
it should be 258920 if wowhead is correct

**Comment by Hekili** [comment]
That's the default spell ID.  I have 258920 and 452487 configured.

**Comment by SilberComic** [comment]
Is that something i can do myself? or did that small update today introduce a change? (11.0.2-1.0.16c but its still happening)

**Comment by Hekili** [comment]
If you get TipTac or another tooltip addon that shows spell IDs when you mouseover a spell, you could mouseover Immolation Aura on your action bar when the keybind is not displayed and it will show if the spell ID is different.  You'll have to go quick, though.

**Comment by SilberComic** [comment]
i tried it with tiptac and it shows 258920 when out of combat and then it switches to 427917 (and after some time, guessing the AoE Effect timer its back to the starting one)

**Comment by Hekili** [comment]
I suspect 427917 is the version of Immolation Aura that enables you to have multiple distinct buffs.  I'll add it to keybind detection and see what happens.
