### ISSUE TITLE
SIN Rogue: Unable to Provide Recommendation

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3817]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Single target rotation, doing a delve, on last boss, auto snap shotted, not sure.  

### How to Reproduce

Played Sin rogue, Did ST rotation on Boss, addon auto snap shotted

### Player Information (Link)

https://pastebin.com/dUEF94sd

### Error Messages (Link)

https://pastebin.com/dUEF94sd

### Contact Information

Wren1740

**Comment by DrWren** [comment]
Just checking in with this?  I know it was just a delve, but it was single target with M+ Talents.

**Comment by syrifgit** [comment]
Please check on the newest version once you are able to update.

https://github.com/Hekili/hekili/releases/tag/v11.0.2-1.0.15a

**Comment by Hekili** [comment]
(1.0.15a)

**Comment by michaerlrob92** [comment]
Using v11.0.2-1.0.16 on training dummy

https://pastebin.com/7dJZSnqH

**Comment by syrifgit** [comment]
Closing as there is a new ticket on the newest addon version: https://github.com/Hekili/hekili/issues/3853
