### ISSUE TITLE
Block Seasonal Affix from mob count

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#3818]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

The weekly affix spawns 10 orbs that count towards target count.

https://www.wowhead.com/npc=229296/orb-of-ascendance

**Comment by syrifgit** [comment]
I would even expand this as a feature to allow people to add their own NPC IDs to a blacklist inside the addon, some specs actually benefit from counting them such as funnel specs, or marksmanship in 2-target scenarios due to the orbs allowing trickshots.

Player choice!

**Comment by Hekili** [comment]
Will filter in next release.
