### ISSUE TITLE
[REC] Bear form not recommended anymore

### ISSUE THREAD

**Issue by batkuip** [Hekili/hekili#3819]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Guardian

### Describe the Issue

The latest update prevents shifting to bear if you are in any shapeshift form.  As a result, it now recommends things like casting lunar beam in travel form.  Showing bear was great esp when you are the wrong form.  I understand there are some edge cases where you don't want this eg cat dps while specced guardian.  Can we make this a toggle?

`actions.precombat+=/bear_form,if=buff.any_form.down`

### How to Reproduce

1. Enter game as guardian druid
2. Enable standard Elune's Chosen build `CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmxYmZsMjlZGjxADzMLWGAjBzMmoZGzMzMmFDbMAAAAAAghZmBW2mZDjZbAMFAAAYjZmB`
3. Shift to travel form
4. Lunar beam is now recommended

### Snapshot (Link)

https://pastebin.com/mqsqfV7y

**Comment by syrifgit** [comment]
Doesn't seem to be anything wrong with this. Lunar beam is castable while in travel form, which you are in during the snapshot. If you follow the rotation through, it will then tell you to heart of the wild, followed by incarn which automatically puts you in bear form.

I guess you could add an option for travel form though?

**Comment by batkuip** [comment]
It only suggests lunar beam, recommendations are empty after that.  Maybe a bug?  The snapshot is hinting at further recommedations, but they are not displaying for me unless I shift into bear form.  Its not just travel form though, it also happens in cat form.  Same thing, it only suggests lunar beam, nothing else.  No cat abilities are recommend either.  How is this supposed to work in guardian spec?  Should it recommend cat dps abilities or recommend guardian rotation?
