### ISSUE TITLE
Holy Priest as an available specialization

### ISSUE THREAD

**Issue by weleo** [Hekili/hekili#382]
Thanks for this awesome addon!

I have been using Hekili quite a bit beyond the officially supported rotations.

In this context,  it would be great to get PriestHoly as an available specialization option 
-- as it is currently the case for PriestDiscipline.

From the looks of it, this would mean that a PriestHoly file has to be created with;

-- RegisterResource
-- PvP Talents
-- Auras
-- Abilities

What goes into making a specialisation available beyond the PriestHoly.lua file?

**Comment by Hekili** [comment]
The file has to be added to the Hekili.toc file as well.

Then I generally build a priority in-game, then export the string there to use as a default priority.
