### ISSUE TITLE
Enabling disabling spells on all 8 level 80 characters not working

### ISSUE THREAD

**Issue by spottsy** [Hekili/hekili#3821]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Havoc

### Describe the Issue

The turning on or off spells to exclude from rotation on all my toons doesn't remove them. So for instance on the Havoc spec vengful retreat is disabled. "tootip says when enabled vengful retreat will NOT be recommended etc etc" but it makes no difference if disabled. The same goes for Fel rush. I would like to decide when to use fel Rush and Vengful retreat on my own. 

Fel Rush gold button is not filled but still being recommened along side of vengful retreat. Especially in open world don't need to use these two spells for low health mobs. 

I would like to add that this addon is great as I play a lot of alts and no way would remember rotations on all of them. I also use it for raiding on my hunter and helps in the hetic play to not stuff up priority so a big thanks. 

I update addons daily and has been a problem since war within release. I only just came back to game after a year. 

### How to Reproduce

Not situational always not working. I wonder if it is an addon conflict I don't know. 

### Snapshot (Link)

always present

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/guzhX4Hx1LCe1ucaM58fRW

### Contact Information

cino1965

**Comment by syrifgit** [comment]
Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot 

It is likely that you are confusing "Disabling an ability" with the havoc spec options for vengeful retreat, but I would know for sure if you provide a snapshot like the ticket instructions say to do.

**Comment by Hekili** [comment]
These particular settings for Havoc require support written into the default priority, which I have not done.  Right now, if you disable Vengeful Retreat, for example, the priority will completely fall apart because timing Vengeful Retreat is integral to the standard Havoc builds.

I'm more likely to remove the settings than to attempt to re-implement them.

**Comment by spottsy** [comment]
Thanks for letting me know. You are amazing at what you do thanks for the reply.
________________________________
