### ISSUE TITLE
[BUG] AoE not showing at all

### ISSUE THREAD

**Issue by Gabriel-R-A** [Hekili/hekili#3822]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Well, the addon is not showing the AoE rotations in any situation and with any class, I tested it with priest and monk, and it only shows the single target rotations, even in open world or dungeon, it never changes, I enabled it in the addon interface so that the AoE would appear but still nothing.

### How to Reproduce

Simply install the addon and use it normally.
I opened the display settings, checked the single and AoE modes, left both checked and went to test.

### Player Information (Link)

Brewmaster; AOE - Chi Burst(0.00), Blackout Kick(1.00), Weapons of Order(2.00) build: v11.0.2-1.0.14a level: 73 (73) class: MONK spec: brewmaster  talents: CwQAUXY49giSj4C5Wpk6qnLyQAAAAAGjxMwsMjtZmZGAAAAAAAssAiZGYGGbmBLzMzwsMMjlZZm22eglZbmZY2AAAIAAABBwMYD     ancient_arts = 2/2     august_blessing = 1/1     blackout_combo = 1/1     bob_and_weave = 1/1     bounding_agility = 1/1     breath_of_fire = 1/1     call_to_arms = 1/1     calming_presence = 1/1     celerity = 1/1     celestial_brew = 1/1     charred_passions = 1/1     chi_burst = 1/1     chi_proficiency = 2/2     chi_surge = 1/1     counterstrike = 1/1     dance_of_the_wind = 1/1     elixir_of_determination = 1/1     elusive_footwork = 1/1     exploding_keg = 1/1     face_palm = 1/1     fast_feet = 1/1     fatal_touch = 1/1     ferocity_of_xuen = 1/1     flow_of_chi = 1/1     fortifying_brew = 1/1     gai_plins_imperial_brew = 1/1     gift_of_the_ox = 1/1     grace_of_the_crane = 1/1     hasty_provocation = 1/1     high_tolerance = 1/2     hit_scheme = 1/1     ironshell_brew = 1/1     jade_walk = 1/1     keg_smash = 1/1     lighter_than_air = 1/1     martial_instincts = 2/2     paralysis = 1/1     pretense_of_instability = 1/1     purifying_brew = 1/1     ring_of_peace = 1/1     rising_sun_kick = 1/1     rushing_jade_wind = 1/1     salsalabims_strength = 1/1     shadowboxing_treads = 1/1     shuffle = 1/1     spear_hand_strike = 1/1     spirit_of_the_ox = 1/1     stormstouts_last_keg = 1/1     strength_of_spirit = 1/1     tiger_tail_sweep = 1/1     tigers_lust = 1/1     training_of_niuzao = 1/1     tranquil_spirit = 1/1     transcendence = 1/1     vigorous_expulsion = 1/1     vivacious_vivification = 1/1     weapons_of_order = 1/1     windwalking = 1/1     yulons_grace = 1/1     zen_meditation = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: none  gear: dunewind_sash = 1     eversong_cuffs = 1     mistdancer_band_of_stoicism = 1     mistdancer_cloak_of_rage = 1     mistdancer_defender_idol = 1     mistdancer_defender_stone = 1     mistdancer_footpads = 1     mistdancer_handguards = 1     mistdancer_helm = 1     mistdancer_legguards = 1     mistdancer_staff = 1     mistdancer_vest = 1     ring_of_umbral_doom = 1     shoulderpads_of_the_silvermoon_retainer = 1     soldiers_dog_tags = 1  legendaries: none  itemIDs: 133466, 133476, 153832, 153834, 153836, 153837, 153838, 153839, 153840, 153841, 153865, 170659, 188300, 188342, 188379  settings: aoe = 2     combatRefresh = 0.25     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 8     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxTime = 20     nameplateRange = 10     nameplates = true     noFeignedCooldown = false     package = Brewmaster     petbased = false     potion = phantom_fire     rangeFilter = false     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     bof_percent = 50     eh_percent = 65     max_damage = true     purify_for_celestial = true     purify_for_niuzao = true     purify_stagger_currhp = 12     purify_stagger_maxhp = 6     vivify_percent = 65  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     funnel = false      interrupts = true      mode = automatic      potions = false   keybinds:      blackout_kick              = F   [01]     breath_of_fire             = E   [01]     celestial_brew             = CX  [06]     chi_burst                  = 3   [01]     clash                      = SE  [06]     crackling_jade_lightning   = 1   [01]     expel_harm                 = A3  [06]     exploding_keg              = F2  [05]     fortifying_brew            = F5  [05]     invoke_niuzao_the_black_ox = F4  [05]     keg_smash                  = Q   [01]     leg_sweep                  = 4   [01]     paralysis                  = AQ  [06]     provoke                    = A1  [06]     purifying_brew             = CZ  [06]     ring_of_peace              = AE  [06]     rising_sun_kick            = Z   [01]     roll                       = SM5 [05]     rushing_jade_wind          = C   [01]     spear_hand_strike          = X   [01]     spinning_crane_kick        = 2   [01]     tiger_palm                 = R   [01]     tigers_lust                = CE  [06]     touch_of_death             = 5   [01]     transcendence              = A4  [06]     transcendence_transfer     = CQ  [06]     vivify                     = A2  [06]     weapons_of_order           = F1  [05]     zen_meditation             = F3  [05], F   [08], F   [09]  warnings: none   targets:  Nameplates are enabled.  player_buffs:    166646 - windwalking                              -   1 - 3600.00    450574 - flow_of_chi_speed                        -   1 - 3600.00    392883 - vivacious_vivification                   -   1 - 3600.00    442982 - *generals_phalanx                        -   1 - 3600.00    335148 - *sign_of_the_twisting_nether             -   1 - 3600.00    292361 - *embrace_of_paku                         -   1 - 3600.00    430191 - *warband_mentored_leveling               -   1 - 3600.00    450832 - *fatal_touch                             -   1 - 0.14      450552 - jade_walk                                -   1 - 3600.00  player_debuffs:  target_auras:  target does not exist  previous_spells:    1 - touch_of_death    2 - celestial_brew    3 - purifying_brew   New Recommendations for [ AOE ] requested at 22:07:08 ( 228046.31 ); using built-in ( Brewmaster ) priority. *** START OF NEW DISPLAY: AOE *** Purged 338 marked values in 0.15ms.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: chi[ 0.00 / 4.00 ], energy[ 100.00 / 100.00 ], mana[ 405160.00 / 405160.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Brewmaster - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   potion ( precombat - 1 ) - ability disabled ( toggle potions )         Time spent on this action:  0.52ms         TimeData:Brewmaster-precombat-1:potion:0.52:Ability Known, Enabled(0.52)                  2.   chi_burst ( precombat - 2 )         The action (chi_burst) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria PASSES: talent.chi_burst.enabled[true]         Action chosen:  chi_burst at 0.00!         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Brewmaster - precombat ].     Recommendation is chi_burst at 0.00 + 0.00.     Recommendation #1 is chi_burst at 0.00s (0.00s).     Queueing chi_burst cast finish at 228047.14 [+0.83] on Creature-0-4232-2601-25261-218251-00006F6AA2.     Queued chi_burst from 228046.31 to 228047.14 (CAST_FINISH).  RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.00, Casting: 0.83 ).      There are 1 queued events to review.     Resources: chi[ 0.00 / 4.00 ], energy[ 100.00 / 100.00 ], mana[ 405160.00 / 405160.00 ]          Finishing queued event #1 ( CAST_FINISH of chi_burst ) due at 0.83 as player is casting and castable spells are not ready.     Casting: Yes, Channeling: No, Break: No, Check: No     While advancing by 0.83 to 0.83, chi_burst CAST_FINISH occurred at 0.83.          Handling chi_burst at 228047.14 (CAST_FINISH).     Using ability on a different target.      - cycle aura appears to be down, so we're sticking with our current target.     Starting combat at 228047.13 -- time is 0.01.     Trying to remove chi_burst CAST_FINISH from queue.     Removing 1 from queue.     Resources: chi[ 0.00 / 4.00 ], energy[ 100.00 / 100.00 ], mana[ 405160.00 / 405160.00 ]          Resources: chi[ 0.00 / 4.00 ], energy[ 100.00 / 100.00 ], mana[ 405160.00 / 405160.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Brewmaster - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   potion ( precombat - 1 ) - ability disabled ( toggle potions )         Time spent on this action:  0.50ms         TimeData:Brewmaster-precombat-1:potion:0.50:Ability Known, Enabled(0.50)                  2.   chi_burst ( precombat - 2 )         The action is not ready ( 30.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Brewmaster-precombat-2:chi_burst:0.02:Ability Known, Enabled(0.02)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Brewmaster - precombat ].          Processing default action list [ Brewmaster - default ].                  Current recommendation was NO ACTION at +10.00s.                  3.   spear_hand_strike ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Brewmaster-default-1:spear_hand_strike:0.03:Ability Known, Enabled(0.03)                  4.   diffuse_magic ( default - 2 ) - talent [ diffuse_magic ] missing         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-2:diffuse_magic:0.02:Ability Known, Enabled(0.02)                  5.   vivify ( default - 3 )         The action (vivify) is usable at (0.83 + 0.17) with cost of 30 energy (have 100).          - the action is ready before the current recommendation (at +0.17 vs. +10.00).          - this entry's criteria FAILS: health.pct[100.00] <= settings.vivify_percent[65.00] & buff.vivacious_vivification.up[true]         There were no recheck events to check.         Time spent on this action:  0.16ms         TimeData:Brewmaster-default-3:vivify:0.16:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.03):Post-Recheck Times(0.01):Post Recheck(0.00)                  6.   purifying_brew ( default - 4 )         The action (purifying_brew) is unusable at (0.83 + 0.00) because no damage is staggered.         Time spent on this action:  0.15ms         TimeData:Brewmaster-default-4:purifying_brew:0.15:Ability Known, Enabled(0.03):Post-TTR and Essential(0.07):Post Cycle(0.00):Post Usable(0.05)                  7.   celestial_brew ( default - 5 )         The action is not ready ( 12.43 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Brewmaster-default-5:celestial_brew:0.03:Ability Known, Enabled(0.03)                  8.   purifying_brew ( default - 6 )         The action (purifying_brew) is unusable at (0.83 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-6:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  9.   purifying_brew ( default - 7 )         The action (purifying_brew) is unusable at (0.83 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-7:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  10.  purifying_brew ( default - 8 )         The action (purifying_brew) is unusable at (0.83 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-8:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  11.  purifying_brew ( default - 9 )         The action (purifying_brew) is unusable at (0.83 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-9:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  12.  purifying_brew ( default - 10 )         The action (purifying_brew) is unusable at (0.83 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-10:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  13.  purifying_brew ( default - 11 )         The action (purifying_brew) is unusable at (0.83 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-11:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  14.  dampen_harm ( default - 12 ) - talent [ dampen_harm ] missing         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-12:dampen_harm:0.02:Ability Known, Enabled(0.02)                  15.  fortifying_brew ( default - 13 )         The action (fortifying_brew) is usable at (0.83 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: health.pct[100.00] < 50 & incoming_damage_3s[0.00] > health.max[1232400.00] * ( 0.2 + ( 0.2 * group[false] ) ) & ( buff.dampen_harm.down[true] )         There were no recheck events to check.         Time spent on this action:  0.17ms         TimeData:Brewmaster-default-13:fortifying_brew:0.17:Ability Known, Enabled(0.02):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.05):Post-Recheck Times(0.01):Post Recheck(0.00)                  16.  potion ( default - 14 ) - ability disabled ( toggle potions )         Time spent on this action:  0.49ms         TimeData:Brewmaster-default-14:potion:0.49:Ability Known, Enabled(0.49)                  17.  touch_of_death ( default - 15 )         The action is not ready ( 59.04 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Brewmaster-default-15:touch_of_death:0.03:Ability Known, Enabled(0.03)                  18.  call_action_list:items ( default - 16 )         There is no criteria for items.         Action list (items) was found.         + items         Current recommendation was NO ACTION at +10.00s.                  19.  main_hand ( items - 1 )         The action (main_hand) is unusable at (0.83 + 0.00) because ability.usable was false.         Time spent on this action:  0.05ms         TimeData:Brewmaster-items-1:main_hand:0.05:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  20.  trinket1 ( items - 2 )         Time spent on this action:  0.02ms         TimeData:Brewmaster-items-2:trinket1:0.02:Ability Known, Enabled(0.02)                  21.  mydas_talisman ( items - 3 ) - IsUsableItem item 158319 and nil         Time spent on this action:  0.04ms         TimeData:Brewmaster-items-3:mydas_talisman:0.04:Ability Known, Enabled(0.04)         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from list (items), current recommendation is NO ACTION (+10.00).         - items                  22.  blood_fury ( default - 17 ) - ability unknown         Time spent on this action:  0.03ms         TimeData:Brewmaster-default-17:blood_fury:0.03:Ability Known, Enabled(0.03)                  23.  berserking ( default - 18 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-18:berserking:0.02:Ability Known, Enabled(0.02)                  24.  lights_judgment ( default - 19 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-19:lights_judgment:0.02:Ability Known, Enabled(0.02)                  25.  fireblood ( default - 20 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-20:fireblood:0.02:Ability Known, Enabled(0.02)                  26.  ancestral_call ( default - 21 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-21:ancestral_call:0.02:Ability Known, Enabled(0.02)                  27.  bag_of_tricks ( default - 22 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-22:bag_of_tricks:0.02:Ability Known, Enabled(0.02)                  28.  expel_harm ( default - 23 )         The action (expel_harm) is unusable at (0.83 + 0.17) because health is above 65%.         Time spent on this action:  0.08ms         TimeData:Brewmaster-default-23:expel_harm:0.08:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.01)                  29.  call_action_list:rotation_pta ( default - 24 )         Criteria for rotation_pta FAIL at +0.83 - talent.press_the_advantage.enabled[false]                  30.  call_action_list:rotation_boc ( default - 25 )         Criteria for rotation_boc PASS at +0.83 - ! talent.press_the_advantage.enabled[false]         Action list (rotation_boc) was found.         + rotation_boc         Current recommendation was NO ACTION at +10.00s.                  31.  blackout_kick ( rotation_boc - 1 )         The action (blackout_kick) is usable at (0.83 + 0.17).          - the action is ready before the current recommendation (at +0.17 vs. +10.00).         List ( rotation_boc ) called from ( Brewmaster:default:25 ) would PASS at 0.17.         ! talent.press_the_advantage.enabled[false]          - this entry has no criteria to test.         Action chosen:  blackout_kick at 0.17!         Time spent on this action:  0.14ms         TimeData:Brewmaster-rotation_boc-1:blackout_kick:0.14:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.02):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)         The recommended action (blackout_kick) is ready in less than 0.2s; exiting list (rotation_boc).         Exiting rotation_boc with recommendation of NO ACTION at +10.00s.         Returned from list (rotation_boc), current recommendation is blackout_kick (+0.17).         - rotation_boc         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Brewmaster - default ].     Recommendation is blackout_kick at 0.83 + 0.17.     Recommendation #2 is blackout_kick at 0.17s (1.00s).  RECOMMENDATION #3 ( Offset: 1.00, GCD: 1.00, Casting: 0.00 ).      Resources: chi[ 0.00 / 4.00 ], energy[ 100.00 / 100.00 ], mana[ 405160.00 / 405160.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Brewmaster - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   potion ( precombat - 1 ) - ability disabled ( toggle potions )         Time spent on this action:  0.50ms         TimeData:Brewmaster-precombat-1:potion:0.50:Ability Known, Enabled(0.50)                  2.   chi_burst ( precombat - 2 )         The action is not ready ( 29.83 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Brewmaster-precombat-2:chi_burst:0.03:Ability Known, Enabled(0.03)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Brewmaster - precombat ].          Processing default action list [ Brewmaster - default ].                  Current recommendation was NO ACTION at +10.00s.                  3.   spear_hand_strike ( default - 1 )         The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-1:spear_hand_strike:0.02:Ability Known, Enabled(0.02)                  4.   diffuse_magic ( default - 2 ) - talent [ diffuse_magic ] missing         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-2:diffuse_magic:0.02:Ability Known, Enabled(0.02)                  5.   vivify ( default - 3 )         The action (vivify) is usable at (1.00 + 1.00) with cost of 30 energy (have 100).          - the action is ready before the current recommendation (at +1.00 vs. +10.00).          - this entry's criteria FAILS: health.pct[100.00] <= settings.vivify_percent[65.00] & buff.vivacious_vivification.up[true]         There were no recheck events to check.         Time spent on this action:  0.12ms         TimeData:Brewmaster-default-3:vivify:0.12:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.02):Post-Recheck Times(0.01):Post Recheck(0.00)                  6.   purifying_brew ( default - 4 )         The action (purifying_brew) is unusable at (1.00 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-4:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  7.   celestial_brew ( default - 5 )         The action is not ready ( 12.26 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-5:celestial_brew:0.02:Ability Known, Enabled(0.02)                  8.   purifying_brew ( default - 6 )         The action (purifying_brew) is unusable at (1.00 + 0.00) because no damage is staggered.         Time spent on this action:  0.05ms         TimeData:Brewmaster-default-6:purifying_brew:0.05:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  9.   purifying_brew ( default - 7 )         The action (purifying_brew) is unusable at (1.00 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-7:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  10.  purifying_brew ( default - 8 )         The action (purifying_brew) is unusable at (1.00 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-8:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  11.  purifying_brew ( default - 9 )         The action (purifying_brew) is unusable at (1.00 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-9:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  12.  purifying_brew ( default - 10 )         The action (purifying_brew) is unusable at (1.00 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-10:purifying_brew:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  13.  purifying_brew ( default - 11 )         The action (purifying_brew) is unusable at (1.00 + 0.00) because no damage is staggered.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-11:purifying_brew:0.06:Ability Known, Enabled(0.03):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01)                  14.  dampen_harm ( default - 12 ) - talent [ dampen_harm ] missing         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-12:dampen_harm:0.02:Ability Known, Enabled(0.02)                  15.  fortifying_brew ( default - 13 )         The action (fortifying_brew) is usable at (1.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria FAILS: health.pct[100.00] < 50 & incoming_damage_3s[0.00] > health.max[1232400.00] * ( 0.2 + ( 0.2 * group[false] ) ) & ( buff.dampen_harm.down[true] )         There were no recheck events to check.         Time spent on this action:  0.11ms         TimeData:Brewmaster-default-13:fortifying_brew:0.11:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.02):Post-Recheck Times(0.01):Post Recheck(0.00)                  16.  potion ( default - 14 ) - ability disabled ( toggle potions )         Time spent on this action:  0.49ms         TimeData:Brewmaster-default-14:potion:0.49:Ability Known, Enabled(0.49)                  17.  touch_of_death ( default - 15 )         The action is not ready ( 58.86 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-15:touch_of_death:0.02:Ability Known, Enabled(0.02)                  18.  call_action_list:items ( default - 16 )         There is no criteria for items.         Action list (items) was found.         + items         Current recommendation was NO ACTION at +10.00s.                  19.  main_hand ( items - 1 )         The action (main_hand) is unusable at (1.00 + 0.00) because ability.usable was false.         Time spent on this action:  0.04ms         TimeData:Brewmaster-items-1:main_hand:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  20.  trinket1 ( items - 2 )         Time spent on this action:  0.02ms         TimeData:Brewmaster-items-2:trinket1:0.02:Ability Known, Enabled(0.02)                  21.  mydas_talisman ( items - 3 ) - IsUsableItem item 158319 and nil         Time spent on this action:  0.04ms         TimeData:Brewmaster-items-3:mydas_talisman:0.04:Ability Known, Enabled(0.04)         Exiting items with recommendation of NO ACTION at +10.00s.         Returned from list (items), current recommendation is NO ACTION (+10.00).         - items                  22.  blood_fury ( default - 17 ) - ability unknown         Time spent on this action:  0.03ms         TimeData:Brewmaster-default-17:blood_fury:0.03:Ability Known, Enabled(0.03)                  23.  berserking ( default - 18 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-18:berserking:0.02:Ability Known, Enabled(0.02)                  24.  lights_judgment ( default - 19 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-19:lights_judgment:0.02:Ability Known, Enabled(0.02)                  25.  fireblood ( default - 20 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-20:fireblood:0.02:Ability Known, Enabled(0.02)                  26.  ancestral_call ( default - 21 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-21:ancestral_call:0.02:Ability Known, Enabled(0.02)                  27.  bag_of_tricks ( default - 22 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Brewmaster-default-22:bag_of_tricks:0.02:Ability Known, Enabled(0.02)                  28.  expel_harm ( default - 23 )         The action (expel_harm) is unusable at (1.00 + 1.00) because health is above 65%.         Time spent on this action:  0.06ms         TimeData:Brewmaster-default-23:expel_harm:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.01)                  29.  call_action_list:rotation_pta ( default - 24 )         Criteria for rotation_pta FAIL at +1.00 - talent.press_the_advantage.enabled[false]                  30.  call_action_list:rotation_boc ( default - 25 )         Criteria for rotation_boc PASS at +1.00 - ! talent.press_the_advantage.enabled[false]         Action list (rotation_boc) was found.         + rotation_boc         Current recommendation was NO ACTION at +10.00s.                  31.  blackout_kick ( rotation_boc - 1 )         The action (blackout_kick) is usable at (1.00 + 4.00).          - the action is ready before the current recommendation (at +4.00 vs. +10.00).         List ( rotation_boc ) called from ( Brewmaster:default:25 ) would PASS at 4.00.         ! talent.press_the_advantage.enabled[false]          - this entry has no criteria to test.         Action chosen:  blackout_kick at 4.00!         Time spent on this action:  0.13ms         TimeData:Brewmaster-rotation_boc-1:blackout_kick:0.13:Ability Known, Enabled(0.02):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.02):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)                  32.  weapons_of_order ( rotation_boc - 2 )         The action (weapons_of_order) is usable at (1.00 + 1.00) with cost of 20258 mana (have 405160).          - the action is ready before the current recommendation (at +1.00 vs. +4.00).         List ( rotation_boc ) called from ( Brewmaster:default:25 ) would PASS at 1.00.         ! talent.press_the_advantage.enabled[false]          - this entry's criteria FAILS: ( buff.recent_purifies.up[false] ) & talent.improved_invoke_niuzao_the_black_ox.enabled[false]         There were no recheck events to check.         Time spent on this action:  0.19ms         TimeData:Brewmaster-rotation_boc-2:weapons_of_order:0.19:Ability Known, Enabled(0.03):Post-TTR and Essential(0.06):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.02):Pre-Script(0.00):Post-Script(0.03):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)                  33.  invoke_niuzao_the_black_ox ( rotation_boc - 3 ) - talent [ invoke_niuzao_the_black_ox ] missing         Time spent on this action:  0.02ms         TimeData:Brewmaster-rotation_boc-3:invoke_niuzao_the_black_ox:0.02:Ability Known, Enabled(0.02)                  34.  invoke_niuzao_the_black_ox ( rotation_boc - 4 ) - talent [ invoke_niuzao_the_black_ox ] missing         Time spent on this action:  0.02ms         TimeData:Brewmaster-rotation_boc-4:invoke_niuzao_the_black_ox:0.02:Ability Known, Enabled(0.02)                  35.  invoke_niuzao_the_black_ox ( rotation_boc - 5 ) - talent [ invoke_niuzao_the_black_ox ] missing         Time spent on this action:  0.02ms         TimeData:Brewmaster-rotation_boc-5:invoke_niuzao_the_black_ox:0.02:Ability Known, Enabled(0.02)                  36.  weapons_of_order ( rotation_boc - 6 )         The action (weapons_of_order) is usable at (1.00 + 1.00) with cost of 20258 mana (have 405160).          - the action is ready before the current recommendation (at +1.00 vs. +4.00).         List ( rotation_boc ) called from ( Brewmaster:default:25 ) would PASS at 1.00.         ! talent.press_the_advantage.enabled[false]          - this entry's criteria PASSES: ( talent.weapons_of_order.enabled[true] ) & ! talent.improved_invoke_niuzao_the_black_ox.enabled[false]         Action chosen:  weapons_of_order at 1.00!         Time spent on this action:  0.14ms         TimeData:Brewmaster-rotation_boc-6:weapons_of_order:0.14:Ability Known, Enabled(0.03):Post-TTR and Essential(0.04):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.02):Pre-Script(0.00):Post-Script(0.00):Pre-Recheck(0.01):Post Recheck(0.00):Action Stored(0.01)         Only off-GCD abilities would be usable before the currently selected ability; skipping...         The recommended action (weapons_of_order) is ready within the active GCD; exiting list (rotation_boc).         Exiting rotation_boc with recommendation of NO ACTION at +10.00s.         Returned from list (rotation_boc), current recommendation is weapons_of_order (+1.00).         - rotation_boc         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Brewmaster - default ].     Recommendation is weapons_of_order at 1.00 + 1.00.     Recommendation #3 is weapons_of_order at 1.00s (2.00s).     Time spent generating recommendations:  8.53ms

### Error Messages (Link)

No error message

### Additional Information

No error message

**Comment by Hekili** [comment]
Snapshots have to be placed on Pastebin and linked so they remain readable.

That said, I think you are misunderstanding how Display Modes work.  They are explained on the toggle screen.

![image](https://github.com/user-attachments/assets/0a099b0d-29da-4178-87f6-3b075c2bd1a0)

Your active Display Mode is Automatic.
