### ISSUE TITLE
[REC] Mark of Khardros still not in rotation

### ISSUE THREAD

**Issue by purefreakz** [Hekili/hekili#3823]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

Mark of Khardros still not in rotation

### How to Reproduce

Equip the trinket :D 

### Snapshot (Link)

not in snapshot

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cDRr5dC72hJv3GfuouWE5P

**Comment by syrifgit** [comment]
It's already fixed for the next update
