### ISSUE TITLE
[BUG] v11.0.2-1.0.15 causes large numbers of LUA errors on first login

### ISSUE THREAD

**Issue by Furydins** [Hekili/hekili#3827]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Since v11.0.2-1.0.15 has been installed on first login to a character Helki is continually generating the same LUA error over and over again (well into double figures per minute). Logging out and in again to the same character resolves the error for all characters on the same realm but the issue can be reproduced again by logging in to a character on another realm

### How to Reproduce

1. Immediately after installing v11.0.2-1.0.15 log in to any character.
2 . Observe that after a minute or so the game displays a warning about excessive LUA errors from Hekili
3. Observe that the Hekili UI is not displayed
3. Log out
4. Log back in to the  same character - observer that the error is no longer present and Hekil UI is visible.
5. Repeat steps on another character on a different realm

### Player Information (Link)

Hekili would not open

### Error Messages (Link)

https://pastebin.com/LrABGcG0

**Comment by Furydins** [comment]
Update: while relogging does usually resolve the issue - logging to a different character and then back to the first can sometimes cause the issue to reccur.

**Comment by syrifgit** [comment]
Pastebins from Theo

https://pastebin.com/3rHBa5AN  
https://pastebin.com/9LFKY2RJ 
https://pastebin.com/LCrx4kBh 
https://pastebin.com/16AtJj3t 
https://pastebin.com/aD24Mitf 
https://pastebin.com/7HXPz0pd 
https://pastebin.com/2DMvUCB3

My pastebin
https://pastebin.com/57KaXARb

**Comment by Hekili** [comment]
Fixed in 1.0.15a.
