### ISSUE TITLE
[REC] Trinket "Oppressive Orator's Larnyx" Not Recommended in Rotation

### ISSUE THREAD

**Issue by rheuzzy** [Hekili/hekili#3829]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

The trinket "Oppressive Orator's Larnyx" is not recommended at all during the rotation. Skyterror trinket is properly recommended at start of fight, but the second trinket is not. 

### How to Reproduce

Simply begin fight with cooldowns and small cooldowns enabled. BoS talent build: CsPAtbMOTHlnKIwUyAn+DK70SPGAzMzMjxYYGzMzMzMGmJzYMjBMzYMjZmZmZmZxMAAAAAAAAAAAAbmtBGwCYbYCZsgZYMDA

### Snapshot (Link)

https://pastebin.com/Z90XdVBf

### Contact Information

.rheuz

**Comment by Hekili** [comment]
Thanks for the report; the required buff ID was incorrect in the addon.  This will be fixed in the next version.
