### ISSUE TITLE
2 prot warrior tweeks 

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#383]
Hello

After playing warrior for few weeks i have some nice tip's for hekilii:

1. Berserker rage  (ID: 18499)- should be recommended only if character is Feared,sap-ed,
2. Spell reflect  (ID:23920 ) - should be recommended if enemy start cast on you and that cast can be spell reflected

build: v8.3.0-07
level: 120 (120)
class: WARRIOR
spec: protection

talents: anger_management
    bolster
    booming_voice
    crackling_thunder
    into_the_fray
    rumbling_earth
    unstoppable_force

azerite: azerite_empowered = 3
    bastion_of_might = 3
    brace_for_impact = 1
    bulwark_of_the_masses = 1
    deafening_crash = 1
    earthlink = 1
    heart_of_darkness = 1
    impassive_visage = 1
    overwhelming_power = 2
    resounding_protection = 1

essences: [vision_of_perfection] = 3, aegis_of_the_deep = 3, conflict_and_strife = 3, strength_of_the_warden = 4

sets/legendaries/artifacts: none

gear: adulation_enforcer = 1
    ashjrakamas_shroud_of_resolve = 1
    ashvane_wardens_cuirass = 1
    boots_of_hallucinatory_reality = 1
    disc_of_indomitable_will = 1
    dragonbone_vambraces = 1
    girdle_of_burgeoning_apathy = 1
    heart_of_azeroth = 1
    heavy_alloy_legplates = 1
    humming_black_dragonscale = 1
    lingering_psychic_shell = 1
    malignant_leviathans_gauntlets = 1
    seabrawlers_greathelm = 1
    seal_of_the_regal_loa = 1
    thornwoven_band = 1
    writhing_spaulders_of_madness = 1

corruptions: twilight_devastation = 5

itemIDs: 155885, 158075, 158713, 159440, 159450, 159458, 159632, 162548, 168966, 169223, 173466, 174044, 174165, 174170, 174173, 174277

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Protection Warrior
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    free_revenge = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
I don't have a simple, consistent way of detecting if you are feared to use Berserker Rage, nor to know which spells to reflect, so these modifications are unlikely.  Thanks for the suggestions.
