### ISSUE TITLE
[REC] Prot Warrior is not recommending Last Stand or Shield Wall.

### ISSUE THREAD

**Issue by winnerwinnington** [Hekili/hekili#3830]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Protection

### Describe the Issue

Last stand conditions from the addon: 
`( target.health.pct >= 90 & talent.unnerving_focus.enabled | target.health.pct <= 20 & talent.unnerving_focus.enabled ) | talent.bolster.enabled | set_bonus.tier30_2pc | set_bonus.tier30_4pc`

I have neither talent, and I think Tier 30 is two sets ago? TWW Season 1 is Tier 32 - right?

This problem extends to Shield Wall which appears to only require the talent immovable object. 
`talent.immovable_object.enabled & buff.avatar.down`

Are either these connected to their sliders for health % and incoming damage?

### How to Reproduce

1. Enter the game as a Prot Warrior
2. Don't take unnerving focus, or bolstering
3. Equip any non-tier 30 gear
4. lose nearly all your health

### Snapshot (Link)

https://pastebin.com/JTFXe5y6

### Raidbots Sim Report (Link)

N/A

### Additional Information

None.

### Contact Information

Staypuft#8032

**Comment by Hekili** [comment]
`( target.health.pct[97.86] >= 90 & talent.unnerving_focus.enabled[false] | target.health.pct[97.86] <= 20 & talent.unnerving_focus.enabled[false] ) | talent.bolster.enabled[false] | set_bonus.tier30_2pc[0.00] | set_bonus.tier30_4pc[0.00]`

Probably needs criteria updates, but currently requires Unnerving Focus, Bolster, or tier 30.

**Comment by Spike2D** [comment]
`tanking & incoming_damage_5s > last_stand_damage_taken & health.pct <= last_stand_health_pct & ! ( buff.shield_wall.up | buff.last_stand.up | buff.rallying_cry.up | buff.potion.up )`

Would this be correct @Hekili ?

**Comment by Spike2D** [comment]
+ Added Mitigations correctly to both SimC and tied them to the settings.
+ Added Victory Rush/Impending Victory setting as well as added them to SimC.
- Removed Last Stand used Offensively option, not relevant anymore.

Pull request: #3846

**Comment by SerhatSoruklu** [comment]
Hello im also a prot warrior its not recommending last stand, shield wall, rallying cry, slam, impending victory and many others...

**Comment by Hekili** [comment]
PR merged for next release.
