### ISSUE TITLE
[BUG] Resto Druid - Graphic Stutter on Login

### ISSUE THREAD

**Issue by moncuex** [Hekili/hekili#3833]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

While specced resto druid I am getting graphic stutter.  Just started today with the newest updates.  I saw there was another release today so I went and did that one first before checking this.
I entered the game as resto - swiched to boomkin (the stutter disappears) - switched back to resto (the stutter doesn't come back).
I then log back out and back in as resto - and the stutter re-appears.

### How to Reproduce

I entered the game as resto - swiched to boomkin (the stutter disappears) - switched back to resto (the stutter doesn't come back).
I then log back out and back in as resto - and the stutter re-appears.

It appears that Hekili isn't loading when I log in as resto - but does load after I swap specs and come back to it.

### Player Information (Link)

This isn't opening the panels - just the placement of hekili on the screen.

### Error Messages (Link)

Not getting any error messages.

### Contact Information

Discord ID:  moncuex

**Comment by syrifgit** [comment]
Update to the newest version of the addon 
![image](https://github.com/user-attachments/assets/dc123b79-f653-473e-adae-4411280b94b8)

If the issue persists, re-open the ticket with a snapshot or error logs.
