### ISSUE TITLE
Sequence stop refreshing after casting Soul Sunder

### ISSUE THREAD

**Issue by liugongkai111** [Hekili/hekili#3834]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Vengeance

### Describe the Issue

Every time as a vengeance DH casting Soul Sunder, the enhanced soul cleaver from metamorphosis, the whole sequence will stop refreshing and recommending spells that are still in cool-down.

### How to Reproduce

1. Enter game as a vengeance DH
2. enter metamorphosis by any means
3. cast Soul Sunder, the enhanced soul cleaver
4. sequence will stop refreshing

### Snapshot (Link)

https://pastebin.com/JvC0eTev

**Comment by Hekili** [comment]
This will be fixed in v1.0.16b.

**Comment by syrifgit** [comment]
Closing as no further responses received after the fix
