### ISSUE TITLE
Windwalker Trinkets and Invoke Xuen not in the Rotation

### ISSUE THREAD

**Issue by Troxlear** [Hekili/hekili#3835]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Windwalker

### Describe the Issue

trinkets and Xuen are not part of the Rotation

### How to Reproduce

.

### Snapshot (Link)

.

**Comment by Hekili** [comment]
Snapshots are required.
