### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by dsypher2** [Hekili/hekili#3836]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Error at world login
![image](https://github.com/user-attachments/assets/0072082e-ca9a-4958-92d5-32b403e00ff0)

### How to Reproduce

Enter game as demonology warlock

### Player Information (Link)

no snapshots generated

### Error Messages (Link)

https://pastebin.com/qDX1b8eL

**Comment by Hekili** [comment]
Fixed in 1.0.16a.
