### ISSUE TITLE
Sin Rogue ST rotation saying to use tempest when there is only 1 target present

### ISSUE THREAD

**Issue by OppYchan** [Hekili/hekili#3837]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

When hitting target dummy or bosses when there are no other mobs in range it sometimes says to use tempest in the rotation. It doesnt happen 100% of the time so its a bit weird.

### How to Reproduce

Spec into tempest on a hybrid build. Do rotation on a target dummy with no targets around. 

### Snapshot (Link)

https://pastebin.com/iPmVYANd

**Comment by Sedveth** [comment]
It’s correct in simc, in hybrid build, we use CT in single target as well
