### ISSUE TITLE
[REC] Blood Death knight rotation issue

### ISSUE THREAD

**Issue by Cheetah714** [Hekili/hekili#3838]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Blood

### Describe the Issue

as Deathbringer we getting buff each time Reaper's Mark explodes - but the rotation rarely consume Exterminate buff , the exterminate deal massive dmg overall and also reduces the rune resources we need to cast Marrowrend , one more issue the rotation suggest Tombstone while im only at 4 stacks of Bone Shield , and even so my dancing rune weapon is of cd its still suggest tombstone , we use tombstone not just for shield but also to reduce the dancing rune weapon cd
![image](https://github.com/user-attachments/assets/55c64d40-1116-455b-a01e-aaeff90a9d5d)

### How to Reproduce

1. enter the game as Deathbringer
2. get Reaper's Mark , Painful Death , Exterminate Hero talents
3. follow the rotation

### Snapshot (Link)

Exterminate buff issue https://pastebin.com/8xyEipKz / Bone Shield at 4 stacks https://pastebin.com/c0FJVjni / Dancing Rune Weapon of cd issue https://pastebin.com/MzRCM5x2

**Comment by Hekili** [comment]
This was raised in another ticket; Exterminate stacks get consumed when you have 2 or if your last stack is going to expire soon or just by chance if you need to generate Bone Shield stacks with Marrowrend anyway.

I have just made a change that ensures this occurs both during and outside of DRW.
