### ISSUE TITLE
Sin Rogue Deathstalker - Recommending ambush at the wrong time

### ISSUE THREAD

**Issue by OppYchan** [Hekili/hekili#3839]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Rotation is recommending ambush when you are in stealth and you already have the darkest night buff (This will reapply the market). 

If you have the darkest night buff, it should recommend garrote, garrote, rupture.... etc then pop the mark with max combo points.

![Rogue Opener with Darkest Night](https://github.com/user-attachments/assets/b49d9562-d9a4-482a-aebb-e30ce6971208)

### How to Reproduce

Go to open on a pack from stealth when you have the darkest night buff and it will recommend ambush.

### Snapshot (Link)

https://pastebin.com/c2R1nJWh

**Comment by syrifgit** [comment]
There have been numerous assassin rogue tickets referencing these pictures, and they are out of date with the class guides and sims. This snapshot is following the assassin rogue sim perfectly from what I can tell. Please provide a sim showing that this is not the correct behaviour.

**Comment by Hekili** [comment]
The addon doesn't see any debuffs on your actual target, which leads me to think you're probably using action targeting (soft targeting) such that your enemy isn't truly selected. 

Otherwise, the priority as written will Ambush to mark your target.

**Comment by Hekili** [comment]
Thinking more about this, it may be an artifact of moving pack to pack in M+ as well.  I'm going to test requiring Darkest Night to be inactive or no Deathstalker's Mark active at all before Ambushing.
