### ISSUE TITLE
Demonology rotation/prioritization tweaks

### ISSUE THREAD

**Issue by Devilwench** [Hekili/hekili#384]
Please describe your idea or feature and when it would be useful.
Suggested updates to current Hekili prioritization:
- the last 3 components of the tyrant setup if the user is running worldvein, should essentially always be Hand of Guldan, Hand of Guldan, Worldvein, Tyrant.  Current prioritization within the addon has WV after tyrant, which both means the Tyrant will be substantially delayed in picking up the WV buff and for most current users imps won't have time to spawn from the second hand meaning the tyrant is under-buffed by demonic consumption.
- Fairly often Hekili will suggest Demonic Strength right before tyrant, this is wrong. Demonic Strength will be buffed substantially by tyrant and should be used right after tyrant.  Basically the first 2 spells after Tyrant should be hand of guldan to burn shards, spawn imps, then Demonic strength.  
- The explosive potential buff should be refreshed right before tyrant setup (even if it isn't about to expire)
- If you did that EP buff refresh, then you'll want to implode the imps from the hand of guldan right after tyrant.  Basically tyrant, hand of guldan, demonic strength, some spell, implosion.  This will give you maximum imp uptime for remaining imps during tyrant.
- Lastly, if you got all of the above right, you'll want to implode your imps right as tyrant expires because at that point WV buff is still active.

**Comment by Hekili** [comment]
Provide a sim of yourself.

**Comment by Devilwench** [comment]
https://www.raidbots.com/simbot/report/kAQw7BrBeHdCnJrkbnQB61

**Comment by Devilwench** [comment]
BTW, to clarify the 'EP buff should be refreshed right before tyrant setup', it's before the sequence, not immediately before tyrant.  So if it's Implosion, HG, HG, WV, tyrant, or implosion, HG, demonbolt, HG, DB, HG, HG, WV, tyrant, depending on how many demonic cores you have (with implosion, HG, DB, HG, HG, WV, tyrant, if you just have 1 demonic core).

**Comment by wow1989** [comment]
Any progress on this?

**Comment by Lipstopica** [comment]
> Any progress on this?

If simcraft devs dont make changes then nope. He will wait for simc devs most likely but they won't do anything also cus end of expansion
