### ISSUE TITLE
Sin Rogue - Suggestion - Optional CheckBox |  In AOE do not recommend Envenom before deathmark and Kingsbane

### ISSUE THREAD

**Issue by OppYchan** [Hekili/hekili#3840]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

In AOE (M+ specifically) its hard to get out your damage CDs as the pack dies quickly. Envenoming first in aoe (Before deathmark CD window) is in theory better dps but getting deathmark out 3ish globals later will hurt your damage way more. Going directly into Deathmark and Kingsbane will net a lot more damage in most cases from my experience.

It would be great to have a check box to enable or disable this priority recommendation 

### How to Reproduce

I have included a screenshot. Have an option of removing the "Optional" mutilate and envenom before deathmark would smooth out M+ for many rogues I think. 

![Deathmark suggestions - Ass Rogue](https://github.com/user-attachments/assets/3e37df5f-c581-4f8a-8f1b-61c8cd8eec67)

### Snapshot (Link)

https://pastebin.com/vJHGEy0h

### Additional Information

Thank you guys for reviewing this. I love the addon. Let me know how I can help. Would love to get this one in ass rogues rotation features.

**Comment by Hekili** [comment]
It may be difficult to modify the priority to avoid that usage of Darkest Night.

You may try editing your Assassination priority, list: `direct`, entry: `2`, with the following conditions:

`buff.darkest_night.up & effective_combo_points >= cp_max_spend & ( boss | active_enemies = 1 | fight_remains > cooldown.deathmark.remains + buff.deathmark.duration | cooldown.deathmark.remains > 3 * gcd.max )`

I'm genuinely not sure if this will resolve this, but it will require the same Envenom conditions for consuming Darkest Night, plus one of the following:
* You're in a boss fight
* You have a single target (not going to do AOE)
* The fight is expected to last longer than Deathmark's CD + Deathmark's duration
* Deathmark won't come off CD for 3+ GCDs

If that seems to work, I'll consider making it a spec options.

**Comment by Hekili** [comment]
You can reopen this if you test those conditions (now in `direct - 3`, I believe) and find it works for your situation.  I will then consider adding a spec option for it.
