### ISSUE TITLE
WW - Multiple issues with rotation

### ISSUE THREAD

**Issue by Squatty1** [Hekili/hekili#3841]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Windwalker

### Describe the Issue

After the update trinkets, Invoke Xuen and Celestial Conduit is no longer recommended. 

I think the APL is slightly outdated for WW also.

_Hekili can also recommend to use the same attack twice quite often without any parry or miss. This results in the mastery buff dropping off. Getting a snapshot of the latter is impossible as it is not the displayed priority in the list, the same attack is simply not "removed" if you will._ - possibly fixed cannot seem to replicate it this morning..

### How to Reproduce

1. start combat with any target that should trigger big cd's - like a dummy, opening rotation and recommendation is not aligned with APL

### Snapshot (Link)

https://pastebin.com/R7NwPqci

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ukfVXA4eh81uwKqZckHDZt

**Comment by scoofz** [comment]
I can confirm that this update messed things up for WW quite a lot. Quite unusable. I rolled back to a previous version and CDs were working fine. Not sure about the APL though.

**Comment by mwojtkowski** [comment]
If you look on Xuen's condition in Hekili and compare it to Sumulationcraft APL

Simulationcraft:
```
(fight_style.DungeonSlice&active_enemies=1&(time<10|talent.xuens_bond&talent.celestial_conduit)|!fight_style.dungeonslice|active_enemies>1)
&cooldown.storm_earth_and_fire.ready
&(target.time_to_die>14&!fight_style.dungeonroute|target.time_to_die>22)
&(active_enemies>2|debuff.acclamation.up|!talent.ordered_elements&time<5)
&(chi>2&talent.ordered_elements|chi>5|chi>3&energy<50|energy<50&active_enemies=1|prev.tiger_palm&!talent.ordered_elements&time<5)
|fight_remains<30
```
Current version of Hekili:
```
( ! boss & active_enemies = 1 & ( time < 10 | talent.xuens_bond.enabled & talent.celestial_conduit.enabled ) | boss & active_enemies > 1 ) 
& cooldown.storm_earth_and_fire.ready 
& ( fight_remains > 14 & boss | fight_remains > 22 ) 
& ( active_enemies > 2 | debuff.acclamation.up | ! talent.ordered_elements.enabled & time < 5 ) 
& ( chi > 2 & talent.ordered_elements.enabled | chi > 5 | chi > 3 & energy < 50 | energy < 50 & active_enemies = 1 | prev.tiger_palm & ! talent.ordered_elements.enabled & time < 5 ) 
| boss & fight_remains < 30
```
Problem is how Simulationscraft APL was converted to Hekili, first part of that condition should be 
`( ! boss & active_enemies = 1 & ( time < 10 | talent.xuens_bond.enabled & talent.celestial_conduit.enabled ) | boss | active_enemies > 1 ) `

As for Trinkets/Celestial Conduit they are not suggested because their conditions depend on Xuen's cooldown/buff

In version v11.0.2-1.0.14a Xuen works properly
```
( ! boss & active_enemies = 1 & time < 10 | boss | active_enemies > 1 ) 
& cooldown.storm_earth_and_fire.ready 
& ( target.time_to_die > 14 & boss | target.time_to_die > 22 ) 
& ( active_enemies > 2 | debuff.acclamation.up | ! talent.ordered_elements.enabled & time < 5 ) 
& ( chi > 2 & talent.ordered_elements.enabled | chi > 5 | chi > 3 & energy < 50 | energy < 50 & active_enemies = 1 | prev.tiger_palm & ! talent.ordered_elements.enabled & time < 5 ) 
| boss & fight_remains < 30
```

**Comment by syrifgit** [comment]
You are not simming an equivalent scenario. You provided an AoE snapshot, but a single target sim. Please choose one or the other and provide the sim and snapshot.

**Comment by Hekili** [comment]
I've made adjustments to Xuen which should also make SEF used more often.  Try 1.0.16c and let me know if you are still having trouble.

**Comment by mozza1155** [comment]
why simc Conduit of theCelestial ?

**Comment by kpaule** [comment]
> I've made adjustments to Xuen which should also make SEF used more often. Try 1.0.16c and let me know if you are still having trouble.

The adjustment looks successful, and Xuen is again recommended.

**Comment by Hekili** [comment]
Thanks.  I plan to add one more modification to ensure Tiger Palm doesn't break Hit Combo when moving pack to pack.
