### ISSUE TITLE
[REC] Hammer of Light recommended with insufficient Holy Power

### ISSUE THREAD

**Issue by benkimball** [Hekili/hekili#3845]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Protection

### Describe the Issue

Starting with commit 5c61d302, Hekili began recommending Hammer of Light when I had only 2 holy power. By reverting [this change](https://github.com/Hekili/hekili/commit/5c61d302c96cac4dfb03a5ae85edc0a5ee8a822e#diff-da112ed019b7b1c7a32cbf91c042698eb1e3e4c44dde34dc3d00b7e6abea2b78L912) to `PaladinProtection.lua`, the previous behavior (Hammer of Light only recommended with 3 holy power or more) was restored.

### How to Reproduce

1. Enter the game as protection paladin
2. My talent build: CIEAE74QAafj6bdTrgpLZS4VlvNjZwix2DYGzMW2MzMmxMzYGAAAAAAAAAA0WDzMziBmZYmZxgxsBAjBAwAGgBAYmptZZWmBIwmZA
3. Attack target dummy and follow recommendations
4. The third time Hammer of Light is recommended, around 60s into the fight, observe that it cannot be cast because you only have 2 holy power

### Snapshot (Link)

https://pastebin.com/BWFUyxac

### Additional Information

I can reliably fix the issue locally by reverting that change to the PaladinProtection.lua file. (I keep all my addons in a git repository so that I can easily see changes.)

**Comment by Hekili** [comment]
I will test a fix (updating `reset_precast` in PaladinProtection.lua to replace existing code with:

```Lua
    if IsActiveSpell( 429826 ) then applyBuff( "hammer_of_light_free" ) end
    if IsActiveSpell( 427453 ) then applyBuff( "hammer_of_light_ready", 12 - ( query_time - action.eye_of_tyr.lastCast ) ) end
```
