### ISSUE TITLE
[REC] Not recommending comet storm

### ISSUE THREAD

**Issue by Stoufs** [Hekili/hekili#3847]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Frost

### Describe the Issue

not recommending comet storm

### How to Reproduce

any combat including dummies

### Snapshot (Link)

https://pastebin.com/fGEsvM1B

### Raidbots Sim Report (Link)

na

### Additional Information

na

### Contact Information

na

**Comment by Hekili** [comment]
I will modify Comet Storm to cast at max Splinterstorm stacks until/unless action.splinterstorm.in_flight is implemented.
