### ISSUE TITLE
[REC] Immolate reccomended when all targets freshly dotted

### ISSUE THREAD

**Issue by yenbounger** [Hekili/hekili#3848]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Destruction

### Describe the Issue

![image](https://github.com/user-attachments/assets/eb4420e7-7cc0-4a7e-b485-7ea2825e79dc)
I have just opened with cataclysm -> infernal and immolate has been reccomended for the next 3 globals - i would expect to see a different generator as I am below 3 soulshards, and would need to build to rain of fire

### How to Reproduce

1. Enter game as a destruction warlock
2. Go to cleave target dummy
3. Open with cataclysm -> summon infernal

### Snapshot (Link)

https://pastebin.com/uiUbctp9

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bcD39m81URYb7mvx7vZJeL

**Comment by syrifgit** [comment]
The trigger for immolate here seems to be

cooldown.cataclysm.remains[28.11] > dot.immolate.remains[25.41] ) & target.time_to_die[417.99] > 11 & ! ( talent.diabolic_ritual.enabled[true] & talent.inferno.enabled[false] )

You also said you opened with cataclysm > infernal, but that's not what I see you casting as your previous 3 spells. Are you not following the opener?

previous_spells:
   1 - rain_of_fire
   2 - ruination
   3 - cataclysm
   
   Can you get a new snapshot of the following
   - Change your hekili to show like 7 buttons
   - Be standing close to all the dummies
   - ONLY cast your first spell, rain of fire (or a generator first if that's required)
   - Take the snapshot

**Comment by Ruffy418** [comment]
I can confirm Hekili is recommending to immolate on multiple targets straight after using cataclysm which has applied immolate to every target already. This happens with diabolist hero talent tree and cataclysm specced on the destro tree and on aoe recommendations.

**Comment by Hekili** [comment]
I will add a check that Immolate is refreshable to that entry.

**Comment by Hekili** [comment]
This was fixed.
