### ISSUE TITLE
update event for use in WeakAuras

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#385]
Another event for WeakAuras similar to `HEKILI_TOGGLE` would be awesome to see when a new ability gets recommended. 
Either an event that passes the display and spellid as an argument or just the event itself to use it with `Hekili_GetRecommendedAbility` (sth like `HEKILI_UPDATE`).

*Why?*
There are several WeakAuras on Wago that use your `Hekili_GetRecommendedAbility` function but update every frame (sometimes one aura for every spell). This would open up more possibilities to use the Hekili recommendation for own WAs or even small plugins. Additionally I'm just unable to find the right function to hook to (searching for 2 hours now 😄 )

**Comment by Hekili** [comment]
That's not an unreasonable request, but requires some thought in terms of implementation.

**Comment by ghost** [comment]
implemented in the latest version
