### ISSUE TITLE
[REC] Ruination proc recommended multiple times as demo lock

### ISSUE THREAD

**Issue by peepeehero** [Hekili/hekili#3851]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

When I get a ruination proc as demo lock with diabolist hero talents, the addon recommends to use the proc in every slot instead of just one slot. This makes it hard to see what's supposed to be used next.
![Wow_2Y8WxPuNw7](https://github.com/user-attachments/assets/81d18932-6f47-4c82-a3ce-5c1ccb36f713)

### How to Reproduce

1. Enter game as Demonology warlock
2. Use Diabolist hero talents
3. Summon the pit lord and get ruination proc
4. The addon will then recommend the ruination proc in all the slots in single target

### Snapshot (Link)

https://pastebin.com/ZvrcptnB

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/73KQJfb2AAeoCtTVJnEG1o

### Contact Information

gypsy on discord

**Comment by syrifgit** [comment]
This is fixed in the newest version, please update once it is available (probably .17a ?)
