### ISSUE TITLE
[REC] If another priest applies power word fortitude, the addon recommends I apply power word fortitude still.

### ISSUE THREAD

**Issue by jsburson** [Hekili/hekili#3852]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Holy

### Describe the Issue

If another priest applies power word fortitude, the addon recommends I apply power word fortitude still. I've verified the fortitude applied by the other priest is the same power as mine (hero talent under archon, 5% more). I just reapply the buff and it is no longer recommended until the other priest applies the buff and then it wants me to apply again.

### How to Reproduce

1. Enter game as holy priest.
2. Group with another priest (shadow).
3. Allow other priest to apply fort.
4. Hekili still recommends I apply fort although I already have it from other priest.
5. Apply fort myself.
6. have other priest apply fort to show hekili again recommends I apply fort.

### Snapshot (Link)

https://pastebin.com

**Comment by syrifgit** [comment]
your pastebin link isn't a link to your copy/paste snapshot, it's just the main website.
