### ISSUE TITLE
Ret pal Hammer of wrath low priority

### ISSUE THREAD

**Issue by Kahdam** [Hekili/hekili#3854]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

 noticed that hammer of wrath is the last builder pushed in single target situation, when we prefer pressing it over other builders if:
if HP <=3
AND target health <20% (35% if vengeful wrath is talented)  OR during avenging wrath

### How to Reproduce

1.Enter game as a ret paladin with herald of the sun hero talent
2.Talent into Hammer of wrath / vengeful wrath / final verdict / vanguards momentum / wake of ashes / blessing of an'she
3.start single target combat 
4.see first 10 reccomandations
5.play until after the first wake of ashes
6.Spend holy power with final verdicts and follow rotation until you have blade of justice recomended while having a procc of hammer of wrath

### Snapshot (Link)

https://pastebin.com/jBVf9Z54

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/r9VcMi2gjvBLx31Z9BLeh2

### Contact Information

165132836163026944 (discord id)

**Comment by syrifgit** [comment]
your snapshot does not include wake of ashes, avenging wrath, or a low HP enemy. Your wake of ashes is failing a range check. 

Are you using action targeting mode?

**Comment by Kahdam** [comment]
How can I check for the action targeting mode ?
I snapshot during prepull that might be why, should I take the snapshot the frame I refer to, or after an amount of time ?
I thought it considered the let's say 5th recco based on the 1,2,3,4 reccos as they were pressed and gave the related buffs

**Comment by syrifgit** [comment]
You should take the snapshot when the recommendation is wrong. So in your case, do it when you think the addon should be saying "Hammer of Wrath". but it isn't. So like during wings, or during low HP enemy.

Action targeting is where you don't need to click on enemies to target them. Moving your camera around automatically selects targets.

**Comment by Kahdam** [comment]
I'll do for the snapshot thanks, and no I'm not using this mode

**Comment by Kahdam** [comment]
should be right there 
https://pastebin.com/yGux3B0h

**Comment by cremor** [comment]
You did not have a Blessing of An'she proc in this snaphot. So it is correct that Blade of Justice had a higher priority than Hammer of Wrath.

**Comment by cremor** [comment]
Sorry, please ignore my last comment. It looks like the Blessing of An'she proc is not an actual buff.

@syrifgit Looks like Hekili needs to be changed to not search for a Blessing of An'she buff, but instead check if Hammer of Wrath is usable even if it shouldn't be based on all other conditions (HP % of target, Wings up, ...).

**Comment by cremor** [comment]
Sorry, please ignore my last comment (which I've now deleted). It was wrong.

Here is a snapshot with an active Blessing of An'she buff: https://pastebin.com/k9ZX4se4
Hammer of Wrath is correctly shown here. So I can't reproduce the problem.

@Kahdam Please provide more details or provide a snapshot that actually shows the problem.

**Comment by syrifgit** [comment]
No further updates received
