### ISSUE TITLE
[FEATURE] Rogue - Reserve Vanish Charge Option when Without a Trace talented

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3855]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

All Rogue specs can talent into Without a Trace to provide a second vanish charge. While it will be always be optimally damage wise to use two charges whenever possible, there can be situations where you might want to keep a charge available - e.g. before a damage amp or for a mechanic cheese.

Would be nice if there was an option to reserve a vanish charge if this talent is active (bonus if it can be toggled with a keypress).

I know you can hotkey a custom ability list but I think this will turn off vanish completely rather than only if one charge is available?

**Comment by Hekili** [comment]
Can you elaborate on this?  Wouldn't you have Cooldowns -- and therefore Vanish -- toggled off before a damage amp phase?  There is a similar setting for Windwalker Monk, where Storm, Earth, and Fire is allowed to spend one charge while CDs are toggled off, but it sounds like your scenario starts from a non-default configuration.

**Comment by fzarr** [comment]
I believe this was mainly for outlaw rogue where you would want to save a vanish to go into a crackshot window or vanish for a mechanic cheese and since outlaw doesn't really hold cooldowns you'd probably never toggle them off for an extended period. 

There could also be a situation where the optimal sim dps uses two vanishes aggressively back to back, but the value of using the second vanish isn't that high and it might be better to hold that second vanish usage for 30 seconds later if adds are going to pop out and you want to vanish to spread bleeds or you're going into a new pack shortly afterwards.

**Comment by johnnylam88** [comment]
I think the closest comparable is the slider for havoc demon hunter to reserve 0/1/2 Fel Rush charges. Fel Rush grants a buff upon use that creates a short DPS window, but Fel Rush is often held for utility purposes as well. 

I think the option can be similarly added for Vanish on rogues that fakes the number of available charges.
