### ISSUE TITLE
[REC] Hekili does not factor in Bladestorm duration in Fury.

### ISSUE THREAD

**Issue by IronMongrel** [Hekili/hekili#3858]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Fury

### Describe the Issue

Hekili does not take the duration of bladestorm into consideration. This can cause unexpected last-second changes to the recommendations.

### How to Reproduce

Use Bladestorm when cooldowns will come up during the channel.

### Snapshot (Link)

https://pastebin.com/4KT6QWSi

### Contact Information

IronMongrel

**Comment by syrifgit** [comment]
Can you get a snapshot of the actual issue? You aren't casting blade storm here. And ideally show more than 1 icon for the snapshot if you can

**Comment by johnnylam88** [comment]
This is just generally a problem with Bladestorm, which does not behave like a typical channeled spell. The cast time is instant, but there is a *hidden* channel component where even though there is no cast bar and it appears abilities can be used, the warrior is locked out of doing anything until the Bladestorm has finished or you explicitly interrupt the channel with a `/stopcasting` macro.

**Comment by IronMongrel** [comment]
It applies a buff, with a duration that goes down with your haste. You could probably make it predict that buff and make the priority helper not recommend things until after that buff is completed.

Also @syrifgit I'm sorry it's hard to snapshot the issue -- I tried to take a snapshot right after it changed from recommending a basic rotational ability to odyn's fury when odyn's fury came off cooldown during my bladestorm.

It's hard to time.

**Comment by johnnylam88** [comment]
I see that the Bladestorm code tries to set the cooldown of `global_cooldown` to the remaining time of the Bladestorm buff.

**Comment by Hekili** [comment]
Thanks, I will add this additional spell ID for Bladestorm and it will advance the clock accordingly.
