### ISSUE TITLE
[REC] Windwalker CDs not being recommended

### ISSUE THREAD

**Issue by Slayor09** [Hekili/hekili#3859]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Windwalker

### Describe the Issue

Before and immediately after entering combat my trinket (Imperfect Ascendency Serum), Storm Earth and Fire, and Xuen are all shown as recommendations however as I begin my rotation those are all removed from the recommendations and do not show up again until I leave combat. This has happened in LFR as well as on the target dummy.

### How to Reproduce

1. Enter game as Windwalker.
2. Enter combat
3. Follow addon recommendations and watch for the CDs to disappear as a recommended next ability

### Snapshot (Link)

https://pastebin.com/Ne2SFKXw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/uESaSgA9wFLBH4A1rNhpXG

### Contact Information

slayor (Discord)

**Comment by syrifgit** [comment]
The addon told you to use Storm earth fire first? Are you sure you followed it right? If it did, that's probably the issue.

Can you get a snapshot before you cast SEF, early in combat?

**Comment by Slayor09** [comment]
Yes, as soon as I press SEF, then Xuen disappears and never reappears. Here is the pastebin for after starting combat but before pressing SEF.

https://pastebin.com/yGPDEPSD

**Comment by Hekili** [comment]
There's a little nuance with the opener that may need further revisions, but I have a fix for this prepped for the next release.
