### ISSUE TITLE
[Aug] Hekili Suggestions Disappear During Empowered Spells

### ISSUE THREAD

**Issue by Irenside** [Hekili/hekili#3861]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

Hekili suggestions disappear while "channeling" empowered spells.

### How to Reproduce

1. After casting Ebon Might and then during the channeling of Fire Breath, the entire bar of suggestions disappears until casted.

### Snapshot (Link)

https://pastebin.com/JEBuTJaY

**Comment by Hekili** [comment]
I'm not able to replicate your report, and your snapshot doesn't show this issue occurring.  Can you take the snapshot when recommendations disappear, if this still happens in 1.0.18 or later?  Thanks!

**Comment by Irenside** [comment]
It was just during Fire Breath and 18 looks to have fixed it. Thanks again for your hard work.

**Comment by Irenside** [comment]
Still happening, not sure how to get the keys alt+shift+[ pressed in the time it takes to cast an empowered spell. I'll keep trying but possible feature may to be able to key bind the snapshot.

**Comment by Bingo176** [comment]
![image](https://github.com/user-attachments/assets/ca66d5ea-cfca-4834-b76c-b3795df3caea)

Toggles>Troubleshooting>Snapshot

Set binding here.

**Comment by Irenside** [comment]
Got it! Although the snapshot shows N/A, which I'm guessing is correct because the display wasn't showing. Only happens to Fire Breath (not Upheaval). When I start casting a level 3 Fire Breath, the display disappears until I release it. Then it goes back to normal operation.

https://pastebin.com/fWzLVBtQ

**Comment by Irenside** [comment]
Thank you again, looks good.

**Comment by Irenside** [comment]
Reopening and thank you again! Happening in 20a.

Clicked at 3rd empower: https://pastebin.com/EhamctCM
Let it time out: https://pastebin.com/vHuUDaJY

**Comment by Hekili** [comment]
20a is outdated now.

**Comment by Irenside** [comment]
Same on 21: https://pastebin.com/gsQiAsHR
