### ISSUE TITLE
[REC] Under specific talents, the output priority of balance seems to have an issue.

### ISSUE THREAD

**Issue by lie5860** [Hekili/hekili#3862]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

There seems to be a slight issue with the output loop in this balance talent setup when using the default configuration. During mono-output, when the energy is full, it does not use skills that consume these energies, such as [Starsurge]. This seems to occur intermittently, after using [Force of Nature] or [Convoke the Spirits]. I switched to another talent that does not have these two skills and it functions normally. Here is the list of talents.
**CYGAqvgeoHLefPLb/Pa8nkKXDBAAAAAAAAAAAAAAAAAAWGFMzMjBzAmZGzMDG2GjxMz2MWwMzMjtZMzYGjNwCAGLLzstsMzysNTzMLzUAAIA2MzwA**

![image](https://github.com/user-attachments/assets/fef47090-1d7f-4c39-9474-d30d94370337)

Is there any way to resolve this issue?

### How to Reproduce

1. Operate with the Balance Druid and use the inherent Balance simc configuration of Hekili.
2. Use the talents attached in the above description.
3. Output based on the recommended skills from Hekili.

### Snapshot (Link)

https://pastebin.com/a8rgH8dD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/vVQ1uUijGwgCU8GsaQWNaz

**Comment by Hekili** [comment]
To compare with your sim, you'd need to run a 5-target sim.  Your sim is using the single-target action list while in-game, you are in a multi-target scenario.

You don't have Starfall, and Starsurge usage in AOE is gated behind two buffs:
* `buff.starweavers_weft.up[false] | buff.touch_the_cosmos_starsurge.up[false]`

You don't have either of the relevant talents for these buffs, so I don't think the sim would cast Starsurge in AOE for you either.

I'll make an edit to address this, though the takeaway is *probably* that this is not an optimal build for AOE.

**Comment by lie5860** [comment]
I apologize as this was my mistake. I've been using a single-target talent. However, when training against a single dummy in the game, my skill's AoE can hit other minions, which results in a deviation. If I set the Hekili's rule to single-target, it will correctly use Astral Power. Here is the link for  5-target sim. https://www.raidbots.com/simbot/report/9BwiFNKPnt7xzRDC5Vubvo 
If the results are the same as Hekili's, then there's no need for adjustments. The issue lies with my talent choices.

**Comment by Hekili** [comment]
Yeah, in your 5-target sim, you do a surprising amount of damage despite never spending Astral Power.  I went ahead and made adjustments in the next release to spend with Starsurge if you don't have Starfall or Starweaver or Touch the Cosmos.
