### ISSUE TITLE
[REC] Enhancement Default Priority Does Not Reflect Latest SimC Priority Update

### ISSUE THREAD

**Issue by rivengh** [Hekili/hekili#3867]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

With commit 894b5d97c71ced4a2bdf0bf5c819c552b96a906b, the Enhancement Shaman SimC Priorities in `TheWarWithin/Priorities/ShamanEnhancement.simc` have been updated, while the default priority package in `TheWarWithin/ShamanEnhancement.lua` does not reflect this. The package string in [line 2744](https://github.com/Hekili/hekili/blob/894b5d97c71ced4a2bdf0bf5c819c552b96a906b/TheWarWithin/ShamanEnhancement.lua#L2744) has still the same old content.

### How to Reproduce

1. Install latest Hekili release [v11.0.2-1.0.17](https://github.com/Hekili/hekili/tree/v11.0.2-1.0.17)
2. Inspect Enhancement Shaman default priorities

### Snapshot (Link)

n/a

**Comment by syrifgit** [comment]
He has a process in place to manage simc updates already, no need for a ticket.

**Comment by syrifgit** [comment]
Actually, I misread your ticket. Will submit a change to sync up the pack string with the simc file in the addon.
