### ISSUE TITLE
[REC] Casting any spell with cast time will prevent Ancestral Swiftness recommendation until end of current cast.

### ISSUE THREAD

**Issue by mwojtkowski** [Hekili/hekili#3869]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

Casting any spell with cast time will prevent Ancestral Swiftness recommendation until end of current cast.
Looking at snapshots it seems like Hekili is putting Ancestral Swiftness on cooldown whenever player is casting spell that has cast time

### How to Reproduce

1. Enter game as Elemental shaman
2. Use Single Target build from wowhear (Farseer)
3. When Hekili will suggest Ancestral Swiftness start casting spell that has cast time
4. Ancestral Swiftness icon will disappear until you finish your cast

### Snapshot (Link)

Snapshot when not casting
https://pastebin.com/DaVi9MsQ

Snapshot when casting Lightning Bolt and Ancestral Swiftnes is ready to use 
https://pastebin.com/kNgE6sfu

**Comment by syrifgit** [comment]
I've identified the issue and will submit a fix.

**Comment by Hekili** [comment]
Resolved in 1.0.17a.
