### ISSUE TITLE
MW monk  monastery stacks

### ISSUE THREAD

**Issue by livery1** [Hekili/hekili#3870]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Windwalker

### Describe the Issue

Mistweaver spec wasnt an option in the dropdown menu, so I picked ww

Tiger palm on MW monk, hekili is prioritizing black out kick and rising sun kick on and im losing ton of dmg because im not getting monastery stacks. Tiger palm gives stacks of teachings of the monastery, which is required for enhancing dmg of blackout kick. This is basic rotation for like 3-7 targets to maximize dmg and then transferred to healing. You can actually see hekili wanting to do the rotation of 2x tiger palm and then black out kick, but soon as its the next button to press, it changes back to either rising sun kick or blackout kick postponing the tiger palm and therefore not getting any stacks of monastery

Please take a look at the picture in the 1st comment, as you can see tiger palm is nowhere to be seen, meaning you get no teachings of the monastery stacks, and therefore there is almost no point pressing blackout kick
could someone help me set this up, prioritizing tiger palm to be shown as top priority when there are no teachings of the monastery stacks active? or maybe less stacks then 2 ?

I  tried asking on your discord but unfortunately got zero responses, so I wanted to try it here

### How to Reproduce

1. log mw monk
2. try either AOE or ST rotation 
3. ideally turn off spinning crane kick so its not used as filler as much
4. see tigerpalm being delayed in both rows because either rising sun kick or blackout kick is always prioritized

### Snapshot (Link)

https://pastebin.com/UVf3vq64

### Contact Information

Livery#1198

**Comment by livery1** [comment]
![Screenshot 2024-09-27 203650](https://github.com/user-attachments/assets/85783d14-ac82-49c5-9e2b-3776b5dd7351)

**Comment by Hekili** [comment]
Thanks; the priority wasn't revised to account for Teachings of the Monastery becoming baseline.  I'll be adjusting that.

**Comment by Hekili** [comment]
Fixed in 1.0.18.
