### ISSUE TITLE
[REC] Frost Death Knight rotation issue

### ISSUE THREAD

**Issue by Cheetah714** [Hekili/hekili#3875]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

as Frost dk i expect the add-on to recommend reaper mark before pillar because we don't want use reaper mark during pillar because we want to get as many killing machine obliterate as possible during pillar and it can happen very often that you have two killing machine procs but not enough runes to use obliterate , also droping DnD during breath of sindragosa it should be before it ? we should prioritizing spending runes to keep up breath , also the addon suggest use howling blast precombat 

### How to Reproduce

1. Enter game as a Frost Death Knight.
2. take Deathbringer hero talent, Breath of Sindragosa build ( CsPAtbMOTHlnKIwUyAn+DK70SPAMzYMMDDzMjZmZGmZmpZGDjBMzYMjZmZmZmZZmBAAAAAAAAAAAYzsNbmtZYsww2MbTDNjFMzYMDA )
3. follow the rotation

### Snapshot (Link)

Reaper Mark issue : https://pastebin.com/j4yKbtyv  /  DnD during BoS  https://pastebin.com/pp0nTUzt

### Raidbots Sim Report (Link)

breath of sindragosa ST : https://www.raidbots.com/simbot/report/85SkZJKkP4j1Gvk7smstFe / breath of sindragosa 5 target https://www.raidbots.com/simbot/report/wr1M5gMAuckxksc4gKJbtE / no-breath ST  https://www.raidbots.com/simbot/report/6ixvofjyGjBuRX7sTN97Mj / no-breath 5 target https://www.raidbots.com/simbot/report/fw7CQZUgM3nHfEDj4Wdtqe

**Comment by Hekili** [comment]
> as Frost dk i expect the add-on to recommend reaper mark before pillar because we don't want use reaper mark during pillar 

![image](https://github.com/user-attachments/assets/e1e44242-433c-44a0-a289-41790c33f38e)

Without Breath of Sindragosa (per your first snapshot), Reaper's Mark is explicitly written to be used with PoF up (or at least on cooldown for 10 more seconds).

> also droping DnD during breath of sindragosa it should be before it ?

![image](https://github.com/user-attachments/assets/add3d66c-f002-462a-9ef5-f23b8d99523a)

You can see Death and Decay falling off during BoS and being recommended during BoS.

> also the addon suggest use howling blast precombat

It doesn't.  The Frost priority has no precombat actions at all.
