### ISSUE TITLE
[BUG] Action Bar Icons Disappear (SpellFlash?)

### ISSUE THREAD

**Issue by Soeroah** [Hekili/hekili#3876]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Somehow, some of my spells and abilities are invisible while using this addon. Turning the addon off made them reappear, but ever since I installed it, any character using Hekili has had icons vanish from the action bar, though mousing over the area they were still shows the tooltip and the abilities are still usable.

### How to Reproduce

All that seems to be needed is playing the game normally with Hekili installed.

### Player Information (Link)

No snapshots created

### Error Messages (Link)

No error messages created

### Additional Information

The addon itself doesn't seem to register an error so there's nothing I can screenshot, but two of my abilities on my evoker are now invisible after doing a follower dungeon

**Comment by Hekili** [comment]
Is there any chance that you have "Button Blink" enabled in /hekili > Displays > (whichever) > SpellFlash?

![image](https://github.com/user-attachments/assets/0606ec20-d2a8-47b3-adc0-156362537d49)

**Comment by Soeroah** [comment]
That seems to have fixed the issue, as far as I can tell
