### ISSUE TITLE
Unholy DK San'layn rotation flicker

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#3877]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

AOE 5 targets the rotation starts to flicker. Vampiric Strike will insert into the rotation and disappear instantly. Starts happening when the outbreak spam starts.

### How to Reproduce

5 target dummies 
AOE and follow prompts

### Snapshot (Link)

https://pastebin.com/Vu26Ke6n

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/itJytWeshazBrjRAXSWQfz

### Additional Information

https://pastebin.com/bLUAZVdm

additional snapshot.

**Comment by Hekili** [comment]
Testfix noted in other open ticket for same issue.
