### ISSUE TITLE
[BALANCE DRUID] No Starfall recommendation with 2+ target. 

### ISSUE THREAD

**Issue by Aspirinag** [Hekili/hekili#3879]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

in multitarget situations, for AOE or Auto setting, Starfall is not suggested.

### How to Reproduce

1. Enter the game as Balance Druid
2. Take Starfall
3. Fight with dummies and follow AUTO or AOE suggestions

### Snapshot (Link)

https://pastebin.com/hKuyVV3P

### Contact Information

Lelloh (Discord ID)

**Comment by comfreak89** [comment]
Can confirm - same here since today. Nothing changed. Profile already resetted, no change.

**Comment by Hekili** [comment]
This is fixed in the latest release.

**Comment by comfreak89** [comment]
yes - can confirm. thanks
