### ISSUE TITLE
Vendetta not being recommended again after opener

### ISSUE THREAD

**Issue by RyanTamulevicz** [Hekili/hekili#388]
My guess is Vision of Perfection but I'm not sure. For some reason it also looks like it will only recommend Vendetta if stealth or Subterfuge are up.

[Assass Rogue Snapshot.txt](https://github.com/Hekili/hekili/files/4907439/Assass.Rogue.Snapshot.txt)

**Comment by Exsol-bit** [comment]
I was about to post a similar issue up with Vendetta & Vanish not being suggested.

There is another post [https://github.com/Hekili/hekili/issues/371](here) where the response suggest that if you're testing on target dummies (or solo) it wont suggest vanish, which would also mean it won't suggest Vendetta as well as the action priority list wants to cast Vanish _before_ Vandetta.

Hopefully Hekili can confirm at some point, but it might be the case.

**Comment by Hekili** [comment]
Exsol-bit's comments are correct.  Vendetta relies on you Vanishing to trigger Subterfuge, and Vanish isn't recommended on dummies and/or solo (since that would reset your targets).
