### ISSUE TITLE
Shadowmoon Insignia Trinket Missing From Gear and Items Dropdown

### ISSUE THREAD

**Issue by stongecat** [Hekili/hekili#3882]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

The Shadowmoon Insignia trinket isn't available in the Gear and Items dropdown and thus not available to Enable/Disable for my rotation.

### How to Reproduce

1. Open Gear and Items from the menu
2. With the Ret specialization, search for Shadowmoon Insignia from the dropdown
3. See it is not there

### Snapshot (Link)

N/A

### Additional Information

For some reason, the addon wouldn't let me take a screenshot, sorry. :( Hopefully this issues is self-explanatory enough that it doesn't really need it.

### Contact Information

Discord: Stonge

**Comment by syrifgit** [comment]
Please provide the item ID for the trinket
