### ISSUE TITLE
[REC] Enh Sham AoE

### ISSUE THREAD

**Issue by xray1919** [Hekili/hekili#3883]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

swapping to single target prio in aoe fights. after a reload it is fixed for a while but returns at some point

### How to Reproduce

play a bit and wait until it happens

### Snapshot (Link)

https://pastebin.com/PpDBATRa

**Comment by syrifgit** [comment]
Seems like you are 30 yards from the enemies. Provide a snapshot when you're actually in AoE combat and receiving alleged wrong recommendations.

**Comment by Hekili** [comment]
Not able to replicate this issue; snapshot indicates you are out of range (outside 10 yards) of all but 1 enemy.  You can reopen this is you provide a snapshot AND screenshot from the same time, showing your position so I can tell if range detection is an issue.  Thanks!
