### ISSUE TITLE
[REC] Rogue - Scroll of Momentum trinket not recognized

### ISSUE THREAD

**Issue by Grayfox2325** [Hekili/hekili#3885]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

2nd item in the CD action list is Sprint - ( trinket.t1.is.scroll_of_momentum | trinket.t2.is.scroll_of_momentum ) & buff.full_momentum.up. Conditions show as false even when trinket is equipped.

### How to Reproduce

1. Equip Scroll of Momentum trinket as a Rogue.

### Snapshot (Link)

https://pastebin.com/L5KEJ0pS

**Comment by syrifgit** [comment]
You need to provide the snapshot of the display that has sprint on it.

```
        19.  sprint ( cds - 2 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-2:sprint:0.01:Ability Known, Enabled(0.01)
```

Please also provide the correct item ID of the trinket.

**Comment by Grayfox2325** [comment]
![Screenshot 2024-09-29 232123](https://github.com/user-attachments/assets/c503b847-3426-4444-b031-0bd844b8b91b)

I'm not sure which display it's on, there are no required toggles, would that not mean primary display?
Item ID is 226539. Screenshot attached showing conditions not met when equipped.

**Comment by syrifgit** [comment]
The snapshot says otherwise. You are either showing it with your CDs, interrupts or defensives.

That screenshot does work for this case though.
