### ISSUE TITLE
[REC] Demo lock soul strike

### ISSUE THREAD

**Issue by peepeehero** [Hekili/hekili#3887]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

I think the addon sometimes recommends abilities that will overcap shards. In particular I feel like it is not considering the soul strike cast from the felguard thats happening every 10 seconds sometimes. I provided 2 pastebin snapshots the first one is the soul strike thing I'm confused about but the second one it was recommending using infernal bolt when i was already at 5 shards which was super weird.

### How to Reproduce

1. enter game as a demonology warlock
2. follow the general recommended priority of hekili
3. sometimes you will end up casting shadow bolt while soul strike gets you to 5 shards for no reason

### Snapshot (Link)

https://pastebin.com/JmVKjUcy and https://pastebin.com/5bJ4sgja

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/69FwTxD3caX4ESV7Z9BbK8

### Contact Information

gypsy on discord

**Comment by peepeehero** [comment]
Oh also sometimes instead of shadow bolt it will ask you to cast a demonbolt proc which will get you to 5 shards when soul strike is coming off cd in 1-2 seconds so it will overcap

**Comment by syrifgit** [comment]
I cannnot find a single reference to this pet ability in the sims or any of the class guides. Feels like it's not considered by anyone. Non-issue?

**Comment by peepeehero** [comment]
Its a talent that's taken by every guide I've seen and every top log in pretty much every scenario. Its not a part of your rotation because you leave it on auto cast but you should still play around the fact that it is generating a soul shard every 10 seconds.

**Comment by syrifgit** [comment]
There is consideration for soulstrike cooldown in the sim / addon, but the snapshots you provided passed due to other conditions, so the things related to soul strike did not prevent demonbolt from being chosen because of other factors.

The conditions are identical to the sim. So whatever it's doing seems to be correct.

```
 100. demonbolt ( default - 11 )
        The action (demonbolt) is usable at (2.69 + 0.00) with cost of 50000 mana (have 2496028).
         - the action is ready before the current recommendation (at +0.00 vs. +9.13).
         - this entry's criteria PASSES: ( ! debuff.doom.up[false] | ! action.demonbolt.in_flight[false] & debuff.doom.remains[0.00] <= 2 ) & buff.demonic_core.up[true] & ( ( ( ! talent.soul_strike.enabled[true] | cooldown.soul_strike.remains[0.00] > gcd.max[1.34] * 2 & talent.fel_invocation.enabled[true] ) & soul_shard[3.00] < 4 ) | soul_shard[3.00] < ( 4 - ( active_enemies[1.00] > 2 ) ) ) & ! prev_gcd[1].demonbolt[false] & talent.doom.enabled[true] & cooldown.summon_demonic_tyrant.remains[27.89] > 15
```

**Comment by peepeehero** [comment]
Hmm maybe I am slow sometimes on my button presses I'm not sure why. i have noticed it throughout dungeons a lot as well where it will ask me to cast a shadow bolt at 4 shards when soul strike will come up before I can spend the shards and so I'll overcap a shard. I can maybe try to find more examples as I keep playing over time

**Comment by Hekili** [comment]
Fix for next release; Soul Strike added as a hidden ability and it is emulated to fire when it comes off CD (assuming you don't have shards capped).
