### ISSUE TITLE
[REC] Enhancement Shaman - Lava Lash to spread FS vs. LF in AOE

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#3889]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

If we use Pwave or Flame Shock on long range targets, and we have Hothand talent triggered at that moment, it will not recommend Flame Shock and after Lava Lash. The order will be that first Lava Lash then Flame Shock. Or it will always be only Lava Lash without spreading Flame Shock on the target. This is only a problem when the Hothand talent is active. This I think is a disadvantage in AOE because we don't distribute Flame shock to the other targets, and when switching under the active Hothand talent it's a loss of dps. Since we could distribute Flame shock to the targets and then put Lava lash on 6 more targets, thus increasing our AoE damage.

### How to Reproduce

Use Flame shock and Pwave on long-range targets.
Then switch and run up to other targets that are farther away from the ones you used Flame Shock and Pwave on
Get the Hothand buff. 
And there will be no Flame shock then Lava lash recommendation.
There will be a recommendation of Lava lash then Flame shock.

### Snapshot (Link)

https://pastebin.com/vzSUgvKq

**Comment by syrifgit** [comment]
@Hekili Maybe a mistranslation of simc APL?

Addon line
```
        47.  lava_lash ( aoe - 15 )
        The action (lava_lash) is usable at (0.00 + 0.00) with cost of 20000 mana (have 2500000).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
        List ( aoe ) called from ( Enhancement:default:22 ) would PASS at 0.00.
        active_enemies[2.00] > 1 & ( ! toggle.funnel[false] )
         - this entry's criteria PASSES: talent.lashing_flames.enabled[true]
        Action chosen:  lava_lash at 0.00!
        Exiting aoe with recommendation of NO ACTION at +10.00s.
        Returned from list (aoe), current recommendation is lava_lash (+0.00).
        - aoe
        The recommended action (lava_lash) is ready in less than 0.2s; exiting list (default).
        Exiting default with recommendation of NO ACTION at +10.00s.
```

SIMC Equivalent line
`actions.aoe+=/lava_lash,target_if=min:debuff.lashing_flames.remains,if=talent.lashing_flames.enabled`

Other than that I see nothing in the AoE APL (both addon and simc) that indicates needing to Flame Shock first in this scenario.

**Comment by geraint425** [comment]
It is always recommended by the guides to only use Lava lash on targets that already have Flame Shock. Here he just suggests to first press Lava lash and then Flame shock on the target. In practice, we will not be able to spread Flame Shock through the main target. Taking M+ as an example, while we are running we want to use Pwave on the first target and then Flame Shock on the other so that when we press Lava lash on 1 of the targets we get 6 targets. But it happens that at that moment you may have a character to get a Hothand buff and addon ignores the fact that 1 target, which is with Pwave may be a little further away, and Flame shock we have not yet had time to press, and it will recommend Lava lash on any target regardless of the fact that it has a buff Flame shock or not. Getting the Hothand buff breaks the rotation in aoe. So we would extend the Flame shock to other targets via Lava lash even if they die, then we would put a new buff on the next target. And so the addon just uses Lava lash without benefit for us to just click and we lose buffs on new and old targets Flame shock and will already from the second blow trying to distribute Flame shock. It's not right.

**Comment by Hekili** [comment]
> @Hekili Maybe a mistranslation of simc APL?

Nope, it's just unfortunate timing that the APL doesn't seem to accommodate, i.e., when moving from single-target to AOE.  It's hard to demonstrate in SimC because it's not written to show debuffs in the auras column.

There is room to optimize for this -- I did a test sim that does *0.11%* more DPS on average by adjusting that line to target someone with Flame Shock applied -- but 0.11% is *nothing*, and it results in higher variance with lower bottom-end damage.  That most likely means this is an opportunity cost scenario, where when you fortunately have a Flame Shocked target to spread, it's fine, but if you don't, holding the Lava Lash doesn't seem to actually pay off.

I'll share this with Rusah and Purge, who maintain the SimC priority, to see if they have thoughts about how to improve on this, but please remember, you're always free to *not* hit the button the addon recommends and switch to a Flame Shocked target if Lava Lash is up.  You more than likely don't want Lava Lash sitting off cooldown for any significant amount of time, especially with Hot Hand active.

**Comment by Hekili** [comment]
I made minor adjustments in a recent release based on feedback from Purge.  If this is still an issue, feel free to post/reopen.
