### ISSUE TITLE
[REC] Hekili is not finding Sigil of Spite keybind when Precise Sigils is talented

### ISSUE THREAD

**Issue by CR82** [Hekili/hekili#3890]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Vengeance

### Describe the Issue

With the talent "Precise Sigils" the keybind for Sigil of Spite is not shown by Hekili.

### How to Reproduce

1. Enter game as Vengeance Demon Hunter
2. Select Precise Sigils and Sigil of Spite in the talent tree.

### Snapshot (Link)

https://pastebin.com/H3gAkyDk

**Comment by Hekili** [comment]
What is the spell ID of Sigil of Spite when Precise Sigils is talented?

**Comment by CR82** [comment]
389815

**Comment by Hekili** [comment]
Fixed for next release.
