### ISSUE TITLE
Unholy DK San'layn Unholy Assault blocked if desynced from Vile Contagion

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#3891]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

This was on alpha2 with the other San'layn fixes.

Unholy Assault doesn't get recommended at all and if it shows up in the queue it never makes it to the front.

### How to Reproduce

5 target dummies 
AOE rotation

### Snapshot (Link)

https://pastebin.com/5xpT9fAE

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/xexnRxHtHD4vBFqmyRE97L

### Additional Information

In the sim it is used on the 4th gcd or so. I cycled every cooldown then took the snapshot.

**Comment by Hekili** [comment]
It doesn't help to put everything on cooldown.  Can you take a snapshot when Vile Contagion and Unholy Assault are both off-cooldown?

At that time, is Vile Contagion recommended before or after Unholy Assault?

The criteria for Unholy Assault requires that you have 2+ wounds and Vile Contagion is off-CD / coming off CD very soon -OR- that Vile Contagion is not talented.
`( debuff.festering_wound.stack[2.00] >= 2 & cooldown.vile_contagion.remains[34.86] < 6 | ! talent.vile_contagion.enabled[true] )`

![image](https://github.com/user-attachments/assets/35190e24-2978-437e-b670-900352a8235b)

You can see that your opener has Festering Strike + Unholy Assault giving you a bunch of wounds, then Vile Contagion.  This probably comes up if/when Unholy Assault and Vile Contagion get out of sync; it would require some sim-testing to find out the threshold where it's better to allow them to desync than to wait for them to sync again.

**Comment by Bingo176** [comment]
https://pastebin.com/WmTj67dF Raise Abom>Abom Limb> 1 Festering for wounds and held on the Vile Contagion. No UA recommended.

I think that's correct

**Comment by Hekili** [comment]
That makes sense; you're reaching 4 wounds so Vile Contagion goes ahead and spreads them, which makes Unholy Assault criteria not met for the next 90 seconds.  I'll adjust it.

**Comment by Hekili** [comment]
This should be resolved in the next release.
