### ISSUE TITLE
SIN Rogue: Unable to Suggest...Again

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3892]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Doing M+ and doing rotation and couldn't suggest next spells

### How to Reproduce

Follow rotation, aoe, into st

### Player Information (Link)

https://pastebin.com/GGsbUT3u

### Error Messages (Link)

https://pastebin.com/GGsbUT3u

### Additional Information

Also, in ST in AOE Spec, I am not sure that we are supposed to use CT for anything (2 target is ok, not recommended but ok, 3 target is perferred, been doing this alot as well)

### Contact Information

wren#1740

**Comment by Hekili** [comment]
Your previous ticket is still open; I'll add your snapshot there.

**Comment by Hekili** [comment]
edit:  Your snapshot actually doesn't help, because it wasn't taken when the addon wasn't recommending anything.  Nor was CT recommended.  You can provide snapshots that correspond to your concerns in the open ticket (labeling which is which).  Thanks!
