### ISSUE TITLE
[REC] Scalecommander - Do not recommend Prescience in M+ if both DPS have the buff.

### ISSUE THREAD

**Issue by damn2k-tech** [Hekili/hekili#3894]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

When using the Scalecommander hero talents in M+, there are moments when Prescience is being recommended when both DPS are already buffed. If the rotation is followed, this leads to the Tank and Healer being buffed and causes downtime on the buff for DPS. I don't raid, so I don't know whether this is an issue there.
In M+, ideally, you only ever want to buff the DPS with Prescience. 

### How to Reproduce

1. Enter the game as Augmentation Evoker.
2. Play with the Scalecommander hero talents.
3. Enter a 5-man dungeon.
4. Follow the rotation.
5. Check details so see buff uptime.

### Snapshot (Link)

https://pastebin.com/qQ39cXud

### Additional Information

I believe the rotation is working for raid scenarios and for when Chronowarden is selected. It is my understanding that you want to press Prescience on cooldown.
However, for Scalecommander in a 5-man group, Prescience uptime is much lower in general. Therefore, you only want to use Prescience when the buff is absent on at least one of the DPS.

### Contact Information

dinkystick#9129

**Comment by damn2k-tech** [comment]
I attempted to change the logic in the action list for Prescience myself. However, the change caused me to lag out and didn't work correctly.
For reference this is how I attempted to change the logic:
```
**active_dot.prescience < 2 &** ( full_recharge_time <= gcd.max * 3 | cooldown.ebon_might.remains <= gcd.max * 3 & ( buff.ebon_might_self.remains - gcd.max * 3 ) <= buff.ebon_might_self.duration * variable.ebon_might_pandemic_threshold | boss & fight_remains <= 30 ) | cooldown.breath_of_eons.remains <= 8 & talent.wingleader.enabled | evoker.allied_cds_up > 0 & ! talent.wingleader.enabled
```

**Comment by Hekili** [comment]
I've since made adjustments to Prescience (based on the novel Push by Sapphire).  This should be resolved.
