### ISSUE TITLE
[REC] Sub rogue recommends trinkey use when in stealth, which breaks stealth, and then recommends using vanish right after.

### ISSUE THREAD

**Issue by LionRezz** [Hekili/hekili#3895]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

As im going for an opener, the priority helper, recommends that i use my trinket before i open, but it does so in a strange way that doesnt translate well into my understanding of rogue gameplay. It recommends that i stealth, and then use the trinket, which breaks the stealth and then in recommends i vanish, as i ofc want to open in stealth. But it just seems silly to use the trinket that early, instead of just using it mid rotation somewhere instead.

Im currently with a trinket that has a use function that has me target an area, that throws out a boomerang. However, this stealth breaking trinket use also occours when using a stat boosting trinket with no direct damaging use ability.

The issue might have correlation with the characters level, which is not 80. Currently level 78.

### How to Reproduce

1. Play sub rogue, possibly level 70-79
2. Have a trinket with a use
3. go stealth ready to open on the enemy
4. Follow hekili instructions.

### Snapshot (Link)

https://pastebin.com/LTuEpPy1

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/g2nseXXt1LPXEWaqXuGbND

### Contact Information

lionrezz @Discord

**Comment by Hekili** [comment]
Trinkey. 😢

I'll take a look, this should be pretty straightforward.

**Comment by Hekili** [comment]
Fix for next release.
