### ISSUE TITLE
[REC] Sub rogue using backstab/evis rotation instead of using available shadow dance

### ISSUE THREAD

**Issue by LionRezz** [Hekili/hekili#3896]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

Going through the rotation with hekili, it will suddenly stop wanting to use available shadow dance and just seems to want to use backstab/shurikenstorm and evis. A little furhter into the rotation it seems to want to use a shadow dance, but it never seems to dump em both, and prioritizes staying in the backstab rotation over using a shadow dance, which does not seem like a DPS advantage.

### How to Reproduce

1. Play sub rogue
2. Use hekili on a training dummy
3. Follow directions untill shurikenstorm is the recommendation
4. Backstab/evis rotation gets very frequent and seems to want to save shadow dance instead of use them.

### Snapshot (Link)

https://pastebin.com/gU2TfHqC

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/hvsHNYNVHywPT7MFzVUePT

### Contact Information

lionrezz @Discord

**Comment by LionRezz** [comment]
It seems to be correctly done by hekili, but im without a clue why this is the correct rotation. This issue does not seem to need to be solved.

**Comment by syrifgit** [comment]
Looks like it has to do with the unseen blade talent, and/or shadowblades not being up.
