### ISSUE TITLE
[REC] 25% lower AoE dps than sim (Fire mage)

### ISSUE THREAD

**Issue by sixsi** [Hekili/hekili#3897]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Fire

### Describe the Issue

As a Fire mage, I'm doing less DPS than my sim shows. The Combustion window is fine DPS-wise, but outside of Combustion, my DPS drops significantly, and I can't recover with the next Combustion. In my specific case, the sim shows almost 1.9M DPS on 5 dummies during a 3-minute fight, while following the addon recommendations, I'm doing about 1.4M DPS on 5 dummies over 3 minutes, which is around 25% less.

Again, the Combustion window is fine and performs as well as the sim shows, but afterward, something goes wrong, and the addon recommends spamming multiple Fireballs in a row even though I have 3 charges of Fire Blast available.

I took a snapshot around 5 seconds after Combustion when the addon started recommending Fireball spam. I'd appreciate it if you could check the Fire Mage rotation. Thanks for your help!

### How to Reproduce

Enter the game as a Fire Mage.
Use AoE talents from high-ranking players.
Start your rotation on 5 dummies and wait until your Combustion window finishes.
At some point, the addon will struggle with recommendations and suggest spamming Fireballs, even though you have your Fire Blasts back.

### Snapshot (Link)

https://pastebin.com/kp4XfZ0K

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/gseyt7TmznGQdEikPAGWQD

**Comment by sixsi** [comment]
I see the sim casts some Fireballs in a row, but again, something is clearly wrong because I'm doing 25% less DPS on a 3-minute, 5-dummy fight.

**Comment by syrifgit** [comment]
Yeah, you're playing fire mage, that's what happens. Unfortunately fire mage is the 1 dps spec that cannot compete with sim dps using the addon (Currently). It requires some under the hood improvements.

**Comment by johnnylam88** [comment]
Are there any places where these under-the-hood improvements needed are documented? I see this issue is tagged as *backlog*.

**Comment by syrifgit** [comment]
I was just leaving it up to Hek whether or not to close the ticket. Eventually, I will set aside time to go through the spec. Maybe when I do I will reach out for asssistance.

**Comment by Hekili** [comment]
Fire is actually in a much more addon-friendly state than previous expansions.

For a comparison in recommendations to have much value, I'd need a snapshot with multiple recommendations (4+) taken after exiting the Combustion window to see if it differs significantly from the sim behavior.

**Comment by GitBearded** [comment]
> Fire is actually in a much more addon-friendly state than previous expansions.
> 
> For a comparison in recommendations to have much value, I'd need a snapshot with multiple recommendations (4+) taken after exiting the Combustion window to see if it differs significantly from the sim behavior.

Do you want the snapshot just outside of combustion window or when it begins to recommend fireball 3+ times in a row even though you have stacks and instant pyros ready? I can test any and all of this today.

**Comment by Hekili** [comment]
You can test both/all situations, just make sure you note which snapshot is which and why you believe it is wrong at that time.

**Comment by GitBearded** [comment]
Will do. I’ll have these incoming in about an hour.

**Comment by GitBearded** [comment]
> You can test both/all situations, just make sure you note which snapshot is which and why you believe it is wrong at that time.

Do you want the issues I find here or open my own ticket?

**Comment by GitBearded** [comment]
https://pastebin.com/aCS7Tewt - Sunfury AoE Opener not recommending a hard casted Flame Strike on pre-pull.

https://paaster.io/eIiSN5yhZw5N4m-gvECm-#Z46DrqIGty2HC5PiUM7yg0HzolUd-XOfGBpxbG4OBjo - (Sorry for not using pastebin but apparently fire aoe snapshot is too large for free users to post.) This SS is taken as soon as fire ball is being recommended in aoe far more than it should be, it made me hard cast fire ball 4-6 times each test while stacks of Pheonix Flames and Fire Blast were available. This happens with 25 ish seconds left on combustion cd. 
(https://www.raidbots.com/simbot/report/vYA66rYaQWvyNzX6pdkzv2 Here is AoE SIM for both snapshots.)

**Comment by syrifgit** [comment]
> https://pastebin.com/aCS7Tewt - Sunfury AoE Opener not recommending a hard casted Flame Strike on pre-pull.
> 

This is a spec setting you need to enable in the Fire Mage addon settings (or from the minimap icon).

From your snapshot
`pyroblast_pull = false`

This setting allows hard casted pryoblasts and flamestrikes during prepull.

> https://paaster.io/eIiSN5yhZw5N4m-gvECm-#Z46DrqIGty2HC5PiUM7yg0HzolUd-XOfGBpxbG4OBjo - (Sorry for not using pastebin but apparently fire aoe snapshot is too large for free users to post.)

Save it as a .txt file and attach it directly here on Github, if pastebin won't allow it.

**Comment by GitBearded** [comment]
[SunFuryAoE.txt](https://github.com/user-attachments/files/17235396/SunFuryAoE.txt)
Here is AoE Fire ball spam.

[SunfuryFireOpener.txt](https://github.com/user-attachments/files/17235402/SunfuryFireOpener.txt)
Here is the opener recommending Pyroblast as the opener regardless of having pure aoe selected.

**Comment by syrifgit** [comment]
RE: Opener

Flame strike AOE requires 4 targets, but your AOE display is set to 3.

With flame strike build, you still use pyro at 3 targets as per sims and guide. 

Non-issue.

RE: fireball spam

Will check this later

**Comment by GitBearded** [comment]
> RE: Opener
> 
> Flame strike AOE requires 4 targets, but your AOE display is set to 3.
> 
> With flame strike build, you still use pyro at 3 targets as per sims and guide.

Fixed thanks<3
