### ISSUE TITLE
[REC] Bilescourge Bombers not showing up as prio during AOE

### ISSUE THREAD

**Issue by Reshuffling** [Hekili/hekili#3899]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

Doing some testing on the five dummies, I went in to 1:30 combat time without Bilescourge Bombers not being recommended to cast once. 

### How to Reproduce

1. Demo Lock
2. Bilescourge Bombers talent
3. AoE dummies
4. Not get recommended to cast it

### Snapshot (Link)

https://pastebin.com/zVWjq0Nt

### Contact Information

Hardan in Discord

**Comment by syrifgit** [comment]
You didn't talent into the spell.
