### ISSUE TITLE
Arms Azerite Executioner's Precision is wrong in the default execute action list

### ISSUE THREAD

**Issue by KagomeKagome** [Hekili/hekili#39]
The default execute action list is written as "buff.executioners_precision.stack" when it should be "**de**buff.executioners_precision.stack" instead. Changing it makes it work as intended.

**Comment by Hekili** [comment]
I will revisit this.  SimC treats it as a buff, last I checked, so I'll create a workaround if needed.

**Comment by Hekili** [comment]
Fixed in #40.
