### ISSUE TITLE
Hello.  Outlaw Rogue - RTB Rules.

### ISSUE THREAD

**Issue by User4461** [Hekili/hekili#390]
Hi.  New to GitHub and I hope I'm doing this in the right section.

I was trying to figure out how to change the RTB rules on my own for my Outlaw Rogue.  So far I've had some success changing the Blade Flurry rules but I'm having problems with Single Target rules. 

I go to ActionList >  Precombat > and I try to change values for #5 (which I'm assuming is w/o Blade Flurry) and #10 (which is when Blade Flurry is up)

Basically what I'm trying to do is this.

**When on Single Target w/o Blade Flurry** = **Keep ANY 2 Buffs, or Broadside, or True Bearing**.  If 2 buffs, if it's anything with Skull and Crossbones eg. (Buried Treasure & SaC) or ( Ruthless Precision & SaC) or (Grand Melee & SaC) it should force me to reroll since SaC is considered a -1 for a buff.

**When Blade Flurry is up** = **Keep ANY 2 Buffs, or Broadside, or True Bearing, or Grand Melee.**  If 2 buffs, if it's anything with Skull and Crossbones eg. (Buried Treasure & SaC) or ( Ruthless Precision & SaC) or (Grand Melee & SaC) is should force me to reroll since SaC is considered a -1 for a buff.

Any help is greatly appreciated.  I got close once, but I'm wasn't completely there with the setup I wanted.

Thank you!

**Comment by Hekili** [comment]
What have you tried?

**Comment by User4461** [comment]
Hi. Sorry, had to go in and copy what I did.  So here goes.

**For Single Target with without Blade Flurry, I changed this line #5 on the Action List under Precombat.**

**(ORIGINAL)** rtb_buffs < 2 & ! buff.grand_melee.up & ! buff.ruthless_precision.up 
to
**(MY EDIT)** rtb_buffs < 2 & ! buff.broadside.up & ! buff.true_bearing.up

**With Blade Flurry up, I changed this line #10 on the Action List under Precombat.**

**(ORIGINAL)** rtb_buffs - buff.skull_and_crossbones.up < 2 & ( buff.loaded_dice.up | ! buff.grand_melee.up & ! buff.ruthless_precision.up & ! buff.broadside.up )

**(MY EDIT)** rtb_buffs - buff.skull_and_crossbones.up < 2 & ( buff.loaded_dice.up | ! buff.grand_melee.up & ! buff.true_bearing.up & ! buff.broadside.up )

It looks like the Blade Flurry one is working but the ST one wont.  I'm also trying to figure out how to do the 2 buff so that Buried Treasure, Ruthless, Grand Melee don't count as two buffs when paired with SaC.  It should just ask me to reroll.

Please let me know if there is anything else you need.

**Comment by Hekili** [comment]
Rules have been updated since this time.
