### ISSUE TITLE
[REC] Summon Charhound showing up multiple times

### ISSUE THREAD

**Issue by Reshuffling** [Hekili/hekili#3900]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

Summon Charhound shows up several times in a row, I have seen in it in all three spots, but I snapshotted when I saw two. 

### How to Reproduce

Doing normal rotation

### Snapshot (Link)

https://pastebin.com/Lh5tsbaq

### Contact Information

Hardan in Discord

**Comment by Reshuffling** [comment]
[Three Charhound recommended](https://pastebin.com/jLt7u7He)

**Comment by syrifgit** [comment]
Was caused by a Blizzard talent UI error. Changing specs and going back fixed it.

**Comment by Reshuffling** [comment]
[Opening this back up again](https://pastebin.com/irfUi5J6) seems like it still doing it in some cases. I have reloaded and changed specs to try.

**Comment by syrifgit** [comment]
> [Opening this back up again](https://pastebin.com/irfUi5J6) seems like it still doing it in some cases. I have reloaded and changed specs to try.

Did you try staying in the same spec and just changing talent pages? If so, I will re-open the ticket
