### ISSUE TITLE
[REC] Max Shards, get recommended casting another Shadow Bolt

### ISSUE THREAD

**Issue by Reshuffling** [Hekili/hekili#3901]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

Keep testing rotation, I got recommended casting another Shadow Bolt when I was capped on Shards

### How to Reproduce

Just doing standard rotation on dummies.

### Snapshot (Link)

https://pastebin.com/tcBUdTJJ

### Contact Information

Hardan in Discord

**Comment by syrifgit** [comment]
Was caused by a Blizzard talent UI error. Changing specs and going back fixed it.
