### ISSUE TITLE
[REC] Hand of Gul'Dan recommended three times

### ISSUE THREAD

**Issue by Reshuffling** [Hekili/hekili#3902]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

Hand of Gul'Dan get recommended three times sometimes, which you can't use three times in a row.

### How to Reproduce

Still just doing my rotation on dummies(look at the other tickets I have submitted)

### Snapshot (Link)

https://pastebin.com/5rWssJm4

### Contact Information

Hardan in Discord

**Comment by syrifgit** [comment]
Was caused by a Blizzard talent UI error. Changing specs and going back fixed it.
