### ISSUE TITLE
[REC] Sub Rogue, coup-de-grace keybinding

### ISSUE THREAD

**Issue by syrifgit** [Hekili/hekili#3903]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

Coup De Grace doesn't display a keybind, it needs to be defined linked/copied to Eviscerate. It is a spell override from a talent in the Trickster Hero tree.

Putting this here in case someone else gets to it before I do.

### How to Reproduce

Trickster tree

### Snapshot (Link)

Talent string: CUQA27SZpS4XnmFfcXRqkppuwDAMAAAAAAAzyYmlJYZBzMjxMzMzMmZGz2YMjtNzMmZmxYMzysMAAAAmZwAYMbGGYgZRL0iNYA

### Contact Information

syrif

**Comment by Hekili** [comment]
You smell bad!

(This is easy to fix.)
