### ISSUE TITLE
[REC] Sin rogue - scent of blood stacks

### ISSUE THREAD

**Issue by erenmert-2105** [Hekili/hekili#3904]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

I expect my asas rogue to have max stacks of [Scent of Blood] but addon don recomment.

### How to Reproduce

Asas rogue. when [Indiscriminate Carnage] buff is active it should recomment rapture with 3+ combo points or 5+ for [Sanguine Stratagem] till have max [Scent of Blood] stacks but it is kinda hard with 5+ because [Indiscriminate Carnage]  is just 6 sec so 3+ is fine i quess. Please contact me if someting not clear. Thanks.

### Snapshot (Link)

https://ibb.co/NYg1rH0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ftKeyZPpdYqV4CDtVWumK1

### Additional Information

[Scent of Blood] gives agility based on how many targets have rapture on it

**Comment by syrifgit** [comment]
That is not a snapshot, that is a screenshot.

Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by erenmert-2105** [comment]
[st.txt](https://github.com/user-attachments/files/17236167/st.txt)
can i share it like that sory for confusion

**Comment by erenmert-2105** [comment]
394080 - scent_of_blood                           -  12 - 3600.00

this should stack up to 20 when possible

**Comment by syrifgit** [comment]
Turn on target swapping. 
`cycle = false`

![image](https://github.com/user-attachments/assets/9326e0db-295d-4cd4-b664-6bd802c7bb58)
