### ISSUE TITLE
[REC] 11.0.2 HAVOC DH - Raid ST FEL-SCARRED Priority 

### ISSUE THREAD

**Issue by theonex1x** [Hekili/hekili#3905]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Havoc

### Describe the Issue

The priority list for HAVOC DH ST , is not providing the best optimal DPS output as recommended under Wowhead. 

The recommended rotation as per Wowhead is shown below 

https://www.wowhead.com/guide/classes/demon-hunter/havoc/rotation-cooldowns-pve-dps

![image](https://github.com/user-attachments/assets/9685ed20-cf59-461f-ada9-bb9f52d53b53)

Some of the discrepancies noticed are 

1- It recommends Sigil of Flame **before** Immolation Aura  under the precombat
2- It **does not** recommend Vengeful Retreat and Metamorphosis after after the first Death Sweep & Annihilation compo in the opener.  

### How to Reproduce

1- Enter the game as HAVOC DH. 
2- Use the ST Inertia Build Below
`CEkAAAAAAAAAAAAAAAAAAAAAAYGMzMzgZmZMmJmZGAAAAAAwsMmxMMGLzMz2sNLjZGmZBLbwysYGDzmmGMzMzw2G`
3-Test it on Training Dummy

### Snapshot (Link)

https://privatebin.net/?3c9ea67f5e8b9134#83b519Sepqinjwc8Xb5X66fs4wxK9pGh9yudcQrjYtLE

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dNGyxRaQPBKDbjSLg3iDo2/

### Contact Information

theonex1x

**Comment by syrifgit** [comment]
> 1- It recommends Sigil of Flame before Immolation Aura under the precombat

So does your sim. Guides are condensed, less nuanced versions of the sim and not always as accurate.
![image](https://github.com/user-attachments/assets/8419785a-2ffd-4faa-af45-213c83f56b6c)

> 2- It does not recommend Vengeful Retreat and Metamorphosis after after the first Death Sweep & Annihilation compo in the opener.

Get a snapshot of that then. Take it after casting the death sweep, or when that death sweep is up next in the queue.
