### ISSUE TITLE
[REC] Provide a short, descriptive title of you Recommendation issue

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3906]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

I have 5 icons showing. This issue is specifically about how/when Unholy Assault is recommended. Basically, it will recommend Raise Abomination and then Unholy Assault after (correct), but in aoe situations in M+ as soon as you hit Raise Abomination it will not recommend Unholy Assault anymore and will seemingly forever push it back in the que, causing a major desync issue

### How to Reproduce

Enter game as DK, do key, see how it uncouples Unholy Assault and Raise Abomination

### Snapshot (Link)

cant get one

**Comment by aaronlilla** [comment]
disregard, already open issue

**Comment by syrifgit** [comment]
> Snapshot (Link)
cant get one

Snapshots are required. Get one before casting raise abom (when UA is in the queue), and one after casting raise abom (when UA is incorrectly missing from the queue / pushed back)
