### ISSUE TITLE
[BUG] Unholy Unable to make recommendation

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3907]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Auto snapshots taken during M+ key

### How to Reproduce

Enter game as Unholy DK
Do key

### Player Information (Link)

https://pastebin.com/PJHcdkT4

### Error Messages (Link)

none

**Comment by Hekili** [comment]
This would not be the correct snapshot; it provides a full set of recommendations.
