### ISSUE TITLE
[REC] Unholy DK Unholy Assault recommendation being removed after hitting Raise Abomination

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3908]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

Unholy Assault being removed from recommendations after hitting Raise Abomination

### How to Reproduce

Enter game as Unholy DK
Approach dummies, noting next 5 in rotation
Should be Raise Abom -> Dark Transformation -> Unholy Assault
Hit Raise Abom
Notice rotation change, removing Unholy Assault from recommendations

### Snapshot (Link)

https://pastebin.com/QVKQxvRg

### Additional Information

BEFORE RAISE ABOM:
https://pastebin.com/f9t3aAc0

AFTER RAISE ABOM:
https://pastebin.com/QVKQxvRg

**Comment by Hekili** [comment]
Before Abom you had 1 target; after Abom you had multiple. In multi-target, UA looks for 2+ wounds which you didn't appear to have. I'm guessing that condition should only apply if you have the ... spready fun time talent ... so I'll take a look.

**Comment by Hekili** [comment]
Will be addressed in today's release.
