### ISSUE TITLE
[REC] MM target count with Sentinel talents

### ISSUE THREAD

**Issue by mwojtkowski** [Hekili/hekili#3911]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Marksmanship

### Describe the Issue

Sentinel tooltip:
Your attacks have a chance to apply Sentinel on the target, stacking up to 10 times. While Sentinel stacks are higher than 3, applying Sentinel has a chance to trigger an implosion, causing a stack to be consumed on the target every sec to deal (78.3% of Attack power) Arcane damage.

Sentinel aura 
spell id: 450387 
CLEU subEvent: SPELL_AURA_APPLIED, SPELL_AURA_REFRESH, SPELL_AURA_APPLIED_DOSE

Damage part of Sentinel
spell id: 450412
CLEU subEvent: SPELL_DAMAGE

Problem is this aura behave like DoT but in combat log event is shown as SPELL_DAMAGE instead of SPELL_PERIODIC_DAMAGE which I think causes Hekili to count that target as active when it should be ignored (unless option to track DoTted / Debuffed enemies is enabled)

I expect Survival will also have this problem/bug as they use Sentinell in both ST and AoE

### How to Reproduce

1. Enter game as MM Hunter
2. Use AoE build from wowhead (Sentinel)
3. In Marksmanship target options set timeout to 3 seconds
4. Hit AoE target dummies with Multi-Shot few times to stack Sentinel debuff above 3 stacks to trigger it
5. When sentinel triggers just auto attack and wait 3 seconds
6. Hekili will report targets that have/had "ticking" sentinel when it should report only 1 target

### Snapshot (Link)

After triggering dmg part of Sentinel aura
https://pastebin.com/8Z99pm4R

After several seconds of auto attacking single target since triggering Sentinel
https://pastebin.com/wKdtQqz1

**Comment by Hekili** [comment]
I don't understand. It's damage-based target detection and they were damaged. Why shouldn't they be counted? I can potentially filter specific damage but if the target is there and getting damaged, why shouldn't it count?

**Comment by syrifgit** [comment]
Tested with your exact settings, and it works exactly as written. Sentinel is not a DoT by definition, but it is very similar. Once sentinel stops dealing damage to them, after 3 seconds they aren't counted.

I supposed you could recode that sentinel damage as a DoT even though it really isn't. I guess my question is .. when has this mattered? Is it impacting gameplay?

**Comment by mwojtkowski** [comment]
Mobs with that debuff triggered can move outside of your AoE (Multi-shot) range. Every tick of sentinel (450412) will then reset timeout on those mobs and depending on how many stacks you had before it triggered it can tick up to 20 seconds in worst case (10 stacks), which will make Hekili suggest AoE rotation instead of ST.

But yes it is very minor problem which I noticed on Silken Court fight
