### ISSUE TITLE
[REC] The opener on the shaman is crashing 

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#3912]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

The problem appears most often on bos ovinax. If we start for the first time rotation will be as it should start opener. But all subsequent will be complete chaos in the addon. And this will be until the end until I do not make a relog. After the relog everything is back to normal but only once before the first death. After again goes chaos in the addon. I do not know from what this manifests itself. On some bosses the same result happens but not always. 

### How to Reproduce

1. Go to the boss ovinax preferably heroic difficulty.
2. Start the fight on the shaman surrounded by eggs.
3. Make 1-2 deaths on the boss.
4. Then start the fight again with the boss from the beginning
5. There will be a mess of opener and rotation.

### Snapshot (Link)

https://pastebin.com/ZJWLm8s4

**Comment by Hekili** [comment]
Sorry, I don't have any idea what you mean by "mess" or anything described above. What are you seeing, when do you see it, and what do you believe you should see instead?

**Comment by geraint425** [comment]
Patchwerk![1](https://github.com/user-attachments/assets/52753d19-3d35-4bf3-9013-851f3cb39b5b)
Hectic add cleave 
![Screenshot_1](https://github.com/user-attachments/assets/330300fc-11cd-4428-a127-8ad6b4970a35)
At the beginning of the battle until from the eggs have not yet appeared mobs addon should offer rotation as on Patchwerk I want to see an opener like this approximately as on the sim Patchwerk. But the addon at some point after deaths begins to break in rotation. That he when we again start the fight with the boss again, it is no longer as Patchwerk recommendations offers and as Hectic add cleave as if we already have additional targets around the boss and we need to tighten their burst. He just at some point starts playing AOE. Although the addon itself does not show the target counter. But the rotation and opener is not as in one target goes. That's why I say that chaos is going to addon.

**Comment by syrifgit** [comment]
Sounds like a target detection issue. Can you get the snapshot while you're fighting the boss Broodtwister and the addon is wrong? That way we can see what it is detecting. And also include the actual screenshot picture as well, it should record one at the same time as your snapshot.

**Comment by Hekili** [comment]
If this is a target count issue, it wasn't occurring when the snapshot was taken. As Syrif noted, please take a snapshot when the issue is occurring and provide that instead.

**Comment by geraint425** [comment]
https://pastebin.com/WpeuQZ26
https://imgur.com/a/2kn8Fjg
Here's a screenshot+snapshot. It happens after the first wipe on the boss. After rotation, cleave is enabled
