### ISSUE TITLE
[REC] Assassin Rogue - Mutilate filler unused with Darkest Night leading to no-rec

### ISSUE THREAD

**Issue by GAMEBOOK** [Hekili/hekili#3913]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [x] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

On my chat I have some message during fight : Unable to make recommandation for Primary #1; trigerring auto-snapshot

I post it here.

### How to Reproduce

Dummy, Full default addons (deleted and reinstall) on Rogue assasination
[message (1).txt](https://github.com/user-attachments/files/17250051/message.1.txt)

### Snapshot (Link)

https://pastebin.com/nqwYjsMe

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/koC8RjRLrGwZw1kq3WmgcD

### Additional Information

**Comment by Hekili** [comment]
Fixed for next release.

**Comment by GAMEBOOK** [comment]
Thanks
