### ISSUE TITLE
Mage rotation not loading for fire 7.3.5

### ISSUE THREAD

**Issue by trlx7117** [Hekili/hekili#3915]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Fire

### Describe the Issue

I downloaded the latest version from curseforge, but neither in the game nor in the hekili folder is there a lua file for the mage

### How to Reproduce

I downloaded the latest version from curseforge, but neither in the game nor in the hekili folder is there a lua file for the mage

### Snapshot (Link)

https://pastebin.com/VU5qGStJ

### Contact Information

.trlx

**Comment by trlx7117** [comment]
I had to check all the boxes, otherwise he couldn't create a ticket, I'm sorry

**Comment by syrifgit** [comment]
The addon is only supported for retail and Cata classic. You literally clicked a checkbox that says you aren't on a private server.

**Comment by trlx7117** [comment]
> The addon is only supported for retail and Cata classic. You literally clicked a checkbox that says you aren't on a private server.

my question is not that the addon does not work, but that the lua file is missing
