### ISSUE TITLE
[REC] Spellflash not working on Clawing Shadows

### ISSUE THREAD

**Issue by xbotxash** [Hekili/hekili#3916]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

It seems like Spellflash isn't working on Clawing Shadows. It show on the priority list but there is no spellflash on action bars for that spell. 
![WoWScrnShot_100424_141651](https://github.com/user-attachments/assets/8171e4f2-defc-44ee-b436-136c165130c4)

### How to Reproduce

1. Enter game as Unholy DK
2. Take the talent Clawing Shadows
3. Follow rotation shown until it recommends Clawing Shadows.

### Snapshot (Link)

https://pastebin.com/71jNvnaW

### Additional Information

The character i tried this on isn't max level but i've also had a friend with the same issue at level 80.

### Contact Information

Discord: xbotxash

**Comment by syrifgit** [comment]
Probably because you have it in 2 different spots on your actionbars. Manually assigning a keybind from the "abilities" page in the addon settings might help. 

Additionally, just want to point out the addon is designed for max level only, if you choose to use it while levelling you may experience issues. Use at own risk. :)

**Comment by xbotxash** [comment]
The 2 different points on the bar was just to check to see if it was anything to do with the action bar. I have a friend that is level 80 that has the exact same issue with a complete different bar setup. Seems to be the only ability within the addon that has this issue. 

It still recommends it if i use the primary Hekili bar but there is no spellflash on the action bar at all, which is also the same as what my friend is seeing on their DK at cap. I can maybe get their snapsnot later if that helps?

**Comment by syrifgit** [comment]
Did you manually assign the keybind like I said?

**Comment by xbotxash** [comment]
Yeah no luck luck with that either : (
