### ISSUE TITLE
[REC] Free Hammer of Light not shown for Protection

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#3917]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Protection

### Describe the Issue

Hekili doesn't show the free Hammer of Light after consuming 60 stacks of Light's Deliverance for Protection Paladin.

### How to Reproduce

1. Play as Templar Protection Paladin.
2. Get to 60 stacks of Light's Deliverance to get a free Hammer of Light.
3. See that Hekili doesn't show the free Hammer of Light.

### Snapshot (Link)

https://pastebin.com/fW4NyFPh

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9qbXKCk6RZzAtEWhqkyaBt

### Additional Information

This was recently fixed for Ret in #3849, but still doesn't work for Prot.

**Comment by cremor** [comment]
An additional note:
The tuning notes for the next weekly maintenance state: "Templar: Light’s Deliverance now triggers at 50 stacks (was 60)."
But this is only listed for Ret. We'll have to see if they change Prot too, or if they both need different max stack sizes. (If the max stack size even matters for your code.)

**Comment by Hekili** [comment]
Fixed in next release.
