### ISSUE TITLE
[Aug] Upheaval is being recommended when Ebon Might is not active

### ISSUE THREAD

**Issue by Irenside** [Hekili/hekili#3918]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

Upheaval is being recommended when Ebon Might is not active.

### How to Reproduce

Run through Hekili suggestions and desync Fire Breath and Upheaval by a few seconds. Then wait until Upheaval is being recommended (I show 4 icons) and let Ebon Might drop. After several more seconds after Ebon Might is down and Hekili will still show the Upheaval as the next action. Empowered spell shouldn't be recommended unless Ebon Might is active.

### Snapshot (Link)

https://pastebin.com/Fjh27FQy

### Additional Information

Thank you!

**Comment by Hekili** [comment]
This matched the sim priority, as the bolded conditions were met (and were between `|`s meaning "or"):

>- this entry's criteria PASSES: target.time_to_die[515.00] > cast_time[0.95] + 0.2 & buff.ebon_might_self.remains[0.00] > cast_time[0.95] & cooldown.time_skip.up[true] & talent.time_skip.enabled[true] & ! talent.interwoven_threads.enabled[true] | **talent.mass_eruption.enabled[true] & talent.overlord.enabled[true] & cooldown.breath_of_eons.remains[0.00] <= 1 & ! talent.molten_embers.enabled[false] & active_enemies[5.00] >= 3** | empowering.upheaval[false]

The SimC priority has been updated and so has the addon; this should no longer occur in the next release.
