### ISSUE TITLE
Shaman Enhancement remove Earth Elemental rotation TOGGLE off or when cooldowowns OFF not suggested

### ISSUE THREAD

**Issue by spottsy** [Hekili/hekili#3919]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hi, Love the addon for all my alts. I would like to be able to remove 5min coolddown earth elemental from main rotation. Two options either a TOGGLE to turn it off or when cool downs OFF it is not suggested. It is a long cooldown and want to use situationally. I have played all thirteen classes at 80 and this is the only issue other than demon hunter not being able to remove dash and jump back ability but was told it messes up rotation if removed. I cannot remember all rotations for that many but this addon helps me have fun and as I have an illness when tired helps me be focused. Been using for years not thanks. 
TURNING OFF Major and Minor cooldowns doesn't remove from rotation.

**Comment by syrifgit** [comment]
Go to the abilities page in the add-on settings, find it, and assign it to the cooldowns toggle. This will make it turn on and off with that toggle.

**Comment by spottsy** [comment]
Thanks so  much never knew this existed thanks for the reply all fixed
