### ISSUE TITLE
BDK not recommending Marrowrend with Exterminate buff

### ISSUE THREAD

**Issue by OfficialExiled** [Hekili/hekili#3920]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Blood

### Describe the Issue

So, im not 100% sure but I think when you have the Exterminate buff you want to use Marrowrend to maximize damage for ST and even in AOE. But it seems like either it never recommends it or shows it very late when the buff is running out. 

This is additional snapshot that recommends marrowrend but at very late when the buff is running out and not instantly. 
https://pastebin.com/ScGDTLEN

### How to Reproduce

Just do regular rotation and you will get the Exterminate buff but it won't recommend it. 

### Snapshot (Link)

https://pastebin.com/97BMvabf

**Comment by johnnylam88** [comment]
The official guides for BDK recommend Marrowrend when you have 2 stacks of Exterminate, but if you have only one, then wait until an active Reaper's Mark is about to expire before consuming it. 

The reason for that is to avoid capping on a Bone Shield charges unnecessarily, but to use up Exterminate before you gain another 2 stacks.
