### ISSUE TITLE
[REC] Hekili not recommending trinket (Treacherous Transmitter) mid rotation

### ISSUE THREAD

**Issue by Wafflesss736** [Hekili/hekili#3921]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Fury

### Describe the Issue

Trinket will appear on the recommendation bar before engagement, but it will not recommend any more mid fights, even if the trinket is available for use.

### How to Reproduce

1. Enter game as Fury warrior
2. Start fight in front of dummy
3. Use the trinket as the first recommendation, as suggested by the addon.
4. Wait 1m 30s (trinket cool down time)
5. Trinket does not come up again on list.

### Snapshot (Link)

https://pastebin.com/JZKTpcR2

**Comment by CapitalPlayer** [comment]
MM Hunter - It worked the first day i had the trinket, would reccomend mid pull, start. But now [Mad Queen's Mandate] is never reccomeneded to  me. I've re-downloaded aswell as turn addon off/ reset default settings.

**Comment by Hekili** [comment]
> MM Hunter - It worked the first day i had the trinket, would reccomend mid pull, start. But now [Mad Queen's Mandate] is never reccomeneded to me. I've re-downloaded aswell as turn addon off/ reset default settings.

Each priority is unique; you'd need to open a separate ticket with a snapshot when you would expect the trinket to be recommended but it isn't.

**Comment by Hekili** [comment]
@Wafflesss736 This will be resolved in the next release.

**Comment by Wafflesss736** [comment]
thank you sir.
