### ISSUE TITLE
Feral- Moonfire 3x times in a row, with debuff already active on target.

### ISSUE THREAD

**Issue by LucasRals** [Hekili/hekili#3922]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Feral

### Describe the Issue

During ZekVir farming, rotation would recommend 3x casts of Moonfire when low on energy ~40%. Even though the debuff was already present

### How to Reproduce

This seems to only occur when I farm ZekVir for valor stones. So it might be some interaction with a prolonged fight with single target boss.
Enter fight start rotation , Around half way through the fight or energy starved the rotation defaults to multiple Moonfire casts even though debuff is present and other priorities should be maintaining Rip/Rake

### Snapshot (Link)

https://pastebin.com/siwbCMvg

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wbnD9hZ7aZm9UEQnHUyLTW

### Additional Information

Discord ID linked below

### Contact Information

130821473660043265

**Comment by syrifgit** [comment]
Your sim also does this, it is correct.
