### ISSUE TITLE
[REC] Sub rogue recommending slide and dice even though a longer duration slice and dice already active

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3924]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

Slice and dice is being recommended sometimes even when it can't be applied because it's already active with a longer duration than would be produced by using the button.

### How to Reproduce

Not entirely sure hot to recreate it, sometimes it will recommend snd when snd is active, but not all the time.

### Snapshot (Link)

https://pastebin.com/6NABiqN0

**Comment by Hekili** [comment]
Fixed for next release.
