### ISSUE TITLE
[REC] PI not being recommended properly as voidweaver shadow priest

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3925]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

On my sp I am experimenting with voidweaver, and I noticed that PI is not being recommended correctly, for example not at all in the opener. It is only very rarely being recommended subsequently.

Tangentially related, 1:30 trinkets (eg transmitter) are being recommended at 1:30 not with cooldowns as they should be. Both correct behaviours are present in the sim I linked.

Tangentially related to my tangent, if there could be a special case added for transmitter that recommends it a couple of gcds early so you can prepare the minigame to line up with cds that would be great too. Thats probably worth its own issue, if its not trivial.

### How to Reproduce

Play shadow
Spec voidweaver hero tree
Observe pi recommendations
(At 1:30 observe transmitter being recommended)

### Snapshot (Link)

https://pastebin.com/vRGAMX8z

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/na8K8By1hypJto6JTj6ySG

### Additional Information

While this hero tree is slightly worse at the very highest level where you are pulling extremely large around 2 min cds, its very good if not better in <12 keys.

**Comment by syrifgit** [comment]
You can just macro it to dark ascension / void eruption for now.

@Hekili 

`( buff.voidform.up[false] | buff.dark_ascension.up[true] & ( boss[false] & fight_remains[26.26] <= 80 | fight_remains[26.26] >= 140 ) )`

I'm not sure about locking PI behind fight length and boss. Dark Ascension / voidform buff up condition should be sufficient, you're never going to send PI solo. It is always with every voidform, or every 2nd dark ascension (cd length difference). PI should just inherent whatever conditions are on those 2 spells as a consequence of their buff needing to be up.

Simc uses fight length without the boss condition.

**Comment by Hekili** [comment]
> Simc uses fight length without the boss condition.

Yeah, `boss` is addon-only and sims generally assume it's a fresh pull on a boss.  This check is usually added to entries where the priority says to use something because the fight's about to end, which would have everybody burning their CDs as every trash pack dies in M+.  However, since this does sync up with SPriest CDs and those CDs are toggleable, it makes sense to remove the time conditions.
