### ISSUE TITLE
[REC] Hardcasted vampiric touch recommended when shadow crash is in the air.

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3926]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

If you are playing the whispering shadows talent you generally want to use shadow crash to apply your VTs, especially in aoe. 

When you approach a pack the addon does not know whether you are in aoe or ST so recommends a manual VT cast. 

If you override this by using your eyes and pressing shadow crash the VT cast should go away (until it lands and it turns out you actually missed, surely that would never happen to me though).

Another tangent: A way to control manual re-dot recommendations would be good. In a pack if I have 7/8 targets VT'd then the option to disable being told to press VT on the 8th would be good. Two controls would be good here, a slider for X targets total dotted (default disabled or 16 or something), and one for "do not recommend with X seconds remaining on shadow crash". 

My thinking behind this: theoretical optimal play and optimal play based on your own gameplay and UI (eg how easy it is for you to quickly identify what targets need dotted/if they do) dont always align and I think this is one of those cases. If someone has a UI that does tell them intuitively what targets need to be dotted then they dont need the addon to tell them to do it, and alternately if they don't then telling them to manually dot the 3 undotted targets in an 11 mob pull isnt going to be beneficial at all and will only kill their dps for the whole pull while they try to work out what to dot.

### How to Reproduce

Play SP
Play shadowcrash
Go to aoe dummies, press shadow crash, observe recommendations

### Snapshot (Link)

https://pastebin.com/adGqNU21

**Comment by Hekili** [comment]
Thanks, I'll add a check for Shadow Crash being in the air to a Vampiric Touch line or two.
