### ISSUE TITLE
Feral rotation fails to cycle through abilities after update

### ISSUE THREAD

**Issue by Rawr-kitteh** [Hekili/hekili#3928]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

With the newest update, it seems that some specs are not working correctly. As feral, it never goes further than Prowl in recommended abilities. 

### How to Reproduce

Enter game as feral, try to follow the rotation. Also, if you spec into balance, then back to feral, balance abilities remain. Reverting back to v11.0.2-1.0.19 fixes the current issue.

### Player Information (Link)

none

### Error Messages (Link)

none

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Rawr-kitteh** [comment]
Yeah, I was just trying to edit it, but it does not generate a snapshot, get the following LUA error when i press the snapshot keybind.

2x Hekili/State.lua:5338: bad argument #2 to 'max' (number expected, got nil)
[string "=[C]"]: in function `max'
[string "@Hekili/State.lua"]:5338: in function <Hekili/State.lua:5202>
[string "-- Feral:default:10 recheck
return dot.adaptive_swarm_damage.remains, (dot.adaptive_swarm_damage.remains+0.01)-(2), action.adaptive_swarm.in_flight_remains, dot.rip.remains"]:2: in function `Recheck'
[string "@Hekili/State.lua"]:1667: in function `recheck'
[string "@Hekili/Core.lua"]:1033: in function `GetPredictionFromAPL'
[string "@Hekili/Core.lua"]:1430: in function `GetNextPrediction'
[string "@Hekili/Core.lua"]:1818: in function `Update'
[string "@Hekili/Options.lua"]:11828: in function `MakeSnapshot'
[string "@Hekili/Options.lua"]:11935: in function `FireToggle'
[string "@Hekili/UI.lua"]:2874: in function <Hekili/UI.lua:2873>

Locals:
(*temporary) = 0
(*temporary) = nil
(*temporary) = "number expected, got nil"

**Comment by Hekili** [comment]
Try https://github.com/Hekili/hekili/releases/tag/v11.0.2-1.0.20a

**Comment by Rawr-kitteh** [comment]
> Try https://github.com/Hekili/hekili/releases/tag/v11.0.2-1.0.20a

Fixed it, tyvm
