### ISSUE TITLE
[REC] Priorities are incorrect now for Arcane Mage after new update

### ISSUE THREAD

**Issue by heypeterm** [Hekili/hekili#3931]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Arcane

### Describe the Issue

After the update, Hekili suggests either Arcane Blast over and over - with nothing else - or Arcane Barrage with no charges at all.  Also, the primary row isn't seen until I initiate combat, unlike before I could see it outside of combat to know what to do first.

### How to Reproduce

1 . Enter Game as a Arcane Mage, Sunfury spec and battle some enemies.  You should notice incorrect priorities suggested.  I find it rarely changes a suggestion and repeats it over and over now.  Sometimes it does work, then goes back to incorrect behavior.

### Snapshot (Link)

https://pastebin.com/pViq08Bf

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tonXbKywKd3ULEUfPwP4qR

### Additional Information

I also tried my Spellslinger hero talent spec and had similar incorrect priorities.

### Contact Information

._disco_. on discord

**Comment by syrifgit** [comment]
This is not the newest addon version. Update to .20a

**Comment by heypeterm** [comment]
Updated to newest version and it works now.
