### ISSUE TITLE
[REC] Demonic Strength showing up in Single Target 

### ISSUE THREAD

**Issue by Reshuffling** [Hekili/hekili#3934]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

With the new APL updates to Demonology(mid september) Demonic Strength should not be recommended in Single Target any more. 

### How to Reproduce

Just take Demonic Strength talent and it gets recommended after summoning Demonic Tyrant. 

### Snapshot (Link)

https://pastebin.com/xvWbRUa5

### Contact Information

Hardan in Discord

**Comment by syrifgit** [comment]
If it's a new APL change then it will get updated the next time the APLs are synced with the addon

**Comment by Reshuffling** [comment]
> If it's a new APL change then it will get updated the next time the APLs are synced with the addon

No the APL is updated for Hekili but doesn't translate it right I think? 

`actions+=/demonic_strength,,if=active_enemies>1 `

Should be more than one enemy right? 

[Sim for reference](https://www.raidbots.com/simbot/report/69G4ZotEcHCsipY4QzeFXp)

**Comment by Hekili** [comment]
There's a leftover line from an older version of the priority.  It'll be fixed soon (probably tomorrow).
