### ISSUE TITLE
[REC] Summon Charhound showing up multiple times

### ISSUE THREAD

**Issue by Reshuffling** [Hekili/hekili#3936]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

Had this issue before, seemed to be solved when I just loaded new talents, but noticed in raid the other day and got a snapshot during dummies just now. [Prev issue ticket](https://github.com/Hekili/hekili/issues/3900)

### How to Reproduce

Just follow rotation.

### Snapshot (Link)

https://pastebin.com/irfUi5J6

### Contact Information

Hardan in Discord

**Comment by Hekili** [comment]
In your case, it looks like the Soul Strike prediction is failing to clear, so when it syncs up with an ability, the ability's handler and CD don't get triggered.  Subtle bug.  Will fix.
