### ISSUE TITLE
[REC] Recommendation keep showing PVP trinket 

### ISSUE THREAD

**Issue by Stoufs** [Hekili/hekili#3937]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Survival

### Describe the Issue

Just randomly and rare but it does seem to recommend 'Forged Aspirant's Medallion'. The problem is this does not exist in the abilities entries OR the items trinket list, so I am at a loss.

### How to Reproduce

DPS anything. Seems to be survival only related. seems to be mainly recommended during cooldowns from my testing but the item does not exist in any ability list so I am not sure how to disable it?

### Snapshot (Link)

na

**Comment by Hekili** [comment]
All of the medallion trinkets are configured under Gladiator's Medallion.
