### ISSUE TITLE
[REC] VDH Demon Spikes not showing up pre-pull in solo-tank content

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3939]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Vengeance

### Describe the Issue

The Demon Spikes entry currently has the condition that you must be tanking for it to be shown, this means you will not see the recommendation pre-pull in a solo tank environment like a dungeon which means you are going to die when you engage without it. 

Ideally there should also be a small overlap on this action to prevent it falling off for any time. It is off gcd so ~0.5s should be plenty from my testing.

### How to Reproduce

Play VDH
Observe recommendations
Remove `& tanking`
observe recommendations

### Snapshot (Link)

https://pastebin.com/VKWisy4s

**Comment by syrifgit** [comment]
Could make this into a spec option maybe

**Comment by Hekili** [comment]
This has been resolved; Demon Spikes is recommended in the default priority if `tanking` or `time<5` to account for the opener.
