### ISSUE TITLE
aoe bar flickering after 8.3.0-1(2020-08-03) update

### ISSUE THREAD

**Issue by PaigePB** [Hekili/hekili#394]
I also want to mention how much I appreciate this addon!

**Describe the Bug/Issue**
the aoe bar flickers in and out constantly (whether there are targets nearby or not)

**To Reproduce**
Since this is constant, there are no steps to reproduce this

**Expected behavior**

I would expect (depending upon the mode) the aoe bar would appear when it should (either all the time, none or reactive) depending upon the settings

**Screenshots**
I included a short video
[zoom_0.zip](https://github.com/Hekili/hekili/files/5023541/zoom_0.zip)

**WHEN SUBMITTING AN ISSUE:**

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v8.3.0-10
level: 120 (120)
class: DRUID
spec: feral

talents: balance_affinity
    bloodtalons
    mass_entanglement
    predator
    primal_wrath
    soul_of_the_forest
    wild_charge

azerite: azerite_empowered = 3
    blightborne_infusion = 1
    gutripper = 1
    heart_of_darkness = 1
    heed_my_call = 1
    impassive_visage = 1
    jungle_fury = 2
    self_reliance = 1
    switch_hitter = 1
    unstable_flames = 1
    wild_fleshrending = 2

essences: [blood_of_the_enemy] = 4, breath_of_the_dying = 3, conflict_and_strife = 3, purification_protocol = 4

sets/legendaries/artifacts: none

gear: anzig_vra = 1
    ashjrakamas_shroud_of_resolve = 1
    bracers_of_dark_prophecy = 1
    gorak_tuls_mantle = 1
    grips_of_electrified_defense = 1
    heart_of_azeroth = 1
    irradiated_undercoat = 1
    kul_tiran_cannonball_runner = 1
    logic_loop_of_recursion = 1
    overclocking_bit_band = 1
    port_pillagers_belt = 1
    raiment_of_the_blighted_tribe = 1
    sandshined_snakeskin_sandals = 1
    singeblotched_britches = 1
    stygian_guise = 1
    writhing_segment_of_drestagath = 1

corruptions: devour_vitality = 1

itemIDs: 158075, 159306, 159309, 159327, 159335, 159337, 159339, 159628, 169158, 169159, 169223, 169878, 172191, 173946, 174132, 174138

settings: 1 = 2
    aoe = 3
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 3
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Feral
    potion = potion_of_empowered_proximity
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    brutal_charges = 2

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = reactive
    potions = false

**Comment by Hekili** [comment]
Should be resolved in v8.3.0-11.
