### ISSUE TITLE
[REC] VDH Fel Dev and Meta empowered abilities and cooldown resets are not implemented correctly

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3940]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Vengeance

### Describe the Issue

Metamorphosis (the spell) resets the cooldown of Sigil of Flame and Fel Devastation (violent transformation) and empowers them (demonic intensity). When you are in meta and you cast empowered fel dev (fel desolation) it recommends you to immediately press it again despite it going on a 40 second cooldown. When the cast finishes the recommendations fix themselves.

### How to Reproduce

Play VDH
Play fel-scarred hero tree
Press meta
Observe recommendations, note multiple instances of fel desolation despite it having a 40s cd 
Press fel desolation and observe the next recommendation with a 40s timer on it 

One of these is before pressing fel dev, one is during the cast.
https://pastebin.com/7aU4ibUk
https://pastebin.com/K0wNReTN

### Snapshot (Link)

https://pastebin.com/K0wNReTN

**Comment by dubudevs** [comment]
Entering meta by pressing fel devastation with Demonic talented or by cheating with Last Resort does not proc the reset cd and empowered fel dev and SoF, only actually pressing meta.

**Comment by dubudevs** [comment]
Piggybacking this issue, in general Sigil of Doom cpm seems low. I dont have a specific snapshot, and I am not sure if its related to the same issue as the initial one. Will check some more when its fixed.

**Comment by dubudevs** [comment]
The issue is from line 1156 of https://github.com/Hekili/hekili/blob/thewarwithin/TheWarWithin/DemonHunterVengeance.lua

Violent Transformation and Demonic Intensity do not apply to Fel Dev or Fel Deso. 

Remove lines 
1156-1167
1180-1192
1254-1265
1278-1290

The Metamorphosis section at like 1463 seems to be the Havoc section, it needs to have what was removed from the fel dev/fel deso sections added to the meta section. Not sure if there is more there that needs to be updated, but the fel_scarred section thats in there just includes havoc skills and the rest of it includes havoc talents.

That alone doesnt seem to be enough to fix the SoD/Fel Deso recommendation problems, unfortunately I dont have enough knowledge to further diagnose :(

**Comment by dubudevs** [comment]
Additionally Meta does not reset the cooldown of Immo aura.

**Comment by Hekili** [comment]
Thanks; I've implemented these changes for next release.

**Comment by dubudevs** [comment]
~~There is a small issue I found with the changes, when you initiate meta with fel dev then it will recommend the meta exclusive spells to be cast after meta falls off https://pastebin.com/2AWi0suL~~

I had the wrong action list selected so it was a change I made that caused this xdd

**Comment by dubudevs** [comment]
Ok a not fake report this time, the addon is miscalculating whether its still in meta meta for some reason: Here there are no recommendations for Consuming Fire (I modified the immo aura line in meta list to this for testing purposes) or Sigil of Doom despite them being very high priority and being available. When you press fel desolation in meta it extends meta meta, and pressing meta within fel dev meta converts the meta into meta meta. God these names are confusing I hope you understand what I mean...

https://pastebin.com/RVqTR0ec

This is what I described in the comment of https://github.com/Hekili/hekili/issues/3953 - ~~unsure if its because its tracking demonsurge and failing to recommend after its been consumed, or if hardcast demonsurge refers to meta meta.~~ Seems like its just not accounting for extended/converted metas

**Comment by Hekili** [comment]
This snapshot gave me the info I needed -- Immolation Aura was set to unavailable while Metamorphosis was active, and Immolation Aura and Consuming Fire are interchangeable in implementation.  I've removed the `nobuff = ...` line from Immolation Aura in the Vengeance model and may post a quickfix before the 11.0.5 release.
