### ISSUE TITLE
[REC] VDH dps-centric fel devastation usage in opener causing extremely sketchy gameplay

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3941]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Vengeance

### Describe the Issue

Sims opt to press fracture twice before pressing fel devastation when going into a pull to optimise dps by having souls preloaded and near capped fury, however if you actually do this in any relevant content you will immediately die and/or lose threat killing your dps/healer.

I have changed this to change action 4 in fel_dev_prep to `( ( fury + variable.fel_dev_passive_fury_gen ) >= 50 ) & ( variable.can_spburst | variable.can_spburst_soon | soul_fragments >= 0 )`  (5 to 0) to cause it to always cast if you have enough fury. This aligns with gameplay guides found on wowhead, icyveins, and youtube.

### How to Reproduce

Play VDH
Play fel-scarred
Observe opener

### Snapshot (Link)

https://pastebin.com/niK1tTjX

**Comment by dubudevs** [comment]
An update on this, while it would be lower dps, if you do not have fury for fel dev after SoF + Immo aura on the opener but meta is available, you should use meta instead of fel dev. If you try to engage a pack in anything higher than a 6 key and fracture is your 2nd gcd with no frailty stacks or meta then you will just die. 

In a similar vein for not completely inting, if expected combat time remaining is less than 15 seconds and you have meta available but not fel dev then meta should be used and the reset fel dev cd should not be used, so that it is available for pull on the next pack.

A "defensive meta usage" toggle would be excellent so that in normal and heroic raid where defensive usage is irrelevant you can still play for max dps.

If this is more suitable for Nerien's packs then I can talk with them about it, but as it stands the current APL is unusable for tanking anything except easy raidbosses when you outgear them which is unfortunate because historically the included APL has been decent for tanking keys.

**Comment by taherbert** [comment]
Two things:

1. Not sure on Hekili's stance for tank specs, but IMO at a certain point tanks are going to struggle if blindly following _any_ rotation helper (no fault of Hekili's). Starting a M+ pull is pretty nuanced and requires some on-the-fly thinking. The addon can't play the game for you. 

The double fracture opening described above IS optimal for damage. That's what sims and the APL are optimizing for. Hekili could try to do a whole lot of manual overrides to tell folks how to perform a pull, but I suspect it's just not going to be possible in all situations and require a bunch of manual maintenance.


2. On this part:
> I have changed this to change action 4 in fel_dev_prep to ( ( fury + variable.fel_dev_passive_fury_gen ) >= 50 ) & ( variable.can_spburst | variable.can_spburst_soon | soul_fragments >= 0 ) (5 to 0) to cause it to always cast if you have enough fury. This aligns with gameplay guides found on wowhead, icyveins, and youtube.

This does not align with gameplay guides. The intent with this line is for you to prepare to enter fel dev with sufficient souls and fury to immediately cast spirit bomb at an optimal number of soul fragments, followed by a soul cleave. This consumes your demonsurges and maintains efficient spirit bomb usage. You probably don't want to make the `soul_fragments >= 0` change, as that will make it difficult for you to perform an optimal spirit burst cast.

Just like with above, if you need Fel Dev as a defensive then just press the button and ignore Hekili's recommendation. The APL/addon will adjust to the new situation.

**Comment by Hekili** [comment]
Generally, I defer to @taherbert here. If there is a DPS neutral adjustment that can be pared down to a simple option (i.e., a slider for number of souls in your recommended change), I'm open to consider it. 

Have you run sims with any of your modifications in place for comparison?

**Comment by Hekili** [comment]
Looking at this again, I would be open to adding a "Defensive Fel Devastation" option with criteria something like:

> `settings.defensive_fd & buff.metamorphosis.down & ( tanking | time < 5 )`

It'd need a warning that it's not optimal for damage but will get you into Meta if you're not already in Meta.  The `time<5` portion is just so you're essentially assumed to be tanking for the very beginning of the fight, before you've grabbed threat.  I'll need to do some sims to see just how much DPS is lost, though.
