### ISSUE TITLE
[REC] Prescience - Aug Evoker

### ISSUE THREAD

**Issue by moxx255** [Hekili/hekili#3943]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

The priority list is not showing PRESCIENCE to be used however on the changelog it describe less use of prescience.. but it does not show at all in my rotation.

### How to Reproduce

play scalecommander spec on aug, check rotation it does not recommend using prescience.. which sits at 2 stacks.

### Snapshot (Link)

q

### Additional Information

changelog states less use of prescience how ever seems that no use of prescience is being used..

### Contact Information

robinator1990@hotmail.co.uk

**Comment by syrifgit** [comment]
Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot
