### ISSUE TITLE
Paladin Eternal flame not showing hotkey

### ISSUE THREAD

**Issue by station384** [Hekili/hekili#3944]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

Ret Paladin
Spell Eternal Flame
Hekili recommends correctly but does not show the associated hotkey the item is on.   
I have placed the spell on the main bar using a 1-0,-,= hotkey.

### How to Reproduce

Using talents:
CYEAE74QAafj6bdTrgpLZS4VlDAAAwAAjJ22mZ2W2mZsZmZbxsNAAAAAAMbT0MDDMzYGzyYYMMmlZW2GGMYwyCbAAzysNzMbNzMtNbz2MAgFA
I go to a tanking dummy and get attacked and attack it using the recommended items till it recommends eternal flame.

### Snapshot (Link)

https://pastebin.com/5Yp0Ze0X
https://pastebin.com/9f0hai3k  - Profile used to create condition, based on default with eternal flame added to recommend healing yourself.

### Contact Information

station384@gmail..com

Edit:  Added a pastebin with a profile that uses eternal flame, as the default does not recommend healing

**Comment by syrifgit** [comment]
This is addressed in the FAQ: https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions
