### ISSUE TITLE
[REC] MM Hunter - Wailing Arrow is not recommended 

### ISSUE THREAD

**Issue by mwojtkowski** [Hekili/hekili#3945]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Marksmanship

### Describe the Issue

Wailing Arrow is not recommended by Hekili. 

With primary icon set to show three next actions, addon will show Trueshot and as next icon in queue Wailing Arrow. That is because Trueshot is set to apply wailing_arrow_override buff and Wailing Arrow require wailing_arrow_override to be suggested, but the moment you use Trueshot addon ignores Wailing Arrow 

in HunterMarksmanship.lua wailing_arrow_override has id 459808 - there is no buff/aura with that id when Wailing Arrow is usable (I've checked that using WeakAuras)

using WeakAuras I made simple wa to show when Wailing Arrow is usable 
trigger spell -> spell usable -> spell id 355589
WeakAura -> https://pastebin.com/Xp3rTrsg

### How to Reproduce

1. Enter game as MM Hunter
2. Use ST build from wowhead (Sentinel or Dark Ranger)
3. Follow normal rotation on ST dummy
4. it is most noticeable when addon suggest Trueshot, Wailing Arrow should be suggested as next ability right after Trueshot

### Snapshot (Link)

Snapshot taken right after Trueshot was used
https://pastebin.com/JJg4KCWg

**Comment by syrifgit** [comment]
I have already been slowly working on this for awhile. Just writing to acknowledge, haven't had much time lately to get it finished up.

355589 doesn't work for this case, but the solution will be `IsSpellKnownOrOverridesKnown(392060)` once I get time to finish it. Specifically, trying to smooth out predicting when you will hit 20 wind arrows and proc the spell.

**Comment by syrifgit** [comment]
Submitted a PR that gets it mostly working. It won't predict wailing arrow coming up due to wind arrows, but when it does proc, the addon will behave correctly. That should do for now until I get around to wind arrow stuff.

**Comment by Hekili** [comment]
This is resolved for next release.
