### ISSUE TITLE
Cooldowns (Renewal/Feral Druid) being recommended while on cooldown

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [Hekili/hekili#3946]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Feral

### Describe the Issue

I am expecting abilities to not show up on my cooldown section when they are on cooldown. 

### How to Reproduce

Use the default feral druid rotation, use renewal, take damage while renewal is on cooldown.

### Snapshot (Link)

Not applicable.

**Comment by syrifgit** [comment]
Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by BuurmanDeBuurman** [comment]
It is not specific to feral, I'm noticing, trinkets, cooldowns being recommended while on cooldown with no indicator that they are actually not usable. Would you still want a snapshot?

Enhancement Shaman, Blood Death Knight

**Comment by syrifgit** [comment]
Yes, that's why I asked for one.

**Comment by BuurmanDeBuurman** [comment]
Here you go, buddy. Have fun.

https://pastebin.com/gR5t6WfD
https://pastebin.com/8Hh2aX9N

**Comment by syrifgit** [comment]
It's telling you to use it in 6.78 seconds, not right now. You probably want to turn on your "delay" indicators under display settings.
