### ISSUE TITLE
[REC] Unholy DK San Layn build recommendation cannot be presented

### ISSUE THREAD

**Issue by Gromzie** [Hekili/hekili#3948]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

Gives an error in the chat that the recommendation cannot be presented, and it also suggests that you should wait 10 seconds before the next spell should be used, which should not be correct. 

### How to Reproduce

1.Enter as unholy dk
2. Use the san layn build (CwPAtbMOTHlnKIwUyAn+DK70SDgZGDjZGjlZMzMzYYYmxMmBAAAAAAAAAzwMzYmZGAY2MDzywMzMPwMjxADMjhxyCgtBbAwMA)
3. Start follow rotation on single target dummy

### Snapshot (Link)

https://pastebin.com/vhFc907S

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tVcqNP6Bor5iJ29mz7Kn43

**Comment by syrifgit** [comment]
It suggests waiting 10 seconds because that's how far into the future the addon looks. Seems to me it is waiting for resources, your sim also does this.

![image](https://github.com/user-attachments/assets/d6c241f8-00f1-453a-b955-f147acd49c0c)


How long does it take for a recommendation to pop up?

**Comment by syrifgit** [comment]
@Hekili I wonder if this should behave more like demon blades DH? Kind of show the next thing greyed out while waiting for resources?

Or even some fallback icon/action that indicates waiting for resources

**Comment by b14554124** [comment]
I have been trying to fix this issue recently, and my initial assessment is that there is a problem with the handling of [wound_spender].

**Comment by b14554124** [comment]
```
    if not talent.clawing_shadows.enabled or buff.vampiric_strike.up or buff.gift_of_the_sanlayn.up then
        class.abilities.wound_spender = class.abilities.scourge_strike
        class.abilities[ 433895 ] = class.abilities.scourge_strike
        cooldown.wound_spender = cooldown.scourge_strike
    else
        class.abilities.wound_spender = class.abilities.clawing_shadows
        class.abilities[ 433895 ] = class.abilities.clawing_shadows
        cooldown.wound_spender = cooldown.clawing_shadows
    end
```

It seems that this part of the code cannot properly handle wound_spender due to the changes brought by clawing_shadows and scourge_strike.

**Comment by syrifgit** [comment]
This isn't an "issue". As you can see by looking at the sim, you simply need to wait for runic power.

And not sure what you mean by that code not handling wound spender, when that seems to be exactly what that code is doing?

**Comment by b14554124** [comment]
Sorry ,~~ my wording is a bit off :D, but with the San Layn talent on a single target, there seems to be an error with the description of Gromzie. Here’s the code I tried to fix it; I hope it helps! (Of course, it may not be correct.) @Gromzie 

https://pastebin.com/LBM1E3iC

**Comment by syrifgit** [comment]
I'll be honest here, I think the root cause of the issue is that fact you aren't running a standard build, but a new experimental build.

This is how much your build waits when simmed.

![image](https://github.com/user-attachments/assets/21e1f2ab-58c0-4a02-a6a4-f666cb3861aa)


When I sim your exact character using a San'layn build from the class guides

![image](https://github.com/user-attachments/assets/07821e9f-f056-4b46-b85a-77fc3b318cb0)

So, this is expected behaviour.
