### ISSUE TITLE
[REC] Destruction warlock doesn't use Cataclysm to refresh Immolate when available

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#3950]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Destruction

### Describe the Issue

As per the Warlock priority (on Wowhead) and in the Simcraft APL (see included simc report) Destro is supposed to use Cataclysm even in single target to refresh Immolate over raw casting Immolate when possible.

### How to Reproduce

Play Destro lock in a single target scenario and need to refresh Immolate when Cataclsym is available.

### Snapshot (Link)

https://pastebin.com/xZzA7jmS

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/r8KxDHxRVhV9y6nDHXKY6w/simc

**Comment by syrifgit** [comment]
Catacylsm is assigned to your interrupts display, so it is not being recognized in the main rotation as being available. You will need to use it on your own if it's in a separate display.

I see in the code that Cataclysm is set to be an interrupt in single target only (automatically, not done by you). However, I see in your sim that it is used as part of the regular rotation. I will submit a change to have this functionality removed as it is impacting the rotation. It's probably leftover from an expansion/tier where cataclysm was not a normal part of the rotation.

**Comment by Hekili** [comment]
The "Cataclysm in single-target" probably should've been more transparent to users; requiring the Interrupts toggle (and showing Interrupts separately) was my own personal preference because the addon doesn't predict whether adds are spawning soon, and I found it annoying to waste Cataclysm right before an add wave or new pack in M+.

This is fixed in next release but I may add a new option to toggle this behavior later.
