### ISSUE TITLE
[REC] Assa rogue - recommending builder when already on animacharged CP

### ISSUE THREAD

**Issue by Yuuseki** [Hekili/hekili#3951]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

In the screenshot you can see the addon recommending Mutilate (a builder generating combo points) before Rupture (a spender using combo points) even when we are already at an animacharged CP (using a spender at an animacharged CP counts as if the spender was used at full combo points).
![image](https://github.com/user-attachments/assets/de63f8ee-7e06-49d3-8640-a6e89ed86f6b)
It doesnt make sense to use a builder here, does it?

In the attached snapshot you can see the addon returning 4 for `combo_points.deficit`.
On the rogue discord, Whispyr said:
Yuuseki — Today at 03:33
does combo_points.deficit include animacharged CPs?
Whispyr — Today at 03:36
if you're on an animacharge it'll evaluate your cp at 7

So should `combo_points.deficit` return 0 in this situation? Not sure if including animacharged CPs is the right approach here.

### How to Reproduce

Hit a dummy and follow the recommendations until you see it recommending a builder i. e. Mutilate even when already on animacharged CP.

### Snapshot (Link)

https://pastebin.com/arq2CutW

### Additional Information

Another example where Garrote was recommended instead of Mutilate:
https://pastebin.com/bKMGXedF

### Contact Information

yuuseki.

**Comment by Sedveth** [comment]
ER will be removed in 2 weeks anyway so you won’t have to deal with this in the future, might not be in high priority list if he has something else to do

**Comment by a-mak-tqgg** [comment]
@Sedveth you mean with the anniversary patch? Maybe I missed some notes, but afaik ER stays, only its icon has been updated.

**Comment by Yuuseki** [comment]
@Sedveth you mean the redesign with supercharged CP? Its sort of the same there, a supercharged CP counts as +2 CP, should `combo_points.deficit` include this?

**Comment by Sedveth** [comment]
> @Sedveth you mean the redesign with supercharged CP? Its sort of the same there, a supercharged CP counts as +2 CP, should `combo_points.deficit` include this?

the "supercharged CP" here just make people confused, it's basically just a buff that add 2CP (3 if talented into Forced Induction) to your finisher. There won't be mini game like current ER functioning anymore

**Comment by Hekili** [comment]
I have this fixed for next release (and will break it again soon after).
