### ISSUE TITLE
[REC] Stormkeeper and Tempest recommened after each other.

### ISSUE THREAD

**Issue by Thornic** [Hekili/hekili#3952]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

When you're doing your normal rotation. It often happens that you get Tempest and Stormkeeper is off cooldown.
The addon recommends to cast Stormkeeper first and than Tempest.

I believe the maelstrom generation is much higher if you SK -> CL -> CL -> Tempest -> CL -> CL.

Also the Arc Discharge Proc you get from Tempest doesn't stack with the Stormkeeper buff.

### How to Reproduce

Just do normal rotation according to the addon.

### Snapshot (Link)

https://pastebin.com/P8Ky7WVV

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/gNQ94vTmxJf9AsUbf28EdC

### Contact Information

Tornic.

**Comment by Thornic** [comment]
Forgot to mention that this on AOE.

**Comment by syrifgit** [comment]
This does appear to be a mismatch between simc and the addon. Simc appears to consume both stormkeeper stacks before using tempest, just not sure why yet. Will look into it.

**Comment by syrifgit** [comment]
After looking at it more, I'm not 100% sure this is an issue. The sim doesn't do it, but it's because SK and tempest don't come up at the same time, because the sim can perfectly track maelstrom.

Elemental class discord seems to say it doesn't matter. You just send tempest.
