### ISSUE TITLE
[FEATURE] Add timewalking trinket Wrathstone

### ISSUE THREAD

**Issue by Kanaxai** [Hekili/hekili#3956]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Wrathstone (item id=156000) is a particularly powerful on-use WotLK timewalking trinket, please add it so it can be recommended by Hekili.

**Comment by syrifgit** [comment]
Can you get the name and spellID of the in-game buff when you activate the trinket? You can use an addon like IdTip or a weakaura.

Code so far for `Items.lua` in case anyone else sees this.

```
    wrathstone = {
        cast = 0,
        cooldown = 120,
        gcd = "off",

        item = 156000,
        toggle = "cooldowns",

        proc = "primary",
        self_buff = "wrathstone",

        handler = function()
            applyBuff( "wrathstone")
        end,

        auras = {
            wrathstone = {
                id = 64800,
                duration = 20,
                max_stack = 1
            },
        },
    },
```

**Comment by johnnylam88** [comment]
Should we create expansion-specific directories and add these items into `Items.lua` files within those directories? I imagine that Timewalking will continue to happen for the foreseeable future and it's odd to add these expansion-specific trinkets/items to the existing file in `TheWarWithin`.

**Comment by syrifgit** [comment]
> Should we create expansion-specific directories and add these items into `Items.lua` files within those directories? I imagine that Timewalking will continue to happen for the foreseeable future and it's odd to add these expansion-specific trinkets/items to the existing file in `TheWarWithin`.

Probably, good idea. I was also wondering about the UI especially for turning on/off trinkets, wonder if we did start tagging trinkets if you could do a sub-dropdown. So select "All", "current expansion", "PvP", "Timewalking", etc. Easier to find what you're looking for.

**Comment by Kanaxai** [comment]
> Can you get the name and spellID of the in-game buff when you activate the trinket? You can use an addon like IdTip or a weakaura.
> 
> Code so far for `Items.lua` in case anyone else sees this.
> 
> ```
>     wrathstone = {
>         cast = 0,
>         cooldown = 120,
>         gcd = "off",
> 
>         item = 156000,
>         toggle = "cooldowns",
> 
>         proc = "primary",
>         self_buff = "BUFFNAME",
> 
>         handler = function()
>             applyBuff( "BUFFNAME")
>         end,
> 
>         auras = {
>             BUFFNAME = {
>                 id = BUFFID,
>                 duration = 20,
>                 max_stack = 1
>             },
>         },
>     },
> ```

Sure, here's the ID:
![image](https://github.com/user-attachments/assets/ec0b42cf-6e72-448a-8bea-251f86ba429f)

**Comment by syrifgit** [comment]
> > Can you get the name and spellID of the in-game buff when you activate the trinket? You can use an addon like IdTip or a weakaura.
> > Code so far for `Items.lua` in case anyone else sees this.
> > ```
> >     wrathstone = {
> >         cast = 0,
> >         cooldown = 120,
> >         gcd = "off",
> > 
> >         item = 156000,
> >         toggle = "cooldowns",
> > 
> >         proc = "primary",
> >         self_buff = "BUFFNAME",
> > 
> >         handler = function()
> >             applyBuff( "BUFFNAME")
> >         end,
> > 
> >         auras = {
> >             BUFFNAME = {
> >                 id = BUFFID,
> >                 duration = 20,
> >                 max_stack = 1
> >             },
> >         },
> >     },
> > ```
> 
> Sure, here's the ID: ![image](https://private-user-images.githubusercontent.com/8879953/375970757-ec0b42cf-6e72-448a-8bea-251f86ba429f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDk5NjcsIm5iZiI6MTcyODc0OTY2NywicGF0aCI6Ii84ODc5OTUzLzM3NTk3MDc1Ny1lYzBiNDJjZi02ZTcyLTQ0OGEtOGJlYS0yNTFmODZiYTQyOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMTYxNDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFiNzU1ZjJjOGMzYTlkNWQ0MjE3NGQ0OWZkYjI2YmZiNjUxNmY5NjIyOTQ5ZjNkODI0MDhmMzQ2ODAzYWMzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EG321QkKL6mK1EkigdTlaWK9cfvuKVZZ2FpFZaooTWA)

Thanks!

**Comment by johnnylam88** [comment]
I'll include this change in my latest branch.
