### ISSUE TITLE
[REC] function tempest_mael_count always returns 0

### ISSUE THREAD

**Issue by holytobi** [Hekili/hekili#3958]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

i played a bit enhancer and find out that the rotoation is not 100% correct so i step into the action list and saw that these variable/function is always 0 and because ot this reason the whole rotation is a bit messed up. This variable function is used very often in the APL. How i understand it should return how much maelstorm i consumed and how far away the next tempest is. But it returns everytime 0. 

Find in codefile: Shaman Enhancement.lua
line 991
spec:RegisterStateExpr( "tempest_mael_count", function ()
    return GetSpellCastCount( class.abilities.tempest.id )
end )

ID is filled: class.abilities.tempest.id = 452201
I doesent found the implementation from the method GetSpellCastCount so i cant dig deeper. 

### How to Reproduce

Enter game as enhancer, go to dummys start the rotation and take a look in variables for example aoe-> 1.Tempest and check there "tempest_mael_count" if the value changes

### Snapshot (Link)

pastebin down rightnow

**Comment by syrifgit** [comment]
This is known already: https://github.com/Hekili/hekili/issues/3590

see the comment [here](https://github.com/Hekili/hekili/issues/3590#issuecomment-2318480685) and [here](https://github.com/Hekili/hekili/issues/3590#issuecomment-2322501123)
