### ISSUE TITLE
[REC] Add Flask of Alchemical Chaos to Potions for DK

### ISSUE THREAD

**Issue by rheuzzy** [Hekili/hekili#3959]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

The list of potions doesn't list the current meta, Flask of Alchemical Chaos.

### How to Reproduce

Check list of potions, note it is not listed. 

### Snapshot (Link)

https://www.wowhead.com/guide/classes/death-knight/frost/enchants-gems-pve-dps

### Additional Information

https://www.wowhead.com/guide/classes/death-knight/frost/enchants-gems-pve-dps 

See section,  Best Consumables for Frost Death Knights

**Comment by syrifgit** [comment]
Flasks are not potions. If you need reminders for your weapon oils and flasks, get a weakaura reminder or ERT.
