### ISSUE TITLE
Havoc DH Issue

### ISSUE THREAD

**Issue by mediamst** [Hekili/hekili#396]
I am playing a Havoc Demon Hunter. For some reason, my trinket never is suggested for use even though I have it selected and it is not disabled. 

Also, It keeps recommending I use Fel Rush which does 4K damage vs Blade Dance that causes 23K damage. Blade Dance is not disabled either.  

Any ideas on how to have it recommend blade rush and my trinket when available?

build: v8.3.0-07
level: 120 (120)
class: DEMONHUNTER
spec: havoc

talents: demon_blades
    demonic
    fel_eruption
    felblade
    first_blood
    soul_rending
    trail_of_ruin

azerite: azerite_empowered = 3
    azerite_veins = 1
    furious_gaze = 3
    gemhide = 1
    heart_of_darkness = 1
    heed_my_call = 1
    impassive_visage = 1
    resounding_protection = 1
    revolving_blades = 1
    shimmering_haven = 1
    tradewinds = 1

essences: [essence_of_the_focusing_iris] = 2, breath_of_the_dying = 1, the_crucible_of_flame = 4, worldvein_resonance = 1

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    corrupted_gladiators_leather_footguards = 1
    corrupted_gladiators_warglaive = 1
    darkheart_robe = 1
    deepwarden_fangs = 1
    girdle_of_the_insatiable_maw = 1
    handguards_of_the_insatiable_maw = 1
    heart_of_azeroth = 1
    pearl_divers_compass = 1
    ring_of_cosmic_potential = 1
    seafarer_shoulderpads = 1
    stygian_guise = 1
    unseen_predators_breeches = 1
    vitacharged_titanshard = 1
    voidetched_band = 1
    wristwraps_of_the_insatiable_maw = 1

corruptions: racing_pulse = 2
    void_ritual = 1

itemIDs: 157979, 158075, 158089, 158162, 169070, 169223, 172627, 172752, 173508, 173815, 174131, 174132, 174500, 174531, 174533, 174954

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 25
    nameplates = true
    package = Havoc
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    recommend_movement = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
You'll need to post snapshots of the recommendations you disagree with, following the instructions that are included in the initial ticket.

**Comment by Hekili** [comment]
I did a quick check and confirmed that the "Use Items" action is in the Havoc priority and that Pearl Diver's Compass is a supported item.

Fel Rush should not be available as you have the spec option for movement off and haven't taken the Momentum talent.

I will not be able to do further testing without the snapshot.

**Comment by mediamst** [comment]
Thanks so much for the response. I am working on figuring how to the snapshot works. The last info you provided is helpful but somehow Hekili isnt showing up all a sudden when I log in. Let me figure that out first :) Thanks!

**Comment by mediamst** [comment]
It wants me to use Fel Blade, instead of blade dance. I will post snapshot soon (hopefully)
