### ISSUE TITLE
Execution Sentence not been recommended most of the time

### ISSUE THREAD

**Issue by LeighMetz** [Hekili/hekili#3961]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

Most of the time Execution Sentence isn't been recommended (usually only at the start) optimally use is execution before using wake of ashes and hammer of light. It completely ignores Execution.

### How to Reproduce

Start rotation with blade, toll, templars then will recommend execution and then ashes-hammer of light and will often never mention to use it again after that.

### Snapshot (Link)

https://pastebin.com/gThWH0C4

**Comment by syrifgit** [comment]
Because training dummy time-to-tie is finicky. It thinks the dummy will die in 2 seconds, so it's appropriately holding it.
