### ISSUE TITLE
Infernal Bolt detection issue

### ISSUE THREAD

**Issue by Jumimaru** [Hekili/hekili#3963]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Destruction

### Describe the Issue

Recommendation issue when practicing on a target dummy.

Really nothing weird.

### How to Reproduce

See logfile.

### Snapshot (Link)

https://pastebin.com/BEVsYZy1

### Raidbots Sim Report (Link)

(https://www.raidbots.com/simbot/report/atm7Hhv2FfT4DKDtuf1JWe)

**Comment by syrifgit** [comment]
Please add a quicksim link for your character with the same talents/situation

**Comment by Jumimaru** [comment]
Sure, here you go brother!

https://www.raidbots.com/simbot/report/atm7Hhv2FfT4DKDtuf1JWe

**Comment by Jumimaru** [comment]
Sorry, fat finger close -_-'

**Comment by Jumimaru** [comment]
Let me know if you need more information @Hekili @syrifgit :)

**Comment by syrifgit** [comment]
Seems to be an issue with Infernal Bolt, looking into it.

**Comment by syrifgit** [comment]
I think I see what's wrong with it. Interestingly, I wasn't able to reproduce the issue.

**Comment by Jumimaru** [comment]
Is this ticket still relevant?

**Comment by Hekili** [comment]
I'm going to close it as stale -- if the problem recurs, submit a new ticket with a new snapshot.
