### ISSUE TITLE
[FEATURE] How can I keep this status notification persistent

### ISSUE THREAD

**Issue by Judisstoo** [Hekili/hekili#3964]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

How can I keep this status notification persistent, as it's easy to forget my current status during combat? Every time I toggle it, the message disappears after about 4 seconds.
![微信截图_20241014134649](https://github.com/user-attachments/assets/38f7186c-43fd-408e-85d2-69c1dddec83a)

**Comment by syrifgit** [comment]
Use the weakaura: https://wago.io/HekiliToggles
