### ISSUE TITLE
[REC] Dispatch from stealth?

### ISSUE THREAD

**Issue by sapperphish** [Hekili/hekili#3965]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

So i noticed in M+....after taking a pack down and entering stealth for next pack (only entering stealth after subterfuge runs out)....that hekili was recommending dispatch instead of Bte sometimes. Upon further experimentation at dummies ....if i start whacking them and then vanish and step away.....bte will be recommended then as soon as combat drops it reverts to dispatch.

### How to Reproduce

1. Enter game as Outlaw KIR Fatebound build.
2. Hit dummies.
3. Vanish and move away.
4. When combat ends....Bte will change to Dispatch even though in stealth.

### Snapshot (Link)

https://pastebin.com/uN9sERY2

**Comment by syrifgit** [comment]
```
        43.  between_the_eyes ( stealth - 3 )
        The action (between_the_eyes) is unusable at (0.00 + 1.00) because bte subterfuge bug workaround.
```

Apparently this is a workaround to the BTE bug? Can you try actually following the rotation you think it should be and see if you are even allowed to cast BTE?

**Comment by sapperphish** [comment]
Sure yes...retesting right now....Bte always works as intended despite the Dispatch recommended on Hekili....crackshot and ace procs are working properly from this Bte.  I can live with it for 8 more days tbh....the patch is getting rid of the Bte bug i hope.
Something is wrong tho.  Dispatch out of stealth with the correct combo points and Bte not on CD can't be right.

**Comment by Hekili** [comment]
It's right if you don't want to risk BtE's CD not being reset. But it will be moot next week.

**Comment by sapperphish** [comment]
Big thanks for the work u folks do with hekili....!!!!
