### ISSUE TITLE
Assassination Rogue Tempered Potion never recommended though checked

### ISSUE THREAD

**Issue by Silentzar** [Hekili/hekili#3966]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Even though Tempered Potion is in the database now, it is never recommended -- even when box is checked to "boss only". I did notice that when you choose it out of the database list under gear/equipment that only the r1 is shown (I use r2 level of that potion) with no way to  choose a different r-level (if that even matters?). Either way, it is never recommended now matter how long the fight.

### How to Reproduce

1. ensure the potions box is checked
2. ensure Tempered Potion is in database and check box for "Boss fight only"
3. enter boss fight with sin rogue
4. potion is never recommended

### Snapshot (Link)

I cannot make a snapshot of something not happening.

### Raidbots Sim Report (Link)

# Base Actor armory=us,stormrage,Silentzar name=Silentzar  # Consumables potion=tempered_potion_2 food=beledars_bounty flask=flask_of_alchemical_chaos_2  # Expansion Options temporary_enchant= thewarwithin.dawn_dusk_thread_lining_uptime=0.6  # Actors  # Simulation Options iterations=5000 desired_targets=1 max_time=300 calculate_scale_factors=0 scale_only=strength,intellect,agility,crit,mastery,vers,haste,weapon_dps,weapon_offhand_dps override.bloodlust=0 override.arcane_intellect=0 override.power_word_fortitude=0 override.battle_shout=0 override.mystic_touch=0 override.chaos_brand=0 override.skyfury=0 override.mark_of_the_wild=0 override.hunters_mark=0 override.bleeding=0 report_details=1 single_actor_batch=1 optimize_expressions=1

**Comment by syrifgit** [comment]
> I cannot make a snapshot of something not happening.

That's exactly what the snapshot will do in this situations. Please provide the snapshot instead of making assumptions, as we will not be able to do any analysis without it.

Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot 


The sim isn't necessary for this particular one, but all that is wanted for it is a link to your quick sim from raidbots.

**Comment by Silentzar** [comment]
Take a snapshot of when I *think* it should recommend the potion but it’s not there?  I’m not sure why you would need that since the problem is the potion is never ever recommended. Last season, the potion I used was always recommended during a boss fight. This season, this battle potion (Tempered Potion) is never recommended. Why is that?  How do I take a picture of it when it never shows up in the window?  That’s not an “assumption”, that’s simply a fact. On Oct 14, 2024, at 8:27 AM, syrifgit ***@***.***> wrote:﻿

I cannot make a snapshot of something not happening.

That's exactly what the snapshot will do in this situations. Please provide the snapshot instead of making assumptions, and we will not be able to do any analysis without it.
Please get a proper snapshot during the time you think the recommendation is incorrect.
Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot
The sim isn't necessary for this particular one, but all that is wanted for it is a link to your quick sim from raidbots.

**Comment by syrifgit** [comment]
Well, it doesn't really matter that you're not sure why I need it. If you want the issue looked at, get in combat and press the keybind to make a snapshot, get the text and put it into pastebin.

Full instructions and explanation of the snapshot is available both in game in the add-on settings snapshot section as well as in the link I provided in my last reply.

If you decide to do it you can reopen the ticket.

**Comment by Silentzar** [comment]
Nice. Ok, well I guess I can send as many pictures as you’d like of the potion *not* being in any of the recommendation windows. I can even make a video of fighting a boss if you’d like?  For the life of me, I don’t know what is so confusing about “the Tempered Potion is never recommended when I ask for it in a boss fight” like my previous battle potion always did last season (Elemental Potion of Ultimate Power) so that you need a picture of it *not* being recommended. Oh well. Maybe you guys will fix it eventually when enough people bring it up?  Take care. On Oct 14, 2024, at 2:10 PM, syrifgit ***@***.***> wrote:﻿
Closed #3966 as not planned.

**Comment by syrifgit** [comment]
If you actually opened the instructions I sent, you'd see that it is not a "picture". A snapshot is a detailed log of the logic and decisions made by the addon, which can very quickly and easily tell us why the addon does or does not show something. It's hundreds of lines of text, and is a very powerful diagnostic tool for people familiar with the addon.


https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by Silentzar** [comment]
I got it to work. It was a user error on my part. Thank you for your patience and I apologize if I was short with you.Sent from my iPhoneOn Oct 14, 2024, at 3:59 PM, syrifgit ***@***.***> wrote:﻿
If you actually opened the instructions I sent, you'd see that it is not a "picture". A snapshot is a detailed log of the logic and decisions made by the addon, which can very quickly and easily tell is why the addon does or does not show something. It's hundreds of lines of text.
