### ISSUE TITLE
[REC] Hekili doesn't recommend trinket [Kaheti Shadeweaver's Emblem]

### ISSUE THREAD

**Issue by Jumimaru** [Hekili/hekili#3967]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Destruction

### Describe the Issue

For my Warlock i expact the addon to recommend the trinket Kaheti Shadeweaver's Emblem, but it doesnt even when its at full power. 

### How to Reproduce

Kaheti Shadeweaver's Emblem doesn't get a recommendation, probably not in the default rotation list.

### Snapshot (Link)

https://pastebin.com/kG3sR1hp

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/4gFZXUfZ7htRoGhSm3TYjV

**Comment by syrifgit** [comment]
The trinket randomly applies a buff and you activate when that happens to trigger the effect. You would need to provide a snapshot when this buff is on you and the trinket still isn't recommended.

```
player_buffs:
   108366 - soul_leech                               -   1 - 3600.00
   186406 - *sign_of_the_critter                     -   1 - 3600.00
   335149 - *sign_of_the_scourge                     -   1 - 3600.00
   415603 - *encapsulated_destiny                    -   1 - 3600.00
   387158 - impending_ruin                           -   8 - 3600.00
```



```
        Substituting kaheti_shadeweavers_emblem for Kaheti Shadeweaver's Emblem action; it is otherwise not included in the priority.
        38.  kaheti_shadeweavers_emblem ( items - 2 )
        The action (kaheti_shadeweavers_emblem) is unusable at (3.58 + 1.34) because required buff (kaheti_shadeweavers_dark_ritual) not active.
```

```
    kaheti_shadeweavers_emblem = {
        cast = 0,
        cooldown = 60,
        gcd = "off",

        item = 225651,
        toggle = "cooldowns",
        buff = "kaheti_shadeweavers_dark_ritual",

        proc = "damage",

        handler = function()
            removeBuff( "kaheti_shadeweavers_dark_ritual" )
        end,

        auras = {
            kaheti_shadeweavers_dark_ritual = {
                id = 455479,
                duration = 30,
                max_stack = 10
            }
        }
    },
```

**Comment by Jumimaru** [comment]
https://pastebin.com/c4XWstXM

https://pastebin.com/SgtuidkZ

This should do the trick brother, let me know if you need anything else (y)!

**Comment by syrifgit** [comment]
The trinket buff is still not on you when you took those snapshots. You're going to need to be in combat and fighting for it to proc, not sitting on a mount ... 

![image](https://github.com/user-attachments/assets/bc716021-a59e-4d1a-8fc9-77043fee59b8)

**Comment by Jumimaru** [comment]
![WoWScrnShot_101524_165913](https://github.com/user-attachments/assets/3b896ef3-009b-43ac-a8a1-e287577e95b5)

You can see in this picture i have the buff on me (10 stacks)!
But still no recommendation in the addon.

This should be the log from the screenshot:

https://pastebin.com/pgSyZsRR

At maximum stacks, the trinket does not show in my prio list, when you press it, you do the dmg. It needs to show the icon when it's at full stacks (at least it should).

Hope this helps, even the log does say i don't have the buff. The reality is i have the buff (check screenshot).

**Comment by syrifgit** [comment]
Looks like it might be a spellID issue. Are you able to do the following?

Get a spellID weakaura, or use the addon ID Tip and get a spellID for these situations? You just need to mouse over the buff and write down the number.

- 1 stack of the buff
- 10 stacks of the buff

![image](https://github.com/user-attachments/assets/920aa9e0-0573-48f7-ab3f-66d7dc9d1152)

**Comment by johnnylam88** [comment]
The snapshot shows the spell ID for the Kaheti buff at 10 stacks as 455464.

**Comment by johnnylam88** [comment]
`TheWarWithin/Items.lua` has the buff ID as 455479, so there's definitely a discrepancy.

**Comment by syrifgit** [comment]
> `TheWarWithin/Items.lua` has the buff ID as 455479, so there's definitely a discrepancy.

Yeah that's what I was thinking, I just don't have the trinket to test for myself lol.

**Comment by Jumimaru** [comment]
I can test for you, but i am limited in time, but i can try my very best ^^

**Comment by johnnylam88** [comment]
I decided to just make a PR for it since the change is small and seemed correct when I looked up the relevant spells on Wowhead.

**Comment by Hekili** [comment]
Fix is in for next release.
