### ISSUE TITLE
[REC] Brewmaster: Rising Sun Kick should be prioritized ahead of Tiger Palm even for Blackout Combo builds

### ISSUE THREAD

**Issue by ptarjan** [Hekili/hekili#3970]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Brewmaster

### Describe the Issue

For my Brewmaster I expected to press Risking Sun Kick ahead of Tiger Palm to get it on cooldown as Tiger Palm doens't have a cooldown. It won't consume the Blackout Combo proc which should still be availble.

### How to Reproduce

1. Create a Brewmaster
2. Choose Blackout Combo talent
3. Look at Hekili and see that the first two recommendations for the opener are "Blackout Kick" then "Tiger Palm

### Snapshot (Link)

https://pastebin.com/H8bBwY6P

**Comment by johnnylam88** [comment]
This one is tricky because you really don't want to accidentally use BoC with Celestial or Purifying Brew, so most priorities will immediately spend BoC to not delay mitigation.

**Comment by ptarjan** [comment]
Agreed, you shouldn't spend the proc on those. But can the priority list know that a BoC is pending and instead recommend the Tiger Palm ahead of the defense? I agree that it is 3 globals before mitigation instead of 2 globals, but we are already prioritizing offence over defense otherwise we would have offered mitigation right at the start, so we should just lean into that to get them all on cooldown. The player can of course choose to hit their defensives earlier, but my assumption is that hekili prioritize DPS ahead of defense.

**Comment by Hekili** [comment]
There's a priority update that simplifies/streamlines the BrM priority quite significantly (down to ~50 lines and one list).  I've made a couple of adjustments to ensure Celestial and Purifying are ruled out while BoC is active, unless you turn off the Maximize Damage option (or whatever I called it).
