### ISSUE TITLE
[REC] periodic gain of stacks from bonestorm isn't implemented

### ISSUE THREAD

**Issue by kyatastrophe** [Hekili/hekili#3976]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Blood

### Describe the Issue

periodic gain of stacks from bonestorm isn't implemented causes over-recommendation of marrowrend

### How to Reproduce

in bonestorm its overrecommending marrowrend if you fall below bone shield stacks 

### Snapshot (Link)

https://pastebin.com/Ke7E4vhB

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/dTBQWdamdJLvWwBL8Cosvm

### Contact Information

kyatastrophe

**Comment by johnnylam88** [comment]
Your snapshot shows that Marrowrend is being suggested because Exterminate is about to fall off, which is the right thing to do regardless of if Bonestorm is up or not.

**Comment by syrifgit** [comment]
> Your snapshot shows that Marrowrend is being suggested because Exterminate is about to fall off, which is the right thing to do regardless of if Bonestorm is up or not.

What about the 2nd marrowrend?

**Comment by johnnylam88** [comment]
For Recommendation 1, `buff.bone_shield.stack == 6`, but for Recommendation 3, `buff.bone_shield.stack == 1`. I don't see why that would happen since Recommendation 2 was just `death_strike`.

**Comment by Hekili** [comment]
The issue is that the model for Bone Shield had `max_stack` = 1; stacks were appropriately taken from the API for the first recommendation, but the addon enforced its `max_stack` value after the first Marrowrend, which then caused the next Marrowrend condition to be met.

This is fixed for next release, and modeling the Bonestorm -> Bone Shield gains has also been added.
