### ISSUE TITLE
[FEATURE] Frostfire bolt added to ability list for mages

### ISSUE THREAD

**Issue by Norvelas** [Hekili/hekili#3978]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'd like Hekili to add in the ability Frostfire bolt to the ability list. Frostfire empowerment makes Frostfire bolt insta cast, deal more, damage, and always crit. As a fire mage, this does way more damage than weaving in a Heat Shimmer for Scorch and a Phoenix Flames with From the Ashes buff. It also applies a slow and dot which can def help in PvP

**Comment by Hekili** [comment]
The addon substitutes Frostfire Bolt in place of Fireball for Fire Mage by default.  I'd need to see a snapshot when Frostfire Bolt isn't being recommended despite Frostfire Empowerment, but Fireball / Scorch / Phoenix Flames is recommended instead.

A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press `ALT-SHIFT-P` to Pause and Snapshot (or use `ALT-SHIFT-[` to Snapshot without pausing).
   * You can change these keybindings in `/hekili` > `Toggles` if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type `/hekili` and press Enter.
 * Open the `Snapshots (Troubleshooting)` section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the `Export Snapshot` box, press `CTRL+A` to select all text including hidden text and press `CTRL+C` to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use `CTRL+V` to paste the snapshot text, then click Create New Paste.  If you only end up with one line of text, then you did not press `CTRL+A` to select all text.  Try again before continuing.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Aerio2236** [comment]
Frostfire Bolt replaces Fire Bolt in the Spellbook and does not get recommended at all. I have checked and Fire Bolt is enabled in Hekili settings. Once you run out of Phoenix Flames and Fire Blasts the recommendations break.

Snapshot: https://pastebin.com/exSXA917

**Comment by syrifgit** [comment]
@Hekili This is likely fixed with the new frostfire bolt IDs in 11.0.5 and the `copy` section of fireball? I'll check

**Comment by syrifgit** [comment]
Nvm, not fixed on new version.
