### ISSUE TITLE
[REC] Corruption recommendation issue

### ISSUE THREAD

**Issue by Jumimaru** [Hekili/hekili#3979]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Affliction

### Describe the Issue

Corruption keeps getting a recommendation even when it's already on the target (Target Dummy).
![WoWScrnShot_101724_092139](https://github.com/user-attachments/assets/34515c35-8e84-479e-87fb-0fce5863ce46)
 

### How to Reproduce

Spec into Aflliction and follow the single target rotation.

### Snapshot (Link)

https://pastebin.com/aTdFBN8X

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/w6kfzq2zw9TRpqo4R3phtf

**Comment by syrifgit** [comment]
Looks like the refreshable variable might be borked? a 20 second dot is uh .. probably not in the pandemic window.

`   146739 - corruption                               -   1 - 20.02 `

```
 54.  corruption ( default - 13 )
        The action (corruption) is usable at (0.00 + 0.00) with cost of 25000 mana (have 2338275).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry's criteria PASSES: ! ( action.seed_of_corruption.in_flight[false] | active_dot.seed_of_corruption[0.00] > 0 ) & refreshable[true] & fight_remains[30.00] > dot.corruption.remains[20.02] + 5
```

**Comment by Hekili** [comment]
> Looks like the refreshable variable might be borked? a 20 second dot is uh .. probably not in the pandemic window.

*Sort of.*

@Jumimaru has Absolute Corruption talented so Corruption's apply duration is changed to 3600.  However, they are attacking a PvP dummy, and Absolute Corruption only has a 24 sec duration for players.  It'd be helpful to see if `target.is_player` works for the PvP dummy; if so, I can easily adjust Corruption's duration based on the type of target.

edit:  `target.is_player` doesn't work -- because the existing code already checks for it.  I'll have to look for other API functions to check.

```Lua
corruption = {
    id = 146739,
    duration = function () return ( talent.absolute_corruption.enabled and ( target.is_player and 24 or 3600 ) or 14 ) * ( talent.creeping_death.enabled and 0.85 or 1 ) end,
    tick_time = function () return 2 * ( 1 - 0.15 * talent.creeping_death.rank ) * ( 1 - 0.15 * talent.sataiels_volition.rank ) * haste end,
    type = "Magic",
    max_stack = 1
},
```

**Comment by Hekili** [comment]
I will add the Dornogal PvP training dummy to this list of faked player NPC IDs in the next update.
