### ISSUE TITLE
[REC] Assasination Rogue - Unable to make recommendation for Primary...

### ISSUE THREAD

**Issue by JustZexxi** [Hekili/hekili#3981]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

From time to time when playing the addon says it's impossible to make recommendations I'm sending a screen and also a pastebin with a snapshot.

![WoWScrnShot_101724_141705](https://github.com/user-attachments/assets/ac7b64ca-9fdb-48d0-a910-8fb2b6358c7d)

### How to Reproduce

Cant really find a patern how to reproduce it since it seems to be random and not based on any talents or rotation.

### Snapshot (Link)

https://pastebin.com/RPMbWmR4

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qBw9piF7AzrGwUkivLbZXw

### Additional Information

It was mostly aoe fight but at the time the addon made a error all of the mobs was mostly dead and only one was alive

### Contact Information

discord - zexxi

**Comment by Hekili** [comment]
This is fixed for next release (failure to recommend a builder/spender at 6 CP with Darkest Night active).
