### ISSUE TITLE
[REC] (Balance Druid) Sunfire constant priority when still applied on targets

### ISSUE THREAD

**Issue by crackerbiz** [Hekili/hekili#3984]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

Sunfire will permanently take up the first spot on the priority helper, even when you apply it multiple times.  

### How to Reproduce

1. Enter as a Balance Druid 2. Fight mobs or rares and you will eventually run into the problem 3. Very easily shown on Ulgrax the Devourer from the Skittering Battlements

### Snapshot (Link)

https://pastebin.com/9LWJ2PYq

**Comment by syrifgit** [comment]
Are you using action-targeting mode? The addon thinks you don't have a target, and as such it has no debuffs to check so it thinks sunfire is down.

**Comment by Hekili** [comment]
Syrif's explanation is correct; the addon pulls information from your "hard" target, while you're using action targeting (which provides a "soft" target).  There's no support for action targeting at this time.
