### ISSUE TITLE
[REC] Assasination rogue opener changes from precombat when a few globals in

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3985]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Precombat, the recommendation is showing ambush->garrote->rupture->echoing reprimand->rupture->FoK->SnD but the simcraft recommendation is ambush->garrote->rupture->snd->ER. After the initial rupture, the recommendation order changes to remove the second rupture and to snd before ER

### How to Reproduce

Enter game as sin rogue, displayed recommendation will change after the opener.

### Snapshot (Link)

https://pastebin.com/5qKMJpvC

**Comment by syrifgit** [comment]
Are you using action targeting mode?

`target_auras:  target does not exist`

**Comment by fzarr** [comment]
Nope I don't have that option turned on. In this particular case i was targetting a dummy but I targetted an enemy npc in a dungeon and it showed the same issue.

**Comment by Hekili** [comment]
> Nope I don't have that option turned on. In this particular case i was targetting a dummy but I targetted an enemy npc in a dungeon and it showed the same issue.

You'd want to provide a snapshot of that, since the other one does not have a real active target.

**Comment by Hekili** [comment]
Also:

> the simcraft recommendation is ambush->garrote->rupture->snd->ER

Is there a combo point refund from Rupture that would make Slice and Dice available in your sim?  Otherwise, I'm not sure how you Rupture -> SnD without generating combo points.  Bear in mind, the addon *does not* pretend unpredictable things will happen.  If Rupture has a *chance* to proc a refund of Combo Points, the addon will wait and react to see if it happens instead of anticipating something that may not happen.

Anyway, can you provide a Raidbots link that shows this?

The FoK is the next recommendation after Rupture because you're not expected to have combo points for SnD, and the next entry that has its criteria met is FoK with Clear the Witnesses procced.

**Comment by wrogg** [comment]
> Is there a combo point refund from Rupture that would make Slice and Dice available in your sim? 


Having the Serrated Bone Spike buff guarantees that combo points will be available after Rupture.
Also, hijacking this to mention that Ambush is being recommended out of stealth to apply the hero talent, Deathstalkers Mark, but when you have Darkest Night buff active, your envenom will apply the mark and thus Ambush from stealth shouldn't be recommended as per guides. Here's my snapshot showing this happening: https://pastebin.com/K1mWzxhy

**Comment by fzarr** [comment]
Sorry I thought i had included a raidbots link, here it is: https://www.raidbots.com/simbot/report/g8seC9hUwL991VEhqbJsq4 and an updated snapshot on dungeon mob: https://pastebin.com/fBGJbzk9. Like wrogg says, if you have a serrated bone spike active, at least 1cp will be guaranteed after pressing rupture (more in aoe).

Not sure if its best to open a second ticket from wrogg's other issue but I also noticed that, it turns out the APL in hekili has this line:
`actions.stealthed+=/ambush,if=!debuff.deathstalkers_mark.up&talent.deathstalkers_mark&(active_dot.deathstalkers_mark=0|buff.darkest_night.down)`
but in the actual APL, the `&(active_dot.deathstalkers_mark=0|buff.darkest_night.down)` condition doesn't exist although in either case it will still apply ambush with the darkest_night buff up. 

Maybe can add an option that removes the 'active_dot.deathstalkers_mark=0' condition thats in the hekili apl currently to be more consistent with guides.

edit: apparently why garrote is recommended in guides is that darkest night is bugged in-game atm and interacts weirdly if both it and a deathstalker's mark are active simultaneously.
