### ISSUE TITLE
Action Bar Highlighting

### ISSUE THREAD

**Issue by dMopp** [Hekili/hekili#399]
I would love if hekili would have an option to highlight the current spell on the action bar like ConRo is doing it.

**Comment by Hekili** [comment]
If you install SpellFlash (a separate addon), you can enable SpellFlash for any of your Hekili displays and have action buttons highlighted.  But I don't recommend it.

The thing about good HUD elements is that they don't leave you playing whack-a-mole with your action buttons.  They let you look at the same place for the same information each time.

I have no plans to further enhance that feature or implement similar features.

**Comment by dMopp** [comment]
Actually SpellFlash is not compatible with ElvUI (anymore) afaik since 2018  :(

**Comment by Crelam** [comment]
You can build your own solution using Weakauras if you are so inclined. Use https://wago.io/JksSkiOp7 as a starting point and use the 'glow external frame' action.

**Comment by dMopp** [comment]
> You can build your own solution using Weakauras if you are so inclined. Use https://wago.io/JksSkiOp7 as a starting point and use the 'glow external frame' action.

Thx. I have zero knowledge right now but i will try
