### ISSUE TITLE
Execution Sentence in AO

### ISSUE THREAD

**Issue by veroinx** [Hekili/hekili#3992]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

When engaging in an AoE scenario, Execution Sentence is not recommended at any point. 

### How to Reproduce

1. Enter game as Retribution Paladin.
2. Take the this build (Wowhead Templar M+ build) CIEAAAAAAAAAAAAAAAAAAAAAAsNjZYWM2egHwYmxymZmxMGzYGAAAAAAAAAA0WDzMziBmZYmZxAmNAYMwAwAGgBAABYmZZbptZGLmB
3. Engage in AoE fight on training dummies
4. See recommendations.

### Snapshot (Link)

https://pastebin.com/RY9H0whw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/uMSRcQo57P3cfZF75ypJ6S

**Comment by veroinx** [comment]
I did manage to get Execution sentence to show up in the list of recommended abilities but was not able to snapshot it. It's incredibly inconsistent and doesn't show nearly as often as it should given it only has a 30 second CD and should line up with every Wake of Ashes.

**Comment by Hekili** [comment]
Execution Sentence is not recommended when your target won't live for more than 8 seconds.  In your snapshot, your current target is estimated to die in 5 or fewer seconds.  (Basically, you were attacking a dummy that was sitting close to 1 HP.)

**Comment by veroinx** [comment]
Thank you! I hadn't thought about this scenario. Appreciate your time and
efforts with this addon!
