### ISSUE TITLE
[REC]  Frost DK - Remorseless Winter 

### ISSUE THREAD

**Issue by devil81** [Hekili/hekili#3994]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

It is very simple , the addon never recomand remorseless winter 

### How to Reproduce

https://www.raidbots.com/simbot/report/37drV2A9FmUmiPN9xFN5PQ

### Snapshot (Link)

https://pastebin.com/YehPTiYY

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/37drV2A9FmUmiPN9xFN5PQ

### Contact Information

viorel.ghita@gmail.com

**Comment by devil81** [comment]
Also i see no Death and Decay on opener

**Comment by devil81** [comment]
![image](https://github.com/user-attachments/assets/3a0ee821-ff38-46db-b01d-eccc4c60f159)

**Comment by Hekili** [comment]
It looks like this should be fixed as of today's release.
