### ISSUE TITLE
[REC] Assassination Rogue: shiv occasionally getting recommended pre-tailend of kingsbane window 

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#3996]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

This is something I've seen happen quite a few times but I've only managed to capture one snapshot so far, but I'll add more to this ticket as I encounter it.

The issue is that sometimes shiv will be recommended even if kingsbane or deathmark are ready to use or almost ready to use (in the attached snapshot, kingsbane is off cd and deathmark will be off cd in 8seconds). There are some syncing of cooldowns that complicate matters but i think the attached snapshot shows a case where shiv use should have been withheld til about 20 seconds later. Additionally, even though its recommending shiv to ensure shiv is up for kingsbane, kingsbane is delayed (probably due to syncing with deathmark) so the shiv window is wasted and won't be back up for kingsbane.

In cases where there are only one shiv charge, shiv should be held til the last 8 seconds of kingsbane, unless kingsbane has > 30s coodown left so you can fit another shiv in.

One interesting thing i saw in the snapshot is that for recommended #2, step 40. says Action chosen:  deathmark at 8.15! but it doesn't choose it but I guess that could be just an internal state thing.

### How to Reproduce

Can't accurately reproduce this yet, I'll try to identify a pattern or state. Seems to happen mostly when stealth/vanish.

### Snapshot (Link)

https://pastebin.com/SLbzsrYj
https://pastebin.com/bMtA7AvK

**Comment by Hekili** [comment]
As written, the priority without Lightweight Shiv will still use Shiv in the `stealthed` action list, if Kingsbane is *ready* and Shiv hasn't been applied, when Envenom is up.  I believe this would show in your sims as well.

```
18.  shiv ( stealthed - 3 )
The action (shiv) is usable at (0.00 + 0.00) with cost of 30 energy (have 256).
- the action is ready before the current recommendation (at +0.00 vs. +10.00). 
List ( stealthed ) called from ( Assassination:default:8 ) would PASS at 0.00.
    stealthed.rogue[false] | stealthed.improved_garrote[true] | master_assassin_remains[0.00] > 0
- this entry's criteria PASSES: talent.kingsbane.enabled[true] & ( dot.kingsbane.ticking[false] | cooldown.kingsbane.up[true] ) & ( ! debuff.shiv.up[false] & debuff.shiv.remains[0.00] < 1 ) & buff.envenom.up[true]
Action chosen:  shiv at 0.00!
```

I do see that Kingsbane isn't about to be used there, so there is probably additional logic needed to sync them up.  Can you provide a Raidbots sim?

**Comment by Hekili** [comment]
> Action chosen: deathmark at 8.15!

This means it that Deathmark criteria would be met in 8.15 seconds; it still looks for something that has its criteria met, sooner.

**Comment by fzarr** [comment]
https://www.raidbots.com/simbot/report/g8seC9hUwL991VEhqbJsq4 

It does seem like they fire shiv off in stealth instead of waiting til the tail end of kb (2m11s) - im not sure if thats an error on their end or not. I think its this same logic causing my issue - its just that the sim has zero downtime and perfect play so they never encounter a situation e.g. going between packs in m+ or downtime due to a mechanic that causes shiv to be used _before_ kb.

edit: apparently the shiv straight after kb in vanish is because of a micro-optimisation since garrote is such an efficient combo point generator. I guess in the sim it will be perfect, but if you are in game, some situations might cause this to use shiv incorrectly.

**Comment by Hekili** [comment]
I've made modifications to address this in the latest release.
