### ISSUE TITLE
[REC] Revise Arcane Opener Variable

### ISSUE THREAD

**Issue by nikolavuljan** [Hekili/hekili#3999]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Arcane

### Describe the Issue

**Issues**:
1. Currently ToTM is required to be up to even start doing a 2nd evocation into the fight, meaning you're wasting about 5 seconds of your cooldowns every time it happens. (as an example, sim usually 2nd evocates at about 1:18 into the fight, while third ToTM only comes up around 1:21)
2. The sim apl does not take into consideration evocation cooldown for the small burn gate as it never desyncs in a patchwerk enviroment

**Current logic for opener variable:**
```
(cooldown.touch_of_the_magi.up)
&(cooldown.arcane_surge.up|action.arcane_surge.time_since<5|cooldown.arcane_surge.remains>15) 
&(cooldown.evocation.up|action.evocation.time_since<5|cooldown.evocation.remains>15)
```
**Recommendation 1.**
"Big burn" gate should somewhat follow the APL requirement - evocation itself has this
```
cooldown.arcane_surge.remains<(gcd.max*3)&cooldown.touch_of_the_magi.remains<(gcd.max*5)
```

**Recommendation 2.**
"Small Burn" gate in the opener variable has "evocation and surge cd>15" while the APL itself asks for atleast 30sec, tho only on surge as they never desync, increasing this from 15 will mean its more likely your cooldowns resync during downtimes (M+ between packs) and create a safety net.

**My Result:**
Big burn gates open at surge gcd max 2 and totm gcd max 4 (compared to 3 and 5 of APL) - more conservative to not break something, make evocation within 7 seconds in case you get CC/big movement while casting surge - buff is 20sec so you have all the time to execute a burn
OR Small burn gate at >27sec cd on evocation and >30sec surge (like the evocation APL) making a resync more likely
```
((cooldown.touch_of_the_magi.remains<(gcd.max*4))&(cooldown.evocation.up|action.evocation.time_since<7)
&(cooldown.arcane_surge.remains<(gcd.max*2)|action.arcane_surge.time_since<5)) # Big burn gate
|(cooldown.evocation.remains>27&cooldown.arcane_surge.remains>30&cooldown.touch_of_the_magi.up) # OR Small burn gate
```

### How to Reproduce

1. Enter game as mage
2. Do your big burn
3. Wait until evocation is up again
4. Look how it isnt recommended until ToTM is up

### Snapshot (Link)

no snapshot needed

**Comment by Hekili** [comment]
@syrifgit Can you give me a head's up if this needs to be reviewed/integrated or if it's stale with 11.0.5 launch?

**Comment by Hekili** [comment]
Resolved in Syrif's PR.
