### ISSUE TITLE
Make Hekili use default AceDB profile by default

### ISSUE THREAD

**Issue by comiluv** [Hekili/hekili#400]
Please describe your idea or feature and when it would be useful.
Currently Hekili makes a new profile for every other character when logged in, but it would actually be more convenient if it managed configurations in a single setting if the player has any alt.
This only need line 63 in core.lua to be changed
```lua
function Hekili:OnInitialize()
    self.DB = LibStub( "AceDB-3.0" ):New( "HekiliDB", self:GetDefaults() , true)
```
like above.

Also see [Curseforge authors post](https://authors.curseforge.com/forums/world-of-warcraft/addon-chat/frameworks/ace3/209666-acedb-and-default-profiles-picking-a-bone) which discusses this topic

**Comment by Hekili** [comment]
This is not unreasonable at all, and Shadowlands would be a good time to make this shift.

**Comment by Hekili** [comment]
This is going in the next alpha build.
