### ISSUE TITLE
Outlaw Rogue. variable.rtb_reroll returns 0 instead of true or false

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#4000]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

In the Outlaw simc profile there are currently 3 variables, that are named "variable.rtb_reroll".

Number 1   # Default rule: reroll if the only buff that will be rolled away is Buried Treasure, or Grand Melee in single target without upcoming adds
actions+=/variable,name=rtb_reroll,value=rtb_buffs.will_lose=(rtb_buffs.will_lose.buried_treasure+rtb_buffs.will_lose.grand_melee&spell_targets.blade_flurry<2&raid_event.adds.in>12&raid_event.adds.count<2)

Number 2    # If Loaded Dice is talented, then keep any 1 buff from Roll the Bones but roll it into 2 buffs when Loaded Dice is active
actions+=/variable,name=rtb_reroll,if=talent.loaded_dice,value=rtb_buffs.will_lose=buff.loaded_dice.up

Number 3  # If all active Roll the Bones buffs are ahead of its container buff and have under 40s remaining, then reroll again with Loaded Dice active in an attempt to get even more buffs
actions+=/variable,name=rtb_reroll,**value=variable.rtb_reroll&**rtb_buffs.longer=0|rtb_buffs.normal=0&rtb_buffs.longer>=1&rtb_buffs<6&rtb_buffs.max_remains<=39&!stealthed.all&buff.loaded_dice.up

The problem is, that 3d variable is referring to either 1st, or 2nd rtb_reroll variable and adds up some new rules to it, but addon does not recognise that inner call to a previous variable in 3d variable.rtb_reroll and returns 0 instead of "true" or "false"
That leads to a false "pass" of variable, despite it should be returned as "false"

        10.  variable ( default - 3 )
        rtb_reroll #1 [Outlaw:default:3]; conditions = PASS: NONE
         - value = false: rtb_buffs_will_lose[3.00] = ( rtb_buffs_will_lose_buff.buried_treasure[true] + rtb_buffs_will_lose_buff.grand_melee[true] & spell_targets.blade_flurry[1.00] < 2 & raid_event.adds.in[3600.00] > 12 & raid_event.adds.count[0.00] < 2 )
         - variable.rtb_reroll[false] will check this script entry ( Outlaw:default:3 )
        Time spent on this action:  0.05ms
        TimeData:Outlaw-default-3:variable:0.05:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03)

        11.  variable ( default - 4 )
        rtb_reroll #2 [Outlaw:default:4]; conditions = PASS: talent.loaded_dice.enabled[true]
         - value = false: rtb_buffs_will_lose[3.00] = buff.loaded_dice.up[false]
         - variable.rtb_reroll[false] will check this script entry ( Outlaw:default:4 )
        Time spent on this action:  0.05ms
        TimeData:Outlaw-default-4:variable:0.05:Ability Known, Enabled(0.03):Post-TTR and Essential(0.02)
 
        12.  variable ( default - 5 )
        rtb_reroll #3 [Outlaw:default:5]; conditions = PASS: NONE
         - value = true: variable.rtb_reroll[0.00] & rtb_buffs_longer[0.00] = 0 | rtb_buffs_normal[2.00] = 0 & rtb_buffs_longer[0.00] >= 1 & rtb_buffs[3.00] < 6 & rtb_buffs_max_remains[16.08] <= 39 & ! stealthed.all[true] & buff.loaded_dice.up[false]
         - variable.rtb_reroll[true] will check this script entry ( Outlaw:default:5 )
        Time spent on this action:  0.04ms
        TimeData:Outlaw-default-5:variable:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02)

### How to Reproduce

Follow the recommendations on raid target dummy being outlaw rogue

### Snapshot (Link)

https://pastebin.com/bdvFhnZA

### Contact Information

IIeTpoc#3818 discord ID

**Comment by Hekili** [comment]
This is interesting.  Try changing the Value for `default - 4` to:

`rtb_buffs_will_lose = ( 0 + buff.loaded_dice.up )`

edit:  Nope, this doesn't quite solve it.  Still digging.

**Comment by Hekili** [comment]
Found the issue; will be fixed in next release.
