### ISSUE TITLE
MF:I not being recommended during rotatio | Vampiric Touch spam as filler

### ISSUE THREAD

**Issue by justinEKG** [Hekili/hekili#4003]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

During extended single target encounter as Voidweaver Shadow Priest, Vampiric Touch is recommended multiple times in a row (i.e. 5-6). Mind Flay: Insanity is never recommended. I hope the snapshot is useful, but I can grab others if necessary.

### How to Reproduce

With cooldowns enabled, just do your ST rotation for maybe ~8 seconds or so. No other requirements.

### Snapshot (Link)

https://pastebin.com/5xjfQXHs

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kVtFod73ogUc6tVTee993o

### Additional Information

Here is the condition to call the "empowered filler" action list:

#19 Call action list - Empower Filler
`( buff.mind_spike_insanity.stack > 2 & talent.mind_spike.enabled | buff.mind_flay_insanity.stack > 2 & ! talent.mind_spike.enabled ) & talent.empowered_surges.enabled & ! cooldown.void_eruption.up`

Empowered Surges is an Archon-only hero talent. As such, the issue I outlined above happens at priority #24 (listed below), so I don't believe a condition is ever satisfied to cast Mind Flay or Mind Flay:Insanity as a filler on situations less than 6 targets:

# 24 Vampiric Touch
`buff.unfurling_darkness_cd.remains < execute_time & talent.unfurling_darkness.enabled & ! buff.dark_ascension.up & talent.inner_quietus.enabled & active_dot.vampiric_touch <= 5`

### Contact Information

glue

**Comment by Hekili** [comment]
For now, try adding `de` to the front of that Vampiric Touch entry; `debuff.unfurling_darkness_cd.remains` ...

**Comment by lucaswj** [comment]
This problem is still there in live release. It will constantly tell you to use VT to fish for unfurling darkness even while it's procced and on CD.
