### ISSUE TITLE
Balance Druid rotation suggesting Regrowth spam as opener

### ISSUE THREAD

**Issue by Toumari** [Hekili/hekili#4005]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

For my Balance Druid, before I start combat, Regrowth is being suggested 3 times, once these have been cast the normal rotation resumes.

### How to Reproduce

1. Enter the game
2. Target an enemy
3. Regrowth is suggested 3 times

### Snapshot (Link)

https://pastecode.io/s/o0nsd0q0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rhCciK2NTaEMy51cnMPAev

### Contact Information

dtox9097 / Dtox

**Comment by Hekili** [comment]
I'm pretty sure there's an open ticket for this.  You can disable Regrowth in /hek > Abilities in the meantime.
