### ISSUE TITLE
[REC] Failed to generate recommendation as aldrachi reaver VDH

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#4008]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Vengeance

### Describe the Issue

Not sure how to replicate, hopefully the snapshot has enough info. I was just hitting a ST dummy. 

Happens frequently in real content and vs a dummy. 

### How to Reproduce

.

### Snapshot (Link)

https://pastebin.com/aLiKMG1y

**Comment by Hekili** [comment]
If this is occurring in 1.0.4 or later, please let me know.
