### ISSUE TITLE
Large FPS drop when enabling addon

### ISSUE THREAD

**Issue by Depoh** [Hekili/hekili#401]
Hi,

I have been using the addon for a while but have noticed a large FPS drop when enabling. This happens on all of my characters, regardless of spec etc. I am sure it is the addon as disabling resolves the issue. This happens in and out of combat (fps is obviously worse in combat anyway but significantly worse when using the addon.) 

I've attached two screenshots with and without the addon enabled. FPS is shown in the bottom right. I've tried installing older version but still having the same issue. Default addon settings were used when taking the screenshots, just after I reinstalled.

Let me know if you need any more detail. I imagine this is a performance issue of some kind.

Character Data;
build: v8.3.0-12
level: 120 (120)
class: DEMONHUNTER
spec: havoc

talents: blind_fury
    demonic
    first_blood
    immolation_aura
    soul_rending
    trail_of_ruin
    unleashed_power

azerite: azerite_empowered = 3
    chaotic_transformation = 1
    eyes_of_rage = 2
    gutripper = 1
    heed_my_call = 2
    longstrider = 1
    revolving_blades = 2
    soulmonger = 1
    thirsting_blades = 1
    vampiric_speed = 1

essences: [essence_of_the_focusing_iris] = 3, breath_of_the_dying = 3, purification_protocol = 2, the_crucible_of_flame = 4

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    besiegers_deckstalkers = 1
    bilestained_crawg_tusks = 1
    bloody_tideturner = 1
    charged_sandstone_band = 1
    cowl_of_fluid_machinations = 1
    goldtasseled_epaulets = 1
    grips_of_electrified_defense = 1
    harlans_loaded_dice = 1
    heart_of_azeroth = 1
    leggings_of_the_galeforce_viper = 1
    logic_loop_of_division = 1
    mydas_talisman = 1
    primal_dinomancers_belt = 1
    servoarm_bindings = 1
    tabard_of_summer_skies = 1
    type_ii_bomber_jacket = 1

corruptions: echoing_void = 3
    twisted_appendage = 1

itemIDs: 155881, 158075, 158319, 158353, 158366, 159299, 159301, 159302, 159320, 159329, 159337, 159635, 159653, 169073, 169157, 169223, 35279

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 7
    nameplates = true
    package = Havoc
    potion = potion_of_focused_resolve
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    demon_blades_acknowledged = false
    recommend_movement = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

![With Addon](https://user-images.githubusercontent.com/69481752/89826735-9c092b00-db4e-11ea-8b96-a2e880f63842.jpg)
![Without Addon](https://user-images.githubusercontent.com/69481752/89826767-a7f4ed00-db4e-11ea-8487-32d4e787c181.jpg)

**Comment by Hekili** [comment]
There's a lot going on here.

1.  Your settings show config options that aren't available in the retail version, though your snapshot reports that you're using the version of the addon for retail.  Did you upgrade to beta and then try to downgrade?  If so, reset your profile.  You may have beta priorities that don't work on retail.

2.  You seem to have other addon install issues; i.e., you have WeakAuras for Classic installed on retail.

3.  Is there BugSack/BugGrabber information?  I'm wondering if there are errors that are impacting performance for you.

On my own installation, idling in Orgrimmar with your talent build is a negligible difference in DPS.

**Comment by Depoh** [comment]
Wow I feel like such a moron. The issue was right in front of my eyes and I didn't see it...

Uninstalled WeakAuras and my FPS jumped up again. Reinstalled the correct version and it hasn't dropped now. Strange how having the wrong version of WeakAuras installed on its own didn't cause a problem but when Hekili was enabled with it I had a drop.

Thanks so much for getting back to me anyway, sorry for wasting your time!

<3

**Comment by Hekili** [comment]
My addon detects WeakAuras and sends some event information to WeakAuras so that people can make HUD elements that interact with it.  If you had BugSack/BugGrabber, there probably would've been error messages related to trying to use WeakAuras.ScanEvents but that it wasn't present.

I'll do a little investigation on that front.  Glad things have improved.  :)
