### ISSUE TITLE
[BUG] UI hangs when pressing Bonestorm

### ISSUE THREAD

**Issue by rmilesson** [Hekili/hekili#4010]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

My UI hangs whenever I'm pressing Bonestorm. The game recovers after about 10s.

### How to Reproduce

1. Enter the game as a Death Knight
2. Engage multiple enemies
3. Press Bonestorm

### Player Information (Link)

https://gist.github.com/rmilesson/53ae36edcc7e7127741688ba68fc5f5f

### Error Messages (Link)

https://gist.github.com/rmilesson/5c8e3e3a8dfce74c4a8719e99a674acb

**Comment by rmilesson** [comment]
I'm no Lua-dev. Far from it, but I assume it's somewhere around here it breaks?

```
                if not ok then
                    err = err .. "\n\n" .. debugstack( thread )
                    Hekili:Error( "Update: " .. err )

                    if Hekili.ActiveDebug then
                        Hekili:Debug( format( "Recommendation thread terminated due to error: %s", err and err:gsub( "%%", "%%%%" ) or "Unknown" ) )
                        Hekili:SaveDebugSnapshot( self.id )
                        Hekili.ActiveDebug = nil
                    end

                    pcall( error, err )
                end
```

How do I turn on `Hekili.ActiveDebug`?

**Comment by Hekili** [comment]
There's no release for 11.0.5 yet; no tickets allowed.

**Comment by rmilesson** [comment]
Eh, what do you mean? I played retail, with Hekili updated from CurseForge?
