### ISSUE TITLE
Passive Enhancement talent "Flowing Spirits" in recommendation.

### ISSUE THREAD

**Issue by Crelam** [Hekili/hekili#4011]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

Flowing Spirits makes Feral Spirits a passive proc instead of an active ability, however it still can show as an active ability for things that reference Feral Spirits like Macros and Action Bar slots.

When talented into Flowing Spirits, it recommends "casting" Flowing Spirits where it would recommend casting Feral Spirits.

I tried to add a condition for flowing_spirits (`!talent.flowing_spirits.enabled`) however it returned false regardless of my talent selection.

### How to Reproduce

Log in as enhancement shaman, select Flowing Spirits talent.

### Snapshot (Link)

https://pastebin.com/c7RBp6j3

### Raidbots Sim Report (Link)

n/a

### Contact Information

crelam

**Comment by Hekili** [comment]
This will be accounted for when the 11.0.5 release goes live.
