### ISSUE TITLE
Vampiric Touch being over recommended during single target for Shadow Priest

### ISSUE THREAD

**Issue by itsDUMPTRUCK** [Hekili/hekili#4012]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

Vampiric Touch is being recommended multiple times in a row (4-5+ times) during single target, even after using the Unfurling Darkness proc.  It seems to get hung up on the ability idk how else to explain it.

### How to Reproduce

1. Be in Shadow Priest Voidweaver spec
2. Follow recommended rotation

### Snapshot (Link)

https://pastebin.com/Ec4g3rHS

**Comment by Hekili** [comment]
There's no release for 11.0.5 yet; no tickets allowed.
