### ISSUE TITLE
Potion action only recommended when old Dragonflight potion in bags

### ISSUE THREAD

**Issue by dglynch** [Hekili/hekili#4015]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

For my retribution paladin, I expect the potion action will be recommended if I have any kind of TWW potion in my bags and if the potion action is enabled. However, this only occurs if I have one specific kind of Dragonflight potion in my bags: item 191387.

I have pasted 2 snapshots in the Link below: one for without the item and one for with.

### How to Reproduce

Enter the game as a retribution paladin
Enable the potion action
Don't have item 191387 in your bags
See that potion is never recommended
Obtain item 191387 from the auction house
See that potion action is now recommended as expected

### Snapshot (Link)

https://pastebin.com/6zbARn9i

**Comment by Hekili** [comment]
See /hekili > Retribution > Specialization Settings > Potion.
