### ISSUE TITLE
[REC] Doesn't track jadefire teachings buff or talent

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#4017]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Mistweaver

### Describe the Issue

When casting jadefire teachings - Hekili doesn't track if the new talent is enabled or whether the buff is up. Both is "false"
buff.jadefire_teachings.up is false

### How to Reproduce

1. Talent into jadefire teachings
2. Cast jadefire teachings
3. Both appear "false" in APL.

### Snapshot (Link)

https://pastebin.com/mKMqZSFa

**Comment by Hekili** [comment]
Fixed for release.
