### ISSUE TITLE
[REC] Can't track jade empowerment (stacks to 2)

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#4018]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Mistweaver

### Describe the Issue

When gaining jade empowerment, hekili doesn't track the buff.
buff.jade_empowerment.up is false
buff.jade_empowerment.stack>1 is 0.

### How to Reproduce

1. Cast Thunder Focus Tea
2. Cast Rising Sun Kick
3. Gain Jade Empowerment buff.
4. Hekili doesn't track it whether you have 1 or 2 stacks

### Snapshot (Link)

https://pastebin.com/XKAnZ5sZ

**Comment by Hekili** [comment]
Fixed for release.
