### ISSUE TITLE
[REC] Can't track buff - Dance of Chi-ji

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#4019]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Mistweaver

### Describe the Issue

When you gain "Dance of Chi-ji", hekili doesn't track the buff.

### How to Reproduce

1. Cast some random spells
2. Gain a proc of "Dance of Chi-ji"
3. Hekili doesn't track the buff, and buff.dance_of_chiji.up appears false.

### Snapshot (Link)

https://pastebin.com/QuKH6Vg3

**Comment by Hekili** [comment]
I promise you don't need to submit tickets for 11.0.5, which I haven't posted a release for (yet).

**Comment by oversoe** [comment]
Didn't think it through about the other 2 buffs then, but this buff has been untrackable for a while, since it's been in the game since TWW launch.

I just came around to submitting this one now with the other 2.

Sorry for the spam and an enormous thanks for keeping healers up to date 🙌

**Comment by Hekili** [comment]
Added for release.
