### ISSUE TITLE
Lots of in game lua errors

### ISSUE THREAD

**Issue by Meltun** [Hekili/hekili#402]
Using the latest version.  Even went back two versions and still happens.  Disabling Hekili eliminates the errors but I am not convinced Hekili is the real culprit.  Any ideas?

- Thanks

Date: 2020-08-11 08:20:45
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Hekili\Core.lua line 1425:
   attempt to call field 'ScanEvents' (a nil value)
Debug:
   [string "@Hekili\Core.lua"]:1425: ProcessHooks()
   [string "@Hekili\UI.lua"]:825:
      Hekili\UI.lua:689
Locals:
self = <table> {
 GetTTD = <function> defined @Interface\AddOns\Hekili\Targets.lua:653
 DeserializeStyle = <function> defined @Interface\AddOns\Hekili\Options.lua:8591
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:3463
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Interface\AddOns\Hekili\Targets.lua:638
 After = <function> defined @Interface\AddOns\Hekili\Utils.lua:268
 NewSpellInfo = true
 Run = <function> defined @Interface\AddOns\Hekili\Hekili.lua:223
 UpdateDisplayVisibility = <function> defined @Interface\AddOns\Hekili\UI.lua:1601
 IsEnabled = <function> defined @Interface\AddOns\SellJunk\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Interface\AddOns\Hekili\State.lua:5492
 CreateCustomDisplay = <function> defined @Interface\AddOns\Hekili\UI.lua:1550
 ToggleHold = <function> defined @Interface\AddOns\Hekili\State.lua:5517
 SpecializationChanged = <function> defined @Interface\AddOns\Hekili\Classes.lua:4923
 UpdateUseItems = <function> defined @Interface\AddOns\Hekili\Events.lua:558
 SetSpecOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3377
 GetDefaults = <function> defined @Interface\AddOns\Hekili\Options.lua:521
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\SellJunk\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Interface\AddOns\Hekili\Core.lua:1067
 Options = <table> {
 }
 ReInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:172
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Interface\AddOns\Hekili\Classes.lua:4870
 State = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\Hekili\Core.lua:195
 RestoreDefault = <function> defined @Interface\AddOns\Hekili\Classes.lua:748
 CmdLine = <function> defined @Interface\AddOns\Hekili\Options.lua:8329
 IsDisplayActive = <function> defined @Interface\AddOns\Hekili\UI.lua:1698
 ImporterData = <table> {
 }
 ShowDiagnosticTooltip = <function> defined @Interface\AddOns\Hekili\UI.lua:2277
 Notify = <function> defined @Interface\AddOns\Hekili\Options.lua:9214
 OnInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:63
 NewModule = <function> defined @Interface\AddOns\SellJunk\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Interface\AddOns\Hekili\Utils.lua:41
 SetPackShareOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3361
 CreateButton = <function> defined @Interface\AddOns\Hekili\UI.lua:1736
 ReleaseHolds = <function> defined @Interface\AddOns\Hekili\State.lua:5549
 Deserialize = <function> defined @Interface\AddOns\ArkInventory\Externals\Ace3\AceSerializer\AceSerializer-3.0.lua:246
 SaveDebugSnapshot = <function> defined @Interface\AddOns\Hekili\Hekili.lua:292
 SetSpecPref = <function> defined @Interface\AddOns\Hekili\Options.lua:3416
 GetName = <function> defined @Interface\AddOns\SellJunk\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:7560
 GetSpec = <function> defined @Interface\AddOns\Hekili\Classes.lua:5179
 SerializeDisplay = <function> defined @Interface\AddOns\Hekili\Options.lua:8488
 name = "Hekili"
 ExpireTTDs = <function> defined @Interface\AddOns\Hekili\Targets.lua:843
 GetEncounterList = <function> defined @Interface\AddOns\Hekili\Options.lua:72
 NewSpecialization = <function> defined @Interface\AddOns\Hekili\Classes.lua:790
 Disable = <function> defined @Interface\AddOns\SellJunk\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetOption = <function> defined @Interface\AddOns\Hekili\Options.lua:7905
 auditInterval = 0
 GetNextPrediction = <function> defined @Interface\AddOns\Hekili\Core.lua:995
 currentSpec = <table> {
 }
 Print = <function> defined @Interface\AddOns\SellJunk\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 DumpFrameInfo = <function> defined @Interface\AddOns\Hekili\Core.lua:1475
 ImportSimcAPL = <function> defined @Interface\AddOns\Hekili\Options.lua:3160
 SetOption = <function> defined @I
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AceGUI30SelectablePanel, vv1.0-alpha2
  ArkInventory, v30930
  ArkInventoryRules, v20000
  ArkInventoryRulesExample, v20000
  ArkInventorySearch, v20000
  AskMrRobot, v86
  BattlePetBreedID, vr209
  DBMArchaeology, vr39
  DBMCore, v8.3.30
  DBMCountPackHotS, v1.7.8
  DBMDefaultSkin, v
  DBMInterrupts, v1.13.5
  DBMLegendaryDummy, v2.0
  DBMNightholdDBH, v
  DBMSMGEventsPack, v1.5.7
  DBMSoundEventsPack, v1.6.6
  DBMStatusBarTimers, v
  DBMVPARNOLD, v8.1.5
  DBMVPCodiak, v1.0.0
  DBMVPDemo, v11.0.0
  DBMVPEnglishfemale, v8.3.2
  DBMVPEnglishmale, v8.3.2
  DBMVPEyeofCrowKR, v0.6
  DBMVPKassiopeia, v1.1.0
  DBMVPKiwi, v@project-version@
  DBMVPUndeadVO, v6.2.3
  DBMVPUT99, v7.3.5.12
  DBMVPVEM, v11.0.0
  DBMVPYike, v20191221
  DBMVPYun, v7.3.5
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  FocusInterruptSounds, v4.0
  GreenWall, v1.11.1+classic
  Grid, v8.0.1.1
  GTFO, v4.56
  GWAudit, v1.1.0
  Hekili, vv8.3.0-09
  Identity2, v4.2.0
  Incognito, v1.4.1
  Informant, v8.2.6508 (SwimmingSeadragon)
  LoggerHead, v196
  LowHealthAlarm, vrelease_v2.1.5
  MasterPlanA, vA
  MaxCam, vv2.4.2
  MethodAltManager, vv2
  MethodDungeonTools, v3.0.9
  MythicDungeonTools, v3.1.0
  Name2Chat, v2.0.3
  Pawn, v2.3.30
  PetBattleTeams, v3.3.11
  PetTracker, v8.3.8
  PetTrackerConfig, v
  PetTrackerJournal, v
  QuestCompletist, v109.29
  QuestLookup, v1.0.0.15
  RaidAssist, v
  Rematch, v4.10.5
  SavedInstances, v8.3.4
  SellJunk, v3.0.20
  SimpleSpellsteal, v1.0
  Simulationcraft, v1.12.5
  Skada, v1.7.7
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SpellStealer, v1.85
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TargetCharms, v1.6.4 (7/18/2018)
  TomTom, vv80300-1.1.3
  Transcriptor, vv8.3.1
  WeakAuras, v2.18.1
  BlizRuntimeLib_enUS v8.3.7.80300 <none>
  (ck=738)

**Comment by Hekili** [comment]
You have the wrong version of WeakAuras installed (i.e., Classic on Retail).  Fix that and the error goes away.

Next release will also prevent it from happening.
