### ISSUE TITLE
[REC] Augmentation spams azure strike and never uses living flame

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#4020]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

Augmentation will almost never recommend living flame and will instead only recommend azure strike. Disabling azure strike will even force you to wait to do anything instead of hitting living flame

### How to Reproduce

Enter game as aug, do rotation, observe as it never recommends living flame except as the first global and will only recommend azure strike

### Snapshot (Link)

https://pastebin.com/BcXcs0sq

**Comment by Hekili** [comment]
It looks like you do not have the Pupil of Alexstrasza talent; the current priority does not use Living Flame in multi-target unless Pupil of Alexstrasza is talented.  (This appears to be consistent with the Icy-Veins guide, as well.)

I'm going to make it so Living Flame can be used in multi-target when Leaping Flames is active, also.
