### ISSUE TITLE
[REC] Elemental Shaman priority doesn't use ascendance and stormkeeper 

### ISSUE THREAD

**Issue by warpunish** [Hekili/hekili#4021]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

Elemental shaman priority never shows ascendance or stormkeeper it the queue even if talent is learned and selected.

### How to Reproduce

1. Enter the game
2. Select talents ![image](https://github.com/user-attachments/assets/2a9f96b1-4a22-45db-9b77-dd21a9dc8761)
3. Start your rotation
4. They won't pop up in the queue

### Snapshot (Link)

https://pastebin.com/5tmHu3XU

**Comment by Hekili** [comment]
You don't appear to have Ascendance talented; I checked and I'm able to detect Ascendance on my character.

**Comment by syrifgit** [comment]
`build: v11.0.2-1.0.21`

**Comment by Hekili** [comment]
It looks like (even with Ascendance talented), Flame Shock's spell ID has changed and Ascendance was gated behind spending Lava Bursts which was gated behind applying Flame Shock.  Next release will include the fix.

![image](https://github.com/user-attachments/assets/b6cd267c-dbc3-4382-9c80-ed693f1436e2)
