### ISSUE TITLE
[BUG] Blood -> Bonestorm leads to Client freeze/crash

### ISSUE THREAD

**Issue by Razacki** [Hekili/hekili#4023]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After pressing Bonestorm the game is freezing/crashing

### How to Reproduce

1. Blood DK
2. Press Bonestorm after having enough Stacks of Boneshield Charges
3. Freeze/Crash

### Player Information (Link)

https://pastebin.com/KZE9QnS4

### Error Messages (Link)

https://pastebin.com/DKypf386

### Contact Information

razack

**Comment by Hekili** [comment]
Oops.  Fixed for next release.
