### ISSUE TITLE
[REC] Ice Strike Passive recommended, Active not recommended 

### ISSUE THREAD

**Issue by apaxgelfling** [Hekili/hekili#4024]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

Ice strike passive is being recommended during rotation when selected, but the active talent is never being recommended when selected. I'm attaching my paused snapshot, but I'm unsure if it's actually giving the information you need. Ice strike not listed in the snapshot. The snapshot was taken with the Passive Talent Selected.

### How to Reproduce

1. Spec into Passive Ice Strike and perform rotation as recommended
2. Spec into Active Ice Strike and perform rotation as recommended 

### Snapshot (Link)

https://pastebin.com/aqzCHNS8

**Comment by syrifgit** [comment]
1) that's not a correct snapshot 

2) I believe this is already fixed for next release

**Comment by apaxgelfling** [comment]
For my own knowledge, does the snapshot need to be pressed at the start before performing the rotation, and then the link gathered after the issue is seen?

**Comment by syrifgit** [comment]
You do it when "what I see is wrong", but you didn't press `Ctrl-A` to select it all before copying. Your snapshot is only one line when it should be hundreds.

**Comment by apaxgelfling** [comment]
That's my issue then, i pressed the snapshot bind when i saw the issue, and stopped there.

**Comment by syrifgit** [comment]
That's the right way to to it, you just didn't copy it all.

**Comment by apaxgelfling** [comment]
Should I edit and reupload? or are you closing this because it'd been addressed already?

**Comment by syrifgit** [comment]
It's already been fixed for the next update
