### ISSUE TITLE
[BUG] Lua error 11.0.5 causing screen freeze

### ISSUE THREAD

**Issue by khelge** [Hekili/hekili#4026]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Whole screen freezes for 10-15 seconds every time this error happens, not sure if only hekili is the problem but i get the same LUA each time

### How to Reproduce

Blood DK, sanlayn (dont think matters), i do the recommended rotation on the dornagol tank training dummy. After doing some heartstrikes and deathstrikes and marrowrends the bug happens the second i hit the "Bonestorm" ability. As soon as I click it, the screen freezes for 10-15 sec. Happens every single time its the first time i do it after a reload/login. After the first hang i can use the ability fine. But logging out/reloading and trying again on the dummy, the same thing happens as soon as I get to the bonestorm hekili recommendation (and i press it). 

### Player Information (Link)

Does not generate hekili error, just lua

### Error Messages (Link)

https://pastebin.com/VS7x1jKQ

### Additional Information

The only lua error im getting when it freezes is hekili. I have tried to turn off every other addon and only use hekili and it still causes the 10 seconds freeze (down from 15sec)

### Contact Information

khelge discord

**Comment by syrifgit** [comment]
This is already fixed for next release.

**Comment by khelge** [comment]
ah sorry, not on github often so I only checked open issues, forgot to check closed
