### ISSUE TITLE
[REC] Shaman bug with new talents. Does not show Flame shock in rotation

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#4027]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

I use a set of talents like this. CcQAYp+JUk5Lea12OyacsLNThMzMgZgZmZYmZmHALzMbbjZAAAAAAAAAAAAAAAAAAAAAAAAAAAAsBbwCMjNN2GQmJYDAz2kZwswwMjxMzsNsMzMNLsMwMDAwMzA 
I tried in AOE and in ST nowhere Flame shock +opener again did not show accendace and Doom Winds as shown in raid bots. sims attached. 
https://www.raidbots.com/simbot/report/o2MDWtW941WvLgkevvnUiE 
https://www.raidbots.com/simbot/report/iws2ui6cbEQkzxNx6g482W

### How to Reproduce

Follow the recommendations of the addon.

### Snapshot (Link)

https://pastebin.com/Gax4LSuf

**Comment by Hekili** [comment]
Good catch.  Fixed for 1.0.0a.

**Comment by geraint425** [comment]
![image](https://github.com/user-attachments/assets/9fab5d77-47f7-48ae-b141-95d94ff6488f)
https://pastebin.com/XLTdLMwf
I replaced the files with your changes, but the Doom winds still don't show up. Took another snapshot. To show that the 3rd on the list is accendace and should be doom winds as on the screenshot.

**Comment by Hekili** [comment]
Thanks; there were some missing APL entries in the single-target list.
