### ISSUE TITLE
[REC] Keeps recommending Vampiric touch when dot is applied without unfurling darkness

### ISSUE THREAD

**Issue by shadowsliver** [Hekili/hekili#4028]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

Archon priest without unfurling darkness talented, hekili recommends shadow crash and only recommends Vampiric Touch henceforth

### How to Reproduce

1. Make sure Unfurling darkness isn't talented
2. Apply vampiric touch and shadow word pain on target dummy
3. addon proceeds to recommend Vampiric embrace ad infinitum

### Snapshot (Link)

https://pastebin.com/SqWPs3F9

**Comment by syrifgit** [comment]
Looks to me like your pack is edited, try resetting it to default.

https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#rotation--performance

```
        12.  vampiric_touch ( default - 1 )
        The action (vampiric_touch) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry has no criteria to test.
        Action chosen:  vampiric_touch at 0.00!
        Exiting default with recommendation of NO ACTION at +10.00s.
```

**Comment by shadowsliver** [comment]
That was the issue, I must have edited it while looking through the configuration; apologies.
