### ISSUE TITLE
[REC] Ele sham recommending to wait 5-8 seconds for lava burst to come off CD before casting anything else

### ISSUE THREAD

**Issue by larnold0192** [Hekili/hekili#4029]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

Ele sham is recommending me to wait for the full 5-8 seconds without casting anything whilst lava burst comes off cooldown whilst I am in ascendance form

### How to Reproduce

Enter game as ele sham, proceed to follow recommendations up until ascendance form, eventually Hekili will recommend a few casts of lava burst. At this point after the first or second cast, the issue will appear

### Snapshot (Link)

https://pastebin.com/2MuzR1gA

### Contact Information

559859506482380800

**Comment by larnold0192** [comment]
Discord ID posted in ticket

**Comment by Hekili** [comment]
This should be resolved in the next release (Chain Lightning was blocked by Ascendance due to expecting the old Ascendance behavior).
