### ISSUE TITLE
Latest Update Breaks Hekili

### ISSUE THREAD

**Issue by niczak** [Hekili/hekili#403]
**Describe the Bug/Issue**
Upon loading the game (since the update for Tuesday 8/11/2020) I get a ton of LUA errors one of which just continues to increment the count of occurances until I reload the UI (at which point it starts again) or disable the addon.  I have tried the version that is currently on Twitch as well as 8.3.7-01-beta1 and the same issue occurs.

**To Reproduce**
- Login with the addon enabled

**Expected behavior**
No LUA errors.

**Screenshots**
[Screenshots of error(s) available here.](https://imgur.com/a/MoeEoVb)

**Comment by Hekili** [comment]
Install the right version of WeakAuras.

**Comment by niczak** [comment]
I apologize for the post, for some reason Twitch (I really hate that client) replaced my installed version of WA when I did an update with the version for Classic.

Thanks for the quick response!

**Comment by Hekili** [comment]
No worries.  I'm putting protection against this issue in the next release.
