### ISSUE TITLE
[ELE SHAM] Ancestral Swiftness remains as a CD after clicking. Won't dissapear after selecting.

### ISSUE THREAD

**Issue by zartoons1271** [Hekili/hekili#4030]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

After updating to the latest version, I noticed most suggestions are working now, however, I did notice that when Ancestral Swiftness is suggested, after clicking, it remains as a CD.

**Comment by syrifgit** [comment]
Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by zartoons1271** [comment]
The recommendation is correct, it just won't disappear once you select it...

https://pastebin.com/wTrFT0UX

**Comment by Hekili** [comment]
Fixed for next release.
