### ISSUE TITLE
[BUG] Ele Shaman Recommends Lava Burst when on CD

### ISSUE THREAD

**Issue by RenSai93** [Hekili/hekili#4031]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Lava Bust during ascendance is being recommended when on CD. 

### How to Reproduce

Cast Ascendance
Use all charges of lava burst
Will still tell you to do lava burst

### Player Information (Link)

https://pastebin.com/pfBZac9q

### Error Messages (Link)

n/a

**Comment by tcarlsen86** [comment]
adding to this https://pastebin.com/81prxsR3

it seems like it still thinks ascendance functions as before the patch

**Comment by Hekili** [comment]
Fixed for next release.
