### ISSUE TITLE
[REC] AOE Ele Shaman recommends LvB a LOT

### ISSUE THREAD

**Issue by tcarlsen86** [Hekili/hekili#4032]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

AoE without Primordial Wave should really never recommend Lava Burst as per rotations posted by HawkCorrigan, but the aoe rotation (specially during Ascendance) spams LvB a LOT instead of chain lightning when it should

### How to Reproduce

just play normally in aoe

### Snapshot (Link)

https://pastebin.com/NsV3fTmW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/888FRi3i2SEu5jCR494acP

**Comment by Hekili** [comment]
Fixed for next release.
