### ISSUE TITLE
Outlaw finisher recommended on low combo points

### ISSUE THREAD

**Issue by Fehh1** [Hekili/hekili#4034]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

Outlaw finisher recommended on low combo points both in stealth and outside.

### How to Reproduce

Log onto outlaw hit dummy quickly you will see its recommending finishers at low combo points over builders.

### Snapshot (Link)

https://pastebin.com/yriVkEHz

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/1xqZj8cqmD5uF5hyBb4R86

### Contact Information

fehhi

**Comment by Gyudon47** [comment]
I think this problem has to do with supercharger. Hekili wont suggest finishing on low combo if you play HO

**Comment by syrifgit** [comment]
```
entry's criteria PASSES: variable.finish_condition[true] & talent.crackshot.enabled[true] & ( ! buff.shadowmeld.up[false] | stealthed.rogue[true] )
```

Will look at it later

**Comment by Hekili** [comment]
This looks to be resolved in a pending priority update.
