### ISSUE TITLE
Doom Winds is never recommended for single target in "Single Target Storm Totemic" Enhancement spec

### ISSUE THREAD

**Issue by Squidlybeard** [Hekili/hekili#4035]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

There are multiple issues, and I've created a snapshot for each one. First, with recommended single target totemic storm talents, doom winds is never recommended for single target. Second, Ascendance is not recommended, UNLESS the target has the flame shock dot effect applied. Third, Voltaic Blaze is never recommended. 

I'm tacking on one more that can be easily seen from the first snapshot, so sorry if this is frustrating. Sundering should be basically the highest priority cast with this build, and it seems to be lower priority than Stormstrike, as well as casting lightning bolt.

All three snapshots are named, and they are linked in the snapshot box, each separated by a semicolon.

Same talents for each issue.

### How to Reproduce

1. Be an enhancement shaman
2. Use these talents: CcQAYp+JUk5Lea12OyacsLNThMzAMzYsNzMzglZGbz2MAAAAAAAAAA2gFYBmxmGbDIzEsBgZZyMwyiZmZGGzMLDLzMTgxyYmBAYmZA
3. Follow recommended ability uses.

### Snapshot (Link)

https://pastebin.com/Ym4vgfjw; https://pastebin.com/h7fXxiZU; https://pastebin.com/0CNsqptb

### Raidbots Sim Report (Link)

(https://www.raidbots.com/simbot/report/a2kCt8F9yNEorHCxVmxVAd)

### Contact Information

squidly9235

**Comment by Hekili** [comment]
This is already addressed in next release.
