### ISSUE TITLE
Lightning bolt is not being recommended sometimes when at high or max maelstrom.

### ISSUE THREAD

**Issue by Squidlybeard** [Hekili/hekili#4037]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

I can't reliably recreate this one, but the linked snapshot should work. Only sometimes, Stormstrike is recommended over lightning bolt when at 8+ maelstrom.

### How to Reproduce

1. Be Enhancement Shaman
2. Use these talents: CcQAYp+JUk5Lea12OyacsLNThMzAMzYsNzMzglZGbz2MAAAAAAAAAA2gFYBmxmGbDIzEsBgZZyMwyiZmZGGzMLDLzMTgxyYmBAYmZA
3. Follow recommendations until at 8+ maelstrom
4. It sometimes recommends Stormstrike instead of Lightning Bolt

### Snapshot (Link)

https://pastebin.com/HLq3QqhB

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/a2kCt8F9yNEorHCxVmxVAd

### Contact Information

squidly9235

**Comment by Hekili** [comment]
It does.

![image](https://github.com/user-attachments/assets/79e52797-2c05-4775-af0c-653b6d734c4a)

![image](https://github.com/user-attachments/assets/8d66fa1f-d392-4bfc-8d38-a8ffb9bc7a36)

![image](https://github.com/user-attachments/assets/0b2680a0-0091-4e9c-9ee6-ef2287e6f0db)

This matches your sims behavior based on your talents.

**Comment by Squidlybeard** [comment]
Sorry, I'm not sure how to read this. Are you saying that it's correct to use stormstrike instead of lightning bolt here, based on whatever priority list was made, or are you saying lightning bolt WAS recommended, I just didn't use it?

I'm testing this build out in the most recent release of Hekili, and it still seems to be acting this way.
