### ISSUE TITLE
Demo lock sugesting shadowbolt at max soulshards/ call dreadstalkers image remains even after using

### ISSUE THREAD

**Issue by Zagora69** [Hekili/hekili#4038]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

when entering combat the rotation works semi well until right before call dreadstalkers. its still overecasting shadowbolt while already at max soulshards and when using call dreadstalkers the addon freezzes, the rotation consistently still asking for call dreadstalkers even though it is on cd so we must manually play the rotation for about 10 seconds before it comes back.

### How to Reproduce

enter the game as a demo lock
start rotation
shadow bolt over cast while at full soulshards followed by a complete freeze of the addon recommendation after using call dreadstalkers for about 10 seconds .

### Snapshot (Link)

https://pastebin.com/6Y1CnCZ9

**Comment by syrifgit** [comment]
Lua error somewhere, I probably tried doing math on a boolean again.

Will check later.

**Comment by Dyelawn57** [comment]
Commenting to confirm multiple reports of the same issue and for tracking. I appreciate the hard work o7

**Comment by syrifgit** [comment]
It's been figured out and being worked on.

**Comment by Hekili** [comment]
This will be resolved in the next release.
