### ISSUE TITLE
Frost DK simc misspell leads to not use soul reaper

### ISSUE THREAD

**Issue by element221** [Hekili/hekili#4039]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

line 87 and 88 missing the 'a' letter 'actions'
![{B8F32B98-32E2-4244-9422-6DA66CADE9F2}](https://github.com/user-attachments/assets/806acc9e-217c-4a0e-a89b-d8bff608190f)

### How to Reproduce

try frost dk, will never recoment soul reaper

### Snapshot (Link)

dont have one

**Comment by Hekili** [comment]
Thanks, will be fixed in next release.
