### ISSUE TITLE
Weak Auras 2 Scan Event

### ISSUE THREAD

**Issue by keivamp** [Hekili/hekili#404]
When Turning on Weal Auras 2 with the Version: v8.3.0-12 of Hekili a scan event error stack happens. When I turn off line 1436 in the Hekili core it all works fine or if I turn off Weak Auras. As soon as weak auras loads the error happens. I am pasting the bug sack report in as well as posting images of the Bugsack report and the line I turned off in code.

2311x Hekili\Core.lua:1436: attempt to call field 'ScanEvents' (a nil value)
[string "@Hekili\Core.lua"]:1436: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:825: in function <Hekili\UI.lua:689>

Locals:
self = <table> {
 GetTTD = <function> defined @Hekili\Targets.lua:654
 DeserializeStyle = <function> defined @Hekili\Options.lua:8591
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili\Options.lua:3463
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili\Targets.lua:639
 After = <function> defined @Hekili\Utils.lua:268
 NewSpellInfo = true
 Run = <function> defined @Hekili\Hekili.lua:223
 UpdateDisplayVisibility = <function> defined @Hekili\UI.lua:1601
 IsEnabled = <function> defined @CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili\State.lua:5493
 CreateCustomDisplay = <function> defined @Hekili\UI.lua:1550
 ToggleHold = <function> defined @Hekili\State.lua:5518
 Class = <table> {
 }
 UpdateUseItems = <function> defined @Hekili\Events.lua:558
 SetSpecOption = <function> defined @Hekili\Options.lua:3377
 GetDefaults = <function> defined @Hekili\Options.lua:521
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Hekili\Core.lua:1076
 Options = <table> {
 }
 ReInitialize = <function> defined @Hekili\Core.lua:172
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Hekili\Classes.lua:4870
 State = <table> {
 }
 OnEnable = <function> defined @Hekili\Core.lua:195
 RestoreDefault = <function> defined @Hekili\Classes.lua:748
 CmdLine = <function> defined @Hekili\Options.lua:8329
 IsDisplayActive = <function> defined @Hekili\UI.lua:1698
 ImporterData = <table> {
 }
 ShowDiagnosticTooltip = <function> defined @Hekili\UI.lua:2277
 Notify = <function> defined @Hekili\Options.lua:9214
 OnInitialize = <function> defined @Hekili\Core.lua:63
 NewModule = <function> defined @CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Hekili\Utils.lua:41
 SetPackShareOption = <function> defined @Hekili\Options.lua:3361
 CreateButton = <function> defined @Hekili\UI.lua:1736
 ReleaseHolds = <function> defined @Hekili\State.lua:5550
 Deserialize = <function> defined @BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 SaveDebugSnapshot = <function> defined @Hekili\Hekili.lua:292
 SetSpecPref = <function> defined @Hekili\Options.lua:3416
 GetName = <function> defined @CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetOptions = <function> defined @Hekili\Options.lua:7560
 GetSpec = <function> defined @Hekili\Classes.lua:5179
 SerializeDisplay = <function> defined @Hekili\Options.lua:8488
 name = "Hekili"
 ExpireTTDs = <function> defined @Hekili\Targets.lua:844
 GetEncounterList = <function> defined @Hekili\Options.lua:72
 NewSpecialization = <function> defined @Hekili\Classes.lua:790
 Disable = <function> defined @CanIMogIt\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetOption = <function> defined @Hekili\Options.lua:7905
 auditInterval = 5.533000
 GetNextPrediction = <function> defined @Hekili\Core.lua:1004
 currentSpec = <table> {
 }
 Print = <function> defined @CanIMogIt\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 DumpFrameInfo = <function> defined @Hekili\Core.lua:1486
 ImportSimcAPL = <function> defined @Hekili\Options.lua:3160
 SetOption = <function> defined @Hekili\Options.lua:8032
 mt_default_totem = <

![Hekili_WA_Bug](https://user-images.githubusercontent.com/6789771/90061765-392da600-dcac-11ea-94a0-3542023bdf9b.jpg)
![Hekili_WA_Bug_Weak auras on](https://user-images.githubusercontent.com/6789771/90061793-45b1fe80-dcac-11ea-9cd2-7c7a8c2b438d.jpg)

**Comment by Hekili** [comment]
You have WeakAuras for Classic installed on Retail.  Check your chatbox.

I'll be babyproofing this in the future, but you'll be fine if you just install the correct WeakAuras now.

**Comment by keivamp** [comment]
I am sorry, that was the problem, weird because I don't use Weak Auras in classic and I just updated the retail version before I posted, I had to remove that one and do a fresh install on the Weak Auras and it worked perfect, sorry about that.

**Comment by Hekili** [comment]
No problem.  Twitch client is having issues providing the right versions of addons.  You provided the error messages in good faith, so I appreciate that.
