### ISSUE TITLE
Demonology suggesting HoG and other spells without enough Shards

### ISSUE THREAD

**Issue by mbrierley1** [Hekili/hekili#4040]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

Demonology suggesting HoG and other spells without enough Shards instead bolts to build more shards

### How to Reproduce

AOE dummies in game.  Get low on shards.... 

### Snapshot (Link)

Not possible

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/tEY5aRaJ4cuiKG12dNyLoV

### Contact Information

yank4986 - Discord

**Comment by Hekili** [comment]
Snapshots are required (and possible).  But Demo already has fixes slated for next release.
