### ISSUE TITLE
[REC] Void Blast and Mind Blast do not share an internal CD - Voidweaver Shadow Priest

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#4042]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

Void Blast and Mind Blast do not seem to correctly put eachother on cooldown (cant get a snapshot to show MB not starting VB cd, only VB not starting MB cd), in this snapshot Mind Blast is being recommended when it wouldnt be available. 

https://pastebin.com/snXNNTSK This one is the end of entropic rift, so it will start to cast void blast and as its casting ER will fall off so it will turn back into MB and be "usable" except that vblast shares a cd with MB.

### How to Reproduce

Play voidweaver
Observe

### Snapshot (Link)

https://pastebin.com/snXNNTSK

**Comment by dubudevs** [comment]
https://pastebin.com/LPbijXjT This is probably a better snapshot. VB/MB has a 7.7s cooldown so if its cast in 1.28s it wont be ready in 5.12s

**Comment by syrifgit** [comment]
![image](https://github.com/user-attachments/assets/32a8fb2d-4cff-45a1-8302-8440314013c5)
?

**Comment by dubudevs** [comment]
Wtf I completely forgot I already mentioned it, I swapped to this tab and thought I just forgot to click post... my brain... send help...
