### ISSUE TITLE
[REC] BA now working but Dire Beast appears to be missing from rotation for BM

### ISSUE THREAD

**Issue by ElizabethvGorkom** [Hekili/hekili#4043]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Beast Mastery

### Describe the Issue

Black arrow is now working in the rotation but it appears that Dire Beast is now missing from the rotation.  was in yesterday now since latest updates it is not showing in the rotation.

### How to Reproduce

1. Enter Game as BM.
2. Use below talent calc:
C0PAjWdaYGhrXhCioy+K0kCnAastMwAmgZhtQGLAAAAAAYAAAAAAAmx2MGzMGMzYGzYmhZMzMzMZGGzMzMGzMmhxYmZwyMwMMb
3. Target Dummy 
4. DB should be one of the first in initial rotation and on cooldown.

 

### Snapshot (Link)

https://pastebin.com/fCW3764f

### Contact Information

Eliserasilva

**Comment by Hekili** [comment]
Thanks, this will be fixed in the next release.

**Comment by Hekili** [comment]
Fixed in 1.0.2.
