### ISSUE TITLE
[REC] Devastation - Recommending wrong order of Empowered Spells and Shattering Star

### ISSUE THREAD

**Issue by Noodleboy0** [Hekili/hekili#4044]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Devastation

### Describe the Issue

The Devastation opener priority recommendation is off. It recommends Eternity Surge, Shattering Star, Tip the Scales, Fire Breath. During the opener according to the sim behavior, it should be Deep Breath, Dragonrage, Fire Breath, Shattering Star, Eternity Surge, then Distintegrates. It also recommends Tip the Scales during the first round of Empowered spells when that is also not the sim behavior.

### How to Reproduce

Single target talents: CsbBV7//nP39x/JJympTqouKSAAAAAAAAAAAAmZmBzsZGMgBjZaGzMZ2GbjZmZMjZWmBMjZ2GzMLzMDMwYwCsMGN2GQmJAbYA

1. Enter Combat with Living Flame 
2. Cast Deep Breath, hit mob
3. Cancel Deep Breath 
4. See recommendations

### Snapshot (Link)

https://pastebin.com/VUhEi2QX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/4ZjcgMdFRHd5fxaWRsaLss

### Additional Information

In the conditions for "8. [Call Action list] fb" The condition "talent.mass_disintegrate.enabled" is shown false, when the talent is enabled. That could be part of the issue?

### Contact Information

Discord: spujetti

**Comment by Hekili** [comment]
Your Mass Disintegrate talent wasn't detected due to a typo/error on my part.  Fixed for next release.
