### ISSUE TITLE
Sunder not prioritized highly enough for ENhancement's  Totemic ST setup

### ISSUE THREAD

**Issue by Squidlybeard** [Hekili/hekili#4047]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

From what I understand, Sunder is basically cast on cooldown with these talents. The recommendations show Sunder being below most other options.

### How to Reproduce

1. Be Enhancement Shaman
2. Use these talents: CcQAYp+JUk5Lea12OyacsLNThMzAMzYsNzMzglZGbz2MAAAAAAAAAA2gFYBmxmGbDIzEsBgZZyMwyiZmZGGzMLDLzMTgxyYmBAYmZA
3. Start opener until Sunder should be recommended
4. See that Sunder is not recommended

### Snapshot (Link)

https://pastebin.com/8ZtiZSLc

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/4P6acE8a4srGeRH3HP5N7h

### Contact Information

squidly9235

**Comment by Hekili** [comment]
This looks consistent with your sim:

![Screenshot_20241024-162130.png](https://github.com/user-attachments/assets/3a5993a2-d890-4650-bd09-c4e198b548c0)

**Comment by Hekili** [comment]
I've added the "prototype" Totemic priority to the addon as of 1.0.3/1.0.4.
