### ISSUE TITLE
Outlaw Rogue variable.rtb_reroll returns "nil "instead of true/false

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#4048]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

Outlaw Rogue variable.rtb_reroll returns "nil "instead of true/false.

I guess, it is due to  `rtb_buffs_will_lose[4.00] <= buff.loaded_dice.up[false]` returning invalid value

### How to Reproduce

Just use roll the bones and make snapshot

### Snapshot (Link)

https://pastebin.com/tnf91YFb

### Contact Information

IIeTpoc#3818 discord ID

**Comment by Gyudon47** [comment]
Hekili have been recommending to roll off 5 buffs that would have been wiped. Not sure if this would fix it

**Comment by Hekili** [comment]
You should update the latest release first.

**Comment by syrifgit** [comment]
@Hekili This line was not changed with the newest release, it is still an issue. see: https://github.com/Hekili/hekili/issues/4067
