### ISSUE TITLE
 Massive LUA with patch 8.7.3

### ISSUE THREAD

**Issue by zanalia** [Hekili/hekili#405]
I even shut off all addons in this list with this bug and it didnt fix the issue i am using the latest version the addon is unusable atm

1797x Hekili\Core.lua:1436: attempt to call field 'ScanEvents' (a nil value)
[string "@Hekili\Core.lua"]:1436: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:825: in function <Hekili\UI.lua:689>

Locals:
self = <table> {
 GetTTD = <function> defined @Hekili\Targets.lua:654
 DeserializeStyle = <function> defined @Hekili\Options.lua:8591
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili\Options.lua:3463
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili\Targets.lua:639
 After = <function> defined @Hekili\Utils.lua:268
 NewSpellInfo = true
 Run = <function> defined @Hekili\Hekili.lua:223
 UpdateDisplayVisibility = <function> defined @Hekili\UI.lua:1601
 IsEnabled = <function> defined @AstralKeys\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili\State.lua:5493
 CreateCustomDisplay = <function> defined @Hekili\UI.lua:1550
 ToggleHold = <function> defined @Hekili\State.lua:5518
 SpecializationChanged = <function> defined @Hekili\Classes.lua:4923
 UpdateUseItems = <function> defined @Hekili\Events.lua:558
 SetSpecOption = <function> defined @Hekili\Options.lua:3377
 GetDefaults = <function> defined @Hekili\Options.lua:521
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @AstralKeys\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 GetDisplayByName = <function> defined @Hekili\Core.lua:1076
 Options = <table> {

**Comment by Hekili** [comment]
There is no 8.7.3.

You have the wrong version of WeakAuras installed.

If you update Hekili, the error will stop but you should also install the right version of WeakAuras.

It's Twitch's fault.
