### ISSUE TITLE
[FEATURE] Always screenshot when manually paused/snapshotting

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#4050]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

![image](https://github.com/user-attachments/assets/eda58835-a6ec-44d1-b22c-5027e117e8af)

Having a once per login limit makes some sense for automatic snapshots, but when manually triggering a snapshot via pause or snapshot it should override this and always screenshot. Or just always screenshot.

**Comment by syrifgit** [comment]
As a workaround for now, you can do what I do during testing and comment out this line in `Hekili.Lua`, like 385

![image](https://github.com/user-attachments/assets/66071b6f-6122-4c39-b5a4-5e53ac05b5ec)

**Comment by syrifgit** [comment]
Adding this to my project list

**Comment by Hekili** [comment]
Fixed for 1.0.7
