### ISSUE TITLE
[REC] MM Hunter - For AoE, Black Arrow does not require trick shots (multi-shot cast)

### ISSUE THREAD

**Issue by RussellAnas** [Hekili/hekili#4057]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Marksmanship

### Describe the Issue

For my Hunter in marksman spec and dark ranger talent tree, If I am doing AoE dps, the addon does not recommend multi shot prior to Black Arrow for trick shots. Trick shots is required for max aoe dps in dark ranger spec

### How to Reproduce

1. Enter game as MM hunter
2. Go to target dummies in dornogoal (cleave ones)
3. Start aoe rotation
4. Dark arrow gets suggested without trick shots

### Snapshot (Link)

https://pastebin.com/w2iBvuyn

**Comment by syrifgit** [comment]
This is not what the sims do currently. If/when that changes, the addon will too.
