### ISSUE TITLE
[REC] Asass slow recommendations

### ISSUE THREAD

**Issue by Stoufs** [Hekili/hekili#4058]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Assassination recommendations are slow in comparison to others

### How to Reproduce

Any combat presence.

### Snapshot (Link)

na

**Comment by syrifgit** [comment]
Sin rogue has a massive apl with lots of calculations, so that is expected.

That being said, please provide some snapshots in combat.
