### ISSUE TITLE
minimum and maximum targets slider for boss encounters

### ISSUE THREAD

**Issue by mspykerez** [Hekili/hekili#406]
Hi! On 'Abilities' and 'Gear and Trinkets' tabs can you add 2 additional sliders, one for minimum and one for maximum targets selections, but this ones will only apply to boss encounters. Basically I want certain abilities/gear to only show up on thrash when there is a certain minimum targets detected but I also want that said abilities/gear to show up on Boss encounters with a different set of minimum and maximum targets detected.

Example:
- set minimum targets to 3 on thrash making it only recommend a item usage on that many targets
... and at the same time set minimum targets to 0 on boss encounters making it always recommend said item usage on boss encounters only.

**Comment by Hekili** [comment]
I probably won't address this issue in the form that you've described.

At the point where you're looking to complete this level of customization, you are probably ready to start editing priority lists directly to implement your changes.

If I were to implement a new solution for this, I would probably convert the existing features into "rulesets" that load under specific circumstances.  It would be a big project with big debugging/troubleshooting impacts, and is not something currently under development.
