### ISSUE TITLE
Feral Recommendation issue

### ISSUE THREAD

**Issue by whynotdead** [Hekili/hekili#4060]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Feral

### Describe the Issue

Some logical error with conditions like cooldown.???.ready and cooldown.???.remains and it's acting with reverse logic. Trying to modify rotation for myself and here is string:

( buff.apex_predators_craving.up & ! ( variable.need_bt & active_bt_triggers = 2 ) ) | ( ( dot.primal_wrath.up | dot.rip.up ) & ( energy.deficit < 81 | cooldown.tigers_fury.remains < 2 | ! cooldown.tigers_fury.ready ) & ( buff.ravage.up & combo_points = 5 ) )

It should send bite with apex up and not needing trigger bt or with rip dot up and energy starved no more than 81 or tiger's fury ready/ready in 2 sec with ravage buff up and 5 cp. However, with cooldown.tigers_fury.ready it thinks that's on cd, while with ! it determines it's not on cd. Is that suppose to be like that? I think all conditions in cooldown section acts the same

### How to Reproduce

1. Enter game as feral
2. Proceed to recommendations

### Snapshot (Link)

https://pastebin.com/1AYkWmdu

### Additional Information

Latest recommendation confirms that cooldown.???.ready have reverse logic

### Contact Information

whynotdead7

**Comment by Hekili** [comment]
`! cooldown.tigers_fury.ready` means *not* ready.

**Comment by whynotdead** [comment]
Ye, my tiger's fury is off cd. but it acts otherwise. So conditions passes as with ! cooldown.tigers_fury.ready but not cooldown.tigers_fury.ready, that's what i meant

**Comment by whynotdead** [comment]
Attached snaphot is with String below

( buff.apex_predators_craving.up & ! ( variable.need_bt & active_bt_triggers = 2 ) ) | ( ( dot.primal_wrath.up | dot.rip.up ) & ( energy.deficit < 81 | cooldown.tigers_fury.remains < 2 | ! cooldown.tigers_fury.ready ) & ( buff.ravage.up & combo_points = 5 ) )

**Comment by whynotdead** [comment]
Total energy is 120, i had 31 which is more than 81 deficit, no apex proc, but ravage was up, so only condition that trigger it to pass is ! cooldown.tigers_fury.ready when it was actually ready

**Comment by whynotdead** [comment]
Also https://pastebin.com/Rrj5LfSi with cooldown.tigers_fury.remains < 2 removed but ! cooldown.tigers_fury.ready persist  to double confirm it. I have tiger's fury ready. No apex proc, energy deficit is > 81

**Comment by Hekili** [comment]
>  - this entry's criteria PASSES: ( buff.apex_predators_craving.up[false] & ! ( variable.need_bt[false] & active_bt_triggers[1.00] = 2 ) ) | ( ( dot.primal_wrath.up[true] | dot.rip.up[true] ) & ( energy.deficit[89.00] < 81 | cooldown.tigers_fury.remains[30.00] < 2 | ! cooldown.tigers_fury.ready[false] ) & ( buff.ravage.up[true] & combo_points.current[5.00] = 5 ) )

> A: ~~( buff.apex_predators_craving.up[false] & ! ( variable.need_bt[false] & active_bt_triggers[1.00] = 2 ) )~~
> or
> B: ( ( `dot.primal_wrath.up[true] | dot.rip.up[true]` ) 
> and
> C: ( ~~energy.deficit[89.00] < 81~~ or ~~cooldown.tigers_fury.remains[30.00] < 2~~ or `! cooldown.tigers_fury.ready[false]` )
> and
> D: ( `buff.ravage.up[true] & combo_points.current[5.00] = 5` ) )

To pass, either A alone or B and C and D together (or all four) are required to pass.  A is false, so we look at B/C/D, all of which are met.  For B, Rip is active.  For C, Tiger's Fury is NOT ready (`! false` is `true`).  For D, Ravage is up and you have 5 CP.

**Comment by whynotdead** [comment]
But my TF IS ready all the time

**Comment by whynotdead** [comment]
Okay, i see, most likely TF which was put to cooldowns to trigger and when it's off acts like my TF isn't ready at all times? Like it bypasses it

**Comment by Hekili** [comment]
Yeah, it is kept on full CD so the addon can recommend the other things you are allowing it to recommend.

![image](https://github.com/user-attachments/assets/ea203687-2818-4d03-abc6-70cff029280f)

**Comment by whynotdead** [comment]
Ah alright, should be working like i wanted then to send ravage buffed bites in prio of refreshing rip if it still persist and i have enough energy to quickly rebuild rip/primal wrath, thank you! Was cooked a bit not knowing turned off cooldown acts like on cd to let recommendations going
