### ISSUE TITLE
[BUG] Druid's Sunfire requires Moonkin Form, which hasn't been the case since Dragonflight.

### ISSUE THREAD

**Issue by Exentrick** [Hekili/hekili#4061]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The druid's sunfire ability requires moonkin form, which locks it out being possible to implement into the rotation for any spec besides balance now that moonkin is baseline for them, despite it being a class talent that any spec can take.

Syrif said it can be fixed by removing the form condition from the following in the lua.

Sunfire = {
        id = 93402,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        school = "nature",

        spend = 0.12,
        spendType = "mana",

        talent = "sunfire",
        startsCombat = false,
        form = "moonkin_form",

        handler = function ()
            applyDebuff( "target", "sunfire" )
            if talent.improved_sunfire.enabled then active_dot.sunfire = active_enemies end
        end,
    },

### How to Reproduce

1) Change spec to anything but balance
2) Add a sunfire line to the top of your action list and talent it.
3) See that it isn't being recommended despite all the conditions (or lack thereof) being met.

### Player Information (Link)

https://pastebin.com/TVWhRcJj

### Error Messages (Link)

https://pastebin.com/cePnkUxS

### Additional Information

The error messages is just gonna tell you my personalblacklist is bugged. This is unrelated to the hekili addon.

### Contact Information

Exentrick

**Comment by Hekili** [comment]
Fixed for next release.
