### ISSUE TITLE
Hekili is showing a spell in the rotation that doesn't exist?  "Integrated Primal Fire"

### ISSUE THREAD

**Issue by BobBa3** [Hekili/hekili#4063]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hekili is showing a spell in the rotation that doesn't exist?  "Integrated Primal Fire"

### How to Reproduce

Fire Specialization for Mage

### Player Information (Link)

https://pastebin.com/U5Cum6ek

### Error Messages (Link)

https://pastebin.com/U5Cum6ek

**Comment by Hekili** [comment]
```
gear: archaic_charm_of_presence = 1
    ...
    integrated_primal_fire = 1
```

(It's your trinket.)
