### ISSUE TITLE
sub rogue not recommending cd usage for a long time

### ISSUE THREAD

**Issue by thundertubee** [Hekili/hekili#4064]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

for the aoe rotation it recommends shurikens into eviscerate over and over for around 15-20 seconds until finally recommending the burst cds. something is wrong and it started when 11.0.5 came out

### How to Reproduce

happens any time i test in aoe

### Snapshot (Link)

https://pastebin.com/xzJTU8T2

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pV8UTQEVobsS3dkkEou9Eb

### Contact Information

"thundertube" in the discord

**Comment by syrifgit** [comment]
Looks like you're using action targeting mode? You have no target.

This setting stops the addon from being able to see your target.

![image](https://github.com/user-attachments/assets/69958bda-4284-4c88-9473-69debba3d3b9)

**Comment by thundertubee** [comment]
action targeting is not on

**Comment by thundertubee** [comment]
https://pastebin.com/Kkn1YbPb 
![WoWScrnShot_102524_155004](https://github.com/user-attachments/assets/7d569488-09c5-4b9f-ac4b-6d78fae99004)

**Comment by syrifgit** [comment]
Okay, not sure why you didn't have a target the first time, but it's fine now.

Issue is just that the Sun Rogue Pack needs to be updated, which should be in the next addon update. Keep your eyes open for it on curseforge.
