### ISSUE TITLE
[REC] Assasination Garrote persistent multiplier

### ISSUE THREAD

**Issue by chyla95** [Hekili/hekili#4065]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Hey,

Given the following APL:
`actions.apl+=/mutilate,if=dot.garrote.pmultiplier>1`
`actions+=/call_action_list,name=apl`

I would expect `mutilate` to only be recommended if there is:
- ticking `garrote` on the target
- `garrote` was improved when casted ("Improved Garrote" talent)

Instead, I get the following result:
- when my 1st `garrote` is "improved", the addon suggests me to use `mutilate` (as expected), but the `pmultiplier` state doesn't change - doesn't matter if `garrote` wears down or if I use another, "not improved" `garrote`, the addons stucks in the state of `pmultiplier` being set to `1.5`.
- when my 1st `garrote` is "not improved", no action is being recommended (as expected), but as before, the addon stucks in the state of `pmultiplier` being set to `1`.

This can be reset with `/reload` command, but obviously after using `garrote` it stucks again.

### How to Reproduce

Import the following APL:

`actions.apl+=/mutilate,if=dot.garrote.pmultiplier>1`
`actions+=/call_action_list,name=apl`

Follow the description from "Describe the Issue" section.

### Snapshot (Link)

Not needed

**Comment by Hekili** [comment]
Ok, I definitely need snapshots to make sure I'm tracking correctly, taken at multiple steps.  Can you break it down as follows?

Applied Garrote from Stealth with Improved Garrote talented:  <link snapshot>
* Expect dot.garrote.pmultiplier to equal 1.5

Reapplied Garrote after Improved Garrote expires with Improved Garrote talented:  <link snapshot>
* Expect dot.garrote.pmultiplier to equal 1

What are we expecting Mutilate to do to your Garrote snapshot?  Is there a new talent/mechanic that I'm not tracking?

**Comment by chyla95** [comment]
Sadly, I wont be home for the next week to make a proper snapshot. 

Yes, you have described the expected `pmultiplier` state transitions correctly. The only problem is once the addon calculates the state once, it freezes in this state.

The APL provided by me is only an example and does not represent any specific part of the rotation - you are not missing any talent/mechanic. I have provided it only to make verification of the bug easier for the dev team. 

So, what I would expect it to behave is:
- when I use `garrote` from `stealth`, I expect the addon to suggest me to use `mutilate` (because `pmultiplier` should be `1.5`)
- then, when `garrote` expires from the target (or when I change a target to a different one) I expect the addon to suggest me nothing (because the garote is not ticking)
- then, when I use `garrote` (not from stealth/vanish) the addon should suggest me nothing (because `pmultiplier` should be `1`)
- then, when I use `garrote` casted directly after using `vanish`, I expect the addon to suggest me to use `mutilate` (because `pmultiplier` should be `1.5`)

**Comment by Hekili** [comment]
I *think* I found the issue -- cached debuff pmultipliers were not in the list of values to reset when the addon resets.
