### ISSUE TITLE
Rolling the bones not being recommended properly 

### ISSUE THREAD

**Issue by Gyudon47** [Hekili/hekili#4067]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

Just one example, I have both broadside and true bearing active. RTB should not be recommended here especially since loaded dice is also not active as well.

### How to Reproduce

Press RTB and snapshot

### Snapshot (Link)

https://pastebin.com/RJZGvrU8

**Comment by syrifgit** [comment]
Looks like an issue with this statement in the variable

`rtb_buffs.will_lose<=buff.loaded_dice.up`

I see you already opened this: https://github.com/Hekili/hekili/issues/4048

It was not fixed by updating. Will look at it.

**Comment by Hekili** [comment]
The line doesn't need to be changed; it's potentially a translation/interpreter issue.

**Comment by syrifgit** [comment]
`((rtb_buffs.will_lose<=1&buff.loaded_dice.up)|(rtb_buffs.will_lose<1&!buff.loaded_dice.up))` This is logically equivalent but doesn't do math on a boolean (my favourite thing)

The raw simc line is `(rtb_buffs.will_lose<=buff.loaded_dice.up)`

**Comment by syrifgit** [comment]
Test snapshot: Returns `false` instead of `nil`

```
        10.  variable ( default - 4 )
        rtb_reroll #2 [Outlaw:default:4]; conditions = PASS: talent.loaded_dice.enabled[true]
         - value = false: ( ( rtb_buffs_will_lose[2.00] <= 1 & buff.loaded_dice.up[false] ) | ( rtb_buffs_will_lose[2.00] < 1 & ! buff.loaded_dice.up[false] ) ) | buff.loaded_dice.up[false] & rtb_buffs_will_lose[2.00] < 3 & ( ! rtb_buffs_will_lose_buff.broadside[false] | buff.broadside.remains[0.00] < 11 ) & ( ! rtb_buffs_will_lose_buff.ruthless_precision[false] | buff.ruthless_precision.remains[0.00] < 11 ) & ( ! rtb_buffs_will_lose_buff.true_bearing[false] | buff.true_bearing.remains[0.00] < 11 )
         - variable.rtb_reroll[false] will check this script entry ( Outlaw:default:4 )
        Time spent on this action:  0.03ms
        TimeData:Outlaw-default-4:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02)
```

**Comment by syrifgit** [comment]
If you have another solution we can do that, but for now this un-bricks RTB
