### ISSUE TITLE
[REC] Blood DK Boneshield stacks / Death's Caress / Marrowrend Priority is wrong or not working correctly

### ISSUE THREAD

**Issue by HDawgBeest** [Hekili/hekili#4068]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Blood

### Describe the Issue

When I am doing my rotation and have full bone shield stacks and press bonestorm, Death's Caress becomes my first priority. Marrowrend also seems to be prioritized even when bone shield stack aren't needed and aren't about to expire.

### How to Reproduce

Run rotation as blood DK with bonestorm, tombstone, deathbringer talents.

### Snapshot (Link)

https://pastebin.com/U6qGRk4C

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/5WqeWc3q7QWmCyaA6jxXn2

### Additional Information

On line 413-418, you see it says that bone shield up returns false even though in line 229 you see bone shield is 12 stacks with 29+ seconds remaining. It appears that something is going wrong when determining if bone shield is up or not. In line 1473 it also shows that buff.bone_shield_stack = 4 even though i have 12 stacks. Not sure what the internal logic is that's causing it but marrowrend and death's caress are being recommended MUCH more than they need to be. Also, dot.bonestorm.ticking seems to be not working as well

### Contact Information

#HarrisonL

**Comment by syrifgit** [comment]
Added solution to my next PR. The addon had bone_shield coded as maximum 10 stacks, so when it was at 12 stacks it didn't like that. It now (read: on next update, if approved) properly accounts for reinforced bones talent adding 2 additional max stacks.
