### ISSUE TITLE
[REC] Retribution Paladin - Rotation after 11.0.5 sometimes does not show Hammer Of Wrath

### ISSUE THREAD

**Issue by MacieQA** [Hekili/hekili#4069]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

I sometimes notice that the queue for new spells is active with a countdown but the Hammer Of Wrath is available. Please update Retri rotation for Templar since its been a month with no updates and latest changes show "Ret HoL?" in comments which is no longer the case.

### How to Reproduce

1. Go to a dummy
2. Nuke dummy untill there is a queue for next spell
3. Check if the Hammer Of Wrath is available

Observed result: The Hammer Of Wrath is available but the Hekili does not show to use it
Expected Restult: When Hammer Of Wrath is available and other higher priority spells are not available show it as the next ability to use.

### Snapshot (Link)

https://ibb.co/K5dym39

### Additional Information

The screenshot shows 3 sec but sometimes its 4-5 seconds.

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Dranni21312** [comment]
I went to test this and I can reproduce this behavior as well. HoW is off CD and is not suggested as a recommendation.

Here's my snapshot data: https://pastebin.com/BmkmFVQK

**Comment by syrifgit** [comment]
Looks like an issue with the usable function, will test later.

```
        usable = function () return target.health_pct < 20 or ( talent.avenging_wrath.enabled and ( buff.avenging_wrath.up or buff.crusade.up ) ) or buff.final_verdict.up or buff.blessing_of_anshe.up or buff.hammer_of_wrath_hallow.up or buff.negative_energy_token_proc.up, "requires buff/talent or target under 20% health" end,
```

With the rework to the talent tree, you can't actually have the avenging wrath talent and crusade buff up at the same time, it's not possible.

**Comment by Hekili** [comment]
Fix inc.
