### ISSUE TITLE
Call feature for Hekili

### ISSUE THREAD

**Issue by nyteghost** [Hekili/hekili#407]
Was wanting to call Hekili info into Plater so that the buttons show up on the Plater Nameplate. What .lua would i be calling or dofile to achieve this?

**Comment by Hekili** [comment]
If you're doing anything in Plater, the only thing I can provide is the `Hekili_GetRecommendedAbility()` function.

`Hekili_GetRecommendedAbility( "Primary", 1 )` returns the recommended ability in the first icon of the Primary display.

![image](https://user-images.githubusercontent.com/9438134/94347560-57a0f400-0003-11eb-884a-c5d0824fced7.png)

Spell 257284 is Hunter's Mark.
