### ISSUE TITLE
Priority List for WW doesnt have major CD included. 

### ISSUE THREAD

**Issue by Monk1414** [Hekili/hekili#4072]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Windwalker

### Describe the Issue

For my windwalker monk, the priority list has the wrong opener. Also does not include invoke xuen, strike of the windlord, storm earth and fire, or whirling dragon punch in the rotation at all. 
<img width="861" alt="Screenshot 2024-10-25 at 10 20 36" src="https://github.com/user-attachments/assets/54dd7aed-740c-4007-b4c7-2b69e0530e0d">

### How to Reproduce

Enter game as windwalker, see priority list

### Snapshot (Link)

https://pastebin.com/PN2G99LM

### Contact Information

weezy_raw_03@yahoo.com

**Comment by syrifgit** [comment]
That snapshot is not correct, you need to press ctrl-A before copying to get all of it.

**Comment by Hekili** [comment]
Closing for missing snapshot.
