### ISSUE TITLE
[REC] Outlaw incorrect use/suggestion of RtB

### ISSUE THREAD

**Issue by Zwolfychu** [Hekili/hekili#4073]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Outlaw

### Describe the Issue

On outlaw, it seems Hekili recommends Roll the Bones at any point it is off of cooldown, regardless of the specific or pure number of buffs we currently have. This makes it impossible to ever fish enough to use KiR at all. Its interaction with KiR seems bad too

### How to Reproduce

1.) Enter the game as outlaw rogue
2.) Use any KiR build 
3.) Follow the rotation as normal. Fishing for Count the Odds procs to KiR with 4+ buffs.
4.) Watch what happens when Roll the Bones comes off of CD regardless of the buffs you currently posses.a

### Snapshot (Link)

https://pastebin.com/JrQxLnwV

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iQPQJtKxsEpFmePTJKGwrc

### Additional Information

In the snapshot included, this was after pull. I Adrenaline rushed for guaranteed 2 buff. While fishing for Count the Odds procs for a 3rd+4th, The second roll the bones came off of CD it recommended it. It does this very often, even rolling off 3 and 4 buffs if KiR isn't currently active. 

### Contact Information

zwolfychu

**Comment by syrifgit** [comment]
This is already fixed for the next release.
