### ISSUE TITLE
[REC] Indefinite regrowth casts recommended for balance druid

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#4075]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

After casting a single precombat regrowth to proc the DR from the hero tree the recommendations are replaced with all regrowths.

### How to Reproduce

Play m+ talents
Press regrowth once

### Snapshot (Link)

https://pastebin.com/a2mr1aQu

**Comment by syrifgit** [comment]
Fixed with https://github.com/Hekili/hekili/pull/4079
