### ISSUE TITLE
[REC] Balance: Wrath recs (for Lunar Eclipse) before FoN, Incarnation in AOE

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#4076]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

The addon tries to manually enter an eclipse before pressing incarn which doesnt make sense because incarn triggers both eclipses.

### How to Reproduce

Play m+ talents and see first recommendations in combat after dots are 2x wrath or starfire to proc an eclipse followed by FoN>incarn. 

### Snapshot (Link)

https://pastebin.com/kvpKpS5L

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pkKapiHZSp93e3Z3LPcMoc

**Comment by Hekili** [comment]
TBH, I'm not sure off the top of my head why the sim *isn't* casting those Wrath entries.

> 29.  variable ( default - 18 )
> enter_lunar `#1` [Balance:default:18]; conditions = PASS: NONE
> - value = true: ~~talent.lunar_calling.enabled[false]~~ | `spell_targets.starfire[5.00] > 2 - ( talent.umbral_intensity.rank[1.00] + talent.soul_of_the_forest.enabled[true] > 1 )`

This should be `true` for the sim as well, unless the sim initially places its 5 targets spaced more than 10 yards apart, in which case, `spell_targets.starfire` could be 1 in SimC but 5 in-game.

> 39.  wrath ( aoe - 7 )
> The action (wrath) is usable at (0.00 + 0.00).
> List ( aoe ) called from ( Balance:default:21 ) would PASS at 0.00.
        `spell_targets.any[5.00] > 1`
> - this entry's criteria PASSES: `variable.enter_lunar[true]` & ( `! variable.eclipse[false] | variable.eclipse_remains[0.00] < cast_time[1.39]` )

**Comment by Hekili** [comment]
If you update `default - 18`'s value to the following:
`( talent.incarnation.enabled & cooldown.incarnation.remains > 3 * gcd.max | cooldown.celestial_alignment.remains > 3 * gcd.max ) & ( talent.lunar_calling.enabled | spell_targets.starfire > 2 - ( talent.umbral_intensity.rank + talent.soul_of_the_forest.enabled > 1 ) )`

...does that behave more like you'd expect?

**Comment by Hekili** [comment]
It looks like SimC has an update (which I've just implemented) that prevents those Wrath/Starfire casts when Incarnation is coming off CD (or `cd_condition` is `true`).  I've incorporated the same change into the AOE action list.  This will be resolved for next release.

**Comment by dubudevs** [comment]
If you enter combat by using the precombat 2x wrath casts (which starts a lunar eclipse, not sure if this is actually correct but thats a separate issue) then this issue doesnt happen, but if you enter combat any other way then it recommends entering solar eclipse with 2x starfire in ST (correct, just not before incarn) before incarn (wrong). 

https://pastebin.com/aC7tjUhn

**Comment by syrifgit** [comment]
> If you enter combat by using the precombat 2x wrath casts (which starts a lunar eclipse, not sure if this is actually correct but thats a separate issue) then this issue doesnt happen, but if you enter combat any other way then it recommends entering solar eclipse with 2x starfire in ST (correct, just not before incarn) before incarn (wrong).
> 
> https://pastebin.com/aC7tjUhn

let's hold off until I finish updating the spec please, like I mentioned to you last night on discord.
