### ISSUE TITLE
[REC] Pressing Moonfire is redundant before you cast Force of Nature with keeper of the grove hero tree

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#4077]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

Force of Nature treants cast Moonfire on nearby enemies (Treants of the Moon). Manually dotting enemies with moonfire is skipped if you plan to use treants to apply the dot. Sims/guides specifically recommend not manually applying the dot on pull as trees will do it for you, unless you dont have trees obviously.

### How to Reproduce

Play KotG hero tree and see recommendations. 

### Snapshot (Link)

https://pastebin.com/n0AdFTA9 

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/pkKapiHZSp93e3Z3LPcMoc

**Comment by syrifgit** [comment]
I am going to work on a Boomkin overhaul on this branch: https://github.com/syrifgit/syrif-hekili/tree/syrif-fixes-2

**Comment by syrifgit** [comment]
This is addressed in https://github.com/Hekili/hekili/pull/4079
