### ISSUE TITLE
[REC] Triggering eclipse often recommends more than 2 casts until you start the first cast then it snaps to 2 - balance druid

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#4078]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

When triggering an eclipse with 2x casts of your builders it often recommends many more than 2 casts. Getting to the first cast and starting it then fixes the recommendations. 

Here is a snapshot immediately after it snaps back to 2x recommendations only, from 5x. https://pastebin.com/wVhi5HCC

The other snapshot shows 4x being recommended, maybe more beyond the 5 icons I display.

### How to Reproduce

Press buttons as instructed until it happens. Seems to happen when you dont have FoN or incarn coming up.

### Snapshot (Link)

https://pastebin.com/iME66j5W

**Comment by syrifgit** [comment]
I am going to work on a Boomkin overhaul on this branch: https://github.com/syrifgit/syrif-hekili/tree/syrif-fixes-2

**Comment by Hekili** [comment]
I added some quickfixes that we can review vs. Syrif's changes, but seems to control for this issue.
