### ISSUE TITLE
UH DK rotation not recommending apocalypse

### ISSUE THREAD

**Issue by nugletking** [Hekili/hekili#408]
The addon no longer recommends apocalypse in the UH DK rotation. This seems to have only appeared this week, starting on Tuesday. I tried bringing in an older version of the addon in from my back up (when i know it was working correctly) and it still would not recommend using apocalypse. I worry that maybe it was something blizzard changed on their end?

https://pastebin.com/SvpKLLNW

On a completely unrelated note, I know that the addon makes a DPS recommendation error with reapplying virulent plague. It should recommend to reapply one global after the disease falls off to make use of the extra chance at the eruption from from the final tick. See this article in the "Unexpected eruptions" section for an explanation: https://www.wowhead.com/unholy-death-knight-advanced-rotation-guide

**Comment by Hekili** [comment]
You've disabled the Apocalypse ability in your settings.

For your unrelated note, you would need to show sims that demonstrate a DPS gain vs. the existing SimulationCraft priority.  There are tons of guides that are technically true, but don't actually provide a tangible benefit when tested.  Submit a ticket for that issue if/when you can also attach sims.  Thanks!

**Comment by Hekili** [comment]
(Re-enabling Apocalypse is _probably_ as simple as going to /hekili > Toggles and checking Show Cooldowns; Apocalypse is considered one of your big DPS cooldowns.)

**Comment by nugletking** [comment]
<img width="747" alt="Screen Shot 2020-08-19 at 11 41 57 AM" src="https://user-images.githubusercontent.com/69919730/90676529-025a1180-e211-11ea-88b2-68f35838d91e.png">

i already checked that. apoc is not disabled.

**Comment by Hekili** [comment]
From your screenshot, it requires the **cooldowns** toggle.

From your snapshot:
![image](https://user-images.githubusercontent.com/9438134/90676837-8cfb3a80-e22a-11ea-9ac3-9ffe31309894.png)

The cooldowns toggle is disabled.

**Comment by nugletking** [comment]
sorry for the trouble! must have fat fingered that toggle button somehow. thanks for the fast response and thanks for such a great addon!

**Comment by Hekili** [comment]
Glad it helps!  And again, for the priority recommendation -- if you get sims that demonstrate a DPS benefit, send them my way and I'll look into making edits.  Take care!
