### ISSUE TITLE
[BUG] Addon fails to make recommendation, Assassin 

### ISSUE THREAD

**Issue by rheuzzy** [Hekili/hekili#4080]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Addon disappears during rotation and performs an automatic snapshot. Consistent.

### How to Reproduce

Talents:
CMQAA0tw2gAD7pPTLoW5IGZDeMjZmZmxM8ADAAAAAAzyglZAAAAAAottZmhZmBzMzysNzMjBGmZmxMbWGzAsYWGYALBLDTghFA

1. Target dummy
2. Cooldowns on, small cooldowns on

### Player Information (Link)

https://pastebin.com/LFQJK4GH

### Error Messages (Link)

There are no bugs recorded by Bugsack and BugGrabber

**Comment by syrifgit** [comment]
Going to hold off on this because there are assassin rogue updates coming. If it still happens after the next addon update, report again on the new version.
