### ISSUE TITLE
Unholy DK Defile Keybind

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#4081]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

The Unholy DK Defile does not show a keybind. It will show for DND when Defile is untalented. 

I have the override on all 4 abilities I assume would interact with it and it will not show either. Death's Due, Both DND options, and Defile. In the snapshot it shows Defile and Death's due as the correct binds but DND is empty.

### How to Reproduce

Normal rotation untill DND shows. 

### Snapshot (Link)

https://pastebin.com/57XvGhur

**Comment by bjth** [comment]
If you override the keybind Death and Decay in the Abilities Options, it'll appear.

![image](https://github.com/user-attachments/assets/f78a4574-f555-4589-bfd4-504a2e5a0913)

**Comment by Bingo176** [comment]
Yah I was on the frost panel still seems like an underlying issue of the abilities correct?

**Comment by Hekili** [comment]
Fixed for 1.0.4 -- your "Defile" still thought it was "Death and Decay" due to a talent issue.  I'll post a beta1 of 1.0.4 since I literally *just* posted 1.0.3.
