### ISSUE TITLE
[REC] Lava Lash prioritised too highly in AoE when Flameshock already spread

### ISSUE THREAD

**Issue by Nazacra** [Hekili/hekili#4086]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

I expect that in an AoE situation for a Stormbringer Storm Enhancement build Lava Last would not be recommended in AoE unless:

1. Flameshock is active and needs to be spread/refreshed (up to 6 targets)
2. There are no other available actions

This matches my expectation from both https://www.icy-veins.com/wow/enhancement-shaman-pve-dps-rotation-cooldowns-abilities?area=area_b and https://www.wowhead.com/guide/classes/shaman/enhancement/rotation-cooldowns-pve-dps#sb-aoe-rotations-elementalist

![image](https://github.com/user-attachments/assets/df125a69-fd4a-486d-9136-b3730a19c5ba)
![image](https://github.com/user-attachments/assets/0979e9c3-acb5-4963-ad9c-0903d4d67de0)

I expect the issue is with this part of the priority:
https://github.com/Hekili/hekili/blob/a9e0c3e67e3b16b1a424079af4a3a894ede64db5/TheWarWithin/Priorities/ShamanEnhancement.simc#L120
The problem being that is higher than many other abilities such as Ice Strike / Sundering / Crash Lightning / etc, and it doesn't have any conditional other than "Has Molten Assault talent && Flame shock is ticking". This means that a lot of those other abilities will basically _never_ be recommended due to Lava Lash having a short cooldown and Flameshock being up the majority of the time.

Interestingly the earlier check for Lava Lash appears to be more what I would expect:
https://github.com/Hekili/hekili/blob/a9e0c3e67e3b16b1a424079af4a3a894ede64db5/TheWarWithin/Priorities/ShamanEnhancement.simc#L109

So it might be that the solution is to just flat out remove line 120? (i.e. `actions.aoe+=/lava_lash,if=talent.molten_assault.enabled&dot.flame_shock.ticking`) as I don't see why that is part of the rotation based on guides.

### How to Reproduce

1. Enter game as an Enh Shaman with an Elementalist build
2. Perform opener on AoE Target dummies until after CDs / etc expire
3. See that in non-opener/cd rotation Lava Lash is being recommended over other abilities when the other abilities are available

### Snapshot (Link)

https://pastebin.com/VH9DJ0GS

**Comment by Hekili** [comment]
As far as I can tell from sims, this is intentional pending an official update of the priority in SimulationCraft.  When SimC updates, I will.
