### ISSUE TITLE
Assa APL issues

### ISSUE THREAD

**Issue by Yuuseki** [Hekili/hekili#4087]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

In the Assa APL, `variable.single_target` is used but never set. It has been replaced by `active_enemies` previously.
Line 148:
`actions.stealthed+=/envenom,if=effective_combo_points>=variable.effective_spend_cp&buff.master_assassin_aura.up&variable.single_target&(debuff.deathstalkers_mark.up|buff.cold_blood.up)`

---
Line 31:
![image](https://github.com/user-attachments/assets/c84e44a4-ea71-4468-829a-c1a11fc93122)
small thing here, it should be
`energy.percent>=variable.upper_limit_energy`
greater than equal

### How to Reproduce

Update to v1.0.4

### Snapshot (Link)

-

**Comment by Hekili** [comment]
Fixed for next release.
