### ISSUE TITLE
[REC] Primordial wave and tempest combo

### ISSUE THREAD

**Issue by Espboe** [Hekili/hekili#4088]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

When talentet "Primordial Wave" it should be recommended first when you got a tempest proc, not after. This to spread lightning rod and nuke that AoE pack <3

### How to Reproduce

1. Enter the game as enhancement shaman 
2. Talent into stormbringer and pick up primordial wave in enhancement. 
3. Go to AoE training dummy
4. Follow the rotation until you get tempest proc and got primordial wave up. 
5. See recommendations.

### Snapshot (Link)

https://pastebin.com/f604q3RK

### Additional Information

![bilde](https://github.com/user-attachments/assets/2a5b4272-ac29-4343-8069-0db14ed99f55)

**Comment by Hekili** [comment]
edit:  I take it back.  That would be the case for T31, not TWW tier 1.

There's a higher priority Primordial Wave entry for folks still wearing Tier 31 2pc, before forking to the `aoe` action list:
`actions+=/primordial_wave,if=set_bonus.tier31_2pc`

Primordial Wave is 6th in the AOE action list in the current SimC profile.  If there is a change made, I'll incorporate it once it hits SimC.
```
actions.aoe+=/tempest,target_if=mindebuff.lightning_rod.remains,if=buff.maelstrom_weapon.stack=buff.maelstrom_weapon.max_stack|(buff.maelstrom_weapon.stack>=5&(tempest_mael_count>30|buff.awakening_storms.stack=2))
actions.aoe+=/windstrike,target_if=mindebuff.lightning_rod.remains,if=talent.thorims_invocation.enabled&buff.maelstrom_weapon.stack>0&ti_chain_lightning
actions.aoe+=/crash_lightning,if=talent.crashing_storms.enabled&((talent.unruly_winds.enabled&active_enemies>=10)|active_enemies>=15)
actions.aoe+=/lightning_bolt,target_if=mindebuff.lightning_rod.remains,if=(!talent.tempest.enabled|(tempest_mael_count<=10&buff.awakening_storms.stack<=1))&((active_dot.flame_shock=active_enemies|active_dot.flame_shock=6)&buff.primordial_wave.up&buff.maelstrom_weapon.stack=buff.maelstrom_weapon.max_stack&(!buff.splintered_elements.up|fight_remains<=12|raid_event.adds.remains<=gcd))
actions.aoe+=/lava_lash,if=talent.molten_assault.enabled&(talent.primordial_wave.enabled|talent.fire_nova.enabled)&dot.flame_shock.ticking&(active_dot.flame_shock<active_enemies)&active_dot.flame_shock<6
actions.aoe+=/primordial_wave,target_if=mindot.flame_shock.remains,if=!buff.primordial_wave.up
```
