### ISSUE TITLE
[REC] Assassination opener issue

### ISSUE THREAD

**Issue by imarkvisser** [Hekili/hekili#4090]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

The assa recommendation has 2 abilities that swap recommendation order when you enter combat.

The correct opener is: Ambush -> Garrote -> Rupture -> Fan of Knives

This is the hekili snapshot before combat: https://pastebin.com/uYiFfm6j
This is the hekili snapshot after casting Ambush, entering combat: https://pastebin.com/KuHmuNMr

Any thoughts why that recommendation swap happens?

### How to Reproduce

Observe the precombat recommendations.
Enter combat, and watch the recommendation change.

### Snapshot (Link)

https://pastebin.com/uYiFfm6j

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kkz8NZZkCKsMRWZDRi3FyD

**Comment by syrifgit** [comment]
Take a snapshot after the garrote

**Comment by imarkvisser** [comment]
Sure, here is the snapshot after garrote: https://pastebin.com/eBA8QyfM

**Comment by syrifgit** [comment]
Seems like it's incorrectly predicting the amount of combo points you'll have after garrote, will check it out.

**Comment by Hekili** [comment]
> Seems like it's incorrectly predicting the amount of combo points you'll have after garrote, will check it out.

Is it a predictable gain?  I don't see Shrouded Suffocation talented (for +2 CP from Garrote in stealth), so I'm not sure what is granting extra CP from Garrote.  If it's a crit that we can't guarantee, the addon can only react to it.

**Comment by Hekili** [comment]
I think this is as fixed as it can be for next release, but the addon can't/won't predict a bonus CP from critting because it doesn't know you're going to crit in advance (barring Cold Blood).
