### ISSUE TITLE
Assa - master_assassin_aura evaluated incorrectly

### ISSUE THREAD

**Issue by Yuuseki** [Hekili/hekili#4091]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

In SimC, `buff.master_assassin_aura.up` is only true when we are stealthed and haven't broken stealth yet. Hekili behaves differently, in the addon `master_assassin_aura` is also up **after** breaking stealth.

This is based on the answer I received in Rogue Discord:
Kojiyama — Today at 16:24
`buff.master_assassin_aura` is only up when you are stealthed and haven't broken stealth yet. In a more generic sense, you should be using `master_assassin_remains` which merges both and doesn't care. (In the case the aura is up, `master_assassin_remains` will return the duration of the stealth break buff + remaining GCD time)

Although my issue sounds similiar to https://github.com/Hekili/hekili/issues/4090, these 2 are probably unrelated.

### How to Reproduce

In Hekili v11.0.5-1.0.4, modify default Assa APL and change the line
`actions.stealthed+=/envenom,if=effective_combo_points>=variable.effective_spend_cp&buff.master_assassin_aura.up&variable.single_target&(debuff.deathstalkers_mark.up|buff.cold_blood.up)`
to
`actions.stealthed+=/envenom,if=effective_combo_points>=variable.effective_spend_cp&buff.master_assassin_aura.up&active_enemies=1&(debuff.deathstalkers_mark.up|buff.cold_blood.up)`
to fix single target detection (`variable.single_target` vs `active_enemies=1` because `variable.single_target` is never set)

Now during opener, the addon recommends Ambush -> Garrote -> Envenom instead of Ambush -> Garrote -> Rupture. In the default APL of the addon the opener is correct (although only accidentally) because `variable.single_target` is always false/nil, so that Envenom line never gets executed.

### Snapshot (Link)

Snapshot taken during opener after casting Ambush -> Garrote
https://pastebin.com/DXLFCHhG

### Additional Information

Paused screenshot to the snapshot
![image](https://github.com/user-attachments/assets/5951615c-f220-483e-b8db-2e2b2a7fc5c9)

**Comment by Hekili** [comment]
Looks good.
