### ISSUE TITLE
Missing Assassination Double Rupture Openers AOE

### ISSUE THREAD

**Issue by Romdiaz123** [Hekili/hekili#4092]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Blood

### Describe the Issue

Assassination now not recommending double Rupture in opener for AoE to spread for Scent of Blood stacks. Stays are 12/20 stacks 

### How to Reproduce

1.Enter as rogue.
2. Open rotation on AOE Target dummies 

### Snapshot (Link)

https://pastebin.com/BMuYv5bZ

**Comment by syrifgit** [comment]
Can you link a quick sim as well

**Comment by Romdiaz123** [comment]
https://www.raidbots.com/simbot/report/tucDyZ4FaiwVF7yg1huLtq
![Screenshot 2024-10-27 171903](https://github.com/user-attachments/assets/520f2d8a-30cb-49c8-b70c-8e19cbb141f0)

**Comment by syrifgit** [comment]
I have found the issue and will make a fix.

![image](https://github.com/user-attachments/assets/93d10a0e-656d-48b8-9288-ae004c740371)

**Comment by syrifgit** [comment]
Fixed in next release btw
