### ISSUE TITLE
[REC] Warrior Fury，Execute priority seems wrong

### ISSUE THREAD

**Issue by 393910898** [Hekili/hekili#4094]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Fury

### Describe the Issue

Hekili doesn't seem to recognize the target's "Marked for Execution" debuff, it always prompts me to use Execute even if the target doesn't have any "Marked for Execution"
![1111](https://github.com/user-attachments/assets/502ed853-65a0-41c1-aab9-92562d162688)

### How to Reproduce

1.using fury slayer
2.target health ≤ 20% or 35%（choose Massacre）
3.single or multi-target combat

### Snapshot (Link)

https://pastebin.com/TVXw8Jw8

**Comment by 393910898** [comment]
![2222](https://github.com/user-attachments/assets/6b46533a-f1a5-4c11-a5be-4517f5626b0f)
target doesn't have any "marked for execution" and I didn't choose "Ashen Juggernaut"

**Comment by 393910898** [comment]
And I didn't choose "Ashen Juggernaut"

**Comment by syrifgit** [comment]
Link a quicksim.

**Comment by 393910898** [comment]
https://www.raidbots.com/simbot/report/oWEa6GYx8qFPrEAMJJBY1o

**Comment by 393910898** [comment]
https://www.raidbots.com/simbot/report/4CRswDKc2Mqw5KpeYQ1QBG
5 targets

**Comment by Hekili** [comment]
There's a good chance this is a dummy-only issue because of how tracking resets on enemy death and combat exit. Will investigate.

**Comment by heungleung** [comment]
> 这很有可能只是一个虚拟问题，因为跟踪会在敌人死亡和战斗退出时重置。将进行调查。

no, this DEBUFF will not be reduced and will always show 3 layers.

**Comment by heungleung** [comment]
> 这很有可能只是一个虚拟问题，因为跟踪会在敌人死亡和战斗退出时重置。将进行调查。

PLS FIX

**Comment by Hekili** [comment]
Can you provide a snapshot where this is happening on real enemies (not target dummies)?

**Comment by Hekili** [comment]
Also: There are updates to the Fury priority in the next release.

**Comment by heungleung** [comment]
> Can you provide a snapshot where this is happening on real enemies (not target dummies)?

Yes, any target is like this. "11.0.2-1.0.20a" is correct. "11.0.5-1.0.7" still has this bug.

**Comment by Hekili** [comment]
That's not a snapshot.

**Comment by heungleung** [comment]
> That's not a snapshot.

![Uploading 1.png…]()

**Comment by heungleung** [comment]
![1](https://github.com/user-attachments/assets/b9ef94bd-0bda-4718-9d16-97161c52f690)

**Comment by heungleung** [comment]
> That's not a snapshot.

![1](https://github.com/user-attachments/assets/bc242372-d7c4-4cd8-b022-174fa77c70b1)

**Comment by heungleung** [comment]
> That's not a snapshot.
look
![1](https://github.com/user-attachments/assets/c5e4c9c9-d84b-4e84-a2ad-e0335a310c9f)

**Comment by syrifgit** [comment]
That's still not a snapshot.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by heungleung** [comment]
> That's still not a snapshot.
> 
> Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

![1](https://github.com/user-attachments/assets/00e68097-44d5-4e41-9e0f-ff9c759397b3)

**Comment by heungleung** [comment]
> That's not a snapshot.

[snapshot.txt](https://github.com/user-attachments/files/17659218/snapshot.txt)
