### ISSUE TITLE
[FEATURE] The highlight feature does not work correctly when using NDui's action bars.

### ISSUE THREAD

**Issue by huchang47** [Hekili/hekili#4096]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

[https://www.curseforge.com/wow/addons/ndui](url)
NDui, a widely popular enhanced UI, has an issue where Hekili's skill highlight isn't working correctly on the action bars within its environment.Other addons that use the NDui action bar framework are experiencing the same issue.

Solution:
Add the following code at line 321 in SpellFlashCore.lua to resolve the issue.

> NDui = LibStub:GetLibrary("LibActionButton-1.0-NDui", true),
UI = LibStub:GetLibrary("LibActionButton-1.0-UI", true),

Please add this support.

**Comment by Hekili** [comment]
This is not a complete fix; I'm guessing
