### ISSUE TITLE
Enhancement Shaman - EB wrongly recommended at top of profile

### ISSUE THREAD

**Issue by Sratarak** [Hekili/hekili#4097]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

Elemental blast is wrongly recommended at the top of the APL.
Current line in Hekili reads:
`buff.tempest.stack < buff.tempest.max_stack & buff.maelstrom_weapon.stack >= 5 & talent.elemental_spirits.enabled & feral_spirit.active >= 2 & ( ! talent.flowing_spirits.enabled & time_to_max_charges < cooldown.feral_spirit.remains_expected | feral_spirit.remains <= 2 * gcd.max )`

should read:
`actions.single+=/elemental_blast,if=buff.maelstrom_weapon.stack=buff.maelstrom_weapon.max_stack&talent.elemental_spirits.enabled&feral_spirit.active>=6&(charges_fractional>=1.8|buff.ascendance.up)`

Main issue is that it's recommending EB on 2 wolves over, and especially in the opener.  Means we're using our charges before double wolves in ascendance losing a lot of damage

### How to Reproduce

Do enhancement shaman opener.

### Snapshot (Link)

https://github.com/simulationcraft/simc/blob/thewarwithin/profiles/TWW1/TWW1_Shaman_Enhancement.simc

**Comment by Hekili** [comment]
This is addressed in the next release.
