### ISSUE TITLE
Treacherous Transmitter not recommended in AoE

### ISSUE THREAD

**Issue by Westside24ch** [Hekili/hekili#4102]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

On my Frost Death Knight, the treacherous transmitter isn't being recommended at all in AoE situations. In ST its part of the opener, right after Abom Limb, but I did about 2 mins of AoE rotation on dummies and it was never recommended.

### How to Reproduce

Log in as Frost Death Knight, play the standard mythic+ Breath of Sindragosa talents, with the transmitter and ovniax mercurial egg equipped for trinkets. From there, i suggest going to a ST dummy and testing there, and then doing the same at 3+ targets on the dummies.

### Snapshot (Link)

https://pastebin.com/TQYfNK16

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/p64c6ugx9e5jUZYqum5AZA

**Comment by Hekili** [comment]
The trinket is synced with Pillar of Frost, which shows as turned off according to your preferences. What does /hek > Abilities > Pillar of Frost show?

**Comment by Westside24ch** [comment]
I have that disabled, because I send it with Reaper's Mark generally on CD. That would explain it. I use spellflash for the most part, is there a way I could keep Pillar of Frost on my bars, but also have it not recommended while allowing the transmitter to be recommended?

**Comment by Hekili** [comment]
Not without customizing the priority, no.

I may be able to revise to accommodate though. I'll take a look tomorrow.

**Comment by Hekili** [comment]
Fixed for next release (probably).
