### ISSUE TITLE
[REC] Blood rotation should consume Reaper of Souls procs (Deathbringer)

### ISSUE THREAD

**Issue by trbaxter** [Hekili/hekili#4103]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Blood

### Describe the Issue

When using the default profile for Blood, it does not appear that Soul Reaper is recommended in the rotation after Reaper's Mark is applied to a target. 

<br/>

Here are the details of the hero talent: 

![image](https://github.com/user-attachments/assets/c8906099-dbb8-4f0f-a226-7339698405cb)

<br/>

Here's a screenshot of the recommended rotation _before_ Reaper's Mark is used:

![image](https://github.com/user-attachments/assets/7a1296c8-1b43-4021-a757-db98352f8c78)

<br/>

Notice that after Reaper's Mark is applied to the enemy, Soul Reaper is not recommended at all in the rotation:

![image](https://github.com/user-attachments/assets/fd2de1cd-091b-41ed-adeb-b054416a869a)

<br/>

I have verified that this is not user error by identifying the buff on my character after Reaper's Mark is applied to an enemy:

![image](https://github.com/user-attachments/assets/1af5e0b7-d23c-4751-80f8-c7e48c3e7019)

<br/>

I've also verified that following the recommended BDK rotation results in a DPS loss without this, as one would expect.

Following the rotation resulted in [489,871.0 DPS](https://www.warcraftlogs.com/reports/142ahXcfxBznVrYP#fight=last&type=damage-done) on a raid target dummy.

Applying Soul Reaper in the rotation per this recommendation resulted in [529,580.1 DPS](https://www.warcraftlogs.com/reports/8NrpfHxj74m9AJMR#fight=last&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%24261376853.0.0.Warlock%24true%240.0.0.Any%24false%240&type=damage-done) on the same dummy.

Therefore, I am recommending that the Deathbringer rotation for blood death knights follow this type of pattern if possible:

```mermaid
flowchart TD
    A[Reaper's Mark cast]
    B[Use Soul Reaper]
    C[Continue with rotation]
    
    A --> B --> C
```    

There may need to be a change added when Exterminate procs are used as well, as Reaper's Mark has a chance to be applied to the target whenever Exterminate is cast. In that case, we would expect the following:

```mermaid
flowchart TD
    A[Cast Exterminate]
    B{Reaper's Mark applied?}
    C((Yes))
    D((No))
    E[Cast Soul Reaper]
    F[Continue rotation]
    
    A --> B --> C --> E --> F
              B --> D --> F
```              

### How to Reproduce

1.) Log into the game as a level 80 blood death knight. 
2.) Choose the Deathbringer hero talent tree. 
3.) Choose the Reaper of Souls hero talent. 
4.) Find any target.
5.) Cast Reaper's Mark on it. 
6.) You will see Soul Reaper is not properly displayed in the rotation recogizing the hero talent's effect.

### Snapshot (Link)

https://pastebin.com/chBqLiU9

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/qdLkJr7DHRiRmf7jhScg3J

### Additional Information

Looking through the sample ability log, it looks like Raidbots is not properly taking advantage of this talent either in the sims, leading an underestimate in potential player output. 

(501,835 DPS vs 529.580.1 DPS over the same approximate 3 minute interval)

**Comment by Hekili** [comment]
The addon will be updated for this tomorrow.
