### ISSUE TITLE
Arcane sometimes repeatedly suggests Arcane Barrage in the first rec.

### ISSUE THREAD

**Issue by amackenzie** [Hekili/hekili#4104]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Arcane

### Describe the Issue

On occasion, Arcane will suggest Arcane Barrage (and other, non-arcane barrage skills to follow it), but on casting Arcane Barrage, the recommendations remain the same (eg, arcane barrage followed by the other skills). Repeatedly casting AB does not appear to clear it. Usually, casting Arcane Blast causes it to re-assess what's happening.

### How to Reproduce

Reproduction of the bug isn't very consistent and seems a bit random.

I was doing 5-mans through the random dungeon queue and it would usually happens once or twice a run.

### Snapshot (Link)

https://pastebin.com/TAcRNbiy

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/sY4hc6ceHcRXbqUcRnd5bx

### Additional Information

![WoWScrnShot_102824_204237](https://github.com/user-attachments/assets/402cc7a2-0931-43fe-a36b-898862029da6)

Attached is the screenshot of when it was happening, if that helps.

**Comment by syrifgit** [comment]
It's because you desynced your touch of the magi from your big cooldowns, known issue, no good solution yet except don't desync your cooldowns, or, put touch of magi on the cooldowns toggle and toggle it off if you aren't using it.

**Comment by Pokettz1** [comment]
I am also having this issue.
