### ISSUE TITLE
Pwave/Lighting Bolt AOE Issue

### ISSUE THREAD

**Issue by jakeparshall** [Hekili/hekili#4105]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

In AOE, tempest is being consumed by lightning bolt when Pwave is up. The priority is pwave into tempest to tempest all flameshocked mobs.

It also sends pwave before tempest in AOE with all the mobs having flame shock. Mega DPS loss.

### How to Reproduce

1. Just hit dummies in Dornagol. 
2. Standard rotation goofs that up, just sends pwave before tempest in AOE. 

### Snapshot (Link)

https://pastebin.com/U1FawrHj

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/k1V3w6s23L9gJjd3qCjfDT

### Additional Information

Let me know if you need anything else.

**Comment by Hekili** [comment]
At maxed Maelstrom Weapon stacks, Tempest is prioritized over Primordial Wave.
