### ISSUE TITLE
[FEATURE] Assassination Rogue - Track Envenom TTK stacks

### ISSUE THREAD

**Issue by djopero** [Hekili/hekili#4109]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hey, is it possible for Hekili to track Twist the Knife stacks of Envenom? It allows you to get two stacks and in the Simc APL it has this line. As guideline you want to try and clip the 2nd stack with this talent not just the overall envenom stack.

# Check to clip envenom
actions+=/variable,name=clip_envenom,value=buff.envenom.up&buff.envenom.remains.1<=1

Which is tracking the second stack of envenom with "buff.envenom.remains.1<=1" which returns nil in Hekili. If I edit the current Hekili line of "buff.envenom.remains<=1" which is just tracking overall Envenom

Maybe it's not even that line but the apl is intended to try and clip the Envenom stack as it's about to lose the second stack.

**Comment by Hekili** [comment]
`buff.envenom.remains.1<=1`

I definitely won't support that syntax directly, but I'll add a way to track overlaps and update the priority accordingly.

**Comment by djopero** [comment]
Awesome, thank you

**Comment by syrifgit** [comment]
Implemented
