### ISSUE TITLE
[REC] Not recommending wrath to enter eclipse

### ISSUE THREAD

**Issue by GoochWookie** [Hekili/hekili#4110]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

When playing as balance talents aren't being recommended to enter eclipse

### How to Reproduce

1.) Enter as balance
2.) Navigate to the Dornogal cleave training dummies
3.) Start recommended rotation with cooldowns on 

### Snapshot (Link)

https://pastebin.com/crbxZnES

### Contact Information

goochwookie

**Comment by syrifgit** [comment]
Can you also post a quicksim using the same scenario

**Comment by Hekili** [comment]
There are missing lines for Wrath/Starfire in the AOE action list.  I'll post a fix in a bit.

**Comment by Hekili** [comment]
Fixed in 1.0.6a
