### ISSUE TITLE
[REC] Ret paladin abilities not recommended correctly

### ISSUE THREAD

**Issue by Dranni21312** [Hekili/hekili#4111]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

With the latest update on 10/29, abilities are not recommended correctly. Sometimes the add-on recommends waiting for even 5+ seconds instead of recommending an available ability.

I also tried reloading the priority pack, which did not fix the issue.

Here are some sample snapshots:

https://pastebin.com/p0JqVbbW

https://pastebin.com/d7irCTzG

https://pastebin.com/2eyZZQjV

Thanks

### How to Reproduce

--

### Snapshot (Link)

https://pastebin.com/p0JqVbbW

**Comment by Hekili** [comment]
Thanks; should be resolved in 1.0.6b
