### ISSUE TITLE
[FEATURE]  Add Demonic Healthstones

### ISSUE THREAD

**Issue by Ryketz** [Hekili/hekili#4116]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

When talented for Pact of Gluttony in the Warlock tree, Hekili no longer recognizes my healthstone because the item is now called Demonic Healthstone. An option to include the Demonic Healthstones would be much appreciated.

**Comment by Hekili** [comment]
Fixed for 1.0.7
