### ISSUE TITLE
[REC] variable cooldown.ascendance.remains is always 120

### ISSUE THREAD

**Issue by holytobi** [Hekili/hekili#4126]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

The variable "cooldown.ascendance.remains" returns everytime 120 whether ascendance is on cooldown or not. This breaks on many point the rotation etc

### How to Reproduce

just open the hekili window search for an entry of "cooldown.ascendance.remains" for example in the variables in the precombat section in enhancement. 
Use ascendence check if the cool goes down ur remains on 120

### Snapshot (Link)

https://pastebin.com/NttxDzSE

**Comment by Hekili** [comment]
This is how abilities that are disabled (i.e., Ascendance is on the Cooldowns toggle, and that toggle is off) are handled so that recommendations can still function.  When Ascendance is enabled (CDs toggled on), its actual remaining cooldown will be shown.

**Comment by holytobi** [comment]
so if i show Cooldowns on the sepperate toggle, it breaks a bit the rotation or i.e. the cd of ascendance cant be read. Why its a different where the icon shows for the rotation?

**Comment by syrifgit** [comment]
Because that's just how it works, they are 2 separate displays with entirely separate sets of recommendations. You can try the "global cooldown" feature in Abilities -> Ascendance

**Comment by Hekili** [comment]
Basically, Syrif is correct.  If you put Ascendance in a separate CD display, you're saying that Ascendance can't be recommended in the Primary display.  Can't be recommended = disabled = on CD for predictive purposes.  The feature does warn that it can be an issue for different specializations.
