### ISSUE TITLE
[REC] Demonic Strength doesn't get a recommendation!

### ISSUE THREAD

**Issue by Jumimaru** [Hekili/hekili#4127]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Demonology

### Describe the Issue

When i use my rotation, Hekili doesn't recommend Demonic Strength which is a huge part of our dps.

### How to Reproduce

Spec into SH Demo and select [Demonic Strength] in the spec tree. Follow Hekili rotation for a couple of minutes. Not ones will it be recommended.

### Snapshot (Link)

https://pastebin.com/UevGVywM

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/d3uLjSUG7CiTrLFHQXcAbz

**Comment by syrifgit** [comment]
Your sim doesn't cast it either, will confirm with demo theorycrafter.

**Comment by Jumimaru** [comment]
That's because it didn't get recommended. I just followed the rotation what was given.

**Comment by syrifgit** [comment]
Yes, and I am saying it's doing exactly what the sim from raidbots is doing .. not casting it.

The button is not pressed in single target, you just use it to path to the talents below it. Not an issue, if the sims get updated the addon will too.
