### ISSUE TITLE
[REC] Summon Jade Serpent Statue is not on spell table anymore

### ISSUE THREAD

**Issue by oversoe** [Hekili/hekili#4129]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Mistweaver

### Describe the Issue

An old APL with Summon Jade Serpent Statue is now bugged.

You can add the spell from the list of spells in the APL anymore

### How to Reproduce

1. Have SJSS talented.
2. Look in Action list
3. It doesn't appear - should be next to summon ox statue
![billede](https://github.com/user-attachments/assets/42ff98e7-603b-4ab0-b679-54a339bf1aab)

### Snapshot (Link)

https://pastebin.com/2jMBfuhy

**Comment by syrifgit** [comment]
Closing to consolidate into 1 ticket
