### ISSUE TITLE
WW Monk - Queue stops working (BFA)

### ISSUE THREAD

**Issue by cdc1287** [Hekili/hekili#413]
Hello,

WW monk seems to lose some of its queued abilities during combat until I press any random ability. I started a WQ and during the combat, I had 3 automatic SnapShots within a minute.

This was happening a while ago as well but I left WW.

https://pastebin.com/00P4fNfn

https://pastebin.com/PQa0jcwA

https://pastebin.com/uXzkzjFh

Thanks,

**Comment by Hekili** [comment]
Thanks.  WW can have scenarios where chi decay leads to no viable abilities.  Since your report, I did some tweaking of the priority that may have helped resolve this.  In any case, for priorities I am only looking at Shadowlands issues going forward.
