### ISSUE TITLE
[REC] Frost DK Oblit not suggested when 2 KM procs

### ISSUE THREAD

**Issue by Juicincuh** [Hekili/hekili#4131]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

It seems frost strike is too high priority. Sometimes spamming 3x in a row when killing machine available with runes available for use. Also notice that reapers mark is used within the pillar of frost window when every guide suggests using it before to not waste killing machine procs

### How to Reproduce

1. Take wowhead main single target breathe of sindragosa build
2. Use the breath of sindragosa opener. (I just let if fall of immediately because this isn't the issue)
3. After breath of sindragosa falls off and there is a suggestion for frost strike. Wait till you get two killing machine procs.
4. A lot of the time the frost strike will not change to suggest obliterate

### Snapshot (Link)

https://pastebin.com/rwReE6z6

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/6fJzBevCQCjkaJBTeiJoGK

### Additional Information

Even with max icy talons stacks present and sometimes even with two killing machine procs available during pillar of frost hekili will recommend frost strike as first priority which is insane as this is the last ability I would want to use in this scenario. On a side note I know remorseless winter is to be used on cooldown and hekili wont recommend this ability as its coming off cooldown or off cooldown. Also would be good to consider hekili to have a wait function for resource feature when breath of sindragosa is off cooldown instead of spamming all the runic power away wasting resources while my strongest cooldown is up

### Contact Information

Discord: juicincuh

**Comment by bjth** [comment]
It's because of Dark Talons, when it changes how many IT stacks you have forces a Frost Strike, regardless if you have KM.

Working on resolving it with some APL updates soonTM.

**Comment by Hekili** [comment]
This may be addressed in the next release; if not, we would need a new snapshot due to priority updates.
