### ISSUE TITLE
Auto snapshot happening when I should just be getting a delay indicator

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#4136]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Just playing the game, I keep getting autosnap shots of things that when I should just be getting a delay indicator

### How to Reproduce

Playing my Sin rogue, doing M+, doing rotation, sometimes get out of "rotation" and snap shot happens.

### Player Information (Link)

https://pastebin.com/Wmib4Suz

### Error Messages (Link)

https://pastebin.com/Wmib4Suz

### Additional Information

Just trying to help as much as possible.

### Contact Information

Wren1740

**Comment by Hekili** [comment]
The snapshot you provided doesn't look like an auto-snapshot -- it didn't fail to make a recommendation.

Also, there are priority updates in 1.0.9 that just went out that may render this moot.  If it occurs again in 1.0.9, open a ticket with the auto-snapshot.
