### ISSUE TITLE
[REC] deactivate feral druid shred ability stops the rota

### ISSUE THREAD

**Issue by bk-81** [Hekili/hekili#4137]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Feral

### Describe the Issue

Since you have to stand behind the boss for shred and you can't always do that, I deactivated shred.
Then the rotation stops after Wild Roar and no longer shows anything.

it would be great if you could activate and deactivate shred depending on the battle via hotkey

### How to Reproduce

deactivate shred, attack any mob and follow the hekili instructions until the rota stops

### Snapshot (Link)

https://pastebin.com/yyTttcqW

### Contact Information

gumbl_43588

**Comment by bk-81** [comment]
this concerns cataclysm classic

**Comment by Hekili** [comment]
This could be addressed in a couple of ways -- one is to Claw when you can't Shred, the other is to add Claw to the priority so it gets recommended when Shred is disabled.  I generally would just hit Claw when it showed Shred when I was playing Druid.
