### ISSUE TITLE
[REC] Wrong rotation in AOE shaman

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#4138]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

![image](https://github.com/user-attachments/assets/f854722d-4954-4579-a823-c0866ed27338)
In aoe when the fight starts, the rotation incorrectly starts recommending it differently than what is recommended on the site. Even logically if you look at using Pwave in AoE and after it Ascendance is a loss of DPS. We always want to use Lava lash after Pwave to unleash Flame shock and then if we have Tempest or light bolt we use it to cast Lightning Rod on the target. And then using Ascendance + Doom Winds will give us a huge boost in DPS in AOE. Now there is no such recommendation. Tested on manikins and in M+.

### How to Reproduce

Approach the manikins and just follow the guidelines.

### Snapshot (Link)

https://pastebin.com/M7HdQWAq

**Comment by Hekili** [comment]
The sim priority is still undergoing updates; you'll still need to wait for it to stabilize.
