### ISSUE TITLE
[FEATURE] Keybind for "Enable" option ? 

### ISSUE THREAD

**Issue by KatyPurry** [Hekili/hekili#4139]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello,

I've looked everywhere in the addon, in my kebinds settings, in the Wiki, but I can't find any option to assign a key to the “Enable” option. Sometimes I don't want to see the recommendations, so I have to manually uncheck “Enable”. 

![image](https://github.com/user-attachments/assets/b63541e6-9877-4892-898e-f51653407ee9)

Is it possible to add an option to assign a keybind for the "Enable" mode ?

**Comment by syrifgit** [comment]
You can make macros with the following to turn on/off the entire addon.

`/hek enable`
`/hek disable` 

Not really sure a built-in keybind to enable/disable the addon would be popular enough to build.

**Comment by Zazou89** [comment]
Thank you for your answer, a macro is also perfect for me !

**Comment by KatyPurry** [comment]
Thank you for your answer, a macro is also perfect for me !
