### ISSUE TITLE
Guardian rotation bugs (Alpha 20/21)

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#414]
After testing guardian i found 2 bugs for Alpha 21 build.

1. After rotation started, hekili get crashed for few sec. 
2. Iron fur not in recommendation by hekili, even if defensive enabled and 100 rage capping. (Build Alpha 19) Tested in dungeon before enable guardian in hekili, but as far i see even i caped 100 rage and enter combat, hekili still not recomend IronFur. 
Maul disabled as it's worst spender for Guardian rage. 

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.pl/view/48b53df0

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.pl/view/80644c45

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

https://pastebin.pl/view/ea901e89

**Comment by Hekili** [comment]
Thanks for the report.  I have a bugfix and priority change ready for the next build.
