### ISSUE TITLE
[REC] Elemental Shaman AOE rotation recommending too many chain lightnings / not prioritizing DRE procs

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#4142]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Elemental

### Describe the Issue

Basically, hekili is heavily heavily prioritizing just spamming chain lightning in AOE scenarios despite having other things to be hitting. The entire idea behind the current elemental build in M+ is to constantly try to get out as many DRE procs as possible (Earth shock, ele blast, earthquake) and the addon is seemingly just prioritizing chain lightning over anything else. I don't know how to exactly describe what's going on, but I've done my best or what i've observed. Making the AOE rotation prioritize "fishing" for DRE procs in M+ would result in a MASSIVE net get in dps.

### How to Reproduce

1. Enter game as Elemental Shaman
2. Go to 5+ aoe dummies (or do M+)
3. Notice how it will ask you to repeatedly chain lightning despite having empower earthquakes or procs

### Snapshot (Link)

https://pastebin.com/Xi3pMgcA

**Comment by TheHambrick** [comment]
Based on my limited ele knowledge, it looks like it's somewhat normal to cast a few chain lightnings in a row. Even just simming a random top 10 ele there are a couple of 3 in a row chain lightnings, I'm not sure what (if any) modeling hekili does of overloads for maelstrom generation, so it may be possible that you don't actually end up hitting 4 CLs in a row like the snapshot would indicate, or it may be a stats thing. /shrug. 

Going into specifically look at the APL though, the entries that show up on a 5 target patchwerk sim are entry 42 in the snapshot: "hit earthquake if you [have 0 lightning rods, or are less than 30 away from cap] and [you have echoes of great sundering up or you don't have it talented]. In the first recommendation, it looks like you have 2 lightning rods out and are still 69 maelstrom away from cap, so it fails the first condition and moves on.

and then Entry 45 in the snapshot: Which (if I'm reading it right) wants you to spread lightning rod to a different target if you don't have the buff up for earthquake, and a few other conditions.

What's important (and what you may be missing) is the condition about being not far away from the cap is in a lot of places in the APL AND in the wowhead guide. The top of the ele guide even specifically states "**It is important to note that we still are not going to spend as soon as possible. Hovering at a high amount of resources allows us to easily react to certain procs like Awakening Storms or[ Rolling Thunder]."** It doesn't sound like it's intended to just dump your maelstrom and keep it at 0 all the time in search of DRE procs.


https://www.raidbots.com/simbot/report/naz2QmTa8WE9mCzQhqJfYX

**Comment by aaronlilla** [comment]
i may need to look into creating custom priorities or something then if this is the intended behavior according to the resources you're looking at, because fishing for dre procs (within reason of course) is basically the only way we can do significant damage pack-to-pack when ascendance is down. i understand what you're saying may be technically correct though. a few examples of things i've noticed is that if you were to just following the rotation, the vast majority of your overall damage in M+ will be concentrated into chain lightnings, and about half of the chain lightning's % of damage would be in earthquake damage- if you were to look at the logs of other top damage ele shaman parses for M+ it would be much higher earthquake damage than chain lightning. now, i definitely understand this could come down to a # of targets issue, however i think a pretty solid chance it comes down to having significantly more DRE procs. 

couple more random things i've noticed, just to have them written down:
- the chain lightning spam is much more egregious on 2 targets
- it will recommend using LMT and pwave even if the pack is about to die
- in the rotation que, it will say to use LMT -> totemic recall, until you actually hit LMT and then totemic recall is never recommended. totemic recall is never actually the no. 1 recommendation at any point ever for any reason, it just shows up in the que.

- if it wasn't so unfun to hit extra buttons, i could (and have) gotten much higher overall in keys in aoe if i set the addon to only single-target mode, and every time it were to recommend hitting lightning bolt i just instead hit chain lightning. the single target rotation uses earth shock and earthquake significantly more, and thus procs DRE more. as soon as DRE procs, i swap back to AOE mode and just blast as usual

**Comment by aaronlilla** [comment]
another thing to note is that when ascendance is proc'd, it applys a bunch of flame shocks, which will make huge burst windows with primordial wave (giving you more haste and whatnot, inside of the ascendance) which is a very large source of pack-to-pack damage while ascendance is down, with just the sheer amount of globals you can get out

**Comment by aaronlilla** [comment]
i guess i'll throw another thing out there is that im basically only talking about M+, and only 12+ keys. in lower keys i can see how fishing for dre procs would be worthless, but when packs live long enough, and are on average pretty large in these higher keys it may shift the priority

**Comment by TheHambrick** [comment]
> i guess i'll throw another thing out there is that im basically only talking about M+, and only 12+ keys. in lower keys i can see how fishing for dre procs would be worthless, but when packs live long enough, and are on average pretty large in these higher keys it may shift the priority

> i may need to look into creating custom priorities or something then if this is the intended behavior according to the resources you're looking at, because fishing for dre procs (within reason of course) is basically the only way we can do significant damage pack-to-pack when ascendance is down.


That would be something you'd want to take up with the ele shaman APL writers then, because it appears that the addon is doing what the guide and APL writers want it to do, or at least pretty close to it.

**Comment by aaronlilla** [comment]
yea maybe. i may need to figure out how to write custom priorities to get what im looking for here, or maybe someone out there has already done it

**Comment by TheHambrick** [comment]
> yea maybe. i may need to figure out how to write custom priorities to get what im looking for here, or maybe someone out there has already done it

You should talk to the shaman people, and they may be able to tell you why they don't do it

**Comment by Hekili** [comment]
> Making the AOE rotation prioritize "fishing" for DRE procs in M+ would result in a MASSIVE net get in dps.

Have you done any sims to verify this?  Deeply Rooted Elements isn't factored into Elemental sims at all.  

```
41.  earthquake ( aoe - 19 )
The action (earthquake) is usable at (0.00 + 0.00) with cost of 55 maelstrom (have 81).
- the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( aoe ) called from ( Elemental:default:13 ) would PASS at 0.00.
spell_targets.chain_lightning[5.00] > 1
- this entry's criteria FAILS: cooldown.primordial_wave.remains[45.00] < gcd.max[1.31] & talent.surge_of_power.enabled[true] & ( buff.echoes_of_great_sundering_es.up[true] | buff.echoes_of_great_sundering_eb.up[true] | ! talent.echoes_of_great_sundering.enabled[true] )
```

Earthquake would've been recommended here but Primordial Wave shows as on cooldown.

```
30.  primordial_wave ( aoe - 8 ) - ability disabled ( toggle cooldowns )
```

Primordial Wave wasn't recommended because CDs are toggled off (which causes the PWave CD to reflect the full PWave CD).

Earthquake also would've been recommended under these circumstances:

* You had no Lightning Rods active / Maelstrom was over 120.

```
42.  earthquake ( aoe - 20 )
The action (earthquake) is usable at (0.00 + 0.00) with cost of 55 maelstrom (have 81).
- the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( aoe ) called from ( Elemental:default:13 ) would PASS at 0.00.
spell_targets.chain_lightning[5.00] > 1
- this entry's criteria FAILS: ( lightning_rod[2.00] = 0 & talent.lightning_rod.enabled[true] | maelstrom.current[81.00] > variable.mael_cap[150.00] - 30 ) & ( buff.echoes_of_great_sundering_es.up[true] | buff.echoes_of_great_sundering_eb.up[true] | ! talent.echoes_of_great_sundering.enabled[true] )
```

* Stormkeeper was active with 6+ targets *or* Tempest was up.

```
43.  earthquake ( aoe - 21 )
The action (earthquake) is usable at (0.00 + 0.00) with cost of 55 maelstrom (have 81).
- the action is ready before the current recommendation (at +0.00 vs. +10.00).
List ( aoe ) called from ( Elemental:default:13 ) would PASS at 0.00.
spell_targets.chain_lightning[5.00] > 1
- this entry's criteria FAILS: ( buff.stormkeeper.up[false] & spell_targets.chain_lightning[5.00] >= 6 | buff.tempest.up[false] ) & talent.surge_of_power.enabled[true] & ( buff.echoes_of_great_sundering_es.up[true] | buff.echoes_of_great_sundering_eb.up[true] | ! talent.echoes_of_great_sundering.enabled[true] )
```

**Comment by aaronlilla** [comment]
@Hekili if my goal is to essentially fish for dre procs, in aoe, when ascendance is down, what kind of custom action would you recommend? or maybe atleast point me in the right direction?

**Comment by Hekili** [comment]
My interpretation of the priority is that you're pooling Maelstrom so that if you do proc Ascendance from ES/EB/EQ, you're going to have Maelstrom to spend again with the benefit of Ascendance active.

You could remove the `maelstrom.current > variable.mael_cap - 30` checks from ES/EB/EQ and see if that accomplishes what you want.  You may want to make that revision to a sim and see how it shakes out.

**Comment by scoofz** [comment]
I honestly have no idea if this is the cause of the terrible DPS I'm pulling as elemental on my shaman with hekili and I haven't looked into the rotation myself to see if I perform the same. However I noticed that it actually performs pretty well regarding numbers on dummy but really bad in dungeons for some reason... I also noticed that flame shock is barely even pressed if I follow Hekili
