### ISSUE TITLE
[BUG] Wrong icon for sub rouge talent Flagellation

### ISSUE THREAD

**Issue by Burzolog** [Hekili/hekili#4144]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

Patch 11.0.5 updated the icon for Flagellation from a red Venthyr-themed icon to a more generic icon. Hekili is still displaying the old icon.

### How to Reproduce

1. Enter the game as a Subtlety Rogue
2. Take the Flagellation talent
3. Go into combat and follow the rotation until it recommends Flagellation

### Snapshot (Link)

https://pastebin.com/0hQkd07C

**Comment by syrifgit** [comment]
Literally Unplayable! ;)

I will submit a fix soon.

![image](https://github.com/user-attachments/assets/e8437e89-6818-4c41-a003-483749a96f8c)
