### ISSUE TITLE
[REC] Option to hide chat notification not found

### ISSUE THREAD

**Issue by imanozxx** [Hekili/hekili#4146]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Arcane

### Describe the Issue

The issue I have is not specifically for arcane mages, but all classes. I would like to know  how I can hide the hekili chat notifications in my general chat. This occurs everytime i swap between display settings with my keybind toggle. I would like to hide the notification of the current set display in my chat. I have not found how or where to do it. Please help me.

### How to Reproduce

Enter Game as any class.
Press hotkey for toggle display hekili
see chat notification

![image](https://github.com/user-attachments/assets/41803ff7-439c-4d98-a900-994370228afa)

### Snapshot (Link)

Arcane; AOE - Mirror Image(0.00) build: v11.0.5-1.0.10 level: 80 (80) class: MAGE spec: arcane  talents: C4DAjd9IgsSkCmGQ8vOmZtyV7MYZmtZZGzMmZWAmZGjpxYMAAAAAAGIgZmplZbbmZmtlllZmYBAAAAAgFAWmBmZMzYGGzMzYmZmZmZMMA     accumulative_shielding = 1/1     aethervision = 1/1     alter_time = 1/1     amplification = 1/1     arcane_bombardment = 1/1     arcane_debilitation = 2/2     arcane_echo = 1/1     arcane_harmony = 1/1     arcane_missiles = 1/1     arcane_surge = 1/1     arcane_tempo = 1/1     arcane_warding = 2/2     arcing_cleave = 1/1     augury_abounds = 1/1     barrier_diffusion = 1/1     blast_wave = 1/1     charged_orb = 1/1     concentrated_power = 1/1     consortiums_bauble = 1/1     controlled_instincts = 1/1     displacement = 1/1     dragons_breath = 1/1     energized_barriers = 1/1     enlightened = 1/1     eureka = 1/1     evocation = 1/1     flow_of_time = 2/2     force_of_will = 1/1     greater_invisibility = 1/1     high_voltage = 1/1     ice_block = 1/1     illuminated_thoughts = 1/1     impetus = 1/1     improved_clearcasting = 1/1     improved_touch_of_the_magi = 1/1     incanters_flow = 1/1     magis_spark = 1/1     mass_barrier = 1/1     master_of_time = 1/1     mirror_image = 1/1     nether_precision = 1/1     orb_barrage = 1/1     overflowing_energy = 1/1     presence_of_mind = 1/1     prismatic_barrier = 1/1     quick_witted = 1/1     reactive_barrier = 1/1     remove_curse = 1/1     resonance = 1/1     ring_of_frost = 1/1     shifting_power = 1/1     shimmer = 1/1     signature_spell = 1/1     slippery_slinging = 1/1     slipstream = 1/1     spellfrost_teachings = 1/1     spellslinger = 1/1     spellsteal = 1/1     splintering_orbs = 1/1     splintering_sorcery = 1/1     splinterstorm = 1/1     temporal_velocity = 2/2     time_anomaly = 1/1     time_loop = 1/1     time_manipulation = 1/1     tome_of_antonidas = 1/1     tome_of_rhonin = 1/1     touch_of_the_magi = 1/1     volatile_detonation = 1/1     volatile_magic = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: forged_gladiators_medallion = 1     gladiators_medallion = 1  gear: algari_competitors_cloth_sash = 1     algari_competitors_cloth_treads = 1     algari_competitors_signet = 1     algari_competitors_staff = 1     forged_gladiators_insignia_of_alacrity = 1     forged_gladiators_medallion = 1     forged_gladiators_necklace = 1     forged_gladiators_silk_cap = 1     forged_warmongers_bindings = 1     forged_warmongers_cloak = 1     forged_warmongers_garb = 1     forged_warmongers_mantle = 1     forged_warmongers_pants = 1     gladiators_medallion = 1     jeweled_gauntlets_of_violet_rebirth = 1     knights_colors = 1     stylish_green_shirt = 1  legendaries: none  itemIDs: 15198, 212093, 215137, 217119, 217124, 218467, 218710, 218714, 218716, 223807, 223811, 223813, 223814, 223841, 225369, 6385  settings: aoe = 3     combatRefresh = 0.15     custom1Name = Custom 1     custom2Name = Custom 2     cycle = true     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 6     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     gcdSync = true     maxTime = 19     nameplateRange = 37     nameplates = false     noFeignedCooldown = false     package = Arcane     petbased = false     potion = tempered_potion     rangeFilter = false     regularRefresh = 0.3     throttleRefresh = true     throttleTime = true     cancel_pom = false     check_explosion_range = false  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = false      essences = true      funnel = false      interrupts = true      mode = aoe      potions = false   keybinds:      alter_time                     = Y   [04]     arcane_barrage                 = S4  [05]     arcane_blast                   = S5  [05]     arcane_explosion               = C   [01]     arcane_intellect               =     arcane_missiles                = 2   [05]     arcane_orb                     = R   [05]     arcane_surge                   = 1   [05]     blast_wave                     =     blink                          =     cone_of_cold                   = S3  [01]     counterspell                   = E   [08]     displacement                   =     dragons_breath                 = C   [01]     evocation                      = E   [01]     frost_nova                     = M4  [01]     frostbolt                      = S6  [01]     gladiators_medallion           =     greater_invisibility           = S   [08]     healthstone                    = CMwD[04]     hyper_organic_light_originator = SE  [04]     ice_block                      =     ice_cold                       =     mass_barrier                   = S2  [01], C1  [06]     mirror_image                   = S6  [01]     presence_of_mind               = SF  [01]     prismatic_barrier              = S   [01], S2  [08]     remove_curse                   = MwD [04]     ring_of_frost                  =     shifting_power                 = CR  [01]     spellsteal                     = E   [01], CG  [06]     supernova                      =     tempered_potion                =     time_warp                      = CF  [01]     touch_of_the_magi              = 3   [05]  warnings: none   targets:  Nameplates are enabled.  player_buffs:      1459 - arcane_intellect                         -   1 - 3126.93    458335 - *diamond_mechsuit                        -   1 - 3600.00    432021 - *flask_of_alchemical_chaos               -   1 - 4362.80    186401 - *sign_of_the_skirmisher                  -   1 - 3600.00    452307 - *sign_of_the_past                        -   1 - 3600.00    455020 - *wows_anniversary                        -   1 - 3600.00    462806 - *viziers_supremacy                       -   1 - 3600.00    458701 - *vantus_rune_the_bloodbound_horror       -   1 - 62225.26    321388 - *enlightened                             -   1 - 3600.00  player_debuffs:  target_buffs:  target_debuffs:  previous_spells:    1 - arcane_intellect    2 - blink    3 - arcane_intellect    4 - prismatic_barrier   New Recommendations for [ AOE ] requested at 11:42:54 ( 500989.81 ); using built-in ( Arcane ) priority. *** START OF NEW DISPLAY: AOE *** Purged 227 marked values in 0.11ms.  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: arcane_charges[ 0.00 / 4.00 ], mana[ 2760443.00 / 2760443.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Arcane - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   arcane_intellect ( precombat - 1 )         The action is not ready ( 3126.93 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.03ms         TimeData:Arcane-precombat-1:arcane_intellect:0.03:Ability Known, Enabled(0.03)                  2.   variable ( precombat - 2 )          - variable.aoe_target_count references a hardcoded variable and this entry will be ignored.         Time spent on this action:  0.04ms         TimeData:Arcane-precombat-2:variable:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02)                  3.   variable ( precombat - 3 )          - variable.aoe_target_count references a hardcoded variable and this entry will be ignored.         Time spent on this action:  0.03ms         TimeData:Arcane-precombat-3:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  4.   variable ( precombat - 4 )         opener #1 [Arcane:precombat:4]; conditions = PASS: NONE          - value = true: ( cooldown.touch_of_the_magi.remains[0.00] <= action.evocation.execution_time[0.00] ) & ( cooldown.arcane_surge.remains[0.00] <= action.evocation.execution_time[0.00] | action.arcane_surge.time_since[784.92] < 5 | cooldown.arcane_surge.remains[0.00] > 15 ) & ( cooldown.evocation.up[true] | action.evocation.time_since[789.06] < 5 | cooldown.evocation.remains[0.00] > 15 )          - variable.opener[true] will check this script entry ( Arcane:precombat:4 )         Time spent on this action:  0.03ms         TimeData:Arcane-precombat-4:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  5.   variable ( precombat - 5 )         touch_ready #1 [Arcane:precombat:5]; conditions = PASS: NONE          - value = false: variable.opener[true] & ( buff.arcane_surge.up[false] | cooldown.arcane_surge.remains[0.00] > 30 ) | ( prev_gcd.1.arcane_surge[false] & buff.arcane_charge.stack[0.00] < 4 )          - variable.touch_ready[false] will check this script entry ( Arcane:precombat:5 )         Time spent on this action:  0.03ms         TimeData:Arcane-precombat-5:variable:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  6.   variable ( precombat - 6 )         steroid_trinket_equipped #1 [Arcane:precombat:6]; conditions = PASS: NONE          - value = false: equipped.gladiators_badge[false] | equipped.signet_of_the_priory[false] | equipped.high_speakers_accretion[false] | equipped.spymasters_web[false] | equipped.treacherous_transmitter[false] | equipped.imperfect_ascendancy_serum[false] | equipped.quickwick_candlestick[false]          - variable.steroid_trinket_equipped[false] will check this script entry ( Arcane:precombat:6 )         Time spent on this action:  0.03ms         TimeData:Arcane-precombat-6:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  7.   variable ( precombat - 7 )         transmitter_double_on_use #1 [Arcane:precombat:7]; conditions = PASS: NONE          - value = false: ( equipped.gladiators_badge[false] | equipped.signet_of_the_priory[false] | equipped.high_speakers_accretion[false] | equipped.spymasters_web[false] | equipped.imperfect_ascendancy_serum[false] | equipped.quickwick_candlestick[false] ) & equipped.treacherous_transmitter[false]          - variable.transmitter_double_on_use[false] will check this script entry ( Arcane:precombat:7 )         Time spent on this action:  0.03ms         TimeData:Arcane-precombat-7:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  8.   variable ( precombat - 8 )         treacherous_transmitter_precombat_cast #1 [Arcane:precombat:8]; conditions = PASS: NONE          - value = 11: 11          - variable.treacherous_transmitter_precombat_cast[11] will check this script entry ( Arcane:precombat:8 )         Time spent on this action:  0.03ms         TimeData:Arcane-precombat-8:variable:0.03:Ability Known, Enabled(0.01):Post-TTR and Essential(0.01)                  9.   treacherous_transmitter ( precombat - 9 ) - IsUsableItem item 221023 and nil         Time spent on this action:  0.05ms         TimeData:Arcane-precombat-9:treacherous_transmitter:0.05:Ability Known, Enabled(0.05)                  10.  mirror_image ( precombat - 10 )         The action (mirror_image) is usable at (0.00 + 0.00) with cost of 50000 mana (have 2760443).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry has no criteria to test.         Action chosen:  mirror_image at 0.00!         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Arcane - precombat ].     Recommendation is mirror_image at 0.00 + 0.00.     Recommendation #1 is mirror_image at 0.00s (0.00s).     Time spent generating recommendations:  1.62ms

### Additional Information

I doubt that snapshots are relevant because this is not an issue. It is an option I am not sure it exist or not, which is why I can not put this request in the new features section,

### Contact Information

IMANO - ZX Discord ID

**Comment by Hekili** [comment]
This option doesn't exist; if the notification panel is not enabled, there would be no other feedback that you've used a toggle.  I probably won't implement this.
