### ISSUE TITLE
[BUG] Rogue showing Pick Pocket as next skill to use

### ISSUE THREAD

**Issue by LEOMODE** [Hekili/hekili#4147]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Currently, Pick Pocket is showing as next skill to use. 

### How to Reproduce

Outlaw Rogue keeps showing Pick Pocket as the next skill to use in the DPS rotation. 4
![Screenshot 2024-11-05 093053](https://github.com/user-attachments/assets/0359bc2f-2576-427b-82d4-d677a054d63d)

### Player Information (Link)

Couldn't find Issue Reporting tab on the left :(

### Error Messages (Link)

N/A

### Contact Information

Discord ID LEOMODE

**Comment by syrifgit** [comment]
Trinket most likely, first question of the [FAQ](https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#rotation--performance).

I will fix the issue reporting thing, I think the tab was renamed and I didn't update that text. Thanks.

**Comment by LEOMODE** [comment]
You are right, it's a trinket that has the same logo as pick pocket. 
![Screenshot](https://github.com/user-attachments/assets/9cf0bb9d-f7b5-4f2a-8571-5176fad237f8)

Any way to disable this trinket skill in hekili?
