### ISSUE TITLE
[FEATURE] Option to use Crimson Tempest sooner in AoE

### ISSUE THREAD

**Issue by sixsi** [Hekili/hekili#4148]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Right now AoE opener is fine, but in lower keys (10s and lower) it takes kinda long for the addon to make Crimson Tempest recommendation. For example if CT would be 3rd GCD it would do more damage to lower HP mobs which means more dps.
I can't find any way to make the addon to do what I want. So an option would be appreciated, or some advice how to do this on my own :)

**Comment by syrifgit** [comment]
option 1a) Modify your pack: https://github.com/Hekili/hekili/wiki/Customizing-A-Hekili-Priority
option 1b) Modify your pack and also move Crimson Tempest to the interrupts, defensives or CDs toggle so that you can make the choice on your own

Option 2) Just push crimson tempest

**Comment by Hekili** [comment]
I'm going to close this since it's really a recommendation ticket and doesn't have a snapshot or sims.  I *suspect* that you might get the results you want by adding conditiosn to the `call_action_list` for `core_dot` like:

`active_enemies = 1 | ! boss & ( fight_remains < 10 | raid_event.adds.remains < 10 )`
