### ISSUE TITLE
UH DK Army of the Dead/Raise Abomination Issue

### ISSUE THREAD

**Issue by Excitedguy** [Hekili/hekili#415]
If I enter pvptalent.raise_abomination.enabled as a condition for Army of the Dead and enter an instance where PVP talents are disabled (dungeons for instance), then the ability icons for primary rotation stop showing after a few seconds. Works as intended when in areas where PVP talents are enabled.

https://pastebin.com/a1hXbKAJ

**Comment by Hekili** [comment]
```47.  army_of_the_dead ( cooldowns - 2 )
The action (army_of_the_dead) is usable at (1.00 + 0.00) with cost of 3.
 - the action is ready before the current recommendation (at +0.00 vs. +2.45).
List ( cooldowns ) called from ( Unholy:default:28 ) would PASS at 0.00.
   NONE
 - this entry's criteria FAILS: pvptalent.raise_abomination.enabled[false]
```

All you've done is prevent AOTD from being used there.  What's your goal?

That's preventing Scourge Strike later on (due to checking AOTD's cooldown):

```62.  scourge_strike ( generic - 5 )
The action (scourge_strike) is usable at (3.45 + 1.05) with cost of 1.
 - the action is ready before the current recommendation (at +1.05 vs. +60.00).
List ( generic ) called from ( Unholy:default:30 ) would PASS at 1.05.
   active_enemies[1.00] = 1
 - this entry's criteria FAILS: ( ( debuff.festering_wound.up[true] & ( cooldown.apocalypse.remains[69.21] > 5 & ( ! essence.vision_of_perfection.enabled[false] | ! talent.unholy_frenzy.enabled[true] ) | essence.vision_of_perfection.enabled[false] & talent.unholy_frenzy.enabled[true] & cooldown.unholy_frenzy.remains[66.78] > 6 ) ) | debuff.festering_wound.stack[5.00] > 3 ) & ( cooldown.army_of_the_dead.remains[0.00] > 5 | death_knight.disable_aotd[false] )
```

**Comment by Excitedguy** [comment]
My goal is to only show Raise Abomination in all conditions and only show Army of the Dead during boss encounters, how do I accomplish this? Reason is because Raise Abomination is only a 1 and half minute cooldown where AOTD is 8 minutes...

**Comment by Hekili** [comment]
`boss | pvptalent.raise_abomination.enabled`

**Comment by Excitedguy** [comment]
I added that condition to AOTD and same issue unfortunately. New snapshot here: https://pastebin.com/z4GziqXQ

**Comment by Hekili** [comment]
```45.  army_of_the_dead ( cooldowns - 1 )
The action (army_of_the_dead) is usable at (1.39 + 4.79) with cost of 3.
 - the action is ready before the current recommendation (at +4.79 vs. +60.00).
List ( cooldowns ) called from ( Unholy:default:28 ) would PASS at 4.79.
   NONE
 - this entry's criteria FAILS: target.is_boss[false]
There were no recheck events to check.
Time spent on this action:  0.18ms
```

Why is that there?

**Comment by Excitedguy** [comment]
My apologies, I put that there originally to try and fix the issue myself. I may of uploaded an older snapshot, here's the most recent one with the condition you suggested I add in: https://pastebin.com/cxus7dcQ

**Comment by Hekili** [comment]
Right.  So with the latest snapshot, you still have the same core problem -- if you prevent Army of the Dead from being recommended, the conditions for Scourge Strike aren't going to be met (because it relies on AOTD going on cooldown).  

In your snapshot:
`boss[false] | pvptalent.raise_abomination.enabled[false]`

You were neither in a boss fight nor was your PvP talent enabled.

So you need to either:

1.  Revise entries that refer to cooldown.army_of_the_dead.remains to remove it or replace it.  For example...

```((cooldown.army_of_the_dead.remains>5|death_knight.disable_aotd)&(cooldown.apocalypse.remains>5&debuff.festering_wound.stack>0|debuff.festering_wound.stack>4)&(time_to_die<cooldown.death_and_decay.remains+10|time_to_die>cooldown.apocalypse.remains))```

...to...

```(cooldown.apocalypse.remains>5&debuff.festering_wound.stack>0|debuff.festering_wound.stack>4)&(time_to_die<cooldown.death_and_decay.remains+10|time_to_die>cooldown.apocalypse.remains)```

(Make sure to look at Scourge Strike, Clawing Shadows, and Festering Strike.

2.  Just use the existing toggle for cooldowns to turn AOTD on/off in these different scenarios.
