### ISSUE TITLE
[REQ] Warlock PvP Talent: Soul Swap

### ISSUE THREAD

**Issue by whorrnados** [Hekili/hekili#4150]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Affliction

### Describe the Issue

I spent a significant amount of time trying to get it to work and it seems that because soul swap is a PVP talent it doesn't work with "talent.soul_swap.enable" I'm assuming support for PVP talents needs to be added in general?

### How to Reproduce

try and check the action list, soul swap isnt there. 

### Snapshot (Link)

https://pastebin.com/XZ7T9nnC

### Contact Information

theguccikucci (discord)

**Comment by Hekili** [comment]
I'll (re)add Soul Swap but, as it is a PvP talent, it's not a top priority right now.  Thanks.

**Comment by whorrnados** [comment]
Awesome much appreciated
