### ISSUE TITLE
Warrior aggressively recommending Charge when too close.

### ISSUE THREAD

**Issue by amackenzie** [Hekili/hekili#4152]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Protection

### Describe the Issue

Charge is recommended even when within melee range (and not far enough to use charge), most noticeably on enemies with large hitboxes (screenshot attached of a delve boss, but this is very noticeable on the current event world bosses --- you have to be standing quite a bit inside the Sha of Anger's circle before it stops recommending Charge).

I have this listed for Protection since that's when I got the snapshot but I first noticed it happening on Fury.

### How to Reproduce

1. Find a boss with a larger hitbox (?), and often Charge will be recommended unless you're standing very near to the center of the boss's circle.

### Snapshot (Link)

https://pastebin.com/zUB8zz4A

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fpNUrJA2kMRabZUudae2X5

### Additional Information

Screenshot attached is of a boss where this is happening. I am currently successfully using other skills (shield slam, revenge, etc) on the boss while moving out of the boss's attack range when he burrows, but Charge is constantly recommended (even though it's tinted red due to being too close to use it).
![WoWScrnShot_110524_214338](https://github.com/user-attachments/assets/ca21d2bd-16c4-4139-a181-803a69f3dc6e)

**Comment by frogmox** [comment]
This appears to be happening again. Examples in Nerub-ar Palace on Ulgrax, Bloodbound, and Queen.
