### ISSUE TITLE
[REC] Monk MistWeaver stucks in Rushing Wind Kick while cooldown

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#4154]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Brewmaster

### Describe the Issue

Monk MistWeaver stucks in Rushing Wind Kick while cooldown

### How to Reproduce

None

### Snapshot (Link)

https://pastebin.com/8psKxYtv

**Comment by Hekili** [comment]
Fixed for next release.
