### ISSUE TITLE
[BUG] Allow Target Swaps sets to default(enabled) during login

### ISSUE THREAD

**Issue by tidehunter1** [Hekili/hekili#4156]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Spec > Targeting > "Allow Target Swaps" set to disable, then upon next login of the game it resets back to enabled.

### How to Reproduce

Spec > Targeting > "Allow Target Swaps" set to disable, then upon next login of the game it resets back to enabled.

### Player Information (Link)

no

### Error Messages (Link)

no

**Comment by Jumimaru** [comment]
I can confirm this with Demo and Destro. 

I won't get the arrow when target already got the dot on him.

**Comment by syrifgit** [comment]
References

old ticket: https://github.com/Hekili/hekili/issues/2049

How to reproduce

1) Choose 2 classes that have a spec with different default settings (nameplates or cycle is easy). Warlock and Magework, as they have opposite target swap default states, enabled for locks (Demo/Destro only), disabled for mages (all 3 specs).

(you could also just pick 2 classes/specs and modify their default values in the class file while you test)

2) Log into mage, change nameplates and target swaps to on, reload and change spec as much as you want, exit game log back in, etc. Settings will stay.

3) Log into your warlock (already prepped as Demo or Destro spec) which has different default settings

4) Relog and go back onto your mage, you'll see that mage has been reset to mage default settings.

**Comment by Hekili** [comment]
This should be resolved for next release.
