### ISSUE TITLE
hekili gave me this while  testing out unholy dk  with dummies.

### ISSUE THREAD

**Issue by comproh** [Hekili/hekili#4157]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

https://i.imgur.com/NngUC1s.jpeg

### How to Reproduce

No clue how to reproduce it. 

### Player Information (Link)

https://pastebin.com/cyBdi4vA

### Error Messages (Link)

https://pastebin.com/cyBdi4vA

**Comment by syrifgit** [comment]
It just ran out of things to recommend, that's much more likely to happen when you're showing 6 icons as the addon needs to read about ~6 seconds into the future depending on your GCD time. So any stuff like procs or random resource gains can't be predicted.

**Comment by Hekili** [comment]
There's a potential defect here with the way the priority variables are set up; I'm going to revise and it may/may not have an impact.

I will *probably* make it so the addon doesn't autosnapshot when failing to find a recommendation beyond 4 icons; I may need to come up with a visual that indicates it couldn't find anything (hourglass?).
