### ISSUE TITLE
[REC] Ret pal rotation (hammer of wrath)

### ISSUE THREAD

**Issue by zZzProstudazZz** [Hekili/hekili#4159]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

Could you please explain how I could make use hammer of wrath on my ret pal a bit often, cuz I play mostly on pvp and need it, btw atm he use blade of justice by cd, and only when everything on cd he recommend to use hammer of wrath. I have latest version of retpal.simc 

### How to Reproduce

Just want to use hammer of wrath by cd when it proc and my holy power lower <=3 this is my pvp spec 

### Snapshot (Link)

https://pastebin.com/BJg2sEB9

**Comment by syrifgit** [comment]
There is a wiki page that explains the basics of editing your pack, but essentially you need to move it higher in the list.

https://github.com/Hekili/hekili/wiki/Customizing-A-Hekili-Priority

**Comment by zZzProstudazZz** [comment]
It might be helpful thanks
