### ISSUE TITLE
Defensives Not Showing

### ISSUE THREAD

**Issue by Gortob** [Hekili/hekili#416]
First off I want to say thank you for a great addon that I have been using for years!

Recently my defensives when I am in tank spec have stopped working and I am not quite sure what is wrong? I have looked through the settings and even reset saved variables but it is still the same no matter what class I have in tank spec, any help greatly appreciated.

**Comment by Hekili** [comment]
Most likely, defensives are toggled off.

/hekili
Toggles
Show Defensives

If that doesn't solve it, submit a ticket with the Issue Reporting info and/or a Snapshot and I'll take a look.

**Comment by Gortob** [comment]
That was it thank you /blush
