### ISSUE TITLE
[REC] Disc Priest not recommending Mind Blast before Penance

### ISSUE THREAD

**Issue by rubybrowncoat** [Hekili/hekili#4161]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Discipline

### Describe the Issue

I think the addon should suggest Penance after Mind Blast if both are off cooldown.
When Voidwraith is not active and is on cooldown, the priority is correctly suggesting Mind Blast before Penance.
As soon as Voidwraith goes off cooldown, or is active, the suggestion goes back to Penance before Mind Blast.

Is this intended? It seems weird to me since you are losing on both Power of the Dark Side and the benefits of Collapsing Void.

### How to Reproduce

1. Enter the game as a Disc Priest
2. Make sure to have both "Power of the Dark Side" and "Dark Indulgence" talented.
3. Make sure both penance and mind blast are off coldown.
4. Cast Purge the Wicked so it's not in the priority

### Snapshot (Link)

https://pastebin.com/A3xe4dkg

**Comment by Hekili** [comment]
As far as I can tell, current sim/priority uses Penance over Mind blast in the "Long Shadow Covenant" window.
