### ISSUE TITLE
[REC] Stacks of Juggernaut

### ISSUE THREAD

**Issue by Juchello40k** [Hekili/hekili#4165]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Arms

### Describe the Issue

In ST build of arms with Juggernaut talent hekili recommend execution every time when proc sudden death. But it must be on 3 stacks of marked of execution or at 2-3 sec of juggernaut talent

### How to Reproduce

Enter game at ARMS Warrior, take slayer heroic talents with sudden death and juggernaut talents. See that hekili recommend execution every time when proc sudden death

### Snapshot (Link)

https://pastebin.com/ai99eRmD

**Comment by syrifgit** [comment]
Provide a sim link please

**Comment by Mosborne90** [comment]
Below is a snapshot and Sim for Fury impacted by this issue.

Snapshot (Link)
https://pastebin.com/dvQRMmya

Raidbots Sim Report (Link)
https://www.raidbots.com/simbot/report/3Tte9NSk8XF9ESa6K2c9Hs/simc

**Comment by syrifgit** [comment]
Does this only happen on dummies or any enemy? @Mosborne90 @Juchello40k 

I can't tell from the snapshot because 1 is in cryllic and the other doesn't show any enemy names

**Comment by Hekili** [comment]
I've updated the Arms/Fury models to get Marked for Execution stacks from the default API (it is visible).  The manual detection was not resetting on using Execute because Execute's damage could have a different spellID than expected.

**Comment by Mosborne90** [comment]
> I've updated the Arms/Fury models to get Marked for Execution stacks from the default API (it is visible). The manual detection was not resetting on using Execute because Execute's damage could have a different spellID than expected.

Tested the issue after the latest update. It appears to be working properly now.

Expected damage distribution:

![image](https://github.com/user-attachments/assets/8dc2b386-1284-432f-8f47-69cc457ba5b7)

Hekili rotation damage distribution on live:
![image](https://github.com/user-attachments/assets/a41f0023-55e5-4460-a086-e0a5ec11be9e)
