### ISSUE TITLE
[REC] Fury Warrior rotation, too much Execute

### ISSUE THREAD

**Issue by Mosborne90** [Hekili/hekili#4166]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Fury

### Describe the Issue

I believe the rotation for fury warrior is using execute too often. It is preferring to use execute over crushing blow, rampage, or bloodbath regardless of the stacks of marked for execution. Ideally, this should be used at 3 stacks of mark or to refresh ashen juggernaut, otherwise it falls to a lower priority ability. I've included a snapshot of when execute was recommended that I believe to be incorrect.

![image](https://github.com/user-attachments/assets/691d545c-c7cb-40f4-854d-32fc96dd67e1)

Below is an execute patchwerk sim result:
![image](https://github.com/user-attachments/assets/9391dd0a-368c-4628-869e-fd72da4ec4a9)

here is me following the hekili rotation on execute:
![image](https://github.com/user-attachments/assets/8c0dc172-65c5-45d9-90d0-5f72b88aefe8)

### How to Reproduce

No special actions required

### Snapshot (Link)

https://pastebin.com/dvQRMmya

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3Tte9NSk8XF9ESa6K2c9Hs/simc

**Comment by Juchello40k** [comment]
I have the same problem in Arms, I wrote a ticket https://github.com/Hekili/hekili/issues/4165

**Comment by Mosborne90** [comment]
> I have the same problem in Arms, I wrote a ticket #4165

Yeah it's strange. It seems to want to use execute as soon as I get a sudden death proc regardless of the conditions listed.

```
- this entry's criteria PASSES: debuff.marked_for_execution.stack[3.00] = 3 | buff.ashen_juggernaut.remains[10.68] < 2 | buff.sudden_death.stack[0.00] = 2 & buff.sudden_death.remains[0.00] < 7 | buff.sudden_death.remains[0.00] < 2
        Action chosen:  execute at 0.00!
```

**Comment by syrifgit** [comment]
@Mosborne90 

Can you copy your sim link and snapshot link on the other ticket as a comment and I will close this duplicate?

**Comment by Mosborne90** [comment]
> @Mosborne90
> 
> Can you copy your sim link and snapshot link on the other ticket as a comment and I will close this duplicate?

The other ticket is missing a sim link but provided a pastebin: https://pastebin.com/ai99eRmD

I would make this incident the master as it provides more detail for the issue but appears to be impacting Arms & Fury specs.

**Comment by Mosborne90** [comment]
> @Mosborne90
> 
> Can you copy your sim link and snapshot link on the other ticket as a comment and I will close this duplicate?

Done
