### ISSUE TITLE
Prot war not showing defensive 

### ISSUE THREAD

**Issue by PKoka5** [Hekili/hekili#4169]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [ ] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Protection

### Describe the Issue

when i get low on my prot warrior, hekili is not showing me to pop shield wall or last stand.
Hope this can be fixed 

### How to Reproduce

get low hp on prot warr while being in combat

### Snapshot (Link)

https://pastebin.com/BLvUQ0ih

**Comment by Hekili** [comment]
That is not the default priority for Protection Warrior.

**Comment by PKoka5** [comment]
Where do i get the default priority? i have updated Hekili. i even deleted all the lua's and reinstalled the addon.

**Comment by syrifgit** [comment]
On retail the button is here, unsure about classic

![image](https://github.com/user-attachments/assets/d99181e3-268f-4166-977e-88b840245aa7)

**Comment by PKoka5** [comment]
Done that aswell. Also cant find Shield wall or last stand in the actionlist

![image](https://github.com/user-attachments/assets/8e9bcd49-65e0-4420-9c19-7cf2ff8c7fea)

**Comment by PKoka5** [comment]
Yea the proffile i have is from 2023

![image](https://github.com/user-attachments/assets/eff94171-fdca-4cf7-b6c8-44a9807fa0aa)

**Comment by PKoka5** [comment]
in the addon file there is no Prot warrior APLs 
![image](https://github.com/user-attachments/assets/dcd2e558-a0c4-49bb-8b85-c12b58eca577)
