### ISSUE TITLE
[REC] Fury for some Warriors not working properly

### ISSUE THREAD

**Issue by nancikennedy** [Hekili/hekili#4172]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Fury

### Describe the Issue

I have multiple Warriors, who all use the same talent loadouts for the same things. The only difference is their gear and race. On some of them, as soon as combat starts I get a "Unable to make recommendation for Priority #X".  In most cases, it is for #6 although I can't remember what the others were. This causes the priority queue to drop Raging Blow and Bloodthirst recommendations, although they each become temporarily viewable in the queue when I actually use the ability.

Also, trinkets are never recommended.

### How to Reproduce

1. Enter game as Fury Warrior
2. Use talents: CgEAmidFBOBFf5oKuZ7r/WeW7MAAAAAAAAAgRDMDYMMDjBmFYYGjZmHYYmZbbMmZmFMzMzMjZYb4BYMzAAAAhBGAQAIAbDbA
3. Enter combat

### Snapshot (Link)

https://pastebin.com/ZN4U5PRc

### Additional Information

The char that generated this snapshot is wearing these trinkets
1. id: 129849, Gnomeregan Auto-Blocker 601, ilvl 450
2. id: 207166, Cataclysmic Signet Brand, ilvl 499

**Comment by Hekili** [comment]
This should already be fixed if you upgrade to v11.0.5-1.0.12.

**Comment by nancikennedy** [comment]
Well, no fair pushing an update after I updated my addons today. /grin Thanks for all your great work!
