### ISSUE TITLE
[REC] Word of glory doesn't recommended 

### ISSUE THREAD

**Issue by zZzProstudazZz** [Hekili/hekili#4175]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

I try to add word of glory for my ret pal like as u guide https://github.com/Hekili/hekili/wiki/Customizing-A-Hekili-Priority with regrowth for druid. So I try to set it like health.pct<80  but it's doesn't recommended me to use it after I get under 80 pct hp, also I try another trigger health.pct<80 & holy_power>=3 same - doesn't recommended. I'm asking to help me setup this =\ need it for pvp, like until I rest my hp above pct that I need my ret use only generators abilities for allow me to cast word of glory (requires 3 holy power)

### How to Reproduce

Just start the fight with dummies, I do this in Valdrakken and get under that 80 pct hp or w/e  pct u set

### Snapshot (Link)

https://pastebin.com/NCrN81Mc

### Additional Information

Add a couple screens to show you how I try to setup it https://imgur.com/a/UsJ9Bmd

**Comment by syrifgit** [comment]
Well you placed it at the very very end of your list, which means it's the absolute last priority. Every item in those lists above it also needs to fail first.

Move it higher in your list.

**Comment by Hekili** [comment]
Position matters.  You have it at the lowest point in the action list, so it would only reach that point when none of the spenders or generators are recommended.  You probably want to move the Word of Glory entry up a position or two.

**Comment by zZzProstudazZz** [comment]
Damn seems worked, thanks a lot!
