### ISSUE TITLE
[REC] Aug Evoker not recommending Living Flame (spell)

### ISSUE THREAD

**Issue by Umbrawl** [Hekili/hekili#4177]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

Default priority not recommending living flame as a filler and instead recommends azure strike despite having Pupil of Alexstrasza talented

### How to Reproduce

1. Enter game as Aug Evoker
2. Follow Default Priority on Single Target or AOE
3. See that addon recommends azure strike over living flame as a filler

### Snapshot (Link)

https://pastebin.com/3DNPzcuM

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/wqS3AfeoM3WD8gWngS1Prc

### Additional Information

Living flame does not appear in the "abilities" tab of the addon.
Perhaps this may be due to the addition of the Living Flame Trinket? Just a thought.
Sorry if any formatting is incorrect, this is my first time making a post.

**Comment by Hekili** [comment]
This will be fixed in the next release; Living Flame was overwritten by an old trinket.
