### ISSUE TITLE
[FEATURE] Added text current toggle and current priorities

### ISSUE THREAD

**Issue by blawdi** [Hekili/hekili#4178]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hello, it's possible to added text current toggle and current priorities
![YXhQe2g 1](https://github.com/user-attachments/assets/fdad2ed7-c879-4c14-9c88-6a7a88b663b6)

thx in advance

**Comment by Hekili** [comment]
This is in my backlog, but in the meantime, you can use WeakAuras to see/control your toggles.

https://wago.io/HekiliToggles
