### ISSUE TITLE
See a Display in Healer Spec

### ISSUE THREAD

**Issue by lloydBl** [Hekili/hekili#418]
Is it possible at the moment to activate the primary display and make it visible while in a healer spec?  If not, is this something that can be easily implemented?

I'd love to be able to make my own priority/action lists for simple healer DPS recommendations in dungeons while everyone is at good HP levels. Given healer damage is secondary, I don't think built in priorities are needed, just the ability to see the display and make our own priorities lists.

**Comment by Hekili** [comment]
I'd like to support healer DPS recommendations but it's not a quick and easy thing to do -- abilities are modeled with each specs features in mind, and pretending like you do/don't have those features is problematic.

I do plan on supporting this eventually, just not at the top of the list.

**Comment by lloydBl** [comment]
Neat, and makes sense.
Thanks for that rapid reply
