### ISSUE TITLE
Warrior rotation have missing spells

### ISSUE THREAD

**Issue by Zerak7** [Hekili/hekili#4181]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Arms

### Describe the Issue

Thunderous war, for example, mever appear in the rotation.

### How to Reproduce

Just try warrior arm slayer rotation

### Snapshot (Link)

https://pastebin.com/N1k9h2jQ

### Contact Information

Biggy

**Comment by Zerak7** [comment]
I ve the feeling it happens since I switch between Slayer and Colossus, it's like he doesn't know I ve those spells anymore

**Comment by syrifgit** [comment]
Your cooldowns are disabled.

Use one of these to turn them on/off
- `alt-shift-r`
- type `/hek set cooldowns on`
- Click the minimap button
- or use the weakaura: https://wago.io/HekiliToggles
