### ISSUE TITLE
[REC] Deathstalker sin rogue aoe opener should open with garrote rather than ambush if darknest night is active (due to game bug)

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#4182]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

There's a bug in the game currently where applying Deathstalker's Mark with Ambush from stealth while the Darknest Night is active causes the target's Mark stacks to not be consumed until the Darkest Night buff is consumed. 

The addon seems to always recommend 7cp envenoms to consume the Darkest Night buff even if there is a mark on the target so the bug is already mostly mitigated, however opening with ambush with Darkest Night on aoe is wasted since the applied mark is non-functional until the first 7cp envenom happens anyway, and the ambush can be replaced by an imp. garrote instead when opening onto a new pack in m+ from stealth.

Ideally, the addon would only recommend ambush in aoe with a Darkest Night buff up if it looks like the 7cp envenom wouldn't get applied before the DN buff expires.

### How to Reproduce

1. Use ambush to apply mark + 3 finishers to get darkest night buff
2. Restealth, addon will recommend ambush
3. If you ambush to reapply mark, the mark stacks won't be consumed until the first 7cp envenom

### Snapshot (Link)

https://pastebin.com/nHD6UizR

**Comment by Hekili** [comment]
Is this an issue outside of training dummies?

I could use a snapshot that more accurately reflects the situation you're describing -- as far as the addon can see, you have no Deathstalker's Marks applied, but that might be due to dummies "dying" repeatedly and wiping the aura trackers.

Can you get a snapshot where you have Deathstalker's Mark applied to your current target, Darkest Night is up, and you are in Stealth?

```
target_debuffs:
   383414 - amplifying_poison_dot                    -   1 - 3.01  

...   

21.  ambush ( stealthed - 2 )
 - this entry's criteria PASSES: ! debuff.deathstalkers_mark.up[false] & talent.deathstalkers_mark.enabled[true] & ( active_dot.deathstalkers_mark[0.00] = 0 | buff.darkest_night.down[false] )
```

In the meantime, I'll see if I can persist the aura counting for those target dummies.

**Comment by fzarr** [comment]
I can't be in full stealth (out of combat) as it seems applied marks get removed once you drop combat. But here is a snapshot of me being just out of stealth (after pressing ambush to apply the mark to the mob) with darkest night up before i pressed ambush.

https://pastebin.com/jAQt625U

I should add the addon is working correctly as far as simc is concerned because simc doesn't accurately model this particular bug. Not using ambush with Darkest Night already up is an optimisation since applying a mark with ambush won't have any effect until the darkest night buff is consumed due to bug and garrote is a more efficient GCD.

So the end result would be in the above snapshot (even though the ambush is recommendation -1 and not shown), it would have been garrote instead since the DN buff is up.

**Comment by syrifgit** [comment]
>  because simc doesn't accurately model this particular bug
