### ISSUE TITLE
Living Flame Never Recommended as Dev Evoker

### ISSUE THREAD

**Issue by Rasconza** [Hekili/hekili#4183]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Devastation

### Describe the Issue

**During any rotation the spell Living Flame (the primary filler) is never recommended.**

_In single target, Living Flame is your main filler spell when you lack essence:_

- You will cast Living Flame if you have any of the following buffs: Burnout, Iridescence: Red, Iridescence: Blue or Scarlet Adaptation!
- If none of those things are true, cast Azure Strike to build Essence Burst to cast more Disintegrate!

_In AoE situations the following applies:_

- Living Flame is priority with Leaping Flames!
- At 2 targets, consume Burnout procs with Living flame.
- At 3 or more targets, cast Azure Strike!

### How to Reproduce

The previously mentioned rotation rules above generate no Living Flame suggestions when following it.

### Snapshot (Link)

ST (on dummies): https://pastebin.com/8j4BQdbG
AoE: https://pastebin.com/tBcVgBWp

### Contact Information

ghostras

**Comment by PinkLionArt** [comment]
![image](https://github.com/user-attachments/assets/55ee2291-f7f8-41b7-8c6a-50322420be03)
The Living Flame spell in the action list is not the actual spell

**Comment by syrifgit** [comment]
This is already fixed, wait for the next addon update.
