### ISSUE TITLE
EVOKER?DEV issue reoccuring settings BUG and Rotation

### ISSUE THREAD

**Issue by moxx255** [Hekili/hekili#4186]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

Priority suggest using azure strike during rotation in both Scale commander and chrono warden this is incorrect.. i can see why azure strike could be used due to GCD however with the appropriated talents this isn't a recommended rotation..

secondly when i manually disable azure strike to stick with living flame > azure strike.. it still displays azure strike instead of said living bomb.. this requires a /reload... but when logging out and relogging the azure action setting resets and does the whole process again

this bug causes distraction lack of performance and does not register any buffed ability's 

### How to Reproduce

rotation as a evoker both chrono and scalecommander on training dummys. untick in hekili options azure display and it will still display to use azure strike.. 
/reload to fix with box unticked (works fine)
do a hard relog and it will reset the settings back

### Snapshot (Link)

q

### Additional Information

im not sure how to upload to a pastebin
![AUG BUG](https://github.com/user-attachments/assets/4636cf5f-2908-402b-967d-5cb1e59b558f)

### Contact Information

robinator1990@hotmail.co.uk

**Comment by syrifgit** [comment]
![image](https://github.com/user-attachments/assets/ed9082c0-40ea-4118-9425-bc8d07139f03)

https://github.com/Hekili/hekili/issues/4183 :)

This issue is already solved, please wait for the next addon update.
