### ISSUE TITLE
[REC] Assasination Rogue Envenom energy settings

### ISSUE THREAD

**Issue by sneakerh3ad** [Hekili/hekili#4187]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

In Hekili UI and Assa APL I can see settings for Envenom energy:

![image](https://github.com/user-attachments/assets/44d50f0e-4848-4a88-bff5-bdb669228f96)

Now, as I see, Hekili recommend spend Envenom on 200 energy when Envenom needs 35, that is why sometimes I need to stay afk for 5-7 sec in boss fights, I want to change energy request to 20% in this settings, but it is not working, doesn't metter what amount of energy you select Hekili will recommend Envenom on 200 energy. 

Video - https://www.youtube.com/watch?v=Cwz_6Vh7a-s

### How to Reproduce

1. Enter game on Assa Rogue
2. Target dummy
3. Spend energy to less than 200
4. See recommendation to wait until u get 200
5. Open Hekili settings
6. Change Envenom Energy settings to 20% (60 energy)
7. Target dummy
8. Spend energy to less than 200
9 See recommendation to wait until u get 200 anyway

### Snapshot (Link)

https://pastebin.com/dxjmsQMi

### Contact Information

.sneakerhead

**Comment by syrifgit** [comment]
This setting doesn't do anything at the moment, I may hide it. All energy pooling (waiting) is handled by the SIMC APL, the same thing that runs the sims like Raidbots.

Waiting for the energy is correct and you should do it. Using it earlier will be a DPS loss.
