### ISSUE TITLE
[REC] Frost Mage recommends Freeze when no water elemental pet exists

### ISSUE THREAD

**Issue by EricMiukyQin** [Hekili/hekili#4188]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Frost

### Describe the Issue

This issue occurs both in and out combat sometimes.

### How to Reproduce

None

### Snapshot (Link)

https://pastebin.com/qAM1FupG

**Comment by syrifgit** [comment]
Can you provide the screenshot that the addon took when you generated the snapshot? It should be in your wow folder screenshots

**Comment by EricMiukyQin** [comment]
![Uploading WoWScrnShot_111324_221559.jpg…]()

**Comment by EricMiukyQin** [comment]
![WoWScrnShot_111324_221559](https://github.com/user-attachments/assets/7b3819a8-0cf3-4bb7-8d4c-a1fa46eda516)

**Comment by EricMiukyQin** [comment]
![image](https://github.com/user-attachments/assets/b54bfc2e-79ef-4ef4-8d6a-1ab5e81b774c)

**Comment by EricMiukyQin** [comment]
![image](https://github.com/user-attachments/assets/a8e70d1b-f0c8-4a8d-a28a-6bae6c94c9a6)

**Comment by EricMiukyQin** [comment]
I found the issue. I changed the code incorrectly. My bad, sorry :)
