### ISSUE TITLE
Move icon partially out of the screen.

### ISSUE THREAD

**Issue by Aldwew** [Hekili/hekili#419]
I was wondering if it would be possible to allow the icon to partially out of screen. The x axis does nothing between 900 and 960.

**Comment by Hekili** [comment]
Why?

**Comment by Aldwew** [comment]
Sounds dumb, but I'd like to move the icon so that I can see just the hotkey on the corner of my ui.

**Comment by Hekili** [comment]
It'd make more sense to resize the icon and adjust the hotkey font size into some combination.  I'm going to keep icons fully on-screen as a design decision.
