### ISSUE TITLE
There is always a spell that i dont have in my recommendation and i cant block it 

### ISSUE THREAD

**Issue by Burak309** [Hekili/hekili#4190]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

i rly Love and appreciate your work , but i have a bug where i have always one spell in my rotation, which i dont have on my character . I tried to block the spell but i cant cause i dont have it on my char. i rly hope you can help me with that.
![Screenshot 2024-11-14 000141](https://github.com/user-attachments/assets/42122589-b84d-4a8c-adf7-799f39ded652)
I have a preservation evoker btw and im realy a beginner first time playing wow 

### How to Reproduce

1.enter as evoker 2.look at my rotations always a spell there which i dont have 

### Player Information (Link)

Preservation; Primary - Tiefer Atem(0.00), Integriertes Urfeuer(6.00), Feueratem(6.00)

### Error Messages (Link)

cant get any 

### Additional Information

i tried other characters and still , always this spell is coming up 

### Contact Information

Elvis Stitchley #8750

**Comment by Burak309** [comment]
its the 2. spell on the rotation. i know that this class is a healer but i get it with every char

**Comment by syrifgit** [comment]
That's not whole snapshot, you need to press ctrl-a to get it all.

But it's either a trinket or the living flame bug. Did you update to the newest version that came out today?

**Comment by Burak309** [comment]
where can i download the newest version cause there is no on curse forge. Thanks for the quick response tho
![new](https://github.com/user-attachments/assets/61d7dd8f-b8e0-4687-832c-22258c5a05b6)

**Comment by syrifgit** [comment]
Maybe Curseforge is slow today, you can always download it right here from Github: https://github.com/Hekili/hekili/releases/tag/v11.0.5-1.0.13

**Comment by Burak309** [comment]
sry that i bother you with this question but should i just download the first hekili zip or all data with the source code and then just copy paste into addons ?

**Comment by Burak309** [comment]
so installed the newest version and still got the spell 
![new](https://github.com/user-attachments/assets/b6cfa896-9e59-4d43-952e-2ba16304e58d)

**Comment by syrifgit** [comment]
Try and get the full snapshot. Instructions below.


Please get a proper snapshot during the time you think the recommendation is incorrect.

Instructions: https://github.com/Hekili/hekili/wiki/Report-An-Issue#how-do-i-get-a-snapshot

**Comment by Burak309** [comment]
Preservation; Primary - Segen der Bronzenen(0.00), Tiefer Atem(1.40), Integriertes Urfeuer(7.40)
build: v11.0.5-1.0.13
level: 31 (31)
class: EVOKER
spec: preservation

talents: CwbBV7//nP39x/JJympTqouKSAAAAAAYmZ2GAGAAAAAghxAMjwDMAAAAzMzEAAAAAAAAAAYA
    attuned_to_the_dream = 2/2
    cauterizing_flame = 1/1
    dream_breath = 1/1
    echo = 1/1
    essence_attunement = 1/1
    essence_burst = 1/1
    expunge = 1/1
    font_of_magic = 1/1
    heavy_wingbeats = 1/1
    innate_magic = 2/2
    instinctive_arcana = 1/2
    obsidian_bulwark = 1/1
    obsidian_scales = 1/1
    quell = 1/1
    reversion = 1/1
    rewind = 1/1
    scarlet_adaptation = 1/1
    spiritbloom = 1/1
    spiritual_clarity = 1/1
    temporal_compression = 1/1
    time_dilation = 1/1
    verdant_embrace = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: integrated_primal_fire = 1

gear: blutrotes_dracthyrtuch = 1
    ekrazathals_bunter_reizahn = 1
    ewige_drachenspitze = 1
    gamaschen_des_expeditionssldners = 1
    gelenkbnder_des_expeditionssldners = 1
    geschwungene_klaue_von_todesriss = 1
    grtel_der_karmindracthyrrstung = 1
    halsberge_des_expeditionssldners = 1
    integrated_primal_fire = 1
    integriertes_urfeuer = 1
    primalistenanhnger = 1
    schulterschutz_der_karmindracthyrrstung = 1
    siegelring_der_drachkin = 1
    stiefel_des_expeditionssldners = 1
    sturmklapperstulpen = 1
    wespenabweisende_schdelkappe = 1

legendaries: none

itemIDs: 191809, 191810, 193752, 193803, 193916, 194333, 194352, 194369, 194382, 194402, 194405, 194413, 194422, 197725, 200868

settings: aoe = 3
    combatRefresh = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 30
    enabled = true
    gcdSync = true
    maxTime = 20
    nameplateRange = 40
    nameplates = false
    noFeignedCooldown = false
    package = Preservation
    petbased = false
    potion = default
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    fire_breath_fixed = 0
    spend_essence = false
    use_deep_breath = true
    use_unravel = false

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true [overridden]
    funnel = false 
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    azure_strike           = 2   [01]
    blessing_of_the_bronze = C5  [05]
    cauterizing_flame      = F7  [06]
    deep_breath            = 5   [01]
    disintegrate           = 3   [01]
    dream_breath           = F5  [06]
    echo                   = F1  [06]
    emerald_blossom        = F2  [06]
    fire_breath            = 4   [01]
    living_flame           = 1   [01]
    naturalize             = C6  [05]
    obsidian_scales        = 8   [01]
    reversion              = F4  [06]
    spiritbloom            = F3  [06]
    time_dilation          = 7   [01]
    verdant_embrace        = F6  [06]

warnings: none


targets:  Nameplates are enabled.

player_buffs:
   225788 - *zeichen_des_gesandten                   -   1 - 3600.00
   452307 - *zeichen_der_vergangenheit               -   1 - 3600.00
   225822 - *gefunkel                                -   1 - 476.26
   455020 - *geburtstag_von_wow                      -   1 - 3600.00
   404464 - *flugstil_himmelsreiten                  -   1 - 3600.00
   463525 - *prismatischer_segen                     -   1 - 3600.00
   463534 - *obsidiansegen                           -   1 - 3600.00

player_debuffs:

target_auras:  target does not exist

previous_spells:
   1 - hover


New Recommendations for [ Primary ] requested at 01:21:51 ( 76004.01 ); using built-in ( Preservation ) priority.
*** START OF NEW DISPLAY: Primary ***
Purged 361 marked values in 0.14ms.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: essence[ 5.00 / 5.00 ], mana[ 2165.00 / 2165.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Preservation - precombat ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        1.   blessing_of_the_bronze ( precombat - 1 )
        The action (blessing_of_the_bronze) is usable at (0.00 + 0.00) with cost of 21 mana (have 2165).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry has no criteria to test.
        Action chosen:  blessing_of_the_bronze at 0.00!
        Exiting precombat with recommendation of NO ACTION at +10.00s.
    
    Completed precombat action list [ Preservation - precombat ].
    Recommendation is blessing_of_the_bronze at 0.00 + 0.00.
    Recommendation #1 is blessing_of_the_bronze at 0.00s (0.00s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.40, Casting: 0.00 ).

    Resources: essence[ 5.00 / 5.00 ], mana[ 2143.35 / 2165.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Preservation - precombat ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        1.   blessing_of_the_bronze ( precombat - 1 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Preservation-precombat-1:blessing_of_the_bronze:x0:0.02:Ability Known, Enabled(0.02)
        Exiting precombat with recommendation of NO ACTION at +10.00s.
    
    Completed precombat action list [ Preservation - precombat ].
    
    Processing default action list [ Preservation - default ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        2.   quell ( default - 1 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.03ms
        TimeData:Preservation-default-1:quell:x0:0.03:Ability Known, Enabled(0.03)
        
        3.   cauterizing_flame ( default - 2 )
        The action (cauterizing_flame) is unusable at (0.00 + 0.00) because requires dispellable effect.
        Time spent on this action:  0.15ms
        TimeData:Preservation-default-2:cauterizing_flame:x0:0.15:Ability Known, Enabled(0.03):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.07)
        
        4.   unravel ( default - 3 ) - talent [ unravel ] missing
        Time spent on this action:  0.02ms
        TimeData:Preservation-default-3:unravel:x0:0.02:Ability Known, Enabled(0.02)
        
        5.   deep_breath ( default - 4 )
        The action (deep_breath) is usable at (0.00 + 1.40).
         - the action is ready before the current recommendation (at +1.40 vs. +10.00).
         - this entry has no criteria to test.
        Action chosen:  deep_breath at 1.40!
        Time spent on this action:  0.20ms
        TimeData:Preservation-default-4:deep_breath:x0:0.20:Ability Known, Enabled(0.07):Post-TTR and Essential(0.07):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Recheck(0.00):Post Recheck(0.00):Action Stored(0.01)
        
        Substituting elemental_potion_of_power for Potion action; it is otherwise not included in the priority.
        6.   elemental_potion_of_power ( default - 5 ) - IsUsableItem item 191387 and nil
        Time spent on this action:  0.06ms
        TimeData:Preservation-default-5:elemental_potion_of_power:x0:0.06:Ability Known, Enabled(0.06)
        The recommended action (deep_breath) is ready within the active GCD; exiting list (default).
        Exiting default with recommendation of NO ACTION at +10.00s.
    
    Completed default action list [ Preservation - default ].
    Recommendation is deep_breath at 0.00 + 1.40.
    Recommendation #2 is deep_breath at 1.40s (1.40s).
    Starting combat at 76005.41 -- time is 0.01.

RECOMMENDATION #3 ( Offset: 1.40, GCD: 6.00, Casting: 0.00 ).

    Resources: essence[ 5.00 / 5.00 ], mana[ 2165.00 / 2165.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Preservation - precombat ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        1.   blessing_of_the_bronze ( precombat - 1 )
        The action is not ready ( 3598.60 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Preservation-precombat-1:blessing_of_the_bronze:x0:0.02:Ability Known, Enabled(0.02)
        Exiting precombat with recommendation of NO ACTION at +10.00s.
    
    Completed precombat action list [ Preservation - precombat ].
    
    Processing default action list [ Preservation - default ].
        
        Current recommendation was NO ACTION at +10.00s.
        
        2.   quell ( default - 1 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Preservation-default-1:quell:x0:0.02:Ability Known, Enabled(0.02)
        
        3.   cauterizing_flame ( default - 2 )
        The action (cauterizing_flame) is unusable at (1.40 + 0.00) because requires dispellable effect.
        Time spent on this action:  0.06ms
        TimeData:Preservation-default-2:cauterizing_flame:x0:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.01)
        
        4.   unravel ( default - 3 ) - talent [ unravel ] missing
        Time spent on this action:  0.02ms
        TimeData:Preservation-default-3:unravel:x0:0.02:Ability Known, Enabled(0.02)
        
        5.   deep_breath ( default - 4 )
        The action is not ready ( 120.00 ) before our maximum delay window ( 10.00 ) for this query.
        Time spent on this action:  0.04ms
        TimeData:Preservation-default-4:deep_breath:x0:0.04:Ability Known, Enabled(0.04)
        
        Substituting elemental_potion_of_power for Potion action; it is otherwise not included in the priority.
        6.   elemental_potion_of_power ( default - 5 ) - IsUsableItem item 191387 and nil
        Time spent on this action:  0.04ms
        TimeData:Preservation-default-5:elemental_potion_of_power:x0:0.04:Ability Known, Enabled(0.04)
        
        7.   use_items ( default - 6 )
        There is no criteria for Use Items.
        + items
        Current recommendation was NO ACTION at +10.00s.
        
        8.   integrated_primal_fire ( items - 1 )
        The action (integrated_primal_fire) is usable at (1.40 + 6.00).
         - the action is ready before the current recommendation (at +6.00 vs. +10.00).
        List ( items ) called from ( Preservation:default:6 ) would PASS at 6.00.
        NONE
         - this entry's criteria PASSES: ( ! settings.boss[false] | boss[false] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
        Action chosen:  integrated_primal_fire at 6.00!
        Time spent on this action:  0.27ms
        TimeData:UseItems-items-1:integrated_primal_fire:x0:0.27:Ability Known, Enabled(0.09):Post-TTR and Essential(0.07):Post Cycle(0.00):Post Usable(0.01):Post Ready/Clash(0.02):Post Stack(0.02):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.03):Post Recheck(0.00):Action Stored(0.01)
        Exiting items with recommendation of NO ACTION at +10.00s.
        Returned from Use Items; current recommendation is integrated_primal_fire (+6.00).
        - items
        
        9.   fire_breath ( default - 7 )
        The action is not ready in time ( 6.00 vs. 6.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Preservation-default-7:fire_breath:x0:0.03:Ability Known, Enabled(0.03)
        
        10.  fire_breath ( default - 8 )
        The action is not ready in time ( 6.00 vs. 6.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Preservation-default-8:fire_breath:x0:0.03:Ability Known, Enabled(0.03)
        
        11.  fire_breath ( default - 9 )
        The action is not ready in time ( 6.00 vs. 6.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Preservation-default-9:fire_breath:x0:0.03:Ability Known, Enabled(0.03)
        
        12.  fire_breath ( default - 10 )
        The action is not ready in time ( 6.00 vs. 6.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Preservation-default-10:fire_breath:x0:0.03:Ability Known, Enabled(0.03)
        
        13.  hover ( default - 11 )
        The action is not ready in time ( 6.00 vs. 6.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Preservation-default-11:hover:x0:0.03:Ability Known, Enabled(0.03)
        Only off-GCD abilities would be usable before the currently selected ability; skipping...
        The recommended action (integrated_primal_fire) is ready within the active GCD; exiting list (default).
        Exiting default with recommendation of NO ACTION at +10.00s.
    
    Completed default action list [ Preservation - default ].
    Recommendation is integrated_primal_fire at 1.40 + 6.00.
    Recommendation #3 is integrated_primal_fire at 6.00s (7.40s).
    Time spent generating recommendations:  3.45ms

**Comment by Burak309** [comment]
![new](https://github.com/user-attachments/assets/d2edb60c-2dff-4eee-8c03-54a9738e8b1e)

**Comment by Reshuffling** [comment]
Trinket https://www.wowhead.com/de/item=200868/integriertes-urfeuer

**Comment by Burak309** [comment]
how do i fix it ?

**Comment by syrifgit** [comment]
Cast the trinket? Or turn it off under Gear and items pahe.
