### ISSUE TITLE
[REC] Sin rogue ST opener with M+ build prediction is incorrect

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#4191]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

ST opener predicts ambush->garrote->rupture->fan->ambush (corrent) but then goes into rupture->fan instead of envenom->deathmark, Attached snapshot vs raidbots sample iteration.

Think it could possibly be something to do with the cycle setting.

### How to Reproduce

1. Set rotation to ST mode
2. Stealth and target mob. Incorrect prediction of opener is shown

### Snapshot (Link)

https://pastebin.com/1RBceUrH

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/1j814zsq7cZQdQg5Q8rR7K

**Comment by syrifgit** [comment]
Has to do with energy regen and my target swap helper thing. Turning target swap on should immediately fix it, but I'll incorporate a permanent fix like I did for garrote on my next update. Like the other ticket, update to newest version as well.

**Comment by fzarr** [comment]
Seems to be fixed with the latest release.
