### ISSUE TITLE
[REC] Sin rogue opener is recommending garrote between opening DM and KB

### ISSUE THREAD

**Issue by fzarr** [Hekili/hekili#4193]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Addon recommending garrote instead of kingsbane after dm in opener. In snapshot, Rec#1 should be KB instead of garrote.

### How to Reproduce

1. Perform opener rotation, a garrote will be recommended between DM and KB instead of direct to KB

### Snapshot (Link)

https://pastebin.com/LrjRAtEC

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/1j814zsq7cZQdQg5Q8rR7K

**Comment by syrifgit** [comment]
You should update to the newest version first. But looks to me like maybe you're doing your opener too slow and so garrote is getting below 12 seconds remaining and so refreshing it is a higher priority there. I don't think this disagrees with the sims, but I also can't replicate it.

**Comment by fzarr** [comment]
This has been fixed in the latest version.
