### ISSUE TITLE
[BUG] LUA error triggered by Elemental Spirits - Molten Weapon (Enha Shaman)

### ISSUE THREAD

**Issue by datslurms** [Hekili/hekili#4194]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

When a fire dog is summoned by the ability Elemental Spirits (Flowing Spirits) I'm getting a lua error accompanied by a pretty substantial performance drop until I reload my ui.

reinstalled version 1.0.14 of the addon and the issue persisted, rolled back to version 1.0.12 and it appears to be solved.

### How to Reproduce

1. talent Elemental Spirits
2. possibly talent Flowing Spirits
3. enter combat and attack with a fire based spell (flame shock, fire nova, lava burst or lava lash) until a fire dog (Molten Weapon) is summoned

### Player Information (Link)

https://pastebin.com/6wUKzFjZ

### Error Messages (Link)

https://pastebin.com/jdFMT6eM

### Contact Information

discord id: slurms (i am in the hekili discord server)

**Comment by geraint425** [comment]
https://pastebin.com/p111TRGR
Confirmed, I also get the same error

**Comment by Hekili** [comment]
1.0.14a should fix this issue.  Thanks!
