### ISSUE TITLE
[REC] Living Flame (Chrono Flame) is not being recommended for Augment

### ISSUE THREAD

**Issue by rognarok** [Hekili/hekili#4195]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Evoker - Augmentation

### Describe the Issue

Chrono Flame is not being recommended, and neither is living Flame with either hero talent tree.  When looking at the ability list in the addon for stuff to enable Living Flame nor Chrono Flame is even listed for enable or disable

### How to Reproduce

1. Enter the game and play as augment evoker.  2. Try to do normal rotation, even on single target and instead of Chrono Flame/Living Flame Azure Strike is recommended.

### Snapshot (Link)

https://pastebin.com/zUunfXN7

### Contact Information

pastafarian for discord

**Comment by syrifgit** [comment]
This is already fixed, you're multiple addon versions out of date.

https://www.wowinterface.com/downloads/info24608-HekiliPriorityHelper.html

https://addons.wago.io/addons/hekili/

https://github.com/Hekili/hekili/releases/latest

**Comment by rognarok** [comment]
I apologize, it seems I wasn't automatically updated to the latest version even though I should have been.  I will try to be more careful in the future
