### ISSUE TITLE
[REC] Priority/Recommendation Issue Blood DK for both San'layn& Deathbringer

### ISSUE THREAD

**Issue by PARADOX070** [Hekili/hekili#4197]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Blood

### Describe the Issue

Both default priority's provided for San'layn & Deathbringer feel off. What is currently being suggested is the default APL and not, the APL that is provided on the Acherus DK discord for both San'layn & Deathbringer.

These 2 quick sims are a reflection of what's currently being suggested in-game:
- (San'layn) https://www.raidbots.com/simbot/report/aXDAXk1qEvjoVnnC5mRMpF
- (Deathbringer) https://www.raidbots.com/simbot/report/akjTJ15GKQmAG6vbyLofyd

Following hekili's current recommendations reflects the DPS from these sims in-game as well.

However following the APL from the Acherus DK discord this happens:
- (San'layn) https://www.raidbots.com/simbot/report/pDedC5LAFPqWxWSUXBVNRM
- (Deathbringer) https://www.raidbots.com/simbot/report/2Y8qSfV8fVPHkJjEa1GAWr

And yes these number can be reproduced in-game following the correct rotation.

The entire rotation for San'layn just seems wrong, Vampiric Blood is still being suggested in the rotation (snapshot included), this is no longer a thing as of recent changes. As San'layn Soul Reaper also doesn't seem to be prioritized on targets at or below 35%. Death & Decay usage also feels off as San'layn, as in not being suggested as much as it should. Deathstrike usage needs to be a lot more then what it currently is, you're often Runic Power capped and beyond.

Deathbringer not consuming Soulreaper procs as per snapshot when having the Reaper of Souls buff. (It does show up briefly but very quickly disappears, leaving you with the Reaper of Souls buff not consuming it).

The custom APL's provided on the Acherus DK discord are:

San'layn APL
```
# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats
actions.precombat+=/deaths_caress

# Executed every time the actor is available.
actions=auto_attack
actions+=/use_items
actions+=/run_action_list,name=sanlayn,if=hero_tree.sanlayn

actions.sanlayn=variable,name=death_strike_dump_amount,value=50
actions.sanlayn+=/variable,name=death_strike_pre_essence_dump_amount,value=20
actions.sanlayn+=/variable,name=bone_shield_refresh_value,value=7
actions.sanlayn+=/variable,name=heart_strike_rp_drw,value=(21+spell_targets.heart_strike*talent.heartbreaker.enabled*2)
actions.sanlayn+=/death_strike,if=buff.coagulopathy.remains<=gcd
actions.sanlayn+=/deaths_caress,if=!buff.bone_shield.up
actions.sanlayn+=/blood_boil,if=!dot.blood_plague.ticking|(dot.blood_plague.remains<10&buff.dancing_rune_weapon.up)
actions.sanlayn+=/potion,if=buff.dancing_rune_weapon.up
actions.sanlayn+=/consumption,if=pet.dancing_rune_weapon.active&pet.dancing_rune_weapon.remains<=3
actions.sanlayn+=/death_strike,if=runic_power>=108
actions.sanlayn+=/bonestorm,if=(buff.death_and_decay.up)&buff.bone_shield.stack>5&cooldown.dancing_rune_weapon.remains>=25&buff.coagulopathy.remains>3*gcd
actions.sanlayn+=/heart_strike,if=buff.dancing_rune_weapon.up&rune>1
actions.sanlayn+=/death_and_decay,if=!buff.death_and_decay.up
actions.sanlayn+=/heart_strike,if=buff.infliction_of_sorrow.up&buff.death_and_decay.up
actions.sanlayn+=/raise_dead
actions.sanlayn+=/abomination_limb
actions.sanlayn+=/tombstone,if=(!buff.dancing_rune_weapon.up&buff.death_and_decay.up)&buff.bone_shield.stack>5&runic_power.deficit>=30&cooldown.dancing_rune_weapon.remains>=25&buff.coagulopathy.remains>2*gcd
actions.sanlayn+=/dancing_rune_weapon,if=buff.coagulopathy.remains>=2*gcd&(!buff.essence_of_the_blood_queen.up|buff.essence_of_the_blood_queen.remains>=3*gcd)&(!buff.dancing_rune_weapon.up|buff.dancing_rune_weapon.remains>=6*gcd)
actions.sanlayn+=/death_strike,if=!buff.vampiric_strike.up&cooldown.dancing_rune_weapon.remains<=30&runic_power>variable.death_strike_pre_essence_dump_amount&buff.essence_of_the_blood_queen.stack>=3
actions.sanlayn+=/marrowrend,if=!dot.bonestorm.ticking&(buff.bone_shield.stack<variable.bone_shield_refresh_value&runic_power.deficit>20&rune>3|buff.bone_shield.remains<=3)
actions.sanlayn+=/marrowrend,if=!dot.bonestorm.ticking&(buff.bone_shield.stack<variable.bone_shield_refresh_value&runic_power.deficit>20&!cooldown.dancing_rune_weapon.up|buff.bone_shield.remains<=3)
actions.sanlayn+=/soul_reaper,if=active_enemies=1&target.time_to_pct_35<5&target.time_to_die>(dot.soul_reaper.remains+5)
actions.sanlayn+=/death_strike,if=buff.dancing_rune_weapon.up&(buff.coagulopathy.remains<2*gcd|(runic_power.deficit<=variable.heart_strike_rp_drw&buff.incite_terror.stack>=3))
actions.sanlayn+=/heart_strike,if=buff.vampiric_strike.up|buff.infliction_of_sorrow.up&((talent.consumption.enabled&buff.consumption.up)|!talent.consumption.enabled)&dot.blood_plague.ticking&dot.blood_plague.remains>20
actions.sanlayn+=/dancing_rune_weapon,if=buff.coagulopathy.up
actions.sanlayn+=/death_strike,if=runic_power.deficit<=variable.heart_strike_rp_drw|runic_power>=variable.death_strike_dump_amount
actions.sanlayn+=/blood_boil,if=charges>=2|(full_recharge_time<=gcd.max)
actions.sanlayn+=/consumption,if=cooldown.dancing_rune_weapon.remains>25
actions.sanlayn+=/heart_strike,if=rune>1
actions.sanlayn+=/bonestorm,if=buff.death_and_decay.up&buff.bone_shield.stack>5&cooldown.dancing_rune_weapon.remains>=25
actions.sanlayn+=/tombstone,if=buff.death_and_decay.up&buff.bone_shield.stack>5&runic_power.deficit>=30&cooldown.dancing_rune_weapon.remains>=25
```

Deathbringer APL
```
actions.precombat=flask
actions.precombat+=/food
actions.precombat+=/augmentation
actions.precombat+=/snapshot_stats

# Executed every time the actor is available.
actions=auto_attack
actions+=/variable,name=death_strike_dump_amount,value=35
actions+=/variable,name=bone_shield_refresh_value,value=6
actions+=/variable,name=heart_strike_rp_drw,value=(25+spell_targets.heart_strike*talent.heartbreaker.enabled*2)
actions+=/potion,if=buff.dancing_rune_weapon.up
actions+=/raise_dead
actions+=/blood_fury,if=cooldown.dancing_rune_weapon.ready
actions+=/berserking,if=cooldown.dancing_rune_weapon.ready
actions+=/blood_tap,if=rune<=1
actions+=/use_items
actions+=/deaths_caress,if=!buff.bone_shield.up
actions+=/death_strike,if=buff.coagulopathy.remains<=gcd|runic_power.deficit<35
actions+=/blood_boil,if=dot.reapers_mark.ticking&dot.reapers_mark.remains<2*gcd
actions+=/blood_boil,if=dot.reapers_mark.ticking&charges_fractional>=1.5
actions+=/consumption,if=dot.reapers_mark.ticking&dot.blood_plague.ticking
actions+=/soul_reaper,if=buff.reaper_of_souls.up&buff.coagulopathy.remains>1*gcd
actions+=/soul_reaper,if=active_enemies=1&target.time_to_pct_35<5&target.time_to_die>(dot.soul_reaper.remains+5)
actions+=/blood_boil,if=(dot.reapers_mark.ticking&(pet.dancing_rune_weapon.active&!drw.bp_ticking))|!dot.blood_plague.ticking|(charges_fractional>=1&dot.reapers_mark.ticking&buff.coagulopathy.remains>2*gcd)
actions+=/death_and_decay,if=((dot.reapers_mark.ticking)&!death_and_decay.ticking)|!buff.death_and_decay.up
actions+=/marrowrend,if=(buff.exterminate.up)&(runic_power.deficit>20&buff.coagulopathy.remains>2*gcd)
actions+=/abomination_limb,if=dot.reapers_mark.ticking
actions+=/reapers_mark,if=!dot.reapers_mark.ticking&dot.blood_plague.ticking
actions+=/bonestorm,if=buff.death_and_decay.up&buff.bone_shield.stack>5&cooldown.dancing_rune_weapon.remains>=10&(dot.reapers_mark.ticking)
actions+=/abomination_limb
actions+=/blooddrinker,if=buff.coagulopathy.remains>3*gcd&!buff.dancing_rune_weapon.up
actions+=/dancing_rune_weapon,if=buff.coagulopathy.remains>2*gcd
# actions+=/tombstone,if=buff.death_and_decay.up&cooldown.bonestorm.up&buff.bone_shield.stack>10&runic_power.deficit>=30&cooldown.dancing_rune_weapon.remains>=10
actions+=/bonestorm,if=buff.death_and_decay.up&buff.bone_shield.stack>5&cooldown.dancing_rune_weapon.remains>=10
actions+=/tombstone,if=buff.death_and_decay.up&buff.bone_shield.stack>5&runic_power.deficit>=30&cooldown.dancing_rune_weapon.remains>=10
actions+=/marrowrend,if=!dot.bonestorm.ticking&(buff.bone_shield.stack<variable.bone_shield_refresh_value&runic_power.deficit>20|buff.bone_shield.remains<=3)
actions+=/blood_boil,if=charges_fractional>=1.5|(full_recharge_time<=gcd.max)
actions+=/consumption
actions+=/death_strike,if=runic_power.deficit<=variable.heart_strike_rp_drw|runic_power>=variable.death_strike_dump_amount
actions+=/blood_boil,if=charges_fractional>=1.5&buff.hemostasis.stack<5&cooldown.reapers_mark.remains>5
actions+=/heart_strike,if=rune>=1|rune.time_to_2<gcd|runic_power.deficit>=variable.heart_strike_rp_drw
actions+=/blood_boil
```

### How to Reproduce

See above.

### Snapshot (Link)

(San'layn) https://pastebin.com/8Xp7zCfX
(Deathbringer) https://pastebin.com/pUX8Ak52
(Deathbringer) https://pastebin.com/4aw5HLa9

**Comment by ElemKai** [comment]
+++

**Comment by syrifgit** [comment]
Someone else asked about reaper of souls on discord, basically we have the wrong SpellID for it (use the ID of the talent instead of the buff). Will be fixed soon hopefully.

If you want to fix it for yourself in the meantime, you can go into the `DeathKnightBlood.lua` file and change this

![image](https://github.com/user-attachments/assets/7864accc-92a9-4a90-90b1-03151b1e5759)


to this `469172`

![image](https://github.com/user-attachments/assets/040223d2-9460-4d3a-b7c2-5b887369a415)


Haven't looked at the rest of the ticket yet, just address this quick fix.

**Comment by PARADOX070** [comment]
Will apply it and give it a try for Deathbringer. However the main culprit right now is San'layn being a (insert something funny), it just isn't right at all.

**Comment by trbaxter** [comment]
Tested this out from my end, not getting a similar outcome for San'layn. Current version is 11.0.5-1.0.14a.

Using the default APL: [1.6M on 4 level 80 target dummies in Zuldazar](https://www.warcraftlogs.com/reports/KC17DZQ6y2rhgjnG#fight=last&start=788882&end=968850)

Using Acherus APL: [1.3M on same targets](https://www.warcraftlogs.com/reports/afrKdWQhJjxAqLm3#fight=last&start=1095298&end=1275442)

Default APL seems objectively better in terms of damage (18.218% difference). Can confirm that Vampiric Blood was being recommended in the rotation with defensives turned on, however, it was always low on the ladder and would fade out before moving up the priority chain: 

![image](https://github.com/user-attachments/assets/fa35a2fc-e427-4021-82bf-670a3d06af29)

Highest priority is shown from left to right in the image. This issue can be avoided entirely by simply turning off the defensives in the display menu. These results are in near-alignment with the output of [a raidbots sim](https://www.raidbots.com/simbot/report/fxUwtFv6UTPk2JCmQm1cVk) given the conditions used in-game.

**Comment by PARADOX070** [comment]
> Tested this out from my end, not getting a similar outcome for San'layn. Current version is 11.0.5-1.0.14a.
> 
> Using the default APL: [1.6M on 4 level 80 target dummies in Zuldazar](https://www.warcraftlogs.com/reports/KC17DZQ6y2rhgjnG#fight=last&start=788882&end=968850)
> 
> Using Acherus APL: [1.3M on same targets](https://www.warcraftlogs.com/reports/afrKdWQhJjxAqLm3#fight=last&start=1095298&end=1275442)
> 
> Default APL seems objectively better in terms of damage (18.218% difference). Can confirm that Vampiric Blood was being recommended in the rotation with defensives turned on, however, it was always low on the ladder and would fade out before moving up the priority chain:
> 
> ![image](https://private-user-images.githubusercontent.com/108769032/386708424-fa35a2fc-e427-4021-82bf-670a3d06af29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTQ4NjEsIm5iZiI6MTczMTY5NDU2MSwicGF0aCI6Ii8xMDg3NjkwMzIvMzg2NzA4NDI0LWZhMzVhMmZjLWU0MjctNDAyMS04MmJmLTY3MGEzZDA2YWYyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxODE2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWRmNWIwZmNlOGE4YzlhNWEyNzE1M2E2Y2MwYWQzY2QyMGFhMGUzMTA3NjI3YWEzYzBlYmVmMzI3ZThmYjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qK2uL1TiZ3yCVR3WQp9FYdVS89IgTO3A1QEaNtGxI9k)
> 
> Highest priority is shown from left to right in the image. This issue can be avoided entirely by simply turning off the defensives in the display menu. These results are in near-alignment with the output of [a raidbots sim](https://www.raidbots.com/simbot/report/fxUwtFv6UTPk2JCmQm1cVk) given the conditions used in-game.

Custom APL your settings and character and voila: https://www.raidbots.com/simbot/report/h6uZbyuHq8USxHtAkwP2mG, All my SIMS are ST Patchwerk 5m, and not AOE.

**Comment by syrifgit** [comment]
You could just run an advanced sim and directly compare the 2 APLs on the same sim.

**Comment by trbaxter** [comment]
Here's another test run where I was able to squeeze out a bit more DPS by deviating slightly from Acherus APL by capitalizing on Blood Boil stacks from hemostasis: [~1.443M on same targets in the same time](https://www.warcraftlogs.com/reports/jzPgmRncd1MwCfWZ#fight=last)

Still not even remotely reaching what raidbots is claiming with the modified APL. Something seems incredibly fishy about those numbers. 

Comparing some parts of the damage profile, some things are standing out: 

Vampiric Strike (real run) - 40 counts, 42.97M total damage
Vampiric Strike (raidbots) - 54 counts, 173.3M total damage

The Blood is Life (real run) - 12 counts, 29.63M total damage
The Blood is Life (raidbots) - 5 counts, 70.76M total damage

Infliction of Sorrow (real run) - 164 counts, 34.85M total damage
Infliction of Sorrow (raidbots) - 213 counts, 39.06M total damage

I'd love to know where the additional 14 Vampiric Strike casts came from and how they more than quadrupled the overall damage from that ability. The average VS in a real run was a little over a million per strike. Acherus APL's is about 3.2 million per strike. Where is the other 2 million coming from?

<br/>

This isn't to say that the Acherus APL is inherently bad - hell, if we can get an extra 300k by using it, then let's rock n' roll. But such a massive difference in expected vs. actual outcomes seems sus compared to Hekili vanilla numbers.

**Comment by PARADOX070** [comment]
Once again you're AOEing.

Advanced comparing both APL's https://www.raidbots.com/simbot/report/vXvdtYvw4xN9D3emNqP714
@trbaxter feel free to call them out in discord, dont shoot the messenger.

**Comment by trbaxter** [comment]
No no, don't interpret it as shooting the messenger. If there's a better rotation that's 15% better, that's awesome. 

The question is whether this is a sim trap or not. Here's the results of a single-target run just now: [484k](https://www.warcraftlogs.com/reports/PnvD8yRJcGLY7BMC#fight=last)

Using the custom APL in raidbots returns [655k](https://www.raidbots.com/simbot/report/e6kZMy9HcLvjdqHvvVhZiU).

What I think is important to know is why, when I add the Acherus APL into a custom profile in the addon and do what they're instructing, that the outcome is 25% different than what's experienced in game compared to the default profile (which is only 5% different).

**Comment by syrifgit** [comment]
I mean if it's better, why are they not updating SIMC?

**Comment by PARADOX070** [comment]
> I mean if it's better, why are they not updating SIMC?

https://i.imgur.com/HQUqARc.png

**Comment by syrifgit** [comment]
Not sure I agree with your comment, assuming that's you, but thanks.

**Comment by trbaxter** [comment]
"as I have some one screaming from the top of their lungs.. Acherus is wrong default is correct." 

I already suspected you never read anything I wrote, but that line confirms it.

**Comment by PARADOX070** [comment]
This is turning into bickering and finger pointing at this point. As I've said don't shoot the messenger. I'm here reporting things backed up by an entire server with a lot of people breaking their heads over this. I'm not here for flak, I'm here trying to get this resolved for anyone playing San'layn using the addon they all love. If you think they are wrong feel free to bring it up there.

**Comment by syrifgit** [comment]
Relax. I asked why the sims weren't updated (because we always base the addon APLs off of what the sims are set to, unless we have good reason not to do that), I got my answer that's all I needed. Addon will be updated eventually.
