### ISSUE TITLE
[BUG] Unholy DK Bugged

### ISSUE THREAD

**Issue by Fuxxic** [Hekili/hekili#4199]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I was using Hekili today as an unholy DK on the AOE target dummies in Dornogal. The addon has failed. Its not working.

### How to Reproduce

Enter Game as Unholy DK...Use my Talent Build.... DO aoe damage rotation on AOE target dummies in Dornogal

### Player Information (Link)

https://pastebin.com/7pqPvrNf

### Error Messages (Link)

No errors

### Contact Information

FartyMcturdy#8524 - discord

**Comment by syrifgit** [comment]
Unholy still needs to be looked at in general, it's on a todo list

**Comment by syrifgit** [comment]
This ticket is around 7 versions old now an Unholy has undergone significant improvements since then.
