### ISSUE TITLE
Error "Bad Argument #1 to ipairs"

### ISSUE THREAD

**Issue by hwiegard** [Hekili/hekili#42]
Sometimes (primarily in bear form) I get the error ```bad argument #1 to 'ipairs' (table expected, got nil)``` in State.lua:2570.

**Comment by Hekili** [comment]
Thanks, working out a fix for this.  It's related to spec swapping and can be avoided by using /reloadui after swapping to/from Feral until the fix is in.  Thanks!

**Comment by Hekili** [comment]
Fixed.
