### ISSUE TITLE
Retribution AoE not using certain abilities

### ISSUE THREAD

**Issue by Nystroza** [Hekili/hekili#420]
When using the AoE rotation on retribution certain abilities seem to never show up. i tried with Cool downs on and off 

The abilities are
Consecration 
Wake of Ashes
Final Reckoning ( i was unsure if this one was supposed to show on AoE due to the passive)

Trinkets also didn't seem to work either.

**Comment by Hekili** [comment]
Please submit the information that the ticket asks you for.

Keep in mind, current beta work is focused on the features/systems; nobody really has optimized priority lists for any spec yet.  You can always tweak your own priority in /hekili > Priorities > Retribution.

**Comment by Nystroza** [comment]
Issue Report: https://pastebin.com/6v0CGFJ4
Snapshot: https://pastebin.com/vHLWavzB

**Comment by Hekili** [comment]
These all appear to be in the current priority (update and report again if needed).
