### ISSUE TITLE
[BUG] saying to use second on use trinket when not available.

### ISSUE THREAD

**Issue by N6REJ** [Hekili/hekili#4202]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I have two on-use trinkets, and its saying to use the second one when its not available due to cooldowns.

### How to Reproduce

Equip both trinkets, use 13 first then try to us
![WoWScrnShot_111624_203558](https://github.com/user-attachments/assets/9ef12beb-a65d-4cbf-b617-f4cd71fe1bca)
![WoWScrnShot_111624_203557](https://github.com/user-attachments/assets/58ab140f-99ad-4dbb-92cc-72b93b6d0712)
e 14

### Player Information (Link)

not available, see image

### Error Messages (Link)

none

### Additional Information

This happened during raid

**Comment by Hekili** [comment]
The snapshot isn't optional -- it would've taken screenshots as well.

Also, the trinket that's recommended doesn't look like it's on cooldown in your UI.  I'll take a look when you send the snapshot(s).
