### ISSUE TITLE
Sin Rogue opener Ambush logic

### ISSUE THREAD

**Issue by Bingo176** [Hekili/hekili#4203]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

With  v11.0.5-1.0.15 opener is recommending ambush from stealth 4-5 times.

![image](https://github.com/user-attachments/assets/3c57dd85-f6d8-4602-8e60-5250b6bb12c5)
Reverting this line fixed it. 

### How to Reproduce

Target dummies and open from stealth. 

### Snapshot (Link)

https://pastebin.com/mwMnbeQY

**Comment by Hekili** [comment]
This should be resolved in 1.0.15a.
