### ISSUE TITLE
Cata Marksmenship Hunter rotation 

### ISSUE THREAD

**Issue by PrimeDamage** [Hekili/hekili#4204]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

The addon is not working with my marksmanship hunter when I press the button the addon tells me to press, it shows the button toggle like I pressed it, but the rotation doesn't move at all to see what to use next. 
![2024-11-17](https://github.com/user-attachments/assets/6d0d172e-2892-40d8-8324-4d43bfa3b081)

### How to Reproduce

Get on game as marksmanship hunter. Turn on addon to marksmanship rotation. Addon doesn't move rotation at all but shows you pressed the skill button. 

### Player Information (Link)

Marksmanship; Primary - Hunter's Mark(0.00), Rapid Fire(0.00), Call of the Wild(0.00), Serpent Sting(1.39) build: v4.4.1-1.0 level: 85 (85) class: HUNTER spec: hunter  talents: aimed_shot     artisan_quiver     bestial_discipline     bombardment     careful_aim     chimera_shot     essence_of_the_viper     frenzy     go_for_the_throat     improved_stead_shot     marked_for_death     master_marksman     master_of_beasts     one_with_nature     pathing     piercing_shots     posthaste     rapid_killing     rapid_recuperation     readiness     sic_em     termination     trueshot_aura     wild_quiver  pvptalents: none  covenant: none  conduits: none  soulbinds: none  sets: none  gear: amulet_of_dull_dreaming = 1     balkars_waders = 1     belt_of_the_stargazer = 1     bloodpetal_mantle = 1     coultons_crushers = 1     darkmoon_card_hurricane = 1     elementium_scale_bracers = 1     grace_of_the_herald = 1     kaleki_cloak = 1     mainhand = 1     mainhand_2h = 1     ring_of_dun_algaz = 1     ring_of_rebellion = 1     smokeflare_chestguard = 1     sporeshot = 1     tabard_of_ramkahen = 1     torthslayers_staff = 1     treads_of_malorne = 1     wildhammer_riding_helm = 1  legendaries: none  itemIDs: 55802, 55858, 55861, 55997, 56295, 56443, 56445, 57931, 61414, 62051, 62385, 62439, 63702, 63749, 63803, 63890, 65904  settings: aoe = 2     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = false     gcd = 1494     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Marksmanship     petbased = false     potion = speed     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     usePackSelector = true     arcane_threshold = 80     assigned_aspect = aspect_of_the_hawk     beast_mastery = Beast Mastery (wowtbc.gg)     call_of_the_wild_macro = false     maintain_aspect = true     manage_mana_viper = true     marksmanship = Marksmanship (wowtbc.gg)     suggest_explosive_st = false     survival = Survival (wowtbc.gg)  toggles:     cooldowns = true      custom1 = false      custom2 = false      defensives = false      essences = false [overridden]     interrupts = false      mode = automatic      potions = false   keybinds:      aimed_shot         = 4   [01]     arcane_shot        = 3   [01]     chimera_shot       = 6   [01]     concussive_shot    = X   [06]     deterrence         = 0   [01]     disengage          = V   [06]     explosive_trap     = 8   [01]     feign_death        = F5  [06]     flare              = F2  [06]     hunters_mark       = -   [01]     kill_command       = 2   [01]     kill_shot          = E   [06]     misdirection       = SQ  [06]     multishot          = 5   [01]     rapid_fire         = =   [01]     readiness          = R   [06]     scare_beast        = SX  [06]     scatter_shot       = Z   [06]     serpent_sting      = 7   [01]     steady_shot        = 1   [01]     tranquilizing_shot = F3  [06]     trap_launcher      = T   [05]     widow_venom        = F4  [06]     wing_clip          = SZ  [06]    player_buffs:     19506 - trueshot_aura                            -   1 - 3600.00     93337 - champion_of_ramkahen                     -   1 - 3600.00     13165 - aspect_of_the_hawk                       -   1 - 3600.00  player_debuffs:  target_auras:  target does not exist   New Recommendations for [ Primary ] requested at 17:22:53 ( 82858.87 ); using built-in ( Marksmanship ) priority. *** START OF NEW DISPLAY: Primary ***  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: focus[ 100.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Marksmanship - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   hunters_mark ( precombat - 2 )         The action (hunters_mark) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).          - this entry's criteria PASSES: down[true]         Action chosen:  hunters_mark at 0.00!          Completed precombat action list [ Marksmanship - precombat ].     Recommendation is hunters_mark at 0.00 + 0.00.     Recommendation #1 is hunters_mark at 0.00s (0.00s).  RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.39, Casting: 0.00 ).      Resources: focus[ 100.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Marksmanship - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   hunters_mark ( precombat - 2 )         The action (hunters_mark) is usable at (0.00 + 1.39).          - the action is ready before the current recommendation (at +1.39 vs. +10.00).          - this entry's criteria FAILS: down[false]         There were no recheck events to check.         Time spent on this action:  0.08ms         TimeData:Marksmanship-precombat-2:hunters_mark:0.08:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)          Completed precombat action list [ Marksmanship - precombat ].          Processing default action list [ Marksmanship - default ].                  Current recommendation was NO ACTION at +10.00s.                  2.   run_action_list:aoe ( default - 1 )         Criteria for aoe FAIL at +0.00 - active_enemies[1.00] >= 2                  3.   run_action_list:st ( default - 2 )         There is no criteria for st.         Action list (st) was found.         + [st]         Current recommendation was NO ACTION at +10.00s.                  4.   steady_shot ( st - 1 )         The conditions for this entry contain an error.  Skipping.         Time spent on this action:  0.02ms         TimeData:Marksmanship-st-1:steady_shot:0.02:Ability Known, Enabled(0.02)                  5.   hunters_mark ( st - 3 )         The action (hunters_mark) is usable at (0.00 + 1.39).          - the action is ready before the current recommendation (at +1.39 vs. +10.00).         List ( st ) called from ( Marksmanship:default:2 ) would PASS at 1.39.         NONE          - this entry's criteria FAILS: down[false]         There were no recheck events to check.         Time spent on this action:  0.09ms         TimeData:Marksmanship-st-3:hunters_mark:0.09:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)                  6.   rapid_fire ( st - 4 )         The action (rapid_fire) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( st ) called from ( Marksmanship:default:2 ) would PASS at 0.00.         NONE          - this entry's criteria PASSES: buff.rapid_fire.down[true]         Action chosen:  rapid_fire at 0.00!         Returned from list (st), current recommendation is rapid_fire (+0.00).         - [st]         Resetting delayMin to 0.00 from 0.00.         Added st to blocklist as it was called via RAL.          Completed default action list [ Marksmanship - default ].     Recommendation is rapid_fire at 0.00 + 0.00.     Recommendation #2 is rapid_fire at 0.00s (0.00s).  RECOMMENDATION #3 ( Offset: 0.00, GCD: 1.39, Casting: 0.00 ).      Resources: focus[ 100.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Marksmanship - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   hunters_mark ( precombat - 2 )         The action (hunters_mark) is usable at (0.00 + 1.39).          - the action is ready before the current recommendation (at +1.39 vs. +10.00).          - this entry's criteria FAILS: down[false]         There were no recheck events to check.         Time spent on this action:  0.08ms         TimeData:Marksmanship-precombat-2:hunters_mark:0.08:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)          Completed precombat action list [ Marksmanship - precombat ].          Processing default action list [ Marksmanship - default ].                  Current recommendation was NO ACTION at +10.00s.                  2.   run_action_list:aoe ( default - 1 )         Criteria for aoe FAIL at +0.00 - active_enemies[1.00] >= 2                  3.   run_action_list:st ( default - 2 )         There is no criteria for st.         Action list (st) was found.         + [st]         Current recommendation was NO ACTION at +10.00s.                  4.   steady_shot ( st - 1 )         The conditions for this entry contain an error.  Skipping.         Time spent on this action:  0.01ms         TimeData:Marksmanship-st-1:steady_shot:0.01:Ability Known, Enabled(0.01)                  5.   hunters_mark ( st - 3 )         The action (hunters_mark) is usable at (0.00 + 1.39).          - the action is ready before the current recommendation (at +1.39 vs. +10.00).         List ( st ) called from ( Marksmanship:default:2 ) would PASS at 1.39.         NONE          - this entry's criteria FAILS: down[false]         There were no recheck events to check.         Time spent on this action:  0.08ms         TimeData:Marksmanship-st-3:hunters_mark:0.08:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)                  6.   rapid_fire ( st - 4 )         The action is not ready ( 180.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Marksmanship-st-4:rapid_fire:0.01:Ability Known, Enabled(0.01)                  7.   call_of_the_wild ( st - 5 )         The action (call_of_the_wild) is usable at (0.00 + 0.00).          - the action is ready before the current recommendation (at +0.00 vs. +10.00).         List ( st ) called from ( Marksmanship:default:2 ) would PASS at 0.00.         NONE          - this entry's criteria PASSES: buff.call_of_the_wild.down[true]         Action chosen:  call_of_the_wild at 0.00!         Returned from list (st), current recommendation is call_of_the_wild (+0.00).         - [st]         Added st to blocklist as it was called via RAL.          Completed default action list [ Marksmanship - default ].     Recommendation is call_of_the_wild at 0.00 + 0.00.     Recommendation #3 is call_of_the_wild at 0.00s (0.00s).  RECOMMENDATION #4 ( Offset: 0.00, GCD: 1.39, Casting: 0.00 ).      Resources: focus[ 100.00 / 100.00 ]     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Marksmanship - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   hunters_mark ( precombat - 2 )         The action (hunters_mark) is usable at (0.00 + 1.39).          - the action is ready before the current recommendation (at +1.39 vs. +10.00).          - this entry's criteria FAILS: down[false]         There were no recheck events to check.         Time spent on this action:  0.08ms         TimeData:Marksmanship-precombat-2:hunters_mark:0.08:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.00):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)          Completed precombat action list [ Marksmanship - precombat ].          Processing default action list [ Marksmanship - default ].                  Current recommendation was NO ACTION at +10.00s.                  2.   run_action_list:aoe ( default - 1 )         Criteria for aoe FAIL at +0.00 - active_enemies[1.00] >= 2                  3.   run_action_list:st ( default - 2 )         There is no criteria for st.         Action list (st) was found.         + [st]         Current recommendation was NO ACTION at +10.00s.                  4.   steady_shot ( st - 1 )         The conditions for this entry contain an error.  Skipping.         Time spent on this action:  0.01ms         TimeData:Marksmanship-st-1:steady_shot:0.01:Ability Known, Enabled(0.01)                  5.   hunters_mark ( st - 3 )         The action (hunters_mark) is usable at (0.00 + 1.39).          - the action is ready before the current recommendation (at +1.39 vs. +10.00).         List ( st ) called from ( Marksmanship:default:2 ) would PASS at 1.39.         NONE          - this entry's criteria FAILS: down[false]         There were no recheck events to check.         Time spent on this action:  0.08ms         TimeData:Marksmanship-st-3:hunters_mark:0.08:Ability Known, Enabled(0.01):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post-Recheck Times(0.01):Post Recheck(0.00)                  6.   rapid_fire ( st - 4 )         The action is not ready ( 180.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Marksmanship-st-4:rapid_fire:0.01:Ability Known, Enabled(0.01)                  7.   call_of_the_wild ( st - 5 )         The action is not ready ( 300.00 ) before our maximum delay window ( 10.00 ) for this query.         Time spent on this action:  0.01ms         TimeData:Marksmanship-st-5:call_of_the_wild:0.01:Ability Known, Enabled(0.01)                  8.   potion ( st - 6 ) - ability disabled ( toggle )         Time spent on this action:  0.02ms         TimeData:Marksmanship-st-6:potion:0.02:Ability Known, Enabled(0.02)                  9.   use_items ( st - 7 )         There is no criteria for Use Items.         + [st], items         Current recommendation was NO ACTION at +10.00s.         Returned from Use Items; current recommendation is NO ACTION (+10.00).         - items                  10.  hyperspeed_acceleration ( st - 8 ) - item [ 0 ] missing         Time spent on this action:  0.02ms         TimeData:Marksmanship-st-8:hyperspeed_acceleration:0.02:Ability Known, Enabled(0.02)                  11.  kill_shot ( st - 9 )         The action (kill_shot) is unusable at (0.00 + 1.39) because enemy health must be below 20 percent.         Time spent on this action:  0.06ms         TimeData:Marksmanship-st-9:kill_shot:0.06:Ability Known, Enabled(0.02):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.00)                  12.  serpent_sting ( st - 10 )         The action (serpent_sting) is usable at (0.00 + 1.39) with cost of 25 focus.          - the action is ready before the current recommendation (at +1.39 vs. +10.00).         List ( st ) called from ( Marksmanship:default:2 ) would PASS at 1.39.         NONE          - this entry's criteria PASSES: debuff.stings.down[true]         Action chosen:  serpent_sting at 1.39!         Time spent on this action:  0.14ms         TimeData:Marksmanship-st-10:serpent_sting:0.14:Ability Known, Enabled(0.02):Post-TTR and Essential(0.05):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.02):Post Stack(0.01):Pre-Script(0.00):Post-Script(0.01):Pre-Recheck(0.01):Post Recheck(0.00):Action Stored(0.01)         The recommended action (serpent_sting) is ready within the active GCD; exiting list (st).         Returned from list (st), current recommendation is serpent_sting (+1.39).         - [st]         Added st to blocklist as it was called via RAL.          Completed default action list [ Marksmanship - default ].     Recommendation is serpent_sting at 0.00 + 1.39.     Recommendation #4 is serpent_sting at 1.39s (1.39s).     Time spent generating recommendations:  2.30ms

### Error Messages (Link)

no error message

**Comment by Hekili** [comment]
When your snapshot was taken, the addon doesn't see that you have a target at all.  Therefore, Hunter's Mark is down.  I don't know if "soft targeting" or "action targeting" is happening in Cataclysm, but the targeting settings warns that it's not compatible with the addon.
