### ISSUE TITLE
[REC] Death Sweep / Blade dance doesn't check melee range =\

### ISSUE THREAD

**Issue by zZzProstudazZz** [Hekili/hekili#4205]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Havoc

### Describe the Issue

Hello guys! Just wondering is it possible to make DH check for being in melee range for use Death Sweep / Blade Dance or even if  some enemy targets in radius 3-4 yards? Cuz almost always while I'm being out of range and rotation advice me to use Death Sweep / Blade Dance it's being useless =\ no one got even a hit from me

### How to Reproduce

Mb improove it somehow like doesn't advice to use Death Sweep / Blade Dance if nobody around you or you far from you target

### Snapshot (Link)

https://pastebin.com/ZaKj50t4

**Comment by Hekili** [comment]
It doesn't.  The addon generally doesn't range check abilities that don't technically have (via the WoW API) a maximum range.  When it says you want to Death Sweep / Blade Dance, the implication is that you should *get in range* and use it.

**Comment by zZzProstudazZz** [comment]
Well the thing is they I try to be in melee range, but most often Death Sweep / Blade Dance is used immediately after Vengeful Retreat :(( as you understand, after Vengeful Retreat I can not be in the melee range in any way =\

**Comment by syrifgit** [comment]
Then you are using Vengeful retreat incorrectly. I would check on YouTube for some Havoc DH guides and how to properly angle your dashes so that you never leave melee range.

Here is a good one: https://www.youtube.com/watch?v=PGK79kIeyPk&t=45s

**Comment by zZzProstudazZz** [comment]
Got you, will try, thanks
