### ISSUE TITLE
[REC] Assa Rogue m+ 1 shiv kingsbane issue

### ISSUE THREAD

**Issue by yokaii4** [Hekili/hekili#4206]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

After the newest update, while playing m+ build with assa rogue (1 shiv charge) the addon suggest to use shiv and thistle tea before sending kingsbane, while it should be used during the last 7-8s while playing with 1 charge. I have also noticed that Skardyn's grace is recommended way before deathmark so we risk losing its buff  while in deathmark kingsbane CDs

The snapshots provided should be able to highlight both the shiv and trinket issue

NOTE: I'm aware that the APL suggests from some reason that shiv should be casted before kingsbane, however you can check all the guides that contradicts this + kingsbane does more DPS in its latter half so it is a DPS loss. I guess that the APL just take the ST rotation and misplace the only shiv you have because it considers it 1/2 charges

### How to Reproduce

1. enter game as assa rogue
2. practice with dummies using the m+ build (1 shiv charge)
3. execute the rotation

### Snapshot (Link)

https://pastebin.com/tq5vj3Mr    https://pastebin.com/C2FKaLHX

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/cfheoa2QDDiPV7Np5SUnVn

### Contact Information

yokaii__

**Comment by syrifgit** [comment]
Sounds like this is worth bringing up to the Rogue APL writers in the Rogue discord. I will take a look eventually, but you should ask them about it too.

**Comment by yokaii4** [comment]
I will, in addition, you could check the correct kingsbane timings thanks to this WA: https://wago.io/OtohaQlq-

Also skardyn's Grace should be used with Deathmark too. Is this hekili's issue or is this something we should bring to the APL writers too?

NOTE: the WA sent tracks only during kingsbane so in case of ST build it can't track the first shiv we send

**Comment by fzarr** [comment]
For skardyn's I just remove it from the addon's ability list and macro it into deathmark.

I already researched the shiv thing and the APL is a dps loss but not as much as it sounds like it would be, something like 0.3-0.5% dps. This was already raised in the discord but it doesnt look like its something they care to address.

I manually alter the addon priority list by adding a condition to the shiv fallback line to only work if you have lightweight shiv talented:

`actions.stealthed+=/shiv,if=talent.kingsbane&(dot.kingsbane.ticking|cooldown.kingsbane.up)&(!debuff.shiv.up&debuff.shiv.remains<1)&buff.envenom.up`

to

`actions.stealthed+=/shiv,if=talent.kingsbane&(dot.kingsbane.ticking|cooldown.kingsbane.up)&(!debuff.shiv.up&debuff.shiv.remains<1)&buff.envenom.up&talent.lightweight_shiv.enabled`

**Comment by yokaii4** [comment]
Hey @syrifgit apparently it is an unfixed issue but as fzarr said maybe they do not care to fix it since the dps loss is marginal (but still it's more dps for free so why not) about Skardyn, I would just sync it with deathmark or follow what fzarr said above

**Comment by yokaii4** [comment]
@fzarr where do you change the lightweight shiv line specifically?

**Comment by fzarr** [comment]
I don't have access to the game atm but its under one of the 'assassination' sections in the left panel, there should be a tab that says priority or action list or something and it has the simcraft APL in a text editor pane. You can modify the line within that APL (might be easier to copy it into a text editor and paste it back into) then you click accept, and then import. You may need a reload too. You can revert any manual changes made to the apl by clicking a circular undo arrow in one of the tabs somewhere.

**Comment by yokaii4** [comment]
> I don't have access to the game atm but its under one of the 'assassination' sections in the left panel, there should be a tab that says priority or action list or something and it has the simcraft APL in a text editor pane. You can modify the line within that APL (might be easier to copy it into a text editor and paste it back into) then you click accept, and then import. You may need a reload too. You can revert any manual changes made to the apl by clicking a circular undo arrow in one of the tabs somewhere.

found it thank you! Although for better accessibility for everyone this is something that could be officially done, what do you think? @syrifgit

**Comment by Ltz-lab** [comment]
> For skardyn's I just remove it from the addon's ability list and macro it into deathmark.
> 
> I already researched the shiv thing and the APL is a dps loss but not as much as it sounds like it would be, something like 0.3-0.5% dps. This was already raised in the discord but it doesnt look like its something they care to address.
> 
> I manually alter the addon priority list by adding a condition to the shiv fallback line to only work if you have lightweight shiv talented:
> 
> `actions.stealthed+=/shiv,if=talent.kingsbane&(dot.kingsbane.ticking|cooldown.kingsbane.up)&(!debuff.shiv.up&debuff.shiv.remains<1)&buff.envenom.up`
> 
> to
> 
> `actions.stealthed+=/shiv,if=talent.kingsbane&(dot.kingsbane.ticking|cooldown.kingsbane.up)&(!debuff.shiv.up&debuff.shiv.remains<1)&buff.envenom.up&talent.lightweight_shiv.enabled`

this is huge and i have been complaining/asking about it for awhile. works well

**Comment by fzarr** [comment]
Just FYI there might be occasions where this fix causes shiv not to be recommended when it should - im guessing this line is added to force shiv to be used in some situations, but I don't know enough about when it might not be used without it. I use a separate kingsbane tracker weakaura and have noticed it not always agree with hekili but not investigated further yet.

**Comment by yokaii4** [comment]
UPDATE AFTER [v11.0.5-1.0.16]: 

I confirm what fzarr said that even after the update sometimes shiv does not get recommended. It mostly happens when deathmark is on cd and we use kingsbane only. It does happen quite randomly so it's very hard to replicate but I suppose it's a clash between the suggestions leading up to that kingsbane only window.

**Comment by syrifgit** [comment]
Given that this is 4 version old and doesn't disagree with the APL, I am closing it.
