### ISSUE TITLE
Border Thickness on Icons

### ISSUE THREAD

**Issue by j-mes** [Hekili/hekili#421]
> Please describe your idea or feature and when it would be useful.

ElvUI as an user interface addon which is used by a lot of people, I feel that having options to specify the border thickness would be great to have in Hekili. Currently, it only has 1px border thickness, while ElvUI has `thin`, `2px`, `default` and `thick` options for when it comes to setting the thickness with icons and other various elements that make up an user interface.

My proposal is whenever it is possible to offer an option where people can decide the thickness of the border for the icons that show up in Hekili. As for when... only if it's not a big thing to implement, and please only at your own convenience. I'd not consider this to be a ground-breaking change but more of a 'nice to have' feature/option.

Lastly, I'd like to say, that this is a great addon and it helps with keeping the rotation tidy while allowing me to have much better awareness around in mythic raids at the same time.

**Comment by Crelam** [comment]
Isn't that functionality gained by applying different Masque skins to the icons?  Hekili already has Masque support, have you tried any different skins?

**Comment by j-mes** [comment]
I can explore Masque if they have the theme that I would use, however is it another dependency to have to achieve something whenever it could be implemented in Hekili itself since there is an option to have a border or not?

Again, only at your discretion 😄

**Comment by Hekili** [comment]
This will be available in Shadowlands, but it's a very simplistic implementation.

**Comment by j-mes** [comment]
Thank you for clarifying this and looking to implement something for Shadowlands @Hekili 😄
