### ISSUE TITLE
Spellflash doesn't work with the spell Tempest. Enhancement Shaman.

### ISSUE THREAD

**Issue by Narzogg** [Hekili/hekili#4211]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hi, 
When i use spellflash with my enchancement shaman, it doesn't spellflash the spell Tempest when i need to press it. It works really well with every other spell but not this one.

### How to Reproduce

1. Load the game as an enhancement shaman 2. Enable spellflash in Hekili 3. Hit a dummy and notice that it doesn't flash Tempest even when it is recommended by the addon. 

### Player Information (Link)

Enhancement; Primary - Tempest(0.00), Flame Shock(1.21), Crash Lightning(2.41)

### Error Messages (Link)

https://pastebin.com/6kxQ4erg

**Comment by syrifgit** [comment]
Duplicate, make sure to check existing tickets first.
