### ISSUE TITLE
[REC] Issue with Primordial Wave/Lightning Bolt combo Enhance Shaman

### ISSUE THREAD

**Issue by Tjkrafty** [Hekili/hekili#4212]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

Not recommending to use Lightning bolt at 8 Stacks of Maelstrom when Primordial wave buff(Your next Lightning Bolt will also hit all targets affected by your Flame Shock for 175% of normal damage)is present during AOE pulls. All targets almost always have flameshock present so might as well ignore that part. This is also on icy-veins storm mythic+/ aoe, with aoe rotation selected.

### How to Reproduce

get 8 stacks with primordial wave active at training dummies or in any aoe pull

### Snapshot (Link)

https://pastebin.com/qefYRE4s

### Contact Information

Tyler#1102

**Comment by syrifgit** [comment]
You have 10 maelstrom weapon in this snapshot, not 8, which causes flame shock to not be chosen. It considers spending that maelstrom weapon to be a higher priority to not overcap.
