### ISSUE TITLE
[REC] Balance KOTG Treant Desync and Spymaster Web Logic

### ISSUE THREAD

**Issue by yokaii4** [Hekili/hekili#4214]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Druid - Balance

### Describe the Issue

After the 1st treant + incarn, it seems that there's a slight desync in the recommendations that cause treants to be suggested way before the next incarn. Also, it's quite weird how the spymaster logic works: the addon tries to suggest it during the 1st incarn but the suggestion quickly disappears, then it directly suggests its usage at 40 stacks or so. While the stack required is fight dependant, guides suggest to use the trinket during the 2nd or 3rd incarn so I'm guessing the stacks will be around 30 by that time

### How to Reproduce

1 enter game as balance druid
2 use KOTG m+ build
3 go on dummies and do the first incarn
4 wait until 2nd incarn is suggested and notice the desync with treant

### Snapshot (Link)

this one is for the spy rec then as soon as we start the fight it disappears: https://pastebin.com/NLFwABer 

https://pastebin.com/AS2FD047

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3XcBgSm5vgTToY5fcJTZBf

### Contact Information

yokaii__

**Comment by yokaii4** [comment]
Note: notice how in the sim the APL suggests the spy usage at around 42s, which should be during our 2nd incarn and then tries to follow this 42s mark throughout the sim. Not sure though if spymaster is a trinket that works well with Hekili since it could be situational and maybe impossible for the addon to implement correctly

**Comment by syrifgit** [comment]
That's not a snapshot, that's just your sim link twice

**Comment by yokaii4** [comment]
> That's not a snapshot, that's just your sim link twice

fixed my bad

**Comment by syrifgit** [comment]
Working correctly as per the sims. Could add a boss tag to the fight_Remains entry on Default:7 to stop it from triggering early on dummies and trash packs. In a raid environment it should work as intended.
