### ISSUE TITLE
[REC] Issue when choice node is swapped but apply changes is cancelled

### ISSUE THREAD

**Issue by Bissell15** [Hekili/hekili#4215]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

The addon will take abilities out of the recommendations if you swap a choice node with something that removes that ability (i.e. Flowing Spirits/Witch Doctor's Ancestory or Radiant Glory) but after clicking "apply changes" your cast gets cancelled. So you have wolves but the addon doesn't recommend pressing it. This is resolved with a reload UI and recommends wolves again. I see the same thing on my Ret Paladin with the remove wings talent.

### How to Reproduce

1. Be an indecisive Shaman or Paladin that can't decide whether or not they want to press their buttons.
2. decide you don't want to press your buttons and change your talent selection.
3. Click apply but change your mind again and cancel the cast.
4. Get recommended abilities as if you hadn't cancelled the cast until you reload your UI.

### Snapshot (Link)

https://pastebin.com/4pBBySat

### Contact Information

@bissell in Earthshrine discord

**Comment by syrifgit** [comment]
Probably not much you can do there except reload.
