### ISSUE TITLE
[REC] Sin Rogue Envenom Stacks issue, maybe?

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#4216]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

I was mentioned to a friend that Hekili wasn't tracking Evenom stacks correctly, so I took a look and I'm not entirely sure what I am looking at but the Envenom stack in value is not what I see on weak auras or at all on the remaining time in game.

For example, it's saying max_stacks_remains = 4.7 but while I'm at 2 max stacks I have 1 second left before going into 1 stack. Now this isn't always returning values like that. Sometimes it is correct and is reading the lowest stack remaining time. I hope this shows in the Snapshot, took me a few attempts to capture stuff. Also have screenshot because it might not show what I am referring to and just look that it should be pressing that because of upper limit energy. But I am only talking about the remaining time is showing something different occasionally (not always).
![dsadsa](https://github.com/user-attachments/assets/3731e178-a2d6-4704-9853-9a893523e551)
I will say it again. I am referring to the remaining time is not matching. Not that it should be or not recommending it. Because max_stacks is ending in roughly 2 seconds according to weak auras but it returns not that.

Unless this is how it's supposed to be? All I know is according to the dev apl for sin rogue is that the apl tracks the lowest stack of the two to clip

### How to Reproduce

1. /hek
2. action list - default
3. 5. variable clip envenom
4. look at remaining time in value while following rotation. Sometimes it shows correct, sometimes not.

### Snapshot (Link)

https://pastebin.com/ckx0q81T

### Additional Information

Please let me know if I pressed the pause at the wrong time but screenshot also has what I am referring to.

**Comment by Smudgiee** [comment]
And yes I was moving my mouse on and off the value for it to update value for screenshot

**Comment by syrifgit** [comment]
This is still being iterated on. More changes are coming eventually.

**Comment by Smudgiee** [comment]
Oh okay :). Wasn't too sure just saw a change for it sometime ago so I thought it was fully implemented.

**Comment by Smudgiee** [comment]
If possible can you update/reply to this when this gets looked at? please, or just close it when looked at whenever that is. I miss GitHub updates sometimes but got a notification when you replied to this.

**Comment by syrifgit** [comment]
Update your addon to .17

**Comment by Smudgiee** [comment]
I updated the addon to .17 and the timer is still off. Do you want another snapshot? 
![1111111](https://github.com/user-attachments/assets/e9ca82dd-99ac-43bf-8778-9e1c9f50101f)

**Comment by Smudgiee** [comment]
https://pastebin.com/91A8PWi0 I hope I caught it in this pause with the first icon being envenom. But in that screenshot the timer is way off as I had 11 sec of envenom, confirmed from buff at top right of wow and 2 seconds on the stack but it shows 4.51. Though I noticed with that weak aura it seems 1 sec higher than what is actually on as it doesn't show below 1 like 0.xx, just ends at the end of 1. Not that matters but thought to mention as with 2 seconds left, its less than 2 seconds as it its not doing 1.4 etc
