### ISSUE TITLE
[Setting] How do i remove the buffs from the middle of my screen

### ISSUE THREAD

**Issue by Dixy-Rekt** [Hekili/hekili#4217]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

How do i remove the buffs from the middle of my screen

### How to Reproduce

![image](https://github.com/user-attachments/assets/4b37f40f-83c2-42b6-a89b-685a57109326)

### Player Information (Link)

none

### Error Messages (Link)

none

**Comment by syrifgit** [comment]
If that's even Hekili, just open your settings and move it, or type `/hek move`

**Comment by Dixy-Rekt** [comment]
That worked. Thanks!
