### ISSUE TITLE
[FEATURE] Scalecommander Bombardments target switch

### ISSUE THREAD

**Issue by N30Exca** [Hekili/hekili#4219]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I would suggest for Augumentation ad Devastation to add a target switch marker in aoe situations when scalecommander is selected as hero talent the current target is already debuffed with Bombardments and an additional mass eruption/disintegration charge is active.

### Additional Information

This addition would simplify the handling of Bombardments debuffs in AoE and increase DPS as Breath of Eons and Deep Breath would recharge faster.
In AoE this is something that should be done anyway and the current version of the Addon does not suggest this.

**Comment by syrifgit** [comment]
Notes from Kaz on discord 

Sure thing, the basic concept is : 
* it applies for dev and aug when Scalecommander hero talent is chosen
* when we cast an empower spell we gain a stack of Mass Eruption (Aug, id : 438588) or Mass Disintegrate (Dev, id : 436336), max 2
* when we use one of those stacks it triggers a bombardment on the target
* when we have two stacks and there are at least 2 enemies we should use a stack on each enemy to spread bombardments

So for Aug it would show on the second Eruption when you have two stacks and at least two targets and for Dev it would show on the second Disintegrate with the same conditions
