### ISSUE TITLE
Balance druid rotation sugesstion

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#422]
After testing new alpha build i think balance druid need's lite tweek on rotation. 

In single target scenario, 95% starsurge should be used durning solar eclipse and only 1/2 time durning lunar eclipse to avoid AP capping. Dots should be refreshed before entering eclipse (only if dots time remaining less than solar eclipse duration) for min/max dps on single target

In Multi-Target scenario:
(2-3 targets ): most AP should be spend to starsurge durning lunar eclipse and 1/2 durning solar eclipse for avoid AP capping 

(4+ targets) targets all AP Should go to Starfall (eclipse here doesn't matter), 2 solar wraths should be recommended to reset lunar eclipse, but durning solar eclipse only starfire should be recommended. During lunar eclipse dot's refresh rate is fine, because most dmg on 4+ targets going from starfall.

**Comment by Hekili** [comment]
Haha, yes, priority lists are nowhere near finalized but it was previously wasting a LOT of AP.

I'd recommend toying with your priority in-game and see if you come up with a result that feels better.  We'll need to wait until profiles for shadowlands can be simmed with meaningful results for comparing performance later.
