### ISSUE TITLE
Protection Paladin : Lay on Hands being suggested when it's on CD ( only when playing Empyreal Ward talent)

### ISSUE THREAD

**Issue by PvpSpells** [Hekili/hekili#4222]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Protection

### Describe the Issue

Addon suggests Lay on Hands even when it’s on cooldown after picking the talent.

### How to Reproduce

1)Log into the game as Protection Paladin.
2)Select Lay on Hands and the Empyreal Ward talent. 
3)Use Lay on Hands to put it on cooldown. (have a condition like health.pct < 90 for it)
4)Drop HP below 905 and you will see the addon still suggests LoH while it's on cooldown.

### Snapshot (Link)

https://pastebin.com/ynknAcDs

**Comment by syrifgit** [comment]
Will investigate tomorrow. If you want to save me some time:

- What is the normal CD of lay on hands
- what things reduce it? Either through base cooldown or by granting CDR (like +5 seconds for casting spell X)

**Comment by PvpSpells** [comment]
[Lay on Hands] (base ability, spell ID: 633) has a 7-minute cooldown. However, most Protection builds opt for the [Unbreakable Spirit] (talent ID: 114154), which reduces the cooldown by 30%, bringing it down to 4.9 minutes.

The [Tirion's Devotion] (talent ID: 392928) further reduces the cooldown of Lay on Hands by 1 second for every Holy Power spent.

In patch 11.0.5, [Empyreal Ward] (talent ID: 387791) turned Lay on Hands into a core defensive cooldown. This talent also changes the base ability’s spell ID from 633 to 471195.

Also, the LIGHTSMITH hero tree includes the talent [Laying Down Arms] (talent ID: 432866), which reduces the cooldown of Lay on Hands by 15 seconds each time Armament fades from you.

**Comment by masterkain** [comment]
I have the same problem but not limited to Lay on Hands, happens also with Guardian of Ancient Kings / Guardian of the Forgotten Queen (pvp)
Also Ardent Defender is barely recommended, in general it seems the addon is waiting for the automatic Gift of the Golden Val'kyr before starting recommending these defensives

**Comment by PvpSpells** [comment]
> I have the same problem but not limited to Lay on Hands, happens also with Guardian of Ancient Kings / Guardian of the Forgotten Queen (pvp) Also Ardent Defender is barely recommended, in general it seems the addon is waiting for the automatic Gift of the Golden Val'kyr before starting recommending these defensives

What you're describing doesn't seem to be the same issue. It appears to be a priority issue. If you don't like the default priority, you can adjust it to suit your preferences. That said, I highly recommend disabling automatic use of defensives like [Divine Shield], [Blessing of Protection], [Ardent Defender], [Blessing of Spellwarding], and [Guardian of Ancient Kings], and instead using them based on your own decision when needed. Lay on Hands is a rudimentary cooldown whose sole purpose is to restore your health when you fall below a certain percentage, typically as a backup if Word of Glory is unavailable so it can be scripted.

The issue in this ticket is that the addon assumes Lay on Hands is always off cooldown after selecting the Empyreal Ward talent.

---
Update: You are right btw, I just always turn those CDs off, so I didn't run into the same issue with them, I just tried them out and realized, anyhow it should probably be fixed already for the next update.

**Comment by syrifgit** [comment]
Change incoming that addresses everything mentioned except the armaments thing from laying down arms talent, that will be part of a larger pass over the spec.
