### ISSUE TITLE
[REC] Frost Death Knight recommending doing nothing instead of Frost Strike during POF to Generate runes for Obliterate

### ISSUE THREAD

**Issue by K1NG-1337** [Hekili/hekili#4223]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Frost

### Describe the Issue

At times during Pillar of Frost, when I don't have enough runes for Obliterate, the addon recommends standing around and doing nothing waiting for runes to generate instead of using frost strike.

### How to Reproduce

1. Enter game as frost dk
2. Go into a fight and use the pillar of frost + RM outside of BoS opener
3. Follow standard rotation until it produces the issue.

### Snapshot (Link)

https://pastebin.com/Q81Lvjbd

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/5hNeJ4EmiPFaxVjuk7jNZG

### Additional Information

Additional snapshot: https://pastebin.com/qMK7qmTC

### Contact Information

Discord: the.k1ng

**Comment by syrifgit** [comment]
Looks like it thinks you can cast it with 1 rune without exterminate. Will look into it tomorrow.

**Comment by AlexOneMercer** [comment]
I often encounter the same issue in my recent mythic+ games.

**Comment by syrifgit** [comment]
This should now be resolved on the newest update.
