### ISSUE TITLE
[BUG] The entire sequence disappeared

### ISSUE THREAD

**Issue by AlexOneMercer** [Hekili/hekili#4225]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

It only happened when I play Frost DK. I also play a Retribution Paladin.  The entire recommended casting sequence disappears when casting Breath of Sindragosa and engaging Haste. The entire frame disappears completely and then appears for half a second  , and then disappears again.

### How to Reproduce

Play as Frost DK. Cast breath of sindragosa with high haste or heroism.

### Player Information (Link)

https://pastebin.com/f0kQHq7f

### Error Messages (Link)

Hekili: Unable to make recommendation for Primary #1; triggering automatic snapshot

**Comment by bjth** [comment]
Can you post the snapshot in a pastebin and attach the link to the ticket please.

**Comment by AlexOneMercer** [comment]
> Can you post the snapshot in a pastebin and attach the link to the ticket please.

https://pastebin.com/f0kQHq7f, does this one work?

**Comment by syrifgit** [comment]
This is 2 versions old and I believe updates were made to DK. If the issue persists, open a new ticket with a new snapshot.
