### ISSUE TITLE
[FEATURE] Autohide bars

### ISSUE THREAD

**Issue by fuddlesworth** [Hekili/hekili#4228]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'm using ELVUI and some of the functionality is hiding the user/target bars and action bars while not in combat or if you don't have a target.

It would be nice if Hekilli provided similar functionality.

**Comment by syrifgit** [comment]
This already exists.

![image](https://github.com/user-attachments/assets/340baffd-34ad-41a6-8fb9-e2a9aa3c4306)
