### ISSUE TITLE
[BUG] all combo point builder is being recommended as fan of knives only. Rogue

### ISSUE THREAD

**Issue by xdownbeatx** [Hekili/hekili#4229]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

I am constantly being told to use fan of knives in all situations, even in pure st add-on will not suggest using mutilate more than once.
![111113333](https://github.com/user-attachments/assets/b6c0f957-52d8-41e6-8c81-c3be3e2379d8)

### How to Reproduce

Enter the game as a rogue and go attack a ST dummie and it should replicate it

### Player Information (Link)

https://pastebin.com/L20nKcPg

### Error Messages (Link)

NA

### Additional Information

I hope everything is included correctly. this is my first time posting here so I hope it's all good. 

here is a quick sim https://www.raidbots.com/simbot/report/o6ezkqHTG7B1vPET32gk4H 

### Contact Information

Downbeat in discord.

**Comment by xdownbeatx** [comment]
https://pastebin.com/fJ5K77Mn

**Comment by xdownbeatx** [comment]
That is a second paste that may be more accurate

**Comment by syrifgit** [comment]
Take the snapshot when it's actually showing fan of knives. Both of those aren't even in combat.

**Comment by xdownbeatx** [comment]
They are both in combat?

**Comment by xdownbeatx** [comment]
I'll go to a dummy and see if I can get it going again after this heroic run

**Comment by syrifgit** [comment]
Then something is very wrong if it's telling you to cast stealth while in combat

**Comment by xdownbeatx** [comment]
https://pastebin.com/PfYw8NcP

**Comment by xdownbeatx** [comment]
this is while im hitting a target so unless I don't understand how to get a in combat one it should be

**Comment by xdownbeatx** [comment]
I may have solved it. if deadly poison isn't on it only shows Fan of Knives.

**Comment by 825i** [comment]
Yeah I am getting the exact same problem, it is recommending Fan of Knives over and over. It is also recommending me Thistle Tea THREE times in a row... back to back when I have 90% energy also.

**Comment by El0quenz** [comment]
> I may have solved it. if deadly poison isn't on it only shows Fan of Knives.

Dude, thank you so much. I was going crazy about that issue; turns out I wasn't using Deadly Poison. You were correct; once I applied it, it finally shows Multilate in the Prio. 
Thanks again!
