### ISSUE TITLE
Blood DK Death Strike Entry in Profile

### ISSUE THREAD

**Issue by nyteghost** [Hekili/hekili#423]
- Go to Priorities
- Click on Profile
- Scroll down to # Incoming damage requirement is 25% of max health solo, 50% of max health in a group.
- See below for the entry

# Incoming damage requirement is 25% of max health solo, 50% of max health in a group.
actions.mitigation+=/death_strike,if=incoming_damage_5s>=0.5*health.max|(!group&incoming_damage_5s>=0.25*health.max)

Looking at this, shouldn't it be;
   actions.mitigation+=/death_strike,if=incoming_damage_5s>=0.25*health.max|(!group&incoming_damage_5s>=0.5*health.max)

since !group is when you are in a group. Or am i reading this wrong and !group means you're not in a group?

**Comment by Hekili** [comment]
`!` means `not`.  So yeah, the existing logic is "any time damage in past 5 seconds is > 50% or if you're solo and damage is > 25%".

**Comment by nyteghost** [comment]
> 
> 
> `!` means `not`. So yeah, the existing logic is "any time damage in past 5 seconds is > 50% or if you're solo and damage is > 25%".

Thank you very much. I am still learning lua, so much appreciated :)

**Comment by Hekili** [comment]
In that case, be careful.  ! is used as "not" in SimC's syntax, which the addon invisibly translates to Lua.

**Comment by nyteghost** [comment]
Okay thank you so much!
