### ISSUE TITLE
[FEATURE] Frame Strata

### ISSUE THREAD

**Issue by S4mmis** [Hekili/hekili#4230]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Would it be possible to get the option to change Frame Strata?

**Comment by syrifgit** [comment]
It already exists under display settings in the very first tab
