### ISSUE TITLE
Importer un profil de rotation Monk heal

### ISSUE THREAD

**Issue by praxitian** [Hekili/hekili#4231]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Windwalker

### Describe the Issue

hello, I would like to know how to import a complete profile for a monk heal because I downloaded hekili but there is only a few spells and not a complete rotation. if you could help me please

### How to Reproduce

.

### Snapshot (Link)

.

### Additional Information

.

### Contact Information

Praxitian

**Comment by Zanetsuken** [comment]
There isn’t one. Any such profile is going to focus on doing maximum damage, rather than effective healing.
The addon can’t tell you who to heal with what.

**Comment by praxitian** [comment]
hello, thank you for your answer, there is on youtube mayhem, a monk heal which uses hekili and I don't know if the addon does what it does or how but I find it really very complete

**Comment by NickGesirenZhang** [comment]
In one of the videos the creator claims "The addon calculates all health points, HoTs, and DoTs of all players in the group or raid 50 times per second." I don't think Hekili is able to accomplish this. It must be some other add-on.
