### ISSUE TITLE
Death Knight: UH - M+ Defile Autosnap

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#4232]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Was doing M+ and it auto snapped.  I believe it could be that I used defile in the incorrect spot (ie rune usage) but it snapped so I wanted to make sure to report.

### How to Reproduce

Unsure how to Reproduce.

### Player Information (Link)

https://pastebin.com/qgbqqDLw

### Error Messages (Link)

https://pastebin.com/qgbqqDLw

### Additional Information

Feel free to tell me I need to play better :D

### Contact Information

Wren1740

**Comment by syrifgit** [comment]
Not newest version
