### ISSUE TITLE
[REC] Assassination Rogue is being recommended Thistle Tea 2-3 times in a Row

### ISSUE THREAD

**Issue by 825i** [Hekili/hekili#4233]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

When going against any enemy, single or AoE or a target dummy I as getting recommended back-to-back Thistle Teas. Even worse, I am being given them when I have 280-290 out of 300 energy already... This is in addition to the same problem as #4229 I am being told to extremely often in single target just spam Fan of Knives to build combo points.

The first pastebin is below in the dedicated section, but here are two additional.
This Thistle Tea is like a plague on my rotation lol, so there is no shortage of snapshots.

https://pastebin.com/RPrQrNTL
https://pastebin.com/fhYxfBsi

### How to Reproduce

1. Get into combat
2. Follow recommended opener
3. On about the 5th action of my rotation, get back-to-back thistle teas between Fan of Knives lol @ over 280/300 energy...
4. Keep getting recommended Thistle Teas even right after using one before the first one has fallen off
5. Stop attacking and wait for energy to fill to 300 and Thistle Tea is still next up...

### Snapshot (Link)

https://pastebin.com/ckZFPWYR

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kL9pv6yKZqd2V12VifPYRA

### Additional Information

I think this seems to be the information I could find in: Hekili > Assassination > Action Lists > cds > Thistle Tea

This doesn't look right to me at all, it's calling Thistle Tea depending on the amount of enemies and how long the fight has potentially left by the looks of it, instead of by my energy level.

`! buff.thistle_tea.up & ( dot.kingsbane.ticking | debuff.shiv.remains >= 4 ) | spell_targets.fan_of_knives >= 4 & debuff.shiv.remains >= 6 | fight_remains <= cooldown.thistle_tea.charges * 6`

### Contact Information

Ginzoyel

**Comment by syrifgit** [comment]
There's nothing wrong with this snapshot. It's dumping tea because it thinks the fight is over. Using tea at full energy is completely fine, it's for the mastery buff. You can toggle your cooldowns on and off as you please to prevent this in dungeons.

You also have nameplates disabled so I can't tell what you're fighting, but presumably a target dummy. Dummies have weird time remaining because they don't die.

This ticket also has nothing to do with the other one you mentioned, completely unrelated.

Finally, you're not even max level. The addon is designed for use at max level.

**Comment by 825i** [comment]
@syrifgit 

I'm really not sure what you mean here.

Here is one of the screenshots I took at the same moment I paused the Addon:
![World of Warcraft 05_12_2024 22 42 36](https://github.com/user-attachments/assets/88fc86ba-12ba-4b0c-bddd-3a8d1e3aa786)

As you can see:

1. I am clearly still in a fight
2. not fighting a dummy
3. it should not be telling me to dump all my tea **_ever_**. That's just bad programming.
4. I might have another fight starting a few seconds later and what I'm supposed to do it with zero tea?.
5. It's on a 1 minute CD and the mastery buff isn't even that much and I am being recommended to use it back-to-back before the Tea's mastery buff has even expired.

The addon behaviour also shouldn't be so weird if I am only like 3 levels away from max so I don't think that is a valid reason either. The logic for recommending Tea just looks bad. It should be based on my remaining energy, which is primarily what the skill is for in the first place. Not to gain a near meaningless 10% mastery for a few seconds...

Recommending me Thistle Tea when I am already basically energy capped is nad logic. Fine if it maybe recommends me one just for the mastery buff. But it will recommend all three Teas back to back within 5 skills which is just horrible. The mastery buff from the first tea hasn't even fallen off yet and I am already energy capped. It's a total waste of my Tea and my rotation.

@Hekili can I please get a second opinion.

**Comment by Ltz-lab** [comment]
Go to Thistle Tea in hekili abilities and disable it then macro tea to shiv. the queen of assassin rogue and wowhead guide write himself has said to forget about pressing tea and use the macro.

#showtooltip Shiv 
/cast Shiv 
/castsequence reset=5 Thistle Tea, null

**Comment by syrifgit** [comment]
> it should not be telling me to dump all my tea ever. That's just bad programming.

Bring that up with the rogue discord sim writers then, because it's doing what the sim does. 

> I might have another fight starting a few seconds later and what I'm supposed to do it with zero tea?.

Toggle it, like I said. Check the `Getting Started` page inside the addon settings for instructions. The addon can never know if you have another pull right after, that's up to you as a player.

On top of that, you're 

1) Not max level with your capstone talent 
2) Not running the normal build

Both of these things affect it as well.
