### ISSUE TITLE
[REC] Elemental Blast (and Doom Winds) is missing from Enhancement rotation

### ISSUE THREAD

**Issue by kalman5** [Hekili/hekili#4236]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

Using the following specialization (single target)

CcQAYp+JUk5Lea12OyacsLNThMzMzCmhZ2mZmZY2mZ2WGAAAAAAAAAAYDgNzYYjsAzohGsAgZZyMwyiZmZGGzMbDLzMTgxyYmBAYGD

Elemental Blast and Doom Winds is not suggested.

Doom Winds is otherwise suggested with the following spec (multi target)

CcQAYp+JUk5Lea12OyacsLNThMzMDMjZYmZmhZZmZZbWmBAAAAAAAAAwGAbmxwGZBmRDNYBAzykBssMzMzMMjZMsMzMNLsMwMDAwMA

### How to Reproduce

Play Enh Shaman use the specialization for single target:

CcQAYp+JUk5Lea12OyacsLNThMzMzCmhZ2mZmZY2mZ2WGAAAAAAAAAAYDgNzYYjsAzohGsAgZZyMwyiZmZGGzMbDLzMTgxyYmBAYGD

and observe that both  Elemental Blast and Doom Wind are not suggested

### Snapshot (Link)

https://pastebin.com/ea8Ydgwz

### Additional Information

Looks like it doesn't suggest Elemental Blast if Elemental Spirit is not known (Alpha Wolf is known instead)

**Comment by Hekili** [comment]
You'll need to take the snapshot at the point where Doom Winds and/or Elemental Blast should've been used; your snapshot looks like the start of a fight (i.e., recommending Earth Elemental totem).

Elemental Blast in current sims for non-Totemic builds (in single-target) requires:
* Max Maelstrom Weapon, Elemental Spirits talented, 6+ Feral Spirits active, and either (1) it's about to cap charges or (2) Ascendance is up.
* 8+ stacks of Maelstrom Weapon, 4+ Feral Spirits active, and either (1) it's about to cap charges or (2) Ascendance is *not* up.
* Maelstrom Weapon is at 5+ stacks, you have 4+ Feral Spirits, Deeply Rooted Elements is talented, and (1) you're about to cap charges or (2) you have 4+ stacks of Molten Weapon + Icy Edge combined) and Flowing Spirits is not talented.

So yeah, current priority is not written to use Elemental Blast without a Feral Spirit damage bonus that you're not really going to have.  It's likely that some similar logic as the Totemic use of Elemental Blast should be merged, but there aren't sims showing specifically when/where that should be.  I'll investigate more later.

**Comment by syrifgit** [comment]
Closing as this ticket is 2 weeks old and there are newer enhance APLs now.
