### ISSUE TITLE
Prot paladin bug

### ISSUE THREAD

**Issue by rambutanMan** [Hekili/hekili#424]
Message: ...nterface\AddOns\Hekili\Classes\PaladinProtection.lua:979: attempt to index field 'light_of_the_protector' (a nil value)
Time: Fri Sep 11 04:33:11 2020
Count: 239
Stack: ...nterface\AddOns\Hekili\Classes\PaladinProtection.lua:979: attempt to index field 'light_of_the_protector' (a nil value)
[string "@Interface\AddOns\Hekili\Classes\PaladinProtection.lua"]:979: in function `handler'
[string "@Interface\AddOns\Hekili\State.lua"]:4988: in function `RunHandler'
[string "@Interface\AddOns\Hekili\Core.lua"]:1477: in function `ProcessHooks'
[string "@Interface\AddOns\Hekili\UI.lua"]:825: in function <Interface\AddOns\Hekili\UI.lua:689>

Locals: (*temporary) = nil
(*temporary) = <function> defined @Interface\AddOns\Hekili\Utils.lua:234
(*temporary) = 0
(*temporary) = nil
(*temporary) = "attempt to index field 'light_of_the_protector' (a nil value)"

**Comment by Hekili** [comment]
Try -alpha36 and let me know if you find issues.
