### ISSUE TITLE
Clear the witness problem.

### ISSUE THREAD

**Issue by exedrasd** [Hekili/hekili#4243]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - subtlety

### Describe the Issue

According to wowhead you only use shuriken storm outside of stealth and shadow dance. The rotation uses shuriken storm in the opener after vanish because you get clear the witness proc, but it should only use shuriken storm with clear the witness  outside of stealth/shadow dance in single target. 

### How to Reproduce

Enter the game, and you will see that the 5th ability used will be shuriken storm. 

### Snapshot (Link)

Subtlety; Cooldowns - N/A build: v11.0.5-1.0.19 level: 80 (80) class: ROGUE spec: subtlety  talents: CUQAA0tw2gAD7pPTLoW5IGZDeAAM2mBAAAAAgZZMWmmZGzMGGDDzMzMjxsNMzYbbmZMzMjBjlZbAAAAYGMsYWGYALglhJkZBG     acrobatic_strikes = 1/1     airborne_irritant = 1/1     alacrity = 2/2     atrophic_poison = 1/1     blind = 1/1     cheat_death = 1/1     clear_the_witnesses = 1/1     cloak_of_shadows = 1/1     cold_blood = 1/1     corrupt_the_blood = 1/1     danse_macabre = 1/1     dark_shadow = 2/2     darkest_night = 1/1     deadened_nerves = 1/1     deadly_precision = 1/1     death_perception = 2/2     deathstalker = 1/1     deathstalkers_mark = 1/1     deepening_shadows = 1/1     deeper_daggers = 1/1     deeper_stratagem = 1/1     double_dance = 1/1     ephemeral_bond = 1/1     ethereal_cloak = 1/1     evasion = 1/1     fade_to_nothing = 1/1     fatal_intent = 1/1     featherfoot = 1/1     find_weakness = 1/1     flagellation = 1/1     fleet_footed = 1/1     forced_induction = 1/1     gloomblade = 1/1     graceful_guile = 1/1     hunt_them_down = 1/1     improved_ambush = 1/1     improved_backstab = 1/1     improved_shadow_dance = 1/1     improved_sprint = 1/1     inevitability = 1/1     iron_stomach = 1/1     leeching_poison = 1/1     lethality = 2/2     lingering_darkness = 1/1     master_poisoner = 1/1     momentum_of_despair = 1/1     nimble_fingers = 1/1     premeditation = 1/1     recuperator = 1/1     relentless_strikes = 1/1     rushed_setup = 1/1     secret_stratagem = 1/1     secret_technique = 1/1     shadewalker = 1/1     shadow_blades = 1/1     shadow_focus = 1/1     shadowcraft = 1/1     shadowed_finishers = 1/1     shadowrunner = 1/1     shot_in_the_dark = 1/1     shrouded_in_darkness = 1/1     singular_focus = 1/1     supercharger = 2/2     swift_death = 1/1     the_rotten = 1/1     thrill_seeking = 1/1     tricks_of_the_trade = 1/1     veiltouched = 1/1     weaponmaster = 1/1  pvptalents: none  covenant: none  conduits: none  soulbinds: []  sets: tww1 = 4  gear: alliance_tabard = 1     detachable_fang = 1     enkindled_locket = 1     fuzzy_molding_halo = 1     ironclaw_dirk = 1     kareshi_phantoms_emptiness = 1     kareshi_phantoms_grips = 1     kareshi_phantoms_leggings = 1     kareshi_phantoms_shoulderpads = 1     myconic_wrap = 1     myconic_wristbands = 1     seal_of_the_silent_vigil = 1     shadowbinding_ritual_knife = 1     spelunkers_leather_footpads = 1     spelunkers_practiced_sash = 1     tww1 = 4     vest_of_fading_luminescence = 1  legendaries: none  itemIDs: 168100, 212036, 212037, 212038, 212039, 215178, 219167, 219184, 219186, 219189, 219470, 219480, 222465, 223297, 225657, 225748  settings: aoe = 3     canFunnel = true     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = false     damageExpiration = 6     damageOnScreen = true     damagePets = false     damageRange = 0     enabled = true     funnel = false     gcdSync = true     nameplateRange = 10     nameplates = true     noFeignedCooldown = false     package = Subtlety     petbased = false     placeboBar = 3     potion = tempered_potion     rangeFilter = false     mfd_points = 3     priority_rotation = false     rupture_duration = 12     solo_vanish = true     vanish_charges_reserved = 0  toggles: cooldowns = true [separate]     custom1 = false      custom2 = false      defensives = true      essences = false [overridden]     funnel = false      interrupts = true      mode = automatic      potions = false   keybinds:      ambush                = S   [07]     backstab              = S   [01]     black_powder          = CE  [01]     blind                 = SZ  [03]     cloak_of_shadows      = C2  [06]     crimson_vial          = CA  [06]     dismantle             = O   [06]     evasion               = CX  [06]     eviscerate            = E   [01], E   [07]     feint                 = 4   [03]     flagellation          = Q   [01], Q   [07]     gloomblade            = S   [01]     kick                  = 8   [06]     kidney_shot           = D   [07]     rupture               = R   [01], R   [07]     sap                   = P   [05]     secret_technique      = SF  [03], F   [05], A   [06]     shadow_blades         = M3  [01], M3  [07]     shadowstep            = 3   [05], W   [07]     shadowstrike          = S   [07]     shroud_of_concealment = SC  [03]     shuriken_storm        = X   [05]     shuriken_toss         = Z   [06]     slice_and_dice        = 6   [01]     sprint                = CS  [01], SX  [03], SS  [05], SE  [06], 6   [07]     stealth               = C   [01], C   [07]     symbols_of_death      = 2   [06]     thistle_tea           = 9   [05]     vanish                = 5   [03]  warnings: [#1] Update: Interface/AddOns/Hekili/Core.lua:736: attempt to index local 'packInfo' (a nil value) [string "@Interface/AddOns/Hekili/Core.lua"]:736: in function `GetPredictionFromAPL' [string "@Interface/AddOns/Hekili/Core.lua"]:952: in function `GetPredictionFromAPL' [string "@Interface/AddOns/Hekili/Core.lua"]:1478: in function `GetNextPrediction' [string "@Interface/AddOns/Hekili/Core.lua"]:1878: in function <Interface/AddOns/Hekili/Core.lua:1528>  [#2] Unknown buff in [Subtlety:stealth_cds:1]: first_dance [string "@Interface/AddOns/Hekili/State.lua"]:4077: in function <Interface/AddOns/Hekili/State.lua:4068> [string "@Interface/AddOns/Hekili/TheWarWithin/RogueSubtlety.lua"]:335: in function <...terface/AddOns/Hekili/TheWarWithin/RogueSubtlety.lua:335> [string "=(tail call)"]: ? [string "@Interface/AddOns/Hekili/State.lua"]:994: in function `applyBuff' [string "@Interface/AddOns/Hekili/TheWarWithin/RogueSubtlety.lua"]:1231: in function `handler' [string "@Interface/AddOns/Hekili/State.lua"]:6443: in function `RunHandler' [string "@Interface/AddOns/Hekili/Core.lua"]:2020: in function <Interface/AddOns/Hekili/Core.lua:1528>    targets:  Nameplates are enabled.  - Checking nameplate list for nameplate1 [ Creature-0-4236-2552-17822-225983-000056F91C ] Dungeoneer's Training Dummy.     nameplate1   - -1 - Creature-0-4236-2552-17822-225983-000056F91C - 300.00 - 1 - Dungeoneer's Training Dummy    player_buffs:    381637 - atrophic_poison                          -   1 - 666.30    315584 - instant_poison                           -   1 - 664.81    462810 - *weavers_prodigy                         -   1 - 3600.00    452307 - *sign_of_the_past                        -   1 - 3600.00    455020 - *wows_anniversary                        -   1 - 3600.00    471521 - *sign_of_the_explorer                    -   1 - 3600.00    457178 - clear_the_witnesses                      -   1 - 10.51     196911 - shadow_techniques                        -   3 - 3600.00    108211 - leeching_poison                          -   1 - 3600.00    455144 - acrobatic_strikes                        -   2 - 2.45    player_debuffs:  target_buffs:  target_debuffs:    457129 - deathstalkers_mark                       -   3 - 58.51     392388 - atrophic_poison_dot                      -   1 - 8.63      316220 - find_weakness                            -   1 - 8.63      461981 - *fatal_intent                            -   1 - 59.45   previous_spells:    1 - shadowstrike    2 - stealth    3 - gloomblade    4 - gloomblade    5 - gloomblade   New Recommendations for [ Cooldowns ] requested at 23:36:00 ( 96528.46 ); using built-in ( Subtlety ) priority. *** START OF NEW DISPLAY: Cooldowns *** Purged 688 marked values in 0.20ms. Danse Tracker @ Reset:  RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).      Resources: combo_points[ 7.00 / 7.00 ], energy[ 77.00 / 100.00 ]     Danse Tracker @ Step:     Checking if I'm casting ( No ) and if it is a channel ( No ).     No whitelist.          Processing precombat action list [ Subtlety - precombat ].                  Current recommendation was NO ACTION at +10.00s.                  1.   apply_poison ( precombat - 1 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-precombat-1:apply_poison:x0:0.02:Ability Known, Enabled(0.02)                  2.   variable ( precombat - 2 )         priority_rotation #1 [Subtlety:precombat:2]; conditions = PASS: NONE          - value = false: toggle.funnel[false]          - variable.priority_rotation[false] will check this script entry ( Subtlety:precombat:2 )         Time spent on this action:  0.04ms         TimeData:Subtlety-precombat-2:variable:x0:0.04:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02)                  3.   variable ( precombat - 3 )         trinket_sync_slot #1 [Subtlety:precombat:3]; conditions = FAIL: trinket.t1.has_stat.any_dps[false] & ( ! trinket.t2.has_stat.any_dps[false] | trinket.t1.is.treacherous_transmitter[false] | trinket.t1.cooldown.duration[0.00] >= trinket.t2.cooldown.duration[0.00] )          - value = 0: 1          - variable.trinket_sync_slot[0] will check this script entry ( Subtlety:precombat:3 )         Time spent on this action:  0.03ms         TimeData:Subtlety-precombat-3:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  4.   variable ( precombat - 4 )         trinket_sync_slot #2 [Subtlety:precombat:4]; conditions = FAIL: trinket.t2.has_stat.any_dps[false] & ( ! trinket.t1.has_stat.any_dps[false] | trinket.t2.cooldown.duration[0.00] > trinket.t1.cooldown.duration[0.00] )          - value = 0: 2          - variable.trinket_sync_slot[0] will check this script entry ( Subtlety:precombat:4 )         Time spent on this action:  0.03ms         TimeData:Subtlety-precombat-4:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  5.   stealth ( precombat - 5 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-precombat-5:stealth:x0:0.02:Ability Known, Enabled(0.02)         Exiting precombat with recommendation of NO ACTION at +10.00s.          Completed precombat action list [ Subtlety - precombat ].          Processing default action list [ Subtlety - default ].                  Current recommendation was NO ACTION at +10.00s.                  6.   stealth ( default - 1 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-default-1:stealth:x0:0.01:Ability Known, Enabled(0.01)                  7.   kick ( default - 2 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-default-2:kick:x0:0.01:Ability Known, Enabled(0.01)                  8.   variable ( default - 3 )         stealth #1 [Subtlety:default:3]; conditions = PASS: NONE          - value = false: buff.shadow_dance.up[false] | buff.stealth.up[false] | buff.vanish.up[false]          - variable.stealth[false] will check this script entry ( Subtlety:default:3 )         Time spent on this action:  0.03ms         TimeData:Subtlety-default-3:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  9.   variable ( default - 4 )         skip_rupture #1 [Subtlety:default:4]; conditions = PASS: NONE          - value = true: buff.shadow_dance.up[false] | ! buff.slice_and_dice.up[false] | buff.darkest_night.up[false] | active_enemies[1.00] >= 8 & ! talent.replicating_shadows.enabled[false] & talent.unseen_blade.enabled[false]          - variable.skip_rupture[true] will check this script entry ( Subtlety:default:4 )         Time spent on this action:  0.03ms         TimeData:Subtlety-default-4:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  10.  variable ( default - 5 )         maintenance #1 [Subtlety:default:5]; conditions = PASS: NONE          - value = false: ( dot.rupture.ticking[false] | variable.skip_rupture[true] ) & buff.slice_and_dice.up[false]          - variable.maintenance[false] will check this script entry ( Subtlety:default:5 )         Time spent on this action:  0.03ms         TimeData:Subtlety-default-5:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  11.  variable ( default - 6 )         secret #1 [Subtlety:default:6]; conditions = PASS: NONE          - value = false: buff.shadow_dance.up[false] | ( cooldown.flagellation.remains[0.00] < 40 & cooldown.flagellation.remains[0.00] > 20 & talent.death_perception.enabled[true] )          - variable.secret[false] will check this script entry ( Subtlety:default:6 )         Time spent on this action:  0.03ms         TimeData:Subtlety-default-6:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  12.  variable ( default - 7 )         racial_sync #1 [Subtlety:default:7]; conditions = PASS: NONE          - value = false: ( buff.flagellation_buff.up[false] & buff.shadow_dance.up[false] ) | ! talent.shadow_blades.enabled[true] & buff.symbols_of_death.up[false] | boss[false] & fight_remains[1731.12] < 20          - variable.racial_sync[false] will check this script entry ( Subtlety:default:7 )         Time spent on this action:  0.03ms         TimeData:Subtlety-default-7:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  13.  variable ( default - 8 )         shd_cp #1 [Subtlety:default:8]; conditions = PASS: NONE          - value = false: combo_points.current[7.00] <= 1 | buff.darkest_night.up[false] & combo_points.current[7.00] >= 7 | effective_combo_points[7.00] >= 6 & talent.unseen_blade.enabled[false]          - variable.shd_cp[false] will check this script entry ( Subtlety:default:8 )         Time spent on this action:  0.03ms         TimeData:Subtlety-default-8:variable:x0:0.03:Ability Known, Enabled(0.02):Post-TTR and Essential(0.01)                  14.  call_action_list:cds ( default - 9 )         There is no criteria for cds.         Action list (cds) was found.         + cds         Current recommendation was NO ACTION at +10.00s.                  15.  cold_blood ( cds - 1 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-cds-1:cold_blood:x0:0.02:Ability Known, Enabled(0.02)                  Substituting tempered_potion for Potion action; it is otherwise not included in the priority.         16.  tempered_potion ( cds - 2 ) - ability disabled ( toggle potions )         Time spent on this action:  0.02ms         TimeData:Subtlety-cds-2:tempered_potion:x0:0.02:Ability Known, Enabled(0.02)                  17.  symbols_of_death ( cds - 3 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-cds-3:symbols_of_death:x0:0.02:Ability Known, Enabled(0.02)                  18.  shadow_blades ( cds - 4 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-cds-4:shadow_blades:x0:0.02:Ability Known, Enabled(0.02)                  19.  thistle_tea ( cds - 5 ) - talent [ thistle_tea ] missing         Time spent on this action:  0.02ms         TimeData:Subtlety-cds-5:thistle_tea:x0:0.02:Ability Known, Enabled(0.02)                  20.  flagellation ( cds - 6 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-cds-6:flagellation:x0:0.02:Ability Known, Enabled(0.02)         Exiting cds with recommendation of NO ACTION at +10.00s.         Returned from list (cds), current recommendation is NO ACTION (+10.00).         - cds                  21.  blood_fury ( default - 10 ) - ability unknown         Time spent on this action:  0.03ms         TimeData:Subtlety-default-10:blood_fury:x0:0.03:Ability Known, Enabled(0.03)                  22.  berserking ( default - 11 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Subtlety-default-11:berserking:x0:0.02:Ability Known, Enabled(0.02)                  23.  fireblood ( default - 12 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Subtlety-default-12:fireblood:x0:0.02:Ability Known, Enabled(0.02)                  24.  ancestral_call ( default - 13 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Subtlety-default-13:ancestral_call:x0:0.02:Ability Known, Enabled(0.02)                  25.  treacherous_transmitter ( default - 14 ) - IsUsableItem item 221023 and nil         Time spent on this action:  0.05ms         TimeData:Subtlety-default-14:treacherous_transmitter:x0:0.05:Ability Known, Enabled(0.05)                  26.  imperfect_ascendancy_serum ( default - 15 )         The action (imperfect_ascendancy_serum) is unusable at (0.00 + 0.00) because item not equipped.         Time spent on this action:  0.12ms         TimeData:Subtlety-default-15:imperfect_ascendancy_serum:x0:0.12:Ability Known, Enabled(0.08):Post-TTR and Essential(0.03):Post Cycle(0.00):Post Usable(0.00)                  27.  mad_queens_mandate ( default - 16 ) - IsUsableItem item 212454 and nil         Time spent on this action:  0.04ms         TimeData:Subtlety-default-16:mad_queens_mandate:x0:0.04:Ability Known, Enabled(0.04)                  Bypassing 'trinket1' action because the equipped trinket #1 is not usable.                  28.  trinket1 ( default - 17 )         Time spent on this action:  0.02ms         TimeData:Subtlety-default-17:trinket1:x0:0.02:Ability Known, Enabled(0.02)                  Bypassing 'trinket2' action because the equipped trinket #2 is not usable.                  29.  trinket2 ( default - 18 )         Time spent on this action:  0.02ms         TimeData:Subtlety-default-18:trinket2:x0:0.02:Ability Known, Enabled(0.02)                  30.  call_action_list:stealth_cds ( default - 19 )         Criteria for stealth_cds PASS at +0.00 - ! variable.stealth[false]         Action list (stealth_cds) was found.         + stealth_cds         Current recommendation was NO ACTION at +10.00s.                  31.  shadow_dance ( stealth_cds - 1 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-stealth_cds-1:shadow_dance:x0:0.02:Ability Known, Enabled(0.02)                  32.  vanish ( stealth_cds - 2 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-stealth_cds-2:vanish:x0:0.02:Ability Known, Enabled(0.02)                  33.  shadowmeld ( stealth_cds - 3 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-stealth_cds-3:shadowmeld:x0:0.01:Ability Known, Enabled(0.01)         Exiting stealth_cds with recommendation of NO ACTION at +10.00s.         Returned from list (stealth_cds), current recommendation is NO ACTION (+10.00).         - stealth_cds                  34.  call_action_list:finish ( default - 20 )         Time-sensitive Criteria for finish deferred at +0.00 - ! buff.darkest_night.up[false] & effective_combo_points[7.00] >= 6 | buff.darkest_night.up[false] & combo_points.current[7.00] = cp_max_spend[7.00]         Action list (finish) was found.         + finish         Current recommendation was NO ACTION at +10.00s.                  35.  secret_technique ( finish - 1 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-finish-1:secret_technique:x0:0.02:Ability Known, Enabled(0.02)                  36.  rupture ( finish - 2 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-finish-2:rupture:x0:0.01:Ability Known, Enabled(0.01)                  37.  rupture ( finish - 3 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-finish-3:rupture:x0:0.01:Ability Known, Enabled(0.01)                  38.  coup_de_grace ( finish - 4 ) - ability disabled ( display )         Time spent on this action:  0.04ms         TimeData:Subtlety-finish-4:coup_de_grace:x0:0.04:Ability Known, Enabled(0.04)                  39.  black_powder ( finish - 5 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-finish-5:black_powder:x0:0.01:Ability Known, Enabled(0.01)                  40.  eviscerate ( finish - 6 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-finish-6:eviscerate:x0:0.02:Ability Known, Enabled(0.02)         Exiting finish with recommendation of NO ACTION at +10.00s.         Returned from list (finish), current recommendation is NO ACTION (+10.00).         - finish                  41.  call_action_list:build ( default - 21 )         There is no criteria for build.         Action list (build) was found.         + build         Current recommendation was NO ACTION at +10.00s.                  42.  shadowstrike ( build - 1 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-build-1:shadowstrike:x0:0.01:Ability Known, Enabled(0.01)                  43.  shuriken_storm ( build - 2 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-build-2:shuriken_storm:x0:0.01:Ability Known, Enabled(0.01)                  44.  shuriken_tornado ( build - 3 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-build-3:shuriken_tornado:x0:0.01:Ability Known, Enabled(0.01)                  45.  shadowstrike ( build - 4 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-build-4:shadowstrike:x0:0.01:Ability Known, Enabled(0.01)                  46.  goremaws_bite ( build - 5 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-build-5:goremaws_bite:x0:0.01:Ability Known, Enabled(0.01)                  47.  gloomblade ( build - 6 ) - ability disabled ( display )         Time spent on this action:  0.01ms         TimeData:Subtlety-build-6:gloomblade:x0:0.01:Ability Known, Enabled(0.01)                  48.  backstab ( build - 7 ) - ability disabled ( display )         Time spent on this action:  0.02ms         TimeData:Subtlety-build-7:backstab:x0:0.02:Ability Known, Enabled(0.02)         Exiting build with recommendation of NO ACTION at +10.00s.         Returned from list (build), current recommendation is NO ACTION (+10.00).         - build                  49.  call_action_list:fill ( default - 22 )         Criteria for fill PASS at +0.00 - ! variable.stealth[false]         Action list (fill) was found.         + fill         Current recommendation was NO ACTION at +10.00s.                  50.  arcane_torrent ( fill - 1 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Subtlety-fill-1:arcane_torrent:x0:0.02:Ability Known, Enabled(0.02)                  51.  arcane_pulse ( fill - 2 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Subtlety-fill-2:arcane_pulse:x0:0.02:Ability Known, Enabled(0.02)                  52.  lights_judgment ( fill - 3 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Subtlety-fill-3:lights_judgment:x0:0.02:Ability Known, Enabled(0.02)                  53.  bag_of_tricks ( fill - 4 ) - ability unknown         Time spent on this action:  0.02ms         TimeData:Subtlety-fill-4:bag_of_tricks:x0:0.02:Ability Known, Enabled(0.02)         Exiting fill with recommendation of NO ACTION at +10.00s.         Returned from list (fill), current recommendation is NO ACTION (+10.00).         - fill         Exiting default with recommendation of NO ACTION at +10.00s.          Completed default action list [ Subtlety - default ].     Recommendation is NO ACTION at 0.00 + 10.00.     Recommendation #1 is NO ACTION at 10.00s (10.00s).     Resources: Resources: combo_points[ 7.00 / 7.00 | 7.00 @ [1 - actual] 0.00 ], energy[ 77.00 / 100.00 | 100.00 @ [2 - shadow_techniques] 5.72 ]     Time spent generating recommendations:  3.02ms   Performance | Updates | Updates / sec | Avg. Work | Avg. Time | Avg. Frames | Peak Work | Peak Time | Peak Frames | FPS | Work Cap | |    2630 |          0.81 |     16.02 |     35.28 |        2.55 |     22.35 |     58.77 |        3.00 |  83 |     7.93 |

### Contact Information

exedra#8511

**Comment by syrifgit** [comment]
Update to the newest version first, re-open if the issue persists.

Also, please use pastebin for snapshots. don't paste directly into the ticket as it's impossible to read.
