### ISSUE TITLE
Hekili for Classic ERA

### ISSUE THREAD

**Issue by RayMoake** [Hekili/hekili#4245]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Please add Hekili to Classic ERA. I find after all these years that Hekili is always been more reliable than others. I am stuck right now with Conrac and it is not even give me complete updates on different classes. When I played hekili it was always up to date and should be simple to put on Classic ERA caused classic ERA will not change. It is set in stone and therefore should be simple to setup for us. Please. I tried Hero but it did nothing on Classic Era because of two files that I find are for retail mainly.

### Contact Information

raymoake@bellsouth.net

**Comment by syrifgit** [comment]
Not likely to be supported.
