### ISSUE TITLE
[REC] Suggest optimizing the timing of Ovi'nax's Mercurial Egg usage

### ISSUE THREAD

**Issue by lie5860** [Hekili/hekili#4247]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Paladin - Retribution

### Describe the Issue

According to the trinket description, 'Additional stacks above 20 grant 60% reduced benefit.' Therefore, it is recommended to use this trinket when neither stack is above 20 and the total number of stacks is at least 30. Currently, the trinket is used immediately as soon as it is off cooldown, regardless of whether you have 30 stacks or 0 stacks.

### How to Reproduce

Any class and any talent, I've tried Retribution Paladin, Balance Druid, and Enhancement Shaman, and they all have this issue.

### Snapshot (Link)

https://pastebin.com/jb8YhzLv

**Comment by lie5860** [comment]
t seems like it can be handled through buffs using deliberate_incubation in player_buffs from the snapshot. However, I'm not sure if this is correct.

**Comment by syrifgit** [comment]
If your spec APL does not have a particular entry for the trinket, then you may be better off disabling it and using a weakaura.
