### ISSUE TITLE
[REC] Frost Mage Death Chill Ice Lance Not Being Recommended + Spymaster Web issue

### ISSUE THREAD

**Issue by yokaii4** [Hekili/hekili#4249]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Mage - Frost

### Describe the Issue

Issue 1: When talented into ST with Death Chill build, the addon fails to suggest Ice Lance even when Fingers of Frost is Up. While it's understandable during Icy Veins, there's no reason why outside of it we should prefer casting frostbolt over Ice Lance with FoF proc

Issue 2: Spymaster is being recommended randomly during raid bosses and m+. In both instances, it gets recommended while  only 20 ish charges are available. I did not get a snapshot for this because I simply believe that a correction to the combat time remaining script would suffice (since it got fixed on balance which had same issue)

### How to Reproduce

1. Enter game as Frost Mage
2. Spec into ST Death Chill build (you can copy-paste it from Sikran logs or check pastebin)
3. fight ST dummy (the one above the tower in Dornogal)
4. execute rotation normally until Icy veins fall off and Fingers of Frost is up and check that Ice Lance is not being recommended

### Snapshot (Link)

https://pastebin.com/7b8Z5Jmi

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/9hibiWfwvFCYhrPcdYqPtV

### Contact Information

yokaii__

**Comment by yokaii4** [comment]
Here's the guide page for reference: https://www.icy-veins.com/wow/frost-mage-pve-dps-rotation-cooldowns-abilities?area=area_3#single-target-opener-for-wowspellslingerht-frost-mage-in-linkcurrentexpansion

Another mistake that hekili does is to assume that the Time Warp Icy Veins procs are considered like the manual ones for the death chill while they should not (you can find it in the guide too). I think this is probably the main issue with Death Chill and hekili

**Comment by yokaii4** [comment]
NOTE: after speaking with @syrifgit I'm also adding the following issue: during freezing winds, the addon will randomly recommend flurry without a previous frostbolt or Glacial Spike. I believe that this issue is caused by the freezing winds timings that might be too fast for the addon to register. There are some instances where the next proc happens in around +1.7s which is where we should cast that filler frostbolt/GS with flurry IMHO. You can check this WA to understand the timings of freezing winds: https://wago.io/gO_8GIa8o

NOTE: all issues in this ticket happens with SPELLSINGER Hero Talent

**Comment by syrifgit** [comment]
### Item 1

> When talented into ST with Death Chill build, the addon fails to suggest Ice Lance even when Fingers of Frost is Up. While it's understandable during Icy Veins, there's no reason why outside of it we should prefer casting frostbolt over Ice Lance with FoF proc

Except for the fact that the Frost Mage APL has 0 consideration for this proc in SS builds with boltspam talents.

This is directly from SIMC, not Hekili.

```
actions.st_ss=comet_storm,if=prev_gcd.1.flurry&buff.icy_veins.down
actions.st_ss+=/flurry,if=cooldown_react&remaining_winters_chill=0&debuff.winters_chill.down&(prev_gcd.1.frostbolt|prev_gcd.1.glacial_spike)
actions.st_ss+=/frozen_orb,if=cooldown_react&(cooldown.icy_veins.remains>22|buff.icy_veins.up)
actions.st_ss+=/glacial_spike,if=buff.icicles.react=5&(action.flurry.cooldown_react|remaining_winters_chill|cooldown.flurry.remains<action.glacial_spike.execute_time&cooldown.flurry.remains>0)
actions.st_ss+=/ray_of_frost,if=variable.boltspam&remaining_winters_chill&buff.icy_veins.down
actions.st_ss+=/ray_of_frost,if=!variable.boltspam&remaining_winters_chill=1
actions.st_ss+=/shifting_power,if=cooldown.icy_veins.remains>10&!action.flurry.cooldown_react&(variable.boltspam|buff.icy_veins.down|buff.icy_veins.remains>10)&(fight_remains+10>cooldown.icy_veins.remains)
actions.st_ss+=/frostbolt,if=variable.boltspam&buff.icy_veins.remains>9&buff.deaths_chill.stack<8
actions.st_ss+=/ice_lance,if=variable.boltspam&(remaining_winters_chill=2|remaining_winters_chill&action.flurry.cooldown_react)
actions.st_ss+=/ice_lance,if=!variable.boltspam&(buff.fingers_of_frost.react&!prev_gcd.1.glacial_spike|remaining_winters_chill)
actions.st_ss+=/frostbolt
actions.st_ss+=/call_action_list,name=movement
```

Your sim does the exact same thing until a flurry proc comes up, then it'll switch over to ice lance. Addon looks like many frostbolts because it can't tell you exactly when a random proc will happen. But it will surely happen sometime before the 7th frostbolt.

### Item 2

> Spymaster is being recommended randomly during raid bosses and m+. In both instances, it gets recommended while only 20 ish charges are available. I did not get a snapshot for this because I simply believe that a correction to the combat time remaining script would suffice (since it got fixed on balance which had same issue)

I've added an extra `boss` condition to the spymasters entry, should help.

### Item 3

> assume that the Time Warp Icy Veins procs are considered like the manual ones for the death chill while they should not (you can find it in the guide too). I think this is probably the main issue with Death Chill and hekili

This appears to already be handled by the APL, given that the free proc is 8 seconds, and there are lots of entries which require the buff to be 9 seconds or longer. This seems to already be live in-game. Are you on the newest version?

### Item 4

> during freezing winds, the addon will randomly recommend flurry without a previous frostbolt or Glacial Spike. I believe that this issue is caused by the freezing winds timings that might be too fast for the addon to register.

Need a snapshot. When you have one just do a new ticket, since all the other items are already addressed. But for what it's worth, the addon already predicts freezing winds correctly. But the current recommendation won't make you wait 0.1 seconds for it to happen if something else is already available.

**Comment by yokaii4** [comment]
> This appears to already be handled by the APL, given that the free proc is 8 seconds, and there are lots of entries which require the buff to be 9 seconds or longer. This seems to already be live in-game. Are you on the newest version?
Yes I am, unless you mean the one that just released. I noticed that the random proc changes suddenly to all frostbolts. Would it be possible to add a string to "force" the addon to ignore the procs?

As for the rest gotcha, was just noticing that happening often so I thought it was an issue
