### ISSUE TITLE
AOE Spells Suggested in Single Target Bar

### ISSUE THREAD

**Issue by Ash-Bird** [Hekili/hekili#425]
**Describe the Bug/Issue**
For the Arms Warrior Hekili, the Fervor of Battle talented Whirlwind (30 Rage, ST Slam + AOE Whirlwind) is frequently suggested as both a ST and AOE skill. The traditional 20 Rage ST Slam is seemingly never suggested as a ST skill. In combat scenarios where I am fighting one hostile creature, but surrounded by multiple neutral creatures, this can lead to unintentionally large pulls when the intention was to only pull ST. 

**To Reproduce**
- Use Default Arms Warrior Priority List
- Select Fervor of Battle talent 
- Attack ST creature, and follow ST Hekili suggestions
- Watch Whirlwind AOE come up in suggestions

**Expected Behavior**
I expect that the AOE suggestions include both AOE and ST as needed for the highest DPS but that the ST suggestions **only** include ST skills. 

**Screenshots**
Both Screenshots are showing the ST bar - 
![image](https://user-images.githubusercontent.com/20172078/92957835-72317580-f426-11ea-8ddf-ce46810cfeb9.png)
![image](https://user-images.githubusercontent.com/20172078/92957870-7fe6fb00-f426-11ea-82ec-f789e6d03423.png)

**Issue Reporting Information**
https://pastebin.com/NGYSSRU5

**Comment by Hekili** [comment]
Please use the snapshot feature to include a snapshot.

**Comment by Hekili** [comment]
With Fervor of Battle, Whirlwind does more damage and Slams your target.  So there's no reason you'd use Slam alone, as that would cost Rage and do less damage.  I.e., Whirlwind is effectively a single-target ability with your talent selection.

![image](https://user-images.githubusercontent.com/9438134/92963870-27712700-f441-11ea-8731-86e5e62b7486.png)
