### ISSUE TITLE
[FEATURE] How to access the variable which control "Major Cooldowns"/"Minor Cooldowns"

### ISSUE THREAD

**Issue by 1989wd3** [Hekili/hekili#4254]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

I'm trying to combine WA and Hekili to improve the bursting control performance, however, I don't know how to visit the variable
which control "Major Cooldowns"/"Minor Cooldowns",  hope author can tell me, thanks！

**Comment by chevyn11** [comment]
if it helps, there is a WA that displays the toggles that is clickable.. so it should have an example of the access you need: https://wago.io/HekiliToggles

**Comment by syrifgit** [comment]
`/hek set`
