### ISSUE TITLE
[REC] Assa Rogue - Deathmark not being recommended properly

### ISSUE THREAD

**Issue by yokaii4** [Hekili/hekili#4255]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Rogue - Assassination

### Describe the Issue

Deathmark/kingsbane is not being recommended properly: every time the addon gets stuck in recommending rupture instead of envenom to start with the deathmark and kingsbane. Envenom gets recommended for the first time after around 10 gcd, even if all the mobs are already dotted. What happens is that envenom, deathmark sequence gets recommended for a split second then the addon changes to what I recorded in my snapshot

### How to Reproduce

1. enter game as Assa rogue
2. execute rotation on dummies both ST or AOE
3. follow the addon suggestions and notice how no envenom gets recommended therefore too many gcd passes till deathmark can start

### Snapshot (Link)

https://pastebin.com/qWVEn6hM

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/miUYA8KxJR83fZcegSpywE

### Contact Information

yokaii__

**Comment by yokaii4** [comment]
NOTE: do not follow the APL blindly since it recommends to use shiv before kingsbane, which is wrong since you should use it during kingsbane last 15s when you are playing 1 shiv charge

**Comment by yokaii4** [comment]
P.S.: found a moment where in ST it's randomly recommending me to fan of knives https://pastebin.com/nvtrsXf7 sometimes it happens with rupture too but it's quite random. But what I can tell 100% is that it always happen when deathmark and/or kingsbane are used after the fight begun for like 20-30s

**Comment by syrifgit** [comment]
> P.S.: found a moment where in ST it's randomly recommending me to fan of knives https://pastebin.com/nvtrsXf7 sometimes it happens with rupture too but it's quite random. But what I can tell 100% is that it always happen when deathmark and/or kingsbane are used after the fight begun for like 20-30s

That's a fallback to try and apply deadly poison because your deadly poison fell off.

**Comment by yokaii4** [comment]
> > P.S.: found a moment where in ST it's randomly recommending me to fan of knives https://pastebin.com/nvtrsXf7 sometimes it happens with rupture too but it's quite random. But what I can tell 100% is that it always happen when deathmark and/or kingsbane are used after the fight begun for like 20-30s
> 
> That's a fallback to try and apply deadly poison because your deadly poison fell off.

my poisons were up: I'm still logged in and I have 10 minutes left so not sure about it

**Comment by syrifgit** [comment]
> > > P.S.: found a moment where in ST it's randomly recommending me to fan of knives https://pastebin.com/nvtrsXf7 sometimes it happens with rupture too but it's quite random. But what I can tell 100% is that it always happen when deathmark and/or kingsbane are used after the fight begun for like 20-30s
> > 
> > 
> > That's a fallback to try and apply deadly poison because your deadly poison fell off.
> 
> my poisons were up: I'm still logged in and I have 10 minutes left so not sure about it

Deadly poison is a dot which goes onto the enemy. It's a buff on you, which also applies a debuff when you hit the enemy. In your snapshot it wasn't active on the enemy. It's the exact same as everyone who complains about fan of knives spam but they aren't using deadly poison.

**Comment by yokaii4** [comment]
> > > > P.S.: found a moment where in ST it's randomly recommending me to fan of knives https://pastebin.com/nvtrsXf7 sometimes it happens with rupture too but it's quite random. But what I can tell 100% is that it always happen when deathmark and/or kingsbane are used after the fight begun for like 20-30s
> > > 
> > > 
> > > That's a fallback to try and apply deadly poison because your deadly poison fell off.
> > 
> > 
> > my poisons were up: I'm still logged in and I have 10 minutes left so not sure about it
> 
> Deadly poison is a dot which goes onto the enemy. It's a buff on you, which also applies a debuff when you hit the enemy. In your snapshot it wasn't active on the enemy. It's the exact same as everyone who complains about fan of knives spam but they aren't using deadly poison.

oh I thought you were referring to the weapon poison. But anyway why does it recommend fok instead of mutilate for st?

**Comment by syrifgit** [comment]
Ask the rogue theorycrafters. They are the ones who determined it's the optimal way to try and reapply it in that situation.

**Comment by yokaii4** [comment]
> Ask the rogue theorycrafters. They are the ones who determined it's the optimal way to try and reapply it in that situation.

i would guess it's because it consumes less energy, then I was doing it wrong. Anyway, I think the most important points are the previous snapshot I posted

**Comment by chevyn11** [comment]
![image](https://github.com/user-attachments/assets/9db7ac4f-c08c-4cc4-bb3d-fcc069be1fb2)

**Comment by syrifgit** [comment]
Unable to replicate the deathmark issue. Looks to me like your pack is edited, as it is missing a line for a variable declaration in the stealth list, which is causing your Rupture logic to be weird. Reset your pack to default.

![image](https://github.com/user-attachments/assets/af9e5e66-bf85-49bf-8887-c984f3dd17fc)

**Comment by yokaii4** [comment]
> Unable to replicate the deathmark issue. Looks to me like your pack is edited, as it is missing a line for a variable declaration in the stealth list, which is causing your Rupture logic to be weird. Reset your pack to default.
> 
> ![image](https://private-user-images.githubusercontent.com/139663837/398023917-af9e5e66-bf85-49bf-8887-c984f3dd17fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTc3NzgsIm5iZiI6MTczNDkxNzQ3OCwicGF0aCI6Ii8xMzk2NjM4MzcvMzk4MDIzOTE3LWFmOWU1ZTY2LWJmODUtNDliZi04ODg3LWM5ODRmM2RkMTdmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwMTMxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGIyZWY5MTBhYjUxMmExNjBmNjFmNjgwNDljNGNhMjYyNDZmZjM1NzE5MzhlZjRmYTA3ZmRmMWU3ZGNmMmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9C1NNBCfFOFby5jU3f65NsOCSAJrosh1P6NCRm7eRtc)

actually worth to note that I changed race that day and did not restart the game, as in ALT F4 it. I think this was the cause. Did not know that race change could brick hekili somewhat. In fact that day i was getting shadowmeld recommendation, now i never get them for some reason
