### ISSUE TITLE
[REC] Showing incorrect Storm, Earth, and Fire icon

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#4258]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Monk - Windwalker

### Describe the Issue

When in rotation, it will be suggested to reuse Showing incorrect Storm, Earth, and Fire after the first spell ends. It will show the hunter's mark recommendation instead of Showing incorrect Storm, Earth, and Fire. Please correct this.
![Screenshot_1](https://github.com/user-attachments/assets/99424b4a-750c-48b8-9ad4-a0b50bba8471)

### How to Reproduce

Follow the rotation

### Snapshot (Link)

https://pastebin.com/GDSR9VJg

**Comment by Hekili** [comment]
It's not the Hunter's Mark icon, truly -- it's the Storm, Earth, and Fire "fixate" button that may or may not be a thing.  I'll adjust it.

**Comment by Hekili** [comment]
Resolved.
