### ISSUE TITLE
Question about what Blood DK Bone Shield

### ISSUE THREAD

**Issue by YsKylin** [Hekili/hekili#426]
Hi,I'm CN wower. I use the Blood DK. Thanks Hekili for helping me over the years. Hekili great help for my test of Shadowlands Beta.

I found a problem. I use Hekili v9.0.1-1.0-alpha36. If blood tap is talents,Ossuary is passive. Marrowrend just release the skill once. Bone Shield only＜5.when I use alpha32 no problem at all. so maybe needs optimization.

**Comment by Hekili** [comment]
I don't know what "release the skill once" means, exactly.

If you can follow the ticket instructions, providing snapshots when you see results you don't agree with (and then explaining what you want to see instead) helps me investigate these kinds of issues.

**Comment by Hekili** [comment]
I *think* I get what you mean -- the priority itself still checked for Ossuary (talent) before stacking Bone Shield above 5.  I have removed that talent check.  However, it's worth noting that this means the addon is going to recommend stacking Bone Shield > 5 before you get the Ossuary effect from leveling.  But I'm okay with it.
