### ISSUE TITLE
[REC] Suggestions on the Enhancement Shaman's Rotation

### ISSUE THREAD

**Issue by hekilifans** [Hekili/hekili#4266]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

I've been playing the game with the Enhancement Shaman during the version from 11.05 to 11.07. I found that there should be a fixed opener rotation when using the Enhancement Shaman for AOE output. For example, the following is the guide I found on Maxroll:
Cast Primordial Wave on the way into melee to apply Flame Shock.
Cast Flame Shock on a secondary target if 6 or more targets are present.
Cast Crash Lightning.
Cast Lava Lash to spread Flame Shock.
Cast the following to build up to a Tempest proc:
Cast Stormstrike / Crash Lightning to generate Maelstrom Weapon;
Cast Chain Lightning when Maelstrom Weapon reaches 5 or more to spend it;
Once Tempest triggers from any source, move on.
Cast Tempest when Maelstrom Weapon reaches 5 or more to consume Primordial Wave.
Cast Ascendance.
Cast Doom Winds.
Cast Windstrike when it's off cooldown.
Cast Chain Lightning when Maelstrom Weapon reaches 5 or more and Windstrike when it's off cooldown.
Cast Tempest when Maelstrom Weapon reaches 8 or more whenever it procs.
Continue with normal priority.
However, it's obvious that the current recommendation is inaccurate. I feel that these output techniques need to be optimized, but I'm unable to make the modifications by myself.

### How to Reproduce

Quite often, after casting Primordial Wave, if there's no Windstrike available, it won't recommend casting Chain Lightning to trigger Tempest, which will lead to a significant reduction in DPS. Or when I have Windstrike available at the start, it will directly recommend me to use Windstrike instead of spreading Flame Shock first and then casting Primordial Wave, and so on. Besides, I think that if Windstrike is ready and the cooldown of Primordial Wave is about to end soon, Windstrike should be used after Primordial Wave.
![Uploading 微信图片_20241224143748.png…]()

### Snapshot (Link)

Since I'm not familiar with English, I didn't understand what the function of this step is. I've already uploaded the questions and pictures in the previous dialog box.

**Comment by hekilifans** [comment]
https://pastebin.com/8J4BazzD

**Comment by syrifgit** [comment]
It would be much better to compare yourself to sims (aka Raidbots) instead of a written guide on Maxroll which might not even be correct. Sims (and Hekili) are much more accurate and nuanced than a simple written guide, which overlooks many optimizations.

Unfortunately your snapshot is also very difficult to read because the data is coming through in Mandarin.
