### ISSUE TITLE
Keybind does not display when spell is modified via PvP Talent

### ISSUE THREAD

**Issue by RazeYinglet** [Hekili/hekili#428]
This relates to Frost Mage - Frozen Orb correctly updates the displayed keybind under most circumstances. However, when selecting the PvP talent 'Concentrated Coolness' this changes the spell ID, and the keybind is no longer displayed. Frozen Orb is treated as having no keybind. 
Frozen Orb spell ID is, i believe, 84714 , 
PvP Modified spell ID - still named Frozen Orb - appears to be 198149

**To Reproduce**
Activate War Mode, and select the PvP Talent Concentrated Coolness. This will remove the keybind from the ability display. Replacing this PvP talent with anything else, and the keybind will display as normal. 

**Expected behavior**
For the addon to recognise the modified version of Frozen Orb as still having a keybind set. 

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/d1HtT1Bd - This doesn't seem to include PvP Talents, but they are listed below: 
Adaptation
Frostbite
Deep Shatter
Concentrated Coldness * 
*I believe this to be what is causing this particular display error.

**Comment by Hekili** [comment]
If you open Classes/FrostMage.lua and go to teh entry for frozen_orb (it ends with a handler function), add `copy = 198149` like the following:

```        frozen_orb = {
            id = 84714,
            cast = 0,
            cooldown = 60,
            gcd = "spell",

            spend = 0.01,
            spendType = "mana",

            -- toggle = "cooldowns",

            startsCombat = true,
            texture = 629077,

            handler = function ()
                addStack( "fingers_of_frost", nil, 1 )
                if talent.freezing_rain.enabled then applyBuff( "freezing_rain" ) end
                applyBuff( "frozen_orb" )
                applyDebuff( "target", "frozen_orb_snare" )
            end,

            copy = 198149
        },
```

Save, reload UI, and see if the binding resolves itself.  If so, I'll update and fix.

**Comment by RazeYinglet** [comment]
Confirming the " copy = 198149 " line corrected the hiccup, and the keybind updates properly with both the modified and base spell ID. 

Thankyou :>
