### ISSUE TITLE
Rotation buttons not showing on only 1 of my 12 characters

### ISSUE THREAD

**Issue by Evborg3000** [Hekili/hekili#430]
Hi,  I love this addon!
i use it on 12 alts.  only one character has a problem, my discipline alt doesn't have the buttons appear.  i reset it to default and made sure everything was enabled (followed the trouble shooting suggestions). still not showing up on this character.

**PUT ERROR MESSAGE(S) HERE:**
build: v8.3.0-13
level: 120 (120)
class: PRIEST
spec: discipline

talents: angelic_feather
    contrition
    lenience
    power_word_solace
    purge_the_wicked
    schism
    shining_force

azerite: depth_of_the_shadows = 1
    sudden_revelation = 1

essences: none*, none

sets/legendaries/artifacts: none

gear: azshari_stormsurger_cape = 1
    cobra_charmers_ring = 1
    cracked_crawg_shackles = 1
    heart_of_azeroth = 1
    honorable_combatants_satin_belt = 1
    honorable_combatants_satin_boots = 1
    honorable_combatants_satin_bracers = 1
    kortheks_greatstaff = 1
    owlseye_loop = 1
    shirakess_grips = 1
    vile_manipulators_hood = 1
    vile_manipulators_legwraps = 1
    vile_manipulators_mantle = 1
    vile_manipulators_robe = 1
    vindictive_golem_core = 1
    white_swashbucklers_shirt = 1

corruptions: none

itemIDs: 153685, 155440, 158075, 159912, 159915, 159916, 159977, 160004, 161182, 169489, 170133, 173435, 173458, 173467, 173845, 6795

settings: enabled = true
    potionsReset = 20180919.1

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Discipline priest is not officially supported.
