### ISSUE TITLE
Didnt show hotkeys properly

### ISSUE THREAD

**Issue by Shadowjab** [Hekili/hekili#433]
![Bug](https://user-images.githubusercontent.com/71948300/94350940-f81f0480-0053-11eb-8f1f-00222cf0ed1c.png)

The Azerite Essence is binded to G but i do not why the addon shows a 5 where i have binded Vampiric Touch.

Thank you.

**Comment by Hekili** [comment]
So, the long version is long...  Action slots are shared between multiple action bars.  The addon operates on the (bad) assumption that you organize your bars consistent with the default action bar paging.  You probably didn't.  You shouldn't have to.  But I'd have to code the addon to detect people's settings from multiple action bar mods and I just haven't.

The short answer is:  if the right keybind isn't detected, you can set the keybinding manually in /hekili > Abilities > Reaping Flames > Override Keybind Text (or some such).

I'll revisit it at some point.

**Comment by Hekili** [comment]
Oop, I take it back.  I figured out a quick and dirty way to get ElvUI keybinds better.  I'll drop it into the retail release and see what happens.

**Comment by Shadowjab** [comment]
Thank you mate!

**Comment by Hekili** [comment]
Give v8.3.7-03-beta3 a try and see if it is any better.

**Comment by Shadowjab** [comment]
Works like a charm!

Thank you mate!
