### ISSUE TITLE
Arcane Mage

### ISSUE THREAD

**Issue by Snichy** [Hekili/hekili#434]
The description says Arcane Mage is a work in progress. Is this still the case?

Also, plans to keep updated in Shadowlands?

**Comment by Hekili** [comment]
Which description, where?

Shadowlands version is in active development; test versions start with 9.0 on the releases tab.

**Comment by Snichy** [comment]
Main description on Curseforge, under What is Hekili, second paragraph, in bold no less.

**Comment by Hekili** [comment]
Go ahead and give Arcane Mage a spin.  I'll update Curse.
