### ISSUE TITLE
Lua Errors, worked before update

### ISSUE THREAD

**Issue by JHaych** [Hekili/hekili#438]
**Describe the Bug/Issue**

When downloading the zip, I extract the folder hekili-9.0.1-1.0-alpha48 into the beta addons folder, the addon does not show up in the games addon manager, I rename it to 'Hekili' and it see's it, but now has 64 LUA errors

![WoWScrnShot_100220_205456](https://user-images.githubusercontent.com/72279109/94964355-95b18280-04f1-11eb-81a3-ccfba9e713a2.jpg)

![WoWScrnShot_100220_205439](https://user-images.githubusercontent.com/72279109/94964358-964a1900-04f1-11eb-8905-75481f8f966d.jpg)

**Comment by Hekili** [comment]
Extract the package, not the source code.  You didn't get any of the libraries.

**Comment by JHaych** [comment]
How do I do this? can you explain :)

**Comment by JHaych** [comment]
![Untitled](https://user-images.githubusercontent.com/72279109/94965800-08236200-04f4-11eb-84d1-16d37e61bd73.png)


This is what I have in my addons folder

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/94966929-19587880-04cc-11eb-9f0d-3c61d5b9a4af.png)

Download the first link, not the other links.

**Comment by JHaych** [comment]
I don't see this Assets anywhere? Am I being stupid lol

**Comment by JHaych** [comment]
Found it, this place is a maze for people who don't know it, thanks.
