### ISSUE TITLE
Keybind of modifier + Scrollwheel up/down showing as bar slot number rather than 'CMwU' or 'CMwD'

### ISSUE THREAD

**Issue by KyleCRat** [Hekili/hekili#439]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
- Version: Hekili v8.3.7-03

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.
- Did not see any

**Describe the Bug/Issue**
Having a keybind using a modifier + the mouse scroll wheel up or down is showing in hekili as the index of the bar slot the icon is placed rather than showing the actual keybinding. 

Example issue I am seeing:
Hekili is showing a keybind of `4`
![image](https://user-images.githubusercontent.com/7562229/94974545-e79bdd80-04dc-11eb-9539-57bc111131e7.png)
but my bars show a keybind of `CMwD`
![image](https://user-images.githubusercontent.com/7562229/94974557-eff41880-04dc-11eb-9ed1-bec2ec3f9f73.png)

**To Reproduce**
- Using ElvUI create a keybinding for a spell within your rotation of ctrl + mousewheel up or down

**Expected behavior**
I would expect the keybind to show as `CMwD` for ctrl + mousewheel down and `CMwU` for ctrl + mousewheel up

**Screenshots**
![image](https://user-images.githubusercontent.com/7562229/94974545-e79bdd80-04dc-11eb-9539-57bc111131e7.png)
![image](https://user-images.githubusercontent.com/7562229/94974557-eff41880-04dc-11eb-9ed1-bec2ec3f9f73.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://gist.github.com/KyleCRat/b8ec5f985166d00f294bf66efc0f18e6

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
N/A

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

N/A

**Comment by Hekili** [comment]
Which bar and slot # is that totem in on your action bars?

If that's Totem Mastery, type `/dump Hekili.KeybindInfo.totem_mastery` and post the output from your chat window, please.

**Comment by KyleCRat** [comment]
![image](https://user-images.githubusercontent.com/7562229/94976936-9859ab00-04e4-11eb-8059-f048c7227d05.png)
![image](https://user-images.githubusercontent.com/7562229/94976963-b6bfa680-04e4-11eb-9886-9f7b1b5348d4.png)

In elvui it is Bar: 8. with the options: { buttons: 6, buttons per row: 2 } When showing all buttons it is in the 9th position on bar 8.

This has persisted through many re-logs and a lot of different bar locations as I set up my character. 

I changed to shift + T on bar 1 position 8 and it works as expected. 
![image](https://user-images.githubusercontent.com/7562229/94977095-482f1880-04e5-11eb-8a13-68c842fa6f1d.png)
changing that working keybind to use the mousewheel works as expected as well
![image](https://user-images.githubusercontent.com/7562229/94977139-714fa900-04e5-11eb-9a29-1c109626eff2.png)


but moving back to bar 8 results in the same issue, showing as 4 rather than SMwD

**Comment by Hekili** [comment]
Which bar and button # is actually bound to 4?

**Comment by Hekili** [comment]
8.3.7-04 *might* fix this.  If not, a picture of your bars and a picture of your keybinds would be useful.

**Comment by KyleCRat** [comment]
![image](https://user-images.githubusercontent.com/7562229/94980621-571fc600-04f9-11eb-96f5-8ed401e5cc4a.png)
4 is bound to Earth Shock on bar 1, button 4
Thank you very much for the time and assistance. 

All keybinding is done through elvui. When I go to the actual key bindings menu I can not find the 8th bar that I have the totems bound to in that window. It seems that perhaps elvui allows me to bind some extra bars not normally available?

**Comment by Hekili** [comment]
Did you upgrade and try the update?

**Comment by Hekili** [comment]
And if you upgraded and are still having an issue, can you `/dump Hekili.KeybindInfo.totem_mastery` again?

**Comment by KyleCRat** [comment]
Update did the trick!
![image](https://user-images.githubusercontent.com/7562229/94981367-c13b6980-04ff-11eb-87d9-23a7430b2b31.png)
Thank you! Appreciate the assistance and Love the addon. Keep up the great work

**Comment by Hekili** [comment]
Thanks.  Do you think I should change "MwDn" to "MwD" and "MwUp" to "MwU"?

**Comment by KyleCRat** [comment]
Yeah I would agree with that, if just to keep it as short as possible. it's already a super long keybind name especially when adding some modifiers to it.
