### ISSUE TITLE
beta version wont load  get 60 diff ula errors

### ISSUE THREAD

**Issue by cm0918** [Hekili/hekili#440]
when ever i try to use this add on   for the first time on a fresh download i get this:   

Message: Interface\AddOns\hekili\Utils.lua:33: attempt to index local 'Hekili' (a nil value)
Time: Fri Oct  2 21:32:11 2020
Count: 1
Stack: Interface\AddOns\hekili\Utils.lua:33: attempt to index local 'Hekili' (a nil value)
[string "@Interface\AddOns\hekili\Utils.lua"]:33: in main chunk

Locals: addon = "hekili"
ns = <table> {
 queue = <table> {
 }
 Tooltip = HekiliTooltip {
 }
 lib = <table> {
 }
 snapshots = <table> {
 }
 Patrons = <table> {
 }
 PTR = true
 hotkeys = <table> {
 }
 auras = <table> {
 }
 TTD = <table> {
 }
 debug = <table> {
 }
 UI = <table> {
 }
 targets = <table> {
 }
 keys = <table> {
 }
 cpuProfile = <table> {
 }
 Error = <function> defined @Interface\AddOns\hekili\Utils.lua:15
 frameProfile = <table> {
 }
}
Hekili = nil
format = <function> defined =[C]:-1
gsub = <function> defined =[C]:-1
lower = <function> defined =[C]:-1
errors = <table> {
}
eIndex = <table> {
}
(*temporary) = <function> defined @Interface\AddOns\hekili\Utils.lua:33
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Hekili' (a nil value)"

then a bunch of class spec loading errors,   i get 60 diff errors  any ideas why this is

**Comment by Hekili** [comment]
You'd need to report the first error, but you probably didn't install the right file.

You need the "package" (first link under Assets), NOT the source code.

**Comment by cm0918** [comment]
i downloaded the whole zip file of v9.0.1-1.0alpha48

**Comment by cm0918** [comment]
and that was the first error

**Comment by Hekili** [comment]
Try capitalizing the folder name.  IDK.

**Comment by ChrisKader** [comment]
If you downloaded the zip from the source page instead of release page, it wont include libraries and results in the errors shown.

**Comment by ChrisKader** [comment]
Looks like v9.0.1-1.0alpha48 does not include the required libraries where v9.0.1-1.0alpha47 did previously.

**Comment by cm0918** [comment]
@ChrisKader   my folder contents contains classes, libs, textures and other files

**Comment by cm0918** [comment]
it seems it cant find a librangecheck file

**Comment by Hekili** [comment]
I rebuilt -alpha48 and the libraries appear intact.  Try redownloading and let me know.

**Comment by cm0918** [comment]
yea man it works,       i may have also downloaded from source instead of release  but thank you for your swift attention
