### ISSUE TITLE
Hekili on Shadowlands BETA

### ISSUE THREAD

**Issue by ShawnSmall43** [Hekili/hekili#441]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
on 10/1/2020 and 10/02/2020 I was using v8.3.7-03 on the Shadowlands Beta and, the addon was working fine. Today(10/03/2020) I updated to v8.3.7-04 and now I get the LUA errors that I listed below. I can not open the options panel or see any recommended abilities. I rolled back to  v8.3.7-03 and still have the LUA errors. Disabled all other addons and still experienced errors

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S)Message: Interface\AddOns\Hekili\UI.lua:1882: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct  3 14:19:02 2020
Count: 1
Stack: Interface\AddOns\Hekili\UI.lua:1882: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Hekili\UI.lua"]:1882: in function `CreateButton'
[string "@Interface\AddOns\Hekili\UI.lua"]:1513: in function `CreateDisplay'
[string "@Interface\AddOns\Hekili\UI.lua"]:2117: in function `BuildUI'
[string "@Interface\AddOns\Hekili\Options.lua"]:7964: in function `TotalRefresh'
[string "@Interface\AddOns\Hekili\Core.lua"]:198: in function <Interface\AddOns\Hekili\Core.lua:195>
[string "=[C]"]: ?
[string "@Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

Message: Interface\AddOns\Hekili\UI.lua:1882: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct  3 14:19:02 2020
Count: 1
Stack: Interface\AddOns\Hekili\UI.lua:1882: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Hekili\UI.lua"]:1882: in function `CreateButton'
[string "@Interface\AddOns\Hekili\UI.lua"]:1513: in function `CreateDisplay'
[string "@Interface\AddOns\Hekili\UI.lua"]:2117: in function `BuildUI'
[string "@Interface\AddOns\Hekili\Events.lua"]:280: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:57: in function <Interface\AddOns\Hekili\Events.lua:51>

Locals: self = <table> {
 GetTTD = <function> defined @Interface\AddOns\Hekili\Targets.lua:779
 DeserializeStyle = <function> defined @Interface\AddOns\Hekili\Options.lua:8675
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:3465
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Interface\AddOns\Hekili\Targets.lua:764
 GetPetBasedTargetSpells = <function> defined @Interface\AddOns\Hekili\Targets.lua:78
 After = <function> defined @Interface\AddOns\Hekili\Utils.lua:268
 NewSpellInfo = true
 GetNumTTDsAfter = <function> defined @Interface\AddOns\Hekili\Targets.lua:927
 UpdateDisplayVisibility = <function> defined @Interface\AddOns\Hekili\UI.lua:1630
 IsEnabled = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Interface\AddOns\Hekili\State.lua:5493
 GetPetBasedTargetSpell = <function> defined @Interface\AddOns\Hekili\Targets.lua:90
 ToggleHold = <function> defined @Interface\AddOns\Hekili\State.lua:5518
 SpecializationChanged = <function> defined @Interface\AddOns\Hekili\Classes.lua:4944
 UpdateUseItems = <function> defined @Interface\AddOns\Hekili\Events.lua:593
 SetSpecOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3377
 GetDefaults = <function> defined @Interface\AddOns\Hekili\Options.lua:521
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Interface\AddOns\Hekili\Core.lua:1076
 Options = <table> {
 }
 ReInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:172
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Interface\AddOns\Hekili\Classes.lua:4891
 State = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\Hekili\Core.lua:195
 RestoreDefault = <function> defined @Interface\AddOns\Hekili\Classes.lua:751
 CmdLine = <function> defined @Interface\AddOns\Hekili\Options.lua:8413
 IsDisplayActive = <function> defined @Interface\AddOns\Hekili\UI.lua:1688
 SetupPetBasedTargetDetection = <function> defined @Interface\AddOns\Hekili\Targets.lua:104
 ShowDiagnosticTooltip = <function> defined @Interface\AddOns\Hekili\UI.lua:2267
 Notify = <function> defined @Interface\AddOns\Hekili\Options.lua:9302
 OnInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:63
 NewModule = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Interface\AddOns\Hekili\Utils.lua:41
 DumpPetBasedTargetInfo = <function> defined @Interface\AddOns\Hekili\Targets.lua:132
 SetPackShareOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3361
 CreateButton = <function> defined @Interface\AddOns\Hekili\UI.lua:1726
 ReleaseHolds = <function> defined @Interface\AddOns\Hekili\State.lua:5550
 Deserialize = <function> defined @Interface\AddOns\Hekili\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 SaveDebugSnapshot = <function> defined @Interface\AddOns\Hekili\Hekili.lua:292
 SetSpecPref = <function> defined @Interface\AddOns\Hekili\Options.lua:3418
 GetName = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:7644
 GetSpec = <

Message: Interface\AddOns\Hekili\UI.lua:150: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct  3 14:19:19 2020
Count: 1
Stack: Interface\AddOns\Hekili\UI.lua:150: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Hekili\UI.lua"]:150: in function `StartConfiguration'
[string "@Interface\AddOns\Hekili\Core.lua"]:50: in function <Interface\AddOns\Hekili\Core.lua:46>

Locals: external = nil
scaleFactor = 1
ccolor = <table> {
 colorStr = "ffa9d271"
 b = 0.447058
 g = 0.827449
 GetRGBA = <function> defined @Interface\SharedXML\Color.lua:28
 SetRGB = <function> defined @Interface\SharedXML\Color.lua:43
 GetRGB = <function> defined @Interface\SharedXML\Color.lua:20
 OnLoad = <function> defined @Interface\SharedXML\Color.lua:9
 GenerateHexColorMarkup = <function> defined @Interface\SharedXML\Color.lua:51
 WrapTextInColorCode = <function> defined @Interface\SharedXML\Color.lua:55
 GenerateHexColor = <function> defined @Interface\SharedXML\Color.lua:47
 IsEqualTo = <function> defined @Interface\SharedXML\Color.lua:13
 SetRGBA = <function> defined @Interface\SharedXML\Color.lua:36
 r = 0.666665
 GetRGBAsBytes = <function> defined @Interface\SharedXML\Color.lua:24
 GetRGBAAsBytes = <function> defined @Interface\SharedXML\Color.lua:32
}
(*temporary) = nil
(*temporary) = HekiliNotificationMover {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface/Buttons/WHITE8X8"
 tileSize = 0
 edgeFile = "Interface/Buttons/WHITE8X8"
 tile = false
 edgeSize = 1
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
Hekili = <table> {
 GetTTD = <function> defined @Interface\AddOns\Hekili\Targets.lua:779
 DeserializeStyle = <function> defined @Interface\AddOns\Hekili\Options.lua:8675
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:3465
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Interface\AddOns\Hekili\Targets.lua:764
 GetPetBasedTargetSpells = <function> defined @Interface\AddOns\Hekili\Targets.lua:78
 After = <function> defined @Interface\AddOns\Hekili\Utils.lua:268
 NewSpellInfo = false
 GetNumTTDsAfter = <function> defined @Interface\AddOns\Hekili\Targets.lua:927
 UpdateDisplayVisibility = <function> defined @Interface\AddOns\Hekili\UI.lua:1630
 IsEnabled = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Interface\AddOns\Hekili\State.lua:5493
 GetPetBasedTargetSpell = <function> defined @Interface\AddOns\Hekili\Targets.lua:90
 ToggleHold = <function> defined @Interface\AddOns\Hekili\State.lua:5518
 SpecializationChanged = <function> defined @Interface\AddOns\Hekili\Classes.lua:4944
 UpdateUseItems = <function> defined @Interface\AddOns\Hekili\Events.lua:593
 SetSpecOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3377
 GetDefaults = <function> defined @Interface\AddOns\Hekili\Options.lua:521
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Interface\AddOns\Hekili\Core.lua:1076
 Options = <table> {
 }
 ReInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:172
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Interface\AddOns\Hekili\Classes.lua:4891
 State = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\Hekili\Core.lua:195
 RestoreDefault = <function> defined @Interface\AddOns\Hekili\Classes.lua:751
 CmdLine = <function> defined @Interface\AddOns\Hekili\Options.lua:8413
 IsDisplayActive = <function> defined @Interface\AddOns\Hekili\UI.lua:1688
 SetupPetBasedTargetDetection = <function> defined @Interface\AddOns\Hekili\Targets.lua:104
 ShowDiagnosticTooltip = <function> defined @Interface\AddOns\Hekili\UI.lua:2267
 Notify = <function> defined @Interface\AddOns\Hekili\Options.lua:9302
 OnInitialize = <function> define

Message: Interface\AddOns\Hekili\UI.lua:1717: attempt to index field 'eventsTriggered' (a nil value)
Time: Sat Oct  3 14:19:44 2020
Count: 1
Stack: Interface\AddOns\Hekili\UI.lua:1717: attempt to index field 'eventsTriggered' (a nil value)
[string "@Interface\AddOns\Hekili\UI.lua"]:1717: in function `ForceUpdate'
[string "@Interface\AddOns\Hekili\Events.lua"]:1133: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:57: in function <Interface\AddOns\Hekili\Events.lua:51>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: self = <table> {
 GetTTD = <function> defined @Interface\AddOns\Hekili\Targets.lua:779
 DeserializeStyle = <function> defined @Interface\AddOns\Hekili\Options.lua:8675
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:3465
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Interface\AddOns\Hekili\Targets.lua:764
 GetPetBasedTargetSpells = <function> defined @Interface\AddOns\Hekili\Targets.lua:78
 After = <function> defined @Interface\AddOns\Hekili\Utils.lua:268
 NewSpellInfo = false
 GetNumTTDsAfter = <function> defined @Interface\AddOns\Hekili\Targets.lua:927
 UpdateDisplayVisibility = <function> defined @Interface\AddOns\Hekili\UI.lua:1630
 IsEnabled = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Interface\AddOns\Hekili\State.lua:5493
 GetPetBasedTargetSpell = <function> defined @Interface\AddOns\Hekili\Targets.lua:90
 ToggleHold = <function> defined @Interface\AddOns\Hekili\State.lua:5518
 SpecializationChanged = <function> defined @Interface\AddOns\Hekili\Classes.lua:4944
 UpdateUseItems = <function> defined @Interface\AddOns\Hekili\Events.lua:593
 SetSpecOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3377
 GetDefaults = <function> defined @Interface\AddOns\Hekili\Options.lua:521
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Interface\AddOns\Hekili\Core.lua:1076
 Options = <table> {
 }
 ReInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:172
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Interface\AddOns\Hekili\Classes.lua:4891
 State = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\Hekili\Core.lua:195
 RestoreDefault = <function> defined @Interface\AddOns\Hekili\Classes.lua:751
 CmdLine = <function> defined @Interface\AddOns\Hekili\Options.lua:8413
 IsDisplayActive = <function> defined @Interface\AddOns\Hekili\UI.lua:1688
 SetupPetBasedTargetDetection = <function> defined @Interface\AddOns\Hekili\Targets.lua:104
 ShowDiagnosticTooltip = <function> defined @Interface\AddOns\Hekili\UI.lua:2267
 Notify = <function> defined @Interface\AddOns\Hekili\Options.lua:9302
 OnInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:63
 NewModule = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Interface\AddOns\Hekili\Utils.lua:41
 DumpPetBasedTargetInfo = <function> defined @Interface\AddOns\Hekili\Targets.lua:132
 SetPackShareOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3361
 CreateButton = <function> defined @Interface\AddOns\Hekili\UI.lua:1726
 ReleaseHolds = <function> defined @Interface\AddOns\Hekili\State.lua:5550
 Deserialize = <function> defined @Interface\AddOns\Hekili\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 SaveDebugSnapshot = <function> defined @Interface\AddOns\Hekili\Hekili.lua:292
 SetSpecPref = <function> defined @Interface\AddOns\Hekili\Options.lua:3418
 GetName = <function> defined @Interface\AddOns\Hekili\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:7644
 GetSpec = <

**Comment by SpatenLa** [comment]
you are using the retail version, the version for 8.3.7, download the beta version that starts with 9.0.0

**Comment by ShawnSmall43** [comment]
looks like I need to turn off auto updates on twitch. I looked but have not found the 9.0.0 version.

**Comment by Hekili** [comment]
Go to "releases" on this site.
