### ISSUE TITLE
SLAM not being recommended for Arms warrior

### ISSUE THREAD

**Issue by Smexhy** [Hekili/hekili#443]
Hey, I am not sure if this is bug or not, so I gotta ask first. I play as arms warrior with 2H weapon, but one of the main abilities "Slam" is never being recommended. Is this right? It's like one of the main abilities that arms war has so it's little weird that it is just not being recommended at all.

Hope I can get some info about this. Thanks.

**Comment by Hekili** [comment]
Fervor of Battle talent Slams when you Whirlwind.
