### ISSUE TITLE
Elemental Shaman Issues

### ISSUE THREAD

**Issue by Finadama** [Hekili/hekili#445]
Hi there. I have been having a lot of fun playing on Beta with this addon, but I have noticed a couple of issues:

1) It never suggests Stormkeeper, even though I have it talented.
2) A number of times, it will let me overcap on maelstrom before ever suggesting Earth Shock
3) A lot of the time, it will suggest Echo of the Elements prior to a Flame Shock.

**Comment by Hekili** [comment]
Please follow the ticket instructions when submitting issues with recommendations. Thanks!

**Comment by Hekili** [comment]
Elemental has been updated for 9.0 release.  If you see new issues, make a new report with detailed information.  Thanks.
