### ISSUE TITLE
Brand New Install - Nothing Showing

### ISSUE THREAD

**Issue by xEelonx** [Hekili/hekili#448]
Brand New Install - Nothing Showing

Have done https://www.curseforge.com/wow/addons/hekili "Troubleshooting"

A. /hekili > General: Make sure Enabled is checked. If it's not checked, the addon may have detected an error and shut itself off. If that is the case, use an addon like BugSack/BugGrabber to collect any error messages and submit it via the ticket tracker (linked above). If the addon is enabled and nothing is showing, check your displays. /hekili > Displays > Primary and AOE.  Check the alpha (transparency) settings on the Visibility tab.  If your issue is with one of the default displays, you can create a new profile and see if your displays are shown.

Add on is enabled and transparency are set to 1.

build: v8.3.7-04
level: 111 (111)
class: PRIEST
spec: discipline

talents: angelic_feather
    castigation
    dominant_mind
    lenience
    mindbender
    purge_the_wicked
    sins_of_the_many

azerite: contemptuous_homily = 1

essences: none*, none

sets/legendaries/artifacts: none

gear: celumbra_the_nights_dichotomy = 1
    crown_of_the_champion = 1
    dominant_gladiators_signet = 1
    felknight_greatcloak = 1
    fierce_combatants_signet = 1
    guild_tabard = 1
    heart_of_azeroth = 1
    jarkadiaxs_other_eye = 1
    lights_wrath = 1
    loa_speakers_leggings = 1
    mistbound_helarjar_footwraps = 1
    neophytes_shirt = 1
    night_dreamer_handwraps = 1
    riven_priesthood_sash = 1
    sunfrost_robes = 1
    tunnel_fiend_bracers = 1
    velens_future_sight = 1

corruptions: none

itemIDs: 128868, 133608, 134435, 139087, 139127, 144258, 146666, 146876, 146886, 148565, 149669, 155328, 158075, 159074, 160913, 53, 5976

settings: enabled = true
    potionsReset = 20180919.1

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = true
[Hekili.pdf](https://github.com/Hekili/hekili/files/5370274/Hekili.pdf)

**Comment by Hekili** [comment]
Discipline is not officially supported at this time.
