### ISSUE TITLE
Demon Hunter : Error on "Abilities" Menu options

### ISSUE THREAD

**Issue by StoirmDH** [Hekili/hekili#449]
Message: Interface\AddOns\Hekili\Options.lua:3641: attempt to concatenate field 'name' (a nil value)
Time: Tue Oct 13 16:47:23 2020
Count: 1
Stack: Interface\AddOns\Hekili\Options.lua:3641: attempt to concatenate field 'name' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Hekili\Options.lua"]:3641: in function `member'
[string "@Interface\AddOns\WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@Interface\AddOns\WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:329: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:316>
[string "@Interface\AddOns\WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1121: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: in function `FeedGroup'
[string "@Interface\AddOns\WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...face\AddOns\WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>

Locals: <none>

build: v9.0.1-1.0-alpha54
level: 60 (60)
class: DEMONHUNTER
spec: havoc

talents: burning_hatred
    cycle_of_hatred
    demonic
    demonic_appetite
    master_of_the_glaive
    soul_rending
    unbound_chaos

covenant: venthyr

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: arachnid_cipher_ring = 1
    corpsehide_gloves = 1
    phial_of_putrefaction = 1
    ritual_commanders_ring = 1
    sinful_aspirants_blade = 1
    sinful_aspirants_drape = 1
    sinful_aspirants_leather_belt = 1
    sinful_aspirants_leather_boots = 1
    sinful_aspirants_leather_breeches = 1
    sinful_aspirants_leather_helm = 1
    sinful_aspirants_leather_spaulders = 1
    sinful_aspirants_leather_wristwraps = 1
    sinful_aspirants_necklace = 1
    umbrahide_vest = 1
    withergrove_shardling = 1

legendaries: fel_bombardment = 1

itemIDs: 172314, 175859, 175866, 175870, 175871, 175878, 175883, 175885, 178265, 178670, 178771, 178781, 178933, 181459, 181660

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 7
    nameplates = true
    package = Havoc
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    demon_blades_acknowledged = false
    recommend_movement = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

Please, note that this menu works fine on other classes, except the Demon Hunter. 
![image](https://user-images.githubusercontent.com/72810425/95877469-6d891580-0d74-11eb-8f6e-ef65d6c84d25.png)

**Comment by Hekili** [comment]
Thanks, fix will be in pre-patch release.
