### ISSUE TITLE
Shadow priest lua error with build: v9.0.1-1.0-alpha55 when turning on Cooldowns option

### ISSUE THREAD

**Issue by Sweetcorp** [Hekili/hekili#450]
I hope this is what you need.

**Screenshots**
https://gyazo.com/548823842e47dd02c86cfc0deca254a4
https://gyazo.com/1b564a857fd8b0cadf7dc04ea9bb7602
https://gyazo.com/670c628fad712c4cc68eeb8b0c5a1479

**WHEN SUBMITTING AN ISSUE:**
https://pastebin.com/j1kJtHek

 
**PUT SNAPSHOT LINK HERE:**
It will not allow me to snapshot or pause.

**PUT ERROR MESSAGE(S) HERE:**
https://pastebin.com/CsUvZUBa
https://pastebin.com/cr02zpzW
https://pastebin.com/6RAEnvad

**Comment by Hekili** [comment]
Thanks.  Fixing this.  Wish I'd caught it 5 minutes ago.

**Comment by Sweetcorp** [comment]
Sorry took me a while to get it all set up to send to you while at work.

**Comment by Hekili** [comment]
Haha, no problem.  Will be fixed in the pre-patch build.

**Comment by Sweetcorp** [comment]
Awesome, thanks a ton for what you do <3
