### ISSUE TITLE
Affliction Warlock channelling 

### ISSUE THREAD

**Issue by Lipstopica** [Hekili/hekili#451]
Beta Affliction Warlock.
Basically it's going through an entire channel of Drain Soul before it will suggest anything else. Not suggesting a dot or Rapture when vile taint is ticking, during the channel of Drain Soul.
I think it's pretty important to suggest to use a dot/Rapture instead of going through an entire channel of Drain Soul without a single dot then to suggest using dot/rapture.

https://pastebin.com/xH6Pr74K

**Comment by Lipstopica** [comment]
Also forgot to mention this is with the settings "Extend Cooldown Sweep".  Which is on by default.

**Comment by Hekili** [comment]
There's no logic in the current SimC priority that would prompt you to break a Drain Soul channel.  Have you looked at your sims to see if your sim casts the whole Drain Soul?

**Comment by Hekili** [comment]
Improvements made in 1.0.5, as discussed.
