### ISSUE TITLE
Addon is blocked when trying to teleport

### ISSUE THREAD

**Issue by derekengel** [Hekili/hekili#452]
On my mage, when trying to teleport to a city, the addon is blocked by Blizzard.  Using the spellbook, teleport spell.

**Comment by Hekili** [comment]
Submit a complete, proper ticket with the error(s).  Thanks!

**Comment by derekengel** [comment]
There are no errors to submit or I would.  It just gets blocked by Blizzard via popup.

**Comment by Hekili** [comment]
Disable all your other addons and then confirm if you continue to get the message.

If it happens with only Hekili loaded, post a screenshot.  Thanks!
