### ISSUE TITLE
Enhancement Shaman: Flametongue & Windfury not disappearing from Queue once applied

### ISSUE THREAD

**Issue by ShadowforgeArani** [Hekili/hekili#454]
**Describe the Bug/Issue**
The flametongue and windfury weapon spell reminders aren't disappearing once the spell is applied. 

**To Reproduce**

- For me personally I have hekili show when targetting mob
- Click on Flametongue & Windfury weapon spells

**Expected behavior**
After applying the Flametongue Weapon & Windfury Weapon spells to weapons, I expected the icons to disappear from the rotation interface. This hasn't happened. 

**Screenshots**
![image](https://user-images.githubusercontent.com/72868347/95987696-afbb6100-0e1f-11eb-8c75-c08e913c6679.png)

**WHEN SUBMITTING AN ISSUE:**

build: v9.0.1-1.0.2
level: 50 (50)
class: SHAMAN
spec: enhancement

talents: ascendance
    elemental_assault
    feral_lunge
    lashing_flames
    spirit_wolf
    stormflurry
    sundering

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    bilestained_crawg_tusks = 1
    dread_captains_irons = 1
    dreamers_unblinking_pauldrons = 1
    ebony_scaled_gauntlets = 1
    gaolers_chainmail_gaiters = 1
    harlans_loaded_dice = 1
    heart_of_azeroth = 1
    helm_of_actualized_visions = 1
    last_vestige_of_neltharion = 1
    nefarious_tormentors_belt = 1
    renowned_guild_tabard = 1
    ring_of_collective_consciousness = 1
    sabatons_of_coruscating_energy = 1
    thornwoven_band = 1
    unguent_caress = 1
    vitacharged_titanshard = 1

legendaries: none

itemIDs: 155881, 158075, 159372, 159388, 159392, 159653, 162548, 169223, 172197, 173452, 174147, 174149, 174151, 174153, 174500, 174530, 69210

settings: aoe = 2
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = superior_battle_potion_of_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Thanks for the report.  I'm in the process of fixing this now and will post a new build in a minute.

The short answer is that I was destroying some data when you change specs that shouldn't have been destroyed.  Oops.  Testing now, fix in 10 minutes or so.

**Comment by ShadowforgeArani** [comment]
Keep up the hard work! Patch day is always a stress fest <3 You're doing amazing.
