### ISSUE TITLE
On use trinket not in rotation

### ISSUE THREAD

**Issue by praiseshiva** [Hekili/hekili#455]
Addon has been updated to most recent version.

On use trinket, specifically Pocket-Sized Computation Device not coming up in rotation.

Snapshot:
https://pastebin.com/AxEvJq1G

Thanks!

**Comment by Hekili** [comment]
Current priority for Havoc saves usable items for Metamorphosis (which is a bit odd for something like the PSCD).  I'll take a look.

**Comment by Hekili** [comment]
Should be available in 1.0.5.

**Comment by praiseshiva** [comment]
Thanks! I appreciate your quick response and the effort you put into your addon. Keep your feet on the ground.
