### ISSUE TITLE
Keybind snyc from Bindpad

### ISSUE THREAD

**Issue by MattMer** [Hekili/hekili#456]
Hello,

I believe Hekili should utilize keybinds from the addon Bindpad, as it's a popular keybind manager and what i use for all of my characters. Currently Hekili doesn't detect these addons so i have to manually input my keybinds.

**Comment by Hekili** [comment]
I'll look into it.  If you can provide your Bindpad config files, that would help me get some idea of how it stores binding data.

**Comment by Hekili** [comment]
Closing; never received Bindpad config files.
