### ISSUE TITLE
Subtlety Rogue Missing PVP talent Cold Blood

### ISSUE THREAD

**Issue by MCampbell1092** [Hekili/hekili#457]
**Describe the Bug/Issue**
Cold Blood[Instant](Requires Stealth) - When Activated, your next Cheap Shot or Shadowstrike will deal up to 10%
of the target's total health in Shadow damage.

Even when trying to manually add the skill from the Action List it does not appear.

**To Reproduce**
- Go to 'Priorities > Subtlety > Action List'
- Click on 'Action'
- Scroll down to 'Cold Blood'
- Item missing.

**Expected behavior**
Ability to manually add this skill to the required rotation.
![WoWMissingSkill](https://user-images.githubusercontent.com/72885553/96028121-84844200-0e1e-11eb-9be6-abfc6feccd2f.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.
https://pastebin.com/NeT3UPjK

**Comment by MCampbell1092** [comment]
As I'm looking further in to it, I just want to note that none of my PVP talents are working with Hekili at the moment.

**Comment by Hekili** [comment]
Yep, PvP talents aren't available in real PvE content, so they're only added upon request or if there's a need (i.e., the Azerite that gave you a PvP talent).

**Comment by MCampbell1092** [comment]
Any chance I could make a request for it then?  Or maybe guide me a little on what to change in order to add it myself?  I'm using Hekili for PVP and reminding me to use cold blood would be really nice.  If not I understand, I'm sure you're super busy with this addon since pre-patch just came out.

**Comment by Hekili** [comment]
Just provide a list of which ones you actually need.  If they cause a buff/debuff, knowing the buff/debuff ID would be helpful as well (can source that from Wowhead).

**Comment by MCampbell1092** [comment]
https://www.wowhead.com/spell=213981/cold-blood
Causes a BUFF, requires stealth.
Spellid=213981

This is the only one I need.

Thank you Hekili!

**Comment by Hekili** [comment]
This will be in 1.0.10.
