### ISSUE TITLE
Spellflash not working in Shadowlands pre-patch?

### ISSUE THREAD

**Issue by herrde** [Hekili/hekili#458]
Hi,

how do I get SpellFlash to work with Hekili? I have installed SpellFlash and SpellFlashCore, yet none of my icons in my action bars are flashing. I have enabled SpellFlash within Hekili though.

Am I missing something?

Thanks for your help!

Best

**Comment by Hekili** [comment]
I honestly have no idea if SpellFlash still works at all.

**Comment by herrde** [comment]
...I see... well, is there any other way to get the icons of the recommended skills flashing in the action bars apart from SpellFlash...?

**Comment by Hekili** [comment]
Nothing that I'm aware of.  Do you have any error messages or anything?

**Comment by herrde** [comment]
..no, nothing....

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/96053256-30448680-0e4d-11eb-828c-7996f56a296f.png)

![image](https://user-images.githubusercontent.com/9438134/96053267-363a6780-0e4d-11eb-88d0-58f683afe6d4.png)

I'm not seeing any issues.  Have you updated your addons?

**Comment by herrde** [comment]
...that's exactly what my setting is. And yes, all addons are up to date.... so you're saying that your icons are flashing in the action bars...?

**Comment by Hekili** [comment]
Yeah, it works for me.  I only have SpellFlashCore installed.

**Comment by herrde** [comment]
...ok, I have just deinstalled SpellFlash and installed just SpellFlashCore, but no change... strange that it works on your end... well thanks anyway for your help, much appreciated!

**Comment by Hekili** [comment]
It could be an action bar addon compatibility issue between SpellFlash and whatever you're using.  That'd be my best guess.
