### ISSUE TITLE
Blood talons not showing on the rotation and swapping from aoe to sgt mid fight at wrong times

### ISSUE THREAD

**Issue by moxx255** [Hekili/hekili#462]
hello, 
so i have been using the addon since BFA and i have found it very useful altho i play feral druid and have noticed that blood talons does not show at any point..
i have also witnessed that my rotation will change mid fight and go to AOE whilst im in single target and its very confusing.
BFA had it perfect with rotation and it change accordingly to the correct amount of targets.

any way i can resolve this please give me advice otherwise please can you fix this..

many thanks 
robb

**Comment by Hekili** [comment]
?
