### ISSUE TITLE
Affliction Rotation

### ISSUE THREAD

**Issue by kusosando** [Hekili/hekili#464]
**Describe the Bug/Issue**
The rotation for affliction warlocks is broken.  The priority now seems to be stuck in an infinite loop of Unstable Agony and nothing else shows up.

**To Reproduce**
This issue occurs every time I set my spec to affliction.

**Expected behavior**
I expected to be given a priority rotation based on MR.

**Comment by Hekili** [comment]
Submit a complete and proper ticket, thanks!
