### ISSUE TITLE
Affliction Warlock Priority

### ISSUE THREAD

**Issue by kusosando** [Hekili/hekili#465]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
After the latest update, the rotation/priority for Affliction seems to get stuck on Unstable Agony.

**To Reproduce**

This error presents itself whenever I spec into affliction.

**Expected behavior**
Before the latest update the rotation/priority was dynamic and included things like MR, Corruption, etc.

**Screenshots**

https://imgur.com/a/fLs896k

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here. 

https://pastebin.com/kMZNreuf

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.

https://pastebin.com/YvX2UUM8

**Comment by Hekili** [comment]
Update to 1.0.7 and retest.

**Comment by kusosando** [comment]
same results w/ 1.0.7

https://pastebin.com/rAQJLN3X

**Comment by Hekili** [comment]
Do you have any errors in BugSack / BugGrabber?  None of your Azerite gear is detected.  The second Unstable Affliction is intended to proc your calamity azerite, but looks like there's a problem in your case.

**Comment by kusosando** [comment]
I have some bugs in there but nothing related to the Hekili addon.

**Comment by Hekili** [comment]
Can you try reloading your UI (/reload) and checking /hek > Issue Reporting for the line that says `azerite:` to see if it shows your Azerite.

Mine is actually `none` right now, too.

**Comment by kusosando** [comment]
With Addons Enabled: https://pastebin.com/iLAbKy11

With only Hekili Enabled: https://pastebin.com/1NBLYvgQ

That's the latest

**Comment by kusosando** [comment]
mine also says none:

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

**Comment by Hekili** [comment]
Thanks, this helped identify a bug in Azerite and Essence detection.  I think I have it solved.  Then we can test again in 1.0.8.  :)

**Comment by kusosando** [comment]
1.0.8 looks like a winner!

**Comment by Hekili** [comment]
There will be more iteration on Affliction, but glad this is resolved.  Thanks for working through it.

Note that there's no real effort to set up Seed of Corruption for AOE yet.
