### ISSUE TITLE
Moonfire/Starfire/Stellar Flare - Moonkin

### ISSUE THREAD

**Issue by tharpy35** [Hekili/hekili#466]
Moonfire, Stellar Flare and Starfire are being refreshed too soon. All three of them are being refreshed with 5-7 seconds left of the original DoT. They are not that large of Astral Power generators and the damages is being clipped off too soon. All of them tick every 1.5-1.7 seconds. Moonfire and Starfire are instant casts, Stellar Flare is not. Please correct the refresh rates to have them not clip 4 ticks worth of damage.

**Comment by Hekili** [comment]
Please fill out a complete and proper ticket, thanks!
