### ISSUE TITLE
Large Number of Error Messages

### ISSUE THREAD

**Issue by Aphoristic** [Hekili/hekili#467]
**Describe the Bug/Issue**
Hekili causing a large number of errors.

**To Reproduce**
- Enter combat with an enemy.  Only tried as a fire mage so far.

**Expected behavior**
No errors.

**PUT ISSUE REPORT LINK HERE:** https://pastebin.com/NGdwXZXJ

**PUT ERROR MESSAGE(S) HERE:**
129x Hekili\State.lua:6233: bad argument #2 to 'max' (number expected, got function)
[string "=[C]"]: in function `max'
[string "@Hekili\State.lua"]:6233: in function `TimeToReady'
[string "@Hekili\Core.lua"]:724: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:1256: in function `GetNextPrediction'
[string "@Hekili\Core.lua"]:1534: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:825: in function <Hekili\UI.lua:689>

Locals:
(*temporary) = 0
(*temporary) = <function> defined @Hekili\State.lua:922
(*temporary) = "number expected, got function"

**Comment by Hekili** [comment]
Is that the entirety of the error message?

**Comment by Hekili** [comment]
Fixed in 1.0.9.
