### ISSUE TITLE
Demonology LUA error

### ISSUE THREAD

**Issue by badinplaid737** [Hekili/hekili#468]
Message: ...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:209: attempt to compare number with nil
Time: Thu Oct 15 11:04:30 2020
Count: 122
Stack: ...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:209: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface\AddOns\Hekili\Classes\WarlockDemonology.lua"]:209: in function <...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:103>
[string "@Interface\AddOns\Hekili\Classes.lua"]:676: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:54: in function <Interface\AddOns\Hekili\Events.lua:48

Using ElvUI with shadow and light, add on skins, projectArizoka, skada and ask mr robot

**Comment by Hekili** [comment]
Where's the rest of the ticket info?

**Comment by Hekili** [comment]
Should be fixed in 1.0.10 though.
