### ISSUE TITLE
Moonfire/Starfire/Stellar Flare Refreshing too Soon

### ISSUE THREAD

**Issue by tharpy35** [Hekili/hekili#469]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.  - Up to date

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports. - Nope

**Describe the Bug/Issue**

Moonfire/Starfire/Stellar Flame are refreshing too soon in the rotation. 3-5 ticks are being clipped off as they tick 1.2-1.7 seconds and the DoT is refreshed at 5-7 seconds remaining.

**To Reproduce**
Run rotation for Moonkin

**Expected behavior**
Moonfire/Starfire are not big Astral Power generators. DoT uptime should be maximized to get full duration of damage. Moonfire/Starfire should be refreshed on 1 tick remaining. Stellar Flame cast should end with 1 tick remaining.

**Comment by Hekili** [comment]
Please don't just delete the instructions.  Provide the snapshot information that the ticket asks for.

**Comment by Hekili** [comment]
Also, I'm not sure why you think you need to wait until the last tick of Moonfire and Sunfire, but that's not correct.  The priority refreshes them when they're under 30% duration, at which point you do not lose any uptime.

**Comment by Hekili** [comment]
I rechecked that Stellar Flame also refreshes at 30% without losing uptime.  There's no reason to wait until the last second.

**Comment by tharpy35** [comment]
Yep, after review, that is my bad

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 15, 2020 at 12:19 PM, Hekili<notifications@github.com> wrote:   


Also, I'm not sure why you think you need to wait until the last tick of Moonfire and Sunfire, but that's not correct. The priority refreshes them when they're under 30% duration, at which point you do not lose any uptime.
