### ISSUE TITLE
Suggestions:  Audio Prompts

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#47]
Love the addon, was using hero-rotaion and that was good also but I like seeing "into the future".

So, my suggestion is to provide sounds, yes sounds to assign to skills that are part of the rotation.
The sound would only trigger on the last (4th or 1st, depending on how you count the final icon)

The sounds should be single tone, like a bing, bong, 1bell, etc (no clapping or ringing or any long sounds)

The sounds would queue the user to hit whatever button is associated with that skill, thus the user does not need to constantly monitor the flow, sound would key him/her as to what to hit on the keyboard.

He/she would only need to look occasionally to see whats upcoming and the rest of the time use their eyes for more important things, like there surroundings/environment. Right now our sense of hearing is being wasted by Hekili not using it.

I play Outlaw/Assassination Rogue and I would at most use four sound (for Outlaw):
Dispatch
Pistol Shot
Slice and Dice
(maybe) Between the Eyes and or Vanish

But if you provide lets say 7 or 8 sounds (single tone) that should cover just about everything.

This would allow me to keep my eyes on the game and not so much on Hekili, sound good?!!

Thank you,
Pete

**Comment by Hekili** [comment]
I really do like the sound suggestion -- I've gotten feedback from one person who plays in tandem with a blind sibling, and they use WeakAuras to play sounds when specific abilities are recommended.  So one of them controls movement and targeting, while the other controls abilities.

It is something I can add, but I have to consider how to deal with situations where people are using two displays and/or have interrupts and defensives separated into their own displays.  Otherwise, you'd hear an orchestra every time recommendations changed.

**Comment by petesmisc** [comment]
I would say to let the players decide what sounds to bind to what actions, for me, interrupts are more or less displayed by DBM in raids so I would not use that myself in a raid, same for Dungeons ( I think DBM warns to Interrupt, etc)

But the bottom line is that the players can decide what to hear and what not, for me the key thing to hear is the rotation so I don't have to take my eyes off of whats going on around me.

Also, this could be done in stages, first the Rotation sound binds and than go from there :)

I currently use Weak Auras to sound off on five combo points (or six if I'm talented for that), buts its limited at this point.

I really hope this can be done, it would put all other rotation addons to shame!

**Comment by petesmisc** [comment]
I would say to let the players decide what sounds to bind to what actions, for me, interrupts are more or less displayed by DBM in raids so I would not use that myself in a raid, same for Dungeons ( I think DBM warns to Interrupt, etc)

But the bottom line is that the players can decide what to hear and what not, for me the key thing to hear is the rotation so I don't have to take my eyes off of whats going on around me.

Also, this could be done in stages, first the Rotation sound binds and than go from there :)

I currently use Weak Auras to sound off on five combo points (or six if I'm talented for that), buts its limited at this point.

I really hope this can be done, it would put all other rotation addons to shame!

**Comment by petesmisc** [comment]
Oh, it just occurred to me that the simplest sounds would be just someone saying the number (fast, like in New York, lol) one, two, three, four, f1, f2, etc...

There would be no doubt as to what is being implicated and someone that has an issue with "sound" would be better served with a spoken word (although sound should be included as well).

Don't know if sounds like that already exist or not, I guess that the hard would be getting the "sounds".

Thanks,
Pete

**Comment by Smoothglobal** [comment]
This is such a great suggestion. I would be very thankful to just hear a number "1, 1, 4, 3" etc. Great suggestion!

**Comment by Hekili** [comment]
I'm closing this ticket since it's remained idle and doesn't fit in current priorities.  It would become a Project if/when it is pursued.
