### ISSUE TITLE
Affliction Warlock Rotation not showing Summon Darkglare or Dark Soul Misery

### ISSUE THREAD

**Issue by Macneel** [Hekili/hekili#470]
Not exactly sure where to put this, but this is my first time using Hekii and unless it is intended, when i go thru the rotation and follow the recommended spells/abilities shown for an Affliction Warlock, it is currently never showing Summon Darkglare or Dark Soul Misery.

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/wiki/Getting-Started

**Comment by Macneel** [comment]
Thank you so much for the Getting Started link.

In the Affliction Action List, 

The criteria for both Step 12 : Call Action List darkglare_prep & 13: Dark Soul Misery are apparently not happening, preventing the recommendation to cast both those abilities in the rotation.

**Comment by Hekili** [comment]
Please follow the ticket instructions and post a snapshot (instructions will explain) when this is happening for you.

Do you have Cooldowns toggled on?
