### ISSUE TITLE
ProtPally missing Crusader Strike - hammer icon instead?

### ISSUE THREAD

**Issue by NostraDavid** [Hekili/hekili#473]
**BEFORE SUBMITTING AN ISSUE:**

This is for v9.0.1-1.0.11

**Describe the Bug/Issue**
When following the rotation, there's a hammer icon, without key binds. I don't recognize the icon, but I think it probably should be the Crusader Strike instead, because that is the only ability that is missing from the rotation.

**To Reproduce**
- Pick Protection Paladin
- Attack an enemy
- See that an unbound hammer icon shows up
- See that no Crusader Strike shows up

**Expected behavior**
I expect a Crusader Strike instead of an unbound hammer icon

**Screenshots**

It's the first icon

![ProtPally](https://user-images.githubusercontent.com/55331731/96268130-f7312100-0fc8-11eb-81d0-e93de4166d75.png)

**Character Data**

https://pastebin.com/nmA8PJJ9

**Comment by Hekili** [comment]
The addon warns you that it's for current content (level 50+) when you first start combat.  There are abilities that change a lot over the course of leveling, and modeling them all would require tons of maintenance and take up CPU time at level cap.

**Comment by NostraDavid** [comment]
I figured out what went wrong in my case:
I had Hammer of the Righteous before the Level Crunch, but because of the level crunch, I lost that ability, which conflicted with Hekili - this didn't happen before the level crunch. I am now level 14 and just regained the ability, which made this bug click in my head.

My bad, apologies for the wasted time :)

PS: I'm a Starter Edition player, so I'll never be able to get to 50 anyway Sadge

edit: I'm aware it actually warned me. I just didn't know **what it warned me for/about**.

**Comment by Hekili** [comment]
Enjoy the Starter Edition.

Yeah, the addon generally assumes you have the full repertoire of level 50 skills available to you, and the way Blizzard gradually replaces some abilities over time doesn't line up with what the addon is looking for.  Any usage below the "current" content is at your own risk.  But I hope you're having fun!
