### ISSUE TITLE
Warlock demonology's rotation priority is wrong, spell "implosion" never appears

### ISSUE THREAD

**Issue by slipkorn20** [Hekili/hekili#475]
Warlock demonology's rotation priority is wrong, spell "implosion" never appears, 

**https://pastebin.com/M1XnChf5**

**Comment by Hekili** [comment]
Yup, the Warlock theorycrafters have communicated that AOE priorities are not-yet-implemented as of yesterday, but I'll incorporate changes as they come out.

**Comment by Hekili** [comment]
FWIW, the next build will have Implosion, new sims have come out.
