### ISSUE TITLE
Aff lock rotation issue

### ISSUE THREAD

**Issue by MaddyLif3** [Hekili/hekili#476]
Affliction lock rotation is still showing unstable affliction stacking with shards instead of suggesting malefic rupture to dump shards. You can only cast one unstable affliction now. Below is screenshot of the issue.

https://imgur.com/ksyRrj8

**Comment by Hekili** [comment]
Fill out a proper ticket if you'd like to explore further, but you're probably wearing Cascading Calamity azerite and referring to when it procs your haste buff.

**Comment by MaddyLif3** [comment]
ah good call, thank you for that!
