### ISSUE TITLE
Affliction AOE optimization

### ISSUE THREAD

**Issue by Devilwench** [Hekili/hekili#479]
Hi,

So currently, when the Vile Taint talent is taken, Hekili assumes that should be the first thing cast.  This should not generally be the case as you're setting up for as many Malefic Raptures as possible and it means that VT will fall off before you get to the end.  You'll generally want to put the other dots (at least agony/corruption, and potentially UA/Siphon depending on situation and talents), then VT, then 4-5 MR's.  It may be that it's assuming that you're going to go into a Dark Caller and get a duration extension, so as an opener, not actually bad, but less optimal than it could be.  Even if you have DR, the extra tick chance for getting a shard will be better than the tick on VT.

**Comment by Hekili** [comment]
Many priorities are still being theorycrafted by their respective class/spec groups.  Everything you're saying is probably valid, but the way to prove it would be with some sim testing that can be translated into the addon.  You're welcome to do some of that testing and provide data or to wait for theorycrafters to sort more out.  Thanks!

**Comment by seathasky** [comment]
The addon is literally not procc'ing malefic at all, even after casting all dots. The addon is just doing a bad job on a base spell.

**Comment by Hekili** [comment]
I've played a fair amount of Affliction this week, and know that's not accurate. If you're actually seeing that happen, follow the instructions to fill out a complete ticket with snapshot and I'll be happy to investigate.

**Comment by seathasky** [comment]
https://www.youtube.com/watch?v=XCAWO1rfLTc  video might be processing still. looks like a lot of shadow bolts to me. on latest version of hek as well. cleared wtf saved variables as well just to make sure.

**Comment by Hekili** [comment]
I'll look, but you still need to read the instructions so you can submit the snapshot that allows for investigating the issue.

**Comment by seathasky** [comment]
I'm not sure how to do that. Similar to what i just did here on a seperate ticket you mean?

**Comment by Hekili** [comment]
When you go to submit an issue here, it starts prefilled with instructions.

**Comment by Lipstopica** [comment]
In current APL without the azerite cascading calamity it wont use Rapture unless you have vile taint dot on the target, I believe.

**Comment by Hekili** [comment]
Same deal, submit a ticket that has a snapshot of what you're describing. Thanks.

**Comment by Lipstopica** [comment]
Oh no I am not putting it as a bug, just saying thats why its not showing Rapture. Which is why it's not suggested to use Hekili low levels

**Comment by seathasky** [comment]
That's still buggy imo. And i've been leveling as a rogue from level 1 and have not had any rotation issues, it actually been updating as i get new spells. I'm gonna bug ticket it regardless.

**Comment by Lipstopica** [comment]
I wouldn't say it's buggy. It's the APL. Maybe a suggest to change/add in a function to allow it without vile and azerite enabled on low levels.

**Comment by Hekili** [comment]
Yeah, low levels and short trash fights are not the best situations for testing. Snapshots will help clarify what's happening exactly, but it's most likely a matter of pooling shards. You wouldn't waste UA on something dying in a GCD and you wouldn't dump Raptures prematurely either. But there's room to enable such behavior on enemies that are short-lived (but it would not sim as optimal).

**Comment by seathasky** [comment]
I'm not sure what snapshots are, i'm creating a ticket now, this is my first time posting for this addon, any help is appreciated.

**Comment by Hekili** [comment]
And anything sub-50 is explicitly not supported because abilities change significantly as you level in most cases.

**Comment by seathasky** [comment]
Or should i not bother since its not a level 50 toon? Let me know.

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

**Comment by Lipstopica** [comment]
When you made the ticket, it should've gave you instructions in the actual box on how to send the details needed.

**Comment by seathasky** [comment]
i see it now thanks!

**Comment by seathasky** [comment]
updated https://github.com/Hekili/hekili/issues/480
