### ISSUE TITLE
Time To Die calculations are too conservative, leading to dot/bleed reapplications when targets are dying.

### ISSUE THREAD

**Issue by Hekili** [Hekili/hekili#48]

**Comment by behub-au** [comment]
If it helps at all, HeroLib is very accurate.
https://github.com/herotc/hero-lib/blob/master/HeroLib/Class/Unit/TimeToDie.lua

When i put the TTD functions from both addons side by side in a weakaura then you can see how far Hekili is off.

Was testing in raid last and Hekili was giving me at times 8+ seconds on the death of a mob that was dead within less than 1 second. That's just one example.

**Comment by Hekili** [comment]
The new beta release uses new time-to-die calculations that I'm more satisfied with.  It does take a couple of seconds after the enemy is injured before it has an estimate, but if an enemy dies in 2 seconds, recommendations probably don't matter.

I'll leave this ticket open for feedback.

**Comment by Hekili** [comment]
I'm going to close this unless/until new issues are identified.
