### ISSUE TITLE
Brwmaster Monk has permanent no 1-2 priority a passive talent ability (judging by the icon)

### ISSUE THREAD

**Issue by TooUnskilled** [Hekili/hekili#481]
![WoWScrnShot_101920_001046](https://user-images.githubusercontent.com/49813844/96387063-ce16b900-119f-11eb-8b6b-c399365f08fc.jpg)

It's Special Delivery. For some reason it reads as if it's on the no1 slot in the interface as well, even if that slot has nothing in it.

**Comment by Hekili** [comment]
I have no idea what you mean, but if you submit a complete ticket following the instructions I might be able to investigate.

**Comment by TooUnskilled** [comment]
> I have no idea what you mean, but if you submit a complete ticket following the instructions I might be able to investigate.

Actually never mind, it was a different ability with the same icon, but even though it was missing from my interface, it wasn't glowing in the spellbook. Just chalk it up to Blizz bugs :) 

By the way, I got here this way:
1) Report a bug on Twitch client
2) "Issues" on Hekili's page on curseforge
3) Issues tab on Github

Unless I just can't see it, there isn't a template for reporting bugs shown somewhere in my path, so you might want to change that. Just so you don't get any more unformatted reports :)

Cheers!

**Comment by Hekili** [comment]
Thanks for following up. The ticket form starts prepopulated with instructions, you'd have to delete them for them not to be included. Take care!

**Comment by TooUnskilled** [comment]
> Thanks for following up. The ticket form starts prepopulated with instructions, you'd have to delete them for them not to be included. Take care!

Oh wow, so it is.
I wasn't logged in to GitHub when I got here. I clicked on create new issue, and that took me through the login process. Then after logging in I was thrown into the "new post" page, but my post wasn't prepopulated. Maybe it only happens like that?

Anyway, thanks for the addon since I'm here, I love it <3
