### ISSUE TITLE
Massive Number of LUA errors on latest patch

### ISSUE THREAD

**Issue by avrosati** [Hekili/hekili#484]
**Update: I installed latest version. LUA errors still registered and recorded by BugSack.**
Hekili error issue reporting info:

build: v9.0.1-1.0.13
level: 50 (50)
class: PRIEST
spec: shadow

talents: ancient_madness
    auspicious_spirits
    body_and_soul
    damnation
    mind_bomb
    searing_nightmare
    unfurling_darkness

covenant: none

azerite: azerite_empowered = 3
    azerite_globules = 1
    death_throes = 1
    heed_my_call = 1
    impassive_visage = 1
    resounding_protection = 1
    searing_dialogue = 1
    spiteful_apparitions = 3
    thought_harvester = 1
    unstable_flames = 1
    vampiric_speed = 1

essences: [essence_of_the_focusing_iris] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 3, the_crucible_of_flame = 3

sets/legendaries/artifacts: none

gear: artisan_officers_shirt = 1
    ashjrakamas_shroud_of_resolve = 1
    heart_of_azeroth = 1
    leggings_of_the_drowned_lord = 1
    lurking_schemers_band = 1
    mithril_wristwatch = 1
    moonpriests_sash = 1
    neural_synapse_enhancer = 1
    renowned_guild_tabard = 1
    sirensong_garments = 1
    smartly_plumed_cap = 1
    squallshaper_mantle = 1
    thornwoven_band = 1
    thousandyear_pickled_egg = 1
    vile_manipulators_bracelets = 1
    vile_manipulators_handguards = 1
    vile_manipulators_treads = 1

legendaries: none

itemIDs: 117358, 117359, 155886, 157994, 158035, 158075, 159242, 162548, 165438, 168973, 169223, 173478, 173490, 173507, 175008, 69210, 89195

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Shadow
    petbased = false
    potion = potion_of_rising_death
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = single
    potions = true

-------------------------------------------------------------------------------------------------------------------------
Version 9.0.1-1.0.12 
Running on current retail version of game.
My LUA bug collection addon registers this:

**19897x** Hekili\UI.lua:1192: attempt to compare number with nil
[string "@Hekili\UI.lua"]:1192: in function `RefreshCooldowns'
[string "@Hekili\UI.lua"]:1215: in function <Hekili\UI.lua:1207>

Locals:
self = HekiliDisplayPrimary {
 0 = <userdata>
 Activate = <function> defined @Hekili\UI.lua:1293
 index = 2
 Active = true
 firstForce = 224433.844000
 UpdateKeybindings = <function> defined @Hekili\UI.lua:644
 Deactivate = <function> defined @Hekili\UI.lua:1347
 combatTime = <table> {
 }
 combatUpdates = <table> {
 }
 GetPerimeterButtons = <function> defined @Hekili\UI.lua:1359
 RefreshCooldowns = <function> defined @Hekili\UI.lua:1163
 Initialized = true
 Buttons = <table> {
 }
 Recommendations = <table> {
 }
 refreshTimer = 0.039000
 Header = HekiliDisplayPrimaryHeader {
 }
 lastFlashTime = 0
 auraTimer = 0
 flashTimer = -1
 lastUpdate = 225304.741000
 UpdatePerformance = <function> defined @Hekili\UI.lua:1402
 glowTimer = -1.409000
 numIcons = 4
 Moving = false
 delayTimer = 0.050000
 alphaCheck = 0.073000
 id = "Primary"
 Backdrop = HekiliDisplayPrimary_Backdrop {
 }
 alpha = 1
 RecommendationsStr = "potion:void_eruption:focused_azerite_beam:neural_synapse_enhancer"
 eventsTriggered = <table> {
 }
 recTimer = 0.573000
 superUpdate = true
 criticalUpdate = true
 UpdateAlpha = <function> defined @Hekili\UI.lua:1130
 targetTimer = 0.018000
 rangeTimer = 0.118000
 NewRecommendations = false
}
gStart = 225304.950000
gDuration = 1.040000
gExpires = 225305.990000
now = 225305.281000
conf = <table> {
 glow = <table> {
 }
 displayPoint = "TOP"
 builtIn = true
 order = 1
 delays = <table> {
 }
 flash = <table> {
 }
 anchorPoint = "BOTTOM"
 rel = "CENTER"
 frameLevel = 10
 targets = <table> {
 }
 numIcons = 4
 border = <table> {
 }
 range = <table> {
 }
 enabled = true
 relativeTo = "SCREEN"
 keepAspectRatio = true
 zoom = 30
 captions = <table> {
 }
 elvuiCooldown = false
 frameStrata = "LOW"
 queue = <table> {
 }
 keybindings = <table> {
 }
 x = -408.285492
 name = "Primary"
 primaryHeight = 50
 primaryWidth = 50
 indicators = <table> {
 }
 visibility = <table> {
 }
 y = -160.428345
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
}
(for control) = 1
i = 1
rec = <table> {
 actionName = "potion"
 index = 1
 scriptType = "simc"
 item = 152559
 list = "default"
 listName = "default"
 resources = <table> {
 }
 texture = 2057564
 ActScript = "buff.bloodlust.react | target.time_to_die <= 80 | target.health.pct < 35"
 script = "Shadow:default:2"
 pack = "Shadow"
 actionID = -152559
 wait = 0
 ActElements = <table> {
 }
 display = "Primary"
 action = 2
}
ability = <table> {
 gcd = "off"
 charges = 1
 id = -5
 startsCombat = false
 handler = <function> defined @Hekili\Classes.lua:1984
 funcs = <table> {
 }
 name = "|cff00ccff[Potion]|r"
 toggle = "potions"
 realCast = 0
 key = "potion"
}
cd = Hekili_Primary_B1_Cooldown {
 0 = <userdata>
 _occ_priority = 1
 _occ_show = false
 lastDuration = 0
 _occ_kind = "default"
 _occ_duration = 0
 _occ_start = 0
 _occ_draw_swipe = true
 _occ_settings = <table> {
 }
 lastStart = 0
}
start = 0
duration = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = "attempt to compare number with nil"
Hekili = <table> {
 GetTTD = <function> defined @Hekili\Targets.lua:794
 DeserializeStyle = <function> defined @Hekili\Options.lua:8868
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili\Options.lua:3623
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili\Targets.lua:779
 GetPetBasedTargetSpells = <function> defined @Hekili\Targets.lua:88
 After = <function> defined @Hekili\Utils.lua:268
 NewSpellInfo = true
 Run = <function> defined @Hekili\Hekili.lua:263
 UpdateDisplayVisibility = <function> defined @Hekili\UI.lua:1600
 IsEnabled = <function> defined @A

**Comment by Hekili** [comment]
Please post a complete ticket with all the required information.  (For example, I can't see what version you are using here.)
