### ISSUE TITLE
Additional LUA errors in latest version for pre-patch

### ISSUE THREAD

**Issue by avrosati** [Hekili/hekili#486]
**Describe the Bug/Issue**
My LUA bug collector addon reported performance degrading issues due to a high volume of LUA errors.

**To Reproduce**
Open LUA bug collector addon (i.e., BugSack)

**Expected behavior**
No LUA errors being registered and recorded.

**Screenshots**
N/A

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.1-1.0.13
level: 50 (50)
class: PRIEST
spec: shadow

talents: ancient_madness
    auspicious_spirits
    body_and_soul
    damnation
    mind_bomb
    searing_nightmare
    unfurling_darkness

covenant: none

azerite: azerite_empowered = 3
    azerite_globules = 1
    death_throes = 1
    heed_my_call = 1
    impassive_visage = 1
    resounding_protection = 1
    searing_dialogue = 1
    spiteful_apparitions = 3
    thought_harvester = 1
    unstable_flames = 1
    vampiric_speed = 1

essences: [essence_of_the_focusing_iris] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 3, the_crucible_of_flame = 3

sets/legendaries/artifacts: none

gear: artisan_officers_shirt = 1
    ashjrakamas_shroud_of_resolve = 1
    heart_of_azeroth = 1
    leggings_of_the_drowned_lord = 1
    lurking_schemers_band = 1
    mithril_wristwatch = 1
    moonpriests_sash = 1
    neural_synapse_enhancer = 1
    renowned_guild_tabard = 1
    sirensong_garments = 1
    smartly_plumed_cap = 1
    squallshaper_mantle = 1
    thornwoven_band = 1
    thousandyear_pickled_egg = 1
    vile_manipulators_bracelets = 1
    vile_manipulators_handguards = 1
    vile_manipulators_treads = 1

legendaries: none

itemIDs: 117358, 117359, 155886, 157994, 158035, 158075, 159242, 162548, 165438, 168973, 169223, 173478, 173490, 173507, 175008, 69210, 89195

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Shadow
    petbased = false
    potion = potion_of_rising_death
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = single
    potions = true

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

My LUA Bug collecting addon recorded this:
625x Hekili\Hekili-v9.0.1-1.0.13.lua:325: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "@Hekili\Hekili-v9.0.1-1.0.13.lua"]:325: in function `Debug'
[string "@Hekili\Core.lua"]:1031: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:1263: in function `GetNextPrediction'
[string "@Hekili\Core.lua"]:1540: in function `ProcessHooks'
[string "@Hekili\Options-Options.lua"]:9505: in function `MakeSnapshot'
[string "@Hekili\Core.lua"]:1550: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:825: in function <Hekili\UI.lua:689>

Locals:
(*temporary) = "%8sAction chosen:  %s at %.2f!"
(*temporary) = ""
(*temporary) = nil
(*temporary) = 0
(*temporary) = "string expected, got nil"

**Comment by Hekili** [comment]
Should be resolved in 1.0.14.
