### ISSUE TITLE
Demon Hunter-Unbound Chaos

### ISSUE THREAD

**Issue by mon1800** [Hekili/hekili#487]
you may have been asked this, and apologies if you have answered already, but do you plan on adding Fel Rush to the rotation of hekili with the talent Unbound Chaos? Im reading it is the current go to spec but there is no rotational suggestion to Fel Rush when it is buffed. Thanks for all you do in advance.

**Comment by Hekili** [comment]
Check out your spec options.

**Comment by mon1800** [comment]
it says for momentum? optimal build doesnt run momentum but undound chaos? is that an error in tooltip or am i just being too literal?

**Comment by Hekili** [comment]
Click it.

**Comment by mon1800** [comment]
i did. works great just making sure TY SIR!
