### ISSUE TITLE
Brewmaster Monk only suggesting Blackout Kick

### ISSUE THREAD

**Issue by oforia3** [Hekili/hekili#488]
build: v9.0.1-1.0.13
level: 16 (16)
class: MONK
spec: brewmaster

talents: eye_of_the_tiger

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ascetics_cord = 1
    ascetics_cuffs = 1
    ascetics_handguards = 1
    eternal_will_of_the_martyr = 1
    inherited_cape_of_the_black_baron = 1
    lasting_feralheart_spaulders = 1
    mash_tun_mixer = 1
    preened_ironfeather_breastplate = 1
    preened_wildfeather_leggings = 1
    stained_shadowcraft_cap = 1
    swift_hand_of_justice = 1
    vigorous_stompers = 1

legendaries: none

itemIDs: 122248, 122255, 122261, 122361, 122377, 122382, 122668, 157625, 157692, 157696, 157697, 51963

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Brewmaster
    petbased = false
    potion = superior_battle_potion_of_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    bof_percent = 50
    eh_percent = 65
    purify_stagger_currhp = 12
    purify_stagger_maxhp = 6

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Level 16 is not supported.
