### ISSUE TITLE
[Request] Display Visibility IsMounted() Condition

### ISSUE THREAD

**Issue by totalschaden** [Hekili/hekili#49]
Would be nice to have a Checkbox to have 0 Visibility when Mounted. Had the Check added already but it gets annoying to redo it every Update.

Also would suggest replacing the current system as it dosnt give many options or any combinations. I would replace it with enum Checkboxes (On/Off/Ignore) and have them work together. 

For Example you could have a Checkbox for Target,Combat,etc. and based on whats choosed it could show up only when all conditions are matching. So if you have Target on true, mounted on false, and everything else on ignore it will show up when you have a target and not mounted.

Suggestions on Conditions:
Always (Ignore other Conditions)
Target (Player has a Target)
Combat (Player is in Combat)
TargetInCombat (Players Target is in Combat)
IsMounted (Player is Mounted)
PvP Target (Target is valid PvP Target)

**Comment by Hekili** [comment]
Just want to confirm that I plan to revisit this.

**Comment by Hekili** [comment]
Testing this for 8.3.
