### ISSUE TITLE
Balance Druid Shadolands Beta

### ISSUE THREAD

**Issue by tharpy35** [Hekili/hekili#490]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version. yes

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports. no

**Describe the Bug/Issue**
Balance druids have Moonfire spam on one target fights

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

See screenshot

**Expected behavior**
Correct rotation would be the correct path.

**Screenshots**

![image](https://user-images.githubusercontent.com/72934193/96786896-e57fbd00-13be-11eb-8ca9-26811cfdc391.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.1-1.0.15
level: 60 (60)
class: DRUID
spec: balance

talents: heart_of_the_wild
    natures_balance
    restoration_affinity
    shooting_stars
    starlord
    stellar_flare
    wild_charge

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: beaten_copper_loop = 1
    bijou_of_the_golden_city = 1
    honorbound_outriders_belt = 1
    honorbound_outriders_boots = 1
    honorbound_outriders_bracers = 1
    honorbound_outriders_chestcover = 1
    honorbound_outriders_faceguard = 1
    honorbound_outriders_gloves = 1
    honorbound_outriders_greatcloak = 1
    honorbound_outriders_mantle = 1
    honorbound_outriders_pants = 1
    honorbound_war_staff = 1
    sea_sapphire_band = 1
    shaleshell_pendant = 1
    shimmering_rune = 1

legendaries: none

itemIDs: 163361, 163433, 163436, 163440, 174035, 177097, 177101, 177105, 177106, 177119, 177155, 177157, 177164, 177165, 177167

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    starlord_cancel = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
I need the snapshot.

**Comment by tharpy35** [comment]
How do i get that?

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 21, 2020 at 5:50 PM, Hekili<notifications@github.com> wrote:   


I need the snapshot.

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
PUT SNAPSHOT LINK HERE:

**Comment by Hekili** [comment]
Resolved.
