### ISSUE TITLE
Arcane mage rotation is not correct

### ISSUE THREAD

**Issue by shadagada** [Hekili/hekili#491]
Hi Hekili,

the arcane mage rotation is not correct. According to icy viens and wowhead guides during the "conserve" phase we should be saving up our rune of power and touch of the magi, and using them together in order to benefit from a "mini-burn' the addon does not recommend this, rather it uses the CDs on cooldown. It seems that the addon is having trouble with understanding the idea of the burn and conserve phase.

There is also the AM spam rotation, however blizzard did a hotfix today on the azerite pummeling trait, so this rotation/style may no longer be meta.

**Comment by Hekili** [comment]
Yes, the arcane mage priority will be updated due to hotfixes.

No, the addon doesn't have trouble differentiating burn and conserve.

In the future, please follow the ticket instructions to provide the required information when reporting a priority issue.  Thanks!
