### ISSUE TITLE
Feature request: custom "Ignore these NPCs for AoE" list

### ISSUE THREAD

**Issue by razko** [Hekili/hekili#492]
I think it'd be really cool if we could have a list where we add NPCs by ID that makes the "automatic" switching ignore them for its AoE detection purposes. From reading changelogs for recent versions, I understand such a list already exists internally, there's just no interface for it.

It might even make sense to make this an extra option for every spec individually (i.e. put it into the Displays->Spec->Targeting tab, which is where we control things like "nameplate/damaged-enemies detection", "minimum targets", etc, where are aoe-specific things). The reason I think so is that some specs have longer or shorter AoE setups, so there might be adds that I want to AoE on spec1 that I wouldn't want to AoE on spec2, so I'd configure these ignore lists differently.

(On a side note, the main culprit that prompted this all are the little cysts from the tankbuster obelisk boss in m+... I almost never want to AoE them, but since frost mage wants to start aoeing already at 2 targets and I always end up hitting them with splitting ice lances, the addon keeps recommending me to cast Blizzards and that really annoys me. I'd go as far adding this to a global ignore list by default tbh... which also means that perhaps there should be a gui for both the 'global' ignore list and the additional 'per-spec' ignore list?)

**Comment by Hekili** [comment]
This seems pretty reasonable.  I've thought about making the NPCID filter ignore itself if/when you are targeting something with that NPCID (i.e., if you're targeting a cyst, maybe you're into popping cysts).

Making it editable in-game is totally reasonable, but would take more time.  What is the NPCID of the cyst?

**Comment by razko** [comment]
> This seems pretty reasonable. I've thought about making the NPCID filter ignore itself if/when you are targeting something with that NPCID (i.e., if you're targeting a cyst, maybe you're into popping cysts).
> 
> Making it editable in-game is totally reasonable, but would take more time. What is the NPCID of the cyst?

Grabbed it from a random log: https://www.wowhead.com/npc=161408

Btw, for what it's worth, usually if you're targeting cysts, you're just killing them with single target spells anyway. In best case the boss will be dragged near them and walk by momentarily so you might get to press a cleave spell like once or twice, but he's never really explicitly tanked near a cyst for dps purposes, so I don't think there's even really a situation where you'd want to consider this an 'AoE encounter'.

**Comment by Hekili** [comment]
More thoughts on this ticket:  The feature could be a "special targets" identifier that allows special behavior based on what enemy (NPC ID) you're targeting.  For example, if you're targeting a Cyst, I could force `active_enemies` to be 1 so that you only get single-target recommendations.

It'd need to be configurable and it's starting to get into bossmod territory, so it'd require some caution.

**Comment by dubudevs** [comment]
Biggest offender I've noticed for this is the add on High Adjudicator Aleez (HoA 2nd last boss)

**Comment by Hekili** [comment]
This is an old ticket; the feature exists to filter out irrelevant enemies, you simply have to supply the NPC ID and whether there's a relevant aura that influences whether to filter or not.

**Comment by dubudevs** [comment]
For some reason the date was showing as 2 weeks ago for me, weird bug my bad. Good to know.
