### ISSUE TITLE
Using Spellflash functionality - Improving it?

### ISSUE THREAD

**Issue by Peregran** [Hekili/hekili#493]
Please describe your idea or feature and when it would be useful.
I'm using the spellflash functionality and the flashing of the action bar icons is hard to see with my interface.   I can barely see them flash the color they are supposed to.   Is there a function I'm missing or if not a way to give the user some alternatives to be able to see the flashing better.    

Thanks in advance!

- Richard

**Comment by ArcticLatent** [comment]
Same. Still waiting a good spellflash functionality . I hope it is in the works.

**Comment by Hekili** [comment]
There is already an open ticket for this.
