### ISSUE TITLE
Cooldowns - Can we get a "Show Separately" checkbox for Cooldowns?

### ISSUE THREAD

**Issue by codecrete-ross** [Hekili/hekili#494]
Having a separate display for cooldowns would be a game-changer for this addon. 

As much as I love Hekili, it's a little annoying having cooldowns taking up space in my primary display when I know that I'm going to be saving them for an upcoming fight.

I realize we can toggle cooldown display, but having a separate display is a quality of life change that I think would add a significant degree of usefulness to the addon.

Thank you for all your hard work.

**Comment by Hekili** [comment]
So, this exists now, but is experimental and fairly high risk.  Try it.
