### ISSUE TITLE
Add a trinket/utility toggle

### ISSUE THREAD

**Issue by tflo** [Hekili/hekili#495]
Please, please add a general (class-agnostic) toggle for trinkets/utilities, similar to the existing potions toggle.

I have macroed my trinkets to the most appropriate CDs, and I’m not a cutting-edge-level player where a suboptimal trinket usage would matter.

But I have 11 toons, and it is really annoying that I have to find and disable the utility/trinket usage in the action lists for each and every toon every time a new Hekili update comes out. And then again with the next update. This goes so far that I’m seriously considering ditching Hekili for HeroRotation, albeit Hekili obviously is ways better.

I beg you: Add that toggle.

– Tom

**Comment by Hekili** [comment]
You could disable the trinkets themselves rather than their priority entries.

**Comment by tflo** [comment]
This would be the same or even more work, no? (Unless all toons have the same trinkets.) Or am I missing something obvious?

**Comment by Hekili** [comment]
A toggle implies that you want to be able to quickly and easily turn them off/on for good reasons in combat.  That doesn't sound like your use-case, here.

I don't think it's exceptionally burdensome to go into the trinket's options and hit disable when you acquire a new trinket that you want to keep out of your priority.  (Far better than adjusting the priority and then having your priority reset when I update.)

If there's something I'm missing that would be more persuasive, let me know.  Adding more and more toggles means asking folks to bind more and more keys, and I think it's a really small # of users that would want to disable trinkets permanently and a smaller number that would want to toggle them on/off separately from the Cooldowns toggle.

**Comment by tflo** [comment]
No, the idea of a toggle was to circumvent the repeated “patching” of the priorities because of resets (updates). A more long-term thingy, not so much for quickly switching on/off. And keybinds are optional either way.

But this…

> […] to go into the trinket's options and hit disable when you acquire a new trinket that you want to keep out of your priority. (Far better than adjusting the priority and then having your priority reset when I update.)

…seems to imply that the Trinket options are *not* reset with updates. _If it is like this, then it is something I didn’t know._ In that case it is indeed better than patching the abilities each time. Now [your first answer above](https://github.com/Hekili/hekili/issues/495#issuecomment-715528087) also makes more sense to me!

OK. I will test going this route in the future.

I still think a more global toggle (like in HeroRotation, or like your Potion toggle) would be very handy, but I also understand your reluctance to add more stuff.

Many thanks!

– Tom

**Comment by Hekili** [comment]
Thanks for understanding.  It's still up for consideration if there's more thought behind it.  It just creates more complexity.

And yes, the rule of default priorities is that I can update them at any time I want.  Your trinket options are not reset with priority updates.  :)

**Comment by tflo** [comment]
> Your trinket options are not reset with priority updates.

Thanks for the confirmation. Great!
