### ISSUE TITLE
[Request] WW Monk - SEF charged ability option

### ISSUE THREAD

**Issue by RyanMcCullough1997** [Hekili/hekili#496]
WW Monk has 2 charges on their DPS cooldown, Storm, Earth, and Fire. Would there be a way to have Hekili group the first charge with your normal rotation and leave the second charge up unless you have cooldowns enabled? Ideally the first charge would be recommended just prior to using Fists of Fury or as an opener.
This way you could still have one charge saved for DPS windows like bloodlust.

You mentioned on discord that you've had similar options before for charged abilities, so hopefully this wouldn't be too much trouble to implement.

**Comment by Hekili** [comment]
Still considering this, just wanted to confirm that I've seen this.

**Comment by Hekili** [comment]
This is now in testing and will show up in the next build.
