### ISSUE TITLE
Spell queue disappearing depending on how much holy power i have

### ISSUE THREAD

**Issue by Monkzuk** [Hekili/hekili#497]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
build: v9.0.1-1.0.17-beta1
level: 50 (50)
class: PALADIN
spec: retribution

talents: blade_of_wrath
    final_reckoning
    fist_of_justice
    healing_hands
    seraphim
    unbreakable_spirit
    zeal

covenant: none

azerite: avengers_might = 2
    azerite_empowered = 3
    elemental_whirl = 1
    empyrean_power = 1
    gutripper = 1
    heart_of_darkness = 1
    impassive_visage = 1
    lights_decree = 2
    longstrider = 1
    on_my_way = 1
    resounding_protection = 1

essences: [vision_of_perfection] = 3, conflict_and_strife = 3, memory_of_lucid_dreams = 3, the_crucible_of_flame = 4

sets/legendaries/artifacts: none

gear: argent_crusaders_tabard = 1
    ashjrakamas_shroud_of_resolve = 1
    breastplate_of_twilight_decimation = 1
    dark_crystalline_girdle = 1
    dragonbone_vambraces = 1
    embroidered_shirt = 1
    gauntlets_of_absolute_authority = 1
    greathelm_of_phantasmic_reality = 1
    heart_of_azeroth = 1
    ironhulls_reinforced_legplates = 1
    logic_loop_of_recursion = 1
    overclocking_bit_band = 1
    pauldrons_of_infinite_darkness = 1
    skshuul_vaz = 1
    stormsurgers_sabatons = 1
    vial_of_animated_blood = 1
    vitacharged_titanshard = 1

legendaries: none

itemIDs: 158075, 159419, 159420, 159625, 168980, 169158, 169159, 169223, 172200, 174164, 174166, 174167, 174170, 174171, 174500, 46874, 53852

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 10
    nameplates = true
    package = Retribution
    petbased = false
    potion = potion_of_focused_resolve
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false
![0hp](https://user-images.githubusercontent.com/73367705/97058502-ec0c6100-1585-11eb-9d44-78f4b1a95c80.jpg)
![3hp](https://user-images.githubusercontent.com/73367705/97058503-eca4f780-1585-11eb-86b3-03f387fb066c.jpg)
![4hp](https://user-images.githubusercontent.com/73367705/97058504-ed3d8e00-1585-11eb-946c-1c663eb52c48.jpg)
![5hp](https://user-images.githubusercontent.com/73367705/97058506-ed3d8e00-1585-11eb-9e63-63bfc10cccf2.png)

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
-
-
-
-
As you can see from the screenshots above, as i generate my holy power my spell queue starts to diminish till no spell is shown at all. This issue doesnt seem to happen during aoe encounters were there's more than 1 target. After some further testing i noticed that when i use Final Reckong all my spell queue shown correctly regardless of holy power and the issue occured again once Final Reckoning came of CD. If i didnt have Final Reckoning selected as a talent i again didnt have to issue. The last thing i tried was to have FR talented but disable it in the 'Abilites' section again seemed to resolve the issue, but now i wont see it in the queue.

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
PUT SNAPSHOT LINK HERE:

**Comment by Hekili** [comment]
I'll close this in 24 hours if there's no snapshot from the addon to review.  Thanks!

**Comment by Rickard811** [comment]
I had the same problem but i think its is locked to Seraphim.

**Comment by Rickard811** [comment]
![image](https://user-images.githubusercontent.com/73783482/97804761-32cb1c80-1c52-11eb-8bfe-98db1294a98e.png)
![image](https://user-images.githubusercontent.com/73783482/97804766-3a8ac100-1c52-11eb-86f4-58a1369e438c.png)
![image](https://user-images.githubusercontent.com/73783482/97804770-41b1cf00-1c52-11eb-8e06-11b493464a9c.png)

**Comment by Rickard811** [comment]
https://pastebin.com/JqaGuFji

**Comment by Hekili** [comment]
This will be fixed in next build.
