### ISSUE TITLE
Prompting to constantly replace Windfury Totem when 2 enhancement Shaman are in the same group

### ISSUE THREAD

**Issue by Sratarak** [Hekili/hekili#499]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
When 2 enhancement Shaman are in the same group, hekili will constantly put Windfury Totem as the next recommendation.  I believe this is due to the buff you gain "Windfury Totem" being attached to the first person to place it, if it's the other person

**To Reproduce**
Reproducible with 2 enhancement Shaman in the group.  Have the other enhancement Shaman place Windfury Totem down first so that the cast and buff is theirs.  Hekili will prompt for Windfury, you'll put it down, and then as the buff is the other enhancement's Windfury Totem the addon prompts again for it.

**Expected behavior**
I'd expect the addon to recognise the Windfury Totem buff regardless of the caster.

**Screenshots**
![WF](https://user-images.githubusercontent.com/73387882/97080150-4393e680-15f1-11eb-8900-a45c8474e747.PNG)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/kibnfndz

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/kB43cd3H

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
This will be fixed in the next build.
