### ISSUE TITLE
Still performance issues with CDs / No CDs option

### ISSUE THREAD

**Issue by amarques** [Hekili/hekili#5]
Hello guys,
U have a amazing addon. I have a issue to report.

I play as Enhancement shaman now as Monk and i am experience some performance issues:
- The error appear when i Switch between CDs or No CDs mode playing as monk. Playing as Shaman, the performance issue appear but is not heavy, is perfectly fine.

So, could u check monk ww addon performance issue switching between CDs and Not CDs mode?

Ty so much

**Comment by Hekili** [comment]
The CD toggle does very, very little.  I'm not aware of any performance issue (or what you mean by performance issue, to be honest).

Framerate issue?
Slow update?
Wrong recommendation?

I don't know what to look at here.

**Comment by amarques** [comment]
Hello @hekili,

So sorry about my English :( I’m Brazilian.

I’ll try make a video, but right now I’m explain myself again on this chat, basically:

Main issue: Low Framerate:
When u toggle to “No CDs” mode during the battle, the game experiencing a really decrease of FPS. I have a good PC (overpower to WoW game). The sensation is similar when u watching a movie with 40 FPS and when u switch to “No CDs”, the FPS go to 7 or 12. Sometimes is really heavy. But this not happen 100% of times.

Sometimes, I can see the FPS decrease but is not so heavy. A little bit uncomfortable but acceptable.

When I disable Hekili addon, this framerate decreases don’t reproduce, so... because that reason I believe this is a addon issue.

I play before with enhance shaman using the addon, I experienced this problem just a few times, and never was a big issue to me. But, with my Monk DPS, is really hard to play sometimes, this happen with 20 man encounters (like mythic raid) or 5 encounters (like mythic+ encounters)

Ty so much and sorry to bother u.
By the way, u have some donation entry on the Hekili addon page? Could u show me if u have please?

Kind regards

**Comment by Hekili** [comment]
The CD toggle does the following:

1.  Enables (or disables) the 2 or 3 abilities that are treated as cooldowns.
2.  Forces the addon to update early (once).

If you can reply back with info from the Issue Reporting tab of the addon as well as a snapshot when you see a framerate drop (so hit your CD toggle and then hit the snapshot key that you bind on the Toggles menu), that'll give me some information to see what's going on.

I am always looking to make the addon more efficient, and there's certainly room for improvement.  I'll check it out but I'll need more information.
