### ISSUE TITLE
Suggestion - Moooe wook

### ISSUE THREAD

**Issue by petesmisc** [Hekili/hekili#50]
To have a "lock/unlock" button (similar to what the addon Derails has) to be able to quickly reposition the "bar of icons"  on players screen WITHOUT having to go into the main setting->Display and fiddling with the x and y coordinates.

Thank you for all your hard work (I will donate to the effort)

**Comment by SpatenLa** [comment]
open the options
move the bar with your mouse
that already exists

**Comment by petesmisc** [comment]
If you mean that I can move the bar when the "Options" is open (right click), that's NOT acceptable nor what I'm suggesting (maybe I misunderstood what you are saying).

I'm suggesting having a lock/unlock for the displayed icon bar (for single and AOE) that if "unlocked" I can grab the icon bar and drag it quickly, even during a fight.

Having this big screen "Options" open just to move the bars is totally the wrong way to go about it. First of all (1), it blocks the view of where you want to move it and second,
I would never open "Options" in  the middle of a fight (see reason 1)

So I still stand by mu suggestion, I believe that others have asked for a lock/unlock button, I think that their thinking is along the same lines as mine.
Still a great addon, keep up the good work, I did make a donation for what you have given me so far :)

**Comment by petesmisc** [comment]
Perhaps it would be less upheaval in code to just add a "move bars" button under the "left-click" dropdown menu, that is not intrusive and once turned on, it could act the same as if you did the "right-click" to bring up the Options menu, as far as being able to move the icon bar/s

**Comment by Hekili** [comment]
I'm going to leave it as-is.  I strongly suggest setting X/Y values for placement rather than clicking and dragging anyway.
