### ISSUE TITLE
BM Hunter

### ISSUE THREAD

**Issue by NavarJo** [Hekili/hekili#501]
build: v9.0.1-1.0.16
level: 50 (50)
class: HUNTER
spec: beast_mastery

talents: animal_companion
    killer_cobra
    one_with_the_pack
    posthaste
    stomp
    thrill_of_the_hunt
    trailblazer

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: none

legendaries: none

itemIDs: none

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Beast Mastery
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    aspect_vop_overlap = false
    barbed_shot_grace_period = 0.5

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
?

**Comment by Hekili** [comment]
Sorry, you haven't presented an issue so I'm closing this ticket.
