### ISSUE TITLE
Paladin: Judgment Holy Power generation doesn't account for Sanctified Wrath talent

### ISSUE THREAD

**Issue by nvillahermosa** [Hekili/hekili#503]
**Describe the Bug/Issue**
Version v9.0.1-1.0.16
PaladinProtection.lua, line 913: `gain( buff.holy_avenger.up and 3 or 1, "holy_power" )` 

The calculation above doesn't account for the Sanctified Wrath talent. For Prot, if taken, during Avenging Wrath Judgment generates +1 power (so 4 during Holy Avenger, 2 otherwise). This leads to the addon recommending actions that overcap HP.
See https://www.wowhead.com/spell=171648/sanctified-wrath 

**To Reproduce**
1. Take Sanctified Wrath talent
2. Hit a target dummy until you're at 4 Power with no Avenger's Shield charges.
3. Activate Avenging Wrath.
Judgment is the next priority despite either Hand of Glory or Shield of the Righteous being preferable to dump Power.

Maybe something like:
```
if talent.sanctified_wrath.enabled and buff.avenging_wrath.up then
    gain( buff.holy_avenger.up and 4 or 2, "holy_power" )
else
    gain( buff.holy_avenger.up and 3 or 1, "holy_power" )
end
```

I'm an amateur but would be happy to do a pass on the Prot paladin and work on a Holy Paladin setup for the practice if you're interested in any assistance.

**Comment by Hekili** [comment]
Fixed in next build.  You're welcome to make adjustments to the module or the priority and submit your changes as well.
