### ISSUE TITLE
Frost Mage -  Ice Lance

### ISSUE THREAD

**Issue by Lipstopica** [Hekili/hekili#504]
Pretty sure this can't be helped because of flight times etc etc but I'll give it a shot and see if you can see anything.
I did take a snapshot but it didn't end in log with ice lance even though it was paused on Ice Lance so not sure if I missed it... again. Mostly all during Lust but can happen without Lust.

https://pastebin.com/UHQaNpf0

Basically it's suggesting Ice Lance more than it should, obviously guessing because of the flight time of ice lance as it doesn't take a stack off of Winter's Chill until Ice Lance actually hits the target. So range of mob will count and I guess it can't really calculate it all so good. But was wondering if there is another way around it all.

**Comment by Hekili** [comment]
In your snapshot, the first recommendation is Ice Lance so I'm not sure about that part of your comment.

Your snapshot has no Ice Lance in-flight, and so it seems like Ice Lance should be a fine recommendation to consume that last stack.

Did you have an Ice Lance in the air when you snapshotted?

**Comment by Lipstopica** [comment]
Yeah I had already pressed the Ice Lance, so it was travelling to the target as it suggested a third which I snapshotted

**Comment by Lipstopica** [comment]
https://pastebin.com/kbD68fmX

Not related to that ice lance but I also notice sometimes on ice lance and frostbolt its got the "delay" overlay on it so its darkened. Not sure why that happens.

**Comment by Hekili** [comment]
One issue per ticket.  But any delay means that the criteria to cast the spell aren't met until the delay is up.

**Comment by Lipstopica** [comment]
Got another snap I believe of the issue of ice lance

https://pastebin.com/T4u3f0DR

![ssss](https://user-images.githubusercontent.com/48372691/97233352-bc07cc80-17d6-11eb-878f-5b4375488f29.png)

**Comment by Hekili** [comment]
I just double-checked; if Ice Lance was in-flight, the addon had not detected it.  `remaining_winters_chill` is reduced by 1 if there's an Ice Lance in-flight.

**Comment by Lipstopica** [comment]
![sssssss](https://user-images.githubusercontent.com/48372691/97233556-0e48ed80-17d7-11eb-937c-fcc1fc0ace4f.png)
Thats the overlay for the last message I sent here

**Comment by Hekili** [comment]
Yeah, that information is always in the snapshot.  I'll see if Ice Lance impacts aren't being queued up, but that would seem pretty odd.

**Comment by Lipstopica** [comment]
shows remaining 1 but there is no stack of winters chill on the target as u see in the pic

**Comment by Hekili** [comment]
Yeah, those queued impacts don't seem to be successfully removing Winter's Chill stacks.  I'm investigating.  Thanks.

**Comment by Lipstopica** [comment]
Good luck ^^

**Comment by Hekili** [comment]
It actually looks like a pretty simple error.  Will roll any fixes into the next build.

**Comment by Hekili** [comment]
Incoming fix in next beta build.

**Comment by Lipstopica** [comment]
The issue still happens

https://pastebin.com/SYLfrsW3
https://pastebin.com/uPgQDvxj

**Comment by Hekili** [comment]
Neither of those are showing an Ice Lance in-flight, which means the Ice Lance impact is estimated to have already happened and expired when it hasn't actually hit yet.  I can account for that, to some extent, but travel time is always an estimation.

Do you notice any differences based on how close you are to your target?

**Comment by Lipstopica** [comment]
only a slight suggestion of ice lance when closer to the target. Not as long as longer distance

**Comment by Hekili** [comment]
Sorry, can you explain that differently?

**Comment by Lipstopica** [comment]
Yeah, it still appears but not like when it's at a further distance. It doesn't appear on the icon for as long. Just at the very start. It's like a fast flicker

**Comment by Hekili** [comment]
Alright, as of -beta4, those Ice Lance impact events should survive a little longer than before, so it should be much less often that you'll see Ice Lance pop-in.
