### ISSUE TITLE
Hekili broken on certain characters and works on others

### ISSUE THREAD

**Issue by MSgtShadow** [Hekili/hekili#505]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

I have tried various versions of the addon between the 10/13 release and the 10/25 release. Issue exists with the latest release version and beta1 and beta2 versions.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

Did not see similar issue.

**Describe the Bug/Issue**

When I login to the game on my Subtlety Rogue the addon doesn't load the onscreen bar and then about 10 seconds after login I get an error stating: Your AddOns are experiencing a large amount of errors and could be slowing down the game. You can turn on display of Lua errors in the Interface Options.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

Just logging in on my rogue or druid causes this. Can login to my DK, Priest, Lock just fine and Hekili works.

**Expected behavior**

Mod Wont work.

**Screenshots**
![WoWScrnShot_102620_181440](https://user-images.githubusercontent.com/73502730/97234709-c8c8f800-17b7-11eb-9aa0-4ab31042c7b5.jpg)
![WoWScrnShot_102620_181747](https://user-images.githubusercontent.com/73502730/97234722-ce264280-17b7-11eb-994a-fdf22e82b5fa.jpg)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.1-1.0.17-beta2
level: 50 (50)
class: ROGUE
spec: subtlety

talents: enveloping_shadows
    marked_for_death
    master_of_shadows
    night_terrors
    soothing_darkness
    subterfuge
    weaponmaster

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: deeptide_scroll = 1
    enraged_diemetradon_fin = 1
    fathomstalker_cloak = 1
    fathomstalker_leggings = 1
    fathomstalker_waistband = 1
    heart_of_azeroth = 1
    idol_of_voljamba = 1
    jambani_walkers = 1
    murky_cerulean_signet = 1
    ritual_flayers_gloves = 1
    ritual_flayers_wristguards = 1
    spirit_twisters_band = 1
    stained_shadowcraft_cap = 1
    stained_shadowcraft_spaulders = 1
    vest_of_the_champion = 1
    wardruids_cutter = 1

legendaries: none

itemIDs: 122248, 122358, 155319, 158075, 158318, 158971, 159098, 159147, 159763, 159764, 159906, 161139, 167765, 169487, 169809, 170201

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Subtlety
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    mfd_waste = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

Message: Interface\AddOns\Hekili\Classes\RogueSubtlety.lua:434: attempt to perform arithmetic on local 'oh_speed' (a nil value)
Time: Mon Oct 26 18:17:57 2020
Count: 1
Stack: Interface\AddOns\Hekili\Classes\RogueSubtlety.lua:434: attempt to perform arithmetic on local 'oh_speed' (a nil value)
[string "@Interface\AddOns\Hekili\Classes\RogueSubtlety.lua"]:434: in function <Interface\AddOns\Hekili\Classes\RogueSubtlety.lua:414>
[string "@Interface\AddOns\Hekili\Classes\RogueSubtlety.lua"]:26: in function `interval'
[string "@Interface\AddOns\Hekili\State.lua"]:1160: in function <Interface\AddOns\Hekili\State.lua:1117>
[string "@Interface\AddOns\Hekili\State.lua"]:5476: in function `reset'
[string "@Interface\AddOns\Hekili\Scripts.lua"]:1370: in function `LoadScripts'
[string "@Interface\AddOns\Hekili\Scripts.lua"]:1474: in function `LoadScripts'
[string "@Interface\AddOns\Hekili\Classes.lua"]:5377: in function `SpecializationChanged'
[string "@Interface\AddOns\Hekili\Events.lua"]:286: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:55: in function <Interface\AddOns\Hekili\Events.lua:49>

Locals: t = <table> {
}
k = 5
n = 5
mh_speed = 1.610000
mh_next = 85996.773000
oh_speed = nil
oh_next = 85995.968000
(*temporary) = <table> {
 1 = 85998.383000
 2 = 85999.993000
 3 = 86001.603000
 4 = 86003.213001
}
(*temporary) = 86003.213001
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'oh_speed' (a nil value)"
swings_since_sht = 0
sht = <table> {
 1 = 85998.383000
 2 = 85999.993000
 3 = 86001.603000
 4 = 86003.213001
}
last_shadow_techniques = 0

**Comment by Hekili** [comment]
Does it go away if you equip an offhand weapon?

**Comment by Hekili** [comment]
Will baby-proof this function in the next build.
