### ISSUE TITLE
script ran too long Error

### ISSUE THREAD

**Issue by KestrelWild** [Hekili/hekili#506]
I have been getting some huge client freezes in the middle of combat lately (like 30 seconds long and come back dead kind of thing). Turned on bug grabber/sack and it caught this error when I experienced a freeze. Also adding the copy paste from Hekili Issue Reporting, but I have had this happen on multiple toons, not just the mage. Not sure what the lines about Adibags are about. Seems odd - is it something to do with that addon maybe?

3x Hekili\Core.lua:1459: script ran too long
[string "@Hekili\Core.lua"]:1459: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:825: in function <Hekili\UI.lua:689>

Locals:
self = <table> {
 GetMacroCastTarget = <function> defined @Hekili\Events.lua:1744
 GetTTD = <function> defined @Hekili\Targets.lua:839
 DeserializeStyle = <function> defined @Hekili\Options.lua:8871
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Hekili\Options.lua:3623
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Hekili\Targets.lua:824
 EmbedDisciplinaryCommand = <function> defined @Hekili\Classes\MageArcane.lua:383
 GetPetBasedTargetSpells = <function> defined @Hekili\Targets.lua:88
 After = <function> defined @Hekili\Utils.lua:268
 NewSpellInfo = true
 Run = <function> defined @Hekili\Hekili.lua:263
 UpdateDisplayVisibility = <function> defined @Hekili\UI.lua:1600
 IsEnabled = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Hekili\State.lua:5826
 GetPetBasedTargetSpell = <function> defined @Hekili\Targets.lua:100
 ToggleHold = <function> defined @Hekili\State.lua:5851
 SpecializationChanged = <function> defined @Hekili\Classes.lua:5113
 UpdateUseItems = <function> defined @Hekili\Events.lua:596
 SetSpecOption = <function> defined @Hekili\Options.lua:3535
 GetDefaults = <function> defined @Hekili\Options.lua:530
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Hekili\Core.lua:1306
 Options = <table> {
 }
 ReInitialize = <function> defined @Hekili\Core.lua:161
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Hekili\Classes.lua:5060
 State = <table> {
 }
 OnEnable = <function> defined @Hekili\Core.lua:184
 RestoreDefault = <function> defined @Hekili\Classes.lua:777
 CmdLine = <function> defined @Hekili\Options.lua:8609
 IsDisplayActive = <function> defined @Hekili\UI.lua:1697
 SetupPetBasedTargetDetection = <function> defined @Hekili\Targets.lua:114
 ShowDiagnosticTooltip = <function> defined @Hekili\UI.lua:2285
 Notify = <function> defined @Hekili\Options.lua:9521
 OnInitialize = <function> defined @Hekili\Core.lua:61
 NewModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Hekili\Utils.lua:41
 DumpPetBasedTargetInfo = <function> defined @Hekili\Targets.lua:140
 SetPackShareOption = <function> defined @Hekili\Options.lua:3519
 CreateButton = <function> defined @Hekili\UI.lua:1735
 ReleaseHolds = <function> defined @Hekili\State.lua:5883
 Deserialize = <function> defined @BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 SaveDebugSnapshot = <function> defined @Hekili\Hekili.lua:332
 SetSpecPref = <function> defined @Hekili\Options.lua:3576
 GetName = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetOptions = <function> defined @Hekili\Options.lua:7840
 GetSpec = <function> defined @Hekili\Classes.lua:5383
 SerializeDisplay = <function> defined @Hekili\Options.lua:8768
 name = "Hekili"
 ExpireTTDs = <function> defined @Hekili\Targets.lua:1029
 GetEncounterList = <function> defined @Hekili\Options.lua:72
 NewSpecialization = <function> defined @Hekili\Classes.lua:819
 Disable = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetUnitByName = <function> defined @Hekili\Targets.lua:51

------------------------------------------------------------
Issue Reporting copy paste from Hekili

build: v9.0.1-1.0.17-beta2
level: 50 (50)
class: MAGE
spec: frost

talents: chain_reaction
    ice_floes
    incanters_flow
    lonely_winter
    ring_of_frost
    splitting_ice
    thermal_void

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ancient_bloodmoon_cloak = 1
    heart_of_azeroth = 1
    highborne_compendium_of_storms = 1
    honorbound_artificers_amice = 1
    owlseye_loop = 1
    royal_quartz_loop = 1
    ruffled_poet_blouse = 1
    smartly_plumed_cap = 1
    swift_hand_of_justice = 1
    uncanny_combatants_intuitive_staff = 1
    uncanny_combatants_satin_belt = 1
    uncanny_combatants_satin_boots = 1
    uncanny_combatants_satin_bracers = 1
    uncanny_combatants_satin_mittens = 1
    uncanny_combatants_satin_pants = 1

legendaries: none

itemIDs: 122262, 122361, 153683, 153685, 155886, 158075, 158301, 169328, 170318, 170326, 170332, 170337, 170338, 170341, 170529

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Frost Mage
    petbased = false
    potion = potion_of_focused_resolve
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = dual
    potions = false

**Comment by Hekili** [comment]
Thanks, you're not the first person to report this, but narrowing down the source has been challenging.

Can you think more about when it happens?  Are you button mashing to cast something while another cast or channel is finishing?

The next build will force the addon to abort its recommendations if CPU utilization is high.

**Comment by KestrelWild** [comment]
I really can't think of anything specific, though I do tend to button mash :p Would it help to keep running it and getting new error messages? Or will it always be the same message. Anything else I can do to help figure it out?

**Comment by Hekili** [comment]
No, it's just a matter of looking for circumstances where it tends to happen more than others.  I'll keep investigating, and the next build should have controls to keep certain loops from running endlessly.

**Comment by KestrelWild** [comment]
Oh. One possible thing is that I *think* it either started happening or is happening more often after I switched from Automatic to Fixed Dual Display. I just can't remember for sure if it happened before I switched so I'm not sure how useful that observation is. Going to switch back to automatic and see if it keeps happening.

**Comment by KestrelWild** [comment]
Nope still happens. Nevermind!

**Comment by Hekili** [comment]
1.0.17-beta3 is being built right now.  Let me know if it performs any better.

**Comment by KestrelWild** [comment]
been running it since you posted and no freezes/errors/crashes so far!

**Comment by KestrelWild** [comment]
I just got this error, but no freeze:

1x Hekili\Events.lua:2223: attempt to perform arithmetic on local 'maxR' (a nil value)
[string "@Hekili\Events.lua"]:2223: in function <Hekili\Events.lua:2074>
[string "@Hekili\Events.lua"]:2352: in function `handler'
[string "@Hekili\Events.lua"]:55: in function <Hekili\Events.lua:49>

Locals:
event = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1603763226.682000
subtype = "SPELL_CAST_SUCCESS"
_ = false
sourceGUID = "Player-3678-09F1B1B6"
sourceName = "Kestrël"
_ = 1297
_ = 0
destGUID = ""
destName = nil
destFlags = -2147483648
_ = -2147483648
spellID = 84714
spellName = "Frozen Orb"
school = 16
amount = nil
interrupt = nil
a = nil
b = nil
c = nil
d = nil
offhand = nil
multistrike = nil
time = 628947.976000
amSource = true
amTarget = false
hostile = true
minion = false
ability = <table> {
 gcd = "spell"
 spend = 0.010000
 velocity = 20
 handler = <function> defined @Hekili\Classes\MageFrost.lua:921
 copy = 198149
 key = "frozen_orb"
 texture = 629077
 charges = 1
 recharge = 60
 id = 84714
 isProjectile = true
 impact = <function> defined @Hekili\Classes\MageFrost.lua:926
 funcs = <table> {
 }
 spendType = "mana"
 desc = "Launches an orb of swirling ice up to 40 yards forward which deals up to 160 Frost damage to 8 enemies it passes through. Grants 1 charge of Fingers of Frost when it first damages an enemy.

Enemies damaged by the Frozen Orb are slowed by 30% for 3 sec."
 name = "Frozen Orb"
 realCast = 0
 cooldown = 60
 startsCombat = true
}
travel = nil
unit = "target"
_ = nil
maxR = nil
(*temporary) = 20
(*temporary) = nil
(*temporary) = nil
(*temporary) = "target"
(*temporary) = false
(*temporary) = 9
(*temporary) = 10
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'maxR' (a nil value)"
death_events = <table> {
 PARTY_KILL = true
 UNIT_DESTROYED = true
 UNIT_DISSIPATES = true
 SPELL_INSTAKILL = true
 UNIT_DIED = true
}
ns = <table> {
 specTemplate = <table> {
 }
 specializationChanged = <function> defined @Hekili\Classes.lua:5388
 hasRequiredResources = <function> defined @Hekili\State.lua:6157
 serializeActionList = <function> defined @Hekili\Options.lua:8882
 forecastResources = <function> defined @Hekili\State.lua:1134
 frameProfile = <table> {
 }
 UnregisterUnitEvent = <function> defined @Hekili\Events.lua:170
 setClass = <function> defined @Hekili\Classes.lua:4929
 debug = <table> {
 }
 GetTexString = <function> defined @Hekili\Utils.lua:361
 dumpNameplateInfo = <function> defined @Hekili\Targets.lua:398
 queue = <table> {
 }
 addWhitespace = <function> defined @Hekili\Classes.lua:4877
 castsAll = <table> {
 }
 addSetting = <function> defined @Hekili\Classes.lua:4862
 GroupMembers = <function> defined @Hekili\Utils.lua:247
 spendResources = <function> defined @Hekili\State.lua:5784
 safeMax = <function> defined @Hekili\Utils.lua:234
 updateMinion = <function> defined @Hekili\Targets.lua:464
 RegisterUnitEvent = <function> defined @Hekili\Events.lua:131
 AbilitySettings = <function> defined @Hekili\Options.lua:3017
 attr = <table> {
 }
 StartConduits = <function> defined @Hekili\Events.lua:1610
 updateEssences = <function> defined @Hekili\Events.lua:557
 AddTexString = <function> defined @Hekili\Utils.lua:349
 actorHasDebuff = <function> defined @Hekili\Targets.lua:507
 StopEventHandler = <function> defined @Hekili\Events.lua:90
 SpaceOut = <function> defined @Hekili\Utils.lua:50
 getModifier = <function> defined @Hekili\Targets.lua:547
 setRange = <function> defined @Hekili\Classes.lua:4935
 deserializeDisplay = <function> defined @Hekili\Options.lua:8782
 ResourceRegenerates = <function> defined @Hekili\Constants.lua:99
 wipeDebuffs = <function> defined @AddOns

**Comment by Hekili** [comment]
Unrelated to this ticket, but I'll look at it.

**Comment by KestrelWild** [comment]
oops, sorry. i can make a new ticket if you want?

**Comment by Hekili** [comment]
The 'maxR' issue should be fixed in beta4.

Can you post a fresh BugSack + Issue Reporting tab information if you see the "script ran too long" again after updating to beta4?  I think I pinned down the issue, but again, it's *never* happened for me so I can't confirm on my own.

**Comment by KestrelWild** [comment]
will do

**Comment by Hekili** [comment]
This seems to be solved, but please open a new ticket if issues reappear.
