### ISSUE TITLE
Prot warrior Auto Attack 

### ISSUE THREAD

**Issue by parkerstan93** [Hekili/hekili#507]
Prot warrior auto attack has started showing up but there isnt an option dissable it under abilities

**Comment by Hekili** [comment]
1. Please follow ticket instructions when submitting a ticket.

2. Use your pause keybind (ALT-SHIFT-P by default) and put your mouse over the icon to see what it actually is -- there's no "auto-attack" option in the addon.

**Comment by Hekili** [comment]
(It's probably Devastate.)
