### ISSUE TITLE
BM Hunter: Bloodshed Talent Issue

### ISSUE THREAD

**Issue by SARCaelvin** [Hekili/hekili#508]
**Describe the Bug/Issue**
The error apears in bugsack when I click on a unit and have the talent Bloodshed selected for Beast Mastery

**To Reproduce**
- Select Beast Mastery Spec on hunter
- Have the Bloodshed Talent on the last row selected
- Target an ememy or have hekli  turned on
- The addon breaks and will not work

**Expected behavior**
Able to use the addon with talent selected

https://pastebin.com/JfwkLtdv

239x Hekili\Classes\HunterBeastMastery.lua:402: attempt to index global 'fr' (a nil value)
[string "@Hekili\Classes\HunterBeastMastery.lua"]:402: in function `generate'
[string "@Hekili\State.lua"]:4265: in function <Hekili\State.lua:4244>
[string "@Hekili\State.lua"]:892: in function `applyDebuff'
[string "@Hekili\Classes\HunterBeastMastery.lua"]:878: in function `handler'
[string "@Hekili\State.lua"]:5198: in function `RunHandler'
[string "@Hekili\Core.lua"]:1663: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:825: in function <Hekili\UI.lua:689>

Locals:
t = <table> {
 lastApplied = 0
 v1 = 0
 v2 = 0
 caster = "nobody"
 duration = 15
 timeMod = 1
 expires = 0
 key = "bloodshed"
 name = "Bloodshed"
 count = 0
 applied = 0
 v3 = 0
 unit = "target"
 lastCount = 0
}
name = nil
count = nil
duration = nil
expires = nil
caster = nil
_ = nil
(*temporary) = nil
(*temporary) = 40
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'fr' (a nil value)

**Comment by Hekili** [comment]
Thanks, will be fixed in the next build (later tonight).
