### ISSUE TITLE
Shadow Priest Void Torrent

### ISSUE THREAD

**Issue by Shadowjab** [Hekili/hekili#509]
Please describe your idea or feature and when it would be useful.
Hi! Thank you for your good work.

Void Torrent applies Devouring Plague itself, so seems pointless being suggested cast a Devouring plage always before Void Torrent. 

And in the opener, Shadow priest with Void Torrent is like ( Vampiric Touch (pre-cast) > Azerite essence > Use Items > Shadowfiend > Void Torrent > Void Eruption > Void Bolt >  Mind Blast

And in the current version takes to long to suggest you to cast Void Torrent.

![opener](https://user-images.githubusercontent.com/71948300/97408268-249c9980-18fc-11eb-8e22-00d7e80c4d02.png)

*Vampiric Touch is in precast.

Thank you!

**Comment by Hekili** [comment]
I'll look at it, but it'd be more useful to have an actual link to your sim to have talents, etc.

**Comment by Hekili** [comment]
I found that there was a change to Void Torrent's conditions that I overlooked, so I'm reimporting the simc profile to make sure all updates are included.  The result will look more like this (with Misery and Void Torrent):

![image](https://user-images.githubusercontent.com/9438134/97440438-d7b9c280-18fd-11eb-898c-b9fb2cd9bc16.png)

Thanks for the report.

**Comment by Shadowjab** [comment]
Thats looks wonderful.

Thanks mate. Youre awesome.

**Comment by Hekili** [comment]
This is in 1.0.17-beta5 if not -beta4.
