### ISSUE TITLE
Sub Rogue off Hand Speed Error (Performance Slowdown)

### ISSUE THREAD

**Issue by lloydBl** [Hekili/hekili#510]
**Describe the Bug/Issue**
This is not a huge issue as it does not affect gameplay in combat, however as a sub rogue when I unequip my off hand out of combat I get a ton of errors which slow down the game.  The error is pretty self explanatory below but results through no valid off hand speed value to read

**To Reproduce**
- Be a rogue in subtlety spec
- Unequip your off hand weapon
- Equip RP set and RP (optional)

**Expected behavior**
No idle errors which slow down the game performance

**PUT ERROR MESSAGE(S) HERE:**
4222x Hekili\Classes\RogueSubtlety.lua:434: attempt to perform arithmetic on local 'oh_speed' (a nil value)
[string "@Hekili\Classes\RogueSubtlety.lua"]:434: in function <Hekili\Classes\RogueSubtlety.lua:414>
[string "@Hekili\Classes\RogueSubtlety.lua"]:26: in function `interval'
[string "@Hekili\State.lua"]:1149: in function <Hekili\State.lua:1106>
[string "@Hekili\State.lua"]:5456: in function `reset'
[string "@Hekili\Core.lua"]:1302: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:825: in function <Hekili\UI.lua:689>

Locals:
t = <table> {
}
k = 5
n = 5
mh_speed = 3.069000
mh_next = 177936.791500
oh_speed = nil
oh_next = 177935.257000
(*temporary) = <table> {
 1 = 177939.860500
 2 = 177942.929501
 3 = 177945.998501
 4 = 177949.067501
}
(*temporary) = 177949.067501
(*temporary) = 8
(*temporary) = 8
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'oh_speed' (a nil value)"
swings_since_sht = 0
sht = <table> {
 1 = 177939.860500
 2 = 177942.929501
 3 = 177945.998501
 4 = 177949.067501
}
last_shadow_techniques = 0

**Comment by Hekili** [comment]
Yep, this is already fixed and will be available soon.

**Comment by Hekili** [comment]
This should be fixed in 1.0.17-beta5.  Open another ticket if you find this again.
