### ISSUE TITLE
spell Q dissapearing on ret paladin

### ISSUE THREAD

**Issue by maenemanutzzz** [Hekili/hekili#512]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

v9.0.1-1.0.17-beta6

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports. 
There was one paladin who talked about it here, but he didnt provide you with snapshots, so here i am. Also, he didnt touch on the issue being directly connected to hekili not recommending Templars verdict even though i think this might important.

**Describe the Bug/Issue**
My spellQ disapperas, at first i thought it dissapeared every time i used execution sentence, but upon further testing i think it might be connected to too much holy power, the addon doesnt recommend me Templars verdict at all, so when i am in single target combat and my Execution sentence is already on cooldown and i have maximum holy power it seems like it doesnt know what to recommend next.

Also upon further testing, when you reach max holy power and ES is on cd the addon seem to flicker sometimes and completely change the recommendations in seconds while also randomly adding and discarding recommendations which causes the number of recommended spells to randomly decrease and increase.

**To Reproduce**
Fight a training dummy, use execution sentence when you get to 3 holypower and then proceed to stack holy power till you reach max.

**Expected behavior**

**Screenshots**
https://imgur.com/a/ApKjQUo

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
build: v9.0.1-1.0.17-beta6
level: 50 (50)
class: PALADIN
spec: retribution

talents: blade_of_wrath
    cavalier
    execution_sentence
    final_reckoning
    fist_of_justice
    healing_hands
    seraphim

pvptalents: none

covenant: none

azerite: avengers_might = 1
    azerite_empowered = 2
    empyreal_ward = 1
    empyrean_power = 2
    expurgation = 2
    heed_my_call = 1
    on_my_way = 1
    resounding_protection = 2

essences: [the_crucible_of_flame] = 1, none

sets/legendaries/artifacts: none

gear: ashbringer = 1
    band_of_the_petrified_pumpkin = 1
    bleakweald_handguards = 1
    embellished_ritual_sabatons = 1
    heart_of_azeroth = 1
    malignant_leviathans_armguards = 1
    malignant_leviathans_hauberk = 1
    malignant_leviathans_spaulders = 1
    plunderbeards_flask = 1
    pterroleather_cloak = 1
    seal_of_the_regal_loa = 1
    shoalbreach_waistguard = 1
    spiked_counterweight = 1
    stormwind_tabard = 1
    zanjir_scaleguard_faceguard = 1
    zanjir_scaleguard_legguards = 1

legendaries: none

itemIDs: 120978, 136715, 143901, 155861, 158024, 158061, 158075, 158164, 159458, 160127, 167778, 169811, 173460, 173837, 174956, 45574

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Retribution
    petbased = false
    potion = potion_of_focused_resolve
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://www.pastebin.cz/cs/p/dh2TjBs

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
The snapshot needs to be taken when you are experiencing the problem you've described.

**Comment by maenemanutzzz** [comment]
> The snapshot needs to be taken when you are experiencing the problem you've desc

Sorry, i accidentaly uploaded the wrong one, here you go: 
https://www.pastebin.cz/cs/p/nyZaHQx

**Comment by maenemanutzzz** [comment]
Also i just dicovered that when i use Seraphim it recommends Templars verdict, and even after Seraphim is over it keeps recommending Templars verdict until execution sentence comes off cooldown. 

https://imgur.com/HpR51Df

**Comment by Hekili** [comment]
Screenshots aren't that useful, that's why I ask for snapshots. Tell me more about your last post. What is the problem and what do you think you should see instead?

**Comment by maenemanutzzz** [comment]
The problem is that hekili should recommend Templars verdict always, not just when i use Seraphim. 
Here is a snapshot i captured after i used seraphim and execution sentence and it recommended me Templars verdict:
 
https://www.pastebin.cz/cs/p/2BwPERm

Here is a snapshot i posted previously that was captured without using Seraphim but using Execution sentence at which point hekili doesnt recommend Templars verdict and when you reach maximum holy power it breaks and doesnt recommend anything except essences:

https://www.pastebin.cz/cs/p/nyZaHQx

**Comment by Hekili** [comment]
Right, just for tracking purposes, it's most helpful to structure information like:

This snapshot shows X.  It should show Y, because Z.

If there's a lot of editorializing or extra information that's less relevant, it makes it take longer for me to get to the heart of it.  I'll investigate.

**Comment by maenemanutzzz** [comment]
Oh shit im sorry, im fucking retarded, idk what the 2nd snapshot is but its worng. This is the correct one: https://www.pastebin.cz/cs/p/dh2TjBs 
Also, i would love to help you with this but im not experienced in this stuff, i can barely recognize whats going on in those snapshots, let alone analyze the code, although just from control+f search for templars verdict i discovered that the snapshot with seraphim (https://www.pastebin.cz/cs/p/2BwPERm) is showing 12 results while the snapshot without it (https://www.pastebin.cz/cs/p/dh2TjBs) is showing just 2, hope this is atleast a minor help lol. Aain, i apologize for posting the wrong snapshot link.

**Comment by Hekili** [comment]
Thanks for the information.  I did some testing, and the reason is an interaction between Seraphim and Final Reckoning.  FR waits for the Seraphim buff, which you don't have because cooldowns are toggled off and Seraphim is on the cooldowns toggle.

I am:
1.  Removing Seraphim from the Cooldowns toggle, since it's a short CD and should be used as often as possible (like Tiger's Fury for Feral).
2.  Adding Final Reckoning to the Cooldowns toggle, since it's a full minute CD.  It should be used as often as possible, but if you're holding it, you probably mean to do so.

**Comment by maenemanutzzz** [comment]
Just tested the new version (v9.0.1-1.0.17), works perfectly, thank you.

**Comment by Hekili** [comment]
Thanks for the confirmation!
