### ISSUE TITLE
Hekili LUA error when first logging into game with character

### ISSUE THREAD

**Issue by Incompetent-Tech** [Hekili/hekili#513]
**LUA Error:**
Message: Interface\AddOns\Hekili\Classes.lua:623: table index is nil
Time: Sat Oct 31 09:10:56 2020
Count: 1
Stack: Interface\AddOns\Hekili\Classes.lua:623: table index is nil
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Hekili\Classes.lua"]:623: in function `?'
[string "@Interface\AddOns\Hekili\Events.lua"]:282: in function `RunSpellCallbacks'
[string "@Interface\AddOns\Hekili\Events.lua"]:88: in function `StartEventHandler'
[string "@Interface\AddOns\Hekili\Core.lua"]:185: in function <Interface\AddOns\Hekili\Core.lua:184>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Hekili Character Data:**
build: v9.0.1-1.0.17
level: 50 (50)
class: ROGUE
spec: assassination

talents: alacrity
    cheat_death
    elaborate_planning
    iron_wire
    poison_bomb
    subterfuge
    vigor

pvptalents: none

covenant: none

azerite: azerite_empowered = 3
    double_dose = 1
    impassive_visage = 1
    lying_in_wait = 1
    nothing_personal = 1
    overwhelming_power = 3
    resounding_protection = 1
    shadow_of_elune = 1
    shrouded_suffocation = 1
    tidal_surge = 1
    twist_the_knife = 1

essences: [worldvein_resonance] = 4, breath_of_the_dying = 2, memory_of_lucid_dreams = 3, the_crucible_of_flame = 4

sets/legendaries/artifacts: cyclotronic_blast = 1
    pocketsized_computation_device = 1

gear: ashjrakamas_shroud_of_resolve = 1
    chestguard_of_the_insatiable_maw = 1
    cyclotronic_blast = 1
    darkwood_sentinels_breeches = 1
    darkwood_sentinels_cinch = 1
    darkwood_sentinels_cowl = 1
    darkwood_sentinels_footpads = 1
    darkwood_sentinels_grips = 1
    fairweather_shoulderpads = 1
    galecallers_boon = 1
    heart_of_azeroth = 1
    pocketsized_computation_device = 1
    seal_of_dathremar = 1
    sentinels_crescent = 1
    stonemasons_guild_band = 1
    trixies_backup_backbiter = 1
    wound_dressing = 1
    wristwraps_of_the_insatiable_maw = 1

legendaries: none

itemIDs: 158043, 158075, 159614, 165441, 165442, 165443, 165444, 165446, 165624, 165678, 165683, 167555, 167672, 169066, 169223, 173438, 173445, 44693

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Assassination
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    envenom_pool_pct = 50
    mfd_waste = true
    priority_rotation = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Thanks, will sort it out.

**Comment by Hekili** [comment]
I can't replicate this directly, but when 1.0.18-beta1 is out in a few minutes, would you please try it and see if this is resolved for you?  Thanks in advance.

**Comment by Incompetent-Tech** [comment]
Looks to be working. No errors or noticeable issues.  Thanks for the quick fix.
