### ISSUE TITLE
LibSpellRange Error

### ISSUE THREAD

**Issue by mrlenxa** [Hekili/hekili#514]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
LUA Error when targeting any type of mob. Doesn't trigger until you get into combat.

**To Reproduce**
1) target mob
2) engage in combat

**Expected behavior**
No LUA Error

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

https://pastebin.com/ne8R1AcN

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

```
Message: ...\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:40: table index is nil
Time: Sat Oct 31 09:38:34 2020
Count: 3436
Stack: ...\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:40: table index is nil
[string "@Interface\AddOns\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua"]:40: in function <...\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua:38>
[string "@Interface\AddOns\Hekili\Libs\LibSpellRange-1.0\LibSpellRange-1.0.lua"]:163: in function `IsSpellInRange'
[string "@Interface\AddOns\Hekili\UI.lua"]:910: in function <Interface\AddOns\Hekili\UI.lua:690>

Locals: t = <table> {
 Shadow Dance = false
 Slice and Dice = false
 Shadowstrike = false
 Symbols of Death = false
 Backstab = false
 Eviscerate = false
}
i = nil
o = false
(*temporary) = nil
(*temporary) = "table index is nil"
tonumber = <function> defined =[C]:-1
```

**Comment by Hekili** [comment]
?

**Comment by Hekili** [comment]
Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**Comment by mrlenxa** [comment]
Sorry. Just updated the actual problem.

**Comment by mrlenxa** [comment]
> Please provide the following information. Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).
> 
> 1. The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/ne8R1AcN

**Comment by Hekili** [comment]
Can you test 1.0.18-beta1 and let me know if this is resolved for you?  Thanks.

**Comment by mrlenxa** [comment]
Just tested and can confirm that the issue is resolved
