### ISSUE TITLE
Fury Warrior Whirlwind

### ISSUE THREAD

**Issue by Forcefulpuspus** [Hekili/hekili#515]
Not a huge issue by any means but while leveling (Fury Warrior) Hekili wants you to press whirlwind first for AOE but doesn't change after you press it, it never moves forward.  My guess is its anticipating the buff for whirlwind that causes your next attacks to cleave but you don't obtain that buff (Rank 3 Whirlwind) until level 37.

Thanks for your excellent work!

**Comment by Hekili** [comment]
Submit the snapshot where it's happening.  I can tell you if it's that or if it's because you took the talent that causes you to ignore Slam.

**Comment by Forcefulpuspus** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/73762781/97792865-28f1dc80-1bb2-11eb-9723-de11c1190ae9.gif)

**Comment by Forcefulpuspus** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/73762781/97795126-50f03880-1bd0-11eb-9f42-afed03d84842.gif)

**Comment by Hekili** [comment]
Sorry, by snapshot, I mean /hekili > Snapshots. It's a log of the addons decision-making at one moment.

**Comment by Forcefulpuspus** [comment]
https://pastebin.com/0fwvnPH8
