### ISSUE TITLE
Shadow Priest dps uses Mind Control in rotation, and Mind Control is not included in the abilities list (so it can't be disabled).

### ISSUE THREAD

**Issue by lundbergaj** [Hekili/hekili#518]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Hekili uses Mind Control in the shadow priest rotation, and there is no way to disable it's selection of Mind Control in the rotation.

**To Reproduce**
I get this behavior on the shadow priest all the time. Mind Control is selected as part of the standard rotation, but Mind Control is not included in the list of abilities, so it cannot be disabled. 

**Expected behavior**
I would expect that Mind Control should be included in the list of abilities if it is used in the rotation and used by Hekili. 

**Screenshots**
![WoWScrnShot_Mind Control](https://user-images.githubusercontent.com/45601868/97905099-72a40980-1d0f-11eb-951f-d57a9c8265d8.jpg)

**Comment by Hekili** [comment]
Press ALT-SHIFT-P to pause and mouseover that icon.

**Comment by Hekili** [comment]
(It's Mind Blast.)
