### ISSUE TITLE
RET Paladin still have problems with seraphim

### ISSUE THREAD

**Issue by Rickard811** [Hekili/hekili#519]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Ret paladin still don't get suggestion s sometimes with seraphim**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/MJNVDywu

https://pastebin.com/cWg3wmAp

**Comment by Rickard811** [comment]
https://pastebin.com/nj3LzZJZ

**Comment by Hekili** [comment]
Please use Pastebin for snapshots per the instructions (otherwise GitHub eats the snapshot/formatting).

Without Crusade, it looks like the APL is trying to sync FR with Seraphim and sync Seraphim with AW, and AW with Execution Sentence, which can put you in a problematic situation if you used Execution Sentence before enabling cooldowns.  I'll sort it out.

**Comment by Rickard811** [comment]
Added another snapshot, seams something goes wring I have 5 holy power, and it's waiting for several seconds for ES but  I could use a spender and filler before the CD of ES is off. And one more thing if the rotation is to only use ES when seraphim/FR is up why does it give a recommendation to use ES of Seraphim/FR?

**Comment by Hekili** [comment]
Yes, again, it's logic that's trying to sync up Seraphim + Final Reckoning + Execution Sentence.  I have the info that I need.  I'll have to make edits and test solutions.

**Comment by Hekili** [comment]
Try 1.0.21 and submit a new ticket with new snapshots if you run into this again.
