### ISSUE TITLE
Fury warrior rampage on all rotation icons

### ISSUE THREAD

**Issue by Freazerr** [Hekili/hekili#520]
Updated to the last version (v9.0.1-1.0.19) and noticed that when i hit the rage required for rampage insted of it being on 1 of the rotation icons its takes up all of them. After downgrading to the previouse version (v9.0.1-1.0.18) it only showed up on 1 as normal

- Update to v9.0.1-1.0.19
- Play Fury warrior
- Get enough rage for rampage

**Expected behavior**
It would only show up 1 on icon insted of all 4 of them

**Screenshots**
v9.0.1-1.0.19
[https://imgur.com/a/PHZanz2](url)
v9.0.1-1.0.18
https://imgur.com/a/IeCDWoC

**Comment by Hekili** [comment]
I'll look into it, but please re-read the ticket instructions re: snapshots.  Thanks!

**Comment by Hekili** [comment]
This should be resolved in 1.0.20 and/or 1.0.21.
