### ISSUE TITLE
Request:  Don't Try to Hardcast while Moving (i.e., Aimed Shot)

### ISSUE THREAD

**Issue by wow1989** [Hekili/hekili#521]
Please please please

A toggle to stop recommending a casted aimed shot while moving.

**Comment by knagls** [comment]
+++ !

**Comment by Hekili** [comment]
To be fair, that sort of recommendation is technically correct -- you should move as little as possible so you can get back to casting.

Do you have a list of abilities (with a cast time or channeled) that can be used while moving?  (Obviously, instants are fine while moving.)  If I have that information, I can potentially add an option for this.

**Comment by wow1989** [comment]
I believe the ONLY marks ability that can’t be cast while moving is aimed shot (And sniper shot pvp talent, but that currently isn’t recognized by hekili) 

Rapid fire and steady shot can both be cast while moving.

I believe the rotation can just play as is minus casted aimed shots.

**Comment by wow1989** [comment]
Note the talent *lock and load* proccing instant aimed shots being the only current exception

**Comment by wow1989** [comment]
I believe the ONLY marks ability that can’t be cast while moving is aimed shot (And sniper shot pvp talent, but that currently isn’t recognized by hekili) 

Rapid fire and steady shot can both be cast while moving.

I believe the only rotational change would be to leave a base energy amount so you can cast aimed shot once you’re stationary again.

**Comment by knagls** [comment]
hi! any news? :)

**Comment by Hekili** [comment]
Nope.  I don't keep anything secret.  You'll know if/when there are any changes.

**Comment by vicwac** [comment]
Under priorities-marksmanship tab, select aimed shot from the st drop down menu, click modifications and enable the movement option to stationery, so Hekili won't recommend it when you're moving. This can be done for all classes/specs that have skills that can only be cast when stationery.

**Comment by knagls** [comment]
its GREATE! THX!

**Comment by Hekili** [comment]
I've added a checkbox to /hekili > Marksmanship to disable Aimed Shot while moving (if it has a cast time).
