### ISSUE TITLE
Wrong size/position

### ISSUE THREAD

**Issue by Beyonderr** [Hekili/hekili#522]
Updated to the last version (v9.0.1-1.0.21).

Wrong size and position after login in game with a profile since Hekili-v9.0.1-1.0.17.

- Create a profile
- Save size and position
- log out
- log in
- Wrong size and position (until you re-input 1 number in the position/size)

**Expected behavior**
Wrong size and position

**Screenshots**
https://imgur.com/YG8z1r6

**Video**
https://streamable.com/pwdvc5

**ISSUE REPORT LINK HERE:**
https://pastebin.com/Dip6v5Gj

**Comment by Hekili** [comment]
Thanks.

Can you try the following?

In UI.lua, search for "SetIgnoreParentScale" and then preface that line and the SetScale line that follows with two dashes (--), like this:

```Lua
        d:SetSize( scale * ( border + ( conf.primaryWidth or 50 ) ), scale * ( border + ( conf.primaryHeight or 50 ) ) )
        -- d:SetIgnoreParentScale( true )
        -- d:SetScale( UIParent:GetScale() )
        d:ClearAllPoints()
```

Reload UI and see if that fixes the issue for you.

**Comment by Beyonderr** [comment]
Thanks.
Just tested and the issue is resolved.
