### ISSUE TITLE
Hekili options panel doesn't open

### ISSUE THREAD

**Issue by mkaya035** [Hekili/hekili#526]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.:
**I am using the latest version of the addon.**

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.:
**I didnt saw any issue like this.**

**Describe the Bug/Issue**
**When i press right click on the icon options panel dont open, i already try /hekili but it doesn't appear**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
**I want open the options panel.**

**Screenshot**
https://prnt.sc/vdxwnw

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ERROR MESSAGE(S) HERE:**

Shortly: 
Addon is updated latest version. When i open the options panel i got some cubes on my screen like in the screenshot.

**Comment by Hekili** [comment]
Revisit the ticket instructions, to see if there is an error message that needs to be resolved.

**Comment by mkaya035** [comment]
What do you mean with Visit ticket instructions?

**Comment by Hekili** [comment]
The instructions that you deleted when submitting this ticket. They tell you what information I need from you to be able to help you.

**Comment by Hekili** [comment]
Also, if you're playing Classic, the addon does not support Classic.

**Comment by mkaya035** [comment]
Its about retail let me see for the information thank you:)

**Comment by mkaya035** [comment]
its okay like this?

**Comment by Hekili** [comment]
If you submit a ticket with actionable information, I can review. As it stands, there's literally nothing I can do with the information provided. 

Just submit a ticket, following the instructions, and then we can try again. Thanks.

**Comment by Hekili** [comment]
Were you going to submit more information?  Thanks.
