### ISSUE TITLE
v8.1.0-10 - Survival Hunter - runHandler Error

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#53]
![image](https://user-images.githubusercontent.com/870239/51653507-ce444d80-1fe7-11e9-90e5-e9606dc97a6f.png)

No errors when i logged on my balance druid and ret paladin but the errors are coming so fast on survival hunter I could not even copy and paste the text out.

**Comment by behub-au** [comment]
Error has magically stopped.

**Comment by behub-au** [comment]
Zoned into dungeon. Error returned.

**Comment by Hekili** [comment]
Fix inc.

**Comment by Hekili** [comment]
Should be fixed in -11.
