### ISSUE TITLE
Addon Bar not even showing for Affliction

### ISSUE THREAD

**Issue by Dragnclaw** [Hekili/hekili#530]
Have latest version, Version before this one was telling me to cast corruption over and over.

As of when I clicked to submit the bug had not been reported

Addon Bar not even showing for Affliction. It does show if I switch to destruction.

I assume all you would have to do is try to play affliction.

Spell priority bar to show up.

build: v9.0.1-1.0.26
level: 50 (50)
class: WARLOCK
spec: affliction

talents: absolute_corruption
    burning_rush
    dark_soul_misery
    drain_soul
    haunt
    mortal_coil
    vile_taint

pvptalents: none

covenant: none

azerite: azerite_empowered = 3
    bulwark_of_the_masses = 1
    cascading_calamity = 2
    desperate_power = 1
    elemental_whirl = 1
    inevitable_demise = 2
    overwhelming_power = 1
    unstable_flames = 1
    vampiric_speed = 1
    wracking_brilliance = 2

essences: [essence_of_the_focusing_iris] = 4, breath_of_the_dying = 3, the_crucible_of_flame = 3, the_unbound_force = 3

sets/legendaries/artifacts: none

gear: amice_of_the_returned = 1
    ashjrakamas_shroud_of_resolve = 1
    bloodstained_ritual_athame = 1
    boots_of_wrought_shadow = 1
    forbidden_obsidian_claw = 1
    heart_of_azeroth = 1
    ichorspine_loop = 1
    insulating_threaded_gloves = 1
    jade_ophidian_band = 1
    moonstone_of_zinazshari = 1
    ouroborial_sash = 1
    overcharged_pantaloons = 1
    plaguebringers_armwraps = 1
    robes_of_the_reborn_serpent = 1
    uhnish_vwah = 1
    visage_of_nightmarish_machinations = 1

legendaries: none

itemIDs: 158075, 159255, 159257, 159273, 162544, 165471, 165666, 169061, 169071, 169223, 172190, 172201, 173944, 174118, 174128, 174532

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = (none)
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Try to take a snapshot and submit that as well.

**Comment by Hekili** [comment]
And/or BugSack and BugGrabber information per the ticket instructions.

**Comment by Hekili** [comment]
Hellooooo, you _just_ opened this ticket.  Can you respond?

**Comment by Dragnclaw** [comment]
Snapshot:
```
`Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.1-1.0.26
level: 50 (50)
class: WARLOCK
spec: affliction

talents: absolute_corruption
    burning_rush
    dark_soul_misery
    drain_soul
    haunt
    mortal_coil
    vile_taint

pvptalents: none

covenant: none

azerite: azerite_empowered = 3
    bulwark_of_the_masses = 1
    cascading_calamity = 2
    desperate_power = 1
    elemental_whirl = 1
    inevitable_demise = 2
    overwhelming_power = 1
    unstable_flames = 1
    vampiric_speed = 1
    wracking_brilliance = 2

essences: [essence_of_the_focusing_iris] = 4, breath_of_the_dying = 3, the_crucible_of_flame = 3, the_unbound_force = 3

sets/legendaries/artifacts: none

gear: amice_of_the_returned = 1
    ashjrakamas_shroud_of_resolve = 1
    bloodstained_ritual_athame = 1
    boots_of_wrought_shadow = 1
    forbidden_obsidian_claw = 1
    heart_of_azeroth = 1
    ichorspine_loop = 1
    insulating_threaded_gloves = 1
    jade_ophidian_band = 1
    moonstone_of_zinazshari = 1
    ouroborial_sash = 1
    overcharged_pantaloons = 1
    plaguebringers_armwraps = 1
    robes_of_the_reborn_serpent = 1
    uhnish_vwah = 1
    visage_of_nightmarish_machinations = 1

legendaries: none

itemIDs: 158075, 159255, 159257, 159273, 162544, 165471, 165666, 169061, 169071, 169223, 172190, 172201, 173944, 174118, 174128, 174532

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = (none)
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

New Recommendations for [ Primary ] requested at 22:16:13 ( 16975.88 ); using ( (none) ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: mana[ 10000.00 / 10000.00 ], soul_shards[ 3.00 / 5.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ (none) - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        ListActive: N ((none)-precombat)
    
    Completed precombat action list [ (none) - precombat ].
    
    Processing default action list [ (none) - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        ListActive: N ((none)-default)
    
    Completed default action list [ (none) - default ].
    Recommendation is NO ACTION at 0.00 + 60.00.
    Recommendation #1 is NO ACTION at 60.00s (60.00s).
    Time spent generating recommendations:  0.17ms`
```

No error or bug reported

**Comment by Hekili** [comment]
Your priority isn't set in /hekili > Affliction > Core.  If you click the dropdown, is Affliction listed?

**Comment by Dragnclaw** [comment]
No it was not, and that has made it reappear. Thank you.

Only thing is I did not change this setting. I was using the addon, saw there was an update, downloaded it, and /reload.

So i have no idea why that option changed.

**Comment by Hekili** [comment]
Let me know if it vanishes again.  Going to tweak the priority again real quick.
