### ISSUE TITLE
Ret module disappearing during N'Zoth

### ISSUE THREAD

**Issue by Impact009** [Hekili/hekili#531]
This seems to only happen during N'Zoth so far and was not happening before pre-patch. Hekili disappears after exiting Phase 1 and will only reappear upon entering the Mindgate again. It's pretty consistent, but out of about 5 pulls, I did see Hekili once outside of the Mindgate.

**Comment by Hekili** [comment]
Please submit a proper ticket following the ticket instructions, thanks.
