### ISSUE TITLE
Celestial Alignment preferring Starfire

### ISSUE THREAD

**Issue by vladimars** [Hekili/hekili#535]
For single target CA seems to be preferring you to cast Starfire over Wrath. Wrath should be higher single target dps and thus be the preferred spell. Is there a way to change that?

**Comment by Hekili** [comment]
You can edit the priority, but if you'd like to see the defaults changed, you'd need to provide sims that reflect that a change is a DPS increase.  Thanks!

**Comment by vladimars** [comment]
Ok. How do I edit the priority? I looked into the apl and its pretty ... long. After consulting with the balance druid community the general consensus is that wrath should be better than starfire for single target.

**Comment by Hekili** [comment]
/hekili > Priorities > Balance.

For syntax, you can generally refer to SimulationCraft's wiki.  Again, I strongly recommend you prove any changes you'd make in SimulationCraft before even touching it in the addon.

I won't be able to help you customize further, simply as a matter of time management.  Everything you need is there, aside from the expertise of actually writing priorities/APL.

**Comment by Hekili** [comment]
There's a little detail about modifying priorities here, as well:  https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions

Last bit of advice:  I'd encourage you to look into why you're seeing Starfire before deciding that you ought not see it.  It's entirely possible that you and those you've spoken to are right in general.  But it's generally a good idea to know why you see what you see, before going in a different direction.

**Comment by Hekili** [comment]
FYI, I've done a fairly extensive revamp of Balance in the latest beta (1.0.28-beta1) if you want to test and see if you get more of what you're expecting.  If you find issues, please submit a ticket following the instructions that are pre-filled.  Thanks!
