### ISSUE TITLE
Balance druid Shadowlands Rotation

### ISSUE THREAD

**Issue by Jmz1988** [Hekili/hekili#536]
Hi im just wondering how accurate the Balance rotation is at the moment? im feeling that Streaking stars maybe causing some confliction can someone verify :)

**Comment by Hekili** [comment]
Please submit a proper ticket following the ticket instructions.  Thanks.

**Comment by Hekili** [comment]
FYI, I've done a fairly extensive revamp of Balance in the latest beta (1.0.28-beta1) if you want to test and see if you get more of what you're expecting.  If you find issues, please submit a ticket following the instructions that are pre-filled.  Thanks!

**Comment by Jmz1988** [comment]
Thank you for replying, I love the work you have done with that addon. I actually just think the changes to balance have been not very well designed on blizzards behalf, esp lack of UI elements and after testing a lot more I just think that its partly due to Streaking stars with so much going on and trying to track everything else. Im sure Shadowlands release it will be a lot more fluid 😊 but I have noticed the addon is working mostly as intended for balance. Looking forward to shadowlands changes!

Regards james, great work.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
