### ISSUE TITLE
Unholy DK - Hekili bar disappears after pressing just a couple of buttons in combat, in any combat situation. Or randomly it will shrink to 1 or 2 buttons, and not show a queue. 

### ISSUE THREAD

**Issue by monoliith** [Hekili/hekili#537]
Hekili bar disappears after pressing just a couple of buttons in combat, in any combat situation. Or randomly it will shrink to 1 or 2 buttons, and not show a queue. 
![Screenshot_165](https://user-images.githubusercontent.com/65993671/98884084-e30c0280-2454-11eb-886f-cc2cf42f759e.jpg)
![Screenshot_164](https://user-images.githubusercontent.com/65993671/98884087-e3a49900-2454-11eb-983b-f1e75932f712.jpg)

**Comment by Hekili** [comment]
Please resubmit the ticket with the information required.
