### ISSUE TITLE
[Issue] WW Monk Touch of Karma and Fortifying Brew

### ISSUE THREAD

**Issue by vicwac** [Hekili/hekili#538]
Touch of Karma always gets recommended at around 80% hp even after setting the conditions to health.percent <=50. Tried it under default and defensives action lists, no change.

Fortifying Brew does not get recommended at all, suspect that it is broken as I notice the icon looks different from my spell list but there's no way to tell unless I can see the spell ID.

Character Data:

build: v9.0.1-1.0.27
level: 50 (50)
class: MONK
spec: windwalker

talents: chi_wave
    dance_of_chiji
    fist_of_the_white_tiger
    good_karma
    inner_strength
    tigers_lust
    whirling_dragon_punch

pvptalents: alpha_tiger
   pressure_points
   turbo_fists

covenant: none

azerite: azerite_empowered = 3
    blightborne_infusion = 1
    dance_of_chiji = 1
    fury_of_xuen = 1
    glory_of_the_dawn = 1
    heart_of_darkness = 1
    impassive_visage = 1
    open_palm_strikes = 1
    overwhelming_power = 2
    resounding_protection = 1
    strength_of_spirit = 1
    unstable_flames = 1

essences: [conflict_and_strife] = 3, breath_of_the_dying = 3, memory_of_lucid_dreams = 3, the_crucible_of_flame = 3

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    band_of_the_ancient_dredger = 1
    darkheart_robe = 1
    darkwood_sentinels_armguards = 1
    darkwood_sentinels_cinch = 1
    darkwood_sentinels_footpads = 1
    gorak_tuls_mantle = 1
    harlans_loaded_dice = 1
    heart_of_azeroth = 1
    hood_of_the_slithering_loa = 1
    leggings_of_the_galeforce_viper = 1
    mishun_blade_of_tyrants = 1
    seal_of_questionable_loyalties = 1
    sharkhide_grips = 1
    unguent_caress = 1
    writhing_segment_of_drestagath = 1

legendaries: none

itemIDs: 155881, 155889, 158075, 158314, 159318, 159329, 159339, 159461, 165441, 165446, 165447, 169223, 172197, 173946, 174105, 174131

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Windwalker
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    strict = false
    throttleRefresh = false
    throttleTime = false
    allow_fsk = false
    optimize_reverse_harm = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = true
    essences = false
    interrupts = false
    mode = reactive
    potions = false

**Comment by Hekili** [comment]
You will need to provide a snapshot when this is happening per the ticket instructions.
