### ISSUE TITLE
DH blade dance/death sweep not showing

### ISSUE THREAD

**Issue by Shamuraj** [Hekili/hekili#539]
Playing Cycle of hatered and not First Blood casues the addon not to display blade dance or death sweep. If I manually remove the varaible string its working, or if i swap the 2 talents.

this is the data:
build: v9.0.1-1.0.27
level: 50 (50)
class: DEMONHUNTER
spec: havoc

talents: burning_hatred
    cycle_of_hatred
    demonic
    demonic_appetite
    netherwalk
    trail_of_ruin
    unleashed_power

pvptalents: none

covenant: none

azerite: azerite_empowered = 3
    chaotic_transformation = 1
    elemental_whirl = 1
    eyes_of_rage = 1
    furious_gaze = 3
    overwhelming_power = 1
    resounding_protection = 1
    revolving_blades = 1
    soulmonger = 1
    unstable_flames = 1
    vampiric_speed = 1

essences: [essence_of_the_focusing_iris] = 4, breath_of_the_dying = 3, memory_of_lucid_dreams = 3, the_crucible_of_flame = 4

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    bilestained_crawg_tusks = 1
    cephalohide_jacket = 1
    circlet_of_the_enveloping_leviathan = 1
    deadeye_spyglass = 1
    desiccators_blessed_gloves = 1
    heart_of_azeroth = 1
    lord_waycrests_signet = 1
    macabre_ritual_pants = 1
    mishun_blade_of_tyrants = 1
    ooeygooey_galoshes = 1
    pauldrons_of_the_great_convergence = 1
    primal_dinomancers_belt = 1
    ring_of_collective_consciousness = 1
    sea_dogs_cuffs = 1
    torment_in_a_jar = 1

legendaries: none

itemIDs: 158075, 158305, 158362, 159301, 159310, 159312, 159314, 159623, 159653, 169056, 169223, 173943, 174105, 174133, 174143, 174530

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 7
    nameplates = true
    package = Havoc
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    demon_blades_acknowledged = false
    recommend_movement = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Please revisit the ticket instructions re: snapshots.

**Comment by Shamuraj** [comment]
https://pastebin.com/bPaDaTB7

**Comment by Hekili** [comment]
I moved your post to pastebin, per the instructions.

Death Sweep was not recommended, per the priority:

```        41.  death_sweep ( demonic - 2 )
        The action (death_sweep) is usable at (0.00 + 0.00) with cost of 35 fury.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( demonic ) called from ( Havoc:default:12 ) would PASS at 0.00.
        talent.demonic.enabled[true]
         - this entry's criteria FAILS: variable.blade_dance[false]
```

`variable.blade_dance` = `talent.first_blood.enabled[false] | spell_targets.blade_dance1[1.00] >= ( 3 - talent.trail_of_ruin.enabled[true] )`

With Trail of Ruin, you still need at least 2 targets for Death Sweep requirements to be met.

```        45.  blade_dance ( demonic - 6 )
        The action (blade_dance) is usable at (0.00 + 4.44) with cost of 35 fury.
         - the action is ready before the current recommendation (at +4.44 vs. +60.00).
        List ( demonic ) called from ( Havoc:default:12 ) would PASS at 4.44.
        talent.demonic.enabled[true]
         - this entry's criteria FAILS: variable.blade_dance[false] & ! cooldown.metamorphosis.ready[false] & ( cooldown.eye_beam.remains[22.45] > ( 5 - azerite.revolving_blades.rank[1.00] * 3 ) | ( raid_event.adds.in[3600.00] > action_cooldown[4.28] & raid_event.adds.in[3600.00] < 25 ) )
```

Blade Dance also relies on having at least 2 targets (along with some other conditions that are irrelevant when you have fewer than 2 targets).

Sim yourself in single-target and see how often Death Sweep and Blade Dance are cast in the simulation.

**Comment by Hekili** [comment]
(If you think it should be different, you can do some sim testing and link your results.)
