### ISSUE TITLE
Setting frame level?

### ISSUE THREAD

**Issue by tflo** [Hekili/hekili#54]
Is there any way to set the frame level of the icons? (Couldn’t find one, but sometimes I’m just blind…)

If not, then please consider it a suggestion.

Reason: 

I have my Hekili icons on center-left (i.e. directly to the left of the character). The huge Blizzard proc indicators (the ones that surround the character left and right) are overlaying the Hekili icons. 

Not a big issue, but ugly nevertheless. And the Blizzard proc indicators are huge enough to be visible even with the Hekili icons on top.

The Blizz proc indicators seem to be on level 2 in the Medium strata (if I identified it correctly as “SpellActivationOverlayFrame”). So, being able to set Hekili to level 3 or higher should solve the glitch.

The TellMeWhen add-on for example defaults to level 10 (adjustable), which avoids the described issue.

Thanks for considering. (Or thanks for any hints, in case I have overlooked an already existing setting for that.)

**Comment by Hekili** [comment]
Seems reasonable to open that up.  I remember doing some wonky stuff with framelevels to keep text visible over glows, so it'll require some testing.

**Comment by tflo** [comment]
Just checked the [HeroRotation](https://github.com/herotc/hero-rotation) addon and it also is on frame level 10 (like TMW).

So, if it is too much work to implement a user-adjustable frame level setting, it would _probably_ be an impeccable solution to simply hard-set the frame level to 10 or such.

Of course, I can’t speak for other users, but _I think_ that the average Hekili user would always prefer to see his Hekili icons on top of other elements (be it the proc indicators or something else), instead of the other way round.

---

BTW: It seems the Curse link in the General tab of the Hekili settings is broken. (Should be `https://www.curseforge.com/wow/addons/hekili`)

BTW 2: Thanks for developing Hekili. Have been using the above mentioned HeroRotation (formerly Aethys Rotation) until now and just “discovered” Hekili two days ago. Seems really great so far, and I really love the customizability (UI and APLs) without having to tinker with the Lua files.

**Comment by beanlord7** [comment]
I also came to here just to request this. A simple drop-down menu for strata would be highly appreciated, as some other UI elements tend to obscure hekili when raiding especially. 

PS: I'd also like to thank you for developing this amazing addon. I've tried probably all of rotation helper addons and I can say that you obviously put in the most effort and love into this project. It's 100% above the competition and you should be proud. :)

**Comment by Hekili** [comment]
Will pursue this, it's in a pile of other enhancements (anchoring to personal resource display, for example).

**Comment by Hekili** [comment]
Should be available now.
