### ISSUE TITLE
[Sub Rogue] Symbols of Death usage

### ISSUE THREAD

**Issue by Bakamaka11** [Hekili/hekili#542]
Hello, the addon often recommends me to use Symbols of Death despite me having 80++ energy. Is it supposed to be so and there is a math behind it or just some kind of bug? The skill instantly regenerates 40 energy and lot of energy would be wasted, since cap is 100. 

https://www.wowhead.com/spell=212283/symbols-of-death

**Comment by Hekili** [comment]
Please follow the instructions when submitting a ticket.

**Comment by Hekili** [comment]
You can review Symbols of Death requirements in the Subtlety priority.

`actions.cds+=/symbols_of_death,use_off_gcd=1,if=buff.shuriken_tornado.up&buff.shuriken_tornado.remains<=3.5`

`actions.cds+=/symbols_of_death,if=variable.snd_condition&!cooldown.shadow_blades.up&(talent.enveloping_shadows.enabled|cooldown.shadow_dance.charges>=1)&(!talent.shuriken_tornado.enabled|talent.shadow_focus.enabled|cooldown.shuriken_tornado.remains>2)&(!essence.blood_of_the_enemy.major|cooldown.blood_of_the_enemy.remains>2)`

None of these are checking for Energy.  You could try adding conditions related to Energy and running simulations, but consider that the Rogue TCers are very thorough.  I'd be extremely surprised if they did not do testing around trying to optimize away Energy overcapping.  When you do that, there's an opportunity cost (you'd delay SoD, which means you potentially use fewer SoDs over the course of a fight, which means you spend less time getting the other benefits of the ability).
