### ISSUE TITLE
Hekili not suggesting imlosion for demonology warlock

### ISSUE THREAD

**Issue by Jimmis79** [Hekili/hekili#543]
build: v9.0.1-1.0.28
level: 50 (50)
class: WARLOCK
spec: demonology

talents: demon_skin
    demonic_calling
    demonic_consumption
    dreadlash
    mortal_coil
    soul_conduit
    soul_strike

pvptalents: none

covenant: none

azerite: demonic_meteor = 1
    desperate_power = 2
    explosive_potential = 1
    heart_of_darkness = 2
    overwhelming_power = 1
    unstable_flames = 1

essences: [breath_of_the_dying] = 1, the_crucible_of_flame = 1

sets/legendaries/artifacts: none

gear: apothecary_spellstaff = 1
    argent_conscripts_bracers = 1
    argent_conscripts_cord = 1
    argent_conscripts_gloves = 1
    argent_conscripts_robe = 1
    argent_conscripts_treads = 1
    ashjrakamas_shroud_of_resolve = 1
    grondos_todo_list = 1
    gruuks_evil_eye = 1
    heart_of_azeroth = 1
    nerubian_aegis_ring = 1
    rimewoven_pantaloons = 1
    ring_of_carnelian_and_sinew = 1
    vile_manipulators_amice = 1
    vile_manipulators_hood = 1

legendaries: none

itemIDs: 111548, 111948, 158075, 165614, 169223, 173844, 173845, 183535, 183538, 183541, 183576, 183577, 183631, 183673, 183674

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Demonology
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

The Hekili is not suggesting the implosion ability at AOE situations ( i want to have the aoe buff "Explosion Potential" from the azerite gear) and i want to know if there is something wrong with my set up or something has change after the prepatch for the aoe rotation in general for demonology warlocks. Thanks in advance!

**Comment by Hekili** [comment]
Conditions for Implosion are:

```
actions+=/implosion,if=(level<50&active_enemies>2|azerite.explosive_potential.rank>1&buff.explosive_potential.remains<3)&buff.wild_imps.stack>=3
```

At 50, you need at least 2 ranks of Explosive Potential (you have 1) before you'll use Implosion, by design.  Sim yourself and look at your Implosion usage in sim.
