### ISSUE TITLE
Affliction warlock target cycling

### ISSUE THREAD

**Issue by MrSmurfy** [Hekili/hekili#545]
Hello,

For some reason Hekili is not suggesting the cycling of targets after casting Seed of Corruption. Ideally you want to maintain Agony on all targets, for soul shard generation and for increasing your damage output when casting Malefic Rupture.

Am I doing something wrong, or is this perhaps broken?
Or am I expected to switch targets myself without it being suggested? Either is fine for me, just curious.. :)
Thanks for this great addon.

**Comment by Hekili** [comment]
Hi, reread the ticket instructions and resubmit with the required info and I'll take a look.
