### ISSUE TITLE
Druid ticks_gained_on_refresh not accounting for time to die.

### ISSUE THREAD

**Issue by ShmooDude** [Hekili/hekili#547]
`ticks_gained_on_refresh `isn't accounting for `target.time_to_die`.

For example, on Rip, the simc apl has `druid.rip.ticks_gained_on_refresh > variable.rip_ticks` which should prevent it from casting Rip on targets that are about to die.  However, this is not the case.

After looking at the code, this is because it is only considering `fight_remains `and not `target.time_to_die` for most of the calculations.  In the State file, `fight_remains` has `if not t.boss then return 3600 end`.

I could see two ways to fix this.

1) Modify the `tick_calculator` function so that it considers both `target.time_to_die` and `fight_remains` for all it's calculations.  #546 is how I did it on my local copy.

2) Change `fight_remains` to not only be on bosses.  Since I don't actually know the scope of what `fight_remains` is supposed to do, I don't know whether this would be a good option or not.

**Comment by Hekili** [comment]
Thanks again for this.
