### ISSUE TITLE
PvP addition to conditions

### ISSUE THREAD

**Issue by DavidBruun** [Hekili/hekili#548]
I would find it very useful to be able to add in actions with the condition to check for if target is enemy player of opposite faction. That would improve the addons usability in open world PvP or instanced PvP tremendously, so you don't have to make seperate profiles and switch up all the time.

**Comment by Hekili** [comment]
Is `target.is_player` not sufficient for this purpose?  Let me know.  Thanks.

**Comment by vicwac** [comment]
In addition to checking if the target is a human player, can Hekili also check what class and spec the target player is and recommend skills, for example as a Hunter if fighting a rogue, feral druid, mage or another hunter (any class that has stealth or invisibility), the rotation would recommend Hunter's Mark if not cast on that player.

**Comment by Hekili** [comment]
I won't put PvP strategy into the default priorities, but I can provide the expressions (like you've described) that you can use to customize your own priority.

I'll take a look at `target.class` and `target.specialization` and see what I can come up with.  To be honest, though, if I have to rely on WoW's inspect system to get the specialization information, I'm probably not going to do it.

**Comment by vicwac** [comment]
> I won't put PvP strategy into the default priorities, but I can provide the expressions (like you've described) that you can use to customize your own priority.
> 
> I'll take a look at `target.class` and `target.specialization` and see what I can come up with. To be honest, though, if I have to rely on WoW's inspect system to get the specialization information, I'm probably not going to do it.

I can try to input it and see if it works in pvp, what is the exact parameter? Is it "target.is_player & target.class.rogue"? How do you input multiple classes, "target.is_player & target.class.rogue | target.class.hunter | target.class.druid | target.class.mage" for example?

Sorry not too familiar with simulationcraft syntax.

**Comment by Hekili** [comment]
`target.class` will exist in the next release.  I'm not going to do specializations (requires using inspect API and that is asynchronous).  If there's a quick way to identify healers, I'm open to that.

You'd use `target.class` as a comparison vs. the english class name strings from Blizzard, but in lowercase.

`target.class = "demonhunter"`
`target.class != "priest"`

If you don't have a target, `target.class` is `"virtual"`.
If your target is not a player, `target.class` is `"npc"`.
