### ISSUE TITLE
Hunter’s Mark no longer working since 8.1.0-16-beta2

### ISSUE THREAD

**Issue by tflo** [Hekili/hekili#55]
Hunter’s Mark (MM Hunter) is behaving weirdly in 8.1.0-16-beta2 and 8.1.0-16-beta3:

- Hekili no longer recommends Hunter’s Mark as precombat action
- When applied to the target, then it becomes _the only_ recommendation (the entire queue is filled with Hunter’s Mark and all subsequent recommendations are Hunter’s Mark)

Here the relevant instances from a snapshot:

```
[  3]  Checking hunters_mark (Marksmanship - precombat - 7 )...
hunters_mark is known and enabled.
The action (hunters_mark) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.
```

```
[  3]  Checking hunters_mark (Marksmanship - precombat - 7 )...
hunters_mark is known and enabled.
We are already in-combat and this pre-combat action is not essential.  Skipping.
```

```
[ 10]  Checking hunters_mark (Marksmanship - cds - 1 )...
hunters_mark is known and enabled.
The action (hunters_mark) is unusable at (1.33 + 0.00) because ability 'usable' function returned false without explanation.
```

…and some more of the same type.

Going back to 8.1.0-16-beta1 or earlier fixes the issue.

**Comment by Hekili** [comment]
Please try -beta5 and let me know if this is persisting for you.

**Comment by tflo** [comment]
Only a brief test fight, but seems to be fine now (b5). Thanks for being so fast :)
