### ISSUE TITLE
IsKnown error in Demonology

### ISSUE THREAD

**Issue by SHJordan** [Hekili/hekili#551]
**Describe the Bug/Issue**
During rotation it will popup this error

**To Reproduce**
Just follow rotation.

**Expected behavior**
No UI error

**Screenshots**
![image](https://user-images.githubusercontent.com/884602/99669130-64632680-2a4d-11eb-9daf-0328aac7e659.png)

**PUT ISSUE REPORT LINK HERE:**
build: v9.0.2-1.0.1
level: 39 (39)
class: WARLOCK
spec: demonology

talents: bilescourge_bombers
    dark_pact
    doom
    soul_strike

pvptalents: call_fel_lord
   call_felhunter

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ancient_bloodmoon_cloak = 1
    eternal_amulet_of_the_redeemed = 1
    exquisite_sunderseer_mantle = 1
    grand_staff_of_jordan = 1
    karabor_sage_treads = 1
    mantisweave_cord = 1
    mechagonian_tabard = 1
    moonstone_luck_token = 1
    seal_of_sullied_mending = 1
    sporebat_larval_pod = 1
    steamburst_gloves = 1
    steamburst_wristwraps = 1
    tattered_dreadmist_leggings = 1
    tattered_dreadmist_mask = 1
    tattered_dreadmist_robe = 1
    throbbing_swampfly_venom_sac = 1

legendaries: none

itemIDs: 107315, 108906, 112597, 112616, 112802, 113160, 113161, 114338, 122250, 122256, 122262, 122368, 122378, 122384, 122663, 174068

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Demonology
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = true

**PUT ERROR MESSAGE(S) HERE:**
Message: ...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:247: attempt to call global 'IsKnown' (a nil value)
Time: Thu Nov 19 09:51:07 2020
Count: 41
Stack: ...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:247: attempt to call global 'IsKnown' (a nil value)
[string "=[C]"]: in function `IsKnown'
[string "@Interface\AddOns\Hekili\Classes\WarlockDemonology.lua"]:247: in function <...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:142>
[string "@Interface\AddOns\Hekili\Classes.lua"]:699: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:56: in function <Interface\AddOns\Hekili\Events.lua:50>

Locals:

**Comment by Hekili** [comment]
Will fix in next build.
