### ISSUE TITLE
Affliction Warlock - No Rec and Auto-Snapshotting

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#553]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**

Auto Snapshot for affliction each time combat start, probably problem with recommendations, and problems with queue display. 
Video: https://youtu.be/lPKXMu5GNe0 ( recommendations TOP left corner )
REcommendations appear, disappearing. I test on hunter, warrior , destro warlock and only on Affliction i see something like this. 

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/fhkbR3ua

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/Hsan0hpb

**Comment by Hekili** [comment]
The addon is stopping recommendations early based on your throttle settings (/hekili > Affliction > Performance).
