### ISSUE TITLE
Unholy DK - Recommend Target Swaps and # of Targets

### ISSUE THREAD

**Issue by Trilkin** [Hekili/hekili#554]
**Bug/Issue**
The current SimC APL is working off of a BiS list that is impossible to achieve due to certain features (corruptions) being outright removed already. This is manifesting most obviously in the AOE recommendations for splashing the Festering Strike DoT and the likely assumption of more Rune refunds than you would actually get.

Additionally - and partially relatedly - there is no fall-back option in the case of not enough mobs being wounded to allow the rest of the rotation to continue. Simply put: it outright never tells you to use DnD if you don't have enough mobs dotted. It then stops with no recommendation until you change target or cast DnD (possibly any ability?)

**To Reproduce**
Just play UH with a DK with the current ilvl 100/110 catch up gear and the existing APL. You will see both a) lower DPS than you can potentially sim and b) the priority issue mentioned above IF you use 'Recommend Target Swaps.' The Festermight recommendation is turned off. This becomes most egregious in chain-pulling situations.

**Expected behavior**
Since essences are about to get turned off, this is largely a moot issue, HOWEVER: I expect that certain essences would be looked for when recommending how many targets to swap/spread dots to. That's probably largely more a SimC problem than it is a Hekili one, though. In the mean time, however, I would say that it would be best to just use a better middle ground target amount (3 seems best. read below for raidbots outputs from my character for more on why.)

As for the no recommendations issues, I am giving six separate snapshots to illustrate them. There needs to be some sort of fall back loop to prevent it from just outright stopping recommendations because you didn't spread dots. Note, again, this only happens if Recommend Target Swaps is turned on. This issue doesn't appear otherwise.

**Snapshots**

Note: All of these were caused because I didn't have enough targets dotted with Recommend Target Swaps enabled.

https://pastebin.com/ewuHZRuc
https://pastebin.com/Juq9B43s
https://pastebin.com/FGpGNZzD
https://pastebin.com/5CQHZkFt
https://pastebin.com/MMvBqqT5
https://pastebin.com/4ny8XpPR

**RaidBots Links**

https://www.raidbots.com/simbot/report/3TrKSR79soj7DuQPTtsnsq - 5 Swap
https://www.raidbots.com/simbot/report/49zU6sbAcYDmvHqYjibAdg - 4 Swap
https://www.raidbots.com/simbot/report/mfmRtqgHHfyko6P8dH2jHG - 3 Swap
https://www.raidbots.com/simbot/report/bnLHxc6H2xGXdt7jfmRgpA - 2 Swap

The only line in the APL that was changed was:

actions.aoe_setup+="/any_dnd,if=death_knight.fwounded_targets>=5"

I incrementally lowered this number to produce the results above. (i.e. targets>=4 for the 4 swap and so on.)

The difference is absolutely minute, but it *is* there (and it also makes for a smoother rotation when there are fewer swaps.)

**Comment by Hekili** [comment]
I'm going to close this ticket as we'll just need to keep an eye on the evolution of the sim priority and this doesn't show enough cost/benefit to make it worth maintaining a fork.
