### ISSUE TITLE
Elemental Shaman recommendations give conflicting advice regarding elementals

### ISSUE THREAD

**Issue by jokeyrhyme** [Hekili/hekili#555]
**Describe the Bug/Issue**
Hekili seems to recommend using Earth Elemental even when I have my Storm Elemental active, even though doing so would dismiss the Storm Elemental early

**To Reproduce**
Elemental Shaman with Storm Elemental and Primal Elementalist talents

**Expected behavior**
Whilst the Shaman has any elemental active, they should not get a recommendation to summon another elemental

I'm not sure if it's harder to detect, but we want this expected behaviour even without the Primal Elementalist talent

**WHEN SUBMITTING AN ISSUE:**

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/Wsswj1Tx

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/NVNGUQtq

**Comment by Hekili** [comment]
Did you take your snapshot when Storm Elemental was up, or no?

**Comment by jokeyrhyme** [comment]
Yes, it was up when I took the snapshot, and Earth Elemental was the left-most (first) recommended next ability

**Comment by Hekili** [comment]
Try the newest alpha (1.0.3-alpha2) and it should be resolved.

**Comment by jokeyrhyme** [comment]
Thanks heaps! Also, earlier, I should have said thanks for working on this addon and the short turn around on this report :) <3

**Comment by Hekili** [comment]
Thanks for reporting.  Let me know if you find anything else.  (Or if this doesn't seem fully resolved for you.)  Take care!
