### ISSUE TITLE
Elemental Shaman - Echoing Shock timing wrong

### ISSUE THREAD

**Issue by djcosmic22** [Hekili/hekili#559]
BEFORE SUBMITTING AN ISSUE:

Check to see if you are using the latest version of the addon. If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Check to see if someone else has already opened an issue report here. Please don't submit repeat reports.

Describe the Bug/Issue
Echoing Shock is not being placed in the rotation at the correct time. In single target, it should be prioritized before Lava Burst, and in AoE it should be prioritized before Earthquake

To Reproduce

DPS on a target dummy as Elemental Shaman with Echoing Shock talented

Screenshots
N/A

WHEN SUBMITTING AN ISSUE:

Please provide the following information. Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

The information from the Issue Reporting tab ( /hekili > Issue Reporting ). This provides your talent and gear information. You can paste it to pastebin.com and provide a link here.
PUT ISSUE REPORT LINK HERE: https://pastebin.com/kufUgBWc

If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot. This is not a screenshot. A snapshot can be generated by binding the Pause feature on the Toggles tab. When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab. Copy and paste this to pastebin.com and provide the link here.
PUT SNAPSHOT LINK HERE: https://pastebin.com/axJ3yXQT and https://pastebin.com/NbWmpS7A

If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located. You can paste the error information here or use pastebin.com for that as well.
PUT ERROR MESSAGE(S) HERE: N/A

**Comment by Hekili** [comment]
> BEFORE SUBMITTING AN ISSUE:
> Check to see if you are using the latest version of the addon. If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Update to 1.0.3 and you should be set.
