### ISSUE TITLE
8.1.0-16-beta3 - New Errors

### ISSUE THREAD

**Issue by behub-au** [Hekili/hekili#56]
Hello !

Since updating, so far 2 new errors are happening.

Channeling a word quest action (Quest: Gravity Matters [Invasion]):
```lua
142x Hekili\Classes.lua:990: attempt to call global 'formatKey' (a nil value)
Hekili\Classes.lua:990: in function `generate'
Hekili\State.lua:2632: in function <Hekili\State.lua:2621>
Hekili\State.lua:2663: in function <Hekili\State.lua:2621>
Hekili\State.lua:4505: in function `reset'
Hekili\Core.lua:1109: in function `ProcessHooks'
Hekili\UI.lua:1057: in function <Hekili\UI.lua:677>

Locals:
t = <table> {
 lastApplied = 0
 v1 = 286711
 v2 = true
 caster = "player"
 duration = 2.184000
 timeMod = 1
 expires = 262305.485000
 key = "casting"
 name = "X-52 Delevitator"
 applied = 262303.301000
 v3 = 0
 unit = "player"
 count = 1
 lastCount = 0
}
auraType = "buff"
unit = "player"
spell = "X-52 Delevitator"
_ = nil
_ = nil
startCast = 262303.301000
endCast = 262305.485000
_ = nil
_ = "X-52 Delevitator"
notInterruptible = true
spellID = 286711
castInfo = nil
(*temporary) = nil
(*temporary) = "X-52 Delevitator"
(*temporary) = "attempt to call global 'formatKey' (a nil value)"
class = <table> {
 totems = <table> {
 }
 itemMap = <table> {
 }
 abilityList = <table> {
 }
 stateExprs = <table> {
 }
 auras = <table> {
 }
 pets = <table> {
 }
 itemPack = <table> {
 }
 interrupts = <table> {
 }
 gear = <table> {
 }
 trinkets = <table> {
 }
 packs = <table> {
 }
 itemList = <table> {
 }
 abilities = <table> {
 }
 file = "HUNTER"
 stateTables = <table> {
 }
 stances = <table> {
 }
 primaryResource = "focus"
 range = 8
 specs = <table> {
 }
 hooks = <table> {
 }
 settings = <table> {
 }
 resources = <table> {
 }
 toggles = <table> {
 }
 powers = <table> {
 }
 stateFuncs = <table> {
 }
 pvptalents = <table> {
 }
 potionList = <table> {
 }
 itemSettings = <table> {
 }
 potion = "potion_of_bursting_blood"
 talents = <table> {
 }
 potions = <table> {
 }
 num = 4
}
```

During Combat (Survival Hunter tested only atm):
```lua
813x Hekili\State.lua:1537: attempt to perform arithmetic on field 'remains' (a boolean value)
Hekili\State.lua:1537: in function <Hekili\State.lua:1279>
[string "-- Balance:default:19 recheck..."]:2: in function `Recheck'
Hekili\State.lua:1153: in function `recheck'
Hekili\Core.lua:722: in function `GetPredictionFromAPL'
Hekili\Core.lua:1029: in function `GetNextPrediction'
Hekili\Core.lua:1197: in function `ProcessHooks'
Hekili\UI.lua:1057: in function <Hekili\UI.lua:677>

Locals:
InCombatSkipped```

**Comment by Hekili** [comment]
Make sure to reset your bugsack re: the second one; that's a Balance APL so you shouldn't see something like that while testing Survival.  Fix for the first part will be out in a moment.

**Comment by behub-au** [comment]
Ahh yep, that one would of been from last night and i just downgraded back to release and was going to test it after raid. I'll let you know if i still get that error again (the second one).

**Comment by behub-au** [comment]
Yep, logged on druid and moment i enter combat:

```lua
873x Hekili\State.lua:1537: attempt to perform arithmetic on field 'remains' (a boolean value)
Hekili\State.lua:1537: in function <Hekili\State.lua:1279>
[string "-- Balance:default:19 recheck..."]:2: in function `Recheck'
Hekili\State.lua:1153: in function `recheck'
Hekili\Core.lua:722: in function `GetPredictionFromAPL'
Hekili\Core.lua:1029: in function `GetNextPrediction'
Hekili\Core.lua:1197: in function `ProcessHooks'
Hekili\UI.lua:1057: in function <Hekili\UI.lua:677>

Locals:
InCombatSkipped

**Comment by Hekili** [comment]
You sure you're updated to the latest version?  I don't have 'remains' on line 1537 in -beta5.

**Comment by behub-au** [comment]
Curse says I have it installed. Re-installed to be sure and restarted client. Still same error.

**Comment by behub-au** [comment]
> build: v8.1.0-16-beta3
> level: 120
> class: DRUID
> spec: balance
> 
> talents: fury_of_elune
>     restoration_affinity
>     starlord
>     twin_moons
>     typhoon
>     warrior_of_elune
>     wild_charge
> 
> traits: arcanic_pulsar=1
>     azerite_empowered=1
>     blood_rite=1
>     blood_siphon=3
>     dawning_sun=1
>     power_of_the_moon=1
>     resounding_protection=1
>     seductive_power=1
> 
> sets/legendaries/artifacts: none
> 
> gear:     7th_legionnaires_long_cloak=1
>     seal_of_questionable_loyalties=1
>     shoulders_of_the_sanguine_monstrosity=1
>     darkwood_sentinels_tunic=1
>     seafarer_striders=1
>     darkwood_sentinels_grips=1
>     fashionable_undershirt=1
>     desecrated_blade_of_the_disciples=1
>     stretched_sinew_waistcord=1
>     ancient_knot_of_wisdom=1
>     crown_of_aakuls_dark_reign=1
>     venerated_raptorhide_bindings=1
>     wavecaller_beacon=1
>     conch_of_dark_whispers=1
>     band_of_multisided_strikes=1
>     seawalkers_pantaloons=1
>     heart_of_azeroth=1

**Comment by Hekili** [comment]
Curse is probably confused by your downgrade.  Upgrade to -beta5; you can see from the build: line that you have -beta3.

**Comment by behub-au** [comment]
If i go back to the 'release' version, the error no longer occurs

**Comment by behub-au** [comment]
Ahh yep, will do it again

**Comment by behub-au** [comment]
I'll have to manually install it. Lately it has been taking hours for twitch client to catch up even after restarting it.

**Comment by behub-au** [comment]
45 minutes later after you posted even beta 4 and twitch is still convinced beta 3 is the latest.

I can confirm after manually installing beta 5 that the error is gone. Thanks.
