### ISSUE TITLE
How i can disable a White flash after Gcd that added in new version?

### ISSUE THREAD

**Issue by BohdanPenchukov** [Hekili/hekili#561]
How i can disable a White flash after Gcd that added in new version? Im Asking to add a fuction to disable it.
![image](https://user-images.githubusercontent.com/23499600/99867597-7cf54d00-2bc3-11eb-92db-fe7ac9174ac3.png)

**Comment by Hekili** [comment]
I didn't add the cooldown flash.  Were you using Masque?  I noticed that you closed the ticket.

**Comment by BohdanPenchukov** [comment]
It was because of masque dude ye. Sorry for ticket i was wanted to delete it. Sorry again
