### ISSUE TITLE
Shadow Priest's Void eruption's cast timing is different from simc's cast timing.

### ISSUE THREAD

**Issue by iPisces77** [Hekili/hekili#563]
When I use addon, it tells me the loop is
![Snipaste_2020-11-21_19-46-49](https://user-images.githubusercontent.com/39837211/99876620-dea0d000-2c32-11eb-8a97-833ea2f02388.png)
But the simc results are
![Snipaste_2020-11-21_19-45-05](https://user-images.githubusercontent.com/39837211/99876527-2d9a3580-2c32-11eb-8ebc-28deb04d49f8.png)

**Comment by iPisces77** [comment]
https://pastebin.com/HrkYWFR5

**Comment by iPisces77** [comment]
I think there is a problem with the condition pet.fiend.down, where simc means fiend already exists, and addon means fiend is gone!

**Comment by Hekili** [comment]
I moved your snapshot to pastebin per the instructions (so it remains readable).  There is some tuning for Insanity generation that I'll work on, that will get that prediction in alignment with simc more proactively, but keep in mind that the addon still reacts to actual Insanity generation and is going to update to recommend Void Eruption as soon as you actually have the Insanity for it it.

What makes you think `pet.fiend.down` means that your fiend is up?

**Comment by Hekili** [comment]
Reading through the sims, it does look like you're right about fiend.  Which is massively stupid.  `pet.X.up` means the pet is active in every other context, so I'll have to make this backwards for Shadow Priests in particular.

**Comment by Hekili** [comment]
I've submitted a ticket for simulationcraft to explore this behavior; I really think they should be using `pet.fiend.up` to reflect that the pet is active (similar to how you'd use `buff.voidform.up` to show that the buff is active).

In my working copy, I've modified the logic for Shadow Priests with the following result:

![image](https://user-images.githubusercontent.com/9438134/99878801-f0a05580-2bd5-11eb-9ccc-b90e8935be04.png)

I'll post a new alpha or beta soon that includes the change.
