### ISSUE TITLE
Demonology never recommends Tyrant - Tyrant_Ready is not working as intended

### ISSUE THREAD

**Issue by smadam813** [Hekili/hekili#564]
I have been trying to address locally myself, but the issue is tyrant ready logic just feels really off.  The only thing in normal SIMC apl which sets tyrant_ready to true is if Tyrant is off cooldown.

**Comment by Hekili** [comment]
Please provide the info in the ticket instructions.

**Comment by smadam813** [comment]
djsisson pull request fixed my issue.  vilefiend had a spelling error.

**Comment by Hekili** [comment]
Sure, but keep in mind that I wouldn't have been able to connect the two issues without the info that is asked for in the ticket instructions.  Nice that it's solved though.
