### ISSUE TITLE
Use a title that describes the problem scenario.

### ISSUE THREAD

**Issue by Belrend** [Hekili/hekili#565]
**Message: Interface\AddOns\Hekili\Options.lua:6608: script ran too long
Time: Sun Nov 22 07:00:34 2020
Count: 1
Stack: Interface\AddOns\Hekili\Options.lua:6608: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\Hekili\Options.lua"]:6608: in function `EmbedPackOptions'
[string "@Interface\AddOns\Hekili\Options.lua"]:8196: in function `RefreshOptions'
[string "@Interface\AddOns\Hekili\Classes.lua"]:5255: in function `SpecializationChanged'
[string "@Interface\AddOns\Hekili\Events.lua"]:396: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:56: in function <Interface\AddOns\Hekili\Events.lua:50>

Locals: 

Demonology Warlock.. Followup error

Message: ...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:247: attempt to call global 'IsKnown' (a nil value)
Time: Sun Nov 22 07:36:20 2020
Count: 89
Stack: ...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:247: attempt to call global 'IsKnown' (a nil value)
[string "=[C]"]: in function `IsKnown'
[string "@Interface\AddOns\Hekili\Classes\WarlockDemonology.lua"]:247: in function <...nterface\AddOns\Hekili\Classes\WarlockDemonology.lua:142>
[string "@Interface\AddOns\Hekili\Classes.lua"]:699: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:56: in function <Interface\AddOns\Hekili\Events.lua:50>

Locals:

**Comment by Hekili** [comment]
I'm going to ask you to add all the information in the ticket instructions, but first:

Which version of the addon do you have?  Did you make sure you were up to date with the latest?  Thanks.
