### ISSUE TITLE
Custom Priority / Elemental / Earth Shield precombat

### ISSUE THREAD

**Issue by RazaronGit** [Hekili/hekili#566]
Before Shadowlands I added a line,

talent.earth_shield.enabled & buff.earth_shield.down

and turned off the lightning shield buff, but now it's not working. It doesn't show up on the primary bar, I'm not well versed in this so could anyone help me?

**Comment by RazaronGit** [comment]
Seems to work with elemental when the precombat is pretty bare.. might be to do with what already is there for enhancement.

**Comment by Hekili** [comment]
You'd need to post a snapshot for me to see the decision-making, but if your entry for Earth Shield is at the end of the priority, after a spell that would cause combat to begin, it's not going to be recommended.

**Comment by RazaronGit** [comment]
Basically I like to have it so if I choose the Earth Shield talent it appears priority to recast if it's down, I put the, 

talent.earth_shield.enabled & buff.earth_shield.down

line in precombat and default rotation, so in pvp it'll always remind me to recast if it's fallen down. I also edit -just- the precombat lightning shield conditions so it doesn't appear if I choose the earth shield talent. 

It works for elemental but for some reason the same code doesn't work for enhancement. 

**Elemental Precombat which works**

![WoWScrnShot_112420_164029](https://user-images.githubusercontent.com/74959747/100124879-16e32100-2e74-11eb-9724-ae8a3d15d1bf.jpg)
![WoWScrnShot_112420_164031](https://user-images.githubusercontent.com/74959747/100124895-1a76a800-2e74-11eb-81ee-1f2158ae897f.jpg)
![WoWScrnShot_112420_164034](https://user-images.githubusercontent.com/74959747/100124909-1e0a2f00-2e74-11eb-8ad7-12fde4c9c80e.jpg)

**Elemental default rotation which works**

![WoWScrnShot_112420_164045](https://user-images.githubusercontent.com/74959747/100125008-34b08600-2e74-11eb-9d25-cea9eeee9902.jpg)
![WoWScrnShot_112420_164040](https://user-images.githubusercontent.com/74959747/100125018-3a0dd080-2e74-11eb-9296-ab20baac98e0.jpg)

**Enhancement precombat doesn't work**

![WoWScrnShot_112420_164003](https://user-images.githubusercontent.com/74959747/100125082-48f48300-2e74-11eb-9473-1d4c8ef8bdf1.jpg)
![WoWScrnShot_112420_164006](https://user-images.githubusercontent.com/74959747/100125134-5447ae80-2e74-11eb-8966-f74708c4702e.jpg)
![WoWScrnShot_112420_164009](https://user-images.githubusercontent.com/74959747/100125142-56aa0880-2e74-11eb-95ba-04831de056bc.jpg)

**Enhancement default rotation doesn't work**

![WoWScrnShot_112420_164103](https://user-images.githubusercontent.com/74959747/100125214-6d505f80-2e74-11eb-9926-dc512383292c.jpg)
![WoWScrnShot_112420_164106](https://user-images.githubusercontent.com/74959747/100125224-70e3e680-2e74-11eb-9d75-4cb2fbddad16.jpg)


Same conditions but different results. Probably something really simple, again I'm really not well versed in to this. 

Thanks :)

**Comment by Hekili** [comment]
Snapshot, not screenshots.  Refer back to the instructions in a new ticket.

**Comment by Hekili** [comment]
Earth Shield's spell ID changed for Enhancement in Shadowlands.  I've updated to match it, which will be in the next release.

At that time, something like this should work:

![image](https://user-images.githubusercontent.com/9438134/100186380-defbce00-2eb3-11eb-8963-e17d203f7c8a.png)

![image](https://user-images.githubusercontent.com/9438134/100186395-e6bb7280-2eb3-11eb-9c23-457414fd79b1.png)

It's worth noting, that you don't need to check `talent.earth_shield.enabled` to use Earth Shield -- if you don't have the talent, the addon knows you can't use it and rules it out internally.
