### ISSUE TITLE
WW Monk Fortifying Brew not being recommended

### ISSUE THREAD

**Issue by vicwac** [Hekili/hekili#567]
Touch of Karma and Fortifying Brew are not being recommended even though I set it at health.percent <=60 and <=40 respectively under the default category. Strangely If I remove Touch of Karma from the priorities list, it gets auto recommended at 80% hp. Would be great if we could get a GUI slider to set the % at which to recommend these two defensives (or any big cd defensives for all classes for that matter).

Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.4
level: 52 (52)
class: MONK
spec: windwalker

talents: chi_wave
    dance_of_chiji
    fist_of_the_white_tiger
    good_karma
    inner_strength
    tigers_lust
    whirling_dragon_punch

pvptalents: alpha_tiger
   pressure_points
   turbo_fists

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    corpuscular_leather_greaves = 1
    darkheart_robe = 1
    darkwood_sentinels_armguards = 1
    darkwood_sentinels_cinch = 1
    gorak_tuls_mantle = 1
    harlans_loaded_dice = 1
    heart_of_azeroth = 1
    hood_of_the_slithering_loa = 1
    leggings_of_the_galeforce_viper = 1
    mishun_blade_of_tyrants = 1
    overclocking_bit_band = 1
    sharkhide_grips = 1
    thornwoven_band = 1
    unguent_caress = 1
    writhing_segment_of_drestagath = 1

legendaries: none

itemIDs: 155881, 155889, 158075, 159318, 159329, 159339, 162548, 165446, 165447, 169159, 169223, 172197, 173946, 174105, 174131, 174144

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 20
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Windwalker
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    strict = false
    throttleRefresh = false
    throttleTime = false
    allow_fsk = false
    optimize_reverse_harm = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = false
    mode = automatic
    potions = false

New Recommendations for [ Primary ] requested at 18:32:45 ( 997647.16 ); using built-in ( Windwalker ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: chi[ 0.00 / 5.00 ], energy[ 100.00 / 100.00 ], mana[ 13795.00 / 13795.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Windwalker - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   potion ( precombat - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.04ms
        TimeData:Windwalker-precombat-1:potion:0.04
        
        2.   variable ( precombat - 2 )
         - variable.xuen_on_use_trinket will check this script entry ( Windwalker:precombat:2 )
        0
        Time spent on this action:  0.09ms
        TimeData:Windwalker-precombat-2:variable:0.09:Post-TTR and Essential:0.06
        
        3.   chi_burst ( precombat - 3 ) - talent [ chi_burst ] missing
        Time spent on this action:  0.04ms
        TimeData:Windwalker-precombat-3:chi_burst:0.04
        
        4.   chi_wave ( precombat - 4 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.04ms
        TimeData:Windwalker-precombat-4:chi_wave:0.04
    
    Completed precombat action list [ Windwalker - precombat ].
    
    Processing default action list [ Windwalker - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        5.   touch_of_karma ( default - 1 )
        The action (touch_of_karma) is unusable at (0.00 + 0.00) because incoming damage not sufficient (20% / 3sec) to use.
        Time spent on this action:  0.09ms
        TimeData:Windwalker-default-1:touch_of_karma:0.09:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.03
        
        6.   fortifying_brew ( default - 2 ) - PvP talent [ fortifying_brew ] missing
        Time spent on this action:  0.03ms
        TimeData:Windwalker-default-2:fortifying_brew:0.03
        
        7.   spear_hand_strike ( default - 3 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-3:spear_hand_strike:0.02
        
        8.   variable ( default - 4 )
         - variable.hold_xuen will check this script entry ( Windwalker:default:4 )
        cooldown.invoke_xuen_the_white_tiger.remains[0.00] > fight_remains[3600.00] | fight_remains[3600.00] < 120 & fight_remains[3600.00] > cooldown.serenity.remains[90.00] & cooldown.serenity.remains[90.00] > 10
        Time spent on this action:  0.03ms
        TimeData:Windwalker-default-4:variable:0.03:Post-TTR and Essential:0.01
        
        9.   potion ( default - 5 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-5:potion:0.02
        
        10.  call_action_list ( default - 6 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - buff.serenity.up[false]
        
        11.  call_action_list ( default - 7 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - buff.weapons_of_order.up[false]
        
        12.  call_action_list ( default - 8 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - time[47.31] < 4 & chi.current[0.00] < 5 & ! pet.xuen_the_white_tiger.active[false]
        
        13.  fist_of_the_white_tiger ( default - 9 )
        The action (fist_of_the_white_tiger) is usable at (0.00 + 0.00) with cost of 40 energy.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria PASSES: chi.max[5.00] - chi.current[0.00] >= 3 & ( energy.time_to_max[0.00] < 1 | energy.time_to_max[0.00] < 4 & cooldown.fists_of_fury.remains[0.00] < 1.5 | cooldown.weapons_of_order.remains[120.00] < 2 )
        Action chosen:  fist_of_the_white_tiger at 0.00!
    
    Completed default action list [ Windwalker - default ].
    Recommendation is fist_of_the_white_tiger at 0.00 + 0.00.
    Recommendation #1 is fist_of_the_white_tiger at 0.00s (0.00s).
    Used 1.72ms of CPU on 1 prediction(s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.00, Casting: 0.00 ).

    Resources: chi[ 3.00 / 5.00 ], energy[ 60.00 / 100.00 ], mana[ 13795.00 / 13795.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Windwalker - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   potion ( precombat - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Windwalker-precombat-1:potion:0.02
        
        2.   variable ( precombat - 2 )
         - variable.xuen_on_use_trinket will check this script entry ( Windwalker:precombat:2 )
        0
        Time spent on this action:  0.03ms
        TimeData:Windwalker-precombat-2:variable:0.03:Post-TTR and Essential:0.01
        
        3.   chi_burst ( precombat - 3 ) - talent [ chi_burst ] missing
        Time spent on this action:  0.02ms
        TimeData:Windwalker-precombat-3:chi_burst:0.02
        
        4.   chi_wave ( precombat - 4 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.02ms
        TimeData:Windwalker-precombat-4:chi_wave:0.02
    
    Completed precombat action list [ Windwalker - precombat ].
    
    Processing default action list [ Windwalker - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        5.   touch_of_karma ( default - 1 )
        The action (touch_of_karma) is unusable at (0.00 + 1.00) because incoming damage not sufficient (20% / 3sec) to use.
        Time spent on this action:  0.05ms
        TimeData:Windwalker-default-1:touch_of_karma:0.05:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01
        
        6.   fortifying_brew ( default - 2 ) - PvP talent [ fortifying_brew ] missing
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-2:fortifying_brew:0.02
        
        7.   spear_hand_strike ( default - 3 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-3:spear_hand_strike:0.02
        
        8.   variable ( default - 4 )
         - variable.hold_xuen will check this script entry ( Windwalker:default:4 )
        cooldown.invoke_xuen_the_white_tiger.remains[0.00] > fight_remains[3600.00] | fight_remains[3600.00] < 120 & fight_remains[3600.00] > cooldown.serenity.remains[90.00] & cooldown.serenity.remains[90.00] > 10
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-4:variable:0.02:Post-TTR and Essential:0.01
        
        9.   potion ( default - 5 ) - ability disabled ( toggle )
        Time spent on this action:  0.01ms
        TimeData:Windwalker-default-5:potion:0.01
        
        10.  call_action_list ( default - 6 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - buff.serenity.up[false]
        
        11.  call_action_list ( default - 7 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - buff.weapons_of_order.up[false]
        
        12.  call_action_list ( default - 8 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - time[47.31] < 4 & chi.current[3.00] < 5 & ! pet.xuen_the_white_tiger.active[false]
        
        13.  fist_of_the_white_tiger ( default - 9 )
        The action is not ready ( 30.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-9:fist_of_the_white_tiger:0.02
        
        14.  expel_harm ( default - 10 )
        The action (expel_harm) is usable at (0.00 + 1.00) with cost of 15 energy.
         - the action is ready before the current recommendation (at +1.00 vs. +60.00).
         - this entry's criteria PASSES: chi.max[5.00] - chi.current[3.00] >= 1 & ( energy.time_to_max[2.47] < 1 | cooldown.serenity.remains[90.00] < 2 | energy.time_to_max[2.47] < 4 & cooldown.fists_of_fury.remains[0.00] < 1.5 | cooldown.weapons_of_order.remains[120.00] < 2 )
        Action chosen:  expel_harm at 1.00!
        Time spent on this action:  0.37ms
        TimeData:Windwalker-default-10:expel_harm:0.37:Post-TTR and Essential:0.04:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.06:Pre-Recheck:0.17:Post Recheck:0.00:Action Stored:0.06
        
        15.  call_action_list ( default - 12 )
        Criteria for cd_sef PASS at +0.00 - ! talent.serenity.enabled[false]
        Action list (cd_sef) was found.
        + cd_sef
        Current recommendation was expel_harm at +1.00s.
        
        16.  storm_earth_and_fire ( cd_sef - 8 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Windwalker-cd_sef-8:storm_earth_and_fire:0.03
        
        17.  storm_earth_and_fire ( cd_sef - 9 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.01ms
        TimeData:Windwalker-cd_sef-9:storm_earth_and_fire:0.01
        
        18.  storm_earth_and_fire ( cd_sef - 20 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.01ms
        TimeData:Windwalker-cd_sef-20:storm_earth_and_fire:0.01
        
        19.  ashvanes_razor_coral ( cd_sef - 21 ) - IsUsableItem
        Time spent on this action:  0.04ms
        TimeData:Windwalker-cd_sef-21:ashvanes_razor_coral:0.04
        
        20.  use_items ( cd_sef - 22 )
        There is no criteria for Use Items.
        + cd_sef, items
        Current recommendation was expel_harm at +1.00s.
        
        21.  heart_essence ( items - 1 ) - IsUsableItem
        Time spent on this action:  0.10ms
        TimeData:UseItems-items-1:heart_essence:0.10
        
        22.  writhing_segment_of_drestagath ( items - 2 ) - ability disabled ( toggle )
        Time spent on this action:  0.06ms
        TimeData:UseItems-items-2:writhing_segment_of_drestagath:0.06
        Returned from Use Items; current recommendation is expel_harm (+1.00).
        - items
        
        23.  touch_of_karma ( cd_sef - 23 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-23:touch_of_karma:0.02
        
        24.  blood_fury ( cd_sef - 24 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-24:blood_fury:0.02
        
        25.  berserking ( cd_sef - 25 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-25:berserking:0.02
        
        26.  fireblood ( cd_sef - 27 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-27:fireblood:0.02
        
        27.  ancestral_call ( cd_sef - 28 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-28:ancestral_call:0.02
        Returned from list (cd_sef), current recommendation is expel_harm (+1.00).
        - cd_sef
        
        28.  call_action_list ( default - 13 )
        Criteria for cd_serenity FAIL at +0.00 - talent.serenity.enabled[false]
        
        29.  call_action_list ( default - 14 )
        Criteria for st FAIL at +0.00 - active_enemies[5.00] < 3
        
        30.  call_action_list ( default - 15 )
        Criteria for aoe PASS at +0.00 - active_enemies[5.00] >= 3
        Action list (aoe) was found.
        + aoe
        Current recommendation was expel_harm at +1.00s.
        
        31.  energizing_elixir ( aoe - 2 ) - talent [ energizing_elixir ] missing
        Time spent on this action:  0.02ms
        TimeData:Windwalker-aoe-2:energizing_elixir:0.02
        Returned from list (aoe), current recommendation is expel_harm (+1.00).
        - aoe
    
    Completed default action list [ Windwalker - default ].
    Recommendation is expel_harm at 0.00 + 1.00.
    Recommendation #2 is expel_harm at 1.00s (1.00s).
    Used 4.32ms of CPU on 2 prediction(s).

RECOMMENDATION #3 ( Offset: 1.00, GCD: 1.00, Casting: 0.00 ).

    Resources: chi[ 4.00 / 5.00 ], energy[ 56.66 / 100.00 ], mana[ 13795.00 / 13795.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Windwalker - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   potion ( precombat - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Windwalker-precombat-1:potion:0.02
        
        2.   variable ( precombat - 2 )
         - variable.xuen_on_use_trinket will check this script entry ( Windwalker:precombat:2 )
        0
        Time spent on this action:  0.03ms
        TimeData:Windwalker-precombat-2:variable:0.03:Post-TTR and Essential:0.01
        
        3.   chi_burst ( precombat - 3 ) - talent [ chi_burst ] missing
        Time spent on this action:  0.02ms
        TimeData:Windwalker-precombat-3:chi_burst:0.02
        
        4.   chi_wave ( precombat - 4 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.02ms
        TimeData:Windwalker-precombat-4:chi_wave:0.02
    
    Completed precombat action list [ Windwalker - precombat ].
    
    Processing default action list [ Windwalker - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        5.   touch_of_karma ( default - 1 )
        The action (touch_of_karma) is unusable at (1.00 + 1.00) because incoming damage not sufficient (20% / 3sec) to use.
        Time spent on this action:  0.05ms
        TimeData:Windwalker-default-1:touch_of_karma:0.05:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01
        
        6.   fortifying_brew ( default - 2 ) - PvP talent [ fortifying_brew ] missing
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-2:fortifying_brew:0.02
        
        7.   spear_hand_strike ( default - 3 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-3:spear_hand_strike:0.02
        
        8.   variable ( default - 4 )
         - variable.hold_xuen will check this script entry ( Windwalker:default:4 )
        cooldown.invoke_xuen_the_white_tiger.remains[0.00] > fight_remains[3600.00] | fight_remains[3600.00] < 120 & fight_remains[3600.00] > cooldown.serenity.remains[90.00] & cooldown.serenity.remains[90.00] > 10
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-4:variable:0.02:Post-TTR and Essential:0.01
        
        9.   potion ( default - 5 ) - ability disabled ( toggle )
        Time spent on this action:  0.01ms
        TimeData:Windwalker-default-5:potion:0.01
        
        10.  call_action_list ( default - 6 )
        Time-sensitive Criteria FAIL at +1.00 with no valid rechecks - buff.serenity.up[false]
        
        11.  call_action_list ( default - 7 )
        Time-sensitive Criteria FAIL at +1.00 with no valid rechecks - buff.weapons_of_order.up[false]
        
        12.  call_action_list ( default - 8 )
        Time-sensitive Criteria FAIL at +1.00 with no valid rechecks - time[48.31] < 4 & chi.current[4.00] < 5 & ! pet.xuen_the_white_tiger.active[false]
        
        13.  fist_of_the_white_tiger ( default - 9 )
        The action is not ready ( 29.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Windwalker-default-9:fist_of_the_white_tiger:0.02
        
        14.  expel_harm ( default - 10 )
        The action (expel_harm) is usable at (1.00 + 15.00) with cost of 15 energy.
         - the action is ready before the current recommendation (at +15.00 vs. +60.00).
         - this entry's criteria PASSES: chi.max[5.00] - chi.current[4.00] >= 1 & ( energy.time_to_max[0.00] < 1 | cooldown.serenity.remains[90.00] < 2 | energy.time_to_max[0.00] < 4 & cooldown.fists_of_fury.remains[0.00] < 1.5 | cooldown.weapons_of_order.remains[120.00] < 2 )
        Action chosen:  expel_harm at 15.00!
        Time spent on this action:  0.29ms
        TimeData:Windwalker-default-10:expel_harm:0.29:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.01:Pre-Recheck:0.16:Post Recheck:0.00:Action Stored:0.05
        
        15.  tiger_palm ( default - 11 )
        The action (tiger_palm) is usable at (1.00 + 1.00) with cost of 50 energy.
         - the action is ready before the current recommendation (at +1.00 vs. +15.00).
         - this entry's criteria FAILS: combo_strike[true] & chi.max[5.00] - chi.current[4.00] >= 2 & ( energy.time_to_max[2.75] < 1 | cooldown.serenity.remains[90.00] < 2 | energy.time_to_max[2.75] < 4 & cooldown.fists_of_fury.remains[0.00] < 1.5 | cooldown.weapons_of_order.remains[120.00] < 2 )
        1.7634832174424 - true
        There are 1 recheck events.
        Recheck #1 ( +2.76 ) NOT MET: combo_strike[true] & chi.max[5.00] - chi.current[4.00] >= 2 & ( energy.time_to_max[0.99] < 1 | cooldown.serenity.remains[90.00] < 2 | energy.time_to_max[0.99] < 4 & cooldown.fists_of_fury.remains[0.00] < 1.5 | cooldown.weapons_of_order.remains[120.00] < 2 )
        Time spent on this action:  0.60ms
        TimeData:Windwalker-default-11:tiger_palm:0.60:Post-TTR and Essential:0.04:Post Cycle:0.01:Post Usable:0.02:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.01:Pre-Recheck:0.21:Post-Recheck Times:0.06:Pre-Recheck Loop:0.01:Recheck Loop Start:0.00:Recheck Post-Usable:0.01:Recheck Post-Stack:0.00:Recheck Post-Script:0.01:Recheck Post-Channel:0.00:Recheck Loop End:0.20:Post Recheck Loop:0.00:Post Recheck:0.00
        
        16.  call_action_list ( default - 12 )
        Criteria for cd_sef PASS at +1.00 - ! talent.serenity.enabled[false]
        Action list (cd_sef) was found.
        + cd_sef
        Current recommendation was expel_harm at +15.00s.
        
        17.  invoke_xuen ( cd_sef - 1 )
        The action (invoke_xuen) is usable at (1.00 + 1.00).
         - the action is ready before the current recommendation (at +1.00 vs. +15.00).
        List ( cd_sef ) called from ( Windwalker:default:12 ) would PASS at 1.00.
        ! talent.serenity.enabled[false]
         - this entry's criteria PASSES: ! variable.hold_xuen[false] | fight_remains[3600.00] < 25
        Action chosen:  invoke_xuen at 1.00!
        Time spent on this action:  0.18ms
        TimeData:Windwalker-cd_sef-1:invoke_xuen:0.18:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.01:Post Stack:0.02:Pre-Script:0.00:Post-Script:0.02:Pre-Recheck:0.04:Post Recheck:0.00:Action Stored:0.02
        
        18.  storm_earth_and_fire ( cd_sef - 8 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Windwalker-cd_sef-8:storm_earth_and_fire:0.03
        
        19.  storm_earth_and_fire ( cd_sef - 9 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.01ms
        TimeData:Windwalker-cd_sef-9:storm_earth_and_fire:0.01
        
        20.  storm_earth_and_fire ( cd_sef - 20 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.01ms
        TimeData:Windwalker-cd_sef-20:storm_earth_and_fire:0.01
        
        21.  ashvanes_razor_coral ( cd_sef - 21 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Windwalker-cd_sef-21:ashvanes_razor_coral:0.03
        
        22.  use_items ( cd_sef - 22 )
        There is no criteria for Use Items.
        + cd_sef, items
        Current recommendation was invoke_xuen at +1.00s.
        
        23.  heart_essence ( items - 1 ) - IsUsableItem
        Time spent on this action:  0.09ms
        TimeData:UseItems-items-1:heart_essence:0.09
        
        24.  writhing_segment_of_drestagath ( items - 2 ) - ability disabled ( toggle )
        Time spent on this action:  0.07ms
        TimeData:UseItems-items-2:writhing_segment_of_drestagath:0.07
        Returned from Use Items; current recommendation is invoke_xuen (+1.00).
        - items
        
        25.  touch_of_karma ( cd_sef - 23 )
        The action is not ready in time ( 1.00 vs. 1.00 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.03ms
        TimeData:Windwalker-cd_sef-23:touch_of_karma:0.03
        
        26.  blood_fury ( cd_sef - 24 ) - ability unknown
        Time spent on this action:  0.03ms
        TimeData:Windwalker-cd_sef-24:blood_fury:0.03
        
        27.  berserking ( cd_sef - 25 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-25:berserking:0.02
        
        28.  fireblood ( cd_sef - 27 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-27:fireblood:0.02
        
        29.  ancestral_call ( cd_sef - 28 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Windwalker-cd_sef-28:ancestral_call:0.02
        Returned from list (cd_sef), current recommendation is invoke_xuen (+1.00).
        - cd_sef
        
        30.  call_action_list ( default - 13 )
        Criteria for cd_serenity FAIL at +1.00 - talent.serenity.enabled[false]
        
        31.  call_action_list ( default - 14 )
        Criteria for st FAIL at +1.00 - active_enemies[5.00] < 3
        
        32.  call_action_list ( default - 15 )
        Criteria for aoe PASS at +1.00 - active_enemies[5.00] >= 3
        Action list (aoe) was found.
        + aoe
        Current recommendation was invoke_xuen at +1.00s.
        
        33.  energizing_elixir ( aoe - 2 ) - talent [ energizing_elixir ] missing
        Time spent on this action:  0.02ms
        TimeData:Windwalker-aoe-2:energizing_elixir:0.02
        Returned from list (aoe), current recommendation is invoke_xuen (+1.00).
        - aoe
    
    Completed default action list [ Windwalker - default ].
    Recommendation is invoke_xuen at 1.00 + 1.00.
    Recommendation #3 is invoke_xuen at 1.00s (2.00s).
    Time spent generating recommendations:  7.43ms

**Comment by Hekili** [comment]
Please use Pastebin for snapshots.

Touch of Karma requires some incoming damage to proc.  I can adjust it or make it an option, though.

Fortifying Brew was still flagged to require a PvP talent, which I will remove.
