### ISSUE TITLE
Fury Warrior and Condemn/Execute

### ISSUE THREAD

**Issue by Publikstomp** [Hekili/hekili#568]
Neither Condemn nor Execute is appearing in the rotation for a Fury Warrior

**Comment by Freazerr** [comment]
I am also having this issue

**Comment by Rogue1337** [comment]
Yeah same here, Condemn is not getting recommended at all

**Comment by Hekili** [comment]
Please follow the ticket instructions and include all the required information.  Thanks!

**Comment by Publikstomp** [comment]
build: v9.0.2-1.0.4
level: 60 (60)
class: WARRIOR
spec: fury

talents: cruelty
    double_time
    dragon_roar
    frenzy
    siegebreaker
    sudden_death
    warpaint

pvptalents: none

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    grove_wardens_breastplate = 1
    grove_wardens_greathelm = 1
    gubbins_polished_gauntlets = 1
    heart_of_azeroth = 1
    master_duelists_chit = 1
    night_courtiers_ring = 1
    reanimated_executioners_greatsword = 1
    seal_of_fordragon = 1
    splinterball_morningstar = 1
    stoneforged_girdle = 1
    stoneforged_legguards = 1
    stoneforged_sabatons = 1
    stoneforged_spaulders = 1
    stoneforged_vambraces = 1
    vial_of_caustic_liquid = 1

legendaries: none

itemIDs: 158075, 169223, 175424, 175430, 175435, 175438, 175443, 175484, 175647, 175649, 175710, 175722, 175730, 177652, 180669, 184165

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_ww_range = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Publikstomp** [comment]
Will resubmit
