### ISSUE TITLE
Sub Rogue black powder wrong icon

### ISSUE THREAD

**Issue by Zckyy** [Hekili/hekili#569]
Hi there,

The new black powder AoE spell for sub rogues have the wrong icon, its not a big deal, but might a confusing to new players as i spent atleast 10 minutes trying to figure out what ability the rotation was trying to tell me to press.

**To Reproduce**

- Go to a AoE mob pack of 3+ targets and be level 52+, with black powder unlocked.

**Expected behavior**
The correct icon to show up.

**Screenshots**

The current hekili rotation shows this icon:
https://i.imgur.com/r2rsDKG.png

However the actual icon for the spell is:
https://i.imgur.com/MrjuGuR.png

Here is the wowhead link for the spell ID: https://www.wowhead.com/spell=319175/black-powder

**Comment by Hekili** [comment]
Updated icon, will be in next release.
