### ISSUE TITLE
Please add a Dark Succor proc.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#57]
Hello. Is it possible, like DK, to do it in rotation in the right moments? At least the tracking of the prok and so that the rotation offers to push the Death Strike? And for one thing I would like to ask how Necrotic Strike and Raise Abomination work in your rotation. I saw you added support for PVP talents, but I don’t see them in the rotation. Is this so intended? or am i doing something wrong? Thank.

**Comment by Hekili** [comment]
Dark Succor should be detected unless the spellID is wrong.

Army of the Dead and Raise Abomination auto-swap.

I don't put PvP talents in; I support them when asked but you'd have to prioritize them yourself (since there're no tools to determine optimal usage of PvP talents).

**Comment by geraint425** [comment]
I just thought that when tracking the proc, the addon should show the death punch in rotation and it doesn’t show. Ok I will see what the problem is. And about the PVP talents, how can we let the rotation be done for them? or where can I look to do? Thanks for the help.

**Comment by Hekili** [comment]
Priority section of /hekili.
