### ISSUE TITLE
Condemn not recommended in the Fury Warrior Rotation

### ISSUE THREAD

**Issue by Rogue1337** [Hekili/hekili#570]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**
The addon ist not recommending Condemn in the rotation when choosing the Venthyr Covenant.

**Expected behavior**
The addon recommending Condemn in the rotation.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:
*
build: v9.0.2-1.0.4
level: 60 (60)
class: WARRIOR
spec: fury

talents: anger_management
    bladestorm
    cruelty
    massacre
    storm_bolt
    sudden_death
    warpaint

pvptalents: battle_trance
   enduring_rage
   slaughterhouse

covenant: venthyr

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: arachnid_cipher_ring = 1
    ashjrakamas_shroud_of_resolve = 1
    ashscored_girdle = 1
    breastplate_of_otherworldly_influence = 1
    chain_of_the_purposebound = 1
    cinderwall_great_mace = 1
    common_gray_shirt = 1
    dread_sentinels_ebony_grips = 1
    leafed_banewood_band = 1
    sacred_grove_sabatons = 1
    sapsteel_legplates = 1
    sinfall_legion_smasher = 1
    spare_meat_hook = 1
    stolen_maw_badge = 1
    stoneforged_spaulders = 1
    stoneforged_vambraces = 1
    uldum_accord_tabard = 1
    wrathbark_greathelm = 1

legendaries: none

itemIDs: 169223, 174648, 175435, 175443, 175731, 177635, 178694, 178751, 178814, 178933, 179988, 180910, 181216, 181414, 181708, 184515, 184757, 3428

settings: aoe = 2
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_ww_range = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false
*

**Comment by Hekili** [comment]
The snapshot was the key part that's missing.

**Comment by Rogue1337** [comment]
Thats the snapshot from above 80% HP where it should recommend Condemn, do you need one with under 35%/20% too?

https://pastebin.com/mJMkKBwp

**Comment by alexmr06** [comment]
Good evening everyone, in fact the trick is to play with the talent "massacre". So it replaces the execution ^^. But in any case the technique is not displayed. Even having pasted our own Simc. (60).  Thanks for all the work done so far :).

**Comment by Publikstomp** [comment]
> Good evening everyone, in fact the trick is to play with the talent "massacre". So it replaces the execution ^^. But in any case the technique is not displayed. Even having pasted our own Simc. (60). Thanks for all the work done so far :).

Tried that and still not getting the recommendation

**Comment by Hekili** [comment]
The next release will include Covenant abilities that were missing.

**Comment by alexmr06** [comment]
Nice :). Ty.
