### ISSUE TITLE
Kill command for Survival.

### ISSUE THREAD

**Issue by Bustaclompa** [Hekili/hekili#572]
It only recommends Kill Command, outside of Kill shot and Death Chakram.

build: v9.0.2-1.0.4
level: 55 (55)
class: HUNTER
spec: survival

talents: birds_of_prey
    bloodseeker
    born_to_be_wild
    guerrilla_tactics
    mongoose_bite
    natural_mending
    vipers_venom

pvptalents: none

covenant: necrolord

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: argent_conscripts_folded_boots = 1
    ashjrakamas_shroud_of_resolve = 1
    chainlink_belt_of_ill_omens = 1
    ebony_scaled_gauntlets = 1
    flesh_architects_leggings = 1
    heart_of_azeroth = 1
    lurking_schemers_band = 1
    nightmarish_chain_shackles = 1
    plaguebringers_halberd = 1
    ring_of_collective_consciousness = 1
    steelscale_helm = 1
    tabard_of_the_honorbound = 1
    vial_of_caustic_liquid = 1
    voidtwisted_titanshard = 1
    waylight_chainmail = 1
    waylight_shoulderguards = 1

legendaries: none

itemIDs: 158075, 160545, 165613, 169223, 173319, 173339, 174153, 174154, 174156, 174528, 174530, 175008, 175464, 175722, 176775, 183587

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Survival
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    ca_vop_overlap = false
    use_harpoon = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = dual
    potions = false

**Comment by Bustaclompa** [comment]
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.4
level: 55 (55)
class: HUNTER
spec: survival

talents: birds_of_prey
    bloodseeker
    born_to_be_wild
    guerrilla_tactics
    mongoose_bite
    natural_mending
    vipers_venom

pvptalents: none

covenant: necrolord

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: argent_conscripts_folded_boots = 1
    ashjrakamas_shroud_of_resolve = 1
    chainlink_belt_of_ill_omens = 1
    ebony_scaled_gauntlets = 1
    flesh_architects_leggings = 1
    heart_of_azeroth = 1
    lurking_schemers_band = 1
    nightmarish_chain_shackles = 1
    plaguebringers_halberd = 1
    ring_of_collective_consciousness = 1
    steelscale_helm = 1
    tabard_of_the_honorbound = 1
    vial_of_caustic_liquid = 1
    voidtwisted_titanshard = 1
    waylight_chainmail = 1
    waylight_shoulderguards = 1

legendaries: none

itemIDs: 158075, 160545, 165613, 169223, 173319, 173339, 174153, 174154, 174156, 174528, 174530, 175008, 175464, 175722, 176775, 183587

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Survival
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    ca_vop_overlap = false
    use_harpoon = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = dual
    potions = false

New Recommendations for [ Primary ] requested at 11:38:57 ( 1043251.49 ); using built-in ( Survival ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: focus[ 100.00 / 100.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Survival - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   summon_pet ( precombat - 1 )
        The action (summon_pet) is unusable at (0.00 + 0.00) because not recommended while mounted.
        Time spent on this action:  0.07ms
        TimeData:Survival-precombat-1:summon_pet:0.07:Post-TTR and Essential:0.04:Post Cycle:0.00:Post Usable:0.01
        
        2.   azsharas_font_of_power ( precombat - 2 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Survival-precombat-2:azsharas_font_of_power:0.03
        
        3.   worldvein_resonance ( precombat - 3 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-precombat-3:worldvein_resonance:0.02
        
        4.   tar_trap ( precombat - 4 )
        The action (tar_trap) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria FAILS: runeforge.soulforge_embers.enabled[false] | runeforge.nessingwarys_trapping_apparatus.enabled[false]
        There were no recheck events to check.
        Time spent on this action:  0.12ms
        TimeData:Survival-precombat-4:tar_trap:0.12:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.03:Post-Recheck Times:0.00:Post Recheck:0.01
        
        5.   bestial_wrath ( precombat - 5 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-precombat-5:bestial_wrath:0.02
        
        6.   guardian_of_azeroth ( precombat - 6 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-precombat-6:guardian_of_azeroth:0.02
        
        7.   memory_of_lucid_dreams ( precombat - 7 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-precombat-7:memory_of_lucid_dreams:0.02
        
        8.   cyclotronic_blast ( precombat - 8 ) - item [ 167672 ] missing
        Time spent on this action:  0.02ms
        TimeData:Survival-precombat-8:cyclotronic_blast:0.02
        
        9.   focused_azerite_beam ( precombat - 9 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-precombat-9:focused_azerite_beam:0.02
        
        10.  aspect_of_the_wild ( precombat - 10 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-precombat-10:aspect_of_the_wild:0.02
        
        11.  bestial_wrath ( precombat - 11 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-precombat-11:bestial_wrath:0.01
    
    Completed precombat action list [ Survival - precombat ].
    
    Processing default action list [ Survival - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        12.  counter_shot ( default - 1 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-default-1:counter_shot:0.02
        
        13.  counter_shot ( default - 2 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-default-2:counter_shot:0.01
        
        14.  use_items ( default - 3 )
        There is no criteria for Use Items.
        + items
        Current recommendation was NO ACTION at +60.00s.
        
        15.  heart_essence ( items - 1 ) - IsUsableItem
        Time spent on this action:  0.09ms
        TimeData:UseItems-items-1:heart_essence:0.09
        Returned from Use Items; current recommendation is NO ACTION (+60.00).
        - items
        
        16.  tranquilizing_shot ( default - 4 )
        The action (tranquilizing_shot) is unusable at (0.00 + 0.00) because requires dispellable_enrage or dispellable_magic.
        Time spent on this action:  0.08ms
        TimeData:Survival-default-4:tranquilizing_shot:0.08:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.04
        
        17.  use_items ( default - 5 )
        Criteria for ??? FAIL at +0.00 - prev_gcd.1.aspect_of_the_wild[false] | fight_remains[3600.00] < 20
        
        18.  azsharas_font_of_power ( default - 6 ) - IsUsableItem
        Time spent on this action:  0.01ms
        TimeData:Survival-default-6:azsharas_font_of_power:0.01
        
        19.  ashvanes_razor_coral ( default - 7 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Survival-default-7:ashvanes_razor_coral:0.03
        
        20.  cyclotronic_blast ( default - 8 ) - item [ 167672 ] missing
        Time spent on this action:  0.01ms
        TimeData:Survival-default-8:cyclotronic_blast:0.01
        
        21.  call_action_list ( default - 9 )
        There is no criteria for cds.
        Action list (cds) was found.
        + cds
        Current recommendation was NO ACTION at +60.00s.
        
        22.  ancestral_call ( cds - 1 )
        The action (ancestral_call) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cds ) called from ( Survival:default:9 ) would PASS at 0.00.
        NONE
         - this entry's criteria FAILS: cooldown.bestial_wrath.remains[0.00] > 30
        There were no recheck events to check.
        Time spent on this action:  0.11ms
        TimeData:Survival-cds-1:ancestral_call:0.11:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.02:Pre-Recheck:0.02:Post-Recheck Times:0.00:Post Recheck:0.00
        
        23.  fireblood ( cds - 2 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-cds-2:fireblood:0.02
        
        24.  berserking ( cds - 3 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-cds-3:berserking:0.02
        
        25.  blood_fury ( cds - 4 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-cds-4:blood_fury:0.02
        
        26.  lights_judgment ( cds - 5 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-cds-5:lights_judgment:0.02
        
        27.  potion ( cds - 6 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Survival-cds-6:potion:0.02
        
        28.  worldvein_resonance ( cds - 7 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-cds-7:worldvein_resonance:0.01
        
        29.  guardian_of_azeroth ( cds - 8 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-cds-8:guardian_of_azeroth:0.01
        
        30.  ripple_in_space ( cds - 9 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-cds-9:ripple_in_space:0.02
        
        31.  memory_of_lucid_dreams ( cds - 10 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-cds-10:memory_of_lucid_dreams:0.01
        
        32.  reaping_flames ( cds - 11 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-cds-11:reaping_flames:0.02
        Returned from list (cds), current recommendation is NO ACTION (+60.00).
        - cds
        
        33.  call_action_list ( default - 10 )
        Criteria for st PASS at +0.00 - active_enemies[1.00] < 2
        Action list (st) was found.
        + st
        Current recommendation was NO ACTION at +60.00s.
        
        34.  aspect_of_the_wild ( st - 1 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-st-1:aspect_of_the_wild:0.01
        
        35.  barbed_shot ( st - 2 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-st-2:barbed_shot:0.02
        
        36.  tar_trap ( st - 3 )
        The action (tar_trap) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( st ) called from ( Survival:default:10 ) would PASS at 0.00.
        active_enemies[1.00] < 2
         - this entry's criteria FAILS: runeforge.soulforge_embers.enabled[false] & tar_trap.remains[0.00] < gcd.execute[1.23] & cooldown.flare.remains[0.00] < gcd.execute[1.23]
        There were no recheck events to check.
        Time spent on this action:  0.17ms
        TimeData:Survival-st-3:tar_trap:0.17:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.02:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.08:Post-Recheck Times:0.02:Post Recheck:0.00
        
        37.  flare ( st - 4 )
        The action (flare) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( st ) called from ( Survival:default:10 ) would PASS at 0.00.
        active_enemies[1.00] < 2
         - this entry's criteria FAILS: tar_trap.up[false] & runeforge.soulforge_embers.enabled[false]
        There were no recheck events to check.
        Time spent on this action:  0.09ms
        TimeData:Survival-st-4:flare:0.09:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.02:Post-Recheck Times:0.00:Post Recheck:0.00
        
        38.  bloodshed ( st - 5 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-st-5:bloodshed:0.02
        
        39.  wild_spirits ( st - 6 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-st-6:wild_spirits:0.02
        
        40.  flayed_shot ( st - 7 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-st-7:flayed_shot:0.02
        
        41.  kill_shot ( st - 8 )
        The action (kill_shot) is unusable at (0.00 + 0.00) because requires target health below 20 percent.
        Time spent on this action:  0.10ms
        TimeData:Survival-st-8:kill_shot:0.10:Post-TTR and Essential:0.05:Post Cycle:0.00:Post Usable:0.03
        
        42.  barbed_shot ( st - 9 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-st-9:barbed_shot:0.01
        
        43.  death_chakram ( st - 10 )
        The action (death_chakram) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( st ) called from ( Survival:default:10 ) would PASS at 0.00.
        active_enemies[1.00] < 2
         - this entry's criteria FAILS: focus.current[100.00] + cast_regen[7.50] < focus.max[100.00]
        There were no recheck events to check.
        Time spent on this action:  0.14ms
        TimeData:Survival-st-10:death_chakram:0.14:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.02:Pre-Recheck:0.04:Post-Recheck Times:0.00:Post Recheck:0.00
        
        44.  stampede ( st - 11 ) - talent [ stampede ] missing
        Time spent on this action:  0.02ms
        TimeData:Survival-st-11:stampede:0.02
        
        45.  concentrated_flame ( st - 12 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-st-12:concentrated_flame:0.02
        
        46.  a_murder_of_crows ( st - 13 ) - talent [ a_murder_of_crows ] missing
        Time spent on this action:  0.06ms
        TimeData:Survival-st-13:a_murder_of_crows:0.06
        
        47.  resonating_arrow ( st - 14 ) - ability unknown
        Time spent on this action:  0.03ms
        TimeData:Survival-st-14:resonating_arrow:0.03
        
        48.  bestial_wrath ( st - 15 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-st-15:bestial_wrath:0.02
        
        49.  chimaera_shot ( st - 16 ) - talent [ chimaera_shot ] missing
        Time spent on this action:  0.02ms
        TimeData:Survival-st-16:chimaera_shot:0.02
        
        50.  focused_azerite_beam ( st - 17 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-st-17:focused_azerite_beam:0.01
        
        51.  the_unbound_force ( st - 18 ) - ability unknown
        Time spent on this action:  0.04ms
        TimeData:Survival-st-18:the_unbound_force:0.04
        
        52.  resonating_arrow ( st - 19 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-st-19:resonating_arrow:0.01
        
        53.  bestial_wrath ( st - 20 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Survival-st-20:bestial_wrath:0.01
        
        54.  chimaera_shot ( st - 21 ) - talent [ chimaera_shot ] missing
        Time spent on this action:  0.01ms
        TimeData:Survival-st-21:chimaera_shot:0.01
        
        55.  blood_of_the_enemy ( st - 22 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Survival-st-22:blood_of_the_enemy:0.02
        
        56.  kill_command ( st - 23 )
        The action (kill_command) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( st ) called from ( Survival:default:10 ) would PASS at 0.00.
        active_enemies[1.00] < 2
         - this entry has no criteria to test.
        Action chosen:  kill_command at 0.00!
        Returned from list (st), current recommendation is kill_command (+0.00).
        - st
        The recommended action (kill_command) is ready in less than 0.2s; exiting list (default).
    
    Completed default action list [ Survival - default ].
    Recommendation is kill_command at 0.00 + 0.00.
    Recommendation #1 is kill_command at 0.00s (0.00s).
    Time spent generating recommendations:  2.85ms

**Comment by Hekili** [comment]
Thanks for the ticket and info.  The Beast Mastery priority was imported for Survival by mistake.  This will be fixed in the next build.
