### ISSUE TITLE
UI placement shifted unexpectedly to defaults after v9.0.2-1.0.4

### ISSUE THREAD

**Issue by sumosizeit** [Hekili/hekili#573]
**Describe the Bug/Issue**
I logged out, updated to v9.0.2-1.0.4, logged back in, and found the placement of Hekili to be moved from where I left it. I noticed the PR said : _Default display position didn't center the Primary display... Oops._

The problem is, this seems to have moved the UI for anyone who had already configured the placement of their UI, back to default.

**To Reproduce**
This is likely an upgrade error from versions prior to this change. Customize the placement using a version not containing this PR, then upgrade and compare placement.

**Expected behavior**
UI placement does not reset between addon version updates

**Screenshots**
https://imgur.com/a/H1Vwkpc

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/RLJmNHhp

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
N/A

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

N/A

**Comment by sumosizeit** [comment]
This is mitigable with some tweaking of the X placement of each unit, and is a pretty minor issue, but still kind of jarring nonetheless.

**Comment by Hekili** [comment]
Yup.  Just move it once and it'll stay.  If not, let me know.
