### ISSUE TITLE
Subtelty rogue seeing Black Arrow on ability rotation how to fix?

### ISSUE THREAD

**Issue by zeylin17** [Hekili/hekili#574]
When using Hekili, while playing my Subtlety Rogue, I get a Black Arrow Icon that pops up during rotation often.  It isn't always and I have yet to be able to determine when it decides to show it.  It feels like when there are multiple enemies it tends to show up more often.  How can I disable that ability recommendation or fix this?    I am guessing it may have black powder and black arrow confused?
![Screenshot (1692)](https://user-images.githubusercontent.com/75004040/100185289-7ad80a80-2eb1-11eb-8d3f-eb6b597a45f8.png)

I hope this helps.  Take care and thank you for this addon!

**Comment by Hekili** [comment]
Yes, the texture will be fixed in the next release.
