### ISSUE TITLE
CDs not being suggested *Balance and Fire* and Empowered Bonds Ability not working properly *Mainly With Party Members*

### ISSUE THREAD

**Issue by Nystroza** [Hekili/hekili#575]
**Describe the Bug/Issue**
I have cooldowns toggled on but Combustion and Celestial Alignment are not being recommended and the overall rotation seems to be incorrect until I use the cooldown.  for fire it's suggesting I only cast fireball.

Empowered bonds is also trying to get me to cast Kindred Spirits on myself in combat and only recommends Lone Empowerment and never Empowered Bonds when I have bonded with a party member the Kindred Spirits Icon shows up and then it's suggesting I get back into boomkin form after I Bond with myself right afterwards

**Expected behavior**

**Screenshots**
https://prnt.sc/vptj9j this is what it shows during combat even if I have bonded with a party member. (Boomkin)
https://prnt.sc/vptt1x it's only suggesting fireball every cast (Fire Mage)

**Issue Reporting**
https://pastebin.com/wY15A1FA (Boomkin)
https://pastebin.com/X81ufFjk (Firemage)

**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/M2i2rKiA (Boomkin)
https://pastebin.com/9hjDf7nk (Fire Mage)

**Comment by Hekili** [comment]
One ticket per spec, please.

**Comment by Hekili** [comment]
I think I have these sorted and queued up for the next release (1.0.6).  Submit individual tickets for each spec if you find issues in 1.0.6.
