### ISSUE TITLE
[Druid, All Specs] Kindred Spirits (Kyrian) being recommended when applied to another player.

### ISSUE THREAD

**Issue by Trilkin** [Hekili/hekili#576]
Title is issue. Pastebin includes snapshot for all three specs; just Ctrl+F *** GUARDIAN ***, *** FERAL ***, or *** BALANCE ***. Screenshot is just to show exactly what I'm seeing. It's the same for all three specs: Kindred Spirits > Shapeshift > First Real Rec.

https://pastebin.com/w5JcPcYV
https://i.imgur.com/Ri9m1Bh.jpg (rip anybody with eyes i'll do this more elegantly next time)

**Comment by Trilkin** [comment]
As requested in Discord:

Buff Spell ID when bonded to other player is 326967. This does not change with spec, thankfully.
Buff Spell ID when bonded to myself is 338041.
ID for the spell itself on my bar is 326434.

**Comment by Nystroza** [comment]
Having this same issue on v9.0.2-1.0.6

**Comment by Hekili** [comment]
All those spell IDs match what I have at the moment.  Still investigating.

**Comment by Hekili** [comment]
I believe we determined that this is solved.
