### ISSUE TITLE
fire mage

### ISSUE THREAD

**Issue by naofabo** [Hekili/hekili#578]
when playing fire mage, it's only suggesting to cast scorch. all the time.

**Comment by MarcoStudi** [comment]
I also encountered this bug. For me it only occured with Cooldowns Off, so that's a workaround until it's fixed, just play with Cooldowns.

**Comment by naofabo** [comment]
> I also encountered this bug. For me it only occured with Cooldowns Off, so that's a workaround until it's fixed, just play with Cooldowns.

ye exactly. I just forgot to mention it. I think it has something to do with the simulation string. I tried to install an older version but it didn't change anything. The string was updated yesterday, since then I have this bug.

**Comment by Hekili** [comment]
Please fill out a complete ticket with all the requested info.

**Comment by Hekili** [comment]
I'm putting in a workaround for this in 1.0.8; however, part of the workaround is that Shifting Power was moved from the Covenants toggle to the Cooldowns toggle (because it relies on having accurate CD values for Combustion, etc.).
