### ISSUE TITLE
WW Monk Touch of Karma & Fortifying Brew still not being recommended

### ISSUE THREAD

**Issue by vicwac** [Hekili/hekili#580]
After my previous ticket, there was a fix in the form of a health % slider for Touch of Karma to be recommended, but that is not happening, and Fortifying Brew is also not showing up (apparently the snapshot says ability unknown).

I have tried putting both under Defensives, creating a Defensives action list and a call action list function under the Default tab first with active_enemies >=1 and again with health.percent <=60, but nothing happened.

Snapshot: https://pastebin.com/AY0ZCFpr

I also removed the Defensives toggle, put both under default, but still not getting recommended.

Snapshot: https://pastebin.com/psbfqFM5

Both snapshots were taken when below 40% health, I set the Touch of Karma slider to 51.9% . Previously before I raised this issue, Touch of Karma would automatically pop at around 80% HP but even that is not happening now.

Please let me know if you need more info, it's very frustrating that I'm not able to get this to work, thanks.

EDIT: Spear Hand Strike (Monk interrupt) is in the same list and with Interrupts toggled it gets recommended:
![Hekili](https://user-images.githubusercontent.com/74341592/100356509-4a69ab00-302e-11eb-86e6-58c3fa64280a.JPG)

Also the icon for Fortifying Brew in Hekili is blue in color, whereas the one in my spellbook is yellow:
![Capture](https://user-images.githubusercontent.com/74341592/100356856-c5cb5c80-302e-11eb-992c-9d610b754609.JPG)
![InkedCapture_LI](https://user-images.githubusercontent.com/74341592/100357314-7c2f4180-302f-11eb-8a5f-1ca4e85e3c60.jpg)

**Comment by Hekili** [comment]
The slider is not your health percentage.  The slider is how much incoming damage you've taken in proportion to your health.

**Comment by vicwac** [comment]
> The slider is not your health percentage. The slider is how much incoming damage you've taken in proportion to your health.

Ok I tried that out, but I don't know really how to use that slider, when I set it to 10 it would recommend around 60% HP, and when I set it to 8 it would trigger at around 90% HP, so I'm not sure what the unit of measurement is. Perhaps you could just allow users to set it to based on their health.percent? If you're too busy to fix it now that's fine, I'll just leave the slider at 10 and it will trigger at 60% HP. Also look forward to a fix on Fortifying Brew, thanks in advance.

**Comment by Hekili** [comment]
The slider doesn't care about your health percentage at all.  It's incoming damage in proportion to your health.

If you set it to 10%, that means Touch of Karma can be used when you've taken 10% of your maximum health in damage in the past 3 seconds.  I've reset the number to be smaller (1%) so that you don't ToK when you're taking no damage.

If you want to use it as a defensive, based on health percentage, that's something to be done in a custom priority.

**Comment by vicwac** [comment]
Ok noted, what about Fortifying brew not being recommended?

**Comment by Hekili** [comment]
Can you see the spell ID for Fortifying Brew?  If so, what is it for WW?

**Comment by vicwac** [comment]
It's there above in the screenshot I sent, spell ID 243435

**Comment by Hekili** [comment]
I'll update the spell ID in the addon, and then it should be fine.

**Comment by Hekili** [comment]
(If you don't want to wait, you can change line 927 in MonkWindwalker.lua to `id = 243435,` and try it out.)

**Comment by vicwac** [comment]
Ahh ok great I'll just do it myself, I know you're busy, thanks man

**Comment by vicwac** [comment]
Happy to report that Fortifying Brew is working as intended now, but I see you've already updated the addon, thanks!
