### ISSUE TITLE
Game freezes and runs pretty bad whenever you start a boss fight.

### ISSUE THREAD

**Issue by Vaniolock** [Hekili/hekili#581]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**build: v9.0.2-1.0.7
level: 60 (60)
class: WARLOCK
spec: affliction

talents: dark_caller
    dark_soul_misery
    demon_skin
    drain_soul
    mortal_coil
    shadow_embrace
    vile_taint
    writhe_in_agony

pvptalents: none

covenant: night_fae

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: abominable_visage = 1
    drape_of_twisted_loyalties = 1
    fallen_empresss_cord = 1
    inscrutable_quantum_device = 1
    marquiss_lace_cuffs = 1
    muehzalas_hexthread_sarong = 1
    plaguelicked_amice = 1
    ring_of_perpetual_conflict = 1
    ritual_bone_band = 1
    sin_stained_pendant = 1
    sinister_requiem_vestments = 1
    slippers_of_leavened_station = 1
    stolen_maw_badge = 1
    stonefiend_shapers_mitts = 1
    surgical_pustule_extractor = 1
    vessel_of_shining_radiance = 1

legendaries: none

itemIDs: 175731, 178732, 178753, 178803, 178804, 178827, 178831, 178833, 178852, 178870, 178872, 179350, 179351, 179989, 180098, 180123

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Affliction
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
Hello there. I have noticed during dungeon runs and even world quests whenever starting a boss encounter the game freezes during all the fight like hell. The thing is that fps  is not dropping but it feels like you are playing at 15fps, the problem is fixed asap when u pause the addon. Please check that because I am really used to the addon!

**Comment by Hekili** [comment]
There's not really any data in this ticket that I can use to investigate or pursue anything.

A snapshot might clarify some details.

BugSack or BugGrabber information might catch some kind of error message.
