### ISSUE TITLE
"if not t.boss then return 3600 end"

### ISSUE THREAD

**Issue by brucek2** [Hekili/hekili#582]
Referring to the mob/fight time remaining functions in State.lua (time_to_die, fight_remains, etc.), around line 1700.

The code includes the quoted condition which appears to defeat ttl timers for trash mobs, etc, which means rules that prevent the use of DOTs on mobs that could be killed with a single direct spell don't work (as well as rules designed to preserve cooldowns.)

Would it be possible to return a better estimate than 3600 for these mobs? Personally I've been playing with these lines commented out, and find it an improvement, but I realize I can't account for every spec / every situation.

**Comment by Hekili** [comment]
These are intentionally designed to avoid triggering conditions that are aimed at burning CDs as a fight ends, unless you're actually in a boss encounter.

You can provide snapshots of this as a problem if you'd like me to explore it further.

**Comment by brucek2** [comment]
I see. Thank you for explaining.

Assuming that will be an ongoing necessary safeguard for best out-of-box experience with default SimC APLs, maybe I should reframe this as a feature request for non-safeguarded versions that custom APLs could opt into using? i.e., maybe something like time_to_die_actual? That way players could choose to use it when desired, while still having the protection you're talking about in unmodified conditions?

**Comment by ShmooDude** [comment]
Just use `target.time_to_die`, that should be what you're looking for.
