### ISSUE TITLE
Guardian Rotation isn´t working with night fae

### ISSUE THREAD

**Issue by MrHunter79** [Hekili/hekili#583]
Only showing this when in bear form:
![image](https://user-images.githubusercontent.com/75111071/100448670-f3f28000-30b2-11eb-81aa-dfc0409a9334.png)

Snapshot Link:

https://pastebin.com/165f2jx4
Issue Reporting:

build: v9.0.2-1.0.9
level: 60 (60)
class: DRUID
spec: guardian

talents: balance_affinity
    blood_frenzy
    earthwarden
    galactic_guardian
    mighty_bash
    rend_and_tear
    wild_charge

pvptalents: none

covenant: night_fae

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ashjrakamas_tuch_der_entschlossenheit = 1
    dmmerwrtersense = 1
    emblem_des_aufgestiegenen_verteidigers = 1
    herz_von_azeroth = 1
    hftgrtel_der_dunklen_hingabe = 1
    nachtverhllte_schuhe = 1
    ring_des_endlosen_konflikts = 1
    ritualknochenband = 1
    schattengebundene_armschtzer = 1
    schattengebundene_beinschtzer = 1
    schattengebundene_schulterstcke = 1
    schattengebundene_stulpen = 1
    schattengebundene_weste = 1
    schattengebundener_helm = 1
    unvergleichlicher_alchemistenstein = 1

legendaries: none

itemIDs: 158075, 169223, 171085, 172250, 172252, 172253, 172254, 172255, 172257, 175487, 175718, 178823, 178870, 178872, 179532

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Guardian
    petbased = false
    potion = focused_resolve
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    catweave_bear = false
    ironfur_damage_threshold = 5
    maul_rage = 20
    owlweave_bear = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by MrHunter79** [comment]
This is the acutal snapshot:
https://pastebin.com/165f2jx4

**Comment by Hekili** [comment]
That is intentional for Convoke, but I'll make it into an option.

**Comment by Hekili** [comment]
Discussed in Discord.
