### ISSUE TITLE
PROT Pala - Kyrianer unable to unable classutily 

### ISSUE THREAD

**Issue by chaosboy91** [Hekili/hekili#585]
hi,

ich try to deselect the Kyrianer ability from my rotation - there is an Checkbox -but nothin happen.
Its still in my rotation.

build: v9.0.2-1.0.9
level: 60 (60)
class: PALADIN
spec: protection

talents: blessed_hammer
    cavalier
    divine_purpose
    first_avenger
    fist_of_justice
    judgment_of_light
    sanctified_wrath

pvptalents: none

covenant: kyrian

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: berquellender_glutspiegel = 1
    brustplatte_der_tdlichen_vorrichtungen = 1
    ehrenzollhammer = 1
    eingeweide_des_verdichteten_hasses = 1
    grtung_des_seelenschinders = 1
    halkias_gewaltige_sulen = 1
    kette_der_vorsehungsgebundenen = 1
    listwindsteinkrallen = 1
    ring_des_endlosen_konflikts = 1
    schattenstahlarmschtzer = 1
    schattenstahlsabatons = 1
    schulterstcke_des_grausamen_scharfrichters = 1
    siegelring_des_blutschwurs = 1
    stahlgebundener_langschild = 1
    steingeschmiedete_kopfbedeckung = 1
    tuch_der_unergrndlichen_vorsehung = 1
    wappenrock_der_lichtgeschmiedeten = 1

legendaries: none

itemIDs: 157756, 171443, 171449, 175414, 175532, 177633, 177657, 178808, 178818, 178840, 178871, 178872, 179326, 179346, 181635, 184757, 184758

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Protection Paladin
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = false
    interrupts = true
    mode = dual
    potions = false

**Comment by Hekili** [comment]
/hekili > Abilities > Divine Toll, check Disabled.

And you probably want to undo whatever else you did.
