### ISSUE TITLE
Serrated Glaive Not Working

### ISSUE THREAD

**Issue by S4BRE21** [Hekili/hekili#586]
I am not getting prompted to throw glaive before eye beam.

https://pastebin.com/BVszRrzA

**Comment by Hekili** [comment]
Please follow the complete ticket instructions in the future.  I moved your snapshot to Pastebin.  I'll take a look.

**Comment by Hekili** [comment]
Can you post a screenshot that shows Serrated Glaive enabled and active?

**Comment by S4BRE21** [comment]
![Capture](https://user-images.githubusercontent.com/51067321/100481227-125b7a00-30b9-11eb-9166-c1aac0a0351b.JPG)
