### ISSUE TITLE
Shadow Priest pre-combat issue: Vampiric Touch -> Damnation?

### ISSUE THREAD

**Issue by fieldser** [Hekili/hekili#587]
Noticed an issue where Hekili is wanting me to open combat by casting Vampiric Touch first, followed by Damnation. Seems redundant since Damnation just applies Vampiric Touch already. I'm very new to Hekili and I've been unable to figure out how to modify my profile to fix this myself.

**Comment by fieldser** [comment]
I should also say I'm pretty new to Github and I see in the previous reported issue it was mentioned to follow complete ticket instructions. Trying to find those, but having trouble.

**Comment by fieldser** [comment]
OH it was located in the add-on... sorry. Here is a snapshot from pre-combat

https://pastebin.com/hv6wSKTV

**Comment by fieldser** [comment]
So I seemed to have resolved the problem by going to:
_Priorities -> Shadow -> Profile tab_ 
Then added a line for Damnation just before Vampiric Touch.

Though i'm guessing this may cause issues if I ever talent out of Damnation, not sure. But for now it's what I need.

```
# Shadow Priest
# November 23, 2020

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat+=/power_word_fortitude,if=remains<300
actions.precombat+=/shadowform,if=!buff.shadowform.up
actions.precombat+=/arcane_torrent,if=insanity.deficit>15
actions.precombat+=/use_item,name=azsharas_font_of_power
actions.precombat+=/variable,name=mind_sear_cutoff,op=set,value=2
actions.precombat+=/damnation
actions.precombat+=/vampiric touch
```

**Comment by Hekili** [comment]
This is one of those scenarios where you'd need to do your own sim testing, but both sims and guides presently agree -- use VT to open, even with Damnation.

![image](https://user-images.githubusercontent.com/9438134/100495393-6302bf80-3119-11eb-9a5e-7ffe78c697b1.png)

https://www.wowhead.com/shadow-priest-rotation-guide

If you do sim testing that demonstrates otherwise, that might lead to changes to the default profile.  But otherwise, you're always welcome to edit your own copy as you see fit.

**Comment by fieldser** [comment]
> This is one of those scenarios where you'd need to do your own sim testing, but both sims and guides presently agree -- use VT to open, even with Damnation.
> 
> ![image](https://user-images.githubusercontent.com/9438134/100495393-6302bf80-3119-11eb-9a5e-7ffe78c697b1.png)
> 
> https://www.wowhead.com/shadow-priest-rotation-guide
> 
> If you do sim testing that demonstrates otherwise, that might lead to changes to the default profile. But otherwise, you're always welcome to edit your own copy as you see fit.

Ahh, okay. I see and don't really understand, but it's hard to argue with sim testing so I'll accept it as is. Thank you for the response!
