### ISSUE TITLE
Not an Issue – Just a Note

### ISSUE THREAD

**Issue by tflo** [Hekili/hekili#59]
A mentioned before, I discovered your add-on only recently. But I’m more than pleasantly surprised: It seems to work better than Hero Rotation with all non-Rogue classes ; significantly better. And also with Rogue (which is the native domain of Hero Rotation) _I think_ that your add-on is giving me the better advices.

Chapeau!

Feel free to close this ticket once you’ve read it.

**Comment by Hekili** [comment]
Thanks for the nice comment.  :)
