### ISSUE TITLE
Can't move bar w/Elvui?

### ISSUE THREAD

**Issue by 69bossmustang** [Hekili/hekili#592]
Instructions say just go into config mode and you can move the bars. Only Elvui wont let you move the Hekili config window to get at the bars behind it.

MoveAnything wouldnt even move it.

Not a problem with your work, only inconsistent method of toggling lock bars. It would help if there was either a commandline or a config "toggle" option so the menu can be closed and still can move.

**Comment by Hekili** [comment]
I use my addon with ElvUI all the time. If you can't click the window (by the title) and drag it out of the way, you can set x/y positioning in each display's settings.

**Comment by 69bossmustang** [comment]
You are correct, it must have been a issue with me being on so long. Once I logged out/back in Elvui allowed me to move (they also had a update between that).

Thanks for your insight ;)
