### ISSUE TITLE
Is it possible to somehow get the ability to other windows?

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#593]
Hello. Faced a problem in rotation about my bursts. The problem lies in the fact that the rotation suggests using them always and everywhere, regardless of the battle. And I want to control this process. But in the addon, you can only delete them, or hide them. Is there a possibility, like the same herorotation, to make them be taken out in another window from the rotation, like they were implemented by OffCGD. Is it possible to do this? It just would be great, since I would have seen the rotation going on, and my burst was shown in another window, and thus I could control this process. Thanks in advance for your message.

**Comment by Hekili** [comment]
Not at this time.
