### ISSUE TITLE
Outlaw - Flagellation stacks not being consumed at end of debuff

### ISSUE THREAD

**Issue by whoaisjustin** [Hekili/hekili#594]
Add-on recommends flagellation at the beginning of combat, however it lets the debuff fall off without consuming the stacks for the haste buff.

https://pastebin.com/qeAN4X3y

**Comment by Hekili** [comment]
Will take a look.

**Comment by Hekili** [comment]
Should be addressed in next build, but I'd watch it closely -- the default priority puts stealth and CDs above Flagellation Cleanse and there's some risk that you'd miss the 2 second window.
