### ISSUE TITLE
BM Hunter Beastial Wrath Aura in Torghast

### ISSUE THREAD

**Issue by Bastyani** [Hekili/hekili#595]
There is an Anima Power in Torghast that activates your Bestial Wrath for 60 seconds when you enter new floor. Is it posible that Hekili checks if the aura is already up on you so it doesn't suggest it in the rotation. Right now it suggests it and it overwrites the 60 second one with 12 second one so you practically lose it if you follow the rotation.

**Comment by Hekili** [comment]
It depends. Do you have the spell ID of the Torghast version? If it is the same, then this is easy enough.

**Comment by Hekili** [comment]
I've added a toggle in your spec options that allows you to avoid this issue.

**Comment by Bastyani** [comment]
Wow that was fast! Thanks a lot!
