### ISSUE TITLE
MM hunter steady shot while moving

### ISSUE THREAD

**Issue by Triggersad** [Hekili/hekili#596]
This is similar to functionality you had with fire mages and scorch. The only caveat being with mm hunters is that it really should only suggest steady shot while aim shot is in the priority spot. As other skills can already be cast while moving. (Rapid fire,
 Arcane shot, etc). This functionality should be toggles on and off like the fire mage for those that have a preference.

**Comment by Hekili** [comment]
There's already an open ticket for this.
