### ISSUE TITLE
Support Torghast anima powers that alter the availability of abilities

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#598]
It would be nice if Hekili would support the temporary anima powers inside Torghast. Some of those alter the availability of abilities - so they could affect the next suggested ability.

For Paladin I've noticed those powers until now that could be supported:
https://www.wowhead.com/spell=332545/ring-of-unburdening
https://www.wowhead.com/spell=335069/negative-energy-token

**Comment by Hekili** [comment]
This is a "probably, eventually" kind of thing.  I may work on it piecemeal, so it's good to list them here.

**Comment by cremor** [comment]
I'm wondering why Negative Energy Token doesn't work by default. The normal bar buttons indicate when it procs (so the button changes from a "not usable grey" to its normal state). Isn't that something that Hekili reacts to? Or rather: Doesn't Hekili use the WoW functions to determine if an ability can be used?

**Comment by Hekili** [comment]
No, because for Hammer of Wrath, the reason it is usable is significant and can change.

For instance, if the addon recommends Avenging Wrath, you expect Hammer of Wrath to be available next.  But according to the WoW API, Avenging Wrath hasn't happened yet and HoW is unusable.  So it has to be manually modeled and configured.

If there's a buff present that makes HoW usable, I can add that to the model.

**Comment by Hekili** [comment]
I'm adding Negative Energy Token (id=345693) to the addon model.

**Comment by cremor** [comment]
Something is wrong with how you added that. It seems like it's now always (when I have the anima power) showing HoW as usable after I use Judgment, even if the anima power didn't proc.

But the buff id (345693) is correct.

**Comment by Hekili** [comment]
You'll have to submit proper testing information, because it works fine in my own testing.  And make sure it includes the version you're using.

**Comment by cremor** [comment]
Found the problem. Prot and Holy still use "negative_energy_token" instead of "negative_energy_token_proc" for the usable condition for HoW.

**Comment by Hekili** [comment]
Yeah, I just caught that as well.  I'll post that change later today or tomorrow morning.

**Comment by cremor** [comment]
Thanks. And sorry for the short messages, I'm in Torghast right now in a wing where mobs spawn when you are out of combat...

But could you please leave this issue open for other anima powers which might be suppored "probably, eventually"?

**Comment by Hekili** [comment]
No, I'd want the ones worth supporting to appear on a case-by-case basis.
