### ISSUE TITLE
Aff Lock UA being reccomended on multiple targets.

### ISSUE THREAD

**Issue by towicode** [Hekili/hekili#599]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

Unstable Affliction on AFF lock, is recommended even if it currently is on another target.

**To Reproduce**
Cast UA on target 1.
Switch target.
UA should be recommended after Haunt

**Expected behavior**
UA can only be applied to one target, so generally you don't want to cancel it on another target. There may be existing conditions in the APL for if a target is very low health but that should be it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8232247/100554057-7a43c900-324f-11eb-848f-27b4fdba829c.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

Here is my profile -> https://pastebin.com/Hd8wuctx

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.

Here is the snapshot -> https://pastebin.com/Hd8wuctx

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Resolved in beta.
