### ISSUE TITLE
Exclude Out-of-Range for Survival Hunters

### ISSUE THREAD

**Issue by howtnted** [Hekili/hekili#603]
Hello I get some weird recommendation for Survival Hunter while I am not in melee range (but in range to cast my attacks). I have Exclude Out-of-Range activated. But in this case I am in range, but the attacks [Kill Command] and [Serpent Sting] are "mistakenly?" excluded.

Thank you for your help!

https://pastebin.com/ngP52veU

**Comment by Hekili** [comment]
There's no information available to me via the API to do anything different with Survival range checking.
