### ISSUE TITLE
Can a range check be added to all DK abilities?

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#606]
Hello. While playing DK in 3 specializations, I noticed that abilities that work on AOE are like blood boil, unholy blight, frostscythe, remorseless winter, and so on. Please tell me, is it possible to make them be used when they can really reach the target? It would be great if they worked in a place with a range check of other abilities. This would remove accidental triggers when the target is far away. Thanks in advance for your reply.

**Comment by Hekili** [comment]
It depends.  I have Wake of Ashes configured with a setting for this.  For Frost DK, the entire priority might fall apart if Frostscythe were blocked.  (Keep in mind, the actual optimal recommendation when Frostscythe appears is to be in range or get in range and use Frostscythe.)  You have to think about whether you'd actually have a different button to push, if those actions were excluded.

**Comment by geraint425** [comment]
Well, if I understood you correctly. Then, in principle, it is realizable. It's just that with the same Frostscythe, it cannot be dropped from rotation. Because it, in principle, when it does not reach the goal, it is simply used, and does not spend anything, but in the vicinity, it is implemented normally. But the other abilities that I listed, they also work fine. But I would like me to use them when they could reach the goal. It's just that in battle it happens that you have to run away, and the tank brings other targets, but I don't understand if I can get it with these abilities or not. Because other abilities clearly show in red when I miss the target, and I just press these, in the hope that I seem to get it, but in fact not.

**Comment by Hekili** [comment]
You can use `target.withinX` as a condition (in addition to any existing conditions) in your custom priority to solve for this.
