### ISSUE TITLE
Prot Paladin suggests Guardian of Ancient Kings while it's on cooldown sometimes

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#607]
Screenshot paused on the recommendation showing the ability on cooldown on hotbars.

![WoWScrnShot_120120_142238](https://user-images.githubusercontent.com/2590271/100787388-8f506180-33e1-11eb-8166-a7f9838c812e.jpg)

Here's a paste of the snapshot

https://pastebin.com/Wkrhkzfp

**Comment by jmusick** [comment]
Updated screenshot.

**Comment by Hekili** [comment]
Can you see spell IDs in your UI?  What is the spell ID for your Guardian of Ancient Kings?

Do you have any gear or talents that modify GoAK?

**Comment by jmusick** [comment]
I don't see anything that modifies it. I installed a spellID addon to put the id in the tooltip and the GoAK shows ID# 212641

**Comment by jmusick** [comment]
Oh I have the Glyph of the Queen glyph on. Maybe that's why?

**Comment by Hekili** [comment]
Yeah, looks like it.

**Comment by Hekili** [comment]
I have a fix to detect the changed spell ID planned for the next release.
