### ISSUE TITLE
Doom winds breaks rotation

### ISSUE THREAD

**Issue by dmack94** [Hekili/hekili#609]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Yes, running the most recent version as per Wowup.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

Not that i've seen

**Describe the Bug/Issue**

Dooms winds legendary breaks the rotation when WF totem is placed.

**To Reproduce**

Drop a dooms wind totem and observe the next rotation suggestions

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/3v19suDn

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/bc2Pj8mU

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

No Error 
![Doom winds](https://user-images.githubusercontent.com/75344535/100814685-3d730000-3410-11eb-98fc-4db857797938.PNG)

**Comment by Hekili** [comment]
Update to 1.0.15.
