### ISSUE TITLE
Should Death Strike be showing up for Unholy DK?

### ISSUE THREAD

**Issue by parkerstan93** [Hekili/hekili#614]
I'm not getting Death Strike showing up for my DK no matter what toggles I choose. I did get it to work for a day when i had show defensives checked and show separately checked (but was still showing in the automatic window) , but then it stopped showing up again.

what can I do to have it show in my rotation again?

**Comment by Hekili** [comment]
https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#how-do-i-make-the-addon-recommend-________
