### ISSUE TITLE
Problem with ADK rotation

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#62]
Hello. I would like to talk to you about such things as Grongs trinket RAGE trinket (Mekkatorque). Your addon does not correctly use them in the rotation. Because as I looked they are used by more experienced people according to such tactics.

When should I use the Grongs trinket?
Pretty much off Cooldown. Use it in the opener after you've popped Unholy Frenzy (wounds will still be applied).

How do I use the RAGE trinket (Mekkatorque) correctly?
Use it in opener and use Unholy Frenzy as you usually do. Then save Unholy Frenzy for your other uses, popping Unholy Frenzy 6 seconds after using the trinket. 

And it turns out that these conditions Hekilli does not take into account. And it turns out in fact that I immediately give away at all two trinkets. Is it possible to implement them in addon so that he understands when to use them? I have not found where I can set these conditions as described above. And also when changing the race, hekilli does not show to use the racial abilities of another faction (Berserk, etc.)

**Comment by Hekili** [comment]
Unholy DK should talk to their simc devs about including this in the Unholy priority.

You can absolutely add/change this in your own priority if you want.
