### ISSUE TITLE
(Frost) DK death strike

### ISSUE THREAD

**Issue by Pendorax** [Hekili/hekili#620]
Would it be possible to add some kind of slider or other form of option to change the rotation based on health% to focus on death strike instead of frost strike?

**Comment by Hekili** [comment]
You can edit your own priority as you see fit -- it's just not necessarily *optimal*.

The closest thing I have in terms of instructions is here:  https://github.com/Hekili/hekili/wiki/Frequently-Asked-Questions#how-do-i-make-the-addon-recommend-________
