### ISSUE TITLE
Movement check for classes with hard cast spells/skills

### ISSUE THREAD

**Issue by vicwac** [Hekili/hekili#621]
As a modification has already been done to the MM Hunter rotation to recommend Aimed Shot only when stationery, it would be great if this can be extended to all other classes such as Balance Druid Wrath/Starfire, Fire Mage Pyroblast, Destro Lock Chaos Bolt, to name a few.

Currently I can set the movement check modification to stationery for all my recommended hard cast skills, but it gets overwritten with every Hekili update (at least that's what I think happens as I constantly have to redo the movement check settings).

I understand this is not optimal for dps but in real-world gameplay, very seldom do we get to execute optimal rotations due to boss mechanics, PVP, etc.

**Comment by Hekili** [comment]
Fire Mage already has settings.

Refer to the Wiki here about how to make a copy of a default priority so that your changes aren't overwritten.
