### ISSUE TITLE
Abilities: Elite Encounter (similar to Boss Encounter Only)

### ISSUE THREAD

**Issue by doktorstick** [Hekili/hekili#624]
The change would be to add a checkbox for "Elite Encounter" under the Abilities configuration for the per ability toggle. Often, I don't care about big cooldowns when out in the world, but there are rares, group world quests, and now, with sections of the Maw being rather tough, I would like these abilities to be available. I imagine it working not just with the mob you have targeted, but if there's an elite in combat with you. 

This would have the follow-on change that "Boss Encounter Only" would become "Boss Encounter", as you could have "Elite Encounter" and "Boss Encounter" simultaneously checked.

**Comment by Zarggg** [comment]
I'm definitely in favor of this use case, but would also like to add that currently I just toggle Cooldowns on for these encounters, then back off when I'm only fighting normal mobs.

**Comment by Hekili** [comment]
Yeah, CDs toggle is meant to address this, for the most part.  I'd encourage you to get used to toggling them on/off as needed.  It's very helpful for saving CDs for fight mechanics, too.

The biggest barrier to this feature is that WoW is reeeeeeally inconsistent with whether they flag specific enemies as elite or not.
