### ISSUE TITLE
stutterin during combat

### ISSUE THREAD

**Issue by Mhedo** [Hekili/hekili#626]
Hi all,

as soon as I start combat WoW starts to stutter on my Fire Mage. I checked all addons and it is definitely a problem caused by Hekili.

build: v9.0.2-1.0.15
level: 60 (60)
class: MAGE
spec: fire

talents: flame_on
    flame_patch
    frenetic_speed
    kindling
    rune_of_power
    searing_touch
    shimmer

pvptalents: none

covenant: night_fae

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: beinwickel_der_luterungsprotokolle = 1
    dunkelmondkartenset_fulnis = 1
    fustlinge_des_steinscheusalformers = 1
    gewnder_des_finsteren_requiems = 1
    hishtars_strenges_stilett = 1
    kit_jins_aufreizender_hftgurt = 1
    mantel_des_zchtigers = 1
    pfadspinneranhnger = 1
    schattengarngugel = 1
    schattengarnmanschetten = 1
    schattenschreckring = 1
    siegelring_des_falschen_anklgers = 1
    sonnenblutamethyst = 1
    tabernakel_von_nathria = 1
    tuch_der_verdrehten_treue = 1
    windschuppenmokassins = 1

legendaries: firestorm = 1

itemIDs: 173069, 173218, 173222, 178707, 178824, 178826, 178828, 178833, 178859, 178926, 179322, 180098, 180107, 180123, 184788, 184798

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    petbased = false
    potion = superior_battle_potion_of_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    pyroblast_pull = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

Br,
Mhedo

**Comment by Hekili** [comment]
Yep, Fire Mage requires a lot.  Show fewer icons or don't use it.
