### ISSUE TITLE
Legendary: Account for Deathmaker

### ISSUE THREAD

**Issue by nate8282** [Hekili/hekili#627]
The Deathmaker legendary gives Rampage a 30% chance of applying Siegebreaker for 6 seconds (Instead of the default 10). Currently, with this legendary equipped in fury spec, Siegebreaker is cast even if Siegebreaker was just applied by Rampage causing up to 4 seconds of Siegebreaker to be wasted. 

It would be nice if Siegebreaker would wait to be applied if it's already currently applied by the legendary.

**Comment by Hekili** [comment]
Have you simmed any APL changes to account for this?

**Comment by Hekili** [comment]
So far, in my own sim testing, holding Siegebreaker when it has already been applied by Rampage has been DPS neutral on average with a possibility of higher top-end damage when you're lucky.

**Comment by nate8282** [comment]
Thanks for checking.

**Comment by Hekili** [comment]
The edit is currently in beta and will be included in the next release.  Even though it's neutral.
