### ISSUE TITLE
Don't show GCD on abilities that are off the GCD

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#629]
Abilities that are always off the GCD like Shield of the Righteous from the Protection Paladin shouldn't show the GCD on the icon.

**Comment by Hekili** [comment]
This may be addressed in 1.0.23.

**Comment by cremor** [comment]
I've just tested 1.0.23. The main icon still shows the GCD for Shield of the Righteous. The queue icons behaves a bit weird. Most of the time it doesn't show the GCD, but sometimes it does. I couldn't figure out when.

I don't really care about the queue icon, but fixing it for the main icon would be great. So please re-open this issue.

Here is a snapshot. I took it during the GCD while Shield of the Righteous was on the main icon. https://pastebin.com/r2XM4CuH
And here the general issue information: https://pastebin.com/a1x2ukQk

**Comment by Hekili** [comment]
The spiral isn't always the GCD; it can also be the delay if you're waiting to use it (i.e., daisy-chaining or waiting to push right as the buff falls off).

**Comment by cremor** [comment]
Sure, but in my tests it was always shown when I used an ability. So I'm quite sure that it was the GCD.
Also, the bar button didn't show the spiral, only the icon of Hekili.

**Comment by Hekili** [comment]
The bar button would not show a spiral when the addon is delaying SotR to wait for the buff to wear off.  But I'll check it out.

**Comment by Hekili** [comment]
This appears to be resolved.

**Comment by cremor** [comment]
@Hekili I can **not** confirm that this is fixed in v9.0.5-1.0-beta1. To be more specific: It seems to be fixed for the queue icons, but not for the main icon.

Repro steps for a Prot Paladin:

1. Build 5 holy power so that Shield of the Righteous is shown on the main icon.
2. Use any ability.
3. The main icon will show the GCD spiral on Shield of the Righteous.

Please reopen.

**Comment by Hekili** [comment]
Provide a fresh snapshot of that, please.

**Comment by cremor** [comment]
Character data: https://pastebin.com/yjpy8tbS
Snapshot with 5 HP and everything off CD: https://pastebin.com/gNvYttP1
Snapshot with same conditions but during GCD (I hope I got it): https://pastebin.com/Ne3GEpJn

**Comment by Hekili** [comment]
You have your addon configured to sync with the GCD, so it does.

**Comment by cremor** [comment]
Oh, wow, sorry. I didn't even remember that that option exists. And I had to read its descripton 3 times now to understand what it actually does. I always thought that it only affects the recommendation itself, not the cooldown swirl on it.
Thanks!
