### ISSUE TITLE
account for movement

### ISSUE THREAD

**Issue by mspykerez** [Hekili/hekili#63]
Can you add an option to only suggest abilities that can be cast while moving when we move ?

**Comment by Hekili** [comment]
This is worth considering, but can degrade the quality of a priority list rather quickly.

**Comment by Hekili** [comment]
I'm closing this ticket because I'm not planning to implement this -- the solution to optimizing DPS when moving is to stop moving (for casters).  Responding to fight mechanics during movement is up to the player.

**Comment by mspykerez** [comment]
Humm you don't make much sense since you CAN optimize DPS while moving, for example if you are a balance druid you can throw moonfire or sunfire while moving despite that in theory for the best dps increase option would be to stop moving and cast something else, in situations where you just cant stop moving it would be a dps increase instead of doing nothing, off course if you stop moving the suggestion would be reverted to the best DPS option. Other addons like herorotation already take into account the movement of the fight and do just that. I'd suggest Hekili do the same with a toggle option where it says 'account for movement'.

**Comment by Hekili** [comment]
Most priorities are not written to account for movement, and simply blocking out hardcasts while moving may not be optimal. 

Yes, Balance Druids can hit Moonfire while moving and they should know to do that. Meanwhile, the addon will have recommendations ready for when they can return to an optimal DPS priority.

The addon _can_ account for movement, but it's up to the user to customize their own priority if they want that. So, again, no.
