### ISSUE TITLE
Wrong icons with The Codex of Xerrath

### ISSUE THREAD

**Issue by tflo** [Hekili/hekili#630]
On my Warlock I have [The Codex of Xerrath](https://www.wowhead.com/spell=101508/the-codex-of-xerrath#comments) (the achievment that makes all fire spells green).

After login, Hekili shows the default red (fire) icons, instead of the green (fel) icons. However, after a manual UI reload the correct icons are shown.

Wrong (after login):

![WoWScrnShot_120520_163943-bad](https://user-images.githubusercontent.com/1410282/101247397-b7113380-3719-11eb-9b61-b7e68a1c2585.jpg)

Correct (after reload):

![WoWScrnShot_120520_164011-good](https://user-images.githubusercontent.com/1410282/101247404-c1333200-3719-11eb-94a3-c52a83837a9b.jpg)

(To avoid confusion: The second spell in the screenshots (Channel Demonfire, 196447) is always green, with or w/o Xerrath.)

I tend to think that this issue was not there before Shadowlands. But I’m not sure, since I rarely played the Destro spec before Shadowlands. (Not many fire spells with Affli/Demo.)

Would be nice if the correct icons were shown, also without manual reload.

– Tom

---

PS: On the action bar and in the Spellbook the icons are always correct. So, it’s probably not an issue with the game itself.

**Comment by Hekili** [comment]
I believe this is fixed in beta; try the beta branch and include the required ticket information (from /hekili > Issue Reporting) if this needs follow-up.

**Comment by tflo** [comment]
Yes, seems fine now. Thank you!
