### ISSUE TITLE
Trueshot and Double Tap are not being recommended 

### ISSUE THREAD

**Issue by TeaguePerry** [Hekili/hekili#631]
**BEFORE SUBMITTING AN ISSUE:**

1.  I am using the latest version

2.  I saw another issue reported in February but it has been closed.

**Describe the Bug/Issue**
When using Hekili trueshot and double tap are never being recommended.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
I expect that they would be recommended at some point.  The opener for marksman hunters is double tap then Aimed shot.

**Screenshots**

![image](https://user-images.githubusercontent.com/13986496/101260390-84594200-36fd-11eb-83f0-bc4bb49f953e.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.2-1.0.13
level: 60 (60)
class: HUNTER
spec: marksmanship

talents: double_tap
    explosive_shot
    master_marksman
    natural_mending
    posthaste
    streamline
    volley

pvptalents: none

covenant: kyrian

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: absonant_constructs_handguards = 1
    artisan_officers_shirt = 1
    ballista_of_buried_kings = 1
    champions_of_azeroth_tabard = 1
    fleshfused_circle = 1
    gorewrought_drape = 1
    hiveswarm_bracers = 1
    infinitely_divisible_ooze = 1
    mantle_of_ephemeral_visages = 1
    ring_of_perpetual_conflict = 1
    shadowgrasp_totem = 1
    sin_stained_pendant = 1
    sinful_aspirants_chain_belt = 1
    sinful_aspirants_chain_vest = 1
    soulthorn_visage = 1
    striders_of_restless_malice = 1
    wind_dancers_legguards = 1

legendaries: none

itemIDs: 160544, 175854, 175877, 178692, 178703, 178745, 178769, 178821, 178827, 178839, 178869, 178872, 179356, 180105, 181638, 184805, 89195

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Marksmanship
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    trueshot_vop_overlap = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
They are controlled by the Cooldowns toggle, which you have turned off.

[See the Getting Started part of the Wiki.](https://github.com/Hekili/hekili/wiki/Getting-Started#toggles--cooldowns-interrupts-potions-and-defensives)
