### ISSUE TITLE
Getting your specialization automatically changed by entering or exiting an queued dungeon does not change the priority

### ISSUE THREAD

**Issue by nzall** [Hekili/hekili#632]
**Describe the Bug/Issue**
If you are DPS in the open world, and then join a dungeon as a tank, you enter the dungeon immediately as a tank. However, entering the dungeon in this way does not change the Hekili recommendations to match the new spec. Example, as a Ret Paladin, if I queue as a tank for a random dungeon, I get automatically set to Protection spec upon entering (similar to how BGs work), but Hekili thinks I'm still Retribution and I need to /reload my UI to fix it. The reverse happens when leaving the dungeon: my spec gets returned to Retribution, but Hekili assumes I'm protection still.

**To Reproduce**
- Log in on a character with a DPS spec and a Tank spec;
- Be in DPS spec while queueing for a random dungeon as tank;
- Enter the dungeon.
Entering the dungeon will automatically set you to Protection, but Hekili will remain retribution.

**Expected behavior**
I expect Hekili to switch priority systems according to the specialization automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/6772095/101262003-98239900-373b-11eb-98aa-d1cba32ffc33.png)
This shows my paladin in DPS spec while my priority is shown for tank spec (it should be recommending Wake of Ashes and Templar's Verdict normally).

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/SMCrKHgd

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/dHUMf8rG

**Comment by Hekili** [comment]
I believe this is fixed in the 1.0.16 release I'm putting out now (it worked for me).  Let me know if it persists.
