### ISSUE TITLE
Affliction Warlock: no target swap icon when Recommend Target Swaps is enabled

### ISSUE THREAD

**Issue by codecrete-ross** [Hekili/hekili#633]
**Describe the Bug/Issue**
When using an AoE rotation for Affliction Warlock, the target swap icon does not appear on any spells.

**To Reproduce**
- Spec as Affliction.
- Enable the "Recommend Target Swaps" setting under Affliction > Targeting.
- Engage in a multi-target fight.
- Observe the lack of target swap icons when the queue fills up with Agony.

**Expected behavior**
I expect the target swap icon to appear if any DoT spell is suggested to be cast repeatedly.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/raw/72RwWQFA

**Comment by Hekili** [comment]
Why did you cut off the snapshot instructions and not include one?

**Comment by Hekili** [comment]
@kehlankrumme Can you provide a snapshot taken when there are multiple targets, but no recommendations to apply dots to other targets?

**Comment by codecrete-ross** [comment]
Apologies. I will try to reproduce this ASAP and provide a snapshot. I just did a bunch of dungeons and it seems intermittent.

**Comment by Hekili** [comment]
Can you tell me more about the circumstances you're concerned about?  Are you trying to set up initial dots or are you concerned with dots falling off?  It'll be very challenging for you to get a snapshot, but keep in mind that when targets are expected to die quickly, or when targets haven't been seen long enough to know how quickly they will die.

**Comment by codecrete-ross** [comment]
The main problem is that sometimes the queue will completely fill up with Agony casts, but it won’t give me a target swap icon, which can make things difficult when trying to tab over to the correct target that needs the Agony DoT.

**Comment by Hekili** [comment]
Use a mouseover macro, but also, yeah, snapshot that.

**Comment by tflo** [comment]
Seeing the same or a similar thing.

Tested it on a swarm dummy (5 targets):

- Happens only when set to AoE or Auto (or in the separate AoE display, if activated)
- The recommendation basically seems correct (put Agony on all targets), but, as @kehlankrumme said, the queue fills up with Agony, and often (not always) no Swap icons, even with Target Swaps enabled:

![WoWScrnShot_120820_105418](https://user-images.githubusercontent.com/1410282/101468533-d7bcd180-3943-11eb-9ae7-36ca906f0fce.jpg)


In my understanding (which often is wrong) it should behave like this:

- If set to AoE or Auto, with Target Swaps _disabled_, it should only show recommendations for the current target. This would include AoE abilities _on the current target_ (like Seed of Corruption) but _not_ recommendations for the other targets (like a queue full of Agony in this case).

- If set to AoE or Auto, with Target Swaps _enabled_, it should show recommendations for the current target and give recommendations for the other targets by displaying them with the Swap icon. (This could be a queue of Agony, but with Swap icons.)

Is this correct?

Concerning the intermittent absence of Swap icons when Target Swaps is enabled, I couldn’t see a pattern when these start to appear/disappear.

Snapshots, after casting an initial Seed of Corruption and Agony on the first target:

[Without Target Swaps](https://pastebin.com/hgxjSXWx)
[With Target Swaps enabled](https://pastebin.com/DgSLX5ww)

**Comment by Hekili** [comment]
I have a fix for this that will be in 1.0.19.
