### ISSUE TITLE
Tranquilizing Shot not recommended as Marksmanship

### ISSUE THREAD

**Issue by hlokk101** [Hekili/hekili#635]
Tranquilizing Shot is not recommended when in combat and targeting a mob with a dispelable debuff, which it does for Beast Mastery.

**To Reproduce**

Fight any mob with a dispelable debuff as a Marksmanship hunter and you will note that Tranquilizing Shot is not recommended.

**Expected behavior**

Tranquilizing Shot is expected to be recommended when targeting a mob with a dispelable debuff.

**Issue reporting info**

https://pastebin.com/qYw52vdR

**Comment by Hekili** [comment]
It's not there.  To be honest, half the time when I include dispels, people want them removed.  If I don't include them, people want them added.

I'll probably do this when I also have time to make it easier to turn on/off.

**Comment by hlokk101** [comment]
Thanks mate <3
