### ISSUE TITLE
Demon Hunter Havoc - Cycle of Hatred Talent

### ISSUE THREAD

**Issue by HallwayRaptor** [Hekili/hekili#636]
**Describe the Bug/Issue**
Addon doesn't account for the Cycle of Hatred talent which eliminates Blade Dance from the rotation completely. Currently it is suggesting Blade Dance in the ST and AOE rotations, it shouldn't be in either. 

**To Reproduce**
Fight any target with Cycle of Hatred talent

**Expected behavior**
choosing the Cycle of Hatred talent should remove blade dance/death sweep from the rotation

Issue report
https://pastebin.com/R8uKED4Y

**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/XLbtQ5UA

**Comment by Hekili** [comment]
You are not using the default priority for Havoc.

The default priority uses the following criteria for Blade Dance:

`talent.first_blood.enabled | spell_targets.blade_dance1 >= ( 3 - ( talent.trail_of_ruin.enabled + buff.metamorphosis.up ) ) | runeforge.chaos_theory.enabled & buff.chaos_theory.down`

That is:
1.  First Blood is talented.
-OR-
2.  There are 3 targets; that requirement is reduced by one if Trail of Ruin is talented and reduced by one again if Metamorphosis is up.
-OR-
3.  You have the Chaos Theory legendary and Chaos Theory is down.

**Comment by Misclicker** [comment]
Hi Hekili,

Thanks for the addon, Just curious, I am also facing this issue where I am wanting to remove Blade Dance from my rotation completely and I have also disabled it in Hekili's settings, but it still recommends me to cast it? 

What can I do to remove this?

Thanks
