### ISSUE TITLE
MM Hunter suggesting Multishot during Volley

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#637]
While you have Volley up as MM Hunter you get Trick Shots buff for the entire durtation, which means you should be able to get off a Aimed Shot and Rapid Fire,
I was testing out using Double Tap and Volley (which is cds used inbetween next Trueshot) and after the first Aimed Shot, it was suggesting to use Multishot maybe thinking it needs to reapply Trick Shots. I don't believe Hekili is tracking Trick Shots entire duration of Volley, only the first ability.

To reproduce, just go to dummy and use Volley or Double Tap and Volley. Also happens in Dungeons, so nothing to do with Dummies... I believe.

Snapshot:
https://pastebin.com/6a2giNFc

**Comment by Hekili** [comment]
Resolved.
