### ISSUE TITLE
Hekili Updates Don't Overwrite Customized Priorities

### ISSUE THREAD

**Issue by vicwac** [Hekili/hekili#638]
Correct me if I'm wrong, but if I use a customized priority, does that mean when Hekili is updated I won't be able to enjoy the latest updates unless I switch back to the latest default priority?

Is it possible to make it such that updates don't overwrite customized settings unless the update directly affects that particular setting? For example when an improvement or fix has been made to a skill that I had to customize myself previously while waiting for an update, then the parameters for that skill will be overwritten.

Whenever the addon updates, I lose all my health.pct settings for heal skills and healthstones as well, in addition to movement check modifiers for hard cast skills, so unless the update is going to patch that skill beneficially, it would be good if customized settings can continue to exist alongside the latest updates so I don't have to choose between keeping my custom settings or losing them so I can have the most updated version.

**Comment by Hekili** [comment]
Nope.

If you use customized priorities, it's on you to maintain them.

The FAQ explains to make a copy.
