### ISSUE TITLE
Missing Recommendations at 2 3 and 4 Wounds | Unholy DK

### ISSUE THREAD

**Issue by Gamniac** [Hekili/hekili#641]
**Describe the Bug/Issue**

Hekili does not provide a Recommendation at 2 3 or 4 Wounds.

**To Reproduce**

I simply played Wow with Hekili on? I was inside the Maw should that matter.

**Screenshots**

Infight with 2 Wounds

https://www.bilder-upload.eu/bild-f16591-1607371652.jpg.html

Out of Combat

https://www.bilder-upload.eu/bild-6b3d79-1607371699.jpg.html

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/rH2KBBdy

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3 Wounds

https://pastebin.com/KZPS3dBa

2 Wounds

https://pastebin.com/eFt9DnET

Out of Combat (snap at the moment from screenshot above)

https://pastebin.com/7detSikP

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

No Error Messages

**Comment by Gamniac** [comment]
Oh by the Way it only started with the latest Version of Hekili

**Comment by Hekili** [comment]
When it finishes building, try 1.0.18-beta1.

**Comment by Xeltor** [comment]
For me 1.0.18-beta1 seems to have fixed the issue.

**Comment by Hekili** [comment]
Thanks for confirming.  Will get this in a release ASAP.

**Comment by Gamniac** [comment]
While this fixed the Issue for the Wounds it opened up the Issue that Unholy Blight and Dark Transformation are not recommended anymore whatsoever
