### ISSUE TITLE
Shadlowlands are missing from "Default Potion" 

### ISSUE THREAD

**Issue by Serenga** [Hekili/hekili#643]
Hello! Absolutely love your work! I am using version: Using Version: 9.0.0-1.0.17

Shadowlands potions such as " Potion of Spectral Strength"  are missing from the drop down. 

Here are the item id's:

spell=307098 Potion of Spectral Strength
spell=307093 potion-of-spectral-agility
spell=261423 spiritual-rejuvenation-potion
spell=307095 potion-of-spiritual-clarity

Is there a way I can manually add them into the mix?

Thank you!!!
![WoWScrnShot_120720_183845](https://user-images.githubusercontent.com/75647492/101418704-6980fc00-38bc-11eb-90cb-b28ce257ec98.jpg)

**Comment by Hekili** [comment]
Will add a bunch.  Will retire the old ones.

**Comment by Serenga** [comment]
Thank you very much!!!!
