### ISSUE TITLE
Expose IsSpellInRange in State

### ISSUE THREAD

**Issue by jeanbmar** [Hekili/hekili#644]
First, thank you for the impressive and well polished work on this project.

Right now we have no way to check if a spell is in range to change priorities since IsSpellInRange is not exposed in state.
target.distance doesn't provide a reliable value and target.in_range uses an hardcoded value.
State.IsUsable won't work since self.rangefilter is nil or false.

Could you expose LSR.IsSpellInRange in State?

**Comment by Hekili** [comment]
Give me examples of usage.

**Comment by Hekili** [comment]
Gonna throw in `in_range` or `action.whatever.in_range` and see what comes of it.

If an ability doesn't have an actual range, it's going to return true.  Or if you don't have a target.  Or if you have a non-attackable target.

So basically it returns false if you don't have an attackable target or you're out of range for the ability.

**Comment by jeanbmar** [comment]
Sounds good thank you.
I'm using this to prioritize sub rogue blink abilities (shadowstrike, shadowstep) over melee stuns (cheap shot) for non-raid APL.
