### ISSUE TITLE
Druid "Moonkin" Symbol stays in rotation

### ISSUE THREAD

**Issue by pltboom** [Hekili/hekili#645]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is. When using the addon for my Moonkin druid, it keeps telling me to become a moonkin even after I already am, they symbol never goes away
![WoWScrnShot_120720_194013](https://user-images.githubusercontent.com/64226897/101422245-393d5b80-38c4-11eb-853d-2a627787c6b4.jpg)

**To Reproduce**
- Go to '...' Have the addon and be a moonkin druid and just log in, Im in shadowlands
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
Once I transform to a moonkin , I expect that symbol to go away on the addon to show the clear rotation but the moonkin symbol never goes away

**Screenshots**
If applicable, add screenshots to help explain your problem.+
added

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.    https://pastebin.com/YDZq4wmt

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
PUT SNAPSHOT LINK HERE:

**Comment by Hekili** [comment]
Are you using Glyph of Stars?  If so, what is the spell ID of your Moonkin Form?

**Comment by pltboom** [comment]
Im lookoing for it, can you tell me exactly where to look? Im in the character data but Im lost

**Comment by pltboom** [comment]
> Are you using Glyph of Stars? If so, what is the spell ID of your Moonkin Form?

I have no idea where to look, Im in the character data, please point me in the right direction and Ill be happy to get it for you and yes I am using glyph of stars

**Comment by Hekili** [comment]
To see the spell ID, you'd need an addon like TipTac that shows spell IDs when you mouseover the icon.  But I will get this sorted.

**Comment by Hekili** [comment]
I can't replicate this on my druid, so you'll need to get the snapshot per the instructions I posted earlier.

**Comment by Hekili** [comment]
Oh, wait -- why don't you use your Kyrian ability (which will knock you out of Moonkin Form) and then use Moonkin Form again?

I'm actually not seeing a problem here.

**Comment by pltboom** [comment]
> Oh, wait -- why don't you use your Kyrian ability (which will knock you out of Moonkin Form) and then use Moonkin Form again?
> 
> I'm actually not seeing a problem here.



> Oh, wait -- why don't you use your Kyrian ability (which will knock you out of Moonkin Form) and then use Moonkin Form again?
> 
> I'm actually not seeing a problem here.

Yep that worked thank you so much, sorry I wasted your time. My apologies
