### ISSUE TITLE
Hekili does not recommend Flare when Tar Trap affects certain enemies, such as bosses

### ISSUE THREAD

**Issue by witchof0x20** [Hekili/hekili#648]
**Describe the Bug/Issue**
Hekili should recommend casting Flare while the target is inside a Tar Trap if the player is wearing a Soulforge Embers legendary. On certain enemies, such as bosses, or the Raider's Target Dummy, the target is not afflicted by the Tar Trap Debuff, and Hekili does not recommend Flare.

Extra info:
* I casted Tar Trap on Raider's Target Dummy
* I ran: `/run for i=1,40 do local name, icon, _, _, _, etime,_,_,_,spellId = UnitDebuff("target",i); if name then print(("%d=%s, %s, %.2f minutes left."):format(i,name,spellId,(etime-GetTime())/60)); end end`
* No output

* I casted Tar Trap on Dungeoneer's Target Dummy
* I ran the above command
* It output: `1=Tar Trap, 135299, -213.49 minutes left`

**To Reproduce**
- Wear a Soulforge Embers legendary on a hunter
- Cast Tar Trap at Raider's Training Dummy

**Expected behavior**
Hekili recommends flare, at some point in the list of recommended moves

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/rjtqh2UJ

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/cmLY0Zud

**Comment by Hekili** [comment]
I'm not able to replicate this on my end.  The only place where Flare fails to show up is when the Tar Trap debuff is not applied.

Can you throw a Tar Trap at a dummy and provide the following output:

`/run local s = Hekili.State; s.reset(); print( s.tar_trap.up, s.tar_trap.remains, s.debuff.tar_trap.up, s.debuff.tar_trap.remains, s.debuff.tar_trap.id )`

**Comment by Hekili** [comment]
Rechecking, can you provide the requested information?

**Comment by Marakuja** [comment]
Maybe I can help here as I experience the same issue, it seems. When targeting a boss (or crowd control immune mobs) with a tar trap, the debuff is not shown on the target frame, but placing a flare there will still apply soulforge embers debuff. Like the tar trap is "hidden" but active on the target.

I screenshotted a boss fight this evening, where he stands in a tar trap and casting flare is placing embers on him. But Hekili doesn't recommend it, as the tar trap debuff is not there.

![image](https://user-images.githubusercontent.com/5399381/101681181-12b52700-3a62-11eb-87bd-1d4cbfcf0173.png)

**Comment by Hekili** [comment]
This is a challenging scenario.  I could potentially capture the triggering of the trap and assume that a target is in the trap for a certain amount of time.  But it's entirely possible for a boss to get kited through and out of your trap very quickly.

**Comment by witchof0x20** [comment]
> I'm not able to replicate this on my end. The only place where Flare fails to show up is when the Tar Trap debuff is not applied.
> 
> Can you throw a Tar Trap at a dummy and provide the following output:
> 
> `/run local s = Hekili.State; s.reset(); print( s.tar_trap.up, s.tar_trap.remains, s.debuff.tar_trap.up, s.debuff.tar_trap.remains, s.debuff.tar_trap.id )`

`false 0 false 0 135299`



> This is a challenging scenario. I could potentially capture the triggering of the trap and assume that a target is in the trap for a certain amount of time. But it's entirely possible for a boss to get kited through and out of your trap very quickly.

I think this would be nice as an option, though not necessarily as the default.

**Comment by Hekili** [comment]
Yeah, for bosses, I will have to fake a trap because I can't even see the trap trigger vs. a boss (the only indicator is the debuff application, which doesn't happen).

Tuning around how long one should reasonably expect the trap to be applied, how long it should take to trigger, etc., is complicated.  But I'm thinking about it.

**Comment by witchof0x20** [comment]
FWIW, I sometimes use a modified profile that takes `if=tar_trap.up` out of Flare's condition and just tells me to use it on CD, and it works fairly well. The only issue I've run into is that since Tar Trap sits on the ground longer than its CD, Hekili will tell me to refresh it, and I just ignore the recommendation until the boss moves and I need to throw it.

**Comment by p4nchez** [comment]
is there a way for me to fix this ?
its the same it suggest me tar trap and right in the moment i press tar trap flare disapears in the recommendation list

it happens even if i throw trap on targets and they proc or not
testet on dummys and in dungoen it only show flare as second if tar trap the first but after pressing trap flare is gone and get not even on first icon postion

http://wanna.see.my.p4nda.de/ShareX/2021-01-23_15-00-25.mp4

**Comment by Hekili** [comment]
I'm looking into options for this.  When looking into the future, the addon models you casting Tar Trap and then assumes your target(s) will trigger the trap and get the debuff.

After you actually cast Tar Trap, if it pops under an enemy that isn't affected by snares, the addon can't see anything re: whether your target is actually standing in the trap or not.

You can test with the latest beta and provide new snapshots for the issue, which might give me new information that helps sort it out.  But it's really a matter of when/how I will decide to fake the Tar Trap debuff on enemies that can't actually be snared.

In the meantime, it's okay to use Flare even if the addon didn't tell you to, assuming your enemy is in a Tar Trap.
