### ISSUE TITLE
Enhance shammy with Doom Winds legendary - windfurry totem error

### ISSUE THREAD

**Issue by Siba234** [Hekili/hekili#649]
build: v9.0.2-1.0.3
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: earthen_spike
    elemental_assault
    forceful_winds
    natures_guardian
    spirit_wolf
    stormflurry
    sundering

pvptalents: ride_the_lightning
   spectral_recovery
   swelling_waves

covenant: venthyr

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: boneshatter_helm = 1
    bottled_flayedwing_toxin = 1
    dark_praetorians_clasp = 1
    death_gods_signet = 1
    decanter_of_animacharged_winds = 1
    drape_of_inscrutable_purpose = 1
    fallen_paragons_armguards = 1
    gorebound_predators_gavel = 1
    green_linen_shirt = 1
    hakkari_revenants_grips = 1
    harness_of_twisted_whims = 1
    sin_stained_pendant = 1
    sinful_aspirants_ring = 1
    stone_generals_edge = 1
    striders_of_restless_malice = 1
    tabard_of_the_maghar_clans = 1
    technocoil_legguards = 1
    wintersnap_shoulderguards = 1

legendaries: doom_winds = 1

itemIDs: 161328, 172325, 175879, 178695, 178742, 178745, 178827, 178857, 178861, 178864, 179325, 179337, 179353, 179355, 180110, 180114, 184758, 2579

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = superior_battle_potion_of_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
You are more than 15 releases behind.  You need to update your addons more frequently.
