### ISSUE TITLE
Show other factions racials when transformed

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#65]
When the player is transformed to the other faction in Battle of Dazar'alor, it would be nice if Hekili would show the new factions racials. E.g. as a human ret paladin, I'm transformed to a blood elf and then have access to Arcane Torrent.

**Comment by Hekili** [comment]
I believe this is resolved in the latest beta, but haven't tested it in raid.  I simply removed the race-checks on the racial abilities -- if they are in your spellbook, they should work; if not, they shouldn't.

**Comment by cremor** [comment]
Do you mean v8.1.0-20-beta16? Because that's the latest beta version I can see. I already used that version when I created the issue, so it didn't work with that.

**Comment by Hekili** [comment]
Looks like the update was held back.  I'm posting v8.1.0-20 as a release version that should include this.  Re-report if you're seeing issues.

**Comment by cremor** [comment]
@Hekili Still don't see Arcane Torrent with v8.1.0-24-beta1

**Comment by Hekili** [comment]
I'll need information from a character transformed into a Blood Elf to work
on this. See the issue reporting tab and/or snapshot.

**Comment by cremor** [comment]
As transformed blood elf: https://pastebin.com/TcvpnZFC

Snapshot is hard during a raid encounter 😉 ~Will try to find a target dummy toy.~ Target dummy toys can't be used in raids.

Here is a snapshot: https://pastebin.com/dxMWyTwd
I noticed "arcane_torrent is known and NOT enabled." there. Seems like it is disabled because I have the "cooldowns" toggle disabled? Is it by design that Arcane Torrent is counted as a cooldown, even though the default Ret APL has it listed under "generators"?

**Comment by Hekili** [comment]
Arcane Torrent is flagged as a cooldown, yes.  You can change that if you see fit.  And you can see that by looking up the ability in-game.  :)
