### ISSUE TITLE
Unholy DK ui is dissapearing for a few seconds.

### ISSUE THREAD

**Issue by Scaelam** [Hekili/hekili#653]
Im using the latest version of the app through curse.
There does seem to be incomplete tickets on here regarding this, sorry if I'm retreading old ground

The issue is that in seemingly random scenarios across pvp and pve at time the UI element just completely vanishes for a couple seconds. 

Issue report - https://pastebin.com/k76P0WRj

appreciate the hard work my man!

**Comment by Hekili** [comment]
Use beta.

**Comment by Scaelam** [comment]
Likely a dumb question but how do I do that?
