### ISSUE TITLE
Unholy Blight and Dark Transformation not recommended while not on CD

### ISSUE THREAD

**Issue by Gamniac** [Hekili/hekili#658]
**Describe the Bug/Issue**

As reported, Unholy Blight (if talented) and Dark Transformation are not recommended on the Main "Window" while not on CD. Strangely it is shown on the AOE "Window"

**To Reproduce**

Did not figure to how reproduce sorry

**Screenshots**

https://ibb.co/YXjz1Q6

**PUT ISSUE REPORT LINK HERE:**

https://pastebin.com/sz0R1sgb

**PUT SNAPSHOT LINK HERE:**

with the issue

https://pastebin.com/4R4H0jJ6

**PUT ERROR MESSAGE(S) HERE:**

No error messages

**Comment by Hekili** [comment]
The APL was trying to sync Dark Transformation with Unholy Blight but was failing to detect the Unholy Blight dot.  Should be fixed in 1.0.19.
