### ISSUE TITLE
After few seconds of fight hekili stops to show or recommend rotation

### ISSUE THREAD

**Issue by vaskolukas** [Hekili/hekili#659]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Basically after today update to newest version, when i start the fight after few seconds in chat appaers the message that snapshot was made and rotation stops recommend next spells to use (showed in screenshot). I have 4 recommended spells to show in a row but now it stops to show rotation and keeps only one or two spells there. As you can see in my spells bar, i have plenty of spell ready but hekili wont show them on rotation. And then after few seconds its "resets" and working fine, then again after few seconds like freeze.

**To Reproduce**
Just start fight.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16058658/101646006-4cbd0380-3a37-11eb-9c18-0130ec2b4807.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/zFpWkuW8

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/RQm7La50

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

bugsnack says no errors

**Comment by Hekili** [comment]
Thanks for the complete ticket.  Fix is coming in 1.0.20 in a few minutes.
