### ISSUE TITLE
Interface LUA Error upon game load in

### ISSUE THREAD

**Issue by Racerx323** [Hekili/hekili#660]
1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.2-1.0.20
level: 60 (60)
class: PALADIN
spec: protection

talents: blessed_hammer
    blinding_light
    divine_purpose
    first_avenger
    sanctified_wrath
    unbreakable_spirit

pvptalents: none

covenant: kyrian

sets: none

gear: chain_of_the_purposebound = 1
    darkmoon_deck_voracity = 1
    drape_of_inscrutable_purpose = 1
    emberscarred_girdle = 1
    gorewrought_loop = 1
    honortoll_gavel = 1
    kudebehs_remarkable_targe = 1
    overflowing_ember_mirror = 1
    precious_ribbon = 1
    sapsteel_breastplate = 1
    selfless_collectors_gauntlets = 1
    selfless_collectors_legguards = 1
    shadowghast_helm = 1
    shieldguards_vambraces = 1
    sprigthistle_loop = 1
    steelcore_warboots = 1
    tabones_branded_pauldrons = 1

legendaries: holy_avengers_engraved_sigil = 1

itemIDs: 171415, 173087, 174292, 174293, 175713, 177657, 181202, 181400, 181614, 181626, 181635, 181656, 184757, 184758, 184806, 184809, 52019

settings: aoe = 2
    buffPadding = 0.25
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Protection Paladin
    petbased = false
    potion = potion_of_unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

Message: Interface\AddOns\Hekili\Options.lua:3943: attempt to concatenate local 'k' (a nil value)
Time: Wed Dec  9 13:29:20 2020
Count: 1
Stack: Interface\AddOns\Hekili\Options.lua:3943: attempt to concatenate local 'k' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Hekili\Options.lua"]:3943: in function `EmbedItemOption'
[string "@Interface\AddOns\Hekili\Classes.lua"]:545: in function `func'
[string "@Interface\AddOns\Hekili\Events.lua"]:218: in function `handler'
[string "@Interface\AddOns\Hekili\Events.lua"]:56: in function <Interface\AddOns\Hekili\Events.lua:50>

Locals:

**Comment by Hekili** [comment]
Thanks for the report.  Does this keep the addon from working?

**Comment by Racerx323** [comment]
It does not appear to prevent the add-on from functioning.

**Comment by Hekili** [comment]
After updating 1.0.23, can you let me know if there is anything in /hekili > Warnings (the section only appears if there's a warning).

**Comment by Hekili** [comment]
I'm closing due to lack of updated information.

**Comment by Racerx323** [comment]
Hi,
Apologize for the delay. There is not a 'warnings' section and the error no longer occurs after the update to 1.0.23. Thank you for the excellent work and awesome plugin.
