### ISSUE TITLE
Vanish is not showing up in recommendation after toggle update

### ISSUE THREAD

**Issue by Gyudon47** [Hekili/hekili#661]
https://pastebin.com/k8KhjSNU

Vanish is not showing up in recommendation with either solo toggle on or off. Did not show up in any content.
Thanks for all the work you do hekili

**Comment by Hekili** [comment]
Test 1.0.22-beta2 in a few minutes.

**Comment by Gyudon47** [comment]
working after 1.0.22-beta2 update. Thank you
