### ISSUE TITLE
Corpse exploder

### ISSUE THREAD

**Issue by bobtatuss** [Hekili/hekili#663]
Hello i was just wondering how would i go by removing an ability off my rotation , ive never had corpse exploder pop up in the rotation before and id like to remove it so it doesn't show up. thank you

**Comment by Hekili** [comment]
/hekili > Abilities, and you're probably concerned with "Sacrificial Pact" -- you really should consider blowing up your friend before he goes away.

**Comment by bobtatuss** [comment]
Oh my god that's what it is! because its the same image i got hell confused man , your a legend thank you so much for the help and quick response!
