### ISSUE TITLE
Retribution paladin Torghast doesn't show next ability (sometimes)

### ISSUE THREAD

**Issue by justnubby** [Hekili/hekili#664]
I have Sanctified Wrath talent.  When I get the "free" level 50 talent through an anima orb, I pick Crusade.  Hekili freaks out and starts showing random abilities in the list.  It will usually go blank within 1-5 GCDs.

build: v9.0.2-1.0.18
level: 60 (60)
class: PALADIN
spec: retribution

talents: divine_purpose
    empyrean_power
    fist_of_justice
    healing_hands
    righteous_verdict
    sanctified_wrath
    unbreakable_spirit

pvptalents: none

covenant: kyrian

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: anima_field_emitter = 1
    arachnid_cipher_ring = 1
    breastplate_of_brutal_dissonance = 1
    drape_of_twisted_loyalties = 1
    dreadguards_greathelm = 1
    gormshell_greaves = 1
    guilewind_stone_talons = 1
    lucky_shirt = 1
    muckwallow_stompers = 1
    rimebinders_runeblade = 1
    sin_stained_pendant = 1
    steelcore_girdle = 1
    stitchfleshs_misplaced_signet = 1
    unyielding_combatants_pauldrons = 1
    vambraces_of_the_depraved_warden = 1
    viscera_of_coalesced_hatred = 1

legendaries: none

itemIDs: 138385, 178701, 178736, 178774, 178780, 178802, 178808, 178827, 178840, 178845, 178933, 180099, 180118, 180123, 181675, 184660

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Retribution
    petbased = false
    potion = potion_of_focused_resolve
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Always update to the latest version before submitting a bug report.

**Comment by justnubby** [comment]
Would it be worthwhile to try again with the latest?  I'll give it a try tomorrow and report back.

**Comment by Hekili** [comment]
Yes, of course, that's why I said it.
