### ISSUE TITLE
How to add Death Strike to rotation so that it is shown by percentage.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#665]
Hello. Tell me please. How do I add Death Strike to the rotation? and in which section in the addon is it better to register it? I would like to add the condition that if we have less than 70% HP then use Death Strike. If more than 70% are not offered for rotation. And if there is a dark succor buff, then also make him the same conditions as above so that I apply it in the same way as a percentage of hp. Tell me please. How best to write it, and where in the rotation cells I can add it. This will make the task very easy in solo mode.

**Comment by Hekili** [comment]
Sorry, I don't write custom priorities for people. I don't have the time. Look at the FAQ.
