### ISSUE TITLE
Request Ability to remove recommendations from list!

### ISSUE THREAD

**Issue by Destruo** [Hekili/hekili#666]
Please describe your idea or feature and when it would be useful.
Hi this may already be available and apologies if it is but is there anyway to remove or disable an ability from being recommended.

**Comment by Voltaec** [comment]
if you add an ability to a toggle list that you don't have active it will not be recommended...so put the ability on custom 1, and leave custom 1 turned off, and you'll never see it.

**Comment by Hekili** [comment]
You can disable abilities permanently in /hekili > Abilities.
