### ISSUE TITLE
Windfury no longer pops up when out of range

### ISSUE THREAD

**Issue by Voltaec** [Hekili/hekili#667]
With the last update, the Doom Winds legendary effect is causing the mod to not prompt a new Windfury Totem when out of range of the last one.  It's now only looking at the Doom Winds debuff and prompting a new totem when the debuff is gone.  This happened with the most recent update, as it was working correctly last night in the raid, and the behavior changed when I went to the newest version, even though there were no listed shaman changes.

**To Reproduce**
With Legendary off - Target Mob, drop totem on prompt, move 30 yards to move out of range, another prompt for the totem, so working correctly.

With Legendary On, Target Mob, drop totem on prompt, move 30 yards to move out of range, no prompt for another totem, it should be telling me to drop it since I'm no longer in range of the totem for the buff.  It is only prompting the totem when not wearing the Doom Winds legendary.

**Expected behavior**
It is only prompting the totem when not wearing the Doom Winds legendary item.  As soon as I take the legendary off it works correctly.  

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  build: v9.0.2-1.0.22
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: earthen_spike
    elemental_assault
    forceful_winds
    natures_guardian
    spirit_wolf
    stormflurry
    sundering

pvptalents: none

covenant: night_fae

sets: none

gear: azurevenom_choker = 1
    boneshatter_helm = 1
    dark_praetorians_clasp = 1
    decanter_of_animacharged_winds = 1
    drape_of_inscrutable_purpose = 1
    fallen_paragons_armguards = 1
    grips_of_the_dreadhound_tamer = 1
    harness_of_twisted_whims = 1
    mantle_of_ephemeral_visages = 1
    penitent_edge = 1
    phial_of_putrefaction = 1
    ring_of_perpetual_conflict = 1
    signet_of_the_false_accuser = 1
    stoneguardians_morningstar = 1
    striders_of_restless_malice = 1
    technocoil_legguards = 1

legendaries: doom_winds = 1

itemIDs: 172325, 178745, 178771, 178821, 178824, 178834, 178861, 178872, 179337, 179353, 180095, 180110, 180114, 180115, 184659, 184758

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
This will be resolved in 1.0.23.
