### ISSUE TITLE
Frostbrand wanting to be constantly applied

### ISSUE THREAD

**Issue by drzepp123** [Hekili/hekili#67]
When switching talents that did not previously have hailstorm with a tome of tranquil mind the addon does not recognize the hailstorm buff you get when cast and will constantly want you to cast the ability. This happens alot in raid and I have to turn off the addon and not use it. The only way I was able to fix it is to redownload the addon.

**Comment by Hekili** [comment]
Please fill out the template and provide the required information to investigate this issue.

**Comment by drzepp123** [comment]
https://pastebin.com/shxxrVFX is this what you want or to just recreate the whole ticket?

**Comment by Hekili** [comment]
I need the snapshot showing it recommend Frostbrand.

**Comment by drzepp123** [comment]
https://pastebin.com/p3rmauzp

**Comment by Hekili** [comment]
Thanks.  Can you try the latest beta and see if you still have this issue?

**Comment by drzepp123** [comment]
Seems to be fixed thanks!
