### ISSUE TITLE
Implement movement detection (easy + adds a lot of value)

### ISSUE THREAD

**Issue by TrackManGod** [Hekili/hekili#670]
A lot of Simc actions rely on checking if the character is moving or not.  
We could easily implement this check by checking if WoW api function GetUnitSpeed("player") > 0 .

This could be used to improve many action packs, especially for classes that have both casted spells and instant spells, for example Arcane Mage, Elemental Shaman, Shadow Priest, Marksman Hunter, and more.

**Comment by Hekili** [comment]
Good news, this already exists.  `moving` is a valid condition.
