### ISSUE TITLE
Use a title that describes the problem scenario.

### ISSUE THREAD

**Issue by marshmallowpotato** [Hekili/hekili#672]
**Describe the Bug/Issue**
On Marksmanship Hunter in AoE Multi-shot on 3 or more target causes your next aim shot or rapid fire to cleave.

On the Addon it will say MultiShot -> Aimed Shot -> Rapid Fire , after the aimed shot cast goes off the Trickshots buff that makes it cleave is consumed meaning you should be casting another multi shot immediately after.  By default in AoE on 3+ target you should be activating trick shots by casting a multi shot inbetween each but because while casting aimed shot you still have the trick shots buff it default recommends following up with a rapid fire because you still have the buff until consumed.
**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Please fill out the ticket correctly.

**Comment by Hekili** [comment]
I'm just going to close this, actually.  Submit a new ticket with the information required, following all the steps, if needed.
