### ISSUE TITLE
Void eruption missing from rotation

### ISSUE THREAD

**Issue by EventMerge** [Hekili/hekili#676]
Is there any reason why i would be missing void eruption in the shadow priests rotation..ive confirmed i have the latest version and that its on my bar. However im never asked to use it and just do it myself - once i have void bolt does appear in the rotation. Im not an experience user with Hekili but so far im liking the addon!

**Comment by Hekili** [comment]
It's most likely that you do not have the Cooldowns toggle turned on (see /hekili > Toggles).

If it's not that I have no way of answering with the limited information provided.  See the ticket instructions when you click the "New issue" button here.
