### ISSUE TITLE
Sub Rogue - Prey on the Weak

### ISSUE THREAD

**Issue by dazedsean** [Hekili/hekili#677]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

When the talent Prey on the Weak is slotted as a sub rogue the add-on does not recommend to use cheap shot or kidney shot during the rotation to increase damage to the target for 6 seconds. I imagine it would rotate something similar to shadow dance, kidney (or cheap) shot, shadowstrike til full combo points then a finisher and repeat

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:
build: v9.0.2-1.0.22
level: 60 (60)
class: ROGUE
spec: subtlety

talents: cheat_death
    deeper_stratagem
    enveloping_shadows
    prey_on_the_weak
    secret_technique
    shadow_focus
    weaponmaster

pvptalents: cold_blood
   maneuverability
   smoke_bomb

covenant: night_fae

sets: none

gear: chain_of_the_purposebound = 1
    darkmoon_deck_indomitable = 1
    darkwing_assassins_blade = 1
    deadly_sinvyr_ring = 1
    drape_of_inscrutable_purpose = 1
    duskwarder_knife = 1
    oakheart_armguards = 1
    oakheart_tunic = 1
    remote_guidance_device = 1
    shadebound_armguards = 1
    shadebound_greaves = 1
    shadebound_helm = 1
    shadebound_waistguard = 1
    vanquished_usurpers_footpads = 1
    versatile_solenium_ring = 1
    wicked_bladewing_pauldrons = 1

legendaries: none

itemIDs: 169769, 172253, 172254, 172256, 172257, 173096, 173131, 173134, 178797, 178858, 179500, 179765, 179767, 181215, 184757, 184758

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Subtlety
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    mfd_waste = true
    priority_rotation = false
    solo_vanish = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE: https://pastebin.com/ayJX5TKu

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:

**Comment by Hekili** [comment]
As we discussed, neither Sub nor Assassination attempts to take advantage of Prey on the Weak in sims (mainly because it's useless on bosses, generally).  Please keep me updated on the outcome of your simc ticket.
