### ISSUE TITLE
Demonology Demonic Tyrant

### ISSUE THREAD

**Issue by FabienCap** [Hekili/hekili#68]
Hi Kapulani, 

First of all, thank you for your awesome work ! Big kudos !

I would like to report an issue with Demonic Tyrant : Warlock Demonology spec.

I saw you updated Hekili with more precise calculation on when to cast implosion. The rotation seems to be correct and implosion is never suggested when < 3 imps. Good !

The issue comes with the **Summon : Demonic Tyrant** who will never show in my action list. The fact is that this is a VERY important cooldown since last class rework by blizz.

Here is the top opener for warlock : Making Demonic Tyrant overpowered : 

Pre-cast Demonbolt (Hekili suggests Shadow bolt at pull)
Cast Doom, if talented
Cast Bilescourge Bombers, if talented
Cast Hand of Gul'dan
Soul Strike, if talented
Build to 5 Soul Shards (Hekili suggests Hand Of Guldan when at 3 soulshard : Not optimized for pull)
Implosion
**Cast Grimoire: Felguard if talented** (Hekili does not show this spell in action list)
Cast Summon Vilefiend, if talented
Cast Call Dreadstalkers
Build to 5 Soul Shards
Cast Hand of Gul'dan
Build to 3 Soul Shards
Cast Hand of Gul'dan
Cast Demonic Strength or Doom (again), if talented, or Shadowbolt
**Cast Summon Demonic Tyrant** (Hekili does not show this spell in action list)

**MAIN ISSUE : SPELLS : Summon Demonic Tyrant and Grimoire: Felguard (Talent) will never show on action list.**

Character data : 

build: v8.1.0-20
level: 120
class: WARLOCK
spec: demonology

talents: burning_rush
    darkfury
    demonic_calling
    demonic_consumption
    demonic_strength
    soul_conduit
    soul_strike

traits: explosive_potential=3
    gutripper=1
    heed_my_call=1
    overwhelming_power=1
    shadows_bite=1
    treacherous_covenant=1
    umbral_blaze=1

sets/legendaries/artifacts: none

gear:     shadra_silk_mantle=1
    stonemasons_guild_band=1
    loa_exultants_shroud=1
    desecrated_blade_of_the_disciples=1
    cord_of_zandalari_resolve=1
    incandescent_sliver=1
    wavecaller_leggings=1
    manceroys_flamefists=1
    the_boomshirt=1
    ironkelp_wristwraps=1
    slippers_of_the_encroaching_tide=1
    charged_sandstone_band=1
    heart_of_azeroth=1
    blazewing_hood=1
    gilded_hexmaw=1
    crest_of_paku=1
    loa_betrayers_vestments=1

Many thanks for your help

**Comment by Hekili** [comment]
You probably don't hav cooldown enabled, but please follow the ticket instructions so I can investigate. I would need a snapshot when you think Tyrant should be recommended but isn't.

**Comment by FabienCap** [comment]
Hi, 
Below the snapshots.

So here are the actual issues I encounter :

- Hekili is suggesting to cast Implosion unstead of sumonic Tyrant after a 5x soulshard and 3x soulshard hand of guland cycle. Also, Hekili never suggets me to cast Demonic Tyrant at any time.
- Hekili suggest me to Implosion while Summon: Demonic Tyrant is active. You don't wan't to kill imps while Tyrant is active.

Once again, thank you for your help


![demonic failure](https://user-images.githubusercontent.com/43843536/53170910-924dd980-35e1-11e9-85ef-ecec5d412d03.PNG)

![hekili config](https://user-images.githubusercontent.com/43843536/53170542-a93ffc00-35e0-11e9-9ba0-513af5689175.PNG)

**Comment by Hekili** [comment]
That is not a snapshot.  Snapshots are the logs created when you pause the addon.

In the meantime, go to the Toggles tab and check out the section about Cooldowns.

**Comment by FabienCap** [comment]
Problem solved in the Toggle section. Many thanks

**Comment by Hekili** [comment]
Great!  Let me know if you find anything else strange!
