### ISSUE TITLE
protection warrior venthyr (no condemn suggestion, only old execution)

### ISSUE THREAD

**Issue by vernetroyer** [Hekili/hekili#680]
Hello, I decided to play Venthyr warrior tank, and Condemn is not suggested in my rotation, it's only the old Execution, I felt like it was a bug, so I'm coming here to tell you :)

build: v9.0.2-1.0.23
level: 60 (60)
class: WARRIOR
spec: protection

talents: anger_management
    booming_voice
    crackling_thunder
    devastator
    indomitable
    rumbling_earth
    unstoppable_force

pvptalents: none

covenant: venthyr

sets: none

gear: bague_rituelle_en_os = 1
    chevalire_de_dieu_de_la_mort = 1
    codex_sinistre = 1
    collier_rapide_en_oxxine = 1
    croquenots_de_fangemare = 1
    cuirasse_dinfluence_surnaturelle = 1
    espauliers_dorgueil_dbrid = 1
    gardepoignets_du_combattant_de_la_fosse = 1
    grand_heaume_de_gardeffroi = 1
    grves_en_carapaces_de_gorm = 1
    hache_du_bosquet_mort = 1
    plerine_de_la_marchande_xyexa = 1
    rempart_de_noirmtin = 1
    sangle_dangoisse_expurge = 1
    serres_en_pierre_rusevent = 1
    suite_de_sombrelune_voracit = 1

legendaries: none

itemIDs: 173087, 173146, 178701, 178711, 178774, 178807, 178811, 178814, 178820, 178840, 178842, 178870, 178950, 179349, 179355, 184660

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Protection Warrior
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    free_revenge = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
If you'd like to resubmit with a complete ticket, following all the instructions re: required information, I'll take a look.
