### ISSUE TITLE
Hekili not suggesting to cancel/break FoF channel during SeF with WoO

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#681]
When playing Kyrian with the ability Weapons of Order (WoO) it's suggest during the cooldown windows that include both WoO and SeF (Storm, Earth and Fire) up, it should be cancelling the channel of FoF (Fists of Fury). This is actually in the SIMC APL by the looks of it with Interrupt=1. And also suggested by the people in Monks discord to perform. But only during WoO and SeF, both must be up. But I think It only counts for SeF in the APL currently.

Even though it appears in the APL, it doesn't seem to be suggesting to break the channel on Hekili. It's always a full channel suggestion.
![unknown](https://user-images.githubusercontent.com/75596862/101988343-e59a8b80-3c90-11eb-9813-4fdfa1eb9ae6.png)
(Full channel of FoF is like 4 seconds. That's roughly around 1gcd after casting FoF (breaking channel)

I've included a few Snapshots:

https://pastebin.com/KEmn2L5w
https://pastebin.com/0rQX2unN
https://pastebin.com/afinww0M

**Comment by Hekili** [comment]
This will be resolved when I provide tick times for Fists of Fury.

**Comment by Smudgiee** [comment]
Thank you (brain freeze with using the word Interrupt for some odd reason when I know it was breaking -.- apologies)

**Comment by Hekili** [comment]
Not a big deal.  Will be doing some testing now.
