### ISSUE TITLE
Customizable Skill Icons

### ISSUE THREAD

**Issue by ValokAsura** [Hekili/hekili#682]
I wonder if we could be allowed to change the icons for the spells to our own textures, similar to the TellMeWhen or WeakAura addons.

For example: In WarriorProtection.lua, dragon_roar's texture setting is "texture = 642418"  I would like to be able to change this to something like "texture = 'Interface/Addons/MyTextures/CoolTexture.tga'"    I tried doing this myself in various ways, but with no luck and I just ended up breaking the addon until I reverted the change. I hoped I could tweak it as I do in TellMeWhen, but no dice.

I really like the addon! I'm just trying it for the first time, and I would really like to use a bunch of custom textures that I've gotten used to. I don't care for some of the default skill icons.

Thank you for your time!

**Comment by Hekili** [comment]
What's the use case for this?  Why would you want to see the wrong icon?

For bonus points, convince me that this feature isn't intended to support an automation bot or something along those lines.

**Comment by ValokAsura** [comment]
Thanks for responding! I don't know if there is a strong use case I can provide you, I can only suggest that people like to customize things to fit their preferred style and interface configuration. I can't tell you why anyone would like to see the wrong icon, but I might be able to explain why they would want to see a preferred icon that fits their needs/style.

Like WeakAuras, I bet not everyone wants to use the standard skill icons for various alerts and skill cooldowns/notification. I prefer, and I assume most players do as well, to use either some of the cool, built-in textures, or their own custom ones that can be found online or created by hand. I like to keep track of my Goblin Glider Kit cooldown (among many other things), but I don't like to use the default "Red bag" icon or an icon of my cloak. Instead I like to use a [custom image](https://w7.pngwing.com/pngs/528/751/png-transparent-black-and-gray-wing-buffalo-wing-icon-hand-painted-black-flying-wings-watercolor-painting-painted-wings.png). I don't like seeing default trinket icons, instead preferring to use something that reflects what it does (Heal, AOE, bubble, blood-theme, poison-theme, ranged, melee, etc.) perhaps something that isn't available as a stock icon. I can do all of these things with WeakAuras, and to a lesser extent, TellMeWhen.

I'm afraid I shall receive no bonus points on the automation front because I don't believe convincing anyone is possible. Automation is already supported by addons like Hekili, Ovale, TellMeWhen, WeakAuras, MaxDps, and the default hotbar (I'm sure there are tons more). I don't know if being able to change the textures will make it any easier than it likely already is. I just thought it would be nice if I could make your addon match the aesthetics of my other addons that allow this customization.

Thanks again for your time! I understand if this isn't something you want to do. It won't make the addon work any better, it'll only allow it to look better for the users. I'll eventually get used to the default icons as I continue using the addon. It just won't be as pretty =)
