### ISSUE TITLE
Keeps recommending potions when I have it disabled under toggle (even when potions are on CD)

### ISSUE THREAD

**Issue by ShaanMeisterr** [Hekili/hekili#684]
I have potions disabled under hekili's toggls ( https://imgur.com/a/ALscd7z ); yet, it keeps recommending my potions during boss fights. 

**To Reproduce**
Start any boss fight (Dungeons/raids/Maw rares), does not happen during target dummy.
Pop Trueshot/wildspirits and it will show potion recommendations, EVEN when potions are on cooldown

**Expected behavior**
Used to not see the potions on my hekili display at all.

**Screenshots**
Here is a screenshot
https://imgur.com/a/FlLvvXZ

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/SCWxLSLg

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/0sDmvFhf

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
I can't replicate this on my end.  If you make a new profile, does it do it with the new profile?

**Comment by ShaanMeisterr** [comment]
Ya, with a new profile, it seems to be fixed.
