### ISSUE TITLE
Rogue Vanish showing up when it should not.

### ISSUE THREAD

**Issue by Cager1974** [Hekili/hekili#685]
The rogue Vanish ability is getting recommended when not in a group.  This is an error, as using it in single player content causes mobs to disengage and return to full health.  This happens even when the player has NPC allies/bodyguards.  

Vanish definitely is a DPS gain in group content as it triggers a number of abilities and buffs.

Thanks!

**Comment by Hekili** [comment]
Use your spec options.  Or submit a complete ticket.
