### ISSUE TITLE
Balance Druid - Convoke the Spirits + Legendary

### ISSUE THREAD

**Issue by Dreamin93** [Hekili/hekili#687]
I'm noticing some weird things going on now that I have the Balance of all things Legendary.

In the opener it never asks me to use 'Convoke the Spirits' - It's also not appearing at all in my rotation - I have both cooldowns and essences ticked.
(It sometimes randomly asks me to use it but i can be off cooldown for ages and the times it wants me to use it seem to be random.)

It also seems to be getting into this weird loop where as soon as I get 40 astral power it want's me to use Starsurge whereas usually you pool to 90 then use 3 of them:
"The way you play this Legendary is pooling over 90 Astral Power as you enter Eclipse, then you gain the buff from Balance of All Things, then you dump x3 Starsurge as to gain insane crit value from Balance of All Things."

build: v9.0.2-1.0.23
level: 60 (60)
class: DRUID
spec: balance

talents: mass_entanglement
    natures_balance
    restoration_affinity
    solstice
    soul_of_the_forest
    stellar_drift
    wild_charge

pvptalents: none

covenant: night_fae

sets: none

gear: chain_of_the_purposebound = 1
    darkmoon_deck_repose = 1
    drape_of_twisted_loyalties = 1
    duskwarder_branch = 1
    flame_of_battle = 1
    fleshcrafters_knife = 1
    freshly_embalmed_jerkin = 1
    risen_monstrosity_cuffs = 1
    sapgorger_belt = 1
    shadebound_greaves = 1
    signet_of_the_false_accuser = 1
    stitchfleshs_misplaced_signet = 1
    umbrahide_treads = 1
    vicious_surge_faceguard = 1
    wicked_bladewing_pauldrons = 1
    winged_hunters_gloves = 1

legendaries: balance_of_all_things = 1

itemIDs: 172254, 172315, 173078, 178699, 178736, 178741, 178744, 178789, 178824, 178858, 179562, 180103, 180106, 180123, 181501, 184757

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Dreamin93** [comment]
I'm doing some more testing, and if I use convoke the Spirits it gets me out of that loop - but Hekili isn't asking me to use it. So it looks like Hekili is expecting to get a bunch of Astral Power from Convoke, but it's not being used so it gets stuck in a loop.

**Comment by Hekili** [comment]
Submit a snapshot when you're having the issue, per the ticket instructions.

**Comment by Dreamin93** [comment]
https://pastebin.com/2rks9Q4i

**Comment by Hekili** [comment]
Thanks, I moved that snapshot to Pastebin.  In the snapshot you provided, Starsurge was cast because you were in Celestial Alignment and the BOAT buff was up.  Which would be intended.

Can you provide a snapshot of the addon recommending Starsurge when it should be pooling AP pre-Celestial Alignment?

**Comment by Hekili** [comment]
Also, could you do a Quick Sim of your character on Raidbots and provide the link?  Thanks for your help investigating this.

**Comment by Hekili** [comment]
Okay, I think I have a fix in place for this.  There was a subtle bug, and then a failure to set a value on the BOAT buffs.  1.0.24-beta2 should fix it.  Could you try it out?

If you see Convoke recommended and then quickly disappearing, let me know.  That would require a tweak to the priority to solve, one that I've already sim tested and shows as equal DPS.

**Comment by Dreamin93** [comment]
Hey, thanks for looking into this - sorry I'd just gone to bed after posting.

I've tested the beta build and it seems to be coming up now (as I can see it in the queue) but disappears as soon as I hit Celestial Alignment. Also once Celestial Alignment is on cooldown, it comes up again but disappears as soon as I enter an eclipse.

Snapshot with cooldown:
https://pastebin.com/xy6JRVVb

Snapshot without cooldown:
https://pastebin.com/40prsuqa

**Comment by Hekili** [comment]
> Also, could you do a Quick Sim of your character on Raidbots and provide the link? Thanks for your help investigating this.

**Comment by Dreamin93** [comment]
Sure, here's the link here:
https://www.raidbots.com/simbot/report/qaJQmdSjfgvqJ5N81py9kz

**Comment by Hekili** [comment]
The issue with it disappearing is that you're actually supposed to hit it simultaneously with CA when you have BOAT.  It wants you to start Convoke with max BOAT stacks.  But they immediately tick down, and the addon moves on as you no longer meet the criteria.

I'm loosening that restriction since it's easy to mess up in actual gameplay.

**Comment by Hekili** [comment]
This should be resolved in 1.0.24, but it still does require that you press Convoke pretty quickly after Celestial Alignment.  If that is still awkward, let me know.
