### ISSUE TITLE
Elemental Shaman with legendary "Echoes of Great Sundering"

### ISSUE THREAD

**Issue by worldskorobei** [Hekili/hekili#688]
Elemental shaman with legendary "Echoes of Great Sundering" has a rotation problem on 2 targets. Addon recommend "Earthquake", instead of alternating with "Earth Shock".

version 9.0.2-1.0.23

**Comment by Hekili** [comment]
Follow the ticket instructions and submit a snapshot from when this is happening.

**Comment by Hekili** [comment]
Closing due to lack of information.
