### ISSUE TITLE
Hekili icons blinking every single opener [GIF]

### ISSUE THREAD

**Issue by Vikerules** [Hekili/hekili#69]
https://i.imgur.com/Bt7SbsR.gifv

same thing during aoe opener, i have the latest version

**Comment by Hekili** [comment]
Can you complete the template from the issue reporting instructions?  It is likely just related to the silly amount of time you spend waiting to regen runes in the Frost DK opener.

**Comment by Hekili** [comment]
I was able to replicate this -- please update to v8.1.0-22 and see if things appear to work better.
