### ISSUE TITLE
Kyrian Paladin - Divine Toll - Holy Power # of Targets

### ISSUE THREAD

**Issue by Morl0ck** [Hekili/hekili#691]
I have noticed this mainly while playing as retribution.

Divine toll is recommended regardless of how many targets it will hit around you.
Divine toll can hit up to 5 targets around the paladin meaning it will generate 5 holy power.

I have seen it where Divine toll is recommended as the next spell even though I have 8 targets around me but only 4/5 holy power.
Meaning that 4 holy power will be wasted.

Is there a way to include the AoE aspect of divine toll into its recommendation to alleviate over capping on holy power?

**Comment by Hekili** [comment]
Sure.  This is the sort of thing one would test by tinkering with sims and verifying that it's worth holding (it probably is).  If you complete sims that show a consistent DPS gain, both the simc maintainers and I would be happy to incorporate those updates.

**Comment by Hekili** [comment]
I could not find a performance increase in my own testing, so I have no planned changes for this at this time.
