### ISSUE TITLE
Stuttering/lag Sub Rogue

### ISSUE THREAD

**Issue by Mkay321** [Hekili/hekili#692]
**Describe the Bug/Issue**
Stuttering/lag during fights (mostly in instances like dungeons, raids, torghast)
Only happens with my sub rogue, I've tried disabling every other addon I have and the issue only happens with Sub Rogue and Hekili.

**To Reproduce**
N/A

**Expected behavior**
No lag/stuttering.

**Screenshots**
N/A

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
build: v9.0.2-1.0.22
level: 60 (60)
class: ROGUE
spec: subtlety

talents: deeper_stratagem
    enveloping_shadows
    premeditation
    secret_technique
    shadow_focus
    shot_in_the_dark
    soothing_darkness

pvptalents: none

covenant: night_fae

sets: none

gear: abyssal_disharmony_breeches = 1
    armguard_of_the_unseen_assailant = 1
    cowled_batwing_cloak = 1
    death_gods_signet = 1
    gloves_of_obscure_rituals = 1
    hood_of_the_hidden_path = 1
    inscrutable_quantum_device = 1
    phial_of_putrefaction = 1
    rainshadow_hauberk = 1
    sinful_aspirants_band = 1
    sinful_aspirants_choker = 1
    sinful_aspirants_dagger = 1
    sinful_aspirants_leather_belt = 1
    sinful_aspirants_leather_boots = 1
    wicked_bladewing_pauldrons = 1

legendaries: none

itemIDs: 175859, 175878, 178293, 178299, 178470, 178691, 178698, 178757, 178771, 178858, 179350, 179355, 180108, 183034, 184657

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Subtlety
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    mfd_waste = true
    priority_rotation = false
    solo_vanish = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/ev24kgNh

**Comment by Hekili** [comment]
You skipped this part:

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Update to the latest version of the addon, then submit a complete ticket if you're still seeing performance issues.
