### ISSUE TITLE
AOE targets confusion

### ISSUE THREAD

**Issue by j3llevdb** [Hekili/hekili#693]
build: v9.0.2-1.0.23
level: 60 (60)
class: DEATHKNIGHT
spec: unholy

talents: army_of_the_damned
    grip_of_the_dead
    infected_claws
    pestilent_pustules
    unholy_blight
    unholy_pact
    wraith_walk

pvptalents: none

covenant: venthyr

sets: none

gear: blue_linen_shirt = 1
    breastplate_of_brutal_dissonance = 1
    drape_of_twisted_loyalties = 1
    fleshfused_circle = 1
    gormshell_greaves = 1
    instructors_divine_bell = 1
    plague_handlers_greathelm = 1
    sabatons_of_the_rushing_juggernaut = 1
    shadowghast_gauntlets = 1
    signet_of_the_false_accuser = 1
    sin_stained_pendant = 1
    spare_meat_hook = 1
    thunderous_echo_vambraces = 1
    ulfius_calming_claymore = 1
    vile_butchers_pauldrons = 1
    waistguard_of_expurged_anguish = 1

legendaries: deaths_certainty = 1

itemIDs: 171414, 178701, 178749, 178751, 178773, 178824, 178827, 178836, 178842, 178869, 180099, 180113, 180123, 184804, 184842, 2577

settings: aoe = 4
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycleDebuff = festering_wound
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

Hey

The feature 'AOE Display: minimum targets' is not working anymore. Eventho i put it on 4 targets minimum, it still suggests the AOE rotation on 3 targets.

Then i tried putting Epidemic on 4 targets only, but then its not showing death coil in stead anymore

Grtz

**Comment by Hekili** [comment]
No, the feature just doesn't work the way you think it does. Read the information you see when you put the mouse over it.

Basically, it controls how many targets, minimum, the addon will pretend you have when your display mode is AOE or the AOE display is shown.

Few specs have an AOE rotation (priority) but just use multitarget abilities based on conditions including target counts.
