### ISSUE TITLE
Havoc Demon Hunter Darkglare Medallion Eyebeam capping fury

### ISSUE THREAD

**Issue by JacksonLawrence1** [Hekili/hekili#694]
**Describe the Bug/Issue**
Currently using a legendary called Darkglare Medallion which has a 20% chance to reset the cooldown of Eye beam entirely. Whenever the item procs it seems to want to cast eye beam immediately after the previous eyebeam so it caps a lot of excess fury at 100%, so it's wasting a lot of the fury. Also I think it might be not spending the excess fury after casting metamorphisis too (because it resets eye beam's cd) but not the main issue.

**To Reproduce**
- Keep using eye beam as a Havoc Demon hunter with Darkglare Medallion equipped
- Wait until Darkglare Medallion ability has worked

**Expected behavior**
I think it should be recommending a few chaos strikes or blade dances to get rid of the excess fury before casting eye beam again

**ISSUE REPORT LINK**
https://pastebin.com/TWFQqz88
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/fejTJ1mb
(I'm not entirely sure how to view the snapshot but it happened right near the end before I finished recording the snapshot)

**Comment by Hekili** [comment]
Have you done any comparison sims to compare the default behavior vs. what you're asking for?

It's possible that it should spend down some Fury, but we'd need to test and prove that.  Delaying usage of Eye Beam means you get fewer uses over the course of a fight, so the opportunity cost could be more than the benefit.

**Comment by JacksonLawrence1** [comment]
Tried to find how I could go about simming different behaviour and tried using AMR, but it's apparently bad and doesn't give accurate results (also not the same APL used in the addon). 

I'm not sure how I could go about altering the APL for raidbots as I couldn't find the option where you could change it, though I think it's just because its unfamiliar territory for me. I'm not sure of another way to do it other than just logging the dps over a time period on a target dummy but it would probably be a bad idea cos of error margins and stuff.

One thing which would be easiest would be to wait until WowAnalyzer has finished optimizing havoc DH, and it should explain whether capping out the fury is a better/worse from some of my logs

**Comment by Hekili** [comment]
If you sim yourself on raidbots, you can get your whole profile from the result and then make edits and compare.  I'm going to close this for now, since there's no data to base a change on at this time.  If new information becomes available, I'll look at it then.
