### ISSUE TITLE
BFA Neck still Shows up in Rotation for Combat Rogues

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#695]
I don't know if this is just over sight but when trying to learn Combat, it still has me using my Heart of the Essence in my rotation?

**Comment by Hekili** [comment]
If it shows you Combat Rogues, welcome back to Warlords of Draenor.

The Heart still shows up only in settings where you can use it.  It'll be filtered back out of the action lists over the next few releases.  In the meantime, you can disable any heart-related actions in /hekili > Abilities or /hekili > Essences.
