### ISSUE TITLE
Table to blacklist mobs that cannot be stunned

### ISSUE THREAD

**Issue by Lockem90** [Hekili/hekili#696]
Would it be possible to add a blacklist for non-boss mobs that cannot be stunned? This would be extremely helpful for rogues running Prey on the weak, as well as adding an option to interrupt with stuns.

Thanks

**Comment by Hekili** [comment]
I don't have any plans to add this; if an external library were created, I'd likely make use of it.  But having folks manually add to this is problematic, and trying to automatically learn what's stunnable is also problematic.
