### ISSUE TITLE
Sub Rogue auto-snapshot during fight

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#697]
Hi! To be honest I don't know what caused the bug. I was DPSing on last boss at Sanguine Depths and my addon for a split second did not know what to suggest and used an auto snapshot function. Here is a link to a snapshot.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/squ2PF2V

**Comment by Hekili** [comment]
I'm going to post a 1.0.25-beta1 that will include more data in snapshots that I'll need to be able to investigate this.

**Comment by Hekili** [comment]
Closing for lack of updates.
