### ISSUE TITLE
Combat Rogue - Kick not being suggested for interrupt against interruptible target.

### ISSUE THREAD

**Issue by Brudoken** [Hekili/hekili#698]
**Describe the Bug/Issue**
A mob casting an interruptible spell, when targeted, is not getting a suggestion to use interrupt using Kick.

**To Reproduce**
Any attackable unit casting an interruptible spell should work.

**Expected behavior**
Hekili should suggest Kick to be cast to interrupt the target's spell.

**Screenshots**
Attached.
![bug report screenshot](https://user-images.githubusercontent.com/76073715/102277193-ed0e9e80-3ef5-11eb-81fe-5786e9cb3f69.jpg)

**Character Data**
build: v9.0.2-1.0.23
level: 60 (60)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    blade_rush
    cheat_death
    prey_on_the_weak
    quick_draw
    vigor

pvptalents: none

covenant: venthyr

sets: none

gear: ardent_sunstar_signet = 1
    bloodoath_signet = 1
    chain_of_the_purposebound = 1
    darkwing_assassins_blade = 1
    digested_interrogators_gaze = 1
    drape_of_twisted_loyalties = 1
    fearless_challengers_leggings = 1
    gloves_of_haunting_fixation = 1
    infinitely_divisible_ooze = 1
    miasmalacquered_jerkin = 1
    phial_of_putrefaction = 1
    precisely_calibrated_chronometer = 1
    primeval_souls_ankleguards = 1
    shadowhirl_waistwrap = 1
    umbrahide_pauldrons = 1
    zinks_subtle_shank = 1

legendaries: celerity = 1

itemIDs: 172319, 178760, 178769, 178771, 178801, 178832, 178871, 179352, 180111, 180123, 181215, 183009, 183019, 183035, 184757, 184797

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Outlaw
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    dirty_gouge = false
    mfd_waste = true
    solo_vanish = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
I need you to take a snapshot following the ticket instructions, when your target is casting but your interrupt is not recommended.

**Comment by Brudoken** [comment]
**Snapshot taken from the Primary Display**
**_Snapshot of Interrupt Display Below_**
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.23
level: 60 (60)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    blade_rush
    cheat_death
    prey_on_the_weak
    quick_draw
    vigor

pvptalents: none

covenant: venthyr

sets: none

gear: ardent_sunstar_signet = 1
    bloodoath_signet = 1
    chain_of_the_purposebound = 1
    darkwing_assassins_blade = 1
    digested_interrogators_gaze = 1
    drape_of_twisted_loyalties = 1
    fearless_challengers_leggings = 1
    gloves_of_haunting_fixation = 1
    infinitely_divisible_ooze = 1
    miasmalacquered_jerkin = 1
    phial_of_putrefaction = 1
    precisely_calibrated_chronometer = 1
    primeval_souls_ankleguards = 1
    shadowhirl_waistwrap = 1
    umbrahide_pauldrons = 1
    zinks_subtle_shank = 1

legendaries: celerity = 1

itemIDs: 172319, 178760, 178769, 178771, 178801, 178832, 178871, 179352, 180111, 180123, 181215, 183009, 183019, 183035, 184757, 184797

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Outlaw
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    dirty_gouge = false
    mfd_waste = true
    solo_vanish = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

New Recommendations for [ Primary ] requested at 20:53:12 ( 427684.23 ); using built-in ( Outlaw ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: combo_points[ 0.00 / 5.00 ], energy[ 150.00 / 150.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Outlaw - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   apply_poison ( precombat - 1 )
        The action (apply_poison) is unusable at (0.00 + 0.00) because requires missing poison.
        Time spent on this action:  0.08ms
        TimeData:Outlaw-precombat-1:apply_poison:0.08:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.04
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #5 in list ( precombat ) is not set or not enabled.  Skipping.
        
        2.   marked_for_death ( precombat - 6 ) - talent [ marked_for_death ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-6:marked_for_death:0.01
        
        3.   stealth ( precombat - 7 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-7:stealth:0.01
        
        4.   roll_the_bones ( precombat - 8 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-8:roll_the_bones:0.01
        
        5.   slice_and_dice ( precombat - 9 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-9:slice_and_dice:0.01
    
    Completed precombat action list [ Outlaw - precombat ].
    
    Processing default action list [ Outlaw - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        6.   stealth ( default - 1 )
        The action (stealth) is unusable at (0.00 + 0.00) because cannot stealth in combat.
        Time spent on this action:  0.04ms
        TimeData:Outlaw-default-1:stealth:0.04:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.02
        
        7.   variable ( default - 2 )
         - variable.rtb_reroll will check this script entry ( Outlaw:default:2 )
        rtb_buffs[0.00] < 2 & ( buff.buried_treasure.up[false] | buff.grand_melee.up[false] | buff.true_bearing.up[false] )
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-2:variable:0.02:Post-TTR and Essential:0.01
        
        8.   variable ( default - 3 )
         - variable.ambush_condition will check this script entry ( Outlaw:default:3 )
        combo_points.deficit[5.00] >= 2 + buff.broadside.up[false] & energy.current[150.00] >= 50
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-3:variable:0.02:Post-TTR and Essential:0.01
        
        9.   variable ( default - 4 )
         - variable.blade_flurry_sync will check this script entry ( Outlaw:default:4 )
        spell_targets.blade_flurry[1.00] < 2 & raid_event.adds.in[3600.00] > 20 | buff.blade_flurry.up[false]
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-4:variable:0.02:Post-TTR and Essential:0.01
        
        10.  call_action_list ( default - 5 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - stealthed.all[false]
        
        11.  call_action_list ( default - 6 )
        There is no criteria for cds.
        Action list (cds) was found.
        + cds
        Current recommendation was NO ACTION at +60.00s.
        
        12.  vanish ( cds - 1 )
        The action is not ready ( 120.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-1:vanish:0.01
        
        13.  flagellation ( cds - 2 )
        The action (flagellation) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cds ) called from ( Outlaw:default:6 ) would PASS at 0.00.
        NONE
         - this entry has no criteria to test.
        Action chosen:  flagellation at 0.00!
        Returned from list (cds), current recommendation is flagellation (+0.00).
        - cds
        The recommended action (flagellation) is ready in less than 0.2s; exiting list (default).
    
    Completed default action list [ Outlaw - default ].
    Recommendation is flagellation at 0.00 + 0.00.
    Recommendation #1 is flagellation at 0.00s (0.00s).
    Used 1.00ms of CPU on 1 prediction(s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.00, Casting: 0.00 ).

    Resources: combo_points[ 0.00 / 5.00 ], energy[ 150.00 / 150.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Outlaw - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   apply_poison ( precombat - 1 )
        The action (apply_poison) is unusable at (0.00 + 1.00) because requires missing poison.
        Time spent on this action:  0.06ms
        TimeData:Outlaw-precombat-1:apply_poison:0.06:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.03
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #5 in list ( precombat ) is not set or not enabled.  Skipping.
        
        2.   marked_for_death ( precombat - 6 ) - talent [ marked_for_death ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-6:marked_for_death:0.01
        
        3.   stealth ( precombat - 7 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-7:stealth:0.01
        
        4.   roll_the_bones ( precombat - 8 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-8:roll_the_bones:0.01
        
        5.   slice_and_dice ( precombat - 9 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-9:slice_and_dice:0.01
    
    Completed precombat action list [ Outlaw - precombat ].
    
    Processing default action list [ Outlaw - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        6.   stealth ( default - 1 )
        The action (stealth) is unusable at (0.00 + 1.00) because cannot stealth in combat.
        Time spent on this action:  0.04ms
        TimeData:Outlaw-default-1:stealth:0.04:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.01
        
        7.   variable ( default - 2 )
         - variable.rtb_reroll will check this script entry ( Outlaw:default:2 )
        rtb_buffs[0.00] < 2 & ( buff.buried_treasure.up[false] | buff.grand_melee.up[false] | buff.true_bearing.up[false] )
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-2:variable:0.02:Post-TTR and Essential:0.01
        
        8.   variable ( default - 3 )
         - variable.ambush_condition will check this script entry ( Outlaw:default:3 )
        combo_points.deficit[5.00] >= 2 + buff.broadside.up[false] & energy.current[150.00] >= 50
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-3:variable:0.02:Post-TTR and Essential:0.01
        
        9.   variable ( default - 4 )
         - variable.blade_flurry_sync will check this script entry ( Outlaw:default:4 )
        spell_targets.blade_flurry[1.00] < 2 & raid_event.adds.in[3600.00] > 20 | buff.blade_flurry.up[false]
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-4:variable:0.02:Post-TTR and Essential:0.01
        
        10.  call_action_list ( default - 5 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - stealthed.all[false]
        
        11.  call_action_list ( default - 6 )
        There is no criteria for cds.
        Action list (cds) was found.
        + cds
        Current recommendation was NO ACTION at +60.00s.
        
        12.  vanish ( cds - 1 )
        The action is not ready ( 120.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-1:vanish:0.01
        
        13.  flagellation ( cds - 2 )
        The action (flagellation) is unusable at (0.00 + 5.00) because flagellation already active.
        Time spent on this action:  0.05ms
        TimeData:Outlaw-cds-2:flagellation:0.05:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.02
        
        14.  flagellation_cleanse ( cds - 3 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-3:flagellation_cleanse:0.01
        
        15.  adrenaline_rush ( cds - 4 )
        The action (adrenaline_rush) is usable at (0.00 + 1.00).
         - the action is ready before the current recommendation (at +1.00 vs. +60.00).
        List ( cds ) called from ( Outlaw:default:6 ) would PASS at 1.00.
        NONE
         - this entry's criteria PASSES: ! buff.adrenaline_rush.up[false] & ( ! cooldown.killing_spree.up[true] | ! talent.killing_spree.enabled[false] )
        Action chosen:  adrenaline_rush at 1.00!
        Time spent on this action:  0.23ms
        TimeData:Outlaw-cds-4:adrenaline_rush:0.23:Post-TTR and Essential:0.08:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.02:Pre-Recheck:0.05:Post Recheck:0.00:Action Stored:0.04
        
        16.  shadowmeld ( cds - 13 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Outlaw-cds-13:shadowmeld:0.02
        
        17.  potion ( cds - 15 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Outlaw-cds-15:potion:0.02
        
        18.  blood_fury ( cds - 16 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Outlaw-cds-16:blood_fury:0.02
        
        19.  berserking ( cds - 17 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Outlaw-cds-17:berserking:0.02
        
        20.  fireblood ( cds - 18 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Outlaw-cds-18:fireblood:0.02
        
        21.  ancestral_call ( cds - 19 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Outlaw-cds-19:ancestral_call:0.02
        
        22.  use_items ( cds - 20 )
        Criteria for ??? FAIL at +0.00 - buff.bloodlust.react[0.00] | fight_remains[3600.00] <= 20 | combo_points.deficit[5.00] <= 2
        Returned from list (cds), current recommendation is adrenaline_rush (+1.00).
        - cds
        
        23.  run_action_list ( default - 7 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - combo_points.current[0.00] >= cp_max_spend[5.00] - buff.broadside.up[false] - ( buff.opportunity.up[false] * talent.quick_draw.enabled[true] ) | combo_points.current[0.00] = animacharged_cp[5.00]
        
        24.  call_action_list ( default - 8 )
        There is no criteria for build.
        Action list (build) was found.
        + build
        Current recommendation was adrenaline_rush at +1.00s.
        Returned from list (build), current recommendation is adrenaline_rush (+1.00).
        - build
    
    Completed default action list [ Outlaw - default ].
    Recommendation is adrenaline_rush at 0.00 + 1.00.
    Recommendation #2 is adrenaline_rush at 1.00s (1.00s).
    Used 2.92ms of CPU on 2 prediction(s).

RECOMMENDATION #3 ( Offset: 1.00, GCD: 0.00, Casting: 0.00 ).

    Resources: combo_points[ 0.00 / 5.00 ], energy[ 150.00 / 200.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Outlaw - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   apply_poison ( precombat - 1 )
        The action (apply_poison) is unusable at (1.00 + 0.00) because requires missing poison.
        Time spent on this action:  0.06ms
        TimeData:Outlaw-precombat-1:apply_poison:0.06:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.03
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #5 in list ( precombat ) is not set or not enabled.  Skipping.
        
        2.   marked_for_death ( precombat - 6 ) - talent [ marked_for_death ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-6:marked_for_death:0.01
        
        3.   stealth ( precombat - 7 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-7:stealth:0.01
        
        4.   roll_the_bones ( precombat - 8 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-8:roll_the_bones:0.01
        
        5.   slice_and_dice ( precombat - 9 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-9:slice_and_dice:0.01
    
    Completed precombat action list [ Outlaw - precombat ].
    
    Processing default action list [ Outlaw - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        6.   stealth ( default - 1 )
        The action (stealth) is unusable at (1.00 + 0.00) because cannot stealth in combat.
        Time spent on this action:  0.04ms
        TimeData:Outlaw-default-1:stealth:0.04:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.02
        
        7.   variable ( default - 2 )
         - variable.rtb_reroll will check this script entry ( Outlaw:default:2 )
        rtb_buffs[0.00] < 2 & ( buff.buried_treasure.up[false] | buff.grand_melee.up[false] | buff.true_bearing.up[false] )
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-2:variable:0.02:Post-TTR and Essential:0.01
        
        8.   variable ( default - 3 )
         - variable.ambush_condition will check this script entry ( Outlaw:default:3 )
        combo_points.deficit[5.00] >= 2 + buff.broadside.up[false] & energy.current[150.00] >= 50
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-3:variable:0.02:Post-TTR and Essential:0.01
        
        9.   variable ( default - 4 )
         - variable.blade_flurry_sync will check this script entry ( Outlaw:default:4 )
        spell_targets.blade_flurry[1.00] < 2 & raid_event.adds.in[3600.00] > 20 | buff.blade_flurry.up[false]
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-4:variable:0.02:Post-TTR and Essential:0.01
        
        10.  call_action_list ( default - 5 )
        Time-sensitive Criteria FAIL at +1.00 with no valid rechecks - stealthed.all[false]
        
        11.  call_action_list ( default - 6 )
        There is no criteria for cds.
        Action list (cds) was found.
        + cds
        Current recommendation was NO ACTION at +60.00s.
        
        12.  vanish ( cds - 1 )
        The action is not ready ( 120.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-1:vanish:0.01
        
        13.  flagellation ( cds - 2 )
        The action (flagellation) is unusable at (1.00 + 4.00) because flagellation already active.
        Time spent on this action:  0.05ms
        TimeData:Outlaw-cds-2:flagellation:0.05:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.02
        
        14.  flagellation_cleanse ( cds - 3 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-3:flagellation_cleanse:0.01
        
        15.  adrenaline_rush ( cds - 4 )
        The action is not ready ( 180.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-4:adrenaline_rush:0.01
        
        16.  roll_the_bones ( cds - 5 )
        The action (roll_the_bones) is usable at (1.00 + 0.00) with cost of 25 energy.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cds ) called from ( Outlaw:default:6 ) would PASS at 0.00.
        NONE
         - this entry's criteria PASSES: buff.roll_the_bones.remains[0.00] <= 3 | variable.rtb_reroll[false]
        Action chosen:  roll_the_bones at 0.00!
        Returned from list (cds), current recommendation is roll_the_bones (+0.00).
        - cds
        The recommended action (roll_the_bones) is ready in less than 0.2s; exiting list (default).
    
    Completed default action list [ Outlaw - default ].
    Recommendation is roll_the_bones at 1.00 + 0.00.
    Recommendation #3 is roll_the_bones at 0.00s (1.00s).
    Time spent generating recommendations:  4.00ms

**Snapshot taken from the Interrupt Display**
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.23
level: 60 (60)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    blade_rush
    cheat_death
    prey_on_the_weak
    quick_draw
    vigor

pvptalents: none

covenant: venthyr

sets: none

gear: ardent_sunstar_signet = 1
    bloodoath_signet = 1
    chain_of_the_purposebound = 1
    darkwing_assassins_blade = 1
    digested_interrogators_gaze = 1
    drape_of_twisted_loyalties = 1
    fearless_challengers_leggings = 1
    gloves_of_haunting_fixation = 1
    infinitely_divisible_ooze = 1
    miasmalacquered_jerkin = 1
    phial_of_putrefaction = 1
    precisely_calibrated_chronometer = 1
    primeval_souls_ankleguards = 1
    shadowhirl_waistwrap = 1
    umbrahide_pauldrons = 1
    zinks_subtle_shank = 1

legendaries: celerity = 1

itemIDs: 172319, 178760, 178769, 178771, 178801, 178832, 178871, 179352, 180111, 180123, 181215, 183009, 183019, 183035, 184757, 184797

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Outlaw
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    dirty_gouge = false
    mfd_waste = true
    solo_vanish = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

New Recommendations for [ Defensives ] requested at 20:53:12 ( 427684.23 ); using built-in ( Outlaw ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: combo_points[ 0.00 / 5.00 ], energy[ 150.00 / 150.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Outlaw - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   apply_poison ( precombat - 1 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-1:apply_poison:0.01
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #5 in list ( precombat ) is not set or not enabled.  Skipping.
        
        2.   marked_for_death ( precombat - 6 ) - talent [ marked_for_death ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-6:marked_for_death:0.01
        
        3.   stealth ( precombat - 7 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-7:stealth:0.01
        
        4.   roll_the_bones ( precombat - 8 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-8:roll_the_bones:0.01
        
        5.   slice_and_dice ( precombat - 9 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-precombat-9:slice_and_dice:0.01
    
    Completed precombat action list [ Outlaw - precombat ].
    
    Processing default action list [ Outlaw - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        6.   stealth ( default - 1 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-default-1:stealth:0.01
        
        7.   variable ( default - 2 )
         - variable.rtb_reroll will check this script entry ( Outlaw:default:2 )
        rtb_buffs[0.00] < 2 & ( buff.buried_treasure.up[false] | buff.grand_melee.up[false] | buff.true_bearing.up[false] )
        Time spent on this action:  0.03ms
        TimeData:Outlaw-default-2:variable:0.03:Post-TTR and Essential:0.02
        
        8.   variable ( default - 3 )
         - variable.ambush_condition will check this script entry ( Outlaw:default:3 )
        combo_points.deficit[5.00] >= 2 + buff.broadside.up[false] & energy.current[150.00] >= 50
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-3:variable:0.02:Post-TTR and Essential:0.01
        
        9.   variable ( default - 4 )
         - variable.blade_flurry_sync will check this script entry ( Outlaw:default:4 )
        spell_targets.blade_flurry[1.00] < 2 & raid_event.adds.in[3600.00] > 20 | buff.blade_flurry.up[false]
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-4:variable:0.02:Post-TTR and Essential:0.01
        
        10.  call_action_list ( default - 5 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - stealthed.all[false]
        
        11.  call_action_list ( default - 6 )
        There is no criteria for cds.
        Action list (cds) was found.
        + cds
        Current recommendation was NO ACTION at +60.00s.
        
        12.  vanish ( cds - 1 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-1:vanish:0.01
        
        13.  flagellation ( cds - 2 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-2:flagellation:0.01
        
        14.  flagellation_cleanse ( cds - 3 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-3:flagellation_cleanse:0.01
        
        15.  adrenaline_rush ( cds - 4 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-4:adrenaline_rush:0.01
        
        16.  roll_the_bones ( cds - 5 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-5:roll_the_bones:0.01
        
        17.  marked_for_death ( cds - 6 ) - talent [ marked_for_death ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-6:marked_for_death:0.01
        
        18.  marked_for_death ( cds - 7 ) - talent [ marked_for_death ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-7:marked_for_death:0.01
        
        19.  blade_flurry ( cds - 8 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-8:blade_flurry:0.01
        
        20.  ghostly_strike ( cds - 9 ) - talent [ ghostly_strike ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-9:ghostly_strike:0.01
        
        21.  killing_spree ( cds - 10 ) - talent [ killing_spree ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-10:killing_spree:0.01
        
        22.  blade_rush ( cds - 11 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-11:blade_rush:0.01
        
        23.  dreadblades ( cds - 12 ) - talent [ dreadblades ] missing
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-12:dreadblades:0.01
        
        24.  shadowmeld ( cds - 13 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-13:shadowmeld:0.01
        
        25.  sepsis ( cds - 14 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-14:sepsis:0.01
        
        26.  potion ( cds - 15 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-15:potion:0.01
        
        27.  blood_fury ( cds - 16 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-16:blood_fury:0.01
        
        28.  berserking ( cds - 17 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-17:berserking:0.01
        
        29.  fireblood ( cds - 18 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-18:fireblood:0.01
        
        30.  ancestral_call ( cds - 19 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-cds-19:ancestral_call:0.01
        
        31.  use_items ( cds - 20 )
        Criteria for ??? FAIL at +0.00 - buff.bloodlust.react[0.00] | fight_remains[3600.00] <= 20 | combo_points.deficit[5.00] <= 2
        Returned from list (cds), current recommendation is NO ACTION (+60.00).
        - cds
        
        32.  run_action_list ( default - 7 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - combo_points.current[0.00] >= cp_max_spend[5.00] - buff.broadside.up[false] - ( buff.opportunity.up[false] * talent.quick_draw.enabled[true] ) | combo_points.current[0.00] = animacharged_cp[5.00]
        
        33.  call_action_list ( default - 8 )
        There is no criteria for build.
        Action list (build) was found.
        + build
        Current recommendation was NO ACTION at +60.00s.
        
        34.  shiv ( build - 1 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-build-1:shiv:0.01
        
        35.  echoing_reprimand ( build - 2 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-build-2:echoing_reprimand:0.01
        
        36.  serrated_bone_spike ( build - 3 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-build-3:serrated_bone_spike:0.01
        
        37.  pistol_shot ( build - 4 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-build-4:pistol_shot:0.01
        
        38.  pistol_shot ( build - 5 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-build-5:pistol_shot:0.01
        
        39.  sinister_strike ( build - 6 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-build-6:sinister_strike:0.01
        
        40.  gouge ( build - 7 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Outlaw-build-7:gouge:0.01
        Returned from list (build), current recommendation is NO ACTION (+60.00).
        - build
        
        41.  arcane_torrent ( default - 9 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Outlaw-default-9:arcane_torrent:0.02
        
        42.  arcane_pulse ( default - 10 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-default-10:arcane_pulse:0.01
        
        43.  lights_judgment ( default - 11 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-default-11:lights_judgment:0.01
        
        44.  bag_of_tricks ( default - 12 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Outlaw-default-12:bag_of_tricks:0.01
    
    Completed default action list [ Outlaw - default ].
    Recommendation is NO ACTION at 0.00 + 60.00.
    Recommendation #1 is NO ACTION at 60.00s (60.00s).
    Time spent generating recommendations:  1.51ms

**Comment by Hekili** [comment]
I'm guessing that you imported your own priority, instead of using the default.  In my default, Kick is the first action in the default action list.  Kick is not included in yours at all.
