### ISSUE TITLE
Frostwyrm's Fury no longer being suggested.

### ISSUE THREAD

**Issue by Imahorn** [Hekili/hekili#699]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Frostwyrm's Fury is no longer being recommended.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
In either the Primary window or my AOE window, I expect to see it recommended when **up.**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.2-1.0.23
level: 60 (60)
class: DEATHKNIGHT
spec: frost

talents: avalanche
    cold_heart
    death_pact
    deaths_reach
    gathering_storm
    murderous_efficiency
    obliteration

pvptalents: none

covenant: kyrian

sets: none

gear: anima_field_emitter = 1
    blighted_margraves_cloak = 1
    breastplate_of_brutal_dissonance = 1
    charm_of_eternal_winter = 1
    emberscarred_girdle = 1
    entwined_gorger_tendril = 1
    galvanized_oxxein_legguards = 1
    guilewind_stone_talons = 1
    klontzas_precise_pummeler = 1
    pit_fighters_wristguards = 1
    sabatons_of_the_rushing_juggernaut = 1
    shadowghast_helm = 1
    signet_of_the_false_accuser = 1
    vile_butchers_pauldrons = 1
    viscera_of_coalesced_hatred = 1

legendaries: biting_cold = 1

itemIDs: 171415, 178749, 178755, 178800, 178807, 178808, 178824, 178836, 178840, 178848, 180099, 180118, 181202, 183040, 184800

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Frost DK
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    bos_rp = 50

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = true

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.23
level: 60 (60)
class: DEATHKNIGHT
spec: frost

talents: avalanche
    cold_heart
    death_pact
    deaths_reach
    gathering_storm
    murderous_efficiency
    obliteration

pvptalents: none

covenant: kyrian

sets: none

gear: anima_field_emitter = 1
    blighted_margraves_cloak = 1
    breastplate_of_brutal_dissonance = 1
    charm_of_eternal_winter = 1
    emberscarred_girdle = 1
    entwined_gorger_tendril = 1
    galvanized_oxxein_legguards = 1
    guilewind_stone_talons = 1
    klontzas_precise_pummeler = 1
    pit_fighters_wristguards = 1
    sabatons_of_the_rushing_juggernaut = 1
    shadowghast_helm = 1
    signet_of_the_false_accuser = 1
    vile_butchers_pauldrons = 1
    viscera_of_coalesced_hatred = 1

legendaries: biting_cold = 1

itemIDs: 171415, 178749, 178755, 178800, 178807, 178808, 178824, 178836, 178840, 178848, 180099, 180118, 181202, 183040, 184800

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Frost DK
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    bos_rp = 50

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = true

New Recommendations for [ Cooldowns ] requested at 12:58:54 ( 249271.29 ); using built-in ( Frost DK ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: runes[ 6.00 / 6.00 ], runic_power[ 0.00 / 100.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Frost DK - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
    
    Completed precombat action list [ Frost DK - precombat ].
    
    Processing default action list [ Frost DK - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   mind_freeze ( default - 1 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-default-1:mind_freeze:0.02
        
        2.   howling_blast ( default - 2 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-default-2:howling_blast:0.02
        
        3.   glacial_advance ( default - 3 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-default-3:glacial_advance:0.02
        
        4.   frost_strike ( default - 4 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-default-4:frost_strike:0.02
        
        5.   call_action_list ( default - 5 )
        There is no criteria for covenants.
        Action list (covenants) was found.
        + covenants
        Current recommendation was NO ACTION at +60.00s.
        
        6.   deaths_due ( covenants - 1 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-covenants-1:deaths_due:0.02
        
        7.   swarming_mist ( covenants - 2 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-covenants-2:swarming_mist:0.02
        
        8.   swarming_mist ( covenants - 3 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Frost DK-covenants-3:swarming_mist:0.01
        
        9.   swarming_mist ( covenants - 4 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Frost DK-covenants-4:swarming_mist:0.01
        
        10.  abomination_limb ( covenants - 5 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-covenants-5:abomination_limb:0.02
        
        11.  abomination_limb ( covenants - 6 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Frost DK-covenants-6:abomination_limb:0.01
        
        12.  shackle_the_unworthy ( covenants - 7 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-covenants-7:shackle_the_unworthy:0.02
        
        13.  shackle_the_unworthy ( covenants - 8 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-covenants-8:shackle_the_unworthy:0.01
        Returned from list (covenants), current recommendation is NO ACTION (+60.00).
        - covenants
        
        14.  call_action_list ( default - 6 )
        There is no criteria for cooldowns.
        Action list (cooldowns) was found.
        + cooldowns
        Current recommendation was NO ACTION at +60.00s.
        
        15.  use_items ( cooldowns - 1 )
        Criteria for ??? PASS at +0.00 - cooldown.pillar_of_frost.ready[false] | cooldown.pillar_of_frost.remains[60.00] > 20
        + cooldowns, items
        Current recommendation was NO ACTION at +60.00s.
        Returned from Use Items; current recommendation is NO ACTION (+60.00).
        - items
        
        16.  potion ( cooldowns - 2 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-cooldowns-2:potion:0.01
        
        17.  blood_fury ( cooldowns - 3 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-3:blood_fury:0.02
        
        18.  berserking ( cooldowns - 4 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-4:berserking:0.02
        
        19.  arcane_pulse ( cooldowns - 5 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-5:arcane_pulse:0.02
        
        20.  lights_judgment ( cooldowns - 6 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-6:lights_judgment:0.02
        
        21.  ancestral_call ( cooldowns - 7 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-7:ancestral_call:0.02
        
        22.  fireblood ( cooldowns - 8 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-8:fireblood:0.02
        
        23.  bag_of_tricks ( cooldowns - 9 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-9:bag_of_tricks:0.02
        
        24.  empower_rune_weapon ( cooldowns - 10 )
        The action (empower_rune_weapon) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cooldowns ) called from ( Frost DK:default:6 ) would PASS at 0.00.
        NONE
         - this entry's criteria FAILS: talent.obliteration.enabled[true] & ( cooldown.pillar_of_frost.ready[false] & rune.time_to_5[0.00] > gcd.execute[0.00] & runic_power.deficit[100.00] >= 10 | buff.pillar_of_frost.up[false] & rune.time_to_5[0.00] > gcd.execute[0.00] ) | fight_remains[3600.00] < 20
        There were no recheck events to check.
        Time spent on this action:  0.44ms
        TimeData:Frost DK-cooldowns-10:empower_rune_weapon:0.44:Post-TTR and Essential:0.17:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.01:Post Stack:0.02:Pre-Script:0.00:Post-Script:0.02:Pre-Recheck:0.17:Post-Recheck Times:0.01:Post Recheck:0.01
        
        25.  empower_rune_weapon ( cooldowns - 11 )
        The action (empower_rune_weapon) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cooldowns ) called from ( Frost DK:default:6 ) would PASS at 0.00.
        NONE
         - this entry's criteria FAILS: talent.breath_of_sindragosa.enabled[false] & runic_power.deficit[100.00] > 40 & rune.time_to_5[0.00] > gcd.execute[0.00] & ( buff.breath_of_sindragosa.up[false] | fight_remains[3600.00] < 20 )
        There were no recheck events to check.
        Time spent on this action:  0.19ms
        TimeData:Frost DK-cooldowns-11:empower_rune_weapon:0.19:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.11:Post-Recheck Times:0.01:Post Recheck:0.00
        
        26.  empower_rune_weapon ( cooldowns - 12 )
        The action (empower_rune_weapon) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cooldowns ) called from ( Frost DK:default:6 ) would PASS at 0.00.
        NONE
         - this entry's criteria FAILS: talent.icecap.enabled[false] & rune.current[6.00] < 3
        There were no recheck events to check.
        Time spent on this action:  0.12ms
        TimeData:Frost DK-cooldowns-12:empower_rune_weapon:0.12:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.04:Post-Recheck Times:0.00:Post Recheck:0.00
        
        27.  pillar_of_frost ( cooldowns - 13 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-13:pillar_of_frost:0.02
        
        28.  pillar_of_frost ( cooldowns - 14 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-cooldowns-14:pillar_of_frost:0.01
        
        29.  pillar_of_frost ( cooldowns - 15 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-cooldowns-15:pillar_of_frost:0.01
        
        30.  breath_of_sindragosa ( cooldowns - 16 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-16:breath_of_sindragosa:0.02
        
        31.  frostwyrms_fury ( cooldowns - 17 ) - ability disabled ( boss-only )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-17:frostwyrms_fury:0.02
        
        32.  frostwyrms_fury ( cooldowns - 18 ) - ability disabled ( boss-only )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-cooldowns-18:frostwyrms_fury:0.01
        
        33.  frostwyrms_fury ( cooldowns - 19 ) - ability disabled ( boss-only )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-cooldowns-19:frostwyrms_fury:0.01
        
        34.  hypothermic_presence ( cooldowns - 20 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-20:hypothermic_presence:0.02
        
        35.  raise_dead ( cooldowns - 21 )
        The action (raise_dead) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cooldowns ) called from ( Frost DK:default:6 ) would PASS at 0.00.
        NONE
         - this entry's criteria FAILS: buff.pillar_of_frost.up[false]
        There were no recheck events to check.
        Time spent on this action:  0.10ms
        TimeData:Frost DK-cooldowns-21:raise_dead:0.10:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.01:Post-Recheck Times:0.00:Post Recheck:0.00
        
        36.  sacrificial_pact ( cooldowns - 22 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 18.10 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-22:sacrificial_pact:0.02
        
        37.  death_and_decay ( cooldowns - 23 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-cooldowns-23:death_and_decay:0.02
        Returned from list (cooldowns), current recommendation is NO ACTION (+60.00).
        - cooldowns
        
        38.  call_action_list ( default - 7 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - talent.cold_heart.enabled[true] & ( buff.cold_heart.stack[20.00] >= 10 & ( debuff.razorice.stack[0.00] = 5 | ! death_knight.runeforge.razorice[true] ) | fight_remains[3600.00] <= gcd.execute[0.00] )
        
        39.  run_action_list ( default - 8 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - buff.breath_of_sindragosa.up[false]
        
        40.  run_action_list ( default - 9 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - talent.breath_of_sindragosa.enabled[false] & ( cooldown.breath_of_sindragosa.remains[0.00] < 10 )
        
        41.  run_action_list ( default - 10 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - buff.pillar_of_frost.up[false] & talent.obliteration.enabled[true]
        
        42.  run_action_list ( default - 11 )
        Time-sensitive Criteria FAIL at +0.00 with no valid rechecks - talent.obliteration.enabled[true] & cooldown.pillar_of_frost.remains[60.00] < 10
        
        43.  run_action_list ( default - 12 )
        Criteria for aoe FAIL at +0.00 - active_enemies[1.00] >= 2
        
        44.  call_action_list ( default - 13 )
        There is no criteria for standard.
        Action list (standard) was found.
        + standard
        Current recommendation was NO ACTION at +60.00s.
        
        45.  remorseless_winter ( standard - 1 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-standard-1:remorseless_winter:0.02
        
        46.  glacial_advance ( standard - 2 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Frost DK-standard-2:glacial_advance:0.01
        
        47.  frost_strike ( standard - 3 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-standard-3:frost_strike:0.01
        
        48.  frost_strike ( standard - 4 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-standard-4:frost_strike:0.01
        
        49.  howling_blast ( standard - 5 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-standard-5:howling_blast:0.01
        
        50.  obliterate ( standard - 6 ) - ability disabled ( display )
        Time spent on this action:  0.02ms
        TimeData:Frost DK-standard-6:obliterate:0.02
        
        51.  frost_strike ( standard - 7 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-standard-7:frost_strike:0.01
        
        52.  obliterate ( standard - 8 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-standard-8:obliterate:0.01
        
        53.  frost_strike ( standard - 9 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Frost DK-standard-9:frost_strike:0.01
        
        54.  horn_of_winter ( standard - 10 ) - talent [ horn_of_winter ] missing
        Time spent on this action:  0.02ms
        TimeData:Frost DK-standard-10:horn_of_winter:0.02
        
        55.  arcane_torrent ( standard - 11 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Frost DK-standard-11:arcane_torrent:0.02
        Returned from list (standard), current recommendation is NO ACTION (+60.00).
        - standard
    
    Completed default action list [ Frost DK - default ].
    Recommendation is NO ACTION at 0.00 + 60.00.
    Recommendation #1 is NO ACTION at 60.00s (60.00s).
    Time spent generating recommendations:  2.91ms

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
You have to post a snapshot taken when you thought it should recommend Frostwyrm's Fury but didn't.

> 2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
> PUT SNAPSHOT LINK HERE:

**Comment by Imahorn** [comment]
A snapshot is impossible as it never is suggested when in my Frost Spec and furthermore, up until I added a tanking profile, it was always and accurately suggested.  Please respond with something more concrete.

**Comment by Hekili** [comment]
> You have to post a snapshot taken when you thought it should recommend Frostwyrm's Fury but didn't.

**Comment by Imahorn** [comment]
I guess my expectations are too ambitious.  I assume you wrote the code.  I further assume you provide all the updates and finally I assume that you have kept release history.  You should assume that I have no idea when it should be recommended beyond the icey veins recommendation and I believe you use the same source.

I apologize for the inconvenience.  I would suggest that a current primer be produced on how to fully use all of the features contained within the add on.  It is actually quite helpful and extremely accurate but for the sudden changes that seemingly come out of nowhere.  If one exist beyond the outdated material I have located thus far, please provide a link.

If I can get a snapshot of when it should proc (maybe it easier than it appears) I will update both of my threads.

Again, thanks.

**Comment by Hekili** [comment]
You should be able to provide a snapshot of this pretty quickly vs. a target dummy.  Just start the fight, pop cooldowns, and if it seems like you should've cast Frostwyrm's Fury but it wasn't recommended, press ALT-SHIFT-P twice (once to pause, once to unpause).  Then grab the info from /hekili > Snapshots and put it on Pastebin and put the link here.

GitHub has the full commit history and the priority lists available for review.

**Comment by Hekili** [comment]
Closed for lack of information.  (I did my own quick testing, and Frostwyrm's Fury was recommended with your talents selected.)

![image](https://user-images.githubusercontent.com/9438134/102383756-e6396780-3f99-11eb-837e-6cd3980fdb5a.png)

**Comment by Imahorn** [comment]
Like I said, or think I said, I saw in the code it was in the action list for Oblteration but, still not being recommended.  

Please don’t be so hasty in closing ticket, I told you I would make an attempt at providing you a snapshot.

**Comment by Imahorn** [comment]
In addition, in Obliteration, you should use it every time it is up unlike Breath of Syndragosa when you should use after either Pillar of Frost or Chains of Ice.

**Comment by Imahorn** [comment]
Oh I see the the buff condition, Pillar of Frost set False.  Sorry
