### ISSUE TITLE
Hekili\State.lua:573: attempt to index field '?'

### ISSUE THREAD

**Issue by BaturalNoobs** [Hekili/hekili#7]
First off, thank you so much for all your hard work on Hekili. It has helped me learn so many specs I sucked at before. I really appreciate your awesome addon!

I'm running into this error:

```
Message: Interface\AddOns\Hekili\State.lua:573: attempt to index field '?' (a nil value)
Time: 02/24/18 13:39:17
Count: 223
Stack: Interface\AddOns\Hekili\State.lua:573: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\Hekili\State.lua:573: in function <Interface\AddOns\Hekili\State.lua:540>
Interface\AddOns\Hekili\State.lua:583: in function `removeBuff'
Interface\AddOns\Hekili\Classes\Warrior.lua:759: in function `handler'
Interface\AddOns\Hekili\Classes.lua:621: in function `runHandler'
Interface\AddOns\Hekili\Core.lua:1691: in function `ProcessHooks'
Interface\AddOns\Hekili\UI.lua:1025: in function <Interface\AddOns\Hekili\UI.lua:634>

Locals: 
```

A few notes:

- Hekili 7.3.5.23
- No other addons enabled
- Fresh WTF folder
- 110 Arms Warrior (no errors when I switch to Fury)

Any ideas of things I can try?

Thanks again and keep up the great work?

**Comment by Hekili** [comment]
Download an alpha version of the addon from CurseForge.  This error doesn't match up with the current alpha version, and some Warrior aura bugs were fixed since the last release.
