### ISSUE TITLE
Frostbrand constantly prioritized for enhance shaman

### ISSUE THREAD

**Issue by Fynnconceivable** [Hekili/hekili#70]
**BEFORE SUBMITTING AN ISSUE:**

1.  Version 8.1.0-23 (downloaded 2/22/19 shortly before 11 PM CST)

2.  "Frostbrand wanting to be constantly applied" issue #67 is closed and doesn't appear to have the same root cause.

**Describe the Bug/Issue**
With a PP build (see details below), Frostbrand wants to be applied almost constantly. Occasionally LL or RB or another proc take priority, but usually FB is up again right after casting.

**To Reproduce**
See Fynn-Korialstrasz for any gear/build details.

Azerite traits: 3 PP, 2 NH, 1 RS
Talents: HH, TM, Hailstorm, Sundering, ES

Start fight on a training dummy. After opening, FB will be priority #1 most of the time.

**Expected behavior**
After opening and first application, FB should only be at the top of the queue when it's about to fall off (or a little before if there's nothing else to do?) It's a 16 second buff.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/bPYi3ieH

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/gLpFpGqJ
https://pastebin.com/MbVkmrig
https://pastebin.com/4SV42zpc
https://pastebin.com/eYv4W3JQ

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
N/A

**Comment by Hekili** [comment]
Can you confirm if Natural Harmony Frost is up when you're seeing this? The
addon is seeing 0 seconds remaining on that buff.

**Comment by Hekili** [comment]
Additionally, could you confirm that you are in melee range and striking your target (i.e., with Frostbrand/Hailstorm active so that Natural Harmony: Frost is being refreshed)?

**Comment by Fynnconceivable** [comment]
I was definitely in melee range and striking my target (with FB active). I'll get back to you on the NH: Frost buff later today when I log in.

**Comment by Fynnconceivable** [comment]
I've just tested on a raiding training dummy and...the problem is no longer occurring. I haven't updated the add-on since last night when I entered the ticket and I don't think I've made any changes to my gear or talents, so I don't know what to think. I did see the Launcher download a small update for WoW this afternoon when I logged on.

I hate mysteries, but maybe issue is resolved.

**Comment by Hekili** [comment]
That's cool -- the logs you posted did show it would recommend Frostbrand due to NH Frost being down.  I wonder if there's an issue with spec swapping?  Did you switch gear or from Ele to Enhance when it was a problem?

**Comment by Fynnconceivable** [comment]
I did swap gear (and specs, from enhance to ele to resto) several times last night, and I do have separate azerite gear for each spec. I logged off a few times during raid while in enhance spec trying to fix it and while updating the add-on, which didn't help at the time, but maybe something was still being cached somehow?

**Comment by Hekili** [comment]
Looks like this is resolved.
