### ISSUE TITLE
After changing from Night Faye Covenant to  Kyrian

### ISSUE THREAD

**Issue by Imahorn** [Hekili/hekili#700]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Death and Decay not being suggested.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
Death and Decay being suggested when up.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.2-1.0.23
level: 60 (60)
class: DEATHKNIGHT
spec: frost

talents: avalanche
    cold_heart
    death_pact
    deaths_reach
    gathering_storm
    murderous_efficiency
    obliteration

pvptalents: none

covenant: kyrian

sets: none

gear: anima_field_emitter = 1
    blighted_margraves_cloak = 1
    breastplate_of_brutal_dissonance = 1
    charm_of_eternal_winter = 1
    emberscarred_girdle = 1
    entwined_gorger_tendril = 1
    galvanized_oxxein_legguards = 1
    guilewind_stone_talons = 1
    klontzas_precise_pummeler = 1
    pit_fighters_wristguards = 1
    sabatons_of_the_rushing_juggernaut = 1
    shadowghast_helm = 1
    signet_of_the_false_accuser = 1
    vile_butchers_pauldrons = 1
    viscera_of_coalesced_hatred = 1

legendaries: biting_cold = 1

itemIDs: 171415, 178749, 178755, 178800, 178807, 178808, 178824, 178836, 178840, 178848, 180099, 180118, 181202, 183040, 184800

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Frost DK
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    bos_rp = 50

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = true

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
Again, impossible to snapshot an event that does not occur.

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by IIeTpoc** [comment]
If you did not make any custom priorities and thorough hekili setup you can try to 
1. Save everything related to Hekili in your WTF folder on the character you have issues at.
2. Delete everything related to Hekili in your WTF folder on the character you have issues at.
3. Then reinstall Hekili addon.

**Comment by Hekili** [comment]
You don't need to reinstall.  You do need to provide a snapshot.  A snapshot is not a screenshot; it is a log of decision-making.  Please read the instructions and submit the required information.

**Comment by Hekili** [comment]
The conditions for Death and Decay for Frost DK are as follows:

`actions.cooldowns+=/death_and_decay,if=active_enemies>5|runeforge.phearomones`

Basically, it requires 6 or more enemies or the Phearomones legendary.  If you find Death and Decay not recommended when either of those circumstances are true, then please submit a new ticket with a screenshot.  Thanks.

**Comment by Imahorn** [comment]
Got it.  Thank you.  I seem to remember the number of enemies could be controlled by toggle and thought I had that set to >2. Then when Shadowlands came out and I was in Night Faye, D&D became Deaths Due and was the first thing up in a fight, regardless of mob size.  I assumed when I went to Kyrian, D&D just defaulted back.  Maybe I am mistaken.

Also and re: Frostwyrm’s Fury, attached is a screen shot of Icey Veins Oblteration rotation and quick discussion on Cooldowns and when to use them.  FF should be used every time it’s available, different from Breath of Syndragosa build.  It worked great until I added a Blood Spec for Torgast; now in Frost spec it is never suggested.

I’ll try to get a snapshot in a bit but it will be on a dummy after the initial opening rotation you see in the attached image and then I’ll pop cooldowns.

**Comment by Hekili** [comment]
The criteria for using Death's Due are different from the criteria for using Death and Decay.

I am not going to respond to any further tickets/posts without a snapshot of the exact scenario that you're concerned with.  This is like going to the dentist and telling them you refuse to open your mouth and that they have to go in from the opposite end.  I'm just not going to do it.

**Comment by Imahorn** [comment]
Lol. Sounds like a man speaking from experience.  Point taken.

**Comment by Imahorn** [comment]
Ok.  I think I sent it correctly, or should I open a new ticket.  However, it miraculously started showing up.  Not sure why.
