### ISSUE TITLE
Use Starfall in Single-Target with Stellar Drift isn´t working (Balance Druid)

### ISSUE THREAD

**Issue by MrHunter79** [Hekili/hekili#701]
No idea if it´s my own mistake or the "Starfall in Single-Target" Option isn´t running correct.
Because I never see the starfall in rotation when casting and only one target is in range.

-----

build: v9.0.2-1.0.23
level: 60 (60)
class: DRUID
spec: balance

talents: mighty_bash
    restoration_affinity
    solstice
    soul_of_the_forest
    stellar_drift
    warrior_of_elune
    wild_charge

pvptalents: crescent_burn
   faerie_swarm
   moon_and_stars

covenant: night_fae

sets: none

gear: abgrndige_bundhosen_der_zwietracht = 1
    amulett_des_sndigen_gladiators = 1
    blick_des_verdauten_verhrmeisters = 1
    dunkelmondkartenset_fulnis = 1
    festgezurrte_giftstachelbnder = 1
    geschtzter_ring_der_ritualistin = 1
    handschuhe_der_obskuren_rituale = 1
    hfttuch_des_schattenwirbels = 1
    schlundgebundenes_assassinenwams = 1
    siegelring_des_falschen_anklgers = 1
    spiritueller_alchemiestein = 1
    stinkende_knorpelvernhte_schiftung = 1
    tuch_der_verdrehten_treue = 1
    umbraledertreter = 1
    zischbummwanderstecken = 1

legendaries: balance_of_all_things = 1

itemIDs: 171323, 172315, 173069, 178448, 178757, 178760, 178763, 178824, 178934, 179339, 180108, 180111, 180123, 183037, 184656

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = true
    starlord_cancel = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
You have to submit a proper tickets following the instructions.  There is an entry for Starfall in single-target but there are additional conditions present.

**Comment by MrHunter79** [comment]
Would be nice to know what conditions have to be active that the option is working ;)

**Comment by Hekili** [comment]
You would need to read through the priority to see that information.
