### ISSUE TITLE
Balance Druid (Moonfire Spamming)

### ISSUE THREAD

**Issue by chuchacho** [Hekili/hekili#703]
1.  Version(s) in which the issue occurs:

> Problem persists on both the release (v9.0.2-1.0.24) and beta (v9.0.2-1.0.24-beta4) versions.

2. The bug I'm running into happens on my balance druid after I import a SimC profile.
     a. I type "/simc" and copy the popup text.
     b. I open the SimulationCraft application and paste that text into the "Import > Simc Addon", tabs.
     c. After the simulation finishes, I scroll to the bottom of the page and copy the text from the "Profile" dropdown.
     d. Ingame, I go to Hekili options > Priorities > Balance > Profile, and then paste in my text (then I hit "Accept" then "Import")

3. What the bug is specifically is whenever I'm under 100 astral power, Hekili recommends to continually spam Moonfire (usually 11 times in a row) until I reach max power. Then it recommends Celestial Alignment into a single Starsurge. After that, it once again has me continually spamming Moonfire until I reach 100 astral power. It just repeats that process indefinitely.
     

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/EWjKJeqN 

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/vCepBEEV

**Comment by Hekili** [comment]
Don't import a SimC profile.
