### ISSUE TITLE
"Fade as unusable" is fading out-of-gcd actions when GCD lock.

### ISSUE THREAD

**Issue by Dezc** [Hekili/hekili#705]
Hekili v9.0.2-1.0.24

**Describe the Bug/Issue**
When recommanding out-of-gcd abilities like "Shield of the Righteous", or "Avenging Wrath" (on paladin, didn't try on other classes) the recommanded action is "faded out" (grey action) during the GCD if the "Fade as unusable" option is check."

**To Reproduce**
- Go to Displays > Primary > Delays
- Set "No indicator" (not sure if relevant) and check "Fade as unusable"

**Expected behavior**
When recommanding out-of-gcd abilities the recommanded action should not be faded but immediatly usable.

**Comment by Hekili** [comment]
The exact purpose of "Fade as Unusable" is to darken the icon until it is time to use it. Just because it is off GCD, doesn't mean you are to use it immediately.
