### ISSUE TITLE
Shred vs Swipe

### ISSUE THREAD

**Issue by Nephliem** [Hekili/hekili#707]
Please describe your idea or feature and when it would be useful.
I have noticed that the rotation guide recommends to use swipe over shred vs 1 target. I can see using it in energy save mode for an upcoming burst phase but as a primary attack I have would see the use of Shred being its a higher base dmg and gets more form the 20% extra damage against bleeding targets. Vs 2 or more targets in an AOE situation I would agree to use swipe but purely single target the addon should prioritize shred even if the energy is slightly more.

**Comment by Hekili** [comment]
> I have noticed that the rotation guide recommends to use swipe over shred vs 1 target. 

What, where?  What makes you think this?  What rotation guide?  What?

> I can see using it in energy save mode for an upcoming burst phase but as a primary attack I have would see the use of Shred being its a higher base dmg and gets more form the 20% extra damage against bleeding targets. Vs 2 or more targets in an AOE situation I would agree to use swipe but purely single target the addon should prioritize shred even if the energy is slightly more.

This is a concern about the priority that should be submitted with the complete "Bug Report" template, including a snapshot when Swipe is shown over Shred in single-target.  *If* that's something that's actually happening, I'd guess that it's probably with Bloodtalons to proc the buff, but you'd need to submit the right information to know for sure.
