### ISSUE TITLE
WW Monk suggesting to use SeF when already out

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#708]
It's not all the time but I am seeing Hekili suggesting me to use SeF when its got a few seconds left before it runs out. Could easily get one more global cooldown in that time. Not sure why it is suggesting to use SeF while they're already out and I have no more left to use after this one has ran out. Doesn't have happen all the time but it does happen. And I think I snapshotted it at the right time... I hope.

Hard to say how to reproduce other than just playing around with it. It doesn't happen all the time but it does happen from time to time. I can't figure out why.

I believe it should be getitng another global inside of the time it suggesting SeF especially when there is no more to use after this one has ended. 

https://pastebin.com/nzVVwNsu

**Comment by Hekili** [comment]
The right time is the moment where the thing you are concerned with is happening.

You have 2 charges of SEF in that snapshot, which seems odd if you have clones expiring in a few seconds (which I can't see).

No other action criteria were met.

**Comment by Smudgiee** [comment]
Clearly the snapshot is wrong? I had SeF out -.-... the SeF button was red and not the normal icon. There were some changes to APL I believe.

**Comment by Hekili** [comment]
Ah, that is interesting.

**Comment by Hekili** [comment]
Well, in order to solve this, I have to split the "focus" ability for SEF into a fully-fledged separate ability (which is fine, no one uses it anyway, it's never in the APL).

But that allows the addon to check charges on the actual ability.  That might impact recommendations in your snapshot, since your snapshot expected 2 full charges of SEF.

**Comment by Smudgiee** [comment]
Yeah the Focus is only really a thing to use when you have the conduit (Coordinated Offensive) I believe you only need to press focus once and thats it, I think from what I've read atleast. But that should just be a brain thing to just do anyways.

EDIT: I think if it's just single target its auto fixate on same target for that conduit. Might just be for aoe stuff if u want to fixate but that doesn't really need to be in the recommendations as that would be hard to determine
