### ISSUE TITLE
Move windfury totem to cooldowns when Doomwinds is off cooldown and windfury totem is up

### ISSUE THREAD

**Issue by Ruby437** [Hekili/hekili#709]
Windfury Totem becomes a cooldown with Doom Winds and there are good reasons to not drop it when you know a burst phase is upcoming. Also, since this would put it into the same display as ascendance, make sure that ascendance is displayed first as you don't want to waste a doom winds GCD pressing ascendance (which lasts longer than doom winds anyways).

_As a side note, the enhancement shaman APL has been updated for both single target and multitarget and could use some updating. (I just did a pull request for the aoe portion, so it should be in tomorrow hopefully)

**Comment by Hekili** [comment]
Whether it appears before or after Ascendance would depend purely on the priority itself.

You can flag any ability as a cooldown yourself, if that's your preference.  Though I do understand the logic and will consider that behavior as a default.

There are no outstanding Enhancement APL changes in SimulationCraft that aren't included.  If/when your PR is accepted, I'll review it for inclusion here.

**Comment by Ruby437** [comment]
Hmm, can you explain how I can make Windfury totem only a cooldown when doomwinds is on CD? Since it should be maintained when it won't accidentally trigger doomwinds.

The missing APL update is sundering inside the doomwinds window.

**Comment by Hekili** [comment]
> Can you explain how I can make Windfury totem only a cooldown when doomwinds is on CD? Since it should be maintained when it won't accidentally trigger doomwinds.

You can't, and I won't.  You can choose to make WFT a cooldown via /hekili > Abilities, though.  You'll have to make a choice about how you manage it.

> The missing APL update is sundering inside the doomwinds window.

All simc APL updates that pass testing and are make it into the application will be reviewed for addition.  You don't need to notify me, I am watching them.
