### ISSUE TITLE
Trinket not showing in 'Gear and Trinkets' Section

### ISSUE THREAD

**Issue by ps-from-md** [Hekili/hekili#71]
**Describe the Bug/Issue**
I have a trinket which I got that does not show in the list of available trinkets.  It is required for my simc profile and there for will not prompt to use it.

My profile: https://worldofwarcraft.com/en-us/character/alterac-mountains/Neeman
Trinket: Ritual Feather of Unng Ak
iLvl: 375

**Comment by Hekili** [comment]
This will show up in the next beta.

**Comment by ps-from-md** [comment]
> This will show up in the next beta.

Is it possible to download the beta and how?

**Comment by Hekili** [comment]
The beta is being built right now and can be downloaded through all the normal channels when complete.

Look for v8.1.0-24-beta1.

**Comment by ps-from-md** [comment]
Just FYI.  I downloaded the v8.1.0-24-beta1 as indicated through Twitch and the trinket still does not show up.  I tried the different betas (up to 5) as well, and none of them had it in the list of gear and trinkets.

I did also notice that Ancient Knot of Wisdom does show up twice in the list (dont know if thats an issue or knot ;)

**Comment by Hekili** [comment]
Yup, typo on the item ID.  Will post a new beta.
