### ISSUE TITLE
Tranquilizing Shot for Marksmanship Hunter

### ISSUE THREAD

**Issue by mgibbonsjr** [Hekili/hekili#710]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

Confirmed I am using Hekili-v9.0.2-1.0.24.zip

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

I don't see any mentions of Tranquilizing Shot in the search. 

**Describe the Bug/Issue**

Tranquilizing Shot is never displayed as Marksmanship hunter specialization, but Beast Master works great. I went through the settings in the addon and I see Tranquilizing Shot as an action list item for Beast Master, but I don't see that for MM. Shouldn't that be applicable to Marks now too with the class change? 

**To Reproduce**
1. As BM specialization, target an enemy mob with an enrage or magic effect. Notice that Hekili suggests to tranq shot. 
2. Switch to MM specialization, target an enemy mob with an enrage or magic effect. Notice that Hekili does not suggest to tranq shot. 

**Expected behavior**
Tranquilizing Shot should be included in the display for Marksmanship the same as it is for Beast Master. 

**Screenshots**
[https://imgur.com/gallery/BJ46Gxy](Comparison between the BM vs MM view)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
[https://pastebin.com/B1VsEU1f](Pastebin Error Report)

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

N/A

**Comment by Hekili** [comment]
There's some inconsistency on this front, but it mostly has to do with what has been requested by players.  A lot of people don't like having the dispel, others do.  I have to sort out what I want to do, so that it's consistent.

**Comment by mgibbonsjr** [comment]
I see in the change log you added this back for Marks and Survival. Thank you so much for listening and making the quick addition. I appreciate your work and donated $10 through Curseforge. Thanks again!

**Comment by Hekili** [comment]
Thanks for the support.  While you're here, do you use a separate Interrupts display?  Would you move Tranq to your Interrupts (or "Utility") display?  I do that with Dispel Magic on my Priest, and I'm contemplating making that the default behavior.  That is, making it linked to the Interrupts toggle.

**Comment by mgibbonsjr** [comment]
Whhhaaatttt you can put it in the interrupt window instead? Yes I would
like that much better. Is that a setting I do or is that something you do
with code?

Thanks by the way for all you do for the community. A friend mentioned the
addon in guild back in bfa and I have used it ever since. It's so nice to
be able to switch between characters and not forget rotations. We have also
helped fix some and parses by telling folks to try the addon to get used to
the rotation. You are doing a lot of good for the community and I speak for
us all when I send a sincere thank you!
