### ISSUE TITLE
WW - Weapons of Order not accounting for reduced chi cost buff's duration when making suggestions

### ISSUE THREAD

**Issue by AlviSVPP** [Hekili/hekili#711]
Using Hekili-v9.0.2-1.0.24

**Describe the Bug/Issue**

There's a small annoying bug with WW: 
During "Weapons of Order" (Kyrian covenant ability, spell ID 310454) if you cast RSK you get another buff called "Weapons of Order" (spell ID 311054) that lowers the chi cost of spells by 1 for 5 seconds.

Now for the bug itself: 
There are times during that 5 second window where the addon suggests casting RSK next because you have 1 chi and it only costs 1 chi but by the time the GCD is over, the buff faded and then suddenly the recommendation swaps to something else, but I'm still spamming that RSK key before noticing that something's wrong. 

**Expected behavior**
Checking that the buff would last long enough to actually cast the recommended spell at reduced cost, or adapt accordingly.

**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/nGD4kKyN

**Comment by Hekili** [comment]
That would be somewhat annoying, but I'm not sure the cost of fixing it is worthwhile (it means rechecking resource costs at every point in time, to catch this edge case).  I'll think about it though.

**Comment by AlviSVPP** [comment]
Is there some possible workaround just for RSK? Like checking if buff.weapons_of_order.ww (I assume that's the chi reduction special for WW?) remains for more than a GCD? The problem is really mostly visible for RSK because at that point it's the only 2 chi ability that would be affected by the buff going away when at 1 chi.

**Comment by Hekili** [comment]
Yes, the APL could be written differently.

**Comment by Hekili** [comment]
1.0.29-beta1 is meant for you to test.

**Comment by Hekili** [comment]
I'll assume we're good.
