### ISSUE TITLE
WW- Suggesting to break FoF without Sef and WoO up.

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#712]
Seems to be suggesting to break FoF for some reason when both SeF and WoO are not even up and are on cooldown. Not always the case but it happens quite frequently which I think it might be something to do with SeF coming off CD?
Because at the time it was suggesting to break, SeF was actually like 1 sec from being able to be used.

I dont think it should be trying to break the channel of FoF ever unless both SeF and WoO are up, which these werent at the time. 

https://pastebin.com/yQGdmUJh
https://pastebin.com/0w4PkH38 (disabled cooldowns, and still suggests to break FoF)

EDIT: My delays are set up correctly.

**Comment by Smudgiee** [comment]
I was messing around and looking what had interrupt in the profile section and saw "actions.serenity+=/fists_of_fury,interrupt_if=!cooldown.rising_sun_kick.up" I removed that and reloaded and it seems to being working now? Did that really have something to do with it or is there something else going on? Doesnt make sense that would fix it because that belongs to serenity talent which is not specced into

**Comment by Hekili** [comment]
You're actually on the right track, there.  When you use an ability, I can't technically know *why* you used it.  So I cannot differentiate if you used Fists of Fury based on the Serenity list or based on another list.  But I will modify the conditions so that interrupt is only allowed if you are talented for Serenity.

**Comment by Hekili** [comment]
Closing because we don't need multiple tickets for the same issue.
