### ISSUE TITLE
MM hunter - serpent sting doesn't recommend target swap when multiple targets detected and current target has serpent sting

### ISSUE THREAD

**Issue by kp9928** [Hekili/hekili#713]
Version : v9.0.2-1.0.25

**Describe the Bug/Issue**
So I enabled recommend target swap. MM hunter serpent sting target swap should be recommended but theres no ">" icon for the next aimed shot when current target already has serpent sting and prior to this I have volley-ed a bunch of mobs to ensure they are detected.

**Expected behavior**
The next aimed shot should have a target swap reticle ">" ? if the current target already has serpent sting

Snapshot Pastebin here
https://pastebin.com/LMNLWb47

**Comment by Hekili** [comment]
Thank you for the ticket; this should be pretty easy to resolve.
