### ISSUE TITLE
Hammer of Wrath recommended non stop.

### ISSUE THREAD

**Issue by v3lasco** [Hekili/hekili#714]
Latest update "v9.0.2-1.0.25" is causing the addon to recommend Hammer of Wrath while it is not up. I have only tested this in Torghost so far and I do have the chance to be able to cast HoW Anima Power which could be the cause this issue. I will update this report if it continues to do it outside of Torghast.

**Comment by v3lasco** [comment]
Just confirmed its only in Torghast, and I think it's in reference to the Anima power "Negative Energy Token Judgment" which has a 30% chance to allow Hammer of Wrath to be cast on any target for 5 sec.

**Comment by Hekili** [comment]
It would've been helpful to include a snapshot per the ticket instructions.

Can you clarify the scenario you're describing?  Which of the following:

1.  You acquire Negative Energy Token.  The addon now recommends Hammer of Wrath constantly, permanently.

2.  You acquire NET.  The addon behaves as normal until you proc NET from a Judgment cast.  For 5 seconds, the addon recommends only Hammer of Wrath.

3.  Something else?  Please describe.

Finally, can you confirm if the NET proc is consumed after 1 cast, or if it allows you to cast one HoW in that 5 second window?  Thanks.

**Comment by Hekili** [comment]
Per the Paladin discord, the second option sounds correct.  So I still need to know -- did it just show HoW forever after obtaining the anima power, or did it show multiple usages of HoW while the buff was up?

Can you obtain a snapshot when this is happening?

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

**Comment by v3lasco** [comment]
It shows it forever in the third slot but then when I target mobs it becomes the action it says to take first even though it is not up.

https://pastebin.com/qubEe1fa

**Comment by Hekili** [comment]
Is Negative Energy Token applied to the target? Or to yourself?

**Comment by joceanlab** [comment]
its applied to yourself, and the moment it procs the addon starts recommending HoW, but when it ends HoW is still being recommended, and doesn't leave without a reload UI.

**Comment by Hekili** [comment]
Do you have spell IDs in your UI?  Can you show the spell ID of the 5 second buff and the spell ID of the anima power itself?

**Comment by v3lasco** [comment]
https://www.wowhead.com/spell=335069/negative-energy-token

**Comment by Hekili** [comment]
I don't need the Wowhead link, I need to be certain of what's actually showing in game.

**Comment by joceanlab** [comment]
that wowhead link is the buff that gets applied to you. i just finished my run but that was 100% it

**Comment by phoenixsoap** [comment]
I just did a torghast run and was confused because of this. I think it was negative energy token judgement. I think maybe the var is reversed so if judgement buff then no hammer, if not judgement buff then hammer instead of vicey versy

**Comment by Hekili** [comment]
Did you happen to log your Torghast?  It'd be nice to look at it.

**Comment by phoenixsoap** [comment]
I didn't but I can turn on logs next time
