### ISSUE TITLE
WW - Not suggesting to break second FoF in WoO and SeF now

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#715]
Using the latest version of the addon. I've reset profile, reinstalled Hekili.

The first suggestion of breaking FoF appears but the second FoF while in WoO and SeF are not being suggested to cancel. It should be breaking all channels of FoF while in WoO and SeF, which is not the case.

It's either suggesting Tiger Palm or Blackout Kick but it's faded as not to be used, when it can be used.

https://pastebin.com/kKWf1pxs (Tiger Palm)
https://pastebin.com/Ww5kFdaH (Tiger Palm)
https://pastebin.com/GSz3p1f3 (Blackout Kick)

**Comment by Smudgiee** [comment]
This is with the second usage of SeF that it happens* Not sure if that has anything to do with it

**Comment by Smudgiee** [comment]
May be just happening on Dummies. Will update more when I get chance to do another dungeon (Worked fine in dungeon). Which doesn't really make sense if that was the case or? When im actually playing though I'm not fully paying attention to it. It's just muscle memory to do it now.

**Comment by Smudgiee** [comment]
Can confirm, doesn't suggest to break any kind of target/cotent during the second SeF FoF. Which wouldn't have made sense either way.

**Comment by Smudgiee** [comment]
I changed the interrupt FoF line to "actions.weapons_of_order+=/fists_of_fury,interrupt_if=buff.storm_earth_and_fire.up&raid_event.adds.in>cooldown.fists_of_fury.duration*0.6" and now it seems to be breaking channel? I removed the WoO from it. But it may also be breaking when only SeF is up now instead of both. Will do more testing.

Edit: Yep, now it wants to break every FoF with just SeF out. Even though this condition is in the condition for WoO buff being up, yet it happens out of WoO. So is it still reading from WoO action list when not even in WoO?

https://pastebin.com/XGb4WaQf (Suggesting to break with jsut SeF and not even in WoO where the condition to break is placed) Not sure if this means anything but doesn't it seem odd that it's suggesting to break the FoF with just SeF up when I made that condition only to be in WoO buff up action list.

**Comment by Smudgiee** [comment]
I've ran the raidbots, both quick sim and advanced and it's always giving multiple examples on breakdown. Some don't break other FoF but then some breakdowns do. It confuses me, completely no idea why that is

**Comment by Hekili** [comment]
Yeah, I think you need to wait for another priority update.

**Comment by Hekili** [comment]
I think this is sorted.
