### ISSUE TITLE
Feral Apex Predator's Craving Proc seems low prio on high target count

### ISSUE THREAD

**Issue by p4nchez** [Hekili/hekili#718]
on high aoe target mob count the use of apex predators procs seems to have low prio 
it seems primal wrath or swipe hase a higher prio on high mob counts? and my free feriocius bite proc glow and want get suggested

should it not be that it use allways the proc over swipe or primal wrath? to get benefit from every primal wrath rip tick to proc more apex?

what is holding the free use of Fbite back on high pull counts?

snap 1
https://pastebin.com/7WGGp7EA

snap2
https://pastebin.com/TK2zAjyd

**Comment by Hekili** [comment]
It does.  It matches the priority as written (sim yourself in Hectic Add Cleave), but I don't know if additional testing would lead it to be used more often.  Or if it should even try to avoid letting the buff drop to avoid wastage.  Got a sim of yourself to link?

**Comment by p4nchez** [comment]
Hectic Add Cleave
5 minutes - 1 boss target
Bloodtalons+Primal Wrath
https://www.raidbots.com/simbot/report/ht9V4RB2dJ5BUJNR4cRaXC

Hectic Add Cleave
5 minutes 1 boss target
Moment of Clarity+Primal Wrath
https://www.raidbots.com/simbot/report/vEccsemXSnm1Tjim6meJrW

Hectic Add Cleave
5 minutes - 10 boss targets
Bloodtalons+Primal Wrath
https://www.raidbots.com/simbot/report/2BUi7oTAV8phZS9vqe8kPV

Hectic Add Cleave
5 minutes - 10 boss targets
Moment of Clarity+Primal Wrath
https://www.raidbots.com/simbot/report/6b3cLnAWDKB2tuUETQ3XZH

**Comment by Hekili** [comment]
I did some research on this; you can write an APL that uses Ferocious Bite more (I think 2-4 more times in a fight) in multi-target and it ends up being about equal in DPS until there are a lot of targets (since you're trading an AOE GCD for a ST GCD).

Not quite worth building it in yet...  Have you tried tweaking the sim priority yourself, to see if you can create an improvement?

**Comment by p4nchez** [comment]
thanks for your research and time you invested in this
now it make sense that a AOE GCD would do more or the same DPS in high count pulls

i understand it is not worth bulding in yet 
i dont know how to tweak sim prioritys myself or write APL myself

im very happy with your rotation so far so no need to change something 
thx for your help <3
