### ISSUE TITLE
PvP Trinket being used in Balance Druid rotations.

### ISSUE THREAD

**Issue by naamtar** [Hekili/hekili#719]
**Describe the Bug/Issue**
"Sinful Aspirant's Medallion" iLVL 184 is being recommended at the start of Balance Druid rotations - it has no benefit to DPS.

**To Reproduce**
Equip a PvP trinket and go to Balance form.

**Expected behavior**
PvP trinket shouldn't be part of any DPS rotation, it is for clearing CC from your character.

**Screenshots**
https://gyazo.com/2d9f97dae54595a057f93db36f1b66b3

It's worth noting that my trinket is bound to Q but the interface for the addon is not showing any keybinding when choosing this trinket for use.

**WHEN SUBMITTING AN ISSUE:**

build: v9.0.2-1.0.25b
level: 60 (60)
class: DRUID
spec: balance

talents: mass_entanglement
    natures_balance
    renewal
    restoration_affinity
    solstice
    starlord
    stellar_drift

pvptalents: none

covenant: night_fae

conduits: none

soulbinds: [dreamweaver]

sets: sinful_aspirants_medallion = 1

gear: arachnid_cipher_ring = 1
    bands_of_the_undergrowth = 1
    drape_of_twisted_loyalties = 1
    hood_of_refracted_shadows = 1
    rainshadow_hauberk = 1
    ring_of_perpetual_conflict = 1
    rocket_chicken_handlers = 1
    shadowghast_necklace = 1
    sinful_aspirants_leather_spaulders = 1
    sinful_aspirants_medallion = 1
    sinful_gladiators_lyre = 1
    soulletting_ruby = 1
    spellwoven_tourniquet = 1
    surgical_pustule_extractor = 1
    viscerastitched_footpads = 1
    volatile_shadestitch_legguards = 1

legendaries: the_dark_titans_lesson = 1

itemIDs: 175871, 178698, 178702, 178731, 178753, 178809, 178817, 178872, 178927, 178933, 179336, 179569, 180123, 182995, 183024, 184052

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    solo_drift = false
    starlord_cancel = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**PUT SNAPSHOT LINK HERE:**

Snapshot Link: https://pastebin.com/p1VZ8rNL

**Comment by Hekili** [comment]
I've flagged this trinket as defensive instead, and it should only be recommended while under a loss of control effect.
