### ISSUE TITLE
Pls update APL Unholy

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#72]
Hello, please update APL Unholy DK. The last update was December 28, 2018, now February 26, 2019. I think it's time to update the APL and finalize the rotation is not a lot. Thanks in advance for your help.

http://www.simulationcraft.org/reports/T23_Raid.html

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/53419926-c42bbb00-39a8-11e9-8aa5-a8d6be02ae69.png)

?

**Comment by Hekili** [comment]
I did find some incremental changes that were missed (very minor change for Outbreak).  The new beta includes the changes.
