### ISSUE TITLE
Guardian Druid Tweek sugestion

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#720]
Hello,

After playing few days on guardian and watched what hekili is recommended, i think there is one update must be made.

If player use legendary " Ursoc's Fury Remembered", during Incarnation or Celestial, Bear should only use Trash as dps skill, because this legendary give guardian huge absorb shield and with incarnation / celestial buff , there is no CD on Trash.
Recommending mangle during incarnation/celestial is maybe lite dps loss, but with this legendary it give bear huge self-healing.

**Comment by Hekili** [comment]
Sorry, there's not enough information here about what exactly you would change and no data to support a change.
