### ISSUE TITLE
Balance RunHandle Error

### ISSUE THREAD

**Issue by jtrack3d** [Hekili/hekili#722]
Please describe your idea or feature and when it would be useful.
The balance rotation continuously issues an attempt to call method RunHandle with a nil value errors.
DruidBalance.lua:880

809x Hekili\Classes\DruidBalance.lua:880: attempt to call method 'RunHandle' (a nil value)
[string "@Hekili\Classes\DruidBalance.lua"]:880: in function 'func'
[string "@Hekili\State.lua"]:5251: in function 'HandleEvent'
[string "@Hekili\State.lua"]:5851: in function 'advance'
[string "@Hekili\State.lua"]:5785: in function 'reset'
[string "@Hekili\Core.lua"]:1302: in function 'ProcessHooks'
[string "@Hekili\UI.lua"]:821: in function <Hekili\UI.lua:685>

**Comment by Hekili** [comment]
Thank you.  Typo will be resolved in this morning's release.
