### ISSUE TITLE
Support the Ring of Unburdening Anima Power

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#723]
As requested in #598 here a separate issue:
With the [Ring of Unburdening](https://www.wowhead.com/spell=332545/ring-of-unburdening) Anima Power all Paladin abilities cost 1 fewer Holy Power. It would be nice if Hekili would support that.

**Comment by Hekili** [comment]
This requires too much additional support, tbh.  It'd require a recustomized APL which means it's extra effort everywhere, when it's really only for Torghast.
