### ISSUE TITLE
Throw glaive shows up more than 3 times in suggestions of vengeance DH

### ISSUE THREAD

**Issue by riasvdv** [Hekili/hekili#724]
**Describe the Bug/Issue**

This mostly happens in aoe but sometimes also in single target, when doing the suggested rotation, suddenly the queue turns all throw glaive and I have to use a different ability to have it "reset" to the normal suggestoins.

**To Reproduce**

Do the normal vengeance DH rotation.

**Expected behavior**
Not more than 1 throw glaive suggestion in a row. Or at most 2 since that's the amount of stacks it has.

![image](https://user-images.githubusercontent.com/3626559/102820344-6403d580-43d5-11eb-894e-c60747a2b93e.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:** https://pastebin.com/Quqk9qqz

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:** https://pastebin.com/JZHcpXP6

**Comment by Hekili** [comment]
Did you put Spirit Bomb on your Cooldowns toggle or something?  It's disabled, and that's how you'd spend fragments to concern yourself with starting to generate again.

The multiple Throw Glaive counts account for regenerating charges; the issue is that the APL is written to spend Soul Fragments via Spirit Bomb if you've taken Spirit Bomb.  If you disabled SB or have it toggled off as a Cooldown, you've undermined the priority list.

**Comment by stornquist** [comment]
I have this issue as well and I just started using Hekili with default profiles (havn't changed any settings apart from icon size and position)

**Comment by Hekili** [comment]
Still need an explanation for why Spirit Bomb would be disabled.  Gotta actually post info.  Show me screenshots of /hekili > Abilities > Spirit Bomb.

**Comment by stornquist** [comment]
![image](https://user-images.githubusercontent.com/42915664/102840160-806a3700-4402-11eb-8461-86bcc51956a9.png)

**Comment by stornquist** [comment]
To be clear, it works fine some of the time but then sometimes it just stops recommending Spirit Bomb.

**Comment by Hekili** [comment]
And a snapshot when Spirit Bomb is no longer recommended for you?

**Comment by Hekili** [comment]
Another key detail is that Conduits/Soulbinds are missing from this snapshot, too.  Something is shaking off Conduit/Soulbind detection.

**Comment by Hekili** [comment]
I am fixing the bug where your conduits/soulbinds get forgotten occasionally in 1.0.27a.  Let me know whether this behavior occurs in 1.0.27a.

**Comment by riasvdv** [comment]
Not at my PC until tonight, but I have the most default installation of Hekili, I haven't changed or disabled any abilities / priorities

**Comment by Hekili** [comment]
Sure.  Please test with 1.0.27a and let me know.

**Comment by riasvdv** [comment]
Same issue in 1.0.27a

Character data: https://pastebin.com/ZYSCRVDF

Snapshot: https://pastebin.com/cXxi3de9
Another snapshot: https://pastebin.com/j1cLmSTE

**Comment by Hekili** [comment]
Can you tell me more about when this starts happening?  I presume it's not happening when you first sign in, then you start seeing it later?  When?

**Comment by Hekili** [comment]
Ahh, so this is happening when you have Soul Fragments but low Fury.  You can't Spirit Bomb for lack of Fury, you can't Fracture (due to overcapping).

**Comment by riasvdv** [comment]
Yes that seems the case, it often happens after using Elysian Decree as it spawns extra fragments

**Comment by Hekili** [comment]
I've tweaked the priority to allow Fracture at low Fury regardless of Soul Fragments.  You can generate Fury a few other ways, but you'd have already used those abilities by that point.  That'll be in 1.0.28 later today.

**Comment by Hekili** [comment]
(You can add `fury < 30 |` at the start of the existing Fracture entry, if you don't want to wait.)
