### ISSUE TITLE
MonkBrewmaster.lua, purifying_brew id out of date

### ISSUE THREAD

**Issue by crk5623** [Hekili/hekili#725]
The Purifying Brew skill has two ranks. MonkBrewmaster.lua only contains the id for rank1 (line 1077). Once the player learns rank2 the skill isn't shown any more. Changing the id fixed the problem for me.

rank1 id = 119582
rank2 id = 343743

**Comment by Hekili** [comment]
I need a proper ticket for this, because I'm definitely not seeing the bug you'd reported.

The spell ID for Purifying Brew doesn't change at rank 2, you're still casting 119582.

Please submit a snapshot showing PB not being recommended at level 47+ because of its spell ID.
