### ISSUE TITLE
Trinkets doesnt show on imported profiles from SimulationCraft

### ISSUE THREAD

**Issue by hectorgd** [Hekili/hekili#727]
Hi , How are you?

**Describe the Bug/Issue**
After importing a profile from SimulationCraft Report, trinkets do not appear in rotation. I see some Warnings after the import ( see image below) and if I go to the 'Action list' tab and click the [Use Items] entry there is an issue that says: "2: attempt to index field '?' (a nil value)" (see image below) 

**To Reproduce**
- Firstly simulate your character and copy the Profile from SimulationCraft Report
- Go to 'Priorities'
- Make a copy of an existing Priority or edit one already created
- Click on Profile tab
- Paste your SimulationCraft profile 
- Click Accept and Import

**Expected behavior**
After importing a SimulationCraft profile the trinkets should still appear in the rotation
**Screenshots**
- Warnings after importing
![image](https://user-images.githubusercontent.com/36993544/102877921-613dca80-443f-11eb-806a-b0d0bf59d386.png)
- Issue at [Use Items] entry at Action List
![image](https://user-images.githubusercontent.com/36993544/102878008-89c5c480-443f-11eb-89f1-8e5bbac5bc29.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

[https://pastebin.com/xwQjsg5n](https://pastebin.com/xwQjsg5n)

And this is the profile that I'm trying to import : [https://pastebin.com/8E4G4DEh](https://pastebin.com/8E4G4DEh) it was created by SimulationCraft version 902-01

Thank you for this awesome addon 👍

**Comment by Hekili** [comment]
Don't import from SimulationCraft. Custom priorities are at your own risk. Most require additional adjustment.
