### ISSUE TITLE
microstutters as fire mage.

### ISSUE THREAD

**Issue by Kelmith** [Hekili/hekili#73]
hello,

microstutters only as firemage, frost and other classes/speccs working fine. 

build: v8.1.0-23
level: 120
class: MAGE
spec: fire

talents: flame_on
    incanters_flow
    living_bomb
    meteor
    ring_of_frost
    searing_touch
    shimmer

traits: autoselfcauterizer=1
    blaster_master=1
    blightborne_infusion=1
    cauterizing_blink=1
    eldritch_warding=1
    heed_my_call=3
    relational_normalization_gizmo=1
    wildfire=3

sets/legendaries/artifacts: none

gear:     captains_signet_of_command=1
    lightfeather_footpads=1
    7th_legionnaires_handwraps=1
    bloodbough_mantle=1
    wand_of_zealous_purification=1
    conch_of_dark_whispers=1
    lord_admirals_signet=1
    arathor_battle_tabard=1
    darkwood_sentinels_drape=1
    surging_synthetic_specs=1
    balefire_branch=1
    heart_of_azeroth=1
    loa_betrayers_vestments=1
    moonpriests_cuffs=1
    rattling_jar_of_eyes=1
    sleeveless_tshirt=1
    ivus_tanglemoss_waistcord=1
    chumcoated_leggings=1

**Comment by Hekili** [comment]
I don't know what this means, precisely.

**Comment by Kelmith** [comment]
I dont know how to describe it (my english is awful :D). it feels "laggy", fps drops I think.

**Comment by Hekili** [comment]
I believe this was addressed with other fixes, but if not, please resubmit with a complete ticket.
