### ISSUE TITLE
Fps drops / high cpu usage

### ISSUE THREAD

**Issue by techicode** [Hekili/hekili#730]
**Describe the Bug/Issue**
I notice today a massive drop of fps. from +100fps to 57fps. I have installed an addonn to check wich addons use the most cpu/memory and hekili was on top. 
So I desactivated hekili to check if was really the cause of the lag and yes. almost no fps variation when hekili was desactivated.

**My rig:
ryzen 3600
gtx 2070 super
16gb ram
installed on m2 samsung**

**To Reproduce**
This only happend when I start using my skills. When Im iddle or just walking/fliying theres no fps drop.

**Expected behavior**

**Screenshots**
![Screenshot_252](https://user-images.githubusercontent.com/54788838/102948059-bc090d80-44a3-11eb-9f92-624ac06ee230.jpg)
drop to 57 fps with hekili activated (in middle of a fight)
Also heavy use of cpu.

![Screenshot_253](https://user-images.githubusercontent.com/54788838/102948085-d347fb00-44a3-11eb-9437-c4f8ac271fdc.jpg)
same place, same mobs, hekili desactivated  (in middle of a fight too)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

It's not a issue that can be tracked I guess?

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Fire Mage is use-at-your-own-risk.  It's an especially CPU intensive spec.
