### ISSUE TITLE
Recommending Word of Glory when criteria not met (HP>65%)

### ISSUE THREAD

**Issue by Skylines01** [Hekili/hekili#733]
**Describe the Bug/Issue**
Occasionally suggesting to use Word of Glory at 100% HP for protection paladin when Shining Light buff is up and GCD is empty. There are instances where I have empty GCD's as well as the buff but it does not make the same suggestion, leading me to think it might be a bug? There is an entry in the mitigation action list that includes this criterion but I have it disabled it as it serves no useful purpose to me and wastes the buff. This criterion may be useful to heal a raid member but without the Hand of the Protector talent the heal is very small and better served healing your self. 

**To Reproduce**
Nothing specific. The problems occur in all environments: instances, solo, training dummy, taking damage, taking zero damage, single target, and aoe. Usually occurs 1-2 times a minute but is unpredictable. You need to cast five Shields of the Righteous to gain the Shining Light buff which makes Word of Glory Free to Cast. 

**Expected behavior**
Do not recommend Word of Glory above 65% HP under any circumstances including those mentioned above: shining light and empty GCD. Potentially remove the entry or edit it to require Hand of the Protector?

**Screenshots**
![WoWScrnShot_122320_163231](https://user-images.githubusercontent.com/76530275/103020095-cb3d9900-453f-11eb-96e5-2e759be7d150.jpg)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/xBirjvNb

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/S7tsCyuB

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

N/A

Thank you for your time in reading this. I very much appreciate the time you've taken to develop this addon. I just wanted to add that I have done my best to go through all of the settings to resolve this issue myself before taking up your time.

**Comment by Hekili** [comment]
You will need to provide a snapshot that shows Word of Glory being recommended.

**Comment by Skylines01** [comment]
Thank you for your quick reply.

https://pastebin.com/svPvNC4q

Is this suitable?

**Comment by Hekili** [comment]
Yep.

**Comment by Hekili** [comment]
This should be resolved as of Dec 25; refer to the updated Protection Paladin priority.
