### ISSUE TITLE
[Warrior] Recommending Whirlwind Instead of Execute On Two Targets

### ISSUE THREAD

**Issue by Totos1991** [Hekili/hekili#734]
During raid (Huntsman Boss), the addon is telling me to use whirlwind instead of the available execute ability when there are only two targets present. Execute typically would hit between 4.5-12k damage when triggered, while whirlwind was hitting only for about 2k dps when triggered.

To reproduce you would have to fight two mobs and when one of them gets to the execute phase, you will see whirlwind being suggested some of the times.

Expected behavior
Since execute hits more for the same fury cost, I would expect execute to be priority when dealing with two mobs (maybe execute priority up to 4 mobs?).

Screenshots
https://gyazo.com/15ee653f03cebd1336c9624dc2aa6805

Snapshot:
https://pastebin.com/D0Pd3GST

**Comment by Hekili** [comment]
I've done some comparison sims, and it does seem to be a problem in sims as well.  Will have to tweak and tune the numbers a bit.

**Comment by Hekili** [comment]
I'm trying out an adjusted priority in 1.0.32-beta1, let me know how it works for you.  It sims higher for me.
