### ISSUE TITLE
[Shaman] Night Fae Elemental Shaman Lava Burst before Fae Transfusion

### ISSUE THREAD

**Issue by m3dos** [Hekili/hekili#735]
I notice that the elemental shaman rotation doesn't prioritize a 'master of the elements' (talent) cast of lava burst before casting the covenant ability, "Fae Transfusion" - This is an important dps mechanic - as the cast of lava burst will empower fae transfusion with 20% more damage.

**Comment by Hekili** [comment]
Please follow the ticket instructions, provide a snapshot, and in this case, a comparison sim showing your changes.

**Comment by m3dos** [comment]
from https://www.icy-veins.com/wow/elemental-shaman-pve-dps-rotation-cooldowns-abilities

![image](https://user-images.githubusercontent.com/12224799/103050284-cf21e900-4548-11eb-98a6-5a73587d274a.png)

**Comment by Hekili** [comment]
I understand; that's still not following the ticket instructions.  Did you check SimC?  Do a comparison sim?  Do you need to notify them about it?
