### ISSUE TITLE
[Arcane Mage] Opener rotation never recommended

### ISSUE THREAD

**Issue by Gnoma69** [Hekili/hekili#736]
Addon version - V9.0.2-1.0.30

Steps to reproduce:
Login as a Mage and set spec to Arcane.
Before opening on a target the rotation shows as Mirror Images (ok), Trinket (not expected, should be used with Arcane Power), Touch of the Magi (not expected).

Expected Behaviour:
The Arcane Mage opener rotation has you cast Mirror Images, Arcane Blast (pre-pull) into Arcane Orb, and Arcane Blast up to 4 charges, drop a Rune of Power and Arcane Blast to fish for Clearcasting, before dumping all charges with Arcane Barrage and then burning starting from Touch of the Magi etc.

![image](https://user-images.githubusercontent.com/34569427/103055840-79544c00-45ef-11eb-877f-bfab05e58ee2.png)

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/T7wm1j0V

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Please sim yourself on Raidbots and provide a link, as well.  Thanks!

**Comment by Gnoma69** [comment]
As requested, Raidbots link
https://www.raidbots.com/simbot/report/pqh5hyQdCNfSCaG6162Jc1

**Comment by Hekili** [comment]
Thanks.  This is a subtle bug in translating from SimC to Lua (for addon purposes).  I have a testfix but I may post an adjusted priority list that doesn't cause the bug, since changing my translator can impact ALL THE THINGS.

**Comment by Hekili** [comment]
Actually, two bugs.  But I'm getting closer:

![image](https://user-images.githubusercontent.com/9438134/103139001-ae22da80-46a5-11eb-9281-ba9be117243f.png)

**Comment by Hekili** [comment]
This should be resolved in the next release.
