### ISSUE TITLE
balance filler

### ISSUE THREAD

**Issue by deedz1** [Hekili/hekili#737]
Please describe your idea or feature and when it would be useful.
hi hekili,

can you please respond with simc code I can add to the balance rotation for the following filler:

I want to recommend moonfire/sunfire on my target while moving if they are currently not on my target (or say 5 seconds remaining) AND I do not have Stellar Drift talented  AND if I do - star fall is not up

thanks

**Comment by Hekili** [comment]
No, sorry, I don't write custom APLs for people.  You have to know what you're doing to customize priorities.
