### ISSUE TITLE
Requesting additional racial/trinket support

### ISSUE THREAD

**Issue by Excitedguy** [Hekili/hekili#739]
Hello,

Can't speak for all racial abilities and trinkets, but I've noticed there's some missing racial abilities and PVP trinkets. Certain PVP trinkets being recommended when they shouldn't be. Will list some examples that I personally noticed.

Sinful Aspirant's Emblem is a trinket that increases max HP for 20 seconds on use. Hekili is recommending this trinket as  if it were a DPS trinket. No option to configure this trinket at all in the settings.

Will to Survive is a human racial ability, removes stun effects. I see it listed no where in the abilities or gear and trinkets sections in the settings. Also, was wondering if there's a condition that can be specified to recommend when you are stunned and possibly specify the duration of the stun.

Thank you

**Comment by Excitedguy** [comment]
Update: Actually discovered that Notorious Gladiator's Emblem is the same as Sinful Aspirant's Emblem according to Hekili, so I can configure this. Still not finding a Will to Survive setting yet for Human racial. It was recently renamed to Will to Survive from Every Man For Himself, but not finding either in the settings.

**Comment by Excitedguy** [comment]
I was able to get Will to Survive added by adding the following entry to Classes.lua

    will_to_survive = {
        id = 59752,
        cast = 0,
        cooldown = 180,
        gcd = "off",

        toggle = 'defensives',
    },

If you could add this in next update, would appreciate it!

**Comment by Hekili** [comment]
I've added Will to Survive for the next beta and release.  Ideally, I'd be able to check if you're stunned but I can't do that consistently just yet.  So it has no conditions and it also does nothing.
