### ISSUE TITLE
Shadow Priest rechecking during Mind Flay impacting FPS

### ISSUE THREAD

**Issue by bcbooker** [Hekili/hekili#740]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**Addon works fine, until addon has to account for it seems like downtime. It then will show 3 icons of mindflay and I'll notice my FPS will drop 20 and some slight stuttering will occur. This only occurs during that particular portion of the commendation.** 

**I'm not sure if it has to do with me removing surrender to madness from the action list, as I didn't want it to recommend all the time.**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

https://pastebin.com/QFCFG5s9

**PUT ERROR MESSAGE(S) HERE:**

**No error messages to report.**

**Comment by Iyadriel** [comment]
I second this, even with heavy throttling enabled in the performance options I still experience these fps drops. This only occurs on my shadow priest as well.

**Comment by Hekili** [comment]
Thanks, I'll re-enable a setting that will result in fewer rechecks during Mind Flay channels.  Basically, the criteria for breaking Mind Flay's channel are met when Void Bolt is off cooldown, but Void Bolt has been treated as off cooldown even when you can't cast it (i.e., not in Voidform, no Dissonant Echoes).

I'll have to watch this closely, because this is going to result in more full channels of Mind Flay and we have to be certain that's consistent with the sim.

**Comment by Hekili** [comment]
I'm pretty satisfied with the current solution to recheck less during channels, but may refine it further.
