### ISSUE TITLE
Shockwave has more value than solely as an interrupt

### ISSUE THREAD

**Issue by IronMongrel** [Hekili/hekili#741]
in WarriorProtection.lua after shockwave = {

toggle = "interrupts",
            debuff = "casting",
            readyTime = state.timeToInterrupt,
            usable = function () return not target.is_boss end,

all of that should be defined/definable in the priority list and/or in the modifiable settings. shockwave can be used to stun a large number of mobs to reduce incoming damage damage rather than simply as an interrupt on your present target and i would argue it's actually useful in that context far more often than as a single target interrupt.

**Comment by Hekili** [comment]
Tell me more about the criteria when you would use it (and that it would be correct to do so as a damage or mitigation ability).  Or for proccing Sephuz.

I agree that it has more uses than just as a single-target interrupt, but most of those are highly situational with potential drawbacks as well (stunning in a pool, interfering with kiting, etc.).

There's nothing stopping anyone from using it as a utility ability regardless of having it show up in the priority.  What is the actual use-case that you're aiming for?

P.S.  I really prefer descriptive ticket names vs. dramatic ones.

**Comment by IronMongrel** [comment]
I'm very sorry. I'm pretty dramatic [:

I personally usually use it if there's a lot of mobs nearby, particularly if I'm getting hit pretty hard, doubly in particular if my defensives are going to drop.

I also use it pretty often if I'm going to lose threat on a couple of mobs and just need a couple more seconds before my aoe threat cooldowns are back up, to prevent mobs splitting and having to chase them down, although I'm guessing that's not a use case that Hekili could handle really well.

I think it would serve the most benefit in an action list just to kind of remind people if they're getting really low against a pretty sizable pack and don't have another big defensive cooldown up, "Hey, stun 'em all for a couple of seconds." If you're not used to using it defensively because it's not quite a traditional defensive cooldown, you might not think to - but those couple of seconds might be just enough to let a healer get off a big heal that you might otherwise not be able to stay standing for.

I'd personally maybe slap something like this bad boy right at the end of the mitigations action list:

actions.mitigation+=/shockwave,if=incoming_damage_3s>health*1.2|(incoming_damage_5s>health * .8 & buff.shield_wall.down & cooldown.shield_wall.remains > gcd * 2)

I might even make a duplicate entry right after just for strictly handling big honkin pulls, something like

actions.mitigation+=/shockwave,if=incoming_damage_5s > health & active_enemies>4

Maybe having a little clicky-option like "Only use revenge if free!" along the lines of, "Allow shockwave to be used as a defensive cooldown"

**Comment by Hekili** [comment]
I'm adding a setting for this.
