### ISSUE TITLE
hekili not showing rotation for Outlaw using latest beta version.

### ISSUE THREAD

**Issue by MrSmurfy** [Hekili/hekili#746]
Problem exists with (latest) beta version, v9.0.2-1.0.31-beta1  

**Describe the Bug/Issue**
Hekili doesn't show spell suggestions using Outlaw spec.

**To Reproduce**
Run as outlaw spec, observe Hekili not doing anything. Addon is loaded correctly.

**Expected behavior**
Hekili showing spell rotation for Outlaw.

Issue Reporting output:
https://pastebin.com/16FahtMt

No error is given.

**Comment by Backsteinschloss** [comment]
hey there,
i am having the same issue.

but I want to add that there is no priority for "Outlaw" within the "Outlaw"-settings tab. Besides that, u can find an outlaw priority in the "assassination" tab. 

best regards

Screenshots:
https://prnt.sc/wabist
https://prnt.sc/wabiwt

**Comment by choseh** [comment]
It helps to duplicate the Priority under Priorities -> Outlaw, then selecting outlaw from the duplicated dropdown and activating it (if that helps for debugging)

**Comment by Hekili** [comment]
Should be fixed in -beta2.
