### ISSUE TITLE
Feral - druid.owlweave_cat check using wrong type

### ISSUE THREAD

**Issue by Grayfox2325** [Hekili/hekili#748]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
With latest addon version the Feral priority no longer recommends owlweave regardless of settings. Switched to default priority and still not working. Owlweave is enabled, conditions have been met.

**To Reproduce**
Noticeable in normal priority use

**Expected behavior**
Primary display should recommend Moonkin Form/Heart of the Wild when conditions met. If manually entered the balance action list will play out as expected.

**Screenshots**
N/A

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/2UmsFcs4

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
The conditions are not met in your snapshot.  You won't pop Heart/Moonkin unless:

1. Your energy is below 40.
2. Your Rake is up and will last 4.5 seconds.
3. Rip will last 4.5 seconds (or your combo points are < 5).
4. Tiger's Fury is on CD for 4.5 seconds.
5. Clearcasting is not up.
6. Apex Predator's Craving is not up.
7. Convoke is not ready.

That said, the Heart/Moonkin entries that end with `&druid.owlweave_cat=1` should have the `=1` removed as well.  I'll take care of it.

**Comment by Hekili** [comment]
Should be resolved in the newest beta.

**Comment by lucala** [comment]
I wondered why it never suggested owlweaving even though I met the above conditions. Turns out you need to turn it on in the settings! Love the addon so far, great work.

**Comment by lucala** [comment]
Talking to the theorycrafters behind owlweaving on the dreamgrove discord it seems like the conditions that should be met are slightly different. (copied directly from there)
```
The conditions are:
- Energy < 30
- Either Rip up and duration > 4.5s OR combopoints < 5
- Tigers Fury on cooldown and cooldown > 6.5s (ignore this if you run cateye curio)
- No clearcast and Apex procs
- No bloodlust active
- Either Berserk/Inc is not active OR Berserk/Inc has more than 5s duration left
- Convoke the spirits is on cooldown (if you're not NF, ignore this)
It doesn't matter if you'd clip Sunfire, do it anyway.
If all conditions are true, then you perform a sequence based on your Heart of the Wild (HotW) cooldown and buff
```
I noticed that hekili will suggest the owlweave cycle while berserker is up which is suboptimal. The rotation in an owlweave cycle seems to be correct (starsurge & sunfire). Additionally if possible, for AoE dmg with night fae it should suggest HotW/boomy/convoke based on the following conditions:
```
- 1-5 targets: feral convoke
- 6-8 targets: HotW boomkin convoke (or feral convoke if no HotW)
- 9+ targets: boomkin convoke (even without HotW)
```

**Comment by Hekili** [comment]
This is an already closed ticket.

You didn't provide the required ticket information.

If/when they update the sim to follow the conditions they've written up, I'll update as well.

**Comment by lucala** [comment]
> This is an already closed ticket.
> 
> You didn't provide the required ticket information.
> 
> If/when they update the sim to follow the conditions they've written up, I'll update as well.

Ok so you're monitoring this and there is no need for me to open a new ticket?

**Comment by whoaisjustin** [comment]
He gets notified when the nightly simc build for each spec is updated. When Feral is updated, he'll know shortly after.

**Comment by Hekili** [comment]
Yeah, what @whoaisjustin -- I check for updated APLs on (roughly) a daily basis.  Xanzara and the Feral crew are really good about updating SimC once they've fine-tuned a priority change.  @ShmooDude might know if/why this isn't in SimC yet, too.
