### ISSUE TITLE
[Guardian Druid] Mangle Priority

### ISSUE THREAD

**Issue by ShmooDude** [Hekili/hekili#749]
While technically the simcraft APL will produce the best DPS (or I assume so, I haven't tried to tweak it myself), I'm not sure that its the best default behavior for Hekili.  Specifically speaking of Mangle.

Right now, it will basically stop using Mangle at 3 targets in favor of Swipe, which will result in better damage, but worse mitigation since Mangle is our best Rage generator.

Currently, I added a Mangle between the 2nd and 3rd Moonfire lines (below galactic guardian, but above refreshable).

Perhaps there should be a toggle for Damage vs. Mitigation?

**Comment by Hekili** [comment]
I'm adding a spec setting for this.
