### ISSUE TITLE
ret paladin lay on hands not checking for forbearance

### ISSUE THREAD

**Issue by IronMongrel** [Hekili/hekili#75]
usable = function () return not debuff.forbearance.up end,

is missing from the ret paladin lay on hands entry.

i just checked and it's also missing from prot paladin, however i haven't witnessed it being recommended while uncastable due to forbearance first hand as i have with ret.

**Comment by Hekili** [comment]
Thanks!

**Comment by Hekili** [comment]
Fixed.
