### ISSUE TITLE
Balance Druid Simc profiles spamming Moonfire

### ISSUE THREAD

**Issue by Jlsweeney96** [Hekili/hekili#750]
Title speaks for itself really, whenever I try loading the T26 profile here on Github or generating my own with SimC, Hekili for some reason wants me to spam moonfire when I am balance. When i reset it to default it doesn't do this, only with profiles. Is there something I am doing wrong or is there a reason it has me spamming moonfire?

**Comment by Hekili** [comment]
I don't support custom priorities; the feature is there for folks who can troubleshoot them.

There's no reason you'd need to import the tier 26 profile from SimC/GitHub because I've already translated that for the addon -- that's what the default is.

**Comment by Jlsweeney96** [comment]
Ah okay, I'm very new to hekili so I wasn't sure how everything ties
together, thank you

**Comment by Hekili** [comment]
No worries, some bits are not intuitive so feel free to ask questions.
