### ISSUE TITLE
Sepsis Cooldown

### ISSUE THREAD

**Issue by Mkay321** [Hekili/hekili#751]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
The "remaining CD" timer on Sepsis is not always displayed correctly, and sometimes not at all.
Sometimes It shows the timer, sometimes It doesnt, sometimes its greyed out and sometimes it looks like it can be casted but its still on CD. Check my screenshot where cropped out what Hekili shows and the actual CD from my hotbar next to it. 

**To Reproduce**
Smash ur rotation, If sepsis is on cooldown and is suggested it sometimes shows as if it isnt on cooldown even tho its a second or two left on the cooldown.

**Expected behavior**
The timer to be displayed at all times until its off cooldown, just like it does for all other abilities/cooldowns.

**Screenshots**
![image](https://user-images.githubusercontent.com/76015649/103204485-c4c07000-48f7-11eb-8131-03af76e95493.png)
Would like to have the timer displayed like the 4th ability in the screenshot below:
![image](https://user-images.githubusercontent.com/76015649/103204786-61830d80-48f8-11eb-9553-b82097ec62c4.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/U9VsW24T

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/fNSAmvDr

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Hi, thanks for the ticket.  Can you provide a snapshot when Sepsis is recommended but on CD, without CD text?  The snapshot you provided is not recommending Sepsis.

**Comment by Mkay321** [comment]
Here Sepsis was the next suggestion but on CD with no CD text as I pushed snapshot and stopped the rotation: (I did not use Sepsis)
https://pastebin.com/6p5tCJ6E

In this snapshot I used Sepsis when it was suggested and went off CD, and It did not show the CD text
https://pastebin.com/svJWdj5x

Here It did not show the CD-text as it was in "queue 2,3,4" but came off CD perfectly as it got to 1st suggestion.
https://pastebin.com/qGTgK7xW

Hopefully I got it right, let me know If you need anything else
(To be clear: The rotation itself makes perfect sense, but I just miss the CD-text)

**Comment by Hekili** [comment]
I have tried to replicate this, but it doesn't work for me.  The major difference might be that I'm in Covenant preview mode at level 50, but Sepsis shows its CD for me:

1. ElvUI + /hekili > Displays > Primary > Apply ElvUI Cooldown Style
2. ElvUI without Apply ElvUI Cooldown Style
3. Hekili w/o ElvUI

This leaves me wondering if you have a CD text addon that's otherwise interfering with Sepsis.  Or if I have to really select Night Fae permanently to experience the bug (which I hope is not right).

**Comment by Mkay321** [comment]
I dont use ElvUI but I disabled all my addons and turned them a couple at the time and It seems to be Bartender4 that somehow is interfering with the Sepsis CD unless it is a very random coincendence that It started working without addons and suddenly started acting weird with Bartender4 active.

**Comment by Hekili** [comment]
It's certainly odd.  I have no idea how I would address that, to be honest.
