### ISSUE TITLE
UNHOLY DK DEATH AND DECAY

### ISSUE THREAD

**Issue by pqr337** [Hekili/hekili#752]
Hi, im trying to display Death and decay at 3 or more targets, i edit the ability in the minimum targets field but its doesnt work, it always priorize death and decay at 2 or more.  Thanks

**Comment by Hekili** [comment]
I found what is causing this, but I'll just warn you in advance that the whole Unholy DK priority is very sensitive to target counts so you may find that the priority doesn't really work well for you anymore if you prevent a 2-target Death and Decay.

You'd need to actually look at revising the priority itself for this kind of change (which I don't provide support for).
