### ISSUE TITLE
Allow buff/debuff checks by spell ID (for unsupported auras)

### ISSUE THREAD

**Issue by Excitedguy** [Hekili/hekili#753]
I think it would be a really cool feature to be able to specific buffs on a target as a condition, even if it was implemented via spell IDs only. I would mainly use this for PVP, some examples would be to recommend a weapon disarm if Paladin uses avenging wrath or a warrior uses Avatar. Another example would be to not recommend Disable if the target has Blessing of Freedom active.

I know you probably don't care much for PVP support for this addon as it's primary purpose is for PVE DPS optimizations, but I can think of a few PVE uses this could have. One would be if you were a mage and wanted to recommend Spell Steal only when an important buff is up on the target that would improve you DPS if you stole it. Another example could be for Tranquilizing Shot for when a frenzy effect is up on the target. One last example I could think of is if during a boss fight the boss becomes immune temporarily to damage and has a buff up to indicate as such. I'm sure there's other examples such as purging particular spells, but you get the idea.

**Comment by Hekili** [comment]
I'm not opposed to this, but implementation would be challenging.  For instance, if you refer to a buff to decide whether to Purge from your target, the addon won't know that particular aura is getting purged and might recommend Purge repeatedly.

More generically, you can refer to `buff.dispellable_magic.up` to see if your target has something dispellable (but without the specific spell ID).  The same is true for `buff.dispellable_enrage.up`, `buff.dispellable_curse.up` and so on.

**Comment by Hekili** [comment]
Adding this to the backlog, as it may be a side-effect of other target and aura handling changes that are coming.

**Comment by Hekili** [comment]
Closing for housekeeping; if any old tickets are still desired, I'll watch for updated requests.
