### ISSUE TITLE
Lightning Lasso channel causes Lua errors.

### ISSUE THREAD

**Issue by danielsql** [Hekili/hekili#754]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**Message: Interface\AddOns\Hekili\Core.lua:448: attempt to index local 'a' (a nil value)
Time: Mon Dec 28 15:54:49 2020
Count: 33
Stack: Interface\AddOns\Hekili\Core.lua:448: attempt to index local 'a' (a nil value)
[string "@Interface\AddOns\Hekili\Core.lua"]:448: in function `CheckChannel'
[string "@Interface\AddOns\Hekili\Core.lua"]:1475: in function `ProcessHooks'
[string "@Interface\AddOns\Hekili\UI.lua"]:820: in function <Interface\AddOns\Hekili\UI.lua:685>

Locals: self = <table> {
 GetMacroCastTarget = <function> defined @Interface\AddOns\Hekili\Events.lua:1280
 GetTTD = <function> defined @Interface\AddOns\Hekili\Targets.lua:840
 DeserializeStyle = <function> defined @Interface\AddOns\Hekili\Options.lua:9354
 modules = <table> {
 }
 EmbedAbilityOptions = <function> defined @Interface\AddOns\Hekili\Options.lua:3789
 Scripts = <table> {
 }
 GetDeathClockByGUID = <function> defined @Interface\AddOns\Hekili\Targets.lua:825
 GetPetBasedTargetSpells = <function> defined @Interface\AddOns\Hekili\Targets.lua:88
 After = <function> defined @Interface\AddOns\Hekili\Utils.lua:268
 Run = <function> defined @Interface\AddOns\Hekili\Hekili.lua:263
 UpdateDisplayVisibility = <function> defined @Interface\AddOns\Hekili\UI.lua:1643
 IsEnabled = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 KeybindInfo = <table> {
 }
 RemoveHold = <function> defined @Interface\AddOns\Hekili\State.lua:6017
 GetPetBasedTargetSpell = <function> defined @Interface\AddOns\Hekili\Targets.lua:100
 ToggleHold = <function> defined @Interface\AddOns\Hekili\State.lua:6042
 SpecializationChanged = <function> defined @Interface\AddOns\Hekili\Classes.lua:5144
 UpdateUseItems = <function> defined @Interface\AddOns\Hekili\Events.lua:656
 SetSpecOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3576
 GetDefaults = <function> defined @Interface\AddOns\Hekili\Options.lua:535
 dumpKeyCache = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDisplayByName = <function> defined @Interface\AddOns\Hekili\Core.lua:1283
 Options = <table> {
 }
 ReInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:161
 npUnits = <table> {
 }
 GetAbilityInfo = <function> defined @Interface\AddOns\Hekili\Classes.lua:5090
 State = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\Hekili\Core.lua:184
 Version = "v9.0.2-1.0.31"
 CmdLine = <function> defined @Interface\AddOns\Hekili\Options.lua:8938
 IsDisplayActive = <function> defined @Interface\AddOns\Hekili\UI.lua:1742
 SetupPetBasedTargetDetection = <function> defined @Interface\AddOns\Hekili\Targets.lua:114
 ShowDiagnosticTooltip = <function> defined @Interface\AddOns\Hekili\UI.lua:2330
 Notify = <function> defined @Interface\AddOns\Hekili\Options.lua:10059
 OnInitialize = <function> defined @Interface\AddOns\Hekili\Core.lua:61
 NewModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetErrors = <function> defined @Interface\AddOns\Hekili\Utils.lua:41
 EmbedItemOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3918
 DumpPetBasedTargetInfo = <function> defined @Interface\AddOns\Hekili\Targets.lua:140
 SetPackShareOption = <function> defined @Interface\AddOns\Hekili\Options.lua:3560
 CreateButton = <function> defined @Interface\AddOns\Hekili\UI.lua:1780
 ReleaseHolds = <function> defined @Interface\AddOns\Hekili\State.lua:6074
 Deserialize = <function> defined @Interface\AddOns\Details\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 SaveDebugSnapshot = <function> defined @Interface\AddOns\Hekili\Hekili.lua:332
 SetSpecPref = <function> defined @Interface\AddOns\Hekili\Options.lua:3617
 HasSnapped = false
 GetName = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 RunSpellCallbacks = <function> defined @Interface\AddOns\Hekili\Events.lua:289
 GetSpec = <function> defined @Interface\AddOns\Hekili\Classes.lua:54

**Comment by danielsql** [comment]
Lightning Lasso - Shaman Elemental

**Comment by Hekili** [comment]
I need your Issue Reporting tab information.

**Comment by danielsql** [comment]
oh, sorry
thats it?
build: v9.0.2-1.0.31
level: 43 (43)
class: SHAMAN
spec: enhancement

talents: earth_shield
    elemental_assault
    forceful_winds
    natures_guardian
    stormflurry

pvptalents: grounding_totem
   skyfury_totem
   spectral_recovery

covenant: none

conduits: none

soulbinds: []

sets: none

gear: anelsinete_do_tempestigador = 1
    banana_jakificada = 1
    botinas_torcalin = 1
    capa_herdada_do_baro_negro = 1
    clava_de_marfim_de_hipossabre = 1
    corrente_torcalin = 1
    dolo_de_voljamba = 1
    elmo_desgastado_do_berserker_enraivecido = 1
    elo_do_torceesprito = 1
    espaldares_torcalin = 1
    fatiador_de_berserker_amani = 1
    guardapernas_do_chifre_verde = 1
    luvas_encadeadas__prova_de_mordida = 1
    munhequeiras_torcalin = 1
    peitoral_causamortis_do_campeo = 1
    tabardo_dos_vulperas = 1
    vontade_eterna_do_mrtir = 1

legendaries: none

itemIDs: 122246, 122261, 122379, 122668, 134681, 155304, 155892, 158410, 158421, 158446, 159116, 159763, 160947, 161125, 161139, 174069, 175289

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = true
    mode = single
    potions = false

**Comment by danielsql** [comment]
oh, sorry
thats it?
build: v9.0.2-1.0.31
level: 43 (43)
class: SHAMAN
spec: elemental

talents: echo_of_the_elements
    echoing_shock
    master_of_the_elements
    natures_guardian
    spirit_wolf

pvptalents: lightning_lasso
   skyfury_totem
   spectral_recovery

covenant: none

conduits: none

soulbinds: []

sets: none

gear: anelsinete_do_tempestigador = 1
    banana_jakificada = 1
    botinas_torcalin = 1
    capa_herdada_do_baro_negro = 1
    clava_de_marfim_de_hipossabre = 1
    corrente_torcalin = 1
    dolo_de_voljamba = 1
    elmo_desgastado_do_berserker_enraivecido = 1
    elo_do_torceesprito = 1
    espaldares_torcalin = 1
    fatiador_de_berserker_amani = 1
    guardapernas_do_chifre_verde = 1
    luvas_encadeadas__prova_de_mordida = 1
    munhequeiras_torcalin = 1
    peitoral_causamortis_do_campeo = 1
    tabardo_dos_vulperas = 1
    vontade_eterna_do_mrtir = 1

legendaries: none

itemIDs: 122246, 122261, 122379, 122668, 134681, 155304, 155892, 158410, 158421, 158446, 159116, 159763, 160947, 161125, 161139, 174069, 175289

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Elemental
    petbased = false
    potion = potion_of_spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    stack_buffer = 1.1

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = true
    mode = single
    potions = false

**Comment by Hekili** [comment]
So far, I've found this to occur on non-enUS clients (I tested esMX) only.  Interesting.

**Comment by Hekili** [comment]
This should be fixed in 1.0.32-beta2 and the future 1.0.32 release.
