### ISSUE TITLE
[Sub Rogue] Incorrect keybind reading in shadow dance.

### ISSUE THREAD

**Issue by GamingSeat** [Hekili/hekili#755]
Addon version: Up to date, updated today before the issue occured.

Repeat post: Did not see a repeat of this as far as I could tell?

**Describe the Bug/Issue**
When I go into my shadow dance rotation the addon begins to read off abilities and says to press 2 for Eviscerate and 3 for Rupture but they're bound to W and Q respectively. I have my eviscerate and rupture on bar 2, bar 1 is my stealth bar and contains all my stealth abilities which is what "changes" based on stance. 

Note: This does not happen on any other classes I have. This is solely an issue with my shadow dance.
This is with ElvUI which is also fully updated.

**To Reproduce**
- Go to any NPC
- Click on "Shadow Dance"
- Start rotation until you see a combo point spender suggested
- See error

**Expected behavior**
The rotation should be suggesting the use of Q and W binds rather than 2 and 3 which are entirely different spells.

**Screenshots**
[https://imgur.com/a/7ULc6ga](url)

**PUT ISSUE REPORT LINK HERE:**
[https://pastebin.com/NtKfbtZW](url)
 
**PUT SNAPSHOT LINK HERE:**
[https://pastebin.com/SeMGWP9E](url)

**Comment by Hekili** [comment]
I'll revert the change in 1.0.32; thanks for the report.

**Comment by GamingSeat** [comment]
> I'll revert the change in 1.0.32; thanks for the report.

Thanks for your hard work, appreciated :)

**Comment by Hekili** [comment]
Latest betas should have this resolved.
