### ISSUE TITLE
Latest update broke WW FoF break?

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#757]
Just updated the Addon with the latest changes from the beta. I know it's beta, but I guess it's there for testing and use anyways.

I've not changed anything apart from updating the addon. Used to suggest to break FoF but no longer. I even reset my profile and still the same. 

https://pastebin.com/GsuvkbuG

**Comment by Hekili** [comment]
Please fill out the complete ticket when submitting.  But yes, I'm working on channeling stuff in beta.

**Comment by Hekili** [comment]
-beta3 should be fine.

**Comment by Smudgiee** [comment]
Can confirm, fixed. Thank you and next time I will, sorry.
