### ISSUE TITLE
State.lua error - Shadow Priest in Dungeon

### ISSUE THREAD

**Issue by jacii9467** [Hekili/hekili#758]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.2-1.0.32-beta2
level: 60 (60)
class: PRIEST
spec: shadow

talents: body_and_soul
    fortress_of_the_mind
    hungering_void
    last_word
    misery
    shadow_crash
    void_torrent

pvptalents: none

covenant: necrolord

conduits: dissonant_echoes = 3
   lights_inspiration = 4

soulbinds: [plague_deviser_marileth]
   oozs_frictionless_coating = 1
   volatile_solvent = 1

sets: none

gear: charm_of_eternal_winter = 1
    cinch_of_infinite_tightness = 1
    confidants_favored_cap = 1
    contaminated_gauze_wristwraps = 1
    death_gods_signet = 1
    drape_of_twisted_loyalties = 1
    grimveiled_mittens = 1
    inscrutable_quantum_device = 1
    manastorms_magnificent_threads = 1
    nathrian_ferula = 1
    purge_protocol_legwraps = 1
    reanimators_mantle = 1
    signet_of_the_false_accuser = 1
    slippers_of_the_forgotten_heretic = 1
    soulletting_ruby = 1

legendaries: eternal_call_to_the_void = 1

itemIDs: 173244, 178740, 178806, 178809, 178824, 178829, 179335, 179350, 179355, 180107, 180123, 182979, 183021, 183028, 183040

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Shadow
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_ascended_blast = true
    pad_void_bolt = true
    stm_timer = 22

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

https://pastebin.com/01L0DsJk

**Comment by Hekili** [comment]
Try -beta4 and let me know if you see the error again.

**Comment by Hekili** [comment]
Appears resolved.
