### ISSUE TITLE
[FEATURE/REQUEST] Diminishing Return Library Connection

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#759]
Hi! I found a good and constantly updating library of Diminish Return spells (diminishing of stuns and other crowd control (CC) spells) and I'd like to suggest implementing its functionality into Hekili addon.

As for PvE it can be very useful in mythic plus and Torgast clearing in a group. Because there are many situations when you have to CC a a target and it would be nice to optimise addon's recomendations with accounting to CC use and its DR.

Here is the link to the library with list of spells.
https://www.curseforge.com/wow/addons/drlist-1-0

And here is a good-working addon to track DR with nice logic behind it.
https://github.com/wardz/Diminish

**Comment by Hekili** [comment]
This is interesting, though the implementation could be a bit challenging.  I'd probably have to create fake auras like `buff.stun_dr.up` and so forth.  Not sure how I'd do this, yet.

**Comment by IIeTpoc** [comment]
There is also a weakaura that has a decent logic in counting DRs (like 1st DR makes a CC 50% effective and 2nd one makes CC only 25% effective and this weakaura is able to count the quantity of repetitive CC spells which might be helpful in organising the logic of DR and CC duration)

Link to the weakarua: https://wago.io/1_8A7rUPo

**Comment by CKATEPTb** [comment]
I would like to raise this issue

**Comment by CKATEPTb** [comment]
Ok)
