### ISSUE TITLE
Shadow priest target cycling

### ISSUE THREAD

**Issue by Bastyani** [Hekili/hekili#76]
Hey. Any chance to implement Shadow Priest dot target cycling. I know it was working for monk but no idea if it was ever supposed to be a feature for SP.
Thanks.

**Comment by Hekili** [comment]
Have you tried this with target cycling enabled in Shadow's options?

**Comment by Bastyani** [comment]
Yes I did. Also tried *Detect enemies by Damage over Time*

**Comment by Hekili** [comment]
Had you hit the other targets with anything?  You can't detect targets at range without actually hitting them.

**Comment by Bastyani** [comment]
Yes. I tried everything. I dotted all the targets but it never suggests to reapply dots afterwards.

**Comment by Hekili** [comment]
DOT target cycling should work in the latest builds.  Please submit a new ticket if you've enabled "Recommend Target Swaps" in Shadow > Targeting and it is not satisfactory.  Thanks!
