### ISSUE TITLE
Affliction Warlock delaying MR later in fights?

### ISSUE THREAD

**Issue by towicode** [Hekili/hekili#763]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

For some reason during the 2nd burst window. aka the second time "summon darkglare" comes off cooldown, the addon is recommending to apply dots instead of casting MR (malefic rapture). I think the addon for some reason doesn't think I have the dots applied. I'm not entirely sure. I've provided all the screenshots and profiles below.

The correct sequence here should be (mr, mr, mr... (until out of soul shards))

**To Reproduce**
Play aff lock, follow hekili, go through one normal rotation w/ summon darkglade. On the second rotation you should see the issue. (so the issue happens around 3 minutes into the fight)

**Expected behavior**
If a warlock has all of his dots + haunt on the target + has soul shards he should be using MR. The addon correctly displays this behavior on the first round but for some reason never on the second round. Furthermore, you shouldn't refresh a dot while it still has 15+ seconds left. .So something is for sure incorrect.

**Screenshots**
You can see from my UI that I have all dots applied (bottom bars), I also have just recently cast summon darkglare and darksoul misery. This screen shot was taken a second after I paused hekili for the profile snapshot
![image](https://user-images.githubusercontent.com/8232247/103369652-ecded900-4a87-11eb-8f45-aa4fe221ca58.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/N4m9s4Z1

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/H2ajyL3w

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Interesting; the durations on your dots in the screenshot aren't matching your snapshot.  I don't know if that means your screenshot and your snapshot were taken at different times, or if aura refresh events aren't firing so the addon's information doesn't get updated.

Did you take the screenshot and snapshot at the same time?

> The addon correctly displays this behavior on the first round but for some reason never on the second round. Furthermore, you shouldn't refresh a dot while it still has 15+ seconds left.

You haven't shown anything where dots are being refreshed with 15+ seconds left.

**Comment by Hekili** [comment]
Try 1.0.32-beta5 under Releases and see if you still have issues.

**Comment by towicode** [comment]
I tried the new version and what I experienced was that during the second darkglare window the recommendation rapidly changed. Once again it did show corruption, but then it displayed MR, but then it would go back to corruption and then it finally settled on MR. 

I'll report back on this issue with more snapshots tomorrow, leaving for the day. I'll record some screen casts and see if I can capture multiple snapshots

**Comment by Hekili** [comment]
Yeah, I'm not seeing what you described in my own testing, so your description of it being consistent doesn't match up with what I find.  If you could answer the question(s) from my first response, that'd also be helpful.

**Comment by towicode** [comment]
I took the screen shot right after the pause, maybe 1-2 second delay. And the 15 second thing was a gross generalization. I have experienced it recommend a dot when my dot bar was full. My dot bar is full from any duration from 10 seconds to max duration of the dot. 

I will try to provide more snapshots for this issue.

**Comment by towicode** [comment]
@Hekili I'm hoping these images help. What I'm noticing is that it doesn't seem that hekili is immediately getting the update when summon darkglare extends the length of dots. I know you'd prefer the snapshots, but since I have to wait 3 minutes to do this they are a bit hard to get. Is there a hekili mode where it debugs every recommendation? 


Screenshot story.

at 3:12 into the fight I activate summon darkglare
![image](https://user-images.githubusercontent.com/8232247/103396296-97d6ad80-4aef-11eb-82e7-a8636df10ebe.png)

the very next frame the length of corruption goes up to 10 seconds, Hekili is still recommending it.
![image](https://user-images.githubusercontent.com/8232247/103396308-a8872380-4aef-11eb-9038-ef6616d23c03.png)

After I cast Corruption, the recommendations all change to MR. So it's really not a huge deal. I'm only losing one GCD which is so small, but it can be confusing in the fight as you can see from the previous image it's even recommending UA in the 3rd slot.
![image](https://user-images.githubusercontent.com/8232247/103396339-dcfadf80-4aef-11eb-8b94-8d5ab9a10386.png)

I'm gonna try a couple more times to get the snapshot, if I can I'll post it here.

**Comment by towicode** [comment]
I got a snapshot. This snapshot is taken right at ~ 3:12 into a fight (separate combat of the screenshots above). The previously cast spell was summon dark glare. Because darkglare extends the length of the DOTS the next cast should be MR. However, hekili is recommending UA.

https://pastebin.com/jyuD8v9q

**Comment by Hekili** [comment]
Testfix for this in -beta6.

**Comment by Hekili** [comment]
Appears resolved; closing.
