### ISSUE TITLE
Some variables of the form "cooldown.#SPELLNAME.remains" have incorrect values

### ISSUE THREAD

**Issue by ghost** [Hekili/hekili#764]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version. **Answer - I am running the latest version of Hekili.**

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports. **Answer - They have not. **

**Describe the Bug/Issue**
cooldown.#SPELLNAME.remains (where #spellname is the name of an arbitrary spell as represented in a priority.) An example of this is the following snapshot - I was testing whether Immolation Aura would correctly be not chosen because Fiery Brand was about to come off CD - specifically, it has <10 seconds left - however, cooldown.fiery_brand.remains instead had the value of 52 (seconds), which is max CD for the spell with my current conduits. From further testing, the value of cooldown.fiery_brand.remains appears to be stuck at this value even after casting it again.

[fiery brand actually at less than 10 secs CD remaining.txt](https://github.com/Hekili/hekili/files/5757020/fiery.brand.actually.at.less.than.10.secs.CD.remaining.txt)

Another instance of incorrect value for this variable - cooldown_fel_devastation.remains is stuck at 45 (seconds), despite the CD of the spell being 60 seconds

**To Reproduce**
-Use current Vengeance priority in Hekili
-Open entry 5 in the "normal" action list
-Hover mouse over the "conditions" window
-Cast Fel Devastation
-Hover mouse over the "conditions" window again

**Expected behavior**
Prior to casting, mousing over the conditions window should indicate that the variable cooldown.fel_devastation.remains has the value of 0. Shortly after casting, the variable should have the value of approximately 60 (per the 1 minute CD) and counting down. Instead it constantly has the value of 45.

**Screenshots**

![fel dev ss](https://user-images.githubusercontent.com/74689640/103406830-e6e10a80-4b10-11eb-883a-043d29538467.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/fXPteJeK

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**Answer - I don't disagree with the addon's recommendations given the state of the variable; however, some variables of the format cooldown.#SPELLNAME.remains appear to have incorrect values, resulting in the addon giving incorrect recommendations.**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

No error - addon giving incorrect recommendations due to incorrect variable value.

**Comment by ghost** [comment]
From further testing, it looks like disabling a spell under Toggles causes variables associated with the spell (such as the above examples) to be held at a default value. Knowing this, it looks like I should un-disable these spells under Toggles and modify the specific priority steps that would trigger them (to ensure they are not returned as recommendations.) No further action needed here from your end.

**Comment by Hekili** [comment]
Good job investigating this.

You can use `cooldown.X.true_remains` to bypass the feigned cooldowns of toggled/disabled abilities.  The feigned cooldown helps support priorities that do some kind of prep work before a big cooldown becomes available, so that you're not just repeatedly doing that prep work but never pressing the cooldown ability.
