### ISSUE TITLE
Demonic Consumption

### ISSUE THREAD

**Issue by fumbaba** [Hekili/hekili#77]
When using the Demonic Consumption talent Hekili will, at times and often, suggest Implosion directly after Summon Demonic Tyrant. When using Demonic Consumption you will have no imps to use for Implosion, making it a null skill in that moment. It should not suggest these skills in this order: Summon Demonic Tyrant>Implosion. It will get stuck on Implosion as the next suggestion long enough to cause rotation issues and dps loss. Just a little issue I've run across that can easily be replicated on a dummy, as it's a common suggestion in my experience. Btw much <3 I used Hekili through Legion and have recruited many people into using it since.

**Comment by fumbaba** [comment]
When using the Demonic Consumption talent Hekili will, at times and often, suggest Implosion directly after Summon Demonic Tyrant. When using Demonic Consumption you will have no imps to use for Implosion, making it a null skill in that moment. It should not suggest these skills in this order: Summon Demonic Tyrant>Implosion. It will get stuck on Implosion as the next suggestion long enough to cause rotation issues and dps loss. Just a little issue I've run across that can easily be replicated on a dummy, as it's a common suggestion in my experience. Btw much <3 I used Hekili through Legion and have recruited many people into using it since.

**Comment by Hekili** [comment]
You should try mashing Implosion while casting Summon Demonic Tyrant.

It will (for now) still consume your imps, because they don't die immediately, granting you the Explosive Potential buff.

Optimal play for Demonology currently involves making use of this mechanic, until 8.1.5.
