### ISSUE TITLE
Balance: No longer using Convoke when COOLDOWNS OFF and COVENANTS ON

### ISSUE THREAD

**Issue by Smoothglobal** [Hekili/hekili#770]
For the last few days, I have noticed if I turn COOLDOWNS OFF but leave COVENANTS ON, that I no longer ever get Convoke. Now, I am not sure if something changed in the latest release but I did notice this in the latest release notes:

Balance APL updates.
Map druid.no_cds to toggle.cooldowns.

Is there something that has changed or some way to revert back to the old behavior?

If I turn COOLDOWNS ON then convoke is recommended with my CA. 

I just installed the latest beta and I am still having this issue.

Am I doing something wrong? I liked being able to turn off my 3 min cooldown but have my 2 min convoke cast when I want it to.

Thanks for the great addon!

**Comment by Hekili** [comment]
Yes, the logic for Convoke relies on CA.  It's intentionally written that way, but arguably could be changed.

**Comment by Smoothglobal** [comment]
Okay, but something changed? It used to be that I could fire convoke by turning on COVENANTS with COOLDOWNS off?

I assume it changed on the new release a few days ago?

**Comment by bitnoir** [comment]
Hi and thanks for the great addon! Is there any way to manually make Convoke shows like before, when I didn't have to toggle COOLDOWNS on? For now I have toggled COOLDOWNS on but deactivated any other cooldown abilities except Convoke. To be honest I preferred it as it was a few days before.

**Comment by Smoothglobal** [comment]
Definitely something changed here:

Balance APL updates.
Map druid.no_cds to toggle.cooldowns.

Was this intentional or was it "broken" before that we could fire of Convoke by turning Covenants on and Cooldowns off?

**Comment by Hekili** [comment]
Yeah, the usage of "druid.no_cds" does prevent Convoke there and doesn't really make a whole lot of sense in-game.  I'll be revising it.

**Comment by Hekili** [comment]
This should be resolved in 1.0.32.
