### ISSUE TITLE
Use a title that describes the problem scenario.

### ISSUE THREAD

**Issue by ramenloverninja** [Hekili/hekili#771]
**Describe the Bug/Issue**

The addon is suggesting an ability I don't have

**To Reproduce**

When I use Symbols of Death and the buff is up the addon suggests using the ability I don't have. The ability has the same icon as the Lightforged Warframe.

**Expected behavior**

The addon should suggest going into shadow dance and continue the rotation

**Screenshots**
![image](https://user-images.githubusercontent.com/76824014/103425068-889a4300-4b75-11eb-9cd7-8c7b9cbcf6b9.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.2-1.0.31
level: 60 (60)
class: ROGUE
spec: subtlety

talents: cheat_death
    deeper_stratagem
    enveloping_shadows
    master_of_shadows
    nightstalker
    prey_on_the_weak
    weaponmaster

pvptalents: none

covenant: night_fae

conduits: perforated_veins = 2

soulbinds: [niya]
   grove_invigoration = 1
   run_without_tiring = 1

sets: none

gear: ashjrakamas_shroud_of_resolve = 1
    briarbane_signet = 1
    chain_of_the_purposebound = 1
    digested_interrogators_gaze = 1
    duskwarder_knife = 1
    gloves_of_corrupted_waters = 1
    harmonias_chosen_belt = 1
    macabre_ritual_pants = 1
    oakheart_vestment = 1
    overflowing_ember_mirror = 1
    ring_of_collective_consciousness = 1
    runetender_bracers = 1
    runetender_shoulderguards = 1
    sinsoaked_waders = 1
    tanglewood_thorn = 1
    withergrove_shardling = 1

legendaries: none

itemIDs: 159321, 169223, 174143, 174530, 177657, 178077, 178710, 178760, 178837, 179500, 179774, 180444, 181418, 181429, 183851, 184757

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Subtlety
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    mfd_waste = false
    priority_rotation = false
    solo_vanish = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
![image](https://user-images.githubusercontent.com/76824014/103424973-fb56ee80-4b74-11eb-8d52-8c0cda718c23.png)

**Comment by Hekili** [comment]
It's your trinket.
