### ISSUE TITLE
Rogue Sub - The APL seems to be not optimized as it should

### ISSUE THREAD

**Issue by Kylvan-8** [Hekili/hekili#772]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

For Rogue Subtely, the APL is surely not find at all and at least not for my char.

- Shadowstrike / Black Powder isn't rightly displayed in the APL, letting always place to Eviscerate.
- The numbers of ennemies isn't considered as if you have to do Tempest / Eviscerate for 2 ennemies or SS / Eviscerate for two ennemies. Many times the APL is wrong there.
- Rupture is focusing only on one ennemie, but many times rupture need to be applied on more than 1 target and the APL doesn't tell you that. The APL for Altimor fight is completly wrong (not working at all as excepted in a similar Sim)
- Finality Legendary Power isn't well considered as to manage the APL from what i've seen.
- There is way to much differences between the rotation for the sim of a char and the actual APL (not in a good way)
- Trinkets and Shadowblade are barely never used in APL.

There is more as the gamplay of Sub is precise but it will be better if some facts has explained in this guide could be considered in the APL working in adequation with SimC (ofc).

- https://www.ravenholdt.net/guides/subtlety-rogue-guide/
- https://www.ravenholdt.net/guides/subtlety-rogue-guide-battle-for-azeroth-raid-dps/

**My SIM**

- https://www.raidbots.com/simbot/report/6MjDV1f65mEPj8nqaSkAU3

**Expected behavior**

- A great APL with an adaptative, not messy way, to really optimize the rotation, all things considered.

**Screenshots**

Following Hekili APL, this is what i get :

![wowanalyzer](https://user-images.githubusercontent.com/61290148/103413307-e11b1180-4b70-11eb-882c-12961b24d56b.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**https://pastebin.com/7Wd50sjy**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
1/  https://pastebin.com/03c4vpHY
2/  https://pastebin.com/ZqYxRybb
3/  https://pastebin.com/fyw0yRfA
4/  https://pastebin.com/K9auy2bJ

**Comment by Hekili** [comment]
Can you provide context for your snapshots?  What do you disagree about with the snapshot?  What should you have seen instead?

**Comment by Hekili** [comment]
After review, most of this is a result of fundamentally misunderstanding the addon and/or its configuration.  (It's not as intuitive as I might like, but 

> Shadowstrike / Black Powder isn't rightly displayed in the APL, letting always place to Eviscerate.

This is what the "Use Priority Rotation (Funnel Damage)" setting does, which you have enabled.

> The numbers of ennemies isn't considered as if you have to do Tempest / Eviscerate for 2 ennemies or SS / Eviscerate for two ennemies. Many times the APL is wrong there.

Not sure what you mean here, but you don't have "Recommend Target Swaps" checked under /hekili > Subtlety > Targeting, so it is not going to recommend actions that cause you to swap your target.  (Most users don't like being told to swap targets, and most fights aren't sustained multi-target where multidotting as melee is especially effective.)  You can check it and try it out instead.

> Rupture is focusing only on one ennemie, but many times rupture need to be applied on more than 1 target and the APL doesn't tell you that. The APL for Altimor fight is completly wrong (not working at all as excepted in a similar Sim).

No, same as the previous point, it's following your settings.

> Finality Legendary Power isn't well considered as to manage the APL from what i've seen.

For this piece, I'm inclined to agree with you -- I don't see it really factored into the SimC priority at all.  The addon does model it properly, but the APL doesn't really check for one of the finality buffs and adjust its recommendations accordingly.

If/when sim profiles are enhanced to optimize that legendary power, the same enhancements will carry over to this addon.

> There is way to much differences between the rotation for the sim of a char and the actual APL (not in a good way)

This is meaningless.

> Trinkets and Shadowblade are barely never used in APL.

You'd demonstrate this by posting a snapshot where Shadow Blades is available and you think it should be recommended, but it isn't.  Or that your trinket is available, you think you should use it, and it's not recommended.

But looking at one of your snapshots, you have Cooldowns toggled off.  Therefore, your cooldown abilities would not be recommended.  See /hekili > Toggles.

Based on this, I'm going to close this ticket and encourage you to familiarize yourself more with this tool.  You may also want to follow-up with Ravenholdt about Finality and whether it's appropriately utilized in the sims.

**Comment by Kylvan-8** [comment]
@Hekili  Thanks for your points about setting up the tool. But it's not possible that trinkets and shadowblades aren't used in the APL. You didn't even look to the sim that actually use everything. If you would have take the time to read the entire post, you will see that i'm coming from Ravenholdt.

The context of the snapshots are explained in the first place of this post, they was taken in MM+.

> There is way to much differences between the rotation for the sim of a char and the actual APL (not in a good way)

As the trinkets and shadowblades aren't used, for example. And they are in SimC.

**Comment by Hekili** [comment]
I answered those points in my response.
