### ISSUE TITLE
Del

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#774]
del

**Comment by Hekili** [comment]
Why would you delete the part of the ticket instructions regarding snapshots? You'll need to provide snapshots of this actually occurring.

**Comment by Dragonfo** [comment]
The first time I addressed a problem in your addon in the UH rotation. And the answer simply concerns more about why remotely, and not to understand the problem .... Thanks, but I'd rather find someone who will fix this problem for me in the addon .... You are just a disgusting person.

**Comment by Hekili** [comment]
If you decide you'd like to provide the information needed to troubleshoot your report, you're still welcome to do so.

Happy New Year!
