### ISSUE TITLE
shadow priest

### ISSUE THREAD

**Issue by roces43** [Hekili/hekili#776]
-Shadow priest
-Covenant: necrolord
Does not exist in the dps rotasion , only if i set cooldown setting off please help me out ty!

**Comment by roces43** [comment]
there is a problem with shadow priest necrolord covenant it doesnt show the covenant spell named "unholy nova" in the rotasion please fix it

**Comment by Hekili** [comment]
Yes, it does, and you need to submit complete tickets following the instructions if you would like further investigation.
