### ISSUE TITLE
Trinkets can't be added to cooldowns

### ISSUE THREAD

**Issue by Greenstriped** [Hekili/hekili#779]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
I am sorry if this isn't a bug, but it appears to be. Issue is with adding trinkets to my cooldown list. More specifically, I wish to add a trinket to my CD list rather than have it appear in my regular primary window.

**To Reproduce**
- Go to specific spec in options (in my case Outlaw)
- Click on Toggles
- Under the Cooldowns section, click "add ability"
- Select any trinket (nothing happens)

**Expected behavior**
I was hoping when I opened this list and saw that trinkets are in fact available in the list of potential options, that it should work to shuffle my trinket here. However, when I select the trinket I wish to use (in my case, Memory of Past Sins) nothing happens at all. If I select any ability from this window, they are added to the cooldown list exactly as expected, but trinkets disappear when I try.

build: v9.0.2-1.0.32
level: 60 (60)
class: ROGUE
spec: outlaw

talents: acrobatic_strikes
    alacrity
    blade_rush
    cheat_death
    dirty_tricks
    quick_draw
    vigor

pvptalents: none

covenant: night_fae

conduits: count_the_odds = 4
   quick_decisions = 4
   sleight_of_hand = 5

soulbinds: [dreamweaver]
   podtender = 1
   soothing_voice = 1

sets: none

gear: ardent_sunstar_signet = 1
    azurevenom_choker = 1
    bleakwing_assassins_grips = 1
    cowled_batwing_cloak = 1
    decanter_of_animacharged_winds = 1
    fastened_venombarb_binds = 1
    memory_of_past_sins = 1
    miasmalacquered_jerkin = 1
    remorse = 1
    shadowghast_ring = 1
    sinful_gladiators_fang = 1
    skyterrors_stonehide_leggings = 1
    vicious_surge_faceguard = 1
    viscerastitched_footpads = 1
    waistcord_of_dark_devotion = 1
    wicked_bladewing_pauldrons = 1

legendaries: celerity = 1

itemIDs: 155943, 178731, 178819, 178823, 178858, 178861, 178926, 178934, 179495, 180106, 180115, 183007, 183009, 183034, 183035, 184025

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Outlaw
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    dirty_gouge = false
    mfd_waste = true
    solo_vanish = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/103490618-1b8fe300-4deb-11eb-873c-aeeefd0520a0.png)

![image](https://user-images.githubusercontent.com/9438134/103490630-33fffd80-4deb-11eb-9627-d166a76b401f.png)

The trinket should be on the Cooldowns toggle by default, though.
