### ISSUE TITLE
Hekili LUA Error

### ISSUE THREAD

**Issue by MrWittur** [Hekili/hekili#78]
Date: 2019-03-08 20:29:27
ID: 1
Error occured in: Global
Count: 1
Message: ...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua line 1019:
   Attempt to register unknown event "GLYPH_ADDED"
Debug:
   [C]: RegisterEvent()
   ...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1019: activate()
   ...ngeCheck-2.0\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1065: in main chunk
Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "GLYPH_ADDED"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BasicBuffs, vv8.0.1
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  BigWigs, vv138.1
  DejaCharacterStats, v800r116
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.91
  FasterLoot, v1.0
  Hekili, v6.2.0.1
  Stubby, v8.1.6240 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=499)

**Comment by Hekili** [comment]
It looks like you may have LibRangeCheck installed independently of my addon, overriding the version provided by the addon.

GLYPH_ADDED is not used by any modern LibRangeCheck since that event doesn't fire any more.  It is not included in my addon.
