### ISSUE TITLE
[Affliction] - Summon Darkglare and Dark Soul: Misery not being recommended

### ISSUE THREAD

**Issue by whoaisjustin** [Hekili/hekili#781]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Two cooldowns, Summon Darkglare and Dark Soul: Misery, are not being recommended. Confirmed they are both on the Cooldowns toggle and this is toggled on. NOTE: I am only level 53. If this is simply an issue of not being max level, please slap my hands and close. I think perhaps because there's a higher rank of Corruption and UA learned at higher levels, I'm never meeting the requirements for Darkglare to be recommended. Not sure why Dark Soul Misery isn't being suggested, so I think I'll still submit the ticket.

**To Reproduce**
Attacking target dummy in Stormwind.

**Expected behavior**
I'm not an expert on Affliction, but I would expect Summon Darkglare to be recommended after Corruption, Agony, Unstable Affliction, etc. are on the target. Dark Soul: Misery would be suggested near pull, I would think. 

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/f5yUZx4X

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
Snapshot not useful, as it's not being recommended. 

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

No error message.

**Comment by whoaisjustin** [comment]
Snapshot w/ DoTs: https://pastebin.com/0fmgu08u

Strange, because the add-on was definitely recommending Drain Soul, not Malefic Rapture.

**Comment by whoaisjustin** [comment]
Cooldown snapshot: https://pastebin.com/28wVBBn6

**Comment by whoaisjustin** [comment]
![image](https://user-images.githubusercontent.com/15135401/103491091-c3f37680-4dee-11eb-8141-6485973587ea.png)

**Comment by Hekili** [comment]
This should be resolved in 1.0.33 with the support for `covenant.none` added.

**Comment by Hekili** [comment]
Additional tweaks made that will be out in next update.
