### ISSUE TITLE
Hekili packages latest Ace3, currently interferes with ElvUI options.

### ISSUE THREAD

**Issue by sebastianlang84** [Hekili/hekili#783]
Since today my ElvUI options menu is disabled while having Hekili enabled.
![image](https://user-images.githubusercontent.com/24494724/103550544-57897d80-4ea9-11eb-8370-6c4d7ae558a5.png)

**Comment by NoobTaco** [comment]
Can confirm. Was on my way to report this as well.

**Comment by Hekili** [comment]
Do you use SilverDragon?

**Comment by sebastianlang84** [comment]
nope.. didnt even know about that

**Comment by Hekili** [comment]
This will mean that some library is updated that is impacting ElvUI, and is packaged with my addon.  We'll have to wait it out.  You can downgrade safely (or just downgrade the Libs folder from an older release).

**Comment by Hekili** [comment]
It's an Ace3 update; ElvUI will be fixing on their end.

https://discord.com/channels/209244641537556480/222356141785612288/795622706879922197

**Comment by sebastianlang84** [comment]
thx for clearing up!

**Comment by adamcadot** [comment]
I downgraded Hekili twice and ElvUI options are still broken. Any suggestions? I checked the other addons' issue queues and there is no mention of this issue.

**Comment by Hekili** [comment]
Then you have another addon supplying the new Ace3.  (If any addon supplies the new Ace3, all addons will use the new Ace3.)

There's a link right there to their discord discussion of it.

Here are my recommendations:

![image](https://user-images.githubusercontent.com/9438134/103560966-ac67cc80-4e86-11eb-8180-86bbdcf3cc2f.png)

**Comment by Hekili** [comment]
The new ElvUI is out; update to fix.

https://www.tukui.org/download.php?ui=elvui
