### ISSUE TITLE
Mauvais keybind

### ISSUE THREAD

**Issue by BeelyZ** [Hekili/hekili#784]
**Describe the Bug/Issue**
Hekilli m'affiche un autre keybind que celui que j'ai configurer sur un druide équilibre, alors que sur tous mes autres personnages il marche très bien, il peut meme m'afficher par exemple deux sort différent sur la même touche.

**Expected behavior**
Je ne saurais pas vraiment d'où le problème pourrait venir étant donner que sur mes autres personnages l'addons fonctionne très bien. 

**Screenshots**
https://imgur.com/a/CnZK6lF

**Comment by Hekili** [comment]
`Hekilli shows me another keybind than the one I have configured on a balance druid, while on all my other characters it works very well, he can even show me for example two different spells on the same key.`

`I wouldn't really know where the problem might come from given that on my other characters the addons work great.`

You may have your action bars set up in a weird order; remember that druids use action bar paging more than any other class.  The addon pulls keybindings from your bars starting from 1 - 10, except it moves the current action bar page to the front of the list when possible.

If you don't feel like searching through and potentially stripping entries from your action bars, you can set the keybind manually for any actions in `/hek` > Abilities> *select the ability* > Override Keybind Text.
