### ISSUE TITLE
How can i delete everything about the addon?

### ISSUE THREAD

**Issue by Unghiutza** [Hekili/hekili#785]
So, my question is as follows, i did some wrong settings, and i just want to return to default, but if i delete and reinstall addon, i still get those settings i fucked up. I tried deleting Hekili lua from savedvariables

**Comment by Hekili** [comment]
/hek > Profiles > Reset Profile, probably /reload after.

**Comment by Unghiutza** [comment]
> /hek > Profiles > Reset Profile, probably /reload after.

Ty <3
