### ISSUE TITLE
evlui issue

### ISSUE THREAD

**Issue by cm0918** [Hekili/hekili#786]
updated the addon this morning   logged into the game   went into evlui to change something and all the options headings were greyed out,  disabled the addon and i was able to fix it, re-enabled the addon and the options went back to being greyed out.   evlui was up to date when the issue was happeneing  12.16  i know there is an evlui update but this is an issue for those who dont update
![WoWScrnShot_010421_120826](https://user-images.githubusercontent.com/72286963/103593955-3fbff280-4ec5-11eb-8af8-7be9a3563090.jpg)

**Comment by Hekili** [comment]
Update ElvUI.
