### ISSUE TITLE
 No Death's Caress ability and very bad defense rotation.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#79]
Hello, please add Death's Caress when you are 30 yards away. That it was possible to do from a distance pool. And I also noticed that the addon, strive to inflict as much damage as possible, but it ignores the Death Strike when it is very necessary. Could you review the rotation of the BDK in defense? Since in fact he plays very badly in defense. Thank you so much for your work. I hope you do not ignore this question.

**Comment by Hekili** [comment]
Death's Caress added (only if refreshing Blood Plague, though).  The max DPS solution is to get into melee, but I understand you're wanting to kite.

Death Strike generally expects you to take a lot of damage before using it, but I've modified it to require less damage when you are soloing.
