### ISSUE TITLE
Hekili Blocking ElvUI Options

### ISSUE THREAD

**Issue by Laexxi** [Hekili/hekili#791]
Since the last update Hekili is not working with ElvUI. (Issue for me and my cousin). ElvUI Options can be shown, but are not working (Tabs on the left side are greyed out). After disableling Hekili everything is fine,

**Comment by Hekili** [comment]
Update ElvUI.

**Comment by 3kynox** [comment]
Evening, sorry to re-open but got the same problem and latest elvUi (12.16).
![image](https://user-images.githubusercontent.com/308755/103717153-a8d66180-4fbc-11eb-97b0-64341d5848b8.png)

Thanks in advance for help!

**Comment by Hekili** [comment]
![image](https://user-images.githubusercontent.com/9438134/103717310-24bbb400-4f93-11eb-9bfe-4dfa849cf4eb.png)
