### ISSUE TITLE
Hekili is making Elvui features unclickable

### ISSUE THREAD

**Issue by eternallydee** [Hekili/hekili#795]
When hekili is disabled, I'm able to edit my elvui settings just fine. However when Hekili is enabled, the options buttons are covered up by a box that doesn't allow me to click on anything behind it. 

You can view this here: 

Hekili enabled: https://i.imgur.com/jD3lCqm.png
Hekili disabled: https://i.imgur.com/DHMzAZc.png

Had a look through the hekili settings and nothing stood out to me.

**Comment by p4nchez** [comment]
update your elvui to 12.17 then its fixed
