### ISSUE TITLE
Unh DK suggestions bar disappear

### ISSUE THREAD

**Issue by papajuras** [Hekili/hekili#796]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**
During testing on "swarm training dummy" suggestions bar disappeared. display mode auto.

**To Reproduce**
Just try dpsing the dummies.

**Expected behavior**
Hekili suggestions bar is not disappearing

**Screenshots**
n/a

 
**PUT SNAPSHOT LINK HERE:**
edit: moved snapshot to pastebin

https://pastebin.com/u0GPTvLS

**Comment by ijoihlhnn** [comment]
Can't reproduce it in an actual Dungeon on my end. Might be an Training dummy issue only.

**Comment by Hekili** [comment]
@papajuras That's not the default priority that I package with the addon.  If you import your own or do customizations, you have to support those yourself.  Thanks.
