### ISSUE TITLE
cooldown.final_reckoning.remains not correctly returning dynamic cooldown value

### ISSUE THREAD

**Issue by lloydBl** [Hekili/hekili#798]
**Describe the Bug/Issue**

As the title says, calling "cooldown.final_reckoning.remains" returns the static max cooldown value of Final Reckoning instead of the actual dynamic cooldown.  This means it returns 60 at all times even if the spell is available.  This causes issues with the current default Ret action list which bases Seraphim off of final reckoning's cooldown.

**To Reproduce**
Load Ret Action list and use Seraphim.  It will never be suggested by the current action list

**Expected behavior**
Should return the time remaining on the cooldown or 0 if the spell is available

**Issue reporting**
https://pastebin.com/nkmEqw2f

**Comment by Hekili** [comment]
Abilities that are toggled off are treated as though they are on CD.  If you enable your Cooldowns toggle, Final Reckoning's CD will be accurate.  This is necessary so that action list logic that does prep work to sync abilities will still work if/when you activate/deactivate toggles.
