### ISSUE TITLE
Ret Pally - Justicar's engeance  Talent

### ISSUE THREAD

**Issue by zerokool209** [Hekili/hekili#800]
Would like to have Justicar's Vengeance as part of the rotation. I think its left out because it uses 5 Holy power. But its one of the strongest strikes It seems like a wasted talent if it's not included.

**Comment by Hekili** [comment]
It's left out because nobody takes it, really.  When you sim, you don't even cast it right now.

In the meantime, refer to the Wiki/FAQ if you'd like to add the ability to your priority.

**Comment by Hekili** [comment]
If you want to do some testing with SimC and find a scenario where using Justicar's Vengeance is a DPS increase at all, provide those sims and I'll look at incorporating it.  The theorycrafting crowd have found it to be a DPS loss to even bother with it.
