### ISSUE TITLE
Blood DK issue with Control Undead and Raise Dead conflict

### ISSUE THREAD

**Issue by Aelmott** [Hekili/hekili#801]
Perhaps I missed the way to fix this within the addon, so I'm sorry if thats the case.

While playing my Blood DK I use and love Hekili, but I noticed an irritation when I 
use CONTROL UNDEAD.  This basically makes an undead mob into my minion / pet
for approx 5 minutes. Now during this time in my rotation while fighting when my
RAISE DEAD is off cooldown, Hekili keeps telling me to cast RAISE DEAD, but you
can't do that while you have a current minion/pet under control. There need to be
a check of some kind so as not to suggest RAISE DEAD is you already have a minion.

Thanks for the addon and I look forward to any responses that can help with this.

**Comment by Hekili** [comment]
Good call, fixed in next update.
