### ISSUE TITLE
Destruction Warlock - Fel Domination appearing in queue without useful reason

### ISSUE THREAD

**Issue by DarkpawGnoll** [Hekili/hekili#802]
**Describe the Bug/Issue**
Fel Domination reduces the casting time for a pet to be summoned. I can't find any other side effects. This spell keeps on being added to my queue as a Destruction Warlock when I've already summoned and sacrificed my pet using the Grimoire talent. Even if I follow the queue and use Fel Domination, it never directs me to use it by summoning a different pet.

**To Reproduce**
Destruction Warlock with Grimoire of Sacrifice Talent
Summon any Demon
Sacrifice Demon for the 1 hour Grimoire buff
You don't need to be in combat to see the Fel Domination recommendation as the 2nd item in queue
When used, the buff will sit on your buff bar until expired with no following command to summon a new demon in the queue

**Expected behavior**
Fel Domination should only be used prior to summoning a demon, and never when Grimoire of Sacrifice is active.

1.  https://pastebin.com/RQp1wPQy

2.  https://pastebin.com/hPgeruKU

3.  No error messages

**Comment by Hekili** [comment]
Good catch.  Will be resolved in next release.
