### ISSUE TITLE
Suggestion: auto-attack action

### ISSUE THREAD

**Issue by khomyaque** [Hekili/hekili#804]
Hello.

I'm playing enhancement shaman, and my ranged spells (like Flame shock) do not trigger auto-attack even when I'm in melee range. Would it be possible to add an action to suggest auto-attack on target whenever it's not toggled on, i.e. add support for SimC _auto_attack_ action?

Thanks!

**Comment by Hekili** [comment]
I will probably not pursue this; I'd recommend getting a WeakAura that warns you about auto-attack and whether you're out of range.  It's a useful thing, but telling people to auto-attack in a visual way is not an economical use of space in a priority display.
