### ISSUE TITLE
ElvUI Options Greyed Out

### ISSUE THREAD

**Issue by ashkaraoc** [Hekili/hekili#806]
1.  Using latest release

2.  Cannot find a similar issue here

**Describe the Bug/Issue**

Opening the ElvUI panel with only ElvUI + Hekili greys out ElvUI, Turning off Hekili allows for button use again on ElvUI

Download ELVUI
Download Helkili
Open up the ElvUI Panel
Check Greyed Buttons

**Expected behavior**

Will be unable to select ElvUI options

Picture: https://imgur.com/a/UB7n5CP

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here. -- It's on Paladin, DH, Shaman, Druid and Warrior. I'm unsure if this is even important as it has no relation to rotation, but a conflict in why the panel for ElvUI is greyed out when using Hekili. 

**PUT ISSUE REPORT LINK HERE:**

2.  N/A
 

3.  N/A - There are no errors and bugsack/buggrabber causes mod taint anyway

No error messages are given

**Comment by Hekili** [comment]
Update ElvUI.
