### ISSUE TITLE
Errors generated while in resto shaman spec

### ISSUE THREAD

**Issue by cacng2** [Hekili/hekili#807]
## Overview

I'm leveling an elemental shaman (57, so above 50).  Hekili worked yesterday, but after updating with Ajour today, it stopped displaying any recommendations (I'm still able to access the options through the minimap icon). The last time I updated was probably a week ago.

I did just get the 'preview' of Fae Transfusion, if that could somehow be related.

## Version

Hekili.toc reads
```
## Interface: 90002
## Version: v9.0.2-1.0.34
## Title: Hekili
## Author: Hekili
## Notes: Priority helper for many DPS and tanking specializations, based on SimulationCraft action lists.
## SavedVariables: HekiliDB
## OptionalDeps: AddOnSkins, BrewmasterTools, ConsolePort, ElvUI, LibDualSpec-1.0, Masque, SpellFlash, SpellFlashCore, WeakAuras
## X-Curse-Project-ID: 69254
## X-WoWI-ID: 24608
```

## Reset Profile

First thing, I create a new Hekili profile using the in game UI (Hekili options through minimap button -> Profiles -> Type name in "new" box -> press enter).  This moved the display frames to the center, unfortunately, no recommendations were displayed.

## Lua Errors (Part 1)

I used `/console scriptErrors 1` to see errors.  This error was being generated many times per second while idle.
![Wow_VTU1zFOvC6](https://user-images.githubusercontent.com/9330629/103959599-b6ebc580-5115-11eb-9ae4-09247daee81c.png)

Line 302 is `self:Debug( "New Recommendations for [ %s ] requested at %s ( %.2f ); using %s( %s ) priority.", display, date( "%H:%M:%S"), GetTime(), self.DB.profile.packs[ pack ].builtIn and "built-in " or "", pack )`, the last line in `Hekili:SetupDebug`. I commented it out to see if I could get any further.

Update: I realized these errors were being caused because I was in resto spec.  Not displaying recommendations is fine while in resto, but maybe the errors are an issue.

## Lua Errors (Part 2)

Now I am not getting errors every second.  But no recommendations are being displayed.  I press the shortcut to get a Hekili snapshot to include in my bug report, and a new lua error is displayed, and no snapshot is generated.  This error, I'm able to grab the text of:

```
Message: Interface\AddOns\Hekili\Utils.lua:186: bad argument #1 to 'pairs' (table expected, got nil)
Time: Thu Jan  7 18:18:00 2021
Count: 1
Stack: Interface\AddOns\Hekili\Utils.lua:186: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `pairs'
[string "@Interface\AddOns\Hekili\Utils.lua"]:186: in function <Interface\AddOns\Hekili\Utils.lua:180>
[string "@Interface\AddOns\Hekili\Utils.lua"]:198: in function `(for generator)'
[string "@Interface\AddOns\Hekili\Options.lua"]:8103: in function `GenerateProfile'
[string "@Interface\AddOns\Hekili\Hekili.lua"]:345: in function `SaveDebugSnapshot'
[string "@Interface\AddOns\Hekili\Options.lua"]:10044: in function `MakeSnapshot'
[string "@Interface\AddOns\Hekili\Options.lua"]:10134: in function `FireToggle'
[string "@Interface\AddOns\Hekili\UI.lua"]:2161: in function <Interface\AddOns\Hekili\UI.lua:2160>

Locals: 
```

Line 186 of utils.lua is the first line here (for key..):
```lua
    for key in pairs( t ) do
        table.insert( orderedIndex, key )
    end
```
in `__genOrderedIndex( t )`

I stopped my debugging here.  But I can provide any info if needed.  I'm very curious why Hekili would be breaking, but only for me :)

## Addon Conflicts?

I also tried disabling all addons except Hekili.  These errors remained.

**Comment by cacng2** [comment]
All of this was happening because I was in resto spec and forgot to swap to elemental spec. 

🤦

**Comment by cacng2** [comment]
I'll leave it open in case the # of errors while in resto spec is an issue.

**Comment by Hekili** [comment]
Correct, resto isn't supported.  I've found that error comes up when trying to debug/pause/snapshot for an unsupported spec.  I'll prevent this in the next release.  Thanks!
