### ISSUE TITLE
Sometimes not recommending abilities when in a AOE fight

### ISSUE THREAD

**Issue by Steviiie** [Hekili/hekili#809]
Hi! First I would like to thank you for all the work you put into this addon. It's great!

The problem I have is that on my DK sometimes in aoe fights the addon won't recommend abilites. In ST fights there is never a problem. I guess it's something I might have done. I reloaded the priority list to the latest one just to make sure but I can't recall me changing anything there. 

https://pastebin.com/0uZEXePw

**Comment by Hekili** [comment]
The ability it would've recommended was Death and Decay -- but you have it set to require 3+ enemies before casting.  The rest of the priority logic relies on casting Death and Decay, so I'd recommend resetting that setting back to 0.

**Comment by Steviiie** [comment]
Hmm that's true! That explains it! Sorry for not seeing that in the log :)
