### ISSUE TITLE
Custom keybind isn't working on trinket

### ISSUE THREAD

**Issue by IronMongrel** [Hekili/hekili#81]
Hekili doesn't detect my macro for activating Razdunk's Big Red Button. I tried setting a custom keybind for it, but it doesn't work. If I only have the macro on the bar, it'll not display any keybind. If I drag the trinket from my equipment screen on to the action bar, it will show the keybind for the slot that I've dragged it to, regardless of the fact that I've set the custom keybind to a different key.

I've tested this behavior with Blade of Justice in the abilities menu as opposed to the "Gear and Trinkets" one and it worked correctly.

I've also just tried setting the keybind for the button under *prot* as well, just to see if they were incorrectly assigned or something, but that didn't help, either.

I don't have another trinket to test this with to see if it's an issue only for this trinket or all trinkets or some trinkets or what. Sorry.

**Comment by Hekili** [comment]
This will be fixed in 8.1.5-04.
