### ISSUE TITLE
Recommending Flare Before Tar Trap with Soulforge Embers

### ISSUE THREAD

**Issue by NokuraWoW** [Hekili/hekili#810]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

Prior to engaging a mob, it recommends I use tar trap, if I do not use it, it acts as if tar trap is down and always recommends I use flare. 

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

Enter Combat with SFE equipped as a BM hunter

**Expected behavior**

Recommend Tar Trap, then recommend Flare

**Screenshots**

https://imgur.com/a/x4lVQQQ

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/eRfw0SPJ

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/D64JLDwm AOE 1
https://pastebin.com/jfQhgkQ5 Primary 1
https://pastebin.com/T4kp8Wnj AOE 2
https://pastebin.com/B65G0W3z Primary 2
https://pastebin.com/Dv6nHDZu AOE 3
https://pastebin.com/6dhqBvqs Primary 3

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

No error messages

**Comment by Hekili** [comment]
Tell me more about this scenario.

Did you use Tar Trap at all?  I.e., in M+, did you use Tar Trap on one pack and then moved on to a new pack?  Or have you not cast Tar Trap at all?

**Comment by NokuraWoW** [comment]
I hadn't used tar trap in ~60 seconds as I was testing it. it was in torg. I waited until I went to a new floor

**Comment by NokuraWoW** [comment]
in the SS you can see that the AOE is recommending it properly but single target isnt

**Comment by Hekili** [comment]
If this is still a significant issue, it can continue in the other open Tar Trap / Flare issue.
