### ISSUE TITLE
Hunter "Double Tap" in Pre-combat Entry List Marks Hekili into Combat?

### ISSUE THREAD

**Issue by kp9928** [Hekili/hekili#815]
1. Version 9.0.2-1.0.35-beta2
2. Description : Double tap in pre-combat entry list marks Hekili into combat skipping everything else in the entry(?). 
3. In the current Marksmanship precombat action list entry for Double Tap, active enemies > 1 is set. But if I were to want to use double tap for single target (eg. ST boss fight), followed by an aimed shot, I would change this entry conditions to be active enemies > 0 or something similar so it will fire regardless. Even after setting this and the next entry in the list is an aimed shot - the aimed shot is no longer recommended after double tap entry. I suspect double tap makes hekili thinks its going into combat?
4. Expected behavior - double tap should not make hekili thinks im going into combat
5. Issue Reporting Character Data
build: v9.0.2-1.0.35-beta2
level: 60 (60)
class: HUNTER
spec: marksmanship

talents: double_tap
    explosive_shot
    master_marksman
    natural_mending
    posthaste
    streamline
    volley

pvptalents: none

covenant: night_fae

conduits: markmans_advantage = 6
   reversal_of_fortune = 6
   spirit_attunement = 5

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   run_without_tiring = 1

sets: none

gear: bangles_of_errant_pride = 1
    blue_martial_shirt = 1
    boneshatter_pauldrons = 1
    cowled_batwing_cloak = 1
    doublechained_utility_belt = 1
    entwined_gorger_tendril = 1
    greaves_of_enigmatic_energies = 1
    helm_of_insatiable_appetite = 1
    inscrutable_quantum_device = 1
    macabre_sheet_music = 1
    master_huntsmans_bandolier = 1
    most_regal_signet_of_sire_denathrius = 1
    nobles_birthstone_pendant = 1
    oathsworn_soldiers_gauntlets = 1
    shrieking_sinseeker = 1
    stoneclas_stompers = 1

legendaries: serpentstalkers_trickery = 1

itemIDs: 167190, 172327, 178848, 179350, 180071, 182976, 182977, 182988, 182991, 183001, 183006, 183012, 183034, 183036, 183039, 184024

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 8
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 15
    nameplates = false
    package = Marksmanship
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = true
    trueshot_vop_overlap = false

toggles: cooldowns = true
    custom1 = true
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = single
    potions = false

Snapshot after I made the changes to Double Tap to fire even on ST (recommendation is Double Tap then straight into ST list skipping the pre-combat Aimed Shot?)
https://pastebin.com/afEEcdQn
 
Snapshot before I made changes to Double Tap (recommendation is Aimed Shot then straight into ST list)
https://pastebin.com/FAjVkiw4

**Comment by Hekili** [comment]
Ok.
