### ISSUE TITLE
Hekili rotation wont show

### ISSUE THREAD

**Issue by Rossilqt** [Hekili/hekili#816]
Hello guys, I've updated my Hekili to the newest version today, but it wont show my rotation now.. I used it last night and it worked just fine.. I've uploaded a few screenshots and my character data, this is my first time reporting a bug, let me know if I'm missing something.

Best regards Thomas

![Combat](https://user-images.githubusercontent.com/77197102/104092314-77db8280-5283-11eb-8f65-7e8c6627616c.png)
![Enabled](https://user-images.githubusercontent.com/77197102/104092322-7c07a000-5283-11eb-975c-1ec70753f551.png)

build: v9.0.2-1.0.34
level: 50 (50)
class: WARRIOR
spec: fury

talents: anger_management
    bladestorm
    double_time
    fresh_meat
    frothing_berserker
    massacre
    warpaint

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: ashjrakamas_shroud_of_resolve = 1
    auric_puddle_stompers = 1
    breastplate_of_twilight_decimation = 1
    ceremonious_claymore = 1
    embalmers_steadying_bracers = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    malignant_leviathans_spaulders = 1
    mirageweavers_gauntlets = 1
    ring_of_collective_consciousness = 1
    ring_of_cosmic_potential = 1
    scryers_tabard = 1
    second_sight_helm = 1
    vitacharged_titanshard = 1
    welloiled_plate_girdle = 1
    zanjir_scaleguard_legplates = 1

legendaries: none

itemIDs: 158075, 159409, 159412, 169057, 169223, 170110, 171383, 173460, 174044, 174163, 174164, 174178, 174500, 174530, 174533, 31780

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = true
    throttleTime = true
    check_ww_range = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Rossilqt** [comment]
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.34
level: 50 (50)
class: WARRIOR
spec: fury

talents: anger_management
    bladestorm
    double_time
    fresh_meat
    frothing_berserker
    massacre
    warpaint

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: none

gear: ashjrakamas_shroud_of_resolve = 1
    auric_puddle_stompers = 1
    breastplate_of_twilight_decimation = 1
    ceremonious_claymore = 1
    embalmers_steadying_bracers = 1
    heart_of_azeroth = 1
    humming_black_dragonscale = 1
    malignant_leviathans_spaulders = 1
    mirageweavers_gauntlets = 1
    ring_of_collective_consciousness = 1
    ring_of_cosmic_potential = 1
    scryers_tabard = 1
    second_sight_helm = 1
    vitacharged_titanshard = 1
    welloiled_plate_girdle = 1
    zanjir_scaleguard_legplates = 1

legendaries: none

itemIDs: 158075, 159409, 159412, 169057, 169223, 170110, 171383, 173460, 174044, 174163, 174164, 174178, 174500, 174530, 174533, 31780

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = true
    throttleTime = true
    check_ww_range = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

New Recommendations for [ Primary ] requested at 14:44:39 ( 9538.39 ); using built-in ( Fury ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: rage[ 20.00 / 100.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Fury - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #4 in list ( precombat ) is not set or not enabled.  Skipping.
    
    Completed precombat action list [ Fury - precombat ].
    
    Processing default action list [ Fury - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   charge ( default - 2 )
        The action (charge) is unusable at (0.00 + 1.13) because ability 'usable' function returned false without explanation.
        Time spent on this action:  0.11ms
        TimeData:Fury-default-2:charge:0.11:Post-TTR and Essential:0.04:Post Cycle:0.00:Post Usable:0.06
        
        2.   run_action_list ( default - 3 )
        Criteria for movement PASS at +0.00 - movement.distance[6.00] > 5
        Action list (movement) was found.
        + [movement]
        Current recommendation was NO ACTION at +60.00s.
        
        3.   heroic_leap ( movement - 1 )
        The action (heroic_leap) is unusable at (0.00 + 0.76) because ability 'usable' function returned false without explanation.
        Time spent on this action:  0.05ms
        TimeData:Fury-movement-1:heroic_leap:0.05:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.01
        Returned from list (movement), current recommendation is NO ACTION (+60.00).
        - [movement]
        Added movement to blocklist as it was called via RAL.
        
        4.   heroic_leap ( default - 4 )
        The action (heroic_leap) is unusable at (0.00 + 0.76) because ability 'usable' function returned false without explanation.
        Time spent on this action:  0.03ms
        TimeData:Fury-default-4:heroic_leap:0.03:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.01
        
        5.   potion ( default - 5 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Fury-default-5:potion:0.02
        
        6.   rampage ( default - 6 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Fury-default-6:rampage:0.01
        
        7.   recklessness ( default - 7 )
        The action (recklessness) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.15ms
        TimeData:Fury-default-7:recklessness:0.15:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.01:Post Stack:0.02:Pre-Recheck:0.00:Post-Recheck Times:0.02:Post Recheck:0.01
        
        8.   whirlwind ( default - 8 )
        The action (whirlwind) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.09ms
        TimeData:Fury-default-8:whirlwind:0.09:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.01:Post Recheck:0.00
        
        9.   dreadfire_vessel ( default - 9 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Fury-default-9:dreadfire_vessel:0.03
        
        10.  blood_fury ( default - 10 )
        The action (blood_fury) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        There were no recheck events to check.
        Time spent on this action:  0.08ms
        TimeData:Fury-default-10:blood_fury:0.08:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.00:Post Recheck:0.00
        
        11.  berserking ( default - 11 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Fury-default-11:berserking:0.02
        
        12.  lights_judgment ( default - 12 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Fury-default-12:lights_judgment:0.02
        
        13.  fireblood ( default - 13 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Fury-default-13:fireblood:0.02
        
        14.  ancestral_call ( default - 14 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Fury-default-14:ancestral_call:0.02
        
        15.  bag_of_tricks ( default - 15 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Fury-default-15:bag_of_tricks:0.02
        
        16.  run_action_list ( default - 16 )
        There is no criteria for single_target.
        Action list (single_target) was found.
        + [single_target]
        Current recommendation was NO ACTION at +60.00s.
        
        17.  raging_blow ( single_target - 1 )
        The action (raging_blow) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded -1.14 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.11ms
        TimeData:Fury-single_target-1:raging_blow:0.11:Post-TTR and Essential:0.04:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.02:Post Recheck:0.00
        
        18.  raging_blow ( single_target - 2 )
        The action (raging_blow) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded -1.14 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.07ms
        TimeData:Fury-single_target-2:raging_blow:0.07:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.01:Post Recheck:0.00
        
        19.  siegebreaker ( single_target - 3 ) - talent [ siegebreaker ] missing
        Time spent on this action:  0.01ms
        TimeData:Fury-single_target-3:siegebreaker:0.01
        
        20.  rampage ( single_target - 4 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Fury-single_target-4:rampage:0.01
        
        21.  condemn ( single_target - 5 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Fury-single_target-5:condemn:0.02
        
        22.  execute ( single_target - 6 )
        The action (execute) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.
        Time spent on this action:  0.10ms
        TimeData:Fury-single_target-6:execute:0.10:Post-TTR and Essential:0.04:Post Cycle:0.00:Post Usable:0.05
        
        23.  bladestorm ( single_target - 7 )
        The action (bladestorm) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        There were no recheck events to check.
        Time spent on this action:  0.08ms
        TimeData:Fury-single_target-7:bladestorm:0.08:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.00:Post Recheck:0.00
        
        24.  bloodthirst ( single_target - 8 )
        The action (bloodthirst) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.09ms
        TimeData:Fury-single_target-8:bloodthirst:0.09:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.01:Post Recheck:0.00
        
        25.  bloodthirst ( single_target - 9 )
        The action (bloodthirst) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.07ms
        TimeData:Fury-single_target-9:bloodthirst:0.07:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.01:Post Recheck:0.00
        
        26.  dragon_roar ( single_target - 10 ) - talent [ dragon_roar ] missing
        Time spent on this action:  0.02ms
        TimeData:Fury-single_target-10:dragon_roar:0.02
        
        27.  onslaught ( single_target - 11 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Fury-single_target-11:onslaught:0.02
        
        28.  raging_blow ( single_target - 12 )
        The action (raging_blow) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.08ms
        TimeData:Fury-single_target-12:raging_blow:0.08:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.02:Post Recheck:0.00
        
        29.  raging_blow ( single_target - 13 )
        The action (raging_blow) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        Excluded 0.00 recheck time as it is outside our constraints ( 0.00 - 15.00 ).
        There were no recheck events to check.
        Time spent on this action:  0.08ms
        TimeData:Fury-single_target-13:raging_blow:0.08:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.02:Post Recheck:0.00
        
        30.  bloodthirst ( single_target - 14 )
        The action (bloodthirst) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        There were no recheck events to check.
        Time spent on this action:  0.06ms
        TimeData:Fury-single_target-14:bloodthirst:0.06:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.00:Post Recheck:0.00
        
        31.  bloodthirst ( single_target - 15 )
        The action (bloodthirst) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        There were no recheck events to check.
        Time spent on this action:  0.06ms
        TimeData:Fury-single_target-15:bloodthirst:0.06:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.00:Post Recheck:0.00
        
        32.  raging_blow ( single_target - 16 )
        The action (raging_blow) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        There were no recheck events to check.
        Time spent on this action:  0.06ms
        TimeData:Fury-single_target-16:raging_blow:0.06:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.00:Post Recheck:0.00
        
        33.  raging_blow ( single_target - 17 )
        The action (raging_blow) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        There were no recheck events to check.
        Time spent on this action:  0.06ms
        TimeData:Fury-single_target-17:raging_blow:0.06:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.00:Post Recheck:0.00
        
        34.  whirlwind ( single_target - 18 )
        The action (whirlwind) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        Blocking list ( movement ) called from ( Fury:default:3 ) would BLOCK at 0.00.
        movement.distance[6.00] > 5
         - this entry would not be reached at the current time via the current action list path (0.00).
        There were no recheck events to check.
        Time spent on this action:  0.06ms
        TimeData:Fury-single_target-18:whirlwind:0.06:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.02:Post Ready/Clash:0.00:Post Stack:0.01:Pre-Recheck:0.00:Post-Recheck Times:0.00:Post Recheck:0.00
        Returned from list (single_target), current recommendation is NO ACTION (+60.00).
        - [single_target]
        Added single_target to blocklist as it was called via RAL.
    
    Completed default action list [ Fury - default ].
    Recommendation is NO ACTION at 0.00 + 60.00.
    Recommendation #1 is NO ACTION at 60.00s (60.00s).
    Time spent generating recommendations:  2.60ms

**Comment by Rossilqt** [comment]
Resetting my profile fixed the problem, thanks to @Smufy :-)

**Comment by Hekili** [comment]
My guess would be that you imported a priority that didn't work.  (There aren't 4 entries in my default precombat action list.)

Don't import action lists.  Unless you've written something new and novel by hand, I've already translated simc action lists to the addon.
