### ISSUE TITLE
Detection does not work at arena

### ISSUE THREAD

**Issue by maktens** [Hekili/hekili#818]
hi
detection does not work at arena, addon just simply cant see characters but still see their pets (so addon cant use aoe scenario in auto mode when face multiple enemy chars)
im using nameplate detection but tried other and still nothing
btw detection work at bg's properly

ps: just love ur work mate, so good tuning in ingame ui, cheers :)

**Comment by Hekili** [comment]
I'll add arena units to unit ID tracking (for target counts and time-to-death calculations), but you'd need to provide a complete ticket with the required information for any further investigation/exploration.

There's nothing I see that would explicitly block nameplate detection in arenas.
