### ISSUE TITLE
Rotation Tweak Unholy DK

### ISSUE THREAD

**Issue by j3llevdb** [Hekili/hekili#821]
build: v9.0.2-1.0.35-beta2
level: 60 (60)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    army_of_the_damned
    grip_of_the_dead
    soul_reaper
    spell_eater
    unholy_blight
    unholy_pact

pvptalents: none

covenant: necrolord

conduits: eternal_hunger = 5
   insatiable_appetite = 4
   lingering_plague = 5

soulbinds: [plague_deviser_marileth]
   oozs_frictionless_coating = 1
   plagueborn_cleansing_slime = 1
   volatile_solvent = 1

sets: none

gear: bloodoath_signet = 1
    blue_linen_shirt = 1
    charm_of_eternal_winter = 1
    cloak_of_enveloping_manifestations = 1
    darkmoon_deck_voracity = 1
    drustlords_greataxe = 1
    fogweaver_gauntlets = 1
    gormshell_greaves = 1
    memory_of_past_sins = 1
    pranksters_pauldrons = 1
    sabatons_of_the_rushing_juggernaut = 1
    scarred_bloodbound_girdle = 1
    shadowghast_breastplate = 1
    shoulderblade_vambraces = 1
    signet_of_the_false_accuser = 1
    wrathbark_greathelm = 1

legendaries: deadliest_coil = 1

itemIDs: 171412, 173087, 178694, 178697, 178701, 178706, 178713, 178824, 178836, 178851, 178871, 178931, 183040, 184025, 184135, 2577

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycleDebuff = festering_wound
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

- Unholy Transformation is not always paired with unholy blight in AOE.
- Unholy Transformation check on pet buff in stead of on unholy pact buff (because unholy pact runs out before dark transformation if you have the deadliest coild legendary equipped).
- Epidemic should be used only on 4 targets and up if the legendary deadliest coil is equipped, even if dark transformation is not active.

regards!!

**Comment by Hekili** [comment]
For this sort of request/recommendation, you'd need to test your request with simulation changes and provide links to the sims that show a DPS boost.
