### ISSUE TITLE
MM Hunter Double Tap

### ISSUE THREAD

**Issue by MrDheu** [Hekili/hekili#822]
When you are out of combat and is about to start a fight, I would like Double Tap to be placed before Aimed Shot, since you should pre-cast it before your Aimed Shot to land when the fight starts

Now: Aimed Shot - Double Tap - Explosive Shot

After: Double Tap - Aimed Shot - Explosive Shot

**Comment by Hekili** [comment]
For yourself, you can customize your priority to do this.  (Refer to the wiki, here, for guidance re: creating a copy that won't be overwritten when I provide updates.)

If you want this to be a default for the addon, you'd need to provide a comparison sim demonstrating the DPS gain.

**Comment by MrDheu** [comment]
Thanks for the fast replay!

Thanks, then I can get that for my self.

But how can I sim on somthing that is out off combat?
Its like a pre-pot that you take a few second before the fight start, by doing Double Tap before the fight start, and line up with your Aimed Shot you get the perfect start.
(Also what Icy veins write)

Love your addon Hekili, it's as close to perfect as it can get!
I have recommended it for all my guild mates and friends!

**Comment by Hekili** [comment]
> But how can I sim on somthing that is out off combat?

Take a look at the sim profile:

https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier26/T26_Hunter_Marksmanship.simc

Double Tap is shown before Aimed Shot, but with certain conditions.  But that's how you'd adjust your sim -- modify the APL to reflect the changes you want to see.  If that's not matching your experience with the addon, submit a complete ticket with a snapshot and I can explain why you're seeing what you see.
