### ISSUE TITLE
Option "Use Starfall in Single-Target with Stellar Drift" isn't working

### ISSUE THREAD

**Issue by Maktoal** [Hekili/hekili#823]
Hello,

iam playing on a german client and version 9.0.2-1.0.35-beta2.

In have opt in the ""Use Starfall in Single-Target with Stellar Drift" but Starfall wont show up the single target rotation list.
Ist there any bug with the option or german client?
Or can I change anythink in the "deeper" options?

Cheers Maktoal

**Comment by Hekili** [comment]
You will have to provide a snapshot, per the ticket instructions, from when you thought it should recommend Starfall with that option enabled but did not.

**Comment by Hekili** [comment]
I've added entries to the BOAT and Dreambinder lists to use Starfall this way, but they're almost certainly not optimal.  The default legendary-free action list was handling this just fine.
