### ISSUE TITLE
Unable to remove Dark Command from priority queue as frost

### ISSUE THREAD

**Issue by Pismochef** [Hekili/hekili#824]
Maybe I'm just not seeing it on the customization panel, but I am trying to remove dark command as being a cooldown in my frost DK's priority queue

**Comment by Hekili** [comment]
Dark Command isn't in the priority for Frost by default, and is not a Cooldown ability for Frost at all.

I'm guessing you probably mean Sacrificial Pact, since folks tend to think it is Corpse Explosion and other stuff -- you can remove that as you see fit.
