### ISSUE TITLE
Include Word of Glory in Retribution Paladin Rotation

### ISSUE THREAD

**Issue by Kestrelator** [Hekili/hekili#825]
Please describe your idea or feature and when it would be useful.
Word of Glory is an important self-heal for both Prot and Ret paladins. It shows up correctly in the Prot rotation, but not for Ret. I tried the Ret rotation on a tanking dummy, until it killed me. Word of Glory was not in the rotation or queue.

**Comment by Hekili** [comment]
WoG is in the Protection priority because it's a tank spec.

Healing/mitigation isn't part of the Retribution priority because Ret is DPS.

You can refer to the Wiki/FAQ re: making a custom priority that uses Word of Glory.
