### ISSUE TITLE
Brewmaster Keg Smash + Kyrian Weapons of Order

### ISSUE THREAD

**Issue by sanyex89** [Hekili/hekili#827]
At the start of the fight hekili says we should use Weapons of Order first and keg smash after that.
But Weapons of Order resets the cooldown of Keg Smash.

So it should be: 
Keg Smash -> Weapons of Order -> Keg Smash  

instead of: 
Weapons of Order -> Keg Smash

**Comment by Hekili** [comment]
It's important to fill out the entire ticket providing all the requested data.

I've done some sim testing to see if putting KS on CD before WoO is worth delaying WoO by a GCD and so far it's just damage neutral at best, in both Patchwerk and Single Target.

This is an adjustment you could make to your own custom priority, until/unless we find a meaningful DPS gain attached to this.  You might want to reach out to Brewmaster TCs about the SimulationCraft APL, to see if they want to make changes consistent with your request.

Have you done any comparison sims yourself?

**Comment by Hekili** [comment]
Please confirm if you'll be adding information to this ticket or if I should close it.  Thanks.
