### ISSUE TITLE
Showing Weapons of Order as a CD 

### ISSUE THREAD

**Issue by burock3333** [Hekili/hekili#828]
As a brewmaster monk, I would rather prefer Hekili to show Weapons of Order as a CD than as part of the primary rotation. That skill has 2 min. CD which justifies moving into the CD category. I looked for a way to manually force it to show under CDs but failed to find a way to do so so far.

**Comment by Hekili** [comment]
No, Weapons of Order is on the Covenants toggle, which allows it to be controlled separately from Cooldowns.

If you check "Cooldowns Override" next to the Covenants toggle, it will be enabled when Cooldowns are enabled (even if Covenants are toggled off).

If you want to do something different, you can change the toggle via /hekili > Abilities > Weapons of Order.
