### ISSUE TITLE
Demonic tyrant and balefire branch trinket recommend and wrong time past 8.1.5

### ISSUE THREAD

**Issue by Nirion123** [Hekili/hekili#83]
build: v8.1.0-25
level: 120
class: WARLOCK
spec: demonology

talents: dark_pact
    demonic_calling
    demonic_circle
    demonic_consumption
    demonic_strength
    soul_conduit
    soul_strike

traits: azerite_empowered=1
    baleful_invocation=1
    desperate_power=1
    explosive_potential=3
    lifeblood=1
    longstrider=1
    overwhelming_power=1
    treacherous_covenant=2
    unstable_flames=2

sets/legendaries/artifacts: none

gear:     moonpriests_legwraps=1
    phoenixfire_staff=1
    balefire_branch=1
    loa_exultants_shroud=1
    seal_of_the_zandalari_empire=1
    incandescent_sliver=1
    lightfeather_footpads=1
    murky_cerulean_signet=1
    precious_ribbon=1
    gigacharged_shoulderpads=1
    greasy_bacongrabbers=1
    drustthatched_wristwraps=1
    waistcord_of_flowing_silk=1
    heart_of_azeroth=1
    blazewing_hood=1
    divine_fury_raiment=

Issue 1: addon wanna use balefire brach randomly in opener: 
build: v8.1.0-25
level: 120
class: WARLOCK
spec: demonology

talents: dark_pact
    demonic_calling
    demonic_circle
    demonic_consumption
    demonic_strength
    soul_conduit
    soul_strike

traits: azerite_empowered=1
    baleful_invocation=1
    desperate_power=1
    explosive_potential=3
    lifeblood=1
    longstrider=1
    overwhelming_power=1
    treacherous_covenant=2
    unstable_flames=2

sets/legendaries/artifacts: none

gear:     moonpriests_legwraps=1
    phoenixfire_staff=1
    balefire_branch=1
    loa_exultants_shroud=1
    seal_of_the_zandalari_empire=1
    incandescent_sliver=1
    lightfeather_footpads=1
    murky_cerulean_signet=1
    precious_ribbon=1
    gigacharged_shoulderpads=1
    greasy_bacongrabbers=1
    drustthatched_wristwraps=1
    waistcord_of_flowing_silk=1
    heart_of_azeroth=1
    blazewing_hood=1
    divine_fury_raiment=1

New Recommendations for [ Primary ] requested at 20:01:38 ( 12477.77 ).
*** START OF NEW DISPLAY: Primary ***

[ ** ] Checking for recommendation #1 ( time offset: 0.00, remaining GCD: 0.00 ).
[ ** ] soul_shards, 3 / 5
[ ** ] mana, 100000 / 100000

Processing precombat action list [ Demonology - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

[  1]  Checking summon_felguard (Demonology - precombat - 4 )...
summon_felguard is known and enabled.
The action (summon_felguard) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.

[  2]  Checking inner_demons (Demonology - precombat - 5 )...
inner_demons is NOT known and enabled.

Entry #6 in list ( precombat ) is not set or not enabled.  Skipping.

[  3]  Checking potion (Demonology - precombat - 7 )...
potion is known and NOT enabled.

[  4]  Checking power_siphon (Demonology - precombat - 8 )...
power_siphon is NOT known and enabled.

[  5]  Checking demonbolt (Demonology - precombat - 9 )...
demonbolt is known and enabled.
The action (demonbolt) is usable at (0.00 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: boss[true] | action.demonbolt.cast[3.99] = 0
Action chosen:  demonbolt at 0.00!
Completed precombat action list [ Demonology - precombat ].
Recommendation is demonbolt at 0.00 + 0.00.
Recommendation #1 is demonbolt at 0.00s (0.00s).
Advancing clock by 3.99...

[ ** ] Checking for recommendation #2 ( time offset: 3.99, remaining GCD: 0.00 ).
[ ** ] soul_shards, 5 / 5
[ ** ] mana, 98005 / 100000

Processing precombat action list [ Demonology - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

[  1]  Checking summon_felguard (Demonology - precombat - 4 )...
summon_felguard is known and enabled.
The action (summon_felguard) is unusable at (3.99 + 0.00) because ability 'usable' function returned false without explanation.

[  2]  Checking inner_demons (Demonology - precombat - 5 )...
inner_demons is NOT known and enabled.

Entry #6 in list ( precombat ) is not set or not enabled.  Skipping.

[  3]  Checking potion (Demonology - precombat - 7 )...
potion is known and NOT enabled.

[  4]  Checking power_siphon (Demonology - precombat - 8 )...
power_siphon is NOT known and enabled.

[  5]  Checking demonbolt (Demonology - precombat - 9 )...
demonbolt is known and enabled.
We are already in-combat and this pre-combat action is not essential.  Skipping.

[  6]  Checking shadow_bolt (Demonology - precombat - 10 )...
shadow_bolt is known and enabled.
We are already in-combat and this pre-combat action is not essential.  Skipping.
Completed precombat action list [ Demonology - precombat ].

Processing default action list [ Demonology - default ].
Current recommendation was NO ACTION at +60.00s.

[  7]  Checking spell_lock (Demonology - default - 1 )...
spell_lock is NOT known and enabled.

[  8]  Checking implosion (Demonology - default - 2 )...
implosion is known and enabled.
The action (implosion) is unusable at (3.99 + 0.00) because no imps available.

[  9]  Checking potion (Demonology - default - 3 )...
potion is known and NOT enabled.

[ 10]  Checking use_items (Demonology - default - 4 )...
use_items is known and enabled.
Criteria PASS at +3.99 - pet.demonic_tyrant.active[false] | time_to_die[-3.99] <= 15
Current recommendation was NO ACTION at +60.00s.

[ 11]  Checking balefire_branch (UseItems - items - 1 )...
balefire_branch is known and enabled.
The action (balefire_branch) is usable at (3.99 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: ( ! settings.boss[false] | boss[true] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
Action chosen:  balefire_branch at 0.00!
Returned from Use Items; current recommendation is balefire_branch (+0.00).
The recommended action (balefire_branch) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Demonology - default ].
Recommendation is balefire_branch at 3.99 + 0.00.
Recommendation #2 is balefire_branch at 0.00s (3.99s).

[ ** ] Checking for recommendation #3 ( time offset: 3.99, remaining GCD: 0.00 ).
[ ** ] soul_shards, 5 / 5
[ ** ] mana, 98005 / 100000

Processing precombat action list [ Demonology - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

[  1]  Checking summon_felguard (Demonology - precombat - 4 )...
summon_felguard is known and enabled.
The action (summon_felguard) is unusable at (3.99 + 0.00) because ability 'usable' function returned false without explanation.

[  2]  Checking inner_demons (Demonology - precombat - 5 )...
inner_demons is NOT known and enabled.

Entry #6 in list ( precombat ) is not set or not enabled.  Skipping.

[  3]  Checking potion (Demonology - precombat - 7 )...
potion is known and NOT enabled.

[  4]  Checking power_siphon (Demonology - precombat - 8 )...
power_siphon is NOT known and enabled.

[  5]  Checking demonbolt (Demonology - precombat - 9 )...
demonbolt is known and enabled.
We are already in-combat and this pre-combat action is not essential.  Skipping.

[  6]  Checking shadow_bolt (Demonology - precombat - 10 )...
shadow_bolt is known and enabled.
We are already in-combat and this pre-combat action is not essential.  Skipping.
Completed precombat action list [ Demonology - precombat ].

Processing default action list [ Demonology - default ].
Current recommendation was NO ACTION at +60.00s.

[  7]  Checking spell_lock (Demonology - default - 1 )...
spell_lock is NOT known and enabled.

[  8]  Checking implosion (Demonology - default - 2 )...
implosion is known and enabled.
The action (implosion) is unusable at (3.99 + 0.00) because no imps available.

[  9]  Checking potion (Demonology - default - 3 )...
potion is known and NOT enabled.

[ 10]  Checking use_items (Demonology - default - 4 )...
use_items is known and enabled.
Criteria PASS at +3.99 - pet.demonic_tyrant.active[false] | time_to_die[-18.99] <= 15
Current recommendation was NO ACTION at +60.00s.

[ 11]  Checking balefire_branch (UseItems - items - 1 )...
balefire_branch is known and enabled.
The action (balefire_branch) is usable at (3.99 + 15.00).
 - the action is ready before the current recommendation (at +15.00 vs. +60.00).
 - this entry's criteria PASSES: ( ! settings.boss[false] | boss[true] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
Action chosen:  balefire_branch at 15.00!
Returned from Use Items; current recommendation is balefire_branch (+15.00).

[ 12]  Checking berserking (Demonology - default - 5 )...
berserking is NOT known and enabled.

[ 13]  Checking blood_fury (Demonology - default - 6 )...
blood_fury is NOT known and enabled.

[ 14]  Checking fireblood (Demonology - default - 7 )...
fireblood is NOT known and enabled.

[ 15]  Checking call_action_list (Demonology - default - 8 )...
call_action_list is known and enabled.
Time-sensitive Criteria deferred at +3.99 - azerite.explosive_potential.rank[3.00] & talent.demonic_consumption.enabled[true] & time[0.01] < 30 & ! cooldown.summon_demonic_tyrant.remains[0.00]
Action list (dcon_ep_opener) was found.
Adding dcon_ep_opener to stack, parent is (none) (RAL = false.
Current recommendation was balefire_branch at +15.00s.

[ 16]  Checking hand_of_guldan (Demonology - dcon_ep_opener - 1 )...
hand_of_guldan is known and enabled.
Line CD is 30, last cast was 11409.878, remaining CD: 0
The action (hand_of_guldan) is usable at (3.99 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +15.00).
List ( dcon_ep_opener ) called from ( Demonology:default:8 ) would PASS at 0.00.
 - azerite.explosive_potential.rank[3.00] & talent.demonic_consumption.enabled[true] & time[0.01] < 30 & ! cooldown.summon_demonic_tyrant.remains[0.00]
 - this entry has no criteria to test.
Action chosen:  hand_of_guldan at 0.00!
Returned from list (dcon_ep_opener), current recommendation is hand_of_guldan (+0.00).
Removed dcon_ep_opener from stack.
The recommended action (hand_of_guldan) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Demonology - default ].
Recommendation is hand_of_guldan at 3.99 + 0.00.
Recommendation #3 is hand_of_guldan at 0.00s (3.99s).
Advancing clock by 1.33...

[ ** ] Checking for recommendation #4 ( time offset: 5.32, remaining GCD: 0.00 ).
[ ** ] soul_shards, 2 / 5
[ ** ] mana, 99335 / 100000

Processing precombat action list [ Demonology - precombat ].
Current recommendation was NO ACTION at +60.00s.

Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.

Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.

[  1]  Checking summon_felguard (Demonology - precombat - 4 )...
summon_felguard is known and enabled.
The action (summon_felguard) is unusable at (5.32 + 0.00) because ability 'usable' function returned false without explanation.

[  2]  Checking inner_demons (Demonology - precombat - 5 )...
inner_demons is NOT known and enabled.

Entry #6 in list ( precombat ) is not set or not enabled.  Skipping.

[  3]  Checking potion (Demonology - precombat - 7 )...
potion is known and NOT enabled.

[  4]  Checking power_siphon (Demonology - precombat - 8 )...
power_siphon is NOT known and enabled.

[  5]  Checking demonbolt (Demonology - precombat - 9 )...
demonbolt is known and enabled.
We are already in-combat and this pre-combat action is not essential.  Skipping.

[  6]  Checking shadow_bolt (Demonology - precombat - 10 )...
shadow_bolt is known and enabled.
We are already in-combat and this pre-combat action is not essential.  Skipping.
Completed precombat action list [ Demonology - precombat ].

Processing default action list [ Demonology - default ].
Current recommendation was NO ACTION at +60.00s.

[  7]  Checking spell_lock (Demonology - default - 1 )...
spell_lock is NOT known and enabled.

[  8]  Checking implosion (Demonology - default - 2 )...
implosion is known and enabled.
The action (implosion) is unusable at (5.32 + 0.00) because no imps available.

[  9]  Checking potion (Demonology - default - 3 )...
potion is known and NOT enabled.

[ 10]  Checking use_items (Demonology - default - 4 )...
use_items is known and enabled.
Criteria PASS at +5.32 - pet.demonic_tyrant.active[false] | time_to_die[-18.99] <= 15
Current recommendation was NO ACTION at +60.00s.

[ 11]  Checking balefire_branch (UseItems - items - 1 )...
balefire_branch is known and enabled.
The action (balefire_branch) is usable at (5.32 + 13.67).
 - the action is ready before the current recommendation (at +13.67 vs. +60.00).
 - this entry's criteria PASSES: ( ! settings.boss[false] | boss[true] ) & ( settings.targetMin[0.00] = 0 | active_enemies[1.00] >= settings.targetMin[0.00] ) & ( settings.targetMax[0.00] = 0 | active_enemies[1.00] <= settings.targetMax[0.00] )
Action chosen:  balefire_branch at 13.67!
Returned from Use Items; current recommendation is balefire_branch (+13.67).

[ 12]  Checking berserking (Demonology - default - 5 )...
berserking is NOT known and enabled.

[ 13]  Checking blood_fury (Demonology - default - 6 )...
blood_fury is NOT known and enabled.

[ 14]  Checking fireblood (Demonology - default - 7 )...
fireblood is NOT known and enabled.

[ 15]  Checking call_action_list (Demonology - default - 8 )...
call_action_list is known and enabled.
Time-sensitive Criteria deferred at +5.32 - azerite.explosive_potential.rank[3.00] & talent.demonic_consumption.enabled[true] & time[1.34] < 30 & ! cooldown.summon_demonic_tyrant.remains[0.00]
Action list (dcon_ep_opener) was found.
Adding dcon_ep_opener to stack, parent is (none) (RAL = false.
Current recommendation was balefire_branch at +13.67s.

[ 16]  Checking hand_of_guldan (Demonology - dcon_ep_opener - 1 )...
hand_of_guldan is known and enabled.
Line CD is 30, last cast was 12483.095, remaining CD: 30
The action is not ready before our maximum delay window (15.00) for this query.

[ 17]  Checking implosion (Demonology - dcon_ep_opener - 2 )...
implosion is known and enabled.
The action (implosion) is unusable at (5.32 + 0.00) because no imps available.

[ 18]  Checking doom (Demonology - dcon_ep_opener - 3 )...
doom is NOT known and enabled.

[ 19]  Checking hand_of_guldan (Demonology - dcon_ep_opener - 4 )...
hand_of_guldan is known and enabled.
The action (hand_of_guldan) is usable at (5.32 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +13.67).
List ( dcon_ep_opener ) called from ( Demonology:default:8 ) would PASS at 0.00.
 - azerite.explosive_potential.rank[3.00] & talent.demonic_consumption.enabled[true] & time[1.34] < 30 & ! cooldown.summon_demonic_tyrant.remains[0.00]
 - this entry's criteria FAILS: prev_gcd.1.hand_of_guldan[true] & soul_shard[2.00] > 0 & prev_gcd.2.soul_strike[false]
There were no recheck events to check.

[ 20]  Checking demonic_strength (Demonology - dcon_ep_opener - 5 )...
demonic_strength is known and enabled.
The action (demonic_strength) is usable at (5.32 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +13.67).
List ( dcon_ep_opener ) called from ( Demonology:default:8 ) would PASS at 0.00.
 - azerite.explosive_potential.rank[3.00] & talent.demonic_consumption.enabled[true] & time[1.34] < 30 & ! cooldown.summon_demonic_tyrant.remains[0.00]
 - this entry's criteria FAILS: prev_gcd.1.hand_of_guldan[true] & ! prev_gcd.2.hand_of_guldan[false] & ( buff.wild_imps.stack[0.00] > 1 & action.hand_of_guldan.in_flight[true] )
There were no recheck events to check.

[ 21]  Checking bilescourge_bombers (Demonology - dcon_ep_opener - 6 )...
bilescourge_bombers is NOT known and enabled.

[ 22]  Checking soul_strike (Demonology - dcon_ep_opener - 7 )...
soul_strike is known and enabled.
Line CD is 30, last cast was 11407.599, remaining CD: 0
The action (soul_strike) is usable at (5.32 + 0.00).
 - the action is ready before the current recommendation (at +0.00 vs. +13.67).
List ( dcon_ep_opener ) called from ( Demonology:default:8 ) would PASS at 0.00.
 - azerite.explosive_potential.rank[3.00] & talent.demonic_consumption.enabled[true] & time[1.34] < 30 & ! cooldown.summon_demonic_tyrant.remains[0.00]
 - this entry's criteria PASSES: ! buff.bloodlust.remains[0.00] | time[1.34] > 5 & prev_gcd.1.hand_of_guldan[true]
Action chosen:  soul_strike at 0.00!
Returned from list (dcon_ep_opener), current recommendation is soul_strike (+0.00).
Removed dcon_ep_opener from stack.
The recommended action (soul_strike) would be ready before the next GCD (0.00 < 0.00); exiting list (default).
Completed default action list [ Demonology - default ].
Recommendation is soul_strike at 5.32 + 0.00.
Recommendation #4 is soul_strik

**Comment by Hekili** [comment]
This is effectively a duplicate.
