### ISSUE TITLE
Havoc Demon Hunter Unbound Chaos Buff Not Registering

### ISSUE THREAD

**Issue by colin-green** [Hekili/hekili#830]
Havoc Demon Hunter Unbound Chaos Buff Not Registering

**Describe the Bug/Issue**
When playing Havoc Demon Hunter, does not recognize the Unbound Chaos buff or it's Spell ID.

**To Reproduce**
- Go to an action list of your choice on Havoc DH
- Make the spell "Fel Rush" (or anything else, really)
- For the condition, type "buff.unbound_chaos.up" or "buff.347462.up"

**Expected behavior**
I expect it to say "true" when I highlight the aforementioned condition with my mouse cursor, but it always says false, even when the buff is up.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here: https://pastebin.com/PeGUruiC

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
> For the condition, type "buff.unbound_chaos.up" or "buff.347462.up"

FYI, `buff.347462.up` isn't supported syntax at all.  However, the spell ID used for Unbound Chaos was not updated when Unbound Chaos was reworked, so I will be correcting the ID.  The next beta version will include the fix.

**Comment by colin-green** [comment]
Ok, thanks for the info! Love your addon, btw.
