### ISSUE TITLE
Keybind Toggle On/Off For Recommending Target Swaps

### ISSUE THREAD

**Issue by RickyDudio** [Hekili/hekili#836]
I think it could be really useful to be able to keybind a toggle On/Off Button for Recommending Target Swaps. on some fights there are times where I don't wanna target swap to something for example the adds on barghast and it would be a big QoL Change to be able to key bind it off in certain situations.

**Comment by Hekili** [comment]
It's not a bad idea, but having something take up a keybind is something of a big deal.  I might make it something you can swap with `/hek set` but it's not a priority at the moment.

**Comment by Hekili** [comment]
`/hek set target_swap` will be available (so you can macro it) in the next release.
