### ISSUE TITLE
Vanish / Master assassin problem (Rogue)

### ISSUE THREAD

**Issue by endisnear1010** [Hekili/hekili#841]
Hekili wants to use vanish in the opener while Master Assassin (100% crit chance buff which is active 4 seconds after stealth) is still up instead of waiting for it to run out and to get a new buff right afterwards which seems like a waste to me. 

https://pastebin.com/7iFH43Ft

**Comment by endisnear1010** [comment]
ok my hekili wasnt on the newest update, but i just updated it now and it still does this. Here's a new snapshot with the update.
https://pastebin.com/1pFeMwaC

if you need anything else tell me.

**Comment by Hekili** [comment]
Your snapshot doesn't show Master Assassin being up when Vanish is recommended.  Can you screenshot when this is happening?  Can you show me the spell ID of your Master Assassin buff?  Or link a log?

**Comment by endisnear1010** [comment]
ID is: 340094, ill make a screenshot soon

**Comment by endisnear1010** [comment]
there's a screenshot: https://gyazo.com/879e0ea91b953a16e116b8860ddf3496

made a weakaura to show that MA is up.

**Comment by endisnear1010** [comment]
just noticed the screenshot ist very good, had to use the built in wow functipn as the ma windows is pretty small. if you need another screenshot tell me and ill do a better one.

**Comment by choseh** [comment]
can confirm that this is happening here aswell, not showing up as as "up" in the snapshot:
https://pastebin.com/Dh4SEQMY

spell id/aura for me: 340094

**Comment by Hekili** [comment]
Next release should address this.
