### ISSUE TITLE
No Recomandation for Flare after Tar Trap on Survival Hunter with Soulforge Embers

### ISSUE THREAD

**Issue by Preacher1972** [Hekili/hekili#843]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
I switched my Hunter from Beastmaster to Survival and on Bestmaster i always get a Flare recommendation after Tar Trap, but on Survival Spec i only get the Tar Trap recommendation. I wear the Soulforge Embers Legendary in both specs.

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/hkuiDnvE

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.

 https://pastebin.com/U0KVLV47

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
There is no way to detect Tar Trap is applied to snare-immune enemies (raid test dummies, bosses, etc.).

**Comment by Preacher1972** [comment]
But it worked really flawless with my Beastmastery Specification ..... i am a little confused :).

**Comment by Preacher1972** [comment]
I compared the Beast Master profile with the survival hunter profile and there are no Tar Trap + Flare in the Profile....

actions.cleave+=/tar_trap,if=runeforge.soulforge_embers&tar_trap.remains<gcd&cooldown.flare.remains<gcd
actions.cleave+=/flare,line_cd=25,if=tar_trap.up&runeforge.soulforge_embers

and 

actions.st+=/tar_trap,if=runeforge.soulforge_embers&tar_trap.remains<gcd&cooldown.flare.remains<gcd
actions.st+=/flare,line_cd=25,if=tar_trap.up&runeforge.soulforge_embers

is missing in the survival hunter Profile.....

**Comment by Hekili** [comment]
Those lines aren't part of the Survival priority.  But there is a missing call for CDs in general that I've added and are present as of 1.0.36-beta4.
