### ISSUE TITLE
Minimum targets doesn't work for 2 targets.

### ISSUE THREAD

**Issue by leewynn** [Hekili/hekili#844]
**Describe the Bug/Issue**
For outlaw rogue, AOE Display: Minimum targets doesn't work for 2 targets.

**To Reproduce**
Open Hekili, select Outlaw, go to Targetting tab and set AOE Display: Minimum Targets to 2

**Expected behavior**
AOE Display should display when 2 targets are configured in the Targetting tab

**Screenshots**
N/A

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/A4s0ubsd

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Setting AOE Display: Minimum Targets to 2 means *when it is shown*, the AOE display will always pretend there are at least 2 targets.

To make the AOE display appear, you have to set your Display Mode (in the Toggles section) to a mode that uses two displays.  That would be "Fixed Dual Display" (always showing both) or "Reactive Dual Display" (appearing when there are 2+ targets).

**Comment by leewynn** [comment]
@Hekili it's on reactive dual display at the moment, it displays when it's 3 targets, but does not appear on 2 targets which is why i logged this card

**Comment by Hekili** [comment]
Will look again, thanks.

**Comment by Hekili** [comment]
Good catch.  I have a fix for this that I'll put out in a new release later this morning.

**Comment by leewynn** [comment]
Thanks for looking into it!
