### ISSUE TITLE
Cannot add Wrathstone trinket to cool downs

### ISSUE THREAD

**Issue by steveriggins** [Hekili/hekili#845]
**Describe the Bug/Issue**
I picked up a Wrathstone trinket, on use agility, form time walking ulduar. When I try to toggle it on, it does not show in the list and I cannot figure out how to add it.

**To Reproduce**
I am wearing the trinket in the second trinket slot. It does not show up in my rotation in either the main abilities nor the separate cooldown list.

**Expected behavior**
To be able to toggle this trinket as a cooldown

** thank you!
Love this addon 

* Profile

build: v9.0.2-1.0.35
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ascendance
    forceful_winds
    hailstorm
    natures_guardian
    spirit_wolf
    stormflurry
    sundering

pvptalents: none

covenant: venthyr

conduits: thunderous_paws = 1
   unruly_winds = 4
   vital_accretion = 4

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: belt_of_the_blood_pit = 1
    boneshatter_helm = 1
    boots_of_the_forgotten_depths = 1
    claws_of_the_stone_generals = 1
    cloak_of_enveloping_manifestations = 1
    darkwing_rebels_chainmail = 1
    dominance_guards_band = 1
    fearstalkers_ebony_bracers = 1
    fearstalkers_ebony_gauntlets = 1
    fearstalkers_ebony_leggings = 1
    fearstalkers_ebony_monnion = 1
    infinitely_divisible_ooze = 1
    kinetic_ripper = 1
    leafed_banewood_band = 1
    sin_stained_pendant = 1
    wrathstone = 1

legendaries: doom_winds = 1

itemIDs: 156000, 156014, 156225, 156305, 172325, 178769, 178827, 178851, 180912, 180918, 180923, 180930, 181188, 181217, 181708, 182416

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Every trinket has to be manually added to ensure it's scripted.  I'll add the Wrathstone for the next release.

**Comment by steveriggins** [comment]
Sweet, thank you!
