### ISSUE TITLE
Master Assassin + Vanish possible regression in beta5

### ISSUE THREAD

**Issue by choseh** [Hekili/hekili#848]
**Describe the Bug/Issue**

Hekili suggests to vanish, even if master assassin aura is up. (spellid: 340094)

**To Reproduce**

Start fight from stealth, have vanish available

**Expected behavior**
Hek should only suggest it after the aura has faded.

https://pastebin.com/iY2z9FKX

master_assassin_remains[0.00] = 0 
but aura is up

**Comment by Hekili** [comment]
Thanks, incoming fix to spell ID:  340094.
