### ISSUE TITLE
windwalker monk not telling me to use karma

### ISSUE THREAD

**Issue by bitmatt2** [Hekili/hekili#849]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by bitmatt2** [comment]
hello, when playing my windwalker monk it recommends to use good karma (when talented) but not karma itself if im not talented into good karma. also, is there a way i can move a spell like weapons of order or good karma to show up as a cooldown rather than be on my primary or aoe bar.

build: v9.0.2-1.0.35
level: 60 (60)
class: MONK
spec: windwalker

talents: chi_burst
    dance_of_chiji
    diffuse_magic
    fist_of_the_white_tiger
    ring_of_peace
    tigers_lust
    whirling_dragon_punch

pvptalents: none

covenant: kyrian

conduits: coordinated_offensive = 5
   harm_denial = 3
   strike_with_clarity = 1
   tumbling_technique = 5

soulbinds: [pelagos]
   cleansed_vestments = 1
   combat_meditation = 1
   focusing_mantra = 1

sets: none

gear: collectors_pulse_staff = 1
    cowled_batwing_cloak = 1
    darkmoon_deck_voracity = 1
    entwined_gorger_tendril = 1
    guild_tabard = 1
    inscrutable_quantum_device = 1
    miasmalacquered_jerkin = 1
    radiant_light_binders = 1
    ring_of_perpetual_conflict = 1
    selfless_bearers_hands = 1
    selfless_bearers_legs = 1
    studscarred_footwear = 1
    trailspinner_pendant = 1
    umbrahide_helm = 1
    waistcord_of_dark_devotion = 1
    wicked_bladewing_pauldrons = 1

legendaries: invokers_delight = 1

itemIDs: 172317, 173087, 177053, 177054, 178707, 178823, 178847, 178848, 178858, 178872, 179347, 179350, 183009, 183010, 183034, 5976

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Windwalker
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    strict = false
    throttleRefresh = false
    throttleTime = false
    allow_fsk = false
    check_wdp_range = true
    optimize_reverse_harm = false
    tok_damage = 1

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = dual
    potions = false

**Comment by bitmatt2** [comment]
btw. i tried to add the weapons of order spell to my cooldown toggle and it did not work

**Comment by Hekili** [comment]
Internally, the addon required Good Karma for Touch of Karma to be recommended.  I'll lift this requirement.

Additionally, keep an eye on your WW setting regarding incoming damage for Touch of Karma.

> btw. i tried to add the weapons of order spell to my cooldown toggle and it did not work

Which part of putting Weapons of Order on your CD toggle did not work?

![image](https://user-images.githubusercontent.com/9438134/105250031-0cc56200-5b47-11eb-8af7-989be9463b4b.png)

![image](https://user-images.githubusercontent.com/9438134/105250047-14850680-5b47-11eb-8119-868c203b9969.png)

![image](https://user-images.githubusercontent.com/9438134/105250072-236bb900-5b47-11eb-867d-895f03a4edea.png)

**Comment by Hekili** [comment]
The ToK changes (not requiring Good Karma) will appear in the next release.

**Comment by bitmatt2** [comment]
i added it to the cooldowns toggle like you did in the first screenshot
(which worked for me with good karma), but it still will not show up in the
cooldown window (i have cds shown separately). so since ur lifting the
requirement will karma now show up as well as good karma. i have the
incoming damage for karma set to 1.

**Comment by Hekili** [comment]
Please fill out the ticket (following the instructions re: snapshots); I can't investigate further without the required information.

Remember, snapshots are to be taken when you think the addon should recommend what you're concerned with (Weapons of Order, in this case).  Provide snapshots for both the Primary and Cooldowns displays.
