### ISSUE TITLE
Wake of Ashes/Divine Toll not being recommenced in AoE with Execution Sentenc

### ISSUE THREAD

**Issue by lloydBl** [Hekili/hekili#850]
**Describe the Bug/Issue**
This issue is for the ret paladin priority list. Wake of Ashes and Divine Toll are not being recommended by the addon in situations where there are more than 3 active targets.  This is due to Wake of Ashes and Divine Toll having dependencies on the Execution Sentence debuff up or on cooldown.  However in AoE situations, Execution Sentence is (correctly) never commended when there are 4 or more targets (Divine storm is correctly recommended instead).  Wake of Ashes and Divine Toll however should be recommended in AoE situations even if execution sentence is un-used. 

**To Reproduce**
Spec into Execution Sentence
Engage in AoE (4+ targets) combat

**Expected behavior**
Wake of Ashes and Divine Toll should be recommenced as a builder in AoE situations even when Execution Sentence is left unused (not on cooldown)

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/NsbfDd6F

 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/qt0zc0hL

This snapshot was taken with 5 targets while while Execution sentence was available.  Holy Power deficit is high but neither Wake of Ashes or Divine Toll are recommended as a generator.

**PUT ERROR MESSAGE(S) HERE:**
N/A

**Comment by lloydBl** [comment]
I should note I made a copy of the defualt ret priority and called it "Ret Mine" in the snapshot.  I have not edited the priority list other than un-enabling Wings/Holy Avenger/Trinkets in the cooldown Action List. Generators and Finishers remain untouched and this issue stilll occurs using the default priority list

**Comment by Hekili** [comment]
> However in AoE situations, Execution Sentence is (correctly) never commended when there are 4 or more targets (Divine storm is correctly recommended instead).

That is not what my priority says and does.

Execution Sentence -- and the pathway to reach the recommendation for Execution Sentence -- is indifferent toward the number of targets.

I can't troubleshoot customized action lists; there's not enough time in the day.  If you replicate this behavior with default settings and priority, feel free to submit a new ticket.
