### ISSUE TITLE
Does not show correct keybinds

### ISSUE THREAD

**Issue by JamesParkDev** [Hekili/hekili#852]
**Describe the Bug/Issue**
Does not correctly show keybinds for bound (with shift or ctrl in front maybe other combinations) splell

**To Reproduce**
- Use Dominos (Simple UI like Elvui but for me, it's better than it)
- Set some spell with quick keybind (must be with Shift + [Something] or Ctrl + [Something])

**Expected behavior**
It should show correct keybind like "CE" not "E"

**Screenshots**
![image](https://user-images.githubusercontent.com/36516118/105221915-0db3bf00-5b5a-11eb-9988-67460907822b.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here: https://pastebin.com/GbD3YWyh.

**Comment by Hekili** [comment]
You can manually set keybinds for each ability if the autodetection does not suffice.
