### ISSUE TITLE
Use a title that describes the problem scenario.

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#853]
Hi! Actually I am not sure if it is bug or not but during normal rotation from time to time addon suggests to wait about 3-4 seconds to use next spell. It might be the coded logic but it seems very weird for me to lose such a huge ammount of uptime. 

Here is the snapshot. Nothing special to reproduce, just kill mobs

https://pastebin.com/0q1zwD6m

**Comment by Hekili** [comment]
Please fill out tickets correctly and completely.

The snapshot provided does not match the situation you're describing.  There are wait times in the Windwalker priority but 3 - 4 seconds does sound like a lot.

Feel free to submit a new ticket with a correct title and all of the details requested, if/when you get a snapshot that shows a significant wait time before the next recommendation.
