### ISSUE TITLE
Confusing Fire Blast recommendation on Fire Mage

### ISSUE THREAD

**Issue by thomas-henley** [Hekili/hekili#857]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
While using Hekili on Fire Mage, I often get recommendations to burn my last charge of Fire Blast even when I am not "Heating Up." This is likely causing a DPS loss, as it means I can't use that Fire Blast to generate a "Hot Streak" the next time "Heating Up" does proc.

**To Reproduce**
Reproducible by just doing the fire mage rotation with Hekili. I think it usually happens a little while after the first use of Shifting Power.

**Expected behavior**
Since I am not capping on Fire Blast charges, I would expect it to wait until a "Heating Up" proc before telling me to use Fire Blast.

**Screenshots**
I didn't get screenshots (sorry) but I think the snapshot should show the issue well enough.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/1V9tcyDx

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/whMCJgy0

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Thanks for the information.

The entry for Fire Blast that was selected met its criteria:

```
46.  fire_blast ( default - 28 )
The action (fire_blast) is usable at (0.00 + 0.00) with cost of 500 mana.
 - the action is ready before the current recommendation (at +0.00 vs. +4.77).
 - this entry's criteria PASSES: ! variable.fire_blast_pooling[false] & ( variable.time_to_combustion[48.13] > 0 | active_enemies[1.00] >= variable.hard_cast_flamestrike[2.00] & ! firestarter.active[false] & ! buff.hot_streak.react[0.00] & ( buff.heating_up.react[0.00] & action.flamestrike.execute_remains[0.00] < 0.5 | charges_fractional[1.20] >= 2 ) )
Action chosen:  fire_blast at 0.00!
```

I'll have to do some digging with regard to the `action.shifting_power.full_reduction` expression, which influences the `fire_blast_pooling` variable and *might* be miscalculated (I'll research this).  But effectively, it's true -- you're not pooling Fire Blast for your Combustion window at this time.

The other relevant check is `time_to_combustion` -- here it's showing Combustion will be about 48 seconds out.  Since that's greater than zero, the rest of the values in this set of conditions don't really matter.

If you want to sim yourself on Raidbots and link it, we can look at how often this Fire Blast entry is used, and can also run a comparison sim to see what the performance difference is if it were disabled.

**Comment by thomas-henley** [comment]
I get that it's not in the "pooling" phase, but even so, you don't dump your FB charges unless you're about to cap. You use them when your fireballs crit to generate "Hot Streak". Of course, I could be misunderstanding something about the spec (getting a better understanding is why I'm using Hekili in the first place) but this is pretty fundamental Fire Mage doctrine.

Here's a quick sim: https://www.raidbots.com/simbot/report/8HLpZneS8v6FFtfJnicH9r

**Comment by thomas-henley** [comment]
Yeah, if I'm reading this Raidbots report right, something is definitely off -- it looks like it's an AOE rule that the addon is getting confused by?

```
fire_blast,use_off_gcd=1,use_while_casting=1,if=!variable.fire_blast_pooling&(variable.time_to_combustion>0|variable.disable_combustion)&active_enemies>=variable.hard_cast_flamestrike&!firestarter.active&!buff.hot_streak.react&(buff.heating_up.react&action.flamestrike.execute_remains<0.5|charges_fractional>=2)
When Hardcasting Flame Strike, Fire Blasts should be used to generate Hot Streaks and to extend Blaster Master.
```

**Comment by thomas-henley** [comment]
Hek:
( variable.time_to_combustion[48.13] > 0 | active_enemies[1.00] >= variable.hard_cast_flamestrike[2.00]

Raidbots:
(variable.time_to_combustion>0|variable.disable_combustion)&active_enemies>=variable.hard_cast_flamestrike

Looks like the wrong operator might have been pulled out along with that `variable.disable_combustion`

**Comment by Hekili** [comment]
It does look that way. Will revise.

**Comment by ronniebex** [comment]
thanks @Hekili @thomas-henley  , 

I was very happy to see a revision can be done. thanks for the effort . 
@thomas-henley i still miss the arcane mage  :-) but yeah m+ this is almost not posible . 

have a nice day !
