### ISSUE TITLE
Wake of Ashes/Divine Toll/Execution Sentence not being recommenced in AoE with Default Action List

### ISSUE THREAD

**Issue by lloydBl** [Hekili/hekili#858]
**Describe the Bug/Issue**
Same issue from previous report persists with default built in retribution priority list.

Wake of Ashes and Divine Toll are not being recommended by the addon in situations where there are 4 or more active targets.  This may be related to the fact that Execution Sentence is not recommended either in 4+ target situations.  From my understanding Execution Sentence is correctly not recommended in AoE as per the default priority conditions (specifically the  spell_targets.divine_storm <= 3 requirement to recommend). Without using Execution Sentence, Divine Toll/Wake of Ashes are not being recommended. 

**To Reproduce**
Spec into Execution Sentence
Engage in AoE (4+ targets) combat

**Expected behavior**
Wake of Ashes and Divine Toll should be recommenced as a builder in AoE situations. Possibly Execution sentence should be recommended as well in AoE.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/3wjLGrVk

 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/ed1iQMDS

This snapshot was taken with 5 targets (target dummies in Kyrian covenant base) while while Execution sentence was available.  This was using the default retribution action list with no modifications. Holy Power is zero but neither Wake of Ashes or Divine Toll are recommended as a generator. Neither ability was ever recommended unless Execution Sentence was pressed first.  Execution sentence was also never recommended

**PUT ERROR MESSAGE(S) HERE:**
N/A

**Comment by Hekili** [comment]
Execution Sentence is listed as not usable. Can you post a screenshot of your /hekili > Abilities > Execution Sentence settings?

**Comment by lloydBl** [comment]
See attached.  I'm not sure how to fully read your snapshot format (so this may be unhelpful), but this snapshot was taken when holy power was at zero (so Execution Sentence would have been not usable).  Below is an additional snapshot taken immediately after casting Final Reckoning when I had 3 holy power. This is where I would typically expect Execution Sentence to be recommended.  The previous snapshot was taken after following the Final Reckoning with a Divine Storm (which was recommended).

https://pastebin.com/EQq7s1tg

![WoWScrnShot_012121_181409](https://user-images.githubusercontent.com/50121257/105436810-bd4d6780-5c14-11eb-9289-e87afe246723.jpg)

**Comment by lloydBl** [comment]
I don't want to speculate too much on your Execution Sentence conditions given I do not know where the conditions come from, but removing the "spell_targets.divine_storm <= 3" from the default

spell_targets.divine_storm <= 3 & ( ( ! talent.crusade.enabled | buff.crusade.down & cooldown.crusade.remains > 10 ) | buff.crusade.stack >= 3 | cooldown.avenging_wrath.remains > 10 | debuff.final_reckoning.up ) & time_to_hpg = 0

does allow for Execution Sentence to be recommended in these AoE situations (4+ targets).  This then causes Divine Toll and Wake of Ashes to be recommended as well after Execution Sentence is cast.  Of course I have no idea if this removal is optimal given what the built in considers is the best usage of Execution Sentence

**Comment by Hekili** [comment]
Yeah, that check is already gone in the beta branch with the latest profile updates.  You should try the latest beta and see if you find issues.

**Comment by lloydBl** [comment]
Yep new updated action lists in the beta build work as expected and don't cause this issue.  Thanks for the update

**Comment by Hekili** [comment]
Thanks for confirming!  Sorry for the time it took!
