### ISSUE TITLE
Add Kezan Stamped Bijou trinket

### ISSUE THREAD

**Issue by sneezyyzeens** [Hekili/hekili#86]
I have a 385 version of the trinket and I don't see me getting an upgrade anytime soon.  I add in the code manually, but there have been so many updates lately it seems like I have to edit the file every day.

Code to add to Classes.lua:

`
all:RegisterAbility( "kezan_stamped_bijou", {
    cast = 0,
    cooldown = 60,
    gcd = "off",
    item = 165662,
    toggle = "cooldowns",
} )
`

**Comment by Hekili** [comment]
Will add the missing trinket.

**Comment by Hekili** [comment]
Will appear in 8.1.5-04.
