### ISSUE TITLE
[UH-DK] Epidemic in AOE works incorrectly.

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#867]
**BEFORE SUBMITTING AN ISSUE:**

1.  v9.0.2-1.0.36-beta9

2. I opened it earlier. But I decided to try your addon again.

**Describe the Bug/Issue**

As soon as new targets are added to the main battle, the addon recommends using the epidemic without an outbreak. And he had to offer to update the outbreak on the main target, and outweigh the new targets on a number. This is how it should work.

**To Reproduce**

- Starting a boss fight
- We press Outbreak if Unholy Blight is not taken.
- The tank is adding more adds.
- Then an epidemic appears in the rotation.
- And here is a bug, since nearby targets do not have an outbreak, but the epidemic was proposed for rotation

**Expected behavior**

In short, it should be so:
- Starting a boss fight
- We press Outbreak if Unholy Blight is not taken.
- The tank is adding more adds.
- I press outbreak or Unholy Blight. And then only I push the epidemic.

**Screenshots**
https://imgur.com/a/qir7dMZ

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here. **(https://pastebin.com/FZtEHQmL)**

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here. **(https://pastebin.com/tmmm8Vw7)**
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.
**(The addon does not freeze, and does not turn off, the rotation is just broken. I have nothing to put here.)**

**PUT ERROR MESSAGE(S) HERE:**

Please correct the error in the rotation with the epidemic when adding new goals to the main one. So that the addon recommends using the outbreak when adding new targets, so that the epidemic works correctly and only when there is a buff from the outbreak. Without an outbreak buff, the epidemic should not be rotated.

P.S. If you have time, please make sure death and decay is offered in rotation when the targets are near the character. But not when the targets are far away, but death and decay appears in rotation, this is very inconvenient thanks.

**Comment by Hekili** [comment]
Please provide a Raidbots sim of your character (Hectic Add Cleave) for comparison purposes.

**Comment by Hekili** [comment]
Also, please provide a snapshot from *when the behavior you describe is actually occurring*.  Per the instructions:

`When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.`

In this case, you'd press Pause (ALT-SHIFT-P) or Snapshot (ALT-SHIFT-[) when Epidemic is recommended but you would've preferred to Outbreak first.  Put that snapshot on Pastebin and link here.
