### ISSUE TITLE
Feral Druid Errors

### ISSUE THREAD

**Issue by Seahaze350** [Hekili/hekili#869]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
3127x Hekili\Classes\DruidFeral.lua:1203: attempt to compare number with boolean
[string "@Hekili\Classes\DruidFeral.lua"]:1203: in function <Hekili\Classes\DruidFeral.lua:1201>
[string "=(tail call)"]: ?
[string "@Hekili\State.lua"]:6454: in function `TimeToReady'
[string "@Hekili\Core.lua"]:751: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:820: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:1284: in function `GetNextPrediction'
[string "@Hekili\Core.lua"]:1580: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:824: in function <Hekili\UI.lua:689>

**Comment by Hekili** [comment]
WHEN SUBMITTING AN ISSUE:

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

PUT ISSUE REPORT LINK HERE:

**Comment by Hekili** [comment]
@Seahaze350 Could you provide the missing information, please?

**Comment by Hekili** [comment]
I'm posting a test fix which is literally just a reimport of the Feral priority.  I won't be able to replicate this issue without knowing more about your situation.

**Comment by Hekili** [comment]
Reopening in case someone has details to provide. Make sure you're using the latest release.

**Comment by Hekili** [comment]
Okay, I believe you may have been using an imported priority from elsewhere.  This should be resolved, but I'd check for an updated priority from your source(s) just to be sure.

**Comment by Seahaze350** [comment]
Just tested seems like its fixed :)

**Comment by Hekili** [comment]
Thanks for confirming.
