### ISSUE TITLE
outlaw routine got scuffed

### ISSUE THREAD

**Issue by IronMongrel** [Hekili/hekili#87]
actions.finish+=/slice_and_dice,if=**(active_enemies=1|buff.blade_flurry.down)**&(buff.slice_and_dice.remains<target.time_to_die&buff.slice_and_dice.remains<(1+combo_points)*1.8)
actions.finish+=/roll_the_bones,if=**(active_enemies=1|buff.blade_flurry.down)**&(buff.roll_the_bones.remains<=3|variable.rtb_reroll)

These parts are wrong. I think the idea was "don't reroll during blade flurry," which is *kind of* a thing, but that's only **re**rolling, and it's only applicable for large numbers of enemies. I'm not sure what the cutoff point is, but I'm personally putting it at 4. You also should be maintaining RTB 100% of the time, so the buff remains <= 3 should be a hard check.

actions.finish+=/roll_the_bones,if=buff.roll_the_bones.remains<=3|((active_enemies<4|buff.blade_flurry.down)&(variable.rtb_reroll))

That's what I came up with.

**Comment by Hekili** [comment]
I think the intent was also on the Blade Flurry end of things -- I wasn't going to have it recommend BF unless you had a buff up, but may have left that out.  I'll take a look at it.

**Comment by Hekili** [comment]
Incoming fix in 8.1.5-04.
