### ISSUE TITLE
Show "Spell is Queued" Glow

### ISSUE THREAD

**Issue by sfogarty** [Hekili/hekili#871]
It would be helpful if Hekili replicated the "spell is queued" glow that occurs on the action button itself. 
* For clarity, this is the WoW spell queue, that determines what spell will be cast when the next GCD is up.
* Perhaps set by separate checkboxes in the 'Glow' tab. 
* If a spell that is not in the Hekili queue is next in the WoW spell queue, it could be put at the front of the Hekili queue or ignored.
* This would help users to know when they have successfully queued the spell, and stop hammering on their keys and inflaming their RSI. Or perhaps just to provide useful information, in a more general sense.

**Comment by Hekili** [comment]
Thanks for the ticket.

It looks like this *could be* pretty straightforward via the `IsCurrentSpell` API call, but I wonder about scenarios where you press the same button repeatedly (Shred, Shred, Shred).  I could potentially support this in the primary icon for instants, but dealing with hardcast spells might be a challenge.

**Comment by Hekili** [comment]
This has long since been implemented (to mixed feedback).
