### ISSUE TITLE
Cold Blood (rogue pvp talent) update

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#872]
Hi! As for shadowlands Cold Blood neither starts combat nor is on GCD. That is why I suggest to substitute

 cold_blood = {
            id = 213981,
            cast = 0,
            cooldown = 60,
            gcd = "spell",
            
            pvptalent = "cold_blood",            

            startsCombat = true,
            texture = 135988,

With

 cold_blood = {
            id = 213981,
            cast = 0,
            cooldown = 60,
            gcd = "off",
            
            pvptalent = "cold_blood",            

            startsCombat = false,
            texture = 135988,

**Comment by Hekili** [comment]
Thanks, I'll update it.
