### ISSUE TITLE
Frost DK recommendations only shows Chains of Ice

### ISSUE THREAD

**Issue by Vsmit** [Hekili/hekili#873]
Version 9.0.2-1.0.36b

**Describe the Bug/Issue**
Problem with Frost Death Knight recommendations, display only shows Chains of Ice after Pillar of Frost goes on CD. Does not occur in v 1.0.35, reverted from new version to test. Does not occur on Azeroth, only in Shadowlands.

**To Reproduce**
Enter combat, cast PoF, follow recommendations.
 
**PUT SNAPSHOT LINK HERE:**

https://pastebin.com/eh44LeM8

**Comment by Hekili** [comment]
This is addressed in 1.0.37, though I'm not entirely clear on why it didn't happen in 1.0.35.  But I just removed the "last-second Chains of Ice as the fight ends" entry because it really doesn't provide a meaningful benefit anyway.
