### ISSUE TITLE
Pistol Shot not suggested during Opportunity procs with talent Ghostly Strike  

### ISSUE THREAD

**Issue by dariogentiletti** [Hekili/hekili#875]
**Describe the Bug/Issue**
As outlaw rogue, when having the talent Ghostly Strike and get Opportunity procs, Hekili does not suggest to use Pistol Shot but only Sinister Strike. There is no reason to not use PS when is free and use SS instead. 

**To Reproduce**
- Get talent "Ghostly Strike"
- Go to a dummy and hit until you get Opportunity Procs
- After casted the other priorities, it would suggest you to use SS instead of Pistol Shot. 

**Expected behavior**
Pistol Shot should be suggested instead of SS.

**Screenshots**
//

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

N/A (Server restarted and forgot to copy it, but aside having Ghostly Strike I'm confident you can replicate with any other gear and talent)

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/RMXZQHC3

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

N/A

**Comment by Hekili** [comment]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

**Comment by Hekili** [comment]
You're a few versions behind, that includes an Outlaw update.  Let me know if you have an issue after you've updated.

**Comment by dariogentiletti** [comment]
Just downloaded the latest release and tested on a dummy. There is still the same issue. 
Here a screenshot where it suggests me SS when it should be PS:

![Screenshot from 2021-01-26 23-48-25](https://user-images.githubusercontent.com/40705549/105944291-05afbf80-6031-11eb-8a0f-b8f61a7ca2f2.png)

**Comment by dariogentiletti** [comment]
I believe it is possible it suggested SS instead of PS because I had capped energy. I'll try again to see if it suggests even below <70 energy.

**Comment by Hekili** [comment]
Sure.  But also, include snapshots, not screenshots.

Yes, at least some of the Oppo logic involves using it when your Energy is low enough that the regen during the GCD isn't wasted.
