### ISSUE TITLE
Healthstone toggle bugged.

### ISSUE THREAD

**Issue by ShmooDude** [Hekili/hekili#877]
**Describe the Bug/Issue**
Healthstone (the item), can't be properly added to the defensive toggles.  In the priority, after doing the steps in the "To Reproduce" below, Healthstone will now show up in both Defensives and Primary if added to the action list despite having Defensives set as show separately.

**To Reproduce**
- Go to 'Feral' (or probably whatever your active spec is)
- Open `Toggles`
- Open 'Defensives'
- Click on '+ Add Ability'
- Select `Healthstone` from dropdown.
- Notice how `Healthstone` is not listed.

**Expected behavior**
When added to the defensives, Healthstone (and presumably other items?) should:
1) Show up in the Defensives ability list.
2) Not be shown in the Primary window if Show Separately is checked.

**Note**
Hopefully this is a simple fix.  I suspect its just not looking in "items" settings for toggles in some places where it should be.

**Saved Variables**
```[103] = {
					["maxRefresh"] = 10,
					["custom2Name"] = "Custom 2",
					["throttleRefresh"] = false,
					["damagePets"] = false,
					["throttleTime"] = false,
					["settings"] = {
						["owlweave_cat"] = true,
					},
					["debuffPadding"] = 0,
					["aoe"] = 3,
					["gcdSync"] = true,
					["damageDots"] = false,
					["damage"] = false,
					["enabled"] = true,
					["petbased"] = false,
					["maxTime"] = 33,
					["nameplates"] = true,
					["custom1Name"] = "Custom 1",
					["cycle_min"] = 6,
					["abilities"] = {
						["regrowth"] = {
							["toggle"] = "none",
						},
						["swiftmend"] = {
							["toggle"] = "defensives",
						},
						["convoke_the_spirits"] = {
							["toggle"] = "cooldowns",
						},
						["tigers_fury"] = {
							["toggle"] = "none",
						},
					},
					["cycle"] = false,
					["items"] = {
						["healthstone"] = {
							["toggle"] = "defensives",
						},
					},
					["nameplateRange"] = 8,
					["potion"] = "spectral_agility",
					["buffPadding"] = 0,
					["potionsReset"] = 20180919.1,
					["damageExpiration"] = 3,
					["package"] = "ShmooDude Feral",
					["damageRange"] = 0,
				},
```
**PUT ISSUE REPORT LINK HERE:** 
build: v9.0.2-1.0.38
level: 60 (60)
class: DRUID
spec: feral

talents: balance_affinity
    bloodtalons
    brutal_slash
    heart_of_the_wild
    sabertooth
    soul_of_the_forest
    wild_charge

pvptalents: none

covenant: night_fae

conduits: born_of_the_wilds = 6
   conflux_of_elements = 5
   taste_for_blood = 5
   wellhoned_instincts = 5

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   run_without_tiring = 1

sets: none

gear: azurevenom_choker = 1
    bloodoath_signet = 1
    chiropteran_leggings = 1
    fastened_venombarb_binds = 1
    fleshfused_circle = 1
    girdle_of_shattered_dreams = 1
    mantle_of_manifest_sins = 1
    miasmalacquered_jerkin = 1
    primeval_souls_ankleguards = 1
    quarterstaff_of_discordant_ethic = 1
    rocket_chicken_handlers = 1
    sinful_gladiators_leather_shoulderpads = 1
    skulkers_wing = 1
    stone_legion_heraldry = 1
    umbrahide_helm = 1

legendaries: circle_of_life_and_death = 1

itemIDs: 172317, 178373, 178805, 178869, 178871, 178934, 179336, 179352, 180097, 180115, 182993, 183009, 183033, 184016, 184027

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 3
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = ShmooDude Feral
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    owlweave_cat = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Healthstone falls within the Gear and Trinkets category rather than as a regular ability, though the phrasing here is kind of misleading.  As noted on the Feral > Toggles screen, Gear and Trinkets are adjusted in a different screen.

![image](https://user-images.githubusercontent.com/9438134/106181474-a30f0e80-616b-11eb-95ed-4ad0b33929d5.png)

The reason for this is just that there are a lot of trinkets and most of them are flagged as Cooldowns.  Including them in this screen would make it a very long list.

In /hek > Gear and Trinkets, you can select Healthstone from the list and set Require Toggle = Defensives.

![image](https://user-images.githubusercontent.com/9438134/106181669-e10c3280-616b-11eb-9acc-1f6becc8d32a.png)

Let me know if that does not get you the result you're looking for.

**Comment by ShmooDude** [comment]
So doing the steps under **To Reproduce** actually does properly set the Healthstone toggle to Defensives.  It just doesn't add it to the list abilities list because as you pointed out it falls under Gear and Trinkets.

There is still the issue that it shows up now in both the "Defensives" and "Primary" display, so its not being properly removed from the "Primary" display.

![Healthstone](https://user-images.githubusercontent.com/5076859/106194992-9398c100-617d-11eb-984d-d813e47f448c.jpg)
From Left to Right: Defensives, Cooldowns, Primary(3 icons)
---

As a note, I wouldn't consider Healthstone "Gear and Trinkets" as to me that implies equippable items.  But you're saying that its really any items (which makes sense from a programming point of view).

**Comment by Hekili** [comment]
Yeah, the reason is that Gear and Trinket existed as a category (separating out items in general since it's a long list) before Healthstones were added.

I can definitely look at why it's not successfully filtered from Primary.  Should be simple to fix.

**Comment by Hekili** [comment]
This appears to be resolved.
