### ISSUE TITLE
[Request] Prot Paladins & Exclude Out-of-Range

### ISSUE THREAD

**Issue by DeezIssues** [Hekili/hekili#879]
Shield of the Righteous is currently suggested even when you are out of melee range of any enemies.

Consecration is also suggested when there is nothing in range of the AoE effect.

https://www.wowhead.com/spell=53600/shield-of-the-righteous
https://www.wowhead.com/spell=26573/consecration

Would you be willing to add these abilities to the list for excluding when out of range? 

My reason for asking is because these two abilities either halt the rotation until you waste a GCD casting Consecration, or waste holy power when you're ranged by casting Shield of the Righteous.

Thank you!

**Comment by Hekili** [comment]
No, you're going to have to do the work to manage positioning.  Putting a range-filter on SotR based on your target is a bad idea as you could be tanking multiple.  If you're a tank and you're out of range, you should get in range.
