### ISSUE TITLE
too much Ram usage

### ISSUE THREAD

**Issue by borgraman** [Hekili/hekili#88]
Earlier patch before 8.1.5 it didnt lag that much atm i have removed 90 % of my addons only using elvui and hekili still can feel the aoe lag when reaping comes up and big trash pulls there is a lag and addon uses around 30mb is it normal ?.

**Comment by Hekili** [comment]
Please submit a proper ticket.  I don't know what version you're using.

The addon will use 10 MB at baseline and then the longer you're playing and the more you do, it will take up some more memory until the garbage collector fires.  I'll be doing some work on that, but there isn't a performance impact from that.

I'm guessing you haven't updated to the latest version.
