### ISSUE TITLE
Freezing and lagging when using spells at the mage

### ISSUE THREAD

**Issue by weedgazm322** [Hekili/hekili#881]
On other classes, everything is fine, but when I switch to a mage and use spells, the game starts to freeze and lag, only when using spells, when mobs attack me, it also starts to freeze. This problem is only on fire magician. https://www.youtube.com/watch?v=BOvAxmrkWiM

**Comment by Hekili** [comment]
Fire Mage is a complex priority and requires more work.  You can show fewer icons or look at your /hekili > Fire > Performance options.  Or don't use it.

Please submit full and proper tickets when submitting a report.
