### ISSUE TITLE
Having a serious issue with FPS drops while using this add-on for certain classes. 

### ISSUE THREAD

**Issue by Woodzy13** [Hekili/hekili#882]
Whilst playing classes like DK / Mage and Boomie i am having serious FPS problems whilst in combat. My main which is a warrior has no issues with this at all but atm playing my Unholy DK this has been a major issue.

Character data below;

build: v9.0.2-1.0.38
level: 60 (60)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    army_of_the_damned
    asphyxiate
    soul_reaper
    spell_eater
    unholy_blight
    unholy_pact

pvptalents: none

covenant: necrolord

conduits: brutal_grasp = 1
   convocation_of_the_dead = 4
   hardened_bones = 5
   spirit_drain = 4

soulbinds: [plague_deviser_marileth]
   oozs_frictionless_coating = 1
   plagueborn_cleansing_slime = 1
   volatile_solvent = 1

sets: none

gear: ardent_sunstar_signet = 1
    baetheas_ironclad_warboots = 1
    charm_of_eternal_winter = 1
    darkmoon_deck_voracity = 1
    decadent_nathrian_shawl = 1
    fallen_templars_gauntlets = 1
    gormshell_greaves = 1
    muirnnes_stormforged_signet = 1
    shadowghast_breastplate = 1
    soldiers_stoneband_wristguards = 1
    stoic_guardsmans_belt = 1
    stone_legion_heraldry = 1
    tabones_branded_pauldrons = 1
    ulfius_calming_claymore = 1
    wrathbark_greathelm = 1

legendaries: deadliest_coil = 1

itemIDs: 171412, 173087, 178694, 178701, 183013, 183025, 183031, 183035, 183040, 184027, 184778, 184783, 184796, 184804, 184809

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycleDebuff = festering_wound
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 4
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = true
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false

Any advice for this would be great.

**Comment by Hekili** [comment]
Your options for managing performance are in /hek > *spec* > Performance.

Beyond that, I'm always looking for opportunities to improve efficiency but nothing I can offer you. 

Longer, more complex priorities require more calculation time.

More displayed icons require more calculation time. 

When submitting a ticket for any particular spec you're concerned with, please provide a snapshot taken at a time performance is an issue. It may help identify specific priorities that can be further tuned.
