### ISSUE TITLE
Cheap Shot and Kidney Shot fix for Sub Rogues

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#887]
I was searching through the code at Sub Rogue profile and noticed if I am right some outdated info. There is nothing wrong in the snapshots i believe because these abbilities are never suggested. I just want to share my thoughts as I think it is still a bug.

I believe that Cheap Shot has some outdated combopoint gain info in sub rogue profile. Now it is at the line 735 like this

` gain( 2 + ( buff.shadow_blades.up and 1 or 0 ), "combo_points" )`

Right one should be like this 

`gain( buff.shadow_blades.up and 2 or 1, "combo_points" )`

And Kidney Shot in game does not consume an animacharged CP that is why the string which codes the logic as it consumes animacharged CP is incorrect. Also I think it might be useful to add
 
`applyDebuff( "target", "kidney_shot", 1 + ( 1 * combo_points.current ) )`

to kidney shot aura info.

So basically  I think it would be nice to have the following change to kidney shot function in Sub Rogue profile

        kidney_shot = {
            id = 408,
            cast = 0,
            cooldown = 20,
            gcd = "spell",

            spend = function () return 25 * ( ( talent.shadow_focus.enabled and ( buff.shadow_dance.up or buff.stealth.up ) ) and 0.8 or 1 ) * ( 1 - conduit.rushed_setup.mod * 0.01 ) end,
            spendType = "energy",

            toggle = "cooldowns",

            startsCombat = true,
            texture = 132298,

            usable = function () return combo_points.current > 0 end,
            handler = function ()
                if talent.alacrity.enabled and combo_points.current > 4 then
                    addStack( "alacrity", 20, 1 )
                end

    applyDebuff( "target", "kidney_shot", 1 + ( 1 * combo_points.current ) )

                local combo = min( talent.deeper_stratagem.enabled and 6 or 5, combo_points.current )
                applyBuff( "kidney_shot", 2 + 1 * ( combo - 1 ) )

                if talent.prey_on_the_weak.enabled then applyDebuff( "target", "prey_on_the_weak" ) end
               
                spend( min( talent.deeper_stratagem.enabled and 6 or 5, combo_points.current ), "combo_points" )
            end,
        },

**Comment by Hekili** [comment]
This will go in the next build.
