### ISSUE TITLE
[Request] - Stoneform (Dwarven Racial)

### ISSUE THREAD

**Issue by cheelerocheeler** [Hekili/hekili#888]
Hi,

Unless I'm mistaken, stoneform doesn't appear to be an option from which I can choose. Would like to add this racial ability to my Prot Pally mitigation rotation upon certain conditions. Thank you for any consideration/direction!

**Comment by Hekili** [comment]
Sure, not a high priority issue but I can add it.

**Comment by Hekili** [comment]
This will be in the next beta or release (after 1.0.40).
