### ISSUE TITLE
Pyroblast Hardcasts with Searing Touch Talent - Bosses: <30% HP

### ISSUE THREAD

**Issue by sanyex89** [Hekili/hekili#889]
**Describe the Bug/Issue**
Hekili sometimes suggests to hardcast pyroblast with the searing touch talent - 

if the boss is under 30% hp the addon sometimes suggest: Scorch -> generates heating up -> needs another crit to instant cast pyro -> instead suggests hardcasting pyroblast

Shouldnt it be Scorch->Fire Blast/PF/another Scorch -> Pyro ? 

**WHEN SUBMITTING AN ISSUE:**

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/VkpRLVLm

https://pastebin.com/6h5UT0TF

**Comment by Hekili** [comment]
It's better not to delete the full ticket instructions, so that you are more likely to submit everything that is required.

The snapshot you provided is casting Fireball, which is not the scenario you described.  Make sure to provide a snapshot when the addon is requesting the hardcast of Pyroblast that you described.

**Comment by sanyex89** [comment]
https://pastebin.com/7PmPTN1W this was the other snapshot i created with a recommended pyroblast

**Comment by Hekili** [comment]
That snapshot shows that you have Hot Streak active.

**Comment by sanyex89** [comment]
sorry i am new to this kind of stuff - this should be the right snapshot - it went like this 2 times in a row -> scorch - pyroblast hardcast - scorch - pyroblast hardcast https://pastebin.com/vVFF5bsF - here is a screenshot - instead of waiting for Fire Blast or using another Scorch it suggested hardcasting pyro
![grafik](https://user-images.githubusercontent.com/77323774/106757729-00ee9b00-6631-11eb-9399-78bd373845b0.png)

another: https://pastebin.com/PZndGvdN

**Comment by sanyex89** [comment]
So its only happening IF the boss is under 30% and i dont have any Fire Blasts left - wouldnt it be better to use scorch 2 times instead of scorch + pyro?

**Comment by Hekili** [comment]
Of course.  But I needed you to provide the information to explore what is happening.

The next beta build will have some changes to how "buff.heating_up.react" and similar auras are handled, which may resolve this issue.

**Comment by sanyex89** [comment]
mh okay thanks for your help, i really enjoy your addon with every class and spec i am currently playing :) could there be an option to just get the rotation "while running" with the searing touch talent and the target under 30% hp? i mean i just tried running around and it was basicly the perfect rotation

**Comment by sanyex89** [comment]
same issue with beta 3 

https://pastebin.com/VHwWvuqf

another

https://pastebin.com/NeNep1c1

**Comment by Hekili** [comment]
Incoming fix.

**Comment by sanyex89** [comment]
https://pastebin.com/KcCXjwT9

its waaay better now, but still occurs sometimes
