### ISSUE TITLE
Location Parameters for Rotation Queue

### ISSUE THREAD

**Issue by JargerWolf** [Hekili/hekili#89]
Hello. I want to say that this addon is absolutely amazing and I am beyond elated to have it. The amount of time and effort that gets put into it amazes me and I thank you for it.

I have been using it for a long time and recently I noticed that my rotation queue had moved. I run ElvUI for my UI and I have everything adjusted around each other. I went in to check the settings on where it was to be positioned on the X & Y axis and I noticed that the Y axis had a new lower limit. I think its set so that it can be positioned between -384 & 384. I looked at a couple of my other toons who have the same layout and one of them had Y set to -481.85 (or something close to that). Is this a new feature that isn't allowing us to position the rotation queue that low or is it just a bug? I really liked having it there because it was positioned jut above my bars. I can make due with the change but I am hoping there is a way to revert it back to the old parameters.

Thank you again for all of your help with this and keep up the great work on the addon!!

Sincerely,
Jarger

**Comment by Hekili** [comment]
I haven't changed the options with regard to screen positioning at all.  I'm guessing you are scaling your UI differently than you had previously; the addon allows a range of +/- half of your vertical screen height for positioning.

I will leave the current displayed maxes (which are calculated from your screen resolution) but allow manual entry to go up to twice that.  You'll be able to manually enter your X/Y position in 8.1.5-04.
