### ISSUE TITLE
Balance rotation is wrong after importing APL from raidbots

### ISSUE THREAD

**Issue by papajuras** [Hekili/hekili#890]
This might be a bug or it might be a question, that depends on you Mr. Hekili.

**Describe the Bug/Issue**
After simming my character (balance) on raidbots I imported APL into the addon. Having my toggle on single target hekili gets 'stuck', it just spams sunfire for around 10 seconds (target has sunfire, no moonfire though). This is not what i can see in example rotation on raidbots neither what I would expect. If this an issue with APL please let me know.

**Expected behavior**
I would expect to spam wrath/starfire depending on current eclipse.

**WHEN SUBMITTING AN ISSUE:**

char info : https://pastebin.com/c9pMHSnU

2 separate snapshots of same issue 
https://pastebin.com/7ak3u15v
https://pastebin.com/dtavHQiT

APL from raidbots:
https://pastebin.com/hvHimWFn

**Comment by Hekili** [comment]
There's no reason for you to import the APL from Raidbots.  You only lose the adjustments I've made to have it work in-game.
