### ISSUE TITLE
Glyph of assimilation

### ISSUE THREAD

**Issue by Unethical-Sloth** [Hekili/hekili#893]
Hello,

I am having a hard time adding glyph of assimilation to my rotation. It does not show up by default and is not disabled in the list of gear/trinkets.

build: v9.0.2-1.0.38
level: 60 (60)
class: SHAMAN
spec: elemental

talents: echo_of_the_elements
    elemental_blast
    master_of_the_elements
    natures_guardian
    primal_elementalist
    spirit_wolf
    stormkeeper

pvptalents: none

covenant: kyrian

conduits: call_of_flame = 5
   elysian_dirge = 5
   refreshing_waters = 6
   thunderous_paws = 6

soulbinds: [pelagos]
   bond_of_friendship = 1
   combat_meditation = 1
   focusing_mantra = 1

sets: none

gear: arachnid_cipher_ring = 1
    charm_of_eternal_winter = 1
    dark_praetorians_clasp = 1
    glyph_of_assimilation = 1
    grimveiled_cape = 1
    harness_of_twisted_whims = 1
    hyperlight_band = 1
    mementoladen_cuisses = 1
    oathsworn_soldiers_gauntlets = 1
    rattling_deadeye_hood = 1
    striders_of_restless_malice = 1
    symphonic_chimekeeper = 1
    tabard_of_the_zandalari = 1
    unbound_changeling = 1
    watchful_arbelists_bracers = 1
    wintersnap_shoulderguards = 1

legendaries: windspeakers_lava_resurgence = 1

itemIDs: 165001, 173242, 178695, 178708, 178738, 178745, 178933, 178973, 179353, 180110, 182982, 182985, 182991, 183038, 183040, 184021

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Elemental
    petbased = false
    potion = potion_of_spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    stack_buffer = 1.1

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
I have it and it works for me.  If you provide all the required ticket information about your character, I may be able to figure out the issue in your specific case.

**Comment by Unethical-Sloth** [comment]
I just updated it,

Also, can I program it to remind me to use a potion during BL?

thank you

**Comment by Hekili** [comment]
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

I need the above to see if/why Glyph isn't recommended for you.

You can refer to the wiki re: customizing your priority for potions.  (The APL already has a potion action to use basically on CD, but you can add conditions to that as you desire.)

**Comment by Hekili** [comment]
(And you'll likely want to toggle CDs on before you take the snapshot, since trinkets are generally on the Cooldowns toggle.)

**Comment by Unethical-Sloth** [comment]
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.38
level: 60 (60)
class: SHAMAN
spec: elemental

talents: echo_of_the_elements
    elemental_blast
    master_of_the_elements
    natures_guardian
    primal_elementalist
    spirit_wolf
    stormkeeper

pvptalents: none

covenant: kyrian

conduits: call_of_flame = 5
   elysian_dirge = 5
   refreshing_waters = 6
   thunderous_paws = 6

soulbinds: [pelagos]
   bond_of_friendship = 1
   combat_meditation = 1
   focusing_mantra = 1

sets: none

gear: arachnid_cipher_ring = 1
    charm_of_eternal_winter = 1
    dark_praetorians_clasp = 1
    glyph_of_assimilation = 1
    grimveiled_cape = 1
    harness_of_twisted_whims = 1
    hyperlight_band = 1
    mementoladen_cuisses = 1
    oathsworn_soldiers_gauntlets = 1
    rattling_deadeye_hood = 1
    striders_of_restless_malice = 1
    symphonic_chimekeeper = 1
    tabard_of_the_zandalari = 1
    unbound_changeling = 1
    watchful_arbelists_bracers = 1
    wintersnap_shoulderguards = 1

legendaries: windspeakers_lava_resurgence = 1

itemIDs: 165001, 173242, 178695, 178708, 178738, 178745, 178933, 178973, 179353, 180110, 182982, 182985, 182991, 183038, 183040, 184021

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Elemental
    petbased = false
    potion = potion_of_spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    stack_buffer = 1.1

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = false
    interrupts = false
    mode = automatic
    potions = false


player_buffs:
   307166 - eternal_flask                            -   1 - 2693.98
     2645 - ghost_wolf                               -   1 - 3600.00
   225787 - sign_of_the_warrior                      -   1 - 3600.00
   334132 - vantus_rune_huntsman_altimor             -   1 - 389117.64
   292361 - embrace_of_paku                          -   1 - 3600.00
   260881 - spirit_wolf                              -   4 - 3600.00
     6673 - *Battle Shout                            -   1 - 3487.74

player_debuffs:

target_auras:  target does not exist


New Recommendations for [ Primary ] requested at 21:54:42 ( 624336.97 ); using built-in ( Elemental ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Elemental - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   earth_elemental ( precombat - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.03ms
        TimeData:Elemental-precombat-1:earth_elemental:0.03
        
        2.   stormkeeper ( precombat - 2 )
        The action (stormkeeper) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria PASSES: talent.stormkeeper.enabled[true] & ( raid_event.adds.count[0.00] < 3 | raid_event.adds.in[3600.00] > 50 )
        Action chosen:  stormkeeper at 0.00!
    
    Completed precombat action list [ Elemental - precombat ].
    Recommendation is stormkeeper at 0.00 + 0.00.
    Recommendation #1 is stormkeeper at 0.00s (0.00s).
    Queueing stormkeeper cast finish at 624338.30 [+1.33] on unknown.
    Queued stormkeeper from 624336.97 to 624338.30 (CAST_FINISH).
    Used 0.70ms of CPU on 1 prediction(s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.33, Casting: 1.33 ).

    There are 1 queued events to review.
    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    
    Finishing queued event #1 ( CAST_FINISH of stormkeeper ) due at 1.33 as player is casting and castable spells are not ready.
    Casting: Yes, Channeling: No, Break: No, Check: No
    While advancing by 1.33 to 1.33, stormkeeper CAST_FINISH occurred at 1.33.
    
    Handling stormkeeper at 624338.30 (CAST_FINISH).
    false unknown unknown true
    Trying to remove stormkeeper CAST_FINISH from queue.
    Removing 1 from queue.
    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    
    Time spent on event #1: 0.24ms...
    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Elemental - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   earth_elemental ( precombat - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.04ms
        TimeData:Elemental-precombat-1:earth_elemental:0.04
        
        2.   stormkeeper ( precombat - 2 )
        The action is not ready ( 60.00 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.03ms
        TimeData:Elemental-precombat-2:stormkeeper:0.03
        
        3.   elemental_blast ( precombat - 3 )
        The action (elemental_blast) is usable at (1.33 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria PASSES: talent.elemental_blast.enabled[true]
        Action chosen:  elemental_blast at 0.00!
    
    Completed precombat action list [ Elemental - precombat ].
    Recommendation is elemental_blast at 1.33 + 0.00.
    Recommendation #2 is elemental_blast at 0.00s (1.33s).
    Queueing elemental_blast cast finish at 624340.07 [+3.10] on unknown.
    Queued elemental_blast from 624338.30 to 624340.07 (CAST_FINISH).
    Used 1.63ms of CPU on 2 prediction(s).

RECOMMENDATION #3 ( Offset: 1.33, GCD: 1.33, Casting: 1.77 ).

    There are 1 queued events to review.
    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    
    Finishing queued event #1 ( CAST_FINISH of elemental_blast ) due at 1.77 as player is casting and castable spells are not ready.
    Casting: Yes, Channeling: No, Break: No, Check: No
    While advancing by 1.77 to 3.10, elemental_blast CAST_FINISH occurred at 3.10.
    
    Handling elemental_blast at 624340.07 (CAST_FINISH).
    false unknown unknown true
    Trying to remove elemental_blast CAST_FINISH from queue.
    Removing 1 from queue.
    Resources: maelstrom[ 30.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    
    Time spent on event #1: 0.31ms...
    Resources: maelstrom[ 30.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Elemental - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   earth_elemental ( precombat - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Elemental-precombat-1:earth_elemental:0.02
        
        2.   stormkeeper ( precombat - 2 )
        The action is not ready ( 58.23 ) before our maximum delay window ( 15.00 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Elemental-precombat-2:stormkeeper:0.02
        
        3.   elemental_blast ( precombat - 3 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.02ms
        TimeData:Elemental-precombat-3:elemental_blast:0.02
        
        4.   lava_burst ( precombat - 4 )
        We are already in-combat and this pre-combat action is not essential.  Skipping.
        Time spent on this action:  0.02ms
        TimeData:Elemental-precombat-4:lava_burst:0.02
        
        5.   potion ( precombat - 5 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Elemental-precombat-5:potion:0.02
    
    Completed precombat action list [ Elemental - precombat ].
    
    Processing default action list [ Elemental - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        6.   wind_shear ( default - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.03ms
        TimeData:Elemental-default-1:wind_shear:0.03
        
        7.   spiritwalkers_grace ( default - 2 ) - ability disabled ( toggle )
        Time spent on this action:  0.03ms
        TimeData:Elemental-default-2:spiritwalkers_grace:0.03
        
        8.   bloodlust ( default - 3 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Elemental-default-3:bloodlust:0.02
        
        9.   potion ( default - 4 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Elemental-default-4:potion:0.02
        
        10.  fire_elemental ( default - 5 )
        The action (fire_elemental) is usable at (3.10 + 0.00) with cost of 500 mana.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  fire_elemental at 0.00!
    
    Completed default action list [ Elemental - default ].
    Recommendation is fire_elemental at 3.10 + 0.00.
    Recommendation #3 is fire_elemental at 0.00s (3.10s).
    Time spent generating recommendations:  2.79ms

**Comment by Hekili** [comment]
That is not the default priority; you are missing an entry for "Use Items" between potion and fire_elemental in your default action list.
