### ISSUE TITLE
Frost Mage suggestions fall through to blink/shimmer

### ISSUE THREAD

**Issue by brucek2** [Hekili/hekili#894]
Prep:
. Hekili is current as of submission
. No similar open or closed issue found

Summary:
My frost mage often sees the 3 suggestions as:
(ICE LANCE) (SHIMMER) (SHIMMER)

When I suspect they should be
(ICE LANCE) (ICE LANCE) (ICE LANCE)  # Other combinations for #2 and #3 possible.

To Reproduce:
Engage a target dummy. After using cooldowns and gaining procs, you will quickly see the issue described. The issue occurs frequently in normal play (for me, often Mythic Plus.)

Commentary:
1. The bug is seeing shimmer x2 so often, not not seeing a specific other suggestion.
2. I suspect this is because Shimmer is the only available option off the GCD (can't prove that.)
3. I believe I started seeing this 2-3 weeks ago and not before.
4. Shimmer never makes it to the first position.

Snapshot:
https://pastebin.com/4z8VyXSp

**Comment by Hekili** [comment]
> I suspect this is because Shimmer is the only available option off the GCD (can't prove that.)

Yeah, that looks like the issue.  It's the only spell you'd really be able to cast between GCDs.  I'll adjust it.

**Comment by Hekili** [comment]
Incoming fix.
