### ISSUE TITLE
Vanish + Master Assassin + Killing Spree

### ISSUE THREAD

**Issue by endisnear1010** [Hekili/hekili#896]
**BEFORE SUBMITTING AN ISSUE:**

1. I am using the latest version of hekili

So apparently there was an issue with simming Killing Spree with master assassin putting it below bladerush, with this fixed killing spree is the way to go in m+ now when used properly with master assassin hence vanish. Hekili wants to use Killing Spree when vanish has 2 seconds cooldown left, and also sometimes wants to use it before vanish even when both are up. Ill provide snapshots for both issues.

**To Reproduce**
just hit a target dummy

**Expected behavior**
I think using Killing Spree outside of master assassin has no value, especially not when vanish is close to comming of cooldown or isnt on cooldown at all. So i expect hekili to pair these two, to use Killing Spree with atleast 2 Seconds of Master Assassin left ( Which is Killing Spree's cast time)
 
**PUT SNAPSHOT LINK HERE:**
Hekili trying to use Killing Spree when vanish is close to comming of CD : https://pastebin.com/cb6S2AhK
Hekili trying to use Killing Spree when vanish is up                                   : https://pastebin.com/M41jyAmf

**Comment by Hekili** [comment]
This behavior is consistent with the sim.  I've done some additional sim testing and the opportunity cost of holding Killing Spree for Vanish seems to neutralize any gains from blending them together.

There are probably burst scenarios where you'd really want to carefully sync them up, but I'm not seeing that pan out in any of my test sims.  (I basically left all other conditions as-is and made it so Killing Spree isn't usable unless Vanish is on CD and won't be off CD for 10+ seconds.)

1 boss Patchwerk:
![image](https://user-images.githubusercontent.com/9438134/107446336-36512800-6b0c-11eb-828e-965dc5f1d55b.png)

3 boss Patchwerk:
![image](https://user-images.githubusercontent.com/9438134/107446359-46690780-6b0c-11eb-9bfd-dfe7b91ff037.png)

Hectic Add Cleave (note this benefit is really small with significantly higher variance):
![image](https://user-images.githubusercontent.com/9438134/107446398-5a146e00-6b0c-11eb-8f57-e2a105eff10b.png)

DungeonSlice (higher average but lower top end):
![image](https://user-images.githubusercontent.com/9438134/107446434-6ef10180-6b0c-11eb-9c28-0c8e299b21ec.png)

If you're aware of sim-tested profiles that demonstrate a clearer benefit, please provide them and I'll do additional testing.
