### ISSUE TITLE
Affliction Warlock AOE recommendation

### ISSUE THREAD

**Issue by MrSmurfy** [Hekili/hekili#898]
**Describe the Bug/Issue**
I play affliction warlock using Hekili with fixed dual display enabled.
Whilst idle and not in combat the AOE display recommends using Seed of Corruption twice in a row. 
Any idea if that is intentional?  

**Expected behavior**
A single cast of Seed of Corruption being recommended.

**Screenshots**
https://i.imgur.com/Wm4Ukh1.png

Issue Report:
https://pastebin.com/YGqbPcyj

Snapshot: 
https://pastebin.com/ynSnc4bG

**Comment by Hekili** [comment]
The issue here is just that Seed of Corruption has a travel time, so the "precombat" list logic still passes when you initiate a fight.

```6.   seed_of_corruption ( precombat - 6 )
The action (seed_of_corruption) is usable at (0.00 + 0.00) with cost of 1 soul_shards.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
 - this entry's criteria PASSES: spell_targets.seed_of_corruption_aoe[3.00] >= 3 & ! equipped.azsharas_font_of_power[false]
Action chosen:  seed_of_corruption at 0.00!
```

Once Seed actually hits the enemy and combat starts, the second recommendation would go away.  But it is misleading.  I'll adjust it.

**Comment by Hekili** [comment]
Incoming fix.
