### ISSUE TITLE
Unholy casts Sacrificial Pact while Dark Transformation is active

### ISSUE THREAD

**Issue by nzall** [Hekili/hekili#899]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
When I'm Unholy and cast Dark Transformation, a couple seconds later usually Sacrificial Pact is recommended, even though there's an explicit check to not do that. It appears to be checking player buffs, not pet buffs.

**To Reproduce**
Be an Unholy DK at a level where you have both Sacrificial Pact and Dark Transformation and just follow the APL.

**Expected behavior**
It shouldn't recommend Sacrificial Pact during Dark Transformation.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/KABFQREL

**Comment by Hekili** [comment]
> When I'm Unholy and cast Dark Transformation, a couple seconds later usually Sacrificial Pact is recommended, even though there's an explicit check to not do that. It appears to be checking player buffs, not pet buffs.

No, the issue is that the Sacrificial Pact recommendation is recommended based on the fight being almost over (so it doesn't care that nuking your pet as Unholy is just a bad plan outside of a boss encounter).

> - this entry's criteria PASSES: active_enemies[2.00] >= 2 & ! buff.dark_transformation.up[true] & ! cooldown.dark_transformation.ready[false] | fight_remains[1.00] < gcd.execute[1.41]

I'll make adjustments.

**Comment by nzall** [comment]
I'm not even sure how important it is to make that adjustment. The current APL for Unholy from Simcraft does not use Sacrificial pact, not even at the end of the fight, so by the time you make a new release to include this bug and also update the APLs, this bug is probably going to be moot.

> > When I'm Unholy and cast Dark Transformation, a couple seconds later usually Sacrificial Pact is recommended, even though there's an explicit check to not do that. It appears to be checking player buffs, not pet buffs.
> 
> No, the issue is that the Sacrificial Pact recommendation is recommended based on the fight being almost over (so it doesn't care that nuking your pet as Unholy is just a bad plan outside of a boss encounter).
> 
> > * this entry's criteria PASSES: active_enemies[2.00] >= 2 & ! buff.dark_transformation.up[true] & ! cooldown.dark_transformation.ready[false] | fight_remains[1.00] < gcd.execute[1.41]
> 
> I'll make adjustments.

**Comment by Hekili** [comment]
> The current APL for Unholy from Simcraft does not use Sacrificial pact

Of course it does.  Where did you think the entry came from?

https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier26/T26_Death_Knight_Unholy.simc#L98

![image](https://user-images.githubusercontent.com/9438134/107158611-52f92e80-6959-11eb-842c-015eb76f8e1b.png)

As I noted, it doesn't really function really well outside the context of a simmed boss fight, because of the downsides of murdering your pet.  So I'll make adjustments.

**Comment by nzall** [comment]
Sorry, I was dumb and looking at T25 APLs, not T26.

**Comment by Hekili** [comment]
Incoming fix.
