### ISSUE TITLE
Please add Throw Glaive DH Havoc to the rotation

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#90]
Good afternoon, please make it in the rotation of Throw Glaive. Why am I asking this? It is convenient when you are far away from the target, and you can throw a blade during the battle, so to speak, without losing DPS, and when taking talent for 2 blades, it is not so bad to kite mobs in mythyc +. Just there is such a condition "if you’ve been talented into a global or global cooldown or if you’ve been able. And I would like you to add it. Thank you.

**Comment by Hekili** [comment]
This is a bit of a judgment call that comes up fairly often.  For melee specs that are out of range, the best DPS recommendation is to get in range so you can keep melee'ing.  If you can't (i.e., you're kiting like you mentioned), then sure, it's a good idea to use your (limited) ranged abilities, but at some point it's better to get back in range.

If/when I can link this to a personal preference, I'll consider the change.  Leaving this open for further consideration/comments.

**Comment by geraint425** [comment]
Why do I propose to use the blade at a distance? Because you could have noticed and correctly emphasized that even when I am engaged in kiting, this is very convenient, since I minimize the loss in DPS. You can see how implemented by your colleagues HerroRotations. Of course, there are mistakes there, but this functionality works as it should. Take a look please how it is implemented from HerroRotation. P.S. With the new version of your addon, Vengence has stopped showing demonic spikes in rotation. Look here please.

**Comment by Hekili** [comment]
The Demonic Spikes part should be fixed in 8.1.5-07.

I'm still considering the Throw Glaive piece, but like I said, I want that to be something you can turn on/off easily.
