### ISSUE TITLE
My Enhancement Shaman only shows Windfury Weapon

### ISSUE THREAD

**Issue by Shamancement** [Hekili/hekili#902]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
It onlly shows Windfury Weapon
**To Reproduce**
Ran a simulation using Simulationcraft and Simc Addon. Loaded profile into enhancement priorities. It only shows Windfury Weapon.

**Expected behavior**
A rotation for my specific build. It worked in the past then I got some gear and trinkets and now nothing but Windfury
**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.build: v9.0.2-1.0.39
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ascendance
    elemental_assault
    forceful_winds
    natures_guardian
    spirit_wolf
    stormflurry
    sundering

pvptalents: none

covenant: night_fae

conduits: crippling_hex = 6
   refreshing_waters = 6
   unruly_winds = 5
   vital_accretion = 6

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   niyas_tools_burrs = 1
   run_without_tiring = 1

sets: none

gear: boneshatter_helm = 1
    castellans_chainlink_grips = 1
    charm_of_eternal_winter = 1
    crest_of_the_legionnaire_general = 1
    forsworn_stalkers_hauberk = 1
    legionnaires_bloodstained_sabatons = 1
    loadbearing_belt = 1
    macabre_sheet_music = 1
    mantle_of_ephemeral_visages = 1
    mementoladen_cuisses = 1
    overcharged_anima_battery = 1
    precious_ribbon = 1
    ritualists_treasured_ring = 1
    shackles_of_alluring_vitality = 1
    stone_generals_edge = 1
    stonesnap_mandibles = 1
    twisted_witherroot_band = 1

legendaries: doom_winds = 1

itemIDs: 172325, 178821, 178846, 178857, 179577, 180100, 180116, 182985, 182990, 183014, 183016, 183032, 183037, 183040, 184024, 184142, 52019

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false
![WoWScrnShot_122720_224846](https://user-images.githubusercontent.com/78679301/107442297-1877c900-6af4-11eb-82d1-ae9e6fe56fe4.jpg)
![WoWScrnShot_122720_224846](https://user-images.githubusercontent.com/78679301/107442326-288fa880-6af4-11eb-9aa4-6e527be66302.jpg)
![WoWScrnShot_020921_163225](https://user-images.githubusercontent.com/78679301/107442505-6b518080-6af4-11eb-80fb-8ce1fbf9450c.jpg)

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Snapshot?

**Comment by Shamancement** [comment]
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.39
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ascendance
    elemental_assault
    forceful_winds
    natures_guardian
    spirit_wolf
    stormflurry
    sundering

pvptalents: none

covenant: night_fae

conduits: crippling_hex = 6
   refreshing_waters = 6
   unruly_winds = 5
   vital_accretion = 6

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   niyas_tools_burrs = 1
   run_without_tiring = 1

sets: none

gear: boneshatter_helm = 1
    castellans_chainlink_grips = 1
    charm_of_eternal_winter = 1
    crest_of_the_legionnaire_general = 1
    forsworn_stalkers_hauberk = 1
    legionnaires_bloodstained_sabatons = 1
    loadbearing_belt = 1
    macabre_sheet_music = 1
    mantle_of_ephemeral_visages = 1
    mementoladen_cuisses = 1
    overcharged_anima_battery = 1
    precious_ribbon = 1
    ritualists_treasured_ring = 1
    shackles_of_alluring_vitality = 1
    stone_generals_edge = 1
    stonesnap_mandibles = 1
    twisted_witherroot_band = 1

legendaries: doom_winds = 1

itemIDs: 172325, 178821, 178846, 178857, 179577, 180100, 180116, 182985, 182990, 183014, 183016, 183032, 183037, 183040, 184024, 184142, 52019

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false


player_buffs:
   192106 - lightning_shield                         -   1 - 1694.61
    72968 - preciouss_ribbon                         -   1 - 3600.00
   186406 - sign_of_the_critter                      -   1 - 3600.00

player_debuffs:

target_auras:  target does not exist


build: v9.0.2-1.0.39
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ascendance
    elemental_assault
    forceful_winds
    natures_guardian
    spirit_wolf
    stormflurry
    sundering

pvptalents: none

covenant: night_fae

conduits: crippling_hex = 6
   refreshing_waters = 6
   unruly_winds = 5
   vital_accretion = 6

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   niyas_tools_burrs = 1
   run_without_tiring = 1

sets: none

gear: boneshatter_helm = 1
    castellans_chainlink_grips = 1
    charm_of_eternal_winter = 1
    crest_of_the_legionnaire_general = 1
    forsworn_stalkers_hauberk = 1
    legionnaires_bloodstained_sabatons = 1
    loadbearing_belt = 1
    macabre_sheet_music = 1
    mantle_of_ephemeral_visages = 1
    mementoladen_cuisses = 1
    overcharged_anima_battery = 1
    precious_ribbon = 1
    ritualists_treasured_ring = 1
    shackles_of_alluring_vitality = 1
    stone_generals_edge = 1
    stonesnap_mandibles = 1
    twisted_witherroot_band = 1

legendaries: doom_winds = 1

itemIDs: 172325, 178821, 178846, 178857, 179577, 180100, 180116, 182985, 182990, 183014, 183016, 183032, 183037, 183040, 184024, 184142, 52019

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false


player_buffs:
   192106 - lightning_shield                         -   1 - 1768.29
    72968 - preciouss_ribbon                         -   1 - 3600.00
   186406 - sign_of_the_critter                      -   1 - 3600.00

player_debuffs:

target_auras:  target does not exist


New Recommendations for [ Primary ] requested at 16:55:07 ( 1034654.77 ); using built-in ( Enhancement ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Enhancement - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        1.   windfury_weapon ( precombat - 4 )
        The action (windfury_weapon) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  windfury_weapon at 0.00!
    
    Completed precombat action list [ Enhancement - precombat ].
    Recommendation is windfury_weapon at 0.00 + 0.00.
    Recommendation #1 is windfury_weapon at 0.00s (0.00s).
    Used 0.28ms of CPU on 1 prediction(s).

RECOMMENDATION #2 ( Offset: 0.00, GCD: 1.25, Casting: 0.00 ).

    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Enhancement - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        1.   windfury_weapon ( precombat - 4 )
        The action (windfury_weapon) is usable at (0.00 + 1.25).
         - the action is ready before the current recommendation (at +1.25 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  windfury_weapon at 1.25!
        Time spent on this action:  0.07ms
        TimeData:Enhancement-precombat-4:windfury_weapon:0.07:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Recheck:0.00:Post Recheck:0.00:Action Stored:0.02
        The recommended action (windfury_weapon) is ready within the active GCD; exiting list (precombat).
    
    Completed precombat action list [ Enhancement - precombat ].
    
    Processing default action list [ Enhancement - default ].
        
        Current recommendation was windfury_weapon at +1.25s.
        The recommended action (windfury_weapon) is ready within the active GCD; exiting list (default).
    
    Completed default action list [ Enhancement - default ].
    Recommendation is windfury_weapon at 0.00 + 1.25.
    Recommendation #2 is windfury_weapon at 1.25s (1.25s).
    Used 0.57ms of CPU on 2 prediction(s).

RECOMMENDATION #3 ( Offset: 1.25, GCD: 1.25, Casting: 0.00 ).

    Resources: maelstrom[ 0.00 / 100.00 ], mana[ 10000.00 / 10000.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Enhancement - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        Entry #1 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #2 in list ( precombat ) is not set or not enabled.  Skipping.
        
        Entry #3 in list ( precombat ) is not set or not enabled.  Skipping.
        
        1.   windfury_weapon ( precombat - 4 )
        The action (windfury_weapon) is usable at (1.25 + 1.25).
         - the action is ready before the current recommendation (at +1.25 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  windfury_weapon at 1.25!
        Time spent on this action:  0.07ms
        TimeData:Enhancement-precombat-4:windfury_weapon:0.07:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Recheck:0.00:Post Recheck:0.00:Action Stored:0.02
        The recommended action (windfury_weapon) is ready within the active GCD; exiting list (precombat).
    
    Completed precombat action list [ Enhancement - precombat ].
    
    Processing default action list [ Enhancement - default ].
        
        Current recommendation was windfury_weapon at +1.25s.
        The recommended action (windfury_weapon) is ready within the active GCD; exiting list (default).
    
    Completed default action list [ Enhancement - default ].
    Recommendation is windfury_weapon at 1.25 + 1.25.

**Comment by Hekili** [comment]
That's not the default priority.  I'm guessing you've imported from SimC.  There's no need to do that.  You'll want to revert to the built-in/default.
