### ISSUE TITLE
Lack of smoothie in Unholy Rotation

### ISSUE THREAD

**Issue by Nazeth** [Hekili/hekili#905]
I don't want tag it as a bug, because i still didn't look at rotation scripts and still im at 53 lvl, but after first hours i've see huge issues with smooth of rotation. After soo long time you should notice, that SimC scripts aren't very practical in use. They are good base, but not good final material to use it in that addon.

Soul Reaper jumping and dissapear from rotation. Technically it should be used under 35% of enemy HP and above it, if debuff will drop in time. Sadly even if im fighting with weak trash, then rotation suggest me to use it once per half or one minute, but still i can kill trash with more than 5 sec.

AoE rotation looks very chaotic and jumping like a hell, what makes it hard to prepare next skill. Outbreak is often avoided. Death and Decay is often avoided. Death Coil without Sudden Doom jumping before Epidemic. After use of Death and Decay i have chain of Epidepic skills instead of Scourge Strikes (Its waste of AoE dps).

Probably scripts aren't enough optimized and also per next weeks i haven't time to look into it.

I miss some defensive cooldowns like Death Strike or Death Pact. I mostly need to implement them myself. There are other skills that also can be implemented. I feel, that im even more squishy now, so i care more about my self-heal skills.

**Comment by Hekili** [comment]
Thanks. Please follow instructions when submitting tickets. Take care.
