### ISSUE TITLE
Keybinds do not show modifiers

### ISSUE THREAD

**Issue by Industrial** [Hekili/hekili#906]
**Describe the Bug/Issue**
Keybinds do not show modifiers.

**To Reproduce**
Use Hekili with Bongos.

**Expected behavior**
Keybinds to show S for Shift, A for Alt and C for Control

**Screenshots**
![Screenshot](https://i.imgur.com/aEcoqlo.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.
build: v9.0.2-1.0.38
level: 56 (56)
class: SHAMAN
spec: enhancement

talents: elemental_spirits
    feral_lunge
    hailstorm
    lashing_flames
    spirit_wolf
    stormflurry
    sundering

pvptalents: ride_the_lightning
   swelling_waves
   thundercharge

covenant: kyrian

conduits: none

soulbinds: []

sets: none

gear: band_of_chronicled_deeds = 1
    bonefused_crusher = 1
    brand_of_the_banshee_queen = 1
    favored_fanatics_gauntlets = 1
    flesh_architects_belt = 1
    flesh_architects_chainmail = 1
    flesh_architects_galoshes = 1
    flesh_architects_leggings = 1
    flesh_architects_wristwraps = 1
    guidenote_grip = 1
    humble_aspirants_helm = 1
    reconstructed_family_locket = 1
    salvaged_mercenarys_drape = 1
    signet_of_the_learned = 1
    vial_of_caustic_liquid = 1
    waylight_shoulderguards = 1

legendaries: none

itemIDs: 129104, 173330, 173339, 173344, 175449, 175458, 175464, 175472, 175476, 175518, 175707, 175708, 175722, 175763, 176336, 180819

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    pad_windstrike = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
If your bars and bindings are organized in a non-standard way, the assumptions made in the keybinding detection will be wrong. 

You can manually set the bindings for each ability or you can reorganize your bars. I would recommend setting the bindings via /hek > Abilities, select the ability, Override Keybind Text.

**Comment by Industrial** [comment]
Thanks!
