### ISSUE TITLE
Fury Warrior with Signet recommending Recklessness on pull

### ISSUE THREAD

**Issue by johngallo0892** [Hekili/hekili#907]
Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.39
level: 60 (60)
class: WARRIOR
spec: fury

talents: anger_management
    bladestorm
    cruelty
    massacre
    storm_bolt
    sudden_death
    warpaint

pvptalents: none

covenant: venthyr

conduits: ashen_juggernaut = 5
   inspiring_presence = 6
   safeguard = 5
   stalwart_guardian = 5

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   dauntless_duelist = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: binding_of_warped_desires = 1
    dread_sentinels_ebony_grips = 1
    drustlords_greataxe = 1
    hellhound_cuffs = 1
    illustrious_guild_tabard = 1
    ritualists_treasured_ring = 1
    shadowghast_ring = 1
    sinful_gladiators_crusaderblade = 1
    sinful_gladiators_drape = 1
    sinful_gladiators_insignia_of_alacrity = 1
    sinful_gladiators_pendant = 1
    sinful_gladiators_plate_chestguard = 1
    sinful_gladiators_plate_helm = 1
    sinful_gladiators_plate_shoulders = 1
    sinful_gladiators_plate_wargreaves = 1
    skulkers_wing = 1
    stoneguard_attendants_boots = 1

legendaries: signet_of_tormented_kings = 1

itemIDs: 175887, 175890, 175909, 178353, 178369, 178386, 178387, 178713, 178926, 180910, 182402, 182983, 183015, 183018, 183037, 184016, 69209

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potion = potion_of_phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_ww_range = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

player_buffs:
     6673 - battle_shout                             -   1 - 3440.19
    97340 - *Guild Champion                          -   1 - 3600.00
   186406 - *Sign of the Critter                     -   1 - 3600.00
    21562 - *Power Word: Fortitude                   -   1 - 3471.05
   166646 - *Windwalking                             -   1 - 4.64

player_debuffs:

target_buffs:

target_debuffs:

New Recommendations for [ Cooldowns ] requested at 10:31:41 ( 244733.33 ); using built-in ( Fury ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: rage[ 0.00 / 100.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Fury - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   battle_shout ( precombat - 1 ) - ability disabled ( display )
        Time spent on this action:  0.01ms
        TimeData:Fury-precombat-1:battle_shout:0.01
        
        2.   recklessness ( precombat - 2 )
        The action (recklessness) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry has no criteria to test.
        Action chosen:  recklessness at 0.00!
    
    Completed precombat action list [ Fury - precombat ].
    Recommendation is recklessness at 0.00 + 0.00.
    Recommendation #1 is recklessness at 0.00s (0.00s).
    Time spent generating recommendations:  0.22ms

**Comment by Hekili** [comment]
Thanks, I overlooked an edit.  You can workaround this by going to /hekili > Priorities > Fury > Actions, precombat, entry 2 and unchecking Enabled.

**Comment by Hekili** [comment]
Should be resolved in 1.0.40.
