### ISSUE TITLE
#taco-dog-fanclub Discord channel

### ISSUE THREAD

**Issue by Thordros** [Hekili/hekili#908]
_Please describe your idea or feature and when it would be useful._

Add a channel to Discord where you post pictures of the taco dog. She is a sweetie and we love her. You should make it a Patron only benefit and advertise it heavily.

**Comment by Rebdull** [comment]
Please send dog.

**Comment by MrSmurfy** [comment]
Dog or riot.

**Comment by Thordros** [comment]
This is the content we are being denied.

![image](https://user-images.githubusercontent.com/22895308/107856672-eeb9ed00-6de6-11eb-860e-93be8f81f123.png)

**Comment by Hekili** [comment]
Toofs.

**Comment by Thordros** [comment]
Pleeeeeaaaaaseeee

![image](https://user-images.githubusercontent.com/22895308/107859467-d3ef7480-6df6-11eb-964c-db4503877a6c.png)

**Comment by Hekili** [comment]
No.

*(Maybe.)*
