### ISSUE TITLE
Lua errors on Fire Mage

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#909]
Updated to the latest version of Hekili v9.0.2-1.0.40

Basically getting two lua errors that are spammed when playing Fire mage. Only seems to happen during combustion and lust. This was tested on a dummy. I dont know what else to say apart from this wasn't happening in previous updates only this latest one. I tried to read the error to understand it more to report more but no idea what it's saying but I believe it has something to do with hot streak in flight

Follow the rotation to Fire Mage during combustion and lust and the lua pops up on the screen

https://pastebin.com/Lep9sA94 -  my issue report

I've put the error messages in a pastebin instead of just copying it here.

https://pastebin.com/t6q40hgC - 1/2
https://pastebin.com/4dh3NsYe - 2/2

**Comment by Hekili** [comment]
Resolved.
