### ISSUE TITLE
Keybinds visual missing

### ISSUE THREAD

**Issue by ishist** [Hekili/hekili#91]
There are no keybind indicators on buttons on one of my characters. My other characters are working as expected. The keybinds settings can be changed but nothing appears regardless.

**Comment by Hekili** [comment]
Please submit a complete and proper ticket.

**Comment by Hekili** [comment]
Also, do you use separate profiles per character?
Can you send your Hekili.lua file from your SavedVariables?

**Comment by ishist** [comment]
Yes, I tried using a separate profile and also switching to a profile I knew worked properly. I also tried defaulting the profile. Sorry, I'm a bit Github illiterate. 
[Hekili.zip](https://github.com/Hekili/hekili/files/3014738/Hekili.zip)

**Comment by Hekili** [comment]
Wrong Hekili.lua file -- I need the one from your SavedVariables, not from the addon itself.  :)

**Comment by ishist** [comment]
Ok.
[Hekili.zip](https://github.com/Hekili/hekili/files/3031625/Hekili.zip)

**Comment by Hekili** [comment]
And which profile(s) or characters were not displaying keybindings?

**Comment by ishist** [comment]
"Bahdmon" is the only one that's having the problem so far.

**Comment by Hekili** [comment]
Just wanted to confirm, I've tried using your profile and the keybinds appear without issue.

Is it possible that you need to revisit the font-size or the icon-size for your keybinds/displays?  Please try 8.0.1-beta2 and see if your issue persists.  If so, submit a new ticket.  Try adjusting your keybinding font size down or increasing the size of your icons -- if there's not enough room for the text, it may be replaced with "..."

**Comment by ishist** [comment]
I've tried various combinations to get it to display. Even after returning the profile to default or switching to my other characters profiles there were no keybinds showing. I haven't had this happen on any other character. I just switched to using Herorotation for this character.
