### ISSUE TITLE
setting Toggles for each character

### ISSUE THREAD

**Issue by CosmicRider60** [Hekili/hekili#910]
Not sure if this is a bug , feature request or missing something in Hekili.

I play two different characters (boomkin and ww monk). For each character I want Toggles set to different values. I have yet to see a way to accomplish this

**Comment by Hekili** [comment]
You can set up multiple profiles via /hekili > Profiles, that will give them their own toggles.

If you copy settings from your existing profile, the displays and other settings will come over from the original profile.
