### ISSUE TITLE
Hekili.DB.profile.packs[pack].warnings is nil on a brand new action list

### ISSUE THREAD

**Issue by KOVIKO** [Hekili/hekili#913]
[Options.lua:5856](https://github.com/Hekili/hekili/blob/b42348aa9211864f32fed72f316c89dc67bedfe7/Options.lua#L5856) throws an error when creating a new priority list and attempting to navigate to the "Profile" tab. Replacing nil with an empty string seems to solve the issue.

```diff
- return "|cFFFFD100Import Log|r\n" .. ( p.warnings ) .. "\n\n"
+ return "|cFFFFD100Import Log|r\n" .. ( p.warnings or "" ) .. "\n\n"
```

**Comment by Hekili** [comment]
This is resolved.
