### ISSUE TITLE
Fire mage - FPS drops when using Hekili as fire mage

### ISSUE THREAD

**Issue by LupeHD** [Hekili/hekili#914]
**1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.**

Yes, latest version

**2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.**
 I saw a LUA error bug report for fire mage, but don't know if it's the same. Excuse me if it is.

**Describe the Bug/Issue**
When playing as a fire mage with the Hekili add-on, I get extreme FPS drops. 
To the point where I had to switch to frost, because it's not playable.
EDIT: When disabling the add-on or switching specs, the issues also go away.

This morning on Reddit, there was at least 1 other person with exactly the same problem.
I also believe it's fairly recent, as I have played fire mage with Hekili earlier on, without problems. (Like 1 Month ago).

**To Reproduce**
Enter combat/ cast spells as a fire mage while using the Hekili add-on. 

**Expected behavior**
No fps drops

**Screenshots**
/

**WHEN SUBMITTING AN ISSUE:**

1.  Issue reporting pastebin:

**https://pastebin.com/35HesfDy**

**Comment by Hekili** [comment]
Fire is the most CPU intensive by far based on the class design and its priority.  If there's an opportunity to optimize it further, I'll do so, but there's not a specific error here.

**Comment by LupeHD** [comment]
Okay, thank you for your response.
Just thought I should report it, because a month ago it wasn't happening. 

thanks for your time!

**Comment by Hekili** [comment]
I'll do a recheck, sometimes there's new forking the priority that I can simplify, but I don't recall seeing anything new in that regard.

**Comment by LupeHD** [comment]
Okay, thank you !

**Comment by Cruup** [comment]
Hello!

Just wanted to report that I am experiencing the same issue as OP. Willing to provide any data you might need to sort it.

Keep up the good work!
