### ISSUE TITLE
Duplicate spell id in PaladinRetribution.lua file is causing the_magistrates_judgment check to fail.

### ISSUE THREAD

**Issue by Morshed11218** [Hekili/hekili#915]
Hi, 
In PaladinRetribution.lua file, you have two spells 'the_magistrates_judgment' & 'the_arbiters_judgment' with the same spell id (337682). Spell Id 337682 is correct for the_magistrates_judgment. Not certain about the other spell. This is causing the the_magistrates_judgment aura check to fail. Tested and verified on my end. 

![image](https://user-images.githubusercontent.com/2136499/108167843-53659800-70c4-11eb-8630-cd3964b7d1e0.png)

**Comment by Hekili** [comment]
Good catch, will resolve.

**Comment by Hekili** [comment]
This is fixed for 9.0.5.
