### ISSUE TITLE
Windwalker Monk defensives

### ISSUE THREAD

**Issue by mrgianlu** [Hekili/hekili#917]
Hi, in WW monk neither Fortifying Brew nor Fleshcraft (necrolord covenant) are shown even though the defensives are checked. Just a small suggestion for improvement.

**Comment by Hekili** [comment]
Please refer to the FAQ.  Defensives are not built in by default for DPS specializations.  You can modify your own priority to include them by referencing the FAQ.

**Comment by mrgianlu** [comment]
makes sense, thanks :)
