### ISSUE TITLE
[Outlaw Rogue] Do not suggest vanish unless Killing Spree is up

### ISSUE THREAD

**Issue by iamkevindu** [Hekili/hekili#918]
Hello. Now that Master Assassin legendary + Killing Spree is becoming popular and meta, I would like to suggest to ask Hekili not to suggest Vanish unless Killing Spree is available. This is important because Vanish will grant Master Assassin buff and you would want to use ambush right out of vanish (for Count The Odd conduit) followed by KS and then a finisher. This is the way MA + KS should be played for maximum DPS. Also, please suggest having Blade Flurry up before doing all this since it amplifies KS damage.

I would also like to suggest Hekili not to have SnD in spell queue right after coming out of stealth with Master Assassin buff. The MA buff is a 4 second window and you only want to use damaging abilities to get the most use out of the 100% crit.

I'd suggest adding a toggle button for it under "Outlaw" when clicking Hekili since some people would not want this if they're not playing MA.

**Comment by Hekili** [comment]
I think this is rolled into default APL changes, but if not, report/reopen with a snapshot after 9.0.5 is live.
