### ISSUE TITLE
Recklessness shows in queue but is never recommended

### ISSUE THREAD

**Issue by nate8282** [Hekili/hekili#919]
**Recklessness is no longer suggested on the first icon**
Not sure what I did. Recklessness shows on the second and the third icon as if it's in queue, but never actually shows on the first icon to the left.

**To Reproduce**
1. Enable CDs.
2. Attack a dummy using the recommended skills from the first icon.
3. Notice Recklessness shows in previous icons in queue, but never shows as the first icon.
(This may be just me, and may not be reproducable)

**Expected behavior**
Recklessness should show on the first icon to the left when cooldowns are enabled.

**Screenshots**
![2021-02-17_21-41-05](https://user-images.githubusercontent.com/52011990/108306334-27502280-7169-11eb-8a06-094aaf06ed79.gif)

**What I've Tried**
So far I've deleted and re-installed to the newest release, reset my profile and it still does it. I have Cooldowns enabled and my other CDs work. I'm assuming I did something to break it but I'm not sure.

**Info**
build: v9.0.2-1.0.40a
level: 60 (60)
class: WARRIOR
spec: fury

talents: bladestorm
    cruelty
    double_time
    massacre
    siegebreaker
    sudden_death
    warpaint

pvptalents: none

covenant: venthyr

conduits: ashen_juggernaut = 5
   inspiring_presence = 6
   safeguard = 6
   stalwart_guardian = 6

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   dauntless_duelist = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: anima_field_emitter = 1
    breastplate_of_cautious_calculation = 1
    charm_of_eternal_winter = 1
    decadent_nathrian_shawl = 1
    dessias_decimating_decapitator = 1
    epaulettes_of_overwhelming_force = 1
    fallen_templars_gauntlets = 1
    fleshfused_circle = 1
    girdle_of_the_soulflayer = 1
    legplates_of_unholy_frenzy = 1
    phial_of_putrefaction = 1
    shadowghast_ring = 1
    soldiers_stoneband_wristguards = 1
    stoneguard_attendants_boots = 1
    wrathbark_greathelm = 1

legendaries: signet_of_tormented_kings = 1

itemIDs: 178694, 178739, 178771, 178866, 178869, 178926, 179326, 180118, 182983, 182987, 182994, 183013, 183031, 183040, 184778

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Fury
    petbased = false
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_ww_range = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by nate8282** [comment]
I just downgraded to version 9.0.2-1.0.33 and Recklessness is suggested and working again. I then updated to the current release 9.0.2-1.0.40a and it stopped working again.

**Comment by nate8282** [comment]
I just verified that this issue only exists in version 9.0.2-1.0.40a for me and I have no issues with recklessness in version 9.0.2-1.0.40.

**Comment by nate8282** [comment]
Ok something weird just happened. When I upgrade from an older version to 9.0.2-1.0.40a the recklessness issue happens. If I reset the profile, but do NOT reload then recklessness works as intended again, but if I reset the profile and then reload it stays broken. It's weird. This could just be something weird with my computer or something.

**Comment by Hekili** [comment]
The APL as-written uses Recklessness off-GCD.  So if you have your spec set to sync the addon with the GCD, you'll only see Recklessness in-queue while the GCD is active.

I'm probably going to revise it, but if you dig in your spec options, you can uncheck Sync with Global Cooldown (or something like that) and the recommendation will be more stable.

**Comment by nate8282** [comment]
Thank you. You can close this if you like.
