### ISSUE TITLE
Survival Hunter - Wildfire Infusion

### ISSUE THREAD

**Issue by andalina1986** [Hekili/hekili#92]
Survival Hunter
Level 100 talent: Wildfire Infusion

It has 3 different bombs that come out in random

Shrapel Bomb
Pheromone Bomb
Volatile Bomb

they don't show right on Hekili, It shows in the queue but they do not SpellFlash....Sometimes it shows a differetn bomb instead of what is on

**Comment by Hekili** [comment]
Please submit a complete and proper ticket for this issue.

Note that addons cannot predict what the *next* bomb will be with Wildfire Infusion, only what the current one is.  If the addon is incorrect about the current bomb, submit a ticket with a proper snapshot when that is occurring.

I'll look into the SpellFlash bit.
