### ISSUE TITLE
Large FPS drop when only playing Fire Mage Spec

### ISSUE THREAD

**Issue by tr4549c** [Hekili/hekili#921]
**BEFORE SUBMITTING AN ISSUE:**

**Describe the Bug/Issue**
I seem to get large amounts of FPS drops when playing only the fire mage spec? all of my other classes are not effected by this. (by large fps drops i mean i go from 110 ish at normal rest, to around 30 in combat). I use hekili on many of my other chars and it works completely fine. 

**To Reproduce**
Not sure, but its just whenever you start combat as fire mage on my char.

**Expected behavior**
less fps drop?

**Screenshots**
N/A

build: v9.0.2-1.0.40a
level: 55 (55)
class: MAGE
spec: fire

talents: flame_on
    flame_patch
    frenetic_speed
    kindling
    rune_of_power
    searing_touch
    shimmer

pvptalents: none

covenant: night_fae

conduits: none

soulbinds: []

sets: none

gear: blighted_margraves_cloak = 1
    cocoonsilk_cowl = 1
    ingra_malochs_mantle = 1
    lakalis_spire_of_knowledge = 1
    mountainsage_cord = 1
    mountainsage_idol_of_destruction = 1
    mountainsage_medallion = 1
    mountainsage_stone_of_destruction = 1
    mountainsage_wristwraps = 1
    pure_aspirants_leggings = 1
    sandals_of_souls_clarity = 1
    signet_of_the_false_accuser = 1
    sparring_trainers_handwraps = 1
    stitchfleshs_misplaced_signet = 1
    waylight_vestment = 1

legendaries: none

itemIDs: 153815, 153816, 153819, 153826, 153827, 173317, 173322, 173327, 175624, 178693, 178696, 178714, 178736, 178755, 178824

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Fire
    petbased = false
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    prevent_hardcasts = false
    pyroblast_pull = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment]
Thanks for the report.  If Fire Mage gets updated and becomes more efficient, you'll see it.  If the performance impact is too significant, please don't use it.  Thanks.
