### ISSUE TITLE
Auto Generated Snapshots (Unholy DK)

### ISSUE THREAD

**Issue by ijoihlhnn** [Hekili/hekili#922]
**BEFORE SUBMITTING AN ISSUE:**

1.  using latest Stable Version "v9.0.2-1.0.39"

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Auto generated Snpahshots during Combat, mostly happens during AOE Scenarios.

happens during Combat mostly in AoE Scenarios with disabled cooldows.

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.2-1.0.39
level: 60 (60)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    army_of_the_damned
    grip_of_the_dead
    soul_reaper
    unholy_blight
    unholy_pact
    wraith_walk

pvptalents: none

covenant: necrolord

conduits: eternal_hunger = 5
   hardened_bones = 6
   reinforced_shell = 5
   spirit_drain = 6

soulbinds: [bonesmith_heirmir]
   forgeborne_reveries = 1
   heirmirs_arsenal_marrowed_gemstone = 1
   resourceful_fleshcrafting = 1
   runeforged_spurs = 1

sets: none

gear: charm_of_eternal_winter = 1
    colossal_plate_gauntlets = 1
    dessias_decimating_decapitator = 1
    dreadfire_vessel = 1
    inscrutable_quantum_device = 1
    mantle_of_manifest_sins = 1
    most_regal_signet_of_sire_denathrius = 1
    pit_fighters_wristguards = 1
    pranksters_pauldrons = 1
    rampaging_giants_chestplate = 1
    shadowghast_greaves = 1
    signet_of_the_false_accuser = 1
    stoic_guardsmans_belt = 1
    tabard_of_the_lightbringer = 1
    warboots_of_ruthless_conviction = 1
    wrathbark_greathelm = 1

legendaries: frenzied_monstrosity = 1

itemIDs: 171416, 178694, 178697, 178807, 178824, 178866, 179350, 180101, 182984, 182999, 183025, 183033, 183036, 183040, 184030, 52252

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycleDebuff = festering_wound
    cycle_min = 5
    damage = false
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = reactive
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/8mr0aJ9q
https://pastebin.com/cQGHWCvE
https://pastebin.com/J2ytTfxn
https://pastebin.com/3uYg35TN
https://pastebin.com/NdGw2pdN

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
Thanks for the report.  It looks like, because of the way the priority is written, some of the retests that would normally occur are not happening for Unholy.  That results in a lack of recommendations which results in a snapshot.  I'll enable a potential fix in the next build.

**Comment by Hekili** [comment]
These changes are in the new beta; let me know if you continue to see these snapshots (and provide new snapshots, if so!).
