### ISSUE TITLE
KNOWN ISSUE:  Fire Mage performance impact.

### ISSUE THREAD

**Issue by Hekili** [Hekili/hekili#923]
The Fire Mage priority (and spec mechanics) are far more complicated that most.  This is known and does not need to be reported.

If the performance impact is too high, and the settings in /hekili > Fire > Performance aren't sufficient, my recommendation is not to use the addon with your Fire Mage.

No further reports are necessary at this time.  Thanks.

**Comment by Myro2** [comment]
Hello. Is there a way to fix this problem? Or can't it be removed? Thank you in advance

**Comment by Hekili** [comment]
There have been recent improvements, but what you see is what you get.

**Comment by Hekili** [comment]
<details>
<summary>Ignore this, just testing markdown stuff.</summary>
Nonsense text goes here.
</details>
