### ISSUE TITLE
target.within doesnt seem to work

### ISSUE THREAD

**Issue by machajr** [Hekili/hekili#924]
9.   recklessness ( default - 9 )
        The action (recklessness) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria FAILS: target.within7[false]
        There were no recheck events to check.
        Time spent on this action:  0.08ms
        TimeData:Fury edit-default-9:recklessness:0.08:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.01:Post-Recheck Times:0.00:Post Recheck:0.00

**Comment by Hekili** [comment]
What about this makes you think it doesn't work?

`target` is your literal target, not the target of the self-buff.  If your target is outside 7 yards, false would be correct.
