### ISSUE TITLE
Shadowmeld Rogue

### ISSUE THREAD

**Issue by Narftv** [Hekili/hekili#938]
Hi, you pretty much got trolled with a request removing shadowmeld from Hekili.

While you dont get the stealthbar when you shadowmeld, you can use any ability u usually could do while in stealth. (you dont need to be out of combat at all)
You just need to simplify things with a macro like this:

#showtooltip
/cast [stealth] Ambush; Sinister Strike

Im using Ambush with shadowmeld without any real "stealth" macro the whole time with this. Is there a chance that you can help me to enable Shadowmeld again so i get it in the rotation, like it should be?

**Comment by Hekili** [comment]
When I removed it, I checked sims first and it's not particularly worthwhile in terms of DPS.  Retesting now, it is close to 1%, so I'll add it back in (with a preference to easily enable/disable it).

**Comment by Hekili** [comment]
I revised the criteria for Shadowmeld to allow it in boss fights OR when you're in a group (to avoid resetting).

**Comment by Hekili** [comment]
This is available in the new beta.
