### ISSUE TITLE
Dreadfire Vessel not being recommended for BM Hunter

### ISSUE THREAD

**Issue by aerix88** [Hekili/hekili#940]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Trinket "Dreadfire Vessel" is no longer being recommended for BM Hunter. Cooldowns are enabled, and trinket settings are for boss only; my other trinket is being recommended. DV has been recommended in the past, so I'm not sure what's changed (or if I broke something). As a workaround, I have resorted to manually using the trinket once it is available to be used after the other one is used.

**To Reproduce**
Nothing special here, just using the DV trinket in raid.

**Expected behavior**
DV trinket would be recommended at least once. I've waited several minutes for it to show in the queue but does not.

**Screenshots**
n/a

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/pEVRKTZ2

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/sc21rfLu

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

n/a

**Comment by Hekili** [comment]
Is this happening consistently?  It looks like Dreadfire Vessel was missing from your (autogenerated) Use Items list, which is strange.

**Comment by aerix88** [comment]
I will let you know after tonight (raid night, woo!). Will likely play just BM to see if this is happening all the time or just sometimes.

**Comment by Hekili** [comment]
Thanks.  If you could paste the output from the following command, it would be helpful as well.

`/dump Hekili.Class.itemPack.lists.items`

**Comment by Hekili** [comment]
Based on our conversation, I'm going to close this, but let me know if you see this come up again.
