### ISSUE TITLE
Actionlists not triggering when conditions = true (for Demo at least)

### ISSUE THREAD

**Issue by brugrabud-wow** [Hekili/hekili#946]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by brugrabud-wow** [comment]
**Describe the Bug/Issue**
Run action lists (Demonology) do not seem to work when the priority list is not the default list

**To Reproduce**
Import SimulationCraft APL from SimulationCraft or Create a new Run Action List in the default priority tree.

In my case, I want the APL to trigger an Action list called Tyrant Prep, w/ the only condition being that cooldown.summon_demonic_tyrant.remains <= 20.

When testing it vs. dummy, it shows that the conditions are True, but the action list never triggers

**Expected behavior**
The action list should trigger based on the conditions set when they = True

**Screenshots**
If applicable, add screenshots to help explain your problem.

build: v9.0.2-1.0.40a
level: 60 (60)
class: WARLOCK
spec: demonology

talents: demon_skin
    demonic_calling
    demonic_consumption
    demonic_strength
    grimoire_felguard
    mortal_coil
    summon_vilefiend

pvptalents: none

covenant: necrolord

conduits: borne_of_blood = 5
   diabolic_bloodstone = 6
   fel_celerity = 6
   fel_commando = 5

soulbinds: [bonesmith_heirmir]
   forgeborne_reveries = 1
   heirmirs_arsenal_gorestompers = 1
   resourceful_fleshcrafting = 1
   runeforged_spurs = 1

sets: none

gear: charm_of_eternal_winter = 1
    cinch_of_infinite_tightness = 1
    confidants_favored_cap = 1
    dark_silk_shirt = 1
    faemoss_amice = 1
    grim_pursuants_maille = 1
    impossibly_oversized_mitts = 1
    lakalis_spire_of_knowledge = 1
    leggings_of_lethal_reverberations = 1
    ritual_bone_band = 1
    robes_of_the_cursed_commando = 1
    shadowghast_ring = 1
    shroud_of_the_penitent = 1
    slippers_of_the_forgotten_heretic = 1
    unbound_changeling = 1
    vial_of_caustic_liquid = 1

legendaries: wilfreds_sigil_of_superior_summoning = 1

itemIDs: 178708, 178714, 178870, 178926, 181420, 181503, 182979, 182981, 182996, 182998, 183021, 183022, 183028, 183040, 184141, 4333

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 15
    damage = true
    damageDots = true
    damageExpiration = 6
    damagePets = true
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 20
    nameplates = true
    package = March 3rd
    petbased = true
    potion = spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    implosion_imps = 6

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = false
    mode = automatic
    potions = false
-------------------------------

https://pastebin.com/2cHXLiJm

**Comment by Hekili** [comment]
I moved your snapshot to Pastebin per the instructions.

```
15.  run_action_list ( default - 6 )
Time-sensitive Criteria for tyrant_prep deferred at +3.04 - cooldown.summon_demonic_tyrant.remains[0.00] <= 20 | cooldown.summon_demonic_tyrant.remains[0.00] =0
Action list (tyrant_prep) was found.
+ [tyrant_prep]
Current recommendation was NO ACTION at +60.00s.

16.  demonbolt ( tyrant_prep - 1 )
The action (demonbolt) is usable at (3.04 + 0.00) with cost of 1000 mana.
 - the action is ready before the current recommendation (at +0.00 vs. +60.00).
List ( tyrant_prep ) called from ( March 3rd:default:6 ) would PASS at 0.00.
cooldown.summon_demonic_tyrant.remains[0.00] <= 20 | cooldown.summon_demonic_tyrant.remains[0.00] =0
 - this entry's criteria PASSES: soul_shard[3.00] <=3
Action chosen:  demonbolt at 0.00!
Returned from list (tyrant_prep), current recommendation is demonbolt (+0.00).
- [tyrant_prep]
Added tyrant_prep to blocklist as it was called via RAL.
 - blocking script did not immediately block; will attempt to tune it.
 - leaving delayMin at 0.
The recommended action (demonbolt) is ready in less than 0.2s; exiting list (default).
```

Per the snapshot, the the recommendation of demonbolt is from your `tyrant_prep` list.  What am I missing?

**Comment by brugrabud-wow** [comment]
Unreleated, but being a Paetron supporter - I hope you would have a little more patience, this isn't easy stuff to figure out, and after looking at the directions for 5 minutes I finally found the pastebin request, maybe that should go on the top if it's that important.

Anyhow :)

So if that's true, then maybe it's something very specific to Summon Tyrant.  When I import an APL from SimC, or create my own version of it, it never suggests to Summon Tyrant.   But when I use your Default list, it works fine.

https://www.simulationcraft.org/reports/T26_Raid.html

It's really hard to troubleshoot in-game.

**Comment by Hekili** [comment]
You probably don't want to import at all.  Are you writing a customized list or are you trying to just use what comes from your sim?  The addon's defaults are based directly on the sim profile, and if you import from SimC, you lose the customizations I've made.

If you're not actually writing a custom list for yourself, don't import!  If you are writing a custom list for yourself in SimC, you'll also need to look at how the addon's default priority differs from the SimC default priority, so you can make equivalent changes on your own.

**Comment by brugrabud-wow** [comment]
I am taking your default script, and modifying it so that it aligns better with the suggested rotation based on my legendary.

**Comment by Hekili** [comment]
Show me those specific differences.

**Comment by brugrabud-wow** [comment]
![image](https://user-images.githubusercontent.com/49727795/109874096-a9961780-7c3c-11eb-8b93-5a622896ec58.png)

**Comment by brugrabud-wow** [comment]
ok so I moved the demonbolt and shadowbolt lines below Tyrant and it worked.

**Comment by Hekili** [comment]
What are the differences, though?
