### ISSUE TITLE
After leaving VF it suggests to cast SF

### ISSUE THREAD

**Issue by clozzer** [Hekili/hekili#95]
After leaving VF it suggests casting Shadowform(although we still are in SF).

Issue report: https://pastebin.com/Wfg25cX9

 
Also i get the following Error Message in bugsack: https://pastebin.com/RjMemRvc

**Comment by Hekili** [comment]
Update to the latest release and re-report if you see that issue in your BugSack.

The Shadowform after Voidform bit is persistent; will attempt another fix.
