### ISSUE TITLE
Waiting for DnD to come back up 8 seconds during two target fights 

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#953]
Happens during two target fights like huntsman or during any other 2 target scenario. It stops recommending anything but to wait for death and decay to come back up

https://gist.githubusercontent.com/lemonlust/65b71b9e8fafdcafe616b37987171c85/raw/07782cb36f3ffe0c482f2157186842b01ec150f3/gistfile1.txt

**Comment by Hekili** [comment]
I'm adding an experimental change to the 9.0.5 release that may help with this.  Essentially, you have target swapping disabled (/hek > Unholy > Targeting) which means you have nothing to do while waiting for DnD to come off CD.  The new logic will let you spend runes/wounds as long as you'll have a few when it's time to DnD.

**Comment by Hekili** [comment]
https://gist.githubusercontent.com/lemonlust/3e289a908b35121d4a8314fe16570260/raw/de136ca6b131d32a056230bede7769e97b242106/gistfile1.txt

Hekili wont make a recommendation other than to wait for DND to come on in 8 seconds. On latest update

**Comment by Hekili** [comment]
For some reason, your snapshot isn't including information that mine includes.  Have you made any modifications to your priority?  Are you using the default?

**Comment by lemonlust** [comment]
Happened again on Council 

https://gist.githubusercontent.com/lemonlust/e9280b109604d1ce3616bef35ee5c3d7/raw/0c1529bd0a4ab1b8fdb04a21a1a624e809b1cbf8/gistfile1.txt

**Comment by JL907** [comment]
Happened again on Council

https://gist.githubusercontent.com/lemonlust/e9280b109604d1ce3616bef35ee5c3d7/raw/0c1529bd0a4ab1b8fdb04a21a1a624e809b1cbf8/gistfile1.txt

**Comment by Hekili** [comment]
Next version has some new changes to test.  Coming in about ~5 minutes.

**Comment by Hekili** [comment]
I have 2 threads going re: Unholy DK so I'm closing this one.
