### ISSUE TITLE
Moving the icons

### ISSUE THREAD

**Issue by useotherdoor** [Hekili/hekili#954]
It would be much more useful to have the ability to move the icons. WoW puts temporary action buttons directly in the way for the icons, making them impossible to see

**Comment by Smudgiee** [comment]
You can? Type "/hekili" in game without the quotation marks ofc, Then you're able to move the positions and plenty of other things.

**Comment by Hekili** [comment]
Yes, you can move the displays with /hekili open, or set specific coordinates for each display via /hekili > Displays.
