### ISSUE TITLE
Cancel starlord after first starsurge for Balance druid at opener before combat

### ISSUE THREAD

**Issue by mati3464** [Hekili/hekili#955]
v9.0.5-1.0-beta1

**Describe the Bug/Issue**
At opener for balance druid hekili recommending wrong spell: After first starsurge hekili recommend cancel starlord, even at opener without Celestial/convoke on, hekilii still recommends cancel starlord after first starsurge. 

https://i.imgur.com/fvXc96k.png
https://i.imgur.com/Rdh6cTo.png

https://i.imgur.com/4mYmSuW.png

Recommendation disappear after entering combat. It's ok but something wrong there. 

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.
https://pastebin.com/p09Hj3vd

**Comment by Hekili** [comment]
Please follow the ticket instructions.

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

**Comment by mati3464** [comment]
Snap: 

https://pastebin.com/Gpc1UxUh (clean snap )

Screen with Starlord cancel screen recommendation while paused between 3 starsurges:

https://i.imgur.com/LuQOpbR.png


That strange recommendation appear after new beta released.

**Comment by Hekili** [comment]
Try this:

/hekili > Priorities > Balance > Action Lists.

Select Action List = boat, Entry = 6.

Update the criteria to:
```gcd.remains = 0 & ( buff.balance_of_all_things_nature.remains > 4.5 | buff.balance_of_all_things_arcane.remains > 4.5 ) & ( cooldown.ca_inc.remains > 7 | ( cooldown.empower_bond.remains > 7 & ! buff.kindred_empowerment_energize.up & covenant.kyrian ) ) & astral_power >= 30```

Click Accept.

**Comment by mati3464** [comment]
Ok it fixed.

**Comment by Hekili** [comment]
Thanks.  I'll be adding a different fix that accomplishes the same thing.
