### ISSUE TITLE
HEKILI Doesn't show keybind for Druid

### ISSUE THREAD

**Issue by kplaya1** [Hekili/hekili#956]
When I play as Druid, Hekily doesn't show keybindings.
However, if I play in a different class, it is fine.
I wonder if this is a bug or another problem.
![WoWScrnShot_031021_005709](https://user-images.githubusercontent.com/80341203/110499567-b682a180-813b-11eb-962c-3a868b50971a.jpg)

**Comment by Hekili** [comment]
You have your druid's bars arranged in an odd way that interferes with automatic detection.

You can manually set keybindings in /hekili > Abilities > Override Keybind Text, if you don't want to reorganize your bars to match the default.

**Comment by kplaya1** [comment]
Thank you for your feedback!!!
It works well!!
