### ISSUE TITLE
Hekili still waiting for DnD 8 seconds w/ Cycling Enabled in two target fights

### ISSUE THREAD

**Issue by JL907** [Hekili/hekili#958]
https://gist.githubusercontent.com/lemonlust/3e289a908b35121d4a8314fe16570260/raw/de136ca6b131d32a056230bede7769e97b242106/gistfile1.txt

Hekili wont make a recommendation other than to wait for DND to come on in 8 seconds. On latest update

Original Issue: https://github.com/Hekili/hekili/issues/953

**Comment by Hekili** [comment]
Reopening original ticket for you, to keep info together.
