### ISSUE TITLE
Auto generated Snapshots Unholy DK during Aoe Scenarios

### ISSUE THREAD

**Issue by ijoihlhnn** [Hekili/hekili#962]
**BEFORE SUBMITTING AN ISSUE:**

1.  Latest Release

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Auto Genrérated Snapshots during AOE Scenarios

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

build: v9.0.5-1.0
level: 60 (60)
class: DEATHKNIGHT
spec: unholy

talents: army_of_the_damned
    grip_of_the_dead
    infected_claws
    soul_reaper
    unholy_blight
    unholy_pact
    wraith_walk

pvptalents: none

covenant: venthyr

conduits: eternal_hunger = 5
   fleeting_wind = 6
   hardened_bones = 6
   spirit_drain = 6

soulbinds: [theotar_the_mad_duke]
   exquisite_ingredients = 1
   leisurely_gait = 1
   soothing_shade = 1

sets: none

gear: charm_of_eternal_winter = 1
    colossal_plate_gauntlets = 1
    dessias_decimating_decapitator = 1
    diadem_of_imperious_desire = 1
    dreadfire_vessel = 1
    epaulettes_of_overwhelming_force = 1
    inscrutable_quantum_device = 1
    mantle_of_manifest_sins = 1
    most_regal_signet_of_sire_denathrius = 1
    pit_fighters_wristguards = 1
    rampaging_giants_chestplate = 1
    shadowghast_greaves = 1
    signet_of_the_false_accuser = 1
    stoic_guardsmans_belt = 1
    tabard_of_the_lightbringer = 1
    warboots_of_ruthless_conviction = 1

legendaries: frenzied_monstrosity = 1

itemIDs: 171416, 178807, 178824, 178866, 179350, 180101, 182984, 182994, 182997, 182999, 183025, 183033, 183036, 183040, 184030, 52252

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycleDebuff = festering_wound
    cycle_min = 5
    damage = false
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = potion_of_spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = reactive
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
https://pastebin.com/KMu66MyT

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment]
That doesn't look like an AOE scenario.  There's only 1 target.

**Comment by Hekili** [comment]
In /hekili > Unholy > Performance, check Enhanced Recheck and see if that resolves your issue.

**Comment by ijoihlhnn** [comment]
i will test it tomorrow with Enhanced recheck enabled!

**Comment by JL907** [comment]
https://gist.githubusercontent.com/lemonlust/707150bccbe9d8de71144f2f461e968c/raw/e08074c257eaf0b178d2c0068676cd33f9f47d81/gistfile1.txt

i got some auto generated snapshots during an AOE situation wondering if this helps

**Comment by ijoihlhnn** [comment]
i just saw i already hat enhanced recheck enabled.
The issue arrived with the change made in version 
v9.0.2-1.0.39 where you tighted down on Festering wounds, not sure just a thought if that has to do with it. 

https://github.com/Hekili/hekili/commit/506a42d941a76a7ca4b6ddbddf34940597c5a9a1

**Comment by ijoihlhnn** [comment]
actions.cooldowns+=/apocalypse,if=active_enemies=1&debuff.festering_wound.stack>=4

Thats the Simc Profile from https://github.com/simulationcraft/simc/blob/shadowlands/profiles/Tier26/T26_Death_Knight_Unholy.simc

and the profile hekili uses right now uses this line:
actions.cooldowns+=/apocalypse,if=active_enemies=1&debuff.festering_wound.stack>3

line 70.

**Comment by Hekili** [comment]
Your snapshot shows `enhancedRecheck = false`.

`>=4` and `>3` are functionally the same.

**Comment by ijoihlhnn** [comment]
i see, my bad the "/hekili > Issue Reporting" export showed it as true because i probably enabled it afterwards and wasnt enabled as the Snpashot occured. Will send you new Snapshots if they should occur with enhanced recheck enabled.

Okay, good to know!

**Comment by ijoihlhnn** [comment]
Got one with the same setup as above but with enhanced recheck enabled in version: v9.0.5-1.0.1-beta1

AOE window: https://pastebin.com/B4yPCbdK
-------------------------------------------
Primary window:

https://pastebin.com/yA9NRNtE
https://pastebin.com/j3kwMnsd
https://pastebin.com/sFhPmMD9
https://pastebin.com/uz2vwPAC
https://pastebin.com/5xWAH87W

**Comment by Hekili** [comment]
There's something strange happening with Rune regeneration that I'm working on.  Will post a new beta in a bit.

**Comment by ijoihlhnn** [comment]
I'm going to test it, not sure if today but i will let u know about it by tomorrow.

**Comment by ijoihlhnn** [comment]
Snap from version: v9.0.5-1.0.1-beta2 - seems to be the same line
https://pastebin.com/SjxmzKpx
https://pastebin.com/N46RsDCC

**Comment by Hekili** [comment]
What do you mean by "seems to be the same line"?

**Comment by ijoihlhnn** [comment]
it looked like it starts to throw the generated snapshot at the same time as before the fix. it was mainly my own thought idk why i typed it down.

**Comment by Hekili** [comment]
If there are Unholy DK auto-snapshots in the newer releases, you can open a new ticket with those snapshots.  I don't think there is anything left outstanding at this point in time.
