### ISSUE TITLE
Unknown Icon and spell in rotation - Feral Druid

### ISSUE THREAD

**Issue by Lnau** [Hekili/hekili#964]
Unknown Icon and spell in rotation - Feral Druid
I there a way to show a list with icons being used in the rotation?
Can you tell me what spell is associated with this icon?
Thanks
![Icon](https://user-images.githubusercontent.com/11722169/110855461-39564a00-826b-11eb-85e9-0c2e7bc80ac2.jpg)

**Comment by Hekili** [comment]
That is Shadowmeld.  You can Pause (SHIFT-ALT-P, by default) and mouseover the icon to see what is displayed and why.

**Comment by Lnau** [comment]
Thank you for the quick response!
