### ISSUE TITLE
Affliction - Agony target swap not at right time

### ISSUE THREAD

**Issue by tacoinspace** [Hekili/hekili#965]
Agony will only recommend to refresh the dot on other targets when it falls off, not when it's refreshable. This also applies to the other warlock dots as well, but it really hurts warlock dps on agony because it needs to stay on to do full damage.

**Comment by Hekili** [comment]
Yes, it's a known issue.  It requires rewriting how multi-target is handled, and will not be resolved any time soon.  I suggest using WeakAuras to track when you have Agony close to falling off on secondary targets.
