### ISSUE TITLE
[Cancel Buff] action not working with Bladestorm.

### ISSUE THREAD

**Issue by Crelam** [Hekili/hekili#969]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
`cancel_buff` action in Fury Warrior priority is not recommending canceling Bladestorm.  As part of trouble shooting I also tested this same action, but changed the buff to Recklessness and it was recommended implying the issue is specific to Bladestorm.

**To Reproduce**
Spec into Bladestorm.  Use default Fury Warrior priority.  Attack training dummy.  Use Bladestorm.  While Bladestorm is running (spinning?) take a snapshot.  Note that action `23.  cancel_buff ( single_target - 3 )` states:
     `The action (cancel_buff) is unusable at (0.00 + 1.97) because required buff (bladestorm) not active.`

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/suYUxhM7

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
Note that this snapshot was taken when under the effects of Bladestorm.
https://pastebin.com/epSE3mX6

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
No error messages, but as a side note WoW does freeze for a sec when interacting with the options of a Cancel_Buff action.  I assume this is due to it loading that massive list of buffs.

**Comment by Hekili** [comment]
This will be fixed in the next build.
