### ISSUE TITLE
Shadow Word  Death is in the recomendations for healthy targets without the fiend pet  being active

### ISSUE THREAD

**Issue by octapusxft** [Hekili/hekili#970]
Lastest version of the addon

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
The rotation recommends using Shadow Word: Death on mobs outside of their 20% execution phase when the Shadowflame Prism legendary is equiped even when there is no Mindbender or Shadowfiend active or Off the cooldown.
When looking at the action lists, the "pet.fiend.active" somehow is "nil" instead of "false" when the fiend/bender is not active and "true" when the fiend/bender is actually active"

**To Reproduce**
Equip the shadowflame prism legendary as a shadow spec priest.
You will see that the Shadow word Death is already second or there in the sequence of the suggested spells without

**Expected behavior**
Considering that the SW: Death is supposed to be used when having this legendary when the mindbender/shadowfiend is active, it should not be higher on the priority than the mindbender itself and it should not be prompted to be used outside of the mindbender windows when the target is above 20% health.

**Screenshots**
https://i.imgur.com/vQDC3PY.png  (shows the recommendations with Mindbender on off cooldown and on cooldown
https://i.imgur.com/DCNO8yC.png (Shows the paused text of Shadow word death. Should it not be recomended when the pet.fiend.active is "nil" and the target not on <20% health ?)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1. **PUT ISSUE REPORT LINK HERE:** 
https://pastebin.com/9n7MxCwB

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:** 
https://pastebin.com/mQwavuVX  (old snapshot)
 edit: https://pastebin.com/PihuWpwM (new snapshot)

**Comment by Hekili** [comment]
The snapshot you provided was not taken at the time Shadow Word Death was being recommended.  Please provide that.

**Comment by octapusxft** [comment]
This time I paused it when Shadow world death was the primary icon 
I hope it works this time  https://pastebin.com/PihuWpwM

Here is a short recording as well showing the incident
https://www.youtube.com/watch?v=81mHSUGZqzA

**Comment by Hekili** [comment]
The snapshot was perfect.  I have a fix prepared to go out today.

**Comment by octapusxft** [comment]
This is great news, I am happy to help. This addon is very important to me, I do not think I would be able to play a lot of the specs anymore (some became too complex over the years). I hope the time will someday come were disk also gets supported, I will join on Patreon in hopes of making it more likely to happen one day  :)

EDIT: I can confirm the issue was fixed in that latest beta 3 version of the addon!
