### ISSUE TITLE
Moonkin bad Starfire\SUnfire suggestions

### ISSUE THREAD

**Issue by Swiftkill** [Hekili/hekili#974]
Hekili often suggest to cast those two in wrong phases. Sunfire should have priority in sun phase, while starfire - in moon phase. While there are edge cases, e.g. spamming moonfire in sun phase while moving to place dots or to use it in PVP - moonfire there got a talent that applies full damage, in general that's a GCD loss and push of counter in wrong direction.

**Comment by Hekili** [comment]
Please follow the instructions when submitting tickets.
