### ISSUE TITLE
Interrupt icon doesnt show up

### ISSUE THREAD

**Issue by rosenberger877** [Hekili/hekili#976]
Addon is great, but cant get interrupt icon to show up in testing with other classes casting. Have tried to set up 15 times and in test mode can get the box to show up.

- Go to 'displays'
- Click on 'interrupts'
- Enable (check) 'target'

build: v9.0.5-1.0
level: 60 (60)
class: PALADIN
spec: retribution

talents: blade_of_wrath
    divine_purpose
    final_reckoning
    fist_of_justice
    healing_hands
    righteous_verdict
    unbreakable_spirit

pvptalents: none

covenant: kyrian

conduits: lights_barding = 4
   ringing_clarity = 5
   shielding_words = 5
   templars_vindication = 5

soulbinds: [pelagos]
   bond_of_friendship = 1
   combat_meditation = 1
   focusing_mantra = 1
   let_go_of_the_past = 1

sets: sinful_gladiators_badge_of_ferocity = 1

gear: band_of_the_risen_bonelord = 1
    dessias_decimating_decapitator = 1
    fallen_templars_gauntlets = 1
    oversized_centurion_helm = 1
    shadowghast_breastplate = 1
    shieldguards_warboots = 1
    sinful_aspirants_plate_girdle = 1
    sinful_gladiators_amulet = 1
    sinful_gladiators_badge_of_ferocity = 1
    sinful_gladiators_drape = 1
    sinful_gladiators_plate_legguards = 1
    sinful_gladiators_plate_shoulders = 1
    sinful_gladiators_ring = 1
    sinful_gladiators_sigil_of_adaptation = 1
    soldiers_stoneband_wristguards = 1
    stormwind_tabard = 1
    white_tuxedo_shirt = 1

legendaries: final_verdict = 1

itemIDs: 171412, 175875, 175904, 175909, 175916, 175921, 178353, 178448, 178866, 181606, 181816, 183013, 183031, 184132, 184143, 45574, 6833

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Retribution
    petbased = false
    potion = spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = single
    potions = false

**Comment by Hekili** [comment]
This is your third ticket without providing all the ticket information.  I need you to provide a snapshot when this is happening.

> 2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
>
> **PUT SNAPSHOT LINK HERE:**  

If you have /hekili > Toggles > Interrupts: Show Separately checked, then I need you provide a snapshot of your Interrupts display.

If you do not have Show Separately checked, then I need you to provide a snapshot of your Primary display when your target is casting an interruptible spell.

**Comment by rosenberger877** [comment]
Cant send you a screen shot of the " Primary display when your target is casting an interruptible spell" because the interrupt box doesn't show up when I'm fighting an opponent

I do have this checked:    /hekili > Toggles > Interrupts: Show Separately checked,

<img width="1600" alt="Screen Shot 2021-03-13 at 10 43 48 AM" src="https://user-images.githubusercontent.com/55889865/111037306-1487e100-83e9-11eb-9cf7-5c9a257a2d7d.png">

<img width="1600" alt="Screen Shot 2021-03-13 at 10 40 40 AM" src="https://user-images.githubusercontent.com/55889865/111037214-c70b7400-83e8-11eb-9f48-96c7d86db95a.png">

Thanks for any help

build: v9.0.5-1.0
level: 60 (60)
class: PALADIN
spec: retribution

talents: blade_of_wrath
    divine_purpose
    final_reckoning
    fist_of_justice
    healing_hands
    righteous_verdict
    unbreakable_spirit

pvptalents: none

covenant: kyrian

conduits: lights_barding = 4
   ringing_clarity = 5
   shielding_words = 5
   templars_vindication = 5

soulbinds: [pelagos]
   bond_of_friendship = 1
   combat_meditation = 1
   focusing_mantra = 1
   let_go_of_the_past = 1

sets: sinful_gladiators_badge_of_ferocity = 1

gear: band_of_the_risen_bonelord = 1
    dessias_decimating_decapitator = 1
    fallen_templars_gauntlets = 1
    oversized_centurion_helm = 1
    shadowghast_breastplate = 1
    shieldguards_warboots = 1
    sinful_aspirants_plate_girdle = 1
    sinful_gladiators_amulet = 1
    sinful_gladiators_badge_of_ferocity = 1
    sinful_gladiators_drape = 1
    sinful_gladiators_plate_legguards = 1
    sinful_gladiators_plate_shoulders = 1
    sinful_gladiators_ring = 1
    sinful_gladiators_sigil_of_adaptation = 1
    soldiers_stoneband_wristguards = 1
    stormwind_tabard = 1
    white_tuxedo_shirt = 1

legendaries: final_verdict = 1

itemIDs: 171412, 175875, 175904, 175909, 175916, 175921, 178353, 178448, 178866, 181606, 181816, 183013, 183031, 184132, 184143, 45574, 6833

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Retribution
    petbased = false
    potion = spectral_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    check_wake_range = true

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = single
    potions = false

**Comment by Hekili** [comment]
Please reread the instructions I provided. Without a snapshot, this ticket will be closed.

**Comment by rosenberger877** [comment]
Snapshot is beyond my technical skills. Thanks anyway
