### ISSUE TITLE
Retribution Paladin - Self Healing

### ISSUE THREAD

**Issue by Nazeth** [Hekili/hekili#977]
Hey.

I added 2 lines in actions to heal myself, if its very needed.

actions+=/flash_of_light,if=(health.pct<50)&buff.selfless_healer.stack=4
actions+=/word_of_glory,if=(health.pct<50)

sadly for some reason both of them dont trigger, if conditions are truth.

Did i miss something?

**Comment by Hekili** [comment]
Custom priorities aren't actively supported, but if I did support them, I'd need you to fill out a whole ticket including the required snapshot so I can see what's happening.

My best guess with what's provided here is that you added to the import tab but didn't import.  My next best guess is that, based on where you placed these in your priority, there are other entries that are higher priority that are recommended instead.
