### ISSUE TITLE
As a player, I would like to be able to opt skills out of moving so that I can know what to press as MM

### ISSUE THREAD

**Issue by steveriggins** [Hekili/hekili#978]
I am learning MM and while moving a lot (say Sire) I am having a hard time keeping DPS up because all of my Volley/Aimed Shots are prioritized.

I noticed on Elemental Shaman that spells come and go as I move, and aside from the simc profile, I did not notice a setting or in the code where this is handled. I did try for hours before coming here :)

Mainly I want to be able to tell Aimed Shot to go away when I am moving. I separated Volley/Explosive Shot into AOE, and made my main display ST only. I made them 1 icon each and stuck on top of my character. I have focus issues so I need them right there, right now.

I love Hekili. I’ll keep looking around for how I can achieve what I want, I just find myself lost in the number of option panels.

Thank you!

**Comment by SpatenLa** [comment]
there is only one spell where you need to stand still as marksman hunter.
![grafik](https://user-images.githubusercontent.com/39881841/111076101-3b2e4080-84eb-11eb-8999-2d7b6061d277.png)
aimed shot without proc

**Comment by steveriggins** [comment]
Thanks! No idea why I could not see that checkbox.
