### ISSUE TITLE
[Shadowpriest] pet.fiend.active is returning nil status

### ISSUE THREAD

**Issue by porklasagna** [Hekili/hekili#981]
**Describe the Bug/Issue**
Hekili is suggesting casting SW:D even when Shadowfiend/Mindbender isn't up and active.
Upon checking the action list, it seems that the flag pet.fiend.active is returning nil.

**To reproduce : **

1. Go to Hekili (As Shadowpriest, theres a default Shadow profile)
2. Click Priorities
3. From the dropdown of Priorities, select Shadow
4. On the right window, select Action Lists
5. Select 'main' from Action List drop down
6. In the Entry drop down, Select Item 12, Shadow Word Death(for default Shadow Priest profile)
7. Hover over conditions. check pet.fiend.active 
8. pet.fiend.active is returning nil; expected should be either false or true

OR

1. As a shadowpriest, equip Shadowflame Prism.
2. Check the priorities given by Hekili out of combat; SW:D is always shown even when Mindbender is not out.

**Expected behavior**
Shadow Word : Death should not be recommended when Shadowfiend/Mindbender is not out while wearing Shadowflame Prism; the flag pet.fiend.active should not return nil (should return false or true)

**Screenshots**

Out of combat SW:D  : 
![image](https://user-images.githubusercontent.com/80699322/111196938-18e40380-857b-11eb-94e7-32e609aaf99e.png)

pet.fiend.active returning nil : 
![image](https://user-images.githubusercontent.com/80699322/111197141-58125480-857b-11eb-9e09-127648a21c7a.png)

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/mvZZptHj

**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/tFCiJBa7

**Comment by Hekili** [comment]
Per ticket instructions, try latest beta before reporting.

**Comment by Hekili** [comment]
(For clarity, this should be solved within the latest beta builds.)
