### ISSUE TITLE
Seraphim is not showing in rotation

### ISSUE THREAD

**Issue by nejkoo** [Hekili/hekili#983]
**BEFORE SUBMITTING AN ISSUE:**

I tried to use latest version aswell as beta.

**Describe the Bug/Issue**
Paladin / Retribution
Usually seraphim talent was top priority as soon as it was off cooldown and you had 3HP but now there is no seraphim in rotation. I tried in boss fights, dungeons, dummies, different talents and then go back and it doesnt work.

**To Reproduce**
Cant reproduce if its not there.

**Expected behavior**
Seraphim in rotation.

https://pastebin.com/9H15PP1A

**Comment by Hekili** [comment]
Fill out the entire ticket, including the snapshots when you think Seraphim should be recommended but it isn't.

**Comment by nejkoo** [comment]
https://pastebin.com/9H15PP1A

**Comment by Hekili** [comment]
> Fill out the entire ticket, including the snapshots when you think Seraphim should be recommended but it isn't.

You don't have any Holy Power in that snapshot, I'm sure you weren't expecting Seraphim to appear without Holy Power.  Can you take a snapshot when you have 3 Holy Power and are expecting Seraphim to be recommended?

**Comment by nejkoo** [comment]
> > Fill out the entire ticket, including the snapshots when you think Seraphim should be recommended but it isn't.
> 
> You don't have any Holy Power in that snapshot, I'm sure you weren't expecting Seraphim to appear without Holy Power. Can you take a snapshot when you have 3 Holy Power and are expecting Seraphim to be recommended?

https://pastebin.com/ULkpi618

**Comment by Devates** [comment]
+1 seraphim has not showed up as priority at all in rotation since maybe last week? its driving me nuts haha hopefully it gets fixed <3 even with hp
after every other cd is used it still isn't prio'd
EDIT-THIS IS ONLY WHEN TALENTED INTO EXECUTION SENTENCE AND WORKS GOOD WITH ZEAL ETC I THINK

**Comment by Hekili** [comment]
This should have been resolved when the logic for Execution Sentence, Final Reckoning, and Seraphim were relaxed.  If it's still an issue, please open a new ticket with updated snapshots.
