### ISSUE TITLE
Lua Errors on Unholy

### ISSUE THREAD

**Issue by Tzuyume** [Hekili/hekili#984]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Whenever you play unholy with Soul Reaper the addon gives you a constant barrage of lua errors.

**To Reproduce**
From what i know all you need to do is log a unholy dk and whenever addon tells you to press Soul Reaper you get thousands of Lua Errors.

**Expected behavior**
No Lua Errors

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/nLZDJkMt

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

https://pastebin.com/gScXgE5P

**Comment by geraint425** [comment]
I also have a bug with rotation here is a screenshot. https://imgur.com/a/aW6yObY

**Comment by Hekili** [comment]
Yes, that's likely the same issue.

I'll be posting a new beta tonight which should resolve it.

**Comment by Hekili** [comment]
This should be resolved in v9.0.5-1.0.1
