### ISSUE TITLE
Racials

### ISSUE THREAD

**Issue by pkuall4life** [Hekili/hekili#985]
Please describe your idea or feature and when it would be useful.
For Goblins, we have either Rocket Jump or Rocket Barrage. Would like to use that in my core rotation if i have no use for using the Rocket Jump Ability.

**Comment by Hekili** [comment]
Nah, there's no optimizing around this.  I don't have anyway to know if/when you might want the utility of Rocket Jump and Rocket Barrage is probably a DPS loss in most cases (like how Bag of Tricks can be a DPS loss for Vulpera).
