### ISSUE TITLE
Fury Warrior wrong APL

### ISSUE THREAD

**Issue by lonesniper52** [Hekili/hekili#989]
**Describe the Bug/Issue**
Hekili starts off with charge, condemn, bloodthirst, raging blow, enrage , recklessness
how it should be: charge, bloodthirst, recklesness

**Expected behavior**
how it should be: charge, bloodthirst, recklesness. Shouldnt wait to enrage before recklessness

**Screenshots**
hekili recommendation: https://cdn.discordapp.com/attachments/691318915149856838/821901387632869378/unknown.png
5 min patchwerk sim:
https://cdn.discordapp.com/attachments/691318915149856838/821901447788363827/unknown.png

 
**PUT SNAPSHOT LINK HERE:**

https://pastebin.com/SCAaq7De

**PUT ERROR MESSAGE(S) HERE:**

**Comment by jozo1200** [comment]
Skyhold lodge on discord has it correct as per the current apl if you are using the signet. Always enrage before recklessness btw

Charge -> Condemn -> Bloodthirst (no Enrage) -> Raging Blow -> Condemn -> Rampage + Recklessness -> Condemn (cancel BS proc) -> Bladestorm -> Condemn (cancel BS)

or if enraged from bloodthirst use:

Charge -> Condemn -> Bloodthirst (Enrage) -> Bladestorm -> Condemn (cancel BS) -> Rampage + Recklessness -> Condemn (cancel BS proc)

**Comment by lonesniper52** [comment]
thats incorrect that pin is outdated. that was the normal rotation with signet up until like 2 weeks ago.

**Comment by Hekili** [comment]
The difference is that the Fury APL, as written for SimC uses the "sequence" feature that the addon doesn't support.  I can (and will) rewrite that part soon.

**Comment by Hekili** [comment]
I've written a really horrible but functional workaround for this into the addon's Fury APL.  It's available in v9.0.5-1.0.2.
