### ISSUE TITLE
Please fix Raise Abomination for Unholy DK - added screenshots

### ISSUE THREAD

**Issue by Bjardr** [Hekili/hekili#99]
Hello Sir,

The pvp ability "raise abomination" has not been working for several patches. I don't think it has worked since you adjusted the way this ability is recognized a couple months ago. Hekili does not recognize "raise abomination" as an ability, and it does not suggest it's use while in PvP even though it is selected as a PvP talent. Please help!

`Adam

**Comment by Hekili** [comment]
What about it doesn't work?  I'm looking at it right now.

Submit a proper ticket with a snapshot if/when you think it should be showing but it isn't appearing, please.

**Comment by Bjardr** [comment]
My apologies for not submitting a proper ticket. I don't have a snapshot to paste here, but will paste my character info and attach a document showing my issues to help. In "Issue 1" attachment, it shows how "raise abomination" is missing from the ability list, but is in my primary display when out of a PvP match. When within a PvP match, "raise abomination" does not display, but "army of the dead" does instead.

![Issue 1](https://user-images.githubusercontent.com/49419120/55815140-8cc22b00-5a8b-11e9-8c52-c2159d132c36.png)
![Issue 2](https://user-images.githubusercontent.com/49419120/55815156-964b9300-5a8b-11e9-8489-a81cf4f899d1.png)

 Thank you very much.

build: v8.1.5-07
level: 120
class: DEATHKNIGHT
spec: unholy

talents: ebon_fever
    grip_of_the_dead
    infected_claws
    pestilence
    soul_reaper
    unholy_frenzy
    wraith_walk

traits: azerite_empowered=2
    azerite_globules=1
    battlefield_precision=1
    cold_hearted=1
    festermight=3
    gemhide=1
    gutripper=1
    harrowing_decay=1
    magus_of_the_dead=1
    overwhelming_power=1
    self_reliance=1

sets/legendaries/artifacts: none

gear:     loop_of_pulsing_veins=1
    desert_guardians_breastplate=1
    sinister_gladiators_cape=1
    zanchas_venerated_greatbelt=1
    footbomb_championship_ring=1
    knot_of_ancient_fury=1
    sinister_gladiators_maledict=1
    ballast_sinkers=1
    electroarm_bludgeoner=1
    sharktoothknuckled_grips=1
    legplates_of_profane_sacrifice=1
    antisepticsoaked_dressing=1
    heart_of_azeroth=1
    sinister_gladiators_plate_headcover=1
    concealed_fencing_plates=1
    skyscorcher_pauldrons=1

**Comment by Bjardr** [comment]
Also, here is another screenshot from an older version I tried (v8.1.0-06) just to see if it would be fixed. However in the older version it didn't display "raise abomination" even when it was placed on the action list. 

![Issue 3 (older version)](https://user-images.githubusercontent.com/49419120/55816194-6ef5c580-5a8d-11e9-9642-8924dfbee3af.png)

Thank you.

**Comment by Hekili** [comment]
Raise Abomination and Army of the Dead are treated as the same spell.

I'm posting 8.1.5-08-alpha3 which may improve PvP talent detection in BG content, but for anything else, you'll either have to wait for me to replicate the issue that you're having on my own, or follow the ticket instructions to provide a proper snapshot.
