### ISSUE TITLE
Frost Shock/Flame Shock

### ISSUE THREAD

**Issue by Twizzerious** [Hekili/hekili#990]
[Snapshot.txt](https://github.com/Hekili/hekili/files/6160807/Snapshot.txt)

There is something going on with recommendations of flame shock and frost shock based on the pandemic window. Ive seen it for a while but was finally able to get a decent clip and snap shot.

Issue: Hekili will recommend frost shock till the very last second at which point it quickly swaps over to flame shock. Most of the time the frost shock button is already being pressed and qued up to be cast right as it changes over. This very well might not be a problem at all but I think in these situations it should have been recommending flame shock the whole time based on the pandemic timer + some extra wiggle room for latency perhaps? A twitch clip is also linked. A few seconds in you will see an instance of what i am talking about.

https://www.twitch.tv/videos/953473096

This is twizz from the shaman discord. we can talk about it a bit if you would like via discord or whatever. This is a thing ive seen since basically the start of the expac but could never catch good evidence for it (or just plain forgot to while in the middle of progression)

**Comment by Hekili** [comment]
Update to the latest version (new release tonight).  That snapshot shows Windfury Totem, etc. being recommended.  It's not a snapshot showing the behavior you're describing.

**Comment by Hekili** [comment]
As far as it goes, a recommendation doesn't have any kind of verification beyond the recommendation time.  So "use Frost Shock with Hailstorm" can be the right action at +1.05 and "refresh Flame Shock in Pandemic range" can be right at +1.10.  Rechecking to see if the recommendation would be valid for X amount of time isn't CPU efficient at all.

But with a correct snapshot for each scenario, I can approach with more clarity.  It seems like this would be replicable on a dummy.

**Comment by Hekili** [comment]
Closing -- if you submit additional snapshots related to flickering, I can reopen and investigate.
