### ISSUE TITLE
[Arcane Mage] Default settings are confusing for new users

### ISSUE THREAD

**Issue by Thordros** [Hekili/hekili#991]
**1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.**
_I did it!_

**2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.**
_You aren't my dad._

****Describe the Bug/Issue**
A clear and concise description of what the bug is.**
_The Arcane Mage module has Arcane Missiles spam turned on by default. That's confusing for new users, since it's more of an advanced feature. It should be turned off by default._

_Also, the addon is interpreting line 233...._

`actions.movement+=/blink_any,if=movement.distance>=10`

_.... as recommending you Blink any time you're more than 10 yards from the target. I recommend disabling Blink by default._

**Comment by Hekili** [comment]
I'll shift am_spam to default to off since that's what the current sim profile does.

> Also, the addon is interpreting line 233....
> actions.movement+=/blink_any,if=movement.distance>=10
> .... as recommending you Blink any time you're more than 10 yards from the target. I recommend disabling Blink by default.

It is disabled by default.  But I should probably make movement.distance depend on you actually moving.
