### ISSUE TITLE
Error spam in 9.0.5-1.0.1

### ISSUE THREAD

**Issue by filliph** [Hekili/hekili#994]
**Describe the Bug/Issue**
Error spam after installing 9.0.5-1.0.1, as Frost Mage.

**To Reproduce**
- Go into combat
- Watch your BugGrabber error log fill up

**Expected behavior**
The addon to work without spamming up the error log

**PUT ERROR MESSAGE(S) HERE:**
117x Hekili\Hekili-v9.0.5-1.0.1.lua:205: bad argument #4 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "@Hekili\Hekili-v9.0.5-1.0.1.lua"]:205: in function `Debug'
[string "@Hekili\Core.lua"]:1687: in function `ProcessHooks'
[string "@Hekili\Options-Options.lua"]:10182: in function `MakeSnapshot'
[string "@Hekili\Core.lua"]:1776: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:824: in function <Hekili\UI.lua:689>

Locals:
(*temporary) = "%4sNo recommendation found before event #%d (%s %s) at %.2f; triggering event and continuing ( %.2f ).
    "
(*temporary) = ""
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0.071277
(*temporary) = 2.984000
(*temporary) = "string expected, got nil"

**Comment by slothplaysnecro** [comment]
Also getting similar errors when in combat with 3+ targets. The following was generated in Heroic MoTS when fighting the Drust Spiteclaws along with the pack of Drust with the Tirnen Villager.

No errors fired while in combat with Droman. (2 target encounter)

73x Hekili\Hekili-v9.0.5-1.0.1.lua:205: bad argument #4 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "@Hekili\Hekili-v9.0.5-1.0.1.lua"]:205: in function `Debug'
[string "@Hekili\Core.lua"]:1687: in function `ProcessHooks'
[string "@Hekili\Options-Options.lua"]:10182: in function `MakeSnapshot'
[string "@Hekili\Core.lua"]:1776: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:824: in function <Hekili\UI.lua:689>

Locals:
(*temporary) = "%4sNo recommendation found before event #%d (%s %s) at %.2f; triggering event and continuing ( %.2f ).
    "
(*temporary) = ""
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0.241489
(*temporary) = 2.713000
(*temporary) = "string expected, got nil"

**Comment by Hekili** [comment]
This may be resolved in v9.0.5-1.0.1a.  If any new Snapshots are generated, I'd appreciate if they could be provided here (via Pastebin).

**Comment by methodrik** [comment]
Frost mage here as well, using v9.0.5-1.0.1a and glacial fragments legendary (now named Icebringer, if that matters at all).
I was getting spam errors before the bandaid but still getting them after updating.

Weird thing is the snapshot spam stops and everything goes back to normal if I unequip the Icebringer legendary (I picked pants slot) and starts again if I put them on.

pastebin of snapshot: (sorry if this isn't proper, never done this before)

https://pastebin.com/VBWfwTmG

**Comment by Hekili** [comment]
Post the error after the update.
