### ISSUE TITLE
Venthyr Warrior Covenant Ability not excluded for range.

### ISSUE THREAD

**Issue by Crelam** [Hekili/hekili#997]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
Condemn, the Venthyr Warrior Covenant Ability that replaces Execute, does not have a range check.  I think this is the same issue as Stormstrike/Primal Strike where you have to check the range of the base ability.  Please note that I only checked this under Fury spec, but I can't see why it would be different for Prot/Arms.

**To Reproduce**
Use standard fury priority list, be Venthyr, set Primary Display Range Setting to "Exclude Out-of-Range", stand just outside of melee range of training dummy, see that is recommends Condemn.

**Expected behavior**
I expect it to hide the Condemn action, moving on to other actions, while out of range.  Like other targeted melee abilities.

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**
https://pastebin.com/vqu758eu

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**
https://pastebin.com/N0mgWjMM

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Crelam** [comment]
In a tangentially related issue, the minimum range for Charge seems to be off by about 2 yards.  I'm not sure if that is intentional or not.

**Comment by Hekili** [comment]
First, friendly reminder that I hate "Exclude Out-of-Range" and every time I do something to support it, I get 1% sadder.

Second, I'll make it use Execute's spell ID for range checking (next beta).

> In a tangentially related issue, the minimum range for Charge seems to be off by about 2 yards. I'm not sure if that is intentional or not.

It's manually set to 10 yards, when the requirement is actually 8, to deal with some inconsistency with range via the WoW API.  It also makes it a little forgiving.

**Comment by Crelam** [comment]
Sorry to Saturate you with Sorrow & Sadness.  I tried this under the current beta (v9.0.5-1.0.2-beta1) and now it acting like I don't have the Condemn ability at all.  The entry in the priority list is in red. The ability does not show in the Abilities listing.

Here is an updated snapshot: https://pastebin.com/RLjiWkM2

**Comment by Hekili** [comment]
Check the end of the Abilities listing.  It sounds like it's disabled (which moves it to the end of the list due to the text coloring).

**Comment by Crelam** [comment]
I thought the same thing, but no dice.  I don't have any red entries in the abilities list.

Also, the snapshot does not indicate that condemn is `ability disabled ( preference )` it just simply skips them.  Note how it goes from  `22.  bladestorm ( single_target - 4 )` to `23.  siegebreaker ( single_target - 6 ) - talent [ siegebreaker ] missing` skipping over `single_target- 5`.

**Comment by Hekili** [comment]
May be fixed in upcoming beta build.

**Comment by Hekili** [comment]
I believe this is fixed, reopen or comment if you find it missing.
