### ISSUE TITLE
FPS Drop as Rogue when in combat

### ISSUE THREAD

**Issue by toddctc76** [Hekili/hekili#998]
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
When entering combat as any Rogue spec, there is a 20 - 40 FPS drop during the course of combat.  This occurs during combat with enemy NPCs, enemy players, and training dummies.  Once combat ends, the FPS goes back to normal.  I discovered this by disabling addons one-by-one and the only one that caused the FPS drop was Hekili.  I do not see the FPS drop on other classes.  With Hekili disabled, frames only drop about 5 in combat.

**To Reproduce**
- While Rogue (any spec), enter combat
- Notice frame drop and stuttering
- Exit combat and normal frame rate returns

**Expected behavior**
Expected frame rate drop, but only minor during combat; similar to other classes.
![nocombatFPS](https://user-images.githubusercontent.com/80970815/111802529-17c51600-889c-11eb-9887-f7b8a2bd2f5f.JPG)
![combatFPS](https://user-images.githubusercontent.com/80970815/111802538-1ac00680-889c-11eb-993d-08b24ff2fadc.JPG)

**Screenshots**
2 screenshots submitted - one in combat, the other not.  Notice the FPS difference in the bottom right of the screens.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:** 
build: v9.0.5-1.0.1a
level: 60 (60)
class: ROGUE
spec: subtlety

talents: deeper_stratagem
    enveloping_shadows
    premeditation
    prey_on_the_weak
    secret_technique
    shadow_focus
    soothing_darkness

pvptalents: none

covenant: venthyr

conduits: fade_to_nothing = 3
   lashing_scars = 5
   planned_execution = 3
   recuperator = 1

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   familiar_predicaments = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: azurevenom_choker = 1
    darkmoon_deck_voracity = 1
    ebony_death_shroud_belt = 1
    ebony_death_shroud_bindings = 1
    ebony_death_shroud_breeches = 1
    ebony_death_shroud_cloak = 1
    ebony_death_shroud_gloves = 1
    ebony_death_shroud_hood = 1
    ebony_death_shroud_spaulders = 1
    ebony_death_shroud_vest = 1
    grim_codex = 1
    quick_oxxein_ring = 1
    ritual_bone_band = 1
    sinfall_darkblade = 1
    sinful_aspirants_dagger = 1
    sinsoaked_waders = 1

legendaries: none

itemIDs: 173087, 173133, 177642, 178470, 178811, 178837, 178870, 180115, 180904, 180909, 180915, 180919, 180920, 180927, 180931, 180936

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Subtlety
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    mfd_points = 3
    priority_rotation = false
    solo_vanish = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
No error message from bugsack.

**Comment by Hekili** [comment]
Roll this into the open rogue ticket.
