### ISSUE TITLE
[Survival Hunter] There are questions about the rotation.

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#999]
Hello. I decided to try the survival hunter rotation and would like to clarify some questions. 
1.When taking the legendary power of the Memory of a Wildfire Cluster, why isn't Shrapnel Bomb often used in the AOE rotation? If I used Shrapnel Bomb myself without the recommendation of the addon, then I had a very large DPS in AOE. And if you strictly follow the rotation, then for some reason we use very little Shrapnel Bomb and while it comes to Shrapnel Bomb, there are no more targets, or they are almost dead.
2. Recommendations that are specified in the rotation of Use harpon and coordinated assault Overlap (Vision of Perfection) do not work. Maybe you should remove them altogether?
3. Well, in conclusion, I can say that the rotation seems to be broken. If, of course, I'm wrong, then clarify. Because it seems to me that the rotation does not support some of the legendary properties of items, conduits and covenants. They seem to be displayed in rotation, but if you look at the recommendations from the guides, and warcraftlogs play there in a completely different way, and preferences are given differently.

**Comment by Hekili** [comment]
I think you could have good conversations with the theorycrafters for Survival, in terms of what they present in guides vs. what they build into the SimC APL.  If that leads to changes to the sim profile, I'll match those changes at that time.
